### ISSUE TITLE
[EventCounters] Emit metrics for request execution time and request wait time

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#10020]
Add EventCounters for

- Request Execution Time
- Request Wait Time

Related https://github.com/aspnet/AspNetCore/issues/9486

**Comment by shirhatti** [comment]
@davidfowl Do you want to do these in preview6 as well?

**Comment by Tratcher** [comment]
Wait time?

**Comment by benaadams** [comment]
> Wait time?

More an IIS thing? How long the request is waiting in the queue

> ASP.NET\Request Wait Time – shows the amount of time (in milliseconds) that the last request was held in the queue.It should be close to 0 ms. If this indicator is usually greater than 1000 ms, the performance of the IIS server is suffering.

**Comment by davidfowl** [comment]
Wait time could be described as thread pool time

**Comment by anurse** [comment]
Do we have a clear idea of exactly how to measure "wait time"? If not, I'd rather hold off on it for now since we're pretty tightly scheduled. Execution time seems reasonable and can be fairly easily tracked.

**Comment by anurse** [comment]
Backlogging for 3.1 (this is a perfect candidate for the kind of paper-cut reduction work we want to do there). We do need to define how we'd measure "wait time", or just skip it for now.

**Comment by BrennanConroy** [comment]
We can revisit later
