### ISSUE TITLE
Provide guidance about moving large amount of data from JavaScript into Blazor.

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#10083]
### Describe the bug

When attempting to move "large" amounts of data from JavaScript into Blazor I get different errors at different times:

`wasm-0074c056:474 Uncaught (in promise) RangeError: Maximum call stack size exceeded`

`blazor.webassembly.js:1 Uncaught (in promise) Error: System.Reflection.TargetException: Non-static method requires a target.`

`blazor.webassembly.js:1 Uncaught (in promise) Error: System.BadImageFormatException: Method has zero rva`

### To Reproduce

Using version of ASP.NET Core 3.0.0-preview4-19216-03

JavaScript side:

```
function GetLongString() {
    return "a".repeat(6000000);
}
```

Blazor Side:

`((IJSInProcessRuntime)JSRuntime).Invoke<string>("GetLongString", null);`

Making the call from Blazor into JavaScript generates the errors in the browser console. Note that what I am really trying to do is to move pictures from JavaScript into Blazor by first serializign the pictures into base64 and them moving them to Blazor as suggested here: https://github.com/aspnet/Blazor/issues/527#issuecomment-401840036

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rxelizondo.
We're focusing our efforts mainly on to the Blazor Server Side model for the upcoming 3.0 release. We'll look into this after that.

**Comment by mkArtakMSFT** [comment]
Let's document what the patterns are for doing this.

**Comment by javiercn** [comment]
Here is a gist that explains how to do this https://gist.github.com/javiercn/f9c732b1d8e51634cbfd4cb0bce95b19

**Comment by javiercn** [comment]
This is done, I've filed a doc bug for the docs team to add it to the JS interop section
https://github.com/aspnet/AspNetCore.Docs/issues/16627
