### ISSUE TITLE
Nuget Package Microsoft.AspNetCore.App bug

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#10095]
Hello, my friends! I,m create new WebHostBuilder().UseStartup<Startup>().UseKestrel() etc...

I manually add the necessary packages. 
I run the application on the IISExpress web server and see "Now listening on: http://localhost:5000", This contradicts "launchSetings.json". I,m add metapackage Microsoft.AspNetCore.App 
and everything starts to work, with the same code and settings.

In addition, in the properties of the project in debugging, the ability to select the placement model is added. Why does it depend on the package? Why don't I command this? Is this some kind of agreement or did I get to the point and is it a bug?

and in VS 2017, when adding a controller, EntityFramevork, RazorDesigner and some other packages are installed and added to the project. This is not relevant to the topic, and does not require an answer if it was intentionally designed by you.

**Comment by terrainkognito2017** [comment]
VS 2019, .Net Core 2.2,

**Comment by terrainkognito2017** [comment]
public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
#if DEBUG
                    .AddJsonFile("appsettings.Development.json", true, true)
#else
                    .AddJsonFile("appsettings.json",true,true)
#endif
                .Build();
            var host = new WebHostBuilder()
                .UseStartup<Startup>()
                .UseKestrel()
                
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddConsole();
                })
#if DEBUG
                .UseWebRoot(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot"))
#else
                .UseWebRoot(Path.Combine(Directory.GetCurrentDirectory(), "dist"))
#endif
                .UseConfiguration(config)
                .Build();
            host.Run();
        }

**Comment by terrainkognito2017** [comment]
<PropertyGroup>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <AssemblyName>Client</AssemblyName>
    <RootNamespace>Client</RootNamespace>
  </PropertyGroup>

**Comment by terrainkognito2017** [comment]
if change OutOfProcess , i,m see error "Failed to bind to address http://127.0.0.1:5000: address already in use." 
I understand why this is happening, but I don’t understand why installing the package solves this problem.

**Comment by Tratcher** [comment]
@jkotalik missing ANCM in-proc handler?

**Comment by Tratcher** [comment]
@terrainkognito2017 IIS Express requires a call to either UseIIS or UseIISIntegration.

**Comment by Tratcher** [comment]
Out of proc has this piece of magic to call UseIISIntegration for you:
https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IISIntegration/src/IISHostingStartup.cs

**Comment by jkotalik** [comment]
Closing as the customer hasn't responded, feel free to open another issue if you are still having issues.
