### ISSUE TITLE
ForbidResult is not converted to ProblemDetails like NotFoundResult or any other StatusCodeResult

### ISSUE THREAD

**Issue by altso** [dotnet/aspnetcore#10120]
`ForbidResult` is not converted to `ProblemDetails` like `NotFoundResult` or any other `StatusCodeResult`.

### To Reproduce
See sample controller:
```cs
[HttpGet("{id}")]
public ActionResult<string> Get(int id)
{
    if (id < 0)
    {
        // works as expected and returns ProblemDetails:
        // {"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"8000095c-0000-fb00-b63f-84710c7967bb"}
        return NotFound();
    }

    if (id > 100)
    {
        // empty response without ProblemDetails
        return Forbid();
    }

    return "value";
}
```
Full repo: https://github.com/altso/ForbidProblemDetails/blob/master/Controllers/ValuesController.cs

### Expected behavior
I would expect `ForbidResult` to be 'converted' to `ProblemDetails` like many other results that produce HTTP status code greater than 400.

### Additional context
`ApiBehaviorOptions.ClientErrorMapping` dictionary _does_ contain an entry for HTTP 403, but it's never used.
https://github.com/aspnet/AspNetCore/blob/b03bca15dec61b83c318106cee6f0986b2fea8de/src/Mvc/Mvc.Core/src/DependencyInjection/ApiBehaviorOptionsSetup.cs#L59-L63

`ClientErrorResultFilter.OnResultExecuting()` checks action result object for `IClientErrorActionResult` implementation and `ForbidResult` _does not_ implement this interface.
https://github.com/aspnet/AspNetCore/blob/b03bca15dec61b83c318106cee6f0986b2fea8de/src/Mvc/Mvc.Core/src/Infrastructure/ClientErrorResultFilter.cs#L40-L43
https://github.com/aspnet/AspNetCore/blob/b03bca15dec61b83c318106cee6f0986b2fea8de/src/Mvc/Mvc.Core/src/ForbidResult.cs#L16
https://github.com/aspnet/AspNetCore/blob/b03bca15dec61b83c318106cee6f0986b2fea8de/src/Mvc/Mvc.Core/src/StatusCodeResult.cs#L15
https://github.com/aspnet/AspNetCore/blob/b03bca15dec61b83c318106cee6f0986b2fea8de/src/Mvc/Mvc.Core/src/NotFoundResult.cs#L14

```
> dotnet --version
2.2.100
```

**Comment by pranavkm** [comment]
This was intentional. `ProblemDetails` is specifically returned for status code returning action result. `Forbid` isn't one of those - it calls in auth. Depending on how your app is set up, you might see a a browser redirect (cookie auth does this) to the login screen.

**Comment by altso** [comment]
Thanks for the explanation. In my specific case I am hosting in IIS and would prefer `ProblemDetails` in the response.

A 403 mapping in `ClientErrorMapping` dictionary also adds some confusion...

If `Forbid` is designed to work that way, I do not see this behavior documented anywhere.

Please feel free to close this issue if you do not plan acting on that.
