### ISSUE TITLE
[Discussion] TestServer no longer preserves ExecutionContext and AsyncLocals between client and server

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#10134]
**Note: This change affects test code using [`TestServer`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0) only.**

Starting in ASP.NET Core 3.0 Preview 6, the [`ExecutionContext`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.executioncontext?view=netcore-3.0) will no longer be preserved when making HTTP requests to `TestServer`.

As a result of this change, the `ExecutionContext` in the _calling code_ will not be available to the _server code_. This means the following values which use `ExecutionContext` as their underlying storage will not be preserved when performing an HTTP request over `TestServer`:

* [`Thread.CurrentCulture`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.currentculture?view=netcore-3.0)
* [`CultureInfo.CurrentCulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=netcore-3.0)
* [`CultureInfo.CurrentUICulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentuiculture?view=netcore-3.0)
* [`Activity.Current`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.current?view=netcore-3.0)
* [`Thread.CurrentPrincipal`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.currentprincipal?view=netcore-3.0)
* Other values which use [`AsyncLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netframework-4.8) for storage.

If the previous behavior is required by your test code, you can restore it by setting the `PreserveExecutionContext` property on `TestServer` to `true`:

```csharp
var server = new TestServer(webHostBuilder) 
{
	PreserveExecutionContext = true;
};
```

------

This is the discussion issue for https://github.com/aspnet/Announcements/issues/358.

**Comment by slang25** [comment]
Was the motivation for this better perf during tests?

**Comment by olivier-spinelli** [comment]
Thank you! Fighting against the AsyncLocal will make hideous implicit-based-architecture less common. This is welcome!

**Comment by slang25** [comment]
Ah, I think I misunderstood the change. It won't flow from your tests to the server code, I thought it wouldn't preserve ExecutionContext within the server code, which would be problematic in places. Ignore me, this change makes complete sense.

**Comment by anurse** [comment]
@slang25 Correct, this is about flowing from the client to the server. It's not a perf thing, it's a correctness thing. And yeah, it generally makes sense because you are testing an HTTP request, and HTTP requests generally don't flow `AsyncLocal` values across them (since they're cross machine!) :).

The specific motivation is that flowing execution context actually **breaks** `IHttpContextAccessor` if you have "nested" HTTP calls. Imagine you are testing a multi-app system using `TestServer`:

```
Client -> Server A -> Server B
```

Both servers are hosted in `TestServer` and you're giving the `HttpClient` provided by `TestServer` to `Server A` so that it can "call" `Server B`. Testing authentication flows often requires this, as do some microservice systems.

During an invocation to `Server A`, both servers are **sharing** the `IHttpContextAccessor` value, which makes all kinds of mess :).

**Comment by slang25** [comment]
Thanks, that makes complete sense. I think I even ran into this trying to set the identity server backchannel client to a `TestServer` client and getting issues.

**Comment by anurse** [comment]
> I think I even ran into this trying to set the identity server backchannel client to a `TestServer` client and getting issues

Exactly! Glad to hear it will help :).
