### ISSUE TITLE
dotnet dev-certs https --trust produces new certificate on every run

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [dotnet/aspnetcore#10220]
### Describe the bug
We have multiple Windows VMs running in AWS and hosting dotnet application with self signed dev certificate. 

On one VM we got an issue with creating new certificate - multiple certificated are produced and none of them recognized by dotnet host when trying to bind to HTTPS

### To Reproduce
1. run command and confirm propmt
![image](https://user-images.githubusercontent.com/11254187/57671165-ef43b380-7655-11e9-97b2-10563caa7bac.png)
2. run command again and see another prompt
![image](https://user-images.githubusercontent.com/11254187/57671188-071b3780-7656-11e9-8720-92d1412c6a05.png)

### Expected behavior
Only one certificate is registered and dotnet can bind to HTTPS

Here is a list of trusted certificates
![image](https://user-images.githubusercontent.com/11254187/57671279-64af8400-7656-11e9-9f41-a8c4190d8e4a.png)

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.106\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by blowdart** [comment]
Creating multiple certificates is expected and what it's designed for.

When you're binding what host names are you binding too? I find it doubtful it's going to be "localhost" inside a VM.

**Comment by EvgenyMuryshkin** [comment]
I am binding to *, which works on other machines without issues
```
adf.Addresses.Add($"https://*:5003");
```

**Comment by EvgenyMuryshkin** [comment]
Also, if I run command line anywhere else - it said that certificate is already registered and does not produce a new one
![image](https://user-images.githubusercontent.com/11254187/57736799-b0147180-76ec-11e9-8c6f-ecad284d6d9b.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. After another review of this issue it seems this is not a scenario the dev-certs tool is intended for. Given that there are no much concerns regarding current behavior form the community similar to this, we're closing this issue.
