### ISSUE TITLE
Does renaming from`.cshtml` to `.razor` behave correctly in the editor?

### ISSUE THREAD

**Issue by jeffwlandry** [dotnet/aspnetcore#10265]
using vs 2019 preview 3 and CORE 3.0 preview 5.

I created a class in a new folder "case".  Called it _caseDetailLayout.razor.  Building project results in errors.  Moved file to "shared" folder, builds without errors.

Must a layout be in the shared folder?

solution contains layout in case folder
![image](https://user-images.githubusercontent.com/50668541/57783619-721f4980-76fc-11e9-8420-50d8e20cc8c9.png)

layout code. LayoutComponentBase not recognized
![image](https://user-images.githubusercontent.com/50668541/57783630-79deee00-76fc-11e9-8942-be97269adc1d.png)

build errors
![image](https://user-images.githubusercontent.com/50668541/57783648-7fd4cf00-76fc-11e9-8981-e8bc323f1dda.png)

LayoutComponentBase with full namespace recognized
![image](https://user-images.githubusercontent.com/50668541/57783656-8400ec80-76fc-11e9-9929-6e04ee8f558a.png)

build errors
![image](https://user-images.githubusercontent.com/50668541/57783669-882d0a00-76fc-11e9-8144-d82bf65344d0.png)

Final, step is move layout file to shared folder, now solution builds without errors.

Jeff

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jeffwlandry.
Can you please share the `csproj` file? Also, did you create the file as `.cshtml` and then renamed it to `.razor`?

**Comment by jeffwlandry** [comment]
Artak:

I created by adding a class called xxx.razor when asked to name it.

In order to try a clean recreation, I created a new solution by creating a blazor template project.  I added a page and a layout and a new _imports file in a new folder (cases).  I’ve attached it to this email but it’s not going to be of use for the reason stated later.

As I was working through this process, I got the behavior originally mentioned.  That is the build started failing and it didn’t recognized LayoutComponentBase.  However, the last thing I added was _imports in the cases folder.  Magically at that point it started working.

Now I can’t get it to fail.

I gave up on trying to organize things into folders and moved on, so I will have to try and recreate the original failure.  If I can successfully recreate this I will be happy to send you the project.

I guess the basic question here is should I be able to create a new folder in a blazor server side project and put pages and layouts in it.  Clearly I was just trying to get some organization into what I am doing.  Along the lines of issues, I’m finding that if I create .razor in one folder and move to another I get errors seeming associated with the namespace in the generated files not conforming to the new folder name and just changing said files doesn’t fix anything.  Again, these errors came along with the issue submitted, so if I can recreate them I will send everything along.

Thank you and if I can’t recreate this, then I appologize for jumping the gun and opening an issue.

Jeff



________________________________

**Comment by jeffwlandry** [comment]
Links to onedrive files which were too large to attach
https://1drv.ms/u/s!Aq_4W1bjkBTqhPBAyZnsdneYjGZoSA
https://1drv.ms/u/s!Aq_4W1bjkBTqhPBBNV8HUhG7M76zYQ
https://1drv.ms/u/s!Aq_4W1bjkBTqhPBCuMpX83vWyp8UEQ

Attached is the entire project which demonstrates issue.  Also attached is a steps recorder recording of the problem occurring.  Finally attached is the project used in the recording after the recording ended.

Basically this is the Blazor project template.  I’m not much of a theory person, so I’m just starting with it and adding what I need.  When I figure out what is going on, I’ll get rid of the unneeded template stuff.

The case folder is the source of the problems.  You will notice the files there reference “awctsBlazorComponent” namespace.  This is because I solved my problem previously by moving the layout to the shared folder and the other case files to a razor library called awctsBlazorComponent.

To create this solution showing the problem I added the case folder and dragged the files from where they worked into the case folder.  I can’t figure out why the awctsBlazorComponent namespace still works as I can’t find any reference to it in any files other than the component references in the cs files.

I finally recreated the original issue:
[cid:image002.png@01D50C97.46064A30]

Note: closing and reopening solution containing project causes undefined  LayoutComponentBase to now be defined.

Jeff

**Comment by NTaylorMullen** [comment]
Nothing wrong with renaming .cshtml -> .razor. The reason why things are exploding unexpectedly is because of the folder name `case`. If you rename the folder to its uppercase variant `Case` things work properly.

Reason why `case` explodes is because the files generated C# `namespace` ends in the C# keyword `case`:
![image](https://user-images.githubusercontent.com/2008729/58668453-d3930b00-82ed-11e9-88dc-115029ce758f.png)

With @rynowak's suggestion I did a thought experiment and added a C# file to the `case` directory and it also exploded in similar fashion:
![image](https://user-images.githubusercontent.com/2008729/58669471-2f12c800-82f1-11e9-98be-75ee49e81127.png)

Going to backlog this because it's a super edge case.

**Comment by jeffwlandry** [comment]
Thank you for taking the time to investigate this.  In retrospect, I should have realized the namespace was conflicting with the reserved word.

Because of the seemingly hidden generated files I was unclear of how to rename the namespace, so rejected the attempt although I did think about it.

Your conclusion and action are appreciated.

Thank you again,
Jeff landry



________________________________

**Comment by SteveSandersonMS** [comment]
Closing as answered
