### ISSUE TITLE
ViewComponent view locations are unaffected by IViewLocationExpander

### ISSUE THREAD

**Issue by asbjornu** [dotnet/aspnetcore#10277]
### Describe the bug

The interface `IViewLocationExpander` makes it possible to adjust the folders in which views are located. This works for most types of views except the ones used by view components. As the `ViewComponent` view location is [hard coded in a constant string](https://github.com/aspnet/Mvc/blob/e985fa5d423968f36a651a354d9c953192c52532/src/Microsoft.AspNet.Mvc.ViewFeatures/ViewComponents/ViewViewComponentResult.cs#L20
) and the methods inside the `ViewViewComponentResult` are impossible to override, `ViewComponent` views will have to reside in the location `Components/<ViewComponentName>/<ViewName>` with the only option of prepending or appending something to this constant string.

### To Reproduce
1. Create a class called `MyViewComponent` inheriting from the `ViewComponent` class in a folder that doesn't adhere to default `ViewComponent` location, for instance in the project root.
2. Create a view called `Default.cshtml` adjacent to the `MyViewComponent` class.
3. `return View("Default");` in the `InvokeAsync` method of the `MyViewComponent` class.
4. Render `MyViewComponent` with `@await Component.InvokeAsync("MyViewComponent")` in the `Home` view, for instance.
5. Visit the `Home` route in a browser and witness the error `The view 'Components/MyViewComponent/Default' was not found. The following locations were searched: …`

### Expected behavior
I expect that an implementation of `IViewLocationExpander` should be able to adjust the view location of all types of views, including `ViewComponent` views.

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @asbjornu.
Given that we've heard this ask several times now, we're going to try to squeeze this in to 3.1 release.

**Comment by mkArtakMSFT** [comment]
@asbjornu feel free to send us a PR, if you'd like, and we'll consider it.

**Comment by asbjornu** [comment]
I would like to provide a PR, but some guidance on how this should work would be nice. I'm also unable to build `Mvc.sln` on macOS 10.14.4:

>~/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(48,5): error : Path './src/submodules/MessagePack-CSharp' doesn't point at a valid Git repository or workdir. [./src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do in the near future.
