### ISSUE TITLE
Page Binding to Class With Parameters Throws Exception

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#10330]
Using ASP.NET Core 2.2 Razor Pages. My page binds to the object InputModel. If I add a parameter to that class, and initialize the class in the constructor, I get this error:

> An unhandled exception occurred while processing the request.
> InvalidOperationException: Could not create an instance of type 'SoulAlignmentReadingFormModel+InputModel'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. **Alternatively, set the 'Input' property to a non-null value in the 'SoulAlignmentReadingFormModel' constructor.**

It clearly states that it should work if the field is set in the constructor, yet it doesn't.

Here's the code.

    public class SoulAlignmentReadingFormModel : PageModel
    {
        private ConstantDataProvider _constantData;

        public SoulAlignmentReadingFormModel(ConstantDataProvider constantData)
        {
            _constantData = constantData;
            Input = new InputModel(constantData);
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public InputModel(ConstantDataProvider constantData)
            {
                Country = new InputList(constantData.Countries);
            }

            [BindProperty]
            public InputList Country { get; set; }
        }
    }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mysteryx93.
This is not something we support at the moment but we will consider it in a future release.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
