### ISSUE TITLE
Single project template for Razor Pages and MVC apps

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#10345]
- Single project template
- Option to select view engine: Razor Pages or Razor Views (MVC)
- Alias existing "mvc" template to this and make it pre-select "Razor Views" for option above:
  - Razor Pages: `dotnet new webapp` or `dotnet new razor`
  - MVC: `dotnet new webapp --mvc `

**Comment by isaac2004** [comment]
@mkArtakMSFT @ryanbrandenburg  as part of this, does it make sense to refactor the folders for the templates. Right now there is
![image](https://user-images.githubusercontent.com/8878502/60921742-3cfd2680-a269-11e9-8228-bb89305f5b1f.png)

RazorComponents is getting renamed to BlazorServerWeb, and I think doing the following would make the templates more clear

- Merge StarterWeb-CSharp into RazorPagesWeb 
- Add conditionals based on above option to use different files (if MVC, use MVC files etc)
- Rename StarterWeb-FSharp to MVCWeb-FSharp

This would make the templates more clear for future contribution. Let me know what you think and include whoever in the convo you need

**Comment by mkArtakMSFT** [comment]
@isaac2004 I would not start on this yet. Given the complexity this would introduce, let's wait for now. Things may change by the time we get there.

**Comment by mkArtakMSFT** [comment]
Closing as we don't think this will add much value.
