### ISSUE TITLE
dotnet watch - Run modified tests instead of all tests

### ISSUE THREAD

**Issue by AlexTeixeira** [dotnet/aspnetcore#10366]
Hi,

### Current Behavior

Currenlty **dotnet watch** works good, but I think some improvements can be done.

When you save a file and watch is active, all project tests are runned.

But dotnet watch have the filter option to watch only specific **class** or **test method** : 
`
--filter "FullyQualifiedName~Project.Namespace.UserService_Test"`

### Expected Behavior 

**Scenario:** Developer was updating one or multiples test
**Given:** I save the changes made in appropriated files
**Then:** Plugin should run only the modified tests

**Exemple :** 

- I update the tests **User_WantTobeCalled_ShouldHaveNumberPhone** and **Order_AddItem_ShouldhaveNewItem**
- I save the files **UserTest** and **OrderTest**
- Only **User_WantTobeCalled_ShouldHaveNumberPhone** and **Order_AddItem_ShouldhaveNewItem** should run 

This will improve tests feedback and avoid CPU overhead on running tests multiple times.

I think this features can be split in two steps.

### First Step

Update the whole files instead of the updated tests. Plugin should be able to detect the updated files and add it in **dotnet watch test --filter**

### Second Step

Try to get the modified test to run only the tests instead of the whole class under the file that was updated. 
I think this one is quite more difficult to achieve.

Currently, I don't have enough time to have a look to this feature. But I think it can be a good enhancement.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AlexTeixeira.
Do you have any design in mind to share some details about it?
