### ISSUE TITLE
two way binding does not yet handle color picker in blazor

### ISSUE THREAD

**Issue by mohankumar91** [dotnet/aspnetcore#10376]
I have the the following in my index.razor

```
<h2> Color Picker </h2>
<input type="color" name="favcolor" bind="@colorValue" />
<input type="text" name="favcolor" bind="@colorValue" />
```

```
@functions {
protected string colorValue = "c10e0eff";
}
```

I have updated the color value with this format(#RRGGBBAA) in text value not updated the color  field

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by ElementZ-Zareth** [comment]
@mohankumar91 your colorValue might need to be = "#c10e0e" 
1.) The HTML5 color picker doesn't support alpha values.
2.) The HTML5 color picker value included the # symbol, so the initial string should contain it as well.

I'm working on a Sudoku game that allows the user to choose colors to associate to each number.  I've bound the values of each number to a list of strings.  When you choose a new color, the corresponding block changes.  Here's some of my code, I hope it helps:

Under the HTML section:

`@for (int x = 0; x < size; x++)
{
    var index = x;
    <input type="color" @bind="Colors[index]" />
    <label for="head">@index</label>
    @if (index % squareSize == (squareSize - 1))
    {
        <br />
    }
}`

Under @code section:

`public List<string> Colors;
public void CreateColors()
    {
        Colors = new List<string>();
        for (var y = 0; y < size; y++)
        {
            Colors.Add($"#{(y * size).ToString("X")}{(y * size).ToString("X")}{(y * size).ToString("X")}");
        }
    }`

If you need anymore help with this, let me know.

If an alpha value is needed, it might need to be in a separate input value.

**Comment by Treemendus** [comment]
@mohankumar91 

`<h2> Color Picker </h2>
<input type="color" name="favcolor" bind="@colorValue" />
<input type="text" name="favcolor" bind="@colorValue" />`

Your "bind" attribute is missing the "@" symbol. It should be:

`<input type="color" name="favcolor" @bind="colorValue" />`

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @Treemendus!
