### ISSUE TITLE
Rationalize Razor Compiler diagnostic IDs

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#10382]
When we merged the components prototype code into the Razor Compiler codebase we basically kept it as-is, but our choices of diagnostic ids are kinda wacky. We picked unusual or large numbers to try and avoid collisions with the mainline compiler, resulting in some unpredictable numbers. We should do a pass and make sure what we have is sane.

Also we should look at the components analyzer that uses the `BLXXXX` numbering scheme. It should probably be `RZXXXX` for consistency.

**Comment by pranavkm** [comment]
Changing either of these is going to cause needless headache for users migrating from 3.0. We'll live with our poor life choices.
