### ISSUE TITLE
[Helix] enable Microsoft.AspNetCore.Mvc.FunctionalTests

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#10423]
src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj

This test project does not work in Helix and is currently disabled because it has a dependency on the layout of the source code in this repo.

Recommendation for updating: see aspnet/Extensions#1697

**Comment by HaoK** [comment]
Skipped tests on helix:
  Link/Script in HtmlGenerationTest.WebPagesData

HtmlGenerationWebSite_GeneratesExpectedResultsNotReadyForHelix
HtmlGenerationWebSite_GenerateEncodedResultsNotReadyForHelix
TagHelpersTest.CanRenderViewsWithTagHelpersNotReadyForHelix

Also revert:
```c#
        public async Task CompilationFailuresFromViewImportsAreListed()
            var expectedCompilationContent = "public class Views_ErrorFromViewImports_Index : "
```

**Comment by HaoK** [comment]
Keeping this bug open until skipped tests are reenabled

**Comment by HaoK** [comment]
Test failures tracked https://github.com/dotnet/aspnetcore/issues/29597
