### ISSUE TITLE
[Helix] enable Microsoft.AspNetCore.Analyzers.Test

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#10422]
src/Analyzers/Analyzers/test/Microsoft.AspNetCore.Analyzers.Test.csproj

This test project does not work in Helix and is currently disabled because it has a dependency on the layout of the source code in this repo.

Recommendation for updating: see https://github.com/aspnet/Extensions/issues/1697

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/18867
