### ISSUE TITLE
[Test utils] create more granular skip conditions for Linux

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#10428]
As the matrix of Linux test platforms expands, is has become necessary to skip tests on specific versions of Linux which do not meet system requirements for certain features of ASP.NET Core.

For example, HTTP/2 does not work on Debian 8 because the version of OpenSSL it uses is too old.

Desired usage:
```csharp
[ConditionalFact]
[OSSkipCondition(KnownRuntimeIdentifiers.Debian8)]
```

**Comment by dougbu** [comment]
We're actually moving away from granular skips and toward quarantining tests across the board. We also seem to have the skip conditions we need when tests don't run on one or more platforms.
