### ISSUE TITLE
Influencing HTML Head from a Blazor component

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#10450]
In Blazor apps the root of the HTML document is typically controlled by the layout component. If other components need to influence the contents of the HTML Head tag (e.g. to add or change Meta or Title tags) there isn't really an established patterns to do that today.

**Comment by Andrzej-W** [comment]
Hopefully it will work during prerendering in Blazor client side app. It is needed for SEO and social sites integration.

**Comment by roduman** [comment]
Very lacking this functionality today

**Comment by vertonghenb** [comment]
Sometimes it's even needed to adjust the <body> tag (most of the time the css classes due to theme requirements. For example the case where you open/close sidebars and it's based on the css class of the body tag. Currently I use the following code snipped to do so via Interop:
```js
window.application = {
    toggleAsideOnMobile() {
        const className = 'kt-aside--on';
        const body = document.getElementsByTagName('body')[0];
        const aside = document.getElementById('kt_aside');
        body.classList.toggle(className);
        aside.classList.toggle(className);
        return true;
    },
    toggleTopbarOnMobile() {
        const className = 'kt-header__topbar--mobile-on';
        const body = document.getElementsByTagName('body')[0];
        body.classList.toggle(className);
        return true;
    }
};

```

**Comment by chucker** [comment]
@vertonghenb unless it _has_ to be the `<body>` tag, you don't need JS for that. Inside the components, you can simply emit different CSS classes.

Blazor doesn't have built-in tooling for that, but you can use something like [CssBuilder](https://github.com/EdCharbeneau/CssBuilder).

**Comment by vertonghenb** [comment]
@chucker Yes, I know but it _has_ to be the `body` tag.

**Comment by vertonghenb** [comment]
Another use case for this is adding a `css` file for a specific page.

**Comment by vertonghenb** [comment]
@TrabacchinLuigi I don’t know that was possible, awesome! Thanks for sharing!

**Comment by dotkiwi** [comment]
@TrabacchinLuigi  Hmm, I'm not sure if this would work, please correct me if I'm wrong. Since components can't contain <script> tags, if you place the <body> tag inside a component then you have nowhere to place <script> tags. <script> tags are meant to be in the <body> are they not?

**Comment by vertonghenb** [comment]
> @TrabacchinLuigi Hmm, I'm not sure if this would work, please correct me if I'm wrong. Since components can't contain `<script>` tags, if you place the `<body>` tag inside a component then you have nowhere to place `<script>` tags. `<script>` tags are meant to be in the `<body>` are they not?

That's a good argument!

**Comment by TrabacchinLuigi** [comment]
@dotkiwi @vertonghenb as far as i know script tags can be placed in head tag, inside body tag or after it, it just depends on when you want that script to be available and start executing, in this case it should not matter, the page is very lightweight and the majority of the content is downloaded later by Blazor ...

**Comment by zachneu** [comment]
Is there anyway now to add script and css references from a Razor component now? I have several Razor components with their own JavaScript files and css files. If i use these components i'll have to link to their JavaScript and css files in "index.html" manually. Is there some way this can be done from the Razor component?

**Comment by DamianEdwards** [comment]
Another use case to document that the lack of this feature is impacting right now is web analytics solutions. Today, in systems like Application Insights, page views are tracked via the JavaScript SDK which can be configured to auto-track route changes and report those as page views (no problem there). The issue is the document title is used as the page view name, so looking at page views in your analytics dashboard just shows all views being for the application home page (as the title never changes).

**Comment by muratgur** [comment]
> Is there anyway now to add script and CSS references from a Razor component now? I have several Razor components with their own JavaScript files and css files. If i use these components i'll have to link to their JavaScript and css files in "index.html" manually. Is there some way this can be done from the Razor component?

This is a very reasonable request. How can I add style links inside a component? FAQ page needs custom style for example. The Head tag is in _Host.cshtml and as far as I understand there is no way right now?

**Comment by GioviQ** [comment]
@muratgur you can see how I can achieve this here https://github.com/enkodellc/blazorboilerplate/blob/development/src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo/ThemeTagHelperComponent.cs

**Comment by dodyg** [comment]
This feature will be very useful in supporting RTL and LTR layout switching.

**Comment by walterlv** [comment]
@GioviQ I've tried this component.

But this only works in the Browser and we can find that the title changes in the browser's tab. But the title **WILL NOT UPDATE** if someone tries to share a link through some social apps, because the title is updated using the Web Socket but the social apps only fetch the title once and will not update further.

**Comment by GioviQ** [comment]
@walterlv I think you're right, so what is the solution?

**Comment by SPWwj** [comment]
need a way for server to render prerender component base on first time request url. this will help seo to fetch necessary info, meanwhile allow user to serve the seamlessly

**Comment by Ecroyd** [comment]
To add to the example by @vertonghenb and when using MapFallbackToPage, the _Host.cshtml file is evaluated, then if present, the cshtml layout file is evaluated. In addition, a dependency injected service can be accessed by the blazor ServerPrerendered, and the layout page. 

So to influence the HTML Head when using ServerPrerendered, you make sure you are constructing the HTML Head in a cshtml layout file. You then use a transient dependency injected service to carry the value from Blazor to the layout.

> @vertonghenb I don't see why anything need to be modified to achieve what you ask :
> 
> ```
> File _Host.cshtml
> 
> <!DOCTYPE html>
> <html lang="en">
> ...
> </head>
> @(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
> </html>
> ```
> 
> Then
> 
> ```
> File App.razor
> 
> @code { ... }
> <body class="@someClasses">
> <Router AppAssembly="@typeof(Program).Assembly">
> ...
> </Router>
> </body>
> ```
