### ISSUE TITLE
Add a .vsconfig file to the repo root

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#10462]
See https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

Work required: 
- [ ] convert https://github.com/aspnet/AspNetCore/blob/master/eng/scripts/vs.json into the proper format and ensure InstallVisualStudio.ps1 still works.
- [ ] review the list of required workloads and see if we can remove any. Candidates:  
  * Microsoft.VisualStudio.Workload.VisualStudioExtension, 
  * Microsoft.VisualStudio.Component.Azure.Storage.Emulator
  * all of the old Microsoft.Net.Component.(version).TargetingPack workloads

**Comment by rynowak** [comment]
That's pretty dope that they added this 👍

**Comment by JunTaoLuo** [comment]
Unassigning myself since this is backlogged

**Comment by dougbu** [comment]
@Pilchie fixed this in f34033a415f5
