### ISSUE TITLE
Server-side Blazor + more SignalR

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#10475]
How do you use SignalR from a server-side Blazor app?

**Comment by danroth27** [comment]
https://github.com/aspnet/AspNetCore/issues/10407

**Comment by Alienroid** [comment]
Following this.

I can create my own signalr core connection (ie endpoints.MapHub...). It works fine on localhost. However, when I deploy to Azure. I get all kinds of errors.

1) Error: The circuit failed to initialize. (this happens when using Azure Signalr service)
2) System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions.  ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions. at System.Net.Http.ConnectHelper.ConnectAsync (This happens using webapp's Websocket)

Any additional information would help, thanks!

**Comment by danroth27** [comment]
@Alienroid What does your SignalR client code look like?

**Comment by Alienroid** [comment]
Hi Dan: Below are my steps of getting it working on localhost.

**Server code** (no magic here)
1) startup.cs:
ConfigureServices, I've added:
`            services.AddSignalR(hubOptions =>
            {
                hubOptions.EnableDetailedErrors = true;
            });`

Configure, I've added:
`
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapBlazorHub();                
                endpoints.MapFallbackToPage("/_Host");
                endpoints.MapHub<GPlatformHub>("/gphub");
            });
`

2) I created a SignalR Core hub: GPlatformHub : Hub

**My Client code follows:**

In AppLayout.razor, I added a component called **NetworkManager**

```
<NetworkManager>
        <AuthorizeView>
            <Authorized>
               @Body
            </Authorized>
            <NotAuthorized>
               @Body
            </NotAuthorized>
        </AuthorizeView>
</NetworkManager>
```
Network Manager does all the signalr connection stuff:

`
@using System
@using System.Security.Claims
@using Microsoft.AspNetCore.SignalR.Client
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@implements IDisposable

    <CascadingValue Value=@this Name="NetworkMgr">
        <CascadingValue Value="@connection">

                        @ChildContent

        </CascadingValue>
    </CascadingValue>


@code {
    [Parameter] public RenderFragment ChildContent { get; set; }

    HubConnection connection = null;

    [CascadingParameter]
    private Task<AuthenticationState> authenticationStateTask { get; set; }

    private AuthenticationState authState { get; set; }
    private ClaimsPrincipal user { get; set; }

      //+ test code
    public string testCode = "";
    //- test code
    private bool debugOn { get; set; } = true;

    protected override async Task OnInitializedAsync()
    {

        authState = await authenticationStateTask;
        user = authState.User;

        if (user.Identity.IsAuthenticated)
        {
            Console.WriteLine("The user is authenticated.");
            await StartSignalR();
        }
        else
        {
            Console.WriteLine("The user is NOT authenticated.");
            StopSignalR();
        }

    }
    public void Dispose()
    {
        if (connection != null)
        {
            connection.Remove("TestCb");
            StopSignalR();
        }
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {

    }

    // signalr
    private async Task StartSignalR()
    {
        connection = new HubConnectionBuilder()
                .WithUrl("https://localhost:44306/gphub")
                .WithAutomaticReconnect()
                .Build();

        connection.On<string>("TestCb", testCb);

        await connection.StartAsync();
    }
    private async Task StopSignalR()
    {
        if (connection != null)
        {
            connection.StopAsync();
            connection.DisposeAsync();
            connection = null;
        }

    }

    //+  SIGNALR Callbacks
    private async void testCb(string msg)
    {
        testCode = msg;
        this.StateHasChanged();
    }

}`


Then, any child components that wants to use SignalR connection, they can use it. An example:

`
@using Microsoft.AspNetCore.SignalR.Client
@using Microsoft.AspNetCore.Components.Authorization
@using System.Security.Claims
@using Newtonsoft.Json
@using System
@implements IDisposable

    <div>
        @if (hConnection != null)
        {
            
        }
        else
        {
            <p>No Connection</p>
        }
    </div>

@code {
    //// Parameters
    [CascadingParameter]
    private Task<AuthenticationState> authenticationStateTask { get; set; }
    [CascadingParameter]
    protected HubConnection hConnection { get; set; }
    [CascadingParameter(Name = "GameClient")]
    public Client gameClient { get; set; }
    // wait challenge fragment
    [Parameter]
    public RenderFragment SplashScreen { get; set; }
    // for quit popup confirmation
    [Parameter]
    public MultiplayerGameState mpGameState { get; set; }
    [Parameter]
    public EventCallback<MultiplayerGameState> mpGameStateChanged { get; set; }

    //// local variables
    // security (connection needs identity)
    private AuthenticationState authState { get; set; }
    private ClaimsPrincipal user { get; set; }
 

    // test
        //[CascadingParameter]
    //public TestClient testClient { get; set; }
    private string testMsg { get; set; } = "";
    private bool debugOn { get; set; } = false;

    public void Dispose()
    {
        //hConnection.Remove("SetCommandCb");
        if (hConnection != null)
        {
            if (oppoSID != null)
            {
                hConnection.InvokeAsync("InformOppoDone", oppoSID, server.GameHostId); // inform other party the game exited
            }
            try
            {
                hConnection.Remove("GameReady");
                hConnection.Remove("OppoMove");
                hConnection.Remove("OppoDone");
                hConnection.Remove("ResyncGame");
            }
            catch
            {

            }

        }
    }
    protected override async Task OnInitializedAsync()
    {
        authState = await authenticationStateTask;
        user = authState.User;
        gameState = GameState.PLAYING;

        if (user.Identity.IsAuthenticated)
        {
            if (hConnection != null)
            {

                // register signalR
                hConnection.On<int>("GameReady", GameReady);
                hConnection.On<string>("OppoMove", OppoMove);
                hConnection.On<int>("OppoDone", OppoDone);
                hConnection.On("ResyncGame", ResyncGame);
                // test code
                //hConnection.On<string>("SetCommandCb", SetCommandCb);
                //await hConnection.InvokeAsync("SetCommand", "THIS WORKS!");
                //if (testClient!=null) { testClient.testid = 2; }

                
            }
            else
            {
                // connection null
            }
        }
        else
        {
            // not authenticated
        }
    }
    /* + SIGNALR*/

    /* - SIGNALR*/

}`

I removed lots of my code that's not related to this topic, but what I provided should be clear enough. Let me know if you need more information.

**Comment by Alienroid** [comment]
As I was writing above, I found out what the issue was. I followed signalr documentation: https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.0&tabs=visual-studio and I used incorrect url for HubConnectionBuilder. Previous version of Signalr didn't need to specify domain just the /hub.

connection = new HubConnectionBuilder()
            .WithUrl("**https://localhost:44306**/gphub")
            .WithAutomaticReconnect()
            .Build();

I created an app on Azure and I just tested it out. It works for the websocket case. I'll test with Azure Signalr service in the future. 

Thanks again! 

My code above works, so if anyone ask how to run more signalR on serverside Blazor, it works as it is, Don't need to wait until aspnetcore 5.

**Comment by MithrilMan** [comment]
FYI, whenever I run into this kind of System.Net.Sockets.SocketException (10013) exception, I first check if my port is for some reason excluded from dynamic range, with this command
`netsh interface ipv4 show excludedportrange tcp`

and it's always there, so for some reason the port I want is in an excluded range and I just change the port.
I'd like to know if there is a better way to understand what/why is excluded a specific port range

**Comment by mkArtakMSFT** [comment]
@anurse this is an ask we have from SignalR for 5.0.

**Comment by mrlife** [comment]
@mkArtakMSFT Is this being considered for 6.0?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
