### ISSUE TITLE
Very high consumption of the CPU when reading data from the database with async api

### ISSUE THREAD

**Issue by landryn** [dotnet/aspnetcore#10484]
### Describe the bug
The problem occurs when calling http methods in ASP Net Core application. In the process request, we connect to the sql server and read data. Problem occurs when using the asynchronous API to read data. It can be obtained when we host an application on IIS and IIS Express.

### To Reproduce
1. API: Microsoft.AspNetCore.App 2.2.0, Microsoft.EntityFrameworkCore 2.2.4, System.Data.SqlClient 4.6.1
2. Create Controller which inherits from ControllerBase
3. Run this code 
`[HttpGet] public async Task<ActionResult<string>> Get(){`
`var query = $"select TOP 1 * from ftBinDocuments ";`
`using (var cc = new SqlConnection(DbContextCommandExtensions.st))  {`
`using (SqlCommand command = cc.CreateCommand()){`
 ` command.CommandText = query;`
`  cc.Open();`
`using (var rd= await command.ExecuteReaderAsync()){`
`while (await rd.ReadAsync()){`
`}`
`}}`
`return "ok";`
`}`
4. We connect to MS Sql Server and read a lot of data.  The row size  is over 5-6 MB.
5. There is a lot of CPU usage during the execution of rd.ReadAsync ().

The problem disappears if we switch to synchronous api.

### Expected behavior
Low CPU usage.

### Screenshots

![cpu](https://user-images.githubusercontent.com/214203/58255603-a97d9e00-7d6d-11e9-861c-be91b17c7523.PNG)

**Comment by Eilon** [comment]
Tagging @sebastienros @ajcvickers

**Comment by davidfowl** [comment]
@landryn record a CPU profile and show the results in here.

**Comment by landryn** [comment]
@davidfowl - ok, I did it.
[Report20190524-0834.zip](https://github.com/aspnet/AspNetCore/files/3215446/Report20190524-0834.zip)

I am also enclosing the application's source code.

[WebApplication5.zip](https://github.com/aspnet/AspNetCore/files/3215453/WebApplication5.zip)
