### ISSUE TITLE
Refactoring support for Razor (.cshtml and .razor) files

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#10480]

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please dupe this with the work we do to cover this? Thanks.

**Comment by NTaylorMullen** [comment]
This is too broad an issue to begin with. Closing given it's not clear as to which refactoring scenarios we were trying to track without a dup

**Comment by mkArtakMSFT** [comment]
This was a dupe of https://github.com/dotnet/aspnetcore/issues/6112
