### ISSUE TITLE
Using .htaccess with .NET Core

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#10513]
I'm setting up a .NET Core 2.2 app on my Linux/Apache2 server but can't get .htaccess to work. I placed .htaccess at the root of the application, alongside all the other DLLs, and it contains URL redirect rules. However, those rules aren't working.

I saw this article about URL Rewrite Middleware
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.2

It states:

> Use URL Rewriting Middleware when you're unable to use the following approaches: Apache mod_rewrite module on Apache Server

So my question is, can I use .htaccess and mod_rewrite on Linux with .NET Core or not?

**Comment by Eilon** [comment]
Typically you'd use Kestrel as the web server on Linux, not Apache. I believe you can use Apache as a reverse proxy, or to host additional static assets, but not for hosting the .NET Core app.

The ASP.NET Core Rewrite Middleware can load certain compatible rewrite rules, such as ones from IIS or Apache. So, instead of using Apache mod_rewrite, you can load the same type of rules into the ASP.NET Core feature. (There could conceivable be some differences, because it's unlikely to be 100% compatible.)

**Comment by Eilon** [comment]
Here's some more info on using Apache with ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2

And some of the other docs above/below that in the Table of Contents should be illuminating.

**Comment by mysteryx93** [comment]
They highly recommend running a web server like Apache2 behind Kestrel; otherwise Kestrel on its own can only host a single application on the server.

In the doc, they set the rewrite rules directly in the Apache2 config file. You say you can load rewrite rules from the middleware, but they say Middleware's performance is lower than handling rewrites at the Apache2 or IIS level and should only be done if it can't be done on the web server directly.

Apart from these two options, can .htaccess be used or not?

**Comment by Tratcher** [comment]
> They highly recommend running a web server like Apache2 behind Kestrel

Correction: you run Kestrel behind Apache2 to enable hosting multiple applications.

**Comment by Eilon** [comment]
Here's my understanding:

If you want to use an actual `.htaccess` file, you need to use Apache at whatever node/server you want to use it.

If you want to just use the *contents* of a `.htaccess` file (say, because you already have one from a service you're trying to migrate), you can use ASP.NET Core's built-in support for loading that file with the RewriteMiddleware.

**Comment by mysteryx93** [comment]
> If you want to use an actual .htaccess file, you need to use Apache at whatever node/server you want to use it.
So how do I do that?

If I just want the content in a middleware, I'd just reconfigure the rewrites in middleware format. Looking at other options before going that route.

**Comment by Eilon** [comment]
@mysteryx93 can you share some info on what you're trying to set up? What server(s) are in play, for what purpose, or any other info?

**Comment by mysteryx93** [comment]
.NET Core on Apache2 on Ubuntu. It's probably ignoring .htaccess because MVC is handling everything?

**Comment by davidfowl** [comment]
@mysteryx93 What does your configuration look like?

**Comment by mysteryx93** [comment]
<VirtualHost *:80>
  ServerName www.emergenceguardian.com
  ServerAlias emergenceguardian.com

  Redirect permanent / https://www.emergenceguardian.com/
</VirtualHost>

<VirtualHost *:443>
  ServerName emergenceguardian.com
  ServerAlias www.emergenceguardian.com
#  DocumentRoot /var/www/emergenceguardian.com
  Documentroot /var/www/spiritualselftransformation.com/
   DirectoryIndex default.aspx index.aspx index.php index.html

  <Directory "/var/www/spiritualselftransformation.com/">
    Require all granted
    AllowOverride All
  </Directory>

  <Location "/blog">
    SetHandler None
  </Location>

  SSLEngine on
  SSLCertificateFile /etc/apache2/SSL-KEYS/www.emergenceguardian.com/www_emergenceguardian_com.2017-2019.crt
  SSLCertificateKeyFile /etc/apache2/SSL-KEYS/www.emergenceguardian.com/privateKey.key
  SSLCertificateChainFile /etc/ssl/certs/comodo.bundle
  SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
  Protocols h2 http/1.1

  <LocationMatch ".*\.php">
    SetHandler application/x-httpd-php
  </LocationMatch>

  ProxyPreserveHost On
  ProxyPass .ht* !
  ProxyPass / http://127.0.0.1:5000/
  ProxyPassReverse / http://127.0.0.1:5000/

</VirtualHost>

**Comment by mysteryx93** [comment]
Now that I think of it, Apache2 should process .htaccess BEFORE forwarding anything to .NET Core, so there's no way .NET Core can conflict with it if it's setup right. After doing some research, I also realized .htaccess lookup is disabled by default for performance and security reasons. They also recommended to do the rewrites directly in the Apache2 config file to avoid a performance hit. Doing so in that way is working.

That doesn't explain why the redirect middleware isn't working though; which I posted as a separate issue.

**Comment by anurse** [comment]
> That doesn't explain why the redirect middleware isn't working though; which I posted as a separate issue.

This is https://github.com/aspnet/AspNetCore/issues/10543 right?

> Apache2 should process .htaccess BEFORE forwarding anything to .NET Core, so there's no way .NET Core can conflict with it if it's setup right.

Correct. We don't control how Apache2 processes `.htaccess`.
