### ISSUE TITLE
[Announcement] Kestrel Request trailer headers moved to new collection

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#10519]
In prior versions Kestrel would add HTTP/1.1 chunked trailer headers into the request headers collection when the request body was read to the end. This caused some concerns about ambiguity between headers and trailers so we decided to separate the trailers out to a new collection.

HTTP/2 request trailers were unavailable in 2.2, but are now also available in this new collection in 3.0.0-preview6.

New [request extension methods](https://github.com/aspnet/AspNetCore/blob/3be11f6544485948ba17646ffa7b4242c2c5339a/src/Http/Http.Abstractions/src/Extensions/RequestTrailerExtensions.cs) have been added to access these trailers.

HTTP/1.1 trailers are available once the entire request body has been read.

HTTP/2 trailers are available as soon as they’re received from the client, but the client won’t send them until the entire request body has been at least buffered by the server.  You may need to read the request body to free up buffer space. Trailers will always be available if you read the request body to the end, as the trailers mark the end of the body.

See https://github.com/aspnet/AspNetCore/pull/10410 for the changes.

**Comment by Sebazzz** [comment]
Does this change anything when reading multipart forms? (File uploads for instance)

**Comment by Tratcher** [comment]
No, those don't normally use trailer headers.
