### ISSUE TITLE
More InputComponents for common use cases

### ISSUE THREAD

**Issue by sjohag** [dotnet/aspnetcore#10529]
Please add more components in InputComponents for Blazor, covering common tasks like file uploading and select-multiple (perhaps render something like bootstrap-select).
A simple grid and a modal wouldn't hurt either.
And keep up the good work, you are making amazing progress!

**Comment by 3x0dv5** [comment]
I agree, although it is straightforward to add your own components.

1. dotnet new razorcomponent -o CcInputPassword
![image](https://user-images.githubusercontent.com/250271/58375095-2746d280-7f43-11e9-9b16-4b5cbe2f5a36.png)

2. I like to separate the razor syntax from the actual c# code, so create a cs file to keep the c#. Inherit your class from InputBase<T>
![image](https://user-images.githubusercontent.com/250271/58375098-33329480-7f43-11e9-8c08-d2f1890cf1b2.png)

![image](https://user-images.githubusercontent.com/250271/58375108-6d039b00-7f43-11e9-9ae6-1a74d125daee.png)

3. Inherit from the "cs code" and implement the razor markup
![image](https://user-images.githubusercontent.com/250271/58375104-578e7100-7f43-11e9-94a5-0ac614a10109.png)

4. ready to use on your form
![image](https://user-images.githubusercontent.com/250271/58375114-a6d4a180-7f43-11e9-8d19-86ebf13de872.png)

**Comment by sjohag** [comment]
Some are straightforward, some are not. 
I think that file uploading requires JS-interop, and select-multiple is not very useful with standard rendering in most browsers, slightly better on mobile phones thanks to the lack of keyboard (no ctrl-button).

Your implementation of InputPassword is simple and clean, but almost identical to the existing InputText. If the existing implementation had a "type"-parameter (enum), making your own wouldn’t be necessary. Same goes for InputDate, a "type"-parameter (datetime, datetime-local etc) would make it more useful.

It would be nice and more productive if the basic interaction elements were included.

**Comment by 3x0dv5** [comment]
Well yes and no. For the functionality I wanted to show you are right, a input type=password would be enough, but my password component has a bit more than just be a password field. I also noticed that I could inherited from InputText and not InputBase<>, but well it is a sample.

This is still work in progress and I believe that the guys will add a bit more love to this, meanwhile everyone is free to create their own open source razor component libs and nuget them ;) the purpose of a framework is to provide the foundations to build on top of it.

Personally I am loving it!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This ask is already covered as part of multiple other issues. So closing this as we will be handling these instead.

**Comment by mkArtakMSFT** [comment]
#12205, #15405, #5519
