### ISSUE TITLE
Add `Focus` method to ElementRef

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#10521]
It's really common to need to programmatically set focus on an element, and currently the only way  is using JSInterop.

**Comment by mikes-gh** [comment]
I can see quite a few components where this might be the only bit of JSinterop as it is very common.
Is the reason its delayed to 3.1.0 because it is difficult or part of some wider issue?

**Comment by mkArtakMSFT** [comment]
@mikes-gh, we're quite a small team and we try to focus effort only on the most-critical issues/improvements for the upcoming release (3.0). In other words, this is not as important as the work we do for the 3.0 release.

**Comment by mikes-gh** [comment]
@mkArtakMSFT  appreciate your efforts :+1:

**Comment by rik-smeets** [comment]
I was also struggling with basic keyboard accessibility in an `EditForm`, with components like `InputText`. Right now, it requires a lot of JS Interop, so I'm glad to see this is recognized.

However, the issue describes adding a `Focus` method to an `ElementRef`. Right now, `EditForm` components can't be bound to an `ElementRef` field. You'll get an error like:
`CS0029: Cannot implicitly convert type 'Microsoft.AspNetCore.Components.Forms.InputText' to 'Microsoft.AspNetCore.Components.ElementRef'`.

Is part of this issue also allowing form components (like `InputText`) to be bound to an `ElementRef` field?

And another question: in all my forms, basically what I want is this: 
- on the first render, autofocus the first field on the form. 
- when submitting an invalid form, focus on the first invalid field of the form.
- when the form is submitted successfully, focus the first field again (after emptying the contents). 

I believe this is some basic form functionality which should be easily implemented as well (without a lot of code duplication/JS Interop).  Can this be considered too?

Thanks!

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/17472
