### ISSUE TITLE
AddRazorPages() on new ServiceCollection > ApplicationPartManager missing parts

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#10611]
### Describe the bug
For background that lead to the discovery of this issue, see: https://github.com/aspnet/AspNetCore/issues/10469

`services.AddRazorPages()` seems to have hidden dependencies - basically there are other services that need to be already present in the `ServiceCollection` in order for `ApplicationPartsManager` to establish parts needed for `MapRazorPages()` to populate endpoint routes correctly. It's not clear or explicit what these dependent services are though, which is why I am referring to them as "hidden". All I can establish is that it must be one / some of the 60ish services that are already added for you to the IServiceCollection that gets passed into the Startup.ConfigureServices() method. The sample shows that if you add all 60ish of these services into a new IServiceCollection before then calling AddRazorPages() on that new IServiceCollection (and corresponding MapRazorPages) then ApplicationPartsManager correctly populates Razor parts which correctly drives endpoint routes. 
If you don't do this, then ApplicationPartsManager misses some parts and no endpoint routes are created for razor pages. Its imho a bug to allow AddRazorPages() to be added to a new service collection which due to missing services will result in no page routes ever being generated. At the least this could be detected and an exception thrown to indicate what the missing dependent services were. I'd prefer if it forced you to establish regiatration of any dependencies via the registration / builder API for adding razor pages but appreciate that could be tricky to get right.

Suppose your job is creating a multitenancy application where each tenant has it's own IServiceCollection.. you would think you could new up an IServiceCollection and add razor pages to it, but in reality you need to somehow figure out the hidden dependent services that are relied upon. It's hard to tell precisely what services those are
 Adding all the 60ish default services for example does resolve the issue, but which ones of those does RazorPages actually need.. who knows?

### To Reproduce
- Run the sample here: https://github.com/dazinator/DemoRazorPagesMapped - and note, if you don't clone the IServiceCollection passed in to configure, stuff won't work.

### Expected behavior
I expect to be able to Add Razor Pages to a new ServiceCollection and then use the RazorPages / endpoint middleware to serve razor pages. At the moment it only works if other unknown services are already in the ServiceCollection required for ApplicationPartManager be populate parts, and ultimately endpoint routes.

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
@rynowak what should we do here?
Should we update the service resolution code to require certain services rather than silently fail?
This is not really an ask we've got from community and this is pretty corner case situation. So I'm not sure we should change anything, especially when there is a workaround to manually add all the necessary services.

**Comment by rynowak** [comment]
This would be reasonable for us to do, but it's already really late in 3.0. We should consider this for .NET 5.0 (next year).

**Comment by alistairjevans** [comment]
Thought I'd add some additional context to this issue, which I believe I encountered yesterday when configuring an application without a `Startup` class (and was very confused by).

This issue appears to manifest itself in the fact that **which** `ConfigureServices` call you register services in really matters.

If I define my application as below, no razor pages are loaded/detected, I get 404s on all of them:

```csharp
var hostBuilder = Host.CreateDefaultBuilder(args)
.ConfigureServices(services =>
{
    services.AddRazorPages();
})
.ConfigureWebHostDefaults(webBuilder =>
{
    webBuilder.Configure((context, app) =>
    {
        var env = context.HostingEnvironment;

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
        }

        app.UseRouting();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapRazorPages();
        });
    });
});
```

I have to move the call to `AddRazorPages` to **inside** the web builder's `ConfigureServices`:

```csharp
var hostBuilder = Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.ConfigureServices(services =>
        {
            services.AddRazorPages();
        })
        .Configure((context, app) =>
        {
            var env = context.HostingEnvironment;

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        });
    });
```

It's a somewhat confusing behaviour that the `ConfigureServices` you choose impacts whether or not it works.

**Comment by dazinator** [comment]
@rynowak to remedy this I think it would be a fairly small change to make this code throw an exception if `IWebHostEnvironment` wasn't found, at the moment it would get a null instance, and environment name would be an empty string, and the application part manager would be added with no parts, which was the bug I was seeing:

https://github.com/dotnet/aspnetcore/blob/15f341f8ee556fa0c2825cdddfe59a88b35a87e2/src/Mvc/Mvc.Core/src/DependencyInjection/MvcCoreServiceCollectionExtensions.cs#L81

**Comment by brunolins16** [comment]
@dazinator I know that you opened this bug a long time ago, however, I have started the investigation and instead throw an exception we could add a new API that will allow you provide the `entryAssembly` instead of relying on the `IWebHostEnvironment`. 

I have been playing with your demo project and the option I just mentioned, and we will get all pages detected and routes created but based on your code you are expecting the request coming from:

- `/T1/Foo`
- `/T2/Bar`

Is that what you are looking for? I am asking because the `PageRouteModelFactory` will remove the root directory from the route and you actually get a `HTTP 404 - Not found`.

Eg.:
```c#
// rootDirectory = "/Pages/AllMyPages/"
// path = "/Pages/AllMyPages/Home.cshtml"
// Result = "/Home"
```

**Comment by dazinator** [comment]
@brunolins16 

> I have started the investigation and instead throw an exception we could add a new API that will allow you provide the entryAssembly instead of relying on the IWebHostEnvironment.

What happens if the entry assembly isn't provided (i.e assuming it's an option api and the developer isn't aware of it's existence) and the IWebHostEnvironment isn't found, would you then throw an exception? Would just be keen to see we don't see the same problem of silent failure in that scenario.

> Is that what you are looking for? I am asking because the PageRouteModelFactory will remove the root directory from the route and you actually get a HTTP 404 - Not found.

Yeah I think this is more down to the routing.. I was attempting to have two different containers, each with Razor pages, both serving from different "root" folders where the pages are expected to live - i.e so /T1 folder vs /T2 folder. When a request comes in, I use something on the request to identify which razor pages should handle this request (for example in a multitenant scenario, which tenant does the request belong to). If the razor pages in container mapped to /T1 handles the request, then it should only be able to resolve pages in that folder. In terms of the me using /T1 and /T2 in the request path, I think you are saying if I removed that from the request path upon handling the request, before Razor pages handled the request, then it would work - i.e so the Razor Pages middleware sees an incoming request for /Home rather than /T1/Home. If that is the case then I don't see any issues with that!

P.S thanks for looking at this after all this time ;-)

**Comment by brunolins16** [comment]
@dazinator

> What happens if the entry assembly isn't provided (i.e assuming it's a new optional api and the developer isn't aware of it's existence) and the IWebHostEnvironment isn't found, would you then throw an exception? Would just be keen to see we don't see the same problem of silent failure in that scenario.

The goal is to not fail silently anymore, and I am working to find the best approach here to throw an exception when the ApplicationParts are not configured correctly and should have an API Suggestion soon.

> - i.e so the Razor Pages middleware sees an incoming request for /Home rather than /T1/Home. If that is the case then I don't see any issues with that! Typically I wouldn't actually need to do anything as I tend not to use reqeust path as a mechanism to do this mapping, I would typically actually do this mapping via subdomain or hostname - e.g http://t1.localhost.com/*--> t1 container, http://t2.localhost.com/* --> t2 container.

Subdomains or hostnames should work perfectly!

**Comment by brunolins16** [comment]
I am closing this issue since the API Suggestion (#39126) was approved and we will start work on it soon and we track from there. Thanks for submit the issue.
