### ISSUE TITLE
Memory usage goes to 700MB for an almost empty project using dotnet watch run in a container

### ISSUE THREAD

**Issue by Rakiah** [dotnet/aspnetcore#10629]
I'm getting huge memory usages in my containers using `dotnet watch run`, each of my .NET Core 2.1 containers reach up to 700mb and for each request, it raised 1mb in ram, after 15 minutes, it went down to 200mb and again it raised 1mb in ram for each request, i've been seeing that disabling ServerGarbageCollector in the .csproj would fix my problem but it didn't, i'm using .NET Core 2.1.6

Anyone is experiencing the same problem ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We haven't heard others complaining about this issue. If you believe this is still an issue please share memory profiles of your dotnet watch app so that we can investigate this further.
