### ISSUE TITLE
Polly on Blazor

### ISSUE THREAD

**Issue by pdeveau** [dotnet/aspnetcore#10652]
### Describe the bug
Using a Polly Policy in blazor on httpclient does not execute policy on a transient failure.

### To Reproduce
Using the code below:

```cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using Microsoft.AspNetCore.Components.Builder;
using Microsoft.Extensions.DependencyInjection;
using Polly;

namespace Web.Client
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
             // custom wasm request handler to add a bearer token to each internally matching request
             services.AddSingleton(x => new HttpClient(new TokenWebAssemblyMessageHandler(x.GetService<ITokenService>())));

            // add polly wait and retry policy
            services.AddHttpClient<IMicroServiceClient, SomeMicroserviceClient>()
                .AddTransientHttpErrorPolicy(builder => builder.WaitAndRetryAsync(new[]
                {
                    TimeSpan.FromMilliseconds(300),
                    TimeSpan.FromMilliseconds(600),
                    TimeSpan.FromMilliseconds(900),
                    TimeSpan.FromMilliseconds(1200)
                }));

            services.AddSingleton<AppState>();
        }

        public void Configure(IComponentsApplicationBuilder app)
        {
            app.AddComponent<App>("app");
        }
    }
}
```

### Expected behavior
When the httpclient makes a failed call, i.e. response in the 5xx and 4xx ranges, should retry the request per the orders of policy.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pdeveau.
Can you please provide us with a repro project (as a repo in GitHub)? The simpler the repro process for us, the faster we'll find time to look into it.

**Comment by pdeveau** [comment]
https://github.com/pdeveau/blazor-reproduction

**Comment by pdeveau** [comment]
In some further checking there are apparently some wipes in AddHttpClient, providing a simple HttpClientFactory gets a bit further.  See branch feature/with-httpclient-factory

**Comment by mkArtakMSFT** [comment]
Thanks @pdeveau.
We're wrapping up upcoming releases now and will be able to get to this only after that.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
