### ISSUE TITLE
Blazor client chrome debugger - doesn't send cookies when requesting static files

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#10687]
### Describe the bug
When serving up a blazor client app from an asp.net core host / middleware pipeline, if you put some cookie authentication middleware in front of it (i.e because you don't want to allow someone to download the app until they are logged in with X claims) it initially works. However when you launch the debugger using ctrl+shift+d it looks like the blazor debugger in chrome makes a number of requests for static files (css etc) but it doesn't submit cookies. This results in those requests being rejected with challenges. 

Note: I am aware that once the static files have been served up they have escaped the server and could be used by anyone including unauthorised people - therefore i'm not relying on this as a security mechanism, rather it's an addition to baking authentication and authorisation in on the server side API that the client blazor app then consumes.

### To Reproduce
UPDATE: I have linked a repro project in the conversation below!

1. serve a razor client app from an asp.net core middleware pipeline.
2. Insert some cookie middleware before `.UseBlazor<Client.Startup>();`
3. Insert some middleware after the cookie middleware, and before ` setupBranch.UseBlazor<Client.Startup>();` that authorises the request based on cookie authentication scheme.
4. Launch the blazor app ijn chrome
5. Open the blazor debugger with ctrl+shift_d

### Expected behavior
The debugger makes requests for additional files from the server - it should include cookies so that the files are served up.

### Screenshots

![image](https://user-images.githubusercontent.com/3176632/58692806-5025f800-8387-11e9-8b58-8b466dc3e775.png)

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Given that nobody else has faced this issue and a long time has passed, can you please confirm this is still an issue you're facing? Thanks!

**Comment by dazinator** [comment]
@mkArtakMSFT 

Yes this is still an issue. Here is a repro: https://github.com/dazinator/AspNetCore-BlazorDebuggingIssue
