### ISSUE TITLE
Better experience for passing ChildContent with CaptureUnmatchedParameters

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#10709]
Using a component like `InputText` that captures unmatched parameters, but **doesn't** accept a child content can result in some silent-ish failures if you try to provide one. 

Since passing a *content* to the builder is a different gesture than passing an *attribute*, the result is that Blazor will ToString the delegate and put it in the attribute.

- We could choose to make this *just work* which is think is not ideal (violates intent of the component developer)
- We could make this explicitly an error by special casing this parameter name (behavior when you don't have capture unmatched parameters)
- We could do nothing.

I'm not totally concerned about a breaking change since this doesn't do anything useful.

![image](https://user-images.githubusercontent.com/1430011/58729655-da2d8b00-839e-11e9-83ec-524340714202.png)

Sample code:
```razor
@page "/"
@using Microsoft.AspNetCore.Components.Forms

<EditForm Model="@p">
    <InputText ChildContent="@((RenderFragment)RenderIt)" @bind-Value="@p.Name"></InputText>
</EditForm>


@functions {
    Person p = new Person();
    public class Person
    {
        public string Name { get; set; }
    }

    void RenderIt(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder b)
    {
        b.OpenElement(0, "strong");
        b.AddContent(1, "YO");
        b.CloseElement();
    }
}

```

**Comment by rynowak** [comment]
My recommendation on this is backlog and wait for feedback, doesn't seem urgent.

**Comment by SteveSandersonMS** [comment]
Due to lack of any feedback in ~18 months it seems this is not a clear need, so I'll close it. We can always reconsider in the future.
