### ISSUE TITLE
Remove DisableFastUpToDateCheck from Blazor projects

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#10711]
We have projects in the Blazor solution that use `<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>`. This setting makes VS call into MSBuild to *build* these projects when running tests - which adds about 15-20 seconds of lag time every time we run the E2E tests.

This was originally added because some of these projects have an *implict* dependency on the blazor dev server.

We could fix this in one of three ways:
- Move the testing of the Blazor dev server into template tests (we probably want this anyway)
- Make the actual up-to-date-check work correctly via project references 
- Isolate the impact of this by creating a separate E2E test project for *just* testing the dev server
- Remove the workaround and accept the regression (testing changes to dev server will require an explicit rebuild)

**Comment by pranavkm** [comment]
This has been resolved.
