### ISSUE TITLE
Aspnetcore MVC on IIS - Terrible first request performance

### ISSUE THREAD

**Issue by worldspawn** [dotnet/aspnetcore#10749]
### Describe the bug
I have a aspnetcore mvc application which is experience very poor performance on it's first request. I have excluded efcore's own context creation time and am left with a large unaccounted for delay that I do also experience locally (in iisexpress) but just not as bad.

I have 2.2.5 runtime installed on the server however I have "published" it as "self-contained" for win-x64 and have 2.2.3 on my local machine so... 

Windows Server 2016 14393.2906
IIS 10.0.14393.0

### Expected behavior
No inexplicably large delays.

### Screenshots
This is a profile of the first document request. As you can see there is this bizarre ~8s delay that is occurring between view seeks (i have two custom view file providers and the original is still present).

![image](https://user-images.githubusercontent.com/819581/58769413-37694c80-85ea-11e9-8b13-3699a72c6cd9.png)

Heres the same request locally:

![image](https://user-images.githubusercontent.com/819581/58769523-371d8100-85eb-11e9-9071-352db42a3daf.png)

**Comment by worldspawn** [comment]
I can confirm I dont have this delay when using a file system view. Is this delay all view compilation? Seems very excessive if so.

Tried with this simple view (no layout):
```
@{
	
}
<p>
Hello Worlds</p>
```

and the profiling went:

![image](https://user-images.githubusercontent.com/819581/58769949-fcb5e300-85ee-11e9-9f04-d01bf4140f99.png)

1.1 seconds to compile that doesn't seem right. These times are from my local dev machine.

**Comment by worldspawn** [comment]
I created a simplified view file provider which just does this in InitView

```
private void InitView(string connection)
        {
            _viewContent = Encoding.UTF8.GetBytes("HELLO WORLD. ALL YOUR BASE ARE BELONG TO US.");
        }
```

and I am still getting > 1s for this request to serve. Is there someway to speed this up?

**Comment by worldspawn** [comment]
Can I _prime_ the view cache with something like this?

``` csharp
    public class TestHostedService: IHostedService
    {
        private readonly IServiceProvider _serviceProvider;
        public TestHostedService(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            // Create a new scope to retrieve scoped services
            using(var scope = _serviceProvider.CreateScope())
            {
                var viewEngine = scope.ServiceProvider.GetRequiredService<ICompositeViewEngine>(); 
                // Get the DbContext instance
                using (var dbContext = scope.ServiceProvider.GetRequiredService<SugarcubeContext>())
                {
                    var paths = dbContext.Template.Select(t => t.Path)
                        .Union(dbContext.Layout.Select(l => l.Path))
                        .Union(dbContext.Snippet.Select(l => l.Path));

                    foreach (var path in paths)
                    {
                        var success = viewEngine.GetView(null, path, false).Success;
                        if (!success)
                        {
                            throw new Exception("NO Success");
                        }
                    }
                }
            }
        }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @worldspawn.
In ASP.NET Core 2.2 runtime-comiplation is disable by default. So all your Razor views/pages should be compiled at build time. Have you manually enabled it?
Please share a repro project so we can investigate this.

**Comment by mkArtakMSFT** [comment]
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.2

**Comment by worldspawn** [comment]
Hi @mkArtakMSFT. Sorry it's not explicit on my question. The views are being sourced from a database so compile time processing is not an option. I have added my own `IFileProvider` implementation to provide the source for each of these views. The fact that come from the database isn't relevant, just that they are coming from a custom source.

Its clear to me now that this whole issue is caused by doing runtime compilation of the views. And the runtime compilation is happening because the view are not cshtml files and cannot be compiled at build time. So no mystery there.

The best path forward I can see is to _prime_ the cache of compiled views when the server process starts. In the example above I am loading all the known view _paths_ from the database and I am then requesting that view from the ICompositeViewEngine.

For whatever reason though, subsequent requests (after the above has run) for that same view path do not seem to come from cache (they are loaded from db and compiled). A proper request initiated through a controller etc does seem to result in a compiled view being cached though. I know I'm going against the grain here but do you have any guidance on how I can prime the view cache?

**Comment by mkArtakMSFT** [comment]
So if I understood you correctly, the issue is that the caching doesn't work and the views being requested from the database always, rather than only the fist time, correct?
