### ISSUE TITLE
[Discussion] UseSignalR and UseConnections are marked obsolete

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#10754]
The methods `UseConnections` and `UseSignalR`, and the classes `ConnectionsRouteBuilder` and `HubRouteBuilder` are being marked obsolete in 3.0. And will be removed in the next major release after that.

The preferred method for using SignalR starting in 3.0 is to use Endpoint Routing. See example below.

Old code:
```csharp
app.UseSignalR(routes =>
{
    routes.MapHub<SomeHub>("/path");
});
```

New code:
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<SomeHub>("/path");
});
```

This is the discussion issue for aspnet/Announcements#362.

**Comment by Kahbazi** [comment]
@VictorioBerra yes, there's also MapController extension method for mvc

**Comment by idrivediesel2006** [comment]
What is you're not using MVC, instead you're using Web API... What's the implementation for SignalR?

**Comment by davidfowl** [comment]
> What is you're not using MVC, instead you're using Web API... What's the implementation for SignalR that is replacing the obsolete UseSignalR() method?

The code above is the same. 

PS: MVC is the same thing as Web API in ASP.NET Core. It's a single framework.
