### ISSUE TITLE
Can I mock a request to trigger `HttpContext.RequestAborted`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#10758]
Hi,
I wanna to test a scene when the user abort the request before server writes its response.
But seemed to not work with my cancellation on my browser.

So can I mock a request cancel behavior in my test?

**Comment by jkotalik** [comment]
I would take a look at some of our tests in Kestrel. Specifically, look at
https://github.com/aspnet/AspNetCore/blob/8c41472336f1d6364c454b4b6ce19cb63c527dca/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs#L187. This is a test that verifies RequestAborted is triggered when the client aborts the request.

**Comment by WeihanLi** [comment]
I'd tried to use a `HttpClient` to send a request with 3 second cancellation, while the server wait for 5 seconds then judge the `HttpContext.RequestAborted.IsCancellationRequested`, seemed to be `false` always

request client:
``` csharp
            using (var client = new HttpClient(new HttpClientHandler()
            {
                Proxy = new WebProxy(new Uri("http://127.0.0.1:8888")),
                UseProxy = true
            }))
            {
                // var resString = client.GetStringAsync($"https://weihanli.xyz").GetAwaiter().GetResult();

                var cts = new CancellationTokenSource(TimeSpan.FromSeconds(3));
                cts.Token.Register(() => Console.WriteLine("request canceled"));

                try
                {
                    var responseMessage = client.GetAsync($"http://localhost:65125/api/chat/hello", cts.Token).GetAwaiter().GetResult();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }
```
web server:
``` csharp
            await Task.Delay(5000);
            var requestAborted = HttpContext.RequestAborted.IsCancellationRequested;
```
