### ISSUE TITLE
Remove obsolete methods/classes in SignalR

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#10756]
In 3.0 we marked `UseConnections`, `ConnectionsRouteBuilder`, `HubRouteBuilder`, and `UseSignalR` obsolete. See https://github.com/aspnet/AspNetCore/commit/f0df10f211b5ea8192579808c223e82aab549268 for the change.

We should remove them in the next major release.

**Comment by anurse** [comment]
Pre-planning notes: FYI, this work requires an API review and announcement.
