### ISSUE TITLE
Warning in SampleDataController.cs in SPA projects with Visual Studio for Mac: Redundant array creation expression

### ISSUE THREAD

**Issue by iantoalms** [dotnet/aspnetcore#10762]
### Describe the bug
In Visual Studio for Mac 8.1 we added support for the SPA ASP.Net Core project templates.  When creating one of these projects and opening the SampleDataController.cs source file, we see a warning in the code.

### To Reproduce
Install steps:

1.Install 8.0 (latest-released-build):
Install latest from https://visualstudio.microsoft.com/vs/mac/
2. Launch the IDE
3. Sign-in using your MS account creds
4. Update VS Mac to latest 8.1 preview by selecting the Preview channel in Visual Studio->Check for updates.

Repro steps:
1. File > New Solution > .NET Core > App> Angular > .NET Core 2.2 > Create
2. Build the project.
3. Open Controllers > SampleDataController.cs file, it will show up some orange squiggles.

### Expected behavior
We don't expect warnings in code in the templates.

### Screenshots

![ArrayCreationWarning](https://user-images.githubusercontent.com/14179593/58795164-de051b80-85f1-11e9-87f0-30fd6b584fad.png)

### Additional context
This warning comes from RefactoringEssentials, and is designated as a warning:

https://github.com/icsharpcode/RefactoringEssentials/blob/master/RefactoringEssentials/CSharp/Diagnostics/Synced/RedundanciesInCode/ArrayCreationCanBeReplacedWithArrayInitializerAnalyzer.cs#L18

This seems to just be a case where VSmac has an analyzer running that VSwin lacks.

**Comment by jkotalik** [comment]
@ryanbrandenburg is this something we can address in 3.0? Should be a quick one-liner.

**Comment by mkArtakMSFT** [comment]
Thanks @iantoalms.
@ryanbrandenburg let's get this merged as soon as the PR checks pass. We'll take this as part of Preview7 release.

**Comment by pranavkm** [comment]
We've since changed the templates and the controller no longer appears. Closing this issue.
