### ISSUE TITLE
Can I suggest a suggestion about anomalies?

### ISSUE THREAD

**Issue by YPTopMan** [dotnet/aspnetcore#10767]
### Is your feature request related to a problem? Please describe.
A lot of duplicate exception code, increasing the amount of code, can it be streamlined into a single line?   Too much

### Describe the solution you'd like
One line of code can do it

### Describe alternatives you've considered
![image](https://user-images.githubusercontent.com/11879898/58803563-64494e00-8642-11e9-914c-51f47405af57.png)

### Additional context
![image](https://user-images.githubusercontent.com/11879898/58803622-86db6700-8642-11e9-96c0-eb46c89b73af.png)

**Comment by YPTopMan** [comment]
![image](https://user-images.githubusercontent.com/11879898/58803749-c73ae500-8642-11e9-9d28-aafff9967bf6.png)

**Comment by jkotalik** [comment]
This is really a stylistic thing. I personally don't have a preference between each style. I don't think we would accept a pull request to fix all of these instances.

**Comment by YPTopMan** [comment]
![image](https://user-images.githubusercontent.com/11879898/58847428-89c36f80-86b5-11e9-895f-e7c8d45043fe.png)


I don't know if I am clear. I want to say that this kind of repeated judgment is null and throws an exception. If it is modified into one line, it can reduce the number of lines of code. Does it affect the size of the source package?

--Google Translate's Notes

**Comment by YPTopMan** [comment]
Should I ask for a requirement in the C# language?
