### ISSUE TITLE
Java signalr client not ASP.NET SignalR compatible, but ASP.NET java client is obsolete now?

### ISSUE THREAD

**Issue by daybyter** [dotnet/aspnetcore#10788]
Hi!

Thanks for your efforts!

I'm trying to connect to fxstreet.com with your java client. No luck so far. fxstreet doesn't seem to support websocket transport, so I need a java client version, that support other transports. So older versions are not an option, it seems.

So I tried the AspNetCore version, and this is, what I get:

[java] FXStreet Push Notifications
     [java] Got token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
     [java] Create hub connection
     [java] Exception in thread "main" java.lang.RuntimeException: Detected an ASP.NET SignalR Server. This client only supports connecting to an ASP.NET Core SignalR Server. See https://aka.ms/signalr-core-differences for details.
     [java]     at com.microsoft.signalr.HubConnection.lambda$handleNegotiate$2(HubConnection.java:269)
..

Will this client ever be ASP.NET compatible? Or what are other options to connect to this server? It seems the older version are no longer developed, so I guess there won't be a backport of other transports to the ASP.NET version?

Thanks in advance,
Andreas

**Comment by anurse** [comment]
As you noted, the `com.microsoft.signalr` client is not compatible with ASP.NET SignalR. The ASP.NET SignalR Java client is located here: https://github.com/SignalR/java-client and is no longer updated. You're welcome to take the code and do what you want with it, the license in permissive (Apache 2.0), but we have no plans to update it at this time.

**Comment by mikaelm12** [comment]
Following up on this, you can use the LongPolling transport on the ASP.NET Core SignalR Java client like so 
```java
HubConnection hubConnection = HubConnectionBuilder
    .create("http://example.com")
    .withTransport(TransportEnum.LONG_POLLING)
    .build();
```
