### ISSUE TITLE
Error 139 Segmentation Fault on ARM32 for server-side Blazor project

### ISSUE THREAD

**Issue by Mewgrammer** [dotnet/aspnetcore#10847]
Building the "blazorserverside" template on Odroid MC-1 (ARM32) fails with Error Code 139 segfault.

1. Using ASP.NET Core 3.0 Preview 5
2. dotnet new blazorserverside
3. dotnet build

I experienced this error when using the cli  and also when trying to build using Docker
Images uses for Docker:
mcr.microsoft.com/dotnet/core-nightly/aspnet:3.0.0-preview5
mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-preview5

Building and running the app and the docker container on Windows 10 works without any issues.

**Comment by SteveSandersonMS** [comment]
I'm afraid we're unlikely to have access to the same hardware that you're describing, but we can run things in Docker.

Are you saying that you can reproduce the problem in Docker on a Windows 10 machine? If so, can you post steps for doing that?

**Comment by Mewgrammer** [comment]
On Windows 10 the docker container runs fine. On the Odroid it fails with code 139 during "dotnet build".

**Comment by SteveSandersonMS** [comment]
Thanks for clarifying!

Given that, I'm not sure how we could investigate this within the ASP.NET Core team due to (1) not having that hardware, and (2) not doing anything hardware-specific in our code anyway.

It's most likely going to be a job for whichever team deals with porting .NET Core to run on ARM32. @danroth27 / @mkArtakMSFT Any ideas how we can redirect this to the right people?

**Comment by Mewgrammer** [comment]
Some additional information about the hardware used:
I tested on single node of the Odroid MC-1 which is a Odroid xu4
Odroid xu4 uses the Samsung Exynos 5 (5422) Processor which is made up of a Cortex-A15  and Cortex-A7 which are both 32bit processors implementing the ARMv7-A architecture.

this is the Dockerfile I used to build my docker container:
https://github.com/Mewgrammer/dotnetCoreARMtest/blob/master/Dockerfile

this builds fine on Windows 10 and Raspberry Pi, however fails on the Odroid machine as mentioned above.

**Comment by rynowak** [comment]
@richlander - can you help route this?

**Comment by richlander** [comment]
Very interesting. Do you see the same thing if you try to build a .NET Core console application?

Can you successfully run ARM32 Debian images in your environment?

Please try with Preview 6 images?

/cc @MichaelSimons

**Comment by MichaelSimons** [comment]
Can you please include the output of running `docker info` and `docker version` in your Odroid environment?

**Comment by Mewgrammer** [comment]
Next Tuesday I will have access to the hardware again and provide you with the outputs. I will try to build & run several of the templates for net core 3.0 preview 6 both on docker and directly on the OS. 

Are there any further command outputs or information that could be useful?

**Comment by Mewgrammer** [comment]
Today we tested again with preview 6 Images:

Attempt 1: 
Project: Net Core 3.0 Preview 6 Console App ("dotnet new console") + Added Docker Support (generated by VS, Target OS Linux ) Source Code here: https://github.com/Mewgrammer/dotnetCoreARMtest/tree/master/ConsoleApp

Referenced Images in Dockerfile: 
- mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim
- mcr.microsoft.com/dotnet/core/sdk:3.0-buster

Build & Run on Windows works
Building on the Target Machine ouputs this:
![Build 3 0 Image](https://user-images.githubusercontent.com/5330937/59795293-3703cd80-92db-11e9-9b98-e745288e9463.jpg)



Attempt 2: 
Project: Same as Attempt 1
Referenced Images in Dockerfile: 
- mcr.microsoft.com/dotnet/core/runtime:3.0.0-preview6-buster-slim-arm32v7
- mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-buster-arm32v7

Ouput:
![Build 3 0 Arm32 Image](https://user-images.githubusercontent.com/5330937/59795292-366b3700-92db-11e9-9074-e6616d873f74.jpg)

Docker Info:
![Docker Info ](https://user-images.githubusercontent.com/5330937/59795296-3703cd80-92db-11e9-8c6e-12a4447ebac5.jpg)

Docker Version:
![Docker Version](https://user-images.githubusercontent.com/5330937/59795290-366b3700-92db-11e9-81a3-e92b08510c2e.jpg)

as we weren't able to get the console app to work we didn't try other templates.

**Comment by pranavkm** [comment]
@Mewgrammer do you continue seeing this issue with 3.1 released?
