### ISSUE TITLE
Single directive attributes with parameters don't result in errors.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#10860]
### Describe the bug
Having an element with a single directive attribute + parameter does not result in warnings to user about invalid usage:

![image](https://user-images.githubusercontent.com/2008729/58915154-3c56fa80-86d5-11e9-85f5-207ff697b532.png)

In VS this is pretty obvious with coloring but at command line or in VSCode it's far less obvious.

### Additional context
This is due to how directive attributes apply their parameters at the matching phase (the entire element doesn't get counted as a Component). Essentially Razor's matching system is comparing `@bind` to `@bind:format` without considering its parameters when deciding if an HTML element is a component.

**Comment by rynowak** [comment]
hmm. 

Well we're going to want to make this work. This **specific** case should be an error (specific to `bind` without `bind:format`). 

We want this case to work without an error:

```razor
<button type="submit" @onclick:preventDefault />
```

Consider the semantic of where the non-parameterized version to be part of the *implementation* of the directive.
```

**Comment by NTaylorMullen** [comment]
> Consider the semantic of where the non-parameterized version to be part of the _implementation_ of the directive.

Yup totally agree this is something we should support.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
