### ISSUE TITLE
Templates aren't C# 8.0 nullability compliant by default

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#10921]
Not sure if this is something we want to do but figured i'd file an issue anyhow. Basically our templates aren't nullability enforcement compliant. For instance **RequestId**:

![image](https://user-images.githubusercontent.com/2008729/58987968-7daedf00-8795-11e9-988c-3ad55361779f.png)

**Comment by NTaylorMullen** [comment]
Just for context Blazor templates have a bit more violations: https://github.com/aspnet/AspNetCore/issues/13072#issuecomment-523220833

**Comment by DamianEdwards** [comment]
This is covered by #33947 now
