### ISSUE TITLE
Error for multiple CaptureUnmatchedValues properties isn't visible in the editor in .razor

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#10952]
```razor
@code {
    [Parameter(CaptureUnmatchedValues = true)] List<string> Attributes { get; set; }

    [Parameter(CaptureUnmatchedValues = true)] Dictionary<string, object> Attributes2 { get; set; }
}

```
> 1>obj\Debug\netcoreapp3.0\Razor\Pages\FetchData.razor.g.cs(49,18,49,27): warning BL0002: Component type 'AnalyzerDemos.Pages.FetchData' defines properties multiple parameters with CaptureUnmatchedValues. Properties:

This error will not show up in the error list because it's in hidden code (the class declaration). It shows up when you do a build, but gives a path to the generated code.

We should adjust where this error appears (choose a property and place it there) or find a way to make the class declaration itself not be hidden code.

**Comment by SteveSandersonMS** [comment]
Don't know when this was fixed, but just checked and it now correctly shows up as a warning even before building.
