### ISSUE TITLE
External logins should use client ID/secret set at login time to not impede multi-tenancy

### ISSUE THREAD

**Issue by jeffputz** [dotnet/aspnetcore#10975]
## Problem
Setting up external logins (i.e., social logins) is currently accomplished via configuration in Startup, setting the client ID's and secrets at app start. In a situation where the application runs as a multi-tenant app, it should be possible to set the ID and secret at the time of the login.

## Possible solution
One solution I've toyed with is to break the link between `OAuthHandler`s and `OAuthOptions`. For example, if you could configure a handler via `AddOAuth<TOptions, THandler>()` by using an alternative options, you could have your own implementation that sourced the ID and secret from somewhere else. This would be even easier if you could get a reference to the DI container, because then you could get an `IMyTenantResolver` or whatever to get your new values. Right now though, the handlers are all tightly bound to options (i.e., `GoogleHandler` inherits from `OAuthHandler<GoogleOptions>`).

## Alternative
A possible alternative is to have the `OAuthEvents` include another event that's invoked, but it looks like that would not be thread safe today, and you'd be risking race conditions.

## Anti-vision
What I'm not looking for is deeper integration to the Identity stack, and EF.

## Other notes
The identity stack right now is a lot of magic that feels a little more complex that it has to be, and part of that is because it's hard to strip it down to roll your own, non-EF Identity stack. I had to look into the source to [roll my own controller actions](https://github.com/POPWorldMedia/POPForums/blob/27bee6e2b9d538564d6415e349b284bc21b94005/src/PopForums.Mvc/Areas/Forums/Controllers/AuthorizationController.cs#L113) to play nice with the magic stuff. I appreciate the usefulness of Identity/EF to quickly build something, but anything non-trivial tends to require something else before too long.

**Comment by blowdart** [comment]
@sebastienros how are you handling this in Orchard?

@jeffputz We don't aim to be a multi-tenant solution unfortunately, but we try not to hinder. @Tratcher didn't you have an example around this?

**Comment by jeffputz** [comment]
@blowdart That's fair, I don't expect the framework to implement multi-tenancy, it's just that the current pattern makes it very difficult and it does hinder. I've been working in SaaS the last few years, and multi-tenancy it's not only common, it's the primary use case. 😁

As for the "opinionated" part, you're not kidding. I'm not sure I would celebrate that as a good thing. Just trying to separate it from EF is hard.

**Comment by Tratcher** [comment]
@blowdart Not for this case. If you derive from OAuthHandler I think you could make it work, but you'd have to override both the challenge and the code exchange.

**Comment by jeffputz** [comment]
@sebastienros So you're creating an entirely dedicated copy of middleware and the entire DI stack per tenant? That doesn't have significant memory implications? (Honest question... I don't know what the footprint of the DI mapping is.) I guess that means you could also tear down a stack if a setting changes for a tenant (like OAuth keys) without having to restart the app instance, yes?

**Comment by sebastienros** [comment]
On average less than 4MB per tenant, on 64bits. But everything is isolated so we can reload one without impacted the other running ones, for instance when a configuration needs to change. We can also setup new ones dynamically (SaaS). Example: https://try.orchardproject.net is a self-service platform that creates new sites based on pre-defined recipes. Yet it's a single web application.

**Comment by jeffputz** [comment]
@sebastienros thanks. Not sure we could run with that approach, with a target of 1k tenants in cheap cloud infrastructure. Still would like to look... is that context loading in OrchardCore, and if so, which sub-project?

**Comment by sebastienros** [comment]
Try to follow this tutorial https://orchardcore.readthedocs.io/en/dev/docs/guides/create-modular-application-mvc/ and then in the module configure the authentication. Go on the gitter forum and ping me so we can show you how to setup 1000 tenants for testing.

**Comment by jeffputz** [comment]
That's still a heavy solution for a simple problem. An OAuth exchange is reasonably straight forward, and the ask here is just to decide at login time which credentials we use.

**Comment by justinhelgerson** [comment]
@jeffputz Did you get any closer to a solution for this?  I need to dynamically auth against AWS Cognito depending on the tenant (query string).

@Tratcher Have you seen any examples of someone accomplishing this that you could share?

**Comment by jeffputz** [comment]
@justinhelgerson No, the framework simply won't let you change this at request time. I'm working on a mini-framework that decouples all of this from Identity and EF. OAuth and a OpenID Connect are not that complicated, and it's frustrating how abstract yet monolithic this solution is. If you follow the POPForums project here on GitHub, you'll see a reference to this thing soon.

**Comment by Tratcher** [comment]
@justinhelgerson no, these OAuth & OIDC components are not designed for dynamic multi-tenancy.

**Comment by justinhelgerson** [comment]
@sebastienros I think your idea of a DI container for each tenant is the way to go unless this becomes a first class feature.  Do you have a stripped down example showing how you can add/update the containers dynamically?  🤞

**Comment by jeffputz** [comment]
@justinhelgerson I did finally come up with a solution that required me to learn a lot more about OAuth2 than I would have liked. 😁 I whipped up a simple library that just gets the user bounced through the IdP, then does the token exchange you need for the ID. It totally leaves persistence and `Principal` forming to you. https://github.com/POPWorldMedia/POPIdentity

I rolled it in to [POP Forums](https://github.com/POPWorldMedia/POPForums), and so far so good. Now I'm not using any part of Identity, and it feels good. There's no universe where I could do separate DI containers per tenant, and I didn't feel comfortable with that kind of memory footprint.
