### ISSUE TITLE
Creation of an Identity User via External Login doesn't set AuthenticationMethod

### ISSUE THREAD

**Issue by serpent5** [dotnet/aspnetcore#10970]
When signing in with an external provider for the first time, the Default UI for Identity doesn't set the `ClaimTypes.AuthenticationMethod` claim.

In [`ExternalLoginModel<TUser>.OnPostConfirmationAsync`](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L174), I think the [call to `SignInAsync`](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L206) should include an `authenticationMethod` argument, like this:

```cs
await _signInManager.SignInAsync(user, isPersistent: false, info.LoginProvider);
```

**Comment by blowdart** [comment]
We've thought about this before, but in reality you're not logging in through the external provider, but you are instead using the external provider to lookup users in your identity database, and then login through identity. It'd be an untruth to flag such logins as coming from Facebook, or Google, because the identity user database overrides, augments and changes any claims from the external provider.

**Comment by serpent5** [comment]
The second time around, the code succeeds when using `ExternalLoginSignInAsync`, which just looks up the user from the Identity store and sets the `AuthenticationMethod` claim to e.g. Google. Is this particularly different to the first-time setup? The database overrides, etc all still apply here, from what I can see.

**Comment by blowdart** [comment]
Oh that is weird. OK, sounds like a bug, or somewhere we a decision was made and didn't take effect everywhere.

**Comment by serpent5** [comment]
I'm happy to have a go at a PR for this if it would be helpful. I realise that a decision might need to be made on how to proceed first and that changes would apply to both the V3 and V4 UIs and the scaffolding too. I guess it might be a breaking change for someone that's depending on the claim not being set (or being set if that's what changes).

**Comment by blowdart** [comment]
Sure, we'd love a PR!

**Comment by serpent5** [comment]
I’d still like to try and PR this, but I’m having a really hard time trying to build from source, so I’ll come back when I’ve got that going.

**Comment by blowdart** [comment]
@serpent5 Are you still trying to get this working? We'd like to get this into 3.1

**Comment by serpent5** [comment]
@blowdart I couldn't ever get past not understanding how to use a locally built version of `Microsoft.AspNetCore.Identity.UI` so that I could run and test the change. The guidance in [Use the result of your build](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#use-the-result-of-your-build) didn't work for me and I didn't get a response on the [issue](https://github.com/aspnet/AspNetCore/issues/12706) I raised seeking help (which I put down to the team being all kinds of busy or my explanation just being terrible).

**Comment by blowdart** [comment]
@hoak can you give some guidance here?

________________________________

**Comment by serpent5** [comment]
@blowdart Thanks, it'd be great to get some help. I guess you meant to tag @HaoK...

**Comment by blowdart** [comment]
Hah, yes, no autocomplete on email :)

**Comment by Pilchie** [comment]
Moving to P3, since it's too late for P2.  What's the state of this for P3?

**Comment by HaoK** [comment]
This seems like something safe to move to 5.0 @ajcvickers @blowdart

**Comment by ajcvickers** [comment]
@HaoK Seems fine to move.

**Comment by serpent5** [comment]
FYI, I've managed to figure this out now, so I've just submitted a PR. Please don't view this comment as a nudge to review said PR.

**Comment by HaoK** [comment]
Thanks again @serpent5   Fixed by https://github.com/dotnet/aspnetcore/pull/18296
