### ISSUE TITLE
Blazor Default Server-Side Template Uses Deprecated app HTML Tag

### ISSUE THREAD

**Issue by Mike-E-angelo** [dotnet/aspnetcore#11013]
### Describe the bug
The default server-side Blazor template appears to include a deprecated HTML5 tag: the `app` tag.

### To Reproduce

1. Create a server-side template
2. Navigate to `~/Pages/_Host.cshtml`
3. Deprecated `app` tag should be on line `25`.

### Expected behavior
Something besides an `app` tag or no `app` tag at all. 😊  

Perhaps `<div class="application">...</div>` ?  

### Additional context
https://html.com/tags/app/

**Comment by mkArtakMSFT** [comment]
Closing this as this seems to be supported and people can choose to use the proposed approach.

**Comment by Mike-EEE** [comment]
@mkArtakMSFT "seems to be" or is?  Based on the provided link this is not a supported tag and if there is support it is probably for legacy reasons.  Providing a link with more information would be greatly appreciated.

Also, I am also in the dark with regards to the proposed approach.  Shedding some additional context would be greatly appreciated as well.  Thanks in advance.

**Comment by Mike-EEE** [comment]
A couple of obvious concerns here:

- The templates here are used by every developer who will touch Blazor.  They should be providing the best guidance.  These templates will, of course, be copy/pasted to the ends of Earth so they should have the best guidance and implementation possible.
- By using deprecated/inaccurate HTML5 or simply not following the HTML5 specification, you make MSFT look bad.
- Subsequently, other non-MSFT HTML5 developers will see this and wonder why you are using non-compliant tags and question your chops.  If you cannot use compliant tags, what else are you doing that's questionable?  Of course, they will not say anything as they will prefer you to maintain your ignorance as much as possible.

**Comment by mkArtakMSFT** [comment]
@Mike-EEE we're a small team trying to focus our efforts on critical and most important issues only. This one is not really a blocker in any way, and given the priority of it realize that we won't get to this even in the near future.
The suggestion you have with the `<div>...` tag is an option you can build.

**Comment by Mike-EEE** [comment]
Cool, thank you for the extended context and explanation, @mkArtakMSFT.  Would you be willing to allow a PR around this if I can figure out how to make one? 😇

**Comment by mkArtakMSFT** [comment]
That would be great.
@SteveSandersonMS what do you think it would make sense to replace the current `<app>` tag with?

**Comment by Mike-EEE** [comment]
FWIW I have created a draft (in every sense of the word 😆) PR for this, simply to test the capacity of doing so, but to also gauge where exactly I should be editing and which files I should be modifying.  

I have also applied my suggestion of the `<div class="application" />` as above but, of course, is subject to change if we can think of something better.

Thank you in advance for any additional assistance and/or consideration around this issue. 👍

**Comment by mkArtakMSFT** [comment]
We'll remove the `app` tag completely.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by Mike-E-angelo** [comment]
Looks like this is no longer an issue in the latest `5.0.0` templates:

![](https://i.imgur.com/my82VfS.png)

I will close this issue now.  

But before I do so, I wanted to give a GINORMOUS shout of respect and appreciation for all your diligent work out there.  I am finally coding my first client application since 2011.  Think of that!  Nearly a full decade.  And yes, if we're talking 2011 we're talking Silverlight.

I have been nose/brain-deep into Blazor for the past year and it has been truly something.  HTML isn't as pretty as Xaml, of course, but the architecture/design of Blazor far and away makes up for it.  

That parsing engine, tho.  https://twitter.com/Mike_E_angelo/status/1322595036006068224

Anyway, thanks again, team!  Continue the greatness. 🙏
