### ISSUE TITLE
Blazor build should fail noisily if required files are missing

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#11034]
The experience is pretty poor right now when the Blazor build can't produce all of it's required files.

For one of the users in our workshop, his antivirus was deleting `blazor.boot.json` (or preventing it from being written). This made parts of our build no-op and made his site fail to load.

He was using https://www.comodo.com/home/internet-security/security-software.php

**Comment by marin-bratanov** [comment]
This may be related #18752

**Comment by mkArtakMSFT** [comment]
Closing this as we think the current experience of failing at runtime is ok for now.
