### ISSUE TITLE
Add gRPC interop tests to our PR test suite 

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#11064]
Investigate adding gRPC interop tests. These should not be mandatory.

**Comment by Pilchie** [comment]
@JamesNK @JunTaoLuo I'm guessing this isn't happening for Preview 9 at this point?

**Comment by JamesNK** [comment]
@JunTaoLuo You're the best out of the two of us to do this one. Do you think you'll have time for it in the next couple of weeks?

**Comment by Pilchie** [comment]
@JamesNK started a mail thread about this, so assigning him.  Moving to the 5.0.0-preview1 milestone as well.

**Comment by JamesNK** [comment]
### Reasons

1. Verify ASP.NET Core/Kestrel changes in the next .NET Core release aren't accidentally breaking gRPC
2. Verify gRPC runs on HttpSys/IIS (note: grpc-dotnet build server is Linux only so not possible to test there)

2 is particularly important. HttpSys work is happening now and it takes a long time to get changes in Windows. If we need changes then we have to discover them now and tell the correct teams. The interop tests provide a cross-section of major functionality to double-check we're compatible. There are only about 20 tests, and they take about 10 seconds to run.

### How

Run [interop client](https://github.com/grpc/grpc-dotnet/tree/master/testassets/InteropTestsClient) against [interop server](https://github.com/grpc/grpc-dotnet/tree/master/testassets/InteropTestsWebsite) to execute tests. In the official gRPC interop test environment the client is called from the command line. I think for our CI build we should just have a single parameterized unit test that will start the server, and create an InteropClient instance which is passed arguments for each test. That should work for Kestrel, and maybe HttpSys. Will need to investigate what to do for IIS functional testing.

The interop client and server are both small self-contained apps, and should rarely - if ever - change. We can just copy and paste them from grpc-dotnet into aspnetcore and make minor edits to them as needed (the grpc-dotnet versions themselves were copied from grpc/grpc).

**Comment by Pilchie** [comment]
Reverted the change, so re-opening.

**Comment by JunTaoLuo** [comment]
This was re-added by https://github.com/dotnet/aspnetcore/pull/20069
