### ISSUE TITLE
Generate manifests for insertion of aspnetcore runtime into Visual Studio

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#11072]
We are working with the SDK team to simplifying the insertion of the .NET Core SDK into Visual Studio. dotnet/core-sdk#2166 Today, the ASP.NET Core runtime is inserted into VS via the .NET Core SDK. As a part of breaking the SDK into smaller pieces, we need to add a new builds step to 3.0 build which generates a .vsman manifest for insertion into Visual Studio.

### Work items
- [ ] Generate a .vsman file during build
- [ ] Automate uploading ASP.NET Core runtime installers (msi) and their .vsman file into VSDrops
  * Shared framework MSI
  * Targeting pack MSI
  * ANCM IIS Express MSI (note: these are not the ANCM installers for full IIS)

### Notes:
* We might also take on doing the PRs into Visual Studio at some point, but not yet. Still working with @johnbeisner to clarify/coordinate ownership of insertions of .NET Core into Visual Studio
* Depends on support in arcade for generating a .vsman file for our MSI files. Preliminary support exists, but only for .VSIX files

Related https://github.com/aspnet/AspNetCore-Internal/issues/1576 - it's worth considering applying the same approach to the ANCM installers

cc @Pilchie @aspnet/build @anurse

**Comment by anurse** [comment]
I was mid-typing that we should do this for ANCM when I finished reading :). Yes, let's definitely try to do this for ANCM at the same time. Ideally, we'd probably want to insert ANCM at the same time as the SDK for 3.0.

**Comment by anurse** [comment]
Let's officially make this cover ANCM as well (we can help make it happen). It should just be a matter of pointing it at one more set of MSIs (the ANCM installers). If not, we can split it later.

**Comment by rynowak** [comment]
BTW - we have done all of this stuff in AspNetCore-Tooling. The `.vsman` thing is done by arcade as part of the VSIX build. The VSDrop and VS PR functionality is in a release pipeline

**Comment by anurse** [comment]
Nice, we just need support for doing it from MSIs, since we don't have VSIXes for these components (they're global installs). @natemcmaster happy to provide some support if you need it, we really want to automate insertions as much as possible.

**Comment by natemcmaster** [comment]
@rynowak - yup, thanks for blazing a trail here. I've been looking at what you did for the AspNetCore-Tooling repo and sharing it with the Arcade team as a model of something we want to apply to this and other repos that need to insert into VS>

But yes, as mentioned above, completing this depends on support in arcade for generating a .vsman file for our MSI files. Preliminary support exists, but only for .VSIX files

In the short term, @johnbeisner is working on a VS PR that would use .nupkgs which wrap our MSIs instead (see #11071 )

**Comment by natemcmaster** [comment]
Marking this one as blocked until we can get Arcade support for generating a vsman file for .msi's. 

https://github.com/aspnet/AspNetCore/issues/11071 tracks generating nupkgs as a short-term fix.

**Comment by rynowak** [comment]
> @rynowak - yup, thanks for blazing a trail here. I've been looking at what you did for the AspNetCore-Tooling repo and sharing it with the Arcade team as a model of something we want to apply to this and other repos that need to insert into VS>

😊 - you're making me blush. Feel free to put me in touch with whomst've'ever is looking at this.

**Comment by anurse** [comment]
I'll find someone ;)

**Comment by anurse** [comment]
@dotnet/aspnet-build do you know what our status here is? I believe we are successfully inserting our runtime into VS, are we still using the nupkg-based hack referenced above? Or do none of you know and I should go chase other leads to figure this out? :)

**Comment by wtgodbe** [comment]
I'm not sure about this one - @livarcocc @dougbu was this what you two were discussing regarding our OSX installers over email recently?

**Comment by dougbu** [comment]
We push at least some of the packages to the VSDrops repo directly but I'm pretty sure we have no .vsman logic in aspnetcore -- the keyword doesn't match any code.

This also seems to overlap with #14045 (assigned to @JunTaoLuo).

Should we discuss this in Department of Infrastructure or Build / Leads sync?

**Comment by JunTaoLuo** [comment]
Sounds like we were waiting for a feature from Arcade to get the .vsman file generated? I took a look in our builds and it looks like we are not generating this file at the moment. I'm assuming that @jkotalik has done the required work for wrapping via nupkg in https://github.com/dotnet/aspnetcore/issues/11071 in the mean time.

**Comment by anurse** [comment]
Do we have anything tracking the necessary work in Arcade? @dotnet/aspnet-build are we currently doing *something* automated to push our shared framework to the VS feed?

**Comment by dougbu** [comment]
We push our VS.Redist.* packages into the VS feed e.g. https://dev.azure.com/dnceng/internal/_build/results?buildId=561858&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=e6eb9397-ba71-59b2-f76c-d069fa554d12&l=25 and it looks like the other points above are resolved. Is there any reason to keep this open anymore?

**Comment by anurse** [comment]
> Is there any reason to keep this open anymore?

I think this was tracking producing a `.vsman` file to aide insertions, but I'm not sure we need to do that now. Who is running insertions of our runtime in to VS?

**Comment by Pilchie** [comment]
So far the CLI team (@dsplaisted and @wli3) have been doing this, but I don't think that's the desired long-term state.

**Comment by anurse** [comment]
Right, in tneory we should be able to do an insertion ourselves using only artifacts we produce. I'm not yet clear on what additional artifacts we need to provide though. Perhaps this `.vsman` file is the (or at least 'a') missing link?

**Comment by dougbu** [comment]
@wtgodbe and @NTaylorMullen this is done isn't it❔

**Comment by wtgodbe** [comment]
I don't know that we've done the work to produce a `.vsman` file yet - @dsplaisted @wli3 is that still desired?

**Comment by dsplaisted** [comment]
@joeloff should probably know

**Comment by joeloff** [comment]
It might be. We previously looked at simplifying the insertion process using VSDROP. There were some issues because we focused on keeping things centralized in the SDK. I'm working on a new proposal that should simplify this significantly and will send it out for feedback this week.

**Comment by dougbu** [comment]
> will send it out for feedback this week.

Not sure I saw anything about this. But, in any case, it appears this issue is no longer relevant. Closing&hellip;
