### ISSUE TITLE
Remove or document python2 dependency in ProjectTemplate.Tests

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#11121]
### Is your feature request related to a problem? Please describe.

AngularTemplateTests.AngularTemplate_Works() in ProjectTemplate.Tests seems to install some node module that depends on running [GYP](https://gyp.gsrc.io/) which in turn depends on python2. If you do not have python2 on the path when running the test, the test will fail. I did not catch which nod module was running GYP.

### Describe the solution you'd like

Remove the python2 dependency for running ProjectTemplate.Tests.

### Describe alternatives you've considered

Add the python2 dependency to the ProjectTemplate README.

### Additional context
@ryanbrandenburg asked me to file this issue.

**Comment by ryanbrandenburg** [comment]
Quick research suggests the culprit is likely node-sass which is an optional dependency of our Angular templates (but not of the default `ng new` templates.)

**Comment by dougbu** [comment]
Issue is no longer relevant because the tests no longer exist
