### ISSUE TITLE
Question: GC Time

### ISSUE THREAD

**Issue by yahorsi** [dotnet/aspnetcore#11135]
Hi Guys!

I did a research and didn't find anything on that more or less simple wish.

It would be really cool to have an ability to record how much time is spent in GC, for the particular request, while that request was executing. If that is somehow possible we could return that info back to the client in e.g. header to be able to simplify perf debugging.

Thank you

**Comment by samsosa** [comment]
The garbage collection runs asynchronously and is not bound to a single request, instead it works on a more global level.

**Comment by yahorsi** [comment]
Let me clarify questions. Imagine the real life scenario, we have requests that takes aprox 100ms to execute. We know part of that time is time taken to execute some TSQL. We also know juring request execution we do allocate some memory. What we don't know is what is the persentage of the request time, request thread(s) were blocked by GC. Having such number will give us clear answer on is it worth investing time and money in optimizing mem allocks.

**Comment by DAllanCarr** [comment]
It's an interesting idea and EventPipe will allow you to listen to collection states. But regards to server and background GC the time spent would be minimal compared to executing a database call so I am not sure where the optimization would take effect.

**Comment by yahorsi** [comment]
> am not sure where the optimization would take effect.


Exactly, and we too. So we need to understand what is GC impact right now. Having time spent on allocations would be great as well.

**Comment by DAllanCarr** [comment]
I suppose the question is what would GC impact give us? In a finely tuned application nothing in user code should survive Gen0 and Server GC is optimized for that. I would expect questions would need to be asked if Gen1 and Gen2 is being over allocated. Something like a high water mark for when a possible Full GC is about to happen. But determining this would still be a best guess.

**Comment by davidfowl** [comment]
I would love something like this and it something I hope to push for (the ability to determine where time is spent during a request with a break down of how much time is spent in your code or in various subsystems in the runtime) but it's not something you can easily build today (at least without significant overhead). .NET Core 3.0 does have event pipe as @DAllanCarr mentions but there might not be enough events to build something like that, at least not yet.

**Comment by yahorsi** [comment]
> I would love something like this and it something I hope to push for (the ability to determine where time is spent during a request with a break down of how much time is spent in your code or in various subsystems in the runtime) but it's not something you can easily build today (at least without significant overhead). .NET Core 3.0 does have event pipe as @DAllanCarr mentions but there might not be enough events to build something like that, at least not yet.

Even for very basic things? Just like GC time total and e.g. Total Time per request spent in allocations?

**Comment by davidfowl** [comment]
> Even for very basic things? Just like GC time total and e.g. Total Time per request spent in allocations?

You can easily get process wide information using the new event counters in 3.0. There's nothing as granular as getting pause time per request.

**Comment by yahorsi** [comment]
> > Even for very basic things? Just like GC time total and e.g. Total Time per request spent in allocations?
> 
> You can easily get process wide information using the new event counters in 3.0. There's nothing as granular as getting pause time per request.

Am I right Server GC blocks all threads? If so, we can try to collect data and then just filter GC events that were inside request start/end. I mean that server GC pauses all threads and so all currently executing requests. The only exception is when request is currently waiting for IO to complete, then it is not affected by GC (means requests won't take less time if there was no GC).
