### ISSUE TITLE
JS interop should not require assembly-wide unique IDs for instance methods

### ISSUE THREAD

**Issue by francotiveron** [dotnet/aspnetcore#11131]
Two DIFFERENT Blazor components define the following instance method:
```
[JSInvokable]
public void MyInstanceMethod()
{
...
}
```
At load time they call a js function, passing themselves to js:
```
await JS.InvokeAsync<object>("jsFunction", new DotNetObjectRef(this));

```
In js, the passed .NET object reference is saved in a variable named _callback.
Later, an event occurring in javascript calls back the instance method
```
_callback.invokeMethodAsync("MyInstanceMethod");

```
The browser console fails with the following error:
```
blazor.webassembly.js:1 Uncaught (in promise) Error: 
System.InvalidOperationException: 
The assembly 'WebApplication7.Client' contains more than one [JSInvokable] method 
with identifier 'MyInstanceMethod'.
All [JSInvokable] methods within the same assembly must have different identifiers.
```
BTW, everything goes well if only one component has the method.

Isn't this a violation of one of the fundamental scope features in any OO language?

Can anybody tell me why methods, including instance methods, are required to have different identifiers to be JSInvokable? 

If this is a limit of Blazor, is there a plan to fix it?

**Comment by SteveSandersonMS** [comment]
Sounds like a bug. Thanks for reporting it.

It makes sense to require `static` methods to have assembly-wide unique identifiers. However it doesn't make sense that instance methods need assembly-wide unique identifiers. We should only require the identifier to be unique within the type of the instance you're passing.

As a workaround, you could do something like:

```cs
[JSInvokable("SomeUniqueIdentifier")]
public void MyInstanceMethod()
{
...
}
```

I know it's annoying to need a workaround like this. We'll fix the underlying bug (most likely after 3.0 ships).

**Comment by glararan** [comment]
Today I met with this bug. It should be fixed soon because blazor still lacks few features so we have to use JS implementation.

**Comment by mkArtakMSFT** [comment]
@pranavkm did you already fix this? Close if so.

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/extensions/issues/1360.
