### ISSUE TITLE
Cook does not see the server

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#11158]
Hello! Application .netcore 2.2 I.m set cook on webbrowser document.cookie="asdf=Vasya;path=/;"
Server: var cookie = context.Request.Cookies; cookie.Count=1; Ok!
I,m delete cook.
document.cookie="asdf=Vasya P;path=/;"
Server: var cookie = context.Request.Cookies; cookie.Count=0; Oh no!
Why?

**Comment by anurse** [comment]
Cookie values can't contain unescaped whitespace:

> A &lt;cookie-value> can optionally be set in double quotes and any US-ASCII characters **excluding** CTLs, **whitespace**, double quotes, comma, semicolon, and backslash are allowed. Encoding: Many implementations perform URL encoding on cookie values, however it is not required per the RFC specification. It does help satisfying the requirements about which characters are allowed for &lt;cookie-value> though.
>
> - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by jkotalik** [comment]
Closing as this has been answered.
