### ISSUE TITLE
[Helix] Figure out why functional tests aren't publishing properly on arm/linux builds

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#11205]
Disabled:
`Microsoft.AspNetCore.Authentication.AzureAD.FunctionalTests.csproj`
`src/Security/test/AuthSamples.FunctionalTests/AuthSamples.FunctionalTests.csproj`
`src/Identity/test/Identity.FunctionalTests/Microsoft.AspNetCore.Identity.FunctionalTests.csproj`

on arm64 helix runs until issues around publishing their test assets for these queues are resolved

**Comment by dougbu** [comment]
@HaoK has this issue been resolved in the year and a half since you opened it❔ Please close if yes

**Comment by HaoK** [comment]
I'll give it a try, its possible https://github.com/dotnet/aspnetcore/issues/27296 helped

**Comment by dougbu** [comment]
@HaoK did something go wrong in #30087❔ Mostly wondering why AuthSamples.FunctionalTests.csproj and Microsoft.AspNetCore.Identity.FunctionalTests.csproj remain disabled on Helix ARM and point to this (closed) issue.

**Comment by HaoK** [comment]
I don't remember exactly anymore, but I believe the tests just fail when run on arm64, so they publish now, but they don't work, this is likely something that will get resolved once the arm64 work is done

**Comment by HaoK** [comment]
I added these to the meta item work item https://github.com/dotnet/aspnetcore/issues/39281
