### ISSUE TITLE
the ASPNetCore original API template project is missing the 'Store user accounts in-app' Authentication

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [dotnet/aspnetcore#11216]
the ASP Net Core 3 preview 6 original API template project in Visual Studio 2019 Community 16.1.3 is missing the 'Store user accounts in-app' authentication option for `Individual User Accounts`.

Just open visual studio and start creating a new ASP Core API project with `Individual User Accounts` authentication
There is will be only one option and that is `Connect to an existing user store in the cloud`

### Screenshots
![image](https://user-images.githubusercontent.com/7858946/59496264-5b9e1680-8e91-11e9-9355-7f2a6eb9ecfe.png)

**Comment by blowdart** [comment]
This is expected. You can create an API project with Identity Server as an in app store at the command line, not within the UI

**Comment by ahmedflix25** [comment]
i don't know how is this expected i should be able to do so from within visual studio the old one let me and the other new templates still do like mvc angular reactjs etc but even so the command line doesn't offer an option to do it when creating a new webapi project

for the WebAPI
![image](https://user-images.githubusercontent.com/7858946/59509054-3ff63880-8eb0-11e9-8c88-f6807871cf30.png)

for Angular
![image](https://user-images.githubusercontent.com/7858946/59509162-919ec300-8eb0-11e9-8a04-0d15e6bd4e51.png)

it's also offer the option from within visual studio for Angular ReactJS and Blazor but not the WebAPI
![image](https://user-images.githubusercontent.com/7858946/59509286-e7736b00-8eb0-11e9-984b-e85f33df45dd.png)

also the MVC template project from within visual studio and command line offers all of them
![image](https://user-images.githubusercontent.com/7858946/59509700-0faf9980-8eb2-11e9-9abb-fceb0698da11.png)
![image](https://user-images.githubusercontent.com/7858946/59509725-1fc77900-8eb2-11e9-87f2-9d985c0a7316.png)

**Comment by blowdart** [comment]
It's only in .NET Core 3 previews. Have you installed that?

And there's always a lag before things appear in a VS UI as we, hopefully, get feedback from the community on how things are implemented. There's no point in going through the pain of adjusting the VS UI until the templates are set

**Comment by javiercn** [comment]
Individual user accounts is only available through the SPA templates. We don't have support in the API template at this time.

**Comment by blowdart** [comment]
Oh heck yes, my bad.

**Comment by ahmedflix25** [comment]
> 
> 
> It's only in .NET Core 3 previews. Have you installed that?
> 
> And there's always a lag before things appear in a VS UI as we, hopefully, get feedback from the community on how things are implemented. There's no point in going through the pain of adjusting the VS UI until the templates are set

yes, you can check the net core version being used from the right bottom corner of the screenshot of visual studio

**Comment by ahmedflix25** [comment]
> 
> 
> Individual user accounts is only available through the SPA templates. We don't have support in the API template at this time.

seems about right i checked all the dot net core template project from version 1 to 3 preview 6 and the webapi doesn't support it.

any plans adding it for the dot net core 3.0 release or 3.1?

**Comment by blowdart** [comment]
Sorry for leading you astray, I should stop triaging issues before coffee :)

We've been thinking about it, but getting it into spa templates was the big push for 3.0.

It might make it, but right now it's not a high priority because it's a bit of an oddity, because if you create it and hit f5, well, there's nothing, you'll get a 401 which won't see in the browser. The template, if working as expected, would look broken. 

Until we have a repl, and one that supports an oauth dance it'd be hard to have something that is usable immediately upon creation.

**Comment by ahmedflix25** [comment]
> 
> 
> Sorry for leading you astray, I should stop triaging issues before coffee :)
> 
> We've been thinking about it, but getting it into spa templates was the big push for 3.0.
> 
> It might make it, but right now it's not a high priority because it's a bit of an oddity, because if you create it and hit f5, well, there's nothing, you'll get a 401 which won't see in the browser. The template, if working as expected, would look broken.
> 
> Until we have a repl, and one that supports an oauth dance it'd be hard to have something that is usable immediately upon creation.

no problem, but first you should take a look at the dot net framework web api project with individual user accounts because that how everyone from asp.net 5 expect it to be at least that what i think.

**Comment by blowdart** [comment]
Yes, that gap has been a long standing problem. The solution is, frankly, Identity Server, it's what we've recommended for Core, and we didn't want to start reinventing the wheel. Our integration will probably be a slightly simpler configuration were we hide the complications for very simple, streamlined scenarios to get folks started.

So if you need it now, use the templates Identity Server provides :)

**Comment by ahmedflix25** [comment]
no i was just trying wpf core and core webapi for the first time making a simple project and was just surprised it wasn't there by default so i came to report it

**Comment by blowdart** [comment]
And thanks for reminding me. I need to find a way to write up why it's not there right now, so it's not a surprise. It will come at some point, but just not now. So I'll pop this into backlog as a reminder.

**Comment by ahmedflix25** [comment]
is this going into net core 3.1 or .net 5?

**Comment by imukai** [comment]
Just spent 30+ minutes trying to figure out why none of the Identity scaffolding was appearing in a new project (created from the UI) and came to find this thread -- and now I'm disappointed that anything would ship in this state.

**Comment by ahmedflix25** [comment]
the sad thing is now one cared enough to check on it since .net core released @imukai

**Comment by UlissesMeira** [comment]
> Sorry for leading you astray, I should stop triaging issues before coffee :)
> 
> We've been thinking about it, but getting it into spa templates was the big push for 3.0.
> 
> It might make it, but right now it's not a high priority because it's a bit of an oddity, because if you create it and hit f5, well, there's nothing, you'll get a 401 which won't see in the browser. The template, if working as expected, would look broken.
> 
> Until we have a repl, and one that supports an oauth dance it'd be hard to have something that is usable immediately upon creation.

Maybe a template can deliver a collection of Postman for test.. working like a MockServer... i think thats can be a idea..

**Comment by duaneking** [comment]
So I am on version five in this is still an issue and I don't have any beta bits installed at all that I'm aware of because I only install production updates.￼

**Comment by ahmed-abdelrazek** [comment]
@duaneking yes, and i don't think they are going to add it anytime soon

**Comment by mkArtakMSFT** [comment]
This is now simpler given the new [Identity APIs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.identityapiendpointroutebuilderextensions.mapidentityapi?view=aspnetcore-8.0) that were added in .NET 8.
We don't have plans to expose an option though through the template at the moment.

**Comment by ahmed-abdelrazek** [comment]
lol i forgot this one
for any one that still looking at the end of 2023 https://devblogs.microsoft.com/dotnet/whats-new-with-identity-in-dotnet-8/
