### ISSUE TITLE
Write an analyzer for TaskCompletionSource(TaskContinuationOptions.RunContinuationsAsynchronously)

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#11329]
We have a recurring bug that would make good practice for an analyzer.
https://github.com/aspnet/AspNetCore/pull/11294/files
```
new TaskCompletionSource<object>(TaskContinuationOptions.RunContinuationsAsynchronously);
vs
new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously);
```

**Comment by anurse** [comment]
This isn't servers, it's infrastructure. Updating.

**Comment by dougbu** [comment]
Is this now a CSharp analyzer @mavasani @sharwell ❔

**Comment by dougbu** [comment]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2247 covers this. Microsoft.CodeAnalysis.FxCopAnalyzers should enable the rule automatically.
