### ISSUE TITLE
[Blazor Server Side] Setting @layout on _Imports.razor' project root folder freezes the project -- the browser page keeps loading forever

### ISSUE THREAD

**Issue by baartho** [dotnet/aspnetcore#11406]
### Describe the bug
After setting the @layout on the root folder _Imports.razor file my project builds, no errors/exceptions are thrown, but the project keeps loading forever. 

If I remove the @layout declaration the issue stops happening.

### To Reproduce
1. Create a new ASP.NET Core Blazor 3.0 Preview 6 Server Side project
2. Open _Imports.razor on the project root folder
3. Add a layout declaration. Ej: @layout MainLayout
4. Run the project

### Expected behavior
The browser keeps loading the page forever 

### Screenshots
![image](https://user-images.githubusercontent.com/19720384/59815984-bbad1680-92f0-11e9-88a5-50afb0919e3a.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @baartho.
@ajaybhargavb can we check for this and error out instead? How hard will it be? If it's extra-small work item, we may try to do that at some point in the future. If not, we may not even do it given how corner case this is.

**Comment by AndrewPlakhotnyi** [comment]
Just spent several hours on this issue. It happens all the time when `_Imports.razor` imports a `@layout` within the same folder. This will often happen when people refactor their code by moving around *.razor files. Very hard to understand the cause because the app just hangs without any error.

**Comment by netleader** [comment]
This also happens to me.
As soon as I add a @layout to the _Imports.razor the app hangs.

Very annoying

**Comment by mkArtakMSFT** [comment]
Bringing this back to triage

**Comment by mkArtakMSFT** [comment]
We will consider adding some type of error in situations, where an infinite loop cycle exists in layouts.

**Comment by mkArtakMSFT** [comment]
We don't think this is something we'll do in the near future. If this will be impacting more users, we will reconsider.
