### ISSUE TITLE
Blazor Client - lightweight JWT to ClaimsPrinicpal

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#11417]
### Is your feature request related to a problem? Please describe.
With the new `AuthenticationStateProvider` we can now return a `ClaimsPrincipal` for the current authentication session, which is great.

BlazingPizza app [has a simple implementation](https://github.com/dotnet-presentations/blazor-workshop/blob/1c35728a9cafb1add72e14fae88dd037216913d7/save-points/06-add-authentication/BlazingPizza.Client/ServerAuthenticationStateProvider.cs) of this which uses CookieAuthentication and a request to the server - which is certainly one way to do things.

For my application, the backend is a pure Web API, and I do not use cookie authentication, I use a fairly simple /login endpoint that returns a `JWT` authentication token, which is then cached on the client, and appended to requests as a BEARER authentication header. 

With the advent of `AuthenticationStateProvider` all I need to do is have it get my JWT token from this cache, and then decode it to return a `ClaimsPrinicpal`.

All the solutions I have seen for decoding a JWT token and obtaining a claims prinicpal use the `JwtSecurityTokenHandler` class from `System.IdentityModel.Tokens` - which looking at NuGet is still tied to `Newtonsoft.Json`: https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/

I've switched my client side app to use `System.Text.Json` because I am trying to keep it lightweight and use what is natively available and not inflate the size of the application too much. So having to pull in `System.IdentityModel.Tokens` and `Newtonsoft.JSON` for this one case of dealing with JWT's leaves a bitter taste.

Before I have to write my own JWT to Claims prinicpal conversion method, i'd like to know if you could improve support for this - perhaps my including a method for doing this in the framework, or updating `System.IdentityModel.Tokens` so that it isn't dependency on Newtonsoft ?

Or perhaps there is an alternative I should be considering?

### Describe the solution you'd like
A lightweight mechanism to decode a JWT token in order to then construct a ClaimsPrincipal in Blazor client side apps.

### Describe alternatives you've considered
- `System.IdentityModel.Tokens` (dismissed due to newtonsoft.json dependency)
- Writing my own

**Comment by dazinator** [comment]
Was able to write a method to get access to claims informarion from a JWT.  Roughly:

```
var jwt = "header.payload.sig" // replace this with your jwt.

string[] jwtEncodedSegments = jwt.Split('.');
var payloadSegment = jwtEncodedSegments[1];

var decodePayload = System.Convert.FromBase64String(payloadSegment);
var decodedUtf8Payload = Encoding.UTF8.GetString(decodePayload);
           
var result = System.Text.Json.Serialization.JsonSerializer.Parse<Dictionary<string, JsonElement>>(decodedUtf8Payload)

```

Then loop through the dictionary and build a lost of Claims up.

Not sure if this is the best or most efficient way but it serves my needs. I'll leave this issue open though for you to consider providing something for decoding JWT's in the framework.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by dazinator** [comment]
With the most recent blazor release and the new TokenAuthentication stuff - there is a possibility this was done, and could be closed now. Need to investigate the new token authentication stuff and whether there is a method for decoding JWT tokens provided.

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know. If you still think there's further work we need to do here, could you please clarify what? If not, no need to reply, as it will auto-close in a few days.

**Comment by dazinator** [comment]
@SteveSandersonMS 
I don't think the framework provides anything explicitly for parsing / deserializing JWT access token strings, and turning them into a collection of Claims, but saying that, I'm happy to stick to using my own method. Closing.
