### ISSUE TITLE
Better Error Message for restore.cmd

### ISSUE THREAD

**Issue by DylanDmitri** [dotnet/aspnetcore#11465]
### Is your feature request related to a problem? Please describe.
Tried to run `./restore.cmd` and received the following error

```
.\restore.cmd
C:\Users\t-dygra\Desktop\AspNetCore\build.ps1 : The environment variable JAVA_HOME was set, but C:\Program
Files\Java\jdk-11.0.2\bin\javac.exe does not exist. Remove JAVA_HOME or update it to the correct location for the JDK.
See https://www.bing.com/search?q=java_home for details.
At line:1 char:126
+ ... ulture = '';& 'C:\Users\t-dygra\Desktop\AspNetCore\build.ps1' -all -n ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build.ps1
```

Followed the advice in the error message, searched JAVA_HOME, found Oracle docs, followed the Oracle docs, installed Java, updated my environment variables. Still didn't work.

Looked around more, found [these docs](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md), saw that there's an included Java install script. Ran `./eng/scripts/InstallJdk.ps1` as recommended, and it fixed the problem.

### Describe the solution you'd like
If `Restore.cmd` fails in this way, it should recommend that the user run the included InstallJDK script. This helps remove friction for new contributors.

### Describe alternatives you've considered
Maybe restore should run the script automatically if it encounters this error.

**Comment by dougbu** [comment]
We're not going to get to this experience issue
