### ISSUE TITLE
[Discussion]: ConnectionAdapters have been removed from Kestrel

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#11475]
This is the discussion for https://github.com/aspnet/Announcements/issues/371

**Comment by davidfowl** [comment]
cc @Drawaes because you're the one person I know that wrote one of these 😄

**Comment by Drawaes** [comment]
I have several not just one, but that's cool I am sure I can adapt to it ;)

**Comment by davidfowl** [comment]
Actually, you may be able to use the new negotiate auth feature in ASP.NET Core 3.0. The protocol switcher is trivial to do with pipelines 😄
