### ISSUE TITLE
How do i select a transport type in the signalr client c++ ?

### ISSUE THREAD

**Issue by proga7med** [dotnet/aspnetcore#11477]
I have a hub connection and i want to select a transport type. i don't see any method for that.
but i noticed that there are 2 classes, http_client and websocket_client. should i use one of them instead of hub connection to select the transport type or currently it doesn't support ?

**Comment by captmomo** [comment]
the HubConnectionBuilder .WithUrl lets you state the transport type. I believe you also pass in a list of transport types for the httpclient.  
  Example:
`            _connection = new HubConnectionBuilder()
                .WithUrl(_hubRoot, Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets)
                .Build();`

**Comment by BrennanConroy** [comment]
There is only the websockets transport currently for the C++ client.
