### ISSUE TITLE
Add Streaming API support to MVC

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#11558]
See previous discussions here - https://github.com/aspnet/AspNetCore/issues/4833

This depends on:
- [ ] Add support for asynchronously (de)serializing IAsyncEnumerable<T> https://github.com/dotnet/runtime/issues/1570

**Comment by mkArtakMSFT** [comment]
It's not clear what's being asked here. Closing, until we have a concrete proposal here.

**Comment by mkArtakMSFT** [comment]
This work depends on https://github.com/dotnet/runtime/issues/1570

**Comment by bradygaster** [comment]
Can confirm with @mkArtakMSFT this is in the right spot. Also can confirm this and  https://github.com/dotnet/runtime/issues/1570 would be very-very nice-to-have items. Anything that makes it easier [more elegant, discoverable, yada^2] is a good thing IMO.

**Comment by mkArtakMSFT** [comment]
We're still waiting for the above referenced issue from the dotnet/runtime repo to be delivered to be able to get to this. Synced up with @ericstj and that is going to land no sooner than 6.0-preview4, so we're still blocked here.
