### ISSUE TITLE
Unable to locate the .NET Core SDK

### ISSUE THREAD

**Issue by huysentruitw** [dotnet/aspnetcore#11566]
Today, when running `.\restore.cmd` or `.\build.cmd`, I ran into this error:

```
error : Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
```

After some digging, I've found out because of a fresh install of VS2019 which didn't already had _Use previews of the .NET Core SDK_ checked. As you can image, I've lost some time because of that and I wondered if we can document this in f.e. `BuildFromSource.md`, `BuildErrors.md` or even expand the `build.ps1` script so it outputs the suggestion into the console when that error occurs.

Related issue: https://github.com/dotnet/arcade/issues/3035

Thoughts?

**Comment by anurse** [comment]
Sounds good. Would you like to submit a PR?

**Comment by huysentruitw** [comment]
I want to, Yes. Any suggestion for which solution you want to go?

**Comment by anurse** [comment]
I don't see why we couldn't just take the same blurb and put it in both `BuildFromSource.md` and `BuildErrors.md`. The first one is linked from the README, and the second is where you might go upon getting the error.

Expanding the `build.ps1` is a larger work item. Maybe if we knew what underlying data that checkbox was using (registry value or something) we could emit a clearer warning, but that seems like a more complicated solution.

**Comment by dougbu** [comment]
Fixed a while ago. See https://github.com/dotnet/aspnetcore/blob/master/docs/BuildErrors.md#error-msb4236--unable-to-locate-the-net-core-sdk
