### ISSUE TITLE
Allow the option to delay sending headers until at least resource filters are fired

### ISSUE THREAD

**Issue by aliostad** [dotnet/aspnetcore#11585]
## Context
Currently, ASP.NET Core sends headers as soon as possible and allows for various hooks (OnStarting, etc) to register actions to be taken before sending headers. This is for improving performance and understandably solves most use cases while maintaining a high performance.

There are cases, however, when these options do not work and response buffering needs to be implemented. However, this seems extreme especially for filters (in my case Resource Filter) where we are really dealing with MVC abstractions in their in-memory object form rather than IO streams. As such, there should be a built-on option not to send headers rather than the heavy-handed buffering by the clients. 

## Previous Conversations
So the conversation on twitter on the subject with @davidfowl is here (where David agreed for the feature to be discussed here and potentially implemented):
https://twitter.com/davidfowl/status/1140739141342302208

## Proposed solution
Allow setting a flag to make it safe (i.e. not to send headers) to change payload/headers while we are still in Filters (especially Resource Filters).

**Comment by Tratcher** [comment]
@rynowak What's the rationale for moving this to servers? It seems specific to MVC's filters layer.

**Comment by rynowak** [comment]
I spoke to @davidfowl and his plan for this was to create a scoping construct for buffering like: 

```C#
using (DoBuffering(HttpContext))
{
    // Do stuff that *might* write to the request here.
}
```

Or a pair of middleware that do the same.

**Comment by davidfowl** [comment]
I specifically don’t want a middleware. I just want to make the logic that @pranavkm wrote in the formatter easier to write without requiring a middleware in the pipeline.

**Comment by davidfowl** [comment]
We have this logic now in the FileBufferWriteStream but it's not trivial to wire up. I filed an issue for this https://github.com/dotnet/aspnetcore/issues/31146
