### ISSUE TITLE
Build blazor.*.js in CI; don't commit the artifacts

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#11592]
At some point in the recent past, we started including `blazor.*.js` in source control. This was intended as a way of avoiding the Node dependency in some CI cases. However, it turns out that:

 * This is very damaging to productivity, as it forces us to shepherd our PRs through CI in series, not in parallel. Every commit that affects the `blazor.*.js` artifacts causes a merge conflict for every other such commit, even if they were only touching completely unrelated files. Some work items have been queued up for days due to this.
 * It's super annoying that sometimes you wait ages for a CI build result, and it fails claiming your output was out of date, even though in some cases that doesn't appear to be true. We haven't tracked down the exact conditions under which this occurs, though it might be something like when SignalR makes changes that overlap with the PR's lifetime.
 * It turns out to be completely unnecessary anyway. We've consulted with the build team (Doug/John, plus Chris regarding source build) and everyone agrees it's actually completely fine to use Node during CI builds, and it's already installed in all our environments except CentOS (where it can be installed via yum).

The build team has agreed to support us with figuring out how to make this change, though @dougbu is asking that someone from the Blazor crew actually do it.

**Comment by BrennanConroy** [comment]
>completely fine to use Node during CI builds

SignalR has been doing this since the beginning. If you need any help or guidance you can ask us or take a look at our npm builds. https://github.com/aspnet/AspNetCore/tree/master/src/SignalR/clients/ts

**Comment by JunTaoLuo** [comment]
This has been completed in https://github.com/aspnet/AspNetCore/pull/12145

**Comment by JunTaoLuo** [comment]
We can't actually do this given source build requirements. Though we have nodejs and yarn, we don't have the dependencies such as typescript available in source build and won't be able to compile our ts source into js artifacts. This is going to be tricky to resolve given our source build commitments.

**Comment by rynowak** [comment]
We need to keep pushing on this something (post 3.0 OK). The current state us functional (we can make progress) but unacceptable for the team's productivity (JS changes can never be merged automatically and require manual intervention).

**Comment by JunTaoLuo** [comment]
@pranavkm I recall we met a while ago and concluded there's something we can do in blazor to stop depending on the *.js files when built in source-build. did you eventually try it out?

**Comment by pranavkm** [comment]
@mkArtakMSFT parking this back on your plate to figure out how to do this. This needs to go thru DOI and I don't have any workable solutions to this.

**Comment by mkArtakMSFT** [comment]
Closing as there is no good solution for this.

**Comment by mkArtakMSFT** [comment]
Related https://github.com/dotnet/aspnetcore/issues/43715

**Comment by mkArtakMSFT** [comment]
Blocked on https://github.com/dotnet/aspnetcore/issues/37398

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/aspnetcore/pull/53154
