### ISSUE TITLE
UseReactDevelopmentServer with UseSpa keeps console open.

### ISSUE THREAD

**Issue by smartcodinghub** [dotnet/aspnetcore#11597]
### Describe the bug
When I use "UseReactDevelopmentServer", the title of the console changes to "npm" and when I stop debugging with Visual Studio, this console keeps open. This can be pretty annoying when debugging fast.

### To Reproduce
**Version:** 2.2.300, 3.0.0-preview6
1. Create a React app using the template (or use UseReactDevelopmentServer).
2. Start Visual Studio debugging or use dotnet run.
3. Stop debugging.

### Expected behavior
When I stop, the console should be closed.

### Additional context
Looking at the code, I don't see any code to close npm. It could use IApplicationLifetime to close the process on Shutdown, for example.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @smartcodinghub.
Will you be interested in submitting us a PR? We'll happily consider it.

**Comment by smartcodinghub** [comment]
I can do it this weekend, if you can point me how to do it. (dotnet version, docs to update, etc...)

**Comment by mkArtakMSFT** [comment]
Thanks @smartcodinghub. You can start by reading through our contribution guidelines at: https://github.com/aspnet/AspNetCore/blob/master/CONTRIBUTING.md

**Comment by mkArtakMSFT** [comment]
Thanks @AndriySvyryd!
