### ISSUE TITLE
@attributes should declare a better type than object

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#11629]
![image](https://user-images.githubusercontent.com/1430011/60222338-ce17da80-9831-11e9-84c3-f04083ac8b83.png)

We should have this say `IEnumerable<KeyValuePair<string, object>>` instead.

**Comment by NTaylorMullen** [comment]
Hmm, can't it also take a List<string> today? Asking because of : https://github.com/aspnet/AspNetCore/issues/10952

**Comment by rynowak** [comment]
The type that matters is the one I mentioned, List is an `IEnumerable<>` 🤣

**Comment by NTaylorMullen** [comment]
GitHub failed to show my generic, updated the above comment, I was referring to `List<string>`

**Comment by rynowak** [comment]
`List<string>` will super not work.

**Comment by NTaylorMullen** [comment]
I see I see.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
