### ISSUE TITLE
[Discussion] SignalR JavaScript client changing package name to @microsoft/signalr

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#11637]
In `3.0.0-preview7`, the SignalR JavaScript client will change from being `@aspnet/signalr` to `@microsoft/signalr`. We are doing this to reflect the fact that SignalR is useful in more than just ASP.NET Core applications, thanks to the Azure SignalR Service.

To react to this change, you will need to change your references in `package.json` files, `require` statements, and ECMAScript `import` statements. No API will change as part of this rename.

This is the discussion issue for https://github.com/aspnet/Announcements/issues/372.

**Comment by GeraudFabien** [comment]
Hello, I'm curious about what make you choose between:
1. [Microsoft](https://github.com/Microsoft)
2. [dotnet](https://github.com/dotnet)
3. [SignalR](https://github.com/SignalR)
4. A new one

I don't have any preference or idea on the subject i'm just curious.

**Comment by Mertsch** [comment]
The organization
https://github.com/SignalR
could probably also use a new description to reflect the change

> SignalR
> SignalR for ASP.NET

**Comment by anurse** [comment]
> The organization
> [@SignalR](https://github.com/SignalR)
> could probably also use a new description to reflect the change

Right now, the `SignalR` GitHub organization hosts ASP.NET SignalR (the version that predates this one). We are doing some work to consider how to restructure things like this though.

> Hello, I'm curious about what make you choose between ...

We considered most of these:

1. `@dotnet/signalr` continues to indicate SignalR can only be used with .NET, which has the same problem as `@aspnet/signalr`. With the Azure SignalR Service REST APIs and Azure Functions bindings, it's now possible to write a SignalR app without a single line of C# (though C# is still a fantastic language to do so in!).

1. `@signalr/client` gives us a place to hang other things, and creates a new identity, but in general we've been leaning away from doing that and want to consolidate a bit around a few Microsoft identities (see https://github.com/Microsoft for example)

1. `@azure/signalr` would align it with a bunch of other Azure clients. However, this has the opposite problem of `@aspnet/signalr`. While we don't want people to think SignalR can only be used with .NET, we **also** don't want people to think it can only be used with Azure! It can be used in either environment and works great in each.

1. `@microsoft/signalr` makes it clear it's the official SignalR client, produced by Microsoft. Other SignalR components can still be named things like `@microsoft/signalr-...` (like the MessagePack protocol library). It doesn't create brand new NPM orgs (there is already an `@microsoft`

In the end `@microsoft/signalr` was the clearest choice. Since it is somewhat disruptive to rename package names, we don't really expect to do it again, getting to something that is truly general (`@microsoft`) means we'll be happiest to live with it for a long time and avoid disrupting the ecosystem any more.

**Comment by anurse** [comment]
**TL;DR**: If you develop a JavaScript **library component** that depends on `@aspnet/signalr`, we'd like to hear from you!

One **open question** that we'd like some support from the community on is how to manage the name transition. Here, we'd love feedback from app developers **and** anyone developing other NPM components that depend upon `@aspnet/signalr`. 

My biggest concern is if a library component references `@aspnet/signalr` at version `>=1.0.0`. They are saying they work with versions 1.0 and higher, but the problem is that version 3.0 is not part of that set (because it's a different package name).

We have a few options

1. Just stop shipping `@aspnet/signalr`.
	* Pros: It's easy
	* Cons: People using `@aspnet/signalr` don't know that we changed
1. Ship one last version of `@aspnet/signalr` (probably version `3.0`) and immediately deprecate it on NPM.
	* Pros: Still pretty easy, clearly tells users they need to update (via the deprecation message)
	* Cons: Libraries taking a dependency on `@aspnet/signalr` either have to update, or can't get the new stuff
1. Ship `@aspnet/signalr` as a "shim package". This would be a package that has a direct dependency on the matching version of `@microsoft/signalr` and *re-exports* all the types. So it's content would be something like the snippets below
	* Pros: Nobody is broken
	* Cons:
		* We have to maintain this package for some undefined period of time. 
		* If an app is already using the new version (`@microsoft/signalr`) and references a library using `@aspnet/signalr` version `1.x` (**BEFORE** the shimming), then they may end up with two copies of the library. The `1.x` version of `@aspnet/signalr` and the `3.x` version of `@microsoft/signalr`. Thanks to JavaScript this will probably still work, types can be exchanged just fine.

I think if we did option 3, we'd **also** mark each release of these shims as deprecated so that NPM users get the warning. That means that if an app did use `@microsoft/signalr` and a library it depends on used `@aspnet/signalr` you **would** get a warning indicating you were in a slightly odd state. If you manually installed the shim package `@aspnet/signalr` it would **fix** the odd state since now the library would be using the shim and there'd only be one copy of `@microsoft/signalr`

**@aspnet/signalr package.json**

```json
{
	"name": "@aspnet/signalr",
	"main": "index.js",
	"dependencies": {
		"@microsoft/signalr": "[exact same version]"
	}
}
```

**@aspnet/signalr index.ts**

```typescript
export * from "@microsoft/signalr"
```

**Comment by benaadams** [comment]
@anurse need to update the docs https://docs.microsoft.com/en-gb/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio-code

![image](https://user-images.githubusercontent.com/1142958/65770090-332ee500-e12d-11e9-8e46-53d23793d243.png)

**Comment by MarkSFrancis** [comment]
The docs also need updating here:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.0&tabs=visual-studio#enable-client-and-server-communication

**Comment by BrennanConroy** [comment]
Tracked at https://github.com/aspnet/AspNetCore.Docs/issues/14794 feel free to fix it if you'd like!
