### ISSUE TITLE
Write documentation for areas, we have little coverage on

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#11665]
We have some debt in the Docs area, and all this work is tracked here: https://github.com/aspnet/AspNetCore.Docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3APU+label%3A%223.0%22

This issue will be used as a reminder for us to triage the docs issues and reserve time to handle those we think are important.

**Comment by mkArtakMSFT** [comment]
@anurse it seems there are a lot of unassigned issues on the referenced list, which are on topics your team owns. Do you want to take over this one?

**Comment by anurse** [comment]
Yep, we'll take it!

**Comment by anurse** [comment]
I'm going to close this. We'll be bringing docs triaging into our normal triage and this issue is mostly noise now :).
