### ISSUE TITLE
Blazor - Please consider exposing the IFileProvider for the static content.

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#11682]
### Is your feature request related to a problem? Please describe.

The following extension method provided by Blazor constructs a new `IFileProvider` that is capable of returning static files for a blazor client app.

```
  app.UseClientSideBlazorFiles<Client.Startup>();
```

However, it doesn't expose this IFileProvider anywhere, instead it just adds a static files middleware to the pipeline that sits on top of it - something I can't figure out how to get at.

In my case, getting this `IFileProvider` is useful, because I have a browser reload mechanism, that can watch paths from a FileProvider, then use signal r to trigger a browser reload. So in this situation being able to access the `IFileProvider` that is created to resolve the client apps static files is very useful to my workflow. I can already do this with other content in my app, by using `IHostEnvironment.ContentFileProvider` and `.WebRootFileProvider` for example which are exposed.

I have resorted to peeking inside that extension method, and writing my own logic to create a return the IFileProvider based on all the things that it does - ike checking for a `.blazor.config` and various path manipulations to work out what the root directory should be.. But as this logic is changing as blazor progresses, I will have to keep revisiting this in new releases and amending my code - which is a pain point.

### Describe the solution you'd like
Provide a mechanism for those wishing to just obtain the `IFileProvider` without adding static files middleware so they can configure static files middleware options themselves if they wish, or not at all.

For example - i'd actually prefer to not add a seperate static files middleware and just integrate the blazor client IFileProvider files with my host environment `IHostEnvironment.WebRootFileProvider` in ConfigureServices:

```
// Extend `IHostEnvironment.WebRootFileProvider with the one able to resolve blazor client files.
 var clientProvider = BlazorClientAppFileProviderHelper.GetFileProvider<Client.Startup>();
            Environment.WebRootFileProvider = new CompositeFileProvider(Environment.WebRootFileProvider, clientProvider);

```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by dazinator** [comment]
Since the change to StaticWebAssets things have moved on slightly, but there is still no easily provided method to get a file provider given a StaticAssetBase path other than copying a bunch of internal files and classes and rolling it yourself - i.e in Development mode look for a project directory vs non development looking relative to WebRoot dir for the published folder and setting up a physical file provider (StaticAssets file provider) over the right location.

This is not an issue right now as all static assets have IFileProviders built and added the HostingEnvironment.WebRootFileProvider composite so should be able to find them through interacting with that - but with https://github.com/dotnet/aspnetcore/issues/20605 has potential to change that, will open something new if necessary.
