### ISSUE TITLE
[Helix] Enable additional arm queues

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#11718]
Tracking reenabling the other two arm queues which don't currently work (permissions related)

```
 <HelixAvailableTargetQueue Include="(Alpine.38.Arm64)Ubuntu.1604.Arm64.Docker@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-arm64v8-46e69dd-20190327215724" Platform="Linux" />
    <HelixAvailableTargetQueue Include="(Ubuntu-1804.Arm64.Open)Ubuntu.1604.Arm64.Docker.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-6f28fa9-20190606004102" Platform="Linux" />
```

Note see coreclr platform matrix for the arm queues they use here: https://github.com/dotnet/coreclr/blob/master/eng/platform-matrix.yml

**Comment by HaoK** [comment]
Likely need to tweak something in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/18.04/arm64v8/Dockerfile

**Comment by HaoK** [comment]
@MattGal so I did a quick diff between https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/18.04/arm64v8/Dockerfile and the debian arm queue that works for us currently https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/debian/9/arm64v8/Dockerfile

The delta is:

```
debian
            curl \
            gettext \
            libgdiplus \
            uuid-dev \

ubuntu 18.04 arm
        libstdc++6 \
```

Should I just submit a PR that adds the missing packages to ubuntu 18.04 to make it a superset of debian 9?

Alpine looks very different https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/alpine/3.9/arm64v8/Dockerfile

**Comment by MattGal** [comment]
Sure, adding new dependencies is usually fine (and if they do somehow break others, they're not immediately broken since it only matters when the tag is updated).  CC myself and Matt Thalman on the PRs please.

**Comment by dougbu** [comment]
@HaoK what is the status of this issue❔ I don't see any Linux Docker testing except for Debian.9.Arm64.Open. Don't want to add a lot of load but putting these in our twice-daily helix-matrix and quarantined-matrix might be :ok:

**Comment by HaoK** [comment]
Do we really want/need additional arm queue testing?  I can try enabling them again if we really want to

**Comment by HaoK** [comment]
Given that we haven't found any product issues, its likely just going to create a lot more infrastructure grief for no actual value I'd assume

**Comment by dougbu** [comment]
:ok:
