### ISSUE TITLE
Build fails if Java Runtime (not SDK) is installed

### ISSUE THREAD

**Issue by NickCraver** [dotnet/aspnetcore#11731]
### Describe the bug
Building with the Java Runtime installed (but not the SDK) fails with an error of:
> The environment variable JAVA_HOME was set, but C:\Program Files\Java\jre1.8.0_201\bin\javac.exe does not exist. Remove JAVA_HOME or update it to the correct location for the JDK. See https://www.bing.com/search?q=java_home for details.

### To Reproduce
1. Install Java Runtime only
2. Get latest AspNetCore repo
3. Run `.\build.cmd`

### Expected behavior
The build completes, without being able to run the pieces that need the Java SDK.

### Additional context
The problem lies [in `build.ps1`](https://github.com/aspnet/AspNetCore/blob/9f18444518ff3c851f9e49d40e819b0cfe195acd/build.ps1#L243), at:
```powershell
elseif ($env:JAVA_HOME) {
    if (-not (Test-Path "${env:JAVA_HOME}\bin\javac.exe")) {
        Write-Error "The environment variable JAVA_HOME was set, but ${env:JAVA_HOME}\bin\javac.exe does not exist. Remove JAVA_HOME or update it to the correct location for the JDK. See https://www.bing.com/search?q=java_home for details."
    }
    else {
        Write-Host -f Magenta "Detected JDK in ${env:JAVA_HOME} (via JAVA_HOME)"
        $foundJdk = $true
    }
}
```
It simply doesn't handle the case of having a proper Java Runtime installed which doesn't include compiler bits like `javac.exe`.

cc @anurse

**Comment by anurse** [comment]
cc @aspnet/build 

If we already have logic that correctly skips the Java stuff when there is no `JAVA_HOME` it feels like the build script should just treat the "`JAVA_HOME` is set but `$JAVA_HOME\bin\javac` doesn't exist" case the same as when `JAVA_HOME` isn't set.

**Comment by dougbu** [comment]
The advantage of the suggested change isn't clear. We need the Java compiler when `-noJava` isn't specified with `-all`. Closing because `-noJava` is available and the error is relatively clear.
