### ISSUE TITLE
Data Protection - Azure Key Vault - Bug 

### ISSUE THREAD

**Issue by rezres** [dotnet/aspnetcore#11742]
### Describe the bug
The bug happens when I use azure blob to persist keys and key vault to protect the keys, 
Note I tried to use the same config for key vault but instead of using blob storage I use file directory and it was fine, 
I also used the same config for my azure blob but without key vault protection and it worked,
when I use both of them, it doesn't work for some reason, upon generating token I get the error 
Invalid ObjectIdentifier: https://myvaultname.vault.azure.net. Bad number of segments: 1
 
 
I follow [this](https://github.com/aspnet/AspNetCore/tree/master/src/DataProtection/samples) and [this](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2)
### To Reproduce
1. Using this version of ASP.NET Core '2.2'
2. Code 
```
            var identifier = config.GetSection("VaultConfigurations")["KeyVaultName"];
            var applicationId = config.GetSection("VaultConfigurations")["ApplicationID"];
  var store = new X509Store(StoreName.My,
                                      StoreLocation.CurrentUser);
            store.Open(OpenFlags.ReadOnly);
            var certs = store.Certificates
                             .Find(X509FindType.FindByThumbprint,
                                   config.GetSection("VaultConfigurations")["CertThumbprint"], false);
            store.Close();
services.AddDataProtection()
                                  .SetApplicationName("myappname")
                                  .UseCryptographicAlgorithms(new AuthenticatedEncryptorConfiguration {
                                      EncryptionAlgorithm = EncryptionAlgorithm.?,
                                      ValidationAlgorithm = ValidationAlgorithm.?
                                  }).SetDefaultKeyLifetime(TimeSpan.FromDays(?))
.PersistKeysToAzureBlobStorage(_cloudStorageAccount,"my relative path")
.ProtectKeysWithAzureKeyVault(identifier, applicationId, certs.OfType<X509Certificate2>().Single());


```

## Additional context
The bug happens when I call **GeneratePasswordResetTokenAsync** from identity user manager.

I run the same code without **ProtectKeysWithAzureKeyVault** and the files was created and that's how I noticed that if the file exists in the blob storage already, it would work, if it doesn't exist, it wouldn't work.
Please note I am using azure key vault as well for my configuration and it is working fine, that's why  i am sure my key vault config is correct and the authorization is successful.

**Comment by blowdart** [comment]
@anurse Who is looking after data protection in Nate's absence?

**Comment by anurse** [comment]
I suppose me? (cc @Pilchie)

**Comment by mhamri** [comment]
any solution for this? I'm facing the same

**Comment by HaoK** [comment]
@blowdart should we close since Azure is owning these going forward? https://github.com/aspnet/Announcements/issues/409

**Comment by blowdart** [comment]
Yup :)
