### ISSUE TITLE
Creating a new component using `dotnet new razorcomponent` uses the directory name as the default file name

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#11824]
Creating a new component using `dotnet new razorcomponent` uses the directory name as the default file name.

Repro steps:
- `mkdir foo`
- `cd foo`
- `dotnet new razorcomponent`

Expected result:
- *Component1.razor* generated

Actual result:
- *foo.razor* generated

**Comment by pranavkm** [comment]
Needs a change from the templating engine: https://github.com/dotnet/templating/issues/2303 to make any follow up changes. See the discussion here: https://github.com/dotnet/aspnetcore/pull/19430

**Comment by mkArtakMSFT** [comment]
@danroth27 do you think we should update the command (which will be a breaking change) to require a component name to be specified, or should we just add some suffix to the generated component name?

**Comment by danroth27** [comment]
> @danroth27 do you think we should update the command (which will be a breaking change) to require a component name to be specified, or should we just add some suffix to the generated component name?

I think we can just close this. Typically you'll want to specify the name explicitly anyway.
