### ISSUE TITLE
Stabilize Kestrel's AddressRegistrationTests

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#11822]
These tests are inherently flaky because they try to bind to a specific port and we know that behavior to be flaky in test environments (because of all the different components running, including sample apps, etc.). Let's stabilize these tests. A few alternatives:

1. Containerize the tests. This gives us automated Windows and Linux testing (which are the production environments), but not macOS coverage since there is no native container system for that

2. Convert the tests to CTI scenarios for manual testing. This gives us full coverage but is more costly. Could be combined with the above to provide a "smoke test" for macOS though.

**Comment by jkotalik** [comment]
I believe these are duped with the test specific failures.
