### ISSUE TITLE
HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

### ISSUE THREAD

**Issue by jo-asakura** [dotnet/aspnetcore#11885]
### Describe the bug

When I publish my website to the remote IIS server (using a publishing profile setup) I'm getting the following error: `HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure`. When I try to use CLI to see what the error might be using `dotnet .\<app>.dll` I'm getting nothing at all, it's just no console output what so ever.

When I do same thing locally, running the app using CLI `dotnet .\bin\Release\netcoreapp2.2\<app>.dll` it runs just fine. It also runs perfectly fine when I launch it from Visual Studio.

It's been about 4 days since I saw that issue for the first time and since then I've tried everything I could find online:

- `OutOfProcess` and `InProcess` (in latter case I get `HTTP Error 500.30 - ANCM In-Process Start Failure` error instead)
- Deleting and reinstalling all possible files/folders/projects/sdks/frameworks.
- Converted the entire app to run under core 2.1 and got same error. I then converted it back, no luck again.
- I even went that far that I've created a brand new app, copied over `*.cs` files and configured brand new setup, no luck.

#### web.config

```json
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="52428800" />
      </requestFiltering>
    </security>
  </system.webServer>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet"
                  arguments=".\Cccn.NetworkImport.Manager.dll"
                  stdoutLogEnabled="true"
                  stdoutLogFile=".\logs\"
                  requestTimeout="01:00:00"
                  hostingModel="InProcess">
        <environmentVariables>
          <environmentVariable name="COREHOST_TRACE" value="1" />
        </environmentVariables>
      </aspNetCore>
    </system.webServer>
    <system.serviceModel>
      <bindings>
        <basicHttpBinding>
          <binding maxReceivedMessageSize="52428800" />
        </basicHttpBinding>
        <basicHttpsBinding>
          <binding maxReceivedMessageSize="52428800" />
        </basicHttpsBinding>
      </bindings>
    </system.serviceModel>
  </location>
</configuration>
```

#### Program.cs

```cs
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureKestrel((context, options) =>
                {
                    options.Limits.MaxRequestBodySize = null;
                    options.Limits.MaxRequestBufferSize = null;
                })
                .UseSetting(WebHostDefaults.DetailedErrorsKey, "true")
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseIIS()
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConsole();
                });
    }
```

I would really appreciate any help or guidance since at this point I'm not sure what else I can do to troubleshoot the issue.

### Screenshots

- OutOfProcess:
![image](https://user-images.githubusercontent.com/1740109/60637635-70a6ff00-9dd8-11e9-8049-6f41f6d29a62.png)

- InProcess:
![image](https://user-images.githubusercontent.com/1740109/60637653-81f00b80-9dd8-11e9-8b96-c24fec4e6a98.png)

### Additional context

This is the error I see in the EventLog when I run it as `OutOfProcess`:
```
Application  '/LM/W3SVC/1/ROOT' with physical root 'G:\Web\rosters\' failed to
start process  with commandline 'G:\Web\rosters\Cccn.NetworkImport.Manager.exe
.\Cccn.NetworkImport.Manager.dll' with multiple retries. The last try of  listening port
is '21040'. See previous warnings for  details.
```

And the previous warning is:
```
Application  '/LM/W3SVC/1/ROOT' with physical root 'G:\Web\rosters\' failed to
start process  with commandline 'G:\Web\rosters\Cccn.NetworkImport.Manager.exe
.\Cccn.NetworkImport.Manager.dll' at stage 'PostStartCheck', ErrorCode =  '0x8027025a',
assigned port 21040, retryCounter '0'.
```

This is the error I see in the EventLog when I run it as `InProcess`:
```
Application  '/LM/W3SVC/1/ROOT' with physical root 'G:\Web\rosters\' failed to load
clr and  managed application. Managed server didn't initialize after 120000  ms.
```

### Logs

- OutOfProcess: https://gist.github.com/jo-asakura/95b181bac107c162d8ab44651564219b
- InProcess: https://gist.github.com/jo-asakura/317fae72ee290cfa05eb90925cfcf3f6

**Comment by jhawkesworth** [comment]
I have a very similar issue.  I can get the application to run locally, or in on premise virtual machines (S2012R2).  However, it will not run at all on S2012R2 virtual machines in Azure US East 2 region, either at the command line or from IIS.
Its clear the application is getting stuck in an endless loop of some sort as it immediately monopolizes a single core of a 2 core virtual machine.  When run from the command line, Ctrl-C reports that the application will shut down, but is unable to complete that and the only way I have found to stop it is to kill the dotnet.exe process.

I have run procmon on it but can't see any ACCESS DENIED results for dotnet.exe process.  Any suggestions for other exceptional 

I enabled the stdout log in web.config.  The file is opened, but has no information written to it.

Event log shows the same error messages as described above.

I have installed dotnet core 2 hosting bundle after IIS, and also installed latest VC redist from https://aka.ms/vs/16/release/vc_redist.x64.exe 

Any suggestions how to debug this would be gratefully received, as would any suggestions why it only fails to start running on Azure virtual machines.

**Comment by jhawkesworth** [comment]
Also, like the opener of this issue, I am not running from the C:\ drive, could that be significant?

**Comment by jo-asakura** [comment]
More logs to help troubleshoot the issue, this time they're from `ancm.log` using [`handlerSettings` setup](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2#enable-the-aspnet-core-module-debug-log):
```
[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 492.. File Version: 12.2.19109.5. Description: IIS ASP.NET Core Module V2. Commit: 33c2d01092d9a1b7a583fe99a50b15686e2b7de9.
[aspnetcorev2.dll] Resolving hostfxr parameters for application: 'dotnet' arguments: '.\Cccn.NetworkImport.Manager.dll exec .\Cccn.NetworkImport.Manager.dll' path: 'G:\Web\rosters\'
[aspnetcorev2.dll] Known dotnet.exe location: ''
[aspnetcorev2.dll] Process path 'dotnet.exe' is dotnet, treating application as portable
[aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'dotnet.exe'
[aspnetcorev2.dll] Invoking where.exe to find dotnet.exe
[aspnetcorev2.dll] where.exe invocation returned: 'C:\Program Files\dotnet\dotnet.exe
C:\Program Files (x86)\dotnet\dotnet.exe
'
[aspnetcorev2.dll] Current process bitness type detected as isX64=1
[aspnetcorev2.dll] Processing entry 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Binary type 6
[aspnetcorev2.dll] Found dotnet.exe via where.exe invocation at 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\2.2.0\hostfxr.dll'
[aspnetcorev2.dll] Converted argument '.\Cccn.NetworkImport.Manager.dll' to 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2.dll] Converted argument '.\Cccn.NetworkImport.Manager.dll' to 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\2.2.0\hostfxr.dll' arguments:
[aspnetcorev2.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Argument[1] = 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2.dll] Argument[2] = 'exec'
[aspnetcorev2.dll] Argument[3] = 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2.dll] c:\b\w\da744fbcc13abce\src\servers\iis\aspnetcoremodulev2\commonlib\fileoutputmanager.cpp:142 Operation failed with LastError: 32 HR: 0x80070020
[aspnetcorev2.dll] Loading request handler:  'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.0\aspnetcorev2_inprocess.dll'
[aspnetcorev2.dll] Creating handler application
[aspnetcorev2_inprocess.dll] Initializing logs for 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.0\aspnetcorev2_inprocess.dll'. Process Id: 492.. File Version: 12.2.18316.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: ce8cf65589734f82b0536c543aba5bd60d0a5a98.
[aspnetcorev2_inprocess.dll] Waiting for initialization
[aspnetcorev2_inprocess.dll] Starting in-process worker thread
[aspnetcorev2_inprocess.dll] Resolving hostfxr parameters for application: 'dotnet' arguments: '.\Cccn.NetworkImport.Manager.dll exec .\Cccn.NetworkImport.Manager.dll' path: 'G:\Web\rosters\'
[aspnetcorev2_inprocess.dll] Known dotnet.exe location: 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Process path 'dotnet.exe' is dotnet, treating application as portable
[aspnetcorev2_inprocess.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\2.2.0\hostfxr.dll'
[aspnetcorev2_inprocess.dll] Converted argument '.\Cccn.NetworkImport.Manager.dll' to 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2_inprocess.dll] Converted argument '.\Cccn.NetworkImport.Manager.dll' to 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2_inprocess.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\2.2.0\hostfxr.dll' arguments:
[aspnetcorev2_inprocess.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Argument[1] = 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2_inprocess.dll] Argument[2] = 'exec'
[aspnetcorev2_inprocess.dll] Argument[3] = 'G:\Web\rosters\.\Cccn.NetworkImport.Manager.dll'
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 0
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] Event Log: 'Application '/LM/W3SVC/1/ROOT' with physical root 'G:\Web\rosters\' failed to load clr and managed application. Managed server didn't initialize after 120000 ms.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Exception 'InvalidOperationException' caught at c:\b\w\e37dd45d8cd1eaf4\src\iisintegration\src\aspnetcoremodulev2\inprocessrequesthandler\inprocessapplication.cpp:350 
[aspnetcorev2_inprocess.dll] Failed HRESULT returned: 0x8007023e at c:\b\w\e37dd45d8cd1eaf4\src\iisintegration\src\aspnetcoremodulev2\inprocessrequesthandler\dllmain.cpp:120 
[aspnetcorev2_inprocess.dll] Starting app_offline monitoring in application 'G:\Web\rosters\'
[aspnetcorev2_inprocess.dll] Starting file watcher thread
```

**Comment by anurse** [comment]
The error you're getting definition seems to be related to the fact that `dotnet <app>.dll` is failing on your server machine. Is this true of any .NET Core application? If you take a simple console app and publish it does it fail similarly when you run it on the command line? And the same app runs fine on your local machine?

> [aspnetcorev2_inprocess.dll] Event Log: 'Application '/LM/W3SVC/1/ROOT' with physical root 'G:\Web\rosters\' failed to load clr and managed application. Managed server didn't initialize after 120000 ms.' 

This is the key error. It means that ANCM started the `dotnet` process but didn't get any response after 2 minutes.

Would you be able to provide a complete runnable sample application that reproduces the problem? From the code you posted so far I don't see any reason why the app shouldn't be starting up.

Could you also provide the output from `dotnet --info` **on your remote server**?

**Comment by jo-asakura** [comment]
@anurse Yep, any other app runs just fine using `dotnet <app>.dll` or IIS setup on the same machine. It's definitely something up with that specific app and I couldn't figure it out. 

That's good to know that `dotnet` process gets kicked off but doesn't get any response in 2 minutes and fails after that. My next step is to disable various parts of `Startup.cs` to make sure that nothing silently fails or hangs on the app startup thereby causing the issue. I'll report back on that once I get the results.

**Comment by jo-asakura** [comment]
@anurse This is the output from `dotnet --info`:
```
Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by anurse** [comment]
> My next step is to disable various parts of `Startup.cs` to make sure that nothing silently fails or hangs on the app startup thereby causing the issue. I'll report back on that once I get the results.

This sounds like the right track. If something in Startup is hanging, it could cause this behavior.

**Comment by jo-asakura** [comment]
@anurse Finally, found it 🎉 

There is a script that we run on the app startup to run database migration:
```cs
        private static void UpdateDatabase(IApplicationBuilder app)
        {
            using (IServiceScope serviceScope = app.ApplicationServices
                .GetRequiredService<IServiceScopeFactory>()
                .CreateScope())
            {
                using (var context = serviceScope.ServiceProvider.GetService<CrContext>())
                {
                    context.Database.Migrate();
                }
            }
        }
```

Once I removed that part the app magically started to work. The actual issue was in missing database credentials that our engineers forgot to transfer when they migrated the app's database to a new location. That's weird that the invalid database credentials problem wasn't reported at any of the loggers; seems like it should've been caught fairly easy.

**Comment by anurse** [comment]
> That's weird that the invalid database credentials problem wasn't reported at any of the loggers; seems like it should've been caught fairly easy.

That is strange indeed. Is an exception thrown by `Migrate`? If you'd be able to isolate this to a runnable sample we might be able to track down why it isn't logged.

This also presumes you have logging configured at this point. You could always grabbing a logger with `serviceScope.ServiceProvider.GetRequiredService<ILogger<Startup>>()` and logging a test message there.

**Comment by jhawkesworth** [comment]
In our case, it transpired a dll needed to update as it was hanging while attempting to connect to a downstream system.   I guess we needed to have had logging configured earlier in the startup process too.

**Comment by Bernoulli-IT** [comment]
In a situation I have at hand a migration procedure is also taking (expectedly) long but needs to be executed. Is it possible to just increase the timeout of 120s (2 min)?

**Comment by Bernoulli-IT** [comment]
The answer is found here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#attributes-of-the-aspnetcore-element

```
<location path="." inheritInChildApplications="false">
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\???.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" **startupTimeLimit="600"**>
    </aspNetCore>
  </system.webServer>
</location>

```
