### ISSUE TITLE
F# MVC Does not even support authentication out of the box.

### ISSUE THREAD

**Issue by duaneking** [dotnet/aspnetcore#11905]
### Describe the bug
The F# Language is not treated as a first class citizen at all.  Testing, I can't even add authentication to a new projects created by the command line, and on Mac, I don't even get a UI.  If you try to look up why, you end up at a templating bug post in an archived github account that seems to suggest this issue just slipped through the cracks.

This is not just a feature request in my mind; this is me ringing the bell that this work looks half finished and makes devs like me that get to use F# as part of our day jobs feel like we do not matter to the ASP/Net/Core team, because we cant start new projects that can actually be USEFUL without doing a lot of extra work that shouldn't need to be done, that most people wont even try to do.  This makes me and others I know less invested in the language, and greatly harms the F# community as a whole since we devs effectively are left to feel like the language doesn't have a future based on how its being treated.

### To Reproduce
1. Using any version of ASP.NET Core '...'
2. dotnet new mvc -n love -o love -lang "F#" -au Individual

This fails with an invalid switch error; I know it's because the template doesn't support it but thats what this bug is about.  Honestly, not a single supported language in dotnet core should lack support for auth, period, as part of the security efforts MS has highly publicly marketed, it just doesn't make any sense not to support this from my perspective.  If VB can get great support, why cant F#? 

### Expected behavior
I expect to see a project created that works and not to get random errors about the -au switch being unsupported.  This is a greater issue than just it not being supported; What use is a web api that can't be secured by a login? Why would you force a developer to do that work themselves when every other language gets this support out of the box when I can just use C# instead and it will "just work"?

### Additional context
This is true as of the most recent stable version as of today, as I just reinstalled a devbox and added dotnet to it and still get this issue.

### Is your feature request related to a problem? Please describe.
I want to create my own MVC apps in F# and would like to have projects at home I can use to explore the language so I can be more effective and comfortable with it.  But I can't do that unless the projects I can create on the command line - since not all my devboxes are windows, Mac doesn't have a project options UI, and I use the command line no matte what platform I am on anyway - have what I need to get started; What I want in the best case is a project that is pure F# that includes the standard login stuff so I can just get to work on my idea and not have to worry about plumbing.

### Describe the solution you'd like
Effectively this command should not fail to create a new project:

dotnet new mvc -n login -o login -lang "F#" -au Individual 

Supporting EF-core in F# without having to use a wrapper would be nice, too.

### Additional context
I'm happy to talk about this.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by duaneking** [comment]
With respect, this is such a HUGE issue that the fact that this is broken means the language itself is broken.

When I spoke with Patrice about this at MSR whern I was last there years ago. he was very passionate about the F# language and his desire to see it be successful; It was amazing to work with him and that team.  I'm saddened to see that this blocking issue is being limited by MS simply because the F# language needs support as a first class citizen; that lack of support is creating the bad impression that you have that this is not a real issue, simply because 99.99999% of people notice this issue and give up on f#.
