### ISSUE TITLE
Blazor OnAfterRender Recursive Warning

### ISSUE THREAD

**Issue by jbomhold3** [dotnet/aspnetcore#11910]
It would be nice to have a warning in the tooling about recursion when using StateHasChanged() in OnAfterRender event.  Should warn only if with the top level of the method not if used in a conditional statement. Not a pressing issue but it would be a nice, oops I didn't mean to have that their anyways notice. Even better for newer users that have no idea that would happen.

**Comment by rynowak** [comment]
Want to send a PR for this?

**Comment by jbomhold3** [comment]
I have never looked at the tool repo to even know where to start to do a PR for it

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
