### ISSUE TITLE
Asp.net Core Identity Reset Token Not Url Safe? Leads to 404 Error

### ISSUE THREAD

**Issue by chobo2** [dotnet/aspnetcore#11943]
Hi

I am trying to use asp.net core identity and am running asp.net core 2.2

I am using the default implementation of asp.net identity core and use this line of code

` var token = await userManager.GeneratePasswordResetTokenAsync(employee);`

I then url encode it like this

`   token = HttpUtility.UrlEncode(token)
`

then send it via email and would look like this

`https://www.example.com/forgotPassword/CfDJ8BocAWQJpDVCswirwjHYLWRCG6zZTSxopJgdO3DDm4aO3g3PDFOjmENf6aTbq4qNUF6lMQuOot%2f1e1xZYdkM%2fV9%2bvatM6UBYNBJsZRBuiNnvnX2dPnMv8ANqg56Q2jaCXfVvW4Q%2fwGDDud28NJsFPQIBcb%2bsTnnu%2f22qwfEODpXk4e1BB8VdJWXwzEy8r1F9dq4iptdVEAf5thdUn4lMMpxsKW5r63QLCnn19GPhUcQA`

however when this link it clicked and redirected to my website I get a 404 error as iis seem to think this is a file on the system.

If I shorten the url down to something like this

`CfDJ8BocAWQJpDVCswirwjHYLWRCG6zZTSxopJgdO3DDm4aO3g3PDFOjmENf6aTbq4qNUF6lMQuOot
`
which excludes the` %2` it works fine.

This seems like a bug to me as this token should be able to work in a url.

**Comment by blowdart** [comment]
@HaoK did the fix for this go in?

**Comment by HaoK** [comment]
Not yet Eilon didn't like the quick and dirty regen when the token contains a '+' we will need to do something slightly less hacky (probably a shared helper in the UI code that does the html/token cleanup for all the code methods

**Comment by chobo2** [comment]
@HaoK  @blowdart 

Do you guys have an eta of when this will be fixed? When it is fixed which package would I need to update?

**Comment by HaoK** [comment]
It should be fixed in 3.0, and the fix would be in the Identity.UI package

**Comment by chobo2** [comment]
@HaoK 

Ok so I will have update to core 3.0? Can you give an eta like will this be a month sort of thing or a week?

**Comment by HaoK** [comment]
The fix for the other issue is just with our default templates/UI, you could adopt somthing similar in your code, but its not necessarily going to help your issue if you are generating tokens and sending emails yourself.

If you include the full code of generating the token + sending the email we can provide suggestions for you

**Comment by chobo2** [comment]
@HaoK 

My code is pretty simple, it pretty much is generate the token via built in command then send it via email.

```
        public async Task ForgotPasswordAsync(string email)
        {
            var employee = await userManager.FindByEmailAsync(email);
            if (employee != null)
            {
                var token = await userManager.GeneratePasswordResetTokenAsync(employee);
                if (token != null)
                {
                    var sent = await SendForgottenPassword(email, token);
                }

            }
        }

        public async Task<bool> SendForgottenPassword(string email, string token)
        {
            var msg = new SendGridMessage();
            msg.SetFrom(from);
            msg.AddTo(email);

            var dynamicTemplateData = new
            {
                token = HttpUtility.UrlEncode(token)
            };

            msg.SetTemplateData(dynamicTemplateData);


            var response = await sendGridClient.SendEmailAsync(msg);
        }
```

**Comment by HaoK** [comment]
So the change we made to the templates was just to url encode the token before html encoding the full link, and then url decoding the token before checking it against identity.  You should be able to do the same thing in your code.  Hope that helps

**Comment by chobo2** [comment]
@HaoK 

So I have to do?

```
token = HttpUtility.UrlEncode(token)
token = WebUtility.HtmlEncode(token);

```

**Comment by HaoK** [comment]
Yup, and then make sure you url decode the token on the way back

**Comment by chobo2** [comment]
@HaoK 

Hmm I am still having problems

Raw Token

`CfDJ8IWFAz1gD91Pqn/zn4L4Op6X/4lessN26aG//jLLzOKnKFesBaKl+I5M+zXETVZexrHc8cl0zCSJhISZu5JKGT/i3AThLGwrICSzdqOkzDYFnx+2zR4tr2fUdT9Kc2QQ0kGKZaWA9Tf3bMJID6IaMnjXdbG2UKi+GYH7/YqVqW+HVCXopXHNXtxWIiqiY+/ltZ+ecDA5DlvY4+SwzeWu2UeOkHH5q8ZbShshLvAD53jU`

now I added this line of code

     token = HttpUtility.HtmlEncode(HttpUtility.UrlEncode(token))

which results to 

`CfDJ8IWFAz1gD91Pqn%2fzn4L4Op6X%2f4lessN26aG%2f%2fjLLzOKnKFesBaKl%2bI5M%2bzXETVZexrHc8cl0zCSJhISZu5JKGT%2fi3AThLGwrICSzdqOkzDYFnx%2b2zR4tr2fUdT9Kc2QQ0kGKZaWA9Tf3bMJID6IaMnjXdbG2UKi%2bGYH7%2fYqVqW%2bHVCXopXHNXtxWIiqiY%2b%2fltZ%2becDA5DlvY4%2bSwzeWu2UeOkHH5q8ZbShshLvAD53jU`

It still has `%2f `what still leads me to getting a 404.

as if I would shorten down to before the first `%2f`

`CfDJ8IWFAz1gD91Pqn`

it works.

I am using IIS btw.

**Comment by HaoK** [comment]
Its not the token you need to html encode, you need to html encode the entire link that contains the url encoded token that you are emailing, so they can click on a link that works.

**Comment by chobo2** [comment]
@HaoK 

Well when I send out my email, I pass it to a send grid template which has 

`<a href="http://www.example.com/{{token}}">Reset Password </a>`

what gets converted to

<a href="http://www.example.com/{CfDJ8IWFAz1gD91Pqn%2fzn4L4Op6X%2f4lessN26aG%2f%2fjLLzOKnKFesBaKl%2bI5M%2bzXETVZexrHc8cl0zCSJhISZu5JKGT%2fi3AThLGwrICSzdqOkzDYFnx%2b2zR4tr2fUdT9Kc2QQ0kGKZaWA9Tf3bMJID6IaMnjXdbG2UKi%2bGYH7%2fYqVqW%2bHVCXopXHNXtxWIiqiY%2b%2fltZ%2becDA5DlvY4%2bSwzeWu2UeOkHH5q8ZbShshLvAD53jU">Reset Password </a>

So why do I need to url encode the entire link?

**Comment by HaoK** [comment]
Try sending the token as a query string

**Comment by chobo2** [comment]
@HaoK 

That will probably work, I just would have rather to used it as in a param as it is easy to get at(via react router).

Why do these tokens use unsafe symbols in the first place?

**Comment by HaoK** [comment]
These are tokens and opaque to identity, in this case the tokens are generated using Base64 encoding which is not safe, the app is responsible for round tripping the tokens correctly to identity

**Comment by chobo2** [comment]
@HaoK 

But from what I can tell IIS does not like % stuff in the url, and as shown in my case no amount of encoding will make it accept it.

I would think this would be taken in consideration seeing it is all MS products.

**Comment by u7pro** [comment]
@chobo2 

this is due to segments default size limit to 255 in http.sys => IIS.

when `%2F` ( `/` ) is encoutred in a URL, a new segment is considered and then you can have another 255 chars

you can change the default size in the registry as described here
https://support.microsoft.com/en-us/help/820129/http-sys-registry-settings-for-windows
