### ISSUE TITLE
odd but real DI issue when registering singleton in optionsConfigureAction 

### ISSUE THREAD

**Issue by aammfe** [dotnet/aspnetcore#11959]
DI do not register singleton in optionsConfigureAction in  asp.net core 2.2

`IAuthorizationHandler` will not be registered in code below 
![image](https://user-images.githubusercontent.com/11896817/60815552-580c5f80-a1b1-11e9-8cf8-054b9437bf79.png)

but it will register overhere 
![image](https://user-images.githubusercontent.com/11896817/60815662-8ab65800-a1b1-11e9-9ef4-7ad2fdb37228.png)

Yes its wired place may be no body register dependency overhere  but It can consume hours to debug 
Thanx.

**Comment by Pilchie** [comment]
Hi @aammfe sorry this fell through the cracks.  Is it still an issue for you?

**Comment by aammfe** [comment]
Hello!!
I had resolved it by not calling it in Options Func.
but its still an issue

**Comment by JunTaoLuo** [comment]
I think there's a confusion here with what the options configuration delegate is able to do. 

AddPolicyHandlers is meant to configure the **service collection** and add a singleton service. This would be executed **before** the service provider is built from the service collection. The `Action<AuthorizationOptions>` is meant to configure the instance of the `AuthorizationOptions` that was retrieved as part of resolving the options type from the **service provider**. Thus you must call `AddPolicyHandlers` as part of configuring the service collection and it would not do anything if you called it as part of options configuration.
