### ISSUE TITLE
Method for changing the binding event for Input* components

### ISSUE THREAD

**Issue by aherrick** [dotnet/aspnetcore#11960]
Trying to bind to the key press so when typing two way binding kicks in.

I have my input setup as so:							

`<InputText class="form-control" @bind-value="@VM.Connector.Name" @bind-value:event="oninput" />`

However I only receive feedback of the change update on blur.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @aherrick.
We're going to make sure the compiler errors out in this situation, as this is not supported.

**Comment by SteveSandersonMS** [comment]
@rynowak Not sure if you've got a design in mind for this. Let's discuss if so.

**Comment by mkArtakMSFT** [comment]
Bumping up the priority given community interest in this.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by vertonghenb** [comment]
Is there a possible workaround for this?

**Comment by SteveSandersonMS** [comment]
Yes, as a workaround you can subclass `InputText` and change how it renders in 2 lines of code. Please see: https://stackoverflow.com/a/57326353
