### ISSUE TITLE
[Blazor ASP.NET Core Hosted] Is there or are there plans to support easy access to query string values from routes?

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#11977]
Hello,

It appears there has been some discussions about this before, but I wasn't able to find any concrete answers to the topic.

Essentially, I think it would be really nice if Blazor client side supported routes with query string values. For example:

`@page "/whateverpage?{xyz}"`

Where the url to match this page wold look something like:

`/whateverpage?xyz=abc`

I think this would be pretty handy.

Note that the parameter values should be automatically decoded, so a query string value of `abc%2Bxyz` should bee automatically decoded to `abc+xyz` for example.

This issue became a problem for us when we tried to implement the standard password reset process. Essentially, when the user resets his or her password, an email is sent to them, that email link (as far as I know) comes in similar shape to the one below:

`MyWebsite.com/MyResetPasswordRoute?resetToken=abc%2Bxyz`

when the user clicks on the link, we would want a Blazor client side page to open where the user can enter the new password and then submit the request (the submit request must include the token of course).

As of today, it appears the only way to get the query string is via the `uriHelper.GetAbsoluteUri()` and t hen parse out the query string.... not practical.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rxelizondo.
We do, indeed, plan to make this much easier. However this is not a critical blocking scenario for 3.0 release so we'll handle it post 3.0.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
