### ISSUE TITLE
Asp.Net Core windows service template

### ISSUE THREAD

**Issue by pantonis** [dotnet/aspnetcore#11996]
### Is your feature request related to a problem? Please describe.
I have recently found this link
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md. Every time I want to create a new windows service based on .net core I have to repeat the steps

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.
Can you add an asp.net core windows service template on VS2017?

**Comment by anurse** [comment]
We're adding a worker service template in .NET Core 3.0 which will include smoother Windows Service integration. The bulk of that document is about registering the app as a Windows Service which isn't something we can fix in a template. The other content is simply describing the deployment and configuration options.

What content would you want to see in the template? We do have an issue tracking easier installation (https://github.com/aspnet/Extensions/issues/1080) but that's not something that a template would do, that refers to features we'd provide in the framework.

**Comment by Tratcher** [comment]
@glennc had some proposals for a self-registering service. E.g. run it once in admin mode to register.

**Comment by anurse** [comment]
Yep, that's the issue I linked.

**Comment by pantonis** [comment]
@anurse a template that creates the windows service that you describe on this document. a template of the final result of this example
