### ISSUE TITLE
Consider improving dev-certs experience on WSL

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#12011]
Right now, since WSL is effectively a "separate VM", the dev-certs experience is a bit rough. You run your app in WSL and we generate a dev-cert there, but your Windows machine doesn't trust it.

The optimum solution would be to somehow allow the WSL instance and Windows to share the same certificate. There are ways to jump between WSL and Windows so this may be feasible.

Other alternatives include detecting WSL and printing a warning or something, perhaps linking to a useful doc.

**Comment by Tratcher** [comment]
Is it still using localhost to communicate between the brower and the WSL app?

**Comment by anurse** [comment]
Yes, WSL proxies the localhost ports.

As WSL gets more popular, we're going to need to consider some solution for this. Probably the most seamless and simplest solution is to have the `dev-certs` experience on WSL automatically install the certificate as trusted on Windows (apps in WSL _can_ launch Windows executables, including shells like powershell, so this _could_ be feasible). It's basically our least-supported scenario since we have a two "machines" trying which need to use the same certificate (WSL as the server, Windows as the client browser).

Docker would probably be similar, which makes me wonder if/how that scenario works...

**Comment by mkArtakMSFT** [comment]
Talked to @javiercn and this is mainly about providing docs showing what to do in WSL situation.

**Comment by javiercn** [comment]
This is done now and covered in docs
