### ISSUE TITLE
[Blazor] Occasional Heartbeat took too long messages on new HubConnections 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#12015]
When a large number of HubConnections are opened on a Blazor app, we occasionally see a warning from the server:

> Heartbeat took longer than "00:00:01" at "07/09/2019 01:30:17 +00:00". This could be caused by thread pool starvation.

**Comment by rynowak** [comment]
What's the impact of this? Does it disconnect the client? Does it just log a message?

**Comment by davidfowl** [comment]
How many connections?

**Comment by pranavkm** [comment]
No errors on the client. I need to investigate this further, but I'm having trouble using the diagnostics tools.

@davidfowl I see this when I add more than 5k connections on a sever with 60k connections.

**Comment by BrennanConroy** [comment]
Don't see how this is related to SignalR at all
https://github.com/aspnet/AspNetCore/blob/9851e0168812471e52c4c965a0c0005240f762ba/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs#L51

**Comment by davidfowl** [comment]
It's usually a sign of thread pool starvation/exhaustion. @pranavkm Ir would be good to capture both performance counters and a process dump when this happens.

**Comment by BrennanConroy** [comment]
@pranavkm Can you provide a repro or close if it isn't relevant anymore

**Comment by pranavkm** [comment]
We can reopen once we look at this again. We haven't received user reports of this.
