### ISSUE TITLE
use .useSockets(), got many connection time out at Linux

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#12017]
_From @sharbui on Friday, June 14, 2019 9:54:25 AM_

my Environment is 
CentOS 7 latest
dotnet verion 2.2.105

i  use dotnet new web to create a project and use ab to test performance
when  i use default and dotnet run
![image](https://user-images.githubusercontent.com/16458001/59500557-47c3d600-8ecc-11e9-9460-aaf58a5bed28.png)
the ab result was
![image](https://user-images.githubusercontent.com/16458001/59500822-cb7dc280-8ecc-11e9-912b-a7dfb3fdea3b.png)
got so many failed requests

but if i add libuv package and use .UseLibuv()
![image](https://user-images.githubusercontent.com/16458001/59500931-fa943400-8ecc-11e9-8ebf-f65c7b6f7846.png)
the ab result was 
![image](https://user-images.githubusercontent.com/16458001/59501016-34653a80-8ecd-11e9-9dd5-5389cb4263bc.png)

From the results
I feel that using libuv is relatively stable in the Linux environment.

have anyone know about this or how to tuning kestrel with sockets?

_Copied from original issue: dotnet/core#2873_

**Comment by Pilchie** [comment]
_From @carlossanlop on Tuesday, July 9, 2019 5:22:11 PM_

@Pilchie does this sound like something the ASP.NET team can help with?

**Comment by davidfowl** [comment]
Where are your ab parameters?

**Comment by sharbui** [comment]
ab -c 300 -n 10000 -r or no -r

**Comment by sharbui** [comment]
Finally i also tried to use redhat linux transport, the result is better than libuv and socket.
at high number of concurrent connections, linux transport result is good, 
at low number of concurrent connections,  socket is better than other.

**Comment by davidfowl** [comment]
No keep alive? Those end up being http/10 requests

**Comment by sharbui** [comment]
Because we tested the web service, we did not consider using -k at the time of testing.
When testing the hello page, I did not consider adding -k

It should be said that the entire test scenario, all tests, only one connection, one object at a time, so we did not consider -k

I will test it again. After using -k, does websocket/libuv performance improve?
