### ISSUE TITLE
Add CI configurations for build.cmd in sub-areas

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#12029]
The proposal is to add CI configurations to run the build.cmd/build.sh in sub-areas such as Components, Installers, SignalR, etc to ensure the expected dev workflows, such as restore and build, remain aligned to the contributor guidelines.

**Comment by rynowak** [comment]
@jkotalik

**Comment by JunTaoLuo** [comment]
No, this is just a sub part. I'm still writing the full issue.

**Comment by rynowak** [comment]
> @jkotalik 

> No

**Comment by rynowak** [comment]
How do I cancel pinging someone? 😆

**Comment by dougbu** [comment]
Reassigning because you're already working on something very much like this @mkArtakMSFT

**Comment by dougbu** [comment]
@mkArtakMSFT can this now be closed?

**Comment by mkArtakMSFT** [comment]
Yes.
