### ISSUE TITLE
The problem with using the component-material-web  in blazor hosted core

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#12031]
Hi. I've installed material-component-web through npm, it's on the razor page, but the styles do not apply. Please guide.
Thanks

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/583187/the-problem-with-using-the-component-material-web.html
VSTS ticketId: 899596_
_These are the original issue comments:_

Visual Studio Feedback System on 5/27/2019, 01:50 AM (43 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/28/2019, 00:27 AM (42 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi.

We will need some more information to be able to assist you. Please provide a minimalistic project so we can repro this.
