### ISSUE TITLE
How to check if Model/ModelState is valid in Blazor?

### ISSUE THREAD

**Issue by marcelovidigal** [dotnet/aspnetcore#12044]
Is there anything like TryValidadeModel in Blazor? How can I check in @code if the model passed to EditForm is valid or not?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @marcelovidigal.
You have to create the `EditContext` yourself to do this. We're going to use this issue to improve the docs to include such an example.

**Comment by enetstudio** [comment]
I guess this can help you solve your issue...
```
/// <summary>
        /// A callback that will be invoked when the form is submitted.
        ///
        /// If using this parameter, you are responsible for triggering any validation
        /// manually, e.g., by calling <see cref="EditContext.Validate"/>.
        /// </summary>
        [Parameter] public EventCallback<EditContext> OnSubmit { get; private set; }

```
Source:  https://github.com/aspnet/AspNetCore/blob/993d943aec5c8bd590524d56b0c8cdec27032767/src/Components/Components/src/Forms/EditForm.cs

**Comment by mkArtakMSFT** [comment]
We've improved our Forms and validation docs quite a bit. This should be covered .there already: https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1
As pointed out in the docs you can now call `Validate` on the `EditContext`.

**Comment by glararan** [comment]
@mkArtakMSFT can you provide please guide how to remove field from validation? Like from MVC via `ModelState.Remove(".....")`. I am using same class for database where I require those attributes to be required. I fill them after post. Or is there way to do action before validation? (I guess somehow via EditContext?)

**Comment by mkArtakMSFT** [comment]
Hi @glararan.

**It looks like you are posting on a closed issue!**
We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
