### ISSUE TITLE
[Blazor] Investigate RuntimeDependenciesResolver behavior

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#12059]
Debugging it, it looks like it does not correctly inspect all transitive dependencies. For instance, Blazor.HttpClient was added as a new dependency to StandAloneApp, but it does not show up in the `FindsReferenceAssemblyGraph_ForStandaloneApp` test.

**Comment by pranavkm** [comment]
System.Memory showed up in the unexpected list of a assemblies in my ElementRef \ JsonConverter change: https://dev.azure.com/dnceng/public/_build/results?buildId=269456&view=logs&jobId=1402d8c5-7e47-5bf4-467f-73e45e01bcce

```
Microsoft.AspNetCore.Blazor.Build.Test.RuntimeDependenciesResolverTest+ContentMisMatchException : Unexpected content found: System.Memory.dll
```

I'm going to Skip this test in entirety until we get to the bottom of this issue. 

FYI @SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
@pranavkm is this still relevant?

**Comment by pranavkm** [comment]
Yes. It's the only test we have for a fairly complicated feature.
