### ISSUE TITLE
Add an analyzer for pubternal

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#12066]
We want to create an analyzer that squiggles usage of pubternal code exposed by ASP.NET Core.

EF has an existing analyzer for this that we want to reship for `Microsoft.AspNetCore.Analyzers`.

**Comment by gfoidl** [comment]
https://github.com/aspnet/Extensions/pull/345 also introduced such an analyzer -- but I don't know if this one can be used here.

**Comment by rynowak** [comment]
Yeah, the logic for this will be similar, but it will ship in our main analyzers package. The goal is to warn *everyone* if they are using an unsupported API.

**Comment by rynowak** [comment]
That's probably the best area

**Comment by dougbu** [comment]
This was fixed when we migrated Internal.AspNetCore.Analyzers into this repo, wasn't it @pranavkm❔ That is, can this issue be closed❔

**Comment by JunTaoLuo** [comment]
This issue is probably moot. We did migrate Internal.AspNetCore.Analyzers but we removed it in https://github.com/dotnet/aspnetcore/pull/24693 since we no longer author pubternal APIs at all. FYI @pranav who removed the analyzer.
