### ISSUE TITLE
Make doc comments required on public APIs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#12067]
Now that we've moved away from pubternal APIs we should make it required to have public documentation on these APIs.

**Comment by dougbu** [comment]
@mkArtakMSFT what is lacking here❔ Warnings about missing XML documentation (`CS1591`) will break builds as soon as https://github.com/dotnet/aspnetcore/blob/master/Directory.Build.props#L102-L103 is removed. Suggest assigning to someone on your team to see where we aren't fully documenting the public APIs. Up to you whether this is needed in 5.0.

**Comment by dougbu** [comment]
See resolution of #26397

**Comment by JunTaoLuo** [comment]
Followup in #27538 for what's still missing in terms of API docs.
