### ISSUE TITLE
building the dotnet new react template always creates a production build

### ISSUE THREAD

**Issue by steveoh** [dotnet/aspnetcore#12071]
## Describe the bug

I cannot figure out a way to modify the csproj created by the dotnet new template to allow for other configurations of CRA builds to be created. 

It is [documented](https://facebook.github.io/create-react-app/docs/deployment#customizing-environment-variables-for-arbitrary-build-environments) in the react community to set the environment before a build is created e.g.

`./node_modules/.bin/env-cmd -f ./.env.stage react-scripts build`

aspnet core has the same functionality with `ASPNETCORE_ENVIRONMENT`.

If I run an aspnet core project in a staging environment, I would also like to build the react app for that environment.

What is missing is a link between the two. The csproj allows for `Condition` properties but as far as I can tell, they do not understand the environment. The closest you can get is the Configuration with `Release` and `Debug`.

`'$(Configuration)' == 'Debug'`

It would be great if the environment was available to the csproj so you could add conditions around the environment.

Otherwise, would you need to add some sort of condition on the

`<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />`

command to run different commands?

Something like the following kinda works...

```xml
  <PropertyGroup>
    <BuildEnvironment>$([System.Environment]::GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"))</BuildEnvironment>
  </PropertyGroup>

...

    <Exec Condition=" '$(BuildEnvironment)' == 'Staging' " WorkingDirectory="$(SpaRoot)" Command="npm run build:stage" />

or

 <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:$(BuildEnvironment)" />

```

### To Reproduce

1. dotnet new react
2. add a `.env.stage` file
3. dotnet run
4. try to use the env.stage variables

### Expected behavior

A way to conditionally run `npm run build` commands based on the environment.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @steveoh .
We'd happily consider a PR, if you'd like to send one.

**Comment by steveoh** [comment]
What would you like to see in a PR?

**Comment by mkArtakMSFT** [comment]
Your original suggestion was reasonable:

> A way to conditionally run `npm run build` commands based on the environment

**Comment by steveoh** [comment]
Ok @mkArtakMSFT, where is the template for the dotnet new react project type?

**Comment by mkArtakMSFT** [comment]
Here you go: https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
