### ISSUE TITLE
[AzureADB2C] AddAzureADB2C options

### ISSUE THREAD

**Issue by andreujuanc** [dotnet/aspnetcore#12085]
Hello!

### Is your feature request related to a problem? Please describe.
AddAzureADB2C calls AddOpenIdConnect and AddCookie and in both methods the option actions is hardcoded like so: o => { }.
I cannot have my own implementation of AddAzureADB2C because some of the classes are internal.

### Describe the solution you'd like
It'd be nice if they could be passed as an argument of one of the overloads of AddAzureADB2C.

### Additional context
Source code:
https://github.com/aspnet/AspNetCore/blob/7db16f174d3c142fd41ad22455fc0df0828edddf/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/AzureAdB2CAuthenticationBuilderExtensions.cs#L125-L126

I can PR this if needed.

Hope this is clear enough.

Cheers

**Comment by blowdart** [comment]
@jmprieur

**Comment by Tratcher** [comment]
Here's an example on how to configure the options for the underlying schemes:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.2#configure-the-underlying-openidconnectoptionsjwtbearercookie-options

**Comment by anurse** [comment]
We should consider a better options pattern here since there are multiple options objects to handle.

**Comment by andreujuanc** [comment]
I agree with @anurse . Even thought it's a valid solution (haven't tried it yet), it involves finding that specific documentation page. Which, in my opinion, is a bit brittle. 
A parameter, on the other hand, gives the developer the actual up-to-date documentation on how to pass the options.

Personally I've never been a fan of configuration or conventions, i prefer code.

**Comment by Tratcher** [comment]
Closing since AddAzureADB2C is now obsolete and replaced by Microsoft.Identity.Web.
