### ISSUE TITLE
SignalR Cpp connection start http error 105

### ISSUE THREAD

**Issue by HeMinzhang** [dotnet/aspnetcore#12120]
### Describe the bug
SignalR Cpp connection start http error 105

### To Reproduce

1. asp.net core signalR 1.1.0 in Microsoft.AspNetCore.App 2.2.0
2. The latest version of signalR Cpp

### Additional context
I guess if I must have asp.net core 3.0 preview？

**Comment by BrennanConroy** [comment]
Http status code 105 is a DNS error. Which seems unlikely to be a problem with the client.

Have you verified that the endpoint can be connected to without the cpp client?

**Comment by HeMinzhang** [comment]
https://github.com/HeMinzhang/SignalRCppErrorExample
This is my project, the endpoint can be accessed

**Comment by HeMinzhang** [comment]
https://github.com/HeMinzhang/SignalRCppErrorExample/tree/master/src/ConsoleApp1

![QQ截图20190713045406](https://user-images.githubusercontent.com/2683269/61159866-20dedb00-a530-11e9-8b03-151012f81f41.png)

c# client test example,already connection.

**Comment by HeMinzhang** [comment]
I upgraded vcpkg to the latest version, upgraded boost to 1.70.0, upgraded cpprestsdk to v2.10.13, still the same http 105 error

Then I used vs2019 to load the signalr to compile, copy the c++ console test example, and then compile, and it actually runs successfully.

For specific reasons, I don't understand, but I will upload the project to github

**Comment by HeMinzhang** [comment]
https://github.com/HeMinzhang/SingalRCppSuccessExample

**Comment by HeMinzhang** [comment]
I found that using signalrclient.dll generated by vs2019 can solve the problem.

**Comment by BrennanConroy** [comment]
Interesting, how were you compiling it before?

**Comment by HeMinzhang** [comment]
> PS> git submodule update --init
> PS> .\submodules\vcpkg\bootstrap-vcpkg.bat
> PS> .\submodules\vcpkg\vcpkg.exe install cpprestsdk:x64-windows
> PS> mkdir build.release
> PS> cd build.release
> PS> cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE="..\submodules\vcpkg\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
> PS> cmake --build . --config Release

> PS> git submodule update --init
> PS> .\submodules\vcpkg\bootstrap-vcpkg.bat
> PS> .\submodules\vcpkg\vcpkg.exe install cpprestsdk:x64-windows
> PS> mkdir build.debug
> PS> cd build.debug
> PS> cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE="..\submodules\vcpkg\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Debug
> PS> cmake --build . --config Debug

**Comment by anurse** [comment]
To set expectations: The SignalR C++ client is not shipping in .NET Core 3.0, so we'll look in to this but we may have 3.0 work with higher priority than this.

**Comment by alexsandro-xpt** [comment]
@anurse So, when this will be released?

**Comment by BrennanConroy** [comment]
Closing, unsure what the error is here.
