### ISSUE TITLE
[Suggestion] Stick all the community chat rooms together

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/aspnetcore#12156]
Hello Friends!

I've following/contributing to multiple repos under both AspNet/ and dotnet/ organisations and for that, I had to spread attention to multiple chat applications. Mostly on Slack and Gitter.

The most _hot_ of those chats today (meaning where is more discussions from the community) is the aspnet Slack workspace. However, there are core compoments like coreclr, corefxlab, roslyn and (many) others that are (hard to find) on Gitter.

What I would propose, for the sake of visibility of all OSS projects, is to merge the Gitter community into the Slack one and make it called dotnet rather than aspnet like it is today. 

That way would simplify the way community would meet and talk about the OSS projects on Microsoft ecosystem (not to mention will bring features that Gitter doesn't have to them).

@jongalloway / @terrajobst as you guys are heading .Net Foundation, what do you think?

Thanks!

PS: I don't know if this is correct repo to discuss this but I got lost on 170+ repos and nowhere is clear were to discuss it as the community is split. If there is a better place, please migrate the issue there.

**Comment by Eilon** [comment]
@Pilchie @DamianEdwards

**Comment by terrajobst** [comment]
@richlander @jongalloway @shanselman 

In principle I think that's a good idea. Personally I think Gittter would make more sense though.

**Comment by shanselman** [comment]
I agree, Gitter is open source and I'd prefer to not have a hard dependency on Slack

**Comment by lastlink** [comment]
what about discord

**Comment by terrajobst** [comment]
> what about discord

What benefit does it have over Gittter? We already use Gitter and it's built for GitHub. In my opinion, you'll have to offset that quite a bit.

**Comment by galvesribeiro** [comment]
Discord is more famous in the world of gaming... They are very game-oriented (i.e. now playing, shards, etc.) even thought some communities hang around there like (part of) Facebook devs with React rooms etc.

I like Slack because of its search and other features like voice calls. When helping people we just get in a call and quickly solve the problem without having to add everyone that ask for help on Skype or other VoIP app.

But yeah, the fact that Gitter is OSS is a big deal and if rest of the community migrate to it from Slack, I'm just fine as well.

My point was to really simplify comms and avoid different islands of community members...

Btw, on Gitter there is already the `dotnet/` (and `azure/` and other as well) namespace with many rooms, so it would be just a matter of create new ones for the aspnet, announce the deprecation of slack ones and let people come in...

**Comment by terrajobst** [comment]
> Btw, on Gitter there is already the `dotnet/` (and `azure/` and other as well) namespace with many rooms, so it would be just a matter of create new ones for the aspnet, announce the deprecation of slack ones and let people come in...

That's my thinking too.

**Comment by galvesribeiro** [comment]
Just adding more to that, AspNet team already merged the repos, so it would be a matter of just create 1 room like `dotnet/aspnet`.

**Comment by poke** [comment]
Discord doesn't really fit the code centric discussions we usually have. For that Slack and Gitter work best.

I agree that Gitter makes the most sense here as a general public chat, although I personally find it rather difficult to follow discussions there.

As for the rooms, I don't think it makes sense to restrict the discussion to a single room. There are far too many separate topics. On the .NET Core Slack, we have quite a few channels with varying topics to best fit everyone's interest. That works really well and we have a quite good set of people being able to help with these different topics.

> announce the deprecation of slack ones

As a very involved member of the Slack community, I honestly don't see that happening. The Gitter has been around for very long already and it is somewhat known that it is the “official chat”, yet there is a large number of active members in the Slack and the community actually continues to grow. I don't think the Gitter will be able to replace that equally. So it's more likely that both communities will continue to co-exist, with some members being part of both.

**Comment by galvesribeiro** [comment]
> As for the rooms, I don't think it makes sense to restrict the discussion to a single room.

No no, when I said I single room I meant not to bring the whole aspnetcore/ to a single room. it could and probably should be easier to migrate one by one starting by the bigger one which is asppet.

Like I said, I do think Gitter is a lot worse than Slack as I mentioned the reasons. 

I just would like that we had a single app to deal with, and the most usable prevail... The hard thing is that you eventually have duplicated channels on both sides. And some time ask duplicated questions there because they have different people...

I know that Slack is working pretty well for the aspnet core community so far and also know about the recommendation to keep away from Slack, even though it doesn't apply to OSS projects on MSFT. It is just too bad to have it away from the rest of .Net ecosystem...
