### ISSUE TITLE
Default Kestrel's Http2Limits.MaxRequestHeaderFieldSize to 32KB like MaxRequestHeadersTotalSize

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#12213]
KestrelServerOptions.Limits.Http2.MaxRequestHeaderFieldSize defaults to 8KB. This is the default maximum size for an HTTP/2 header value which is smaller than then default maximum size for an HTTP/1 header value which is equivalent to the default KestrelServerOptions.Limits.MaxRequestHeadersTotalSize (32 KB).

HTTP/1 doesn't have a per-header limit, and the MaxRequestHeadersTotalSize is already enforced for both HTTP/1 and HTTP/2. In order not to break existing apps upgrading to ASP.NET Core 3 that might currently accept headers between 8KB and 32KB in size, I think we should default KestrelServerOptions.Limits.Http2.MaxRequestHeaderFieldSize to 32 KB.

**Comment by halter73** [comment]
Eventually, if we decide that we want to limit both individual header value lengths and total header lengths, we should add a unified per-header-value limit to KestrelServerLimits directly instead of forcing the app developer to know about, understand and configure Http2Limits.MaxRequestHeaderFieldSize.

After all, the concept of a per-header-value limit isn't HTTP/2-specific.

**Comment by anurse** [comment]
Let's up it to 32KB for 3.0 .
