### ISSUE TITLE
Too many Files Open Error Even After Increasing Limit

### ISSUE THREAD

**Issue by muzzammilhussain** [dotnet/aspnetcore#12228]
I am using 2.1.505 dotnet core version. I am having a very strange issue, I have hosted the application on Ubuntu 18 Server. 3 servers are being used Postgres / Ubuntu /Nginx at 3 different places. The other two machines remain fine but after a while, I start getting this error on Ubuntu logs attached with the issue.
The limit is now increased to 164000 in kernel and soft by ulimit -n 

Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Request finished in 25.2332ms 200 application/json; charset=utf-8
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Request starting HTTP/1.1 POST http://ems.pgc.edu.pk/api/FeeStudentChallan/GetFindBy application/json;charset=UTF-8 118
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Successfully validated the token.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Route matched with {action = "GetFindBy", controller = "FeeStudentChallan"}. Executing action Cms360.UI.Controllers.Account.FeeStudentChallanController.GetFindBy (Cms360.UI)
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Connection id "(null)" communication error.
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: System.Net.Sockets.SocketException (23): Too many open files in system
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.RunAcceptLoopAsync()
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]:       Entity Framework Core 2.1.1-rtm-30846 initialized 'NpgSqlContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: using lazy-loading proxies MigrationsAssembly=Cms360.Data
Jul 16 11:44:46 ubnt-var dotnet-ems360[49075]: info: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]

**Comment by anurse** [comment]
If we can't get a socket there's not much we can do. Could you app be leaking file handles (i.e. not properly closing all of them)?
