### ISSUE TITLE
Shared cookie not being read by SignalR server.

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/aspnetcore#12236]
Im trying to share a cookie between a SignalR server and a ASP Core project using Identity cookies. 

### Describe the bug
When I make a request with an Identity Cookie from my ASP Core project to the SignalR server, I get an exception regarding authentication.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Http.Connections.Internal.AuthorizeHelper.AuthorizeAsync(HttpContext context, IList`1 policies)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteNegotiateAsync(HttpContext context, HttpConnectionDispatcherOptions options)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Clone this repo: https://github.com/KieranDevvs/SignalRCoreSharedCookies
3. Run both projects and insert the absolute directory to the shared singing key e.g
`C:\Users\KieranDevlin\Documents\git\sources\SignalRCoreSharedCookies\KeyRing`
4. Register a new user & login (registering logs you in) to obtain a cookie.
5. Visit the contact page (the page that has authorisation) to initialze the SignalR connection.
6. Open the browser console to see the handshake failed and see the SignalR server console to see the exception thrown.

### Expected behavior
I expect the cookie to be read and to have `Context.User` populated with the identity of the cookie.

**Comment by davidfowl** [comment]
The repo doesn't exist.

**Comment by KieranDevvs** [comment]
@davidfowl Apologies, I made it private by mistake.

**Comment by davidfowl** [comment]
You have UseAuthentication after UseSignalR, put it before.

**Comment by KieranDevvs** [comment]
@davidfowl Unfortunately I still get the same issue, I've updated the repo to reflect this.

**Comment by davidfowl** [comment]
Ah I didn’t look at the error properly. Where are you actually adding cookie authentication in the SignalR app?

**Comment by blowdart** [comment]
@davidfowl It's not there :)

@KieranDevvs `services.ConfigureApplicationCookie()` does nothing because you're not adding identity anywhere, and that's to configure part of Identity. So you either need to add identity in the same way you do in your other project, or add cookie middleware manually and set it to match the identity config.

**Comment by KieranDevvs** [comment]
@blowdart You are correct, adding an identity works however, how would I go about configuring an identity without using a store/db context as I don't intend on creating any users or cookies from the SignalR server (just authorising)

If I add just the identity by itself, dependency injection fails to construct the sign in manager:
```
services.AddDefaultIdentity<IdentityUser>();
```

**Comment by blowdart** [comment]
You can get away without validating the security stamp if you don't care about invalidating tokens, but to be honest you should care. However if you want to go down that route then it'd be something like

```
services
    .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options => 
    {
         options.Cookie.Name = ".AspNet.SharedCookie";
    });
)
```

**Comment by anurse** [comment]
Marking as discussion and it seems like there isn't a action item for SignalR here right now. We can adjust if necessary.

**Comment by fredyfx** [comment]
Is there any reason to add a cookie with signalR? Why not using JWT to do auth?

**Comment by KieranDevvs** [comment]
@fredyfx Our existing services use cookie based authentication and it seems easier to just use whats already provided rather than managing two sessions for essentially the same session.

**Comment by KieranDevvs** [comment]
@blowdart In regards to invalidating cookies, yeah I agree its best to validate the stamps however I'm trying to limit the round trips to the database as much as possible as the cookie will already be validated on the web app. I think I might look into storing some form of stamp in the servers memory space and implement a method of handling that without the DB context store.

**Comment by blowdart** [comment]
You could implement a validator that queries the database directly rather than go through the identity overhead.
