### ISSUE TITLE
For server-side Blazor, consider packing the reference frames more tightly

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#12306]
Currently, `RenderBatchWriter` uses 20 bytes per frame. It could be reduced to 14 bytes per frame via non-breaking changes as described in https://github.com/aspnet/AspNetCore/pull/12305/files#r304891742

**Comment by mkArtakMSFT** [comment]
Closing as this will be obsoleted by https://github.com/dotnet/aspnetcore/issues/35897
