### ISSUE TITLE
Adding the certificate to the Trusted Root Certificate store failed with the following error: Failed with a critical error

### ISSUE THREAD

**Issue by steffenlyng** [dotnet/aspnetcore#12356]
### Describe the bug
I have created a solution with a single ASP.NET Core Web Application project. When I try to run it I get a security error related to the certificate. 
Please see discussion: https://github.com/microsoft/DockerTools/issues/99#issuecomment-512973642
Additional related discussion: https://github.com/aspnet/AspNetCore/issues/3421

### To Reproduce
1. Create a new solution, with a single project (ASP.NET Core Web Application)
2. Using this version of ASP.NET Core 2.2
3. Enable docker support
4. Use Linux Container
5. Run project
6. Get the same error as here: https://github.com/microsoft/DockerTools/issues/147

### Expected behavior
Not to get an error

### Screenshots
https://user-images.githubusercontent.com/12519678/45336010-8dff9980-b536-11e8-9324-5993867fa3a1.PNG

### Additional context
I have not made any changes to the solution or projects. This happens with OOB scaffolding code.
- Visual Studio 16.1.6
- Docker Desktop 2.0.0.3
-- Engine 18.09.2
- ASP.NET Core 2.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe most of the issues related to the dev-certs tool have been addressed in later releases. We recommend updating to the latest .NET SDK.
