### ISSUE TITLE
Angular-CSharp migrations should be updated for 3.0

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/aspnetcore#12364]
@HaoK and I are doing this for the Identity templates (#12168), but the SPA templates [here](https://github.com/aspnet/AspNetCore/tree/master/src/ProjectTemplates/Web.Spa.ProjectTemplates/content) are a different non-Identity, model that I have no context on.

/cc @anurse @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
@ajcvickers will things break, if we don't do these updates?

**Comment by ajcvickers** [comment]
Probably not. You won't get the updates to migrations that we made in 3.0, but I doubt this will cause any actual issue for the scenarios you have.

**Comment by mkArtakMSFT** [comment]
I will put this in 3.1 in that case.

**Comment by javiercn** [comment]
Likely a super stale issue, we did this for sure in 5.0 at least I believe
