### ISSUE TITLE
Dotnet core 3-preview6 build warning - load Analyzer assembly

### ISSUE THREAD

**Issue by bahmansh** [dotnet/aspnetcore#12403]
When I want build my project I get following warning.

![Annotation 2019-07-21 102458](https://user-images.githubusercontent.com/19801131/61587566-ceda2d00-aba1-11e9-8342-1bfd3efae1ab.png)

**Comment by rynowak** [comment]
Can you share you project file? Where is the reference to the 2.2.0 version of the MVC analyzers coming from?

**Comment by bahmansh** [comment]
About your second question, I did not set it and I don't know exactly.


<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="*" />
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0-preview6.19307.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview6.19307.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="*" />
    <PackageReference Include="FluentFTP" Version="*" />
    <PackageReference Include="uaparser" Version="*" />    
    <PackageReference Include="System.Drawing.Common" Version="4.6.0-preview6.19303.8" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0006" />
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0006" />
    <PackageReference Include="DotNetCore.NPOI" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Gamma.Core">
      <HintPath>D:\GAC\GammaCore\Gamma.Core.dll</HintPath>
    </Reference>
    <Reference Include="RotativaCore">
      <HintPath>D:\GAC\lib\RotativaCore.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gamma.ITSM.AppCore\Gamma.ITSM.AppCore.csproj" />
    <ProjectReference Include="..\Gamma.ITSM.Services\Gamma.ITSM.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="WkHtmlToPdf\wkhtmltoimage.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="WkHtmlToPdf\wkhtmltopdf.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>

**Comment by pranavkm** [comment]
@bahmansh could you share the `project.assets.json` from the `obj` directory in your app? That should help.

**Comment by bahmansh** [comment]
[project.assets.json.zip](https://github.com/aspnet/AspNetCore/files/3420827/project.assets.json.zip)
@pranavkm

**Comment by bahmansh** [comment]
I removed obj folder but after build it contained "Microsoft.AspNetCore.Mvc.Analyzers": "2.2.0" again.

**Comment by pranavkm** [comment]
Thanks @bahmansh. The refererence is added transitively via the reference to https://www.nuget.org/packages/RotativaCore/.

@JunTaoLuo \ @davidfowl would you know why the package reference might not get knocked out. Here's the project.assets.json in a gist so it's easier to inspect: https://gist.github.com/pranavkm/9b87e51591754223854a5abe5cc29df9

**Comment by bahmansh** [comment]
So how can I resolve it?

**Comment by Pilchie** [comment]
@bahmansh Sorry this fell through the cracks.  Is this still an issue for you?

**Comment by bahmansh** [comment]
Yes, I get it yet.
I have upgraded my dot net core version to 3.1 but no thing changed.

**Comment by Pilchie** [comment]
@dsplaisted @nguerrera How should conflict resolution work here?  Would you expect it to knock out the whole `PackageReference` including analyzers, or just the assembly reference?

@bahmansh you could probably work around this with a `<PackageReference Remove=` for the transitive references.

**Comment by dsplaisted** [comment]
@Pilchie Conflict resolution doesn't apply to analyzers.  It looks like this is happening because the MVC analyzers moved from the package to the SDK (so it is similar to the problem that conflict resolution solves).

However, I wasn't able to reproduce this with a simple MVC project with a reference to RotativaCore.  I would guess it has to do with the way some of the other packages in the graph are including asset groups from their references.

I don't think there's a simple way to fix the warning, because ExcludeAssets doesn't work with analyzers: https://github.com/NuGet/Home/issues/6279

**Comment by JunTaoLuo** [comment]
This issue is related to how MVC analyzers are referenced so I'm updating the labels.

**Comment by pranavkm** [comment]
It looks like the latest version of the package downgraded their reference to MVC to 2.0 which does not transitively bring in the analyzer. It's likely that this resolves the issue. Closing this since we haven't heard any additional feedback on this issue.
