### ISSUE TITLE
Consider adding an overload of Listen that takes an EndPoint

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#12428]
To allow custom transport that supports any arbitrary EndPoint, we need to expose a Listen overload that flows this information to the transport. This came up when implementing named pipe transport.

Proposal:

```C#
public partial class KestrelServerOptions
{
    public void Listen(EndPoint endpoint);
    public void Listen(EndPoint endpoint, Action<ListenOptions> configure);
}
```

cc @shirhatti

**Comment by shirhatti** [comment]
Yes! Please make it happen

**Comment by shirhatti** [comment]
I'm sure @mconnew would want this as well 😄

**Comment by davidfowl** [comment]
Can we do this in 3.1?
