### ISSUE TITLE
Question - Low level caching in SignalR

### ISSUE THREAD

**Issue by Kikimora** [dotnet/aspnetcore#12433]
Let say I have typical single producer multiple consumers scenario with SignalR. Multiple clients connect and receive same data produced by one producer. Messages produced every second, every message produced could be in range of few hundred bytes to a couple of kilobytes. 

Number of clients could be in low hundreds of thousands. In this scenario I want to cache raw bytes of my messages and spit them out to clients. I imagine bytes can be copied directly into a socket buffers so I don’t waste time with serialization. Is this possible with SignalR?

**Comment by BrennanConroy** [comment]
If you create the message and send it using `Clients.All.SendAsync(...)` or `Clients.Group(name).SendAsync(...)` etc. then it will only be serialized once by SignalR and sent to all the clients.

But if you're wanting to send to multiple groups or multiple individual clients or send the same message multiple different times there is currently no way to do this.
The closest you can probably get is to base64 encode the message and pass that string in `SendAsync`.

We do have an issue tracking sending pre-serialized data: https://github.com/aspnet/AspNetCore/issues/5339
