### ISSUE TITLE
Dynamic Port Binding

### ISSUE THREAD

**Issue by endeffects** [dotnet/aspnetcore#12451]
It would be really helpfull if you would support dynamic port bindings on the launchSetting.json for IIS and Kestrel hosting enviroments.

**Comment by Tratcher** [comment]
Can you elaborate? What would you expect to enter in launchSettings.json and how would you expect the server to react?

**Comment by davidfowl** [comment]
Doesn’t passing 0 for the port work?

**Comment by endeffects** [comment]
Nope, this ends up in an invalid address error.

**Comment by davidfowl** [comment]
I believe it works for Kestrel but not for IIS. Can you describe what you're trying to do?

**Comment by endeffects** [comment]
Well, i just want to ensure that the applications are able to run on each developer machine.
So picking the ports automatically is the prefered choice in my opinion.

**Comment by Tratcher** [comment]
The other option is not to check in the launchsettings.json file, let VS create it locally. The way VS selects ports is less likely to conflict locally, and the dev can change it without affecting anyone else.
