### ISSUE TITLE
Provide FileVersionProvider Async Option

### ISSUE THREAD

**Issue by deanmarcussen** [dotnet/aspnetcore#12466]
### Is your feature request related to a problem? Please describe.
When replacing the `DefaultFileVersionProvider` my replacement needs to make async calls.

Specifically the use case is to retrieve the `ContentMD5` property from an Azure Blob Store with `blob.FetchAttributesAsync()` from within a tag helper, which has an async option, and then from the `IFileVersionProvider`, which has no `Async` option

### Describe the solution you'd like
Implement an Async option, like the Tag Helpers do, i.e. 

`string AddFileVersionToPathAsync(PathString requestPathBase, string path)`

### Additional context

I can call `.GetAwaiter().GetResult()` but would prefer to be using async all the way.

**Comment by mkArtakMSFT** [comment]
I believe you ment

```csharp
Task<string> AddFileVersionToPathAsync(PathString requestPathBase, string path)
```

**Comment by deanmarcussen** [comment]
> I believe you ment
I believe you're correct 😄

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
