### ISSUE TITLE
`dotnet-watch run` fails when there are access-denied folders

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#12484]
_From @Shuenhoy on Tuesday, July 23, 2019 10:38:11 AM_

## Steps to reproduce

```bash
$ mkdir test
$ sudo chown 0:0 test
$ sudo chmod 700 test
$ dotnet watch run
```

## Expected  behavior
`dotnet-watch` should ignore the `test` folder.

## Actual behavior
`dotnet-watch` fails with exception `System.UnauthorizedAccessException: Access to the path 'test' is denied. ---> System.IO.IOException: Permission denied`

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  3.0.100-preview6-012264 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

_Copied from original issue: dotnet/cli#11977_

**Comment by anurse** [comment]
_From @livarcocc on Tuesday, July 23, 2019 5:09:15 PM_

@anurse can you move this issue to asp.net? In the CLI, we just take a package for this verb from asp.net.

**Comment by anurse** [comment]
Why would you expect `dotnet watch` to ignore the `test` folder? Have you excluded it from your project? If not, `dotnet watch` needs to be able to see inside that folder to detect changes within it.

Can you post a runnable sample (with necessary `chmod` steps) that reproduces the problem so we can see the full project layout?

**Comment by Shuenhoy** [comment]
> Why would you expect `dotnet watch` to ignore the `test` folder? Have you excluded it from your project? If not, `dotnet watch` needs to be able to see inside that folder to detect changes within it.
> 
> Can you post a runnable sample (with necessary `chmod` steps) that reproduces the problem so we can see the full project layout?

I found that I can only reproduce the problem in the docker containers with non-root user  (docker image is "mcr.microsoft.com/dotnet/core/sdk:3.0"). When I do the same thing in the host OS with the same dotnet version, I will only get a yellow-color warning and it can continue to work. However, `dotnet run` also works well in the containers.

```
watch : The file watcher observing '<project root>' encountered an error: Access to the path '<project root>/test' is denied.
```

BTW, I have tried to add the following items into my `.csproj` file, but I can still not solve the problem.

```xml
 <ItemGroup>
    <Watch Include="**/*.cs" Exclude="test\**\*" />
    <Compile Remove="test\**\*" />
    <Content Remove="test\**\*" />
  </ItemGroup>
```

**Comment by anurse** [comment]
> BTW, I have tried to add the following items into my `.csproj` file, but I can still not solve the problem.

That does seem like something we could investigate. I definitely agree that it should be possible to exclude an entire directory and avoid this kind of issue.

**Comment by mkArtakMSFT** [comment]
This looks like caused by how MSBuild evaluation works, rather than a behavior of the dotnet watch tool. Given that this has not been impacting community in general and we haven't heard many complains, I'm going to close this for now.
