### ISSUE TITLE
Issue adding .razor page with the same name as your project

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#12517]
[Reported by a customer](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-7/#) on the ASP.NET Core 3.0 Preview 7 blog post:

I found an issue when you add .razor page with the same name as your projects (and a using statement referencing for example the Data namespace, the namespace recognition is messed up and you end up with several errors, not knowing where they come from :-) Anyway I figured out what it is so I know what to do and have steps to reproduce it: 

1. Create a new project dotnet new blazorserverside -o <someproject> 
2. In the Pages folder add a razor page with the exact same name as <someproject> add a @page "/gotothispage" add a @using <someproject>.Data  
3. Compile You end up with a lot of namespace errors.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by pranavkm** [comment]
This should be resolved as part of https://github.com/dotnet/aspnetcore/issues/18757.
