### ISSUE TITLE
[Blazor] Add build error when Blazor version does not match sdk version

### ISSUE THREAD

**Issue by RemiBou** [dotnet/aspnetcore#12562]
### Is your feature request related to a problem? Please describe.
Currently if you update your sdk version (in global.json) without updating the Blazor assembly reference version, you got a regular build error that some method doesn't exists or something else.

### Describe the solution you'd like
This problem is due to the fact that the class file for component are generated by the SDK and the razor compiler which expect you to have a specific version of Blazor. Maybe it would be a good idea in the SDK to check the referenced Blazor assembly and check if it's compatible with the generated code. This will reduce the amount of issues created at each new version (for instance from preview6 to 7 the signature of BuildRenderTree changed).

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by pranavkm** [comment]
Now that Blazor WASM and Server are GA, this should no longer be an issue. The API surface is stable and we validate that newer versions of the SDK are compatible with older versions of the framework.
