### ISSUE TITLE
[Question] Server-side Blazor: Inject javascript file

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#12604]
I would like to inject javascript file e.g.: **article.js** on url `/article/{title}`. I couldn't find at docs steps how to do it. Is there anything like this implemented?

I dont want to have article.js on all pages if there is code that is not needed to be executed / parsed by browser.

Something like `@scripts` in MVC would be nice.

If not, do I have to do it by creating global javascript file where I can put function to append script tag before end tag of body? Then call it `OnInitAsync` / `OnInit` by `IJSRuntime`?

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by glararan** [comment]
Ok so I will have to use `IJSRuntime` workaround at .NET Core 3 release time.
Anyway thanks for answer

**Comment by SteveSandersonMS** [comment]
With .NET 5 we recommend using `import` for this: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references
