### ISSUE TITLE
InputNumber doesn't work with javascript interop (focus, select, etc.)

### ISSUE THREAD

**Issue by alexandrereyes** [dotnet/aspnetcore#12619]
I have a EditForm and i'm trying to set focus on some InputNumber field, unfortunately, it doesn't work, no error is showed neither focus occur...
If I change the code bellow to a simple `<input @ref="myInput" />` it works.

```
<EditForm>
        <InputNumber @ref="myInput" />
</EditForm>

@code
{
        protected InputNumber<int> myInput;

        [Inject]
        protected MyBrowserInteropInjection MyBrowserInteropInjection{ get; set; }

        protected async override Task OnInitAsync()
        {
              MyBrowserInteropInjection.Focus(myInput);
        }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alexandrereyes.
JS Interop should happen `OnAfterRender` phase.

**Comment by alexandrereyes** [comment]
Since I disabled server side rendering, OnInit with JsInterop works very good! 
But.....even on OnAfterRender event, the above code doesn't work.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.
