### ISSUE TITLE
Consider mitigations for select elements vs untrusted data

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#12616]
One quirk of server-side Blazor is that events sent from the client are untrusted data.

This means that some of your base assumptions about how features like `<select>` can be violated. For instance in the following example literally anything could be passed to the server as the selected value.

```razor
<select @bind="size">
  <option value="Sizes.Small">small</option>
  <option value="Sizes.Medium">medium</option>
  <option value="Sizes.Large">large</option>
</select
```

The value that the server sees might be a value that's not in the list like `Sizes.XXL`.

----

We need to provide docs and guidance about this since it's something developers will have to understand. I propose we doc this for 3.0

**Comment by mkArtakMSFT** [comment]
This is already covered in the Blazor Security docs.
