### ISSUE TITLE
Support Microsoft Identity Platform v2 endpoints.

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#12626]
This is a (mostly placeholder) issue to track migrating template and AAD auth support to Microsoft Identity Platform v2 endpoints.

**Comment by anurse** [comment]
cc @blowdart @jmprieur this is our tracking item for updating to these v2 endpoints in 5.0, feel free to post any content related to that here so we can reference it if you have any

**Comment by jmprieur** [comment]
Thanks @anurse. We'll do. When for do you need content?

**Comment by anurse** [comment]
> When for do you need content?

This is targeting 5.0 so there's a good amount of lead time. I don't have a specific date we need content by (I also don't have the full context on what we need, @blowdart and @Tratcher might have more thoughts).

**Comment by blowdart** [comment]
When we discussed this earlier in the year we had decided upon AAD giving use the new startup code, which didn't rely on .UseAzureAd but rather used the ODIC configuration directly with helper functions, or with as minimal a wrapper as possible, in the form of an MVC app with just that in the configuration pieces. So, that.

**Comment by brentschmaltz** [comment]
@blowdart agreed, we are working on this.

**Comment by jmprieur** [comment]
@blowdart we are. Do you have expected ETAs?

**Comment by blowdart** [comment]
End of December / Early Jan would be good then we can experiment with it :)

**Comment by JunTaoLuo** [comment]
The work has been completed as part of the two PRs: https://github.com/dotnet/aspnetcore/pull/24167 and https://github.com/dotnet/aspnetcore/pull/24268
