### ISSUE TITLE
Blazor client project - conditional package references not working correctly

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#12651]
## Describe the bug
When a `<PackageReference>` is included in a blazor client project (csproj), and it has a condition - such as:

```
 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
<PackageReference Include="NetPack.BrowserReload.BlazorClient" Version="0.3.0-alpha0108" Condition="$(DefineConstants.Contains(DEBUG))" />
  </ItemGroup>
```

Swithing from Debug build configuration, to Release configuration, the first quirk (but not the primary reason I open this bug) is that the nuget package still shows in the dependencies node of the project in solution explorer, until you unload the project, then reload it manually:

before reload (but after a re-build):

![image](https://user-images.githubusercontent.com/3176632/61997452-7622fc80-b099-11e9-9ce7-26bbf18fc7f7.png)

after manually unloading then reloading the project - now the dependency us correctly removed from display:

![image](https://user-images.githubusercontent.com/3176632/61997468-b4202080-b099-11e9-9ca6-c0e071c4c207.png)

However the more worrying bug, is even though this dependency should now not technically be part of a Release build, and having deleted the bin release directory, it's still output to the bin  part of the release build:

![image](https://user-images.githubusercontent.com/3176632/61997491-1416c700-b09a-11e9-9c45-dcdec37a7798.png)

### To Reproduce
1. Install latest VS2019 Preview
2. Create a new blazor client project
3. Add a package reference with a condition on a compilation constant as show above.
4. Switch build configurations so the compilation constant becomes false - rebuild the project (even after an unload reload) - the referenced package assemblies are still included in build output.

### Expected behavior
If a package reference is excluded from the build I would not expect to still see it's output assembly in the bin output folder after a build.
### Screenshots
Shown above

### Additional context
I'm using latest vs 2019 preview, but my solution has a global.json file pinning the .net core sdk to preview 6. My blazor project is still at preview6.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
We don't control this functionality.
@livarcocc who should be the person to look into this?

**Comment by livarcocc** [comment]
Actually, this seems like a nomination bug to me. As in, it seems the project system does not know to re-run restore (which it will need to, since packages changed) based on conditions. @jjmew is there a bug for this already in dotnet/project-system? Should this one be moved there?

**Comment by dazinator** [comment]
Reminder to check this with the latest vs2019 16.3.0 preview 2 to see if it's still an issue or was coincidentally fixed.

**Comment by dazinator** [comment]
I retested this in Microsoft Visual Studio Professional 2019 Version 16.5.4.

The main bug is fixed.

The side issue (smaller bug) is still present - i.e if you switch Build Configurations in VS (i.e from Debug to Release etc) the project's dependencies list in Solution explorer doesn't refresh to display the set of dependencies only relevent for that new build configuration - you need to unload and reload the project and then it does.

**Comment by pranavkm** [comment]
> The side issue (smaller bug) is still present - i.e if you switch Build Configurations in VS (i.e from Debug to Release etc) the project's dependencies list in Solution explorer doesn't refresh to display the set of dependencies only relevent for that new build configuration - you need to unload and reload the project and then it does.

While PackageReferences are allowed to be configuration specific, the output of NuGet restores are invariant to the build configuration. That may explain why VS does not re-trigger a restore on configuration change and why the Solution Explorer does not update. That said, using the VS feedback utility is a better way get this routed to the correct team.

**Comment by dazinator** [comment]
> That said, using the VS feedback utility is a better way get this routed to the correct team.

I'm not sure I care enough about this issue in all honesty to warrant spending 10 minutes creating the issue in VS feedback and the following up the inevitable questions and comments. ;-)

Closing
