### ISSUE TITLE
Components solution does not build due to missing .npmproj

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#12653]
This is failing after the recent changes to fix the build of our node-related projects.

![image](https://user-images.githubusercontent.com/1430011/61997813-40135780-b05c-11e9-81dd-9e0717f2feed.png)

VS doesn't appear to support adding projects with arbitrary `.*proj` file extensions (not an option in the UI, and the commandline `dotnet sln add` rejects it).

If I use my l33t hacker skills to edit the sln by hand then I get errors like:

```txt
36>C:\git\aspnet\AspNetCore\src\Components\test\testassets\BasicTestApp\BasicTestApp.csproj : error NU1105: Unable to find project information for 'C:\git\aspnet\AspNetCore\src\Components\Web.JS\Microsoft.AspNetCore.Components.Web.JS.npmproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution so please run a restore from command-line. Otherwise the project file may be invalid or missing targets required for restore.
36>Done building project "BasicTestApp.csproj" -- FAILED.
```

---

I think we either need to make these project conditional based on VS - or we need to change them to `.msbuildproj` - which is the file extension for general-purpose msbuild-based projects.

**Comment by dougbu** [comment]
Hmm, @Pilchie and @pranavkm our AspNetCore.sln file does not contain any `*.npmproj` projects nor any `*.javaproj` projects. In fact there are no matches for `"src\\.*[^c][^s]proj"` in the solution file at all. Won't that break people who just run `.\restore.cmd` from the command line and attempt to build many of our filtered solutions❔

**Comment by pranavkm** [comment]
I don't think sln files can include npmproj files. Projects that depend on the build output of npmproj files manually build them e.g. https://github.com/dotnet/aspnetcore/blob/master/src/Components/Server/src/Microsoft.AspNetCore.Components.Server.csproj#L31-L37

**Comment by dougbu** [comment]
@pranavkm should special cases like that work when building in VS❔ Or, are users _required_ to build the `*.npmproj` projects before building in VS❔

**Comment by pranavkm** [comment]
We require users to build the project from the command line before launching in VS. We've tried automating the npm reference and that does not work.

**Comment by dougbu** [comment]
@captainsafia this issue indicates a gap in the [src/Components/README.md](https://github.com/dotnet/aspnetcore/blob/master/src/Components/README.md) file. That file should indicate that executing [src/Components/build.cmd](https://github.com/dotnet/aspnetcore/blob/master/src/Components/build.cmd) before opening Visual Studio is strongly suggested because otherwise the NPM projects will not be up-to-date and the .NET SDK or runtimes may be missing.

**Comment by captainsafia** [comment]
@dougbu Done in https://github.com/dotnet/aspnetcore/pull/27833.
