### ISSUE TITLE
Investigate new transport options for SignalR

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#12662]
Historically we've picked transports for SignalR based on what was available in browsers since Javascript was the primary target. We've evolved since then and are now based on bedrock (on both the server and .NET client) which gives us the ability to run on transports. Since the original SignalR we've done WebSockets, Server-Sent-Events (SSE) (or EventSource in the browser), and LongPolling. With the new fetch APIs it might be possible to support some new scenarios that weren't possible before:

- HTTP/2 based bi-directional streaming (Request streaming isn't implemented in browsers as yet). The benefit here is that we can use HTTP/2 streams as connections which makes it very cheap to create hub connections. It no longer takes up an entire TCP connection, it's just muxed on top of any existing connection. This also benefits us for when HTTP/3 comes around as it has similar semantics. 
    
- Replace Server-Sent-Events with a long running streaming response. This enables us to work around the overhead and limitations of SSE (like being text only and having a specific framing).

Both proposals would let us use bearer tokens via headers since we'd be controlling the request initiation.

*If websockets over HTTP/2 and HTTP/3 becomes a thing, we wouldn't need this though as it would do similar things (though a a little more overhead).*

**Comment by anurse** [comment]
We're tracking this work as part of https://github.com/dotnet/aspnetcore/issues/21104 now.
