### ISSUE TITLE
[Feature Request] UserManager inconsistencies in confirming tokens

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#12672]
## Background

Identity's `UserManager` does not behave consistently when confirming tokens.

Examples:

I can call `userManager.ConfirmEmailAsync(...)` multiple times, and it will succeed each time even though the token was already redeemed. This tells me that although the token was redeemed, it is still valid and unexpired.

I can call `userManager.ChangeEmailAsync(...)` only once successfully, and will return errors afterwards. This tells me that the token is 1) invalid or 2) expired or 3) redeemed.

There are other such methods, with the same inconsistency.

## Problem
This inconsistency makes it difficult/impossible to correctly interpret errors for the user.

Is the token "invalid", or is it expired, or is it simply already redeemed? Those are different errors, and they lead to two different actions by the user.

This is a source of friction for our users, who end up in a never-ending loop of redoing some action, then incorrectly interpreting the error and asking for another token, etc. And eventually they call us and we need to make the changes manually.

## Solution
Please return a standard result from these related methods, so we can tell whether:
1. the token is invalid (possibly due to hacking, etc.), so no action was taken
2. the token is valid, but is expired, so no action was taken
3. the token is valid, but it has already been redeemed, so no action was taken
4. the token is valid, unexpired and unredeemed, so the action was taken

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
