### ISSUE TITLE
[Discussion] ASP.NET Core master branches have switched to "5.0"

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#12732]
Various ASP.NET Core repos have switched their master branches to "5.0", and will use 3.x branches for 3.0 and 3.1 projects. We will evaluate incoming work and make individual decisions on whether to back-port the work to 3.1. The version number being used is `5.0.0-alpha1`. This does not indicate a specific name or timeline for the initial preview release, it’s just a pre-release tag that allows us the flexibility to change the version as necessary. The [.NET Core Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) is the authoritative source for committed release schedules. 

At present, this change is only relevant if you contribute to ASP.NET Core repositories. Otherwise, we recommend that you wait for the official 5.0 Preview releases before installing this new version.

## Details
The following repos have moved their master branches to "5.0":

* [aspnet/AspNetCore](https://github.com/aspnet/AspNetCore)
* [aspnet/AspNetCore-Tooling](https://github.com/aspnet/AspNetCore-Tooling)
* [aspnet/Blazor](https://github.com/aspnet/Blazor)
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore)
* [aspnet/Extensions](https://github.com/aspnet/Extensions)

In addition, the [aspnet/EntityFramework6](https://github.com/aspnet/EntityFramework6) repository has changed version numbers to 6.4 to reflect a version after the 6.3 release in progress. Again, there is no specific timeline or committment for this release.

Version numbers may still change during the development cycle for 5.0. This change is being done to reflect the current plans. 

In large part, we switched master to 5.0 to enable to the community to contribute changes. As the .NET Core 3.0 release progresses towards the final build, we're increasing scrutiny on the changes we will accept. Now that we've permanently branched for 3.0, we can accept a much broader set of changes. Please consider that to be an open invitation!

At present, there is no SDK or developer experience for 5.0. Switching your project file to target `netcoreapp5.0` won't do anything useful. Look for a follow-up announcement when this experience is available.

**Comment by OdeToCode** [comment]
Would it be possible to update the [Use the Result of Your Build](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#use-the-result-of-your-build) instructions for contributors? The last update looks to be in the 3.0 time frame and using the build doesn't seem as easy adding a NuGet.config these days.

**Comment by Pilchie** [comment]
@aspnet/build @anurse @mkArtakMSFT Can someone take point on this?
