### ISSUE TITLE
HTTP/2 Clients can see truncated responses despite reading above minimum data rate.

### ISSUE THREAD

**Issue by analogrelay** [dotnet/aspnetcore#12785]
In https://github.com/aspnet/AspNetCore/issues/12222, @halter73 observed:

> This highlights a bug that is introduced by moving the MaxResponseBufferSize to the transport options. Now, even if the client reads continuously above the minimum data rate it can still see truncated responses due to a drain timeout if the MaxResponseBufferSize is increased for m the default. Less importantly, the drain timeout is not as aggressive as it could be when the buffer size is reduced.

We should look at improving this to avoid this unintentional extra limiting

**Comment by anurse** [comment]
We'll doc that these should be set to the same value and leave it at that until we get more feedback.

**Comment by anurse** [comment]
It's and edge case and you can work around it by setting the values to the same thing. We'll look at cleaning this up in 5.0

**Comment by amcasey** [comment]
I'm having trouble determining which setting has to be kept in sync with `MaxResponseBufferSize`.  I would guess `MinRequestBodyDataRate`, but they're not obviously in sync now: the default max buffer size is 64 KiB and the default rate limit is 240 Bps after a 5 second grace period.  Also, both are on `KestrelServerLimits`, which is not obviously the same as the "transport options" where they were when this was filed.  Maybe we addressed the underlying issue.

@halter73 Are you aware of an outstanding issue in this area (other than the fact that `MinRequestBodyDataRate` is hard to reason about) or can I close this?

**Comment by amcasey** [comment]
Offline, @halter73 suggested that the two settings were `MaxWriteBufferSize` on `SocketConnectionFactoryOptions`, `SocketTransportOptions`, `QuicTransportOptions`, and `NamedPipeTransportOptions` and `KestrelServerLimits.MaxReponseBufferSize`.

**Comment by amcasey** [comment]
I don't think it makes sense to add documentation answering a question no one is asking and that we plan/hope to remove in the next release.
