### ISSUE TITLE
DynamicTable Resize doesn't handle circular scenarios

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#12784]
DynamicTable uses a circular buffer, but it's Resize API doesn't account for that. When Resize copies the underlying buffer it can end up inserting that new blank space in the middle of the circular buffer, throwing off the indexes.
https://github.com/aspnet/AspNetCore/blob/c703093346c903fc05eb6108c0ef7b8a8205c95c/src/Servers/Kestrel/Core/src/Internal/Http2/HPack/DynamicTable.cs#L63-L76

No external reports of this yet, table resize doesn't appear to be a common action, especially not after the first settings frame.

@geoffkizer Same for the corefx copy.
https://github.com/dotnet/corefx/blob/06d215d9fe6fff08f81add5ed341641f668075c0/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/DynamicTable.cs#L62-L77

**Comment by geoffkizer** [comment]
@Tratcher Thanks for the heads up. We disable dynamic table usage, so this won't affect us for this release.

**Comment by anurse** [comment]
We're not aware of clients that do this, but I'd like to look at this in the 3.x wave sometime because I don't like waiting all the way to 5.0 to resolve a correctness bug.

**Comment by anurse** [comment]
My gut feeling is to hold until we get customer reports, which doesn't feel great, but I don't see us having resources to invest proactively here.

**Comment by Tratcher** [comment]
If we do get customer reports this is going to be patch worthy (data corruption). Start with up-for-grabs? The fix is not complex.

**Comment by anurse** [comment]
Ok, fair. If it's a small we can probably find time to do it. I was mostly being conservative not fully understanding the change. We can chat in planning, just putting my initial sentiment in.

**Comment by KonradMasalski** [comment]
Hi, Isn't it already fixed at https://github.com/dotnet/corefx/pull/40040/files? If It is just a matter of moving the code, I can tackle that one.

**Comment by Tratcher** [comment]
@kmasalski yeah, looks like they addressed this in a separate copy.

**Comment by kmasalski** [comment]
@Tratcher it is already moved to master https://github.com/dotnet/aspnetcore/blob/master/src/Shared/runtime/Http2/Hpack/DynamicTable.cs. It seems that the issue can be closed

**Comment by Tratcher** [comment]
Should make sure we have some tests before closing this.

**Comment by TimmyGunawan123** [comment]
> DynamicTable uses a circular buffer, but it's Resize API doesn't account for that. When Resize copies the underlying buffer it can end up inserting that new blank space in the middle of the circular buffer, throwing off the indexes.
> https://github.com/aspnet/AspNetCore/blob/c703093346c903fc05eb6108c0ef7b8a8205c95c/src/Servers/Kestrel/Core/src/Internal/Http2/HPack/DynamicTable.cs#L63-L76
> 
> No external reports of this yet, table resize doesn't appear to be a common action, especially not after the first settings frame.
> 
> @geoffkizer Same for the corefx copy.
> https://github.com/dotnet/corefx/blob/06d215d9fe6fff08f81add5ed341641f668075c0/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack/DynamicTable.cs#L62-L77

I still dont know bout this one..  http://hapetfs.com/

**Comment by Kahbazi** [comment]
@Tratcher Which scenarios should the tests cover? Is it good enough to just bring the tests from [runtime](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/Tests/System/Net/aspnetcore/Http2/DynamicTableTest.cs) to this repo?

**Comment by Tratcher** [comment]
Yes, those should be a good start.

**Comment by Kahbazi** [comment]
@Tratcher I was looking at the old version of `DynamicTableTests`. Looks like all the tests from the runtime is already in this repo. Any special scenario you had in mind that need to be tested?

**Comment by JamesNK** [comment]
Looked into this and it was fixed here - https://github.com/dotnet/corefx/pull/40040

There is already a unit test `DynamicTable_Resize_Success` that tests different resizing issues in detail.

Nothing to do here.
