### ISSUE TITLE
Expand event handling to BOM events

### ISSUE THREAD

**Issue by ChrisMyrick** [dotnet/aspnetcore#12798]
Please consider adding the ability to handle BOM window events. An example use case would be in creating a custom install dialog for a Blazor PWA by leveraging the "beforeinstallprompt' event.

```
    window.addEventListener('beforeinstallprompt', (e) => {
        console.log('beforeinstallprompt', e);
        // prevent Chrome 67 and earlier from automatically showing the prompt
        e.preventDefault();
        // save the event so it can be triggered later.
        window.deferredPrompt = e;
        ...

```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ChrisMyrick.
We will try to do something in this area in the future. For now you can simply use JSInterop.

**Comment by ChrisMyrick** [comment]
@mkArtakMSFT - Thank you for the response. I would like to request that we revert this issue back to identifying BOM versus DOM. I don't readily see a way to leverage JSInterop for the BOM, because in this case, you aren't calling a JavaScript function directly based on a DOM event, but rather listening for a BOM (Browser Object Model) event to occur.

https://developer.mozilla.org/en-US/docs/Web/API/Window/onbeforeinstallprompt

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
