### ISSUE TITLE
Rzc should respect WarningsAsErrors

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#12814]
Follow up to https://github.com/aspnet/AspNetCore-Tooling/pull/922#issuecomment-517412593

Right now Razor diagnostic warnings won't fail the build even if WarningsAsErrors is set to true. The work here probably involves wiring that up during Razor compilation just like how Roslyn passes it in to csc.

**Comment by pranavkm** [comment]
We think this should be resolved as part of the source generator changes.
