### ISSUE TITLE
Blazor page error takes much longer time to show up

### ISSUE THREAD

**Issue by wli3** [dotnet/aspnetcore#12845]
### Describe the bug
Find in appbuilding exercise. When editing Blazor page with VS. The error take much longer to show up than normal C# file. And the delay is too long I need to slow down my typing.

### To Reproduce
1. Using this version
SDK 3.0.100-preview9-013654

2. Create a page on top of _dotnet new blazorserver_
3. Edit the page
4. 

See the delay between the change and the red squiggle showed up
![slow_error](https://user-images.githubusercontent.com/6993335/62399060-6854f780-b52f-11e9-929f-be9fe3226a67.gif)

### Expected behavior
The error shows faster

#### VS info
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.3.0 Preview 2.0 [29131.210.master]
VisualStudio.16.IntPreview/16.3.0-pre.2.0+29131.210.master
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.184.47901
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.184.47901
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.184.47901
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.184.47901
Azure Functions and Web Jobs Tools

C# Tools   3.3.0-beta2-19375-02+3e79b161117fd14bfc7ef6158e48f8eae01211c3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2018.3.4   Build 183.0.20190304.43214
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20726.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61907.31040
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10730.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.0-beta2-19375-02+3e79b161117fd14bfc7ef6158e48f8eae01211c3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19381.3+8e8a754ab056dc16f6dda49110fe8729d1bbabc9
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

####  SDK info
λ  dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-013654
 Commit:    1d6333d63b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-013654\

Host (useful for support):
  Version: 3.0.0-preview8-28379-12
  Commit:  38f6ef72ca

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013437 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-013654 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19374.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19401.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28379-12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28379-12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @wli3.
@NTaylorMullen can you please suggest who should be looking into this? Somebody from the tooling team maybe?

**Comment by NTaylorMullen** [comment]
@heejaechang Does this fall on your plate?

**Comment by allisonchou** [comment]
Lots of improvements have been made in the new Razor editor perf-wise, so closing out this issue for now.
