### ISSUE TITLE
Should respect cancellation token when waiting on connection lock. 

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/aspnetcore#12882]
Waiting on the connection state lock in the `HubConnection` and `HttpConnection` should respect cancellation token

The `WaitConnectionLockAsync` method should take a cancellation token and  pass it into the `WaitAsync` method.
https://github.com/aspnet/AspNetCore/blob/4921dc3aa3496eb3e9fe73255213ce54a0ba29d6/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L1926-L1930

We also  need this in `HttpConnection` here
https://github.com/aspnet/AspNetCore/blob/4921dc3aa3496eb3e9fe73255213ce54a0ba29d6/src/SignalR/clients/csharp/Http.Connections.Client/src/HttpConnection.cs#L207

**Comment by anurse** [comment]
Let's do it in master. We talked through the cancellation impact and it should be fine.
