### ISSUE TITLE
MultiSelectList should be inter-operable with SelectListItem with a nested SelectListGroup

### ISSUE THREAD

**Issue by AqeelAT** [dotnet/aspnetcore#12948]
I was trying to create a multi select list using tag helpers. However, I cannot use my SelectListItems if I want to also use `<optgroups>`. MultiSelectList gets the value of the field named Group which is `Microsoft.AspNetCore.Mvc.Rendering.SelectListGroup` and groups them under that name.

Solution:
Adding the constructor:
`public public MultiSelectList( IEnumerable<SelectListItem> items, IEnumerable selectedValues)` that sets up the list to get the group names `SelectListItem.Group.Name` or something like that.

Page Model:
```c#
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Test.Pages.Home
{
   public class testModel : PageModel
   {
      public MultiSelectList MultiItems { get; set; }

      [BindProperty]
      public List<string> SelectedItems { get; set; }

      public void OnGet()
      {
         var group1 = new SelectListGroup{Name = "Group 1"};
         var group2 = new SelectListGroup{Name = "Group 2"};
         var items = new List<SelectListItem>();
         items.Add(new SelectListItem{Text = "one", Value = "1", Group = group1 });
         items.Add(new SelectListItem{Text = "two", Value = "2", Group = group1 });
         items.Add(new SelectListItem{Text = "three", Value = "3", Group = group2 });
         items.Add(new SelectListItem{Text = "four", Value = "4", Group = group2 });
         MultiItems = new MultiSelectList(items, "Value", "Text", new []{1,2}, "Group");
      }

      public void OnPost()
      {
         Console.Write(SelectedItems);
      }
   }
}
```
Page:
```c#
@page
@model Test.Pages.Home.testModel
@{
    ViewData["Title"] = "test";
   Layout = null;
}

<form method="post" asp-page="/Home/Test">
   <select multiple asp-for="SelectedItems" asp-items="Model.MultiItems"></select>
   <input type="submit" value="Submit"/>
</form>
```
HTML Output:
```html
<html>
      <head></head>
      <body style="">
            <form method="post" action="">
                  <select multiple="" id="SelectedItems" name="SelectedItems">
                        <optgroup label="Microsoft.AspNetCore.Mvc.Rendering.SelectListGroup">
                              <option selected="selected" value="1">one</option>
                              <option selected="selected" value="2">two</option>
                              <option value="3">three</option>
                              <option value="4">four</option>
                        </optgroup>
                  </select>
                  <input type="submit" value="Submit">
            </form>
      </body>
</html>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AqeelAT.
We've heard similar feedback in the past so putting this into the 5.0 release for now to reevaluate later.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by AqeelAT** [comment]
Can I implement it myself?

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
