### ISSUE TITLE
Blazor debugging on linux chrome

### ISSUE THREAD

**Issue by navneetgarggate6** [dotnet/aspnetcore#12970]
### Describe the bug
Trying to debug blazor app on the linux chrome 73

I ran following command
dotnet run --configuration Debug
google-chrome --remote-debugging-port=9222 http://localhost:5000/

### Screenshots
![image](https://user-images.githubusercontent.com/16791876/62702871-86c26380-ba05-11e9-98f3-dd625c464555.png)

When i check the console getting following error

Access to XMLHttpRequest at 'http://localhost:5000/css/bootstrap/bootstrap.min.css.map' from origin 'http://localhost:9222' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
shell.js:8066

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS there were several debugging-related issues which I assigned to you. If you believe they're not related and would like to load-balance a bit, let me know.

**Comment by guardrex** [comment]
Adding a note here: This issue doesn't seem to be the same cause of one potential source of trouble that came up on a docs issue (`Unknown OS platform`) ...

https://github.com/aspnet/AspNetCore.Docs/issues/16366

`Unable to find debuggable browser tab` instructions content always calls `GetLaunchEdgeInstructions` (i.e., on Linux), but `GetLaunchEdgeInstructions` throws for Linux at ...

https://github.com/aspnet/AspNetCore/blob/e72223eaf58a3ee6660a922064d2449e47b78253/src/Components/Blazor/Server/src/MonoDebugProxy/BlazorMonoDebugProxyAppBuilderExtensions.cs#L288

See the conditionals there ... `OSPlatform.Windows` and `OSPlatform.OSX`.

**Comment by Sm1le291** [comment]
if deal in CORS should be just temporary disable it? Someone tried?

**Comment by SteveSandersonMS** [comment]
Verified working on Ubuntu 19.10 with Chromium thanks to the fix in #18997
