### ISSUE TITLE
Remove mention of Mission Control in Helix.md

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#13060]
The /docs/Helix.md file in this repo mentions Mission Control and https://mc.dot.net URLs in a number of places. None of this is correct because the Helix infrastructure no longer relies on Mission Control. See dotnet/arcade#3578 for Arcade's similar cleanup.

/cc @MattGal

**Comment by jkotalik** [comment]
Is there any place where we can view entire test output logs other than Mission Control?

**Comment by dougbu** [comment]
> Is there any place where we can view entire test output logs like we had with Mission Control?

The URLs in the Helix build's console logs should work now that I got b9584d56d8b7 in. I haven't looked recently for a "don't show just failures" option but will later.
