### ISSUE TITLE
Building components without java installed causes build to hang indefinitely

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#13067]
Repro steps:
1. Try to build components without java installed.
2. Wait for build to finish.

Expected:
Either components doesn't need java or it fails with an error.
Actual:
Build hangs forever.

**Comment by mkArtakMSFT** [comment]
We can do this post code complete, so let's tackle this then.

**Comment by javiercn** [comment]
@jkotalik Can you provide more details?
* Did you call build.cmd at the root.
* Did you call build.cmd from the components folder?

Can you provide a dump/log of the hung process?

We have a flag to enforce prerequisites at build time that is disabled on the top level build.

I'm wondering if we should just provision Java at build time same as dotnet

**Comment by jkotalik** [comment]
> Did you call build.cmd from the components folder?

Build in the components folder.

> Can you provide a dump/log of the hung process?

Trying to repro now by deleting java off my path. Didn't repro :/. Will keep trying as I hit this twice before in a row and had to kill my VS instance.

**Comment by javiercn** [comment]
i tried to repro this without success. @jkotalik were you trying to build, run tests? Were you trying to specifically build components from VS?

**Comment by javiercn** [comment]
I'm assigning this back to you, if you repro it again and can give me repro steps I'll look into it again.

**Comment by mkArtakMSFT** [comment]
This should be already fixed.
