### ISSUE TITLE
Razor Component elements can't use arbitrary complex types in rendering

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#13062]
## Problem

I'm playing around with some Blazor stuff and my custom component has a property of type `System.Drawing.Color`:

```c#
 [Parameter] public Color BackColor { get; set; }
```

In the `RenderAttributes` part of the lifecycle I try to render it like this:

```c#
            builder.AddAttribute(2, nameof(BackColor), BackColor);
```

And then in `ApplyAttributes` I try to consume it like this:

```c#
                    case nameof(BackColor):
                        BackColor = (Color)attribute.AttributeValue;
                        break;
```

But, the call to `AddAttribute` doesn't do what I expected because it ends up calling `Color.ToString()`, which returns a non-round-trippable value like `"Color: [Red]"` or similar.

## Workaround

In my case the workaround wasn't too bad: I serialized the `Color` as an ARGB integer value, and then 'parsed' it back out by calling `Color.FromArgb()`. But in other cases it might not be as easy.

## Thoughts

It might be nice to use something like `TypeConverters` to convert to/from strings (which is entirely natural for TypeConverters), or perhaps even throw if it's an unknown type.

Ultimately the problem here is that for component systems that don't rely as much on actual rendered markup, requiring string-ifying all parameter values feels at odds with the natural expectations in such a system.

cc @rynowak @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Agreed. The stringification of attribute values should be an aspect of the web-specific renderers, not the Renderer base class.

**Comment by campersau** [comment]
See also https://github.com/aspnet/AspNetCore/issues/8493#issuecomment-499662342

**Comment by mkArtakMSFT** [comment]
Let's track this as part of the `Type converters` work referenced above.

**Comment by SteveSandersonMS** [comment]
If you don’t mind I’d like to keep this open, since we don’t really know we’d want to solve this with type converters. I suspect the solution may be different.

**Comment by Eilon** [comment]
Adding more info:

Indeed, TypeConverters are quite limiting, so while having support for them would be very helpful in many cases, it is likely insufficient. For example, imagine a component that accepts arbitrary user-defined objects, and then needs to pass that to its rendered element. It is not possible in the general case to serialize all arbitrary user-defined objects, yet there are cases where it is required.

Imagine this case:

```xml
<GridComponent DataSource="@myDataObject" ... />
```

The `myDataObject` variable might contain all kinds of non-serializable data, such as circular references.

Yet, when this _component_ renders, if its rendered _element_ expects an object (not a string), there's no general way to get the data over.

It would be nice to have some (perhaps new) API that allowed transferring arbitrary objects from components to elements.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
