### ISSUE TITLE
Attempt to gracefully close HTTP/2 connection with a GOAWAY if graceful timeout queue limit exceeded 

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#13097]
When a Kestrel HTTP/2 connection exceeds its internal limit of 100 (by default) HTTP/2 streams that have been closed by the server but not the client within the last 5 seconds, it should try to gracefully close the connection with a GOAWAY in order to allow existing streams to complete without accepting new streams on the connection.

See https://github.com/dotnet/corefx/issues/40051#issuecomment-520946585 for context.

**Comment by Tratcher** [comment]
This may temporarily unblock the client but it's going to make the server's memory situation worse. Not only do you add the latency and overhead of creating a new connection, but now you've potentially doubled the number of dead streams it needs to track. That old connection can only be cleaned up when all active requests end.

**Comment by Tratcher** [comment]
Put another way, 100 seems way too low to start taking measures like gracefully closing the connection. Connections are expensive and the client has done nothing wrong, in the example given the server terminated the stream without consuming the body.

As discussed on the other thread, Kestrel could be much more aggressive with its memory cleanup for dead streams. It tracks these streams for two reasons:
A) To be consistent about enforcing protocol correctness for things like receiving frames in the wrong order, etc.. It could opt to be more lax about these checks for dead streams, but probably shouldn't skip all of them, you wouldn't want to get spammed by frames for dead streams forever.
B) To allow the client time to react to the RST_STREAM, stop sending frames, and avoid a connection error for sending frames on a closed stream. This check doesn't require the whole stream structure, just the ID and a timeout.

**Comment by halter73** [comment]
I just don't see this as a very realistic scenario, and I don't think increasing the limit even by an order of magnitude changes the situation much. If an app ever runs into a situation where it RSTs over 100 streams on a single connection mid-request-body within 5 seconds, it's very likely to RST over 1000 streams or 10000 streams in that same time period. I don't think RSTing even over 10 streams mid-request-body within 5 seconds will be terribly common.

**Comment by JamesNK** [comment]
Server RSTs are realistic in gRPC. In a client streaming call it is perfectly valid to choose to complete without reading the request stream to completion.

gRPC clients making a call like this, a shared HttpClient (a single instance would come from HttpClientFactory) plus some load and you've got this bug.

**Comment by halter73** [comment]
If it is really common in gRPC scenarios for the server to RST a stream mid-request-body at a high rate, the much better and more-important fix is to have the clients explicitly close the stream on its end before opening new streams.

@Tratcher is right that the spec does not recommend this, but AFAIK it doesn't caution against it either. The client change seems like a better fix, because it sets no arbitrary upper bound on the rate of server-RSTd requests.

The changes that's been suggested so far on the server would only increase the RPS in the scenario by some factor or make the failure case a little more graceful, but you'd still be left with the same basic underlying issue.

The only way to not to have an arbitrary rate limit in this scenario is for the client to also close the stream. I get that other clients might also not explicitly close the stream after receiving an RST, but if that's the case, maybe we should reach out to the authors of the affected clients.

**Comment by JamesNK** [comment]
> the clients explicitly close the stream on its end before opening new streams

There are many gRPC client implementations (C++, Java, Go, Node, etc). We can't rely on them to do this.

**Comment by halter73** [comment]
Whether or not we can rely on the clients to do this, I don't see how increasing the limit does anything other than kick the can down the road. If we increase the limit to track up to 1,000 RST'd connections at a time instead of 100 and someone reports their gRPC client hit the increased limit, would we increase it to 10,000 connections? What if that limit is then hit? Would we increase it again? I don't know why 100 is insufficient.

**Comment by geoffkizer** [comment]
> the much better and more-important fix is to have the clients explicitly close the stream on its end before opening new streams.

As I mentioned on the corefx issue, this is specifically prohibited by the RFC. https://tools.ietf.org/html/rfc7540#section-5.4.2:

```
   To avoid looping, an endpoint MUST NOT send a RST_STREAM in response
   to a RST_STREAM frame.
```

**Comment by Tratcher** [comment]
> > the much better and more-important fix is to have the clients explicitly close the stream on its end before opening new streams.
> 
> As I mentioned on the corefx issue, this is specifically prohibited by the RFC. https://tools.ietf.org/html/rfc7540#section-5.4.2:
> 
> ```
>    To avoid looping, an endpoint MUST NOT send a RST_STREAM in response
>    to a RST_STREAM frame.
> ```

@geoffkizer this overlooks a possibility. We've discussed elsewhere that when the client receives a final status code and END of stream (before a RST, if any), it has a choice to either continue sending data (today's behavior) or to RST the stream itself. This wouldn't be a RST in response to a RST, it would be a RST in response to an END and would put the stream in a fully closed state on both client and server. The server may or may not send that final RST, or may wait until additional frames are received before sending a RST, but either way there's no reason to keep sending the request body when a RST can substitute.

**Comment by geoffkizer** [comment]
@Tratcher In that scenario -- client receives response end of stream before it has finished sending the request body -- we expect that the server will send RST_STREAM with NO_ERROR if it's not interested in the rest of the request body. This is what the RFC suggests. Previously, we didn't handle this correctly, but it was fixed with https://github.com/dotnet/corefx/pull/40112

I think you are suggesting that we could reset the stream ourselves if we receive response end of stream before we finish sending the request body. Am I understanding you correctly here?

I'm not sure what this would get us; it seems better to just wait for the RST_STREAM with NO_ERROR from the server. Servers (including Kestrel) do seem to send RST_STREAM with NO_ERROR if they are not interested in the rest of the request body. I'm not sure if there are cases where a server would send response end of stream and still expect the request body to continue sending, but it seems like there could be.

**Comment by Tratcher** [comment]
> I think you are suggesting that we could reset the stream ourselves if we receive response end of stream before we finish sending the request body. Am I understanding you correctly here?

Correct. Consider the example where the response is a 401 and the request will be retried with credentials. There's no point in continuing to send the request body, you're wasting resources. (I don't remember if you handle >= 4xx status codes differently at the moment).

> it seems better to just wait for the RST_STREAM with NO_ERROR from the server. 

A server may not send this until it receives additional data frames from the client. In the meantime you may have filled the connection full of useless data.

It's also is a clear signal from the client to server that the client will never send additional frames on this steam. That's useful for cleanup purposes.

> I'm not sure if there are cases where a server would send response end of stream and still expect the request body to continue sending, but it seems like there could be.

**Comment by geoffkizer** [comment]
> A server may not send this until it receives additional data frames from the client. In the meantime you may have filled the connection full of useless data.

It seems like a well-behaved server would either send this immediately after the end stream, or not at all -- the server doesn't want to receive useless data either.

> It's also is a clear signal from the client to server that the client will never send additional frames on this steam. That's useful for cleanup purposes.

Yes, I can see how it's useful for the server. It's unfortunate that HTTP2 doesn't have a better way of managing the cleanup here. QUIC seems to do better here with its STOP_SENDING/RESET_STREAM frames.

We can certainly consider adding behavior like this to HttpClient in the future.

**Comment by anurse** [comment]
Triage: We think we're OK with the timeout behavior here now and don't expect to make significant changes here.
