### ISSUE TITLE
Installing preview8 left preview7 runtimes and sdks installed

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#13126]
### Describe the bug
Following the ASP.NET blog post for Preview8 I first installed the .NetCore preview8 SDK and then updated Visual Studio to 16.3.0 Preview2. The Preview7 runtimes and SDKs are still installed and are no longer accessible from 'control panel/programs and features' for removal.

### To Reproduce
1. Install the preview8 ASP.Net SDK
2. Install the preview2 VS 2019 16.3.0
3. See the 'dotnet --info' output below

### Expected behavior
I'd expect that the installer for the SDK would have done the 'Upgrade in Place' as they have done since Preview3. If it isn't doing the upgrade in place I would have expected that entries in the 'programs and features' would still exist for manual removal.

### Additional context

C:\Solutions\OHI\LocalStorage>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\OHI\LocalStorage>

**Comment by mikes-gh** [comment]
I have the same issue. I uninstalled preview 7 manually.
I would also  add that when preview 8 is installed via vs 2019 preview 2 no add remove program entry is present.
Is this new behaviour?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MarkStega.
@livarcocc who owns the install experience?

**Comment by mikes-gh** [comment]
Additional info

I believe I installed preview 7 outside of vs installer.  Maybe its a case of what method was used to install preview 7?

Add/Remove Programs or vs installer.

**Comment by livarcocc** [comment]
If you installed the .NET Core SDK through both VS and the stand alone installer, you effectively have two channels. So, it is expected that you will have a P7 and a P8.

**Comment by MarkStega** [comment]
I just followed the instructions on the ASP.NET Core Preview 8 blog post which specifies installing the SDK and then installing the VS preview. Is VS2019 16.3P2 defaulting to install the old P7? This is a real mess with two separate installation scenarios/channels IMO. I guess is has been an issue with the 2.1 & 2.2 runtimes for a while, removing the entries in add/remove programs makes it worse.

**Comment by livarcocc** [comment]
16.3 P2 will bring with it .NET Core SDK preview8. We removed the entries from ARP because it led to lots of people removing the SDK(s) they needed to work with their VS. This way, VS can manage all that it needs. The scenario where folks just install VS, get an SDK and start working with Core is a lot more common than the one where are trying to control exactly what they want on the machine.

**Comment by mikes-gh** [comment]
OK so only the vs installer upgrades in place?
The installer form the dotnet site does not do in place upgrades?

**Comment by livarcocc** [comment]
They both do upgrades in place. But they don't interfere with each other.

**Comment by MarkStega** [comment]
Since I ran both installers how do we figure out which one didn't do an upgrade in place (leaving the P7 stuff in place).

**Comment by livarcocc** [comment]
@johnbeisner can you work with @MarkStega to get logs and take a look at why P7 is still around after upgrading VS to 16.3 P2 and running the p8 stand alone installer?

**Comment by livarcocc** [comment]
Also, this link contains more information regarding the changes we made to the installer: https://devblogs.microsoft.com/dotnet/improving-net-core-installation-in-visual-studio-and-on-windows/

**Comment by MarkStega** [comment]
@johnbeisner If you send me the locations and names of the relevant log files I can zip them up and send them to you.

**Comment by Pilchie** [comment]
@shirhatti - can we update the blog post to *NOT* say to install the SDK separately if folks are using VS?
