### ISSUE TITLE
Publish info about Kestrel's exposure to HTTP/2 vulnerabilities

### ISSUE THREAD

**Issue by johncrim** [dotnet/aspnetcore#13173]
These vulnerabilities have been recently published as VU#605641
https://kb.cert.org/vuls/id/605641/

Kestrel isn't listed on the vendor matrix, though IIS is. Please publish an announcement elaborating how Kestrel handles these attacks, and when fixes (if needed) will be available.

**Comment by blowdart** [comment]
https://github.com/aspnet/Announcements/issues/382

I had hoped not to have to do this, because we can never prove a negative, but here you go :)
