### ISSUE TITLE
SETTINGS_MAX_CONCURRENT_STREAMS and long running gRPC calls

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#13176]
Kestrel defaults SETTINGS_MAX_CONCURRENT_STREAMS to 100.

If I start 100 duplex streaming calls using a HttpClient, the 101st will block until one is closed:

```csharp
var calls = new List<AsyncDuplexStreamingCall<DataMessage, DataMessage>>();

for (int i = 1; i < 1000; i++)
{
    Logger.LogInformation($"ITERATION {i}");

    // The streaming call stays open forever
    var call = client.DuplexStreamingCall();

    // Blocks on 101st iteration
    await call.ResponseHeadersAsync.DefaultTimeout();

    calls.Add(call);
}
```

A HttpClient reuses the same connection, and sharing one HttpClient for many calls is not uncommon. The HttpClient could be created via HttpClientFactory and then reused for many streaming calls.

A solution to this is to increase [MaxStreamsPerConnection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#maximum-streams-per-connection). It is a simple change to make but it has some drawbacks:
1. Someone has to know to do it. They develop an app, it works fine in testing, then they deploy to production and encounter blocked calls. Now they have to investigate and redeploy.
2. Increasing the stream limit increase it for all HTTP/2 connections, not just gRPC calls.

Is there something we can do to make this a better experience?

Related corefx issue: https://github.com/dotnet/corefx/issues/40333

// @shirhatti @JunTaoLuo @Tratcher @halter73 @anurse

**Comment by halter73** [comment]
> Increasing the stream limit increase it for all HTTP/2 connections, not just gRPC calls.

If we find that 100 max concurrent streams per connection is too small of a default for gRPC, I think we should change the default for all HTTP/2 connections. After all, it's possible to use the same HTTP/2 connection for gRPC calls and normal requests, right?

**Comment by JamesNK** [comment]
Yeah gRPC is just regular HTTP/2, and gRPC and "regular" HTTP/2 requests could live on the same connection.

Many other servers default to 100 as the connection stream limit as well, but it doesn't fit well with how gRPC uses HTTP/2.

* With regular web HTTP/2 traffic 100 streams makes more sense because each stream is very fast. For example, a website with 200 images will start 100 requests, and wait for images to be finished before starting more.

* A gRPC server with 200 users on it wants to start 200 long running gRPC calls to another server. 100 users will be happy but the other 100 users will be permanently blocked.

**Comment by anurse** [comment]
We're good with what we've got here. Sounds like everyone else uses 100 as the default, so this is fine.
