### ISSUE TITLE
Ability to define bind-value:event conditionally

### ISSUE THREAD

**Issue by srowan** [dotnet/aspnetcore#13181]
There are cases where it is desirable to have @bind-value:event be a little more "dynamic".

One approach that does NOT work:

`<input type="text" @bind-value="@InputValue" @bind-value:event='@(UpdateOnInput ? "oninput" : "onchange")'/>`

This fails with the following error:  _InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': 'updateoninput ? "oninput" : "onchange' is not a valid attribute name.

We also can't use IF statements inside an element, so I don't see any way to conditionally set the bind event.   This leaves us with something like this which is undesirable as the number of parameters goes up, as you have to repeat large amounts of code:

```
@if (UpdateOnInput)
{
  <input type="text" @bind-value="@InputValue" @bind-value:event="oninput" />
}
else
{
  <input type="text" @bind-value="@InputValue" />
}
```

I'm sure someone else can identify other kinds of attribute modifiers which would benefit from being conditional.   

It makes sense that these can't be "bound" to (I assume it would be super awkward to switch from onchange to oninput after the client has already been rendered for example) but it would be nice if there was a way to set the initial value conditionally.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @srowan .
We will try to address this in the 3.1 release.

**Comment by rynowak** [comment]
Compiler change is in for this. Work remaining will be to add some functional tests

**Comment by mkArtakMSFT** [comment]
@rynowak should this be marked as `Done` ?

**Comment by mkArtakMSFT** [comment]
Reopening to not loose track of the remaining work.

**Comment by mkArtakMSFT** [comment]
Closing this as we won't get to this.
