### ISSUE TITLE
Add NoCache to ResponseCacheAttribute

### ISSUE THREAD

**Issue by jods4** [dotnet/aspnetcore#13189]
### Is your feature request related to a problem? Please describe.
I use `ResponseCacheAttribute(NoStore = true)` on my apis to prevent caching by front-end.
I also use `ValidateAntiForgeryTokenAttribute`, for obvious reasons.
The latter will always define the `Cache-Control: no-cache, no-store` response header, which is fine.
But if the header was already set and `no-cache` was not part of it, the anti-forgery token logs a warning.
On a busy system that's a lot of warnings for something that's "expected" so we need a good way to mute them.

### Describe the solution you'd like
I would be ok if `ResponseCacheAttribute` had a `NoCache` property as well.

That's not a big change and it would give the attribute additionnal flexibility.

It would fix the problem above because then I would do `ResponseCache(NoStore = true, NoCache = true)` and the anti-forgery middleware won't log warnings anymore.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jods4.
We will review this for the next 5.0 release and see what to do about it.

**Comment by pranavkm** [comment]
You should be able to control this using `ResponseCacheLocation.None`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.responsecachelocation?view=aspnetcore-3.1

**Comment by jods4** [comment]
@pranavkm Thanks for the tip, I assume you mean 
`[ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]`
would work fine with the antiforgery middleware.

I'll try and update this issue accordingly.
Unfortunately due to the current covid situation I probably won't be able to do so before 3 weeks, so please be bear with me.

**Comment by jods4** [comment]
It works fine indeed! Thanks.
