### ISSUE TITLE
[Blazor - ASP.NET Core] Resolve Namespace conflits in the BuildRenderTree with the "global::" keyword

### ISSUE THREAD

**Issue by MajdajkD** [dotnet/aspnetcore#13220]
Hi guys!
### Description:
I have an issue with the generated BuildRenderTree functions of my razor components.
The issue is the following: I have multiple namespaces containing the same segments (this naming convention is company policy (customer censored, this is a demo project, not a production one.)):
![imports](https://user-images.githubusercontent.com/10176488/63216585-8af22d80-c137-11e9-8176-edceff4eaeea.png)

I am using the default generated server-side template:
![layoutmarkup](https://user-images.githubusercontent.com/10176488/63216594-d6a4d700-c137-11e9-8d0e-34e584e66578.png)

I get the following error:
![error](https://user-images.githubusercontent.com/10176488/63216637-7a8e8280-c138-11e9-9e65-e8c5f21a0593.png)

### Possible fix:
The namespaces in the generated component code should use the "global::" contextual keyword (like the old designer files did).
The following temporary fix solves the problem until the next cleaning (build works fine, rebuild re-generates the wrong code):
![error](https://user-images.githubusercontent.com/10176488/63216695-8af32d00-c139-11e9-8e51-2e640f501a13.png)

### Edit: 
The #13090 enhancement could also provide a workaround.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
