### ISSUE TITLE
Update readme for SpaServices & NodeServices to clarify the components are obsolete

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#13223]
https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/NodeServices/README.md
https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/SpaServices/README.md

**Comment by menorless** [comment]
Can I use NodeServices to execute arbitrary .js module yet or all functionality are obsolete?

**Comment by pranavkm** [comment]
All yours @danroth27

**Comment by menorless** [comment]
1. I would like to implement the above mentioned functionality. I can use NodeServices or I have to use SpaServices.Extensions? 

2. by the way. If so(Use SpaServices.Extensions): 
Execute arbitrary code .js file is not supposted to be Spa module, so why put it in SpaServices.Extensions?

I don't understand yet.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by captainsafia** [comment]
Closing this issue since the code has been moved out of the repo.
