### ISSUE TITLE
Allowing us to invoke the overload of DisplayNameFor for a collection in Razor Pages

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/aspnetcore#13237]
In MVC, if `@model IEnumerable<Student>` is specified,  we can invoke `@Html.DisplayNameFor(x=>x.Name)`.

However, in Razor Pages, the default scaffolding template always uses 
`@Html.DisplayNameFor(x=>x.Students[0].Name)` and the bound property `Students` is of type `IList<Student>` rather than `IEnumerable<Student>`.

IMHO,  `@Html.DisplayNameFor(x=>x.Students[0].Name)` syntax does not promote something like "readability". Semantically, when `Students=null` then `Students[0].Name` should throw null exception error but magically it does not. 

## Requested feature

Allowing us to invoke the overload of `DisplayNameFor` for a collection in Razor Pages.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pstricks-fans.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by pranavkm** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
