### ISSUE TITLE
Blazor markup method generates invalid C# code with CS0103

### ISSUE THREAD

**Issue by pgrho** [dotnet/aspnetcore#13275]
### Describe the bug

Markup method defined in Blazor `@functions` directive generates code that depends on a parameter `RenderTreeBuilder builder` but it won't be added to the method automatically.

### To Reproduce
1. Using Blazor 3.0.0-preview8.19405.7
2. Define markup function in a `.razor` file (Copied from [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.0#functions))
```
@functions {
    private void RenderName(string name)
    {
        <p>Name: <strong>@name</strong></p>
    }
}
```
3. Blazor generates following method in `.razor.g.cs` and got `error CS0103`
```
private void RenderName(string name)
{
    builder.AddContent(0, "        ");
    builder.OpenElement(1, "p");
    builder.AddContent(2, "Name: ");
    builder.OpenElement(3, "strong");
    builder.AddContent(4, name);
    builder.CloseElement();
    builder.CloseElement();
    builder.AddMarkupContent(5, "\r\n");
}
```

### Expected behavior

The code generation will automatically define and pass `builder` parameter.

**Comment by pranavkm** [comment]
@pgrho thanks for the issue report. This is a bug and we don't have a good solution to resolving this in 3.0. We're going to work on improving this as part of our next release.

**Comment by sven5** [comment]
It seems the workaround for preview9 is still to manually add the `RenderTreeBuilder` parameter, now differently named `RenderTreeBuilder __builder`.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.

**Comment by Oblomoff** [comment]
Community is waiting. Update documents at least please.
