### ISSUE TITLE
External SVGs are not rendered

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#13280]
External SVGs are rendered into the DOM but are not visually rendered by the browser (Chrome, Edge Chromium in my case).
It appears this issue is due to the way how the DOM is updated in BrowserRenderer.ts.
This issue seems very similiar to this issue: https://github.com/aspnet/Blazor/issues/366
I did some research and it appears this is maybe the reason:
```typescript
let svgElem = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
let useElem = document.createElementNS('http://www.w3.org/2000/svg', 'use');

// This
useElem.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', 'circle.svg#icon');
// or this
useElem.setAttributeNS('http://www.w3.org/1999/xlink', href', 'circle.svg#icon);
// seems to be missing in BrowserRenderer.ts
```

### To Reproduce
1. Create a Blazor application
2. Create a file named `circle.svg` within `wwwroot` Folder with this content:
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
    <symbol id="icon" fill="currentColor" viewBox="0 0 100 100">
        <ellipse cx="200" cy="80" rx="100" ry="50" style="fill:yellow;stroke:purple;stroke-width:2"/>
    </symbol>
</svg>
```
3. Paste the following SVG / HTML snippet into the Index page
```html
<svg>
    <use href="circle.svg#icon"></use>
 </svg>
```
### Expected behavior
The browser treats this as normal html with external svg and renders it properly

### Actual Behavior
The browser does not display the svg.

**Comment by MarkusRodler** [comment]
I coincidentally discovered a workaround for this problem. If you add an eventhandler to the svg, then it will be rendered correctly. For example with a dummy one:
```razor
<svg @onclick="@(() => {})">
    <use href="circle.svg#icon"></use>
</svg>
```

It is really only a workaround, but maybe it is useful for someone else. (And I hope the issue will be fixed soon 🙏)

**Comment by christallire** [comment]
I having same problem too. adding event handler works as a workaround.
Thanks @MarkusRodler

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @MarkusRodler.

I've been looking into SVG issues in general, of which not supporting external SVGs is a big one. For now, I'll ref this issue into #18271 as we'd like to tackle all the SVG-related issues in one go.

**Comment by mkArtakMSFT** [comment]
Closing as we will be tackling this as part of https://github.com/dotnet/aspnetcore/issues/18271
