### ISSUE TITLE
Re-enable F# tests when we have a 5.0 compatible F# SDK

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#13303]
Extensions:
* [ ] Microsoft.Extensions.Configuration.UserSecrets.MsBuildTargetTest.GeneratesAssemblyAttributeFile

RazorSDK:
* [ ] Build_SimpleMvcFSharp_NoopsWithoutFailing
* [ ] Publish_SimpleMvcFSharp_NoopsWithoutFailing
* [ ] Build_ProjectWithDependencyThatReferencesMvc_AddsAttributeToNonCSharpProjects

**Comment by javiercn** [comment]
@pranavkm reopen if necessary
