### ISSUE TITLE
Blazor browser developer tool extension, that removes the "Blazor comments" in "Elements" tab

### ISSUE THREAD

**Issue by egil** [dotnet/aspnetcore#13310]
To make it easier to _inspect_ and _debug_ rendered HTML from Razor components, it would be very nice, if _somebody_ would create a developer tool extension for Chrome/Edge/Firefox (I believe they are using the same extension model now, so one would work everywhere), that removes the annoying "Blazor comments" (`<!--!-->`) from the "Elements" tab.

![image](https://user-images.githubusercontent.com/105649/63417366-a63b9200-c3f0-11e9-900e-f3bc8c0b646f.png)

In the future, it could probably also be a place to put better support for debugging client-side Blazor.

**Comment by danroth27** [comment]
@egil Thanks for the suggestion! We hope to look at creating some sort of developer tools extension for Blazor in a future release.

**Comment by egil** [comment]
@danroth27 no problem. Just to be clear, I put _somebody_ in italic to maybe inspire somebody other than the core team to take up this issue, as I know you have other important issues with a higher priority.

**Comment by danroth27** [comment]
@egil Yup, understood. We probably won't get to this for a while, so if someone in the community wants to create a great Blazor browser dev tool extension, that would be awesome! Maybe someone has already started one?

**Comment by stsrki** [comment]
I already reported this issue with empty comments and that it would be great to remove them from generated html. I got the response that it's used to debug generated code. Can anyone explain what is the benefit of empty comments and why it's used to "debug"?

**Comment by egil** [comment]
> I already reported this issue with empty comments and that it would be great to remove them from generated html. I got this response:
> 
> > The comments are there for functional reasons. They let the renderer track the boundaries of components in a more efficient way than we could otherwise, and don’t really have any practical drawback that I know of.
> 
> Can anyone better explain the use case of empty comments?

I think the explanation you quote says it quite well. Put differently, they use them to faster update the rendered  HTML.

My goal is not to remove them from the rendered HTML as they serve a purpose. I simply want to hide them when we view the rendered HTML in the "Elements" tab in the dev tools.

**Comment by stsrki** [comment]
@egil Chrome has an option to hide comments from Elements section.

Open DevTools > Settings(F1) > and uncheck _Show HTML comments_

**Comment by egil** [comment]
> @egil Chrome has an option to hide comments from Elements section.
> 
> Open DevTools > Settings(F1) > and uncheck _Show HTML comments_

That is a good workaround for now. Thanks. I would still like to only have the razor comments removed with a dedicated extension/checkbox, at some point.

**Comment by mrpmorris** [comment]
They break script tags in Safari.

https://github.com/mrpmorris/blazor-fluxor/blob/master/src/Blazor.Fluxor/content/index.js#L4

**Comment by egil** [comment]
> They break script tags in Safari.
> 
> https://github.com/mrpmorris/blazor-fluxor/blob/master/src/Blazor.Fluxor/content/index.js#L4
@mrpmorris think that needs its own separate issue, it it doesn't already have one.

**Comment by TanayParikh** [comment]
Thanks, closing as dup of https://github.com/dotnet/razor-tooling/issues/4613.
