### ISSUE TITLE
Adding .Net Core reference (netstandard 2.0) breaks BlazorWASm project

### ISSUE THREAD

**Issue by kijoyin** [dotnet/aspnetcore#13365]
### Describe the bug
When a reference to a .netcore class library is added to the Blazor client porject I am getting an error saying the the referenced dll cannot be found in browser console.

WASM: System.TypeLoadException: Could not load type of field 'REST.Manangement.V2.UI.Pages.Environments.AddEnv:exampleModel' (0) due to: Could not load file or assembly 'REST.Management.V2.Resources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### To Reproduce
1. Create a Blazor Client (blazorwasm) project using .Netcore 3 (make sure taget framwrok is TargetFramework>netstandard2.0</TargetFramework>)
2. Create a .Netcore 3 class library project (make sure taget framwrok is TargetFramework>netstandard2.0</TargetFramework>)
3. Add a simple poco object in the class library project
4. Add a reference in blazor project to the class library and use the poco object
5. Run the Blazor client porject and you will get a WASM error

Failed to load resource: the server responded with a status of 404 (Not Found)
blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: System.TypeLoadException: Could not load type of field 'REST.Manangement.V2.UI.Pages.Environments.AddEnv:exampleModel' (0) due to: Could not load file or assembly 'REST.Management.V2.Resources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) <0x1a17ff8 + 0x00008> in <2633e9d520a54c07bbb230e18fb56239>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.RuntimeType.IsAssignableFrom (System.Type c) <0x1a17d78 + 0x0005a> in <2633e9d520a54c07bbb230e18fb56239>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RouteTableFactory+<>c.<Create>b__2_0 (System.Type t) <0x1fdc690 + 0x0000c> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at (wrapper delegate-invoke) System.Func`2[System.Type,System.Boolean].invoke_TResult_T(System.Type)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Linq.Enumerable+WhereArrayIterator`1[TSource].MoveNext () <0x1fdc5c8 + 0x00064> in <af905e9224bc421eab37e6eaa56c7e23>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RouteTableFactory.Create (System.Collections.Generic.IEnumerable`1[T] componentTypes) <0x1fdc060 + 0x00092> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RouteTableFactory.Create (System.Reflection.Assembly appAssembly) <0x1fbdb78 + 0x0005e> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync (Microsoft.AspNetCore.Components.ParameterView parameters) <0x1fc55d8 + 0x00020> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters (Microsoft.AspNetCore.Components.ParameterView parameters) <0x1f2b4d8 + 0x000ae> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1f48a28 + 0x00082> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 frameIndex) <0x1f48830 + 0x00082> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 newFrameIndex) <0x1f484e0 + 0x000d8> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange (Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder+DiffContext& diffContext, System.Int32 oldStartIndex, System.Int32 oldEndIndexExcl, System.Int32 newStartIndex, System.Int32 newEndIndexExcl) <0x1f478c0 + 0x004c8> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff (Microsoft.AspNetCore.Components.Rendering.Renderer renderer, Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, System.Int32 componentId, Microsoft.AspNetCore.Components.RenderTree.ArrayRange`1[T] oldTree, Microsoft.AspNetCore.Components.RenderTree.ArrayRange`1[T] newTree) <0x1f46de0 + 0x0009e> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x1f3c3b8 + 0x00162> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Components.Rendering.RenderQueueEntry renderQueueEntry) <0x1f3bfe0 + 0x0004e> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue () <0x1f3b7f0 + 0x00056> in <100f02d5db4143bd88f7ce610be59116>:0 
d.printErr @ blazor.webassembly.js:1

### Expected behavior
Balzor UI should have loaded.

**Comment by kijoyin** [comment]
Sorry I am not familiar with the tags here but are you expecting more details from me ? Happy to provide if specific information is needed

**Comment by kijoyin** [comment]
Hi @danroth27 ,

I think my blazor-wasm project template is outdated (no idea how to get it to the latest version as I have followed all the steps in -https://docs.microsoft.com/en-gb/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio). I still can't see the blazor project template in Visual studio, so I am creating in using dontnet new . My VS preview is slightly outdates 16.2.0 Preview 3 and it is work environment , so has to jump a few hops to get it to the latest.

Only personnel PC I have the latest and greatest of all and it all seems to work fine and so I am happy to manually updated the project that is not working to look like the one that is working.

**CSPROJ for not working**
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>7.3</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview8.19405.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0-preview8.19405.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview8.19405.7" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\bugtest.vm\bugtest.vm.csproj" />
  </ItemGroup>

</Project>

**CSPROJ for working**

**Feel free to close this bug as I can confirm it is working with all the latest and greatest.**

**Comment by kijoyin** [comment]
@danroth27  - Actually this is still an issue but an interesting one. This error only happens if the referenced library is named <something>.**Resources** . Looks like it is the resources in the name that is causing the issue .

Check out this https://github.com/kijoyin/BlazorError where I have checked in the code that is broken . There is also a class library called "ClassLibrary1.ViewModels" which is exactly same as the "ClassLibrary1.Resources" and if we switch the reference it all works fine (this is why I could never replicate this earlier as I didn't bother naming the my test projects previously)

**Comment by danroth27** [comment]
@kijoyin OK, thanks for letting us know! We'll take a look.

**Comment by javiercn** [comment]
I've investigated this issue a bit, I believe this is a mono bug, as I see the dll being downloaded and added to the mono runtime.

![image](https://user-images.githubusercontent.com/6995051/72792890-95d15280-3bee-11ea-8823-09e78471a676.png)

Which corresponds with 
![image](https://user-images.githubusercontent.com/6995051/72792958-aeda0380-3bee-11ea-9769-821f8c04e8f8.png)

I believe the issue here is that mono doesn't like the .resources.dll as it think it might be a satellite assembly.

**Comment by javiercn** [comment]
This issue was moved to mono/mono#18522

**Comment by javiercn** [comment]
I've moved the issue to the mono repo
