### ISSUE TITLE
Rename SignalR "Ping" to Heartbeat

### ISSUE THREAD

**Issue by mikaelm12** [dotnet/aspnetcore#13393]
As per @blowdart's request. 
Ping is not actually accurate for what we have. What we're calling a ping is exactly what a heartbeat it. Wikipedia says `heartbeat is a periodic signal generated by hardware or software to indicate normal operation`

**Comment by mikaelm12** [comment]
Actually we can't do this. We thought we were safe because the APIs that configure the Ping interval don't actually use the word ping. The actual `PingMessage` type is public. We could obsolete it and introduce a new `HeartbeatMessage` though.

**Comment by BrennanConroy** [comment]
This doesn't add much value and adds lots of potential disruption. We could have done this a couple years ago, but now it isn't worth it.
