### ISSUE TITLE
HubConnectoin on close listener remove

### ISSUE THREAD

**Issue by mashahbazi** [dotnet/aspnetcore#13409]
### Is your feature request related to a problem? Please describe.
having persist connection

### Describe the solution you'd like
provide remove onClose listener

### Additional context
Hi
When I working with SignalR .Net (not core) (java client for android) the best practice for having persist connection was stopping hubConnection when state changed to reconnecting and start new hubConnection. 
Now in SignalR .Net core (java client for android) I use onClose listener and stop then start new hubConnection. Is better idea for having persist connection??
If not with this practice onClose trigger to many times so if you can provide some methods to remove onClose listener it help to user it better.

**Comment by mashahbazi** [comment]
> I've never heard of this.
I get this practice from WebSocket and use it in signalR and it help me to my connection more persist.Before it my connection wasn't reliable and it was on connection slow state and I lose my signals

I don't want my added listener for onClose on HubConnection that I stop trigger any more.yes I use bool for start ,checking connection state but this still cause some bugs for me. for example when I reset my server I have too many connection's. I add to many check and finally I can stop all connection except one but I want start just one siganlR. Removing onClose help me at this work

**Comment by mashahbazi** [comment]
> Are you adding an onClose handler during each reconnect? Do you have to do that if so?

yes I have to because I start new hub I must handle new hub on Close

**Comment by jdnichollsc** [comment]
It would better having the option to remove onclose listener, to avoid unnecessary events registered in memory, memory leaks, etc
What do you think folks?
