### ISSUE TITLE
Some files missing when debugging Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#13417]
When I debug a Blazor WebAssembly app using the latest preview9 build I see a view in the browser dev tools of the files in my project, but some of the files appear to be missing:

![image](https://user-images.githubusercontent.com/1874516/63642517-3558dc00-c675-11e9-830b-91c067fdf566.png)

Is there a reason why *Index.razor* or *App.Razor* don't show up?

**Comment by mkArtakMSFT** [comment]
Closing as this may not apply any more.

**Comment by danroth27** [comment]
It still applies. Here are the files that show up with our latest builds:

![image](https://user-images.githubusercontent.com/1874516/75700473-f8465580-5c66-11ea-9b2b-a294b5d0bc9d.png)

**Comment by danroth27** [comment]
This issue was moved to mono/mono#19099
