### ISSUE TITLE
Client-Side Blazor: Automatically download assemblies to browser

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#13416]
### Is your feature request related to a problem? Please describe.

When developing client-side Blazor applications you may want to have an architecture where not all assemblies are statically linked to your main Blazor application. You may want to have numerous independent component projects that are compiled into their own assemblies and loaded dynamically at startup.

One would assume that as long as the assemblies exist in the _framework/_bin/ folder then Blazor will download them automatically to the browser. However this is currently not the case. Instead Blazor only downloads the main application assembly and any statically linked dependencies - it ignores any other assemblies. The workaround to this problem is that you must handle it explicitly in your main application by writing logic to download assemblies as byte arrays and load them:

// download assembly from server and load
var bytes = await http.GetByteArrayAsync("_framework/_bin/" + AssemblyName + ".dll");
Assembly.Load(bytes);

However this is problematic for a number of reasons. First, the behavior is not intuitive and the code is cumbersome to write manually. Second, since HttpClient is not available during startup, you have to execute this logic AFTER the application has started up, This means that you cannot dynamically register any services which may exist in these external assemblies in startup - which restricts the ability to use dependency injection. Third, you need to keep track of any dependencies your assemblies may have and download and load them manually as well. Fourth, there seems to be a bug related to linking to .NET Standard after these external assemblies are downloaded and loaded https://github.com/aspnet/AspNetCore/issues/13171

### Describe the solution you'd like

Blazor downloads and loads all assemblies which exist in the _framework/_bin/ folder automatically to the browser. 

### Additional context

Oqtane is an open source modular application framework which is currently trying to use the manual methods to accomplish the goals above - https://github.com/oqtane/oqtane.framework

**Comment by SteveSandersonMS** [comment]
> One would assume that as long as the assemblies exist in the _framework/_bin/ folder then Blazor will download them automatically to the browser. However this is currently not the case.

I understand that would seem intuitive. However, just to clarify why it's not what happens, fetching resources over the network *must* be done asynchronously. Browsers enforce this. So .NET's synchronous on-demand assembly loading feature that you know from desktop CoreCLR isn't applicable. Additionally it isn't normally desirable to have the UI hang for an indeterminate period anyway, even if we could freeze the browser until the loading was completed.

> Second, since HttpClient is not available during startup, you have to execute this logic AFTER the application has started up,

Good news - this limitation has been eliminated.

Overall it seems like the functionality being requested in this issue is the same as in #5465, so I think we should regard it as already tracked by that. Is that OK?

**Comment by sbwalker** [comment]
Thank you for looping back on this. Yes I think its fine to track this through #5465. To provide some additional context to my earlier points:

1. The behavior is not intuitive and the code is cumbersome to write manually. 
>> once you understand the behavior it actually is intuitive and the code is not that difficult to write. Plus Dan Roth recently showed me a simple way to determine which runtime you are running on, which allows for conditional logic to invoke the download of assemblies only when running on WebAssembly.

2. Since HttpClient is not available during startup, you have to execute this logic AFTER the application has started up, This means that you cannot dynamically register any services which may exist in these external assemblies in startup - which restricts the ability to use dependency injection. 
>> I was able to work around this in my app by including logic in my custom router to download assemblies to the browser. However it will be much better to have HttpClient available during startup - and it will solve my dependency injection issue. Can't wait to try it. 

3. You need to keep track of any dependencies your assemblies may have and download and load them manually as well. 
>> this is challenge but I am not sure if we should expect Blazor to provide a solution.

4. There seems to be a bug related to linking to .NET Standard after these external assemblies are downloaded and loaded
>> I was able to resolve this by turning off the Linker on my external assemblies ( thank you for this suggestion Steve ). Once I did this, they worked just fine when running on WebAssembly.

**Comment by Pilchie** [comment]
Closing resolved issue.
