### ISSUE TITLE
ASP.NET Core looks for index.html in wrong folder when using SSR

### ISSUE THREAD

**Issue by PieterjanDeClippel** [dotnet/aspnetcore#13433]
### Describe the bug
I created a new project and added server-side rendering.
When I enable production mode by setting the (Project properties - Debug - ASPNETCORE_ENVIRONMENT) environment variable = Production, the app won't build anymore.

`System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.`

It seems that when using SSR in production mode, ASP.NET Core looks for the angular browser build in the **ClientApp/dist** folder instead of the **ClientApp/dist/browser** folder. However in development mode it works fine.

### To Reproduce
1. Create a new ASP.NET Core Angular project.
2. Debug the project. The project works.
3. Switch to production mode. The project isn't working anymore.
4. Run `ng build --prod` or `npm run build`
5. Debug the project again. The project can find the angular app.
6. Setup SSR with following instructions (express-engine): https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa
    a. Remove the ClientApp
    b. Create a new app: `ng new ClientApp --style=scss --routing`
    c. Build the project: `ng build --prod`. I see that this creates **ClientApp/dist/ClientApp** instead of **ClientApp/dist**.
    d. Modify the call for AddSpaStaticFiles: `configuration.RootPath = "ClientApp/dist/ClientApp";`
    e. Add Express to the ClientApp: `ng add @nguniversal/express-engine --clientProject ClientApp`
    f. Add aspnet-prerendering: `npm install --save aspnet-prerendering`
    g. Add the SPA prerendering middleware (article).
    h. Add node to the types of tsconfig.app.json and tsconfig.server.json
    i. Modify main.ts and main.server.ts
    j. Remove the dist folder.
    k. Run `ng build --prod` and `npm run build:ssr`
    l. Run the project. The project isn't working
7. Notice ASP.NET Core throwing the above exception
8. Switch back to development mode. The project works fine.
9. Switch back to production mode. Copy over the files from ClientApp/dist/browser to ClientApp/dist (because that's where ASP.NET Core looks). The project works fine.

Repository: https://github.com/PieterjanDeClippel/AspNetCoreSSRIssue

### Expected behavior
Equal behavior in production mode as in development mode. In production mode ASP.NET Core should look for the angular app in **ClientApp/dist/browser**

### Additional context
Angular version: 8.1.1
Node version:11.7.0
NPM version: 6.10.1
.NET Core version: 2.2

**Comment by PieterjanDeClippel** [comment]
I think this is a minimal setup.
Without SSR it works fine in DEV as well in PROD.

With SSR the spa-prerenderer looks in
- DEV: **ClientApp/dist/browser**
- PROD: **ClientApp/dist**

Currently I just copy the files from dist/browser to dist when publishing a new version, and the problem is solved.
All steps noted in the thread are required to get SSR working, so there's no step to skip. It's as minimal as it can get. To see the issue in action:
- git clone  https://github.com/PieterjanDeClippel/AspNetCoreSSRIssue
- Run in Development mode. Wait for the dist/browser and dist/server folder to generate.
- Notice the working app. ASP.NET Core looks in ClientApp/dist/browser
- (Remove the ClientApp/dist folder)
- Run in Production mode. Wait for the dist-folders to regenerate.
- Notice the app failing to find index.html (Output window)
- Copy the files from dist/browser to dist
- Notice the working app.

**Comment by MintPlayer** [comment]
It appears that after adding `@nguniversal/express-engine` you can modify your angular.json file:
**projects:ClientApp:architect:build:options:outputPath** is set to dist/browser after running the ng add command. Changing this back to **dist** makes the SSR work for both development and production ASPNETCORE_ENVIRONMENT.
