### ISSUE TITLE
IdentityServer4 preconfigured client builder methods should return the client

### ISSUE THREAD

**Issue by tibitoth** [dotnet/aspnetcore#13435]
### Describe the bug
The `ClientCollection` class' `AddNativeApp`, `AddIdentityServerSPA` `AddSPA` methods do **not** return with the created `Client` object now. Becouse of this the extra configuration steps are not so comfortable eg.:

```
options.Clients.AddNativeApp("nativeapp", cfg =>
{
    var builder = cfg
        .WithScopes("openid", "profile", "myAPI")
        .WithRedirectUri("mycallback://callback");
});
options.Clients.Single(c => c.ClientId == "nativeapp").AllowOfflineAccess = true;
```

### Expected behavior
The `ClientCollection` class' `AddNativeApp`, `AddIdentityServerSPA` `AddSPA` method shpuld return with the created `Client` object.

### Additional context
ASP.NET Core 3.0 preview7
related: #13434

**Comment by rudiv** [comment]
+1 for this, having to pull out the client from the list feels a little wrong, although necessary to take additional configuration steps.

**Comment by HaoK** [comment]
Thanks again @tibitoth
