### ISSUE TITLE
Blazor doesn't render the value attribute if it is set to an empty string

### ISSUE THREAD

**Issue by fire-birdie** [dotnet/aspnetcore#13440]
Blazor doesn't render the `value` attribute of an `option` element if the value is an empty string. In other words, this:
```html
<option value="">Test Option</option>
```
becomes:
```html
<option>Test Option</option>
```
when rendered to the client. The result is that selecting the option will set the containing `select` element's value to the text of the option (i.e. `Test Option`) instead of the empty string.

The same markup, when used inside a `.cshtml` file, renders the `value` attribute to the client, allowing for an option that has an empty string as its value. I haven't found a way to do this from a `.razor` file short of running some Javascript code to set the attribute after the content is rendered.

### To Reproduce
1. Using v3.0.0-preview8 of ASP.NET Core, create a new Blazor application
2. Add the following to the `body` tag of `_Host.cshtml`:
```html
	<script>
		function fixOptionValue(option) {
			option.setAttribute('value', '');
		}
	</script>
```
3. Replace the contents of `Index.razor` with:
```razor
@page "/"
@inject IJSRuntime JsRuntime

<select @bind="selectedValue">
	<option selected hidden disabled>Select one</option>
	<option value="">Default behaviour</option>
	<option value="" @ref="EmptyOption" @ref:suppressField>Modified by script</option>
	<option>Option without value</option>
</select>

<div>
	Selected Value: @selectedValue
</div>

@code {
	private string selectedValue;
	private ElementReference EmptyOption;

	protected override async Task OnAfterRenderAsync(
		bool firstRender)
	{
		if (firstRender)
		{
			await this.JsRuntime.InvokeAsync<object>(
				"fixOptionValue",
				this.EmptyOption);
		}
	}
}
```
4. Run the app and switch between the options in the select element
5. Inspect the options in the browser's dev tools

### Expected behaviour
Expected the `Default behaviour` option to have `value=""`

**Comment by Matthewsre** [comment]
I have had to set the value to a specific value I chose to represent an empty string and translate it in the setter of the binded property.

Are there any better alternative approaches to get this to show up/work with an empty string or null?

**Comment by mikelyncheski** [comment]
For now, I created a simple method that creates the markup for the option:

	`{return $"<option value='{firstItem.Value}'>{HttpUtility.HtmlEncode(firstItem.Label)}</option>";`

I have a wrapper around each of our Input components so I only had to put this in one place.:

https://gist.github.com/mikelyncheski/7543d2d1f37aa1c27b735077a2efdc41

**Comment by chrisdpratt** [comment]
A less complicated workaround:

    @((MarkupString)"<option value=\"\">Select Something</option>")

No need for a whole component wrapper just to handle this.

**Comment by Radnen** [comment]
@chrisdpratt That example is not working on Blazor for .Net Core 3.1 the `value=""` just becomes `value`. The issue I have is that this affects form validation. Suppose you want to show a  `-- choose option --` prompt, but if they don't choose something, mark the field invalid. It's currently not possible to do this in Blazor without crafty workarounds.

**Comment by chrisdpratt** [comment]
`value=""` and `value` are functionally equivalent.

**Comment by Radnen** [comment]
Hmm, it seems to clear the prompt though. I just see a white box in the selector rather than the default `-- choose option --` prompt. Maybe a different issue with the fact I'm using integer values (which are non-nullable) and `value` by itself is treated as if it were _null_?

If I instead put `value="0"` I lose the `required` validation attribute, but the prompt works correctly. So, I'd need the `value` to mean null in the selector, so it can prevent form submission, but still correctly map to the `-- choose option --` text.

**Comment by SteveSandersonMS** [comment]
The original issue described here no longer repros in 3.1+, but the comments near the end refer to a different issue which is now fixed in https://github.com/dotnet/aspnetcore/pull/23221

**Comment by wangjunjx8868** [comment]
Good. Solved my problem
