### ISSUE TITLE
[Proposal] Visual configuartion and auto-generated classes for JSON 

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#13446]
I suggest to add two tools to ASP.NET Core:
# A Visual Configuration window
Most of code written in the startup class, can be auto generated throw a window that offers visual options. Even dependency injection can be done by a grid with one column showing interfaces in a dropdown list and another column showing corresponding types that implementing each interface in a dropdown list. These auto generated options can be added to a StartupBase class, which the Startup class inherits from and overrides its methods of course with calling the base methods.

# Auto generate JSON strong types:
Suppose I have this appsettings.json file in ASP.NET Core project:
```JSON
"AppSettings":{
  "First" : "Value 1",
  "Second" : "Value 2",
  "Car": {
      "NumberOfDoors" : 5,
      "RegistrationDate" : "2017-01-01T00:00:00.000Z",
      "Color" : "Black"
    }
}
```

To use these settings with strongly typing, I have to build these classes:
```C#
public class Car
{
    public int NumberOfDoors { get; set; }
    public DateTime RegistrationDate { get; set; }
    public string Color { get; set; }
}

public class AppSettings
{
    public string First { get; set; }
    public string Second { get; set; }
    public Car Car { get; set; }
}

```
then use the `services.Configure` method to make ASP.NET populate them with values.

I suggest to add a tool to ASP.NET to generate the classes and populate them, by defang a class with static read-only fields holding settings values. All these generated classes should be hidden from the solution, and updated when the json file changes.
This can be done by adding a context menu option in the for any selected JSON file in the solution explorer, say: "auto generate strongly typed classes". 
There are already many online sites that generate classes from JSON, but doesn't populate them with values. This is good, but still time consuming. Such a capability should be a VS built-in.

You can try http://json2csharp.com/  and https://app.quicktype.io/#l=cs&r=json2csharp , but enclose the entire JSON in `{}`

**Comment by VBAndCs** [comment]
@halter73
> I doubt we're going to create a wizard for generating a Startup class. ASP.NET Core is generally code first.

It is better to consider beginners and deferent developers preferences. I myself miss the LinQ to SQL O/R Designer, and hope it come back to EF Core.
The middleware can have a similar designer to add and arrange components by drag and drop.

**Comment by VBAndCs** [comment]
@shirhatti
It is a pleasant surprise, despite it is a strange way in a stage place!
This utility is less helpful in current state:
1. It is unlikely to look at a past command on the edit menu to notice a Paste special one!
2. To use it, one needs to open the json file, select and copy all its content, create a new class, and use the paste special command. In my suggestion, only one click is needed!
3. We need to repeat the same steps again and again every time we edit the json file! In my suggestion, VS will compare the last modified dates of the json and classes files, to auto regenerate the classes!

I hope you consider this.

**Comment by shirhatti** [comment]
I'd recommend creating a suggestion at https://developercommunity.visualstudio.com/content/idea/post.html

**Comment by VBAndCs** [comment]
@shirhatti  
I will, despite it's nearly useless. They close issues after tree months because there is not enough users interactions! This will have a chance if ASP.NET team asked for.

**Comment by VBAndCs** [comment]
I am still not using ASP.NET Core because of this complex configuration system. I hope you give us an easy alternative.
