### ISSUE TITLE
Websocket transport non functional in Xamarin

### ISSUE THREAD

**Issue by NVentimiglia** [dotnet/aspnetcore#13451]
### Describe the bug

- Websocket transport non-functional in Xamarin
- Deployed to / Tested against Ubuntu and Azure servers
- Unit tests pass, chrome websocket connects, but xamarin client fails

### To Reproduce

- Sample App
- https://github.com/NVentimiglia/XamarinFormsSignalRDotNetCore

### Expected behavior

SignalR supports WebSockets 

### Screenshots

- Video
- https://www.loom.com/share/6d0adc5740834d41ae903aba29b4b9df

### Additional context

A 'http' protocol connection works fine (long polling, I assume)

**Comment by NVentimiglia** [comment]
@BrennanConroy confirm I was testing against a live instance. I only put localhost in the repository as an example.

Just to reiterate. I think using the http protocol for xamarin android is a fine and works. I just felt it was confusing that the ws protocol did not work in android but worked in my dnc test project.

**Comment by davidfowl** [comment]
What's the error?
