### ISSUE TITLE
Consider setting DetailedErrors to be default in Development

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#13454]
The plan was to do this via `appSettings.Development.json` or `launchSettings.json`. This would avoid having to configure it via code. Blazor should benefit from this: https://github.com/aspnet/AspNetCore/issues/13400

**Comment by JunTaoLuo** [comment]
@pranavkm Is this something we need to consider implementing in 6.0. Also is this referring the to the `DetailedErrors` in hosting or components? https://github.com/dotnet/aspnetcore/blob/fd1f1c355984f76070d8e32c891e6bac0bd96fdf/src/Hosting/Hosting/src/Internal/WebHostOptions.cs#L58 https://github.com/dotnet/aspnetcore/blob/c74e9efd0e6ea5b4d6737d23b92042772a50a249/src/Components/Server/src/CircuitOptions.cs#L58 I've applied both labels but feel free to update it.

**Comment by pranavkm** [comment]
Nah, I think we can close this. Blazor does a jank thing already and we haven't; heard of anyone complain of it.
