### ISSUE TITLE
New resend email confirmation button missing in V4 Login page

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#13462]
Found this while writing CTI scaffolding/identity UI scenarios https://github.com/aspnet/AspNetCore/commit/555b506a97a188583df2872913cc40b59e563da6#diff-aa64cc98cdcd1cce5815c2cb27d9f45c updated the V3 login page but the resend email confirmation link on the login page is missing in V4.

This was something new we added as an improvement in 3.0 so this is not a regression.  Oddly enough, the version in Scaffolding is correct so if you scaffold the Login page, you do get the register confirmation link (albeit with styling issues (button vs link)).

cc @ajcvickers @blowdart

**Comment by HaoK** [comment]
@blowdart since this is a new feature, I guess this also should go to master/5.0?

**Comment by blowdart** [comment]
It's not a new feature, it's adding something missing in the non-scaffoled version

**Comment by HaoK** [comment]
I don't think a LTS 3.1 servicing release is the right time to introduce this UI change to the login page, its a fairly involved change and seems much safer to do in 5.0, since it touches several pages and introduces new pages as well.  Aka this will have an impact on scaffolding too :/

**Comment by HaoK** [comment]
here's the PR, its certainly not a trivial PR unfortunately https://github.com/aspnet/AspNetCore/pull/14118/files

**Comment by HaoK** [comment]
Plan is to remove the left over code (V3 login + scaffolding) in 3.1, and bring it back correctly in master(5.0)

**Comment by HaoK** [comment]
Lets use this bug to track making sure everything works properly for 5.0/master, and use https://github.com/aspnet/AspNetCore/issues/14659 to track removing all of it from 3.1

**Comment by HaoK** [comment]
UI changes are done, need to port changes to scaffolding before closing this issue

**Comment by HaoK** [comment]
Should be fixed as of https://github.com/aspnet/Scaffolding/pull/1243
