### ISSUE TITLE
I want to use power of LINQ but dont want to use EF, what should I do?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#13465]
Hi,

In dotnet (core) world there is no/maybe no way to convert/translate LINQ/expression tree to SQL query, the only solution is EF ([Working with Data in ASP.NET Core Apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps)) ([related SO question](https://stackoverflow.com/q/7731905/3367974))

What do you suggest?

Thank you!

**Comment by dehghani-mehdi** [comment]
> Why don't you want to use EF?

There is couple of reasons, for example I don't like its complexity and configs

> There are other ORMs 

Would you share the list of them? btw something like [linq2db](https://github.com/linq2db/linq2db) it's not good for me, if I want to use something like that, I would go with EF.

**Comment by ichensky** [comment]
>> Would you share the list of them?

https://github.com/search?q=.net+core+orm

**Comment by RemiBou** [comment]
Nhibernate does that (https://nhibernate.info/doc/nhibernate-reference/querylinq.html)

**Comment by dehghani-mehdi** [comment]
@RemiBou If I want to use such an ORM, I'll go with EF. I'm looking for just translator with minimal/zero config. for example [SQLite.cs](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs).
