### ISSUE TITLE
Add or improve docs for lifecycle methods

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#13473]
We should improve the docs to answer questions like: https://github.com/aspnet/AspNetCore/issues/13469

We get lots of these kinds of questions, we should make sure the docs are in a good state, and then link to the appropriate section and close issues.

**Comment by andoband** [comment]
Maybe add a flow diagram kinda like Vue doc's: https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram

**Comment by mkArtakMSFT** [comment]
This is done already.
