### ISSUE TITLE
Add perf and reliability benchmarks for Blazor

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#13483]
From #10449: 

## Scenarios

Run these in our perf lab.

### Performance

Run Blazing Pizza on the VM, and spin up enough clients to saturate the CPU or thrash the memory. Figure out which resource is the most scarce, and then optimize, and repeat.

I propose we automate a canonical scenario like placing a pizza order - then measure *render operations per-second* for that fixed test script. 

- [x] Create a checked in automated performance test in our perf lab that reports *render operations per-second*.
- [x] Analyze results and log issues for improvement for some time-boxed amount of time. As with all perf work this is open ended so the size of this item is flexible.

### Capacity and Reliability

Run Blazing Pizza on the VM, and spin up a bunch of clients, but have them run the test script **slowly** (with pauses), let's say one operation per-second. The goal is to simulate a bunch of users in actual use of the web site to try and get a realistic estimate of a user count, and what kinds of resources your run out of first.

- [ ] Create a checked in automated reliability test in our perf lab than can run for a long period of time. The number of client used for this should put the server at 75% capacity.
- [ ] Analyze results for memory growth and reliability issues. The bar for this category is stricter, we need to address all issues that cause memory growth or reliability problems.

**Comment by mitchlabrador** [comment]
@pmkArtakMSFT any results you can share?

**Comment by adwilliamjr** [comment]
same question, any results you can share.. before me diving in on blazor

**Comment by rpskelton2** [comment]
It looks like this issue stated with #13483 where Dan outlined some ideas on test clients/frameworks.  Will there still be a framework that the general public can use to perf test their own code or was that idea given up in in lieu of a hard coded pizza test?

**Comment by Pilchie** [comment]
Clearing milestone for re-triage
