### ISSUE TITLE
Blazor Client-Side: Unable to create a SignalR connection in a C# Service

### ISSUE THREAD

**Issue by Z3roCoder** [dotnet/aspnetcore#13503]
### Describe the bug
I have set up a hosted Blazor Client-Side Application and have added a SignalR-Connection to my Server (Calling endpoints.MapHub<MyHub>("/somePath").

Now I tried to connect to this SignalR-Hub in a C#-Service in ClientSide-Blazor - However, this does not work as expected - I am receiving some strange Exception upon trying to call StartAsync on the HubConnection:
```
Could not resolve type with token 0100003f from typeref (expected class 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' in assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=abd9793829ddae60')
```

However, when trying to connect to the same hub through JavaScript, it works (as expected) flawlessly, so it's not a problem of my Hub or Server...

### Expected behavior
The Connection should be able to be established without error

### Screenshots
I attached some Screenshots with more Information.
![2019-08-28_10h25_07](https://user-images.githubusercontent.com/10726046/63839497-b539bb80-c97f-11e9-9dea-466afbc34f7f.png)
![2019-08-28_10h25_43](https://user-images.githubusercontent.com/10726046/63839444-99ceb080-c97f-11e9-9c41-782323719d01.png)
![2019-08-28_10h26_11](https://user-images.githubusercontent.com/10726046/63839466-a521dc00-c97f-11e9-85ec-ac2fb79bc8e8.png)

The "StartIfNeededAsync"-Method is called on a Razor Page after a Buttonclick:
```
@inject SignalRService signalr
.....
<button @onclick="start">Test start</button>
...
protected async Task start()
    {
        await signalr.StartIfNeededAsync();
    }
```

### Additional context
Include the output of `dotnet --info`

.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Z3roCoder** [comment]
Thanks for your reply,

I'm wondering - How expensive is the C#/JS Interop actually?

And is it planned that Client Side Blazor will support the SignalR Client in the future?

My goal actually was to achieve a constant data streaming from the server to the Client - As a sort of Log-Streaming, and I thought SignalR would be the way to go here.

**Comment by mkArtakMSFT** [comment]
We'll be using this issue to track the work necessary to support SignalR client on Blazor Client-side. So yes, we expect that this will work at some point.

**Comment by Z3roCoder** [comment]
Alright - Thank you for your fast response! I'll be looking forward to see this work!

**Comment by ChristianWeyer** [comment]
Hi @mkArtakMSFT - do you have any detailed explanation of why the SignalR .NET Core client is not compatible to be used with Client-side Blazor?
Thanks!

**Comment by SteveSandersonMS** [comment]
@ChristianWeyer It's because .NET's built-in websockets APIs are built on underlying TCP networking APIs that can't ever work in the browser, since JavaScript doesn't expose raw TCP networking capabilities. This naturally leads to a runtime failure from somewhere low in the stack. What we have to do to make it work is provide a browser-compatible implementation of the relevant low-level websocket APIs that are implemented by calling the JavaScript websocket APIs.

As it happens, this work has already been done. We just haven't integrated it yet. Once it is integrated, my expectation is that the SignalR client should just start working.

**Comment by ChristianWeyer** [comment]
Thanks for the update @SteveSandersonMS - great!

**Comment by mkArtakMSFT** [comment]
@anurse is there a separate issue tracking this? Or should this one be used to track this work?

**Comment by anurse** [comment]
I'm fine to use this issue. We should make sure it's in `area-signalr` so we see it in triage though ;). Happy to have it in both areas though.

**Comment by RedWingBB** [comment]
Is this work expected to release in core 3.2?

Consider cases where a webapi is already written using the full framework.
Is it expected that a .net core client will be able to connect to an asp.net/full framework hub?

**Comment by SteveSandersonMS** [comment]
Yes, it will work in the 3.2 release. We have a plan for making it work.

**Comment by BrennanConroy** [comment]
> Is it expected that a .net core client will be able to connect to an asp.net/full framework hub?

No, ASP.NET SignalR is not compatible with ASP.NET Core SignalR.

**Comment by anurse** [comment]
@SteveSandersonMS @BrennanConroy anything remaining here? SignalR should be working for Blazor WASM apps (with some other bugs that are otherwise tracked).

**Comment by BrennanConroy** [comment]
I think this can be closed

**Comment by anurse** [comment]
I'll close it then! If anyone is seeing this kind of issue using SignalR Client on Blazor WASM, feel free to open a new issue!

**Comment by Z3roCoder** [comment]
Awesome to see this resolved now!
Only wanting to ask - What package would I need to have Blazor WASM communicate via SignalR now, without using a JavaScript library like I ended up doing?
Could someone write up a few little Steps of how to go about it with the changes now? Thank you!

**Comment by brikken** [comment]
@Z3roCoder I assume you should simply use the .NET client, as described in the SignalR docs

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio
