### ISSUE TITLE
Problems with console

### ISSUE THREAD

**Issue by philburns-72** [dotnet/aspnetcore#13509]
I'm working through [this](aspnetcore/security/authentication/social/microsoft-logins.md), but when I get to the part "Store the Microsoft client ID and client secret" I have a problem.
I have a cmd prompt open at the folder where the .csproj file lives, but the command dotnet user-secrets set Authentication:Microsoft:ClientId <Client-Id> fails with the message 'Could not load the MSBuild project...'
Does that mean I'm not actually in the right directory, or something more serious has gone wrong?

**Comment by philburns-72** [comment]
Hi, I'm still stuck with this - can anyone help?
Trying to authenticate O365 users on my web app, have followed the instructions on "Microsoft Account external login setup with ASP.NET Core" but I can't get past this point:
<C:\AZURE Live\HCPTAzure2020>dotnet user-secrets set Authentication:Microsoft:ClientID "dea3e5cd-be3f-4f46-b9f2-cf1fab76c3cb"
Could not load the MSBuild project 'C:\AZURE Live\HCPTAzure2020\HCPTAzure2020.csproj'.>
Any ideas? Anyone?

**Comment by philburns-72** [comment]
[code]Microsoft Account external login setup with ASP.NET Core[/code]

**Comment by philburns-72** [comment]
Hi, I'm still stuck with this - can anyone help?
 Trying to authenticate O365 users on my web app, have followed the instructions on "Microsoft Account external login setup with ASP.NET Core" but I can't get past this point:
 < C:\AZURE Live\folder>dotnet user-secrets set Authentication:Microsoft:ClientID "88888888-8888-8888-8888-888888888888"
 Could not load the MSBuild project 'C:\AZURE Live\folder\projectname.csproj'. >
 Any ideas? Anyone?

**Comment by Rick-Anderson** [comment]
This is a doc issue. Recommend closing. 
cc @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
