### ISSUE TITLE
Razor NavMenu throws ArgumentException when try to Invoke StateHasChanged

### ISSUE THREAD

**Issue by maxreb** [dotnet/aspnetcore#13568]
Created the default Razor Components Template with Visual Studio Preview 16.3 and .net Core preview 8. Edited the `NavBar.razor` component to show the user the state of a service. When the state has changed I try to Invoke the `StateHasChanged` method. But when I try to do so I get the following exception:

> Exception thrown: 'System.ArgumentException' in Microsoft.AspNetCore.Components.dll
> The renderer does not have a component with ID 5.

The code:

```
<div class="top-row pl-4 navbar navbar-dark">
	<a class="navbar-brand" href="">Workbench @(mqttConnected ? "On" : "Off") </a>
	<button class="navbar-toggler" @onclick="ToggleNavMenu">
		<span class="navbar-toggler-icon"></span>
	</button>
</div>

<div class="@NavMenuCssClass" @onclick="ToggleNavMenu">
	<ul class="nav flex-column">
		<li class="nav-item px-3">
			<NavLink class="nav-link" href="" Match="NavLinkMatch.All">
				<span class="oi oi-home" aria-hidden="true"></span> Home
			</NavLink>
		</li>
		<li class="nav-item px-3">
			<NavLink class="nav-link" href="counter">
				<span class="oi oi-plus" aria-hidden="true"></span> Counter
			</NavLink>
		</li>
		<li class="nav-item px-3">
			<NavLink class="nav-link" href="fetchdata">
				<span class="oi oi-list-rich" aria-hidden="true"></span> Fetch data
			</NavLink>
		</li>
	</ul>
</div>

@code {
	bool collapseNavMenu = true;
	string NavMenuCssClass => collapseNavMenu ? "collapse" : null;
	bool mqttConnected;



	protected override void OnInitialized()
	{
		base.OnInitialized();//don't know if needed?
							 //ugly implementation due to VS syntax error when trying to use FactoryStart
		new Task(async () =>
		{
			await Task.Delay(2000);

//			try { //if we activate the try/catch block, everything works like it should
				mqttConnected = true;
				await this.InvokeAsync(() => this.StateHasChanged()); //here throws the exception
//			}catch
//			{
				// do nothing
//			}

		}).Start();
	}

	void ToggleNavMenu()
	{
		collapseNavMenu = !collapseNavMenu;
	}
}

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @maxreb.
Can you also share the call stack from the exception you're getting?

**Comment by mkArtakMSFT** [comment]
We'll also try to cover the guidance here: https://github.com/aspnet/AspNetCore/issues/13584

**Comment by maxreb** [comment]
sure thing, the call stack is posted down below.

Interesting fact: If I just put an empty `try/catch` block around the `InvokeAsync/StateHasChanged ` methods everything works like it should.

> System.ArgumentException
>   HResult=0x80070057
>   Message=The renderer does not have a component with ID 3.
>   Source=Microsoft.AspNetCore.Components
>   StackTrace:
>    at Microsoft.AspNetCore.Components.Rendering.Renderer.GetRequiredComponentState(Int32 componentId) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 392
>    at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 569
>    at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 409
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
>    at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception) in /_/src/Components/Components/src/Rendering/HtmlRenderer.cs:line 77
>    at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 422
>    at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 356
>    at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in /_/src/Components/Components/src/ComponentBase.cs:line 112
>    at BlazorApp1.Shared.NavMenu.<OnInitialized>b__5_1() in c:\temp\BlazorApp1\Shared\NavMenu.razor:line 44
>    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state) in /_/src/Components/Components/src/Rendering/RendererSynchronizationContext.cs:line 49
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 162
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 107
>    at BlazorApp1.Shared.NavMenu.<<OnInitialized>b__5_0>d.MoveNext() in c:\temp\BlazorApp1\Shared\NavMenu.razor:line 44
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 1954
>    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 808
>    at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 335
>    at System.Threading.QueueUserWorkItemCallback.Execute() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 824
>    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 684
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /_/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
>

**Comment by mkArtakMSFT** [comment]
Closing as we will be documenting the guidance per the above comment.
