### ISSUE TITLE
IdentityUser Email field is not encrypted even though it is marked with the ProtectedPersonalData attribute

### ISSUE THREAD

**Issue by nauticalcoder** [dotnet/aspnetcore#13562]
1. Using this version of ASP.NET Core 2.1
2. Here is my User model:

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using Microsoft.AspNetCore.Identity;

namespace Test.Entities

{
    public class User : IdentityUser<int>
    {
        [ProtectedPersonalData]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? LastLoginTime { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [DefaultValue(false)]
        public bool IsDeleted { get; set; }
        public DateTime? DeletedDate { get; set; }
    }
}

```

- Implement IPersonalDataProtector.
- Call  `UserManager.CreateAsync(user);`
3. Check the `AspNetUsers` table.  The `UserName` field will be encrypted but the `Email` field is not.  

### Expected behavior
I expect that any field marked with [ProtectedPersonalData] will be encrypted in the database.  I have also added the `FirstName` and it is being encrypted as expected.

**Comment by blowdart** [comment]
@HaoK any idea why this wouldn't kick in?

**Comment by HaoK** [comment]
It should I can take a look

**Comment by HaoK** [comment]
Things look like they are working as expected, I went with just a very basic reverse encryptor and just modified a new individual auth template like so:

```
            services.AddDefaultIdentity<IdentityUser>(options =>
            {
                options.Stores.ProtectPersonalData = true;
            })
                .AddEntityFrameworkStores<ApplicationDbContext>();
            services.AddTransient<ILookupProtector, Lookup>();
            services.AddTransient<ILookupProtectorKeyRing, KeyRing>();
            services.AddTransient<IPersonalDataProtector, Protector>();

    public class Lookup : ILookupProtector
    {
        public string Protect(string keyId, string data)
        {
            return new string(data?.Reverse().ToArray());
        }

        public string Unprotect(string keyId, string data)
        {
            return new string(data?.Reverse().ToArray());
        }
    }

    public class Protector : IPersonalDataProtector
    {
        public string Protect(string data)
        {
            return new string(data?.Reverse().ToArray());
        }

        public string Unprotect(string data)
        {
            return new string(data?.Reverse().ToArray());
        }
    }

    public class KeyRing : ILookupProtectorKeyRing
    {
        public string this[string keyId] => "key";

        public string CurrentKeyId => "key";

        public IEnumerable<string> GetAllKeyIds()
        {
            return new string[] { "key" };
        }
    }

```

**Comment by nauticalcoder** [comment]
I assume this test was with 2.1?  I'm a little perplexed as to why the Email field is the only one not getting encrypted.  I didn't not this above but the Username, NormalizedUserName, and NormalizedEmail are all getting encrypted as expected.  Any suggestions on what to look at next to see why the Email field is being excluded?

**Comment by HaoK** [comment]
No this was with 3.0 preview 8 but this code hasn't changed at all since 2.1, if you want to share a complete repro it might be easier to diagnose where the issue is.  Did you replace all 3 protector services?

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
