### ISSUE TITLE
SessionMiddleware Catch  System.OperationCanceledException

### ISSUE THREAD

**Issue by lianggx** [dotnet/aspnetcore#13574]
# Hi, All !
I have same quetions from below code.

```C#
public async Task Invoke(HttpContext context)
        {
            var isNewSessionKey = false;
            Func<bool> tryEstablishSession = ReturnTrue;
            var cookieValue = context.Request.Cookies[_options.Cookie.Name];
            var sessionKey = CookieProtection.Unprotect(_dataProtector, cookieValue, _logger);
            if (string.IsNullOrWhiteSpace(sessionKey) || sessionKey.Length != SessionKeyLength)
            {
                // No valid cookie, new session.
                var guidBytes = new byte[16];
                CryptoRandom.GetBytes(guidBytes);
                sessionKey = new Guid(guidBytes).ToString();
                cookieValue = CookieProtection.Protect(_dataProtector, sessionKey);
                var establisher = new SessionEstablisher(context, cookieValue, _options);
                tryEstablishSession = establisher.TryEstablishSession;
                isNewSessionKey = true;
            }

            var feature = new SessionFeature();
            feature.Session = _sessionStore.Create(sessionKey, _options.IdleTimeout, _options.IOTimeout, tryEstablishSession, isNewSessionKey);
            context.Features.Set<ISessionFeature>(feature);

            try
            {
                await _next(context);
            }
            finally
            {
                context.Features.Set<ISessionFeature>(null);

                if (feature.Session != null)
                {
                    try
                    {
                        await feature.Session.CommitAsync(context.RequestAborted);
                    }
                    catch (OperationCanceledException)
                    {
                        _logger.SessionCommitCanceled();
                    }
                    catch (Exception ex)
                    {
                        _logger.ErrorClosingTheSession(ex);
                    }
                }
            }
        }

```
# same error info

fail: Microsoft.AspNetCore.Session.SessionMiddleware[1]
      Error closing the session.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

# Q1:
The Error Message "Error closing the session." from  

** _logger.ErrorClosingTheSession(ex);**

But the exception type is OperationCanceledException, Why  Exception catch it else OperationCanceledException.

# Q2:
I thinking filter from the System.OperationCanceledException, becase the exception is OperationCanceledException when browser cancels the request, actually it's not the host fault, How can i catch it or filte it.

Thank yours reply.

**Comment by Tratcher** [comment]
Are you using an older version? `catch (OperationCanceledException)` was added later. (e.g. [1.1](https://github.com/aspnet/Session/blob/2ba243975e7c0208d9d441bf64b96634e9603fc1/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L114-L121) didn't have it.)

Note the use of the RequestAborted cancellation token has been removed from here in 3.0:
https://github.com/aspnet/AspNetCore/blob/725fa34cc801017294a805a6c0929992456de42a/src/Middleware/Session/src/SessionMiddleware.cs#L116-L127

Yes the OperationCanceledException will primarily happen if the client disconnects before the session is saved. There is also a timeout if the storage system is being slow: https://github.com/aspnet/AspNetCore/blob/725fa34cc801017294a805a6c0929992456de42a/src/Middleware/Session/src/SessionOptions.cs#L40-L44

**Comment by lianggx** [comment]
@Tratcher Hi, Tratcher，Thank your reply!
My used . version-2.2, May be that OperationCanceledException should be throw i think.
So ignore the OperationCanceledException i want to. The OperationCanceledException message caused a large number of logs to be written and that message on client disconnects before the session is saved.
