### ISSUE TITLE
AuthorizationHandlerContext.Resource is not of type Endpoint with Endpoint Routing

### ISSUE THREAD

**Issue by jessicah** [dotnet/aspnetcore#13572]
According to #11705, `AuthorizationHandlerContext.Resource` should be an instance of `Endpoint` in ASP.NET Core 3.0 when using endpoint routing, but it is instead an instance of my resource. Perhaps this is because I'm using the `AuthorizationHandler<TRequirement, TResource>` version, but from documentation I've read, that seems to be the right thing to do, and indeed has worked correctly thus far. However, I now want to redirect to a different error page when authorization fails, but I cannot fetch `Endpoint` as documented in linked issue.

```
public class EmailAuthorizationHandler : AuthorizationHandler<SameEmailRequirement, Models.Member>
{
	protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, SameEmailRequirement requirement, Models.Member resource)
	{
		if (context.User.HasClaim(claim => claim.Type == ClaimTypes.Email))
		{
			var emailAddress = context.User.Claims.SingleOrDefault(claim => claim.Type == ClaimTypes.Email)?.Value;

			if (emailAddress != null && 
				(emailAddress.ToLowerInvariant() == resource.EmailAddress?.ToLowerInvariant() ||
				emailAddress.ToLowerInvariant() == resource.ZwiftEmailAddress?.ToLowerInvariant()))
			{
				context.Succeed(requirement);
			} else
			{
				if (context.Resource is Endpoint endpoint)
				{
					// False
				}
				if (context.Resource is Models.Member resourceIsMember)
				{
					// True
				}
			}
		}

		return Task.CompletedTask;
	}
}

public class SameEmailRequirement : IAuthorizationRequirement { }
```

**Comment by blowdart** [comment]
The linked issue isn't an authorization issue.

What is calling into your handler? Are you doing it declaratively with the attribute or imperatively with code?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by jessicah** [comment]
Sorry, typo, I meant #11075, and didn't see the email notification :/

```
services.AddAuthorization(options =>
{
	options.AddPolicy("SameEmail", policy => policy.Requirements.Add(new SameEmailRequirement()));
});

services.AddSingleton<IAuthorizationHandler, EmailAuthorizationHandler>();
			
```

**Comment by blowdart** [comment]
@HaoK is this expected for endpoint routing?

**Comment by anurse** [comment]
> So how do I write an AuthorizationHandler that has access to both the `Endpoint` instance and the `Models.Member` instance?

If you're explicitly authorizing against a custom resource like `Models.Member` then that's the resource you'll get in the handler. If you need access to other data (like the `Endpoint`), you'll need to add that to the resource you provide when authorizing. You should be able to access it off the `HttpContext` when you create your resource. For exmaple:

```csharp
var endpoint = // Get Endpoint off HttpContext (I don't remember off-hand exactly where it is)
var member = // your code to get the Models.Member object
authzService.AuthorizeAsync(...., new MyCustomResource(member, endpoint));
```
