### ISSUE TITLE
Automate updates of partner packages

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#13586]
- at a slow cadence
- use list @JunTaoLuo is compiling

**Comment by JunTaoLuo** [comment]
This looks like the list: https://github.com/dotnet/aspnetcore/issues/4019#issuecomment-528096894. I think the tool I used to generate the list is at https://github.com/JunTaoLuo/DepScanner/.

**Comment by dougbu** [comment]
Potential use of dependabot here❔

**Comment by wtgodbe** [comment]
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by dougbu** [comment]
This tracks work we have incentive to handle anytime soon. Let's deal w/ the partner ecosystem if and when the exact guidance becomes clear at the .NET level.
