### ISSUE TITLE
Inconsistent UI state after reconnect for app deployed to Azure App Service with Azure SignalR Service

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#13600]
After a successful reconnect, the UI state appears to be out of sync with the browser. If I click on the Counter tab after losing my network connection and then reestablish my network connection the reconnection succeeds and the browser address says I'm on the Counter page but I still see the home page.

Repro steps:
- Create a new Blazor Server App
- Deploy the app to Azure App Service with the Azure SignalR Service added as a dependency
- Browse to the app home page successfully
- Disconnect the network
- Click on the Counter tab
- Reconnect the network
- Wait for successful reconnection (click Retry button if you need to)

Expected result:
- App reconnects and the Counter tab is shown

Actual result:
- App reconnects but stays on the home page even though the address bar says I navigated to the counter page.

![image](https://user-images.githubusercontent.com/1874516/64071367-b98b0080-cc2d-11e9-9d45-da55f4eeb6d3.png)

**Comment by ADefWebserver** [comment]
I have seen this, As a temporary workaround I stopped using the Azure SignalR service, and instead just [turned on web socket support](http://blazorhelpwebsite.com/Portals/0/Blog/Files/1/4349/Windows-Live-Writer-Deploying-A-Server-Side-Blazor-Applicati_65AC-image_a7dcaab9-f3a1-45e1-b26d-7726954c9c92.png) on my Azure App service. This work around may not work for someone who has their Azure App service scale up into multiple instances.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
