### ISSUE TITLE
Consider not using the wall clock time for timeouts in Kestrel

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/aspnetcore#13628]
### Is your feature request related to a problem? Please describe.

I have an embedded instrument with an RTC that's powered by a small gold cap. However, that battery is limited and so the instrument might forget the current date / time. If that happens, the system boots with a default date/time depending on when the Linux image was built.

There's a user interface that's rendered on an internal web browser connected to the localhost web server via SignalR.

Third, there's a way to set the date/time when lost, which directly sets the wall clock on the instrument (the time difference is typically O(months)).

When the user sets the date/time, the SignalR connection runs into a timeout [because timeouts are based on wall clock time](https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview9.19424.4/src/SignalR/server/Core/src/HubConnectionContext.cs#L558) and my thought-to-be stable localhost connection breaks. I have included a retry logic just for that case.

### Describe the solution you'd like

Using wall clock for timeouts always runs into scenarios such as the one described above. In my opinion it would be better to base those decisions off of a monotonic and continuous time source (Stopwatch?).

**Comment by halter73** [comment]
Do you know if Stopwatch is actually guaranteed to be monotonic and continuous?

**Comment by Tragetaschen** [comment]
My read on the documentation is that Stopwatch uses a monotonic counter as a backing store and looking through the code, that claim is backed:
- Windows uses QueryPerformanceCounter and debug-asserts that it works (available since XP)
- On Linux [it uses a CLOCK_MONOTONIC](https://github.com/dotnet/corefx/blob/v3.0.0-preview9.19421.4/src/Native/Unix/System.Native/pal_time.c#L88), again with an assert.
- On Mac, there is `mach_absolute_time`

**Comment by halter73** [comment]
If we change this is SignalR, we should probably consider doing the same for Kestrel timeouts. While it's probably not as likely to run on client devices with unreliable clocks like SignalR, it seems like the right thing to do.

**Comment by BrennanConroy** [comment]
This specific case looks like the server was running on one of those devices so Kestrel would definitely have similar issues.

**Comment by samsosa** [comment]
Maybe Environment.TickCount or Environment.TickCount64 are good (and fast) enough?

**Comment by Tragetaschen** [comment]
This is probably worth synchronizing with: https://github.com/dotnet/corefx/issues/3249

**Comment by Tragetaschen** [comment]
Related to https://github.com/dotnet/corefx/pull/35401

**Comment by davidfowl** [comment]
This feels like something we should do.

**Comment by BrennanConroy** [comment]
Agreed, SignalR and Kestrel should switch to using `Environment.TickCount64` for timeouts.

**Comment by halter73** [comment]
The analogue for this in the SignalR JS/TS client is [performance.now()](https://developer.mozilla.org/docs/Web/API/Performance/now).

**Comment by adityamandaleeka** [comment]
Updated the title since the SignalR side of this is done in https://github.com/dotnet/aspnetcore/pull/34382

**Comment by halter73** [comment]
> 😢 I should push a branch for the Kestrel stuff I tried

This isn't an API change. I see no reason we couldn't take this for 6 if it's ready.

**Comment by adityamandaleeka** [comment]
Agreed. It's not ready though, and it sounds like it's trickier than originally imagined. @BrennanConroy if you are still interested in getting it done for 6, don't let the milestone change stop you :).
