### ISSUE TITLE
[Blazor] Containment Ability

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/aspnetcore#13643]
Dear AspNetCore team,

Sometimes, we need _Containment_ feature like React has because of some components don’t know their children ahead of time, especially for abstract components.

In React, we can do the following:
```
function Base(props) {
  return (
    <div className={'Component-' + props.name}>
      {props.children}
    </div>
  );
}

function Button() {
  return (
    <Base name="button">
      <button type="button">{props.label}</button>
    </Base>
  );
}
```

Is it possible in **Blazor** if I create a base component too like I do in React, for instance an abstract called `Component` and it extends `ComponentBase`? It also has a render template as following:
`<div id="@id" class="component @class" state="@state"></div>`

And for the `Button`, it just needs to extend the `Component` class by using `@Inherits Component` with the render implementation as following:
`<div class="label">@buttonText</div>`

The final render presentation of the `Button` component would become:
```
<div id="123" class="component button" state="1">
  <div class="label">Submit</div>
</div>
```

And we might be able to extend the `Button` component again into another `AwesomeButton` components so it can be reused and flexible.

I would have so many components in my future project and it would be very helpful if Blazor has this feature. Thank you for your time.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @justinushermawan .
This should already be possible using RenderFragments: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#child-content.
Have you tried this out already?

**Comment by justinushermawan** [comment]
> Thanks for contacting us, @justinushermawan .
> This should already be possible using RenderFragments: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#child-content.
> Have you tried this out already?

Yes, I have. But it's just look like the _layout composition_ (the child content was supplied by the parent). Whereas, what I need is more to the OO inheritance concept where the child can inherit the parent render template and it supplies its own content as the children element of its parent.

```
function Base(props) {
  return (
    <div className={'Component-' + props.name}>
      {props.children}
    </div>
  );
}

function Button() {
  return (
    <Base name="button">
      <button type="button">{props.label}</button>
    </Base>
  );
}
```

**Comment by mkArtakMSFT** [comment]
Thanks @justinushermawan.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by SteveSandersonMS** [comment]
Another solution worth considering is *not* to use inheritance, but instead use composition.

For example, let's say you have a `MyGenericDialog` component that takes a bunch of parameters like `[Parameter] RenderFragment Header { get; set; }` and `[Parameter] RenderFragment Body { get; set; }` and so on.

Then you can also declare a `MyCustomizedDialog` that itself renders a `MyGenericDialog`, passing in whatever hard-coded or dynamic content you want:

MyCustomizedDialog.razor:

```
<MyGenericDialog>
    <Header>Some content</Header>
    <Body>More content</Body>
</MyGenericDialog>
```

You mention React in your post - I think this compositional solution would be closer to an idiomatically React-like way of doing things than using OO inheritance.

**Comment by SteveSandersonMS** [comment]
This has been stale for a while with no clear community interest, so I'll close it. People have been successful using `RenderFragment` so it's not clear there's a strong need here.
