### ISSUE TITLE
Profile HTTP/2 and identify hotspots

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#13745]
Scenarios:
* [ ] TechEmpower plaintext but over HTTP/2
* [ ] Basic POST. Request is text/plain string of name. Reply is text/plain `"Hello " + name`
* [x] Basic gRPC. See [gRPC tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start)
* [x] Streaming gRPC. The same as the basic gRPC but the [server streaming multiple messages](https://github.com/grpc/grpc-dotnet/blob/a56e110986fee4bb3861e198e1721e13bf7980a3/examples/Clients/Greeter/Program.cs#L51-L70)
* [ ] Stream per connection vs multiple streams on one connection
* [ ] H2 vs H2C
* [ ] Kestrel and IIS HTTP/2 performance
* [ ] Server streaming

Output:
* [ ] Create new HTTP2 issues with screenshots/traces/numbers from profile

**Comment by davidfowl** [comment]
This is an old benchmark from preview4 https://github.com/aspnet/AspNetCore/issues/6567

**Comment by jkotalik** [comment]
@JamesNK is https://github.com/dotnet/aspnetcore/issues/13752 sufficient for the info covered here?

**Comment by BrennanConroy** [comment]
@JamesNK Any remaining work? And is it for Next Sprint or Backlog?

**Comment by JamesNK** [comment]
Backlog

**Comment by JamesNK** [comment]
I think there are improvements still to be made to writing frames on busy multiplexed connections but not a priority for 6.0

**Comment by JamesNK** [comment]
I'm going to close this. With .NET 7 we've hit the known remaining hotspots: upload flow control, and download concurrency.

In the future, we can have individual issues for future HTTP/2 perf hotspots.
