### ISSUE TITLE
SPAServices React app without create-react-app

### ISSUE THREAD

**Issue by Daniel15** [dotnet/aspnetcore#13757]
I have an existing React app that was not built using create-react-app. I'm trying to convert it from PHP to ASP.NET Core.

Currently it uses the Webpack dev server. It looks like `spa.UseReactDevelopmentServer()` requires me to use create-react-app, but it has some nice features like automatically starting the React server. For regular Webpack, it seems like I need to use `spa.UseProxyToSpaDevelopmentServer()` and start the server myself.

Is there a way to have ASP.NET automatically start the development server when using webpack-dev-server, similar to what `UseReactDevelopmentServer` does?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
