### ISSUE TITLE
Blazor Server-Side: Render Component via JavaScript

### ISSUE THREAD

**Issue by schmitch** [dotnet/aspnetcore#13766]
### Is your feature request related to a problem? Please describe.
Currently if somebody has a big codebase in say react/angular (or other SPA framework) and want to migrate to Blazor Server-Side he would need to rewrite everything at once.
So it would be great if it would be possible to "render" a blazor component server-side via JavaScript methods into a dom element.

### Describe the solution you'd like
Probably it would be good enough to have a javascript library published to npm that can call a blazor component by name.
I think the following points would need to be addressed aswell:

- Input Parameters (how to handle these)
- Output Events (how to handle these, to interact with other SPAs)
- Authentication/Authorization (if cookies are used it should work as-is, else also allow to send the auth token?!)
- manual Blazor Bootstrap, i.e. since the Blazor Server js library would probably need to be bundeled.

something like `await Html.RenderComponentAsync<CoursesList>(new { Courses = Model })` just for typescript with more options. Probably also needs some changes to blazor.

I think at the moment it's possible to render to a razor view via `RenderMode.Server` and innerHTML the generated comment. (get the html page with the comment via ajax)

actually `RenderComponentAsync` has a protocol that might be useful for the JavaScript part:
`https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview9.19424.4/src/Components/Server/src/Circuits/ServerComponentDeserializer.cs` unfortunatly it needs DataProtection and I'm also unsure how useful Authentication/Authorization is on these components. Because I tried preview9 and the component will be rendered (but not work) as soon as the marker exists and the RazorPage/Mvc is AllowAnon.

### Additional context
Guess it would be a nice addition for .NET 5. And make it easier to test out Blazor when just creating a small set of components.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by 0x53A** [comment]
Has there been any progress on this?

Not being able to create hostable-from-js components means we would be unable to reuse anything we build in blazor, which kinda kills it for us.

**Comment by adamhathcock** [comment]
I would love to be able to reuse the Blazor server JavaScript snippet outside of CSHTML.

This would enable migration from other SPAs to Blazor in a better slice approach.  Otherwise I have to resort to something like iframes in my angular app and post messages across.

I keep thinking this must be possible as the rendered CSHTML output is just JavaScript.  Understanding how I could do this myself or why it isn't possible would be great.

Thanks!

**Comment by javiercn** [comment]
We implemented this feature as part of our 6.0 wave. You can see more details [here](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#render-blazor-components-from-javascript)
