### ISSUE TITLE
Migration 2.2 -> 3.0 document migration path for a library

### ISSUE THREAD

**Issue by mrgleba** [dotnet/aspnetcore#13760]
W have a library being used by a couple of projects. Our csproj for 2.2 was
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.*" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
</Project>
```

As the packages are part of the framework now and there are no 3.0 version. A simple
change to ```<TargetFramework>``` is not sufficent. Also ```<Project/>``` neds to be changed to
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

and 
``` xml
<OutputType>Library</OutputType>
```
needs to be added.

The new file for 3.0 is
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
</Project>
```

We found that by luck after a lot of digging aroud. I'd be nice for this to be a part of the migration docs.

**Comment by Pilchie** [comment]
@glennc @davidfowl @danroth27 - fodder for the migration guide doc.

**Comment by Rick-Anderson** [comment]
@glennc `@davidfowl` @danroth27 -
Should I add this to the [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio) doc so you can close this issue?

**Comment by Rick-Anderson** [comment]
@pranavkm Should I add this to the [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio) doc so you can close this issue?

**Comment by pranavkm** [comment]
Isn't this already covered by https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#framework-reference?

**Comment by Rick-Anderson** [comment]
No mention of 
`    <OutputType>Library</OutputType>`

But maybe that's not necessary
If we have enough, can you close this issue?

**Comment by pranavkm** [comment]
If you're targeting `Microsoft.NET.Sdk` or `Microsoft.NET.Sdk.Razor`, the `OutputType` is `Library` by default. So theoretically that's not necessary if @mrgleba had followed the migration guide.

**Comment by danroth27** [comment]
@scottaddie was working with@DamianEdwards on some content specifically for ASP.NET Core library authors that I believe covers this scenario.

**Comment by scottaddie** [comment]
https://github.com/aspnet/AspNetCore.Docs/pull/15741 is where the work is being done to cover this scenario.

**Comment by Pilchie** [comment]
Closing as this should be covered by the docs above.
