### ISSUE TITLE
IIS support with Kestrel and ServerCertificateSelector

### ISSUE THREAD

**Issue by dolphinsd** [dotnet/aspnetcore#13788]
We are running asp.net core behind IIS on win server 2019.

IIS configured with default SSL server certificate on ip with no  hostname, see attached. It works, if you hit on that certificate subject.

But when server is requested with website ServerCertificateSelector is not run per specs here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#how-to-use-kestrel-in-aspnet-core-apps

When you run request https://my.site.com HTTPS selector is never called.

What are we missing? Does IIS support ServerCertificateSelector ?
Our site supports many urls, and we have ssl certificates stored in database. We want to server them on demand.

![broken](https://user-images.githubusercontent.com/3460517/64469521-63fc9b00-d0e8-11e9-952c-56e88623cc12.png)

**Comment by blowdart** [comment]
IIS doesn't support ServerCertificateSelector, nor would nginx. That's only for running kestrel "raw", with nothing in front it, as proxies in front terminate the HTTPS connection at their own level.

**Comment by dolphinsd** [comment]
@blowdart , thanks for an insight, it works in development, but when we try to run from command line in production, certificate selection is not called for some reason.

**Comment by blowdart** [comment]
By the time it gets through IIS in production it's not exactly a connection any more, because of the way IIS integration works. IIS has the responsibility of the handling the HTTPS termination. There's no easy way to do this in IIS unfortunately

**Comment by dolphinsd** [comment]
@blowdart , do you know if IISHttpServer exposes ability to swap certificates in runtime like Kestrel?

**Comment by blowdart** [comment]
I don't believe so. @shirhatti to confirm.

**Comment by shirhatti** [comment]
IIS supports SNI, but doesn't allow you to run custom ASP.NET Core code during the handshake to select the certificate. The options you have available are either to have all certificates available at the time of creating the binding(s) OR use the central certificate store (CCS) which allows you to specify certificates via file-name based conventions. 

From what you've described thus far, it sounds like CCS can achieve what you're trying to do.

**Comment by dolphinsd** [comment]
@shirhatti , thanks for the pointer, we implemented CCS, the problem, is that certificate is not loaded till you either recycle iis server or open iis admin for the new binding by hand and close it, only then ssl certificate is loaded. I would assume IIS should listen for folder changes and load those certificate :(

**Comment by dolphinsd** [comment]
We tried to update central SSL certificate store from ASP.NET core app. Even after given permission to the iisnet config path for IUSR and IIS_IUSRS, when biding record is committed we get exception. The binding record is created, but it fails to associate with SSL certificate via the store. Any idea, how to overcome it?

> Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
>    at Microsoft.Web.Administration.Interop.IAppHostMethodInstance.Execute()
>    at Microsoft.Web.Administration.BindingManager.Save()
>    at Microsoft.Web.Administration.ServerManager.CommitChanges()

Here is a the code that rights the record

```
ServerManager manager = new ServerManager();
Site site = this.manager.Sites[0];
Binding bind = site.Bindings.CreateElement();
bind.Protocol = "https";
bind.BindingInformation = "*:443:" + hostName;
bind.sslFlags = SslFlags.CentralCertStore | SslFlags.Sni;
site.Bindings.Add(bind);
manager.CommitChanges();
```
