### ISSUE TITLE
Self hosted application as windows service seems to have some issues with cookies

### ISSUE THREAD

**Issue by taori** [dotnet/aspnetcore#13804]
### Describe the bug
I've got an application which i am developing on my machine with a publish profile to deploy it to a services folder. If i'm using the application while debugging the cookie consent messages correctly goes away after i accept it - if i run the application after deploying and running it as windows service the cookie consent message won't go away.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Pull this commit https://github.com/taori/ShutdownTimer/commit/fe31763b0b13a202350e7dc094cc4f04f6614e81
3. publish locally
4. run createService.ps1 as admin
5. navigate to app (localhost:4300)
6. press Ok on consent 
7. reload - consent message still there.

### Expected behavior
It should behave the same as when i'm debugging the application

**Comment by taori** [comment]
Logging in doesn't work either obviously since cookied are not working.

**Comment by taori** [comment]
After spending quite a while and attempts to fix it i found a mention im some thread that signin cookies don't work outside of https.

So this issue happening to me was a result of combined factors:
- deployment as windows service
- executed as custom local service user account

fixing it required me to export the dev certificate and then reference it in the configuration like this:


	"Https": {
		"Url": "https://localhost:4302",
		"Certificate": {
		  "Path": "path to pfx file",
		  "Password": "password"
		}
	},

Ideally there should be some error logging pointing this out when hosting as windows service when specifying a http binding outside of debugging. I'll bring it up at the docs.

**Comment by anurse** [comment]
> So this issue happening to me was a result of combined factors:
> 
> * deployment as windows service
> * executed as custom local service user account
> 
> fixing it required me to export the dev certificate and then reference it in the configuration like this:

Yep, this is expected if you are running outside of your local user profile. You'll need to import a specific certificate and can't use the dev cert since that associated with your user.
