### ISSUE TITLE
ASP.NET Multipart Form Response

### ISSUE THREAD

**Issue by etherealjoy** [dotnet/aspnetcore#13810]
### Is your feature request related to a problem? Please describe.

I am trying to implement an endpoint which returns a multipart/formdata response in ASP.NET Core but apparently there is no inbuilt mechanism to do that or at least I am not aware how and have not found it in the docs somewhere.

### Describe the solution you'd like

Of course we could write our own implementation for this, but it wouldn't be such an elegant thing to do if there is something coming in the framework in the future.
So some extension or a new class to handle this in the framework would be great.

### Additional context

e.g instead of returning content which is based on `IActionResult` something like returning a `MultiPartResult` response and this gets serialized correctly or the `IActionResult` gets updated to return MultiPart as well.

e.g.

```C#
public IActionResult DownloadFile([FromRoute][Required]string fileName) {            
	var path = Directory.GetCurrentDirectory();
	var fs = new FileStream(Path.Combine(path, fileName), FileMode.Open);

	if(fs == null) 
	{
		return NotFound(); 
	}
	return File(fs, "application/octet-stream", fileName); 
} 
```
With `IActionResult` additional fields in the response besides `fileName` cannot be returned without a custom implementation.
A new hypothetical `MultiPartResult` could allow returning additional fields, by adding items to a response and is automatically serialized as a multipart form response.

**Comment by MV10** [comment]
See https://github.com/aspnet/Mvc/issues/4933

**Comment by mkArtakMSFT** [comment]
Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
