### ISSUE TITLE
Improve the experience for polymorphic model validation

### ISSUE THREAD

**Issue by pamedasa** [dotnet/aspnetcore#13829]
### Describe the bug
The annotations that we add for validations are not getting invoked for polymorphic input classes. They are getting invoked only for the non-polymorphic classes.
Data model validators are not being invoked for request input data which is of type polymorphic data. In general, all the validators are being fired up before passing to actual implementation of controller code. 

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
in Asp.Net framework, irrespective on input data model (whether it is normal (or) polymorphic) all the validators gets invoked and thrown the exception in right format. After moving to asp.net core as well, validators should work as expected earlier.

### Additional context
Include the output of `dotnet --info`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @pamedasa .
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
I just got around to writing a snippet in our docs that shows how to author a polymorphic binder: https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2#polymorphic-model-binding. Outside of the top level property being bound, MVC uses the declared model type unless the model binder explicitly tells it otherwise.:

```C#
bindingContext.Result = ModelBindingResult.Success(result);

// Add a ValidationStateEntry with the "correct" ModelMetadata so validation executes on the actual type, not the declared type.
var modelMetadataProvider = bindingContext.HttpContext.RequestServices.GetRequiredService<IModelMetadataProvider>();

bindingContext.ValidationState.Add(result, new ValidationStateEntry
{
    Metadata = modelMetadataProvider.GetMetadataForType(result.GetType()),
});
```

@rynowak \ @dougbu  we might want to build a thing for 5.0, but for 3.1 would it help if `ValidationVisitor` printed a warning if the `model.GetType() != Metadata.ModelType` saying you might have missed this? It's not super obvious that a binder has to do this.

**Comment by pamedasa** [comment]
I have created custom model validator which works for complex inputs like polymorphic data. Taken the advantage of TryValidateModel provided by controllerbase from asp.net core MVC and override the method to add our own logic.

public override bool TryValidateModel(object inputObject)
        {
            Type type = inputObject.GetType();
            foreach (var prop in type.GetProperties().Where(p => !p.GetIndexParameters().Any()))
            {
                object val = prop.GetValue(inputObject);
                base.TryValidateModel(val);

                // Skipping the model validation for primitive types and 
                // objects which don't have properties.
                if (!val.GetType().IsPrimitive && val.GetType().GetProperties().Length != 0)
                {
                    this.TryValidateModel(val);
                }
            }
            return true;
        }

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @pamedasa.
We'll look into improving polymorphic model validation effectiveness for 5.0.

**Comment by pranavkm** [comment]
@pamedasa I wouldn't recommend using the example you have. It misses validators on primitive data types and ignores validation attributes applied to properties. Have a look at the sample, the change to make MVC's model validation pick up the correct model requires minimal changes to the model binder.

**Comment by BrunoZell** [comment]
Another workaround is to call `TryValidateModel(..)` for all instances in the model you know have polymorphic characteristics and use the short-circuit response `ValidationProblem(ModelState)` in case the validation failed (returned `false`). All validation errors will be added to `ModelState`.
