### ISSUE TITLE
Perf: Build custom pipelined client for TechEmpower benchmarks

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#13836]
### What problem are you having.
In TechEmpower benchmarking, we're seeing that the pipelined test is limited by CPU on the load generator based on it interpreting LUA script.

### Describe the solution you'd like
Let's write a custom load generator client instead.

**Comment by dougbu** [comment]
/ping @sebastienros and @davidfowl 

Has this issue been resolved❔ If not, what work is still required and who should do it❔

**Comment by sebastienros** [comment]
Done
