### ISSUE TITLE
InvalidOperationException: 'RemoteNavigationManager' has not been initialized when used from DelegatingHandler in OnAfterRenderAsync

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#13906]
Originally reported by @akorchev.

Repro steps:
- Create a delegating handler that uses the `NavigationManager` to navigate.
- Setup the delegating handler with `HttpClient` using HttpClient factory
- In a Blazor Server app use the configured HttpClient from *Index.razor* in `OnAfterRenderAsync`.

```
System.InvalidOperationException: 'RemoteNavigationManager' has not been initialized.
   at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
   at Microsoft.AspNetCore.Components.NavigationManager.NavigateTo(String uri, Boolean forceLoad)
   at BlazorApp5.MyDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\user
[BlazorApp5.zip](https://github.com/aspnet/AspNetCore/files/3602254/BlazorApp5.zip)
[BlazorApp5.zip](https://github.com/aspnet/AspNetCore/files/3602256/BlazorApp5.zip)

\Source\Repos\BlazorApp5\BlazorApp5\MyDelegatingHandler.cs:line 25
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BlazorApp5.MyService.DoHttpStuff() in C:\Users\user\Source\Repos\BlazorApp5\BlazorApp5\MyService.cs:line 26
   at BlazorApp5.Pages.Index.OnAfterRenderAsync(Boolean firstRender) in C:\Users\user\Source\Repos\BlazorApp5\BlazorApp5\Pages\Index.razor:line 11
```

**Comment by danroth27** [comment]
[BlazorApp5.zip](https://github.com/aspnet/AspNetCore/files/3602265/BlazorApp5.zip)

**Comment by rynowak** [comment]
>Setup the delegating handler with HttpClient using HttpClient factory

That's not going to work unfortunately. The client factory doesn't share scopes with requests, or with the circuit.  So what you're getting is an unitialized `NavigationManger` - which is why it's throwing an exception.

**Comment by gorrilla10101** [comment]
You get the same error when you use OwningComponentBase for a service with a dependency on NavigationManager. 
in this example their is an OwningService with a dependency on NavigationManager
and index.razor inherits OwningComponentBase<OwningService>

[OwningComponentBaseExample.zip](https://github.com/aspnet/AspNetCore/files/3617239/OwningComponentBaseExample.zip)

**Comment by mikoskinen** [comment]
I have a scenario where I tried to access NavigationManager from a JSInvokable method. The method is called through DotNet.invokeMethodAsync.

I'm getting the same exception:

    System.InvalidOperationException: ''RemoteNavigationManager' has not been initialized.'

 I don't suppose there's anyway around this? Here's the code:

        [JSInvokable]
        public static Task NavigateToUrl(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
            {
                return Task.CompletedTask;
            }

            Debug.WriteLine($"Navigating to {url}");

            var scopeFactory = ServiceProvider.GetService<IServiceScopeFactory>();
            using (var scope = scopeFactory.CreateScope())
            {
                var navigationManager = scope.ServiceProvider.GetRequiredService<NavigationManager>();
                navigationManager.NavigateTo(url);
            }

            return Task.CompletedTask;
        }

**Comment by rynowak** [comment]
@akorchev - what are you trying to do?

I wouldn't expect this scenario to work. HTTP client factory doesn't resolve services into message handlers from the containing scope - ie - there's no way to create an HTTP client that will share state with a bunch of components automatically.

**Comment by akorchev** [comment]
I have a delegating http handler that redirect to a login page when an access token is not available (or has expired). I've managed to do that by manually creating the HttpClient instead of using the HttpClientFactory.

**Comment by jan-johansson-mr** [comment]
I have run into the [same issue](https://github.com/aspnet/AspNetCore/issues/11867) :-)

**Comment by jan-johansson-mr** [comment]
Here is an interesting question, how can I use [NavigationManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanager?view=aspnetcore-3.0) in middleware?

**Comment by Mike-EEE** [comment]
Experimenting with the default server-side template + authentication, I am getting a similar but intermittent exception that occurs after logging in and appears to be related to the `NavLink`s found in the `NavMenu.razor` file.  Commenting them out seems to make the error go away altogether.

I should also mention that after I login and try logging out/back in the error does not occur.

I should also also 😁 mention that I am using the Twitter external authentication provider, just to maximize my grief.

Here is my stack trace:

```
InvalidOperationException: 'RemoteNavigationManager' has not been initialized.
Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
Microsoft.AspNetCore.Components.NavigationManager.remove_LocationChanged(EventHandler<LocationChangedEventArgs> value)
Microsoft.AspNetCore.Components.Routing.NavLink.Dispose()
Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)
Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(bool disposing)
Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose()
Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, object parameters)
Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
Administration.Application.Pages.Pages__Host.<ExecuteAsync>b__14_1() in _Host.cshtml
+
        <component type="typeof(App)" render-mode="ServerPrerendered" />
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
Administration.Application.Pages.Pages__Host.ExecuteAsync() in _Host.cshtml
+
    Layout = null;
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I will update here if I can track this down further.
