### ISSUE TITLE
Re-enable Build_ExplicitCSharp8_NullableEnforcement_WarningsDuringBuild_BuildServer test

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#13930]
Details in: https://github.com/aspnet/AspNetCore-Tooling/pull/1122#issuecomment-530940364.

We disabled this test when converting to the 3.1 TFM since Roslyn seems to only use C# 8 for netcoreapp3.0 only https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6-L10. Seems to me that this should be updated to netcoreapp3.0 AND later.

cc @pranavkm

**Comment by allisonchou** [comment]
This test and its area path doesn't seem to exist anymore, and given this issue is over 2 years old, I think it's likely safe to close out.
