### ISSUE TITLE
Re-enable RazorSdk_DoesNotBuildViewsForNetCoreApp11Projects test skipped when migrating to netcoreapp3.1

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#13943]
I disabled the test as part of https://github.com/aspnet/AspNetCore-Tooling/pull/1122#issuecomment-530976125. Tracking whether we want to remove the test or figure out why it failed.

cc @pranavkm @mkArtakMSFT

**Comment by pranavkm** [comment]
Thanks @JunTaoLuo. Like I noted in the PR, this tests 1.1 scenarios which are no longer supported. We should remove the test. @ajaybhargavb could you have a look at this?

**Comment by rynowak** [comment]
Let's get more visibility on this before doing something. I'm not sure we what point we willfully start removing/not-testing things.

**Comment by ajaybhargavb** [comment]
> Let's get more visibility on this before doing something. I'm not sure we what point we willfully start removing/not-testing things.

Sorry, I missed this comment until now (when I merged and was going to close this issue). 

@mkArtakMSFT we are removing a bunch of 1.x related SDK and VS Code Razor tests because 1.x is no longer in support. Here is the [PR](https://github.com/aspnet/AspNetCore-Tooling/pull/1169). I can revert if you think we should still keep the test.

**Comment by rynowak** [comment]
@kevinpi - what's the expectation for SDK support for runtimes that are out of support?

**Comment by mkArtakMSFT** [comment]
I am supportive of this change. @Pilchie what are your thoughts?

**Comment by rynowak** [comment]
I'm very concerned about removing tests for things that we still care about working (yes I know it's end of life). If we don't care about it working, we can remove a bunch of cruft from the SDK.

**Comment by mkArtakMSFT** [comment]
Are we loosing coverage by removing these tests? Given the proposal to remove these tests I assume there are others in place covering scenarios we care about, aren't there?

**Comment by rynowak** [comment]
> I assume there are others in place covering scenarios we care about, aren't there?

I don't assume that 😆 - we should not *just remove all of the tests for 1.1*. There's code and features we still ship that are unique to 1.1. We should remove it all (if appropriate) or bring back the tests.
