### ISSUE TITLE
published self hosting .exe does not has blank app attributes

### ISSUE THREAD

**Issue by sprocket99** [dotnet/aspnetcore#13954]
### Describe the bug
I have an asp.net core app, using latest 2.2 version. I set the Product Name and Description under `Package` tab in Project > Properties. The compiled .dll file has the correct attributes under `Details` tab. But when I publish and it becomes an `.exe` it loses those attributes and they blank. 

### Expected behavior
For the published self hosting .exe to have the same product name, description and version as the .dll.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sprocket99.
@vijayrkn can you please look into this as this is publishing related? Thanks.

**Comment by vijayrkn** [comment]
For VS issues, please open a developer community issue. Documentation - https://developercommunity.visualstudio.com/content/problem/post.html?space=8

**Comment by sprocket99** [comment]
Is this VS related? You can publish without using VS, using `dotnet publish` I believe.
