### ISSUE TITLE
Blazor render SVG onclick event

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#14005]
this doenst compile within a SVG tree (with html elements it works)
Base is a s componentBase - Rendertree Event 
SVG is displayed 

builder.AddAttribute(++seq, "onclick", onclick);
...

 public void onclick(UIMouseEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("Hello");

        }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hannespreishuber.
We'll look into adding support for this in our next major release.

**Comment by mkArtakMSFT** [comment]
Closing as we will be tackling this as part of https://github.com/dotnet/aspnetcore/issues/18271
