### ISSUE TITLE
[Blazor] Consider using tracing APIs to perform more fine grained logging

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#14034]
Right now we log in important information in the Blazor renderer using ILogger. This has some drawbacks, like the need to depend on Microsoft.Extensions.Logging from Microsoft.AspNetCore.Components and the need to pass around an ILogger instance for logging purposes, which limits the amount of logging we do inside the framework.

Currently we log major events within the renderer, like a component rendering, etc, but in some cases, more information is beneficial for troubleshooting scenarios. For example, it is highly beneficial to log the parameters a component is being rendered with when calling SetParametersAsync or to log the component current parameters values before applying them in order to understand why a component is being re-rendered.

Similarly, logging information inside the diffing algorithm can be beneficial too. Those scenarios however are not very well suited for ILogger due to:
* High performance requirements not met by ILogger.
* Requiring an ILogger instance to perform logging.

For these situations we could consider using EventSource logging as a way capturing this information. The advantages of using EventSource directly are:
* It doesn't require adding new dependencies as its netstandard2.0
* It doesn't require an instance to be used.
* It is designed for very high performance scenarios (100.000 events/sec).

We should consider adding additional instrumentation using EventSource to make complex scenarios easier to troubleshoot.
* Log in parameters passed to SetParameters
* Log in render requests from components (component base)
* Log in component Lifecycle events
* Log in component parameters before new parameters are applied.
* Log in new parameters before they are applied.

This will provide a more in depth trace of what is happening within an app and will greatly help troubleshoot scenarios in production apps and when we receive repro projects.

**Comment by mkArtakMSFT** [comment]
@javiercn there is no enough evidence for this to be an important thing. If there is, please bring it up, let's discuss.
