### ISSUE TITLE
AspNetCore should publish a package that identifies the non-stabilized version

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#14045]
Because aspnetcore (correctly) publishes its installers and blobs to a non-stabilized directory (e.g. 3.0.1-servicing-1235 vs. 3.0.1), Core-SDK needs to be able to identify that version number to be able to construct download paths.  For 3.0.100 GA, I used the following workaround:

https://github.com/dotnet/core-sdk/blob/release/3.0.1xx/src/redist/targets/GenerateLayout.targets#L15

That works fine since this package is not stabilized, but I'd like to be able to use something I know will ship in every servicing release.  For instance, a simple package called Microsoft.AspNetCore.Internal which always points to the non-stabilized version.

**Comment by dougbu** [comment]
What is the required timing of this change @mmitche❔ I suspect the actual work could be combined with work to give the ANCM installers per-build names even at 3.0 GA.

**Comment by mmitche** [comment]
post GA

**Comment by wtgodbe** [comment]
@mmitche can we just continue using `Microsoft.AspNetCore.DeveloperCertificates.XPlat` for this purpose? https://github.com/dotnet/core-sdk/blob/b7ef045669b9f07b29d9a13e20a537058d10d69f/eng/Version.Details.xml#L54

**Comment by mmitche** [comment]
Assuming you are goign to always publish it...yes. If not, then no.

**Comment by dougbu** [comment]
For 3.0 and newer, ASP.NET Core always publishes everything. The only exceptions are targeting packs.

**Comment by wtgodbe** [comment]
In that case I'll close this
