### ISSUE TITLE
Razor compiler breaks when adding reference to .NET Standard library

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#14058]
Repro steps:
- Create a Blazor Server app called "Weather.Blazor"
- Add a .NET Standard class lib to the solution called "WeatherLib"
- Add the following `Weather` class to the .NET Standard class lib (note the class namespace is the same as the class name):

```csharp
namespace Weather
{
    public class Weather
    {
    }
}
```

- Build the solution and check that it builds successfully
- Add a reference from the Weather.Blazor app to the WeatherLib project
- Build the solution again

Expected result: The solution still builds successfully

Actual result:

```
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0426	The type name 'Blazor' does not exist in the type 'Weather'	Weather.Blazor	C:\Users\user\Source\Repos\Weather.Blazor\Weather.Blazor\_Imports.razor	9		N/A
Error	CS0246	The type or namespace name 'WeatherForecastService' could not be found (are you missing a using directive or an assembly reference?)	Weather.Blazor	C:\Users\user\Source\Repos\Weather.Blazor\Weather.Blazor\obj\Debug\netcoreapp3.0\RazorDeclaration\Pages\FetchData.razor.g.cs	107		N/A
Error	CS0246	The type or namespace name 'WeatherForecast' could not be found (are you missing a using directive or an assembly reference?)	Weather.Blazor	C:\Users\user\Source\Repos\Weather.Blazor\Weather.Blazor\Pages\FetchData.razor	40		N/A
Error	CS0426	The type name 'Blazor' does not exist in the type 'Weather'	Weather.Blazor	C:\Users\user\Source\Repos\Weather.Blazor\Weather.Blazor\Pages\FetchData.razor	3		N/A
Error	CS0426	The type name 'Blazor' does not exist in the type 'Weather'	Weather.Blazor	C:\Users\user\Source\Repos\Weather.Blazor\Weather.Blazor\_Imports.razor	8		N/A
```

**Comment by danroth27** [comment]
I ran into this situation trying to build an app using a library that contained a generated gRPC client.

**Comment by rynowak** [comment]
Does this repo with all C#? What's specific about Blazor here?

**Comment by MajdajkD** [comment]
@danroth27   @rynowak 
I ran into the same problem: 
https://github.com/aspnet/AspNetCore/issues/13220
The Blazor specific part is, that the rendertree is not generated with global context namespaces.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by danroth27** [comment]
Tracking this as part of #18757
