### ISSUE TITLE
Update to the latest Angular version

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#14076]
Looks like Angular 9 is expected in Oct/Nov.

**Comment by mkArtakMSFT** [comment]
Hopefully we can get this available early enough to fit in 3.1 timeframe.

**Comment by varghesep** [comment]
Is there an update on upgrading to **Angular 9**? Since **Angular 9** is not released yet, Is there any branch that currently works with **Angular 9 RC**

**Comment by ericfowler303** [comment]
Angular 9 has been released: https://github.com/angular/angular/releases/tag/9.0.0

**Comment by mkArtakMSFT** [comment]
It looks like many people have done this manually and are facing some issue here: https://github.com/dotnet/aspnetcore/issues/17277

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by henrikdahl8240** [comment]
Just to be sure, .NET 5.0 Preview 6 will not support Angular 9 or .NET 5.0 RTM will not support Angular 9?
