### ISSUE TITLE
Is it possible to customize ASP.NET core 2.2 model binder so that exceptions of type *InvalidCastException* result in 400 status code response ?

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [dotnet/aspnetcore#14070]
Hi, 

we have noticed a behavior of the ASP.NET core 2.2 model binder that seems strange to us. 

Consider an ASP.NET core 2.2 web application obtained with the Visual Studio 2019 template for ASP.NET core web applications of type **API**. Add a controller like this: 

```
  [Route("api/[controller]")]
  [ApiController]
  public class ValuesController : ControllerBase
  {
    // POST api/values
    [HttpPost]
    public string Post([FromBody] ExpandoObject value)
    {
      return $"Number of items is: {value?.Count() ?? 0}";
    }
  }
```

When you call the path `/api/values` with a **POST** request and an empty request body (I mean that the request contains nothing at all) you get the following response having a `400` status code:

```
{
    "errors": {
        "": [
            "A non-empty request body is required."
        ]
    },
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "80000020-0003-fb00-b63f-84710c7967bb"
}
``` 

You get **the same response** if you make the same call with a request body containing the json value `null`. 

So far, so good. 

Things become unclear when you repeat the POST call to `/api/values` with a request body containing a json value such as `"test"` (a string) or `123` (a number): in that case the response has a `500` status code and the root cause of it is a server side `InvalidCastException` (for instance, when trying to cast the string "test" to an instance of ExpandoObject). 

In this case we would expect a `400` status code response, because both the values `"test"` and `123` are formally valid as json, but their type is not compliant with the action method parameter; in other words this is a scenario where the client calling the API is providing an invalid request content, so it is a client error. Put another way, we don't see any difference between a request body containing  `null` and one containing  `"test"`: both of them are not compliant with the action method signature due a client error, so in both cases we would expect a `400` status code. 

Is this an explicit design decision ? If it is, could you please explain why it is designed that way (maybe there are corner cases and details we haven't thought about) ? 

Is there a way to customize this behavior of the built in model binder (without rewriting from scratch a custom model binder and registering it with the framework) ? 

Thanks for helping

**Comment by mkArtakMSFT** [comment]
Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

**Comment by EnricoMassoneDeltatre** [comment]
> Thank you for your feature request. We'll consider this feature during the next release planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

Hi, this is not really a feature request.
Instead, this could be the starting point to investigate a possible bug.

We would like to understand whether the described behavior of the default model binder is the side effect of a bug in the `ExpandoObject` handling or an intended behavior.

For me the described behavior seems strange and I would have expected a `400` status code even when posting a `string`  or a `number`. An interval server error due to a failed cast seems to indicate a bug in ASP.NET core.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
