### ISSUE TITLE
Add API for AddHealthChecks().AddDbContextCheck<IDbService, DbContext>();

### ISSUE THREAD

**Issue by Euphoric** [dotnet/aspnetcore#14089]
It is possible to register Entity Framework's DB context like this:

`services.AddDbContext<IMyDbContext, MyDbContext>()`

But then, when one wants to use default health checks, it is not possible to do it as using 

`services.AddHealthChecks().AddDbContextCheck<MyDbContext>()`

throws an exception, because `MyDbContext `is not registered.

There should be a an API, that allows setting up the EF DB Context health check using the registered service interface.

`services.AddHealthChecks().AddDbContextCheck<IMyDbContext, MyDbContext>()`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Euphoric.
@rynowak can you please look into this? Thanks!

**Comment by klyse** [comment]
I have the same problem

**Comment by Pilchie** [comment]
Moving to Preview 3, since there  is no way for this to happen by Preview2.  @rynowak - any ideas here?

**Comment by rynowak** [comment]
This would require us adding a new API - I think we'd ultimately do what's being suggested in the issue. It should be fairly easy to do.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
