### ISSUE TITLE
[SpaServices] ng serve fails to start sometimes and causes reliability issues

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#14106]
[Standard_Console_Output Angular.log](https://github.com/aspnet/AspNetCore/files/3626760/Standard_Console_Output.Angular.log)

See the bottom of the attached log
```console
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! errno 1

fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! aspnet.angularnoauth.gn3lxmyceba@0.0.0 start: `ng serve "--port" "15302"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aspnet.angularnoauth.gn3lxmyceba@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is a development feature, but it affects our E2E test reliability. We don't have a workaround as in a similar case for react. We should consider building additional reliability into the middleware/product (given that this is used during dev, we could for example retry running the script a few times before failing)

**Comment by mkArtakMSFT** [comment]
Let's investigate this and understand how we can work around this, assuming this is an external issue.
