### ISSUE TITLE
LinkTagHelper fallback test for HTML attributes

### ISSUE THREAD

**Issue by XmlmXmlmX** [dotnet/aspnetcore#14104]
### The Problem
I am trying to add a fallback for [normalize.css](https://github.com/necolas/normalize.css/) but the [normalize.css file](https://github.com/necolas/normalize.css/blob/master/normalize.css) doesn't contain any css classes, but [attribute selectors](https://github.com/necolas/normalize.css/blob/master/normalize.css#L347-L349).

### The Solution
Adding an additional fallback test attribute to be able to test also attribute selectors.

Example:
`asp-fallback-test-attribute` would be the new additional attribute.
```
<link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
          asp-fallback-test-attribute="hidden"
          asp-fallback-test-property="display"
          asp-fallback-test-value="none"
          asp-fallback-href="~/lib/normalize.min.css" />
```
should be rendered like this:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"/>
<meta name="x-stylesheet-fallback-test" content="" class="" hidden>
<script>!function(a,b,c,d){var e,f=document,g=f.getElementsByTagName("SCRIPT"),h=g[g.length-1].previousElementSibling,i=f.defaultView&&f.defaultView.getComputedStyle?f.defaultView.getComputedStyle(h):h.currentStyle;if(i&&i[a]!==b)for(e=0;e<c.length;e++)f.write('<link href="'+c[e]+'" '+d+"/>")}("display","none",["\/lib\/normalize.min.css"], "rel=\u0022stylesheet\u0022 ");</script>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @XmlmXmlmX.
@NTaylorMullen what do you think?

**Comment by NTaylorMullen** [comment]
Hmmm I definitely think it sounds reasonable. That being said we may need to re-evaluate how the fallback link TagHelper works in its entirety because it utilizes inline script tags which are highly frowned upon and seem to be losing support.

**Comment by pranavkm** [comment]
@NTaylorMullen we spoke about this offline and we wouldn't block accepting this PR because it uses inline script tags. We already use it elsewhere for fallback so this just keeps the pattern.

**Comment by mkArtakMSFT** [comment]
> @NTaylorMullen we spoke about this offline and we wouldn't block accepting this PR because it uses inline script tags

@pranavkm did you talk to @blowdart regarding this?

**Comment by blowdart** [comment]
Oh heck no. This would make it impossible to apply a useful Content Security Policy. Enabling inline scripts is a horrible idea.

**Comment by rynowak** [comment]
We already have this, it isn't new

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
