### ISSUE TITLE
Field level permissions based on data classification

### ISSUE THREAD

**Issue by Tankske** [dotnet/aspnetcore#14120]
### Is your feature request related to a problem? Please describe.
I would like to classify entity properties according to a specific perspective and the manage access to them via permissions based on these classifications. 
EG. I would like to add a GDPR perspective classification (PII or non-PII). Then I would like to specify to certain users, roles or permissions if they are allowed to see PII and/or non-PII data. Another classification is confidentiality (public data, internal data, condifential and or strictly confidential) 

### Describe the solution you'd like
It would be great to have an annotation such as @classify that works in a similar was as @authorize. 

### Additional context
In my opinion, there are 3 levels of security being action (crud-operation), object level and field-property level. This last one is still missing. Views are an option, but it isn't fundamentalky about security, views are about representing behaviour and how you expose data. Not about if you are allowed to expose data. 

Looking forward on feedback about this!

**Comment by blowdart** [comment]
The only facility where we save PII is identity, and [we provide encryption at rest](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2#personal-data), but that's there only if your database doesn't provide it.

What you're asking for is hard to make generic. You could approach it with [resource based authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-2.2), but it's not something we'd introduce a specific approach for.

**Comment by Tankske** [comment]
Hi Barry,

Thx for the feedback. Maybe my view is to simplistic but an annotation is a wrapper of a function, so I thought this could be used on the setters/getters of each property. This won't help with persistance and potential encryption, but can help with access.

Another solution is to implement this security at dB level, but than somehow authentication should be transposed to the dB. I don't know if that is supported. If I'm correct there is only one technical user from an app.

Met vriendelijke groeten,
Yves
________________________________
