### ISSUE TITLE
`UsePathBase` settings ignored for `asp-href-include` and `asp-src-include`

### ISSUE THREAD

**Issue by EduardSergeev** [dotnet/aspnetcore#14136]
### Describe the bug
`UsePathBase` prefix is correctly added to `src` and `href` attributes in Razor pages. I.g. if I configure app with
```
app.UsePathBase("/prefix");
```
then all `src` and `href` attributes in `.cshtml` which use `src ="~/something.."` format are correctly adjusted. For example:
```
<img src="~/images/Logo.png" />
```
becomes
```
<img src="/prefix/images/Logo.png" />
```

However `asp-href-include` is not addjusted. I.e.:
```
<link rel="stylesheet" asp-href-include="~/css/main.*.css" />
```
is converted into
```
<link rel="stylesheet" href="/css/main.8c62a9f4c3aecc43edf4.css">
```

### To Reproduce
1. Using this version of ASP.NET Core: `2.2.6`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @EduardSergeev .
We'll look into this after we're done with the upcoming 3.0 release.

**Comment by EduardSergeev** [comment]
I suspect that the observed behaviour is due to the way `asp-href-include` & `asp-src-include` are handled: looks like the `~` is removed from the path when the attribute is processed (i.e. `"~/css/main.*.css"` is expanded into `"/css/main.8c62a9f4c3aecc43edf4.css"`) and for this kind of absolute path `UsePathBase` has no effect. If `~` were preserved during the expansion the resulting path `"~/css/main.8c62a9f4c3aecc43edf4.css"` would be correctly handled by `UsePathBase`.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
