### ISSUE TITLE
asp.net core 3.0 rc1 hangs when using the wrong Logging settings

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/aspnetcore#14135]
### Describe the bug
Recently upgraded my project to asp.net core 3.0 rc1 and noticed it would hang when in production environment. Upon further investigation I found that I had old logging settings since I've been upgrading from older .net core versions

### To Reproduce
1. Create a new web application (asp.net core 3.0 rc1)
2. in appsettings.json and appsettings.development.json change the logging to this:
```json
"Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  }
```
3. Run the application using `dotnet run`
4. The process hangs and there is no output, no way of knowing what the issues

### Expected behavior
Perhaps an indication about what the problem is? Couldn't work out where the issue was. Could easily miss the logging settings upgrades that were required. It probably should run with defaults if they aren't defined?

The issue is very hard to track down and isolate, perhaps it can help others who are upgrading their projects. Is this documented somewhere?

**Comment by davidfowl** [comment]
I don't think anything is hanging, it's just not printing any output so maybe it looks like it's hanging? We now log everything through the logging (which is why the default template includes `"Microsoft.Hosting.Lifetime": "Information"` by default).

**Comment by dotnetshadow** [comment]
@davidfowl Yep you are right, hanging is probably the wrong word to use.
