### ISSUE TITLE
Testing HTTP protocol

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#14141]
Today `HttpRequest.Protocol` is a string. That makes testing the protocol version of a request difficult/error prone.

```cs
if (Request.Protocol != "HTTP/2" && Request.Protocol != "HTTP/2.0")
{
    // Throw an error that HTTP/2 is required
}
```

Consider exposing a `Version` or some other object with integer version numbers to test against.

```cs
if (Request.ProtocolVersion.MajorVersion != 2)
{
    // Throw an error that HTTP/2 is required
}
```

Related: https://github.com/aspnet/AspNetCore/issues/14139

**Comment by Tratcher** [comment]
Or at least some helper methods like `IsHttp2()`?

**Comment by Tratcher** [comment]
We could also add shared constants for these like we have with header names. That helps avoid some of these inconsistencies and makes equality checking faster.

**Comment by JamesNK** [comment]
`IsHttp2()` would be an improvement but it wouldn't scale into the future. What happens when HTTP/3 is a thing. I'm thinking of gRPC which will probably have a HTTP/3 implementation or compatibility.

```cs
if (Request.ProtocolVersion.MajorVersion < 2)
{
    // Throw an error that HTTP/2 or HTTP/3 is required
}
```

I think this would be worth considering once HTTP/3 on Kestrel is a thing.

**Comment by anurse** [comment]
> it wouldn't scale into the future

I'm actually more concerned that exposing a version number and expecting people to assign semantics to it is **less** future-proof. HTTP protocol versioning is beyond our control. I think I'd prefer explicit extension methods, but I could be convinced.

Either way, this seems like a reasonable proposal. We'll need an API shape proposal to approve to move forward.

**Comment by JamesNK** [comment]
Fixed with https://github.com/dotnet/aspnetcore/pull/18049
