### ISSUE TITLE
Blazor WebAssembly dotnet run --pathbase=/ doesn't work

### ISSUE THREAD

**Issue by jefflangston** [dotnet/aspnetcore#14152]
When deploying our Blazor WebAssembly app we have the base href="/Blazor/" because that is where it will live, but when trying to override that while developing locally using the dotnet run --pathbase=/ I get the following text "The server is configured only to handle request URIs within the PathBase '/'." and I get 404 errors for all the resources.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jefflangston.
We'll investigate this after we're done with the upcoming 3.0 release.

**Comment by mkArtakMSFT** [comment]
Given that we heard no more reports of this for quite a while now, we're moving this issue to the `Backlog`. It will, probably, take some time for us to get to it.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
