### ISSUE TITLE
How can I access the ConnectionContext  from Blazor server-side

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#14167]
Is there a way to do that ?

Thanks....

**Comment by javiercn** [comment]
@enetstudio Thanks for contacting us.

We don't pass in the connection context to Blazor Server-side applications. 

What are you trying to accomplish? Why do you want to have access to the connection context?

**Comment by enetstudio** [comment]
I thank you for the time you took to respond. I'd like to get client information such as IP adress and browser name/version in Blazor server-side.

I read this comment anurse:
For the IP address, you can use the GetHttpContext extension method on ConnectionContext to get an HttpContext and then use the Connection property on there to find the client information.

And this:
#944 added better support for getting Client IP data, and the rest is all available off the HttpContext via the ConnectionContext.GetHttpContext method.

Link: https://github.com/aspnet/SignalR/issues/1114

But not a word about how to access ConnectionContext.

Once again, I want to get client information such as IP address and browser name/version in Blazor server-side...

Many thanks...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @enetstudio.
There is no a good way to do this at the moment. We will look into how we can provide make this information available to the client.

**Comment by Andrew-Pynch** [comment]
@mkArtakMSFT any updates on this? Really need this functionality in my app and would prefer to use native functionality than the weird workarounds with the Javascript interop. 😆

**Comment by javiercn** [comment]
@Andrew-Pynch We recommend you follow the approach described [here](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/additional-scenarios?view=aspnetcore-3.1#pass-tokens-to-a-blazor-server-app) to pass any data you need from the request into the Blazor app
