### ISSUE TITLE
Discussion: Binary breaking change in removal of Microsoft.AspNetCore.Mvc.Components.Prerendering 

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#14174]
**This is the discussion thread for https://github.com/aspnet/Announcements/issues/388 **

## Removal of Microsoft.AspNetCore.Mvc.Components.Prerendering

The assembly `Microsoft.AspNetCore.Mvc.Components.Prerendering` was removed in 3.0-preview 9. This can cause applications compiled against earlier 3.0 previews to fail at runtime even if they are not using this assembly.

### Version introduced

3.0-preview 9

### Old behavior

Applications compiled against 3.0-preview 8 or earlier are able to load `Microsoft.AspNetCore.Mvc.Components.Prerendering`

### New behavior

Application crashes during startup with an exception like:

```

"Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Components.Prerendering, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. File name: 'Microsoft.AspNetCore.Mvc.Components.Prerendering, Culture=neutral, PublicKeyToken=null'    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)    at System.Reflection.Assembly.Load(String assemblyString)    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.<>c.<GetApplicationPartAssemblies>b__8_0(ApplicationPartAttribute name)    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)  
```

### Reason for change

This assembly was part of the Blazor programming model, and the design and layering of these components changed between preview 8 and preview 9.

### Recommended action

Rebuild the application against 3.0 preview 9 or later.

### Category

ASP.NET

### Affected APIs

"Not detectable via API analysis"

---
#### Issue metadata

* Issue type: breaking-change

**Comment by mahabirsingh-kis** [comment]
Rebuilding the application is also not working with .NET Core 3.0
Error: FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Components.Prerendering, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by rynowak** [comment]
@mahabirsingh-kis  - can you open a new issue and provide repro steps so we can investigate? It sounds like something didn't get rebuilt.

**Comment by mkrishna2025** [comment]
Only option is to update from 3.0 to 3.1.. it works for me.
