### ISSUE TITLE
Blazor (Client-Side) URL parameters need more work/testing for Routing

### ISSUE THREAD

**Issue by ericgrantholland** [dotnet/aspnetcore#14236]
I am trying to get information from a url link using Blazor routing. The problem is the router does not allow '/' or '+' characters inside the parameter. A second issue is that there appears to be a maximum url length limit in the router setup. 

@page "/account/resetpassword/{identityPasswordResetToken}" 
<...>some page stuff here<...>
@code {
    [Parameter]
    public string identityPasswordResetToken { get; set; }
}
with the above routing settings in my page and the URL string below, I get a "Bad Request 400" error. If I take off a single 'a' character in the link below, paste it into a browser then the routing works and my page displays fine. 

"http://localhost:53726/account/resetpassword/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

In my use-case, I'm trying to pass a PasswordResetCode Token generated from Microsoft.Identity. Identity generates the token with pluses and slashes Any '+' signs completly crash the page, while a '/' truncates the actual value assigned to the blazor parameter. 

Another use-case might be sending an entire url to a blazor page as a query string param.

I'd suggest adding support for query strings, but looks like it's already planned #11977. 
As for the max-length URL issue, no suggestions.

**Comment by ericgrantholland** [comment]
FYI, for anyone who needs a way around this NOW. I was able to use string manipulation in combination with the NavigationHelper.Uri to get the query parameters. 

It works for any length link and with '+' and '/' characters.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by ericgrantholland** [comment]
I have built a sample client-side blazor project showing the bug and my work-around solution for extracting query parameters. 

My solution to query parameters was to disect the url which can be made available by injecting NavigationManager into the page. 
If you want to see the example, see the "hiddenpagewithqueryparams" page. 

Ok, now to see the error. Run the project and enter the following url:
http://localhost:6006/hiddenpage/01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

Everything should work great. Now add a single character to the end of the above link, here is my sample:
http://localhost:6006/hiddenpage/01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789Z

At this point, you're likely looking at an ugly page saying "Bad Request -Invalid URL"

To prove to you this has nothing to do with the browser, lets try my workaround with 2 query params with lengths greater than the "artificial max". 
Try it out by pasting the ridiculously long link below into the browser:
http://localhost:6006/hiddenpagewithqueryparams?param1=01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789Z&param2=01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789Z2


So it appears there is some kind of artificial max length being applied to router parameter handling. 
This makes router parameters error prone for my use-case of passing a Microsoft.Identity password-reset token or email verification token into a URL because the length of these tokens often exceeds the "artificial limit".
Furthermore, the link parameter handling cannot handle and '/' characters or '+' characters, which are also present in the Microsoft.Identity tokens generated for password reset and email verification. 

To get around all of this, I'm using my queryParamHelper class, which is working with the '/' and '+' characters and has no max-length issues. 


Hope this helps explain the issue better, let me know if you need anything else. 

[BlazorApp1.zip](https://github.com/aspnet/AspNetCore/files/3650518/BlazorApp1.zip)

**Comment by Cameron097** [comment]
> FYI, for anyone who needs a way around this NOW. I was able to use string manipulation in combination with the NavigationHelper.Uri to get the query parameters.
> 
> It works for any length link and with '+' and '/' characters.

Just to add to this, I think the NavigationHelper object has been changed to NavigationManager.
You can use the static UriHelper class, passing in the Uri to seperate it and get the query params.
You can then use the static QueryHelpers class to parse the query string into it's key value pairs.

For building the Uri for a email confirm/password reset link you can also use the Uri helper class to build the Uri.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
