### ISSUE TITLE
TagHelper tag coloring

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14270]
Enable dynamic coloring of TagHelper elements. VSCode uses text mate grammars to accomplish coloring which will make this especially difficult. However, there is a portion of the language server protocol being developed that adds dynamic colorization.

**Comment by NTaylorMullen** [comment]
VSCode has some proposed APIs for this (not part of the LSP spec yet): https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/dotnet/aspnetcore-tooling/pull/1686.
