### ISSUE TITLE
Update TextMate grammar to properly represent Razor content.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14287]
Right now we're re-using the built-in Razor TextMate grammar but it has its own flaws. One of which is the following end `</p>` tag is not colored correctly: `<p>@DateTime.Now</p>`

----------------------

# Updates after initial release
Have done a lot of work to get the Razor grammar into a usable state for most scenarios. That being said there are several known things I still haven't done:

- [x] Markin in functions
![image](https://user-images.githubusercontent.com/2008729/70840782-9a257700-1dc9-11ea-9b76-fdb379b9d5ab.png)
- [x] Razor templates
![image](https://user-images.githubusercontent.com/2008729/70397304-fbaea580-19c5-11ea-9bbf-c48e2379bb5a.png)
- [x] await foreach
![image](https://user-images.githubusercontent.com/2008729/70761817-6253fc00-1d03-11ea-9809-98af9b8d2491.png)
- [x] Email addresses 
![image](https://user-images.githubusercontent.com/2008729/70397253-9490f100-19c5-11ea-881e-e058a4470ead.png)
- [x] Nested HTML in non-transitioned C# constructs
![image](https://user-images.githubusercontent.com/2008729/70397327-2993ea00-19c6-11ea-8ce3-dd8071533994.png)

- (Optional) Known TagHelpers. This can technically be done at the semantic colorization level as well
![image](https://user-images.githubusercontent.com/2008729/70397367-842d4600-19c6-11ea-97bc-5ceb6800eed8.png)

- (Optional) TagHelper C# attribute content.This can technically be done at the semantic colorization level as well
![image](https://user-images.githubusercontent.com/2008729/70397436-0ae22300-19c7-11ea-9a30-4342e4d645b1.png)

-------------

## Areas for improvement

- Mark embedded languages in the grammar and extension configuration. This will enable things such as contextual comments (C# comment = `//` or `/* ... */`, or HTML = `<!-- ... -->`) and specific embedded language brace matching/indentation.

- Customize default VSCode themes to make the Razor colorizations more familiar. For instance, in VS the `@` transitions are yellow and the C# bits that follow are distinct from HTML.

**Comment by NTaylorMullen** [comment]
Have done a lot of work to get the Razor grammar into a usable state for most scenarios. That being said there are several known things I still haven't done:

- [ ] Email addresses 
![image](https://user-images.githubusercontent.com/2008729/70397253-9490f100-19c5-11ea-881e-e058a4470ead.png)

- [ ] Razor templates
![image](https://user-images.githubusercontent.com/2008729/70397304-fbaea580-19c5-11ea-9bbf-c48e2379bb5a.png)

- [ ] Nested HTML in non-transitioned C# constructs
![image](https://user-images.githubusercontent.com/2008729/70397327-2993ea00-19c6-11ea-8ce3-dd8071533994.png)

- [ ] Known TagHelpers
![image](https://user-images.githubusercontent.com/2008729/70397367-842d4600-19c6-11ea-97bc-5ceb6800eed8.png)

- [ ] TagHelper C# attribute content
![image](https://user-images.githubusercontent.com/2008729/70397436-0ae22300-19c7-11ea-9a30-4342e4d645b1.png)

**Comment by peterblazejewicz** [comment]
@NTaylorMullen 

- [ ] `@code` blocks (this specific screen comes from Mac OS, but I consider this xplat):

![image](https://user-images.githubusercontent.com/14539/70478621-be3c3c00-1adb-11ea-9efc-176ddde161ef.png)

Where should someone look when considering contr., here or Omnisharp/VSCode?

**Comment by NTaylorMullen** [comment]
@peterblazejewicz this is the correct repo 😄. I've gone ahead and added a lot of colorization support to the next release. Once O# releases (sometime this week) you should see improvements.

**Comment by NTaylorMullen** [comment]
The only pieces of the grammar that are yet to be completed are intermingling HTML into deep C# structures. This is tracked by  microsoft/vscode-textmate#122, microsoft/vscode#87496

Now for why, when we hand off the grammar to the C# grammar it doesn't always give us the opportunity to enable HTML constructs. For top level constructs like `@if (...) {` we understand everything in the declaration portion, the keyword, condition and opening brace. This means we can allow for HTML inside of the body (the opening  brace) because we declare what the body allows; however, in the case of:
```C#
@code {
    public void RenerHTML()
    {
        // Content
    }
}
```
we don't understand method declarations (Razor hasn't had a need to understand them). This means when we let the C# grammar parse the body of `@code` it will understand method declarations in their entirety and never unweave to give us the opportunity to "allow" HTML.

The two issues I have filed on VSCode take advantage of a TextMate grammar concept called [injection grammars](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars). Basically I had the idea that we could tie into specific C# constructs with an injection grammar to give us an opportunity to allow HTML. Turns out they don't currently support injections into child grammars, aka when a top-level grammar (aspnetcorerazor) calls into a child grammar (source.cs).

If VSCode isn't willing to fix the issue we'll need to copy the C# grammar wholesale and edit each piece individually. Or if VS' TextMate grammar support doesn't support injection grammars either we'll have to do this as well.

Leaving this issue as blocked until we hear back from the VSCode and VS folks (i've started those conversations).

**Comment by NTaylorMullen** [comment]
Hmm, VSCode's PHP grammar does similar things and they've been able to get this to work. When I have time i'll have to look into this more.

**Comment by NTaylorMullen** [comment]
Heard back from VSCode folks and if we change how we inject we can get this to work. Unblocking

**Comment by NTaylorMullen** [comment]
Syntactic colorization work complete!
