### ISSUE TITLE
Restart LanguageServer when configuration values change.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14280]
Need to make our server shut down and restart when config changes.

**Comment by ryanbrandenburg** [comment]
#Stolen

**Comment by ryanbrandenburg** [comment]
#Unstolen

**Comment by ajaybhargavb** [comment]
What is the value in doing this given the work we did to sync config from the client?

**Comment by NTaylorMullen** [comment]
Hmm, good question. Honestly at this point it'd probably just be for dev scenarios

**Comment by ajaybhargavb** [comment]
Spoke offline. What we want here is for certain configuration changes like Razor.Trace, we'll display a dialog to the user prompting them to restart.
