### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#14297]

**Comment by NTaylorMullen** [comment]
Bringing this into the next release to encompass updating our README.md bits to include running of Razor VSCode

**Comment by NTaylorMullen** [comment]
@danroth27 do you recall what you wanted in the readme to be updated? I know this is asking you to time travel a bit since this was over a year ago but thought I'd ask 😄

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg assigning this to you since you already have this done in your PR 😄

**Comment by danroth27** [comment]
> @danroth27 do you recall what you wanted in the readme to be updated?

Nope 😝. Maybe this was to track updating the readme for the VS Code C# extension for the new Razor support?

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg this done?

**Comment by ryanbrandenburg** [comment]
At least somewhat as of https://github.com/dotnet/aspnetcore-tooling/commit/9f4528d415cd230d2542b0368319018683440a7c. We can call that good for now and if anyone comes up with more concrete suggestions we can create a new issue.
