### ISSUE TITLE
Opening Razor documents outside of workspace results in error.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14304]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce
1. Open a workspace
2. Ctrl + o => open another Razor file outside of the workspace

#### Description of the problem:

Expected behavior:
You get misc document behavior

Actual behavior:
Exceptions get thrown and you get 0 completions.

@danroth27 leaving this up to you to determine which milestone / priority this should fall in.

**Comment by NTaylorMullen** [comment]
This may be a medium depending on why things are breaking

**Comment by NTaylorMullen** [comment]
Tried this out and it works way better than I expected. Lol you even get FAR for the current file

**Comment by ajaybhargavb** [comment]
And formatting works too which is super surprising 😆
