### ISSUE TITLE
HTML completions should be able to be auto-completed by `>`

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14303]
#### Is this a Bug or Feature request?:
Feature

#### Steps to reproduce
Get Html completion, type `>` as the auto-complete character (instead of tab)

#### Description of the problem:

Expected behavior:
tag is completed with the ending `>`

Actual behavior:
completion item is ignored and `>` gets stuck wherever the cursor currently was.

**Comment by allisonchou** [comment]
I believe this is now fixed in the new editor, closing out the issue.
