### ISSUE TITLE
Add support for contextual Razor comments

### ISSUE THREAD

**Issue by fenati** [dotnet/aspnetcore#14320]
## Is this a Bug or Feature request?:
Bug

## Steps to reproduce
1. Open a .razor file, and navigate to the @ functions block.
2. Use the "Add Line Comment" command of the VSCode command palette when cursor is inside the @ functions block.

## Description of the problem:

Expected behavior:
The selected line(s) should be commented out using the C# comment syntax (// ...something...)

Actual behavior:
The selected lines(s) are commented out using HTML comment syntax (&lt;!-- ...something... --&gt;)

#### OmniSharp
Starting OmniSharp server at 4/24/2019, 5:56:57 PM
    Target: /home/fna/Documents/playground/test

OmniSharp server started with Mono 5.20.1.
    Path: /home/fna/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 28314

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 18.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/home/fna/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/usr/lib/mono/msbuild/15.0/bin"
            CscToolExe = csc.exe
            CscToolPath = /home/fna/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/fna/Documents/playground/test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/fna/Documents/playground/test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/fna/Documents/playground/test/test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/fna/Documents/playground/test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/fna/Documents/playground/test/test.csproj
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/fna/Documents/playground/test' on host 28217.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/fna/Documents/playground/test/test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/fna/Documents/playground/test/test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: test

#### Razor
<details><summary>Expand</summary>
<p>

```
[Client - 5:57:21 PM] -- Starting Issue Data Collection-- 
[Client - 5:57:27 PM] Notifying document '/home/anonymous/Documents/playground/test/Pages/Index.razor' changed 'htmlChanged'
[Client - 5:57:27 PM] Notifying document '/home/anonymous/Documents/playground/test/Pages/Index.razor' changed 'htmlChanged'
[Client - 5:57:27 PM] Updating the C# document for Razor file '/home/anonymous/Documents/playground/test/Pages/Index.razor' (2)
[Client - 5:57:27 PM] Notifying document '/home/anonymous/Documents/playground/test/Pages/Index.razor' changed 'csharpChanged'
[Client - 5:57:32 PM] -- Stopping Issue Data Collection-- 
```

</p>
</details>

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

Counter = @counter

<SurveyPrompt Title="How is Blazor working for you?" />

@functions {
    <!-- int counter = 0; -->
}
```

</p>
</details>

#### Projected CSharp document:
<details><summary>Expand</summary>
<p>

```C#
////////////////////// Projected CSharp as seen by extension ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace test.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#line 1 "/home/anonymous/Documents/playground/test/_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#line 2 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#line 3 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.AspNetCore.Components.Layouts;

#line default
#line hidden
#line 4 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#line 5 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#line 6 "/home/anonymous/Documents/playground/test/_Imports.razor"
using test;

#line default
#line hidden
#line 7 "/home/anonymous/Documents/playground/test/_Imports.razor"
using test.Shared;

#line default
#line hidden
    [Microsoft.AspNetCore.Components.Layouts.LayoutAttribute(typeof(MainLayout))]
    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public class __generated__Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
#line 1 "/home/anonymous/Documents/playground/test/Pages/Index.razor"
global::System.Object __typeHelper = "/";

#line default
#line hidden
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
#line 7 "/home/anonymous/Documents/playground/test/Pages/Index.razor"
     __o = counter;

#line default
#line hidden
            __o = "";
            builder.AddAttribute(-1, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment)((builder2) => {
            }
            ));
#line 9 "/home/anonymous/Documents/playground/test/Pages/Index.razor"
__o = typeof(SurveyPrompt);

#line default
#line hidden
        }
        #pragma warning restore 1998
                    
    
                                     

    }
}
#pragma warning restore 1591



////////////////////// Projected CSharp as seen by VSCode ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace test.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#line 1 "/home/anonymous/Documents/playground/test/_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#line 2 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#line 3 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.AspNetCore.Components.Layouts;

#line default
#line hidden
#line 4 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#line 5 "/home/anonymous/Documents/playground/test/_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#line 6 "/home/anonymous/Documents/playground/test/_Imports.razor"
using test;

#line default
#line hidden
#line 7 "/home/anonymous/Documents/playground/test/_Imports.razor"
using test.Shared;

#line default
#line hidden
    [Microsoft.AspNetCore.Components.Layouts.LayoutAttribute(typeof(MainLayout))]
    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public class __generated__Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
#line 1 "/home/anonymous/Documents/playground/test/Pages/Index.razor"
global::System.Object __typeHelper = "/";

#line default
#line hidden
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder builder)
        {
#line 7 "/home/anonymous/Documents/playground/test/Pages/Index.razor"
     __o = counter;

#line default
#line hidden
            __o = "";
            builder.AddAttribute(-1, "ChildContent", (Microsoft.AspNetCore.Components.RenderFragment)((builder2) => {
            }
            ));
#line 9 "/home/anonymous/Documents/playground/test/Pages/Index.razor"
__o = typeof(SurveyPrompt);

#line default
#line hidden
        }
        #pragma warning restore 1998
                    
    
                                     

    }
}
#pragma warning restore 1591

// 5
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
////////////////////// Projected Html as seen by extension ///////////////////////
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

Counter = @counter

<SurveyPrompt Title="How is Blazor working for you?" />

@functions {
    <!-- int counter = 0; -->
}


////////////////////// Projected Html as seen by VSCode ///////////////////////
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

Counter = @counter

<SurveyPrompt Title="How is Blazor working for you?" />

@functions {
    <!-- int counter = 0; -->
}
// 3
```

</p>
</details>

## Machine information

**VSCode version**: 1.33.1
**Razor.VSCode version**: 1.19.0
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/anonymous/dotnet/sdk/3.0.100-preview4-011223/

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  3.0.100-preview4-011223 [/home/anonymous/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [/home/anonymous/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [/home/anonymous/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>

|Extension|Author|Version|
|---|---|---|
|Angular-BeastCode|Mikael|8.0.3|
|angular2-inline|natewallace|0.0.17|
|csharp|ms-vscode|1.19.0|
|debugger-for-chrome|msjsdiag|4.11.3|
|docomment|k--kato|0.1.6|
|docthis|joelday|0.7.1|
|gc-excelviewer|GrapeCity|2.1.32|
|githistory|donjayamanne|0.4.6|
|html-snippets|abusaidm|0.2.1|
|msbuild-project-tools|tintoy|0.2.54|
|ng-template|Angular|0.1.11|
|svg|jock|0.1.4|
|svg-snippets|sidthesloth|1.0.1|;

</p>
</details>

**Comment by NTaylorMullen** [comment]
We have yet to add support for contextual comments. This will be added in a future release.

**Comment by minestarks** [comment]
@NTaylorMullen since this is blocking JS commenting in Razor, is there an ETA for this item? Thanks!

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen since this is blocking JS commenting in Razor, is there an ETA for this item? Thanks!

16.9-P3 currently

**Comment by NTaylorMullen** [comment]
16.10-P1 is the updated target

**Comment by allisonchou** [comment]
I'm going to mark this as blocked for now on https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1169191/.
We are pushing for prioritization on the Editor side so we can hopefully continue work on this issue in the near future.

**Comment by Haraldi-Coding** [comment]
What I really don't understand: On my other computer having Visual Studio Enterprise 2019 Preview Version 16.9.0 Preview 2.0 installed it is working. Why? (For me that means that I will not update this computer).

But: Computer with Preview 2.0 is an "old" computer, that means having Visual Studio Enterprise and Preview installed, both updated for a long time. The computer where it is not working now with (now) Preview 5.0 is "brand new", only the preview is installed and not the normal VS Enterprise.

Is there anything else that I am missing? Can we get some clarifications why it has worked and now no longer works? Has this something to do with the parallel installation of the working VS Enterprise instance?

**Comment by NTaylorMullen** [comment]
@Haraldi-Coding I'm so sorry for the frustrating experience! We're currently in the midst of experimenting with a new experimental Razor editor (started turning it on in 16.9-Preview3+) to enable things like light bulbs, better formatting, better Blazor refactorings etc; however, it doesn't currently support contextual Razor comments (coming in 16.10). For the interim if you'd like to get your contextual Razor commenting back you can uncheck the experimental Razor editor checkbox listed here:

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

That being said I'd highly suggest turning it back on once 16.10 is released because I'd bet you'll have a superior Razor editing experience because of it 😄
