### ISSUE TITLE
Cannot get C# IntelliSense for FormTagHelper asp-antiforgery

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14335]
Trying to get completions here: `<form asp-antiforgery="tr|">` doesn't seem to work according to this: https://github.com/aspnet/Tooling-ManualTests/pull/561

**Comment by ryanbrandenburg** [comment]
If I do `<form asp-antiforgery="tr` and just wait there's no suggestions, but I do get true as the first suggestion if I do `Ctrl+SPACEBAR`. Is that the correct scenario?

**Comment by NTaylorMullen** [comment]
I believe so. Seems like we may have fixed this one. I'd review the CTI test plans linked above to ensure that a similar test-case is not skipped because of the belief that it's still broken

**Comment by ryanbrandenburg** [comment]
https://github.com/aspnet/Tooling-ManualTests/pull/809 is closed, so we're good here.
