### ISSUE TITLE
Assembly "foo.dll" does not contain an entrypoint

### ISSUE THREAD

**Issue by jocco** [dotnet/aspnetcore#14370]
### Describe the bug
After upgrading to dotnet core 3 I get a build error 
`GenerateOpenApiDocuments:
dotnet "C:\Users\joakim.lindqvist\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "foo.dll" --file-list "obj\foo.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "Foo" --assets-file "...\obj\project.assets.json" --platform "AnyCPU"
2>Assembly 'foo.dll' does not contain an entry point.`

This assembly is a class library and as such can not define an entrypoint (and a error is produced if I try to ad it), but it contains code shared between multiple aspnet web api projects (all of whom generate swagger documentation).

While this GenerateOpenApiDocuments step fails, my assembly generates just fine so if I do another build the up to date check determine there is no work to do and my build succeeds.

I did not see this issue using dotnet core 3 preview 7.

### To Reproduce
1. Using Aspnet Core 3
2. Add a class library that uses swagger (I use Swashbuckle.AspnetCore and Swashbuckle.Aspnet.Core.ReDoc). This class library should be set to use Web SDK:
`Project Sdk="Microsoft.NET.Sdk.Web">`

3. Build this class library

### Expected behavior
No build errors.

**Comment by Dontrym3** [comment]
I had the same problem also. A quick fix for the build is to not generate the openApi documents. Add this to your project's propertyGroup (in the .csproj):     
```
<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
```

**Comment by mkArtakMSFT** [comment]
@rafikiassumaniMSFT FYI

**Comment by adityamandaleeka** [comment]
cc: @bradygaster

**Comment by bradygaster** [comment]
what @Dontrym3 said - Swashbuckle in Class Library projects isn't a scenario with which we're quite familiar or that we support. The only scenario with which we have elaborate expertise is using Swashbuckle in a Web or Minimal API project. The package does offer quite a bit of customization, and has some good docs, so I'd encourage folks look there.

**Comment by adityamandaleeka** [comment]
Sounds like this should be closed then?

**Comment by bormm** [comment]
Had the same issue:
- It works before with "<TargetFramework>net472</TargetFramework>" 
- but not with "<TargetFramework**s**>net472</TargetFramework**s**>" 
- and not with "<TargetFramework>net5.0</TargetFramework>" 
- and not with "<TargetFrameworks>net5.0</TargetFrameworks>" 

And failed in "...\packages\microsoft.extensions.apidescription.server\3.0.0\build\Microsoft.Extensions.ApiDescription.Server.targets"

Having a class library seems a common use-case in a modular application. Did you expect all related stuff is just put in a single project?

I disabled build time generation by "OpenApiGenerateDocumentsOnBuild=false" I've found in the targets, but have not found any documentation about this parameter and what it exactly does. Also comparing to OpenApiGenerateDocuments=false.

Can someone give a link?

**Comment by adityamandaleeka** [comment]
Closing this issue since as @bradygaster said this isn't a scenario we support.
