### ISSUE TITLE
Verifying usage of HTTPClientFactory from a Command line application that leverages DI

### ISSUE THREAD

**Issue by scalablecory** [dotnet/aspnetcore#14398]
_From @ajopjo on Friday, August 30, 2019 1:34:16 PM_

# Issue Title

I haven't find any directions regarding usage of HTTPClientFactory from a command line application. 

This is **NOT an issue**. I'm submitting this ticket to verify the approach is correct. I have attached the code snippet below. 

# General

```c#
 var builder = new HostBuilder()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHttpClient();
                    services.AddSingleton<CommandArgsMapper>();
                    services.AddSingleton<IInvalidationService, InvalidationService>();
                }).UseConsoleLifetime();

            var host = builder.Build();

            using (var serviceScope = host.Services.CreateScope())
            {
                var mapper = serviceScope.ServiceProvider.GetRequiredService<CommandArgsMapper>();
                var cmdValues = mapper.Map(args);
                var service = serviceScope.ServiceProvider.GetRequiredService<IInvalidationService>();
                            }

            host.Run();
```

_Copied from original issue: dotnet/core#3284_

**Comment by Pilchie** [comment]
@rynowak ?

**Comment by rynowak** [comment]
This seems like what I'd expect 👍 

Though this question has much more to do with hosting/di than anything. @Tratcher - do we have docs for this?

**Comment by Tratcher** [comment]
Docs for what, generic host?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0
