### ISSUE TITLE
CSHTML file not refreshing

### ISSUE THREAD

**Issue by scalablecory** [dotnet/aspnetcore#14430]
_From @justlearntutors on Wednesday, September 25, 2019 10:41:37 AM_

I make a change in a .cshtml file. I refresh the browser. I don't see the change. I rebuild the application. I see the change. It worked in asp net core 2.2.

How to solve?

https://stackoverflow.com/questions/54106058/why-does-page-not-update-after-refresh-when-cshtml-changes

_Copied from original issue: dotnet/core#3467_

**Comment by pranavkm** [comment]
@justlearntutors as part of 3.0, runtime compilation is not available by default and MVC relies on Visual Studio's rebuild behavior to refresh the file. The response in the linked StackOverflow issue (https://stackoverflow.com/a/54110388) summarizes why these file changes aren't picked up. I

f you'd like to continue seeing the 2.x behavior, you'd have to enable runtime compilation in your MVC project: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#opt-in-to-runtime-compilation. I would recommend reading through the entirety of the migration guide to identify any other changes in 3.0 that might affect your application.

**Comment by justlearntutors** [comment]
Okay. We found a solution.
`if (Startup.IsLocalhost)
{
services.AddControllersWithViews().AddRazorRuntimeCompilation();
} else {
services.AddControllersWithViews();
}`

Will you fix the issue in 3.1?

**Comment by pranavkm** [comment]
@justlearntutors this is an intentional change. Your solution looks like what we'd recommend in 3.0.

**Comment by woeterman94** [comment]
> AddRazorRuntimeCompilation

AddRazorRuntimeCompilation() does not exist in the current context? How did you fix it?

**Comment by pranavkm** [comment]
> if you'd like to continue seeing the 2.x behavior, you'd have to enable runtime compilation in your MVC project: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#opt-in-to-runtime-compilation. I would recommend reading through the entirety of the migration guide to identify any other changes in 3.0 that might affect your application.
