### ISSUE TITLE
Razor should not use PATH to find dotnet.exe

### ISSUE THREAD

**Issue by wli3** [dotnet/aspnetcore#14432]
Razor should not use PATH to find dotnet.exe. It is not reliable. 

https://github.com/aspnet/AspNetCore-Tooling/blob/2e70e0cbd7d8b952313d1114cd750befca2b1453/src/Razor/src/Microsoft.NET.Sdk.Razor/DotnetToolTask.cs#L61

Here is the linker's example. Use `DOTNET_HOST_PATH` on core. And use $(NetCoreRoot) with dotnet/dotnet.exe on fullframework. I believe $(NetCoreRoot) property is also available for Razor props and targets (please double check)

https://github.com/dotnet/sdk/blob/46917a9b622ea05377dc438db9f6b6e184bd3d83/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L78

cc @nguerrera

**Comment by pranavkm** [comment]
Thanks @wli3. Should this - https://github.com/dotnet/sdk/issues/20 - be closed as resolved since there's a solution for it now?

**Comment by wli3** [comment]
yes. I closed it

**Comment by rynowak** [comment]
Spoke with @nguerrera about this. We should fix this and we now know what to do 👍 - @wli3 do we have any user reports of this?

**Comment by wli3** [comment]
no, we caught it in our tests.
