### ISSUE TITLE
DataTokens from EndpointRouting are not available in ActionMethodSelectorAttribute

### ISSUE THREAD

**Issue by mariuszkochanowski** [dotnet/aspnetcore#14446]
Description:
Collection DataTokens in ActionMethodSelectorAttribute is empty when using EndpointRouting.
To reproduce:
[RouteDataSamples.zip](https://github.com/aspnet/AspNetCore/files/3655057/RouteDataSamples.zip)

Solution contains two projects: 
1) MvcClassicRouting - runs without error
2) MvcEndpointRouting - throws exception in class CustomActionMethodSelectorAttribute
because Collection DataTokens is empty

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
