### ISSUE TITLE
Better on typing completion triggers

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#14445]
Visual studio has the ability to auto-trigger completion when typing in a document. We should implement a similar experience so the implicit experience for typing results in quality completions.

**Comment by rynowak** [comment]
What does this mean?

**Comment by NTaylorMullen** [comment]
> What does this mean?

This is the idea that every point in which VS auto-triggers completion, aka you're typing `<input |` and once you hit the `space` after `input` to auto-trigger the completion. This is just one example. This item also includes figuring out any other scenarios which make sense to light up for completion auto-trigger.

**Comment by allisonchou** [comment]
I believe this is addressed in the new editor.
