### ISSUE TITLE
Data annotation localizaton  in blazor client app

### ISSUE THREAD

**Issue by swordream** [dotnet/aspnetcore#14493]
Just like the asp.net core mvc apps, using AddDataAnnotationsLocalization to provide Data annotation localizaton.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @swordream.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by SteveSandersonMS** [comment]
Closing as implemented (a long time ago).
