### ISSUE TITLE
How can I use Microsoft.AspNetCore.Mvc.Internal.ActionSelector in ASP.NET Core 3.0/.NET Core 3.0 or alternative solution in Core 3.0? 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#14512]
_From @Microshaoft on Friday, September 27, 2019 7:04:36 AM_

reference MSDN:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.internal.actionselector?view=aspnetcore-2.2

c# code in .NET Core 2.2, for your reference:

https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net.4x/blob/aace0a952433f09d24d5977ad7fae7adf40a18d4/CommonUtilities.Shared/WebApi.Common.Controllers/SyncAsyncActionSelector.cs#L8

_Copied from original issue: dotnet/corefx#41381_

**Comment by pranavkm** [comment]
@Microshaoft the type was made internal as was announced in https://github.com/aspnet/Announcements/issues/326. If you'd like direct parity, I would recommend copying the code in your application - https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.Core/src/Infrastructure/ActionSelector.cs. 

I'm having a hard time following your customization in the code that you pointed out, but  I suspect you could use an `ActionConstraint` to influence action selection. Have a look at https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Mvc/Mvc.WebApiCompatShim/src/OverloadActionConstraint.cs#L21, it's fairly likely something like this would be enough rather than plugging in a custom selector.

**Comment by Microshaoft** [comment]
@pranavkm both ActionConstraint  and ActionSelector are NOT Supported in ASP.NET Core 3.0.

I want control the request be routed one WebApi Controller action method, when I set same one [Route("XXXX")] to multiple method, such as one method is Sync , another method is Async, and then I want use Custom ActionSelector to control select Sync or Async version method, these two method are almost same, except Async/Sync.

Sync method ProcessActionRequest:

https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net.4x/blob/cc425887db5a8bbfad9e07ae4d2ea6948a31bf03/CommonUtilities.Shared/WebApi.Common.Controllers/StoreProcedureExecutorController/AbstractStoreProcedureExecutorControllerBase.3.NET.Core.Standard.cs#L225

Async method ProcessActionRequestAsync:

https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net.4x/blob/cc425887db5a8bbfad9e07ae4d2ea6948a31bf03/CommonUtilities.Shared/WebApi.Common.Controllers/StoreProcedureExecutorController/AbstractStoreProcedureExecutorControllerBase.3.NET.Core.Standard.cs#L323

the above two methods use same route attribute:

```
#if !NETCOREAPP3_X
        [HttpDelete]
        [HttpGet]
        [HttpHead]
        [HttpOptions]
        [HttpPatch]
        [HttpPost]
        [HttpPut]
        [
            Route
                (
                    "{routeName}/"
                    + "{resultJsonPathPart1?}/"
                    + "{resultJsonPathPart2?}/"
                    + "{resultJsonPathPart3?}/"
                    + "{resultJsonPathPart4?}/"
                    + "{resultJsonPathPart5?}/"
                    + "{resultJsonPathPart6?}"
                )
        ]
        [
            Route
                (
                    "export/{routeName}/"
                    + "{resultJsonPathPart1?}/"
                    + "{resultJsonPathPart2?}/"
                    + "{resultJsonPathPart3?}/"
                    + "{resultJsonPathPart4?}/"
                    + "{resultJsonPathPart5?}/"
                    + "{resultJsonPathPart6?}"
                )
        ]
#endif
```

would you give more help? @pranavkm

**Comment by Microshaoft** [comment]
@pranavkm  @mkArtakMSFT thanks for your feedback. Will you plan to migrate it to . Net Core 3.x recently?

**Comment by mkArtakMSFT** [comment]
No plans to do this in 3.1 timeframe.

**Comment by Microshaoft** [comment]
how about postponed plan or not at all ? @mkArtakMSFT

**Comment by Microshaoft** [comment]
@pranavkm @mkArtakMSFT after .NET Core 3.1 released, when will the feature be back?

**Comment by Microshaoft** [comment]
with @pranavkm help and tips
I have implemented the feature of Sync or Async action selection by using custom ActionConstraint, custom ApplicationModelProvider, custom RouteAttribute.

https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net.4x/tree/master/CommonUtilities.Shared/WebApi.Common.Controllers/Constraint

https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net.4x/blob/86f7822e359e25e85bbf79df5af53d51aa85690b/Samples/MsSqlCodeDiffVersioning/MsSqlCodeDiffVersioning.Shared/Startup.cs#L83

thanks @pranavkm
