### ISSUE TITLE
CSRF antiforgery token not being in different sessions

### ISSUE THREAD

**Issue by mtinnes** [dotnet/aspnetcore#14521]
Generated tokens are identical between sessions. We are calling `antiForgery.GetAndStoreTokens(HttpContext);` on login and are getting the same token for the same user. Seems the token generation is based on user identity only. Is there a way to add more randomness (salt) to the token generation?

### To Reproduce
1. Using this version of ASP.NET Core '3.0'
2. Run this code 'var tokens = _antiForgery.GetAndStoreTokens(HttpContext);'
3. Returned token is identical between sessions for the same user id

### Expected behavior
A new token should be generated each time based on some randomness.

### Additional context
The method generating the token is a WebAPI method called via XHR from a SPA web app. There is no form provided in the HttpContext.

**Comment by blowdart** [comment]
No there isn't. This is by design so it's not dependent on sessions or anything else.

**Comment by mtinnes** [comment]
Maybe provide a method to invalidate the current token causing it to regen the next time around? This way we could manually invalidate on logout.

**Comment by pranavkm** [comment]
At this time we're not considering adding the suggested feature. Closing this as we haven't seen more feedback from our users.
