### ISSUE TITLE
How do we explicitly handle formatting for only the content type desired when using a custom OutputFormatter?

### ISSUE THREAD

**Issue by casperOne** [dotnet/aspnetcore#14559]
Some background:

This is in the context of writing a custom `OutputFormatter` for OData.  OData uses derived instances of `OutputFormatter` which do things like check if the output is for an OData request, etc.

An interesting thing about OData; the specification says that the query string can define a `$format` parameter to define the format of the returned data.

This is a little similar to the `FormatFilterAttribute`, with the exception that this is defined in the query string.

That said, the implementation of OData places their formatters at the head of the output formatter chain (when the call to `AddOData` is made in DI, and just as the [documentation](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-2.1) states they should).

The problem is this: the default implementation of `OutputFormatter.CanWriteResult` assumes that when no content type is specified, that the handler will of course want to handle this.  This is reflected in the implementation, in that it sets the `ContentType` of the `OutputFormatterCanWriteContext` as well as returns true from the method.

In the scenario where we want to look at other factors for negotiating content type (like the `$format` query string parameter in OData) in addition to standard content type negotiation, there is no clean way to defer to the base class implementation of `OutputFormatter` without buying into this idea that if a content type isn't specified, we want to handle it.

That said, I can get around this by copying most of the code from `OutputFormatter` into my class, but that seems a little unwieldy and brittle; it would be better if the `CanWriteResult` method returned a tuple of a boolean and a content type that should be used.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @casperOne .
You can either write a filter or a middleware, that reads the `$format` querystring and sets the header accordingly.

For the other part of your feedback below, feel free to send us a PR that adds a flag to the OutputFormatter and we'll happily consider it.

> The problem is this: the default implementation of OutputFormatter.CanWriteResult assumes that when no content type is specified, that the handler will of course want to handle this. This is reflected in the implementation, in that it sets the ContentType of the OutputFormatterCanWriteContext as well as returns true from the method.

**Comment by pranavkm** [comment]
We're closing this issue as we haven't seen additional interest or engagement from the community.
