### ISSUE TITLE
Can we have an icon for RCL?

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#14557]
Seems underwhelming?

![image](https://user-images.githubusercontent.com/1430011/65823453-7c556680-e20b-11e9-9fbc-492959f34060.png)

@danroth27 @SteveSandersonMS - thoughts?

**Comment by SteveSandersonMS** [comment]
I too would like to see a cool icon here.

**Comment by AngelosP** [comment]
Icon request [submitted](https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/8484)
