### ISSUE TITLE
UseHealthChecks ResponseWriter ContentType is not set

### ISSUE THREAD

**Issue by matjazmav** [dotnet/aspnetcore#14553]
I have implemented custom JSON `ResponseWriter` for health check endpoint, and registered it in `Startup.cs`:

```cs
        public static Func<HttpContext, HealthReport, Task> ResponseWriter = async (httpContext, healthReport) => {
            await JsonSerializer.SerializeAsync(httpContext.Response.Body, healthReport, typeof(HealthReport), new JsonSerializerOptions {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            });
            httpContext.Response.ContentType = "application/json; charset=utf-8";
            httpContext.Response.StatusCode = healthReport.Status == HealthStatus.Unhealthy ?
                (int)HttpStatusCode.BadRequest :
                (int)HttpStatusCode.OK;
            await httpContext.Response.CompleteAsync();
        };
```

### To Reproduce
1. Register health checks
2. Configure health check endpoint with custom `ResponseWriter`
3. Request health check endpoint & observe response headers

### Expected behavior
`Content-Type` header is set in response message.

### Screenshots
![image](https://user-images.githubusercontent.com/9011654/65822126-416d2600-e23f-11e9-87d5-a977a7a2cfda.png)

### Additional context

```bash
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by matjazmav** [comment]
Also one question, is there any similar implementation included "out of the box"?

**Comment by rynowak** [comment]
Does this work if you set the content type/status code before writing out the response?

> Also one question, is there any similar implementation included "out of the box"?

No we don't include a default serializer for health reports, because the format is different for each system that talks to health checks. We don't have plans to change this unless there emerge industry standard formats.

@Tratcher - any idea why this isn't working?

**Comment by Tratcher** [comment]
Set ContentType and StatusCode before calling SerializeAsync. Those properties should throw exceptions if you set them afterwards.

**Comment by pranavkm** [comment]
Closing this as we haven't heard additional feedback on this.
