### ISSUE TITLE
response caching of authenticated requests

### ISSUE THREAD

**Issue by JonasSamuelsson** [dotnet/aspnetcore#14569]
We are using response caching and enabled caching of authenticated requests by providing our own implementation of `ResponseCachingPolicyProvider`.
As of 3.0 both `IResponseCachingPolicyProvider` & `ResponseCachingPolicyProvider` are now internal and the middleware constructor has been changed (https://github.com/aspnet/Announcements/issues/354, https://github.com/aspnet/AspNetCore/pull/9392).

Any guidance on how to enable this in v3.0 would be greatly appreciated.

**Comment by Tratcher** [comment]
@JunTaoLuo?

**Comment by JunTaoLuo** [comment]
Unfortunately, there's no way to enable this in 3.0 right now. This extension point was not fully designed and we decided to remove it in the 3.0 release. The feature is tracked in https://github.com/aspnet/AspNetCore/issues/2612. We haven't seen a great amount of interest or request for it and so it hasn't been prioritized.

cc @glennc @anurse for awareness

**Comment by JonasSamuelsson** [comment]
will this get any attention in 5.0?

**Comment by Tratcher** [comment]
@JonasSamuelsson we do not plan on investing in this scenario unless we get feedback about it from multiple sources.

**Comment by JunTaoLuo** [comment]
This scenario will be supported by Output Caching: https://github.com/dotnet/aspnetcore/issues/27387
