### ISSUE TITLE
AspNet Core 2.2 routing with MvcRouteHandler, IRouter, etc

### ISSUE THREAD

**Issue by ctaswell** [dotnet/aspnetcore#14565]
Why does Microsoft abandon support for the 2.2 routing with MvcRouteHandler, IRouter, etc when releasing AspNet Core 3.0????  And make it so difficult for us to migrate from 2.2 to 3.0?

There is NO backward compatibility because code like the following does NOT work:

      services.AddMvc(options => { options.EnableEndpointRouting = false; })
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
        .AddNewtonsoftJson(options => { options.SerializerSettings.ContractResolver = new DefaultContractResolver(); });

Setting compatibility version to 2.2 does not make available all of the routing utilities that were available under 2.2.   That's because namespaces like 

using Microsoft.AspNetCore.Mvc.Internal;

have been completely removed from AspNet Core 3.0.  

Why does Microsoft insist on such "churn and burn" WITHOUT maintaining any backward compatility on important namespaces that have been used by many of us developers.  There's NO warning and no deprecation phase, nothing but "churn and burn" that makes our life so difficult to migrate from 2.2 to 3.0 on the MvcRouteHandler and IRouter based MVC routing.

Please restore backward compatibility for 2.2 routing in the next AspNetCore 3.1

**Comment by davidfowl** [comment]
We spent a year developing ASP.NET Core 3.0 and shipped 10 preview versions in order get feedback. We also wrote blog posts explaining the changes that were coming and why we were making them. Do you have any suggestions for what we could do in the future to help make more developers aware of changes like this in the future?

What were you doing before? It's possible there's an easy way forward.

PS: Here are the list of breaking changes in 3.0 https://github.com/aspnet/announcements/issues?q=is%3Aissue+is%3Aopen+label%3A3.0.0+label%3A%22Breaking+change%22.

There are also part of the migration guide here https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

**Comment by davidfowl** [comment]
cc @rynowak

**Comment by ctaswell** [comment]
Solution is simple:  do not rip things out; leave them in; give developers the CONTINUING choice of both the old way and the new way!!!!  Code should NOT have to be changed on a yearly basis.  Old code should work with new code, so that developers can take advantage of new features in new code WITHOUT being forced to abandon the old code.  If there are compatibility switches for 2.1 versus 2.2 versus 3.0, then those switches should actually work!!!  And that requires that enough of the old 2.1 and 2.2 code be maintained side-by-side with the new 3.0 code.  But that's not possible if Microsoft rips out all of the necessary namespaces that make backward compatibility for 2.1 and 2.2 impossible.
