### ISSUE TITLE
JSON Hub protocol is a bit bloated on the wire

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#14564]
The protocol overhead of sending invoking a hub method and getting an empty reply is ~123 bytes.

Request

```JSON
{"arguments":[""],"invocationId":"0","streamIds":[],"target":"send","type":1}
````
Reply

```JSON
{"type":3,"invocationId":"0","result":null}
```

This is for a simple invocation but it also varies for number of arguments specified and different types of invocations. This isn't exactly proportional to the side of the message but we've been a bit lazy here (you can see we send an empty streamIds array even when this isn't a streaming invocation). 

I can think of a few very easy ways to reduce this overhead:
1. Tell people to use messagepak (leave it as is)
2. Do the bare minimum and don't send things like streamIds when they aren't required
3. Use smaller property names (what old SignalR did)

Before and after for number 3:

Request

```
{"arguments":[""],"invocationId":"0","streamIds":[],"target":"send","type":1}
{"a":[""],"i":"0","m":"send","t":1}
```

Reply

```
{"type":3,"invocationId":"0","result":null}
{"t":3,"i":"0","r":null}
```

**Comment by anurse** [comment]
Do we know the perf impact of shrinking this? With real data instead of contrived samples? I'm struggling to figure out what saving 27 bytes gets us, given the cost of updating all the clients and servers.

**Comment by anurse** [comment]
Guess that answers my question 🙃 😝 ❤️

**Comment by davidfowl** [comment]
Reopened out of spite
