### ISSUE TITLE
View InMemory Caching Provider - IViewCompilationMemoryCacheProvider for 3.0

### ISSUE THREAD

**Issue by joetherod** [dotnet/aspnetcore#14575]
The IViewCompilationMemoryCacheProvider is not available in Core 3.0. How can I access the memory store for compiled views in 3.0 now?
My app is tenant based and views are virtualized in the database. I used that interface to get the memory store to force recompilation of views.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @joetherod.
These APIs are not available in 3.0 any more. We'll look into ways to trigger recompilation on-demand.

**Comment by mkArtakMSFT** [comment]
For now you can simulate this by faking file updates. You can use the file provider and trigger the expiration manually from it, which will cause recompilation.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
