### ISSUE TITLE
Add Headers option for TS client

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#14588]
We should add a headers option in `IHttpConnectionOptions` in the TS client. Especially since we're adding the user agent we want to make it easy for users to set their own headers/override our headers.

Note: We need to make sure it's clear that the headers are only applied where possible. For example WebSockets and EventSource in browsers don't let you set headers.

**Comment by anurse** [comment]
Pre-planning notes: It's possible to override HttpClient to do this, right? I recognize that's not ideal (or even particularly good) but I'm trying to identify if there are blocked scenarios. If there aren't blocked scenarios, my feeling is that we leave this in the Backlog and be willing to take a PR (one is already in progress, so we might even land this soon).

**Comment by BrennanConroy** [comment]
Providing an HttpClient should be possible, I even answered a stackoverflow post about this with some pseudo code showing how to do it: https://stackoverflow.com/questions/59652214/how-do-i-add-custom-headers-to-signalrs-typescript-client

**Comment by anurse** [comment]
We can chat more in planning to confirm but given that my gut feeling is Backlog and review existing PR (and/or new PRs if that PR doesn't land)
