### ISSUE TITLE
Visual studio 2019 using too much CPU

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#14590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/549081/visual-studio-2019-using-too-much-cpu.html)._

---
<p>VSF_TYPE_MARKDOWN</p><p>Even when idle, with all extensions disabled, Visual Studio uses too much cpu.</p><p>System info:</p><p>Intel Core I5-2450M - 2.50GHz<br>8GB Ram<br>VStudio installed on SSD</p>

---
#### Visual Studio Feedback System on 4/28/2019, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 5/5/2019, 00:15 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

#### rezination on 7/5/2019, 04:38 AM: 

I'm getting this too.  It's fine for a while, but after a few intense debugging sessions, it gets unusable (86.5% CPU usage). <br><br>CPU: Intel Core i7-4790 3.6 GHz (quad core)<br>RAM: 14 GB<br>Visual Studio is installed on my SSD.<br>Virtual memory file is also on the SSD.

---
### Original Solutions
(no solutions)

**Comment by ryanbrandenburg** [comment]
Moving to here since as per https://devdiv.visualstudio.com/DevDiv/_workitems/edit/887631 a lot of time is being spent in the RazorParser.

**Comment by wgutierrezr** [comment]
I have the same issue since today only. Before VS2019 was working perfectly until the last update to 16.4.4.

Now it is using 75.1% average of my computer:
- I7-8650U 1.90GHz
- 16GB Ram
- 512GB SSD

**Comment by Pilchie** [comment]
@wgutierrezr - I would recommend still filing a VS Feedback ticket where you record the problem happening.  That will record a performance trace that will allow an engineer to confirm that you're actually running into the same Razor parser issue, and not a distinct issue.

This issue is 5 months old, and your issue just started on the latest update, so it seems quite possible that you're running into a distinct issue.

**Comment by allisonchou** [comment]
Given that VS 2022 has been released along with the new editor, I'm going to close out this issue. If you still are experiencing CPU problems, feel free to file another issue.
