### ISSUE TITLE
Update the Baseline Generator to handle Shared Framework package

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#14630]
Before 3.0, we had standalone packages corresponding to every assembly in AspNetCore. Now many of those are only exposed by the shared framework, so the current package baseline file is incomplete. We should update https://github.com/aspnet/AspNetCore/tree/master/eng/tools/BaselineGenerator to handle the shared framework package, then update https://github.com/aspnet/AspNetCore/tree/master/eng & re-run the tool.

CC @dougbu @anurse @Pilchie @JunTaoLuo

**Comment by JunTaoLuo** [comment]
With the tests added in https://github.com/dotnet/aspnetcore/pull/23070 which checks framework contents (runtime and ref) against a static list, we think the coverage may be sufficient to address this issue. There is one more scenario in offline discussion regarding possible changes between framework assemblies and whether we need to verify those.

**Comment by JunTaoLuo** [comment]
Confirmed that we don't need any additional verification.
