### ISSUE TITLE
Blazor datalist binding for autocomplete not working in Edge browser

### ISSUE THREAD

**Issue by blenke** [dotnet/aspnetcore#14648]
### Describe the bug
I made a simple input with datalist autocomplete in Blazor (3.0 RTM). The binding for this does not get set in Edge unless you type something in the input box. Just selecting from the list does not trigger a bind. In Chrome the label gets displayed after the value is selected and the input box loses focus. In Edge this never happens and the variable remains null.
The issue is the same as described here:
https://github.com/aspnet/AspNetCore/issues/5594
However it is not completely fixed. 

### To Reproduce
Example:
```
<input type="text" name="dlinput" list="dl" @bind="@myvar" />
<datalist id="dl">
    <option value="one"></option>
    <option value="two"></option>
    <option value="three"></option>
</datalist>
<label>@myvar</label>
@code
{ 
string myvar;
}

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @blenke.
We'll look into this and will get back to you.

**Comment by donhuvy** [comment]
> The binding for this does not get set in Edge unless you type something in the input box.

exactly, I just tried it.

**Comment by seanjbsol** [comment]
I get the same issue. I'm trying to allow easy selection from a list of values, but also allow new values to be created.

The value does update when changing the field afterwards, but not on the selection, and not on edge. 

`            if (EntityLookup != null)
            {
                <input list="list@(FieldID)" type="text" class="form-control @((!Valid) ? "is-invalid" : "is-valid")" id="@FieldID" placeholder="@FullName" @bind="Value" @attributes="InputAttributes" />
                <datalist id="list@(FieldID)">
                    @foreach (var item in EntityLookup)
                    {
                        @EntityDisplayTemplate(item)
                    }
                </datalist>
            }`

**Comment by enetstudio** [comment]
> In Chrome the label gets displayed after the value is selected and the input box loses focus

When using the @bind directive, you instructs the compiler to use the change  event to update the bound variable. The change event fires when the input element **loses focus** after its value was changed or  when selecting a value from the drop-down with a mouse click. No bug at all. It is by design. If you wish, however, to display the value at each stroke on the keyboard, you should tell the compiler to use the input event instead of the change event as the following:

 <input type="text" name="dlinput" list="dl" @bind="@myvar" @bind:event="oninput" />
  
With regard to Edge, I may add that the painting of the control is problematic as well...

**Comment by blenke** [comment]
Thanks this is working, Bind should not be with upper case though. 
<input type="text" name="dlinput" list="dl" @bind="@myvar" @bind:event="oninput" />

Obviously it is confusing that it works on most browsers except Edge. 
I'm not sure if the issue is fixed though, I would expect a bind to happen if I select something from the datalist and that does not happen without the bind:event oninput.

I did also notice that this issue is fixed in the new Chromium Edge.

**Comment by enetstudio** [comment]
> Bind should not be with upper case though

Sorry, not my fault...It's the editor's fault caused when you make text bold. I'll change it...

**Comment by mkArtakMSFT** [comment]
This is not something we plan to fix as it doesn't meet the priority bar as it's behavior to the old version of Microsoft Edge.
