### ISSUE TITLE
Update ASP.NET Core KeyVault integration package 

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#14657]
### Describe the bug
From @vijayrkn, we need to:

1.	Regularly update this integration package - Microsoft.AspNetCore.AzureKeyVault.HostingStartup
2.	Updating the Azure SDK dependency from Microsoft.Azure.KeyVault to Azure.Security.KeyVault.Keys & Azure.Security.KeyVault.Secrets. 

We want to do this for .NET Core 3.1

**Comment by Pilchie** [comment]
Tagging @anurse

**Comment by vijayrkn** [comment]
@anurse - Information on the new KeyVault packages from the Azure SDK team.

|                     |                                                                            |                                                                                                                         |                                                                                                                        |                                                                                                     |
|---------------------|----------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| Key Vault - Keys    | [Package](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys/)    | [Readme](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/README.md)    | [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys/samples)    | [API Reference](https://azure.github.io/azure-sdk-for-net/api/Azure.Security.KeyVault.Keys.html)    |
| Key Vault - Secrets | [Package](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/) | [Readme](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples) | [API Reference](https://azure.github.io/azure-sdk-for-net/api/Azure.Security.KeyVault.Secrets.html) |

**Comment by blowdart** [comment]
This may affect the data protection keyvault pieces too. cc @HaoK

**Comment by Pilchie** [comment]
@anurse  - did you have someone who was going to look at  this?

**Comment by anurse** [comment]
This slipped my radar. I don't have someone in mind but can find someone.

**Comment by anurse** [comment]
These packages ([`Azure.Security.KeyVault.Keys`](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys) and [`Azure.Security.KeyVault.Secrets`](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets)) are still in preview, so we can't update to take dependencies upon them until they GA. I don't think we can hit preview2 with this, given that. Unless they are GAing by mid-November I don't think we could update to support them in 3.1 at all.

Similarly, we need to evaluate these to see if there are breaking changes. Changing dependencies like this is considered a breaking change since users may have been using KeyVault APIs via the transitive reference we provide.

**Comment by Petermarcu** [comment]
Can your previews not depend on previews? This is a breaking change release so we need to decide the strategy to take for this update. Users using the older version transitively can directly reference it to work around.

**Comment by Petermarcu** [comment]
Also, we should partner to make sure dates for GA. We should be able to line up.

**Comment by anurse** [comment]
> This is a breaking change release

I'm not confident in reacting to these changes in the very tight remaining time for 3.1. We'll miss preview 2 for sure if there are breaing changes to react to

**Comment by Pilchie** [comment]
Moving to 3.1, since we're going to look at it before 5.0, but probably out of band from 3.1 itself.

**Comment by Tratcher** [comment]
Are we doing anything here? Also, where is the source for this package?

**Comment by Pilchie** [comment]
Isn't that https://github.com/dotnet/aspnetcore/pull/17041?

**Comment by anurse** [comment]
Yep, #17041 is the update for this. Just waiting for March branches to open.

**Comment by TechWatching** [comment]
I was wondering if there would be a way to make this package work a little bit like keyvault configuration provider in ASP.NET (classic). This provider only needs a `get` permission in Strict Mode and only loads the needed secrets. It prevents the application loading all the secrets of keyvault inlucded secrets it does not need. Okay I know we can implement IKeyVaultSecretManager to target only specific secrets (maybe by doing a logic based on tags) but the `list` right is needed. There should be a mechanism to allow to load only needed secrets without  having to manually retrieve each secret one by one using the sdk.

**Comment by Pilchie** [comment]
This can be closed now based on the new Azure packages, right @anurse ?

**Comment by anurse** [comment]
Yes indeed!
