### ISSUE TITLE
Potential dotnet watch performance improvement

### ISSUE THREAD

**Issue by CoderNate** [dotnet/aspnetcore#14691]
In order to speed up dotnet watch, I'm wondering if after the first iteration of the while loop you could begin the process of creating an up-to-date FileSet *before* waiting for a file change event from the user (instead of after).  Calling MsBuild in order to get a list of files can take one or two seconds for even a pretty small number of project dependencies.

**Relevant file**:  src/Tools/dotnet-watch/src/DotNetWatcher.cs

### Current steps of 1 iteration of the while loop
1. Call ``await`` on ``fileSetFactory.CreateAsync`` (which calls MsBuild)
2. Call ``fileSetWatcher.GetChangedFileAsync`` which gives back a task that can be used to cancel the iteration early if user edits a file
3. ProcessRunner executes the ProcessSpec for the dotnet build/test/whatever process
4. Before the iteration completes, another call is made to await ``fileSetWatcher.GetChangedFileAsync`` (wait for user to edit something)

### Proposal
Before awaiting step 4, start (but do not immediately wait on) a task for fileSetFactory to Create a new FileSet.  Most of the time this task will be finished before the user edits another file and then step 1 of the next while loop iteration can make use of this pre-started task in order to save time:
```C#
while (true) {
    processSpec.EnvironmentVariables["DOTNET_WATCH_ITERATION"] = iteration.ToString(CultureInfo.InvariantCulture);
    iteration++;

    var fileSet = await (preStartedFileSetCreationTaskFromPreviousIteration ?? fileSetFactory.CreateAsync(cancellationToken));
    ...
```

### Drawbacks
Probably something I'm not thinking of?  There is an edge case where a file edit could fail to cause an early bail-out of the ProcessRunner if:
1. User adds new file X.cs to the project (does not trigger file change event because new file is not yet in the FileSet)
2. User edits some other file that *is* part of the FileSet and kicks off the next while loop iteration
3. User immediately edits X.cs but the edit is not picked up and the current iteration does not get cancelled early like it normally would
This seems like a pretty minor drawback compared to the current limitation of not detecting new files.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you have data proving that this will lead to a better performance?

**Comment by CoderNate** [comment]
Sure I can provide some data.  So ``fileSetFactory`` is an instance of ``MsBuildFileSetFactory`` so we can do a simple test to see how long the ``MsBuildFileSetFactory.CreateAsync`` call takes:
1. Create a blank .NET core console app
2. Add a reference to "C:\Program Files\dotnet\sdk\2.2.103\DotnetTools\dotnet-watch\2.2.0\tools\netcoreapp2.2\any\dotnet-watch.dll"
3. Implement Microsoft.Extensions.Tools.Internal.IReporter interface with a simple class called ``CustomReporter`` that just logs everything to the console.
4. Run this code:
```cs
using Microsoft.DotNet.Watcher.Internal;
using Microsoft.Extensions.Tools.Internal;
for (var i = 0; i < 2; i++) {
	var w = System.Diagnostics.Stopwatch.StartNew();
	var fileSetFactory = new MsBuildFileSetFactory(
		new CustomReporter(),
		@"C:\SomeProject\SomeProject.csproj",
		waitOnError: true,
		trace: true);
	var set = fileSetFactory.CreateAsync(System.Threading.CancellationToken.None).Result;
	Console.WriteLine($"Calling CreateAsync took {w.Elapsed}");
}
```
I get this
```
C:\DotnetWatchTest>dotnet run
Running MSBuild target 'GenerateWatchList' on 'C:\SomeProject\SomeProject.csproj'
Started 'C:\Program Files\dotnet\dotnet.exe' with process id 42532
Process id 42532 ran for 1282ms
Watching 314 file(s) for changes
Calling CreateAsync took 00:00:01.3256122
Running MSBuild target 'GenerateWatchList' on 'C:\SomeProject\SomeProject.csproj'
Started 'C:\Program Files\dotnet\dotnet.exe' with process id 3136
Process id 3136 ran for 1391ms
Watching 314 file(s) for changes
Calling CreateAsync took 00:00:01.3956035
```

So in this case if I typically have pauses of at least 1.4 seconds between dotnet watch being triggered by a file change (seems very likely), then I'm completely removing 1.4 seconds from my wait time on every iteration!

**Comment by mkArtakMSFT** [comment]
Thanks for the details. Are you interested in sending us a PR for this proposal? We'll happily consider it.

**Comment by mkArtakMSFT** [comment]
We're reviewing community submitted PRs weekly and we will pick yours up in a week, if you send it now.

**Comment by CoderNate** [comment]
In addition to the drawback I already mentioned, this PR also has a slightly different flavor of problem.  Steps:
1. The first iteration is completing and we proactively start creating the next fileset (we'll call it fileset A)
2. The user adds BrandNewFile.cs to the project which doesn't trigger anything (this is no different than how dotnet watch has always worked).
3. The user edits an existing file which *does* get noticed by the file watcher.  This begins the next iteration.
4. The second iteration is completing and we proactively start creating a new fileset (call it fileset B).
5. We call ``fileSetWatcher.GetChangedFileAsync`` using fileset A.
6. **User edits BrandNewFile.cs and nothing happens because that file is not in fileset A.**

This can be fixed if it's deemed worth fixing.  We just have to start watching fileset B for changes right away once it's done being built.  That might look something like:
```cs
if (finishedTask == processTask)
{
	preStartedFileSetCreationTaskFromPreviousIteration = fileSetFactory.CreateAsync(cancellationToken);

	// Now wait for a file to change before restarting process
	var fileChangedTask = fileSetWatcher.GetChangedFileAsync(cancellationToken, () => _reporter.Warn("Waiting for a file to change before restarting dotnet..."));
	var firstTaskToComplete = await Task.WhenAny(preStartedFileSetCreationTaskFromPreviousIteration, fileChangedTask);
	if (firstTaskToComplete == preStartedFileSetCreationTaskFromPreviousIteration)
	{
		using (var newFileSetWatcher = new FileSetWatcher(preStartedFileSetCreationTaskFromPreviousIteration.Result, _reporter))
		{
			await Task.WhenAny(
				newFileSetWatcher.GetChangedFileAsync(cancellationToken),
				fileChangedTask);
		}
	}
}
```
Unfortunately that makes the code a little more complicated.

**Comment by jkotalik** [comment]
As we changed the way we implement `dotnet watch` to not do an msbuild evaluation, we're going to close this. Feel free to reopen or file a new issues if you find other performance issues.
