### ISSUE TITLE
How can I tell if a Signalr client has received the message sent by the server?

### ISSUE THREAD

**Issue by Pibe93** [dotnet/aspnetcore#14694]
Good morning,
I need to know when the client actually received the message sent by the signalr server.
I understand that there is no way to know it and what I was thinking about was when the client receives the message, I invoke something on the server and then perform a certain action.
For example I should once the signalr client received the message write a record to a table where I will mark that the message was delivered.

I thought of notifying me of receiving the message in this way:

```C#
connection.On<string, string>("ReceiveMessage", (title, message) =>
{
    // I always notify the server using the Signalr connection that the message has been
    connection.InvokeAsync("NotifyReceiveMessage");
    OpenToast(title, message);
});
```

So in the hub on the server when NotifyReceiveMessage will be invoked it will mean that the client has actually received the message and I will write the record on the DB with my service.
What was I thinking of doing is correct? Is there a better or more correct way?

Thanks for the help.

**Comment by BrennanConroy** [comment]
This is basically the approach we recommend to people. Implement an ACK system so the server knows when a client has processed/received a message.

In your specific example code, you should use `SendAsync("NotifyReceiveMessage")` as you aren't expecting a response, `InvokeAsync` would cause the server to send a response message which is a waste of bandwidth in this case.

Also, await your tasks! Our `.On` handlers should support `Task` returning handlers.

**Comment by Pibe93** [comment]
OK but in case you want to send a message to the server regardless of whether it is received what should I use? SendAsync is present only within the Task .On
