### ISSUE TITLE
SA0001 warning when building Razor view assemblies

### ISSUE THREAD

**Issue by Dennis-Petrov** [dotnet/aspnetcore#14692]
### Describe the bug

Getting SA0001 warnings (one per project) from StyleCopAnalyzers when building Razor view assemblies. `RazorCoreCompile` does not set the `DocumentationFile` property when invoking CSC.

### To Reproduce

Using ASP .NET Core 2.2 and VS 16.3.2.
All of my projects import shared MSBuild props file with this property:

```
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
```
After update StyleCopAnalyzers  from 1.0.2 to 1.1.118 every Razor project gets SA0001 when executing `RazorCoreCompile` task. 

Related StyleCopAnalyzers issue with more details:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3034

### Expected behavior
When `GenerateDocumentationFile` is turned on in Razor Project, views assembly project must turn it on too.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
