### ISSUE TITLE
Microsoft.AspNetCore.Authorization.Policy 3.0.0 nuget packet missing

### ISSUE THREAD

**Issue by mangeg** [dotnet/aspnetcore#14697]
### Describe the bug
When trying to implement the interface **IPolicyEvaluator** inside of a project not using the Web SDK that is a netstandard2.1 lib or a netcoreapp3.0 console app there is no way to reference Microsoft.AspNetCore.Authorization.Policy 3.0.0 nuget package. The latest available on nuget.org is 2.2.0 which in turn references **Microsoft.AspNetCore.Authentication.Abstractions** and **Microsoft.AspNetCore.Authentication 2.2.0**

[https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization.Policy](url)

Metadata info for IPolicyEvaluator inside a netcoreapp3.0/netstandard2.1 using Microsoft.NET.Sdk:
```
#region Assembly Microsoft.AspNetCore.Authorization.Policy, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.authorization.policy\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Authorization.Policy.dll
#endregion
```

Metadata info for IPolicyEvaluator inside a netcoreapp3.0 app using Microsoft.NET.Sdk.Web:
```
#region Assembly Microsoft.AspNetCore.Authorization.Policy, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0\ref\netcoreapp3.0\Microsoft.AspNetCore.Authorization.Policy.dll
#endregion
```

### To Reproduce
1. Create new netstandard 2.1 project.
2. Implement IPolicyEvaluator interface.
3. Add nuget reference to Microsoft.AspNetCore.Authorization.Policy. Highest available 2.2.0.

### Expected behavior
Expected to be able to get 3.0.0 versions of the nuget packages. The 2.2.0 versions seems to be working. But don't know if there could be anything unexpected happening when 2.2.0-versions of the dependant DLLs Microsoft.AspNetCore.Authentication.Abstractions and Microsoft.AspNetCore.Authorization are loaded when referencing the netstandard lib in a web project.

**Comment by pranavkm** [comment]
Hi @mangeg, you'll need a `FrameworkReference` to `Microsoft.AspNetCore.App` to reference the API. 
Our migration guide - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30 - has notes on updating to target ASP.NET Core 3.0 as well as ways to cross-compile your library to support multiple versions of ASP.NET Core.

**Comment by mangeg** [comment]
Hi @pranavkm 
I see. I had misunderstood that part of the migration, and it was a bit confusing since I was also using Microsoft.AspNetCore.Authorization package that is on the list but still exists in a 3.0.0 version on nuget.org.
Thank you for the clarification.

**Comment by BenjaminAbt** [comment]
FrameworkReference did the trick for me

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <NullableContextOptions>enable</NullableContextOptions>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```
