### ISSUE TITLE
@Html.DisplayFor uses template for base class and not derived class

### ISSUE THREAD

**Issue by mheptinstall** [dotnet/aspnetcore#14709]
When using DisplayTemplates for derived classes @Html.DisplayFor renders the template for the base class and not the derived class in ASP.NET Core 2.2.

https://stackoverflow.com/questions/58224973/how-to-use-displaytemplates-in-asp-net-core-razor-pages-with-model-inheritance

When doing this in a ASP.NET Web Application (.NET Framework) project the template for the derived class is rendered.

Example solution/projects attached [WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3687830/WebApplication1.zip)

**Comment by huysentruitw** [comment]
Using `DisplayForModel` seems to solve that issue:

```C#
@foreach (var principal in Model.Principals)
{
    @Html.DisplayForModel(principal)
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mheptinstall.
@ajaybhargavb can you please try to repro this? Thanks!

**Comment by huysentruitw** [comment]
@mkArtakMSFT the repro is in the attached zip file. The solution contains 2 projects (ASP.NET one and a net48 one using ASP.NET Core 2.2). Both behave differently.

**Comment by huysentruitw** [comment]
I think I'm on it, I already have a test that reveals this issue (in ASP.NET Core 3).

```C#
[Fact]
public void DisplayFor_InheritedModel_UsesCorrectTemplate()
{
    // Arrange
    var model = new object();
    var view = new Mock<IView>();
    var displayForModel = (SomeModel)new SomeInheritedModel();
    var viewEngine = new Mock<ICompositeViewEngine>(MockBehavior.Strict);
    viewEngine
        .Setup(v => v.GetView(/*executingFilePath*/ null, It.IsAny<string>(), /*isMainPage*/ false))
        .Returns(ViewEngineResult.NotFound(string.Empty, Enumerable.Empty<string>()));
    viewEngine
        .Setup(v => v.FindView(It.IsAny<ActionContext>(), It.IsAny<string>(), /*isMainPage*/ false))
        .Returns(ViewEngineResult.Found("SomeInheritedView", view.Object));
    var helper = DefaultTemplatesUtilities.GetHtmlHelper(model, viewEngine.Object);

    // Act
    var displayResult = helper.DisplayFor(_ => displayForModel);

    // Assert
    viewEngine.Verify(v => v.GetView(/*executingFilePath*/ null, "SomeInheritedModel", /*isMainPage*/ false), Times.Once);
    viewEngine.Verify(v => v.FindView(It.IsAny<ActionContext>(), "DisplayTemplates/SomeInheritedModel", /*isMainPage*/ false), Times.Once);
}
```

Where `SomeInheritedModel` inherits from the already existing `SomeModel` in the tests.

Test error message:

```
Moq.MockException : 
 Expected invocation on the mock once, but was 0 times: v => v.GetView(null, "SomeInheritedModel", False)
    
Configured setups: 
ICompositeViewEngine v => v.GetView(null, It.IsAny<String>(), False)
    
Performed invocations: 
IViewEngine.GetView(null, "SomeModel", False)
IViewEngine.FindView(ViewContext, "DisplayTemplates/SomeModel", False)
```

So because I'm down-casting the `SomeInheritedModel` instance to the base-class `SomeModel`, you see that the framework searches for the base-class instead. That's probably because it takes the ReturnType of the expression instead of the type of the instance.

**Comment by huysentruitw** [comment]
The 'problem' is this line: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/ExpressionMetadataProvider.cs#L125

It takes `typeof(TResult)` where `TResult` is a generic type derived from our input expression, so in the test case: `SomeModel`. We should somehow get the type of the instance instead, but I'm not sure where it's safe to do that without generating side-effects (f.e. getting a property or executing underlying code, in case of a method being passed in).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
