### ISSUE TITLE
Client Certificate Validation for non-public CA

### ISSUE THREAD

**Issue by alexhcheng** [dotnet/aspnetcore#14718]
If i have a client cert signed by a non-public CA (but not self signed), it will fail validation in

https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Certificate/src/CertificateAuthenticationHandler.cs

Specifically, since it is not self-signed

chainPolicy.VerificationFlags |= X509VerificationFlags.AllowUnknownCertificateAuthority;

won't be set and we result in 

"A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider"

I can't tell if there is a way to pass in a CA to the X509 ChainPolicy

**Comment by alexhcheng** [comment]
looks like custom store is enabled by this
https://github.com/dotnet/corefx/pull/40379
but somehow this will need to be integrated with the CertificateAuthenticationHandler

**Comment by blowdart** [comment]
Are you on Windows or Linux? If you're on Windows the expectation here is for you to add it to the certificate store as a trusted root. If you're on Linux you do the same, but for OpenSSL.

**Comment by alexhcheng** [comment]
running as docker container on Linux kubernetes.  So the certificate are actually just downloaded onto a FS mount.  And the code load the bytes into X509Certificate2 object.

**Comment by edwardneal** [comment]
This also causes some difficulty on client certificate authentication on Azure App Services. Authenticating with a self-signed client certificate is fine (the check for .IsSelfSigned() sets the VerificationFlags to avoid the CA check), but authenticating using a client certificate which has been signed by a non-public CA won't work.

App Services doesn't allow changes to the list of trusted root certificates, so this seems to prevent any kind of non-trivial client certificate authentication without using a dedicated App Service Environment.

I can submit a PR to add the feature. Would it be better to have a simple boolean (ValidateCertificateAuthority) on CertificateAuthenticationOptions to disable the CA check, or a new event (OnCertificateValidating) on CertificateAuthenticationEvents?

**Comment by davidsh** [comment]
>Would it be better to have a simple boolean (ValidateCertificateAuthority) on CertificateAuthenticationOptions to disable the CA check

I think this a good choice.

@Tratcher
