### ISSUE TITLE
Create RazorPage page file encoding

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#14733]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/662762/建立razorpage頁面檔案編碼.html)._

---
右鍵&gt;加入&gt;新增項目&gt;Razor頁面<br><br>編碼卻是Big5，可以修正，編碼Default UTF-8 嗎?<br><br>這個問題找了很久，上到測試機之後才注意到.

---
#### Visual Studio Feedback System on 7/29/2019, 02:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/29/2019, 08:25 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Joe Davis (WEB TOOLS) [MSFT] on 7/30/2019, 03:01 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it

---
### Original Solutions
(no solutions)

**Comment by ajaybhargavb** [comment]
We fixed the encoding issue for Blazor templates in https://github.com/aspnet/AspNetCore/issues/11435. We need to verify if this issue still exists in Razor Page item template and if so, fix it.
