### ISSUE TITLE
Bad responses: FortunesPostgreSql-Actix, LinkAThonGrpcTrimmedAndR2R, LinkAThonGrpcTrimmedAndR2RSingleFile

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#14751]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| LinkAThonGrpcTrimmedAndR2R | Linux, Physical, http, KestrelSockets | 10/5/19 2:09:05 AM +00:00 | 54992 |
| LinkAThonGrpcTrimmedAndR2RSingleFile | Linux, Physical, http, KestrelSockets | 10/5/19 2:10:47 AM +00:00 | 404595 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
Still have issues

**Comment by jkotalik** [comment]
@rynowak I don't believe this is a gRPC issue, more an issue with linking. Can you do the needful?
