### ISSUE TITLE
Change the name of Startup class method, for more clarity

### ISSUE THREAD

**Issue by nefcanto** [dotnet/aspnetcore#14775]
### Is your feature request related to a problem? Please describe.
In this page of fundamentals overview, it's been said that in `Startup` class we have two methods, one is to configure services that we want to use in our app (which is appropriately named `ConfigureServices`), the other is to create the pipeline (which I believe is wrongly named `Configure`). Having two `Configure` is confusing. A lot of better names can be used for the second method to create pipeline.

### Describe the solution you'd like
I recommend any of these names:

- ComposePipeline
- CreatePipeline
- ConfigurePipeline
- AddMiddleware

**Comment by davidfowl** [comment]
We’re not going to change something this fundamental at this point. However I don’t disagree with you. If this feedback was given back in the 1.0 timeframe it would have been more feasible

**Comment by nefcanto** [comment]
Code as comment, self-explanatory, self-descriptive; They are all terms we use to describe a code which requires less and less documentation and is more understandable by the names being chosen.

Another example is `Content root` and `Web root`. Based on the explanation from the same page, they could simply be called `PrivateFolder` and `PublicFolder`.

And agilemanifesto.org claims that we're not afraid of change and we embrace it even late in development.

> Welcome changing requirements, even late in
> development. Agile processes harness change for
> the customer's competitive advantage.

If it can't be done, then maybe there are things that have not be coded properly. Please note that I'm not criticizing you or the team of course, and I'm full of faults and I love ASP.NET Core and Microsoft products. I just want to redirect your attention to some points. That's all. Thanks.

**Comment by davidfowl** [comment]
Thanks for the feedback!

**Comment by MintPlayer** [comment]
Hi @davidfowl 

I agree that ConfigureHttpPipeline would be a better name for the method, but at this point we're simply too close to the release of .NET Core 3.1, which is a long-term-support release of .net core (i mean like 3 years). Right now we can't "just" change things in an impulsive way. It's important that major bugs are being addressed, and no new bugs are introduced.

But it sure is something that can and probably will be renamed with ASP.NET-core 3.1
