### ISSUE TITLE
Identity UI should use autocomplete attributes 

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#14809]
### Is your feature request related to a problem? Please describe.

Identity UI should use autocomplete attributes on the input HTML elements to better work with password managers and in-browser password managers.

### Describe the solution you'd like
Login
```html
  <input type="text" autocomplete="username">
  <input type="password" autocomplete="current-password">
```

Register
```html
  <input type="text" autocomplete="username">
  <input type="password" autocomplete="new-password">
  <input type="password" autocomplete="new-password">
```

Change password; while it doesn't require username, should include it as a non-displayed field with the correct username prefilled and autocomplete set to again aid password managers: 
```html
  <input style=display:hidden" type="text" autocomplete="username" value="@username">
  <input type="password" autocomplete="current-password">
  <input type="password" autocomplete="new-password">
  <input type="password" autocomplete="new-password">
```

### Additional context

* [Create Amazing Password Forms](https://www.chromium.org/developers/design-documents/create-amazing-password-forms)
* [Password Form Styles that Chromium Understands](https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands)

/cc @blowdart

**Comment by kapsiR** [comment]
May I take that and submit a PR? (Would change the pages in [UI/src/Areas/Identity/Pages](https://github.com/aspnet/AspNetCore/tree/master/src/Identity/UI/src/Areas/Identity/Pages))

**Comment by benaadams** [comment]
Please do :)

**Comment by blowdart** [comment]
Backlogging for evaluation in v5

**Comment by HaoK** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/14953, thanks again @kapsiR
