### ISSUE TITLE
[MVC] Replace usages of Assembly.CodeBase with Assembly.Location

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#14827]
We are using Assembly.CodeBase across the code when we need to find the location of an assembly. This was based on the need to support shadow-copy on full framework.

We spoke with the .NET Core folks and they've essentially told us that Location and CodeBase should be equivalent in .NET Core and that Location is preferred.

Given that we don't support full framework anymore, we should replace all the usages of Assembly.CodeBase across the board in favor of Assembly.Location.

See https://github.com/aspnet/AspNetCore/issues/14501#issuecomment-538606720 for details on the discussion.

**Comment by davidfowl** [comment]
This isn't just MVC, we should fix it in hosting as well https://github.com/aspnet/AspNetCore/search?q=CodeBase&unscoped_q=CodeBase

**Comment by javiercn** [comment]
@davidfowl Yes, my plan is to scour the entire codebase for it, I just used [MVC] because using [ASP.NET] seemed wrong, and I like to have the area in the issue title 👍. But we will fix it across asp.net core
