### ISSUE TITLE
Re-enable tests that depend on the targeting pack being built

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#14832]
https://github.com/aspnet/AspNetCore/pull/14746 disables some tests that depend on the targeting pack being built. Once we re-enable building said targeting pack (likely in 3.0.2), we should re-enable the tests.

CC @JunTaoLuo @dougbu

**Comment by wtgodbe** [comment]
We also skip these in https://github.com/aspnet/AspNetCore/pull/17335

**Comment by Pilchie** [comment]
We didn't do this for 3.0.2 - are we doing it for 3.0.3?  (Trying to clean up some stale milestones)

**Comment by wtgodbe** [comment]
These tests should just remain disabled in servicing branches, since we (hopefully) won't build the targeting pack again. Will close

**Comment by dougbu** [comment]
This bit us in 3.1.2. Need to enable `TargetingPackTests` in **all** builds where Microsoft.AspNetCore.App.Ref builds for realz

**Comment by dougbu** [comment]
Also need to add tests that check the manifest against _expected_ content. This won't be an issue where we have a checked-in manifest but could miss issues in 'master' branch
