### ISSUE TITLE
Change HttpSys default client cert mode to Allow

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#14840]
https://github.com/aspnet/AspNetCore/pull/14839 introduced a new option to let you control how client certs are populated. It did not change the default behavior for compat reasons. In 5.0 we should change the default to Allow as to avoid a TLS renegotiation during a sync API (Connection.ClientCertificiate).

We should also change GetClientCertificateAsync to prefer the certificate in the request structure (if any) before triggering a renegotiation.

**Comment by Tratcher** [comment]
I confirmed in wireshark traces that GetClientCertificateAsync will not trigger a renegotiation if a cert was already provided at the start of a connection. In that case it should be safe to return the cert from the request structure if present. Even ClientCertificiate could do that if AllowRenegoation is enabled.

**Comment by anurse** [comment]
It looks like the default is [already `AllowRenegotiation`](https://github.com/dotnet/aspnetcore/blob/cc2f5497e86a4c029e2928f315f65a01edc20254/src/Servers/HttpSys/src/HttpSysOptions.cs#L62), so is the proposal to change it to `AllowCertificate`?

**Comment by Tratcher** [comment]
Right, AllowCertificate. Also:
> We should also change GetClientCertificateAsync to prefer the certificate in the request structure (if any) before triggering a renegotiation.
