### ISSUE TITLE
Rename "build" directories

### ISSUE THREAD

**Issue by dasMulli** [dotnet/aspnetcore#14846]
GitHub filters out build/ and Build/ directories for code search and go-to (press "t" on the code tab and look for files in build directories).

The dotnet/sdk repo did this by moving msbuild targets from `build/` to `targets/` and then changing packaging logic where the generated layout needs to have `build` directories.

The AspNetCore-Tooling repo and also this repo should do the same and not use directories named "build" or "Build" to be better accessible through GitHub UI.

**Comment by dougbu** [comment]
The build/ directories still exist in our release/2.1 branches but files have been migrated everywhere else. I doubt we're going to make further changes in this area.

/cc @Pilchie in case you disagree.
