### ISSUE TITLE
Investigate using sendBeacon to trigger disconnect on browser close for non-websocket transports

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#14847]
I was made aware of the sendBeacon by @rynowak as blazor uses [it](https://github.com/aspnet/AspNetCore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Components/Web.JS/src/Boot.Server.ts#L64) to gracefully close circuits. This gives us a clean way to  end SSE and long polling transports on browser close without waiting for the disconnect timeout.

**Comment by davidfowl** [comment]
Seems like there’s also a way to do this with a regular fetch request https://fetch.spec.whatwg.org/#keep-alive-flag

**Comment by javiercn** [comment]
@davidfowl it would be nice if SignalR can take care of this and blazor can simply be "notified".

**Comment by davidfowl** [comment]
Yes that's the intention. This should be happening today anyways the difference here is that its more proactive specifically for non-websocket transports. The websocket API already does the needful and sends a close frame when the browser is closed.

**Comment by davidfowl** [comment]
Seems there was a discussion about being able to detect graceful disconnects here https://github.com/aspnet/AspNetCore/issues/12828#issuecomment-519980526

**Comment by rynowak** [comment]
> 
> 
> Seems there was a discussion about being able to detect graceful disconnects here [#12828 (comment)](https://github.com/aspnet/AspNetCore/issues/12828#issuecomment-519980526)

Right, we tested SignalR's ability to detect graceful disconnect - and it didn't work well.

**Comment by anurse** [comment]
Yeah, we've definitely talked about this before. Seems good.

**Comment by anurse** [comment]
Re-triage: This is probably out-of-scope for 5.0 now. Also, we'd prefer `fetch({ keepAlive: true})` over `sendBeacon` if the browser supports `fetch` since it lets us do any kind of request.
