### ISSUE TITLE
Consider using a format string for TimeSpan.TotalMilliseconds in log messages

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/aspnetcore#14854]
### Describe the bug
Since .NET Core 3, floating-point value's ToString behavior [has changed](https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/). I now frequently see things like `200.19760000000002 ms` in the log which looks rather clumsy.

### To Reproduce
```csharp
var ts = TimeSpan.FromTicks(2001976);
Console.WriteLine(FormattableString.Invariant($"{ts.TotalMilliseconds} ms"));
Console.WriteLine(FormattableString.Invariant($"{ts.TotalMilliseconds:F4} ms"));
```
```
200.19760000000002 ms
200.1976 ms
```

### Expected behavior
`TimeSpan.TicksPerMilliSecond == 10000`, so a format string of `F4` shows all the relevant digits.

**Comment by JunTaoLuo** [comment]
This seems like a simple clean up item, we'll look for contributors to help out!

**Comment by RonaldMariah** [comment]
Happy to contribute and create an PR for this. Any ideas/recommendations on the approach?

**Comment by davidfowl** [comment]
I thought @benaadams fixed this

**Comment by benaadams** [comment]
Yeah is 4 decimal digits after https://github.com/dotnet/aspnetcore/pull/10102

**Comment by davidfowl** [comment]
Yep! Closed as fixed
