### ISSUE TITLE
Endpoint routing breaks Asp-route parameters in core 3.0 / Razor Pages 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#14869]
Moved from https://github.com/aspnet/AspNetCore.Docs/issues/14911 by @mrAshpool 

In 2.2 an anchor would automatically include any route parameters, if the source had that property, and the destination contained the @page "{ParamName}"

i.e.
`<a asp-page="/Test/Index">Test</a>` could be rendered as 
`<a href="xx/Test/Index/ParamValue">Test</a>`
despite not including asp-route-ParamName

After migrating to 3.0 I need to explicitly include any route details in the tag helper

If I disable Endpoint Routing in 3.0, the anchor helper works as it did in 2.2

Is this the intended behavior?

**Comment by mrAshpool** [comment]
@Rick-Anderson, thankyou - I've attached a new 3.0 project which demos the issue on the home page.  Startup.cs has both routing options, simply uncomment 

Correction on my original issue - In 2.2 an anchor would automatically include any route parameters, if the source had that ~~property~~ route parameter, and the destination contained the @page "{ParamName}"

[WebApplication1.zip](https://github.com/aspnet/AspNetCore/files/3712395/WebApplication1.zip)

**Comment by mkArtakMSFT** [comment]
@rynowak was this intentional change in Endpoint Routing?

**Comment by mkArtakMSFT** [comment]
Closing as this change was intentional.
