### ISSUE TITLE
Remove type names from ControllerActionInvoker logs and use something more concise

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#14880]
Example:
```
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Sessions"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.Collections.Generic.List`1[ConferenceDTO.SessionResponse]]] Get() on controller BackEnd.Controllers.SessionsController (BackEnd).
```

Printing out the method signature in logs is too verbose (and ugly since we don't pretty print), is there any cleaner way to disambiguate in the face of overloads?

**Comment by javiercn** [comment]
@davidfowl Thanks for contacting us :trollface: 

Do you have any suggestion on how can we improve this and if in doing so, we could miss some common ambiguous cases?

On a more serious note, we could provide a more detailed exception with simplified signatures and after that, include the full signature for completeness.
