### ISSUE TITLE
Improve KnownFrameworkReference workarounds in templatetests.props.in

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#14895]
https://github.com/aspnet/AspNetCore/commit/462acbe46d0d85107f75647f3cc7bcec09eb774b#diff-a0bc203ab59b1a2f006b56858a20684b removed the `TargetFramework` metadata from the `KnownFrameworkReference` workarounds in `templatetests.props.in`. We need these workarounds in order to reference the desired versions of Microsoft.Netcore.App (the one we depend on in versions.props, rather than the one the SDK depends on). However, the current workaround modifies the metadata for all `KnownFrameworkReference` items for `Microsoft.Netcore.App`/`Microsoft.AspNetcore.App`, rather than just the ones that match the TFM of the desired reference version. This is because, during the build of the template test projects, conditions on Item metadata give the following error:

> error MSB4191: The reference to custom metadata "TargetFramework" at position 1 is not allowed in this condition "'%(TargetFramework)' == 'netcoreapp3.1'".

This happens for both of the following conditions:

> Condition="'%(TargetFramework)' == '${DefaultNetCoreTargetFramework}'"

> Condition="'%(KnownFrameworkReference.TargetFramework)' == '${DefaultNetCoreTargetFramework}'"

We should investigate why this error occurs _only_ in the template tests, and what we can do to work around it so that we can apply this condition to the update. It's worth noting that the same workaround appears in release/3.1, so we should decide if it's worth fixing there as well.

CC @dougbu @JunTaoLuo @Pilchie

**Comment by dougbu** [comment]
@rainersigwald any suggestions on avoiding the error @wtgodbe describes above?

**Comment by rainersigwald** [comment]
You can't do that kind of metadata expansion in a condition outside of a target. Can you move the filtering operation to a target?

**Comment by dougbu** [comment]
@wtgodbe anything new for this issue?

**Comment by wtgodbe** [comment]
Not yet, we can keep this in backlog for now

**Comment by dougbu** [comment]
Taking this because it's addressed in #27473

**Comment by dougbu** [comment]
To clarify: The templates used in the `GenerateFiles` project introduced in #26788 avoided updates to all `@(KnownFrameworkReference)` items using `WithMetadataValue(...)` item function calls, avoiding unsupported `Condition`s. #27473 finishes the job because it uses the `GenerateFiles` output for the project template test assets.

**Comment by dougbu** [comment]
5fd1db26257c
