### ISSUE TITLE
Blazor WASM .NET Core 3 preview 9 (alpine): The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering'

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#14976]
I am trying to build my blazor app within a docker container. I developed it with my Win 10 x64 PC on the command line. (dotnet watch build)
No issues so far.
But with this simple dockerfile i get the same errors as in the first post.
```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS dotnet

WORKDIR /app
COPY /src /app
RUN dotnet publish -c Release
```
Failing part of the log output:
```shell
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 6.02 sec for /app/Dark.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
/build/obj/Release/netstandard2.0/RazorDeclaration/App.razor.g.cs(61,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [/app/Dark.csproj]
/build/obj/Release/netstandard2.0/RazorDeclaration/Component/Index/Index.razor.g.cs(62,92): error CS0234: The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?) [/app/Dark.csproj]  
```
This is happening with the alpine version of the sdk. If I use the "normal" one everything works as expected:
```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS dotnet
```
This issue is very similar to https://github.com/aspnet/AspNetCore/issues/13695

**Comment by javiercn** [comment]
@MarkusRodler Thanks for contacting us.

Can you try out with RTM bits? I think we had an issue like that at the time but that we solved it.

Let us know if you still run into issues after updating to RTM.

**Comment by MarkusRodler** [comment]
@javiercn How can I update the docker container? I'm already using the latest alpine tag: `mcr.microsoft.com/dotnet/core/sdk:3.0-alpine`
I have no problems with the Debian 10 Docker Image and with Windows 10.

**Comment by javiercn** [comment]
@MarkusRodler You can reference the RTM SDK like this `mcr.microsoft.com/dotnet/core/sdk:3.0.100-alpine3.9`

I see now that you are using client-side Blazor. Can you check the dependencies in your csproj files and make sure that they point to the latest released blazor version?

I believe there was an issue at some point about this, I'm not sure if it's not fixed yet. You can try and workaround it by explicitly referencing the Microsoft.AspNetCore.Components package directly in your csproj project and see if that fixes the issue.

**Comment by MarkusRodler** [comment]
@javiercn 
This is my csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>8.0</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview9.19465.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.0.0-preview9.19465.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview9.19465.2" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

`mcr.microsoft.com/dotnet/core/sdk:3.0.100-alpine3.9` works

**Comment by MarkusRodler** [comment]
I thougth the tag `3.0-alpine` is the latest tag in the listing here: https://hub.docker.com/_/microsoft-dotnet-core-sdk

**Comment by javiercn** [comment]
@richlander What's the right way to reference the RTM sdk for Alpine? How is using `mcr.microsoft.com/dotnet/core/sdk:3.0-alpine` different from using `mcr.microsoft.com/dotnet/core/sdk:3.0.100-alpine3.9`

@MarkusRodler  was running into issues and using 3.0.100-alpine3.9 solved his issue, and he mentions that with Debian and Windows 10 everything was fine.

**Comment by MarkusRodler** [comment]
Normally
`mcr.microsoft.com/dotnet/core/sdk:3.0-alpine` should be the same version or a newer one than
`mcr.microsoft.com/dotnet/core/sdk:3.0.100-alpine3.9`

**Comment by javiercn** [comment]
@MarkusRodler Exactly, that's why I'm asking @richlander as he's the expert in the matter. It might be a bug in the generated image.

**Comment by SteveSandersonMS** [comment]
Cleaning up! This is a very old issue which most likely no longer applies to current versions of the software.

If anyone is still able to reproduce this with the latest version (3.2.0-preview2 or later) could you please open a new bug with repro steps? Thanks!

**Comment by MarkusRodler** [comment]
I tested this with the current 3.1-alpine version and it works without issue.
