### ISSUE TITLE
Scaffolding Error

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#14970]
VS.NET Community 2019 v 16.3.4

I was following this tutorial:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio#the-student-entity
until I reached the Scaffold Student pages part:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio#scaffold-student-pages
When I used the scaffolding wizard, I got an error message asking me to install the following two NuGet Packages because they are missing:
- Microsoft.EntityFrameworkCore.Design
- Microsoft.EntityFrameworkCore.SQLServer
In fact I installed the first one only, and found the second already installed, then I rerun the scaffolding wizard, and it succeeded.
I think you need to fix the wizard to install the Microsoft.EntityFrameworkCore.Design NuGet.

**Comment by javiercn** [comment]
@VBAndCs Thanks for contacting us.

@vijayrkn This seems to be a scaffolding issue. Can you get someone on your team to handle it?

**Comment by pranavkm** [comment]
Hi, we haven't heard additional reports of this issue since this was filed. Closing this for now. If you continue seeing this, please file an issue in https://github.com/dotnet/scaffolding.
