### ISSUE TITLE
Azure AD authentication and client side Blazor.

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/aspnetcore#15022]
This may be more of a question than a feature request, and I appreciate it's not released yet so I might be a bit premature! :)

### Is your feature request related to a problem? Please describe.
I want to use Azure AD for multi tenant authentication with a Blazor web assembly client and a web api server and am a bit lost.

### Describe the solution you'd like
I guess this would ideally fit in with the standard Blazor authentication framework, cascading authentication state etc. And not involve too much work ;)

### Additional context
So, I'm a bit unsure what the direction of this is and where I should or shouldn't be focusing my efforts:
1. Is some sort of integration planned, or do I need to come up with something myself?
2. If not, should I be looking at MSAL.js or MSAL.net (see request [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1271)), or something more home grown?
3. For Javascript/SPAs the recommended route appears to be the implicit grant flow. Is this the correct method for client side Blazor, or is some other flow (refresh tokens) more appropriate? How do we get the hidden authorization via an iframe to work?
4. Ideally I'd like to support SSO and am not sure how that should work from Blazor?

Apologies if I'm jumping the gun or have missed some information. Having spent some time playing with it I'm not sure where I should be going and whether I'm wasting my time as some magic is around the corner!

Thanks! Loving Blazor BTW.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @LaughingJohn.
We don't have a solution for this at the moment. We plan to make this work in the near future. For now we recommend asking about how to enable this in StackOverflow.

**Comment by LaughingJohn** [comment]
I just wanted to add to this. I've basically given up on the whole token thing, as I don't think it is necessary because the API is my own. I think I can just use asp.net core sessions. I'm still experimenting and by no means an expert on this, so bear with me!

- I've set up session based authentication on the server side.
- I have a page and controller (currently using MVC but will probably switch to Razor Pages).
- Going to that page successfully bounces me to the microsoft azure ad login and back again.
- My understanding is that I now have 2 cookies, a Microsoft one and my own session cookie.

This I believe means my API is now secured, apart from checking that the user actually has access to the system and I've proved this works.

Now my blazor client application needs to figure out if I'm authenticated and potentially navigate to the microsoft login page - possibly via the server side page I've set up for that purpose. One thing that's also not clear here is how I get it to bounce back to the starting (Blazor) page?

The bit I'm now struggling with, is how do I read the cookie or otherwise tell whether I am authenticated or not.

I've implemented the Blazor Authentication (CascadingAuthenticationState) with a custom AuthenticationStateProvider, but I have no idea what to actually put in that provider?

Again I realise that this is still in flux, and I'm not necessarily expecting an answer, I really wanted to post again to highlight a similar but different scenario, so that it could be considered if it isn't already!

One other point from the above. It's not entirely obvious how to hose server side pages as well as Blazor pages, notably with the routing. I ended up doing this and it seems to work:

`            app.UseEndpoints(endpoints =>
            {
                // Map route to page purely to bounce to Microsoft Login if not authenticate.
                endpoints.MapControllerRoute(
                    "Login", 
                    "Login", 
                    new {controller = "Home", action = "Login"});

                endpoints.MapDefaultControllerRoute();
                endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html");
            });`

Thanks again, and sorry if this is all "in hand"! :)

**Comment by LaughingJohn** [comment]
Hmmm, I think I'm going around in circles, using session/cookie authentication when my token expires the call to the web api gets bounced to login.microsoftonline.com which fails because of cross site scripting because the site doesn't support CORS. Even if it did, then I guess when the session cookie from login.microsoftonline.com expires it would bounce to the login page without returning, so not sure what to do there.
This stuff is painful!

**Comment by cradle77** [comment]
@LaughingJohn this might help you :)

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1271#issuecomment-555262113

**Comment by LaughingJohn** [comment]
Thanks @cradle77, I did play around extensively with MSAL.js and may well have looked at the example you posted, I'm not entirely sure.

At the moment I have the site protected using ASP.Net core server side and this protects both the site and the API which is good.

The bit I'm still struggling with is how to tell from the client side whether I'm authenticated or not. At the moment once the token expires it just stops working (in the background the API calls are redirecting to the MSFT login page).

I'm not sure how I integrate the client/server side authentication (my server also has some Razor pages). It all seems annoyingly difficult which I appreciate may be the nature of the problem, but it's not good when security is hard to get right. Of course I may be missing something, it's not an easy journey when you're new to Blazor and Asp.net and to Javascript and Bootstrap and HTML (to any major degree) and... :(

At least securing the server side gives me confidence.

**Comment by LaughingJohn** [comment]
Maybe to be a bit clearer, I have:
1. A webassembly Blazor application 
2. A server side application that includes razor pages of its own and a web api used by the client application.

Currently:
- The first page a user sees is a server side razor page. This redirects them to log in and then takes them to the web assembly application.
- Because the user is now authenticated, the web api calls work fine until the token expires. 
- I have no way of knowing when this happens client side. So I can't pre-empt the failure of a web api call, nor can I secure individual pages of the web assembly app (and redirect the login page).

**Comment by cradle77** [comment]
Hello @LaughingJohn, 

Your scenario is complicated because you have a mix of server side pages + client side ones. Tbh I don't think this hybrid is supported by MSAL, even without Blazor in the equation :) 

If you were in a pure SPA scenario - e.g. Blazor WebAssembly calling an API - I would recommend using MSAL.js to perform the OpenID Connect flow, authenticate the user, get an Access Token for the API and then pass it in the header.

In this case, MSAL will handle the token renewal for you automatically, even prompting the user to re-authenticate if needed.

Should you opt for that solution, have a look at the package I've built, as it integrates with the Blazor object model and simplifies the marshalling between .NET and JS :)

Happy coding!

**Comment by hubert-associates** [comment]
@cradle77 nice example/lib, trying to figure what I need to change to make it work with AadB2C. Server-side/C# is clear, but JS code seems to be looking for AAD-specific endpoints... Any tips appreaciated.

**Comment by cradle77** [comment]
hello @hubert-associates, 

this is something I have in my backlog, just haven't had time yet to test it.

Long story short, it should just be a matter of replacing the Authority URL in the configuration with something like: `https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#step-5-configure-the-sample-code-to-use-your-azure-ad-b2c-tenant`
as explained here
https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#step-5-configure-the-sample-code-to-use-your-azure-ad-b2c-tenant

Let me know if it works, or feel free to [open an issue](https://github.com/cradle77/Blazor.Msal/issues/new) in my repo so I can notify you when support is there and tested :)

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/17014
