### ISSUE TITLE
Revisit and unify BadHttpRequestException

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#15038]
We need to revisit the fact that we have two different BadHttpRequestException types. They also can't be constructed by users which makes it difficult to test.

**Comment by anurse** [comment]
Proposed action:
* Create a common _non-abstract_ base type `BadHttpRequestException` in Http Abstractions
* Change Kestrel and IIS versions to inherit and obsolete them (suppressing exceptions where we create them) telling users to use the other one.

[TODO: Full API Suggestion]

**Comment by jkotalik** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/11208
