### ISSUE TITLE
Bad responses: ConnectionClose, ConnectionClose, DbMultiUpdateDapper, DbMultiUpdateDapper, DbMultiUpdateEf ...

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#15094]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| ConnectionClose | Linux, Cloud, https, KestrelSockets | 10/13/19 5:24:53 AM +00:00 | 67 |
| ConnectionClose | Linux, Cloud, http, KestrelSockets | 10/13/19 8:48:34 AM +00:00 | 908 |
| DbMultiUpdateDapper | Windows, Cloud, http, KestrelSockets | 10/16/19 9:52:44 AM +00:00 | 166 |
| DbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 10/16/19 8:38:31 PM +00:00 | 164 |
| DbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 10/15/19 12:49:12 PM +00:00 | 6 |
| DbMultiUpdateEf | Windows, Cloud, http, KestrelSockets | 10/16/19 9:53:32 AM +00:00 | 158 |
| DbMultiUpdateRaw | Windows, Cloud, http, KestrelSockets | 10/16/19 9:51:56 AM +00:00 | 130 |
| DbMultiUpdateRaw | Linux, Cloud, http, KestrelSockets | 10/16/19 8:37:45 PM +00:00 | 162 |
| MvcDbMultiUpdateDapper | Windows, Cloud, http, KestrelSockets | 10/16/19 9:55:07 AM +00:00 | 162 |
| MvcDbMultiUpdateDapper | Linux, Cloud, http, KestrelSockets | 10/17/19 12:02:06 AM +00:00 | 287 |
| MvcDbMultiUpdateEf | Windows, Cloud, http, KestrelSockets | 10/16/19 9:55:56 AM +00:00 | 140 |
| MvcDbMultiUpdateEf | Linux, Cloud, http, KestrelSockets | 10/17/19 12:02:55 AM +00:00 | 256 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by sebastienros** [comment]
ConnectionClose is back.
Analyze DbMultiUpdate

**Comment by anurse** [comment]
Soooooooooooo. Do we need this still hanging around?

**Comment by sebastienros** [comment]
Yes, these errors are still showing up and I need to investigate.

**Comment by anurse** [comment]
Not to be repetitive but this issue does keep coming up in triage and I'm not sure what (if any) action is expected from the servers team here.

Should we consider having an `area-perf` for issues that the perf v-team (and thus perf sync meeting) is responsible rather than product teams? Thoughts @sebastienros @Pilchie ?

**Comment by mkArtakMSFT** [comment]
Moving this to `5.0.0` milestone to avoid showing in during every triage

**Comment by anurse** [comment]
I'm going to move this to an `area-perf` instead and suggest we set up triaging for that in the perf sync. I don't think we should put it in 5.0.0 because it'll get lost there.
