### ISSUE TITLE
Why isn't there FromHeaderValueProvider?

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#15116]
I created custom binder for typed string `LanguageName` and marked action parameter with `FromHeader` attribute:

```CSharp
public async Task<IActionResult> DoIt([FromHeader(Name = "Accept-Language")] LanguageName languageName)
```
So my expectation was, that `ValueProvider` will be of type `FromHeaderValueProvider`, but there is no such type.

If I set type of `languageName` parameter to `string`, I see in debug mode the following output:

```
ParameterBinder: Debug: Attempting to bind parameter 'languageName' of type 'System.String' ...
HeaderModelBinder: Debug: Attempting to bind parameter 'languageName' of type 'System.String' using the name 'Accept-Language' in request data ...
SimpleTypeModelBinder: Debug: Attempting to bind parameter 'languageName' of type 'System.String' using the name 'Accept-Language' in request data ...
SimpleTypeModelBinder: Debug: Done attempting to bind parameter 'languageName' of type 'System.String'.
HeaderModelBinder: Debug: Done attempting to bind parameter 'languageName' of type 'System.String'.
ParameterBinder: Debug: Done attempting to bind parameter 'languageName' of type 'System.String'.
ParameterBinder: Debug: Attempting to validate the bound parameter 'languageName' of type 'System.String' ...
ParameterBinder: Debug: Done attempting to validate the bound parameter 'languageName' of type 'System.String'.
```

### Describe the solution you'd like
My expectation is that `values` variable in the code below
```CSharp
var name = bindingContext.ModelName;
var values = bindingContext.ValueProvider.GetValue(name).Values;
```
will contain value from `Accept-Language` header extracted by `FromHeaderValueProvider` with corresponding `BindingSource`.

**Comment by pranavkm** [comment]
Thanks for the issue report @voroninp. We'll take a look at this as part of the 5.0 release.

**Comment by pranavkm** [comment]
Do you have a minimal repro app you could share?

**Comment by voroninp** [comment]
@peckham , https://github.com/voroninp/NoFromHeaderValueProvider

**Comment by voroninp** [comment]
@pranavkm , and regarding headers where priorities are allowed, would be nice to have out of the box method to extract a sequence of values with their priorities ;-)

**Comment by rynowak** [comment]
The reason why we didn't do a value provider for headers is that:
- value providers are global
- HTTP headers use a bunch of names that are common nouns like "Host"

The result would be having model fields populated with protocol-related details, which would be genuinely surprising.

This is just the background on why didn't implement header binding this way, I 💯 agree we should make this better, but the solution will be different.

**Comment by voroninp** [comment]
@rynowak  It would be very cool, if deserialization/model binding supported advanced stuff out of the box.

For example, I would like to get a property of type `UserId` which is a type safe wrapper of `Guid` rather than a plain `Guid` value. Or the support for discriminated unions.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do.
