### ISSUE TITLE
No documentation on how to create custom SignalR Core Scaleout

### ISSUE THREAD

**Issue by georgiosd** [dotnet/aspnetcore#15139]
All the information that's on the Internet refers to ASP.NET SignalR, there's nothing I could find in SignalR Core on how to implement our own scaleout solution.

Any pointers?

**Comment by BrennanConroy** [comment]
I'd recommend taking a look at the Redis implementation for starters. https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs

In general, you're taking a few parameters (target and arguments usually) and figuring out what type of message to create and where to send it.

**Comment by anurse** [comment]
Yeah, we don't have docs on this as it's a relatively advanced scenario and it hasn't been a priority. We're happy to help answer questions you may have though.

**Comment by georgiosd** [comment]
Thank you guys, I'll come back with questions when I get a chance to look at this.
