### ISSUE TITLE
Allow showing invalid input values on data bound properties

### ISSUE THREAD

**Issue by jjamid** [dotnet/aspnetcore#15195]
I am using Blazor server and trying to show clear error messages about invalid inputs so that the user doesn't guess why their keyboard is suddenly not working.
The current behavior blocks/reverts invalid inputs which is very not user-friendly since it provides no feedback at all and dismisses the action without informing the user.
It also forces the user to start all over instead of just fixing the input in some cases.

The documentation states that: 
_“the reversion occurs after any keystroke that introduces an unparsable value. When targeting the oninput event with an int-bound type, a user is prevented from typing a . character. A . character is immediately removed, so the user receives **immediate feedback** that only whole numbers are permitted”_
This is plain wrong. A typical user is not looking at the screen while typing so they actually **don't get any feedback** and they might continue typing or even not notice that something has undone their work or that the paste operation was cancelled or its text shortened.

There should be an option so the framework doesn't meddle with the input entered by the user, even for example when entering a string in a text box that only allows a date or a number.
This will allow us to show a clear message (e.g. "This maximum allowed length is 50, please shorten your comment, or the number 115 is larger than 114).
This behavior exists in other frameworks at least as a choice (e.g. angular through ngModelOptions  => allowInvalid)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
