### ISSUE TITLE
Blazor: Default template and wrong reference count

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#15190]
Using the default template and looking at the Code Lense reference count:

![image](https://user-images.githubusercontent.com/8482283/67144616-b6e57880-f278-11e9-88a5-40a7f0e1d22c.png)

**Comment by javiercn** [comment]
@Postlagerkarte Thanks for contacting us.

@NTaylorMullen @ajaybhargavb I believe this would have something to do with FindAllReferences? 

Can this be caused by `@inject WeatherForecastService` being present in the design and implementation files for the component?

**Comment by NTaylorMullen** [comment]
Yas there was a duplicate VSTS issue for this that I can't for the life of me find now. I asked @jasonmalinowski to take this over.

**Comment by mkArtakMSFT** [comment]
Closing as we track this as an external issue
