### ISSUE TITLE
Add "show all routes" command line tool

### ISSUE THREAD

**Issue by TangMonk** [dotnet/aspnetcore#15206]
In Rails, there is `$rake routes` to list all available routes, it is useful on development

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TangMonk.
There is enough extensibility, however, for anybody to create such a tool.

@rynowak do you think this will be valuable to be part of the framework?

**Comment by mkArtakMSFT** [comment]
Moving this to the backlog.

**Comment by Rick-Anderson** [comment]
@rynowak if you can give me the code to do this, I'll document it in [Routing to controller actions](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.0)

I've seen lots of customer requests for this. It doesn't need to be a formal tool.

**Comment by javiercn** [comment]
The nature of routing in ASP.NET Core requires the app to run for us to know the set of routes. This is not something we have received much feedback about and the list of configured routes is accessible at runtime via introspection of EndpointDataSource.

What we recommend is that people use EndpointDataSource to create an endpoint they can list the routes from during development for debugging purposes or other development related tasks.
