### ISSUE TITLE
Provide a sample showing how EF and Blazor WASM work together

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#15224]

**Comment by mkArtakMSFT** [comment]
@JeremyLikness is this something you're working on? Do you track it somewhere else?

**Comment by JeremyLikness** [comment]
@mkArtakMSFT the answer isn't simple. We are working on guidance for Blazor Server. Right now there aren't any EF-compatible databases directly accessible from Wasm (this may change with SQLite and Cosmos DB, but I'm not aware of those working in general cases right now), so it doesn't make sense to have EF in the browser. Any EF-interaction would be a classic case of standing up Web APIs with EF on the server and accessing from the client using REST/OData/GraphQL/gRPC-Web.

**Comment by mkArtakMSFT** [comment]
Thanks Jeremy. I am going to close this issue as you're going to provide guidance for Blazro Server. It seems this issue was supposed to be for Blazor Server (given this is dated October).
