### ISSUE TITLE
Problem Dockerizing Blazor WebAssembly App

### ISSUE THREAD

**Issue by SantosRay** [dotnet/aspnetcore#15222]
### The application is building and running fine but when I try to build a docker image I get the following:

 Building settings-spa
Step 1/14 : FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
 ---> 6b6086a5fb0e
Step 2/14 : WORKDIR /src
 ---> Using cache
 ---> 86fad60764f9
Step 3/14 : COPY ["src/Settings/Settings.Client/Settings.Client.csproj", "src/Settings/Settings.Client/"]
 ---> Using cache
 ---> 895040b3d1a5
Step 4/14 : COPY ["src/Settings/Settings.Shared/Settings.Shared.csproj", "src/Settings/Settings.Shared/"]
 ---> 349130dffcb3
Step 5/14 : COPY "src/Settings/Settings.Client/NuGet.Config" .
 ---> a84ed9e4b59c
Step 6/14 : RUN dotnet restore --configfile "NuGet.Config" "src/Settings/Settings.Client/Settings.Client.csproj"
 ---> Running in a398423cb511
  Restore completed in 7.48 sec for /src/src/Settings/Settings.Shared/Settings.Shared.csproj.
  Restore completed in 17.24 sec for /src/src/Settings/Settings.Client/Settings.Client.csproj.
Removing intermediate container a398423cb511
 ---> 93864453468e
Step 7/14 : COPY . .
 ---> ada90b0193d1
Step 8/14 : RUN dotnet build "src/Settings/Settings.Client/Settings.Client.csproj" -c Release -o /app/build
Microsoft (R) Build Engine version 16.3.0-preview-19426-01+faf5e5d75 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 2.17 sec for /src/src/Settings/Settings.Shared/Settings.Shared.csproj.
  Restore completed in 2.16 sec for /src/src/Settings/Settings.Client/Settings.Client.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  Settings.Shared -> /app/build/CyberBizSoft.TAE.Settings.Shared.dll
  Settings.Client -> /app/build/CyberBizSoft.TAE.Settings.Client.dll
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
    - The following frameworks were found:
        3.0.0-preview9-19423-09 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

====================================================================================

### After adding global.json with:
{
  "sdk": {
    "version": "3.0.0-preview9-19423-09"
  }
}
================================================================

===========================================================
Step 8/14 : RUN dotnet build "src/Settings/Settings.Client/Settings.Client.csproj" -c Release -o /app/build
 ---> Running in 5f9c3def1535
A compatible installed .NET Core SDK for global.json version [3.0.0-preview9-19423-09] from [/src/global.json] was not found
Install the [3.0.0-preview9-19423-09] .NET Core SDK or update [/src/global.json] with an installed .NET Core SDK:
  3.0.100-preview9-014004 [/usr/share/dotnet/sdk]

================================================================
 dotnet --info 
=============================================================
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview1-014459
 Commit:    ac3b59712d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview1-014459\

Host (useful for support):
  Version: 3.1.0-preview1.19506.1
  Commit:  bbf5542781

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
===========================================================================================================================

Any ideas?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SantosRay.
You're using older bits, please update to the latest release.
Also, we are aware of certain issues in Blazor WASM with Docker, which we will be covering for the Blazor WASM release in May. For now to work around these issues you should try setting the below setting:
`<ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>`

**Comment by endeffects** [comment]
I have the same issue with .net core 3.1 preview. The available framework on docker for me is .net core 3.0 final. I've installed visual studio preview 2 and .net core 3.1 preview 1.

**Comment by SantosRay** [comment]
Thanks @mkArtakMSFT, 

I am using one of the latest preview, 3.1.100-preview1-014459 Visual Studio 16.4.0 preview 2, with the same results, but I downgraded trying to make it work.

I will upgrade and try again with your suggestion; <ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>

Best

**Comment by SantosRay** [comment]
Well, I upgraded to the latest preview again, 

`<ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.1.0-preview1.19508.20" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="3.1.0-preview1.19508.20" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.1.0-preview1.19508.20" PrivateAssets="all" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="2.2.0" />
  </ItemGroup>`

added the `<ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>` 

but unfortunately it did not work:

Step 8/14 : RUN dotnet build "src/Settings/Settings.Client/Settings.Client.csproj" -c Release -o /app/build
 ---> Running in 72bfb660792d
Microsoft (R) Build Engine version 16.3.0-preview-19426-01+faf5e5d75 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 323.14 ms for /src/src/Settings/Settings.Shared/Settings.Shared.csproj.
  Restore completed in 353.71 ms for /src/src/Settings/Settings.Client/Settings.Client.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  Settings.Shared -> /app/build/CyberBizSoft.TAE.Settings.Shared.dll
  Settings.Client -> /app/build/CyberBizSoft.TAE.Settings.Client.dll
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '3.1.0-preview1.19506.1' was not found.
    - The following frameworks were found:
        3.0.0-preview9-19423-09 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

BTW, I also tried with: 

RUN dotnet build "src/Settings/Settings.Client/Settings.Client.csproj" -c Debug -o /app/build
 
in the dockerfile, but it did not work either

**Comment by mkArtakMSFT** [comment]
From @rynowak "This likely have to do with our command-line tools, that we run inside the build"

**Comment by javiercn** [comment]
The original build issue is gone

**Comment by javiercn** [comment]
This was fixed as part of https://github.com/dotnet/aspnetcore/pull/18409

**Comment by otaskiran** [comment]
Hi,
How can resolve this issue?
020-03-21T13:17:23.190991431Z   An assembly specified in the application dependencies manifest (XXXXX.deps.json) was not found:
2020-03-21T13:17:23.190997031Z     package: 'Blazored.LocalStorage', version: '2.1.1'
