### ISSUE TITLE
Perf workflow tool

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#15241]
We want a tool that helps investigate perf regressions.

The current thought is to create a custom widget on our Power BI page.

* Click on two points on the graph
* Show a side-by-side of differences between the points
e.g.

Category | Point1 | Point2
-- | -- | --
RPS | 1,305 | 2,100
CPU | 35 | 43
etc. | # | #

* Can copy text from widget (might need a "copy to clipboard" button for everything?)
* Auto generate GitHub commit diff links for aspnetcore and corefx repos (and extensions/ef?)
* `Stretch Goal`: Generate command line to run benchmark
* `Super Stretch Goal`: Ability to automatically find regression commit(s) (by running benchmarks with all the differing commits and figuring out the regression)

**Comment by davidfowl** [comment]
![image](https://user-images.githubusercontent.com/95136/67708295-23e3c700-f979-11e9-9ee8-71199b21c52f.png)

**Comment by dougbu** [comment]
Nice drawing

**Comment by dougbu** [comment]
@davidfowl @BrennanConroy @sebastienros another great idea. Is this something that we'll do❔

**Comment by adityamandaleeka** [comment]
We have most of this at this point. Closing this issue.

cc @sebastienros
