### ISSUE TITLE
Binding UI Controls to Dynamic Object

### ISSUE THREAD

**Issue by PKYADAV** [dotnet/aspnetcore#15244]
Dear Team, I am trying to bind dynamic object to UI controls like below

```
@using Newtonsoft.Json;
@using System.Dynamic;

@if (sections == null)
{
    <p>Loading... Please wait...!</p>
}
else
{
<fieldset>
    <legend>@sections.section</legend>
    @if (sections.controls != null)
    {
        foreach (dynamic control in JsonConvert.DeserializeObject<List<Object>>(sections.controls))
        {
             if (control.type == "DATETIME")
            {
                <input type="datetime" @bind="@bindObject.date" />
            }
            else if (control.type == "TYPE")
            {
                <input @bind="@bindObject.type" />
            }
            else
            {
                <input type="text" @bind="@bindObject.id" />

            }
        }
    }
    else
    {
        <p>Ops! No controls found !!</p>
    }
</fieldset>
}

@code {
    [Parameter]
    public dynamic sections { get; set; }

    dynamic bindObject = new ExpandoObject();

    protected override void OnInitialized()
    {
        bindObject.id = "1001";
        bindObject.date = DateTime.Now;
        bindObject.type = "TEST";
    }
}

```
Error:

> Error	CS1963	An expression tree may not contain a dynamic operation

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @PKYADAV.
We'll look into collecting more feedback regarding this ask. For now this is not supported.

**Comment by PKYADAV** [comment]
Can we get some deadline as we are targeting dynamic ERP using AspNet Core and Cosmos Db?

**Comment by mkArtakMSFT** [comment]
@PKYADAV we don't have any plans to provide this capability in the near future. Don't plan for this to be available any time soon.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
