### ISSUE TITLE
Prerendering client-side blazor and authorization

### ISSUE THREAD

**Issue by Infactum** [dotnet/aspnetcore#15253]
I'm trying to use prerendering in client side application. Some pages uses http requests to backend REST service which requires authorization. Authorization itself is based on AspNet Identity.  
It seems that there is no way to archeive valid client auth state during prerendering now.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Infactum.
We plan to provide guidance about this in the future.
For now, here is some high level guidance.
Because the prerendering is happening on the server, you can have all your auth-related logic exposed through some interface and different implementations registered in the DI. Your actual app should then consume that service to run auth logic, and based on whether it's prerendering or not it will use the right implementation to work.

**Comment by sabitertan** [comment]
@Infactum If I understand right this repo should be answer : https://github.com/MV10/BlazorOIDC

I am also using MV10's idea in a conjuction with 

https://github.com/IdentityModel/IdentityModel.AspNetCore

 to add token sharing/management with 3rd party HttpClients.
Also this is an experimental Hybrid solution that uses oidc-client-js with JSInterop:
https://github.com/sabitertan/BlazorAspnetHostedOidcJS

I am working on a sample using IdenityModel only. Hope to finish up and share :)

**Comment by javiercn** [comment]
These are the steps you need to follow if you are using our current auth support.

## Steps for supporting auth + prerendering on Blazor applications.
* The app will prerender paths for which  authorization is not required.
* Paths for which authorization is required will not be prerendered.

1. On your Client/Program.cs factor common service registrations into a separate method.
2. On your Server/Startup.cs register the services required for the UI and the applicaation to work.
  ```csharp
  services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();
  services.AddScoped<SignOutSessionStateManager>();

  Client.Program.ConfigureCommonServices(services);
  ```
3.  Replace `endpoints.MapFallbackToFile("index.html")` with `endpoints.MapFallbackToPage("/_Host")`

4. Create a `_Host.cshtml` page inside the pages directory, paste the contents from index.html into it and replace the `<app>Loading...</app>` tag with the following:
  ```razor
  <app>
      @if (!HttpContext.Request.Path.StartsWithSegments("/authentication"))
      {
          <component type="typeof(Wasm.Authentication.Client.App)" render-mode="Static" />
      }
      else
      {
          <text>Loading...</text>
      }
  </app>
  ```
