### ISSUE TITLE
Add test automation for Alpine

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#15277]
We should have test automation on Alpine, perhaps as part of migration to Helix.

**Comment by dougbu** [comment]
@halter73 which of the many Helix-compatible images from https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-master.json should we use to cover this requirement❔ If there's a recommendation, should be as simple as adding another line to the full matrix queues listed in eng\targets\Helix.Common.props.
