### ISSUE TITLE
`dotnet dev-certs https --clean` should clean the certs generated for Docker profile

### ISSUE THREAD

**Issue by ArieShout** [dotnet/aspnetcore#15357]
### Describe the bug
When I debug the ASP.NET Core application using the Docker profile in Visual Studio, a `pfx` certificate will be generated in `C:\Users\<user>\AppData\Roaming\ASP.NET\Https\<project-name>.pfx`. If later I switched to use the "project" debug profile, it will use this certificate rather than the one in the system certificates store (the same in Visual Studio and `dotnet run`). `dotnet dev-certs https --clean` or `dotnet dev-certs https --trust` won't affect this certificate file.

After one year of development, I had the issue that the dev certificate (the file) was expired.

The certificate is named as `<project-name>.pfx`, so checking out the source to a new directory and start the VS from the new location won't help.

### To Reproduce
1. Create an ASP.NET Core application with Docker debug profile enabled in Visual Studio
1. Debug with Docker profile, when prompt to generate and trust dev certs, accept with yes.
1. Switch to the project debug profile, and do dev/test
1. Wait for 1 day, run `dotnet dev-certs https --clean` and `dotnet dev-certs https --trust`
1. Start the application, launch browser and check the certificate valid period. **The start date is a day before**.
1. [Kidding] Wait for 1 year. Start the application, launch the browser, and the browser will report the invalid certificate issue

### Expected behavior
`dotnet dev-certs https --clean` should remove the certificate files used by the Docker profile (as tested, it will also be picked up by normal debug profiles, if present).

### Additional context
Include the output of `dotnet --info`

```
λ dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100
 Commit:    04339c3a26

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@ArieShout thanks for contacting us.

I'm not sure how you are running into an issue here. Kestrel will only try to load the certificate in `C:\Users\<user>\AppData\Roaming\ASP.NET\Https\<project-name>.pfx` if someone specified the password through config. `Kestrel: { Certificates: { Development: { Password } }`

The IDEs are configured to check for the validity of the certificate but they likely cache the results of the call for the certificate once they've checked the first time. What has likely happened is that the IDE has cached the result and the certificate has become invalid while you had it open.

`dotnet dev-certs https --trust` should always generate a new certificate if there is an expired one.
WRT to the certificate in `C:\Users\<user>\AppData\Roaming\ASP.NET\Https\<project-name>.pfx` it's up to the docker tools to clean that up.

I'll check with them to see if there is an issue in the way they are running the tool or if there is an issue with the tool itself.

**Comment by anurse** [comment]
That sounds like an idea, but not one that's a very high priority TBH. No matter what we choose, it's always going to be possible to hit this problem, we're just making the window longer.

If we did think this was worth doing, I'd suggest doing it directly in the tool by having it look at the list of certs provided by the CertificateManager and checking if any are going to expire in say, a month. Cookie auth does a similar sliding refresh when 50% of the validity period has elapsed (so say, 1 month if the cookie is valid for 2 months) so there's some precedent for this, **but** Cookie auth is also able to silently renew the token. Certificates can't always be silently recreated (since we have to mark the new cert as trusted).

More interesting to me would be to have Kestrel report a log message with something like "The developer certificate is present but has expired." so you know what to do when it **does** fail. I believe right now it will just fail to find the cert.

**Comment by ArieShout** [comment]
When I hit the problem, I tried:

1. run `dotnet run` in the project from command line
1. clean build the project in IDE
1. restart IDE
1. `dotnet dev-certs https --clean` and then `dotnet dev-certs https --trust`
1. checkout the source in another directory, and start the IDE from that project location

All these tries picked the expired certificate in `AppData` directory. I can see new certificates gets generated and installed in the certificate store after `--clean` and `--trust`, but the running project just didn't pick up the certificate there.

I spent a long time on this until I found the doc here https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#docker---certificate-not-trusted . Went to the `AppData` folder and I saw the expired certificates. Deleted them and everything went back working again.

I can see the certificate were protected by password, however, I didn't specify `Kestrel: { Certificates: { Development: { Password } }` anywhere in my application configuration. I wonder if the IDE just injected the password into the `dotnet user-secrets` store.

If we're not going to fix this, probably we can add some documentation on trouble shooting in https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#windows---certificate-not-trusted

**Comment by javiercn** [comment]
@ArieShout Thanks,

It might be an issue with the docker tooling, we'll get someone to look at it.

**Comment by Rick-Anderson** [comment]
@ArieShout  wrote:
> I spent a long time on this until I found the doc [Troubleshoot certificate problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#docker---certificate-not-trusted ).  `Per the docs`: Went to the AppData folder and I saw the expired certificates. Deleted them and everything went back working again.

If we're not going to fix this, probably we can add some documentation on trouble shooting in [Troubleshoot certificate problems](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#docker---certificate-not-trusted ). 

@ArieShout  what do you suggest I add to the docs?  Can you suggest an edit to my `H3` to increase SEO juice?

Sounds like the docs had the right solution.

**Comment by mkArtakMSFT** [comment]
Thanks @Rick-Anderson.
Closing this as there is no more action pending for us here.
