### ISSUE TITLE
SVG <text> tag flags an error in one case, but not in another.

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/aspnetcore#15378]
The following razor code flags a compile error that the `<text> `shouldn't have any attributes because it is interpreting `<text>` as the razor literal text tag.

```
    @foreach (var designObject in ToolService.DesignObjects)
         {
             switch(designObject)
             {
                 case ImageObjectModel imageObjectModel:
                     break;
                 case TextObjectModel textObjectModel:
                     <text @x="@textObjectModel.Coordinate.X" @y="@textObjectModel.Coordinate.Y" class="small"></text>
                     break;
             }
         }
```

On another component's razor code, the following doesn't flag an error:

```
<text class="text" x="@Coordinate.X" y="@Coordinate.Y" >@CustomText</text>

@code
{
    [Parameter]
    public string CustomText { get; set; } = "Custom Text";
    public string FontStyle { get; }
}

```

Why isn't razor interpreting the `<text> `tag the same way in both cases?

**Comment by javiercn** [comment]
@Joebeazelman thanks for contacting us.

@NTaylorMullen is this the editor or the compiler.

**Comment by NTaylorMullen** [comment]
Compiler. Definitely an interesting use-case for SVG which would be ideal to support. I'm not sure what we can really do so marking it as needs-design even though there's a chance we close this as by-design.

**Comment by Joebeazelman** [comment]
> Compiler. Definitely an interesting use-case for SVG which would be ideal to support. I'm not sure what we can really do so marking it as needs-design even though there's a chance we close this as by-design.

**Comment by Joebeazelman** [comment]
> @Joebeazelman thanks for contacting us.
> 
> @NTaylorMullen is this the editor or the compiler.

Do you want me to attach the two razor files in question?

**Comment by NTaylorMullen** [comment]
> Do you want me to attach the two razor files in question?

Sure that'd be helpful

**Comment by Joebeazelman** [comment]
> > Do you want me to attach the two razor files in question?
> 
> Sure that'd be helpful
Attached two of the files. They are not dependent on each other and won't compile, but they should show the issue in context.

[Archive.zip](https://github.com/aspnet/AspNetCore/files/3774410/Archive.zip)

**Comment by mkArtakMSFT** [comment]
Closing as we will be tackling this as part of #18271
