### ISSUE TITLE
ASP.NET Core 3.0 catch-all route unexpected behavior

### ISSUE THREAD

**Issue by ExileLee** [dotnet/aspnetcore#16579]
### Describe the bug
Recently i encounter some unexpected issue

I'm using ASP.NET Core 3.0 and i defined two routes in StartUp.cs

**StartUp.cs**
```
   app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "file",
            pattern: "{controller=File}/folder/{*path}",
            new { Action = "Folder" });

        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=File}/{action=Index}/{filename}");
    });
```
**FileController.cs**
```
public class FileController : Controller
{
    public IActionResult Folder(string path)
    {
        return Ok(path);
    }

    public IActionResult Index(string filename)
    {
        return Ok(filename);
    }
}
```
request to file/folder/abc/abc i expected to match first route but the result was 404 not found

but if i changed order of route

```
   app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=File}/{action=Index}/{filename}");

        endpoints.MapControllerRoute(
            name: "file",
            pattern: "{controller=File}/folder/{*path}",
            new { Action = "Folder" });
    });
```
It work!

### Expected behavior
My questing is why first version don't work if i defined `{controller=File}/folder/{*path}` on top

I thought it will check route table sequentially

**Comment by javiercn** [comment]
@ExileLee thanks for contacting us.

I believe with endpoint routing even "traditional" routes are not routed sequentially (@rynowak can correct me) but are treated in "precedence" order, that means, more specific routes like `/literal/literal/literal` take precedence over `/literal/{parameter}/literal`.

That said, I don't think why your first route wouldn't match.
@rynowak Thoughts? I don't see why the first route wouldn't match.

**Comment by ExileLee** [comment]
If i only confiure one route
```
   endpoints.MapControllerRoute(
            name: "file",
            pattern: "{controller=File}/folder/{*path}",
            new { Action = "Folder" });

```
it will match 

but following code will end up 404 not found
```
        endpoints.MapControllerRoute(
            name: "file",
            pattern: "{controller=File}/folder/{*path}",
            new { Action = "Folder" });

        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=File}/{action=Index}/{filename}");

```

**Comment by rynowak** [comment]
This is definitely a bug. Adding additional routes shouldn't make something turn into a 404.

Here's a comparison:

**Broken**

![image](https://user-images.githubusercontent.com/1430011/68550876-f60c7280-03bb-11ea-89d5-c7bce1fa203e.png)

**Working**

![image](https://user-images.githubusercontent.com/1430011/68550894-1a684f00-03bc-11ea-8ff3-17f37904b572.png)

We're not building the same graph here depending on the ordering.
