### ISSUE TITLE
@ref="this.Menu" not updating the "this.Menu" variable

### ISSUE THREAD

**Issue by rpc-scandinavia** [dotnet/aspnetcore#16571]
### Describe the bug
I have a problem with a @ref="this.Menu" not setting the "this.Menu" variable when updating.
I am creating a Blazor/Razor app using MatBlazor, and you can see the example using the MatMenu here:

[https://www.matblazor.com/Menu](https://www.matblazor.com/Menu)

Everything works fine in my application, both in Blazor (client-side) and in Razor (server-side).
However when I change culture/localization and thus generate new elements, the "this.Menu" variable is not updated.

I do call "base.StateHasChanged()" when updating the culture, and I have confirmed through inspection in the browser, that the elements are re-generated in the correct language, but without the @ref variable being updated.

### Additional context
`$ dotnet --info
.NET Core SDK (reflecting any global.json):
Version:   3.1.100-preview1-014459
Commit:    ac3b59712d
Runtime Environment:
OS Name:     debian
OS Version:  10
OS Platform: Linux
RID:         debian.10-x64
Base Path:   /usr/share/dotnet/sdk/3.1.100-preview1-014459/
Host (useful for support):
Version: 3.1.0-preview1.19506.1
Commit:  bbf5542781
.NET Core SDKs installed:
3.0.100 [/usr/share/dotnet/sdk]
3.1.100-preview1-014459 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0-preview1.19506.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download`

**Comment by mrpmorris** [comment]
You can't pass references like that.

Instead, change your parameter type to `Func<ElementRef>` and make sure your child component reads it in OnAfterRender.

**Comment by rpc-scandinavia** [comment]
Thank you @mrpmorris.
But I do not understand, because I use the @ref to GET the component object rendered (ComponentBase descendent) representing the MatMenu element in managed code.
As I understand, you sugest that I provide a method which return a compoent.

But it initially works, until I change the components (a new MatButton with a new MatMenu).
Perhaps I did not say, but I am not in the child-component, but in the component containing the MatButtun and the MatMenu, and I need the reference to open/show the menu with:

`await this.Menu.OpenAsync();`

Microsoft uses a variable/field here (under "Capture references to components"):
[https://docs.microsoft.com/nb-no/aspnet/core/blazor/components?view=aspnetcore-3.0#chained-bind](https://docs.microsoft.com/nb-no/aspnet/core/blazor/components?view=aspnetcore-3.0#chained-bind)

**Comment by mrpmorris** [comment]
@rpc-scandinavia The MS example doesn't show when they call OnSomething. Can you provide a link to the code where you are doing this?

**Comment by rpc-scandinavia** [comment]
@mrpmorris The OnSomething event method is probably called by a button, which should show the MyLoginDialog.

My code is like the MatMenu example, where the MatMenu submenu is opened/shown when the MatButton is clicked. In my code I just handle more menus, because it is a row of menu buttons, which each might have a sub menu. Okay, let me try to show some of my code:

1) I have a RecordMenu class with among others these properties:

```
public class RecordMenu {
	public Guid Guid
	public String Icon
	public String Name
	public String Url
	public List<RecordMenu> Children
}
```

2) I have a class to handle each set of references:

```
public class MatMenuReference {
	public ForwardRef Item1 = new ForwardRef();
	public BaseMatMenu Item2 = null;
} // MatMenuReference
```

3) In the ".razor" file:

```
<!-- Titlebar menu -->
@foreach (RecordMenu menuRecord in this.menuRecords) {
	<MatButton RefBack="@this[menuRecord].Item1" Icon="@(menuRecord.Icon)" Label="@(menuRecord.Name)" OnClick="(async (e) => await this.MenuItemClickedAsync(e, menuRecord))">
	</MatButton>
	@if (menuRecord.Children.Count > 0) {
		<MatMenu @ref="this[menuRecord].Item2" TargetForwardRef="@this[menuRecord].Item1">
			<MatList>
				@foreach (RecordMenu childMenuRecord in menuRecord.Children) {
					<MatListItem OnClick="(async (e) => await this.MenuItemClickedAsync(e, childMenuRecord))">@(childMenuRecord.Name)</MatListItem>
				}
			</MatList>
		</MatMenu>
	}
}
```

4) In the ".ca.razor" file I have this:

```
public List<RecordMenu> menuRecords;
private Dictionary<String, MatMenuReference> references;

protected async Task MenuItemClickedAsync(MouseEventArgs e, RecordMenu menuRecord) {
	// Navigate to the clicked page.
	this.navigation.NavigateTo(menuRecord.Url);

	// Open the clicked sub menu.
	if ((menuRecord.Children.Count > 0) && (this[menuRecord].Item2 != null)) {
		await this[menuRecord].Item2.OpenAsync();
	}
} // MenuItemClickedAsync


// I use this to handle multiple menus, that potentially can have children (a sub-menu).
protected MatMenuReference this[RecordMenu menuRecord] {
	get {
		if (this.references.ContainsKey(menuRecord.Guid.ToString()) == false) {
			this.references.Add(menuRecord.Guid.ToString(), new MatMenuReference());
		}
		return this.references[menuRecord.Guid.ToString()];
	}
} // this
```

So the component is initialized and loads the "menuRecords" in the current culture, and this works as expected. The submenu opens when the button is clicked. I can see that the value in "this[menuRecord].Item2" is set and not null (I write this to the console in MenuItemClickedAsync).

When I change culture, the "menuRecords" are cleared and populated with menu items in the new culture. The component is renderes and everything changes as expected, but the "this[menuRecord].Item2" is null.

When I change back to the original culture, it opens the sub-menu because the "references" dictionary still holds the values for the other "menuRecords". Insted of changing back to the first culture, I can hit F5 to reload the page in the browser, and after the relod the second culture work and opens the sub-menu. But naturally I can not change back to the first culture and open the sub-menu without a F5.

I just wrote this to clerify what I am doing, but my take is still that the problem is that the "@ref="this[menuRecord].Item2"" do not set the field/variable when a new MatMenu is rendered.

And Yes, I also tried without using my "references" dictionary, and just a simple field/variable in a senario with just one sub-menu.

I guess that somewhere inside the "ComponentBase" class, it sets the field given in the @ref attribute, to either "this" or a element-reference object when the field's type is "ElementReference". Perhaps I should take a look, if it is not too complicated  :)

**Comment by rpc-scandinavia** [comment]
I was looking around, and it is not that simple as a assignment in the "ComponentBase" class.
But I looked in the generated ".razor.g.cs" file and found where the assignment occures:

```
__builder7.AddComponentReferenceCapture(98, (__value) => {
#nullable restore
#line 47 "...long path.../TemplateDefault.razor"
**this[menuRecord].Item2 = (MatBlazor.MatMenu)__value;**
#line default
#line hidden
#nullable disable
}
);
```

Next step is to find out, why this is not called everytime the component is rendered.

**Comment by javiercn** [comment]
@rpc-scandinavia Thanks for contacting us.

Your case is a bit complicated, if you have a repro-project that would help us provide a better answer.

In general, references are populated/updated while we diff component trees and are only available for use after the UI update has been applied in the Browser (this is, they are available during OnAfterRender)

Components can render independently (a parent rendering doesn't mean that a child re-renders and vice-versa) so you can't know from within a child component when an element reference from a parent will be valid.

Only the component holding on to the element reference can know when it is valid (inside the OnAfterRender method, pretty much)

One thing you could try (and I'm not sure I understand your sample completely) is to pass the parent component as a parameter to the child component, and expose there some functionality for the child to associate some code that runs whenever the parent component finishes rendering and reacts accordingly.

**Comment by mrpmorris** [comment]
The click occurs after render, but are you storing the references away somewhere before that? Try the `Func<ElementReference>` approach and only evaluate them after rendering.

**Comment by rpc-scandinavia** [comment]
@mrpmorris Thanks for your input.
Yes, the click occurs after render, and everything look okay in the browser when I inspect the markup code. When trying to pass a "Func<ElementReference>" to the @ref, I get a build error:

`Components/Templates/TemplateDefault.razor(47,77): error CS0029: Cannot implicitly convert type 'MatBlazor.MatMenu' to 'System.Func<Microsoft.AspNetCore.Components.ElementReference>'
`

Please educate me if I am wrong, but I understant it as "ElementReference" is just a numeric id, and is used for JS interop. I looked at the source code for "ElementReference" and do not see anything different. The biggest thing is that MS hides the number of id's generated when sending the data over the wire to Blazor.

I need the native object of type MatMenu so I can call its "OpenAsync" method. And it initially works, until I change culture and thereby renders new MatMenu elements.

**Comment by rpc-scandinavia** [comment]
I have been playing around and writing stuff to the console. Maybe I am wrong, but I suspect that there are some reuse of elements going on, when rendering.

My two languages have an unequal number of menus, and when I change from the language with few menu items to the language having many menu items, the first number of MatMenuReference classes do not get populated, when changing to the language with many menu items.

```
protected override void OnAfterRender(bool firstRender) {
Console.WriteLine($"===============================================");
	foreach (String key in this.references.Keys) {
		Console.WriteLine($"Render: Id: {this.references[key].Item1.Current.Id}  Menu: {this.references[key].Item2}");
	}
}
```

First render with 5 menu items (one has a sub-menu):

```
=================================================================
Render: Id: 2c88b1b7-909b-4731-9c9c-0a53b456ae61  Menu:
Render: Id: 98e2ac43-a3a4-4932-9390-2b4d4daaea45  Menu:
Render: Id: 11bef403-bafe-4fa7-8cf5-94770455b20f  Menu:
Render: Id: b7dbef7f-3d52-4245-9ee7-f3c3e1aba5cf  Menu:
Render: Id: 5229f0b0-e611-4d21-a5ca-50a575fdf129  Menu:
Render: Id: cbfdc4b4-4fee-4876-bf92-b2aab9f2cbe8  Menu:
Render: Id: 9e2763a6-5028-4945-b9bf-5eda80b31f0e  Menu: MatBlazor.MatMenu
```
Second render after change to the other language with 7 menu items (one has a sub-menu) and clearing the "this.references":

```
=================================================================
Render: Id:   Menu:
Render: Id:   Menu:
Render: Id:   Menu:
Render: Id:   Menu:
Render: Id:   Menu:
Render: Id: 50e6f8ce-ea57-4e35-af3c-abbd2eb57e02  Menu:
Render: Id: ac41248b-3044-438f-9e5f-bd9e6f14e305  Menu:
```

The "Item2" which is the MatMenu is still not populated, but the Item1 are, they are MatBlazor specifig ForwardRef that inturn contains a ElementReference used for JS interop to actually open/show the sub-menu.

**Comment by rpc-scandinavia** [comment]
Okay, I actually got it to work. Still testing, but from my code abowe I changed the ".razor" file from:

```
<!-- Titlebar menu -->
@foreach (RecordMenu menuRecord in this.menuRecords) {
	<MatButton RefBack="@this[menuRecord].Item1" Icon="@(menuRecord.Icon)" Label="@(menuRecord.Name)" OnClick="(async (e) => await this.MenuItemClickedAsync(e, menuRecord))">
	</MatButton>
	@if (menuRecord.Children.Count > 0) {
		<MatMenu @ref="this[menuRecord].Item2" TargetForwardRef="@this[menuRecord].Item1">
			<MatList>
				@foreach (RecordMenu childMenuRecord in menuRecord.Children) {
					<MatListItem OnClick="(async (e) => await this.MenuItemClickedAsync(e, childMenuRecord))">@(childMenuRecord.Name)</MatListItem>
				}
			</MatList>
		</MatMenu>
	}
}
```

To:

```
<!-- Titlebar menu -->
@if (menuRecord.Children.Count > 0) {
	@foreach (RecordMenu menuRecord in this.menuRecords) {
		<MatButton RefBack="@this[menuRecord].Item1" Icon="@(menuRecord.Icon)" Label="@(menuRecord.Name)" OnClick="(async (e) => await this.MenuItemClickedAsync(e, menuRecord))">
		</MatButton>
		<MatMenu @ref="this[menuRecord].Item2" TargetForwardRef="@this[menuRecord].Item1">
			<MatList>
				@foreach (RecordMenu childMenuRecord in menuRecord.Children) {
					<MatListItem OnClick="(async (e) => await this.MenuItemClickedAsync(e, childMenuRecord))">@(childMenuRecord.Name)</MatListItem>
				}
			</MatList>
		</MatMenu>
	}
} else {
	<MatButton Icon="@(menuRecord.Icon)" Label="@(menuRecord.Name)" OnClick="(async (e) => await this.MenuItemClickedAsync(e, menuRecord))">
	</MatButton>
}
```

That is good news, and I will probably test more tomorrow.

**Comment by rpc-scandinavia** [comment]
I was gone to bed, but got a thought.
Could it be that the @ref is only set on FIRST render - because when I change culture, the render is not FIRST in "OnAfterRender".

@javiercn, can I force a new FIRST render without F5 ?

Another thing I can try, is to move the entire titlebar menu to its own component, which then would be FIRST rendered when I change culture. Intreaging.

**Comment by mrpmorris** [comment]
Take your code, copy it, cut out code that isn't relevant to your problem, then keep cutting out code so it demonstrates the problem rather than performing its original purpose.

Then share it. I think that will help.

**Comment by rpc-scandinavia** [comment]
Sorry, I have been away from this.

I will try to take my code apart. I created this Fiddle using my real "ElementMatMenuButtons" component, and it works.

[https://blazorfiddle.com/s/pse4ew06](https://blazorfiddle.com/s/pse4ew06)

**Comment by mrpmorris** [comment]
> I created this Fiddle using my real "ElementMatMenuButtons" component, and it works except when I click the current language - then the sub-menu do not open.

I think you'll have to make something much more specific. I doubt anyone will spend time trying to work out if the problem even exists within Blazor rather than your code. The fact you can't reproduce it without introducing your code suggests it might not be.

**Comment by rpc-scandinavia** [comment]
Yes, the BlazorFiddle show that there is something wrong.
However I wait and see if the new betas or 3.1 solves the problem.
