### ISSUE TITLE
Blazor: InputText emit required attribute based on DataAnnotations

### ISSUE THREAD

**Issue by Condra963** [dotnet/aspnetcore#16650]
Is it possible to make InputText depending on the linked DataAnnotations?

For example i have this fields:
```
[Required(AllowEmptyStrings = false, ErrorMessage = "Required.")]
[EmailAddress]
[StringLength(100, MinimumLength = 8)]
public string Email { get; set; }
```
or
```
[Required(AllowEmptyStrings = false, ErrorMessage = "Required.")]
[DataType(DataType.Password)]
[StringLength(100, MinimumLength = 8)]
public string Password { get; set; }
```

If we see these attributes, like 'EmailAddress' and 'Password' and 'Required', we could easily add the attributes needed for these field, aren't we? Than our output would be auto generated like this:
```
<input type="email" required />
```
```
<input type="password" required />
```

These are examples, we can implement a lot more of course. Now i created a custom InputText that handles these cases, but i really think this would be a handy feature.

**Comment by javiercn** [comment]
@Condra963 thanks for contacting us.

The ask sounds reasonable. 

@SteveSandersonMS do you have any thoughts? Would this be a good up-for-grabs?

**Comment by SteveSandersonMS** [comment]
It’s certainly an interesting idea. We would need a whole new design for something that supplies extra attributes based on a model field. It’s not completely obvious how this should be designed, given that we’re not coupled to DataAnnotations and need to support extensibility to other validation systems. Further, consideration must be given to all possible mismatches between what’s representable in DataAnnotations and in standard HTML attributes. 

For now I think your custom solution is most likely to be the best thing for you, given how you’re free to hardcode assumptions about the validation system being used and what range of validation attributes you will use. I don’t know that we could generalise beyond that without a much broader design effort.

**Comment by javiercn** [comment]
Thanks.

I've moved it to the backlog and we can reconsider this in the future, as it's definitely not a 3.1 thing.

**Comment by Condra963** [comment]
@SteveSandersonMS for now i made my own custom InputText as a quick fix, but this is coupled to DataAnnotations. Can i ask if there is a better solution to temporarily fix this? (The form-control class is just because i should not put it everywhere over and over again, it doesn't count for this request.)
```
public class CustomInputTextBase : InputText
{
    private const string _placeHolder = "placeholder";
    private const string _required = "required";

    private const string _type = "type";
    private const string _type_email = "email";
    private const string _type_password = "password";
    private const string _type_text = "text";

    private const string _class_form_control = "form-control";
    private const string _class_valid = "valid";
    private const string _class_isvalid = "is-valid";
    private const string _class_invalid = "invalid";
    private const string _class_isinvalid = "is-invalid";

    protected new string CssClass
    {
        get
        {
            return GetCssClasses(base.CssClass);
        }
    }

    public new IReadOnlyDictionary<string, object> AdditionalAttributes
    {
        get
        {
            return GetAdditionalAttributes();
        }
    }

    private IReadOnlyDictionary<string, object> GetAdditionalAttributes()
    {
        Dictionary<string, object> additionalAttributes = new Dictionary<string, object>();

        if (base.AdditionalAttributes != null)
        {
            additionalAttributes = new Dictionary<string, object>(base.AdditionalAttributes);
        }

        AddAdditionalAttributeDataAnnotations(additionalAttributes);
        AddAdditionalAttribute(additionalAttributes, _placeHolder, FieldIdentifier.FieldName);

        return additionalAttributes;
    }

    private void AddAdditionalAttributeDataAnnotations(Dictionary<string, object> additionalAttributes)
    {
        Type modelType = FieldIdentifier.Model.GetType();
        PropertyInfo fieldProperty = modelType.GetProperty(FieldIdentifier.FieldName);

        AddAdditionalAttributeDataAnnotation(additionalAttributes, _required, true, fieldProperty.GetCustomAttribute<RequiredAttribute>());
        AddAdditionalAttributeDataAnnotation(additionalAttributes, _type, _type_email, fieldProperty.GetCustomAttribute<EmailAddressAttribute>());

        switch (fieldProperty.GetCustomAttribute<DataTypeAttribute>().DataType)
        {
            case DataType.EmailAddress: AddAdditionalAttribute(additionalAttributes, _type, _type_email); break;
            case DataType.Password: AddAdditionalAttribute(additionalAttributes, _type, _type_password); break;
            case DataType.Text: AddAdditionalAttribute(additionalAttributes, _type, _type_text); break;
        }
    }

    private void AddAdditionalAttributeDataAnnotation(
        Dictionary<string, object> additionalAttributes,
        string key,
        object value,
        Attribute attribute)
    {
        if (attribute != null)
        {
            AddAdditionalAttribute(additionalAttributes, key, value);
        }
    }

    private void AddAdditionalAttribute(Dictionary<string, object> additionalAttributes, string key, object value)
    {
        if (!additionalAttributes.ContainsKey(key))
        {
            additionalAttributes.Add(key, value);
        }
    }

    private string GetCssClasses(string cssClass)
    {
        List<string> classes = cssClass.Split(' ', StringSplitOptions.RemoveEmptyEntries).ToList();

        AddCssClasses(classes, _class_form_control);
        ReplaceCssClasses(classes, _class_valid, _class_isvalid);
        ReplaceCssClasses(classes, _class_invalid, _class_isinvalid);

        return string.Join(' ', classes).Trim();
    }

    private void AddCssClasses(List<string> classes, string @class)
    {
        if (!classes.Contains(@class))
        {
            classes.Add(@class);
        }
    }

    private void ReplaceCssClasses(List<string> classes, string currentClass, string newClass)
    {
        if (classes.Contains(currentClass))
        {
            classes.Remove(currentClass);
            classes.Add(newClass);
        }
    }
}
```

**Comment by SteveSandersonMS** [comment]
What you're doing here looks mostly fine to me.

The one bit that's quite weird in the code is `OnParametersSet` removing and re-adding event handlers - not sure why it does that.

**Comment by Condra963** [comment]
I updated my previous comment because the previous code had still some issues. I think now i covered it all.

**Comment by Condra963** [comment]
@SteveSandersonMS there is still an issue with my solution, the fields getting validated in all way now. But when i submit my form and there is a field invalid the form still thinks it's valid. I'm trying to figure out why the form still thinks it's invalid. Can you tell me what i missed?

**Comment by Condra963** [comment]
Ok, everything is working fine, it is just the CompareAttribute that is failing. But there are some ongoing issues i have seen.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
