### ISSUE TITLE
[commandline-tools] dotnet dev-certs improvements

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#16670]
The tool has aged quite a bit and while it gets the job done we might want to improve it in some aspects to react to the customer feedback we've seen so far.

**Comment by OskarKlintrot** [comment]
I miss a `--NonInteractive` or `--force` options to be able to use `--trust` in a CI/CD pipeline.

**Comment by javiercn** [comment]
There's no way to do trust without user interaction on windows or on mac.

**Comment by OskarKlintrot** [comment]
To bad :(

**Comment by javiercn** [comment]
If you want it for test automation, browsers allow you to skip HTTPS certificate validation when running in a test context. That's how we run our E2E tests.

**Comment by OskarKlintrot** [comment]
I'm using a pwsh-script to verify that a project templates (as in `dotnet new yadayada`) works by restoring it, building it, running it and then finally calling it with `Invoke-RestMethod`. I get some really strange behaviors in Azure DevOps when it comes to the certificates that I can't replicate locally but not I just added `-SkipCertificateCheck` instead, similar to what you said, and now it works. Thanks a lot! 😄

**Comment by javiercn** [comment]
I'm closing this issue since we've tackled the improvements in separate issues and we think we are done for the time being.
