### ISSUE TITLE
Cannot build arcade, due to incorrect MSBuild Version specified in build.ps1

### ISSUE THREAD

**Issue by kelsosharp** [dotnet/aspnetcore#16684]
If you follow the instructions here: https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md

You will get a version requirement error, its using, and reference to a package location that does not exist.

C:\Users\Dell\\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19517.3\tools\Tools.proj : error : Version 5.0.100
-alpha1-014696 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBui
ld is 16.0.461.62831. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild v
ersion currently available.
C:\Users\Dell\\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19517.3\tools\Tools.proj : error MSB4236: The SDK
'Microsoft.NET.Sdk' specified could not be found.
Build failed.

**Comment by PhilippeAuchlin** [comment]
Got exactly the same problem executing the build or start script.

**Comment by miaojiuchen** [comment]
+1

**Comment by miaojiuchen** [comment]
my hack solution:
1. In eng/common/tools.ps1 Line 275
add code to modify install version
```powershell
$vsInfo = LocateVisualStudio $vsRequirements
  if ($vsInfo -ne $null) {
    $vsInstallDir = $vsInfo.installationPath
    $vsMajorVersion = $vsInfo.installationVersion.Split('.')[0]

    InitializeVisualStudioEnvironmentVariables $vsInstallDir $vsMajorVersion
  } else {

    if (Get-Member -InputObject $GlobalJson.tools -Name "xcopy-msbuild") {
      $xcopyMSBuildVersion = $GlobalJson.tools.'xcopy-msbuild'
      $vsMajorVersion = $xcopyMSBuildVersion.Split('.')[0]
    } else {
      $vsMajorVersion = $vsMinVersion.Major
      $xcopyMSBuildVersion = "$vsMajorVersion.$($vsMinVersion.Minor).0-alpha"
      ------>   $xcopyMSBuildVersion = "16.3.0-alpha" <------
    }

    $vsInstallDir = InitializeXCopyMSBuild $xcopyMSBuildVersion $install
    if ($vsInstallDir -eq $null) {
      throw "Unable to find Visual Studio that has required version and components installed"
    }
  }
}
```

2. You may also need to copy  
**C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC** 
folder to
{your aspnetcore source repo dir}\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC

3. You may also need to install VC++ toolkits in VS installer

**Comment by dougbu** [comment]
This is similar to the problem corrected for the release/3.1 branch in b8a0fa74dcd4 but may also be a problem in your Visual Studio installation. Either way, we now rely primarily on `dotnet msbuild` in this repo but when building native components and installers on Windows, the global.json snippet at https://github.com/dotnet/aspnetcore/blob/master/global.json#L21-L28 describes the minimum acceptable VS.

To ensure you're installation meets those requirements, it's best to iterate with commands like the following to find missing components or an older installation. Remove `-requires` until an installation path is displayed then add whatever component(s) you removed to your installation. If necessary, reduce the `-version` and keep trying. If you need to remove the `-requires` for `Microsoft.Component.MSBuild` something is really wrong😺
``` powershell
& 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -prerelease -requires Microsoft.Component.MSBuild -products * -version 16.5 -requires Microsoft.VisualStudio.Component.VC.ATL -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -requires Microsoft.VisualStudio.Component.Windows10SDK.17134 -property installationPath
```

If you prefer never to do that, `-noBuildNative` _might_ work but will lack components used for IIS integration. (Think result is a warning which would fail the build _after_ building everything else correctly.)

**Comment by dougbu** [comment]
Please close this issue if problems are resolved

**Comment by dougbu** [comment]
Assuming everything is working now&hellip;
