### ISSUE TITLE
Inject dependencies into SignalR hub method

### ISSUE THREAD

**Issue by Daniel15** [dotnet/aspnetcore#16686]
Is there a way to inject dependencies into a SignalR hub method, similar to how we can use `FromServicesAttribute` with ASP.NET MVC to inject a service into an action method? I tried just listing the dependency in the method signature but got an error "Failed to invoke foo due to an error on the server"

### API

```diff
public class HubOptions
{
+    public bool EnableInferredFromServiceParameters { get; set; }
}
```

### Alternative names

EnableImplicitFromServiceParameters
InferFromServiceParameters
InferParametersFromService(s)

### Additional thoughts

Instead of opt-in, make the option an opt-out and attempt to detect services by default. (This would likely require a breaking change announcement)

**Comment by davidfowl** [comment]
No there isn't. It's something we could look at in the future though.

**Comment by halter73** [comment]
FWIW, the lifetime of the hub is typically only the duration of a Hub method invocation. I think the same is true for Controllers and Actions for that matter. So ctor injection might not look as nice, it should work more or less the same.

**Comment by Daniel15** [comment]
The issue is if each hub method requires different dependencies, you end up with a giant constructor :)

I haven't tested but I guess injecting the IServiceProvider into the constructor would work, then I could use that or ActivatorUtilities in the hub method.

**Comment by halter73** [comment]
> I haven't tested but I guess injecting the IServiceProvider into the constructor would work, then I could use that or ActivatorUtilities in the hub method.

That should definitely work, but I understand that's far from ideal.

**Comment by erikmf12** [comment]
@Daniel15 - I know this doesn't solve your problem, but it might help to use partial classes for your hub class. You could have your constructor in a MyHub.Constructor.cs and all other methods in a different MyHub.ClientMethods.cs.

**Comment by davidfowl** [comment]
Maybe we can support this better now that we have synthetic arguments (like cancellation tokens).

**Comment by davidfowl** [comment]
We need to define a `[FromServices]` attribute lower in the stack that can be used by SignalR. The one in MVC is well tied to MVC.

**Comment by BrennanConroy** [comment]
`api-suggestion`?

**Comment by halter73** [comment]
I hate having multiple `[FromServices]` attributes though. Type forwarding and still needing `using Microsoft.AspNetCore.Mvc;` doesn't seem great either though.

I wonder if we could infer the parameter is a service without an attribute? Even if we could, we'd probably still want an attribute. :sad:

**Comment by BrennanConroy** [comment]
We also need a way to allow opting out of services per parameter or per method.
e.g. `[FromClient]`, `[FromInvocation]`, `[FromCall]`

Or, only DI inject if `[FromServices]` is on the parameter.

**Comment by pranavkm** [comment]
API review:

API approved. We spoke about this and think this should be an opt-out feature. We discussed the name and think `DisableImplicitFromServiceParameters` (using implicit over inferred) is better.
 
```diff
public class HubOptions
{
+    public bool DisableImplicitFromServiceParameters { get; set; }
}
```

**Comment by BrennanConroy** [comment]
Was the breaking change nature discussed? We probably need to make an announcement if we make it opt-out.

**Comment by halter73** [comment]
I think I mentioned how unlikely I feel this was to break people 😆 Making an announcement is a good idea though.
