### ISSUE TITLE
no CSS changes made to main site show on any pages in the Identity area

### ISSUE THREAD

**Issue by ChristopherJTrent** [dotnet/aspnetcore#16764]
I make changes to the CSS for my page, and then I go to log in, and I get blinded by the white background of bootstrap's Reboot.SCSS file, and there is no way to edit anything about that, since it is downloaded from elsewhere.

**Comment by ChristopherJTrent** [comment]
I also can't just add Inline CSS, since the entire page seems to be drawn straight from the aether, none of the pages that handle logging in are actually part of my project.

**Comment by blowdart** [comment]
Not from the aether, but from a package. You can [scaffold out](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity) the CSS for identity and make changes there.
