### ISSUE TITLE
UserManager.Create does not generate identity after migration to 3.0

### ISSUE THREAD

**Issue by malballah** [dotnet/aspnetcore#16775]
After I have migrated to asp.net core 3.0 UserManager.Create does not generate identity column for the table users, I am using asp.net identity and I use this code to change the table name
`builder.Entity<User>().ToTable("Users");`
and this to create the user
`var result = await _userManager.CreateAsync(user, model.Password);`

**Comment by blowdart** [comment]
What have you migrated from?
Where are you trying to customise the model?

**Comment by malballah** [comment]
I have migrated from asp.net core 2.2
I am customizing the model in the OnModelCreating event after base.OnModelCreating(builder);

protected override void OnModelCreating(ModelBuilder builder)
		{
			base.OnModelCreating(builder);

            //register models from other modules
            var moduleRegistrars = _httpContextAccessor.HttpContext.RequestServices.GetServices<IModuleRegistrar>();
            foreach (var moduleRegistrar in moduleRegistrars)
            {
                moduleRegistrar.RegisterDbModels(builder);
            }

            //customize identity tables
            builder.Entity<User>().ToTable("Users");
            builder.Entity<Role>().ToTable("Roles");
            builder.Entity<UserClaim>().ToTable("UserClaims");
            builder.Entity<RoleClaim>().ToTable("RoleClaims");
            builder.Entity<UserToken>().ToTable("UserTokens");
            builder.Entity<UserRole>(entity =>
            {
                entity.ToTable(name: "UserRoles").HasKey(p => new { p.UserId, p.RoleId });
                entity.HasOne(p => p.User).WithMany().HasForeignKey(p => p.UserId).IsRequired();
                entity.HasOne(p => p.Role).WithMany().HasForeignKey(p => p.RoleId).IsRequired();
            });
            builder.Entity<UserLogin>(entity =>
            {
                entity.ToTable(name: "UserLogins").HasKey("UserId");
            });

            //appy global query filters
            ApplyQueryFilters(builder);
            //applying trackable configuration
            builder.ApplyTrackableConfiguration();
        }

**Comment by HaoK** [comment]
Seems like this might be the same issue as https://github.com/dotnet/aspnetcore/issues/16866 @ajcvickers is this a dupe?

**Comment by ajcvickers** [comment]
@HaoK Yes, I think so.
