### ISSUE TITLE
Odd completions on component tag helper

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#16777]
The completions on a the component tag helper seem a bit odd:

- They appear to be a selection of HTML attributes, but then why the razor icon?
- Why this specific list of attributes?
- Tiny empty docs bubble shows up just to the right of the completion list

![image](https://user-images.githubusercontent.com/1874516/68076701-7821e900-fd75-11e9-995d-ee7dc7e49579.png)

**Comment by danroth27** [comment]
@NTaylorMullen

**Comment by javiercn** [comment]
@NTaylorMullen can you take a look?

**Comment by NTaylorMullen** [comment]
@danroth27 what VS are you using?

**Comment by danroth27** [comment]
VS 16.4 Preview 3. Latest public preview.

**Comment by NTaylorMullen** [comment]
I see. Ya I can reproduce. This is super odd; sadly we don't control TagHelper completions for attributes. @ToddGrun we should talk about this, it's most likely a piece of the TagHelperAttribute completion code you guys have.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen is there something left to do here?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen is there something left to do here?

Not by us today. LSPification fixes this but if we want it to be fixed sooner that'd have to happen on @ToddGrun / @alexgav 's end(s)

**Comment by mkArtakMSFT** [comment]
Closing as we have separate tracking issue which will resolve this.
