### ISSUE TITLE
[Blazor] Consider an analyzer to suggest using foreach instead of for in Blazor code.

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#16815]
Consider an analyzer to suggest using foreach instead of for in Blazor code, as the latter can result in undersired behaviors when the loop variable gets captured inside a lamba:
* This happens explicitly in event-handlers.
* This happens implicitly within ChildContent fragments.

We can produce an analyzer that looks at for loops inside generated razor components and produces a warning when the loop variable is being used in an unsafe context. 

I agree this is a c# behavior, but specially in the second case it happens implicitly as a result of an implementation detail, which can make it incredibly hard to troubleshoot.

The diagnostic will simply loop at the for loops and see if the loop variable is being used inside the closure.

**Comment by Andrzej-W** [comment]
I think it is **a very good idea**. I have seen similar problems from the beginning of Blazor #15633, #16144, #16073 and many others. Issue #16809 is especially hard to understand if you are not smart enough to look at generated code.

**Comment by Andrzej-W** [comment]
Suggestion from analyzer should be "use foreach or local variable ...".

**Comment by YordanYanakiev** [comment]
I am strongly against it. Replacing a basic ideology because there is a bug is an absurd.
The bug should be fixed one or another way, not replacing the basic ideology of a programmers logic and language property nearly 60 years old.
The fix is as well an easy one - just apply internal/hidden variable as a counter if there is missing such - 2 steps code check I believe will fix this, and probably this won't be the first, nor the last time such fix must be applied.

**Comment by Andrzej-W** [comment]
> The bug should be fixed

@YordanYanakiev this is not the bug - it is a standard C# behaviour which is simply not known to some people and sometimes it is not obvious if you are not an expert on Blazor internals.

People can write loops with arbitrary complexity and it is not a trivial task to introduce some local variables (sometimes more than one) to automatically solve the problem. Here is a simple example without Blazor stuff for simplicity:
```c#
for (int i = 0; i < 10; i++)
{
  WriteLine(i);
  if (i % 2 == 0)
    i++;
  WriteLine(i);
}
```
Now let's add local variable and replace all references inside loop:
```c#
for (int i = 0; i < 10; i++)
{
  int x = i;
  WriteLine(x);
  if (x % 2 == 0)
    x++;
  WriteLine(x);
}
```
I hope you see immediately that these two loops have different behaviour.

**Comment by YordanYanakiev** [comment]
Unfortunately I am unable to accept this misconception of the basic ideology of the procedural programming languages. This is illogical and unintuitive. Therefore it should be never part of any kind of programming language.

**Comment by mkArtakMSFT** [comment]
We're closing this as this is a c# specific thing, rather than something specific to Blazor.
