### ISSUE TITLE
Produce a Microsoft.AspNetCore.App.Internal package, for version flow of stabilized builds

### ISSUE THREAD

**Issue by nguerrera** [dotnet/aspnetcore#16827]
We need a package that is 1. Never stabilized, and 2. Always built and published in servicing. This is needed to determine the suffixed blob storage location.

For base shared framework, we are using a Microsoft.NETCore.App.Internal package. For ASP.NET, there doesn't seem to be any package that meets both criteria always yet.

@mmitche @dougbu @JunTaoLuo

**Comment by dougbu** [comment]
Are this and #16859 duplicates?

**Comment by mmitche** [comment]
Nope, they are different. The other one is about generating files for the layout itself. This is about generating a package that Maestro can flow versions of, for the purpose of identifying the non-suffixed aspnetcore version.  Today we end up using the xplat certs package but that is non-ideal.

```
<!-- Only package from ASP.NET that did not stabilize and is still published, use it to get unsuffixed blob location  -->
    <!-- Replace with Microsoft.AspNetCore.App.Internal when available: https://github.com/aspnet/AspNetCore/issues/16827 -->
    <Dependency Name="Microsoft.AspNetCore.DeveloperCertificates.XPlat" Version="3.0.3-servicing.20073.3">
      <Uri>https://github.com/dotnet/aspnetcore</Uri>
      <Sha>bd1e14b7d16b798de8a874189c89afed755a266c</Sha>
    </Dependency>
```

**Comment by dougbu** [comment]
@wtgodbe this is done now isn't it❔

**Comment by wtgodbe** [comment]
Effectively, yes. We use `developerCertificates.xplat` for this purpose
