### ISSUE TITLE
Extend GetAuthenticationStateAsync to include auth properties

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#16831]
Opening per https://github.com/aspnet/AspNetCore.Docs/issues/15325#issuecomment-548934968 for Blazor Server documentation issue [Social login provider tokens+claims for Blazor auth (aspnet/AspNetCore.Docs \#15160)](https://github.com/aspnet/AspNetCore.Docs/issues/15160) opened by @hfaran ...

`GetAuthenticationStateAsync` doesn't provide authentication properties (and use of `options.Events.OnCreatingTicket` for the auth provider per the [Persist additional claims and tokens from external providers](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0) guidance isn't effective when working with tokens).

For ...

```csharp
var authResult = await HttpContext.AuthenticateAsync();
var authProperties = authResult.Properties.Items;
```

... only `.issued` and `.expires` is exposed for an external auth provider ...

```
// Immediate Window
authProperties
Count = 2
    [0]: {[.issued, Thu, 17 Oct 2019 13:26:57 GMT]}
    [1]: {[.expires, Thu, 31 Oct 2019 13:26:57 GMT]}
```

**Comment by Tratcher** [comment]
There's two steps here. A) Persist the auth tokens when transitioning from the external cookie to the app cookie. The code [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0#save-the-access-token) should cover that.
B) In a blazor page there's no way to get access to AuthenticationProperties. AuthenticationStateProvider.GetAuthenticationStateAsync returns a AuthenticationState containing only the ClaimsPrincipal, not the associated AuthenticationProperties.

**Comment by javiercn** [comment]
Tokens can be passed in to the root component in the initial component request and saved as context

**Comment by Tratcher** [comment]
Sample?

**Comment by javiercn** [comment]
@Tratcher 

This is the gist of it. Can you fill in the details with the appropriate auth code to retrieve the tokens?

@guardrex You simply need to define the parameters in the main component and maybe provide them as a cascading value or set them inside a singleton service during OnInitializing.

```razor
@page "/"
@namespace BlazorServerIndividualSqlLite.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@inject Microsoft.AspNetCore.Authentication.AuthenticationService AuthService;
<!DOCTYPE html>
<html lang="en">
<head>
...
</head>
<body>
    <app>
        @{ var properties = await GetTokens(); }
        <component type="typeof(App)" render-mode="ServerPrerendered" param-google="@(properties.GetParameter<string>("google"))" />
    </app>

    <script src="_framework/blazor.server.js"></script>
</body>
</html>
@functions{
    public async Task<Microsoft.AspNetCore.Authentication.AuthenticationProperties> GetTokens()
    {
        var result = await AuthService.AuthenticateAsync(HttpContext, User.Identity.AuthenticationType);
        return result.Ticket.Properties;
    }
}
```

**Comment by javiercn** [comment]
There is a separate issue somewhere where I showcased how to do this for Azure AD with server-side blazor. Closing this issue since it's the same content.
