### ISSUE TITLE
HTML warning when setting disabled attribute using Razor syntax

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#16833]
In Blazor Server app with .NET Core 3.0 in a .razor file:

![image](https://user-images.githubusercontent.com/1874516/68168654-5ca61200-ff1e-11e9-8de9-c8a60b78ebb2.png)

Warning: '@IsDisabled' is not a valid value of attribute 'disabled'
VS 16.3.7

**Comment by javiercn** [comment]
@NTaylorMullen @ajaybhargavb I imagine this is yours?

**Comment by javiercn** [comment]
encasing it in `@()` fixes it, but this should work without that.

**Comment by NTaylorMullen** [comment]
@ToddGrun this is on your plate.

**Comment by Snazzie** [comment]
> encasing it in `@()` fixes it, but this should work without that.

Actually it doesnt
![image](https://user-images.githubusercontent.com/19627023/74614429-c209c180-510f-11ea-8783-ae811ab0401b.png)

**Comment by ToddGrun** [comment]
OK, was able to track this down. Believe it or not, this comes from a partial parse issue that's been in our code forever. Just checked in a fix and should be fixed in 16.6.

**Comment by Regenhardt** [comment]
@ToddGrun How long away is 16.6? I'd hoped for something closer, since this seems like something small enough for a patch. (IMO. I have literally no idea how your release process works.)

**Comment by ToddGrun** [comment]
16.6 Preview 1 should be available in the next few weeks. Unfortunately, 16.5 is in a state now where it’s getting ready to release, and we won’t take even small changes unless there is a major need to do so.
