### ISSUE TITLE
SignalR : Cookie management

### ISSUE THREAD

**Issue by TheCamel** [dotnet/aspnetcore#16847]
Hello,
I am migrating an old ASP SignalR v2.2.0 solution to Core. Our solution is behind an apache reverse proxy. We use the cookie added by apache when server is elected on both client side.

Managing cookie on java client and javascript has disapear ?

Can you restore this or provide an alternative ? may be I am wrong too ?

.cookie() on js 
and in java 
CookieCredentials cookieCredentials = new CookieCredentials("bbbbb");
Connection.setCredentials(cookieCredentials);

thanks for your feedback.
bye

**Comment by BrennanConroy** [comment]
I'm curious why you want to set the cookies explicitly? Normally, you get cookies automatically from the server/proxy that you connect to and they should flow without manual intervention between the client and server.

Could you explain your scenario and why you're wanting to manually set cookies?

**Comment by TheCamel** [comment]
Not only "set", also "get"

We use the hub to allow a html+javascript application (APP1) to communicate with another local java application(APP2). 

The workflow is :
APP1 start a new group on the hub with a guid, here the RP elected one web server and set a cookie in the response ( APP1 extract the cookie)
APP1 start the java APP2 with the guid and the cookie;
APP2 set the cookie and join the same group on the same web server because of the RP cookie 
now they can exchange messages through the hub. 

This is done to allow a web app to access client machine and smart card reader. Before it was an applet ....

**Comment by BrennanConroy** [comment]
In javascript you can use `document.cookie` to get and set the non-httponly cookies.

We currently don't have any support for cookies in the Java client. And will consider it for a future release.

**Comment by BrennanConroy** [comment]
In 5.0 we allow setting up an OkHttpClient.Builder callback which has settings including cookies. This is as much as we'll do for now.
