### ISSUE TITLE
Too many ISystemClock definitions

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/aspnetcore#16844]
The `ISystemClock` defines a way to get the current time in UTC timezone, and it has a simple implementation:

```csharp
public interface ISystemClock
{
    DateTimeOffset UtcNow { get; }
}

public interface SystemClock : ISystemClock
{
    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
}
```

The interface exists in:
* `Microsoft.AspNetCore.Authentication`
* `Microsoft.AspNetCore.ResponseCaching`
* `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure`
* `Microsoft.Extensions.Internal`

There is a small difference exists between implementations, but in most cases it can be moved out. In case of Kestrel's clock which has a specific logic inside, there could be made a new interface `IScopedSystemClock` which will provide the scope start time as `UtcNow` does now. Therefore, looks like all of them could be merged into a single class/interface and put into `Microsoft.Extensions.Primitives`.

**Comment by JunTaoLuo** [comment]
`ISystemClock` seems to be used elsewhere in our codebase as well so the list might be incomplete. Instead of putting this Extensions.Primitives, we should also consider having it as a shared source file.

**Comment by BrennanConroy** [comment]
We aren't planning to do anything here.
