### ISSUE TITLE
Generate a version metadata file which can be used by dotnet-install

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#16859]
When the runtime or other components generates a stabilized build, it publishes to a non-stable directory, with an identical set of stable and suffixed asset names inside. This is so that dotnet-install, which makes an assumption that the version to install will match the asset name, will work properly.  Example:

```
3.0.100-preview3-123545\sdk-3.0.100-preview3-123545.zip (contents are 3.0.100 branded) 
3.0.100-preview3-123545\sdk-3.0.100.zip (contents are 3.0.100 branded) 
```

We publish both so that we can push the final branded artifacts on release day, and the suffixed assets will work with dotnet-install. dotnet-install, however, will install the sdk, then look for the installed version (3.0.100-12345) rather than 3.0.100 because it knows nothing about the contents of the zip. It will fail.

We want to solve two problems

- dotnet-install doesn't know what version to check for when it expands an archive
- We have to double publish everything so that we still have the desired suffix-less assets for release day.

To solve this, the runtime, sdk, and aspnetcore repos should produce a file called productVersion.version, which inside, identifies the actual product version.  Example:

```
productVersion.version -> contains 3.0.100
```

Thus, the dotnet-install script can find the blob directory of the files based on the passed in version, then look up the file containing the version number and use this to identify what the names of the runtime/sdk archives it should download as well as what it should verify it installed after it completes,.

**Comment by dougbu** [comment]
To be clear, this is for 3.0.x and up, correct?

We already generate a number of *.version files e.g. files that get placed at known locations in blob storage. What exactly is missing and where should it be placed?

I think you (@mmitche) changed something not long ago to fix a similar issue. Please correct me if I'm wrong.

> Alternatively, this file could be named "productVersion.version" or something like that.

That name looks identical. What's the alternative?

**Comment by mmitche** [comment]
@dougbu Yeah,3.0 and above.

> That name looks identical. What's the alternative?

I originally had another solution in here.

The current aspnetcore versions are the right form (contain actual product versions), but we will should probably name these these consistently across components so that dotnet-install does not need to special case the file name for each component,

**Comment by dougbu** [comment]
Are this and #16827 duplicates?

**Comment by mmitche** [comment]
Nope, see: https://github.com/dotnet/aspnetcore/issues/16827#issuecomment-579799950

**Comment by bozturkMSFT** [comment]
The name `productVersion.txt` was used in the installer. Let's use the same name everywhere unless there is a good reason, please.

**Comment by dougbu** [comment]
@wtgodbe @bozturkMSFT @mmitche do we have any work left here❔ If not, please close.

**Comment by wtgodbe** [comment]
I'm not sure if what we have now in the shared framework is sufficient - @mmitche?

**Comment by mmitche** [comment]
Yeah, we still need this file for aspnetcore. It's been completed for runtime and SDK.

This is not a blocker for RTM builds though. It just means that you can't use dotnet-install to obtain aspnetcore for a stable build.

**Comment by mmitche** [comment]
This is not about something inside the artifacts. It's an artifact that goes alongside them. See https://github.com/dotnet/runtime/pull/41721 for an example.

This allows dotnet-install to find the actual artifact given the non-stabilized version number. So if aspnetcore's RTM build is 5.0.0-rtm.1234.5, productVersion.txt will say "5.0.0", which tells dotnet-install to construct a path to the installer as:

`aspnetcore\Runtime\5.0.0-rtm.1234.5\aspnetcore-runtime-5.0.0-win-x64.exe`

**Comment by dougbu** [comment]
@wtgodbe and @mmitche I've been chatting w/ @hoyosjs about this issue. The https://github.com/dotnet/diagnostics repo uses `dotnet-install` to install ASP.NET runtime bits. They're currently unable to run tests with our RTM bits -- though they did test up to RC2.

Do we have any runway to fix this before locking down release/5.0 completely❔ If not, we should try to get a fix into 5.0.1 and re-enable diagnostics testing then.

Separately, @wtgodbe would a fix in our repo (albeit in eng/Publishing.props) be as simple as dotnet/runtime#41721❔

**Comment by mmitche** [comment]
Even with fixing this, it would not help. We do not update the aka.ms links for a stable build. This is because we're going to produce the same version of the runtime, aspnetcore, etc. over and over again. Furthermore, you can't use the standard nuget package feeds to exercise the stable bits anyway. FYI 3.1 also didn't update 'latest' on the equivalent infra in that release (installer's copy to latest stages).

Using dependency flow is the correct way to flow bits in these cases, as it identifies the exact version as well as provides a way to get the nuget feeds.

**Comment by hoyosjs** [comment]
@mmitche it's complicated® using darc given we test several versions on one branch. We have to depend on a non shipping asset so the version doesn't get stabilized, but to be fair we do that for the latest branch (in this case, we consider it to still be 5.0). This is for arcade's dotnet-install mechanisms (global.json and the install scripts in the common directory). For stabilized builds @MattGal added the productVersions.txt given the storage links look like https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/5.0.0-rtm.20517.7/aspnetcore-runtime-5.0.0-win-x64.zip We will need this to be able to test MSRC builds and any type of stabilized builds really. This is not the latest versions file, nor the aka links.

**Comment by mmitche** [comment]
We could enable aka.ms links for stable builds, but I'm pretty nervous about that. Anyways, it's still good to do this work item..so that we could easily enable 'latest' links.

**Comment by hoyosjs** [comment]
Sure. I'm not too interested in the `latest` behavior. In fact I'd be warry because stable builds have a version that would be conflicting with other builds. I mostly care for a fully-qualified download with dotnet-install using the version parameter that can support public and private storage usage for stabilized assets.

**Comment by mmitche** [comment]
Yeah, that will work with this added functionality.

**Comment by wtgodbe** [comment]
@mmitche is there still an ask here for us? If so, what is it?

**Comment by mmitche** [comment]
We still need to generate this productVersion.txt for future dotnet-install scenarios to work.

**Comment by mmitche** [comment]
FYI this has been done for runtime, windowsdesktop, sdk, etc.

**Comment by wtgodbe** [comment]
Alright, I'll put it on my to-do for the month. What branches?

**Comment by mmitche** [comment]
master and release/5.0
