### ISSUE TITLE
Remove user id from logs in order to comply GDPR

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#16864]
### Is your feature request related to a problem? Please describe.
https://github.com/aspnet/AspNetCore/blob/81379147e69864bf841c2953b50bb0849ceb830e/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Login.cshtml.cs#L135
https://github.com/aspnet/AspNetCore/blob/81379147e69864bf841c2953b50bb0849ceb830e/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Login.cshtml.cs#L144
There's no user id for these logs.

### Describe the solution you'd like
I think it's useful for `PasswordSignInAsync` to return the `User` for this scenario.

**Comment by blowdart** [comment]
You appear to be saying two things here.

We don't put potential PII in logs due to GDPR concerns. If you want to log user ids you need to change the log statements yourself.

While I can see why you'd want a user there, a user isn't the result of a sign-in, especially one that fails, or requires a second factor, so the api wouldn't be changing.

**Comment by Kahbazi** [comment]
> We don't put potential PII in logs due to GDPR concerns.

The user id is being logged in `LoginWith2fa` page and I thought it's missing in the `Login` page.
https://github.com/aspnet/AspNetCore/blob/6a6deb298c8b3385213174dd023a45f6a309da5f/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/LoginWith2fa.cshtml.cs#L133
https://github.com/aspnet/AspNetCore/blob/6a6deb298c8b3385213174dd023a45f6a309da5f/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/LoginWith2fa.cshtml.cs#L138
https://github.com/aspnet/AspNetCore/blob/6a6deb298c8b3385213174dd023a45f6a309da5f/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/LoginWith2fa.cshtml.cs#L143
So should it removed from these logs?

**Comment by blowdart** [comment]
We'll get rid of those there, thanks!

**Comment by Kahbazi** [comment]
Are you accepting PR for this?

**Comment by blowdart** [comment]
Oh certainly yes, we like PRs :)

**Comment by Kahbazi** [comment]
Good, I'll send a PR. I have some questions
- User Id is being logged in multiple pages and UserManager, should I remove them all?
- Should I also remove Principal.Identity.Name?
https://github.com/aspnet/AspNetCore/blob/7202634cead940379a7ddbb41b71da6882a9aab2/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L151
- Having user id in logs is very useful specially when there are reports based on logs. What do you think about adding an option for adding user id to logs and the default value could be false to obey GDPR?

**Comment by HaoK** [comment]
@blowdart can confirm, but I think we should remove them all (UserId), I would guess user name is the same as user id since its a 1:1 mapping

I'm wary about adding an option at this point

**Comment by Rick-Anderson** [comment]
> Having user id in logs is very useful specially when there are reports based on logs.

We could add that to the docs- how to log `UserId`

**Comment by Kahbazi** [comment]
@blowdart @HaoK I want to start working on this. Should I add an option to switch on logging user id or remove them completely?

**Comment by blowdart** [comment]
Remove entirely please :)

**Comment by rynowak** [comment]
This is a breaking change, we should review it as such and announce it.

**Comment by HaoK** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/17491 Thanks again @Kahbazi
