### ISSUE TITLE
When publish creates Identity folder in wwwroot

### ISSUE THREAD

**Issue by RetsamSoft** [dotnet/aspnetcore#16862]
Hello, sorry for my bad English, when I publish my project I create a folder called "Identity" in the wwwroot folder.
I use my own layout in /Areas/Identity/Pages/_ViewStart.cshtml

```
@ {
    Layout = "/Views/Shared/_MyLayout.cshtml";
}
```

I don't want the "Identity" folder to be created automatically at wwwroot, thx.

-     .NET Core 3.0

**Comment by javiercn** [comment]
@RetsamSoft thanks for contacting us.

This is already possible if you modify the list of static web assets.

```
<PropertyGroup>    
<ResolveStaticWebAssetsInputsDependsOn>RemoveIdentityAssets</ResolveStaticWebAssetsInputsDependsOn>
</PropertyGroup>

<Target Name="RemoveIdentityAssets">
    <ItemGroup>
        <StaticWebAsset Remove="@(StaticWebAsset)" Condition="%(SourceId) == 'Microsoft.AspNetCore.Identity.UI'" />
    </ItemGroup>
  </Target>
```

**Comment by mmarinchenko** [comment]
@javiercn

**1.** Any plans to simplify this by adding support for something like:
```
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.*">
      <ExcludeAssets>staticwebassets</ExcludeAssets>
    </PackageReference>
```
?

**2.** dotnet sdk has templates which contain wwwroot folder with bootstrap etc. So after the following commands (for example):
```
dotnet new mvc --auth Individual
dotnet publish -o Distrib
```
we end up with wwwroot folder inside Distrib which contains application web assets and another copy of assets under Identity subfolder:
```
PS> ls .\Distrib\wwwroot\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10.01.2020     10:48                css
d-----       10.01.2020     10:48                Identity
d-----       10.01.2020     10:48                js
d-----       10.01.2020     10:48                lib
-a----       10.01.2020     10:48          32038 favicon.ico

PS> ls .\Distrib\wwwroot\Identity\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10.01.2020     10:48                css
d-----       10.01.2020     10:48                js
d-----       10.01.2020     10:48                lib
-a----       16.11.2019     11:05          32038 favicon.ico
```
Any plans to solve this somehow? Maybe dotnet sdk templates must contain Identity assets exclusion in project configuration by default.

BTW dotnet sdk templates actually have more common problem with assets exclusion, for example after the commands above I have the following package references:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0" />
  </ItemGroup>
```
but it should be more like:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```
As I can see all templates lack design-time assets exclusion for now. I may create separate issue for that if you don't have one already.

**Comment by javiercn** [comment]
@mmarinchenko I don't think we plan to do this. 

At best we would offer a property in the identity UI package to turn off adding these assets, but we don't plan to build generic functionality for this, as there is already an extensibility point to do this.

We don't plan to extend the PackageReference itemgroup for this feature.

**Comment by mmarinchenko** [comment]
Ok, thanks.
