### ISSUE TITLE
Possible Sockets regression causing server test flakiness

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#16873]
We're getting quite a bit of flakiness in server tests. We suspect a regression in Sockets because we haven't changed code here, other than accepting a new runtime.

@halter73 @BrennanConroy we can use this issue to track/monitor work on investigating this.

**Comment by anurse** [comment]
Or maybe [thread-pool starvation](https://github.com/aspnet/AspNetCore/pull/16853#issuecomment-550440127)?

Either way we need to investigate and mitigate these failures.

**Comment by anurse** [comment]
> Can we capture a dump?

(@davidfowl failing at reading comprehension in https://github.com/aspnet/AspNetCore/pull/16853#issuecomment-550808037)

We certainly could. We also talked about the fact that if we double down on transitioning tests that are *working well in Helix* to use Helix *exclusively* we might gain some reliability here. We have a hunch (with some anecdata to back it up) that because AzDO builds run a whole bunch of test projects in the same xUnit batch, they starve the thread-pool causing timeouts. Helix runs each test project in a separate work item (which means a separate machine) and would improve reliability.

Is that a correct interpretation of our Helix model @HaoK ?

**Comment by HaoK** [comment]
Yep you got it @anurse , currently our Helix jobs run each unit test project by itself on a dedicated machine, so each test runs in isolation, with the tradeoff that we spend more time waiting for helix machines than running tests typically.

**Comment by HaoK** [comment]
FYI, longer term we might want to repackage things a bit since we've been getting some pushback about how we aren't utilizing machines efficiently this way.  It might be better if we aggregated things so that each feature area has one single helix work item that ran all of its related tests, instead of having every test project get a dedicated machine

**Comment by anurse** [comment]
> It might be better if we aggregated things so that each feature area has one single helix work item that ran all of its related tests, instead of having every test project get a dedicated machine

Hrm, that may bring us back to the problems we're seeing in AzDO. Perhaps there's a compromise that makes sense though, bundling a few test projects together instead of doing each individual one, but also not just running **all the tests** in one batch.

**Comment by HaoK** [comment]
Yeah we don't need to run them in parallel on helix, since we are running all the feature areas at once, we could just run each test project by itself per machine

**Comment by HaoK** [comment]
I'll file an issue for this helix enhancement as it will take some new functionality/complexity in the helix scripts/build stuff

**Comment by anurse** [comment]
The, somewhat higher-priority, item I'd like to look at is to start migrating some test suites to be run exclusively in Helix. In general we think there are test suites that are more reliable when run in Helix than in AzDO (because they run in separate processes rather than overloading a single process with a huge number of tests).

**Comment by HaoK** [comment]
I filed https://github.com/aspnet/AspNetCore/issues/16901

Yeah seems reasonable to just add a reverse skipOnHelix attribute?  Maybe `[HelixOnly]` that you would slap on azdo starved tests ?

**Comment by HaoK** [comment]
Although now that we are running helix as a required PR check, we could actually consider only running SkipOnHelix tests across the board for the azdo jobs now right?

**Comment by HaoK** [comment]
@anurse we discussed this a bit in the build meeting today, and I created https://github.com/aspnet/AspNetCore/issues/16910 to look into seeing if we can stop tests that are happy in helix entirely.

**Comment by jkotalik** [comment]
@HaoK / @anurse how is this looking now?

**Comment by anurse** [comment]
Let's close and re-evaluate with Helix in place.
