### ISSUE TITLE
Review Startup APIs for Blazor WASM

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#16874]
## Goals

- Reduce complexity/ceremony of startup/main code for Blazor WASM
- Address gaps in current scenarios (no way to get services before UI is shown)
- **non-goal** symmetry or consistency with server-side ASP.NET Core

## Sample Code

*These are some focused samples with my proposed implementation choice. There's another section with alternatives and why I didn't choose them. I think there are a lot of reasonable small tweaks to this, but I wanted to lead with something.*

Adding configuration to the mix opens a few questions which need further discussion, so it's a good thing we're injecting it at this point.

### Simple

This is the code that we expect to appear in every template.

```C#
async static Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.RootComponents.Add<App>("app");

    await builder.Build().RunAsync();
}
```

### Adding custom initialization 

This adds some custom initialization after components are registered and after services are available, but before the UI is shown.

```C#
async static Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.Services.AddSingleton<WeatherService>();
    builder.RootComponents.Add<App>("app");

    var host = builder.Build();

    var weatherService = host.Services.GetRequiredService<WeatherService>();
    await weatherService.InitializeAsync();

    await host.RunAsync();
}
```

### Adding configuration

This adds configuration, which the user can use in their initialization code. 

```C#
async static Task MainWithConfig(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.Services.AddSingleton<WeatherService>();
    builder.RootComponents.Add<App>("app");

    var host = builder.Build();

    var weatherService = host.Services.GetRequiredService<WeatherService>();
    await weatherService.InitializeAsync(host.Configuration["WeatherUrl"]);

    await host.RunAsync();
}
```

## Open questions

- [ ] Should we rename one of the two `.Services` properties for clarity? One is `IServiceCollection`, the other is `IServiceProvider`. I like the idea of this in general, but I haven't come up with a pair of names that feel good.
- [ ] What's the cost (in size) of including `IConfiguration` and `IConfigurationBuilder`?

### StartAsync/StopAsync vs RunAsync

The ASP.NET Core hosting stuff has start/stop in addition to run. It's a source of confusion, start/stop are a lot more subtle than they seem, so I didn't plan to add them here.

### Configuration as part of WebAssemblyHostBuilder

One of the negatives of putting configuration here is that it won't/can't be linked out without a look of gymnastics. I think it's worth it though from a design point of view. 

You could also imagine an alternative where we don't tie ourselves to configuration at all (nowhere on our API surface). The guidance for users could be to add it to DI themselves.

### ComponentMappingCollection vs methods on the WebAssemblyHostBuilder

We discussed this idea last time, so I wanted to include it so we can compare. I like the property a little bit better.

### Disposing the host

NOTE: `host.RunAsync()` will dispose the host if/when RunAsync terminates. This is a little bit bizarre, but it's what generic host does. Hosts are single-use. It's not clear in the WASM how that `RunAsync` will terminate, at least not in this release.

## Apis

```C#
namespace Microsoft.??????
{
    public sealed class WebAssemblyHostBuilder
    {
        public static WebAssemblyHostBuilder CreateDefault(string[] args) => throw null;

        public WebAssemblyEnvironment Environment { get; }

        public IServiceCollection Services { get; }

        public IConfigurationBuilder Configuration { get; }

        public ComponentMappingCollection RootComponents { get; }

        public WebAssemblyHost Build() => throw null;
    }

    public sealed class WebAssemblyEnvironment
    {
        public string BaseUri { get; }
    }

    public sealed class WebAssemblyHost : IDisposable
    {
        public IConfiguration Configuration { get; }

        public IServiceProvider Services { get; }

        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public Task RunAsync() => throw null;
    }

    public sealed class ComponentMappingCollection : Collection<ComponentMapping>
    {
        public void Add<TComponent>(string selector) where TComponent : IComponent => throw null;
        public void Add(string selector, Type componentType) => throw null;
    }

    public readonly struct ComponentMapping
    {
        public ComponentMapping(string selector, Type componentType)
        {
            Selector = selector;
            ComponentType = componentType;
        }

        public string Selector { get; }

        public Type ComponentType { get; }
    }
}
```

## Feedback to consider
- [x] https://github.com/aspnet/AspNetCore/issues/14340
- [x] https://github.com/aspnet/AspNetCore/issues/13694

**Comment by mkArtakMSFT** [comment]
We should make sure https://github.com/aspnet/AspNetCore/issues/13694 is considered for `Startup API` review part.

**Comment by huzder** [comment]
Hello,
Please consider providing a capability to extend end-application's startup in the following way: 

Startup.ThirdPartyLib.cs
```
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;

[assembly: HostingStartup(typeof(Blazor.ServerSide.ThirdPartyLibHostingStartup))]

namespace Blazor.ServerSide {
    public partial class ThirdPartyLibStartupFilter : IStartupFilter {

        public ThirdPartyLibStartupFilter(ILoggerFactory loggerFactory) {
            //
        }

        public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next) {
            return builder => {
                builder.UseMiddleware<...>();
                next(builder);
            };
        }
    }
    public partial class ThirdPartyLibHostingStartup : IHostingStartup {
        void IHostingStartup.Configure(IWebHostBuilder builder) {
            builder.ConfigureServices((serviceCollection) => {
                serviceCollection.AddTransient<IStartupFilter, ThirdPartyLibStartupFilter>();
                serviceCollection.AddScoped<...>();
            });
        }
    }
}

```

Use case:
Nuget package copies own startup template file ( Startup.%ThirdPartyLibName%.cs ) into end application after installation via msbuild target to simplify a first time setup for a new user. The described approach works fine for serverside blazor since it's based on top of aspcore, but it has a lack of functionality in case wasm

**Comment by simonpbond** [comment]
Another reason why it would be good to have access to JSRuntime inside ConfigureServices [can be found here.](https://github.com/serilog/serilog-sinks-browserconsole/issues/8)

**Comment by SteveSandersonMS** [comment]
Altogether this looks great to me.

> This is the code that we expect to appear in every template.

This is not a big deal, and I know we tend to prefer not adding explanatory comments to templates, but do you think the unfamiliarity of this new arrangement might warrant giving an extra clue about where to configure services now there's no `ConfigureServices` method? For example,

```cs
async static Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.RootComponents.Add<App>("app");

    // To configure services in your application, use builder.Services

    await builder.Build().RunAsync();
}
```

> Configuration as part of WebAssemblyHostBuilder

I do think that would be really valuable. Maybe even necessary. That would make it much more convenient if you're trying to do something like:

```cs
builder.Services.AddSingleton(() => {
    return new MyGrpcClient(builder.Configuration["BackendUri"]);
});
```

Otherwise it's very difficult to have DI services that require config info as constructor parameters rather than a subsequent `Init` call.

I know we haven't exactly nailed down the mechanics of how the config info gets into the system yet.

> Should we rename one of the two .Services properties for clarity

If we're doing this, then I think the simpler name (`Services`) should be reserved for `builder.Services`, since that's by far the more common usage. Then maybe we'd have `host.ServiceProvider`. That seems reasonably usable to me.

> What's the cost (in size) of including IConfiguration and IConfigurationBuilder

I'd say we should design whatever we think is the nicest API to use, and then measure the cost. Only if the cost is problematic (say, adds > 10KB) then we can do some gymnastics to find a way to get the linker to be able to trim it out.

**Comment by javiercn** [comment]
I like it!

It's simple and straightforward.

**Comment by rynowak** [comment]
> Do you expect people to duplicate service registrations?
> Will we suggest people to move service registrations into a separate method?

These are super good questions. I really do expect (for instance) that something like that would be needed. If your services talk to data you're going to need different implementations at the least.

**Comment by RemiBou** [comment]
I have a question : would it be a good idea to expose the renderer instance ? It could be nice for libraries that which to extend it (for instance I wanted to build MiniProfiler.Blazor but I couldn't find any good global hook, exposing WebRenderer would help I think). Maybe this is not related to this issue ...

**Comment by rynowak** [comment]
Closing as done. 

@RemiBou can you file a separate issue for that discussion? I think we'd want to know more about this. We don't consider the renderer APIs to be stable right now, so we're not likely to put it in everyone's face.
