### ISSUE TITLE
How to handle tcp client accident close without sending closing message to server when using ConnectionHandler 

### ISSUE THREAD

**Issue by stantoxt** [dotnet/aspnetcore#16886]
If the tcp client close without communicating to the server,the kestrel server will close this connection when reading data next time, but I want to do some more extra disconnection operations like logging something or writing something to database.
Is there any shutdown event I can register to the shutdown method?

**Comment by anurse** [comment]
We should be signalling the [`HttpContext.RequestAborted`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-3.0) cancellation token if the client disconnects. You can register a handler on that token to be signalled, or check it proactively in your code.

**Comment by anurse** [comment]
Oops, missed that you said `ConnectionHandler` :). The [`ConnectionContext.ConnectionClosed`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.connections.connectioncontext.connectionclosed?view=aspnetcore-3.0#Microsoft_AspNetCore_Connections_ConnectionContext_ConnectionClosed) token serves the same purpose there.

**Comment by jkotalik** [comment]
Going to close due to inactivity.
