### ISSUE TITLE
[Helix] Add ability to run aggregate test projects per payload (for feature areas)

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#16901]
Today we basically have a 1:1 mapping between helix work items and test project publish directories.

This has the downside of not utilizing helix machines well as we end up waiting for machines longer than we are running tests.

One possible improvement would be to add the ability to aggregate all of a tests per feature area instead, for example, we could aggregating and publishing all tests under `Hosting`, `Security`, `Identity` and run them as a single work item on a helix machine (instead of running each nested test project on its own machine).

This would entail writing some new harvesting logic on the build/publish to helix side, as well as some payload script logic to run these tests

cc @aspnet/build @anurse

**Comment by dougbu** [comment]
@anurse @HaoK is this still relevant -- despite plan to use Kusto to extract area information?

**Comment by anurse** [comment]
This is more about optimizing the runs, not data collection. I think it's still worth discussing.

**Comment by dougbu** [comment]
@Haok is this optimization still important❔ For example, would reducing the number of work items mean we end up with fewer runs that execute in seconds but we don't see results 'til project template tests complete❔ Most importantly could we use this (somehow) to reduce the overall time for our Helix test runs (ideal) or at least reduce our AzDO agent consumption❔

**Comment by HaoK** [comment]
Larger payloads means less work items so less overhead for the queues.  I don't think we'd such much different on our end as yeah the bottleneck is always going to be the longest area.  Its unclear how much benefit we'd see here, as its more about creating less queue depth

**Comment by dougbu** [comment]
Sounds good. Putting this on the Build dashboard just to watch. Let @dotnet/aspnet-build know if you need help 😺

**Comment by HaoK** [comment]
Closing this for now, we can always reopen/schedule this work if it ever becomes an issue
