### ISSUE TITLE
Look into not running tests in both helix / non helix

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#16910]
Per discussion in build meeting today

Now that helix is a required PR check, we should look into not running tests that are covered in helix, in the normal azdo test jobs.

We might be able to use the SkipOnHelix attribute (or the lack thereof), to accomplish this

**Comment by anurse** [comment]
I'd like to be a little more deliberative than just using the attribute, but I'm on board for this. Perhaps a project by project decision rather than per test.

**Comment by HaoK** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/17109
