### ISSUE TITLE
Remove HttpClient from the standard DI services list and add it in the template

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#16929]

**Comment by Regenhardt** [comment]
May I try my hand on this one? Seems simple enough.

**Comment by mkArtakMSFT** [comment]
> 
> 
> May I try my hand on this one? Seems simple enough.

Thanks for your suggestion, @Regenhardt.
We're quite close to the code-complete date for current milestone. If you can send a PR within a day, we'll consider it. /cc @ajaybhargavb

**Comment by Regenhardt** [comment]
Not sure I did everything right, since I couldn't actually get it to run. Probably should have started yesterday, might have eased the whole schedule thing 😅 .

**Comment by ajaybhargavb** [comment]
Thanks for your contribution, @Regenhardt!
