### ISSUE TITLE
EventCallback for second binding value not work

### ISSUE THREAD

**Issue by nguyenvanbien95** [dotnet/aspnetcore#16937]
### I have two values for binding form parent component to child component.
First value is binded success but second value is not work.

### To Reproduce
Child.cs

        // display Value1, Value2

        @code {

        [Parameter] Type1 Value1{ get; set; }
        [Parameter] EventCallback<Type1 > Value1Changed { get; set; }
        [Parameter] Type2 Value2{ get; set; }
        [Parameter] EventCallback<Type2 > Value2Changed { get; set; }

        override async Task OnInitializedAsync() 
        {
                var dbData = await Service.GetAsync();
                Value1 = dbData.Item1;
                Value2 = dbData.Item2;
                await Value1Changed.InvokeAsync(Value1);
                await Value2Changed.InvokeAsync(Value2);
        }
        }

Parent.cs

        <Child @bind-Value1="Value1" @bind-Value2="Value2"></Child>

        @code {
        Type1 Value1{ get; set; }
        Type2 Value2{ get; set; }
        }

When child Initialized, Value1 is send back to parent, Value2 is changed to value of Value2 of parent(not change value in parent).
Parent load: Value1 = 0, Value2 = 0
Child load: Value1 = 1, Value2 = 2
=> after send to Parent: 
Parent: Value1 = 1, Value2 = 0
Child : Value1 = 1, Value2 = 0

It seem not good practice. I can change code for a object contain both. But I want to sure this is not a bug?

### Further technical details
- ASP.NET Core version 3.0
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

- The IDE is visual studio 2019 v16.3.7

**Comment by javiercn** [comment]
@nguyenvanbien95 thanks for contacting us.

@SteveSandersonMS thoughts?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
