### ISSUE TITLE
Developer SDK language localized comments, as well as official documentation

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/aspnetcore#16951]
1. I am looking at.net core 3x now and I find that the help documentation is relatively simple. It is not as detailed as the.net Framework, for example, it was not introduced when I did the global error capture.Of course, familiar people can get the general meaning from the class.I think there should be an official document, such as I need to globally catch system errors, model validation, and how I should inject it in startup.cs
2. I would like to ask about the development of annotation language localization, which is done very well on the.net Framework, such as Japanese, Chinese, Korean, English and so on.
I didn't see any in.net CORE version 1X 2X 3X. I was just curious to ask if this localization work is to be considered in the future?
For example, the global error help documentation on the.net Framework, please, this is very, very important for beginners
https://docs.microsoft.com/en-us/aspnet/web-api/overview/error-handling/web-api-global-error-handling
3. Maybe I came from the.net Framework 2X 3X 4X. The webapi project seems to have a separate design from MVC, but on the.net CORE it seems to use UseMvc and so on

**Comment by javiercn** [comment]
@JHeLiu thanks for contacting us.
Ragarding 1. I believe we have such document. Isn't [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.0) what you are looking for?

Regarding 2. We haven't been doing localization in the past releases and I'm not sure what the plan here is. @Pilchie or @danroth27 can comment further.

Regarding 3. ASP.NET .NET Core its a complete new version that unifies the old Web API and MVC frameworks into one.

**Comment by JHeLiu** [comment]
@javiercn Thank you

**Comment by danroth27** [comment]
@JHeLiu I'm not sure what you mean by "annotation language localization". Are you trying to localize validation messages? We have docs on how to do that here: https://docs.microsoft.com/aspnet/core/fundamentals/localization#dataannotations-localization

@javiercn We do have localized documentation content. For example, here are the ASP.NET Core docs in Korean: https://docs.microsoft.com/ko-kr/aspnet/core/.

**Comment by JHeLiu** [comment]
@danroth27 

Sorry, maybe my description is not clear, my English is not very good.So I'll show you the screenshot.

**.NET CORE**

![image](https://user-images.githubusercontent.com/15246138/68631903-80bdb080-0527-11ea-9c3b-18c216a6e2b3.png)

**.NET Framework** 

![image](https://user-images.githubusercontent.com/15246138/68631893-74395800-0527-11ea-9e9f-e79069efc70a.png)

**Comment by Pilchie** [comment]
Found this issue I never replied to.

@nguerrera Do you know what the latest plans are on localizing XML Doc comments.

**Comment by Rick-Anderson** [comment]
@nguerrera Do you know what the latest plans are on localizing XML Doc comments.

**Comment by nguerrera** [comment]
I do not know. @vivmishra might

**Comment by vivmishra** [comment]
There are no formal plans to pick any new localization work for .NET 5 or 3.1. 

But, if this can be automated easily with MT then it is something we can consider. Adding Jason to check the feasibility of such a translation work. Will get back with updates once we have them.  

cc: @JasonCard ; @mairaw

**Comment by mairaw** [comment]
We now offer manual installs of localized IntelliSense for some targets (.NET Core, .NET Standard and Desktop SDKs)

https://dotnet.microsoft.com/download/dotnet-core/intellisense
https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense

They are human translated quality IntelliSense files.

But I'm not familiar with annotation language localization. I don't know how you get those comments in code like it's shown in the screenshot. Can someone help me understand how do you get that?

**Comment by JasonCard** [comment]
We currently cannot localize comments in code. We do have a feature request, but considered low priority due to complexity and lack of data on demand. With help from @Rick-Anderson, we're currently gathering feedback on this by [adding links under code snippets](https://github.com/dotnet/docs/pull/17129/files) and directing feedback [here](https://github.com/MicrosoftDocs/feedback/issues/2515).

**Comment by Rick-Anderson** [comment]
This isn't comments in code.  See the images above. This is more like the API's that are translated.

**Comment by JasonCard** [comment]
It looks like the images above are highlighting localized comments in code, but I don't know where those screenshots are coming from. 
I'm also not sure what "XML Doc comments" is referring to.
We do localize API reference content for .NET and Xamarin.Forms. 
Do you know what content/repo are requested to be localized?

**Comment by mairaw** [comment]
But that is not IntelliSense @Rick-Anderson. Do you know how to see that?

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/75935217-bb26c280-5e22-11ea-84a4-86510798e53b.png)

**Comment by saber-wang** [comment]
> We now offer manual installs of localized IntelliSense for some targets (.NET Core, .NET Standard and Desktop SDKs)
> 
> https://dotnet.microsoft.com/download/dotnet-core/intellisense
> https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense
> 
> They are human translated quality IntelliSense files.
> 
> But I'm not familiar with annotation language localization. I don't know how you get those comments in code like it's shown in the screenshot. Can someone help me understand how do you get that?

It is similar to this, but the file of ASP. Net core is missing

**Comment by JunTaoLuo** [comment]
@Pilchie Is this something we should follow up for 6.0?

**Comment by Pilchie** [comment]
Interestingly, I'm on a mail thread about this very topic right now.

**Comment by wtgodbe** [comment]
@Pilchie was there any resolution from that email thread?

**Comment by dougbu** [comment]
Ping @Pilchie 

> It is similar to this, but the file of ASP. Net core is missing

@saber-wang what file is missing❔

**Comment by dougbu** [comment]
`blocked` 'til we know what's needed

**Comment by JasonCard** [comment]
Regarding localized IntelliSense (example [here](https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense)), we may reduce support going forward, as our team is refocusing our investments on high-usage content. 
We will continue to publish localized reference content on docs.microsoft.com (example [here](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-3.1)). 
Please let me know if there's any unlocalized content on docs.microsoft.com that I can help with.

**Comment by Pilchie** [comment]
Closing since we're not currently planning on creating localized doc comments for aspnetcore.
