### ISSUE TITLE
Samples cannot run

### ISSUE THREAD

**Issue by Vampire2008** [dotnet/aspnetcore#16957]
### Describe the bug
Try to run samples from `src\Security\samples\` with `dotnet run`. Displays error:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Не удается найти указанный файл.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at AuthSamples.Cookies.Program.Main(String[] args)
```

### To Reproduce
1) Clone this repository
2) Switch to branch release/3.0`
3) Navigate to `src\Security\samples\ClaimsTransformation`
4) Run `dotnet run`

### Further technical details
- ASP.NET Core version 3.0
- dotnet --info
```
SDK for .NET Core (any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio Community 16.3.8
But I run from PowerShell without opening project.

**Comment by blowdart** [comment]
None of them?

**Comment by Tratcher** [comment]
First make sure to run restore.cmd from the repo root, especially after switching branches.

For visual studio run `startvs.cmd src\security\security.sln` to open VS using the local dotnet runtime.

For command line usage start powershell and then run `. .\activate.ps1` in the repo root to enable the local dotnet runtime. Then dotnet commands should work elsewhere in the repo.

**Comment by Vampire2008** [comment]
> https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md covers most of the setup required.
> 
> First make sure to run restore.cmd from the repo root, especially after switching branches.
> 
> For visual studio run `startvs.cmd src\security\security.sln` to open VS using the local dotnet runtime.
> 
> For command line usage start powershell and then run `. .\activate.ps1` in the repo root to enable the local dotnet runtime. Then dotnet commands should work elsewhere in the repo.

Same error.

**Comment by Tratcher** [comment]
Does running build.cmd in the repo root work for you?

**Comment by Vampire2008** [comment]
Build successful.
But error same.

**Comment by Tratcher** [comment]
This works in master but I was able to repro the error in 3.0. @JunTaoLuo said this is an issue with our ref assemblies.

**Comment by Tratcher** [comment]
@aspnet/build

**Comment by Elpaggio** [comment]
Any instructions on how to fix this in order to be able to run the samples?
If you delete the *.deps.json you will be able to run the sample but I guess this is not a permanent fix.

**Comment by Tratcher** [comment]
@Elpaggio have you tried this in master? It should be working there?

**Comment by Elpaggio** [comment]
Yes it works on master (and git tag 3.1.0) but I would like to be able to
compile and run the samples checking out the tag 3.0.1.
3.0.1 is the version that I have production code compiled against. This is
just in order to explore and get a better understanding of the ASP.NET Core
and to be able to debug tough issues.

Cheers

lør. 4. jan. 2020 18.21 skrev Chris Ross <notifications@github.com>:

**Comment by Tratcher** [comment]
I recommend using the 3.1 branch then. 3.1 was a short release and most of the behaviors will be the same.

**Comment by Elpaggio** [comment]
I will - thanks.

lør. 4. jan. 2020 18.51 skrev Chris Ross <notifications@github.com>:

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.
