### ISSUE TITLE
JsonPatchDocument should use System.Text.Json in ASP.NET 5

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/aspnetcore#16968]
As asked by @mkArtakMSFT, I've raised a new issue, following on from the discussion in https://github.com/aspnet/AspNetCore/issues/14035.

### Is your feature request related to a problem? Please describe.

ASP.NET Core has mostly switched to System.Text.Json but JsonPatchDocument still relies on Newtonsoft.Json.

### Describe the solution you'd like

JsonPatchDocument should use System.Text.Json

**Comment by javiercn** [comment]
@RehanSaeed Thank you for your feature request. 

We'll consider this feature during the next release planning period and update the status of this issue accordingly.

**Comment by mkArtakMSFT** [comment]
Thanks for filing this issue, @RehanSaeed.
We're closing this issue as we don't plan to make the proposed change in 5.0. The main reason is that this will require a huge investment from us, with not a very high value-add for majority of our customers.
