### ISSUE TITLE
MVC Template with Database Users Template confuses email and username.

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/aspnetcore#16979]
If you create a new MVC Template with the Database storing Application, your login page assumes you're asking for email when you're actually using username. 

The problem is part of login. The View of the login asks for email:

![image](https://user-images.githubusercontent.com/568272/29480355-d3035fc6-8445-11e7-9186-b0e5a6197436.png)

Problem is that the Login functionality passes in the email as the username:

```
public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
    {
      ViewData["ReturnUrl"] = returnUrl;
      if (ModelState.IsValid)
      {
        // This doesn't count login failures towards account lockout
        // To enable password failures to trigger account lockout, set lockoutOnFailure: true
        var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
```

The PasswordSignInAsync is expecting the username as the first parameter.

And this works most of the time because when you register new users, you're duplicating email and username:

```
 public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
    {
      ViewData["ReturnUrl"] = returnUrl;
      if (ModelState.IsValid)
      {
        var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
```

But as a project matures, this can confuse users when they expect you're validating against email when it should be userid (when they are different). Please update the template to use the right nomenclature (username instead of email in login would be sufficient).

**Comment by blowdart** [comment]
The templates are strongly bound to our assumptions / opinions of identity, where username and email address are the same. Trying to separate them or make them more generic is difficult and would mean cancelling other work. 

If you customise identity beyond our opinions we expect you to customise the UI and code as well.

**Comment by shawnwildermuth** [comment]
The problem is that when users use username and you assume to check email then it fails without any explanation. It's not about customizing the UI, it's about confusion...When the UI says email but you store it as username, it's a mistake not a feature.

**Comment by blowdart** [comment]
Yes we know, and it's one we regret, but we're kind of stuck with it. @HaoK can we improve error messages here?

**Comment by shawnwildermuth** [comment]
An error message improvement would help a lot. Thanks.

**Comment by Rick-Anderson** [comment]
@HaoK  can you draft something we could add to the docs? 
I'll add it to [Introduction to Identity}(https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.0&tabs=visual-studio)

Something like

The templates assume username and email address are the same.

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/AspNetCore.Docs/pull/18035
