### ISSUE TITLE
Support for commandline argument in 

### ISSUE THREAD

**Issue by wli3** [dotnet/aspnetcore#16996]
### Describe the bug
commandLineArgs in launchSettings.json is not honored in dotnet run
### To Reproduce
Create launchSettings.json like the following

```json
{
  "profiles": {
    "console12": {
      "commandName": "Project",
      "commandLineArgs": "hello"
    },
    "newProfile1": {
      "commandName": "Executable"
    }
  }
}
```

change the program files to be

```cs
using System;

namespace console12
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(args[0]);
        }
    }
}

```

F5 in Visual Studio works
If you run it with `dotnet run` you will see the following. Since the command line args are not passed down
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at console12.Program.Main(String[] args) in C:\work\temp\console12\Program.cs:line 9
```

It is due to this https://github.com/dotnet/toolset/blob/b3a65fd82a879beb7ff8565a781ad257337f1de1/src/dotnet/commands/dotnet-run/LaunchSettings/ProjectLaunchSettingsProvider.cs#L77

Note, LaunchSettings related logic is owned by aspnet

### Further technical details

I believe it was never supported

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview2-014569\

Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91

**Comment by Pilchie** [comment]
@vijayrkn Does your team own the launchSettings.json stuff?

**Comment by vijayrkn** [comment]
Yes.

**Comment by Pilchie** [comment]
@wli3 Can you file an AzDO bug for the tooling team for this?

**Comment by wli3** [comment]
I filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1058897
