### ISSUE TITLE
Support non-PE format assemblies

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17019]

**Comment by pranavkm** [comment]
Should we close this? /cc @javiercn

**Comment by SteveSandersonMS** [comment]
I don't think we're realistically planning to do anything else for this, so I'm closing now but @mkArtakMSFT @javiercn @pranavkm if anyone thinks we're going to do something here for May, please re-open.

**Comment by javiercn** [comment]
Agree
