### ISSUE TITLE
Publishing cleanup for Blazor WASM apps

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17018]
The work here is

a) To move the contents of the `wwwroot` folder to the root of the publish folder
b) Change the `Standalone.web.config` to clean up redirection

**Comment by javiercn** [comment]
We need to be careful here in hosted scenarios, as we can't really determine if a dll must go to the output and if we try to remove it we might end up breaking the published app

**Comment by pranavkm** [comment]
I had a look at this. One way to do this is to manipulate the path that items would get published to and let the actual publishing targets do the work, and the other is to do something after the fact. While the first option is doable with vanilla msbuild, it's gnarly to do path manipulation as strings, especially if we want to avoid normalizing the kind of slashes that gets used. I'm not sure if it's important, but Windows and Linux have different kinds of slashes in their paths and I'd rather not change it.

The other option has issues with VS's publishing. 

I feel option 1 is the best way to go, but we're a bit strapped for time with little time to react if it goes wrong. Let's table this until 5.0.
