### ISSUE TITLE
Setup performance testing for sample Blazor WASM apps

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17011]
* Use AspNetCore Benchmarks scenario
* Use Selenium to launch and scrape perf events

Sceanrios we already cover: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/testassets/Microsoft.AspNetCore.Blazor.E2EPerformance/wwwroot/benchmarks/index.js

* [x] Startup time
* [x] Rendering list
* [x] Json handling (this measures Mono's perf, but it's a good one)
* [x] Measure render time for a more complex component - More complex component, nested child component 
* [x] Event handling - complex grid with bind and automate the process of changing the textbox content
* [x] Size of published app (with and without linker)

**Comment by pranavkm** [comment]
We have the intiail set of scenarios checked in and tracked via https://aka.ms/aspnet/benchmarks.
