### ISSUE TITLE
Setup E2E multi-device testing infrastructure for a sample Blazor WASM app

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17013]

**Comment by ajaybhargavb** [comment]
The PR is now merged. We now have tests running on Android and macOS safari. iOS testing is currently blocked because of SauceLabs subscription issue.
@mkArtakMSFT given the infrastructure is now merged, should we close this issue and file a new one to track the iOS real device testing work?

**Comment by pranavkm** [comment]
> @mkArtakMSFT given the infrastructure is now merged, should we close this issue and file a new one to track the iOS real device testing work?

Filed some follow up issues:

* https://github.com/dotnet/aspnetcore/issues/18647
* https://github.com/dotnet/aspnetcore/issues/18646
