### ISSUE TITLE
API proposal: IMultiplexedConnectionListenerFactory and company

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#17037]
Today, when accepting a connection from an IConnectionTransport, you get a ConnectionContext that has information about the connection. However, for scenarios like QUIC, after you get the connection, you need to accept again in order to get a QUIC stream on said connection. This is fairly awkward and isn't intuitive as the System.IO.PipeReader/PipeWriter will be unusable.

When implementing HTTP/3, right now we have the following:
```c#

public interface IConnectionListenerFactory
{
    ValueTask<IConnectionListener> BindAsync(EndPoint endpoint, CancellationToken cancellationToken = default);
}

public interface IConnectionListener : IAsyncDisposable
{
    EndPoint EndPoint { get; }
    ValueTask<ConnectionContext> AcceptAsync(CancellationToken cancellationToken = default);
    ValueTask UnbindAsync(CancellationToken cancellationToken = default);
}

public interface IQuicStreamListenerFeature
{
    ValueTask<ConnectionContext> AcceptAsync(CancellationToken cancellationToken = default);
}
```

Usage:
```C#
IConnectionListener connectionListener = connectionListenerFactory.BindAsync(new IPEndPoint());
ConnectionContext context = await connectionListener.AcceptAsync(); 
IQuicStreamListenerFeature feature = context.ConnectionFeatures.Get<IQuicStreamListenerFeature>();
ConnectionContext streamContext = await feature.AcceptAsync();
```

I'd like to propose a new API for accepting connections and streams from a multiplexed connection. Though this may only apply to QUIC for now, the notion of streams/connections will probably apply to other scenarios.

```c#
public interface IMultiplexedConnectionListenerFactory : IConnectionListenerFactory
{
}
public interface IMultiplexedConnectionListener : IConnectionListener // Need to downcast
{
    ValueTask<MultiplexedConnectionContext> AcceptMultiplexedAsync(CancellationToken cancellationToken = default);
}
public class MultiplexedConnectionContext : ConnectionContext
{
    ValueTask<StreamConnectionContext> AcceptStreamAsync();
    ValueTask<StreamConnectionContext> ConnectStreamAsync(bool unidirectional); // undirectional or bidirectional stream, like half open/half close
}
public class StreamConnectionContext : ConnectionContext
{
    int StreamId { get; }
    bool Unidirectional { get; }
}
```
Also, we could see how IMultiplexedConnectionListenerFactory without implementing IConnectionListenerFactory.

Usage:

```C#
IMultiplexedConnectionListener connectionListener = connectionListenerFactory.BindAsync(new IPEndPoint()) as IMultiplexedConnectionListener;
MultiplexedConnectionContext context = await connectionListener.AcceptAsync(); 
ConnectionContext streamContext = await context.AcceptAsync();
```

To me this feels a bit cleaner that what we are doing with features.

**Comment by jkotalik** [comment]
cc @davidfowl @halter73 @scalablecory thoughts?

**Comment by halter73** [comment]
Should the StreamConnectionContext indicate in what way the stream is unidirectional (i.e send-only or receive-only)?

**Comment by jkotalik** [comment]
Good point, we may need it to be an enum instead stating which direction.

**Comment by halter73** [comment]
Does IMultiplexedConnectionListenerFactory exist just so you can tell early what type of listener you'll get from it? It doesn't add any methods, so BindAsync will still return a plain old IConnectionListener which you'd need to cast to a IMultiplexedConnectionListener either way. You might as well save the as-casting until you get the listener.

Or better yet, keep IMultiplexedConnectionListenerFactory but don't have it derive from IConnectionListener at all. Kestrel could inject both kinds of listeners and use the right one where appropriate.

Also, do you think MultiplexedConnectionContext should derive from ConnectionContext? Before we had no choice since it was returned from IConnectionLister.AcceptAsync(). But now that it's returned from IMultiplexedConnectionListener.AcceptMultiplexedAsync(), we could reconsider that. One thing I like about this design is we could avoid having ConnectionContext that would can be neither read from nor written to. Even though the only property you *don't* want from ConnectionContext is probably the Transport IDuplexPipe, I still think it will be better if the type system prevents people from thinking the Transport IDuplexPipe will work.

Having a StreamConnectionContext that derives from ConnectionContext makes a lot of sense even if we stick with something closer to the old design with a IQuicStreamListenerFeature.

**Comment by davidfowl** [comment]
It has to be a connection context. Do you really want another middleware pipeline that only works for multiplexed connections?

**Comment by jkotalik** [comment]
> Does IMultiplexedConnectionListenerFactory exist just so you can tell early what type of listener you'll get from it? 

As you mentioned, I'd like for kestrel to inject both listener factories. You can resolve IMultiplexedConnectionListenerFactory and IConnectionListenerFactory individually.

> Or better yet, keep IMultiplexedConnectionListenerFactory but don't have it derive from IConnectionListener at all. Kestrel could inject both kinds of listeners and use the right one where appropriate.

That could work. To make sure I'm on the same page, it would look like:
```c#
public interface IMultiplexedConnectionListenerFactory
{
}
public interface IMultiplexedConnectionListener
{
    ValueTask<MultiplexedConnectionContext> AcceptMultiplexedAsync(CancellationToken cancellationToken = default);
}
public class MultiplexedConnectionContext : ConnectionContext
{
    ValueTask<StreamConnectionContext> AcceptStreamAsync();
    ValueTask<StreamConnectionContext> ConnectStreamAsync(bool unidirectional); // undirectional or bidirectional stream, like half open/half close
}
public class StreamConnectionContext : ConnectionContext
{
    int StreamId { get; }
    Direction Direction{ get; }
}
// Wordsmith this pls.
public enum Direction
{
   Bidirectional,
   UnidirectionalInbound,
   UnidirectionalOutbound
}
```

And as @davidfowl mentioned, everything we return needs to return a ConnectionContext, so I'll keep both of these deriving from ConnectionContext.

**Comment by anurse** [comment]
> Do you really want another middleware pipeline that only works for multiplexed connections?

Spicy question (though I'm not entirely sold either way yet): Is there middleware that can work on both a Multiplexed and a Non-Multiplexed connection?

I suppose I can think of some that just operate on features, such as a filtering middleware that rejects connections based on some conditions (remote IP, TLS cipher selections, etc.).

What about pulling up a new base class or interface that doesn't have a body pipe for those shared middleware to use? We're really early in bedrock, so it's a good time to think about this kind of refactoring (if we're ever going to do it).

> ```cs
> public class MultiplexedConnectionContext : ConnectionContext
> {
>     ValueTask<StreamConnectionContext> AcceptStreamAsync();
>     ValueTask<StreamConnectionContext> ConnectStreamAsync(bool unidirectional); // undirectional or bidirectional stream, like half open/half close
> }
> public class StreamConnectionContext : ConnectionContext
> {
>     int StreamId { get; }
>     Direction Direction{ get; }
> }
> ```

These APIs are too rigid IMO. QUICv1 is likely to only have the one "attribute" associated with a stream (its directionality), but what if QUICv2 adds a new attribute that should be specified during "Connect"? What about other multiplexed protocols? Will they all have a concept of directionality?

Also, we talked in corefx about using the term `Open` for streams since there isn't really a connection handshake involved.

**Comment by davidfowl** [comment]
> I suppose I can think of some that just operate on features, such as a filtering middleware that rejects connections based on some conditions (remote IP, TLS cipher selections, etc.).

Maybe we can ask more questions here, What does this mean for SignalR? How would we go about changing it to work in a world where there are multiplexed streams? How far does it need to bleed?

> What about pulling up a new base class or interface that doesn't have a body pipe for those shared middleware to use? We're really early in bedrock, so it's a good time to think about this kind of refactoring (if we're ever going to do it).

Make sense, but what would take the interface? Where would it be used?

> These APIs are too rigid IMO. QUICv1 is likely to only have the one "attribute" associated with a stream (its directionality), but what if QUICv2 adds a new attribute that should be specified during "Connect"? What about other multiplexed protocols? Will they all have a concept of directionality?

That's what features are for. I think if we're going to do a multiplexed stream type, it needs to be lowest common denominator (like ConnectionContext currently is).

**Comment by anurse** [comment]
Right but the `ConnectStreamAsync` takes a single argument. How would that scale to other attributes?

**Comment by davidfowl** [comment]
We have this same problem on the client side BTW, ConnectAsync should take a property bag.

**Comment by jkotalik** [comment]
Alright, I think we have something we can spike here. I'll make a PR once I merge the initial HTTP/3 PR.

**Comment by davidfowl** [comment]
I’m writing up something for how SignalR would use it

**Comment by jkotalik** [comment]
> We have this same problem on the client side BTW, ConnectAsync should take a property bag.

This also applies to ConnectionAsync for the IConnectionFactory.

**Comment by anurse** [comment]
Spicy thought (I already talked to @jkotalik about this). What if `ConnectStreamAsync` and `ConnectAsync` took an `IFeatureCollection`? That's a pretty good "strongly-typed property bag" we have already. I don't think it would necessarily be that the implementation takes that `IFeatureCollection` and uses it as the base feature collection for the resulting `ConnectionContext`, it just seems like the a nice kind of "property bag" we already have...

**Comment by davidfowl** [comment]
That’s not spicy, it’s logical 😬

**Comment by jkotalik** [comment]
I went ahead and tried my original proposal and I wasn't happy with the results. Here are my findings:

- Splitting IConnectionListener(Factory) and IMultiplexedConnectionListener(Factory) didn't feel good when dealing with shared code. For example, in [KestrelServer.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/KestrelServer.cs#L24), we have a list of listeners we are accepting from, a dispatcher, etc. that make it hard to split the world on, when in reality they are doing very similar things.
- Muxing/demuxing a connection to a stream doesn't really work if the MultiplexedConnectionContext doesn't derive from ConnectionContext. For HTTP/3, we need to be able to accept a connection up to HttpConnection/Http3Connection. With that, it needs to go through all of the connection middleware first or we would need to short circuit the connection middleware pipeline and just create an HttpConnectionContext (see [HttpConnectionMiddleware](https://github.com/aspnet/AspNetCore/blob/ba15186bbe779d774fa60044f90df4da4dba2ef2/src/Servers/Kestrel/Core/src/Middleware/HttpConnectionMiddleware.cs)). The question remains if we should create a separate pipeline of connection middleware for multiplexed connections.

So I'm going to be a lot more conservative with this proposal now: I'm only targeting removing the odd features that expose accept and connect functionalities.
Here is the updated proposal:
```c#
public class MultiplexedConnectionContext : ConnectionContext
{
    ValueTask<StreamConnectionContext> AcceptAsync(CancellationToken token = default);
    ValueTask<StreamConnectionContext> ConnectAsync(IFeatureCollection features = null, bool unidirectional = false, CancellationToken token = default);
}
public class StreamConnectionContext : ConnectionContext
{
    long StreamId { get; } // ConnectionId is a string today, StreamId for HTTP/3 needs to be a long, figure out how to consolidate.
    Direction Direction{ get; }
}
public enum Direction
{
   BidirectionalInbound,
   BidirectionalOutbound,
   UnidirectionalInbound,
   UnidirectionalOutbound
}
public class IConnectionFactory
{
   ValueTask<ConnectionContext> ConnectAsync(IFeatureCollection features = null, CancellationToken token = default);
}
```

**Comment by halter73** [comment]
> The question remains if we should create a separate pipeline of connection middleware for multiplexed connections.

I that the plan was that there would be two pipelines. Why wouldn't there be?

> So I'm going to be a lot more conservative with this proposal now

Having MultiplexedConnectionContext derive from ConnectionContext is not conservative. The more conservative action is to not have the is-a relationship. It could easily be added later, but removing the base class would be more tricky.

**Comment by jkotalik** [comment]
> I that the plan was that there would be two pipelines. Why wouldn't there be?

What concerns me is how we would handle this in Kestrel as well as handling it in connection middleware. As I mentioned before:

For HTTP/3, we need to be able to accept a connection up to HttpConnection/Http3Connection. With that, it needs to go through all of the connection middleware first or we would need to short circuit the connection middleware pipeline and just create an HttpConnectionContext (see HttpConnectionMiddleware).

Maybe that's okay to have duplicated HttpConnectionMiddleware and a duplicated pipeline, but it was starting to smell so I aborted that idea for now in my draft.

> Having MultiplexedConnectionContext derive from ConnectionContext is not conservative. The more conservative action is to not have the is-a relationship. It could easily be added later, but removing the base class would be more tricky.

I think at this point, we should have a design meeting, as I am pulling back from my original proposal after prototyping.

**Comment by davidfowl** [comment]
@halter73 it forks *everything* to avoid a null `IDuplexPipe` and that's a reasonable concern but it's a non trivial change to kestrel and bedrock and we should be sure that it's worth forking at that layer.

**Comment by halter73** [comment]
I'm not saying it's trivial, but if we are going to split the pipeline, it will be easier to do it earlier rather than later.
