### ISSUE TITLE
Improve developer experience of VSCode extension

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#17045]
Right now the process of running tests and developing fixes is laborious in this area because:

1. When running tests you have to re-run the whole functional test suite, which takes about 45+ seconds.
2. When re-running tests after making a change to the test infra it seems that the js files aren't regenerated.
3. If there's a failure within your test you get your line and column numbers relative to the generated JS instead of typescript, which means that our source-map generation must be incorrect.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg you took care of 2 right?

**Comment by ryanbrandenburg** [comment]
Either what I did didn't work or there's some other co-morbid problems in the same vein still happening.
