### ISSUE TITLE
Constantly getting PathTooLongExceptions when deploying an ASP.NET Core website using Web Deploy

### ISSUE THREAD

**Issue by MintPlayer** [dotnet/aspnetcore#17046]
Hi,

Every time I'm publishing an ASP.NET Core project using Web Deploy, I'm getting the infamous PathTooLongException. The path of the file that the publishing wizard complains about is clearly longer than 260 characters (right now I've got one with a length of 261 characters) and my project is positioned in the root of my C-drive.

This really annoys me since all the time I'm wasting time moving my project to the root of my C-drive and renaming the folder of my solution/project. It's only now the first time that I cannot manage to avoid the PathTooLongException, which is why I decided to file an issue here.

As already stated, my project is on the root of my C-drive, so there's nothing more I could do about that. I'm getting the error now for a file with length of **261 characters** (261 !!!!!!). Now I had to rename my project folder...

## Enable long paths in Windows
I already tried the following: https://betanews.com/2016/05/29/long-paths-windows-10/ somehow this time with no success.

- Visual Studio 2019 Stable (16.3.9).
- Windows 10 Home - 1903 (build 18362.418)
- I don't have gpedit

I kinda feel like this should not occur at all, since Microsoft owns both Windows and Visual Studio. I stumbled upon this multiple times past monts and I remember I got around it but now it's not working anymore.

- Is the 260 character path length a limitation that comes with Unix or was it introduced by Windows?
- Is it really necessary to use such a long hash in the path using Web Deploy?

Here's a picture to keep the fun in it :-)

![image](https://user-images.githubusercontent.com/48772716/68718601-03874f80-05aa-11ea-9b90-5b53c21c92db.png)

**Comment by javiercn** [comment]
@MintPlayer Thanks for contacting us.

Is WebDeploy trying to copy/deploy those files and that is how you are getting the exception? 

As far as I understand you wouldn't need to copy anything within the node_modules folder when you are deploying your app.

@vijayrkn This is something in publish, isn't it? Can you take a look?

**Comment by MintPlayer** [comment]
**Is WebDeploy trying to copy/deploy those files?** Yes

Deploying as regular: Right-click ASP.NET Core project --> publish --> IIS, FTP, ... --> Connection + Settings - Remove additional files

The path is already in mentioned in the issue, but since this already contains obj/Release/netcoreapp2.2/.../Out/ClientApp/node_modules/.cache/%module%/%hash% this quickly becomes a long path (the ... = **PubTmp** is something I configured myself in the project file).

**Comment by Pilchie** [comment]
@vijayrkn How should we report this?

**Comment by vijayrkn** [comment]
The best place to report this is websdk. WebSdk has the logic that builds up this path.

**Comment by Pilchie** [comment]
This issue was moved to aspnet/websdk#1243
