### ISSUE TITLE
httpcontext.getiisservervariable always returns null in development

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#17055]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/638965/httpcontextgetiisservervariable-always-returns-nul.html)._

---
I am creating a web api in asp net core 2.2 which will be served from IIS and whose clients need access to some server variables.  The docs for asp net core 2.2 describe the httpcontext extension method GetIISServerVaraible(string)

I am using IISExpress in process hosting for testing and this extension method just returns null.  I imagine something needs to be doen to set the values in IIS Express, but I can't seem to find any information for how to do that.  What am I missing?

---
#### Visual Studio Feedback System on 7/9/2019, 07:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 7/15/2019, 04:55 PM: 

<p>Base on the documentation @ <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.iis.httpcontextextensions.getiisservervariable?view=aspnetcore-2.2">https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.iis.httpcontextextensions.getiisservervariable?view=aspnetcore-2.2</a></p>
<p>Returns null if the feature does not support the IServerVariablesFeature feature. May return null or empty if the variable does not exist or is not set.</p>
<p>Please let us know if this resolves your issue. If not please share sample code/project where this issue is occuring.</p>

#### Pamela Thalacker on 7/16/2019, 11:10 AM: 

<p>I assume IIS supports the IServerVariablesFeature.  Isn't there some way to mock it in IIS Express for testing?</p>

#### Visual Studio Feedback System on 11/12/2019, 08:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Andrew Stanton-Nurse on 11/12/2019, 08:40 PM: 

<p>I’m not aware of a reason this wouldn’t work in IIS Express, but I may be wrong 😃. Since this is an <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core runtime issue, I’m going to move this to our GitHub repo so the team can investigate further.</p>

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment]
Is there a specific variable you're having trouble with? It's possible that the two support different variables.

**Comment by davidfowl** [comment]
We should expose a way to query all variables.

**Comment by jkotalik** [comment]
We need to see if there is an API to get all available server variables. I don't think there is an IIS api.

**Comment by davidfowl** [comment]
There must be https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.servervariables?view=netframework-4.8

**Comment by jkotalik** [comment]
We have tests which check Server Variables with IISExpress here: https://github.com/dotnet/aspnetcore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Servers/IIS/IIS/test/Common.FunctionalTests/Inprocess/ServerVariablesTest.cs

I think we need more information here to figure out why the server variables are null. I'm going to close for now and reopen if you are still hitting the issue.
