### ISSUE TITLE
win-arm64 not found Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by CaiJinHao** [dotnet/aspnetcore#17057]
Only Microsoft.NET core. App was installed successfully on arm64 architecture, but Microsoft. Aspnetcore. App was not installed successfully.I installed it using dotnet-install.sh.Hopefully you can come up with a solution

**Comment by javiercn** [comment]
@CaiJinHao thanks for contacting us.

@aspnet/build can someone take a look here?

**Comment by dougbu** [comment]
@CaiJinHao what are the exact repro steps and what exactly did you observe?

@javiercn though there may be an infrastructure root cause, this is a platform issue.

**Comment by Pilchie** [comment]
I think we're going to look at arm64 support for the ASP.NET Core runtime in the .NET 5 timeframe.

**Comment by snickler** [comment]
In case you're interested, I was able to build the ASP.NET Core Runtime for ARM64 Windows, along with the .NET Core SDK (minus WinForms/WPF). 
https://sinclairinat0r.com/2020/02/05/compiling-net-core-for-windows-10-arm64

**Comment by wli3** [comment]
As part of @tommcdon 's request for win-arm64 SDK. We need win-arm64 version of aspnet core runtime.

**Comment by JunTaoLuo** [comment]
Just to clarify, we are planning to add win-arm64 support. There's already linux-arm64 and linux-musl-arm64 support.
