### ISSUE TITLE
Enable to have a separate css / scss file per component

### ISSUE THREAD

**Issue by jgomesmv** [dotnet/aspnetcore#17067]
### Describe the solution you'd like
Currently on a blazor single page app all the styles must be created inside of the site.css
I think that in terms on structure, organization and maintainability it's way easier to have styles split per component. 
It's easier for refactoring
It's easier to understand the styles and where they are used

### Additional context
Something like this should do the work:
![image](https://user-images.githubusercontent.com/8100887/68776961-d2019900-0628-11ea-9470-05a5e7f764de.png)

**Comment by javiercn** [comment]
@jgomesmv thanks for contacting us.

We'll consider this feature during the next release planning period and update the status of this issue accordingly.

**Comment by jgomesmv** [comment]
That's great! Thanks for the feedback!

**Comment by mkArtakMSFT** [comment]
We'll be handling this as part of https://github.com/dotnet/aspnetcore/issues/10170
