### ISSUE TITLE
@aspnet/signalr - Unable to receive a message sent to concrete client

### ISSUE THREAD

**Issue by StanislavChankov** [dotnet/aspnetcore#17106]
### Describe the bug
I am unable to receive a message sent from AspNetCore WebApi via `Microsoft.AspNetCore.SignalR` Hub to concretely targeted client.
The issue I am encountering exists **only**, when I am trying to send the message to single client:
`await Clients.Client("Valid connection Id").SendAsync("Client message", response);`

I am successfully sending the same message passing the same flow, when sending it to all of the clients:
`await Clients.All.SendAsync("Client message", response);`

### To Reproduce
The code pictures are just examples of what I am trying to do.

Back-end AspNetCore side
![image](https://user-images.githubusercontent.com/35253870/68892278-4cb2dd00-072b-11ea-9e20-59620545f89e.png)

Front-end Angular side
![image](https://user-images.githubusercontent.com/35253870/68892468-c945bb80-072b-11ea-9fb6-c4445a7b6630.png)

### Further technical details
- ASP.NET Core version - `netcoreapp3.0`
- Node.js version - `10.16.3`
- Angular version - `8.3.6`
- aspnet/signalr version - `1.1.4`
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/35253870/68891666-fbeeb480-0729-11ea-91e6-6c50bac38647.png)

![image](https://user-images.githubusercontent.com/35253870/68892533-e7abb700-072b-11ea-8177-05ab1d289b93.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 - 16.3.5
![image](https://user-images.githubusercontent.com/35253870/68891853-5b4cc480-072a-11ea-9daf-c43e6ec750dc.png)

![image](https://user-images.githubusercontent.com/35253870/68891742-280a3580-072a-11ea-872e-8ff567fd7423.png)

**Comment by BrennanConroy** [comment]
First question I have to ask, how do you know you have a valid connection Id?

**Comment by StanislavChankov** [comment]
> First question I have to ask, how do you know you have a valid connection Id?

Good question I could say. I am caching the connections to the memory cache and also a logger to the `override Task OnDisconnectedAsync(Exception exception)` method indicating, when some user gets disconnected.

**Comment by BrennanConroy** [comment]
And you're using `Context.ConnectionId` from inside the Hub to get the connection ID initially?

**Comment by StanislavChankov** [comment]
> Context.ConnectionId

That's right.

**Comment by BrennanConroy** [comment]
I can't think of anything that would be wrong from the info provided. Would it be possible for you to make a minimal repro app and put it on github?

**Comment by halter73** [comment]
If you send a message directly to the `Context.ConnectionId` in OnConnectedAsync, does that work?

**Comment by StanislavChankov** [comment]
> If you send a message directly to `Context.ConnectionId` in OnConnectedAsync, does that work?

No. I am not able to send any message to anyone from `OnConnectedAsync`. I have tried `Client(Context.ConnectionId)`, `All`, `Caller`, but isn't it expected behavior? I am not able to send any message from `OnConnectedAsync` in other hubs as well.

I wrote an integration test, which shows exactly the same behavior. I am able to send a message, when I target all of the clients, but not able, when I select exact client. Therefore we are eliminating the possible issues in my client application and @aspnet/signalr library.

**Comment by StanislavChankov** [comment]
> I can't think of anything that would be wrong from the info provided. Would it be possible for you to make a minimal repro app and put it on github?

Is there a small app `netcoreapp3.0` with workin with example showing how to send private messages `Clients.Client()`

**Comment by BrennanConroy** [comment]
Sure, I created a super simple 3.0 app that sends to `Clients.Client(Context.ConnectionId)` in `OnConnectedAsync`.

https://github.com/BrennanConroy/3_0_Sample

**Comment by StanislavChankov** [comment]
Good job @BrennanConroy ! I have tested it and it is working perfectly. I created another branch of the your repo, where I cached in the memory the connections in `OnConnectedAsync` and send the message to the other user in `SendMessage` and it is working properly.

I noticed that you are using `@microsoft/signalr`, which is created for AspNetCore. However I am using `@aspnet/signalr` as I have described above. I guess that's my mistake and switching to `@microsoft/signalr@3.0.0` will fix the issue.

**Comment by BrennanConroy** [comment]
> However I am using `@aspnet/signalr` as I have described above. I guess that's my mistake and switching to `@microsoft/signalr@3.0.0` will fix the issue.

Using @aspnet/signalr shouldn't cause any issues. I switched the sample to @aspnet/signalr@1.1.4 and it continued working as expected.

> One more thing, not only sending to concrete client, but also `OnDisconnectedAsync` is not working on `@aspnet/signalr@1.1.4` with `netcoreapp3.0`

What isn't working? You probably wont be able to send a message to the specific client that is closing because it is in the process of shutting down.

Could you please provide a sample app that shows these things not working properly?

**Comment by StanislavChankov** [comment]
1. I had an issue with authorization. Exactly the same as `ddydeveloper` had in https://github.com/aspnet/SignalR/issues/1764 . Hope that help to anyone.
```
            services
                .AddAuthentication("Bearer") // Just an example
                .AddJwtBearer(options =>
                {
                    options.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
                        {
                            var accessToken = context.Request.Query["access_token"];
                            if (!string.IsNullOrWhiteSpace(accessToken))
                            {
                                context.Token = accessToken;
                            }

                            return Task.CompletedTask;
                        }
                    };
                });
```
2. I worked around the issue with `Clients.Client(clientConnectionId)` with `Clients.User(staOpsConnections.Id)`. I guess I will come back, when I have to create a anonymous hub. I am sorry that I don't have enough time to provide you a sample repo of the issue.
