### ISSUE TITLE
MvcRazorCompileOnPublish does not work correctly in .NET Core 3.0 SDK

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17112]
Previous discussion here: https://github.com/aspnet/AspNetCore/issues/16688

----------------------------------------------------------------------

This might be a bug in the SDK:

https://github.com/aspnet/AspNetCore-Tooling/blob/3ed4e871790a9a56ea617cca6659033d0918a1d2/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L177-L180

The evaluation order seems to be incorrect. We have tests for this, but they aren't set up correctly to identify this: https://github.com/aspnet/AspNetCore-Tooling/blob/a833cd4b30de213aafca02e8cf6e7a4b2c4610d7/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTestLegacy.cs#L94-L109.

**Comment by pranavkm** [comment]
For future reference, the `<RazorCompileOnPublish>false</RazorCompileOnPublish>` would be the substitute gesture for this in 3.0.

**Comment by FalconWu2017** [comment]
@pranavkm It still not working in #16688 and I do not know how I open the issue.
