### ISSUE TITLE
key ring is not stored to default location %LOCALAPPDATA%/ASP.NET/DataProtection-Keys

### ISSUE THREAD

**Issue by ileve** [dotnet/aspnetcore#17180]
I know that i can specify a customized storage location for key ring with `PersistKeysToFileSystem` method. For example:
```C#
services.AddDataProtection()
        .PersistKeysToFileSystem(new DirectoryInfo("e:\\asp.net.core\\temp\\keys"))
        .ProtectKeysWithDpapi()
        .SetApplicationName("staticapp");
```

But what i cannot understand, is why the key ring is not stored automatically to default location `%LOCALAPPDATA%/ASP.NET/DataProtection-Keys` when i use the following snippet.

```C#
services.AddDataProtection()
        .ProtectKeysWithDpapi()
        .SetApplicationName("staticapp");
```

I get an invalid operation exception `(The 'IXmlRepository' instance could not be found. When an 'IXmlEncryptor' instance is ...)` instead of storing the encrypted key ring in the default location. Why is that?

**Comment by blowdart** [comment]
What operating system is this one? Where are you hosting? I'm a little confused by / rather than \

**Comment by ileve** [comment]
Windows 7 x64 SP1 and i am talking in development mode with IIS express.

**Comment by blowdart** [comment]
That's strange. What is data protection saying in the startup logs?

(As an aside you know you'll be completely out of support with Win7 in January?)

**Comment by ileve** [comment]
If you mean the debug output window, it displays what i have already mentioned above.
`An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll
The 'IXmlRepository' instance could not be found. When an 'IXmlEncryptor' instance is set, a corresponding 'IXmlRepository' instance must also be set.`

The invalid operation exception happens when in `Program.cs` file, the following line is executed, in `main` entry point.

```c#
CreateHostBuilder(args).Build().Run();
```
And the `CreateHostBuilder` is:
```c#
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });

```

**Comment by ileve** [comment]
I will test it on a windows 10 laptop machine, to see if the same thing happens and i will update my feedback info.

**Comment by ileve** [comment]
I have just tested it in Windows 10 machine and i still get the same exception. It has nothing to do with the windows operating system.

**Comment by HaoK** [comment]
Yeah this is expected, basically if you change any of the defaults, you must tell data protection where to persist the keys via the 4 persist extension methods: see comment at:

https://github.com/dotnet/aspnetcore/blob/b3599b6cfa1a65da3c3b5c74fa63111bdf62be34/src/DataProtection/DataProtection/src/IDataProtectionBuilder.cs#L17

And for reference the persist extension methods are all setting the IXmlRepository

https://github.com/dotnet/aspnetcore/blob/416d8cd1ea098eb643b4258247af3448f5545c32/src/DataProtection/DataProtection/src/DataProtectionBuilderExtensions.cs#L213
