### ISSUE TITLE
Should pick a TypeScript compile version

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#17199]
### Describe the bug
Builds get a fair number of warnings that are not good matches for the `msbuild` rules. These warnings are noise.

### To Reproduce
Do a full build or download a build log from AzDO. Observe warnings such as
```
TypeScriptNoVersionWarning = Your project does not specify a TypeScriptToolsVersion. The latest available TypeScript compiler will be used (3.7). To remove this warning, set TypeScriptToolsVersion to a specific version or "Latest" to always select the latest compiler.
```
Occasionally `(3.7)` is logged in encoded form (`%283.7%29`).

### Further technical details
- Noticed originally in a 'release/3.0' build but likely affects other branches

**Comment by dougbu** [comment]
@anurse @mkArtakMSFT could one of you please find someone to look at this?

**Comment by anurse** [comment]
I don't believe we use TypeScript in MSBuild at all, we do our own TS building. Probably can just put `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` in a common props file.

I can probably have someone look at this later this week.

**Comment by javiercn** [comment]
@anurse  is correct. I'm wondering if we are importing the typescript build package somewhere.

@anurse suggestion is also valid for Blazor I think.

**Comment by anurse** [comment]
I'm not seeing these warnings in any builds right now. Is this still causing problems @dougbu?

**Comment by dougbu** [comment]
I just double-checked a detailed log for a local `.\build.cmd -all` of the 'master' branch. No matches for `TypeScriptNoVersionWarning`. I suspect we now set `$(TypeScriptCompileBlocked)` everywhere it's needed.
