### ISSUE TITLE
LocalizedHtmlString (HtmlFormattableString) crash internally trying replacing {0} without input param array

### ISSUE THREAD

**Issue by anisite** [dotnet/aspnetcore#17191]
## Describe the bug
The problem is exactly like this one : https://github.com/aspnet/AspNetCore/issues/2642

### To Reproduce
If I call @Localizer["myLabelToTranslate"] but this key contains value like "This is {0} my value" an internal fonction of HtmlFormattableString is crashing.

I opened the source code and saw the WriteTo function is calling string.Format() all the time, without checking if _args contains something.

This part of code is wrong
``` C#
public void WriteTo(TextWriter writer, HtmlEncoder encoder)
{
    if (writer == null)
    {
        throw new ArgumentNullException(nameof(writer));
    }

    if (encoder == null)
    {
        throw new ArgumentNullException(nameof(encoder));
    }

    var formatProvider = new EncodingFormatProvider(_formatProvider, encoder);
    writer.Write(string.Format(formatProvider, _format, _args));
}
```

### Further technical details
- ASP.NET Core 3.0 (100)

**Comment by javiercn** [comment]
@anisite thanks for contacting us.

@ryanbrandenburg do you have any ideas?

**Comment by ryanbrandenburg** [comment]
@anisite could you provide a minimal repro app as a GitHub repo? It helps us look at the exact issue you're seeing rather than having to approximate your scenario.

**Comment by anisite** [comment]
@ryanbrandenburg this one here is not good? https://github.com/hiiru/LocalizationBugExample I based my work on this guy solution as workarround. Please tel me.

**Comment by ryanbrandenburg** [comment]
That repro is using netcoreapp1.1, manually embedding resources and manually compiling Designer.cs files (the last two being things we tell people not to do in later releases). Given that you said you're using ASP.NET Core 3.0 you must have made significant changes, and I'd like my tests to reflect those so we can be sure I solve the precise problem you're seeing.

**Comment by anisite** [comment]
Ok. I Will Do a repo! Thanks

**Comment by anisite** [comment]
here a demo project targeting .net core 3.1 https://github.com/anisite/LocalizerBug

**Comment by anisite** [comment]
In demo project, this part of code:
```html
<div class="text-center">
    <h1 class="display-4">this is : @Localize["demo", new[] { "working" }]</h1>
    <h2 class="display-4">this is : @Localize["demo"] (buffer output fail here...)</h2>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
```
render like that:
![image](https://user-images.githubusercontent.com/3194288/70366433-5381cb00-1865-11ea-83a1-c28c571bdba1.png)

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please look into the provided repro project to understand what is causing this behavior? Please update this issue with your findings.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by anisite** [comment]
Hi @mkArtakMSFT it's second time the Community report this problem. We need to use a work arround to prevent that from crashing we have lost several time investigate into it. It's in reality a small bug. Quite simple to fix. Why don't fix it? Thanks
