### ISSUE TITLE
Is it possible to change login url from one place? 

### ISSUE THREAD

**Issue by scalablecory** [dotnet/aspnetcore#17211]
_From @Aleksej-Shherbak on Saturday, November 16, 2019 5:53:24 PM_

I will describe what I mean here.  By default, Identity has the following login URL: `/Identity/Account/Login`. I would like to change it on just `/Login`. 

And I have it done! For this I have added on the `Login.cshtml` file the following code: 
```
@page "/Login"
```
And it works, but after logout I have redirect on the previous URL and 404 error. I have added the following on the `Startup.cs` to avoid this behavior: 
```
services.PostConfigure<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme,
                opt =>
                {
                    opt.LoginPath = "/Login";
                });
``` 

And it works. Now I have redirection on  `/Login` after logout.  But if I want change URL again I must replace two places, not one. It's uncomfortable. Is it possible from one place? I tried this: 

```
services.PostConfigure<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme,
                opt =>
                {
                    opt.LoginPath = "/Login";
                    opt.LogoutPath = "/Login";
                });
``` 
But without any effect. 
Somebody suggested me to keep login URL in the `appsettings.json` but, I think, it's nonsense. I think, `appsettings.json` is the most unexpected place for URLs. 

Any ideas?     

_Copied from original issue: dotnet/core#3822_

**Comment by cbrit** [comment]
Maybe related to my feature request: #17216

**Comment by blowdart** [comment]
Identity is designed to be in a separate area. I guess you could fudge a route, but that's really an MVC question

@pranavkm ?

**Comment by pranavkm** [comment]
@javiercn would have more context here.

**Comment by cbrit** [comment]
I think the question is more a general one than specifically the Login page:

> But if I want change URL again I must replace two places, not one. It's uncomfortable. Is it possible from one place?

I believe he's asking if there is a way to hard code a route once and then use a reference to it wherever relevant instead of having to hard code it everywhere. Is that right @scalablecory ?
