### ISSUE TITLE
There be many issues with our test infrastructure on AzDO

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#17243]
I started diving into issues I/we have been seeing on AzDO with our test infrastructure and logging. Here are some issues we have:
- Test logs don't show up under attachments (so logged test doesn't show up) for both helix and non-helix builds. For example, [going here](https://dev.azure.com/dnceng/public/_build/results?buildId=431705&view=ms.vss-test-web.build-test-results-tab&runId=13664682&resultId=117361&paneView=debug) should show
- Helix tests don't output any logged tests files.
- Non-helix builds only output flaky tests logged files. For example, under that same build, you can see in Windows_Test_logs that there are only flaky tests in the test folder.
- For tests, we can't tell which os each build is for non-helix builds. They show up as XUnit_TestResults_*
- No trx files are outputted for builds.

cc @aspnet/build @BrennanConroy

**Comment by BrennanConroy** [comment]
>Test logs don't show up under attachments

Looks like AzDo only supports trx and nunit for attachments https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml#attachments-support

**Comment by BrennanConroy** [comment]
>     * Non-helix builds only output flaky tests logged files. For example, under that same build, you can see in Windows_Test_logs that there are only flaky tests in the test folder.

This was fixed yesterday in master (probably want to backport to 3.1).

**Comment by dougbu** [comment]
The bullets above are now fixed, tracked elsewhere, or will become irrelevant as we move remaining tests to Helix.
