### ISSUE TITLE
Figure out what to do with the AutoRebuild

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17248]
The code in here: https://github.com/aspnet/AspNetCore/tree/master/src/Components/Blazor/Server/src/AutoRebuild doesn't work any more. We need to figure out how to revive this feature.

**Comment by mkArtakMSFT** [comment]
@rynowak , given @BillHiebert is looking into enabling this for the entire solution in VS, is there anything else we need to do here?

**Comment by rynowak** [comment]
I'm not sure there's any work for the runtime here. Would like to know if @SteveSandersonMS has other ideas 👍

**Comment by pranavkm** [comment]
At the very least, we should delete the dead code from the package.

**Comment by SteveSandersonMS** [comment]
I definitely agree with removing dead code. None of the existing implementation is likely to have any relation to whatever future solution we implement for this.

**Comment by rynowak** [comment]
Ok great. I will delete the code with glee.
