### ISSUE TITLE
Parsing issue in API version via route

### ISSUE THREAD

**Issue by bderveni** [dotnet/aspnetcore#17242]
### Describe the bug
Api versioning via the URL Path fails when the status contains the same character as the literal.

### Assumption

I read over the [API Version Format documentation](https://github.com/microsoft/aspnet-api-versioning/wiki/Version-Format) to see if there were any constrains on the values that **Status** in *[Version Group.]<Major>.<Minor>[-Status]* can take, but did not find anything. I assumed that this is not desired behavior.

In our case we have a v1-preview version for some of the routes, which fails even when there is a match.

### To Reproduce

[Repo](https://github.com/bderveni/ApiVersioningIssue) with a simple Web API project to reproduce the issue. 
I have included an [insomnia](https://insomnia.rest/) config [file](https://github.com/bderveni/ApiVersioningIssue/blob/master/ApiVersioningIssue.json) with all the following calls. No postman config as I do not use it ¯\_(ツ)_/¯.

Either way the following cURL calls will work just as good once the app is running:

##### Routes with literal A

```cURL
curl -X GET -d "" https://localhost:5001/a1/WeatherForecastVersionLiteralA
```

```cURL
curl -X GET -d "" https://localhost:5001/a1-preview/WeatherForecastVersionLiteralA
```

##### Routes with literal V

```cURL
curl -X GET -d "" https://localhost:5001/v1/WeatherForecastVersionLiteralV
```

```cURL
curl -X GET -d "" https://localhost:5001/v1-status/WeatherForecastVersionLiteralV
```

#### Version parsed but no matching routes with that version

```cURL
curl -X GET -d "" https://localhost:5001/a1-sts/WeatherForecastVersionLiteralA
```

```json
{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI 'https://localhost:5001/a1-sts/WeatherForecastVersionLiteralA' does not support the API version '1-sts'.",
    "innerError": null
  }
}
```

```cURL
curl -X GET -d "" https://localhost:5001/v1-sts/WeatherForecastVersionLiteralV
```

```json
{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI 'https://localhost:5001/a1-sts/WeatherForecastVersionLiteralA' does not support the API version '1-sts'.",
    "innerError": null
  }
}
```

##### Routes with literal A

```cURL
curl -X GET -d "" https://localhost:5001/a1-statusWithAIn/WeatherForecastVersionLiteralA
```

```json
{
  "error": {
    "code": "ApiVersionUnspecified",
    "message": "An API version is required, but was not specified.",
    "innerError": null
  }
}
```

##### Routes with literal V

```cURL
curl -X GET -d "" https://localhost:5001/v1-statusWithVIn/WeatherForecastVersionLiteralV
```

```json
{
  "error": {
    "code": "ApiVersionUnspecified",
    "message": "An API version is required, but was not specified.",
    "innerError": null
  }
}
```

### Culprit

The app uses serilog and is configured to log debug messages from the middleware.

The following messages provided good insight into where the issue was:

```log
[Debug] ({ Id: 1002, Name: "CandidateRejectedByComplexSegment" }) Endpoint '"RouteVersioningIssue.Controllers.WeatherForecastVersionLiteralVController.Get (RouteVersioningIssue)"' with route pattern '"v{version:apiVersion}/WeatherForecastVersionLiteralV"' was rejected by complex segment '"v{version:}"' for the request path '"/v1-statusWithVIn/WeatherForecastVersionLiteralV"'

[Debug] ({ Id: 1003, Name: "CandidateRejectedByConstraint" }) Endpoint '"RouteVersioningIssue.Controllers.WeatherForecastVersionLiteralVController.Get (RouteVersioningIssue)"' with route pattern '"v{version:apiVersion}/WeatherForecastVersionLiteralV"' was rejected by constraint '"version"':'"Microsoft.AspNetCore.Mvc.Routing.ApiVersionRouteConstraint"' with value 'null' for the request path '"/v1-statusWithVIn/WeatherForecastVersionLiteralV"'

[Debug] ({ Id: 1004, Name: "CandiateNotValid" }) Endpoint '"RouteVersioningIssue.Controllers.WeatherForecastVersionLiteralVController.Get (RouteVersioningIssue)"' with route pattern '"v{version:apiVersion}/WeatherForecastVersionLiteralV"' is not valid for the request path '"/v1-statusWithVIn/WeatherForecastVersionLiteralV"'
```

After some debugging I think the issue is at the following [line](https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs#L384).

After LastIndexOf(literal.Content, StringComparison.OrdinalIgnoreCase) the literal ends up being the corresponding matching char in the **Status** instead of the first character. The parameter is determined at this [line](https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs#L454). As a result the condition at this [line](https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs#L495) is not satisfied and the complex segment is not matched, hence the behavior. 

### Further technical details

- Microsoft.AspNetCore.Mvc.Versioning 4.0.0

- ASP.NET Core version

 Microsoft.AspNetCore.App 3.0.0

- Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Microsoft Visual Studio Professional 2019, Version 16.3.9

**Comment by rynowak** [comment]
You should probably file this issue at: https://github.com/microsoft/aspnet-api-versioning - that project is separate and is built on top of ASP.NET Core

**Comment by bderveni** [comment]
@rynowak will file it there as well. However, the error results from the routing midleware in this repo.

**Comment by rynowak** [comment]
It might be the case that there are problems in how api-versioning is using complex segments. I can tell you that this is an area that's often misunderstood.

**Comment by bderveni** [comment]
I opened an [issue ](https://github.com/microsoft/aspnet-api-versioning/issues/580) at: https://github.com/microsoft/aspnet-api-versioning.

**Comment by rynowak** [comment]
Great, let's use that to track.

**Comment by rynowak** [comment]
Reopening this. We discussed and the feedback here is really about how routing parses complex segments. This comment has the explain https://github.com/microsoft/aspnet-api-versioning/issues/580#issuecomment-558249270

**Comment by javiercn** [comment]
Closing this issue in favor of https://github.com/dotnet/aspnetcore/issues/19772 as it offers a better alternative for this, and we can't change the behavior for complex segments.
