### ISSUE TITLE
Blazor: Guidance on model reference when using EditContext

### ISSUE THREAD

**Issue by aaronhudon-ts** [dotnet/aspnetcore#17244]
Guidance needed:

When using an EditForm where the EditContext is specified, and *not* the Model, what is the correct way to bind an input to the EditContext's model?

Now, I can handle the set {... } of the MyEditContext property, and extract the model from the Model property, and then use that object for binding, but i just want to be sure I'm following best practices.

E.g.
```
<EditForm EditContext="MyEditContext">
<InputText @bind-Value="....?...."/>
</EditForm>

@code {
    [CascadingParameter]
    public EditContext MyEditContext { get; set; }
}
```

------ OR --------

```
<EditForm EditContext="MyEditContext">
<InputText @bind-Value="myModel.Name"/>
</EditForm>

@code {
    [CascadingParameter]
    public EditContext MyEditContext 
    {
        get => myEditContext;
        set 
         {
            myEditContext = value;
            myModel = value.Model as MyModel;
         }
    }
    EditContext myEditContext;
    MyModel myModel;
   
}
```

**Comment by javiercn** [comment]
@aaronhudon-ts thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?
