### ISSUE TITLE
MarkupString is not being honored in attributes

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/aspnetcore#17251]
### Describe the bug

When trying to embed a line-break in a `title` attribute, I noticed that it is always encoded even when I use `MarkupString`.

### To Reproduce

    <label title="AAA&#013;BBB">Works</label>
    <br/>
    <label title="@((MarkupString)"AAA&#013;BBB")">Doesn't Works, the title is still escaped</label>

### Further technical details

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
```

**Comment by javiercn** [comment]
@Grauenwolf thanks for contacting us.

Could you provide more details? Are you prerendering your app?

**Comment by Grauenwolf** [comment]
Yes, prerendering is enabled. 

I don't know if the bug happens all the time or only during pre/normal rendering. (I'm just starting with this.)

**Comment by Grauenwolf** [comment]
What other details do you need?

**Comment by anurse** [comment]
@Grauenwolf sorry, some automation went a tiny bit agressive ;). Things in the "Discussions" milestone shouldn't be getting this workflow applied.
