### ISSUE TITLE
Frequent Start/Stop connection not working well in SignalR Core Client 3.0

### ISSUE THREAD

**Issue by scottkdavis** [dotnet/aspnetcore#17267]
I have a Xamarin mobile app that has a slide out tab for a chat interface. When the tab is opened, I connect to the Azure SignalR Service (not self-hosted in a web app). When the tab is closed, I stop the connection.  If a user closes the tab, then quickly reopens it (1 second), the SignalR connection often cannot recover.  I do not use auto-reconnect. I don't want it. I have good connection management logic and want the connection to be closed when not in use.

On the reopen, I check the connection state, if it is "Disconnected" I attempt to connect.  I will often get one of two errors. "Invalid negotiation response received." or an error that states that StartAsync cannot be called while StopAsync is running.  If the later error is received, I can attempt to connect again every few seconds for minutes, and will always get the StopAsync is running error. It seems unrecoverable.  

On the other hand, if I encounter the "Invalid negotiation" error, that does seem to go away after 10-20 seconds. This makes me think the server is rejecting the connection request for a client it thinks is already connected. I do occasionally see this error in the prior version of the Nuget package, but less frequently.

The connection state seems to be incorrect for a period of time after calling StopAsync. It states the connection is disconnected, when it isn't quite yet disconnected.  Perhaps there should be a "Disconnecting" state.

The issues exist whether I simply Stop the connection when the tab is closed, or Stop/Dispose/Null the connection, then create a new one with the tab is reopened.

I have rolled back to the previous Nuget package, which works.  Sorry I don't have a sample app for reproduction. I've already lost 12 hours on this issue and lack the time to build a repo project. I understand if no code will result in a closure of the bug report.

Also, I expect the Microsoft response may be to leave the connection open for the lifetime of the mobile application, which would increase my active server connection count by a multiplier of 1000. I'm not inclined to do that.

**Comment by anurse** [comment]
> The issues exist whether I simply Stop the connection when the tab is closed, or Stop/Dispose/Null the connection, then create a new one with the tab is reopened.

This seems really odd to me. The new connection should be using all new state. Can you share a snippet of code illustrating how you create the connection? What options you set, etc.?

**Also**, can you capture a network trace and debug logs from the client side? See https://aka.ms/aspnet/signalr/troubleshoot for guidance on how to enable this.

**Comment by scottkdavis** [comment]
`        public override async Task<bool> VerifyConnectionAsync()
        {
            ApplicationMaster.ViewModels.CommCenter.FailedToConnect = false;
            if (_hubConnection != null && _hubConnection.State == HubConnectionState.Connected)
            {
                UpdateConnectionStatus(_hubConnection.State);
                ApplicationMaster.ViewModels.CommCenter.ShowChatAuthExpired = false;
                return true;
            }
            else if (_token == null || _expiresUtc < DateTime.UtcNow)
            {
                ApplicationMaster.ViewModels.CommCenter.ChatHubConnectionStatus = ChatConnectionStatusEnum.Connecting;
                await ApplicationMaster.ViewModels.Login.LoginWithRetryAsync();
                if (!ApplicationMaster.ViewModels.Login.LoginSuccess)
                {
                    ApplicationMaster.ViewModels.CommCenter.ShowChatAuthExpired = true;
                    UpdateConnectionStatus(HubConnectionState.Disconnected);
                    return false;
                }
            }
            ApplicationMaster.ViewModels.CommCenter.ShowChatAuthExpired = false;

            try
            {
                ApplicationMaster.ViewModels.CommCenter.ChatHubConnectionStatus = ChatConnectionStatusEnum.Connecting;

                if (_hubConnection == null)
                {
                    System.Diagnostics.Debug.WriteLine("Connection NULL: Creating new connection");

                    // Connect to the server
                    var root = RequestFactoryBase.ChatRootURL;
                    if (RequestFactoryBase.ServerTarget == RequestFactoryBase.PROD_ROOT_TARGET)
                    {
                        _hubConnection = new HubConnectionBuilder().WithUrl($"{root}chatHub", options =>
                        {
                            options.AccessTokenProvider = GetAuthTokenAsync;
                        }).Build();
                    }
                    else
                    {
                        _hubConnection = new HubConnectionBuilder().WithUrl($"{root}chatHubTest", options =>
                        {
                            options.AccessTokenProvider = GetAuthTokenAsync;
                        }).Build();
                    }
                    _hubConnection.Closed += _hubConnection_Closed;

                    // Wire up a handler for the methdos for the server
                    // to be called on our client
                    _hubConnection.On<InitChatRoomDto>("InitRoom", HandleChatRoomInit);
                    _hubConnection.On<ChatRoomMessageDto>("GroupMessageReceived", HandleGroupMessageReceived);
                    _hubConnection.On<ChatMessageModifiedDto>("OnMessageLiked", HandleOnMessageLiked);
                    _hubConnection.On<ChatMessageModifiedDto>("OnMessageSuppressed", HandleOnMessageSuppressed);
                    _hubConnection.On<ChatMessageModifiedDto>("OnMessageSuppressedByAuthor", HandleOnMessageSuppressedByAuthor);
                    _hubConnection.On<ChatMessageModifiedDto>("OnMessageFlagged", HandleOnMessageFlagged);
                    _hubConnection.On<string>("OnAlertMessage", HandleOnAlertMessage);
                }

                System.Diagnostics.Debug.WriteLine("Starting - Connection State: " + Enum.GetName(typeof(HubConnectionState), _hubConnection.State));

                // Start the connection
                ApplicationMaster.ViewModels.CommCenter.ChatHubConnectionStatus = ChatConnectionStatusEnum.Connecting;
                await _hubConnection.StartAsync();
                UpdateConnectionStatus(_hubConnection.State);
                if (!string.IsNullOrEmpty(this.LastCurrentFullRoomKeyRequested) || !string.IsNullOrEmpty(this.LastMonitoredFullRoomKeyRequested))
                {
                    await AsyncTrapper.TrapAsync(async () =>
                    {
                        await ConnectToRoomAsync(this.LastCurrentFullRoomKeyRequested, this.LastMonitoredFullRoomKeyRequested);
                    }, Constants.ASYNC_CONNECT_TO_ROOM3, LogSeverityEnum.Verbose);
                }
                UpdateConnectionStatus(_hubConnection.State);
                System.Diagnostics.Debug.WriteLine("Finished Verify Connection: " + Enum.GetName(typeof(HubConnectionState), _hubConnection.State));
                return true;
            }
            catch (Exception exc)
            {
                _connectionFailureCount++;
                Client.Helpers.ProgramTracer.WriteLine(Client.Enums.ProgramTraceType.OkToIgnore, "Ignored Exception: " + exc.Message);
                WebException webx = exc as WebException;
                //chat server seems to be offline
                ApplicationMaster.ViewModels.CommCenter.FailedToConnect = true;
                if (webx != null && (webx.Status == WebExceptionStatus.ConnectFailure || webx.Status == WebExceptionStatus.NameResolutionFailure))
                {
                    System.Diagnostics.Debug.WriteLine("Connection Failed: " + Enum.GetName(typeof(HubConnectionState), _hubConnection.State));
                }

                //if (System.Diagnostics.Debugger.IsAttached)
                //{
                //    System.Diagnostics.Debugger.Break();
                //}

                System.Diagnostics.Debug.WriteLine("Connection Failed Exception: " + exc.Message);

                await CleanUpAsync();
                return false;
            }            
        }
private async Task CleanUpAsync()
        {
            try
            {
                if (_hubConnection != null)
                {
                    System.Diagnostics.Debug.WriteLine("Stopping Connection: " + Enum.GetName(typeof(HubConnectionState), _hubConnection.State));
                    await _hubConnection.StopAsync();
                    System.Diagnostics.Debug.WriteLine("Stopped Connection: " + Enum.GetName(typeof(HubConnectionState), _hubConnection.State));

                    if (_connectionFailureCount > 3)
                    {
                        //after three failures, throw away object in finally
                        await _hubConnection.DisposeAsync();
                        System.Diagnostics.Debug.WriteLine("Disposed");
                    }
                }
                UpdateConnectionStatus(HubConnectionState.Disconnected);
            }
            catch (Exception exc)
            {
                Client.Helpers.ProgramTracer.WriteLine(Client.Enums.ProgramTraceType.OkToIgnore, "Ignored Exception: " + exc.Message);
                //if (System.Diagnostics.Debugger.IsAttached)
                //{
                //    System.Diagnostics.Debugger.Break();
                //}
                System.Diagnostics.Debug.WriteLine("Cleanup Failed: " + exc.Message);
            }
            finally
            {
                if (_connectionFailureCount > 3)
                {
                    //after three failures, throw away object
                    _hubConnection = null;
                    _connectionFailureCount = 0;
                    System.Diagnostics.Debug.WriteLine("Connection set to NULL");
                }
            }
        }
`

**Comment by scottkdavis** [comment]
It may be several days before I can come back to trying the 3.0 version of the client library to attempt to grab a network trace.  Not sure why the post above formatted so poorly.

**Comment by anurse** [comment]
How are you calling this from your event handlers? I ask because generally event handlers are *not* asynchronous and if you aren't careful, this code looks like it could cause races when initializing the `_hubConnection` value.

**Comment by scottkdavis** [comment]
Good tip. I will add a flag to ensure that duplicate calls to not step on each other and report back. I do see this error even if I step through the entire method while debugging which should remove the chance of there being a race condition, but a flag to avoid parallel execution would be good to have regardless. Hopefully I'll be able to try this in a few days and report back. Thanks for the advice.
