### ISSUE TITLE
Consider adding an option to the MVC \ Razor Pages template that enables runtime compilation by default

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17272]
As part of .NET Core 3.0, runtime compilation of views and Razor Pages was moved to a separate package. Our migration guide has a section that deals with re-adding runtime compilation to their projects. Reloading views on file changes relies on VS which only works when the debugger is not attached,

We've had several reports of users being surprised or confused when changes to the views aren't being picked up. This is understandable given users are accustomed to entering <kbd>F5</kbd> in their IDEs and expect things to just work.

One possible way to make this a bit nicer is to have a switch during project creation that enables runtime compilation. 

A couple of things to note:

* [ ] The feature requires templating changes with no runtime changes. 
* [ ] We would need to surface this experience as a UI gesture (a checkbox) during the VS project creation dialog. 
* [ ] We do not want runtime compilation on in non-development environments (runtime compilation results in using the file watcher + blocking async calls both of which are problematic). Having the package reference also results in additional reference assemblies being produced in the build and publish output which we worked hard to eliminate in the 3.0 release. Could we do something more in the templates than adding it behind the `IsDevelopment` flag to minimize the impact on published apps?

**Comment by pranavkm** [comment]
For the last bullet point, we have a sample of what the template might look like if we conditionally referenced the package: 

* https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/Startup.cs#L32-L41
* https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/MyApp.csproj#L11-L13

/cc @DamianEdwards

**Comment by pranavkm** [comment]
Ping @danroth27 \ @mkArtakMSFT. Since the suggestion is to do this for a patch release, should we triage this for an earlier release?

**Comment by DamianEdwards** [comment]
Keeping pinging @pranavkm 😄

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/18648

**Comment by pranavkm** [comment]
Verified. For users starting with a new application, both the CLI and VS offer an option to enable runtime compilation. For users updating, here are the two steps required to enable runtime compilation only during development:

a) Add a PackageReference to `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` version 3.1.3 or newer.
b) Update `launchSettings.json` to include a `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` environment variables:

```diff
"WebApplication3": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
-        "ASPNETCORE_ENVIRONMENT": "Development"
+        "ASPNETCORE_ENVIRONMENT": "Development",
+        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      }
    }
```
