### ISSUE TITLE
Add method to indicate an event handler should enforce value consistency

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#17281]
In other words, a way to tell Blazor that a given event handler is part of a two-way binding even if you're not using `@bind`.

It would probably look like this:

```razor
<input value="@MyValue" @onchange="MyHandler" @onchange:enforceConsistency />
```

... or maybe `@onchange:sync` or `@onchange:twoWay`. The implementation is simply to emit a `builder.SetUpdatesAttributeName` call for whatever is the "value" attribute for this element type (e.g., on `<input type=checkbox>` it would call `builder.SetUpdatesAttributeName("checked");`).

For more details about the scenario and justification for this design, see https://github.com/aspnet/AspNetCore/issues/17099#issuecomment-556825048

**Comment by JvanderStad** [comment]
The `onchange` event handler receives a `Microsoft.AspNetCore.Components.ChangeEventArgs` instance.

```c# 
namespace Microsoft.AspNetCore.Components
{
    //
    // Summary:
    //     Supplies information about an change event that is being raised.
    public class ChangeEventArgs : EventArgs
    {
        public ChangeEventArgs();

        //
        // Summary:
        //     Gets or sets the new value.
        public object Value { get; set; }
    }
}
```

Can't we use the `Value`-setter to reflect changes?

```c# 
public void ChangeEvent(ChangeEventArgs args)
{
	args.Value = "new value";
}
```

**Comment by hultqvist** [comment]
Could you also look into a scenario where the value is modified elsewhere, for example in a form submit method. The change in MyValue won't be related to the `@onchange` event.

**Comment by hultqvist** [comment]
I'm looking for a workaround.
This one appears to work though there's some magic in there.

    async Task MyHandler(ChangeEventArgs args)
    {
        var old = Text;
        Text = args.Value as string;
        await Task.Delay(1); //Magic!
        Text = old;

**Comment by thalaeg** [comment]
@hultqvist I know its a little late, but you can do a get and set with a private variable like this illustrates
https://stackoverflow.com/questions/60378477/filter-blazor-input-field

**Comment by JvanderStad** [comment]
Looking forward to this one!

**Comment by danroth27** [comment]
@SteveSandersonMS Do we still need this now that we have get/set/after?

**Comment by javiercn** [comment]
@SteveSandersonMS I believe this is handled, if not, feel free to reopen
