### ISSUE TITLE
how to access a remote shared folder with credential in asp.net core if you're not using IIS?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/aspnetcore#17293]
How can you read/write to a protected, windows based, network share, if you're not using IIS hosting?

**Comment by blowdart** [comment]
You either run the kestrel process as a user accounts with rights, or use impersonation in your code to become a user with rights. Note that impersonation does not support async.

**Comment by Leonardo-Ferreira** [comment]
@blowdart would you mind sharing a few more details? would you be able to provide a code sample? bear in mind that some people, like me, host the app on linux
