### ISSUE TITLE
Endpoint routing strange behavior

### ISSUE THREAD

**Issue by DaniilSokolyuk** [dotnet/aspnetcore#17292]
### Describe the bug
I have controller with 2 actions
`personalpage/{userID:long}/{**filterString}`
`{subjectType:dummy}/{subjectId:long}/reviews/{**filterString}` where dummy constraint always false (for example)
When i make request to `personalpage/123456/reviews/movies/` i expect action with route `personalpage/{userID:long}/{**filterString}` but i got 404 
debug log
```
      1 candidate(s) found for the request path '/personalpage/123456/reviews/movies/'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1003]
      Endpoint 'EndpointRoutingStrange.Controllers.MainController.Reviews (EndpointRoutingStrange)' with route pattern '{subjectType:dummy}/{subjectId:long}/reviews/{**filterString}' was rejected by constraint 'subjectType':'EndpointRoutingStrange.DummyConstraint' with value 'personalpage' for the request path '/personalpage/123456/reviews/movies/'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1004]
      Endpoint 'EndpointRoutingStrange.Controllers.MainController.Reviews (EndpointRoutingStrange)' with route pattern '{subjectType:dummy}/{subjectId:long}/reviews/{**filterString}' is not valid for the request path '/personalpage/123456/reviews/movies/'
```
Why only 1 candidate?
If set EnableEndpointRouting=false, and UseMvc instead endpoint routing i got first action as expected

### To Reproduce
Repro: https://github.com/DaniilSokolyuk/endpointroutingstrange

### Further technical details
- ASP.NET Core version 3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DaniilSokolyuk.
@rynowak can you please look into this one? Thanks!

**Comment by javiercn** [comment]
@rynowak Can this be a bug in the DfA?

**Comment by DaniilSokolyuk** [comment]
@rynowak it could be fixed in 3.1?

**Comment by DaniilSokolyuk** [comment]
@rynowak @javiercn ping

**Comment by javiercn** [comment]
Very likely to be due to this:
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#conventional-routing-order

Use `   AppContext.SetSwitch("Microsoft.AspNetCore.Routing.UseCorrectCatchAllBehavior", ` in your app and let us know if you still have issues.

I'm closing this for now, but feel free to commend and we'll re-evaluate.
