### ISSUE TITLE
Replace Error.razor with Error.cshtml in the Blazor Server template

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#17312]
The Blazor Server template currently uses a Razor component for the /error page, which is overkill. We should replace the Error.razor page with a normal Razor page, Error.cshtml.

**Comment by mkArtakMSFT** [comment]
Handle this as part of this work: https://github.com/dotnet/aspnetcore/issues/19670

**Comment by mkArtakMSFT** [comment]
@javiercn putting this in 3.1.x to handle post 5.0-preview4 work.
