### ISSUE TITLE
Naming a project "website-getdonet" causes ANCM to fail loading the app

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17393]
When I try this locally, here’s the application logs I see:

```
Application 'C:\Users\prkrishn\source\repos\website-getdotnet\website-getdotnet\' failed to start. Exception message:
Unable to find hostfxr directory at C:\Users\prkrishn\source\repos\website-getdotnet\website-getdotnet\bin\Debug\netcoreapp3.1\host\fxr
Failed to start application '/LM/W3SVC/2/ROOT', ErrorCode '0x8007023e'.
```

Different app:
```
Application 'C:\Users\prkrishn\source\repos\website-getdotne1\website-getdotne1\' started successfully.
```

**Comment by Tratcher** [comment]
Lol, do we have an EndsWith("dotnet") in there somewhere?

**Comment by anurse** [comment]
Sounds like it. We need to be a little cleverer and look at the trailing path.

However, no customers have reported this yet, so not the highest pri.

**Comment by pranavkm** [comment]
^ This one was customer reported, but I'd agree not the highest priority given it's fairly easy to run in to this.

**Comment by anurse** [comment]
Ah, thanks for the context :)

**Comment by rin0o1** [comment]
I think so

**Comment by jkotalik** [comment]
This was done! Thanks @newbienewbie
