### ISSUE TITLE
too many files open error in linux

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#17395]
_From @for7raid on Thursday, November 7, 2019 7:11:03 AM_

# too many files open error in linux

After several hours of work web application on cent os 7 gets error "Too many files open"

# General

After each request to my application the system opens and keep open a lot of /dev/zero files.
I run command `lsof | grep zero | wc -l` and looking out that count of files increase and increase.

![image](https://user-images.githubusercontent.com/34707446/68367453-d28cc200-0146-11ea-91c2-2d2b4e9828ad.png)

# System Info
OS LINUX X64 Linux 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 Cent OS 7
.NET Core 3.0.0

_Copied from original issue: dotnet/core#3769_

**Comment by Pilchie** [comment]
_From @scalablecory on Thursday, November 7, 2019 3:10:58 PM_

Are you opening /dev/zero, or do you think it is being opened by something within .NET?

Can you share your code?

**Comment by Pilchie** [comment]
_From @for7raid on Friday, November 8, 2019 4:57:17 PM_

We do not open /dev/zero stream in our code.
What I found out.
1. Clear (`dotnet new mvc`) application do not reproduce this issue (it seems to me)
2. We have custom fileproviders for razor and static files, and autofac with specific lifetime model. File providers use FileInfo, PhysicalFileInfo and FileWatchers.
3. It reproduce only when Razor processes the request. In case of Json result - everything is ok, static file is ok too

And it very strange that Razor asks and opens new stream of Shared files (like layout, viewimport etc) several times due one page. 

We can not share the code, because it is very big corporate system. We try to determinate place in code. Will touch you on progress.

**Comment by Pilchie** [comment]
_From @carlossanlop on Tuesday, November 19, 2019 11:17:11 PM_

> _We have custom fileproviders for razor and static files, and autofac with specific lifetime model. File providers use FileInfo, PhysicalFileInfo and FileWatchers._

Are you properly closing the file handles (disposing the file handling objects) after using them?

**Comment by Pilchie** [comment]
_From @for7raid on Wednesday, November 20, 2019 9:06:33 AM_

After the long time of investigation we found out the reason.
We do not precompile views on publish and use runtime compilation, so .net tries find (I guess) *.views.dll, cant find it and redirect stream to /dev/zero and doesn't close it.

# Steps to reproduce:
1. Create new clear mvc app `dotnet new mvc`
2. Add runtime view compilation nuget package `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`
3. Edit code in Startup.cs file
```
 services.AddControllersWithViews()
            .AddRazorRuntimeCompilation();
```
4. Edit project file to stop compile views on publish
```
  <PropertyGroup>
      <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
      <PreserveCompilationContext>true</PreserveCompilationContext>
      <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
  </PropertyGroup>
```
5. Publish app to folder with following parameters
```
Configuration: Release
Target Framework: netcoreapp3.0
Deployment mode: Framework-Dependent
Target Runtime: Portable
```
6. If publish still reproduces *.view.dll file, remove it, copy Views folder to publish folder
7. Copy publish folder to linux machine
8. Run in standart way `dotnet {fileName}.dll`
9. Open url in browser, wait while app compile views
10. Check opened /dev/zero files via lsof app `lsof | grep zero | wc -l`
11. Count of /dev/zero over the 0 items
12. Open another page
13. Count of /dev/zero increased

P.S. May be we should move this issue to asp repo?

**Comment by Pilchie** [comment]
_From @scalablecory on Thursday, November 21, 2019 9:06:10 PM_

Thanks, that's helpful.

@Pilchie can you help route

**Comment by Pilchie** [comment]
Tagging @mkArtakMSFT for triage.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by for7raid** [comment]
@mkArtakMSFT @Pilchie  I believe that this issue does not relevant to aspnetcore, but this is coreclr issue. I have posted additional info there. You should close this item and reopen original issue, I think.

**Comment by mikhail-barg** [comment]
Is there any progress on this issue? We are using `LoadAssembly` to load results of Roslyn compilation for thousands of small assemblies, and things get really ugly with all FD pool is wasted on /dev/zero (

**Comment by pranavkm** [comment]
@mikhail-barg we haven't investigated this issue as yet. That said, it sounds like your issue isn't specific to ASP.NET Core. Have you tried asking https://github.com/dotnet/roslyn? They would have the best answers about the compiler API usage.

**Comment by for7raid** [comment]
@pranavkm I provided all information about this issue, and believe this is related to core clr team. Could you please touch your colleges to reopen original ticket?

**Comment by mikhail-barg** [comment]
@pranavkm The original issue has been reopened, so it seems there's no need in this issue anymore. Thanks for answering!
