### ISSUE TITLE
Publish with no build doesn't copy static web assets from referenced projects

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17426]
Noticed this as part of writing tests for Blazor.Build. This *might* be an issue outside blazor too. Essentially, when doing a `dotnet publish --no-build`, assets from transitive project references aren't captured. There's an explicit check in the SDK that prevents this:

https://github.com/aspnet/AspNetCore-Tooling/blob/3ed4e871790a9a56ea617cca6659033d0918a1d2/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets#L67-L70

**Comment by pranavkm** [comment]
Uncomment tests in src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs once this is resolved

**Comment by mkArtakMSFT** [comment]
Just a reminder, that we will need to patch this in 3.1, when we get to this.
