### ISSUE TITLE
Blazor. Dynamically created component

### ISSUE THREAD

**Issue by Hellevar** [dotnet/aspnetcore#17429]
Hello everyone!
I'm working on a library, which fully generates Blazor-based component type in the runtime(by using Reflection.Emit). It produces type inherited from the ComponentBase, with it's own BuildRenderTree method logic, fields, properties and so on.
I want to render this generated component on some specific route.
At this moment i'm using approach with additional class component with code like this:

```
[Route("customView")]
    public class CustomView : ComponentBase
    {
        [Inject]
        public ICustomViewTypeProvider TypeProvider { get; set; }

        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            builder.OpenComponent(0, TypeProvider.GetCustomViewType());
            builder.CloseComponent();
        }
    }
```

So, it ships in form of Razor Component library and to use it in the Blazor server side application i need to provide additional parameter to app Router - AdditionalAssemblies="new[] { typeof(CustomView).Assembly }" - 
to allow user to navigate to my customView route and see my generated component.

So the main question - is how to properly use and render such generated type in the Blazor applications? Any better ways how to handle such flow?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

This is not a scenario we support at the moment. Hopefully the community can help you out with this, so leaving this issue open for some time in the `Discussions` milestone.
