### ISSUE TITLE
Add Blazor survey to Blazor Server template

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#17433]
The Blazor survey is currently only used in the Blazor Server template, which skews the data results. We should add the survey to the Blazor Server template as well:

- 3.1: https://go.microsoft.com/fwlink/?linkid=2112271
- 3.0: https://go.microsoft.com/fwlink/?linkid=2112158

**Comment by mkArtakMSFT** [comment]
@danroth27 3.1 is done and we won't be doing the 3.0 change.
