### ISSUE TITLE
'GetAuthenticationStateAsync was called before SetAuthenticationState.'

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/aspnetcore#17442]
### Describe the bug

GetAuthenticationStateAsync throws an InvalidOperationException with the message:

    'GetAuthenticationStateAsync was called before SetAuthenticationState.'

I do not know if this is an actual bug or just a lack of documentation on its correct use.

ref:  https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.serverauthenticationstateprovider?view=aspnetcore-3.0

### To Reproduce

Inject a `ServerAuthenticationStateProvider` into a page. Then call `'GetAuthenticationStateAsync` in any of its async-events.

### Further technical details

    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@SteveSandersonMS can you please look into this, thanks!

**Comment by Grauenwolf** [comment]
I switched to using `[CascadingParameter] Task<AuthenticationState> AuthenticationState { get; set; }` instead. If that's actually the right way to do it then a simple note in the `GetAuthenticationStateAsync` docs would be sufficient.

**Comment by sven5** [comment]
You'll have to manually register the `AuthenticationStateProvider` in ConfigureServices:
`services.AddSingleton<AuthenticationStateProvider, ServerAuthenticationStateProvider>();`

This is a little weird as I expected that this service is already registered behind the scenes. :smirk:

**Comment by cbrit** [comment]
I'm getting the same error but I'm not injecting it into a Razor Component, just a class. Injecting this type works in one class but not another even though the implementation seems identital. I have added the service manually in Startup.cs (it's been that way a while), but when I made a new class and tried to inject it I started getting
`GetAuthenticationStateAsync was called before SetAuthenticationState`.

```
C:\Users\*****\source\repos\Project>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by rysep2** [comment]
I get the same error when I try to access the `AuthenticationStateProvider` from _any_ service class.

**Comment by Blackleones** [comment]
I have the same problem. 

I have a service called `CurrentUserService` with the goal of retrieving the current user. Each time anyone calls dbContext `SaveChangesAsync()` then I try to retrieve the current user through `CurrentUserService` but then I get the exception.

my code 

```csharp 

public interface ICurrentUserService
{
    Task<string> GetUserId();
}

public class CurrentUserService : ICurrentUserService
{
    private readonly AuthenticationStateProvider _authenticationStateProvider;
    public CurrentUserService(AuthenticationStateProvider authenticationStateProvider)
    {
        _authenticationStateProvider = authenticationStateProvider;
    }

    public async Task<string> GetUserId()
    {
        var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
        var user = authState.User;

        if (user.Identity.IsAuthenticated)
        {
            return user.Identity.Name;
        }
        else
        {
            return null;
        }
    }
}
```
my dbContext snapshot

```csharp 
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>, IApplicationDbContext
{
    private readonly ICurrentUserService _currentUserService;

    /* ... */

    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, ICurrentUserService currentUserService) : base(options)
    {
        _currentUserService = currentUserService;
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
    {
        var userId = await _currentUserService.GetUserId();

        foreach (var entry in ChangeTracker.Entries<AuditableEntity>())
        {
            switch (entry.State)
            {
                case EntityState.Added:
                    entry.Entity.CreatedBy = userId;
                    entry.Entity.Created = DateTimeOffset.Now;
                    break;

                case EntityState.Modified:
                    entry.Entity.LastModifiedBy = userId;
                    entry.Entity.LastModified = DateTimeOffset.Now;
                    break;
            }
        }

        return await base.SaveChangesAsync(cancellationToken);
    }

    /* ... */
}
```

I've noticed that when this service is called from a Blazor page then it works.

**Comment by nullpainter** [comment]
> You'll have to manually register the `AuthenticationStateProvider` in ConfigureServices:
> `services.AddSingleton<AuthenticationStateProvider, ServerAuthenticationStateProvider>();`
 
I presume this is intended to be `AddScoped`, @sven5? When I naively copied and pasted this registration, I ended up with one user's session receiving the other session's user details.

**Comment by sven5** [comment]
@nullpainter 
Oh yes you could be right about this.
However, it seems that this is no longer needed. I'm currently working on a new Blazor project using .NET Core 3.1.2 - I didn't explicitly register the `AuthenticationStateProvider` and it's working.

**Comment by Blackleones** [comment]
I've noticed that if I change `services.AddScoped<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<IdentityUser>>();` to `services.AddSingleton<AuthenticationStateProvider, RevalidatingIdentityAuthenticationStateProvider<IdentityUser>>();` then it works, but I don't think this is a good solution. Are there other solutions?

**Comment by SteveSandersonMS** [comment]
> Inject a ServerAuthenticationStateProvider into a page.

This is the problem. Don't do that, because you'll just receive an uninitialized instance.

You need to use the instance provided by the framework, which has been initialized. To get that, inject an `AuthenticationStateProvider` instead of `ServerAuthenticationStateProvider`.

For anyone else posting here, your issues may be different, since maybe you were not trying to inject `ServerAuthenticationStateProvider`. If you still have trouble, could you please post a separate issue with repro steps for your scenario? Thanks!

**Comment by eddiepaz** [comment]
> 
> 
> I have the same problem.
> 
> I have a service called `CurrentUserService` with the goal of retrieving the current user. Each time anyone calls dbContext `SaveChangesAsync()` then I try to retrieve the current user through `CurrentUserService` but then I get the exception.
> 

@Blackleones Did you ever get this to work? I'm doing basically the same thing and it's still not working.

**Comment by TimBurris** [comment]
Much like @eddiepaz , i'm still exeriencing the same issue.  i think for me it's because i'm using custom Middleware and utilizing IServiceProvider with CreateScope to created a Scoped instance of my User provider.  

the error can be demonstrated with the following (serviceProvider is an injected IServiceProvider):
```
using (var serviceScope = serviceProvider.CreateScope())
{
    var service = serviceScope.ServiceProvider.GetRequiredService<AuthenticationStateProvider>();
    var state= await service.GetAuthenticationStateAsync();
}
```
