### ISSUE TITLE
.net core 3.0 nginix with loadbalancing giving 404 error. where should i place ForwardedHeadersOptions

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#17458]
Where should i add ForwardedHeadersOptions in asp.net core 3.0 startup class

I have a case where i have nginix proxy having https is doing round robin on my web api's which are running on http

As per https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.0

I have added the forwarder as

```
public static IWebHostBuilder BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args).ConfigureKestrel(serverOptions => { }).UseIISIntegration().UseStartup<StartupShutdownHandler>();

        private static readonly ILog Logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private const string MyAllowSpecificOrigins = "_myAllowSpecificOrigins";


        public StartupShutdownHandler(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }


        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddControllers(options => options.RespectBrowserAcceptHeader = true).AddXmlSerializerFormatters().AddXmlDataContractSerializerFormatters();//for twilio            
            services.AddCors(options =>
                {
                    options.AddPolicy(MyAllowSpecificOrigins, builder => { builder.WithOrigins(lstofCors.ToArray()).AllowAnyMethod().AllowAnyHeader(); });
                });
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
        }

```

nginix was working fine till i have enabled https on nginix. When ever i try to access All but one controller i am getting 404 response. One controller where i have simply retruning text is not giving 404 error

```
[Produces("application/json")]
    [Route("[controller]/[action]")]
    public class HomeController : ControllerBase
    {

        [HttpGet]
        public string Index()
        {            
                return "Test";
        }}}     
    }   
```
I am running these api's on linux ubuntu servers. i have posted this on stackoverflow but looks like there is no response. so trying here as well

**Comment by Tratcher** [comment]
Did you also add the UseForwardedHeaders middleware in Startup.Configure?

That said, incorrectly configured forwarders should not cause a 404. Try turning your application logs up to Debug and see what routing said.

**Comment by KamranShahid** [comment]
here should i add it?

**Comment by Tratcher** [comment]
At the top, or right after error handling.

**Comment by KamranShahid** [comment]
Let me try with


```
    public class StartupShutdownHandler
    {

        public static IWebHostBuilder BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args).ConfigureKestrel(serverOptions => { }).UseIISIntegration()
            .UseStartup<StartupShutdownHandler>();

        private static readonly ILog Logger = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private const string MyAllowSpecificOrigins = "_myAllowSpecificOrigins";


        public StartupShutdownHandler(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddControllers(options => options.RespectBrowserAcceptHeader = true).AddXmlSerializerFormatters().AddXmlDataContractSerializerFormatters();//for twilio            
            services.AddCors(options =>
                {
                    options.AddPolicy(MyAllowSpecificOrigins, builder => { builder.WithOrigins(lstofCors.ToArray()).AllowAnyMethod().AllowAnyHeader(); });
                });
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
        }        

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime)
        {
            app.UseForwardedHeaders();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseCors(MyAllowSpecificOrigins);
            app.UseHttpsRedirection();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Home}/{action=Index}/{id?}");
            });
            //app.UseMvc(); //this is changed in 3.0
            applicationLifetime.ApplicationStarted.Register(StartedApplication);
            applicationLifetime.ApplicationStopping.Register(OnShutdown);
        }


        private void OnShutdown()
        {
            ............er.Fatal(ex, ex);
            }
        }

        private void StartedApplication()
        {
            ..............
        }
    }


```

**Comment by KamranShahid** [comment]
I have tried above order of adding it. then stand alone application which is hosted on https stop working. while it is working on another instance where i have http only

**Comment by Tratcher** [comment]
> then stand alone application which is hosted on https stop working.

Could you be more specific? Did this site work on https before? What doesn't work now? Adding UseForwardedHeaders should never make an application's behavior worse.

**Comment by KamranShahid** [comment]
Site work on https when deployed without proxy (nginix)
My devop team have done some changes in nginix after which it started to work.
I now just have to check whether above mentioned changes are still required or not.

**Comment by niklascp** [comment]
Can you explain the changes your team did in nginx? I am facing a similar 404 response on my Apache Reverse Proxy, with the .NET Core app running on IIS backend nodes.

**Comment by KamranShahid** [comment]
@niklascp sorry for late reply. following does work

upstream tag {
        server  1.2.3.4:8080;
}


server {

    listen 81;
    server_name myappdomain.com.net;
         location / {
                        proxy_pass      http://tag;
                        proxy_next_upstream error http_502;
                        proxy_redirect     off;
            server_tokens off;
            proxy_set_header   Host             $host;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            client_max_body_size       25m;
            client_body_buffer_size    256k;

            proxy_connect_timeout     180;
            proxy_send_timeout        180;
            proxy_read_timeout        180;
            proxy_buffer_size          8k;
            proxy_buffers              8 32k;
            proxy_busy_buffers_size    64k;
            proxy_temp_file_write_size 64k;
                        proxy_buffering on;

        access_log  /var/log/nginx/authstg_access_log ;
        error_log  /var/log/nginx/authstg_error_log notice;
        }
