### ISSUE TITLE
Q - Identity: Using a custom User type, UserStore, and non-string Id

### ISSUE THREAD

**Issue by bernatgy** [dotnet/aspnetcore#17464]
Hi,

This would be more of a general question about Identity, but I feel like the docs are confusing enough that it should be a real issue. I apologize for the long form. I have a tendency of not being able to stay concise, but I'm trying.

## For context (you can skip this)
I have a very simple setup. I want to integrate with an old firebird database that is handled by an old Dephi program. Data is recorded through the Delphi program, and I should build a really basic Webshop around it.
_(Later, the whole Delphi program will be converted to ASP.NET, so I want to have some coding done for that too.)_

For this I've chosen the ASP.NET Core 3 Web API / NHibernate / Angular stack.
Uphill battle considering 70% of the MS documentation assumes Entity Framework, and the use of templates / generated code, service registration / middleware configuration through undocumented shortcut extensions which configure another 10 service / middleware ...
_(Which I, personally despise, as I like to control and know everything my applications do.)_

Problem comes, when I want to integrate some very basic stuff by Identity.
I only have a "Users" table (user, pass, email) for now, which I can only modify for critical needs.

## Problem
I started [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.0) but by the end I realized this is completely useless for me, as it seems to assume an Entity Framework layer which I don't have and don't want.
I went onto [this one](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.0) and this just screams of confusion and contradictions.

My users table only has 3 columns, and the docs in [Customize the user class](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.0#customize-the-user-class) say I can have only an Id and a UserName field. So that would be a check.
The next few lines are already telling me, that because my users have an integer Id, I have to  inherit from IdentityUser to specify that...?
I don't want those extra properties... I don't want to specify TUserLogin, TUserRole, TUserToken and TUserClaim, as I don't need any of those functionalities, at least not yet.

I've read through it all, and I have more problems, but for now, this is by far the biggest one. I just need a simple user class with an integer Id.

For now, I wouldn't even use roles, or claims.
This is all the functionality I'll need for my UserStore;
```csharp
public class IntegraUserStore : IUserStore<IntegraUser>,
                                  IUserPasswordStore<IntegraUser>,
                                  IUserEmailStore<IntegraUser>,
                                  IQueryableUserStore<IntegraUserStore>
```
But if I go on like this, the interfaces just require me to have string Ids...

I would like some pointers in the right direction. My goal is an absolute minimal but completely transparent / explicit setup, with only critically needed DB modifications which I can eventually build up to a more "complete" Identity integration.

Thank you in advance!

**Comment by blowdart** [comment]
If you only have 3 columns why use identity at all? It has the assumption you want so much more.

Just do your check, and then use the [cookie middleware](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1) to write out a secure cookie.

**Comment by bernatgy** [comment]
In the end, that's what I did. I'm just using cookie authentication. This Issue on one hand solved itself, on the other, it did not. I still believe it to be a really bad sign that the framework, while providing a lot, is so rigid. It's built on the principles of flexibility, but still some of the most common needs are not supported. 

I wanted to use Identity, so that I could build up the implementation as we needed them. The project will grow. Isn't that why supported features can be provided in the form of implemented interfaces?

You can close the issue if you feel like it's not actionable. But I'd love to see some voices about this.
