### ISSUE TITLE
Blazor Integrated Windows Authentication Roles do not work with long polling

### ISSUE THREAD

**Issue by DouglasRiddle** [dotnet/aspnetcore#17467]
### Describe the bug
When using Windows Authentication with a server-side Blazor application, AuthorizeView Roles="WindowsActiveDirectoryGroup" appears to evaluate correctly when using websockets. If the connection uses long polling the active directory group membership initially evaluates correctly then the screen immediately updates and removes the AuthorizeView Roles section. Using AuthorizeView with no specified roles works as expected.

### To Reproduce

- Create a new Blazor Server App using Windows Authentication.
- Force LongPolling
- Create and load a new page that uses AuthorizeView Roles="WindowsAdGroupName"

```C#
// Force LongPolling in Startup.cs Configure
app.UseEndpoints(endpoints =>
{
    endpoints.MapBlazorHub(options =>
    {
        options.Transports = HttpTransportType.LongPolling;
    });
    endpoints.MapFallbackToPage("/_Host");
});
```
```C#
@page "/"

<AuthorizeView Roles="AdUserGroup">
    <p>Some content to display for only members of AdUserGroup.</p>
</AuthorizeView>
<AuthorizeView>
    <p>Some content to display for all authenticated users.</p>
</AuthorizeView>
```

### Further technical details
- ASP.NET Core 3.0.1
- VisualStudio 16.3.10

**Comment by javiercn** [comment]
@DouglasRiddle thanks for contacting us.

We believe we fixed this recently. Could you try and see if you can reproduce it with the latest preview?

**Comment by DouglasRiddle** [comment]
> @DouglasRiddle thanks for contacting us.
> 
> We believe we fixed this recently. Could you try and see if you can reproduce it with the latest preview?

3.1 preview? I am currently using 3.0.1 released 11/19/19.
https://devblogs.microsoft.com/dotnet/net-core-november-2019/

**Comment by javiercn** [comment]
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-3/

**Comment by DouglasRiddle** [comment]
Using 3.1.100 preview 3 SDK with Visual Studio 16.4.0 preview it is doing the same thing.

**Comment by DouglasRiddle** [comment]
For what it is worth, I tried it today with the production releases of ASP.NET Core 3.1.0 and VS 16.4.0 and it still has the same issue.

**Comment by DouglasRiddle** [comment]
I stumbled across a work-around by adding .RequireAuthorization() to both endpoints.

```C#
app.UseEndpoints(endpoints =>
            {
                endpoints.MapBlazorHub().RequireAuthorization();
                endpoints.MapFallbackToPage("/_Host").RequireAuthorization();
            });
```
Inspired by https://github.com/dotnet/aspnetcore/issues/4656#issuecomment-605012014

**Comment by rezalas** [comment]
I'm having the same problem when deployed to a server but changing the transport type between websockets and long polling both have the same result with an immediate refresh after load and the role disappearing. When testing in debug mode locally it doesn't have this problem and roles appear to work properly, though the refresh does occur. I've only tested with IIS on the server and IIS Express/VS 2019 community preview in debug.

**Comment by mkArtakMSFT** [comment]
Closing as Long Polling is now not supported: https://github.com/aspnet/Announcements/issues/470
