### ISSUE TITLE
Cannot use dotnet core 3 and unit test of aspnet project via Azure Dev Ops Visual Studio Build Task

### ISSUE THREAD

**Issue by houserrob** [dotnet/aspnetcore#17460]
#13109 # Describe the bug

We've recently tried to migrate our Service Fabric application which includes an ASPNet Core web front end and associated unit test to DotNetCore 3.  Locally there are no issues with build nor unit testing but when we run in Azure Dev Ops the build itself will consistently fail with unresolved references to the main ASPNet project.  This also reproduces with two projects built from the VS templates.   Using msbuild locally with the same parameters as those used in the ADO build also works so it's not clear what is different about the ADO environment.  

Create an ASPNet Core Project with a API.  By default this gives you a WeatherForecastController

``` C#

    //The controller (more or less straight from the template)
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController()
        {
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}


    // In the Unit Test Project - included a reference to WebAppCore and add a single test
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var wfc = new WeatherForecastController();
            wfc.ControllerContext = new Microsoft.AspNetCore.Mvc.ControllerContext()
            {

            };

            var items = wfc.Get();
        }
    }
```

Build these two projects with a standard VS Build Task in Azure Dev Ops set to build the solution.  Interestingly using a dotnet build task will handle this case as well so the issue seems isolated to the VS build task only.  

### Exceptions
_##[error]Prototypes\WebAppCore\WebAppCore.UnitTest\UnitTest1.cs(13,17): Error CS0012: The type 'ControllerBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
UnitTest1.cs(13,17): error CS0012: The type 'ControllerBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. [E:\a\_w\20\s\Prototypes\WebAppCore\WebAppCore.UnitTest\WebAppCore.UnitTest.csproj]
##[error]Prototypes\WebAppCore\WebAppCore.UnitTest\UnitTest1.cs(13,17): Error CS1061: 'WeatherForecastController' does not contain a definition for 'ControllerContext' and no accessible extension method 'ControllerContext' accepting a first argument of type 'WeatherForecastController' could be found (are you missing a using directive or an assembly reference?)
UnitTest1.cs(13,17): error CS1061: 'WeatherForecastController' does not contain a definition for 'ControllerContext' and no accessible extension method 'ControllerContext' accepting a first argument of type 'WeatherForecastController' could be found (are you missing a using directive or an assembly reference?) [E:\a\_w\20\s\Prototypes\WebAppCore\WebAppCore.UnitTest\WebAppCore.UnitTest.csproj]
##[error]Prototypes\WebAppCore\WebAppCore.UnitTest\UnitTest1.cs(13,51): Error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
UnitTest1.cs(13,51): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [E:\a\_w\20\s\Prototypes\WebAppCore\WebAppCore.UnitTest\WebAppCore.UnitTest.csproj]
##[error]Prototypes\WebAppCore\WebAppCore.UnitTest\UnitTest1.cs(18,29): Error CS0012: The type 'ControllerBase' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'._

### Further technical details
- ASP.NET Core version: 3.0.0

From one of our build agents
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.101\

Host (useful for support):
  Version: 3.0.1
  Commit:  32085cbc72

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Pilchie** [comment]
@JunTaoLuo does this look like the type forward issue?  Sounds like Azure DevOps doesn't have 3.0.1 targeting pack installed yet?

**Comment by Pilchie** [comment]
Also tagging @leecow.  @houserrob How are you getting the .NET Core SDK on the build machine? Are you using the "Use .NET Core" task?  If so, can you change the version to 3.0.101?

**Comment by leecow** [comment]
Ah, looking again at the output above, 3.0.101 and 3.0.1 are already installed. So the question is, why isn't the 3.0.1 targeting pack there?

**Comment by JunTaoLuo** [comment]
I'm not sure if this is the type forward issue since I recall that had a different symptom. But it does seem like there's an issue with ref packs not being resolved. @houserrob were you able to capture a binlog by any chance?

**Comment by houserrob** [comment]
@JunTaoLuo  thanks for taking a look!  I'm attaching the diagnostics logs from the build ( assuming that's what binlogs are :)) 
[logs_3583.zip](https://github.com/aspnet/AspNetCore/files/3899129/logs_3583.zip)

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo what is the pending action here?

**Comment by JunTaoLuo** [comment]
Oh I never got a chance to investigate this. There also doesn't seem to be any binlogs available to investigate so I'm not sure what further action we can take. Curious if this issue is still active given it has been half a year.

**Comment by JunTaoLuo** [comment]
I'm going to close this issue since:
1. We never got bin logs to debug
2. This affects dotnet core 3 which is out of support
3. We have not heard other users running into the same issue.
