### ISSUE TITLE
Server side Blazor components in MVC and Razor pages can fail silently during Component Initialisation

### ISSUE THREAD

**Issue by tomRedox** [dotnet/aspnetcore#17522]
When running a Blazor app in a project created with the server side Blazor (SSB) template, errors of the following nature will all cause the gold error bar to be shown when a component is being loaded:

 - When a dependency registration is missing for a service injected into that component
 - When an error occurs in the constructor for of a service injected into a component
 - When the component's `OnInitialized` method calls a method in a service that then throws an error

If I then add an MVC project to the solution, set it up [as per my notes here](https://stackoverflow.com/a/56245667/1879019), and then place those same components on MVC pages in that new MVC project, the error behaviour seems to be different:

 #### Missing dependency registrations and injected services constructor errors 
 Component fails completely silently:
 - No gold bar
 - No logging entries at all, not even at Debug level

 #### Errors from OnInitialized and onwards in the lifecycle
 Component fails visibly:
 - Gold bar shown
 - Logging entry at the 'Warn' level

I've also had times where a Debug level log entry has been added (as per case #17508) but no gold bar is shown, however I can't reproduce that in the repo below.  

It's very possible that I'm configuring the MVC project incorrectly in some way to use the components from the Blazor project, but in all other respects this seems to be working well in our app which is in final production testing with a client at the moment.

### To Reproduce
I've created a repo here: https://github.com/tomRedox/BlazorInMvcFailsSilently

It has two projects, a Blazor project and an MVC project.  

![image](https://user-images.githubusercontent.com/11335350/69977696-2b236500-1523-11ea-8d74-93d3b14c8768.png)

![image](https://user-images.githubusercontent.com/11335350/69977612-062ef200-1523-11ea-9d1f-02f8132a5e6d.png)

There are three services, components and MVC pages, one for each type of error.  

If you set the start up app to the Blazor project, you'll see gold error bars for all the different components, whereas if you set the startup project to MVC you'll only get the gold error bar on the Method Error page.

### Further technical details
- ASP.NET Core version:  
Core 3.1 Preview 3

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview3-014645\

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Professional 2019 Preview
Version 16.4.0 Preview 4.0

**Comment by ryanbrandenburg** [comment]
![repro](https://user-images.githubusercontent.com/14987221/70003872-6456d780-1519-11ea-9603-22ff1fb5a5b8.PNG) This did not reproduce for me. My procedure was:
1. Fresh box, latests VS preview, sdk 3.1 preview3.
1. Clone your repro
1. Launch Blazor version from VS, push all the buttons, get all the error bars.
1. Launch MVC app from VS, push all the buttons, get all the error bars.

I did notice that the default settings for VS pause on the throw-line, and the yellow bar doesn't show until after you hit continue (because there's no problem yet), could that have be confounding the situation?

**Comment by tomRedox** [comment]
Well that's very odd!  

I Just tried it again here, using both Chrome 78.0.3904.108 (Official Build) (64-bit) both regular and incognito and on Microsoft Edge 44.17763.1.0.  

Like you I get the code breaking on the error, but unlike you when I hit F5 it continues and I get no error bar.  I also tried running it with Shift+F5 and again no error bar:

![DucISW40fb](https://user-images.githubusercontent.com/11335350/70005206-a1928800-1560-11ea-8718-6db127e711ee.gif)

The site is running on the IIS Express instance that VS runs by default.

What on earth could be causing that difference?

**Comment by ryanbrandenburg** [comment]
I bet that I tried it without IIS Express, if you switch to the "raw" version do you see the same behavior as me?

**Comment by tomRedox** [comment]
@ryanbrandenburg well spotted, yes that's it.  If I change to MvcUI:

![image](https://user-images.githubusercontent.com/11335350/70005658-4792c200-1562-11ea-9c16-044ae81bf948.png)

then I see the same behaviour

**Comment by ryanbrandenburg** [comment]
It would seem so. I'll look into this from our end, but this may end up being a problem that the IISExpress folks will have to look at.

**Comment by tomRedox** [comment]
@ryanbrandenburg that's great, many thanks.

**Comment by tomRedox** [comment]
@ryanbrandenburg have you got everything you need for me on this one?  If so should the 'Needs: Author Feedback' tag be removed?

**Comment by ryanbrandenburg** [comment]
@tomRedox we have automation that's supposed to do this when the Author replies so that it's faster and more reliable, but apparently that's not working ATM.

**Comment by mkArtakMSFT** [comment]
This should already be fixed. Please use the upcoming 3.2-preview2 release to validate.
