### ISSUE TITLE
VS Blazor WebAssembly debugging can't connect in HTTPS

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#17547]
As of preview 4 it's possible to attach the debugger via CDP to a Blazor WebAssembly app, but only if you're using an `http` URL. If you're on `https`, then VS hangs for about 30 seconds before reporting "An operation is not legal in the current state".

![image](https://user-images.githubusercontent.com/1101362/70062737-81a1a980-15de-11ea-931c-439d61743c53.png)

At first I thought this would be a simple fix. This line looks buggy: https://github.com/aspnet/AspNetCore/blob/blazor-wasm/src/Components/Blazor/Server/src/MonoDebugProxy/BlazorMonoDebugProxyAppBuilderExtensions.cs#L114

It's hardcoded to use `ws://`, but really it should pick between `ws://` and `wss://` depending on `request.IsHttps`.

However, I tried that fix, and it doesn't work, because VS is hanging before our `BlazorMonoDebugProxyAppBuilderExtensions` handler code even runs. This may be an issue on the VS side. We need to be sure that it allows HTTPS URLs, and equally importantly, that it's not enforcing cert validation since people are typically using self-signed dev certs.

**Comment by javiercn** [comment]
Agree.

HTTPS is important during development as it can be the source of many production issues when not used during development.

**Comment by ajaybhargavb** [comment]
I did some more investigation. I found that Visual Studio (and also VSCode with Chrome debugger extension) makes a `http` request to the /json endpoint regardless of whether we try to connect to `http://localhost:5000` or `https://localhost:5001`.

So, entering `https://localhost:5001` in the Connection target, actually results in a call to http://localhost:5001/json which is not valid.
![image](https://user-images.githubusercontent.com/1579269/72307375-ec5af180-362e-11ea-9f02-495cf595b037.png)

I also confirmed this by entering `https://localhost:5000` in the Connection target, but the incoming request is `http://localhost:5000/json`.

Moreover, I noticed while a browser tab is open with `https://localhost:5001` that entering `https://localhost:5000` in the connection target, shows the following,
![image](https://user-images.githubusercontent.com/1579269/72307566-976bab00-362f-11ea-8625-426289a88a13.png)
Attaching to that works and I am able to debug my https tab.

@SteveSandersonMS @pranavkm @mkArtakMSFT

**Comment by javiercn** [comment]
That's all good and well,

but we should work with the VS folks on being able to attach on the HTTPS address. That's what people will put in that box (unless there's something automatic happening that I missed).


Best regards,

Javier Calvarro Nelson

________________________________

**Comment by ajaybhargavb** [comment]
From https://github.com/dotnet/aspnetcore/issues/17444#issuecomment-588238152, the next version of the debugger is no longer going use the /json endpoint. We don't want to do this work anymore.
