### ISSUE TITLE
Blazor router generates 404 errors for some URIs it can route internally.

### ISSUE THREAD

**Issue by NeilMacMullen** [dotnet/aspnetcore#17548]
### Describe the bug
When creating internal links to pages with parameters it is possible to generate URIs that are correctly parsed when navigating directly to page but which result in a 404 error when navigating from an external source.

### To Reproduce

See [this stackoverflow question ](https://stackoverflow.com/questions/59140306/what-is-the-recomended-way-to-pass-blazor-parameters-that-include-special-charac) for background.

In summary:
-  Create  target page that accepts a string parameter....  
```
@page "/LocationDetailPopup/{placename}"
@code{
[Parameter]
public string placename { get; set; }
}
```
- Create a source page that generates a link to it....
`
<a href="/LocationDetailPopup/@Uri.EscapeDataString(place)"> more info...</a>`

If 'place' is set to a string such as "38.7650,-90.3540" the generated URI is of the form 

> https://..mydomain.../locationdetailpopup/38.7650%2C-90.3540

This is parsed correctly when navigating directly from the application (i.e. the user clicks on the link the source page) but generates a 404 error if the user copies the URI from the browser address bar and tries to use it as a bookmark for a later session.  The problem appears to be caused by the periods or hyphen since if a more conventional string is used as a parameter, the URI can be used as a bookmark without generating a 404 error.  However, manually escaping the periods and hyphen with % codes still generates a 404 error when the URI is used as a bookmark.

### Further technical details
PS D:\work\Backend\Csharp\Applications\Cli\Info\bin\Debug> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview3-014645
 Commit:    b32d27f4b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview3-014645\

Host (useful for support):
  Version: 3.1.0-preview3.19553.2
  Commit:  13f35c3d86

.NET Core SDKs installed:
  2.1.507 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS D:\work\Backend\Csharp\Applications\Cli\Info\bin\Debug>

**Comment by NeilMacMullen** [comment]
I notice this has the **question** tag added.  I should be clear that while the original SO post was in the form of a question, the (apparent) bug I'm reporting is that the router treats URIs from internal and external sources differently.  The fact that _manually_ escaping the URI still doesn't resolve the issue implies that there is some layer that is unescaping too early.

**Comment by javiercn** [comment]
@NeilMacMullen We don't believe that this is an issue, but that the server is not properly configured. When using MapFallbackToClientSideBlazor you can specify the route template to avoid this situation.

We need to fix this for the dev-server case as that's not configurable, but that's it.

**Comment by NeilMacMullen** [comment]
Thanks that's interesting. (Yes, this is a server-hosted Blazor project.)  Could you point  me to a reference on how to to use this and I'll confirm it does resolve the issue?  Google has a few hits for *MapFallbackToClientSideBlazor * but they all lead to articles about setting the startup page which does seem to be what you're talking about here.
