### ISSUE TITLE
custom validation attribute does show the incorrect error message in Razorpages PageRemote validation aspnet core 3

### ISSUE THREAD

**Issue by djary** [dotnet/aspnetcore#17541]
I created one custom validation attribute and work fine:

        public sealed class DuplicateUrlCheckerAttribute : ValidationAttribute
     {
        public string GetErrorMessage() => $"آدرس Url پیش تر توسط شما یا دیگری ثبت شده است";

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {

            var service = (IOrderValidationService)validationContext.GetService(typeof(IOrderValidationService));

            if (service.DuplicateUrl(value.ToString()))
            {
                return new ValidationResult(GetErrorMessage());
            }

            return ValidationResult.Success;
        }

    }

and I used in a razor page as remote validation (page remote):

       public class IndexModel : PageModel
       {
        readonly IViewerOrderService _viewerOrderService;

        public IndexModel(IViewerOrderService viewerOrderService)
        {
            _viewerOrderService = viewerOrderService;
        }

        [PageRemote(
         AdditionalFields = "__RequestVerificationToken",
         HttpMethod = "post",
         PageHandler = "CheckValidations"
        )]
        [BindProperty]
        public Order Order { get; set; }

        [Required]
        [Url]
        [RegularExpression(@"^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$", ErrorMessage = "آدرس معتبر از سایت یوتیوب وارد کنید.")]
        [DuplicateUrlChecker]
        [PageRemote(
         AdditionalFields = "__RequestVerificationToken",
         HttpMethod = "post",
         PageHandler = "CheckValidations"
        )]
        [BindProperty]
        public string DuplicateUrl { get; set; }

        public void OnGet()
        {

        }
        public async Task<IActionResult> OnPostAsync(CancellationToken cancelationToken)
        {
            if (!ModelState.IsValid)
                return Page();

            Order.LinkUrl = DuplicateUrl;

            if (await _viewerOrderService.AddOrder(Order, cancelationToken))
            {
                TempData.Set("newOrder", Order);
                return RedirectToPage("ThankYou");
            }

            return Page();

        }

        public JsonResult OnPostCheckValidations()
        {
            if (!ModelState.IsValid)
                return new JsonResult(false);

            return new JsonResult(true);
        }
    }

still, work fine but the problem is that, don't show correctly ErrorMessage. in the view instead show this error

> آدرس Url پیش تر توسط شما یا دیگری ثبت شده است

showing

> 'DuplicateUrl' is invalid.
even I used `[DuplicateUrlChecker(ErrorMessage = "آدرس Url پیش تر توسط شما یا دیگری ثبت شده است") ` 

but still, show

> DuplicateUrl' is invalid.

And View is:

     @page "{handler?}"
     @model MakeMoney.Web.Pages.IndexModel
     @using MakeMoney.Domain.Models.LinkOrder;
     @{
       ViewData["Title"] = "دانلود ویدیو ";
     }

      <form id="wrapped" asp-page="/Index" method="POST">
       <input id="website" name="website" type="text" value="">
        
       <div id="middle-wizard">
        
      
     ...
    
  
      <div class="submit step" id="end">
        <div class="question_title">
          <h3>فرم مشخصات</h3>
          <p>لطفا فیلد ها را با دقت پر کنید</p>
        </div>
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="box_general">
              <div class="form-group">
                <input type="email" asp-for="Order.Email" class="required form-control" title="لطفا ایمیل خود را وارد کنید" placeholder="ایمیل">
                <span class="text-danger" asp-validation-for="Order.Email"></span>
              </div>
              <div class="checkbox_questions">
                <input asp-for="Order.Inform" type="checkbox" class="icheck">
                <label>هر زمان روی کانال قرار گرفت مرا باخبرساز</label>
                <span class="text-danger" asp-validation-for="Order.Inform"></span>

              </div>
              <div class="form-group">
                <input type="text" asp-for="DuplicateUrl" class="required form-control" pattern="^(http\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$" title="آدرس Url را وارد کنید" placeholder="لینک موردنظر" required>
                <span class="text-danger" asp-validation-for="DuplicateUrl"></span>

              </div>
              <div class="form-group add_bottom_30">
                <label>زیرنویس:</label>
                <div class="styled-select">
                  <select asp-for="Order.SubtitleType" class="required" asp-items="@Html.GetEnumSelectList<SubtitleType>()">
                  </select>
                  <span class="text-danger" asp-validation-for="Order.SubtitleType"></span>

                </div>
              </div>
              <div class="checkbox_questions">
                <input name="terms" type="checkbox" class="icheck required" value="yes" title="اجباری">
                <label> قبول <a href="#" data-toggle="modal" data-target="#terms-txt">شرایط و ضوابط</a></label>
              </div>
            </div>
            
          </div>
        </div>
        
      </div>
      
    </div>
  </div>
     
      <div id="bottom-wizard">
       <button type="button" name="forward" class="forward">بعدی</button>
        <button type="submit" name="process" class="submit">ارسال</button>
       <button type="button" name="backward" class="backward">قبلی</button>
     </div>
     
</form>

     @section Scripts {
       <partial name="_ValidationScriptsPartial" />
     }

certainly, add `ErrorMessage` to PageRemote.! without ErrorMessage in PageRemote, Default message not working!

        [PageRemote(
         ErrorMessage = "آدرس Url پیش تر توسط شما یا دیگری ثبت شده است",
         AdditionalFields = "__RequestVerificationToken",
         HttpMethod = "post",
         PageHandler = "CheckValidations"
        )]

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
