### ISSUE TITLE
Project templates need to be updated for 5.0

### ISSUE THREAD

**Issue by phenning** [dotnet/aspnetcore#17553]
The template identities defined in template.json need to be updated for all the templates in master which are now targetting netcoreapp5.0. 

Since they currently have the same identities as the templates which target 3.1, when these tempaltes are installed, they hide the 3.1 templates, and prevent them from being created either via dotnet new, or from within Visual Studio.

Additionally, precedence also needs to be updated.

This is essentially the same issue as described in #14486

**Comment by javiercn** [comment]
Thanks @phenning.

We'll triage this and get it updated. @mkArtakMSFT this should be simple to perform, we should probably included in preview1 of 5.0

**Comment by javiercn** [comment]
@ajaybhargavb  Can you take care of making this change?

**Comment by phenning** [comment]
@mkArtakMSFT Can you please prioritize this for Preview 1, we are blocked in allowing 5.0 templates to be used in Visual Studio until this is fixed due the 5.0 templates effectively hiding the 3.1 templates since they share the same ID.
