### ISSUE TITLE
CSRF token is linked to user identities

### ISSUE THREAD

**Issue by clement911** [dotnet/aspnetcore#17576]
Continuing the discussion starting on #17478 ...

We have recently implemented CSRF protection with `services.AddAntiforgery` and have hit some issues.

Specifically, we understand that the current version of the Antiforgery issues a CSRF cookie which contains a sort of hash of the identity of the user.

This is problematic for our SPA application.
Currently, when serving the SPA we generate a token with IAntiforgery.GetAndStoreTokens and then the SPA passes the token on every requests (except GETs).

However, any user may authenticate with multiple providers and sign in/out at anytime with any of the providers. Because of the link between the CSRF cookie and the identities, this means the token originally served to the SPA becomes instantly invalidated.

How can we remove the tie between the CSRF cookie and the identities?

**Comment by clement911** [comment]
https://github.com/aspnet/AspNetCore/blob/4a5f2d16bbeab0e16f3786d5058872c013c686f9/src/Antiforgery/src/Internal/DefaultClaimUidExtractor.cs#L40-L121

**Comment by clement911** [comment]
There is quite a bit of copy and paste but it seems that the code will first look for a claim `'sub'` or `ClaimTypes.NameIdentifier` or `ClaimTypes.Upn` and use that instead of all claims if it finds one.

I don't get why but we could potentially generated an identity with such a claim, which would remain constant regardless of other identities / claims.

But how are the identities ordered? It seems that the code simply iterates through them from the User principal. Are these ordered in any particular order?

**Comment by blowdart** [comment]
If you're in a SPA app then why not authenticate with JWT which doesn't have CSRF concerns so an anti-forgery token isn't needed?

**Comment by clement911** [comment]
It's a separate question. There are pros and cons with both cookies and jwt.
At least for now our architecture relies on cookies.

**Comment by blowdart** [comment]
Our CSRF implementation is coded to use the user identity when it's available to protect against shared domain attacks. It's a conscious choice on our part, and not one we plan to change.

**Comment by clement911** [comment]
Is there any chance to make this configurable in a future release?
So that we can disable the use of the user identity explicitly?

**Comment by blowdart** [comment]
Every time it's come up we've said no because people can move to JWT

**Comment by brockallen** [comment]
A similar issue comes up where you render a login page in 1 tab and another form in another tab. Since the user is not authenticated, the anti-forgery tokens track that. Then in the first tab you login, when then establishes authentication and in essence invalidates the token in the 2nd tab. Of course if the user switches to the 2nd tab and then submits (now authenticated) it fails. It's been like this since old-skool MVC.

**Comment by clement911** [comment]
Right, we'll have to dig into JWT further at some point and see what it takes to implement it.

I'd still love to understand what's happening in the DefaultClaimUidExtractor.cs

Why does the code will first look for a claim 'sub' or ClaimTypes.NameIdentifier or ClaimTypes.Upn?
Clearly, this relies on identities being ordered. How are the identities ordered?

**Comment by clement911** [comment]
@blowdart I did some more reading one JWT and my understanding is that it is considering a poor practice to store JWT in local storage because it is vulnerable to XSS attacks. The recommendations I could find suggest to store the JWT in an HTTP only secure cookie.
While this prevents XSS, this means we must still protect against CSRF even if we use JWT.

**Comment by blowdart** [comment]
Well if you put it in a cookie then our JWT middleware wouldn't see it anyway, so you wouldn't get any authentication at all. Yes, local storage can be vulnerable to an XSS attack, but then as asp.net core encodes everything by default you'd have to be rendering stuff yourself to fall pray to it (or your SPA app is miscoded in some way). So our opinion is, as you're protected against XSS by default, and as JWTs in cookies won't work, and as the standard way to transmit JWT is via an auth header, not a cookie, the opinion to put it in a cookie is not exactly a useful one.

Once again we're not changing how CSRF works.

**Comment by clement911** [comment]
Got it, I didn't know the JWT middleware couldn't work with cookies.

I understand that asp.net core will encode everything that is generated sever side but I think SPAs are very common these days. Sure, if our SPA is coded perfectly then we don't need to protect against XSS, but the point is that we want to be protected by default.

I understand there is a standard JWT header, but what I don't understand is where it should be stored (assuming the client is a browser here). Local storage is not secure.

Unless the asp.net core JWT authnentication is intended for single use token? i.e the user must authenticate every time?

> Once again we're not changing how CSRF works.

Yes, you've made that clear. I'm trying to understand our options.
Sorry if these questions seem obvious. I'm pretty new to JWT as I always used cookies in the past

**Comment by clement911** [comment]
Looks like we were able to mitigate this problem.

Since the `DefaultClaimUidExtractor` looks for a 'sub' claim and treats these differently, we are generating a unique 'sub' claim, and set its to be the same value on all identities.
This way, even if the user signs in/out of various identities, there is always a common 'sub' value across all of them.

When signing with any identity: retrieve the sub value from any other identity, or generate a sub value if needed.

`var subjectClaim = ctx.User.Claims.FirstOrDefault(c => c.Type == "sub") ?? new Claim("sub", Guid.NewGuid().ToString());`

Then, simply add this claim to all the normal claims when generating the `ClaimsIdentity`.

This seems to be working fine. Does that seem reasonable?

**Comment by blowdart** [comment]
Ah, you answered once I went on vacation.

Umm yea, I guess that'd work. Just make sure you're not on shared subdomains like azurewebsites.net and of course you don't use the sub value to do any actual work with.

**Comment by clement911** [comment]
Got it, thanks for the tip.
I'll close this issue.
