### ISSUE TITLE
VS2019 Publish UI does not allow update from netcoreapp3.0 to 3.1

### ISSUE THREAD

**Issue by JoelW187** [dotnet/aspnetcore#17583]
After upgrading to Visual Studio 2019 16.4.0 I updated a Blazor WebAssembly solution so all the projects were upgraded to .NET Core 3.1 and .NET Standard 2.1. The solution compiled and ran correctly under the debugger. But when I tried to publish using an existing publish profile (created under .NET Core 3.0) I got the dreaded:

> Error NETSDK1005: Assets file '...\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.0'. Ensure that restore has run and that you have included 'netcoreapp3.0' in the TargetFrameworks for your project.

Editing the publish profile through the VS2019 UI listed the Target Framework as "netcoreapp3.1" and there were no other options in the dropdown. But when I inspected the publish profile .xml it shows the TargetFramework element as "netcoreapp3.0".

The fix is to either delete the publish profile and recreate it, or manually edit the publish profile .xml and change TargetFramework to "netcoreapp3.1". I verified that both of these workarounds work.

![image](https://user-images.githubusercontent.com/15229643/70152164-b82d0200-167a-11ea-9cb2-7194e7db40f5.png)

**Comment by javiercn** [comment]
@JoelW187 thanks for contacting us.

We believe this issue is external and you'll get a faster and better answer by filing the issue through the report a problem dialog in Visual Studio. For more details see https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

@vijayrkn Can you take a look at this?

**Comment by Pilchie** [comment]
Tagging @vijayrkn again.

**Comment by vijayrkn** [comment]
There is already a developer community ticket tracking this - https://developercommunity.visualstudio.com/content/problem/880185/visual-studio-wont-allow-changing-the-targetframew.html

You can track the progress of this here.

**Comment by Pilchie** [comment]
Closing this in favor of the developer community item.
