### ISSUE TITLE
CORS With Windows Authentication on IIS 10 not working

### ISSUE THREAD

**Issue by mrunks** [dotnet/aspnetcore#17602]
### Describe the bug
I have an ASP.NET Core 3.0 Application that is configured to use CORS per Microsoft's  documentation and I receive 401 errors when trying to send requests from Angular client Applications or .NET MVC controllers that are hosted in IIS with windows credentials.

The client applications that use both the Angular  httpclient as well as C#.NET MCV Controllers to make cross domain requests to another application hosted in IIS 10 with ASP.NET Core 3.0.  

I specify the content type application/json for PUTS, DELETES and POSTS and receive 401 errors.  If I turn on Anonymous Authentication then I no longer have the problem and the requests will work. 

The CORS only fails when IIS only has Windows Authentication . If I use JWT with CORS then on the same application hosted by IIS as well, then there is no problem.

Furthermore, I have multiple ASP.NET 4.x applications that use code in Application_Begin request to dynamically set the Origin and I have middleware in both a 2.1 application and .NET CORE 3.0 application to perform the equivalent function and that too does not work with CORS and Windows Authentication.  But the same code works WITH JWT.  So weather I use CORS and set a specific origin or use middle ware to capture a dynamic origin the requests fail unless Anonymous authentication is enabled.

I know .NET CORE 2.2 CORS no longer allowed one to configure AllowAnyOrigin and AllowCredentials so I am not sure if this is part of the problem.

Is there a way to dynamically capture the origin with Windows Credentials that works for Windows Authentication in ASP.NET CORE 3.0 as works in both 4.x applications and 2.1 .NET CORE.

For example in ASP.NET 4.x I have the following code in Application_BeginRequest

protected void Application_BeginRequest()
    {
      var currentResponse = HttpContext.Current.Response;

      var currentRequestOrigin = HttpContext.Current.Request.Headers["Origin"];
      if (currentRequestOrigin != null)
      {
        currentResponse.AppendHeader("Access-Control-Allow-Origin", currentRequestOrigin);
      }

      if (Request.Headers.AllKeys.Contains("Origin") && Request.HttpMethod == "OPTIONS")
      {
        HttpContext.Current.Response.End();
      }
    }

In ASP.NET CORE I attempted to use Middleware that works for 2.1 and JWT but fails with .NEt CORE 3.0:

private async Task BeginInvoke(HttpContext context)
    {

      var origin = context.Request.Headers["Origin"];

      if (origin.Any() && origin.FirstOrDefault().Trim() != "")
      {
        context.Response.Headers.Add("Access-Control-Allow-Origin", new[] { origin.FirstOrDefault().ToLower() });
      }

      context.Response.Headers.Add("Access-Control-Allow-Headers", new[] { "Accept, Authorization, Origin, X-Requested-With, Content-Type" });
      context.Response.Headers.Add("Access-Control-Allow-Methods", new[] { "GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH" });
      context.Response.Headers.Add("Access-Control-Allow-Credentials", new[] { "true" });
      
      if (context.Request.Method == "OPTIONS")
      {
        context.Response.StatusCode = 200;
        await context.Response.WriteAsync("OK");
      }
      else
      {
        await this._next.Invoke(context);
      }
    }

At the end of the day I just want to provide the equivalent behavior of dynamically capturing origins as I currently have in multiple 4.x applications or earlier .NET Core applications with JWT but these need to work with Windows Credentials as well.  

I followed the documentation step by step and keep receiving the 401 errors.

At first I thought this was a chrome error but if it was then the 4.x applications would not work and they work perfectly as intended with only having Windows Authentication enabled.

**Comment by blowdart** [comment]
https://github.com/aspnet/AspNetCore/issues/11764

You can't use the asp.net CORS middleware with Windows Auth on IIS, you must use the IIS CORS functionality

**Comment by mrunks** [comment]
I am not sure what you mean by IIS CORS can you explain ?

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/AspNetCore/issues/11764#issuecomment-507428068

**Comment by mkArtakMSFT** [comment]
Let's get this documented so we can respond to these type of comments with link to docs instead.

**Comment by mrunks** [comment]
> [#11764 (comment)](https://github.com/aspnet/AspNetCore/issues/11764#issuecomment-507428068)

I went ahead and installed the CORS module and then when trying to follow the example to configure from the following link I now get 500 errors.

It seems the <cors> child element is causing the problem when I try to create it under system.webserver as described in the example below.

<configuration>
    <system.webServer>
        <cors enabled="true" failUnlistedOrigins="true">

https://docs.microsoft.com/en-us/iis/extensions/cors-module/cors-module-configuration-reference

And just for clarification, I should be using this going forward instead of using app.UseCors() or any custom middleware I had written in prior versions ?

**Comment by mrunks** [comment]
I have been looking work a working example of the IIS Cors module with .NET CORE and have been unable to find one.  Is the module compatible with ASP.NET CORE 3.0 hosted in IIS or is it only for 4.x versions ?

**Comment by pranavkm** [comment]
@mrunks you should only need this if you're using IIS with Windows Auth and do not have allow anonymous. IIS will interecept these requests before it gets to ASP.NET Core. Consequently the CORS headers need to be set via the module.

What's the error you see?
