### ISSUE TITLE
New Descripton Parameter for Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute Class

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#17608]
### Is your feature request related to a problem? Please describe.
Right now documenting API's can be more of a struggle than it needs to be.  The OpenAPi documentation tool chain often relies on getting a description from XML comments result code.  Ideally result code comments wouldn't be needed in most cases.

### Describe the solution you'd like
Would it be possible to add an **optional** Description parameter to ProducesResponseTypeAttribute.  The purpose of this description would be to override the default HTTP response description.  This would be a nice benefit when documenting API controllers..

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Such a change will actually span across multiple repos including external ones we don't own. Besides, this is not a priority for us at the moment. So if you would like to send PRs for the end-to-end scenario to light up, we would happily consider it. For now, we're moving this to backlog for future consideration.

**Comment by willwolfram18** [comment]
I'd be interested in looking at this. I've run into this issue myself and wouldn't mind taking a crack at adding this capability!

I'm getting familiar with the contribution guidelines and building from source documentation, I'll check back in after getting that going.

**Comment by abc516** [comment]
Hi @mkArtakMSFT @pranavkm, is this still a valid open issue? I'm open to taking it on.

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/55656.

**Comment by sander1095** [comment]
Thanks @captainsafia ! I wont be able to work on this the next month because of holiday, but my offer to work on this still stands if i can get some help with the api changes that need to be made :)

**Comment by captainsafia** [comment]
> Thanks @captainsafia ! I wont be able to work on this the next month because of holiday, but my offer to work on this still stands if i can get some help with the api changes that need to be made :)

Yep -- I need to make some updates to the proposal so that we apply the changes to the minimal API-based metadata as well. If all goes well, I'll bring it up during API review on Thursday. However, at this point, it's likely to go into .NET 10 and not .NET 9 :/
