### ISSUE TITLE
Could not load System.Runtime on project using source build

### ISSUE THREAD

**Issue by joshpearce** [dotnet/aspnetcore#17629]
I followed all the steps [here](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md) to build from source. I was able to build successfully using this command:
`./build.sh --pack`

Then, in a new directory outside the source repo, I ran,
`dotnet new react`

I added a NuGet.Config file as in the docs, pointing the packages I built.

I updated the package reference to be,
`<PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="5.0.0-dev" />`

Restore and build work fine.

But when I run, I get the following error,

```
(AspNetCore) joshuapearce@KNAT:~/Code/cp3$ dotnet run
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
This is on OSX.

**Comment by pranavkm** [comment]
Likely a dup of https://github.com/dotnet/sdk/issues/3929.

**Comment by joshpearce** [comment]
Interesting to me though, is that if I go into `src/Identity/samples/IdentitySample.Mvc` and run `dotnet run` it works. 

Would I be able to follow one of the developer docs about adding a new project (in aspnetcore), to piggyback on whatever is making this sample work?

**Comment by OdeToCode** [comment]
I've been having the same issue. 

The [Use the result of your build](https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#use-the-result-of-your-build) section of the Wiki seems out of date as it still refers to 3;0.0-dev. Also, there are no installers built by default, so it is a bit of a mystery how to setup a preview SDK to work with the shared runtime built from source.

**Comment by pranavkm** [comment]
Do you still see this? We have newer builds of the SDK with bug fixes. In addition, I tried building and using the project template on Windows which worked fine for me.
