### ISSUE TITLE
Visual Studio Azure WebJob templates for full .NET seems outdated.

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#17634]
Just tried creating an Azure WebJob using the latest version of Visual Studio 2019 and the built-in Azure WebJob template for the `**full .NET**` (not .NET Core). As far as I can see, the templates appear to still reflect the old way for doing things.

Are there any plans for updating those templates? Alternatively, can someone point me to a place where I can get detailed instruction on how to create an Azure WebJob for the `**full .NET**` (not .NET Core)? Fallowing the instructions layout on the [Get started with the Azure WebJobs SDK for event-driven background processing](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started) document does not seem to work when using full .NET.

**Comment by javiercn** [comment]
@rxelizondo Thanks for contacting us.

@bradygaster this is an external thing I believe. Can you redirect/loop in the right folks?

**Comment by bradygaster** [comment]
adding @fabiocav here on the service side and @vijayrkn/@timheuer for the tooling side of things.

**Comment by Pilchie** [comment]
Actually tagging @vijayrkn - where should this go?

**Comment by vijayrkn** [comment]
The templates for Azure WebJobs is on the VS side but the content is owned by [@fabiocav](https://github.com/fabiocav)/[@paulbatum](https://github.com/paulbatum). Where should this issue be routed? Are there plans to update the full framework WebJobs templates or is Azure Functions the recommended mechanism for this task?

**Comment by fabiocav** [comment]
Apologies for the delayed message. I've opened https://github.com/Azure/azure-webjobs-sdk/issues/2431 so we can keep track of this work in the SDK repo. This will allow us to triage and prioritize the work there.

@jeffhollan , FYI

**Comment by Pilchie** [comment]
Thanks - closing this one.
