### ISSUE TITLE
Integrate ASP.NET core with custom\Inhouse keyvault application

### ISSUE THREAD

**Issue by amshekar** [dotnet/aspnetcore#17647]
### How to integrate this custom in-house key-vault in ASP.NET core configurations.  

There are many recommended samples to integrate with know vaults like Azure or aws.
We have one in-house hosted key-vault application which will store secret can access by rest call by sending secret id. 

By default the appsettings json have keys without values , Just added an update configuration/appsettings dictionary with the new values 
It is working fine but some cases application giving empty secret and throwing some errors 

```c#
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<ICustomVault, CustomVault>();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env,ICustomVault customVault)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        //By this time we have appsecrets /configuration is loaded in app 
        //Call the update configuration method update/override empty key values of name and password with the below call
        customVault.UpdateConfiguration();        


        app.UseAuthorization();

    }
}
Public Class CustomVault
{
    UpdateConfiguration()
    {
        //Step1: Calling the inhouse kayvault api getting the secret 
        //Step2: updating the configuration dictionary

    }
}
```

```json
appsettings.json
{
"username":" ",
"password":""
}
```

### Describe the solution you'd like
As per my initial analysis on this implementation , By default the appsettings have the empty keys on app startup, before the updation on the configuration done if any request try to read the configuration application returning empty values then updating the configuration. So that request is sending empty secret so facing some failures. Do we have any recomended approach to handle this  

### Additional context
ASP.NET Core custom vault integration

**Comment by Pilchie** [comment]
@HaoK any thoughts here?

**Comment by HaoK** [comment]
I'm not sure I completely understand the scenario, but can you just implement a custom `IConfigurationProvider` using your `CustomVault`, this should prevent empty values as your vault would always have a chance to do lookup against the inhouse keyvault apis.

**Comment by Pilchie** [comment]
Closing this as stale - please let us know if your issue isn't addressed.
