### ISSUE TITLE
Unit-testing rendering views with Razor Engine not working in dotnet core 3.x

### ISSUE THREAD

**Issue by toralux** [dotnet/aspnetcore#17655]
### Describe the bug
Unit-testing rendering of Razor Views using Microsoft.AspNetCore.Mvc.Testing worked in dotnet core 2.2, but in 3.1 (and 3.0) the Razor Engine does not locate my views any more specified like this:

```csharp
builder.UseSolutionRelativeContentRoot("Rendering");
```
### To Reproduce
I have made a small example that reproduces the issue in the dotnet core 3.1 solution (while in the dotnet core 2.2 solution the view is found).

https://github.com/toralux/RazorEngineRendering

* dotnetcore3.1
* dotnetcore2.2

The only difference between the solutions is the framework (TargetFramework is netcoreapp3.1 instead of netcoreapp2.2) and version of nuget packages (Microsoft.AspNetCore.Mvc and Microsoft.AspNetCore.Mvc.Testing) (version 3.1.0 instead of 2.2.0).

The part of the example that don't find the view:

```csharp
var viewEngineResult = _viewEngine.FindView(actionContext, name, false);

if (!viewEngineResult.Success) // <-- here 2.2 has found the view and 3.1 has not
{
    throw new InvalidOperationException(string.Format("Couldn't find view '{0}'", name));
}
```

### Further technical details
- ASP.NET Core version: 3.1 (and 3.0)

**Comment by toralux** [comment]
Any news on this one? Should I stay at Dotnet Core 2.2 or do I have to delete my unit-tests?

**Comment by brockallen** [comment]
Any word on this? I suspect there are lots of integration tests that aren't happy in 3.x now. Here's how my tests are failing now:

```
System.InvalidOperationException : The view 'Foo' was not found. The following locations were searched:
    /Views/Account/Foo.cshtml
    /Views/Shared/Foo.cshtml
```

**Comment by brockallen** [comment]
BTW, I did hack up a workaround:

`builder.UseContentRoot(Path.Combine(AppContext.BaseDirectory, @"..\..\..\..\..\src\MyMvcProjectFolder"))`

**Comment by brockallen** [comment]
Setting an explicit content root via `UseContentRoot` also has no effect.

**Comment by javiercn** [comment]
@brockallen This might be because the app name is not setup correctly, try setup the app name. One way to troubleshoot this is to look at the list of application parts and see if the views assembly is there.

**Comment by toralux** [comment]
@javiercn Does setting up app name correctly apply to my github example in the original post?

**Comment by brockallen** [comment]
I tried this and now it seems to be working:

```
            var builder = new WebHostBuilder();
            builder.ConfigureAppConfiguration((context, b) => {
                context.HostingEnvironment.ApplicationName = typeof(HomeController).Assembly.GetName().Name;
            });

```

Makes me wonder why it worked in 2.1.

**Comment by javiercn** [comment]
@brockallen This was likely caused to the move to generic host in 3.0. 

The way we find views/application parts changed in 3.0 and I think some changes in generic host might have caused the app name to be different. I imagine you have a Startup class on a test assembly and are trying to use that and as a result of calling UseStartup the app name is changing (or is setup to the test assembly from the get go).

**Comment by pikoscielniak** [comment]
Perfect. Problem solved.

**Comment by toralux** [comment]
I applied this solution and it solved my problem, happily running my app using 3.1 :)

**Comment by toralux** [comment]
I have applied the fix and committed it to my example
