### ISSUE TITLE
Asp .Net Core 3.0 adding a custom Startup class in tests causes that the Views are not served anymore

### ISSUE THREAD

**Issue by pikoscielniak** [dotnet/aspnetcore#17651]
I test an Asp .Net Core 3.0 MVC application. This a basic sample app create with the command dotnet new mvc. In the xunit test project I test returning of the view Index from the `HomeController`. The test looks like this:

```csharp
public class HomeControllerTests
{
    [Fact]
    public async Task ReturnsView()
    {
        const string testProjectDir = "ViewsTestingTests";
        var factory = new TestServerFactory();
        var client = factory.WithWebHostBuilder(builder =>
        {
            builder.UseSolutionRelativeContentRoot(testProjectDir);
            builder.ConfigureTestServices(services =>
            {
                services.AddControllersWithViews()
                    .AddApplicationPart(typeof(Startup).Assembly);
            });
        }).CreateClient();

        var resultIndex = await client.GetAsync("/");
        resultIndex.StatusCode.Should().Be(200);
        var content = await resultIndex.Content.ReadAsStringAsync();
        content.Should().Contain("Welcome");
    }
}

public class TestServerFactory : WebApplicationFactory<TestStartup>
{
    protected override IWebHostBuilder CreateWebHostBuilder()
    {
        return WebHost.CreateDefaultBuilder(null)
            .UseStartup<TestStartup>();
    }
}

public class TestStartup : Startup
{
    public TestStartup(IConfiguration configuration) : base(configuration)
    {
    }
}
```
I use a test startup class because I'll be overriding some methods. When I use this `TestStartup` class the test doesn't pass with the following reason:

```
The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
```

But if I use the Startup class from the main project like this:

```csharp
public class TestServerFactory : WebApplicationFactory<Startup>
{
    protected override IWebHostBuilder CreateWebHostBuilder()
    {
        return WebHost.CreateDefaultBuilder(null)
            .UseStartup<Startup>();
    }
}
```
And create Client like this:
```csharp
var client = factory.WithWebHostBuilder(builder =>
            {
                builder.UseSolutionRelativeContentRoot(testProjectDir);
            }).CreateClient();
```
Then the test pass. Of course I copied the whole Views folder to the test project.
What is interesting the same test used to work in Asp. Net Core 2.2. 

Using builder.UseContentRoot inside factory.WithWebHostBuilder and setting a path to the test project folder doesn't help. Please help me how to approach this problem.

**Comment by mykola384** [comment]
Do you have any news on this? I have very similar issue. I also described it and asked for help here:
https://stackoverflow.com/questions/60058325/net-core-3-1-webapplicationfactory-testserver-cannot-find-razor-view-when-over

**Comment by brockallen** [comment]
Related? https://github.com/dotnet/aspnetcore/issues/17655#issuecomment-581418168

**Comment by pikoscielniak** [comment]
Yes, and it works. Thank you.

**Comment by mykola384** [comment]
I fixed it by adding 

`services
                .AddMvc()
                .AddRazorRuntimeCompilation()
                .AddApplicationPart(typeof(TTestStartup).Assembly);`

But thanks for the suggestion!

**Comment by pikoscielniak** [comment]
@mykola384 for me even better solution. I must only add the package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation. Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by jjxtra** [comment]
Still seeing this in .NET 5 rc1 unfortunately... cannot unit test views.
