### ISSUE TITLE
Consider adding an analyzer that recommends not using endpoint routing when authorization filters are used

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17671]
Based on https://github.com/aspnet/AspNetCore/issues/17138

In 3.0, with endpoint routing, MVC will evaluate `IAuthorizeData` on actions twice if the application uses AuthZ filters - once as part of the AuthZ middleware and once as part of the filter exection. Auth filters run as combined by default. The `AuthorizeAttribute` may require the policy to be evaluated with the policy on the filter. Doing otherwise may result in incorrect behavior.

We don't have any good indication that mixing authZ filters + endpoint routing might be problematic. We could author an analyzer that nudges users towards the `RequireAuthorization` feature over using filters.

**Comment by mkArtakMSFT** [comment]
Moving this to Backlog to collect more data regarding whether this confuses community more broadly or not.

**Comment by javiercn** [comment]
We would do the opposite if anything, don't recommend using authorization filters at all. endpoint routing is the future.

**Comment by javiercn** [comment]
Closing since this is not a direction we want to take.
