### ISSUE TITLE
When Razor views are compiled, i'd like to get access to resulting C# code

### ISSUE THREAD

**Issue by IKoshelev** [dotnet/aspnetcore#17690]
### Describe the solution you'd like
Ideally - I'd like to see resulting C#  files as sub-items of the .cshtml files (like https://github.com/RazorGenerator/RazorGenerator allows for non-core MVC). But really, any non-hacky solution which lets me feed in .cshtml files and outputs C# files will do. 

### Additional context
![image](https://user-images.githubusercontent.com/5594348/70394939-316d8180-19fa-11ea-872f-11c8beda5243.png)

**Comment by pranavkm** [comment]
You can look at the generated Razor files under the `obj\Debug\$TargetFramework$\Razor`.
