### ISSUE TITLE
Asynchronous implementation of IDataProtectionProvider.CreateProtector

### ISSUE THREAD

**Issue by gregbradley** [dotnet/aspnetcore#17696]
We need to implement an `IDataProtectionProvider` that has a `CreateProtector()` method that calls an asynchronous method. Is this possible to do with the current definition and usage of `IDataProtectionProvider`?

**Comment by blowdart** [comment]
Well you could await inside it, but generally no. We don't expect asynchronous use of this, because the keyring is created rarely and needs to be fully created before anything else continues. The complications of async aren't worth it in this case.

**Comment by gregbradley** [comment]
Hi @blowdart. Thanks for the quick reply. We have a requirement when creating our data protector to make a HTTP call to fetch some keys from our HSM. You said we could await inside, but how do we do that when `CreateProtector()` is not `async`? Our attempt to use `Task.Run(() => ...).Result` ended up creating deadlocks.

**Comment by blowdart** [comment]
var task = MyAsyncMethod();
var result = task.WaitAndUnwrapException();

or

var result = AsyncContext.Run(MyAsyncMethod);

**Comment by gregbradley** [comment]
Hi @blowdart, are those classes/methods from an external library are a newer version of .NET Core? I don't see them in .NET Core 2.2.

**Comment by blowdart** [comment]
Huh I thought there were there for ages.

Hey @Tratcher any help here?

**Comment by Tratcher** [comment]
You're stuck with Task.GetAwaiter().GetResult().

**Comment by gregbradley** [comment]
Hi @Tratcher. We will give that a try. We had a problem where our app would be working fine and then every now and then the thread count would just start climbing and we were forced to restart the application. Microsoft Azure support looked into it and believe the problem was because of where we were using Task.Result. So we shouldn't the same thread count issue if we use Task.GetAwaiter().GetResult() to call asynchronous code from a synchronous method? Thanks for you help.

**Comment by Tratcher** [comment]
Yes, this can still cause the same issue. That said, you should be able to set up data protection during Startup which is all sync anyways. That should avoid causing any Task.Result related issues during requests.

**Comment by gregbradley** [comment]
The problem is our data protection needs to get some keys from our HSM by making a HTTP GET request to the service, using HttpClient which only provides async methods.

**Comment by Tratcher** [comment]
Sure, as long as you finish that in Startup, before you start processing requests, it should be OK.

**Comment by saber-wang** [comment]
I get the key from the middleware and save it in the context, and customize IDataProtectionProvider to get the password from the context
