### ISSUE TITLE
Identity scaffolding and "OTS parsing error: invalid version tag"

### ISSUE THREAD

**Issue by gaelian** [dotnet/aspnetcore#17693]
### Describe the bug
After adding the ASP.NET Identity scaffolding to an ASP.NET Core 2.1 web app, glyph icons don't display correctly and a number of  `OTS parsing error: invalid version tag` and `Failed to decode downloaded font` messages are visible in the browser console, referring to these files:

`glyphicons-halflings-regular.woff2`
`glyphicons-halflings-regular.woff`
`glyphicons-halflings-regular.ttf`

Also, an `OTS parsing error: invalid version tag` and `DevTools failed to parse SourceMap` messages are visible in relation to `bootstrap.css.map`.

### To Reproduce

- In Visual Studio (on Windows) 2017, create a new ASP.NET Core 2.1 Web Application ("File" > "New" > "Project" > Choose "ASP.NET Web Application", click "OK".
- In the pop-up window, choose ".NET Core" and "ASP.NET Core 2.1" in the drop down boxes, choose Web Application (Model-View-Controller), click "OK".
- Click the "IIS Express" button to debug the app (using Chrome 78.0.3904.108) - note that the `glyphicon-chevron-left` and `glyphicon-chevron-right glyphs` used as the left/right arrows for the carousel on the home page display **correctly**.
- Stop debugging the app.
- In Visual Studio, right click on the project name and choose "Add" > "New Scaffolded item...", choose "Identity", click "Add".
- Click "Override all files", select the default "Data context class" and "User class" via the "+" buttons, click "Add".
- Wait for Identity scaffolding code to be generated and added to the project
- Click the "IIS Express" button to debug the app (using Chrome 78.0.3904.108) - note that the `glyphicon-chevron-left` and `glyphicon-chevron-right` glyphs used for the carousel on the home page now display **incorrectly** as white rectangles and the previously mentioned `OTS parsing error: invalid version tag` messages are now visible in the browser console (in Internet Explorer 11, the `glyphicon-chevron-left` and `glyphicon-chevron-right` glyphs do not display at all).

I have searched for the `OTS parsing error: invalid version tag` error and there appears to be a number of possible causes, from incorrect resource paths to missing MIME types for the font file extensions (`.woff`, `.woff2`, etc.). I am not seeing any 404 errors when running the project and looking at the resources being downloaded, nor does MIME type seem to be an issue as far as I can tell.

### Further technical details
- ASP.NET Core version (being used): 2.1
- Using Visual Studio 2017 on Windows (15.9.17)

Output of `dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.110
 Commit:    4797dabd3c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.110\

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by blowdart** [comment]
We can't repro this at all. Can you share a github repo?

**Comment by gaelian** [comment]
Hi @blowdart,

Here's a project I just pushed for you:

https://github.com/gaelian/TestApp

Haven't tested on any other machines as yet to see if perhaps it's machine-specific.

I've also attached a screen shot of what things look like when I debug:
![error](https://user-images.githubusercontent.com/357458/72114892-29a65180-3399-11ea-9f48-9150cdfc946e.png)

**Comment by pranavkm** [comment]
Thank you for the issue report @gaelian. We haven't seen any additional reports of this issue. Closing this as per our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
