### ISSUE TITLE
Remove most of Razor VSCode's project telemetry reporting

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#17712]
Today Razor's VSCode extension reports all Razor language server based telemetry. We should move the project configuration telemetry portion into the Razor Language Server so we can get telemetry data on all Razor Langauge Server telemetry uses regardless of client.

**Comment by ryanbrandenburg** [comment]
Because it was found that most of the telemetry we were producing was not useful we've decided to remove the unhelpful parts and come back to this issue when we have a plan which will help us better understand the usage and needs in this area.
