### ISSUE TITLE
Blazor server localization issue in Visual Studio 16.4 + .NET Core 3.1 SDK.

### ISSUE THREAD

**Issue by mttrkm** [dotnet/aspnetcore#17729]
### Describe the bug
Blazor server localization is not working in Visual Studio 16.4 + .NET Core 3.1 SDK.

### To Reproduce
Please see
https://github.com/mttrkm/BlazorLocalizationIssueWithCore3_1SDK
Localization works with Visual Studio 16.3.10 + .NET Core 3.0 SDK.
But that does not work by upgrading Visual Studio 16.4 + .NET Core 3.1 SDK.

### Further technical details
- ASP.NET Core version 
3.0(Target) but SDK is 3.1

- Include the output of `dotnet --info`
> .NET Core SDK (global.json を反映):
>  Version:   3.1.100
>  Commit:    cd82f021f4
> 
> ランタイム環境:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.100\
> 
> Host (useful for support):
>   Version: 3.1.0
>   Commit:  65f04fb6db
> 
> .NET Core SDKs installed:
>   3.1.100 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Professional 2019
Version 16.4.0

**Comment by mttrkm** [comment]
Thanks for your planning.
End of support for .NET Core 3.0 is March 23, 2020.
The release schedule for .NET 5.0 is November 2020.
What are the workarounds for this blank period?

**Comment by mttrkm** [comment]
I found a workaround at #17733 . 
That is to move SharedResource.cs from the Resources folder to the root.

**Comment by pranavkm** [comment]
@mttrkm this seems to be an intentional change in how the 3.1 SDK generates namespaces for resources. The workaround you have seems to be an appropriate workaround. I'll follow up on the issue you linked to.
