### ISSUE TITLE
Run Razor VSCode functional tests on PRs

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#17721]
Currently the Razor VSCode functional tests do not run in PRs for several reasons.

1. They hit path-to-long exceptions when acquiring a dynamic VSCode to run tests in
1. Their flakiness level is too high. This might be an over exaggeration now because we've done a lot of work to make them better; however, I still want to put this statement here because ideally, they have 0% flake. This work item is primarily tracked: https://github.com/aspnet/AspNetCore/issues/13556
1. Have not investigated the requirements on agents to run them as part of the CI. They may already "just work" but this is a point of interest when completing this item.

**Comment by ajaybhargavb** [comment]
I took a stab at this with https://github.com/aspnet/AspNetCore-Tooling/pull/1459.
To update on @NTaylorMullen's points earlier,
- The path too long exception still exists and blocks running tests on Windows (https://github.com/microsoft/vscode-test/issues/43)
- Linux CIs don't seem to have yarn installed or atleast it's not on path
- Mac CIs attempt to run them but fail with `Error: command 'extension.configureRazorDevMode' not found` which doesn't happen locally

**Comment by ajaybhargavb** [comment]
Update:
- The problem with macOS is that VSCode doesn't respect the dotnet that is activated. 
- Got past the yarn error in Linux CI but it now fails with an unknown error when invoking `runTests.ts`.
  - I'm unable to reproduce this error locally on Ubuntu but it fails due to some arcade sdk not being found,
```
/home/ajay/GitHub/dotnet/aspnetcore-tooling/Directory.Build.props(11,3): Error: /home/ajay/GitHub/dotnet/aspnetcore-tooling/.dotnet/sdk/5.0.100-alpha.1.20063.3/Sdks/Microsoft.DotNet.Arcade.Sdk/Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
/home/ajay/GitHub/dotnet/aspnetcore-tooling/Directory.Build.props(11,31): Error: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
/home/ajay/GitHub/dotnet/aspnetcore-tooling/Directory.Build.props(11,31): Error: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
```

**Comment by ajaybhargavb** [comment]
The follow-up of this is tracked here. https://github.com/dotnet/aspnetcore/issues/19296
