### ISSUE TITLE
SignalR streaming produces tons of Gen2 arrays on client's heap.

### ISSUE THREAD

**Issue by Kant8** [dotnet/aspnetcore#17736]
I was trying to implement file upload with WebSockets on SignalR and got stuck on this.
Hub has IAsyncEnumerable<FileChunk> argument and writes chunks to disk, where FileChunk contains byte array and explicit chunk size. Client sends these chunks generating async stream from file, nothing special.

But for some reason when upload is fast, client eats memory proportional to file size. All created objects are promoted to Gen2 in heap, therefore not collected often, and have no roots right after chunk was sent via network. You can see them in dump pefview or dotnet-dump (dumpheap -dead).

Objects that got stuck are pairs of byte array (4 or 8kb size) and System.IO.Pipelines.BufferSegment (80 bytes).

I've tried to set AddHubOptions<>(o => o.StreamBufferCapacity = 1);  - it doesn't help.
You can reproduce it with default settings, without playing with different available buffer size options (and none of them helps to fix this).

However if you put await Task.Delay(1) in method, that generates stream on client, memory consumption disappears, but upload slows down for like 1000 times.

### To Reproduce
Here are examples that reproduce memory consumption even without files just with MemoryStream.

Hub on server:
``` C#
public class FooHub : Hub
    {
        public async Task Upload(string fileName, int maxChunkSize, IAsyncEnumerable<FileChunk> chunks)
        {
            // emulate writing file
            var buffer = new byte[maxChunkSize];
            var stream = new MemoryStream(buffer, true);
            await foreach (var chunk in chunks)
            {
                await stream.WriteAsync(chunk.Data, 0, Math.Min(chunk.Size, maxChunkSize));
                stream.Position = 0;
            }

            await Clients.Caller.SendAsync("UploadFinished");
        }

        [DataContract]
        public class FileChunk
        {
            [DataMember]
            public int Size { get; set; }

            [DataMember]
            public byte[] Data { get; set; }
        }
    }
```
Hub is configured as
``` C#
 endpoints.MapHub<FooHub>("/foohub", o =>
                {
                    o.Transports = HttpTransportType.WebSockets;
                });
```
Everyting else is default.

Client (with Main method inside to play in console):
``` C#
public class FooClient
    {
        private readonly HubConnection _connection;
        private readonly TaskCompletionSource<bool> _tcs;
        private readonly int _chunkSize;
        private readonly int _chunkCount;

        private byte[] _buffer;

        public FooClient(string url, int chunkSize, int chunkCount)
        {
            _tcs = new TaskCompletionSource<bool>();
            _connection = new HubConnectionBuilder().WithUrl(url).Build();
            _chunkSize = chunkSize;
            _chunkCount = chunkCount;

            _buffer = new byte[chunkSize];
        }

        public async Task<bool> UploadFile(string fileName)
        {
            _connection.On("UploadFinished", UploadFinishedHandler);
            _connection.Closed += ClosedHandler;

            await _connection.StartAsync();
            await _connection.SendAsync("Upload", fileName, _chunkSize, GetChunkStream());

            var result = await _tcs.Task;
            await _connection.StopAsync();

            return result;
        }

        private async IAsyncEnumerable<FileChunk> GetChunkStream()
        {
            // emulate file read
            var fictionalFile = Enumerable.Repeat((byte)1, _chunkSize).ToArray();
            var stream = new MemoryStream(fictionalFile);

            for (int i = 0; i < _chunkCount; i++)
            {
                //await Task.Delay(1); // uncomment this to "fix" memory consumption and make upload slow
                stream.Position = 0;
                var bytesRead = await stream.ReadAsync(_buffer, 0, _chunkSize);
                if (bytesRead > 0)
                    yield return new FileChunk { Size = bytesRead, Data = _buffer };
            }
        }

        private Task UploadFinishedHandler()
        {
            _tcs.SetResult(true);
            return Task.CompletedTask;
        }

        private Task ClosedHandler(Exception ex)
        {
            if (ex != null)
                _tcs.SetException(ex);
            else
                _tcs.TrySetResult(false);

            return Task.CompletedTask;
        }

        [DataContract]
        public class FileChunk
        {
            [DataMember]
            public int Size { get; set; }

            [DataMember]
            public byte[] Data { get; set; }
        }

        static async Task Main(string[] args)
        {
            string serverUrl = "http://localhost:XXXXX/foohub";

            var sw = new Stopwatch();
            string command;
            while (!String.IsNullOrEmpty(command = Console.ReadLine()))
            {
                try
                {
                    if (command == "gc")
                    {
                        GC.Collect(2, GCCollectionMode.Forced, true, true);
                        continue;
                    }

                    if (!int.TryParse(command, out var chunkSizeKB))
                    {
                        chunkSizeKB = 4;
                    }

                    Log("Start uploading " + command);

                    var client = new FooClient(serverUrl, chunkSizeKB * 1024, 5000);

                    sw.Restart();
                    var result = await client.UploadFile("foo.blob");
                    sw.Stop();

                    Log("Upload result " + result + " in " + sw.ElapsedMilliseconds + " ms");
                }
                catch (Exception ex)
                {
                    Log("Error: " + ex);
                }
            }
        }

        private static void Log(string msg)
        {
            Console.WriteLine("[x] " + msg);
        }
    }
```
Simple Main method reads commands from console, for empty string => exit, "gc" => collect gen2, and any number  => send 5k chunks of number KB size.
Every time you make new upload console client eats RAM until some threshold, when .net itself finally decides to collect some arrays in gen2.

aspnetcore 3.1 (initially tried on 3.0, same behaviour)

**Comment by anurse** [comment]
> Objects that got stuck are pairs of byte array (4 or 8kb size) and System.IO.Pipelines.BufferSegment (80 bytes).

Are you able to track back which `byte[]`s are being kept around? Are they specifically your byte arrays (the ones held by `FileChunk`s)? SignalR uses a pool of `byte[]`s to buffer data as it's being sent on the wire. We buffer data being sent to the server, and I think it's that buffer you're seeing. You're generating data faster than it can be sent, so it's being buffered. Eventually, when the buffer goes

It looks like we don't expose the Pause/Resume thresholds for the client-side Pipelines implementation. Doing that might give you more control here. We should consider that.

**Comment by anurse** [comment]
Filed https://github.com/aspnet/AspNetCore/issues/17797 to consider adding buffer size thresholds for the client.

I'd still like to hear if you can confirm what owns the buffers that are being kept around. If it's `FileChunk` there may be some other place we need to investigate. If they're mostly owned by types in `System.IO.Pipelines`, then it's the buffering I mentioned above that's keeping them around.

**Comment by Kant8** [comment]
Yes, they are not my arrays. I can send FileChunks with different size buffers, but in gen2 heap arrays are always exactly 8kb (in other project they were 4kb for some reason).
And also contents of these arrays is already encoded. In sample I send "files" with numbers 1, in dump it is "AQEBAQEBAQEBA...".

**Comment by anurse** [comment]
Ok, given that, I think #17797 is the main action we can take here. I'm shifting this specific issue to the Discussions milestone. We can continue discussing and create issues if any other actionable work comes out.

@Kant8 I'm curious how quickly you are generating messages in your app. Generally, buffer growth like this would occur because you are generating messages much faster than the network stack can flush them out. This means more and more arrays are allocated to buffer that data. It looks like you're sending 4KB chunks which is a slightly unfortunate number because SignalR *also* uses 4KB buffers to store outgoing messages. This means that your 4KB has a few bytes of SignalR protocol added to it and then we end up needing more than one buffer to hold the data (it doesn't **double** buffer use because we can use the leftover space in one buffer to store a part of the next message, but it can cause growth like this). Does the allocation rate change at all if you reduce the chunk size to say 2 or 3KB?

**Comment by Kant8** [comment]
Unfortunately I cannot reproduce case where buffers were 4KB, they are all 8KB now. Mb that depends on .netcore version.
I was sending file in that stream, so data is available almost immediately, network is definitely slower than SSD + FileStream buffer caching.
And yes, memory consumptions is much better when I send arrays up to 7KB (so 7KB bytes + array length + manual length field + stream message header). But reducing message size is bad for throughput. In my tests upload speed stabilized at at least 16KB per chunk.
