### ISSUE TITLE
Configuring health checks through appsettings.json and/or Azure

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/aspnetcore#17734]
Being able to configure health checks through C# is great. But it would be nice to be able to configure some settings through appsettings.json and Azure app settings. Examples of this could be to enable/disable single checks, disable all checks, etc. I cannot seem to find any documentation showing if this is possible or not. Health Checks UI has some config but doesn't apply for anything else than UI itself. Possible?

**Comment by rynowak** [comment]
We don't generally put coupling between configuration and our systems unless it's something that has a really strong need for it (logging).

If you want to do this there's a pretty straightforward path. Coincidentally are you using health checks for metrics reporting?

This seems like a good doc article that could be added. I'd start with something like:

```C#
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();

                endpoints.MapHealthChecks("/healthz", new HealthCheckOptions()
                {
                    // Will be called once-per-check per request to the health endpoint.
                    Predicate = (check) =>
                    {
                        // Ask the config if this should be enabled.
                        var section = Configuration.GetSection("healthChecks");
                        return section.GetValue(check.Name, true); //enabled by default
                    }
                });
            });
```

**Comment by ThomasArdal** [comment]
In my case, I want to be able to enable/disable publishing of health checks depending on the environment where the code is currently deployed. On a test environment, you may not want to publish health checks while on production you definitely want to. I could check for the environment and include an if in the code. But would be much nicer to be able to write something like this:

```json
{
    "HealthChecks": {
        "Enabled": false
    }
}
```

**Comment by pranavkm** [comment]
@ThomasArdal you should be able to conditionally register healthchecks based on some value in the appsetting or based on the deployment environment. We don't think there are any blocking issues in this area, but if there are feel free to file a new issue explaining what's blocking and we'll investigate.

**Comment by ThomasArdal** [comment]
Sure thing. I can easily create one or more booleans in my config file and then pull those boolean values from C# and register the health checks conditionally. I just wanted to hear if there was some kind of built-in feature for this 👍
