### ISSUE TITLE
[Identity] Save external tokens automatically on every login

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#17737]
When using Identity with an external authentication provider, the tokens are not saved automatically by the default UI.

I had to scaffold the UI and add the following code to OnGetCallbackAsync to get this to work
```csharp
await _signInManager.UpdateExternalAuthenticationTokensAsync(info);
```

The tokens also weren't saved as part of the account creation flow in `OnPostConfirmationAsync` and following the instructions in the docs seemed to have no effect https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.1

See
```
                // Include the access token in the properties
                var props = new AuthenticationProperties();
                props.StoreTokens(info.AuthenticationTokens);
                props.IsPersistent = true;

                await _signInManager.SignInAsync(user, props);
```

**Comment by pranavkm** [comment]
@javiercn do you think we still need to do this?

**Comment by javiercn** [comment]
I think so, at least for 6.0. 

The external providers flow should work with the default Identity UI, without requiring the user to scaffold the page.

**Comment by adityamandaleeka** [comment]
Triage: the docs might have been improved since this was filed. Need to check and reevaluate.

**Comment by mikekistler** [comment]
Closing this for now. Please reopen if you feel this should be re-considered.
