### ISSUE TITLE
Add LSP light bulb support for Fully qualified types in Razor.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#17744]
The idea behind this issue is to enable users to `ctrl + .` -> fully qualify a piece of C# that is not properly included.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg this done?>

**Comment by ryanbrandenburg** [comment]
As of https://github.com/dotnet/aspnetcore-tooling/commit/9f4528d415cd230d2542b0368319018683440a7c yes. I got super used to things auto-closing when you do "Fixees #sfddsf", but 1, that doesn't work because we're in a different repo and 2, it doesn't fix the labels, I I've gotta break that habit.
