### ISSUE TITLE
Typo in file '.azure/pipelines/ci.yml': 'valule'

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#17743]
Here:

https://github.com/aspnet/AspNetCore/blob/e72223eaf58a3ee6660a922064d2449e47b78253/.azure/pipelines/ci.yml#L66

Not sure if this typo matters, but the it should clearly be `value` instead of `valule`.

**Comment by Pilchie** [comment]
@aspnet/build ?

**Comment by BrennanConroy** [comment]
I fixed this somewhere... I'll go find if it hasn't flowed yet

**Comment by BrennanConroy** [comment]
Yeah, it's stuck flowing forward from 3.0 in this PR https://github.com/aspnet/AspNetCore/pull/16621

**Comment by dougbu** [comment]
Fixed ages ago 😺
