### ISSUE TITLE
Middleware skipped when UseEndpoints is called multiple times

### ISSUE THREAD

**Issue by jussimattila** [dotnet/aspnetcore#17750]
### Describe the bug
Middleware between two calls to configure endpoint routing using `app.UseEndpoints(...)` is never executed. 

Expected:
Looking at this startup code, I would expect `SetUser()` middleware to be executed before MVC controller.
![image](https://user-images.githubusercontent.com/8625258/70565202-408b3580-1b9a-11ea-8409-81be94420a01.png)

Actual:
The breakpoint is never hit.

### To Reproduce
Create a new ASP.NET Core 3.1 MVC web application. Replace `Startup.cs` with this: https://gist.github.com/jussimattila/047ab4936f943ed8b0f2a6574c2525a5

Set a breakpoint to the middleware, confirm it is not executed.

### Further technical details
- ASP.NET Core 3.1
```
C:\Users\Jussi>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
```
- Visual Studio 2019 16.4

**Comment by javiercn** [comment]
@jussimattila thanks for contacting us.

I believe we don't recommend/support using `app.UseEndpoints` multiple times.

@rynowak anything to add here?

**Comment by jussimattila** [comment]
To me, this was a surprise. I was expecting that any middleware, which is configured in the request pipeline before endpoints, would get called. Maybe there should be a validator complaining about multiple calls to `app.UseEndpoints`?

**Comment by khellang** [comment]
Semi-related: https://github.com/aspnet/AspNetCore/issues/17210

**Comment by khellang** [comment]
The issue here is that the `UseEndpoints` method gives the illusion that you can configure individual endpoints per call, while in reality they all end up in the same endpoint collection which is used to resolve an endpoint in the `UseRouting` middleware and invoked at the first instance of `UseEndpoints`.

IMO, the solution is to either somehow tag endpoints so only the "correct" endpoint middleware will handle it, or just disallow multiple calls to `UseEndpoints` altogether. They are, after all, terminating endpoints, not middleware.

**Comment by DaleyKD** [comment]
This is the problem we're seeing now, almost exactly.

We have a piece of middleware that needs to run for all endpoints EXCEPT HealthChecks.  Therefore, what do we do?

**Comment by javiercn** [comment]
@DaleyKD you can mark your healthcheck endpoints with some metadata and check for that endpoint metadata in your custom piece of middleware to skip it.

**Comment by DaleyKD** [comment]
For now, I just went back to the old app.UseHealthChecks.  Fixed my needs for now.

**Comment by anurse** [comment]
Reactivating per [Twitter discussion](https://twitter.com/khellang/status/1229181050527637507?s=21).

**Comment by khellang** [comment]
@mkArtakMSFT This issue isn't a question or a discussion. This is a bug 🐛 🙈

**Comment by rizi** [comment]
@mkArtakMSFT we have exactly the same problem, please "allow" to call app.UseEndPoints multiple times and execute all configured middlewares.
br

**Comment by danielearwicker** [comment]
> @DaleyKD you can mark your healthcheck endpoints with some metadata and check for that endpoint metadata in your custom piece of middleware to skip it.

For example, to stop the healthcheck route from requiring auth:

```cs
endpoints.MapHealthChecks("/health").WithMetadata(new AllowAnonymousAttribute());
```

**Comment by javiercn** [comment]
We don't recommend calling UseEndpoints multiple times as described in a similar issue.

I'm closing this issue for now, if we hear new/more feedback about it we'll reconsider.
