### ISSUE TITLE
Blazor: Mono linker path not properly quoted

### ISSUE THREAD

**Issue by jspuij** [dotnet/aspnetcore#17754]
### Describe the bug
The new BlazorILLink task does not properly quote the MonoLinkerPath, so usernames with e.g. spaces make the linker task fail.
See: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Build/src/targets/Blazor.MonoRuntime.targets#L204

### To Reproduce

Try to compile a blazor wasm project from a machine with a space in the username. See this gist, at "_LinkBlazorApplication":

https://gist.githubusercontent.com/TofuEcho/0d110f8cad83071406dcd8f48d928fbc/raw/259d63b7e9b541cdc17475b142fa8c7a7e537a62/gistfile1.txt

### Further technical details
- ASP.NET Core version 3.1.0

**Comment by Flearz** [comment]
Got the same problem, "ILLink failed with exited code 1" even with a blank project...

**Comment by jspuij** [comment]
@Flearz workaround is to edit the file ".nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets" in your home directory and change:

```
  <BlazorILLink
        ILLinkPath="$(MonoLinkerPath)"
        AssemblyPaths="@(_BlazorAssemblyToLink)"
        RootAssemblyNames="@(_BlazorLinkerRoot)"
        RootDescriptorFiles="@(BlazorLinkerDescriptor)"
        OutputDirectory="$(BlazorIntermediateLinkerOutputPath)"
        ExtraArgs="$(_BlazorLinkerAdditionalOptions)"
        ToolExe="$(_DotNetHostFileName)"
        ToolPath="$(_DotNetHostDirectory)" />
```
into
```
  <BlazorILLink
        ILLinkPath="&quot;$(MonoLinkerPath)&quot;"
        AssemblyPaths="@(_BlazorAssemblyToLink)"
        RootAssemblyNames="@(_BlazorLinkerRoot)"
        RootDescriptorFiles="@(BlazorLinkerDescriptor)"
        OutputDirectory="$(BlazorIntermediateLinkerOutputPath)"
        ExtraArgs="$(_BlazorLinkerAdditionalOptions)"
        ToolExe="$(_DotNetHostFileName)"
        ToolPath="$(_DotNetHostDirectory)" />
```

**Comment by Flearz** [comment]
@jspuij 
This works thank you so much, I've been stuck with this for hours. Hope they will correct this soon.
Have a nice week.
Rihen

**Comment by jspuij** [comment]
@Flearz You're welcome ;-)

**Comment by javiercn** [comment]
@jspuij thanks for contacting us.

We'll take a look at the issue and get back to you.

**Comment by stormleoxia** [comment]
In fact the problem doesn't come from quoting but instead because monolinker should not be called by dotnet. 

I manage to make it work  by changing the target in 
`%UserProfile%\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets` like this:

    <BlazorILLink
        ILLinkPath="$(MonoLinkerPath)"
        AssemblyPaths="@(_BlazorAssemblyToLink)"
        RootAssemblyNames="@(_BlazorLinkerRoot)"
        RootDescriptorFiles="@(BlazorLinkerDescriptor)"
        OutputDirectory="$(BlazorIntermediateLinkerOutputPath)"
        ExtraArgs="$(_BlazorLinkerAdditionalOptions)"
        ToolExe="$(MonoLinkerPath)"
        ToolPath="$(MonoLinkerPath)" />

and recompile the `Microsoft.AspNetCore.Blazor.Build.Tasks.dll` and change the following

        protected override string ToolName => Path.GetFileName(DotNetPath);
        protected override string GenerateFullPathToTool() => DotNetPath;
        protected override string GenerateCommandLineCommands() => ILLinkPath;

by 

        protected override string ToolName => Path.GetFileName(ILLinkPath);
        protected override string GenerateFullPathToTool() => ILLinkPath;
        protected override string GenerateCommandLineCommands() => string.Empty;

It's a bit quick and dirty fix but it works :)

**Comment by SeppPenner** [comment]
I'm seeing the same issue.

> This works thank you so much, I've been stuck with this for hours. Hope they will correct this soon.

@Flearz Glad it was hours only for you. Days for me :)

**Comment by TroelsL** [comment]
Same issue here. Spent an evening tracking this down before finding this post. Can confirm that the workaround worked. Thanks!

**Comment by zhou-xb** [comment]
@jspuij  thank you so much, how can you be that rocking smart?

**Comment by SeppPenner** [comment]
@jkotalik Nice :)
