### ISSUE TITLE
AuthorizeAttribute on specific action is ignored

### ISSUE THREAD

**Issue by clement911** [dotnet/aspnetcore#17768]
I have a global policy with `AuthorizationPolicyBuilder.RequireAuthenticatedUser()` but I'm trying to override authorization on a single action to only allow user authenticated with a specific scheme.

```
[Authorize(AuthenticationSchemes = "myscheme")]
[HttpGet]
public ActionResult DoSomething()
```

This doesn't work. Anyone authenticated can trigger this action, regardless of which scheme they are authenticated with.
Am I doing something wrong or is this a bug?

**Comment by javiercn** [comment]
@clement911 thanks for contacting us.

Can you provide more details on what version of asp.net core are you using?
@HaoK this is a question about how policies combine. Can you take it from here?

**Comment by clement911** [comment]
We are using aspnet core 3.1

**Comment by HaoK** [comment]
So the issue is that when you don't specify any specific requirements for your DoSomething, any authenticated user is considered sufficient, specifying "myscheme" doesn't do what you desire.  You would need to add a specific requirement that is checking that they have successfully authenticated via "myscheme" only.  The default authorize attribute just requires any authenticated user, similar to your global policy

**Comment by HaoK** [comment]
More concretely, you could register a requirement/handler which calls `httpContext.AuthenticateAsync("myscheme")` and only succeeds when that returns a success.

**Comment by clement911** [comment]
What's the purpose of the `AuthorizeAttribute.AuthenticationSchemes` property then?

```
        // Summary:
        //     Gets or sets a comma delimited list of schemes from which user information is
        //     constructed.
        public string AuthenticationSchemes { get; set; }
```

The `HttpContext.User` is populated with all identities, regardless of the value provided to `AuthenticationSchemes`

**Comment by HaoK** [comment]
Do you have a repro for the behavior you are describing?  It doesn't look like we have a specific test for this scenario but I don't see any issues with a challenge not being sent with what you describe, see https://github.com/aspnet/AspNetCore/pull/17816 which is a test that has a default policy that RequiresAuthenticatedUser and an endpoint with an authorize that specifies a scheme that fails to authenticate which results in a challenge

**Comment by clement911** [comment]
No I don't have a test.
Let me explain what I'm trying to do.
Our users can authenticate with two different schemes.
I want to restrict specific action so that they are only authorized if the user is authenticated with a specific scheme.
I've followed this: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#selecting-the-scheme-with-the-authorize-attribute but it doesn't appear to be working.
The only difference is that I'm applying the attribute to a specific action and not a controller.
Is that not a supported scenario? It's certainly not obvious to me.

**Comment by anurse** [comment]
This sounds a lot like a bug. The doc is pretty clear that this is exactly what you would do to *require* a specific scheme. If the code isn't doing that, we should look at fixing that. If there are breaking change issues, we can look at implementing a new feature and updating the doc. Either way, this seems to be something we claim is working, but it is not :).

@clement911 The suggestion @HaoK posted (using a custom requirement that verifies the user is authenticated with the correct scheme) *should* allow to you to get the behavior you want for now, while we evaluate our options for fixing this in 5.0.

**Comment by HaoK** [comment]
Just to be clear, when I added a simple unit test to try and repro the behavior, I couldn't reproduced it via https://github.com/aspnet/AspNetCore/pull/17816  But its possible he is hitting something going on at a higher level, @clement911 can you post a repro app somewhere for us to look at?

**Comment by clement911** [comment]
keep open please

**Comment by anurse** [comment]
@clement911 can you post the requested repro app? @HaoK wasn't able to reproduce it simply from the description. It's certainly quite possible we missed something, which is why a _runnable_ repro app is preferred so we can make sure everything is the same. That's what we need to further investigate here.

**Comment by anurse** [comment]
We still can't repro the issue described in the original post.

@clement911 It's certainly possible that some aspect of your app configuration could be revealing a bug here, but without a runnable sample it's hard to identify that.

Closing this issue for now as there's no further action we can take at this time. When/if you are able to get a repro, we can reopen (or feel free to file a new bug!).
