### ISSUE TITLE
Build AspNetCore from source code

### ISSUE THREAD

**Issue by westfin** [dotnet/aspnetcore#17765]
For certification reasone we need build framework from source code.
But we need build actualy just only source code without test code.
We need remove all tests from repository, but when do it `build.sh` script failed with different errors. Seems tests affect to building process. Maybe you already have any solution for propblem like that?

**Comment by JunTaoLuo** [comment]
We have a script for doing this in Linux: https://github.com/dotnet/aspnetcore/blob/master/eng/scripts/ci-source-build.sh. See example usage at https://github.com/dotnet/aspnetcore/blob/master/.azure/pipelines/ci.yml#L651.

Building from source on other platforms is not currently supported bur should work in similar ways.
