### ISSUE TITLE
C++ Client: error on server when attempting to pass 0xFFFFFFFF to hub method using signalr::value() object

### ISSUE THREAD

**Issue by willroman** [dotnet/aspnetcore#17779]
### Describe the bug
We have a client library written in C++ with a method with a signature similar to:

```C++
void SendSetXXXXEnabledCommand(unsigned short row, unsigned short col, unsigned int flags);
```

and are calling it as follows:

```C++
SendSetXXXXEnabledCommand(1, 1, 0xFFFFFFFF);
```

Within the library we encapsulate the arguments and call SignalR as follows (Note: Using a simple type cast below to cut down on the space needed -- double is the only numeric type available?):

```C++
std::vector<signalr::value> arr{ signalr::value((double)row), signalr::value((double)col), signalr::value((double)flags) };
signalr::value args(arr);

_connection.invoke("SendSetXXXXEnabledCommand", args, ...);
```

Shortly thereafter we receive an exception within the C++ client output: 

```JSON
2019-12-10T21:38:22Z [message     ] processing message: 
{
  "type":3,
  "invocationId":"1",
  "error":"Failed to invoke \u0027SendSetXXXXEnabledCommand\u0027 due to an error on the server."
}
```

Unfortunately, we never receive any call in our server-side code and haven't been able to catch any exceptions there.

When we call this same method using the same parameter values from either a C# or TypeScript/JavaScript client, there is no error.  Furthermore, if we use a smaller value for the last parameter (e.g. 0x7FFFFFFF) in the C++ client there is also no error.

The `0xFFFFFFFF` value (which would seem to be the culprit here) is properly encoded within the `signalr::value` object and `std::vector<signalr::value>` collection (i.e. 4294967295.0000000) so it would seem the problem would be somewhere between handing off the value to the SignalR C++ client proper and when it is attempted to be decoded on the server-side.

### Further technical details
ASP.NET Core SignalR version: 1.1.0
ASP.NET Core version: 3.1.0-preview3.19533.2
.NET Core version: 3.1.0-preview3.19553.2
Visual Studio Enterprise 2019 version: 16.3.10

aspnet/SignalR-Client-Cpp branch master commit 0a35552

UPDATE: I just discovered where this can be corrected in the SignalR C++ client code.  I'll include the correction in a subsequent update to this issue.

**Comment by willroman** [comment]
Found the function in the json_helpers module that is being used to serialize `signalr::value` objects.  The function, `createJson`, currently checks to see when given a float64 value if that value has a fractional part or not.  

If there is a fractional part, the value is simply encoded as a JSON type of real/double.  

If there is no fractional part, the value is cast to (int) and encoded as a JSON type of int.  Unfortunately, for our case described previously, the value we are passing (i.e. `0xFFFFFFFF`) causes an overflow for int (a signed, 32-bit integer) turning it into a negative value.  Our server side code is expecting an unsigned, 32-bit integer so an exception is thrown.

We are proposing a modification to the `createJson` function to further check the value (with no fractional part) and encode it using an appropriately sized type for the value (all of the code of the function is included here for context):

```C++
    Json::Value createJson(const signalr::value& v)
    {
        switch (v.type())
        {
        case signalr::value_type::boolean:
            return Json::Value(v.as_bool());
        case signalr::value_type::float64:
        {
            auto value = v.as_double();
            double intPart;
            // Workaround for 1.0 being output as 1.0 instead of 1
            // because the server expects certain values to be 1 instead of 1.0 (like protocol version)
            if (std::modf(value, &intPart) == 0)
            {
		if (value < 0)
		{
		    if (value > (double)INT32_MIN)
		    {
			// Fits within int32_t
			return Json::Value((int32_t)intPart);
		    }
		    else
		    {
			// Needs int64_t
			return Json::Value((int64_t)intPart);
		    }
		}
		else
		{
		    if (value < INT32_MAX)
		    {
			// Fits within int32_t
			return Json::Value((int32_t)intPart);
		    }
		    else if (value < UINT32_MAX)
		    {
			// Needs uint32_t
			return Json::Value((uint32_t)intPart);
		    }
		    else if (value < INT64_MAX)
		    {
			// Fits within int64_t
			return Json::Value((int64_t)intPart);
		    }
		    else
		    {
			// Needs uint64_t
			return Json::Value((uint64_t)intPart);
		    }
		}
            }
            return Json::Value(v.as_double());
        }
        case signalr::value_type::string:
            return Json::Value(v.as_string());
        case signalr::value_type::array:
        {
            const auto& array = v.as_array();
            Json::Value vec(Json::ValueType::arrayValue);
            for (auto& val : array)
            {
                vec.append(createJson(val));
            }
            return vec;
        }
        case signalr::value_type::map:
        {
            const auto& obj = v.as_map();
            Json::Value object(Json::ValueType::objectValue);
            for (auto& val : obj)
            {
                object[val.first] = createJson(val.second);
            }
            return object;
        }
        case signalr::value_type::null:
        default:
            return Json::Value(Json::ValueType::nullValue);
        }
    }
```

I will try to prepare a pull request including this modification.

**Comment by anurse** [comment]
Sounds good, we'll take a look at the suggestion! The SignalR C++ client is still fairly early on so I'd expect some quirks like this :).
