### ISSUE TITLE
cannot authorize with custom scheme

### ISSUE THREAD

**Issue by yohsii** [dotnet/aspnetcore#17780]
I'm using:
```
services.AddAuthentication().AddCookie("custom", options=> {
                options.LoginPath = "/admin/in";
                options.LogoutPath = "/admin/out";
            });
```
to register the scheme "custom" but when i try and authorize on the controller doing this:
```
[Authorize(Roles = "admin", AuthenticationSchemes = "custom")]
        public ActionResult Index()
        {
            return View();
        }
```
it doesn't authorize the user and redirects to login page even though the user is logged in and is in the correct role.

if, however, i try this:
```
[Authorize(Roles = "admin", AuthenticationSchemes = "Identity.Application")]
        public ActionResult Index()
        {
            return View();
        }
```
the same user will happily authorize and i can get through to the page.

so my question is - how can i get my "custom" authentication scheme to work like "Identity.Application". is there additional configuration required to get the custom authentication scheme to work correctly?

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try now, I just gave you write permissions. Do you need to be an admin to transfer?

**Comment by blowdart** [comment]
@yohsii Can you narrow this down to a small repo? Identity.Application indicates that asp.net core identity is in play, but it's not in your config code, which is confusing

**Comment by yohsii** [comment]
the other pertinent parts of ConfigureServices looks like this:
```
services.AddEntityFrameworkSqlServer().AddDbContext<DbContext>(optionsLifetime: ServiceLifetime.Transient);
services.AddDefaultIdentity<User>(options => { options.SignIn.RequireConfirmedAccount = false; })
                .AddRoles<Role>()
                .AddEntityFrameworkStores<DbContext>();
                
```

**Comment by blowdart** [comment]
OK, so that's where Identity.Application comes from.

So you're mixing identity and cookies here, which is unusual, because now you'll end up having two cookies. What's the second scheme `puck.core.Constants.Mvc.AuthenticationScheme` trying to do?

**Comment by Frankofoedu** [comment]
@blowdart Here is a new repo i created showing the above behaviour. [https://github.com/Frankofoedu/testAspCore](url).

The [Authorize(AuthenticationSchemes ="Admin")]  in the Index.cs file only works when this option `o.ForwardAuthenticate = "Identity.Application";` is in the addcookies code

**Comment by yohsii** [comment]
@blowdart there are two sites in the application. one backoffice admin area with its own login page and a front end site with a different login page. the two schemes are just to be able to register two different login pages.
sorry for making you look through that rather long startup file lol

**Comment by anurse** [comment]
Is there a reason you can't use an Admin role for certain users rather than an entirely separate login system? It's certainly _possible_ to run two separate sets of auth cookies, but it's very complicated (as this thread illustrates ;))

**Comment by yohsii** [comment]
@anurse I needed two separate login pages for two completely separate parts (areas) of the website. You can only achieve this with different schemes.

**Comment by anurse** [comment]
Why do you need separate login pages? Are there separate user databases?

**Comment by yohsii** [comment]
Same database, different identity user.
The pages will have totally different styling, different logic for handling things like claims they really are two different beasts

**Comment by anurse** [comment]
> Same database, different identity user.

So a user would be concurrently logged in as two separate users? One for the Admin area and one for the non-admin area? That seems... odd to me.

**Comment by yohsii** [comment]
Yeah it is and I doubt that'll ever actually happen. I just haven't tested it and I doubt it will work the way I've currently set it up. Anyway it's not a requirement.

**Comment by yohsii** [comment]
Just to clarify, I have two different identity user classes. One is the back office user for the CMS and one is the front-end user with different properties.
I've just tested that you can indeed be logged into both areas at the same time with the same username even though different identity user classes are being used with different user type specific signinmanager.
You wouldn't actually be signed in as two different users in this system

**Comment by anurse** [comment]
> Just to clarify, I have two different identity user classes.

So you have two instances of Identity registered in the app? I'm not sure that actually works. @HaoK do you know?

**Comment by yohsii** [comment]
here's the code
```
if (Configuration.GetValue<bool?>("UseSQLite") ?? false)
            {
                services.AddEntityFrameworkSqlite().AddDbContext<PuckContextSQLite>(optionsLifetime: ServiceLifetime.Transient);
                services.AddDefaultIdentity<PuckUser>(options => { options.SignIn.RequireConfirmedAccount = false; })
                .AddRoles<PuckRole>()
                .AddEntityFrameworkStores<PuckContextSQLite>();
                services.AddTransient<I_Puck_Context>(x => x.GetService<PuckContextSQLite>());
                //add front end db context and identity
                services.AddDbContext<DbContextSQLite>(x => x.UseSqlite(Configuration.GetConnectionString("SQLite")), optionsLifetime: ServiceLifetime.Transient);
                services.AddIdentityCore<User>(options => { options.SignIn.RequireConfirmedAccount = false; })
                .AddRoles<Role>()
                .AddEntityFrameworkStores<DbContextSQLite>();
                services.AddScoped<SignInManager<User>>();
            }
```

so i'm using `AddDefaultIdentity` with one type of user and i'm using `AddIdentityCore` with the second type of user

**Comment by HaoK** [comment]
@yohsii So the main issue you will run into is that only one of the sign in managers can be registered, the other one you will have to manually call the httpcontext.signin methods with the appropriate cookies.  So you want to call AddDefaultIdentity with the main user you want to be signed in, and you can try calling the authentication apis directly for the other user type.

**Comment by yohsii** [comment]
hi @HaoK 
if you look at the code i posted before your last comment, i'm manually registering the SignInManager for the second type of user.
```
services.AddScoped<SignInManager<User>>();
```
i've just tested this and i am able to use both sign in managers for the two different types of user and both can log in just fine.

**Comment by HaoK** [comment]
So it looks like you have gotten things working via ForwardAuthenticate?  I don't think this is something common enough to document as its not something we would recommend people do, nor is it something we are intentionally trying to support (multiple sign in managers).

**Comment by yohsii** [comment]
i reckon this functionality is critical for anybody building a cms or any other similar system which needs more flexibility with regards to security. i'm just glad this works and hope it will continue to work going forward.
anyway this issue is here now for anybody else who finds themselves in this situation.
