### ISSUE TITLE
[SignalR] Allow controlling maximum buffer size on client

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#17797]
## Background and Motivation

We currently allow control over the "maximum buffer size" on the server: https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-3.1&tabs=dotnet#advanced-http-configuration-options

(We derive the PauseWriterThreshold and ResumeWriterThreshold values from that).

However, we don't let the .NET client configure this. We should consider doing so to allow the client better control over backpressure.

This is important for high performance scenarios where the users might be receiving a large batch of data e.g https://github.com/dotnet/aspnetcore/issues/34895 and want to control how much memory is OK to allocate for unprocessed messages.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http.Connections.Client
{
    public class HttpConnectionOptions
    {
+        /// <summary>
+        /// Gets or sets the maximum buffer size for data read by the application before backpressure is applied.
+        /// </summary>
+        /// <remarks>
+        /// The default value is 1MB.
+        /// </remarks>
+        public long TransportMaxBufferSize { get; set; }
+        
+        /// <summary>
+        /// Gets or sets the maximum buffer size for data written by the application before backpressure is applied.
+        /// </summary>
+        /// <remarks>
+        /// The default value is 1MB.
+        /// </remarks>
+        public long ApplicationMaxBufferSize { get; set; }
    }
}
```

## Usage Examples

``` C#
var hubConnection = new HubConnectionBuilder()
                    .WithUrl("http://localhost:5000/chat", o =>
                    {
                        // Set the transport buffer size to 30 MB before yielding
                        o.TransportMaxBufferSize = 1024 * 1024 * 30;
                    })
                    .Build();
```

## Risks

None

Notes:
- This mirrors the properties on the server side, but the naming isn't great. Transport -> transport to application buffer (inbound) and Application -> application to transport (outbound).

**Comment by BrennanConroy** [comment]
Removing milestone to bring back to triage.

We've had another customer report about this.

**Comment by davidfowl** [comment]
There’s 2 work items. Set a default. Make it configurable

**Comment by BrennanConroy** [comment]
Right, and if we backport, we can only backport the default value

**Comment by davidfowl** [comment]
I may take stab at this. We should make sure we have a way to very the memory behavior on our performance lab.

**Comment by BrennanConroy** [comment]
> Right, and if we backport, we can only backport the default value

And also should have an AppContext switch to disable this just in case.

**Comment by davidfowl** [comment]
I'll do this one. @BrennanConroy I'm assuming it's much easier to test this with the new performance infrastructure right?

**Comment by BrennanConroy** [comment]
😶
Not sure about easier currently.

**Comment by davidfowl** [comment]
@BrennanConroy it should also be possible to update the client binaries trivially right 😄

**Comment by BrennanConroy** [comment]
Yeah, adding something like `--load.options.outputFiles <filename>` to the command line should do that.

**Comment by pranavkm** [comment]
API review: We should document that setting this to  `-1` will disable buffering. In addition, we should use the `value` node because it exists. API review noted that the names were poor choices, but they match the server names and it's in our best interest to keep them consistent.

**Comment by davidfowl** [comment]
Using the value node is fine but does it actually show up anywhere?
