### ISSUE TITLE
Investigate why we need dummy targets in Components.Web.JS.npmproj

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#17798]
We have the following three dummy targets in `Components.Web.JS.npmproj`:

https://github.com/aspnet/AspNetCore/blob/2e4dbe0ba35d5b712c60eac9c5acc3f069734bee/src/Components/Web.JS/Microsoft.AspNetCore.Components.Web.JS.npmproj#L24-L27

Without these, we get errors like the following on OSX while packing packages for the template tests:

> /Users/runner/runners/2.160.1/work/1/s/src/Components/Web.JS/Microsoft.AspNetCore.Components.Web.JS.npmproj : error MSB4057: The target "GetTargetPath" does not exist in the project.

We should investigate why this project is missing those targets, and find a better workaround if possible.

**Comment by pranavkm** [comment]
I think it's required because it's referenced by a a regular proj file. We do this in later branches too: https://github.com/aspnet/AspNetCore/blob/master/src/Components/Web.JS/Microsoft.AspNetCore.Components.Web.JS.npmproj#L29. I wouldn't fret too much about this

**Comment by rynowak** [comment]
> We should investigate why this project is missing those targets, and find a better workaround if possible.

`.npmproj` isn't a standard/supported thing, it's something we made. If I had a guess it's our static assets support that requires `GetTargetPath`
