### ISSUE TITLE
Update Razor's Language Server with project system information

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#17799]
In the VSCode scenarios we do this as part of O# by serializing all project level information down into a project.razor.json file. In Visual Studio we'll need to take our in-process data and serialize it down into a project.razor.json file that the Language Server understands. This is dependent on https://github.com/aspnet/AspNetCore/issues/17711

The majority of this work has already been [done ](https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs)and depends on two things
1. A `ProjectSnapshot` representation of a project
1. A place to publish the serialized file

**Comment by NTaylorMullen** [comment]
Did some thinking about this tonight and thought I'd write down a list of requirements for the feature.

1. Project state should be serialized into a format that is already understood by our Language Server. Today in VSCode this is done by the [DefaultProjectChangePublisher](https://github.com/dotnet/aspnetcore-tooling/blob/00d5a4792e62ec8dd2c661a0086f9f4020b91eb4/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs). We'll need to build something similar or share common infrastructure between the two to enable this for VS
1. Project state should be serialized to a similar destination to the one VSCode publishes its to. [This ](https://github.com/dotnet/aspnetcore-tooling/blob/bacd388779180f901b900ef16d955742b8e43777/src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectManager.cs#L288) is how we calculate that path in O#. In VS the project system model is a bit different and operates on things called [rules/subscriptions](https://github.com/dotnet/aspnetcore-tooling/blob/bacd388779180f901b900ef16d955742b8e43777/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs#L73-L78). We have some custom defined rules but for your needs there's probably already a rule defined to monitor the temp obj path in VS' [.NET project system repo](https://github.com/dotnet/project-system/tree/c73075d15a02dfebd8df664759d9dcec9b1fb3e7). For reference we use the [ConfigurationGeneral](https://github.com/dotnet/aspnetcore-tooling/blob/bacd388779180f901b900ef16d955742b8e43777/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs#L78) rule that's [defined in the .NET project system repo](https://github.com/dotnet/project-system/blob/c1a5bb26a42a83500c87529bdb3d47e1fe575001/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/ConfigurationGeneral.xaml) and not in our own. Worse case you can reach out to one of those folks to help you subscribe to the temp path (if it changes we'll need to react accordingly).
1. Project information should only be serialized if the Razor LSP Editor feature flag is enabled. Today this is controlled by the [DefaultLSPEditorFeatureDetector](https://github.com/dotnet/aspnetcore-tooling/blob/00d5a4792e62ec8dd2c661a0086f9f4020b91eb4/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs). The feature detector currently can indicate if a document belongs to a project that supports the LSP editor but does not directly expose a way to say "a project supports the LSP Editor". This is where the bulk of the work in this issue will come from.
1. Assuming the feature flag is enabled, serialization should occur when:
    1. A Razor file has been
        1. Changed (we don't really care if a .cshtml file has been changed).
        1. Removed
        1. Added
        1. Renamed
    1. A project has been
        1. Changed
        1. Removed
        1. Added
        1. Renamed
        1. Built

For the last bullet point all of those should pretty much already be covered by our existing infrastructure. I listed it more as a verification item.

It seems like a lot of work but it's mostly going to be an investigative journey on how to hook everything up. In the end it'll probably be pretty simple. Either way, I envision the bulk of this work being in requirements 2 and 3. There'll probably be a bullet point 5 that we don't know about yet too 😆

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/dotnet/aspnetcore-tooling/pull/1711.
