### ISSUE TITLE
Add basic HTML completion to VS LSP Razor editor

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#17800]
We need to do the work to delegate Razor completion requests over to appropriate projection buffers. The majority of this work will involve working with the LSP platform team to ensure we have the proper APIs to do this.

**Comment by NTaylorMullen** [comment]
@ajaybhargavb this is more hard mode 😄 

You'll need to debug through https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient to find the appropriate API to call.

@tinaschrepfer What API again is the one that LiveShare calls to delegate requests?

**Comment by NTaylorMullen** [comment]
Oh and in order to get the HTML LSP to boot up on our hidden `ITextBuffer` you'll need to locally install @alexgav's branch that adds that support: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/231014

The root of the repo has a Readme.md with instructions for building/installing bits locally. Once installed you'll need to ensure the `ITextBuffer` we create for HTML doesn't get classified as "unsupported" as included in that PR:

```C#
        private bool IsUnsupportedBuffer(ITextBuffer buffer)
        {
            // Process only contained language buffer.
            // TODO: more elegant way of determining that the buffer is a contained language buffer?
            return !(buffer.ContentType.IsOfType(CodeRemoteContentDefinition.CodeRemoteBaseTypeName) && buffer.Properties.ContainsProperty(ContainedLanguageMarker));
        } 
```

Note the `buffer.Properties.ContainsProperty` check that's done. I'm working on the C# side of this equation and that bit me 😄

**Comment by ajaybhargavb** [comment]
d12492edf118463b5de8e091cccce1d1827eb10c
