### ISSUE TITLE
Make VS LSP Client insertable into VS

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#17832]
Today we have a RazorExtension that encompasses all of the Razor functionality needed for VisualStudio. It includes things like LiveShare by class library reference; however, in the case of an LSP client we'll have a few more requirements than just a class library reference. For instance we'll need to have a language grammar, server, configuration switches etc. This issue tracks the work to incorporate those added pieces into something that can be inserted into Visual Studio. This could be the existing RazorExtension or something new.

**Comment by rynowak** [comment]
It would be really great if this could be the same extension.
