### ISSUE TITLE
CS1061 incorrectly identifies File with typo

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#17841]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/853115/cs1061-incorrectly-identifies-file-with-typo.html)._

---
I had a typo in Subscriptions.cshtml but Visual Studio Error List window says it occured in Securities.cshtml.

If helpful, this problem appears to occur when you copy-paste a cshtml file from one folder to another in order to expedite feature development.  Attached is an annotated screenshot, as I imagine nobody in VS Engineering would believe this bug exists without it.

---
#### Visual Studio Feedback System on 12/11/2019, 10:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Taylor Mullen [MSFT] on 12/12/2019, 11:23 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/143521/c48e692a-6258-4ade-947a-d6a2c5ff88ac.html" nodeid="143521">@John Alexander Zabroski</a> did you happen to rename the file at all? Also, would it be possible for you to provide a minimalistic repro with instructions? I'm unable to reproduce on my own box.</p>

#### John Alexander Zabroski on 12/12/2019, 00:08 PM: 

<p>It's unlikely I'll have time soon to build a repro.  However, I copied the parent folder containing Securities.cshtml and renamed that parent folder from "Securities - Copy" to "Reports".  I think I then re-named Securities.cshtml in the new "Reports" folder to Subscriptions.cshtml.  It is also possible I first renamed the cshtml and then renamed the copied folder. Perhaps this is more clear than my original descriptive comment:</p><p>"If helpful, this problem appears to occur when you copy-paste a cshtml file from one folder to another in order to expedite feature development."</p><p>Additionally, if helpful, Razor files in my solution have sometimes lag of up to 5 seconds to activate a context menu.  My disk has 450mb/s read/write capacity.  I plan to test on an NVMe drive later in the week.  I have inquired to VS Engineering if there is Input-Output Anomalies in how Visual Studio watches files, and it would make sense that only some of the anomalies I've filed have been accepted as bugs due to VS Engineers having 5x faster disks.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
This will be addressed by LSPification. Leaving it here to ensure that renaming a document works.

**Comment by allisonchou** [comment]
This should be fixed in the new editor, closing out.
