### ISSUE TITLE
Retrieve traceId

### ISSUE THREAD

**Issue by chniter** [dotnet/aspnetcore#17857]
### Is your feature request related to a problem? Please describe.

I am trying to retrieve the **traceId** from server side that is attached on every HttpRequest.
The Json response look like this:

{"type":"https://tools.ietf.org/html/rfc7235#section-3.1",
"title":"Unauthorized",
"status":401,
"**traceId**":"|a08ab0a-4722acd640681cf6.1.1dfb8ec2_"}

### Describe the solution you'd like
We can retrieve this value from: 
HttpContext.Request.Headers["Request-Id"]
But why isn't the same as **HttpContext.TraceIdentifier** ?

**Comment by davidfowl** [comment]
This is the API: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.id?view=netcore-3.1#System_Diagnostics_Activity_Id

> But why isn't the same as HttpContext.TraceIdentifier ?

There are a couple of reasons: 
- `HttpContext.TraceIdentifier` existed long before Activity did
- The server id and Activity.Id can be different, for example flowing the Id from IIS or http.sys into the application code.
- Activity is general purpose and not tied to ASP.NET Core so we want libraries to be able to get the current activity without being tied to ASP.NET Core APIs (in some cases).

That said, we should figure out how to stash the `TraceIdentifier` on the activity.

**Comment by JunTaoLuo** [comment]
Sounds like this issue has been answered.
