### ISSUE TITLE
Build yields warning CS0649: Field 'HttpApiTypes.HTTP_REQUEST_PROPERTY_ST REAM_ERROR.ErrorCode'

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/aspnetcore#17885]
### Describe the bug
This is build time related and I understand can be expected behaviour and trade-off.
After the #17645 changes (`Expose Http.Sys's Http/2 Reset error code API`) the build of the project yields a warning now:

> Build succeeded.
>
> C:\..\AspNetCore\src\Shared\HttpSys\NativeInterop\HttpApiTypes.cs(76,27): warning CS0649: Field 'HttpApiTypes.HTTP_REQUEST_PROPERTY_ST REAM_ERROR.ErrorCode' is never assigned to, and will always have its default value 0 [C:\...\AspNetCore\src\Shared\test\Shared.Tests\Mi crosoft.AspNetCore.Shared.Tests.csproj]
    1 Warning(s)
    0 Error(s)
```
### To Reproduce

```bash
cd AspNetCore
git pull origin master
.\build.cmd
```

### Further technical details

 .NET Core Runtime version 5.0.0-alpha.1.19562.8

**Comment by dougbu** [comment]
We made a focused effort to remove all build warnings seen in this repo a few months ago. This issue went away as part of that, if not before.
