### ISSUE TITLE
AspNet Core 3.1 Razor compilation extremely slow (dozen of minutes) for a view with big static html table

### ISSUE THREAD

**Issue by agrinei** [dotnet/aspnetcore#17890]
I've updated an asp.net core 2.2 mvc website to core 3.1 and found razor compilation extremely slow. I'm talking dozen of minutes! After a couple of hours I've found the problem: I had a 5Mb razor view with a big static html table containing 9300 rows. I know this may not be a common scenario but the performance degradation - comparing to netcore 2.2 - is not acceptable and certainly deserves improvement.

I was able to reproduce just creating a new asp.net core 3.1 mvc project and adding the html table to the Home/Index.cshtml

- ASP.NET Core version: 3.1
- Visual Studio 2019 version 16.4.1

`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by rynowak** [comment]
@ajaybhargavb

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@ajaybhargavb can you please look into this, as we may need to patch something here? Thanks!

**Comment by ajaybhargavb** [comment]
Investigating

**Comment by ajaybhargavb** [comment]
After some perf investigation, I've identified some hot spots in the new syntax tree,
![image](https://user-images.githubusercontent.com/1579269/70951241-c1718380-2017-11ea-92c5-cd41289abd85.png)

Although, some perf impact might be unavoidable due to the fact that the new syntax tree now has a deeper understanding of HTML structures, I'll investigate more and see if there are any high impact low hanging fruits that we can optimize.

**Comment by ajaybhargavb** [comment]
@agrinei, thanks for the report. You can unblock yourself in the mean time by doing one of the following,

#### Option 1
Move the large static table to a separate .html file and then do,
```C#
@Html.Raw(System.IO.File.ReadAllText("Path/to/table.html"))
```

#### Option 2
Move the contents inside a script tag and embed it as a string,
```html
<div id="mytable"></div>
<script>
    var tabledata = `
<table>
  <tr>...</tr>
  <tr>... </tr>
  ...
</table>
`;

    document.getElementById('mytable').innerHTML = tabledata;
</script>
```

**Comment by agrinei** [comment]
Thank you for the quick response! I've just left a link to download the table.

If you're not able to improve performance significantly maybe you could add an attribute to make the razor parser consider that part of the view as a single html node:

<table asp-single-html-node="true">
(...)
</table>

**Comment by moxplod** [comment]
I am seeing this as well. Moved from 2.2 to 3.1.
In my case for a much simpler Razor page. Taking at least 30+ seconds to load a page after making some minor changes to the razor page.

**Comment by mkArtakMSFT** [comment]
@moxplod given that you're facing this issue with a simpler scenario, can you please also share a repro project?

**Comment by moxplod** [comment]
Hi @mkArtakMSFT here is a page load time - 18ms when razor is compiled. 
And I add single whitespace in the razor page and refresh, it takes around 10.06s in most cases. Some cases I have seen much higher. Trying to figure out how to send you a repro project.

![image](https://user-images.githubusercontent.com/4554395/74908368-8b7bb300-536a-11ea-98f9-64ee8bfc88f6.png)

**Comment by ajaybhargavb** [comment]
@moxplod's issue sounds more related to Razor runtime compilation than the parser. @pranavkm thoughts?

**Comment by pranavkm** [comment]
@moxplod, do you have [runtime compilation](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#opt-in-to-runtime-compilation) set up?

**Comment by moxplod** [comment]
@pranavkm That was definitely the issue. Adding runtime compilation brought down that time from 10+ seconds to 100ms!
Thank you so much.

**Comment by andreweberle** [comment]
@moxplod I take it you added this to your startup file
`services.AddRazorPages().AddRazorRuntimeCompilation();`

**Comment by moxplod** [comment]
> @moxplod I take it you added this to your startup file
> `services.AddRazorPages().AddRazorRuntimeCompilation();`

Yes. that is what was missing.
