### ISSUE TITLE
Asp.Net Core mvc error : rzc discover exited with code -2147450749.

### ISSUE THREAD

**Issue by Mahdi-Mousawi** [dotnet/aspnetcore#17897]
### Describe the bug
When I build my asp.net core 3.1 MVC project I get this error:
`rzc discover exited with code -2147450749 in line 99`  

and this is the code of line 99 in Microsoft.Net.Sdk.Razor.CodeGeneration.targets file :
```
99 >>  <RazorTagHelper
      Debug="$(_RazorDebugTagHelperTask)"
      DebugTool="$(_RazorDebugTagHelperTool)"
      ToolAssembly="$(_RazorToolAssembly)"
      UseServer="$(UseRazorBuildServer)"
      ForceServer="$(_RazorForceBuildServer)"
      PipeName="$(_RazorBuildServerPipeName)"
      Version="$(RazorLangVersion)"
      Configuration="@(ResolvedRazorConfiguration)"
      Extensions="@(ResolvedRazorExtension)"
      Assemblies="@(RazorReferencePath)"
      ProjectRoot="$(MSBuildProjectDirectory)"
      TagHelperManifest="$(_RazorTagHelperOutputCache)">
      <Output
        TaskParameter="TagHelperManifest"
        ItemName="FileWrites"/>
    </RazorTagHelper>
```

I really need to fix this bug because when I run `Add-Migration` in package manager console I get the error : `Build Failed`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This error indicates a missing runtime. The build output, actually contains the message about the specific runtime missing.

**Comment by mkArtakMSFT** [comment]
We will try to document how to investigate this error, to make it simpler going forward.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
