### ISSUE TITLE
AddDefaultIdentity removed from Identity.UI 3.1.0?

### ISSUE THREAD

**Issue by bhalicki** [dotnet/aspnetcore#17912]
AddDefaultIdentity appears to have been removed from Microsoft.AspNetCore.Identity.UI v3.1.0.  Only solution was to revert to v3.0.0.  Can you please confirm and what alternative solution is?  Sample source code in AspNetCore.Docs appears to be referencing v3.0.0.

**Comment by andrew-vdb** [comment]
Its there,
![image](https://user-images.githubusercontent.com/12871379/70995534-10c7ba80-20d1-11ea-8a9b-50939530da2c.png)

If there is question, why is that method on Microsoft.AspNetCore.Identity.UI, but that separate thread i guess

**Comment by NeilMcKechnie** [comment]
Yes but only if you use the soon-to-be-obsolete icrosoft.AspNetCore.Mvc.IHostingEnvironment. If you upgrade instead to Microsoft.Extensions.Hosting.IWebHostingEnvironment, then AddDefaultIdentity is gone.

![Capture](https://user-images.githubusercontent.com/8440886/71314555-138f1c00-23ff-11ea-9787-61607c9fd2d7.PNG)

**Comment by blowdart** [comment]
This feels like either an intellisense bug or a package mess. Can you share your packages.json?

**Comment by avisser** [comment]
I'm seeing the same thing. Not sure if this helps, but in Rider on OSX Identity.UI v3.1.0 won't open in the Assembly browser. v3.0.0 opens fine and I can browse all the classes in the assembly. Maybe something got biffed in the build?

**Comment by NeilMcKechnie** [comment]
Hmmm, not sure what changed in my environment but it is working now, using ASP.Net Core 3.1 and Microsoft.Extensions.Hosting.IWebHostingEnvironment .
