### ISSUE TITLE
Add IServiceProvider argument to HttpClientFactoryServiceCollectionExtensions.AddHttpClient's configureClient argument

### ISSUE THREAD

**Issue by Pzixel** [dotnet/aspnetcore#17921]
### Is your feature request related to a problem? Please describe.

My current problem is I'm unable to fully use DI because I'm have to create dependencies in controllers.

Assume we have following controller

```cs
ctor(IHttpClientFactory clientFactory, MyTypedClientSettings clientSettings) { ... }

[HttpGet]
public async Task<IActionResult> GetSome() 
{
    var httpClient = this._clientFactory.CreateClient();
    client.BaseAddress = clientSettings.BaseAddress;
    client.DefaultRequestHeaders.Authorization = GetAuthHeaders(this.HttpContext);
    var myClient = new MyTypedClient(httpClient);
    return Ok(await myClient.PerformGetSomeRequest());
}
```

We need to perform some external http request but we also need some context about our own currently executing request.

The problem as you can easily see is that I have to create some dependencies in controller. Why? Because line `lient.DefaultRequestHeaders.Authorization = GetAuthHeaders(this.HttpContext);` cannot be expressed in DI

### Describe the solution you'd like
I think I'd like to have something like that:

```cs
serviceCollection.                
    .AddHttpClient<MyTypedClient, MyTypedClient>((client, serviceProvider) =>
    {
        client.BaseAddress = serviceProvider.GetService<MyTypedClientSettings>().BaseUri;
        client.DefaultRequestHeaders.Authorization = GetAuthHeaders(serviceProvider.GetService<IHttpContextProvider>().HttpContext);
    })
    .SetHandlerLifetime(TimeSpan.Zero)
```

It's a bit tricky but the idea is following: you set a zero timespan thus new HttpClient gets created for each new request (basically, it's how we make it transient). Each client gets its headers filled via context they get from `serviceProvider`. And then this dependency gets injected in the controller.

In the end I'd like to use it like this:

```cs
ctor(MyTypedClient myClient) { ... }

[HttpGet]
public async Task<IActionResult> GetSome() => Ok(await myClient.PerformGetSomeRequest());
```
Which is clearly better than what we had when we started.

Maybe there is a way to do that today but I'm unaware of any.

**Comment by Pzixel** [comment]
I'm not sure which name to choose for this issue. My problem is quite narrow (I just need to copy some request headers from request to httpclient), but the solution may be broader.

**Comment by stack111** [comment]
Not sure if you worked around this issue. In general I would suggest you to use a handler life which is greater than 0. The idea is you want to benefit from the connection pooling and concurrent http requests right? If that is the case, why not implement as:

`MyTypedClient.PerformGetSomeRequest(Request.Headers)`

Just an idea :).

**Comment by BrennanConroy** [comment]
That method already exists https://source.dot.net/#Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs,156
