### ISSUE TITLE
bug(spa): poor Angular messaging

### ISSUE THREAD

**Issue by cpboyd** [dotnet/aspnetcore#17925]
### Describe the bug
When there's a compilation error, the .NET server will simply report a timeout.

### To Reproduce

Use the Angular starter project and simply modify the project to not compile.

### Further technical details
- ASP.NET Core version:
**3.1.100**
- Include the output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
**Visual Studio 16.4.1**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will consider looking into this during 5.0 release.
However, we will happily consider a community PR for this. So feel free to send one if you want.

**Comment by cpboyd** [comment]
Just to clarify, the issue occurs when Angular compilation fails (not .NET).

The Angular error shows in the command prompt, but it was kind of confusing to see a timeout error in the browser.

I guess it may not be a "bug" per se, since effectively the Angular server doesn't respond.

It'd just be nice if the SPA extensions could provide a more helpful error message than the vague timeout, which probably leads to reports like #17607

**Comment by cpboyd** [comment]
Another related point: "compiling" messages (probably Ivy specific) are marked in the command prompt with a red "fail", even though they're just Angular denoting progress.

Likewise, an error specifying to clear `node_modules` never gets mentioned in the command prompt at all.

The timeout message just appears, with no information on how to clear the error.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
