### ISSUE TITLE
React Authentication & Identity Server template

### ISSUE THREAD

**Issue by BartoGabriel** [dotnet/aspnetcore#17922]
### Describe the bug
In the template it is configured so that the token is refreshed automatically, by the oidc-client library.

The problem is that the library does it in a separate IFrame, and when it calls notifySubscribers (in AuthorizeService.js), it does not notify, since within the IFrame the variable this._callbacks is empty.

### To Reproduce
I recommend setting the Identity Server client in AccessTokenLifetime = 60. To make the test easier. Change the username, and note that it does not change on the client aplication.

### Solution
A solution that will maintain the same code. It is to change the function ensureUserManagerInitialized in the AuthorizeService class. Settiating so that it does not refresh automatically and adding an event.
```javascript
async ensureUserManagerInitialized() {
	if (this.userManager !== undefined) {
		return;
	}

	let response = await fetch(ApplicationPaths.ApiAuthorizationClientConfigurationUrl);
	if (!response.ok) {
		throw new Error(`Could not load settings for '${ApplicationName}'`);
	}

	let settings = await response.json();
	settings.automaticSilentRenew = false;  //SET TO FALSE
	settings.includeIdTokenInSilentRenew = true;
	settings.userStore = new WebStorageStateStore({
		prefix: ApplicationName
	});

	this.userManager = new UserManager(settings);

	this.userManager.events.addUserSignedOut(async () => {
		await this.userManager.removeUser();
		this.updateState(undefined);
	});

	//ADD NEXT LINES
	this.userManager.events.addAccessTokenExpired(async () => {
		await this.signIn();
	});
}
```

**I think that a better solution would be to handle all this with the React context API.**

### Further technical details
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@BartoGabriel thanks for contacting us.

@leastprivilege Is the suggested proposal a better way to handle the renew?

**Comment by pranavkm** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our Triage Process writeup.
