### ISSUE TITLE
Consume the Mono WASM DebuggerProxy as a binary

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#17948]
The Mono build produces a binary of the DebuggerProxy. We can package it up from the aspnet/blazor repo and consume it rather than building it as source in our repo.

**Comment by captainsafia** [comment]
@pranavkm During today's sync, we discussed asking the Mono team to package the proxy so that we can consume it in the same way we consume other things.

Let's track changing how the mono proxy is consumed in this issue.

cc: @danroth27 @mkArtakMSFT @SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
Closing as we have a separate issue tracking this.
