### ISSUE TITLE
🎅 🎄  Happy Holidays, everyone! Responses for issues may be delayed till early January

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#17955]
As the holidays are approaching, many of our team members are taking time off to get some rest.
Because of this, responses to new issues, PRs, and comments may be delayed till early next year.

Happy Holidays!

**Comment by zaranetCore** [comment]
Have a nice holiday for You

**Comment by Pilchie** [comment]
Most people are back now, so closing this.
