### ISSUE TITLE
Angular Template - Component styles do not get applied after ng build --prod (publish)

### ISSUE THREAD

**Issue by the-real-coder** [dotnet/aspnetcore#17954]
Steps to reproduce:

1. Create a new ASP.NET Core Angular application with .NET Core SDK 3.1 (Visual Studio 2019)
2. Add a new CSS file (home.component.css) to the home component with some basic style
3. Update home.component.ts to include the newly added CSS file
4. Run the application locally, style from home.component.css gets applied to the home.component
5. Publish and deploy the application, style from home.component.css does not apply and additionally none of the default styles from the nav-menu.component.css gets applied in the deployed package

I have tried the same with .NET Core SDK 3.0 and got the same result.

I'm using the default template from Visual Studio 2019 and the only updates are the ones described in step 2 and 3 above. 

**Issue # 2**
Default template adds 2 body tags to the HTML. There is one in index.html and another in app.component.html

**Comment by the-real-coder** [comment]
Do I need to install nodejs on the server where the ASP.NET Core Angular 8 application is deployed? I deployed the web application package on my development machine IIS and I can get the styles working but when I deploy the same package on the server (does not have nodejs installed) styles do not get applied as described in the issue above.

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem. 

> Do I need to install nodejs on the server where the ASP.NET Core Angular 8 application is deployed? 

You shouldn't need nodejs on the server.
