### ISSUE TITLE
Unable to Inject Dependencies to SignalR Core Hub (Microsoft.AspNetCore.SignalR.Hub)

### ISSUE THREAD

**Issue by aneeshsiva77** [dotnet/aspnetcore#17977]
We are currently using Notification Hub (Microsoft.AspNetCore.SignalR.Hub), When the Hub receives a message form the client, we needs to save the message to a database. For that we need to inject the dbcontext / repositories to the hub.
Is it possible to inject dependency to a SignalR hub (We tried the HubContext option but drop the plan because of the unavailability of the methods OnConnectedAsync(), OnDisconnectedAsync and HubCallerContext)

**Comment by davidfowl** [comment]
Yes you can.

**Comment by aneeshsiva77** [comment]
Hi @davidfowl Thanks Much for the reply. Can you please share some link / documentation that explain DI using SignalR Hub

**Comment by davidfowl** [comment]
It works like anything else in ASP.NET Core. Add your dependencies to the ISeviceCollection and then declare your hub with a constructor that takes the dependency.

We don't have a doc explicitly for this though, it makes sense to add one as there exists ones for MVC.

**Comment by renanliberato** [comment]
I found the documentation page from ASP.NET Signalr docs that you might be referring to: https://docs.microsoft.com/en-us/aspnet/signalr/overview/advanced/dependency-injection#simple-dependency-injection-in-signalr

**Comment by renanliberato** [comment]
I would like to help creating this page. I'm using SignalR quite a lot recently, so I'd be happy to contribute to it. Could I give some suggestions here like where to attach this page and which topics to have?

**Comment by BrennanConroy** [comment]
We'd love contributions! If you'd like you can write a rough draft for the page and paste it as a comment which we can turn into a doc, or if you'd like you can make a PR with the whole document written out and we'd be happy to review it.

**Comment by MagicPelikan** [comment]
HI everyone. I'm using asp net core 3.1 but I can't inject a service into a class that inherits from Hub.
I have something like:
```
public class MyHub : Hub
{
	private IMyCustomService _myCustomService;
		
	public MyHub(IMyCustomService myCustomService)
	{
		_myCustomService = myCustomService;
	}
	
	
public async Task SendMessage(string user, string message)
	{
		// I want to do something here with _myCustomService...
		
		_myCustomService.Method(....);
		
		await Clients.All.SendAsync("ReceiveMessage", user, message);
	}
}
```
Then in my Startup.cs I have something like:
```
public void ConfigureServices(IServiceCollection services)
{
	...
	services.AddSignalR();
	...
}


public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	...
	endpoints.MapHub<MyHub>("/testHub");
	...
}
```

I'm getting this error:
**System.InvalidOperationException: A suitable constructor for type 'BlazorSignalRApp.Server.Hubs' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.**

I feel I'm missing something when DI is trying to create an instance of MyHub but I can't figure out what ?

Thanks a lot! And stay home please :)

**Comment by SereetsiKC** [comment]
Hey Guys, am having a similar issue (well sort of), am using ninject in a .netcore Api. everything else works well with dependency injection until I try to use my Repository in a SignalR hub.

System.InvalidOperationException: Unable to resolve service for type 'Kopanos.Solutions.Components.Api.ModelsApi.Interfaces.IChatApi' while attempting to activate 'Kopanos.Solutions.Components.Api.Hubs.UserHub'.     at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)   

If i try and addScoped the solution doesn't run.

is there a way i can override DefaultDependencyInjection in SignalR V3 like it can be done on V2 with .Net 4

**Comment by davidfowl** [comment]
Ninject works with ASP.NET Core? Can you show me the code?

**Comment by SereetsiKC** [comment]
public class Startup
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="configuration"></param>
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        /// <summary>
        /// 
        /// </summary>
        public IConfiguration Configuration { get; }
        private readonly AsyncLocal<Scope> scopeProvider = new AsyncLocal<Scope>();
        private IKernel Kernel { get; set; }

        private object Resolve(Type type) => Kernel.Get(type);
        private object RequestScope(IContext context) => scopeProvider.Value;

        private sealed class Scope : DisposableObject { }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="services"></param>
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
           
            var appSettings = this.Configuration.GetSection("AppSetting").Get<AppSetting>();

            var activator = new HangfireJobActivator(this.Configuration.GetSection("ConnectionStrings").GetSection("DbConnection").Value, this.Configuration);
            services.AddHangfire(x =>
            {
                x.UseSqlServerStorage(this.Configuration.GetSection("ConnectionStrings").GetSection("DbConnection").Value);
                x.UseActivator(activator);
            });
            services.AddHangfireServer();

            ApiConfig.Configurations.JWTConfigurations(services, appSettings);
            services.AddHttpContextAccessor();
            services.AddControllers().AddJsonOptions(opts => opts.JsonSerializerOptions.PropertyNamingPolicy = null);
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll", p =>
                {
                    p.WithOrigins("http://localhost:4200", "http://localhost:5000")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials();
                });
            });

            services.AddApiVersioning(x =>
            {
                x.AssumeDefaultVersionWhenUnspecified = true;
                x.DefaultApiVersion = new ApiVersion(1, 0);
                x.ReportApiVersions = true;
            });

            services.AddSwaggerGen(setupAction =>
            {
                setupAction.SwaggerDoc("CaseFilingOpenAPISpecification", new Microsoft.OpenApi.Models.OpenApiInfo()
                {
                    Title = "Case Filing Storage API",
                    Version = "1",
                    Description = "",
                    Contact = new Microsoft.OpenApi.Models.OpenApiContact()
                    {
                        Email = "sereetsikc@gmail.com",
                        Name = "Kopano Sereetsi",
                        Url = new Uri("https://github.com/SereetsiKC")
                    },
                    License = new Microsoft.OpenApi.Models.OpenApiLicense()
                    {
                        Name = "Kopanos Solutions",
                        Url = new Uri("https://opensource.org/licenses/MIT")
                    }
                });
                var xmlCommentsFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlCommentsFullPath = Path.Combine(AppContext.BaseDirectory, xmlCommentsFile);
                setupAction.IncludeXmlComments(xmlCommentsFullPath);
            });
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<UserInfoInMemory>();
            services.AddRequestScopingMiddleware(() => scopeProvider.Value = new Scope());
            services.AddCustomControllerActivation(Resolve);
            services.AddCustomViewComponentActivation(Resolve);
            //services.AddScoped<IChatApi, ChatApi>();
            services.AddSignalR();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            this.Kernel = this.RegisterApplicationComponents(app);
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSerilogRequestLogging();
            app.UseMiddleware(typeof(ErrorHandlingMiddleware));
            app.UseHangfireDashboard();
            app.UseCors("AllowAll");
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<ChatHub>("/ChatHub");
                endpoints.MapHub<UserHub>("/DirectMessages");
            });
            app.UseSwagger();
            app.UseSwaggerUI(setupAction =>
            {
                setupAction.SwaggerEndpoint("swagger/CaseFilingOpenAPISpecification/swagger.json", "Case Filing Storage API");
                setupAction.RoutePrefix = "";

            });
            var serviceProvider = app.ApplicationServices;
            this.Kernel.Bind<IHubContext<ChatHub>>().ToMethod(context => serviceProvider.GetService<IHubContext<ChatHub>>());
            this.Kernel.Bind<IHubContext<UserHub>>().ToMethod(context => serviceProvider.GetService<IHubContext<UserHub>>());
        }

        private IKernel RegisterApplicationComponents(IApplicationBuilder app)
        {
            var kernel = new StandardKernel();

            // Register application services
            foreach (var ctrlType in app.GetControllerTypes())
            {
                kernel.Bind(ctrlType).ToSelf().InScope(RequestScope);
            }

            // This is where our bindings are configurated
            WebConfig.Configurations.SystemConfigurations(kernel, this.Configuration);
            // Cross-wire required framework services
            kernel.BindToMethod(app.GetRequestService<IViewBufferScope>);

            return kernel;
        }
    }

**Comment by SereetsiKC** [comment]
public static class Configurations
    {

        public static void DataBaseServices(IKernel kernel,IConfiguration configuration)
        {
            kernel.Bind<Microsoft.AspNetCore.Http.IHttpContextAccessor>().To(typeof(Microsoft.AspNetCore.Http.HttpContextAccessor));
            var unitOfWorkBuilder = new UnitOfWorkBuilder(globalConfig.SetupConfig.DbConnection("DbConnection", configuration));
            DbContextLoaders(kernel, configuration);
            kernel.Bind<IUnitOfWork>().ToMethod(x => unitOfWorkBuilder.Build(kernel.Get<IContextLoader>())).InRequestScope();
            kernel.Bind(typeof(IRepository<,>)).To(typeof(BaseRepository<,>));
        }

        internal static void DbContextLoaders(IKernel kernel, IConfiguration configuration)
        {
            kernel.Bind(typeof(IContextLoader)).To(typeof(DefaultContextLoader));
            ServiceConfigurations(kernel, configuration);
        }

        internal static void ServiceConfigurations(IKernel kernel, IConfiguration configuration)
        {
            config.Configurations.IntegrationConfigurations(kernel, configuration);
            Loggers.Configurations.Configurations.ServiceConfigurations(kernel, configuration);
            kernel.Bind(typeof(IAuthentication)).To(typeof(Authentication));
            kernel.Bind(typeof(IApiUserPrinciples)).To(typeof(ApiUserPrinciples));
            kernel.Bind(typeof(IChatApi)).To(typeof(ChatApi));
            kernel.Bind<IModelsApi<Message, int>>().To<ChatApi>();
            kernel.Bind(typeof(ILookupApi)).To(typeof(LookupApi));
            kernel.Bind(typeof(IEmailApi)).To(typeof(EmailApi));
            kernel.Bind(typeof(ISettingsApi)).To(typeof(SettingsApi));
            kernel.Bind(typeof(IUserApi)).To(typeof(UserApi));
            kernel.Bind(typeof(IModelsApi<Domain.Models.Authentication.Users, Guid>)).To(typeof(UserApi));
            kernel.Bind(typeof(ICompanyApi)).To(typeof(CompanyApi));
            kernel.Bind(typeof(IModelsApi<Domain.Models.Administration.Company, Guid>)).To(typeof(CompanyApi));

            //kernel.Bind(typeof(UserInfoInMemory)).To(typeof(UserInfoInMemory)).InSingletonScope();

            var settings = configuration.GetSection("AppSetting").Get<AppSetting>();
            kernel.Bind(typeof(IOptions<AppSetting>)).To(typeof(AppConfigOption<AppSetting>))
            .WithConstructorArgument(settings);

            var hangFireConfigurations = configuration.GetSection("HangFireConfigurations").Get<HangFireConfigurations>();
            kernel.Bind(typeof(IOptions<HangFireConfigurations>)).To(typeof(AppConfigOption<HangFireConfigurations>))
            .WithConstructorArgument(hangFireConfigurations);


        }
    }

**Comment by SereetsiKC** [comment]
All My services configs are done on the Configurations class

**Comment by SereetsiKC** [comment]
as you notice even the Singleton has to be added Configure method of the startup class. Had the same issue as am having with the ChatApi only Diff is that i got the Singleton to work with default dependency injection just cant get the solution to run if i include the ChatApi

**Comment by SereetsiKC** [comment]
My hub is as below 

namespace Kopanos.Solutions.Components.Api.Hubs
{
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class UserHub : Hub
    {

        private readonly UserInfoInMemory _userInfoInMemory;
        private readonly IChatApi chatApi;

        public UserHub(UserInfoInMemory userInfoInMemory, IChatApi chatApi, IHttpContextAccessor httpContextAccessor)
        {
            _userInfoInMemory = userInfoInMemory;
            chatApi.httpContextAccessor = httpContextAccessor;
            this.chatApi = chatApi;
        }

        public async Task Leave()
        {
            _userInfoInMemory.Remove(Context.UserIdentifier);
            await Clients.AllExcept(new List<string> { Context.ConnectionId }).SendAsync("UserLeft", Context.UserIdentifier);
        }

        public async Task Join()
        {
            if (!_userInfoInMemory.AddUpdate(Context.UserIdentifier, Context.ConnectionId))
            {
                // new user

                var list = _userInfoInMemory.GetAllUsersExceptThis(Context.UserIdentifier).ToList();
                await Clients.AllExcept(new List<string> { Context.ConnectionId }).SendAsync("NewOnlineUser", _userInfoInMemory.GetUserInfo(Context.UserIdentifier));
            }
            else
            {
                // existing user joined again

            }

            await Clients.Client(Context.ConnectionId).SendAsync("Joined", _userInfoInMemory.GetUserInfo(Context.UserIdentifier));

            await Clients.Client(Context.ConnectionId).SendAsync("OnlineUsers", _userInfoInMemory.GetAllUsersExceptThis(Context.UserIdentifier));
        }

        public Task GetOnlineUsers(string targetUserName)
        {
            return Clients.Client(Context.ConnectionId).SendAsync("OnlineUsers", _userInfoInMemory.GetAllUsersExceptThis(Context.UserIdentifier));
        }

        public Task SendDirectMessage(Message message, string targetUserName)
        {
            var results = chatApi.Save(message);
            if (results.Succeeded)
            {
                var userInfoSender = _userInfoInMemory.GetUserInfo(Context.UserIdentifier);
                var userInfoReciever = _userInfoInMemory.GetUserInfo(targetUserName);
                if (userInfoReciever != null)
                {
                    return Clients.Client(userInfoReciever.ConnectionId).SendAsync("SendDirectMessage", message, userInfoSender);
                }
            }

            return Task.CompletedTask;
        }
    }
}

**Comment by davidfowl** [comment]
So you have this commented out             

// services.AddScoped<IChatApi, ChatApi>();

That's likely the reason why it's not working.

SignalR doesn't know anything about ninject in the above configuration.

I see you're wiring up MVC somehow:

```
services.AddCustomControllerActivation(Resolve);
services.AddCustomViewComponentActivation(Resolve);
```

You also need one of those for SignalR if you want ninject to resolve it.

**Comment by SereetsiKC** [comment]
yes I need that for signalr but I don't know which class to override, initial question

**Comment by SereetsiKC** [comment]
I commented that out because the solution fails to run without any errors

**Comment by BrennanConroy** [comment]
You can inject your own `IHubActivator<THub>` to customize Hub creation.

**Comment by SereetsiKC** [comment]
cool, let me work on that will give feedback in few

**Comment by SereetsiKC** [comment]
Epic failure 

  public class SimpleInjectorHubActivator<T> : IHubActivator<T> where T : Hub
    {

        private readonly IKernel kernel;
             
        private Scope ownedScope;
        public SimpleInjectorHubActivator(IKernel kernel)
        {
            this.kernel = kernel;
        }

        public T Create()
        {
            return this.kernel.Get<T>();
        }

        public void Release(T hub)
        {
            EndScope();
        }

        private void EndScope()
        {
            this.ownedScope?.Dispose();
        }
    }

**Comment by SereetsiKC** [comment]
@BrennanConroy do you have a sample piece of code i can relate to?

**Comment by BrennanConroy** [comment]
The only "example" I have is the current implementation https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/server/Core/src/Internal/DefaultHubActivator.cs
What issue(s) did you hit?

**Comment by SereetsiKC** [comment]
So after working my ( | ) off, got around my issue by using the same scenario one would use with hangfire job activators...the above wont really work because HubActivators are internal classes.

my HangFire activator is as below

public class HangfireJobActivator : JobActivator
    {
        public IKernel Kernel { get; private set; }
        public HangfireJobActivator(IConfiguration configuration)
        {
            CreateKernel(configuration);
        }

        public void Bind(Type from, Func<IContext, object> to)
        {
            Kernel.Bind(from).ToMethod(to);
        }

        private void CreateKernel(IConfiguration configuration)
        {
            this.Kernel = new StandardKernel();
            try
            {
                Configurations.DataBaseServices(this.Kernel, configuration);
                this.Kernel.Bind<Func<IKernel>>().ToMethod(ctx => () => this.Kernel);
            }
            catch
            {
                Kernel.Dispose();
                throw;
            }
        }

        public override object ActivateJob(Type type)
        {
            return this.Kernel.Get(type);
        }
    }

So to get around using Ninject on SignalR 3 I created a class below

public class SignalRConfigurations
    {
        private IKernel Kernel { get; set; }
        public SignalRConfigurations(IConfiguration configuration)
        {
            CreateKernel(configuration);
        }

        private void CreateKernel(IConfiguration configuration)
        {
            this.Kernel = new StandardKernel();
            try
            {
                Configurations.DataBaseServices(this.Kernel, configuration);
                this.Kernel.Bind<Func<IKernel>>().ToMethod(ctx => () => this.Kernel);
            }
            catch
            {
                Kernel.Dispose();
                throw;
            }
        }

        public object Activate(Type type)
        {
            return this.Kernel.Get(type);
        }
    }

On my hub i have the below peace of code 

  [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class UserHub : Hub
    {
        private readonly UserInfoInMemory _userInfoInMemory;
        private readonly IChatApi chatApi;
        public UserHub(IConfiguration configuration, IHttpContextAccessor httpContextAccessor)
        {
            var activator = new SignalRConfigurations(configuration);
            this._userInfoInMemory = (UserInfoInMemory)activator.Activate(typeof(UserInfoInMemory));
            var chat = (IChatApi)activator.Activate(typeof(IChatApi));
            chat.httpContextAccessor = httpContextAccessor;
            this.chatApi = chat;
        }
   }

**Comment by SereetsiKC** [comment]
its not the best out there but i have less headache
