### ISSUE TITLE
.... hello-world-tutorial/modify 

### ISSUE THREAD

**Issue by scalablecory** [dotnet/aspnetcore#17974]
_From @pete-r61 on Tuesday, December 17, 2019 8:59:45 PM_

Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows 10

Hello, 
Just getting started with basics, I got stuck already after the first page. Below some data. Hope someone can help
Regards P.

**After copy/paste**
```
Index.cshtml

@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Hello, world!</h1>
    <p>The time on the server is @DateTime.Now</p>
</div>
```
**Error Message:**
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.

myWebApp.Pages.Pages__ViewStart.ExecuteAsync() in _ViewStart.cshtml, line 4

**Stack trace**
NullReferenceException: Object reference not set to an instance of an object.

    myWebApp.Pages.Pages__ViewStart.ExecuteAsync() in _ViewStart.cshtml

            ViewData["Title"] = "Home page";
    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderViewStartsAsync(ViewContext context)
    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
    Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
    Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

_Copied from original issue: dotnet/core#4010_

**Comment by pranavkm** [comment]
Hi @pete-r61, thanks for trying out ASP.NET Core. The error message you're seeing suggests that you started from MVC with controllers template rather than a Razor Pages template. Could you ensure you have

a) The most recent build of the .NET Core SDK installed: https://download.visualstudio.microsoft.com/download/pr/639f7cfa-84f8-48e8-b6c9-82634314e28f/8eb04e1b5f34df0c840c1bffa363c101/dotnet-sdk-3.1.100-win-x64.exe? You can run `dotnet --info` which should say that the SDK is 3.1.100 or newer.

b) You started from the `webapp` template? If you run `dotnet new --help`, it should include this line:

```
ASP.NET Core Web App                              webapp                   [C#]              Web/MVC/Razor Pages
```

If you've verified both of these are correct and you continue seeing this error, we can try and resolve it further.
