### ISSUE TITLE
Add HttpProtocols helper class

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#17972]
Basically the same as `HttpMethods`, except for HTTP protocol version, e.g. HTTP/1.1, HTTP/2, `HttpProtocols.IsHttp11(protocol)`, `HttpProtocols.IsHttp20(protocol)`, etc.

Right now the only way to check the protocol version is magic strings, e.g. when request is HTTP/2 then `HttpRequest.Protocol == "HTTP/2"`

**Comment by JamesNK** [comment]
Maybe have a different name because there is already a `HttpProtocols` enum in Kestrel.

**Comment by Tratcher** [comment]
How about HttpRequest extension methods to go with it?
`if (context.Request.IsHttp2())`

**Comment by JamesNK** [comment]
I don't feel strongly either way about adding extension methods.

I expect the user's of this feature would be app framework developers, so the convenience of extension methods is probably not needed. Applications are typically agnostic to the HTTP protocol version (REST doesn't care about 1.1 vs 2) or they are using an app framework that does the check for them (gRPC)
