### ISSUE TITLE
Access to RCL embedded resources from css is problematic

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#17990]
### Describe the bug
In an RCL I am trying to access a resource from css with a broken http request observed in a wasm client.

in my css I have "background-image: url("_content/Optimiser.Components/images/triangles.svg");" does a "Request URL: https://localhost:44348/_content/_content/Optimiser.Components/images/triangles.svg" returning a 404 because of the mangled path (_content/_content).

### To Reproduce

Simply try to reference an embedded resource from css in an RCL such as
```
.triangles {
    background-image: url("_content/Optimiser.Components/images/triangles.svg");
    background-size: cover;
    height: 100%;
    bottom: 0;
    left: 0;
    mix-blend-mode: hard-light;
    position: fixed;
    right: 0;
    top: 0;
    background-position: center center;
}
```
My resources are in wwwroot\css, wwwroot\images etc.

### Further technical details

Blazor WASM Preview4 client

VS 2019 16.5.0 P1.0

```
C:\Solutions\OHI\blazorboilerplate>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Solutions\OHI\blazorboilerplate>

**Comment by MarkStega** [comment]
Very odd implementation IMHO; If I remove my "_content" from the path the correct path is generated & I get the resource. Why is this not consistem with accessing a resource from in code?

**Comment by MarkStega** [comment]
And in another project I have
```
.triangles {
    background-image: url("BlazorBoilerplate.CommonUI/images/triangles.svg");
    background-size: cover;
    height: 100%;
    bottom: 0;
    left: 0;
    mix-blend-mode: hard-light;
    position: fixed;
    right: 0;
    top: 0;
    background-position: center center;
}
```
 and the request URL is "Request URL:http://localhost:53414/_content/BlazorBoilerplate.CommonUI/css/BlazorBoilerplate.CommonUI/images/triangles.svg"

I really think that all that should be done is the prepend of the base url.

**Comment by pranavkm** [comment]
@MarkStega can you share a minimal project that reproduces the problem you're seeing?

**Comment by MarkStega** [comment]
[BlazorApp-CSB-3.1.0.zip](https://github.com/aspnet/AspNetCore/files/4000368/BlazorApp-CSB-3.1.0.zip)

Attached is an example where I have "background-image: url("_content/RazorClassLibrary1/triangles.svg");" in the css but the requested file is "https://localhost:44379/css/_content/RazorClassLibrary1/triangles.svg"

**Comment by pranavkm** [comment]
@javiercn could you have a look?
