### ISSUE TITLE
Add event for AuthenticateResult.NoResult to CertificateAuthenticationEvents

### ISSUE THREAD

**Issue by Egor92** [dotnet/aspnetcore#18020]
### Is your feature request related to a problem? Please describe.
I have Web API app (.NET Core 3.1).
I want to have authentication by certificate in my Web API. I have installed [Microsoft.AspNetCore.Authentication.Certificate](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Certificate) package and used AddCertificate method in Startup. It works good.
Also I want to handle situation where there is no certificate provided. CertificateAuthenticationEvents has properties OnAuthenticationFailed and OnCertificateValidated. But it has no event for AuthenticateResult.NoResult.

### Describe the solution you'd like
Add event for AuthenticateResult.NoResult to CertificateAuthenticationEvents

**Comment by blowdart** [comment]
What would you be expecting to do in such an event?

**Comment by Egor92** [comment]
I wanted to have debug scenario: set principle even if there was no certificate and log it.
Also I think it is a little bit strange that I can call ValidateCertificateContext.Success() and set principle even if it was exception during certificate checking ([example](https://github.com/Egor92/TestApplications/blob/master/.Net%20Core/CertificateAuthentication/CertificateAuthentication/Startup.cs#L32)). But can't do it if certificate didn't exist.

**Comment by anurse** [comment]
> I wanted to have debug scenario: set principle even if there was no certificate and log it.

If you want to log this, wouldn't it be better done after the middleware by checking if auth returned `NoResult` or if the principal was `IsAuthenticated=false` ?

I'm not sure I see the value here, especially since none of the other auth providers provide such a thing.

**Comment by prof28** [comment]
OnAuthenticationFailed is not triggered even if expired certificate is provided, plain HTTP 403 is returned. Unable to capture unauthorized attempt.
