### ISSUE TITLE
SignalR .NET client restart failed with "The HubConnection cannot be started while StopAsync is running"

### ISSUE THREAD

**Issue by dlyz** [dotnet/aspnetcore#18028]
### Describe the bug

I'm using .NET SignalR Client. After connection breaks I invoke `await connection.StopAsync()` and then `await connection.StartAsync()`. StartAsync throws InvalidOperationException: "The HubConnection cannot be started while StopAsync is running". The super easy way to reproduce it is to create a connection, invoke `await connection.StopAsync()` and then `await connection.StartAsync()`. After that the connection can never be started.

It looks like a bug. I looked at the code and it seems that `StopAsyncCore` cancels the cts, but never directly recreates it.

### Further technical details
- ASP.NET Core 3.1

**Comment by halter73** [comment]
Are you sure you're fully awaiting the completion of `connection.StopAsync()` before calling `connection.StartAsync()`? I just double-checked this with 3.1, and stopping and restarting a HubConnection still works for me. We also have test coverage for this.

https://github.com/aspnet/AspNetCore/blob/057ec9cfae1831f91f1a0e01397059b20431db7b/src/SignalR/clients/csharp/Client/test/UnitTests/HubConnectionTests.ConnectionLifecycle.cs#L95-L104

Can you provide a sample app that reproduces this behavior?

**Comment by BrennanConroy** [comment]
> After connection breaks I invoke `await connection.StopAsync()` and then `await connection.StartAsync()`

I think the key here is that stop is called "after connection breaks".

And a quick test shows that:
```c#
var connection = builder.build();
await connection.StopAsync();
await connection.StartAsync(); // throws here
```

fails.

@dlyz you shouldn't need to call stop after the connection "breaks", so you can workaround the issue by removing that logic.

**Comment by dlyz** [comment]
> I think the key here is that stop is called "after connection breaks".

Yes, that's the key.

> @dlyz you shouldn't need to call stop after the connection "breaks", so you can workaround the issue by removing that logic.

Sometimes it's hard to distinguish this situation from other fails. For example, now in my code, if something goes wrong while working with the connection, I just restart it.

Ok, so i can check `HubConnection.State` and decide whether I need to call `StopAsync`. But I think, workaround will not work if the connection "breaks" right before the stop call. It's a small chance, but still there are edge cases.
