### ISSUE TITLE
Method 'InvokeAsync' of view component should be declared to return Task&lt;T&gt;

### ISSUE THREAD

**Issue by as-ivanov** [dotnet/aspnetcore#18037]
Hi,

I have a Razor Class Library project with views shared across multiple servers. If I publish asp.net core server which imports the library in Debug configuration everything works fine. However if I publish it in Release configuration, I get a razor compilations error for several (not all) of view components at run time (details are provided bellow).
I created an empty project and reproduced the issue by adding a sample view component and inserting it in my _Layout.cshtml:

```
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Test.RazorUI.Features.Shared.Components.Example
{
  public class ExampleViewComponent : ViewComponent
  {
    public Task<IViewComponentResult> InvokeAsync()
    {
      return Task.FromResult<IViewComponentResult>(Content(""));
    }
  }
}

```
Once I publish server and make a first request the following error occurs:

Error RZ3902: Method 'InvokeAsync' of view component 'Test.RazorUI.Features.Shared.Components.Example.ExampleViewComponent' should be declared to return Task&lt;T&gt;.
at CompiledViewDescriptor Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(string relativePath)
   at Task<CompiledViewDescriptor> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(string normalizedPath)
   at RazorPageFactoryResult Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(string relativePath)
   at ViewLocationCacheResult Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet<IChangeToken> expirationTokens, string relativePath, bool isMainPage)
   at ViewLocationCacheResult Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at ViewLocationCacheResult Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, string pageName, bool isMainPage)
   at ViewEngineResult Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, string viewName, bool isMainPage)
   at ViewEngineResult Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, string viewName, bool isMainPage)
   at ViewEngineResult Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)

Test.RazorUI.csproj:
```

<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
```

Directory.build.props:

```
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeFrameworkVersion>3.1.0</RuntimeFrameworkVersion>
    <BuildProjectFramework>netcoreapp3.1</BuildProjectFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EmitEntryPoint>false</EmitEntryPoint>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <DefineConstants>JETBRAINS_ANNOTATIONS</DefineConstants>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <IncludeSymbols>true</IncludeSymbols>
    <DebugType>full</DebugType>
    <WarningLevel>0</WarningLevel>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzers>false</RunAnalyzers>
    <SkipValidatePackageReferences>true</SkipValidatePackageReferences>
    <Configurations>Debug;Release;Staging;Staging NO_CLIENT;Debug NO_CLIENT</Configurations>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyCompanyAttribute>true</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Company>PanzarStudio</Company>
    <CurrentYear>$([System.DateTime]::Now.ToString(yyyy))</CurrentYear>
    <OutputPath>bin</OutputPath>
    <IntermediateOutputPath>obj</IntermediateOutputPath>
    <EnableCentralPackageVersions>true</EnableCentralPackageVersions>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Release'))">
    <WarningLevel>0</WarningLevel>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DefineConstants>$(DefineConstants);Debug</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Staging'))">
    <DefineConstants>$(DefineConstants);Staging</DefineConstants>
	<Optimize>false</Optimize>	
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('NO_CLIENT'))">
    <DefineConstants>$(DefineConstants);NO_CLIENT</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2019.1.3" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup Condition="$(DefineConstants.Contains('Debug'))">
    <PackageReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.2" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="3.4.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.9.8" />
    <PackageReference Include="Microsoft.CodeAnalysis.Razor" Version="3.1.0" />
  </ItemGroup>
</Project>
```

Also I noticed, that if I simply replace Test.RazorUI.dll compiled in Release configuration with the one in Debug configuration the error disappears.
Please, let me know what extra information is required to address the issue.

- ASP.NET Core version
3.1

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 16.4.1

**Comment by pranavkm** [comment]
> I created an empty project and reproduced the issue by adding a sample view component and inserting it in my _Layout.cshtml:

@as-ivanov could you share this project with us? I tried reproducing the issue based on the contents you have, but I was unable to. A repro app would help investigate this further.

**Comment by as-ivanov** [comment]
Hi Pranav,

In order to avoid violations of my company's NDA (since repro contains some code of our projects), I had to create a private repository with repro application and add you as a collaborator there:
https://github.com/as-ivanov/razor-error-repro/ 
If you run RazorError application in Debug it works. However, once you publish it in Release configuration the error above appears.

Please, let me know if anything else is required.

**Comment by pranavkm** [comment]
Thanks @as-ivanov. Looks like your app turns on linking in Release builds. In addition, you rely on runtime compilation of views in published applications. The linker is likely removing types that are required by the views to build \ run. 

Is there a reason you rely on runtime compilation? It has a much slower startup experience compared to build time compiled views and increases the published output size. If you're using the linker for a smaller startup size, you should definitely consider using build time compiled views. There's a pattern to use runtime compiled views only in development \ Debug environment:

* https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/MyApp.csproj#L12
* https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/Startup.cs#L32-L41

If you must use runtime compilation, I'd recommend turning off the linker. It's going to be a constant struggle to make sure the linker doesn't strip out types that are used by views. You can configure the linker to preserve additional types: https://github.com/mono/linker/blob/master/src/ILLink.Tasks/README.md#adding-reflection-roots, but I would weight it against the const of accidentally breaking views without knowing so.

**Comment by as-ivanov** [comment]
Hi @pranavkm,

Thank you for the detailed feedback. We use runtime compilation intentionally, since we rely on it during partial updates, while startup speed is not an issue for us.

Can confirm that turning off the linker helped. Thank you!

Since compilation can do nothing with stripped out types at runtime, is that possible to just have a more precise error message in case a required type is missing? Perhaps even warn that the linker is incompatible with runtime compilation (in case the last is turned on), to help users faster address the issue?
