### ISSUE TITLE
JsonHubProtocol is a little too strict in C#

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#18055]
While testing my golang server implementation of signalr, I tried using the .NET client with the go server and got this error:

```
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[50]
      The server connection was terminated with an error.
System.IO.InvalidDataException: The 'error' and 'result' properties are mutually exclusive.
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindCompletionMessage(String invocationId, String error, Object result, Boolean hasResult, IInvocationBinder binder)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[46]
      Canceling all outstanding invocations.
Unhandled exception. System.IO.InvalidDataException: The 'error' and 'result' properties are mutually exclusive.
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindCompletionMessage(String invocationId, String error, Object result, Boolean hasResult, IInvocationBinder binder)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
```

The payload was this:

```
{"type":1,"target":"Send","arguments":["ok"]}\x0A\x1E{"type":3,"invocationId":"1","result":null,"error":""}\x0A\x1E
```

As you can see the invocation result has both result and error but they are both empty/null. This works fine in javascript but blows up in C#. We should relax this a bit

**Comment by halter73** [comment]
How does the JS client handle this? Does it consider it a successful invocation with a null result?

**Comment by halter73** [comment]
OK. So I just took a look. It seems as long is the error value is falsy, the JS client doesn't consider the invocation has an error. This is why even when the JS client receives invocation result that includes an error property won't treat it as an error if the value is an empty string or null.

I'm not sure recreating javascript's falsy logic in C# is the way to go. To get the C# logic to match the JS logic it would have to treat errors with the value `false`, `0`, `""`, `null`, `undefined` and `NaN` as not an error. Maybe we should just make the JS client more strict.

https://github.com/aspnet/AspNetCore/blob/c7937640a4079465d36441724933eae5a9ca0085/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L398-L402

**Comment by davidfowl** [comment]
> I'm not sure recreating javascript's falsy logic in C# is the way to go. Maybe we should just make the JS client more strict.

I think we should just check for null instead of trying to make the js client fail.

**Comment by halter73** [comment]
Null and empty string? What if a real error gets encoded as an empty string? Should the existence of any result override any error? It seems weird that a null result should override and empty string error even if that's what the JS client currently does.

**Comment by davidfowl** [comment]
> What if a real error gets encoded as an empty string?

Seems like an edge case no?

**Comment by anurse** [comment]
> It is a protocol error for a Caller to send a Completion message carrying both a result and an error.
> https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md#errors

The spec seems clear here. I'm not sure why we'd make the server change that expectation.

**Comment by davidfowl** [comment]
> The spec seems clear here. I'm not sure why we'd make the server change that expectation.

So you're arguing the same as @halter73 , the javascript client should detect the presence of the fields and throw, no matter the values?

**Comment by anurse** [comment]
Sure, either is fine. We can make C# more flexible or JS less flexible. It's whichever feels more appropriate to achieve consistency.

**Comment by anurse** [comment]
> As you can see the invocation result has both result and error but they are both empty/null

Oof, this makes things more complicated if you want `result` to be preferred in your suggestion. The JavaScript client is succumbing to JavaScript's definition of falsiness. Would we make the C# client consider an empty-string `error` as the same as a non-present property? That seems like a scarier change...

**Comment by davidfowl** [comment]
OK, I'll close it.
