### ISSUE TITLE
[Blazor] The App.razor is not created default with UTF-8 encoding

### ISSUE THREAD

**Issue by vulcanlee** [dotnet/aspnetcore#18058]
Because App.razor of Blazor project is not save with encoding default by UTF-8 (the default encoding is Chinese Traditional (Big5) - Codepage 950), cannot show any Chinese text of UTF-8.

To Reproduce this issue ( I also recording this problem and you can downlod  [Reproduce video without audio](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/2019-12-30_06-30-13.mp4)  ), you can create a Blazor of server side project and open App.razor file to change as following.

```html
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>抱歉，此地址沒有任何內容。</p>
        </LayoutView>
    </NotFound>
</Router>
```

![](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/2019-12-30_06-05-33.png)

To run this Blazor project and enter a not exist url, it will show incorrect context. 

![](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/2019-12-30_06-03-36.png)

If I use function from menu : [File] > [Save App.razor as...] > [Save with Encoding...] and change Encoding property to "Unicode (UTF-8 with signature) - Codepage 65001" on "Advanced save options dialog"

![](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/2019-12-30_06-14-33.png)

Then re-run this Blazor project, the page is working fine as following:

![](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/2019-12-30_06-18-06.png)

My environment is Windows 10 Profession 1099 build 18363.535  of Chinese version 

- ASP.NET Core version : 3.1
- Include the output of `dotnet --info`
- Visual Studio 2019 is 16.4.2

**Comment by pranavkm** [comment]
@ajaybhargavb didn't we fix this?

**Comment by glararan** [comment]
Confirming bug for 3.1. Did happen to me today

**Comment by ajaybhargavb** [comment]
@vulcanlee @glararan is this specific to App.razor or are you seeing this in all .razor files?

**Comment by glararan** [comment]
> @vulcanlee @glararan is this specific to App.razor or are you seeing this in all .razor files?

Only in App.razor

**Comment by ajaybhargavb** [comment]
After investigation I found the following,
When VS first opens `App.razor` it defaults to Windows Codepage 1252 encoding. The same file when opened in VS Code defaults to UTF-8. 
When I try to save the file with some unicode characters I get the following warning in VS,
![image](https://user-images.githubusercontent.com/1579269/71687746-6ba91500-2d53-11ea-9753-82b5982312f9.png)

Clicking yes saves it in the correct format and everything works as expected.

Yet, the core problem here is that Visual Studio thinks that App.razor is Codepage 1252 by default which we have no control over. I believe the reason this doesn't happen in other files is because they are stored as UTF8 with BOM where as App.razor is UTF-8 without BOM. So, to workaround this we'll change App.razor to be UTF with BOM and make it consistent with other files.

**Comment by glararan** [comment]
Im not so sure about dialog window. Didnt appear for me if I remember correctly. I had to resave it manually with UTF encoding

**Comment by ajaybhargavb** [comment]
@glararan what version of VS are you using? I'm on the latest 16.4.2.

**Comment by glararan** [comment]
> @glararan what version of VS are you using? I'm on the latest 16.4.2.

16.4.0

**Comment by ajaybhargavb** [comment]
Found the real cause of this issue after discussing with @pranavkm. It is an issue with how dotnet templating works. This is now being tracked here https://github.com/dotnet/templating/issues/2217.

**Comment by pranavkm** [comment]
From the linked issue

> This looks like a bug when the first line of the processed file contains a conditional construct such as #if.
> 
> I just verified that either adding a blank line to the top of the file, or moving the #if to the next line as follows results in the encoding being preserved.
> 
> ```
> @*
> #if (NoAuth)
> <Router AppAssembly="@typeof(Program).Assembly">
> ```
> 
> @ajaybhargavb This could be used as a a workaround in the template content until the root cause of underlying bug is found and fixed.

@danroth27 do we want to try and mitigate this in an AspNetCore patch release?

**Comment by vulcanlee** [comment]
> @vulcanlee @glararan is this specific to App.razor or are you seeing this in all .razor files?

I only see in App.razor

**Comment by Andrzej-W** [comment]
Maybe it is time to think again about .editorconfig file, see here #11617

**Comment by ajaybhargavb** [comment]
Closing as this is tracked here https://github.com/dotnet/templating/issues/2217.
