### ISSUE TITLE
razorclasslib template project support for F#

### ISSUE THREAD

**Issue by wilsoncg** [dotnet/aspnetcore#18067]
### Please consider razorclasslib template project support for F#
The following should succeed:
`dotnet new razorclasslib -lang f# -o RazorComponents`

### Describe the solution you'd like
This addition would improve the developer experience when using [Bolero](https://fsbolero.io/) and Blazor.

I'm not sure where the template packs are located for the Razor class library or what the process is for submitting a modified template pack, so any further information would be greatly appreciated.

**Comment by pranavkm** [comment]
Thanks for your issue report. We'll track fixing this as part of our next milestone.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
