### ISSUE TITLE
Blazor docs: Requires more information for lifetimes

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#18077]
https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1

This page says that IJSInterop etc are scoped as singletons, which is incorrect in server-side apps.

**Comment by pranavkm** [comment]
Thanks for the issue report @mrpmorris. We'll work on updating the docs as part of the Blazor WASM release.

**Comment by mkArtakMSFT** [comment]
@guardrex can you handle this?

**Comment by guardrex** [comment]
Where are you seeing that @mrpmorris? The topic states ...

> Singleton (Blazor WebAssembly)
> Scoped (Blazor Server)

... and doesn't refer to `IJSInterop` otherwise.

**Comment by guardrex** [comment]
btw - Please open docs issues on the docs repo by using the **This page** feedback button+form.

**Comment by mrpmorris** [comment]
@guardrex You fixed it 1 week after I reported it, but the PR doesn't reference this issue so it has remained open.

https://github.com/dotnet/AspNetCore.Docs/pull/16463

**Comment by guardrex** [comment]
:smile: @mrpmorris ... sorry about that. I'm 🏃😓😵 with updates these days. It worked out ok tho because I spotted that `HttpClient` entry that needed a fix, and that's taken care of now. :+1:
