### ISSUE TITLE
Add <InputDateTime> blazor component 

### ISSUE THREAD

**Issue by borseno** [dotnet/aspnetcore#18078]
Hello all, 

I've been using blazor for a while and I really liked it. 
However, there is one thing that I always need and it isn't present in Blazor.
It is DateTime input component. There is a InputDate component, so I can enter date, but there is no nice and convenient way to enter time and date in the same field (or in separate fields)

So it would be nice to add such components as InputTime, InputDateTime.

Thank you

**Comment by jaymcguinness** [comment]
InputDate builds a HTML compliant Input element which the type attribute set to "date"

https://github.com/aspnet/AspNetCore/blob/8c02467b4a218df3b1b0a69bceb50f5b64f482b1/src/Components/Web/src/Forms/InputDate.cs

The w3c spec supports other values, which includes capturing date and time - eg.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

But the UI will vary by browser so IME you'd be better off writing your own component for this.

**Comment by pranavkm** [comment]
Thanks for your issue report. We'll consider whether to address this during our next milestone planning.

**Comment by Bernhard-Ninaus** [comment]
Hey!
New here to .NET Core in general.

This works for me. I hope it's not complete wrong...

`@inherits InputBase<DateTime?>

<input @bind=CurrentValue 
       @attributes=AdditionalAttributes 
       @bind:format="yyyy-MM-ddTHH:mm"
       class=@CssClass 
       type="datetime-local"/>

@code {
    protected override bool TryParseValueFromString(string value, out DateTime? result, out string validationErrorMessage)
    {
        result = CurrentValue;
        validationErrorMessage = "";
        return true;
    }
}`

**Comment by Bogdan2033** [comment]
Привет,скинь свой телеграм или напиши мне! @azeloneAnD

**Comment by IanKnighton** [comment]
I've tried a few different ways of implementing this and there are some weird issues with data-binding. 

I tried using the `<input type="datetime-local">` that is referenced in the Mozilla documentation and sometimes the input would just completely crash. 

It would be nice if there was a cleaner and more consistent way to do this.

**Comment by IanKnighton** [comment]
I took @BernhardNinaus' solution and created an override to the `InputDate` class. This makes a usable DateTime picker that binds and saves nicely with the model. 

**InputDateTime.cs**
```csharp
public class InputDateTime<TValue> : InputDate<TValue>
    {
        private const string DateFormat = "yyyy-MM-ddTHH:mm";

        /// <inheritdoc />
        protected override void BuildRenderTree ( RenderTreeBuilder builder )
        {
            builder.OpenElement( 0, "input" );
            builder.AddMultipleAttributes( 1, AdditionalAttributes );
            builder.AddAttribute( 2, "type", "datetime-local" );
            builder.AddAttribute( 3, "class", CssClass );
            builder.AddAttribute( 4, "value", BindConverter.FormatValue( CurrentValueAsString ) );
            builder.AddAttribute( 5, "onchange", EventCallback.Factory.CreateBinder<string>( this, __value => CurrentValueAsString = __value, CurrentValueAsString ) );
            builder.CloseElement();
        }

        /// <inheritdoc />
        protected override string FormatValueAsString ( TValue value )
        {
            switch ( value )
            {
                case DateTime dateTimeValue:
                    return BindConverter.FormatValue( dateTimeValue, DateFormat, CultureInfo.InvariantCulture );
                case DateTimeOffset dateTimeOffsetValue:
                    return BindConverter.FormatValue( dateTimeOffsetValue, DateFormat, CultureInfo.InvariantCulture );
                default:
                    return string.Empty; // Handles null for Nullable<DateTime>, etc.
            }
        }

        /// <inheritdoc />
        protected override bool TryParseValueFromString ( string value, out TValue result, out string validationErrorMessage )
        {
            // Unwrap nullable types. We don't have to deal with receiving empty values for nullable
            // types here, because the underlying InputBase already covers that.
            var targetType = Nullable.GetUnderlyingType( typeof( TValue ) ) ?? typeof( TValue );

            bool success;
            if ( targetType == typeof( DateTime ) )
            {
                success = TryParseDateTime( value, out result );
            }
            else if ( targetType == typeof( DateTimeOffset ) )
            {
                success = TryParseDateTimeOffset( value, out result );
            }
            else
            {
                throw new InvalidOperationException( $"The type '{targetType}' is not a supported date type." );
            }

            if ( success )
            {
                validationErrorMessage = null;
                return true;
            }
            else
            {
                validationErrorMessage = string.Format( ParsingErrorMessage, FieldIdentifier.FieldName );
                return false;
            }
        }

        static bool TryParseDateTime ( string value, out TValue result )
        {
            var success = BindConverter.TryConvertToDateTime( value, CultureInfo.InvariantCulture, DateFormat, out var parsedValue );
            if ( success )
            {
                result = (TValue)(object)parsedValue;
                return true;
            }
            else
            {
                result = default;
                return false;
            }
        }

        static bool TryParseDateTimeOffset ( string value, out TValue result )
        {
            var success = BindConverter.TryConvertToDateTimeOffset( value, CultureInfo.InvariantCulture, DateFormat, out var parsedValue );
            if ( success )
            {
                result = (TValue)(object)parsedValue;
                return true;
            }
            else
            {
                result = default;
                return false;
            }
        }
    }
```

Here's the usage in the `.razor` file. 
```html
<div class="form-group row">
    <label for="createdDate" class="col-sm-3">Created Date:</label>
    <InputDateTime id="createdDate" class="form-control col-sm-8" @bind-Value="SystemOutage.CreatedDate"></InputDateTime>
    <ValidationMessage class="offset-sm-3 col-sm-8" For="(()=>SystemOutage.CreatedDate)"></ValidationMessage>
</div>
```

Might be overkill, but I hope it helps someone.

**Comment by cyberdarius** [comment]
@IanKnighton 

Your solution helped me alot !

Thanks !

**Comment by MarianoJP** [comment]
@IanKnighton 
Nice and elegant solution. I used it with success! Thanks for the code.

**Comment by codemonkey85** [comment]
@IanKnighton Have you considered submitting a PR to the Blazor repo to have your component added? I think a lot of people would benefit from it being built-in.

**Comment by ryanbuening** [comment]
> ```razor
> @inherits InputBase<DateTime?>
> 
> <input @bind=CurrentValue 
>        @attributes=AdditionalAttributes 
>        @bind:format="yyyy-MM-ddTHH:mm"
>        class=@CssClass 
>        type="datetime-local"/>
> 
> @code {
>     protected override bool TryParseValueFromString(string value, out DateTime? result, out string validationErrorMessage)
>     {
>         result = CurrentValue;
>         validationErrorMessage = "";
>         return true;
>     }
> }
> ```

How could you use the solution above from @BernhardNinaus  (inherit from InputBase<DateTime?>), but also include a `<ValidationMessage>`? I have the following (note addition of `ValidationFor`):

#### CustomDateInput.razor

```razor
<input type="date"
		 class="@CssClass"
		 @bind=CurrentValue
		 @attributes=AdditionalAttributes />

@if (ValidationFor is not null)
{
	<ValidationMessage For="@ValidationFor" />
}

@using System.Linq.Expressions
@inherits InputBase<DateTime?>

@code {
	[Parameter] public Expression<Func<DateTime>>? ValidationFor { get; set; }

	protected override bool TryParseValueFromString(string? value, out DateTime? result, out string validationErrorMessage)
	{
		result = CurrentValue;
		validationErrorMessage = "";
		return true;
	}
}
```

#### FooPage.razor
```razor
<CustomInputDate @bind-Value="FooDate" ValidationFor="() => FooDate"></CustomInputDate>
```

#### FooPage.razor.cs
```csharp
public DateTime? FooDate { get; set; }
```

However, I get errors:

![image](https://user-images.githubusercontent.com/812974/125317868-5416f900-e307-11eb-83d4-c3869c951295.png)

**Comment by MarianoJP** [comment]
@ryanbuening be careful when you use DateTime? since it is nullable. This means that when you use a nullable DateTime variable you must call variabl.Value to get the date and time value. Ex:

`FooDate.Value.ToString("MMM dd yyyy HH:mm") `

This will return you the correctly formatted date and time in a nullable DateTime, otherwise if you use:

`FooDate.ToString("MMM dd yyyy HH:mm")`

will get you the same error you are experiencing. Now I am not sure how it may impact in a lamda expression, but I would assume that you may need to take the nullable aspecs of the field into consideration and use the .Value.

**Comment by ryanbuening** [comment]
I have the following now...

`[Parameter] public Expression<Func<DateTime?>>? ValidationFor { get; set; }`

But I'm still getting the same errors. And when I hover over `ValidationFor=` in `FooPage.razor` I see this tooltip...

![image](https://user-images.githubusercontent.com/812974/125376573-4b4f1300-e359-11eb-8471-946b4b566487.png)

I would expect that to show `Expression<Func<DateTime?>>`

**Comment by MarianoJP** [comment]
> I have the following now...
> 
> `[Parameter] public Expression<Func<DateTime?>>? ValidationFor { get; set; }`
> 
> But I'm still getting the same errors. And when I hover over `ValidationFor=` in `FooPage.razor` I see this tooltip...
> 
> ![image](https://user-images.githubusercontent.com/812974/125376573-4b4f1300-e359-11eb-8471-946b4b566487.png)
> 
> I would expect that to show `Expression<Func<DateTime?>>`

Make sure you change to:

`[Parameter] public Expression<Func<DateTime?>> ValidationFor { get; set; }`

I think the second ? is the problem. Try it and I hope it helps.

**Comment by ryanbuening** [comment]
> Make sure you change to:
> 
> `[Parameter] public Expression<Func<DateTime?>> ValidationFor { get; set; }`

Unfortunately that doesn't work either. I still receive the same error.

I have posted a StackOverfow question [here](https://stackoverflow.com/questions/68350438) so as to not pollute this issue thread further. Thanks.

**Comment by papaja** [comment]
Thank you @IanKnighton. Just a small note - as of .net 6 RC1
> ```cs
> private const string DateFormat = "yyyy-MM-ddTHH:mm";
> ```

should be:
> ```cs
> private const string DateFormat = "yyyy-MM-ddTHH:mm:ss";
> ```

**Comment by segvan** [comment]
Great job @IanKnighton. In order to validate seconds input need to add step attribute (default is 60).

`builder.AddAttribute( 2, "step", "1" );`

**Comment by SteveSandersonMS** [comment]
This is already supported:

```razor
<InputDate Type="InputDateType.Time" @bind-Value="@myTime" />

@code {
    DateTime myTime;
}

```
