### ISSUE TITLE
Intersection Observer Not working in blazor server side app

### ISSUE THREAD

**Issue by fingers10** [dotnet/aspnetcore#18080]
I recently came across `IntersectionObserver` API. so I thought of making my existing `window.onscroll` logic to work with `IntersectionObserver` API. However I'm not able to achieve it.

Here is what I'm trying to do. In my parallax page with fixed top nav bar and I would like to apply `active` css class to `a.nav-items` when the user scroll reaches the respective section he wants to view.

Here is the HTML:

```html
<body data-spy="scroll" data-target=".site-nav" data-offset="55">

  <header id="page-hero" class="site-header d-flex flex-column align-content-between">

    <nav class="site-nav family-sans text-uppercase navbar navbar-expand-md navbar-dark fixed-top">

    <div class="container-fluid">

        <NavLink class="navbar-brand" href="#page-hero" @onclick="NavigateToElementAsync">
            <i class="fas fa-microphone-alt"></i> The Prodcast
        </NavLink>

        <button type="button" class="navbar-toggler @NavToggleCssClass" @onclick="ToggleNavMenu" aria-controls="#myTogglerNav"
                aria-label="Toggle Navigation" aria-expanded="@($"{!collapseNavMenu}".ToLowerInvariant())">
            <span class="navbar-toggler-icon"></span>
        </button>

        <section class="navbar-collapse collapse @NavMenuCssClass" id="myTogglerNav">
            <div class="navbar-nav ml-auto">
                <NavLink class="nav-item nav-link" href="#page-hero" @onclick="NavigateToElementAsync">home</NavLink>
                <NavLink class="nav-item nav-link" href="#page-multicolumn" @onclick="NavigateToElementAsync">podcasts</NavLink>
                <NavLink class="nav-item nav-link" href="#page-media" @onclick="NavigateToElementAsync">blogs</NavLink>
                <NavLink class="nav-item nav-link" href="#page-photogrid" @onclick="NavigateToElementAsync">gallery</NavLink>
                <NavLink class="nav-item nav-link" href="#page-carousel" @onclick="NavigateToElementAsync">youtube</NavLink>
                <NavLink class="nav-item nav-link" href="#page-nested" @onclick="NavigateToElementAsync">hiring</NavLink>
                <NavLink class="nav-item nav-link" href="#page-iconcolumns" @onclick="NavigateToElementAsync">community</NavLink>
                <NavLink class="nav-item nav-link" href="#page-floater" @onclick="NavigateToElementAsync">subscribe</NavLink>
                <NavLink class="nav-item nav-link" href="#page-cards" @onclick="NavigateToElementAsync">about us</NavLink>
            </div>
        </section>

    </div>

</nav>

    <section class="layout-hero jumbotron jumbotron-fluid d-flex align-items-center mt-5 text-reverse">
      <div class="container text-center">
......
......
......

    <article id="page-multicolumn" class="page-section vertical-padding">

    <header class="page-section-header container">
.....
.....
.....

    <article id="page-media" class="page-section vertical-padding">

    <header class="page-section-header container text-center">
....
```

I have `article` tag with `id` matching `href` of `a` in top `.nav-item`. I have only pasted few of the html as the skeleton is same for all article tags.

Here is my `IntersectionObserver`:

```js
const sections = document.querySelectorAll('.page-section,.site-header');
const config = {
    rootMargin: '-55px 0px -55%'
};

let observer = new IntersectionObserver(function
    (entries, self) {

    entries.forEach(entry => {
        console.log(entry);
        if (entry.isIntersecting) {
            intersectionHandler(entry);
        }
    });
}, config);

sections.forEach(section => observer.observe(section));

function intersectionHandler(entry) {
    const id = entry.target.id;
    const currentlyActive = document.querySelector('nav a.nav-item.active');
    const shouldBeActive = document.querySelector('nav a.nav-item[href="#' + id + '"]');

    if (currentlyActive) {
        currentlyActive.classList.remove('active');
    }
    if (shouldBeActive) {
        shouldBeActive.classList.add('active');
    }
}
```

But my intersection observer is not working. I tired using `console.log(entry)` to see what happens. All the entries gets logged only on page load and not working after that.

**Comment by pranavkm** [comment]
@fingers10 do you know if you see the same issue in a non-Blazor app (for instance an MVC application with Views)? We don't think this is a Blazor specific issue, more likely an issue with how you're using the browser API.

**Comment by fingers10** [comment]
@pranavkm  This is a pure java script logic and this works even with simple html, and js files. Everything is loaded correctly in blazor but still it fails.

**Comment by pranavkm** [comment]
@SteveSandersonMS could you have a look?

**Comment by SteveSandersonMS** [comment]
My expectation is that the reason the code here doesn't work is that it's running at the wrong time. The call to `document.querySelectorAll('.page-section,.site-header')` needs to be executed *after* those elements have been rendered into the DOM, otherwise it won't match anything.

For examples of how to use JS interop against the rendered output of a component, please see docs about `ElementReference` at https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#capture-references-to-elements

**Comment by fingers10** [comment]
@SteveSandersonMS This is a static parallax page. The elements rendered and are available in page when it is loaded. Intersection observer should execute when a scroll happens in a page and apply css class to elements. So the elements are available and no page reload or no dynamic contents. But still it fails.

**Comment by SteveSandersonMS** [comment]
@fingers10 I don't understand how the elements can be available when the page is first loaded. At the time when initial scripts run, Blazor hasn't yet rendered the initial UI. You *may* have prerendered elements in the page, but they are not the same elements that will exist once the initial UI is rendered interactively.

**Comment by fingers10** [comment]
@SteveSandersonMS So I need to call my function from inside the component after it got rendered?

**Comment by SteveSandersonMS** [comment]
If you're relying on interacting with its rendered elements, then yes you have to do that after the elements are rendered ;)

**Comment by fingers10** [comment]
@SteveSandersonMS Thanks for pointing me in right direction. I made it to work using `OnAfterRenderAsync`

Wrapped my code to a java script function `highlightMenu()`

```js
function highlightMenu() {
    const sections = document.querySelectorAll('.page-section,.site-header');
    const config = {
        rootMargin: '-55px 0px -85%'
    };

    let observer = new IntersectionObserver(function
        (entries, self) {

        entries.forEach(entry => {
            if (entry.isIntersecting) {
                intersectionHandler(entry);
            }
        });
    }, config);

    sections.forEach(section => observer.observe(section));

    function intersectionHandler(entry) {
        const id = entry.target.id;
        const currentlyActive = document.querySelector('nav a.nav-item.active');
        const shouldBeActive = document.querySelector('nav a.nav-item[href="#' + id + '"]');

        if (currentlyActive) {
            currentlyActive.classList.remove('active');
        }
        if (shouldBeActive) {
            shouldBeActive.classList.add('active');
        }
    }
}
```

```c#
@code{

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JSRuntime.InvokeVoidAsync("highlightMenu");
        }
    }

}
```
