### ISSUE TITLE
[Proposal]Add a generic Set and Get methods to the Microsoft.AspNetCore.Http.SessionExtensions class

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#18081]
Now that .Net Core 3 has a built-in JsonSerializer, it is helpful to add a generic Set and Get methods to the SessionExtensions class:

```C#
using Microsoft.AspNetCore.Http;
using System.Text.Json;

namespace Microsoft.AspNetCore.Http
{
    public static class SessionExtensions
    {
        // Old methods
        public static byte[] Get(this ISession session, string key);
        public static int? GetInt32(this ISession session, string key);
        public static string GetString(this ISession session, string key);
        public static void SetInt32(this ISession session, string key, int value);
        public static void SetString(this ISession session, string key, string value);
    }

       // New Methods
    public static void Set<T>(this ISession session, string key, T value)
    {
       session.SetString(key, JsonSerializer.Serialize(value));
    }

    public static T Get<T>(this ISession session, string key)
    {
       var value = session.GetString(key);
       return value == null ? default(T) : JsonSerializer.Deserialize<T>(value);
    }
}
```

**Comment by Tratcher** [comment]
We've decided against this repeatedly. It makes too strong an assumption that all types can be safely round-tripped through JSON serialization.

At most we should update the sample in the docs showing how to do this. (It uses JsonConvert today).
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1#set-and-get-session-values

**Comment by VBAndCs** [comment]
You can add some safeguards in these method to throw an exception if T is not suitable and add warnings to the docs.
Or you can add many non-generic methods to deal with DateTime and  numeric types other than Int32, so we can deal with object properties individually.

**Comment by VBAndCs** [comment]
> It makes too strong an assumption that all types can be safely round-tripped through JSON serialization.

I added a constraint o T to implement ISerializable.
```C#
        public static void Set<T>(this ISession session, string key, T value) where T: ISerializable
        {
            session.SetString(key, JsonSerializer.Serialize(value));
        }
```

**Comment by anurse** [comment]
We don't plan to add any direct functionality to JSON serialize arbitrary objects in to session (it's very costly to do right because of all the configuration options needed and will likely not fulfill all the necessary requirements).

We'll update the doc to use the new System.Text.Json serializer though.

**Comment by anurse** [comment]
Unfortunately the doc is a full runnable sample so the update is non-trivial. Moving to the backlog for now, we'll evaluate priorities and look at when we can do this.

It would probably make for a good PR if someone wants to make it. The changes needed are:

* Make a 3.1 version of [`aspnetcore/fundamentals/app-state/samples/2.x/SessionSample`](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/app-state/samples/2.x/SessionSample) that uses System.Text.Json in [SessionExtensions](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state/samples/2.x/SessionSample/Extensions/SessionExtensions.cs)
* Update https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md to reference that sample in the `>= 3.1` version of the doc.

**Comment by Tratcher** [comment]
FYI @guardrex

**Comment by anurse** [comment]
We actually already have a larger item to update these docs (https://github.com/aspnet/AspNetCore.Docs/issues/13328), so I've included this suggestion in that and will close this in lieu of that larger update.

**Comment by Jaben** [comment]
Why not just keep it clear and add:

```csharp
       // New Methods
    public static void SetAsJson<T>(this ISession session, string key, T value)
    {
       session.SetString(key, JsonSerializer.Serialize(value));
    }

    public static T GetAsJson<T>(this ISession session, string key)
    {
       var value = session.GetString(key);
       return value == null ? default(T) : JsonSerializer.Deserialize<T>(value);
    }
```

?
