### ISSUE TITLE
User secret value can't have a dash (-) as a prefix

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#18095]
_From @tuscen on Saturday, December 28, 2019 9:44:44 AM_

When trying to add a secret with a value prefixed with a dash I get the following error

```
$ dotnet user-secrets set KEY "-1234567" 
Specify --help for a list of available options and commands.
Unrecognized option '-1234567'
```

dotnet sdk version: 3.1.100

_Copied from original issue: dotnet/sdk#4106_

**Comment by anurse** [comment]
_From @livarcocc on Tuesday, December 31, 2019 6:51:17 PM_

@anurse @mkArtakMSFT should this be moved to asp.net?

**Comment by anurse** [comment]
@tuscen FYI, discussion on your issue has moved here.

_It looks like this is probably an issue with command-line parsing in the tool_. If I open the user secret JSON file directly, it works as both as key and a value (both in `dotnet user-secrets list` and at runtime).

```json
{
  "-1234567": "Foo",
  "Bar": "-1234567"
}
```

```shell
> dotnet user-secrets list
Bar = -1234567
-1234567 = Foo
> dotnet run # A simple app that just dumps the two keys above
-1234567=Foo
Bar=-1234567
```

@tuscen as a workaround you can either:

* Right click the project in VS and choose 'Manage User Secrets' to open the file directly and add your settings there
* Locate the file on disk and add your settings (where `[UserSecretsId]` is the value of the `UserSecretsId` MSBuild property in your csproj file).
	* Windows: `%AppData%\Microsoft\UserSecrets\[UserSecretsId]]\secrets.json`
	* macOS and Liunx: `~/.microsoft/usersecrets/[UserSecretsId]/secrets.json`

**Comment by Kahbazi** [comment]
@anurse I tried something to fix this in Extensions repo. Basically if an option is not available, the arg would assign to argument list if possible. I'm not quite sure if I break any existing scenarios but at least the tests are passed.
Once it merged I could also add the unit tests for user-secrects in this repo.

**Comment by anurse** [comment]
@Kahbazi sounds reasonable! If you'd like to open a PR to fix this, we'd take a look!

**Comment by Kahbazi** [comment]
@anurse I opened a PR here https://github.com/aspnet/Extensions/pull/2822

**Comment by Kahbazi** [comment]
@anurse When can I see the new `CommandLineApplication` in this repo?
