### ISSUE TITLE
Document hosting Blazor in non-root URLs

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18094]
Per https://github.com/aspnet/AspNetCore/issues/17997#issuecomment-570184384

> We absolutely should document at least the process of hosting Blazor WebAssembly at a non-root URL (which in turns gives you the ability to host N of them at different non-root URLs) but there's no point doing that until we implement the new startup APIs, as it will all change in the next couple of months as we approach the May release.

**Comment by Wayne-Mather** [comment]
Hi,

Will the May release mentioned by @SteveSandersonMS be in the 3.1LTS branch?

**Comment by softlion** [comment]
It is documented there https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.1&tabs=visual-studio

**Comment by mkArtakMSFT** [comment]
Thanks @softlion. Indeed this is documented. Closing as a dupe.
