### ISSUE TITLE
ASP.NET Core Identity implementation for EF6

### ISSUE THREAD

**Issue by BRiley01** [dotnet/aspnetcore#18102]
Migrating AspNetCore Framework 4.72 app targetting EF 6.2 to Core 3.1 targeting EF 6.4

Identity UserStore exists in 2 packages: Microsoft.AspNet.Identity.EntityFramework and Microsoft.AspNetCore.Identity.EntityFrameworkCore

Microsoft.AspNet.Identity.EntityFramework targets .net framework and would not permit migration to Core 3.1.

Microsoft.AspNetCore.Identity.EntityFrameworkCore targets EntityFrameworkCore  and is not compatible with EF 6.4 

A new "Microsoft.AspNetCore.Identity.EntityFramework" likely needs to be created, otherwise this upgrade path won't work if using EF 6.4 with identity.

Open to alternative solutions.

**Comment by ajcvickers** [comment]
@blowdart @HaoK Now that EF6 runs on .NET Core we are starting to see people asking for Identity Code to work with EF6. We have never planned to do this, but bringing this here to consider or be explicit that we're not doing it.

**Comment by blowdart** [comment]
Generally our solution has been the cookie compat shim, nothing more. I'd need more justification on why people want this to consider it.

**Comment by ajcvickers** [comment]
@blowdart Where is the "cookie compat shim" documented?

**Comment by blowdart** [comment]
Well really it's [data protection.](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/replacing-machinekey?view=aspnetcore-3.1) but this allows identity cookies to be read.

**Comment by blowdart** [comment]
So after discussion the path for aspnet applications still remains update to aspnetcore, which in turn means moving to efcore. EF6 on core is there to simplify migrations, but I don't feel it applies to aspnet core, you still have to port your aspnet application anyway.
