### ISSUE TITLE
Comfortable way to populate @bind-Value value with generated values in case of generic components

### ISSUE THREAD

**Issue by SayusiAndo** [dotnet/aspnetcore#18108]
### Is your feature request related to a problem? Please describe.
I'm working on a generic grid solution and I have problem with populating `@bind-Value` values with generated values. In case of generated `@bind-Values` there will be no working binding.

For example, the following code results two way binding:
```razor
<BSBasicInput InputType="InputType.Text" 
                             id="@propertyInfo.Name"
                            @bind-Value="_editedItem.Name"/>
```
The following code will be generated from this:

```
#nullable restore
#line 46 "/.../ExactGrid.razor"
                                            _editedItem.Name

#line default
#line hidden
#nullable disable
                            , 77, Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => _editedItem.Name = __value, _editedItem.Name)));
                            __builder5.AddMarkupContent(78, "\n            ");
                        }
                        ));

```

The code I'm trying to use is the following:
```razor
@{
string bindValue = $"{nameof(_editedItem)}.{propertyInfo.Name}";
}
<BSBasicInput InputType="InputType.Text"
              id="@propertyInfo.Name"
              @bind-Value="@bindValue"/>
```

The above generates the following in the .g files, and I believe the problem is that it has the `bindValue` value instead of the variable name and property name, as it is in the first example.

```
#line default
#line hidden
#nullable disable
                        , 37, 
#nullable restore
#line 32 "/.../ModalEdit.razor"
                                                            bind

#line default
#line hidden
#nullable disable
                        , 38, Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => bind = __value, bind)));
                        __builder4.AddMarkupContent(39, "\n");
```

I have tried the all thing I know about razor, but I can't force that the bind value is evaluated before (so not `bind` will be part of the compiled code, rather `_editedItem.Name`) the file is compiled. 

- I asked help from [Stackoverflow](https://stackoverflow.com/questions/59570685/how-to-generate-dynamically-blazors-bind-value), no answer yet.
- I checked a few blazor grids, but the only one working uses exclusively [RenderTreeBuilder](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#manual-rendertreebuilder-logic)

I can't decide, what I'm looking for doesn't exist yet, or I'm doing something wrong.

### Describe the solution you'd like
I'd like to request a comfortable way to setup `@bind-Value` in generic cases where this value also generated, without using RenderTreeBuilder. The example above, I believe, clearly explains what I'm looking for.

In the [Data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#data-binding) section of the following is stated:

```
<input value="@CurrentValue"
    @onchange="@((ChangeEventArgs __e) => CurrentValue = 
        __e.Value.ToString())" />
        
@code {
    private string CurrentValue { get; set; }
}
```
and 

```
<input @bind="CurrentValue" />

@code {
    private string CurrentValue { get; set; }
}
```
are essentially equal. So, it says to me that without using RenderTreeBuilder it is not possible to generate bindings in a generic component.

**Comment by pranavkm** [comment]
@SteveSandersonMS would you like to respond to this?

**Comment by SteveSandersonMS** [comment]
I'm afraid that if you want the set of parameters you're passing to vary dynamically, you would have to do that with manual `RenderTreeBuilder` logic, since `.razor` syntax doesn't offer a way to do it.

> So, it says to me that without using RenderTreeBuilder it is not possible to generate bindings in a generic component.

It depends on what you mean by "generic". If you mean "has a generic parameter, e.g., declared using `@typeparam`" then you absolutely can do that with regular `.razor` syntax.

However I suspect that when you say "generic" you mean something very different, something like "the *names* of the parameters it passes to a child are not known until runtime", and that does require manual `RenderTreeBuilder` logic, since `.razor` syntax doesn't offer a way to do it.
