### ISSUE TITLE
Harden UrlHelperBase.IsLocalUrl against control characters

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18109]
`UrlHelperBase.IsLocalUrl` will return true for urls such as `/\n/not-local-url`. Using this value as part of `LocalRedirectResult` will result in an exception from HttpAbstractions rather than the more helpful error message from `LocalRedirectResultExecutor`: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/LocalRedirectResultExecutor.cs#L53

**Comment by gfoidl** [comment]
I'll take a look into this.

**Comment by am11** [comment]
Related to another IsLocalUrl behavior; according to https://tools.ietf.org/html/rfc8089, these are also local URLs:

*  file:///path/to/file
*  file:/path/to/file
*  file:c:/path/to/file
*  file:///c|/path/to/file
*  file:/c|/path/to/file
*  file:c|/path/to/file

whereas, these are not:

*  file://host.example.com/path/to/file
*  file:////host.example.com/path/to/file
*  file://///host.example.com/path/to/file
