### ISSUE TITLE
DefaultPageHandlerMethodSelector not available in 3.0 anymore

### ISSUE THREAD

**Issue by mgubis** [dotnet/aspnetcore#18115]
We are now migrating our project from .NET Core 2.2 to .NET Core 3.1. We had quite some customization in place (to connect with in-house framework). We are implementing custom IPageHandlerMethodSelector to connect with some postback functionality and we had fallback to the default selector in place. Our current implementation looks following:

       public class PageHandlerMethodSelector : IPageHandlerMethodSelector
        {
            private DefaultPageHandlerMethodSelector selector;

            public PageHandlerMethodSelector(IOptions<RazorPagesOptions> options)
            {
                this.selector = new DefaultPageHandlerMethodSelector(options);
            }

            public HandlerMethodDescriptor Select(PageContext context)
            {
                if (OurFrameworkCode.HasMatch) 
                {
                    return OurFrameworkCode.Select(context);
                }

                return this.selector.Select(context);
            }
        }

How are we supposed to implement custom IPageHandlerMethodSelector with fallback to the default behaviour of ASP.NET? I was trying to google for this but failed to found relevant information.
Thank you very much.

**Comment by pranavkm** [comment]
Hi @mgubis, the type was made internal as part of our making pub-internal types internal. See https://github.com/aspnet/Announcements/issues/326. For 3.x, the recommendation is to copy the type in to your application: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.RazorPages/src/Infrastructure/DefaultPageHandlerMethodSelector.cs.

**Comment by mgubis** [comment]
Thank you for the answer. I have managed to copy it into our libraries (little change was necessary, but it was really just cosmetic change) and migrated successfully to .NET Core 3.1.

Nevertheless, I think it would be nice to have a possibility to access default functionality (copying of the code just increases maintenance costs and in case of bugfixes, they are not received automatically). Maybe some DefaultsProvider returning instance typed as an interface would be nice. What do you think?

**Comment by pranavkm** [comment]
In the past, making our default implementations public severely affected our abilities to change or evolve these types. That was one of the primary motivations for making these non-public. 

One option you could explore in this particular case is to use a DI framework that allows decorating. @khellang would you happen to know if this would work with Scrutor?

**Comment by khellang** [comment]
In theory it should, yes. Just make sure you inject `IPageHandlerMethodSelector` in your implementation (as opposed to newing it up) and decorate the default registration:

```csharp
services.Decorate<IPageHandlerMethodSelector, PageHandlerMethodSelector>();
```

**Comment by mgubis** [comment]
I understand, that making default implementations public affected flexibility you could use in evolution of framework. But I think, that if the default implementation is exposed only via interface, it shouldn't create friction points (changing the interface is breaking change anyway).

Anyway, thanks to the Scrutor (thanks @khellang), I was able to get default instance - your proposed solution works well. Thanks @pranavkm and @khellang for your help!
