### ISSUE TITLE
AzureAD Authentication system - Cannot turn off Issuer validation

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/aspnetcore#18117]
Source project:
`https://github.com/aspnet/AspNetCore/tree/master/src/Azure/AzureAD/Authentication.AzureAD.UI/`

When authenticating against the `common` endpoint, Issuer Validation needs to be turned off. However, the current implementation of the library provides no discoverable/intuitive way to turn this off.

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1#configure-the-underlying-openidconnectoptionsjwtbearercookie-options
```
services.Configure<OpenIdConnectOptions>(
    AzureADDefaults.OpenIdScheme, options => 
    {
        // Omitted for brevity
    });
```
Look at options.TokenValidationParamters.ValidateIssuer.

**Comment by sujayvsarma** [comment]
Ok, when I did that, the flow went ahead and I got my token. BUT, now I hit a new issue. Apparently, I cannot authorize the application against the `common` endpoint.

**My scenario:**
This is a multi-tenant application targeted at Azure subscribers. It needs to be able to perform actions against both the Graph API (Azure AD only, more specifically users & groups) and also calls against the AzureRM API.

In `AzureADOptions` if I provide a specific tenant Id (a Guid or a `xxxx.onmicrosoft.com`) and authenticate against that, everything works. But if I set Tenant to `common`, I hit the dreaded `Authorization_IdentityNotFound` exception on any request AFTER I get a token.

I see that in [this line](https://github.com/aspnet/AspNetCore/blob/c17ce436b8703470231e7979cead042f5682c3f5/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADOpenIdConnectOptionsConfiguration.cs#L32) of the source code, you are setting:

```
options.Authority = new Uri(new Uri(azureADOptions.Instance), azureADOptions.TenantId).ToString();
```

which gives the URL: `https://login.microsoftonline.com/<tenantId>` which means that TenantId must be set to `common` for it to work in the multi-tenant scenario. Right?

Or am I misreading the code/docs?

**Comment by blowdart** [comment]
This is probably one for @jmprieur to answer as it's more about how azure ad works.

**Comment by jmprieur** [comment]
@sujayvsarma : did you have a look at this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2 ?

**Comment by sujayvsarma** [comment]
@jmprieur  - Let me take this forward with you via issues on the samples repo.

Thank you @blowdart.
