### ISSUE TITLE
input time

### ISSUE THREAD

**Issue by matengo** [dotnet/aspnetcore#18119]
### Describe the bug
When using the input time. <input type="time" @bind="FromTime" /> it's not possible to bind to a string anymore, for example "08:00". Now it seems to be needed to bind to a datetime..? When I do that.. As soon as I change the time using the inout field, the date in the datetime is changed to current date...? Is that expected behavior?, or is there something I'm missing?

### To Reproduce

<input type="time" @bind="FromTime" />

DateTime FromTime = DateTime.Now.AddDays(-5);

Change the time in the input...

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by mathisloge** [comment]
Maybe related to https://github.com/aspnet/AspNetCore/issues/17898

**Comment by pranavkm** [comment]
Dup of #17898.
