### ISSUE TITLE
HashRoute Support Request

### ISSUE THREAD

**Issue by VARUN46** [dotnet/aspnetcore#18123]
### Is your feature request related to a problem? Please describe.
This is case for Blazor Web Assembly App 

I want to use HashRouter instead of Router, in App.razor 

```
<HashRouter AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</HashRouter>

```
### Describe the solution you'd like
Now,

I want to open #/about for About.razor it should work fine in case of @page "/about" 

### Additional context
It helps in working with old browsers and other route handling schemes for specific URL context.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.
