### ISSUE TITLE
SignalR Core - Remove user from group

### ISSUE THREAD

**Issue by NullQubit** [dotnet/aspnetcore#18141]
Removing a user from a group using "RemoveFromGroupAsync" requires a connectionId.  Sometimes you might need to remove a user from a group when you don't have that user's connection id in context.

Example:
Admins can create chat rooms and add users to these chat rooms.  An admin can also kick a user from a chat room.  So on the server side, we are within the context of the admin's connection, but we need to remove some other user from the group to stop him from getting notifications.

How can we remove all connections of a user from a group?  Do I need to maintain this association in an external storage or is there some other way that I'm missing?

Thanks

**Comment by jkotalik** [comment]
@BrennanConroy @halter73 thoughts?

**Comment by halter73** [comment]
This would be non-trivial to implement. Every HubLifetimeManager (e.g. DefaultHubLifetimeManager, RedisHubLifetimeManager, ServiceLifetimeManager, and user-defined HubLifetimeManagers) would need to add support for this. It's a bit like asking to support removing one group from another, but at least this would be limited to users and not all groups.

The only way I can think of  work around this is to keep a mapping of users->ConnectionIds yourself and loop over each connectionId for a user to remove them from a group. You also have to make sure this doesn't race against users adding themselves to the group on OnConnectedAsync or elsewhere, but this would be true even with built-in remove-user-from-group support.

**Comment by journger** [comment]
Similar functionality exists on the "@aspnet/signalr@1.1.0", upgrading to @microsoft/signalr@3.1 looses this? 
What is the point to keep the groups then if you cannot manipulate them?

**Comment by BrennanConroy** [comment]
> upgrading to @microsoft/signalr@3.1 looses this?

What functionality are you observing that is no longer there?

**Comment by halter73** [comment]
You can still remove connections from groups just like you always could in SignalR. Users can represent multiple connections, however, and SignalR never supported directly removing a user from a group.

**Comment by rogierpennink** [comment]
I have a similar issue: I'm working on a (web-based) game where players can travel to different locations, and when they do, I need to add them to the new location's group, and remove them from their previous location's group. Traveling is triggered by the server so I cannot just use the calling connection's context to manage the groups they're in - I need to be able to find the connections that belong to a user so I can then use those connection ids to call `AddToGroupAsync` and `RemoveFromGroupAsync`.

What is the recommended approach in this case? Manually keep a mapping of users to connection ids in memory? Do I need to be on the lookout for unintended side-effects in this case?
