### ISSUE TITLE
Blazor Server - Random error occuring "The list of component records is not valid."

### ISSUE THREAD

**Issue by physix99** [dotnet/aspnetcore#18143]
Hi,

We're using Asp.Net.Core 3.1.0, got a Blazor Server website.

Occasionally we get an error in the browser console saying:
`blazor.server.js:15 [2020-01-06T11:22:02.989Z] Error: The list of component records is not valid.`

But the trouble is I haven't been able to work out why it appears, it seems like the signalr connection is being restarted as the console logs immediately before that line say:

```
[2020-01-06T11:22:02.785Z] Information: Normalizing '_blazor' to 'https://localhost:44303/_blazor'.
[2020-01-06T11:22:02.914Z] Information: WebSocket connected to wss://localhost:44303/_blazor?id=DpnlPPLrSkoFlbbF_TnHqg.
[2020-01-06T11:22:02.915Z] Information: Using HubProtocol 'blazorpack'.
```

I've got a feeling it's when I've used the back button, but I haven't been able to replicate the issue at all, it just randomly appears sometimes.

Can anybody give me a clue what could cause this issue? So i can try and manually replicate it?

The code that is throwing the error is in [ComponentHub.StartCircuit](https://github.com/aspnet/AspNetCore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Components/Server/src/ComponentHub.cs), which looks to be called from the javascript function in [CircuitManager.ts.startCircuit](https://github.com/aspnet/AspNetCore/blob/602cb1dea59751a1297d674cddf7f0729c23e6ca/src/Components/Web.JS/src/Platform/Circuits/CircuitManager.ts).

The javascript function is passing this parameter
`JSON.stringify(this.components.map(c => c.toRecord()))` which is what is causing the error to be thrown, but i'm not sure where this list of components is coming from?

Thanks

**Comment by KKacer** [comment]
Happened to me as well,
Randomly!
I always like and to build some complex multi assembly project and folder structure.
BTW still just made part of the bare-bone structure.
Placed the Counter blazor component inside another assembly, enabled logging both in the application and the component scope with the minimum code.
Happened some times that when ran the app and tried to click the **Counter** and **Log** that via Serilog facing the same error. Interestingly when moving through the web app, suddenly it started working! 
Same error appeared more in different execution of that multi-tier basic app. (without data)
Rarely happened though,
May give more info later...

**Comment by pranavkm** [comment]
@physix99 the error message usually indicates one of two things:

a) You've multiple servers, but don't use sticky sessions.
b) Your site restarted between the the time the initial request with pre-rendered content was sent to the client and the client reconnected to the server.

Your console logs likely indicate the latter. Is this something you see consistently?

**Comment by physix99** [comment]
Hi,

Thanks for the response.

We are not using multiple servers, and i'm pretty sure the site did not restart between.

I have slightly narrowed it down, It seems to happen most when i'm using NavigationManager.NavigateTo("currentUrl", true) to refresh the page completely, then hitting the back button.

However it doesn't happen every time and I have still not been able to fully replicate the issue.

Thanks

**Comment by gaffkins** [comment]
Hi, I have the same issue. I open blazor app, then I click back in browser to back google for example, on random time I click forward to back to blazor app. It's very frustrating.
Best!

**Comment by pranavkm** [comment]
@gaffkins do you have a minimal app that reproduces this error? I tried following your steps but did not see the error. In the meanwhile, one thing to try might be to configure the ResponseCache filter to disable caching on `_Host.cshtml`.
