### ISSUE TITLE
Identity UI Email not sent via external login user creation

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#18140]
In the external login flow, when require confirmed account = true (the default), this skips sending the confirmation email:

See https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L207

The send email needs to occur above the redirect to register confirmation.

@blowdart @ajcvickers we should probably consider whether this should be patched

See https://github.com/aspnet/AspNetCore.Docs/issues/13206 for some more context

**Comment by HaoK** [comment]
This fix will need to be ported to scaffolding

**Comment by blowdart** [comment]
It probably needs to be smarter. If you're using external logins you generally should trust the logins you're using, so if the login provider gives you an email address, and the user doesn't change it when entering their information it could be considered confirmed. If they change it then send the email.

**Comment by HaoK** [comment]
Well originally we didn't send any confirmation emails via social providers, I mean we can go the other way with this fix and just automatically confirm any accounts that were created via social providers if you want instead of sending confirmation emails

**Comment by brockallen** [comment]
yea, facebook emails are garbage since they provide an @facebook.com domain. i'd not say those are terribly trustworthy.

**Comment by HaoK** [comment]
Fixed for 5.0, port to 3.1 still pending branch lockdown

**Comment by timmywiff** [comment]
Hi @HaoK 

It looks like this hasn't been updated in the Microsoft.AspNetCore.Identity.UI NuGet package yet. The current package (3.1.1) is built from an older version.

Apologies if this is the wrong place to ask for this to be updated.

https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.UI/3.1.1
