### ISSUE TITLE
Windows hosting bundle 3.x localized help text is clipped

### ISSUE THREAD

**Issue by dagood** [dotnet/aspnetcore#18152]
### Describe the bug
When using the hosting bundle with non-English localization, the help text is clipped.

![image](https://user-images.githubusercontent.com/12819531/71851647-a0db9d00-309c-11ea-8c0e-06963e1bd8ad.png)

### To Reproduce
1. Download the 3.1.0 or 3.0.1 Windows hosting bundle from https://dotnet.microsoft.com/download/dotnet-core/3.1
2. Set language/region to Spanish (any language larger than English)
3. Run `.\dotnet-hosting-3.1.0-win.exe -?`

**Comment by Pilchie** [comment]
@aspnet/build who would normally look at this?

**Comment by dougbu** [comment]
Most likely @joeloff. @jkotalik has also done some work in the relevant files.

**Comment by joeloff** [comment]
I've looked at this before. The layouts need to be manually adjusted unfortunately

**Comment by anurse** [comment]
@joeloff are you able to look at this then?

**Comment by joeloff** [comment]
yeah, you can assign to me @anurse

**Comment by anurse** [comment]
This was fixed in https://github.com/dotnet/aspnetcore/pull/18246 and will be released in 3.1.3.

**Comment by RomBrz** [comment]
@anurse just to know, this will be release in 3.0.4 too?

**Comment by anurse** [comment]
No, [3.0 will be end-of-life before the next patch](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) (it goes out of support March 3rd, 2020).
