### ISSUE TITLE
Flaky Servers Test: Settings_MaxHeaderListSize_Server

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#18154]
[The `Settings_MaxHeaderListSize_Server` test](https://github.com/aspnet/AspNetCore/blob/a386abcb2a62a776abef349dd7ac446dd4e703b3/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs#L1351) is [failing fairly consistently on CI](https://dev.azure.com/dnceng/public/_build/results?buildId=473307&view=ms.vss-test-web.build-test-results-tab&runId=15063152&resultId=100011&paneView=debug) (~40% failure rate). We need to resolve the flakiness.

**Comment by Tratcher** [comment]
@anurse it's already marked as flaky, and it's caused by a client issue https://github.com/dotnet/runtime/issues/860. Do you want to disable it?

**Comment by Tratcher** [comment]
Where did you get that percentage?

**Comment by anurse** [comment]
@ryanbrandenburg did some very unscientific math :).

**Comment by ryanbrandenburg** [comment]
@Tratcher I looked at the history histogram and guessed.

**Comment by anurse** [comment]
This is already marked flaky, so we're good here.

**Comment by ryanbrandenburg** [comment]
What work item tracks marking this as not-flaky when it's resolved?
