### ISSUE TITLE
Wierd behaviour of AuthorizationHandlerContext.HasSucceeded in an edge case.

### ISSUE THREAD

**Issue by yeah-boi** [dotnet/aspnetcore#18156]
With the current implementation of the property `AuthorizationHandlerContext.HasSucceeded`, it will be `false` if we use it for an instance that has just been initialized with an empty set of requirements. This because `this._succeedCalled` will be `false` in that case.

I expect `AuthorizationHandlerContext.HasSucceeded` to be `true` in this case since all 0 requirements has succeeded in this case.

**Comment by anurse** [comment]
It shouldn't be possible to create a policy with no requirements though. We explictly don't want policies with zero requirements because that wouldn't make sense. Where are you seeing this behavior?
