### ISSUE TITLE
Make it simple to remove 'Use Another Service To Login'

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/aspnetcore#18164]
I read several posts on stackoverflow that you cannot remove the part that says 'Use Another Service To Login.' If you do not agree with the privacy policy of any of the other services, my only choice is to write my own authentication, or show a message 'Use Another Service To Login'.

The link to the page in the article that explains how to setup up another service, does not show how to opt out of using another service. For an open source project, the built in login is fine.

I read the 'How To Scaffold A Razor Page Article someone suggested, but a simple 'ShowExternalProviderMessage' would be much simpler.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by HaoK** [comment]
@blowdart @ajcvickers so if we want to add UI options, this prob would end up looking like the following:

- new UIOptions subproperty in Identity/Extensions.Core which we would add all identity UI specific properties
- accessed via IdentityOptions.UI.* or something similar to configure it along side 

so for this specific issue, we could do something like:

```
services.AddDefaultIdentity(o => o.UI.ShowExternalLogins = false)
```

This would result in the UI pages just not showing the relevant sections, it would not prevent the handler code from working or anything else, it would just cause rending changes on Login and Manage.

Does that sound reasonable?

**Comment by HaoK** [comment]
Alternatively, this does just work via the normal, scaffold, and delete the elements from the layout, which is the general idea...

**Comment by blowdart** [comment]
Folks don't want to scaffold and who can blame them? 

I like the idea of UI properties, it's more future proof. If you're going to set that to true, but also configure logins I'd assume you were doing something yourself in your UI elsewhere.

**Comment by OzBob** [comment]
"There are no external authentication services configured." should also be considered worth fixing.

The packaged template pages display the message when there are no oAuth services configured. E.g. when the Web App does not actually need oAuth and is using their own local auth Identity database.

The updated page templates from  original v4 "Identity" project have an IF around the required section.

Will the latest templates be imported?

**Comment by blowdart** [comment]
https://github.com/dotnet/aspnetcore/issues/30305 has another approach we should consider as part of the work.

**Comment by hrkrx** [comment]
As this is something not many seem to need, how would one achieve this without a new feature?

**Comment by OzBob** [comment]
[The Identity Server v4 UI original code](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/main/Views/Account/Login.cshtml#L52), has an ```@if (Model.VisibleExternalProviders.Any())```

Is there another project to rebase from? [This repo pages](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Login.cshtml#L53) is missing out on new features from Identity Server 4 Quickstart.
