### ISSUE TITLE
ASP.NET Core project templates write Startup.cs and Program.cs with ANSI encoding, not UTF-8

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/aspnetcore#18168]
Updating the header comments in my ASP.NET Core 3.1 project's C# files today (changing end year from 2019 to 2020), I noticed incorrect display of Unicode Character 'COPYRIGHT SIGN' (U+00A9) and Unicode Character 'REGISTERED SIGN' (U+00AE) when committing the files to GitHub using GitHub Desktop - but only in template-generated files `Startup.cs` and `Program.cs`.

Why?  Turns out the template (e.g. ASP.NET Core Web Application template) writes out `Startup.cs` and `Program.cs` with ANSI encoding, whereas all the other C# files (generated manually by Visual Studio 2019 when I create a new file) have UTF-8-BOM encoding.

Not a biggie, to be sure.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We'll review this and get back to you.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb can you please look into this one? Thanks!

**Comment by ajaybhargavb** [comment]
@Andrew-Webb, I tried creating multiple new projects both in command-line with `dotnet new` and with VS. But all of the `Program.cs` and `Startup.cs` files that were created had UTF-8 encoding and not ANSI. I'm using the SDK version `3.1.100`.

Can you try creating a new project from the template and check if you are still seeing the issue? If you do, can you provide the exact steps as well as your output of `dotnet --info`?

**Comment by Andrew-Webb** [comment]
@ajaybhargavb - surveying a number of projects created by me over the last year with VS 2017 and VS 2019, and a mixture of ASP.NET Core 2.2, 3.0 and 3.1, I can see a mixture of ANSI encoding and UTF-8 (no BOM) encoding for these two files.

Creating a new ASP.NET Core 3.1 MVC website with the template in VS 2019 v16.4.2 just now, the encoding of these two files is UTF-8 (as you found).  Looking at the encoding at various files in the new solution/project, it's either UTF-8 or UTF-8-BOM.

For example:-

* Startup.cs - UTF-8
* appsettings.json - UTF-8
* HomeController.cs - UTF-8-BOM
* ErrorViewModel.cs - UTF-8
* _Layout.cshtml - UTF-8-BOM

My conclusion:-

1) The encoding varies from file to file within any one specific version of the template.
2) The encoding of the same file can vary from version to version of the template.
3) The encoding of Startup.cs and/or Program.cs has been ANSI in the past, but is now UTF-8 in the latest/current version of the template.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb should we close this now?

**Comment by ajaybhargavb** [comment]
Yes, this specific issue has been fixed. I did a quick sanity check to make sure we don't have more issues like these but I found we still have some inconsistencies that were introduced recently. Looks like the test I added to catch issues like these was being skipped on helix. I filed https://github.com/dotnet/aspnetcore/issues/22753 to track this fix.
