### ISSUE TITLE
Errors from inaccessible types in the current project do not appear in the error window

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#18166]
Ver: VS.NET Community 16.4.2, .NET Core 3.1
In a Razor pages project, I defined this static class:
```C#
    internal static class SessionKeys
    {
        internal static readonly string IDs = "1";
        internal static readonly string Count = "2";
        internal static readonly string Note = "3";
        internal static readonly string Date = "4";
    }
```

I added this ststement to the _ViewImports.cshtml file:
`@using Microsoft.AspNetCore.Http`

In the page, I wrote this:
```Razor
@page
@model IndexModel
@{
    var count = HttpContext.Session.GetInt32(SessionKeys.Count);
}
```

I have intelligence support for `SessionKeys`, but the build fails with no error or warning in the Error window!  
The build succeeds if I get rid of the  `SessionKeys.Count` and use a const string like:
```
@{
    var count = HttpContext.Session.GetInt32("4");
}
```

So,
1. What is wrong with the static fields? Why the build fails?
2. Why there are no errors in the Error window?

**Comment by pranavkm** [comment]
Hi @VBAndCs,

This looks like a bug in how Razor's editing works. In general, views are compiled in to a separate assembly. Consequently, referencing `internal` types or members would result in an error about the type's accessibility. Howerver in the editor, the type that drives the formatting is code-gened to be part of the project. This would explain why you don't see accessibility errors while editing the file. Interestingly, building the project does produce an error in the Output window, however it gets suppressed in the Error window.

If you close the .cshtml file in the editor, you should see the exact error show up in the Error Window. The fix here is to make the type and it's members public.

/cc @NTaylorMullen

**Comment by VBAndCs** [comment]
@pranavkm
Thanks for the info and the fix.
Can you find a solution for `Internal` types other than making them public which would be risky in some cases as it violates security guidelines? 
At least, types defined in the Pages Namespace (and Pages Folder) should be included in the View assembly. This can be none breaking if we mark them with some attribute (such as `[ViewAsem]`).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
