### ISSUE TITLE
DefaultHttpContextFactory not available in nuget

### ISSUE THREAD

**Issue by mantasaudickas** [dotnet/aspnetcore#18167]
Hi,

Latest nuget package of Microsoft.AspNetCore.Hosting is 2.2.7 which does not have DefaultHttpContextFactory type available.

It is possible to reference version 3.1.0 using file system which I guess is completely wrong solution:
`<Reference Include="Microsoft.AspNetCore.Hosting">
      <HintPath>C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.0\ref\netcoreapp3.1\Microsoft.AspNetCore.Hosting.dll</HintPath>
    </Reference>`

AspNet Core app with netcoreapp3.1 target also uses this type.. but its impossible to access it in library package which targets netstandard2.0.

Was it forgotten to release as Nuget package or there is another idea here?

**Comment by anurse** [comment]
ASP.NET Core 3.0 and higher versions are no longer available as packages, as they are a built-in framework in .NET Core (and not supported on .NET Framework).

We have [guidance on how to use ASP.NET Core types from a class library available in our documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio).
