### ISSUE TITLE
View renderer seems to disregard passed in view model

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/aspnetcore#18169]
### Describe the bug
Trying to render a partial view with a defined view model but the renderer seems to ignore what I pass in and grab a view model from the initial model passed in to the controller action.

### To Reproduce
Create a post method that takes in an int from the route and a view model.
Then return a partial view while passing it a new view model.
The view should then render with the values from the model passed in to the action rather than the null values that are present in the newly created view model that has been constructed within the action.

![image](https://user-images.githubusercontent.com/21192520/71912370-48c09b80-316d-11ea-843c-a346637e15e4.png)

https://gitlab.com/KieranDevvs/mvc-model-bug

1) Clone the repo.
2) Start the project.
3) Create a POST request to /Home/Index/{any id}.
4) Add a URL encoded form body with a key of `SomeDecimal` and the value of any 32 bit integer.
5) See the response has a text field with the value provided in the request body.

![image](https://user-images.githubusercontent.com/21192520/72015923-98c95c00-325a-11ea-9d0c-8f22ea504aad.png)

*Expected result:* A text field is rendered with no value as a blank view model is being passed into the `PartialView(viewPath, viewModel)` call.

*Actual result:* A text field is rendered with the value that is passed into the request from the URL encoded form body.

### Further technical details
- ASP.NET Core version 2.1 (Reproducible in 2.2 & 3.1 also)
- VS2019 16.3.9

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
> I can provide a repository with a reproducible example if necessary.

That usually helps expedite our investigations.

**Comment by KieranDevvs** [comment]
> > I can provide a repository with a reproducible example if necessary.
> 
> That usually helps expedite our investigations.

I've added a repository that you can clone and some steps to follow to fully reproduce the issue.

**Comment by mkArtakMSFT** [comment]
Thanks @KieranDevvs.

@pranavkm can you please look into this? Thanks!

**Comment by ScholliYT** [comment]
Just had the same Problem with `asp.net core mvc 3.1`. Seems really weird 😒

**Comment by pranavkm** [comment]
Sorry, I missed your earlier response @KieranDevvs. The value from the ModelState is likely being used. https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-3.1#expression-names has some explanation about how model expressions (the value in `TextBoxFor`) is evaluated.

**Comment by pranavkm** [comment]
See previous discussions here: https://github.com/aspnet/Mvc/issues/7260, including https://github.com/aspnet/Mvc/issues/7260#issuecomment-360527445 which has a way to clear ModelState to change this behavior.

**Comment by Pilchie** [comment]
Closing resolved issue.
