### ISSUE TITLE
Html.NameFor in camel case format

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#18161]
Is it possible to configure how the `NameFor` helper so it will produce camel case format? I tried to use the `[Display(Name = "")]` attribute but it does not seem to work? Maybe there are som other built in method for making this to work or do I need to create my own extension?

I would like this `@Html.NameFor(x => x.ArtDirection.Images.Landscape)` to produce `artDirection.images.landscape`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we have support for. Given that we haven't heard much similar ask in the past, this is not something we plan to do.
