### ISSUE TITLE
TempDateAttribute doesn't work with private properties

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#18176]
I defiend this property in a Razor Page:
```C#
[TempData] DateTime Date { get; set; }

public void OnGet()
{
  Date = DateTime.Now;
}
```

I forgot to use the `public` modifier in the Date property definition, so it became `private`, and the `TempDateAttribute` had no effect!

I think you should give an error or a warning about this, because I lost some time trying to find out why the `TempData["Date"]` returns null!
The TempDateAttribute documentation also say nothing about this, which should be fixed.

**Comment by javiercn** [comment]
@VBAndCs thanks for contacting us.

MVC doesn't do reflection over private members (I don't think we do it anywhere) and that's not something that is likely to change.

I don't think we would write an analyzer for this as each analyzer has an impact on performance however minimal it is, and this is a well-known MVC pattern. You could choose to write one for your projects or as an external library if you wanted to.

I would suggest you declare your properties using the `prop` snippet that will give you a public property you can simply Tab through.

**Comment by VBAndCs** [comment]
Thanks for your reply.
I want also to ask: Why there is no SessionAttribute to bind properties to Session state?

**Comment by mkArtakMSFT** [comment]
This is not a common pain point so we don't plan to implement it.
> I want also to ask: Why there is no SessionAttribute to bind properties to Session state?

**Comment by VBAndCs** [comment]
@mkArtakMSFT
Just for reporting:
We also can mark full-implemented properties with the TempDateAttribute and it will have no effect, and we don't get any error or warning.
Thanks.
