### ISSUE TITLE
Java Client error:  Expected HTTP 101 response but was '404 Not Found'

### ISSUE THREAD

**Issue by akhilbansal** [dotnet/aspnetcore#18175]
We are getting below mentioned error when trying to establish connection with SignalR api. We are on Version 3.0

"WebSocket closed from an error: Expected HTTP 101 response but was '404 Not Found'"

Java client application has maven dependency:
<code>
		<dependency>
		    <groupId>com.microsoft.signalr</groupId>
		    <artifactId>signalr</artifactId>
		    <version>3.0.0</version>
		</dependency>
</code>

Code to establish connection is: 
HubConnection conn  = HubConnectionBuilder.create(endpoint).withHeader("Authorization","Bearer "+token).build();
conn.open();

**Comment by BrennanConroy** [comment]
Well, the obvious question is, are you sure your endpoint is correct? Where is your server listening and what is the hub path?

**Comment by akhilbansal** [comment]
Endpoints I provided were correct, though they were behind load balancer. Setting shouldSkipNegotiate(true) solved the issue.
