### ISSUE TITLE
(Microsoft.AspNetCore.TestHost.)TestServer doesn't support Certificate Authentication

### ISSUE THREAD

**Issue by dommorin** [dotnet/aspnetcore#18177]
### Describe the bug
Enabling certificate authentication in .net core api causes the TestServer to always return 403-Forbidden in integration tests (despite certificate used in request).

### To Reproduce
Internal Microsot repo: https://dev.azure.com/maluuba/_git/TuringSearch 

1. Enable certificate authentication in .NET Core API
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1
``` C#
// Startup.cs
    ...
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<CertificateValidationService>();
        services.AddAuthentication(
            CertificateAuthenticationDefaults.AuthenticationScheme).AddCertificate(options =>
        {
            ...
        });
        services.AddAuthorization();
        services.AddControllers();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILogger<Startup> logger)
    {
        ...

        app.UseRouting();

        app.UseCertificateForwarding();
        app.UseAuthentication();
        app.UseAuthorization();
        ...

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    }
```

2. Use "authorize" attribute on your api
``` C#
// WeatherForecastController.cs
    [ApiController]
    [Route("api/weather")]
    [**Authorize**]
    public class WeatherForecastController : ControllerBase
    {
    ...
    }
```

3. Write integration test using Microsoft.AspNetCore.TestHost
``` C#
// IntegrationTests/ClientCertificateTests.cs
    [Fact]
    public async void GivenValidCertificate_PerformGet_ExpectSuccess()
    {
        X509Certificate2 validClientCertificate;
        using (var certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
        {
            certStore.Open(OpenFlags.ReadOnly);
            validClientCertificate = certStore.Certificates.Find(X509FindType.FindByTimeValid, DateTime.Now, true)[0];
        }

        using (var server = new TestClientProvider(ignoreCertificate: false).Server)
        {
            // Act
            var result = await server.SendAsync(context =>
            {
                context.Connection.ClientCertificate = validClientCertificate;
                context.Request.Method = "GET";
                context.Request.Path = "/api/weather";
            });

            // Assert
            Assert.Equal(200, result.Response.StatusCode);
        }
    }
```

### Further technical details
I tried altering the CertificateValidationService in TestClientProvider but it seems the certificate validation is failing before reaching my code. The service is working properly with client certificate when deployed in Azure.

**Comment by anurse** [comment]
Triage: It seems like this is just a feature gap that we can look at fixing in the future. @Tratcher does that sound right to you?

**Comment by dommorin** [comment]
Can you suggest any workaround? Being able to write integration tests is quite crucial if I want to push my API to production.

**Comment by anurse** [comment]
There's not likely to be a workaround possible, short of cloning the test server code and making a change directly. Right now, the best bet is to use a real socket connection.

Making the change to test server should be *relatively* straightforward though. Test Server doesn't do a "real" request, it's basically just a fake `HttpClientHandler` that takes an `HttpRequestMessage`, wraps it up in `HttpContext` and runs it through the middleware pipeline. Still, it wouldn't ship until a 5.0 preview.

**Comment by Tratcher** [comment]
That approach should have worked, I'll have to debug through it to see why it didn't. Our tests do almost the same thing:
https://github.com/dotnet/aspnetcore/blob/149aa55629bd7c451b0a2e2e2feccc38e36cd282/src/Security/Authentication/test/CertificateTests.cs#L489-L496

**Comment by anurse** [comment]
Ah yeah, I missed that you were "sending" an `HttpContext` directly rather than using the HttpClient version. It should indeed have worked then.

**Comment by Tratcher** [comment]
I see the problem, you need to set the request scheme to `https`.
`context.Request.Scheme = "https";`
Cert auth no-ops for `http` requests.
https://github.com/dotnet/aspnetcore/blob/da984f57c508819704004d24245cff17c7f43bbc/src/Security/Authentication/Certificate/src/CertificateAuthenticationHandler.cs#L47-L54
