### ISSUE TITLE
[Discussion] Moving AspNetCore repo to dotnet org 2020-01-07.

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#18171]
As a first step towards the work describe [here](https://github.com/dotnet/announcements/issues/127), we're planning on migrating the AspNetCore repo to the dotnet org.  We'd like to get this done ASAP.

We don't expect any significant issues for contributors, GitHub is great about adding redirects.  However, it may impact our ability to produce nightly builds and flow dependencies for a few days.

Please let us know if you run into any other issues.

**Comment by WiredUK** [comment]
@Pilchie Can you fix the title on the [announcement](https://github.com/aspnet/Announcements/issues/400) please? It's got a weird date! 😊

**Comment by Pilchie** [comment]
Yeah, just did. Not quite sure how I managed that ;)

**Comment by Pilchie** [comment]
The initial move is complete.  We still have work to get builds and dependency flow working again.

**Comment by TanvirArjel** [comment]
@Pilchie why all the repository names are in lower case this time instead of upper case as before?

**Comment by Pilchie** [comment]
@TanvirArjel To be consistent with just about all of the other repos in the `dotnet` org, as described in the original (announcement)[https://github.com/dotnet/announcements/issues/127].

**Comment by Pilchie** [comment]
This is done now.
