### ISSUE TITLE
Blazor Server HttpContextAccessor.HttpContext null when client is behind proxy

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#18183]
I am trying to get tokens in a Blazor server app using `httpContext.GetTokenAsync()` method but for some reason `HttpContextAccessor.HttpContext` is always null when the client (browser) is behind a proxy and WebSockets are not available.

This doesn't happen if I access the app from my mobile, for example, which is not behind a proxy.

Is there something I am missing?

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

We don't recommend using HttpContextAccessor in server-side Blazor applications as the context is not always available and its availability depends on the underlying transport, which is not reliable.

This is the same as for other SignalR applications.

**Comment by mihaimyh** [comment]
> @mihaimyh thanks for contacting us.
> 
> We don't recommend using HttpContextAccessor in server-side Blazor applications as the context is not always available and its availability depends on the underlying transport, which is not reliable.
> 
> This is the same as for other SignalR applications.

Thanks for the answer. Then again, how can I get the acces token, for example?

Mihai

**Comment by javiercn** [comment]
Here is a sample

### Startup.cs
```csharp
            services.AddAuthentication(o => {
                o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                o.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            }).AddOpenIdConnect(options =>
            {
                // Configure this provider or an alternative provider
            })
            .AddCookie();

```

### _Host.cshtml
```razor
<body>
    @{ 
        var token = await HttpContext.GetTokenAsync("access_token");
    }
    <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" param-AccessToken="token" />
    </app>

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.server.js"></script>
</body>
```

### App.razor
```razor
<CascadingValue Name="AccessToken" Value="AccessToken">
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
    </CascadingAuthenticationState>
</CascadingValue>
@code{
    [Parameter] public string AccessToken { get; set; }
}
```

### ShowToken.razor
```razor
@page "/showtoken"

<p>This is part of the access token @(AccessToken != null ? AccessToken.Substring(0,30) : "(null)")</p>


@code {
    [CascadingParameter(Name = "AccessToken")] public string AccessToken { get; set; }
}

```

**Comment by mihaimyh** [comment]
@javiercn That worked, thank you very much.

**Comment by mihaimyh** [comment]
@javiercn I got one more question if you are so kind to help. I am trying to inject `User-Agent` from HttpContext request headers into AspNet.Core DI container by creating an extension method and use it in ConfigureServices method in Startup.cs. The issue is, using the solution provided by you, I only can get the value of `User-Agent` after the app started, in App.razor component. Should I try to inject it from there?

**Comment by mihaimyh** [comment]
> @javiercn I got one more question if you are so kind to help. I am trying to inject `User-Agent` from HttpContext request headers into AspNet.Core DI container by creating an extension method and use it in ConfigureServices method in Startup.cs. The issue is, using the solution provided by you, I only can get the value of `User-Agent` after the app started, in App.razor component. Should I try to inject it from there, but in this case the extension method will fail when it will be called into the ConfigureServices method.

You can ignore this, after checking, HttpContext is not null at that stage.
