### ISSUE TITLE
Missing SameSite and secure attributes when using Microsoft.AspNetCore.Http.Delete method

### ISSUE THREAD

**Issue by bmoyet** [dotnet/aspnetcore#18189]
Hello,
In the following issue (https://github.com/dotnet/aspnetcore/issues/12125) you fixed the Headers library to effectively set the SameSite attribute to None in cookie instead of omitting it.
I think I found another case where cookie attributes are not properly set.

### Describe the bug
When trying to remove a cookie I used the following code : 

> context.Response.Cookies.Delete(name, new CookieOptions()
			{
				Domain = context.Request.Host.Host,
				SameSite = SameSiteMode.None,
				Secure = true
			});

But on the browser side the set-cookie header has SameSite=lax and no secure attribute. Whereas if I manually create the set-cookie to remove my cookie it works correctly :

> context.Response.Cookies.Append(name, value, new CookieOptions()
			{
				Domain = context.Request.Host.Host,
				SameSite = SameSiteMode.None,
				Secure = true,
				Expires = new DateTimeOffset()
			});

### Further technical details
- ASP.NET Core 2.0.0
- Microsoft.Net.Http.Headers 2.8.0

**Comment by blowdart** [comment]
https://github.com/dotnet/aspnetcore/issues/17833
https://github.com/dotnet/aspnetcore/issues/17980

**Comment by Tratcher** [comment]
The new SameSiteMode.None behavior was not patched into 2.0.0, the minimum required version is the latest 2.1.x.

**Comment by anurse** [comment]
Closing this. ASP.NET Core 2.0 is end-of-life and this issue is known to be fixed in 2.1.
