### ISSUE TITLE
Get html Element info as position / size without JS

### ISSUE THREAD

**Issue by yToxide** [dotnet/aspnetcore#18187]
**Is your feature request related to a problem? Please describe.**

I'm trying to move an html element dynamically on my code, and also trying to resize some others so they can be responsive. 

**Describe the solution you'd like**

let's say we have

```
<div class="movable-div" @ref="myDivRef" draggable="true" @ondragend="OnDragEnd" @ondragstart="OnDragStart">
    <MyComponent/>
</div>

<div @ref="myOtherDivRef">
   Some Random Content
</div>

@code {

    private UIElement<div> myDivRef;
    private UIElement<div> myOtherDivRef;

    private double startX, startY;

    private void OnDragStart(DragEventArgs args) {
        startX = args.ClientX;
        startY = args.ClientY;
    }

    private void OnDragEnd(DragEventArgs args) {
        myDivRef.Position.X += args.ClientX - startX;
        myDivRef.Position.Y += args.ClientY - startY;
    }

    private void MyResizeFunction(int width) {
        myOtherDivReft.Width = width;
    }
}
```

**Comment by javiercn** [comment]
@yToxide thanks for contacting us.

I'm not sure what you are trying to achieve here, but currently there's no way to do that without JS interop.

This is not something that would work on things like server-side Blazor so it is unlikely we would do it as it would make very easy to write components that only work in some environments, which is not something we want to promote.
