### ISSUE TITLE
The server disconnected before the handshake was completed

### ISSUE THREAD

**Issue by newuser27** [dotnet/aspnetcore#18195]
I have
Connection = new HubConnectionBuilder().WithUrl(Constants.SignalRServer).Build();
 await Connection.StartAsync();

have a Exception
the Exception.message is “The server disconnected before the handshake was completed”

[pila.txt](https://github.com/dotnet/aspnetcore/files/4036442/pila.txt)

**Comment by BrennanConroy** [comment]
Can you provide more details about your environment, like how is the server hosted? Is there a proxy in use?

And could you capture server side logs and maybe network traces: https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging

**Comment by newuser27** [comment]
I generated this. are they enough?
[fiddlerfile.txt](https://github.com/dotnet/aspnetcore/files/4036841/fiddlerfile.txt)


[networktrace.txt](https://github.com/dotnet/aspnetcore/files/4036847/networktrace.txt)

**Comment by BrennanConroy** [comment]
Not really. It would be useful to know how your app and client are set up.

It looks like you're running the .Net Client on the server? In which case what is the client trying to connect to? And it would be useful to get the network trace between the client and the server it's trying to connect to. As well as the logs for the server the client is trying to connect to.

**Comment by newuser27** [comment]
I am working with .Net, I have hosted an API to which I connect to send messages via signarl.

How do I get network trace between the client and the server?

in this fragment i get HubConnectionState Disconnected
 Connection = new HubConnectionBuilder().WithUrl(Constants.SignalRServer).ConfigureLogging(logging =>
                {
                    logging.AddConsole();
                    logging.SetMinimumLevel(LogLevel.Debug);
                })
                .Build();

the connection in the api is simple and I don't know why
that state is returned

**Comment by BrennanConroy** [comment]
> I have hosted an API to which I connect to send messages via signarl.

Is this "API" an ASP.NET Core app that is configured to run SignalR? With `MapHub` and `AddSignalR`? https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio#configure-signalr
