### ISSUE TITLE
Blazor WebAssembly hosted publish --no-build is broken (and the test)

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#18191]
We have a test called `Publish_HostedApp_WithNoBuild_Works` but it's not a very useful test because it doesn't attempt to run the resulting app to check if it really works. And currently, the resulting app does not work.

Repro steps:

 * `cd src\Components\Blazor\testassets\HostedInAspNet.Server`
 * `rm -rf bin obj` (or otherwise delete these two dirs completely)
 * `dotnet build -c Release`
 * `dotnet publish -c Release --no-build`
 * `cd bin\Release\netcoreapp3.1\publish\`
 * `HostedInAspNet.Server.exe`

Expected: published app should run and serve working Blazor WebAssembly app to browser

Actual: throws during startup because `HostedInAspNet.Client.blazor.config` is missing

Note that this issue only occurs with `--no-build`.

It would be great if, as part of fixing this, we could make the "publish" tests verify that the resulting app correctly displays "hello world" in a browser, though that does involve introducing Selenium here.

**Comment by javiercn** [comment]
@SteveSandersonMS I see what you mean.

I would suggest we simply validate that the test validate the expected files are present on the output folder.

I don't think we want to do this in these tests as this complicates them unnecessarily. If we cared enough about this scenario I would suggest we define an E2E scenario for the vendors to try or we could add it as a template test variation.

In any case, that file will go away once we move to use static web assets as the only important thing in it was the client app path.

**Comment by SteveSandersonMS** [comment]
> I would suggest we simply validate that the test validate the expected files are present on the output folder.

That's what we're already doing. The issue is when we make mistakes about what the expected files are :)

**Comment by javiercn** [comment]
@SteveSandersonMS im moving this to preview2 for validation.

It should be fixed now.

**Comment by javiercn** [comment]
@SteveSandersonMS I validated this.

Do you feel strongly we need a test for this?

**Comment by SteveSandersonMS** [comment]
> Do you feel strongly we need a test for this?

Seems like we do have a test for this, except it only makes a limited set of assertions and doesn't try to execute the published app.

If you think it fits into our test pattern to execute the standard browser automation test against the result of this publish test, then that would be great, but if it's going to be expensive to do then I wouldn't necessarily give it more priority than other scenarios.

**Comment by javiercn** [comment]
@SteveSandersonMS yeah, I think it would be expensive to do it here and I'm not sure of the ROI. If we end up hitting this more times we can add it to the template tests, but I'm not sure many customers do this.
