### ISSUE TITLE
[Feature Request] Razor Class Library - Support 'Add Client-Side Library...'

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#18209]
Please consider adding support for the 'Add Client-Side Library...' menu when developing a Razor Class Library so that 3rd party javascript etc. may be adding in the same manor as they are to web sites/applications projects.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the VS Feedback to report this issue, so the team who owns the area can track the ask.
