### ISSUE TITLE
Scaffolded Identity "Manage" Layout Refers to Unscaffoldable Layout Page

### ISSUE THREAD

**Issue by pm64** [dotnet/aspnetcore#18200]
### Describe the bug
The scaffolded Areas\Identity\Pages\Account\Manage\\_Layout.cshtml page references "/Areas/Identity/Pages/_Layout.cshtml" as its layout. This page is not present in the project template and is not available for scaffolding.

### To Reproduce
1. In VS2019, create a new ASP.Net Core web application using "Individual User Accounts" authentication
2. Right-click project node in Solution Explorer, select Add | New Scaffolded Item...
3. Use the scaffolder to add the Identity page Areas\Identity\Pages\Account\Manage\_Layout.cshtml to the project
4. Observe that the generated _Layout.cshtml references "/Areas/Identity/Pages/_Layout.cshtml" as its layout. This page does not exist in the project template and is not itself available for scaffolding.

### Notes
- A workaround is to change the layout to "/Pages/Shared/_Layout.cshtml", a page that does reside in the project template. But I don't believe this is the intended layout (though it may be very similar), since "Areas\Identity\Pages\Account\Manage\_Layout.cshtml" does get rendered at runtime. The intended layout appears to be imprisoned in the Identity DLL.

### Further technical details
- ASP.NET Core version 3.1
- Output of `dotnet --info`:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:
Visual Studio Enterprise 2019  v16.4.2

**Comment by blowdart** [comment]
@danroth27  This seems to be blazor specific.

**Comment by pm64** [comment]
@blowdart @danroth27 I thought so at first, but then confirmed that traditional web apps are also affected. What leads you to this conclusion? It's quite possible I missed something.

**Comment by blowdart** [comment]
Ah that wasn't clear from the issue, as the one you linked to was blazor and no-one has brought this up before.

**Comment by blowdart** [comment]
@javiercn Is this a bug, or are we missing something?

**Comment by javiercn** [comment]
@blowdart That sounds like a bug.

The scaffolder should detect (within reason) whether the user is using the included layout or has overridden it with the one on the page and provide the path to the right layout on the scaffolded code.

(It can determine what layout is being used by the presence of the _ViewImports file in `/Areas/Identity/Pages`)

**Comment by blowdart** [comment]
@anurse Can you move this to scaffolding repo please?

**Comment by pm64** [comment]
@blowdart can we remove the area-blazor tag? While Blazor is affected, I don't want this bug to get clumped in with existing known scaffolding issues in Blazor.

**Comment by anurse** [comment]
This issue was moved to aspnet/Scaffolding#1225
