### ISSUE TITLE
Blazor/ASP.NET Core Windows/Linux CultureInfo mismatch

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/aspnetcore#18215]
I have written a small Blazor WASM application (.NET Core 3.1 initial release) to compare CultureInfo objects available in WASM with those available on the server (ASP.NET Core). I'm using this simple query to retrieve all cultures:
```c#
CultureInfo.GetCultures(CultureTypes.AllCultures).OrderBy(c => c.Name, StringComparer.Ordinal);
```
For some cultures in WASM calendar is not defined and exception is thrown when you try to access `DateTimeFormat`. I'm using this simple loop to have only cultures with calendars:
```c#
foreach (CultureInfo ci in allCultures)
{
    try
    {
        if (!string.IsNullOrEmpty(ci.DateTimeFormat.ShortDatePattern))
            selectedCultures.Add(ci);
    }
    catch (Exception)
    {
    }
}
```
I compare only a few DateTimeFormat and NumberFormat properties. Application is available online here: http://culturecompare.azurewebsites.net
The are a lot of problems. First in WASM I have far less cultures available. What is interesting number of cultures available in .NET Core running on Windows is different than number of cultures on Linux. Application available here http://culturecompare.azurewebsites.net runs in Linux, it is configured for .NET Core 3.1 and this is screenshot

![obraz](https://user-images.githubusercontent.com/32604409/72027609-fa4ff180-327f-11ea-8596-e796f797a817.png)

The same application on my laptop (Windows 10 1903)

![obraz](https://user-images.githubusercontent.com/32604409/72027668-2cf9ea00-3280-11ea-8231-4b4bb2be6e66.png)
As you can see there are more cultures on Windows.
There are buttons on the right - if the button is red it means that there are some inconsistencies. You can click it to display something like this:

![obraz](https://user-images.githubusercontent.com/32604409/72027884-e062de80-3280-11ea-909b-4cbe973e780b.png)

This inconsistency in culture definitions will create an interesting visual effect in applications which will use prerendering. First we will see dates/times/numbers formatted on the server and after a while it will be replaced with something that looks different. Please note that some cultures have completely different date formats or different currency symbols!!!

There is one more problem which is probably even worse. You can write application which will read information from Accept-Language HTTP header and use it to format dates/times/numbers. You can send information about culture selected by the server to the Blazor app in hope that Blazor will use it. Unfortunately there are some cultures which simply don't exist in WASM implementation or don't have calendars defined so any attempt to read DateTimeFormat information throws exception.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Andrzej-W.
This is not something the framework has a say in.
It comes from the underyling platforms (WASM, Windows and Linux) and the cultures they have/support are indeed different. Mono WASM does some customization regarding these and you can learn more about that by posting a question in their repo: https://github.com/mono/mono
