### ISSUE TITLE
Make the CircuitHost public 

### ISSUE THREAD

**Issue by rpskelton2** [dotnet/aspnetcore#18210]
I have a custom CircuitHandler in a Blazor server project that I'm using to detect when a circuit closes.  When the circuit closes there may be some stateful information I'd like to store into redis for the next time that user connects.  The internal Circuit._circuitHost object that is passed to the CurcuitHandler contains all the information I need but I can only get to it via reflection.

Was it just thought that this would not be needed by 3rd parties or is there an explicit danger in accessing the CircuitHost object?  I am currently using a reflection hack to get to it but that's obviously not ideal.

**Comment by rynowak** [comment]
We will not make `CircuitHost` public. Please don't use reflection to access framework internal, we will not offer support if you encounter bugs, and we **will** break your code in patch releases without notice.

Can you be more specific about what you want to do so we can help you? `Circuit` exposes an `Id` property so you can uniquely track it.

**Comment by rpskelton2** [comment]
We are creating a server side blazor app to front-end legacy business objects currently used in a large wpf application.  These business objects can be quite sizable (100+ meg).  If the user is in the middle of editing a business object and loses connection (say they turn airplane mode on) we’d like to serialize the modified business object and de-serialize it the next time they connect.  Because these objects are so large it’s not practical to serialize them every time a small change is made (like evert time a field on a form is modified).  The idea is to only serialize the business object if the circuit is closed (and the business object is dirty).


public class CircuitHandlerService : CircuitHandler, ICircuitHandler
{
	public override Task OnCircuitClosedAsync(Circuit circuit, CancellationToken cancellationToken)
	{
		var businessObj = circuit._circuitHost.GetService<BusinessObj>();
		if(businessObj?.Dirty == true)
		{
			// Serialize
		}
	}
}


On a side note…  Given that the CircuitHandler doesn’t expose much other than a circuit id what practical use is there for creating a custom one?  Besides possibly logging the fact that a circuit state has changed what sort of use is this intended for?

**Comment by rynowak** [comment]
>  The idea is to only serialize the business object if the circuit is closed (and the business object is dirty).

So based on your code sample, it sounds like what you need is access to the service associated with the circuit. Is that right? This seems reasonable.

> On a side note… Given that the CircuitHandler doesn’t expose much other than a circuit id what practical use is there for creating a custom one? Besides possibly logging the fact that a circuit state has changed what sort of use is this intended for?

It was one of the first features we designed, and it's intended for usage like yours. I think at the time we added it, there were some other services you could see to peek inside the service collection.

**Comment by pranavkm** [comment]
Hi @rpskelton2, you should be able to DI in services from the current scope as part of your circuit handler. In your case, something like this should work:

```C#
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddScoped<BusinessObj>();
    services.AddScoped<CircuitHandler, MyHandler>();
}

public class BusinessObj
{
    public Task DoThing() => Task.CompletedTask;
}

public class MyHandler : CircuitHandler
{
    private BusinessObj service;

    public MyHandler(BusinessObj service)
    {
        this.service = service;
    }

    public override async Task OnCircuitClosedAsync(Circuit circuit, CancellationToken cancellationToken)
    {
        await service.DoThing();
    }
}
```

Does this help in this particular scenario?

**Comment by rpskelton2** [comment]
I will give this a try.  Thank you!

On a side note, it seems that simply implementing IDisposable on my BusinessObj service (AddScoped) allows me to accomplish the same thing.  Just check for .Dirty in the Dispose method and serialize to redis there.  Do you see any benefits to using a CircuitHandler over that?

**Comment by pranavkm** [comment]
The events on the `CircuitHandler` are a bit clearer about the intent compared to object initialization and disposal, but I can't think of a very good reason why you wouldn't be able to use disposal to do work. If you're serializing to Redis, implementing `IAsyncDisposable` on your service might be more appropriate.

**Comment by rpskelton2** [comment]
@pranavkm, thank you for your help.  I'm going to close this since I now have multiple ways to solve.
