### ISSUE TITLE
Questions about nuget package reference of Microsoft.AspNetCore.Mvc or Microsoft.AspNetCore.Mvc.Core

### ISSUE THREAD

**Issue by ldqk** [dotnet/aspnetcore#18225]
When I was referenced nuget package called Microsoft.AspNetCore.Mvc to develop a class, and my class that inherits from [`VirtualFileResultExecutor`](https://github.com/dotnet/aspnetcore/blob/f8da3e2e331833ff23f8f4ad6ab45c900a362f4b/src/Mvc/Mvc.Core/src/Infrastructure/VirtualFileResultExecutor.cs#L22), and my class needs to implement the constructor of [`VirtualFileResultExecutor`](https://github.com/dotnet/aspnetcore/blob/f8da3e2e331833ff23f8f4ad6ab45c900a362f4b/src/Mvc/Mvc.Core/src/Infrastructure/VirtualFileResultExecutor.cs#L22) class. The constructor of [`VirtualFileResultExecutor`](https://github.com/dotnet/aspnetcore/blob/f8da3e2e331833ff23f8f4ad6ab45c900a362f4b/src/Mvc/Mvc.Core/src/Infrastructure/VirtualFileResultExecutor.cs#L22) requires a parameter of type IHostingEnvironment, and IHostingEnvironment has been marked as Obsolete and replaced with IWebHostEnvironment in .net core 3.1, but when I check your github source code, I found that the constructor of [`VirtualFileResultExecutor`](https://github.com/dotnet/aspnetcore/blob/f8da3e2e331833ff23f8f4ad6ab45c900a362f4b/src/Mvc/Mvc.Core/src/Infrastructure/VirtualFileResultExecutor.cs#L22) is already an IWebHostEnvironment type parameter. Does the latest released nuget package not contain the latest code of [`VirtualFileResultExecutor`](https://github.com/dotnet/aspnetcore/blob/f8da3e2e331833ff23f8f4ad6ab45c900a362f4b/src/Mvc/Mvc.Core/src/Infrastructure/VirtualFileResultExecutor.cs#L22)?
nuget package:[nuget:https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc)
![image.png](https://i.loli.net/2020/01/09/6O7amyQ32icFhPq.png)

**Comment by pranavkm** [comment]
Hi @ldqk, the 3.1 API reference looks fine: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.infrastructure.virtualfileresultexecutor.-ctor?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_Infrastructure_VirtualFileResultExecutor__ctor_Microsoft_Extensions_Logging_ILoggerFactory_Microsoft_AspNetCore_Hosting_IWebHostEnvironment_. It looks like you're referencing the 2.2 version of the package.

To upgrade your project to reference ASP.NET Core 3.0 or later, please follow our migration guide: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio

**Comment by ldqk** [comment]
That's right! But I have been installed .NET Core 3.1 SDK and Runtime,and my project has been upgraded latest target framework .NET Standard 2.1 also, and project referenced nuget package `Microsoft.AspNetCore.Mvc` version is 2.2.0, The .NET Core 3.0 released at 11/19/2019, but I checked nuget package `Microsoft.AspNetCore.Mvc` and `Microsoft.AspNetCore.Mvc.Core` on https://www.nuget.org, they are published at 2018/12 and 2019/05. So could you published the packages to compatible .NET Standard 2.1？ 
Reference：
nuget：https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Core/
Source by decompiled：
![image.png](https://i.loli.net/2020/01/10/4AEzwHdqolmQVrL.png)
My project properties:
![image.png](https://i.loli.net/2020/01/10/uLIm2QHPvE4gdTk.png)
My project reference packages:
![image.png](https://i.loli.net/2020/01/10/7y2x4lrCFWocNsa.png)
