### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#18229]
Hello,

Now that a new year is beginning (!), I am wondering if an update of the milestone information could be made for this project.:smile: I hope this is Ok.

Closed Milestones
--------------------------
A. _3.1.0-preview1_: There is still 1 opened issue. Can it be closed? What is the status?
B. _3.1.0-preview3_: There are still 3 opened issues. Can they be closed? What are their statuses?

Opened Milestones
--------------------------
C. _2.2.x:_ Can it be moved to Closed Milestone? Is it still required?
D. _3.0.1_: Can it be moved to Closed Milestone?
E. _Done_: What is the goal of this Milestone?

Thank you for your answers.

**Comment by Pilchie** [comment]
Tagging @mkArtakMSFT who usually cleans up milestones.

**Comment by boukenka** [comment]
Is it possible to get a feedback ? 😄

**Comment by pranavkm** [comment]
@boukenka thanks for reporting this. 

* The 3.1 preview, 2.2.x, and 3.0.1 milestones have since been closed.
* The Done milestone was likely an accident (We use the Done *label* for issues).

**Comment by boukenka** [comment]
Thank you @pranavkm. I am closing this issue.
