### ISSUE TITLE
Blazor File upload

### ISSUE THREAD

**Issue by etherealjoy** [dotnet/aspnetcore#18227]
There are multiple solutions out there for uploading files with Blazor. However is it planned to have an inbuilt Blazor element that can perform this operation and which is user extensible?

### Is your feature request related to a problem? Please describe.

This is a feature request and not related to a problem since we can basically write our own to perform file upload. But would be great to not have to invent the wheel every time.

### Describe the solution you'd like

The best way in my opinion is to have a generic element which can be extended by the user, because this is a basic feature needed almost everywhere and it does not makes sense for everyone to have to write their own stuff every time just to perform a basic operation. It is a very ubiquitous feature . 
Having a js free reusable element is a big plus in my opinion in Blazor.

### Additional context

There is blog from @SteveSandersonMS which highlight one way this is achieved. 
I tried using it and it is very intuitive. However it is not aligned to dotnet core 3.1.

https://github.com/SteveSandersonMS/BlazorInputFile

https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We do have an existing issue tracking a similar ask: https://github.com/dotnet/aspnetcore/issues/17056
So we're closing this issue in favor of the referenced one.

**Comment by etherealjoy** [comment]
OK thanks
