### ISSUE TITLE
[Blazor Server] Static assests are still not working properly for other extension names.

### ISSUE THREAD

**Issue by AlseinX** [dotnet/aspnetcore#18222]
### Describe the bug
Static assets in `wwwroot` with `.js` or `.css` extensions works fine.

But files with other extension names are still 404

### To Reproduce
Create a project with razor class library template
Put `main.less` in `wwwroot/style/` folder
A razor component references it by `<link rel="stylesheet/less" type="text/css" href="_content/ASSEMBLYNAME/style/main.less" />`
Create a blazor server project to use the component
The request to `main.less` results in 404.

### Further technical details
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by AlseinX** [comment]
The problem is located in `Startup.cs`
Setting the `ServeUnknownFileTypes` property to `true` does make it possible to access the files with other extensions:
```
 app.UseStaticFiles(new StaticFileOptions { ServeUnknownFileTypes = true });
```
BUT, `blazor.server.js` becomes 404 now.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
This has nothing to do with static web assets but with the static files middleware being incorrectly configured.

You need to configure the StaticFileOptions with the with a content type provider 
 that contains your extension. See `FileExtensionContentTypeProvider` for details.
