### ISSUE TITLE
Count how many blazor - signalR connections are currently opened

### ISSUE THREAD

**Issue by Blackleones** [dotnet/aspnetcore#18231]
Using Blazor Server-Side, is possible to know how many users (signalR connections) are currently connected?

I would create a singleton service with a very simple logic:  the service increments / decrements a counter whenever it receives an event like "new connection attempt" / "connection closed"

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by pranavkm** [comment]
Hi @Blackleones, you could use the connection-up and connection-down events on a `CircuitHandler` to keep track of this. You can [register a singleton instance](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/ComponentsApp.Server/Startup.cs#L17) of a `CircuitHandler`  and use these events to track connections being set up and torn down. Note that there is a bug where the connection down events sometimes get invoked twice: https://github.com/dotnet/aspnetcore/issues/18242, so you'd have to account for this in some way.
