### ISSUE TITLE
CircuitHost.OnConnectionDownAsync executes twice on closing

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18242]
Makes it hard to use reliably

**Comment by rynowak** [comment]
Do you know the repo? or just that it always removes two connections?

**Comment by pranavkm** [comment]
I think it's when you closed the browser tab (i.e. when it gracefully closed the circuit), but I'm not 100% certain that's the only scenario this happens.

**Comment by rynowak** [comment]
It's not tied to that, it's ignitor doing it in my case.

**Comment by mkArtakMSFT** [comment]
@pranavkm is there anything to be done in 5.0 here?

**Comment by pranavkm** [comment]
It's a bug, we should fix it. The one data point I have for this, is that we've only had one report of this so far.

**Comment by pranavkm** [comment]
Closing this as we haven't seen any additional feedback for this issue.
