### ISSUE TITLE
Blazor Cast List<T>

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#18245]
I have this class:

````csharp
  public class SupplierDto : INavigationListItem
````
I have a list of SupplierDto Deserilized from a json string:
````csharp
List<SupplierDto> dto = JsonSerializer.Deserialize<List<SupplierDto>>(responseString);
````
And i want to cas it do I did that:
````csharp
List<INavigationListItem> Items = _entities..Cast<INavigationListItem>().ToList();
````

I get this error:

blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: System.InvalidCastException: Specified cast is not valid.
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () <0x2271278 + 0x00068> in <b51c1933184d4dceadd1b43b1badf1d6>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) <0x2270ed8 + 0x00084> in <781da9efd6db41878e0251092c3ff5e1>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) <0x2270d18 + 0x00092> in <781da9efd6db41878e0251092c3ff5e1>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) <0x2270b38 + 0x0002a> in <b51c1933184d4dceadd1b43b1badf1d6>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Client.Pages.Settings.SuppliersBase.OnInitializedAsync () [0x00166] in C:\Team Foundation\Graphene\Client\Pages\Settings\Suppliers.razor.cs:32 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x1eb6968 + 0x0014c> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x21c1668 + 0x000c2> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0 
h.printErr @ blazor.webassembly.js:1

I tried some variant like 

````csharp
List<INavigationListItem> Items = _entities.AsEnumerable()..Cast<INavigationListItem>().ToList();
````

but the result is the same;

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

We think this is a mono issue, I would suggest you file an issue in the [mono repo](https://github.com/mono/mono) as they will be able to give you a faster and better answer.

We would also suggest you try a couple of things:
* Does this code snippet work in .NET Core?
* What happens if you call OfType instead of cast. Do you get an empty result set?

**Comment by JulienM28** [comment]
both of these solutions are working:

````csharp
Items = _entities.OfType<INavigationListItem>().ToList();
Items = _entities.Select(s => s).ToList<INavigationListItem>();
````

**Comment by JulienM28** [comment]
It's working now
