### ISSUE TITLE
Access UIHint attribute from TagHelper

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#18257]
I use this code in my `TagHelper`:
```c#
ModelMetadata metadata = _htmlHelper.MetadataProvider.GetMetadataForProperty(type, Property);
```
but the `ModelMetadata` does not seem to have eg the `UIHintAttribute`. How can I access this from my helper? I would like to read the presentation layer and controlParameters.

**Comment by marcuslindblom** [comment]
It seems to work like this:
```c#
var uiHint = ((DefaultModelMetadata)metadata).Attributes.Attributes.OfType<UIHintAttribute>().FirstOrDefault();
```
... but is this the way to do it?

**Comment by javiercn** [comment]
@marcuslindblom thanks for contacting us.

I don't see any issue with the way you are doing it (other than the downcast).

You can probably get it from `metadata.TypeOrUnderlyingType.Attributes` if you wanted to avoid the downcast.

Hope that helps.
