### ISSUE TITLE
Adjust PasswordOptions defaults to be more in-line with NIST recommendations

### ISSUE THREAD

**Issue by garrettjoecox** [dotnet/aspnetcore#18269]
### Is your feature request related to a problem? Please describe.
The default password options set in [/src/Identity/Extensions.Core/src/PasswordOptions.cs](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/PasswordOptions.cs) are not in-line with the the current recommendations from the NIST, [See section 5.1.1.2 here](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5). This is a problem because projects using this library likely stick with the defaults, compromising their user's password security encouraging weak passwords.

### Describe the solution you'd like
Make the following changes to defaults:
```
RequiredLength = 8;
RequireNonAlphanumeric = false;
RequireLowercase = false;
RequireUppercase = false;
RequireDigit = false;
```

**Comment by blowdart** [comment]
The NIST guidelines also talk about forcing 2fa but that would be a burden a lot of customers don't want to carry. Given that we don't implement protection against stuffing nor do we implement checks against already breached usernames and passwords the advice, whilst I can see their argument, doesn't really fit. Customers are free to change the requirements as they wish.
