### ISSUE TITLE
[Question:Blazor] How would I detect if my code is running client side?

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#18268]
Q: How would I detect if my code is running client side within a browser (wasm-runtime)
is it possible to use RuntimeInformation.IsPlatform ?

**Comment by javiercn** [comment]
@grahamehorner thanks for contacting us.

You can do this with
```csharp
RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))
```

**Comment by pavelsavara** [comment]
`RuntimeInformation.IsOSPlatform(OSPlatform.Create("Browser"))` worked for me
