### ISSUE TITLE
returning this.Ok( null ) shows last successful request

### ISSUE THREAD

**Issue by Jelgab** [dotnet/aspnetcore#18267]
# Issue Title

returning this.Ok( null ) shows last successful request

# General
Version: .Net Core 3.1
OS: Windows 10. Version 10.0.18362.535
Editor: Visual Studio 2019 16.4.0

(Tried on two different machines, two different API projects)

When a controller is trying to return this.Ok( someObject ), if the value of the object is null, it will not show any error: It will return the result of the last successful request for that controller.

Steps:
1. Add a new controller
2. Add a method that successfully returns a simple value
3. Add a method that returns this.Ok( null )
4. Request first method. See that the result is returned as expected
5. Request second method that returns this.Ok( null ). No error will be shown, the result from the last successful request will be shown. It might be a different method (like in this case) or the same method, with the result of the last time there was a non-null result.

Code example:
```
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    [HttpGet("Version")]
    public IActionResult Version() => this.Ok( "Weather Controller version 1.0.1" );

    [HttpGet("TestOne")]
    public async Task<IActionResult> TestOne() {
        await Task.Delay( 1 );

      //return this.Ok( "Fixed value for Test One. 001" );
        return this.Ok( null );
    }

    [HttpGet("TestTwo")]
    public IActionResult TestTwo() {

      //return this.Ok( "Fixed value for Test Two. 001" );
        return this.Ok( null );
    }
}
```

![Ok_Null_Returns_Previous_004](https://user-images.githubusercontent.com/1036858/71916012-fa9aa080-314a-11ea-9c93-f848709e6b6f.gif)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Jelgab.
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@Jelab it's likely returning a [204](https://github.com/dotnet/aspnetcore/issues/8847) the second time around. Can you use a REST client and verify this or look at the browser network tab? It's likely returning the browser doesn't update when it sees a 204 response.

**Comment by Jelgab** [comment]
Note: If possible, please reply to GabrielHenao222@Yahoo.Com since my original email gets too much spam.

@pranavkm , yes, with a REST client, it returns a 204, but the other part you say doesn't seem to happen: You say the browser doesn't update, but the browser is changing the route (see the gif I attached when I created the ticket). I call /version, then call /testOne, then there's a redirect to /version. It still can be the browser's fault though. Thank you.

c.c. @mkArtakMSFT 
![2020-01-10_18-49-10 - Returning a 204](https://user-images.githubusercontent.com/1036858/72194191-b1f91680-33da-11ea-849a-c4e5eff99cc0.jpg)

**Comment by pranavkm** [comment]
@Jelgab this looks like a browser behavior, not related to MVC.
