### ISSUE TITLE
SQL Server access behavior changed in 3.x.x (sni.dll missing)

### ISSUE THREAD

**Issue by RomBrz** [dotnet/aspnetcore#18266]
# Issue Title

.NET Core 3.x.x didn't come with the DLL "sni.dll" inside of Microsoft.AspNetCore.App folder. .NET Core 2.x.x and prior come with that.

# General

Since the DLL sni.dll didn't come natively with .NET Core 3.x.x, we were facing problems with SQL Server connections. After troubleshooting, we discover that the developer need to put the dll inside his application code, and give execute permission to work.
The same application using .NET Core 2.x.x didn't need that, because of the sni.dll came inside "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App".
We are facing problems because of the lower permission given to the Application Pool Identity (read only).

# Workaround

I copied the sni.dll from "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.8" to "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3x.x" and the applications running .NET Core 3.x.x could run with "Read Only" permission on project folder (the same behavior that works with 2.x.x projects).

# Question

Why the sni.dll isn't coming with .NET 3.x.x? This is expected? 

PS: I'm not a dev, i'm like a "opsdev" (as oposite to devops LOL) so i work helping devs publishing their codes, so i'm sorry if it's a "trivial thing" for a dev.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @RomBrz.
@ajcvickers do you know what this assembly is and who is best positioned to look into this? Thanks!

**Comment by ajcvickers** [comment]
@RomBrz This comes with Microsoft.Data.SqlClient, which is maintained here: https://github.com/dotnet/SqlClient It may already be covered by one of the [existing issues](https://github.com/dotnet/SqlClient/issues?q=is%3Aissue+SNI+is%3Aopen)--there have been several people hitting issues with SNI.dll. If not, then please file a new issue there.
