### ISSUE TITLE
Date response header cannot be cleared

### ISSUE THREAD

**Issue by msft-mw** [dotnet/aspnetcore#18270]
I have a project where I want to set `Cache-Control: no-cache, no-store`, which I'm able to do by adding a middleware item.

But when I was testing, I noticed that calls were returning a `Date` header automatically. I tried clearing the header by setting its value to `StringValues.Empty` and it still shows up. It's not a deal-breaker I guess, but it's weird to me to have it when I'm setting `no-cache, no-store` at the same time.

The repro I used was the default aspnetcore 3.1 API project that returns weather elements, and then hooking this bit of code into the `Startup.Configure` method:

```csharp
if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseAuthorization();

            app.Use(
                async (ctx, next) =>
                {
                    ctx.Response.OnStarting(
                        () =>
                        {
                            ctx.Response.GetTypedHeaders().CacheControl = new CacheControlHeaderValue
                            {
                                NoCache = true,
                                NoStore = true
                            };

                            ctx.Response.Headers[HeaderNames.Date] = StringValues.Empty;

                            return Task.CompletedTask;
                        });

                    await next();
                });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
```

The response headers:

```
curl http://localhost:5000/weatherforecast -v     
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /weatherforecast HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 10 Jan 2020 18:03:45 GMT
< Content-Type: application/json; charset=utf-8
< Server: Kestrel
< Cache-Control: no-store, no-cache
< Transfer-Encoding: chunked
<
* Connection #0 to host localhost left intact
[{"date":"2020-01-11T10:03:46.105218-08:00","temperatureC":39,"temperatureF":102,"summary":"Cool"},{"date":"2020-01-12T10:03:46.1052497-08:00","temperatureC":20,"temperatureF":67,"summary":"Hot"},{"date":"2020-01-13T10:03:46.1052504-08:00","temperatureC":1,"temperatureF":33,"summary":"Mild"},{"date":"2020-01-14T10:03:46.1052508-08:00","temperatureC":39,"temperatureF":102,"summary":"Bracing"},{"date":"2020-01-15T10:03:46.1052512-08:00","temperatureC":5,"temperatureF":40,"summary":"Mild"}]
```

Is there a way to prevent Kestrel from setting the `Date` header?

**Comment by blowdart** [comment]
Date is mandatory (except in the edge case where your server doesn't have a clock)

_[7.1.1.2. Date](https://tools.ietf.org/html/rfc7231#section-7.1.1.2)

An origin server MUST NOT send a Date header field if it does not have a clock capable of providing a reasonable approximation of the current instance in Coordinated Universal Time. An origin server MAY send a Date header field if the response is in the 1xx (Informational) or 5xx (Server Error) class of status codes. An origin server MUST send a Date header field in all other cases.

Note the last sentence of the quote. The Date header field MUST be sent if the origin server is capable of providing a "reasonable approximation" of the date in UTC, but there is nothing stopping a server from misrepresenting itself._
