### ISSUE TITLE
Improve SVG support in Blazor

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18271]
Treating this as the top-level issue for SVG support in Blazor to track

**Comment by pablofrommars** [comment]
SVG support has nicely been working for me until I started experimenting with foreignObject.

A possible workaround until "full support" is to render your problematic content as [raw html](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#raw-html]) using MarkupString:

```razor
<svg>
    @((MarkupString)$"<foreignObject>Hello, <em>{@name}</em>!</foreignObject>")
</svg>

@code {
    private string name = "World";
}
```

Hope it helps prevent a few headaches!

**Comment by pablofrommars** [comment]
CultureInfo can interfere with SVG rendering, specifically which decimal separator is used. Probably quite tricky to handle, how to feed SVG properties (or CSS for that matter) with the expected number formatting while retaining Blazor ability to localize content? Important feature for full SVG support.

**Comment by mkArtakMSFT** [comment]
I've duped all the svg-related issues with this one. We should make sure all those concerns are considered when handling this.

**Comment by dmitry-pavlov** [comment]
@MikaBerglund has shared in our [ASP.NET Core community](https://www.facebook.com/groups/about.asp.net.core/permalink/1584960758348572/) the blog [Configure Offline Assets for Blazor PWA Applications] (https://mikaberglund.com/2020/05/26/configure-offline-assets-for-blazor-pwa-applications) which explains how to add `SVG` support . 

What would adding "SVG support in Blazor" mean in scope of this issue? @captainsafia

**Comment by MarkusRodler** [comment]
@dmitry-pavlov All of those issues that are referenced in this issue. For example this one: 
https://github.com/dotnet/aspnetcore/issues/13280

**Comment by captainsafia** [comment]
Correct: I'll update the issue title to reflect this but this particular issue is really about addressing the known gaps in our existing SVG support.

**Comment by Thaina** [comment]
Is this issue also include autocomplete for svg in razor file?

**Comment by captainsafia** [comment]
@Thaina Not explicitly. I'd recommend opening an issue with a clear description of what you'd like to see that we can dupe against this one.

**Comment by Thaina** [comment]
@captainsafia Thanks, but I think it should be include in the term "improve svg support"

It was nothing much, just that I wish that while html element could be shown in vscode autocomplete in `.razor` file like this

**Comment by Ted-Lapkin** [comment]
Not sure if this has been covered or not, but within .Net 5, using something like
`<svg class="bi" width="26" height="26" fill="currentColor">
    <use xlink:href="bootstrap-icons.svg#house-fill" />
</svg>`
works fine, but using a variable within the href
`<svg class="bi" width="26" height="26" fill="currentColor">
    <use xlink:href=@($"bootstrap-icons.svg#{HouseFill}") />
</svg>`
causes it to not render on the page.

**Comment by dmitry-pavlov** [comment]
> Not sure if this has been covered or not, but within .Net 5, using something like
> `<svg> <use xlink:href="bootstrap-icons.svg#house-fill" /> </svg>`
> works fine, but using a variable within the href
> `<svg> <use xlink:href=@($"bootstrap-icons.svg#{HouseFill}") /> </svg>`
> causes it to not render on the page.

@Ted-Lapkin it should be something like this I guess (note wrapping quotes): 

`<use xlink:href="@($"bootstrap-icons.svg#{HouseFill}")" />`

**Comment by dennisreimann** [comment]
I noticed that referencing a file with the `~` doesn't work for the `href` and `xlink:href` attributes of a `use tag`. Also it'd be good to have support for the `asp-append-version="true"` attribute here.

**Comment by MaxNau** [comment]
Hi,

is this supported at the moment? If not, any plans when it will?

`<foreignObject>
         @foreach (var htmlTag in HtmlTags)
          {
              @((MarkupString)htmlTag)
          }
</foreignObject>`

**Comment by jongio** [comment]
Looks like LinearGradient isn't support:


```
<svg data-slug-id="storage" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 18 18">
  <defs>
    <linearGradient id="storage:ad4c4f96-09aa-4f91-ba10-5cb8ad530f74" x1="9" y1="15.83" x2="9" y2="5.79" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#b3b3b3"/>
      <stop offset="0.26" stop-color="#c1c1c1"/>
      <stop offset="1" stop-color="#e6e6e6"/>
    </linearGradient>
  </defs>
   
  <path d="M.5,5.79h17a0,0,0,0,1,0,0v9.48a.57.57,0,0,1-.57.57H1.07a.57.57,0,0,1-.57-.57V5.79A0,0,0,0,1,.5,5.79Z" fill="url(#storage:ad4c4f96-09aa-4f91-ba10-5cb8ad530f74)"/>
  <path d="M1.07,2.17H16.93a.57.57,0,0,1,.57.57V5.79a0,0,0,0,1,0,0H.5a0,0,0,0,1,0,0V2.73A.57.57,0,0,1,1.07,2.17Z" fill="#37c2b1"/>
  <path d="M2.81,6.89H15.18a.27.27,0,0,1,.26.27v1.4a.27.27,0,0,1-.26.27H2.81a.27.27,0,0,1-.26-.27V7.16A.27.27,0,0,1,2.81,6.89Z" fill="#fff"/>
  <path d="M2.82,9.68H15.19a.27.27,0,0,1,.26.27v1.41a.27.27,0,0,1-.26.27H2.82a.27.27,0,0,1-.26-.27V10A.27.27,0,0,1,2.82,9.68Z" fill="#37c2b1"/>
  <path d="M2.82,12.5H15.19a.27.27,0,0,1,.26.27v1.41a.27.27,0,0,1-.26.27H2.82a.27.27,0,0,1-.26-.27V12.77A.27.27,0,0,1,2.82,12.5Z" fill="#258277"/>
</svg>
```


Should be:

![image](https://user-images.githubusercontent.com/2163001/114288767-d3561180-9a26-11eb-9cbc-7a7291312b1d.png)



Renders as:

![image](https://user-images.githubusercontent.com/2163001/114288775-e537b480-9a26-11eb-83c1-f7cd31c4e352.png)


With
`<img src="imgs/@item.Icon">`

**Comment by Xyncgas** [comment]
I actually would like to pick up my drawing talbet and draw svg directly in visual studio, put that aside, it would be like if we can have a svg animation designer/work flow for stepping up the game of website appearances

**Comment by jongio** [comment]
@guardrex - I noticed that you closed this item in ref to 22450.  I wanted to make sure that gradient support didn't get lost in that.  Do we have that captured somewhere else?

**Comment by guardrex** [comment]
The PU issue (here) tracks the framework work ... which is done, and the docs issue tracks the doc work, which is still open and hasn't been done. That issue will probably be worked in the RC1 timeframe ... due to churn ... we've been burned a few times trying to doc things too early before the feature settles for release. The docs issue cross-links this, so this won't get lost.

**Comment by guardrex** [comment]
... but btw if you're referring to this issue being closed **_before_** the framework has a gradient feature that you don't think the preview work covers, then you'd need to take that up with the PU here. The docs issue is only that ... for docs. It doesn't address anything over here.

**Comment by gulbanana** [comment]
The linearGradient svg works for me in .NET 6 preview 4 when embedded directly in a .razor file.

**Comment by jongio** [comment]
Can you see if it works when you ref with <img src="name.svg" >?
