### ISSUE TITLE
Blazor WebAssembly not building

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#18276]
using dotnet new blazor template code fails to build

1>------ Build started: Project: WASM, Configuration: Debug Any CPU ------
1>**[REMOVED]**\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets(184,5): error : rzc generate exited with code 1.
1>Done building project "WASM.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by pranavkm** [comment]
`microsoft.aspnetcore.blazor.build\0.7.0` 0 that looks an [incredibly old](https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Build) version of the package. You probably need to update

**Comment by grahamehorner** [comment]
@pranavkm thanks for the reply, the package was installed using the originally using the nuget package https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor/ then updated via https://marketplace.visualstudio.com/items?itemName=aspnet.blazor in VisualStudio 
I now see this is the **wrong way** to install Blazor by reviewing the comments in the gallery;
maybe **obsolete** gallery items need to be reflected in a different way inside VisualStudio to avoid issues.
 
I've since removed the extensions and updated the template package to the latest preview and this has corrected the issue.

thanks again
