### ISSUE TITLE
Errors and crashes during development and debugging at .Net Core3.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18281]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/878467/在net-core31开发调试时出现错误并导致死机.html)._

---
When developing a BLAZOR project, if a component member is an empty type, but no default value is set to report an error during debugging. Such as:
In the SellPage.razor component
Write in SellPage.razor.cs file
```
public int? Numbers s get; set; s
```

Then call in SellPage.razor
```
@Number <span></span>
```

Error:
unhandled exception in circuit
nullable object must must have a value

The error was not located on the corresponding statement, I was also looking for a long time to find out is the above statement of the problem.
The bigger problem is that this leads to 100% cup possession and a crash, so I shut down N times.

When I fix it like this,
```
public int? Number { get; set; } = 0;
```
No more mistakes will be reported, and no more will crash.

I'm not sure if the error caused the crash to be a problem for Visual Studio or .Net Core 3.1, but it must be a problem.

---
#### Visual Studio Feedback System on 1/8/2020, 08:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Edited for clarity.

I'm not sure if this will repro. I'm not sure what our behavior for trying to render null values is, whether we don't emit anything (empty string) or whether we null ref and consider it an application error.

In case that for normal values we don't nullref and that we null ref for nullable types without a value, I think this will be a bug in how we handle nullable values. Otherwise this is by design.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
