### ISSUE TITLE
Asp.net Core project upgraded to 3.1 with Visual Studio version 16.4 not running as InProcess

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18284]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/872784/aspnet-core-project-upgraded-to-31-with-visual-stu.html)._

---
We have upgraded our .net core project from 2.1 to 3.1.0 and are using Visual studio 2019 (16.4). I was able to get the application running in local IIS but is failing to run on IIS in Demo/QA environments, throwing a generic error, &quot;HTTP Error 500.30 - ANCM In-Process Start Failure&quot;. After logging enabled found the error as below. I checked all the appsettings Json files  and they were not modified compared to the working version. Also made sure that there are no old package references. Any help is appreciated. 

<pre>&quot;Application: w3wp.exe
CoreCLR Version: 4.700.19.56106
.NET Core Version: 3.1.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException: Could not parse the JSON file.
 ---&gt; System.Text.Json.JsonReaderException: '&quot;' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 11 | BytePositionInLine: 3.
&quot;</pre>

---
#### Visual Studio Feedback System on 1/2/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Padarthi, Padmaja on 1/6/2020, 09:39 AM: 

Any help is appreciated
#### Andrew Stanton-Nurse on 1/10/2020, 03:37 PM: 

<p>This is an <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core Runtime issue rather than a Visual Studio issue, so I’m going to move it over to our GitHub repo so the whole team can see it easily. The next comment will contain a link to the issue, and someone from the team will get back to you on that thread. This ticket will be closed.</p>
<p>You can log in to GitHub and then click the “Subscribe” button on the issue to be notified of activity on the GitHub issue.</p>

---
### Original Solutions
(no solutions)

**Comment by anurse** [comment]
Are you able to attach your appSettings.json files (with any secret values removed)?

The issue is definitely that *some* JSON file is incorrect :). How are you deploying the project to your Demo/QA environment in which it is failing?
