### ISSUE TITLE
Unable identify the current Navigation Url through NavigationManager

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18282]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/875217/unable-identify-the-current-navigation-url-through.html)._

---
The navigation address cannot be identified in the razor components, if you use NavigationManager the Location Changed event is raised after the component rendering.
If there is no other way to identify the current address, the LocationChanged event must be called before rendering!

---
#### Visual Studio Feedback System on 1/5/2020, 07:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by enetstudio** [comment]
You can identify the current address like this:
`@inject NavigationManager NavigationManager
`

`var currentUrl = NavigationManager.ToBaseRelativePath(NavigationManager.Uri);`

**Comment by javiercn** [comment]
Thanks for contacting us.

@enetstudio answer is right. That's the appropriate way to do it.
