### ISSUE TITLE
Identity Cookie and [Authorize] attribute

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#18299]
### Describe the bug
Cookie AspNetCore.Identity.Application is no more used when the browser is re-opened and a call
is made on a web page having the ```@attribute [Autorize]``` attribute. The user is already logged in after that the project has been restarted in Visual Studio.

### To Reproduce
Create a project like the super :smile: Mission Control from @SteveSandersonMS.
Identity is used for the registration, login and logout.
Access to APIs is made via the JSON Web Tokens.
The ```@attribute [Authorize]``` is added on the '_Fetchdata_' page used to get the weather information. The ```[Authorize]``` attribute is also added to the API providing the weather information.

Below are the steps:

The user is signed in. The '_Fetchdata_' page is rendered. Via the initialization method, 
the data are fetched via a request. The authorization request header contains the JSON Web Token.
The cookie of the request header contains the AspNetCore.Identity.Application information.
The weather information is displayed on the page. Everything is fine.

Then the browser is closed and the project is restarted on Visual Studio. 
No logout operation has been made. The browser is started.
Based on the user.Identity.IsAuthenticated information, the user is still authenticated.
Via the LoginDisplay, the user is '_recognized_' in the ```<AuthorizeView>``` section.
This time, when the '_Fetchdata_' page is called, the request to get the data is different.
The authorization request header still contains the JSON Web Token.
But there is no more AspNetCore.Identity.Application cookie information in the request header.
The request gets a 302 response with a redirection to the Login.

Is it normal? Should not the attribute ```@attribute [Authorize]``` stops from the beginning to access to the '_Fetchdata_' page after reopening the browser? The cookie for AspNetCore.Identity.Application is still present in the local storage of the browser.

If the ```@attribute [Authorize]``` is removed, the weather information is displayed on the page.

I would just like to understand the logic in this scenario.

### Further technical details
ASP.NET Core version 3.1.
Microsoft Edge 81.0.381.0
It's a Blazor Web Assembly with ASP.NET core hosted.
Visual Studio 16.5.0 Preview 1.0.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by mkArtakMSFT** [comment]
@blowdart after reviewing this with the team this looked like non-Blazor specific and the behavior seems to be expected. We've asked the original author to ask this question in `StackOverflow` as that would be a faster way to get this answered. Re-marking as `area-security` in case you'd like to provide explanation why this behaves the way it does.

**Comment by boukenka** [comment]
Thank you @mkArtakMSFT for the comment. And sorry for the delay.

After some research and the implementation of a DI service to provide an output via the console
(this is easier for the debugging), I was able to find out what was causing the problem in this unlikely scenario.

When the project is restarted, the ```GetAuthenticationStateAsync``` method is called in the ```AuthenticationState``` object. The Identity is then defined and is returned based on the token stored 
in the local storage of the browser. In this scenario, the JSON Web Token has already expired (the token lifetime value is only 30 seconds). This is why it is no longer possible to retrieve the data during the API call and a 302 response is returned.

I am closing this issue.
