### ISSUE TITLE
Scaffold Identity UI using different footer for the layout

### ISSUE THREAD

**Issue by xshiiiidev** [dotnet/aspnetcore#18292]
I just want to make this short.

I scaffold all the identity ui to customize it, I was able to customize each page. However, while customizing the identity ui for each page, I suddenly realize that the identity ui footer _(one the part of Identity/Account/Manage)_ is different from my original customize footer. The footer that the identity ui is using is the initial footer creation of the project.

Version: ASP.NET Core 3.1

Edit:

Actually it is using a whole different Layout.

May navigation menus are missing also.

**Comment by blowdart** [comment]
@anurse Can you move this to the scaffolding repo please?

**Comment by anurse** [comment]
This issue was moved to aspnet/Scaffolding#1232
