### ISSUE TITLE
Adding Microsoft.CodeAnalysis.BannedApi as suggested for SignalR MessagePackHubProtocol

### ISSUE THREAD

**Issue by tebeco** [dotnet/aspnetcore#18290]
### Is your feature request related to a problem? Please describe.
I was trying to do update `MessagePack` to `2.0.x` but as few things changed like the introduction of `MessagePackSerializerOptions`.
As i forgot to properly instantiate it @AArnott [suggested here to use `Microsoft.CodeAnalysis.BannedApi`](https://github.com/dotnet/aspnetcore/pull/18133#discussion_r363308261) :
> Use the Microsoft.CodeAnalysis.BannedApiAnalyzers package and add a banned api file to ban all APIs that do not include the options in order to stay on the safe side.
neuecc/MessagePack-CSharp#534 tracks making this easier.

### Describe the solution you'd like
Trying to check if such analyzer makes sense and could be used here

### Additional context
As i'm submitting this issue, i began to read :
https://github.com/neuecc/MessagePack-CSharp/issues/534
https://github.com/neuecc/MessagePack-CSharp/pull/533
https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Microsoft.CodeAnalysis.BannedApiAnalyzers.md
https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md
https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#id-string-format

But i'm not sure how to setup properly this analyzer to be honest.
Especially since the `Banned Methods` for `MessagePack` are one with either/both `ref` and `optional parametters` so i'm not sure it's going to kicks in properly

**Comment by anurse** [comment]
Given https://github.com/neuecc/MessagePack-CSharp/pull/769, is this just a matter of installing and enabling the new analyzers now? @AArnott are the analyzers available to use?

**Comment by tebeco** [comment]
that was related :https://github.com/dotnet/aspnetcore/pull/18291
https://github.com/dotnet/aspnetcore/pull/18291#issuecomment-574589606

**Comment by anurse** [comment]
I think the idea is that the MessagePack-CSharp project will produce their own set of analyzers. So ideally we would just add a reference to the analyzers they are producing and enable them. But that's why I want to check in with @AArnott.

**Comment by AArnott** [comment]
Yes, 2.1.80 of the [MessagePackAnalyzer](https://www.nuget.org/packages/messagepackanalyzer) package supports this. Make sure [MsgPack001 and MsgPack002](https://github.com/neuecc/MessagePack-CSharp/blob/master/doc/analyzers/index.md) are enabled. The rest can be disabled if you want as they're irrelevant.

**Comment by anurse** [comment]
Cool, so we just need to add a reference and enable the analyzers. Thanks!

**Comment by tebeco** [comment]
@AArnott 
Is the `MessagePackAnalyzer` will always have the same version of `MessagePack` ?
I mean, Are they produced in the same build pipeline, and use the exact same logic to extract the version, and does the build always runs for both ?

I'm trying to understand if i should re-use the `$(MessagePackPackageVersion)` or create a new one

**Comment by AArnott** [comment]
Yes, I would reuse the same msbuild property for both versions.

**Comment by tebeco** [comment]
Should this be closed + milestone associated ?
(Not sure i should close it if there's a merge associated TBH)

**Comment by AArnott** [comment]
Closing makes sense to me.

**Comment by tebeco** [comment]
i wonder if i close it the current milestone will be changed ^^ 

(cc @anurse )

**Comment by BrennanConroy** [comment]
Thanks @tebeco 😄
