### ISSUE TITLE
Interop and object properties, initial letter casing, bug or by design?

### ISSUE THREAD

**Issue by LilMinmax** [dotnet/aspnetcore#18298]
I have this in Javascript:

```
            fttvPlayer.interopTest = function (m) {
                const instance = fttvPlayer.dotnetInstance;
                var issues = instance.invokeMethod('GetIssues');
                console.log("In JS, now have ", issues);
                var sendBack = [{ Property1: "I am Property1", Property2: 100 }, { property1: "I am property, a lowercase property", property2: 99 }];
                console.log("in js, about to send back", sendBack);
                instance.invokeMethod("ReceiveIssues", sendBack);
            };
```

And these are the C# Methods:

```
    [JSInvokable]
    public object[] GetIssues()
    {
        var x = issues.Select(r =&gt; new { r.IssueId, DisplayStart = r.DisplayStart.TotalSeconds, DisplayEnd = r.DisplayEnd.TotalSeconds, r.Answer }).ToArray();
        Console.WriteLine("Sending from C# to JS");
        Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(x));
        return x;
    }

    [JSInvokable]
    public void ReceiveIssues(object[] x)
    {
        Console.WriteLine("Got back in C# from JS");
        Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(x));

    }
```

Here is the console output:

```
WASM: Sending from C# to JS
WASM: [{"IssueId":10425,"DisplayStart":2,"DisplayEnd":6,"Answer":true},{"IssueId":10426,"DisplayStart":7,"DisplayEnd":12,"Answer":false},{"IssueId":10427,"DisplayStart":15,"DisplayEnd":23,"Answer":false},{"IssueId":10428,"DisplayStart":25,"DisplayEnd":29,"Answer":true},{"IssueId":10429,"DisplayStart":31,"DisplayEnd":36,"Answer":false}] 

In JS, now have 
0: {issueId: 10425, displayStart: 2, displayEnd: 6, answer: true}
1: {issueId: 10426, displayStart: 7, displayEnd: 12, answer: false}
2: {issueId: 10427, displayStart: 15, displayEnd: 23, answer: false}
3: {issueId: 10428, displayStart: 25, displayEnd: 29, answer: true}
4: {issueId: 10429, displayStart: 31, displayEnd: 36, answer: false}
length: 5
__proto__: Array(0)

in js, about to send back
0: {Property1: "I am Property1", Property2: 100}
1: {property1: "I am property, a lowercase property", property2: 99}
length: 2
__proto__: Array(0)

Got back in C# from JS
WASM: [{"Property1":"I am Property1","Property2":100},{"property1":"I am property, a lowercase property","property2":99}]
```

I'm curious why the property names from C# to JS change from the initial capping in C# to lowercase first letter in JS, but when I send an object back with lowercase properties, those are not uppercased. (If I send the same data back and forth, it stays lowercase in C# on the return, so it's not round-trippable, I set up an example that shows the initial caps are preserved when going from JS to C#.

I'm wondering why this happens, and if this is maybe a bug. If not, what's the technical reason for it? It took me a while to figure out why my JS logic wasn't working, because it was looking up values by property name and the names didn't match.

**Comment by javiercn** [comment]
@LilMinmax thanks for contacting us.

The objects are being deserialized as JsonElement instances under the hood, so the behavior you see is by design. JsonElement is a C# representation of the json payload you sent and that has mixed casing.

**Comment by LilMinmax** [comment]
One last question @javiercn - I'd expect that by default I could round trip data, and there's nothing about JSON that requires the initial character to be lowercase. i.e. this is perfectly valid JSON:

```
{
	"UpperCase": 100,
	"lowerCase": 200
}
```

When I go from JS to C# everything is as expected. When I go from C# to JS the initial cap situation comes up. Why is that by design vs being able to round trip data?

**Comment by LilMinmax** [comment]
Also, in the JsonElement etc documentation, I see this:

"By default, property names and dictionary keys are unchanged in the JSON output, including case."

This serialization might be using JsonNamingPolicy.CamelCase which seems incorrect.
