### ISSUE TITLE
Blazor: Build failure on Linux due to wrong dotnet location, Error code MSB6003

### ISSUE THREAD

**Issue by curtisy1** [dotnet/aspnetcore#18308]
### Describe the bug
[DotNetToolTask.ExecuteTool](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/DotnetToolTask.cs#L91) gets passed a wrong path on Linux in some circumstances, resulting in a failed build since the dotnet binary cannot be located. For me the path it spits out looks like a fallback path (```/usr/bin/dotnet```)
I'm still not sure as to why this happens but I hope it's at least reproducable with the example below.

### To Reproduce
Not really minimalistic but I haven't yet figured out how to narrow it down any further. Steps to reproduce are as follows:
- Clone the [Blazor boilerplate](https://github.com/enkodellc/blazorboilerplate)
- ```cd``` into ```src/BlazorBoilerplate.CommonUI/```
- run a simple ```dotnet build```

Got Exceptions? Include both the message and the stack trace
[LOGLEVEL_DIAG.log](https://github.com/dotnet/aspnetcore/files/4051710/LOGLEVEL_DIAG.log)
[LOGLEVEL_NORMAL.log](https://github.com/dotnet/aspnetcore/files/4051711/LOGLEVEL_NORMAL.log)

### Further technical details
- ASP.NET Core version
Not sure? But I think it should be 3.1.0?

- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     solus
 OS Version:  4.0
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/curtisy/.dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [/home/curtisy/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/home/curtisy/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/home/curtisy/.dotnet/shared/Microsoft.NETCore.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
None, I'm invoking a ```dotnet build``` command from a bash shell

- I'm using the dotnet binaries from the [Install Script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)

**Comment by javiercn** [comment]
@curtisy1 thanks for contacting us.

@pranavkm do you have any thoughts on this?

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/14432 that's shows up in .NET Core as a result of https://github.com/dotnet/aspnetcore/issues/17308. The second issue is slated for the upcoming 3.1 patch release, so that should help. Closing since we're separately tracking fix this
