### ISSUE TITLE
Custom Model Binding

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/aspnetcore#18304]
Hi
I am struggling with Model Binding. There is a lot of stuff out on the internet that seems to relate to other frameworks or older versions of MS frameworks and I cannot find a simple documented example of what I am trying to do beyond this: https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1

It talks of the ModelBinder and the BindProperty attributes, TypeConverters IModelBinderProviders etc. 

There is also mention of DefaultModelBinder which is old MVC but I can't see how to extend the MVC Core 3.1 functionality so that I only use my code for one property of my POCO object and rely on the out of the box functionality for all other fields.

Please can we have some simple and complete examples. I  have the following use cases:

- I have a simple POCO object with a property say x that is the class name for a child object. I want to return an object of type X not the string with the name of the class I am to instantiate.
- I want to apply a timezone conversion to all date fields.

If I have to do it my Model Object level - how can I fall back to out of the box functionality?

Thanks
Mark

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MCFHTAGENTS.
@pranavkm can you please look into this? Let's also get the docs updated to include a sample covering this scenario.

**Comment by pranavkm** [comment]
@MCFHTAGENTS you should be able to specify a custom model binder using `ModelBinderAttribute` as documented here: https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#custom-model-binder-sample. This includes code snippets on configuring model binders globally which may help for your timezone conversion scenario.

> I have a simple POCO object with a property say x that is the class name for a child object. I want to return an object of type X not the string with the name of the class I am to instantiate.

This sounds like a very specific scenario. I'd recommend using StackOverflow with the `asp.net-core` tag to get an answer here.

**Comment by MCFHTAGENTS** [comment]
Thank you for this - that looks a great set of additions to the docs. I can see how the polymorphic example addresses much of my scenario.

Would be great to see examples for:
> The framework determines the difference based on the existence of a TypeConverter. We recommended you create a type converter if you have a simple string -> SomeType mapping that doesn't require external resources.

and

> You can apply the ModelBinder attribute to individual model properties (such as on a viewmodel)

as I couldn't get these to work by 'just applying the attribute', even if I created a binderprovider at the head of the queue...

Thanks
Mark
