### ISSUE TITLE
Add support for `int` for the `<InputSelect>` component

### ISSUE THREAD

**Issue by giorgi-abashidze** [dotnet/aspnetcore#18305]
.NET Standard 2.1 webassembly app, i have problem validating int field, in more details i have list of items in inputselect and their Ids into `<option value="@item.Id"> `

i have [Required] Data anotation in this field in model class but still not care, onvalidsubmit method is calling even if `<optionvalue="">`  is selected,

i tried to add another data anotation to the field greater than zero  `[Range(0, Int32.MaxValue, ErrorMessage = "Parent id is Required")]`

and replaced  default select option -> `<option value="" selected>`  with `<option value="0" selected>`

still not works.

**update:**

validation is working fine. problem is binding. @bind-Value not changing the fields value, I added default value 0 to the field  and it showing error now, but when select other item, field value not updating and showing the same error.

**Comment by javiercn** [comment]
@giorgi-abashidze thanks for contacting us.

In order for us to be able to investigate this issue. Could you provide a minimal repro project that shows the problem and detailed steps on how to reproduce it?

**Comment by giorgi-abashidze** [comment]
@javiercn here is the demo project 

https://github.com/giorgi-abashidze/InputSelect-Test-For-int

created new test project and now i'm getting error in console: inputselect not suporting type Int32.
in old project there was no errors in console maybe because i had form in modal.

**Comment by RogerMKE** [comment]
Just to be clear, to handle real world scenarios, the InputSelect needs to handle both int and Guid, as well as the nullable versions of each.  Not just 'int'.

Options values sourced from a database are almost always going to have int or Guid keys.  The input model being bound to may or may not require the user to make a choice from the list, so the nullable variants are appropriate for that situation.

In its current state, InputSelect out of the box is unusable in many real world scenarios, where int and Guid dominate.

**Comment by mrlife** [comment]
Supporting `int` is a basic need for this type of component. This workaround in the meantime was provided by @SteveSandersonMS.

https://github.com/dotnet/aspnetcore/issues/11181#issuecomment-506288035

**Comment by MackinnonBuck** [comment]
Closing as this was fixed as part of #23415.

**Comment by mrlife** [comment]
@MackinnonBuck Is this a 5.0 only release?
