### ISSUE TITLE
Improvement Request: DevEnv compile speed drastically reduced based on codebase size

### ISSUE THREAD

**Issue by strich** [dotnet/aspnetcore#18302]
### Describe the bug
I have recently been playing around with Blazor and whilst I'm loving it, one key drawback I'm having is that the compile speed is quite bad when the codebase is medium-sized.

A common devenv work loop is making minor modifications to HTML within .razor files, and in doing so requires a recompile of the Client project. Below I provide 2 typical compile times for the following environments:

**Default Client Project:**
The Client Project in the template `Blazor WebAssembly App hosted on .NET Core` solution.

**Client Project with Syncfusion.EJ2.Blazor:**
The Client Project in the template `Blazor WebAssembly App hosted on .NET Core` solution, with the `Syncfusion.EJ2.Blazor` NuGet package. This package weighs in at about 12MB compiled. 

```
Default Client Project:
    Time Elapsed 00:00:03.48
Client Project with Syncfusion.EJ2.Blazor:
    Time Elapsed 00:00:27.28
```

These times were captured by first performing a full debug build and then another debug build after modifying the `Counter.razor` file.

A 30 sec build time seems far larger than I would expect when the Client project itself is so small - Even with large 3rd party libraries it should be pretty quick given that they are precompiled?

### Further technical details
- ASP.NET Core version: v3.1
- Visual Studio 2019

**Comment by strich** [comment]
Thanks to @BirdseyeviewNL we discovered the primary time sink was the IL Linking & Removal step [described here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1).

Disabling linking _drastically_ reduces compile time. I would highly recommend that IL Linking is disabled by default during debug builds. Maybe someone can provide a case where build size is more important than build speed in the devenv, but given the reduction of compile time the value of disabling this from a quality of life PoV seems huge to me.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will pass this feedback to the Mono team, who own the Linker.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18440

**Comment by strich** [comment]
@mkArtakMSFT so whilst I agree perf improvements is a solid path forward I've also run into issues where some methods (Presumably built-in extension methods?) in core C# namespaces don't exist when I build without IL stripping. 

I assume this is because this feature does both stripping AND additional linking? If so, I'd like to request that it be possible to disable IL stripping and IL linking independant of each other.
