### ISSUE TITLE
Blazor (server) checkbox becomes normal input when using checked

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/aspnetcore#18307]
### Describe the bug
While searching for workarounds for #18306, I tried this one:
```razor
@if (cat.IsBlack)
{
    <input @key="@cat.Id" type="checkbox"
        @onchange=@(eventArgs => { cat.IsBlack= (bool)eventArgs.Value; HandleCatColor(cat); })
        checked />
}
else
{
    <input @key="@cat.Id" type="checkbox"
    @onchange=@(eventArgs => { cat.IsBlack= (bool)eventArgs.Value; HandleCatColor(cat); }) />
}
```

Now if the cat is black, the checkbox is initially checked. If you click it, it becomes unchecked. If you then click it again, the input field loses its `type="checkbox"` field and is no longer a checkbox!

### To Reproduce
Use checkboxes with explicit `checked` fields

### Further technical details
```
PS C:\Users\Benni\repositories\ChallengePad> dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.100
 Commit:    cd82f021f4

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS 2019 16.4.2

**Comment by javiercn** [comment]
@Trolldemorted thanks for contacting us.

I believe your issue is that you are using the same ID for two input elements and that can produce undefined behavior. @SteveSandersonMS can confirm this.

**Comment by Trolldemorted** [comment]
So it does not matter that the two elements never exist in the tree at the same time?

Is there documentation explaining that? This is not what I had expected.

**Comment by SteveSandersonMS** [comment]
`@key` values don't have to be unique globally, but they do have to be unique among siblings of a given parent. Unfortunately the code you've posted does attempt to use the same `@key` value for two different elements within the same parent. The fact that they aren't visible "at the same time" doesn't save you, since the issue occurs while the diffing system is computing the update from one state to the next, during which both are in play.

As per [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#use-key-to-control-the-preservation-of-elements-and-components),

> Ensure that values used for @key don't clash. If clashing values are detected within the same parent element, Blazor throws an exception

Unfortunately this suggests there is a framework bug in the `if/else` case that you've posted. Ideally we should have a clear exception here instead of the broken behavior you've observed. I've filed a bug to track this: https://github.com/dotnet/aspnetcore/issues/18314

**Comment by Trolldemorted** [comment]
Thanks for clearing this up! I assumed "parent element" meant "parent element in the rendered DOM-tree", not blazor's representation of it. You might want to be overly specific in the docs to prevent this misunderstanding, but a thrown exception would be great too.
