### ISSUE TITLE
Access IHost across application classes globally

### ISSUE THREAD

**Issue by satyajit-behera** [dotnet/aspnetcore#18309]
Below is an example code for CreateHostBuilder. Asp.net core host takes care of resolving dependency through constructor and middleware.

If we want to resolve it for our custom classes which does not get invoked through controller or the main method, how can we get the instance of the host across applications. Is it a good way to store it as a static variable Or there is some better way to do that?

```
public class Program
{
    public static async Task Main(string[] args)
    {
        var host = CreateHostBuilder(args).Build();

        using (var serviceScope = host.Services.CreateScope())
        {
            var services = serviceScope.ServiceProvider;

            try
            {
                var serviceContext = services.GetRequiredService<MyScopedService>();
                // Use the context here
            }
            catch (Exception ex)
            {
                var logger = services.GetRequiredService<ILogger<Program>>();
                logger.LogError(ex, "An error occurred.");
            }
        }

        await host.RunAsync();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
}
```

I need to call var serviceContext = services.GetRequiredService<MyScopedService>();
at various places in my code which does not get called from the controller. 
This is required for my Console applications and Worker Services.

Is it possible to access the IHost globally and the same instance that got created in startup without keeping that in a static variable in a static class?

**Comment by davidfowl** [comment]
> Is it possible to access the IHost globally and the same instance that got created in startup without keeping that in a static variable in a static class?

No. You need to store it in a static if you want to access it later. There can be many hosts running side by side in the same process and we generally avoid statics like that. You can however create your own.

What does your logic look like?

**Comment by satyajit-behera** [comment]
In the startup, I am storing the serviceProvider in a static variable.
<code>
public static IServiceProvider ServiceProvider 
        {
            get 
            {
                if (_ServiceProvider == null) throw new NullReferenceException("ServiceProvider cannot be null");

                return _ServiceProvider;
            }
            set 
            { 
                _ServiceProvider = value; 
            } 
        }
</code>

And whereever required, I am calling this method and other serviceProvider methods.
<code>
ServiceProvider.GetService<TService>();
</code>

Is this approach correct, or there is some better approach?

Thanks for the quick response.
