### ISSUE TITLE
Templated generic blazor component does not accept template context RenderFragment<T> for different type T

### ISSUE THREAD

**Issue by awajan** [dotnet/aspnetcore#18310]
When you try to compose and consume a generic (typed) blazor component and expose a RanderFragment<T> parameter, T is being restricted to be the same generic type of the component. Otherwise, the consuming component would show the below error when placing the template markup.

Example: `<Component1>` is a typed component with type T1, exposing a parameter named Header for example, that is `RenderFragmanet<T2>`

Now, in Component2 if you try to consume Component1 as below:
```
<Component1>
  <Header></Header>
</Component1>
```
The below error would show:

The type or namespace 'T2' does not exist in the namespace '__Blazor....'.

Thanks

**Comment by javiercn** [comment]
@awajan thanks for contacting us.

I've updated your post for clarity. I believe that if you want to have a different RenderFragment<T2> you would need to declare your templated component to have more than one type parameter (like `<T1,T2>`, which I'm not 100% sure is possible, but I believe so).

That should allow you to expose `RenderFragment<T>` with a different type.

Di we understood everything correctly?

**Comment by awajan** [comment]
I think you got me correctly, but there is no where mentioned in the documentation that RenderFragment<T> should have T matching the typed component parameter. In addition to that, I was able to specify RenderFragment<T> where T can be any type for components that are not typed (non-generic).

**Comment by javiercn** [comment]
> In addition to that, I was able to specify RenderFragment where T can be any type for components that are not typed

I'm assuming that you mean you were able to declare something like `RenderFragment<Animal>` that's totally valid and expected, Razor components are compiled to C# classes so the same rules apply to them. 

You can't declare a non generic class with a generic property in it and in the same way you can't have a RenderFragment<T> property where T is not a parameter defined with typeparam

**Comment by awajan** [comment]
this is not completely true:

"You can't declare a non generic class with a generic property in it and in the same way you can't have a RenderFragment property where T is not a parameter defined with typeparam"

I used RenderFragment<T> on non generic components, and this was completely fine. The issue remains as stated initially and it is a bug.

**Comment by javiercn** [comment]
@awajan could you provide a minimal repro project that illustrates the issue?
