### ISSUE TITLE
CORS issue when authenticating asp.net core web app

### ISSUE THREAD

**Issue by nehaagrawal** [dotnet/aspnetcore#18319]
I am following this document(https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp) for adding authentication in my asp.net web app and I am getting CORS issue. The document doesn't say anything about CORS setting so I am wondering what am I missing? Below error is from edge but same can be reproduced in chrome. I work at Microsoft so please let me know if you need more details in email.

SEC7120: [CORS] The origin 'https://blahblah:9001' did not find 'blahblah:9001' in the Access-Control-Allow-Origin response header for cross-origin resource at 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize?client_id=2445b019-b035-4493-9f5e-dc71cdd00ca5&redirect_uri=https%3A%2F%2Fattestation-int.dps.mp.microsoft.com%3A9001%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=637145345763734224.ZWJlYjM1MDAtMGYyNi00OTk5LWE4MTMtOWI1ZTVhYzhlNzUyNzlhOGQwNjMtMmU0ZS00MzljLThkOWMtYzdmMDJhZjZkOWI2&state=CfDJ8K_0dkmtbvdKk3yIe6PLUU1tU-XjcqYnpcjlQaxY3oylqw7K93N6EDIGE7YNnrOg0R-ztxrPOgAgMDB4avmzxMpPDa2MlIGwboJm37XW2e5HTh4XmqL5e-Pz0pdZro81NRBp-nyKJkRihup6Fuf--ZB-26yXnuK5k1QVe9FMQNAOZNdNOqkem1O3gJBheDKcqLt4zH1IGzGKLs2sgMsXra06tDhhi7W9qqqc7AmBrxf1zvoDgO8xXADU_d_9pRcfkO4E98GXLk5UcwKhR-KUBjyrehIMKFAzWL9ef4GULO0IFq-BilhGfT5kUx9lqFXv58pS38J0qilTRXl-Q9YtBKRsKBmDoAZwi02SX58n-f-yV2n3MzP1KhR2bgVibzBaf0-T4EjzTm50TlHc2gO1M24HmnAMvLSqKywQoQsIjGa_MMHh2UKfrC0Bo7QMKazIWWzt1-Ma3wQV6vDD351HjUs&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0'.

**Comment by blowdart** [comment]
That's an AD article, the question would be best asked in [their repo](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Closing this issue per @blowdart 's response.
