### ISSUE TITLE
Blazor - Singleton service shares between instances in Server hosting model

### ISSUE THREAD

**Issue by carlosld** [dotnet/aspnetcore#18313]
In .net core 3.1 a Singleton service instance is shared with all instances of a Server side Blazor App. In the default template of Blazor Server side App I create `State` class like this.

```c#
public class State
{
    public int Counter { get; set; }
}
```

Then I configure the service in `ConfigureService`

```c#
public void ConfigureServices(IServiceCollection services)
{
    // .... 
    services.AddSingleton<State>();
}
```

And finally I change the Counter component like this

```html
@page "/counter"

@inject State State

<h1>Counter</h1>

<p>Current count: @State.Counter</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {

    private void IncrementCount()
    {
        State.Counter++;
    }
}
```
When you connect with different browser the counter is shared, witch I think is a bug.

**Comment by pranavkm** [comment]
Hi @carlosld, you'll need a scoped service - https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#add-services-to-an-app. Singleton services are singleton across the lifetime of the app \ across multiple connections (just as they are with controllers).
