### ISSUE TITLE
Duplicate @key values don't throw clear exception in if/else case

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#18314]
As reported here: https://github.com/dotnet/aspnetcore/issues/18307#issue-548638163

With this code,

```razor
@if (cat.IsBlack)
{
    <input @key="@cat.Id" type="checkbox"
        @onchange=@(eventArgs => { cat.IsBlack= (bool)eventArgs.Value; HandleCatColor(cat); })
        checked />
}
else
{
    <input @key="@cat.Id" type="checkbox"
    @onchange=@(eventArgs => { cat.IsBlack= (bool)eventArgs.Value; HandleCatColor(cat); }) />
}
```

This should throw a clear exception about reuse of the same `@key` value with a different sequence ID when toggling `cat.IsBlack` as per docs:

> Ensure that values used for @key don't clash. If clashing values are detected within the same parent element, Blazor throws an exception

However because of the `if/else`, it doesn't throw but instead exhibits broken behavior.

This isn't super high priority because it's not a valid code pattern anyway. The issue is just that the error detection doesn't catch this particular case.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
