### ISSUE TITLE
Identity.UI produce assemblies that are built with implementation assemblies instead of reference assemblies.

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#18323]
We discovered in 3.1.1 that Identity.UI assemblies. Specifically V3.dll and V4.dll. Combined with the bug described in https://github.com/dotnet/aspnetcore/pull/17970, runtime errors due to not being able to load the correct assemblies will be produced. Though we are fixing the related issue, we should ensure that the Identity.UI assemblies are built correctly.

The reason why Identity.UI specifically does not build correctly is because the customized logic at https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Identity/UI/src/Microsoft.AspNetCore.Identity.UI.csproj#L59-L65 where MSBuild is launched to directly invoke the BuildForUI target. This bypasses the logic that we need to trigger at https://github.com/dotnet/aspnetcore/blob/release/3.1/eng/targets/ResolveReferences.targets#L249-L276.

My recommendation would be to try separating out the project into two new project for each of the V3 and V4 content and building them separately in the same way we build the other UI packages. Then compose the final Identity.UI package with the dll produced in the V3 and V4 projects.

cc @pranavkm @mkArtakMSFT to triage.

**Comment by JunTaoLuo** [comment]
Here's the doc for the known issue in 3.1 https://github.com/aspnet/specs/pull/406/files

**Comment by Pilchie** [comment]
@mkArtakMSFT - we think this issue will block 3.1.2, and we need to work on a fix for it ASAP.  Can you help us find someone who understands the build logic there to investigate ASAP?

**Comment by pranavkm** [comment]
Picking this up

**Comment by Pilchie** [comment]
Thanks @pranavkm !

**Comment by JunTaoLuo** [comment]
The PR is merged so I'm closing. @pranavkm reopen if you need it to track something else.

**Comment by pranavkm** [comment]
Verified that this works in 3.1.2 build 014865
