### ISSUE TITLE
Revert constant reference from "Identity.Application" to IdentityConstants.ApplicationScheme

### ISSUE THREAD

**Issue by vladdy-moses** [dotnet/aspnetcore#18329]
https://github.com/dotnet/aspnetcore/blob/6dd3d6ec49d7e61a71cc825dcbdc9533d2620d7d/src/Identity/Extensions.Core/src/UserClaimsPrincipalFactory.cs#L79

3 years ago (according to git blame) in that line of code constant `IdentityConstants.ApplicationScheme` was replaced to `"Identity.Application"`.

### Is your feature request related to a problem? Please describe.

I am trying to describe authorization policies in asp.net core 3.1 app and I need to define `policy.AddAuthenticationSchemes` requirement.

For example:
`policy.AddAuthenticationSchemes(IdentityConstants.ApplicationScheme, IdentityServer4.IdentityServerConstants.LocalApi.AuthenticationScheme)`

But I can't guarantee IdentityConstants.ApplicationScheme and "Identity.Application" will be same in next aspnetcore versions.

### Describe the solution you'd like

Revert that change.

**Comment by HaoK** [comment]
Moving forward as this is pretty straight forward to fix

**Comment by HaoK** [comment]
Turns out we couldn't use the constant because of the layering, the constant is defined in the AspNetCore package, while this class lives in the Core (non aspnet specific) package.  We don't think this is important enough to fix since its a constant that will not change
