### ISSUE TITLE
Blazor local debugging issues

### ISSUE THREAD

**Issue by andyfurniss4** [dotnet/aspnetcore#18328]
# Describe the bug
I've added Blazor to an existing MVC project by essentially following this article: https://mikaelkoskinen.net/post/combining-razor-blazor-pages-single-asp-net-core-3-application

Firstly, if I run the project using the debugger in Visual Studio, any changes I make to my Blazor components are not reflected in the browser, even after a refresh. I have to restart the whole project after every change which is a bit ridiculous. If I run the project without the debugger then I am able to see my changes in the browser, but only after a page refresh. Before refreshing, I can see this error in Chrome console window:

```
[2020-01-14T09:42:05.231Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'.
e.log @ blazor.server.js:1
e.stopConnection @ blazor.server.js:1
transport.onclose @ blazor.server.js:1
e.close @ blazor.server.js:1
i.onclose @ blazor.server.js:1
```

which suggests it's trying to live/hot reload but failing for some reason.

### Questions:

1. Can I not run the project with the debugger if I want to see my component changes in the browser?
2. Is there a fix for the web socket connection issue shown above?

### To Reproduce
Add Blazor support to existing MVC project using guide in article linked above, run the project using Visual Studio 2019 16.4.

### Further technical details
- ASP.NET Core 3.1
- Visual Studio 2019 16.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We plan to address this as part of https://github.com/dotnet/aspnetcore/issues/5456.
For now, for faster development loop, we recommend running without debugger attached.
