### ISSUE TITLE
 User.FindFirstValue(ClaimTypes.Email) returns always null.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#18348]
I am trying to get the logged in user's email from the claim using `User.FindFirstValue(ClaimTypes.Email)` but it always returning `null`. Look at the followings:

     string email = User.FindFirstValue(ClaimTypes.Email); // Always null. Not returning logged in user's Email
     string userName = User.FindFirstValue(ClaimTypes.Name); // Returning logged in user's UserName
     string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // // Returning logged in user's Id

Why `User.FindFirstValue(ClaimTypes.Email)` returning null instead of logged in user's email?

**Note: `User.FindFirst(ClaimTypes.Email)` also returning `null` while `User.FindFirst(ClaimTypes.Name)` and `User.FindFirst(ClaimTypes.NameIdentifier)`; returning expected values.**

**Comment by javiercn** [comment]
@TanvirArjel thanks for contacting us.

@HaoK I believe you wrote this helper in the first place?

**Comment by blowdart** [comment]
Is this user coming from aspnet core identity?

**Comment by TanvirArjel** [comment]
@blowdart Yes! This user is coming from the ASP.NET Core Identity database, Not from external login.

**Comment by anurse** [comment]
@TanvirArjel Can you dump out the claims for the user (using `User.Claims`)? It's possible this isn't the correct user principal.

**Comment by TanvirArjel** [comment]
@anurse, using `User.Claims`, I am getting 4 claims whose types are as follows:

    http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier // value is primary key
    http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name // value is user name
    AspNet.Identity.SecurityStamp 
    amr

**Comment by HaoK** [comment]
Doesn't look like we generate an email claim by default, since generally the user name is the email for us.

See https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/UserClaimsPrincipalFactory.cs#L82 for the list of claims we generate by default.

We could consider also generating the email claim if the user has a non null email as well, thoughts @blowdart ?

**Comment by blowdart** [comment]
We should yes.

**Comment by anurse** [comment]
@blowdart This will be lost in the 5.0.0 milestone. Moving to backlog with `5.0-candidate` for actual planning.

**Comment by Kahbazi** [comment]
Is this up for grab?

**Comment by HaoK** [comment]
Sure @Kahbazi this seems like a good one for up for grabs

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/18580  Thanks again @Kahbazi
