### ISSUE TITLE
Microsoft.AspNetCore.DataProtection 3.1.1 stated dependencies missing on Nuget.org

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/aspnetcore#18341]
Microsoft.AspNetCore.DataProtection 3.1.1 lists the following dependencies that are not available on Nuget.org:

- Microsoft.Extensions.DependencyInjection.Abstractions (>= 3.1.1)
- Microsoft.Extensions.Hosting.Abstractions (>= 3.1.1)
- Microsoft.Extensions.Logging.Abstractions (>= 3.1.1)
- Microsoft.Extensions.Options (>= 3.1.1)

Updating a project to Microsoft.AspNetCore.DataProtection 3.1.1 therefore fails with errors similar to:

	NU1102: Unable to find package Microsoft.Extensions.Hosting.Abstractions with version (>= 3.1.1)
	  - Found 32 version(s) in nuget.org [ Nearest version: 3.1.0 ]
	NU1102: Unable to find package Microsoft.Extensions.DependencyInjection.Abstractions with version (>= 3.1.1)
	  - Found 36 version(s) in nuget.org [ Nearest version: 3.1.0 ]
	NU1102: Unable to find package Microsoft.Extensions.Options with version (>= 3.1.1)
	  - Found 39 version(s) in nuget.org [ Nearest version: 3.1.0 ]
	NU1102: Unable to find package Microsoft.Extensions.Logging.Abstractions with version (>= 3.1.1)
	  - Found 39 version(s) in nuget.org [ Nearest version: 3.1.0 ]
	Package restore failed. Rolling back package changes for 'WebApplication1'.

**Comment by Pilchie** [comment]
Tagging @anurse, but I suspect this is just lag while NuGet indexes the new versions.

**Comment by martincostello** [comment]
I'm seeing the same thing via `Microsoft.AspNetCore.AzureAppServices.HostingStartup` for the 3.1.1 versions of `Microsoft.Extensions.Logging.AzureAppServices` and `Microsoft.Extensions.Configuration.EnvironmentVariables`.

**Comment by achandlerwhite** [comment]
I'm able to find the 3.1.1 package but I get a runtime error: `Could not load file or assembly 'Microsoft.AspNetCore.DataProtection.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)`

0) update SDK to 3.1.101 
1) start a new project with `dotnet new mvc`
2) `dotnet add package Microsoft.AspNetCore.Authentication.OpenIdConnect`
3) In `ConfigureServices`:
```cs
services.AddAuthentication.AddOpenIdConnect();
```
4) `dotnet run` Then I get the error below:

System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler': Could not load file or assembly 'Microsoft.AspNetCore.DataProtection.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
 ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.DataProtection.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.AspNetCore.DataProtection.Abstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by Pilchie** [comment]
See https://github.com/aspnet/announcements/issues/401.  You probably need to add an explicit package reference.

**Comment by achandlerwhite** [comment]
@Pilchie That did the trick. Thanks for pointing me in the right direction.

**Comment by frankbuckley** [comment]
All available now - thanks
