### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Testing missing nuget dependency

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/aspnetcore#18344]
https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing/ V3.1.1 relies on https://www.nuget.org/packages/Microsoft.Extensions.Hosting/ V3.1.1 which doesnt exist

So a nuget update fails

**Comment by javiercn** [comment]
@SimonCropp thanks for contacting us.

@dotnet/aspnet-build This seems like an infrastructure issue, can you take a look? It might be we've published a broken package as part of the patch?

**Comment by SimonCropp** [comment]
@javiercn seems to now exist. so will close this

**Comment by SimonCropp** [comment]
on a side, i am surprised this was not picked up earlier. i would have assume that at least one smoke test of a sample consuming the real nugets would have been done as part of each deployment? 

and please take this as constructive criticism. I think the asp net team is overall doing a great job.

**Comment by javiercn** [comment]
@SimonCropp It is likely that you picked up the update while the packages were being uploaded. It's not atomic, but its done in a few minutes, so it's extremely rare someone runs into this issue.

**Comment by SimonCropp** [comment]
looking at the timestamps, it was broken for 5 hours

**Comment by javiercn** [comment]
@SimonCropp There might have been a glitch in the infrastructure. We do our best, but these things happen from time to time.

It is likely that we caught it and we reacted against it, but these things take time.

**Comment by Pilchie** [comment]
We had a  publishing problem with `extensions` packages yesterday due to the repo move and manually recovered.

Also, though upload is pretty quick, NuGet doesn't make packages available until they have done a fair bit of ingestion validation that can take a  while when we upload a few thousand packages for a servicing event.

**Comment by SimonCropp** [comment]
should NuGet even allow a package to be uploaded when there is a missing dependency?
