### ISSUE TITLE
Template id reference in blazor

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#18349]
### Is your feature request related to a problem? Please describe.

I am porting the ng-zorro to [ant-design-blazor](https://github.com/ElderJames/ant-design-blazor), and have many troubles about template reference.
At current version, if we need to create a template reference, we must assign the `@<{HTML tag}>...</{HTML tag}>` to the `RenderFragment ` variable.

```
@timeTemplate

@petTemplate(new Pet { Name = "Rex" })

@code {
    private RenderFragment timeTemplate = @<p>The time is @DateTime.Now.</p>;
    private RenderFragment<Pet> petTemplate = 
        (pet) => @<p>Your pet's name is @pet.Name.</p>;

    private class Pet
    {
        public string Name { get; set; }
    }
}
```

### Describe the solution you'd like

Can you implement template references like angular:

```
<Template Id="petTemplate" Context="pet">
     <p>Your pet's name is @pet.Name.</p>
</Template>
```

or event like:

```
<p TemplateId="petTemplate" Context="pet">Your pet's name is @pet.Name.</p>
```

And then, render in razor or pass to another component as a parameter. like:

```
@petTemplate(new Pet { Name = "Rex" })
```
or:
```
<OtherComponent PetTemplate="petTemplate"></OtherComponent >
```

I think [bolero](https://github.com/fsbolero/bolero) do a great job at this.

![image](https://user-images.githubusercontent.com/7550366/72410609-bdb25780-37a3-11ea-85e7-ff85659d53d2.png)

![image](https://user-images.githubusercontent.com/7550366/72410692-0407b680-37a4-11ea-8047-0c9964ba69dc.png)

![image](https://user-images.githubusercontent.com/7550366/72410746-28fc2980-37a4-11ea-9e87-9e65f4d55d4a.png)

![image](https://user-images.githubusercontent.com/7550366/72410779-403b1700-37a4-11ea-94a2-29d0ba805992.png)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. The concept of templates from Angular maps to a component in Blazor. This is a good starting point to help you with understanding the concepts better: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1

For general questions like this, to get a faster response we suggest posting them in [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
