### ISSUE TITLE
Update DebuggerProxy sources

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18356]
This includes writing instructions for this, so next time I can handle it

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT I'm holding off on this until we confirm that we're updating to a specific version of Mono, since we should take the corresponding version of the debug proxy sources.

**Comment by mkArtakMSFT** [comment]
Thanks @SteveSandersonMS: https://github.com/dotnet/aspnetcore/pull/18478
