### ISSUE TITLE
LinkGenerator and GetPathByName behaviour changed

### ISSUE THREAD

**Issue by MarcoGix** [dotnet/aspnetcore#18351]
Hi,
we have an issue with LinkGenerator when we use GetPathByName.

_linkGenerator.GetPathByName(this.HttpContext, "V1.GetOperationById", new { operationId = "something" });

In the Prediction controller, we have the following attribute:
[HttpGet("{operationId}", Name = "V1.GetOperationById")]

This is the LOG that comes out:

*Failed to process the template v{api-version:apiVersion}/prediction/{operationId} for TestWithoutArkTools.Controllers.PredictionController.GetOperationById (TestProject). 
A required route value is missing, or has a different value from the required default values. 
Supplied ambient values { "action": "Get", "api-version": "1.0", "controller": "Test" } and { "operationId": "6323b908-49c4-4ae3-b39d-7458cbee6feb" } 
with default values { "action": "GetOperationById", "controller": "Prediction" }*

As you can see, the endpoint is found with the full route. 
The ambient values are all there, correctly printed by the log.
Still the GetPathByName returns null.

We saw in the code that if there is a required paramenter, and api-version is, that is not fetched from ambient values, no idea why.
I may agree that order would be to try supplied values first, and ambient as last, but not using it makes impossible to generate Location headers with global, ambient, route.

We have this problem also for lang route parameter like {lang:lang}/v{api-version:apiVersion}/prediction/{operationId}.

Our current workaround is to:
- extract RouteValue from HttpContext
- create RouteValueDictionary from the route values we want to supply
- add ambient values to the dictionary
- call _linkGenerator.GetPathByName with the dictionary

			var res = "something";

			var ambients = this.HttpContext?.Features.Get<IRouteValuesFeature>()?.RouteValues;

			var rd = new RouteValueDictionary(new { operationId = res })
			{
				{ "api-version", ambients["api-version"] }
			};

			var u_GetPathByNameHttp = _linkGenerator.GetPathByName(this.HttpContext, "V1.GetOperationById", rd);

Could be possible to avoid to use this workaround? 
In ASPNet core 2.2 this was no needed and all working perfectly. From our point a view this is a regression.

Thanks,
Marco Giannotti

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us.
There were multiple breaking changes in this area in 3.0 release. We've documented all these at: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#differences-from-earlier-versions-of-routing

Hope that helps.

**Comment by MarcoGix** [comment]
Well, it really doesn't help much, actually. Sorry.

Even if a breakage is documented, it doesn't make it much useful unless it covers how to act in the new version with old valid scenarios in place, that were supported.

Using route for _lang_ and _version_, even if debatable, is common pattern and the changes does brake it as is impossible to generate sane _Location_ header uri with the new framework in API controllers in a REST application (no pages, razor or blazor involved).

So, the fact that a regression is indeed documented doesn't help us in any way in going forward with update.

Is there a nicer workaround than the one I've suggested above? 
Is there an extension method I'm missing in one of the AspNetCore packages that uses ambient values?
Is there any security risk in using all ambient values (RouteData from HttpContext) in all linkGeneration values?
