### ISSUE TITLE
Restore normal patch versioning to new Azure SDK integration packages when they ship

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#18355]
Filing this here to track updating all the relevant packages.

For the three new Azure SDK integration packages, we set the patch version to `0` in order to be able to ship them at patch version `.0` since they are new packages. We must revert this after the GA of these packages.

I expect we'll keep this untriaged to keep it on our radar.

**Comment by anurse** [comment]
New plan, let's just not reset the versions to `0` in the PRs. @BrennanConroy please do the needful and close this (I don't want to forget to do it :)).

**Comment by BrennanConroy** [comment]
All 3 PRs updated to no longer set the patch version to `0`
