### ISSUE TITLE
Blazor Server App doesn't match in Google Chrome, but in Firefox, works fine

### ISSUE THREAD

**Issue by pedrorja** [dotnet/aspnetcore#18366]
### Describe the bug
I developed an application in Blazor Server and Aspnetcore 3.1, During the develop period, the application run ok, but, when I dockerize and deployed the application in a Linux Suse Server, I tested the app trying to access via Google Chrome, but I recieve this error:

 blazor.server.js:1 [2020-01-15T20:29:08.391Z] Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.

blazor.server.js:1 [2020-01-15T20:29:29.649Z] Warning: Error from HTTP request. 0: .

In Firefox, the error happens, but the application bypass and works well.

### To Reproduce

- Dockerfile

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV CONNECTION_STRING="Server=xxxxxx"
ENV ASPNETCORE_ENVIRONMENT="Production"

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["TecaPlusReport.csproj", ""]
RUN dotnet restore "./TecaPlusReport.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "TecaPlusReport.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TecaPlusReport.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TecaPlusReport.dll"]

### Further technical details
- ASP.NET Core version: 3.1
- VS2019

**Comment by anurse** [comment]
> blazor.server.js:1 [2020-01-15T20:29:29.649Z] Warning: Error from HTTP request. 0: .

@pedrorja is there anything else in the browser console? That message usually means the browser is intentionally not providing the JavaScript code with the *reason* for the error because it could be a security leak, but often it will still write it directly to the console (for the developer to see).

Could you try collecting a network trace? We have [guidance on how to do this in our documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#network-traces).

**Comment by anurse** [comment]
> deployed the application in a Linux Suse Server

Oh, also are you using a front-end proxy like `nginx`? Or is the container directly connected to the public port `80`? Proxies, Kubernetes Ingresses, and other intermediate servers can also interrupt WebSocket connections

**Comment by pedrorja** [comment]
> > deployed the application in a Linux Suse Server
> 
> Oh, also are you using a front-end proxy like `nginx`? Or is the container directly connected to the public port `80`? Proxies, Kubernetes Ingresses, and other intermediate servers can also interrupt WebSocket connections

Hi @anurse !

I ran the container directly in port 80 with this command: **docker run -p 80:80 tecaplus:latest**

**Comment by pedrorja** [comment]
dotnet --output inside container

docker exec -it 057622cf7748 dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by anurse** [comment]
> Could you try collecting a network trace? We have [guidance on how to do this in our documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#network-traces).

Thanks for the info! Can you try collecting a network trace as described here?

**Comment by pedrorja** [comment]
> > Could you try collecting a network trace? We have [guidance on how to do this in our documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#network-traces).
> 
> Thanks for the info! Can you try collecting a network trace as described here?

Hi @anurse 

I installed Telerik Fiddler and captured the network's trace. 
![image](https://user-images.githubusercontent.com/4438494/72549048-be63f000-386e-11ea-9e26-a5914e9b2117.png)


Some requests are returning HTTP 504 error.

Also that, I captured the session and saved in a .saz file, However, I don't know if it's secure to share in this channel.

**Comment by anurse** [comment]
It looks like the WebSocket request is the one that got a 504. The 504 status code is "Gateway Timeout" which generally occurs when a front-end proxy doesn't get a response from a backend service. Are you sure there are no proxies between the browser and your application? Do you have a corporate IT proxy (they can often limit WebSocket support)?
