### ISSUE TITLE
ASP.NET Core 3.1 - Windows Hosting Bundle Installer Doesn't Install Module For IIS Express

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet/aspnetcore#18360]
### Describe the bug

I recently rebuilt my machine and was just using IIS Express. I wanted to host .NET Core in IIS Express, so I was using trying to use the [Windows Hosting Bundle](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.1-windows-hosting-bundle-installer) to install the module. I ran the installer three times. It would successfully complete, but would not install the module assemblies under the following directories:

- C:\Program Files (x86)\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll
- C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll

After enabling full IIS, the installer was able to create these folders and drop the ASP.NET Core module correctly.

### To Reproduce

1. Start with a fresh Windows 10 Installation
1. Install IIS Express
1. Install the Windows Hosting Bundle

**Expected**: Get the assemblies for the ASP.NET Core Module.
**Actual**: The ASP.NET Core Module never installs.

### Expectations

- Support IIS Express
- Install the hosting module even if IIS is not presently installed.

**Comment by mkArtakMSFT** [comment]
@anurse I've assigned both area-labels as I'm not sure where this actually belongs.

**Comment by anurse** [comment]
> I wanted to host .NET Core in IIS Express, so I was using trying to use the [Windows Hosting Bundle](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-3.1.1-windows-hosting-bundle-installer) to install the module. I ran the installer three times. It would successfully complete, but would not install the module assemblies under the following directories:

This is the intended behavior. The Hosting Bundle includes the module for full IIS. The Visual Studio installer brings the module for IIS Express. (cc @shirhatti)

**Comment by anurse** [comment]
Just noticed your other comments about installing IIS **after** the Hosting Bundle. You do have to repair the Hosting Bundle install after installing IIS, this is by design.
