### ISSUE TITLE
ASP.NET Core 2.1 won't run on .NET Core 3.1?

### ISSUE THREAD

**Issue by bencyoung** [dotnet/aspnetcore#18386]
Hi,

I have a exe that pulls plugins in that use ASP.NET Core 2.1 via .netstandard 2 (e.g. plugins that host their own diagnostic server). I've changed the exe to dual target netcoreapp2.1 and netcoreapp3.1. When I run it with:

dotnet run --framework netcoreapp2.1

It spins up fine.

When I run

dotnet run --framework netcoreapp3.1

I get

```
Application startup exception: System.InvalidOperationException: Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
```
If I fix this I get further type errors. 

It looks like something in the core SDK is upgrading the dependencies to ASP.NET Core 3 which I explictly don't want. Is this an intended behaviour? Can I stop it happening? 

Nothing in the VS dependency tree says it will try and use ASP.NET Core 3...

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by chrarnoldus** [comment]
Seems a duplicate of https://github.com/dotnet/aspnetcore/issues/14458

**Comment by bencyoung** [comment]
Agreed, although that was closed with no action! I don't think choosing a .NET version should imply/force the version of a library (ASP.NET Core)

**Comment by bencyoung** [comment]
In that issue @davidfowl says it's possible. Are there any instructions on how to do this? ASP.NET Core is just a very small part of our applications so we don't want it "driving the horse"

**Comment by davidfowl** [comment]
@bencyoung You won't like it and it's not supported and the tooling won't work well.

**Comment by bencyoung** [comment]
I dont understand. .NET Core isn't backwards compatible (I.e. 3 can fail to run something from 2), or theres tooling that infers a library version from a runtime version?

**Comment by davidfowl** [comment]
We ASP.NET Core is part of .NET Core, it's no longer just a bunch of .NET Standard packages on top. That's why this situation is different.

> I dont understand. .NET Core isn't backwards compatible (I.e. 3 can fail to run something from 2), or theres tooling that infers a library version from a runtime version?

Its mostly backwards compatible. ASP.NET Core 3.0 made some breaking changes though https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.0

**Comment by bencyoung** [comment]
Thanks @davidfowl . Slightly long rant coming!

I have to say I'm very surprised, and I'm really struggling to understand the rationale for that. Is there an announcement that says ASP.NET Core is now considered part of .NET Core (in the same way that WCF is part of .NET Framework)?

1. It makes it harder for applications to upgrade to recent .NET Core versions when they only have an incidental dependency on ASP.NET Core, even if they want the benefits that recent version of .NET have.
2. It means any breaking change to ASP.NET Core (and I guess Microsoft.Extensions) should be considered at the same level as a breaking change to one of the System.* namespaces as it could break someone upgrading the platform. This will either be painful for consumers or could slow ASP.NET Core development depending on the route chosen
3. It makes it hard to write common libraries that support multiple ASP.NET Core platforms (I think)

Personally we were extremely happy with the standard "it's a library" NuGet approach of earlier versions. You could still restrict it to .NET Core 3.1 to the the perf benefits, and I think it set a good example to the community of what a nice library approach to something like this was. Now the impression is to be "powerful" you need be integrated with the platform.

I'm also not sure who's life it's going to make easier going this way? Every .NET dev understands NuGet packages, but now this seems a bit all over the place (+ things like FrameworkReference which isn't clear to me etc.)

**Comment by bencyoung** [comment]
Note that if all the above is true then this is the first time (I can remember) in about 16 years of heavy .NET dev that I've seen a pure runtime upgrade cause code, based only on shipped .NET framework code, to break. To me that's a important and concerning development.

**Comment by bencyoung** [comment]
I'll close this one. It's a fait-accompli anyway...
