### ISSUE TITLE
Blazor WebAssembly package renames

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#18384]
These name choices are the outcome from a detailed planning process that aims to balance various requirements and goals. The final naming decisions are:

* Microsoft.AspNetCore.Blazor -> Microsoft.AspNetCore.Components.WebAssembly
* Microsoft.AspNetCore.Blazor.Server -> Microsoft.AspNetCore.Components.WebAssembly.Server
* Microsoft.AspNetCore.Blazor.Build -> Microsoft.AspNetCore.Components.WebAssembly.Build
* Microsoft.AspNetCore.Blazor.DevServer -> Microsoft.AspNetCore.Components.WebAssembly.DevServer
* Microsoft.AspNetCore.Blazor.Templates -> Microsoft.AspNetCore.Components.WebAssembly.Templates
* Microsoft.AspNetCore.Blazor.Mono -> Microsoft.AspNetCore.Components.WebAssembly.Runtime
 
// Experimental packages
* Microsoft.AspNetCore.Blazor.DataAnnotations.Validation -> Microsoft.AspNetCore.Components.DataAnnotations.Validation
* Microsoft.AspNetCore.Blazor.HttpClient -> Moves into BCL

### Why?

In case anyone is wondering, we are **not** removing the Blazor branding. Blazor is, and will be, the name for Blazor as a UI framework including both Blazor Server and Blazor WebAssembly. The only reason we're switching to `Components.WebAssembly` in the *NuGet package names* is for consistency with `Microsoft.AspNetCore.Components` which has already shipped in 3.0 (and is part of Blazor!), and a general principle of having package names that describe functionality rather than product branding.

These changes are to be implemented in the 3.2.0-preview2 milestone.

**Comment by pranavkm** [comment]
Picking this up.

**Comment by javiercn** [comment]
@pranavkm If you pick this up. Can you hold of merging to the end of the milestone to avoid conflicts with all the ongoing work?

**Comment by pranavkm** [comment]
I left the Blazor.HttpClient name as-is for now. Seems unnecessary to change it if the package is going away soon. Using #19117 to track renaming the Blazor.Mono package.

**Comment by pranavkm** [comment]
@SteveSandersonMS do you think this warrants an announcement? Would the preview2 release notes suffice?

**Comment by SteveSandersonMS** [comment]
I would think that specifying this in the upgrade steps will suffice. People will have no way to upgrade to newer packages without using the new names - they will get a restore error if they just change the referenced version numbers and not names. So I think we're OK!
