### ISSUE TITLE
Blazor lifecycle execute more than once.

### ISSUE THREAD

**Issue by jhunexjun** [dotnet/aspnetcore#18382]
### Describe the bug
To be more specific because I wrote the code inside the `OnParametersSetAsync()`, that method executes multiple times. Seems that it executes on how many are the `[Parameter]` are being passed. Just now I checked the other parameters, they are also being executed either 4 or 5 times.

Further, I'm not sure if this is intentional, but a certain component's lifecycle is being executed even if a component is not being called yet. And so the html are already present.

### To Reproduce
What steps can we follow to reproduce the issue?

Just create a component, and write its lifecycle. Run the system and point the breakpoint inside the `OnParametersSetAsync()`.

``` C#
protected override async Task OnParametersSetAsync()
{
   Console.WriteLine("Hello, World!");
}
```

### Further technical details
- ASP.NET Core version 3.1
- Windows 10, VS Pro 2019 v16.4.0

**Comment by javiercn** [comment]
@jhunexjun thanks for contacting us.

OnParametersSetAsync is expected to be called everytime the parameters passed to your component change.

This behavior is by design.

If you want a method that runs only once per component, OnInitializedAsync is your best option.

The intent of OnParametersSetAsync is to allow the component to react to new parameters being passed in. In those situations the component instance is reused.

**Comment by jhunexjun** [comment]
I actually want a lifecycle method runs every time a parameter is passed. OnInitializedAsync() is called only once, how about if I call again the component with new set of parameter? I won't be able to trigger using the new passed param, isn't?

**Comment by jhunexjun** [comment]
I am going to explain it to you in more detail soon. Kinda busy here.

**Comment by jhunexjun** [comment]
For a quick response, how about in a scenario wherein, I would like to insert record into a database every time a new set of parameter is passed. My issue is OnParametersSetAsync() is being called many times, and thus, it inserts records on the number of times. I only expect it to have only one added new record.

**Comment by javiercn** [comment]
@jhunexjun We don't have enough information to understand your question. If you think there is a bug in the framework, please provide a minimal repro project and detailed steps on how to trigger the issue so that we can investigate.
