### ISSUE TITLE
doc update: Enable Cross-Origin Requests (CORS) 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#18390]
See https://github.com/aspnet/AspNetCore.Docs/issues/13423 and [this comment](https://github.com/aspnet/AspNetCore.Docs/issues/13423#issuecomment-552167149) by @mkArtakMSFT 

cc @pranavkm

**Comment by mkArtakMSFT** [comment]
Thanks for the reminder, @Rick-Anderson.
Closing this as we'll be looking into issues in the `AspNetCore.Docs` repo directly.
