### ISSUE TITLE
Use SignalR in netstandard library without asp.net core?

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/aspnetcore#18394]
I have a netstandard library I'm trying to add SignalR to, but I'm not sure how to connect to the Hub without mapping an http endpoint. 
Is it possible to just instantiate a hub and have it listen on a specific port, so I can open a HubConnection ot that port? The tutorial just builds an asp.net core app and maps the hub on an endpoint.
I already added .AddSignalRCore() to my services.
Basically my main project calls an extension method within the library to add some stuff, which also does .AddSignalRCore().

Edit: The library references Microsoft.AspNetCore.SignalR.Core 1.1.0.

**Comment by anurse** [comment]
It's not possible to host ASP.NET Core 3.0 (or higher) components in anything other than a .NET Core application or class library. If you are using a class library, we have documentation on [how to reference ASP.NET Core from it](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio) but it still **requires** .NET Core 3.0 or higher and does not support .NET Standard.

**Comment by halter73** [comment]
> Is it possible to just instantiate a hub and have it listen on a specific port, so I can open a HubConnection ot that port?

WebHost.CreateDefaultBuilder uses Kestrel by default which uses an in-proc server, so building and starting/running a WebHost should do what you want.

**Comment by Regenhardt** [comment]
@halter73 How would I tell it which port to use, and which Hub should use it? THis is my first time using SignalR.

**Comment by Regenhardt** [comment]
I have a coreFx Class library now, but I still don't know how to make the hub listen without mapping an http endpoint.

**Comment by anurse** [comment]
Can you clarify what you mean by "without mapping an http endpoint"? SignalR runs over HTTP so it requires an HTTP endpoint. Can you provide sample code that illustrates the problem?

**Comment by anurse** [comment]
Whoops. Bad bot :).

**Comment by Regenhardt** [comment]
Oh wow you are right. This is one of those times I feel really stupid suddenly. It's quite obvious how SIgnalR works over http. Thank you for the help 😄 .
