### ISSUE TITLE
RenderMode.ServerPrerendered with Authentication seems to cause double rendering of Blazor pages

### ISSUE THREAD

**Issue by ErikApption** [dotnet/aspnetcore#18392]
We have a project with Blazor pages with plenty of AuthorizeView in pages & components and when RenderMode is set to RenderMode.ServerPrerendered, the pages are rendered twice. After the first request completes, there is a new one that completely reloads a page and goes through all OnInitialize(Async) methods a second time.

### Further technical details
- ASP.NET Core version: 3.1.100

**Comment by javiercn** [comment]
@ErikApption thanks for contacting us.

Prerendering the page on the server produces an initial render and then turns it into html after which it disposes the component.

Then when the app starts from the browser it does so from scratch. This is well documented here:
https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#stateful-reconnection-after-prerendering

**Comment by ErikApption** [comment]
Thank you this is indeed well documented. One small thing that would help are messages in the debug log - there is nothing there that mentions pre-rendering.
