### ISSUE TITLE
UserStore AutoSaveChanges = false cause UserManager error conflict foreign key when SaveChanges.

### ISSUE THREAD

**Issue by huang-tianwen** [dotnet/aspnetcore#18407]
#16851 # Describe the bug
When set UserStore AutoSaveChanges to false. UserManager.CreateAsync() and then UserManager.AddClaimsAsync() cause error conflict foreign key in dbContext.SaveChanges().

### To Reproduce
1. Set UserStore AutoSaveChanges to false.
2. Call userManager.CreateAsync().
3. Call userManager.AddClaimsAsync().
4. Call dbContext.SaveChanges().
Error:
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_AspNetUserClaims_AspNetUsers_UserId". The conflict occurred in database "DatabaseName", table "dbo.AspNetUsers", column 'Id'.
The statement has been terminated.

If we call dbContext.SaveChanges between step 2 and 3. It will execute successfully.

### Further technical details
- .Net Core 3.1.0
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.109 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- VS 2019 16.4.3

**Comment by blowdart** [comment]
This is expected. You need to save the user first, so the primary key it has will be there when the claims get created in a separate table with a foreign key.

**Comment by huang-tianwen** [comment]
@blowdart no, it has option to set AutoCommitChanges to false in UserStore, which can use dbContext.SaveChanges() to commit all changes after everything. I don't want to begin a database transaction just for create User and create its Claims based on User information. And when using Azure Sqldatabase, microsoft recommend setting EnableRetryOnFailure in DBContext options which is not support to begin a database transaction.

**Comment by blowdart** [comment]
@ajcvickers This seems like an EF question to me :)

**Comment by huang-tianwen** [comment]
@blowdart I checked the Source code, I don't know if this code will cause this error or not.
AddClaims function call dbContext.DbSet<T>.Add(object) while CreateUser call function dbContext.Add(object).

**Comment by ajcvickers** [comment]
@blowdart Could be a bug.
@huang-tianwen Please attach a small, runnable project that reproduces this behavior so that we can investigate.

**Comment by huang-tianwen** [comment]
[IdentityTest.zip](https://github.com/dotnet/aspnetcore/files/4112227/IdentityTest.zip)
@ajcvickers just run the UnitTest. If the in UserStore.cs file we change the AutoCommitChanges to true, the error will disappear.

**Comment by ajcvickers** [comment]
@HaoK @blowdart EF seems to be working correctly here. It appears that UserManager requires the user to be saved before a claim is added. Is this by-design?

```C#
await userManager.CreateAsync(user, "Qwerty123$%^");
await dbContext.SaveChangesAsync(); // <- this is needed by UserManager
await userManager.AddClaimAsync(user, new System.Security.Claims.Claim("testType", "testValue"));
```

**Comment by HaoK** [comment]
When autosavechanges is false, yeah that's expected

**Comment by huang-tianwen** [comment]
@HaoK from my opinion, when the AutoSaveChanges is false, it should support DbContext.SaveChanges() to commit all changes to database. If not then we lose the purpose of the AutoSaveChanges property in UserStore.

**Comment by HaoK** [comment]
There's limits to what we can do around supporting AutoSaveChanges = false, the flag just basically stops each method from calling save changes, and leaves it up to the user to explicitly call it, that said certain methods do have assumptions (like a user existing), so this behavior is expected
