### ISSUE TITLE
Nullable=Enabled results in required validation errors for parameters or bound properties with default values

### ISSUE THREAD

**Issue by mountain65** [dotnet/aspnetcore#18403]
I generated a new empty WebApplication, .NET Core 3.1 and added <LangVersion>8.0</LangVersion> and <Nullable>enable</Nullable> to my CSPROJ.

Then I added the following controller code:
```   
    [ApiController]
    [Route("api/[controller]")]
    public class CountriesController : ControllerBase
    {
        // GET: api/<controller>
        [HttpGet]
        public IEnumerable<string> GetByLanguage(string language="nl")
        {
            Console.WriteLine(language);
            return new[] { "Nederland", "Duitsland", "Amerika"};
        }
    }
```
When I call this endpoint without a language parameter I get a 400 BadRequest with the followin g ProblemDetail:

```{
    type: "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    title: "One or more validation errors occurred.",
    status: 400,
    traceId: "|a897675b-4df1a9d8146c8919.",
    errors: {
        language: [
            "The language field is required."
        ]
    }
}
```
When I remove the [ApiController] attribute I get the normal optional parameter behaviour once more, OR when I remove the Nullable=enabled option from the CSPROJ.

**Comment by javiercn** [comment]
@mountain65 thanks for contacting us.

@pranavkm any ideas?

**Comment by mountain65** [comment]
Updated the code to include de [ApiController] attribute

**Comment by pranavkm** [comment]
@mountain65, I admit, this is surprising behavior. Non-nullable reference types are treated as [required](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#required-attribute). MVC executes binding and validation prior to inferring default values, consequently you end up getting validation errors for properties and parameters which is always meant to be non-null in the body of the action.

For now, I'd recommend stating that the type is non-null. Alternatively, you may turn off the behavior that implicitly applies non-nullable = Required, by configuring `MvcOptions.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes` as part of your application start:

```C#
services.AddControllers(options => options.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true);
```

**Comment by mountain65** [comment]
I will do that. Thanks.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).
