### ISSUE TITLE
January Validation

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18402]
This issue will be used to collect all info related to the verification data for **Blazor WASM 3.2 - Preview1** release:

Build to use: daily build from https://github.com/dotnet/core-sdk#installers-and-binaries
If you plan to create any Azure resources specifically for the verification work, please create those in the **3.2-p1-validation** resource group, in the **ASP.NET Core Test** subscription.

Make sure to create the issues in aspnet/AspNetCore repo and apply the proper `area-` label as well as the `Validation` label. Put the issue in current milestone.

After you create the issues, add them to the https://github.com/dotnet/aspnetcore/projects/10 project and unassign yourself from this issue.

**Comment by pranavkm** [comment]
* https://github.com/dotnet/aspnetcore/issues/18420

**Comment by NTaylorMullen** [comment]
No Blazor WASM stuff from me.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/issues/18466

**Comment by ryanbrandenburg** [comment]
I don't think I did any Blazor WASM stuff for this release.

**Comment by rynowak** [comment]
https://github.com/dotnet/aspnetcore/issues/18496

**Comment by ajaybhargavb** [comment]
https://github.com/dotnet/aspnetcore/issues/18495

**Comment by SteveSandersonMS** [comment]
https://github.com/aspnet/AspNetCore-Internal/issues/3470#issuecomment-577707818
