### ISSUE TITLE
There isn't a 3.1 version of Microsoft.AspNetCore.Http.Abstractions.dll on Nuget

### ISSUE THREAD

**Issue by rbasniak** [dotnet/aspnetcore#18408]
Hi,

Not sure if I'm on the right place to file this issue, please tell me and sorry if not.

If I create a new ASP.NET Core WebApplication from Visual Studio, using .NET Core 3.1 and need to use `HttpContext`, I need to add  `using Microsoft.AspNetCore.Http` and I'm good to go.

When I create a new .NET Core Class Library, using .NET Core 3.1 and need to use `HttpContext` and add the same using statement, it does not work. Visual Studio doesn't find that namespace, and it hint me to find install the lastest version of `Microsoft.AspNetCore.Http.Abstractions` on Nuget.

When I do that, I  noticed that the version that is installed is `2.2.0` and there isn't a `3.1` version on Nuget.

I thought that was stange and tried to find out how the Web Application project could find the dll. When I go to definition of the `HttpContext` it goes to the following assembly:

```
#region Assembly Microsoft.AspNetCore.Http.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.0\ref\netcoreapp3.1\Microsoft.AspNetCore.Http.Abstractions.dll
#endregion
```

So, somehow there is a `3.1` version of this package, but why isn't it on Nuget or why the class library project can't see it? What's the right way of accessing the `HttpContext` from a class library project?

**Comment by javiercn** [comment]
@rbasniak thanks for contacting us.

You need to add a framework reference to asp.net core. See the migration guide docs for details https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference

**Comment by rbasniak** [comment]
@javiercn I tried to look at the migration guide but looks like I missed that part. Thank you so much for your time!
