### ISSUE TITLE
SignalR Client .Net Standard broken from 3.0>3.1 when compiling in .Net Native

### ISSUE THREAD

**Issue by oduis** [dotnet/aspnetcore#18405]
Scenario
UWP client compiled with .Net Native using latest 3.1.x SignalR C# client.
Protocol: server side events. Compiler: Visual Studio 2019, latest patchlevel.

When upgrading from SignalR 3.0 to 3.1 the client does not receive any server generated event when compiled with .Net Native toolchain. Connection to server works. No error message on client or server. Server side SignalR debug log shows not problem either.

Works again when:
- Compiling WITHOUT .Net Native toolchain
- or downgrading to SignalR C# client 3.0.2

So it seems there is some special code change in 3.0>3.1 that interferes with .Net native compilation.

**Comment by BrennanConroy** [comment]
> So it seems there is some special code change in 3.0>3.1 that interferes with .Net native compilation.

That is surprising, we didn't make very many changes between 3.0 and 3.1.

Would it be possible for you to upload a project on github that's effectively an F5 run so we can try to diagnose the issue?

**Comment by oduis** [comment]
Yes, I already searched the commit history but couldn't find anything that looked like it might be optimized out by the native compiler. Might be a native toolchain compiler bug that just manifests with SignalR 3.1 upgrade by coincident.
Unfortunately I cannot share the code since it is a customer proprietary project. But it is 100% reproducible.

**Comment by BrennanConroy** [comment]
I'm not sure what to say. We have 0 experience with using .NET Native.

Does the issue only repro with SSE?

**Comment by oduis** [comment]
I just switched over to LongPolling, same problem. And still 100% reproducable.

According to the Microsoft documentation for .Net Native the trouble usually occurs which dynamic programming, reflection and serialization. Were there any changes in these areas?

**Comment by BrennanConroy** [comment]
I don't believe there were any changes in the SignalR .NET Client related to reflection.

However there were likely changes in the System.Text.Json library which we use.
You could try switching to Newtonsoft.Json and seeing if the issue still exists. See our docs for how to do that https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#use-newtonsoftjson-in-an-aspnet-core-30-signalr-project

**Comment by oduis** [comment]
That seems to be it! Switching just the Client to NewtonsoftJSON resolve the problem with .Net Native compilation.
Can I mix this? So keep the SignalR Server on the new System.Text.Json and just switch the client to Newtonsoft till the problem is resolved some day? Seems to work.

**Comment by BrennanConroy** [comment]
> keep the SignalR Server on the new System.Text.Json and just switch the client to Newtonsoft

Yes, they work together. Just make sure to test your payloads between the two libraries because there are some differences in what is supported.

**Comment by oduis** [comment]
Thanks for help! It might be a good idea to add some hint about the .Net Native compilation restriction to the SignalR Newtonsoft documentation.
.Net Native Compilation is a requirement for published Windows Store apps, and you surely expecting a flood of touch optimized UWP apps for Win 10X  ;-)

**Comment by BrennanConroy** [comment]
The type of error your app gets when hitting this issue is:
```c#
Microsoft.AspNetCore.SignalR.Client.HubConnection:Error: Failed to bind arguments received in invocation '(null)' of 'Send'.

System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.Reflection.MissingMetadataException: 'System.Text.Json.Serialization.Converters.JsonConverterString' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
   at SharedLibrary!<BaseAddress>+0x134a900
   at System.Text.Json.JsonPropertyInfo.Initialize(Type, Type, Type, Type, PropertyInfo, Type, JsonConverter, JsonSerializerOptions) + 0x155
   at System.Text.Json.JsonPropertyInfoCommon`4.Initialize(Type, Type, Type, Type, PropertyInfo, Type, JsonConverter, JsonSerializerOptions) + 0x4b
   at System.Text.Json.JsonClassInfo.CreateProperty(Type, Type, Type, PropertyInfo, Type, JsonConverter, JsonSerializerOptions) + 0x93c
   at System.Text.Json.JsonClassInfo.AddProperty(Type, PropertyInfo, Type, JsonSerializerOptions) + 0xe3
   at System.Text.Json.JsonClassInfo.AddPolicyProperty(Type, JsonSerializerOptions) + 0x4c
   at System.Text.Json.JsonClassInfo..ctor(Type, JsonSerializerOptions) + 0x899
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type) + 0x79
   at System.Text.Json.ReadStackFrame.Initialize(Type, JsonSerializerOptions) + 0x38
   at System.Text.Json.JsonSerializer.ReadValueCore(Utf8JsonReader&, Type, JsonSerializerOptions) + 0xa9
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader&, Type, JsonSerializerOptions) + 0x6c
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindType(Utf8JsonReader&, Type) + 0x30
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader&, IReadOnlyList`1) + 0xeb

   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader&, IReadOnlyList`1) + 0x25c
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1, IInvocationBinder) + 0xbe0
```

For simple usages you can use the [MissingMetadataException troubleshooter](https://dotnet.github.io/native/troubleshooter/type.html) to add known types to your RD.xml file. In my sample app I was just using strings for Hub method parameters so I only needed to add `JsonConverterString`.

@ahsonkhan is using .NET Native with System.Text.Json documented anywhere?

@anurse should we add a document about using .NET Native with the SignalR Client?

**Comment by oduis** [comment]
There is no error message at all, that is the problem. Just no message received.
There is also the slight chance that it might be a weired compiler error and just pure chance that it failed compiling that particular program correctly.

**Comment by BrennanConroy** [comment]
There will be an error message on the client side (since that's where the problem is occurring).
If you're using VS to debug the app then you'll need to add the debug logger for it to show up. Otherwise you'll need a file logger or the console logger and something that captures console output from a UWP app?

> There is also the slight chance that it might be a weired compiler error and just pure chance that it failed compiling that particular program correctly.

Given that I reproduced the same or similar issue that seems doubtful.

**Comment by oduis** [comment]
You're right, can confirm it works when adding the whole namespace to Default.rd.xml:
<Namespace Name="System.Text.Json.Serialization.Converters" Serialize="Required Public" />

**Comment by BrennanConroy** [comment]
> global unhandled exception handler

That's because it is a handled exception and we log it.
