### ISSUE TITLE
StaticWebAssetsFileProvider.cs System.NotImplementedException when using app.UseDirectoryBrowser()

### ISSUE THREAD

**Issue by rob-ack** [dotnet/aspnetcore#18416]
### Describe the bug
From this line of code:
https://github.com/dotnet/aspnetcore/blob/44e44931fe4050e82b2877047b5104d779147f78/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsFileProvider.cs#L138

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLSRADOA4F8O", Request id "0HLSRADOA4F8O:00000001": An unhandled exception was thrown by the application.
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider.StaticWebAssetsDirectoryRoot.StaticWebAssetsFileInfo.get_LastModified()
   at Microsoft.AspNetCore.StaticFiles.HtmlDirectoryFormatter.GenerateContentAsync(HttpContext context, IEnumerable`1 contents)
   at Microsoft.AspNetCore.StaticFiles.DirectoryBrowserMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

I get this exception by using `app.UseDirectoryBrowser();`.
I also have disabled the `app.UseDeveloperExceptionPage();` which gives me more details on exception callstack since the ExceptionPage does lead to a different callstack.

I can not make to much sense out of this error at the moment, but i guess this method should be implemented (or least lead to an FileNotFound exception)
I'm referencing an RCL which i load at runtime into an AssemblyLoadContext. Clearly the issue is related to static web assets which may not be build or located correctly yet in my case. Due to the fact that i use custom dll locations and do not reference the dlls in my AppHost project as direct dependencies (which may cause the build pipeline to miss something. going to investigate this now ;)).

### Further technical details
- ASP.NET Core version 3.1 using latest Blazor.Server 3.1.0-preview4.19579.2
- Include the output of `dotnet --info`
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.101
 Commit:    b377529961

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- Visual Studio 2019 16.4.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn can you please look into this? Thanks!

**Comment by RobertAcksel** [comment]
From what i see so far you do not leave a distinct path open for me to load my RCL's as plugin like application extension when it comes to static web assets.

[When i read through the code](https://github.com/dotnet/aspnetcore/blob/44e44931fe4050e82b2877047b5104d779147f78/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsLoader.cs#L87) i see that you do expect an xml file generated during build time consumed by the hosting asp application to locate static webassets (development time, not at when published which have not investigated now).

However since my RCL is not referenced directly the *StaticWebassets.xml file will never contain the needed information about my RCL and its web assets. 
Additionally the StaticWebAssetsFileProvider class is made internal which does not enable me to work around the problem by providing my own StaticWebAssetsFileProvider (without reflection).

Did i miss some way of doing it so far?

**Comment by javiercn** [comment]
@RobertAcksel static web assets are a compile time feature with development time runtime support. 

It is expected that you know all the assets that will be part of the app at compile time, it's not meant to provide access to assets from multiple locations at runtime.

If you want to enable that, you can replace the `WebHostEnvironment.WebRootFileProvider` which is what static web assets do.

At publish time, we copy the assets to the wwwroot folder of the app at the specified locations. The runtime component we have is meant to support a better development experience by avoiding copying files around, which allows the files to be modified in place and for the content updates to be reflected without stopping and starting the app.

**Comment by javiercn** [comment]
We believe this is fixed in 6.0-rc1, let us know otherwise
