### ISSUE TITLE
"GetStreamItemType does not have an implementation" when using SignalR in Console

### ISSUE THREAD

**Issue by chrfin** [dotnet/aspnetcore#18415]
I just found out that my usage of SignalR in my console application broke. The same code did work in the past, but I do not know when exactly it broke, as I did not use that part of our program in the last few month.

### Describe the bug
When calling the following:
``` C#
serviceHost = new WebHostBuilder()
		  .UseKestrel()
		  .UseStartup<IpcServer.Startup>()
		  .UseUrls("http://*:8080/")
		  .Build()
```
with the following startup class:
``` C#
public class Startup
{
	public void ConfigureServices(IServiceCollection services)
	{
		services.AddSignalR().AddMessagePackProtocol();
	}

	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		app.UseSignalR(routes =>
			{
				routes.MapHub<IpcServer>("/ipc");
			});
	}
}
```
I get the following exception

> Method 'GetStreamItemType' in type 'Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1' from assembly 'Microsoft.AspNetCore.SignalR.Core, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
> at Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions.AddSignalRCore(IServiceCollection services)  
> at Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions.AddSignalR(IServiceCollection services) 
> at UserQuery.Startup.ConfigureServices(IServiceCollection services), line 20
> --- End of stack trace from previous location where exception was thrown ---  
> at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)  
> at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()  
> at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()  
> at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build() 
> at UserQuery.Main(), line 3

### To Reproduce

Run the following (e.g. in LINQPad):
``` C#
void Main()
{
	using (var host = new WebHostBuilder()
				.UseKestrel()
				.UseStartup<Startup>()
				.UseUrls("http://*:8080/")
				.Build())
	{
		host.Run();
	}
}

public class Startup
{
	public void ConfigureServices(IServiceCollection services)
		=> services.AddSignalR().AddMessagePackProtocol();

	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		=> app.UseSignalR(routes => routes.MapHub<TestHub>("/test"));
}

public class TestHub : Hub
{
	public Task Send(string name, string message)
		=> Clients.All.SendAsync("Message", name, message);
}
```

### Further technical details
- .NET Core 3.1
- Windows 10
- ASP.NET Core SignalR 1.1.0

**Comment by BrennanConroy** [comment]
You should be referencing ASP.NET Core SignalR 3.1 if you're using .NET Core 3.1.
And since SignalR is in the shared framework, you actually don't add a package reference to it anymore, it's there by default for web apps targeting netcoreapp3.1.

**Comment by chrfin** [comment]
And what package do I need to reference if I am using e.g. the WPF template (`Sdk="Microsoft.NET.Sdk.WindowsDesktop"`) and not a web app?
Or when developing a .NET Standard 2.0 library which self-hosts a SignalR hub?

**Comment by anurse** [comment]
> what package do I need to reference if I am using e.g. the WPF template (`Sdk="Microsoft.NET.Sdk.WindowsDesktop"`) and not a web app?

If you are using a non-Web app, you can reference ASP.NET Core using a `FrameworkReference`, as long as you target .NET Core 3.0/3.1. We have documentation on how to do this in our ["Use ASP.NET Core in a class library"](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio) doc (it says "class library" but it should also work in a WPF app.

Are you trying to host an ASP.NET Core server **inside** a WPF app?

> Or when developing a .NET Standard 2.0 library which self-hosts a SignalR hub?

You can't host a SignalR Hub in a .NET Standard 2.0 library, it requires .NET Core 3.0 or higher.

**Comment by chrfin** [comment]
Adding the Framework reference helped. It's working now :-).

> Are you trying to host an ASP.NET Core server inside a WPF app?

Yes, we are using SignalR for real-time communication between two devices (one Windows PC and one embedded device running .NET Core on Linux).

**Comment by anurse** [comment]
@chrfin Glad the framework reference worked out!

> Yes, we are using SignalR for real-time communication between two devices (one Windows PC and one embedded device running .NET Core on Linux).

Very cool! Sounds like a great project.

**Comment by chrfin** [comment]
@anurse  Yes, cool project - will be a commercial product and we are developing the first prototype at the moment. To top it of and show the capabilities of SignalR: We transfer around 5.000-10.000 commands per second between the two devices at a data-rate of ~30 MBit/s (using MessagePack). We investigated different technologies (like gRPC and some other) and SignalR was the easiest to use and on par performance-wise as the top of the bunch :-)...

**Comment by anurse** [comment]
@chrfin Great to hear (and aligns with what we've heard from other customers as well)! Let us know if you need help with any other issues!
