### ISSUE TITLE
Blazor Intermittent Loading Issue

### ISSUE THREAD

**Issue by Bluebeerd** [dotnet/aspnetcore#18411]
We are having an issue with Webassembly, where sometimes we run our code and it works fine, but another time using the same unmodified code, it throws an error. Doing a reload, it then works fine again.
Is anyone else having this behaviour and if so, how do you handle it ?

Example error below

blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
blazor.webassembly.js:1 WASM: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Components.Forms, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
blazor.webassembly.js:1 WASM: File name: 'Microsoft.AspNetCore.Components.Forms, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
blazor.webassembly.js:1 WASM: at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0 (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) <0x2a7d8b0 + 0x0001a> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0
blazor.webassembly.js:1 WASM: at (wrapper delegate-invoke) <Module>.invoke_void_RenderTreeBuilder(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder)
blazor.webassembly.js:1 WASM: at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x2a7d1b0 + 0x00058> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0
blazor.webassembly.js:1 WASM: at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Components.Rendering.RenderQueueEntry renderQueueEntry) <0x2a7cc30 + 0x0004c> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0
blazor.webassembly.js:1 WASM: at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x2a7c2a8 + 0x00092> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
Please also include the browser network tab state (screenshot, any errors?).

**Comment by Bluebeerd** [comment]
I've finally got a minimal project that reproduces the Intermittent loading problem.
Reproduced on two different computers, I managed to get an error after 7 runs, gave up after 20 on another cycle and got the error after 10 runs on a third cycle.
Steps to reproduce:

Hit F5
When the browser opens, hit the 'Counter' button a couple of times to show it's working
Stop Debug

Repeat the above until the program fails to load

Example project at https://github.com/Bluebeerd/Intermittent_Loading

![Unhandled_error_2](https://user-images.githubusercontent.com/19287848/74023843-839a3700-4998-11ea-8680-6d3e20235f60.jpg)
![Unhandled_error_1](https://user-images.githubusercontent.com/19287848/74023847-84cb6400-4998-11ea-8e17-365df6dbf760.jpg)
[Unhandled_error_txt_2.txt](https://github.com/dotnet/aspnetcore/files/4170367/Unhandled_error_txt_2.txt)
[Unhandled_error_txt_1.txt](https://github.com/dotnet/aspnetcore/files/4170368/Unhandled_error_txt_1.txt)

**Comment by rynowak** [comment]
Issue author responded with a repro

**Comment by javiercn** [comment]
@Bluebeerd thanks for contacting us.

Does the network tab show any error when that happens? (Like failing to download a dll?)

**Comment by mkArtakMSFT** [comment]
We believe we have a change we're working on which will potentially eliminate this issue completely by showing the underlying issue. We're closing this issue for now. Please report back after the upcoming release if you happen to repro this again.
