### ISSUE TITLE
Another IdentityServer, SameSite, Core 2.1 - Not Removing Cookies

### ISSUE THREAD

**Issue by onarres** [dotnet/aspnetcore#18419]
I wrote a question on https://github.com/IdentityServer/IdentityServer4/issues/3901 which had a response to open an issue here. I also saw similar issues and didn't know if I should comment on those or create a new
https://github.com/dotnet/aspnetcore/issues/17833
https://github.com/dotnet/aspnetcore/issues/17980

What I wrote in the idsrv issue: 
I am running AspNetCore 2.1.15, IdentityServer4 2.4.0, and have back ported the chunking cookie manager as described in https://www.thinktecture.com/identity/samesite/how-to-delete-samesite-cookies and dotnet/aspnetcore#17953.

I am an auth code grant JS client and can log in fine. I see the cookies get dropped for the JS site and idsrv for .AspNetCore.Antiforgery, .AspNetCore.Identity.Application, and idsrv.session. I initiate a logout in the JS client (which executes the signoutRedirect on the oidc-client manager). From the JS domain, everything looks good but if I navigate to the idsrv domain the cookies still exist and the user is not fully logged out.

Before updating to core 2.1.15 and before setting up a cookie policy as described here https://www.thinktecture.com/identity/samesite/prepare-your-identityserver/ it would delete cookies for both domains.
Also, if I keep all the newer code in place and just I disable the chrome flags "SameSite by default cookies" and "Cookies without SameSite must be secure" then the cookies get removed too (I'm still in chrome 79) - so it has to be something around these settings.

The logout action in my account controller does call await _signInManager.SignOutAsync();

I have a fiddler capture in a comment below.

**LOGIN**
**account/login** 
Request - Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs
Response - Set-Cookie: .AspNetCore.Identity.Application=CfD; path=/; secure; samesite=none; httponly
Response - Set-Cookie: idsrv.session=4aed; path=/; secure; samesite=none

**connect/authorize**
Request - Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfD; idsrv.session=4aed; .AspNetCore.Identity.Application=CfD
Response - Set-Cookie: .AspNetCore.Identity.Application=CfD; path=/; secure; samesite=none; httponly

**LOGOUT**
**connect/endsession**
Request - Cookie: idsrv.session=4aed; .AspNetCore.Identity.Application=CfD; 

**account/logout**
Request - Cookie: idsrv.session=4aed; .AspNetCore.Identity.Application=CfD;
Response - Set-Cookie: .AspNetCore.Identity.Application=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=none
Response - Set-Cookie: Identity.External=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=none
Response - Set-Cookie: Identity.TwoFactorUserId=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
Response - Set-Cookie: idsrv.session=.; expires=Thu, 17 Jan 2019 15:14:36 GMT; path=/; secure; samesite=none

**connect/endsession/callback**
Request - Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfD; .AspNetCore.Identity.Application=CfD;

**VERIFY**
**Now if I navigate to idsrv's domain in my browser**
Request: Cookie: .AspNetCore.Antiforgery.9TtSrW0hzOs=CfD; .AspNetCore.Identity.Application=CfD; idsrv.session=4aed

Which leaves the user still logged in and not prompted to reenter credentials when I click login via the JS Client.

Any help or places to check is appreciated. I am clearly missing something that needs to be modified.

**Comment by onarres** [comment]
I sanitized my fiddler capture, here it is: 

[2020.01.17.samesiteNotLoggingOut.saz.zip](https://github.com/dotnet/aspnetcore/files/4077986/2020.01.17.samesiteNotLoggingOut.saz.zip)

**Comment by onarres** [comment]
From digging in fiddler, I see that the .AspNetCore.Identity.Application cookie is not getting deleted during the https://api.idsrv.local/Account/Logout?logoutId and is sent with the iframe call to https://api.idsrv.local/connect/endsession/callback?endSessionId

**Comment by onarres** [comment]
I figured it out. Elsewhere in our codebase there was a call to services.ConfigureApplicationCookie() to set a different login and logout paths. In this block I had to add the "options.CookieManager = new BackPortedChunkingCookieManager()"
 
I kept trying to figure out why idsrv.session worked fine, but that had nothing to do with what I thought I previously fixed; instead that is due to the idsrv's user session code, it has a method that sets the cookie options on create and delete with the secure flag.

**Comment by kickertw** [comment]
What is BackPortedChunkingCookieManager?

**Comment by onarres** [comment]
@kickertw There are fixes in the ChunkingCookieManager that were applied to the Core 3.1 branch to fix the problem with not sending the secure flag in the cookie deletion that are scheduled (last I checked) to be ported into Core 2.1's branch in March as referenced in https://github.com/dotnet/aspnetcore/pull/17953 I took the the ChunkingCookieManager from the 3.1 branch and added it into my project and named it BackPortedChunkingCookieManager.

A few places talk about doing this, the first I found was here: https://www.thinktecture.com/identity/samesite/how-to-delete-samesite-cookies/

**Comment by hugoqribeiro** [comment]
Hi @onarres.

I'm having the same exact problem.
I implemented your solution with BackPortedChunkingCookieManager in services.ConfigureApplicationCookie() but this has no effect.

I get the same error with cookie named "Identity.External". I debugged the cookie manager but DeleteCookie never gets called. Not even GetRequestCookie with such key...

Any idea?

**Comment by onarres** [comment]
For me the best troubleshooting I had was to run fiddler, see what and how the cookies were dropped during login (which flags are set, etc). Then when you logout, see what is sent to remove the cookies.  The problem is there are so many potential configurations that are not standardized for login/logout.  For me, I was using a version of the sample UI about a year old and it was calling the signInManager.SignOutAsync() which calls https://github.com/aspnet/Identity/blob/feedcb5c53444f716ef5121d3add56e11c7b71e5/src/Identity/SignInManager.cs#L203

**Comment by hugoqribeiro** [comment]
I figured it out and it's so simple.

The "Identity.External" cookie is configured by services.ConfigureExternalCookie(), not services.ConfigureApplicationCookie(). Obvious... now... :)

I applied the ported cookie manager on that. And it works now.

**Comment by onarres** [comment]
Glad you figured it out. Like I said, there are so many permutations.
