### ISSUE TITLE
Blazor state management

### ISSUE THREAD

**Issue by physix99** [dotnet/aspnetcore#18413]
I've read this guide over and over
[https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1)

I might being missing something obvious, but I cannot figure out how you are actually suppose to store the state in the database on server-side, as there is no way of accessing a unique ID for each client. We are using Blazor server side, asp.net core 3.1, and we have prerendering turned on (which we need).

I was thinking of using the Circuit ID from signalR but I think this will change on a page refresh, and it won't be present on prerender? I have got around it via injecting a "SessionService" (which is scoped) into _Host, in which I generate a new session object and store the ID in a cookie, I then pass this ID into the app component, then on OnInitialized in App.razor, I pass this ID back into the "SessionService", so i can then retrieve the session object from any component.

It seems a bit over complicated for such a simple task?

The cookie currently has an expiry time of 1 hour, because it's now SPA the cookie will not have its expiry time extended by changing page etc.. the only way round I can see if to use JSInterop and update the cookie expiry time via javascript? again this seems a bit of hack?

Am I being thick and missing something really simple?

Thanks

**Comment by Bartmax** [comment]
Why not use local storage? You can also sync "session data" between server/client to support offline session data with a little effort.

I think it would be great to have something already. Unless I'm missing something a component that handle common scenarios should be quite trivial.

**Comment by physix99** [comment]
The problem with local storage is you can only access it after render in server mode, which means delaying until the page has fully rendered, then loading the session. Just means there is a longer loading screen.

**Comment by Bartmax** [comment]
I now see what you mean and I believe you are on the right track, except *maybe* on the cookie expiration. I think it's reasonable to have a session cookie (without expiration time, that expire when the browser is closed) so you do not need to deal with expiration/interop.

Do you need to persist session data after browser is closed?

**Comment by physix99** [comment]
The website is question is basically an e-commerce site, so yea I need to be able to keep their session after browser closed, incase of crashes etc...

**Comment by belenos12345** [comment]
I'm interested in implementing a session state handling such as the described one with the "SessionService", but don't have any idea how to do that.
Do you have an example how the session object and the cookie are generated?
