### ISSUE TITLE
Avoid using AuthorizeFilter in project templates

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/aspnetcore#18412]
### Is your feature request related to a problem? Please describe.
The default template for Org Auth in a web app is confusing

### Describe the solution you'd like
A solution that makes it clearer where code is more self explanatory

### Additional context

See here

https://github.com/dotnet/aspnetcore/blob/44e44931fe4050e82b2877047b5104d779147f78/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Startup.cs#L112

I believe a more self describing solution that aligns with the documents should use Default or Fallback Auth policy such as

### Option 1

In ConfigureServices
```csharp
services.AddAuthorization(options =>
{
    options.FallbackPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});

services.AddRazorPages();
```
and in Configure
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages();
    endpoints.MapControllers();
});
```
### Option 2
In ConfigureServices
```csharp
services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});

services.AddRazorPages();
```
and in Configure
```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapRazorPages().RequireAuthorisation();
    endpoints.MapControllers().RequireAuthorisation();
});
```

**Comment by mkArtakMSFT** [comment]
@captainsafia did you do this already?

**Comment by captainsafia** [comment]
I did this but missed updating these templates. I'll submit a follow-up PR for these.
