### ISSUE TITLE
Uploading multipart form data to IFormFile length is zero

### ISSUE THREAD

**Issue by nixa333** [dotnet/aspnetcore#18417]
Hi guys,

we have an app where users can upload files as a part of the form they're posting to the backend. This file is received as IFormFile type property. We got reports that users are uploading the files but apparently we're not receiving them. When we set up additional logging, we found out that sometimes we receive a request which has IFormFile property instantiated, it even has FileName properly set to the name of the file being uploaded, but the Length property equals zero. I personally can't even reproduce this but the log shows it is indeed happening.
The log is showing it mostly happens on Safari 12/13 on iPhone, but we did also find occurrences of it on Windows/Edge and other combinations of OS/Browser.
As I can't reproduce it and log doesn't show any errors, does anyone have any idea why it could happen, or how it could happen that IFormFile ends up not being null and has FileName set but length is zero? Apparently that file stream reaches the server as it has the FileName, but what happens with the rest of it... 

We're using **ASP.NET core 3.0 MVC** as the backend.

HTML:
```HTML
<form id="myForm" enctype="multipart/form-data">
    <input class="form-control input-file" type="file" name="File">
    <button type="button" id="btnSubmit" class="btn btn-primary btn-lg">Submit</button>
</form>
```

Javascript (on btnSubmit click):
```Javascript
var formData = new FormData(document.querySelector('#myForm'));

var xhr = new XMLHttpRequest();
xhr.onload = function () { 					
    // ...
};
xhr.onerror = function () {
    // ...
};
xhr.open('POST', '/SaveFile');
xhr.send(formData);
```

MVC backend:
```csharp
[Consumes("multipart/form-data")]
public async Task<IActionResult> SaveFile(MyClass model)
{
    // At this point model.File.Length would be zero, but model.File.FileName would have the 
    // expected value of the file name

    // ...
}
```

MyClass:
```csharp
public class MyClass
{
    public IFormFile File { get; set; }
}
```

**Comment by javiercn** [comment]
@nixa333 thanks for contacting us.

@Tratcher do you have any idea? I believe MVC has a modelbinder for IFormFile, but the only thing it does is to grab it from the request feature.

@pranavkm does the MVC side of things looks right to you?

**Comment by Tratcher** [comment]
Unfortunately there's no way to debug this without a repro. Ideally we'd get a capture of the request headers and body via Fiddler, Wireshark, etc.. Failing that, you should be able to write some diagnostics into SaveFile. When you detect this condition,

A) Enumerate HttpContext.Request.Form.Files and see if there's more than one element, if any of them have any data, etc..

B) Capture the headers and body:
1. Turn on form request body buffering (warning, this will have a memory and disk perf hit).
`[RequestFormLimits(BufferBody = true)]`
1. Rewind the request body: `HttpContext.Request.Body.Seek(0, SeekOrigin.Begin);`
1. Write out the request headers and body to a file and share them here (or privately).

**Comment by nixa333** [comment]
Here's the request data. I've redacted some of it to remove personal and sensitive info that I believe is not relevant to the issue.

**HEADERS:**
Accept: */*
Accept-Encoding: br
Accept-Language: hr-hr
Connection: Keep-Alive
Content-Length: 3495
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryUOcMGIQnPWtTqeaY
Cookie: tl_id=f9bd0dd1-3a97-4fff-93be-63a8531a663f; tl_session_id=404bc359-d719-492e-8866-82caa767f729
Host: -------------------------
Max-Forwards: 10
Referer: -------------------------
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1
x-requested-with: XMLHttpRequest
origin: -------------------------
X-WAWS-Unencoded-URL: /MyUrl
CLIENT-IP: 31.217.5.124:1119
X-ARR-LOG-ID: 68e7d667-682d-4651-b4a4-ef68aefe1e9e
DISGUISED-HOST: -------------------------
X-SITE-DEPLOYMENT-ID: -------------------------
WAS-DEFAULT-HOSTNAME: -------------------------
X-Original-URL: /MyUrl
X-Forwarded-For: 31.217.5.124:1119
X-ARR-SSL: 2048|256|C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3|CN=-------------------------
X-Forwarded-Proto: https
X-AppService-Proto: https

**FILES:**
Name: Resume | FileName: CV-Europass-20191022-HR.pdf | Length: 0 | Content type:application/pdf

**BODY:**
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="JobId"

17407
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="FirstName"

-------------------------
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="LastName"

-------------------------
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Email"

martinakerep@hotmail.com
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Phone"

0993498789
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Location"

-------------------------
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="CoverLetter"

-------------------------
 
 
-------------------------
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Resume"; filename="CV-Europass-20191022-HR.pdf"
Content-Type: application/pdf


------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Answers[0].Choices"

26025
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Answers[0].Choices"

26065
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Answers[0].Choices"

26067
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Answers[0].Choices"

26068
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Answers[0].Choices"

26069
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Answers[0].Id"

10535
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="invalidSource"

false
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="id"

17407
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="subdomain"

-------------------------
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="websiteId"

3269
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="pageId"

13223
------WebKitFormBoundaryUOcMGIQnPWtTqeaY--

**Comment by Tratcher** [comment]
That does look like a zero length file, unless you altered this part?
```
------WebKitFormBoundaryUOcMGIQnPWtTqeaY
Content-Disposition: form-data; name="Resume"; filename="CV-Europass-20191022-HR.pdf"
Content-Type: application/pdf

------WebKitFormBoundaryUOcMGIQnPWtTqeaY
```

**Comment by nixa333** [comment]
Haven't modified it, that's how the asp.net logged it. 
The thing is, users are uploading their files and it wouldn't make sense that so many of them would have zero length. The files in question are resumes, and it's in the best interest of the person uploading it to actually contain content. I'll try to acquire some of those files, but I'm inclined to thing that it doesn't really have to do anything with them, but something else. 
Is it possible that for reasons of bad connection or similar issue, the file stream gets "dropped" or something like that? As I mentioned, these are mostly iPhones we're having problems with, so it could be a combination of mobile network and iOS/Safari that is causing the issue. I'm just guessing at this point, I don't actually understand how any of this would/could happen.

**Comment by Tratcher** [comment]
The request body is well formatted and complete, that doesn't get modified by the server at all. It looks like there's a bug in the client code that's generating the body.

**Comment by nixa333** [comment]
Great, thanks for your time! We'll check the client to see if we can find anything.
