### ISSUE TITLE
Produce API Refs for Blazor WASM

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18427]
- [x] Produce XML doc files and include in packages
- [x] Publish API ref docs on https://docs.microsoft.com/dotnet/api

**Comment by mkArtakMSFT** [comment]
Submitted the request for the docs publishing.

**Comment by mkArtakMSFT** [comment]
Request being tracked here: https://ceapex.visualstudio.com/Onboarding/_workitems/207902

**Comment by pranavkm** [comment]
This is done, no?
