### ISSUE TITLE
MapRazorPages() required even if main project is MVC only

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/aspnetcore#18422]
### Is your feature request related to a problem? Please describe.
If an MVC project uses a library that contains razor pages for example the `Microsoft.AspNetCore.Authentication.AzureAD.UI`
Then we need to provide MapRazorPages() to the endpoint configuration even though we are only using MVC in the main project

```
            services.AddControllersWithViews();
```
We still have to add
```
         app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();  # Not obvious that this is needed
                endpoints.MapControllers();
            });
```

This caused me hours of not knowing why my logout page was not rendering.
I had to look at the source of the library to work it out.
Since my project is not RazorPages it was not immediately obvious that I had to add this to my startup config

### Describe the solution you'd like
Not sure ???  Just want to make it easier for others to discover

**Comment by javiercn** [comment]
@mikes-gh thanks for contacting us.

This is a result of our changes in 3.0. Not sure if we could have better docs or an Analyzer for this. It would likely mean we do the same thing for the Identity package too.

**Comment by mikes-gh** [comment]
You could add docs but I think some sort of compile time check would be preferable.

**Comment by javiercn** [comment]
@mikes-gh the analyzer is the compiler check.

**Comment by mikes-gh** [comment]
Yeh sorry that what I meant  my vote is analyzer over docs.

**Comment by mkArtakMSFT** [comment]
This is not something we plan to change in the near future.
