### ISSUE TITLE
Catch Blazor error “The following routes are ambiguous” at compile time

### ISSUE THREAD

**Issue by multco-malan** [dotnet/aspnetcore#18421]
### Is your feature request related to a problem? Please describe.
I am trying to catch ambiguous blazor routes at compile time.

### Describe the solution you'd like
I do NOT want to wait until runtime to "discover" that the app has ambiguous routes.

### Additional context
https://stackoverflow.com/questions/59743746/catch-blazor-error-the-following-routes-are-ambiguous-at-compile-time

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @multco-malan.
This is not something we plan to do in the near future. We will reconsider, if we hear too much asks similar to this.
