### ISSUE TITLE
Clean way to guard routing

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18425]
_From @hoksource on Friday, December 13, 2019 11:54:58 PM_

Is there a clean way to guard specific events when user goes to a specified route. I want to be able to prevent users from accessing a set of page or redirect users to another page if a condition is met. I'm looking for something like
- angular routing guards
- or razor pages filters
- or page component base class that triggers onRoutingToPage
- or onRoutingToLayout (this applies for all pages under it)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

_Copied from original issue: aspnet/AspNetCore.Docs#16192_

**Comment by javiercn** [comment]
@hoksource thanks for contacting us.

You can use AuthorizeView to accomplish this and use a custom authorization policy to check for any condition you want as part of validating the policy requirements.

See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1 for examples on how to create and configure policies.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn 's provided approach would work just fine. But it's interesting to know what other (non-auth) scenarios you're thinking about, where this would be useful?

**Comment by hoksource** [comment]
Thank you for looking at my request.

I would like to do something that access the current page/component context reads the querystring/url parameters. Then checks the database if the current user has access to the specific page && querystringid && url parameters. Then redirect the user to another page depending on the requirement. If the user is not logged in then the user is asked to register/login. If the page was set to be restricted or has private sharing, redirect the user to another page that says the page is private.

I will have to do this to multiple pages. lets say mywebsite.com/{userId}/albums/subpages
depending on the state if the viewer is not "userid" the user will have different response. I will probably apply this to a AlbumPageBaseComponent and every subpages are component that inherits AlbumPageBaseComponent. This AlbumPageBaseComponent has a layout that applies to all subcomponents. so depending on the privacy/sharing set the interaction should be different.

**Comment by javiercn** [comment]
@hoksource you could do something like this.

```razor
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <MyCustomWrappingComponent RouteData="@routeData">
            <AuthorizeView>
                <Authorized>
                    <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
                </Authorized>
                <NotAuthorized>
                    <MyCustomRedirectComponent />
                </NotAuthorized>
            </AuthorizeView>
        </MyCustomWrappingComponent>
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```
