### ISSUE TITLE
Blazor: Allow @namespace directive to be inherited through _Imports.razor

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#18426]
This is simply a convenience feature to make it easier to organize components into namespaces.

Idea: allow application of a `@namespace` directive in `_Imports.razor` files that is then inherited like other directives.  It can be overridden in specific components like `@layout` if necessary.

**Comment by rynowak** [comment]
Hi @zbecknell - I think `@namespace` might already work in a way similar to what you want. https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#namespace 

Based on the info that's in the docs - is there something specific you're looking for that's different from what's explained there?

**Comment by zbecknell** [comment]
Thanks for the response, @rynowak, I'm glad to see that already is supposed to apply to components.  It seems I've encountered a bug where the namespace isn't being applied.  I've created a repro repo here:

https://github.com/zbecknell/ImportNamespaceExample

This project builds because I'm importing the default namespace of `NamespaceImport.Components.Nested` in the file `TestConsumer.razor`, but it will break if I remove that using statement.  The directive in `_Imports.razor` doesn't seem to be applying.

**Comment by javiercn** [comment]
@zbecknell thanks for the repro.

@rynowak can you take a look?

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
