### ISSUE TITLE
Help building source.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#18439]
I spent a lot of time trying to build from source.
`restore.cmd` finished successfully.
Got stuck in error when trying to build from root folder:
```
Build FAILED.

C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]

C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\test\testassets\ComponentsApp.App\ComponentsApp.App.csproj]

C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\test\testassets\TestContentPackage\TestContentPackage.csproj]


C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\test\testassets\ComponentsApp.App\ComponentsApp.App.csproj]
C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\test\testassets\TestContentPackage\TestContentPackage.csproj]
C:\Users\Bart\.nuget\packages\microsoft.net.sdk.razor\5.0.0-alpha.1.20060.2\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code -2147450750. [C:\Development\Community\bartmax\aspnetcore\src\Compon
ents\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
```

going into (for example) the `Components\Authorization\src` folder and doing a `dotnet build` returns several errors about `hostpolicy.dll` like:
```
Failed to load the dll from [C:\Development\Community\bartmax\aspnetcore\.dotnet\shared\Microsoft.NETCore.App\5.0.0-alpha.1.19562.8\hostpolicy.dll], HRESULT: 0x800700C1
```

already tried:
running `eng\scripts\InstallVisualStudio.ps1`
running the clean powershell script
deleting installed packages and sdks with no luck. 
running `build.csm` inside `Components` folder (ultimately what I want is to work with Blazor)
all the above with `. .\activate.ps1`
running `eng\scripts\InstallJdk.ps1`
`build.cmd -All`
`.\build.cmd -ForceCoreMsbuild`

can't get to build the Authorization, and the other 2 projects inside testassets.

opening in VS `startvs.cmd` gives me the following output at load:
![image](https://user-images.githubusercontent.com/3386797/72661866-460c4480-39be-11ea-8dc0-e6cdb9de9970.png)

running tests:
![image](https://user-images.githubusercontent.com/3386797/72661889-94b9de80-39be-11ea-9234-9513c534e7b2.png)

Any guidance is appreciated

**Comment by javiercn** [comment]
@Bartmax thanks for contacting us.

What version of visual studio are you using?

@dotnet/aspnet-build will know better. Can you assist here?

**Comment by Bartmax** [comment]
All those tests were made with Visual Studio 2019 16.5.0 Preview 1.0 Community.

![image](https://user-images.githubusercontent.com/3386797/72728430-1864fe00-3b6c-11ea-8c2d-0a06da3f7f3f.png)


Microsoft Visual Studio Community 2019 Preview
Version 16.5.0 Preview 1.0
VisualStudio.16.Preview/16.5.0-pre.1.0+29521.150
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA433
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.126.18061
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.126.18061
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.126.18061
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.126.18061
Azure Functions and Web Jobs Tools

BuildStartProject Extension   1.0
Build only startup project and dependent ones.

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.5.0-beta1-19571-01+fb3f812a3e4b7534bef784fa2df1c21d1f67864d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Image Optimizer   4.0.132
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21108.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.3+g9c91cdec24
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61911.21070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.11113.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta1-19571-01+fb3f812a3e4b7534bef784fa2df1c21d1f67864d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.5.0-beta.19556.3+c2b6d5980a7f64dd4e46448b9b4f5d96eb415aeb
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

**Comment by dougbu** [comment]
@pranavkm I believe we've seen errors loading `rzc` in the past. Are we now rolling the runtime too far forward for that `netcoreapp3.0` tool i.e. have we hit breaking changes in the runtime?

See also aspnet/AspNetCore-Internal#3201

**Comment by pranavkm** [comment]
I am unable to reproduce this error on a clean machine (as also my dev box). The error from `hostpolicy.dll], HRESULT: 0x800700C1` could be a couple of things including a mismatched .dotnet bitness (32-bit powershell + 64-bit .net for instance). All of the rzc errors are simply surfacing the same error. The project incompatiblity error you see when you open Blazor in VS is genuine though, and I've filed https://github.com/dotnet/aspnetcore/issues/18484 to fix it.
