### ISSUE TITLE
Directive attribute hovers don't work

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#18433]
When doing completions:
![image](https://user-images.githubusercontent.com/2008729/72654539-e58cf100-3944-11ea-8cbc-9afcab4d6c0c.png)

When hovering:
![image](https://user-images.githubusercontent.com/2008729/72654545-ecb3ff00-3944-11ea-89f3-e7975b672c7a.png)

**Comment by ryanbrandenburg** [comment]
When I run this locally I only get the middle result (`bind-`), so I suspect that's related to why you don't get the hover (this also suffers from the null hover thing).
