### ISSUE TITLE
Blazor set Parameter via <app>

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#18447]
is it possible to set external from HTML parameter to the "plugin" Blazor webassembly

Like Componenthelper TagHelper param-ID same with <app param-ID=

**Comment by javiercn** [comment]
@hannespreishuber thanks for contacting us.

This is not possible at the moment.

**Comment by SteveSandersonMS** [comment]
If you want, you can render arbitrary data into the DOM during the initial server-side HTML rendering, and then collect it inside your Blazor WebAssembly application by using JS interop to read from the DOM.

I think that answers the question, but please let us know if not!
