### ISSUE TITLE
dotnet run results in errors

### ISSUE THREAD

**Issue by gituser227** [dotnet/aspnetcore#18443]
### Describe the bug
dotnet run results in errors

### To Reproduce
Follow instructions at https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started
At step 3, follow instruction for blazorwasm
Accordingly at step 6, "If using a Blazor WebAssembly app, execute dotnet run from the app's project folder."

This results in errors:

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003: The specified task executable "dotnet" could not be run. System.ComponentModel.Win32Exception (2): No such file or directory [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003:    at System.Diagnostics.Process.Start() [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003:    at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

/usr/local/share/dotnet/sdk/3.1.101/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/Users/_{{username}}_/WebApplication1/WebApplication1.csproj]

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
VS Code for Mac version 1.41.1

**Comment by javiercn** [comment]
@gituser227 thanks for contacting us.

@pranavkm this seems like the compiler failing to run for some reason? Do you have any thoughts?

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/17308. This being fixed in an upcoming patch release. In the meanwhile, the workaround would be to to add the dotnet sdk's install location (in your case `/usr/local.share/dotnet/`) to your PATH.
