### ISSUE TITLE
UserManager.CheckPassword throws exception

### ISSUE THREAD

**Issue by trojanmartin** [dotnet/aspnetcore#18444]
### Describe the bug
I'm trying to use User manager, but method:

`await _userManager.CheckPasswordAsync(appUser, password);`

throws this exception:

> The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters

StackTrace: 

> at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength) 
at System.Convert.FromBase64String(String s) 
at Microsoft.AspNetCore.Identity.PasswordHasher1.VerifyHashedPassword(TUser user, String hashedPassword, String providedPassword)
     at Microsoft.AspNetCore.Identity.UserManager

It looks like that exception is thrown here: https://github.com/dotnet/aspnetcore/blob/e276c8174b8bfdeb70efceafa81c75f8badbc8db/src/Identity/Extensions.Core/src/PasswordHasher.cs#L185

But hash in database is valid Base64 string.
Hash: 

> AQAAAAEAACcQAAAAEC+6mW3Rp8RvJsXGCfNtWBhZKuI5K8fCdRKL1f7wuzPqMpmxlYE84PYcMCbXZnONsg==

### To Reproduce
Create  user using userManager and then try to check password.

### Further technical details
- ASP.NET Core version 3.1
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]      Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Enterprise 2019
Version 16.4.3

**Comment by blowdart** [comment]
And is it only for one particular user or every user?

**Comment by trojanmartin** [comment]
For every user i have created

**Comment by blowdart** [comment]
What database are you using and how are you creating your users?

**Comment by trojanmartin** [comment]
I'm using Microsoft SQL Server Developer (64-bit) and i'm creating users "same" as i'm checking password: 

`    
            var result = await _userManager.CreateAsync(appUser, password);       
`

**Comment by trojanmartin** [comment]
I tried it with older applications which is in .Net Core 2.2 and it works Ok. I used the same database with users which were created by the "new" app in .Net core 3.1.

**Comment by trojanmartin** [comment]
![image](https://user-images.githubusercontent.com/44072595/72683016-e607c200-3ad3-11ea-9d7e-28b23bb0a0eb.png)

I have created my own PasswordHasher and when  VerifyHashedPassword is called, instead of expected hashed password string there is id of user.

**Comment by trojanmartin** [comment]
I found issue in my code. Mapping of user from one entity to another was wrong.
