### ISSUE TITLE
[Blazor WASM] Serve cached assemblies from ASP.NET Core Server

### ISSUE THREAD

**Issue by michuny25** [dotnet/aspnetcore#18448]
I am running ASP.NET Core 3.1 Server which hosts API and also serves Client-Side Blazor files.
I tried to speed up the loading of the Blazor WASM assemblies in ```/_framework``` folder using CloudFlare CDN.

However, even if I create a site policy for ```mydomain.example/_framework/*``` then it's still not being cached and the status of the assemblies is ```cf-cache-status:REVALIDATED``` because the ASP.NET Core server serving Client-Side Blazor does not allow CloudFlare to cache the files in ```/_framework```. The CDN thinks there's always a newer version on the server.

My server is using extension in Startup to serve Client-Side Blazor:
```app.UseClientSideBlazorFiles<Client.Startup>();```

Is there a way how to make Blazor assemblies to be cachable? If not, can the extension have some options about caching the Blazor content which is being served and allow to cache assemblies in ```/_framework```?

**Comment by javiercn** [comment]
@michuny25 thanks for contacting us.

We'll likely handle this as part of https://github.com/dotnet/aspnetcore/issues/16956

I'm closing this issue in favor of that one.
