### ISSUE TITLE
How to add authentication and authorization to Blazor WebAssembly.

### ISSUE THREAD

**Issue by Summpot** [dotnet/aspnetcore#18441]
The document does not seem to mention how to add it, only only mentions how to use it.The scaffold is not currently available. Could it be added manually in some way?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're adding an auth-enabled Blazor WASM project template as part of https://github.com/dotnet/aspnetcore/issues/17014.
As for your specific question, you can see how that template is structured and apply the same auth-enabling gestures to your project: https://github.com/dotnet/aspnetcore/commit/e64b8a91ad1a5acea64f7d2a51ac00618ad96876
