### ISSUE TITLE
Adding blazor events (@onclick etc.) while using MarkupString

### ISSUE THREAD

**Issue by dawgen** [dotnet/aspnetcore#18459]
I was reading this issue: 
(https://github.com/dotnet/aspnetcore/issues/15746)
and I have somewhat the same problem. 

My blazor project gets an html string from the backend containing guids. Blazor then replace the guids with html elements (i.e. images) that will contain onclick-events for statistic purposes. 

A simplified example: 
From the backend, I get: 
```
<div>
[55d815f1-a4f7-4351-ae96-3ff31b1b627b]
</div>
```

using Blazor, I want my output to be (onclick-events lets us monitor user interaction): 
```
<div>
<img src="www.path.com/image.jpg" alt="A nice, clickable image" @onclick="(() => RegisterClick(ProvidedGuid.ToString()))" />
</div>
```

I tried splitting the html on the guid (simplified) and render in order: 
```
string[] boxHtmlArr = boxHtml.Split("[55d815f1-a4f7-4351-ae96-3ff31b1b627b]"); 
@((MarkupString)formatHtml(boxPart[0]));
<img src="www.path.com/image.jpg" alt="A nice, clickable image" @onclick="(() => RegisterClick(ProvidedGuid.ToString()))" />
@((MarkupString)formatHtml(boxPart[1]));
```

```
but it renders as 
<div></div><img src="www.path.com/image.jpg" alt="A nice, clickable image" @onclick="(() => RegisterClick(ProvidedGuid.ToString()))" />
```

as described in the linked issue. 

I have also looked at using Razor Templates, but they seem to only accept pure html and will not accept the "@onclick="

For the rendering, I have also tried adding every html-part to a string OuputHtml and ran `@((MarkupString)OutputHtml)`
in the end of the code. It then renders correctly. 

As I am quite stuck on my project here, any help would be greatly appreciated. 

Edit: 
If it is possible to render the image as 
`<img src="www.path.com/image.jpg" alt="A nice, clickable image" id="55d815f1-a4f7-4351-ae96-3ff31b1b627b" />`, then use a blazor function to add the onclick-event to it, that would also work great.

**Comment by javiercn** [comment]
@dawgen thanks for contacting us.

We are not sure what you are trying to accomplish, but MarkupString is meant to represent literal markup blocks and we don't have plans to change the programming model to support Blazor constructs inside a MarkupBlock.

For what you are trying to accomplish you either need to know the shape of the HTML you are processing and write a component with that markup or parse the HTML yourself and use the Blazor rendering APIs to render that markup yourself and then insert the additional elements you need.

Blazor turns the text in your components into API calls at **compile** time and we don't plan to enable doing it at runtime.
