### ISSUE TITLE
Blazor WASM Enumerable.Append() Issue 

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#18452]
I have this code:

````csharp
 var liste = (propertyInfo.GetValue(Entity) as IEnumerable<object>);
Enumerable.Append(liste, val);
````
It doesn't Add anything to my collection.

But this code does:
````csharp
 var liste = (propertyInfo.GetValue(Entity) as IEnumerable<object>).ToList();
liste.Add(val);
````
I tried Append in differents cases, it nevers worked.

Thanks.

**Comment by javiercn** [comment]
@JulienM28  thanks for contacting us.

We don't think there's anything specific to Blazor and we believe you'll get a better and faster answer if you file the issue directly in the [mono repository](https://github.com/mono/mono) repository.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use .NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com).
