### ISSUE TITLE
Should the project templates use MapDefaultControllerRoute?

### ISSUE THREAD

**Issue by serpent5** [dotnet/aspnetcore#18468]
Project templates that set up MVC usually have [this call](https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L159-L161) inside of the `UseEndpoints` callback:

```csharp
endpoints.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
```

Should this be replaced with the following?:

```csharp
endpoints.MapDefaultControllerRoute();
```

The end result is the same, but this seems like something that might have been considered before (I believe it was the same for `UseMvc` vs `UseMvcWithDefaultRoute` too).

I see that there might be a good argument for the former, in that it's set up for easier customisation, but I wonder if it this is something that gets left alone more often than it gets changed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. While this the effect will be equivalent, we will not chance the templates. The goal is to make it explicit to the customers how these are configured.

**Comment by serpent5** [comment]
Sure, I think that's what I expected.

I have to ask, though: Why even have `MapDefaultControllerRoute`, if that's the case?
