### ISSUE TITLE
AuthorizeCore in AuthorizationAttribute? 

### ISSUE THREAD

**Issue by jtlimson** [dotnet/aspnetcore#18469]
Is there a replacement for `AuthorizeCore` in `AuthorizeAttribute` in MVC 5? 

AuthorizeCore returns a boolean - where we developer can custom override a decision making code. 
lets say;
`
Do I want this user to proceed? type of conditions.
` 
or is this already depricated.

Thanks

**Comment by rynowak** [comment]
The authorization system has a number of extensibility points - we recommend using policies/requirements rather then subclassing the `AuthorizeAttribute`/`AuthorizeFilter`.

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1
