### ISSUE TITLE
I cannot pass data from background method to blazor page

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/aspnetcore#18465]
I need need to pass data from a background method that receives data by gRPC, and i need the Blazor page to be updated as soon as information arrives. Like a triggred event.

Right now i can pass the data through a singleton, wich is not good, but the scooped class cannot be accessed anywhere outside the blazor page. I can also do it with a static class, would that be better?

The other problem with this approach is that the UI doesn't get updated when the values change. Only when i navigate forth and back in the browser is when the data passed is displayed. Wich is not good also.

Is there a way to access the injected and instantiated class of a page and throw in there the new values and get the UI updated?

I tried with an event  Action in the singleton, triggered by the assessor set, but i can't get to bound a trigger to that event on the singleton to the Blazor page to get the UI updated.

How can i do this, anyone knows??

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for contacting us.

We're not sure what you are trying to accomplish here, but here are some options.

We're not sure if you are trying to share data that is specific to a given user or global. If the data is global then you can use a singleton and inject that in your component, add an event to your class and subscribe on the component to update the UI.

If the data is not global, create a subscription before rendering the page from the server for the first time and pass in a subscription ID to your server-side application as a parameter.

Then on your application, use that id to register a callback with the singleton for the data that is specific to that user.

Hope this helps.

**Comment by dannygrieve** [comment]
What?

**Comment by Ricardoaraujo00** [comment]
Hi @javiercn 
In this case the data is global. Please understand that i am a rookie at this and it's not very easy for my to understand some things.

> We're not sure if you are trying to share data that is specific to a given user or global. If the data is global then you can use a singleton and inject that in your component, add an event to your class and subscribe on the component to update the UI.
I was trying to do just that, but i cannot inject the thread safe singleton in the ConfigureServices on the startup.cs. The compiler throws an error that it has not a valid constructor. So i instantiate it in the Program.Main(). 
The sigleton:
```
public class ThreadSafeSingletonString
    {
        private static ThreadSafeSingletonString _instance;
        private static readonly object _padlock = new object();
        private ThreadSafeSingletonString() 
        {
  
        }

        public static ThreadSafeSingletonString Instance
        {
            get
            {
                if (_instance == null)
                {
                    lock(_padlock)
                    {
                        if (_instance == null)
                        {
                            _instance = new ThreadSafeSingletonString();
                            _instance.order="";
                        }
                    }
                    
                }
                return _instance;
            }
            set
            {
                _instance.order = value.order;
                _instance.NotifyDataChanged();
            }
        }
        public string order { get; set; }

        public event Action OnChange;

        private void NotifyDataChanged() => OnChange?.Invoke();
    }
}
```
The instantiation:
public static void Main(string[] args)
    ```
    {
            var tss = ThreadSafeSingletonString.Instance;
            tss.order = "nome";
            Console.WriteLine(tss.order);
            CreateHostBuilder(args).Build().Run();
        }
```
In the Greeter service i give the sigleton new data with this two lines:
```
ThreadSafeSingletonString tss =  ThreadSafeSingletonString.Instance;
            tss.order = clientName+". A nova fila passada por um sigleton é " + queueNames[0] +" é daqui";
```

```
The Blazor page:

```
@page "/greeter"
@using BlazorApp1.Data
@inject GrpcService1.GreeterService GreeterService1
@inject AppData appdata1


<h1>Grpc Connection</h1>

<input type="text" @bind="@Name" />
<button @onclick="@SayHello">SayHello</button>
<p>Fila recebida: @Greetmsg</p>
<p>Thread safe sigleton: @threadSafeSingleton.order</p>

@code {
    string Name;
    string Greetmsg;
    public string fromrefresh;
    ThreadSafeSingletonString threadSafeSingleton = ThreadSafeSingletonString.Instance;

    protected override void OnInitialized()
    {
        threadSafeSingleton.OnChange += updateOrder();
    }

    public System.Action updateOrder()
    {
        this.fromrefresh = threadSafeSingleton.order + " que vem.";
        Console.WriteLine("Passou pelo UpdateName");
        this.StateHasChanged();
        return StateHasChanged;
    }

    async Task SayHello()
    {
        this.Greetmsg = await this.GreeterService1.SayHello(this.Name);
    }

}
```
The **threadSafeSingleton.OnChange += updateOrder();** doesn't bind to the singleton event.
