### ISSUE TITLE
Proposal: Add a generic RedirectToPage method

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#18462]
Take this example of the RedirectToPage method:
```C#
return RedirectToPage("./LoginWith2fa", new {
    ReturnUrl = returnUrl,
    RememberMe = Input.RememberMe
});
```
There are two problems in this code:
1. Potential typo errors in the page path and name.
2. No intellisense aid for route params. 

To solve this, I suggest adding a new overload for the RedirectToPage:
` RedirectToPage<T> (params object[] o)`

so, we can rewrite tha obove example as: 
```C#
RedirectToPage<LoginWith2faModel>( returnUrl, Input.RememberMe)
```

This new overload should call one of the old overloads, so it will have no impact at runtime. It will only affect coding time, making coding easier: 

1.	Each page-model class is unique in its namespace, so there will be no confusion with similar names in areas or other different directories.
2.	No way for typo errors in page class name, with intellisense support.
3.	Intellisence can analyze the defiend page routes and route params injected in the OnGet method to show a helpful param list (or lists) after writing the `(`, instead. So, we will not see the `params object[] o` but will see the route params names and types.

I think it can be done, and will be of a great help.

**Comment by javiercn** [comment]
@VBAndCs thanks for contacting us.

That's not possible/useful due to the way Razor pages are compiled, as it would create a circular dependency between the application assembly and the Views assembly.

If this is a problem for you, you can write your own analyzer to check the parameters to the RedirectToPage method calls and check for typos there.

**Comment by VBAndCs** [comment]
@javiercn 
Thanks for fast response. As I said, this is only a Roslyn work at design time. All the information needed exist in the pagd.shtml and page.cshtml.cs files, and Intellisense can reach them. At compilation, the generic RedirectToPage method can be lowered to the suitable non-generic overload, so, everything will work as usual.
If you agreed with the purpose, you will find a suitable solution to such technicalities.

**Comment by javiercn** [comment]
@VBAndCs Razor and C# don't interact that way.

Razor transpiles to C# classes and doesn't have any insight into the C# you have in your application. 

The views are generated into an additional views assembly that has an `<app-name>.Views.dll` and that references the application assembly, so for a view to be referenceable by the app, the app would also need to reference the views assembly, which would create a circular dependency, and that's not possible in .NET.

If this is a recurring problem for you, you can write an analyzer and share it with the community, but we don't plan to tackle this ourselves as it has a performance impact on the development experience,  we don't have enough data that indicates that this is a common enough, and we would likely not turn it on by default, at which points the benefits are greatly diminished.

I understand that this might not be the answer you are expecting, but we as a team can't handle all requests and this is something that doesn't need to be part of the core framework.

Hope that helps.

**Comment by VBAndCs** [comment]
OK. I just share some thoughts.
There is another alternative (not expecting you to implement):
Generate a hidden static class with the name `Redirect` and generate a static method for each page in the project, such as `ToIndexPage` with params similar to those of the OnGet/OnGetAsync method.
I will write such a class manually in my projects to make my code consistence, but it will be easier if it is auto-generated.
Thanks anyway.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @VBAndCs. This is not something we plan to do per @javiercn 's response.
