### ISSUE TITLE
Route attributes for GUID handled differently

### ISSUE THREAD

**Issue by jason-simard** [dotnet/aspnetcore#18464]
### Describe the bug
Using a GUID as a route attribute produces a 404 error.  Using a similar route attribute for an int works as expected.

### How To Reproduce

```
    app.UseEndpoints(endpoints => {
        endpoints.MapControllers();
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Dashboard}/{id?}");
        endpoints.MapRazorPages();
    });
```

```
    [HttpGet]
    [Route("{employeeNum:int}")]
    [Authorize]
    public async Task<IActionResult> Edit(int employeeNum) {
        return View(model);
    }
```
/Employee/Edit/1717 - works as expected with the above route

```
    [HttpGet]
    [Route("{roleId:guid}")]
    [Authorize]
    public async Task<IActionResult> Edit(Guid roleId) {
        return View(model);
    }
```
/Role/Edit/7b65e7dc-7a29-4ff6-a236-394cfd7619aa - this route returns a 404 error.

```
    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Edit(Guid id) {
        return View(model);
    }
```
If I change the parameter name to id, the route behaves as expected.  No other changes are made.

/Role/Edit/7b65e7dc-7a29-4ff6-a236-394cfd7619aa - this route now behaves as expected.

Adding the following endpoint still results in a 404 error,

```
                endpoints.MapControllerRoute(
                    name: "guidTest",
                    pattern: "{controller=Role}/{action=Index}/{roleId:guid}");
```

Is this by design?  Or a missing configuration issue to handle Guid values as action parameters?  Not a major issue just inconsistent with other type parameters.

Could be related to [#13811](https://github.com/dotnet/aspnetcore/issues/13811)

### Further technical details
ASP.NET Core 3.1.1
VS 2019 16.4.3

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
