### ISSUE TITLE
Grpc and websocket can't be used at the same time

### ISSUE THREAD

**Issue by sunliusi** [dotnet/aspnetcore#18476]
grpc use http2, websocket use http1. It's impossible to use both in same port at the same time.

It can be done by ConfigureKestrel setting different ports, how to user both in same port at the same time.

**Comment by sunliusi** [comment]
Grpc is used in internal micro service, it's not necessity to config TLS certificate. 

Whether or not it can be done by setting http1 or http2 in the endpoints.

**Comment by Tratcher** [comment]
HTTP1 and HTTP2 can only share the same port if TLS is used (via ALPN).

**Comment by sunliusi** [comment]
> HTTP1 and HTTP2 can only share the same port if TLS is used (via ALPN).

It's hard to manage TLS Certificates in internal services, and it's not necessity to config TLS certificate in internal services.

An attempt to set up the  protocol did not take effect:

app.Use(async (context, next) =>
            {
                if (!string.IsNullOrWhiteSpace(context.Request.ContentType) &&
                    context.Request.ContentType.ToLower().Contains("application/grpc"))
                {
                    context.Request.Protocol = "HTTP/2";
                    //context.Request.Headers["Connection"] = "Upgrade";
                    //context.Request.Headers["Upgrade"] = "h2c";

                    //context.Response.StatusCode = 101;
                    //context.Response.Headers["Connection"] = "Upgrade";
                    //context.Response.Headers["Upgrade"] = "h2c";
                    //return;
                }

                await next.Invoke();
            });

Any other solutions to share ports?

**Comment by Tratcher** [comment]
It takes more than setting the protocol on the server. Look up the grpc-web work that is happening, that provides http1 compat.

**Comment by sunliusi** [comment]
Currently  we use grpc for internal micro service. If grpc-web don't use http2, it's not a good choice for performance.

webBuilder.ConfigureKestrel((context, optins) =>
                {
                    var protocol = context.Configuration.Get<MultiProtocolOption>();

                    optins.ListenAnyIP(protocol.Http, listenOption =>
                     {
                         listenOption.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2;
                     });

                    optins.ListenAnyIP(protocol.Grpc, listenOption =>
                    {
                        listenOption.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2;
                    });
                }).UseStartup<Startup>();

I use two port for http1 and http2, things get complicated.

The best solution is  use same port for grpc and websocket

**Comment by Tratcher** [comment]
> If grpc-web don't use http2, it's not a good choice for performance.

Try it before you make that judgement.

> The best solution is use same port for grpc and websocket

That requires TLS.
