### ISSUE TITLE
AddAuthorizationCore should call AddOptions

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#18471]
### Describe the bug

`AddAuthorizationCore` depends on options being registered in the service collection. In server-side ASP.NET Core, this is fine because hosting includes it. In Blazor WASM we're now forced to register options (an extra dependency) in the host, even though Blazor itself doesn't use options.

**Comment by javiercn** [comment]
This will have to happen in .NET 5.0 timeframe or we could consider adding it in a patch, as it should be harmless.

**Comment by rynowak** [comment]
Fixing this in 5.0 sounds good. I don't think this meets the bar for a patch, and I'm not sure we want to couple Blazor WASM to a specific patch version.
