### ISSUE TITLE
Custom router in Razor pages

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#18475]
In MVC I have a custom router where I look up what controller and action the request should end up in. Is it possible to use a custom router in Razor pages?

This is basically how I do it in MVC.

```c#
    public class DefaultRouter : IRouter
    {
        public DefaultRouter() {
        }
        public VirtualPathData GetVirtualPath(VirtualPathContext context)
        {
            throw new System.NotImplementedException();
        }

        public Task RouteAsync(RouteContext context)
        {
            context.RouteData.Values["Controller"] = "Hello";
            context.RouteData.Values["Action"] = "World";
            return Task.CompletedTask;
        }
    }
```

Is it possible to set some route value to send the request to a specific `PageModel` in Razor pages?

**Comment by javiercn** [comment]
@marcuslindblom thanks for contacting us.

@rynowak or @pranavkm can you help here?

It would help if you describe in more detail what you are trying to accomplish so that we might be able to provide an alternative option in case it is not possible.

**Comment by marcuslindblom** [comment]
@javiercn Basically I have a `IDictionary<string, TrieNode>` where the key is the a friendly url and the `TrieNode` has information about the controller and `Id` of the entity to load from the database. The urls are hierarchical and does not have the name of the controller because that information is in the `TrieNode`. A url is constructed by the `h1` on the page and can look something like this. `/always-interactive-lightning-fast-design`. In my router I get the `TrieNode` that matches the path, sets the `Controller` and `Action` in the route data. Now, I would like to do the same thing for Razor pages and route the request to the correct `Page` based on the information in my dictionary.

**Comment by javiercn** [comment]
@marcuslindblom you could try setting the "page" in the `RouteData.Values` to the page path, like "/Index.cshtml"

I believe that should work, otherwise I'm not sure what other options exists, but @rynowak will know.

**Comment by marcuslindblom** [comment]
@javiercn @rynowak I tried something like this but it does not execute my router at all.
```c#
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Test2
{
  public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting()
                .UseRouter(options => new DefaultRouter(options.DefaultHandler));

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }
    }
    public class DefaultRouter : IRouter
    {
        private readonly IRouter _next;
        public DefaultRouter(IRouter next) {
            _next = next;
        }
        public VirtualPathData GetVirtualPath(VirtualPathContext context)
        {
            throw new System.NotImplementedException();
        }

        public async Task RouteAsync(RouteContext context)
        {
            RouteData routeData = new RouteData();
            routeData.Values["page"] = "Index";
            context.RouteData = routeData;
            await _next.RouteAsync(context);
        }
    }
}
```

**Comment by marcuslindblom** [comment]
I forgot to say that I'm developing a CMS so perhaps you can understand more what I'm trying to achieve. I think it's basically a wildcard route where I look for my "page" in the database, route it correctly if it exists on the given path, or else I want to forward the request to the next registered router or endpoint.

**Comment by mrpmorris** [comment]
@marcuslindblom This is currently not possible because the router works by finding `@page '/Whatever'` attributes on components, so it cannot be data driven.

Shaun Walker wrote a blog on how to create a custom router for Blazor that you might find useful - https://www.oqtane.org/Resources/Blog/PostId/521/custom-routing-in-blazor

**Comment by javiercn** [comment]
@mrpmorris this is not a Blazor question but an ASP.NET Core routing question. That advice doesn't apply here.

**Comment by mrpmorris** [comment]
> 
> 
> @mrpmorris this is not a Blazor question but an ASP.NET Core routing question. That advice doesn't apply here.

@javiercn I thought I had the area-blazor filter on, sorry. Deleted :)

**Comment by mkArtakMSFT** [comment]
@rynowak can you please look into this one? Thanks!
