### ISSUE TITLE
Where are directives processed? [Blazor] [Question]

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#18474]
I see some Blazor directives declared here
https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.CodeAnalysis.Razor/RefTagHelperDescriptorProvider.cs

Where can I view the source that processes these directives into the target source code?

Thanks

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

@NTaylorMullen or @rynowak can you give an answer here?

**Comment by RemiBou** [comment]
From my work in this blog post https://remibou.github.io/Blazor-how-it-works-part-1/, the directives are evaluated in this project https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/ for instance https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/FunctionsDirective.cs

Maybe some maintainers can give you more informations

**Comment by mrpmorris** [comment]
> Maybe some maintainers can give you more informations

Hi Remi

From what I can see, those are only where the directives are defined. There is no code in there that performs the actual transpilation into C#. That is what I am looking for.

**Comment by mrpmorris** [comment]
Thanks @RemiBou, that helped me to find the source file I needed
https://github.com/dotnet/aspnetcore-tooling/blob/c38adf926ee98b66bc04edf4be50629f0b04b712/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentReferenceCaptureLoweringPass.cs

**Comment by RemiBou** [comment]
You can start here 

https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Tools/GenerateCommand.cs line 304 then the project engine is defined here

https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectEngine.cs

then here you have the loop through all the phases

https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorEngine.cs

I think the initialization of all the phases is here https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorProjectEngine.cs line 117

The code generation happens here

https://github.com/dotnet/aspnetcore-tooling/blob/3fe99e9d7fede30fd8d2b3f94d488ba63aadcb28/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/FunctionsDirectivePass.cs

The string concatenation is done by this class 

https://github.com/dotnet/aspnetcore-tooling/blob/17a95db34fdfb3afa04ac42a37b68183f667f710/src/Razor/src/Microsoft.AspNetCore.Razor.Language/CodeGeneration/CodeWriter.cs
