### ISSUE TITLE
HttpContext only holding default values in dotnet core 2.1

### ISSUE THREAD

**Issue by agchaudhury** [dotnet/aspnetcore#18472]
I have recently upgraded an application created in dotnet core 1.0 to 2.1. And ever since HttpContext, the application was using to retrieve information, is only having default values and the following lines of code are failing:

`if (!HttpContext.Items.Keys.Contains(Utility.APIGATEWAY_REQUEST))
            {
                //log error
            }`

`var apiGatewayRequest = HttpContext.Items[Utility.APIGATEWAY_REQUEST] as APIGatewayProxyRequest;`

All the HttpContext is fetching is:
![HttpContext](https://user-images.githubusercontent.com/7009918/72783786-58ff6d00-3c7b-11ea-857a-a1a23916437a.JPG)

The UI of the same is made in Angular which makes service calls to AWS Lambdas (made using dotnet core) for all the requirements. User data is stored in AWS Cognito and every time a service call is made it first gets verified by fetching data from Cognito. This part stopped working after the framework upgrade.

Custom api gateway authorizer is used for Cognito and also HttpContext is used inside a controller.

I am not sure if this scenario using Angular, DotNet Core 2.1, AWS Lambda, AWS Cognito, Custom api gateway authorizer was ever tested but I am stuck.

Please provide some inputs or some workaround.

**Comment by anurse** [comment]
@agchaudhury can you post a runnable sample project that reproduces the problem? `HttpContext.Items` is a **per-request collection**. Values stored in it for one request are not available in another.

What is the value you're trying to retrieve?

**Comment by agchaudhury** [comment]
In the newer version of DotNet Core the value of the HttpContext key got changed from "APIGatewayRequest" to "LambdaRequestObject" causing all the pain. And the code was using the value directly from a constant declared inside the project and was not using the constant "AbstractAspNetCoreFunction.LAMBDA_REQUEST_OBJECT" provided by the framework. Kindly close the issue.
