### ISSUE TITLE
routing is not working when uploaded in azure

### ISSUE THREAD

**Issue by ileve** [dotnet/aspnetcore#18477]
I use an anchor tag helper to generate a link with `asp-route-id`.
When `asp-route-id` contains forward slash then routing is working in local host, but not in azure.

Example:  `asp-route-id="MERINO DE LUX / 50"`
The tag helper generates the url:  
`http://{domain name or localhost}/Products/FromCategory/MERINO%20DE%20LUXE%20%2F%2050`

With experiment i figured out that forward slash causes the problem but only when it is uploaded on Azure.

I use asp.net core 3.0 with endpoint routing

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ileve.
@shirhatti do you know why Azure may work this way? Is this expected?

**Comment by shirhatti** [comment]
What are you observing? What is the generated URL as opposed to what you expect?

There are nuanced differences in how Http.Sys/IIS (Azure App Service infrastructure) handle escaped URIs and is possibly manifesting itself here.

cc @Tratcher

**Comment by Tratcher** [comment]
%2F handling is notoriously inconsistent. Avoid using it whenever possible.

Http.Sys un-escapes it to prevent spoofing. ASP.NET's HttpSysServer and IIS in-proc server go out of their way to get the original url format back and avoid un-escaping %2F.  In Azure you're going through several proxies that are likely to break this and there's not much you can do about it there.

@rynowak as a workaround could you define catch-all routes? Something like "/Products/Pages/*"?

**Comment by ileve** [comment]
`asp-route-id` represents a category name which is stored to database by the administrator via a user form. So the user has the flexibility to type whatever he wants. I understand that Azure has this behavior for protection against `XSS` injection. But I thought that sanitization of forward slash was just enough.

Anyway I guess I should replace the forward slash symbol, whenever it is contained in a category name, by another symbol or even completely remove it from the user input. Probably also the angle bracket symbols `'<'` and `'>'` ?
