### ISSUE TITLE
EnumTypeModelBinder use all values for flags

### ISSUE THREAD

**Issue by krispenner** [dotnet/aspnetcore#18498]
### Is your feature request related to a problem? Please describe.
I would like any query string parameter that is of type enum with flags to combine all query string parameters of its name, similar to how an array is bound from the query string.

### Example

```cs
[Flags]
public enum Colors
{
    None = 0,
    Red = 1,
    Blue = 2,
    Green = 4
}
```

### Currently this works
https://api.example.com/controller/action?myColor=Red,Green

### Currently this does not work and I would like it to work
https://api.example.com/controller/action?myColor=Red&myColor=Green

### Describe the solution you'd like
I think the below code should fix this, it's quite simple, I'm happy to submit a PR myself if this is agreed to be used.

Modify the read of `valueProviderResult.FirstValue` at [SimpleTypeModelBinder.BindModelAsync line 65](https://github.com/dotnet/aspnetcore/blob/bc60e9576f88c1ee16dc99f18ca08278c254802d/src/Mvc/Mvc.Core/src/ModelBinding/Binders/SimpleTypeModelBinder.cs#L65) to come from a protected virtual method instead so subtypes can override how the string value is decided on.

```cs
protected virtual string GetStringValue(ModelBindingContext bindingContext, ValueProviderResult valueProviderResult)
{
    return valueProviderResult.FirstValue;
}
```

Then in [EnumTypeModelBinder](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/EnumTypeModelBinder.cs) override this method and return all values joined by a comma for enums with Flags attribute defined.

```cs
protected override string GetStringValue(ModelBindingContext bindingContext, ValueProviderResult valueProviderResult)
{
    if (bindingContext.ModelMetadata.IsFlagsEnum)
    {
        return valueProviderResult.Values;
    }

    return base.GetStringValue(bindingContext, valueProviderResult);
}
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
