### ISSUE TITLE
Consider adding an IEndpointConventionBuilder.RequireAuthorization overload that accepts an AuthorizationPolicy

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18497]
Endpoint routing has a way to configure auth using `RequireAuthorization`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.authorizationendpointconventionbuilderextensions?view=aspnetcore-3.1. The overloads allow specifying names of policies, but no way of specifying a policy itself. 

Compare this to `AuthorizeFilter` which has an overload that allows specifying a policy: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.authorization.authorizefilter.-ctor?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_Authorization_AuthorizeFilter__ctor_Microsoft_AspNetCore_Authorization_AuthorizationPolicy_

This overload allows for fairly easy to follow auth setup: https://github.com/dotnet/aspnetcore/blob/bc60e9576f88c1ee16dc99f18ca08278c254802d/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L112-L118

**Comment by pranavkm** [comment]
/cc @blowdart \ @HaoK 

Right now, doing the equivalent of the code snippet requires setting up a policy during `ConfigureServices` and looking it up by name as part of `UseEndpoints`. Having this would make the transition from filter to endpoint routing much cleaner.

**Comment by rynowak** [comment]
@blowdart @HaoK - can you think of a reason we didn't do this?

**Comment by captainsafia** [comment]
Closing as resolved via https://github.com/dotnet/aspnetcore/pull/41153.
