### ISSUE TITLE
Avoid using AuthorizeFilter in project templates

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18493]
Using the auth filter with endpoint routing isn't particularly optimal and we shouldn't be recommending it to our users.

**Comment by mikes-gh** [comment]
Close this if you think this issue is the same.
https://github.com/dotnet/aspnetcore/issues/18412

**Comment by pranavkm** [comment]
The other issue has more details. We'll use it to track fixing this.
