### ISSUE TITLE
Aggregated IIS events AspNetCoreModuleV2 very high Self Time

### ISSUE THREAD

**Issue by olivierebaachi** [dotnet/aspnetcore#18507]
Hi,
We have a high self time in the first API call then after 1 or 2 hours.
Is it Possible to have this only on the first start of the Application?

This is the code level of my call:

                                                 Elapsed Self time Duration
Web requestIIS                           0 ms 8 µs 20.6 s
aggregated IIS events
General                                       +6 µs 59.6 ms 59.6 ms
aggregated IIS events
FailedRequestsTracingModule +58.8 ms 44 µs 44 µs
aggregated IIS events
RequestMonitorModule           +58.8 ms 5 µs 5 µs
aggregated IIS events
IsapiFilterModule                     +58.8 ms 50 ms 50 ms
aggregated IIS events
RewriteModule                        +109 ms 59 µs 59 µs
aggregated IIS events
HttpCacheModule                    +110 ms 32 µs 32 µs
aggregated IIS events
RequestFilteringModule          +110 ms 63 µs 63 µs
aggregated IIS events
ConfigurationValidationModule +110 ms 192 µs 192 µs
aggregated IIS events
WindowsAuthenticationModule+110 ms 28 µs 28 µs
aggregated IIS events
AnonymousAuthenticationModule+110 ms 1 ms 1 ms
aggregated IIS events
HttpRedirectionModule +186 ms 44 µs 44 µs
aggregated IIS events
AspNetCoreModuleV2 +186 ms 41 µs 41 µs
aggregated IIS events
AspNetCoreModuleV2 +186 ms 17.9 s 17.9 s
aggregated IIS events
General +18.1 s 18 µs 18 µs
aggregated IIS events
AspNetCoreModuleV2 +18.1 s 439 ms 2.56 s
       Synchronous invocation
                   /v1/h-collaborateurs
                      Mainta.Echange.Api.Inter+18.5 s 185 µs 2.12 s
aggregated IIS events
General +20.6 s 185 µs 185 µs
aggregated IIS events
DynamicCompressionModule
+20.6 s
179 µs
179 µs
aggregated IIS events
RewriteModule
+20.6 s
11 µs
11 µs
aggregated IIS events
HttpCacheModule
+20.6 s
14 µs
14 µs
aggregated IIS events
CustomLoggingModule
+20.6 s
20 µs
20 µs
aggregated IIS events
WindowsAuthenticationModule
+20.6 s

Regards

**Comment by anurse** [comment]
Can you clarify what you mean here by "very high self time"? What are you using to measure this? The time spent in `AspNetCoreModuleV2` includes **the entire** execution of your .NET Core code, so if your .NET Core code to process a request takes a while, this would be expected.

**Comment by olivierebaachi** [comment]
Thanks for your answer,
I'm using Dynatrace to measure.

the first API call takes 14 to 20 sec and AspNetCoreModuleV2 is call 3 times during the execution
The second  API call takes less than 1 sec and AspNetCoreModuleV2 is call 2 times.
If I wait 20 minutes before sending a new API call, the call takes 14 to 20 sec and AspNetCoreModuleV2 is call 3 times during the execution.

Question:
Is it possible to keep the compilation .NET Core code in cache for 24h? 
If not,  how  is-it possible to have the first call effect only one time?

Regards,

**Comment by olivierebaachi** [comment]
Capture of the first call: AspNetCoreModuleV2 is call 3 time self time 11 sec
![Capture_a](https://user-images.githubusercontent.com/47693044/72963664-1e4f1f00-3db8-11ea-8993-53f71ce49a6d.PNG)
Capture of the second call : AspNetCoreModuleV2 is call 2 times
![Capture_b](https://user-images.githubusercontent.com/47693044/72963691-2dce6800-3db8-11ea-8d0e-a852f081272d.PNG)

**Comment by anurse** [comment]
> Is it possible to keep the compilation .NET Core code in cache for 24h?

There shouldn't be any compilation in play unless you've enabled runtime compilation for Razor pages. This is likely just start-up time. Can you provide a *runnable* sample application that reproduces this problem? We'd need to know exactly what you are running at start-up in order to investigate in more detail.

> If I wait 20 minutes before sending a new API call, the call takes 14 to 20 sec and AspNetCoreModuleV2 is call 3 times during the execution.

This is the IIS idle worker shutdown. If no requests are received within 20 mins (by default), IIS will shut the process down. On the next request it will restart it. That's why it takes the original 15-20 seconds if you wait that long between requests. You can configure that in the IIS App Pool settings.

**Comment by olivierebaachi** [comment]
Thanks for your help,
We put the timeout to idle worker shutdown to 60 minutes.
We decide to play first request for all the API when the server restart.
So that application calling will not face the 20 sec of the first request.
Regards

**Comment by anurse** [comment]
> We decide to play first request for all the API when the server restart.

This is a common pattern that people use to "prepare" the server and do all the first-request logic before any real requests are processed. Sounds like a good plan.

Closing this issue as there appears to be no further action required from the team.
