### ISSUE TITLE
UseAngularCliServer() leads to permission error when running Visual Studio as administrator

### ISSUE THREAD

**Issue by PooSham** [dotnet/aspnetcore#18501]
### Describe the bug
When running Visual Studio 2019 as administrator (which is required for Service Fabric to work), I can't use `spa.UseAngularCliServer(npmScript: "start")` from Microsoft.AspNetCore.SpaServices.Extensions. It leads to an error when accessing the web page, which states the following:

> An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: Error: EPERM: operation not permitted, mkdir 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm'

After that there are a lot of other errors related to npm, which I assume comes from the fact that npm doesn't have the permission to create the directory. 

This seems to be the same issue as [this ](https://github.com/dotnet/aspnetcore/issues/7949#issue-414604145), but I'm using .NET Core 3.1 with the npm package Microsoft.AspNetCore.SpaServices.Extensions version 3.1.1, so it's still not solved and should be reopened. 

### To Reproduce

1. Start VS2019 as Administrator
2. Create a (Service Fabric Stateless) ASP.NET Core application (I don't think this is related to service fabric)
3. In the `Configure(IApplicationBuilder app...)` method inside `Startup.cs`, add the following code:
```C#
app.UseSpa(spa =>
{
    spa.Options.SourcePath = "ClientApp";

    if (env.IsDevelopment())
    {
        spa.UseAngularCliServer(npmScript: "start");
    }
});
```
3. Debug project in development mode
4. Open page in web browser -> Error

### Further technical details
- ASP.NET Core 3.1.0
- Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101     
 Commit:    b377529961  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18362
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- Visual Studio 2019 on Windows 10

**Comment by PooSham** [comment]
I assume Visual Studio gets the administrator's environment variables, whose `$env:AppData` is `C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\`, but the node process is only run as a normal user, so it doesn't have the permission to create the directory.

**Comment by SteveSandersonMS** [comment]
It sounds like there's an incompatibility between the requirements of Angular CLI (which needs to be able to write files to disk in dev mode) and Service Fabric (which needs to be running as a different user that might not have permission to write to those locations).

My suggestion for a workaround is that instead of using `UseAngularCliServer` to launch the Angular CLI server from your app process, you instead launch the Angular CLI server manually from your own user account and connect to it via `UseProxyToSpaDevelopmentServer`. Docs about this are at https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio#run-ng-serve-independently

**Comment by PooSham** [comment]
> It sounds like there's an incompatibility between the requirements of Angular CLI (which needs to be able to write files to disk in dev mode) and Service Fabric (which needs to be running as a different user that might not have permission to write to those locations).

Too bad! So this will probably never get fixed (unless either Angular CLI or Service Fabric change their requirements)?

> My suggestion for a workaround is that instead of using UseAngularCliServer to launch the Angular CLI server from your app process, you instead launch the Angular CLI server manually from your own user account and connect to it via UseProxyToSpaDevelopmentServer. Docs about this are at https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio#run-ng-serve-independently

That's what I'm doing right now. It works, but it would be neat to have it as a part of the deployment process. 

Anyways, thanks!
