### ISSUE TITLE
Azure App Service: CurrentCulture changed after establishing SignalR connection in Blazor server-side

### ISSUE THREAD

**Issue by sven5** [dotnet/aspnetcore#18508]
### Describe the bug
We like to have german default culture ("de") setting in our Blazor app deployed to Azure.
After login with Azure AD B2C the applcation's CurrentCulture is set to en-us. 
Currently, this issue does not occur in local dev environment but only when deployed to Azure.

Edit:
I've found out that we can use custom policies to change/add claims. There are claims setting culture specific information. However, I assume that this shouldn't be necessary to have the correct culture in the app. 

### To Reproduce

1. Create new Blazor server-side web app.
2. Add AzureADB2C 
```
            services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
                .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));
```
3. Add Azure SignalR service (**edit: this is optional**)
```
 services.AddSignalR().AddAzureSignalR(options =>
                {
                    options.ServerStickyMode =
                        Microsoft.Azure.SignalR.ServerStickyMode.Required;
                });
```
4. Add custom `RequestLocalizationOptions`
```
services.Configure<RequestLocalizationOptions>(options => {
                var supportedCultures = new[] { "de", "en" };
                options.DefaultRequestCulture = new RequestCulture("de-DE");
                options.AddSupportedCultures(supportedCultures);
                options.AddSupportedUICultures(supportedCultures);
            });
```
5. Add `UseRequestLocalization`
`app.UseRequestLocalization();`

6. Add following code to a razor component (e.g. `Index.razor`) to display the value of CurrentCulture:
`@System.Globalization.CultureInfo.CurrentCulture.EnglishName`

### Further technical details
- ASP.NET Core version 3.1.1
```
Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.800 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- VS 2019 Version 16.5.0 Preview 1.0

**Comment by mkArtakMSFT** [comment]
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
I'm failing to see how the auth piece can be related to this. It doesn't do anything with the culture.

The culture you get in Blazor is the one that your user have when the app hits the signalr endpoint during the initial connection.

@rynowak might know more.

**Comment by sven5** [comment]
I've made some investigations and initially, when the website loads the correct culture is selected. I'm using Blazor with server prerendering. After the connection to Azure SignalR service has been established the culture changes to en-US. 
It seems it has nothing to do with Azure AD B2C. It was a mistake from my side.

**Comment by javiercn** [comment]
@sven5 this likely has to do with the culture that's being used when you connect through the SignalR service.

@anurse do we flow the current-culture somehow through the SignalR service? I imagine this is an issue that can happen/reproduce without Blazor being involved.

**Comment by anurse** [comment]
I don't know that it is flowed at all, but it would be the Azure SignalR SDK that does it if anything does. I'd suggest asking/requesting this on http://github.com/azure/azure-signalr.
