### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure after adding httpsredirect

### ISSUE THREAD

**Issue by arun1998** [dotnet/aspnetcore#18505]
After adding 
services.AddMvc(options =>
               {
                    options.Filters.Add(new RequireHttpsAttribute());
                })
in the ConfigureServices method and 
 var options = new RewriteOptions().AddRedirectToHttps(StatusCodes.Status301MovedPermanently);
                app.UseRewriter(options);
in the configure method I am receiving the HTTP Error 500.30 - ANCM In-Process Start Failure

**Comment by anurse** [comment]
The 500.30 error indicates a failure launching your app (such as an exception in `Startup.cs`). Can you check the Windows Event Log (or "Application Events" in Azure App Service)? The exception details should be there (since they are hidden from the error page in Production environments for security reasons).

**Comment by arun1998** [comment]
Hi Andrew, the log has this message - Application "application name" with physical root 'application path' failed to load clr and managed application. CLR worker thread exited prematurely. This happens only when I add the HTTPS redirect code above. Is there another way to do HTTPS redirect?

**Comment by anurse** [comment]
> This happens only when I add the HTTPS redirect code above. Is there another way to do HTTPS redirect?

I doubt this is directly related to the impact. You shouldn't have to remove that functionality to fix this issue, let's try to avoid that :).

> Hi Andrew, the log has this message - Application "application name" with physical root 'application path' failed to load clr and managed application. CLR worker thread exited prematurely.

Is there no other information in the log? Usually the actual exception that crashed the process will be there. Can you try the full troubleshooting steps from our docs on [Troubleshooting with IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#troubleshoot-on-iis)?

**Comment by arun1998** [comment]
Hi Andrew, I updated the config file to write to the logs folder. After running the app from the command prompt, this is the error in the windows application logs - 

Application [applicationname] with physical root  [applicaitonpath] hit unexpected managed exception, exception  code = '0xe0434352'. Please check the stderr logs for more information.

However, nothing is written to the stdout file.

**Comment by anurse** [comment]
@arun1998 can you post a **runnable sample project** that reproduces the problem? We need to see the full context of what's going on. The error message you posted indicates that an exception is being thrown by your application at startup. Did you try the steps in the troubleshooting guide (such as running the app from the command line)?

**Comment by arun1998** [comment]
Hi Andrew,

I have attached the program and start up files. I have highlighted the code which throws the error in red n the start up. Please let me know if you need more information. I really appreciate you taking the time to try and get to the bottom of this.

In the meantime, we are redirecting to https on the IIS server itself, though we would like to get this to work in code.

Thanks
[Startup.docx](https://github.com/dotnet/aspnetcore/files/4124241/Startup.docx)
[Program.docx](https://github.com/dotnet/aspnetcore/files/4124237/Program.docx)

**Comment by anurse** [comment]
What happens when you run the app directly with `dotnet` on the command line (as recommended in the troubleshooting guide)? Also, the code you provided isn't sufficient to run and reproduce the issue.
