### ISSUE TITLE
Slow Page Loading When using Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation in development On IIS

### ISSUE THREAD

**Issue by franks1** [dotnet/aspnetcore#18502]
Hello Team,
Please i have been encountering an issue with the usage of Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package in development on IIS from visual studio.
**After editing a ui element on the view it takes quiet a considerable amount of time for the changes to be seen on the page after page refresh.**
This behaviour is however not the same when running the app in debug mode using IIS Express.
**My problem is with the delay (30 secs) in loading a page after reload when changes are done in the view.**

**Comment by pranavkm** [comment]
Could you share the application's debug logs? The first use of runtime compilation is typically slow - this is a result of loading the JITting the compiler. You could consider mitigating this by attempting to warm up the compiler. https://github.com/aspnet/Mvc/issues/5746 has some sample code that could help.

**Comment by franks1** [comment]
Hi Pranav,
Thank you for the reply. I will share the log soon

**Comment by franks1** [comment]
I have reverted to Asp.net core 2.2
