### ISSUE TITLE
DateTime model binding does not work when form is submitted using method=get

### ISSUE THREAD

**Issue by egrabitt** [dotnet/aspnetcore#18506]
When an input with type="text" is bound to a DateTime property, it behaves differently depending on the form submit method (get or post). 

How to reproduce: create a Razor Pages application with VS Community 16.4.3 (Targetframework: netcoreapp3.1).
Then modify the Index files as follows.

Index.cs:

```
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DateGetBug.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public DateTime Date { get; set; }

        public void OnGet() {}
    }
}
```

Index.cshtml.cs:

```
@page
@model IndexModel

<p>last submitted date: @Model.Date</p>

<form method="get">
    <input asp-for="@Model.Date" type="text"/>
    <input type="submit"/>
</form>
```

So you just add a DateTime property and bind it to a form element.

I'm currently in Switzerland and the local date format is dd.MM.yyyy. 
When I enter 09.01.2020 (meaning January 9th in my locale), the DateTime object is set to 01.09.2020 (September 1st). This is clearly wrong.
But when I change the form submit method to "post" it works correctly! The DateTime object is now set to January 9th.

I understand that some localization settings might be missing/wrong. **But why would the form submit method impact how incoming date strings are parsed during model binding? Shouldn't this be consistent?** The text that is submitted in the HTTP request body (for "post") and in the URL (for "get") are exactly the same (just the unmodified user input as you'd expect).
I also acknowledge that if I remove type="text" from the input declaration, it will work. But I need the date input field to be a text field so I can use a JS date picker.

**Comment by pranavkm** [comment]
@egrabitt see https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-2.1#globalization-behavior-of-model-binding-route-data-and-query-strings-1. Using `method="GET"` results in data being [sent over the query string](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data#The_GET_method) which would explain why you see culture invariant binding. The doc article includes ways to configure culture specific query string binding.

**Comment by egrabitt** [comment]
@pranavkm thank you for your quick reply. 
> This is by design so that URLs are shareable across locales
makes sense. However in my use case, I don't need or want this behavior.
And working around it is not exactly simple. So I'll just bind to a string instead of a DateTime and use DateTime.Parse (which does respect the current culture). Working with dates has never been easy... Thanks again!
