### ISSUE TITLE
Cant build, no service permission

### ISSUE THREAD

**Issue by Meai** [dotnet/aspnetcore#18509]
> aspnetcore/src/Components $ ./build.sh
> aspnetcore/.dotnet/sdk/3.1.100/NuGet.targets(123,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-aspnet-AspNetCore-Tooling-07f16c89/nuget/v3/index.json. [/home/pc/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19607.3/tools/Tools.proj]
> /home/pc/workarea/test/aspnetcore/.dotnet/sdk/3.1.100/NuGet.targets(123,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/home/pc/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19607.3/tools/Tools.proj

Also I get this when trying to build directly with jetbrains:

>   Microsoft.AspNetCore.Authorization.csproj: [NU1105] Unable to find project information for '/aspnetcore/src/Http/Metadata/src/Microsoft.AspNetCore.Metadata.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so please run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.

**Comment by Pilchie** [comment]
@dotnet/aspnet-build - looks like we accidentally have an internal only feed in the public repo still?

**Comment by dougbu** [comment]
Something strange is going on. Our NuGet.config does not contain any darc-int-* feeds.

@Meai please make sure you're using the latest 'release/3.1' commits from GitHub, clean your repo, and try again. I suggest trying `.\restore.sh` in the root directory before using one of the lower-level `build.sh` scripts. Please let us know if that changes anything (or not).

**Comment by wtgodbe** [comment]
@Meai are you building the `v3.1.1` tag? That _does_ have internal feeds in its nuget.config (in fact, that is the case for v3.1.1 tags in most of our repos - I'm chatting offline with @mmitche about this)

**Comment by Meai** [comment]
@wtgodbe yes... I wanted to be safe and get a guaranteed working build

**Comment by dougbu** [comment]
@Meai the tags are for exactly what we built internally as part of the release process. Sometimes they cannot be built externally. On the other hand, our checkin tests should ensure the main branches ('master' and 'release/*') work consistently. ("Guaranteed working build" is what we target for those branches. Of course, bad things sometimes happen e.g. network glitches ☹️)

**Comment by pranavkm** [comment]
@Meai I verified this no longer reproduces in the 3.1 branch. The non-public feeds have been removed. The [3.1.1 tag](https://github.com/dotnet/aspnetcore/blob/v3.1.1/NuGet.config#L9-L12) continues to reference these packages, if you were to specifically build that tag, you'd have to edit the NuGet.config to remove these.
