### ISSUE TITLE
VS 2019 latest update , angular and .net core mixed project not loading

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18515]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/765192/vs-studio-2019-latest-update-angular-and-net-core.html)._

---
vs studio 2019 latest update , angular and .net core mixed project not loading

https://github.com/emonney/QuickApp

this project wont load in 2019, it was working earlier,   and it is also working in 2017

---
#### Visual Studio Feedback System on 10/9/2019, 01:33 AM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it
#### Visual Studio Feedback System on 10/9/2019, 01:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/11/2019, 11:48 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
