### ISSUE TITLE
Pin a couple of packages in 3.0 and 3.1 branches

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#18519]
After the (long) [discussion](https://github.com/dotnet/aspnetcore/pull/18364#discussion_r368208938) in #18364 about CoreFx package versions where we only need ref/ assemblies, should also pin the following to their `.0` versions in 'release/3.0' and 'release/3.1' branches:
- Microsoft.Win32.Registry
- System.Security.Principal.Windows

(We do not seem to need ref/ assemblies from other packages shown in https://github.com/dotnet/runtime/search?q=isnetcoreappref&unscoped_q=isnetcoreappref @ericstj please confirm those properties are the same for 3.0, 3.1 and 5.0 -- GitHub search doesn't help much.)

**Extensions**

- [x] `release/3.0` - https://github.com/dotnet/extensions/pull/2899
- [x] `release/3.1` - https://github.com/dotnet/extensions/pull/2900

**AspNetCore**

- [x] `release/3.0` - https://github.com/dotnet/aspnetcore/pull/18541
- [x] `release/3.1` - https://github.com/dotnet/aspnetcore/pull/18542

EFCore, Aspnetcore-Tooling, Blazor, and EF6 don't depend on any of these packages, so nothing is needed there

**Comment by dougbu** [comment]
Hmm, can't add this to https://github.com/orgs/aspnet/projects/2 My preference is to:
- Move that project to the dotnet organization
- Move the aspnet/AspNetCore-Internal repo to the dotnet organization
- Update RasS to understand the changed landscape

@Pilchie and @anurse do you know a way to move a project between organizations? If we're agreed, could you do that and the AspNetCore-Internal repo move?

**Comment by ericstj** [comment]
> confirm those properties are the same for 3.0, 3.1 and 5.0 

Yes we've represented this the same way since 2.0.

**Comment by anurse** [comment]
@dougbu I don't see a way to move projects between orgs. That's probably because projects can generally only contain issues from repos in the same org, so it gets a little complicated. We could open a new project and work on migrating issues.

As for moving AspNetCore-Internal, I'm fine with that but don't have the necessary permissions in the dotnet org to do so.

**Comment by Pilchie** [comment]
> As for moving AspNetCore-Internal, I'm fine with that but don't have the necessary permissions in the dotnet org to do so.

I don't either, but @jaredpar could probably do it for us.

**Comment by jaredpar** [comment]
Yes I can do it. Can someone positively state they want me to move AspNetCore-Internal to the dotnet org? The language so far is "i'm fine with it". Want to verify before I do the move.

**Comment by Pilchie** [comment]
Please go ahead and move AspNetCore-Internal to the dotnet org whenever it's convenient to you, and let me know when you are done.

**Comment by jaredpar** [comment]
Assuming it should be named aspnetcore-internal (casing change) to match the other moves?

**Comment by Pilchie** [comment]
Yes, sounds good to me.

**Comment by jaredpar** [comment]
The transfer has happened. There is one new team though we hadn't ported yet: aspdoi. Do you need that ported? Seems that aspnet-push had enough overlap that this shouldn't be a problem.

**Comment by Pilchie** [comment]
Thanks!

For `aspdoi` I had created it, but apparently not populated it :)  https://github.com/orgs/dotnet/teams/aspdoi

It's there for mentioning, not for permissions, so we can do that on our own.

**Comment by jawn** [comment]
As 3.1.3 has been released, should this be moved to a later milestone?

**Comment by wtgodbe** [comment]
The issue was resolved in 3.1.3, so should be fine to keep that as its milestone - I guess I just forgot to close it 🤦‍♂
