### ISSUE TITLE
I want you to be able to secure cookies.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18518]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/752872/cookieをセキュアに出来るようにしてほしい.html)._

---
In AspNetCore, to secure cookies, the ConfigureServices method of Startup.cs

After setting AddAntiforgery, session/cookie deserialization process becomes unstable, and HTTP POST frequently returns "Unresponsive HTTP ERROR 400", so we gave up securing cookies.
http://life-of-dev.sblo.jp/article/186622593.html https://infosec.mozilla.org/guidelines/web_security#cookies

---
#### Visual Studio Feedback System on 9/28/2019, 11:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/29/2019, 07:40 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
We need a lot more information. Your Configure and ConfigureServices methods are a good starting point, along with logs from failing requests.

**Comment by Tratcher** [comment]
Those are included in the first link (translation required). A Fiddler trace of the requests would help even more.
