### ISSUE TITLE
Generate Package On Build Doesn't Work For Blazor App

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/890807/generate-package-on-build-doesnt-work-for-blazor-a.html)._

---
I have created Nuget packages for Dot Net Core  and Dot Net Standard libraries this way, but Generate Package on Build doesn't generate a package for a Blazor App.

Is there a reason for this?

And in a follow up question, why is .Net Standard the only option for Razor Class Libraries? It seems like Dot Net Core should also be an option as I only want .Net Standard if I need to reference a .Net Framework library from .Net Core.

Thank you

---
#### Visual Studio Feedback System on 1/20/2020, 06:55 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.
#### Visual Studio Feedback System on 1/20/2020, 06:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
In .NET 5.0 Blazor projects will target `net5.0` TFM.
