### ISSUE TITLE
Unexpected 'asp-for' expression result type

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18514]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/869137/unexpected-asp-for-expression-result-type.html)._

---
Hello.
Please see picture. I write code that way to be no exceptions but Razor compiler or somethink else make an exception
[https://c2n.me/45jMuPD.png](https://c2n.me/45jMuPD.png)

---
#### Visual Studio Feedback System on 12/29/2019, 10:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/30/2019, 09:06 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### ice19942335 on 1/4/2020, 06:56 AM: 

Solved

---
#### ice19942335 solved on 12/28/2019, 00:33 PM, 0 votes: 

<p>Sorry, my bad. The problem is in this place.</p><pre>asp-for="RustServerEditViewModel.ShowInShop"
</pre>

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
