### ISSUE TITLE
Blazor Serverside Global Error Handling #blazor

### ISSUE THREAD

**Issue by bansalankit2601** [dotnet/aspnetcore#18510]
Is there any Blazor Global Error handling feature ?

If the Connection Circuit is broken / Some error in console is thrown which makes the connection break and no furthur navigation is possible.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @bansalankit2601.
The Blazor WASM project template has a section to customize a UI for showing up errors when they happen.
As for having a place in the code to handle and swallow all the errors which can potentially happen within the app, this is something we intentionally do not want to do.
To see how you can customize the error UI, please read: https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1#detailed-errors-during-development

**Comment by bansalankit2601** [comment]
Hi,

I get this kind of error when the circuit breaks in the Console of Developer Window .

![image](https://user-images.githubusercontent.com/55937292/72929746-6b83b000-3d28-11ea-9e05-4293cbace8a3.png)

Is there anyway I can notify the user that an error has occurred after this in the screen and ask to refresh it without manually opening the developer window to check and refreshing it.

**Comment by mkArtakMSFT** [comment]
@javiercn any recommendation regarding this?

**Comment by bansalankit2601** [comment]
I am using Blazor Server Side Application.

**Comment by mkArtakMSFT** [comment]
@bansalankit2601 the link I've provided describes how you can show a UI to the user with a custom message. Isn't that satisfactory for your case?

**Comment by bansalankit2601** [comment]
I don't think you are understanding what I am telling.

This does not cover the case if there is any console error in the page.

**Comment by mkArtakMSFT** [comment]
@bansalankit2601 there are two separate things:
- if you experience errors there is a yellow-bar showing up in the browser UI which you can customize.
- if the connection drops, and you need to reconnect you can use https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#connection-to-the-server

If you think this is not still the answer to your question, please try to rephrase your issue.

**Comment by physix99** [comment]
@bansalankit2601 If you created your Blazor project from an old template, your probably missing

```
<div id="blazor-error-ui">
    An unhandled error has occurred.
    <a href="" class="reload">Reload</a>
    <a class="dismiss">🗙</a>
</div>
```

on your _Host.cshtml page, if you add that (you'll also need some css, best to create a new project based on updated templates to copy from).

When an error occurs a yellow bar appears at the bottom of the page telling your user that an error has occured, without needing to look into the browser console.

That caught me out as well
