### ISSUE TITLE
Auth0: Callback gives error "OpenIdConnectAuthenticationHandler: message.State is null or empty."

### ISSUE THREAD

**Issue by kirk-marple** [dotnet/aspnetcore#18528]
### Describe the bug

When using Auth0 in passwordless model, ASP.NET Core OpenIdConnectAuthenticationHandler throws an exception that the message.State is null or empty.

It appears Auth0 is calling back to the ASP.NET Core application OK with the id_token on the URL, but the middleware isn't parsing/handling the callback URL properly.

I've tried both Token and IdToken for ResponseType (and making the related change in the initial Auth0 POST), and forcing ResponseMode to Fragment, and nothing seems to change the behavior.

                options.ResponseType = OpenIdConnectResponseType.IdToken;

Is this callback from Auth0 not in the proper format, or is this a bug in the authentication handler?  Something in my Startup.cs not configured properly?

http://localhost:3000/signin-auth0#id_token=[id token]&state=STATE

### To Reproduce

1. HTTP POST to https://[subdomain].auth0.com/passwordless/start
``` JSON
{
  "client_id": "[Auth0 web application client_id]",
  "connection": "email",
  "email": "[my email]",
  "send": "link",
  "authParams": {
    "scope": "openid profile",
    "response_type": "id_token",
    "redirect_uri": "http://localhost:3000/signin-auth0",
    "nonce": "NONCE",
    "state": "STATE"
  }
}
```
2. Receive 'magic link' in my email:
https://[subdomain].auth0.com/passwordless/verify_redirect?scope=openid%20profile&response_type=id_token&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsignin-auth0&nonce=NONCE&state=STATE&verification_code=[code]&connection=email&client_id=[Auth0 client id]&email=[my email]

3. HTTP GET in Postman this URL causes redirect to:
https://[subdomain].auth0.com/login/callback?state=[state]

4. Then a redirect to:
http://localhost:3000/signin-auth0#id_token=[id token]&state=STATE

As you can see, the id_token is on the callback URL, in the fragment, which appears correct from what OIDC should expect.

But the ASP.NET Core 3.0 web application throws this exception.  From looking at the source code on Github, it appears it's not parsing this /signin-auth0 callback properly.

From handling OnMessageReceived event, I can see that messageReceivedContext.Properties.Items.Count == 0, and messageReceivedContext.ProtocolMessage.State == null, so it falls through to throw this exception..

https://github.com/dotnet/aspnetcore/blob/8b000d961cd3ccfcc8090fb8368fd6598bace978/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L546

#### Exception:
``` shell
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

#### Startup.cs
``` C#
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            // Add authentication services
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddCookie()
            .AddOpenIdConnect("Auth0", options =>
            {
                options.Authority = $"https://{Configuration["Auth0:Domain"]}";
                options.MetadataAddress = $"https://{Configuration["Auth0:Domain"]}/.well-known/openid-configuration";

                options.ClientId = Configuration["Auth0:ClientId"];
                options.ClientSecret = Configuration["Auth0:ClientSecret"];

                options.ResponseType = OpenIdConnectResponseType.IdToken;

                options.Scope.Clear();
                options.Scope.Add("openid");
                options.Scope.Add("profile");

                // Set the callback path, so Auth0 will call back to http://localhost:3000/signin-auth0
                // Also ensure that you have added the URL as an Allowed Callback URL in your Auth0 dashboard
                options.CallbackPath = new PathString("/signin-auth0");

                // Configure the Claims Issuer to be Auth0
                options.ClaimsIssuer = "Auth0";

                // Auth0 puts token on fragment
                options.ResponseMode = OpenIdConnectResponseMode.Fragment;

                // Saves tokens to the AuthenticationProperties
                options.SaveTokens = true;

                options.Events = new OpenIdConnectEvents
                {
                    // handle the logout redirection 
                    OnRedirectToIdentityProviderForSignOut = (context) =>
                    {
                        var logoutUri = $"https://{Configuration["Auth0:Domain"]}/v2/logout?client_id={Configuration["Auth0:ClientId"]}";

                        var postLogoutUri = context.Properties.RedirectUri;

                        if (!string.IsNullOrEmpty(postLogoutUri))
                        {
                            if (postLogoutUri.StartsWith("/"))
                            {
                                // transform to absolute
                                var request = context.Request;
                                postLogoutUri = request.Scheme + "://" + request.Host + request.PathBase + postLogoutUri;
                            }
                            logoutUri += $"&returnTo={ Uri.EscapeDataString(postLogoutUri)}";
                        }

                        context.Response.Redirect(logoutUri);
                        context.HandleResponse();

                        return Task.CompletedTask;
                    }
                };
            });

            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Latest);
        }
```

### Further technical details
- Visual Studio 2019 v16.5.0 Preview 1.0

- ASP.NET Core 3.0, .NET Core 3.1
- TargetFramework 'netcoreapp3.1'

- dotnet --info:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Tratcher** [comment]
The middleware doesn't support OpenIdConnectResponseMode.Fragment, that only works with client apps. HTTP doesn't transmit the fragment portion of the url to the server, it can only be seen on the client.

**Comment by kirk-marple** [comment]
Thanks for the feedback; that makes sense.  I was able to work around it by using 'form_post', and then can see the state.   I did have to hack the state 'protect/unprotect' in OnMessageReceived since I was passing unencrypted data (a customer GUID) with the 'magic link' from Auth0.

My problem now, and this may just be by design, is that Auth0 passwordless doesn't insert any cookies into the HTTP request, so the middleware gives a 'Correlation not found' error.  I can't see any way to workaround that problem currently, so may be dead in the water for using their 'magic link' email with this middleware.

**Comment by anurse** [comment]
Our OpenIdConnectAuthenticationHandler requires correlation IDs in order to protect against CSRF attacks. Can you provide something like a [Fiddler](https://www.telerik.com/fiddler) trace so we can see how this flow is operating?

(Moved to Discussions since there isn't actionable product work here, as Auth0 Magic Link isn't an officially-supported auth system; but we're happy to help you figure this out!)

**Comment by kirk-marple** [comment]
Great, thanks.  I've attached the Fiddler sessions as cURL export, just so I could redact PII.

If you need the actual Fiddler export, I'd be happy to send via email directly.

[Auth0 Passwordless.zip](https://github.com/dotnet/aspnetcore/files/4106479/Auth0.Passwordless.zip)

Some color on each request:

1. I'm making the initial call to /passwordless/start on Auth0 to send out the 'magic link' email.

Auth0 lets you select id_token, token or both.

{
  "client_id": "redacted",
  "connection": "email",
  "email": "redacted@gmail.com",
  "send": "link",
  "authParams": {
    "scope": "openid profile",
    "response_type": "id_token",
    "response_mode": "form_post",
    "redirect_uri": "http://localhost:3000/signin-auth0",
    "nonce": "NONCE",
    "state": "STATE"
  }
}
2. I receive the email in Gmail, and click the link.
3. That goes to Auth0 /passwordless/verify_redirect
4. That redirects to Auth0 /login/callback
5. Which redirects to my local URL (debugging my web app in IIS Express locally), and does HTTP POST with id_token in body.

**Comment by Tratcher** [comment]
> Great, thanks. I've attached the Fiddler sessions as cURL export, just so I could redact PII.

That's a curious format, it doesn't show you any of the responses. In this case it should be adequate though.

I see what you're missing in all of this, a step 0. Our auth providers don't support remotely initiated auth flows, you need to start on the website you're trying to log into (http://localhost:3000/) and issue a challenge that redirects you to the identity provider (https://redacted.auth0.com/). That challenge is what sets up the state for the login flow and adds CSRF protections. Not sure how this integrates with their passwordless flow, but conceptually you should be able to make them work together.

The callenge can be issued automatically by `[Authorize]` or manually by `HttpContext.ChallengeAsync`.

You'll want to change your DefaultChallengeScheme to "Auth0".

**Comment by blowdart** [comment]
There's also a specific [.NET SDK](https://github.com/auth0/auth0.net) from Auth0, which might work better for you. I'm sure @damieng has some advice on using that.

**Comment by damieng** [comment]
While we do have a .NET SDK it's really for management/scripting.

The recommended approach for integrating Auth0 with ASP.NET applications is to use the built-in ASP.NET stuff.  If it's not working in ASP.NET Core 3.x we'll have to dig in.

**Comment by kirk-marple** [comment]
> I see what you're missing in all of this, a step 0. Our auth providers don't support remotely initiated auth flows, you need to start on the website you're trying to log into (http://localhost:3000/) and issue a challenge that redirects you to the identity provider (https://redacted.auth0.com/). That challenge is what sets up the state for the login flow and adds CSRF protections. Not sure how this integrates with their passwordless flow, but conceptually you should be able to make them work together.

I'm not an expert on this, but I believe their passwordless flow bypasses the step 0.  We are looking for an invite-only method to onboard users.  So, from our admin portal, we create a new user using /passwordless/start, which puts a user into Auth0, and then waits for them to attempt to log back in via the 'magic link' in their email.  That links up their SSO user to the passwordless user, and we let them into the app.

**Comment by Tratcher** [comment]
That's not going to work here, the user needs to visit your site before they're sent to Auth0.

**Comment by blowdart** [comment]
This seems like a question for Auth0 then rather than us. Presumably they have code to support this for their clients.

I'm closing this for now, unless Auth0 have some questions in which case, please reopen.
