### ISSUE TITLE
Issue in .netcore3.1 - when we invoke second request of the same rest api controller

### ISSUE THREAD

**Issue by vimala1085** [dotnet/aspnetcore#18535]
when i invoke the rest api firsttime it is getting processed successfully but i try to invoke second request of the same controller with different rest method the i get the below error:

Can anyone help me out to resove this issue.
```
System.InvalidOperationException: No service for type 'Microsoft.Extensions.Logging.ILoggerFactory' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, Object token)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.GetParameterBindingInfo(IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.CreateBinderDelegate(ParameterBinder parameterBinder, IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Siemens.SiID.UIM.Microservice.Infrastructure.HttpExceptionMiddleware.InvokeRequest(HttpContext context) in D:\SiSuite\sisuite-uim\projects\backend\src\Siemens.SiID.UIM.Microservice\Infrastructure\HttpExceptionMiddleware.cs:line 70
   at Siemens.SiID.UIM.Microservice.Infrastructure.HttpExceptionMiddleware.Invoke(HttpContext context) in D:\SiSuite\sisuite-uim\projects\backend\src\Siemens.SiID.UIM.Microservice\Infrastructure\HttpExceptionMiddleware.cs:line 119
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by pranavkm** [comment]
Could you share your Startup.cs \ Program.cs?

/cc @Tratcher

**Comment by Tratcher** [comment]
This looks the same as #18480.

**Comment by vimala1085** [comment]
public class Program
    {
        /// <summary>
        /// Static main method, Beginning of program execution
        /// </summary>
        public static void Main(string[] args)
        {
            Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);
            var isService = !(Debugger.IsAttached || args.Contains("--console"));
            var seedData = args.Contains("--seed");
            if (seedData)
            {
                IdentityTypeSeedConfig.IntialStartUp().Execute();
                DynamicUiSeedConfig.IntialStartUp(Configuration.SISUITE_UIM_DYNAMIC_UI_SEED_FILE_PATH).Execute();
            }
            UIMMicroServiceHost host = new UIMMicroServiceHost();
            host.Start(isService, seedData);
        }

**Comment by vimala1085** [comment]
public class Startup
    {
      //  private ILoggerFactory _loggerFactory;
        private LoggingProvider _loggingProvider;
        private TenantIssuerValidator _issuerValidator;
        private IDomainEventListener _domEvtListener;
        private IUumEventListener _uumEvtListener;
        private string _hostUrl;

        //private const string ClientName = "siid-uim";  
        private string ClientName = Microservice.Configuration.SISUITE_UIM_CLIENTNAME;
        private static ILog _log = LogManager.GetLogger(typeof(Startup));
        /// <summary>
        /// Gets or sets SeedData
        /// </summary>
        public static bool SeedData { get; set; }
        private IUnityContainer _unityContainer;
        private IServiceProvider _serviceProvider;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="configuration"></param>
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        /// <summary>
        /// to configure the Container
        /// </summary>
        /// <param name="container"></param>
        public void ConfigureContainer(IUnityContainer container)
        {
            // do not remove method, even if body is empty. Needed to get up the Container working properly.
            _unityContainer = container;
            InstanceFactory.SetUnityContainer(container);
        }

        /// <summary>
        /// Gets the configuration values
        /// </summary>
        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. 
        /// <summary>
        /// To add services to the container
        /// </summary>
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddNewtonsoftJson(); 
            services.AddHttpContextAccessor();
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll",
                    builder =>
                    {
                        builder
                        .AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader();
                    });
            });
            services.AddDynamicUiController();
            services.AddSingleton<IDynamicUiRepository, DefaultDynamicUiRepository>();
            services.AddSingleton<ILoggerFactory, LoggerFactory>();
            services
                .AddMvcCore(options =>
                {
                    options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));

                })
                .AddAuthorization()
                .AddNewtonsoftJson()
                .AddFormatterMappings()
                .AddMvcOptions(options =>
                {
                    //  options.InputFormatters.Add(Microsoft.AspNetCore.Mvc.Formatters.IInputFormatter.)
                    //options.OutputFormatters.Add(new SomeKindOf_IOutputFormatter());
                    //options.InputFormatters.Add(new SomeKindOf_IInputFormatter(options));
                })
                //.AddJsonFormatters()
               // .AddFormatterMappings()
                .AddApiExplorer();
               // .SetCompatibilityVersion(CompatibilityVersion.Versio);

            AddAuthenticationHandler(services);

            services.AddAuthorization(options =>
            {
                options.AddPolicy(Microservice.Configuration.IM_ViewIdentities, policy => policy.Requirements.Add(new HasScopeRequirement(Microservice.Configuration.IM_ViewIdentities)));
                options.AddPolicy(Microservice.Configuration.IM_ManageIdentities, policy => policy.Requirements.Add(new HasScopeRequirement(Microservice.Configuration.IM_ManageIdentities)));
                options.AddPolicy(Microservice.Configuration.IM_ManageIdentityTypes, policy => policy.Requirements.Add(new HasScopeRequirement(Microservice.Configuration.IM_ManageIdentityTypes)));
                options.AddPolicy(Microservice.Configuration.IM_ViewIdentities_AllTenants, policy => policy.Requirements.Add(new HasScopeRequirement(Microservice.Configuration.IM_ViewIdentities_AllTenants)));
            });
            
            services.AddSingleton<IAuthorizationHandler, HasScopeHandler>();
            services.AddLogging(builder =>
            {
                //to disable default aspnet core logging on http requests
                builder.AddFilter("Microsoft", LogLevel.Warning);
            });


            services.AddSingleton<IAppSettings, AppSettingsWrapper>();
            services.AddTenantContext();
            services.AddSingleton<IBrokerStatusRepository, BrokerStatusRepository>();
            services.AddSingleton<IDomainEventsWrapper, ActivityFeedExchangeWrapper>();

            RegisterMessageBrokerService(services);
           
        }

        // This method gets called by the runtime. 
        /// <summary>
        /// To configure the HTTP request pipeline.
        /// </summary>
        /// <param name="to"></param>
        /// <param name="the"></param>
        /// <param name="request"></param>
        /// <param name=""></param>
        public void Configure(IApplicationBuilder app, IHostingEnvironment env,IApplicationLifetime applicationLifetime)
        {
           
            _serviceProvider = app.ApplicationServices;                        

          
            _issuerValidator = new TenantIssuerValidator();
            _hostUrl = app.ServerFeatures.Get<IServerAddressesFeature>().Addresses.First();
            //_loggerFactory.AddLog4Net(_loggingProvider.LogConfigPath,true);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseHttpExceptionMiddleware();
            }
            else
            {
                app.UseHttpExceptionMiddleware();
            }

            applicationLifetime.ApplicationStarted.Register(OnStarted);
            applicationLifetime.ApplicationStopping.Register(OnStopping);
            app.UseCors("AllowAll");
            ConfigureStaticFileHosting(app);
            app.UseRouting();
            app.UseAuthentication();          
          //  app.UseMvc();
           
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }


        private void AddAuthenticationHandler(IServiceCollection services)
        {
            services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(x =>
            {
                x.Events = new JwtBearerEvents
                {
                    OnChallenge = c =>
                    {
                        if(!JwtSecurityKeyLoader.CheckSigningKeyStatus())
                        {
                            c.Response.StatusCode = StatusCodes.Status503ServiceUnavailable;
                            c.HandleResponse();
                        }

                        return Task.FromResult(0);
                    }
                };
                x.IncludeErrorDetails = true;
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    
                    ValidateIssuer = false,
                    ValidIssuer = Microservice.Configuration.SISUITE_AUTH_VALID_ISSUER,
                    ValidateLifetime = true,
                    ValidateAudience = false,
                    IssuerValidator = _issuerValidator.Validator,
                    IssuerSigningKeyResolver = ((token, securityToken, identifier, parameters) =>
                    {                        
                        var jwtSecurityToken = new JwtSecurityToken(token);
                        return JwtSecurityKeyLoader.SecurityKeys.Where(sk => sk.KeyId.Equals(jwtSecurityToken.Header.Kid)).ToList();
                    })
                };
            });
        }
    
        private static void ConfigureStaticFileHosting(IApplicationBuilder app)
        {
            var fileOptions = new StaticFileOptions
            {
                ServeUnknownFileTypes = true,
                DefaultContentType = "application/json"
            };

            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wwwroot");
            path = Path.Combine(path, "identitymanagement");
            if (Directory.Exists(path))
            {
                DefaultFilesOptions options = new DefaultFilesOptions();
                options.DefaultFileNames.Clear();
                options.DefaultFileNames.Add("identitymanagement/index.html");
                app.UseDefaultFiles(options);
                app.UseStaticFiles();
                fileOptions = new StaticFileOptions { FileProvider = new PhysicalFileProvider(path), ServeUnknownFileTypes = true, DefaultContentType = "application/json" };
            }

            app.UseStaticFiles(fileOptions);
        }

        private void OnStarted()
        {
          //  var log = _loggerFactory.CreateLogger("StartupLogger");
            if (!JwtSecurityKeyLoader.CheckSigningKeyStatus())
            {
                //_log.Log(LogLevel.Error,
                //    Environment.NewLine + Environment.NewLine +
                //    "Authentication server not available, service can process the request once authorization server is available.");
            }

            ExternalResourceFactory.SyncUserRolesStartup();

            // configuration may have to wait for broker connection
            StartMessageSubscription();

           
            
        }

        private void OnStopping()
        {
            _domEvtListener?.Dispose();
        }

        private void RegisterMessageBrokerService(IServiceCollection services)
        {
            var enableSsl = !Microservice.Configuration.SISUITE_ACTIVITY_FEED_BROKER_SSL.ToLower().Equals("false");

            if (Microservice.Configuration.SISUITE_ACTIVITY_FEED_BROKER_TYPE.Equals(BrokerConnectionFactory.BROKER_IDENTIFIER_ACTIVEMQ))
            {
                services.AddSingleton(s => DomainEvents.Factory.UseActiveMQ(
                    Microservice.Configuration.SISUITE_ACTIVITY_FEED_BROKER_URL,
                    ClientName,
                    enableSsl));
            }
            else
            {
                services.AddSingleton(s => DomainEvents.Factory.UseRabbitMQ(
                    Microservice.Configuration.SISUITE_ACTIVITY_FEED_BROKER_URL, 
                    ClientName, enableSsl
                    ));
            }

        }

        private void StartMessageSubscription()
        {

            var identitiesRepository = _unityContainer.Resolve<IdentitiesRepository>();
            var identitiesRepositoryWrapper = _unityContainer.Resolve<IDomainEventRepoFactory>();

            _domEvtListener = TenantEventListener.Instance;
            _uumEvtListener = UumDomainEventListener.Instance;
            Task.Run(() =>
            {
                IBrokerConnection brokerConnection = null;
                while (brokerConnection == null)
                {
                    try
                    {
                        // ReSharper disable once AccessToDisposedClosure
                        brokerConnection = _serviceProvider.GetService<IBrokerConnection>();
                    }
                    catch (Exception e)
                    {
                        _log.Error("connect messaging", e);
                        Thread.Sleep(3000);
                    }
                }

                _domEvtListener.SubscribeToTenantMessage(brokerConnection, identitiesRepository);
                _uumEvtListener.SubscribeToUumMessage(brokerConnection, identitiesRepositoryWrapper);
            });
        
        }
    }

**Comment by Tratcher** [comment]
Yes, that code looks almost the same as #18480. We'll close this as a duplicate and focus on the other one.
