### ISSUE TITLE
Add support for catch-all routes in Blazor

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18539]

**Comment by SamProf** [comment]
Hi

I have question. `<NotFound>` for me catch all routes, isn't it?
Or maybe you can more properly describe the problem.

**Comment by zbecknell** [comment]
@SamProf See here for what would probably be the goal: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference

**Comment by zbecknell** [comment]
I'm looking into this.  Going to use `RoutePatternParser.cs` as a guide.
