### ISSUE TITLE
[Blazor] Published app results in 404s for pdb files

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18545]
@javiercn's PR for static web assets should fix this, but filing this for record keeping:

![image](https://user-images.githubusercontent.com/174281/73031425-e912f300-3df0-11ea-9bef-51de05fdcf06.png)

**Comment by michuny25** [comment]
I am currently running it on my server with the same issue for  `/_framework/_bin/XXX.Shared.pdb:1` and `/_framework/_bin/XXX.Domain.pdb:1`. Is there something I should be concerned about in terms of breaking some functionality or is it just a notification in console without any consequences?

**Comment by pranavkm** [comment]
The latter. The one scenario that would be broken as a consequence is debugging the app. Publishing it in Debug should fix it if that's an issue.

**Comment by SteveSandersonMS** [comment]
This will have been fixed by https://github.com/dotnet/aspnetcore/pull/18859, since we no longer publish pdbs nor include them in `blazor.boot.json` in the default published case.
