### ISSUE TITLE
blazor.boot.json contains duplicate entries for pdb files for shared projects

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18546]
When a project is referenced both by the server and client, the entry for the pdb file gets duplicated in the boot.json. This results in multiple HTTP requests:

![image](https://user-images.githubusercontent.com/174281/73031603-77877480-3df1-11ea-9885-c77e8763a733.png)

**Comment by SteveSandersonMS** [comment]
Was fixed implicitly as part of the caching work. We now get (example):

```
    "pdb": {
      "LatestBlazorHosted.Client.pdb": "sha256-fKkzoQXSvdgfDh6HajgSMVPU90maxoTU9ovAD9LCEn8=",
      "LatestBlazorHosted.Shared.pdb": "sha256-ph7mMOuoZOAYvH3py3DppxTbrPthCgR9yzRnCj4di6s="
    },
```
