### ISSUE TITLE
SignalR wont works  in IIS when open Web Garden

### ISSUE THREAD

**Issue by newyearsoft** [dotnet/aspnetcore#18553]
When IIS  Web Garden is 1. SignalR is work.everything is normal.
When Web Garden more then 1.SignalR wont works.
What should I set to make it work?

**Comment by davidfowl** [comment]
@newyearsoft once you have more than a single process, you need something to communicate across nodes. 

https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-3.1
