### ISSUE TITLE
user data on user tokens

### ISSUE THREAD

**Issue by cyberhck** [dotnet/aspnetcore#18550]
### User data in User tokens like password reset or activatioin
I'm trying to do password reset, but the token alone isn't enough to reset password, it still requires user to be able to do this. I've seen documentation where they suggest to have userid also set as a query parameter while sending emails which does work for me.

### The question I have
It's not a feature request per se, I just wanted to know the rationale of not having user data right on that token, is this by design? Is this because UserManager isn't supposed to query users?

**Comment by blowdart** [comment]
I assume you're using asp.net identity, is that correct?

What documentation are you referring to?

**Comment by cyberhck** [comment]
https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity

Currently my password reset link which is sent to email, contains 2 info, one is the user id and another is the reset token,

could we have encoded user id on the token directly? is that not included by design?

**Comment by blowdart** [comment]
It is by design. This is not a feature request we've had before and would involve changing how our tokens work, and splitting out common code just for reset tokens. 

For now this won't be something we would consider.

**Comment by cyberhck** [comment]
I understand it's by design, I just wanted to understand why is that? If user data was also set in token, then we'd only need token to reset, right?
