### ISSUE TITLE
Unable to Regenerate a Two Factor Token when User clicks Resend Code

### ISSUE THREAD

**Issue by ejstan** [dotnet/aspnetcore#18557]
Hi,

I'm trying to implement a functionality when a logs in he/she will receive a SMS containing a verification code and he/she must enter it to the web app in order to log in and should have the option to resend the code. When the user clicks on "Resend Code" a new Two Factor code must be generated and sent to his/her email. So far whenever I call the following code below it returns me the previous generated code:

``` C#
 // Generate the token and send it via SMS
 var code = await _userManager.GenerateTwoFactorTokenAsync(user, "Phone");
```

Any ideas on how to implement this or what I'm doing wrong?

**Comment by ejstan** [comment]
Already resolved the issue. Thanks

**Comment by ejstan** [comment]
I'm still unable to generate a new two-factor code when using this

**Comment by blowdart** [comment]
Can you define new for me? The MFA codes are based on time. If you call the code within the time period they will be the same. 

We don't have SMS in our templates any more, you do need to write code and we'd need to see that too.
