### ISSUE TITLE
User defined data type in Ado.net cause issue after upgrading to .net 3.1

### ISSUE THREAD

**Issue by Mrpankaj666** [dotnet/aspnetcore#18554]
In .net core 2.2 its working fine but once I upgrade the project to .net core 3.1 its start failing only for user defined data type in ado
Error: Object must implement IConvertible
please assist on this

**Comment by javiercn** [comment]
@Mrpankaj666 thanks for contacting us.

We believe this issue is not related to ASP.NET Core. You'll get a better and faster answer if you file an issue in the [dotnet runtime](https://github.com/dotnet/runtime) or the [ef repo](https://github.com/dotnet/efcore)

**Comment by Mrpankaj666** [comment]
Thanks @javiercn
