### ISSUE TITLE
SignalR - Start connection with many instances at the same time, SignalR maps them as same connection.

### ISSUE THREAD

**Issue by Kiril1512** [dotnet/aspnetcore#18558]
### Describe the bug
3 different client instances connect at the same time, signalR maps them as same connection.

### To Reproduce

**What steps can we follow to reproduce the issue?**

We have 3 client instances, with 3 different users in 3 separate machine, on 3 different networks. When we connect them to our hub  (a separate .net core 3 microservice that uses Azure SignalR), the connection is mapped correctly and 3 different connection Id are generated. But when we restart our hub (simulating that for some reason the microservice  is down and have resurrected)  all the 3 clients try to reconnect to the hub at the same time, and then they connect with the same connection Id. So if I broadcast a message to the ```caller``` only one of them receives the message. We are logging the connection Id received by the server and the connection Id that is stored in the instance that uses ```signalR.HubConnectionBuilder``` like following:

```typescript
private configureSignalR(token: string) {
 this.hubMessageConnection = new signalR.HubConnectionBuilder()
   .configureLogging(signalR.LogLevel.Trace).withUrl(this.signalRUrl + "/notifications",
     {
       accessTokenFactory: () => token
     })
   .build();
 });

 // invoke server side method to pass AppContext data.
 this.hubMessageConnection.invoke("RegisterApplicationGroupsAsync", this.groups)
    .then((connectionId: string) => {
      this.connectContextId = connectionId; 
      console.log(connectionId); // this is what we are receiving from the server that returns the connectionId when invoke this method.
      console.log(this.hubMessageConnection.connectionId); // this is the connection id stored in the hubMessageConnection.

      this.onConnectionComplete.emit();
    }).catch((ex) => {
      this.onError.emit(WidgetStateEnum.registerError);
    });
}
```

On the hub:
```c#
public async Task<string> RegisterApplicationGroupsAsync(Groups groups)
{
    try
    {
        SmartGuard.NotNull(() => groups, groups);
        SmartGuard.NotNullOrEmpty(() => groups.Groups, groups.Groups);

        // Add each group

        foreach (string group in groups.Groups)
        {
            await this.Groups.AddToGroupAsync(this.Context.ConnectionId, group).ConfigureAwait(false);
        }

        // Return connectionId for the client

        return this.Context.ConnectionId;
    }
    catch (ArgumentNullException)
    {
        throw new ServiceException(ServiceExceptionCode.NoDataProvidedToRegisterConnection, Resources.RES_No_Data_Provider_To_Register_Connection);
    }
}
```

When clients connect separately: 
![image](https://user-images.githubusercontent.com/32172963/73076147-6bfd8180-3eb5-11ea-8a8b-866b9d7e476d.png)

When clients connect exactly at same time (simulating that hub is now online).
Client 1:
![image](https://user-images.githubusercontent.com/32172963/73076814-cb0fc600-3eb6-11ea-938e-3874a12c449b.png)

Client 2:
![image](https://user-images.githubusercontent.com/32172963/73076966-25108b80-3eb7-11ea-94b3-17778e305e17.png)

Client 3:
![image](https://user-images.githubusercontent.com/32172963/73076875-eda1df00-3eb6-11ea-81c1-c3a64ab7964c.png)

As you can see the first console.log is returning the same Id from the hub, while the client connectionId is different in the 3 clients. This happens running the hub on localhost and on azure (web app).

### Further technical details
- API: ASP.NET Core version 3.0.
- Product: APS.NET FW 4.6.1 with SPA (Angular 8).
- Client package: @microsoft/signalr (https://www.npmjs.com/package/@microsoft/signalr)
- IDE: Visual Studio Enterprise 2019 v16.4.3.
- IDE: Visual Studio Code v1.41.1
- `dotnet --info`:
```cmd 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by BrennanConroy** [comment]
Are you able to consistently repro this? Is it possible to provide an app that displays this behavior?

I'm unable to reproduce this with a simple app and two clients.

Also, what is with the "9c41d1fa1" at the end of all the logs? ConnectionId's are 22 characters in length (yours are 31) and definitely don't contain the same sequence of characters across IDs.

**Comment by Kiril1512** [comment]
> Are you able to consistently repro this? Is it possible to provide an app that displays this behavior?
> 
> I'm unable to reproduce this with a simple app and two clients.
> 
> Also, what is with the "9c41d1fa1" at the end of all the logs? ConnectionId's are 22 characters in length (yours are 31) and definitely don't contain the same sequence of characters across IDs.

Yes, we can consistently repro this. I will upload on github a sample and share it here. 

About the "9c41d1fa1" at the end, I can't explain this. I tought that this is about Azure SignalR or something... We also use authentication to our hub using the ```Authorize``` attribute.

**Comment by BrennanConroy** [comment]
> I tought that this is about Azure SignalR or something...

Ah, I thought you were doing this locally, if you're using the Azure SignalR Service then that could make sense.

**Comment by anurse** [comment]
> * API: ASP.NET Core version 3.0.
> * Product: APS.NET FW 4.6.1 with SPA (Angular 8).

How are you using ASP.NET Core 3.0 with .NET Framework 4.6.1? This isn't supported.

> Yes, we can consistently repro this. I will upload on github a sample and share it here.

Please let us know when you can assemble a repro, that will allow us to investigate further.

**Comment by Kiril1512** [comment]
Hello. @anurse we are using a angular component that uses signalR to comunicate with our micro service, so there is not incompatibility. 

After I tried to reproduce this to upload a repro for you, I notice that I don't add the hub as a singleton but in my service I do. 

```c#
services.AddSingleton<EventBusListenerWorker>()
        .AddSingleton<NotificationsHub>()
        .AddSingleton<IEventBusManager, EventBusManager>()
        .AddSingleton<INotificationsManager, NotificationsManager>();
```

So when I remove the singleton from my microservice the issue is no more. So I believe that that was the problem. You can try it to. Just add your hub as a singleton in the startup and call the hub at the same time, it will map them as single connection. 
For now I was able to call my hub from the manager like:

```c#
private NotificationsHub NotificationsHub
{
    get
    {
        return this.serviceProvider.GetRequiredService<NotificationsHub>();
    }
}
```

now since I didn't add it as a singleton I need to inject the ```IHubContext``` like:

```c#
private IHubContext<NotificationsHub> NotificationsHub
{
    get
    {
        return this.serviceProvider.GetRequiredService<IHubContext<NotificationsHub>>();
    }
}
```

Maybe now I need to implement an interface to call my hub methods outside the hub or make client calls directly. Can you confirm that this is the problem?

**Comment by anurse** [comment]
> ```cs
>         .AddSingleton<NotificationsHub>()
> ```

This is the problem. SignalR expects the Hub to be created separately for each message. You need to add it as a Transient service if you want your Hub to be in DI. We should consider adding some check to prevent this though.

> ```cs
> private NotificationsHub NotificationsHub
> {
>     get
>     {
>         return this.serviceProvider.GetRequiredService<NotificationsHub>();
>     }
> }
> ```

You generally shouldn't resolve the Hub out of DI. If you need to share code between your Hub and some other component, I'd suggest using either `IHubContext` or putting the shared code in a separate DI service instead.

**Comment by Kiril1512** [comment]
Yes, I can't reproduce the behavior after removing the hub as a singleton. Thank you for your help. Closing this issue.
