### ISSUE TITLE
Windows Authentication -  ((ClaimsPrincipal)User).IsInRole 

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#18560]
### Describe the bug
User.IsInRole works with ActiveDirectory Group Names on local development machine, but does not work with ActiveDirectory Group Names after deploying to onpremise windows IIS server.  However, ActiveDirectory Group Sid does work on onpremise windows IIS server.  

### To Reproduce
Asp.Net Core 3.1 Blazor Server 
WindowsAuthentication: true
AnonymousAuthentication: false
var authenticationState = await AuthenticationStateProvider.GetAuthenticationStateAsync()
var b = authenticationState.User.IsInRole("MyAdGroupName")
b is true on local development machine, but false on windows IIS server

### Further technical details
- ASP.NET Core version
3.1
- Include the output of `dotnet --info`
Onpremise Windows Server
PS C:\Users\rsurles> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Users\rsurles>
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by blowdart** [comment]
Is the IIS server domain joined? Is the app pool running as a domain joined user? Can the server see an AD controller? Do you mutate the identity in any way?

**Comment by roysurles** [comment]
Is the IIS server domain joined? Is the app pool running as a domain joined user? Can the server see an AD controller? Do you mutate the identity in any way?

**Comment by roysurles** [comment]
Is the IIS server domain joined? YES; Is the app pool running as a domain joined user? YES; Can the server see an AD controller? YES; Do you mutate the identity in any way? NO  We are running other full .net framework 4.7.2 WebForms and MVC that work well with User.IsInRole("AdGroupName").

**Comment by blowdart** [comment]
Strange. Does a simple .NET Core MVC app also work?

**Comment by roysurles** [comment]
No.  Created new .net core 3.1 mvc web app and it works on my local development machine.  deployed it to our onpremise iis web server and it does NOT work either:  Context.User.IsInRole("MyAdGroup")

**Comment by Tratcher** [comment]
How is Windows Auth configured on the IIS site?

Is the user correctly identified? (E.g. Name?)

**Comment by roysurles** [comment]
Anonymous Authentication = Disabled
Windows Authentication = Enabled
![image](https://user-images.githubusercontent.com/37274814/73266715-110da800-419d-11ea-8a3c-d2da537ca939.png)
![image](https://user-images.githubusercontent.com/37274814/73266971-a0b35680-419d-11ea-9d92-fe930567611c.png)
![image](https://user-images.githubusercontent.com/37274814/73267505-d1e05680-419e-11ea-97b7-ec9f576bc1d2.png)
Yes, the user is correctly identified.

**Comment by Tratcher** [comment]
> Correction: Asp.Net Core MVC **DOES** work. We RDP into servers with alternate accounts for security purposes and I had run the MVC app within the RDP session so it was checking my alternate account. When I run web app on the server in a browser on my local machine it works, So this dies appear to be isolated to Blazor... sorry for the confusion.

@mkArtakMSFT looks like this is back in your court. How is Blazor capturing the user?

**Comment by roysurles** [comment]
@code {
    [CascadingParameter] Task<AuthenticationState> AuthenticationStateTask { get; set; }

    protected ClaimsPrincipal User { get; set; }

    protected override async Task OnInitializedAsync()
    {
        User = (await AuthenticationStateTask.ConfigureAwait(false)).User;
    }
}

**Comment by bmoteria** [comment]
I am having exact same issue. After deploying blazor server side app to IIS, User.IsInRole("...") always returns false.

@mkArtakMSFT @SteveSandersonMS @blowdart any timeline when this issue could be resolved? or if we can have a work around until it's fixed? We're re-writting one of our ASP.NET MVC app using Blazor Server Side (windows auth).

**Comment by blowdart** [comment]
@roysurles what happens if you cast it to a WindowsPrincipal?

**Comment by roysurles** [comment]
The only workaround we have found for this is to use the SID of the ActiveDirectory Group instead of the name.   Will try casting to WindowsPrincipal this morning and get back... thanks

**Comment by blowdart** [comment]
Windows Authentication is rather "special". It, as you have discovered, caches roles as SIDs and only does the lookup against role names when IsInRole is called. If it's a claims principal it can't do that, claims principal doesn't know how to call out to AD, so it needs to be cast back. 

Make sure it's not null though when you cast it, if something has fiddled with it (Claims transformation, or something else) then it will stay as a claims identity and you'd need to figure out what did that and stop it.

**Comment by bmoteria** [comment]
@blowdart I tried casting claims principal to windows principal but throws an exception after IsInRole() is executed. - This was tested in my local environment.

---
**Code:**

`private bool isPartOfUsersGroup;`

`protected override async Task OnInitializedAsync()`
    `{`
        `var authState = await authenticationStateTask;`
        `var windowsPrincipal = (WindowsPrincipal)authState.User;`
        `windowsPrincipalName = windowsPrincipal.Identity.Name;`
        `isPartOfUsersGroup = windowsPrincipal.IsInRole("Users");`
    `}`

---
**Exception thrown in console:**
blazor.server.js:15 [2020-02-18T14:03:00.516Z] Error: System.InvalidOperationException: At least one role must be specified.
   at Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement..ctor(IEnumerable`1 allowedRoles)
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder.RequireRole(IEnumerable`1 roles)
   at Microsoft.AspNetCore.Authorization.AuthorizationPolicy.CombineAsync(IAuthorizationPolicyProvider policyProvider, IEnumerable`1 authorizeData)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by blowdart** [comment]
is windowsPrincipal null at that point?

**Comment by bmoteria** [comment]
No it's not null. Please ignore my exception above. I'd <AuthorizeView> in the same page that threw above exception. After removing AuthorizeView tag from that page, i was able to cast to windows principal and it wasn't null - worked locally.

**I published my changes to IIS and gave me following error:**

[2020-02-18T14:21:23.180Z] Error: System.InvalidCastException: Unable to cast object of type 'System.Security.Claims.ClaimsPrincipal' to type 'System.Security.Principal.WindowsPrincipal'.
   at <ProductName>.BlazorUI.Pages.Counter.OnInitializedAsync() in C:\Users\bmoteria\1Source\Workspaces\<ProductName>\Dev\<Product>\<Product>.BlazorUI\Pages\Counter.razor:line 46
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by blowdart** [comment]
Hmm Blazor is doing something odd. Ok I'm leaving this to @SteveSandersonMS

**Comment by bmoteria** [comment]
@SteveSandersonMS, should we expect the fix for this issue before .NET 5 (hoping may be in next .NET core 3.1.2 release)? Appreciate all your help! 🙌

We have a dedicated team that is currently re-writting one of our existing product. Launch date for our product would highly rely on when this issue could be resolved.

**Comment by SteveSandersonMS** [comment]
> looks like this is back in your court. How is Blazor capturing the user?

We receive `IHubContext.User` from SignalR when the circuit is being started up, and make that object available to user code. We pass through the same actual object - we don't clone it or anything like that.

Here's the flow:

1. When starting the circuit, `StartCircuit` passes `Context.User` to `CreateCircuitHost`: https://github.com/dotnet/aspnetcore/blob/116799fa709ff003781368b578e4efe2fa32e937/src/Components/Server/src/ComponentHub.cs#L117
2. `CreateCircuitHost` passes that object to `SetCircuitUser`: https://github.com/dotnet/aspnetcore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Components/Server/src/Circuits/CircuitFactory.cs#L87
3. `SetCircuitUser` uses that object to initialize an `AuthenticationState` instance and passes it to `SetAuthenticationState`: https://github.com/dotnet/aspnetcore/blob/271ebe019823e8e6a751429cd350c2db76ebab05/src/Components/Server/src/Circuits/CircuitHost.cs#L485-L486
4. `SetAuthenticationState` holds this info and supplies it to any user code that accesses the authentication state via `AuthenticationStateProvider.GetAuthenticationStateAsync`: https://github.com/dotnet/aspnetcore/blob/057ec9cfae1831f91f1a0e01397059b20431db7b/src/Components/Server/src/Circuits/ServerAuthenticationStateProvider.cs#L25

Since Blazor doesn't transform the `ClaimsPrincipal` object in any way, but rather just passes through what it gets from `IHubContext.User` into user code, I'm not sure what we could be doing to prevent this from working. @Tratcher do you have any thoughts on anything we might be doing wrong? Are we right to expect the `IHubContext.User` instance to remain value for the duration of a SignalR connection? (Note that we do renew the instance to whatever `IHubContext.User` has become each time the user reconnects - this flow starts [here](https://github.com/dotnet/aspnetcore/blob/116799fa709ff003781368b578e4efe2fa32e937/src/Components/Server/src/ComponentHub.cs#L171)).

> User = (await AuthenticationStateTask.ConfigureAwait(false)).User;

@roysurles I don't know this has anything to do with the problem you're reporting, but you definitely shouldn't use `ConfigureAwait(false)` with Blazor or any other UI stack. If you want lots more info about why, read [this FAQ](https://devblogs.microsoft.com/dotnet/configureawait-faq/). Using `ConfigureAwait(false)` with a UI stack exposes you to synchronization context errors.

**Comment by Tratcher** [comment]
@BrennanConroy? I know SignalR does lots of special things to handle WindowsPrincipals. Not sure how many of them Blazor benefits from for free?

**Comment by BrennanConroy** [comment]
We only do something special if you're using LongPolling.
And I just tested this out, and looks like there is an issue with how we clone the `WindowsPrincipal`.

As a workaround you can do:
```
var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
if (authState.User.Identity is WindowsIdentity)
{
    isInGroup = new WindowsPrincipal((WindowsIdentity)authState.User.Identity).IsInRole("Users");
}
else
{
    isInGroup = authState.User.IsInRole("Users");
}
```

**Comment by bmoteria** [comment]
You guys are genius!!

I tested by deploying the workaround code on IIS and works as expected. Note that in my case it always executes if.. code.

**Comment by SteveSandersonMS** [comment]
> And I just tested this out, and looks like there is an issue with how we clone the WindowsPrincipal.

Thanks for figuring this out, @BrennanConroy!

Are you tracking this issue elsewhere (so I can close this issue), or would you prefer to leave this one open to track that underlying issue?

**Comment by bmoteria** [comment]
I also encountered another issue when fetching data from an api using impersonation.

**Couter.razor**
----
```
var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
if (authState.User.Identity is WindowsIdentity)
{
      var user = new WindowsPrincipal((WindowsIdentity)authState.User.Identity);
      WindowsIdentity wi = (WindowsIdentity)user.Identity;
      await WindowsIdentity.RunImpersonated(wi.AccessToken, async () =>
      {
          forecasts = await ForecastService.GetForecastAsync(user);
      });
}
```

**ForecastService.cs**
----
```
public async Task<WeatherForecast[]> GetForecastAsync(WindowsPrincipal user)
{
      // exception occurs when below statement is executed.
      var returnData = await _httpClient.GetJsonAsync<WeatherForecast[]>("api/WeatherForecast/GetRandomWeather");

      return returnData;
}
```

**WeatherForecastController.cs**
----
```
[HttpGet("GetRandomWeather")]
public List<WeatherForecast> GetRandomWeather()
{
      var rng = new Random();
      var data = Enumerable.Range(1, 5).Select(index => new WeatherForecast
      {
            Date = DateTime.Now.AddDays(index),
            TemperatureC = rng.Next(-20, 55),
            Summary = Summaries[rng.Next(Summaries.Length)]
      }).ToArray().ToList();

      data.Add(new WeatherForecast() { Summary = User.Identity.Name, Date = DateTime.Today, TemperatureC = 77 });
            
      return data;
}
```

**Exception:**
----
[2020-02-25T15:04:44.052Z] Error: System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T](HttpClient httpClient, String requestUri)
   at BlazorImpersonate.Data.WeatherForecastService.GetForecastAsync(WindowsPrincipal user) in C:\Users\bmoteria\source\repos\BlazorImpersonate\BlazorImpersonate\Data\WeatherForecastService.cs:line 34
   at BlazorImpersonate.Pages.FetchData.<>c__DisplayClass3_0.<<OnInitializedAsync>b__0>d.MoveNext() in C:\Users\bmoteria\source\repos\BlazorImpersonate\BlazorImpersonate\Pages\FetchData.razor:line 56
--- End of stack trace from previous location where exception was thrown ---
   at BlazorImpersonate.Pages.FetchData.OnInitializedAsync() in C:\Users\bmoteria\source\repos\BlazorImpersonate\BlazorImpersonate\Pages\FetchData.razor:line 54
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

----

Is there anything I'm missing?

**Comment by SteveSandersonMS** [comment]
@bmoteria Check what the server is actually responding with when you make your request to the API endpoint. The error message `'<' is an invalid start of a value` suggests it's returning HTML when you're expecting JSON, so it may well be misconfigured routes.

**Comment by bmoteria** [comment]
@SteveSandersonMS the api endpoint returns json when navigate directly to uri. When httpclient was trying to request data it wasn't in json format therefore error occurred. After specifying default request header, it's working.

Also deployed on IIS:
![image](https://user-images.githubusercontent.com/61192134/75262872-233e2e80-57bb-11ea-8c67-fd9fc9594b4b.png)

Thank you so much for the help.

**Comment by BrennanConroy** [comment]
> Note that in my case it always executes if.. code.

Right, if you're using WindowsAuth + LongPolling then it always will hit that (until we fix it).

On a related note, Blazor generally works better with WebSockets (less latency) and it also wont hit the WindowsAuth issue. You should consider enabling WebSockets in IIS.

> Are you tracking this issue elsewhere (so I can close this issue), or would you prefer to leave this one open to track that underlying issue?

Not tracked anywhere, we can probably re-purpose this issue.

**Comment by bmoteria** [comment]
> Right, if you're using WindowsAuth + LongPolling then it always will hit that (until we fix it).

Much appreciated.

> On a related note, Blazor generally works better with WebSockets (less latency) and it also wont hit the WindowsAuth issue. You should consider enabling WebSockets in IIS.

Interesting! I checked our new server configuration. We missed to install WebSockets server role but we did had on older server. Thank you for suggestion. I'll certainly install WebSockets on IIS.

**Comment by roysurles** [comment]
Thanks @BrennanConroy for the workaround... it is working for us here.  Thanks @SteveSandersonMS for the code review & tip on ConfigureAwait.  Thank you all for your help with this.
