### ISSUE TITLE
Identity.UI is asking the user to register after Microsoft Authentication the second time and fails

### ISSUE THREAD

**Issue by JohanOtto** [dotnet/aspnetcore#18567]
### MS Authentication Integration issue with MS Identity
![Bug](https://user-images.githubusercontent.com/2878264/73100717-1d9fb100-3ebc-11ea-9524-c1bf97f3d47c.jpg)

Hi I'm using Microsoft authentication as an external login mechanism. A number of users are getting this issue. They log in using the Microsoft button which kicks off the auth process with MS and then it comes back to the attached pages and ask them to register. The first time it works - a week later they follow the same process and again this form appears only this time telling them the email already exists. This is a fundamental problem and I believe it's in MS Identity 

### To Reproduce
I'm unable to reproduce this effectively in the development environment. It seems its an intermittent bug.

In Startup.cs add the MS authentication
``` C#          services
                .AddAuthentication()
                .AddMicrosoftAccount(microsoftOptions =>
                {
                    microsoftOptions.ClientId = Configuration["Authentication:Microsoft:ClientId"];
                    microsoftOptions.ClientSecret = Configuration["Authentication:Microsoft:ClientSecret"];
                });
```

### Further technical details
- ASP.NET Core version 3.0 and 3.1

**Comment by blowdart** [comment]
This is by design. You don't register twice.

**Comment by JohanOtto** [comment]
Hey sorry - this is just IT guys - it shouldn't register twice but CLEARLY is does
