### ISSUE TITLE
.Net Core 3.1 - Unit Test failed in GitLab Runner(Linux) works in local windows - mongo2go directory notfound

### ISSUE THREAD

**Issue by martinsubash** [dotnet/aspnetcore#18577]
# Issue Title

After migrate to .Net core 3.1 the **NUnit** test with **mongo2go** run in local(Windows machine) but failed in gitlab runner(Linux).

# General

The below are the error from the gitlabci pipeline:

```
X GetAll_ReturnsEmptyResultOnEmptyCollection [< 1ms]
190   Error Message:
191    OneTimeSetUp: System.IO.DirectoryNotFoundException : Could not find a part of the path '/builds/testproj/testproj-mytest/Test/~/.nuget/packages'.
192 SetUp failed for test fixture Test.MongoDBStorage.MongoDbRepositoryTest
193 System.IO.DirectoryNotFoundException : Could not find a part of the path '/builds/testproj/testproj-mytest/Test/~/.nuget/packages'.
194    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
195    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
196    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
197    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
198    at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
199    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
200    at Mongo2Go.Helper.FolderSearch.FindFolder(String startPath, String searchPattern)
201    at Mongo2Go.Helper.MongoBinaryLocator.FindBinariesDirectory(IList`1 searchDirectories)
202    at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory()
203    at Mongo2Go.Helper.MongoBinaryLocator.get_Directory()
204    at Mongo2Go.MongoDbRunner.MakeMongoBinarysExecutable()
205    at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet)
206    at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet)
207    at Test.MongoDBStorage.MongoDbTestBase.TestSetup() in /builds/testproj/testproj-mytest/projects/backend/src/Product.Test/MongoDBStorage/MongoDbTestBase.cs:line 17
```
**The below are the used DLL Versions**

    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.1.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="Mongo2Go" Version="2.2.12" />
    <PackageReference Include="NSubstitute" Version="3.1.0" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />

.gitlabci.yml commands:

dotnet restore "testproj.sln" -r win-x64 
dotnet build -c Release --no-restore 
dotnet test -c Release --no-build --no-restore

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear how this is related to the ASP.NET Core framework.
If this is a behavior change you're observing after upgrading your application from an earlier version of ASP.NET Core (2.2 or below) then you most probably are impacted by one or more of the breaking changes introduced in 3.0. To make sure you migrate your application properly, consider following the migration guide available at: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio
