### ISSUE TITLE
SignalR DefaultHubLifetimeManager does not populate _connections field

### ISSUE THREAD

**Issue by StanislavChankov** [dotnet/aspnetcore#18575]
### Describe the bug
We have a RabbitMQ receiver, which handler is sending messages to the clients through `IHubContext<THub>`. The messages aren't sent at all. Even when `EnableDetailedErrors = true;` no errors are shown.
Debugging the DefaultLifetimeManager and checking _connections field in both scenarios.
In the working scenario `_connections` field is populated with the expected connections. 
Not working scenario, where the code starts from RabbitMQ receiver - `_connections` are always empty - no connections at all. Thats the issue obviously that causes no messages to be send.

The same code is tested and works with a common request pipeline. In the working scenario the request starts from a Api Controller.

Not working scenario:
![image](https://user-images.githubusercontent.com/35253870/73118167-41650480-3f59-11ea-8bcf-d3811e40f57c.png)

Working scenario:
![image](https://user-images.githubusercontent.com/35253870/73118336-90ac3480-3f5b-11ea-93a0-99fe9f144a45.png)

My hypothesis is that SignalR creates its own "request" scope, but in this case not created, since the RabbitMQ handler does not pass through the common request pipeline and SignalR are not aware of this and therefore does not resolve `DefaultLifetimeManager._connections`.

I guess the issue relates to:
https://github.com/dotnet/aspnetcore/issues/13200

and

https://github.com/dotnet/aspnetcore/blob/0d02d7a7051edebf24fc2ba92d0172f741f53455/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L218

### To Reproduce

Create some lambda function with handler, which does not starts from the request pipeline and send a message to some hub with connections.

### Further technical details
- ASP.NET Core version
`netcoreapp3.1` -  tested on `netcoreapp3.0` as well.
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/35253870/73118469-357b4180-3f5d-11ea-9ca8-f9fc60f9db23.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`Visual Studio 2019`
`Version 16.4.2`

**Comment by davidfowl** [comment]
Can you provide a running sample of the application? I'm assuming it's a single server and a single client being tested?

**Comment by anurse** [comment]
As @davidfowl said, we need a runnable sample (including your RabbitMQ receiver) so that we can get the full context on what could be going on here.

**Comment by StanislavChankov** [comment]
The issue was related to the usage of the Dependency Injection Container and how `IHubContext<T>` instances are resolved.
By default ASP.NET Core is registering all of the `IHubContext<T>` as `Singleton` lifetime scope. That was the first thing that we didn't know.
The real problem was in this how `BuildServiceProvider` is called. Calling `BuildServiceProvider` to the `IServiceCollection` is creating new DI Container instance with completely new scope and overrides the registered Singleton instances - `IHubContext<T>` in our case. Which results in resolving new instances compared to the those ones that the application initially created.

The issues was resolved by replacing the usage of `BuildServiceProvider` with `serviceProvider.CreateScope()`.

Hope this will be useful for somebody with the same issue.
Thank you.

**Comment by anurse** [comment]
Ok, closing as it appears there is no further action from the team needed here.
