### ISSUE TITLE
SignalR and Windows Authentication / Kerberos in AWS

### ISSUE THREAD

**Issue by johnnyreilly** [dotnet/aspnetcore#18576]
**Is your feature request related to a problem? Please describe.**

Hey all,

Amazing work on SignalR! I'm dropping you a line as I've recently encountered a **hard problem**.

Hand on heart, I don't know how to solve it. I'm no expert on Auth but I have a feeling that I'm not the first to encounter this. I don't know for sure if I'm even asking good questions, but I thought I'd try. If I'm wasting your time please do forgive me.

Here's the situation: I have an ASP.Net Core 3.1 application which runs in docker + kubernetes on AWS. We've a need to connect our application to a SignalR hub that is hosted on an on-premise server. Our cluster has access to the on-premise network + server. However, that hub is secured via Windows Authentication. (A specific service account is permissioned to use it.) It would be amazing if that SignalR hub supported other Auth but alas that's not the case.

**Describe the solution you'd like**

So we've been wondering if there's a way to combine SignalR and Kerberos.Net to do this. Or if there's another way that we haven't happened upon yet. It's possible this is already feasible, but despite much searching I haven't found an example of someone doing this.

I'm wondering if this is possible? Again, apologies for a random question from out of the blue. I'm an open source maintainer myself and I know that your time isn't free. If you're able to spend some time answering this that would be amazing. No sweat if not.

I've raised a similar question against the Kerberos.Net project too: https://github.com/SteveSyfuhs/Kerberos.NET/issues/129

**Comment by blowdart** [comment]
Windows authentication / kerberos authentication is meant for intranet environments, not for the cloud. I don't believe you'd be able to get a kerberos ticket unless your AWS site had access to your domain controller. @stevesyfuhs can tell me how horribly wrong I am though :)

**Comment by johnnyreilly** [comment]
Thanks for responding @blowdart.

> unless your AWS site had access to your domain controller. 

My understanding is that this may be the case. (I'm *so* not an expert in this domain it's untrue 😄) I say that as we're able to access our on premise network resources such as databases / APIs. Up until now we've been able to tackle these with username / passwords / tokens. It's the first time we've been faced with attempting to authenticate via a service account.

You know when you'd have a website in IIS with an Application Pool set to the identity of a an Active Directory account (your "service" account). That's the behaviour we're trying to emulate.

**Comment by SteveSyfuhs** [comment]
Barry is not wrong. The calling party, your AWS site, needs a user-like cred and line of sight to a domain controller to request a ticket. Once it has a ticket it can just send it to SignalR and everything works as normal. However if I'm reading this right your AWS cluster _has_ line of sight so it's just a matter of using a kerb client to get the ticket. The kerb.net KerberosClient can certainly do that if you want.

var client = new KerberosClient();

var kerbCred = new KerberosPasswordCredential("user@domain.com", "userP@ssw0rd!");

await client.Authenticate(kerbCred);

var ticket = await client.GetServiceTicket("http/yoursignalr.app.com");

You say Kub on AWS so presumably that's NOT  Windows hosts, which means you're limited to MIT or Heimdal libs if you need native support. There's docs around somewhere for configuring MIT. If you do use kerb.net you'll find it won't work if you haven't enabled AES on the AWS user account. Go enable it in ADAC and rotate the password.

This gets a lot more complicated if in all this you're also trying to do delegation, but not impossible.
________________________________

**Comment by johnnyreilly** [comment]
Hey @SteveSyfuhs - thanks so much for responding!  I really appreciate it. That's two amazing people responding on one GitHub issue; wow!

> You say Kub on AWS so presumably that's NOT  Windows hosts

Exactly right!  I've written some code like your example: 

```cs
var client = new KerberosClient();
var kerbCred = new KerberosPasswordCredential("user@domain.com", "userP@ssw0rd!");
await client.Authenticate(kerbCred);
var ticket = await client.GetServiceTicket("http/yoursignalr.app.com");
```

I'm successfully requesting a ticket when I run locally on Windows.  I can test it in k8s on Monday.  (With a little help from a marvellous friend who knows more about the networking side that I do.)

> Once it has a ticket it can just send it to SignalR and everything works as normal.

Would you be able to expand upon this a little please?  What I mean is, if we were deployed on IIS running as our service account we'd be able to connect something like this:

```cs
            var connection = new HubConnectionBuilder()
                .WithUrl("https://heres.our.server.com/hub/by", options =>
                {
                    options.UseDefaultCredentials = true;
                })
                .Build();
```

Is there a way to attach Kerberos credentials to that connection? I haven't stumbled upon any docs that describe that. 

Thanks again for your time!

**Comment by blowdart** [comment]
There's no support in Core for making a kerb credential like this. That would be a questions for the .net core repo, rather than asp.net, but right now the only plans for kerb are extending it out to get groups and things.

**Comment by johnnyreilly** [comment]
Oh no! Does this mean I can authenticate but then can't actually use that when I work with SignalR?

**Comment by blowdart** [comment]
That'd be the place. And yea, it looks like you can't do what you want. 

Have you considered using ADFS in your domain, and the OIDC service to service? You'd get a JWT that way, and better still you can host way more things in whatever cloud you wish and have auth to your corporate domain. Although obviously you should use Azure as it pays my salary ;)

**Comment by SteveSyfuhs** [comment]
Assuming you can convert it to a higher stack protocol, that might make things easier. That's obviously a non-trivial solution though.

As Barry says you can't load in a ticket per-se. You would need to manage the

Authorization: negotiate <ticket>

header on your own, but that's not rocket science. What you will need to do is call the EncodeGssApi() method to get a nego ticket (easier to use APIs TBD).

________________________________

**Comment by johnnyreilly** [comment]
> Have you considered using ADFS in your domain, and the OIDC service to service? 

@blowdart I'll talk to our DevOps team and see what they say. We use Azure AD already so maybe that's possible?

**Comment by johnnyreilly** [comment]
@SteveSyfuhs 

> As Barry says you can't load in a ticket per-se. You would need to manage the
>
> `Authorization: negotiate <ticket>`
> 
> header on your own, but that's not rocket science. What you will need to do is call the `EncodeGssApi()` method to get a nego ticket (easier to use APIs TBD).

This sounds like something worth exploring! I'm imagining that possibly the approach detailed [here](https://github.com/aspnet/SignalR/issues/769#issuecomment-334889576) could be adopted and tweaked to this end perhaps?

```cs
var httpHandler = new WrappedHttpMessageHandler();
var connection = new HubConnectionBuilder()
.WithUrl("https://site.name.com")
.WithMessageHandler(httpHandler)
.Build();

private class WrappedHttpMessageHandler : HttpClientHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // Maybe the `Authorization: negotiate <ticket>` can be handled in here somehow?

        var response = await base.SendAsync(request, cancellationToken);

        return response;
    }
}
```

Are you aware of any example code out there that does this:

> What you will need to do is call the `EncodeGssApi()` method to get a nego ticket 

By the way, I write a [tech blog](https://blog.johnnyreilly.com/); if we can work out a way to do this I'll definitely plan to write this up so that others can get the benefit as well. I'd lay good money that in enterprise companies the world over there's developers banging their head against this particular wall 😄

**Comment by blowdart** [comment]
@johnnyreilly If you're on Azure AD anyway .. there is [service to service](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow) auth, but you'd need to have line of site to the Azure AD too. Which may well mean hosting in azure itself, although I'm not 100% on that.

**Comment by johnnyreilly** [comment]
Thanks @blowdart - hopefully that's not the case as we're hosting in AWS (sorry!) But if not that could be another possibility to investigate 🤗
