### ISSUE TITLE
Make it trivial to launch a Helix run of any test project

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#18582]
I’d like it to be easy for any dev to launch any test project in Helix and be able to see their data in Helix (and any other dashboards we create).

I managed to figure out how to do it with some environment variable hacks but I think we can do a little better :). Mostly it’s just `dotnet msbuild -t:Helix` but it seems to want AzDO variables like `BUILD_SOURCEBRANCH` and I’d like to see if we can avoid people having to hack those vars in :).

**Comment by anurse** [comment]
cc @HaoK

**Comment by HaoK** [comment]
Yeah this used to just work, but something changed

**Comment by anurse** [comment]
@BrennanConroy did this. See https://github.com/dotnet/aspnetcore/blob/master/docs/Helix.md
