### ISSUE TITLE
Blazor component not work in ASP.NET Core MVC when I return it a few times

### ISSUE THREAD

**Issue by denmaklucky** [dotnet/aspnetcore#18588]
I have a project ASP.NET Core MVC. This project contains two controllers: Home and Movie. In HomeController I have action which return View like:

```HTML
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "Online Cinema";
}

<div class="row p-2">
    @foreach (var movie in Model)
    {
        <component type="typeof(MovieComponent)" render-mode="ServerPrerendered" param-Model="movie" />
    }
</div>
```
And in MovieController I have some action which return View like this:

```HTML
@model IEnumerable<Movie>

@{
    ViewData["Title"] = $"Online Cinema - {ViewBag.Title}";
}

<div class="row p-2">
    @if (Model.Count() == 0)
    {
        <span>Sorry! We haven't this type of films!</span>
    }
    else
    {
        @foreach (var movie in Model)
        {
            <component type="typeof(MovieComponent)" render-mode="ServerPrerendered" param-Model="movie" />
        }
    }
</div>
```

When I return View from HomeController It's ok. Blazor component work, but when I return View from MovieController Blazor component isn't work.

In browser I found this 

![изображение](https://user-images.githubusercontent.com/8844526/73134442-9ed77f00-4047-11ea-9235-45bc0f861a33.png)

I use .Net Core 3.1.100
[GitHub repository](https://github.com/denmaklucky/Examples/tree/master/OnlineCinema)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like you're missing the `<base>` url in the Layout file: https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/pages-routing-layouts#base-urls
That should help.
