### ISSUE TITLE
Replace calls to buffer.First.Span with buffer.FirstSpan

### ISSUE THREAD

**Issue by NRKirby** [dotnet/aspnetcore#18587]
### Is your feature request related to a problem? Please describe.

This isn't a problem. I see there are statements in the source code where `.First.Span` is called on a `ReadOnlySequence`, such as [here](https://github.com/dotnet/aspnetcore/blob/116799fa709ff003781368b578e4efe2fa32e937/src/Servers/Kestrel/Core/src/Internal/Http/HttpParser.cs#L43).

### Describe the solution you'd like

Would you accept a PR replacing these with the `FirstSpan` method? I have done this in a commit [here](https://github.com/NRKirby/aspnetcore/commit/b26a15e41dffde280cd0b7ca0f0c790aed597f9d) and I'll start a PR if you'll accept it.

**Comment by anurse** [comment]
> Would you accept a PR replacing these with the `FirstSpan` method?

Yes! Certainly! Go right ahead :).

**Comment by NRKirby** [comment]
Can this be closed now as it was merged in [this PR](https://github.com/dotnet/aspnetcore/pull/18615)

**Comment by anurse** [comment]
Yep. Thanks for the contribution!
