### ISSUE TITLE
WASM 3.2 & Azure B2C integration

### ISSUE THREAD

**Issue by BenHayat** [dotnet/aspnetcore#18589]
There was a time where I was using Vue as the Frontend, WebAPI as backend and Google's Firestore and it's authentication system & DB.

Google had offered one of the best implementation and integration of **Client JS via it's SDK**. The SDK offered a simple yet powerful methods to authenticate a user and work with backend API. The whole cycle was very smooth to program as they provided lots of functions backed into the SDK.

I'm hoping Blazor team, will provide such SDK with Blazor WASM 3.2 using Azure B2C. 
Can we expect such a seamless integration to use Azure B2C with Server & Client side Blazor for version 3.2?
Thanks!
..Ben

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We plan to provide an auth-enable template with Azure B2C integration as part of https://github.com/dotnet/aspnetcore/issues/17014

**Comment by BenHayat** [comment]
Thanks for good news.
