### ISSUE TITLE
Migrating custom routing to endpoints

### ISSUE THREAD

**Issue by knyzorg** [dotnet/aspnetcore#18583]
Since the removal of IRouter-related features, how can I reproduce the behaviour described here: https://github.com/aspnet/Routing/issues/823 ?

I am currently trying to figure out how to do it with `IOutboundParameterTransformer` but the fundamental limitation seems to be that it does 1-to-1 matches, while I need multiple action names to match the same action.

Fundamentally, I am looking for two specific behaviours: Altering the route data when links are generated, and altering the route data when a route has been matched in order to replace translated elements back to their proper values for internal processing.

These two behaviors used to be handled by `Route.GetVirtualPath` and `Route.OnRouteMatched`, for which support had been removed: [the endpoint routing system doesn't support IRouter-based extensibility, including inheriting from Route.](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#endpoint-routing-differences-from-earlier-versions-of-routing)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @knyzorg.
@javiercn can you please look into this? Thanks

**Comment by knyzorg** [comment]
I have resolved this issue by inspecting the `HttpContext` to identify the language using DI (#4579) and could match up the routes using `IOutboundParameterTransformer`.

I will eventually clean up the implementation and post it here.

I hit a bug in the process however, the `action` part of the route (and probably `controller` too) seem to only be evaluated once. That is if the first page that gets loaded converts "Home" to "Acceuil", all subsequent pages will do the same by virtue of not checking.

The router is making false assumptions here.

**Comment by mkArtakMSFT** [comment]
>I hit a bug in the process however, the action part of the route (and probably controller too) seem to only be evaluated once. That is if the first page that gets loaded converts "Home" to "Acceuil", all subsequent pages will do the same by virtue of not checking.
> 
> The router is making false assumptions here.

Thanks for the details, @knyzorg.
@javiercn is this expected?
