### ISSUE TITLE
Static Files not found when hosting Blazor server app on Linux

### ISSUE THREAD

**Issue by SteveTeece** [dotnet/aspnetcore#18591]
### Describe the bug
After publishing a Blazor server app, static files and resources (e.g., site.css or favicon.ico) are not found on the web server.  Browser returns Not Found error for static files.  SignalR connection is running, and site is being served, but no CSS styling, and no other static files (images) are found.

Manual copy of contents of wwwroot folder in project to the folder on the server containing the app makes no difference to outcome.

**NOTE**
This app is intended to run in an isolated network, and has no connection to the internet, so security issues are not a concern.

Application runs perfectly when running through Visual Studio.

### To Reproduce
Create a Blazor Server app using the default server app template. Make NO changes. Publish to an 
 Ubuntu 18.04 linux server runing Nginx.  Browse to the site.  CSS and images are not loaded.

Program.cs
``` C#
public static class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStaticWebAssets();
                    webBuilder.UseStartup<Startup>();
                });
    }
```

Startup.Configure.cs
```C#
public static void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            
            app.UseStaticFiles(); // This line was moved to be first to aid debugging
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            // Enable SyncFusion Community Edition License
            Syncfusion.Licensing.SyncfusionLicenseProvider
                .RegisterLicense("Key removed");

            //app.UseHttpsRedirection();

            app.UseRouting();

           
            // Use Authentication and Authorisation providers in the application
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
```
Kestrel service configuration file (on Ubuntu Linux 18.04)

```
[Unit]
Description=TheLab Grafton .NET Core 3 Razor management application

[Service]
WorkingDirectory=/var/www/lab
ExecStart= /usr/bin/dotnet /var/www/lab/Lab.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=dotnet-lab
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Development (NOTE: Staging and Production also tried)

[Install]
WantedBy=multi-user.target
```

Nginx Server block:
```
server {
  listen 80;
  listen [::]:80;

  server_name www.grafton.internal;

  location / {
    proxy_pass http://localhost:5000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header   Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
  }
}
```
Complete repository for code is located at https://github.com/SteveTeece/Lab

Output from Edge Developer Tools (text formatted):
```
Failed to load resource: the server responded with a status of 404 (Not Found)
site.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
LabLogo.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
site.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
blazor.server.js:1 [2020-01-27T01:30:30.203Z] Information: Normalizing '_blazor' to 'http://www.grafton.internal/_blazor'.
blazor.server.js:1 [2020-01-27T01:30:30.386Z] Information: WebSocket connected to ws://www.grafton.internal/_blazor?id=AAihsX1-US7JxAl-cETZ6w.
LabLogo.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
site.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

### Further technical details
- ASP.NET Core version - 3.1.101 (running on Ubuntu Linux 18.04LTS)
- Include the output of `dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:
VS 16.4.3 Community Edition running on Windows 10 version 2004 (Build 19041.21)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SteveTeece .
Are you sure this is not a misconfigured NGINX server? Blazor does nothing special for the static files to work.
@sebastienros do you have any pointers to how to properly configure an app to work with NGINX?

**Comment by sebastienros** [comment]
Can you access the static files when you point directly to the web app, not through nginx?
Can you enable http request console logging to be sure the server is actually receiving the request?

**Comment by SteveTeece** [comment]
@mkArtakMSFT  - I have followed the setup/config documents at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1 to the letter when setting up the Nginx config.  I have also duplicated the "failure" with an "out of the box" Blazor server template provided by visual studio - just compile, then publish (either via FTP or File Deployment).

@sebastienros - I have attempted to copy the contents of the WWWRoot folder from the project source code to the appropriate folder on the linux server, and cannot access the files.  The Developer Tools window in Edge and Chrome both indicate the request is being received by the server, but the files cannot be found to be served.

I am happy to turn on HTTP Request logging for more info if someone can let me know how exactly to do that...

**Comment by sebastienros** [comment]
> The Developer Tools window in Edge and Chrome both indicate the request is being received by the server

The NGinx server, maybe not the Kestrel one, which is why enabling logging would tell us more.

**Comment by SteveTeece** [comment]
@sebastienros - Attached is the Nginx error log from yesterday (27Jan20). I hope this is the log you requested.


[access.log.zip](https://github.com/dotnet/aspnetcore/files/4119851/access.log.zip)

**Comment by SteveTeece** [comment]
I've located the error in a linux shell script that was refusing to copy the wwwroot folder from the app publish folder.

This is now working exactly as expected.  Thank you for your assistance and my apologies for an incorrect bug report.
