### ISSUE TITLE
Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3] Failed to determine the https port for redirect.

### ISSUE THREAD

**Issue by xshiiiidev** [dotnet/aspnetcore#18594]
### Describe the bug
I am getting this error on my production server after accessing the website for the first time after deploying this error will show

> Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3] Failed to determine the https port for redirect.

I am not getting this error on my kestrel web server on development.

BTW my production server is
NginX
Ubuntu18.04

Visual Studio Version: 2019 16.4.3
Dotnet Info on production server:

>   It was not possible to find any installed .NET Core SDKs
>   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
>       https://aka.ms/dotnet-download
> 
> Host (useful for support):
>   Version: 3.1.1
>   Commit:  a1388f194c
> 
> .NET Core SDKs installed:
>   No SDKs were found.
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

To reproduced:
Create new MVC ASP.NET Core 3.1 Project
Use this command to publish
`dotnet publish --configuration Release`

Copy the published files to the server

**Comment by blowdart** [comment]
Do you have the site configured with an HTTPS certificate? Can you share your program.cs?

**Comment by Tratcher** [comment]
NginX is terminating your TLS in a separate process and forwarding to Kestrel without TLS, correct? In that case the https redirect middleware can't detect at startup which port your nginx TLS is listening on. Locally when you run Kestrel directly it has its own TLS and the middleware can detect the port.

See https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#port-configuration to set the port manually.

**Comment by xshiiiidev** [comment]
> 
> 
> Do you have the site configured with an HTTPS certificate? Can you share your program.cs?

This is it

`public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }`

**Comment by xshiiiidev** [comment]
@Tratcher 

As per this document 

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio

![image](https://user-images.githubusercontent.com/19402130/73242279-87cb9500-41df-11ea-97d6-2793f12e9cd4.png)

I disabled my UseHttpsRedirection middleware

Because I already handled the https redirection in my nginx server.

The warning goes away now.

My only concern if this is a security issue disabling this middle ware through my app ?
But I am handling the redirect to nginx server.

**Comment by jkotalik** [comment]
I don't think you should be setting the port at all. If Nginx is doing TLS termination, every time your site gets a url, it will be on HTTP. The HttpsMiddleware will notice that it is HTTP and because a port is now set, it will redirect. This will constantly happen until the browser notices you have too many redirects, which is the behavior you are seeing. I'd remove the HTTPS_PORT and/or the HttpsRedirection middleware if you know your application is deployed where TLS termination is done. 

> My only concern if this is a security issue disabling this middle ware through my app ?

It depends on if you are concerned about the communication between nginx and kestrel using HTTP instead of HTTPS. That is based on your configuration. If it's only on a single machine (localhost), then you should be okay.

**Comment by Tratcher** [comment]
> My only concern if this is a security issue disabling this middle ware through my app ?
> But I am handling the redirect to nginx server.

That's fine.

@jkotalik @xshiiiidev read https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1 that covers how to set up your app and proxy so that the app knows the request was originally https.
