### ISSUE TITLE
MaxLength and StringLengh attribute is adding maxlength html attribute to the input field.

### ISSUE THREAD

**Issue by abdul-wasey** [dotnet/aspnetcore#18607]
# Model Validations Behavior

Be as descriptive as you can with your title.

# General

I am using .net core 3.1 version and try to validate my model data , I am new with net core, so i am confused about the behavior of Model Validation Behavior.
Confusion is that Error Message for Required Attributes are working fine but not showing of Attribute MaxLenght Error Message at the Client Side. 

And it also forces me to put not more than 30 characters in the Name field,
Please tell me where I am Mistaken

Here is my model

```cs
public class Employee
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(30, ErrorMessage = "Name length can't be more than 30 characters.")]
        public string Name { get; set; }

        [Required]
        public string Designation { get; set; }

        [Required]
        public Dept? Department { get; set; }
    }
```

**Comment by pranavkm** [comment]
MVC will render a [`maxlength` HTML attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#htmlattrdefmaxlength) for input types that support it (see the linked documentation). Unfortunately there isn't a very good way to turn the behavior off.

**Comment by abdul-wasey** [comment]
> MVC will render a [`maxlength` HTML attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#htmlattrdefmaxlength) for input types that support it (see the linked documentation). Unfortunately there isn't a very good way to turn the behavior off.

but how can I prevent this behavior ? I want to show validation message for maxlength to end user, 
I think that it will be possible from javascript code ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will bring back the options during 5.0.
For now you can set the `maxlength` attribute in the input tag-helper to some larger number, which will override the current default (30 in your case).

**Comment by pranavkm** [comment]
Copying my response from the other thread - in the meanwhile, you could use JavaScript to get the pre 3.0 behavior:

```JS
 document.addEventListener("DOMContentLoaded", function(){
        for (const item of document.querySelectorAll('input[maxlength][data-val-maxlength]')) {
         item.removeAttribute("maxlength");
       }
    });
```

**Comment by abdul-wasey** [comment]
> ```js
> addEventListener
> ```

Thank you
