### ISSUE TITLE
Reenable ComponentsAnalyzer

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#18611]
The ComponentsAnalyzer is being skipped currently due to a bug where some apps can't run in the repo. This is tracking reenabling the analyzer once the SDK is updated.
https://github.com/dotnet/aspnetcore/blob/547350002a1e5d9d705602bbba0158a72996bad9/Directory.Build.props#L34-L35

**Comment by TanayParikh** [comment]
> The ComponentsAnalyzer is being skipped currently due to a bug where some apps can't run in the repo. This is tracking reenabling the analyzer once the SDK is updated.
> 
> https://github.com/dotnet/aspnetcore/blob/547350002a1e5d9d705602bbba0158a72996bad9/Directory.Build.props#L34-L35

@BrennanConroy do you know if this is still an issue, or can the ComponentsAnalyzer be re-enabled?
