### ISSUE TITLE
Windows Installers: Cannot resolve targets for wixproj files

### ISSUE THREAD

**Issue by M-Schiller** [dotnet/aspnetcore#18619]
### Describe the bug
MSBuild can't resolve (default?) targets, e.g. `Build`, `ReBuild`, for \*.wixproj files using **no** local WiX toolset installation. 
Looking at the Wix*.nupkg to be downloaded and the WiX property sheets, it should not be necessary to have a local installation of the WiX toolset prior to building. I think that references to WiX aren't resolved yet when the remaining projects are built 

### To Reproduce
I followed the the [Build from Source guide](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md), installed all the prerequisites, adapted a pre-existing VS2019 installation, installed node, and the JDK (using the PowerShell script).

Afterwards, I called `restore.cmd`, let it run - 0 warnings, 0 errors.
Then, I opened Windows Installers solution as `startvs.cmd src/Installers/Windows/Installers.sln`, selected "Release|x86" and hit "Rebuild" on the solution. 
Now, some of the projects, i.e. iiscommon.lib and and iisca.lib built but for the WiX project "SharedFramework" I got the error message
`The target "Rebuild" does not exist in the project.`

Besides, possibly related: Visual Studio cannot load the setup projects `AncmIISExpressV2.wixproj` and `AncmV2.wixproj`. Both projects result in the message
`error  : Unrecognized Guid format.`

### Further technical details
- ASP.NET Core version
branch: `master`, commit: `ebb2656e3ea4dd5199fb63925c6e14e99e432399`
- Include the output of `dotnet --info`

A compatible installed .NET Core SDK for global.json version [5.0.100-alpha.1.20063.3] from [C:\Dev\aspnetcore\global.json] was not found
Install the [5.0.100-alpha.1.20063.3] .NET Core SDK or update [C:\Dev\aspnetcore\global.json] with an installed .NET Core SDK:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio Enterprise 2019 Version 16.4.3

**Comment by jkotalik** [comment]
Honestly, I didn't even know we had a sln in that folder for installers. We don't actually build via the sln, we usually invoke build.cmd/build.ps1/build.sh. Can you try running the root build.cmd with the flag -BuildInstallers? Let us know if that works.

**Comment by M-Schiller** [comment]
It fails differently now. 

```
Build FAILED.

C:\Dev\aspnetcore\src\Installers\Windows\TargetingPack\TargetingPack.wixproj(67,5): error : MSB3932: Failed to unzip file "C:\Dev\aspnetcore\artifacts\installers\Debug\asp
netcore-targeting-pack-5.0.0-dev.zip" because the file does not exist or is inaccessible.
C:\Dev\aspnetcore\src\Installers\Windows\TargetingPack\TargetingPack.wixproj(67,5): error : MSB3932: Failed to unzip file "C:\Dev\aspnetcore\artifacts\installers\Debug\asp
netcore-targeting-pack-5.0.0-dev.zip" because the file does not exist or is inaccessible.
C:\Dev\aspnetcore\src\Installers\Windows\SharedFramework\SharedFramework.wixproj(70,5): error : MSB3932: Failed to unzip file "C:\Dev\aspnetcore\artifacts\installers\Debug
\aspnetcore-runtime-internal-5.0.0-dev-win-x64.zip" because the file does not exist or is inaccessible.
C:\Dev\aspnetcore\src\Installers\Windows\SharedFramework\SharedFramework.wixproj(72,5): error : MSB3932: Failed to unzip file "C:\Dev\aspnetcore\artifacts\installers\Debug
\aspnetcore-runtime-internal-5.0.0-dev-win-x86.zip" because the file does not exist or is inaccessible.
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:03:05.31
(NETCORE_ENGINEERING_TELEMETRY=Category) Build failed.
build.cmd completed
```

These three artifacts seem to be missing locally (I ran clean, then restore and then `build.cmd -BuildInstallers`):
* aspnetcore-targeting-pack-5.0.0-dev.zip
* aspnetcore-runtime-internal-5.0.0-dev-win-x64.zip
* aspnetcore-runtime-internal-5.0.0-dev-win-x86.zip

**Comment by dougbu** [comment]
The `*.wixproj` projects are not intended to be build within any `*.sln` in the repo. In fact we now have a single solution file for the entire repo and that doesn't contain any of these projects. This makes sense because the projects depend on both x86 and x64 packages already existing in the repo.
