### ISSUE TITLE
Signalr: Possibility to dynamically set the name of the hub

### ISSUE THREAD

**Issue by JonnyMattsson** [dotnet/aspnetcore#18617]
We have a setup of multiple web applications(api, frontend) where each instance is dedicated to a customer. So we are running the same code in multiple web apps.
We are implementing signalr(azure signalr service) but due to the cost(some customer are really small) we would like to share signalr instance.
As far as I know it is not possible to create client specific hubs since the hubname is taken from the hubclass and that class will be same on all instances.

We would like to name the hub dynamically. If my google skills are great that was possible in the old(pre core) version with an attribute. So a way to dynamically set the name of the hub is the feature we are looking for so that we could name the hub for example like this [customername]-notifications. By dynamically I mean it needs to be possible to set it runtime, for example taken from an environment variable.

**Comment by anurse** [comment]
This isn't something we intend to support in SignalR. Hubs aren't designed as a tenant boundary. If you want to support multi-tenancy, you should do that within the hub (such as by the user principal).

**Comment by JonnyMattsson** [comment]
For sending it is possible to send to a users, connections or a group. But its not possible to group things on disconnectionevent for example. So every instance will get notified.
This is a common scenario in the real world, so I hope you change your mind. Especially since it is most likely a really easy fix. You can already have multiple hubs, its just that they are named automatically.
