### ISSUE TITLE
Inconsistent behavior in ConnectionHandler

### ISSUE THREAD

**Issue by nihlaakram** [dotnet/aspnetcore#18614]
### Describe the bug
Application [1] inherits the **ConnectionHandler** to implement a TCP listener endpoint. The application was tested using multiple client tools, and the behavior of the **IsCompleted** property of the ReadAsync() of the Transport Input[4] was inconsistent. 

| Tool used for TCP request  | Result and findings |
| ------------- | ------------- |
| Hercules | Expected behavior. Echos back the request body  |
| Apache JMeter  | No response. request is hung. When debugged, [2] condition never results in true, hence the loop[3] is infinite   |

Is this the expected behavior of the ConnectionHandler ? Are we missing something? Appreciate your input on this.

[1] https://github.com/nihlaakram/WebApplication
[2] https://github.com/nihlaakram/WebApplication/blob/master/WebApplication/MyEchoConnectionHandler.cs#L26
[3] https://github.com/nihlaakram/WebApplication/blob/master/WebApplication/MyEchoConnectionHandler.cs#L16
[4] https://github.com/nihlaakram/WebApplication/blob/master/WebApplication/MyEchoConnectionHandler.cs#L18

### To Reproduce
Try out the above application with requests from the above mentioned tools.

### Further technical details 
- Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.0.100 [...]
  3.1.100 [...]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [...]
  Microsoft.AspNetCore.App 2.1.14 [...]
  Microsoft.AspNetCore.App 3.0.0 [...]
  Microsoft.AspNetCore.App 3.1.0 [...]
  Microsoft.NETCore.App 2.1.14 [...]
  Microsoft.NETCore.App 3.0.0 [...]
  Microsoft.NETCore.App 3.1.0 [...]
  Microsoft.WindowsDesktop.App 3.0.0 [...]
  Microsoft.WindowsDesktop.App 3.1.0 [...]
````
- The IDE : VS 2019

**Comment by jkotalik** [comment]
Initially, I would guess that the Hercules client is closing the connection after sending the input, while the Apache JMeter client isn't closing the connection. The IsCompleted property will be true when the connection closes, can you see what happens with other clients, like PostMan or cURL?

Other than that, I think your connection handler looks correct. Here is one we used for testing for comparision: https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/clients/ts/FunctionalTests/EchoConnectionHandler.cs

**Comment by nihlaakram** [comment]
Hi @jkotalik ,

Thank you for the prompt response. I tried out with Postman and cURL, the behavior was similar to that of Apache JMeters', where even when the message is completely received, the IsCompleted property is false.

So if IsCompleted refers to the connection status, is there any way to know the message completeion status for TCP requests?
