### ISSUE TITLE
IJSRuntime.Invoke throws TypeError: cyclic object value

### ISSUE THREAD

**Issue by davidkarlsson** [dotnet/aspnetcore#18628]
If you call a JS function with `IJSRuntime.Invoke` in Blazor that returns an object that contains circular references a type error will be thrown because `JSON.stringify` is called on the result when it is sent to `DotNetDispatcher.EndInvoke`: https://github.com/aspnet/Extensions/blob/3a884e2e1e6ae3f1fc4381fc8fbb428de5cff063/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L186

Can these type of data structures be serialized in a way that makes it possible to recover the references when the string is deserialized? Perhaps with Douglas Crockfords cycle.js?

I've tested this with .NET Core SDK 3.0.0-preview5-27626-15.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will look into this during our next sprint planning meeting and decide whether and when we can handle this.

**Comment by mkArtakMSFT** [comment]
After closer review of this it seems this is a limitation with the current System.Text.Json implementation, which is being tracked by https://github.com/dotnet/runtime/issues/30820
