### ISSUE TITLE
new feature to Merge two Asp.Net Core APIs in one application

### ISSUE THREAD

**Issue by alimhabib** [dotnet/aspnetcore#18626]
### Is your feature request related to a problem? Please describe.
I had to merge two APIs projects in one app, to do this I created a simple extension for IApplicationBuilder [Application Builder with Branches](https://github.com/alimhabib/ApplicationBuilderWithBranches.git)
Example. I'm am trying to do [...] but [...]

### Describe the solution you'd like

So the user can plugin n numbers of projects in one ( without repeating many codes) 
```
app.UseBranchWithServices("/admin" ,
                a => a.UseMvc();
                 , typeof( AdminWebApplication.Startup));
```

I wish this feature can ease the plugin of many MVC pipelines easily if it of valuable May I add it

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alimhabib.
This is not something we plan to make as part of the framework.
That said, this seems to be a great idea for a community project.
