### ISSUE TITLE
How to return data from Blazor JSInvokable method to triggered JS method as synchronous action

### ISSUE THREAD

**Issue by gurunathancs1991** [dotnet/aspnetcore#18629]
Am wrapping some existing JS plugins to blazor components. when doing so, i faced below issue.
i have a callback method, which has triggered from JS to blazor using dotnet reference -> `invokeMethodAsync`

`  this.dotnet.invokeMethodAsync("Trigger", this.eventName, '');`

it's perfectly triggers the `JSinvokable ` method. but here, i need to return the data from blazor source to JS function handler where it has been raised.

Instead `invokeMethodAsync`, tried `invokeMethod`, getting the below error 

https://github.com/aspnet/Extensions/blob/master/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L65

**whether it is possible to return data from event call back to JS function from where it has been raised as synchronous action?**

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by mrpmorris** [comment]
@mkArtakMSFT I don't think the DotNet object in javascript supports synchronous invoke, does it?

**Comment by mkArtakMSFT** [comment]
> 
> 
> @mkArtakMSFT I don't think the DotNet object in javascript supports synchronous invoke, does it?

Hope this helps: https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#invoke-net-methods-from-javascript-functions

**Comment by mrpmorris** [comment]
I was unaware of the InvokeMethodAsync function. Thanks!
