### ISSUE TITLE
In services.AddMVC(); JsonSerializerOptions.PropertyNamingPolicy is set as JsonNamingPolicy.CamelCase without any hint

### ISSUE THREAD

**Issue by lhrbu** [dotnet/aspnetcore#18623]
As Title, it may be a pitfall when try to deserialize the Json stream manually.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What type of `hint` are you referring to? You can always set this explicitly the way you want.

**Comment by lhrbu** [comment]
eh, I mean why not just leave the explicitly confiure codes as below in dotnet new project template, so that one can get the point without least superise.
`services.AddMvc().AddJsonOptions(options => 
                options.JsonSerializerOptions.PropertyNamingPolicy =JsonNamingPolicy.CamelCase);`

**Comment by mkArtakMSFT** [comment]
Thanks for the details. This is not something we plan to make the default.
We try to avoid adding default configuration to the Startup as that is unnecessary code and community in general likes the current pattern.
