### ISSUE TITLE
FR: DotNetObjectReference to expose C# methods

### ISSUE THREAD

**Issue by HughPH** [dotnet/aspnetcore#18627]
Current state:
DotNetObjectReference can be passed to JavaScript but still needs .invokeMethodAsync:
```javascript
function example(dotnetHelper) {
    return dotnetHelper.invokeMethodAsync('SayHello')
      .then(r => console.log(r));
  }
```

Desired state:
On the JavaScript side, add method stubs for the C# methods exposed by the type for which a DotNetObjectReference was created:
```javascript
function example(dotnetHelper) {
    return dotnetHelper.SayHello()
      .then(r => console.log(r));
  }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We would be happy to see the community to come up with a solution in this area.
