### ISSUE TITLE
Bug on the onclick event

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/aspnetcore#18620]
I have a blazor server side application(and gRPC server) that has a timer which is second by second updating a page variable with data(int variable) in a gRPC service variable, and makes an invoke state as changed afterwards. 
I have a button that is used to increment on the int variable gRPC client, that will get back later after some processing with the number after the increment.
In the button to make that call i placed  @onclick="IncrementNumber(item.Name)"
What happens is that the code is not triggred by the button click but by the timer invoke state changed that is called second by second. So i cannot use the button to increment the number, but the button click is some how being executed because the call is being made every second to the gRPC client that in turn is returning the updated number. This shouldn't occur. The onClick should only run with a click!

**Comment by Ricardoaraujo00** [comment]
Only way i got this to work:
`@onclick="()=> IncrementNumber(item.Name)" `

Without that anonymous function had to make a method that would return a EventCallback, but this way i don't have to. If the method didn't had a signature i could do it like int the button counter in the default template.
The method, just for exemplification.
```
public void IncrementNumber(string name)
    {
        jsRuntime.InvokeAsync<string>("console.log", "incrementing on  " + name);
        person.FirstOrDefault(x=>x.Name==name).ActualNumber = GreeterService1.IncrementNumber(name).Result;
    }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Ricardoaraujo00.
We're glad that you've found the error and fixed your code already.
Given that your example results in a compilation error, we don't think there is any other action for us to take here.
Event handlers take an event callback and Blazor knows how to convert a method group to an event callback. But when you add a parameter, you're now doing a method invocation, which is not returning an event callback and results in a compilation error.
