### ISSUE TITLE
Question: CORS client error in Blazor server-side with Azure AD B2C

### ISSUE THREAD

**Issue by sven5** [dotnet/aspnetcore#18622]
Hi, 

We have a Blazor server-side app with Azure AD B2C. When the user is not logged in we see errors in browser's console window:

```
Access to XMLHttpRequest at 'https://xxx.b2clogin.com/xxx.onmicrosoft.com/b2c_1_registration_signin/oauth2/v2.0/authorize?client_id=....&redirect_uri=....' (redirected from 'https://xxx.azurewebsites.net/_blazor/negotiate?negotiateVersion=1') from origin 'https://xxx.azurewebsites.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

blazor.server.js:1 [2020-01-28T12:39:17.779Z] Warning: Error from HTTP request. 0: .
e.log @ blazor.server.js:1
blazor.server.js:1 [2020-01-28T12:39:17.779Z] Error: Failed to complete negotiation with the server: Error
e.log @ blazor.server.js:1
blazor.server.js:1 [2020-01-28T12:39:17.780Z] Error: Failed to start the connection: Error
e.log @ blazor.server.js:1
blazor.server.js:15 [2020-01-28T12:39:17.780Z] Error: Error
e.log @ blazor.server.js:15
xxx.b2clogin.com/xxx.onmicrosoft.com/b2c_1_registration_signin/oauth2/v2.0/authorize?client_id=...&redirect_uri=
Failed to load resource: net::ERR_FAILED
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:1)
    at e.sendMessage (blazor.server.js:1)
    at e.sendWithProtocol (blazor.server.js:1)
    at blazor.server.js:1
    at new Promise (<anonymous>)
    at e.invoke (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:15)
    at blazor.server.js:15
    at Object.next (blazor.server.js:15)
    at blazor.server.js:15
```

It's a similar issue as here: https://stackoverflow.com/questions/54562349/cors-problem-with-b2c-and-azure-app-service

I already enabled CORS as [described in the docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-ui-customization-custom-dynamic#step-3-configure-cors-in-azure-app-service) but still the error comes up. The problem is, that the SignalR connection couldn't be established and so the Blazor app is not correctly bootstrapped.

However, after login everything works as expected.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@anurse is this some SignalR specific configuration missing here?

**Comment by anurse** [comment]
Yep, looks like a CORS issue. The reference to `Access-Control-Allow-Origins` indicates a likely problem with the config. 

@sven5 Can you provide a runnable sample app that reproduces the problem, or at least show your full CORS configuration? Also, can you capture a network trace using instructions in the [SignalR troubleshooting guide](http://aka.ms/aspnet/signalr/troubleshoot)?

**Comment by sven5** [comment]
@anurse 
I will try to create a runnable sample app tomorrow. 
Currently, I only created a CORS entry in my Azure App Service with allow-origins set to * . I haven't changed anything in `Startup.cs`.

**Comment by sven5** [comment]
Ok guys. Sorry for confusion, it was a mistake of me.
I tried to secure the blazor hub SignalR connection with `endpoints.MapBlazorHub().RequireAuthorization();`
I didn't consider the non-authenticated state (welcome page) of my app. And that was the source of this errors.

Regards
Sven

**Comment by anurse** [comment]
@sven5 Yep, I did receive your email, thanks! 

Yeah, if you're using an auth system that does redirection and sets cookies then you need to make sure the user is authenticated before they hit the SignalR connection (Blazor's server-side). So you need to make sure the main endpoint that serves the Host page **also** requires authentication.

The problem here is that SignalR's request to `/_blazor/negotiate` is being redirected to Azure AD B2C to prompt for login.

**Comment by multco-malan** [comment]
Hi anurse,
Would you be able to expand upon " So you need to make sure the main endpoint that serves the Host page also requires authentication."
Where would I be doing this?

thanks!
