### ISSUE TITLE
Response completion is inconsistent between NewtonsoftJsonOutputFormatter and SystemTextJsonOutputFormatter 

### ISSUE THREAD

**Issue by zvolkov** [dotnet/aspnetcore#18634]
On asp.net core 3.0 or 3.1 (when hosted either on Kestrel or on IIS In-Process), when NewtonsoftJsonOutputFormatter is used with default settings (SuppressOutputFormatterBuffering=false) the response is completed (from browser's perspective) as soon as ObjectResult finished executing, allowing browser to get the response before any middleware's "after next" logic (e.g. persisting the session state by SessionMiddleware) is fully done.

However, when the buffering is suppressed or when SystemTextJsonOutputFormatter is used, the response is NOT completed immediately after the result is serialized, which gives middleware a chance to run before the browser starts processing the response.

We suspect this is caused by explicitly setting Response.ContentLength in NewtonsoftJsonOutputFormatter which is only done when the buffering is enabled. (Confusingly, we also see the same behavior (early completion) in asp.net core 2.x, which uses JsonOutputFormatter, which does not set ContentLength)

This may be a bug or may be by design but at the very least we would like the exact reasoning/logic behind this behavior to be explained, so we can reason about it in our app design.

We are changing the controller's response in an action filter, and saving session state in a custom middleware, and we would like to know what's the right way to make the browser wait until our middleware is done-done, while still fully supporting ActionFilters.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @zvolkov.
Can you please share some more details about your scenario as well as a minimal repro application? Thanks!

**Comment by zvolkov** [comment]
Here is the repro app:
[FilterChainTest.zip](https://github.com/dotnet/aspnetcore/files/4141413/FilterChainTest.zip)

One of the middlewares has a Task.Delay of 1 second, you can see that response is returned to the browser before middleware completes. You can change appSettings.json to enable/disable buffering & newtonsoft json vs system.text.json. You will see that newtonsoft with enabled buffering is the only configuration that causes HTTP response to finish to before middleware ran to completion.

**Comment by zvolkov** [comment]
FYI: in the absence of any real solution, for now we are setting SuppressOutputFormatterBuffering=true which seems like it "solves" the problem.

**Comment by zvolkov** [comment]
Actually, looks like it's still happening even with SuppressOutputFormatterBuffering=true - just less frequently. Basically, the volume of requests that get finalized with browser getting the full response before all middleware finished running - got back to pre-3.0 levels but it does still happen.

We are a large US company and we really need some guidance on how to make sure all middleware finishes before the browser thinks the request is done.

Any updates on when you can take a look?

**Comment by pranavkm** [comment]
@Tratcher \ @halter73 are you able to help here? The difference between the two scenarios that are being described here is that the default scenario returns a non-chunked response versus a chunked. Although, going by the most recent comment that might not really matter.

**Comment by zvolkov** [comment]
I guess our main question to Microsoft is: how can we control when the server side tells the client side that it's done? We want to be able to do things in the return leg of our middleware and have the client wait for us. Or give us an official "that's not supported" and we will design our things accordingly.

**Comment by Tratcher** [comment]
ASP.NET Core's response model defaults to streaming the response to the client as quickly as possible to limit latency. They client can see the response as soon as the headers arrive. It can then choose to process the response in a streaming fashion or wait for all of the data to arrive. From a protocol perspective it knows the response is finished either:
A) It's a Content-Length response and it receives the expected number of bytes.
B) It's a chunked response and it receives the chunked terminator.
C) It's a HTTP/2 response and it receives an end-of-stream frame.

The only way to slow A down is to buffer some/all of the response until you've finished your work. B and C aren't usually sent until the end of the middleware pipeline. A new 3.0(?) HttpResponse.CompleteAsync API can cause B and C to be sent early.

But let's back up. What kind of things do you want to do in the return leg of your middleware that the client must wait for? If it's just session state, you can force that to save before sending the response by calling ISession.CommitAsync in your MVC action.

**Comment by halter73** [comment]
To summarize what @Tratcher said from an app perspective, the response body completes when the first of any of the following occurs:

1. The middleware pipeline completes.
2. "Content-Length" bytes are written to an HTTP/1.x response.
3. HttpContext.Response.BodyWriter.CompleteAsync() is called.

---

Kestrel could conceivably also complete HTTP/2 responses automatically once Content-Length bytes are written, but doesn't currently IIRC. Doing so would take away the ability for an app to delay an end-of-stream frame after fully writing an HTTP/2 response with a Content-Length header, but I don't see that as a big loss. This was never possible for HTTP/1.x.

**Comment by zvolkov** [comment]
Re: what we do in the return leg of our middleware, we're saving the state using our home-grown state management (we are hopelessly beyond using the built-in ASP.NET Session).

#2 in the last comment above explains the original issue in the title. Only NewtonsoftJsonOutputFormatter with SuppressOutputFormatterBuffering=false sets Response.ContentLength, triggering response body completion as soon as all bytes are written. 

NewtonsoftJsonOutputFormatter with SuppressOutputFormatterBuffering=true and SystemTextJsonOutputFormatter do not set Content-Length (indeed, in the absence of buffering they can't know the length beforehand).

Which means we can achieve what we want by making sure Content-Length is not set. (I don't think we're calling CompleteAsync explicitly unless it gets called by framework? Does SystemTextJsonOutputFormatter call it when done? - I hope not).

**Comment by zvolkov** [comment]
In summary, I think the fact that middleware's return leg's timing vis-a-vis response completion is different for HTTP/2 vs. HTTP/1.x vs NewtonsoftJsonOutputFormatter vs SystemTextJsonOutputFormatter is counter-intuitive for developers. I imagine most people expect that the server always waits for the middleware to finish, regardless of the protocol or formatter etc. Or this could be a configurable setting, AlwaysWaitForMiddlewarePipelineToComplete.

**Comment by Tratcher** [comment]
`AlwaysWaitForMiddlewarePipelineToComplete` isn't possible to implement with HTTP/1.1 Content-Length responses, the client isn't waiting for an explicit End signal, it's counting the number of bytes received. At best, you could disable content-length responses.



> Kestrel could conceivably also complete HTTP/2 responses automatically once Content-Length bytes are written, but doesn't currently IIRC. Doing so would take away the ability for an app to delay an end-of-stream frame after fully writing an HTTP/2 response with a Content-Length header, but I don't see that as a big loss. This was never possible for HTTP/1.x.

@halter73 I think @JamesNK added that optimization so that if you hadn't declared any trailers it would send the EndStream flag immediately when it reached the content-length.

**Comment by zvolkov** [comment]
I thought the end of response in HTTP 1.x was designated by two empty lines? That, or termination of connection? So I assumed that it was the server's logic to send the terminator based on how many bytes were sent, at least that's what I saw in Kestrel's source code.

**Comment by halter73** [comment]
> I thought the end of response body in HTTP 1.x was indicated by two empty lines? That, or termination of connection?

Neither empty lines nor a closed connection signify the end of an HTTP/1.x Content-Length response. @Tratcher is right that clients simply count the number of bytes to determine where the end of the response body is.

>  So I assumed that it was the server's logic to send the terminator based on how many bytes were sent, at least that's what I think I saw in Kestrel's source code...

Maybe you saw HttpProtocol.ProduceEnd()? In some cases like with a chunked response, this can result in a terminator, but aside from some internal bookkeeping, this method essentially no-ops for HTTP/1.x Content-Length responses.

**Comment by zvolkov** [comment]
If that is so, then I guess the only complaint I still have is that asp.net core 3.0 has changed my responses from no-Content-Length to Content-Length ones, without asking - which broke my app. Perhaps this nuance and its impact on middleware timing should be documented.

**Comment by Tratcher** [comment]
> If that is so, then I guess the only complaint I still have is that asp.net core 3.0 has changed my responses from no-Content-Length to Content-Length ones, without asking - which broke my app. Perhaps this nuance and its impact on middleware timing should be documented.

That was due to the buffering added for NewtonsoftJsonOutputFormatter to avoid sync writes. @pranavkm do you have specific docs or announcements around NewtonsoftJsonOutputFormatter you can share?

In general, an app should not be sensitive to content-length vs chunked distinctions. The timing issue in your case is quite subtle, it's not the current response that's affected so much as it is that the client is unblocked and able to make a second request while you're still cleaning up. Clients can always send parallel requests, you'd have to be in full control of the client to prevent that.

Rather than trying to slow down the client I'd suggest trying to save your session state before responding.

**Comment by zvolkov** [comment]
>I'd suggest trying to save your session state before responding.

In our case it is a Controller Action that creates a response, and a Filter that either tweaks the response or wraps it in an envelop. The response is automatically written to the output stream by ASP.NET framework as soon as the Filter pipeline completes. While the session state is managed by a middleware. It is loaded before, and saved after all the Filters and Controller Actions.

To save my session state before responding would require moving that logic from middleware and to a Filter. We expected the state management to belong in the middleware tier, so this would be a big change for us 5 years into the project :)

**Comment by zvolkov** [comment]
This makes me wonder how this works with ASP.NET native session (which is handled by a middleware too, I believe), and whether it's been affected by this buffering change, too.

**Comment by pranavkm** [comment]
>  @pranavkm do you have specific docs or announcements around NewtonsoftJsonOutputFormatter you can share?

Working on adding one to the migration note: https://github.com/dotnet/AspNetCore.Docs/pull/18849

**Comment by halter73** [comment]
Middleware that wants to do something (change headers is the common one) right before the response body is about to be written, but after other middleware gets a chance to act, typically register a callback with HttpContext.Response.OnStarting before calling next().

**Comment by Tratcher** [comment]
> This makes me wonder how this works with ASP.NET native session (which is handled by a middleware too, I believe), and whether it's been affected by this buffering change, too.

The built in session middleware has the same limitations. That's why it provides the CommitAsync API for anyone that wants to save sooner. It doesn't need to be a huge refactor to expose such a capability through HttpContext.Features. OnStarting is another way to hook in.

**Comment by zvolkov** [comment]
Alright. Let's mention it in some kind of documentation and call it a day. I'm done with this ticket, thanks a lot guys.

**Comment by zvolkov** [comment]
One could argue that having NewtonsoftJsonOutputFormatter set Content-Length header was an unnecessary change in 3,0, negatively affecting customers (like us) and it should be fixed to not set the header. But I don't care enough to argue.
