### ISSUE TITLE
Json.Deserialize<T>(jsonString) fails for unsigned integer.

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/aspnetcore#18630]
### Describe the bug
I want to deserialize a json string via Json.Deserialize<T>(jsonString) into a type containing an ```uint``` property, but it fails with the following exception message: ```System.ArgumentException: "Object of type 'System.Int64' cannot be converted to type 'System.UInt32'."``` 

I think the reason is that in [this](https://github.com/aspnet/Extensions/blob/master/src/JSInterop/Microsoft.JSInterop/src/Json/SimpleJson/SimpleJson.cs#L1440) line of code, only signed numbers are checked and ```System.UInt32``` is missing.

### To Reproduce
Run the following app:

```cs
using Microsoft.JSInterop;

namespace Test
{
    public enum Mode
    {
        Mode1 = 1,
        Mode2 = 2
    }

    public class DemoData
    {
        public int Id { get; set; }
        public string StringData { get; set; }
        public uint UIntData { get; set; }
        public Mode EnumData { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var jsonString = "{ \"id\":1,\"stringData\":\"Demo Data\",\"uIntData\":1,\"enumData\":2}";
            var demoData = Json.Deserialize<DemoData>(jsonString);
        }
    }
}
```
Content of the .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.JSInterop" Version="3.0.0-preview5.19227.9" />
  </ItemGroup>

</Project>
```

### Expected behavior
I expect that numbers can be deserialized into properties of type unsigned integer.

### Additional context
The issue was detected when trying to deserialize unsigned data using the BlazorExtensions.Signalr package.

**Comment by pranavkm** [comment]
We've since migrated to using System.Text.Json for JSON parsing. If you still think this is a problem with the latest runtime, please file an issue in https://github.com/dotnet/runtime
