### ISSUE TITLE
Twitter Authentication can't get user email

### ISSUE THREAD

**Issue by davemk99** [dotnet/aspnetcore#18633]
I am using Microsoft.AspNetCore.Authentication package 3.1.1 version with Twitter Provider Microsoft.AspNetCore.Authentication.Twitter package. When trying to get user information from the user, I can't get user email from the details provided, even if I specify TwitterOptions.RetrieveUserDetails. How can I get this information? I've enabled the "Request User Email" option from my Twitter application.

**Comment by Tratcher** [comment]
Twitter used to require contacting their support to enable this permission, has that changed?

**Comment by davemk99** [comment]
@Tratcher yes, they allow mentioning that.

**Comment by Tratcher** [comment]
I just verified our local sample is working. 
https://github.com/dotnet/aspnetcore/blob/e8363b1cc9f2c76ff8fed0aa55fd3ef9a960ee5a/src/Security/Authentication/samples/SocialSample/Startup.cs#L86-L99

A note from their permissions page:
```
Additional permissions
These additional permissions require that you provide URLs to your application or service's privacy policy and terms of service. You can configure these fields in your Application Settings.

Request email address from users
```

If you're unable to get the e-mail address from them then you'll need to contact Twitter support.

**Comment by MintPlayer** [comment]
Dear @davemk99 

Besides the `tw_options.RetrieveUserDetails = true;`, there are 2 additional configurations:

- tw_options.RetrieveUserDetails = true; (this is OK)
- https://developer.twitter.com/en/apps -> Select your app -> App details tab -> Edit -> Edit details -> Check "Enable Sign in with Twitter"
- https://developer.twitter.com/en/apps -> Select your app -> Go to the Permissions tab -> Edit -> At the bottom, check "Request email address from users"

Can you check that?

**Comment by davemk99** [comment]
Thanks everyone for their help. I managed to found out what was the issue with it. It was the issue with account I was using when logging in. When using other account,it worked just as expected.
