### ISSUE TITLE
http POST Request body is null after changing from 2.1.1 to 3.1

### ISSUE THREAD

**Issue by mads221h** [dotnet/aspnetcore#18643]
Hello and thanks for the help in advance.

The problem i'm having is that in my API Controller i have a post method, where i receive some data from the body, and after changing to .net Core to 3.1 it gave me the error 
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

And this is the post method:

```[HttpPost("[action]")]
        public void CreateOrder([FromBody] Order data)
        {
            bool _priceBool = false;
            if(data.Price <= 10000)
            {
                _priceBool = true;
            };
            var order = new Order
            {
                Title = data.Title,
                Date = DateTime.Now.ToString("yyyy-MM-dd"),
                Supplier = data.Supplier,
                Project = data.Project,
                Department = data.Department,
                Description = "Description rkgmrk r,gpw viuje eobin wueji, ok,wem ue wej iemgke ,lrve efke",
                Price = data.Price,
                Approval = _priceBool,
                Payment = false,
            };          
            _db.Order.Add(order);
            _db.SaveChanges();
        }
```
This is the fetch method i made in my react view ;

```
        function handleSubmit(event) {
            
            event.preventDefault();
            const data = new FormData(event.target);
            var object = {};
            data.forEach(function (value, key) {
                object[key] = value;
            });
            var json = JSON.stringify(object);
            fetch('api/SampleData/CreateOrder', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: json,
            }); 
        }
```
I have also tried using postman.
And the body the I send looks something like this

```
{
    "Title": "Turbo",
    "Supplier": "123",
    "Project": "Project 2401",
    "Department": "Department 2401",
    "Price": "2321"
}
```
And since my data parameter is of the type Order i will include this class aswel.
```
public class Order
    {
        [Key]
        public int OrderId { get; set; }
        
        public string Date { get; set; }
        
        public string Title { get; set; }
        
        public string Supplier { get; set; }
        
        public string Project { get; set; }
        
        public string Department { get; set; }
        
        public string Description { get; set; }
        
        public int Price { get; set; }
        
        public bool Approval { get; set; }
        
        public bool Payment { get; set; }

    }
```
I have checked all the names for any typos and other methods that are mostly identical seems to work aswell. This all works just fine with 2.1.1 so i don't understand why it wouldn't work for 3.1 either, or if there is some changes that would break this i couldn't find it.

**Comment by Tratcher** [comment]
What's the stacktrace for the NullReferenceException?

**Comment by pranavkm** [comment]
>  or if there is some changes that would break this i couldn't find it.

There were significant changes to how JSON is deserialized in 3.x: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#newtonsoftjson-jsonnet-support.

**Comment by mads221h** [comment]
Thanks for the help @Tratcher  and @pranavkm. I couldn't find the example of it but its seems like it no longer deserialize a string of numbers as an interger. So i just used parseInt on the key that matched "Price".  in my handlesubmit function.
