### ISSUE TITLE
XML comment support for Razor component files

### ISSUE THREAD

**Issue by nrhoffmann** [dotnet/aspnetcore#18642]
I'm trying to add XML comments to the parameters in my Razor components, but they don't appear in to make it into the generated component class.

When I write comments on the parameters in component with a .razor extension and then use the component in another .razor file, I cannot see the comments when hovering over the properties.

If I write the comments in class style components (the ones with .cs extension), or the partial components (the ones with .razor.cs extension), then everything works as expected.

I'm using visual studio.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nrhoffmann.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@nrhoffmann could you please provide a small repro for what you're seeing to ensure we are able to reproduce and comment on precisely what you're concerned about.
