### ISSUE TITLE
pdb files are published in Blazor WASM template project with Release configuration

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#18655]
### Describe the bug
`pdb` files are published for a blazor wasm project with version 3.2.0 preview 1 when deployed with Release configuration

### To Reproduce
1. Create a new blazor wasm project using the latest template either from VS or from the CLI:

> Note: Make sure to run
>```
>dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1
>```
> to get the template

2. Deploy the app to IIS using the following command
```
dotnet publish --configuration Release -o <PATH_TO_IIS_FOLDER>
```
Suppose that the app is exposed from IIS on http://localhost/blazorwasm32

3. Open http://localhost/blazorwasm32

4. Open the Network tab in DevTools and look for the failed request for `blazorwasm32.Shared.pdb`.
> **Note:** Although files like `blazorwasm32.Server.pdb` and `blazorwasm32.Client.pdb` are part of the content of the published folder on IIS, they are not requested by the browser (not visible in the Network tab).

Screenshot of the result:

![blazor-wasm](https://user-images.githubusercontent.com/1857705/73352302-7cd53b00-4299-11ea-9179-7edc79d5cc7e.png)

A sample is also available in https://github.com/Stamo-Gochev/blazor-wasm-pdb-issue

### Further technical details
- ASP.NET Core version - 3.1.101, WASM 3.2.0-preview-1 (3.2.0-preview1.20073.1)
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Stamo-Gochev.
We'll look into this during our next milestone planning meeting and decide on what we need to do here.

**Comment by pranavkm** [comment]
@SteveSandersonMS does your caching PR - https://github.com/dotnet/aspnetcore/pull/18859 - resolve this issue?

**Comment by SteveSandersonMS** [comment]
It may well do. I didn’t specifically notice either way, but it looks plausible.
