### ISSUE TITLE
Blazor WebAssembly and CodePagesEncodingProvider

### ISSUE THREAD

**Issue by catlan** [dotnet/aspnetcore#18656]
### Describe the bug
It seems to me that _System.Text.Encoding.CodePages_ is not fully loaded by Blazor WebAssembly. I tried this simple code snipped on 3.2.0 Preview 1 and previous on 3.1.0-preview4.19579.2:
```
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var test = Encoding.GetEncoding("Windows-1252");
```
Which results in ``System.NotSupportedException: Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.``.

### To Reproduce

- Run attached project [BlazorAppEncodingTest.zip](https://github.com/dotnet/aspnetcore/files/4127879/BlazorAppEncodingTest.zip) or

- New project "Blazor WebAssembly App":
  1. Add _System.Text.Encoding.CodePages_ nuget
  2. Add ```
              Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
              var test = Encoding.GetEncoding("Windows-1252");
  ```  to ```public static async Task Main(string[] args)```
  3. Run project.

### Further technical details
- Include the output of `dotnet --info`
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
Microsoft Visual Studio Community 2019
Version 16.4.3
```
[BlazorAppEncodingTest.zip](https://github.com/dotnet/aspnetcore/files/4127879/BlazorAppEncodingTest.zip)

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18618
