### ISSUE TITLE
Blazor wasm SignalR does not close the connection

### ISSUE THREAD

**Issue by campersau** [dotnet/aspnetcore#18654]
### Describe the bug
Closing or Disposing a SignalR connection in Blazor wasm does not close the actual websocket connection in the browser.

### To Reproduce
- Create a new Blazor wasm app
- Add SignalR client
- Create a HubConnection and start it
- Add button and code to stop the connection
- The network trace in the browser shows that the connection is still pending after clicking the close button

![image](https://user-images.githubusercontent.com/4009570/73342118-3b836200-427e-11ea-8952-cc7aebd04860.png)

```razor
@using Microsoft.AspNetCore.SignalR.Client

@page "/"

<button @onclick="Close">Close SignalR Connection</button>

@code {

    private HubConnection _hubConnection;

    protected override async Task OnInitializedAsync()
    {
        _hubConnection = new HubConnectionBuilder()
            .WithUrl("https://signalrserver/pathtohub")
            .Build();

        await _hubConnection.StartAsync();
    }

    private async Task Close()
    {
        // try both of them
        await _hubConnection.StopAsync();
        await _hubConnection.DisposeAsync();
    }

}
```

I think the problem is that the `WebSocketsTransport` only disposes the client websocket
https://github.com/dotnet/aspnetcore/blob/76b0dffb647d9799e4548882215bcc6c1237d458/src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/WebSocketsTransport.cs#L413
and the current wasm mono websocket implementation does not close the connection on dispose but on `CloseAsync` only.
https://github.com/mono/mono/blob/883162e861c95b7be7c3e830f1d70ff1c8e74fa9/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs#L479

Because of that feel free to move this issue to the mono repro.

### Further technical details
- ASP.NET Core version 3.2.0-preview1.20073.1
- Microsoft Visual Studio Enterprise 2019 Version 16.4.3

<details>
<summary>dotnet --info</summary>

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.101
 Commit:    b377529961

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by conficient** [comment]
Just encountered this same issue upgrading my [BlazorChatSample](https://github.com/conficient/BlazorChatSample) demo to use the .NET SignalR client. I call `.StopAsync()` and `.DisposeAsync()` as well, but only when I close the browser tab does it drop.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@anurse is this SignalR specific or should I move this to the mono team?

**Comment by anurse** [comment]
Well, it's a little of both. We should probably call `CloseAsync` but mono should *also* be terminating the connection when the socket is disposed (even if `CloseAsync` wasn't called). We'll take a look at our logic but @mkArtakMSFT I think you should go ahead and move this to mono.

**Comment by mkArtakMSFT** [comment]
Thanks @anurse. Do you want to file a separate issue (if you haven't yet) to track the work we need to do on our side?

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18628
