### ISSUE TITLE
Is it possible to bring Startup classes back to Blazor so ASP.NET configuration is "similar" across the board?

### ISSUE THREAD

**Issue by seesharprun** [dotnet/aspnetcore#18658]
It's exciting that there is a simpler syntax to bootstrap an ASP.NET Blazor project:

```
public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("app");

        await builder.Build().RunAsync();
    }
}
```

But I am a little concerned that we are moving away from the tried-and-true syntax used to bootstrap ASP.NET. I can bootstrap an ASP.NET web application with a quick expression-bodied member:

```
public static async Task Main(string[] args) =>
    await Host.CreateDefaultBuilder(args)            
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        })
        .Build()
        .RunAsync();
```

As someone who teaches ASP.NET and .NET Core, it drives me crazy that the syntax is almost, but not exactly the same between ASP.NET and Blazor. There could be improvements.

First, you could start with the following code to begin bootstrapping a Blazor project:

```
public static async Task Main(string[] args) =>
    await WebAssemblyHostBuilder.CreateDefault(args)
    ...
```

It's crazy that noun *"Builder"* has moved from the method name to the static class name. If you wanted a fix that had the least impact, you could simply add a ``WebAssemblyHost`` static class with a ``CreateDefaultBuilder`` method that invokes ``WebAssemblyHostBuilder.CreateDefault`` under the hood.

```
public static class WebAssemblyHost
{
    public static WebAssemblyHostBuilder CreateDefaultBuilder(string[] args) => 
        WebAssemblyHostBuilder.CreateDefault(args);
}
```

Then your first bootstrap line would look almost identical to the ASP.NET version:

```
public static async Task Main(string[] args) =>
    await WebAssemblyHost.CreateDefaultBuilder(args)
```

Even though you have simplified the Startup experience. Having it not consistent with ASP.NET may scare away developers who have a ton of experience already. You can add the option to configure using a Startup class without removing the ability to configure directly in the Main method.

All you would need to do is implement a ``ConfigureWebAssemblyHostDefaults`` extension method that models the implementation for ASP.NET with many less configuration methods.

```
public interface IWebAssemblyStartup
{
    void ConfigureRootComponents(RootComponentMappingCollection components);

    void ConfigureServices(IServiceCollection services);

    // Additional methods
}

public static class WebAssemblyHostBuilderExtensions
{
    public static WebAssemblyHostBuilder ConfigureWebAssemblyHostDefaults(this WebAssemblyHostBuilder builder, Action<WebAssemblyHostBuilder> configure)
    {
        configure(builder);
        
        return builder;
    }

    public static void UseStartup<TStartup>(this WebAssemblyHostBuilder builder) where TStartup : IWebAssemblyStartup, new()
    {
        TStartup startup = new TStartup();

        startup.ConfigureRootComponents(builder.RootComponents);

        startup.ConfigureServices(builder.Services);

        // Additional interface methods
    }
}
```

Then you can add it to the Main method like this:

```
public static async Task Main(string[] args) =>
    await WebAssemblyHost.CreateDefaultBuilder(args)        
    .ConfigureWebAssemblyHostDefaults(webBuilder =>
    {
        webBuilder.UseStartup<Startup>();
    })
```

and create a Startup class like this:

```
public class Startup : IWebAssemblyStartup
{
    public void ConfigureRootComponents(RootComponentMappingCollection components)
    {
        components.Add<App>("app");
    }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<WeatherService>();
    }
}
```

Since everything would be chained, you could simply add ``Build`` and ``RunAsync`` to the end:

```
public static async Task Main(string[] args) =>
    await WebAssemblyHost.CreateDefaultBuilder(args)
        .ConfigureWebAssemblyHostDefaults(blazorBuilder =>
        {
            blazorBuilder.UseStartup<Startup>();
        })
        .Build()
        .RunAsync();
```

That looks almost identical to the ASP.NET configuration, while still maintaing the ability to configure directly in the Main method if you choose to do so.

I wanted to post this long issue before creating a PR to see if there's any interest in implementing this. If so, there's enough code here to start a PR.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @seesharprun.
@rynowak any thoughts?

**Comment by knight1219** [comment]
An outside opinion from someone using Blazor: I agree. It's been nice to look at the project (or multiple projects) and have it look just like a traditional web app/api. No need to learn anything new, everything is just in place. I can potentially see how making configuration simpler is a good thing, but making it too far away from the normal Asp.Net core setup seems like a potential misstep for adoption. 

(This coming from someone updating his Blazor apps to the new preview for the rest of the week 👍)

**Comment by SteveSandersonMS** [comment]
The new startup model is much more flexible and generalised than the one we had before, so the good news is that the old system can be modelled as a special case of the new one.

For example, if you really wanted to have an identical `Startup` class with `ConfigureServices` and `Configure` like before, you could take [this class](https://github.com/dotnet/aspnetcore/blob/ba08d60cb95c01e8de4ebeda3948217fcc6b24a8/src/Components/Blazor/Blazor/src/Hosting/ConventionBasedStartup.cs) and its dependencies, add them to your project, and have it invoke a `Startup` class for you from `Program`'s `Main` method. If you think this is something a lot of developers would want, maybe it would be worth putting the necessary collection of classes into a NuGet package so it's easy for people to reuse.

**Comment by seesharprun** [comment]
I think I will look at the NuGet route. 

It's just a bit suprising that the ASP.NET teams are using two different patterns/models to configure projects.

**Comment by mrpmorris** [comment]
Took a while yesterday to work out where to put the .Use(....) statements.

**Comment by StevenTCramer** [comment]
@SteveSandersonMS 

> The new startup model is much more flexible and generalised than the one we had before, so the good news is that the old system can be modelled as a special case of the new one.

The bad news is though that the old system was NOT modelled as a special case of the new one.  And thus now there will be many different versions attempting do that.  I would prefer we have one official one.
