### ISSUE TITLE
Pin dependencies from the dotnet/efcore repository

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#18667]
In the spirit of pulling EFCore out of our release graph, we should stop having those dependencies be updated automatically by DARC, and instead treat them like 3rd party dependencies. We can do this one of two ways, both of which require deleting the Darc subscriptions: 

1. Pin the dependencies in `version.details.xml`, update both version files when we want to take an EFCore update
2. Remove the dependencies from `version.details.xml` entirely, update `Versions.props` when we want to take an EFCore update

I prefer option 2, but am open to persuasion. I think removing the dependencies from `version.details.xml` creates a better representation of what our "graph" looks like, since that's the file that exactly represents what's updated through DARC. It also gets rid of some weird potential bugs related to CoherentParentDependencies - e.g. if we ever declare `Microsoft.NetCore.App` as the parent for a CPD, darc could choose the EFCore dependency on `Microsoft.Netcore.App` as the "parent", and do the wrong thing. This happened in https://github.com/dotnet/aspnetcore/pull/18247.

CC @bricelam @ajcvickers @dotnet/aspnet-build

**Comment by dougbu** [comment]
Why make the EF dependency flow into aspnetcore manual at this time? As far as I know, the eventual story for 3rd party dependencies will _not_ be manual. This would add extra work and not simplify much, if anything.
