### ISSUE TITLE
Cannot load assembly in when BlazorLinkOnBuild is not set off

### ISSUE THREAD

**Issue by OmidID** [dotnet/aspnetcore#18661]
### Describe the bug
Cannot load assembly when BlazorLinkOnBuild is not set off. The assembly need `netstandard`
In case of loading `netstandard` too the error will be change and it's cannot find the `System.Object`

### To Reproduce
Create one Blazor project and one Net standard library. 

In Blazor project add this code somewhere:
```cs
//Need a api to return assembly file or direct link to assembly
var data = await httpClient.GetByteArrayAsync($"/api/extenstions/get?key=MyLibrary.dll");
var assm = System.Reflection.Assembly.Load(data);
```
In case of adding `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>` to the Blazor project everything working well. 

### Further technical details
- ASP.NET Core version 3.1
- Blazor version 3.2.0-preview1.20073.1
- Net standard 2.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @OmidID .
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@OmidID linking is going to be generally incompatible with dynamic loading. Your dynamically loaded assemblies may rely on APIs that the linker has trimmed, so using the two is a recipe for runtime errors. Even without linking, you have to be responsible for loading the graph of dependencies.

**Comment by OmidID** [comment]
Thank you so much.
@pranavkm , I have a project that loading assemblies as plugins . 
So what is the solution for plugin base applications?

**Comment by pranavkm** [comment]
@OmidID we don't really have a good answer for this as yet. It's likely some of it might be considered as part of https://github.com/dotnet/aspnetcore/issues/5465.
