### ISSUE TITLE
Dll versions not up to date

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/aspnetcore#18673]
I created a worker service using Visual Studio 2019 16.4.2. The project was created and ran so all was well. The project used Micosoft.Extensions.Hosting version 3.1 and has dependencies on:

Microsoft.Extensions.DependencyInjection.Abstractions 3.1
Microsoft.Extensions.Hosting.Abstractions 3.1

Microsoft.AspNetCore 2.2.0 uses

Microsoft.Extensions.DependencyInjection.Abstractions v 3.1
Microsoft.Extensions.Hosting.Abstractions v 2.2.0

So that means I cannot use a worker service as a windows service AspNetCore uses an older version and worker service requires a later version of Microsoft.Extensions.Hosting.Abstractions.

I wanted to ask if the lastest version of AspNetCore could use the latest version of 
Microsoft.Extensions.XXX. Because asp.net core using one version worker service using another has forced me to go backwards and use ServiceBase.

Even with this I am having problems because a third party dll we use uses 
Microsoft.Extensions.DependencyInjection.Abstractions v 3.1.1 and AspNetCore uses 
Microsoft.Extensions.DependencyInjection.Abstractions v 3.1.0.

This is create a dll version nightmare like the early days of windows so is there a way for the versions of Microsoft.Extensions.XXX to be made up to date.

Also I have read that asp.net core 3.1 was released is that true, and is AspNetCore 2.2.0 version 2 or version 3?

**Comment by Tratcher** [comment]
The Microsoft.AspNetCore package has been replaced by a new TargetFramework and FrameworkReference, that's why you don't see a 3.0 version.
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#remove-obsolete-package-references

Microsoft.Extensions.DependencyInjection.Abstractions 3.1.0 vs 3.1.1 shouldn't be a significant issue, everything should roll forwards to the latest patch version. What errors do you get?

**Comment by dgxhubbard** [comment]
This is not an old project, it is brand new so we don't need to remove old versions.

I have no idea what you mean by
"The Microsoft.AspNetCore package has been replaced by a new TargetFramework and FrameworkReference, that's why you don't see a 3.0 version."

Is Microsoft.AspNetCore version 2.2.0 part of asp.net core version 3.x.

When I run as a service, it wanted version  3.1 of Microsoft.Extensions.Hosting.Abstractions but that version had been overwritten by version 2.2.0

**Comment by Tratcher** [comment]
> Is Microsoft.AspNetCore version 2.2.0 part of asp.net core version 3.x.

No, the Microsoft.AspNetCore package doesn't exist anymore in 3.x. Why do you have a package reference to Microsoft.AspNetCore in a new project?

**Comment by dgxhubbard** [comment]
We are using a third party package that uses it.

**Comment by anurse** [comment]
> Microsoft.AspNetCore 2.2.0 uses
> 
> Microsoft.Extensions.DependencyInjection.Abstractions v 3.1

@dgxhubbard Where are you seeing this? The nuget package graph shows only 2.2 dependencies for Microsoft.AspNetCore. Be aware that if you're looking at your `.deps.json` or the transitive package graph in VS it will show the highest versions of packages if two packages request different versions.

> We are using a third party package that uses it.

If this is the case, you need to either upgrade the package to a version that uses 3.1 or stay on 2.2.
