### ISSUE TITLE
Blazor Hybrid

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#18670]
Use .NET and Blazor to build native apps for desktop and mobile while using web technologies (HTML, CSS) for the UI.

Relevant experimental projects:

- [Blazor + Electron](https://aka.ms/blazorelectron)
- [Blazor + WebWindow](https://aka.ms/webwindow)

**Comment by paolofulgoni** [comment]
I think it's obvious, but this should definitely be cross-platform

**Comment by RChrisCoble** [comment]
I looked for a "Blazor Native" thread but couldn't find one. 

If the Blazor Native engine was baked into WinUI this would allows us to write controls/components that run on Web and Windows Universal without modification, with native(ish) performance.

I have a litany of WPF code where we're porting the business logic to .Net Standard.  Cool, then what do we do with it to maximize the reuse?  Blazor gives us a powerful PWA experience on Web, but I also have a request for HoloLens.

If MS is not going to do cross platform XAML (like Uno), this is a great alternative.

**Comment by scottkuhl** [comment]
I've seen the Blazor mobile bindings, but this approach seems like it would be much faster to implement.  I would love to see an experimental project start to support mobile like you did for desktop with Electron and WebWindow.  Its and easier path from server side, to Wasm, to hybrid for web developers.

**Comment by danroth27** [comment]
Hybrid app support has now been added to the [Mobile Blazor Bindings project](https://aka.ms/mobile-blazor-bindings): https://devblogs.microsoft.com/aspnet/hybrid-blazor-apps-in-mobile-blazor-bindings-july-update/. Since we expect future work around Blazor Hybrid apps to be done through the Mobile Blazor Bindings project, we're closing this issue.
