### ISSUE TITLE
prevent page refresh in Blazor (webassembly) when Enter key is pressed in input

### ISSUE THREAD

**Issue by dlr1** [dotnet/aspnetcore#18687]
I have the following piece of html
`<form class="form-inline my-2 my-lg-0 float-right">
            <input class="form-control mr-sm-2" type="search" placeholder="studentid" aria-label="Search" @bind-value="StudentId"  @bind-value:event="oninput"   @onkeypress="@KeyHandler" 
                   @onkeyup:stopPropagation />
        </form>`

`private void KeyHandler(KeyboardEventArgs eventArgs)
    {
        if (eventArgs.Key == "Enter")        // fire on enter 
        {
            Console.WriteLine(StudentId);
            NavigationManager.NavigateTo("auditresults/" + StudentId);
        }
    }`

why does my page refresh when enterkey is pressed? how can I prevent that?

Thanks

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by mkArtakMSFT** [comment]
According to your code you're trying to navigate when `Enter` is pressed. Isn't that expected then?

**Comment by dlr1** [comment]
this is not aspnet core application. it is blazor, hosted in aspnet core. If the input is in the form it refreshes the page and then navigates, if the input is not in a form, it navigates correctly( no page refresh)

**Comment by SteveSandersonMS** [comment]
I tried out this code, and I'm afraid the issue doesn't repro for me. Pressing enter in the input only causes client-side navigation to `auditresults/{valuetyped}`. It does not cause the page to reload. Something else must be triggering this behavior for you, but without a repro I can't say what.

If you are able to provide repro code that demonstrates the problem when added to a new Blazor WebAssembly project, please let us know. Thanks!
