### ISSUE TITLE
All indexes should follow same naming convention [Identity]

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#18680]
Hi,

I think all indexes, created by EF should follow same naming convention. right now some use`IX_TableName_ColumnName` pattern, e.g: `IX_AspNetRoleClaims_RoleId` and some doesn't have any special pattern, e.g: `RoleNameIndex`.

**Comment by blowdart** [comment]
@ajcvickers Is this considered breaking?

**Comment by ajcvickers** [comment]
@blowdart Grey area. (I know you love those!) The runtime doesn't care, but it's a schema change that will cause a new migration to be generated. So I would say not a breaking change, but could cause confusion/questions when people see the new migration.

Should also say that anyone who doesn't like the current names can easily use their own instead.

**Comment by blowdart** [comment]
Given I want to limit migrations as much as possible, this is then a no. What little benefit there is is outweighed by the pain of unexpected schema migrations.

**Comment by dehghani-mehdi** [comment]
> Should also say that anyone who doesn't like the current names can easily use their own instead.

Sure, but the default should use same rules, isn't it good practice in programming world?

**Comment by ajcvickers** [comment]
@dehghani-mehdi Yes, but these needs to be balanced against the cost of disrupting thousands of developers for a change that won't make their application behave any differently. The value in this case does not outweigh this cost to existing developers.
