### ISSUE TITLE
Input 

### ISSUE THREAD

**Issue by HassanAslikh** [dotnet/aspnetcore#18681]
Any one have an idea if Blazor inputSelect component has a bug in binding integer Id

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/11181. There's a workaround listed here: https://github.com/dotnet/aspnetcore/issues/11181#issuecomment-506288035

**Comment by mkArtakMSFT** [comment]
Potential dupe of https://github.com/dotnet/aspnetcore/issues/18305
