### ISSUE TITLE
Razor.Language generates incorrect code on onclick for razor component

### ISSUE THREAD

**Issue by GeorgeAlexandria** [dotnet/aspnetcore#18684]
Hello,

I'm trying to use `Microsoft.AspNetCore.Razor.Language v3.1.1` and it dependencies to generate C# code for a razor component in Blazor app. I try to generate code for the component in Blazor project, that was scaffolded by **Visual Studio v 16.4.3** from Blazor server side template (`Counter.razor` without any changes), using the code bellow:

```c#
private static void GenerateCode(string root, string relativePath)
{
    var fileSystem = RazorProjectFileSystem.Create(root);
    var engine = RazorProjectEngine.Create(RazorConfiguration.Default, fileSystem, (builder) =>
    {
        // Keep namespace and class name
        builder.SetRootNamespace("My_Namespace");
    });

    var item = fileSystem.GetItem(relativePath, FileKinds.Component);
    var source = RazorSourceDocument.ReadFrom(item);
    var codeDocument = engine.Process(item);
    var csharpDocument = codeDocument.GetCSharpDocument();
}
```

As a result I receive:

<details><summary>Received code</summary>

```c#
#pragma checksum "..\repos\BlazorApp1\BlazorApp1\Pages\Counter.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5456520839664fbbeb726a4af0946602a9d68f5c"
// <auto-generated/>
#pragma warning disable 1591
namespace My_Namespace.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using Microsoft.AspNetCore.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using Microsoft.AspNetCore.Components.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using BlazorApp1;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "..\repos\BlazorApp1\BlazorApp1\_Imports.razor"
using BlazorApp1.Shared;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/counter")]
    public partial class Counter : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h1>Counter</h1>\r\n\r\n");
            __builder.OpenElement(1, "p");
            __builder.AddContent(2, "Current count: ");
            __builder.AddContent(3, 
#nullable restore
#line 5 "..\repos\BlazorApp1\BlazorApp1\Pages\Counter.razor"
                   currentCount

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(4, "\r\n\r\n");
            __builder.AddMarkupContent(5, "<button class=\"btn btn-primary\" @onclick=\"IncrementCount\">Click me</button>");
        }
        #pragma warning restore 1998
#nullable restore
#line 9 "..\repos\BlazorApp1\BlazorApp1\Pages\Counter.razor"
       
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
```
</details>

The issue is that the received code places onclick C# handle method just as a markup: 

```c#
__builder.AddMarkupContent(5, "<button class=\"btn btn-primary\" @onclick=\"IncrementCount\">Click me</button>");
```

but C# code, that was generated by Visual Studio with sdk 3.1.101 at a build time, places handle method as an attribute of element:

```c#
__builder.OpenElement(5, "button");
__builder.AddAttribute(6, "class", "btn btn-primary");
__builder.AddAttribute<MouseEventArgs>(7, "onclick", EventCallback.Factory.Create<MouseEventArgs>(this, new Action(this.IncrementCount)));
__builder.AddContent(8, "Click me");
__builder.CloseElement();
```

Currently I found out, that Razor.Language produces incorrect node in syntax tree:

![image](https://user-images.githubusercontent.com/13402478/73452722-8a62f180-437b-11ea-861b-5b4708161038.png)

If I miss something, please let me know about it.

Upd.
Seems that issue appears for all special syntax occurrence inside an html tag:
```c#
<input @bind="Current" />
<input @bind-value="CurrentValue" @bind-value:event="oninput" />
<button class="btn btn-primary" @ref="Current" />
and so on so forth
```
Upd2.
Also Razor.Language supouse that the example below is an element:

``` html
@* OuterComponent *@

<InnerComponent MyInput="value" />

@ code{
    private string value;
    ...
}
```

and generates: 
```c#
__builder.OpenElement(0, "InnerComponent ");
__builder.AddAttribute(1, "MyInput", "value");
__builder.CloseElement();
```

when should generate code for working with component:

```c#
__builder.OpenComponent<InnerComponent >(0); // or __builder.OpenComponent(0, typeof(InnerComponent));
__builder.AddAttribute(1, "MyInput", value);
__builder.CloseComponent();
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GeorgeAlexandria.
We'll look into this during our upcoming milestone review meeting and get back to you then.

**Comment by GeorgeAlexandria** [comment]
Did you look into this in your review meeting (unfortunately, I don't know was your meeting or not)? If so, do you have any updates on this, @mkArtakMSFT?

**Comment by mkArtakMSFT** [comment]
We haven't got to this yet. Will update the issue milestone as soon as we get to this one.

**Comment by pranavkm** [comment]
Hi @GeorgeAlexandria, we don't generally support code generating Razor components. That said, you could just add the contents as a .razor file in your project. The type should be available to you at runtime. This is essentially what we do in Blazor too - https://github.com/dotnet/aspnetcore/blob/master/src/Components/Authorization/src/CascadingAuthenticationState.razor.

**Comment by GeorgeAlexandria** [comment]
Hello, @pranavkm, I'm unpleasantly surprised that you don't support code generating razor components... Do you plan to support it? 

It's really important thing for many analysers application that allows analysers to analyse, investigate, interpret and so on so forth the C# code under razor component. Besides, in many cases analysers can't include source types in their code base or load them into domain at runtime, so you suggestion in this cases not applicable. In other cases, when you actually can add source types at runtime, you can't correctly interpret C# code, because doesn't exist a way to retrieve the correct and corresponding C# code for razor component.

Do you open to receive MR from community on supporting code generating for razor component?

P.S. also, I don't understand one thing: sdk 3.1.101 and newer can build razor component in apps to the correct IL code. Do you generate directly IL code (without C#) from razor component under building by sdk or a way to generate correct C# code exists and does it unavailable for "public"?

**Comment by pranavkm** [comment]
Razor files are code-generated in to C# files. You can inspect their contents - they're usually in the `obj\$(Configuration)\$(TargetFramework)` folder for instance `obj\Debug\netcoreapp3.1`. I'm not sure what analyzers have to do with runtime code-generation, the framework ships with a few that are enabled by default and operate on these code generated file. 

>  In other cases, when you actually can add source types at runtime,
Out of the box, components do no have a model for runtime compilation or loading dynamically.

**Comment by GeorgeAlexandria** [comment]
> Razor files are code-generated in to C# files. You can inspect their contents - they're usually in the obj\$(Configuration)\$(TargetFramework) folder for instance

It means that sdk supports the correct C# code generating Razor component (when Razor.Language nuget package doesn't) but you actually told:
> we don't generally support code generating Razor components

So I try to ask more correct: Is the code generating for Razor component from sdk available for public? Might it be the Razor.Language nuget package?
