### ISSUE TITLE
Improve documentation for updating component state externally

### ISSUE THREAD

**Issue by SayusiAndo** [dotnet/aspnetcore#18693]
I'm not sure this ticket should be filed here. If it is not the right project, please let me know and I'll move it, or feel free to relocate it.

The documentation about how to update component state from external source the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state) shows two code snippets. The snippets are good and usable, or at least they give some hints what to do. Unfortunately, the documentation doesn't mention that the Notification service must be injected as singleton. If it is injected as transparent (new instance for every request), then the Notify property will be null.

Fortunately, this issue was discussed on [Stackoverflow](https://stackoverflow.com/questions/59857650/blazor-event-sent-from-service-to-component-is-null). In my opinion, it would be great to provide a more detailed example to help the community to utilize easier this functionality. 

Thanks!

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/AspNetCore.Docs#16801
