### ISSUE TITLE
Remove arcade workarounds once it is fixed in Arcade

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18696]
The issue tracking the change in Arcade: https://github.com/dotnet/arcade/issues/4727
The change to revert: https://github.com/dotnet/aspnetcore/pull/18599/commits/240eab8f6038ea1beff1a0cc3fc0e3fc299faa9b

**Comment by dougbu** [comment]
@pranavkm dotnet/arcade#4727 is closed with no action on their side. But, `eng/tools.*` scripts change the `$env:Temp` variable only in CI builds (actually writing pipeline variables that primarily affect later build steps). Does this issue track anything important anymore❔

**Comment by pranavkm** [comment]
None that I'm aware of.
