### ISSUE TITLE
ModelBindingMessageProvider SetMissingBindRequiredValueAccessor and friends

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/aspnetcore#18695]
How is this functionality supposed to work with .NET Core 3.1?

[(https://stackoverflow.com/questions/52286286/handling-auto-model-validation)]

I have implemented this by way of creating my own class derived from `IConfigureOptions<MvcOptions>` and register that in startup  immediately after the call to `services.Configure`

`services.TryAddEnumerable(ServiceDescriptor.Transient<IConfigureOptions<MvcOptions>, MyOptionsSetup>());`

but I only ever see resources in English.

I realise this is because the locale is being set in the Middleware call to app.UseRequestLocalization(locOptions.Value);
which is happening a long time after we setup the builder...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Have you looked at the documentation here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#using-one-resource-string-for-multiple-classes

**Comment by MCFHTAGENTS** [comment]
I am currently using the 
` .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix, opts => { opts.ResourcesPath = "Resources"; }).AddDataAnnotationsLocalization()`
with no arguments in the AddDataAnnotationsLocalization.
it is the localisation for attributes like [Required] that is not performed and I am sure I had it working in 2.1.
On this I have no idea what 

> In ASP.NET Core MVC 1.1.0 and higher, non-validation attributes are localized.
means

Google is not your friend as there is loads of legacy code out there too.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
