### ISSUE TITLE
Access ControllerContext using HttpContext outside of the Controller

### ISSUE THREAD

**Issue by keerthimaryala18** [dotnet/aspnetcore#18706]
I am need of writing some custom error handling around a Controller Type and this exception handling is handled in the Middleware of my AspNetCore app. 

I do have access to the HttpContext here

         public class CustomExceptionHandler
        {
               private readonly ILogger _logger;
               public CustomExceptionHandler(ILogger logger)
               {
                       _logger = logger;
               }
               public async Task InvokeAsync(HttpContext context)
               {
                     // Conditional code for Controller Type
               }
        }

I have no access to ActionDescriptor at this point and I do not get the Controller Type Info although I have access to RouteData. 

Is there a way to retrieve a ControllerContext using an HttpContext in the middleware?

**Comment by davidfowl** [comment]
What version of ASP.NET Core are you using?

**Comment by pranavkm** [comment]
If you're using endpoint routing and targeting .NET Core 3.0 or newer, you could inspect the endpoint metadata:

```C#
var endpoint = context.GetEndpoint();
var actionDescriptor = endpoint?.Metadata.GetMetadata<ControllerActionDescriptor>();
```

There's a less clear way of doing this with traditional routing. You could use a filter to stash away metadata in the `HttpContext` that your middleware could later inspect. At that point, you might as well consider writing a globally registered exception filter.

**Comment by keerthimaryala18** [comment]
> What version of ASP.NET Core are you using?

@davidfowl Targeting ASP.NET Core 2.2

**Comment by davidfowl** [comment]
@keerthimaryala18 targeting 2.2 there's no easy way to get the `ActionDescriptor` in middleware
