### ISSUE TITLE
[Blazor server-side] Error: There was an error applying batch "xxx"

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#18708]
### Describe the bug
When JS calls dotnet function which sets html to variable it invokes error on adding new component (in my case FileUpload component)
`Error: There was an error applying batch [number]`

### To Reproduce
Component HTML
```
<article id="article-body">
  @((MarkupString)Model.Body)
</article>

@for(int i = 0; i < attachments; i++)
{
   <label for="Attachment-@i">Attachment</label>

   <FileUpload Async="true" @ref="@FileUploads[i]"></FileUpload>
}

<button type="button" @onclick="AddAttachment">Add</button>
```

Component code
```
int attachments = 1;

List<FileUpload> FileUploads = new List<FileUpload>(8)
{
    new FileUpload(),
    new FileUpload()
};

void AddAttachment()
{
    FileUploads.Add(new FileUpload());

    attachments++;

    StateHasChanged();
}

[JSInvokable]
public void SetHtml(string html) => Model.Body = html;
```
Js code
`dotnet.invokeMethodAsync("SetHtml", "random html string");`

Got Exceptions? Include both the message and the stack trace
```blazor.server.js:15 [2020-01-31T10:50:08.338Z] Error: There was an error applying batch 19.
e.log @ blazor.server.js:15
blazor.server.js:8 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at e (blazor.server.js:8)
    at Object.e [as removeLogicalChild] (blazor.server.js:8)
    at e.applyEdits (blazor.server.js:8)
    at e.updateComponent (blazor.server.js:8)
    at Object.t.renderBatch (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:15)
    at blazor.server.js:15
    at Object.next (blazor.server.js:15)
    at blazor.server.js:15
    at new Promise (<anonymous>)
blazor.server.js:15 [2020-01-31T10:50:08.392Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read property 'removeChild' of null)
 ---> System.InvalidOperationException: TypeError: Cannot read property 'removeChild' of null
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```

### Further technical details
- ASP.NET Core version 3.1.0
- The IDE: VS 16.4.0

Btw is there any simple solution how to make List FileUpload references? I dont like this way. I guess that's why its crashing. 

If I upload attachments before editing html then it works. 
Component keeps working if I comment out `Model.Body = html;`

**Comment by glararan** [comment]
Hmm it seems that QuillJs editor changed html hierarchy via JS and Blazor is not able to map it anymore via
```
<article id="article-body">
  @((MarkupString)Model.Body)
</article>
```

Solution is to set loaded content via js and retreive content also via js

If devs dont see any problem to solve then close it :)

**Comment by SteveSandersonMS** [comment]
@glararan I think you're right. If something mutates the DOM in such a way that Blazor can no longer apply future diffs, it's not a supported scenarios. When using JS that mutates the DOM, you need to be sure that it only acts inside an element that Blazor itself sees as empty.

For example, using JS to put content inside this is valid:

```razor
<div @ref="@myElem"></div>
```

But using JS to put content inside this is *not* valid:

```razor
<div @ref="@myElem">
    @foreach (var ... in ...) { <other elems /> }
</div>
```

**Comment by glararan** [comment]
@SteveSandersonMS good to know. Thanks for reply
