### ISSUE TITLE
Blazor server SignalR load-balancing

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#18705]
Is there a recommended way or guide on how to configure SignalR in a  Blazor server app when used with a load balancer?

I have a kubernetes cluster with the app deployed in 2 replicas and it seems it cannot establish a SignalR connection with those pods.

Thanks in advance.

**Comment by MitchellNZ** [comment]
You can use something like a [Redis cache backplane](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.1) for doing this.
Hope this helps.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@anurse any recommendations here?

**Comment by mihaimyh** [comment]
I've made it work with a Nginx ingress having sticky sessions enabled.

**Comment by davidfowl** [comment]
Yes that's the recommendation.

**Comment by anurse** [comment]
The blazor docs have details on the hosting requirements: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.1

**Comment by mihaimyh** [comment]
Thanks for suggestions, I got it working.
