### ISSUE TITLE
Blazor - Clarification about assemblies and unload / reload?

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#18702]
### Is your feature request related to a problem? Please describe.
I am investigating a blazor wasm "page / component reload" mechanism. I have got a crude implementation already that reloads the entire site when any dll's, css, or html changes on the backend are detected. For code changes this relies in a dotnet build which takes about 10 seconds to complete, and then the reload of the entire application when the page refreshes adds another couple of seconds - not the best. I'm now wondering if this can be improved.

I have built a blazor component that I can place on a page. I have a simple one page blazor app, that shows this component. - i'll refer to it as the "Host Component"

The Host component uses an argument in the query string to dynamically load a component from another assembly by:

1. Work out if the assembly is already loaded into the current app domain, otherwise fetch it dynamically from the server.
2. Find the target component type in that assembly, and render it.

This mechanism works. If all I wanted to do was lazy load a component that would be fine - mission accomplished. I see there is seperate discussion on that here - not quite sure what the blocker is to people doing this today as I have: https://github.com/dotnet/aspnetcore/issues/5465

However my overall goal isn't just lazy loading, it's to improve productivity with "hot reload.". Reloading the entire application when a minor change is made to one component is not efficient. However if I can just reload this single assembly that changed - that might be much speedier.

So my question is, my Host Component currently loads the target assembly dynamically into the current AppDomain. I am assuming blazor wasm is still mono based, but without support for multiple AppDomains - is that correct? If so, is it just pure impossible right now to be able to "Unload" an existing assembly - or essentially, load a newer version of that assembly into the AppDomain? This is the last piece of the puzzle that would allow me to achieve hot reload of a component from a dynamic assembly - My host component would only need to load the newer assembly, then switch from rendering the type in the old assembly to the type in the newer assembly. I wouldn't even technically need to unload the old assembly, I just need to be able to load also a newer version of it.

### Describe the solution you'd like
I'd love the ability from a blazor wasm application, to be able to unload / reload an assembly. Or load a newer version of an assembly into the same AppDomain for use, to allow me to write some Hot Reload mechanism for components in dynamically loaded assemblies.

### Additional context
Blazor is good, but productivity over other tools sucks - I miss being able to quickly see changes reflected as I change HTML, css, code etc - something which was solved in the javascript world a long time ago.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator.
@lewing is this something you can have suggestions for?

@dazinator we're also working hard to improve the dev inner-loop but nothing concrete at the moment.

**Comment by YairHalberstadt** [comment]
I'm working on creating a WebIde for my experimental programming language using blazor wasm. I'm hoping to achieve something similar to https://sharplab.io/.

To do this I need to automatically compile and run the input every time the user edits the code. This obviously requires loading the assembly. However without the ability to unload these assemblies afterwards this would quickly become impractical, with thousands of small assemblies that can't be unloaded.

As such, the ability to unload assemblies is critical for my use case.
