### ISSUE TITLE
Unhandled exception. Mono.Linker.MarkException

### ISSUE THREAD

**Issue by americanslon** [dotnet/aspnetcore#18701]
All of the sudden started getting this 

`Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.IDisposable Microsoft.Extensions.Logging.Logger::BeginScope(TState)' in assembly: 'Microsoft.Extensions.Logging.dll`

I don't even know what else information to provide because it seemingly appeared out of nowhere. Last thing I did before that was connected to azure insights.

I have reinstalled blazor, I have removed the .nuget folder...still the same error.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share some more details about what's your scenario, what does your app look like and what did happen for this exception to show up?

**Comment by mkArtakMSFT** [comment]
All that will be helpful for the investigation, which based on this exception seems to be something related to the Mono runtime.

**Comment by americanslon** [comment]
I have a pretty basic client side blazor app served up by and even more basic netcore web app. 
Everything is on the latest preview. 

I was adding serilog to the netcore portion. Added the file sink, then the azure insights sink. Everything is fine.  Enabled insights. Everything is fine - exception get logged, show up in the insights and files all good. Then literally the next build or so this error. 

As for mono...I don't even know what that is. I am not doing anything with it that blazor isn't already doing.

**Comment by americanslon** [comment]
The only thing that seems to "fix" that error is putting `<BlazorLinkOnBuild >false</BlazorLinkOnBuild>`  in `Blazor.MonoRuntime.Targets` that I fished out from [here](https://github.com/mono/mono/issues/16063)

I put fix in quotes because editing some file that I have never heard of and don't know what it could mean seems like an odd  fix. Also note that the people from that issue don't think it's a mono thing.

**Comment by Madhust** [comment]
@mkArtakMSFT I have faced similar exception. 

> C:\Users\MadhuSudhananP\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : Unhandled exception. Mono.Cecil.ResolutionException: Failed to resolve System.Threading.CancellationToken [D:\Work\temp\TreeShakingTest\TreeShakingTest.csproj]
C:\Users\MadhuSudhananP\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : ILLink failed with exit code -532462766.

csproj file used in my project is as follows.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.2.0-preview1.20073.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.2.0-preview1.20073.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.2.0-preview1.20073.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview1.20073.1" />
  </ItemGroup>
</Project>
```
Disabling blazor link on build resolves this problem but I don`t want to do that so as I am experimenting on assembly trimming.

Any help would be appreciated. Thanks !!

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18651
