### ISSUE TITLE
Share authentication cookie between app which are using Data Protection and machineKey

### ISSUE THREAD

**Issue by MarekKu** [dotnet/aspnetcore#18700]
# Issue Title

Share authentication cookie between app which are using Data Protection and machineKey

# General

The application responsible for login shares a cookie using machineKey. (it is impossible to use Data Protection there). New .net core application tries to use this cookie. I don't know how to configure this scenario, assuming it is possible. Please provide info if such integration is possible. In case it is possible please provide configuration needed on .net core application side.

**Comment by anurse** [comment]
Yep, thanks @scalablecory .

@MarekKu I don't believe there's any built-in support for this. (+ @blowdart @Tratcher)

**Comment by blowdart** [comment]
Correct, the only way to do it is the change the old app to use data protection, it does not, and will not work the other way.
