### ISSUE TITLE
french special characters get badly encoded

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#18714]
calling this in a cshtml view ( asp.net core 3 )
` @Localizer["Dinner"]`
should render this:
`Dîner`
but instead is rendering this:
`D&#xEE;ner`

---
my solution for now is to call: `@Html.Raw(Localizer["Dinner"])`

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by omuleanu** [comment]
ok, the problem is that the js that I'm using is also encoding the value, and it is encoding the '&' character
