### ISSUE TITLE
Where to get the private key which is used to sign ASP.NET Core assemblies?

### ISSUE THREAD

**Issue by victorm1710** [dotnet/aspnetcore#18710]
Is it true that private key which is used to sign ASP.NET Core assemblies is stored publicly (please see the screenshot below)? If yes, where is it stored?

![image](https://user-images.githubusercontent.com/44471919/73547030-404b4000-444f-11ea-87d9-cdd383f4008e.png)

Link to the issue from the screenshot above: https://github.com/dotnet/aspnetcore/issues/3524

**Comment by blowdart** [comment]
The strong name key? Yes, it's in the repo. 

https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/build/Key.snk

**Comment by victorm1710** [comment]
> The strong name key? Yes, it's in the repo.
> 
> https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/build/Key.snk

Thank you, blowdart!
