### ISSUE TITLE
Granular linker assembly file is not regenerated when references are updated

### ISSUE THREAD

**Issue by schwarmau** [dotnet/aspnetcore#18721]
### Technical Details
I'm working with ASP.NET Core 3.1.1 and I'm working in a hosted Blazor WebAssembly project using version 3.2.0-preview1.20073.1 of that. The client SignalR package I'm using is up-to-date (3.1.1).

### Describe the bug
As described [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#use-newtonsoftjson-in-an-aspnet-core-30-signalr-project), SignalR by default is using System.Text.Json for serialization, but you can still opt to use Newtonsoft.Json. The instructions include using an extension method in Startup.cs on the server side and where the hub connection is built on the client side. When I followed these instructions I got the following error:
`WASM: System.InvalidOperationException: A suitable constructor for type 'Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.`
After taking a peek at source code, I resolved the issue by adding `builder.Services.AddSingleton<IHubProtocol, NewtonsoftJsonHubProtocol>(sp => new NewtonsoftJsonHubProtocol());` to Program.cs on the client side. My Program.cs looks like this:
```
using System.Threading.Tasks;
using Microsoft.AspNetCore.Blazor.Hosting;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.Extensions.DependencyInjection;

namespace BlazorTestApp.Client
{
	public class Program
	{
		public static async Task Main(string[] args)
		{
			var builder = WebAssemblyHostBuilder.CreateDefault(args);
			builder.RootComponents.Add<App>("app");
			builder.Services.AddSingleton<IHubProtocol, NewtonsoftJsonHubProtocol>(sp => new NewtonsoftJsonHubProtocol());

			await builder.Build().RunAsync();
		}
	}
}
```

I'm not sure if this is an issue in other ASP.NET Core apps, or just Blazor WebAssembly. It seems like, unless I missed something or am doing something wrong, either the AddNewtonsoftJsonProtocol() extension method isn't working correctly, or the documentation needs to be updated.

### To Reproduce

Follow the instructions [here](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/) under the "Support for the .NET SignalR Client" section. Next, follow the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#use-newtonsoftjson-in-an-aspnet-core-30-signalr-project) to use Newtonsoft.Json. Simply run the app and you should see the error in the browser console.

**Comment by BrennanConroy** [comment]
Trigger a full rebuild to fix the issue.

@pranavkm something weird with blazor not building the blazor.boot.json when adding new deps?

**Comment by schwarmau** [comment]
> Trigger a full rebuild to fix the issue.
> 
> @pranavkm something weird with blazor not building the blazor.boot.json when adding new deps?

Yep, that worked for me. I feel a little silly. Thanks for looking into it.

**Comment by pranavkm** [comment]
@schwarmau I'm going to leave this issue open to figure out why the initial build failed.
