### ISSUE TITLE
razor class library & typescript tooling not working

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#18725]
# Describe the bug
When developing a razor class library component with typescript, typescript intelliscence fails to/import library from the npm packages.json

### To Reproduce
create a razor class library
cmd where project is located open folder 
run npm install Microsoft-cognitiveservices-speech-sdk
create typescript file inside project
import { SpeechConfig } from './' -> note intellisence fails

**Comment by javiercn** [comment]
@grahamehorner Thanks for contacting us.

A few questions:
* Does this work on an asp.net core web application?
  * If it does, do you see any difference between the csproj in the webapp and the razor class library You should see this package installed https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild (or at least suggested by VS) for typescript to work properly, I believe.
* What visual studio version are you using?
We did work in this area to enable the same level of support in Razor Class Libraries as in ASP.NET Core web applications, but I'm not sure of the details.

If this doesn't work in a regular asp.net core application, it is likely you are missing some configuration needed to make it work. I would suggest you open an issue on the typescript repo if that is the case or try through the Visual Studio report a problem dialog. See https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

**Comment by grahamehorner** [comment]
@javiercn 

creating the razor component inside the ASP.NET Core Web Application works as expected;
the reference to the TypeScript.MSBuild is included in bot projects.

I'm using VS 2019 v16.4.4

as aside note the wwwroot is show as a standard folder; and the add-> Client-Side Library... tooling also doesn't work when developing a Razor Library

**Comment by javiercn** [comment]
@grahamehorner thanks for the additional details.

Where are you placing your typescript files within the razor class library, does moving them to a different folder fix the issue? (It might be interfering with Static Web Assets)

**Comment by javiercn** [comment]
Also, check this and see if that fixes it https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#typescript-integration
