### ISSUE TITLE
DefaultAuthorizationHandlerProvider always requires all authorization handlers

### ISSUE THREAD

**Issue by theo-albers** [dotnet/aspnetcore#18728]
In some of our projects we use the requirement policy approach to cut off requests based on request specific constraints. This could be fine grained authorization towards a resource. Such custom authorisation handler has for instance a service dependency, which has a database dependency.

Typically you add the authorization attribute as global filter to your API controllers. Some controller actions might have the AllowAnonymous attribute. Now for all authorization required controller actions, the pipeline will resolve all authorization handlers, for every request. If you have lots of authorization handlers (requirements) which have dependencies, the system creates DI overhead.

I have illustrated the case with this web project. See the TestCaseSetup class for more information:
[FooWeb.zip](https://github.com/dotnet/aspnetcore/files/4142519/FooWeb.zip)

The challenge is the DefaultAuthorizationHandlerProvider. This wants all registered AuthorizationHandler instances in it's constructor. Later on all handlers will be invoked and they have to check for themselves if they handle a Requirement. 

This mechanism works fine when the authorization handlers are registered as Singleton. As soon as you use DI for scoped services, the system adds overhead. You could also have side effects, because you might not realize all handlers are resolved on each request. Maybe you depend on a tenant specific context in one of the handlers which can't be resolved in all controller action types. Since all handlers are resolved, you request might unexpectedly fail due to this.

Replacing the DefaultAuthorizationHandlerProvider doesn't seem like a good option, since you would like to have some Requirement <--> AuthorizationHandler mapping, I guess. Making the provider resolve handlers smarter implies you add runtime cost to every request as well.

**Comment by anurse** [comment]
Is your goal here to have a multi-tenant AuthorizationHandlerProvider that can resolve different sets of handlers for different tenants? In general, multi-tenant apps are going to need to manage a DI container per-tenant ([Orchard](https://github.com/OrchardCMS/OrchardCore) does this, for example) because most of ASP.NET Core (not just Authorization) isn't suited for multiple tenants in the same DI container.

**Comment by theo-albers** [comment]
No, the goal is to add row level authorization as cross cutting concern. In this particular project we wanted to follow the same pattern, but here we have a tenant claim as part of the claims principal. 

The point is basically:

1) the documentation states that you can use authorization handlers with any lifetime scope. See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1 

> The preceding code registers MinimumAgeHandler as a singleton by invoking services.AddSingleton<IAuthorizationHandler, MinimumAgeHandler>();. Handlers can be registered using any of the built-in service lifetimes

Is this claim correct or are authorization handlers meant to do more stateless work? At this point the documentation is not stating that all handlers will be resolved at runtime for every request. If that's by design, OK. In that case we might have to use another pattern. I'm questioning this approach internally anyway, since there are two problems with content based auth via handlers:
- they don't have access to the materialized model, so basically the check is too early
- we fetch data from the database to check access, but we have to do it once more in the request pipeline to actually work with the data. This is for me the biggest issue.

2)  if handlers are supposed to work as documented, why are they all resolved for every request? In that case we might have to investigate if there is better approach to resolve the required policy handlers.
