### ISSUE TITLE
System.IO.Pipelines in latest 5.0 sdk has System.IO.Pipelines at 4.0.1.0

### ISSUE THREAD

**Issue by mjsabby** [dotnet/aspnetcore#18732]
I get the following error when I try to run an asp.net core 3.1 application on 5.0

` System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Pipelines, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

The reason is that the System.IO.Pipelines is at 4.0.1.0 in the sdk alpha builds.

**Comment by jkotalik** [comment]
@wtgodbe could this be related to what we were seeing in aspnetcore tooling?

**Comment by wtgodbe** [comment]
No, this is something else. Likely related to some weirdness with runtime version & targeting packs. I'll take a look later today

**Comment by dougbu** [comment]
Definitely at `5.0.0.0` in the RC2 targeting packs.

**Comment by dougbu** [comment]
(Might have happened in daily builds due to confusion about where System.IO.Pipelines was going to ship.)
