### ISSUE TITLE
Blazor - Add test cases that uses an F# library.

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/aspnetcore#18731]
In order to prevent bugs like https://github.com/mono/linker/issues/927#issuecomment-581080126
Please add some test cases that utilizes an F# library.

**Comment by javiercn** [comment]
@OnurGumus thanks for contacting us.

We believe those tests belong in the mono repository rather than in Blazor as the issue you reference is a linker issue and is not specific to Blazor.

**Comment by OnurGumus** [comment]
@javiercn respectfully I disagree.  I think Blazor should have a test case for that and should not update a newer mono runtime if there is an error with it.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @OnurGumus. We will work with the Mono team to get some coverage for this.
