### ISSUE TITLE
use AddOpenIdConnect when application is already started

### ISSUE THREAD

**Issue by WalterEbbers** [dotnet/aspnetcore#18744]
hi,

We have a asp.net core 2.2 project that enables the user to add Azure AD for logging in and single sign-on. 

To use azure we call AddOpenIdConnect(). The downside of this is that the information for azure must be present at application startup.  

Is there a way to call AddOpenIdConnect() when adding Azure AD to the asp.net core application without restarting the asp.net core application?

We currently use IApplicationLifetime to stop the application, but this does not feel as a fine solution. 

Kind regards, 

Walter

**Comment by brockallen** [comment]
There's a commercial product that does this: https://www.identityserver.com/products/dynamic-authentication-providers

**Comment by WalterEbbers** [comment]
> There's a commercial product that does this: https://www.identityserver.com/products/dynamic-authentication-providers

Thank you for the reply. From this is it save to assume that asp.net core does not supply something like that out of the box?

**Comment by brockallen** [comment]
> Thank you for the reply. From this, is it save to assume that asp.net core does not supply something like that out of the box and we would need a paid solution?

I'm not a representative of Microsoft, so I'll let them answer that.

**Comment by blowdart** [comment]
We do not provide this out of the box.

Whether you need a paid solution or you find a free one is your decision I'm afraid.

**Comment by Tratcher** [comment]
In theory it's possible but it would take a lot of manualy overriding services. I don't think I've seen a complete end-to-end sample yet. Presumably this is how IdentityServer got it working?

**Comment by brockallen** [comment]
> Presumably this is how IdentityServer got it working?

The commercial product is from the IdentityServer EU support org Rock Solid Knowledge. It's not from the IdentityServer OSS folks.

**Comment by WalterEbbers** [comment]
@brockallen @blowdart @Tratcher 
Thank you all for the replies. I will lay this forward to my colleagues and see what will be chosen to do. 

Thnx again all :)
