### ISSUE TITLE
Blazor server looses connection in mobile web browser almost instantly when minimizing app.

### ISSUE THREAD

**Issue by idchlife** [dotnet/aspnetcore#18740]
### Describe the bug
Blazor server looses connection in iOS mobile web browsers, making it impossible to use in production scenarious like "Please enter code we sent you via SMS". We are experiencing this right now, users are stuck without possibility to enter code, because blazor server shows "Attemting to reconnect", which forces users to press "Reload" after failed attempts to reconnect, which makes blazor server force to send new sms, which users could not read (it will produce another broken connection in 1 second after going to sms app instead of browser) etc etc

### To Reproduce
Create any tutorial blazor server app, upload to hosting (linux/nginx), visit through iOS mobile web browser.

Got Exceptions? Include both the message and the stack trace
-->

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@idchlife thanks for contacting us.

You can control the reconnection behavior through the reconnection options, or completely control the server-side Blazor reconnection behavior on the client by providing your own reconnection handler through the blazor options.

On the server you can adjust the time disconnected circuits are kept around and additionally you can use some state management solution to resume the app state on a new circuit, [see these docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1) for reference

```html
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
    Blazor.start({
        reconnectionHandler: customReconnectionHandler,
    });
</script>
```

Here are the interfaces with the options for reference:

https://github.com/dotnet/aspnetcore/blob/6255c1ed960f5277d2e96ac2d0968c2c7e844ce2/src/Components/Web.JS/src/Platform/Circuits/BlazorOptions.ts#L3-L30

**Comment by javiercn** [comment]
I've filed a separate issue to improve the default experience, I'm closing this issue in favor of [this one](https://github.com/dotnet/aspnetcore/issues/18745)
