### ISSUE TITLE
asp.net Core 2.0 application using HealthChecks not working when i used latest dll for AspNetCore.HealthChecks

### ISSUE THREAD

**Issue by ShreekantG** [dotnet/aspnetcore#18746]
<!--

### Describe the bug
I have application built on asp.net core 2.0 , i tried to implement Health Check using asp.net core middle layer registered the services and mapped to "/api/healthcheck". My docker image is getting generated. When i deploy the image to Linux machine and hit health check end point i am not getting any response. But when i debug the code from window machine i am getting the end point response.

Local URl:
http://localhost:50260/api/healthcheck

### To Reproduce
1. Application was built in Asp.net Core 2.0
2. Wanted to include HealthChecks , referenced the new dll files, (AspNetCore.HealthChecks.SqlServer.dll, AspNetCore.HealthChecks.Uris.dll)
3. Following code is written in ConfigureServices()
services.AddHealthChecks()
                    .AddUrlGroup(new System.Uri(idmsHCUrl),
                            name: "x1",
                            failureStatus: HealthStatus.Unhealthy)
                    .AddUrlGroup(new System.Uri(tdsHCUrl),
                            name: "x2",
                            failureStatus: HealthStatus.Unhealthy)
                    .AddUrlGroup(new System.Uri(sesHCUrl),
                            name: "x3",
                            failureStatus: HealthStatus.Unhealthy)
                    .AddUrlGroup(new System.Uri(locHCUrl),
                            name: "x4",
                            failureStatus: HealthStatus.Unhealthy)
                    .AddSqlServer(connectionString: Configuration.GetConnectionString("ApiEntityContainer"),
                            healthQuery: "SELECT 1;",
                            name: "API Database",
                            failureStatus: HealthStatus.Unhealthy,
                            tags: new string[] { "db", "sql", "sqlserver" });
4. Following Configure() method change for config map
var options = new HealthCheckOptions();
                options.ResponseWriter = async (c, r) =>
                {
                    c.Response.ContentType = "application/json";
                    var result = JsonConvert.SerializeObject(new
                    {
                        status = r.Status.ToString(),
                        services = r.Entries.Select(e => new { e.Key, status = e.Value.Status.ToString() })
                    });
                    await c.Response.WriteAsync(result);
                };
                app.UseHealthChecks("/api/healthcheck", options);

5. My application runs properly but when i deploy same in linux machine it is not working
Can you please help to resolve this issue.
Is it allowed to reference those healthcheck dll to asp.net core 2.0 framework or not? 

### Further technical details
- ASP.NET Core version : 2.0
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: I am running 2017 VS.

**Comment by Pilchie** [comment]
This is expected.  Generally if you are running on ASP.NET Core 2.0, you should be using the latest 2.0.x packages.

But you really shouldn't be running on ASP.NET Core 2.0.  It's been out of support for quite a while now. You should upgrade to 2.1 at least, and preferably 3.1.
