### ISSUE TITLE
bug with System.Linq.Dynamic.Core library, code shutdown if linker is enable

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#18741]
Hello guys, im facing a really strange behavior with the usage of System.Linq.Dynamic.Core library.
On webassembly mode, with linker enabled (defaut behavior), the code shutdown when a method of this library is used (no exception, no error in the console, just the code stop when this library  is called).

If i disable the linker, back to normal, but my app make 2 minute to be ready wich is not acceptable.

I try to play with Linker.xml as documented here https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1 but when i use it i have this exception in the browser console "Default constructor not found for type Is.Geckos.Blazor.Client.App", with App.razor the entry point of my app.

I try to add in the linker.xml
````
<assembly fullname="System.Linq.Dynamic.Core" /> //the problematic dll
<assembly fullname="Is.Geckos.Blazor.Client" /> // my blazor app, i don't know if i have to add in the linker it's not really clear
````
but no effect, even if i put nothing in the <linker> node i have this error at startup.

So i don't know what really do now, it's a black box for me.

I take all your suggestions !

PS : i have to put at least 100 console.writeline to debug this problem, my app is really huge there is million of line of code. We really need a better support for webassembly. It's not the first time i see strange behavior in webassembly and was such a pain to debug. im suppose to deploy my app in webassembly in production in few month (i develop in server-side) but i'm more and more worried about this mode. Hope you will make the thing better for the future.

**Comment by marin-bratanov** [comment]
Might be related to this https://github.com/mono/mono/issues/12917

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18679
