### ISSUE TITLE
User impersonation through HTTP header

### ISSUE THREAD

**Issue by Aaronmsv** [dotnet/aspnetcore#18756]
I need to migrate something from ASP.NET Framework to ASP.NET Core and I'd like to check if this implementation is correct. The old implementation was using a custom authentication middleware, but since ASP.NET Core there is only one authentication middleware.

The application needs to allow user impersonation through the REST API, using an HTTP header containing the username of the user to impersonate. To achieve this, I'd add another middleware (just after the authentication middleware) that will handle the impersonation.

So when a request comes in (containing the impersonation header):

1. User gets authenticated by one of multiple authentication schemes by the authentication middleware.
2. The impersonation middleware _replaces_ the current user with the impersonated one, after passing some security checks.
3. The MVC endpoint is called, which uses the impersonated user without really knowing of the change.

For step 2 I see two possibilities. I could add another `ClaimsIdentity` to the `HttpContext`'s `ClaimPrincipal` and then add some logic to resolve the user using the right identity, or I replace the claims on the existing `ClaimsIdentity`.

Does this make sense or is there a better way of achieving this?

**Comment by blowdart** [comment]
Do you really mean impersonation here, i.e. are you trying to change the actual process and have subsequent actions run as the user, or do you meant a custom authentication middleware where the User property on the request contains your user information?

**Comment by Tratcher** [comment]
You don't want to do this as middleware, many components call the auth service directly. IClaimsTransformation might be a better place to hook in:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iclaimstransformation?view=aspnetcore-3.1

**Comment by Aaronmsv** [comment]
@blowdart Yes, the first one. One user is doing actions while pretending to be another one.

@Tratcher I had looked at that as well. I'll give that a go tomorrow, thanks.

**Comment by blowdart** [comment]
We only support "true" impersonation with Windows authentication, unless you're rolling your own here, and it's just swapping out the user property?

**Comment by Aaronmsv** [comment]
@blowdart, well yes, I was thinking of replacing the existing identity myself, adding a new identity to the claims principal and manually mapping the right identity to my internal user, or transforming the claims of the authenticated user to the impersonated one. But I wasn't sure what the right approach was.

**Comment by blowdart** [comment]
In that case Chris's advice to use the claims transformation point is probably your best bet.

**Comment by Aaronmsv** [comment]
I got it working using claims transformation, thanks!
