### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#18754]
We'd like to 

* Provide events that users can subscribe to during drag and drop.
* Have visual cues that shows items being dragged
* Restrict the locations that items can be dropped including providing visual cues

**Comment by danroth27** [comment]
Related issues:

- https://github.com/dotnet/aspnetcore/issues/14132
- https://github.com/dotnet/aspnetcore/issues/15670
- https://github.com/dotnet/aspnetcore/issues/5532

**Comment by Postlagerkarte** [comment]
Hi @danroth27 : Can you please also include  #14792 when considering Drag & Drop? 

Also I currently face the problem that DataTransfer.Files is null when dropping a file.

So basically I would be great if the all properties of the DragEventArgs are available and we read/write access to them!

**Comment by pranavkm** [comment]
More context: https://gist.github.com/MackinnonBuck/374e529e9c3fdb9d228214b4cc79e617. @MackinnonBuck's work is in the “t-mabuc/drag-and-drop” branch in the aspnetcore repository (also linked in the writeup).

**Comment by abspro** [comment]
And how was the lad's internship?  Would like to see this get some love.

**Comment by danroth27** [comment]
After investigating various approaches we've decided that a general purpose drag & drop feature isn't something we can easily add to the Blazor framework due to the following issues:

- There’s a vast range of possible UX designs/requirements for drag-drop including different combinations of:
    - Things that can be highlighted/ghosted/animated while dragging
    - Rules about what can be dropped where and how to warn/animate violations
    - UI experiences when dragging to the edge of scrollable regions, (e.g., speeding up the scrolling when you drag further, doing rubber-band effects)
    - Interactions with keyboard support and accessibility
- Trying to support even 80% of requirements would be very expensive and open a long tail of support issues. 
- There isn’t one standard way to do it. The HTML5 drag/drop APIs are not adequate for most real-world apps (for example, they don’t work at all in iOS). There are lots of different 3rd-party libraries, all talking different opinions on what you want to customize.

Fortunately, it can be relatively straightforward to solve drag/drop in a special-case way according to the needs of one specific app because you can pick out one of the many .js drag/drop libraries that happens to do things with the particular UX you want and call it via JS interop. For example, this [sample](https://github.com/SteveSandersonMS/presentation-2021-01-NDCLondon/tree/master/demo/CalendarApp/src/CalendarApp) uses [draggable.js](https://shopify.github.io/draggable/) and [JS interop](https://github.com/SteveSandersonMS/presentation-2021-01-NDCLondon/blob/master/demo/CalendarApp/src/CalendarApp/wwwroot/calendar-drag.js) to build a mobile-capable drag-drop calendar UI. We think the Blazor community is best suited to decide which approaches to drag & drop are most useful to package and share.

Since we don't plan to add this as a core feature of Blazor, I'm going to go ahead and close this issue.

**Comment by HybridSolutions** [comment]
@danroth27  It would be interesting that Blazor team could provide a couple of examples from basic to more advanced showing how to integrate Blazor with one of the libraries out there. I feel there's little support for advanced functionalities and articles out there take time to appear. Also, since Bootstrap is the framework used in default templates, it would be  interesting to see some how to use BS components and deal with the problem of initialization in Blazor components.

I guess it takes time, but it would be nice to see some examples from the makers with the best practices for easier adoption.
