### ISSUE TITLE
Protected browser storage

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#18755]
Finish and ship https://docs.microsoft.com/aspnet/core/blazor/state-management#protected-browser-storage-experimental-package

A lot of the code exists here: https://github.com/aspnet/AspLabs/tree/master/src/ProtectedBrowserStorage/src

* [ ] This feature relies on a server feature. This packaging requirement will likely requiring having to ship it separately from the other all-purpose Blazor component package.
* [ ] Things to address: Add an optional `scope` to the Get \ Set \ Delete APIs that allows specifying additional scope for data protection

**Comment by brockallen** [comment]
What makes the storage "protected"?

**Comment by BrunoZell** [comment]
@brockallen It uses [ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-3.1).
