### ISSUE TITLE
Update Razor compiler to use global:: more liberally

### ISSUE THREAD

**Issue by MichelArendt** [dotnet/aspnetcore#18757]
**Issue:** In a Razor Component any variables named "Microsoft" reproduce the error (variable type on the error message changes accordingly):

> Error	CS1061	'string' does not contain a definition for 'AspNetCore' and no accessible extension method 'AspNetCore' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)

**Question:** Is this an issue or by design?

**Project details and files:** This is a Razor Class Library project.

### .csproj
```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <LangVersion>8</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="3.1.1" />
  </ItemGroup>

</Project>
```

### LoginFormUserComponent.razor
```
@using SBL.Models.User.Login.OpenId

<div class="login">
    <div class="page-title">
        Login
    </div>

    <p>
        To login you must use one of the available Social Login options below:
    </p>

    <div class="social-login__container">
        <SocialButtonLoginComponent Provider="@Facebook" Image="/images/social/brands/facebook_37x37.png" />
        <SocialButtonLoginComponent Provider="@Google" Image="/images/social/brands/google_37x37.png" />
        @*<SocialButtonLoginComponent Provider="@Microsoft" Image="/images/social/brands/microsoft_37x37.png" />*@
        <SocialButtonLoginComponent Provider="@Twitter" Image="/images/social/brands/twitter_37x37.png" />
    </div>
</div>

@code {
    [Parameter]
    public ProviderOpenIdModel? Facebook { get; set; } = null;

    [Parameter]
    public ProviderOpenIdModel? Google { get; set; } = null;

    //[Parameter]
    //public ProviderOpenIdModel? Microsoft { get; set; } = null; // ERROR

    [Parameter]
    public ProviderOpenIdModel? Twitter { get; set; } = null;

    public string Microsoft { get; set; } // ERROR
}
```

**Comments:**
I started getting this random error and found out that apparently I cannot write "Microsoft" as a variable name in a Razor component. 

I was unable to find the search keywords for anything similar to this.

I initially thought that there was a reference issue on my project when I realized the commented parameter was the issue. I then tried using a native variable type to see if the issue persisted - and it did.

It's not really an issue I need fixing per say - just wondering why this happens.

Thanks in advance!

**Comment by pranavkm** [comment]
Thanks for the issue report @MichelArendt. This looks like a bug in Razor's code generation. Unfortunately there isn't a very good workaround for this outside of using a different member name.

A fix for this would be to globally qualify the `Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck` call.

```
protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder) 
        {
            __builder.AddMarkupContent(0, "<h1>Hello, world!</h1>\r\n\r\nWelcome to your new app.\r\n\r\n");
            __builder.OpenComponent<b.Pages.Counter>(1);
            __builder.AddAttribute(2, "Model", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<b.MyModel>( // here
                Microsoft
            ));
            __builder.CloseComponent();
        }

    public MyModel Microsoft { get; set; } // ERROR
```

**Comment by Rick-Anderson** [comment]
@pranavkm  I can make a doc issue of this and and `Microsoft` to [Razor reserved keywords](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#razor-reserved-keywords).  Let me know if you'd like to go that route.

**Comment by pranavkm** [comment]
@Rick-Anderson this is not a reserved keyword though. Presumably once we fix the underlying issue, this should work.

**Comment by MajdajkD** [comment]
https://github.com/dotnet/aspnetcore/issues/13220#issuecomment-585920915

**Comment by MajdajkD** [comment]
Same old thing?
https://github.com/dotnet/aspnetcore/issues/13220

**Comment by diegofrata** [comment]
@pranavkm the problem with this issue is that **there is no workaround** other than casting the offending type declaration to object or dynamic. It's not possible to simply rename a type I might not own or refactor an entire application changing the namespace whenever there's a conflict. 

Whilst it's a rare issue, when it occurs it is a showstopper. Any chance this can be pulled out of the backlog and shipped as part of .NET 5?

**Comment by pranavkm** [comment]
@diegofrata at this point we're close to wrapping up changes for 5.0. I'll have a look to see how trivial this change is, but I suspect it's fairly involved would make it more likely this would only be fixed in the next major release.

**Comment by teroneko** [comment]
The most markable workaround as component author is to design the component statically => drop `.razor` by moving `@code {...}` and render logic to `.cs` and finally delete the `.razor` file. If not a single razor file is generated the above problem does not occur.

**Comment by Eilon** [comment]
I saw something similar to this where I had a Razor component with the same name as the namespace.

E.g.:

`MyTestComponent.csproj`
- `MyTestComponent.razor`. Full type name = `MyTestComponent.MyTestComponent`
- `AnotherComponent.razor`. In here try to use `<MyTestComponent ... />` and you get C# compiler errors because the generated code is ambiguous between the namespace `MyTestComponent` and the type `MyTestComponent`.

**Comment by TanayParikh** [comment]
Repro app: https://github.com/jirikanda/Blazor-CascadingTypeParameterIssue
