### ISSUE TITLE
blazor.boot.json (and other assets) is 404 when you Publish a Blazor WASM app with disabled linker through Visual studio

### ISSUE THREAD

**Issue by marin-bratanov** [dotnet/aspnetcore#18752]
### Describe the bug

The Visual Studio Publish process does not generate all assets for a Blazor WASM app that has the Linker disabled - they are missing from the `_framework` folder.

The CLI seems to work fine.

### To Reproduce

1. Create an ASP.NET Core hosted Blazor WASM app (I have not tested a non-hosted one yet, the issue may be the same)

1. Disable the Linker (add this to the Blazor `.csproj` file: ` <BlazorLinkOnBuild>false</BlazorLinkOnBuild>`)

1. In VS, right click the Server project, select Publish, and publish to a folder

1. Host this on IIS and access the app

Actual: The app never loads and starts, because the `blazor.boot.json` file is `404`. If you open the publish folder, the client app is missing most of the assets from the `_framework` folder.

Expected: a proper publish output that works.

### Further technical details
- ASP.NET Core version: 3.1.1
- Include the output of `dotnet --info`

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014883\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS 2019 Preview - 16.5.0 Preview 2; Visual Studio 2019 - 16.4.4

**Comment by zbecknell** [comment]
Great to see a PR for this already out there!  I discovered this issue occurs with `dotnet watch run` as well with linking disabled on the client project.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/commit/376f378c0acf08188013fb6811507ffb0ea04eba
