### ISSUE TITLE
[Blazor] - Refactor Rename of a property in a view model fails 

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#18753]
### Describe the bug
When we attempt to refactor-> rename a view model property that is referenced in a razor component the rename will fail due to something to do with the razor component temp file .g.cs.

### To Reproduce
Try to refactor->rename a property in a view model or code behind file referenced by a razor component.

I attached a zip file with the ActivityLog errors. Also contain dotnet --info output

### Further technical details
- ASP.NET Core version - 3.1.101 ref in global.json
[ActivityLog.zip](https://github.com/dotnet/aspnetcore/files/4148132/ActivityLog.zip)

- The IDE = VS 2019 16.4.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is something we have fixed already and the fix will be coming up wiht the 5.0 release.
@NTaylorMullen do you have the issue to dupe this with? Thanks!

**Comment by chassq** [comment]
So looks like we will have this issue until November 2020? Sound right? Just making sure.

**Comment by NTaylorMullen** [comment]
> So looks like we will have this issue until November 2020? Sound right? Just making sure.

Most likely yes.

If you'd like to workaround the issue typically opening the Razor file(s) that has/have the associated C# piece will enable rename to work.


Duping to https://github.com/dotnet/aspnetcore/issues/14278

**Comment by chassq** [comment]
Thank you!
