### ISSUE TITLE
Add Razor theme to properly colorize Razor constructs in Visual Studio.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#18769]
Today in Visual Studio we have Razor syntactic colorization but all Razor constructs are colored blue. We should tie this to the existence Razor `@` classification or fall back to our own in the case the Razor workload is not installed.

Best practice is to
- Create a `ClassificationFormatDefinition` in Core VS that's used to colorize Razor constructs in the absense of the Razor workload.
- Add a .tmTheme side-by-side our grammar to associate our Razor constructs with the `ClassificationFormatDefinition`
- Move the existing Razor classifications to use ours (we'd name them the same so the user wouldn't see the difference).

For this issue we'll probably create our own `ClassificationFormatDefinition` that doesn't go in Core VS yet (shipped as part of our extension) as a stepping stone to properly colorize just the Razor LSP editor scenarios.

**Comment by NTaylorMullen** [comment]
Investigated this a bit further to see what it would mean for VSCode and the result is that [VSCode doesn't currently support theming background colors](https://github.com/microsoft/vscode/issues/3429). This means we can't unify our VSCode colors with Visual Studio because the Razor transition characters have a yellow background with black text. I played around with making those control characters entirely yellow but it just looked wrong.

The work in this issue will provide theming to solely VS and purposefully not include any changes to the VSCode world.

**Comment by warrenbuckley** [comment]
@NTaylorMullen seems like you was trying to do the same as me, in getting a matching style of black on yellow as the big brother VS does - https://github.com/microsoft/vscode/issues/90070

**Comment by NTaylorMullen** [comment]
@warrenbuckley woa, totally didn't read the body of the issue. Ya totally same gist.

**Comment by NTaylorMullen** [comment]
Based on the default theme in Visual Studio looks like we'll need to colorize a few more constructs such as some C# assignments, begin/end angle brackets for HTML and anything else that sticks out. For instance here's colorization today:

![image](https://user-images.githubusercontent.com/2008729/74303560-2ba05f00-4d0f-11ea-998b-a41ecead918c.png)

**Comment by NTaylorMullen** [comment]
Capturing some of @danroth27's epic colorization investigation so we can ensure we work applicable pieces into VS.

Token | Color | Notes
-- | -- | --
razorTagHelperElement | #800080, bold | Same color used by VS light theme
razorTagHelperAttribute | #800080, bold | Same color used by VS light theme
razorTransition | #C586C0 | Same as Razor directives and C# using directive
razorDirectiveAttribute | #C586C0 | Same as Razor directives and C# using directive
razorDirectiveAttributeParameter | #C586C0 | Same as Razor directives and C# using directive

![image](https://user-images.githubusercontent.com/2008729/76491636-72a37200-63eb-11ea-8455-885ab77d0c2e.png)

![image](https://user-images.githubusercontent.com/2008729/76491666-8353e800-63eb-11ea-8c08-40a0be455b26.png)
