### ISSUE TITLE
Logs from WebHost.Run are not written to ApplicationInsights when configuring AddApplicationInsightsTelemetry in ConfigureServices

### ISSUE THREAD

**Issue by arabelaa** [dotnet/aspnetcore#18762]
### Describe the bug
I want to log exceptions that occur when running the webhost. See below the code I used in Program.cs.
The strange part I noticed is that when adding  `           services.AddApplicationInsightsTelemetry();
` in `ConfigureServices` the logs are not pushed to AI. If I remove the registration it works perfectly fine. I did the exact steps with a sample  ASP.NET Core and the same behavior. 

### To Reproduce
``` C#
 
var host = CreateWebHostBuilder(args).Build();
            var logger = host.Services.GetService<ILogger<Program>>();
            try
            {
                host.Run();
            }
            catch (Exception exception)
            {
                logger.LogCritical(exception, "Host running error");
                //wait for logger
                Task.Delay(TimeSpan.FromSeconds(60)).GetAwaiter().GetResult();
                throw;
            }

public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging((context, builder) =>
                    {
                        builder.AddApplicationInsights(
                            context.Configuration.GetValue<string>(
                                "ApplicationInsights:InstrumentationKey"));
                    }
                );
     }
```

Got Exceptions? Include both the message and the stack trace

### Further technical details
- ASP.NET Core version 2.2
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
- The IDE (VS) you're running on, and it's version

**Comment by anurse** [comment]
> * ASP.NET Core version 2.2

FYI, ASP.NET Core 2.2 is [end-of-life and no longer supported](AddApplicationInsightsTelemetry). You should consider moving to 3.1 (the latest LTS) or 2.1 (the previous LTS).

This seems like an issue with App Insights. Can you file the issue on https://github.com/Microsoft/ApplicationInsights-aspnetcore ? If necessary, that team can let us know if it's traced back to an ASP.NET Core framework issue.
