### ISSUE TITLE
Question: Is there an object above Page?

### ISSUE THREAD

**Issue by DataJuggler** [dotnet/aspnetcore#18764]
I developed an easy way for components to talk to their parent / child by using interfaces and it works really well as long as the child is a component, the parent can be another component or a page.

![Image of Login Component](https://datajuggler.com/Images/OnLogin.png)

I would like to do the same thing for a Page, or have 1 Page be a parent of another where if an event or a process finishes on one page, as I am routing to the new page be able to send complex data or messages other than just parameters.

Thanks if I am explaining this right, or if there is some built in way with Routing to do this please tell me how.

I won't go into the details of how I create the interface, if anyone reading is bored and wants to read the article is here:

[Using Interfaces To Communicate Between Components and Pages](https://datajugglerblazor.blogspot.com/)

Thanks for any information.

**Comment by javiercn** [comment]
@DataJuggler thanks for contacting us.

Pages are rendered by the Router component and that is typically part of the App component, which is at the root in the template, but technically they can be referenced from anywhere.
