### ISSUE TITLE
Running dotnet pack on a non-packable web project incorrectly builds default target in referenced projects

### ISSUE THREAD

**Issue by WesleySSmith** [dotnet/aspnetcore#18773]
When running _dotnet pack_ in a web project that uses an SDK of Microsoft.NET.Sdk.Web, if that web project references another library project via a project dependency, then the _dotnet pack_ build will try to perform a build of that referenced library project, even though doing so is unnecessary and unwanted.

In my particular case, I have a solution file with a number of projects.  I want to pack all of the packable projects, but I have other library projects that contain code that doesn't (yet) compile.  When I run a _dotnet pack_, I want the build to only compile the projects that are necessary for packing the packable projects.

### Describe the bug
The pack target is in _NuGet.Build.Tasks.Pack.targets_:
`<Target Name="Pack" DependsOnTargets="$(PackDependsOn)">`

In the web project's build, PackDependsOn is:
`_RemoveWebRootContentFromPackaging; _IntermediatePack; GenerateNuspec; `

_RemoveWebRootContentFromPackaging is added in 
	_Microsoft.NET.Sdk.Razor.StaticWebAssets.targets_:
```
 <PackDependsOn>
      _RemoveWebRootContentFromPackaging;
      $(PackDependsOn)
    </PackDependsOn>
```
Microsoft.NET.Sdk.Razor.StaticWebAssets.targets  is included via: 

_...\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets_
	 ` <Import Project="Microsoft.NET.Sdk.Razor.StaticWebAssets.targets" Condition="'$(StaticWebAssetsEnabled)' == 'true'" />`

The _RemoveWebRootContentFromPackaging target is in _...\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets_:
`<Target Name="_RemoveWebRootContentFromPackaging" DependsOnTargets="ResolveStaticWebAssetsInputs">`

The chain of DependsOnTargets continues with ResolveStaticWebAssetsInputs and then on for quite a few more levels, and eventually contain targets that cause the referenced project to be built with the default target.  

I've found that workaround is to add 
`<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>`
to the web.csproj file, as that causes Microsoft.NET.Sdk.Razor.StaticWebAssets.targets to not be imported, which breaks the chain of includes that causes this error.

### To Reproduce

Download example from https://github.com/WesleySSmith/pack_bug_demo

``` 
dotnet pack web
```

You will see an error from trying to compile error.cs.  The error is intentional, but there's no reason that the build should have tried to compile the lib project, as the web project is not set to be packed.

You can test the workaround by editing the web.csproj file to include `<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>`  Then do a ```dotnet clean web ; dotnet pack web ``` and note that the build is now successful.
 
### Possible fix

The  GenerateNuspec target has a condition so that it only runs if IsPackable is true.  Maybe add that same condition to _RemoveWebRootContentFromPackaging

```
<Target Name="GenerateNuspec" DependsOnTargets="$(GenerateNuspecDependsOn);_CalculateInputsOutputsForPack;_GetProjectReferenceVersions;_InitializeNuspecRepositoryInformationProperties" Condition="$(IsPackable) == 'true'"
          Inputs="@(NuGetPackInput)" Outputs="@(NuGetPackOutput)">
```

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@WesleySSmith thanks for contacting us.

I'm not sure that packing web projects is something that we've ever supported. I would be interested in understanding what your scenario for needing this is.

As you mentioned in the issue, this is something that you can avoid by passing `<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>` to the pack project.

You can do this from the CLI as follows:
`dotnet pack -p:StaticWebAssetsEnabled=false`

We are moving this issue to the backlog and we'll prioritize what action to take in the future.

**Comment by WesleySSmith** [comment]
@javiercn Thanks for your response.  Here's some more detail on why I see this issue:

I've updated my example in https://github.com/WesleySSmith/pack_bug_demo

Now there are 3 projects:

- _lib_ - This has IsPackable = false  set in the .csproj, so is not packable.  Also, it can't compile due to errors.
- _web_ - This is a web project, and so is not packable
- _lib2_ - This library is packable

From the solution directory, I run `dotnet pack`.  What I _want_ to happen is that:

- it skips compiling _lib_ (it's not packable)
- it skips compiling _web_ (it's not packable), 
- it successfully packs _lib2_. 


Instead, what _actually_ happens is:

- it calls the pack target of _lib_, but does nothing because it's not packable) _This is correct_
- it calls the pack target of _web_, then a long chain of target dependencies causes it to build the default targets of _lib_, which fails, due to the error in the code.

If the StaticWebAssetsEnabled=false workaround is enabled, then the correct thing happens (_lib_ and _web_ are skipped, _lib2_ is packed)

To be clear, I don't want to pack the _web_ project - I want it to just do nothing for the web project.


As to the exact reason why I need to pack a solution that has projects that won't compile:  I have a case where I need to:

1. build and pack some libraries from one solution
2. build a second solution that has a package reference to the libraries produced by the first solution. This second solution then creates some .nuget packages.
3. Build the web projects in the first solution (that have a reference to the packages produced by the second solution) .

So, during the initial build on the first solution, the web project can't build due to missing dependencies.    I realize that there are many other potential solutions to this issue that would avoid the bug I'm reporting, including splitting into 3 solutions, modifying my build steps to call _dotnet pack_ only on certain projects, creating a solution build configuration that only builds some projects, etc.  However, the IsPackable property seems like a great solution to this problem, only it doesn't quite work, due to the issue noted here.

**Comment by javiercn** [comment]
@WesleySSmith thanks for the detailed response, 

I think that the best option for you is to disable static web assets explicitly in your project. 

Static Web Assets needs to collect the dependencies from all the referenced projects to allow for scenarios like bundling and minification, so if you try to pack a RCL or a web project that's going to happen.

I recommend you disable static web assets in your web project if that meets your needs.

**Comment by javiercn** [comment]
I believe we changed this as part of 5.0. If this still reproduces, feel free to reopen and we'll re-evaluate.
