### ISSUE TITLE
DI support for auth handler options

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#18772]
https://github.com/dotnet/aspnetcore/issues/9337#issuecomment-581489114
https://github.com/dotnet/aspnetcore/issues/9337#issuecomment-581516787

### Describe the bug
The authentication handlers are configured in Startup.ConfigureServices and have trouble relying on services for any customization. E.g.
```
	.AddCookie(o =>
	{
		o.TicketDataFormat = new CustomDataFormat(settings.Secret, /* Add logging? */);
	});
```

IOptions supports DI for configure callbacks, but the existing overloads aren't compatible with the auth setup pattern.

### Workaround:
```
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie(CookieAuthenticationDefaults.AuthenticationScheme);

            services.AddTransient<IConfigureOptions<CookieAuthenticationOptions>>(sp =>
                new ConfigureNamedOptions<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, o =>
                {
                    o.TicketDataFormat = new CustomDataFormat("secret", sp.GetRequiredService<ILogger<CustomDataFormat>>());
                }));
```

### Proposals:
Some new overloads could make this easier. We should consider if these apply to all of the auth handlers, not just the Cookie samples given here.
```
.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, (o, serviceProvider) =>
{
        o.TicketDataFormat = new CustomDataFormat("secret", sp.GetRequiredService<ILogger<CustomDataFormat>>());
});

.AddCookie<ILogger<CustomDataFormat>>(CookieAuthenticationDefaults.AuthenticationScheme, (o, logger) =>
{
        o.TicketDataFormat = new CustomDataFormat("secret", logger);
});

services.Configure<CookieAuthenticationOptions, ILogger<CustomDataFormat>>(CookieAuthenticationDefaults.AuthenticationScheme, o =>
{
       o.TicketDataFormat = new CustomDataFormat("secret", sp.GetRequiredService<ILogger<CustomDataFormat>>());
});
```

**Comment by anurse** [comment]
> services.Configure<CookieAuthenticationOptions, ILogger<CustomDataFormat>>(CookieAuthenticationDefaults.AuthenticationScheme, o =>

This seems to be well-covered by the [OptionsBuilder API](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#use-di-services-to-configure-options).

> .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, (o, serviceProvider) =>
> .AddCookie<ILogger<CustomDataFormat>>(CookieAuthenticationDefaults.AuthenticationScheme, (o, logger) =>

These are also well-covered by the OptionsBuilder API, the biggest discovery issue here is the named options goop. Maybe this could be useful.

**Comment by Kahbazi** [comment]
`ConfigureOptions` only runs when a new instance of options is requested and for `OptionsMonitor` it runs when config is reloaded. So the only suitable lifetime to use for `TicketDataFormat` is singleton. Could we instead have a `TicketDataFormatCreator` and also `ITicketStoreCreator` so we can pass scoped and transient services to also cover #6946?

**Comment by Tratcher** [comment]
#6946 would benefit from this work but I'd recommend tackling them separately. This issue deals broadly with all auth providers where #6946 is looking for a new feature specific to Cookie Auth.

**Comment by Tratcher** [comment]
@benmccallum yes, this would help you get to the logger. The workaround above should help you do this today.

```
            services.AddTransient<IConfigureOptions<JwtBearerOptions>>(sp =>
                new ConfigureNamedOptions<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, o =>
                {
                    var logger = sp.GetRequiredService<ILogger<CustomDataFormat>>();
                }));
```

**Comment by davidfowl** [comment]
There's a much nicer way to do this since .NET Core 2.1 (I forgo to post it since I last saw it);

```C#
services.AddOptions<JwtBearerOptions>()
             .Configure<ILogger<CustomDataFormat>>((options, logger) =>
             {

             });
```

**Comment by Tratcher** [comment]
@davidfowl that doesn't get you named options, right?

**Comment by Tratcher** [comment]
Oh, right, there's a named overload:
```
services.AddOptions<JwtBearerOptions>("MyJwt")
             .Configure<ILogger<CustomDataFormat>>((options, logger) =>
             {

             });
```

**Comment by benmccallum** [comment]
Thanks guys. Definitely a stupid question, but it was a little tricky to follow the options stuff last time I looked. Would I be calling this method to "register" the options rather than the `AddJwtBearer` extension method? And then it just gets picked up by the auth fx?

**Comment by Tratcher** [comment]
You still need to call AddJwtBearer for other reasons.

**Comment by Kahbazi** [comment]
@Tratcher I would like to work on this.

**Comment by Tratcher** [comment]
@Kahbazi sure. How about starting with this overload and if it works well we can try it for other providers.
```
.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, (o, serviceProvider) =>
{
        var service = serviceProvider.GetRequiredService<MyService>();
});
```

**Comment by Kahbazi** [comment]
@Tratcher I started on `AuthenticationBuilder.AddSchemeHelper` and noticed there's no `Configure` method that gets `Action<TOptions, IServiceProvider> configureOptions` on `OptionsBuilder`. Should I add that first on Extensions repo or start with your workaround first?

**Comment by Tratcher** [comment]
@Kahbazi you should be able to use the existing `services.AddOptions<TOptions>(optionsName).Configure<T>(Action<TOptions, T>)` where T is the IServiceProvider.

**Comment by Kahbazi** [comment]
@Tratcher thanks, I didn't know I could get `IServiceProvider` from `IServiceProvider`!

**Comment by Tratcher** [comment]
ConfigureApplicationCookie and related identity extensions are going to need something similar.
