### ISSUE TITLE
Add better assembly resolve for PublishTrimmed build option for AspNet Core 

### ISSUE THREAD

**Issue by jeremielec** [dotnet/aspnetcore#18781]
### Is your feature request related to a problem? Please describe.

A major feature of .Net core is now to allow project to be publish trimmed (Aka removing unused assembly) and self-contained.
This does  not work fine with AspNet Core, as stated [here](https://docs.microsoft.com/fr-fr/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking), use reflexion.
Therefore used type in controllers are mostly stripped out (Like smtpclient). Occur if the type is created directly in controllers or injected via dependencies injection.

### Describe the solution you'd like
Improve PublishTrimmed option for not remove directly used assembly by controllers.

### Additional context

Attached sample project with a simple route /test

[TrimProblemExample.zip](https://github.com/dotnet/aspnetcore/files/4154216/TrimProblemExample.zip)

This work fine when lauched with visual studio.
This not work with bellow error when lauched with standalone publish with

### dotnet publish WebApplication5.csproj --output out
(note that publish option are in the csproj)

`Unhandled exception. System.TypeLoadException: Could not load type 'System.Net.Mail.SmtpClient' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

**Comment by mmarinchenko** [comment]
**+1**

`dotnet publish` generates `.deps.json` file wich contains `dependencies` section. In my case `System.Resources.ResourceManager` assembly was trimmed out from output directory while existing in `dependencies` section of `.deps.json` file.

Two different dependency resolvers in one command?

**Comment by romanryasne2** [comment]
Any updates?

**Comment by wtgodbe** [comment]
@javiercn @Pilchie thoughts on who should take a look at this?

**Comment by davidfowl** [comment]
Closing as part of https://github.com/dotnet/aspnetcore/issues/27384
