### ISSUE TITLE
Tests: add trace listener to improve Debug.Assert experience

### ISSUE THREAD

**Issue by alefranz** [dotnet/aspnetcore#18785]
`Debug.Assert()` cause the test host process to crash when tests target .NET Core.

This could be quite misleading as it is not usually clear why the tests are not running and could sometimes be not obvious that the rest is not running (the VS UI has recently improved on making it more obvious, so it is less of a problem).

As this project makes heavy use of `Debug.Assert()`, I think it would be nice to improve the experience for contributor.

### Describe the solution you'd like
I've raised an issue on https://github.com/microsoft/vstest/issues/2309 to discuss a global solution for the test runner as it would be nice for anyone to get this better behavior out of the box.

@nohwnd has provided in https://github.com/microsoft/vstest/issues/2309#issuecomment-581918992 a possible implementation of a `TraceListener` to handle this.

Would you be open to include this in the ASP.NET Core tests?

**Comment by nohwnd** [comment]
Just FYI the provided implementation will also throw on any Debug message, there is currently a PR under review for this change that applies to both Debug and Trace, and works as expected.  https://github.com/microsoft/vstest/pull/2335 The change will hopefully be merged soon so you will get it in the next release / preview.

**Comment by nohwnd** [comment]
It's on nuget in pre-release channel now https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/16.6.0-preview-20200226-03

**Comment by dougbu** [comment]
We do not ship anything built using the Debug configuration. That should mean all `Debug.Assert(...)`s are disabled. What scenario would this help with❔

About the only value I can think of would come in conjunction with #11632 but we haven't decided to do anything about that. Or, are you talking about problems that crop up when debugging tests❔

**Comment by wtgodbe** [comment]
Closing this for lack of traction, @alefranz please re-open if you'd like to revive the discussion
