### ISSUE TITLE
ModelBinding in controller using [FromBody] no longer converts strings to numbers and empty strings to nulls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18796]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/887721/modelbinding-in-controller-using-frombody-no-longe.html)._

---
[regression] [worked-in:.Net Core 2.2]
ModelBinding in controller using [FromBody] no longer converts strings to numbers and empty strings to nulls

Previous to .NET Core 3.0, I could pass the following JSON Object and it would be converted successfully to the model

```
{
someNumber: "123",
someNullNumber: ""
}

public class TestModel {
  public int SomeNumber {get; set;}
  public int? someNullNumber {get; set;}
}

[HttpPost()]
public async Task<IActionResult>Create([FromBody] TestModel testModel) {
  // testmodel is null here in .NET Core 3.0, it used to work in 2.2
}
```

---
#### Visual Studio Feedback System on 1/17/2020, 03:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Alex Florin on 1/29/2020, 01:36 PM: 

<p>Please note that this was a breaking change that was not documented.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We switched to use System.Text.Json in ASP.NET Core 3.0 instead of NewtonSoft.JSON and as a result, the default serialization settings might have changed a bit.

I would suggest you try adding back newtonsoft.json as described https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#add-package-references-for-removed-assemblies to see if that fixes your issue.

**Comment by javiercn** [comment]
@mkArtakMSFT moving this to next sprint planning to see if we want to investigate the differences in behavior.

If that's something we are aware of, then lets close this issue and point to the relevant documentation (if any)

**Comment by pranavkm** [comment]
System.Text.Json does not support reading quoted numbers out of the box. There's a workaround listed here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#quoted-numbers

**Comment by AlejandroFlorin** [comment]
This caused numerous issues in my application that were quite difficult to track down (and I still get some reports occasionally). They only show up when client requests are made to specific controller endpoints with specific data.

This should definitely be listed as a breaking change in the release notes.

**Comment by pranavkm** [comment]
@AlejandroFlorin this is covered as part of the changes to the JSON serializer in MVC: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#newtonsoftjson-jsonnet-support. You could consider continuing to use Newtonsoft.Json in your applications if updating the application is problematic.

**Comment by AlejandroFlorin** [comment]
I just switched the project to newtonsoft.json and testing shows it is behaving as before. Thanks.

I had seen that part of the migration doc but it wasn't obvious (at least to me) that it would have affected the controller binding. I'm not using Newtonsoft directly so it never occurred to me that there would be issues. The doc only mentions that there may be missing features and nothing about an actually change to the serialization output nor that it even applies to the model binding in a controller.
