### ISSUE TITLE
[VSCode] Auto completion for methods in razor files is different compared to C# files

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18805]
In a .razor file, the editor appears to perform completion based on suffixes. Best explained as gifs. Here's editing a file inside a cs file.

![C#](https://user-images.githubusercontent.com/174281/73800332-3ede8800-476d-11ea-9e2e-2365e5c74632.gif)

Here's writing the same code inside of a razor file:

![Razor](https://user-images.githubusercontent.com/174281/73800467-a98fc380-476d-11ea-9f55-a7dd09691140.gif)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
