### ISSUE TITLE
Threadpool starvation when using MVC + Newtonsoft Json 

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/aspnetcore#18818]
### Describe the bug
We've been observing threadpool starvation issues since we moved to netcore3.0 on one of our applications, that we were finally able to narrow down using @benaadams awesome [BlockingDetector](https://github.com/benaadams/Ben.BlockingDetector/) package to synchronous reads from the [FileBufferingReadStream](https://github.com/dotnet/aspnetcore/blob/deb51b83f43138570ea86dc17608c45c027deba7/src/Http/WebUtilities/src/FileBufferingReadStream.cs) class. 

This seems to be used by the [NewtonsoftJsonInputFormatter](https://github.com/dotnet/aspnetcore/blob/b44e9c6a24528c5ebec95da60295b4b74f83f8ec/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs#L144)  for any request that needs to be deserialized and includes a JSON object larger than 32kb.

We ended up going through the effort to switch to the new System.Text.Json serializer, but would be a good thing to either document this issue, or to add a configurable value for when to use files for caching (both on FileBufferingReadStream  and on NewtonsoftJsonInputFormatter, as they both have duplicated settings for this).

### To Reproduce

It should be possible to reproduce this issue with a simple MVC setup:

``` csharp
// On Startup.ConfigureServices:
services.AddMvc().AddNewtonsoftJson();
```

``` csharp
// Any controller
public class MyController : Controller
{
    public class Data
    {
         public string Value { get; set; }
    }

    [HttpPost]
    public IActionResult ProblematicEndpoint(Data data)
    {
        return Ok();
    }
}
```

And do a load-test on the ProblematicEndpoint passing a large JSON object as body
``` json
{ "Value" : "... string longer than 32kb ... " }
```

### Further technical details
- ASP.NET Core version 3.0 / 3.1

**Comment by pranavkm** [comment]
@Tratcher - MVC sets the buffer limits to 30k the same as the defaults that `EnableRewind` does:

* https://github.com/dotnet/aspnetcore/blob/4ef204e13b88c0734e0e94a1cc4c0ef05f40849e/src/Http/Http/src/Internal/BufferingHelper.cs#L12
* https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs#L25

Once the buffering switches to disk, you're effectively trading blocking reads over the network with blocking reads over file I/O. Do we need a different strategy here? 
/cc @davidfowl

**Comment by Tratcher** [comment]
We assumed the file io wouldn't block long enough to cause an issue. We'll have to repro this and investigate.

Is the drive mechanical or SSD?

Are there many such concurrent uploads?

**Comment by theolivenbaum** [comment]
This was happening on a large server setup, something like 64 cores, 128GB RAM, NVME SSD.
Haven't measured concurrent executions of the endpoint (as it does more pure async work with the data after that), but this endpoint was being called ~500/s at peek, something that I was surprised would cause issues.
Environment is a RHEL6 instance, with our system running from within a Docker container - but not sure if this is relevant as the sync access is in any case problematic.

**Comment by Tratcher** [comment]
Can you share the callstack for the blocked threads in the starvation scenario?

**Comment by theolivenbaum** [comment]
@Tratcher unfortunately not - tried capturing from under the container it but for some reason the dotnet trace tool would not capture anything for the release build.

**Comment by Tratcher** [comment]
Can you get the stacks by taking a dump of the process?

**Comment by theolivenbaum** [comment]
Closing in favor of [this issue ](https://github.com/dotnet/runtime/issues/32016), as the problem started happening again after the change to System.Text.Json

**Comment by Tratcher** [comment]
Reopening since we still need to debug the buffering scenario.

**Comment by Tratcher** [comment]
Ah, nevermind, I read more of the linked issue.
