### ISSUE TITLE
Allow using custom IServiceProvider in blazor 3.2

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/aspnetcore#18814]
### Is your feature request related to a problem? Please describe.
Before blazor 3.2, I was able to use 3rd party dependency injection libraries such as Autofac.Extensions.DependencyInjection, but now it's not possible.

### Describe the solution you'd like
Ability to use 3rd party implementations in our blazor apps.

### Additional context
N/A

**Comment by javiercn** [comment]
@ysmoradi thanks for contacting us.

We are aware of this and will be looking at it in the future.

**Comment by mkArtakMSFT** [comment]
@rynowak assigning this to you for this milestone per offline conversation.

**Comment by rynowak** [comment]
Design work in progress at #18907 if anyone wants to give feedback.
