### ISSUE TITLE
Blazor default project runs, But errors in .razor files in IDE  VSCode on Linux

### ISSUE THREAD

**Issue by poco1980** [dotnet/aspnetcore#18812]
This is in reference to the listed issue but its on Linux in VSCode.  I have all the mono installed on my Linux Box.  

Edit: Linking original issue #17725

**Comment by javiercn** [comment]
@poco1980 thanks for contacting us.

@NTaylorMullen @ajaybhargavb @ryanbrandenburg thoughts?

**Comment by javiercn** [comment]
@poco1980 can you provide more details on what your exact setup is?

Are you using server-side Blazor or Blazor webassembly? What version  of VS Code and Omnisharp are you using?

**Comment by poco1980** [comment]
Trying to do Server Side
code -v
1.41.1
26076a4de974ead31f97692a0d32f90d735645c0
x64

 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App

**Comment by pranavkm** [comment]
@ajaybhargavb could you follow up on this?

**Comment by ajaybhargavb** [comment]
> How do I find my omnisharp version

It is the version of the vscode C# extension.

**Comment by ajaybhargavb** [comment]
@poco1980, alternatively you can also "Report a Razor issue"command and it'll automatically capture all the version information we need. 
![image](https://user-images.githubusercontent.com/1579269/74187998-7bddcb00-4c02-11ea-9a0f-036e64d6a4a2.png)
