### ISSUE TITLE
Add a setting in ASP.NET Core KeyVault integration package to set or not the precedence over application configuration

### ISSUE THREAD

**Issue by TechWatching** [dotnet/aspnetcore#18822]
### Is your feature request related to a problem? Please describe.
I am trying to use Microsoft.AspNetCore.AzureKeyVault.HostingStartup but I want the app configuration to take precedence over the configuration provided by azure keyvault which is not possible right now. 
The use cas could be the following : I want debug in local my application using secrets from the key vault except from one secret which should corresponds to the connection string of my local database instead of the connection string of an Azure SQL Database (specified in my keyvault). Even if I set my local connection string in secrets.json, it will not be used as the configuration from keyvault will be the last added in the configuration provider.

### Describe the solution you'd like
A solution could be to add a setting (like `ASPNETCORE_HOSTINGSTARTUP__KEYVAULT__CONFIGURATIONPRECEDENCE` that determines whether configuration from keyvault should take precedence or not. According the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-3.1#configuration-provided-by-the-hosting-startup) the implementation should not be really complicated.
I also thought about stop using ASP.NET Core Key Vault integration package and directly add the key vault using  the `ConfigureAppConfiguration` method and then after the `AddUserSecrets`. But that means configuration from secrets.json will be registered twice if I use the CreateDefaultBuilder method (I don't know if it's the problem) and it's too bad not to be able to use HostingStartup concept.

**Comment by Tratcher** [comment]
It looks like we deleted that package? The last release was 2.0.4. I'd have to track down why, but that would preclude adding features.

You can also call AddAzureKeyVault directly in Program.cs and control the ordering yourself.

**Comment by TechWatching** [comment]
I don't think the package was deleted, it has just not been upgraded yet. There is another [issue](https://github.com/dotnet/aspnetcore/issues/14657) about that.
Yes it's what I meant when I said that I could "add the key vault using `ConfigureAppConfiguration`" but if the HostingStartup KeyVault package is planned to be upgraded soon, I think it could be a godd time to add the possibility to control the ordering.

**Comment by amcasey** [comment]
That package does appear to be [deprecated](https://www.nuget.org/packages/Microsoft.AspNetCore.AzureKeyVault.HostingStartup/).  It looks like there's a [new way](https://learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-8.0) to accomplish this.

Cleaning this up for bookkeeping purposes.  Please file a new issue if you're still having trouble with the new API.
