### ISSUE TITLE
How do you increase the startup time on IIS

### ISSUE THREAD

**Issue by DRAirey1** [dotnet/aspnetcore#18824]
Not really a bug, unless this feature just doesn't exist.
I have a .net core web service hosted on Kestrel.  It takes a long time, especially on slower machines, to load up all the data into memory (huge, AI network).  It can't be avoided and is already part of an async method.  When I start it on a machine with many (>16) cpus, it starts fine (in less than two minutes).  When I start it on slower machines (< 16), it takes 5 to 10 minutes and I get a message:

`HTTP Error 500.37 - ANCM Failed to Start Within Startup Time Limit
Common solutions to this issue:
ANCM failed to start after 120000 milliseconds
`

How do I increase this timeout?  Alternatively, how do I instruct the web service not to timeout when starting up?

**Comment by Tratcher** [comment]
That's an error from Asp.Net Core Module. You can change the startupTimeLimit in the web.config:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1
