### ISSUE TITLE
Object Reference in RegistryPolicyResolver

### ISSUE THREAD

**Issue by adamdriscoll** [dotnet/aspnetcore#18828]
Hello,

Sorry to reopen this issue: https://github.com/dotnet/aspnetcore/issues/17888

The problem is that I am experiencing this it's not clear to me how to resolve it. It only seems to happen on Azure DevOps CI builds. After reading up on how the Data Protection keys are stored, it looks like the user doesn't have a profile so it attempts to use the registry to store the keys and then fails to read the registry since `Registry.LocalMachine` returns null.

It sounds like @Tratcher mentioned that it was a dependency issue that was resolved. Can you please let me know which version that was committed to? 

Is there any way config around this? I've attempted to remove the `IRegistryPolicyResolver` service registration but then I run into other issues down the line.

**Comment by Tratcher** [comment]
The application was referencing the wrong version of the Registry package. The app updated its dependency to resolve the issue. There were no changes in AspNetCore.

What is your apps target framework? Please share your dependency list with versions.

**Comment by adamdriscoll** [comment]
Hey @Tratcher,

Thanks for getting back to me. Are you referring to the Microsoft.Win32.Registry package? I updated to the latest version of that in an attempt to fix this. 

Here's the branch I'm messing with: https://github.com/ironmansoftware/universal-dashboard/blob/netstandard/src/UniversalDashboard/UniversalDashboard.csproj

UD is a bit weird because it loads everything into PowerShell. This can cause weird assembly binding issues that might not be reflected in a proper .NET app. 

Also, unfortunately, UD is behind on the ASP.NET Core version because it needs to support Windows PowerShell (and thus .NET Framework). 

So if the real issue here is that I need to upgrade to a newer version of ASP.NET Core or something, I'll just look for a workaround to get us by while we still support WinPS.

**Comment by Tratcher** [comment]
@ericstj can you help out with this? This is similar to our mail thread from Jan 9-10th.

**Comment by ericstj** [comment]
> UD is a bit weird because it loads everything into PowerShell. This can cause weird assembly binding issues that might not be reflected in a proper .NET app.

Can you get powershell to honor a deps file?  This issue appears when the non-windows specific version of Microsoft.Win32.Registry is loaded.  EG: `lib\netstandard2.0\Microsoft.Win32.Registry.dll` is loaded rather than `runtimes\win\lib\netstandard2.0\Microsoft.Win32.Registry.dll`.  The deps file is what tells .NETCore which dlls to use on which runtimes.  Alternatively you could publish for a specific runtime to avoid this.

Another thing I noticed in the linked project is that you're building for `netstandard2.0` and trying to run that.  `netstandard` is not a runnable framework, it's an API surface.  Some packages may provide legitimate `netstandard2.0` based implementations, but others may just expose references and need framework-specific dlls to be used by targeting and publishing the application for a specific framework.

**Comment by adamdriscoll** [comment]
Thanks for the feedback. PS won't honor a deps file as it's currently implemented. I realize now that the reason this works in PS7 and not WinPS is that PS7 is a .NET Core app and likely loading the correct Registry package on Windows already. 

It's possible to build a runtime specific implementation of this but unfortunately, the PS package tooling would require that I ship every possible runtime with the module. The tooling only installs the whole package rather than intelligently installing the specific binaries required for the specific runtime so it ends up being a huge download for the end-user. 

I think they'll fix that eventually but it's an issue that I have now. 

I realize that .NET Standard is an API surface but targeting .NET Standard enables me to work across runtimes but as you can imagine, it's a constant challenge to ship .NET Standard modules that work in every environment. Since PowerShell ends up being the dictator of the runtime, I'm often at the mercy of the assemblies that are already loaded into the process space. 

Historically, I've shipped a .NET Standard version of UD that works on PS6\7 (.NET Core) and another version built against .NET Framework 4.7.2 for WinPS in a single module and loaded the correct module at runtime. 

I was just trying to eliminate the framework one. I'll try to specifically load the Registry DLLs when running in .NET Framework and see how that goes. In the end, it may just be that I continue to build for both runtimes. 

Thanks again for the time and for pointing me in the right direction.
