### ISSUE TITLE
[DataType(DataType.Password)]   - Only in Visual Studio 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18829]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/745796/datatypedatatypepassword-only-in-visual-studio-201.html)._

---
Hi,
I have added [DataType(DataType.Password)]   in model class file.

Issue - Not showing password value as password field in Edit.cshtml and Details.cshtml  as below,
(Only in Visual Studio 2019, in VS2017 working good)

-- Model class
 [DataType(DataType.Password)]       
        public string UserPassword { get; set; }

-- Edit.cshtml 
 <div class="form-group">
            @Html.LabelFor(model => model. UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model. UserPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model. UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

--Details.cshtml
 <dt>
            @Html.DisplayNameFor(model => model. UserPassword)
        </dt>

<dd>
            @Html.DisplayFor(model => model. UserPassword)
        </dd>

---
#### Visual Studio Feedback System on 9/24/2019, 11:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/25/2019, 00:25 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Ranam on 10/11/2019, 07:20 AM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/7/siteadmin.html">Visual Studio Feedback System</a> - Any Update for this?</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
