### ISSUE TITLE
Q: BlazorComponent IEnumeration data binding example

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#18826]
### Is your feature request related to a problem? Please describe.
I'm looking to create a set of custom blazor components that have a hierarchy and interate over collections with in a model; is it possible to pass an instance of the current item (of the interation) to the child component? if so how would you acheive this and/or is this shown in an example somewhere? 

### Describe the solution you'd like
sample code showing how to pass data to child components from with in the parent BuildRenderTree method
 
### Additional context
similar to a tree control where a tree component can have nodes (a collection of node) which may also have a collection of node items.

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use Blazor. We recommend posting your questions to StackOverflow using the asp.net-core-blazor tag to reach a wider audience.
