### ISSUE TITLE
WebApi.Hal - .net core 3.1 project

### ISSUE THREAD

**Issue by gulzarahamed** [dotnet/aspnetcore#18823]
I have created new .net core 3.1 web api project, and just include webapi.hal package reference, and when run the project the line app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
caught erros as given below:- 

"Unable to load one or more of the requested types.
Could not load type 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'."

my .csproj:-

`<Project Sdk="Microsoft.NET.Sdk.Web">
PropertyGroup>
<TargetFramework>netcoreapp3.1</TargetFramework>
</PropertyGroup>
<ItemGroup>
 <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.1" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.1" />
<PackageReference Include="WebApi.Hal" Version="3.1.0" />    
  </ItemGroup>
</Project>`

my Configure method in startup.cs:
`      public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }`

though i have created issue #18479 earlier, which was referred to https://github.com/JakeGinnivan/WebApi.Hal/issues/155.
I have just want to know what is the forward path of this issue?

**Comment by javiercn** [comment]
@gulzarahamed thanks for contacting us.

I'm not sure the library you are mentioning is supports ASP.NET Core. It is up to third-party library authors to make their libraries support asp.net core.

**Comment by gulzarahamed** [comment]
we have resolved by moved the startup.cs class from hosting project. 
Program.cs in hosting project

Hosting project references:-
`<PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="3.1.1" />`

My addtional project conatin startup.cs:-
`
 <PackageReference Include="WebApi.Hal" Version="3.0.0" />
 <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.1" />
`

**Program.cs from startup project:-** 

`using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using TestLibrary;

namespace MyRestApi1
{
    public class Program
    {
        public IConfiguration HostConfiguration { get; set; }
        private IWebHost _webApp;

        public static void Main(string[] args)
        {
            Program prg = new Program();
            prg.Start();
        }

        public void Start()
        {
            try
            {
                _webApp = CreateWebHostBuilder(new string[] { })
                   .UseUrls("http://localhost:8089")
                   .SuppressStatusMessages(true)
                   .Build();

                _webApp.Run();
                Console.WriteLine("Service hosted in 5001...");
                _webApp.Run();
            }
            catch (Exception ex)
            {
                if (Environment.UserInteractive)
                {
                    Console.ReadKey();
                }
            }
        }

        public IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            HostConfiguration = new ConfigurationBuilder()
                .SetBasePath(GetContentRoot())
                .AddCommandLine(args)
                .AddEnvironmentVariables(prefix: "ASPNETCORE_")
                .Build();

            return new WebHostBuilder()
                .UseContentRoot(GetContentRoot())
                .UseConfiguration(HostConfiguration)
                .CaptureStartupErrors(true)
                .UseKestrel()
                .UseStartup<Startup>();
        }

        private string GetContentRoot()
        {
            var pathToContentRoot = AppContext.BaseDirectory;
            return pathToContentRoot;
        }

    }
}`

**Startup.cs moved to seperate project:-**

`using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using Microsoft.AspNetCore.Hosting.Server.Features;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;

namespace TestLibrary
{
    public class Startup
    {
        private object _hostUrl;

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddNewtonsoftJson();
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll",
                    builder =>
                    {
                        builder
                        .AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader();
                    });
            });
            services
                .AddMvcCore(options =>
                {
                    options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));

                })
                .AddAuthorization()
                .AddNewtonsoftJson()
                .AddFormatterMappings();


            services.AddHttpContextAccessor();

            services.AddAuthorization(options =>
            {
            });

            services.AddLogging(builder =>
            {
                builder.AddFilter("Microsoft", LogLevel.Warning);
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime applicationLifetime)
        {
            _hostUrl = app.ServerFeatures.Get<IServerAddressesFeature>()?.Addresses.First();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
            }

            applicationLifetime.ApplicationStarted.Register(OnStarted);
            app.UseCors("AllowAll");
            app.UseRouting();
            app.UseAuthentication();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

        }

        private void OnStarted()
        {
            Console.WriteLine("Server is listening to : " + _hostUrl + "api");
        }

    }
}
`
