### ISSUE TITLE
Minor: AzureADB2C SignedOut.cshtml add 'id' tags

### ISSUE THREAD

**Issue by pjevans** [dotnet/aspnetcore#18825]
### Is your feature request related to a problem? Please describe.
I'm trying to add 'id' tags onto the SignedOut.cshtml view to allow ease of styling on the front end.  Very very minor update.

### Describe the solution you'd like
Want to add "AzureADB2CSignoutTitle" and "AzureADB2CSignoutText" to the h2 and p tags in this file.

### Additional context
Very minor update, already completed doing PR.

**Comment by javiercn** [comment]
@pjevans thanks for contacting us.

I think that will be fine if @blowdart is ok with it. Feel free to send us a PR and we'll evaluate the changes.

**Comment by pjevans** [comment]
Sounds good.  Thanks for the response.  I got the branch created locally but got a 403 error trying to push it up.  If you got a quick suggestion, I'm all ears.. if not, no worries I'll get it figured out.

Have a great day --PJ

**Comment by javiercn** [comment]
@pjevans You need to create your own fork of the repo and then push your local branch to your fork. Then you can go into this repo and start a pull request from the branch in your fork to the branch in this repo.

**Comment by pjevans** [comment]
That's the part I was missing.  Thank you.  New around here, hope to keep learning.  Thank you very much.

**Comment by blowdart** [comment]
Fine by me :)

**Comment by peterblazejewicz** [comment]
@pjevans can you close this now when merged? Thx!

**Comment by pjevans** [comment]
You got it... Thank you, sorry for the wait.
