### ISSUE TITLE
Injection with @ref in Blazor generated code

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#18833]
Lets' say we have a component with `@ref` attribute `<MyComponent @ref="myVariable" />`
This is what Blazor would generate.

```csharp
__builder.OpenElement(0, "MyComponent");
__builder.AddElementReferenceCapture(1, (__value) => 
    {
        myVariable = __value;
    });
__builder.CloseElement();
```

Now the `@ref` value could be anything and it would be replaced in the generated code. For example I can (ab)use this to add reference to components inside a loop.

```
@for (int i = 0; i < 10; i++)
{
    <MyComponent @ref="components.Add((MyComponent)__value);//" />
}
@code
{
    List<MyComponent> components = new List<MyComponent>();
}
```
And this is the generated code.
```csharp
for (int i = 0; i < 10; i++)
{
    __builder.AddMarkupContent(0, "\t");
    __builder.OpenComponent<AfterBlazorServerSide.Pages.MyComponent>(1);
    __builder.AddComponentReferenceCapture(2, (__value) => 
    {
        components.Add((MyComponent)__value);// = (AfterBlazorServerSide.Pages.MyComponent)__value;
    });
__builder.CloseComponent();
```

I just wanted to point out that this exists! This could either be as design, a bug or a feature!

**Comment by javiercn** [comment]
@Kahbazi thanks for contacting us.

We are not sure of the point you are trying to make here. Blazor transpiles to c# and the result of that is expected.

We're not sure what you are trying to accomplish here, but you should avoid leveraging how the compiler generates code as that might be subject to change in future versions.

**Comment by pranavkm** [comment]
This sounds like something we could enforce as part of the parser. Let's triage this.

**Comment by mkArtakMSFT** [comment]
Closing per @javiercn 's response.

**Comment by Kahbazi** [comment]
@mkArtakMSFT I'm totally ok with closing this but don't you want to triage this as @pranavkm said.

**Comment by mkArtakMSFT** [comment]
> 
> 
> @mkArtakMSFT I'm totally ok with closing this but don't you want to triage this as @pranavkm said.

We've discussed this offline and found no good way of doing it.
