### ISSUE TITLE
ProjectCompilationFeatureDetector shouldn't expect VisualStudioWorkspace on a Mac

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/aspnetcore#18835]
VSMac has a MEF error due to VS Workspace missing:

```
MEF composition error: Microsoft.AspNetCore.Analyzers.FeatureDetection.ProjectCompilationFeatureDetector.ctor(workspace): expected exactly 1 export matching constraints:
    Contract name: Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace
    TypeIdentityName: Microsoft.VisualStudio.LanguageServices.VisualStudioWorkspace
```

https://github.com/dotnet/aspnetcore/blob/801578fe19eb3f831075cb7db0b1522e60c61db1/src/Analyzers/shared/FeatureDetection/ProjectCompilationFeatureDetector.cs#L31

@rynowak I think a simple `AllowDefault` on the import should fix this. This code runs on Mac now!

**Comment by mkArtakMSFT** [comment]
Thanks @KirillOsenkov.
Can you please elaborate on the impact of this issue?

**Comment by KirillOsenkov** [comment]
@mrward Matt reported it so I don't know if it's critical or VSMac can start with the issue. It certainly doesn't look critical.

I don't know what your release schedule is but would probably nice to get it into 16.6 (I think?)

**Comment by mrward** [comment]
It is not critical since VS Mac can still start. Was reporting various MEF composition errors since there were a set of new ones introduced in VS Mac 8.5. /cc @rodrmoya

**Comment by rynowak** [comment]
@mkArtakMSFT - taking this. 

How has this code made its way into VS for mac? We don't actually ship this, we just maintain it for WTE. So it sounds like they shipped it in VS for mac. I'm happy to fix this, or at least silence the error, but it sounds like ideally it would work in VS for mac as well.

@abpiskunov

**Comment by abpiskunov** [comment]
We are not using this code in WebTools anymore. We have our own generic feature detection logic which includes similar check and much more stuff. @KirillOsenkov how this code is still running on mac, thought we removed package reference and code using it?

**Comment by KirillOsenkov** [comment]
We've inserted the version from rel/16.5, this code must be in that branch?? ¯\_(ツ)_/¯

**Comment by rynowak** [comment]
@abpiskunov - should I delete this then? We made it for you :heart:

**Comment by abpiskunov** [comment]
Yeah, we changed the way we detect things now, we can detect any kind of things in the project not just code, however to generalize it we switched to declarative models that come form configs. We mimic same logic that you have, but do it declarative now. I guess you don't have to keep it anymore, just keep old packages since old code might need it if we ever build it.

**Comment by rynowak** [comment]
Cool, glad to hear that you're advancing the state of the art. This will still be present in our 3.1 servicing builds, so it should be safe to delete from master.

**Comment by rynowak** [comment]
@KirillOsenkov - it sounds like you don't need anything from us and this will just be taken care up when you update WTE? Clap back if you need something from me.
