### ISSUE TITLE
Microsoft.AspNetCore.Builder namespace / ResponseCachingExtensions class / UseResponseCaching method missing XML Documentation Comments

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18831]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/734313/microsoftaspnetcorebuilder-namespace-responsecachi.html)._

---
The **UseResponseCaching** method in the **ResponseCachingExtensions** class in the **Microsoft.AspNetCore.Builder** namespace is missing XML Documentation Comments.

(As a quick aside, the "Summary" section of this "Report a Problem" wizard should allow us to preview any screenshots we had attached in the "Attachments" step [and, as part of that, we should be able to enlarge the preview].)

---
#### Visual Studio Feedback System on 9/16/2019, 04:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/24/2019, 02:14 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Art Bergquist on 9/26/2019, 03:23 PM: 

It apperas you're also missing a description at https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.responsecachingextensions.useresponsecaching?view=aspnetcore-2.2.

---
### Original Solutions
(no solutions)

**Comment by NRKirby** [comment]
I think this can be closed as it looks like it got merged [here](https://github.com/dotnet/aspnetcore/pull/18968)

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT please close

**Comment by JunTaoLuo** [comment]
All of response caching APIs have been documented after https://github.com/dotnet/aspnetcore/pull/18968 and https://github.com/dotnet/aspnetcore/pull/26531 are merged.
