### ISSUE TITLE
Blazor redirect to cshtml not work with renderMode = Server

### ISSUE THREAD

**Issue by troepolik** [dotnet/aspnetcore#18849]
In my blazor app when I try to redirect to cshtml page with render mode = Server , I got 
"Sorry, there's nothing at this address."
So I got not found routing.
If I switch render mode to ServerPrerendered , It's work fine.
Or If I redirect to .razor page It's work fine

In _Host.cshtml I have 
``` C#
<component type="typeof(App)" render-mode="Server" />
```

And for example In MainLayout.razor I have this
``` C#
@code
{
    // TODO : Setting as not authenticated to false for demo
    private bool IsAuthenticated = false;

    protected override void OnInitialized()
    {
        if (!IsAuthenticated)
        {
            NavigationManager.NavigateTo(@"\login");
        }
    }
}
```

**Comment by javiercn** [comment]
@troepolik thanks for contacting us.


You likely need to do `/login` instead of `\login`. NavigateTo expects a url, relative or absolute, not a path as you seem to be trying to pass.

**Comment by troepolik** [comment]
@javiercn Thanks for your notise.
But actually It's never mind, I tried 
```
NavigationManager.NavigateTo(@"/login");
```
But it's does not work too.
Also, I tried to do it by component in App.razor like this:
```
<NotAuthorized>                
                <MyComponentRedirectToLogin />
</NotAuthorized>
```
And It does not work too.

**Comment by javiercn** [comment]
Can you provide a minimal repro project that illustrates your issue so that we can help you?

**Comment by troepolik** [comment]
@javiercn Sure:
https://github.com/troepolik/testBlazorServerRender

**Comment by javiercn** [comment]
@troepolik [this](https://github.com/troepolik/testBlazorServerRender/blob/master/BlazorApp1/Pages/test.cshtml#L1) needs to be `@page /test`

**Comment by troepolik** [comment]
@javiercn No, It does not work.

**Comment by javiercn** [comment]
@troepolik I've reopened the issue.
