### ISSUE TITLE
Asp.net core 3.1 application with f5 load balancer as reverse proxy server

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#18848]
Can we configure kesterl with f5 load balancer?
https://www.f5.com/services/resources/glossary/load-balancer
I am currently using kesterl behind nginix via help of following article 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1
and it is working fine.
Now some client have f5 load balancer. Please let me know that can i configure kesterl behind F5 load balancer or not?
if yes is there any custom setting needed to be done like we have to do in nginix config

**Comment by Tratcher** [comment]
Have you tried it yet? Conceptually it should be the same and you'd do the same configuration in the .NET app. For the F5 config you'll need to consult their own docs.

**Comment by KamranShahid** [comment]
In my current app i did no custom configuration.
On nginix side i have done cofniguration like

```
server {
    listen        80;
    server_name   example.com *.example.com;
    location / {
        proxy_pass         http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
```
as mentioned in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1

**Comment by amansulaiman** [comment]
@KamranShahid I think you can maintain the same Nginx as an internal reverse proxy for Kestral while f5load balancer as an external load balancing for your network. 
Or you can configure Kestral to accept traffic on port 80 and expose it to f5 node.

**Comment by KamranShahid** [comment]
> @KamranShahid I think you can maintain the same Nginx as an internal reverse proxy for Kestral while f5load balancer as an external load balancing for your network.
> Or you can configure Kestral to accept traffic on port 80 and expose it to f5 node.

Thanks Abdul Rahman
What's the issue if i start Kestral on any other port then 80?

**Comment by amansulaiman** [comment]
@KamranShahid No any issue. But, changing port other than the default 80 requires you to do additional configuration on your f5 node. Because default HTTP traffic is port 80.

**Comment by KamranShahid** [comment]
> @KamranShahid No any issue. But, changing port other than the default 80 requires you to do additional configuration on your f5 node. Because default HTTP traffic is port 80.

Thanks for this valuable information Abdul Rahman
