### ISSUE TITLE
XmlSerializerInputFormatter - More detailed deserializing error message

### ISSUE THREAD

**Issue by Karql** [dotnet/aspnetcore#18847]
Hi,

This issue is continuation to https://github.com/dotnet/aspnetcore/issues/4917

When posted xml contains errors the returned message is: "An error occurred while deserializing input data." It is hard to find where the error is - esspecialy for large xml.

@dougbu you have chagned this a bit in:
https://github.com/dotnet/aspnetcore/pull/6316/files

```c#
...
            catch (InvalidOperationException exception) when (exception.InnerException is FormatException ||
                exception.InnerException is XmlException)
            {
                throw new InputFormatterException(Resources.ErrorDeserializingInputData, exception.InnerException);
            }
...
```
Maybe it is good idea. Insetad of returning `Resources.ErrorDeserializingInputData` return something like: `$"{exception.Message} - {exception.InnerException.Message}"`.
With this change I get messege like: "There is an error in XML document (7, 17). - Input string was not in a correct format."

I also have changed `CreateXmlReader` to use `XmlReader.Create(readStream)` - `XmlDictionaryReader` does not implement `IXmlLineInfo` and returns wrong error position (https://stackoverflow.com/questions/621059/current-line-number-from-a-system-xml-xmlreader-c-net)

Best regards,
Mateusz

**Comment by rynowak** [comment]
For security and safety reasons we generally do not return .NET exception messages to clients unless we really know they are designed to be safe. These messages could contain information about your data structures or other sensitive details about your app's configuration. It seems reasonable to that we could return line info when we have it.

**Comment by Karql** [comment]
@rynowak thank you for the replay.

> For security and safety reasons we generally do not return .NET exception messages to clients unless we really know they are designed to be safe.

That is obvious, but in this catch there is checking what kind of exception it is. 
For xml I would like to get similar message as for json.

**Comment by dougbu** [comment]
The XML formatters throw `FormatException` and / or `XmlException` in numerous places, with numerous messages. Their messages aren't universally designed to hide sensitive information.
