### ISSUE TITLE
Error after upgrade to WebAssembly Preview 3.2.0 - Cannot find WebAssembly.Runtime.CreateUri

### ISSUE THREAD

**Issue by derekcripps** [dotnet/aspnetcore#18854]
I upgraded to 3.2.0, and made the updates as per the upgrade instructions.  The application runs fine inside the Visual Studio debugger environment, but I receive this error after publishing it to an IIS server.

Uncaught (in promise) Can't find method WebAssembly.Runtime:CreateUri

It looks like the Index page has loaded, but only displays the "loading..." message in the browser window.

Please advise...  Thank you, Derek

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by derekcripps** [comment]
[Fuji_Main After Upgrade (2).zip](https://github.com/dotnet/aspnetcore/files/4166824/Fuji_Main.After.Upgrade.2.zip)

Please see attached, and let me know if you need anything else.  Thanks again

**Comment by derekcripps** [comment]
Not sure if this is related or not, but I am also receiving this error regarding DevTools and Chrome:
![image](https://user-images.githubusercontent.com/17464411/73967308-a4558480-48e5-11ea-8748-f3c6e9353f21.png)

I receive this error when running a new, sample Blazor app based on the latest release as well.

**Comment by Discovery-support** [comment]
I also had this exact issue when upgrading to 3.2.0.  Publishing does not seem to create a _framework/blazor.boot.json file (one of many that are missing in the dist\framework).  Is there a workaround to force the generation of these files?  (I have tried Cleaning and Rebuilding.)

**Comment by SteveSandersonMS** [comment]
@derekcripps I'm afraid I'm unable to use your repro project, because it relies on references to NuGet packages that aren't available on public feeds (e.g., `DevExpress.Blazor`). If you're able to update your repro project so that it only uses public packages, I'm happy to take a look.

@Discovery-support To really reset things, be sure you deleted the `bin` and `obj` folders from all your projects. If you still have trouble, please file a separate issue with your own repro steps, since it may be a different underlying cause than was originally reported in this issue.

**Comment by Discovery-support** [comment]
Thanks, but folder deletion didn't resolve it. I have raised a new issue as requested. **https://github.com/dotnet/aspnetcore/issues/19097**

**Comment by derekcripps** [comment]
[Fuji_NoDevExpress-master.zip](https://github.com/dotnet/aspnetcore/files/4215207/Fuji_NoDevExpress-master.zip)
Please see updated project, with DevExpress.Blazor removed.  Thank you

**Comment by SteveSandersonMS** [comment]
@derekcripps Unfortunately you removed more than just DevExpress. There's nothing in that zip file except for `.gitignore` and `.gitattributes` 😄

**Comment by derekcripps** [comment]
Apologies, tried to make a new repo with the changes, but I've done something wrong.  I've zipped the solution, without the obj and bin folders.  Please let me know if this is better.  Thank you
[Fuji_Main.After.Upgrade_NoDevExpress.zip](https://github.com/dotnet/aspnetcore/files/4215360/Fuji_Main.After.Upgrade_NoDevExpress.zip)

**Comment by javiercn** [comment]
We don't think there's any real issue here. If this reproes with a clean project or in 5.0 let us know.
