### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.1.0

### ISSUE THREAD

**Issue by andresabglb** [dotnet/aspnetcore#18857]
I am migrating some APIs from .NET Core 2.2 to .NET Core 3.1 and there is a middleware which catch exceptions and returns an HTTP Code. This is the Invoke method:

```
public async Task Invoke(HttpContext context){
try
{
// some stuff
}
catch (NotFoundException notFound)
{
    _logger.LogDebug(notFound, "Invoke - NotFoundException.");
    await context.Response.WriteAsync(ChangeResponseMiddleware(context, notFound, HttpStatusCode.NotFound));
}
... // Another catches
catch (AmbiguousActionException aaex)
{
    _logger.LogDebug(aaex, "Invoke - AmbiguousActionException.");
    await context.Response.WriteAsync(ChangeResponseMiddleware(context, aaex, HttpStatusCode.NotFound));
}
catch (Exception ex)
{
    _logger.LogCritical(ex, "Invoke - Exception: " + ex.Message);
    await context.Response.WriteAsync(ChangeResponseMiddleware(context, ex, HttpStatusCode.InternalServerError));
}
}
```

As you can see, we have a reference to AmbiguousActionException. This code is throwing the following exception in runtime

`System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.`

And the project file has a reference to Microsoft.AspNetCore.Mvc.Core 2.2.5

```
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Version>2.0.0.0-beta</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.1" />
  </ItemGroup>
</Project>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We suggest following our [migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio).
Also it seems you're mixing both .NET Core and .NET Framework assemblies in your references which won't work.

**Comment by raspyweather** [comment]
hey @andreasbotsikas,
would be cool if you could post your solution. As you're not alone with this issue.
