### ISSUE TITLE
AzureADB2C.UI doesn't allow customizing post-logout redirect URI

### ISSUE THREAD

**Issue by mjrousos** [dotnet/aspnetcore#18865]
I'm using Microsoft.AspNetCore.Authentication.AzureADB2C.UI to provide B2C login in a (server-side) Blazor app. The problem is that after the user logs out (by navigating to `AzureADB2C/Account/SignOut`), they are logged out and [redirected back to a generic 'signed out' page at /AzureADB2C/Account/SignedOut](https://github.com/dotnet/aspnetcore/blob/master/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/Areas/AzureADB2C/Controllers/AccountController.cs#L77).

I would like to be able to customize where the user is redirected back to after logout, but my app is just a simple SPA and I'd rather not add controllers or extra pages just for that functionality. If it were possible to configure the callback URL used by the AzureADB2C.UI library, that would solve the issue.

I've worked around the issue by re-writing calls to /AzureADB2C/Account/SignedOut using `app.UseRewriter` as suggested [on StackOverflow](https://stackoverflow.com/questions/56927081/change-azure-ad-b2c-signout-url-change-azureadb2c-account-signedout-to-custom-u). It seems like making AzureADB2C.UI's callback URL configurable would be an even cleaner solution, though.

**Comment by sven5** [comment]
The only possible workaround currently is to rewrite the URL:
```
var rewrite = new RewriteOptions().AddRedirect("AzureADB2C/Account/SignedOut", "signedOut");
            app.UseRewriter(rewrite);
```

[Found here](https://stackoverflow.com/questions/56927081/change-azure-ad-b2c-signout-url-change-azureadb2c-account-signedout-to-custom-u)

**Comment by lbelloq** [comment]
How did you workaround the issue? I'm using Microsoft.AspNetCore.Authentication.AzureAD.UI in ASP.NET Core MVC 3.0 and have the same problem.

**Comment by mjrousos** [comment]
You can use `IApplicationBuilder.UseRewriter` to redirect requests to `/AzureADB2C/Account/SignedOut` to a different URL. Here's the code I added towards the beginning of my `Startup.Configure` method to use the rewriter:

```CSharp
app.UseRewriter(new RewriteOptions().AddRedirect("AzureADB2C/Account/SignedOut", "/"));
```

**Comment by lbelloq** [comment]
Didn't work in my case, dunno why. I worked around the issue with an extra controller (ugly, but at least I don't have errors in my signout flow anymore). Code in case anyone needs it:

```
[AllowAnonymous]
public class AccountController : Controller
{
    [HttpGet]
    public IActionResult SignOut(string page)
    {
        return RedirectToAction("Index", "Home");
    }
}
```

Just add it as a regular controller to your app and it will work.

**Comment by lbelloq** [comment]
Also, OpenID provides a `post_logout_callback_uri` parameter; I think ASP.NET Core should provide a way to set it to replace the `/Account/SignOut?page=/Account/SignedOut` hardcoded path.

**Comment by anurse** [comment]
In 5.0 we're moving to code built by the MSAL team so this won't really apply.

**Comment by Tratcher** [comment]
Closing since AzureADB2C.UI is now obsolete. Please try the new Microsoft.Identity.Web packages: https://github.com/AzureAD/microsoft-identity-web/

**Comment by jH-** [comment]
@MauriRojas Made some changes to this, seems to work:
```
options.Events.OnSignedOutCallbackRedirect = async context =>
{
    context.HttpContext.Response.Redirect(context.Options.SignedOutRedirectUri);
    context.HandleResponse();
};
```
Redirects to root by default, set SignedOutRedirectUri if you're using a custom logout component.

**Comment by MauriRojas** [comment]
@jH- Thank you! That solved my issue 😁
