### ISSUE TITLE
@functions block coloring is off

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#18864]
![image](https://user-images.githubusercontent.com/1579269/73970645-584d1480-48d2-11ea-87cc-4e7332b152af.png)

@NTaylorMullen is assume this is supposed to work?

**Comment by NTaylorMullen** [comment]
Definitely supposed to work. It works in C# files after all.

**Comment by NTaylorMullen** [comment]
This looks to be a VSCode TextMate bug. Going to push this out to preview3 once validation starts; leaving this here to remind me to file an issue in vscode-textmate. 

For instance this works in VS:

![image](https://user-images.githubusercontent.com/2008729/74305948-0d8a2d00-4d16-11ea-9725-83740b8acd20.png)

**Comment by NTaylorMullen** [comment]
Filed an issue in Microsoft/vscode-test for this: https://github.com/microsoft/vscode-textmate/issues/125

**Comment by NTaylorMullen** [comment]
Re-opening because the associated issue was marked by design. We'll need to find another way to solve this.

**Comment by ryanbrandenburg** [comment]
![image](https://user-images.githubusercontent.com/14987221/96312773-1d52c300-0fc1-11eb-9ad5-3e611c23e29b.png)
