### ISSUE TITLE
Visual Studio 2019 launchSetting.json problem with Dotnet Watch Run

### ISSUE THREAD

**Issue by xshiiiidev** [dotnet/aspnetcore#18877]
So I have this launchSetting

```
"Dotnet Watch run": {
      "commandName": "Executable",
      "executablePath": "dotnet.exe",
      "workingDirectory": "$(ProjectDir)",
      "commandLineArgs": "watch run",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

My problem is the launchBrowser even set as true is not launching the browser. It only opened the command line and not the browser.

Also I cannot put a debug point to visual studio when using this profile using (F5).

**Comment by pranavkm** [comment]
Does setting `applicationUrl` work: https://stackoverflow.com/a/52951565?

**Comment by xshiiiidev** [comment]
> 
> 
> Does setting `applicationUrl` work: https://stackoverflow.com/a/52951565?

I tried that bro before posting here, no chance at all. 

The browser is still not launching automatically.

```
"launchBrowser": true,
 "applicationUrl": "http://localhost:5000/"
```

**Comment by soeleman** [comment]
Maybe you can take a look on this issue #16703
[using shell to invoke browser](https://github.com/dotnet/aspnetcore/issues/16703#issuecomment-549073761)

**Comment by xshiiiidev** [comment]
@soeleman  I can do that but is does not fixed the problem of `"launchBrowser": true`

**Comment by soeleman** [comment]
@xshiiiidev command **Executable** does not read or ignore property **launchBrowser**. 
Since that command using ProcessStat/Shell then we must using executablePath **cmd** and pass command via **commandLineArgs**.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're going to address this as part of #23412
