### ISSUE TITLE
TraceId contains a pipe char 

### ISSUE THREAD

**Issue by juniorgasparotto** [dotnet/aspnetcore#18876]
Hello,

I am migrating to aspnetcore 3.1 and I noticed that the traceId is coming with a "|" at first, does this seem like a problem or did I miss something in the documentation? The same question applies to the name of the field, why "$." as a suffix?

1) "traceId": "|125b177f-444ca33308cefc01."
2) $.dateOfBirth"

Full response:

> {
>     "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
>     "title": "One or more validation errors occurred.",
>     "status": 400,
>     **"traceId": "|125b177f-444ca33308cefc01."**,
>     "errors": {
>         "**$.dateOfBirth**": [
>             "The JSON value could not be converted to System.Nullable`1[System.DateTime]. Path: $.dateOfBirth | LineNumber: 6 | BytePositionInLine: 22."
>         ]
>     }
> }

**Comment by davidfowl** [comment]
There was a change in .NET Core 3.0 to use the ActivityId as the trace id in the logs, it's not a mistake, the docs for the ID format are here https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#activity-id

**Comment by juniorgasparotto** [comment]
Ok, thanks... 

And the "$ .dateOfBirth", it's a New behavior, as well?

**Comment by davidfowl** [comment]
That's separate, as it looks like problem details. 
cc @pranavkm

**Comment by pranavkm** [comment]
The `$` sign is part of the JSON Path specification that System.Text.Json uses. It's meant to indicate the root of the object graph.

**Comment by juniorgasparotto** [comment]
So in these cases of invalid fields, there is no longer a guarantee of associating the JsonParse error with the model field. Despite understanding, this seems strange to me.

**Comment by pranavkm** [comment]
@juniorgasparotto, part of the reasoning was that it's less useful for a client to know how you've modeled your server if there's an issue with the JSON contents. Admittedly you still get the model state path if model validation fails. We haven't had much feedback about this. But if you feel strongly about it, feel free to file an issue for us to consider.

Additionally, these changes are a result of changing the JSON serializer MVC uses by default. We'd generally recommend using it if it works for you. However, if it's affecting your upgrade to 3.x, you could consider switching back to the Newtonsoft.Json based formatters - https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#newtonsoftjson-jsonnet-support

**Comment by juniorgasparotto** [comment]
I agree that it doesn't make sense for this to be a BUG, ​​in fact, the deserializer is doing its job. But it makes me feel disconnected from the model. But I must get used to it.

Thanks
