### ISSUE TITLE
ClientId and ClientSecret shouldn't be mandatory in OAuth

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#18874]
In this code: https://github.com/dotnet/aspnetcore/blob/75e0115de9ff4ba6ab139777099dc9d951b2a3ff/src/Security/Authentication/OAuth/src/OAuthOptions.cs#L29

Checks are made to ensure that ClientId and ClientSecret are provided when using OAuth.  The OAuth2 specification says that these are only required if a confidential client is authenticating with the auth server: https://tools.ietf.org/html/rfc6749#section-2.3

However I'm writing a public client and do not wish to use these.  The OAuth middleware shouldn't mandate them.

**Comment by jez9999** [comment]
OK, re-reading the spec, client ID *is* required as it's presented when hitting the authorization endpoint.  However, client secret should not be required.

**Comment by blowdart** [comment]
If you're writing a public client, then frankly that's not what we're aiming at. We don't use implict flow, or authorization flow by default. We're web apps, we expect to be confidential. If you want to go outside of that then you're outside the scope of what we're aiming at.

**Comment by jez9999** [comment]
I thought you used auth code flow by default.  What flow is the default?

**Comment by Tratcher** [comment]
Yes, we use the auth code flow which requires client id and secret.

**Comment by jez9999** [comment]
> 
> 
> Yes, we use the auth code flow which requires client id and secret.

No: https://tools.ietf.org/html/rfc6749#section-2.3

"If the client type is confidential, the client and authorization server establish a client authentication method suitable for the security requirements of the authorization server." (which can be a client ID and secret)

However if the client type is public, this isn't needed.

**Comment by anurse** [comment]
We currently only support confidential client flows. Can you give an example of a server scenario that uses the public client flow?

**Comment by jez9999** [comment]
Why not support native scenarios?  It could be supported pretty easily.

**Comment by anurse** [comment]
It's just not in our current plan to build and maintain. It's certainly _possible_ but public client scenarios go beyond most server applications, which is what we're set up to do and have resources to implement. It's not out of the picture, we just have to prioritize other things right now (and to be honest, likely will be prioritizing other work for a while). The ASP.NET Core Auth stack is designed for ASP.NET Core, not for native applications (though it's true some code may be equally relevant).

**Comment by jez9999** [comment]
It doesn't seem that hard to support public client scenarios, though.  You basically just don't require a client secret, or authentication to the auth server when requesting tokens.

**Comment by Tratcher** [comment]
Can you give examples of any providers that support public clients?

We added the check to require a client secret because all the providers we've worked with require it and too many people had config errors where they forgot to provide it.

**Comment by jez9999** [comment]
I was using the client to test my own auth server, which allows public clients.

**Comment by Tratcher** [comment]
Any others? Writing a personal auth server is uncommon.

**Comment by jez9999** [comment]
@Tratcher Doesn't any mobile client have to be a pubic client?  Given this, I don't understand why major providers don't support them.  How are mobile apps meant to log in securely?

**Comment by Tratcher** [comment]
That's a completely different flow. The client would use a client-side, provider specific SDK to authenticate and then do something like API / JWT auth when interacting with the server.

**Comment by jez9999** [comment]
@Tratcher Erm, our mobile app uses OAuth2 auth code flow as a public client with our OAuth2 server, so I don't see why it would need to use a provider-specific SDK if they just supported public clients.

**Comment by Tratcher** [comment]
Fair, you can use generic libraries, but the login flow is still happening on the client, not in the ASP.NET app.
