### ISSUE TITLE
[Blazor] Exception not displayed when call in JSInterop times out

### ISSUE THREAD

**Issue by RemiBou** [dotnet/aspnetcore#18875]
### Describe the bug
When a jsinterop task is cancelled because of a timeout, the current execution flow is interupted.

### To Reproduce

With the following component

```cs
@inject IJSRuntime jsRuntime;
<button id="navigator-storage-getStorageEstimate" type="button" @onclick="AskPersist">AskPersist</button>

@code {
  protected async Task AskPersist()
    {
         Console.WriteLine("1");
         var res = jsRuntime.InvokeAsync<bool>("navigator.storage.persist", TimeSpan.FromSeconds(1), null);
         Console.WriteLine("2")
    }
}
```
The console display "1" then nothing. I think the console should display "1" then the exception stacktrace. You should test it in firefox (68.4.2) as this method does not create a prompt in chrome.

But if I execute the following component

```cs
@inject IJSRuntime jsRuntime;
<button id="navigator-storage-getStorageEstimate" type="button" @onclick="AskPersist">AskPersist</button>

@code {
  protected async Task AskPersist()
    {
       Console.WriteLine("1");
       try{
                var res = jsRuntime.InvokeAsync<bool>("navigator.storage.persist", TimeSpan.FromSeconds(1), null);
       } catch(Exception e){
              Console.WriteLine("ERROR");
       }
       Console.WriteLine("2")
    }
}
```

The console displays "1", "ERROR", "2".

### Further technical details
- PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.1.0-preview4.19579.2" 
- Firefox 68.4.2

**Comment by pranavkm** [comment]
@RemiBou that looks like an unawaited task:

```
var res = jsRuntime.InvokeAsync<bool>("navigator.storage.persist", TimeSpan.FromSeconds(1), null);
```

**Comment by RemiBou** [comment]
I missed it in my code sample sorry. The await was here during my tests.

**Comment by RemiBou** [comment]
I think you can reproduce this by removing the try/catch here

https://github.com/dotnet/aspnetcore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Components/test/testassets/BasicTestApp/LongRunningInterop.razor line 41 : 

```cs
        //try
        //{
            using var cancellationTokenSource = new System.Threading.CancellationTokenSource(TimeSpan.FromSeconds(1));
            await JSRuntime.InvokeVoidAsync(
                "asyncFunctionTakesLongerThanDefaultTimeoutToResolve",
                cancellationTokenSource.Token,
                Array.Empty<object>());
        //}
        //catch (TaskCanceledException)
        //{
        //   TaskWasCancelled = true;
        //}
```

 You won't have any error on the console.

It might be due to this LoC : https://github.com/dotnet/aspnetcore/blob/c74e9efd0e6ea5b4d6737d23b92042772a50a249/src/Components/Components/src/ComponentBase.cs line 253.

```cs
                try
                {
                    await task;
                }
                catch // avoiding exception filters for AOT runtime support
                {
                    // Ignore exceptions from task cancellations.
                    // Awaiting a canceled task may produce either an OperationCanceledException (if produced as a consequence of
                    // CancellationToken.ThrowIfCancellationRequested()) or a TaskCanceledException (produced as a consequence of awaiting Task.FromCanceled).
                    // It's much easier to check the state of the Task (i.e. Task.IsCanceled) rather than catch two distinct exceptions.
                     if (!task.IsCanceled)
                     {
                        throw;
                     }
                }
```

 Maybe we should just handle the exception in a else statement line 256 ?

**Comment by javiercn** [comment]
@RemiBou is this related to webassembly?

**Comment by RemiBou** [comment]
Yes this happens in web assembly, I didn't test it in server-side blazor.

**Comment by captainsafia** [comment]
@RemiBou Thanks for taking the time to craft this detailed bug report. I was able to reproduce the issue that you mentioned on both server-side Blazor and on Blazor WebAssembly.

I'm updating the issue title to reflect the real problem (exception not thrown when JSInterop call times out).

I'll start digging into this now.

**Comment by captainsafia** [comment]
Bringing some analysis that @javiercn shared over email into GitHub as to why we handle task cancelled exceptions this way.

> In collation to the conversation we were having the other day about us "swallowing" TaskCancelledExceptions in the renderer. This issue is why https://github.com/dotnet/aspnetcore/issues/20648 we do it.
> 
> People will write a handler and perform async work. We will automatically call StateHasChanged() after the handler has completed. The only way we have to know that work has been cancelled and that we shouldn't call StateHasChanged is to catch the TaskCancelledException and avoid calling StateHasChanged in that case without tearing down the App/Circuit, since it is legitimate for the component to throw the TCS to cancel any async work.

So for handling cancellation of running tasks, you can:
- Catch the `TaskCanceledException` exception as is done in the tests
- Use the sample Javier produced at https://github.com/javiercn/CancellableWorkBlazor

**Comment by vd3d** [comment]
Hi @captainsafia ,

I have read the whole post and my problem is related, a call to JSRuntime is never ending and then canceled ! Sometimes it works... it is really random !

when doing this in pure Javascript, it works perfectly... but not using JSRuntime.

PS: here is my bug https://github.com/dotnet/aspnetcore/issues/21375
