### ISSUE TITLE
Remove signature block from dotnet.js

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18899]
There's a bunch of content in the dotnet.js file that looks like a signature block:

![image](https://user-images.githubusercontent.com/174281/74076826-b57ac000-49cf-11ea-9bf6-2bfe58a39dd7.png)

**Comment by javiercn** [comment]
@pranavkm I have some ideas on this area based on my current work.

Talk to me sometime this week and we can put together a plan :)

**Comment by mkArtakMSFT** [comment]
This is a dupe of https://github.com/dotnet/aspnetcore/issues/18900
