### ISSUE TITLE
Investigate parallelizing dotnet.[js|wasm] downloads

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18898]
![image](https://user-images.githubusercontent.com/174281/74076800-819f9a80-49cf-11ea-8d82-6736c582f07e.png)

**Comment by pranavkm** [comment]
Remember what this picture means.

**Comment by rynowak** [comment]
OK. I will. Thanks :)

**Comment by javiercn** [comment]
@pranavkm We plan to do this with `link rel=preload`

**Comment by pranavkm** [comment]
@javiercn is there an issue we can duplicate this with in that case?

**Comment by SteveSandersonMS** [comment]
Seems super basic to do just by moving a few lines of .ts code: #20029. Result:

![image](https://user-images.githubusercontent.com/1101362/77175289-4c9c6280-6aba-11ea-95d0-69e2cc41384b.png)

The highlighted block contains all requests for `.dll`, `.pdb`, `.wasm`, and `dotnet.*.js`, and they all start loading at roughly the beginning of that block.

**Comment by SteveSandersonMS** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/20029
