### ISSUE TITLE
Finish adding out css id tags on AzureAD/B2C views

### ISSUE THREAD

**Issue by pjevans** [dotnet/aspnetcore#18909]
### Is your feature request related to a problem? Please describe.
I previously added some id tags to the signedOut.cshtml page but added B2C naming on views held within AzureAD.  That got corrected and went ahead and filled the rest of the views out, naming all viewed object.  Very very minor update.

### Describe the solution you'd like
I corrected the mistake and finished adding the rest of the id tags for the views.  commit completed, sending PR.

### Additional context
Thanks again for helping me understand the system. Been a great learning experience.

**Comment by blowdart** [comment]
@HaoK can you take a look?

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/18910, thanks again @pjevans
