### ISSUE TITLE
Getting a TypeLoadException for IReadableStringCollectionExtensions when signing out after upgrading IdentityServer4 to version 3.1.1

### ISSUE THREAD

**Issue by paviad** [dotnet/aspnetcore#18905]
# Summary

When using the latest IdentityServer4 version (currently 3.1.1) the `/connect/endsession` endpoint throws a `TypeloadException` for `IReadableStringCollectionExtensions`

# Minimal Reproduction

# Setup

```
dotnet new angular -au individual
dotnet add package IdentityServer4 --version 3.1.1
```

# Execution

Run the app using `dotnet run` then navigate to `https://localhost:5001`, register a new user, then login using that user, then click the "Logout" link, you will get this error:

`TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.IReadableStringCollectionExtensions' from assembly 'IdentityServer4, Version=3.1.1.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b'.
`

# Environment

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
```

**Comment by rynowak** [comment]
> TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.IReadableStringCollectionExtensions' from assembly 'IdentityServer4, Version=3.1.1.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b'.

@javiercn is this us?

**Comment by javiercn** [comment]
@rynowak We target Identity Server 3.0. 

We can choose to upgrade if we want to 3.1, but that would likely require patch approval + testing to ensure everything works as expected.

It is similar as to when we update angular or react.

**Comment by leastprivilege** [comment]
I think I know what's going on here - we can discuss this week...

**Comment by blowdart** [comment]
Closing as external

**Comment by leastprivilege** [comment]
Thanks, Barry.

I will publish an update to make the external stuff work again with the internal stuff.

**Comment by leastprivilege** [comment]
I pushed a 3.1.2 version of IdentityServer that fixes the problem.
