### ISSUE TITLE
Custom validation library not being invoked when using a tag helper which invokes _htmlHelper.Editor

### ISSUE THREAD

**Issue by ciaran036** [dotnet/aspnetcore#18903]
#18127 # Describe the bug
As per this [StackOverflow questio](https://stackoverflow.com/questions/60078465/editorfor-tag-helper-doesnt-render-validation-attributes-when-using-fluentvalid)n, my problem is as follows: 

I have a simple form like this which makes use of the @Html.EditorFor extension:

```
<form method="post">
    @Html.EditorFor(x => x.SystemSettings.EmailFromAddress)
    <submit-button title="Save"></submit-button>
</form>
```
I want to take advantage of .NET Core's tag helpers so that my form looks like this instead:

```
<form method="post">
    <editor asp-for="SystemSettings.EmailFromAddress"/>
    <submit-button title="Save"></submit-button>
</form>
```
I also eventually would like to have my own custom tag helpers so I can do something like this instead:

`<text-box asp-for="SystemSettings.EmailFromAddress"></text-box>`
I have a string template which gets rendered by the @Html.EditorFor extension:

```
@model string
<div class="form-group">
    <label asp-for="@Model" class="m-b-none"></label>
    <span asp-description-for="@Model" class="help-block m-b-none small m-t-none"></span>
    <div class="input-group">
        <input asp-for="@Model" class="form-control" />
        <partial name="_ValidationIcon" />
    </div>
    <span asp-validation-for="@Model" class="validation-message"></span>
</div>
```
To do that, I saw someone implemented an EditorTagHelper, which looks like this:

```
[HtmlTargetElement("editor", TagStructure = TagStructure.WithoutEndTag,
    Attributes = ForAttributeName)]
public class EditorTagHelper : TagHelper
{
    private readonly IHtmlHelper _htmlHelper;

    private const string ForAttributeName = "asp-for";
    private const string TemplateAttributeName = "asp-template";

    [HtmlAttributeName(ForAttributeName)]
    public ModelExpression For { get; set; }


    [HtmlAttributeName(TemplateAttributeName)]
    public string Template { get; set; }

    [ViewContext]
    [HtmlAttributeNotBound]
    public ViewContext ViewContext { get; set; }

    public EditorTagHelper(IHtmlHelper htmlHelper)
    {
        _htmlHelper = htmlHelper;
    }

    public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    {
        if (context == null)
            throw new ArgumentNullException(nameof(context));

        if (output == null)
            throw new ArgumentNullException(nameof(output));

        if (!output.Attributes.ContainsName(nameof(Template)))
        {
            output.Attributes.Add(nameof(Template), Template);
        }

        output.SuppressOutput();

        (_htmlHelper as IViewContextAware).Contextualize(ViewContext);

        output.Content.SetHtmlContent(_htmlHelper.Editor(For.Name, Template));

        await Task.CompletedTask;
    }
}
```
When I use the EditorTagHelper though, it seems to be missing the unobtrusive Javascript validation attributes:

Using @Html.EditorFor, this gets rendered:

`<input class="form-control valid" type="text" data-val="true" data-val-required="Email From Address cannot be empty" id="SystemSettings_EmailFromAddress" name="SystemSettings.EmailFromAddress" value="whatever@test.com" aria-required="true" aria-invalid="false" aria-describedby="SystemSettings_EmailFromAddress-error">`
It's got the data-val attributes so client-side validation gets applied.

When I use the EditorTagHelper instead, this gets rendered:

`<input class="form-control valid" type="text" id="SystemSettings_EmailFromAddress" name="SystemSettings.EmailFromAddress" value="whatever@test.com" aria-invalid="false">`

The unobtrusive validation attributes are not being applied. I am using FluentValidation and I have specified an AbstractValidator like this:

```
public class SystemSettingsValidator : AbstractValidator<SystemSettings>
{
    public SystemSettingsValidator()
    {
        RuleFor(x => x.EmailFromAddress).NotEmpty()
            .WithMessage("Email From Address cannot be empty");
    }
}
```
I found that if I removed the AbstractorValidator and simply added a [Required] attribute to my model property the validation then works properly. This suggests that there is something wrong with FluentValidation. Perhaps there is a configuration issue.

I am using Autofac dependency injection to scan my assemblies and register validator types:

```
builder.RegisterAssemblyTypes(Assembly.Load(assembly))
    .Where(t => t.IsClosedTypeOf(typeof(IValidator<>)))
    .AsImplementedInterfaces()
    .PropertiesAutowired()
    .InstancePerLifetimeScope();
```
This seems to work fine. In case it wasn't fine, I also tried registering the validators from the fluent validation options like this:

```
.AddFluentValidation(fv =>
{
    fv.RegisterValidatorsFromAssemblies(new List<Assembly>
        {Assembly.GetExecutingAssembly(), Assembly.Load(nameof(Entities))});
})
```
This also seemed to be fine. I also tried not registering anything via Autofac and that didn't seem to make a difference neither. 

I have uploaded a working sample of the code here: https://github.com/ciaran036/coresample2

I [talked ](https://github.com/JeremySkinner/FluentValidation/issues/1312)to Jeremy Skinner who develops FluentValidation. He asked me to debug the FluentValidation library. When I use the @Html.EditorFor extension, the FluentValidation code is invoked. When I don't use it, the FluentValidation code is not invoked. He reckons that therefore there is an issue inside the aspnetcore framework rather than an issue with FluentValidation library. 

Although of course there's probably a higher probability of something I've misconfigured or simply haven't considered. 

Any help appreciated. Thanks! 

### To Reproduce
Navigate to the Settings Page to see the field I am trying to validate. On the Settings/Index.cshtml comment in the <editor ... > tag to see the validation not be applied. Comment in the @Html.EditorFor extension to see the validator attributes being applied. 

### Further technical details
- ASP.NET Core version: 3.1 (latest) 
- FluentValidation: v8.6.1 (latest)
- Visual Studio 2019 v16.4.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ciaran036.
While we do our best to look into every issue posted in this issue tracker, we're a small team and are not setup to debug customer applications.
If you came to conclusion that there is indeed an issue with the ASP.NET Core framework, then we will need to have a very small repro project to investigate it. The repro project is essentially the `default template` + minimum number of changes required to demonstrate the issue.
