### ISSUE TITLE
Consider minimizing dotnet.js

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#18900]
Looks like it strips whitespace, but it could be uglified \ minified further.

**Comment by javiercn** [comment]
Agree.

I also think we should look into producing a more modern bundle for webassembly, given that all our browsers support ES6.

**Comment by RemiBou** [comment]
What would be the point of uglifying ?

About minified, what is the gain vs gzip alone ?

**Comment by mkArtakMSFT** [comment]
We'll track this as part of https://github.com/dotnet/aspnetcore/issues/18899

**Comment by mkArtakMSFT** [comment]
Closing as there has been some improvement here already.
