### ISSUE TITLE
[Blazor, Webassembly] onclick event not working correctly inside loop

### ISSUE THREAD

**Issue by giorgi-abashidze** [dotnet/aspnetcore#18917]
hi,
i have following code for pagination, `@onclick="@(() => getData(i))"` i',m calling getdata function and passing i (pagenumber) to function but i is always 10, (i hardcoded 10 lets say we got 10 pages)
when loop is done i  is 10 of course but i want current value of i when declaring onclick function like:

`@onclick="@(() => getData(1))"`
`@onclick="@(() => getData(2))"`

and so on.

but its always 10

`@onclick="@(() => getData(10))"`
`@onclick="@(() => getData(10))"`

seems like reference of i is passed to function and its using always latest value of i 

 `                     
                           int i = 0;

                            while( i < 10)
                            {

                                if (i == currentPage)
                                {
                                    <li class="page-item active text-dark"><a class="page-link">@(i + 1)</a></li>
                                }
                                else
                                {

                                    <li class="page-item"><a class="page-link" @onclick="@(() => getData(i))">@(i + 1)</a></li>
                                }

                                i++;
                            }`

**Comment by rynowak** [comment]
This is how C# behaves when you combine loops and lambdas. See the notes at: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#lambda-expressions - this behavior is not specific to blazor and will occur with any C# code that creates a lambda inside a loop like your example.

You could work around this by aliasing `i` inside the loop body.

```C#
while( i < 10)
{
    var current = i; 
    ...
}
```

Then use `current` in your lambdas.

**Comment by giorgi-abashidze** [comment]
@rynowak thanks for the information.
