### ISSUE TITLE
SignalR client in Blazor app should throw meaningful exception on connection fail

### ISSUE THREAD

**Issue by duracellko** [dotnet/aspnetcore#18914]
### Describe the bug
Using SignalR (Microsoft.AspNetCore.SignalR.Client ver 3.1.1) client in Blazor (3.2.0-preview1.20073.1) application reports wrong exception, when connection fails. `HubConnection.StartAsync()` throws exception:

```text
WebAssembly.JSException:
TypeError: Failed to fetch
at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch
```

### To Reproduce
1. Follow example from [Blazor WebAssembly 3.2.0 Preview 1 release now available]
(https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/)
2. Change line `.WithUrl(NavigationManager.ToAbsoluteUri("/chatHub"))` in **Index.razor** to not existing URL `.WithUrl("http://localhost:5005/chatHub")`
3. Run application and check console log in browser. There is error: `WASM: WebAssembly.JSException: TypeError: Failed to fetch`

### Actual behavior

There are 2 problems with the exception.

1. `WebAssembly.JSException` is internal type, so it is not possible to catch the specific exception.
2. `TypeError: Failed to fetch` is not very clear error message.

### Expected behavior

I would expect `System.Net.Http.HttpRequestException` or something similar to report that connection was not successful.

### Further technical details
- ASP.NET Core version 3.1.1
- Microsoft.AspNetCore.SignalR.Client: 3.1.1
- Blazor client side:
  - Microsoft.AspNetCore.Blazor: 3.2.0-preview1.20073.1
  - Microsoft.AspNetCore.Blazor.Build: 3.2.0-preview1.20073.1
  - Microsoft.AspNetCore.Blazor.HttpClient: 3.2.0-preview1.20073.1
- `dotnet --info`
```text
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@duracellko thanks for contacting us.

We believe this issue belongs in the [mono/mono](https://github.com/aspnet/aspnetcore) repo. We will discuss the issue within the team and re-route appropriately.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#18780
