### ISSUE TITLE
dotnet user-secrets list not working on published asp.net core app

### ISSUE THREAD

**Issue by xshiiiidev** [dotnet/aspnetcore#18920]
Hello I published my asp.net core mvc app on a linux server under the /var/www/mywebsite

I navigate inside mywebsite folder and execute this

`dotnet user-secrets list`

And then an error was returned.

> Could not find a MSBuild project file in /var/www/mywebsite. Specify which project to use with the --project option.

any idea why this happened ?

**Comment by javiercn** [comment]
@xshiiiidev thanks for contacting us.

User secrets is a development only feature and is not meant to be used on published applications. See https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows for details.
