### ISSUE TITLE
Occasional mixing of code-behind and razor file when renaming razor file

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#18927]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14987221/74178299-27315480-4bf0-11ea-89df-ab278af023af.png)

Per the report: 
"I renamed `@DoThatThing` to `@DoesNotExist` and after saving and waiting those are the reported problems"

**Comment by ryanbrandenburg** [comment]
Got some clairification: The scenario here is to paste in `@DoesNotExist`, then have both the __virtual.cs and .razor results. If you edit the file it will disappear.

**Comment by NTaylorMullen** [comment]
Fixed in O#
