### ISSUE TITLE
Send Alt-Svc frame in HTTP/2 rather than header. 

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#18928]
Spec: https://tools.ietf.org/html/rfc7838#section-4

Right now, to indicate an Alt-Svc in HTTP/3 we are setting the Alt-Svc header. In HTTP/2, there is a frame type we could be sending from the Server to the Client to indicate an alternative service as well.

**Comment by adityamandaleeka** [comment]
Closing since we don't see the value in this as of now. Will reopen if needed.
