### ISSUE TITLE
Data Annotations Not Working when Model Binding to a Reflected Type

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#18924]
I have a model binder which effectively says:

```csharp
var modelType = Type.GetType("Foo,Bar");

var model = Activator.CreateInstance(modelType);
var modelMetadata = _modelMetadataProvider.GetMetadataForType(modelType);
var modelBinder = _modelBinderFactory.CreateBinder(new ModelBinderFactoryContext() {
    Metadata = modelMetadata,
    CacheToken = modelMetadata
});

using (var scope = bindingContext.EnterNestedScope(modelMetadata, bindingContext.FieldName, bindingContext.ModelName, model)) {
    await modelBinder.BindModelAsync(bindingContext);
}

bindingContext.Result = ModelBindingResult.Success(model);
```

This works fine, however I have noticed if the model type has data annotation attributes on any of it's properties then they are ignored and the ModelState always says it's valid.

I'm not sure if this is really a bug as it's abit of an advanced scenarios but I was wondering if anyone could point me in the right direction.

**Comment by rynowak** [comment]
Model validation is based on the data found in `ModelBindingContext.ValidationState`.

If you're doing things like changing the type that's bound you'll need to initialize a `ValidationStateEntry`. [Here](https://github.com/dotnet/aspnetcore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/ModelBinding/Binders/FormFileModelBinder.cs#L128)'s an example of where this is done in the framework for one of the binders. 

You'll probably need to set `Key` and `Metadata` on the entry: https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Abstractions/src/ModelBinding/Validation/ValidationStateEntry.cs#L15

**Comment by nfplee** [comment]
@rynowak thanks the following worked perfect:

```csharp
bindingContext.ValidationState.Add(model, new ValidationStateEntry() {
    Key = bindingContext.ModelName,
    Metadata = modelMetadata
});
```

This got me thinking about how I could add valdation to following attributes binder:

```csharp
var attributes = (IDictionary<string, object>)bindingContext.Model ?? new Dictionary<string, object>();

var properties = ...;

foreach (var property in properties) {
    var name = $"{bindingContext.ModelName}[{property.Name}]";

    if (bindingContext.ValueProvider.ContainsPrefix(name)) {
        var modelMetadata = _modelMetadataProvider.GetMetadataForType(property.PropertyType);
        var modelBinder = _modelBinderFactory.CreateBinder(new ModelBinderFactoryContext() {
            Metadata = modelMetadata,
            CacheToken = modelMetadata
        });

        using (var scope = bindingContext.EnterNestedScope(modelMetadata, name, name, null)) {
            await modelBinder.BindModelAsync(bindingContext);

           if (bindingContext.Result.IsModelSet)
                attributes[property.Name] = bindingContext.Result.Model;
        }
    }
}

bindingContext.Result = ModelBindingResult.Success(attributes);
```

I tried doing:

```csharp
bindingContext.ValidationState.Add(attributes, new ValidationStateEntry() {
    Key = bindingContext.ModelName,
    Metadata = _modelMetadataProvider.GetMetadataForType(attributes.GetType())
});
```

However it didn't work. I looked at the DictionaryModelBinder but alot of the code is internal and I was wondering if there was a simpler way of doing it.

**Comment by rynowak** [comment]
Based on how you're computing the keys (`$"{bindingContext.ModelName}[{property.Name}]"`) - I think the best this to do would be to add each attribute value with its own mapping into the validation state entries.

The most complex part of model binding is dealing with how the system interprets keys for collections. You can avoid that by mapping each entry explicitly.

```C#
var attributes = (IDictionary<string, object>)bindingContext.Model ?? new Dictionary<string, object>();

var properties = ...;

foreach (var property in properties) {
    var name = $"{bindingContext.ModelName}[{property.Name}]";

    if (bindingContext.ValueProvider.ContainsPrefix(name)) {
        var modelMetadata = _modelMetadataProvider.GetMetadataForType(property.PropertyType);
        var modelBinder = _modelBinderFactory.CreateBinder(new ModelBinderFactoryContext() {
            Metadata = modelMetadata,
            CacheToken = modelMetadata
        });

        using (var scope = bindingContext.EnterNestedScope(modelMetadata, name, name, null)) {
            await modelBinder.BindModelAsync(bindingContext);

           if (bindingContext.Result.IsModelSet)
                attributes[property.Name] = bindingContext.Result.Model;

                bindingContext.ValidationState.Add(bindingContext.Result.Model, new ValidationStateEntry()
                {
                    Key = name,
                    Metadata = ...
                });
        }
    }
}

bindingContext.Result = ModelBindingResult.Success(attributes);
```

**Comment by rynowak** [comment]
Note that `modelBinderFactory.CreateBinder` is a really expensive operation. Model binding attempts to resolve all of these things up front to avoid doing this kind of thing per-request.

**Comment by nfplee** [comment]
Thanks, I've just tried that and I keep getting the error:

> ArgumentNullException: Value cannot be null. (Parameter 'key')

Also thanks for the additional information. Both the attributes and parameters model binders are only used in the admin panel so performance isn't too much of an issue.

**Comment by rynowak** [comment]
> Thanks, I've just tried that but I am getting the error:
>ArgumentNullException: Value cannot be null. (Parameter 'key')

I think that would be the case in the following code that I highlighted in comments:

```C#
if (bindingContext.Result.IsModelSet)
{
    attributes[property.Name] = bindingContext.Result.Model;

    // bindingContext.Result.Model == null
    bindingContext.ValidationState.Add(bindingContext.Result.Model, new ValidationStateEntry()
    {
        Key = name,
        Metadata = ...
    });
}
```

If the model is null, there's nothing to validate anyway. You can just add an `if` and skip adding a validation entry.

**Comment by nfplee** [comment]
Thanks for getting back to me, but I'm testing a Required field data annotation (on a string property) and if I skip over it when the value is null then the ModelState says it's valid.

**Comment by rynowak** [comment]
OK, can we start at the beginning then? What are you trying to do?

**Comment by nfplee** [comment]
Yeah sure, against my ViewModel I have the following property:

```csharp
[BindAttributes]
public IDictionary<string, object> Attributes { get; set; }
```

Here's my model binder provider:

```csharp
public class AttributesModelBinderProvider : IModelBinderProvider {
    public IModelBinder GetBinder(ModelBinderProviderContext context) {
        if (context.Metadata.PropertyName == null)
            return null;

        if (context.Metadata.ContainerType.GetProperty(context.Metadata.PropertyName).IsDefined(typeof(BindAttributesAttribute), false))
            return new BinderTypeModelBinder(typeof(AttributesModelBinder));

        return null;
    }
}
```

Now my model binder's BindModelAsync method for this says:

```csharp
public async Task BindModelAsync(ModelBindingContext bindingContext) {
    var attributes = (IDictionary<string, object>)bindingContext.Model ?? new Dictionary<string, object>();

    var properties = GetTypesWithAttribute<AttributesAttribute>().SelectMany(t => t.GetProperties());

    foreach (var property in properties) {
        var name = $"{bindingContext.ModelName}[{property.Name}]";

        if (bindingContext.ValueProvider.ContainsPrefix(name)) {
            // Create the model and model binder
            var modelMetadata = _modelMetadataProvider.GetMetadataForType(property.PropertyType);
            var modelBinder = _modelBinderFactory.CreateBinder(new ModelBinderFactoryContext() {
                Metadata = modelMetadata,
                CacheToken = modelMetadata
            });

            using (var scope = bindingContext.EnterNestedScope(modelMetadata, name, name, null)) {
                await modelBinder.BindModelAsync(bindingContext);

                if (bindingContext.Result.IsModelSet)
                    attributes.Set(property.Name, bindingContext.Result.Model);
            }
        }
    }

    bindingContext.Result = ModelBindingResult.Success(attributes);
}
```

Note: GetTypesWithAttribute<AttributesAttribute>() retrieves any types which have the AttributesAttribute attribute. Here's an example of a matching type:

```chsarp
[Attributes]
public class PostAttributes {
    [Required]
    public string Attribute1 { get; set; }
}
```csharp

Now say my form renders the following:

<input type="text" name="Attributes[Attribute1]" />

If I leave the value blank I'd like it to validate (on the server) and say it's required. Please note that the value correctly updates so I know my model binder works, it's just the validation I can't get working.

I had not initially planned on doing this but once I saw how trivual it was to validate the parameters (the original issue) I figured this would be the same.

I hope that makes my intentions a little clear. Please let me know if you need any more information.

Thanks

**Comment by rynowak** [comment]
OK great. I'll try to help with this. It will take me a little bit.

**Comment by nfplee** [comment]
Thanks I really appreciate it. Please let me know if I can assist any way. I can see why my attempts have failed so far, as the model meta data has no knowledge of the properties data annotation attributes.

**Comment by rynowak** [comment]
You're running into a problem here with validation btw because validation is meant to operate on the *properties of an object* rather than on a single value. 

In your care you're turning a group of classes into a dictionary (no properties in sight).

So I'm not sure there's a great way to have what you want without writing your own validation logic.

**Comment by nfplee** [comment]
Thanks @rynowak for taking a look. I'm thinking of looping over each type from GetTypesWithAttribute  and then create an instance using reflection. This is similar to what I did with the parameters model binder (above), therefore the model binding logic should be the same (including validation). Finally I just have to update my HTML fields to say:

<input asp-for"Attribute1" />

This actually improves things as I can make this strongly typed and I'll just set the HtmlFieldPrefix to "Attributes".

I'll publish the result when I'm done incase it helps someone else.

**Comment by rynowak** [comment]
Ok great, I'm glad you found a solution.

**Comment by nfplee** [comment]
@ryowak my attempts so far have failed. Here's my updated model binder's BindModelAsync method:

```chsharp
public async Task BindModelAsync(ModelBindingContext bindingContext) {
    var attributes = (IDictionary<string, object>)bindingContext.Model ?? new Dictionary<string, object>();

    var types = _moduleManager.GetTypesWithAttribute<AttributesAttribute>();

    foreach (var type in types) {
        var model = Activator.CreateInstance(type);
        var modelMetadata = _modelMetadataProvider.GetMetadataForType(model.GetType());
        var modelBinder = _modelBinderFactory.CreateBinder(new ModelBinderFactoryContext() {
            Metadata = modelMetadata,
            CacheToken = modelMetadata
        });

        using (var scope = bindingContext.EnterNestedScope(modelMetadata, bindingContext.FieldName, bindingContext.ModelName, model)) {
            await modelBinder.BindModelAsync(bindingContext);

            if (bindingContext.Result.IsModelSet) {
                foreach (var property in type.GetProperties().Where(p => bindingContext.ValueProvider.ContainsPrefix($"{bindingContext.ModelName}.{p.Name}"))) {
                    attributes.Set(property.Name, property.GetValue(model));
                }
            }
        }

        bindingContext.ValidationState.Add(model, new ValidationStateEntry() {
            Key = bindingContext.ModelName,
            Metadata = modelMetadata
        });
    }

    bindingContext.Result = ModelBindingResult.Success(attributes);
}
```

This looks the same as my parameters to me, the only difference is that I have multiple types that can contain attributes.

My next step is to step through the source code, but I'm open to suggestions. Thanks
