### ISSUE TITLE
Ensure the servicing attribute is set correctly on assemblies

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#18930]
This is a followup item to the Arcade conversion originally filed at https://github.com/dotnet/aspnetcore/issues/13350.

The action item here is to verify whether the assembly is now correctly set during servicing. Details are at https://github.com/dotnet/arcade/issues/1526

**Comment by dougbu** [comment]
Researched this issue a bit while working on dotnet/efcore#22649. That PR included the only change necessary to add the attribute to our shipping assemblies.

Arcade defaults `$(Serviceable)` to `true` and none of dotnet/aspnetcore, dotnet/aspnetcore-tooling, or dotnet/efcore override that default. This covers the `serviceable` setting in generated `*.nuspec` files.

Further checks:
- [ ] Does dotnet/aspnetcore-tooling add `[AssemblyMetadata("Serviceable", "true")]` to all assemblies❔
    - No
- [ ] Do packages built using custom `*.nuspec` files include the correct setting❔
   - All but the VS.Redist.Common.AspNetCore.SharedFramework and VS.Redist.Common.AspNetCore.TargetingPack packages are fine

What remains is adding the missing `[AssemblyMetadata(...)]` in dotnet/aspnetcore-tooling and using `$CommonMetadataElements)` or something similar in dotnet/aspnetcore `*.wixproj` projects.

**Comment by dougbu** [comment]
The VS.Redist.Common.AspNetCore&hellip; packages don't ship and their .nuspec properties probably don't matter that much. I'll add `<serviceable>true</serviceable>` but doubt it will make much difference.

**Comment by dougbu** [comment]
Just waiting on dotnet/aspnetcore-tooling#2701 (the back-port of dotnet/aspnetcore-tooling#2696) to close this

**Comment by wtgodbe** [comment]
Closing as the last PR is in
