### ISSUE TITLE
IDX10501 error with multiple authentication schemes

### ISSUE THREAD

**Issue by kmk713** [dotnet/aspnetcore#18940]
### Describe the bug
Similar to an issue mentioned in AspNetCore.Docs 
[https://github.com/aspnet/AspNetCore.Docs/issues/16190](https://github.com/aspnet/AspNetCore.Docs/issues/16190)
[https://github.com/aspnet/AspNetCore.Docs/issues/16389](https://github.com/aspnet/AspNetCore.Docs/issues/16389)

I have an application using twoauthentication schemes (called Auth0 and a Custom-Auth scheme).
Auth0 uses asymmetric signing (RS256) and Custom-Auth uses symmetric (SHA256). 

If I configure just one of them (does not matter which one) it works as expected. 
However, when I configure two schemes (like the example in To reproduce section), I get the following error in the app insights (with `IdentityModelEventSource.ShowPII` set to true in `Startup.cs`):

`
IDX10501: Signature validation failed. Unable to match key: 
kid: '[someKey]'.
Exceptions caught:
 'System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'RS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey, KeyId: '', InternalId: '[someId]'.'
 is not supported. The list of supported algorithms is available here: https://aka.ms/IdentityModel/supported-algorithms
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'. 
token: '{"alg":"RS256","typ":"JWT","kid":"[someKey]"}.{"iss":"[someAuthProvider]","sub":"[someUserId]","aud":"[someAudience]","iat":1580871648,"exp":1583463648,"azp":"[someSecret]","gty":"password"}'. 
`

My guess is that the token intended for Auth0 authentication gets validated twice (against each configured scheme) and therefore it fails for one of them (Custom-Auth) which doesn't use kid.

### To Reproduce

I have the following in `ConfigureServices(IServiceCollection services)` in `Startup.cs`

``` C#
        services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer("Auth0", options =>
            {
                options.Authority = "someAuthority";
                options.Audience = "someAudience";
            }).AddJwtBearer("Custom-Auth", options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("someKey")),
                    ValidateIssuer = false,
                    ValidateAudience = false
                };
            });
        services.AddAuthorization(options =>
            {
                options.DefaultPolicy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .AddAuthenticationSchemes("Auth0", "Custom-Auth")
                    .Build();
            });
```
Whenever an API call is made to endpoint that has `[Authorize]` attribute on it, the IDX10501 error gets thrown.

### Further technical details
- ASP.NET Core version
3.0

- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019
Version 16.4.2

**Comment by rckreddy** [comment]
Try this and see if it works
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
            {
                options.Authority = "Auth0 Authority";
                options.Audience = "Auth0 Audience";
            }).AddJwtBearer("Custom-Auth", options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes("someKey")),
                    ValidateIssuer = false,
                    ValidateAudience = false
                };
            });
        services.AddAuthorization(options =>
            {
                /* Just define your policies if any here */
                 options.AddPolicy("SomePolicy", policy => policy.AddRequirements(new SomeRequirement()));
            });

services.AddControllers(options =>
            {
                 var policy = new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                    .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme, "Custom-Auth")
                    .Build();

             options.Filters.Add(new AuthorizeFilter(policy));
          });

Also Make sure when using the Authorize attribute on your action methods, you specify the schemes
as below
[Authorize(Policy = "SomePolicy",AuthenticationSchemes="Bearer, Custom-Auth")]

Hope this helps!!

**Comment by blowdart** [comment]
Does the logged error actually stop authentication, or is it just logged with no real effects?

**Comment by kmk713** [comment]
@blowdart yes it just gets logged, but has no effects other than it's clogging up the log quite badly

**Comment by kmk713** [comment]
@rckreddy I'll try out the suggestion soon and post updates! Cheers

**Comment by blowdart** [comment]
ok phew :)

In that case I'm going to suggest you ask on the AAD repo about how to adjust the logging level. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet is probably a good place to ask.

**Comment by cherici-simone** [comment]
I'm also in the same situation... @kmk713 did you try/open issue on AAD repo as subbested by @blowdart ? because for me this is a blocking issue

**Comment by blowdart** [comment]
Closing as external, because its in the AAD pieces rather than our code.
