### ISSUE TITLE
Disable Diagnostics and Activity

### ISSUE THREAD

**Issue by ladeak** [dotnet/aspnetcore#18955]
[Question]

In ASP.NET Core 2 HostingApplicationDiagnostics only created Activity.Current if we manually subscribed DiagnosticsListener for events ```Microsoft.AspNetCore.Hosting.HttpRequestIn```.

In ASP.NET Core 3.1 it seems the Activity.Current is always created. That means if I have a Request-Id in the header, it is being used by the Activity by default. Is there a way to opt-out this behavior (other than turning off logging)?

**Comment by benaadams** [comment]
Switch off `"Microsoft.AspNetCore.Hosting.Diagnostics"` also need to do it for `EventLog` on Windows 

e.g. appsettings.json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",

      "Microsoft.AspNetCore.Hosting.Diagnostics": "None"
    },
    "EventLog": {
      "LogLevel": {
        "Microsoft.AspNetCore.Hosting.Diagnostics": "None"
      }
    }
  },
```

**Comment by ladeak** [comment]
Perfect. We use this in some of our tests, which expected Diagnostics off by default and turned on by us later by subscribing to DiagnosticsListener.
