### ISSUE TITLE
ConsumesAttribute doesn't support Content-Type headers with list of types

### ISSUE THREAD

**Issue by LucianBornaz** [dotnet/aspnetcore#18952]
### Describe the bug
ConsumesAttribute performs an exact match on Content-Type http request header and the values it has been set up to accept.
Content-Type values such as "application/json; charset=utf-8" will not be matched by an action decorated with [Consumes("application/json")] and the response will be 404 NOT_FOUND

### To Reproduce
1. create a net core web api project
2. create a controller with an action decorated with:
``` C#
[Consumes("application/json")]
```
2. create a net core test project for the net core web api
3. write an end-to-end test for that action which uses Microsoft.AspNetCore.TestHost.TestServer to  spin up the net core web api 
``` C#
var server = new TestServer(new WebHostBuilder()
                .UseConfiguration(configuration)
                .UseStartup<Startup>();
```
4. write test to make an http request to the action in net core web api
``` C#
var httpRequest = new HttpRequestMessage(HttpMethod.Post, controllerRelativeUrl)
            {
                Content = new StringContent(JsonSerializer.Serialize(bodyObject), Encoding.UTF8, "application/json")
            };

 var response = await HttpClient.SendAsync(httpRequest);
```

The request will pass Content-Type haeder as "application/json; charset=utf-8" which will not be validated by ConsumesAttribute although it's a valid request.
The http status code will be 404 NOT_FOUND although it should be 200 OK.

### Further technical details
- ASP.NET Core version: 3.0
- Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 16.4.4

**Comment by pranavkm** [comment]
A mismatched media-type should result in a 415 result, not a 404. Can you share a minimal project as a GitHub repo that reproduces this problem?
