### ISSUE TITLE
Make appsettings.hjson the default config file

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#18950]
Right now, appsettings.json is the default config file read by ASP.NET Core.  I think it'd make more sense to default everything to .hjson (and read appsettings.json if the .hjson didn't exist).  It's widely acknowledged that JSON was never intended to be used for human-readable config files, and it has various shortcomings as such (including notably the lack of comments).  Whilst I realize that the ASP.NET Core JSON parser allows comments, this is a nonstandard implementation of JSON which actually violates the original standard.  HJSON is specifically designed to be human-readable and allow things like comments.  If JSON is going to be used as the default config format rather than XML, at least a more human-readable extension of it should be used.  Then, other programs looking at said file could realize that it's HJSON based on the file extension, and not mark comments as errors.

**Comment by davidfowl** [comment]
What would be the value in changing this convention? Is hjson widely adopted? What about json5? While I sympathize with the premise it doesn't seem practical to change this as there's no real benefit for customers.

**Comment by Pilchie** [comment]
Closing as stale.
