### ISSUE TITLE
Blazor Server Side app with Microsoft.identity.web

### ISSUE THREAD

**Issue by sowsan** [dotnet/aspnetcore#18960]
Anyone has success with integrating Blazor Server Side app with Microsoft.Identity.Web for Azure AD ? You can find a thread here on the issue that I have reported. 

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/285

**Comment by javiercn** [comment]
@sowsan thanks for contacting us.

With regards to authentication, Blazor server-side applications behave like a regular web application. You need to authenticate in the same way and provision any token you need before you start the Blazor application.

Then, you can pass any token you want to your app as parameters to the root component.

**Comment by sowsan** [comment]
Thank you, is there a sample for the same following authorization code flow with scope to call an API protected using Azure AD?

Regards,
Sowmyan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
