### ISSUE TITLE
ASP.NET CORE 3.1 Default Authentication Policy executing last when combined with other policies 

### ISSUE THREAD

**Issue by johnayoub** [dotnet/aspnetcore#18961]
### Describe the bug

Similar to ASP.CORE 2.2 and global filters I expect that adding a `RequireAuthorization` to endpoints would apply globally. That's true, expect when combined with `Authorize` attributes on a controller they execute last which seems like a deviation from previous implementations. In the below example, the `Authorize` attributes on the controller are meant to run only after the user has been authenticated and the context has been established. However, both policies run first and the default policy `DenyAnonymousAuthorizationRequirement` runs last. Is this the new behavior in 3.0+? How can I get the the default policy to run first?

### To Reproduce
In Startup add the following 
```
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers().RequireAuthorization();
});
```

On a controller add the following attributes
``` C#
    [Authorize(Policy = "Policy1")]
    [Authorize(Policy = "Policy2")]
    public class HomeController: Controller 
   {
   }
```

### Further technical details
- ASP.NET Core version **3.1**
```
- Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
- The IDE (**VS**) you're running on, and it's version (**Version 16.4.3**)

**Comment by javiercn** [comment]
@johnayoub thanks for contacting us.

@HaoK  can you chime in on what's going on here?

**Comment by mkArtakMSFT** [comment]
As a side note, it looks like the version of the framework you're using is outdated and is not supported any more.
Consider upgrading to a newer supported version of the framework to make sure it's secure and you get all the new features.
You can learn more about the .NET Core support policy at https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by johnayoub** [comment]
@mkArtakMSFT Thanks! Yes, we're using the latest version 3.1. I was referencing 2.2 as the behavior has changed since we migrated to 3.1. Sorry if that bit wasn't clear.

**Comment by HaoK** [comment]
Why does order matter? All policies need to succeed for the request to be authorized.

**Comment by johnayoub** [comment]
@HaoK That's true but before we relied on the global filters executing first so if the user is not authenticated it short circuits and redirects the user to login. With this new behavior, I have to check in every policy if the user is authenticated or not before I do anything else. I don't know if that behavior is intentional or not but I didn't see this pointed out it in the migration guide from 2.2 to 3+. In 2.2 there was always an order to the authorize filters execution, Global -> Controller -> Action. In our case we applied a global filter to make sure the user is authenticated and then subsequent controller and action level policies would just execute knowing that the user is authenticated.

**Comment by johnayoub** [comment]
@HaoK @anurse could I get some clarification if this is the expected behavior? Is there a global authorize policy that I could run before controller and action level ones?

**Comment by HaoK** [comment]
The default implementation (and expectation), is that all policies succeed for authorization to succeed, we make no guarantees on ordering.  It sounds like you were relying on a specific ordering before, and also relying on short circuiting.  You can certainly add the concept of ordering to your requirements and implement a custom authorization service that sorts the requirements before executing them, that way you can control the ordering explicitly, but this is something that you would need to build

**Comment by johnayoub** [comment]
@HaoK thanks for confirming that!

**Comment by Rick-Anderson** [comment]
@HaoK  should I add this to [Policy-based authorization ](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1)

in 3.0 and later,
Requirement handlers can execute in any order. Do not depend on order.

**Comment by HaoK** [comment]
@Rick-Anderson sorry for not responding to this earlier, yeah I think we should just add that snippet to the docs, I'll file a PR with that update and ping you for review

**Comment by HaoK** [comment]
Behavior is by design, but docs have been updated to clarify
