### ISSUE TITLE
Component library dependency propagation  

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#18974]
### Is your feature request related to a problem? Please describe.
I am trying to build a component library which will build on top of existing libraries.

MyClient <- MyLibrary <- OtherLibrary

If code in OtherLibrary has dependencies on scripts from cdn (e.g bootstrap), how can I propagate that into MyClient (Blazor) index.html/_Host.cshtml
### Describe the solution you'd like
I've explored using a script/style injector which calls to JS to inject the relevant tags into the DOM but feel like there should be some easier way to achieve this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do as it doesn't align well with the plan we have in mind.
The framework has no way to know which of the references to add and in which order.
You can definitely add explicit references to those files from your pages/components, if those files are part of the dependent projects.

**Comment by grahamehorner** [comment]
@mkArtakMSFT I'm interested to understand your explanation/comment 

> You can definitely add explicit references to those files from your pages/components, if those files are part of the dependent projects.

As I understand that the <script> tag is not able to be used from with inside a component and therefore a developer using a component needs to have explicit knowledge about scripts/styles required to use which IMHO they shouldn't need unless overriding functionality/styling.

are you able to point us to examples?

**Comment by ScottKane** [comment]
Also just to clarify @mkArtakMSFT, I didn't mean something automatic. I just meant a mechanism for copying and merging an index.html file (containing only <head>/<body> tags) from my RCL into that of my Blazor client

**Comment by grahamehorner** [comment]
@mkArtakMSFT IMHO it's would be good to have a component model that supported the HTML import https://www.html5rocks.com/en/tutorials/webcomponents/imports/ that way a component could inform the DOM that it has a number of StaticWebAssets it needs to import

**Comment by javiercn** [comment]
@grahamehorner HTML imports are deprecated and have several issues. Many of which this model would share.

See https://github.com/dotnet/aspnetcore/issues/14911#issuecomment-541017878 for a more detailed explanation of why this an herculean task fraught with peril that is bound to fail beyond the most basic scenarios.

Also, this is something that can be built on top of the existing static web assets support, so it is not something we plan to build.

I know this is not likely the answer that you expect to hear, but we as a team consider this is a very complex scenario to try and solve and it would take valuable time away from improving other areas with a small ROI in comparison.

Hope that helps.
