### ISSUE TITLE
Razor Component not working when new protected virtual methods used

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/aspnetcore#18976]
### Describe the bug
when creating/using a custom component base class that is derived from ComponentBase that has
exposese new protected virtual methods; then calls the ComponentBase method the component razor fails to call the component methods
 
### To Reproduce
create a razor component class which is derived from the ComponentBase; hide one/or more of the protected methods of the ComponentBase using the new protected virtual modifiers; place a break point on the method, in side the method call the base class implementation.

use the component in a razor page; note the component is NOT called by the rendering engine and break point triggered.

### Further technical details
I would expect the component methods to be called as the contract is valid for razor components

**Comment by javiercn** [comment]
@3GDXC thanks for contacting us.

If you are hidding the methods with the `new` keyword, that's likely not something we currently support or plan to support.

Could you give us more information about your use case so that we can better evaluate the situation?

**Comment by 3GDXC** [comment]
@javiercn while the ComponentBase is for the majority of use cases acceptable; I was looking to create a set of generic ComonentBase implementations for automated testing; forcing the implement developer to have implementation for methods while hiding others;  the base components implement the IComponent interface; it was my understanding that razor used reflection on the component methods to find the correct signature and/or the interface then call the component accordingly? am I correct in this understanding and/or has this changed?

**Comment by javiercn** [comment]
@3GDXC I don't believe we do any sort of reflection to find the right signature. We simply call SetParametersAsync. All the logic regarding OnInitializeAsync and OnParametersSet is defined in ComponentBase.

**Comment by rynowak** [comment]
If your goal is to bypass ComponentBase`, you have a few options:
- Implement all of the same interfaces as `ComponentBase` without inheriting from it
- Inherit from `ComponentBase` use `new` to replace methods, and then **redeclare** the interfaces that those methods implement.

The second one uses a feature of C# that's little-known called interface re-implementation: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/interfaces#uniqueness-of-implemented-interfaces
