### ISSUE TITLE
[Blazor] Provide redirect to login component in Microsoft.AspNetCore.Authorization

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#18979]
We plan to include it as part of the templates for auth in Blazor wasm, but we should have one out of the box in Microsoft.AspNetCore.Components.Authorization given that this is **not** wasm specific.

**Comment by ryanelian** [comment]
Would this feature only limited in Blazor WASM?

I made a past issue where this feature is also crucial in server-side Blazor using OpenID Connect: (it is marked as Discussion unfortunately)

https://github.com/dotnet/aspnetcore/issues/13709

There are numerous other people in that thread who also requested such feature to be implemented.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
