### ISSUE TITLE
Equivalent of the MVC command url.content in Blazor.net webassembly (client side)

### ISSUE THREAD

**Issue by sodeshpa** [dotnet/aspnetcore#18978]
@foreach (var item in Model)
    {
        string myImgDest = "~/Images/" + item.FieldName+ ".jpg";
 @if (item.IndVreComp == 1) --- Based on some condition , i am changing the url src
                {
                    <img src="@Url.Content(myImgDest )" alt="my text" title="my title" />
                }
i am dynamically constructing the "src" part of the html <img src in MVC4.
Now i am trying to find the equivalent of the same in **Blazor webassembly client side**. What is the equivalent of this **.url.content**

**Comment by rynowak** [comment]
Not sure if you closed this because you found the answer, but here it is...

In Blazor all of the templates set `<base href="...some path..." />`. You don't need a feature like `~/`, you can just use a normal relative path `Images/pizza.jpg` and the browser will do the right thing.
