### ISSUE TITLE
IHostedService is consuming more memory in .net core 2.0

### ISSUE THREAD

**Issue by DEVASENASYN** [dotnet/aspnetcore#18973]
Hi,
I'm using IHosted service to process the records for every 3 seconds. Looks like it is consuming more memory and slow down the execution time

**1st time execution:**
When I try to process 50 records (5 batches)
1st batch execution time : 8542 ms
2nd batch execution time : 7989 ms  
3rd batch execution time : 26513 ms
4th batch execution time : 43848 ms
5th batch execution time : 40477 ms

Execution time is increasing after multiple runs for the same records
1st batch execution time : 43477 ms
2nd batch execution time : 42876 ms  
3rd batch execution time : 37752 ms
4th batch execution time : 46268 ms
5th batch execution time : 42183 ms

I'm using single service for both web app and background worker and no other requests are coming from web site .. 

Using IHosterService only
 **public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IHostedService, MyService>();
      }**

**MyService:**

 protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {

        while (!stoppingToken.IsCancellationRequested)
        {
            if (!CurrentlyRunning)
            {
                CurrentlyRunning = true;
                await _service.RunBackgroundQueue();
                CurrentlyRunning = false;
            }

            await Task.Delay(3000, stoppingToken);
        }
    }

**Comment by davidfowl** [comment]
There's nothing special about IHostedService. Have you profiled your application to see where the time is bring spent?

**Comment by anurse** [comment]
@DEVASENASYN what exact versions are you targeting? .NET Core 2.0 is [has been end-of-life since October 2018](https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle).

**Comment by DEVASENASYN** [comment]
@anurse  I'm using 2.0.0

**Comment by anurse** [comment]
Probably, but also we don't provide support for 2.0.0 any more so you'll need to upgrade to a supported release for us to be able to assist further.
