### ISSUE TITLE
ControllerBase.ValidationProblem() does not respect ApiBehaviorOptions

### ISSUE THREAD

**Issue by kevbite** [dotnet/aspnetcore#18977]
### Describe the bug
When setting up the `ApiBehaviorOptions` within `ConfigureServices` of an MVC project.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
       .ConfigureApiBehaviorOptions(opt
           =>
           {
               opt.InvalidModelStateResponseFactory =
                   (context => new OkObjectResult("Hello?"));
           });
}
```

The custom `InvalidModelStateResponseFactory` is not respected when calling `ControllerBase.ValidationProblem()` within an action. The body of the response is just:

```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|b587c9f9-4aff6eb0721c184a.",
    "errors": {
        "To": [
            "custom"
        ]
    }
}
```

### Further technical details
C:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE 
JetBrains Rider
Version: 2019.3.2
Build: 193.6015.57

**Comment by pranavkm** [comment]
`ApiBehaviorOptions.InvalidModelStateResponseFactory` is specifically used by the filter (unfortunately the API documentation doesn't do a very good job of conveying this).  If you'd like `ValidationProblem` to return a different result, there's a couple of options:

a) You could have a custom base controller type that overrides `ValidationProblem`
b) You could implement a [`ProblemDetailsFactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.infrastructure.problemdetailsfactory?view=aspnetcore-3.1) and register it in DI. The framework uses this type to construct all `ProblemDetails` and `ValidationProblemDetails` instances.

**Comment by kevbite** [comment]
Thanks for the response @pranavkm 

I ended up injecting in `IOptions<ApiBehaviorOptions>` to my actions and using the factory directly, which keeps them uninformed.

I've documented it on my blog https://kevsoft.net/2020/02/09/adding-errors-to-model-state-and-returning-bad-request-within-asp-net-core-3-1.html

I just wanted to make sure I wasn't doing something completely stupid 👍.
