### ISSUE TITLE
[Blazor][Wasm] Disable built-in typescript target

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#18980]
After 679ed5d5caff4833515a82ffb73d9afecd979164 I started getting build errors due to the typescript SDK not being able to load one of the tasks.

Given that we don't use it and that the recommended way is to use the typescript package, I added the following property to disable the default logic 
`<EnableTypeScriptNuGetTarget>true</EnableTypeScriptNuGetTarget>` to bypass this issue.

**Comment by javiercn** [comment]
We can remove this once we get back into a stable train.

**Comment by mkArtakMSFT** [comment]
@javiercn what will happen if we keep this as is? If nothing, let's move this to either `Backlog` or even close it.

**Comment by mkArtakMSFT** [comment]
Ping @javiercn
