### ISSUE TITLE
No startup.cs in the WASM project

### ISSUE THREAD

**Issue by sowsan** [dotnet/aspnetcore#18989]
Is it expected to have a startup.cs file in the project root folder ? I am following the documentation here for vscode and its not creating one.

https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1

**Comment by MJRasicci** [comment]
See the Blazor WASM 3.2-preview 1 release blog post, specifically the Simplified Startup section:

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

**Comment by sowsan** [comment]
Thank you so much :)
