### ISSUE TITLE
Blazor code section: Dark Theme, C# code in Razor has annoying background colour

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18988]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/732605/blazor-code-section-dark-theme-c-code-in-razor-has.html)._

---
What steps will reproduce the problem?
1. Set Visual Studio to have DARK theme
2. Create a BLAZOR project, go to a RAJOR page and all the C# code has an annoying back-ground colour

What is the expected output? What do you see instead?

IMO: the slightly lighter background colour is probably useful in the HTML section where there's binding, e.g.
<td>@forecast. TemperatureC</td>
Here "@forecast. TemperatureC" has a lighter background colour.

However, it the background colour is annoying within the @code {...} section at the bottom of the page.

Please provide any additional information below.

---
#### Visual Studio Feedback System on 9/16/2019, 03:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/16/2019, 10:34 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/aspnetcore/issues/18990

**Comment by caseydierking** [comment]
Was this issue resolved? The colors in dark mode are truly terrible and unreadable.

**Comment by NTaylorMullen** [comment]
Hasn't been fixed, I marked it as duplicate and linked to the corresponding work item which is responsible for the actual fix (not yet done)
