### ISSUE TITLE
Remove @code, @functions, @{...} and @if, @for ...statements... background colorization

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#18990]
We'd remove the background of the opaque code that exists.

**Today:**
![image](https://user-images.githubusercontent.com/2008729/74372011-baa08c00-4d8e-11ea-98f8-0ce4cf2f81c2.png)

 For instance

```Razor
@{
    var x = 123;
}
```

All the C# would not have a background. However, in cases where expressions are mixed those would continue to have background colorizations. i.e. this would continue to look the same:

![image](https://user-images.githubusercontent.com/2008729/74372047-d441d380-4d8e-11ea-8e47-b3d51474d1ed.png)

**Comment by kevonh** [comment]
I agree that this is annoying.  It would be better even if only the section in the @code part was not highlighted.

**Comment by NTaylorMullen** [comment]
> I agree that this is annoying. It would be better even if only the section in the @code part was not highlighted.

With the latest LSP powered editor we're experimenting with what it's like to not have C# code background highlighting anywhere. If you'd like to try it out you can go to Tools -> Options -> Environment -> Preview Features -> Enable experimental Razor editor:
![image](https://user-images.githubusercontent.com/2008729/89328535-6510b200-d642-11ea-8c0e-cd8807f7832a.png)

It has several known gaps currently but it's something we're investing heavily in! [Blog post](https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/) for more info.

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen does this track removing it in the legacy editor? If not "no background" is already the default experience.

**Comment by NTaylorMullen** [comment]
I think this was encompassed by FCOP, we could probably close this out
