### ISSUE TITLE
Allow Razor parser to utilize C# formatting options

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#18996]
Related to https://github.com/dotnet/aspnetcore/issues/14271

Right now no matter how the editor is configured, the background C# document will always be generated with tabSize: 4 and InsertSpaces: true. We need flow editor customization through to the code generation to enable correct formatting behavior.

**Comment by ajaybhargavb** [comment]
@NTaylorMullen can we bring this forward into the next milestone? I already have a PR out and it shouldn't take very long.

**Comment by NTaylorMullen** [comment]
NOOOOOOOO

**Comment by ajaybhargavb** [comment]
Draft PR for future reference, https://github.com/dotnet/aspnetcore-tooling/pull/1606

**Comment by NTaylorMullen** [comment]
@allisonchou your changes fix this right?

**Comment by allisonchou** [comment]
@NTaylorMullen Yep, https://github.com/dotnet/aspnetcore/pull/31211 should fix.

**Comment by ajaybhargavb** [comment]
![image](https://user-images.githubusercontent.com/1579269/112879563-25d61c00-907e-11eb-87b9-881675bf824f.png)

Wow so rude @NTaylorMullen 😝
