### ISSUE TITLE
[Helix] Revisit how we declare/define/target the helix queues

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#18991]
@MattGal suggested that we consider moving to a flat list of helix queues similar to what the run-time repos do, like: https://github.com/dotnet/runtime/blob/4f97bc78f3e86af5351ed4e1e9c64a00a311cb5c/eng/pipelines/libraries/helix-queues-setup.yml#L21

The previous intent was to more have a strongly typed queue object which had properties, there's now complexity with internal/open and we also directly reference queue ids in the test sources.

So this will require some thought and discussion.

**Comment by dougbu** [comment]
Not sure of the advantage of this change. What's the advantage over the current `msbuild` approach❔

**Comment by HaoK** [comment]
I believe it helps with some of the Open/Internal weirdness we deal with mostly.  This is mostly so we would remember to have the discussion.  I agree, that things are reasonable with our current msbuild, I'm ok closing this

**Comment by HaoK** [comment]
But we can also use this issue to track/discuss any improvements around targeting sets of queues, i.e. skip all arm, all OSX, all alpine.  If we want to do anything there soon?

**Comment by dougbu** [comment]
:ok: let's discuss w/ managers on Thursday&hellip; Remind me 😺

**Comment by HaoK** [comment]
I'm out for next 1.5 weeks, but I can bring it up next time I'm at the sync if you haven't discussed it by then

**Comment by HaoK** [comment]
Closing since we discussed this last year and didn't settle on any improvements/changes we wanted to do in the short term
