### ISSUE TITLE
Update Grpc.AspNetCore version referenced by template

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#18994]
The Grpc.AspNetCore package referenced by the template is version 2.23.2. This was released Sep 20, 2019. Since then there have been many bug fixes, some of which are still being reported by users who have old versions of the package.

We should update Grpc.AspNetCore package in the template to 2.27.0.

Related: There is "Add Service Reference" tooling in VS that adds a reference to Grpc.Net.Client. We should also update its references. That is outside the scope of this repo.

// @shirhatti @anurse

**Comment by anurse** [comment]
Yep, let's get a PR open against `release/3.1` to update the template and we can submit it to shiproom.

**Comment by anurse** [comment]
This was fixed in https://github.com/dotnet/aspnetcore/pull/18995 which will be released in 3.1.3.

**Comment by jawn** [comment]
Should this be closed as 3.1.3 has been released?

**Comment by Pilchie** [comment]
Yes, closing.
