### ISSUE TITLE
Blazor data annotation validation does not call IValidationAttributeAdapterProvider.GetAttributeAdapter

### ISSUE THREAD

**Issue by TPIvan** [dotnet/aspnetcore#19001]
### Describe the bug
ASP.NET MVC includes [DataAnnotationsModelValidatorProvider](https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.dataannotationsmodelvalidatorprovider?view=aspnet-mvc-5.2) which allows access to instantiated validation attributes (for property injection).   An equivalent of this in core MVC seems to be [IValidationAttributeAdapterProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.dataannotations.ivalidationattributeadapterprovider?view=aspnetcore-3.1). When an implementation of the interface is created and registered the method [GetAttributeAdapter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.dataannotations.validationattributeadapterprovider.getattributeadapter?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.AspNetCore.Mvc.DataAnnotations.ValidationAttributeAdapterProvider.GetAttributeAdapter);k(DevLang-csharp)%26rd%3Dtrue&view=aspnetcore-3.1) is never called. While reading and stepping through [DataAnnotationsValidator ](https://source.dot.net/#Microsoft.AspNetCore.Components.Forms/DataAnnotationsValidator.cs,3098072f74d1da0d) I have not discovered any equivalent call.

### To Reproduce
Create the interface implementation

    public class MyAdapterProvider : ValidationAttributeAdapterProvider, IValidationAttributeAdapterProvider
        {
            public CustomValidationAttributeAdapterProvider() {}

         IAttributeAdapter IValidationAttributeAdapterProvider.GetAttributeAdapter(ValidationAttribute attribute,IStringLocalizer stringLocalizer)
           {    
            return base.GetAttributeAdapter(attribute, stringLocalizer);
           }
       }

register it 

    services.AddSingleton<IValidationAttributeAdapterProvider, CustomValidationAttributeAdapterProvider>();

`GetAttributeAdapter` is never called before or during a form validation

### Further technical details
- ASP.NET Core version
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Enterprise 2019
Version 16.4.3

### Note
There is a StactOwerflow question connected with the subject: [Data Annotations Property Injection for Blazor](https://stackoverflow.com/questions/60191407/data-annotations-property-injection-for-blazor)

**Comment by javiercn** [comment]
@TPIvan thanks for contacting us.

MVC data annotations don't apply to Blazor. We have an experimental package that might suit your needs, but I'm not sure it contains the functionality you are asking/looking for.

@pranavkm can you add more details here?

**Comment by pranavkm** [comment]
https://blog.stevensanderson.com/2019/09/04/blazor-fluentvalidation/ has an example of plugging an alternate validation system in to Blazor. Perhaps that help's here.
