### ISSUE TITLE
Blazor ItemPresenter 

### ISSUE THREAD

**Issue by GeraudFabien** [dotnet/aspnetcore#19005]
### Is your feature request related to a problem? Please describe.
I want to make a panelTemplate for my project. And for this i need an alternative to "ItemsPresenter".

### Describe the solution you'd like
I first fought to use RenderFragment<RenderFragment>.
Consumer
```
<ItemsControl>
   <ItemPanelTemplate>
      <div>
         @context
      </div>
   </ItemPanelTemplate>
</ItemsControl>
```

While the control look like
```
@typeparam TItem

@ItemPanelTemplate()


@* Templates *@

@template ItemDisplayTemplate{
   @foreach(var item in Items){
      @ItemTemplate(item);
   }
}


@* Code *@

@code {

   [Parameter]
   public IEnumerable<TItem> Items { get; set; }

   [Parameter]
   public RenderFragment<RenderFragment> ItemPanelTemplate { get; set; }

   [Parameter]
   public RenderFragment<TItem> ItemTemplate { get; set; }

}
```

Or maybe cleaner 

```
@typeparam TItem

<ItemPanelTemplate>
   @foreach(var item in context){
      @ItemTemplate(item);
   }
</ItemPanelTemplate>

@code {

   [Parameter]
   public IEnumerable<TItem> Items { get; set; }

   [Parameter]
   public RenderFragment<RenderFragment> ItemPanelTemplate { get; set; }

   [Parameter]
   public RenderFragment<TItem> ItemTemplate { get; set; }

}
```

### Additional context
I was wondering if #8364 is the same.
I need Layout feature for component.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GeraudFabien.
We're having hard time interpreting your question. Is this really your question:

> I need Layout feature for component.

**Comment by GeraudFabien** [comment]
> I need Layout feature for component. 

Thas was a summary of the feature. Another pov of it.

**Comment by javiercn** [comment]
@GeraudFabien I think what you are looking for is just templated components. See https://docs.microsoft.com/en-us/aspnet/core/blazor/templated-components?view=aspnetcore-3.1

If you are asking for a built-in component it is unlikely we will build that into the framework, but it is trivial for you to build your own and re-use across your projects if you want to.

**Comment by GeraudFabien** [comment]
@javiercn  No it's not what i'm looking for. 

If you look at my exemple the Templated component context is a renderFragment. I just look  to put a render fragment inside a renderFragment. Exactly the same as in Xaml where you can use  Item presenter and the render is define by the component.

**Comment by GeraudFabien** [comment]
> I was wondering if #8364 is the same.

I re-read it again. And the two thread are finally duplicate. Sorry.
