### ISSUE TITLE
SignalR: Cannot send messages to user(s)

### ISSUE THREAD

**Issue by saciervo** [dotnet/aspnetcore#19000]
I have SignalR working and can send messages to all, or to specific clients, but unfortunately **NOT** to users. 

### To Reproduce
I created a [repo to reproduce](https://github.com/saciervo/Try.SignalRUsersPubSub) the problem.

Basically I auth users on the SignalR hub with JWT and placed a button that, when clicked, starts a long running job. For the example I hard-coded a user called "johnny".

```js
var connection = new signalR.HubConnectionBuilder()
    .withUrl("/hub",
        {
            accessTokenFactory: function () {
                // JWT => unique_name: "johnny", valid until Apr 09, 2023
                return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpvaG5ueSIsIm5iZiI6MTU4MTA3MTUxNCwiZXhwIjoxNTgxNjc2MzE0LCJpYXQiOjE2ODEwNzE1MTR9.7K6zl8a0uxpN2i2paxwuVsMRtSaKFgoJHpi_r2TzXx4";
            }
        })
    .build();

connection.on("jobCompleted",
    function (jobId) {
        $("#pnl-alerts").append('<div class="alert alert-secondary" role="alert">Congrats! Task completed (Job:' + jobId + ')</div >');
    });

connection.start()
    .catch(function (err) {
        return console.error(err.toString());
    });

$(function () {
    $("#btn-start-job").click(function () {
        $.post("/home/startjob");
    });
})
```

The hub itself has no methods and is only used for the connection. Messages will be sent via injected `HubContext`:
```csharp
[Authorize]
public class NotificationsHub : Hub
{
}
```

The controller action that is called via Ajax POST:
```csharp
[HttpPost]
public IActionResult StartJob()
{
    Task.Factory.StartNew(DoLongRunningWork);
    return Ok("started");
}

private void DoLongRunningWork()
{
    // Simulate hard work
    Thread.Sleep(TimeSpan.FromSeconds(3));

    // Notify clients that the job has been completed.
    hubContext.Clients.User("johnny").SendAsync("jobCompleted", Guid.NewGuid().ToString("N"));
}
```
So the idea is for the controller action to start a task to do some hard working in the background and the immediately returning `200`. As soon as the task in the background has been completed it sends a message to johnny with the ID of the completed job.

But somehow, the message never arrives. Even though the connection is alive and also "johnny" is authenticated:

![image](https://user-images.githubusercontent.com/707898/74421973-25fd6300-4e4e-11ea-8e7c-dc9fc1d67886.png)

It's hard to imagine that it's really a bug but something is missing or I don't use it how the feature was intended... because if I map the users to clients manually, by saving each client of a user to memory in `OnConnectedAsync()` and then read it back from memory when sending the message through the hub context.

### Further technical details
- ASP.NET Core 3.1
- Visual Studio Professional 2019 (16.4.3)

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
```

**Comment by BrennanConroy** [comment]
It looks like you're trying to use the `ClaimsType.Name` value, but SignalR uses `ClaimsType.NameIdentifier` by default. You can see how to replace that default in the docs https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#use-claims-to-customize-identity-handling

**Comment by saciervo** [comment]
Perfect thanks! That was just about as subtle as I expected... especially because the principal looks absolutely fine when debugging.
