### ISSUE TITLE
Blazor Question: ConfigureAwait(false) in Server-Side Blazor?

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#19004]
Read this article recently regarding when to use ConfigureAwait(false) (see https://devblogs.microsoft.com/dotnet/configureawait-faq/) and wondered how it applies to server-side Blazor. If, for example, Blazor components are considered application code that, in most cases, have access to a Main UI thread would **not** using ConfigureAwait(false) apply as the article seems to indicate? Also I do have in our project Blazor component libraries that make calls to service library methods and we are getting fx cop warnings that those calls might want, for example, to implement ConfigureAwait(false) but since it is a component I am just not exactly sure what effect it may have, running an await-able service call within the component. 

Going to do some testing but just wanted to ask if anyone had in general guidance on this or could point us in a direction. Thanks!

**Comment by SteveSandersonMS** [comment]
>  If, for example, Blazor components are considered application code that, in most cases, have access to a Main UI thread would not using ConfigureAwait(false) apply as the article seems to indicate?

Yes, Blazor Server is a UI framework which requires your code to run on its sync context. Therefore do *not* use `ConfigureAwait(false)` within your Blazor component code.

Thanks for checking!

**Comment by chassq** [comment]
Thank you!
