### ISSUE TITLE
[Blazor page] Getting an exception when using a dash in page route parameters

### ISSUE THREAD

**Issue by vcrobe** [dotnet/aspnetcore#19014]
### Describe the bug
I get an exception when using a dash in page route parameters like this:

> /edit/5-3

I'm using Blazor-server.

### To Reproduce

```
@page "/Edit"
@page "/Edit/{Year:int}-{Number:int}"

<p>@Year @Number</p>

@code
{
	[Parameter]
	public int Year {get;set;}

	[Parameter]
	public int Number {get;set;}
}
```

**Exception**

InvalidOperationException: Invalid template 'Edit/{Year:int}-{Number:int}'. The character '}' in parameter segment '{Year:int}-{Number:int}' is not allowed.

Microsoft.AspNetCore.Components.Routing.TemplateParser.ParseTemplate(string template).

### Further technical details

**dotnet --info**
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version**

IDE: VS Code 
Version: 1.41.1

**Comment by javiercn** [comment]
@vcrobe thanks for contacting us.

Blazor routing doesn't support that type of parameter (we call them complex parameters in ASP.NET Core) as an alternative we suggest you capture the parameter and match the value against the pattern you expect.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
