### ISSUE TITLE
SignalR Remove user's all groups.

### ISSUE THREAD

**Issue by Caskia** [dotnet/aspnetcore#19043]
### Describe the solution you'd like
When a user disconnect, we need to call ``hubContext.Groups.RemoveFromGroupAsync(connectionId, groupName)`` manually. So I need to maintain a user online groups map. Can you guys provide a native way to remove user's groups in ``IGroupManager`` .

### Additional context
May be api like this:
``
Task RemoveConnectionAsync(string connectionId, out List<string> groupNames)
``

**Comment by BrennanConroy** [comment]
The connection should be removed automatically from all groups on disconnect. What behavior are you seeing that makes you think they are still in the group?

**Comment by Caskia** [comment]
Thank you @BrennanConroy , it's my hypothesis, no experiments have been done yet. I will have a try right now and feedback.
