### ISSUE TITLE
Dependencies are out of date in master

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#19040]
Both the runtime and blazor dependencies are about 10 days out of date in master. This issue is being filed as a result of our agreed-upon SLA and escalation path of 7 days (max).

![image](https://user-images.githubusercontent.com/54385/74492840-0fbec980-4e85-11ea-8bec-15dba3ff271e.png)

Runtime reports the oldest unconsumed commit as "(unknown)", but the build was produced late on February 3rd, so 10 days out of date should be the upper bound for that. @BrennanConroy What do you think about using the build date for reporting out-of-dateness when the oldest unconsumed commit cannot be found for whatever reason?

**Comment by BrennanConroy** [comment]
It only reports unknown if we are over 250 commits behind, and at that point it doesn't really matter how many days behind we are, because we should be looking into getting updated.

**Comment by halter73** [comment]
I was about to send an org wide email as recommend by the build ops rotation instructions, but it looks like we just too a runtime update in extensions 4 hours ago and it's working through the system. @JunTaoLuo thinks it should turn blue since https://github.com/dotnet/aspnetcore/pull/19035 was merged now.

As for blazor, that hasn't had a commit for 10 days until an hour ago, so I'm going to close this issue.
