### ISSUE TITLE
[Blazor] Passing Parameter to Custom Layout

### ISSUE THREAD

**Issue by NavinAT** [dotnet/aspnetcore#19049]
###  **How to pass parameter to Custom Layout?**
While clicking a `NavLink `the Custom Layout will be rendered inside the '`MainLayout`'.

In **'`MainLayout`'** we have added a 'Custom Layout' as nested one and we want to pass a parameter to the Custom Layout from `MainLayout`

**Comment by javiercn** [comment]
@NavinAT thanks for contacting us.

I'm not sure what you are trying to accomplish, but it is likely you can use a cascading parameter to achieve what you want. Declare a cascading parameter in the component containing the other component and give it a value, the nested component should be able to access it, and if it's the other way around, do the same thing, but pass down a callback that the nested component can call to notify the enclosing component of the value.

**Comment by NavinAT** [comment]
@javiercn Thanks for the response.
The way you mentioned worked as expected, but what we are trying is,

**CustomLayout:**
```
@layout MSLayout
@inherits LayoutComponentBase

<section id="Content-nested">
    <div>
        @Body
    </div>
</section>
```
Here, we are specifying MSLayout (MainLayout) for the CustomLayout, in this case how do we pass parameter or some value to the custom one from MSLayout.
