### ISSUE TITLE
[Blazor] Use nameof() when setting component parameters

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#19048]
If you rename a parameter property on ChildComponent, it is possible to build and run an app where ParentComponent still tries to set the old parameter and causes a runtime error.

It would obviously be better if these were caught at compile time.

Not sure how my suggestion will work when there is a parameter to capture unmatched parameters, but could the generated view code use `nameof(ChildComponent.PropertyName)` when setting element attributes that start with an uppercase character, so that this scenario is caught at compile time?

**Comment by simonziegler** [comment]
I've bumped into this a few times and have learned to be careful.

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

We'll look into this and get back to you.

**Comment by mkArtakMSFT** [comment]
This will be supported by tooling in the future, when we will have proper renaming supported.
