### ISSUE TITLE
Razor Components - render-mode affecting lists of derived classes

### ISSUE THREAD

**Issue by scrollsaw** [dotnet/aspnetcore#19056]
I've got a Razor Component i'm dropping onto a Razor page like so:

```
<component type="typeof(ElementProductComponent)"
render-mode="Server"
param-elementList="Model.elementList" />
```

I'm passing a list (elementList) into the component as a parameter.

The list is declared in the razor page code behind as

```
 [BindProperty]    
public List<ElementModel> elementList { get; set; }
```

ElementModel is a base class. The list will normally contain items of various types derived from the base class (ElementTextModel, ElementDateModel, etc)

In the codebind for the razor page the list is populated like this:
```

 public async Task<IActionResult> OnGet(string id)
    {
        elementList = GetList();

        return Page();
    }
    public static List<ElementModel> GetList()
    {
        var elements = new List<ElementModel>();

        elements.Add(new ElementTextModel { Name = "TestTextName", Value = "hello world" });
        elements.Add(new ElementDateModel { Name = "TestDateName", Value = "20200101" });

        return elements;

    }

```
The models look like this:
```

public class ElementModel
{

    [Required] 
    public string Name { get; set; }


    [Required] 
    public virtual ElementType Type { get; }
}

```
```

 public class ElementTextModel : ElementModel
{

    [Required]
    public string Value { get; set; }

    public Hashtable Attributes { get; set; }

    [Required]
    public override ElementType Type { get { return ElementType.TEXT; } }
}
```
Then in my component, I want to iterate over the list and display different html, child components based on the type of each item in the list. I can do that that with a switch or if. Here is a simplified version of the code where I'm just trying to display the type I see.
```

    <div>
    Elements:
    <ul>
        @for (var i = 0; i < elementList.Count; i++)
        {
        <li>       
                <div>@elementList[i].Type</div>
                <div>@elementList[i].Name</div>

        </li>

        }
    </ul>
</div>
@code {

    [Parameter]
    public List<ElementModel> elementList { get; set; }

}
```

The issue I'm seeing is that when I declare the component like
```

<component type="typeof(ElementProductComponent)"
render-mode="Server"
param-elementList="Model.elementList" />
```

with the render-mode set to Server, the code in the component sees the items in the elementList as of type ElementModel, regardless of how they were declared. This isn't correct.

if I do this:
```

<component type="typeof(ElementProductComponent)"
render-mode="Static"
param-elementList="Model.elementList" />
```

and set the render-mode to Static, the component sees the list correctly, as a mixed list of items of types derived from the base class.

If I do
```
<component type="typeof(ElementProductComponent)"
render-mode="ServerPrerendered"
param-elementList="Model.elementList" />
```

It will render the page twice, once where it sees the elements as the derived classes, and then it'll render again and see the elements as the base classes. 

Is this a bug with render-mode Server and ServerPrerendered? Or is there some configuration issue at play?

```

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Visual Studio Pro 2019 - 16.4.5.

**Comment by javiercn** [comment]
@scrollsaw thanks for contacting us.

This is by design, the deserialization happens based on the compile time type of the parameter, not on the actual parameter type, so there is going to be information loss if you rely on polymorphism to pass parameters to the component.

This behavior is not specific to Blazor but a behavior of the serializer. You are free to implement your own custom converter to serialize and deserialize data as you see fit, but our recommendation is that you avoid inheritance all-together in these scenarios and instead you pass down a set of DTOs or a reference to the data that can be retrieved later.

**Comment by scrollsaw** [comment]
Will there be a fix to this at any point? Or at least a work around? Not supporting polymorphism seems strange to me. 

Maybe I'm trying to use razor components in a way they weren't intended. The end goal was to take my primary data model (basically a tree-like structure -> lists of elements of various types, some of which contain lists of various types themselves) and create controls and html dynamically based on the type. Small lightweight components that only need to know how to handle the one element type (which would be passed in by its parent element on creation) seemed like the way to go. 

And this does work perfectly well when render-mode is set to static. My concern is that by setting it to static I won't be able to have any interactivity ( I think? The docs aren't exactly clear on that point and I'm not sure how out of date they are).

Do you have an example of what you mean by "a set of DTOs or a reference to the data"?

**Comment by mrpmorris** [comment]
@scrollsaw The accepted answer here is very good - https://stackoverflow.com/questions/58074304/is-polymorphic-deserialization-possible-in-system-text-json

**Comment by javiercn** [comment]
@scrollsaw I don't think so, Polymorphism is an OO concept which doesn't apply to serialized data, the best approach you can follow is to create a new type that is a union of the polymorphic type and serialize that as mentioned in the [docs](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#support-polymorphic-deserialization)

This behavior is by design as we don't try to change the default behaviors of the underlying JSON serializer used to serialize the parameters.

**Comment by scrollsaw** [comment]
Thanks for you help. Writing a custom serializer/deserializer seems like a giant pain, but probably the only option. 

While this makes sense to me now, I should note that none of this is made clear to developers up front. There is a bunch of assumed knowledge here that can cause confusion if you don't know it: that  render-mode = Server will use JSON to pass the data around AND then that the JSON converter doesn't support polymorphism out of the box.  

I get that polymorphism is an OO concept which doesn't apply to serialized data, but when you are working in an OO language like C#/.net core and aren't directly working with serialized data, it's confusing to run into serialization problems that occur "under the hood".

Maybe just something for the docs.

Thanks again, appreciate it.
