### ISSUE TITLE
[Blazor][Wasm] Investigate alternatives to loading the blazor app when inside a hidden iframe

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#19053]

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/18851#discussion_r379359028

**Comment by mkArtakMSFT** [comment]
More context: This is to enable silent re-auth when necessary

**Comment by javiercn** [comment]
This already works, its about not loading the entire Blazor app inside a hidden iframe for a faster response and better resource usage.

I already have an idea on how to achieve this and it should be a trivial change

**Comment by javiercn** [comment]
Closing since I did this as part of the auth improvements
