### ISSUE TITLE
[Blazor] Binding data without using any event (onChange, onInput ...)

### ISSUE THREAD

**Issue by jayachaMS** [dotnet/aspnetcore#19055]
### **How to bind data without using any event (onChange, onInput ...)**
We have to update data to the Model in an action (like save). 
**Our idea**: Do not want to make server call often for every time the "focus looses" from the HTML element. Finally we want update the value while Submit.

```
<div>
    <label>Name</label>
    <input type="text" value="@student.Name" />
    <br />
    <label>Age</label>
    <input type="text" value="@student.Age" />
    <br />
    <input type="submit" @onclick="Save" />
</div>

@code {
    Student student = new Student();

    private void Save()
    {
        // At this stage - the value should be updated in the model.
    }
}
```

**Comment by javiercn** [comment]
@jayachaMS thanks for contacting us.

There's no way to achieve that with bind. The best you can do is to capture an element reference to the different input elements, and in your Save action, issue multiple JS interop calls to capture the current element values and then update the model with those.

But I would just recommend using bind unless you have perf-data that shows it has a high impact in your application performance.
