### ISSUE TITLE
[Blazor][Wasm] Investigate moving auth types to use enums instead of strings

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#19054]
They currently blow up with a null-reference exception inside STJ

**Comment by mkArtakMSFT** [comment]
Closing before we find we actually need this. Not much value-add it seems.

**Comment by javiercn** [comment]
@mkArtakMSFT This is a follow-up issue of some of the auth work. It's a cleanup that takes 30min-ish and will be bundled with other cleanups.
