### ISSUE TITLE
value of input field is changed in inspector but the value is not changed in chrome browser window

### ISSUE THREAD

**Issue by NareshBisht** [dotnet/aspnetcore#19057]
The problem is that when i'm pressing back button in chrome the value of input field is changed in inspector but the value is not changed in browser window. This does not happen in edge i dont know why.

here you can see that the value in inspector and browser are different.
![Untitled](https://user-images.githubusercontent.com/48261653/74539877-cfcf1380-4f64-11ea-8c56-58a98ba8e746.png)
here is the code :- 
![Screenshot (99)](https://user-images.githubusercontent.com/48261653/74539892-d9f11200-4f64-11ea-88a5-f12ac4c924ec.png)
![Screenshot (100)](https://user-images.githubusercontent.com/48261653/74539897-db223f00-4f64-11ea-8b4c-6f7b052d259c.png)

**Comment by javiercn** [comment]
@NareshBisht thanks for contacting us.

We don't think that this behavior is specific to ASP.NET Core in any way. Is the server producing the wrong markup?

**Comment by NareshBisht** [comment]
@javiercn Hi,
This issue sure is related to asp.net core as this is not working in chrome and opera (other browser i have not tested). The code which i wrote is not by any mean wrong.

**Comment by javiercn** [comment]
@NareshBisht Can you provide a minimal repro project so that we can better understand the issue? Network traces of before and after will also help.

**Comment by NareshBisht** [comment]
@javiercn sry for the wait but below is the link to the video on youtube you can see that the program is working fine in edge but not in chrome and opera.

video - https://youtu.be/zRPRMa4f_hk
project file - https://drive.google.com/file/d/13Q7gxc-fvzkvftk769Qy51u60_Pxd4IU/view?usp=sharing

**Comment by NareshBisht** [comment]
@javiercn can i get any update on this? we completely stuck with this now hope you can guide us what should we do? Should we switch to some other framework?

**Comment by NareshBisht** [comment]
ok its nots a problem with asp.net core
