### ISSUE TITLE
[Blazor][Wasm] Startup api for mapping blazor files

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#19060]
This is a follow-up issue about the work we are doing to host blazor apps inside asp.net core.

**Comment by mkArtakMSFT** [comment]
@javiercn is this still relevant? If not, simply close it.

**Comment by javiercn** [comment]
@mkArtakMSFT Still relevant, this is about `MapBlazorFiles()`

**Comment by SteveSandersonMS** [comment]
@javiercn This is done as `UseBlazorFrameworkFiles` now, isn't it? If not, could you edit the issue description to clarify what remains to be done?

**Comment by mkArtakMSFT** [comment]
@javiercn can you please clarify what is the pending work here? Just add the description please.

**Comment by mkArtakMSFT** [comment]
@javiercn closing this as it's not clear what's the leftover work here. If there is, feel free to reopen and bring up for discussion.
