### ISSUE TITLE
Custom ModelBinder doesn't fire on Type type

### ISSUE THREAD

**Issue by lhrbu** [dotnet/aspnetcore#19085]
I wrote an custom model binder which just simply read the string value from http request header and map it to Type type as below:
`public async Task BindModelAsync(ModelBindingContext bindingContext)`
`{`
`string key;`
`if (!string.IsNullOrEmpty(bindingContext.ModelName)) { key = bindingContext.ModelName; `
`else { key = bindingContext.FieldName; }`
`if (bindingContext.HttpContext.Request.Headers.TryGetValue(key, out var valueLine))`
`{`
`await Task.Yield();`
`bindingContext.Model = Type.GetType(valueLine.First());`
`bindingContext.Result = ModelBindingResult.Success(bindingContext.Model);`
`}`
`else { bindingContext.Result = ModelBindingResult.Failed(); }`
`}`

The problem is that it doesn't fire at all in the controller, I make a breakpoint in the BindModelAsync method and find that the method is just been skipped leaving the arg below entityType be null during request:
`public async ValueTask<int> AddEntityAsync(`
`[FromHeader][ModelBinder(BinderType =typeof(TypeHeaderModelBinder))]Type entityType`
'...'

And what get things intertesting is that if I change the Type of arg entityType in controller from "Type" to "object" then the Modelbinder fires, and I don't know why.
`public async ValueTask<int> AddEntityAsync(`
`[FromHeader][ModelBinder(BinderType =typeof(TypeHeaderModelBinder))]object entityType,`
'...'

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The framework disallow binding to type `Type`. This is by-design.
If you strongly believe this is the right thing to do for your scenario, there's an option you can use to suppress this behavior. Look at: https://github.com/dotnet/aspnetcore/blob/2e4274cb67c049055e321c18cc9e64562da52dcf/src/Mvc/Mvc.Core/src/Infrastructure/MvcCoreMvcOptionsSetup.cs#L121
