### ISSUE TITLE
Automatically import static files from Razor Class Libraries to the html file of client-side Blazor

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#19088]
### Is your feature request related to a problem? Please describe.
This is work well at 3.1.0-preview1 with EmbeddedResource.

I don't think developers need to care about static resources in other libraries.

**Comment by javiercn** [comment]
@ElderJames thanks for contacting us.

We don't plan to have this feature for reasons mentioned in https://github.com/dotnet/aspnetcore/issues/14911#issuecomment-541017878

This is something that works in very simple cases but that falls apart really quickly in most common cases and that leaves you without options.
