### ISSUE TITLE
Can't serialize enums as string in Blazor

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/aspnetcore#19086]
### Describe the bug
Trying to serialize and object containing an enum with the Attribute `[JsonConverter(typeof(JsonStringEnumConverter))]` will crash. 
Removing the attribute lets me easily send a poco with the enum, which gets serialized to a number as usual. 

### To Reproduce
Simply use the blazorwasm hosted template, add the following file to it:
```
using System.Text.Json.Serialization;

namespace BlazorApp3.Shared
{
	public class Poco
	{
		public string Name { get; set; }
		public int Age { get; set; }
		public MyEnum Number { get; set; }
	}

	[JsonConverter(typeof(JsonStringEnumConverter))]
	public enum MyEnum
	{
		One,
		Two,
		Three
	}
}
```
Also install System.Text.Json to the .Shared project.
Extend the WeatherForecastController with this method:
```
[HttpPost]
public Poco Post(Poco p)
{
	return p;
}
```
Put this at the top of the FetchData.razor for easy demo:
```
<button @onclick="GetPoco" >GetPoco</button>
<text>@resultString</text>
```
And this in the code block:
```
private string resultString = "";
private async Task GetPoco()
{
    var poco = new Poco()
    {
        Age = 3,
        Name = "User",
        Number = MyEnum.Three
    };
    var result = await Http.PostJsonAsync<Poco>("WeatherForecast", poco);
    resultString = $"Result:\r\nName: {result.Name}\r\nAge: {result.Age}\r\nNumber: {result.Number}";
}
```
Start it up and press the button.
### Further technical details
- ASP.NET Core version: 3.1, blazor 3.2 prev1
- dotnet version: 3.1.101
- Visual Studio Community 2019 Version 16.4.5

**Comment by javiercn** [comment]
@Regenhardt thanks for contacting us.

I actually got a repro of this myself as part of a separate piece of work, so this is likely confirmation that there is something wrong in this area.

@pranavkm I believe we need to investigate what goes on here with the json serializer as from my repro it null-ref.

@Regenhardt are you seeing a nullref in the callstack?

**Comment by Regenhardt** [comment]
Yes, the outermost message is a null-ref. Can upload a screenshot of the whole thing later when I'm at home if you like.

**Comment by javiercn** [comment]
@pranavkm This seems to be an actual issue, can you follow up with the right folks?

**Comment by Regenhardt** [comment]
I'm home, here's the screenshot.

![JsonStringEnumException](https://user-images.githubusercontent.com/10476293/74681651-3ef67300-51c4-11ea-9dcc-a43e15dbbc9a.png)

**Comment by Regenhardt** [comment]
Also [this](https://github.com/dotnet/runtime/blob/03dc181bfbb964a6afdb41f7965c2c013b0bdf3e/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L217) might just hide the error. Not sure how though, haven't actually cloned the repo. Good luck ✌️

**Comment by mrpmorris** [comment]
I had to switch to Newtonsoft to get around this

```
	internal class ApiService : IApiService
	{
		private static readonly JsonSerializerSettings JsonSerializerSettings;

		static ApiService()
		{
			JsonSerializerSettings = new JsonSerializerSettings
			{
				MissingMemberHandling = MissingMemberHandling.Ignore,
				NullValueHandling = NullValueHandling.Ignore,
				Formatting = Formatting.None
			};
			var enumConverter = new StringEnumConverter(
				namingStrategy: new CamelCaseNamingStrategy(),
				allowIntegerValues: true);
			JsonSerializerSettings.Converters.Add(enumConverter);
		}

		private async Task<TResponse> PostJsonAsync<TResponse>(
			HttpClient httpClient,
			string url,
			object content)
		{
			string requestJson = JsonConvert.SerializeObject(content, ApiService.JsonSerializerSettings);
			var request = new HttpRequestMessage(HttpMethod.Post, url)
			{
				Content = new StringContent(requestJson, Encoding.UTF8, "application/json")
			};
			HttpResponseMessage httpResponseMessage = await httpClient.SendAsync(request);
			httpResponseMessage.EnsureSuccessStatusCode();
			string responseJson = await httpResponseMessage.Content.ReadAsStringAsync();
			TResponse result = 
				JsonConvert.DeserializeObject<TResponse>(responseJson, ApiService.JsonSerializerSettings);
			return result;
		}
}
```

**Comment by WarrenCrabb** [comment]
Using a custom JsonConverter also works if you don't want to switch to Newtonsoft for one enum conversion.

```
    internal class EnumStringConverter : JsonConverter<CacheLocation>
    {
        public override CacheLocation Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) 
            => (CacheLocation)Enum.Parse(typeof(CacheLocation), reader.GetString());

        public override void Write(Utf8JsonWriter writer, CacheLocation value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString());
    }
```

**Comment by pranavkm** [comment]
This looks like an issue with the linker. It seems to be stripping out some types that are required for the built-in converter to succeed. Turning off the linker or configuring the app to use a [linker configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#control-linking-with-a-configuration-file) make it work correctly. I was able to fix this by adding telling the linker to preserve all types in `System.Text.Json`:

```xml
  <assembly fullname="System.Text.Json">
    <type fullname="*" required="true" />
  </assembly>
```

Publishing an .NET Core app with the linker enabled `PublishTrimmed=true` works fine with the exact same code. Perhaps one of Blazor's linker settings is the culprit here.

Here are linker options produced by the .NET SDK and the ones from Blazor (skipping all the assemblies):

```
// Blazor
-l none --disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com -v false -c link -u link -b true

// .NET SDK
-c copyused -u copyused -l none --skip-unresolved true 
```

@marek-safar \ @lewing suggestions on how to proceed? (FYI @SteveSandersonMS )

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/20446

**Comment by SteveSandersonMS** [comment]
BTW thanks very much @Regenhardt for the report and repro steps.

The way you wrote up the minimal instructions for recreating the problem, rather than linking to an entire repo, is perfect and the way I wish all bug reports were done. This made it so much easier to understand and fix. Great job!
