### ISSUE TITLE
SignalR ws bufferutil utf-8-validate

### ISSUE THREAD

**Issue by Exocomp** [dotnet/aspnetcore#19089]
Angular: 9.0.1
@microsoft/signalr: 3.0.0

I get the following warnings when I build for prod:

```
WARNING in ./node_modules/ws/lib/buffer-util.js
Module not found: Error: Can't resolve 'bufferutil' in 'R:\phoenix\src\phoenix-angular-web\node_modules\ws\lib'
 @ ./node_modules/ws/lib/buffer-util.js
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
 @ ./dist/server/main.js
 @ ./server.ts

WARNING in ./node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in 'R:\phoenix\src\phoenix-angular-web\node_modules\ws\lib'
 @ ./node_modules/ws/lib/validation.js
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
 @ ./dist/server/main.js
 @ ./server.ts
```

I see that @microsoft/signalr has a dependency on ws and in the ws readme I see:

https://github.com/websockets/ws

"Opt-in for performance and spec compliance
There are 2 optional modules that can be installed along side with the ws module. These modules are binary addons which improve certain operations. Prebuilt binaries are available for the most popular platforms so you don't necessarily need to have a C++ compiler installed on your machine.

npm install --save-optional bufferutil: Allows to efficiently perform operations such as masking and unmasking the data payload of the WebSocket frames.
npm install --save-optional utf-8-validate: Allows to efficiently check if a message contains valid UTF-8 as required by the spec."

**My question**:

- Will SignalR benefit from bufferutil/utf-8-validate in any way? 
- Is there better way to handle this with the @microsoft/signalr package so that it doesn't throw these warnings?

**Comment by BrennanConroy** [comment]
I can't reproduce the warnings. But it looks like maybe the `ws` package [has a fix now](https://github.com/websockets/ws/pull/1626). You could try referencing version 7.2.1 explicitly and see if that resolves the warning.

**Comment by Exocomp** [comment]
I can't reproduce it anymore, closing.
