### ISSUE TITLE
Review pubternal APIs in ResourceManagerStringLocalizer

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#19081]
This type was migrated from dotnet/extensions and contains two instances of pubternal APIs in public methods as mentioned in https://github.com/dotnet/aspnetcore/pull/19033#discussion_r379186075. Need to review this API and what to do with the pubternal types.

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo is the intention to get these reviewed during the API Review meeting?

**Comment by dougbu** [comment]
@mkArtakMSFT yes. I mentioned API Review in https://github.com/dotnet/aspnetcore/pull/19033#discussion_r379683510

**Comment by mkArtakMSFT** [comment]
> @mkArtakMSFT yes. I mentioned API Review in [#19033 (comment)](https://github.com/dotnet/aspnetcore/pull/19033#discussion_r379683510)

I see. Well, the process is to create the proposed change as a PR and apply the `api-ready-for-review` label to it. That way it'll show up in the review meeting.

**Comment by dougbu** [comment]
@JunTaoLuo and I are recommending the pub-ternal pattern (something our org has worked to eradicate) be removed where @JunTaoLuo noticed it. We don't have the domain knowledge you and @ryanbrandenburg have to decide whether the pub-ternal APIs should be `public`, `internal`, or (in an exceptional case) should remain pub-ternal.

**Comment by mkArtakMSFT** [comment]
Got it. Thanks for clarifying. Will do the needful!

**Comment by mkArtakMSFT** [comment]
This is going to be addressed as part of https://github.com/dotnet/aspnetcore/pull/22290
