### ISSUE TITLE
[Blazor] Passing Parameter to Custom Layout

### ISSUE THREAD

**Issue by NavinAT** [dotnet/aspnetcore#19090]
Closed Issue:  (https://github.com/dotnet/aspnetcore/issues/19049#event-3039292943)
#
### How to pass parameter to Custom Layout?

**CustomLayout:**

```
@layout MSLayout
@inherits LayoutComponentBase

<section id="Content-nested">
    <div>
        @Body
    </div>
</section>
```
Here, we are specifying `MSLayout `(`MainLayout`) as a root for the `CustomLayout`, in this case how do we pass parameter or some value to the custom one from `MSLayout`.

`CustomLayout `will be used in another component:

```
@layout CustomLayout
@page "/NestedComponent"

<h1>This component is in 'Nested layout!!!'</h1>
```

**Comment by javiercn** [comment]
@NavinAT thanks for contacting us.

Layouts only allow to pass parameters down. You could pass down a callback and have your child layout invoke that or you can avoid using layouts in this case and use a component instead that takes a child content and pass any parameter you want.

**Comment by NavinAT** [comment]
@javiercn Thank you for the suggestions.
