### ISSUE TITLE
 webassembly(client) crashing #Blazor

### ISSUE THREAD

**Issue by giorgi-abashidze** [dotnet/aspnetcore#19095]
hi, my pc have low ram and it freezing often, it freezed when i was working in visual studio and i turned off and on again unplugged from power,

after that when i start application webassemply(client) is crashing error is in dotnet.js

i tried everything including cleaning solution and rebuild again but still got an error

here is a part of error message: Stacktrace: 
dotnet.js:1:18935
650764@https://localhost:44359/_framework/wasm/dotnet.js:1:18917
_emscripten_asm_const_iii@https://localhost:44359/_framework/wasm/dotnet.js:1:19466

and also: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.

my index.html file is: `<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>TestApp</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="_content/Radzen.Blazor/css/default.css" />
    <link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />
</head>

<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script> 
    <script src="_content/Radzen.Blazor/Radzen.Blazor.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>

    <script>

        function ShowProductForm() {
            var form = document.getElementById("product-form");

            form.style = "display:block;"
        }

        function HideProductForm() {
            var form = document.getElementById("product-form");

            form.style = "display:none;"
        }

       function RenderChart(data) {

            options = {
                series: [
                    JSON.parse(data)

                ],
                chart: {
                    height: 350,
                    width: 700,
                    type: 'heatmap',
                },
                dataLabels: {
                    enabled: false
                },
                colors: ["#008FFB"],
                title: {
                    text: 'Data of last 7 days'
                }
                
            };

            var chart = new ApexCharts(document.querySelector("#chart"), options);
            chart.render();
        }

    </script>
</body>

</html>
`

need help asap

**Comment by javiercn** [comment]
@giorgi-abashidze thanks for contacting us.

Can you delete your bin, and obj folders and see if that fixes the issue. If not, can you provide a minimal repro project so that we can investigate.
