### ISSUE TITLE
[Blazor] Incorrect DOM namespace used with children of SVG foreignObject

### ISSUE THREAD

**Issue by akorchev** [dotnet/aspnetcore#19092]
### Describe the bug

Blazor seems to always use the SVG namespace when updating DOM nodes that are children of a SVG element.

### To Reproduce

Use this Blazor page

```
<svg width="100" height="100">
    <foreignObject x="0" y="0" width="100" height="100">
        <strong>foo</strong>
        <strong>@foo</strong>
    </foreignObject>
</svg>

@code {
    string foo = "foo";
}
```

When you render it the second `<strong>` disappears immediately.

![blazor-foreignObject](https://user-images.githubusercontent.com/454726/74638259-3fffb400-5174-11ea-810a-477ede6d6aa8.gif)

The DOM node is still there though:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/454726/74638306-59086500-5174-11ea-8840-f2179dba09db.png">

Further inspection reveals the cause of the problem. The namespace of the second `<strong>` node is SVG.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/454726/74638437-8c4af400-5174-11ea-89ba-aed3cd09505f.png">

The first which works has XHTML as a namespace.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/454726/74638485-9ec52d80-5174-11ea-92af-9a1654396aea.png">

I think the first works because it is "static" content.

### Further technical details
- ASP.NET Core version - 3.1.101
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.2 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - VS Code 1.42.1

**Comment by javiercn** [comment]
@akorchev thanks for contacting us.

We currently don't properly support SVG. We have a separate issue tracking this work, so I'm going to close this one in favor of the tracking issue we already have.

https://github.com/dotnet/aspnetcore/issues/18271

**Comment by akorchev** [comment]
@javiercn Ouch. We've undertaken quite a big SVG related task (Radzen Blazor Chart). So far this is the only issue with SVG and Blazor. Do you know what the existing issues are?
