### ISSUE TITLE
Response is 406 Not Acceptable instead of 404

### ISSUE THREAD

**Issue by andrey-rodin** [dotnet/aspnetcore#19093]
The following action produces 406 response when Accept header is "text/plain". For "application/json" response is 404. I expected 404 in both cases, because if action returns Ok("some string") and Accept header is "text/plain", then result is correct. I do not use output formatters in startup.

[Route("foo")]
[HttpGet]
[Produces("text/plain", "application/json")]
public IActionResult GetString()
{
    return NotFound();
}

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is by-design. @pranavkm can you please share more details about why as well as let's get this documented.

Thanks!

**Comment by pranavkm** [comment]
@andrey-rodin, could you share a minimal app that reproduces this issue? I would have expected a 406 in either case, if you haven't changed the default set of formatters.

**Comment by andrey-rodin** [comment]
Hi @pranavkm,
It's a bit difficult to share all app, but you can try this on service created from scratch. My service has  call `AddNewtonsoftJson(...)` in startup.

Correct response should be 404.
As I mentioned, this action produces valid "text/plain" response:
`
[HttpGet]
public IActionResult GetString()
{
    return Ok("some string");
}
`

**Comment by pranavkm** [comment]
@andrey-rodin I don't see this happening, not in a minimal app.

**Comment by andrey-rodin** [comment]
Hmm... Then I should investigate why at all my app returns text/plain when action returns string. In all other cases response is application/json, of course

**Comment by andrey-rodin** [comment]
My mistake. Response is 406 when Accept header is application/json. I expected 404 in all cases.
`
[HttpGet]
[Produces("text/plain")]
public IActionResult Foo()
{
    return NotFound();
}
`

**Comment by pranavkm** [comment]
The 406 makes sense, since content negotiation failed. Closing this since it's by-design.
