### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#19099]
TypeScript had been updated in VS and it now conflicts with a package, we reference from our react templates. Need to update the npm dependencies in SPA project templates.

**Comment by mkArtakMSFT** [comment]
@javiercn can you please handle this tonight? The windows for 3.1.3 patch is quite short and I hope we can squeeze this in.

**Comment by mkArtakMSFT** [comment]
Given that we're going through the patch process, please update the dependencies for all SPA projects, so we're clean. There have been some other minor reports by CTI regarding some failures there, and this will eliminate all of them.

**Comment by javiercn** [comment]
@mkArtakMSFT Did you mean **ALL** the dependencies? That's not a trivial thing ofr a patch to do. Can you find out what package causes VS to have issues?

**Comment by javiercn** [comment]
I've tentatively updated the dependencies on both and see what the build has to say about it. Does it affect angular too? I believe that would require us to update to angular 9, as angular needs a specific TS version
