### ISSUE TITLE
Error after upgrade to WebAssembly Preview 3.2.0 Missing _framework/blazor.boot.json after publishing

### ISSUE THREAD

**Issue by Discovery-support** [dotnet/aspnetcore#19097]
Steve Sanderson has asked me to raise this as a separate issue.

This project runs locally, but fails to correctly create and then publish (via Web Deploy). The project appears to skip the creation of _framework/blazor.boot.json as well as its dependent DLLs. **The upgrade to Blazor 3.2.0 was responsible for this issue appearing.**

Is there a workaround for this issue? (Deleting Obj and Bin directories in all projects fails to resolve this.)

To reproduce:

Publish Project (I used Web Deploy) and _framework/blazor.boot.json will be missing from the local machine and consequently missing from the remote server.

Browse to Published Website

Chrome error results:

Failed to load resource: the server responded with a status of 404 (Not Found) _framework/blazor.boot.json:1 Uncaught (in promise) ReferenceError: Module is not defined at blazor.webassembly.js:1

GitHub Example Project
**https://github.com/Discovery-support/Missing_BlazorBootJson**

**Comment by javiercn** [comment]
@Discovery-support thanks for contacting us.

@SteveSandersonMS I imagine we can have a chat with the tooling folks about this? (I don't believe webdeploy is a command-line experience).

**Comment by mkArtakMSFT** [comment]
@vijayrkn is `WebDeploy` supposed to work in this situation?

**Comment by vijayrkn** [comment]
Does this file have "CopyToPublishDirectory" set to "Always" or "PreserveNewest"?

**Comment by javiercn** [comment]
@vijayrkn I'm not sure we set it explicitly, but it gets copied as part of `dotnet publish` for sure.

Is there a way we can invoke/simulate the webdeploy logic from the cli?

**Comment by vijayrkn** [comment]
Yes, The same behavior can be triggered from commandline by passing in the web deploy profile name to dotnet publish. 
https://github.com/aspnet/websdk#msdeploy-publish

**Comment by Bartmax** [comment]
I'm having a similar issue but on build.
Rebuild a project (this creates the files no problem).
Without changing anything, press <kbd>CTRL</kbd> + <kbd>B</kbd> (build)

File `blazor.boot.json` is deleted and not regenerated.

**Comment by Discovery-support** [comment]
Thank you Bartmax, I had `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>` because my project would **not build** without it.  The upgrade to Microsoft Visual Studio Community 2019 Preview
Version 16.5.0 Preview 3.0 has resulted in the build **now succeeding** with `<BlazorLinkOnBuild>true</BlazorLinkOnBuild>`, but publishing (via WebDeploy) is resulting in 404 errors, which I am investigating.

**Comment by solidcloudio** [comment]
I'm having a similar issue since upgrading to 3.2..  My build started failing, so I turned off linking, it builds now but I get errors in the console...

Failed to load resource: the server responded with a status of 404 (Not Found)
blazor.webassembly.js:1 WASM: Error: Failed to start platform. Reason: [object XMLHttpRequest]

/_framework/_bin/JD.Blazor.Shared.dll:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Seems the whole /_framework_bin is missing ?

**Comment by Discovery-support** [comment]
Linking has to be *on*, the 404s appear to be this issue:  https://github.com/dotnet/aspnetcore/issues/18655   PDBs seem to be unnecessarily requested by the published release version (404s)

**Comment by mkArtakMSFT** [comment]
Closing as this should be fixed now. If you happen to face this after 3.2-preview2 release, please file a new issue and we will investigate it then.
