### ISSUE TITLE
Blazor WASM project: Could not find assembly: Microsoft.AspNetCore.Blazor

### ISSUE THREAD

**Issue by tobbi** [dotnet/aspnetcore#19109]
### Describe the bug
After deploying the application to IIS, I keep getting the following error in the error console when loading the Blazor app using Firefox:
```
WASM: Error: Could not find assembly: Microsoft.AspNetCore.Blazor
```

I know this is very scarce info. Please tell me what else you need from me and I'll expand on it.

### To Reproduce
1. Deploy a Blazor application. This is the publish profile:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
Diese Datei wird vom Veröffentlichungs-/Paketierungsprozess Ihres Webprojekts verwendet. Sie können das Verhalten dieses Prozesses anpassen,
indem Sie diese MSBuild-Datei bearbeiten. Weitere Informationen hierzu finden Sie unter https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <PublishProvider>FileSystem</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ProjectGuid>4a1429fd-126e-4503-bff3-f90748646f6c</ProjectGuid>
    <SelfContained>true</SelfContained>
    <publishUrl>bin\Release\netcoreapp3.1\publish\</publishUrl>
    <DeleteExistingFiles>False</DeleteExistingFiles>
  </PropertyGroup>
</Project>
```

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
<details>
>dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014883\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 Preview
Version 16.5.0 Preview 2.0

**Comment by javiercn** [comment]
@tobbi thanks for contacting us.

That typically means the app didn't manage to load. I would check the network tab to see if the actuall dll is being successfully downloaded and I would also check the application output under `_framework/_bin/` for the dll

**Comment by tobbi** [comment]
Looking at the Network tab, the DLL is apparently not being loaded. Neither is it present in the _bin directory.

**Comment by javiercn** [comment]
@tobbi can you provide details about the blazor version you are using, and also produce a binary log of the build so that we can investigate what's going on? If you are building from the command-line just pass the `/bl` flag to it.

**Comment by tobbi** [comment]
I'm using the publish command of Visual Studio. How would I pass the flag to it?
For what it's worth, it all works fine when I simply *start* my server project using the Green run button (IIS Express). Just when publishing the DLL doesn't get included.

**Comment by tobbi** [comment]
All my blazor NuGet packages have the following version:
3.2.0-preview1.20073.1

**Comment by javiercn** [comment]
@tobbi thanks for the info.

For Visual Studio is a bit more complicated. Are you publishing to an Azure website or similar or just publishing to disk?

If you want to try and get a binary log from the visual studio build, you can follow the instructions here https://github.com/dotnet/project-system-tools

Otherwise, if you can at least give us details of your publish settings in VS (what type of publish, etc) we can give it a try and see if we can repro.

**Comment by tobbi** [comment]
[ImportTool.Client_Debug_AnyCPU_DesignTimeBuild_2020-02-19T10_22_35.5079773+01_00.zip](https://github.com/dotnet/aspnetcore/files/4224199/ImportTool.Client_Debug_AnyCPU_DesignTimeBuild_2020-02-19T10_22_35.5079773%2B01_00.zip)

I collected these logs from my Temp folder, hope they're helpful.

**Comment by tobbi** [comment]
> For what it's worth, it all works fine when I simply _start_ my server project using the Green run button (IIS Express). Only when deploying, the DLL doesn't get included.

I have to amend that assessment: It doesn't work either, when simply starting it using the green run button (I had it previously set start Internet Explorer, which obviously does not use Web Assembly).

**Comment by mkArtakMSFT** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/19097

**Comment by tobbi** [comment]
I've found that a newly created Blazor project is not suffering from this issue, just the current one I'm working on. Downgrading the Blazor packages on both the server and client side to 3,1.0-preview did not yield any useful results.

**Comment by SteveSandersonMS** [comment]
We'd need repro steps, I'm afraid. I know that's not easy to provide but without it we'd just be making random guesses (and I don't have any good random guesses about this, since other people are not experiencing it).

**Comment by tobbi** [comment]
I'm on mandatory leave until April 6. I will deal with this issue when I'm back in the office. Can you wait that long?

**Comment by SteveSandersonMS** [comment]
@tobbi The bot might auto-close the issue in the meantime. If it does, that's no problem - if you need to then please just file a new issue (with repro steps relating to the latest release at that time) when you're back in the office. Thanks!
