### ISSUE TITLE
Razor runtime compilation ignores _ViewImports.cshtml in class library

### ISSUE THREAD

**Issue by bennycoomans** [dotnet/aspnetcore#19104]
### Describe the bug

I have a asp.net core 3.1 web application consisting of a project for the web app and a project which is a razor class library, containing some views. I have enabled razor runtime compilation. The project compiles fine, but when accessing a view from the class library, I get a compilation error in the browser:

`One or more compilation references may be missing ... The type or namespace name 'AtomModel' could not be found`

This looks like a bug, but maybe I am missing some configuration that I need to do in order for the correct `_ViewImports.cshtml` file to be found by the runtime compilation.

### To Reproduce

I have created a small repo that demonstrates the issue, see https://github.com/bennycoomans/RecompileRazor. Some relevant code snippets are:

#### App/Startup.cs:
``` C#
// Initialize MVC with razor runtime compilation.
var builder = services.AddMvc();
builder.AddRazorRuntimeCompilation(options =>
{
	var libraryPath = Path.GetFullPath(Path.Combine(CurrentEnvironment.ContentRootPath, "..", "Lib"));
	options.FileProviders.Add(new PhysicalFileProvider(libraryPath));
});
```

#### Lib/Views/Styleguide/Atoms.cshtml
```C#
@await Html.PartialAsync("Atoms/Atom", new AtomModel
{
})
```

#### Lib/Views/_ViewImports.cshtml
```C#
@using Lib.Models
```

#### App/Views/_ViewImports.cshtml
```C#
@using App
@using App.Models
@* Uncomment this using statement to make the app work.
@using Lib.Models
*@
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

The compilation error occurs in `/Users/bennycoomans/RiderProjects/RecompileRazor/Lib/Views/Styleguide/Atoms.cshtml` when visiting https://localhost:5001/styleguide/atoms. When uncommenting the using statement in `App/Views/_ViewImports.cshtml`, the error is fixed. It seems that the razor runtime compilation only uses that `_ViewImports.cshtml` and does not use `Lib/Views/_ViewImports.cshtml`.

### Stack trace:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
/Users/bennycoomans/RiderProjects/RecompileRazor/Lib/Views/Styleguide/Atoms.cshtml(1,49): error CS0246: The type or namespace name 'AtomModel' could not be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

#### Environment / IDE

- ASP.NET Core 3.1

Problem occurs both in Rider and when using the CLI:
- Rider 2019.3.1
- `dotnet run --project App/App.csproj`

#### Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by soeleman** [comment]
Trying your project on github and it seem the path cannot find Lib.dll .
![bennycoomans__razor_compile](https://user-images.githubusercontent.com/309413/74746967-c57c8480-5298-11ea-9232-7720385a0535.png)
When change the path as image above. we can open the page.
And it is better using  **AddControllersWithViews** as replacement **AddMvc**.

**Comment by bennycoomans** [comment]
Thanks for your reply. I don't know what you mean by the path not being able to find Lib.dll. However, the reason that the page is displayed correctly when applying your changes is that runtime compilation does not work at all. When I change the content of `Atom.cshtml`, the change is not reflected on the web page when I refresh the browser. It seems that your changes cause the changes in the Lib project not to be detected anymore.

**Comment by soeleman** [comment]
@bennycoomans My bad on that suggestion. 
Your code is working fine as it is. 
The **FileSystemWatcher** will watch the folder _Lib_ as your code does.

Re-read again your issue and as a far i know **_ViewImports.cshtml** compile to csharp (**_ViewImports.cshtml.g.cs**) in obj folder and be use within the project.
The RunTimeCompalation working with running project and they are going 'recompiling' the cshtml (more like copy, compile and as is in running project) and look like the process not 'copy'/'merge' the **_ViewImports.cshtml** from library.
For that reason, seem we must using fully name with namespace or add `using` on **_ViewImports.cshtml** running project.
![bennycoomans__razor_compile_fullnamespace](https://user-images.githubusercontent.com/309413/74759183-f960a580-52aa-11ea-90d7-e7fb81ccc514.png)

**Comment by pranavkm** [comment]
When you have multiple file providers configured, runtime compilation will use the contents of the first file that matches a given path. The order is determined by the order in which file providers are configured in the `RazorRuntimeCompilationOptions.FileProviders` list.

In your case, both files appear at the same path, 

* https://github.com/bennycoomans/RecompileRazor/blob/master/App/Views/_ViewImports.cshtml
* https://github.com/bennycoomans/RecompileRazor/blob/master/Lib/Views/_ViewImports.cshtml

`_ViewImports` do cascade though. You could move the file from the directory into https://github.com/bennycoomans/RecompileRazor/tree/master/Lib/Views/Styleguide and it should work.

**Comment by soeleman** [comment]
@pranavkm Thanks for the info. 
This behavior (conflict resolution on same file on same folder) apply on other _cshtml_, since running project always on 1st index of _FileProviders_.

**Comment by bennycoomans** [comment]
@soeleman is right. I've created a [branch](https://github.com/bennycoomans/RecompileRazor/tree/double-atom) with the following modifications:
- I fixed the application by uncommenting the `using` statement in `_ViewImports.cshtml` in the `App` project, so the page https://localhost:5001/styleguide/atoms works
- I added the file `App/Views/Shared/Atoms/Atom.cshtml`

Now, when visiting https://localhost:5001/styleguide/atoms, the contents of the `Atom.cshtml` within the App project are shown. This is regardless of whether or not recompilation is enabled (i.e. with and without calling `AddRazorRuntimeCompilation`). I understand that this is expected behaviour. Consistent with pranavkm's comment, when I insert the Lib's file provider at index 0 instead of just adding it to the list of file providers, the contents of the `Atom.cshtml` file within the Lib project are shown. So far, so good. However, although I understand where it comes from, the difference in behaviour between normal and runtime compilation still bothers me. The following table outlines which version of the file is used by which compilation method:

_ | Atom.cshtml | _ViewImports.cshtml
------------ | ----------- | ---------------------
Normal compilation | App | Lib
Runtime compilation | App | App

@pranavkm Is there some way to make normal vs runtime compilation result in the same behaviour for `_ViewImports.cshtml`, just like it does for regular `.cshtml` files? I guess it is not really feasible to modify the normal compilation process by preferring files from (in this case) the App project above the Lib project, while compiling the Lib project. So maybe it should be possible to modify the way dynamic compilation works, by making it aware of the fact that the `_ViewImports.cshtml` file in the `Lib` project is part of a separate project and should be preferred over the version in the `App` project. Maybe, for example, by adding a `ProjectFileProvider` that one can point to the `.csproj` file, instead of just pointing to a folder that contains the source files?

**Comment by pranavkm** [comment]
> Is there some way to make normal vs runtime compilation result in the same behaviour for _ViewImports.cshtml, just like it does for regular .cshtml files?

You could write a custom file provider that produces isolated hives of directories.
