### ISSUE TITLE
Missing exception on trying to load settings file without permissions

### ISSUE THREAD

**Issue by digitaldias** [dotnet/aspnetcore#19102]
### Describe the bug
When setting up an Asp.Net Core application using **.ConfigureAppConfiguration()** to add a JsonFile, the runtime fails silently to read that file unless Visual Studio is running as an administrator. 

**Expected**
Some sort of runtime exteption stating that the program lacks the privileges to read that file.

### To Reproduce
Run this in Visual Studio *without* Administrator privileges
```csharp
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(config => {

                var basePath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                var fullName = Path.Combine(basePath, "mySpecialSettings.json");

                if (File.Exists(fullName))
                    config.AddJsonFile(fullName, optional: true);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 19, Version 16.4.5

**Comment by soeleman** [comment]
Usually this happen went file/folder permission involve and nothing todo with ASP.NET .
Check it by look on property setting. From owner or read or etc.
![digitaldias__file_security](https://user-images.githubusercontent.com/309413/74749800-49d10680-529d-11ea-99b4-1d40fb03dc40.png)
and when you open **Advanced**
![digitaldias__file_security_advance](https://user-images.githubusercontent.com/309413/74749837-58b7b900-529d-11ea-97a0-6c876b1535b4.png)

**Comment by Tratcher** [comment]
I expect this is due to the `optional: true` option. Do you get the expected exception if you disable that?
