### ISSUE TITLE
blazor syntax in <style> blocks

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#19105]
I am working with a third-party blazor component where I need to apply styles to UI elements. The third-party component does not support it directly, but all divs etc. have (auto-generated) IDs, so I can write css styles with the correct selectors based on those IDs. So I have a loop over all such IDs and then create a style for the divs. Simplified code:

```csharp
@foreach (var (id, color) in ids.Zip(colors, (a, b) => (a, b)))
{
   <style>
    div[id=@(id)] {
       color: @color
    }
   </style>
}
```

This works, but creates a `<style>...</style>` block for each and every id. This is unnecessary overhead, as everything can be in one style block, if done manually. Ideally, the code should roughly be this:

```csharp
<style>
   @foreach(var (id, color) in ids.Zip(colors, (a, b) => (a, b)))
   {
       // the following line will be interpreted as C# in the current syntax,
       // but is intended as css. Therefore it doesn't work..
       div[id=@(id)] {
       color: @color
    }
   }
</style>
```

The problem here is that there is no way to break out of the C# context without opening a html element, which is (afaik) not permitted within a style block. A workaround here of course is to generate the entire css rule as text in C# and only then paste the text:

```csharp
<style>
   @foreach(var (id, color) in ids.Zip(colors, (a, b) => (a, b)))
   {
      var rule = $"div[id={id}] {{ color: {color} }}";
      @rule
   }
</style>
```

This works, but has the obvious disadvantage of no css-syntax highlighting in IDEs, as it's inside of a C# interpolated string.

In my opinion, the optimal solution would be some syntax that works in the opposite way of the `@` symbol, i.e. break out of C# back into html.

**Comment by javiercn** [comment]
@stefanloerwald thanks for contacting us. 

You can use `<text></text>` to force a context switch in razor syntax. That should do it I believe.

**Comment by stefanloerwald** [comment]
@javiercn Great, that actually does it. I searched the blazor docs for ages, and couldn't find it, now I've seen `<text></text>` and also `@:` in the Razor syntax page. I think it wouldn't hurt having an example of the usage of that syntax in the Blazor section as well.

**Comment by javiercn** [comment]
@stefanloerwald avoid using `@:` in Blazor, it is not something we currently support in Blazor. (Even though we don't error out).

Using `<text></text>` should be fine.
