### ISSUE TITLE
control-label not found

### ISSUE THREAD

**Issue by rhires** [dotnet/aspnetcore#19112]
### Describe the bug
In the input fields for default forms created by dotnet core, the css class "control label" is not found by Resharper. I did a search and could not find this class either. 

### To Reproduce

Create a default project using dotnet core. The forms come with some default input code such as
`<div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" required="required" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>`
But I get notifications from Resharper saying that the "control-label" is an unknown css class. This is a minor thing. It doesn't seem to be in the css in the project. 
Running Visual Studio 16.4.5
### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The class you're referring to is coming from Bootstrap. We recommend following up with the Resharper owners regarding why it's having hard time discovering it.

**Comment by rhires** [comment]
As part of working with Resharper, I did a search of the bootstrap.css file, and "control-label" is not in there. It's also not in any of the sub-files. There are plenty of "custom-control-label" entries in these files, but not the one I'm looking for.

**Comment by mkArtakMSFT** [comment]
@rhires hope this helps: https://stackoverflow.com/questions/37248897/what-does-bootstraps-control-label-class-do

**Comment by mkArtakMSFT** [comment]
It looks like the class has been renamed in Bootstrap 4, but it's still available in Bootstrap 3. Given that IdentityUI has Bootstrap 3 version support too, we still use it. We will look into upgrading to the latest version of Bootstrap during .NET 5.0 timeline and if that will happen, we will adjust the styling as necessary.

**Comment by mkArtakMSFT** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/19225 to address this during migration to the latest Bootstrap release.

**Comment by rhires** [comment]
Awesome! Thank you. I saw the SO post you linked to. I guess I'll need to find out what the control-label class was renamed to, but that's not a big deal. Thanks again! :-)

**Comment by mkArtakMSFT** [comment]
@rhires, from Bootstrap 4 migration documentation:
> Renamed .control-label to .col-form-label.

Source: https://getbootstrap.com/docs/4.0/migration/
