### ISSUE TITLE
Client-SignalR on WebAPI without Hub-SignalR in the same solution - how to configure for work? 

### ISSUE THREAD

**Issue by parad74** [dotnet/aspnetcore#19114]
# Issue Title

Client-SignalR on WebAPI without Hub-SignalR in the same solution - how to configure for work? 

# General
Windows 10
dotnet Core 3.1.1
WebAPI
SignalR 
----------
These are 2 applications Server and WebAPI :
My architecture has 1) remote WebAPI application and 2) Server that calls WebAPI. They are located at different addresses and perform different tasks. Hub SignalR is located on Server. I need to configure Client on WebAPI so that it informs everyone about the intermediate steps performed so that the server knows.
The whole day I was looking for how to register Client SignslR as Service (in WebAPI) so that Client SignslR would send messages from Controller on WebAPI to Server (Hub SignalR ).
I would like it to be convenient as with IHubContext, but at least correctly, even if it is not convenient.

Help me, plz. Cann't find any sample how use SignalR client on WebAPI\in controller without Hub in the same project.

**Comment by BrennanConroy** [comment]
You need to create the connection on the WebAPI and manage passing it to your controller yourself. There is no built in server like `IHubContext` for this. You would need to create your own custom service that wraps a HubConnection if you'd like something similar.

pseudo code:
```c#
class MyService
{
    private readonly HubConnection _connection;
    public MyService()
    {
        _connection = new HubConnectionBuilder().WithUrl("someurl").Build();
       _connection.On(...);
    }

    public Task StartAsync()
    {
        return _connection.StartAsync();
    }

    public Task SendMessage(string message)
    {
        return _connection.SendAsync("method", message);
    }
}
```

**Comment by parad74** [comment]
BrennanConroy , thank you for confirming that this must works. It helped me.
I continued testing.

And got so result
My mistake was that in Action in  Controller I returned not  async Task
//NOT WORK
```
[HttpGet]
public Processes GetProcesses ()
{
//and I called everything synchronously
...
_hubChatConnection.StartAsync();
_hubChatConnection.InvokeAsync("SendMessage", "_hubSignalRRepository", "Processes");
...
}
```
no messages-error were issued in VisualStudio
//==========================
//Need change to async\await !
//WORK
```
[ServiceFilter(typeof(ControllerSignalRChatHubFilter))]
[HttpGet]
public async Task<Processes> GetProcesses()
{
	Processes processes = new Processes();
	processes = this._processRepository.GetProcesses();
	try
	{
	await this._hubSignalRRepository.HubChatConnection.StartAsync();
	await this._hubSignalRRepository.HubChatConnection.InvokeAsync("SendMessage", "GetProcesses", "Count = " + processes.Count);
	}
	catch (Exception ecx) { this._logger.LogError(ecx.Message, ecx); }
	finally { await this._hubSignalRRepository.HubChatConnection.StopAsync();}
	return processes;
}

// add ActionFilter
 ControllerSignalRChatHubFilter : Attribute, IActionFilter
...
public void OnActionExecuting(ActionExecutingContext context)
{
	try
	{
	if (_hubSignalRRepository.HubChatConnection == null)
	{
	_hubSignalRRepository.HubChatConnection = new HubConnectionBuilder()
	  .WithUrl(_chatHubAddress)
	  .Build();
			
	_hubSignalRRepository.HubChatConnection.On<string, string>(SignalRHubFunction.ReceiveMessage, (user, message) =>
	{
	_logger.LogInformation("OnActionExecuting.ControllerSignalRChatHubFilter" + " create SignalR Cient ");
	});
}
}
catch (Exception ex)
{
}
}

```

**Comment by parad74** [comment]
It works, but I still have question where to do StartAsync \ StopAsync ?
In every Action ? This is good practice?

**Comment by BrennanConroy** [comment]
> In every Action ? This is good practice?

No, you should probably do it once at the beginning of your application.
