### ISSUE TITLE
SignalR with Blazor WebAssembly 3.2 - exception in Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder.Build() when following tutorial

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#19115]
Blazor WebAssembly 3.2.0-preview1.20073.1

I am following the 'SignalR with Blazor WebAssembly' tutorial:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio 

However, I get an exception when running my Blazor application:

<img width="845" alt="1" src="https://user-images.githubusercontent.com/888718/74757659-9ce39300-5276-11ea-8d3a-5918ea6c8760.png">
<img width="846" alt="2" src="https://user-images.githubusercontent.com/888718/74757669-a0771a00-5276-11ea-8787-55d7c31d5e1d.png">
![3](https://user-images.githubusercontent.com/888718/74757683-a40aa100-5276-11ea-94d8-92f7049f9aff.png)

Repro can be found here:
https://github.com/ChristianWeyer/blazor-signalr-repro

Any idea what could be the issue?
.cc @danroth27

**Comment by BrennanConroy** [comment]
Try a full clean and rebuild of the project.

**Comment by ChristianWeyer** [comment]
Hi @BrennanConroy - thanks for the super-quick reply :-)

That was easy. Cool.

Do you mind explaining what happened?
