### ISSUE TITLE
Undo changes to Targeting Pack project

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#19121]
In 3.1, we made some changes to the Targeting Pack project related to using a checked-in platform manifest: https://github.com/dotnet/aspnetcore/pull/18250/files

We should tweak the conditions in those changes, as that checked-in file doesn't exist in master.

CC @dougbu @JunTaoLuo

**Comment by dougbu** [comment]
Didn't this get done as part of the mega merge or the follow-up mini-mega merge?

**Comment by wtgodbe** [comment]
Mostly, except for https://github.com/dotnet/aspnetcore/blob/07ce5862b2fcb10d8fdb8d81cf5f26a905f951d4/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L57 (since there is no checked-in manifest), and https://github.com/dotnet/aspnetcore/blob/07ce5862b2fcb10d8fdb8d81cf5f26a905f951d4/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L160 (we can just use `PlatformManifestOutputPath` now). Will put up a PR

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/19529
