### ISSUE TITLE
Dependencies impossible to satisfy for Microsoft.AspNetCore.Identity.EntityFrameworkCore, Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore in connection with Microsoft.EntityFrameworkCore.Relational

### ISSUE THREAD

**Issue by ChaosEngine** [dotnet/aspnetcore#19137]
### Describe the bug
`Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` and `Microsoft.AspNetCore.Identity.EntityFrameworkCore` both have requirement of:
**Microsoft.EntityFrameworkCore.Relational (>= 3.1.2)**
which is not yet release and because of that dotnet restore phas fails

### To Reproduce

In *.csproj Try to reference 
`<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.2" />`
and/or 
`<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.2" />`
which are relased and observe that tahy can not load
`<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.2" />`

### Further technical details
- ASP.NET Core version : 3.1.101
- Include the output of `dotnet --info`

dotnet --info
Zestaw .NET Core SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   3.1.101
 Commit:    b377529961

▒rodowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 -version 16.4.5

**Comment by ChaosEngine** [comment]
![image](https://user-images.githubusercontent.com/1271428/74821077-5b4cf980-5303-11ea-8cb4-e36cc5ce9046.png)

**Comment by knoxi** [comment]
Same for the package `Microsoft.AspNetCore.DataProtection.EntityFrameworkCore`.
It has a dependency to `Microsoft.EntityFrameworkCore` with version >= 3.1.2 which cannot be resolved.

**Comment by AndreiGorlov** [comment]
Same for Microsoft.EntityFrameworkCore.Sqlite:
![image](https://user-images.githubusercontent.com/13963009/74827228-b4be2400-5315-11ea-8441-8f90d6b7b408.png)

Maybe issue should be filed in EntityFrameworkCore repo?

**Comment by kriwec** [comment]
Same for Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore

"someone" forgot to do new package for https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/

**Comment by javiercn** [comment]
@ChaosEngine thanks for contacting us.

@dotnet/aspnet-build We do have an issue related to this, don't we?

@anurse is this the same issue as the sql cache global tool issue?

**Comment by dougbu** [comment]
@anurse @ajcvickers were EF packages released yesterday? This looks very much like a gap in the release.

@javiercn this is unrelated to the global tool issue. That was about dependencies on the latest shared framework while this is about missing packages on NuGet.

**Comment by ajcvickers** [comment]
@dougbu No EF packages were released. There weren't any EF fixes, and my last understanding from talking to @Pilchie was that other packages were supposed to reference 3.1.0 rather than 3.1.x, so I assumed it was by design that we didn't push new packages. We probably just need to push the EF packages.

**Comment by Pilchie** [comment]
FYI that @anurse got these published this morning, so as NuGet.org ingests them, this issue should be mitigated.

@ajcvickers Other packages *are* supposed to reference 3.1.0, but we haven't made that switch yet.

**Comment by kriwec** [comment]
done 31 minutes ago

**Comment by ChaosEngine** [comment]
Closing as I can see new newly published https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/3.1.2
