### ISSUE TITLE
How can I get to know while page be closed by killing the browser process on mobile?

### ISSUE THREAD

**Issue by kyuranger** [dotnet/aspnetcore#19131]
I used to get to know whether the page is closed in blazor-sever side by CircuitHandler before.

Here is the code of the back-end:

using Microsoft.AspNetCore.Components.Server.Circuits;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace BlazorCircuitHandler.Services
{
    public class CircuitHandlerService : CircuitHandler
    {
        public ConcurrentDictionary<string, Circuit> Circuits { get; set; }

        public CircuitHandlerService()
        {
            Circuits = new ConcurrentDictionary<string, Circuit>();
        }

        public override Task OnCircuitOpenedAsync(Circuit circuit, CancellationToken cancellationToken)
        {
            Circuits[circuit.Id] = circuit;
            return base.OnCircuitOpenedAsync(circuit, cancellationToken);
        }

        public override Task OnCircuitClosedAsync(Circuit circuit, CancellationToken cancellationToken)
        {
            Circuit circuitRemoved;
            Circuits.TryRemove(circuit.Id, out circuitRemoved);
            return base.OnCircuitClosedAsync(circuit, cancellationToken);
        }

        public override Task OnConnectionDownAsync(Circuit circuit, CancellationToken cancellationToken)
        {
            return base.OnConnectionDownAsync(circuit, cancellationToken);
        }

        public override Task OnConnectionUpAsync(Circuit circuit, CancellationToken cancellationToken)
        {
            return base.OnConnectionUpAsync(circuit, cancellationToken);
        }
    }
}
Here is the code of front-end
@page "/"

@using Microsoft.AspNetCore.Components.Server.Circuits
@inject CircuitHandler CircuitHandlerService

<h1>Hello, world!</h1>

Welcome to your new app.

<p>
    Number of Circuits: @((CircuitHandlerService as BlazorCircuitHandler.Services.CircuitHandlerService).Circuits.Count)

    <ul>
        @foreach (var circuit in (CircuitHandlerService as BlazorCircuitHandler.Services.CircuitHandlerService).Circuits)
        {
            <li>@circuit.Key</li>            
        }
    </ul>
    @{ 
        var PrimaryKey = "abcdefg";
    }
</p>
All seems works well while these days I found a strange problem:

In the PC browser, the OnCircuitClosedAsync will always invoke even I use the Task Manager of windows to kill the browser process.

However, in the mobile browser(I tested chrome&safari in IOS 13.3.1 and chrome in Android 9) the OnCircuitClosedAsync will not invoke if I kill the browser process.

As we know, many people exit their APP on the cellphone just by killing the process directly that I have to think about this.

How can I solve this? Thank you.

**Comment by kyuranger** [comment]
I found the problem.

I add some code to show all circuits in the front-end. Now I found something interesting: when I debug the program not only by the visual studio but also by the visual studio code, the circuits always alive when I kill the browser in the cellphone while it won't alive when I kill the browser in PC.

And then I found that the circuits which should be closed soon be closed after I disconnect the debug in 15 seconds. At last, I add a logger in my code and test both by PC and mobile without any debugger, the logger logs the close information successfully. It seems it is the problem of the debugger but not the code.

**Comment by kyuranger** [comment]
@mkArtakMSFT It seems the problem of the debugger. Here is the sample project: https://github.com/kyuranger/TestProject .Can Microsoft solve this? Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for the repro. @javiercn do you know what's happening here and why?

**Comment by kyuranger** [comment]
@mkArtakMSFT I should add that it close within 15 seconds because I have set :
services.AddServerSideBlazor(options=> {
                options.DisconnectedCircuitRetentionPeriod = TimeSpan.FromMinutes(1);                
            });
The time is relate to the setting but not the problem.

**Comment by javiercn** [comment]
@kyuranger I suggest you turn on the logs to the maximum level, capture the network traffic if possible and try and see if the the browser sends a request to the disconnect endpoint.

If the OS kills the browser page before calling the handler we setup during the onbeforeunload method, then there's nothing we can do there and the behavior you are seeing is the best it gets.

In that case, the circuit will go away after the retention period passes.
