### ISSUE TITLE
Razor value in HTML attribute syntax coloring broken

### ISSUE THREAD

**Issue by bugproof** [dotnet/aspnetcore#19143]
![image](https://user-images.githubusercontent.com/3116731/74838311-ad9e1280-5323-11ea-8ae0-be5a2cf9852e.png)

Rider:

![image](https://user-images.githubusercontent.com/3116731/74838476-f35adb00-5323-11ea-8408-3ecc34aeb01e.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@NTaylorMullen can you please have a look at this? Thanks!

**Comment by NTaylorMullen** [comment]
@bugproof thanks for the bug! It's super helpful to see what others are doing so we can improve, thanks for providing the comparison so clearly, it's definitely something we want to fix!

We're currently tracking that work as part of https://github.com/dotnet/aspnetcore/issues/14290 so for now I'm going to close this as a duplicate and track the fixing for this there.
