### ISSUE TITLE
ASPNetCore Hosting Bundle doesn't install aspnetcore.dll

### ISSUE THREAD

**Issue by DrewTurner** [dotnet/aspnetcore#19149]
Server 2019

Installing 3.1.0 OR 3.1.1 results in aspnetcore.dll not being put into c:\windows\system32\inetsrv causing IIS to crash as it can't load this dll.  This works properly in 2.1.13

I typically install silently with chef, however it behaves this way when installing directly from the MSI while remoted into the machine as well.

The workflow for install is we install IIS, all of it's dependencies we typically use, then install the hosting bundle.

Output from dotnet --info

> Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

> .NET Core SDKs installed:
  No SDKs were found.

> .NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

This is quite likely a duplicate of #17086 which was closed with no response from the requester.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@joeloff can you please have a look at this issue? Thanks!

**Comment by jkotalik** [comment]
This was an intentional change in 3.0 to remove aspnetcore.dll from the hosting bundle. See https://github.com/aspnet/Announcements/issues/339.

Can you post the error you are seeing though? There are a few types of exceptions that could be happening. Check the windows hosting bundle if you aren't sure.

You should be targeting AspNetCoreModuleV2 in your web.config; all projects by default in 3.0+ should target that.

**Comment by DrewTurner** [comment]
Just now reading that announcement.  Will investigate this as the module is auto generated in the web.config.

Here is the error which make sense as the dll isn't present.

> The Module DLL C:\Windows\system32\inetsrv\aspnetcore.dll failed to load.  The data is the error.

We'll investigate targeting the new module.

**Comment by DrewTurner** [comment]
Switching to AspNetCoreModuleV2 and targeting that worked perfectly.  Thank you very much for pointing out that breaking change.  We totally missed it.
