### ISSUE TITLE
Simple Blazor WASM app (from File - New...) does not properly work in Electron - "Only 'http' and 'https' schemes are allowed"

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#19142]
Blazor WebAssembly 3.2.0-preview1.20073.1

I am creating a simple Blazor WASM application in VS 2019. Then I am going to publish it to the file system. The files are copied over to an Electron folder where electron-packager is used to create a .exe.

Everything looks good when starting the .exe.
However, when navigating to ''Fetch data' I get this exception (and I did change the URL to the Web API to be fully qualified, not just relative):

```
blazor.webassembly.js:1 WASM: System.ArgumentException: Only 'http' and 'https' schemes are allowed.

blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpClient.CheckBaseAddress (System.Uri baseAddress, System.String parameterName) <0x2001100 + 0x00056> in <filename unknown>:0 

blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpClient.set_BaseAddress (System.Uri value) <0x2000ff8 + 0x00008> in <filename unknown>:0 

blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder+<>c.
```

<img width="1680" alt="Screen Shot 2020-02-19 at 13 54 33" src="https://user-images.githubusercontent.com/888718/74836276-644bc400-531f-11ea-98cd-079099a7ef06.png">

Any ideas on what could be the issue here?

Here is a repro:
https://github.com/ChristianWeyer/blazor-electron-repro

Thanks.

**Comment by javiercn** [comment]
@ChristianWeyer thanks for contacting us.

I believe at some point we had an experiment going for electron.

@SteveSandersonMS can you point him to the right place?

**Comment by ChristianWeyer** [comment]
Thanks for the quick reply @javiercn 

Actually, the experiment is here:
https://github.com/aspnet/AspLabs/tree/master/src/ComponentsElectron

It is quite outdated, though.
And in my case, I was trying to just get the published/deployed package to run in Electron :-)

Thanks.

**Comment by ChristianWeyer** [comment]
Could you please elaborate @mkArtakMSFT what would be an 'enhancement' here? :-)

**Comment by SteveSandersonMS** [comment]
The enhancement would be changing `CheckBaseAddress` to not enforce the "http or https only" restriction. Or if this is a difference in behavior between CoreCLR and Mono, then it would be a bug not an enhancement.

**Comment by ChristianWeyer** [comment]
Thanks @SteveSandersonMS ! Does that mean that for now there is now way to use Blazor WASM in Electron?

**Comment by SteveSandersonMS** [comment]
Currently to use Blazor in Electron I'd recommend [this approach](https://github.com/aspnet/AspLabs/tree/master/src/ComponentsElectron), which runs natively on CoreCLR and has many advantages over running it on WebAssembly. It performs better, can call arbitrary native OS APIs, and has complete VS debugging support today.

I don't know whether there's some way to make it run on WebAssembly inside Electron since it's not a scenario I've tried. *Maybe* all you need to do is wait for the next preview release in the next few weeks, since in that release we're no longer going to enforce use of a base address on the default HttpClient.

**Comment by ChristianWeyer** [comment]
Thanks for the clarification, much appreciated.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
