### ISSUE TITLE
UserManager does not update SecurityStamp for role or claim changes

### ISSUE THREAD

**Issue by willdean** [dotnet/aspnetcore#19140]
### Describe the bug

In most methods which change a user (e.g. changing name, telephone, removing ext-logins, password hash, etc), `UserManager` calls a helper method `UpdateSecurityStampInternal` which regenerates the security stamp to cause subsequent invalidation of the auth cookie.

However, this doesn't happen for changes to roles or claims (neither removal nor addition).

Issue #10386 is not directly related to roles or claims, but the principal espoused by @blowdart that removing implied permissions should trigger logout (via the SecurityStamp) seems to apply here.  If I remove a role from a user, I don't want them to retain a cookie which contains that role.

Clearly, a simple work around is to call `UserManager.UpdateSecurityStampAsync` directly from application code whenever roles are changed, but it feels inconsistent that the application needs to do this manually if it changes a role, but wouldn't need to do it if it changed a phone number.

### To Reproduce

Add a role to an existing user (using UserManager.RemoveFromRoleAsync) and observe (via the db) that the security stamp doesn't change.
Change a user's telephone number (using UserManager.SetPhoneNumberAsync) and observe that the security stamp does change.

### Further technical details
- ASP.NET Core version 3.1.1

**Comment by blowdart** [comment]
I think you're misunderstanding what I wrote. Role changes will update the cookie once the refresh limit is hit, I don't feel a role change needs to trigger logouts, it's a reasonably common workflow that doesn't need to logout everyone everywhere.

**Comment by willdean** [comment]
Thanks for the reply - I'm sure it is my misunderstanding - but it does seem to me surprising that if you change someone's phone number then the framework logs them out at the next validation, but if you revoke their role as a manager it doesn't.  

But I guess that's because the framework has its own concerns about phone numbers, email address, etc, whereas the use of roles in authorization is more of an application concern.

**Comment by blowdart** [comment]
It's because phone numbers can be used for 2fa, same for email.
