### ISSUE TITLE
System.IO.Path.GetFileName doesn't work in client-side Blazor wasm

### ISSUE THREAD

**Issue by dmarchant** [dotnet/aspnetcore#19141]
`System.IO.Path.GetFileName(<FullFilePath>)` and `new System.IO.DirectoryInfo(<FullFilePath>).Name` do not work the same in client-side Blazor wasm as they do in server-side C#. In Blazor wasm it just returns back the same full path that you sent it. It doesn't extract the file name from the full path.

### Environment
dotnet sdk: version 3.1.100 commit cd82f021f4
Blazor: 3.2.0-preview1.20073.1

### To Reproduce
Create a new client-side asp.net core hosted blazor wasm project
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1
dotnet new blazor wasm -ho
```
Add the following lines to the `Program.cs` of both the `Project.Server` and `Project.Client`
```C#
Console.WriteLine(System.IO.Path.GetFileName(@"C:\FakePath\File1.txt"));
Console.WriteLine(new System.IO.DirectoryInfo(@"C:\FakePath\File1.txt").Name);
```
Execute the project. The Project.Server will output
```
File1.txt
File1.txt
```
The Project.Client will output
```
WASM: ﻿C:\FakePath\File1.txt
WASM: C:\FakePath\File1.txt
```

**Comment by javiercn** [comment]
@dmarchant thanks for contacting us.

We believe this issue is not related to Blazor itself but to the mono runtime. For that reason, we are moving this issue to that repo so that they can follow-up with you.

**Comment by javiercn** [comment]
This issue was moved to mono/mono#18933
