### ISSUE TITLE
In Blazor WebAssembly preview 2 release notes, be clear about new SDK requirement

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19145]
As of preview2, we'll require .NET Core SDK 3.1.102+.

If customers still have 3.1.101, they will get a really obscure build error:

```
Fatal error in Mono CIL Linker
C:\Users\username\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview2.20119.1\targets\Blazor.MonoRuntime.targets(256,5): error : Unhandled exception. Mono.Cecil.AssemblyResolutionException:
Failed to resolve assembly: 'obj\Debug\netstandard2.1\YourApplication.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

Even though we'll specify the SDK requirement in the release notes, a large percentage of developers may forget to update. It might be frustrating for those developers that it's hard to work out what's gone wrong.

### Proposed solution

~~If we have a sensible way to check the SDK version during build, it would be excellent to fail with a clear message.~~

~~We don't really have to do this. If we choose not to, it just means some extra short-term support noise. We might consider it sufficient just to put a *really clear* notice about the SDK requirement in release notes.~~

Update: we're just going to emphasise it in release notes.

**Comment by rynowak** [comment]
Do we know if there's a way to even *get* the SDK's version? Last I check on this they deliberately made this hard so that other teams wouldn't do things like this 😆

**Comment by SteveSandersonMS** [comment]
We discussed this and decided that since it's *only* going to affect the preview 2 release, and not later previews or the final release (since later previews and the final release will actually ship as part of the SDK that they need), it's not desirable to make a special feature for this.

Instead we'll just be really clear in release notes about which SDK is required.

**Comment by pranavkm** [comment]
This is done.
