### ISSUE TITLE
Razor/Blazor auto inherits BaseComponent (even if defined otherwise in partial class)

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#19152]
### Is your feature request related to a problem? Please describe.
Razor class generation enforces (in Blazor app) @inherits BaseComponent? IMO this should only happen if there are no partial classes for the razor page overriding the inheritance.

e.g:

Counter.razor

    @page "/counter"

    <h1>Counter</h1>

    <p>Current count: @currentCount</p>

    <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

Counter.razor.cs

    namespace Blazor.Client.Pages
    {
        public partial class Counter : SomeComponent
        {
            int currentCount = 0;

            void IncrementCount()
            {
                currentCount++;
            }
        }
    }

Where `SomeComponent : ComponentBase`

In this case, we get an error because the Counter.razor.g.cs (generated class) is extending ComponentBase without me ever defining it.

### Describe the solution you'd like
I would like this "auto" functionality to check for partial classes first to determine if they inherit anything before auto inheriting ComponentBase.

**Comment by pranavkm** [comment]
Sounds like https://github.com/dotnet/aspnetcore/issues/18750

**Comment by grahamehorner** [comment]
@pranavkm the issue you reference is closed; would the team re-open and mark this as up-for-grabs and/or accept a pull request for the tooling that addresses this?!

**Comment by mkArtakMSFT** [comment]
The main reason we closed the referenced issue is that it's a huge amount of non-trivial work to make this work. Given the complexity we don't think this is a good candidate to be up-for-grabs.

**Comment by ScottKane** [comment]
@mkArtakMSFT how is it a huge amount of work? just give us a config option to disable the automatic inheritance in our generated classes?

**Comment by ScottKane** [comment]
@mkArtakMSFT also I don't understand your point "given the complexity", you already have complex code generation which has the ability to detect partial classes. How is it more complicated to check if partial class exists, if it does use it's inheritance if it differs from ComponentBase

**Comment by pranavkm** [comment]
>  you already have complex code generation which has the ability to detect partial classes.

The generated classes are always partial by default. Code generation isn't aware of the "other" partial type.  

> just give us a config option to disable the automatic inheritance in our generated classes?

You might be able to approximate this by adding an `@inherits Microsoft.AspNetCore.Components.IComponent` in the root `_Imports.razor`

**Comment by grahamehorner** [comment]
@pranavkm if by conversation the razor components follow *.razor with the code behind file of *.razor.cs the code generation could simply check for the presence of the code behind and see if the partial class inherent from some base class, if so is it something that differs to ComponentBase and implements IComponent, and therefore the *.razor.g.cs would also derive from the same base class if not then the generated class would derive from ComponentBase as it does currently.  I  understand if the by convention is not something that is willing to be forced upon developers and if that is the case I can see why this could become complicated.  Just an idea, to see if you think that would make this less difficult and possibly address the problem

**Comment by ScottKane** [comment]
Agreed with @grahamehorner, even if the restriction was that if you want to use code behind to define the inheritance then you have to name the file *.razor.cs || *.cshtml.cs. Anything else could use current implementation as default.

**Comment by pranavkm** [comment]
> the code generation could simply check for the presence of the code behind and see if the partial class inherent from some base class,

That's the non-trivial bit. To inspect the type, you'd need to have already compiled the assembly. You cannot guarantee that the assembly compiles without the component present, other C# code could reference it.

**Comment by ScottKane** [comment]
@pranavkm adding `@inherits IComponent` to _Imports.razor and creating code-behind partial classes (inheriting ComponentBase unless otherwise needed) for every razor page works. Thank you

**Comment by ScottKane** [comment]
@mkArtakMSFT @pranavkm I don't think this issue should be closed as regardless of priority, it is still a feature request. Closing it just buries the request so that there is no chance it will ever be done.

Sensible feature request like the ability to override inheritance from a code-behind partial class (even if the convention you have to adhere to is naming the code-behind class {razor_filename}.cs) should be added to a backlog as low priority in the hopes that someone might do it if/when they have time.
