### ISSUE TITLE
HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19153]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/906113/http-error-5025-process-failure.html)._

---
I've just intalled Visual studio 2017, 19 on new computer. 
I am not able to execute any project. 

i am getting below error,

**HTTP Error 502.5 - Process Failure**

or

**dotnet.exe exited with code -2147450743**

---
#### Visual Studio Feedback System on 2/4/2020, 10:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 2/10/2020, 02:17 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Juan José Mejia [MSFT] on 2/18/2020, 09:08 AM: 

<p>Thanks for reporting this. If you were to create a brand new web project, do you still see this problem?</p>

#### Andrew Stanton-Nurse on 2/19/2020, 09:24 AM: 

<p>This is a runtime issue, I’m going to move this to our GitHub repo so the runtime team can see it. The next comment will include a link to the GitHub issue and this issue will be closed. Discussion should move to the GitHub issue.</p>

---
### Original Solutions
(no solutions)

**Comment by anurse** [comment]
Can you take a look at the Windows Event Viewer? The detailed failure should be there. See our [troubleshooting guide for IIS](https://aka.ms/aspnet/iis/troubleshoot) for more details.

**Comment by anurse** [comment]
Going to ping this issue to keep it active a bit longer since it came from VS Feedback and the author may not have taken a look here.
