### ISSUE TITLE
Make sure we never ship a versioned CoreFx ref assembly with the targeting pack

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#19151]
There are a couple of CoreFx packages (e.g. System.IO.Pipelines) that are not in `Microsoft.NetCore.App`, but are in our shared framework. We should make sure we're guaranteeing that, when CoreFx ships new versions of those packages & we patch the targeting pack, we don't include the versioned ref assembly in our patched targeting pack (we should include the ref assembly that shipped with GA).

CC @dougbu @JunTaoLuo @ericstj 

Context: https://github.com/dotnet/corefx/pull/42837

**Comment by dougbu** [comment]
Remaining work is primarily testing.
