### ISSUE TITLE
Development is slow in MVC dot net core compared to MVC 5

### ISSUE THREAD

**Issue by shadinamrouti** [dotnet/aspnetcore#19162]
I think .net core is not practical compared to MVC 5.
Most of my time as a developer is gone waiting for Visual Studio 2019 compile or publish my changes.
This is really non-productive.
The publish is too slow. 
The compilation is too slow.
Modifying a view requires full publishing to get the views dll (by default)
An explicit recompilation is required for every singe change opposite to MVC 5.
This waiting is killing dot net. 
Is this by design? I mean, the dot net application is a console application which means it is not natural to IIS (compared to MVC 5). 
I think I am really suffering in developing in dot net core (compared to MVC 5). 
Please help what should I do to speed up development and debugging.
I'm a 14 year dot net developer. My patience is spent waiting, waiting and waiting.
Please let me know if I should file an issue at another repo. Thanks to all agreeing developers.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @shadinamrouti.
As @benaadams has pointed out, Runtime Compilation is not enabled by-default starting from .NET Core 3.0. This is probably what you're facing. To learn more about how you can enable it for your project you can have a look at: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation

If there is any other specific concern you have please don't hesitate to raise it.
