### ISSUE TITLE
Stop depending on C#_LSP content type for Razor's C# LSP buffer

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#19184]
Roslyn is working on deprecating their C#_LSP content type and instead intend to rely on TextBuffer properties to indicate that a TextBuffer should be an LSP powered buffer.

The setting buffer properties work is tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032052/?triage=true

This issue is blocked today but I'm throwing it into our LSP Preview 3 milestone to ensure we at least check if we can move over to the normal C# content type to allow Roslyn to fully deprecate their old one.

**Comment by NTaylorMullen** [comment]
@dibarbet what's the status on your side of this?

**Comment by dibarbet** [comment]
@NTaylorMullen paused until we have Nexus integration tests running.  I'd expect it to happen after that.  I'll let you know as soon as the work is started.
