### ISSUE TITLE
QUESTION: Passing element reference from js to C# and back #16110

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#19196]
A quick follow up question to this issue #16110.

Are there any plans to support passing HTMLElement to .NET?

**Comment by javiercn** [comment]
@msschl thanks for contacting us.

I'm not entirely sure of what you mean by that. If you mean serializing all the event properties, etc. The answer is likely no.

If all you want is to get a reference to the element you can call methods on, you can use HtmlElement with `ref` to capture it.

**Comment by msschl** [comment]
I am referring to this comment from @SteveSandersonMS:
> Your JS code receives an HTMLElement, which is not the same thing as an ElementRef. We don’t presently have any support for passing an HTMLElement to .NET - that relates to a broader matter of passing arbitrary JS object references to .NET which is not yet implemented.
