### ISSUE TITLE
Cannot make API calls on blazor in front-end

### ISSUE THREAD

**Issue by ALMLAMBO** [dotnet/aspnetcore#19195]
I want to ask why when I make an API call in blazor server app, the app stops working and where I call API throws System.Net.Http.HttpClient.HttpRequestException: 'response status code does not indicate success: 400 (bad request). How can I fix it?

**Comment by javiercn** [comment]
Thanks for contacting us @ALMLAMBO .

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

This question doesn't seem to be specific to Blazor. I would suggest you try to do the same http request from a console application and see if there is any difference.

Additionally, I would recommend you capture the failed request as well as a successful request to examine differences between the request headers and bodies (if any).
