### ISSUE TITLE
Blazor - RenderFragment's OpenElement changes case

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/aspnetcore#19194]
If we wish to create a dynamic fragment which displays an element and that element is a Blazor component we are stuck. Why?

1. Blazor components must start with a capital letter
2. The OpenElement method is converting camel case input to all lower case output
3. Blazor razor tags are case sensitive

```
 protected RenderFragment DynamicFragment;
 protected override void OnInitialized()
{
            DynamicFragment = builder =>
            {
                builder.OpenElement(1, "MyCompany.Web.Areas.MyPageWhichHasToStartWithCapital");
                builder.CloseElement();
            };
 }
```

results in the tag "<mycompany.web.areas.mypagewhichhastostartwithcapital>" which is not the correct namespace and name of the blazor component.

Please change the OpenElement method to not switch the case, or add an optional boolean parameter to turn this off. Or, add the ability to pass in a component's string namespace/name to OpenComponent.

Thanks

**Comment by javiercn** [comment]
@VR-Architect thanks for contacting us.

If you want to render a component the right api to use is OpenComponent.

Hope that helps.
