### ISSUE TITLE
Support IAsyncDisposable in razor components

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#19197]
In order to dispose a razor component in blazor, I need to do some js side cleanups e.g. remove stored DotNetObjectReference from an array and remove some js event listeners.
The js runtime only supports async invoke methods.

One easy solution would be to support IAsyncDisposable in razor components and do the cleanup and disposal of the DotNetObjectReference as part of the async disposal.

**Comment by campersau** [comment]
Looks like a duplicate of https://github.com/dotnet/aspnetcore/issues/9960

**Comment by msschl** [comment]
Thanks @campersau. Closing...
