### ISSUE TITLE
In Blazor WebAssembly lifecycle methods are called on components with AuthorizeAttribute when the AuthorizationState changes to not authorized

### ISSUE THREAD

**Issue by bradymarston** [dotnet/aspnetcore#19200]
### Describe the bug
I have a component tagged with the [Authorize] attribute. Everything works as expected as far as navigation is concerned, but when I "sign out" all the lifecycle methods except for OnAfterRender are called. Is it necessary to navigate away from any page that requires an authorized user before executing the sign out logic?

My OnInitialized method assumes an authenticated user. Do I need to check for this condition inside the method? That seems redundant with the [Authorize] attribute.

### To Reproduce

The steps to getting WebAssembly authorization up and running are covered elsewhere. After that, create a component with an [Authorize] attribute and write to the console in the OnInitialized lifecycle method. Navigate to the component you created and then sign out. The console is written to both when you navigate to the component and when you sign out.

The only way this seems like it could be my fault is if I'm signing out incorrectly, but if this doesn't work, I don't see how that isn't a bug.

Relevant logic from my AuthenticationStateProvider:
``` C#
        private AuthenticationState authenticationState;
        private static AuthenticationState newUnauthenticatedState = new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity()));

        public async Task SignOutAsync()
        {
            await _http.PostAsync(_options.LogoutUrl, null);
            authenticationState = newUnauthenticatedState;
            NotifyAuthenticationStateChanged(GetAuthenticationStateAsync());
        }

        public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            if (authenticationState is null)
            {
                await ServerRefreshUserInfoAsync();
            }

            return authenticationState;
        }
```

I'd be happy to know that I'm doing this wrong, but it really seems like a bug to me.

**Comment by zbecknell** [comment]
Hi Brady, I'm curious how your services registrations look.  Would you mind showing how you're registering your custom `AuthenticationStateProvider`?

**Comment by zbecknell** [comment]
Nevermind about your registrations, @bradymarston, I found it in your repos.  I created a reproduction project where I attempted to find the same problem:

https://github.com/zbecknell/BlazorAuthRepro

I was unable to see logging occur when signed out -- the FetchData page is my protected page.

If you want to check it out or provide your own repro code, that'd help us find the issue.

**Comment by bradymarston** [comment]
This is my extension method that registers the service (I call it with `useAsyncService` set to false in the code I'm having the problem with):

``` C#
public static IServiceCollection AddWebAssemblyAuthenticationService<TCredential>(this IServiceCollection services, Action<ClientAuthenticationOptions> setupAction, bool useAsyncService = false)
{
    services.AddAuthorizationCore();

    if (useAsyncService)
        services.AddSingleton<IAuthenticationService<TCredential>, AsyncAuthenticationService<TCredential>>();
    else
        services.AddSingleton<IAuthenticationService<TCredential>, AuthenticationService<TCredential>>();

    services.AddSingleton(sp => (AuthenticationStateProvider)sp.GetRequiredService<IAuthenticationService<TCredential>>());

    if (setupAction != null)
    {
        services.Configure(setupAction);
    }

    return services;
}
```

You can find the whole authentication service package here: https://github.com/bradymarston/ShadySoft.Blazor.WebAssembly.Authentication

My application code isn't on GitHub and I don't have access to it right now, but I'm pretty sure that this is the only authentication-related registration I make in my `Program.cs` file. Also, seeing that new Blazor WebAssembly templates are coming with authentication built in, I've decided to halt development on this for now.

**Comment by bradymarston** [comment]
To be clear, `OnAfterRender`/`OnAfterRenderAsync` is the only lifecycle method that _isn't_ being called when I sign out. In your example code, that's the only place I saw logging happening. I can upload my code to GitHub and direct you to the relevant sections when I get back in front of my development computer. Thanks for looking into this!

**Comment by zbecknell** [comment]
Ah, yeah, I reread and misunderstood you as meaning that was the lifecycle method with the problem.  I originally had the log statement in the `OnInitializedAsync()` method, which produced the same results -- no logging when desired (unauthorized).

I updated to include more logging but still couldn't reproduce.  Hopefully refactoring with the official WASM auth template helps you out!

**Comment by bradymarston** [comment]
I reproduced the issue using your code and found that it's in the way I edited `MainLayout`. I want to hide the `NavMenu` when not logged in and I use an `AuthorizeView` component in `MainLayout` to achieve that. Is this not a supported use case?

``` HTML
<AuthorizeView>
    <Authorized>
        <div class="sidebar">
            <NavMenu />
        </div>

        <div class="main">
            <div class="top-row px-4">
                <a href="javascript:void(0)" @onclick="@Auth.SignOut" class="ml-md-auto">Sign Out</a>
                <a href="http://blazor.net" target="_blank" class="ml-md-auto">About</a>
            </div>

            <div class="content px-4">
                @Body
            </div>
        </div>
    </Authorized>
    <NotAuthorized>
        <div class="content px-4">
            <a href="javascript:void(0)" @onclick="@Auth.SignIn" class="ml-md-auto">Sign In</a>
            @Body
        </div>
    </NotAuthorized>
</AuthorizeView>
```

The steps are to sign in, navigate to "Fetch Data" and sign out. Thanks.

**Comment by zbecknell** [comment]
Excellent!  Thanks for reproducing it.  The problem seems to be arising from two `@Body` instances in the same page.  I would suggest removing the `@Body` in `<NotAuthorized />` and having some custom markup/component to display there instead.

The team can attest to whether this counts as a bug or not, but at least you could have a workaround that's satisfactory and can maybe get you back up and running.

**Comment by bradymarston** [comment]
Wanting to be able to display routed content when the user is not logged in (registration, password reset, etc.), this was the cleanest way I could come up with to get the behavior I desired. I actually have a login form component in the `NotAuthorized` segment of my `AuthroizeRouteView` in the `App` component.

Automagically, the login form displays when needed, and goes straight to the desired page without any redirect urls or anything. It was all super clean and smooth until this hiccup. I can see how my intentions may be unsupported though.

If I end up needing it, my likely workaround will be to check for an authenticated user at the top of my lifecycle methods that need one and just skip all the logic if there isn't one available.

**Comment by SteveSandersonMS** [comment]
Thanks for clarifying the situation, @bradymarston! Yes, having two different `@Body` rendering paths means the diffing system can't know that the old and new render outputs are meant to be logically the same, hence it has to recreate the output.

If you just want to hide `NavMenu` when the user is logged out, consider wrapping the `<AuthorizeView>` around just that part of the render output, e.g.:

```razor
<AuthorizeView>
    <div class="sidebar">
        <NavMenu />
    </div>
</AuthorizeView>

... now rest of layout goes here, including a single @Body
```
