### ISSUE TITLE
ASP Net Core don't follow project build rules when running Publish on a web project

### ISSUE THREAD

**Issue by Sausbolle** [dotnet/aspnetcore#19212]
### Describe the bug
When using the following build rule in the .csproj file
```
  <ItemGroup>
    <None Include="wwwroot\test\**\*.placeholder" CopyToOutputDirectory="PreserveNewest" />
    <None Include="test\**\*.placeholder" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
```
When building normal (`dotnet build -c Debug`) the rule is adhered to and only includes the ‘.placeholder’ files from those directories.

But when doing an Publish (`dotnet publish -c Release`) the `wwwroot\test\**\*.placeholder` rule is ignored and treated as `wwwroot\test\**` instead. The `test\**\*.placeholder` rule is adhered to as it is suppose to when running Publish, so it seams like this is something that only affects rules set on the `wwwroot` directory (not that I have explored it too much).

### To Reproduce
- Create an ASP NET Core Web app and create the directories
`./wwwroot/test`
`./test`
- In these two directories add some subdirectories with a blak file named `.placeholder` and a random other file.
- Edit the project file adding the above `<ItemGroup>`
- Compile debug (`dotnet build -c Debug`)  
- Compile release (`dotnet publish -c Release`) 
- In the `/bin/Debug/netcoreapp3.1/wwwroot/test/subdir` you will only find the `.placeholder`
- In the `/bin/Release/netcoreapp3.1/publish/wwwroot/test/subdir` you will find all the files that were in `./wwroot/test/subdir`

### Further technical details
- ASP.NET Core version 3.1.101
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`Microsoft Visual Studio Community 2019 Version 16.4.5`

- Test project
[BugTest_Publish_Web.zip](https://github.com/dotnet/aspnetcore/files/4233433/BugTest_Publish_Web.zip)

_Note: I initially created a bugreport in the Developer Community, but thought this perhaps were more appropriate place_

**Comment by javiercn** [comment]
@Sausbolle thanks for contacting us.

This is likely due to how we handle assets in the wwwroot folder. Those are considered static web asseets and are handled differently, if you turn off static web assets in your project (by using `<EnableStaticWebAssets>false</EnableStaticWebAssets>` it should behave as you expect.

**Comment by Sausbolle** [comment]
Thanks for reply and explanation.

I might be doing something wrong that causes the behavior described below. And the simple solution is to manually create the directories after Publish (I didn't find an setting that only created the directories instead of copying the content).

This is in no stretch of the imagination an important thing, but if possible I would like to suggest a change to this.
The project I use it in uses some folders for uploading files (that becomes static assets in the wwwroot on webserver). When running Debugging from VS the files uploaded gets placed in `./wwwroot/testfolder` and not the `./bin/Debug/....` which isn't a bad thing as it makes doing a clean build easier (constancy with database and all that on dev computer).
But it introduces a problem when doing a Publish as it copies all these files to the publish output directory.
It might be laziness on my part and bad coding practice, but as the upload folders is an required part I don't check if they exist in the code I assume they exist (exception thrown if they don't). I could as stated above either manually create them after publish or created an check in code to see if they exist and create if not there.

**Comment by javiercn** [comment]
@Sausbolle Thanks for the additional details.

You will be more successful simply mapping a second static files middleware to serve the additional folder where you are uploading the files, that way you won't have to deal with any build/runtime trouble.
