### ISSUE TITLE
ModelBinding fails when queries are formatted jQuery style

### ISSUE THREAD

**Issue by dhazel** [dotnet/aspnetcore#19220]
### Describe the bug
Http requests fail that format parameters of collections in bracket-form (ie: `https://example.com?sort[0][field]=myfield&sort[0][dir]=desc`). These parameters are silently skipped during model binding, while the corresponding dotted-form queries succeed (ie: `https://example.com?sort[0].field=myfield&sort[0].dir=desc`).

Note: this bug causes jQuery ajax calls to fail.

~
The `Microsoft.AspNetCore.Mvc.ModelBinding.PrefixContainer` does not normalize prefixes to dotted-form when they are stored in the `_sortedValues` sorted array. [The comment here](https://github.com/dotnet/aspnetcore/blob/147be384eea84a8152d63c5132570bb02855ac90/src/Mvc/Mvc.Core/src/ModelBinding/PrefixContainer.cs#L11) indicates that prefixes should be normalized; however, that may not be the best solution to this bug.

### To Reproduce

Clone and run the following solution: https://github.com/dhazel/aspnetcore-bug-19220

### Further technical details
- ASP.NET Core version: **3.1**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: **VisualStudio 2019, version 16.4.4**
- Include the output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@dhazel thanks for contacting us and for the associated PR.

We'll look into this issue and get back to you.

**Comment by dhazel** [comment]
@javiercn thanks.

My pull request is likely not adequate. I have added notes to it. I would do more, but my resources are limited.

**Comment by dhazel** [comment]
I have clarified the bug title and added a simple repo that reproduces it.

**Comment by pranavkm** [comment]
You will need to add `JQueryQueryStringValueProviderFactory` to the value provider list if you need to bind jQuery-params style binding from query string:

```C#
services.AddControllers(options => options.ValueProviderFactory.Add(new JQueryQueryStringValueProviderFactory()));
```

**Comment by dhazel** [comment]
Excellent! Thank you @pranavkm

**Comment by dhazel** [comment]
@pranavkm , your code has a typo. It should be:

```C#
services.AddControllers(options => options.ValueProviderFactories.Add(new JQueryQueryStringValueProviderFactory()));
```
