### ISSUE TITLE
Upgrade to the latest Bootstrap version

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#19225]
There were several breaking changes in Bootstrap 4 (from Bootstrap 3) which we also need to react to as part of this upgrade.

This issue will also be used to track all related work to the bootstrap 5 update:
- [ ] identity ui/scaffolding
- [x] project template fixes

**Comment by KKacer** [comment]
I think Bootstrap was past!
By the all recent changes and news in CSS, there is no need for bootstrap.
tying more and more the platform and components to a 3rd party library will add more time and hassle for people who try to make more pure or more customized things.
I believe BootStrap was past though Blazor can be the future.
So if possible while you try to consider the needs of web newbies, consider 1 extra scenario without Bootstrap, Materialize, and font-awesome, Jquery things, which none of them are standards, they may make a buzz for a period and then be gone, and each person can have it's own choice or custom scenario.
So personally I suggest not invest on bootsrap much, just may be there as an option, instead invest more on the standards. Like considering CSS Grid, FlexBox, ...

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback @KKacer.
We'll definitely think about these points you've mentioned when we will get to handling this issue.

**Comment by mkArtakMSFT** [comment]
Related https://github.com/dotnet/aspnetcore/issues/23017

**Comment by HaoK** [comment]
Met today and we agreed on a plan of record for identity ui for 6.0:
- Both V4/V5 pages and assets will again live in the identity UI package, just like before with V3/V4
- We will need to come up with a new page model convention to make this work (will sync with @pranavkm )
- For 7.0 we can revisit and see if we can switch to UI.Bootstrap5/BootstrapX dlls but too risky to change this late for 6.0

cc @danroth27 @blowdart @DamianEdwards @javiercn @pranavkm @mkArtakMSFT @adityamandaleeka

**Comment by HaoK** [comment]
Bootstrap 5.0.2 has been merged in https://github.com/dotnet/aspnetcore/pull/34052

Still need follow up PR to add back the ability to switch back to V4

**Comment by HaoK** [comment]
@deepchoudhery we have updated to bootstrap5 for net6.0 by default, can you help identify what changes need to go into https://github.com/dotnet/Scaffolding/tree/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/wwwroot for the scaffolding side of things?

**Comment by deepchoudhery** [comment]
Yes, I'll add an item to track for 6.0-rc1. I'll follow up soon.

**Comment by DamianEdwards** [comment]
@HaoK just used the updated templates for the first time and noticed a few spacing/margin issues. Are these known and being fixed? e.g. 
![image](https://user-images.githubusercontent.com/249088/128770070-e4f3a70a-45cb-4903-9941-0e9a6794c3f8.png)

**Comment by HaoK** [comment]
Yeah @blowdart just went over them for me, we think its just a matter of removing the form-group, I will have a PR open for this today soon, I'll add you to the review

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/35197

**Comment by HaoK** [comment]
Looks like @deepchoudhery merged the scaffolding side of things today 🎉
