### ISSUE TITLE
How to kebab-case endpoints with Web API

### ISSUE THREAD

**Issue by t-hart** [dotnet/aspnetcore#19233]
I've been trying to convert the generated endpoints of an ASP.NET Core 3.1 web api from PascalCase to kebab-case, but I can't figure out how to do it. Is there any documentation on how you do it with `useEndpoints`?

**Solution?**: while writing up this issue and documenting what I've tried, I did find a solution for this. From the [documentation for Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1), I found that I can use `AddMvc` and add an outbound parameter transformer.

Is this the 'official'/'correct' way to get this done? It seems strange having to add `AddMvc` to a web api, when we didn't use this before. Especially when you have `AddRouting` which also lets you configure options. However, for the `AddRouting` method, I could only lowercase everything, not transform it arbitrarily.

# What I've tried

I started my search based on [this ASP.NET Core 2.2.0-preview3](https://devblogs.microsoft.com/aspnet/asp-net-core-2-2-0-preview3-now-available/#routing) release post, which suggests using parameter transformers and constraint maps. The example in the article, however, uses seems to be using ASP.NET Core MVC, and gives this example:

```csharp
routes.MapRoute(
    name: "default",
    template: "{controller=Home:slugify}/{action=Index:slugify}/{id?}");
```

I've been looking for information on this, but I can't seem to find out what the `routes` variable refers to here or where this snippet would go.

Furthermore, the [migration docs for 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#routing-startup-code) say to use `UseRouting`, and to replace `UseMvc` with `UseEndpoints`, so if the above code is related to MVC (which it seems to be from my understanding), then it's outdated anyway.

However, using parameter transformers seems like it would be a good idea. The [token replacement in route templates](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#use-a-parameter-transformer-to-customize-token-replacement) section in the routing article says to use `AddMvc` and add the transforming. As mentioned above, this did indeed solve the issue, but it doesn't feel 'right'. Is there a way to apply the transformation in `AddRouting` instead?

I've also been digging through the [documentation for Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1) without any more luck.

This seems to be a similar case to [this issue](https://github.com/aspnet/Routing/issues/861), but that issue seems to use MVC routes and the aforementioned `routes.MapRoute` method.

**Comment by javiercn** [comment]
@t-hart thanks for contacting us.

You don't need to do `services.AddMvc` for it, you can simply use `services.AddControllers` if that's what you are interested in.

It is likely you can configure this at the endpoint routing level if you are not even using controllers.

**Comment by t-hart** [comment]
@javiercn, thanks for the response.

Do you mean that you can use `services.AddControllers` to automatically convert endpoint names from `PascalCase` to `kebab-case`? If so, how? I couldn't find any documentation for it. 

Just so that there is no confusion: what I want is for all endpoints exposed by the application to automatically use `kebab-casing` rather than `PascalCasing`, i.e. `api/v1/my-endpoint` instead of `api/v1/MyEndpoint`. 

By using `services.AddMvc`, I was able to add a `RouteTokenTransformerConvention` to the achieve just this, but I wasn't able to  do it with `AddControllers`. It's quite possible that I've missed something, so if there's a way to achieve this, I'd really appreciate an example or some documentation to look at, if you would be so kind  as to point me in the right direction.

Thanks!

**Comment by javiercn** [comment]
> By using `services.AddMvc`, I was able to add a `RouteTokenTransformerConvention` to the achieve just this, but I wasn't able to do it with `AddControllers`. It's quite possible that I've missed something, so if there's a way to achieve this, I'd really appreciate an example or some documentation to look at, if you would be so kind as to point me in the right direction.

What I meant is that you didn't necessarily need to use `AddMvc` but  that `AddControllers should suffice`.

I would suggest you grab the working solution you have with AddMvc and from there simply try to switch that one line to AddControllers instead (I imagine you have `endpoints.MapControllers()` or similar in your startup.

**Comment by t-hart** [comment]
Aha! You're right. Not sure how I missed that earlier, but it's probably because most other routing changes go in the `AddRouting` method. Thanks for the guidance. 

Is this shown in any of the examples anywhere? It strikes me as a pretty common use case and the fact that it took me several hours to find a solution (which wasn't even the "right" one) makes me think that it could be advertised a bit better. 

Thanks again for the help; it's very much appreciated.
