### ISSUE TITLE
Replace Identity Cookies with JWT

### ISSUE THREAD

**Issue by umar-ulabs** [dotnet/aspnetcore#19239]
I was wondering if it is possible to replace cookie authentication with jwt. I already removed everything related to cookies, but I lost control over most of the SignInManager. For instance, the following code does not work anymore 
(httpcontext.User.IsInRole(DefaultRoles.Administrator)) && httpcontext.User.Identity.IsAuthenticated. So currently I am manually validated the JWT token. Is the a way I can replace cookies and use jwt and I have httpcontext.User.Identity.IsAuthenticated or options.Lockout = new LockoutOptions()  like things working. Thank you

**Comment by blowdart** [comment]
I am a little confused. Where are you getting the JWT from? How are you using it? Are you writing a SPA or an API?

**Comment by umar-ulabs** [comment]
Thanks for prompt reply. Its both SPA and API. SPA uses jwt to do CRUD. Everything seems working fine. In Startup.cs :  

     
                services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
                {
                    options.Password.RequireDigit = false;
                    options.Password.RequiredLength = 10;
                    options.Password.RequireNonAlphanumeric = false;
                    options.Password.RequireUppercase = false;
                    options.Password.RequireLowercase = false;
                    options.Lockout = new LockoutOptions()
                    {
                        AllowedForNewUsers = true,
                        DefaultLockoutTimeSpan = TimeSpan.FromSeconds(20),
                        MaxFailedAccessAttempts = 5
                    };
                })
                  .AddEntityFrameworkStores<MyDbContext>()
                  .AddDefaultTokenProviders();

                services.Configure<SecurityStampValidatorOptions>(options =>
                {
                    // enables immediate logout, after updating the user's state.
                    options.ValidationInterval = TimeSpan.FromSeconds(60);
                });
                
 services.AddAuthentication(o =>{
                    o.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    o.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    o.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                 .AddJwtBearer(cfg =>
                 {
.....and the rest});

Also, having [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)] on a controller, the following works  _userManager.GetUserAsync(HttpContext.User); Mostly the Cookie specific functionalities are not working like login attempts/lockouts

**Comment by blowdart** [comment]
That makes sense, because sending a JWT is not a login attempt or a lockout, whatever is issuing the JWT is the login point, as soon as you get a JWT you're logged in, nothing happens after that. You need to look to your JWT issuing code.

**Comment by umar-ulabs** [comment]
Essentially manually updating aspnetUsers table in database and doing checks on each login for lockouts for example, right ?

**Comment by blowdart** [comment]
Yup. Of course you could just use Identity Server, which uses asp.net identity as its user store, issues jwts and probably does everything you want and more :)

**Comment by umar-ulabs** [comment]
Yes, sounds like that might be the only option, else updating or maintaining identity would be big pain.

**Comment by blowdart** [comment]
Indeed it would!

**Comment by blowdart** [comment]
Closing as I believe you have the answer you need, "Use identity server"
