### ISSUE TITLE
Automatically generate API documentation

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/aspnetcore#19231]
Develop on previous VS tools.We've got XML comments on documents, and I'd like to have a choice on that. A lot of opportunities now exist for WebApi development projects that are split before and after, if it's able to right-click generate a help document similar to Swagger's *.json standard document for open source projects, or more customizable, without reference to third-party libraries.It's like the build solution is packaged.It would be nice if the file could be published to a server dedicated to processing documents

**Comment by javiercn** [comment]
@JHeLiu thanks for contacting us.

We recommend you use something like https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-3.1 to document your APIs.

I would recommend you use the [Request a feature](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#suggest-a-feature) option in Visual Studio if you want to see any tooling specific improvement in this area.
