### ISSUE TITLE
 appBuilder.UseClientSideBlazorFiles<TType>() - non generic equivalent?

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#19234]
### Is your feature request related to a problem? Please describe.
In my multi tenant application, new tenants are created dynamically.
I previoulsy had a single blazor SPA. Now I have two blazor SPA's. I'd like the ability to control which blazor SPA is served up for each tenant using configuration. In future I might also allow new blazor SPA's to be registered with the host at runtime, to participate in this Tenant --> SPA mapping.
However the current provided method: `appBuilder.UseClientSideBlazorFiles<TType>();` requires a Type to be provided at compile time. 
Can you consider providing a non generic equivalent to this API's i.e `appBuilder.UseClientSideBlazorFiles(someTypeFromASpa);`

### Describe the solution you'd like
Can you consider providing a non generic equivalent to this API's i.e `appBuilder.UseClientSideBlazorFiles(someTypeFromASpa);`

I've had to copy the existing UseClientSideBlazorFiles and create my own equivalent at present - but there is logic in there like searching for a particular file output from a blazor build - stuff that might change in future and so this is overhead for me to maintain and a potential source of errors in future if stuff changes.

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

That method will be gone in the next preview as we've changed the way we build Blazor. Blazor applications will just be static files on disk moving forward so you can choose what/when to serve them

**Comment by javiercn** [comment]
> I previoulsy had a single blazor SPA. Now I have two blazor SPA's. I'd like the ability to control which blazor SPA is served up for each tenant using configuration. 
* Each SPA will go in their own url space, for example "/Spa1", "/Spa2". You can decide when/how to serve the entry point for those SPAs and how you set the base path.

> In future I might also allow new blazor SPA's to be registered with the host at runtime, to participate in this Tenant --> SPA mapping.
* You should be able to do this simply by changing the static files middleware to serve the appropriate paths

**Comment by javiercn** [comment]
I'm closing this as there's no further action for us here.

**Comment by dazinator** [comment]
@javiercn - Ok I see, thank you. I'm looking forward to the new way.
