### ISSUE TITLE
How to access the dynamic DOM element reference in Blazor?

### ISSUE THREAD

**Issue by PiramanayagamR** [dotnet/aspnetcore#19237]
I have an requirement to get the reference of dynamic element. For example, I have below code.
```
<ul>
    @foreach (var todo in todos)
    {
        <li><span>@todo.Title, </span><span>@todo.Title</span><button @onclick="EditToDo">Edit</button></li>
    }
</ul>

<input placeholder="Something todo" @bind="newTodo" />
<button @onclick="AddTodo">Add todo</button>
@code {
    private IList<ToDo> todos = new List<ToDo>();
    private string newTodo;
    private void AddTodo()
    {
        if (!string.IsNullOrWhiteSpace(newTodo))
        {
            todos.Add(new ToDo { Title = newTodo });
            newTodo = string.Empty;
        }
    }
    private void EditToDo()
    {
    }
}
```
If I click the edit button then I need to get the reference of sibling span elements.
I want to do some actions in that span elements. 

Could you please tell how to achieve this without JS introp?

**Comment by javiercn** [comment]
@PiramanayagamR thanks for contactign us.

We're not sure what you are trying to accomplish here, could you provide more details on what are you trying to accomplish by accessing the sibling elements?

You can take a hold of any html element by using an ElementReference, but doing anything with it will require JS interop.
https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1#capture-references-to-elements
