### ISSUE TITLE
DistributedSession private methods and fields make it really hard to inherit from.

### ISSUE THREAD

**Issue by riddlemd** [dotnet/aspnetcore#19243]
### Is your feature request related to a problem? Please describe.
My organization wants to encrypt session data regardless of backing IDataCache, I looked into writing a custom EncryptedDistributedSessionStore and EncryptedDistributedSession . This would be incredibly easy if Serialize and Deserialize were protected virtual and not private methods in DistributedSession. As it stands now, we basically have to re implement almost all of the existing logic due to private scope of field and methods.

### Describe the solution you'd like
Review DistributedSession and rescope fields to protected properties where it makes sense and make key methods protected virtual to allow extensibility.

**Comment by javiercn** [comment]
@riddlemd thanks for contacting us.

@anurse who's the expert on this area?

**Comment by JunTaoLuo** [comment]
@Tratcher is most familiar with Session but from what I recall, the idea is that `ISession` is the API contract for how session stores should behave. Serialize and Deserialize are internal implementation details of `DistributedSession` and are not designed to be extensible.
