### ISSUE TITLE
Migrating pieces of dotnet/extensions to dotnet/aspnetcore

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#19254]
I don't think I ever created an issue to track this work so I'll list out the work items below:

- [x]  https://github.com/dotnet/aspnetcore/pull/19033 Move projects to aspnetcore:
M.E.FileProviders.Embedded
M.E.FileProviders.Embedded.Manifest.Task
M.E.Configuration.KeyPerFile
M.E.Localization
M.E.Localization.Abstraction
M.E.ObjectPool
M.JSInterop
M.JSInterop.JS
M.E.WebEncoders
M.E.Diagnostics.HealthChecks
M.E.Diagnostics.HealthChecks.Abstractions
M.A.Testing
Shared sources
- [x] Ensure we didn't miss any commits during the merge.
- [x] Ensure currently open PRs are moved to aspnetcore: https://github.com/dotnet/extensions/pulls?q=is%3Aopen+is%3Apr+label%3Asource-migrated-to-aspnetcore
- [x] https://github.com/dotnet/extensions/pull/2974 Remove those projects from Extensions except M.A.Testing and Shared sources
- [x] https://github.com/dotnet/aspnetcore-tooling/pull/1620 Remove uses of removed extensions packages in aspnetcore-tooling
- [x] Investigate splitting of Logging.Testing project
  - Removing from extensions https://github.com/dotnet/extensions/pull/3040
  - Moving LoggedTest to aspnetcore https://github.com/dotnet/aspnetcore/pull/19545
- [x] Migrate relevant issues 
- [x] Post announcement
- [x] Ensure Interop.JS artifacts published correctly
  - Tracking separately in https://github.com/dotnet/aspnetcore/issues/19300
- [x] Ensure our docs are up to date (such as ops, readmes, etc) This will likely be updated as we notice errors in documentation instead.
- [x] Make sure DARC subscriptions are correct
- [x] Address https://github.com/dotnet/extensions/pull/3091#discussion_r401915600
- [x] Address issues relating to the removed package dependencies from extensions https://github.com/dotnet/aspnetcore/pull/20300/commits/ccf4cd02ba7a4104136594766bcfe455d72dfd6f#r402145057 see discussion at https://github.com/dotnet/aspnetcore/pull/20300#discussion_r402145057 Addressed by https://github.com/dotnet/extensions/pull/3179

**Comment by JunTaoLuo** [comment]
@anurse some of the remaining work will involve your input (such as triage and issue moving) so I'm assigning you as well.

**Comment by leus** [comment]
Sorry if I'm wasting your time - I cannot find a discussion regarding this move. Is there an issue where I can find the rationale or discussion prior to this move? (I use some of the affected components in a very critical piece of infrastructure, so I wonder what's going on.) Thanks.

**Comment by anurse** [comment]
We’re getting an announcement put together shortly! This is purely about where we build/maintain the code though. All the packages are continuing to ship in the same places (NuGet, for example) and same supported frameworks as before.

**Comment by JunTaoLuo** [comment]
The announcement has been posted.

**Comment by smashedapples20** [comment]
Where is the announcement? Do you have a link?

**Comment by anurse** [comment]
Oops! Thanks for the reminder @smashedapples20 :). We posted the announcement but didn't link it in here. It's here: https://github.com/aspnet/Announcements/issues/411

**Comment by JunTaoLuo** [comment]
Announcement for breaking changes was made in https://github.com/aspnet/Announcements/issues/415.

**Comment by NullEntity** [comment]
@JunTaoLuo I was looking for source for Config.Binder. It's at extensions/src/Configuration/Config.Binder/ in the last released tag, then extensions/src/Configuration only has Config.NewtonsoftJson on master. It doesn't look like it got migrated going through the aspnetcore commits. It looks like some stuff may have been removed from the extensions repo that shouldn't have been.
