### ISSUE TITLE
File read/write issue with NFS volume mount in kubernetes 

### ISSUE THREAD

**Issue by ram62836** [dotnet/aspnetcore#19258]
Hi There, 

We are mounting a nfs volume to asp core docker container and trying to read/write files. By SSH into container we were able to read/write files and list the files, so the volume mount is successful. While reading or writing from code, application just hangs. While trying to create a file and write, it creates the file, but hangs while writing. Tried with asp core 2.2 and 3.1 found no luck. There are no exceptions thrown by the application or docker container. Some other application written in Java is able to read write from the same nfs volume. There are restricted permissions on the folder we are accessing. 

Help is highly appreciated. 

Thanks, 
Ramesh R

**Comment by javiercn** [comment]
@ram62836 thanks for contacting us.

We believe there is nothing specific to ASP.NET Core in this question. In order for you to get a faster and better answer I suggest you file this issue directly in the [dotnet/runtime](https://github.com/dotnet/runtime) repo as they'll be better suited to help you.

@richlander Can you route this to the relevant folks?

**Comment by ram62836** [comment]
@javiercn Thanks for the lead. Will post this into run time repo.

**Comment by davidfowl** [comment]
@ram62836 did you figure this out?

**Comment by ram62836** [comment]
Not really, team had that working with Java and Python. So they completed the service using one of them.
The persistent volume mount (NFS) issue is observed only with AspCore container. 
Got some other use case to get this working, will dig in more in the coming week.

**Comment by ram62836** [comment]
I believe it is an issue with the storage provider setup. Kubernetes storage class with vSphere and CSI driver worked without any changes to our code. The issue is with nfs volume mount, didn't really analysed the issue with nfs volume mount. Thanks

**Comment by JunTaoLuo** [comment]
This issue looks like it's in the runtime layer of the stack so it doesn't make sense to track it here. I see the related issue https://github.com/dotnet/runtime/issues/32738 was closed so I suggest reopening it in order to follow up with them or file a new issue.
