### ISSUE TITLE
Add a new non-TLS endpoint to the gRPC template

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#19250]
The only endpoint in the gRPC template is a TLS-enabled endpoint. As part of our desire for a better experience on macOS which doesn't have server-side ALPN and ergo HTTP/2 over TLS, we should add another endpoint to the template.

This in conjunction with https://github.com/grpc/grpc-dotnet/issues/782 should greatly improve the experience on macOS.

cc @JamesNK

**Comment by blowdart** [comment]
Umm

https://grpc.io/docs/guides/auth/

_Google will not allow connections without SSL/TLS, and most gRPC language implementations will not let you send credentials on an unencrypted channel._

If you do this you must be clear this is super unsupported and out of compliance.

**Comment by JamesNK** [comment]
We have a big warning for macOS situation - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1#unable-to-start-aspnet-core-grpc-app-on-macos

**Comment by shirhatti** [comment]
> Google will not allow connections without SSL/TLS, and most gRPC language implementations will not let you send credentials on an unencrypted channel.

Neither do we.

https://github.com/grpc/grpc-dotnet/blob/db7d128f59e52dc7430740fdeb9acb30e0b0fa64/src/Grpc.Net.Client/Internal/GrpcCall.cs#L711-L736
