### ISSUE TITLE
System.Text.Json.JsonException

### ISSUE THREAD

**Issue by ALMLAMBO** [dotnet/aspnetcore#19261]
I want to ask on .net core 3.1 why every time I make a post request it throws System.Text.Json.JsonException.

**Comment by ram62836** [comment]
Please add more detail of your issue. Simple post shouldn't throw any such error. We are using 3.1 and found no such issue yet. Validate your json which you are trying to post. Could be some issue with your config in the startup.cs file.

**Comment by ALMLAMBO** [comment]
This is code which makes API call.
```
await client.PostJsonAsync<AddRepairBindingModel>
			("https://localhost:44355/api/repairs/create-repair", repair);
```

This is code for uploading to firebase.

```
await db.RunTransactionAsync(async transaction => {
				UpdateRepairId(serviceName, repair.RepairId);
				await repairsColRef.AddAsync(repairModel);
			});
```

**Comment by ram62836** [comment]
client.PostJsonAsync - share this post action method code.

**Comment by ALMLAMBO** [comment]
This is in the controller.

```
service.UploadRepair("Value", repair);
```

This is logic in the service.

```
FirestoreDb db = connection.GetFirestoreDb();

			CollectionReference repairsColRef = db
				.Collection("service-repairs");

			DateTime endOfWarranty = new DateTime(
				repair.BoughtAt.Year + repair.WarrantyPeriod / 12,
				repair.BoughtAt.Month, repair.BoughtAt.Day);

			repair.InWarranty = 
				DateTime.UtcNow >= repair.BoughtAt &&
				DateTime.UtcNow <= endOfWarranty ? true : false;

			Repair repairModel = new Repair(repair);

			await db.RunTransactionAsync(async transaction => {
				UpdateRepairId(serviceName, repair.RepairId);
				await repairsColRef.AddAsync(repairModel);
			});
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by rnielikki** [comment]
I found the JsonException is thrown when received data is empty. I tested with EF Core,
When the empty DB result (null) is passed to controller, the controller returns 204 (No content) as result. 204 is in the 2xx range so it doesn't throw error [in this line](https://github.com/dotnet/aspnetcore/blob/01c1d0613ec40c6bc12bdbdebfe7b03bd878868a/src/Components/Blazor/Http/src/HttpClientJsonExtensions.cs#L106). But data is still empty, so it's not valid JSON. So it throws JSON exception.

**Comment by javiercn** [comment]
If you expect an empty body you should not try to read it as JSON.

The APIs in the package you mention are experimental and will likely go away in future versions of Blazor in favor of more general purpose HttpClient APIs.

I'm closing this issue as there's nothing for us to do here.
