### ISSUE TITLE
[Kestrel] Cannot access a disposed object. Object name: 'System.Net.Sockets.Socket'.

### ISSUE THREAD

**Issue by Im5tu** [dotnet/aspnetcore#19267]
### Describe the bug

I've deployed a skeleton application which has an empty health check endpoint so that I can configure the CICD to AWS ECS (EC2). We have the following both System.Runtime & Microsoft.AspNetCore.Hosting event counters sending to DataDog. I noticed the following pattern:

![image](https://user-images.githubusercontent.com/20248180/75098906-8eb5af80-55b3-11ea-822e-1b07dacaae92.png)

Exceptions correlate exactly to the request, but only when it is called by the AWS load balancers. CURL & Chrome requests do not trigger the same behaviour. This application has no logic other than an empty health check & mapping event counters to DataDog, thus serving no traffic at this time.

Here is the exception that we encountered:

![image](https://user-images.githubusercontent.com/20248180/75098785-67aaae00-55b2-11ea-96d3-6d2ac6632bd9.png)

[Click for the full container log - direct to message](https://gist.github.com/Im5tu/dfbdd52f54b5fef072f23031de18a7bb#file-containerlog-txt-L615)

I only managed to find this by adding in the following to my program.cs:

```
AppDomain.CurrentDomain.FirstChanceException += (sender, eventArgs) =>
{
     Console.WriteLine(DateTime.UtcNow.TimeOfDay + " : " + eventArgs.Exception);
};
```

If I didn't notice the accessing a disposed object message, I probably wouldn't have reported.

### To Reproduce

Exceptions are likely triggered on any .Net Core 3.1 app with a mapped health check endpoint running on AWS with AWS's ALB's. Exceptions can only be observed via EventCounters or FirstChanceException handler.

### Further technical details

I have full capabilities to diagnose the container it's running in with `dotnet-dump`/`dotnet-trace`. The container is published in Release mode, key bits from the docker file are:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
ARG app
ARG Version
COPY . /app/
WORKDIR /app/
RUN dotnet publish "/app/src/${app}/${app}.csproj" -c Release --self-contained=true -r alpine-x64 /p:Version=${Version} /p:GenerateDocumentationFile=false

FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine
```

Dockerfile last ran: 2020-02-22T19:30 ish

**Comment by davidfowl** [comment]
The disposed socket error is a red herring, it shouldn't matter. The health check is likely an HTTP/1.0 request (maybe explains the behavior difference between chrome and ALB). That might also explain why it's correlated with requests (HTTP/1.0 is a request per connection).

Where's the ExceptionCount counter coming from? 

I'd be surprised if you were counting first chance exceptions by default. It would be very noisy...

**Comment by Im5tu** [comment]
The exception count is the `exception-count` counter from the `System.Runtime` event source. I agree it's probably going to get noisy when the application actually does things. We will likely add in another one to catch the exceptions that cause us a 500/retry a message. That said, it did help us uncover a performance issue with the dynamo sdk :)

Since the socket disposed error shouldn't matter, i'll close the issue. Let me know if need anything else on this and i'll be happy to help.

In case anyone wants/needs it, this snippet shows the counter incrementing.

```
class Program
{
    static async Task Main(string[] args)
    {
        Process.Start("dotnet-counters", $"monitor -p {Process.GetCurrentProcess().Id}");
        var rnd = new Random();

        for (var i = 0; i < 1000; i++)
        {
            try
            {
                throw new Exception("Test");
            }
            catch (Exception e)
            {
            }
            finally
            {
                await Task.Delay(rnd.Next(25, 150));
            }
        }
    }
}
```

**Comment by davidfowl** [comment]
Let me take a look at the counter
