### ISSUE TITLE
AddRazorRuntimeCompilation.AdditionalReferencePaths Example ?

### ISSUE THREAD

**Issue by NVentimiglia** [dotnet/aspnetcore#19269]
### Describe the bug
Looking for guidance on using AddRazorRuntimeCompilation AdditionalReferencePaths. In my scenario I have two asp.net core 3.1 applications. One project includes the bulk of the project including the controllers, models, and razor views (AbstractProject). The second includes the first as a dependency, and is the run-time application, providing a opportunity for overriding behavior (MainProject).

I noticed that when razor views inside MainProject are modified when running MainProject, AddRazorRuntimeCompilation works correctly. 

When razor vies are modified in AbstractProject when running MainProject, the AddRazorRuntimeCompilation does not work correctly. I need to restart the build to get the views to update.

Here is my configuration

```
 .AddRazorRuntimeCompilation(o =>
                    {
                        var root = new DirectoryInfo(Directory.GetCurrentDirectory());
                        var views = root.Parent.GetFiles("*.cshtml", SearchOption.AllDirectories);
                        foreach (var view in views)
                        {
                            o.AdditionalReferencePaths.Add(view.FullName);
                        }
                    })
```
### To Reproduce

- Create a new dot net core project (A)
- Create a second dot net core project (B)
- Delete most of the files in B, leave only program and the wwwroot files
- Include A into B as a dependency
- Have B run A Statup file

### Further technical details
- ASP.NET Core version 3.1 windows
 Version:   3.1.100

**Comment by pranavkm** [comment]
@NVentimiglia cshtml files are code generated in to cs files and later compiled in to assemblies that get loaded by MVC. `AdditionalReferencePaths` is meant to contribute additional [references](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/reference-compiler-option) when compiling these assemblies. This doesn't look like what you need here.

https://github.com/aspnet/samples/blob/master/samples/aspnetcore/mvc/runtimecompilation/MyApp/Startup.cs#L35-L39 has a snippet of what you would do to get runtime compilation to look at additional directories other than the current executing project.
