### ISSUE TITLE
StateHasChanged Recursively

### ISSUE THREAD

**Issue by hultqvist** [dotnet/aspnetcore#19265]
### Is your feature request related to a problem? Please describe.
I'm trying to implement a live language switcher, where you can change language without leaving the current page or its state. The user might be updating a form should be able to change the language without losing the unsaved changes.

I have a class that supplies the localized strings. By changing its `Language` property I will get different translations from it's other functions.

The problem is that this change is not connected the the component updates.
The new language appear only once each component is updated triggered by other reasons.
After setting a new language I would need to call StateHasChanged on every Component one by one.

Chaining "language-changed" events to every single component seems too much work since it will have to be done for every component.

I don't know if there is a way to iterate over all currently active components.

### Describe the solution you'd like
A single call to `StateHasChangedRecursively()` which will invalidate the component and all child components.

**Comment by javiercn** [comment]
@hultqvist thanks for contacting us.

I believe you can achieve this simply by using a [cascading parameter](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#cryptographic-key-importexport). If you pass in the langugage from the root of you app as a cascading value, any component that needs it can take it in as a parameter and will be updated when you change the value in the root component and every component that receives the parameter will be updated accordingly.

**Comment by hultqvist** [comment]
I've successfully implemented a component that use cascading component to get the current language.

    <Translate Key="Save></Translate>

Can similar be done for attributes?
I assume components can't be rendered into attribute values.

    <input type="submit" value="@Translate.Key("Save")" />
    <input type="submit" value="@InjectedInstance.Key("Save")" />
