### ISSUE TITLE
[Blazor] Blazor swallows exceptions (3.1.0)

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#19271]
When calling a non-existent JS method Blazor swallows the exception.

```
@page "/"
@inject IJSRuntime JSRuntime

<button @onclick=@(() => TryToInvokeJS1())>This throws the exception</button>
<button @onclick=@(() => TryToInvokeJS2())>This swallows the exception</button>

@code{
	public async ValueTask TryToInvokeJS1()
	{
		await JSRuntime.InvokeVoidAsync("ThisDoesNotExist");
	}

	public ValueTask TryToInvokeJS2()
	{
		return JSRuntime.InvokeVoidAsync("ThisDoesNotExist");
	}
}
```

This also happens for other exceptions. For example, when calling an existent JS method and passing a type that System.Text.Json cannot serialize (such as a `Dictionary<int, int>`).

**Comment by richbryant** [comment]
I'd just like to add that this code throws no exceptions *at all* in Client-Side Blazor.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
The issue is actually caused by your code because you don't wait for the handler result when you call it: 

<button @onclick="TryToInvokeJS1">This throws the exception</button>
<button @onclick="TryToInvokeJS2">This swallows the exception</button>

**Comment by richbryant** [comment]
neither of them throws in blazor-wasm.  Is this by design?

**Comment by mrpmorris** [comment]
I understand why my code doesn't see the exception, but wasm is supposed to have a catch-all handler that logs to the console and shows a message on the screen - and neither of those are happening so I think it's a bug.
