### ISSUE TITLE
NuGet: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation - net core 3.1 - not working

### ISSUE THREAD

**Issue by RT77developer** [dotnet/aspnetcore#19270]
Hi, I did everything that is written in this post:

https://docs.microsoft.com/pl-pl/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1

Installed NuGet: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation

I have added line

```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages().AddRazorRuntimeCompilation();
        }
```
and still when I refresh Web Page it does not update any changes made in Visual Studio.

Using all latest updates, Net Core 3.1
chrome browser also latest update

I have no idea why it's not working. Please help. Thank you.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by RT77developer** [comment]
I think I was not doing ctrl+s after editing page. When I save page in visual studio and refresh web page in browser changes made after ctrl+s are shown properly. My bad.

**Comment by mkArtakMSFT** [comment]
Thanks for getting back to us. Closing as there is no pending action here.
