### ISSUE TITLE
ValidationMessage css class should be configurable

### ISSUE THREAD

**Issue by XmlmXmlmX** [dotnet/aspnetcore#19278]
### The Problem

I am trying to use existing styles (Bootstrap) for validation messages, but it is not possible to change the class name for [ValidationMessage](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/ValidationMessage.cs#L77).

**What I get:**

```html
<div class="validation-message" role="alert">Lorem alert!</div>
```

**What I want:**

```html
<div class="alert alert-primary" role="alert">Lorem alert!</div>
```

So it is possible to give some additional custom attributes and they will be rendered, like `role="alert"`. But it is not possible to change the class name.

### The Solution

Allow to set the `class`-attribute.

So this component...

```html
<ValidationMessage For="@(() => Model.MyField)" class="alert alert-primary" />
```

...should render...

```html
<div class="alert alert-primary">Lorem alert!</div>
```

If no class attribute was set, the default will be rendered.

### Suggestion

```csharp
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
    foreach (var message in CurrentEditContext.GetValidationMessages(_fieldIdentifier))
    {
        builder.OpenElement(0, "div");
        builder.AddMultipleAttributes(1, AdditionalAttributes);

        if (!AdditionalAttributes.ContainsKey("class"))
        {
            builder.AddAttribute(2, "class", "validation-message");
        }

        builder.AddContent(3, message);
        builder.CloseElement();
    }
}
```

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/ValidationMessage.cs#L71-L81

#19279

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have an existing issue tracking the same ask: https://github.com/dotnet/aspnetcore/issues/8695
Closing this as a dupe.
