### ISSUE TITLE
Blazor Server: CreateHostBuilder crashes intermittently for a given nuget package

### ISSUE THREAD

**Issue by simonziegler** [dotnet/aspnetcore#19288]
### Describe the bug

This 👇
![image](https://user-images.githubusercontent.com/11708435/75155575-48be3000-5708-11ea-96c8-5920f3392521.png)

### To 
This is an intermittent issue that I get with both VS 16.4 and 16.5. I find that I have 24 to 48 hours of fault-free debugging experience and then get the error as shown. The only thing I can do is to uninstall and reinstall the relevant nuget package. This fixes matters for the next day or so.

### Further technical details
- ASP.NET Core version: *3.1*
- Include the output of `dotnet --info`

'''
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014977
 Commit:    ca5522cead

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014977\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014977 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
'''
- The IDE VS 2019 16.4 and 16.5 on Windows 10.

**Comment by javiercn** [comment]
@simonziegler thanks for contacting us.

Are you cleaning your nuget package cache? (seems like you are using a non-standard location).
There seems to be something going on in your machine that might be interfering with your nuget package cache location.

From what I can see there's nothing wrong with the package and Static Web Assets seems to be behaving as appropriate (I imagine you have the package installed).

When that happens, I would check for the folder on disk and see if its there. To me, it feels something is removing it and that's causing you to see that exception.

**Comment by simonziegler** [comment]
I should have said: I don't have a `C:\root` folder. I'll investigate how to clear the nuget package cache and will report back, probably in a few days with conclusions.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Try to install 3.1.102 .NET Core SDK and use global.json to pin it. We believe we have fixes in that SDK which will resolve this issue.

**Comment by simonziegler** [comment]
Thanks @mkArtakMSFT. I will do. Just one thing, and sorry for the noob question, what do you mean by pinning it with global.json?

Cheers,  Simon

**Comment by javiercn** [comment]
run `dotnet new globaljson --sdk-version 3.1.102` at the root of your solution and close and open visual studio

**Comment by simonziegler** [comment]
Many thanks @javiercn. Out of interest, was there a problem that you found that caused this error to crop up?

**Comment by simonziegler** [comment]
I'm delighted to say that after a two week wait I was finally able to test this out with complete success. Many thanks and sorry for the delay - I wasn't getting a crash for that whole period! Meanwhile please consider this issue closed, but I would be interested to know if the [sdk 3.2.0 preview 2](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/) announced yesterday also contains your fix. Many thanks!
