### ISSUE TITLE
IFormFile breaks when filename missing from Content-Disposition

### ISSUE THREAD

**Issue by amosonn** [dotnet/aspnetcore#19295]
### Describe the bug
When receiving a request with a `multpart/form-data` containing a field which doesn't have the `filename` field in its `Content-Disposition`, the application returns 400 (without getting to the controller code). Standard mandates however that this field is optional:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

### To Reproduce
``` C#
[Route("[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpPost]
    [Consumes("multipart/form-data")]
    public async Task<ActionResult> DoAction([FromForm] IFormFile file)
    {
        return Ok();
    }
}

[Test]
public async Task DoIt()
{
    var builder = new WebApplicationFactory<Startup>();
    var client = builder.CreateClient();
    var stream = new MemoryStream(new byte[] {1, 2, 3});
    var form = new MultipartFormDataContent();
    var streamContent = new StreamContent(stream);
    streamContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
    {
        Name = "file",
        // uncommenting this fixes this
        // FileName = "myfile.txt"
    };
    form.Add(streamContent);
    var result = await Client.PostAsync("http://localhost:5000/my", form);
    Assert.That(result, Is.EqualTo(200));
}
```

Instead of the test function, using curl:
``` bash
echo "abc" > /tmp/a.txt
curl -v -F file=@/tmp/a.txt http://localhost:5000/my # works
curl -v -F file=abc http://localhost:5000/my # doesn't work
```

### Further technical details
- netcoreapp3.0
- sdk:3.0.100

**Comment by javiercn** [comment]
@amosonn thanks for contacting us.

@Tratcher do you have any thoughts?

**Comment by Tratcher** [comment]
Sections without the FileName set are considered form entries. E.g. if your file upload page also had text fields to fill out, that's how they'd be represented in the message.

**Comment by blowdart** [comment]
The page linked to is for downloads where the rules are different, not form uploads.

You wouldn't send it as a form in this case; you'd return a [FileResult()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fileresult?view=aspnetcore-3.1) from your IActionResult controller method

**Comment by amosonn** [comment]
What's the idiomatic way to get `Stream` access to a (large) multi-part form field then? This should be possible even for fields without a `filename`.

Thank you for your time!

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#upload-large-files-with-streaming

**Comment by anurse** [comment]
Closing as we believe the question has been answered and there is no further actionable work on our side at this time.

**Comment by amosonn** [comment]
I would still see this as surprising behaviour, and would expect a shorter way to do something relatively basic - forbidding the comfort of `IFormFile` (as compared to all the boilerplate in the link) just because the `filename` field is missing seems excessive.

**Comment by Tratcher** [comment]
This matches standard browser form behavior, and is even the expected behavior described in the curl docs. https://curl.haxx.se/docs/manpage.html
```
To force the 'content' part to be a file, prefix the file name with an @ sign. To just get the content part from a file, prefix the file name with the symbol <. The difference between @ and < is then that @ makes a file get attached in the post as a file upload, while the < makes a text field and just get the contents for that text field from a file.
```
Text fields are accessible by changing your input parameter to `string file`. There's no expectation that text fields need to be streamed, hence it takes more code to do so.
