### ISSUE TITLE
BlazorWasm benchmark app no longer produces _framework in the publish dir

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19307]
@javiercn looks like some of the static file changes affected the publishing for the app. Can you fix this?

The app that we publish: https://github.com/dotnet/aspnetcore/tree/blazor-wasm/src/Components/benchmarkapps/Wasm.Performance/Driver. The command we use to publish: https://github.com/dotnet/aspnetcore/tree/blazor-wasm/src/Components/benchmarkapps/Wasm.Performance#running-the-benchmarks

**Comment by javiercn** [comment]
@pranavkm We moved to publish things inside the wwwroot folder
