### ISSUE TITLE
Reference dotnet-js-interop by source

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19300]
Now that Microsoft.InteropJS is in aspnetcore@master, Web.JS should reference it by source rather than attempting to use the package from the MyGet feed: https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web.JS/package.json#L19

**Comment by JunTaoLuo** [comment]
FYI, the migration of the package is described in https://github.com/dotnet/aspnetcore/issues/19254

**Comment by pranavkm** [comment]
Moving this out to the next sprint (after wasm is merged upstream).
