### ISSUE TITLE
Add cgmanifest files to Razor's embedded grammar VS extension

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#19309]
Example: https://github.com/microsoft/vscode/blob/master/extensions/razor/cgmanifest.json

@mkArtakMSFT Do the cgmanifests need to ship in VS along side the grammars?

**Comment by mkArtakMSFT** [comment]
> @mkArtakMSFT Do the cgmanifests need to ship in VS along side the grammars?

Not really. It's really to enable scanning. I'm wondering whether there is a third-party-notices file somewhere we need to have, though. I'll try to follow on up this tomorrow. Please remind me - doesn't have my TODO app with me at the moment.
