### ISSUE TITLE
[signalR] Proper way to register async handlers

### ISSUE THREAD

**Issue by captmomo** [dotnet/aspnetcore#19318]
Hi,  
I would like to know what is the proper method to register async method handlers for .NET core signalr C# clients.  I am currently registering as such:
  
```
_hubConnection.On<string>(Strings.ScaleEvents.CreateScale, async (machineName) => _ = await CreateClient(machineName).ConfigureAwait(false));

private static async Task<bool> CreateClient(string machineName)
```  
  
Is this the correct method? Thanks.

**Comment by davidfowl** [comment]
No that's not correct:

```C#
_hubConnection.On<string>(Strings.ScaleEvents.CreateScale, CreateClient);

private static async Task CreateClient(string machineName)
{
  ...
}

```

**Comment by captmomo** [comment]
Thank you for the clarification!

I’m still new to async methods, for my own learning purposes, do you mind
elaborating on  what is the difference and what was wrong with my previous
implementation?

Should I be avoiding using lambda expressions?

Thanks again for your help.

**Comment by davidfowl** [comment]
> Edit; I modified my code accordingly and I'm getting the error that CreateClient has the wrong return type. I'm still using .NET core 2.2, signalr 1.1.0.

Ah 1.1.0 doesn't have these overloads. They were added in the 3.0 version of the client. Before that there's no way to add async callbacks. What you're doing above is ignoring the Task so it's not being awaited by anyone. If there's an exception for example, nothing will fail as a result, it also result in running On callbacks concurrently (which may or may not affect you).

You can upgrade to the 3.0 version of the client (it's compatible with the older version of the server).

**Comment by captmomo** [comment]
Thank you for the explanation and taking the time to clarify.
