### ISSUE TITLE
Perf: TraceIdentifier allocation

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#19323]
Very minor but there is an allocation from accessing `TraceIdentifer`:

![image](https://user-images.githubusercontent.com/303201/75221589-147d6900-5807-11ea-82eb-84a1f05a471c.png)

`TraceIdentifer` is accessed when writing logs in many places. Change these logging methods to take `HttpProtocol` and wrap an `IsEnabled` around accessing `TraceIdentifer`?

![image](https://user-images.githubusercontent.com/303201/75221888-bbfa9b80-5807-11ea-8a61-5d80290dff92.png)

**Comment by davidfowl** [comment]
Fro the error scenarios no. For the non-error ones we could do something else like check IsEnabled first.

**Comment by JamesNK** [comment]
I think the only non-error logs are in `MessageBody`. I guess all our other profiling was GET, meanwhile I'm hitting Kestrel with gRPC's POST.
