### ISSUE TITLE
[Helix] Remaining template test work

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#19327]
Several buckets of tests are still not working on helix in the template tests
- [ ] Selenium tests (Spa/blazor)
- [x] tests that depend on EF and Razor compilation (restore fails)
- [x] Dev cert tests on Mac OS/Windows 7 (grpc, etc)
- [ ] Template tests are disabled entirely for arm64 (is this something we need/want? we didn't do it before)

**Comment by dougbu** [comment]
> Template tests are disabled entirely for arm64 (is this something we need/want? we didn't do it before)

This is currently true. @HaoK do you remember why❔ If it related to `crossgen` issues, we can probably remove the restriction.

**Comment by HaoK** [comment]
Not sure, I can try turning them on again and see if they work

**Comment by HaoK** [comment]
Templates tests are disabled on arm also due to https://github.com/dotnet/aspnetcore/issues/25835

**Comment by HaoK** [comment]
Closing this since we have https://github.com/dotnet/aspnetcore/issues/6857 to track selenium/components so both work items left in this are being tracked
