### ISSUE TITLE
ParserError.cshtml file causes IDE to report error

### ISSUE THREAD

**Issue by HahaMango** [dotnet/aspnetcore#19326]
# ParserError.cshtml file causes IDE to report error

See [ParserError.cshtml](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/test/WebSites/ErrorPageMiddlewareWebSite/Views/ErrorPageMiddleware/ParserError.cshtml)

When I restore the project on ubuntu and then i get an error when vscode opens.

Because the span html tag is outside the braces, Is this a bug?

Like this:

```
@{
    <span>
}
</span>
```

**Comment by javiercn** [comment]
@HahaMango thanks for contacting us.

I think that is intended, Looks like its done on purpose to force an exception and validate the experience on errors.

**Comment by HahaMango** [comment]
@javiercn Thank you, I see.
