### ISSUE TITLE
How Can I pass Parent Tag Ref to Child Tag in taghelper

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/aspnetcore#19321]
How Can I pass Parent Tag Ref to Child Tag in taghelper??

**Comment by javiercn** [comment]
@kugarliyifan thanks for contacting us.

I'm not sure if this can be done through the TagHelper context or if it is simply not possible. @NTaylorMullen do you have any idea on how to achieve this?

**Comment by NTaylorMullen** [comment]
@kugarliyifan `Ref` as in the HTML ref attribute or the actual instance of the parent tag?

**Comment by kugarliyifan** [comment]
the actual instance of parent tag object

> @kugarliyifan `Ref` as in the HTML ref attribute or the actual instance of the parent tag?

**Comment by NTaylorMullen** [comment]
> the actual instance of parent tag object

Hmm, out of curiosity why do you want the parent `TagHelper` instance?

To do what you're looking for in your parent `TagHelper` have it add itself to the `TagHelperContext.Items` collection and have the child `TagHelper` read it.

**Comment by kugarliyifan** [comment]
emm,,thk ,,I use Items property now
