### ISSUE TITLE
Empty request body returns 415 when 400 would be more appropriate

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [dotnet/aspnetcore#19339]
### Describe the bug
If model binding is unable to select an input formatter for the request, BodyModelBinder attaches an UnsupportedContentTypeException, causing a 415 response. 

This isn't always the best response. If an input formatter could not be selected because the request content type is wrong (e.g. conflicts with the Consumes attribute) then it is correct.  But if there is no content type conflict, and the input formatter could not be selected because the input is null, shouldn't the response be 400?

### To Reproduce

``` C#
// AllowEmptyInputInBodyModelBinding is NOT set in Startup.cs.

public class InputModel
{
}

[Route("")]
[ApiController]
public class MyController : ControllerBase
{

    // this works as expected
    [HttpGet("a")]
    public ActionResult Gets200([FromQuery] InputModel model) => Ok();
    
    // FromBody is inferred. Input formatter selection will fail if request body is null.
    // I would expect this to fail with a 400 because required input is not present. 
    // Instead I get a 415 which leads me down the wrong troubleshooting path.
    // (Don't ask me how I spent my afternoon :) )
    [HttpGet("b")]
    public ActionResult Gets415(InputModel model) => Ok();

}
```

### Further technical details
- ASP.NET Core version 3.0  (SDK 3.1.0)

**Comment by javiercn** [comment]
@rellis-of-rhindleton thanks for contacting us.

Are you sending a content-type header with the request? (Even if the body is empty)

**Comment by pranavkm** [comment]
As @javiercn pointed out, content negotiation would fail in the absence of a `Content-Type` header resulting in a 415. It's fairly likely that the GET request doesn't have a `Content-Type`.

**Comment by rellis-of-rhindleton** [comment]
I will confirm this - I'm fighting with a CORS issue in this same project right now, but as soon as I get that out of the way I'll come back and update this.

If indeed that header is missing, I understand the 415.  Given that content type takes part in routing.

**Comment by rellis-of-rhindleton** [comment]
Looks like this was my misunderstanding about how the ApiController attribute works.
