### ISSUE TITLE
consider using case insensitive key comparison in AuthenticationSchemeProvider by default

### ISSUE THREAD

**Issue by spooky** [dotnet/aspnetcore#19331]
Currently, by default, the AuthenticationSchemeProvider class uses case sensitive key comparison (https://github.com/dotnet/aspnetcore/blob/a0eb923ab58193944f333880b2ab61ce2ca62725/src/Http/Authentication.Core/src/AuthenticationSchemeProvider.cs#L24).
The [spec for basic and digest](https://tools.ietf.org/html/rfc2617) auth schemes states that the scheme name itself should be a case insensitive token. Hence, maybe it would be a good idea to use a dict with `StringComparer.OrdinalIgnoreCase` as the default instead of one using `StringComparer.Ordinal`.

**Comment by javiercn** [comment]
@spooky thanks for contacting us.

The authentication scheme name in ASP.NET Core doesn't have any relation to the auth schemes for basic and digest authentication mechanisms.

@HaoK @blowdart in case they want to add something else.

**Comment by blowdart** [comment]
Nope you said everything :)
