### ISSUE TITLE
Debugging too slow with angular

### ISSUE THREAD

**Issue by buster95** [dotnet/aspnetcore#19343]
# .netcore 3.1 and angular

I'm using .net core 3.1 with angular, before that I was using 2.2 debugging was slow but not much, now I update my project to 3.1 and debugging is very very very slow, I'm talking about a lot of time

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
