### ISSUE TITLE
WCF Client failure in Blazor WebAssembly App

### ISSUE THREAD

**Issue by vidir-svanberg** [dotnet/aspnetcore#19349]
### Describe the bug
Calling an operation on a WCF Client results in an exception in  System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy.

The same code calls the WCF Web Service successfully in Blazor Server App and Console App.
I am able to call the same WCF Web Service using HttpClient from the Blazor WebAssembly App.

### Exception Message
The base type 'System.ServiceModel.Channels.ServiceChannelProxy' must have a public parameterless constructor. Parameter name: TProxy 

### Stacktrace
at System.Reflection.DispatchProxyGenerator.GenerateProxyType (System.Type baseType, System.Type interfaceType) <0x277e4c0 + 0x00122> in <filename unknown>:0 at System.Reflection.DispatchProxyGenerator.GetProxyType (System.Type baseType, System.Type interfaceType) <0x277cf50 + 0x0008e> in <filename unknown>:0 at System.Reflection.DispatchProxyGenerator.CreateProxyInstance (System.Type baseType, System.Type interfaceType) <0x277cac8 + 0x00008> in <filename unknown>:0 at System.Reflection.DispatchProxy.Create[T,TProxy] () <0x2758168 + 0x00008> in <filename unknown>:0 at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel] (System.ServiceModel.Description.MessageDirection direction, System.ServiceModel.Channels.ServiceChannel serviceChannel) <0x2757fd0 + 0x00002> in <filename unknown>:0 at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel] (System.ServiceModel.Description.MessageDirection direction, System.ServiceModel.Channels.ServiceChannel serviceChannel) <0x2757cf0 + 0x00036> in <filename unknown>:0 at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel] (System.ServiceModel.EndpointAddress address, System.Uri via) <0x27404d0 + 0x00064> in <filename unknown>:0 at System.ServiceModel.ChannelFactory`1[TChannel].CreateChannel (System.ServiceModel.EndpointAddress address, System.Uri via) <0x273b3b0 + 0x0009a> in <filename unknown>:0 at System.ServiceModel.ChannelFactory`1[TChannel].CreateChannel () <0x273b0a0 + 0x00016> in <filename unknown>:0 at System.ServiceModel.ClientBase`1[TChannel].CreateChannel () <0x273af70 + 0x0000a> in <filename unknown>:0 at System.ServiceModel.ClientBase`1[TChannel].CreateChannelInternal () <0x273aeb0 + 0x00006> in <filename unknown>:0 at System.ServiceModel.ClientBase`1[TChannel].get_Channel () <0x273ac98 + 0x00080> in <filename unknown>:0 at ServiceReference1.Service1Client.GetDataAsync (System.Int32 value) <0x273ab70 + 0x00004> in <filename unknown>:0 at WebServiceClientTest.WebServiceTest.testAsync (System.Int32 x) <0x25620c8 + 0x00080> in <filename unknown>:0 

### To Reproduce
1. Create a Blazor Webassembly App 
2. Create a simple WCF Soap Web Service and run it
3. Add Connected Service for the WCF Soap Web Service in step 2 using Microsoft WCF Web Service Reference Provider.
5. Add a button in the Blazor Webassembly App that uses the service client generated in step 3 and calls an operation in the WCF Soap Web Service when the buttton is clicked.
6. Run the Blazor Webassembly App and click the button from step 5 to generate the error

### Further technical details
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 Version 16.4.5

**Comment by danroth27** [comment]
It's a bit unusual to call SOAP services directly from a browser. Typically you would use HttpClient to call a Web API instead and then deal with WCF on the backend.

Out of curiosity though, can you try disabling IL linking by adding `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>` to your project file?

**Comment by javiercn** [comment]
@vidir-svanberg thanks for contacting us.

As @danroth27 mentions this is not a very common scenario. Our recommendation would be that instead of trying to call the WCF service from the client, you call an API on the server and from there you call the WCF service.

The reason for this is that it is very likely that trying to do this on the client you are going to run into many limitations, due to the fact that you are running inside a browser and many WCF features will not be available.

While it is possible you might get some things to work, I expect that in the general case you will have to spend much more work trying to get it to work (if possible) compared to calling an API and issuing a call from there to the target WCF server.

Hope this helps.

**Comment by vidir-svanberg** [comment]
**Calling Soap Service from Server**
I know that Soap Web Services are not in fashion but changing code that works just to follow current programming fashion does not make financial sense or good use of limited time. 
Calling a wrapper service on a server that uses WCF to call the Web Service adds complexity, additional work, an additional failure point and will probably increase latency.  
The Soap Web Services are relatively simple and are not using any exotic or complex feature of WCF.

**Setting BlazorLinkOnBuild to false**
Adding &lt;BlazorLinkOnBuild&gt;false&lt;/BlazorLinkOnBuild&gt; fixes the current bug but triggers another WCF error in System.ServiceModel.Channels.HttpChannelFactory<TChannel>.GetHttpClientAsync. 
That error can be fixed by only setting the clientHandler.AutomaticDecompression property if clientHandler.SupportsAutomaticDecompression is true. 
I can see that there are other clientHandler properties used in GetHttpClientAsync that are not implemented in   https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.wasm.cs . The other properties are:  UseCookies,  PreAuthenticate, UseDefaultCredentials and  Credentials.

**Stacktrace with &lt;BlazorLinkOnBuild&gt;false&lt;/BlazorLinkOnBuild&gt;**
Property AutomaticDecompression is not supported. at System.Net.Http.HttpClientHandler.set_AutomaticDecompression (System.Net.DecompressionMethods value) <0x32d73f8 + 0x0000c> in <filename unknown>:0 at System.ServiceModel.Channels.HttpChannelFactory`1[TChannel].GetHttpClientAsync (System.ServiceModel.EndpointAddress to, System.Uri via, System.ServiceModel.Security.Tokens.SecurityTokenProviderContainer tokenProvider, System.ServiceModel.Security.Tokens.SecurityTokenProviderContainer proxyTokenProvider, System.ServiceModel.Security.Tokens.SecurityTokenContainer clientCertificateToken, System.TimeSpan timeout) <0x32e7568 + 0x002c8> in <filename unknown>:0 at System.ServiceModel.Channels.HttpChannelFactory`1+HttpClientRequestChannel[TChannel].GetHttpClientAsync (System.ServiceModel.EndpointAddress to, System.Uri via, System.ServiceModel.Security.Tokens.SecurityTokenContainer clientCertificateToken, System.Runtime.TimeoutHelper timeoutHelper) <0x32d35d8 + 0x00178> in <filename unknown>:0 at System.ServiceModel.Channels.HttpChannelFactory`1+HttpClientRequestChannel+HttpClientChannelAsyncRequest[TChannel].SendRequestAsync (System.ServiceModel.Channels.Message message, System.Runtime.TimeoutHelper timeoutHelper) <0x32d15d0 + 0x00132> in <filename unknown>:0 at System.ServiceModel.Channels.RequestChannel.RequestAsync (System.ServiceModel.Channels.Message message, System.TimeSpan timeout) <0x32b4b38 + 0x0022e> in <filename unknown>:0 at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal (System.ServiceModel.Channels.Message message, System.TimeSpan timeout) <0x32b3f50 + 0x0017a> in <filename unknown>:0 at System.Runtime.AsyncResult.End[TAsyncResult] (System.IAsyncResult result) <0x3307468 + 0x000e6> in <filename unknown>:0 at

**Comment by javiercn** [comment]
> **Calling Soap Service from Server**
> I know that Soap Web Services are not in fashion but changing code that works just to follow current programming fashion does not make financial sense or good use of limited time.
> Calling a wrapper service on a server that uses WCF to call the Web Service adds complexity, additional work, an additional failure point and will probably increase latency.
> The Soap Web Services are relatively simple and are not using any exotic or complex feature of WCF.

I understand, the thing that I'm trying to point out is that you'll likely spend more time trying to resolve all the quirks involved in getting a WCF service to work compared to going with the suggested approach.

I'm not sure exactly what the problem is with the WCF stack on Webassembly, but if you are determined to go through this path, I would suggest you file an issue directly in the [mono](https://github.com/mono/mono) as this issue is not Blazor specific.

**Comment by danroth27** [comment]
@vidir-svanberg I'm going to go ahead and just move this issue to the mono repo.

When running on WebAssembly, the HttpClient implementation is really a wrapper around the browser `featch` API, which has certain limitations that we don't control.

**Comment by danroth27** [comment]
This issue was moved to mono/mono#19068

**Comment by vidir-svanberg** [comment]
I think you have overestimated how much work was needed to make the WCF client work in a Blazor WebAssembly App.  
I have successfully called a simple SOAP Web Service from a Blazor WebAssembly App using a WCF client. 
I don’t expect everything in WCF to work from a browser using WebAssembly code but calling simple SOAP Web Services over http(s) is definitely possible.

**Comment by denisbredikhin** [comment]
@vidir-svanberg can you please tell me how you was able to call it? For me browser just hangs on call channelFactory.CreateChannel

**Comment by vidir-svanberg** [comment]
Look at https://github.com/dotnet/wcf/compare/master...vidir-svanberg:Blazor-WebAssembly-fixes?expand=1

**Comment by denisbredikhin** [comment]
@vidir-svanberg thanks a lot, I will try!

**Comment by denisbredikhin** [comment]
@vidir-svanberg it is very strange that you had an exception, but in my case browser just hangs...

**Comment by vidir-svanberg** [comment]
Did you set BlazorLinkOnBuild to false in the project file ,<BlazorLinkOnBuild>false</BlazorLinkOnBuild> ?

I used Add Service Reference ..., Connected Services ... to generate the client side code.

var client = new  XClient( XClient.EndpointConfiguration.X );
// call OpenAsync() not Open(), Open() hangs
await client.OpenAsync().ConfigureAwait( false );
return await client.???( ... );

**Comment by denisbredikhin** [comment]
@vidir-svanberg Thanks, using this way it is not hanging anymore. But now I'm getting CORS error is my client. How did you get CORS enabled for WCF Service? I've tried some ways I've found in interned and nothing helped.

**Comment by vidir-svanberg** [comment]
I used the IIS CORS Module
