### ISSUE TITLE
.NET Core razor page tag helpers execute error

### ISSUE THREAD

**Issue by hauserJr** [dotnet/aspnetcore#19342]
# General

`<a asp-area='backend' asp-controller='home' asp-action='index'>click</a>`

this link on browser will be

> ../home/index?area=backen

not be

> ../backend/home/index

**Comment by javiercn** [comment]
@hauserJr thanks for contacting us.

Can you provide a minimal repro project that showcases your issue? It is very likely that there is an error in your routing configuration.
