### ISSUE TITLE
Limiting Request to Web API that are coming from same location

### ISSUE THREAD

**Issue by ricksanchezisagoodman** [dotnet/aspnetcore#19340]
We have a web api where we allow anon[AllowAnonymous] users to register using our own mobile apps(android & iOS). Recently it was reported that there are multiple users registered with the same email address which we do not allow. We have multiple check to not allow this to happen. When we check our IIS log. We have something like this:

> 2020-02-15 18:40:42 XXX.XXX.X.XX POST /api/Account/Register - 8082 - Y.YY.YYY.YYY OurIOSAppName/3+CFNetwork/1121.2.2+Darwin/19.3.0 - 400 0 64 69968
2020-02-15 18:40:42 XXX.XXX.X.XX POST /api/Account/Register - 8082 - Y.YY.YYY.YYY OurIOSAppName/3+CFNetwork/1121.2.2+Darwin/19.3.0 - 200 0 0 13218
2020-02-15 18:40:42 XXX.XXX.X.XX POST /api/Account/Register - 8082 - Y.YY.YYY.YYY OurIOSAppName/3+CFNetwork/1121.2.2+Darwin/19.3.0 - 200 0 0 17390

it seems that the our web api is receiving multiple request from the iOS mobile app using AlamoFire and the same with RetroFit for Android. Is there away prevent this?

**Comment by blowdart** [comment]
Nothing built in, you'd have to write your own. Or offload it to a firewall/WAF.

**Comment by keithwill** [comment]
Why is the mobile app allowing three registration requests to occur concurrently? That sounds like the app isn't disabling the register button after it is clicked. I don't see how you could create accounts with exact duplicate email addresses if you are using isolated transactions in a database to control the record creation, or if you have a unique column constraint.
