### ISSUE TITLE
Hub: Closing the browser on a long running task does not trigger OnDisconnectedAsync until after the task has finished

### ISSUE THREAD

**Issue by ivan-lapitski** [dotnet/aspnetcore#19367]
### Describe the bug

Closing the browser on a long running task does not trigger OnDisconnectedAsync until after the task has finished.
What I'm after is being able to cancel a normal hub method on user disconnect/browser close.

### To Reproduce
``` C#
 public class TestHub : Hub<IProgressHub>
    {

        public override Task OnDisconnectedAsync(Exception exception)
        {
            // This is triggered only after the task has finished.
            return base.OnDisconnectedAsync(exception);
        }


        public async Task<bool> RunTestAsync()
        {
            return (await _TestTaskAsync(this.Context.ConnectionAborted));
        }

        private async Task<bool> _TestTaskAsync(CancellationToken cancel)
        {
            for (int i = 0; i < 1000; i++)
            {
                if (cancel.IsCancellationRequested)
                {
                    // never triggered.
                }

                await Task.Delay(1000);
                await this.Clients.Client(this.Context.ConnectionId).ReportProgress(i.ToString());
            }

            return true;
        }
    }
```

``` C#
 public interface IProgressHub
    {
        Task ReportProgress(string message);
    }
```

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by anurse** [comment]
The fact that `OnDisconnectedAsync` doesn't run until your Hub method returns is by-design. It's all part of the same processing loop.

The ConnectionAborted token should be signalled relatively immediately though. Is 

> ```cs
> await Task.Delay(1000);
> ```

Does anything change if you pass the `CancellationToken` in here as well? It could be that you're stuck in the delay when the cancellation is triggered.

**Comment by ivan-lapitski** [comment]
Thank you for your answer!

> 
> 
> The fact that `OnDisconnectedAsync` doesn't run until your Hub method returns is by-design. It's all part of the same processing loop.
> 
Ah, that's what I suspected.

> The ConnectionAborted token should be signalled relatively immediately though. Does it never get signalled or is it taking more time than expected to be signalled?
> 
It never gets signalled.

> > ```cs
> > await Task.Delay(1000);
> > ```
> 
> Does anything change if you pass the `CancellationToken` in here as well? It could be that you're stuck in the delay when the cancellation is triggered.

No difference, however even without passing the CancellationToken to the Delay function, the delay is only 1 second long, so it should only delay the check by max 1 second.

**Comment by ivan-lapitski** [comment]
If I run the Task as a stream, cancellation works as expected.
However, this solution is pretty "hacky".

```cs
 public async IAsyncEnumerable<bool> RunTestAsync([EnumeratorCancellation]CancellationToken cancelToken)
        {
            var result = await _TestTaskAsync(cancelToken);

            yield return result;
        }

        private async Task<bool> _TestTaskAsync(CancellationToken cancel)
        {
            for (int i = 0; i < 100; i++)
            {
                if (cancel.IsCancellationRequested)
                {
                    // works
                }

                await Task.Delay(1000);
                await this.Clients.Client(this.Context.ConnectionId).ReportProgress(i.ToString());
            }

            return true;
        }
```

**Comment by anurse** [comment]
Thanks for the info! We'll take a look at this. The `ConnectionAborted` token should be something we signal as quickly as possible.
