### ISSUE TITLE
[Blazor] Allow passing of JSON options in PostJsonAsync extension

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#19368]
`Microsoft.AspNetCore.Components.HttpClientJsonExtensions` always uses an internal set of options that cannot be accessed by a Blazor app.

Please add an additional overload that lets us pass the JSON serialization options to use if we don't want to use the default options.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@terrajobst can you please point out to the issue tracking the HttpClient extensions support for System.Text.Json? Thanks!

**Comment by terrajobst** [comment]
I don't think we have one yet (there is internal DevOps item though), so I just filed this: https://github.com/dotnet/runtime/issues/32937

**Comment by mkArtakMSFT** [comment]
Closing this issue as the work is being tracked in the referenced issue.
