### ISSUE TITLE
Kestrel reloadable config

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#19376]
### Is your feature request related to a problem? Please describe.
It's common for an application to add, remove, or reconfigure endpoints via config. That works today for Kestrel but it requires restarting the application to pick up the changes.

For reference, HttpSys supports live adding or removing endpoints in code, but not in config.
https://github.com/dotnet/aspnetcore/blob/f6c89c2dc776060a5988f56f50c138220eaa129d/src/Servers/HttpSys/samples/HotAddSample/Startup.cs#L24-L41

### Describe the solution you'd like
Have Kestrel's custom configuration binder register for config reload notifications. On config change it would need to diff the changes and update its endpoints. Removing an endpoint should also cause existing connections for that endpoint to gracefully drain and close.

**Comment by rynowak** [comment]
One challenge with this is likely going to be coordinating changes to an endpoint data source (routing) along with the request draining. ie - you need to wait for all of the requests to drain before before allowing routing to process updates.
