### ISSUE TITLE
Chrome debugger doesn’t surface pages when moved to external project

### ISSUE THREAD

**Issue by Justincale** [dotnet/aspnetcore#19372]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Justincale** [comment]
Hey guys. I’m working on a repo that has an architectural pattern that requires the client Pages/Components/Services to be in a separate project (let’s say assembly) than the standard ‘Client’ project created via the VS Blazor webassembly template. I have noticed that when using this repo I don’t see any ‘files’ when shift + alt + d in chrome. Does this suggest that the Pages/Components/services have to reside in the Client project (or possibly at least have the same namespace?). Thanks in advance.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've made a lot of changes in areas relevant to this and this issue may just be resolved in the upcoming release.
 We will close the issue for now, but please feel free to reopen if you are able to repro that after the upcoming Blazor WASM release (3.2 preview 2).
