### ISSUE TITLE
Missing Blazor WebAssembly app template for Visual Studio for Mac

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19382]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/925026/missing-blazor-webassembly-app-template-for-visual.html)._

---
<p>I am trying to create a Blazor WebAssembly app using the latest build of <strong>Visual Studio for Mac (v8.4.6 build 36)</strong>. I have .NET Core 3.1 SDK installed. I also installed the latest Blazor WebAssembly 3.2.0 Preview 1 by running:</p><p><code>dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1</code>.</p> <p>The output log shows it installed successfully on my Mac.</p> <p>However, the Blazor WebAssembly App template does not show up in Visual Studio for Mac, even after restarting:</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/119688-blazor-template-missing.png"> Image:119688-blazor-template-missing.png</a></p><p>And if I create a Blazor WebAssembly app from the CLI as follows, it builds but does not run:</p><pre><code>dotnet new blazorwasm 
dotnet build 
dotnet run</code></pre><p>And if I try to run it in Visual Studio for Mac I get this error: <code>Cannot open assembly '/Users/my.username/projects/blazor/BlazerWasm/bin/Debug/netstandard2.1/BlazerWasm.exe': No such file or directory.</code></p> <p>Is Visual Studio for Mac not able to build or run Blazor WebAssembly apps, or am I missing something?</p>

---
#### Visual Studio Feedback System on 2/20/2020, 03:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This was mistakenly moved over. Closing.
