### ISSUE TITLE
E2E tests are not stable in 'release/2.1'

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#19390]
Should investigate the E2E tests that run in the https://dnceng.visualstudio.com/internal/_build?definitionId=134&_a=summary pipeline. These tests do _not_ have the stability fixes we've tried in other template tests and need a look-see.

See https://dnceng.visualstudio.com/internal/_build/results?buildId=538015&view=logs&j=3c8b9aa9-bc33-5434-4684-4cd0e9579330 for example. That particular job failed most tests using the 'react' template but passed on a rerun.

Although breaks here do not exactly prevent 2.1.x servicing releases, the failures **are** visible and cause questions I shouldn't have to field every month. Your support for fixing this up will be much appreciated.

----

Separately, it appears `stdout` or `stderr` aren't correctly logged in these tests, making debugging more difficult. The first attempt of the above test run is an example. Problem is likely in the [script here](https://github.com/dotnet/aspnetcore/blob/c0e2848ec1ff9280c2a03cfb6eb696bf596215bd/test/Cli.FunctionalTests/run-tests.ps1#L170-L174) or [here](https://github.com/dotnet/aspnetcore/blob/a9132ad26c16f0b2a87aa0d4f28d7e8893975875/eng/scripts/common.psm1#L13). The first location uses a `Detailed` MSBuild console log, The second location is where the command is actually executed (unadorned).

**Comment by dougbu** [comment]
/fyi @mkArtakMSFT @mmitche 

BTW (FYI @Pilchie) this is `tell-mode` because the fix should change only test code. Very worth having because these tests contribute to flakiness of our servicing builds.

**Comment by mkArtakMSFT** [comment]
Let's get these tests disabled.

**Comment by dougbu** [comment]
@mkArtakMSFT :ok:

@mmitche if I disable the https://dev.azure.com/dnceng/internal/_build?definitionId=134&_a=summary pipeline for our E2E tests, will that break ProdCon? If yes, what needs to change in the ProdCon configuration?

**Comment by javiercn** [comment]
@dougbu @mkArtakMSFT We don't own these tests. They seem to be CLI tests, so I suggest you follow up with someone else. My recommendation is that they remove these tests, since we already removed them from 5.0 and so on as we plan to rely on CTI runs

**Comment by ryanbrandenburg** [comment]
Unless I missed a hand-off somewhere I believe we DO own these tests. They were originally written by Mike Harder as a possible alternative to the "normal" functional tests, and I don't believe they were ever passed off to another team.

That said, @javiercn is still correct that we deleted them from master and that it's just as reasonable (and reliable) to rely on CTI for coverage here.

**Comment by dougbu** [comment]
These tests haven't executed since 26 February and should not run anymore. @mmitche removed their execution from ProdCon builds and I disabled the pipeline.

Time to close this issue&hellip;
