### ISSUE TITLE
Enhancements on LinkGenerator and TemplateBinder

### ISSUE THREAD

**Issue by yang-er** [dotnet/aspnetcore#19395]
### Is your feature request related to a problem? Please describe.
Ambient Value Invalidation is one of breaking changes from Endpoint Routing.

With the current algorithm, anchor links for `/[area=project]/{projectid}/[controller=...]/[action=...]` is more complicated. I have to attach `asp-route-projectid="some..."` to each tag.

After I read the source code for `Microsoft.AspNetCore.Routing.Template.TemplateBinder`, I found that if `projectid` can be added into `_requiredKeys`, this problem will no longer exists.

### Describe the solution you'd like
Create a new Attribute for Endpoint Metadata, which contains the route tokens to add into `_requiredKeys`. And when generating `TemplateBinder`s, use these attributes to build that array.

### Additional context
Well, if I make the `_requiredKeys` an empty array through reflection, it will become the behavior in ASP.NET Core 2.1 and earlier. Maybe an alternative compatibility property in `MvcOptions` also works? This really slow down my work for upgrading to ASP.NET Core 3.x. And the solution in the second section doesn't really bother the Endpoint Routing system.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @yang-er.
This is not something we plan to do as we've intentionally stepped away from that model.
/cc @rynowak
