### ISSUE TITLE
Blazor: Scoped dependencies constructed repeatedly

### ISSUE THREAD

**Issue by freever** [dotnet/aspnetcore#19402]
### Describe the bug
According to the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1) a service in server-side Blazor is supposed to endure for the duration of a connection, in other words it should persist acorss a number of page requests as long as the underlying SignalR connection remains connected. 

In trying to puzzle through some issues I am having with scoped dependencies in Blazor, I created a simple sample app with one service registered as scoped. As expected, the same service is retreived from the DI container on each page. However the service is actually constructed and disposed multiple times, usually once per page. The service is even constructed again when you first click the counter button. 

Is this intended behaviour? 

![scoped services](https://user-images.githubusercontent.com/2269624/75456333-0f452900-5983-11ea-8c19-d43796b47d59.gif)

### To Reproduce
 See attached solution for repro. 

[ScopedServiceTest.zip](https://github.com/dotnet/aspnetcore/files/4262222/ScopedServiceTest.zip)

### Further technical details
[dotnetinfo.txt](https://github.com/dotnet/aspnetcore/files/4262234/dotnetinfo.txt)
[vsinfo.txt](https://github.com/dotnet/aspnetcore/files/4262238/vsinfo.txt)

**Comment by freever** [comment]
If I change it to from ServerPreRender to Server then it stops happening, so I suppose it works as intended.

**Comment by freever** [comment]
Actually... it doesn't seem right. 

I can understand that pages will render twice when ServerPrerender is true, but surely a Scoped service should be constructed at most twice per SignalR connection, not every time a new page is loaded?

**Comment by pranavkm** [comment]
@freever I don't see this issue running your app: 
![Scoped](https://user-images.githubusercontent.com/174281/81351290-d27b6980-9078-11ea-9e2e-354eae612b8b.gif)

Perhaps you have other users or extensions that might be attempting to navigate to this page.

**Comment by docmaster2** [comment]
по всей вероятности дело обстоит именно так,хотя объективной причины в этом я не вижу.
