### ISSUE TITLE
OS build architecture causes failures in deployment

### ISSUE THREAD

**Issue by steveoh** [dotnet/aspnetcore#19416]
### Describe the bug

Building an application on OSX and publishing it to windows server 2016/IIS is failing with 500.30 etc. Building and publishing from windows succeeds. 

### To Reproduce

1. Build an application on OSX that contains `serilog.sings.googlecloudlogging`.
1. Create the publish deployment `dotnet publish -c Release -r win10-x86 or x64` with or without `--self-contained false`
1. Compress the publish folder, sftp the zip file to the server via openssh, unzip

The serilog part is included because this was in the event viewer logs. This is without the -r in the build.

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

 ---> System.IO.IOException: Error loading native library "C:\app\runtimes/win/native\grpc_csharp_ext.x64.dll". 
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, IEnumerable`1 channelOptions, ChannelCredentials credentials)

```

Building the same code on a windows machine makes the app load as expected. I have spoken with the serilog author and they are using the [official google library](https://github.com/manigandham/serilog-sinks-googlecloudlogging/issues/22#issuecomment-511466993). Maybe google is doing something that is incompatible with an osx to windows publish? I'm not sure where the issue is coming from and I need the help of someone more talented than me to identify the location.

I thought this was an encoding issue with the tool i was using to sftp the zip file since when I used a different tool the app would load but then would fail with this error

```
ParentId: An unhandled exception has occurred while executing the request. Exception: System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll' or one of its dependencies: Access is denied. (0x80070005 (E_ACCESSDENIED)) 
```

so maybe it's a permission issue or something with the transfer?

### Further technical details

- ASP.NET Core 3.1.2

```
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Pilchie** [comment]
This is seeming about GrpcCore, not our gRPC implementation, but maybe @JamesNK still has an idea here?

**Comment by BrennanConroy** [comment]
This looks like GrpcCore, please file an issue there https://github.com/grpc/grpc
