### ISSUE TITLE
Razor Testability

### ISSUE THREAD

**Issue by jbosse** [dotnet/aspnetcore#19419]
### Is your feature request related to a problem? Please describe.
I am trying to unit test a Razor View

### Describe the solution you'd like
I would like to give some rendering method my View and a Model and have it return the rendered string. 

### Additional context
The root purpose of a web server is to render a string of HTML to a browser. The fact that there is no out-of-the-box way to unit test a rendered razor view without spinning up a web server is simply madness.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Here is a sample which will help with that: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/renderviewtostring

**Comment by jbosse** [comment]
This only works if you have a functioning controller context to pass as a dependency. 

The problem seems to be the large number of global methods and dependencies that one can call from Inside a razor view that need to be accounted for. 

As an aside, after spending days trying to figure out a lightweight method for testing the html a razor view will render from my controllers in the kind of enterprise system that would benefit most from Client-side Blazor.

I find it worrisome that the .NET community at large seems okay with having to spin up a server (which is not easy nor computationally inexpensive for the large enterprise system I am working on) to test a rendered view. A web server exists primarily  to send string to a web browser yet testing those strings simply is not possible (or it is really obvious so nobody has ever posted anything on the internet about how to do it.)

**Comment by mkArtakMSFT** [comment]
Thanks for sharing your concerns, @jbosse.
We plan to enable testing for Blazor WASM applications as part of the 5.0 release. Given that we haven't started on that work yet, we don't know what the final solution will look like, but you can have a look at a prototype @SteveSandersonMS has build and blogged about: https://blog.stevensanderson.com/2019/08/29/blazor-unit-testing-prototype/

//cc @NTaylorMullen in case you have other ideas regarding Razor testing.
