### ISSUE TITLE
Asp.net core 3.1 azure identity issue

### ISSUE THREAD

**Issue by kishorpise** [dotnet/aspnetcore#19418]
I have project, that is configured for 
 TargetFramework netcoreapp3.1 TargetFramework

With nuget reference

PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.2"

Startup code as suggested by Microsoft-
```
  services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                    .AddAzureAD(options =>
                    Configuration.Bind("AzureAd", options)
                    ).AddCookie(); 

            services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
            {

                options.Authority = options.Authority + "/v2.0/";        // Microsoft identity platform
                options.TokenValidationParameters.ValidateIssuer = false; // accept several tenants (here simplified)
            });
```

Login button code in controller 
```
    [HttpGet]        
        public IActionResult Login()
        {            
            var redirectUrl = Url.Action(nameof(AccountController.Main), "Account");
            ChallengeResult cr= Challenge(
                new AuthenticationProperties { RedirectUri = redirectUrl, AllowRefresh = false, IsPersistent = false }, AzureADDefaults.AuthenticationScheme);
            
            return cr;
        }
```
In chrome user is not authenticated, but it redirects to Account/Main controller correctly. and , it gives below error 

and 
![image](https://user-images.githubusercontent.com/48448047/75480881-0f87f900-5970-11ea-9c72-55e4943b6558.png)

I would appreciate if you provide any hint. earlier Microsoft mentioned not to use these component.

Regards
Kishor

**Comment by Tratcher** [comment]
Can you share the rest of Startup.cs and the appsettings.json? It sounds like you're missing `UseAuthentication()` in `Startup.Configure`.

**Comment by kishorpise** [comment]
Below is entire class.

 public class Startup
    {

        ILoggerFactory loggerFactory;
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<AppDbContext>(config =>
            {
                config.UseInMemoryDatabase("Memory");
            });

           

            services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = AzureADDefaults.AuthenticationScheme;
            }).AddAzureAD(options =>
            {
                Configuration.Bind("AzureAd", options);
            })
             .AddCookie();

            services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
            {

                options.Authority = options.Authority + "/v2.0/";        // Microsoft identity platform
                options.TokenValidationParameters.ValidateIssuer = false; // accept several tenants (here simplified)
            });

            services.AddTransient<IEmailSender, EmailSender>();
            services.AddControllersWithViews();
            services.AddRazorPages();
        }


        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {

            this.loggerFactory = loggerFactory;
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseSerilogRequestLogging();

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();
            app.UseCookiePolicy();
            app.UseAuthentication();
            app.UseAuthorization();
                                 
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                    name: "Account",
                    pattern: "{controller=Account}/{action?}");

            });
        }
    }

**Comment by Tratcher** [comment]
And the appsettings?

I'm going to refer back to template code for examples:
https://github.com/dotnet/aspnetcore/blob/f0ac5b07eeb49364db1e51706b84d27a70d9c9f2/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L67-L68
You shouldn't need `.AddCookie()` or `CookieAuthenticationDefaults.AuthenticationScheme`.

https://github.com/dotnet/aspnetcore/blob/f0ac5b07eeb49364db1e51706b84d27a70d9c9f2/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/appsettings.json#L17-L22

**Comment by kishorpise** [comment]
Here are the app settings as requested. Please note this is for core 3.1 and all the examples, code snippets are written using 2.2 or older version. Even on Azure portal, that offers vs 2019 code to download has framework targeted to 2.2. I have confirm code which works on older framework this is for 3.1 latest,and please don't divert topic. 

Second point- .AddCookie() having or removing does not make any difference.

Here is final code
 services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = AzureADDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = AzureADDefaults.AuthenticationScheme;
            }).AddAzureAD(options =>
            {
                Configuration.Bind("AzureAd", options);
            });


 "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "XYZWD.com",
    "TenantId": "4b9f063e-52cf-4738-9db5-0df837b6d114",
    "ClientId": "87d8884b-f0dd-47e1-8ce5-a241193c87a4"
     }

Call back path is not needed as its given in challenge.

**Comment by Tratcher** [comment]
> Here are the app settings as requested. Please note this is for core 3.1 and all the examples, code snippets are written using 2.2 or older version.

Have you tried the 3.1 template for this in VS?

**Comment by kishorpise** [comment]
Yes... Only after that I have opened this thread. I spent good amount of time on figuring this. I tried 
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp?view=aspnetcore-3.1

Apart from this I even tried this -

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1

First of all these sample don't use 3.1 framework.

**Comment by anurse** [comment]
@kishorpise can you provide a runnable sample that reproduces the problem you're seeing? There's a lot of code floating around and we really need the full context of *exactly* what you're running.

**Comment by kishorpise** [comment]
Ok.. I would upload soon on git repo.

Because of Corona- expect delays.

Regards
Kishor

**Comment by anurse** [comment]
@kishorpise No problem, get back to us when you can. If the bot auto-closes this issue, feel free to re-open, or open a new one when you do have a repo!
