### ISSUE TITLE
Reuse request header strings in HTTP/2

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#19428]
HTTP/2 is now reusing `HttpRequestHeaders` across streams, but the strings used by the headers are not, despite `KestrelOptions.DisableStringReuse` being false.

The problem is Reset() is called on a stream multiple times: when it is initialized and when it is completed.

@jkotalik @halter73 @benaadams

**Comment by halter73** [comment]
Nice find. Of the two calls to Reset(), we should probably be keeping the one in OnRequestProcessingEnded(), and not the one in Initialize() so we dereference everything we can while the streams are pooled.
