### ISSUE TITLE
SignalR client depends on deprecated npm package "request"

### ISSUE THREAD

**Issue by mnmr** [dotnet/aspnetcore#19420]
The `@aspnet/signalr` npm package depends on the `request` package [npm](https://www.npmjs.com/package/request), which has been deprecated and is no longer maintained.

This might be causing Azure DevOps builds to fail with errors such as this one:
> Installing website NPM packages
> ##[error]npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> Finishing: Build Solution

However, the package does still appear to be available on npm, so the build could potentially have failed for other reasons.

The error message contains an issue link with additional details on the reasoning for deprecating the package and provides suggestions for alternatives.

Note: description has been updated to clarify that I am not sure about the DevOps relation.

**Comment by bradygaster** [comment]
cc @anurse and @Pilchie as this feels like a hi-pri item we should attend to.

**Comment by BrennanConroy** [comment]
I'm not sure why you're seeing an error here. This should just be a warning that you can ignore. How do you reproduce the error? Because locally all I get is the warning.

In future versions we should consider moving off of `request`.

**Comment by mnmr** [comment]
For some reason the warning is treated as an error. We have made no changes to anything build related, but all Azure DevOps builds are failing (since sometime yesterday). I've already updated the issue to reflect that it may not be the root cause of the build failure.

**Comment by anurse** [comment]
Yep, I do remember seeing `request` being deprecated. We should move to `fetch` and a node polyfill for `fetch` (I know they exist).
