### ISSUE TITLE
Blazor Websocket error: Server returned handshake error

### ISSUE THREAD

**Issue by Nick421** [dotnet/aspnetcore#19427]
### Describe the bug

So I have a Blazor server-side application which I deployed to Kubernetes on Google Cloud. The application runs perfectly locally but when I visit the application that was deployed, sometimes (1 out of 5 times) it will give the exceptions listed below. But, when I switch the HTTP transport type to Long polling it works perfectly with no issues.

The effect of this is, navigation, dropdowns etc. or any JavaScript event will not work and all I have is a static page that does nothing. 

Note that I am using port forwarding to access the application on the cluster so maybe that's effecting the websockets?

### To Reproduce
 

1. Make a Blazor server-side app
2. Deploy to Kubernetes.
3. Access it using Kubenetes-port-forwarder 
4. Check browser console for error after 30 seconds or try clicking elements with JavaScript and see if it triggers.

### Exceptions ###

```
Uncaught Error: Server returned handshake error: Handshake was canceled.
      at e.processHandshakeResponse (blazor.server.js:1)
      at e.processIncomingData (blazor.server.js:1)
      at e.connection.onreceive (blazor.server.js:1)
      at WebSocket.i.onmessage (blazor.server.js:1)
Error: Connection disconnected with error 'Error: Server returned handshake error: Handshake was canceled.'.
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
      at e.send (blazor.server.js:1)
      at e.sendMessage (blazor.server.js:1)
      at e.sendWithProtocol (blazor.server.js:1)
      at blazor.server.js:1
      at new Promise (<anonymous>)
      at e.invoke (blazor.server.js:1)
      at e.<anonymous> (blazor.server.js:15)
      at blazor.server.js:15
      at Object.next (blazor.server.js:15)
      at blazor.server.js:15
```
### Further technical details
- ASP.NET Core version 3.1
- IDE Rider 2019.2.3
- [Kube-forwarder](https://kube-forwarder.pixelpoint.io/)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@anurse can you please look into this one? Thanks!

**Comment by anurse** [comment]
@Nick421 can you take a look at the [SignalR logging and diagnostics guide](http://aka.ms/aspnet/signalr/troubleshoot) and collect a network trace as described on that page?

> when I switch the HTTP transport type to Long polling it works perfectly with no issues. ... Note that I am using port forwarding to access the application on the cluster so maybe that's effecting the websockets?

The fact that Long Polling is working definitely indicates that the forwarder is getting in the way of the WebSockets somehow.
