### ISSUE TITLE
Getting error while building mvc solution - Components.Forms.dll

### ISSUE THREAD

**Issue by tavisca-syedave** [dotnet/aspnetcore#19434]
Hi Team,

Getting below error while building "...\aspnetcore\src\Mvc\Mvc.sln" solution
Tag : v3.1.2
Note: Already tried build/restore commands

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\codebase\aspnetcore\src\Components\Forms\src\bin\Debug\netstandard2.0\Microsoft.AspNetCore.Components.Forms.dll' could not be found	Microsoft.AspNetCore.Components.Web (netstandard2.0)	C:\codebase\aspnetcore\src\Components\Web\src\CSC	1	Active

**Comment by pranavkm** [comment]
It's likely that the sln file is missing dependencies. Running `build.cmd` from the command line before launching VS should work.

**Comment by tavisca-syedave** [comment]
Below command solved my issue:
dotnet sln add C:\codebase\aspnetcore\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj
