### ISSUE TITLE
Remove PortablePdbReader

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19441]
The type was meant to [bridge some gaps](https://github.com/dotnet/extensions/issues/235) in .NET Framework, but shouldn't be needed now that it's exclusively used in .NET Core. There is some code in the "package" that cleans up the stack trace which is the only thing we should need from it.

**Comment by anurse** [comment]
The existing code is *working* though right? It's just unnecessary?

**Comment by pranavkm** [comment]
This came up as part of discussing the new single file bundle format that's planned in 5.0. Things like `Assembly.Location` are going to be broken with it - https://github.com/dotnet/aspnetcore/blob/3c09d644cccdb21801f7a79e1188a1a1212de5d9/src/Shared/StackTrace/StackFrame/PortablePdbReader.cs#L27. If we were to try and react to it, we might very well remove this type since it's unnecessary.

**Comment by Marusyk** [comment]
Please assign it to me
