### ISSUE TITLE
FullyQualifyNamespace light bulb behaves broken in methods within @code blocks

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#19449]
1. `dotnet new blazorserver`
1. Open `Counter.razor`
1. In the `IncrementCount()` method add the following above the `currentCount++;` line: `RenderTree`.
1. Invoke the `FullyQualifyNamespace` light bulb

**Expected:** 
```
    private void IncrementCount()
    {
        Microsoft.AspNetCore.Components.RenderTree
        currentCount++;
    }
```

**Actual:**
```
    private void IncrementCount()
    {
            Microsoft.AspNetCore.Components.RenderTree
            currentCount++;
    }
```

Note the extra indent.

**Comment by ajaybhargavb** [comment]
Also, in some cases the lightbulb doesn't even show up.

```razor
    private void IncrementCount()
    {
        RenderTree // 1
        currentCount++;
        RenderTree // 2
    }
```

In the above case, Ctrl+. on 1 shows the FQN code action but Ctrl+. on 2 shows nothing,

**Comment by NTaylorMullen** [comment]
> Ctrl+. on 2 shows nothing,

If you complete the statement under `// 1` does it? I ask because it might be C# failing to understand the rest of the document since it's malformed

**Comment by ajaybhargavb** [comment]
> If you complete the statement under // 1 does it? I ask because it might be C# failing to understand the rest of the document since it's malformed

Yes. But it has the same indentation issue as you described above.

**Comment by TanayParikh** [comment]
@ajaybhargavb your example has been handled separately here as it has a unique root cause.
https://github.com/dotnet/aspnetcore/issues/20397
