### ISSUE TITLE
An assembly specified in the application dependencies manifest (PortableAntiqities.deps.json) has already been found but with a different file extension

### ISSUE THREAD

**Issue by Madmorgan007** [dotnet/aspnetcore#19447]
Hi,
I'm using Visual Studio 2019, Dotnet core 3.1 all updates are installed. Getting the following issue.
this issue happens when creating a controller or view.

Error:
  An assembly specified in the application dependencies manifest (PortableAntiqities.deps.json) has already been found but with a different file extension:
    package: 'Microsoft.VisualStudio.Web.CodeGeneration.Design', version: '3.1.1'
    path: 'lib/net461/dotnet-aspnet-codegenerator-design.exe'
    previously found assembly: 'C:\Users\Administrator\.nuget\packages\microsoft.visualstudio.web.codegeneration.design\3.1.1\lib\netcoreapp3.1\dotnet-aspnet-codegenerator-design.dll'

**Comment by mkArtakMSFT** [comment]
This is actually tooling related. @vijayrkn where should this go ? `Scaffolding` repo?

**Comment by Pilchie** [comment]
Ping @vijayrkn ?

**Comment by vijayrkn** [comment]
yes, Scaffolding repo would be the right place.

**Comment by Pilchie** [comment]
This issue was moved to aspnet/Scaffolding#1278
