### ISSUE TITLE
Format leading { of @code blocks.

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#19445]
RIght now if you try to format 
```razor
@code
        {
    private int currentCount = 0;

    private void IncrementCOunt()
    {
        currentCount++;
    }
}
```
 it won't correct the { to allign with the @code and }

**Comment by NTaylorMullen** [comment]
❤️ ❤️ ❤️ 

![image](https://user-images.githubusercontent.com/2008729/113245449-d5241600-926b-11eb-8038-43dac2c6a4b6.png)

**Comment by davidwengier** [comment]
You assigned it, I just clicked the button so I wouldn't forget 😛
