### ISSUE TITLE
Add switch to allow ANCM to prefer local environment variables over web.config environment variables. 

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#19450]
Today, when ANCM reads environment variables in web.config, it will always replaces whatever environment variables are present in the process with the values in web.config. This behavior makes sense generally, however for developer environments like Visual Studio, there are many times where the environment variable in the web.config doesn't match the value wanted by VS.

For example, the environment variable ASPNETCORE_ENVIRONMENT is sometimes set in web.config, which is used for production environments. As VS needs that value to "Development" rather than "Production", we override the value in web.config, which leads to the file being modified. To say it short, people don't want us to modify the web.config file at all, as well communicated by https://github.com/aspnet/websdk/issues/564. 

To fix this, the easiest approach is to give an option that can be set by VS to prefer local environment variables rather than ones set in web.config in ANCM. This allows VS to override values that may be set in web.config if the values aren't what would lead to a good development scenario.

**Comment by rellis-of-rhindleton** [comment]
Looking forward to this change.  Right now I'm having to do a string replacement in web.config post-publish to get our process environment variable to be recognized.

If you don't mind, let me read this back to you and make sure I understand. What you're saying is that under the **new** behavior:

If ASPNETCORE_ENVIRONMENT is set in web.config:

 - A new option in Visual Studio will let you toggle between using the variable as it is set in web.config, or ignoring it in favor of something VS does on its own.

 - `dotnet publish` will leave the variable setting in web.config unchanged, unless you specifiy `/p:EnvironmentName={value}`.

If ASPNETCORE_ENVIRONMENT is *not* already set in web.config:

 - The new option in Visual Studio will need to be set, or will have default behavior that acts as if it is set. VS will provide its own value. Web.config will not be changed.
 
 - `dotnet publish` will not add an ASPNETCORE_ENVIRONMENT variable setting to web.config, unless you specifiy `/p:EnvironmentName={value}`.
 
And in general, I wanted to check that the new behavior will still be able to use an arbitrary environment name, e.g. whatever is in `launchSettings.json`, and not necessarily "Development" for local dev/debugging?

Is this going to be for any environment variable or just ASPNETCORE_ENVIRONMENT? Just curious.

**Comment by jkotalik** [comment]
Good clarifying questions.

> A new option in Visual Studio will let you toggle between using the variable as it is set in web.config, or ignoring it in favor of something VS does on its own.

Yes, right now we are planning to have a switch to toggle between the old behavior of preferring environment variables in the web.config and having VS override and the new behavior of preferring process environment variables. There is a case where the new behavior is a regression, for example a user was setting environment variables in the web.config which they wanted to override; having a switch to go back to original behavior seems to be reasonable.

The rest of the behavior your described is correct as well.

> And in general, I wanted to check that the new behavior will still be able to use an arbitrary environment name, e.g. whatever is in launchSettings.json, and not necessarily "Development" for local dev/debugging?

@BillHiebert do we read the launchSettings.json to determine the ASPNETCORE_ENVIRONMENT, or do we always set it to Development? If so, then that would be the way to tell VS to use Development vs Production, even in local dev scenarios.

> Is this going to be for any environment variable or just ASPNETCORE_ENVIRONMENT? Just curious.

The behavior described of preferring local vs web.config environment variables applies to any environment variable. From what we can tell, the override of ASPNETCORE_ENVIRONMENT was the only environment variable VS was actively modifying.

**Comment by BillHiebert** [comment]
@jkotalik it is read from launchsettings.json.

**Comment by rellis-of-rhindleton** [comment]
Sounds great. Thank you.

**Comment by anurse** [comment]
Removing Milestone so this comes up in Triage

**Comment by anurse** [comment]
> the easiest approach is to give an option that can be set by VS

To be extra clear here (for implementation), the plan is to have ANCM read an environment variable that VS will set which tells ANCM to prefer local env vars over web.config-defined ones.
