### ISSUE TITLE
NET Core Hosting Bundle is installed, which makes it unavailable to other sites on IIS

### ISSUE THREAD

**Issue by zxj17815** [dotnet/aspnetcore#19459]
I have an old.net service application on IIS，After I installed Hosting Bundle, it broke and couldn't start，if I uninstall the Hosting Bundle, it works again

My server is Windows server2012, open.net service site is blank, has been loading page status, even without any error

**Comment by davidfowl** [comment]
cc @shirhatti @jkotalik

**Comment by jkotalik** [comment]
My guess is it's the same issue as https://github.com/dotnet/aspnetcore/issues/18019. Does the hosting bundle work with 64 bit applications and not 32 bit? If so, most likely the same issue. This will be fixed in 3.1.3.

**Comment by zxj17815** [comment]
Looks like this problem, Here's my situation
in my server (Windows server2012  x64) , AppPool 32-Bit True  it can't work.
in my PC (Win10 x64) ,also AppPool 32-Bit True,  it working.

**Comment by jkotalik** [comment]
Yeah I'm going to close this as a duplicate then as it seems to be the same issue. See the other issue for recommended action.

**Comment by zxj17815** [comment]
yeah，[Your method](https://github.com/dotnet/aspnetcore/issues/18019#issuecomment-579968453) works for me， thanks
