### ISSUE TITLE
Component Tag Helper: Sending a raw string parameter

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#19466]
I'm trying to send a string as a parameter but getting a build error. I know you can send an integer, like in the example of sending the int 10 in the docs, but I can only send a string if it's in a variable. Here is the code and error.

Code

```
// Color is a string property on the razor component ColorfulCheckbox
// "blue" is a raw string
// Note that this razor component is called from a razor page
<component type="typeof(ColorfulCheckbox)"
	   render-mode="Server"
	   param-Color="blue" />
```

Error

> The name 'blue' does not exist in the current context (CS0103)

@guardrex 

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by guardrex** [comment]
Additional note that when an `int` is used (exactly as [our example](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#render-components-from-a-page-or-view) shows), passing the parameter works.

**Comment by rynowak** [comment]
Try this:

```cshtml
<component type="typeof(ColorfulCheckbox)"
	   render-mode="Server"
	   param-Color="@("blue")" />
```

Why it's this bad:

- `param-*` attributes are of type `object`
- Razor has a special parsing behaviour when the **attribute** is known to be a `string`, allowing you to omit the quotes. This doesn't apply because the attribute is not of type `string` (`object` in this case).
- passing a quoted string requires an explicit expression `@(...)`

**Comment by mrlife** [comment]
@rynowak Thanks for letting me know this is possible. I never would have tried that. The explanation makes sense. Is this the final design for this functionality?

**Comment by rynowak** [comment]
For the Razor language in general yes. 

For the use of `<component />` possibly no - we've talked about adding the ability to invoke a component directly from a view (without going through component tag helper). That would improve your use case. That's a huge amount of work and it's not on the schedule anytime soon.

**Comment by mrlife** [comment]
@rynowak I can understand. It would be nice to use `<ColorfulCheckbox></ColorfulCheckbox>` but it's not a huge difference other than less code. Seeing `<component ...` is pretty easy to spot as a razor component, possibly even easier to spot.
