### ISSUE TITLE
BuildRenderTree not being called

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#19463]
I have a Person.razor component which I wanted to separate the code behind from. After doing so, `BuildRenderTree` method is never called. See below for more information.

### Customer.razor
There is no markup intentionally.

``` C# 
@page "/customer"
@inherits CustomerBase
```

### Customer.razor.cs
``` C# 
    public class CustomerBase: ComponentBase
    {
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
            builder.AddMarkupContent(0, "<h1>Person</h1>");
        }
    }
```

**Comment by rynowak** [comment]
Using `@inherits` in a `.razor` file will inherit from the class you provide, and defining a `.razor` file will **always** override `BuildRenderTree`. 

So your hierarchy looks like:

```txt
Customer::BuildRenderTree(...) (empty)
CustomerBase::BuildRenderTree(...) (overridden by Customer)
ComponentBase::BuildRenderTree(...) (abstract)
```

The solution to this is just remove `Customer.razor` if you want to define a render method in C#. You can use `[RouteAttribute(...)]` to apply a route.

**Comment by rynowak** [comment]
You also don't need to use inheritance to have a code-behind. Blazor as of 3.1 supports partial classes.

**Comment by yopez83** [comment]
It worked. Thank you @rynowak
