### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '3.1.2' was not found.

### ISSUE THREAD

**Issue by xiongdashan** [dotnet/aspnetcore#19467]
When I updated dotnet-ef version to 3.1.2, the following issue occurred:

```
dotnet ef database update --startup-project ../MyApplication
Build started...
Build succeeded.
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.2' was not found.
  - The following frameworks were found:
      2.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.15 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.2&arch=x64&rid=win10-x64
```
**dotnet info**

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by 491134648** [comment]
Microsoft.NETCore.App, version 3.1.2 is gone, integrated in the Microsoft.AspNetCore.App system framework, cannot be updated separately

**Comment by AnReZa** [comment]
I'm having the exact same problem. Is there a workaround?

**Comment by xiongdashan** [comment]
> I'm having the exact same problem. Is there a workaround?

Like it:
1. ``` dotnet tools uninstall -g dotnet-ef ```
2. ``` dotnet tool install -g dotnet-ef --version 3.1.0```
3. Reinstall dotnet runtime  dotnet-sdk-3.1.102 from https://download.visualstudio.microsoft.com/download/pr/5aad9c2c-7bb6-45b1-97e7-98f12cb5b63b/6f6d7944c81b043bdb9a7241529a5504/dotnet-sdk-3.1.102-win-x64.exe

Finally restart computer.

**Comment by stanislavromanov** [comment]
> > I'm having the exact same problem. Is there a workaround?
> 
> Like it:
> 
> 1. `dotnet tools uninstall -g dotnet-ef`
> 2. ` dotnet tool install -g dotnet-ef --version 3.1.0`
> 3. Reinstall dotnet runtime  dotnet-sdk-3.1.102 from https://download.visualstudio.microsoft.com/download/pr/5aad9c2c-7bb6-45b1-97e7-98f12cb5b63b/6f6d7944c81b043bdb9a7241529a5504/dotnet-sdk-3.1.102-win-x64.exe
> 
> Finally restart computer.

Some steps are redundant.

`dotnet tool uninstall -g dotnet-ef && dotnet tool install -g dotnet-ef --version 3.1.1`

**Comment by dayarias** [comment]
1. dotnet tool uninstall -g dotnet-ef
2. dotnet tool install -g dotnet-ef --version 3.1.1
![P1](https://user-images.githubusercontent.com/47326892/76017772-25a43500-5eed-11ea-9999-778c8ad9ebda.png)

This one worked for me, Already was installed lastest version of dotnet so there wasnt need to restart my pc 

Using 3.1.0 Gives me this message.

The EF Core tools version '3.1.0' is older than that of the runtime '3.1.1'. Update the tools for the latest features and bug fixes.

**Comment by dannypc1628** [comment]
I'm having the exact same problem, too.
My classmate say "Install .NET Core SDK  3.1.102，it is including 3.1.2 Runtime."

我有一樣的問題。結果，社團朋友說我只是沒安裝SDK  3.1.102。

**Comment by chainchung** [comment]
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.2&arch=x64&rid=win10-x64

download & Install the .NET Core Desktop Runtime. can fix this issue
