### ISSUE TITLE
RAZORSDK1006 warning

### ISSUE THREAD

**Issue by bstordrup** [dotnet/aspnetcore#19479]
### Describe the bug
I have an asp.net project that uses Microsoft.AspNetCore.Mvc package. This generates a compiler warning RAZORSDK1006 warning about Razor language version downgrade. According to the description, this is caused by a reference to Microsoft.AspNetCore.Razor.Design package.

This package is referenced by Microsoft.AspNetCore.Mvc package - can it be removed?

### Further technical details
- Targeting .net core 3.1
- Referenced version of Microsoft.AspnetCore.Mvc is 2.2.0
- IDE is Visual Studio 2019 v16.4.5

**Comment by rynowak** [comment]
Ideally a 3.1 project wouldn't be referencing MVC 2.2.0 - do you know why that's there? I would try to remove that.

@pranavkm

**Comment by bstordrup** [comment]
@rynowak, which version should I be using instead? Microsoft.AspNetCore.Mvc 2.2.0 is the latest available package on NuGet.

**Comment by rynowak** [comment]
Most ASP.NET Core libraries don't ship packages at all as of 3.0 - they are just included in a web project by default.  It should be safe to remove

**Comment by bstordrup** [comment]
@rynowak, thank you. Removing the packages fixed the issue.
