### ISSUE TITLE
AuthorizeView Roles doesn't work

### ISSUE THREAD

**Issue by AlcoGoblin** [dotnet/aspnetcore#19473]
Hello, I've been trying to get AuthorizeView Roles to work for quite a while and I've followed the simplest tutorials from scratch such as this: https://www.youtube.com/watch?v=8jD08VwNTnc , but it just doesn't work for me.

I'm trying this on a Blazor Server App with ASP.NET Core 3.1.1 and followed the tutorial as instructed. Do i not have something in my packages or are my extensions somehow messing things up? I really do not understand this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We suggest using the guidance from Microsoft Docs here: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio

Good luck learning Blazor 👍
