### ISSUE TITLE
Blazor WASM throwing an ILLINK error on .net standard 2.0 library

### ISSUE THREAD

**Issue by Pinox** [dotnet/aspnetcore#19475]
Hi Guys,

I use FFImageLoading extensively in Xamarin and UWP projects.  
As my existing class libraries is based on .net standard 2.0.  I would expect these libraries to work with Blazor WASM that already support .net standard 2.1.   At this stage I don't use any specific FFImageLoading functionality yet in Blazor just referencing the shared code libraries.

Currently when I reference a .net standard library (version 2.0) with FFImageLoading I immediately get the following error in Blazor or Mono to be specific.  (even on an empty class library with no code just the reference)

![image](https://user-images.githubusercontent.com/5297255/75626260-bcf84800-5bce-11ea-80c0-5cf11d4ed6d6.png)

Anyone has an idea what might cause this ??

plse see attached repo that replicates behavior.

[FFImageLoading.zip](https://github.com/dotnet/aspnetcore/files/4271841/FFImageLoading.zip)

Using latest 3.2 preview of Blazor.

thanks in advance for your attention.

**Comment by pranavkm** [comment]
This issue was moved to mono/mono#19097
