### ISSUE TITLE
Add XRequestedWith to HeaderNames

### ISSUE THREAD

**Issue by ssg** [dotnet/aspnetcore#19478]
### Is your feature request related to a problem? Please describe.
Yes, using hardcoded strings for header names are prone to typos and detecting the typos with HTTP header keys can be hard. Having well-known HTTP headers in HeaderNames makes sense to me, especially "X-Requested-With" which is quite common, contains multiple words, dashes, and passive voice. There is already XForwardedFor and as I understand there is no categorical rejection of XRequestedWith for some reason like discouraging the use of HTTP header to prevent bad practices and whatnot.

### Describe the solution you'd like
New field added to HeaderNames called XRequestedWith with a value of "X-Requested-With"

### Additional context
I already have a [PR open](https://github.com/dotnet/aspnetcore/pull/19470) but it has one flaky test failing. As I understand there is no policy-based counter argument against XRequestedWith so I'm creating this issue in order to keep traction on the PR.

**Comment by anurse** [comment]
Thanks for the PR!

**Comment by ssg** [comment]
My PR got approved, closing this, thank you everyone! :)
