### ISSUE TITLE
about webapi content response in v3.1

### ISSUE THREAD

**Issue by xmduane** [dotnet/aspnetcore#19488]
maybe it is a bug? my issue is like the code below!
 [ApiController]
    [Route("api/v31/demo")]
    public class WeatherForecastController : ControllerBase
    {

        [HttpPost("userlist")] 
        public object GetUserList()
        {
            Result result = new Result();

            Results<UserInfo> data = new Results<UserInfo>();
            data.value.AddRange(new UserInfo[] {
                new UserInfo { UID=1, FirstName="first name 1", LastName="last name 1", },
               new UserInfo { UID=2, FirstName="first name 2", LastName="last name 2",}
            });
            
            result.data = data; // in this case,the value of Results<T> will lost, but in sdk v2. it is work well.
             
            //result.data = new { pages = data.pages, total = data.total, value = data.value }; // in this case, the value of Result<T> can   response to client.

            return result;
        }
 
    }

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by xmduane** [comment]
[API22_31.zip](https://github.com/dotnet/aspnetcore/files/4278817/API22_31.zip)

**Comment by xmduane** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

[API22_31.zip](https://github.com/dotnet/aspnetcore/files/4278822/API22_31.zip)
