### ISSUE TITLE
rzc generate exited with code 1

### ISSUE THREAD

**Issue by Z0d1ak** [dotnet/aspnetcore#19480]
### Describe the bug
Trying to build default project using command 
`dotnet new  blazorhosted -o MyWebApp`.
 I download template using 
`dotnet new -i Microsoft.AspNetCore.Blazor.Templates`
Getting error when building client. 
**UPD:** 
After i downloaded new template command `dotnet new  blazorhosted -o MyWebApp` doesnt works
`dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1`

### Error text
Severity	Code	Description	Project	File	Line	Suppression State
Error		rzc generate exited with code 1.	MyWebApp.Client	C:\Users\Belov Boris\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0\targets\RazorCompilation.targets	184	

### dotnet info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.1.101
 Commit:    b377529961

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### VS2019 Community 16.4.5
[VisualStudio.txt](https://github.com/dotnet/aspnetcore/files/4272402/VisualStudio.txt)

**Comment by pranavkm** [comment]
@Z0d1ak you can install the blazorhosted template using this command `dotnet new blazorwasm -ho`
