### ISSUE TITLE
LiteDb doesn't insert data in .NET 5.0.100-preview.1.20125.9

### ISSUE THREAD

**Issue by DotNetAppCompatFeiWang** [dotnet/aspnetcore#19491]
### Describe the bug
LiteDb doesn' insert data in .NET 5.0.100-preview.1.20125.9

### To Reproduce

```C#
using LiteDB;
using System;
using System.IO;

 public class Author
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

using (var db = new LiteDatabase("mytest.db"))
            {
                var collection = db.GetCollection<Author>("authors");
                var author = new Author
                {
                    Id = Guid.NewGuid(),
                    FirstName = "Mark",
                    LastName = "Twain"
                };
                collection.Insert(author);
                var results = collection.Find(Query.All(Query.Descending), limit: 100);
                foreach (var item in results)
                {
                    Console.WriteLine(item.FirstName + " " + item.LastName + " " + item.Id);
                }
                Console.WriteLine("Record Count:" + collection.Count());
            }
```

### Further technical details
- ASP.NET Core version 
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version 

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20125.9
 Commit:    12e88ed2e5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20125.9\

Host (useful for support):
  Version: 5.0.0-preview.1.20120.5
  Commit:  3c523a6a7a

.NET Core SDKs installed:
  5.0.100-preview.1.20125.9 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.1.20122.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Verify Scenarios: 
1). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.1.20125.9: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build :  3.1.101   Pass

DEVDIV Bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1076180 (has repro machine info)

@dotnet-actwx-bot  FYI

**Comment by mkArtakMSFT** [comment]
@ajcvickers are we somehow involved in here? Wondering whether this should be moved to the LiteDB specific repository (3rd party).

**Comment by ajcvickers** [comment]
@mkArtakMSFT It looks like an external (LiteDB) issue to me.

**Comment by mbdavid** [comment]
This issue is related about .NET LiteDB Database (https://github.com/mbdavid/LiteDB). Open a bug report there that we can help.

**Comment by javiercn** [comment]
Closing as per @mbdavid suggestion.
