### ISSUE TITLE
AlwaysRunResultFilter does not work as expected since version 3.0

### ISSUE THREAD

**Issue by tamarachl** [dotnet/aspnetcore#19496]
### Describe the bug
According to documentation `AlwaysRunResultFilter` should run for all action results including authorization failure, but it doesn't. In case of Authorize-attribute `AlwaysRunResultFilter` is skipped.

https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#ialwaysrunresultfilter-and-iasyncalwaysrunresultfilter

### To Reproduce
Example:
``` C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddScoped<ResponseInterceptor>();
        services.AddControllers();
        services
            .AddAuthentication(options =>
            {
                options.DefaultChallengeScheme = "Bearer";
            })
            .AddJwtBearer();
        services.AddAuthorization(options =>
        {
            options.AddPolicy("MyPolicy", policy => policy.RequireClaim("scope", "..."));
        });
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseRouting();
        app.UseAuthentication();
        app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    }
}

public class ResponseInterceptor : IAsyncAlwaysRunResultFilter
{
    public async Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
    {
        await next();
    }
}

[ApiController]
[Route("[controller]")]
[ServiceFilter(typeof(ResponseInterceptor))]
public class TestController : ControllerBase
{
    [HttpGet]
    [Route("get1")]
    [Authorize("MyPolicy")]
    public IActionResult Get1()
    {
        return Ok();
    }

    [HttpGet]
    [Route("get2")]
    public IActionResult Get2()
    {
        return Unauthorized();
    }
}
```
**Expected result:**
Both endpoints cause invocation of `ResponseInterceptor`.

**Actual result:**
Only get2-endpoint causes invocation of `ResponseInterceptor`.

### Further technical details
- It does not work in .NET Core 3.0 and 3.1
- The similar approach works fine in .NET Core 2.2

**Comment by pranavkm** [comment]
@tamarachl as of 3.0, Authorization occurs as part of the [authorization middleware](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#authorization). In case, the middleware forbids or issues a challenge, the request does not get to MVC. This would explain why you don't see the filter executing.

What is it that you're attempting to use the filter for? You might be able to author a middleware to replace it.

**Comment by tamarachl** [comment]
@pranavkm thank you for the answer ;)

I need to override few type of responses (such as Unauthorized, Forbidden, BadRequest, NotFound, etc) in order to ensure the same format within whole API in our service. `AlwaysRunResultFilter` looks like perfect place to do that :)

You are right, the middleware is an option in case of Unauthorized response that is caused by attribute, but unfortunately i can't override already started responses in the middleware. So i should handle some responses in the filter and some in the middleware... that IMHO is a little bit ugly :) I prefer to have one place to transform final response of API, like i do it in Core 2.2 :)

**Comment by pranavkm** [comment]
Sorry I missed your earlier response. You could consider disabling endpoint routing to get the 2.2 compatible behavior: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#use-mvc-without-endpoint-routing
