### ISSUE TITLE
Blazor performance metrices Idle time

### ISSUE THREAD

**Issue by Venkat4655** [dotnet/aspnetcore#19497]
Thanks for looking this issue

### Describe the bug
Idle time is more when we run the own project in Blazor application

We have checked the performance metrics in browser performance window.  you can refer following snapshot for details,

![image](https://user-images.githubusercontent.com/31058118/75683921-f78cde00-5cbd-11ea-9c24-ec6966c5b73c.png)

In above picture seems idle time was **1231 ms**. What is the cause of this idle time getting delay? Can anyone help me on this?

### Further technical details
- ASP.NET Core version - 3.1
-SDK version 3.1.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. What is the specific scenario you're trying to measure this in?

**Comment by mkArtakMSFT** [comment]
Also, it's not clear why this is a problem. Please clarify.

**Comment by Venkat4655** [comment]
Thanks for looking this issue

We have developed the application using Blazor component(Server side Blazor Application). We just run the sample in Chrome browser. In that scenario, we have checked the performance metrics it shown idle time around **1250ms** as we posted earlier. 

We faced this issue while run/launch the application in Chrome browser. so the replication procedure was simple

**Note**:We using JSInterop for communicate the JavaScript function

**Comment by mkArtakMSFT** [comment]
@Venkat4655 I'm trying to understand what is the `IdleTime` metric you're tracking? Is it being reset when you interact with the app? If so, given that it's manual, maybe your inactivity results in that value?
Alternatively, if this is some kind of automated logic, which is supposed to run the same way on both browsers yet results in drastically different results, we will need to have a repro project (simplified to the bare bones to illustrate the problem, ideally hosted in GitHub) to be able to investigate further.
