### ISSUE TITLE
SVG Sprite in a Layout Page, Blazor

### ISSUE THREAD

**Issue by KKacer** [dotnet/aspnetcore#19490]
I created 2 SVGs, which the 2nd one is a SVG sprite, the first will be visible as expected.
the sprite one (2nd) isn't shown. guess can make it visible via a hack by the help of routing and NavigationManager, but not sure if it is normal that it isn't shown normally this way or not. Can it be visible just by changing the href tag anyhow or not?

`             <svg class="c1icon"><use href="images/spriteTest.svg#aaa" /></svg>`

I want to use the sprite inside the MainLayout (or any Layout page).

Can anyone please let me know what is the issue here? Should I get the address manually via NavigationManager and then bind it there?

Not sure if it could be counted as a bug/'feature request' (about more support on auto-correct and bind the proper address), cause we might expect the razor be able to route to the **href** tag of the **SVG Use**, or maybe that's just a normal behavior and I should manually find and bind the address.

Code is available here:
https://github.com/KKacer/BlazorSVG-issue

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will be handling SVG support as a combined effort probably during 5.0 release.

**Comment by mkArtakMSFT** [comment]
Closing as we will be tackling this as part of https://github.com/dotnet/aspnetcore/issues/18271
