### ISSUE TITLE
Precompression interferes with service worker asset manifest

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19503]
While writing up CTI steps for PWA scenarios, I found there's a regression in the service worker asset manifest due to precompression. It now lists all the precompressed files, as well as the uncompressed ones:

![image](https://user-images.githubusercontent.com/1101362/75695965-be934000-5ca2-11ea-93e4-789de4c2e218.png)

@javiercn Can you comment on how you think this should best be handled within the context of SWA? Is it possible to add some extra metadata to the precompressed items so we don't include them in cases like this where we're describing things from the point of view of the browser?

**Comment by javiercn** [comment]
@SteveSandersonMS we would need to filter them when we generate the manifest

**Comment by SteveSandersonMS** [comment]
Do you have a recommended way to do that? Presumably not by file name, since this includes user-supplied files. Should we add some metadata when generating the compressed items?

**Comment by javiercn** [comment]
@SteveSandersonMS Filtering on the extension should be just fine for preview2.

Here's the associated PR with a test included to validate the manifest generation.
https://github.com/dotnet/aspnetcore/pull/19525

**Comment by SteveSandersonMS** [comment]
@javiercn Can be closed now?
