### ISSUE TITLE
Endpoint Routing: AuthorizeAttribute is not found in the list of controller filters

### ISSUE THREAD

**Issue by mgolois** [dotnet/aspnetcore#19502]
Hello team and @rynowak  
While migrating code to the new endpoint routing, I'm seeing this issue.
Here is a simplified version of the issue. Source code can be found https://github.com/mgolois/Routing-Endpoint-Filter-Convention-Issue

In the nutshell, this code worked fine before Endpoint routing. In a controller model convention, I look for Authorization filter to either remove it or change the policy. Though the base class has a the authorize attribute, my controller model convention finds zero authorization filter for the home controller. Any thoughts?

BaseController.cs:

> [Authorize(Policy = "defaultpolicy")]
>     public class BaseController: Controller
>     {
>     }

HomeController.cs

> public class HomeController : BaseController
> {
>     public IActionResult Index() { return View();   }
> }

Startup.cs

``` 
public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthorization(opt => opt.AddPolicy("defaultpolicy", 
                                     policy => policy.Requirements.Add(new RoleRequirement())));
            services.AddMvc(opt =>  opt.Conventions.Add(new AddAuthFilterControllerConvention()));
        }
```

AddAuthFilterControllerConvention.cs
```
 public class AddAuthFilterControllerConvention : IControllerModelConvention
    {

        public void Apply(ControllerModel controller)
        {
            var filters = controller.Filters.Where(f => f.GetType() == typeof(AuthorizeFilter));

            foreach (var authFilter in filters)
            {
                var removeFilter = (authFilter as AuthorizeFilter)?.Policy.Requirements.FirstOrDefault(r => r.GetType() == typeof(RoleRequirement));

                if (removeFilter != null)
                {
                    controller.Filters.Remove(authFilter);
                }
            }
        }
    }
```

**Comment by rynowak** [comment]
I can say this is definitely expected. We don't use `AuthorizeFilter` with endpoint routing unless someone manually applied it. 

As far as how to implement what you need, we can try and help you out, but the solution might end up being different. What are you ultimately trying to do?

**Comment by mgolois** [comment]
@rynowak We have a base controller with a default policy, the requirement is to change the policy of 2   controller areas (e.g. Students and Instructors mvc areas) to 2 other  different policies. We used to that by removing and adding AuthorizeFilter when those controllers were called.
