### ISSUE TITLE
AddIdentity extension blocks JwtBearerOptions configure

### ISSUE THREAD

**Issue by antonGritsenko** [dotnet/aspnetcore#19512]
ASP.NET Core 3.1.0 + IdentityServer4.
Application generated from OOB template "Web Application -> Angular" with build-in user authentication option

I want to combine [Customize the API authentication handler (link 1)](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#customize-the-api-authentication-handler) and [Identity model customization in ASP.NET Core  (link 2)](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#customize-the-model)

This is default configuration of the template + changes from link 1:
```
// startup.cs, only valuable lines  are shown
...
services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
....
services.AddAuthentication().AddIdentityServerJwt();
services.Configure<JwtBearerOptions>(
     IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
     options =>
     {
        // breakpoint on next line, it works
        var onTokenValidated = options.Events.OnTokenValidated;
       ...
     });
```

This works just perfect.

Now let's add code from link 2:
```
// startup.cs, only valuable lines are shown
...
services.AddIdentity<ApplicationUser, ApplicationRole>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultUI()
                .AddDefaultTokenProviders();
....
services.AddAuthentication().AddIdentityServerJwt();
services.Configure<JwtBearerOptions>(
     IdentityServerJwtConstants.IdentityServerJwtBearerScheme,
     options =>
     {
        // breakpoint on next line, never hits
        var onTokenValidated = options.Events.OnTokenValidated;
       ...
     });
```
This just doesn't work. The option lambda never called, breakpoint never hits.

Even more, I tried to implement same with ```IConfigureNamedOptions<JwtBearerOptions>``` and ```services.AddTransient<IConfigureOptions<JwtBearerOptions>, MyJwtBearerConfigurator>``` - same result, works with ```AddDefaultIdentity<TUser>```, but ```MyJwtBearerConfigurator``` never executed with ```AddIdentity<TUser, TRole>``

Any ideas why??

**Comment by antonGritsenko** [comment]
@Tratcher any thoughts on this? Thank you.

**Comment by Tratcher** [comment]
Your `Configure<JwtBearerOptions>` callback will only be called if something in the app calls Aluthenticate or Challenge with the scheme name IdentityServerJwtBearerScheme. AddIdentity sets the default auth schemes for the app (cookies).

How are you specifying in the rest of the app that IdentityServerJwtBearerScheme should be used? Via AuthenticationOptions defaults, authorization policies, Authorize attributes, etc?

**Comment by antonGritsenko** [comment]
@Tratcher to be honest, I don't for both cases, since I thought it have to be handled by the AddIdentity in a same way as AddDefaultIdentity do, but I was not to track down to source code where this schema added. 
If we will take a look on [AddDefaultIdentity](https://github.com/aspnet/Identity/blob/feedcb5c53444f716ef5121d3add56e11c7b71e5/src/UI/IdentityServiceCollectionUIExtensions.cs#L49), there is call to ```AddAuthentication```:
```
services.AddAuthentication(o =>
{
      o.DefaultScheme = IdentityConstants.ApplicationScheme;
      o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
})
```
and there is quite the same for [AddIndenity](https://github.com/aspnet/Identity/blob/feedcb5c53444f716ef5121d3add56e11c7b71e5/src/Identity/IdentityServiceCollectionExtensions.cs#L45)
```
 services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
                options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
                options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            })
```

And OK, miss match between schema could the case for ```Configure<JwtBearerOptions>```, but why then ```IConfigureNamedOptions<JwtBearerOptions>`` also doesn't work?

**Comment by antonGritsenko** [comment]
Found: the IdentityServerJwtConstants.IdentityServerJwtBearerScheme schema added by [AddIdentityServerJwt](https://github.com/aspnet/Identity/blob/feedcb5c53444f716ef5121d3add56e11c7b71e5/src/ApiAuth.IS/Authentication/AuthenticationBuilderExtensions.cs#L33) for both cases.

**Comment by Tratcher** [comment]
Ah, so depending on the order in which you call Add*Identity or AddIdentityServerJwt, your default auth scheme could be overwritten.

**Comment by antonGritsenko** [comment]
the services.AddAuthentication().AddIdentityServerJwt(); is always after Add*Identity. Here is full code of the ConfigureServices I'm using for testing:
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));
             // doesn't works
            services.AddIdentity<ApplicationUser, ApplicationRole>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultUI()
                .AddDefaultTokenProviders();

            // works
            //services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
            //    .AddEntityFrameworkStores<ApplicationDbContext>();


            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();


            services.AddAuthentication().AddIdentityServerJwt();

            services.AddControllersWithViews();
            services.AddLogging();

            services.AddAuthorization();
      }
```

**Comment by Tratcher** [comment]
Ok, well you don't have an authorization policy so your controllers must be marked with the `Authorize` attribute? What gets passed there?

**Comment by antonGritsenko** [comment]
Just clean attribute: 
```
    [Authorize]
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
```
I didn't touch default template's code expect code from links above.

**Comment by Tratcher** [comment]
@blowdart @HaoK There are conflicting kinds of auth in this app, how is it supposed to work?

**Comment by HaoK** [comment]
Generally don't call AddIdentity if you want fine grain control over auth, calling AddIdentityCore and the other identity builder methods you need will setup identity without auth, then you can call AddAuthentication() and configure things exactly how you want, if you don't want any of the identity cookies and what not

**Comment by antonGritsenko** [comment]
@HaoK how to use ```ApplicationRole``` then from https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#customize-the-model? AddIdentityCore doesn't support it.

**Comment by HaoK** [comment]
What do you mean it doesn't support it, you can call AddRole on the IdentityBuilder

**Comment by antonGritsenko** [comment]
@HaoK didn't known that. I will try.
If this is the case, then this means the article is not correct because it clearly mentioned to use AddIdentity?

**Comment by HaoK** [comment]
I'm not sure what article you are referring to but its likely not talking about what you are trying to do

**Comment by antonGritsenko** [comment]
@HaoK link was in two posts above: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#customize-the-model

Code from the link:
```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));

    services.AddIdentity<ApplicationUser, ApplicationRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultUI()
            .AddDefaultTokenProviders();

    services.AddMvc()
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

**Comment by blowdart** [comment]
This is also mixing in the SPA pieces, so @javiercn to look as well.

**Comment by javiercn** [comment]
@blowdart took a quick look, can't seem to find a specific issue WRT why the callback would never hit. I'm not exactly sure about what AddIdentity does differently from AddDefaultIdentity, but I imagine that the root cause of the issue is there.

**Comment by Tratcher** [comment]
Theory: 

Working:
AddDefaultIdentity sets DefaultScheme.
AddIdentityServerJwt sets DefaultScheme and overwrites the value set by AddDefaultIdentity. Authenticate and Challenge use the default scheme because no other values are set.

Not working:
AddIndentity sets DefaultAuthenticateScheme and DefaultChallengeScheme rather than DefaultScheme.
AddIdentityServerJwt sets DefaultScheme, which doesn't override DefaultAuthenticateScheme or DefaultChallengeScheme.
Authenticate uses DefaultAuthenticateScheme rather than DefaultScheme.
Challenge uses DefaultChallengeScheme rather than DefaultScheme.

Workaround:
```
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = IdentityServerJwtConstants.IdentityServerJwtScheme;
                options.DefaultChallengeScheme = IdentityServerJwtConstants.IdentityServerJwtScheme;
            })
```

**Comment by antonGritsenko** [comment]
@Tratcher workaround works. Is this a really workaround and have to be fixed in next releases or we have to live with that?

**Comment by antonGritsenko** [comment]
Repro and playground:
https://github.com/antonGritsenko/webAppNetCore3.1Playground
 - it use InMemoryDB to quick deploy
 - you can switch between configuration to choose AddIdentity\AddDefaultIdentity

**Comment by Tratcher** [comment]
Now that we've confirmed the problem we still need to decide what to do about it.

@HaoK the odd one out here is AddIdentity. Why does it set DefaultAuthenticateScheme and DefaultChallengeScheme rather than just setting DefaultScheme?

**Comment by HaoK** [comment]
That's what it always did, so mostly just for legacy reasons, its definitely a breaking change to go from setting the granular defaults to setting all the defaults.  The idea was to leave the old AddIdentity alone.  AddIdentityCore is the new more granular api to use.

**Comment by javiercn** [comment]
Could we do this as part of 5.0?

**Comment by HaoK** [comment]
New apps should be using AddIdentityCore or AddDefaultIdentity which already do the right thing, I'm not sure making the migration story more complex for older apps is worth it at all, when those are the apis that were added explicitly to make composition of auth like this possible.

**Comment by anurse** [comment]
As per @HaoK 's comments, we don't believe there's further work here. Using the newer `AddIdentityCore`/`AddDefaultIdentity` APIs are the preferred way to resolve this issue.
