### ISSUE TITLE
Memory leak when use Microsoft.AspNetCore.Authentication.JwtBearer

### ISSUE THREAD

**Issue by cycbluesky** [dotnet/aspnetcore#19523]
My project use JwtBearer middleware to make authentication. After I upgraded the project from .net core 2.1 to .net core 3.1, I encountered memroy leak problem.  I used diagnostic tools to monitor the memory and found that too many authentication releated objects created and cannot be freed by GC.  That's never happened in pervious version.

I created a sample project [here](https://github.com/cycbluesky/JwtBeaMemoryLeak) that can reproduce this problem. 

![memoryLeak_end](https://user-images.githubusercontent.com/1295959/75749969-0cb94980-5d5e-11ea-8c16-67a1bcb70a37.jpg)
![DiagnosticeTools-3-2](https://user-images.githubusercontent.com/1295959/75749993-18a50b80-5d5e-11ea-90bf-9610fae3f61a.jpg)

========================================
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

**Comment by javiercn** [comment]
@cycbluesky thanks for contacting us.

Is there any OutOfMemoryException caused? From what I can see, the pattern looks normal, the GC will simply continue to allocate objects until it gets to a memory threshold (as seems to be the case above) at which points you see the GC run and free all the memory from the orphaned objects.

@Tratcher @sebastienros Is there any additional information here you want to add?

**Comment by cycbluesky** [comment]
@javiercn Each request will cause the memory increase continuously and the memory usage never drop down even no incoming traffic. I think it will run out of memory as long as I keep sending requests.

**Comment by javiercn** [comment]
> Each request will cause the memory increase continuously and the memory usage never drop down even no incoming traffic

I believe that is expected. The server will not start a collection unless it has to because it is running low on memory. The reasoning is, if there's memory available why would I spend cycles on GC that can be spent running the app.

As I said, not an expert in this area, but the pattern that you are seeing feels normal to me. Unless the GC is triggered an the memory can't be reclaimed, I don't believe there's a memory leak here, but if you want to confirm this, just keep sending requests and you'll get to a point where the memory gets collected or the app throws an OutOfMemoryException.

**Comment by cycbluesky** [comment]
According to the rate of memory increase, I believe that memory will be exhausted soon. It was not never happened when I was using .Net core 2.1 with the same code. 
Maybe you can have a try the project I provided, It's simple, build and run it, then make a large number of requests via some tools.  The memory usage will increase more and more and never stop even the GC is on working.

**Comment by blowdart** [comment]
GC doesn't kick in until it's needed. When you say GC is working, how do you know? Can you actually cause an out of memory error with lots of requests?

**Comment by sebastienros** [comment]
The GC is actually triggered as seen on the screenshots. The one with the custom plot (glad that you used it BTW) doesn't show for how long it ran, and how it got to 1.6GB. 

@cycbluesky How much memory and how many cores does this machine have?

I will try an run the app locally for a long time as you provided it.

@javiercn @blowdart can you check if the code seems correct in terms of usage? At least this folder and the Startup.cs: https://github.com/cycbluesky/JwtBeaMemoryLeak/tree/master/src/JwtBearMemoryLeak/Authentications

**Comment by blowdart** [comment]
It looks ok, but you're deep into Wilson now, so it may be something in there that's holding onto things

**Comment by Tratcher** [comment]
In your VS screen shot you've highlighted `Dictionary<String, Int32>`. Can you expand the Paths to Root section and follow the tree under AsymemetricSignatureProvider. What's rooting that tree?

**Comment by Tratcher** [comment]
Is this part being run per request? That would be in-efficient. Setting a breakpoint would tell you.
https://github.com/cycbluesky/JwtBeaMemoryLeak/blob/9a40e609ee25e5179f9255128793567fdb674eaa/src/JwtBearMemoryLeak/Authentications/CustomJwtBearerOptions.cs#L70-L73

**Comment by cycbluesky** [comment]
@Tratcher Yes, it's true. IssuerSigningKeyResolver will be run per request. This delegate is useful when you want to get different SecurityKey via  parameter **kid**. That's to say, in multi tenant scenario, each tenant has different key.
@sebastienros I created two branches(netcore21 & netcore31) for Your reference. Both of them have almost same code, but netcore21 works well, necore 31 does not.
The initial memory usage is 100M or so and then, it will increase more and more until to G level when you make a lot of requests. After stopped, it will not drop down.  
My machine have 4 cores and 16G memory, and I don't think I should run it until memory exhausted since the problem is obvious. I captured some snapshots, you can find them here.  [https://github.com/cycbluesky/JwtBeaMemoryLeak/tree/master/src/JwtBearMemoryLeak/images](url)

**Comment by Seabizkit** [comment]
Im also seeing odd behavior and it extremely hard to tell who or what is at fault. making lots of request.. the amount of Live instance of DBContext does not go down... it doesnt go up either at the rate at which im creating... so it really hard to figure out.

9 instance are floating about after like making 3000 requests.

below is the allocation stack  form one of then 9
![image](https://user-images.githubusercontent.com/1920090/80921833-1587c500-8d79-11ea-8e0e-ba0e5710eea3.png)

**Comment by huang-tianwen** [comment]
@cycbluesky any update on this one?
I am facing the same issue right now.
it force me to keep restarting the pod.

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
