### ISSUE TITLE
Build NuGet packages from source

### ISSUE THREAD

**Issue by michaelmualem** [dotnet/aspnetcore#19528]
Hello,
I am trying to build two NuGet packages from source: Microsoft.AspNetCore.Authentication.JwtBearer
Microsoft.AspNetCore.Mvc.NewtonsoftJson

I have installed all the prerequisites and run the script aspnetcore\build.cmd but I get the following error:
Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-aspnet-AspNetCore-Tooling-07f16c89/nuget/v3/index.json. Response status code does not indicate success: 401 (Unauthorized). Build failed.

What am I doing wrong ? Please help.

Best regards,
Michael

**Comment by Pilchie** [comment]
@dotnet/aspnet-build - this is the internal feed right.  Is the solution just to remove that because the packages are now public?

**Comment by wtgodbe** [comment]
Yes, that's the internal build. @michaelmualem are you building the `v3.1.1` tag? If so, you just need to remove the following lines: https://github.com/dotnet/aspnetcore/blob/e276c8174b8bfdeb70efceafa81c75f8badbc8db/NuGet.config#L9-L12

The reason this happened is that 3.1.1 was built through our internal channels, and therefore used internal (non-public) feeds for publishing packages. The `v3.1.1` tag corresponds the exact commit we built for 3.1.1, which (at the time) still used those internal feeds. The packages are now publicly available on nuget.org, so those feeds can be safely removed from nuget.config. We're aware this is inconvenient, and are tracking improving the process so that release tags corresponding to internally built releases can be built out-of-the-box. @mmitche is there any update on that (or an open issue)?

**Comment by michaelmualem** [comment]
Many thanks it was helpful.

Next, I am getting this error, after many warnings of "Could not find file" in the src\submodules folder (actually this folder is empty, is it supposed to be ?) :

error : An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.4.0.tgz: ESOCKETTIMEDOUT". [\aspnetcore\src\Components\Web.JS\Microsoft.AspNetCore.Components.Web.JS.npmproj]
\aspnetcore\eng\targets\Npm.Common.targets(60,5): error : Command failed with exit code 1.

**Comment by Pilchie** [comment]
See the section on submodules in the [docs](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md#clone-the-source-code)

**Comment by michaelmualem** [comment]
Hi,
I have built the two packages:
Microsoft.AspNetCore.Authentication.JwtBearer 3.1.1
Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.1.1

I do not manage to reference these packages in my .Net Core project.
"Unable to find package Microsoft.AspNetCore.Mvc.ViewFeatures with version (>= 3.1.1-dev)"
Do you have any idea how to resolve this ?

**Comment by Pilchie** [comment]
Once you have built them, you need to put the `.nupkgs` somewhere and add it as a NuGet package source to use them. Have you done that?  What does your .csproj file look like?

**Comment by michaelmualem** [comment]
Yes this is what I did. What these packages has to do with "ViewFeatures" ?

**Comment by Pilchie** [comment]
Ah.  When you build the packages locally, their dependencies get updated to match the local build version. You probably need to do something to edit the `.nuspec` if you want to use only some of the packages, and not the entire build output.

**Comment by dougbu** [comment]
&hellip; or copy pretty much everything that lands in artifacts/packages/Debug/Shipping into your local NuGet package source e.g. use _that_ directory as your added source location

**Comment by michaelmualem** [comment]
I have built Microsoft.AspNetCore.Mvc.ViewFeatures as well and added it to my source directory. 
Microsoft.AspNetCore.Mvc.NewtonsoftJson did resolved but Microsoft.AspNetCore.Authentication.JwtBearer did not. 
still the same error.... do I miss another dependency ?

**Comment by michaelmualem** [comment]
In addition, I replaced the packages with their source code and ran the project, but I get a runtime exception: "Could not load file or assembly 'Microsoft.AspNetCore.JsonPatch, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference."

What should resolve this ?

**Comment by dougbu** [comment]
@michaelmualem I suggest giving up on trying to build a small subset of the repo. Instead execute the root build script with its `-pack` / `--pack` command-line argument then make the entire artifacts/packages/Debug/NonShipping directory the package source for your test project.

Given the errors you're seeing, I wouldn't be surprised if some packages have already been installed into .nuget/packages and that persists the issues. Might want to add `/p:DotNetUseShippingVersions=true` or something like `/p:OfficialBuildId=20200315.6` (incrementing as needed) to generate unique package versions

**Comment by michaelmualem** [comment]
Ok I manages to replace all sources but I am still getting thr runtime exception: 'Microsoft.AspNetCore.JsonPatch, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference."

Although the JsonPatch assembly v 3.1.1 is located in the publish folder of the project. What can cause the problem ?

**Comment by dougbu** [comment]
In that case, one of two things is likely going South:
1. Your ~/.nuget/packages folder contains the expansion of older *-dev packages you created locally (while you were trying to create packages piecemeal). You could start from scratch i.e. run `dotnet nuget locals all --clear` or delete the individual *-dev folders under ~/.nuget/packages.
2. The 3.1 targeting pack is confusing the build process. I'm not sure of the best way to disable its use in your project. @JunTaoLuo and @wtgodbe do you have good suggestions -- avoiding some of the hacks we use in this repo?

**Comment by wtgodbe** [comment]
@michaelmualem you are building the 3.1.1 tag, which includes a busted targeting pack - can you try instead building the `v3.1.2` tag?

**Comment by random82** [comment]
Same happens on v3.1.6 tag

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the questions asked here have been answered.
