### ISSUE TITLE
gRPC-Web issues

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#19540]
This is more of an FYI as I am experiencing the issue noted while using nightly builds of the gRPC packages.

I have an application (ASP.Net Core 3.2.0-Preview1) in which I changed out a REST API DAL for a gRPC-Web DAL. I followed the guidance of the Steve Sanderson blog post. My solution can be run as either CSB or SSB and I was successful with gRPC-Web in both configurations (I did have to advance to a newer version of the gRPC.* nuget packages, I was still in 2.27.0 nightly build range).

I mistakenly did further updates from the nightly builds and I then had gRPC packages at version 2.28.0-pre1. I say mistakenly because my two working solution deployments each fail after this update.

SSB - The client reports an error of "Unhandled exception rendering component: Could not load file or assembly 'System.Text.Json, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified."
[SOLUTION] By simply adding an explicit nuget package of System.Text.Json (4.7.1) to my web server project this error goes away and everything functions.

CSB - At the same point in the client when receiving the first gRPC-Web response I am getting an error of "WASM: Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")".
[SOLUTION] Returning to versions 2.27.0/2.27.0-Pre1 for all of the gRPC.* packages from the NuGet feed resolves this issue.

Sorry for the verbosity, but finally, two questions:

-  Is it possible to use another json serializer/deserializer in gRPC/gRPC-Web?
- Will the gRPC/gRPC-Web packages be 'aligned' with the ASP.Net Core 3.2-Preview 2 or will accessing nightly builds be required?

**Comment by JamesNK** [comment]
Sorry for the delay replying.

System.Text.Json has no relation to gRPC. Neither should effect the other.

`Grpc.Net.Client.Web` was fixed a few weeks ago. 2.27.0-pre2 fixes the issue - https://www.nuget.org/packages/Grpc.Net.Client.Web/2.28.0-pre2
