### ISSUE TITLE
HttpClient Timout exception thrown differences between Kestrel and TestServer

### ISSUE THREAD

**Issue by damianh** [dotnet/aspnetcore#19541]
### Describe the bug

While testing sad-paths in my app with `HttpClient.Timeout`, I've discovered that there are behavioral differences between TestServer and Kestrel in that they throw different exceptions when HttpClient.Timeout elapses. And in ANC2.1, no exception is thrown at all for TestServer. Creating this issue because I think they should be alligned at the exeception type level. If people are writing an integration test for this scenario, their code might be against the wrong exception type than they might get in production (well happened to me).

|     | TestServer                  | Kestrel               |
|-----|-----------------------------|-----------------------|
| 2.1 | _No exception thrown_       | TaskCanceledException |
| 3.0 | OperationCancelledException | TaskCanceledException |
| 3.1 | OperationCancelledException | TaskCanceledException |

### To Reproduce

The code has two tests, one with TestServer and one with Kestrel, which an HttpClient timeout of 1 second, that make a request to an endpoint that waits 5seconds before responding.

``` C#
using System;
using System.Linq;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace XUnitTestProject1
{
    public class UnitTest1
    {
        [Fact]
        public async Task TestServer()
        {
            var webHostBuilder = new WebHostBuilder()
                .UseStartup<Startup>();

            var testServer = new TestServer(webHostBuilder);

            var httpClient = new HttpClient(testServer.CreateHandler())
            {
                BaseAddress = new Uri("http://sample.com/slow"),
                Timeout = TimeSpan.FromSeconds(1)
            };

            // Does not throw on ANC2.1 and completes after 5s.
            // OperationCancelledException on ANC 3.0 / 3.1
            await httpClient.GetAsync("/slow"); 
        }

        [Fact]
        public async Task Kestrel()
        {
            var webHost = new WebHostBuilder()
                .UseStartup<Startup>()
                .UseKestrel()
                .UseUrls("http://*:0")
                .Build();

            await webHost.StartAsync();

            var port = webHost.GetServerPort();

            var httpClient = new HttpClient
            {
                BaseAddress = new Uri($"http://localhost:{port}"),
                Timeout = TimeSpan.FromSeconds(1)
            };

            // TaskCanceledException on ANC 2.1/3.0/3.1
            await httpClient.GetAsync("/slow"); 

            await webHost.StopAsync();
        }

        public class Startup
        {
            public void ConfigureServices(IServiceCollection services)
            {}

            public void Configure(IApplicationBuilder app)
            {
                app.Map("/slow", slowApp =>
                {
                    slowApp.Run(async ctx =>
                    {
                        await Task.Delay(TimeSpan.FromSeconds(5));
                    });
                });
            }
        }
    }

    internal static class WebHostExtensions
    {
        internal static int GetServerPort(this IWebHost server)
        {
            var address = server.ServerFeatures.Get<IServerAddressesFeature>().Addresses.First();
            var match = Regex.Match(address, @"^.+:(\d+)$");
            var port = 0;

            if (match.Success)
            {
                port = int.Parse(match.Groups[1].Value);
            }

            return port;
        }
    }
}

```

My csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.1;netcoreapp3.0;netcoreapp3.1</TargetFrameworks>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="Shouldly" Version="3.0.2" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.0'">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="3.0.3" />
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="3.1.2" />
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

</Project>
```
-->

### Further technical details

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by damianh** [comment]
While TestServer on ANC3.0/3.1 "fails" it does so after 5 seconds so doesn't look like it's respecting the timeout property at all.

![image](https://user-images.githubusercontent.com/57436/75822985-39428500-5da1-11ea-8a37-a6e0bf75f765.png)

**Comment by Tratcher** [comment]
While the exception type difference is unfortunate, this is one area where we intentionally don't try to maintain functional parity. TestServer's goal is to accurately represent server behavior, not client behavior. That means we sometimes allow the client to observe things it wouldn't normally be able to like directly observing exceptions that were thrown in the server code. It can make tests much easier to debug.

When you're using HttpClient with Kestrel there's a Socket and real network calls in between. When a timeout happens the client immediately closes the socket and looses visibility into what happens on the server.

For TestServer there's no network involved, the HttpClient instance directly communicates with the server data structures. The timeout flows as a CancellationToken to HttpContext.RequestAborted. When triggered the request and response body are aborted but it's still possible to observe the server behavior such as by exceptions thrown.

As for general guidance, TestServer is useful for unit testing individual components like middleware. If you want to do full integration testing between a client and server then Kestrel is a better choice.

**Comment by damianh** [comment]
Thank you for fast response; that makes sense.

Perhaps the docs or xml comments around `TestServer` or `TestSever.CreateClient` could make this clearer? This document is all about integration tests with TestServer but could probably do with an update with what you mentioned: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1 (yeah the "integration" term here might be a bit ambigious).

**Comment by Tratcher** [comment]
Fair enough. Let us know if you see anywhere else that could use clarifying.

**Comment by anurse** [comment]
Planning Notes: There are a bunch of differences between TestServer and Kestrel. Long-term we have thoughts on unifying around an in-memory Kestrel testing pattern, but until then we think the best approach here is to doc up a few of the known differences as well as a message indicating that full parity with Kestrel is not expected.

**Comment by Tratcher** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/18259
