### ISSUE TITLE
There is no tracked object with id 'x'. Perhaps the DotNetObjectReference instance was already disposed

### ISSUE THREAD

**Issue by webebox** [dotnet/aspnetcore#19542]
### Describe the bug
I have a page with a form that edits a Model (named Group), for the first component render, everything is OK and I edit and update the model correctly, but when I leave the page (_objRef is disposed) and return back to the page (component rerenderd for the second time),when I try to edit the Model it raises "There is no tracked object with id 'x'. Perhaps the DotNetObjectReference instance was already disposed." However I have disposed the DotNetObjectReference but it seems that the older bojectReference is calling.

OnAfterRenderAsync Method :
```
private DotNetObjectReference<Groups> _objRef;

protected override async Task OnAfterRenderAsync(bool firstRender)
{
    await base.OnAfterRenderAsync(firstRender);
    if (firstRender)
    {
        _objRef = DotNetObjectReference.Create(this);
        await JSRuntime.InvokeVoidAsync("JSFun", _objRef);
    }
}`

JSInvoke Method :
`[JSInvokable]
public void UpdateModel(string Id)
{
    Group = GroupService.Get(new Guid(Id));
    StateHasChanged();
}`

Dispose Method :
`public void Dispose()
{
     _objRef?.Dispose();
}
```

Javascript Function : **(Here in the second page render the error raises)**
```
$(document).on('click', '.btnEdit', function () {       
    instance.invokeMethodAsync('UpdateModel', Id).then(c => {         
        editModal.modal('show');
    });
});
```

Thanks

**Comment by webebox** [comment]
I solve the problem by changing the event handler from $(document).on('click' to wrapperInstance.on('click' where wrapperInstance is a wrapper to my current component :

`var wrapper = $("#wrapper"); wrapper.removeClass(); wrapper.addClass("wrapper" + instance["_id"]); var wrapperInstance = $(".wrapper" + instance["_id"]);`

note that I have added a wrapper to my component like this :

`<div id="wrapper">
  component content
</div>`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Glad that you've resolved the problem yourself!
