### ISSUE TITLE
After updating some packages to get EF Core to work with Blazor WASM, "mscorlib.dll" no longer can be loaded in the web client.

### ISSUE THREAD

**Issue by Tonur** [dotnet/aspnetcore#19554]
I have had issues with creating a new default template of Blazor Web Assembly after installing some updates to packages seperately.
It doesn't matter whether I create the project as "Asp.Net Core Hosted" or not, the issue only affects my pc.
I have transfered the solution and project files onto some colleagues pc, and they can get it to run just fine.

The issue I am receiving is as follows:

blazor.webassembly.js:1 
WASM: The assembly mscorlib.dll was not found or could not be loaded.
blazor.webassembly.js:1 
WASM: It should have been installed in the `/mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/sdks/out/wasm-runtime-release/lib/mono/4.5/mscorlib.dll' directory.

The issue pops up in the console in my Google Chrome browser when I run the program, and it doesn't matter if I run the project as IIS or Console.

The only thing I did to produce this error was to follow along with this guide: https://medium.com/swlh/blazor-ef-core-a-simple-web-app-part-1-3c54380cf69a

I ran into some issues I cannot seem to recall, but I updated some of my packages to fix the issues, specifically:
- Microsoft.AspNetCore.Blazor
- Microsoft.AspNetCore.Blazor.Build
- Microsoft.AspNetCore.Blazor.DevServer
- Microsoft.AspNetCore.Blazor.HttpClient
- Microsoft.AspNetCore.Blazor.Server

Which coincidentally also are the only packages installed in my project, created from the empty default template.

I have tried to reinstall the .net Core 3.1 preview multiple times, and I am at a loss on how to get Blazor WASM to work at all.

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio Professional 2019
Version 16.4.5

**Comment by javiercn** [comment]
@Tonur thanks for contacting us.

* I would recommend you try the following things:
* Turn off linking
* Remove the bin and obj folders in your solution projects
* Navigate with incognito/inprivate mode on.
* Clear nuget packages with `dotnet nuget locals --clear all` **(this will empty your nuget caches)**
* Clear the template engine cache from `~/.templateengine` by removing the folder and install the blazor-wasm template **(this will get rid of any template that didn't come with the installed SDK)**

Try and see if that gets rid of the issue you are having.

**Comment by Tonur** [comment]
Thanks! I got it to work now.
I firstly removed the bin and obj folders in my solution projects and ran the `dotnet nuget locals --clear all` command. Afterwards, it worked like a charm, I can make new projects from the template that can run and projects from other PC's now can run on my PC too.

I appreciate the help immensely!
