### ISSUE TITLE
No more option for <aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" stdoutLogEnabled="false" />

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#19556]
I have a asp.net core 2.0 application which have an option in my web.config as 

```xml
<aspNetCore processPath="bin\IISSupport\VSIISExeLauncher.exe" arguments="-argFile IISExeLauncherArgs.txt" stdoutLogEnabled="false" />
```

In this way My application which is hosted in IIS always keep running and same application I can run in debug

After asp.net core 3.1 upgrade configuration change like 

```xml
<aspNetCore processPath="D:\MyApp\bin\Debug\netcoreapp3.1\MyApp.exe" arguments="" stdoutLogEnabled="false" hostingModel="InProcess" />
```

**Comment by anurse** [comment]
What are you trying to accomplish here? VS should still be doing the same thing even with this config change. What's the problem you're encountering?

(cc @BillHiebert since this seems tooling-related)
