### ISSUE TITLE
BUG:cookies没有写入Response导致请求认证接口callback signin-oidc 丢失了oidc失败

### ISSUE THREAD

**Issue by mahaisong** [dotnet/aspnetcore#19557]
ASP.NET Core  3.1.2
class：Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler
function：GenerateCorrelationId
Issue：the last line

  Response.Cookies.Append(cookieName, CorrelationMarker, cookieOptions);

NO append in Response。

**Comment by blowdart** [comment]
But there [is](https://github.com/dotnet/aspnetcore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Http.Features/src/IResponseCookies.cs#L24).

Are you getting an error? Or is this intellisense doesn't show you Append?

**Comment by Tratcher** [comment]
Or do you mean that the expected set-cookie header is missing from the response?

**Comment by Tratcher** [comment]
Title auto translate:
> Failed to write cookies to the response and caused the request authentication interface callback signin-oidc to lose the oidc failure

**Comment by mahaisong** [comment]
yes,I see the set-cookie in browser Developer Tools （Response Headers）,but Actually the cookies not Save locally。

 Problems after successful login，“RemoteAuthenticationHandler.ValidateCorrelationId” have not  Request.Cookies.

Report as : Exception: Correlation failed.
Unknown location
Exception: An error was encountered while handling the remote login.
AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync() in RemoteAuthenticationHandler.cs, line 111

**Comment by Tratcher** [comment]
Which authentication handler are you using? RemoteAuthenticationHandler is the base implementation for many different kinds.

Please capture and share a decrypted Fiddler trace showing the whole scenario.

**Comment by mahaisong** [comment]
![image](https://user-images.githubusercontent.com/5094449/75941113-caad1680-5ec9-11ea-809a-faec59545138.png)

**Comment by mahaisong** [comment]
![image](https://user-images.githubusercontent.com/5094449/75941209-0516b380-5eca-11ea-9208-68634bc94919.png)

**Comment by Tratcher** [comment]
That's not enough information, we need to see the full network trace. A tool like Fiddler can capture that for you, but make sure to enable decryption.

**Comment by mahaisong** [comment]
ok.I am using Fiddler for the first time,Content in zip，Decrypted.
 Please pay attention “https://identity.gimind.com”  and  “https://localhost:44351/ ”.    

[request.zip](https://github.com/dotnet/aspnetcore/files/4290704/request.zip)

**Comment by mahaisong** [comment]
I spent a lot of time validating.I have verified many browsers，Including chrome, edge, ie11, QQ, 360, etc., only 360 has this problem.Maybe this problem is not a bug of the program, but a problem of 360 browser itself.I have feedback to browser developers.

Thank you for your attention.Have a good time.

**Comment by Tratcher** [comment]
Yeah, it definitely looks like a client issue. The initial auth challenge had the expected cookies, but they don't get returned to /signin-oidc later.
