### ISSUE TITLE
cannot bound SPA in site subfolder using IApplicationBuilder

### ISSUE THREAD

**Issue by giammin** [dotnet/aspnetcore#19563]
### Describe the bug
when using  Microsoft.AspNetCore.SpaServices.Extensions all requests without endpoint are rewrited to the SPA default page. there is no way to bound it to a subfolder

### To Reproduce

just run an mvc core site with an angular site under a subfolder

any 404 will go to the angular sites instead of the mvc root site

also if I try to map the app with:

```
app.Map("/admin", admin =>
            {
                app.UseSpa(spa =>
                {
                    spa.Options.SourcePath = Constants.AdminSpaRoot;
                    spa.Options.DefaultPage = "/index.html";
                    if (env.IsDevelopment())
                    {
                        spa.UseAngularCliServer(npmScript: "start-hmr-sourcemaps");
                    }
                });
            });
```

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by giammin** [comment]
sorry it was a copy paste typo: did not notice:    **admin**.UseSpa(spa =>
