### ISSUE TITLE
Reliably crash VS2019 by adding @if() before a div in blazor page

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19577]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/934919/reliably-crash-vs2019-by-adding.html)._

---
I can reproducably crash Visual Studio 2019 in a blazor page. I made a Github repo to reproduce the crash:
https://github.com/Regenhardt/crash-dummy

### Reprocuction
Basically you go to a blazor page (here: FetchData.razor),
add a div with something inside to render a property from an object (here: @forecasts. Length, line#14),
(save here, next step crashes VS),
type in front of the line (here line#14): @if()

This crashes VS. At first a bar appears at the top that says something about an InvalidOperationException and a log file, then VS freezes, and restarts after a few seconds.

I don't know where this log file is, and I can not click the button in the error bar since VS freezes completely.

### Technical data

Windows 10 1903 (just saw this, will update)
Visual Studio 16.4.5
Blazor 3.2.0-prev1.2073.1

### Extensions

Jetbrains ReSharper Ultimate 2019.3
Live Share
Xamarin.Android SDK
Xamarin.Apple SDK
Developer Analytics Tools
EditorConfig Language Service
Azure Data Lake and Stream Analytics Tools
Solution Error Visualizer
Xamarin Templates
Visual Studio IntelliCode
Microsoft Library Manager
.NET Portability Analyzer
Shrink Empty Lines
Middle Click Scroll
Microsoft Code Analysis 2019
Match Margin

---
#### Visual Studio Feedback System on 3/1/2020, 04:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
I'm unable to reproduce this issue even with the repro:

![image](https://i.imgur.com/7wSdXfD.gif)

If you update to the latest Visual Studio do you still see the issue?
