### ISSUE TITLE
[Discussion] New Azure Integration Packages in ASP.NET Core 5 #408

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#19570]
This is the discussion issue for https://github.com/aspnet/Announcements/issues/408

ASP.NET Core currently includes three packages designed to integrate our components with Azure services. Specifically, the following three packages:

* [`Microsoft.Extensions.Configuration.AzureKeyVault`](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureKeyVault/), which integrates Azure KeyVault in to the Configuration system.
* [`Microsoft.AspNetCore.DataProtection.AzureKeyVault`](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.AzureKeyVault/), which integrates Azure KeyVault into the ASP.NET Core Data Protection system.
* [`Microsoft.AspNetCore.DataProtection.AzureStorage`](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.AzureStorage/), which integrates Azure Blob Storage into the ASP.NET Core Data Protection system.

The Azure SDK team is introducing brand new packages that provide the same extensions using the latest version of the Azure SDK. These packages will be maintained by the Azure SDK team at the [Azure/azure-sdk-for-net repository](https://github.com/Azure/azure-sdk-for-net). Moving these packages over to the Azure SDK team will allow that team to update them as the SDKs themselves are updated, rather than being tied to the .NET Core schedule.

If you are using any of the packages listed above, we suggest replacing them with the new packages:

* `Microsoft.Extensions.Configuration.AzureKeyVault` **becomes** [`Azure.Extensions.AspNetCore.Configuration.Secrets`](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets)
* `Microsoft.AspNetCore.DataProtection.AzureKeyVault` **becomes** [`Azure.Extensions.AspNetCore.DataProtection.Keys`](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Keys)
* `Microsoft.AspNetCore.DataProtection.AzureStorage` **becomes** [`Azure.Extensions.AspNetCore.DataProtection.Blobs`](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs)

These new packages are **supported** on .NET Core 2.1 and 3.1 so you *do not need to wait for 5.0 to update*!

These are new packages that bring in a new version of the Azure SDK which includes breaking changes. The general usage patterns are the same as the existing packages, but some overloads and options may be different (in order to react to the changes to the underlying Azure SDK APIs).

The existing `Microsoft.` packages listed above will continue to be *fully supported* by the ASP.NET Core team for the lifetime of .NET Core 2.1 and 3.1. However, they **will not** be shipping in .NET 5. When upgrading your application to .NET 5, you will need to transition to the `Azure.` packages in order to be supported.

**Comment by juunas11** [comment]
Just wanna comment that I made a quick Core 3.1 app that uses the 2 data protection packages and it was really easy to plug them in :)
Here's a link to that: https://github.com/juunas11/Joonasw.AzureDataProtection/blob/0880cb95d08c220ce7fb8d754192da7f0ebe24bf/Joonasw.AzureDataProtection/Startup.cs#L43

Plugged DefaultAzureCredential to both and everything works really nicely locally.
I'll probably write up a blog post on using these 👍

**Comment by TechWatching** [comment]
What will happened to Microsoft.AspNetCore.AzureKeyVault.HostingStartup that is automatically added to a csproj when using "Connected Services" in Visual Studio 2019 ?

**Comment by anurse** [comment]
@TechWatching yep, we're working with that team to get a plan in place. For now it continues to use the legacy packages (which are still fully supported in .NET Core 2.1 and 3.1).

**Comment by tebeco** [comment]
Hello ;)

Is that normal ?
![image](https://user-images.githubusercontent.com/2266487/87484391-4c5e3f00-c636-11ea-8ec6-0a9f2372d8c0.png)

**Comment by anurse** [comment]
Looks like it got renamed/changed since the original release. If you expand that notice, it has the details.

![image](https://user-images.githubusercontent.com/7574/87498164-fe344600-c60b-11ea-8e6b-477bb24fc69e.png)

**Comment by tebeco** [comment]
@anurse 
oO thanks a lot, I did not spotted that is was expandable, many thanks

Do you think it's possible to edit the links here for further lookup ?
https://github.com/dotnet/aspnetcore/issues/19570#issue-575582628

![image](https://user-images.githubusercontent.com/2266487/87529245-008bb400-c68f-11ea-883e-1cfb2003e45d.png)

**Comment by anurse** [comment]
Should be, yeah. I still have permission since I posted the issue but perhaps @Pilchie should have someone on the team double check things since I'm no longer on the ASP.NET team.

**Comment by Pilchie** [comment]
I'm following up.

**Comment by Pilchie** [comment]
Updated the announcement issue, and the first comment on this issue with the packages, and removed the text about them being preview versions.

**Comment by tebeco** [comment]
thx a lot

**Comment by heaths** [comment]
So all references will be updated to the new packages? Was Microsoft.AspNetCore.All removed then? It accounts for 15.2% of our daily downloads of Microsoft.Azure.KeyVault, which we'd like to get on Azure.Security.KeyVault.Secrets instead. I can only find commits that remove references to it, unless I missed actual code clean up to remove the package for .NET 5.

/cc @AlexGhiondea @pakrym

**Comment by Pilchie** [comment]
Microsoft.AspNetCore.All hasn't existed since .NET Core 2.2.

We cannot update packages for < 5.0, because it would be a breaking change. That's the whole reason we made the new packages in the first place.
