### ISSUE TITLE
Integrate Microsoft Graph with ASP.Net Identity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19576]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/936757/integrate-microsoft-graph-with-aspnet-identity.html)._

---
<p>We are integrating an MVC .NET web application using asp.net identity with Microsoft Graph, however, we don't find an example where both asp.net identity and OAuth work together. We are experiencing an issue where Microsoft Authentication takes over when the session is lost of times out. Can you please point us to a resource/example to accomplish this?</p><p>This is our Startup.Auth.cs code:</p><pre> public partial class Startup
    {
        private static string appId = ConfigurationManager.AppSettings[&quot;ida:AppId&quot;];
        private static string appSecret = ConfigurationManager.AppSettings[&quot;ida:AppSecret&quot;];
        private static string redirectUri = ConfigurationManager.AppSettings[&quot;ida:RedirectUri&quot;];
        private static string graphScopes = ConfigurationManager.AppSettings[&quot;ida:AppScopes&quot;];

        public static OAuthAuthorizationServerOptions OAuthOptions { get; private set; }

        public static string PublicClientId { get; private set; }

        public void ConfigureAuth(IAppBuilder app)
        {
            app.MapSignalR();

            // Configure the db context, user manager and role manager to use a single instance per request
            app.CreatePerOwinContext(HomeImproverContext.Create);
            app.CreatePerOwinContext&lt;ApplicationUserManager&gt;(ApplicationUserManager.Create);
            app.CreatePerOwinContext&lt;ApplicationRoleManager&gt;(ApplicationRoleManager.Create);
            app.CreatePerOwinContext&lt;ApplicationSignInManager&gt;(ApplicationSignInManager.Create);

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString(&quot;/Account/Login&quot;),
                Provider = new CookieAuthenticationProvider
                {
 
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity&lt;ApplicationUserManager, ApplicationUser&gt;(
                        validateInterval: TimeSpan.FromSeconds(10),
                        regenerateIdentity: (manager, user) =&gt; user.GenerateUserIdentityAsync(manager)),

                    OnException = context =&gt; { }
                }
            });
            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
            app.UseTwoFactorSignInCookie(DefaultAuthenticationTypes.TwoFactorCookie, TimeSpan.FromMinutes(5));

            app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);

            PublicClientId = &quot;self&quot;;
            OAuthOptions = new OAuthAuthorizationServerOptions()
            {
                TokenEndpointPath = new PathString(&quot;/Token&quot;),
                Provider = new ApplicationOAuthProvider(PublicClientId),
                AuthorizeEndpointPath = new PathString(&quot;/api/Account/ExternalLogin&quot;),
                AccessTokenExpireTimeSpan = TimeSpan.FromDays(14),
                AllowInsecureHttp = bool.Parse(ConfigurationManager.AppSettings[&quot;AllowInsecureHttp&quot;])
            };

            app.UseOAuthBearerTokens(OAuthOptions);

            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    ClientId = appId,
                    Authority = &quot;https://login.microsoftonline.com/common/v2.0&quot;,
                    Scope = $&quot;openid email profile offline_access {graphScopes}&quot;,
                    RedirectUri = redirectUri,
                    PostLogoutRedirectUri = redirectUri,
                    TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                    {
                        ValidateIssuer = false
                    },
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthenticationFailed = OnAuthenticationFailedAsync,
                        AuthorizationCodeReceived = OnAuthorizationCodeReceivedAsync
                    }
                }
            );

            app.UseAuthorization(options =&gt;
            {
                AddPolicies(options);
                options.Dependencies = AuthorizationDependencies.Create(options, new PermissionHandler());
            });

            
        }

        private void AddPolicies(AuthorizationOptions options)
        {
            try
            {
                var context = new HomeImproverContext();
                var policyPermissions = context.PolicyPermissions;
                foreach (var policy in policyPermissions)
                {
                    options.AddPolicy(policy.Name, p =&gt; p.Requirements.Add(new PermissionRequirement(policy.Permission.Name, (PermissionLevels)policy.PolicyLevel)));
                }
            }
            catch
            {

            }
        }

        private static Task OnAuthenticationFailedAsync(AuthenticationFailedNotification&lt;OpenIdConnectMessage,
  OpenIdConnectAuthenticationOptions&gt; notification)
        {
            notification.HandleResponse();
            string redirect = $&quot;/Home/Error?message={notification.Exception.Message}&quot;;
            if (notification.ProtocolMessage != null &amp;&amp; !string.IsNullOrEmpty(notification.ProtocolMessage.ErrorDescription))
            {
                redirect += $&quot;&amp;debug={notification.ProtocolMessage.ErrorDescription}&quot;;
            }
            notification.Response.Redirect(redirect);
            return Task.FromResult(0);
        }

        private async Task OnAuthorizationCodeReceivedAsync(AuthorizationCodeReceivedNotification notification)
        {
            var idClient = ConfidentialClientApplicationBuilder.Create(appId)
                .WithRedirectUri(redirectUri)
                .WithClientSecret(appSecret)
                .Build();

            var tokenStore = new SessionTokenStore(idClient.UserTokenCache, HttpContext.Current);

            try
            {
                string[] scopes = graphScopes.Split(' ');

                var result = await idClient.AcquireTokenByAuthorizationCode(
                    scopes, notification.Code).ExecuteAsync();

                var userDetails = await GraphHelper.GetUserDetailsAsync(result.AccessToken);

                var cachedUser = new CachedUser()
                {
                    DisplayName = userDetails.DisplayName,
                    Email = string.IsNullOrEmpty(userDetails.Mail) ?
                    userDetails.UserPrincipalName : userDetails.Mail,
                    Avatar = string.Empty
                };

                tokenStore.SaveUserDetails(cachedUser);
            }
            catch (MsalException ex)
            {
                string message = &quot;AcquireTokenByAuthorizationCodeAsync threw an exception&quot;;
                notification.HandleResponse();
                notification.Response.Redirect($&quot;/Home/Error?message={message}&amp;debug={ex.Message}&quot;);
            }
            catch (Microsoft.Graph.ServiceException ex)
            {
                string message = &quot;GetUserDetailsAsync threw an exception&quot;;
                notification.HandleResponse();
                notification.Response.Redirect($&quot;/Home/Error?message={message}&amp;debug={ex.Message}&quot;);
            }
        }
    }

</pre>

---
#### Visual Studio Feedback System on 3/3/2020, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
This would be a question for Microsoft Graph rather than us. 

https://github.com/microsoftgraph would be the place to ask.
