### ISSUE TITLE
UseWhen() not rejoining main branch when containing terminal middleware (v3.1)

### ISSUE THREAD

**Issue by abrguyt** [dotnet/aspnetcore#19586]
The docs clearly state that IAppplicationBuilder.UseWhen() should always rejoin the main branch even in case of short-circuiting or when the delegate contains terminal middleware. However this does not seem to be the case.

This code does not rejoin the main branch:
``` C#
app.UseWhen(true,
	_app => _app.Run(context) => {
		// some work
		return Task.CompletedTask;
	})
);
// this part of the main branch pipeline will never be reached (=incorrect)
```

While this code does it correctly:

``` C#
app.UseWhen(true,
	_app => _app.Use(async (context, next) => {
		// some work
		await next.Invoke();
	})
)
// this part of the main branch pipeline will be reached
```

The current implementation is not in line with the documentation for UseWhen (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1)

**Comment by anurse** [comment]
> The docs clearly state that IAppplicationBuilder.UseWhen() should always rejoin the main branch even in case of short-circuiting or when the delegate contains terminal middleware.

I actually think this is a typo in the docs.

The docs say this:

> UseWhen also branches the request pipeline based on the result of the given predicate. Unlike with MapWhen, this branch is rejoined to the main pipeline _if it does short-circuit or contain a terminal middleware_:

But should say:

> UseWhen also branches the request pipeline based on the result of the given predicate. Unlike with MapWhen, this branch is rejoined to the main pipeline _if it does **not** short-circuit or contain a terminal middleware_:

The [tests appear to support the fact that this is a typo](https://github.com/dotnet/aspnetcore/blob/bda22253e9800e6aea8c6a83096c09075e8cfea8/src/Http/Http.Abstractions/test/UseWhenExtensionsTests.cs#L58). Specifically:

```csharp
        [Fact]
        public async Task PredicateTrue_BranchTaken_CanTerminate()
        {
            // Arrange
            var context = CreateContext();
            var parent = CreateBuilder();

            parent.UseWhen(TruePredicate, child =>
            {
                child.UseWhen(TruePredicate, grandchild =>
                {
                    grandchild.Use(Increment("grandchild", terminate: true));
                });

                child.Use(Increment("child"));
            });

            parent.Use(Increment("parent"));

            // Act
            await parent.Build().Invoke(context);

            // Assert
            Assert.Equal(0, Count(context, "parent"));
            Assert.Equal(0, Count(context, "child"));
            Assert.Equal(1, Count(context, "grandchild"));
        }
```

The "child" and "parent" code paths are not hit.

I'll open a PR to update the docs to clarify this behavior to avoid future confusion. Thanks for catching this!
