### ISSUE TITLE
CORS WithCredentials Worked .NET Core 2.x now broken 3.1.2

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/aspnetcore#19581]
In the past Startup.cs of 

services.AddCors(options => options.AddDefaultPolicy(policy => policySetIsOriginAllowed(origin => return true).WithCredentials()));
services.AddMvc()

then 
app.UseCores();
app.UseMvcwhatever();

Would work fine.

Now this fails. (no matter what order I put it in)

And from what I can tell there is no case where WithCredentials will actually work with an xhr (Angular 9). I've tried every combination I can possibly think of with no luck.  Either this is a bug or the documentation needs to be FAR more clear on how to make this work (and the docs for 3.1 have references to 2_2 comparability in the samples inline still!)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will look through our docs and see what's missing from there to get this covered.

**Comment by JohnGalt1717** [comment]
This isn't just docs. This is regression from .NET Core 2.2 Right now it's impossible to use WithCredentials which is blocking upgrade from .NET Core 2.2.  This is high priority urgent issue because it simply doesn't work in 3.1 and needs to be fixed long before November release of 5.0.

**Comment by Javaman2** [comment]
Maybe this is why no matter what I try with ASP.NET core 3.1 I cannot get Azure AD to work (been trying for weeks now)

**Comment by JohnGalt1717** [comment]
We're having no problems with Azure AD, it's just a matter that you have to have a redirect of the entire browser....

**Comment by Javaman2** [comment]
We can get backend to Authenticate no problem. But not front end using backend to do it.

**Comment by JohnGalt1717** [comment]
Here's the only way that I've gotten CORS to Accept Credentials with V3.1:

```
service.AddCors(options => {
   options.AddPolicy("ControllerPolicy", police => {
					policy.AllowAnyHeader();
					policy.AllowAnyMethod();
					policy.AllowCredentials();
					policy.SetIsOriginAllowed(origin =>
					{
						if (string.IsNullOrWhiteSpace(origin))
							return false;

						if (origin.ToLower().StartsWith("https://localhost"))
							return true;
                                                //Add others here that you need
                                                return false;
   });
});
```

Then on your controllers add:
[EnableCors("ControllerPolicy")]

At the top.

And no setting as the default policy doesn't work, especially with SignalR. You have to have the annotation in my experience.

Anything else just doesn't work and the old ways in .NET Core 2.2 don't at all.

**Comment by Javaman2** [comment]
Thanks John, I'll give it a try.

**Comment by pranavkm** [comment]
We'll be looking at improving the documentation around this as part of https://github.com/dotnet/aspnetcore/issues/21541. As a note, using CORS that allows any origin and allows credentials has a XSRF vulnerability : https://github.com/dotnet/aspnetcore/issues/3106.

**Comment by JohnGalt1717** [comment]
Given that I can just change my hosts file and emulate any host I fail to see how this is any more of a vulnerability than specific naming.  

In fact that's true of all CORS. Total false sense of security given that I can outright bypass it by simply editing my hosts file.
