### ISSUE TITLE
Razor pages grouping

### ISSUE THREAD

**Issue by hhvdblom** [dotnet/aspnetcore#19594]
https://stackoverflow.com/questions/46777404/why-is-razor-pages-the-recommended-approach-to-create-a-web-ui-in-asp-net-core-2/57798703#57798703

**Comment by javiercn** [comment]
Thanks for contacting us @hhvdblom.

Your question is not clear to us. Can you provide more details about your specific issue/question so that we can try and help you?

**Comment by hhvdblom** [comment]
Hi @javiercn, to be clear, Its all about Razor pages. In Razor pages you have a code-behind for every page. If you have lets say 4 pages that are Home page related you will have 4 code-behind pages. They are not grouped to a Home page. If you look at MVC you have a HomeController with all home pages related views in it. Thats an example of a Facade pattern. With Razor pages you could group them in a Directory but that does not feel right.

**Comment by javiercn** [comment]
@hhvdblom It is in gran part a matter of preference, Razor pages are better suited for simple pages where the UI has a higher weight compared to the application logic. Structuring pages into folders is exactly what you are supposed to do.

A good example of this is the Identity UI, which is implemented as a set of razor pages. There is an advantage to use Razor pages when building UI centric applications as they simplify some aspects like antiforgery validation etc. I recommend you look [here](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio#xsrfcsrf-and-razor-pages) to get a better idea.

With regard to what to use when and how to organize your project, we don't offer prescriptive guidance as it is a matter of style in most cases. You can check what we do in the Identity UI project and ultimately decide what do you prefer and go with that.
