### ISSUE TITLE
Look for cheap ways to make the build faster

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19599]
Currently, Blazor WebAssembly build times are OK (when the linker is disabled) but there may be opportunities to make it faster.

In particular, we're calculating the SHA-256 hash of all `_framework` output files on every build - *twice* - because this info is needed both for boot manifest generation and for compression incrementalism. We need to compute the hashes of new inputs to know whether the outputs should change (it's not enough to use file timestamps to determine this, because if you (say) downgrade to an older package dependency, we still need to regenerate the output). Even if we can't eliminate this, we should be able to reduce to to happen just once and reuse the result as metadata.

If we investigate the build logs, there might be other cheap opportunities to skip expensive parts too. We just haven't investigated this recently.

**Comment by javiercn** [comment]
Some food for thought:
* We can do a single hash of the things that are included in computing the hashes that we need, and then just hash things when that changes.
* For example, we hash the project references, package references, etc and then key the hashing task/target based on whether the file emitted as a result of that has changed.
  * That way we only re-hash things when some of the build dependencies change
  * I believe hashing all the input paths together would achieve this

* We can do the hash of all the files in one place and add that as metadata that can be used later.

**Comment by mkArtakMSFT** [comment]
Closing as a lot of work has been done in this area and there is nothing urgent here.
