### ISSUE TITLE
[Blazor Server] Binding to input type=time doesn't work properly in Edge

### ISSUE THREAD

**Issue by jaryn-kubik** [dotnet/aspnetcore#19598]
### Describe the bug
Binding input with type="time" doesn't work properly in Edge, see repro below.
When I write the time inside the input using keyboard, the Time field gets properly updated. Increasing/decreasing the values using up/down arrow keys also works fine.
When I use the UI editor in Edge that opens up the dropdowns with hours/minutes so i can select the time using my mouse, nothing happens when i confirm the dialog.

When I tried changing the Time field to property with getter/setter, the setter never gets called.

### To Reproduce
https://blazorfiddle.com/s/i8c0z2ht
(not sure what version of .net core this uses, but it works the same way on latest 3.1.2)

### Further technical details
- ASP.NET Core 3.1.2
- Microsoft Edge Version 80.0.361.66 (Official build) (64-bit)

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.
