### ISSUE TITLE
Validate inputs when submitting

### ISSUE THREAD

**Issue by antoniogarcez-famo** [dotnet/aspnetcore#19602]
Hi people,

I am with a problem in my SignIn page. 
In my page, I have a form with two inputs and I want to validate if both are filled before submitting but if I put a handler in my form, it prevents my submission.

My HTML code:
``` html
<form action="Authentication/SignIn" method="post" @onsubmit="HandleSubmit">
    <Input @ref="_usernameInput" Type="text" Name="username" @bind-Value="_username" Placeholder="@Resource.key_397" Autocomplete=false Autofocus=true Error="@Resource.key_196" HandleFocus="HandleUsernameFocus" />
    <Input @ref="_passwordInput" Type="password" Name="username" @bind-Value="_password" Placeholder="@Resource.key_314" Autocomplete=false Autofocus=false Error="@Resource.key_195" HandleFocus="HandlePasswordFocus" />
    <KeyPad Class="signin-keypad" HandleButton="HandleButton" />
    <button type="submit" class="hide" />
</form>
```

My handler:
``` c#
private void HandleSubmit()
{
    int a = 0;
}
```

I am using .NET Core 3.1 | Visual Studio 2019 Version 16.4 | 3.1.1

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by mkArtakMSFT** [comment]
Also, this may help: https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1
