### ISSUE TITLE
Razor component disconnects Blazor when passing a class instance

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#19605]
When visiting `Index.cshtml`, the browser console displays the below errors.

Index.cshtml
```
@{
	var myObject = new MyClass(1, "test");
}

<component type="typeof(MyComponent)" render-mode="ServerPrerendered" param-MyObject="@myObject" />
```

MyClass.cs
```
public class MyClass
{
	public int MyInt { get; set; }
	public string MyString { get; set; }

	public MyClass(int myInt, string myString)
	{
		MyInt = myInt;
		MyString = myString;
	}
}
```

MyComponent.razor
```
<p>
	@MyObject.MyInt
	@MyObject.MyString
</p>

@code {
	[Parameter]
	public MyClass MyObject { get; set; }
}

```

Browser console
> Error: The list of component records is not valid.
Information: Connection disconnected.
Unhandled Promise Rejection: Error: Invocation canceled due to the underlying connection being closed.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by guardrex** [comment]
Related doc issue :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/17210

... but I don't repro any such error here.

**Comment by pranavkm** [comment]
@mrlife parameters passed to the component need to be serializable by System.Text.Json. System.Text.Json does not support immutable types - https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#deserialize-to-immutable-classes-and-structs. You'll need to have a public parameterless constructor for this to work correctly.

@javiercn the exception should be thrown here: https://github.com/dotnet/aspnetcore/blob/master/src/Components/Server/src/Circuits/ComponentParameterDeserializer.cs#L68, but the exception is logged as `Debug`. Should this be surfaced more readily to the user?

**Comment by mrlife** [comment]
@pranavkm Thanks for letting me know. I just tried it out, and it seems to work. Is this right?

Code
```
var myObject = new MyClass(1, "test");
var serialized = System.Text.Json.JsonSerializer.Serialize(myObject);
```

Results

> "{\"MyInt\":1,\"MyString\":\"test\"}"

**Comment by pranavkm** [comment]
It's the deserialization routine that needs a parameterless constructor.

**Comment by guardrex** [comment]
We'll need better docs for this scenario. A couple of follow-up ❓ ...

Is passing params only supposed to work for `ServerPrerendered` mode, or should it work for `Server` mode, too? I've had no ❤️ from my test app getting `Server` mode to work in this scenario.

> You'll need to have a public parameterless constructor for this to work correctly.

... but if that's so then why does the following work? ...

```csharp
public class MyClass
{
    public MyClass(int myInt, string myString)
    {
        MyInt = myInt;
        MyString = myString;
    }

    public int MyInt { get; set; } = 999;
    public string MyString { get; set; } = "Initial value";
}
```

```razor
<h2>MyComponent</h2>

<p>MyInt: @MyObject.MyInt</p>
<p>MyString: @MyObject.MyString</p>

@code
{
    [Parameter]
    public MyClass MyObject { get; set; }
}
```

```cshtml
@page "/MyPage"
@model BlazorServer31.MyPageModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BlazorServer31
@using BlazorServer31.Shared
@{ Layout = null; }

<!DOCTYPE html><html><head><title>MyPage</title></head>
<body>
    @{
        var myObject = new MyClass(5, "Set in MyPage");
    }

    <component type="typeof(MyComponent)" render-mode="ServerPrerendered" 
        param-MyObject="@myObject" />
</body></html>
```

Output ...

<img width="197" alt="Capture" src="https://user-images.githubusercontent.com/1622880/76002357-1d87cd80-5ecc-11ea-9e81-10b9023ce27b.PNG">

... with no errors in the console.

**Comment by mrlife** [comment]
> It's the deserialization routine that needs a parameterless constructor.

This is true, thank you. It works when serializing but does throw a runtime error when deserializing.

> NotSupportedException: Deserialization of reference types without parameterless constructor is not supported.
