### ISSUE TITLE
Sudden red squiggles showing up in EditForm 

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#19613]
This squiggles just started to show up. However everything works.

### OnValidSubmit
![image](https://user-images.githubusercontent.com/12285372/76022428-24770600-5ef5-11ea-83dc-2af2fef7035f.png)

### bind-Value
![image](https://user-images.githubusercontent.com/12285372/76022591-7586fa00-5ef5-11ea-9296-374d77b0eeb7.png)

**Comment by javiercn** [comment]
@yopez83 thanks for contacting us.

Can you provide more details about the Visual Studio Version you are using as well as the dotnet SDK so that we can try and help you?

**Comment by yopez83** [comment]
Visual Studio Community 2019 Version 16.4.5, and .NET Core SDK 3.1.102 (x64)

**Comment by javiercn** [comment]
@NTaylorMullen @ajaybhargavb thoughts?

**Comment by ajaybhargavb** [comment]
@yopez83, I used the same VS and dotnet version but I'm unable to reproduce on my side. Can you provide a minimal repro app for us to be able to investigate this further?

![image](https://user-images.githubusercontent.com/1579269/76105371-b3356280-5f89-11ea-81a8-664ec676f861.png)

**Comment by yopez83** [comment]
@ajaybhargavb as you see there is not too much code in it. I have tried the same code in Visual Studio Professional and no squiggles at all. Reinstall VS maybe?

**Comment by ajaybhargavb** [comment]
> @ajaybhargavb as you see there is not too much code in it. I have tried the same code in Visual Studio Professional and no squiggles at all. Reinstall VS maybe?

Interesting. I'm not aware of any differences expected between Community and Professional. Check if repairing VS fixes it.

**Comment by yopez83** [comment]
@ajaybhargavb after repairing everything was back to normal. Then I realize I was missing the Resharper extension. After reinstalling Resharper the squiggles showed up again. Then it's Resharper the one causing the problem.

**Comment by ajaybhargavb** [comment]
Ah yeah that makes sense. Glad you figured it out.
