### ISSUE TITLE
IAuthenticationFilter

### ISSUE THREAD

**Issue by renanrcp** [dotnet/aspnetcore#19611]
I wanna suggest a new ASP.NET Core filter, it will be "IAuthenticationFailedFilter" or "IAsyncAuthenticationFailedFilter" (or both lmao), with that you can intercept the Authentication Schemes results. 

I'm trying to use the IAsyncAuthorizationFilter to change the body response when the ASP.NET Core returns 401 Unauthorized (but with empty response), but unfortunately, it doesn't work with Authentication, just with Authorization.

But pay attention, just wait for AuthenticationScheme fails won't work, because after this ASP.NET Core will see if the Action has the "AuthorizeAttribute" or the "AllowAnonymousAttribute" and with that allow the request or no.

**Comment by pedro-lb** [comment]
Looks good, would be amazing to have this! 

Can we document this better to see how it would work? Maybe providing a code snippet on how to use it or a documentation exposing the properties of this feature.

**Comment by pedro-lb** [comment]
Quick note: would be good to have both filters to be having async and sync support.

**Comment by renanrcp** [comment]
Right I'll do these things

**Comment by renanrcp** [comment]
I do different as I thought when I open this issue.

I made this gist with an example of an async AuthenticationFilter with the context classes too:

https://gist.github.com/renanrcp/ef09480dff0209e0bd376dee2120ff00

I'll change this topic name to IAuthenticationFilter.

**Comment by Tratcher** [comment]
There's a conceptual mismatch here. We don't consider it Authentication's job to produce responses. Authentication's only job is to identify the user associated with a request. If it can't do that then it's up to the caller (usually Authorization) to decide what kind of response is appropriate.

For reference, what kind of authentication are you using in this scenario? 401s are primarily used for programmatic authentication (APIs) where the response body is largely irrelevant. Federated auth (OIDC, OAuth, etc.) would use 301s and again you wouldn't see the response body. Maybe Windows/Kerberos auth?

**Comment by renanrcp** [comment]
I'm using my own Authentication Scheme, and in my Web API I wanna standardize ever response, but when it fail it's just return 401 with an empty body

**Comment by anurse** [comment]
@renanrcp but again, it still seems like a job for an Authorization filter rather than Authentication. AuthN is just the process of identifying the current user, AuthZ is manipulating the response based on that user.

**Comment by renanrcp** [comment]
Hmm, and if I wanna to change the response body I need to make an authorization policy?
