### ISSUE TITLE
Razor Class Libraries are not building properly under 3.1

### ISSUE THREAD

**Issue by rasmus91** [dotnet/aspnetcore#19615]
### Describe the bug
I have created a razor class library, when i add any .cshtml file, however, the project will not build. Sometimes i can get it to, by removing the target razor language version, but not necessarily.

### To Reproduce

Well, It's quite simple:

1. `dotnet new razorclasslib -o RazorLibNotWorking`
2. `cd RazorLibNotWorking`
3. `dotnet build` (notice it already says its missing the namespace razor)
4. `dotnet add package Microsoft.AspNetCore.Mvc --version 2.2.0` (to try and fix the above)
5. `dotnet build` (try and fail to compile again)

Specifically I am getting this error:

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 49,51 ms for /home/user/Projekter/NET/RazorLibNotWorking/RazorLibNotWorking.csproj.
  It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '2.0.9' was not found.
    - The following frameworks were found:
        3.1.2 at [/snap/dotnet-sdk/63/shared/Microsoft.NETCore.App]
  
  You can resolve the problem by installing the specified framework and/or SDK.
  
  The specified framework can be found at:
    - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.9&arch=x64&rid=elementary.5.1.2-x64
/snap/dotnet-sdk/current/sdk/3.1.102/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code 150. [/home/user/Projekter/NET/RazorLibNotWorking/RazorLibNotWorking.csproj]

Build FAILED.

/snap/dotnet-sdk/current/sdk/3.1.102/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code 150. [/home/user/Projekter/NET/RazorLibNotWorking/RazorLibNotWorking.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:21.38

```

I have a non-working code repo [here](https://github.com/rasmus91/RazorLibNotWorking)

clone that and run the build command, and it should (not) work.

I have found at times that removing the Microsoft.AspNetCore.Mvc reference, running `dotnet clean` followed by readding it and running build will allow me to build some arbitrary number of times before it fails again. At other times, commenting out the target razor version helps.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
```.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     elementary
 OS Version:  5.1.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/63/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/snap/dotnet-sdk/63/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/snap/dotnet-sdk/63/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/snap/dotnet-sdk/63/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download```
- VS Code 1.42.1

**Comment by javiercn** [comment]
@rasmus91 thanks for contacting us.

If you are trying to create a project for an earlier version, you will need to pass in the `--framework` parameter, for example `dotnet new razorclasslib --framework netcoreapp2.1 -o rcl21`

**Comment by rasmus91** [comment]
I am trying to create a library containing some standard Razor pages that i want to use across several projects. I have no intention or desire to develop for anything older than 3.1

What seems to be the indicator that my intention was otherwise?

**Comment by javiercn** [comment]
@rasmus91 I misunderstood what you were trying to achieve.

You need to pass the `-s` parameter to it. as in `dotnet new razorclasslib --support-pages-and-views`

**Comment by javiercn** [comment]
> Restore completed in 49,51 ms for /home/user/Projekter/NET/RazorLibNotWorking/RazorLibNotWorking.csproj.
>   It was not possible to find any compatible framework version
>   The framework 'Microsoft.NETCore.App', version '2.0.9' was not found.
>     - The following frameworks were found:

This is what tripped me

**Comment by javiercn** [comment]
You don't need the reference to MVC, that will only cause you issues.

**Comment by rasmus91** [comment]
Thank you very much. I have read and reread the docs, without noticing. 

Pardon my waste of your time.
