### ISSUE TITLE
mvc dropdownlistfor why not support set name attributes

### ISSUE THREAD

**Issue by apchenjun** [dotnet/aspnetcore#19631]
asp.net core mvc why not support set name attributes for dropdownlistfor controls

It should be for me that the edit page can only use dropdownlistfor to bind the drop-down box to select items, so I need to solve the name property Customer.CustomerBiaoshi override and Model corresponds to CustomerBiaoshi
`@Html.DropDownListFor(x => x.Customer.CustomerBiaoshi, Html.GetEnumSelectList<TgNetJZ.CustomerBiaoshi>(), "test",new { @class = "form-control custom-select" ,@name="myName"})`
![image](https://user-images.githubusercontent.com/4964551/76579439-306f5300-6507-11ea-83e6-d675d1c6910c.png)
I want to set the name property to myname instead of Customer.CustomerBiaoshi

**Comment by javiercn** [comment]
@apchenjun thanks for contacting us.

We'll look into your suggestion and update this issue accordingly.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
