### ISSUE TITLE
Bug in base32 implementation that makes it irreversible

### ISSUE THREAD

**Issue by slavanap** [dotnet/aspnetcore#19639]
### Describe the bug
[Implementation](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/Base32.cs) of base32 encoding has an issue.

Encoding+decoding message with base32 is irreversible, i.e. `FromBase32(ToBase32(x)) != x`

### To Reproduce

    var sampleText = "AB12C345";
		
    // Encode to Base32
    var base32Text = Microsoft.AspNetCore.Identity.Base32.ToBase32(Encoding.UTF8.GetBytes(sampleText));
		
    // Decode back
    var decodedBase32Text = Encoding.UTF8.GetString(Microsoft.AspNetCore.Identity.Base32.FromBase32(base32Text));
		
    // Expect string equality
    if (decodedBase32Text != sampleText)
        Console.WriteLine("ERROR");

You may launch it here: https://dotnetfiddle.net/CKASmX

### Further technical details
- ASP.NET Core version 2.1 - 3.1.2 (including master)

### Proposed solution
Pull request https://github.com/dotnet/aspnetcore/pull/19621

**Comment by blowdart** [comment]
@HaoK Can you look please? We don't decode so it doesn't actually matter, and it's private, so I'm not too concerned here.

**Comment by slavanap** [comment]
@blowdart that's why I haven't submitted it as a security issue, because you use it only to encode random array of 20 bytes, and when size of array is 20, the issue does not show itself at all.

As an offtopic, I wonder why .NET does not supply default implementation of base32 encoder/decoder, as it does with base64.

**Comment by blowdart** [comment]
Because it's not used anywhere public that we support. We generally don't add speculative APIs :)

**Comment by HaoK** [comment]
Thanks again @slavanap
