### ISSUE TITLE
Blazor Server - Circuit Loss - Connection Disconnected

### ISSUE THREAD

**Issue by VideoAppsNet** [dotnet/aspnetcore#19637]
Im having an issue where if a client loads the blazor website and then multi tasks away from the browser or locks there phone. After 3:30 minutes if they open up that same browser and go back to the site the circuit does not reconnect. If you open the browser sooner then 3:30 then it reconnects and is usable again with the ui being fully responsive. But if after 3:30 it shows error and would have an unhandled exception. This is for iPhone and Android. If user keeps the website open on there phone the connection is never lost. THis issue only happens when phone is locked or browser is put into hibernation. I ran the chrome java script logging on my iPhone and this is what I get:
Normalizing Blazor to www.site.com
Websocket connected...
---- Here is where I lock the phone and wait 3:30
-- Now I come back to the phone and open the browser
Error Circuit is not initialized....
Connection Disconnected...

If you can help to solve this issue or maybe this issue is solved I just need to know what code to include. Your help is greatly appreciated. Thank you.

**Comment by javiercn** [comment]
@VideoAppsNet Thanks for contacting us.

The behavior you are seeing is by design. If the user/browser stops sending pings from the browser the circuit automatically disconnects to ensure that the resources are not allocated forever. This is explained [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1#blazor-circuits) and can be configured in the CircuitOptions.

When the user hibernates the browser, the server only knows that the client stopped responding and marks the circuit as disconnected and after a certain period of time, it de-allocates it.

Hope that helps.

**Comment by VideoAppsNet** [comment]
Thank you for that. This is what I have so far. I was wondering how would I enable the circuit to reconnect after user has stopped using there browser for a long period of time? I thought it should do this automatically but I get errors such as == Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (). After this error my page does not render anymore and requires a refresh. 

        private class TrackingCircuitHandler : CircuitHandler
        {
            private HashSet<Circuit> _circuits = new HashSet<Circuit>();

            public override Task OnConnectionUpAsync(Circuit circuit, CancellationToken cancellationToken)
            {
                _circuits.Add(circuit);
                return Task.CompletedTask;
            }

            public override Task OnConnectionDownAsync(Circuit circuit, CancellationToken cancellationToken)
            {
                _circuits.Remove(circuit);
                return Task.CompletedTask;
            }

            public override Task OnCircuitClosedAsync(Circuit circuit, CancellationToken cancellationToken)
            {
                return base.OnCircuitClosedAsync(circuit, cancellationToken);
            }

            public int ConnectedCircuits => _circuits.Count;
        }

**Comment by VideoAppsNet** [comment]
One more question. Is Websockets required to achieve what im trying to do? Im using Windows Server 2019 for my hosting.

**Comment by VideoAppsNet** [comment]
Here is a screenshot from my iPhone with console errors. 
https://imgur.com/0NhqfsN

**Comment by javiercn** [comment]
I would check this https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1
