### ISSUE TITLE
Json serialization very slow with large files when using AddNewtonsoftJson

### ISSUE THREAD

**Issue by cmorgan091** [dotnet/aspnetcore#19646]
### Describe the bug
When creating large api outputs (multiple megabytes) and using Newtonsoft (via AddNewtonsoftJson) the default returning of an object (thus having it serialized by aspnetcore) is extremely slow, i.e. takes 4 times as long as serializing it manually in code using Newtonsoft Json.Net and returning as Content

### To Reproduce
I have created a test project in Github to reproduce this: https://github.com/cmorgan091/aspnetcorejsonserialization

This creates a simplistic api which has 3 actions, which all create 10,000 objects and try to return them in different ways:

- Normal - Uses the inbuilt json serialization, in this case Newtonsoft
- Manual - Calls JsonConvert.Serialize on the object and returns using Content
- ManualWriter - Creates a StringWriter and uses JsonWriter, which is more akin to what aspnetcore does internally from a brief look

I test performance by using Powershell for example:

`(Measure-Command -Expression { Invoke-WebRequest -Uri "https://localhost:44316/test/normal" | Out-Null }).TotalSeconds`

All results based on a warm start (discarding first result and taking average of 3 further runs):

- Normal = 4.630s
- Manual = 1.169s
- Manual Writer = 1.180s

I have also run this without the AddNewtonsoftJson and the performance for Normal returns to around 1.1s, however for the project I am working on, moving away from Newtonsoft will cause knock on effects and it is my understanding that Newtonsoft Json.Net is treated as a first class citizen in aspnetcore.

As such it seems there is something that is significantly slowing it down in the way this has been implemented.

### Further technical details
- ASP.NET Core version 3.1.1
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 Professional

**Comment by pranavkm** [comment]
The Newtonsoft.Json based output-formatter buffers content. The buffering is done to avoid synchronous writes to the [HTTP response](https://github.com/aspnet/Announcements/issues/342) since the serializer is entirely synchronous. 

At any given time, the buffer keeps 32k in memory, followed by writing further content to disk. Consequently, your disk I/affects the response time for payloads larger than 32k. We've had a similar discussion about this: https://github.com/dotnet/aspnetcore/issues/17843. https://github.com/dotnet/aspnetcore/issues/17843#issuecomment-565616355 has some guidance on what you could consider doing in your application.
