### ISSUE TITLE
[Blazor] Support pre-compression using brotli

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#19644]
We currently do this for gzip, but we also want to do it for brotli.

We need to evaluate the impact it has on the build on cold build and on warm build and based on that whether we enable an option to compress on publish only.

**Comment by MarkusRodler** [comment]
@javiercn I think this is a really cool feature. But unfortunately this is only be applied to files from the framework. Is it also possible to include the other files in the project like js, css and svg files?

**Comment by javiercn** [comment]
@MarkusRodler we are looking to expanding it for other files. Unfortunately we didn't have time to make it for the current release. We'll look into improving the situation in the future.
