### ISSUE TITLE
Warning when subscribing to child razor component event

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#19643]
Following the subscriber pattern described in "1." at https://github.com/dotnet/aspnetcore/issues/15651#issuecomment-415760918, it works well, however 2 identical warnings are generated for the line `ChildComponent1.YearChanged += ChildFiredEvent;` in the parent component that state:

> Warning BL0005: Component parameter 'YearChanged' should not be set outside of its component.

Is this still the right way to go about triggering a refresh on a parent component from a child?

### Further technical details
- ASP.NET Core version: 3.1.2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Mac 8.5 Preview (8.5 build 3129)
- $ dotnet --info

> .NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

> Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

> Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

> .NET Core SDKs installed:
  3.1.102 [/usr/local/share/dotnet/sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by mrpmorris** [comment]
The recommended way to do it is to add a parameter property to the child, and two-way bind that from the parent. This will automatically rerender the parent. 

https://blazor-university.com/components/two-way-binding/

**Comment by mrlife** [comment]
@mrpmorris What is the recommended data type for when no actual data needs to be sent from child to parent?

**Comment by mrlife** [comment]
@mrpmorris Even when no actual data needs to be sent from child to parent?

**Comment by mrpmorris** [comment]
@mrlife yes. If the parent needs to know when something happens in a child then you use EventCallback.

If the child needs to edit data from its parent then you need to add a [Parameter] decorated property to the client with an XXXChanged event and two-way bind your parent's property to that child property.

**Comment by enetstudio** [comment]
@mrlife, you should do as mrpmorris has suggested...

@mkArtakMSFT, this is not a bug.  YearChanged  is a component parameter  property defined in the child component. Coding like this: `ChildComponent1.YearChanged += ChildFiredEvent;` is actually trying to change the property outside of its component, which currently only illicit a warning not to do so, but still working. I don't see any bug here... The user was redirected to a good site where he can learn how to do it properly...

**Comment by mrpmorris** [comment]
There's a tutorial here - https://blazor-university.com/components/two-way-binding/

**Comment by mrlife** [comment]
@mrpmorris @enetstudio Thank you. I went with the `EventCallback` (no `<T>` since I didn't have any value to return from the child to the parent). Works great!
