### ISSUE TITLE
Alternative to System.Web.Security.Membership.GeneratePassword

### ISSUE THREAD

**Issue by keerthimaryala18** [dotnet/aspnetcore#19653]
# Issue Title

Alternative to System.Web.Security.Membership.GeneratePassword in .NET Core 2.2

# General

I am migrating an application built on .NET Framework to .NET Core 2.2 and as a part of  authentication, use the System.Web.Security library to generate the password in the old app. There doesn't seem to be an equivalent to this in .NET Core. I have seen many posts about implementing the same rules from the source code available https://github.com/Microsoft/referencesource/blob/master/System.Web/Security/Membership.cs
Is this the best way I can do? Our applications also has to cater to existing logins. Is there any other way/library I can use to generate passwords the same way as in .NET Framework?

**Comment by blowdart** [comment]
That API was problematic, and somewhat biased in the characters we choose. Also the nist password guidelines recommend letting users choose their own passwords so it's not something we are considering implementing in Core in any way.
