### ISSUE TITLE
Blazor (3.1.102) Server/Client from template does not work with VS2019 docker debbuging - System.ArgumentException: 'The path must be absolute.'

### ISSUE THREAD

**Issue by skubia** [dotnet/aspnetcore#19656]
Step to reproduce:

install template from official MS site: 

1. _dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1_
2. add docker support
3. Run it with VS2019 F5 version 16.4

I am using SDK 3.1.102

**Comment by skubia** [comment]
workdaround: https://stackoverflow.com/questions/59228315/debug-blazor-wasm-using-visual-studio-container-tools

**Comment by mkArtakMSFT** [comment]
This should already fixed in the 3.2-preview2 release and you should be able to debug the server code.
