### ISSUE TITLE
Blazor Wasm OpenId Connect

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#19669]
Is there any documentation on how to configure a client side Blazor to use authentication and authorization from a token provider like IdentityServer 4?

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

We've actually implemented this in our current milestone and it will be available in the next preview (coming in the following days) so keep an eye on the announcements in the coming weeks.

Hope that helps.
