### ISSUE TITLE
The Server project in an ASP.NET Core hosted Blazor WebAssembly app doesn't define an error page

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#19670]
The Server project in an ASP.NET Core hosted Blazor WebAssembly app sets up middleware to redirect to `/Error` if an there's an unhandled exception, but no `/Error` endpoint is defined: https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Server/Startup.cs#L93-L98.

**Comment by mkArtakMSFT** [comment]
This should be handled with #17312

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/20352
