### ISSUE TITLE
EditForm and Antiforgery for Blazor Web Assembly

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#19687]
Hello,

I am trying to add antiforgery protection to the EditForm for login and registration.

I have added the ```[AutoValidateAntiforgeryToken]``` attribute for the controller 
and the following coding at startup for the server part:

```
services.AddMvc(options =>
{
     options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});
```
The server response is 400 Bad request when a log in operation is submitted.
How to resolve it? Is there an anti-forgery mechanism in EditForm? Or with the addition of ```@Html.AntiForgeryToken()```?

### Further technical details

ASP.NET Core version 3.1.2
Blazor WebAssembly 3.2.0 Preview 1
Microsoft Edge 82.0.439.1
It's a Blazor Web Assembly with ASP.NET core hosted
Visual Studio 16.5.0 Preview 5.0

**Comment by saber-wang** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1#javascript-ajax-and-spas

**Comment by boukenka** [comment]
Thank you @saber-wang. 😄 
But this does not solve the question for a Blazor Web Assembly project model.

**Comment by saber-wang** [comment]
@boukenka Can do

![0A48DD7A-D8E2-488D-85DD-5932AC3AB4B0](https://user-images.githubusercontent.com/45062099/76192866-c4969d00-621d-11ea-9379-9dffab06267a.jpeg)
![0F0ABE7D-5F06-4D3D-8591-533A0D20FFDE](https://user-images.githubusercontent.com/45062099/76192876-ca8c7e00-621d-11ea-885a-40cb6e177782.jpeg)

**Comment by saber-wang** [comment]
Can do
`services.AddAntiforgery(options => options.HeaderName = "X-CSRF-TOKEN");
`
```
app.Use(next=>context=> 
            {
                var tokens = antiforgery.GetAndStoreTokens(context);
                context.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken,new CookieOptions() {HttpOnly=false });
                return next(context);
            });
```
```
@code {
    private WeatherForecast[] forecasts;

    protected override async Task OnInitializedAsync()
    {
        var token = await JSRuntime.InvokeAsync<string>("getCookie", "XSRF-TOKEN");

        Http.DefaultRequestHeaders.Add("X-CSRF-TOKEN", token);
        forecasts = await Http.PostJsonAsync<WeatherForecast[]>("WeatherForecast", null);
    }

}

```
```
function getCookie(cname)
{
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for (var i = 0; i < ca.length; i++)
    {
        var arr = ca[i].split('=');
        if (arr[0] == cname)
            return arr[1]
    }
    return "";
}
```

![内网通截图20200309160506](https://user-images.githubusercontent.com/45062099/76194050-4daed380-6220-11ea-817e-75fccb5e9c84.png)

**Comment by RemiBou** [comment]
I managed it in this blog post : https://remibou.github.io/CSRF-protection-with-ASPNET-Core-and-Blazor-Week-29/ (it was on one of the early preview but it's still ok), basically you need a bit of jsinterop for parsing the cookies and send this as http header.

**Comment by boukenka** [comment]
Thank you both @RemiBou and @saber-wang for your help and the time you took to provide me with explanations. 😄 It works!
