### ISSUE TITLE
Blazor: Using Entity Framework Issues

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#19688]
Related to #10448

### Running into related issue
Wanted to check if there is anymore guidance since #10448 is now locked. I mention some issues below just to try and give my request some context.

We are employing Server-Side Blazor with Scoped DB Contexts currently.

### Issues We Have Seen
1) Cannot run same query against db Context on multi threads. Since Blazor component lifecycle methods run in no particular order across components (i.e. 2 separate component's initialize methods may run at the same time) we would experience two separate components executing the same query on the same db context (DI Scoped Lifecycle) at the same time causing an exception to throw. When we switched the DI Lifecycle to Transient this solved our issue some of the time unless 2 separate components were using he same transient instance, it seems, of the DB Context, due to injection of higher level services that maybe were of a Scoped lifecycle. What we would like maybe some better guidance on is how best to avoid this (e.g. OwningComponent and if that creates a Transient Scope for all Services injected in the Service added to the scope?) but more importantly what are the performance trade-offs (e.g. memory pressure in Blazor Server-Side given Scoped or Transient DBContexts). Having clear guidance here would be beneficial to not make this such a time-sync for research and problem solving.

2) Scoped or even Transient DBContexts can be disposed before subsequent usage. So if we were employing a using statement somewhere along the line we would see the instance become disposed and subsequent db context access would throw an error. Our solution, where we could not just use the injected DBContext, was to create a new Context inside a using statement with the ConnectionString of the injected Context. We will be trying to correct this but until then we do not seem to have a way to assess impact on the code until we can address the issue. So imagine trying to rework a codebase into Blazor that is complex and rife with using statements (as that was best practice for many years).

3) Given that our DBContext is a Scoped Lifecycle we experienced issues when we wanted to update an entity but an error occurred on `await SaveChangesAsync()`. The SaveChangesAsync() error does not clear and modifications to the Entites since the last SaveChangesAsync call so when we run a subsequent operation on the DBContext, no matte what that call is the entity with the previously errored update will commit it (or try to commit it) to the data store. This scenario makes for some very confusing and time consuming debug sessions. On top of that there is really no clear and concise method of handling the problem. Our solution for now is to trap the error and perform:

```
if (item != null)
                {
                    switch (_dbCtx.Entry(item).State)
                    {
                        case EntityState.Modified:
                            _dbCtx.Entry(item).State = EntityState.Unchanged;
                            break;
                        case EntityState.Added:
                            _dbCtx.Entry(item).State = EntityState.Detached;
                            break;
                        case EntityState.Deleted:
                            await _dbCtx.Entry(item).ReloadAsync();
                            break;
                    }
                }
```

We have heard some discussion about just make your DI Lifecycle Transient or go back to using statement and transient DBContext lifecycle. Just want to see if there is any clear guidance out there yet. We really want to spend more of our time implementing business features for our customers as opposed to hunting down these kinds of issues related to what could be perceived as basic fundamental CRUD operations with a best practice performance configuration. Not trying to complain but that is how this feels.

Hope this makes some sense.

Thanks!

**Comment by mrpmorris** [comment]
Have you tried creating an interface IDbContextFactory to create context instances and injecting that instead? That way you could create instances on demand and dispose of them too.

**Comment by chassq** [comment]
Since IDbContextFactory  looks to be obsolete would you be meaning IDesignTimeDbContextFactory<TContext> (https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.idesigntimedbcontextfactory-1?view=efcore-3.1)? Also looks kind of complex to get the connection string from configuration injected into the IDesignTimeDbContextFactory? Any ideas there?

Thanks!!

**Comment by mkArtakMSFT** [comment]
@ajcvickers do you have any guidance around how to avoid the first issue above?

> Cannot run same query against db Context on multi threads. Since Blazor component lifecycle methods run in no particular order across components (i.e. 2 separate component's initialize methods may run at the same time) we would experience two separate components executing the same query on the same db context (DI Scoped Lifecycle) at the same time causing an exception to throw. When we switched the DI Lifecycle to Transient this solved our issue some of the time unless 2 separate components were using he same transient instance, it seems, of the DB Context, due to injection of higher level services that maybe were of a Scoped lifecycle. What we would like maybe some better guidance on is how best to avoid this (e.g. OwningComponent and if that creates a Transient Scope for all Services injected in the Service added to the scope?) but more importantly what are the performance trade-offs (e.g. memory pressure in Blazor Server-Side given Scoped or Transient DBContexts). Having clear guidance here would be beneficial to not make this such a time-sync for research and problem solving.

**Comment by mrpmorris** [comment]
@chassq Sorry, I meant to create your own. I didn't even know that one existed.

**Comment by chassq** [comment]
@mrpmorris Thanks for that I will look into it more!

**Comment by ryanelian** [comment]
In my company, we like to make a god class for injecting all our scoped services INCLUDING the `DbContext`:

```cs
    public class ApplicationService
    {
        public ApplicationService(MyDbContext myDbContext,
            MyOtherServiceWhichRequiresDbContextToo otherService)
        {
            this.DB = myDbContext;
            this.OtherService = otherService;
        }

        public MyDbContext DB { get; }
        
        public MyOtherServiceWhichRequiresDbContextToo OtherService { get; }
    }
```

I know, it gets messy real fast in a large project. You might want to split that. Or not, since this god class allows you to summon required services without `@inject` or `[inject]` for convenience.

But anyway, it allows you to make this then:

```cs
    public class ApplicationServiceComponent : OwningComponentBase<ApplicationService>
    {
    }
```

Which then allows you to do this:

```cs
@inherits ApplicationServiceComponent
```

Which makes the DbContext somehow scoped to THAT component only. Solves whatever EntityFramework issue with Blazor:

- Two distinct components calling `DbContext` can now have their own scoped `DbContext` which allow two queries to run in parallel.

- The scoped `DbContext` unique to the component will only be disposed when the component is disposed.

- Which allows using `DbContextPool` for performance increase (?)

**Comment by ajcvickers** [comment]
@mkArtakMSFT It's [in the 5.0 plan to figure out the guidance and patterns for using EF with Blazor](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#ef-core-platforms-experience). (Note though that is probably not just EF, since the underlying ADO.NET objects are also by-design not thread-safe.)

/cc @bricelam @JeremyLikness @roji

**Comment by mkArtakMSFT** [comment]
Good to know, @ajcvickers. Should I move this issue over to ef to track it, or do you have a separate tracking issue to dupe this with.

**Comment by ajcvickers** [comment]
@mkArtakMSFT https://github.com/dotnet/EntityFramework.Docs/issues/2025

**Comment by mkArtakMSFT** [comment]
Thanks. Closing this as a dupe then.
