### ISSUE TITLE
Blazor Circuit not Initialized

### ISSUE THREAD

**Issue by VideoAppsNet** [dotnet/aspnetcore#19682]
Getting error where if user put there browser into sleep mode and comes back after 3 minutes my blazor app reconnects but the ui is not usable anymore. I have to do a manual refresh. Here is a screen shot of the chrome inspect log from an iPhone. Web socket reconnects after those 3 minutes but the circuit is not initialized. Shouldn't blazor create a new circuit and transfer the state from the old circuit? But in my website the circuit gets an error. This is very bad since users have to refresh the whole page after only putting away there browser for 3 minutes. Not a usable website. I spent 10 hours+ on this issue and no matter what I do on my server side (Windows Server 2019) or in my blalzor code nothing helps to change this outcome. Please help me out.
https://imgur.com/0NhqfsN

This is the last thing remaining from me finishing the site.

**Comment by VideoAppsNet** [comment]
What im trying to store is just the ui on the page. So a user is searching for content and loads some search results. Then that user leaves the browser. After 3+ minutes  they come back and want to see there results again. Blazor does not keep these search results loaded in the browser? Currently for me blazor reconnects and shows the ui. But If I try to interact with the ui such as clicking a button from the search results blazor blows up and shows circuit lost, unhandled exception and I have to reload the whole page. Is this normal? If so this is a huge problem for blazor. I dont want to store 100+ search results for each and every user. I just want to keep the ui interactive. It loads the ui back but the buttons are not clickable and errors out as soon as I click an button.

**Comment by javiercn** [comment]
@VideoAppsNet thanks for contacting us.

Blazor can't keep the session state in memory forever. When the machine is put to sleep, the circuit gets disconnected and the resources are claimed after 3 minutes. You can configure the time you keep circuits in memory. See [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.circuitoptions.disconnectedcircuitretentionperiod?view=aspnetcore-3.1#Microsoft_AspNetCore_Components_Server_CircuitOptions_DisconnectedCircuitRetentionPeriod)

When the app comes back after the circuit has been disposed, the state is gone, but if you need to preserve the state in these situations there are strategies described here to do so:
https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1

You can detect this situation and automatically reload the page for the user, bringing them back to the old experience
