### ISSUE TITLE
Blazor: add tool that checks if net standard  library will work with Mono on WASM

### ISSUE THREAD

**Issue by filipoff2** [dotnet/aspnetcore#19699]
### Is your feature request related to a problem? Please describe.
I am trying to  Generate PDF on Client side =  WASM Blazor.
I checked few libraries/nuget , they are compiling but exceptions in run time

### Describe the solution you'd like
Online form tool that check  if package will work in run-time . 
Add support for WASM here:
https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer

### Additional context
https://github.com/filipoff2/Hello_wasmBlazor/commit/67b2d171e6bf374e93af6bcf717f04485b6828f2

**Comment by RemiBou** [comment]
What is your runtime exception ? 

It seems that in your code you are trying to save some code on disk, you can't save to disk as user's browser does not allow it. This is not a platform problem but an environment problem (Blazor wasm can be executed on Electron). 

Maybe the monowasm platform does not implement the full netstandard, in this case a tool for helping would be really helpful indeed.

**Comment by filipoff2** [comment]
// Encoding 1252 data could not be found. Make sure you have correct international codeset   
https://github.com/filipoff2/Hello_wasmBlazor/commit/67b2d171e6bf374e93af6bcf717f04485b6828f2

1) I'm creating PDF in Memory and when trying to write to PDF document to memory stream exception is thrown.  	

MemoryStream memoryStream = new MemoryStream();
document.Save(memoryStream, true);

// Encoding 1252 data could not be found. Make sure you have correct international codeset   assembly installed and enabled.
I found something similar as in https://github.com/andreakarasho/ClassicUO/issues/715

2) Save via JS works OK :
 document.Save(memoryStream, true);
 this works. 
 Idea was taken from Server Side Blazor:
 https://www.syncfusion.com/kb/10358/how-to-create-a-pdf-file-in-blazor-using-c
 Save part 2 work good.

**Comment by mkArtakMSFT** [comment]
@terrajobst is there any other issue tracking this?

**Comment by javiercn** [comment]
There are attributes in 5.0 that will mark the supported platforms in the assembly, not sure if this is something our team should tackle.

@mkArtakMSFT  @danroth27 feel free to move the issue to the runtime repo, I'm closing this here for now.

**Comment by danroth27** [comment]
The .NET platform compatibility analyzer now fills this role: https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer

**Comment by filipoff2** [comment]
@terrajobst nice video: 
https://www.youtube.com/watch?v=A_y1gIzzRT8
