### ISSUE TITLE
%2B causes HTTP 404 on wildcard requests

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/aspnetcore#19698]
### Describe the bug
When a request is performed to a controller route using a wildcard string parameter containing %2B an HTTP 404 is returned.

### To Reproduce

``` C#
        [HttpPut("{*path}")]
        [ProducesResponseType(200, Type = typeof(Models.Output.Symbols.Symbol))]
        public async Task<IActionResult> PutSymbol([FromRoute] string path, [FromBody, Required] Models.Input.Symbols.SymbolMerge sym)
        {
        }
```

The exception is in python and returned by the Asp.Net Core App: OSError: Invalid request : return code is 404
-->

### Further technical details
- ASP.NET Core version 2.2

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- IDE: Visual Studio 2019 Community Edition

- Note: Problem also occurs under Azure App Service

**Comment by Yuri6037** [comment]
Hello I would like to add that for some reasons after upgrading the entire project to dotnet core 3.1 instead of 2.2, this only happens under Azure App Service it no longer happens on my local computer

**Comment by javiercn** [comment]
@Yuri6037 that looks like an encoding issue somewhere in your app. It can be that something is double encoding the value or that something is decoding the value before it gets to ASP.NET Core and routing is interpreting it differently.

**Comment by Yuri6037** [comment]
I tried to run the application in debug mode directly on the Azure server. The breakpoint in my middlewares before MVC does not even trigger, it seem that the problem happens before reaching Asp.Net Core. In local standalone Debug and Release is fine.

**Comment by Yuri6037** [comment]
Hello, I found something, apparently this is a bug in IIS as Azure services uses IIS...
