### ISSUE TITLE
AmbiguousMatchException: The request matched multiple endpoints when using MapDynamicPageRoute. Matches: / Index / Index

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/aspnetcore#19697]
![image](https://user-images.githubusercontent.com/5792218/76175701-c85bfc80-61e8-11ea-8743-b5d1ea38cc01.png)

AmbiguousMatchException: The request matched multiple endpoints. Matches: /Index /Index
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

` Url = Url.Replace("/Index", "", StringComparison.OrdinalIgnoreCase).TrimEnd('/');

            var m = SystemRout.FindByRTypeAndUrl(2, Url);
            if (m != null)
            {
                values["page"] = m.Pages;
                values["area"] = m.AreaName;
            }

            return new ValueTask<RouteValueDictionary>(values);

`

**Comment by rynowak** [comment]
More detail here: https://github.com/dotnet/aspnetcore/issues/12705

This is our first time getting a user-report of this problem that I remember.

**Comment by rynowak** [comment]
Nevermind, it looks like a few other people reported it in #12705

**Comment by mkArtakMSFT** [comment]
Thanks @rynowak . Closing as a dupe.

**Comment by qcjxberin** [comment]
Tks
