### ISSUE TITLE
Asp.Net Core Blazor Server Excessive Logging in IIS

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#19701]
### Describe the bug
After deploying Blazor Server solution to onpremise IIS / Windows Server, the Blazor Server App is writing to the IIS log file(s) a lot of data which is creating large log files.  Tried changing the appSettings.json Logging:LogLevel to 'Error' for each of the items listed:
- Default
- System
- Microsoft
- Microsoft.Hosting.Lifetime
- Microsoft.AspNetCore.SignalR
- Microsoft.AspNetCore.Http.Connections
This has no effect.

### To Reproduce
- Create new Blazor Server app
- Adjust the default logging in appSettings.json to 'Error'
- Deploy Blazor Server app to onpremise IIS / Windows server
- Browse a page
- Review IIS logs and notice all the logging from the Blazor Server app even though 'Error' level was specified 

### Further technical details
- ASP.NET Core version
3.1
- Include the output of `dotnet --info`
PS C:\Users\rsurles> dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Users\rsurles>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you share a small app to demonstrate this issue? We don't observe this, by the way.
The logs would also be useful, by the way.

**Comment by davidfowl** [comment]
@royaljust What's the IIS log file?

**Comment by royaljust** [comment]
@davidfowl - I think you're looking for @roysurles...

**Comment by davidfowl** [comment]
oops 😄

**Comment by roysurles** [comment]
The name of the log file on the IIS server is:  C:\inetpub\logs\LogFiles\W3SVC2\u_ex200309.log

Attached is the zip of the log file.  There are numerous GET / POST for the Blazor Server App 'EngWeb'.
[u_ex200309.rename to zip](https://github.com/dotnet/aspnetcore/files/4307870/u_ex200309.rename.to.zip)

**Comment by roysurles** [comment]
Working on getting an example app that demonstrates this issue... next.

**Comment by davidfowl** [comment]
These are the normal W3C logs in IIS. It looks like you might not be using websockets. Do you have WebSockets configured on your IIS installation? Can you look at the logs in the browser to see what transport blazor is using?

**Comment by roysurles** [comment]
'WebSocket Protocol' is NOT installed / checked off under Application Development.

![image](https://user-images.githubusercontent.com/37274814/76238678-352dc180-61fe-11ea-9203-604f1d2bdb5a.png)


When I open the log file in the browser, its pretty much the same information as opening the log file in notepad... i dont see any difference or the 'transport'.

**Comment by davidfowl** [comment]
Install it and those logs will go away. It's falling back to a transport that's making HTTP requests for ever change. Not very efficient for Blazor server.

**Comment by roysurles** [comment]
Installed WebSocket Protocol' suppressed all the logging... thank you!
