### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by ZwieberVos** [dotnet/aspnetcore#19704]
Hi,
I want to start programming and i am pretty trash
but i have some cool idea's
my idea is:
i want to make a website where my kids can fill in their data and a program will run and fill it in in the actual website and gives me a message trough my email what they entered and when

If you can help me please
i would appriciate it
you can contact me trough email 
ZwieberV@gmail.com

**Comment by davidfowl** [comment]
This is the wrong place for that kind of request. It's great you want to get into programming, I would suggest using one of our tutorials on Microsoft Learn https://docs.microsoft.com/en-us/learn/modules/create-razor-pages-aspnet-core/?view=aspnetcore-3.1
