### ISSUE TITLE
Provide a simple way to turn an existing app into a PWA

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#19710]
We now have an option on project creation to create a Blazor WebAssembly app that is setup as a PWA. But what if I have an existing Blazor WebAssembly app and I want to turn into into a PWA? Should we have some sort of package that you can add to an existing app that enables PWA functionality? This appears to be how Angular is setup: `ng add @angular/pwa --project AngularBooksPWA`.

**Comment by marcusturewicz** [comment]
I added PWA functionality recently to my [Blazor Wasm website](https://github.com/marcusturewicz/jsonvalidate.net/pull/93/files) by copying relevant files from a dummy project generated from the new PWA template, so I'd be happy to write a doc on how to do this in the meantime in leu of a package being developed?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
