### ISSUE TITLE
Blazor "session" storage

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#19715]
### Is your feature request related to a problem? Please describe.
Ability to save simple values (e.g. `string`, `int`) that are available between route changes and page refreshes and understand how to implement it

Is there a convention that is detailed somewhere?

### Describe the solution you'd like
I've read the popular issues here on this topic and haven't been able to find a solution. Things are alluded to but no path finds an actual solution.

There are recommendations for:
- HTML5 `localStorage` or `sessionStorage` but no locatable, built-in way to implement them via ASP.NET Core/Blazor
- `ConnectionContext.Items`, which I couldn't get to work due to DI errors
- adding actual ASP.NET `HttpContext` session to `_Host.cshtml.cs`, which is a limited workaround
- using a `ClaimsPrincipal`, which requires adding Authentication.

One of these will be fine if it solves it, but I can't tell if they are overkill. Ideally, there would be a package that gives access to the browser's `sessionStorage` (the one I'm likely to use), is used like a dictionary, and implements [Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-3.1).

**Comment by boukenka** [comment]
There is a protected browser storage  [#18755](https://github.com/dotnet/aspnetcore/issues/18755) planned for 5.0.0-preview2.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mrlife.
As @boukenka has pointed out, the referenced issue will cover this.
