### ISSUE TITLE
Self Signed Certificate on macOS

### ISSUE THREAD

**Issue by Steve0212a** [dotnet/aspnetcore#19711]
### Describe the bug
I am using DotNet Core 3.1 and ASP.NET Core 3.1.1.  I am creating a self signed certificate via .net core code and storing it in a certificate store.  The certificate has the server authentication oid specified and the code **works without issues on Windows**.  However, on macOS, I get this error:
`System.InvalidOperationException: Certificate B21E2209FE4B1B067C25252B76FDB0F9410E1853 cannot be used as an SSL server certificate. It has an Extended Key Usage extension but the usages do not include Server Authentication (OID 1.3.6.1.5.5.7.3.1).`

Here is my code for generating the certificate (notice it specifies the oid):
```
        internal static X509Certificate2 GetCertificate()
        {
            var certificate = GetCertificateFromStore();
            if (certificate == null)
            {
                // get the store and open it as read/write
                using X509Store store = new X509Store(CertificateStoreName, CertificateStoreLocation);
                store.Open(OpenFlags.ReadWrite);
                
                // generate a new certificate
                certificate = BuildSelfSignedServerCertificate();

                // save it in the store
                store.Add(certificate);

                // close the store
                store.Close();
            }

            // return back the cert
            return certificate;
        }

        private static X509Certificate2 GetCertificateFromStore()
        {
            // build the return value
            X509Certificate2 retval = null;

            // get and open a read only copy of the cert store
            using X509Store store = new X509Store(CertificateStoreName, CertificateStoreLocation);
            store.Open (OpenFlags.ReadOnly);

            // search for the certificate looking for a valid expiration date.  that way, when the cert is expired, a new one will be created
            var certificateCollection = store.Certificates.Find(X509FindType.FindByTimeValid, DateTime.Now, false);
            if (certificateCollection.Count > 0)
                retval = certificateCollection[0];

            // close the store
            store.Close();

            // return anything we found
            return retval;
        }

        private static X509Certificate2 BuildSelfSignedServerCertificate()
        {
            // build the certificate's subject
            SubjectAlternativeNameBuilder sanBuilder = new SubjectAlternativeNameBuilder();
            sanBuilder.AddIpAddress(IPAddress.Loopback);
            sanBuilder.AddIpAddress(IPAddress.IPv6Loopback);
            sanBuilder.AddDnsName("localhost");
            sanBuilder.AddDnsName(Environment.MachineName);

            // build the distinguished name
            X500DistinguishedName distinguishedName = new X500DistinguishedName(CertificateDistinguishedName);

            // create an RSA key and a certificate request
            using RSA rsa = RSA.Create(2048);
            var request = new CertificateRequest(distinguishedName, rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
            request.CertificateExtensions.Add(
                new X509KeyUsageExtension(X509KeyUsageFlags.DataEncipherment | X509KeyUsageFlags.KeyEncipherment | X509KeyUsageFlags.DigitalSignature, false));
            request.CertificateExtensions.Add(
                new X509EnhancedKeyUsageExtension(
                    new OidCollection {new Oid("1.3.6.1.5.5.7.3.1")}, false));  // server authentication OID
            request.CertificateExtensions.Add(sanBuilder.Build());

            // create the self signed certificate
            var certificate = request.CreateSelfSigned(new DateTimeOffset(DateTime.UtcNow.AddDays(-1)), new DateTimeOffset(DateTime.UtcNow.AddDays(3650)));
            certificate.FriendlyName = CertificateFriendlyName;

            return new X509Certificate2(certificate.Export(X509ContentType.Pfx, CertificatePassword), CertificatePassword, X509KeyStorageFlags.MachineKeySet);
        }
```

and here is where I tell it to use the certificate (the call to CertificateHelper.GetCertificate() calls the GetCertificate() method above):
```
.ConfigureKestrel(options =>
                {
                    options.ConfigureHttpsDefaults(o =>
                    {
                        o.ServerCertificate = CertificateHelper.GetCertificate();
                    });
                })
```

Questions (bare in mind, I am not a MAC expert):

1. While the certificate was created, how can I view it?  I tried the keychain program, but I did not see it in there.  Guessing since I am storing it in local machine, that my keychain program cannot see it.
2. Any idea why the same code works on Windows to properly create the certificate and then use it to start my REST EPA?
3. My requirements are to make my REST EPA use HTTPS and the certificate must be unique to each end user machine.  This will be installed for end users (not corporate), so I do not want to use the dev certificate.  Is there a better way to make this work on macOS?

Thanks for any help you could provide.

**Comment by mkArtakMSFT** [comment]
@javiercn can you please look into this? Thanks!

**Comment by javiercn** [comment]
@Steve0212a thanks for contacting us.

If your issue is specifically about creating a cert, I recommend you file an issue in [the runtime repo](https://github.com/dotnet/runtime) as they will be able to provide you with a better and faster answer.

**Comment by Steve0212a** [comment]
I wouldn't say it is about creating a cert.  The cert gets created on windows and on macOS (and also on Ubuntu which I recently tried).  However, when I try to use the cert on macOS, I get the error I specified above.  The same generated cert from the same code on Windows works.  Same for Ubuntu - same code generating a certificate and ASP.NET successfully used the generated certificate.  The code for ASP.NET to use the cert for HTTPS only fails on macOS.

**Comment by javiercn** [comment]
@Steve0212a what's the error/callstack. From what you are saying it seems to me that the issue is with the the certificate APIs in Mac OS. I still suggest you follow up with the [dotnet/runtime](https://github.com/dotnet/aspnetcore) folks as they'll be able to help you faster and better.

If you post the callstack I'll take a look at it and see if it can be something on our side, but my theory is that is something on the cert APIs.

**Comment by Steve0212a** [comment]
I actually got it to work by changing the location of the certificate store to StoreName.My instead of a custom store name (which worked on Windows).  Not sure why the storage location would fix this though.

Below is the stack trace if it helps at all.  I am going to close this item, but am curious if first, you can tell me why the store location would cause this exception...

thx

```
Unhandled exception. System.InvalidOperationException: Certificate B21E2209FE4B1B067C25252B76FDB0F9410E1853 cannot be used as an SSL server certificate. It has an Extended Key Usage extension but the usages do not include Server Authentication (OID 1.3.6.1.5.5.7.3.1).
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.EnsureCertificateIsAllowedForServerAuth(X509Certificate2 certificate)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   <my line of code that calls run>
Abort trap: 6
```

**Comment by javiercn** [comment]
@Steve0212a I'm not sure why that is the case, I have no significant understanding of how the certificate store APIs are implemented on Mac OS, that's why I was pointing you to the dotnet/runtime repo.

That said, that callstack looks wrong. @Tratcher it seems like the exception kestrel throws here might be incorrect? Should this be transferred to servers for investigation?

**Comment by Tratcher** [comment]
@Steve0212a is GetCertificateFromStore returning the right certificate? It looks like it's returning the first certificate it finds, not necessarily the one you created. You need to filter that list to make sure you pick the right certificate.

**Comment by Steve0212a** [comment]
you are correct.  The code was not returning the proper certificate.  Sorry for the mistake.
