### ISSUE TITLE
Question / Feature Request: Does Server-Side Blazor Render DateTimeOffset (or DateTime UTC) into Browser Local Time?

### ISSUE THREAD

**Issue by ryanelian** [dotnet/aspnetcore#19717]
### Is your feature request related to a problem? Please describe.

I am wondering if I have a `DateTimeOffset` (or `DateTime` variable which is usually UTC from the database) rendered in Blazor server-side `@MyDateTimeOffset`, would it be converted to local time according to the browser time zone?

### Describe the solution you'd like

If the answer to the problem above is no, may I suggest a convenience component / API for dealing with above problem in future Blazor versions?

```cs
// @inject to Blazor page / component just like IJSRuntime
public interface IBrowserDateTimeUtility
{
    DateTimeOffset ConvertToBrowserLocalDateTime(DateTimeOffset value);
}
```

<details>
<summary>Original Suggestion</summary>

```cs
<BrowserLocalDateTime Value="MyDateTimeOffset"></BrowserLocalDateTime>
```
</details>

How it works: Server-Side Blazor JS should get browser / client time zone when first run:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

That value will then be cached throughout the connection and will be used to convert the input `DateTimeOffset` into the browser time zone for display automatically.

... Heck, I wouldn't mind if you guys renders `DateTimeOffset` `@MyDateTimeOffset` into the browser time zone by default.

### Additional context

This convenience method / API / component is critical because developers should not run / write JS interop (which causes client-server communication via SignalR!) for each and every DateTime they write to the UI. (Penalizes application performance)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to implement.
