### ISSUE TITLE
Blazor: prevent (or warn on) component recursion?

### ISSUE THREAD

**Issue by chucker** [dotnet/aspnetcore#19720]
## Is your feature request related to a problem? Please describe.

I had a component, let's call it `Shared/ContactCard.razor`, and to make manual testing easier, I wrote a page `Pages/Test/ContactCard.razor`, with `@page "/Test/ContactCard"` at its start, and various things inside it, including, critically:

```xml
<ContactCard />
```

Now, this _compiles_ just fine.

When loading it in the browser, however, the page never appears, and you eventually get `System.OutOfMemoryException` in the browser console.

It took a while until it dawned on me that the compiler had (presumably!) interpreted `<ContactCard />` to _recursively refer to the page itself_, rather than the identically-named (but differently-namespaced) _component_; I had written an infinite recursion.

## Describe the solution you'd like

There may be scenarios where nesting a component inside itself is useful. However, the experience here isn't great. You get no compile-time warning at all that this may not be the behavior.

My hunch is this kind of recursion should at least produce a warning. In my particular case, it would have helped if the compiler had recognized the ambiguity (did I really mean `MyProject.Pages.Test.ContactCard`, or did I perhaps mean `MyProject.Shared.ContactCard`?), and in that case _not_ implicitly used the local type.

## Workarounds

Explicitly specifying the namespace resolves this:

```xml
<MyProject.Shared.ContactCard />
```

Which is fine, but it's not at all intuitive that this is the problem that's going on.

### Additional context

A screenshot of the exception that eventually occurs:

![image](https://user-images.githubusercontent.com/20194/76256309-fde80080-624f-11ea-8a8d-fcef723b7ce8.png)

**Comment by masonwheeler** [comment]
Many developers use a setting to treat warnings as errors; this would break legitimate recursion for them.

Your problem here isn't with recursion; it's with ambiguity.  What's needed is an error (probably better to have it be an error than a warning) for referencing an ambiguous component.

**Comment by chucker** [comment]
> What's needed is an error (probably better to have it be an error than a warning) for referencing an ambiguous component.

I’d be OK with that.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is the same as the normal C# compiler behavior. Developers should be aware of the type names and don't duplicate them.
