### ISSUE TITLE
HTTP2: content-length header string allocation

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#19731]
When a response has no content its content length is set to zero.

https://github.com/dotnet/aspnetcore/blob/8ec31594eae83295fb2c86d99d23c32ad33da5b0/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1146-L1154

The logic lives on the HttpProtocol base class. Is returning `content-length=0` desirable in HTTP/2?

Assuming we want to keep returning the header, iterating over response headers causes `HttpHeaders.ContentLength` to allocate.

https://github.com/dotnet/aspnetcore/blob/8ec31594eae83295fb2c86d99d23c32ad33da5b0/src/Http/Headers/src/HeaderUtilities.cs#L558-L578

The simple fix here is check for zero in `FormatNonNegativeInt64` and return `"0"` directly.

**Comment by Tratcher** [comment]
> Is returning `content-length=0` desirable in HTTP/2?

Yes, this is still a useful hint for client apps.
