### ISSUE TITLE
Support more logger features

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19737]
`WebAssemblyLoggerFactory` and `WebAssemblyConsoleLogger` lack support for:

 * `factory.AddProvider` (currently, it throws `NotSupportedException`)
 * Controlling the default log level (currently, `IsEnabled` is hardcoded to return `logLevel >= LogLevel.Warning`)

Once we have a configuration feature we might want to implement the second of those. The first one is most likely unnecessary for the May release.

Theoretically anyone who wants to can replace the built-in `ILoggerProvider` with their own implementation so as to fill in any feature gaps that trouble them, so nobody is really strictly blocked by this.

**Comment by captainsafia** [comment]
I'm going to go ahead and close this now since most of this was implemented in #20432.

The configuration aspect of this can certainly be a little bit more polished. We don't currently support `builder.Logging.AddConfiguration` but the work I will be doing in #20231.
