### ISSUE TITLE
[Hosting] Events UnhandledException and RequestFailed not raised

### ISSUE THREAD

**Issue by joacar** [dotnet/aspnetcore#19738]
### Describe the bug

The events `RequestStart` and `RequestStop` is raised from Microsoft.AspNetCore.Hosting namespace. But those for unhandled exception (`UnhandledException`) and failed requests (`RequestFailed `) aren't. 

I've checked [here](https://github.com/dotnet/aspnetcore/blob/7cf264f25ae77d9a6b235a85c66dc13835e5b398/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L124), [here](https://github.com/dotnet/aspnetcore/blob/7cf264f25ae77d9a6b235a85c66dc13835e5b398/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L146) and [here](https://github.com/dotnet/aspnetcore/blob/7cf264f25ae77d9a6b235a85c66dc13835e5b398/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L152) and can't understand what I need to enable for those to get raised.

Listening to `Microsoft-Diagnostics-DiagnosticSource` I can get these events successfully. Example
```c#
if (eventData.EventName.Equals("Event", StringComparison.InvariantCulture))
{
    // Comes from Microsoft-Diagnostics-DiagnosticSource
    if (eventData.Payload.Count > 1 && ((string)eventData.Payload[1])
        .Equals("Microsoft.AspNetCore.Diagnostics.UnhandledException", StringComparison.InvariantCulture))
    {
        // Keywords = 263882790666242
        _failedRequestReporter.Create().Inc();
     }
}
```
Those are in the namespace `Microsoft.AspNetCore.Diagnostics` and maybe I'm better of with them? That would perhaps allow me to track requests per second as well since I've seen the timestamp in some stop-event.

### To Reproduce

[WebApplication2.zip](https://github.com/dotnet/aspnetcore/files/4312061/WebApplication2.zip)

### Further technical details
- ASP.NET Core 3.1.1
- `dotnet --version`
`3.1.101`
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
Microsoft Visual Studio Professional 2019
Version 16.4.5
```

**Comment by shirhatti** [comment]
@joacar I took a quick look at your project and I think I understand your source of confusion. `EventSource` != `DiagnosticSource`.

You will need to create a [`DiagnosticListener`](https://docs.microsoft.com/dotnet/api/system.diagnostics.diagnosticlistener) to subscribe to a `DiagnosticSource`. See this document for more information- https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md

**Comment by shirhatti** [comment]
See the Application Insights SDK for an example on how to consume the DiagnosticSource from Hosting- https://github.com/microsoft/ApplicationInsights-dotnet/blob/7116e54f5d16c519a39a96dd2510c39b90fa9c4d/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs#L443
