### ISSUE TITLE
DataAnnotations on one property will call get method on all other properties and subclass's properties

### ISSUE THREAD

**Issue by liuliang-wt** [dotnet/aspnetcore#19734]
When I post a ModelA to controller, if I add a DataAnnotations like [Required],[StringLength] on one property in ModelA, all other properties' Get method will be called, and if this ModelA derived from ModelB and ModelB has one property which has DataAnnotion, all properties' Get method of ModelA will be called....

**Comment by pranavkm** [comment]
@liuliang-wt would you mind sharing a minimal app that demonstrates the issue? It's not very clear from the description what the issue is.

**Comment by liuliang-wt** [comment]
@pranavkm thank you for your reply,

[WebApplication6.zip](https://github.com/dotnet/aspnetcore/files/4315814/WebApplication6.zip)

the attachment is a miminal asp.net core mvc project, the controller is like this:

  public IActionResult Index()
        {
            ModelA a = new ModelA();
            return View(a);
        }

        [HttpPost]
        public IActionResult Index(ModelA modela)
        {
            return View(modela);
        }

ModelA is a subclass of ModelB,  when post to Index, all ModelA's properties' Get method will be called, only because I add a [Required()] attribute to a ModelB property

![result is this](https://user-images.githubusercontent.com/15852860/76378374-37bc2280-6388-11ea-9525-87d51ada07ce.png)

**Comment by pranavkm** [comment]
@liuliang-wt this makes sense. MVC's validation will visit an object as long as there's at least one property that needs validated. Validation short-circuits if no properties in a model or any of it's sub-properties require validation. Our recommendation would be to use view models \ POCO objects for the types you use for binding. This should ensure there isn't a cost to property accessors.

**Comment by liuliang-wt** [comment]
well... it makes sense that MVC go through every properties to check if there is a validation attribute, but it doesn't make sense to call Get method for those properties that don't have validation attribute.

You can use reflection to check if there is an attribute on a property before calling its' Get method right?
