### ISSUE TITLE
ExceptionHandlerMiddleware should allow more customizabiltiy of logging

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#19740]
I want to use `ExceptionHandlerMiddleware` (via `UseExceptionHandler`) for my exception handling.  Whilst it allows me to run custom code when generating the HTTP response, there appears to be no customizability when it comes to logging:

https://github.com/dotnet/aspnetcore/blob/5e575a3e64254932c1fd4937041a4e7426afcde4/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L92

The middleware always logs "An unhandled exception has occurred while executing the request." with the exception.  I think there should at least be an option I can pass in to prevent this middleware logging anything, so I can output my own logging (I wish to log the `Path` too, obtained from `IExceptionHandlerPathFeature`), and maybe an option to get `ExceptionHandlerMiddleware` to log the `Path` itself.

**Comment by davidfowl** [comment]
Seems reasonable as an option to disable logging.

**Comment by rynowak** [comment]
Isn't this already possible via config?

**Comment by davidfowl** [comment]
Yes it is! @jez9999 you can add this to configuration to disable the logging for this:

```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware": "None"
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by jez9999** [comment]
@davidfowl A couple of things: while that'll work with .NET Core's default logging architecture, "None" might not be an option for all logging frameworks.  I don't think Serilog has that option, for example.  Also, it just looks rather unintuative semantically, because it kind of looks like you're trying to configure your app NOT to log unhandled exceptions.

**Comment by davidfowl** [comment]
> @davidfowl A couple of things: while that'll work with .NET Core's default logging architecture, "None" might not be an option for all logging frameworks.

2 things:
- Logging filtering is handled by the factory by default, so if you use *any* logging provider it will work. 
- Serilog happens to implement an entire ILoggerFactory and there's a serilog specific way to disable categories.

> Also, it just looks rather unintuative semantically, because it kind of looks like you're trying to configure your app NOT to log unhandled exceptions.

I agree it's not as intuitive as an option on the middleware itself but I disagree it not telling your app the log exceptions. The logging category is clearly scoped to the middleware which makes it specific.

The fact that there is a way to do this today makes this a low priority but if you want to send a pull request with a new set of options that apply to this middleware I would happily review it.

**Comment by jez9999** [comment]
>     * Logging filtering is handled by the factory by default, so if you use _any_ logging provider it will work.

Doesn't seem to be working for me.  The following isn't suppressing the exception handler middleware logs:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging => {
                    logging.ClearProviders();
                    logging.AddFilter("Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware", LogLevel.None);
                    logging.AddSerilog();
                })
                .ConfigureWebHostDefaults(webBuilder => {
                    webBuilder
                        // Serilog for logging
                        .UseSerilog((context, config) => {
                            config.ReadFrom.Configuration(context.Configuration);
                        })

                        // Startup type used by web host
                        .UseStartup<WebStartup>();
                });
```

**Comment by jez9999** [comment]
I've just been reading: https://github.com/serilog/serilog-extensions-logging/issues/98

Interestinly you yourself seem to be saying that `UseSerilog` is breaking things in ASP.NET Core, @davidfowl .  It overrides ASP.NET's filtering and throws everything over to Serilog, which provides an inferior filtering experience:
https://github.com/serilog/serilog-extensions-logging/blob/c5bad0c183ae10d448fcc3532095e298d57906a1/src/Serilog.Extensions.Logging/SerilogLoggingBuilderExtensions.cs#L49

Seems like they've made some rather crap decisions about integrating with .NET Core.  I'm gonna have to review whether I wanna use Serilog.

**Comment by jez9999** [comment]
Anyhow, it'd still be good if the exception handling middleware could take a config that made it not log anything.

**Comment by nblumhardt** [comment]
Just in case anyone else is following along and wondering how Serilog handles filtering, see https://github.com/serilog/serilog-filters-expressions#serilogfiltersexpressions-- (and of course the logger-specific level overrides enabled by `MinimumLevel.Override()`).

In Serilog configuration, if level overrides and the `Fatal` level are insufficient to suppress these messages, it's always possible to specify `SourceContext <> 'Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware'` as a filter.

**Comment by jez9999** [comment]
Filtering them out is what I ended up doing.

**Comment by Tratcher** [comment]
Resolved via filtering.
