### ISSUE TITLE
JsonException after upgraded to Blazor WebAssembly 3.2.0 Preview 2

### ISSUE THREAD

**Issue by Berrysoft** [dotnet/aspnetcore#19758]
### Describe the bug
Error messages show in the console of the browser after using `JsonSerializer` or `GetJsonAsync`:
```
Error: System.Text.Json.JsonException: Invalid JSON
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS (Microsoft.JSInterop.JSRuntime jsRuntime, System.String arguments) <0x2d62f10 + 0x000fc> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.EndInvokeJS (System.String argsJson) <0x2d5bdd8 + 0x0000a> in <filename unknown>:0 
```

### To Reproduce
Add a json file to the project and use `GetJsonAsync` extension method to get it.

### Further technical details
```
PS> dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.200-preview-015002
 Commit:    b3dae24c3b

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-015002\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@Berrysoft thanks for contacting us.

I would suggest you clean your bin,obj folder and rebuild just in case there's some intemerdiate/invalid state after the update.

Some other things to try I described [here](https://gist.github.com/javiercn/d6b7e6b498f40aa1d05436a8a19b60f4) beware that many of these have an impact on your whole machine/dotnet install but are the best way to make sure there's nothing impacting it.

If that doesn't work, could you provide a minimal repro project that showcases the issue?

**Comment by Berrysoft** [comment]
My fault. I'm still using classes from old namespaces, and because I'm referencing some old libraries targeting old Blazor assemblies, the compiler doesn't error at all. Now the question is solved.

**Comment by NPadrutt** [comment]
@Berrysoft You saied the compiler didn't call out the wrong referneces. Did you do anything special to find them? 
I have the same problem. But I can't find any old namespaces and I only have the new packages references as far as I can tell. Also deleted bin and obj already.

**Comment by NPadrutt** [comment]
okey, nevermind I found it. I use the library **Toolbelt.Blazor.TimeZoneKit** and version 6.0 uses `Microsoft.AspNetCore.Blazor`. Therefore I used the wrong `WebAssemblyHostBuilder` in my Program.cs. After the upgrade to 7.0 it works as expected.
