### ISSUE TITLE
Bring back possibility to dynamically add blazor wasm apps to aspnet core

### ISSUE THREAD

**Issue by eisendle** [dotnet/aspnetcore#19759]
In Blazor WASM Preview 1 it was possible to dynamically register a Blazor App via ` endpoints.MapFallbackToClientSideBlazor<Client.Program>()`. This API was removed in Preview 2 and replaced with integration of "ASP.NET Core static web assets".

This change removed the possibility:

1. To register Blazor apps to ASP.NET Core at runtime. No project reference was required.
2. To map multiple Blazor apps to different routes (Not sure about that, there is no documentation about that)

To illustrate the scenario I'm trying to achieve:

- Host BlazorApp1 on /ui/App1
- Host BlazorApp2 on /ui/App2

This was possible in Preview 1:
```csharp
 _applicationBuilder.Map("/ui/App1", app => 
{
    app.UseClientSideBlazorFiles<BlazorApp1>();
    app.UseEndpoints(endpoints =>
    {
      endpoints.MapFallbackToClientSideBlazor<BlazorApp1>("index.html");
    });
}

 _applicationBuilder.Map("/ui/App2", app => 
{
    app.UseClientSideBlazorFiles<BlazorApp2>();
    app.UseEndpoints(endpoints =>
    {
      endpoints.MapFallbackToClientSideBlazor<BlazorApp2>("index.html");
    });
}
```
This seems not possible to do in Preview 2.

The above mentioned removed API should be added back or an alternative way should be provided.

Is this related to #19060 ?

**Comment by javiercn** [comment]
@eisendle thanks for contacting us.

This is still possible in preview2. Apps are mapped to '/' by default but you can change `StaticWebAssetBasePath` on the msbuild project for the app to map it to a different location, like `ui/app1` and then you can do as you were doing before:

```csharp
_applicationBuilder.Map("/ui/App1", app => 
{
    app.UseBlazorFrameworkFiles();
    app.UseEndpoints(endpoints =>
    {
      endpoints.MapFallbackToFile("index.html");
    });
}
```

**Comment by eisendle** [comment]
The above mentioned code snippet doesn't work. After a lot of tinkering this works partially for me:
```csharp
_applicationBuilder.UseStaticFiles();
_applicationBuilder.UseBlazorFrameworkFiles("/ui/App1");
```

However the fallback for "/ui/App1" to index.html isn't working.
Using the default Blazor WASM template I've tried multiple things:

```csharp
_applicationBuilder.Map("/blazor/app", x => 
{
    x.UseRouting();
    x.UseEndpoints(endpoints =>
    {
        endpoints.MapFallbackToFile("index.html");
    });
});
```
```csharp
_applicationBuilder.Map("/blazor/app", x => 
{
    x.UseRouting();
    x.UseEndpoints(endpoints =>
    {
        endpoints.MapFallbackToFile("/blazor/app/index.html");
    });
});
```

```csharp
_applicationBuilder.UseEndpoints(endpoints =>
{
        endpoints.MapFallbackToFile("/blazor/app/index.html");
});
```

None of the above mentioned attempts does the trick, maybe I'm missing something


From a documentation point of view, there should be an example in the docs which shows how to host a Blazor WASM app on a non root location.

**Comment by luposky** [comment]
yes, it's a way too complex to guess the appropriate configuration without any docs or example ...

here it is my working solution: https://github.com/luposky/TestBlazorPath

it's the basic example from wasm template with these modifications:
https://github.com/luposky/TestBlazorPath/commit/6e01f2dbea3955789f24c44fb55e9c78783e6b87

please review and share if it working in your scenario (you need to add "/portal" manually on the address bar) ...

**Comment by eisendle** [comment]
@luposky 

Thanks, it's now working for my scenario too. Problem was the leading slash in variant two in my above comment.
