### ISSUE TITLE
Blazor Wasm: caching localhost bleeds between projects

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#19765]
### Describe the bug

With 3.2.0-preview2, assets are cached for localhost websites.  This means that `ProjectA` that runs at `localhost:5001` can end up trying to use DLLs from `ProjectB` that runs at the same host.  Add linking to the mix and you can see where problems start to arise.

Context: my previous runtime bug (https://github.com/dotnet/aspnetcore/issues/19762) was due to linking being enabled.  I discovered that the same bug would then appear in a fresh Blazor templated project. This was the result of the subject of this issue.

I love the caching, but it seems like we may need another component for the cache key?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We actually cache based on unique hashes, so that shouldn't be a problem. Can you please provide us with a small repro project so that we can investigate this? Thanks!

**Comment by zbecknell** [comment]
This one is tough because it involved both linking and various misconfigurations with the original large app, but it definitely resulted in the new templated app having the same error.  That being said, a couple of simple repro projects couldn't replicated it, and hopefully if something is there it'll be enough of a corner case that it never really crops up.

I'm going to close this for now.
