### ISSUE TITLE
Inconsistent status code when file upload is forbidden, depending on the input file size

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/aspnetcore#19766]
### Describe the bug
When I don't have the permission to upload a file in an API, I expect to receive a 403.
On that specific API, I have set `[RequestSizeLimit(2_000_000_000)]`, to be allowed to upload big files through the API.
If I upload a file bigger than the default size limit, I get a "Bad request" instead of the 403 I was expecting.

### To Reproduce
Here is a repro : https://github.com/jeremyVignelles/TestUploadForbidden

Run unit tests. The result should not depend on the file size.

I originally wrote that JwtBearer authentication scheme was consistent, but it seems to be consistent only in my browser, the unit tests give the same result.

### Further technical details
ASP.NET Core version 3.1.1

VS 2019 16.4.4

dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
> If I upload a file bigger than the default size limit, I get a "Bad request" instead of the 403 I was expecting.

The server blocks request if it exceeds specified limits, returning a 400. The action does not execute in this event.

/cc @Tratcher

**Comment by jeremyVignelles** [comment]
As you can see here, the forbidden message is returned from within the action:

https://github.com/jeremyVignelles/TestUploadForbidden/blob/master/TestUploadForbidden/Controllers/HomeController.cs#L16-L21

So, I'd expect that the RequestSizeLimit is properly interpreted.

**Comment by Tratcher** [comment]
Are you using IIS? IIS has a global limit you need to change in the web.config.
https://docs.microsoft.com/en-us/iis/configuration/system.webServer/security/requestFiltering/requestLimits/#configuration

**Comment by jeremyVignelles** [comment]
No, I'm using kestrel. The method executes fine if there is no 403

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by jeremyVignelles** [comment]
Hi, does that mean that this will never be looked into and that I need to live with dirty hacks on the client size?

I thought the investigate label was set while waiting for someone to confirm this is a bug or not.

For me this is a bug in that the behavior is not expected : If I raise the limit, I'd expect every upload below that limit to behave the same, no matter what the original limit was.

I agree this is a corner case, but don't you think this is worth letting open for later, if someone has the same issue?
