### ISSUE TITLE
Claim Empty when it is deployed in IIS

### ISSUE THREAD

**Issue by Justina2711** [dotnet/aspnetcore#19760]
We have created a demo .Net Core version 2.2 application, and we are storing user related data in the claims, everything works fine in the development mode, whenever we deployed the same on IIS windows server 2019, after some time we are trying to retrieve the claim it becomes empty, whereas the AspNetCore.Cookies value is present in the browser cookie

![image](https://user-images.githubusercontent.com/48353468/76395223-d3f02480-639c-11ea-9213-f9637f4b531b.png)

![image](https://user-images.githubusercontent.com/48353468/76395239-df435000-639c-11ea-8d0f-54f2bbec7021.png)

![image](https://user-images.githubusercontent.com/48353468/76395252-e66a5e00-639c-11ea-9baf-dcf02e75c769.png)

**Comment by javiercn** [comment]
@Justina2711 thanks for contacting us.

.ASP.NET Core 2.2 is out of support as per https://dotnet.microsoft.com/download/dotnet-core, so we recommend you upgrade to the next LTS release (3.1) and try to see if the issue you are having reproduces there.

**Comment by Justina2711** [comment]
@javiercn The same issue is faced in .Net Core 2.1 also

**Comment by jkotalik** [comment]
@Tratcher / @HaoK  any ideas?

For more diagnostics, can you post what your deployed web.config is?

**Comment by Justina2711** [comment]
@jkotalik thank you for your reply

we have two projects running on 2 different version .Net core 2.1 and 2.2

**web.config for version 2.2**
![image](https://user-images.githubusercontent.com/48353468/76486521-9398b100-6445-11ea-8ebe-b9d8f0f0e4e0.png)

**web.config for version 2.1**
![image](https://user-images.githubusercontent.com/48353468/76486580-bfb43200-6445-11ea-9dbf-bb3bc4555c76.png)

**Comment by Justina2711** [comment]
@javiercn We have tried to upgrade our solution from 2.2 to 3.1 still the claim values are becoming empty when it is deployed to IIS after a period of time.

**Comment by HaoK** [comment]
What do you mean after a period of time?  Are you saying its there initially but only later the claim is gone?

**Comment by Justina2711** [comment]
@HaoK thank you for your reply
 Yes, initially we are able to get the claim value but after some time we are trying to retrieve the same it became empty whereas the AspNetCore.Cookies value is present in the browser's cookie, kindly find the screenshot 

![image](https://user-images.githubusercontent.com/48353468/76674973-e8b9fb80-65da-11ea-957c-0fcd31d122de.png)

**Comment by Justina2711** [comment]
We were tried to upload the solution on our local pc's IIS (Windows 10) everything is working fine as expected, but whenever the same solution is hosted on the AWS server(Windows Server 2019) the issue still remains to continue

**Comment by Tratcher** [comment]
The next step would be sharing a decrypted Fiddler trace file showing the repro scenario, as well as application debug level logs for the same time period.

**Comment by Justina2711** [comment]
Thanks to all who helped us to overcome this problem.

We have managed to resolved it as there was a improper setting in the IIS, we manged to correct the same, the application is working fine as expected
