### ISSUE TITLE
[Blazor] Code completion is incomplete + poorly formatted

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#19761]
[Screenshot](https://blazor-university.com/wp-content/uploads/2020/03/ezgif-1-e5a7f68eb671.gif)

In an `@code` section type `override oninit` - when the code-insight window pops open showing `OnInitialized` press Enter.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen this seems to be a known issue.

**Comment by NTaylorMullen** [comment]
Ya we thought we fixed this for the current editor with projections but turns out maybe we didn't? @mrpmorris what VS version are you seeing this on?

**Comment by mrpmorris** [comment]
This is what it does in 16.5.0 Preview 5.0.

It pushes the code up to the previous line and does not include the `protected` keyword.

[Screen capture](https://blazor-university.com/wp-content/uploads/2020/03/ezgif-1-8f0bd6150da2.gif)

**Comment by NTaylorMullen** [comment]
@jasonmalinowski you guys did work to fix this on our behalf from the C# projection front. Did something recently change to break this again?

**Comment by NTaylorMullen** [comment]
Closing in favor of https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1130980
