### ISSUE TITLE
[Blazor 3.2.0 preview 2] [Deployment] The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found. 

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#19768]
Hello Guys, this morning i made the migration of my app to web assembly 3.2.0 preview2.
On development, not particular problems, it works as expected.
But now, when i deploy to my preprod server, i have the error "The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found"

By activating debuginformation in web.config, i had the real reason of the "error"

An assembly specified in the application dependencies manifest (Is.Geckos.Blazor.Server.deps.json) was not found: package: 'xxx', version: y.y.y' path: 'lib/netstandard2.1/xxx.dll'

Important information to understand whats happen, my app actually work as well as server and client side. The .net core server reference a .net standard project (the client) which contains all the webapp and configure it in startup as webassembly or server side depending of a parameter in the appsettings.json.

Th result of this was (on the previous version), for all package references by the client, the same dll which was at the same time in the .net core project (\publish) and on the client project (\publish\wwwroot\_framework\_bin) (which was also a problem, but was working)

Now, it seem with the last preview when i publish, all the package reference by the client project are not reference by the server project (the dll are not copied under the /publish directory, they are only in \publish\wwwroot\_framework\_bin). 

even If a try to reference directy the nuget package in the server project, it seem not publish under the \publish directory (because the dll exist under the client ?)

So i finally be able to make my deployment works by copying manually all the dll existing in \publish\wwwroot\_framework\_bin to \publish. 

Lot of question  after this :
- i began to make my app working as well in client/server mode when DanielRoth publish BlazorDualMode (https://github.com/danroth27/BlazorDualMode). Im still not sure it's the good way to make this, but i don't find other options or examples on internet to achieve this. Somebody have a similar configuration and find a better way to do this ? I was thinking made all my app a blazor library, and have two server projet ClientSide and ServerSide, which will be empty shell which will reference the library, But it seem the blazor library can't contain page which is a problem. 
- To resolve the dll problem, i was thinking deploy all my dll (client and server project) in a particular directory of my server and say to the the app (the server one and the client one) to resolve her dependencies in this particular directory. By this way, i solve also the problem of the same dll in multiple location, which can be really heavy for no particular reason. But I don't know how i can do that in .net core. In asp .net, i was doing this in global.asax (which was working great, but if there is easier solution, like put the path of the directory in a config file and let the app load the dll from there, it would be better ! ). 

````
AppDomain lCurrentDomain =  AppDomain.CurrentDomain;
            lCurrentDomain.AssemblyResolve += new ResolveEventHandler(AssembliesResolveEventHandler);

 private Assembly    AssembliesResolveEventHandler(object sender, ResolveEventArgs args)
        {
            //This handler is called only when the common language runtime tries to bind to the assembly and fails.        
            string lDllFolder = AssembliesFolder;

            int lIndex = args.Name.IndexOf(",");
            if (lIndex != -1)
            {
                string lDllName = args.Name.Substring(0, lIndex);
                //-- tentative ignorer les .resources...finallement abandonné
                bool IsRessourceDll = (lDllName.EndsWith(".resources", StringComparison.OrdinalIgnoreCase) || lDllName.EndsWith(".XmlSerializers", StringComparison.OrdinalIgnoreCase));
                //if (lDllName.EndsWith(".resources") && !lDllFields[2].EndsWith("neutral")) return null;

                //-- si dj ddée & pas trv : rien de plus à faire
                if (_inexDllS.Contains(lDllName)) return null;

                string lDllFull = Path.Combine(lDllFolder, lDllName + ".DLL");

                //-- vérifie si dj traitée : si oui évite de revérifier sur le disque
                bool lExistsInDllFolder = _resolvedDllS.Contains(lDllName);
                if (!lExistsInDllFolder)
                {
                    //-- ddée pour la 1ère fois : si présente ds dossier Assemblies : ok, sinon null
                    if (File.Exists(lDllFull))
                    {
                        if (_resolvedDllS.Add(lDllName)) WriteLogDebug(lDllName, "Loaded"); 
                        lExistsInDllFolder = true;
                    }
                }
                if (lExistsInDllFolder) return Assembly.LoadFrom(lDllFull);

                //-- ecrit / Log uniq. si add ok (ss doublons) car Ev. arrivent souvent en meme temps pour la meme dll
                if (_inexDllS.Add(lDllName) && !IsRessourceDll) WriteLogDebug(lDllName, "Inex"); 
            }
            return null;
        }

````

Thank you very much for your help !

Julien

**Comment by zbecknell** [comment]
Without digging into the details, you may want to try disabling linking entirely by putting in your csproj:

```xml
<PropertyGroup>
   <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
</PropertyGroup>
```

My app is broken with linking enabled, and it IS automatically enabled for RELEASE builds, so try this out.

**Comment by julienGrd** [comment]
hello @zbecknell , thanks for your help ! My app had already the linker disable (because of Linq.Dynamic.Core), nothing related in this case !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like that your pre-production environment is missing the correct runtime. As is pointed out in the [release blog post](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/), you will need to have 3.1.2 version of the ASP.NET Core runtime.
Can you please confirm you have it installed?

**Comment by julienGrd** [comment]
Yes I can confirm, deploy an empty server side or client side project on my server works perfectly, its really my project with this specific dual-mode configuration which have problems.

 To understand whats really happen you need read the message entirely (yes i know its really long ^^). It's related to the way the publish deal with dll. In my case, the server app don't have some dll (dll used in the webapp but need to be in the server project in order to the server side work) because i think the publish already copy them in the client project, so he certainly skip it, but in my case both projects need client dll.

**Comment by mkArtakMSFT** [comment]
While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by julienGrd** [comment]
Oh yes sure, i just pointed out that in a particular case the server project is published with missing dll (the dll that are already included in the client project, in the previous version all the dll was both copied in the server and client project).

For my two others questions i will open others issues here, i think its someting expected by the community and its advanced/specific scenario : the good way to make a dual/multi mode project, and the abality to configure publish to load dll from another place than the root folder.

**Comment by julienGrd** [comment]
important thing : the dll are not copied **only** if BlazorWebAssemblyEnableLinking is set to false, otherwise everything works greate.

**Comment by kant2002** [comment]
I can confirm that issue happens on Blazor Preview 2 and 3.1.2 SDK . I create repro care in #19799 but initially I have this issue. Library which was not copied in my case was Microsoft.AspNetCore.Components.WebAssembly

**Comment by mattgenious** [comment]
I am running a blazor wasm project hosted by an asp net core application on AWS Elastic Beanstalk and as such I was relying on the self-contained publish using a runtime identifier on the preview 1, this no longer works and returns the following:
```
 HTTP Error 500.31 - ANCM Failed to Find Native Dependencies
Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found. 
```
This error only presents itself when the .server project references the .client project, if I remove that the asp net core application starts without problems and runs the controller methods correctly.
As soon as the client is referenced the application breaks.

**Comment by spmoran-blazor** [comment]
I have this same issue with Preview 3.

**Comment by mattgenious** [comment]
Agreed.
If you don't already know, you should be able to mitigate it by publishing to release with linker enabled.

**Comment by pranavkm** [comment]
> An assembly specified in the application dependencies manifest (Is.Geckos.Blazor.Server.deps.json) was not found: package: 'xxx', version: y.y.y' path: 'lib/netstandard2.1/xxx.dll'

We fixed this as part of our preview4 release which released today: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available. Can you try updating your applications, we think this should no longer be an issue.
