### ISSUE TITLE
Using custom FileProvider increase response time 3-6 times

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19773]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/942180/using-custom-fileprovider-increase-response-time-3.html)._

---
To be able to load a view from a database, I found [this article][1] (with a [complete code sample][2] at Github), how to create a custom database file provider.

As I use ASP.NET Core 3.1, these adjustment were needed:

In the `Startup` class

services. AddRazorPages()
        . AddRazorRuntimeCompilation(opt => {
            opt. FileProviders.Add(new DatabaseFileProvider(Configuration["MyAppSettings:SQLConnectionString"]));
        })

In the `GetDirectoryContents` method

public IDirectoryContents GetDirectoryContents(string subpath)
    {
        //throw new NotImplementedException();
        return new NotFoundDirectoryContents();
    }

_In the linked sample code, their weren't provided an implementation for the `GetDirectoryContents` method as it appeared not be needed for its use-case. I guess it worked "as-is" in earlier versions of ASP.NET Core, but not in 3.1, where the methods get called and render an exception, so I decided to simply temporarily just return a `NotFoundDirectoryContents` to get pass the exception._

---

By just adding the file provider to my project (not call any view), the response time for my default page increased 3-3.5 times (from ~40-50ms to ~120-140ms).

And when I added a custom component to the very same default page, which loads a view from the database, the response time increased 5-6 times (from ~40-50ms to ~-230-250ms).

@await Component.InvokeAsync("TextImg", new { cityName = "Oslo", viewName = "Test" })

---

Is this expected when using a custom file provider?

If not, what is wrong here.

---

___Please note, given the view gets cached, the above response time doesn't include reading the database.___

[1]: https://www.mikesdotnetting.com/article/301/loading-asp-net-core-mvc-views-from-a-database-or-other-location
  [2]: https://github.com/mikebrind/RazorEngineViewOptionsFileProviders

---
#### Visual Studio Feedback System on 3/8/2020, 11:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It sounds like your file provider is slow and that's what contributes to the overall slowness you see. We recommend profiling it yourself, as it's not a framework -specific code. If however, you've done that and still believe there is something wrong going on in the framework, please provide us with a minimal repro project and your profiling data, so that we can investigate this further.

**Comment by perason** [comment]
I will provide a minimal repro, though when it comes to profiling, as you can read in another issue I posted, [profiler-application-timeline](https://developercommunity.visualstudio.com/content/problem/942191/performance-profiler-application-timeline-and-inst.html), I can't produce any such data.

Do you have a fix for that?

**Comment by mkArtakMSFT** [comment]
Thanks @perason. We will wait for the actual repro from you. For the other issue related to the profiling, VS feedback is the right place for it as we don't own it.
