### ISSUE TITLE
Best Practice for Dynamic ClientId and ClientSecrets in the AddOpenIdConnect 

### ISSUE THREAD

**Issue by aeos** [dotnet/aspnetcore#19778]
Our application is multi-tenanted and each tenant has a unique clientId and client secret. Currently the only way to change the clientId and secret is to do so during all of the OpenIdConnectEvents such as OnRedirectToIdentityProvider

For OnRedirectToIdentityProvider the strategy is to update the RedirectContext.ProtocolMessage.ClientId and ClientSecret before the request triggers, however in this specific case doing so leaks your client secret because it is added to the request query parameters, which you must then remove.

Is there an alternative path, or could there be an improvement with an event that allows you to configure the options on each request before the middleware does any processing?

**Comment by Tratcher** [comment]
The ODIC auth handler does not support dynamic multi-tenant scenarios and we have no plans to add that in the near term, the requirements are too diverse and complex. The closest approximation is to add a separate auth handler instance per tenant, but that has scale limits. 

The recommended alternative is to use a framework like Orchard that's designed for full multi-tenancy.
