### ISSUE TITLE
Blazor InputSelect Errors with "multiple" attribute

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#19776]
### Describe the bug
When adding `multiple` to an `InputSelect` input component, running the app, and selecting an item, an error occurs and is displayed in the browser console.

Is `multiple` supported?

### To Reproduce

Search.razor
``` HTML
<InputSelect class="custom-select" @bind-Value="_myModel.SelectedNumbers" id="numbers" multiple>
	<option value="">Select number ...</option>
	<option value="1">One</option>
	<option value="2">Two</option>
</InputSelect>
```

Search.razor.cs
``` C#
public IEnumerable<string> UnitIds { get; set; }
```

Error

> Error: System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputSelect`1[System.Collections.Generic.IEnumerable`1[System.String]] does not support the type 'System.Collections.Generic.IEnumerable`1[System.String]'.
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.TryParseValueFromString(String value, TValue& result, String& validationErrorMessage)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1.set_CurrentValueAsString(String value)
   at Microsoft.AspNetCore.Components.Forms.InputSelect`1.<BuildRenderTree>b__4_0(String __value)
   at Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.<>c__DisplayClass22_0`1.<CreateBinderCore>b__0(ChangeEventArgs e)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

### Further technical details
- ASP.NET Core version: 3.1.2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Mac 8.5 Preview (8.5 build 3129)
- $ dotnet --info

> .NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

> Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

> Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

> .NET Core SDKs installed:
  3.1.102 [/usr/local/share/dotnet/sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by SteveSandersonMS** [comment]
It's not currently supported. This is tracked by https://github.com/dotnet/aspnetcore/issues/5519, so closing as duplicate.

**Comment by mrlife** [comment]
@SteveSandersonMS I understand. The https://github.com/dotnet/aspnetcore/issues/5519 hasn't been updated with a status for almost 2 years. Possible to provide an update there?

**Comment by mrlife** [comment]
@SteveSandersonMS I see, thank you. The https://github.com/dotnet/aspnetcore/issues/5519 hasn't been updated with a status for almost 2 years. Possible to provide an update there?
