### ISSUE TITLE
The target process exited with code 0 while evaluating the function

### ISSUE THREAD

**Issue by zmp2000** [dotnet/aspnetcore#19777]
Hi, I have a asp.net core project which references another .net standard project which acts as a repository for retrieving database information.
This repository uses NHibernate ORM and PostgreSQL connection.

The project works fine except when I try to debug any retrieved information from the Repository, the objects are lazyloaded as proxy objects just like Entity Framework does.

So when the debugger tries to evaluate the object it throws the message 
The target process exited with code 0 while evaluating the function 'EmpresaObjProxy.get_Informacao'
[27373] quemmeatende.ui.dll' has exited with code 0 (0x0).

This problem is only occurring on Linux with VS Code
I'v tested it under linux on both Vs Code and Visual Studio Comunity and both works fine.

Here my dotnet --info output:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.3
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.803 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.102 [/usr/share/dotnet/sdk]
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

So how can I provide more information on why the process is exiting? Because code 0 means no errors

**Comment by Pilchie** [comment]
@gregg-miskelly any ideas?  What's the best way to report this?

**Comment by gregg-miskelly** [comment]
Unfortunately the debugger doesn't know the real exit code on Linux/Mac, so ignore that part of the message.

Can someone move the issue to https://github.com/omnisharp/omnisharp-vscode? I am on parental leave right now, but hopefully someone can try to help you understand what is going on.

**Comment by Pilchie** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#3655
