### ISSUE TITLE
Blazor server through web proxy

### ISSUE THREAD

**Issue by isvander** [dotnet/aspnetcore#19793]
Dear NetCore Team,
got an error on blazor server version when connection through web proxy/vpn, 
my guess is there's an issue with Blazor when handling SignalR and/or my web proxy configuration

here's error log generated from console log:

blazor.server.js:1 Uncaught (in promise) TypeError: Cannot read property 'writeMessage' of undefined
    at new e (blazor.server.js:1)
    at Function.e.create (blazor.server.js:1)
    at e.build (blazor.server.js:1)
    at blazor.server.js:8
    at blazor.server.js:8
    at Object.next (blazor.server.js:8)
    at blazor.server.js:8
    at new Promise (<anonymous>)
    at r (blazor.server.js:8)
    at S (blazor.server.js:8)

and here's snippet from 
blazor.server.js:1(first line error):

this.cachedPingMessage=fgt_sslvpn.protocol_restore(this).writeMessage({type:o.Ping})}return e.create

Thank you

**Comment by javiercn** [comment]
@isvander thanks for contacting us.

@anurse this seems to be a question specific to signalr ultimately, do you have any ideas/thoughts on what to ask/try here?

**Comment by anurse** [comment]
> blazor.server.js:1 Uncaught (in promise) TypeError: Cannot read property 'writeMessage' of undefined

I'm not clear where this relates to SignalR. Certainly there *can* be considerations to make when running SignalR behind a proxy but I would expect network errors, not JavaScript syntax/semantic errors.

**Comment by BrennanConroy** [comment]
> not JavaScript syntax/semantic errors

This isn't a syntax error. That's a runtime error.

I would guess that either @isvander has misconfigured their app to somehow overwrite the protocol being used with some odd `fgt_sslvpn` type, or they are bringing in a module that's overwriting global properties.

We would need a sample app to see what is going on.

**Comment by isvander** [comment]
thanks everyone and @BrennanConroy for heads up , actually i'm ask here to find some clue whats happen is going on too, i'll be be back and open issue with more information later then
