### ISSUE TITLE
Git's CRLF transformations interfere with content hashes

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19796]
Originally reported as https://github.com/dotnet/aspnetcore/issues/19775, but the issue is slightly more general than that so I'll rephrase it.

**Problem**: If you use Git [1] as a way of transferring build output to your production server, and the production server has different newline conventions from the build server [2], then content hashes in text files (such as `blazor.webassembly.*.js`) will not match and the application will not load.

[1] i.e., the source control technology, not necessarily GitHub. So this applies to Kudu too.
[2] e.g., build machine is Windows and production server is Linux, or vice-versa

This happens because by default [Git performs automatic CRLF conversions on commit](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings).

Strictly speaking this issue is not specific to Blazor, but would apply to any web technology that computes subresource integrity hashes during build. However it's a bigger issue for Blazor because (1) we're now computing subresource integrity hashes during build by default, and (2) an unusually large proportion of Blazor developers use Windows.

## Possible solutions

People have two main ways to avoid this problem. They can use `<BlazorCacheBootResources>false</BlazorCacheBootResources>` to disable the caching-and-integrity-checking feature entirely, or they can put a `.gitattributes` file in their repo specifying `autocrlf=false`.

The question is: how are we going to help people with this?

### 1. Docs only

We could add documentation to the deployment pages giving advice about git-based deployment mechanisms, especially highlighting that this affects GitHub Pages.

We would advise people to add a `.gitattributes` file to their repo specifying `autocrlf=false` (at least in the subdirectory representing their GitHub Pages content, i.e., the published output).

### 2. Auto-generate a `.gitattributes` file

On publish, we could place the relevant `.gitattributes` file in the output.

It sucks pretty bad for us to couple aspects of our build pipeline to a particular source control system, even if it is the de-facto industry standard. We don't know whether the customer is planning to use Git as a deployment mechanism, so we don't know whether the `.gitattributes` file is really relevant.

We could:

 * [A] Just do it all the time regardless, reasoning that it's not harmful in the cases where it's not needed. Possibly with an MSBuild option to disable this for people who care.
    * Pro: just works
    * Con: clumsy
 * [B] Or, do that but with the default being "off", so people have to explicitly enable it by setting `<DisableGitAutoCRLFInPublishOutput>true</DisableGitAutoCRLFInPublishOutput>`
    * Pro: convenient for people who know about it
    * Con: undiscoverable without reading docs. People will still have deployment problems by default and not know what to do. If we're relying on people reading docs, why not just have docs telling them to add a `.gitattributes` file manually?
 * [C] Or, have the default on/off setting determined by the condition "is the publish output going into a git repo?". We can detect this by scanning upwards for the presence of a `.git` directory.
    * Pro: just works at least in the most obvious and basic cases, without cluttering things in non-Git scenarios.
    * Con: Since Git is so overwhelmingly prevalent, why go to all this effort to detect non-Git scenarios? Virtually nobody is *not* using Git.
    * Con: Still doesn't work in more complicated cases, such as when the build process is operating on files outside a Git repo (due to some custom CI setup) but the results are then being copied into a Git repo.

My first instinct is to think about a docs-only solution initially, and consider upgrading it to a more automated solution if we keep getting customer reports about it.

**Comment by SteveSandersonMS** [comment]
Just in case anyone's about to suggest it, here's a solution that *wouldn't* work:

**Change blazor.*.js in our packages to *nix-style line endings**

If we knew for sure that you'd be deploying to Linux, we would benefit from having blazor.*.js use *nix-style line endings even on Windows because then it would just work. However that's just moving the problem, because if you now deploy to a Windows production server, the issue still occurs since the checkout on the Windows server would convert to CRLF.

There is no single *correct* line ending style to solve this problem. We just need Git to stop interfering with the line endings.

**Comment by chucker** [comment]
Blazor generating a `.gitattributes` smells like an unexpected layering violation to me.

---

>Problem: If you use Git [1] as a way of transferring build output to your production server, and the production server has different newline conventions from the build server [2], then content hashes in text files (such as blazor.webassembly.*.js) will not match and the application will not load.

So, if I'm reading this correctly, the (flawed) flow is:

1. development machine produces hashes for files
2. development machine pushes the result, _including_ those hashes, to the remote git
3. production machine has different linebreak convention; thus, the hashes are wrong
4. in this scenario, production machine has no dynamic code (e.g. an ASP.NET Core server) running, i.e. the files are served statically, so this _cannot_ be fixed on the production end

So, given the existence of:

```xml
<BlazorCacheBootResources>false</BlazorCacheBootResources>
```

How about extending this as follows:

```xml
<BlazorCacheBootResources linebreakConvention="lf">false</BlazorCacheBootResources>
```

This still comes with the problem that now we've shifted the wrong behavior — production will now be right, and development no longer will be.

But that's a solved problem! Instead of placing `BlazorCacheBootResources` in the `.csproj` file, we put it in the `.pubxml`, which also uses MSBuild tooling. That way, we can even have different settings for this per-deployment endpoint.

**Comment by chanan** [comment]
@SteveSandersonMS I have not been able to get this solution to work.

I added `autocrlf=false` to my `.gitattributes` and after that did nothing I commented out: `* text=auto` which was created automatically by VS I think. 

Before commenting out `* text=auto` nothing changed. Once I commented that out I got an email from github:

```
The page build failed for the `master` branch with the following error:

Unable to build page. Please try again later.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact/pages?repo_id=197678953&page_build_id=168691231
```

Now when I go to the site I get in the console: 

```
(index):78 GET https://chanan.github.io/BlazorTypography/_framework/blazor.webassembly.js net::ERR_ABORTED 404
```

I am pretty sure its there. You can see the source of the site at: https://github.com/chanan/BlazorTypography/tree/master/docs

**Comment by jspuij** [comment]
@chanan autocrlf is for the git configuration, not for gitattributes.


`* binary`

would probably work for github pages. But do not use this in a source code repo, as line handling is a good thing.

**Comment by SteveSandersonMS** [comment]
> But do not use this in a source code repo, as line ending handling is a good thing.

It's perfectly reasonable to use it in the directory containing your publish output, since that exists only as a way of transferring the content to your production server. The files in that directory are not meant to be edited; they are just emitted by the build system.

**Comment by chanan** [comment]
@SteveSandersonMS Are you saying I should have a different gitattributes in the root and one in the /Docs?

**Comment by jspuij** [comment]
> server. The files in that directory are not meant to be edited; they are just emitted by the build system.

That's what I meant. Could have clarified that. Gitattributes supports patterns, so you could exclude directory from the root .gitattributes file, or just nest gitattributes files inside the repo structure.

**Comment by chanan** [comment]
Tried this. I put back the main gitattrbutes to the way it was before. Added a .gitattributes with the autocrlf in the /Docs - reuploaded the _framework folder.

Again I got an the same email from github that I pasted above. Still getting the 404 that I pasted in the same comment: https://github.com/dotnet/aspnetcore/issues/19796#issuecomment-598230931

End result: still not working

**Comment by campersau** [comment]
@chanan the `_framework` folder got deleted in https://github.com/chanan/BlazorTypography/commit/3f26aa4e897dd0286149b836ab57b7df8eac9de8

**Comment by chanan** [comment]
Sorry, you are right, forgot to push... it's there now, same result.

**Comment by jspuij** [comment]
use * binary

autocrlf is for .gitconfig files.

**Comment by jspuij** [comment]
also, you have to probably delete and recommit the blazor.webassembly.js file.

**Comment by chanan** [comment]
The original is in javascript files, aren't they text files?

Yes, I delete the whole _framework folder and upload every time

**Comment by chanan** [comment]
@jspuij @SteveSandersonMS This worked: https://github.com/dotnet/aspnetcore/issues/19796#issuecomment-598266167

To sum up:

1.  Leave .gitattributes in the main folder as is
2. In the docs folder add a .gitattributes with `* binary`

**Comment by SteveSandersonMS** [comment]
Step 3: Run `git add --renormalize .` if you've just added changed the `.gitattributes` file.

It works for me by the way: https://stevesandersonms.github.io/TestGithubPages/

**Comment by chanan** [comment]
I did it the stupid way of deleting _framework and re-uploading - but yes that would better :)

**Comment by mrpmorris** [comment]
Can you replace `#13#10` with `#10` in memory when computing the hash? Then it doesn't matter how it is stored.

**Comment by chucker** [comment]
@mrpmorris the way I understand the scenario, both the hash and the asset it's referring to are served statically, so there is no replacing things in memory.

**Comment by Franklin89** [comment]
Just in case for anyone hosting their App behind **Cloudflare** this issue can also be because you have Auto Minify enabled. By default Cloudflare will Auto Minify JavaScript files when caching them, which also means to remove all the comments etc. Since MS is code signing their JS files, that leaves a Signature Block at the bottom of the JS file, which will be stripped in the Auto Minification process when the file is cached at Cloudflare. This will also result in an invalid Integrity hash.

**Comment by mrpmorris** [comment]
How about using the DLL hash for embedded JS rather than the JS itself?

**Comment by Franklin89** [comment]
@mrpmorris In my opinion that would not really make sense. The 'integrity' hash checks the integrity of the js file. So you cant just take the dll hash. You need to hash the content of the file to make sure nothing has "changed".

**Comment by conficient** [comment]
@SteveSandersonMS  any idea why a Blazor DLL isn't loading from an ASP.NET Core host with this integrity issue? I have a Blazor client I am trying to retrofit on an existing ASP.NET Core app. The app runs MVC fine but Blazor has this error:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost:5001/_framework/_bin/Ambolt.UI.dll' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.
```
I doubt changing git settings will affect the /bin folder output since that's excluded.

**Comment by conficient** [comment]
Still investigating the above, getting 404 errors on all the framework DLLs if I delete the cache. It looks like the Blazor client app isn't getting imported but I can see the Ambolt.UI.dll and .pdb in the bin folder

**Comment by jspuij** [comment]
@conficient Make sure you have a project reference from the server project to the client project, clean out your obj and bin directories and try again.

Also make sure you have `app.UseBlazorFrameworkFiles();` inside the Configure method of the Startup class.

**Comment by conficient** [comment]
AHA! Thanks @jspuij  that's what I was missing - `app.UseBlazorFrameworkFiles();` fixed it

**Comment by StefH** [comment]
Using the three steps from @chanan + @SteveSandersonMS worked for me. (example : https://stefh.github.io/Howler.Blazor)

**Comment by snerks** [comment]
Thanks everyone! The suggestions here also worked for me:

Using the `master/docs` folder `gh-pages` approach:
1. In the `docs` folder, add a `.gitattributes` file, with content `* binary`
2. On dev machine: Publish the app
3. Replace `[GithubRepoName]\docs\_framework` folder with the Publish-ed equivalent folder
4. Commit and Push to GitHub

App is here:
https://snerks.github.io/BlazorApp322/

Source is here
https://github.com/snerks/BlazorApp322/tree/master/docs

Includes workaround steps for `gh-pages`:
`.nojekyll` file
Clever `404.html` redirecter file
Modified `index.html` file, to match `404.html` redirecter

@rafrex
https://github.com/rafrex/spa-github-pages

**Comment by mkArtakMSFT** [comment]
We will be addressing this as part of #22470

**Comment by zafer-v3** [comment]
Hello I run my application on Github pages.

1-) create dotnet blazor wasm app 
`dotnet new blazorwasm -o WebApplication1`

2-)create publish folder with dotnet cli
`dotnet publish -c Release`

3) go to publish folder \WebApplication1\bin\Release\netstandard2.1\publish\

4) change index.html 
`<base href="./" />`

5) create new file .gitattributes and add this line inside
`* binary`

6) create new file .nojekyll just empty file

7) create new file 404.html 

8) create git repostory (git init / add / remote / push)

8.1) I run this command before git add . 
`git add --renormalize .`

9)Go to repository settings page and select github pages branch.

And wait relase.

Sorry I dont now perfect English grammer. But I want to help everyone :)

Have a nice day!
