### ISSUE TITLE
Blazor templates not showing up correctly.

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#19800]
I am currently running Visual Studio 16.5.5 Preview 5 with the latest version of .NET Core SDK (dotnet --version => 3.1.200-preview-015002). I installed the latest Blazor WebAssembly template as instructed on the release [blog](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/).

The problem is that when I try to create a new Blazor project using the Visual Studio temple I get the following:

![BlaTemp](https://user-images.githubusercontent.com/13452107/76549128-d5355600-645d-11ea-8932-fc0c35c8d04b.png)

As you can see, there are repeated entries and when selecting a Blazor webassembly project the applicable options are not there.

Is there a way to fix this?

Edit: Perhaps I should have mentioned that if I create the project using this templates I get all kinds of compile errors as soon as I try run it. The template references assemblies back from 3.0.0-preview6.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rxelizondo.
@danroth27 I'm wondering whether the template package rename had some impact here. What will happen if customers had the old template installed and now they have also installed the new one?

@rxelizondo can you try to remove all blazor templates, and reinstall the latest one? Please note, that the old one had a different package name.

**Comment by rxelizondo** [comment]
@mkArtakMSFT I would be happy to remove the old template and reinstall the new one but I am not sure how to do that. Would you mind sharing basic instructions on how to delete the old template?

Thanks.

**Comment by danroth27** [comment]
Hi @rxelizondo. Do you by any chance have the old Blazor Visual Studio extension installed? If you do, you should uninstall it from the Extensions menu in VS.

On the command-line you can uninstall templates by first running `dotnet new -u` to see the template packs you have installed and then running `dotnet new -u {PACKAGEID}` for the template packs you want to uninstall. Try uninstalling all Blazor template packs and then reinstalling the latest one.

There's also a possibility that the Visual Studio template hive has gotten out of sync. To fix that you can shut down VS, delete the hive, and then restart VS so that VS will recreate the hive. The hive is located at */Users/{USER}/.templateengine/vs*.

I hope this helps!

**Comment by rxelizondo** [comment]
@danroth27 

I executed the command `dotnet new -u` and got the following:

```
Microsoft Windows [Version 10.0.18363.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Rene>dotnet new -u
Template Instantiation Commands for .NET Core CLI

Currently installed items:
  Microsoft.DotNet.Common.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.3.1
      Version: 3.1.2
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.3.1

  Microsoft.DotNet.Common.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.2.1
      Version: 1.0.2-beta3
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.2.1

  Microsoft.DotNet.Test.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.2.1
      Version: 1.0.2-beta4.20105.2
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.2.1

  Microsoft.DotNet.Web.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.3.1
      Version: 3.1.2
      Author: Microsoft
    Templates:
      Blazor Server App (blazorserver) C#
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      ASP.NET Core gRPC Service (grpc) C#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (webapp) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
      Worker Service (worker) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.3.1

  Microsoft.DotNet.Web.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.2.1
      Version: 2.1.14
      Author: Microsoft
    Templates:
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (razor) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.2.1

  Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1
      Version: 2.1.14
      Author: Microsoft
    Templates:
      ASP.NET Core with Angular (angular) C#
      ASP.NET Core with React.js (react) C#
      ASP.NET Core with React.js and Redux (reactredux) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1

  Microsoft.DotNet.Common.ItemTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ItemTemplates
      Version: 3.1.2
      Author: Microsoft
    Templates:
      dotnet gitignore file (gitignore)
      global.json file (globaljson)
      NuGet Config (nugetconfig)
      Solution File (sln)
      Dotnet local tool manifest file (tool-manifest)
      Web Config (webconfig)
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ItemTemplates

  Microsoft.DotNet.Test.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.3.1
      Version: 1.0.2-beta4.20079.1
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.3.1

  Microsoft.DotNet.Web.ItemTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ItemTemplates
      Version: 3.1.2
      Author: Microsoft
    Templates:
      Protocol Buffer File (proto)
      Razor Component (razorcomponent) C#
      Razor Page (page) C#
      MVC ViewImports (viewimports) C#
      MVC ViewStart (viewstart) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ItemTemplates

  Microsoft.DotNet.Web.Spa.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.Spa.ProjectTemplates.3.1
      Version: 3.1.2
      Author: Microsoft
    Templates:
      ASP.NET Core with Angular (angular) C#
      ASP.NET Core with React.js (react) C#
      ASP.NET Core with React.js and Redux (reactredux) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates.3.1

  Microsoft.Dotnet.WinForms.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.Dotnet.WinForms.ProjectTemplates
      Version: 4.8.1-servicing.20069.13
      Author: Microsoft
    Templates:
      Windows Forms (WinForms) Application (winforms) C#
      Windows Forms (WinForms) Class library (winformslib) C#
    Uninstall Command:
      dotnet new -u Microsoft.Dotnet.WinForms.ProjectTemplates

  Microsoft.DotNet.Wpf.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Wpf.ProjectTemplates
      Version: 3.1.2-servicing.20069.7
      Author: Microsoft
    Templates:
      WPF Application (wpf) C#
      WPF Class library (wpflib) C#
      WPF Custom Control Library (wpfcustomcontrollib) C#
      WPF User Control Library (wpfusercontrollib) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Wpf.ProjectTemplates

  NUnit3.DotNetNew.Template
    Details:
      NuGetPackageId: NUnit3.DotNetNew.Template
      Version: 1.7.1
      Author: akharlov
    Templates:
      NUnit 3 Test Project (nunit) C#
      NUnit 3 Test Item (nunit-test) C#
      NUnit 3 Test Project (nunit) F#
      NUnit 3 Test Item (nunit-test) F#
      NUnit 3 Test Project (nunit) VB
      NUnit 3 Test Item (nunit-test) VB
    Uninstall Command:
      dotnet new -u NUnit3.DotNetNew.Template

  Microsoft.AspNetCore.Components.WebAssembly.Templates
    Details:
      NuGetPackageId: Microsoft.AspNetCore.Components.WebAssembly.Templates
      Version: 3.2.0-preview2.20160.5
      Author: Microsoft
    Templates:
      Blazor WebAssembly App (blazorwasm) C#
    Uninstall Command:
      dotnet new -u Microsoft.AspNetCore.Components.WebAssembly.Templates

```

I deleted all the templates that had the word  `Blazor `on them, these templates were:

- NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.3.1
- NuGetPackageId: Microsoft.AspNetCore.Components.WebAssembly.Templates

I also deleted all the entries under the `/Users/{USER}/.templateengine/vs` folder. 

To make sure that I had a fresh start, I restarted my computer and after it restarted I tried creating the Blazor project using the templates and it did not work, I got the exact same screen and errors.

Maybe I did something wrong (perhaps I deleted the wrong templates?) so if you let me know what I did wrong I can try again.

Thanks.

**Comment by danroth27** [comment]
Oh, the Microsoft.DotNet.Web.ProjectTemplates.3.1 template pack contains the Blazor Server template which is part of SDK. You should do a repair on your SDK and it should come back.

Did you check if you have the old Blazor Visual Studio extension installed? You should be able to search through your installed VS extensions for "Blazor" and see if anything shows up.

Could you please also share the the output of dotnet --info?

**Comment by danroth27** [comment]
I think what's most likely happening here is you have an older SDK installed that has an older version of the Blazor template pack installed. I would go through your SDK versions and what Blazor WebAssembly templates they have installed if any and just remove them. 

Also, when you create a Blazor WebAssembly project from VS be sure to select .NET Core 3.1 from the dropdown in the "Create a new Blazor app" dialog.

**Comment by rxelizondo** [comment]
Aggg, I totally missed checking to see if there was a Blazor extension installed in VS, turns out that I did have a Blazor extensions installed and after deleting it and reinstalling the SDK everything appears to be working fine.'

Thanks you very, very, very much for you help!
