### ISSUE TITLE
Blazor Server template sidebar nav can show in expanded state on browser resize

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#19818]
The Blazor Server template has a rendering logic bug that results in the sidebar nav sometimes showing in its expanded state when the browser is resized to a size small enough to trigger the rendering of the menu in the top-right location (mobile-friendly mode). Seems to be caused by the fact the menu is "toggled" every time anything in it is clicked. Seems it should only be toggled if navigation to a new nav item actually occurs.

## Repro steps
1. Create a new Blazor Server app
1. Run the app
1. Upon opening in the browser, click the first menu item in the left-hand side nav bar
1. Resize the browser window smaller until the menu switches to rendering at the top of the page

## Expected behavior
The menu renders in the collapsed state:
![image](https://user-images.githubusercontent.com/249088/76578677-9f589780-6486-11ea-9abb-c17dc51f2ad1.png)

## Actual behavior
The menu renders in the expanded state:
![image](https://user-images.githubusercontent.com/249088/76578661-9071e500-6486-11ea-956a-218b88167d45.png)

**Comment by javiercn** [comment]
@DamianEdwards thanks for looking into the root cause.

We'll look into this after the webassembly release.

**Comment by mkArtakMSFT** [comment]
We'll handle this as part of template redesign which we will probably do as part of 5.0.
