### ISSUE TITLE
Remove Microsoft.AspNetCore.SpaServices.Extensions dependency on Microsoft.AspNetCore.SpaServices

### ISSUE THREAD

**Issue by ANahr** [dotnet/aspnetcore#19816]
There was already an issue for removing Microsoft.AspNetCore.SpaServices.Extensions dependency on Microsoft.AspNetCore.SpaServices #11627.

That issue was closed as fixed. However when having a look at https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions/ you can see that this does not seem to be the case.

**Comment by mkArtakMSFT** [comment]
@pranavkm I assume this should be marked as `Done` already?
