### ISSUE TITLE
[Question] Advance publish scenario - deal with central dll repository

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#19825]
Hello guys, I wanted to know is there is a way to make my .NET core app working by taking their dll in another directory.
Typically When i deploy  my .net core server app  which a render a webassembly app, i have a lot of dll in common between these two projects. It make the bundle of file really heavy (70 Mb in my case).
I try to make some script to deploy my apps without the dlls and deal with them on the assembly Resolve at startup
````
AppDomain.CurrentDomain.AssemblyResolve += 
               CurrentDomain_AssemblyResolve; 
````
But no way, i think because of the file project.deps.json, the server app can't be launched because dependencies are not resolve

So what the actual position/recommandation on this subject ? (as well for .net core app and webassembly app)

Thanks for your help !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

Is this a question in the context of ASP.NET Core, general .NET or Blazor? If it is one of the first two ones, you might be able to add additional probing paths to your apps or something on those lines, but that's not something I'm an expert on, so I would suggest you ask that question in the [dotnet/runtime](https://github.com/dotnet/runtime) repo. You would have to make sure that the assemblies you want to share have the same version, as you are trying to create your own "mini GAC".

This is something where you would likely have to write your own post publish step to implement.

If it is in the context of blazor, we don't have any current plans to do this at the moment/

**Comment by Pilchie** [comment]
Closing as answered.
