### ISSUE TITLE
[Feature Request] SAML client and IdP support

### ISSUE THREAD

**Issue by hez2010** [dotnet/aspnetcore#19821]
### Feature request
Built-in SAML client and IdP support

### Describe the solution you'd like
ASP.NET Core currently has bulit-in OAuth support for API authentication, however, OAuth is not very suitable for a general SSO identity provider which is used to share user identities between apps. 

Hope that ASP.NET Core can provide built-in SAML support, both for client and identity provider.

**Comment by blowdart** [comment]
We have WS-Fed already. Which is SAML. 

See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1#use-ws-federation-without-aspnet-core-identity

**Comment by hez2010** [comment]
@blowdart Thanks. I'll try WS-Fed and IdentityServer.

**Comment by anurse** [comment]
> However, there's still no SAML for IdP

Can you elaborate on this? What do you mean by `IdP`? Are you talking about a specific identity provider?

**Comment by hez2010** [comment]
@anurse 
> What do you mean by `IdP`?

Yes, I meant identity provider.

**Comment by blowdart** [comment]
We don't provide identity provider code, that's simply not in our feature set,
