### ISSUE TITLE
[Question] Dual/Multi Mode Strategy for blazor

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#19824]
Hello guys, i have architecture related question about the best/recommanded way to make a blazor project working as well as webassembly and server mode.
- When i began my project, i based my architecture on the daniel roth project : https://github.com/danroth27/BlazorDualMode. I'm still on this architecture, it still working but im really afraid one day after an update it will not work. 
- ideally, i wan't to achieve something like that : https://visionsincode.wordpress.com/2019/11/01/one-solution-setup-to-rule-them-all-blazor-webassembly-blazor-server-blazor-electron/. In this way the app is really isolated in a library, and can be run by multiple launcher (webassembly, server-side, electron, etc). The problem i have with this solution is it seem the guy override a lot of code of the blazor router to make this working, i really don't want to do that for the maintenability of my app. The library are not suppose contains entire pages. 

What guys do you think about it ? There is something planned by Microsoft ? 

thanks for your help !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Nothing planned by us in this space in the near future. That said, things may change and we may revisit that later.

**Comment by mkArtakMSFT** [comment]
As for which way to go, we have no specific recommendation - it's completely up to you. @danroth27 may try to update  his sample so that it's based on the recent Blazor release.
