### ISSUE TITLE
Consume DebugProxy package from runtime repo

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19827]
Currently we have `M.A.C.WA.Runtime` in dotnet/blazor, and `M.A.C.WA.DebugProxy` in dotnet/aspnetcore. Only dotnet/blazor is updated automatically to match mono/mono.

This discrepancy is a liability for us, because nothing keeps our version of the Mono runtime in sync with our version of the ws-proxy code. This could break debugging (sometimes dramatically, or sometimes in subtle and weird ways). Also it's constant work to keep updating ws-proxy sources manually [like this](https://github.com/dotnet/aspnetcore/pull/19826).

Since `M.A.C.WA.DebugProxy` is now a self-contained executable, it would be pretty straightforward to move and build it in the dotnet/blazor repo. If we did that, we could update @pranavkm's automation so that as well as updating the Mono runtime files, it could update the three `.cs` source files in `DebugProxy\src\MonoDebugProxy\ws-proxy`.

**Comment by captainsafia** [comment]
Hmmm. I can take a look at this.

**Comment by captainsafia** [comment]
@mkArtakMSFT We should consider bring in this item to the upcoming sprint.

It's the first building block for the work to move launching the DebugProxy to the IDE.

**Comment by captainsafia** [comment]
I'm moving this back to sprint planning.

Now that .NET supports WASM, the sources for the Mono Proxy (and the DebugProxy) will likely move around.

In the future, this issue will probably be something like "consume the MonoProxy package" or perhaps there's no DebugProxy in the framework packages and we just launch the MonoProxy directly.

We'll have a better sense of this around preview8.

**Comment by captainsafia** [comment]
Updates on this. Synced with the Mono team and the MonoProxy sources will be moved into the runtime repo and published as a NuGet package. We'll need to consume that from within our sources.

The Mono team also has a ProxyDriver similar to our DebugProxy that can be packaged to completely replace our DebugProxy server. This will likely happen after the MonoProxy package with the entrypoint API has been exposed.
