### ISSUE TITLE
How to send object from a component to another

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#19820]
### Goal
I have a component A which has an object I want to send to component B

### Should I use
- Route?
- AppState pattern? 

When it comes to routing all information I found refers to passing either ```string``` or ```int```. In MVC I was able to pass objects as parameters with no problem.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Is your question regarding Blazor WASM or Blazor Server?

**Comment by mkArtakMSFT** [comment]
In case of Blazor WASM, if components are not in parent-child relationship, consider using a service for communication. Register it in DI and add inject it into both components.
As an example, you can then expose two `GetState` and `SetState` APIs on that service, which you can use to transfer information between components. This will also work for parent-child relationship situations, but there are other options there as well, which may be simpler.

Please note, that this issue tracker is not aimed to serve as a general-purpose forum to ask questions. We recommend using [StackOverflow](https://stackoverflow.com) for these types of questions as that way you will get much faster response.
