### ISSUE TITLE
JsonPropertyName not working on model binding

### ISSUE THREAD

**Issue by MrCoft** [dotnet/aspnetcore#19835]
I am using a class as an endpoint model with the following attribute:
```cs
[JsonPropertyName("per_page")]
public int PerPage { get; set; }
```
This makes the class serialize with `per_page`, but it never matches it from an incoming query.

Steps to reproduce:
- Download and run project: https://github.com/MrCoft/AspJsonPropertyNameBug
- Send GET to `http://localhost:5000/table-page?sort&page=1&per_page=15`
- Console prints `{"Sort":null,"Page":1,"per_page":0}`

Info:
- ASP.NET Core 3.1
- IDE: Microsoft Visual Studio Community 2019, Version 16.4.5
- `dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
@MrCoft, MVC has two ways of deserializing content from a request in to a .NET type. Formatting is where you have a HTTP request body and you deserialize a model from a JSON (or XML) payload. This understands JSON specific APIs such as `JsonPropertyName`. 

[Model binding](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1) on the other hand reconstructs a model from the query, route, form-post, etc. This uses a different set of attributes to describe how to deserialize a type. The linked doc includes some examples. In your case, using a `[ModelBinder(Name = "per_page"])` would be the easiest way to go.

**Comment by MrCoft** [comment]
@pranavkm Right, my bad, I just wanted to rename the property, but the query isn't a JSON source. Thank you.
