### ISSUE TITLE
Protecting functions with B2C

### ISSUE THREAD

**Issue by raymond-holmboe** [dotnet/aspnetcore#19834]
I could not get my scenario working: a Blazor Webassembly app hosted in a storage account as static page, calling Azure Functions protected by B2C.
I was blocked by a CORS issue. Any chance this may work in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfb23446-3b01-73a8-70e2-697367065264
* Version Independent ID: 67b01234-eeaf-dcee-929f-6e2f6880e313
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by mkArtakMSFT** [comment]
@javiercn in case you have some quick suggestion for this, you're welcome to share :)

**Comment by javiercn** [comment]
@raymond-holmboe thanks for contacting us. Where were you having the CORS issue? Was this related to functions not sending CORS response headers or something else?

**Comment by raymond-holmboe** [comment]
Thanks for getting back to me. The issue seems to be between the function and Azure B2C.
I tried to add the CORS headers on the function (with * and all verbs) but it does not help. Because this is just a test environment, I post the entire error here, this is from the browser console window. The static page URL is: https://scowasmstorage.z16.web.core.windows.net/fetchdata

Access to fetch at 'https://synkronob2c.b2clogin.com/synkronob2c.onmicrosoft.com/oauth2/v2.0/authorize?response_type=id_token&redirect_uri=https%3A%2F%2Fscofunctions.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=7d49fc80-bf43-4cca-8abc-adfcd3b73d0e&scope=openid+profile+email&response_mode=form_post&p=b2c_1_siupin&nonce=422aa7c3294e4225b32a743bc75bf21b_20200317011503&state=redir%3D%252Fapi%252FFunction1%253Fcode%253DwwrOe77EkQ1Q9NaHMkJJ%252FFcBf3xmX3S0lQaNuaAOtcyTl5ai73i0Sg%253D%253D' (redirected from 'https://scofunctions.azurewebsites.net/api/Function1?code=wwrOe77EkQ1Q9NaHMkJJ/FcBf3xmX3S0lQaNuaAOtcyTl5ai73i0Sg==') from origin 'https://scowasmstorage.z16.web.core.windows.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by javiercn** [comment]
@raymond-holmboe This doesn't seem to have anything to do with Blazor itself. As far as I understand, you are able to get a token and what is failing is the call to the function with the token?

**Comment by raymond-holmboe** [comment]
I don't have the token yet, I'm trying to get the SignIn/SignUp page of AzureB2C to show. It actually shows up correctly when I go to the function endpoint directly in the browser: https://scofunctions.azurewebsites.net/api/Function1?code=wwrOe77EkQ1Q9NaHMkJJ/FcBf3xmX3S0lQaNuaAOtcyTl5ai73i0Sg==
But not when the function is called from the static page where the webassembly app is. 
So I am guessing that the Azure B2C workflow does not work from a static page without it's being "hosted", meaning there's an API server in between the static page and functions, and I'm trying to avoid that.

**Comment by javiercn** [comment]
@raymond-holmboe what are you using for authenticating with B2C on your static page?

**Comment by ghidello** [comment]
As far as i know Azure B2c doesn’t support cors on the token endpoint. You should try to use the implicit flow instead of the code+pkce flow
