### ISSUE TITLE
Where does AddBaseAddressHttpClient is defined ?

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#19842]
Please, provide a url to this extension method. I could not find it anywhere... Only two issues related to it.

Thanks...

**Comment by MitchellNZ** [comment]
@enetstudio https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Services/HttpClientServiceCollectionExtensions.cs

**Comment by enetstudio** [comment]
@Mitchell Currey, many thanks for your help.  I didn't know that there is something called Branch: blazor-wasm. I've always used master. I think I should spend some time learning how github works. In any case, your help is appreciated, as I've spend a great deal of time looking for this method.
