### ISSUE TITLE
Discarding variable when using EventCallback<T>

### ISSUE THREAD

**Issue by kramaswamy7** [dotnet/aspnetcore#19844]
### Describe the bug
When trying to implement an EventCallback for a generic-typed object, you are not able to discard the input variable used. This behavior is unusual, as for a non-generic-typed object, there are no problems discarding the input variable.

### To Reproduce
Index.razor:
``` C#
@page "/"

<MyGenericObject Value="@($"Test")" ValueChanged="@(_ => MyMethod())"></MyGenericObject>
<MyObject Value="@($"Test")" ValueChanged="@(_ => MyMethod())"></MyObject>

@code {
    protected void MyMethod()
    {

    }
}
```
MyObject.razor:
``` C#
@inherits MyObjectBase

<div>@Value.ToString()</div>
```
MyObject.razor.cs:
``` C#
using Microsoft.AspNetCore.Components;

namespace BlazorApp1.Pages
{
    public class MyObjectBase : ComponentBase
    {
        [Parameter] public string Value { get; set; }
        [Parameter] public EventCallback ValueChanged { get; set; }
    }
}
```
MyGenericObject.razor:
``` C#
@typeparam T
@inherits MyGenericObjectBase<T>

<div>@Value.ToString()</div>
```
MyGenericObject.razor.cs:
``` C#
using Microsoft.AspNetCore.Components;

namespace BlazorApp1.Pages
{
    public class MyGenericObjectBase<T> : ComponentBase
    {
        [Parameter] public T Value { get; set; }
        [Parameter] public EventCallback<T> ValueChanged { get; set; }
    }
}
```
Exception:
```
Error CS1503: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback' to 'Microsoft.AspNetCore.Components.EventCallback<string>'
```
### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

IDE: 
Microsoft Visual Studio Community 2019
Version 16.4.5
VisualStudio.16.Release/16.4.5+29806.167
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.4.460.23317
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.460.23317
For additional information, visit https://www.asp.net/

C# Tools   3.4.1-beta4-19614-01+165046097562cfe65b09c2e9a9d8f7cd88526f2c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
