### ISSUE TITLE
API for marking parameters/types as immutable

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#19840]
It seems like we have some scenarios where unnecessary re-renders occur.  Here's a very simple reproduction:

https://github.com/zbecknell/RerenderRepro/blob/master/Client/Pages/FetchData.razor

When clicking the `Test` button, you'll see each `<ForecastRow>` component being rendered.  Were we to change the `Forecast` parameter on `<ForecastRow>` to a simple `string` parameter, no re-render occurs.

In my case, my app has an expensive list of objects that are re-rendered each time we click an unrelated button.

I've tested and reproduced with both CSB and SSB.

**Comment by zbecknell** [comment]
This is the practical effect it's having on a page with ~20 complex elements:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/9710256/76656847-e3ab6c80-6546-11ea-8e2e-eac992131915.png">

The button click causes a re-render and then the modal popping up causes one as well, so the complex components in the list are rendering twice.  This is currently much less noticeable in server mode due to performance, but the renders still occur.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We haven't yet investigated this. Before we get to this, we recommend reviewing the [Blazor Lifecycle Docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1) to make sure your app doesn't fall into a valid re-rendering condition.

**Comment by zbecknell** [comment]
My situation is falling into this scenario:

> OnParametersSetAsync and OnParametersSet are called:
>
>    * When the component is initialized and has received its first set of parameters from its parent component.
>    * When the parent component re-renders and supplies:
>        * Only known primitive immutable types of which at least one parameter has changed.
>        * Any complex-typed parameters. The framework can't know whether the values of a complex-typed parameter have mutated internally, so it treats the parameter set as changed.

https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#after-parameters-are-set

With that being said, I'd really like to see some sort of built-in option on the base component object to enable enhanced comparison of parameters, including complex types.  Or perhaps I need guidance on a recommended way of improving performance in this scenario? 

For me, a modest increase in compute time to compare complex parameters would pay off versus re-rendering.

**What I'll attempt on my own:**

* Compare the parameters in `SetParametersAsync()` by serializing and hashing each one.
* Override `ShouldRender()` and return true only when the hashes change.

I'll update this issue with the solution if/when I can solve my problem.

**Comment by zbecknell** [comment]
Here is my workaround for this:

`CustomComponentBase.cs`

```csharp
public class CustomComponentBase : ComponentBase
{
	/// <summary>
	/// When true, parameters will be serialized and be compared before allowing a re-render.
	/// </summary>
	protected bool StrictParameterCheck { get; set; } = false;

	private string oldParameters = "";
	private bool shouldRender = false;

	public override async Task SetParametersAsync(ParameterView parameters)
	{
		if (StrictParameterCheck)
		{
			var newParameters = Newtonsoft.Json.JsonConvert.SerializeObject(parameters.ToDictionary());

			shouldRender = oldParameters != newParameters;

			oldParameters = newParameters;
		}

		await base.SetParametersAsync(parameters);
	}

	protected override bool ShouldRender() => StrictParameterCheck ? shouldRender : base.ShouldRender();
}
```

This is a simple solution that can be opt-in when it's worth trading the performance of serialization for the performance of extra renders.  I'm sure there are holes in it, but it's working in my current scenario.  If anyone has suggestions for improvement, please add them.

**Comment by javiercn** [comment]
The behavior here is expected. We would need stronger evidence that there is a performance bottleneck caused specifically by the fact that we re-render the component by calling SetParameters on the child component before we decide to take any action here.

Blazor is very conservative when checking for parameter changes and will not consider complex-type parameters as the results of an error there are catastrophic and very hard to track down, which leads to a bad experience.

It is ok for renders to happen many times as they are tuned to be as performant as possible, and other actions can be taken on the component themselves (ShouldRender) and on the parent component to fine tune the rendering process on a per-case basis.

I'm putting this issue on the backlog until we hear more feedback and get more concrete details of this being a problem.

**Comment by TanayParikh** [comment]
Hi. Thanks for contacting us. We're closing this issue as there was not much community interest in this ask for quite a while now. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
