### ISSUE TITLE
Problem in Json in appsetting with json having underscore in it's key name

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#19859]
I am facing issue in json in appsettings file where key contains _ e.g.
{
"Key1":"test",
"Key2_problematic":"test2",
"key3":" "test3"

}

Key2_problematic never get loaded in Class property named Key2_problematic
if i remove _  from the key and from my class property value all works.

I am using System.Text.Json in my .net core 3.1 application.

**Comment by KamranShahid** [comment]
Just surprised that no other one faced this issue. Faced it some months ago where i have get rid of newtonjson from my application my .net core 3.1 application . now again i am facing it in another fresh application

**Comment by huysentruitw** [comment]
The reason why no one has faced this issue is probably because not much developers use underscores in property-names and thus also not in their appsettings.json. Is that a certain convention you're using?

**Comment by KamranShahid** [comment]
> The reason why no one has faced this issue is probably because not much developers use underscores in property-names and thus also not in their appsettings.json. Is that a certain convention you're using?

Not using this for new things. There were some old existing items whose keys were with underscore.  But what i remember with default json parser as newtonsoft i never experience this.

**Comment by JunTaoLuo** [comment]
This is an issue with how configuration with Json files are handled. Can you clarify whether you are using Microsoft.Extensions.Configuration.Json or Microsoft.Extensions.Configuration.NewtonsoftJson so I can route to the correct repo?
