### ISSUE TITLE
About endpoint routes url segment separation

### ISSUE THREAD

**Issue by sefacan** [dotnet/aspnetcore#19853]
Hi,

I created an endpoint routes like => /search/{firstTerm}-{secondTerm}

My action:
public IActionResult Search(string firstTerm, string secondTerm)

But if there is a url like this, wrong values ​​are coming.
http://www.domain.com/search/my-app-your-app

* firstTerm => my
* secondTerm => app-your-app

Maybe I'm building it wrong. what is the right way?
Since the url structure I want to create is exactly that, your suggestions for changes in the route section will not work for me.

**Comment by javiercn** [comment]
@sefacan thanks for contacting us.

You can't do what you are trying to achieve with "complex segments" as the mapping MVC did is perfectly valid.

Instead I would recommend you use a single parameter and a regex constraint to achieve the result you want. You'll have to re-parse the individual values though as they won't be part of the route data.

**Comment by sefacan** [comment]
Thanks for you answer.
