### ISSUE TITLE
 System.InvalidOperationException : No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[Autofac.ContainerBuilder]' has been registered.

### ISSUE THREAD

**Issue by jxl1024** [dotnet/aspnetcore#19868]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
Thanks for contacting us @jxl1024 

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag.

**Comment by Pilchie** [comment]
Closing stale issue.
