### ISSUE TITLE
AzureADB2COpenIdConnectOptionsConfiguration generates incorrect Authority for currently deployed version of Azure AD B2C

### ISSUE THREAD

**Issue by alexmarshall132** [dotnet/aspnetcore#19865]
### Description
When attempting to validate tokens on incoming requests from Azure AD B2C SPA applications running in Angular JS8, `AzureADB2COpenIdConnectOptionsConfiguration.BuildAuthority` generates an incorrect authority, resulting in the following Exception:

```
IDX20807: Unable to retrieve document from: 'https://login.microsoftonline.com/<myb2cdomain>.onmicrosoft.com/B2C_1_[MySignInPolicyName]/v2.0/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: private
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  x-ms-request-id: 3f4a9999-50a3-40ee-a873-7c30160a0201
  x-ms-ests-server: 2.1.10155.17 - CHI ProdSlices
  P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
  Set-Cookie: x-ms-gateway-slice=prod; path=/; secure; HttpOnly
  Date: Sun, 15 Mar 2020 08:53:07 GMT
  Content-Length: 0
}', HttpResponseMessage.Content: ''.
```

The retrieval of the B2C OpenId Configuration should be from a path that looks more like:
```
https://<myb2cdomain>.b2clogin.com/<myb2cdomain>.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_[MySignInPolicyName]
```

The problem appears to be caused by incorrect resolution of the Open ID Configuration path.

### To Reproduce
Follow the instructions on this blog to generate the minimal reproduction, with subsequent changes:
`https://about-azure.com/using-azure-ad-b2c-with-angular-8/`:
-- Update both applications from dotnet 2.2 to 3.1 (since 2.2 is EOL)
-- In the API project, update Microsoft.AspNetCore.Authentication.AzureADB2C.UI to version 3.1.2
-- Call `IdentityModelEventSource.ShowPII = true;` in `ConfigureServices` in the API project.

### Further technical details
- ASP.NET Core version: 
3.1

- Include the output of `dotnet --info`
3.1.101

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:
Microsoft Visual Studio Enterprise 2019
Version 16.4.6

**Comment by blowdart** [comment]
@javiercn Is this a dupe of https://github.com/dotnet/aspnetcore/issues/15022 and https://github.com/dotnet/aspnetcore/issues/17014 ?

**Comment by alexmarshall132** [comment]
> @javiercn Is this a dupe of #15022 and #17014 ?

With the brief read through of those issues, I don't think so. This issue is on the server side token validation and is validating tokens generated by a JavaScript MSAL client not implemented in Blazor. I could be mistaken though and a polite correction would be welcome to show me where I've misunderstood the nature of those two issues if that's the case

**Comment by anurse** [comment]
The issue is that the JavaScript component is using the v2 endpoints but the server-side is still on v1.

This seems like a duplicate of #12626 then (updating the server-side components to support the v2 endpoints)

**Comment by anurse** [comment]
Closing as duplicate (see above comment).
