### ISSUE TITLE
System.IO.FileNotFoundException when building in WSL2

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [dotnet/aspnetcore#19864]
I was working on the tutorial called [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio-code) and ran into the following error during the [Run the app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio-code#run-the-app) step;

`System.IO.FileNotFoundException: Could not load file or assembly '/home/ryan/BlazorSignalRApp/Client/obj/Debug/netstandard2.1/BlazorSignalRApp.Client.dll'`

I reported the issue in the AspNetCore.Docs repo and was asked by @guardrex to transfer it here.

I'm using Visual Studio Code to work on the app. I've tried running the "Run Without Debugging" command as well as running `dotnet run`, `dotnet build`and `dotnet clean && dotnet build` in both the Client & Server apps, all result in the same error.

I'm also using WSL2 with Ubuntu along with its integration into VSCode. I've tried running the commands both through the integrated terminal and the Windows Terminal. I walked through the tutorial from a template generated in PowerShell and the application ran as expected.

I did notice that the `dotnet --version` on Windows is 3.1.102 while on Ubuntu it's 3.1.101. When I try updating my Ubuntu version it says I'm at the latest version.

Here's the output of `dotnet --info`
The .NET CLI version I'm using is 3.1.101
```.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Your observation regarding the SDK version is right. You will have to have 3.1.102+ in WSL too.
