### ISSUE TITLE
BigInteger.Parse is wrong, exceeds Span<char> boundaries

### ISSUE THREAD

**Issue by joshlang** [dotnet/aspnetcore#19863]
```
var slice = "355982374923475".AsSpan(0, 1);
Console.WriteLine(slice.ToString());
Console.WriteLine(BigInteger.Parse(slice));
```

In .net core, output:
```
3
3
```

In blazor, output:
```
3
355982374923475
```

This might belong in the mono repo, but we found it in our client-side blazor app, so I'm reporting it here.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19239
