### ISSUE TITLE
Debug issue of aspnetcore source on VS2019

### ISSUE THREAD

**Issue by jyotishbora** [dotnet/aspnetcore#19869]
I was able to successfully build  aspnetcore code base by following the instructions at (https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md). But when I run any of the sample projects in debug mode and set a break point, none of the breakpoints are being hit and  I get "The application is in Break mode" message.( Screenshot attached).  

I want to point out that I am **not**  referring to stepping into aspnetcore code from my application using source linking and loading debug symbols as mentioned here 
https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source
I am struggling to debug the actual aspnet core source code on my local machine after i downloaded the source from git.

What am I missing?
![2020-03-13_21-46-49](https://user-images.githubusercontent.com/7849674/76704450-7bc46580-66af-11ea-9dac-a5ce5da79e5a.png)

**Comment by jkotalik** [comment]
We noticed the same, this was a recent regression in the dotnet/runtime repo. This will be fixed when we update dependencies from the runtime repo, which is being tracked here: https://github.com/dotnet/aspnetcore/issues/19838

**Comment by jkotalik** [comment]
Closing as dup.

**Comment by jyotishbora** [comment]
Thank you for the update. I will track the other thread
