### ISSUE TITLE
Configure IdentityServer Key Store by Thumbprint or Serial Number

### ISSUE THREAD

**Issue by gusarov** [dotnet/aspnetcore#19872]
### Problem
I am trying to publish new ASP Net Core + Angular application created form VS template with Identity Server enabled by default. This works for development environment, but fails on production because I have to configure Identity Server key store first. Since Identity Server does not need trusted certificate for token signing, I've generated self-signed certificate via IIS. This one saves to LocalMachine\Personal folder automatically with the subject equal to server name (e.g. FOX). To configure appsettings.production.json I've added this:
```js
  "IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Name": "CN=FOX"
    }
  }
```
But I have lots of FOX subjects and this is not reliable way to lookup for the certificate, so, AspNetCore.ApiAuthorization.IdentityServer chooses first certificate and it is **wrong** one.

### Solution
I'd like to have an ability to specify certificate by Thumbprint or Serial Number, like this:
```js
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Thumbprint": "0ce5e2126ab4030fe0..."
    }
```

as far as I can see, should be easy to implement in ```Microsoft.AspNetCore.ApiAuthorization.IdentityServer.SigningKeysLoader``` or ```ConfigureSigningCredentials```

**Comment by blowdart** [comment]
We don't hide identity server's configuration options, so you should be able to do

```c#
services.AddIdentityServer()
.AddApiAuthorization<ApplicationUser, ApplicationDbContext>()
.AddSigningCredential(yourX509Certificate2);
```

in startup, and load/resolve the certificate yourself into an X509Certificate2 instance, or go with Identity Server's recommendations for [handing rollovers](http://docs.identityserver.io/en/latest/topics/crypto.html)

**Comment by anurse** [comment]
Closing as we believe this is answered, let us know if you have further questions!
