### ISSUE TITLE
Blazor-wasm (authentication): add OidcProviderOptions.MetadataAddress property

### ISSUE THREAD

**Issue by vstribrny** [dotnet/aspnetcore#19877]
While using `builder.Services.AddOidcAuthentication` (as part of `WebAssemblyAuthenticationServiceCollectionExtensions`), I am not able to specify metadata address of the OIDC provider. The metadata endpoint does not necessarily have to be aligned with `OidcProviderOptions.Authority` (typical in dev/test environments, but sometimes also in prod ones).

I think we need to add `MetadataAddress` property to `OidcProviderOptions` (much like there is `Microsoft.AspNetCore.Authentication.OpenIdConnect.MetadataAddress` in server-side OIDC configuration).

Or, am I missing something and it is somehow possible to configure metadata address if OIDC provider?

**Comment by javiercn** [comment]
@vstribrny thanks for contacting us.

Is there any specific provider you are running into issues with?

**Comment by vstribrny** [comment]
The OIDC provider is [IdentityServer](https://github.com/IdentityServer/IdentityServer4), our custom implementation.
