### ISSUE TITLE
Debug the source and get an error about nuget 

### ISSUE THREAD

**Issue by w152013768** [dotnet/aspnetcore#19874]
When  built the source of aspnetcore according the url (https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md)，I got an error on running the restore command. The error is showed as below:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(123,5): error : can not load source https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-corefx-0f7f38c4/nuget/v3/i
ndex.json  service index。 [C:\Users\WQ\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19607.3\tools\Tools.proj]    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe ts(123,5): error :   response code shows failed: 404 (Not Found - The feed with ID 'darc-pub-dotnet-corefx-0f7f38c4' doesn't exist. (D
evOps Activity ID: 157F7673-97AC-4DA2-80F6-9369EE659F5B))。 [C:\Users\WQ\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19607.3\tools\Tools.proj]
Build failed.

I have reinstall the visual studio 2019 enterprise，but it have no use. Can anybody help me ? Thanks very much!

**Comment by windsOne** [comment]
Me Two
need to help
![image](https://user-images.githubusercontent.com/14890297/76727483-1cd61d80-678f-11ea-9166-3fa811b06240.png)

**Comment by NextLoad** [comment]
I had the same problem, I removed a key-value setting about the source "https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-corefx-0f7f38c4/nuget/v3/i
ndex.json" from the "aspnetcore/NuGet.config" file, Then “restore.cmd” is executed successfully

**Comment by w152013768** [comment]
@NextLoad , You are right, Thank you very much!

**Comment by windsOne** [comment]
@NextLoad  good idea

**Comment by dougbu** [comment]
FYI this feed exists but it's empty these days i.e. all of the packages were deleted but you shouldn't get 404 responses. Have you been able to build more recently @w152013768❔ If yes, the problem has been resolved.

**Comment by dougbu** [comment]
@mmitche did our handling of build-specific public feeds change at some point from deleting the feed to empty them instead❔

**Comment by mmitche** [comment]
> @mmitche did our handling of build-specific public feeds change at some point from deleting the feed to empty them instead❔

Yes. Unfortunately with nuget, a feed that is a 404 fails the restore, even if the exact package is found on another feed.

**Comment by dougbu** [comment]
:ok: thanks @mmitche 

@w152013768 thank you for your feedback. We're closing this issue as we think this is fixed in our working code base. Would you be able to try again see if the issue is resolved for you❔
