### ISSUE TITLE
Set response.ContentType to "application/hal+json” for all responses

### ISSUE THREAD

**Issue by martinsubash** [dotnet/aspnetcore#19876]
# Issue Title

Set response.ContentType to "application/hal+json” for all responses

# General

Actually after migrate to dotnet core 3.1 the JsonResultExecutor (Microsoft.AspNetCore.Mvc.Formatters.Json, Version=2.1.1) was not supported.

Previously(dotnet core 2.2) we are override the JsonResultExecutor and set the response.ContentType as "application/hal+json”.  So all the response.ContentType set to "application/hal+json”.

```
private HttpResponse PrepareResponse(HalJsonResult result, HttpResponse response)
        {
            response.ContentType = "application/hal+json";

            if (result.StatusCode != null)
            {
                response.StatusCode = result.StatusCode.Value;
            }

            if (result.LocationHeader != null)
            {
                response.Headers.Add("Location", Convert.ToString(result.LocationHeader));
            }

            return response;
        }

```

But after migration, the above codes are removed from the project. So that the current response.ContentType is "application/json” instead "application/hal+json”.

Any idea how to set the response.ContentType as application/hal+json in dotnet core 3.1 project.

**Comment by rynowak** [comment]
There are now two implementations of `IActionResultExecutor<JsonResult>` based on which serializer you're using.

If I were in your position, I would use an `IAlwaysRunResultFilter` instead of replacing the executor. Check if the result is convertable to `ObjectResult` or `JsonResult` and then set the content type.
