### ISSUE TITLE
Blazor Client Side & Server Side in the same template

### ISSUE THREAD

**Issue by GioviQ** [dotnet/aspnetcore#19888]
I am starting to study Blazor and instead of the new templates described here https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/, I found more interesting this project https://github.com/enkodellc/blazorboilerplate, where in the same Visual Studio Solution you can switch between client side and server side configuration.

**Comment by javiercn** [comment]
@GioviQ thanks for contacting us.

As far as I know, this is not something we plan to do in the near future, as it as complexity to the starting point of many applications and is something that most people don't need. 

If you need this type of flexibility is easy enough to build it yourself.
