### ISSUE TITLE
Blazor Wasm IdentityServer Custom Claims

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#19886]
In a Blazor server I was able to get custom user claim by calling:

`options.ClaimActions.MapUniqueJsonKey("subscriptionlevel", "subscriptionlevel");` on the `AddOpenIdConnect()` extension method.

And in a razor component use `@context.User.Claims.FirstOrDefault(c => c.Type == "subscriptionlevel")?.Value`

How we can manage claims in a Blazor Wasm project (ex.: define a `subscriptionlevel` `IdentityResource` at IdentityServer level , add it to the client's `AllowedScopes` and check for it in a razor component)?

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

If you get to include the data in the token (which you can do with a custom Identity ClaimsPrincipalFactory you can tell identity server to include it in whatever token is generated for your app).

You can then add claims in the same way they roles are added. See [here](https://github.com/dotnet/AspNetCore.Docs/issues/17649) for an example.
