### ISSUE TITLE
Blazor PWA on iOS: Icon is wrong

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19883]
Firstly, it doesn't use the `icon-512.png` by default at all, because iOS doesn't respect the `icons` property inside `manifest.json`. Instead, you need to reference the icon from `index.html` like this:

```html
<link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
```

Secondly, iOS does not do well with icons that have a transparent background. It renders them against a black background, which doesn't always look good. In the case of the Blazor logo, it looks awful. We should fix this by changing `icon-512.png` to have a solid white background.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/19897
