### ISSUE TITLE
Blazor on iOS: Scaling is annoying

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19885]
Currently the template `index.html` includes: 

```html
<meta name="viewport" content="width=device-width" />
```

This doesn't block user scaling, which means:

1. If you double-tap somewhere, it zooms in, which looks bizarre
2. All click events are subject to a 300ms delay

We should fix this by changing the default to:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

That eliminates both problems.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/19898
