### ISSUE TITLE
Blazor PWA: Start URL is wrong for sites not deployed to the root URL

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19884]
The `manifest.json` file contains this: `"start_url": "/"`

However, if your site is deployed into a non-root location (e.g., `http://example.com/mysubdir/`), then this incorrectly resolves to `http://example.com/`.

To fix this, we need to change it to `"start_url": "./"`. As per the spec, relative URLs are resolved relative to the location of `manifest.json`, so this would be correct in all cases.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/19898
