### ISSUE TITLE
iOS 13 Blazor Server Web API Calls

### ISSUE THREAD

**Issue by loganmarshall1** [dotnet/aspnetcore#19896]
### Describe the bug
I have a Blazor Sever Application deployed to Azure App Services that have a few components that make a web api call via dependency service injection in the .razor page.  The Web Api Call works on edge, edgium, chrome, firefox, andriod, however not iOS 13 Safari.  Very weird as it returns the data fine on ALL other plartforms. I saw a similar blazor bug for WASM for iOS 13, but assumed since that work around was mono/client blazor related, it maybe different issue.  I can't find anything on the web for this issue, its very strange.  any help would me amazing.

### To Reproduce
make any blazor server application that has a web api calling component and view on iOS 13 Safari it wont load the data.  

### Further technical details
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Visual Studio 2019 Professional 16.4.6

**Comment by javiercn** [comment]
@loganmarshall1 thanks for contacting us.

I can't see how it would matter on a server-side context whether you are making an API call from an app that is running on Edge vs an app that is running on IOS.

Could you provide a minimal repro project that showcases your issue so that we could investigate?

**Comment by loganmarshall1** [comment]
Hi The @javiercn !

It would be quite complicated and take a lot of time to make this project into a isolated generic problem project.  Since it uses Azure App Service x2, one for front end, one for api, Azure b2c for authenication, azure sql and azure keyvault. the api calls use JWT bearer to call the secure api. In order for you to see this issue you'd have to deploy to a similar infrastructure architecture and connect via ios safari 13.  

Would a video help, certain files, anything else I can give you to help? Im also thinking that its not JUST api calls but other injected  services.  I'll also get back to you if IOS 12 works fine or not.

**Comment by mkArtakMSFT** [comment]
Thanks @loganmarshall1.
We don't have time to debug custom applications. Unfortunately we won't be able to move forward here without a minimal repro app. If you are able to provide one, we will definitely investigate it.

We wouldn't expect client OS to affect this in any way.

**Comment by loganmarshall1** [comment]
Okay I'll work on a small example repo and attach, thanks,

Logan

On Mar 17, 2020, at 12:39 PM, Artak <notifications@github.com> wrote:

﻿

Thanks @loganmarshall1<https://github.com/loganmarshall1>.
We don't have time to debug custom applications. Unfortunately we won't be able to move forward here without a minimal repro app. If you are able to provide one, we will definitely investigate it.

We wouldn't expect client OS to affect this in any way.

**Comment by loganmarshall1** [comment]
Found the bug!

Was Content Security Policy on my blazor server app was interpreted with different results on ios Safari.

Specifically ios Safari with blazor, signal R, if using csp you need to add connect-src 'ws:' 'wss:';

Working now, not a blazor bug, csp + signal R csp implementation variance on ios 13+ Safari.

Thanks,

Logan

On Mar 17, 2020, at 1:06 PM, Logan Marshall <logan.marshall@live.ca> wrote:

﻿ Okay I'll work on a small example repo and attach, thanks,

Logan

On Mar 17, 2020, at 12:39 PM, Artak <notifications@github.com> wrote:

﻿

Thanks @loganmarshall1<https://github.com/loganmarshall1>.
We don't have time to debug custom applications. Unfortunately we won't be able to move forward here without a minimal repro app. If you are able to provide one, we will definitely investigate it.

We wouldn't expect client OS to affect this in any way.

**Comment by mkArtakMSFT** [comment]
Thanks @loganmarshall1.
Glad you've got this sorted out!
