### ISSUE TITLE
Consider exposing IWebAssemblyHostEnvironment from WebAssemblyHostBuilder

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19900]
As part of the config change, we added a `IWebAsemblyHostEnvironment` to Blazor that exposes the host's environment: https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Hosting/IWebAssemblyHostEnvironment.cs. The type is added to DI which makes it difficult to use as part of startup code. We should consider additionally exposing it as part of `WebAssemblyHostBuilder` as a property.

In addition, the host environment is also missing convenience extension methods such as `IsDevelopment`, `IsProduction` etc. We should consider porting those over.

**Comment by javiercn** [comment]
Yes plz

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/20008
(@captainsafia or if there was anything remaining, please let us know)
