### ISSUE TITLE
Incremental updating of Semantic Colors

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#19902]
We took care of adding Semantic Colorization in https://github.com/dotnet/aspnetcore/issues/14270, but as of right now it updates the entire document after one change, we should use `provideDocumentSemanticTokensEdits` to respond with only the changes.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg is this equivalent to https://github.com/dotnet/aspnetcore/issues/21846 ?

**Comment by ryanbrandenburg** [comment]
Yes. Closing in favor of that.
