### ISSUE TITLE
Failed to find a valid digest in the 'integrity' in Blazor WASM

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#19907]
After upgrading the project to the latest preview 3.2.0 preview-2.2  from version 3.1 preview I got this error.

```
Failed to find a valid digest in the 'integrity' attribute for resource 
'https://draw2mesh.netlify.com/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js' 
with computed SHA-256 integrity 'FJC7gQVpQ5ZmLsci9Oxg/MIH96sVbWXaxI5G3fM7Doc='.
 The resource has been blocked.
```

The project is hosted at https://github.com/sps014/DrawToMesh

When hosting on Netlify I get this error, in debug mode, it works fine.

Please help me I can't deploy with this bug.
Any temporary workaround will work for now.

**Comment by sps014** [comment]
I also have tried ```integrity=""``` but no luck.

**Comment by pierre3** [comment]
I also ran into the same problem.

I hosted at GitHub pages https://line-developer-community.github.io/liff-client-csharp .

![image](https://user-images.githubusercontent.com/1255359/76849935-b255d800-6889-11ea-92d5-7b6360d48237.png)

**Comment by sps014** [comment]
Hope they help us resolve this issue.
Dev Please help it's urgent.

**Comment by campersau** [comment]
Might be a duplicate of https://github.com/dotnet/aspnetcore/issues/19775, https://github.com/dotnet/aspnetcore/issues/19796

**Comment by sps014** [comment]
Replaced content of the ```.gitattributes``` file with ```* binary``` and deleted everything from publish folder except this file and republished and pushed everything is working fine.
