### ISSUE TITLE
git clone issue 

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#19905]
with the consolation of github repo as part of .net 5 the issue #11913 has become more regular and now ever more prevent, preventing successful cloning of the large code base and history.  Please work with teams and or provide guidance in the readme on how developers should clone when seeing the issue

**Comment by javiercn** [comment]
Thanks for contacting us @grahamehorner.

@dotnet/aspnet-build do you have thoughts on this?

Also @Pilchie for awareness.

**Comment by dougbu** [comment]
I assume you're working on a Windows client because I haven't seen similar issues on macOS or Linux. Are you using an SSH or HTTPS URI?

If SSH, using a newer SSH client may help. I've had pretty good luck with both the version shipped with Git for Windows (8.2p1 last I looked) and the latest from https://github.com/PowerShell/Win32-OpenSSH/releases (v8.1.0.0p1-Beta right now). Either way, you may need to update your `$env:Path` and the `core.sshCommand` setting in `git config --global`. (The Git for Windows client seems to hit fewer EOF errors while the Win32-OpenSSH client can be configured to preserve your keys across reboots.)

If HTTPS, you may want to increase `git config --global` buffer sizes e.g. `http.postbuffer=1048576000`.

**Comment by grahamehorner** [comment]
@dougbu yes this issues is from a window platform; using HTTPS changing the http.postbuffer as shown above made no difference. I will trying a few more of the suggestion and give feedback

**Comment by grahamehorner** [comment]
FYI, git version 2.25.1.windows.1

**Comment by grahamehorner** [comment]
FYI, using WSL with Ubuntu has the same issue but gives additional information in the error 

> Cloning into 'aspnetcore'...
> remote: Enumerating objects: 92, done.
> remote: Counting objects: 100% (92/92), done.
> remote: Compressing objects: 100% (73/73), done.
> error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
>

**Comment by Pilchie** [comment]
@grahamehorner I'm not aware of anyone else having similar issues.  I clone AspNetCore on both Ubuntu (in WSL) and natively on Windows regularly, on multiple machines, and have never seen any issues.

It really sounds as if something might be problematic in your network between your endpoint and GitHub.

**Comment by grahamehorner** [comment]
@Pilchie like wise I have multiple systems all showing the same issue, and have used multiple networks and ISPs to verify that it not a network issue or a machine issue.  I am able to clone a number of other github projects (smaller in size/history) without issue.

**Comment by grahamehorner** [comment]
@Pilchie you may be correct after all just tried the SSH protocol using git clone ssh://git@ssh.github.com:443/dotnet/aspnetcore.git and the clone was successful?

it would be good if this is referenced in a README as a possible issue/gottya so others
can avoid/try if the cloning over HTTPS has issues? thinking this must be some ISP proxy/caching/buffering issue... only showing up with larger GIT repos :'(

**Comment by dougbu** [comment]
@grahamehorner the main ./README.md file isn't the place for information specific to cloning and building this repo. Ideally https://github.com would have some overall notes about large repos and cloning / fetching from them. I believe I've only seen this type of info on community pages and in `git` or Git for Windows issues.

Feel free to send a PR updating ./docs/BuildFromSource.md Reference this issue in your commit description and we'll consider this a docs issue.

Another option would be to file an issue on GitHub itself. I am not sure how to make GitHub suggestions these days (@NTaylorMullen you've done this IIRC -- recommendations?) but https://help.github.com/en/github/getting-started-with-github/troubleshooting-connectivity-problems (which already suggests switching URI protocols) and https://help.github.com/en/github/creating-cloning-and-archiving-repositories/https-cloning-errors look like good pages for more information.

Finally, you could follow up at https://github.com/git-for-windows. They may already have more general issues and documentation than the SSH-specific https://github.com/PowerShell/Win32-OpenSSH/issues/1322

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen you've done this IIRC -- recommendations?

Lol my attempt at doing this has always been in the twitter stratosphere by reaching out to folks on the team 🤣. Not sure if there's a "file an issue" approach.

**Comment by Pilchie** [comment]
Email: support@github.com is the documented way.

**Comment by dougbu** [comment]
34a114530dd5

**Comment by dougbu** [comment]
Questions answered here and in 34a114530dd5.
