### ISSUE TITLE
Changing base href in web assembly blazor has undesired results

### ISSUE THREAD

**Issue by jDover01** [dotnet/aspnetcore#19928]
### Describe the bug
After changing the base href tag in web assembly client project authentication no longer works correctly.

### To Reproduce
Create new web assembly project change base href to "/client/"  in index.html and add app.UsePathBase("/client") to server-side project startup.cs file

client now receives a 401 after successful login

### Further technical details
- Blazor WebAssembly 3.2.0 Preview 2
- Visual Studio 2019 16.4.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Have you tried to use `/client/` instead?

**Comment by jDover01** [comment]
If you are referring to server-side blazor app.UsePathBase("/client/"), yes. I have tried that as wel, with no good resultsl. It seems to be a problem with the built in Identy Server URI's and callbacks, once the base uri has changed. IMO.

**Comment by jDover01** [comment]
I have also tried using "/client/" on web assembly blazor client but directly from the docs it states to not include the trailing slash. But no, unfortunately this does not solve the problem.

**Comment by jDover01** [comment]
![authorizeConsoleException](https://user-images.githubusercontent.com/28901954/77079546-74ee6900-69b5-11ea-8061-8008c5c73aab.PNG)

My network capture console errors after successful login and trying to call  var tokenResult = await AuthenticationService.RequestAccessToken(); inside fetchdata.razor page.

**Comment by jDover01** [comment]
It is also worth noting that I also tried "dotnet run --pathbase=/client" and recieve same results as above after successful login.

**Comment by javiercn** [comment]
> dotnet run --pathbase=/client

This is not a thing in asp.net core apps afaik. You need to explicitly map the path.

**Comment by jDover01** [comment]
Correct. Yes, I have explicitly set the base path on client and server blazor project, but thought I would try the command and see if there was any different results. But unfortunately no.

**Comment by javiercn** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/20191

There was an issue in the way the middleware was ordered that was causing the issuer URI to be computed incorrectly, causing the tokens to be rejected.

**Comment by jDover01** [comment]
Ahh. Nice! Thank you for this!! =) When can I expect a new release to update to?
