### ISSUE TITLE
Assemblies shared by the server and Blazor project get removed during publish

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19926]
This is a problem in the Razor SDK, but appears more readily with in the Blazor hosted template. Steps to reproduce:

dotnet new blazorwasm -ho -o BlazorClient
cd BlazorClient
Cd server
dotnet publish
cd ./bin/Debug/netcoreapp3.1/publish
dotnet BlazorClient.Server.dll

An assembly specified in the application dependencies manifest (BlazorClient.Server.deps.json) was not found:
package: 'BlazorClient.Shared', version: '1.0.0'
path: 'BlazorClient.Shared.dll'

**Comment by danroth27** [comment]
Possibly the same issue:
- https://github.com/dotnet/aspnetcore/issues/19799
- https://github.com/dotnet/aspnetcore/issues/19768

Some similar sounding issues reported on the announcement blog: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/#comment-1555

**Comment by isc30** [comment]
Hi, when is this shipping out?

**Comment by danroth27** [comment]
@isc30 This has been addressed for the upcoming [3.2 Preview 4 release](https://github.com/dotnet/aspnetcore/milestone/82), which we expect to release on April 16th.

**Comment by boindiil** [comment]
Problem seems to be solved for us with 3.2.0-preview4.20210.8
