### ISSUE TITLE
asp-action and asp-controller not resolving route with attribute routing.

### ISSUE THREAD

**Issue by ramanmittal** [dotnet/aspnetcore#19927]
I am working on a multi-tenant application in which I am using routing like this
` endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{tenant}/{controller=Home}/{action=Index}/{id?}");`
I have an action in which I am applying attribute routing.
`public class DefaultController : Controller
    {
        [Route("{tenant}/asdf")]
        public IActionResult Index()
        {
            return Content("asdf");
        }
    }`
The issue is that when I creating a action link in a Razor view using tags
`<a asp-action="Index" asp-controller="Default">asdf</a>`
It is generating the wrong output `<a href="/a1/Default">asdf</a>` 
But it should generate `<a href="/a1/asdf">asdf</a> `

**Comment by javiercn** [comment]
@ramanmittal thanks for contacting us.

@rynowak is this an ambient values thing? I'm not sure why the conventional route would be picked over the attribute route and if the attribute route should be picked over it.

Is the conventional route mapped with a higher order than the attribute route?

**Comment by rynowak** [comment]
If you turn logging up to debug for `Microsoft` there's a lot more info about what's going on. This is almost certainly relying on the ambient values behavior that changed in 3.0. We're planning to add a feature for scenarios like this. 

Attribute routes will (by default) have higher order than conventional routes.

**Comment by ramanmittal** [comment]
> If you turn logging up to debug for `Microsoft` there's a lot more info about what's going on. This is almost certainly relying on the ambient values behavior that changed in 3.0. We're planning to add a feature for scenarios like this.
> 
> Attribute routes will (by default) have higher order than conventional routes.

I observed that this issue is occurring when I am applying {tenant} param in route templates. When I am not using then it is giving priority to the attribute route and generate correct URLs.
