### ISSUE TITLE
Avoid duplicating the published dlls in a blazor webassembly project

### ISSUE THREAD

**Issue by waelkdouh** [dotnet/aspnetcore#19921]
I noticed when I publish a balzor webassembly project all the dlls are duplicated. One copy lives at the root level of the published folder and another is found under the wwwroot/_framework forlder. I understand that one only needs to copy the content of the wwwroot folder to the live server but I find it confusing for new comers who would assume that they would need to push the dlls to the server not knowing that they already exist under wwwroot/_framework.

**Comment by javiercn** [comment]
@waelkdouh thanks for contacting us.

This is an area where we can make improvements,  but it is problematic since it requires "fighting the build system" and the ROI for it is relatively low.

**Comment by SteveSandersonMS** [comment]
Tracked by https://github.com/dotnet/aspnetcore/issues/17018

**Comment by javiercn** [comment]
Closing in favor of the existing tracking issue.
