### ISSUE TITLE
Rename Razor Component to Blazor Component in Visual studio item.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#19920]
As **Razor Component (currently)** is the building block of **Blazor app** so it's much better to call it **Blazor Component** instead of Razor Component which denotes that this is tightly related to **Blazor**. On the hand the word **Razor** is related to every kinds of View in ASP.NET and ASP.NET Core.

Here it is: [Razor Component in Visual Studio](https://imgur.com/1PPpZDY)

Thank you.

**Comment by javiercn** [comment]
@TanvirArjel thanks for contacting us.

We normally refer to things as Blazor when we talk about the application model (Server-side, WebAssembly, etc) and to "Components" when we talk about the building blocks. 

We don't intend for the concept of a Razor Component to exclusively refer to Blazor as we might use it in other contexts in the future.

**Comment by TanvirArjel** [comment]
> We don't intend for the concept of a Razor Component to exclusively refer to Blazor as we might use it in other contexts in the future.

Even if you use Razor Component in the other contexts in the future, it will be used for providing Blazor functionality, isn't it?

**Comment by javiercn** [comment]
Not necessarily

**Comment by TanvirArjel** [comment]
Okay! Thank you.
