### ISSUE TITLE
Fix VSCode functional tests

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#19937]
The tests are currently broken due to issues with ConfigureRazorDevMode command. 
Example failure,
https://dev.azure.com/dnceng/internal/_build/results?buildId=562708&view=logs&j=b36057ec-f3d9-56c1-75f0-6724e6013c1d&t=f255f103-e1d6-500a-990a-dfc4094ee936&l=77

**Comment by NTaylorMullen** [comment]
@TanayParikh assigning this to you for the interim since it falls in line with the 24hr timebox rotation 😄
