### ISSUE TITLE
Build from source code faild to get https://dot.net/v1/dotnet-install.ps1 

### ISSUE THREAD

**Issue by xyz0822** [dotnet/aspnetcore#19947]
Dear all ,when i started to build source code from commandline ,it is falid to donwload **https://dot.net/v1/dotnet-install.ps1**  
does "https://dot.net/v1/dotnet-install.ps1" it has been  removed?

**Comment by javiercn** [comment]
@xyz0822 thanks for contacting us.

@dotnet/aspnet-build any ideas?

**Comment by wtgodbe** [comment]
Hmm, I am able to download the file without issue - occasionally there are networking issues or transient problems with that script, are you still having the issue?

**Comment by SIkebe** [comment]
Proxy issue?
#12499

**Comment by xyz0822** [comment]
Thanks for your replay!
i found it can not download from my phone network or company network even in my home network, it turned  out to be a area net work problem from china.
