### ISSUE TITLE
Use DI to resolve IHostApplicationLifetime is invalid

### ISSUE THREAD

**Issue by zhaoqinghai** [dotnet/aspnetcore#19943]
![image](https://user-images.githubusercontent.com/26404526/76920212-deaf3a00-6905-11ea-9688-e2a4948beb42.png)
ApplicationStopped and ApplicationStopping callback is not excute when i exitprocess, but when i use Configure(IApplicationBuilder app, IHostApplicationLifetime applicationLifetime) is run ok

**Comment by davidfowl** [comment]
How do you exit the process?

**Comment by zhaoqinghai** [comment]
I close browser window this process is exited

**Comment by zhaoqinghai** [comment]
it is my fault, i can not reappear
