### ISSUE TITLE
[Question] [SignalR] Possible to auto-failback to websockets after failover to long polling?

### ISSUE THREAD

**Issue by GFoley83** [dotnet/aspnetcore#19946]
Title says it all. Can't seem to find any information in this.

I have failover to long polling which kicks in if websockets become unavailable. It seems that the SDK doesn't ever try to return to using websockets once it has moved to long polling. 

The only work-around that I can see is to disconnect and reconnect to get back to using websockets or am I missing something?

**Comment by davidfowl** [comment]
The SignalR does not try to connect to websockets after long polling successfully connects. That would be a cool feature though but it isn’t something we have planned and it would have to be opt-in.

**Comment by GFoley83** [comment]
Thanks David. Appreciate the feedback.
