### ISSUE TITLE
Transparently call server side class/methods in client side Blazor Wasm

### ISSUE THREAD

**Issue by hxmcn** [dotnet/aspnetcore#19942]
When we take server-side Blazor solution, it's easy to call any class/method since all C# code are running in server.
However, if we take client side Blazor (wasm), It's not as easy as server-side. We need do:
  (1)Define and implements business class; (2) Expose business class as web-api ; (3)In client side wasm class, use HttpCLient.PostAsync()  to call the above web-api, and serialize/deserialize parameter/return result may handle by developers.
The above process to call server-side methods is inefficient, tedious, developers need to repeating one by one, 

**So, my question: Can there be a better and elegant way to call server-side business code/class from wasm?**

Some ideals:
(1) Totally transparently, the client side Wasm code can reference server side project(DLL) and call it just as 'local' class. This may need compiler or some underling components to support.
(2)Automatically generate proxy class for Wasm codes. Just like web-service proxy class, we need add attributes for server side classes/mehtods, once we save the .cs file, VS's plugin will automatically generate a proxy class in the client side.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something specific to Blazor. We have some mechanisms in place for generating proxy code. Have a look at https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.1
