### ISSUE TITLE
[Routing] Literal value duplicated in the url part prevents matching

### ISSUE THREAD

**Issue by sl-florentbrouca** [dotnet/aspnetcore#19951]
Hi,

I couldn't find any additional info about my issue so I'll post it here : 

My routing is unable to match a url that includes (for a url part) the literal value inside the non-literal part too. 

Example : (I modified a test here Routing\test\Microsoft.AspNetCore.Routing.Tests\Patterns\RoutePatternMatcherTest.cs to observe it)

``` C#
// Arrange
var matcher = CreateMatcher("{controller}/myliteral-{action}/{id}");

var values = new RouteValueDictionary();

// Act
var match = matcher.TryMatch("/Bank/myliteral-myliteral-DoAction/123", values);
```

I would indeed expect the {action} to match "myliteral-DoAction" but it does not match at all. 
I debugged quickly and it could come from the use of LastIndexOf in the RoutePatternMatcher but I guess this would create further bugs.

Regards,
Florent

**Comment by rynowak** [comment]
Hi @sl-florentbrouca - here's an explanation of how complex segments work. https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1&branch=pr-en-us-16456#complex-segments

They don't really work when your delimiter token (`myliteral-` in your case) also can appear inside the part of the URL you want to see captured by a parameter (`myliteral-DoAction`) in your case. 

There are two strategies for how a system like this can work:
- Matching can be *greedy* and match the largest possible token
- Matching can be *non-greedy* and match the smallest possible token

The decision was made when this feature was designed to apply non-greedy matching (from right to left) - see the example in the linked doc. This behavior is very old and it is something we're very unlikely to change.

The only real solution to this today is to use a normal parameter segment, and do the parsing in another layer of the system.

**Comment by sl-florentbrouca** [comment]
Hi @rynowak ,

Thanks for taking the time to explain it. I was pretty much sure this was by design but could not find the information to be sure. Anyway thanks a lot, we handled it differently, works fine !
