### ISSUE TITLE
dotnet build Blazor does not respect WarningsAsErrors for "unrecognized components"

### ISSUE THREAD

**Issue by sylvainonweb** [dotnet/aspnetcore#19952]
### Describe the bug
I have a component which was called TypeMesureListView This component is used in a lot of places.
I decided to rename it but after recompiling Visual Studio didn't show me warnings or errors at all.

![Sans titre](https://user-images.githubusercontent.com/37140661/76963033-9fdaad80-6920-11ea-8b7d-e278e9779cae.png)

Please, don't tell me that this is resolved by design as #19791 because It's really a big problem for developpers to not being able to trust the compiler on these kind of errors

### Further technical details
ASP.NET Core version : 3.1

Output of dotnet --info

.NET Core SDK (reflecting any global.json):
Version: 3.1.101
Commit: b377529961

Runtime Environment:
OS Name: Windows
OS Version: 10.0.18362
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
Version: 3.1.1
Commit: a1388f194c

.NET Core SDKs installed:
1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
1.0.1 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.0.3 [C:\Program Files\dotnet\sdk]
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.200 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.1.600 [C:\Program Files\dotnet\sdk]
2.1.601 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.604 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
2.1.800 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.202 [C:\Program Files\dotnet\sdk]
2.2.204 [C:\Program Files\dotnet\sdk]
2.2.300 [C:\Program Files\dotnet\sdk]
2.2.301 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]
3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version : VS 2019 16.4.5 (Windows)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
I was able to reproduce this once but then after attempting to reproduce after that I can't. @sylvainonweb if you re-build you get the warning right?

**Comment by sylvainonweb** [comment]
@NTaylorMullen if I re-build, I get a warning.
But, why isn't it an error because for sure, when user will reach the page, it will crash, no ?

**Comment by NTaylorMullen** [comment]
> But, why isn't it an error because for sure, when user will reach the page, it will crash, no ?

Nope, HTML supports random tag names. So in the case that you do nothing about the warning the page will render the tag as-is.

**Comment by sylvainonweb** [comment]
@NTaylorMullen Please, don't close these issue=>, it's really a big problem. I (and probably I'm not alone) would like to be able to trust the compiler for these kind of errors.

> or instance imagine another framework creating a special tag name that's handled on the client by some JS framework. We wouldn't want to break those scenarios.

I'm talking here about Visual Studio compilation. So, I don't really understand your remark. I read few months ago a note from Steve Sanderson says that the framework can distinguish between Blazor Component and html tag using case (Pascal case for component and camel case for html tag).

Wouldn't it be possible to use it here ?

**Comment by NTaylorMullen** [comment]
> Wouldn't it be possible to use it here ?

The framework can distinguish between Blazor Component's and tags however it has no concept if another framework is lighting up a different tag. This is why we flag any pascal cased HTML tag that is not a Blazor component as a warning; we specifically do not mark it as an error though. You can always turn on warnings as errors in your csproj though.

**Comment by sylvainonweb** [comment]
@NTaylorMullen 
If I turn this warning as error :

**If the file isn't opened**
- In Output pane, no warning/error
- In Error List pan, no warning/error
-  it continues to build successfully

**If the file is opened**
-  In Output, pane it marks as a warning
![2](https://user-images.githubusercontent.com/37140661/77140025-75036d00-6a78-11ea-9cff-fdd60b253b8e.png)
-  In Error List pane, it marks as an error
![1](https://user-images.githubusercontent.com/37140661/77140083-b09e3700-6a78-11ea-8b8a-16ddeb180f39.png)
-  it continues to build successfully


**=> the compiler doesn't break for this kind of errors**

**Comment by NTaylorMullen** [comment]
Hah! That's definitely an interesting experience isn't it? @tmat is it Roslyn who lifts errors from the build output into the error list and controls build success or not?

**Comment by sylvainonweb** [comment]
Interesting experience if and only if issue is fixed. As you can see, I'm a pragmatic guy
Glad to see you like it.

**Comment by sylvainonweb** [comment]
Any news about this issue ?

**Comment by sylvainonweb** [comment]
@NTaylorMullen Is it normal that this issue is set as Resolved and ResolvedByDesign ?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Is it normal that this issue is set as Resolved and ResolvedByDesign ?

Not at all, just updated 😄

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen what's the next action pending here? If this is a bug, is this on our side? I would like to understand the user impact a bit better.

**Comment by NTaylorMullen** [comment]
I investigated this and it is due to an inconsistency in designtime/runtime tooling. 

@sylvainonweb would you mind providing a repro project?

**Comment by sylvainonweb** [comment]
Done
[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/4573604/BlazorApp1.zip)

**Comment by NTaylorMullen** [comment]
@sylvainonweb with that repro project what are the steps to encounter the error you're seeing? I tried doing a few steps myself and things worked as expected

**Comment by sylvainonweb** [comment]
@NTaylorMullen 
The component is called AComponentUsedInManyPlaces but rhe one used in Index.razor missed the first letter (A) so it should not compile (because I configure all warnings as errors in properties of the project) but 

1) if I close all files and rebuild -> Build Succeeded

2) If I open the Index.razor and rebuild -> error is displayed in Error List pane but Build Succeeded

**Comment by NTaylorMullen** [comment]
Thanks @sylvainonweb for the repro, i can reproduce!

For the future bug fixer. This is due to how we compile Blazor/Razor applications. We don't forward along the WarningsAsErrors flag from MSBuild into the Razor compiler. This means the Blazor warning for "Unrecognized component" gets emitted as a warning at build time and then WarningsAsErrors MSBuild flag is never inspected as a way to elevate the error to an error instead of a warning. In the IDE Roslyn does this on our behalf.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by sylvainonweb** [comment]
@mkArtakMSFT 

Seriously ? This kind of errors is the reason I use a typed language as C#. If I can't trust VisualStudio tools to let me know if my solution has errors, there is no benefit to use C# instead of javascript.

For me (and I think for all people developping using C# for the same reason has me), this issue is essential.

**Comment by pranavkm** [comment]
This is resolved as part of the source generator work that was done for 6.0 apps. Unrecognized components produce a build warning or an errors if `TreatWarningsAsErrors=true` both in VS and the CLI. These warnings / errors are treated the same as any other compiler warning / error.

@NTaylorMullen there's a fun issue with tooling where the warning / error is duplicated once you build:

![image](https://user-images.githubusercontent.com/174281/126691010-10339d08-e251-4e2b-98ad-7a0752c2029c.png)

Could you file a separate issue to track addressing it if there isn't one already?

**Comment by NTaylorMullen** [comment]
> Could you file a separate issue to track addressing it if there isn't one already?

We have this fixed behind a feature flag already actually 😄
