### ISSUE TITLE
Microsoft.AspNetCore.Hosting.WindowsServices 3.x not usable in a .Net standard project

### ISSUE THREAD

**Issue by gmihaescu** [dotnet/aspnetcore#19950]
Attempting to upgrade to Microsoft.AspNetCore.Hosting.WindowsServices ver 3.xx in my .Net standard 2.1 project I get the following error:

NU1202: Package Microsoft.AspNetCore.Hosting.WindowsServices 3.1.2 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.AspNetCore.Hosting.WindowsServices 3.1.2 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)

Why is this? I could use Microsoft.AspNetCore.Hosting.WindowsServices ver 2.2. before in a .Net standard 2.0 project.

**Comment by shirhatti** [comment]
From 3.0 onwards, all ASP.NET Core packages target `netcoreapp3.0`. This is a known change from ASP.NET Core 2.1.
