### ISSUE TITLE
Kestrel Server Unable To Start

### ISSUE THREAD

**Issue by EngineerTryingToCode** [dotnet/aspnetcore#19953]
Hello,

I have a strange issue going on regarding Kestrel on my machine. I am currently trying to develop a ASP Net Core application using razor pages for a project I am working on. I am new to development in ASP Net Core entirely and am currently trying several tutorials to build my knowledge. Every time I attempt to troubleshoot using Kestrel rather than IIS, Kestrel is unable to start. Weirdly, I went with an older version of Asp Net Core application and the problem went away. However, I would prefer to use the most up-to-date and therefore longest supported version. I just started a brand new web app while following this tutorial:

https://youtu.be/X75Z8Eq879c

When they run their app at the 34minute and 50 second mark, i get this error:

![c819330dedf50d01e9a43deefa2c965bcf3c2769](https://user-images.githubusercontent.com/62211948/76963590-a43ea080-68f7-11ea-9ee6-98591718e91a.png)

Does anyone know what is going on here? I have verified that nothing is bound to the port it is trying to use which appears to have been a common issue for others. Any help would be tremendous.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This tutorial is using .NET Core 2.0, which is out of support for some time now.
You can get started with the current LTS (Long Term Servicing) release using the following documentation: https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=windows

The problem simply scanning through the screenshot in that video (at that time) is that there were several breaking changes between .NET Core 2.0 and the current one (3.1) which I think you're running on.
If, however, you would like to use a video tutorial instead, look for ASP.NET Core 3.1 specific tutorials: https://www.youtube.com/results?search_query=aspnet+core+3.1+tutorial

This is actually something we plan to cover in our documentation eventually, to help customers discover version-specific good video materials. @Rick-Anderson, @scottaddie here is another example where version-specific video content would be useful.

**Comment by EngineerTryingToCode** [comment]
Unfortunately this isn't the cause, I also used Visual Studio to create an ASP.Net Core project using 3.1 and i got the same error through the visual studio compiler straight out of the box when trying to debug with Kestrel.  If i used IIS it worked fine.  However, when I started a project using 2.0, i was able to debug with kestrel.  No clue why but I cannot find a solution anywhere online for this.  It seems like a lot of people have issues with the port being tied up but i have verified that is not the case in my situation.

**Comment by EngineerTryingToCode** [comment]
> Thanks for contacting us.
> This tutorial is using .NET Core 2.0, which is out of support for some time now.
> You can get started with the current LTS (Long Term Servicing) release using the following documentation: https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=windows
> 
> The problem simply scanning through the screenshot in that video (at that time) is that there were several breaking changes between .NET Core 2.0 and the current one (3.1) which I think you're running on.
> If, however, you would like to use a video tutorial instead, look for ASP.NET Core 3.1 specific tutorials: https://www.youtube.com/results?search_query=aspnet+core+3.1+tutorial
> 
> This is actually something we plan to cover in our documentation eventually, to help customers discover version-specific good video materials. @Rick-Anderson, @scottaddie here is another example where version-specific video content would be useful.

Unfortunately this isn't the cause, I also used Visual Studio to create an ASP.Net Core project using 3.1 and i got the same error through the visual studio compiler straight out of the box when trying to debug with Kestrel. If i used IIS it worked fine. However, when I started a project using 2.0, i was able to debug with kestrel. No clue why but I cannot find a solution anywhere online for this. It seems like a lot of people have issues with the port being tied up but i have verified that is not the case in my situation.

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  wrote

> The problem simply scanning through the screenshot in that video (at that time) is that there were several breaking changes between .NET Core 2.0 and the current one (3.1) which I think you're running on.

That's why we don't do video. It's quickly out of date. We have zero detectable  customers interested in ASP.NET Core 2.0

**Comment by EngineerTryingToCode** [comment]
> @mkArtakMSFT wrote
> 
> > The problem simply scanning through the screenshot in that video (at that time) is that there were several breaking changes between .NET Core 2.0 and the current one (3.1) which I think you're running on.
> 
> That's why we don't do video. It's quickly out of date. We have zero detectable customers interested in ASP.NET Core 2.0

Yeah understandable, it wasn't the code that broke in this case though.  Confirmed because i can open a brand new project in Visual Studio for ASP.Net Core 3.1 and out of the box I have issues with Kestrel debugging.  So independent of this I have issue straight out of the box and no clue why.  Everything I have found online was related to the port being in use but this is also not the case as i checked it.
