### ISSUE TITLE
blazor server project with authentication application hangs when a password ending with "point" character entered in register forms as password.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19965]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/704102/blazor-server-project-with-authentication-applicat.html)._

---
### What steps will reproduce the problem?

1. Start application.
2. Click register.
3. Enter a valid e-mail for example @yyy** .
4. Enter a password  that ends with a point character for both password fields.  For example **2395iSta.** 
note the  point character at the end.
5. Click register.
6. application freezes forever without throwing any error , exception.

### What is the expected output? What do you see instead?
Application should register the user and return to the page that welcomes  the registered user and shows the user as logged on.

Please provide any additional information below.

---
#### Visual Studio Feedback System on 8/22/2019, 03:42 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 8/23/2019, 00:19 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Gave this a quick try, I can't reproduce it.

Can you provide a minimal repro project that showcases the issue? With explicit values for email and password, since I tried with the password value you provided and it just works fine.
