### ISSUE TITLE
Define and test the end-to-end scenarios for HTTP/3 preview

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#19973]
Epic https://github.com/dotnet/aspnetcore/issues/15271

HTTP/3 support will be in *preview* at 5.0 GA. We should spend a few cycles defining the end-to-end scenarios that we want to "work" (to a preview level) and make sure they work.

**Comment by jkotalik** [comment]
Closing as this applies to 5.0, will refile issues for 6.0.
