### ISSUE TITLE
Flaky test when running with unlimited threads

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#19971]
If you run the test with the following xunit.runner.json settings it becomes flaky.
```json
{
  "maxParallelThreads": -1
}
```

Test `InvokeAsync_FuncTaskT_CanRunAsynchronously_WhenBusy`
https://github.com/dotnet/aspnetcore/blob/c74e9efd0e6ea5b4d6737d23b92042772a50a249/src/Components/Components/test/Rendering/RendererSynchronizationContextTest.cs#L697

Fails with: `Assert.NotSame() Failure` when comparing the thread the callback ran on and the thread the callback was registered from.

@rynowak says this is likely a bug in the test. I haven't disabled it yet because this probably wont happen in normal test runs, unless we increase xunit threading.

**Comment by mkArtakMSFT** [comment]
We'll handle this when we actually face this issue. As of now this is not a real concern.
