### ISSUE TITLE
Fix and unskip tests skipped in https://github.com/dotnet/aspnetcore/pull/19978

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#19979]

**Comment by mkArtakMSFT** [comment]
@javiercn I've skipped these tests to unblock the builds. Can you please prioritize this issue over any other work to make sure the relevant data is still available to debug, if necessary. Here is the build where we've faced this issue: https://dev.azure.com/dnceng/internal/_build/results?buildId=562880

**Comment by BrennanConroy** [comment]
Also some skipped in https://github.com/dotnet/aspnetcore/pull/20261

**Comment by pranavkm** [comment]
Do we know what caused the tests to hang (i.e. build logs \ dumps etc)? These tests aren't fundamentally different from some of the other template tests that are currently running just fine. I don't mind looking at why the tests don't time out more readily, but that's possibly a lot more work than root causing this.

**Comment by BrennanConroy** [comment]
Might need to give up on root causing this for now as it's been over a month so the builds are gone.

These will be unquarantined soon anyways probably because they've been passing for a month.

**Comment by pranavkm** [comment]
These ones have the double whammy of being skipped and quarantined 😕

**Comment by BrennanConroy** [comment]
Oh, that's unfortunate.

**Comment by docmaster2** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="false">
      <remove name="WebDAVModule" />
    </modules>
    <security>
      <requestFiltering>
        <requestLimits maxUrl="8192" maxQueryString="4096" maxAllowedContentLength="512000000" />
      </requestFiltering>
    </security>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="outofprocess" />
  </system.webServer>
  
  
  <location path="index.html">
    <system.webServer>
      <httpProtocol>
        <customHeaders>
          <add name="Cache-Control" value="no-cache" />
        </customHeaders>
      </httpProtocol>
    </system.webServer>
  </location>
  
  
  <location path="api">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="false" />
        </authentication>
      </security>
    </system.webServer>
  </location>
  
  
  <location path="api/account/login/windows">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
    </system.webServer>
  </location>
  
  <location path="api/account/register/windows">
    <system.webServer>
      <security>
        <authentication>
          <windowsAuthentication enabled="true" />
If I understand correctly, navigation does not fail us.
        </authentication>
      </security>
    </system.webServer>
  </location>
  
</configuration>
