### ISSUE TITLE
Compiler error re nullability in blazor component

### ISSUE THREAD

**Issue by joshlang** [dotnet/aspnetcore#19974]
Using aspnetcore5.0, blazor 3.2.0 preview 1

Add a new razor component, like this:
```
@typeparam TItem

@code {

    IEnumerable<TItem>? Items;

    void Blarg()
    {
        var item = Items?.FirstOrDefault();
    }
}
```

I get the error `Operator '?' cannot be applied to operand of type 'TItem'`

This started with the upgrade to aspnetcore5.0

**Comment by javiercn** [comment]
@joshlang thanks for contacting us.

@NTaylorMullen do you have an idea of what's going on here?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen do you have an idea of what's going on here?

It's a general C# error so I'd file this in the dotnet/Roslyn repo:

![image](https://user-images.githubusercontent.com/2008729/77086258-c3eccc00-69be-11ea-9386-a937ab8b362b.png)


For some reason if you restrict TItem to `class` (I know we don't support this in Blazor yet) all works well.
