### ISSUE TITLE
Ramp up HTTP/3 interop tests

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#19972]
Epic https://github.com/dotnet/aspnetcore/issues/15271

We need to ramp up some of our existing interop tests to support HTTP/3, once we have an end-to-end working for HTTP/3 between `HttpClient` and Kestrel.

Edit: These are first party clients and servers we should have at least some HTTP/3 interop testing with:
- HttpClinet
- Kestrel
- HttpSys
- IIS
- WinHttp

**Comment by adityamandaleeka** [comment]
- Browser testing should be covered by #34859 
- HTTP.SYS covered in part by #29077 
- IIS covered in part by #29078

Some HttpClient testing against Kestrel is already in place.

Backlogging this for now.

**Comment by adityamandaleeka** [comment]
Only gap seems to be Kestrel + different client, which is now covered in another issue. Closing this.
