### ISSUE TITLE
Virtual FileProvider doesn't work in 3.1

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#19988]
I used this code in ASP.NET core 3.0 preview to enable my virtual file provider:
```
services.Configure<MvcRazorRuntimeCompilationOptions>(
                   options => options.FileProviders.Add(new Vazor.VazorViewProvider( ));
);
```

where VazorViewProvider is a simple class that implements IFileProvider.
It was working in 3.0 preview, but now it doesn't work in ASP.NET Core 3.1. The VazorViewProvider.GetFileInfo is never called.
Why? Am I missing some configuration? How can I get it work?

**Comment by VBAndCs** [comment]
Note:
I defined the VazorViewProvider class in a separate .NET Standard 2.0 library. I got an advice to use Razor Class Library  instead, so I did, but I got the same issue! My File Provider is never used!
Why?

**Comment by VBAndCs** [comment]
You can check this in this project:
https://github.com/VBAndCs/Vazor/tree/master/WebApp1
The file provider is here:
https://github.com/VBAndCs/Vazor/tree/master/Vazor

**Comment by javiercn** [comment]
@VBAndCs thanks for contacting us.

@pranavkm do you have any thoughts here?

**Comment by pranavkm** [comment]
Wouldn't you need to add runtime compilation as part of your startup: 

* https://github.com/VBAndCs/Vazor/blob/master/WebApp1/Startup.vb#L24
* https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#opt-in-to-runtime-compilation

**Comment by VBAndCs** [comment]
@pranavkm
It worked. Thanks very much. 
```
        services.AddControllersWithViews(). ' Enable Vazor
            AddRazorRuntimeCompilation(
                 Sub(options) options.FileProviders.Add(New Vazor.VazorViewProvider())
            )
```

@javiercn
Shouldn't  there be a compiler warning that this code:
```
services.Configure(Of MvcRazorRuntimeCompilationOptions)(
     Sub(options) options.FileProviders.Add(New Vazor.VazorViewProvider())
)
```

is obsolete and will not work, and advice to use the first one?
Thanks for the help.

**Comment by pranavkm** [comment]
Configuring the option is fine, but you have to add the feature for it to be used. For instance, this should work:

```
 services.AddControllersWithViews().
            .AddRazorRuntimeCompilation();

services.Configure<MvcRazorRuntimeCompilation>(...);
```

**Comment by VBAndCs** [comment]
@pranavkm
That's right and it was the first thing I tried. But compiler should give an error when a configuration is missing. This happens for instance if you try to use MapRazorPages without configuring UseRazorPages.

**Comment by VBAndCs** [comment]
@pranavkm
There is another way to look at it:
If I called `options.FileProviders.Add( )` then I definitely want to opt in runtime compilation. So, I think it is practical to do that implicitly for us. I don't know if it is possible to modify the cod of the `FileProviders.Add( )` to do that, or just add the `AddRazorRuntimeCompilation( )` to the assembly in compilation behind the scene. Sure you know better.
