### ISSUE TITLE
Blazor - 3.2 Preview 1 - WebAssemblyHostBuilder - Cannot Add Service Provider Factory

### ISSUE THREAD

**Issue by alistairjevans** [dotnet/aspnetcore#19985]
In the Blazor preview (3.2.0-preview1.20073.1), the WebAssemblyHostBuilder no longer implements IWebAssemblyHostBuilder. This means that, among other things, the Autofac Service Provider Factory cannot be added to the host.

I'm raising this following someone raising the issue on our repo (https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/69).

Is this a temporary change that is going to be resolved in the full 3.2 release, and people can use Autofac with Blazor WebAssembly? Or is it intended for the Blazor build to be as small as possible, so custom service factories somehow aren't going to be supported?

Apologies if this is mentioned somewhere else, I couldn't see an issue related to it.

**Comment by alistairjevans** [comment]
This is the sort of code I imagined would work:

```csharp
public static WebAssemblyHostBuilder CreateHostBuilder(string[] args)
{
    var builder =  WebAssemblyHostBuilder.CreateDefault(args);
    
    builder.UseServiceProviderFactory(new AutofacServiceProviderFactory()))

    builder.RootComponents.Add<App>("app");

    return builder;
}
```

**Comment by RedDeathGitHub** [comment]
Please prioritize this, as this means we cannot update existing Blazor projects as it breaks DI!

I assume this is just a human error, as taking away existing capability to use custom DI would be absolutely terrible!

**Comment by javiercn** [comment]
@alistairjevans thanks for contacting us.

@rynowak you did fix this, didn't you? What's the pattern here?

**Comment by mkArtakMSFT** [comment]
This has been fixed in https://github.com/dotnet/aspnetcore/pull/4785
