### ISSUE TITLE
SignalR - SEH Exception when using CancellationToken 

### ISSUE THREAD

**Issue by AndreNecker** [dotnet/aspnetcore#19986]
Hello,

we are using an .Net application, which hosts some singlaR hubs.
The hubs are located in an .net Standard 2.0 dll and uses Microsoft.ApsNetCore.SignalR version 1.1.0.

The hub offers following method:

```
  public async Task GetFileById(Guid fileId, CancellationToken cancellationToken)
        {
           await Invoke(async () => await DoNothing());
        }

        private Task DoNothing()
        {
            return Task.CompletedTask;
        }
		
```
When the client calls it once, there is no problem. But after calling it multiple times (let's say 2 to 6 times), I get an SEH Exception from GC finalizer thread, which leads to an application crash. The stacktrace of the exception leads to safewaithandle.cs.

The problem does not appear, when I delete the cancellationToken parameter.

Does SignalR support using the CancellationToken?

**Comment by davidfowl** [comment]
Seems unrelated to SignalR. Can you reproduce this error in a new application?

**Comment by AndreNecker** [comment]
I could reproduce it in this solution: 

[WpfApp1.zip](https://github.com/dotnet/aspnetcore/files/4369057/WpfApp1.zip)

I start "Client" and "WpfApp1", press two times enter in the console and wait.

After 5-20 calls the "WpfApp1" process crashes with a SEHException.

It works, when I delete the CancellationToken in ChatHub.cs

**Comment by BrennanConroy** [comment]
This has nothing to do with SignalR.

You can reproduce the error by just running:
```c#
var output = JsonConvert.SerializeObject(new CancellationToken());

for (var i = 0; i < 100; ++i)
{
    var j = JsonConvert.DeserializeObject<CancellationToken>(output);
}
```

I don't think CancellationToken is meant to ever be run through a serializer/deserializer. If you look at the produced Json, there is a value for the `WaitHandle` object that is really a reference to a native object handle. Json uses reflection to modify values on objects when deserializing to produce the "correct" object. And changing internal values that point to native handles is a very bad idea.

If you want to pass some kind of "canceled" value to your hub method, just change it to a bool.
`public string Send(string name, string message, bool isCanceled)`
