### ISSUE TITLE
Remove survey prompt from template

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19992]
We don't want the survey prompt in the template for the final release, right?

Optionally we could try to do something to keep it for preview builds but have it auto-removed from final builds. I'm not sure how well suited our build/template system is to that kind of arrangement.

**Comment by danroth27** [comment]
We actually do want to leave the survey prompt in. We have it in the shipping Blazor Server template as well. It's a useful source of customer feedback.
