### ISSUE TITLE
Blazor WASM Authentication - TryGetToken is null - Version 3.2.0-preview2.20160.5

### ISSUE THREAD

**Issue by aletc1** [dotnet/aspnetcore#19998]
### Describe the bug
Using MSAL (With Azure Active Directory), after a successful login (when calling ```AuthenticationService.RequestAccessToken```, the method ```tokenResult.TryGetToken(out var token)``` returns a null token value.

### To Reproduce
Just generate a new MSAL project using: 
```
dotnet new blazorwasm -au SingleOrg --client-id "{CLIENT ID}" --tenant-id "{TENANT ID}"
```
And to reproduce, consider the following code in index.razor
``` C#
@code {

    protected override async Task OnInitializedAsync()
    {
        var tokenResult = await AuthenticationService.RequestAccessToken();
        
        if (tokenResult.TryGetToken(out var token))
        {
            if (token == null)
                throw new Exception("Access token is null. BUG?");
        }
    }
}
```
token shouldnt be null, since was successfully authenticated.

**Comment by miri10134** [comment]
I was about to open an issue for the same problem. On trying to understand the source of the problem I looked into the source code of the [Interop/AuthenticationService-Class](https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts) and found the following:

```typescript
async getAccessToken(request?: AccessTokenRequestOptions): Promise<AccessTokenResult> {
        try {
            const newToken = await this.getTokenCore(request?.scopes);

            return {
                status: AccessTokenResultStatus.Success,
                token: newToken
            };

        } catch (e) {
            return {
                status: AccessTokenResultStatus.RequiresRedirect
            };
        }
    }

    async getTokenCore(scopes?: string[]): Promise<AccessToken | undefined> {
        const tokenScopes = {
            redirectUri: this._settings.auth.redirectUri as string,
            scopes: scopes || this._settings.defaultAccessTokenScopes
        };

        try {
            const response = await this._msalApplication.acquireTokenSilent(tokenScopes);
            return {
                value: response.accessToken,
                grantedScopes: response.scopes,
                expires: response.expiresOn
            };
        } catch (e) {
            return undefined;
        }
    }
```

`getTokenCore` catches every exception and just returns `undefined`, which is not checked in `getAccessToken`. This leads to a result where "status" is set to "Success", but "token" is empty. The outer catch-block (in `getAccessToken`) will probalby never be reached.  

This does not explain the actual error but it is something that should be addressed along the way.

**Comment by MortenMeisler** [comment]
Holy moly this was driving me crazy!! Is this fixed in pv 4 shipping 6th Apr? Maybe obvious not sure 💯  Any workarounds untill then?
