### ISSUE TITLE
LINQ translation fails after upgrading to 3.1.1

### ISSUE THREAD

**Issue by shahedurrahman** [dotnet/aspnetcore#19997]
Following code fail with exception after upgrading to ASP.NET Core 3.1.1

``` C#
await _userManager.FindByLoginAsync(model.Provider, model.ProviderKey);
```

Exception message:

> The LINQ expression DbSet< User >.Where(u => u.Id.Equals(__userId_0))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().

I'm using custom int column for primary key in AspNetUsers table. Here is my configuration in code.
``` C#
[Table("AspNetUsers")]
public class User : IdentityUser<int>
{
	public int UserId
	{
		get { return Id; }
		set { Id = value; }
	}
```
``` C#
protected override void OnModelCreating(ModelBuilder builder)
{
	base.OnModelCreating(builder);

	builder?.Entity<User>(b =>
	{
		b.Ignore(u => u.Id);
		b.HasKey(u => u.UserId);
		b.Property(u => u.UserId).HasColumnName("Id");				
	});
}
```
The  exception is thrown from following method in library.

> https://github.com/dotnet/aspnetcore/blob/839cf8925278018903f53f22d580d15b0a59ca0f/src/Identity/EntityFrameworkCore/src/UserStore.cs

```C#
protected override Task<TUser> FindUserAsync(TKey userId, CancellationToken cancellationToken)
{
    return Users.SingleOrDefaultAsync(u => u.Id.Equals(userId), cancellationToken);
}
```
# Additional Details
Above mentioned code worked find before upgrading (from ASP.NET Core v2.2)

.NET Core SDK 3.1.101
ASP.NET Core 3.1.1
Microsoft.AspNetCore.Identity.EntityFrameworkCore v3.1.2
Microsoft.EntityFrameworkCore.SqlServer v3.1.2

**Comment by blowdart** [comment]
@ajcvickers any idea?

**Comment by ajcvickers** [comment]
This was being client-evaluated in 2.x probably because the Identity model has been modified by ignoring properties which means the queries can no longer be translated to the database. See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client

**Comment by shahedurrahman** [comment]
Thanks for the breaking changes link. I have already reviewed it during my upgrade from 2.2 to 3.1 and refactored some my other codes in project accordingly. As this particular exception is coming from the Identity package code, is there anything I can do in my code to make it work?

**Comment by Seabizkit** [comment]
change 
return Users.SingleOrDefaultAsync(u => u.Id.Equals(userId), cancellationToken);
to 
return Users.SingleOrDefaultAsync(u => u.Id == userId, cancellationToken);

i would discourage Equals

**Comment by shahedurrahman** [comment]
> change
> return Users.SingleOrDefaultAsync(u => u.Id.Equals(userId), cancellationToken);
> to
> return Users.SingleOrDefaultAsync(u => u.Id == userId, cancellationToken);
> 
> i would discourage Equals
> 
> apologies you are saying the built in lib is do things.

Still produces same exception.

**Comment by ajcvickers** [comment]
@shahedurrahman Use `ToEnumerable` to force evaluation on the client. This is what was happening in 2.2 anyway.

**Comment by shahedurrahman** [comment]
> @shahedurrahman Use `ToEnumerable` to force evaluation on the client. This is what was happening in 2.2 anyway.

That doesn't work either. My understanding is that using separate int property for primary key and ignoring existing 'id' column (which I'm doing in my case) breaks LINQ translation in 3.0/3.1.

```C#
b.Ignore(u => u.Id);
```
Basically this breaks external sign in using Facebook or Google in 3.0/3.1 and preventing me from upgrading. Both of these method are not working because of this issue.

```C#
await _signInManager.ExternalLoginSignInAsync(model.Provider, model.ProviderKey, model.IsPersistent, model.BypassTwoFactor.Value);
await _userManager.FindByLoginAsync(model.Provider, model.ProviderKey);
```

Please let me know if there is any additional details I can provide. This is the only issue right now that is preventing our .NET Core 3.1 migration! :(

**Comment by ajcvickers** [comment]
@shahedurrahman All this should work with the default EF model in ASP.NET Core Identity. Since you have modified the model in a way that the queries cannot be evaluated on the server the only options are:
* Revert your model changes or do them in a way that doesn't involve use of un-mapped properties in queries
* Explicitly use client evaluation in all the places where your modified model requires it.

**Comment by shahedurrahman** [comment]
> @shahedurrahman All this should work with the default EF model in ASP.NET Core Identity. Since you have modified the model in a way that the queries cannot be evaluated on the server the only options are:
> 
> * Revert your model changes or do them in a way that doesn't involve use of un-mapped properties in queries
> * Explicitly use client evaluation in all the places where your modified model requires it.

@ajcvickers Thanks for the quick reply and suggestions. I'm afraid that, I have different situation. Let me try to recap in short.

- I'm using Microsoft.AspNetCore.Identity.EntityFrameworkCore v3.1.2
- I'm using 'UserId' int property in my custom User model to map 'id' database column in 'AspNetUsers', which I believe is a supported scenario.
- I'm using following identity library/package method to sign in using Facebook and Google (which is actually throwing the exception)

```C#
Microsoft.AspNetCore.Identity.EntityFrameworkCore
```

So, none of the code that I've written in project is having issue, the exception is coming from the AspNetCore.Identity package code. Everything worked in 2.2. At this point I'm basically stuck.

**Comment by ajcvickers** [comment]
@shahedurrahman 

> I'm using 'UserId' int property in my custom User model to map 'id' database column in 'AspNetUsers', which I believe is a supported scenario.

Modifying the EF model in this way is supported so long as the model created still works with ASP.NET Core Identity. This was the case with your model for 2.2, but because EF Core 3.0 made a breaking change to stop doing client eval your model is no longer compatible.

Making modifications to the model as [described in the documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1) should not hit this issue. However, as soon as you start ignoring existing properties on the model you're likely to run into this kind of client eval issue.

**Comment by shahedurrahman** [comment]
> @shahedurrahman
> 
> > I'm using 'UserId' int property in my custom User model to map 'id' database column in 'AspNetUsers', which I believe is a supported scenario.
> 
> Modifying the EF model in this way is supported so long as the model created still works with ASP.NET Core Identity. This was the case with your model for 2.2, but because EF Core 3.0 made a breaking change to stop doing client eval your model is no longer compatible.
> 
> Making modifications to the model as [described in the documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1) should not hit this issue. However, as soon as you start ignoring existing properties on the model you're likely to run into this kind of client eval issue.

@ajcvickers Thank you for your time and following up so far. The documentation link did help. As for solution to the problem, I might modify the model/properties in my project according to the documentation. Thanks again!
