### ISSUE TITLE
Get field/property value for JSRuntime

### ISSUE THREAD

**Issue by OsaPL** [dotnet/aspnetcore#19993]
### Describe the solution you'd like
JSInterop is a great tool, works well, but inability to get to properties was getting on my nerves.

The solution I use almost all the time, when I need a property/field value, is:

c#
```csharp
    public async Task<T> GetJSProp<T>(string path)
    {
        return await JSRuntime.InvokeAsync<T>("ResolveValue", path);
    }
```
Usage:
```csharp
ClientId = await GetJSProp<string>("host.clientId");
```

And finally js:
```js
        function ResolveValue(path, obj) {
            return path.split('.').reduce(function(prev, curr) {
                return prev ? prev[curr] : null
            }, obj || self)
        }
```

I know that this is not perfect a perfect solution, due to how js behaves, but it does the job for me.

My request is that can we get something similar for JSRuntime, to just do
```csharp
ClientId = await JSRuntime.GetValue<string>("host.clientId");
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We don't have any plans to make changes in this area in the near future. The solution you've got to seems fine.
