### ISSUE TITLE
OpenIDConnectionOptions does not seem to respect BackChannel HttpClient options

### ISSUE THREAD

**Issue by mjnorman** [dotnet/aspnetcore#20000]
If I'm reading the source correctly, I should be able to pass a new httpclient with a proxy configured to OpenIdConnectOptions, and the below check should allow my httpclient to be used.

https://github.com/dotnet/aspnetcore/blob/ec4a7f6c2b8e4efc7d1e31f9fa586c3dd3eeeec3/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectPostConfigureOptions.cs#L63

However this does not appear to be respected.  If I configure a proxy, and trace with Wireshark I do not see any traffic directed to the proxy.

I have configured a PostConfigureOptions class as such--
```c#            
services.AddSingleton<IPostConfigureOptions<OpenIdConnectOptions>, ConfigureOpenIdOptions>();
```
...
```c#
   public class ConfigureOpenIdOptions : IPostConfigureOptions<OpenIdConnectOptions>
...
        public void PostConfigure(string name, OpenIdConnectOptions options)
        {
            options.Authority += "/v2.0/";

            var httpClientHandler = new HttpClientHandler()
            {
                Proxy = new WebProxy(proxyURI)
            };
            options.Backchannel = new HttpClient(httpClientHandler);
        }
```

Can anyone advise why this might not be working as expected?  Or more realistically, are my expectations incorrect?

**Comment by Tratcher** [comment]
Have you set a breakpoint and confirmed that your PostConfigure action is running? Why are you using IPostConfigureOptions? It seems like you're trying to use this with AzureAd? See this example for adding configuration to those:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1#configure-the-underlying-openidconnectoptionsjwtbearercookie-options

**Comment by mjnorman** [comment]
Yes to using it with AzureAd.  I confirmed with breakpoint that PostConfigure is running, and also checked `OnRedirectToIdentityProvider` and confirmed the backchannel was still set as the message goes out.  As to why, honestly was just trying to clean up the Startup by moving the configuration out to a separate class.  I will move it back in and see if it makes a difference.

**Comment by Tratcher** [comment]
Classes are fine, but you might want to try IConfigureOptions rather than IPostConfigureOptions.

**Comment by Tratcher** [comment]
Another thought. In wireshark are you seeing any direct requests from the web server to the identity provider (not redirects). Our default OIDC response type is IdToken and that doesn't require any backchannel communication.

**Comment by mjnorman** [comment]
Moving it back to Startup allowed me to see the communication to the Proxy.  However, if I change to an IConfigureOptions class, I never hit my Configure method.  

```c#
 public class ConfigureOpenIdOptions : IConfigureOptions<OpenIdConnectOptions>
...
  public void Configure(OpenIdConnectOptions options)
```


  I think this is why I went down the IPostConfigure road after seeing that was how OpenIdConnect looked to be configured, https://github.com/dotnet/aspnetcore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectPostConfigureOptions.cs#L31

**Comment by Tratcher** [comment]
Ah. One issue with IPostConfigureOptions is ordering. OIDC's existing PostConfigure is already setting and consuming the bachchannel. Try registering your IPostConfigureOptions before AddAzureAd so your custom banchannel is used for metadata.

https://github.com/dotnet/aspnetcore/blob/62351067ff4c1401556725b401478e648b66acdc/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectPostConfigureOptions.cs#L63-L96

Not sure why IConfigureOptions isn't working for you.

**Comment by mjnorman** [comment]
The order did do the trick, moving the registration before AddAzureAd allowed me to hit the PostConfigure and allow it to work.  Still a mystery why IConfigure did not work, but will close for now.  Thanks for your help!
