### ISSUE TITLE
Update UI for Blazor WebAssembly PWA

### ISSUE THREAD

**Issue by mselinger75** [dotnet/aspnetcore#20017]
For example i have 2 people opened same blazor PWA with a Counter page. If first person clicks Count button i want Counter value for the second person to match.

what is a recommended approach to do this for Blazor PWA. Thanks!

**Comment by julienGrd** [comment]
if your webassembly app is hosted by a .net core server, you can make a signal-r connection between the clients and server which authorize push (server->client).
all you need is here
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio

Good luck and don't forget to close this issue if its OK !

**Comment by javiercn** [comment]
@mselinger75 thanks for contacting us.

@julienGrd is correct, you would need to use signalr or other server-side technology to accomplish the synchronization.
