### ISSUE TITLE
Scaffolding Identity into a Blazor WebAssembly app with Individual User Accounts enabled results in code that doesn't compile

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#20016]
If you scaffold Identity into a default ASP.NET Core hosted Blazor WebAssembly app, the generated code doesn't compile.

Repro steps:
- Install .NET Core 3.1 SDK
- Run `dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview2.20160.5`
- In VS create a new ASP.NET Core Blazor App WebAssembly app with Individual User Accounts enabled
  - File -> New Project -> Blazor App
  - Select the Blazor WebAssembly template in the Create a New Blazor App dialog
  - Select the "ASP.NET Core hosted" checkbox
  - Change authentication, select Individual User Accounts
  - Click Create
- Build and run the project to see that it runs fine
- Right click on the project -> Add -> New Scaffold item -> Identity
- In the Add Identity dialog
  - Select "Override all files"
  - For the Data context class select the existing one
  - Select Add
- Build the project

Expected result: App builds successfully

Actual result:

```
Error	CS0246	The type or namespace name 'UserManager<>' could not be found (are you missing a using directive or an assembly reference?)	BlazorWebAssemblyWithIdentity.Server	C:\Users\user\source\repos\BlazorWebAssemblyWithIdentity\BlazorWebAssemblyWithIdentity\Server\Areas\Identity\Pages\Account\RegisterConfirmation.cshtml.cs	15	Active
Error	CS0246	The type or namespace name 'UserManager<>' could not be found (are you missing a using directive or an assembly reference?)	BlazorWebAssemblyWithIdentity.Server	C:\Users\user\source\repos\BlazorWebAssemblyWithIdentity\BlazorWebAssemblyWithIdentity\Server\Areas\Identity\Pages\Account\RegisterConfirmation.cshtml.cs	18	Active
```

Additional context:

The same compilation errors also happen if you scaffold Identity into a web app with a new custom DB context class and a new customer user type. The Blazor WebAssembly app comes by default with a customer user type, so it hits the same issue.

The broken file, *RegisterConfirmation.cshtml.cs*, is missing a using for the namespace `Microsoft.AspNetCore.Identity` when the user type isn't the default `IdentityUser` type.

**Comment by HaoK** [comment]
Should be fixed via https://github.com/aspnet/Scaffolding/pull/1284 in scaffolding

**Comment by Sm1le291** [comment]
HI! Does this fix already available or it will be fixed in the next release?
I am using 3.2.0-preview3.20168.3

**Comment by danroth27** [comment]
@Sm1le291 The fix should have been made in the latest scaffolding packages. Try updating the ASP.NET code generator packages in your project and running scaffolding with the latest generator.
