### ISSUE TITLE
Is that any to make AuthorizeAttribute can change scheme arg by routevalue in runtime

### ISSUE THREAD

**Issue by kugarliyifan** [dotnet/aspnetcore#20024]
I want to set the AuthorizeAttribute's AuthenticationSchemes paramter in runtime by the routevalue,like this

/api/file/{type}

when type=adv then AuthenticationSchemes="admin"
when type=product then AuthenticationSchemes="api"

is that any way to do it?

I found the IApplicationModelConvention ,but it's static,and it can't map type to schemename

**Comment by Tratcher** [comment]
I expect you'd need to write an authorization policy for this.

**Comment by mkArtakMSFT** [comment]
Closing per @Tratcher 's response.
