### ISSUE TITLE
AM/PM time value is not binding to the TimeSpan property in ASP.NET Core Model binding.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#20025]
Consider I have the following model class:

```
public class Employee
{       
     public TimeSpan EntryTime { get; set; }
     public TimeSpan OutTime { get; set; }
}
```

In in the view input fields are as follows:

```
<div class="form-group">
       <label asp-for="EntryTime" class="control-label"></label>
        <input asp-for="EntryTime" class="form-control" />
        <span asp-validation-for="EntryTime" class="text-danger"></span>
</div>
<div class="form-group">
       <label asp-for="OutTime" class="control-label"></label>
        <input asp-for="OutTime" class="form-control" />
        <span asp-validation-for="OutTime" class="text-danger"></span>
</div>
```

I am using timepicker to pick the time as `5:39 PM` format.

When submitting the form receving the model validation error:
>The value '5:39 PM' is not valid for EntryTime.

That means, `AM/PM` format time is not binding to the TimeSpan property in ASP.NET Core default Model binding.

**Note: For DateTime property `30-Jan-2020` string value of the input field binding to the property correctly.**

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by TanvirArjel** [comment]
@mkArtakMSFT  This is not a question! This is an issue as I said that ASP.NET Core default Model binder can bind string representation of DateTime to DateTime property while its not binding string representation of TimeSpan value to TimeSpan property. That's it.

Note: I know how the workaround of this issue. But I have posted here so that ASP.NET Core Team can think about this.

Thank you.

**Comment by mkArtakMSFT** [comment]
Thanks for the additional details, @TanvirArjel.
Glad that you have a workaround. This is not a bug in the framework, rather you code should use `DateTime` model properties instead.
