### ISSUE TITLE
Client Authentication State needs initialising upon startup to stay in sync with server

### ISSUE THREAD

**Issue by Discovery-support** [dotnet/aspnetcore#20027]
I am using the latest Blazor WebAssembly 3.2.0 Preview 2
Using the default scaffolding for Blazor WebAssembly App connected to a local database.

The Client Authentication state can be out of sync with the server authentication state, should there not be some initial first rendering check? If so how?

Does the client check for auth token expiry?
Bug: Steps to reproduce

1) Run App and Register a user and mark as confirmed and Login
2) Close App
3) Run App
Result: Client LoginDisplay component shows **Log In** (not Hello BlazorUser...)
           (Server is still authenticated - proved in the next step when a Weather Forecast is given)
6) Click FetchData
Result: App displays (briefly) **Checking login state**
            then LoginDisplay component shows **Hello BlazorUser...** (instead of Log In)
            WeatherForecast appears

**Comment by javiercn** [comment]
@Discovery-support thanks for contacting us.

We'll take a look at you issue and get back to you

**Comment by mkArtakMSFT** [comment]
This is already supported.
