### ISSUE TITLE
Angular template with individual accounts - login without promt after logout

### ISSUE THREAD

**Issue by MiroKov** [dotnet/aspnetcore#20030]
Expected:

User registers with  email & password: (i.e. tesT1a@test.de/tesT1a@test.de). But any username & password can be put here.
User logs in.

What happens:

User registers with  email & password: (i.e. tesT1a@test.de/tesT1a@test.de)
User tries to log in -> Invalid login attempt.

The user gets created. But for some reason login doesn`t go through.

I made a [repo ](https://github.com/MiroKov/testLogout/tree/master/testLogout).

**Comment by MiroKov** [comment]
What I wanted to post initially as a bug, is that after the user (when logged in) logs out, and clicks log in, he automatically gets logged in, without going through some kind of prompt.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MiroKov.
@HaoK can you please look into this? Thanks!

**Comment by HaoK** [comment]
@MiroKov I'm unable to isolate what steps you did to see this behavior, can you outline exactly what steps you did (preferably against a brand new angular template with individual auth) to demonstrate the problematic behavior?

**Comment by MiroKov** [comment]
@HaoK Hi,
That was a brand new app, that I created just for the purpose of proving:

> What I wanted to post initially as a bug, is that after the user (when logged in) logs out, and clicks log in, he automatically gets logged in, without going through some kind of prompt.

After creating the app, I just changed the appsettings' connection string to use the SqlServer.
I created one user.
Then I wanted to log in, in order to test logout function on a brand new app. However, I was unable to log in, although the user was created.

**Comment by HaoK** [comment]
So you created the user on one app and created a different app and are trying to login pointing at the same sql database but with a different app?

**Comment by HaoK** [comment]
Can you try this without sql server, just point both apps at the same localdb using the same connection string

**Comment by MiroKov** [comment]
1. Created a new [repo](https://github.com/MiroKov/WebAppRepo/commits/master). Here in commits you can see all the changes to the files. First commit has the original files.
2. Register new user:
![image](https://user-images.githubusercontent.com/18582187/77758623-95f92e80-7033-11ea-96f9-5ddbb088606d.png)
3. Apply Migrations
![image](https://user-images.githubusercontent.com/18582187/77758681-b0cba300-7033-11ea-81db-0aa170c3d288.png)
In DB there is the user.
4. Log in 
![image](https://user-images.githubusercontent.com/18582187/77758945-26377380-7034-11ea-9349-d3c25f486dd3.png)

So, this was done with a brand new app, brand new DB. 
Also tried to create another user, and to login as that other user. Same story.

Hope this clarifies.

**Comment by MiroKov** [comment]
I am closing this issue, since it was an error on my part. 
I failed to realize that there was a link that I needed to click, namely, to confirm my account.
Thought it was some general info.
