### ISSUE TITLE
No warning/error when there is a static web assets conflict

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#20041]
Repro steps:

- Create an ASP.NET Core hosted Blazor WebAssembly app
- Add a wwwroot folder to the Server project
- Add a *wwwroot/css/site.css* file to the Server project

Expected result: 

- Warning/error because the site.css in the Server project conflicts with the site.css in the Client project

Actual result:

- No warning/error and the site.css in the Server project is used instead of the one from the client project.

**Comment by danroth27** [comment]
@javiercn

**Comment by SteveSandersonMS** [comment]
@javiercn I think this is done, right?

**Comment by javiercn** [comment]
Yep
