### ISSUE TITLE
Angular app - individual accounts authentication doesn't work in IIS when uri with capital letters

### ISSUE THREAD

**Issue by MiroKov** [dotnet/aspnetcore#20052]
Hi all, 
this is a continuation of a long battle that started with #19852. The problems described there (part of them, were because of the Uri, that had a capital letter. Took awhile to figure it out.

### Describe the bug
When deploying an app in IIS (IIS EXPRESS has no problems), and using an individual accounts authentification, following error appears when trying to login:

![image](https://user-images.githubusercontent.com/18582187/77229269-37443880-6b8d-11ea-98f1-279ac95515f6.png)

Take a note of the uri:

![image](https://user-images.githubusercontent.com/18582187/77229279-49be7200-6b8d-11ea-943b-25e19f267e80.png)

and the base uri:

![image](https://user-images.githubusercontent.com/18582187/77229288-593dbb00-6b8d-11ea-921c-2d90e4cbba28.png)

Needless to say, when _Sperris_ -> _sperris_, than everything works fine.

For a code base take a template angular app with individual accounts.

**Comment by blowdart** [comment]
@HaoK is this identity, or routing?

**Comment by HaoK** [comment]
routing i would think

**Comment by javiercn** [comment]
@MiroKov thanks for contacting us.

Not sure what the underlying causes of this can be. It might have to do with the paths on the cookies.
