### ISSUE TITLE
Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.2 nuget missing target?

### ISSUE THREAD

**Issue by omatrot** [dotnet/aspnetcore#20050]
### Describe the bug
The Microsoft EntityFrameworkCore 3.1.2 nuget targets .NET Standard 2.0
The Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.2 nuget targets .NET Standard 2.1 and .NET Core App 3.1.
Is that right?

At this time I'm unable to use shared code in both a .NET Standard 2.0 library and a .NET 4.7.x library.

**Comment by blowdart** [comment]
ASP.NET Core 3 only targets Net Core App 3, which in turn only targets the .NET Core Runtime, so yes, this is correct, you cannot target .NET 4,7 or 4.8.

**Comment by omatrot** [comment]
I'm confused because I thought that the version numbers would allow me to select compatible nugets. In this case it is not.
