### ISSUE TITLE
Blazor WASM wrong error message

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#20051]
I get this error message with my EditForm:

blazor.webassembly.js:1 WASM: System.InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.

The problem is I not defined a model neither a context.

**Comment by javiercn** [comment]
@JulienM28 thanks for contacting us.

Can you provide a minimal repro project that showcases the issue so that we can investigate?

**Comment by JulienM28** [comment]
Here it is:

````
 <EditForm OnValidSubmit="async ()=>await SubmitAsync()">
                <DataAnnotationsValidator />

                <div class="input-group">
                    <InputTextOnInput class="border-bottom-dark" @bind-Value="ViewModel.SupplierName" required />
                    <ValidationMessage For="@(() => ViewModel.SupplierName)" />
                    <label>Raison sociale</label>
                </div>

                <div class="input-group">
                    <InputSiret class="border-bottom-dark" @bind-Value="ViewModel.SupplierSiret" />
                    @* <InputTextOnInput class="border-bottom-dark" @bind-Value="ViewModel.SupplierSiret" required /> *@
                    <ValidationMessage For="@(() => ViewModel.SupplierSiret)" />
                </div>

                <button class="btn btn-default btn-ok btn-fixed-br" disabled="@ViewModel.ValidationDisabled">Valider</button>
</EditForm>
````

In this case, instead of saying that I need a context or a model, th error message is saying :
System.InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.

It's not a big problem, but it may be confusing.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for the details.
The error message is actually correct. If you're interested in sending a PR to add the `parameter` word after `model`, feel free to send us a PR.

**Comment by mkArtakMSFT** [comment]
Thanks for sharing the details.
We think the error message represents the problem correctly and we don't want to change that at the moment.
If we hear similar confusion from other community members in the future, we will reconsider tweaking it then.
