### ISSUE TITLE
[Blazor] Implicit Operator for RenderFragment from String

### ISSUE THREAD

**Issue by vertonghenb** [dotnet/aspnetcore#20068]
Coming from `TypeScript` we have `Union` types, where a parameter can be of multiple types. Which is quite handy because sometimes I want a `[Parameter]` in my Blazor component to be a `string` or a `RenderFragment`. I'm wondering if an implicit operator would make sense to make it possible to set a `parameter` as a `string` or as a `RenderFragment`

### MyComponent.razor
```razor
<h3>@Text</h3>
@code {
    [Parameter] public RenderFragment Text { get; set; }
}
```
### Using the component

```razor

@* Possible *@
<MyComponent>
    <Text>Heya</Text>
</MyComponent>

@* Not possible since Text is a render fragment and not a string. *@
<MyComponent Text="Heya"/>
```

### Describe the solution you'd like
Therefore I was wondering if it would be possible to create an implicit operator for this use case, so that the Parameter can be used as a `string` or as a `RenderFragment`.
```cs
    public class RenderFragment
    {
        public static implicit operator RenderFragment(string content)
        {
            return new RenderFragment(builder =>
            {
                builder.AddContent(1, content);
            });
        }
    }
```
### Additional context
Maybe there are other work arounds but some advise would help if it exists.

**Comment by mkArtakMSFT** [comment]
Thank you for your feature request. We'll consider this feature during the next sprint planning period and update the status of this issue accordingly. To help us prioritize this feature correctly, please make sure you provide as much information as possible about the scenarios and their importance.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
 This is not something we plan to do in the near future. You can definitely achieve this by introducing two separate parameters and rending only the one which was provided.

**Comment by vertonghenb** [comment]
@mkArtakMSFT ok, sorry to hear that, it's used quite a lot though.
Thank you for the consideration!
