### ISSUE TITLE
Include authorization cookie when using IHttpClientFactory to create an HttpClient

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#20062]
I use Identity with cookie authentication but when I use `IHttpClientFactory` to create request no cookies are included in the request. Is there something similar to `credentials: 'include'` when using JS with the `fetch` api for `HttpClient`?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@rynowak can you please look into this? Thanks!

**Comment by marcuslindblom** [comment]
I think I'm looking for something like this but for the default handler.

```c#
    var cookieContainer = new System.Net.CookieContainer();
    System.Net.Http.HttpClientHandler handler = new System.Net.Http.HttpClientHandler
    {
      UseCookies = true,
      UseDefaultCredentials = true,
      CookieContainer = cookieContainer
    };

    if(Context.Request.Cookies.TryGetValue(".AspNet.SharedCookie", out string value)) {
      cookieContainer.Add(new System.Net.Cookie(".AspNet.SharedCookie", value));
    }

    using var client = new System.Net.Http.HttpClient(handler);
```

**Comment by Tratcher** [comment]
See the new header propagation middleware
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#header-propagation-middleware

**Comment by marcuslindblom** [comment]
That’s exactly what I was looking for. Thanks!
