### ISSUE TITLE
Blazor - Connection (Client/Server) Timeout configuration

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#20070]
![Timeout1006](https://user-images.githubusercontent.com/4785384/77297033-154ad300-6cbf-11ea-8436-ea6302521881.jpg)

We are seeing in Server Side Blazor issues with connection timeouts (see attached pic). It seems to be transient (e.g.. if the azure side services (app or signalr) are restarted or, for example, if we lock a computer and walk away for a period of time). When we come back the default "Retry" button is not seen and the scree is essentially "locked" until the screen is refreshed. I think I understand the concept that is, for any reason (server or client side), the circuit connection is broken this can happen.

I have read through some issues/docs  like:
#18840
#10325 - We implemented Dan's entry here (js catch and retry). Nice as a fallback but really need more of a defined config implementation. Both client and server.
Docs - [SignalR Config](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-3.1&tabs=dotnet), assuming I am reading the right docs for this situation.

I guess what we are looking for at this time, if there is no real solution, is clear guidance on how to set server and client timeouts in order to lessen what we are seeing, if possible. According to the docs mentioned above the server and client side timeout settings need to be coordinated so as not to run into issues with varying server and client timeout configs. While I can see the server timeout config it is not really clear on how to set the client side timeouts in the Blazor js (e.g. get a ref to the connectionObject? Circuit?)

Sorry if there is already clear guidance for this and I did not find it. Please close this as needed.

Any input greatly appreciated!

**Comment by pranavkm** [comment]
The error message here doesn't indicate a timeout. 1006 is an abrupt connection disconnect. Quoting https://github.com/dotnet/aspnetcore/issues/20984#issuecomment-616745210, 

> We have a full guide to collecting the necessary diagnostics here: https://aka.ms/aspnet/signalr/troubleshoot
> 
> Please let us know:
> 
> 1. The browser you are using
> 1. Any proxies (Corporate Firewalls, etc.) that might be in use
> 1. The server OS and .NET Core version in use
> 1. Any server logs you can collect [using the instructions in the diagnostics guide](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging)

@BrennanConroy could you help drive this?
