### ISSUE TITLE
Not able to serialize enum to string

### ISSUE THREAD

**Issue by manideep418** [dotnet/aspnetcore#20079]
using the below config in startup.cs 
`services.AddControllers()
                .AddNewtonsoftJson(opt =>
                opt.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter()))`

but not able to serialize the enum to string values. Only integer values are displayed in the swagger page. Could some please help me how to fix this?.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
