### ISSUE TITLE
Changing wwwroot directory does not work

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#20071]
I tried several ways to change the default wwwroot directory to another directory with Blazor Webassembly.
My folder structure is like that:
src/
- csproj file
Web/
- index.html
- Css
- Images

My plan is to move the wwwroot directory to ../Web

I tried this solutions:
1. Add project.json file with this content:
```json
{
    "publishOptions": {
        "include": [
            "wwwroot",
            "**/*.cshtml",
            "appsettings.json",
            "web.config",
            "**/*.html",
            "../Web"
        ]
    }
}
```

2. Add hosting.json file with this content:
```json
{
    "webroot": "../Web"
}
```

3. Add UseWebRoot to Program.cs:
```c#
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("body");

            builder.Services.AddBaseAddressHttpClient();
            builder.Services.AddTransient<HttpClient>();

            var host = builder.Build();
            host.UseWebRoot(YourStuff);
            await host.RunAsync();
        }
```

4. Add <BlazorWebRootName>..\Web\</BlazorWebRootName> to csproj file
https://github.com/dotnet/aspnetcore/blob/2d0c49d0fca0aaf37672e0aec1c011cfe6a2d6f2/src/Components/Blazor/Build/src/targets/Blazor.MonoRuntime.props#L15

None of these solutions did work. My problem is, that files in my web root will not be tracked for pwa content-hashes because it is not in the default wwwroot directory. Therefore offline-support does not work.

**Comment by MarkusRodler** [comment]
Using  `<ServiceWorkerAssetsManifestItem Include="MyDirectory\AnotherFile.json"
    RelativePath="MyDirectory\AnotherFile.json" AssetUrl="files/AnotherFile.json" />` is no option for me because the web root is big and I don't want to specify each file. That would be prone to error.

**Comment by javiercn** [comment]
@MarkusRodler thanks for contacting us.

We don't support project.json (that was from the beginning of dotnet core I believe). You can't configure the webroot with a hosting.json, that's not something that ever existed AFAIK.

There is also no "host.UseWebRoot" in Blazor either.

The best you can do, is to use MSBuild to copy the output to the final destination you are expecting on disk.

From what I understand you want to go from things in `wwwroot` to things in `..\Web`? For example, instead of `<<a>>\wwwroot\file.html` `<<a>>\web\file.html`. Is that the case?

**Comment by SteveSandersonMS** [comment]
@MarkusRodler You can also use MSBuild features to include a whole directory:

```xml
    <ServiceWorkerAssetsManifestItem
      Include="MyDirectory\**"
      RelativePath="MyDirectory\%(RecursiveDir)%(FileName)%(Extension)"
      AssetUrl="$([System.String]::Copy('%(RecursiveDir)%(FileName)%(Extension)').Replace('\', '/'))" />
```

**Comment by MarkusRodler** [comment]
Thanks for your answers @javiercn and @SteveSandersonMS 
The solution from @SteveSandersonMS is ok for me because I am running it within a docker container and can mount the paths like I wanted in development and copy it in production.

Generally it would be nice to specify the web root directory but that seems to be a feature request.

Thanks for your help!
