### ISSUE TITLE
Update Identity package references in Blazor WASM project to the latest 3.1.2 release

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#20074]
When creating an Blazor WASM project with Individual Auth option, the referenced identity packages are 3.1.0. They should instead be the latest 3.1.2 version.
This indicates an issue with the `MicrosoftAspNetCoreIdentityEntityFrameworkCorePackageVersion` variable value in here: https://github.com/dotnet/aspnetcore/blob/a700aa92fec0c3554eb3f450a17037761b069363/src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates/ComponentsWebAssembly-CSharp.Server.csproj.in#L31

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/20148
