### ISSUE TITLE
Callback method as a parameter

### ISSUE THREAD

**Issue by bdnts** [dotnet/aspnetcore#20075]
### Is your feature request related to a problem? Please describe.
A Blazor component can be passed callback methods as parameters.  This is not possible when an Aspnetcore View calls a component https://github.com/dotnet/AspNetCore.Docs/issues/17411

A clear and concise description of what the problem is.
Example: Aspnetcore View calling a Blazor component that is a modal dialog.  The dialog allows User to enter a zip code (or anything)  There are Save and Cancel buttons, which are callbacks to the View/Model methods.  In Blazor, the callbacks indicate the User action chosen, and return the new data.  Without callbacks, User data entry and action cannot be returned.

### Describe the solution you'd like
<component type="typeof(ZipCodeModal)" render-mode="Serverprerendered" param-Save="@Model.Save" param-Cancel="@Model.Cancel" />

It does not appear there is another way to return data from the Blazor component to aspnetcore

**Comment by javiercn** [comment]
@bdnts thanks for contacting us.

The support for components within ASP.NET Core is limited to generating the initial output for a component and this is not something we have plans to change.
