### ISSUE TITLE
[Discussion] Removed `UseSignalR`, `UseConnections` and related methods

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#20082]
*This is the discussion issue for https://github.com/aspnet/Announcements/issues/412*

## Removed `UseSignalR`, `UseConnections` and related methods

In ASP.NET Core 3.0, we converted SignalR to use Endpoint Routing. As part of that we marked `UseSignalR`, `UseConnections` and some related methods (full list below) as obsolete. In ASP.NET Core 5.0 we will remove those methods entirely.

### Version introduced

5.0.0-preview3

### Old behavior

SignalR Hubs and Connection Handlers could be registered in the middleware pipeline using the `UseSignalR` or `UseConnections` methods.

### New behavior

SignalR Hubs and Connection Handlers should be registered within `UseEndpoints` using the `MapHub` and `MapConnectionHandler` extension methods on `IEndpointRouteBuilder`.

### Reason for change

The old methods had custom routing logic that didn't interact with other routing components in ASP.NET Core. In 3.0 we introduced a new general-purpose routing system (Endpoint Routing) and enabled SignalR to work with that. Switching to this model allows users to get the full benefits of endpoint routing.

### Recommended action

Remove code that called `UseSignalR` or `UseConnections` from your `Startup.Configure` method. Replace it with calls to `MapHub` and `MapConnectionHandler` within the body of a call to `UseEndpoints`. In general, your previous `MapHub`/`MapConnectionHandler` calls can be transferred directly from the body of `UseSignalR`/`UseConnections` over to `UseEndpoints` with no change needed.

### Category

ASP.NET

### Affected APIs

* [SignalRAppBuilderExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.signalrappbuilderextensions) class
	* [UseSignalR](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.signalrappbuilderextensions.usesignalr) method
* [ConnectionsAppBuilderExtensions](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.connectionsappbuilderextensions) class
	* [UseConnections](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.connectionsappbuilderextensions.useconnections) method
* [ConnectionsRouteBuilder](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.connections.connectionsroutebuilder) class
	* [MapConnectionHandler](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.connections.connectionsroutebuilder.mapconnectionhandler) method
	* [MapConnections](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.connections.connectionsroutebuilder.mapconnections) method
* [HubRouteBuilder](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.hubroutebuilder) class
	* [MapHub](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.hubroutebuilder.maphub) method

---
#### Issue metadata

* Issue type: breaking-change

**Comment by Suchiman** [comment]
Removed `UseEndpoints`? that's not correct, that's what we're supposed to be using.

**Comment by BrennanConroy** [comment]
Typo, thanks 😄
