### ISSUE TITLE
Do we still need ReceiveBufferSize in the WebSocketOptions?

### ISSUE THREAD

**Issue by huysentruitw** [dotnet/aspnetcore#20084]
The ReceiveBufferSize property of WebSocketOptions seems unused, do we still need it?

https://github.com/dotnet/aspnetcore/blob/6912dda560f52f761d9528dba786a7872ad1739f/src/Middleware/WebSockets/src/WebSocketMiddleware.cs#L134

cc @davidfowl

**Comment by shirhatti** [comment]
Triage: The action here is to obsolete it.

**Comment by BrennanConroy** [comment]
And maybe in https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/WebSockets/src/ExtendedWebSocketAcceptContext.cs too

**Comment by ADustyOldMuffin** [comment]
Can I look into working on this? I'd like to get into contributing.

**Comment by huysentruitw** [comment]
@ADustyOldMuffin sorry, I've already started working on this. Still need to update the reference assemblies, but I'm having some trouble with the build ATM.
