### ISSUE TITLE
Missing .versions file & Third-Party-Notices.txt in shared fx

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#20086]
See https://github.com/dotnet/aspnetcore/pull/19975#issuecomment-601954393 for more context

We appear to be missing some files in our shared framework artifacts.

When this issue is resolved, we should remove the SkipOnHelix attribute for ItContainsVersionFile() in src/Framework/test/SharedFxTests.cs

**Comment by wtgodbe** [comment]
Do we know if there's a strong reason why this file needs to be named `.version`? I don't see such a file in Microsoft.Netcore.App (they have `Microsoft.Netcore.App.versions.txt`), and trying to include the file explicitly gives:

> error NU5119: File 'C:\code\aspnet\aspnetcore\artifacts\obj\Microsoft.AspNetCore.App.Runtime\Debug\.version' was not added to the package. Files and folders starting with '.' or ending with '.nupkg' are excluded by default. To include this file, use -NoDefaultExcludes from the commandline

CC @dougbu @JunTaoLuo

**Comment by wtgodbe** [comment]
But basically the reason that this is happening is that we don't do something like the following for `.version` or `Third-Party-Notices.txt`

https://github.com/dotnet/aspnetcore/blob/ce0886c6dc48b3dd4b3a716810068ffde3871fab/src/Framework/src/Microsoft.AspNetCore.App.Runtime.csproj#L498-L502

So those files don't get included in _packageFiles. That's the same reason why the platform manifest isn't in the runtime pack, though that one's a happy accident (we don't want the platform manifest to be in the runtime pack, so us trying & failing to do so has been good. We should fix that as part of this)

**Comment by JunTaoLuo** [comment]
I think we should just follow the convention for Microsoft.NETCore.App. We should probably also check with the runtime team in case there are any requirements for naming.

**Comment by dougbu** [comment]
May also need to check w/ the SDK team because they may also read the file (and expect a specific name).

**Comment by wtgodbe** [comment]
@Pilchie @anurse looks like our packages are missing a `.version` file, a `Third-Party-Notices.txt` file, a `License.txt` file, and a `UseSharedDesignerContext.txt` file at least as compared to dotnet/runtime packages - do we have a stated strategy/requirement somewhere for what we intend to include in our packages? If not I can just work on including the first 3 (I don't see a `useSharedDesignerContext.txt` in our repo)

**Comment by wtgodbe** [comment]
For what it's worth, Extensions, EFCore, and AspNetCore-Tooling are also missing the files I mentioned above

**Comment by anurse** [comment]
I don't know what `.version` and `UseSharedDesignerContext.txt` are for. We should have some kind of third-party notices file though. The license should be covered by the `<license>` element in the nuspec.

**Comment by Pilchie** [comment]
I agree with what @anurse said.

**Comment by wtgodbe** [comment]
Roger that, I'll get going on it

**Comment by wtgodbe** [comment]
Looks like this isn't exactly how I described it above - some of our packages with custom .nuspecs (e.g. `Microsoft.AspNetCore.Identity.UI` & packages in the `components` dir) _do_ include `Third-Party-Notices.txt`, because they do so explicitly. The rest of our packages do not include the file. In fact, I see nine different `Third-Party-Notices.txt` files checked in to the repo. I guess what's right is to automatically include the one at the root of the repo, unless a custom one has already been included

**Comment by wtgodbe** [comment]
This is fixed in 3.1 & master now

**Comment by mthalman** [comment]
@wtgodbe - It doesn't look like the question on the `.version` file name was really answered here.  Why exactly was it changed away from the original name?  Now it's inconsistent with all the other frameworks in the SDKs; both Microsoft.NETCore.App and Microsoft.WindowsDesktop.App contain a `.version` in their respective locations (see https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.4.20223.1/dotnet-sdk-5.0.100-preview.4.20223.1-win-x64.zip).

This change actually broke our .NET Docker infrastructure which retrieves the version numbers of the shared frameworks in the SDK: https://github.com/dotnet/dotnet-docker/blob/fe5cedf3f4034a263fa2f118b606233cb708b1b4/eng/get-drop-versions.sh#L20

**Comment by dougbu** [comment]
Might need more work
