### ISSUE TITLE
ASP.NET Core 3.1 Identity: Lockout not triggering

### ISSUE THREAD

**Issue by mwhouser** [dotnet/aspnetcore#20081]
### Describe the bug

ASP.NET Core 3.1 projects using the build-in Identity do not trigger a user Lockout when too many incorrect passwords are attempted.

### To Reproduce

1. Create a new ASP.NET Core 3.1 project
    * Web Application (Model-View-Controller)
    * Authentication: Individual User Accounts
2. Run the out-of-the-box generated project
3. Create a user in your application
4. Click to verify your new user
5. Perform 10 **incorrect logins** for your new user

### What Should Happen

After 5 incorrect password attempts, the Lockout should be triggered.

### What Actually Happens

The form always returns the user back to the user login form with "Incorrect login attempt".

Looking at the localdb database after 10 failed attempts:
* `LockoutEnabled` is `True`
* `LockoutEnd` is `null`
* `AccessFailedCount` is `0`

So it looks like `AccessFailedCount` is not being incremented.

### Additional Things I've Tried

I have tried explicitly setting the lockout settings (in case the defaults were incorrect)

```csharp
            services.AddDefaultIdentity<IdentityUser>(options =>
            {
                options.SignIn.RequireConfirmedAccount = true;

                options.Lockout.AllowedForNewUsers = true;
                options.Lockout.MaxFailedAccessAttempts = 2;
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
            })
                .AddEntityFrameworkStores<ApplicationDbContext>();
```

### Further technical details
- ASP.NET Core version: 3.1
- Visual Studio 2019: 16.4.5

### Additional Notes

Again, this is with an **out-of-the-box** project generated by Visual Studio 2019.

**Comment by HaoK** [comment]
Yes this is by design, we don't lockout on password failures by default, you have to scaffold the login page https://github.com/dotnet/aspnetcore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Login.cshtml.cs#L132 and set true for the flag

**Comment by mwhouser** [comment]
Thanks @HaoK .

Is this documented somewhere to be known before scaffolding out the Login page?
