### ISSUE TITLE
HttpSys windows authentication not working across trusted domains

### ISSUE THREAD

**Issue by slewis74** [dotnet/aspnetcore#20091]
### Describe the bug
When hosting a web site in HttpSys that uses Ntlm authentication, the authentication works correctly for users on the same domain as the host server but fails for users on a trusted domain.

Users on the trusted domain get a popup requesting credentials

![image](https://user-images.githubusercontent.com/4229735/77380395-ace71900-6dc6-11ea-8a94-16741bad2905.png)

### To Reproduce
Attached is a simple web app that we've been using to test with. 
[OctoNtlm.zip](https://github.com/dotnet/aspnetcore/files/4372724/OctoNtlm.zip)

To reproduce the issue, run it up then hit the root url as a user from the same domain as the host to see that it echos out the correct user details.
Then hit the url as a user from a trusted domain (from a machine that's a member of the trusted domain).

If you enter credentials in the popup for a user on the trusted domain the authentication still fails. If you enter the user details of a user from the host's domain it will authenticate correctly.

### Further technical details
- ASP.NET Core version 3.1
- Tested on Internet Explorer and Chrome

We deliberately enabled anonymous access in the test app, and returned the 401 ourselves when the user identity isn't authenticated, so we could see more of what was happening. If you disable anonymous access the browser exhibits the same behaviour, but the handler code never gets called because the authentication isn't working.

Also attached are Wireshark captures from both the working and non-working machines. The challenge appears to be consistent between the 2, but the failing one isn't getting a user identity set and returns the 401 again.
[WiresharkCaptures.zip](https://github.com/dotnet/aspnetcore/files/4372764/WiresharkCaptures.zip)

**Comment by Tratcher** [comment]
@blowdart?

This isn't anything that AspNetCore has control over, the auth is happening in kernel mode down inside Http.Sys.

Variations to test:
- Can users from the other domain access file shares on the web server?
- Does this work in IIS using kernel mode or user mode auth?
- Does it work in [Kestrel](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#kestrel) using user mode auth?

**Comment by slewis74** [comment]
Users from the other domain can access file shares without troubles. 

We're hitting this issue as part of moving our product from .NETFramework to .NETCore. The product is installed by our customers, and AD authentication is one of the options we've always supported. Crossing the domain boundary worked when we were using HttpListener, and in the same test environment now we're seeing HttpSys drop users from the second domain.

We'd tried Kestrel and haven't had any luck with it (got it to work locally for the same domain but not currently working on a remote machine even on the same domain). Admittedly we haven't dug too far because it isn't actually an option for us, the majority of our customers who use AD are relying on Ntlm. Similarly IIS isn't an option, our product has always been self hosted.

**Comment by Tratcher** [comment]
The main difference between HttpSys and HttpListener is that HttpListener used user-mode authentication, where HttpSys uses kernel mode auth. That means the auth now happens under the machine account rather than the process's user account. I've seen that mean you needed to change where SPNs were configured, but I don't know what the impact would be across domains.

I suggested IIS only because it supports both kernel and user mode auth and you could compare the behaviors.

**Comment by anurse** [comment]
@Tratcher Sounds like we don't believe there's actionable work on our side here right (since it's in the OS)? I'm going to put this in Discussions for now. If something actionable comes up, we can engage the necessary teams or track some work on our side.
