### ISSUE TITLE
IOptionsMonitor Not Working with DataAnnotationsValidator

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/aspnetcore#20092]
### Describe the bug
Trying to wire up DataAnnotationsValidator that validates a value from IOptionsMonitor renders always valid state, regardless if the Annotations are met. My app is Server-Side Blazor 3.1

### To Reproduce
``` C#
// POCO that is hydrated with Config and exposed via IOptionsMonitor
public class ConfigWrapper
{
    [Required]
    [StringLength(10, ErrorMessage = "Name is too long.")]
    public string HueIpAddress { get; set; }
}

// Blazor Component

@inject IOptionsMonitor<ConfigWrapper> Config

<EditForm Model="@Config.CurrentValue.HueIpAddress" OnValidSubmit="HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <InputText id="name" @bind-Value="@Config.CurrentValue.HueIpAddress" />

    <button type="submit">Submit</button>
</EditForm>

@code {

// this always fires, even if HueIPpAddress is empty string
private void HandleValidSubmit()
{
  Console.WriteLine("OnValidSubmit");
}

```

### Further technical details
- ASP.NET Core version - 3.1
- Include the output of `dotnet --info`

```powershell
PS C:\dev\Personal\PresenceLight\src\PresenceLight.Worker> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20155.7
 Commit:    1c44853056

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20155.7\

Host (useful for support):
  Version: 5.0.0-preview.1.20120.5
  Commit:  3c523a6a7a

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.1.20155.7 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.1.20127.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
![image](https://user-images.githubusercontent.com/8878502/77383216-96e24580-6d3f-11ea-8c71-b8efe53c4f6d.png)

**Comment by javiercn** [comment]
@isaacrlevin thanks for contacting us.

@haok can you follow up here?

**Comment by isaacrlevin** [comment]
@HaoK any update here?

**Comment by JunTaoLuo** [comment]
I believe this issue is mostly concerned with the use of DataAnnotationsValidator so I'm going to tag it as such. 

I'm not too familiar with the component so I'm not sure what could be causing trouble here. However, I took a look at the documentation at https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1 and it seems to me that the `Model` field usually references the model class whereas in the code snippet here, it's referring to a specific field on the model class so that might be an issue. I'm also unsure how DataAnnotationsValidator would interact with injected option classes and whether that would work as intended in the code snipped.

**Comment by HaoK** [comment]
Options in the monitor are configured once and then only modified if change notifications are setup.  My sense here is that the monitor hasn't been hooked up to refresh when inputs change, so the initial state is always going to be the state without notifications.

**Comment by isaacrlevin** [comment]
@HaoK is this what you are referring to?

```
config.SetBasePath(Directory.GetCurrentDirectory())
      .AddJsonFile("PresenceLightSettings.json", optional: false, reloadOnChange: true)
```

**Comment by HaoK** [comment]
Yeah, if you do that, IOptions.CurrentValue should refresh its value, that said, I'm not sure exactly how that would interact with the data annotations validator

**Comment by isaacrlevin** [comment]
I have that in this case and it still does not work

**Comment by pranavkm** [comment]
DataAnnotationsValidator does not subscribe to options changes and it does not look like the app wires it up. Additionally, it seems a bit strange to validate an options type, the component is generally meant to validate forms, not server options.
