### ISSUE TITLE
With .Net 5, "dotnet restore" for F# mvc succeeded with warning NU1603.

### ISSUE THREAD

**Issue by yunwei00q** [dotnet/aspnetcore#20094]
**Steps to reproduce**
Install SDK 5.0.100-preview.2.20169.1(runtime-5.0.0-preview.2.20160.6)
Run "dotnet new mvc -o fsmvc02 -lang f#"

**Expected behavior**
Dotnet restore works fine.

**Actual behavior**
dotnet restore succeeded with warning NU1603: fsmvc depends on Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation (>= 5.0.0-preview.2.318.dev) but Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.0-preview.2.318.dev was not found. An approximate best match of Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.0-preview.2.20121.6 was resolved.
![image](https://user-images.githubusercontent.com/57380211/77389949-7f529d80-6dcf-11ea-913c-016b8214d84c.png)

Note: This is not repro on C# mvc.
This is repro on .NET SDK 5.0.100-preview.1.20155.7, not repro on  .NET SDK 5.0.100-preview.2.20163.4.

Dotnet –info:
.NET Core SDK (reflecting any global.json):
Version: 5.0.100-preview.2.20169.1
Commit: 0d8d4288ac

Runtime Environment:
OS Name: Windows
OS Version: 10.0.18362
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-preview.2.20169.1\

Host (useful for support):
Version: 5.0.0-preview.2.20160.6
Commit: d12f79a4d1

.NET Core SDKs installed:
5.0.100-preview.2.20169.1 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 5.0.0-preview.2.20167.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.0-preview.2.20160.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have a separate issue tracking this, which will be fixed soon.
