### ISSUE TITLE
Analyzer not kicking from "dotnet build" if IDE not open

### ISSUE THREAD

**Issue by tebeco** [dotnet/aspnetcore#20095]
### Describe the bug
`StartupAnalyzer` not showing `Warning` unless i opened `Vs2019` in the background

### To Reproduce

EDIT: When i close VSCode i got no more warning
EDIT 2: Having `Vs2019` open change nothing => no warn in the console, Vs does generate a warning "only for itself in the "error panel"
EDIT 3: The warning shows up in the console ONLY is `VsCode + Omnisharp` are running on this "Workspace"

meaning that i probably wont get that warning on the CI ?

As i was curious about how i could code a custom analyzer, i tried to take a look at the analyzer supposedly in charge or raising a `Warning` when, in `3.x` your startup look like this :
all i did was `dotnet new webapi -n xxxx`

`❯ cat .\Startup.cs`
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace findanalyzer
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(); // <============================
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();
            app.UseMvc(); // <============================

        }
    }
}
```

When toying with it yesterday i think i managed to see that warning once yesterday but had to leave (not sure i saw it) <=== i say that because i forced build and restore
Then this morning, right before debugging [the actual `StartupAnalzyer`](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Analyzers/src/Startup/StartupAnalzyer.cs) i wanted to give it a shot again ONLY from the terminal and could not get a warning :

NoWarning :
![image](https://user-images.githubusercontent.com/2266487/77400530-9f706580-6dab-11ea-9e78-d433e37df6aa.png)

Starting 2 IDE to get the warning in the consolse
(After investigation, Vs2019 change nothing, it's `VsCode / Omnisharp` that make it appear in the `dotnet build` in a terminal)
![image](https://user-images.githubusercontent.com/2266487/77400726-ea8a7880-6dab-11ea-847f-da1d323b4dcd.png)

Closing VSCdoe and VS2019 :
![image](https://user-images.githubusercontent.com/2266487/77401020-77cdcd00-6dac-11ea-98ca-b465488c14e2.png)

### Further technical details
- ASP.NET Core version : `5.0.0-preview.1.20124.5`
- `dotnet --info`
❯ d --info
```
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20155.7
 Commit:    1c44853056

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19587
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20155.7\

Host (useful for support):
  Version: 5.0.0-preview.1.20120.5
  Commit:  3c523a6a7a

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.1.20155.7 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.1.20124.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.1.20120.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.1.20127.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE
  VS Preview 16.6 Preview 1
  VS Code Insider

**Comment by pranavkm** [comment]
@tebeco it might be the result of build incrementalism - the compiler, and consequently, might not run if everything is up to date from a previous build. Could you try running `dotnet msbuild /t:Rebuild` or `dotnet build -force` when VS is closed?

**Comment by tebeco** [comment]
`dotnet build --force` does not show any warning
also it's `VsCode` that make it work in the console

`Vs2019` only raise a warn for himself

NOK
* only console `dotnet build` => no warn
* only console `dotnet build --force` => no warn
* Vs2019 + console `dotnet build` => no warn

OK :
* VsCode + console `dotnet build` => warn

**Comment by pranavkm** [comment]
What about `dotnet msbuild /t:Rebuild`?

**Comment by sharwell** [comment]
This analyzer package has a dependency on Microsoft.CodeAnalysis.Workspaces:

https://github.com/dotnet/aspnetcore/blob/49f23649918407f72acce29f143e3c402e040c59/src/Analyzers/Analyzers/src/Microsoft.AspNetCore.Analyzers.csproj#L22

This dependency is not available during command line builds, but is available inside the IDE. Some runtime scenarios allow the package to still work with this dependency in place, but others instead have a silent failure. The dependency will need to be removed if you want to ensure the analyzer will run during command line builds. I can send a PR for this.

**Comment by tebeco** [comment]
@sharwell 
oO i was not aware that this extensions meant "only from IDE", thx a lot ^^

As i''m trying to write an analyzer, i was looking for an existing analyzer that would
* give a warning
* make the CI raise Warn/Error
* be intrusing in the IDE on purpose
* not be using MsBuild 14 project still ;) (because some templates create `net4xx` project :s)

As i'm very very interesting about the PR (because i have no idea yet how i would have to do this : the "only console + `dotnet build`)

===> thought i think that would be a "breaking change", if project already have `WarnAsError`

**Comment by tebeco** [comment]
@sharwell if you got any example some how about that, i would be very very curious ;)

**Comment by sharwell** [comment]
I looked into this some more, and found that even though the project references Microsoft.CodeAnalysis.CSharp.Workspaces, it is not using it. The reference should still be corrected, but it wouldn't be the cause of failing to run during command line builds.

**Comment by tebeco** [comment]
@sharwell

all the unit test tests are KO for me on the solution
i found 2 different things to change to make them pass but i'm not sure how it will impact the CI and/or Helix

do i make a PR for the discussion about these changes ?

or do i make 2 commit and link them here ?

also the source might not use `Microsoft.CodeAnalysis.CSharp` directly but the `GetCompilationAsync(....)` during the`FeatureDetection` or the creation of `AdhocWorkspace` seems very "near" to that assembly or it transitive dependencies, no ?

**Comment by tebeco** [comment]
@sharwell 
Do you think you could you take a look at https://github.com/dotnet/aspnetcore/pull/20274 ?

it has no direct relation ship with this issue, but this is what i had to do to be able to make the tests pass successfully on VS locally.
My only question on that PR is that i'm not sure if it can break `Helix` or not

**Comment by tebeco** [comment]
also you said :
> The dependency will need to be removed if you want to ensure the analyzer will run during command line builds. I can send a PR for this if you want

Would this work in both IDE + only console scenario ?
I'm trying to create an analyzer that will `warn / error` in the CI, but still be intrusive on the IDE of developer
I don't understand yet why removing a dependency would enable "reporting" :D 

so if i do remove it from my fork from `dotnet/aspnetcore` i could try to use the generated `nupkg` to see if that does have an impact right ?

**Comment by tebeco** [comment]
> What about `dotnet msbuild /t:Rebuild`?

@pranavkm the `dotnet msbuild /t:Rebuild` seems to generate the proper warning from the console yes

@sharwell 
I changed both `src` and `test` Reference
from `<Reference Include="Microsoft.CodeAnalysis.CSharp.Workspace" />`
to `<Reference Include="Microsoft.CodeAnalysis.CSharp" />`

Created a new project and added a `RestoreSource` location by doing (in a `Directory.Build.props`):

```
<Project>
    <PropertyGroup>
        <RestoreSources>
            $(RestoreSources);
            C:\dev\github\tebeco\aspnetcore\artifacts\packages\Debug\NonShipping;
        </RestoreSources>
    </PropertyGroup>
</Project>
```
here is the result :
RED : as you can see, still no `Warn`
BLUE : `dotnet msbuild /t:Rebuild` seems to work (but that's a "No goal: since the CI will run `dotnet build` (and/or `dotnet test|publish`)
GREEN : possible conflict since i use `AspNetCore 5.0-preview` that also has that analyzer as a transitive

![image](https://user-images.githubusercontent.com/2266487/77829265-4abd4980-7121-11ea-973a-fa0e7706b382.png)

**Comment by wtgodbe** [comment]
@sharwell do you know if we ever figured out the root cause of this issue?

**Comment by sharwell** [comment]
The last image suggests you have two different analyzer references to the same assembly name. The analyzer driver only supports loading one of them, and I'm not sure which one that will be. You'll want to use a binlog to find a way to ensure that only one copy of Microsoft.AspNetCore.Analyzers makes its way to the compiler.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're going to close this issue as we haven't heard many other people impacted by this. Plus, this seems to be caused by a local build which is not something we ship.
