### ISSUE TITLE
Allow use of HTTP/2 for OIDC Backchannel

### ISSUE THREAD

**Issue by jeffreyrivor** [dotnet/aspnetcore#20096]
### Is your feature request related to a problem? Please describe.
I'm trying to configure the `HttpClient.DefaultRequestVersion` to HTTP/2 and set that as the `OpenIdConnectOptions.Backchannel`, but `OpenIdConnectHandler.RedeemAuthorizationCodeAsync` and `OpenIdConnectHandler.GetUserInformationAsync` use `HttpClient.SendAsync(HttpRequestMessage)` so the `DefaultRequestVersion` is ignored in favor of the `HttpRequestMessage.Version` property, which is set to HTTP/1.1 by default.

### Describe the solution you'd like
Easiest solution would be for all calls to use the `HttpClient` convenience methods like `HttpClient.GetAsync` or `HttpClient.PostAsync` so that the `DefaultRequestVersion` is used. Another option would be to just set the `HttpRequestMessage.Version` to `HttpVersion.Version20`. These may be too subtle for maintainers to remember (it's really easy to go back to using `SendAsync` or not set `HttpRequestMessage.Version`), so a configuration option or other seam might be a good middle ground.

### Additional context
[Microsoft.Identity.Protocols.HttpDocumentRetriever](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols/Configuration/HttpDocumentRetriever.cs#L90) used by `OpenIdConnectOptions.ConfigurationManager` actually calls `HttpClient.GetAsync(string, CancellationToken)`, so it does respect the `HttpClient.DefaultRequestVersion` property when using the backchannel to get the OIDC metadata.

**Comment by Tratcher** [comment]
I see two instances of HttpRequestMessage in the OIDC code.

This one could easily be switched to use PostAsync:
https://github.com/dotnet/aspnetcore/blob/543e73b6b857bf5c6b9744bd3c01b3b4d56db42e/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L807-L810

This one however can't because it needs to add the header:
https://github.com/dotnet/aspnetcore/blob/543e73b6b857bf5c6b9744bd3c01b3b4d56db42e/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L870-L872
Maybe it should copy the defaults from the HttpClient instance.

Workaround: Add a DelegatingHandler to your HttpClient Backchannel that changes HttpRequestMessage.Version.

Recommend up-for-grabs.

**Comment by Tratcher** [comment]
While we're at it, OAuthHandler has the same issue:
https://github.com/dotnet/aspnetcore/blob/543e73b6b857bf5c6b9744bd3c01b3b4d56db42e/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L196-L199

**Comment by huysentruitw** [comment]
I want to work on this. Do we also have to copy the `DefaultRequestHeaders` from the `Backchannel`'s `HttpClient`?

**Comment by jeffreyrivor** [comment]
@huysentruitw, that's a good question. I was mostly concerned with `DefaultRequestVersion` but the user can configure a bunch of other default headers as well that should be arguably respected as well. It may make sense to copy all headers then overwrite the ones that need to be specific values (like `Cache-Control` to no-cache, no-store, max-age 0).

**Comment by Tratcher** [comment]
> I want to work on this. Do we also have to copy the `DefaultRequestHeaders` from the `Backchannel`'s `HttpClient`? Or is just the version enough?

No, DefaultRequestHeaders are automatically copied to every request.
https://github.com/dotnet/runtime/blob/b80554c56a4c38695518283ef91be5ad5a407a49/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L775-L778
