### ISSUE TITLE
.NET Core 3.1 WCF Web Service Reference Provider error

### ISSUE THREAD

**Issue by mujgancihan** [dotnet/aspnetcore#20097]
Hi,
I have an application created in NET Core 3.1 and I am trying to add a web service by  
WCF Web Service Reference Provider.
But it fails and shows the error below;

Importing web service metadata ...
Number of service endpoints found: 2
Scaffolding service reference code ...
Error:Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\3.1.200\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
Done.

Could you please help me to understand the error reason?

Regards,
Mujgan Chan

**Comment by javiercn** [comment]
@mujgancihan thanks for contacting us.

@Pilchie do you know if this is us, VS or dotnet/runtime?

**Comment by blowdart** [comment]
Neither, it's https://github.com/dotnet/wcf

I don't have permissions to move it. @mujgancihan could you post your issue there and close this one?
