### ISSUE TITLE
Blazor server error 400 fails to negotiate to server when using routing

### ISSUE THREAD

**Issue by Kasper888** [dotnet/aspnetcore#20090]
![Blazor Routing Error](https://user-images.githubusercontent.com/10082735/77368614-4978cf00-6d65-11ea-80d6-3553ac683149.png)

### Describe the bug
As shown in the attached screenshot I'm using routing:

@page "/addbrand/{BrandId:guid}"

When I refresh the url https://localhost:44379/addBrand/1abc52f3-c371-4566-847d-1a986f093396 this lead to error 400 Failed to load resource as the url of balzor negotation changed to https://localhost:44379/addBrand/_blazor/negotiate?negotiateVersion=1   instead of
https://localhost:44379/_blazor/negotiate?negotiateVersion=1

https://localhost:44379/addBrand/_framework/blazor.server.js    instead of
https://localhost:44379/_framework/blazor.server.js 

and this happened to all of links in _host.cshtml file.

Got Exceptions? Yes, browser console log:
[2020-03-23T21:57:35.846Z] Information: Normalizing '_blazor' to 'https://localhost:44379/addBrand/_blazor'.
_blazor/negotiate?negotiateVersion=1:1 Failed to load resource: the server responded with a status of 400 ()
blazor.server.js:1 [2020-03-23T21:57:35.917Z] Error: Failed to complete negotiation with the server: Error

### Further technical details
- ASP.NET Core version: 3.1
- The IDE: VS 2019

**Comment by Kasper888** [comment]
Solved by set
<head>
...
    <base href="~/" />
...
</head>

**Comment by hakanaltindis** [comment]
thx for the answer. It worked for me.

**Comment by hakanaltindis** [comment]
> Solved by set
> 
> ```
> <head>
> 
>     <base href="~/" />
> 
> </head>
> ```

thx for the answer. It worked for me.
