### ISSUE TITLE
Suddenly ASP.NET Core Identity not working for any of my applications in my machine.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#20105]
Strangely! Suddenly ASP.NET Core Identity is not working for any of my applications in my machine. Whenever I am trying to login with right credential, `SignInResult` is Succeed but not setting Identity Cookie to the browser and showing the following error in browser:

> It looks like the webpage at https://localhost:44330/Identity/Account/Login might be having issues, or it may have moved permanently to a new web address.
> ERR_HTTP2_PROTOCOL_ERROR

**ASP.NET Core Version: 3.1.2**
**Visual Studio Version: 16.4.5**

**Note: This is neither a bug nor a feature request. I just need a help to guess the problem.**

**Comment by mkArtakMSFT** [comment]
Hi. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@blowdart, @anurse does this error seems familiar? Any hints?

**Comment by blowdart** [comment]
No, nor is it identity. We don't do anything to make a protocol error occur.

**Comment by anurse** [comment]
Yep, this looks like an HTTP/2 protocol failure of some kind. It's not related to Identity as far as I can tell. cc @Tratcher @halter73 

@TanvirArjel can you provide a runnable sample to reproduce the problem? If not, can you share more details about the environment you're running in? What OS are you on? What browser are you using? How are you hosting the application (in IIS or stand-alone)?

**Comment by halter73** [comment]
In addition to what @anurse asked for, [debug level logs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-filtering) might also be helpful.

**Comment by TanvirArjel** [comment]
@anurse Its happening for all application so you can create a brand new ASP.NET Core 3.1 application with Visual Studio 2019 16.4.5 with `Individual Account Authentication` selected!

**Here is the necessary info**:
Visual Studio Version: 2019 (16.5.4)
ASP.NET Core Version: 3.1.2
Os: Windows 10 
Server: IIS Express
Browser: Latest Chromium Microsoft Edge (80.0.361.69),Latest Google Chrome

**Comment by Tratcher** [comment]
ASP.NET Core shouldn't be able to cause any HTTP/2 protocol violations on IIS/Express, that's all managed at a much deeper layer in the OS. This is most likely to be affected by the OS version. What specific windows 10 version?

I'm using:
Win10 2004 (19041.153)
ASP.NET Core Version 3.1.3 (shouldn't affect this)
VS 16.5.1 (shouldn't affect this)

Kestrel also works fine, but it uses a very different HTTP stack.

What about the new cookie policy? Have you enabled any of the new advanced settings?

**Comment by TanvirArjel** [comment]
@Tratcher  My Version is: Windows 10 2004 (19587.1000)! Same problem is also happening in other PC's too.

**Comment by TanvirArjel** [comment]
>This is most likely to be affected by the OS version

Okay! @Tratcher guessed it correctly! The problem actually lies in the Operating System. I was using the latest preview of Windows 10 which **Windows 10 2004 (Os build: 19587.1000)**.

Now I have downgraded to **Windows 10 1909 (Os build: 18363.720)** and everything is working fine.
So anyone of you can report this fatal issue to the Windows 10 Team.

**Before finishing! Thank you so much everybody participated here and showing your heartfelt interest to identify the problem. You people are doing fantastic job! Wish you all the very best. Stay safe and sound during the this pandemic time.**

Regards
TanvirArjel

**Comment by Tratcher** [comment]
Thanks, I've passed that along to the Windows team.

**Comment by Tratcher** [comment]
Confirmed, they were able to repro this in 19587 but it's already fixed in 19595. Let us know if you see otherwise.
