### ISSUE TITLE
Singleton Services in Blazor wasm project

### ISSUE THREAD

**Issue by mselinger75** [dotnet/aspnetcore#20101]
I implemented Counter service like

public class CounterService
	{
		public int Counter { get; set; }
	}

Then Register it as

builder.Services.AddSingleton<CounterService>();

and then Counter page looks like:

@page "/counter"
@inject CounterService CounterService

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
	private int currentCount => CounterService.Counter;

	private void IncrementCount()
	{
		CounterService.Counter++;
	}
}

When i open a Counter page, then click "Click me" button several times, then navigate to home page, and return back to Counter page - Counter preserves its value, which is expected behavior.

But, if i open Counter page in another browser i see Counter value = 0, which I expect to be let say 10 - the value from a first browser window. 

Am i missing something? How do i implement Singleton service shareable  between multiple browser windows?

Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
I assume this is because Blazor WASM stores the state in memory at the moment. When you're opening a new browser window, you essentially are starting a new process, which doesn't share the memory with the other one.
To make sure the state maintained, you should implement some state-management for your application, to store the data in browser local storage.
@pranavkm am I missing something here?

**Comment by mselinger75** [comment]
@mkArtakMSFT in this case the whole idea behind Singleton doesn't make sense for WASM. Because for Server Side Blazor it works perfectly. So Basically this means i can not write a code shared between Blazor Server Side and WASM, i should always keep in mind that they handle DI differently. Thanks.

**Comment by pranavkm** [comment]
Singetons have the lifetime of an application. Each browser tab is a separate application (just as with any SPA application). 

> Basically this means i can not write a code shared between Blazor Server Side and WASM

If you aren't already familiar with how Blazor works, have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1. Blazor WASM runs inside the browser sandbox, so your application is constrained in different ways than a Blazor server applications. In general, you should be able to re-use components, and the programming model between Blazor Wasm and Blazor Server. However implementations for things like data access are going to be very different in the two models.
