### ISSUE TITLE
AJAX calls using POST requires several steps

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#20106]
I can make an AJAX call like this:

**CSHTML**

    $.ajax({
        url: '?handler=Delete',
        data: {
            id: $(this).data('id')
        },
    });

**CS**

    public void OnGetDelete(int id)
    {
    }

But the following fails with a 400 error:

**CSHTML**

    $.ajax({
        type: 'POST',
        url: '?handler=Delete',
        data: {
            id: $(this).data('id')
        },
    });

**CS**

    public void OnPostDelete(int id)
    {
    }

It appears the second approach will work if I:

1. Add `@Html.AntiForgeryToken()` to the top of my CSHTML page.

2. Add this to my AJAX call:

        beforeSend: function (xhr) {
            xhr.setRequestHeader("XSRF-TOKEN",
                $('input:hidden[name="__RequestVerificationToken"]').val());
        },

3. And configure anti-forgery in my ConfigureServices method:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAntiforgery(o => o.HeaderName = "XSRF-TOKEN");
        }

It seems that this is far more difficult than it was in MVC. I'm curious if these are the intended workaround. A lot of articles show how to do this and they all do something different.

Is there any way to add something that would make this easier? We have `@Html.AntiForgeryToken()`. Could something like that be added that could be used in JavaScript. Am I the only one who thinks this could be simpler?

**Comment by javiercn** [comment]
@SoftCircuits thanks for contacting us.

MVC didn't autovalidate antiforgery tokens, so it was only simpler because you were missing [ValidateAntiforgeryToken] in your action (which made it safe to CSRF attacks).

There's no better way to do this (in the web in general) if you want to protect against CSRF (which you should).

**Comment by SoftCircuits** [comment]
> There's no better way to do this (in the web in general) if you want to protect against CSRF (which you should).

Understood. But so many things are easier in Razor Pages. It would be nice if there was some type of helper that made this as easy as MVC. Also, given the variety of ways people have worked around this, it might at least be nice to have the steps documented somewhere.

**Comment by javiercn** [comment]
@SoftCircuits there are already docs for this. See https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1#javascript-ajax-and-spas for details.

We don't plan to do anything specific about this for the time being, so I'm closing this issue.
