### ISSUE TITLE
Please provide Asp.NET Core 3.1 / Angular solution that uses Active Directory on Azure

### ISSUE THREAD

**Issue by Javaman2** [dotnet/aspnetcore#20102]
Currently there are no working examples of Azure AD working on .NET 3.1 Core/Angular solution.

If we can get an example, we would be able to (keep our jobs).

We have tried to convert the 2.2 and MVC examples to use the new Endpoints logic, but no luck.  Additionally we are thinking that there are CORS issues as well.  The example will remedy all of this.

**Comment by TropicalThunder** [comment]
Is your angular application setting the "withCredentials: true" flag?

**Comment by Javaman2** [comment]
In the startup config?

**Comment by TropicalThunder** [comment]
> In the startup config? By the way the MVC configurations are gone now, it's all Endpoint configuration. Our project was a Web API anyway (there are no examples of Web API projects)

No, this is in the actual angular code. Any HTTP requests to make against the Azure AD Web Api must have the "withCredentials: true" flag set, otherwise it will reject your request as 401.

**Comment by Javaman2** [comment]
But maybe I'm on wrong path, I thought that the HTTP request could go to the back-end to be authenticated and not directly to AD.  I've already proved the back-end has no problems authenticating. The webAPI code is not using that authentication scheme, rather it's using the AD authentication scheme as shown in all the examples.  I think you are saying I need to change the scheme too, plus adding the withCredentials flag.  Does the request go directly to AD or can the backend handle it?  We prefer the back-end to handle all authentication.

**Comment by Javaman2** [comment]
Still would like to see an example of how to authenticate an ASP.NET Core 3.1/Angular app, with Azure AD.

**Comment by danroth27** [comment]
Hi folks. The recommended sample for this scenario is here: https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi.
