### ISSUE TITLE
Authorization for endpoints outside MVC application like swagger not working

### ISSUE THREAD

**Issue by SandeepRCH** [dotnet/aspnetcore#20113]
.Net core 3.1 is expected to come with support for Authorization to endpoint routing outside of MVC. We have tried multiple ways of authorising the endpoints like swagger / custom endpoints.

The following code seems to authorize the user but it is not showing the swagger page.
The response body is empty for some reason and the swagger page never showed up.

```c#
 endpoints.Map("/swagger", async context =>
 {
              app.UseOpenApi();
              app.UseSwaggerUi3();
 }).RequireAuthorization(new AuthorizeAttribute(myPolicy));
```
Can we access the swagger page like this because removing the "RequireAuthorization" part the swagger page seems to be working fine.

Can someone help me fixing this issue or Is there any other issue using which the endpoints outside the MVC be authorised?

**Comment by javiercn** [comment]
@SandeepRCH thanks for contacting us.

Can you clarify for us what you think is not working? 

Is the authorization not being applied?

**Comment by rynowak** [comment]
@SandeepRCH - I suspect this isn't working because you're adding the middleware to the main pipeline instead of creating a new pipeline for routing to call.

Try it like this:

```C#
app.UseEndpoints(endpoints =>
{
    var pipeline = endpoints.CreateApplicationBuilder();
    pipeline.UseOpenApi();
    pipeline.UseSwaggerUi3();
    endpoints.Map("/swagger", pipeline.Build()).RequireAuthorization(new AuthorizeAttribute(myPolicy));
}
```

This creates a new middleware pipeline, attaches the swagger middleware to it, and then hooks it up to routing with the URL and policy you wanted.

**Comment by javiercn** [comment]
Closing as @rynowak anwered with a solution. If the solution doesn't work, feel free to comment and we'll reopen the issue.
