### ISSUE TITLE
Blazor-server HttpClient (external code) DI + Request Issue

### ISSUE THREAD

**Issue by ikkman** [dotnet/aspnetcore#20112]
### Describe the bug
I tried to provide HttpClient through DI for Blazor (server) app using the following:

`            services.AddHttpClient<EmployeeService>(client =>
                    {
                        client.BaseAddress = new Uri("https://localhost:5003/");
                    });
`
But it looks everything is freezing when I try to access the dedicated page that require HttpClient object. Therefore, I started to create HttpClient on my own at the moment just to pass this issue.

However, when I reached the Api call part, I received unexpected NullReferenceException (external code) from Blazor (server) specially when I make the call for Get method with an id.

`var response = await client.GetStreamAsync($"api/employee/{id}");`
OR
`var response = await client.GetAsync($"api/employee/{id}");`

NOTE: Accessing the API from a browser or even running the same code (HttpClient portion) from a terminal has no issue at all, everything is working as expected. 

### Exception Details

System.NullReferenceException: "Object reference not set to an instance of an object."
  at at BlazorIntro.SPA.Components.EmployeeDetails.BuildRenderTree(RenderTreeBuilder __builder)\n   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)\n   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)\n   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)\n   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

### Further technical details
- ASP.NET Core version
3.1.2
- Include the output of `dotnet --info`
[info.txt](https://github.com/dotnet/aspnetcore/files/4377648/info.txt)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS4Mac

**Comment by javiercn** [comment]
@ikkman thanks for contacting us.

@rynowak what's the guidance here?

**Comment by mkArtakMSFT** [comment]
@ikkman based on the exception stack trace this looks like an error in your component. Can you please review that one more time and if you believe there is still an issue on our end, share a small repro app with us to investigate.

**Comment by ikkman** [comment]
You can find the project repo here: [source](https://github.com/ikkman/blazorintro)

**Comment by ikkman** [comment]
Any temporary solution?

**Comment by javiercn** [comment]
> System.NullReferenceException: "Object reference not set to an instance of an object."
> at at BlazorIntro.SPA.Components.EmployeeDetails.BuildRenderTree(RenderTreeBuilder __builder)\n at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)\n at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)\n at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)\n at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

This seems to come from your rendering process, so I believe you have a null ref in the code on the UI.

**Comment by ikkman** [comment]
This is strange. When I debug the code-behind (EmployeeDetails), this exception is always raised when I make the asynchronous call to the Web API.

**Comment by ikkman** [comment]
By creating a dummy employee object as a default value by trying constructor or by property initialization, it looks the issue had been resolved. From this behavior, I can guess the rendering is trying to access the predefined property (Employee) before calling OnInitializedAsync.

**Comment by babelshift** [comment]
I came across a similar issue where a service method called from a component's `OnInitializedAsync` method was awaiting a response from an `HttpClient` get request and throwing a `NullReferenceException` in the component's rendering phase.

I have a feeling this is due to Blazor's ability to render the component's HTML and send it to the browser before the awaited call has finished. Once the callback fires, the component is updated with the new results via SignalR. If the rendering phase accesses whatever variable is data bound before the awaited call has finished, you'll see a `NullReferenceException`. The fix as mentioned by @ikkman is to create an empty object that Blazor can use until real results are returned and bound.

I'm not an authority on this so would love if anyone could correct me where I'm wrong.
