### ISSUE TITLE
IdentityConstants aren't Constants

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/aspnetcore#20122]
### Describe the bug
The Authentication Scheme strings in IdentityConstants aren't constant so they can't be used to differentiate the schemes in controllers. 

### To Reproduce
Find the example in the repo:

https://github.com/shawnwildermuth/ReproIdentityConstants

Essentially, try and add more than one Identity Provider (I used Jwt + Identity). But when I use the authorize attribute to specify the JwtBearer it's fine:

``` C#
  [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
  [Route("api/[controller]")]
  public class FooController : ControllerBase
  {
    public IActionResult Get()
    {
      return Ok(new { name = "Hello" });
    }
  }
```

But when I try to do the same with the IdentityConstants:

``` C#
  [Authorize(AuthenticationSchemes = IdentityConstants.ApplicationScheme)]
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

```

Can't compile as The ApplicationScheme constant needs to be a constant (not just readonly static).

### Further technical details
- ASP.NET Core version
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:

Visual Studio 16.5.0 (though it happens with just dotnet build so it's likely not related)

**Comment by blowdart** [comment]
@HaoK Can we address this, or should it be using the cookie scheme which is a constant?

**Comment by HaoK** [comment]
I guess at this point this isn't something we are ever going to change the values of, so we could switch these to const's, @ajcvickers any issue with that?

**Comment by shawnwildermuth** [comment]
The way I registered Identity didn't have the Cookie type as an option. I am sure I could have added it. That's the way I used to do it in 2.x. But I think the changes in Identity in 3.x caused this to change.

**Comment by blowdart** [comment]
@HaoK go ahead and do this please :)

**Comment by HaoK** [comment]
This is too big of a breaking change at this point for not much value, especially since IdentityServer depends on us now

**Comment by HaoK** [comment]
See https://github.com/dotnet/aspnetcore/pull/21343#issuecomment-622006329 for more context

**Comment by HaoK** [comment]
Reactivating so we can consider again if we want to do this for 8

**Comment by mikekistler** [comment]
Thanks for contacting us. This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
