### ISSUE TITLE
System.Net.Http.HttpMethod vs. Microsoft.AspNetCore.Http.HttpMethods

### ISSUE THREAD

**Issue by am11** [dotnet/aspnetcore#20127]
Since both provide same support except [`System.Net.Http.HttpMethod.Connect` is `internal`](https://github.com/dotnet/runtime/blob/7302fa490d4da1b2b806dfeb3d778636f9cd0121/src/libraries/System.Net.Http/src/System/Net/Http/HttpMethod.cs#L80-L86), is there a general guideline which one the devs should use?
Or can the (plural) one in this repo deprecated?

**Comment by javiercn** [comment]
@am11 thanks for contacting us.

Those two classes serve different purposes. If you are using ASP.NET Core APIs you should use `Microsoft.AspNetCore.Http.HttpMethods` and if you are using HttpClient APIs you should use `System.Net.Http.HttpMethod`

@Tratcher in case he wants to add something more.

**Comment by Tratcher** [comment]
Their types are different. HttpMethod is a class instance containing a string, where HttpMethods is static list of strings that can be used directly.

HttpMethod is required when working with HttpClient. HttpMethods can be used almost anywhere else.

Don't expect either to be deprecated any time soon.
