### ISSUE TITLE
Field used in blazor component shown as "value assigned but never used"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20137]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/945690/field-used-in-blazor-component-shown-as-value-assi.html)._

---
I have a blazor project with nullable enabled. Here I get loads of warnings for fields who VS thinks are assigned but never used. But when I search for references (see attachement) you can see that they are used in the blazor component and that VS actuall does figure out that this is a reference to the field.

---
#### Visual Studio Feedback System on 3/11/2020, 08:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Taylor Mullen [MSFT] on 3/18/2020, 11:09 AM: 

<p>Hello, would you mind providing a simple repro project so we can investigate further?</p>

#### Nino Padrutt on 3/18/2020, 02:25 PM: 

<p>Hi Taylor</p><p>I just wanted to create one, but I noticed it that with the 16.5 the issue is resolved.</p><p>Thanks<br>Nino</p>

#### Taylor Mullen [MSFT] on 3/18/2020, 02:29 PM: 

<p>Ah, good to hear. I'll mark this appropriately.</p>

#### Nino Padrutt on 3/18/2020, 02:37 PM: 

(private comment, text removed)
#### Nino Padrutt on 3/25/2020, 04:33 AM: 

Hi Taylor<br>I saw that this issue is still marked as resolved. Seeing my last comment and the example project this is so far not the case.<br>Thanks<br>Nino

---
#### Visual Studio Feedback System solved on 3/18/2020, 02:29 PM, 0 votes: 

<p>A fix for this issue has been released! Install the most recent release from <a target='_blank' href="https://visualstudio.microsoft.com/downloads/">https://visualstudio.microsoft.com/downloads/</a>. Thank you for providing valuable feedback which has helped improve the product.</p>

**Comment by NTaylorMullen** [comment]
Repro steps:
1. Create a new Blazor project (doesn't matter what type)
1. Set nullability 
1. Create a counter partial class: 
```C#
public partial class Counter
{
    private bool showSomething = false;
}
```
4. Add the following to `Counter.razor`:
```cshtml

@if (showSomething)
{
    <p>Hello World</p>
}
```
5. Build the project. You'll get:
```
1>------ Build started: Project: BlazorApp_CustomerRepro1, Configuration: Debug Any CPU ------
1>C:\Users\nimullen\source\repos\BlazorApp_CustomerRepro1\BlazorApp_CustomerRepro1\Pages\Counter.razor.cs(10,22,10,35): warning CS0414: The field 'Counter.showSomething' is assigned but its value is never used
1>BlazorApp_CustomerRepro1 -> C:\Users\nimullen\source\repos\BlazorApp_CustomerRepro1\BlazorApp_CustomerRepro1\bin\Debug\netcoreapp3.1\BlazorApp_CustomerRepro1.dll
1>BlazorApp_CustomerRepro1 -> C:\Users\nimullen\source\repos\BlazorApp_CustomerRepro1\BlazorApp_CustomerRepro1\bin\Debug\netcoreapp3.1\BlazorApp_CustomerRepro1.Views.dll
1>Done building project "BlazorApp_CustomerRepro1.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

```

---------------------

This looks to be an issue with how we generate the skeletons of our Blazor files in our pre-build step because that pre-build step removes all Razor content other than what's in `@functions` / `@code`. This would technically be fixed by source generators but those are on the cutline for .NET 5.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen why is step #2 (set Nullability) required here?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen why is step #2 (set Nullability) required here?

Copy and paste error. It isn't.

**Comment by yudielcurbelo** [comment]
This has not been resolved. If you declare a string variable in the code behind (.razor.cs) and assign it in the .razor file you will get the warning.

**Comment by celalergun** [comment]
For those who suffers from this strange phenomenon will please take a look at: https://stackoverflow.com/questions/61427520/separate-code-file-in-blazor-gives-bogus-warning-messages

**Comment by mikewodarczyk** [comment]
This should be fixed, but when I saw in one of the associated issues a suggestion to go back to using inheritance instead of partial classes, I decided to take a half step and just make these properties "protected" instead of "private".  The compiler doesn't complain about protected properties not being read because it doesn't know what you will do with them in a child class.  This workaround isn't a solution though because it takes away the needed check for variables that you declare and actually never use.

**Comment by janissimsons** [comment]
When is this going to be fixed? It's annoying to see those warnings from analyzers.

**Comment by NPadrutt** [comment]
Another work around is to make fields into properties. At least for me for properties the reference is calculated correctly.

**Comment by pranavkm** [comment]
Resolved as part of the source generator work.

**Comment by captainsafia** [comment]
@pranavkm Last I tried this, it still repros even with source generators in place. I think there's still some work that we need to do here.

See https://github.com/captainsafia/TestPartialClassAssignment.
