### ISSUE TITLE
How to deploy update without stop Blazor server website on IIS

### ISSUE THREAD

**Issue by ebattulga** [dotnet/aspnetcore#20132]
I was deployed blazor server on IIS through FTP. When user accessing the web, i cannot deploy file because it accessed (550 can't access file). Every update, I'm trying to stop web and deploy updated files and start web site. That's very annoying.

How to deploy update without stop web site?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Blazor has no specific instructions for deployment.
We recommend following the instructions provided at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#app_offlinehtm
