### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureAD.UI throws OptionsValidationException: The 'Instance' option must be provided, if there is another OpenId Connect Authentication

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/aspnetcore#20136]
### Describe the bug
Adding Azure AD Authentication fails if there is are more than one openid connect schemes registered.

This is the same bug as fixed in #13480 just in a different configuration type, this was fixed for the other types by @Tratcher  but unfortunately the same lines exist in:
https://github.com/dotnet/aspnetcore/blob/76add623c9d64c26e5cb847004903bc658a4f7df/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADOpenIdConnectOptionsConfiguration.cs#L23-L24

In the other files the following was changed in #13480
https://github.com/dotnet/aspnetcore/blob/76add623c9d64c26e5cb847004903bc658a4f7df/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADCookieOptionsConfiguration.cs#L23-L29

https://github.com/dotnet/aspnetcore/blob/76add623c9d64c26e5cb847004903bc658a4f7df/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADJwtBearerOptionsConfiguration.cs#L26-L32

### To Reproduce
The source code example was taken from https://github.com/dotnet/aspnetcore/pull/13327#issuecomment-574246887 where the same problem was noticed, but apparently no bug was filed.

```csharp
services.AddAuthentication()
.AddOpenIdConnect("okta", "Okta", options => Configuration.Bind("Okta", options));
.AddAzureAD(options =>
{
options.Instance = "https://login.microsoftonline.com/";
options.Domain = "tenant.com";
options.TenantId = "xxxx";
options.ClientId = "xxxx";
options.CallbackPath = "/signin-oidc";
});
```

**Comment by ArturDorochowicz** [comment]
Are there any workarounds known for this bug?

**Comment by castholm** [comment]
@ArturDorochowicz In our codebase we worked around this bug by doing the following:

```csharp
// Configure Azure AD as usual
services.AddAuthentication(AzureADDefaults.AuthenticationScheme).AddAzureAD(options =>
{
    Configuration.Bind("AzureAd", options));
}

// Temporary workaround for <https://github.com/dotnet/aspnetcore/issues/20136> 
services.Configure<AzureADOptions>(Options.DefaultName, options =>
{
    options.Instance = "https://login.microsoftonline.com/";
});

**Comment by ThatFlashCat** [comment]
Does the above fix work for adding event handlers (such as OnTokenValidated) as well? I've spent many hours this week trying to get an event handler working so I can manipulate user claims after signin. I was hopeful that the above would solve the problem but it doesn't look like it.

**Comment by blowdart** [comment]
Jun to retarget to 3.1
