### ISSUE TITLE
Support for Authorization Flow with PKCE

### ISSUE THREAD

**Issue by javitosanchez** [dotnet/aspnetcore#20134]
I cannot find a way to configure `CodeChallenge` or `UsePkce` parameter for PKCE auth flow in `Microsoft.AspNetCore.Components.WebAssembly.Authentication.OidcProviderOptions`. Is it possible?
If not, do you have plans to implement it?

Thanks!
Great work!

**Comment by javiercn** [comment]
@javitosanchez thanks for contacting us.

The client does this automatically when you set the response type to code.
