### ISSUE TITLE
How to identify which authenticationprovider a claim belongs to?

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/aspnetcore#20130]
The default “aspnetuserclaims” data table does not recognize the authentication provier

![微信图片_20200325215246](https://user-images.githubusercontent.com/39435771/77543851-3a1f9000-6ee3-11ea-803d-8f211e0543d6.png)

**Comment by blowdart** [comment]
No it doesn't, because once you copy the claims out of a third party login and into your user claims they don't belong to the third party any more, they're yours, the claim owner is you, identity.

**Comment by bxjg1987** [comment]
thanks
