### ISSUE TITLE
Unselecting pages in the ASP.NET Core Identity scaffolder after selecting "Select all" doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20143]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/625722/unselecting-pages-in-the-aspnet-core-identity-scaf.html)._

---
Unselecting pages in the ASP.NET Core Identity scaffolder doesn't work when "Override all files" is selected.

Repro steps:
- Install .NET Core 3.0 Preview 6 SDK
- Create a new Blazor (server-side) app with authentication enabled using Individual User Accounts
- Right click on the project and select "New Scaffolded Item"
- Select the Identity scaffolder
- Select "Override all files"
- Unselect Account\Logout as this page is already customized in the app
- Select the data context class from the app
- Select Add

Expected result:
- Scaffolding all pages *except* for the Account\Logout page succeeds

Actual result:
- Scaffolding fails with an error that says the Account\Logout page already exists and asks if you want to overwrite it

---
#### Visual Studio Feedback System on 6/27/2019, 11:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/28/2019, 01:09 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Rogério Mauri on 10/12/2019, 04:05 AM: 

We are also having the same problem.
#### Rogério Mauri on 10/12/2019, 04:05 AM: 

We are also having the same problem.

---
### Original Solutions
(no solutions)

**Comment by Pilchie** [comment]
@vijayrkn - should this be in the scaffolding repo instead of here?

**Comment by vijayrkn** [comment]
This is an issue on the VS side. @deepchoudhery - is this the issue that is already fixed? else, can you create a bug on the VS side with the above information?

**Comment by deepchoudhery** [comment]
Yes it is already fixed on the VS side.

**Comment by deepchoudhery** [comment]
Yes I'll create a bug and investigate on the VS side.

**Comment by Pilchie** [comment]
This was already migrated from a feedback ticket (linked above).  Maybe just reactivate that and provide details?

**Comment by deepchoudhery** [comment]
I reactivated it and moved it to the WebTools/Scaffolding path.

**Comment by Pilchie** [comment]
Closing this as external.  Sorry for the noise here.
