### ISSUE TITLE
Intellisense reports missing types and namespace that are available and built correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20141]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/635256/intellisense-reports-missing-types-and-namespace-t.html)._

---
on a broken build Intellisense generates 332 errors. My c# files show all external references as invalid, same thing for blazor/razor files.
If I look at the actual build errors there are only 2 errors.

---
#### Visual Studio Feedback System on 7/8/2019, 02:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/8/2019, 11:43 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
erik could you please provide a repro app so we can investigate further?
