### ISSUE TITLE
Blazor WASM: Mono.Linker.Steps.XmlResolutionException after upgrade to 3.2p2

### ISSUE THREAD

**Issue by chucker** [dotnet/aspnetcore#20145]
### Describe the bug
The package changes in 3.2p2 (e.g. Microsoft.AspNetCore.Blazor -> Microsoft.AspNetCore.Components.WebAssembly) can cause the MSBuild/NuGet/Mono ILLinker infrastructure to get confused about references.

In my particular situation, a CI server (Azure DevOps Server) kept trying to link `Microsoft.AspNetCore.Blazor` because a previous revision of the code (before 3.2p2) had referenced it.

Even running `dotnet clean` on the CI server did not help; only by manually removing the `bin` and `obj` dirs on the CI server did I resolve the issue. (It's possible just deleting `obj/project.assets.json` would have been enough.)

### To Reproduce
1. Make an Azure DevOps pipeline with Blazor 3.2p1 or older
2. Build it
3. Upgrade to 3.2p2 without manually cleaning anything

### Suggestions
The issue here is that something in the assembly resolution pipeline didn't properly detect that the old references were stale. Ideally, ILLinker (or some step before it) should have detected that it can't link the reference because the reference no longer exists (nor is needed).

As lesser solutions,

* it'd be nice to have a `dotnet clean --prune-obj` option or similar, to run at the beginning of a CI pipeline. (@MarkStega suggests a script of `for /d /r . %%d in (bin,obj,ClientBin,Generated_Code) do @if exist "%%d" rd /s /q "%%d"` for the time being.)
* it would also be nice for ILLinker to give better diagnostics. The build log doesn't really _why_ it was trying to resolve that assembly:

<details>

```
Fatal error in Mono IL Linker
C:\Users\…\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview2.20160.5\targets\Blazor.MonoRuntime.targets(245,5): error : Unhandled exception. Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified> [C:\agent\_work\19\s\MyBlazorProject.Client\MyBlazorProject.Client.csproj]
---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
  at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
  at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
  at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
  at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
  at Mono.Linker.Steps.ResolveFromXmlStep.Process()
  --- End of inner exception stack trace ---
  at Mono.Linker.Steps.ResolveFromXmlStep.Process()
  at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
  at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
  at Mono.Linker.Pipeline.Process(LinkContext context)
  at Mono.Linker.Driver.Run(ILogger customLogger)
  at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
  at Mono.Linker.Driver.Main(String[] args)
```

</details>

### Further notes
There is no custom linker descriptor.

This issue is probably related with what #19561 originally ran into.

**Comment by javiercn** [comment]
@chucker thanks for contacting us.

You need to force the 3.1.102 SDK that is required with preview2. You can do so by invoking `dotnet new globaljson --sdk-version 3.1.102` in the root of your solution.

**Comment by chucker** [comment]
@javiercn it does, in fact, have a `global.json` that forces that SDK version. (And it does use the version, as confirmed by `dotnet --info` from within the dir.)

As I said, it works if I manually clean `bin` and `obj`, but it doesn't seem to properly invalidate the old packages.

**Comment by mkArtakMSFT** [comment]
We don't support incremental builds between previews. Consider cleaning your agents between builds.

**Comment by chucker** [comment]
>We don't support incremental builds between previews.

That's fair. However, the equivalent issue will occur (albeit less likely) in non-previews, as soon as a subsequent incremental build has fewer assembly references.

**Comment by mkArtakMSFT** [comment]
> > We don't support incremental builds between previews.
> 
> That's fair. However, the equivalent issue will occur (albeit less likely) in non-previews, as soon as a subsequent incremental build has fewer assembly references.

We have taken that point for consideration for sure. Reopening this to make sure we don't loose track of making sure that works.

**Comment by javiercn** [comment]
@chucker as an aside from this, I would recommend you run git clean -xdff on your CI prior to build.

**Comment by SteveSandersonMS** [comment]
I don't think this will still apply in 5.0. A large amount of the build infrastructure is all-new.
