### ISSUE TITLE
dotnet watch run does not forward SIGTERM to child process

### ISSUE THREAD

**Issue by rhyek** [dotnet/aspnetcore#20152]
I am running an Orleans silo inside a local kubernetes cluster (using KinD). This is meant for local development. At the same time, I am using [tilt](https://tilt.dev/) and its "live update" functionality which essentially copies any modified files on my local filesystem to the container running my app. Doing so, I can run my program with `dotnet watch run` inside the kubernetes-hosted container relying on its file-watching capabilities to avoid unnecessary image rebuilds.

However, rolling updates are necessary at times (testing scaling, for example) and I am having issues with the application not shutting down gracefully due to the fact that `dotnet watch run` does not forward the `SIGTERM` sent by kubernetes (unless of course I'm missing something) for pod termination.

This is not directly a Kubernetes-related issue, but I'm providing some context in case it helps anyone in some way. This is my current workaround unless someone has a better idea:

Program.cs
```c#
namespace OrleansService.Silo {

  public class Program {
    public static async Task Main(string[] args) {
      var builder = CreateHostBuilder();
      await builder.Build().RunAsync();
    }

    private static IHostBuilder CreateHostBuilder() {
      var builder = Host.CreateDefaultBuilder()
        .ConfigureLogging(logging => logging.AddConsole())
        .UseOrleans(siloBuilder => {
          siloBuilder.Configure<ClusterOptions>(options => {
              options.ClusterId = "main-cluster";
              options.ServiceId = "main-service";
            })
            .UseKubeMembership(opt => {
              opt.CanCreateResources = false;
            })
            .ConfigureEndpoints(new Random(1).Next(30001, 30100), new Random(1).Next(20001, 20100), listenOnAnyHostAddress : true)
            .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(TodoGrain).Assembly).WithReferences())
            .ConfigureServices(services => {
              services.AddSingleton<IDbConnectionService, PgConnectionService>();
            });
        });
      return builder;
    }
  }
}
```
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
RUN apt update && apt install python3 python3-pip -y
RUN pip3 install psutil

WORKDIR /src
COPY . .
WORKDIR /src/Silo

CMD exec python3 dev.py
```
dev.py
```python
import signal
import time
import subprocess
import psutil
import os
import re

child = subprocess.Popen(["dotnet", "watch", "run"])

running = True


def close(a, b):
    global running
    process = psutil.Process(child.pid)
    for proc in process.children(recursive=True):
        path = proc.exe()
        if re.search("/bin/.+netcoreapp", path):
            proc.send_signal(signal.SIGTERM)
            proc.wait()
            break
    running = False


signal.signal(signal.SIGINT, close)
signal.signal(signal.SIGTERM, close)

while running:
    time.sleep(1)

print("\nBye.")

```

**Comment by rhyek** [comment]
Hm. Why was this transferred to aspnetcore? I believe this is a general issue and in fact the sample code is for a console app.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
