### ISSUE TITLE
Add C# hover support to VS

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20158]
Similar to VSCode when you hover over a C# element we should be getting proper descriptions for these situations

**Comment by TanayParikh** [comment]
Task to track updates on VSLanguageServer for supporting sending hover events to multiple language server clients: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1095170

**Comment by TanayParikh** [comment]
Added in support for multiple hover handlers in VS. 

Now blocked on dotnet/roslyn accepting the `textDocument/hover` request: https://github.com/dotnet/roslyn/issues/43274 (Thanks @ajaybhargavb!)

**Comment by TanayParikh** [comment]
Updated to medium to account for the background work required to investigate and add in VS hover support + dotnet/roslyn acceptance of the `textDocument/hover` request.

**Comment by TanayParikh** [comment]
Moved HTML Hover support to https://github.com/dotnet/aspnetcore/issues/20963 so https://github.com/dotnet/aspnetcore-tooling/pull/1800 can be merged in and this can be closed. 

We're waiting on the HTML LSP to support the hover request.

**Comment by NTaylorMullen** [comment]
@TanayParikh can you work with the WTE folks to see if they're planning to add hover support in our timeframe? If so if you could have them or you yourself create an HTML hover support issue in VSTS and attach it to the user story [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1105382). 

Want to make sure we communicate what we're delivering in the VSTS channels and if that doesn't happen to include HTML that's ok as well (don't want to put unnecessary pressure on them). It'd just be an awesome positive to have that support 😄

**Comment by TanayParikh** [comment]
@NTaylorMullen sounds good. I got in touch with WTE folks, looks like they're looking to have a HTML hover support PR up in the next couple of days. I've created a tracking issue [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1106656).

I'll be sure to start testing / integrating it once the code is checked in. Will track those efforts here: https://github.com/dotnet/aspnetcore/issues/20963
