### ISSUE TITLE
Test failure: ClientStreaming_ResponseCompletesWithoutResponseBodyWrite

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#20164]
https://dev.azure.com/dnceng/internal/_build/results?buildId=572377&view=ms.vss-test-web.build-test-results-tab&runId=17948326&resultId=100548&paneView=debug

<details>
<summary>Error</summary>

```
Assert.Throws() Failure

Expected: typeof(System.Exception)

Actual: (No exception was thrown)
```

</details>

<details>
<summary>Stacktrace</summary>

```
at Microsoft.AspNetCore.TestHost.TestClientTests.ClientStreaming_ResponseCompletesWithoutResponseBodyWrite() in /_/src/Hosting/TestHost/test/TestClientTests.cs:line 476
--- End of stack trace from previous location ---
```

</details>

**Comment by shirhatti** [comment]
@JamesNK This seems related to a test you just added. Mind taking a look?

**Comment by shirhatti** [comment]
https://github.com/dotnet/aspnetcore/pull/17158/files
