### ISSUE TITLE
Test failure: FlowControl_ParallelStreams_FirstInFirstOutOrder

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#20169]
Filaure: https://dev.azure.com/dnceng/public/_build/results?buildId=573505&view=ms.vss-test-web.build-test-results-tab

Test: https://github.com/dotnet/aspnetcore/blob/8531e2e83fedf212d51270ba43f00ad85505f329/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs#L30-L110

**Comment by shirhatti** [comment]
@JamesNK Do you have time to take a look at this?

**Comment by anurse** [comment]
A fix has been made, so we'll close this. We're watching this in the quarantined test tracking.

**Comment by BrennanConroy** [comment]
Test is a lot more stable, but still fails occasionally

https://dev.azure.com/dnceng/internal/_build/results?buildId=597791

**Comment by anurse** [comment]
Are you able to take another look at this @JamesNK?

**Comment by halter73** [comment]
We might just have to delete this: https://github.com/dotnet/aspnetcore/pull/20830#issuecomment-614156327

**Comment by anurse** [comment]
Triage: We're going to remove the test. Turns out it's way more costly to maintain this test than the benefit it gives.
