### ISSUE TITLE
Plan for dotnet/aspnetcore-tooling consolidation

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#20168]
I have some meeting notes to convert to a POR

**Comment by JunTaoLuo** [comment]
FYI doc at https://github.com/aspnet/specs/blob/master/notes/5_0/tooling-consolidation.md

**Comment by Pilchie** [comment]
:eyes:

**Comment by Pilchie** [comment]
Nothing private in those notes, consider just putting here instead of internal?
