### ISSUE TITLE
About  <PreserveCompilationReferences>true</PreserveCompilationReferences>

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#20173]
This is my .props file. But it doesn't work. https://github.com/dotnet/roslyn/issues/42439

```C#
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
      <PreserveCompilationReferences>true</PreserveCompilationReferences>
    </PropertyGroup>
</Project>
```

**Comment by javiercn** [comment]
@NMSAzulX thanks for contacting us.

@pranavkm is this us? Can you comment on it?

@NMSAzulX can you provide details about the version of asp.net core you are using so that we can investigate this?

**Comment by NMSAzulX** [comment]
@javiercn  Thanks.  It is about asp.net core3.1. 

When I use Roslyn for dynamic compilation in Asp.net core3.1,  I need to use this node(`<PreserveCompilationReferences>true</PreserveCompilationReferences>`), 

The complete code
```C#
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>

  <ItemGroup>
          //................
  </ItemGroup>

</Project>

```
and I need to use (`<PreserveCompilationContext>true</PreserveCompilationContext>`) node in the Console Project. 
I have carried out a comparative experiment on this. Using the {packageId}.props file to publish on nuget, the console works normally, but web does not work properly, still prompting:

`InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery`

**Comment by pranavkm** [comment]
@NMSAzulX projects targeting the Web or Razor SDK set `PreserveCompilationContext = true` by default. However, they intentionally avoid copying ref assemblies to the publish directory to minimize the publish size. Setting `PreserveCompilationReferences = true` would be to way to go if you need to perform runtime compilation. In general, you should be fine setting both those properties in your project file.

**Comment by NMSAzulX** [comment]
@pranavkm  Thanks. How to automatically add this attribute to the user's project file when I download the library from nuget？ The answer from others is to publish the library using the {packageId} .props file. I've already tried it, and it's not successful.

**Comment by pranavkm** [comment]
@NMSAzulX have a look at the layouts and contents of the [Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.Runtimecompilation). It uses a `${PackageId}.targets` file to set these two properties:
https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Razor.RuntimeCompilation/src/targets/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.targets#L3-L4

**Comment by NMSAzulX** [comment]
@pranavkm Thank you. I'll try this way. :)

**Comment by NMSAzulX** [comment]
Wow, it works. @pranavkm @javiercn  Thank you.   Do I need to close this issue?

**Comment by pranavkm** [comment]
Sure, we could do that
