### ISSUE TITLE
OIDC Handler always uses token endpoint address from configuration

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/aspnetcore#20184]
the OIDC handler allows setting the address of the token endpoint dynamically in the `AuthorizationCodeReceived` event (on the `TokenEndpointRequest` class).

This information is then passed internally to the `RedeemAuthorizationCodeAsync` method - but inside there, the actual HTTP request is made using the static `_configuration.TokenEndpoint` 

https://github.com/dotnet/aspnetcore/blob/4fa5a228cfeb52926b30a2741b99112a64454b36/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L809

I am doing MTLS and need to change the token endpoint address to the MTLS version which is different to the "normal" token endpoint.

**Comment by javiercn** [comment]
Thanks for reporting this Dominic.

@blowdart @Tratcher can you take a look?

**Comment by leastprivilege** [comment]
There are multiple ways to work around that

* redeem the code yourself inside the event handler (thanks for that flexibility)
* provide a custom configuration manager. Unfortunately the default one does not have virtual methods - so this was more work than necessary

**Comment by Tratcher** [comment]
Oh. AuthorizationCodeReceivedContext.TokenEndpointRequest is a generic OpenIdConnectMessage and not every field is used for every action. That said, there's nothing preventing us from using the custom token endpoint if it's available. Looks like it would be a one line change here:
https://github.com/dotnet/aspnetcore/blob/4fa5a228cfeb52926b30a2741b99112a64454b36/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L809-L810
```
var requestMessage = new HttpRequestMessage(HttpMethod.Post, tokenEndpointRequest.TokenEndpoint ?? _configuration.TokenEndpoint);
```

**Comment by leastprivilege** [comment]
yep. thanks!
