### ISSUE TITLE
Transfer raw data between c# and js context 

### ISSUE THREAD

**Issue by sijakret** [dotnet/aspnetcore#20188]
Hi,

I need to pass a raw buffer (ArrayBuffer) from the js context to the a static method in the blazor(wasm) context and preferable modify that buffer in place (or at least return a modified copy).
The way web assembly works i think it might be tricky to modify the buffer in place unless it was allocated in the wasm memory object/the wasm heapin the first place.
I cannot find any documentation, issues or other pointers on this.
Is this supported?

Mono supports this in principle and this works in a simple mono project
https://github.com/mono/mono/blob/master/sdks/wasm/tests/browser/src/BindingsTestSuite/BindingsTestSuite.cs

I could not find a package that adds the corresponding WebAssembly bindings to, say the plain blazor client scaffold.

This issue should be very relevant to anyone thinking about doing actual data processing in the client c# context

Any input on how to do this?

Thanks!!

**Comment by javiercn** [comment]
@sijakret thanks for contacting us.

We don't support this type of interop in Blazor. Data needs to be serialized back and forth from .NET to WebAssembly.

@SteveSandersonMS might have some idea on how this might be achievable?

**Comment by sijakret** [comment]
@javiercn thanks for the reply

I think it is not just an issue of .NET <-> WebAssembly but also one of WebAssembly <-> js.

Somehow I was under the impression Blazor was using Mono under the hood, so I am a bit surprised the marshalling support of blazor is more limited than the one of Mono.
Is there a reason for this?
