### ISSUE TITLE
what about transaction-declarative-annotations?

### ISSUE THREAD

**Issue by athinboy** [dotnet/aspnetcore#20182]
### Is your feature request related to a problem? Please describe.

 It is  inefficiency and bothersome  to begin/commit/rollback transaction manually!
Is there any plan to support transaction-declarative-annotations? Just like spring for java:

https://docs.spring.io/spring/docs/5.2.5.RELEASE/spring-framework-reference/data-access.html#transaction-declarative-annotations

### Describe the solution you'd like

I think this is not belong to  EntityFramework,  but to aspnetcore or dotnet .

Thanks!

**Comment by javiercn** [comment]
@athinboy thanks for contacting us.

This is more of a question for the Entity Framework folks as they are the subject matter experts on the different database usage patterns and are better suited to comment on this issue. If you want a better and faster response I would suggest you file this issue on the [dotnet/efcore](https://github.com/dotnet/efcore) repository.

/cc: @ajcvickers any thoughts on this?

**Comment by ajcvickers** [comment]
@athinboy Can you explain more what you mean by, "I think this is not belong to EntityFramework, but to aspnetcore or dotnet?"

**Comment by athinboy** [comment]
@javiercn @ajcvickers 

First, apologize for my English , I hope  I can express myself clearly and exactly, and thanks for your time!
As a Application programmer,I know the transaction manage(called TM) in program work  is complex and prone to error. The Java Spring will manager transaction, rather than by person, and It is not only One of Spring's advantage.
But,when I want to develop the TM middleware for asp.net，I find it's  impossible. So I propose this issue.
thinks again!

additional,the msftbot is so bureaucratic !

**Comment by athinboy** [comment]
@ajcvickers 
I had program in c# for 10 years, But,four years ago , my company turn to Java. Because All the internet companies choose Java, and almose new project choose Java. 
there is spring.net and mybatis.net，but all of them is dead. It's very sad. The .net ecosystem is a little rigid.

Sorry!
