### ISSUE TITLE
Binary incompatible changes - and nuspec versioning

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#20183]
### Is your feature request related to a problem? Please describe.
Suppose I want to produce a nuget package that can be used in all LTS applications (let's focus on netcoreapp2.1 and 3.1).

My best bet right now is to target `netstandard2.0`. However suppose my library is compiled against an MS `2.1.0` dependency.
If a consumer adds my package to their `asp.net core 3.1.0` application, then the version of that dependency available at runtime would therefore now be `3.1.0` (and not 2.1.0 which my package was compiled against) and in this situation there can now be an exotic runtime error - a binary incompatibility can be encountered at runtime. This has happened a few times in the past and caused issues, like with `Microsoft.Extensions.DependencyInjection` where breaking changes were made to relocate certain methods to become extensions methods etc. The historic response from the aspnet core team to this problem to date, is that dependencies must all be recompiled against the newer dependency version when this occurs - but that answer is not the full picture because this does not explaiin how a single nuget package can support the latest LTS application with the later dependency, whilst also maintaining support for older / other LTS applications using "other" versions of the dependency. I'd like to discover if there is some agreed way to enable this.

To help with this, I'd like to know what MS's policy is on when binary breaking changes can be made. I'm hoping it will be something like this:

1. Binary breaking changes can be made between major version bumps only i.e between 2.1 and 3.0 etc etc.
2. If a binary breaking change is made between a minor increment, e.g 2.1.0 and 2.2.0 - it is eligible for a hotfix, i.e it will be addressed in 2.2.1

Also - I want to limit this issue to only caring about LTS. Its important I can publish a single nuget package that can be used in multiple LTS applications safely, be they 2.1.x or 3.1.x currently or any others you create in future.

If the policy is:

1. There will be only one LTS version in a major version range
    - e.g 3.1.0 is an LTS release, you won't ever also have a 3.2.0 or 3.3.0 LTS release concurrently.
2. Breaking changes that occur on the same major version number are elegible for a patch / hotfix.  

Then as long as each LTS release continues to track with a unique "Target Framework" that can be used to distinguish it in a nuspec, then we can do something like this in the nuspec (pseudo code):

```
// If the target framework = "netstandard2.0"
//      Include the = 2.1.X LTS dependencies.
<dependency id="microsoft.extensions.dependencyinjection" version="[2.1.0,3.0)" /> // version constraint protects consumers from potential binary incompatibilites that may not be patched

// If the target framework = "netstandard2.1"
//        Include the 3.1.X LTS dependencies.
<dependency id="microsoft.extensions.dependencyinjection" version="[3.1.0,4.0)" />// version constraint protects consumers from potential binary incompatibilites that may not be patched

// When the next LTS comes about, we assume there will be some new targetframework identifier so we can pick it out....

```

### Describe the solution you'd like
I'd like clarification over the above - what is the strategy for package authors to produce a single package that supports all potential LTS versions "Safely" - and not just for now, but that will hold up in the future as new LTS releases are made, veering on the side of safety for binary incompatibilities - i.e so we can enforce upper constraints if there is ever a chance of binary incompatibilities that MS won't see as bugs and resolve as hotfixes.

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

@davidfowl @Pilchie @DamianEdwards @JamesNK  any thoughts on this?

**Comment by Pilchie** [comment]
Addressing your questions as best I can:

> Binary breaking changes can be made between major version bumps only i.e between 2.1 and 3.0 etc etc.

That is our goal.

> If a binary breaking change is made between a minor increment, e.g 2.1.0 and 2.2.0 - it is eligible for a hotfix, i.e it will be addressed in 2.2.1

That's not actually possible for things in the shared framework - we can't have a hotfix version have different API surface area, because we don't have hotfix versions in Target Frameworks Monikers.  They aren't uniquely identifiable.  I.e. you can't put `netcoreapp3.1.4` in a `<TargetFramework>` element, and there is no reference assembly pack that specifies what's in it.

> There will be only one LTS version in a major version range
e.g 3.1.0 is an LTS release, you won't ever also have a 3.2.0 or 3.3.0 LTS release concurrently.

I don't think we guarantee that, though our [stated goal](https://github.com/dotnet/core/blob/master/roadmap.md) is to have every other major version be an LTS going forward.

> Breaking changes that occur on the same major version number are elegible for a patch / hotfix.

As above, I don't think so.

As for what you are trying to do, can you limit your audience to those using `netcoreapp`?  If so, I would suggest multi-targeting your library, and having your NuGet package provide a unique binary for each version you want to support.

**Comment by dazinator** [comment]
Thanks for the feedback on this.

I'm not sure I follow this bit:

> That's not actually possible for things in the shared framework - we can't have a hotfix version have different API surface area, because we don't have hotfix versions in Target Frameworks Monikers. They aren't uniquely identifiable. I.e. you can't put netcoreapp3.1.4 in a <TargetFramework> element, and there is no reference assembly pack that specifies what's in it.

I'd like to use a concrete example just to make sure things are as clear as they can be,

I produce the following nuget package: 
- `foo` version `1.0.0` 
    - targets `netcoreapp2.1.0`
        - deps: `microsoft.extensions.dependencyinjection` version `2.1.0`


The following consumer project adopts the package
- `bar`
    - targets `netcoreapp2.2`
        - deps:  `microsoft.extensions.dependencyinjection` version `2.2.0`

Note: the shared dependency has been bumped up to `2.2.0`

At this point, let's say a bug was discovered and a binary breaking change was introduced in the `microsoft.extensions.dependencyinjection` version `2.2.0` so that my library `foo` now produced runtime errors in the consuming application.

My question is:

1. Would MS policy be to fix that breaking change in a patch release of `microsoft.extensions.dependencyinjection` e.g version `2.2.1`

If so, then the solution for package producers would be: do nothing.
The solution for package consumers (i.e the application experiencing the problem) would be: Update their `microsoft.extensions.dependencyinjection` to version `2.2.1`

Given the above, I am not following where  "reference assembly packs" etc come into the equation - would you be able to clarify that aspect of it a bit further, I'd appreciate the insight on that!

Thank you

**Comment by davidfowl** [comment]
> Would MS policy be to fix that breaking change in a patch release of microsoft.extensions.dependencyinjection e.g version 2.2.1

What API broke you?

> At the moment breakages caused by a shared MS dependency binary incompatibily would tend to fall back on the package authors to "recompile their packages against the latest version thanks" - and this is where having a standard strategy / policy I think might help, so thanks for continuing the discussion on this, hopefully it will be helpful to others.

This will always be the case. We try to avoid breaking changes but sometimes they happen in majors. Also you're only discussing binary breaking changes, what about behavior changes? Those count here too right?

> Yeah I'm happy to focus just on the netcoreapp for now. However being able to target multi-target netstandard versions, whilst restricting version ranges of shared ms dependencies to fall within ranges that were covered under a "we'll preserve binary compatibility" policy by MS would be my stretch goal of this issue - how to achieve that - because if we can't preserve compatibility when targeting netstandard tfm's then the value of multitargeting netstandard is somewhat diminished for any package with an ms dependency.

You can't, with netstandard you basically have one level, to rename the package. There's no way within the same package to multi-target or make breaking changes without potentially breaking all consumers.

If you use upper bounds on your packages, the consumer will get a better error but ther's no recourse. What's the next thing the customer is supposed to do? What can the package author do? Somebody still has to make the hard call to release a new version that targets the new package with breaking changes and fork the world either by version of by package name, the TFM is no longer a valid pivot.

**Comment by dazinator** [comment]
> If you use upper bounds on your packages, the consumer will get a better error but ther's no recourse. What's the next thing the customer is supposed to do? What can the package author do?

A consumer getting errors at nuget restore time instead of potentially more exotic errors later on (binary or behavioural breakages) would help protect the consumers, ms, and package authors from debugging and issue triage exercises so I think that could be a worthy goal. I havent analysed the github issue data (or data elsewhere on the interwebs) to work out how many issues are reported for runtime errors caused by breaking changes is ms shared depdencies so I cant put anything in the table for you in that regard.

In terms of recourse though, I think the recourse would be better than the recourse is now. Right now they raise an issue with package author and potentially ms (depending on how developer understands the stack trace or discovers the behavioural breaking change). For a binary change Ms says go to package author as package should be recompiled due to breaking changes. For a 
behavioural change MS usually warns about these in documentation (maybe it's an opt in or  opt out behavior that can be resolved via the docs) and again its between the consumer and package author to sort. 
Package author investigates any bug and decides how best to add support for the breaking change. Package author has no clear guidance on this currently (that I can find) so could chose from a variety of solutions, like attempting to distinguish by TFM (which I think we are saying is not a guaranteed strategy).

So how about this then:

1. Foo.netcore21LTS - ms deps constrained to major 2 and minor 1. Consumer can only update shared ms deps at patch level.
2. Foo.netcore21Current - same as LTS package above except deps are only constrained on major to allow for consumer to update ms shared deps at minor version level.
3. Package author explicitly adds support for new release vehicles one at a time by creating new package names e.g foo.netcore31LTS and foo.netcore31Current
4. Binary or breaking changes introduced by ms that affects any of those packages would now be addressed by ms hotfix or minor fix?
5. If consumer wants to update to a new LTS or current dependency an explicit nuget error will help them with their recourse- e.g contact the package author to get them to add support. Package author does now have exotic error to debug and can add support by creating new package?

**Comment by davidfowl** [comment]
> Package author has no clear guidance on this currently (that I can find) so could chose from a variety of solutions, like attempting to distinguish by TFM (which I think we are saying is not a guaranteed strategy).

This is where we can improve the overall story. I'm not convinced upper bounds should be put in place until there is a break. I wouldn't do it preemptively, it causes more pain without truly understanding if there's a breaking change that will affect the library. Breaking changes are always in the eye of the beholder.

There are 2 kinds of package and they require different techniques when dealing with breaking changes:
- Ones that target netstandard
- Ones that target netcoreapp

I would recommend the following:
- Have your package target the LTS version.
- For packages that target netcoreapp use the TFM to cross target and handle the breaking change (assuming it's a binary breaking change)
- For packages that target netstandard. Add an upper bound to the LTS version of the package so consumers that get auto-upgraded now see an error (if the breaking change affects your package).

The latter strategy means you need a versioning strategy to allow for versioning your own assets and for following the LTS and current train.

**Comment by dazinator** [comment]
>  I wouldn't do it preemptively, it causes more pain without truly understanding if there's a breaking change that will affect the library. 

The type of effort that you have to expend when pre-emptively dealing with this, versus having to react to a breaking change "after the fact" is more of a known quantity in the pre-emptive case. In the pre-emptive case its easier for package authors to safeguard their time, by adding support for new LTS (or current) releases at a time they chose, and its less likely they will have to be reactive to issues reporting binary or behavioural incompatible changes that warrant a different level of debugging and investigation - in order to even pinpoint the issue as a binary or behavioural break let alone fix it. To truly respect nuget package authors it would be good have a story to for both models, with the tradeoffs mentioned so package authors are empowered to make a relevent choice.

However, as long as the scales are currently in favour of it being "Unlikely" for breaking changes to be introduced by MS shared dependencies, then I agree that perhaps not doing it pre-emptively _might_ save effort overall as your package continues to "just work" with new releases. This is basically what I do for all my packages that I publish right now (most of them target netstandard) and is great for .net ecosystem overall as more packages remain available from release to release at only a slight risk of error rate. 

The pre-emptive case is the one I am most interested in right now however, just because I think this will help reveal what level of commitment MS have for preserving compatibility - to help package authors publish particular packages once with a version scope that they know is backed up with some level of service (even a soft guarantee is better than none) by MS to fix binary or behavioural inconsistencies caused by any shared dep updates.

**Comment by davidfowl** [comment]
> The pre-emptive case is the one I am most interested in right now however, just because I think this will help reveal what level of commitment MS have for preserving compatibility - to help package authors publish particular packages once with a version scope that they know is backed up with some level of service (even a soft commitment is better than none) by MS to fix binary or behavioural inconsistencies caused by any shared dep updates.

I'm 100% against preemptive upper bounds but it's really up to you and your package consumers. We're not going to hotfix a breaking change if it was intentional. As much as we don't want to make them, we will deprecate APIs and delete them in new major versions. That alone should be enough to tell you that it will never be 100% binary compatible. On top of that we expect to make behavior changes that could also affect your library usage in major versions, not for fun only when we deem it worth it.

We are much better about breaking changes now and with more adoption I don't expect them to be as rampant as they were before but expect change and evolution which will mean new APIs and new adoption.

I don't know what packages you have experienced breaking changes with (I still want to know what broke you was it BuildServiceProvider?) but it seems like you're saying you spent lots of time dealing with the fallout. Is that true? Did you have lots of customers filing issues on your repo and you had to discover the breaking change happened later on? Though you might have saved yourself some theoretical time by adding an upperbound, customers will file issues asking for support for the newer version (that's what we have seen in the wild).

In the end it's up to you, but when we put out guidance it will *NOT* be to preemptively apply upper bounds on packages because its user hostile.

**Comment by dazinator** [comment]
> I'm 100% against preemptive upper bounds but it's really up to you and your package consumers.

Ok - yep understood!

>  As much as we don't want to make them, we will deprecate APIs and delete them in new major versions. That alone should be enough to tell you that it will never be 100% binary compatible. 

I don't think anyone (certainly not me) is suggesting that things should always be 100% binary compatible even between new major versions that would be insane nonsense, preventing the evolution of software!! :-)

Breaking changes I think are welcomed when its done in a controller manor, and this is where semver spec has been really fundamental to the point were many developers now couldn't live without it and are growing very used to it imho!

> We're not going to hotfix a breaking change if it was intentional.

I am guessing that an intentional breaking change at hotfix level is extremely unlikely to happen though? Can you think of any ever happening for the ms libraries? I haven't come accross any yet in my day to day.

However at a minor version level, do you or the team have a feel for whether breaking changes are still fairly likely to occur - e.g from 2.1 to 2.2 etc? If you are as committed to not introducing breaking changes at that level as you are a the patch level (but I am guessing you are not) then that's a slightly different level of risk for me to relax the constraints at that level. Relaxing the constraints at major level seems almost like madness for a package author to me given this:

> As much as we don't want to make them, we will deprecate APIs and delete them in new major versions. 

I'd go so far as to say if I was producing commercial packages and allowed this to happen, it would almost show a sign of negligence on my part to allow customers to go through the effort of upgrading their applications against my version of a package only to hit binary or runtime errors later because my package really never supported that upgrade to begin with and I was aware of the risk that major breaking changes such as you suggested can happen - passing that risk directly to users / consumers. I think this can also be seen as a "user hostile" action - so it really depends on your take on it - I am playing devils advocate mainly here as I am not in this position myself most of the time i.e I don't have many commercial projects! I'm mainly just a free and open source guy trying to better ring fence my time by eliminating a source of pain so I can address it in a more controller mannor.

I've set I think all I needed to say on this topic, I'll leave this issue now for you / your team to glean what you will - if you do come up with any guidance / samples or docs to show your suggested strategy (maybe some concrete examples would be really useful) I'd be very interested to see those.

**Comment by dazinator** [comment]
Closing this as it doesn't appear to be moving anywhere constructive.

**Comment by davidfowl** [comment]
> Breaking changes I think are welcomed when its done in a controller manor and I appreciate, and know first hand that you try to avoid them.

As a library author, how would you want to be notified of breaking changes?

> I am guessing that an intentional breaking change at hotfix level is extremely unlikely to happen though? Can you think of any ever happening for the ms libraries? I haven't come accross any yet in my day to day.

> However at a minor version level, if you are as committed to not introducing breaking changes at that level as you are a the patch level (but I am guessing you are not) then I can also see the value in relaxing any constraint at that level to allow for application developers to adopt "Current" releases .

Nope. It's mostly because we don't change *any* APIs in patches and we've pretty much stopped shipping minor versions (this is the only place it could happen). We now have yearly release cycles.

> For example if I was producing commercial packages and allowed this to happen, it could almost show a sign of negligence on my part to allow my customers to go through the effort of upgrading their applications against my version of a package only to hit binary or runtime errors later because my package really never supported that upgrade to begin with and I was aware of the risk that major breaking changes such as you suggested can happen - passing that risk directly to users / consumers. I think this can also be seen as a form of "user hostile" action. I am playing devils advocate mainly here as I am not in this position myself most of the time i.e I don't have many commercial projects! I'm mainly just a free and open source guy trying to better ring fence my time by eliminating a source of pain so I can address it in a more controller mannor.

I think it's a reasonable fear to have as a package author but unlike .NET Framework we're going to break and change things this time around. Obviously much less frivolously than in the past, here's an example https://github.com/dotnet/aspnetcore/issues/20614.

> I'd love to see some guidance / samples or docs in future to show the strategy you would most be happy with - that would be a big help here! I am happy to use that as a baseline and discuss the issues i've raised and alternatives as my own blog topic time allowing.

Yes, we could do much more here with respect to docs, tooling and examples (and also features on nuget).

**Comment by dazinator** [comment]
> As a library author, how would you want to be notified of breaking changes?

A major version bump of the nuget package version that contains the breaking change, with some link to release notes documenting the breaking change/s. In a risk-averse scenario I'd then scope my dependencies to a particular major version range that I know is currently compatible, and this would prevent downstream consumers updating their application dependencies to a newer potentially incompatible version, without me explicitly doing the necessary and releasing a version with support for that new major version first. Nuget package manager could do a better job of pointing out major version bumps on its update panel and treating them more prominantly but thats a seperate nuget issue :-)
