### ISSUE TITLE
500.37 - ANCM Failed to Start Within Startup Time Limit -> NativeMethods.HttpGetApplicationProperties COM Exception

### ISSUE THREAD

**Issue by JamesIrish** [dotnet/aspnetcore#20194]
### Describe the bug
Our deployed ASP.Net Core website (hosted behind IIS) sporadically stops, appears to restart and then cannot do so resulting in the browser showing  

> HTTP Error 500.37 - ANCM Failed to Start Within Startup Time Limit
> Common solutions to this issue:
> ANCM failed to start after 120000 milliseconds
 
Our logging solution (SeriLog) output looks like the following:

```
03/26/2020 14:05:03 [INF] Username: Anonymous SessionId: 4393bd33-5daa-b855-8b14-483c8c2e8dd3 RequestId:80000ccc-0003-f800-b63f-84710c7967bb
Returning Login view
03/26/2020 14:05:03 [INF] Username: Anonymous SessionId: 4393bd33-5daa-b855-8b14-483c8c2e8dd3 RequestId:80000ccc-0003-f800-b63f-84710c7967bb
HTTP GET /Account/Login responded 200 in 21.2041 ms
03/26/2020 14:06:05 [INF] Username: Anon
03/26/2020 14:09:12 [INF] Username:  SessionId:  RequestId:
Starting up
03/26/2020 14:12:21 [FTL] Username:  SessionId:  RequestId:
Application start-up failed
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.HttpGetApplicationProperties()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIIS(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.WebHost.ConfigureWebDefaults(IWebHostBuilder builder)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.<>c__DisplayClass0_0.<ConfigureWebHostDefaults>b__0(IWebHostBuilder webHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at ClientPortal.Web.Program.CreateHostBuilder(String[] args) in D:\BuildAgent\work\798572a427b109df\ClientPortal.Web\Program.cs:line 95
   at ClientPortal.Web.Program.Main(String[] args) in D:\BuildAgent\work\798572a427b109df\ClientPortal.Web\Program.cs:line 82
```

### To Reproduce
Unable to do so on demand. :(  Once this issue occurs on one of our web servers it eventually springs back into life but can require multiple (10+) app-pool & site restarts to get the error to clear - there doesn't appear to be a particular trigger for this behaviour.

e.g. it's just come back to life now - log shows.. (with log level upped to debug)

```
03/26/2020 15:27:28 [INF] Username:  SessionId:  RequestId:
Starting up
03/26/2020 15:28:53 [DBG] Username:  SessionId:  RequestId:
Hosting starting
03/26/2020 15:28:53 [DBG] Username:  SessionId:  RequestId:
Mongo client certificate loaded.  
Subject:    *********************
Expires:    ***********
Thumbprint: ****************
Issued by:  ********
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Found key ****************.
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Considering key ************ with expiration date 2020-06-04 13:26:31Z as default key.
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Opening CNG algorithm 'AES' from provider 'null' with chaining mode CBC.
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Opening CNG algorithm 'SHA256' from provider 'null' with HMAC.
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Using key *********** as the default key.
03/26/2020 15:28:54 [DBG] Username:  SessionId:  RequestId:
Key ring with default key *********** was loaded during application startup.
```

### Further technical details
- ASP.NET Core version
3.1.2

- Hosted on
Windows Server 2016 Datacenter x64 1607 14393.3564
2.40GHz 14GB

- Include the output of `dotnet --info`
(latest ASP.NET Core Runtime Windows 'Hosting Bundle')

> C:\>dotnet --info
>   It was not possible to find any installed .NET Core SDKs
>   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
>       https://aka.ms/dotnet-download
> 
> Host (useful for support):
>   Version: 3.1.2
>   Commit:  916b5cba26
> 
> .NET Core SDKs installed:
>   No SDKs were found.
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Visual Studio 2019, but more importantly the build server publish command:

`dotnet.exe publish ClientPortal.Web\ClientPortal.Web.csproj --configuration Release --runtime win-x64 -p:Version=3.5.138 --no-self-contained`

web.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <httpProtocol>
        <customHeaders>
          <clear />
        </customHeaders>
      </httpProtocol>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\ClientPortal.Web.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
```

### Question

Is there any way of getting more information regarding the failure of the COM call?

https://github.com/dotnet/aspnetcore/blob/master/src/Servers/IIS/IIS/src/WebHostBuilderIISExtensions.cs#L33

https://github.com/dotnet/aspnetcore/blob/c84e37f30def9ff0b2d12e877e3de6c283be6145/src/Servers/IIS/IIS/src/NativeMethods.cs#L99

**Comment by anurse** [comment]
Can you share you Program.Main code? I think the COMException is happening just because of the timeout elapsing, it's not the cause of the elapse. If your app takes longer than 120 seconds to start, ANCM will consider it as failing and abandon it (and attempt to restart). That would cause the `UseIIS` call to fail (since IIS has abandoned the app).

**Comment by JamesIrish** [comment]
Ah thanks Andrew, I hadn't looked at it that way around at all and that seems very possible!  Our Program.cs doesn't do much besides setup Serilog and call CreateHostBuilder however our Startup.cs is a different story with data protection, session, etc. depending on MongoDb - I'll add more logging for the startup process as I'm sure that will highlight something.  Thanks for the input, will close the issue and reopen if necessary.

**Comment by anurse** [comment]
> our Startup.cs is a different story with data protection, session, etc. depending on MongoDb

Yep, that could do it. As a general rule of thumb, as long as you get from the start of `Program.Main` to the end of `Startup.Configure` within that 120 seconds window you should be OK (obviously there **is** some additional work going on after `Configure` but it's pretty minimal).

It's also possible to increase the startup time limit if you need to. There's an option on the `<aspNetCore>` element in web.config (see docs here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#configuration-with-webconfig).
