### ISSUE TITLE
OnAfterRender being called after every scrolling via javascript

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/aspnetcore#20193]
I am initiating a scroll to a specific element from `OnAfterRender` override. I am scrolling in multiple steps to animate the scroll but I am noticing that after each step of scrolling is complete, `OnAfterRender` is getting called. Is this expected?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Blazor doesn't automatically re-render on scroll events. This means that you have code which has registered for that event and then this is expected.
We plan to add an ability to throttle these in the future, as part of this issue: https://github.com/dotnet/aspnetcore/issues/10522

**Comment by nvmkpk** [comment]
What event are you talking about? I did not register for any event. I am just invoking `element.scrollTo` from `OnAfterRender` override of my component via JS interop. And `OnAfterRender` is getting called after that scrolling is complete.nI don't think blazor is re-rendering. I will see if I can provide a simple project to reproduce the issue.

**Comment by nvmkpk** [comment]
While reproducing in a new project, I realized this only happens when I have an event handler registered for 'onscroll'. But this event handler does nothing until the scrolling actually completes. I would like to know how to prevent this re-render from happening. I attached the repro project.
[RenderIssue.zip](https://github.com/dotnet/aspnetcore/files/4399696/RenderIssue.zip)

**Comment by pranavkm** [comment]
>  but I am noticing that after each step of scrolling is complete, OnAfterRender is getting called. Is this expected?

Blazor will trigger a render at the end of an event execution which should result in an `OnAfterRender(Async)` to be called.

**Comment by nvmkpk** [comment]
That is an ugly work around. I hoped for a solution like adding `@on{EVENT}:disableRerender="true"` to prevent re-render.

I think I will go the route of a custom base class implementing `IComponent` and `IHandleEvent` interface to permanently disable the call to `StateHasChanged` on handling any events. (along with other related interfaces).
