### ISSUE TITLE
WebApi 404 error with HttpClient

### ISSUE THREAD

**Issue by tezine** [dotnet/aspnetcore#20204]
Hello, 
I'm receiving error 404 when attempting to access a REST API in the same project from a Blazor Server app. The REST API works fine if I try to access it from the browser, but I get error 404 when trying to access from a Blazor Page. 
Here is my Startup.cs
```c#
public class Startup{
        public Startup(IConfiguration configuration){
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }
        public void ConfigureServices(IServiceCollection services){
            services.AddMvc(options => options.EnableEndpointRouting = false);
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSingleton<WeatherForecastService>();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env){
            if (env.IsDevelopment()){
                app.UseDeveloperExceptionPage();
            }
            else{
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseRouting();
            app.UseMvcWithDefaultRoute();
            app.UseEndpoints(endpoints =>{
                endpoints.MapBlazorHub();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }
```
Here is my Controller (TestController.cs):
```c#
    [Route("api/[controller]")]
    public class TestController : ControllerBase {
        [HttpGet("GetTest")]
        public IActionResult GetTest() {
            return Ok("OK");
        }
    }
```
Here is my Page:
```c#
@page "/counter"
@inject NavigationManager NavigationManager
<h1>Counter</h1>
<p>Current count: @currentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;
    private async void IncrementCount(){
        currentCount++;
        //receiving 404 this way
        HttpClient httpClient = new HttpClient();
        var result = await httpClient.GetStringAsync("https://localhost:44390/api/Test/GetTest");

        //also receiving 404
        httpClient.BaseAddress = new Uri(NavigationManager.BaseUri);
        var result= await httpClient.GetStringAsync("/api/Test/GetTest");
    }
}
```
It works whenever I type https://localhost:44390/api/Test/GetTest in the web browser.

### Further technical details
- ASP.NET Core version 3.1.1
- Dotnet sdk 3.1.101
- Blazor 3.2.0-preview2
- Windows 10.0.17763 x64
- Visual Studio 2019

**Comment by javiercn** [comment]
@tezine thanks for contacting us.

Can you provide a minimal repro project so that we can help you determine what's going on here?

**Comment by tezine** [comment]
> @tezine thanks for contacting us.
> 
> Can you provide a minimal repro project so that we can help you determine what's going on here?

Hi @javiercn , I created a project on github. You can get it here:  https://github.com/tezine/TestBlazor

**Comment by javiercn** [comment]
@tezine both things work for me without issue.

![image](https://user-images.githubusercontent.com/6995051/78034703-ecf55100-731c-11ea-83be-6f06b8a1d6b8.png)

I would check your network configuration (host file, proxies, etc) to figure out what is different on your machine.

**Comment by tezine** [comment]
> @tezine both things work for me without issue.
> 
> ![image](https://user-images.githubusercontent.com/6995051/78034703-ecf55100-731c-11ea-83be-6f06b8a1d6b8.png)
> 
> I would check your network configuration (host file, proxies, etc) to figure out what is different on your machine.

Hi @javiercn , are you running the exact sample from github? Are you running blazor server side? I got this error on two computers, both running without proxy configuration.
