### ISSUE TITLE
Using System.Reflection.TypeExtensions.GetProperties in .NET Core 2.0

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#20209]
I am using a Class Library project, whose target frameworks are `net451` and `netstandard1.6`, which dynamically compiles a class in a way similar to the example here (a "standard" way to do the compilation):

https://github.com/dotnet/roslyn/issues/16211#issuecomment-372998985

but inside a method in `MyClass`, I want to retrieve all public properties like this (the actual code is the string of this, which is passed to `CSharpSyntaxTree.ParseText`:
```csharp
using System;
public class MyClass
{
    public static void Print()
    {
#if NET451
            var props = this.GetType().GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
#else
            var props = System.Reflection.TypeExtensions.GetProperties(this.GetType(), System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
#endif
             //additional code
    }   
}
```
Now, the Class Library project is referenced by an ASP.NET Core web app (assume any third party app that I have no control over), which targets `netcore1.1` and as [`System.Reflection.TypeExtensions.GetProperties` is available](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.typeextensions.getproperties?view=netcore-1.1#System_Reflection_TypeExtensions_GetProperties_System_Type_System_Reflection_BindingFlags_), it is working as expected.

However, targeting `netcore2.0` throws an error although it looks like the [method should still be available](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.typeextensions.getproperties?view=netcore-2.0#System_Reflection_TypeExtensions_GetProperties_System_Type_System_Reflection_BindingFlags_). The alternative (used for `net451` above):
```csharp
var props = this.GetType().GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public);
```
is actually working for `netcore2.0`, but not for `netcore1.0` or `netcore1.1`. Also note that this happens only when compiling the class dynamically - using the `MyClass`s `Print` method definition works OK in both `netcore1.0` and `netcore2.0` without the dynamic compilation.

Can you provide more information why this is happening and if it is required for the `netcore2.0` project to "provide" the `System.Reflection.TypeExtensions` package?

**Comment by anurse** [comment]
Looks like this is a pretty stale issue, referencing .NET Core 2.0 which is end-of-life. Is this issue still occurring on a supported release of .NET Core (currently 2.1 or 3.1)?
