### ISSUE TITLE
Breakpoints in `.razor` files, which are not in the `@code` block won't bind

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#20200]
Using the latest VS preview (16.6 Preview 3) release with the latest Blazor bits (3.2-preview3):

![image](https://user-images.githubusercontent.com/34246760/77686707-983b8a00-6f5a-11ea-9d7b-13366a4d46d6.png)

**Comment by mihaimyh** [comment]
Neither those in a "code-behind" class, like FetchData.razor.cs.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19339
