### ISSUE TITLE
Blazor WASM extendibility

### ISSUE THREAD

**Issue by MarekPokornyOva** [dotnet/aspnetcore#20205]
Hello,
I've tried to make few extensions to bring support of the features not supported OOTB. During that I found out Blazor WASM design is not well extendable - basically because it doesn't use dependency.

C# area example:
	https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs#L126 - `_renderer = new WebAssemblyRenderer(Services, loggerFactory);`
The renderer could be injected by dependency container or a factory.

JS area example:
	https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Boot.WebAssembly.ts#L23 - `setEventDispatcher(...`
I'm not JS developer but I guess it's impossible to set custom dispatcher during Blazor boot or near that phase.

Could you please comment if this design is temporary until release version in .NET Core 3.1+ / .NET 5+ or is it meant as final?

**Comment by javiercn** [comment]
@MarekPokornyOva thanks for contacting us.

We don't currently plan to allow users to extend the renderer, but like everything our decisions are influenced by user feedback. If you give us ideas on specific things you are trying to accomplish maybe we can suggest different approaches that might be better suited or take that input into consideration for future changes in this area.

**Comment by MarekPokornyOva** [comment]
Hi @javiercn and thanks for you comment.

In my initial post, I meant general extensibility, not only in the partilar mentioned examples. I can see more places where users can't extend/overwrite core functionality. I think, that is very different from .NET Core / ASP.NET Core's design.

The ideas:
1) Lazy loading
This is highly requested feature by Blazor users - there's quite long issue discussion on github. Please look at https://github.com/MarekPokornyOva/BlazorLazyLoad for a custom implementation of the feature.
Implementation difficulties to be hightlighted:
- to extend NotifyLocationChanged handler on both C# and JS sides - see JSInteropMethods.cs and index.html
- to extend Router - see RouterLL.cs

2) Access to native JS objects (DOM, jQ, any other)
Developers need to make various JS functions to access JS objects (of course that's mostly because of WASM design doesn't allow to access DOM directly). I wanted to make "bridge" to allow to cross over the hole easier. Please look at https://github.com/MarekPokornyOva/BlazorNativeJs for an implementation.
Implementation difficulties to be hightlighted:
- to extend event dispatcher on JS side - I had to tweak "/_framework/blazor.webassembly.js" on server side to inject custom code because I didn't find a pure JS way.
- to extend WebAssemblyEventDispatcher because it's static.

Please note, the projects were done on top of preview1 version while preview3 was very fresh at the time of the issue creation. I haven't check preview3's structure yet.
Anyway, I'd highly appreciate if you suggest better implementations - or implement the features OOTB :-).

**Comment by javiercn** [comment]
@MarekPokornyOva thanks for the details.

Seems like you are focused on trying to implement two things:
* Lazy loading of routes/assemblies
* "Automatic" JS interop.

For the first one I wouldn't recommend using the existing system. I would create my own router from scratch + relevant JS code to support it. The current router is not designed with those scenarios in mind and we don't know if we would change it in the future.

For the second scenario regarding a more "granular" JS Interop, this is not a direction we plan to take for the time being. Our guidance is that JS interop is done in a more coarse way so as to minimize latency problems.

In your sample, something like `NativeJs.GetDocument().getElementsByTagName("h1")[0].innerText` will require several roundtrips to the server and it is modifying the outside of the Blazor rendering system, which is something that is not guaranteed to work.

**Comment by MarekPokornyOva** [comment]
That perfectly answers my initial question!
Also, your comments/suggestions are valuable.
Thanks, that will help me to design/write applications in the future.
