### ISSUE TITLE
Health check tags are not passed to the HealthReportEntry

### ISSUE THREAD

**Issue by mirroj** [dotnet/aspnetcore#20216]
### Describe the bug
When an exception is thrown in an health check (for example when the database context health check cannot reach the database), the resulting `HealthReportEntry.Tags` property is empty. Everything works fine until an exception is thrown.  If it does, it's not possible to read the `Tags` property in a custom `ResponseWriter`.

### To Reproduce
A minimal application
``` C#
public Startup(IConfiguration configuration)
{
}

public void ConfigureServices(IServiceCollection services)
{
    services.AddHealthChecks()
        .AddCheck("Good", () => new HealthCheckResult(), tags: new[] { "good-tag" })
        .AddCheck("Bad", () => throw new Exception(), tags: new[] { "exception-tag" });
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapHealthChecks("/health", new HealthCheckOptions()
        {
            ResponseWriter = async (context, report) =>
            {
                foreach (var e in report.Entries)
                {
                    await context.Response.WriteAsync($"Name: {e.Key}\nTags: [{string.Join(',', e.Value.Tags)}]\n\n");
                }
            }
        });
    });
}
```
The path `/health` produces following output:
```
Name: Good
Tags: [good-tag]

Name: Bad
Tags: []
```
I would expect non empty `Tags` propery for the second `Bad` case. Maybe it's by design but it doesn't make much sense to me.

### Further technical details
- ASP.NET Core version: 3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mirroj.
@rynowak can you have a look at this please? Thanks!

**Comment by rynowak** [comment]
Thanks @mirroj !
