### ISSUE TITLE
Microsoft Office Fabric UI for Blazor

### ISSUE THREAD

**Issue by aksoftware98** [dotnet/aspnetcore#20226]
Hello 

I'm starting using Blazor WebAssembly in my projects but I actually I like the Fabric UI too much 
Will it be available sometime for Blazor WASM?

**Comment by javiercn** [comment]
@aksoftware98 thanks for contacting us.

We'll look into this issue and get back to you.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
