### ISSUE TITLE
debug webassembly breake Google auth

### ISSUE THREAD

**Issue by fileman** [dotnet/aspnetcore#20227]
There are known issue with authentication?
When I try to debug webassembly Azure B2C Google auth return: "https://accounts.google.com/signin/oauth/deniedsigninrejected?client_id=........apps.googleusercontent.com&amp;as=........&amp;destination=https%3A%2F%2F.......b2clogin.com&amp;approval_state=!................&amp;oauthgdpr=....&amp;xsrfsig=.........................&amp;flowName=GeneralOAuthFlow"
Preview2 and Preview3

**Comment by javiercn** [comment]
@fileman thanks for contacting us.

Are you saying that it works without debug and it doesn't with debugging on?

Can you describe your scenario in detail so that we can try and help you out?

**Comment by fileman** [comment]
It's ok with Ctrl+F5, but when I use F5 to Debug from VS:
"Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.6.0 Preview 2.0

**Comment by javiercn** [comment]
@fileman thanks for contacting us.

@SteveSandersonMS this doesn't sound like the regular debugging issue. Does the debug proxy change the urls in any way?

**Comment by SteveSandersonMS** [comment]
@javiercn No, it doesn't.

> Preview2 and Preview3

We didn't have VS debugging in preview 2, so if this was already an issue in preview 2, it can't be related to VS debugging.

**Comment by fileman** [comment]
in preview 2 I followed the "[debug in browser](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#debug-in-the-browser)" docs

**Comment by mkArtakMSFT** [comment]
@fileman there has been many updates. Please try out the latest preview release of Blazor and let us know if that helps: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/

**Comment by fileman** [comment]
@mkArtakMSFT I'm at 3.2.0-preview3.20168.3

**Comment by javiercn** [comment]
@fileman in which way does it break, does the browser crash?

Can you provide a minimal repro project so that we can investigate?

**Comment by fileman** [comment]
@javiercn repro is simple -> `dotnet new blazorwasm -au IndividualB2C --aad-b2c-instance "{AAD B2C INSTANCE}" --client-id "{CLIENT ID}" --domain "{DOMAIN}" -ssp "{SIGN UP OR SIGN IN POLICY}" --force` with your AzureAD B2C with google provider app settings.

If I run F5 the auth flow return error:
![image](https://user-images.githubusercontent.com/17230763/78223380-105bff80-74c7-11ea-9b8c-3bdfc856adbf.png)
But running again with Ctrl-F5 the user result successfully logged in

Instead if I close all browser and then I run Ctrl-F5 the auth flow is completed without issue.

**Comment by javiercn** [comment]
@fileman thanks for providing the details.

It is a bit strange that debugging is causing any issue here, since I imagine the flow goes as Your Site -> AAD B2C Login -> Google login and it's failing on that last leg at which point there was no auth code involved at all.

**Comment by colmardev** [comment]
Same as @fileman here.

F5 from VS 16.6.0 preview2 Wasm App with 3.2.0-preview3.20168.3 through Chrome browser.
But if in same debug session I browse to my app https://localhost:44331 from Firefox it works and I can log in with B2C Google user.

**Comment by SteveSandersonMS** [comment]
@fileman @colmardev In the short term, you'll need to run without debugging when launching from VS in this case. Sorry for the inconvenience. We'll see if we can offer any better solution soon.

**Comment by fileman** [comment]
No problem, this is a preview and for no more Javascript required in UI for asp.net, I think we can wait whatever is necessary

**Comment by SteveSandersonMS** [comment]
Problem no longer occurs with 3.2.0-rc builds.

**Comment by fileman** [comment]
3.2.0-rc don't resolve the issue, but I've tried to close the popup and go to /authentication/login url and now AzureB2C login page is in main window, then I can complete authentication flow with google account.

It's normal that AzureB2C login page is loaded in popup?

**Comment by fileman** [comment]
@colmardev do you have the same problem?

**Comment by colmardev** [comment]
@fileman I guess B2C login in popup is by design, and I hope it keeps popping up in the future, this avoids b2c addresses in main window history

About 3.2.0-rc1.20223.4 I tested right now (VS Preview 16.6.0 preview 4) and can confirm that:

- In debug It **doesn't resolve the issue** with Chrome , running CTL+F5 works in every browser
- navigating manually from main window to /authentication/login login is shown in main window with Chrome, while still pops up correctly with Edge (with both F5 and CTL+F5)

**Comment by fileman** [comment]
@colmardev I'm on VS preview 5.0 and no difference.
Auth fail from pop-up on Edge, Chrome but is working in main window.
Auth work from pop-up with Opera, Firefox.

Something in those browser is the problem, Opera is chromium based.

I hope @SteveSandersonMS and his team can solve this.

**Comment by fileman** [comment]
> * navigating manually from main window to /authentication/login login is shown in main window with Chrome then completes auth flow with Google, while still pops up correctly with Edge (with both F5 and CTL+F5)

In my case the pop-up is always show with all browser, but I can't reach the "password" step of Google login on Edge (stable and dev) and Chrome
