### ISSUE TITLE
CS8103: combined length of user strings used by the program exceeds allowed limit

### ISSUE THREAD

**Issue by link05** [dotnet/aspnetcore#20224]
### Describe the bug
I have 3 for each loop in cshtml that i wanted to nest all 3 loops inside  single jquery tabs and i got this issue. *sorry i updated explanation but now the code looks unstructured here.

### To Reproduce

initally:
```csharp
<div>
@for (int i = 0; Model.ManualData!= null && i < Model.ManualData.Count; i++){<div>...</div>}
@for (int i = 0; Model.ManualData!= null && i < Model.ManualData.Count; i++){<div>...</div>}
@for (int i = 0; Model.ManualData!= null && i < Model.ManualData.Count; i++){<div>...</div>}
</div>
```
after adding code for tabs:
``` csharp
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Nunc tincidunt</a></li>
    <li><a href="#tabs-2">Proin dolor</a></li>
  </ul>
  <div id="tabs-1">
   @for (int i = 0; Model.ManualData!= null && i < Model.ManualData.Count; i++){<div>...</div>}
   @for (int i = 0; Model.ManualData!= null && i < Model.ManualData.Count; i++){<div>...</div>}
   @for (int i = 0; Model.ManualData!= null && i < Model.ManualData.Count; i++){<div>...</div>}
  </div>
  <div id="tabs-2">
    <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc.</p>
  </div>
  <div id="tabs-3">
    <p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, </p>
  </div>
</div>
``` 
I ran the app. when the cshtml code was just 3 for loops(look above at initally) and then added jquery tabs and refreshed the page to see the change. It worked and the error CS8103 did not show up(which makes sense b.c. its a complier error). But when i build and tried to run again, it gave me this error.
Crazy thing is if i undo this(meaning went back to what the code was initally (look above) and clean and rebuild project) then it works. Its only when i try to restructure the 3 loops by nesting all 3 of them in single tab then it gives me this compile time error.

Got Exceptions? Include both the message and the stack trace
1>CSC : error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

### Further technical details
- Include the output of `dotnet --info`:
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

- VS 16.5.1

**Comment by javiercn** [comment]
@link05 thanks for contacting us.

We'll look into this issue and get back to you.

**Comment by link05** [comment]
I worked around the issue by making my model as lean as possible (i got rid of extra objects i did not need). So i think it was b/c i was passing too much info into the view. But this was indeed the case, then it still does not explain why the compiler would be ok with outputting 3 massive list but not okay with putting them inside 1 tab.

**Comment by javiercn** [comment]
@link05 It's hard to tell what's going on here, but in essence there are too many things being compiled to literal strings in your views assembly and that's hitting a compiler limit.

I'm not sure we can do anything about it, since this is the compiler. I would recommend you move long strings into resources as that's what the roslyn team suggests.

**Comment by captainsafia** [comment]
Closing this as external in Razor.
