### ISSUE TITLE
Debugging Blazor WASM visual studio

### ISSUE THREAD

**Issue by dlr1** [dotnet/aspnetcore#20233]
After upgrading VisualStudio to latest preview version and installing latest sdk, creating new project , debugging works fine.

for existing project followed instructions in the blog and added 
 "useWebAssemblyDebugging": true,
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"

Can't get debugging to work. Attached is the log file.

[vscode-chrome-debug.txt](https://github.com/dotnet/aspnetcore/files/4393626/vscode-chrome-debug.txt)

**Comment by javiercn** [comment]
@dlr1 thanks for contacting us.

@SteveSandersonMS any thoughts?

**Comment by mihaimyh** [comment]
I can confirm this, existing projects cannot hit break points after following instructions provided in @danroth27 blog post.

**Comment by miroslavp** [comment]
Not sure if my [issue #20238 ](https://github.com/dotnet/aspnetcore/issues/20238) is related to this one, but the vscode-chrome-debug.txt looks very similar

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like you may have missed some steps from the migration guidance. Please have a look at: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/


Please note, that if your project is updating from an older preview than 3.2-preview2, then you will have to also go through every release migrating guide in between.

**Comment by danroth27** [comment]
Some things to confirm when debugging Blazor WebAssembly in VS Code:

- Is the project fully upgraded to Blazor WebAssembly 3.2 Preview 3?
- Is the project being run in the Development environment with the debug proxy enabled?
- Do you have both the C# and JS Debugger (Nightly) extensions installed with preview JS debugging enabled?
- Did the launch.json file get correctly generated into the project by VS Code?
- Did you first launch the server and then the browser using the generated launch profiles?

**Comment by danroth27** [comment]
@dlr1 We haven't heard back on this one, so I think we're going to go ahead and close it at this point. We do have some improvements planned for Blazor WebAssembly debugging in VSCode planned: https://github.com/dotnet/aspnetcore/issues/19246
