### ISSUE TITLE
Authentication.AzureAD.UI Options for Microsoft identity platform OIDC "/v2.0"

### ISSUE THREAD

**Issue by mrmartan** [dotnet/aspnetcore#20239]
### Is your feature request related to a problem? Please describe.

I am trying to use AddAzureAD and AddAzureADBearer with `login.microsoftonline.com/{tenant}/v2.0/` and while I know I have to use it with `/v2.0/` I have expected the library to handle that. I have found out it does not so went looking for an option for it and I failed. [Samples](https://github.com/dotnet/aspnetcore/tree/master/src/Azure/AzureAD/samples) don't cover this.  

After some digging I found <https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp#startup-class> and <https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API#modify-the-startupcs-file-so-that-the-web-api-becomes-v20-multi-tenant-app> both showing someting like:

```csharp
services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
  {
    options.Authority = options.Authority + "/v2.0/";         // Microsoft identity platform
  });
```
We ended up using something to that effect. Although it seems more like a workaround to me.  
None of my attempts with the library would work until a added the version in such a *"maunal"* way.

### Describe the solution you'd like
IMHO it is not easy to find and make sense of all the documentation and various sample that float around AzureAD. I am pretty sure it is a bit of a nightmare to write and manage all that but I'd like if at least the basic use-case of authenticating with an OIDC/OAuth JWT auth token and `AddAzureADBearer` was easy and discoverable since looking at `AzureADOptions` nothing suggests this `v2.0` pitfall.
I think [AzureADOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADOptions.cs) should provide a way to specify the `v2.0` endpoint. One that ends up creating `Authority` URL like `https://{instance}/{tenant}/v2.0/`, e.g. `https://login.microsoftonline.com/someTenant/v2.0/`. I think it would help with discoverability.

**Comment by blowdart** [comment]
AAD has not been updated to V2 as yet, this will be part of 5.0.

v1 is sufficient for most people right now, and it does still work.

**Comment by blowdart** [comment]
Also this will be addressed as part of the upcoming AAD work for v5, which you can track in the [AAD repo](https://github.com/AzureAD/microsoft-identity-web). 

Closing this as external.
