### ISSUE TITLE
Unit testing a Razor Page Method with a return Partial in it blows up test 

### ISSUE THREAD

**Issue by PurdueGuy531** [dotnet/aspnetcore#20241]
**Something's broken in the Razor Page Model's 'Partial' helper method.** 
Using ASP.NET Core 3.1.1 RazorPages. 

PROBLEM:  
I have a razor page method I'm unit testing with xunit. The method has this signature: 
public async Task< IActionResult > OnPostAsync()

And it ultimately ends with: 
**return Partial("ViewName",myModelClass);**

This unit test fails at the partial call. I also attempted to recreate all the HttpContext base dependencies, in hopes that would resolve the issue. It did not. Used this documentation - following the examples at the bottom of this page:
https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-3.1#unit-tests-of-the-page-model-methods 

WORKAROUND: I created my own PageModel extension method in the meantime, to more easily return a PartialViewResult. This extension method doesn't fail when called from the unit test or normally from the page. To use I call: return this.PartialView(etc, etc);

My Extension method to work around this issue:

**public static PartialViewResult PartialView<T>(this PageModel helper, string viewName, T model)**
        {
            if (helper.ViewData == null)
            {
                //UNIT TEST HITS THIS: When a Razor Page Model class is unit tested, often the 'PageModel.ViewData' is null and this is needed to properly return a PartialView.
                return new PartialViewResult()
                {
                    ViewData = new ViewDataDictionary<T>(
                        new ViewDataDictionary(
                                new EmptyModelMetadataProvider(),
                                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary()
                        ), model),
                    ViewName = viewName
                };
            }
            else
            {
                //REGULAR PAGE FLOW: Will have a non-null ViewData property on PageModel.
                return new PartialViewResult()
                {
                    ViewData = new Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<T>(helper.ViewData, model),
                    ViewName = viewName
                };
            }
        }

Thanks!
Chris

**Comment by javiercn** [comment]
@PurdueGuy531 thanks for contacting us.

If you are trying to execute the view, we don't recommend you go that way and instead we recommend you write an integration test for it. In general, integration tests are a better choice for controllers and pages, but if you want to unit test them, it should be possible (although more involved) to do so.

If you produce a minimal repro with your test code we can take a look at it and give you some pointers.
