### ISSUE TITLE
Blazor Wasm: VS debugging does not work for Razor Class Library

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#20243]
My project uses a UI Razor Class Library that contains all of our `.razor` files.  I haven't been able to debug our project in Visual Studio, so I recreated the scenario starting with the default template.

I first set a breakpoint in `FetchData.razor`.

**Before moving into the RCL:**

The breakpoint hits as expected.

**After moving into the RCL:**

The breakpoint is not hit.

---

I've created a minimal reproduction repository here:

https://github.com/zbecknell/NonDebuggableRepro

**Comment by chuckgiddens** [comment]
I have the same issue.  The Blazor CLIENT will not debug but the Blazor SERVER project will hit the break points.

**Comment by chuckgiddens** [comment]
I cannot get break points to hit on the CLIENT project but it works on the SERVER project.  How do I fix this?  I have updated all PREVIEW Nuget Packages

**Comment by pranavkm** [comment]
This should work if you update to VS 16.6 or newer and the RC (or newer) build of Blazor. Feel free to reopen or file a new issue if you're still seeing this once you've upgraded.

**Comment by zbecknell** [comment]
Unfortunately, we've not been able to successfully debug our project.  It probably deviates from the norm too much, as our login page is a server-side rendered page which then takes you to the client-side app.  We also can build for full server-side and debug our components that way, so it's not been as urgent to get client-side debugging working.  Hopefully, at some point, we'll be able to give this a shot again.
