### ISSUE TITLE
[Blazor] DOMException: Entry already exists

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#20256]
### Describe the bug
When running a simple Blazor WASM app I am seeing errors in the console saying "DOMException: Entry already exists".

For me, this only happens in Chrome.

### To Reproduce
Run this app. https://drive.google.com/open?id=1MnWAzjHcMT60wbBlUhh_haIkTLM88vbo

### Error details
```
Uncaught (in promise) DOMException: Entry already exists.

u | @ | blazor.webassembly.js:1
-- | -- | --
  | Promise.then (async) |   |  
  | s | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | s | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | r | @ | blazor.webassembly.js:1
  | e.addToCacheAsync | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | s | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | s | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | r | @ | blazor.webassembly.js:1
  | e.loadResourceWithCaching | @ | blazor.webassembly.js:1
  | e.loadResource | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | e.loadResources | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | callRuntimeCallbacks | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | preRun | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | run | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | runCaller | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | removeRunDependency | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | receiveInstance | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | s | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | s | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | r | @ | blazor.webassembly.js:1
  | p.instantiateWasm | @ | blazor.webassembly.js:1
  | createWasm | @ | dotnet.3.2.0-preview3.20168.1.js:1
  | (anonymous) | @ | dotnet.3.2.0-preview3.20168.1.js:1
```

### Further technical details
- ASP.NET Core version 3.1.2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Version 16.6.0 Preview 2.0

- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by ThijsBoudrez** [comment]
I got those errors also in Edge (Chromium).

**Comment by jvallejoa** [comment]
Hello, this is a tremendous bug and I think is high priority. It **ALWAYS** happens when after creating a WebAssembly Client project with individual authentication the user scaffolds "Accounts" defaults razor pages for editing pages, like Register, Login, etc. Please, we developers do need this error be resolved asap. Thanks!!

**Comment by jg11jg** [comment]
I have this too on Edge (haven't tried Chrome).  But I haven't noticed any actual functionality issues.  Anyone know what are these error messages actually telling us - can we safely ignore?

**Comment by eric-king** [comment]
This happens to me also with a Blazor WebAssembly app I'm building. As with @jg11jg , I don't notice any problems with the application itself or with its rendering.

**Comment by Sm1le291** [comment]
Yeah, the same error in application with Authentication

**Comment by pranavkm** [comment]
@mrpmorris I don't see any errors running the app in Chrome 81 and Edge 81. I tried scaffolding Identity, and that appeared to work just fine. If you're still seeing an issue, could one of you please share a minimal app that reproduces this error?

**Comment by mrpmorris** [comment]
I don't recall seeing this for a while now. I'll close it for now and reopen it off I start to see it again.

**Comment by netprok** [comment]
I am still getting this error.

blazor.webassembly.js:1 Uncaught (in promise) DOMException: Entry already exists.
u @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
e.addToCacheAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
e.loadResourceWithCaching @ blazor.webassembly.js:1
e.loadResource @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.loadResources @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
c @ blazor.webassembly.js:1
(anonymous) @ VM26:1
(anonymous) @ blazor.webassembly.js:1
start @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
v @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1

**Comment by mrpmorris** [comment]
I am seeing it again now too. This is in the official WebAssembly release.

**Comment by MaxMommersteeg** [comment]
I'm experiencing the same issue using the 3.2.0 WebAssembly NuGet packages.

**Comment by hsinyu-chen** [comment]
same issue here ,got 113 `Uncaught (in promise) DOMException: Entry already exists.` when I upgrade package to 3.2 and launch blazor template project

**Comment by lgulliver** [comment]
I'm getting this too since updating Visual Studio to 16.6. I was previously working in VSCode with no issues, but needed to switch to run multiple function apps alongside it more easily, but now I'm hitting the same issues as above.

**Comment by achmstein** [comment]
I'm experiencing the same issue!

**Comment by SteveSandersonMS** [comment]
People experiencing this issue, is anybody able to post a minimal repro? We'll need this in order to investigate.

**Comment by mrpmorris** [comment]
I can give you remote access to my laptop if you wish?

**Comment by lgulliver** [comment]
> For me it happens on the default blazor app template. WASM, ASP core hosted. On 16.6.0 and 16.6.1.
> 
> Copying the same project to another machine running 16.5.5 doesn't have the errors
> 
> -edit- added project but it's just the unmodified template
> [BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/4718774/BlazorApp1.zip)

I have the same here, but without the hosted option.

https://github.com/lgulliver/blazor-webassembly-serverless-chat-demo or https://github.com/lgulliver/squaddle have the issue.

Both we're originally created in VSCode but opening them in Visual Studio 16.6.x and running with debug gives the exception.

**Comment by SteveSandersonMS** [comment]
Just to check whether this is a caching issue in your browser, could you please try the following and let us know if it works?

1. Try running the app in a different browser (eg Firefox or Chrome if you normally use Edge, or vice-versa)
2. Try clearing all data for the affected site in your normal browser then run the app again (https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/)

**Comment by mrpmorris** [comment]
@SteveSandersonMS 
1: File->New Blazor Wasm ASP.NET Hosted
2: Run app in Chrome, errors occur
3: Run app in Edge / Firefox, no errors
4: Clear all Chrome browsing history and re-run app = errors occur
5: Clear cache for that site only and re-run = errors occur

**Comment by lgulliver** [comment]
Okay, so for me, I normally use Edge (current version I have is 83.0.478.44) and I encounter the issue there. I still encounter it even after clearing all data.

In Chrome (83.0.4103.61) however, I don't encounter the errors in question.

**Comment by jssmotta** [comment]
Hello, in my case, I were getting this error after I added:

https://www.nuget.org/packages/TG.Blazor.IndexedDB

and

https://github.com/Reshiru/Blazor.IndexedDB.Framework/

I removed them from the project and the problem was solved.

I bet that the problem is the dependencies from https://www.nuget.org/packages/TG.Blazor.IndexedDB, but I could no test it.

I hope this information could help someone.

Best,

Jeff

**Comment by Sm1le291** [comment]
Regulary facing with similar issue
![image](https://user-images.githubusercontent.com/15110338/83658523-9b8a6c00-a5c2-11ea-9535-b2f0a925aace.png)

Everything works fine, despite this messages. Sometimes page stops to load and I must open console and press continue because I see message Debugger in pause, it happens randomly

Visual Studio 2019 16.6.1
Blazor 3.1.4

**Comment by pranavkm** [comment]
@SteveSandersonMS could you have a look? I tried a few of the apps here on a few machines and I a don't see the issue. 

For folks reporting here, does opening the browser in a different profile work? For instance, Edge and Chrome have an option to browse using the guest profile.

**Comment by mrpmorris** [comment]
@pranavkm I've tested a few scenarios. It only seems to be a problem (for me) when VS is responsible for launching the browser.

When VS launches Chrome I see the problem.
If I open a new tab in the same browser and go to the URL I see the problem.
If I open an incognito window and go to the URL, no errors.
If I open a new instance of Chrome (not incognito) no errors (whether signed in or as Guest).

I hope that helps.

**Comment by Sm1le291** [comment]
You can download archive with project here 
https://1drv.ms/u/s!AkIXAhGlJ7OukMVzE2JZ6y-gjexNKg?e=T17ReD
Needs a db with name AuctionSpaDBTest

**Comment by pthomson** [comment]
I experience this issue as well but @mrpmorris is correct, only in the browser window that VS2019 16.6 opens. If I open the URL in another browser instance then no error.

**Comment by mkArtakMSFT** [comment]
@pranavkm should this be resolved now?
