### ISSUE TITLE
Net Core 3.1, single file - unable to start application as windows service

### ISSUE THREAD

**Issue by Omen90** [dotnet/aspnetcore#20267]
dotnet sdk: 3.1.201
Microsoft Windows 10 Pro
OS Version: 10.0.18362 Build 1836

Couldn't start app as windows service if it is publish as single file (no matter it is trimmed or not).

Repro:

```
string PathToContentRoot = Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName);

            var config = new ConfigurationBuilder()
               .SetBasePath(PathToContentRoot)
               .AddJsonFile("wwwroot/appsettings.json", optional: false, reloadOnChange: true)
               .Build();

            return Host.CreateDefaultBuilder()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseContentRoot(PathToContentRoot);
                    webBuilder.UseKestrel();
                    webBuilder.UseShutdownTimeout(TimeSpan.FromSeconds(30));
                    webBuilder.UseConfiguration(config);
                    webBuilder.ConfigureLogging(logging =>
                    {
                        logging.ClearProviders();
                        logging.SetMinimumLevel(LogLevel.Information);
                    }).UseNLog();
                }).UseWindowsService();

CreateHostBuilder().Build().Run();
```

csproj:
```

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeFrameworkVersion>3.1.3</RuntimeFrameworkVersion>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
  </PropertyGroup>

```

Compile:
`dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true`

**Comment by Tratcher** [comment]
What errors do you get? Anything in the event logs or application logs?

**Comment by Omen90** [comment]
Unfortunately nothing. No exception. I tried to attach it to the process in VS but without success.

Also no luck with this:

    public class BridgeWebHostService : WebHostService
    {
        public BridgeWebHostService(IWebHost host) : base(host)
        {
       
        }

        protected override void OnStarting(string[] args)
        {
            System.Diagnostics.Debugger.Launch();
            base.OnStarting(args);
        }

        protected override void OnStarted()
        {
            base.OnStarted();
            logger.Debug("Service started");
        }

        protected override void OnStopping()
        {
            base.OnStopping();
	}
    }

    public static class WebHostServiceExtensions
    {
        public static void RunAsBridgeService(this IWebHost host)
        {
            var webHostService = new BridgeWebHostService(host);
            ServiceBase.Run(webHostService);
        }
    }
`
BuildWebHost(args).Build().RunAsBridgeService();`

UseWindowsService() and above work fine as long as it is not a single file. I think the problem is somewhere in the paths. Any idea how to catch something ?

**Comment by Tratcher** [comment]
Windows event viewer should show any crashes. Also, it's a good idea for a windows service to use a direct file logger like  Serilog. 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#create-logs-in-the-program-class

**Comment by Omen90** [comment]
I am using NLog. 

Attach to process in VS result:

```
Zgłoszony wyjątek: „System.IO.FileNotFoundException” w System.Private.CoreLib.dll
Wystąpił nieobsługiwany wyjątek typu „System.IO.FileNotFoundException” w System.Private.CoreLib.dll
Could not find file 'C:\WINDOWS\system32\nlog.config'.
```
**_C:\WINDOWS\system32_**
After fixing this, the service started. But still i have some troubles with wwwroot, other files paths. I need some time to test it more.

**Comment by Omen90** [comment]
#3704
