### ISSUE TITLE
install the .net core 3.0 has a error on win server 2012 

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/aspnetcore#20262]
install the .net core 3.0 has a error is not found a file api-ms-win-crt-filesystem-l1-1-0.dll  on win server 2012

**Comment by anurse** [comment]
.NET Core 3.0 is [end-of-life](https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/) and no longer supported, we strongly recommend upgrading to 3.1.

In general, this error indicates that you are missing the Visual C++ Runtime. Can you try installing that and see if it resolves your issue?

**Comment by bouyeijiang** [comment]
yeah，i has resolves issue

**Comment by anurse** [comment]
Ok, closing this as resolved then. Feel free to file new issues if you have further problems!
