### ISSUE TITLE
Support refactoring for the controllerName parameter in ControllerBase.RedirectToAction method

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#20272]
### Is your feature request related to a problem? Please describe.

I am trying to do some refactoring work that includes renaming some controllers. But unfortunately this involves searching for all hard-coded references of the controller name for example used in `RedirectToAction(actionName, controllerName, ...)` calls.

Current workaround:
```cs
return RedirectToAction(
    nameof(NewController.ActionName),
    nameof(NewController).Replace("Controller", null) // Current workaround
);
```

### Describe the solution you'd like

It would be nice to include a simple check whether the `controllerName` parameter includes the suffix `Controller` and ignore it.

This would be a better solution in my opinion:
```cs
return RedirectToAction(
    nameof(NewController.ActionName),
    nameof(NewController)
);
```

**Comment by javiercn** [comment]
@msschl thanks for contacting us.

You could achieve a similar result if you used a string for the controller and selected to also replace strings when performing the rename.

I don't think it is possible for us to tie into the rename functionality of the editor to implement what you suggest, so the alternative that I'm suggesting might be your better choice.

**Comment by msschl** [comment]
Thanks @javiercn 

This would still require a second search and replace for some editors.

My suggestion would be something like this:
```cs
    /// <summary>
    /// Initializes a new instance of the <see cref="RedirectToActionResult"/> with the values
    /// provided.
    /// </summary>
    /// <param name="actionName">The name of the action to use for generating the URL.</param>
    /// <param name="controllerName">The name of the controller to use for generating the URL.</param>
    /// <param name="routeValues">The route data to use for generating the URL.</param>
    /// <param name="permanent">If set to true, makes the redirect permanent (301). Otherwise a temporary redirect is used (302).</param>
    /// <param name="preserveMethod">If set to true, make the temporary redirect (307) and permanent redirect (308) preserve the initial request method.</param>
    /// <param name="fragment">The fragment to add to the URL.</param>
    public RedirectToActionResult(
        string actionName,
        string controllerName,
        object routeValues,
        bool permanent,
        bool preserveMethod,
        string fragment)
    {
        ActionName = actionName;
        RouteValues = routeValues == null ? null : new RouteValueDictionary(routeValues);
        Permanent = permanent;
        PreserveMethod = preserveMethod;
        Fragment = fragment;

        var index = controllerName.IndexOf("Controller");
        if (index != -1)
            ControllerName = controllerName.Substring(0, index);
        else
            ControllerName = controllerName;
    }
```

I'll close the issue because this is nothing mandatory.
