### ISSUE TITLE
SignalR problem when published as IIS Application.

### ISSUE THREAD

**Issue by axanth** [dotnet/aspnetcore#20276]
I have an Asp Core 3.0 web app that user signalR for notification from server to client. It works fine but when the app is published in IIS as an application signalR stop working with error : POST https://localhost:4433/ProgressHub/negotiate?negotiateVersion=1 404. I think that the problem has to do with the relative path of the Virtual Directory. It does not get included in the Hub path. Searched on how to configure this but did not find anything..... any help appreciated!!!!

**Comment by BrennanConroy** [comment]
Can you share your app configuration? Or even better just provide a github repo of your app.
