### ISSUE TITLE
Automatic reload not working when updating existing project to preview 3

### ISSUE THREAD

**Issue by DanielFawcett** [dotnet/aspnetcore#20270]
### blazor webassembly.
Automatic reload does not work on refresh
I’ve updated from preview 2 to preview 3 and I’ve tried testing the automatic refresh and it does not work. Also load times seem to be a lot longer, is this because it’s linking the debugger with the front end? 

### To Reproduce
Upgrade existing project following steps given in blazor preview 3 

### Further technical details
- visual studio 2019 previews as suggested

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There are few requirements for VS Auto-Rebuild to work:
- you should not have debugger attach. Use Ctrl+F5
- you have to run under IIS Express

**Comment by DanielFawcett** [comment]
Ahhh okay, wonderful thank you!!
