### ISSUE TITLE
Blazor WebAssembly exception while calling REST API calls - WebAssembly.JSException: TypeError: Failed to fetch at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch

### ISSUE THREAD

**Issue by sukeshchand** [dotnet/aspnetcore#20285]
I am trying to call REST API call from web Blazor WebAssembly using the following code

```
var userInfo = new ValidateUserRequest { UserName = UserName, Password = password };
var response = await Http.PostJsonAsync<string>($"{APIBaseUrl}/Security/ValidateUser", userInfo);
```

The CORS is enabled in the API.

But when running the application, I got the following error.

```
WebAssembly.JSException: TypeError: Failed to fetch at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch (System.Threading.Tasks.TaskCompletionSource`1[TResult] tcs, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x22fe098 + 0x00988> in <c4a9717a3f954719acec8a5e4e87c87d>:0 at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x22d6978 + 0x00180> in <c4a9717a3f954719acec8a5e4e87c87d>:0 at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) <0x235f0f8 + 0x00278> in <f29c040f027c48c299bba2e6843ac2e0>:0 at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.SendJsonAsync[T] (System.Net.Http.HttpClient httpClient, System.Net.Http.HttpMethod method, System.String requestUri, System.Object content) <0x22a1c88 + 0x00118> in <393f0d2066e842d38b0e8ac688095cf7>:0 at BlazorTestApp2.Shared.Login.ValidateUser (System.String userName, System.String password) [0x0006d] in C:\Repo\BlazorTestApp2\BlazorTestApp2\Shared\Login.razor:83 at BlazorTestApp2.Shared.Login.LoginWithPassword () [0x0003f] in C:\Repo\BlazorTestApp2\BlazorTestApp2\Shared\Login.razor:116
```

Is this can be fixed anyway?

> net version used : 3.1.0-preview4.19579.2

**Comment by sukeshchand** [comment]
I have upgraded the version to 3.2.0-preview2.20160.5 and the issue got fixed.

For more info about new upgrade
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

**Comment by spmoran-blazor** [comment]
I'm still running into this is Preview 3.

**Comment by aelking** [comment]
This is an issue I am getting issue with the latest version as of today.

**Comment by connorwelborn** [comment]
I am also getting this issue on the latest release (Blazor WebAssembly 3.2.0 Release Candidate).

I am successfully able to use HttpClient with some APIs, but I get this error when trying to GetStringAsync from an Azure deployment of a ASP.NET Core API App I created.

**Comment by Sebastatouille** [comment]
Hello - I had the same issue, trying to make an App Blazor WebAssembly running on my own computer-localhost then and accessing a deployed Azure function => WebAssembly.JSException: TypeError: Failed to fetch

But I found that you have to allow CORS (cross origin ressource sharing) for the function itslef in azure (because the app is not deployed in azure itself)
check this article : https://csharp.christiannagel.com/2018/07/10/azurestoragestaticwebsite/  section CORS.

when activated (added the end point localhost:xxxx) in azure => it worked super well...

hope it can help ! have a good day !

**Comment by WoodyJ007** [comment]
I have the same problem using the latest builds. Internet has been telling me it's a cors issue and I've been going around in circles. The above basic code works fine on console and other apps. Tried it on a blazor server side and works fine so something is up with WebAssembly? Tried it on two from scratch projects on two different PCs and same result.  Any ideas?  Known issue still?

**Comment by WoodyJ007** [comment]
> I have the same problem using the latest builds. Internet has been telling me it's a cors issue and I've been going around in circles. The above basic code works fine on console and other apps. Tried it on a blazor server side and works fine so something is up with WebAssembly? Tried it on two from scratch projects on two different PCs and same result. Any ideas? Known issue still?

FYI. it's when connecting to a webapi on HTTP and project was set to configure for HTTPS.

`
 public async Task<string> GetSomeDataAsync()
    {
        var _client = new HttpClient();

        var response = await _client.GetStringAsync(@"http://dummy.restapiexample.com/api/v1/employees");

        return response;
    }
`

Create Blazor server project with "Configure HTTPS" NOT ticked.  Works
Create Blazor server project with "Configure HTTPS" ticked.  Works

Create the client web assembly project with "Configure HTTPS" NOT ticked.  Works
Create the client web assembly project with "Configure HTTPS" ticked.  Fail
