### ISSUE TITLE
Blazor Wasm 3.2.0 Preview 3 - RequestAccessToken doesn't pass additional scopes with Oidc provider

### ISSUE THREAD

**Issue by cradle77** [dotnet/aspnetcore#20288]
Hello, there seems to be a bug in the implementation of `ITokenProvider.RequestAccessToken` when used with the generic Oidc provider.

**Issue summary**: RequestAccessToken doesn't pass the requested scopes to oidc-client.js

I've created a repo in GitHub that reproduces the issue:
https://github.com/cradle77/RequestAccessToken

There are 3 projects:
1) IdentityServer, which defines an API resource `weatherapi` and a `blazor` client
2) a WeatherApi web api
3) a Blazor WebAssembly client

**Steps to reproduce:**
1) Run the three projects
2) Log in in the Blazor Wasm project. The project is configured to request only `openid` and `profile` as default scopes:
```
builder.Services.AddOidcAuthentication(options =>
{
    // Configure your authentication provider options here.
    // For more information, see https://aka.ms/blazor-standalone-auth
    options.ProviderOptions.Authority = "https://localhost:44399/";
    options.ProviderOptions.ClientId = "blazor";
    options.ProviderOptions.DefaultScopes = new List<string> { "openid", "profile" };
    options.ProviderOptions.PostLogoutRedirectUri = "/";
    options.ProviderOptions.ResponseType = "code";
});
```
3) try to open FetchData, which should request an access token for `weatherapi`:
```
protected override async Task OnInitializedAsync()
{
    var httpClient = new HttpClient();
    httpClient.BaseAddress = new Uri("https://localhost:5002");

    var tokenResult = await this.TokenProvider.RequestAccessToken(
        new AccessTokenRequestOptions()
        {
            Scopes = new[] { "weatherapi" }
        });

    if (tokenResult.TryGetToken(out var token))
    {
        httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token.Value}");
        forecasts = await httpClient.GetJsonAsync<WeatherForecast[]>("WeatherForecast");
    }
    else
    {
        Console.WriteLine("No Token!");
    }
}
```

**Expected behaviour:**
Blazor requests an access token with `weatherapi` as a scope, gets the token from IS4, calls the api and gets the results

**Actual behaviour**
Blazor doesn't request the token, the method returns the ID Token (`openid` and `profile` as a scopes), the API returns a 401

-------

From an initial investigation, `RemoteAuthenticationService` seems to be correctly passing the optional scopes to JavaScript:
```
public virtual async ValueTask<AccessTokenResult> RequestAccessToken(AccessTokenRequestOptions options)
{
    ...
    var result = await _jsRuntime.InvokeAsync<InternalAccessTokenResult>(
      "AuthenticationService.getAccessToken", options);
...
```

However, the function in `AuthenticationService.ts` doesn't have any parameters, nor it passes them to oidc-client-js:

```
public static getAccessToken() {
    return AuthenticationService.instance.getAccessToken();
}

.....

class OidcAuthorizeService implements AuthorizeService {
    ...
    async getAccessToken(request?: AccessTokenRequestOptions): Promise<AccessTokenResult> {
        // request will always be null here
        }
    }
```

**Proposed solution:**
we need an optional parameter in the static function invoked by `RemoteAuthenticationService`:
```
public static getAccessToken(request?: AccessTokenRequestOptions) {
    return AuthenticationService.instance.getAccessToken(request);
}
```

**Comment by vstribrny** [comment]
I have run into the same problem - as a workaround, I added the scope for API resources into the default scopes and it works then: 

`options.ProviderOptions.DefaultScopes = new List<string>(new[] { "openid", "profile", "myApi" });`

**Comment by jan-johansson-mr** [comment]
Hi, I've done the same observation as you guys.

**Comment by javiercn** [comment]
Hi, in general it is recommended that you pass in all the scopes during the initial sign in (which is what DefaultAccessToken scopes is for) as otherwise you are going to need to handle redirects and so on in your app, which is not a great experience.

The main reason `public virtual async ValueTask<AccessTokenResult> RequestAccessToken(AccessTokenRequestOptions options)` is for AAD scenarios, because they separate the scopes into resources and you can't request more than one at the same time, but even in that case there is an "additional scopes to consent" so that you can pass in all the scopes and get consent during sign-in, so that when you use RequestAccessToken with options it is able to provision the token silently.

That said, the issue is trivial to fix, so we are fixing it, but the recommendation is still that you request all the scopes you need during the initial sign in.

**Comment by jan-johansson-mr** [comment]
Thanks!
