### ISSUE TITLE
SignalR awaiting SendAsync for a Group is prolonged when one client's connection drops unexpectedly

### ISSUE THREAD

**Issue by praeliorz** [dotnet/aspnetcore#20282]
I have a Hosted Service that collects changes that clients need to know about in a BufferBlock to send them out one at a time, using an IHubContext. If one client's connection drops (i.e. VPN disconnected), then awaiting one small message can take 7.4 to 16 seconds. I've seen longer in log files but have reliably duplicated the issue in the seconds time frame.

In order to prevent one connection from slowing down everyone else in the same group, do you recommend:

1. send to each connection separately and stop using groups
2. don't await for one message to complete before moving onto sending the next message so that healthy clients keep receiving the messages
3. another option?

Thanks!

**Comment by anurse** [comment]
@praeliorz Can you provide a runnable sample that demonstrates how you're writing to the groups?

In *general*, a slow client should not affect when the `SendAsync` completes. However, if there's a long backlog of messages waiting for a single client and the client has disconnected (and is thus not recieving them), then you can end up blocked.

**Comment by praeliorz** [comment]
@anurse Absolutely. Here's an ASP.NET Core 3.1 test website:
[https://github.com/praeliorz/TestSignalR](https://github.com/praeliorz/TestSignalR)

**Couple notes on the code:**
- Web/Services/TestService.cs has the test code that is sending out messages.
- Web/Views/Portal/Index.cshtml, the UI, is merely incrementing a counter for every message it receives. This helps visualize when messages stop sending.
- NLog is included to record a warning when this issue occurs.

**Note on the test data:**
- I'm sending simple strings for test data.
- Realistically, clients may see anywhere from 1 message per second to 10 per second.
- It's quite possible the same client could have more messages waiting to send from a request sent from the client to the Hub right before a disconnect happened (this scenario is not included in the test code).

**Two options I've used to duplicate:**
- Run one browser window pointing directly to the website and another through a proxy server like TMnetsim. Stop the proxy server.
- Run one browser window locally and another over VPN. Disconnect the VPN.

Thank you!

**Comment by BrennanConroy** [comment]
>     * Realistically, clients may see anywhere from 1 message per second to 10 per second.

I'm seeing 100's of messages per second, and if you include the fact that they're batched in groups of 100 normally, that's really 10's of thousands of messages per second.

Is that the expected traffic for your app?

I wasn't able to repro a large delay, the highest I saw was ~450ms. Maybe it's because I wasn't closing the second connection improperly.

**Comment by praeliorz** [comment]
The test is sending more data than expected traffic. It's an easy way to perform a stress test and duplicate the issue. I'm only seeing the issue when a lot of data is sending and an unhealthy disconnection occurs. It's beautiful how many messages SignalR handles so quickly.

Using expected data, it's far harder to duplicate the issue. The issue did not appear in months of testing and verification. I need a backlog of messages waiting to send for a single client and then break the connection before the messages send. The application sends a burst of data on page load to the caller over SignalR (e.g. initial data). If the client has to reconnect, this same burst occurs to be sure the client has the latest data that was missed. The best way I've duplicated this is to connect multiple clients, drop their connections, allow them to reconnect, and repeat.

I know I've got connectivity issues at play here: wireless signals drop, VPN drops, latency, and a mix of all three. I suspect one or more clients constantly reconnecting is a huge contributing factor.

The plan so far to resolve this: use web APIs for the initial data burst to reduce the amount of SignalR messages to only incremental changes. Second, send messages to individual clients instead of groups just in case for now. Third, add additional logging to track excessive reconnections and if any delays occur when sending to a client. And finally, use logging data to help bubble up network issues.

**Comment by BrennanConroy** [comment]
> use web APIs for the initial data burst to reduce the amount of SignalR messages to only incremental changes

Oh I see, so when the client connects and is getting the large burst, you're sending the normal data in parallel to it so all the connection and it gets a large buffer of data to consume before being like a normal connection and getting the usual pace of messages.

The web API method sounds like it could help, you could also not join the group with the reconnected connection until it has caught up with the backlog of messages, that way you avoid potentially blocking the group while it catches up.

**Comment by praeliorz** [comment]
Good idea. Thanks for the feedback and advice.
