### ISSUE TITLE
Blazor Webassembly & gRPC

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#20287]
running a Grpc Service consuming northwind customers. 
Works with blazor Server and crashes with  Blazor Webassembly - same code (northwind.razor)

blazor.webassembly.js:1 Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")

project https://github.com/hannespreishuber/BlazorWebAssemblyNorthwind

latest builds..

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. gRPC is not supported in browsers. You should use gRPC-web instead.
You can learn more about this at https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1

**Comment by hannespreishuber** [comment]
ah ok, would be helpfull to add some console message for that
