### ISSUE TITLE
[Blazor WASM] Protected API endpoint returns HTML instead of JSON

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#20297]
On a blazor WASM AspNet hosted I have an endpoint protected by a policy but when using `HttpClient` from WASM with a user which does not meet the policy requirements I still get response `200 OK` but the `HttpContent` is the `Areas/Identity/Pages/Account/AccessDenied.cshtml` page.

Of course on the client side it throws below exception, which can be seen in the browser console, due to the fact that the `HttpContent` cannot be deserialized to JSON:

```
blazor.webassembly.js:1 fail: [0]
      The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
System.NotSupportedException: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
  at System.Net.Http.Json.HttpContentJsonExtensions.ValidateContent (System.Net.Http.HttpContent content) <0x328a438 + 0x0009e> in <filename unknown>:0 
  at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync[T] (System.Net.Http.HttpContent content, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x328a290 + 0x00006> in <filename unknown>:0 
  at MovingPicturesEvents.Web.Client.Pages.Admin.GetAllImagesAsync () [0x0019c] in G:\Users\mdumi\GitRepos\LaurKyt\src\Client\Pages\Admin.razor.cs:60 
  at MovingPicturesEvents.Web.Client.Pages.Admin.OnInitializedAsync () [0x00097] in G:\Users\mdumi\GitRepos\LaurKyt\src\Client\Pages\Admin.razor.cs:34 
```

API side:

        [Authorize(Policy = "IsAdmin")]
        [HttpGet("/images/all", Name = "All_Images")]
        public async Task<IActionResult> GetAllImagesAsAdmin()
        {
            // get from repo
            var imagesFromRepo = await _imageRepository.GetAllAsync();

            // map to model
            var imagesToReturn = _mapper.Map<IEnumerable<Image>>(imagesFromRepo);

            // return
            return Ok(imagesToReturn);
        }

Client Side:

        public async Task<List<Image>> GetAllImagesAsync()
        {
            var request = new HttpRequestMessage(HttpMethod.Get, "Images/all");
            var response = await _httpClient.SendAsync(request);

            Console.WriteLine(response.StatusCode.ToString());
            Console.WriteLine(response.ReasonPhrase);

            if (!response.IsSuccessStatusCode)
            {
                return new List<Image>();
            }
            else
            {
                Console.WriteLine(await response.Content.ReadAsStringAsync());

                return await response.Content.ReadFromJsonAsync<List<Image>>();
            }

        }

I know applying same policy on the client side might fix this issue, but still, how can I make the API return the correct status code `401 Unauthorized` and JSON content?

**Comment by mihaimyh** [comment]
I guess it is the same issue as here https://github.com/dotnet/aspnetcore/issues/9039 and I fixed it by adding:

```
        services.ConfigureApplicationCookie(options =>
            {
                options.Events.OnRedirectToLogin = context =>
                {
                    context.Response.StatusCode = 401;
                    return Task.CompletedTask;
                };

                options.Events.OnRedirectToAccessDenied = context =>
                {
                    context.Response.StatusCode = 401;
                    return Task.CompletedTask;
                };
            });
```

Is this the recommended way of doing it?

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

Can you provide a minimal repro project and detailed steps to trigger this issue so that we can help you determine what's going on here?

**Comment by mihaimyh** [comment]
Hi Javier,

There is a repo here https://github.com/mihaimyh/laurkyt but, please note that I've already added code mentioned above to the Startup.cs.

Mihai

**Comment by javiercn** [comment]
Not sure what's going on with your repro, but I tried on a simplified project that we have and I get back a 403 as espected.

![image](https://user-images.githubusercontent.com/6995051/77903688-1e482100-7238-11ea-99ba-9a4e6e9572bb.png)

For context, the project I used is setup to use roles and I simply went to an action and changed a role name for a non existing one. That's should trigger the same behavior.

I believe what's happening must have to do with the way you configure Identity since I saw that you are calling AddIdentity instead of AddDefaultIdenttiy.

Moving this to the identity area as they can better help you since this doesn't seem Blazor specific.

**Comment by javiercn** [comment]
@HaoK  can you help here? Seems like AddIdentity is behaving differently than AddDefaultIdentity

**Comment by mihaimyh** [comment]
@javiercn With AddDefaultIdentity I don't have this issue anymore.

**Comment by HaoK** [comment]
@mihaimyh so everything works properly when you use AddDefaultIdentity but not if you call AddIdentity?

**Comment by mihaimyh** [comment]
@Haok Yes, with default identity is working fine.

**Comment by HaoK** [comment]
So everything is working fine for you now?

**Comment by mihaimyh** [comment]
> So everything is working fine for you now?

Yes, thanks.
