### ISSUE TITLE
CultureInfo.CurrentCulture cannot be changed in Blazor Wasm.

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#20290]
### Describe the bug
I tried to click on the button to modify `CultureInfo.CurrentCulture`, but it doesn't work.

### To Reproduce

``` C#

<p>@CultureInfo.CurrentCulture.Name</p>
<button @onclick="(_=>ChangeLanguage("en-US"))">Click</button>

@code{
   public void ChangeLanguage(string language)
   {
        CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(language);
   }
}

```

Got Exceptions? Include both the message and the stack trace
-->

### Further technical details
- ASP.NET Core version: 3.1.201
- Microsoft.AspNetCore.Components.WebAssembly.*: 3.2.0-preview3.20168.3

**Comment by javiercn** [comment]
@ElderJames thanks for contacting us.

I believe this is not something specific to Blazor and that you will get a faster and better answer if you file an issue in the [mono/mono](https://github.com/mono/mono) repository.

**Comment by pranavkm** [comment]
@ElderJames, `CultureInfo.CurrentCulture` is async-scoped. You need to use https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentculture?view=netstandard-2.1 to configure it. 

We're adding additional support for localization as part of 3.2-preview4 part of which involves loading satellite assemblies. Satellite assemblies are only downloaded as part of the `MainAsync` sequence. To facilitate this, we think have a pattern that involves reloading the app works best to change the culture. Here's what it looks like:

* https://github.com/pranavkm/LocSample/blob/master/Shared/CultureSelector.razor
* https://github.com/pranavkm/LocSample/blob/master/Program.cs#L22-L29

**Comment by ElderJames** [comment]
Thank you, I have implement that with a service to hold the current culture and use a event to notify the StateHasChanged without force reload.

https://ant-design-blazor.gitee.io
