### ISSUE TITLE
CORS problem with subresource integrity

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#20305]
I am trying to load the webassembly version of blazor into an existing javascript app.
But I have problems with the subresource integrity. It throws this error message:
```console
Subresource Integrity: 
The resource 'http://test.local/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js' has an integrity attribute,
but the resource requires the request to be CORS enabled to check the integrity, and it is not.
The resource has been blocked because the integrity cannot be enforced.
```

I included the script within the head with this snippet:
```javascript
var script = document.createElement('script');
script.src = 'http://test.local/_framework/blazor.webassembly.js';
document.head.appendChild(script);
```

**Comment by javiercn** [comment]
@MarkusRodler thanks for contacting us.

@SteveSandersonMS thoughts?

**Comment by MarkusRodler** [comment]
Additional info: If I remove the adding of the integrity attribute in blazor.webassembly.js it will work as expected.
If I remove this command in particular:
```javascript
n.integrity = r;
```
And I have to refactor the urls within this file to be absolute instead of relative because I download it from another domain. For example: fetch("http://test.local/_framework/blazor.boot.json" [...]

**Comment by SteveSandersonMS** [comment]
If you want to disable integrity checking, you can do so by adding this to your project file:

```xml
<BlazorCacheBootResources>false</BlazorCacheBootResources>
```

Otherwise, integrity checking will be enabled and is behaving as expected. The restriction that CORS is required is a restriction controlled by the browser, not Blazor.

**Comment by MarkusRodler** [comment]
@SteveSandersonMS Thanks for your answer. This is an option but I think it would be better to not disable this flag. I have read more about this topic and I think it is a bug in the generation of the link tag.

I think it is a crossorigin="anonymous" attribute missing. If I add it, then everything works:
```javascript
 var r = e.bootConfig.resources.runtime[t]; n.integrity = r; n.setAttribute('crossorigin', 'anonymous'); console.log(n); 
```
Output:
<script src="http://test.local/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js" defer="" integrity="sha256-80Q7rIpqLxXzuMWqtC+FCBNrG15kR/r+ba08n2TpQO0=" crossorigin="anonymous"></script>

Here are some additional resource that I found:
https://github.com/aspnet/Templating/issues/781
https://github.com/symfony/webpack-encore-bundle/issues/55

**Comment by SteveSandersonMS** [comment]
@MarkusRodler That sounds good! If you're interested in making a PR that does this, I think we'd be pleased to accept it.

**Comment by MarkusRodler** [comment]
@SteveSandersonMS I searched throughout the project, but actually I have no idea where the blazor.webassembly.js file is generated. 😄 I can fix it in the generated file but that does not help.
Can you point me to the file where the integrity is set?

**Comment by SteveSandersonMS** [comment]
For that specific script tag, it's here: https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L135

If you're changing this, can you please also change other places where `integrity` is set?

 * https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Platform/WebAssemblyResourceLoader.ts#L30
 * https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Platform/WebAssemblyResourceLoader.ts#L99
 * https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/wwwroot/service-worker.published.js#L21

Not sure if there are others. It's worth searching the source tree for `integrity` to be sure.

Thanks!

**Comment by MarkusRodler** [comment]
Ah my mistake was that I did not switched the branch to blazor-wasm 💡

**Comment by MarkusRodler** [comment]
I created a pull request for the problematic file but not for all possible files

**Comment by javiercn** [comment]
@SteveSandersonMS asigning this to you to confirm the merge

**Comment by SteveSandersonMS** [comment]
@javiercn I don't think this is ready to go, as per comment on the PR. I'll take myself back off this and move it out of the preview 4 milestone.

**Comment by MarkusRodler** [comment]
@SteveSandersonMS What should be set on the other three places? Your first link points to the generation of an html tag. This is the only one I found in that project with an integrity attribute.
The other three links points to fetch-API calls. I didnt't found a `crossOrigin` attribute there but an `mode` attribute to set. But these links are not problematic in my case. Everything works to download _framework stuff via CORS. I don't know if it will be inherited from the first generated html tag or if the default is cors.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @MarkusRodler!
