### ISSUE TITLE
TestServer returns body when StatusCode is 204/NoContent which differs from asp.net core server

### ISSUE THREAD

**Issue by DonFrazier** [dotnet/aspnetcore#20302]
### Describe the bug
I have been updating functional tests for an asp.net core web API service to use TestServer instead of  a separate running service instance as outlined here:
https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1

I have one method which returns 204/NoContent but also includes a response body with JSON result.  I realize this is not a standard behavior.

When this method is called against a running server, the response status code is 204 and no body is returned.

When making the same request with TestServer the body is returned. This test behaves differently when running against a live server vs. TestServer.

### To Reproduce
Easy to repro by making any Controller method that returns 204 and content.  Observe difference returned results.

This is a low priority issue.  I will update my API to conform to the spec.  But there is a difference between the TestServer and a deployed instance.

### Further technical details
- ASP.NET Core version: 3.1
Here is my unit test project that shows my references to versions that use TestServer
  &lt;ItemGroup>
    &lt;PackageReference Include="FluentAssertions" Version="5.10.3" />
    &lt;PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.1.3" />
    &lt;PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.3" />
    &lt;PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    &lt;PackageReference Include="xunit" Version="2.4.1" />
    &lt;PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      &lt;PrivateAssets>all</PrivateAssets>
      &lt;IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    &lt;/PackageReference>
  &lt;/ItemGroup>

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by anurse** [comment]
> This test behaves differently when running against a live server vs. TestServer.

It's not uncommon for TestServer and a "live" server to have different behavior. Even the server behaviors are sometimes inconsistent.

It actually seems useful that TestServer would not filter out content to allow an application's tests to properly assert that there is no body in a 204 response (since a body is not allowed by the spec).

My sense is that this behavior is by design.

**Comment by DonFrazier** [comment]
Everything else worked 100% except the PUT response.  I understand there is no test like PRODUCTION.  This test was the only one that had any issue when I switched from hitting a running service to using TestServer.  If it's supposed to be different in the one small area, I would be surprised.

https://github.com/dotnet/aspnetcore/issues/4398
implies the server code was updated specifically for this behavior.  I don't see that the TestServer ever participated in a similar change.

**Comment by anurse** [comment]
@DonFrazier can you share the test code, to give some more context? I'm certainly not opposed to making a change if it seems valuable here.

**Comment by DonFrazier** [comment]
```
F5 and run from any template project

        [HttpGet]
        public ContentResult Get()
        {
            // iwr -uri https://localhost:44367/weatherforecast
            // observe content is present
            return Content(HttpStatusCode.OK);
        }

        [HttpPut]
        public ContentResult Put()
        {
            // iwr -uri https://localhost:44367/weatherforecast
            // observe content is empty
            return Content(HttpStatusCode.NoContent);
        }

        private static ContentResult Content(HttpStatusCode httpStatusCode)
        {
            return new ContentResult { Content = "Hello", ContentType = "text/html", StatusCode = (int)httpStatusCode };
        }

   public class ShowTests : IClassFixture<WebApplicationFactory<WebApplication2.Startup>>
    {
        private readonly HttpClient httpClient;
        public ShowTests(WebApplicationFactory<WebApplication2.Startup> factory)
        {
            this.httpClient = factory.CreateClient();
        }

        [Trait("Category", "Functional")]
        [Trait("Category", "SkipWhenLiveUnitTesting")]
        [Fact]
        public async Task GetAndPutBothReturnContent()
        {
            var uri = new Uri("/weatherforecast", UriKind.Relative);
            var request = new HttpRequestMessage(HttpMethod.Get, uri);   //  GET
            var resp = await this.httpClient.SendAsync(request);
            var get = await resp.Content.ReadAsStringAsync();

            request = new HttpRequestMessage(HttpMethod.Put, uri);    // PUT
            resp = await this.httpClient.SendAsync(request);
            var put = await resp.Content.ReadAsStringAsync();
            get.Should().Be(put, "but it doesn't when run from a deployed server");
        }
    }
```

**Comment by anurse** [comment]
Triage: I think we're OK with this difference between TestServer and the real server. Testing with a live Kestrel instance (even in-process) is generally a better way to get 1:1 behavior between tests and production.
