### ISSUE TITLE
From 3.1 map routing

### ISSUE THREAD

**Issue by MathiasViggo** [dotnet/aspnetcore#20306]
Hello we got an issue that out folders looks like this:
* Areas
  * Basic
   * * Controllers
   * * * Message
   * * * * MessageController.cs
   * * * * AutoReplyController.cs

To access autoreply our routing in MVC looks like:
`routes.MapRoute(
                  name: "areas",
                  template: "{area=Basic}/{controller=Home}/{action=Index}/{id?}/{subid?}"
                );`

And in the controller it looks like:

    [Area("Basic")]
    [Route("Basic/Message/AutoReply/[action]")]
    public class AutoReplyController : MasterController
    {

How do we get this routing with endpoints?

**Comment by javiercn** [comment]
@MathiasViggo can you clarify what you are asking?

Are you asking about how to achieve the same results with attribute routing? You can declare multiple routes in your action, but I'm not sure what you are trying to achieve here.

**Comment by MathiasViggo** [comment]
At the moment we have this:
`                endpoints.MapControllerRoute(
                        name: "default",
                       pattern: "{area=Basic}/{controller=Home}/{action=Index}/{id?}/{subid?}"
                        );`

But when i try to access the page:
Basic/Message/Autoreply
It never reaches the Autoreply controller
