### ISSUE TITLE
WebApplicationFactory creates two instances of Startup class

### ISSUE THREAD

**Issue by hudecekd** [dotnet/aspnetcore#20307]
### Description
I have ASP.NET Core 3.1 web application and xunit test project.
I use `WebApplicationFactory` with `WithWebHostBuilder`.
If `CreateClient` is called instance of environment specific startup class is created:
- **twice** if `webBuilder.UseStartup(typeof(Startup).Assembly.FullName);` is used which means that `ConfigureServices` is also called twice.
- **once** if `webBuilder.UseStartup<Startup>();` is used.

This can cause unexpected behavior. For example if fluent validation is used and requests are made exceptions is thrown because of multiple ConfigureServices calls.

This happens for **ASP.NET Core 3.1** but DOES work for **ASP.NET Core 2.2**.

### To Reproduce
- Create ASP.NET Core 3.1. project
- Create xunit test project
- use `UseStartup` with assembly name
- Use `WebApplicationFactory`.
- Call `CreateClient`. See multiple startup calls
- Make request. validation exception is thrown (but original problem is multiple `Startup.ConfigureServices` calls)
- 

Source code with this problem is available at https://github.com/hudecekd/WebApplicationFactory

### Further technical details
- ASP.NET Core 3.1
- VS 2019
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@hudecekd thanks for contacting us.

This is due to changes in hosting that happened in 3.1. The startup callback will be queued immediately when calling UseStartup. 

So the recommendation is to call ConfigureServices and replace the services you need to mock for testing purposes.

**Comment by hudecekd** [comment]
@javiercn 

This example shows that if I just want to test application without any mocking it can cause problem because behavior of `UseStartup` methods is not same. So it is not related to any mocking but actual usage of `UseStartup` method in Program.cs.
