### ISSUE TITLE
MemoryStream is closed

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/aspnetcore#20303]
for example below the code throw a error message is  "Cannot access a closed Stream";

                  using (MemoryStream ms = new MemoryStream())
                    {
                        bool isOk = client.Download(ms, actfile);
                        if (isOk) return File(ms, "application/oct-stream", orcfile);
                    }

or

           MemoryStream ms = new MemoryStream();
            workbook.Write(ms);
            ms.Flush();
            ms.Position = 0;//here throw error

**Comment by davidfowl** [comment]
Don't put the memory stream in a using.

for example below the code throw a error message is  "Cannot access a closed Stream";

```C#
MemoryStream ms = new MemoryStream();

bool isOk = client.Download(ms, actfile);
if (isOk) return File(ms, "application/oct-stream", orcfile);
```

The framework is responsible for disposing the stream.

**Comment by bouyeijiang** [comment]
> Don't put the memory stream in a using.
> 
> for example below the code throw a error message is "Cannot access a closed Stream";
> 
> ```cs
> MemoryStream ms = new MemoryStream();
> 
> bool isOk = client.Download(ms, actfile);
> if (isOk) return File(ms, "application/oct-stream", orcfile);
> ```
> 
> The framework is responsible for disposing the stream.

not put the memory stream in a using

**Comment by davidfowl** [comment]
Is it possible something else is disposing the stream?

**Comment by bouyeijiang** [comment]
i don't known why has error

public class helper
{
public MemoryStream GetStream()
{
           MemoryStream ms = new MemoryStream();
            workbook.Write(ms);//写入文件
            ms.Flush();
            ms.Position = 0;//throw error stream is closed
            return ms;
}
}


public class ToHelper
{
 public ToHelper(){}
 public void To(){
  helper h=new helper();
  h.GetStream();//
}
}

**Comment by javiercn** [comment]
@bouyeijiang thanks for contacting us.

Can you provide a minimal repro project with instructions on how to trigger this issue?

**Comment by bouyeijiang** [comment]
> @bouyeijiang thanks for contacting us.
> 
> Can you provide a minimal repro project with instructions on how to trigger this issue?

[test.txt](https://github.com/dotnet/aspnetcore/files/4431091/test.txt)

**Comment by mkArtakMSFT** [comment]
The repro you've provided is not ASP.NET specific. If there is anything ASP.NET Core specific you're having problem with, please provide relevant repro, so that we can move forward with the investigation. It would be great to have that project as a GitHub repo, and it should be buidlable and runnable.
