### ISSUE TITLE
Environment variables still affect DebugProxy

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#20308]
I was getting some errors when trying to launch the debugger on my machine - Kestrel couldn't start because it said something was already listening on the same port. It appears to be because the debug proxy is still trying to inherit environment variables from the parent process.

By putting a breakpoint on the following line in `DebugProxyHost.cs`, it's possible to confirm that the `EnvironmentVariablesConfigurationProvider` is still being used:

![image](https://user-images.githubusercontent.com/1101362/77903428-c4b51600-727a-11ea-9007-8709e449e39b.png)

It looks like this is because both `GenericWebHostBuilder` and `WebHostBuilder` (not certain which is used in this case) are hardcoded to call `.AddEnvironmentVariables(prefix: "ASPNETCORE_")` in their constructors.

As such I'm not sure what is the recommended pattern for *not* loading config from environment variables. @Tratcher - do you have any suggestions?

I investigated to see if we could remove the `EnvironmentVariablesConfigurationProvider` after the builder is created, but that's not easy since by the time `ConfigureAppConfiguration` gets called, that provider is already nested several levels deep in `ChainedConfigurationSource` instances, which seems to be immutable.

If nothing else works we could go back to our previous pattern of removing all environment variables that start with the `ASPNETCORE_` prefix before launching the debug proxy, but cc @captainsafia for any other ideas.

**Comment by Tratcher** [comment]
I see what you mean.
https://github.com/dotnet/aspnetcore/blob/f990751f549417bade35e4c98d3d6ca07ecba43f/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L34-L40

Could you remove that provider in ConfigureHostConfiguration?

**Comment by Tratcher** [comment]
Also, I suggest switching from ConfigureWebHostDefaults to ConfigureWebHost. It won't completely remove this issue, but it will give you the lowest level of control.

**Comment by SteveSandersonMS** [comment]
> Could you remove that provider in ConfigureHostConfiguration?

I tried, but it didn't seem feasible because by the time `ConfigureHostConfiguration` runs, that provider is already nested several levels deep in `ChainedConfigurationSource` instances. These instances don't have any API to tell you about their underlying sources, and even if they did, they don't expose any APIs for mutating those sets.

**Comment by SteveSandersonMS** [comment]
Update: @Tratcher and I discussed this on a call and after some debugging, came to the conclusion that since we want to eliminate *all* inheritance of ASP.NET-related env vars from parent to child, it's not desirable to work around this using `ConfigureWebHost` (not that we could make this work anyway, since IISExpress injects itself into the child via the same inheritance of env vars).

Suggested plan:

 * For Blazor 3.2.0, we go back to removing the `ASPNETCORE_*` env vars. Are you OK to look into doing this, @captainsafia?
 * For ASP.NET Core 5.0, @Tratcher will file an issue suggesting we provide a way of *not* having an `EnvironmentVariablesConfigurationProvider` in the web host

**Comment by captainsafia** [comment]
> For Blazor 3.2.0, we go back to removing the ASPNETCORE_* env vars. Are you OK to look into doing this, @captainsafia?

Yes, I'll prep a PR for this.

**Comment by Tratcher** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/20328 for 5.0

**Comment by captainsafia** [comment]
Thanks, @Tratcher!

Closing this as it has been resolved in #20326.
