### ISSUE TITLE
[Blazor WASM] Support HLS media audio/video

### ISSUE THREAD

**Issue by Delaire** [dotnet/aspnetcore#20309]
### Support HLS m3u8 file format for audio & video
Blazor WASM  supports mp4 videos but does not support hls/m3u8 video format, am I missing something?

url : https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

### Further technical details

- VS 2019 pro PREVIEW 16.6.0 Preview 2.0
- Windows 10 Pro build 18363.720
- MS Edge Version 80.0.361.69 (Official build) (64-bit)
- Google Chrome Version 80.0.397.149
- .NET Core SDK Version: 3.1.300-preview-015048

**Comment by javiercn** [comment]
@Delaire thanks for contacting us.

I'm not sure there's anything specific blazor needs to do to support that. I imagine those things get rendered on a `video` tag and at that point there's nothing blazor specific there?

Can you make it work in plain HTML? Does it give any error message?

**Comment by Delaire** [comment]
Hello @javiercn yes you are correct I completely got side tracked... it works as expected.
