### ISSUE TITLE
No StackOverflowException is thrown when calling recursively too many times in blazor

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/aspnetcore#20314]
I had a method calling itself (indirectly) and I was running into the below error:
```
RuntimeError: memory access out of bounds
```
It took long time for me to figure out the real cause. Is there something blazor/webassembly runtime can do to throw StackOverflowException to make debugging easier?

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19369
