### ISSUE TITLE
Upgrade to latest O# LangaugeServer Extension

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20320]
https://www.nuget.org/packages/OmniSharp.Extensions.LanguageServer/

- Will be able to remove our [AutoFlushingStream](https://github.com/dotnet/aspnetcore-tooling/blob/c1c501215e8be5830090a41fd4bd87135ce35923/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs#L100) impl

- [x] Make sure that hovers/completions/whatnot work on HTMLY files.
- [x] Try removing AutoFlushingStream

Needs Verification in VS:
- [x] SemanticTokens (Ryan)
- [x] Completions
- [x] Completion resolve
- [x] signatureHelp
- [x] documentHighlight
- [ ] codeAction
- [x] codeLens
- [x] formatting
- [x] onTYpeFormatting
- [x] rename

Needs Verification in VSCode:
- [x] SemanticTokens (Ryan)
- [x] Hover
- [x] Completions
- [x] Completion resolve
- [x] signatureHelp
- [x] documentHighlight
- [x] codeAction
- [x] codeLens
- [x] formatting
- [x] onTYpeFormatting
- [x] rename

**Comment by TanayParikh** [comment]
Remove comment: https://github.com/dotnet/aspnetcore-tooling/pull/1948/files#diff-0d41ccb18ff91a95cbd69267725546adR169-R170

**Comment by NTaylorMullen** [comment]
Should validate this: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1173891?src=WorkItemMention&src-action=artifact_link

Once completed

**Comment by NTaylorMullen** [comment]
And this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1174096?src=WorkItemMention&src-action=artifact_link

**Comment by NTaylorMullen** [comment]
I believe this will also resolve: https://github.com/dotnet/aspnetcore/issues/25116

**Comment by ryanbrandenburg** [comment]
Post-upgrade problems:
- [ ]  No codelens in vscode or VS
- [ ] No completions in VS
- [ ] No signatureHelp in VSCode
- [ ] Lightbulb on unknown taghelper hangs in VS
- [ ] Rename doesn't work in VS
- [ ] OnTypeFormatting doesn't work in VS
- [ ] AutoCompletion doesn't work in VS
- [ ] VSCode gives errors about Synchronization failed: Token cancellation requested: undefined

**Comment by TanayParikh** [comment]
> Lightbulb on unknown taghelper hangs in VS

So something like:
`<NonExistantComponent>` -> invoke lightbulb -> VS hangs?

**Comment by ryanbrandenburg** [comment]
Like your example, except instead of "invoke lightbulb" it's just "click on the lightbulb (assumedly just to get a list of available actions)"
