### ISSUE TITLE
Need the ability to suppress the environment variable config source

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#20328]
https://github.com/dotnet/aspnetcore/issues/20308

### Describe the bug

Blazor's debug proxy runs as a separate process launched from the web app. When running behind IIS out-of-proc it inherits all of the environment variables from IIS/ANCM which causes it to think it is the one responsible for handling requests proxied from IIS. It also ends up with the wrong content root and other such config. Removing ConfigureWebHostDefaults or UseIISIntegration doesn't help because IIS sets the HOSTINGSTARTUPASSEMBLIES environment variable to inject itself (maybe that was a bad idea...).

The debug proxy app needs full control over its configuration and thus needs a way to suppress any config coming from environment variables. That's not possible today because the env var config provider is added by default.

https://github.com/dotnet/aspnetcore/blob/f990751f549417bade35e4c98d3d6ca07ecba43f/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L34-L40

### Proposal

Add a way that allows the caller of ConfiureWebHost and/or ConfigureWebHostDefaults to opt out of the environment variable config source.

**Comment by anurse** [comment]
> (maybe that was a bad idea...)

![The character "Chandler Bing" from the TV show "Friends" yells "I knew it" and gestures wildly at a character who is walking off camera.](https://31.media.tumblr.com/d3a36badad4ab1b6ca89b5b6e9da1d31/tumblr_inline_n1ojj6zKaC1qknuzb.gif)
