### ISSUE TITLE
Blazor/Razor: shorthand if and for

### ISSUE THREAD

**Issue by mnbeer** [dotnet/aspnetcore#20322]
For more concise markup and to mimic templating practices developers are used to in JavaScript frameworks, support in-tag "if" and "for" statements.

### So, in addition to this construction
```
@if(ICanEdit) 
{
    <button @onclick="DeleteMe"><i class="ms-Icon ms-Icon--Delete"></i></button>
}
```

### support this one-liner
`
    <button @if="ICanEdit" @onclick="DeleteMe"><i class="ms-Icon ms-Icon--Delete"></i></button>
`

**Comment by nadjibus** [comment]
This would be awesome!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do. We don't want introduce another way of doing what is possible with C#

**Comment by mnbeer** [comment]
I understand that decisions have to be made and after this post I will leave it be. But I want to stress how important it is to have a concise and familiar templating syntax if you want to lure developers away from Angular/Vue/React. Staying put is an opportunity lost.

My view of the history of C# is that its evolution has always included alternate, more elegant syntax. For if statements alone, think of the ternary operator, then the null-coalescing operator, and then the null-coalescing assignment operator. And, in-tag flow control statements wouldn't affect the core language anyway if the template engine extracted the statements out into a normal if() {} structure.
