### ISSUE TITLE
Fix VS completion icons

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20324]
All of our completion items (directives, components, TagHelpers, HTML) have the same "T" completion icon. We need to look into how the LSP client platform handles the icons we're returning and make this experience better.

![image](https://user-images.githubusercontent.com/2008729/77945668-d9db7600-7275-11ea-9243-c192d30d0452.png)

![image](https://user-images.githubusercontent.com/2008729/78056382-e45f4380-7339-11ea-98a7-b0ca03b4cfe6.png)

**Comment by ajaybhargavb** [comment]
This is an external issue. [Here is the PR](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/243472).
