### ISSUE TITLE
Error evaluating DynamicObject value in Blazor WASM

### ISSUE THREAD

**Issue by MarekPokornyOva** [dotnet/aspnetcore#20327]
### Describe the bug
I get error while evaluating DynamicObject descendant's value in Blazor WASM. I can't recognize if this is Blazor or Mono issue, pardon me if I reported this in incorrect repo.

### To Reproduce
Pages\Index.razor
``` C#
@page "/"
@code
{
	protected override void OnAfterRender(bool firstRender)
	{
		TEST.DO();
	}

	public static class TEST
	{
		public static void DO()
		{
			dynamic d = new TestDynamic();
			Log("Log value:"+(string)d); //works as expected
			Log("Log value:"+d); //causes exception
		}

		static void Log(string test)
		{
			Console.WriteLine(test);
		}
	}

	public class TestDynamic:System.Dynamic.DynamicObject
	{
		public override bool TryConvert(System.Dynamic.ConvertBinder binder,out object result)
		{
			result="dynamic value";
			return true;
		}
	}
}
```

Displaying the page in browser I see in browser's console output:
WASM: ﻿Log value:dynamic value blazor.webassembly.js
WASM: ﻿Unhandled exception rendering component: blazor.webassembly.js:1:34754
WASM: System.NullReferenceException: Object reference not set to an instance of an object. blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprFactory.CreateMethodInfo (Microsoft.CSharp.RuntimeBinder.Semantics.MethodSymbol method, Microsoft.CSharp.RuntimeBinder.Semantics.AggregateType methodType, Microsoft.CSharp.RuntimeBinder.Semantics.TypeArray methodParameters) <0x2281280 + 0x00004> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.VisitCONCAT (Microsoft.CSharp.RuntimeBinder.Semantics.ExprConcat expr) <0x22807c0 + 0x000a6> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch (Microsoft.CSharp.RuntimeBinder.Semantics.Expr pExpr) <0x227fde8 + 0x00262> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.Dispatch (Microsoft.CSharp.RuntimeBinder.Semantics.Expr expr) <0x2276360 + 0x00006> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Visit (Microsoft.CSharp.RuntimeBinder.Semantics.Expr pExpr) <0x2276180 + 0x00012> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.VisitBoundLambda (Microsoft.CSharp.RuntimeBinder.Semantics.ExprBoundLambda anonmeth) <0x2254128 + 0x00080> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.Rewrite (Microsoft.CSharp.RuntimeBinder.Semantics.ExprBoundLambda expr) <0x2253dd0 + 0x00010> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateExpressionTreeFromResult (System.Linq.Expressions.Expression[] parameters, Microsoft.CSharp.RuntimeBinder.Semantics.Scope pScope, Microsoft.CSharp.RuntimeBinder.Semantics.Expr pResult) <0x2243758 + 0x0000e> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore (Microsoft.CSharp.RuntimeBinder.ICSharpBinder payload, System.Linq.Expressions.Expression[] parameters, System.Dynamic.DynamicMetaObject[] args, System.Dynamic.DynamicMetaObject& deferredBinding) <0x211e990 + 0x000c2> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind (Microsoft.CSharp.RuntimeBinder.ICSharpBinder payload, System.Linq.Expressions.Expression[] parameters, System.Dynamic.DynamicMetaObject[] args, System.Dynamic.DynamicMetaObject& deferredBinding) <0x211e4c8 + 0x00030> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind (Microsoft.CSharp.RuntimeBinder.ICSharpBinder action, Microsoft.CSharp.RuntimeBinder.RuntimeBinder binder, System.Dynamic.DynamicMetaObject[] args, System.Collections.Generic.IEnumerable`1[T] arginfos, System.Dynamic.DynamicMetaObject onBindingError) <0x211ab48 + 0x0034a> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.CSharp.RuntimeBinder.CSharpBinaryOperationBinder.FallbackBinaryOperation (System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject arg, System.Dynamic.DynamicMetaObject errorSuggestion) <0x220a988 + 0x0004e> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at System.Dynamic.BinaryOperationBinder.FallbackBinaryOperation (System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject arg) <0x220a8c8 + 0x00010> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at System.Dynamic.DynamicMetaObject.BindBinaryOperation (System.Dynamic.BinaryOperationBinder binder, System.Dynamic.DynamicMetaObject arg) <0x220a7f0 + 0x0001c> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at System.Dynamic.BinaryOperationBinder.Bind (System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args) <0x220a6a8 + 0x00056> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at System.Dynamic.DynamicMetaObjectBinder.Bind (System.Object[] args, System.Collections.ObjectModel.ReadOnlyCollection`1[T] parameters, System.Linq.Expressions.LabelTarget returnLabel) <0x210d418 + 0x00154> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T] (System.Runtime.CompilerServices.CallSite`1[T] site, System.Object[] args) <0x220a108 + 0x00044> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at System.Runtime.CompilerServices.CallSiteOps.Bind[T] (System.Runtime.CompilerServices.CallSiteBinder binder, System.Runtime.CompilerServices.CallSite`1[T] site, System.Object[] args) <0x2216070 + 0x00010> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,string,object) blazor.webassembly.js:1:34754
WASM:   at (wrapper delegate-invoke) <Module>.invoke_bound_object_Closure_CallSite_string_object(System.Runtime.CompilerServices.CallSite,string,object) blazor.webassembly.js:1:34754
WASM:   at BlazorApp.Client.Pages.Index+TEST.DO () <0x1f51c10 + 0x0014a> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at BlazorApp.Client.Pages.Index.OnAfterRender (System.Boolean firstRender) <0x1f51038 + 0x00000> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleAfterRender.OnAfterRenderAsync () <0x1f48990 + 0x00028> in <filename unknown>:0 blazor.webassembly.js:1:34754
WASM:   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync () <0x1f486f0 + 0x0001c> in <filename unknown>:0 

### Further technical details
Tested with: Firefox 74.0 (64 bit)
Visual Studio 16.5.1
Project type: Blazor WASM
Project's target framework: .NET Standard 2.1
RazorLangVersion: 3.0
<PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.2.0-preview1.20073.1" />

Please note, the functionality works fine in .NET Core 3.1 console app.
``` C#
	class Program
	{
		static void Main(string[] args)
		{
			TEST.DO();
		}
	}
```
Console result:
Log value:dynamic value
Log value:ConsoleApp1.Program+TestDynamic

**Comment by javiercn** [comment]
@MarekPokornyOva thanks for contacting us.

I believe this must likely be a mono issue since "dynamic" is a runtime feature. I'm moving this issue to the mono repository.

**Comment by javiercn** [comment]
This issue was moved to mono/mono#19388
