### ISSUE TITLE
Fix completion resolve data in VS LSP editor scenarios

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20321]
Right now when we gather completion items from C#/HTML they aren't always correct

![image](https://user-images.githubusercontent.com/2008729/77945028-d1367000-7274-11ea-8b7f-421c502a00eb.png)

![image](https://user-images.githubusercontent.com/2008729/77945099-f3c88900-7274-11ea-920e-7e6b91e2f160.png)

This is most likely due to the platforms non-support for LSP's markup content. We should look at [how Roslyn and friends handle completion resolves](https://github.com/dotnet/roslyn/blob/74c510f27750fe5a32378222406cf00ba1b8ecea/src/Features/LanguageServer/Protocol/LanguageServerProtocol.cs#L272) and similarly convert our resolve requests into something VS understands.

**Comment by ryanbrandenburg** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/VSLanguageServerClient/pullrequest/241748?_a=overview
