### ISSUE TITLE
IIS Load Failure when targeting x86 platform

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/aspnetcore#20331]
### Describe the bug
Changing `PlatformTarget` to `x86` will result in a `HTTP Error 500.0 - ANCM In-Process Handler Load Failure` on run using IIS Express.

![image](https://user-images.githubusercontent.com/7112040/77961944-479c9780-72a0-11ea-8b38-2e10778041c2.png)

### To Reproduce
1.     dotnet new web -o repro
1. Open `repro/repro.csproj` in Visual Studio
1. In `Build` properties, change `Platform target` to `x86`  ![image](https://user-images.githubusercontent.com/7112040/77961722-e379d380-729f-11ea-9bec-870a6ebe870c.png)
1. Run `IIS Express`  ![image](https://user-images.githubusercontent.com/7112040/77961651-c34a1480-729f-11ea-91a6-fd4ea3cf45f7.png)

### Workaround
Add `<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>` to the project file.  ![image](https://user-images.githubusercontent.com/7112040/77961784-0310fc00-72a0-11ea-8cd5-295a1e90aa16.png)

### Further technical details
**`dotnet --info`:**
    .NET Core SDK (reflecting any global.json):
    Version:   3.1.200
    Commit:    c5123d973b

    Runtime Environment:
    OS Name:     Windows
    OS Version:  10.0.18363
    OS Platform: Windows
    RID:         win10-x64
    Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

    Host (useful for support):
    Version: 3.1.2
    Commit:  916b5cba26

**About Microsoft Visual Studio:**

    Microsoft Visual Studio Community 2019
    Version 16.5.1
    VisualStudio.16.Release/16.5.1+29920.165
    Microsoft .NET Framework
    Version 4.8.03752

    Installed Version: Community

I ran into this problem because I have `<PlatformTarget>x86</PlatformTarget>` in my `Directory.Build.props` for compatibility with external 32-bit DLLs. I created a new Blazor Server app which would use those libraries and it gave me that error when launching it.

**Comment by anurse** [comment]
Did you follow the more information link in the error page? It should go to our [IIS troubleshooting guide](https://aka.ms/aspnet/iis/troubleshoot) which will provide more information on how to get the exact error information. Can you go to that guide and follow the instructions to get more information from the Windows Event Log? That way we can see what might be going wrong.

**Comment by danielchalmers** [comment]
From Event Viewer:

**Event 1031, IIS Express AspNetCore Module V2**

>Application 'C:\Users\user\repro\' failed to start. Exception message:
Could not find dotnet.exe at 'C:\Users\user\repro\dotnet' or using the system PATH environment variable. Check that a valid path to dotnet is on the PATH and the bitness of dotnet matches the bitness of the IIS worker process.

**Event 1010, IIS Express AspNetCore Module V2**

>Failed to start application '/LM/W3SVC/2/ROOT', ErrorCode '0x8007023e'.

**Comment by anurse** [comment]
Have you installed the 32-bit version of the .NET Runtime? I saw you referenced `C:\Program Files\dotnet` above, but that's the 64-bit version. The 32-bit version needs to be installed separately (and I believe it doesn't come with VS). You can find it here: https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by danielchalmers** [comment]
you're completely right. I installed the 32-bit version and it's all working now. thank you!
