### ISSUE TITLE
HTTP Error 500.31 - ANCM Failed to Find Native Dependencies

### ISSUE THREAD

**Issue by Reds369** [dotnet/aspnetcore#20349]
Hi Guys,

I'm new to .net core and created a web application using verions 3.1.

I created a new IIS website to host this one but once the site is created and I click browse I receive the following error.

> HTTP Error 500.31 - ANCM Failed to Find Native Dependencies

I checked on the server the .net core Runtime version is 3.1.3 and the SDK version is 3.1.201.

I ran the following commands on the server in Powershell.

Runtime
`(dir (Get-Command dotnet).Path.Replace('dotnet.exe', 'shared\Microsoft.NETCore.App')).Name`

SDK
`(dir (Get-Command dotnet).Path.Replace('dotnet.exe', 'sdk')).Name`

I also tried changing the web.config from 
`<handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>`
to
`<handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>`

but this then gives me an error 

> Handler "aspNetCore" has a bad module "AspNetCoreModule" in its module list

My publish settings in Visual Studio is as follows:
Configuration - Debug
Target Framework - netcoreapp2.2 (this is my only option)
Deployment Mode - Framework-Dependant
Target Runtime - Portable.

I only changed the configuration to Debug as I am creating a QA environment.

Thanks in advance for the assistance.

**Comment by anurse** [comment]
Can you take a look at the [IIS troubleshooting guide](https://aka.ms/aspnet/iis/troubleshoot)? There's more information there on how to diagnose these issues. If that doesn't help, let us know.

> Target Framework - netcoreapp2.2 (this is my only option)

By the way, 2.2 is end-of-life and no longer supported, you should either upgrade to 3.1 or downgrade to 2.1 (both are long-term servicing releases) to get support.

**Comment by Reds369** [comment]
Thanks Anurse.

You were correct after upgrading to 3.1 that solved the issue for me.

Kind regards,
Ruben
