### ISSUE TITLE
Challenge Request does not redirect to the specified RedirectUri

### ISSUE THREAD

**Issue by TestO2015** [dotnet/aspnetcore#20347]
### Describe the bug
I have a Rest API whose task is to authenticate the user to Azure AD. It uses a ChallengeRequest to login in as follows:
```
return Challenge(new AuthenticationProperties
            {  
                RedirectUri = "http://google.com"  
            }, OpenIdConnectDefaults.AuthenticationScheme);  
```

There are 2 terms to delineate here:  

- **CallbackPath**: a parameter of the OpenIdConnect config. This URL must be authenticated in the list of 'Reply Urls' of the Identity Provider.  
- **RedirectUri**: a property passed into the Challenge Request.

What I expect is that the request will redirect to the **RedirectUri** after authenticating against the OpenIdConnect scheme. The purpose being to redirect to a custom URL specified in a Query String. It redirects to the **CallbackPath** instead.

One more piece of information: in another app off which the simplified prototype below was created from, the redirect works as expected on the Edge browser, but not on the Chrome browser.

### To Reproduce
1) You'll need an Identity Provider tenant setup, I used Azure AD.
2) Configure the following Reply Url in Azure AD: "https://localhost:44373/AuthService/"

Using the WebApplication found here, 
https://github.com/TestO2015/Repo1

Configure the Identity Provider settings in appsettings.config and then run the following API: https://localhost:44373/AuthService/login

---
### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 2019

**Comment by Tratcher** [comment]
RedirectUri does not replace CallbackPath, they serve different purposes.
AzureAd returns to the CallbackPath, finishes authenticating, and then if auth was successful it redirects to the RedirectUri.

CallbackPath must be set to a unique path for authentication such as `/signin-oidc`. https://github.com/TestO2015/Repo1/blob/b8f00c67b05d46d470984389af96e8d8e062a452/WebApplication1/WebApplication1/appsettings.json#L7

Why does your app set `options.DefaultAuthenticateScheme = IISDefaults.AuthenticationScheme;`? Are you trying to mix in Windows Auth here? Otherwise don't set that at all.

**Comment by TestO2015** [comment]
> AzureAd returns to the CallbackPath, finishes authenticating, and then if auth was successful it redirects to the RedirectUri.

@Tratcher That's what I expect to happen. But it doesn't redirect to the RedirectUri, it just ends up at the CallbackPath. Could this indicate something went wrong in the authentication process? I checked the Fiddler request (the last one that lands on the Callback path) and it did contain an Auth Token.

> Why does your app set options.DefaultAuthenticateScheme = IISDefaults.AuthenticationScheme;? Are you trying to mix in Windows Auth here?

I have one API authenticating against Windows but it doesn't look like I need that default, thanks.

**Comment by Tratcher** [comment]
Did you fix the CallbackPath so it was a unique value like "/signin-oidc" rather than pointing to the site root "/"? What do the server debug logs say for that request?

**Comment by TestO2015** [comment]
> Did you fix the CallbackPath so it was a unique value like "/signin-oidc"
I followed your advice, however unfortunately it didn't have any impact on this issue.

I've got a new information: 
It now works fine when I run it under **IIS Express** from the Visual Studio IDE. When I try to run it through **IIS** which I'm running in In-Process mode from an EXE file it works in the Edge browser and not in the Chrome browser. This was the original problem I was trying to reproduce.

Why could it work under IIS Express but not IIS?

**Comment by Tratcher** [comment]
Do you have IIS set up using HTTPS?

**Comment by Tratcher** [comment]
Reguardless, you should be able to look at the server debug logs to get more information about how that request was handled.

**Comment by TestO2015** [comment]
IIS isn't set up to use HTTPS at the moment.

Where can I find the server debug logs?

I collected two logs from the Event Viewer:

> Category: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware
EventId: 3
ConnectionId: 0HLUND7JI8NR0
RequestId: 0HLUND7JI8NR0:00000001
RequestPath: /app/login
SpanId: |df2e885c-46152432cb051809.
TraceId: df2e885c-46152432cb051809
ParentId: 

Failed to determine the https port for redirect.

> Category: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
EventId: 15
ConnectionId: 0HLUND7JI8NR0
RequestId: 0HLUND7JI8NR0:00000002
RequestPath: /app/signin-oidc
SpanId: |df2e885d-46152432cb051809.
TraceId: df2e885d-46152432cb051809
ParentId: 

'.AspNetCore.Correlation.OpenIdConnect.1gOTbkrbmtz1fU-wWFk3d6eANrEmKp0bCcfv_T382N8' cookie not found.

**Comment by Tratcher** [comment]
Enable https in IIS, Chrome has started requiring it for cookies like `.AspNetCore.Correlation.OpenIdConnect` that use `SameSite=None`.

**Comment by TestO2015** [comment]
> Enable https in IIS, Chrome has started requiring it for cookies like .AspNetCore.Correlation.OpenIdConnect that use SameSite=None.

@Tratcher It works now, thanks.

Our production environments will run under https so this should be OK.

**Comment by blowdart** [comment]
As it's working, closing
