### ISSUE TITLE
Update outdated libraries in starter templates

### ISSUE THREAD

**Issue by wenz** [dotnet/aspnetcore#20354]
### Is your feature request related to a problem? Please describe.
The starter templates use outdated versions of some libraries, Bootstrap and jQuery.validate. These should be updated to the latest versions.

### Describe the solution you'd like
Update the following libraries:
* jquery-validation (1.17.0 -> 1.19.1)
* Bootstrap (4.3.1 -> 4.4.1)

### Additional context
I am excluding jQuery from that list, since the version currently used (3.3.1) has a security vulnerability, so upgrading it isn't just a feature request; also, there is a separate issue #20001 for it.

**Comment by mkArtakMSFT** [comment]
This is a dupe of https://github.com/dotnet/aspnetcore/issues/20001

**Comment by wenz** [comment]
I respectfully disagree. #20001 is about an insecure, old version of jQuery being used; this here is about non-insecure, outdated versions of other JavaScript libraries being used. I'd recommend to keep them separate, since #20001 is IMVHO more critical than this one here.
