### ISSUE TITLE
Blazor server-side Cloudflare support

### ISSUE THREAD

**Issue by xXBuilderBXx** [dotnet/aspnetcore#20358]
Hey i can't seem to get blazor server-side to work fully with Cloudflare, i have tried some options in the docs such as https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1

I can get the websocket connection to actually connect but it does not trigger any events even when clicking on the sample counter button.

I am using Cloudflare with full https enabled and forward headers set in Startup.cs and an Nginx proxy.

Would there be any other way to hide my web server ip (possibly ddos protection) without using cloudflare or any other way to secure the server?

**Comment by javiercn** [comment]
@xXBuilderBXx thanks for contacting us.

I would suggest you turn on debugging to the maximum level as described below and try to capture the logs after you've clicked an element to see if the event is reaching the server.

One possible cause of this issue is that you haven't turned on session affinity (which server-side blazor needs to work) on Cloudflare. They have some docs on how to do it [here](https://developers.cloudflare.com/load-balancing/understand-basics/session-affinity/)

Add this to your _Host.cshtml
```razor
    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        (function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
            });
        })()
    </script>
```

Replace the logging section with this in your appSettings.json
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  }
}
```

**Comment by xXBuilderBXx** [comment]
Enabled debug logging but no events or logs are being sent when i click the button but the websocket definetely connects in the browser and server-side so not sure why it won't work, also do i really need to use load balancing for this it would require me to pay extra which i could do.

**Comment by javiercn** [comment]
@xXBuilderBXx you do, otherwise your app won't work between reconnections.

**Comment by xXBuilderBXx** [comment]
Has anyone actually tested this before so that i can be sure it works without paying first or would there be a way to route the websocket connection to it's own subdomain like ws.google.com that bypasses cloudflare but have the main site google.com behind cloudflare.

**Comment by javiercn** [comment]
@xXBuilderBXx unfortunately we don't have specifics about cloudflare or any other third party software like that, the best we can do is to point you to the deployment [docs]( https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.1).

I believe other people have got it working with cloudflare on the past, so I would check for docs on their side on how to specifically enable it or maybe stackoverflow and similar.

I know this is probably not what you want to hear, but at the same time I hope you understand that we have limited capacity to test all possible configurations, specially when third party software is involved.

The guidance that we've given you has worked in the past for people using server-side Blazor on Kubernetes, which should be very similar to your specific scenario.

Hope that helps.

**Comment by xXBuilderBXx** [comment]
Thanks for all your help i will see what i can do also about my other question would it be possible to have the websocket connection on its own subdomain like ws.google.com that bypasses cloudflare but have the main site still be google.com with cloudflare.

**Comment by javiercn** [comment]
@xXBuilderBXx that could be something to try. You could tweak the signalr connection as follows:
```razor
    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        (function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
            });
        })()
    </script>
```
Within configureSignalR you can configure the URL I believe, but I'm not sure if it will work.

**Comment by xXBuilderBXx** [comment]
Figured something like that was probably in there will check it out and see how it goes i guess thanks
