### ISSUE TITLE
Is it possible to read data from appsetting.json without the use of DI?

### ISSUE THREAD

**Issue by robbiescholz** [dotnet/aspnetcore#20351]
Hi,

For the project I am currently working on (.net core 3.1 webAPI) I need to read a settings data in the Main method. However, I cannot find a way to read data from setting.json files (custom or the default appsettings file) when there is no constructor provided (as is the case for the main method).

Could you please tell me how can reading the data from settings.json files be achieved without the use of DI?

**Comment by javiercn** [comment]
@robbiescholz thanks for contacting us.

I'm not sure what you are trying to accomplish, but you should be able to create a configuration instance without using DI and use it to read the underlying config. For example:
```csharp
            new ConfigurationBuilder()
                .AddJsonFile("path")
                .Build()
```

**Comment by robbiescholz** [comment]
Hi @javiercn ,

Thank you very much for your fast response.

The thing I do not understand is how to read the data from the added JSON file. In my Startup.cs I create the configuration with the path like this:

```
 public Startup(IWebHostEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddEnvironmentVariables()                                 
                .AddJsonFile("path", optional: false, reloadOnChange: true);
                
            Configuration = builder.Build();            
        }   
```     

However, in order to read the data from the added json file I need to have an the Configuration instance. In the case of the proper class it is clear that I can inject it using the constructor.
But how is this meant to be used when no constructor is available, such as in a static class of in my current situation from the main method.

```
public static void Main(string[] args)
        {            
            //TODO: Read the URL from the JSON file (???)
            //TODO: Send an HTTP request (OK)
            CreateHostBuilder(args).Build().Run();
        } 
```

**Comment by davidfowl** [comment]
You need to pass the configuration around explicitly in that case
