### ISSUE TITLE
BadHttpRequestException: Request body too large.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#20369]
Suddenly I am receiving the following error while uploading file size more than 30 MB:

>BadHttpRequestException: Request body too large.

Here is the Stack Trace:

> BadHttpRequestException: Request body too large.
> Microsoft.AspNetCore.Server.IIS.BadHttpRequestException.Throw(RequestRejectionReason reason)
> Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeRequestIO()
> Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory<byte> memory, CancellationToken cancellationToken)
> System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
> Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory<byte> buffer, CancellationToken cancellationToken)
> Microsoft.AspNetCore.WebUtilities.BufferedReadStream.EnsureBufferedAsync(int minCount, CancellationToken cancellationToken)
> Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
> Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool<byte> bytePool, Nullable<long> limit, CancellationToken cancellationToken)
> Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
> Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
> Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
> Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()
> Exceptionless.AspNetCore.RequestInfoCollector.GetPostData(HttpContext context, ExceptionlessConfiguration config, string[] exclusionList)
> Exceptionless.AspNetCore.RequestInfoCollector.Collect(HttpContext context, ExceptionlessConfiguration config)
> Exceptionless.ExceptionlessExtensions.GetRequestInfo(HttpContext context, ExceptionlessConfiguration config)
> Exceptionless.AspNetCore.ExceptionlessAspNetCorePlugin.Run(EventPluginContext context)
> Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

My web.config file as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!-- To customize the asp.net core module uncomment and edit the following section. 
  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <security>
      <requestFiltering>
        <!--This will handle requests up to 1000MB/ 1048576000 Byte-->
        <requestLimits maxAllowedContentLength="1048576000" />
      </requestFiltering>
    </security>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" hostingModel="InProcess">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44373" />
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
        <environmentVariable name="COMPLUS_ForceENC" value="1" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
```

My Application is running on IIS Express with `In Process` Hosting Model.

I have also tried everything descried here: [New default 30 MB (~28.6 MiB) max request body size limit](https://github.com/aspnet/Announcements/issues/267) but no luck. Receiving same error.

Necessary Info:

Visual Studio: 2019 16.5.1
.NET Core: 3.1.3
Windows: 1909 OS Build-18363.720

Thank you.

**Comment by jkotalik** [comment]
Can you add a call to `UseIIS()` like the following:

```c#
app.UseIIS(options =>
{
    options.MaxRequestBodySize = 1048576000
});
```
I thought we would read the maxAllowedContentLength field from IIS for the default, but potentially not.

**Comment by TanvirArjel** [comment]
@jkotalik I am getting:

>IApplicationBuilder builder does not contain definition for UseIIS.

**Comment by TanvirArjel** [comment]
Okay! Here I have come to the solution with following three steps:

## 1. IIS content length limit
The default request limit (maxAllowedContentLength) is **30,000,000** bytes, which is approximately **28.6MB**. Customize the limit in the web.config file:

```
<system.webServer>
  <security>
    <requestFiltering>
      <!-- Handle requests up to 1 GB -->
      <requestLimits maxAllowedContentLength="1073741824" />
    </requestFiltering>
  </security>
</system.webServer>
```

**Note: Without this application running on IIS would not work.**

## 2. ASP.NET Core Request length limit:
### For application running on IIS:
```
 services.Configure<IISServerOptions>(options =>
 {
      options.MaxRequestBodySize = int.MaxValue;
 });
```

### For application running on Kestrel:

```
services.Configure<KestrelServerOptions>(options =>
{
     options.Limits.MaxRequestBodySize = int.MaxValue; // if don't set default value is: 30 MB
});
```
## 3. Form's MultipartBodyLengthLimit

```
services.Configure<FormOptions>(x =>
{
     x.ValueLengthLimit = int.MaxValue;
     x.MultipartBodyLengthLimit = int.MaxValue; // if don't set default value is: 128 MB
     x.MultipartHeadersLengthLimit = int.MaxValue;
});
```

**Adding all the above options will solve the problem related to the file upload with size more than 30.0 MB.**
