### ISSUE TITLE
Add multiple Identity UI scaffolding

### ISSUE THREAD

**Issue by DarkoPecnik** [dotnet/aspnetcore#20362]
Im developing an MVC app with custom routing to accommodate a multi tenant scenario
localhost/tenant/controller/action/

I've tried to wrestle with the current hybrid Identity UI implementation as much as possible but im hitting limitations, mostly with razor pages routing.

I've now completely switched off defaultUI (razor pages) and gone to reconstruct MVC Identity from the source samples.
I've also tried to use razor pages alone, but routing is "impossible" to achieve what i want.

Please add and maintain distinct identity scaffolding for MVC and Razor Pages

**Comment by blowdart** [comment]
While this is a common issue, it's not common enough for us to divert work from other features I'm afraid. 

Only having razor pages for identity is by design.
