### ISSUE TITLE
SignalR Connection start returns status code 415 unsupported media type

### ISSUE THREAD

**Issue by MarcL-Botron** [dotnet/aspnetcore#20386]
# Issue description

When I initiate a connection to the server using "connection.start" one of the requests is responding with a 415 Unsupported media type. 

On closer inspection of the message, it appears to be sending:
* "Content-Type: text/plain;charset=UTF-8"
* Request Body: {"protocol":"json","version":1}

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core 3.0
- [ ] .NET Framework
- [ ] .NET Standard

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by scottaddie** [comment]
Any ideas, @BrennanConroy or @anurse?

**Comment by anurse** [comment]
@MarcL-Botron Can you put your app up in a GitHub repo or something so we can see the full context? I realize you were following a doc but there could be something quirky going on and seeing the full context gives us the best chance of figuring this out.

> * .NET Core 3.0

Be aware that .NET Core 3.0 is [end-of-life](https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/) and no longer supported. We strongly recommend updating to .NET Core 3.1 (which is a long-term servicing release). See the [full support policy for details](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

Having said that, we didn't change much here in 3.1 so if there *is* an issue, I'd expect it to be present in 3.1 as well, so we'll keep investigating.

**Comment by BrennanConroy** [comment]
No idea where the 415 is coming from (and we don't set that anywhere in SignalR)

Also, you can enable WebSockets in IIS by enabling the windows feature https://docs.microsoft.com/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1#enabling-websockets-on-iis

**Comment by MarcL-Botron** [comment]
@BrennanConroy Yeah, I was thinking about enabling the WebSocket protocol in IIS, but unfortunately, I do not have access to set that feature.

@anurse, I did think about that, so I updated to netcore3.1 after posting this issue, but I still got the same thing. I'll try to get it into a repo for you guys. I think it's related specifically to the "**Content-Type: text/plain;charset=UTF-8**" being sent because it should be using the "**Content-Type:application/json**" mime type for json payloads.

Not sure if the client is at fault for sending an invalid content-type, or the server's for not being able to handle it. What are your guys' thoughts

**Comment by anurse** [comment]
@MarcL-Botron If you can post the full app so we can reproduce the issue that would be helpful. We definitely [use `text/plain` intentionally](https://github.com/dotnet/aspnetcore/blob/14032eae0196914cbc3efcf2dc65cf46b81efe5b/src/SignalR/clients/ts/signalr/src/XhrHttpClient.ts#L36) and haven't seen this issue in our own testing, so understanding your application would help here.

> when I went end published the service to IIS,

Is this on a different server, or locally? If different, can you provide the Windows version?

**Comment by MarcL-Botron** [comment]
@BrennanConroy, @anurse, BTW guys, do you know how to disable the web sockets protocol from the ASP Core service? I looked into it but all I found were older posts about using SignalR with the .NET framework.

I think the issue itself may be related to the other protocols that SignalR falls back to if WebSockets aren't available?

**Comment by MarcL-Botron** [comment]
@anurse I'm just using the IIS on my host machine. My windows version is:
* OS Name	Microsoft Windows 10 Pro
* Version	10.0.18362 Build 18362

**Comment by anurse** [comment]
@MarcL-Botron great. Can you share the app though please? There may be something different about your app that is making this break in your environment but not ours.

**Comment by MarcL-Botron** [comment]
@anurse Here's the repo link: https://github.com/MarcL-Botron/signalr-server

Sorry about the wait.

**Comment by anurse** [comment]
Yep, I see the problem now :). You have an MVC controller at `/Notification` and you've mapped the SignalR Hub to `/Notification`. This causes a conflict and the first one registered wins (the controller in this case), so the message is going to the MVC controller.

**Comment by MarcL-Botron** [comment]
@anurse oh man, looks like I made a boo boo there. Just tried switching the SignalR Hub to a different endpoint and the error is gone! Thanks for the help.

**Comment by anurse** [comment]
No problem! It’s a bit of a tricky one to find ;)

**Comment by MarcL-Botron** [comment]
@anurse Yeah, it makes sense that it didn't show up during debugging since it was using the websocket protocol, but when websockets weren't available, it hit the rest endpoint instead.

Thanks a bunch for the help guys! I'm closing this issue
