### ISSUE TITLE
 error NU1102

### ISSUE THREAD

**Issue by antjazldev** [dotnet/aspnetcore#20381]
### Describe the bug
Hello I following the get started guide provided by https://nbarbettini.gitbooks.io/little-asp-net-core-book/content/chapters/your-first-application/create-aspnetcore-project.html
When i type
` dotnet new mvc --auth Individual -o AspNetCoreTodo`
I get:
![image](https://user-images.githubusercontent.com/62674300/78080126-31134080-7373-11ea-85a9-77a77d8ba16c.png)

When i try to restore I get the errors:
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102: No se encuentra el paquete Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore con la versión (>= 3.1.3)
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102:   - Versiones encontradas en dotnet-core: 236 [ versión más cercana: 3.0.0-preview4-19177-01 ]
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102: No se encuentra el paquete Microsoft.AspNetCore.Identity.EntityFrameworkCore con la versión (>= 3.1.3)
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102:   - Versiones encontradas en dotnet-core: 245 [ versión más cercana: 3.0.0-preview4-19177-01 ]
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102: No se encuentra el paquete Microsoft.AspNetCore.Identity.UI con la versión (>= 3.1.3)
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102:   - Versiones encontradas en dotnet-core: 245 [ versión más cercana: 3.0.0-preview4-19177-01 ]
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102: No se encuentra el paquete Microsoft.EntityFrameworkCore.Sqlite con la versión (>= 3.1.3)
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102:   - Versiones encontradas en dotnet-core: 128 [ versión más cercana: 3.0.0-preview4.19176.6 ]
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102: No se encuentra el paquete Microsoft.EntityFrameworkCore.Tools con la versión (>= 3.1.3)
C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj : error NU1102:   - Versiones encontradas en dotnet-core: 128 [ versión más cercana: 3.0.0-preview4.19176.6 ]
  Error de restauración en 318,63 ms para C:\Users\ABBA\Documents\AspNetCoreTodo\AspNetCoreTodo\AspNetCoreTodo.csproj.

My csproj looks like this:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>aspnet-AspNetCoreTodo-D05D96B0-19D3-4CCC-A46C-BFF3848D045D</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.3" />
  </ItemGroup>

</Project>
```
I just want to get started with .net core.
My dotnet --version is 3.1.201 
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by antjazldev** [comment]
dotnet --info:
```
SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
This is likely because you've disabled NuGet.org as a package source. Could you ensure it is enabled:

```
> dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  ```

**Comment by antjazldev** [comment]
the problem stopped once i added a Nuget.config file in the root of my project
![image](https://user-images.githubusercontent.com/62674300/78161932-ca8e3100-740b-11ea-8499-f861d9e0ca7f.png)

wheni type dotnet nuget list source i get :
![image](https://user-images.githubusercontent.com/62674300/78162065-f1e4fe00-740b-11ea-8659-ad8d4badae6d.png)

There is any configuration Im missing ? 
Do i Need to add the nuget.config file to every project i create ???

**Comment by pranavkm** [comment]
Have a look at https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources to configure NuGet sources globally.
