### ISSUE TITLE
属性注入

### ISSUE THREAD

**Issue by fmpfmp** [dotnet/aspnetcore#20395]
有很多基于aspnetcore的应用框架，都用Autofac替换了ASP.NET Core 自带的IOC，目的仅仅是为了实现属性注入；
ASP.NET Core 自带的IOC，是否应该实现属性注入？
怕滥用的话，可以加一个option开关，默认关闭；

**Comment by athinboy** [comment]
@fmpfmp 你是看了这个？https://www.cnblogs.com/stulzq/p/12610026.html 
直接发中文不行吧，那些开发者大都是英文的。

**Comment by athinboy** [comment]
https://github.com/dotnet/aspnetcore/issues/2131
https://github.com/dotnet/aspnetcore/issues/2331
https://github.com/dotnet/aspnetcore/issues/2346

**Comment by fmpfmp** [comment]
@athinboy    就是看了了这篇博文，并在下面做了回复，所以才想到到这里来提个issues

也是突发奇想，发了个中文

**Comment by athinboy** [comment]
@fmpfmp 唉，对这些人真失望，重要的特性不支持，不知道天天干啥呢！
