### ISSUE TITLE
WebAssembly configuration appsettings vs appSettings

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#20391]
With the latest Blazor WebAssembly preview configuration is supported by providing the appropriate `appsettings.{environment}.json` file.

With a standard net core project the same files are used but the case is different: **appsettings** vs **appSettings**. With a dual project where you can switch between server side or client side execution this means a pre build step is required in VS to not only copy but also rename the files to correct the case (from the project root for the server side to wwwroot for webAssembly).

Suggest to either change the config file name to **appSettings** or rather update the code which checks for these config files during the build process to check for it in a case insensitive way. Currently if the config files are "appSettings.*" these do not get included in the Blazor.boot.json options list.

**Comment by pranavkm** [comment]
The file name in ASP.NET Core server project is also named `appsettings.*.json` - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1. On a case sensitive operating system, a file named `appSettings.json` would not get picked up by the server project. We think using the lower cased form is consistent with how the rest of ASP.NET Core's configuration works.

**Comment by tn-5** [comment]
I think the capitalised version must have been from some old project template. This is a non-issue, will close.
