### ISSUE TITLE
Could not load type 'System.IO.Compression.ZipFile' from assembly on docker raspberry pi when publish with Trimmed 

### ISSUE THREAD

**Issue by leung85** [dotnet/aspnetcore#20407]
### Describe the bug

Below code can be run on window
But on docker with raspberry pi publish with /p:PublishTrimmed=true, have error:

>  Could not load type 'System.IO.Compression.ZipFile' from assembly 

### To Reproduce
Create a WebProject and Use below code then publish with /p:PublishTrimmed=true
```
[HttpGet("logs")]
     public ActionResult GetLog()
     {
         string startPath = @"./data/logs";
         string zipPath = @"./tmp/logs.zip";
         try
         {
             ZipFile.CreateFromDirectory(startPath, zipPath);
             var data = System.IO.File.ReadAllBytes(zipPath);
             var content = new System.IO.MemoryStream(data);
             const string contentType = "application/zip";
             var fileName = $"logs-{DateTime.Now.ToString("yyyyMMddhhmmss")}.zip";
             return File(content, contentType, fileName);
         }
         finally
         {
             System.IO.File.Delete(zipPath);
         }
     }
```

Got Exceptions? Include both the message and the stack trace
>  Could not load type 'System.IO.Compression.ZipFile' from assembly 

### Further technical details
version 3.1.3
Docker on raspberry pi

**Comment by javiercn** [comment]
@leung85 thanks for contacting us.

We believe this issue is not specific to ASP.NET Core. You'll get a better and faster answer if you file an issue in [dotnet/sdk](https://github.com/dotnet/sdk).

/cc: @Pilchie
