### ISSUE TITLE
ControllerBase / CreateApplicationModel question

### ISSUE THREAD

**Issue by bollhals** [dotnet/aspnetcore#20402]
Hey

I was investigating whether I can improve the startup time of my application and I saw that I spend a large amount of my time in the MapControllers function. 

In my project I have 41 Controllers inheriting from ControllerBase.
Now during the MapControllers call, a lot of time is spent on CreateApplicationModel.
Each of my Controller has a few methods (1-8) which it should take care of.

The ControllerBase has 12 public property and a lot of public methods annotated with [NonAction]. Due to this, they're all picked up in the CreateApplicationModel and processed.
For example the properties:
![image](https://user-images.githubusercontent.com/2437596/78115407-138db780-7403-11ea-9a91-21dc416e3c02.png)
There are 492 calls to CreatePropertyModel (492 / 11 controller = 12 properties => the one from ControllerBase) took ~11% of the MapControllers call.

Now to my question:
Could you enlighten me on why these properties / methods are all public? So far I only used them inside of the controller, so protected would've been enough (Protected would also mean they would be filtered out earlier)
Or could I do something else to not pay these costs?

**Comment by pranavkm** [comment]
They're public for [binding properties](https://github.com/dotnet/aspnetcore/blob/6ce8a879ae10e9f27798ec6e1c577092413f813d/src/Mvc/Mvc.Core/src/ControllerBase.cs#L68), ease of unit testing, and compatibility with MVC 5. Changing the visibility of these properties at this point would be a breaking change, so it's not something we would consider. If there are specific perf improvements you'd like to contribute that does not affect the public API surface, we'd be happy to consider it.

> Or could I do something else to not pay these costs?

You could consider using a POCO type or a more stripped down `ControllerBase` as a controller if you think this is a significant cost to your application: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerattribute?view=aspnetcore-3.1

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this, @bollhals.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by bollhals** [comment]
Thank you for providing the answer.

The POCO type certainly helps cutting down these costs 👍
