### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Versioning.* 4.x is not compatible with netstandard2.1

### ISSUE THREAD

**Issue by CreepyGnome** [dotnet/aspnetcore#20415]
This is a breaking change for people who were using Microsoft.AspNetCore.Mvc.Versioning.* 3.* which was netsteadard2.0.

Telling people to change their .NET Standard to a .NET Core library is not really acceptable without a really good reason why. None has been given.

Was this breaking change made by accident and you could just as easily build and deploy Microsoft.AspNetCore.Mvc.Versioning.* as .NET Standard or was it on purpose and no one documented it in the breaking changes migration documents?

I see no mention of breaking changes between 2.2 and 3.1 doc and this is a breaking change between migrating between those versions as we have to stop using .NET Standard for a lot of our supporting library which kind of defeats one of the purposes of .NET Standard.

https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1

**Comment by javiercn** [comment]
@CreepyGnome thanks for contacting us.

I don't think you have the right repository. According to the nuget.org package the source repo is [here](https://github.com/Microsoft/aspnet-api-versioning). I suggest you file an issue with them if you want to get a faster and better answer.

**Comment by javiercn** [comment]
@danroth27 @rynowak can you folks route this appropriately? This is not a package we own.

**Comment by CreepyGnome** [comment]
Moved to https://github.com/microsoft/aspnet-api-versioning/issues/617
