### ISSUE TITLE
Load Configuration On Application Startup from Backed (Blazor WebAssembly)

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/aspnetcore#20411]
We want to load Configuration from the server api and based on this configuration we want to configure our DI. So, we probably need to make a http call. In order to do this http call we need the DI configured so we can get a HttpClient. But DI is not configured, so we can't use HttpClient.

It would be nice to use the javascript to make this call, but we can't use IJSRuntime because it is also created after the DI is configured. (#5664, #5664)

So, can you provide a nice way that we can load Configuration Options On Application Startup before the DI is configured?

**Comment by javiercn** [comment]
@xrkolovos thanks for contacting us.

You can new-up an instance of HttpClient and the base url is available on the WebassemblyHostBuilder as part of preview3.

**Comment by javiercn** [comment]
@captainsafia Can you confirm here?

**Comment by captainsafia** [comment]
Unfortunately, this change is not available in preview3, but it will ship in preview4. The change will allow you to access the `BaseAdress` property from the builder to instantiate an HTTP client (`builders.HostEnvironment.BaseAddress`).
