### ISSUE TITLE
Expression bodied method with `@` prefixed variable usage in .razor files produces build errors

### ISSUE THREAD

**Issue by philippdolder** [dotnet/aspnetcore#20412]
### Describe the bug
The compiler produces build failures when expression body methods inside a `.razor` file access a variable with an `@` prefix as the first thing.

When I have this code inside of my `MyComponent.razor` file:

```csharp
private static bool AffectsOtherTable(MyEvent @event, string table) =>
    !@event.Table.Equals(table, StringComparison.OrdinalIgnoreCase);
```
I get the following build errors:
```
error RZ1006: The code block is missing a closing "}" character.  Make sure you have a matching "}" character for all the "{" characters within this block, and that none of the "}" characters are being interpreted as markup. 

error RZ1025: The "MyModel" element was not closed.  All elements must be either self-closing or have a matching end tag. 
```

I don't get them when using a different name for the `@event` variable:
```csharp
private static bool AffectsOtherTable(MyEvent e, string table) =>
    !e.Table.Equals(table, StringComparison.OrdinalIgnoreCase);
```
I don't get them when I reverse the expression (though it's not equivalent anymore, since `table` could be null)
```csharp
private static bool AffectsOtherTable(MyEvent @event, string table) =>
    !table.Equals(@event.Table, StringComparison.OrdinalIgnoreCase);
```
and I also don't get them when I write the method as statement body:
```csharp
    private static bool AffectsOtherTable(MyEvent @event, string table)
    {
        return !@event.Table.Equals(table, StringComparison.OrdinalIgnoreCase);
    }
```
### To Reproduce
See first code sample for the variant that's not working.
I run `dotnet build --configuration=Release /warnaserror .\MySolution.sln` from powershell to build the project.

### Further technical details
- ASP.NET Core version
The `.csproj` is targeting 
```<TargetFramework>netcoreapp3.1</TargetFramework>```
and references ASP.NET Core 3.1.2

- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
I'm using JetBrains Rider EAP 2020.1 EAP, though this has no influence on this issue.

**Comment by javiercn** [comment]
@philippdolder thanks for contacting us.

@NTaylorMullen do you have thoughts?

**Comment by javiercn** [comment]
@philippdolder you can try using `@@` to escape it, it might work

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Given that this is not a blocker as you can simply rename your variables, we are moving this issue to the Backlog to focus on more important issues for now.

/cc @NTaylorMullen would be great to know what your thoughts are why this isn't working. But don't spend time on investigation, if it's lengthy

**Comment by philippdolder** [comment]
> @philippdolder you can try using `@@` to escape it, it might work
I just went to use statement body style for this method as a work around. I guess the `@` somehow interfered with the parsing of `@` blocks in the razor file

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
