### ISSUE TITLE
Blazor Webassembly Identity Scaffolding Not Working

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#20422]
Create a new Blazor app using the `Blazor WebAssembly App` template with `ASP.NET Core Hosted` selected and `Individual User Accounts` authentication.

After the project is loaded add the identity scaffolding by right clicking the server project and selecting Add `New Scaffolding Item…` and select all files.

If you try to run the project, you will get a compile error due to missing using `Microsoft.AspNetCore.Identity`. If you fix that issue and follow the identity scaffolding read-me the app does not show correctly.

**Comment by PlattevilleWS** [comment]
Funny, I was just doing this same thing for my project. I ended up not doing anything from the read-me, because it was incorrect as you say. Just leaving the Startup.cs in it's original state seemed to work just fine (and fixing the missing Microsoft.AspNetCore.Identity using statement in RegisterConfirmation.cshtml.cs, as you mentioned).

That being said, the next issue I had was due to the Scaffolding site.css overriding the Client project's site.css, presumably because in a static file conflict it takes the file from the server project, causing the actual web assembly app to look wrong. After renaming one of them it ended up being fine, but this is another potential problem with the Scaffolding as it is.

**Comment by javiercn** [comment]
@rxelizondo thanks for contacting us.

We are aware of these issues and I believe we are working on smoothing out the experience.

/cc: @danroth27

**Comment by jvallejoa** [comment]
Yes, this is the same bug open in several threads. No way to scaffold accounts items, it corrupts all the entire page, I share the windows result. the message in console is DOMException-EntryAlreadyExists

@danroth27

Thanks

<img width="960" alt="error" src="https://user-images.githubusercontent.com/8346875/79162468-f06bec00-7da2-11ea-9b3e-b0582b35af64.png">
@danroth27

**Comment by bstorage** [comment]
After updating AspNetCore.Identity (2.2.0) and many other packages (not sure which are relevant here) I can no longer use scaffolding at all on Blazor WebAssembly, including on projects where I have used it previously. On right click of project and selecting Add/New scaffolded Item, I get an error titled "Import" having text: "'Microsoft.WebTools.Scaffolding.Core.ScaffolderFactory.FactoryConfigEvaluator' could not be satisfied."

**Comment by filipgoris** [comment]
Exactly the same issue here, but on ASP.Net Core Web Applications:

- Create a new Project
- Select ASP.Net Core Web Application
- Select ASP.Net Core 3.1
- On the newly created project: Add > New Scaffolded Item... 
brings up the error mentioned by @bstorage: 
"Import 'Microsoft.WebTools.Scaffolding.Core.ScaffolderFactory.FactoryConfigEvaluator' could not be satisfied."

Visual Studio 2019 Version 16.7.0 Preview 2.0
Templates 3.1.3

**Comment by drma-dev** [comment]
A different error appears to me when trying to add a scaffolded item. I would like to customize the login, for example.

InvalidOperationException: The following sections have been defined but have not been rendered by the page at ‘/Areas/Identity/Pages/Account/Manage/_Layout.cshtml’: ‘Scripts’. To ignore an unrendered section call IgnoreSection(“sectionName”).

several items are added, which I see as unnecessary. even deleting all that excess, I can’t get it to work.

**Comment by danroth27** [comment]
@bstorage @filipgoris It sounds like you're hitting a separate issue from what is described in this issue. Could you please submit a VS feedback issue for the problem you are seeing?

**Comment by danroth27** [comment]
@rxelizondo The compilation and styling issues you described should now be fixed. There are still some other issues with using the Identity scaffolder with Blazor WebAssembly projects, but we are tracking those with separate issues: https://github.com/dotnet/Scaffolding/issues/1325

**Comment by Rick-Anderson** [comment]
@bstorage @filipgoris  I reproduced this problem with VS 16.7.0 Preview 3.1 and reported it to [this VS feedback problem](https://developercommunityapi.westus.cloudapp.azure.com/content/problem/1098785/scaffolding-error-import-microsoftwebtoolsscaffoldingcorescaffolderfactoryfactoryconfigevaluator-could-not-be-satisfied.html)
