### ISSUE TITLE
Basic ClaimsTransformation Adding 50-100ms to Requests

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/aspnetcore#20426]
### Describe the bug
When using a very basic IClaimsTransformation, response times are significantly increased. 

### To Reproduce
Running .NET Core 3.1, hosting with Kestrel and Windows Auth. I was writing a simple check that, if the authenticated username was in a hashset, they would be allowed to access specific pages.

My first attempt used the onAuthenticated event from AddNegotiate, but I wanted the code to be functional in both IIS and Kestrel, which meant I was unable to use the onAuthenticated event (which doesn't appear to fire under IIS). So I switched to using a claims transform instead - if the user name is within a hashset of administrator users, add a claim indicating they are in the administrators role.

Here was the claims transfomer:
``` C#
    public class ClaimsTransformer : IClaimsTransformation
    {
        private readonly IPermissionManager _permissionsMgr;
        public ClaimsTransformer(IPermissionManager permissionManager)
        {
            _permissionsMgr = permissionManager;
        }

        public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            var name = principal.Identity.Name;
            principal.AddIdentity(_permissionsMgr.GetClaimsIdentity(name));
            return Task.FromResult(principal);
        }
    }
```

And here as the code from the permissions manager:
```C#
        public ClaimsIdentity GetClaimsIdentity(string name)
        {
            var claims = new List<Claim>();
            if (Permissions.Admins.Contains(name))
            {
                logger.LogInformation($"Adding claim 'admin' to {name}");

                claims.Add(new Claim(
                    ClaimTypes.Role, "admin"));
            }

            if (Permissions.LkgReleasers.ContainsKey(name))
            {
                logger.LogInformation($"Adding claim 'releaser' to {name}");

                claims.Add(new Claim(
                    ClaimTypes.Role, "releaser"));
            }

            return new ClaimsIdentity(claims);
        }
```

The permissions manager is a singleton that loads the hashset of usernames from a file at first call, but subsequent calls I'd assume would be quick (especially considering the set only contains 2-3 users). Instead, this setup appeared to bump response times to 200-300ms. 

We eventually solved the problem by switching to using policy require assertions:
```C#
            // convert claims to policies here (this enables us to filter access)
            services.AddAuthorization(options =>
            {
                options.AddPolicy("Administrators", policy => policy.RequireAssertion(
                    x => _permissionManager.Permissions.Admins.Contains(x.User.Identity.Name)));

                options.AddPolicy("Releasers", policy => policy.RequireAssertion(
                    x => _permissionManager.Permissions.Admins.Contains(x.User.Identity.Name) 
                        || _permissionManager.Permissions.LkgReleasers.ContainsKey(x.User.Identity.Name)));
            });
```

Switching to the require assertions appeared to drop response times down to ~100ms. 

### Further technical details
ASP.NET Core version 3.1

Dotnet info output:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

IDE: VS Enterprise 2019.

**Comment by Tratcher** [comment]
Can you create a github repo with a repro app?

Where did you measure the response latency? From the client? In the server logs?

Was the latency difference on Kestrel, IIS, or both?

AuthZ policies are probably a more efficient solution to this anyways as it doesn't require modifying the principal.

**Comment by iUnknwn** [comment]
Was seen on Kestrel, measured via the server Hosting.Diagnostics log entries. 

However, I just checked out the commit that was still working on claims transformation, right before the switch, and page response times are reasonable (65ms, not the 350ms I was seeing previously). I suspect something else might have been causing this issue that just happened coincided with the change.
