### ISSUE TITLE
[Blazor WASM] Conver all DLL names to lowercase - discussion

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/aspnetcore#20425]
Let's look at some files loaded by Blazor application:
- blazor.webassembly.js
- blazor.boot.json
- dotnet.wasm
- mscorlib.dll
- netstandard.dll

These are "good" names. Now a few "bad" names:
- MyProjectName.Client.dll
- MyProjectName.Shared.dll
- WebAssembly.Net.WebSockets.dll
- System.ComponentModel.DataAnnotations.dll
- Microsoft.AspNetCore.Components.Forms.dll

I think you should convert all file names to lowercase.

I believe that Blazor is (or will be in the near future) a perfect solution for public web applications with complex business logic. Public web applications have to be SEO friendly. When you think about SEO you have to think about lower/upper case letters. Here is a good article about this:
https://www.searchenginejournal.com/url-capitalization-seo/343369/

I have just created a prototype Blazor WASM ASP.NET Core hosted application with prerendering and custom `IRule` class which is used in `app.UseRewriter` to implement URL normalization and redirections. In this class all URLs are checked and (among other things) if there is at least one uppercase letter I change it to lowercase and server returns status 301 with correct normalized URL. Of course this is very inefficient when we have so many files with names like `Microsoft.AspNetCore.Components.Forms.dll`.

There are two solutions. I can change my class and ignore all files (URLs) in `_framework` folder or you can change all file names to lowercase. Second solution is in my opinion cleaner and we will have consistency in file names.

**One more note:** from the SEO point of view uppercase letters in DLL names are not important at all. I can ignore files requested form `_framework` folder and it is OK. Real question is: should we have consistency in file names?

**Comment by javiercn** [comment]
@Andrzej-W thanks for contacting us.

I don't think this is something that we plan to do out of the box, as it has the potential to cause issues in many places on the stack.

This is also something that you can do yourself in a post-build step following a similar approach as the one @SteveSandersonMS demonstrated for changing assembly extensions.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion! However, I agree with @javiercn. 

The casing of resources loaded by your site should not affect SEO.

.NET assembly file names conventionally involve upper and lower case characters, and we have no reason to change that.
