### ISSUE TITLE
[Blazor] [WASM] SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by IIStevowII** [dotnet/aspnetcore#20430]
After upgrading packages to the latest preview version I got the following error when trying to run the application in Firefox:

ReferenceError: SharedArrayBuffer is not defined        dotnet.3.2.0-preview4.20181.1.js:1:123642

Tried removing cache, local files etc. but that didn't matter.
When opening the application in Edge or Chrome it works fine.

I am developing on Windows 10 using Visual Studio 2019 Preview 2.0 (Version 16.6.0)
Firefox version is 74.0 (64-bits)

I did some investigation which packages seemed to cause the problem. It appears to be both Microsoft.AspNetCore.Components.WebAssembly **3.2.0-preview4.20181.13**
Microsoft.AspNetCore.Components.WebAssembly.Build **3.2.0-preview4.20181.13**
(my experience is that using different versions of these packages you're bound to get trouble anyway, so I kept those two versions in sync)

Downgrading the packages back to version *3.2.0-preview4.20181.2* solved the issue. Anything between those versions *(3.2.0-preview4.20181.13 and 3.2.0-preview4.20201.3)* give the same problem. 

### Packages installed in Client project
| Package | Version |
| --------- | ------- |
| Microsoft.AspNetCore.Components.Authorization | 3.1.3 |
| Microsoft.AspNetCore.Components.WebAssembly | 3.2.0-preview4.20181.13 |
| Microsoft.AspNetCore.Components.WebAssembly.Build | 3.2.0-preview4.20201.3 |
| Microsoft.AspNetCore.Components.WebAssembly.DevServer | 3.2.0-preview4.20201.3 |
| Microsoft.AspNetCore.SignalR.Client | 5.0.0-preview.4.20181.16 |
| Microsoft.Authentication.WebAssembly.Msal | 3.2.0-preview4.20201.3 |
| Radzen.Blazor | 2.4.5 |
| System.Net.Http.Json | 3.2.0-preview4.20177.1 |

### dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@IIStevowII thanks for contacting us.

I'm not sure how you are getting a preview4 version since we haven't released it. Are you manually updating to the nightly builds?

**Comment by IIStevowII** [comment]
Yeah, should have mentioned that. I'm doing a hobby project and added the nightly feeds in order to get the latest builds.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this, @IIStevowII!

This was fixed in https://github.com/mono/mono/pull/19420.
