### ISSUE TITLE
Additional step asks to confirm email address

### ISSUE THREAD

**Issue by TonyKenny666** [dotnet/aspnetcore#20445]
Implementing this in core 3.1 and an additional UI step is encountered when it asks the user to confirm the email address before they can log in and also requires email confirmation. This step is not shown in this page and there's no information about how to just use the facebook email address to create a new user without asking first. 
Regarding the email confirmation, i'd like to require this only for users registering directly on the site but not for those registering with facebook as one would assume that the email address they have there is already confirmed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
False alarm. This works as expected when setting `RequireConfirmedAccount = false`. You just need to supply a page to register. You don't need to confirm.

@HaoK  please close.

**Comment by HaoK** [comment]
No prob
