### ISSUE TITLE
[DataMember] and [IgnoreDataMember] not being respected on Blazor WebAssembly

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#20440]
I saw this issue #15698 about, but since it was old, I wonder what happened to it.
I am using `Blazor WebAssembly 3.2.0-preview3.20168.3` with `System.Text.Json 5.0.0-preview.1.20120.5` and noticed that `[DataMember]` and `[IgnoreDataMember]` aren't being respected. Is there a specific reason for that?
I saw on the old issue that a workaround was to not use the built-in serializer, is it still valid? What if I want to use `System.Text.Json`?

**Comment by javiercn** [comment]
@BrunoBlanes thanks for contacting us.

Blazor uses `System.Text.Json` which doesn't support `[Datamember]` and `[IgnoreDataMember]`. This is a feature System.Text.Json would need to add. (You can ask for it on the dotnet/runtime repo).
