### ISSUE TITLE
GetJsonAsync fails to deserialize Guid public field

### ISSUE THREAD

**Issue by chrisrharris** [dotnet/aspnetcore#20451]
### Describe the bug
HttpClientJsonExtensions.GetJsonAsync<t> fails to deserialize public member *fields* of type Guid.  but works for Guid *properties*.

### To Reproduce
Modify weather.json to include a field with Guid string.  
``` JSON
  {
    "date": "2018-05-06",
    "temperatureC": 1,
    "summary": "Freezing",
    "temperatureF": 33,
    "test": "a70b192a-b0f2-4183-8f05-64c69a404e0b"
  },
```
Modify WeatherForcast Model to include Guid field
``` C#
 public class WeatherForecast
    {
        public Guid Test;
        public DateTime Date { get; set; }
        public int TemperatureC { get; set; }
        public string Summary { get; set; }
        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
    }
}
```
Modify Fetch Data to display forecast.Test
``` HTML
<tbody>
            @foreach (var forecast in forecasts)
            {
                <tr>
                    <td>@forecast.Date.ToShortDateString()</td>
                    <td>@forecast.TemperatureC</td>
                    <td>@forecast.TemperatureF</td>
                    <td>@forecast.Summary</td>
                    <td>@forecast.Test</td>
                </tr>
            }
        </tbody>
````

![image](https://user-images.githubusercontent.com/2728915/78260081-8b271980-74cb-11ea-93fc-12914eaf12f5.png)

### Further technical details
- ASP.NET Core version: 3.1.3
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Windows 10 Visual Studio 2019 6.6 Preview 2.0

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/runtime/issues/876. You can use public properties or author a custom converter: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#public-and-non-public-fields

**Comment by chrisrharris** [comment]
I am also noticing this issue with Guid properties when accessing from API instead of a file.  Should I create a new issue?

**Comment by chrisrharris** [comment]
Correct, the issue I'm noticing is with the debugger.  For some reason it shows Guid as null, even though it has an underlying value.
