### ISSUE TITLE
Controller in a .dll

### ISSUE THREAD

**Issue by XxAndres1012xX** [dotnet/aspnetcore#20453]
Hi.
I am developing a project in ASP.net Core and I would like to know if I can put the Controller in a dll.

**Comment by javiercn** [comment]
@XxAndres1012xX thanks for contacting us.

Do you mean putting a controller in a class library and have the app pick it up automatically?

That's supported out of the box.

**Comment by XxAndres1012xX** [comment]
Yes.

**Comment by XxAndres1012xX** [comment]
I think I already solved my problem, I installed the necessary NuGgets in the dll.
Same thanks for the help.
