### ISSUE TITLE
Auto-rebuild not working

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/aspnetcore#20454]
In Blazor preview 3, the auto-rebuild feature is not working according to the following:

Auto-rebuild in Visual Studio
Visual Studio 2019 16.6 will watch for file changes in .cs and .razor files across the solution and automatically rebuild and restart the app so that the changes can be seen by simply refreshing the browser. This enables auto-rebuild support for Blazor WebAssembly projects and Razor Class Libraries. Instead of manually rebuilding and restarting the app when making code changes, just edit, save, and then refresh the browser.

I created a new Blazor ASP.NET Core hosted app, and ran it. I then changed some text in the Counter component, saved the component in Visual Studio (Preview 16.6) and refreshed Chrome but the updates to the text do not appear. I have the latest .NET Core SDK/runtime installed.

Is this an issue or am I doing this incorrrectly?

Thanks

**Comment by scottaddie** [comment]
@pranavkm Any ideas on this one?

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/20220. We'll use the other issue to track work here.
