### ISSUE TITLE
In Blazor Server 3.1, is it possible to move _Host.cshtml?

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#20455]
### Is your feature request related to a problem? Please describe.
We would like to organize code by Feature / Page.  Is it possible to move "\Pages\\_Host.cshtml" to "\Features\Host\\_Host.cshtml" ?

### Describe the solution you'd like
We would like to move "\Pages\\_Host.cshtml" to "\Features\Host\\_Host.cshtml"

### Additional context
Because we host our Blazor Server apps a sub sites in IIS onpremise, we already have the href of the base tag set:  `<base` href="/PickListWeb/" `/>`

**Comment by javiercn** [comment]
@roysurles thanks for contacting us.

It is doable I believe, `_Host.cshtml` is a plain razor page used as the entry point for the server-side blazor app.

@pranavkm can you answer this since you are more familiar with the area.

**Comment by SteveSandersonMS** [comment]
Yes, in your `Startup.cs`, change the call to `AddRazorPages` to pass a different root directory. Example:

```cs
            services.AddRazorPages(options =>
            {
                options.RootDirectory = "/something";
            });
```

**Comment by roysurles** [comment]
Worked exactly as described... thanks much!
