### ISSUE TITLE
Catch all route precedence incorrect

### ISSUE THREAD

**Issue by davidikin45** [dotnet/aspnetcore#20450]
```C#
endpoints.MapControllers();
endpoints.MapGet("{*path}", context =>
{
    context.Response.StatusCode = StatusCodes.Status404NotFound;
    return Task.CompletedTask;
});
```

Always returns 404 even for valid controller action route

**Comment by javiercn** [comment]
@davidikin45 thanks for contacting us.

I believe that's going on here is that attribute routes have a lower order than conventional routes, hence the order wins over the precedence.

/cc: @rynowak to confirm.

**Comment by rynowak** [comment]
@davidikin45 - do you have an example of another route you expect this to match? 

If you turn logging of `Microsoft` up to `Debug` what kind of log output do you see? Are the 404s coming from your code or from a failure to match anything?
