### ISSUE TITLE
Global roles vs context specific roles - is this the right approach?

### ISSUE THREAD

**Issue by sgabler-solytic** [dotnet/aspnetcore#20457]
I am trying to implement the following with Identity:
- a user must have exactly one "global role"
- a user can additionally have one role per Site (of which there are many)

Example:
User Frank's global role is "Regular User", but he is also the "Site Admin" for Sites with ID 5 and 6

This is somewhat incompatible with the table definitions provided by Identity, so I was thinking of introducing four new tables:
- GlobalRoles
- UserGlobalRoles (UserID, GlobalRoleId)
- SiteRoles
- UserSiteRoles (UserID, SiteId, SiteRoleId)

This would mean that the "Roles" table, which would usually be used by Identity, stays empty, and I would also not be able to use the userManager's `AddToRolesAsync`, for example, as this is tied to the Roles table (as far as I know)

Is this a recommended approach, or am I missing something fundamental?

**Comment by blowdart** [comment]
Why rules and not, say, claims, which would lend itself to this. Have a DefaultRole claim, and then multiple SiteAdmin claims per site ID?

**Comment by sgabler-solytic** [comment]
We need to be able to build efficient queries according to our business logic, so running everything via the "user claims" table seems a bit messy and inefficient, whereas having separate tables seems a bit clearer. But maybe I'm missing something?

In any case, thank you for you answer. It seems that my question is probably a bit too broad, so I'll close this issue for now.
