### ISSUE TITLE
Remove ServerSentEvents transport

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#20462]
We should look into removing the ServerSentEvents transport. Now that WebSockets is more common place, and LongPolling with HTTP/2 is also more common (and fast), SSE isn't needed. Plus SSE doesn't support binary.

We probably don't want to remove the implementation from the server, and we can't remove it from the negotiate response, otherwise old clients could break when used with a newer server.

We can remove the transport from all clients (TS and .NET).

Semi related: https://github.com/dotnet/aspnetcore/issues/12662

**Comment by davidfowl** [comment]
> We should look into removing the ServerSentEvents transport. Now that WebSockets is more common place, and LongPolling with HTTP/2 is also more common (and fast), SSE isn't needed. Plus SSE doesn't support binary.

We need to measure before we remove.

**Comment by davidfowl** [comment]
Nah
