### ISSUE TITLE
[Blazor][Wasm][Nigthly] Unexpected behavior with authentication using the MSAL package

### ISSUE THREAD

**Issue by IIStevowII** [dotnet/aspnetcore#20467]
This issue is reproduced on a project based on the following doc page:
[Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)

## Description
The latest version of the Microsoft.Authentication.WebAssembly.Msal package, version 3.2.0-preview4.20201.3, has some unexpected behavior with authentication. This package is retrieved from the nightly build feed, but I thought I'd report it here anyway so the issue is known. It does not seem to handle sessions correctly. The differences between repo steps 2 and 4 explain it best.

### 1) Create a new app like the docs state:
dotnet new blazorwasm -au IndividualB2C --aad-b2c-instance "{AAD B2C INSTANCE}" --api-client-id "{SERVER API APP CLIENT ID}" --app-id-uri "{APP ID URI}" --client-id "{CLIENT APP CLIENT ID}" --default-scope "{DEFAULT SCOPE}" --domain "{DOMAIN}" -ho -ssp "{SIGN UP OR SIGN IN POLICY}" --tenant-id "{TENANT ID}"

### 2) Verify the app works correctly
Run the application and verify you can login using B2C, open a new tab and use the same session etc. You can even close the debugging session and start it again, you will be automatically logged in.

### 3) Update Microsoft.Authentication.WebAssembly.Msal package
Update the Microsoft.Authentication.WebAssembly.Msal package for the Client project to version 3.2.0-preview4.20201.3

### 4) Verify the app doesn't work the same
As soon as you start a new debugging session you will notice you are not logged in. If you login, this works fine and it will show your name. If you open the same app in a different browser tab, you will not be logged in. If you close the debugging session and start a new one, you will also be NOT logged in. This behavior is different from step 2 (and in my opinion not correct)

The redirect behavior referenced in #19855 might be related to this issue. Atleast that was also behavior I encountered during this problem.

**Comment by javiercn** [comment]
@IIStevowII thanks for contacting us.

We recently updated the default settings to default to sessionStorage (to match msal.js defaults). If you want the old behavior back you can simply set the settings to "localStorage" in the cache settings.

That said, we plan to log you silently during app startup, so that'll bring back that behavior back.

**Comment by IIStevowII** [comment]
Thanks for the reply, didn't know that was standard behavior for MSAL.js
Found documentation about it after your advice: https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/msal-js-sso

Tried to change the cache location in the settings, and that indeed solved the problem. Thanks!
For anyone curious how that can be done, in the Program.cs of your client project:
```
services.AddMsalAuthentication(options =>
{
	options.ProviderOptions.Cache.CacheLocation = "localStorage";

	// Rest of the configuration
});
```
