### ISSUE TITLE
Simplify OpenApi_Add_URL_ActualResponse to avoid HTTP over the internet

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#20475]
This test uses HTTP to retrieve a swagger file from the internet.

It would be much better if we can just fake this with a custom `HttpMessageHandler` like: https://github.com/grpc/grpc-dotnet/blob/master/test/dotnet-grpc.Tests/TestBase.cs

This would allow us to execute the HTTP code path of the tool without the requirement to actually do network I/O. Adding this capability also opens the door to using the mock to do interesting things like test failure conditions.

**Comment by rynowak** [comment]
Discussed with the team, the decision is to delete the test.

**Comment by dougbu** [comment]
As in #20476
