### ISSUE TITLE
Disable FileSystemWatchers creation for subfolders

### ISSUE THREAD

**Issue by VladimirKhil** [dotnet/aspnetcore#20488]
### Is your feature request related to a problem? Please describe.
In the VS debugger I see that my ASP.NET Core 3.1 app running on Ubuntu 18.04 server creates two threads for FileSystemWatchers and one of them creates FSW on every app subfolder that I have. I have a lot of subfolders in my app so all these FSW eat a lot of CPU resources.

I have two configuration files with "reloadOnChange: true"option but I don't think this is the case.

### Describe the solution you'd like
Implement a way (API call or Host setting?) to disable FSW creation. My app files are not changed during app lifetime.

**Comment by javiercn** [comment]
@VladimirKhil thanks for contacting us. Can you give us more details about the folder that is affected by this? (Name within the solution at least) so that I can determine what area of the product it belongs to?

**Comment by VladimirKhil** [comment]
@javiercn this is wwwroot folder. It has thousands of subfolders in my case. The folders hierarchy looks like this: wwwroot -> (1 big folder and several small) -> (several hundreds subfolders in the big folder) -> (4 subfolders in each of them)

**Comment by javiercn** [comment]
@VladimirKhil thank. That helps. @pranavkm can this be the file watcher used by razor for runtime compilation? Can you provide instructions here on how to turn it off?

**Comment by javiercn** [comment]
Tentatively moving this to MVC to further look at the issue

**Comment by pranavkm** [comment]
`reloadOnChange: true` creates a file system watcher. Having it off should disable the watcher. Runtime compilation doesn't have a way to turn off the file system watching.

**Comment by Tratcher** [comment]
> `reloadOnChange: true` creates a file system watcher. Having it off should disable the watcher. Runtime compilation doesn't have a way to turn off the file system watching.

So you'd have to disable runtime compilation?

**Comment by pranavkm** [comment]
@Tratcher it's an optional component in 3.x, not on by default. Having runtime compilation indicates you're interested in watching for file changes at runtime so it doesn't make sense for it have a feature that effectively makes it useless. 

It's not clear that runtime compilation is at fault here. If it was, what might have been useful is if the file system entirely turned off watcher if it was configured to use polling. Right now, polling works in addition to the watcher, so it doesn't really help here.

**Comment by VladimirKhil** [comment]
I have disabled all "reloadOnChange: true" options in my code and still sometimes get some high FSW activity in PerfView:

![3](https://user-images.githubusercontent.com/12496778/78771325-acd74380-7998-11ea-90ac-bc57836305eb.PNG)
![2](https://user-images.githubusercontent.com/12496778/78771330-ae087080-7998-11ea-9ea2-9ae7805b0733.PNG)
![1](https://user-images.githubusercontent.com/12496778/78771331-ae087080-7998-11ea-9b78-a7b0c385f28f.PNG)

**Comment by Tratcher** [comment]
It should be possible to look at a memory dump and figure out what component is listening for file watcher callbacks.

**Comment by VladimirKhil** [comment]
I have a dump. It has some cyrillic letters but they are not really bothering :)

It seems that NLog and JsonConfigurationProvider do have FileSystemWatchers.

![1](https://user-images.githubusercontent.com/12496778/79007060-0db27780-7b63-11ea-8119-9f10a0c45054.PNG)
![2](https://user-images.githubusercontent.com/12496778/79007061-0e4b0e00-7b63-11ea-8a82-d8bf5645405b.PNG)
![3](https://user-images.githubusercontent.com/12496778/79007055-0c814a80-7b63-11ea-9d1e-8432e2195046.PNG)

**Comment by rynowak** [comment]
In case anyone was wondering btw, the `IFileProvider` implementation watches *everything* within its scope even if you're just interesting a single file or two (`appsettings.json`). 

The implementation kinda assumes that you are using globs or will use globs, which is why it watches everything rather than just the files you asked for.

On linux this sometimes results in exhausting the handles available to `epoll` (esp in containers).

@VladimirKhil - is there something about your scenario that's triggering a lot of file changes in `wwwroot/`? I would expect something is changing these files since you're seeing high CPU usage. Otherwise the filewatcher would just sit there idle.

**Comment by VladimirKhil** [comment]
> @VladimirKhil - is there something about your scenario that's triggering a lot of file changes in `wwwroot/`? I would expect something is changing these files since you're seeing high CPU usage. Otherwise the filewatcher would just sit there idle.

I had such activity earlier. Yes, there was a great count of files creation and deletion. Now I move that logic outside of `wwwroot` folder. I dont see high CPU activity now. I just only don't know why dotnet-trace catch FileSystemWatcher operations so often.

**Comment by pranavkm** [comment]
We're tracking follow up work for FSWs as part of https://github.com/dotnet/aspnetcore/issues/20733. Marking this as resolved since there isn't a specific issue to track for ASP.NET Core \ Mvc.
