### ISSUE TITLE
Calling Azure Table Function from blazor web assembly

### ISSUE THREAD

**Issue by intech-paul** [dotnet/aspnetcore#20482]
### Describe the bug
Cannot call table api functions; doesnt report a sensible error - An unhandled error has occurred. Reload

### To Reproduce

`@code {
    string error="Hello";
    string constring;

    void DoThis()
    {
        try
        {
            TableApi t = new TableApi();
            t.DoNothing();         //TESTING T LOADED
            t.GetConnectionString();  //TESTING T LOADED
            constring = t.constring;
            t.GetTable();           //actual Call TO table
        }
        catch (Exception ex)
        {
            error = ex.Message;
        }
    }
}
`

`namespace BlazorTableAPITest.Shared
{
    class LineData
    {
        public int index;
        public string label;
        public string units;
        public float value;
        public int status;
        public DateTime lastalarm;

        public LineData(int index, float value, int status)
        {
            this.index = index;
            this.status = status;
            this.value = value;
        }
    }

    class MyData
    {
        public string JobName;
        public string version;
        public string version_api;
        public DateTime time;
        public List<LineData> linedata;

        public MyData()
        {
            linedata = new List<LineData>();
        }
    }

    public class DataEntity : TableEntity
    {
        public DataEntity()
        {
        }
        public DataEntity(DateTime date)
        {
            PartitionKey = date.ToLongDateString();
            RowKey = string.Format("{0:d2}{1:d2}{2:d2}", date.Hour, date.Minute, date.Second);
        }
        public string jsondata { get; set; }
    }

    public class TableApi
    {

        public string reply;

        public void GetAllMessages(CloudTable table)
        {
            TableQuery<DataEntity> query = new TableQuery<DataEntity>();

            Console.WriteLine("GetAllMessages begin");
            foreach (DataEntity message in table.ExecuteQuery(query))
            {
                Console.WriteLine(message.jsondata);
            }
            Console.WriteLine("GetAllMessages ends");
        }

        public void DoNothing()
        { }

        public async void GetTable()
        {
            CloudTable table = await GetCloudTableDB("demoData");

            GetAllMessages(table);
        }

        public string constring;

        public void GetConnectionString()
        {
        constring= "DefaultEndpointsProtocol=https;AccountName=MicroScan;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw ==;TableEndpoint=https://localhost:8081";
        }

        public async Task<CloudTable> GetCloudTableDB(string tableName)
        {
            try
            {
                string storageConnectionString = "DefaultEndpointsProtocol=https;AccountName=MicroScan;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw ==;TableEndpoint=https://localhost:8081";
                CloudStorageAccount storageAccount;
                storageAccount = CloudStorageAccount.Parse(storageConnectionString);

                // Create a table client for interacting with the table service
                CloudTableClient tableClient = storageAccount.CreateCloudTableClient(new TableClientConfiguration());
                CloudTable table = tableClient.GetTableReference(tableName);

                await table.CreateIfNotExistsAsync();

                return table;
            }
        catch (Exception ex)
            {
                reply = ex.Message;
                return null;
            }
        }
    }
}
`

![image](https://user-images.githubusercontent.com/56703036/78314161-9eaeaf00-75b5-11ea-9ef7-4a5f5e344a75.png)

How do I put on the assertion in the build ?

This code works fine in a .net console app.

### Further technical details
Microsoft Visual Studio Professional 2019 Preview
Version 16.6.0 Preview 2.0

![image](https://user-images.githubusercontent.com/56703036/78314446-7bd0ca80-75b6-11ea-9192-907ab3333791.png)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@intech-paul thanks for contacting us.

This looks like the mono runtime itself is crashing. @SteveSandersonMS thoughts?

@intech-paul can you create a minimal repro project that will help us investigate this issue?

**Comment by SteveSandersonMS** [comment]
@javiercn Yes. It might be that the table client does something that's not supportible in a browser environment, though looking at its code in ILSpy, it seems only to use HttpClient for transport so it seems like it should work. Regardless, the runtime would ideally provide a better error message than this, so it is worth reporting upstream.

It looks to me like the code sample posted by @intech-paul is a pretty good repro, so maybe that's all the info we need.

**Comment by intech-paul** [comment]
I've uploaded a sample to 
https://github.com/intech-paul/BlazorAzureCosmosTest
(its the first time ive done this).

dependencies now...

![image](https://user-images.githubusercontent.com/56703036/78831348-959e6180-7a3d-11ea-94fb-e0e4c4c5e2b4.png)

I'm also seeing a similar sort of thing with influxdb clientapi library too, but it that case it goes into and endless loop in blazor executing the same code.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19497
