### ISSUE TITLE
Replace pinned extensions dependencies

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#20485]
Followup to https://github.com/dotnet/aspnetcore/pull/20484. Figure out what to do with the following packages in aspnetcore be it remove, replace with another API/Analyzer or migrate the code from extensions to aspnetcore:

Microsoft.AspNetCore.Analyzer.Testing
Internal.AspNetCore.Analyzers
Microsoft.Extensions.DiagnosticAdapter

**Comment by JunTaoLuo** [comment]
Only Microsoft.Extensions.DiagnosticAdapter remains

**Comment by dougbu** [comment]
Might be done 😀

**Comment by JunTaoLuo** [comment]
Turns out we still use Microsoft.Extensions.DiagnosticAdapter in samples and tests https://github.com/dotnet/aspnetcore/search?p=1&q=diagnosticadapter. We should remove the use of this deprecated package.
