### ISSUE TITLE
Blazor WebAssembly always overwrites web.config on IIS publish

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#20490]
When deploying a standalone Blazor WebAssembly app to IIS it is useful to customise the web.config with items such as the environment to run in, for example adding the following to indicate the QA environment:
```
<httpProtocol>
<customHeaders>
  <add name="Blazor-Environment" value="QA" />
  </customHeaders>
</httpProtocol>
```

Currently (WebAssembly preview 3) this cannot be done since the publish to IIS always overwrites the web config by copying the ```Standalone.Web.Config``` from the sdk to the target folder, ignoring any existing web.config in the project.

Ideally the IIS publish should:
* Honour any existing web.config present in the project and not overwrite it; and/or
* Allow normal web.config transformations to be applied so that the base "Standalone.Web.Config" can be used with specific transforms for specific deployment profiles / project configurations.

**Comment by guardrex** [comment]
Recommend adopting the same behavior [i.e., honor the dev's `<IsWebConfigTransformDisabled>` (or passed value via CLI)].

For those needing a workaround, use ...

```xml
<Target Name="CopyWebConfigOnPublish" AfterTargets="Publish">
  <Copy SourceFiles="web.config" DestinationFolder="$(PublishDir)" />
</Target>
```

**Comment by captainsafia** [comment]
Marking as done since https://github.com/dotnet/aspnetcore/pull/20800 is merged.
