### ISSUE TITLE
Incorrect IdentityError description 

### ISSUE THREAD

**Issue by badamsdev** [dotnet/aspnetcore#20496]
Line [137](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/Resources.resx#L137) & [165](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/Resources.resx#L165) in [src/Identity/Extensions.Core/src/Resources.resx](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/Resources.resx) should be "Username" not "User name" as it's the users unique login id, not the users name.

```
<data name="DuplicateUserName" xml:space="preserve">
    <value>User name '{0}' is already taken.</value>
    <comment>Error for duplicate user names</comment>
</data>
```

```
<data name="InvalidUserName" xml:space="preserve">
    <value>User name '{0}' is invalid, can only contain letters or digits.</value>
    <comment>User names can only contain letters or digits</comment>
</data>
```

**Comment by blowdart** [comment]
We'll happily accept a PR for this :)

**Comment by fgiuliani** [comment]
@blowdart can I take a look to this?

**Comment by blowdart** [comment]
@fgiuliani You certainly can :)

**Comment by fgiuliani** [comment]
@blowdart done!
https://github.com/dotnet/aspnetcore/pull/21237

**Comment by badamsdev** [comment]
@fgiuliani  and @blowdart 
I already submitted a fix: [https://github.com/dotnet/aspnetcore/pull/20497](https://github.com/dotnet/aspnetcore/pull/20497)
Review required...

**Comment by blowdart** [comment]
Oops I missed that
