### ISSUE TITLE
How to add a custom build task to a Blazor WebAssembly project?

### ISSUE THREAD

**Issue by frankabbruzzese** [dotnet/aspnetcore#20491]
I would like to add a custom build task when a Blazor project is compiled in release/debug configuration BEFORE files are packed in the **dist** foder, because at that time it is too late for performing transformations such as dll merging and resources processing. Is this possible? How? I tried adding custom tasks, but they appear to execute AFTER the **dist** folder has been packed.

**Comment by javiercn** [comment]
@frankabbruzzese thanks for contacting us.

We are not sure what you are trying to accomplish, but I would say that the Blazor pipeline is pretty intricate and there is a good chance to break things if you just "attach" to it in the middle and start making changes.

Ideally, any transformation that happens should be after the app has been built/published.

If you give us more details on specific things you are trying to accomplish we can possibly give you alternative ways of achieving the same result.

**Comment by frankabbruzzese** [comment]
My main goal is to merge the main assembly with some library dlls. I can do it also after publication, but then I have to update the list of files in blazor.boot.json. Moreover, while updating blazor.boot.json should be quite easy, I am worried that the more aggressive linker policy and dll compression announced for the 3.2 final, might make this processing very hard if done after all assets have been prepared in the dist folder.

**Comment by javiercn** [comment]
@frankabbruzzese thanks for the details. I don't think that type of transformation is something we plan to support in the near future. We ourselves considered things like ILMerge in the past but the reality of it is that it has significant drawbacks like for example breaking assembly identity.

As I said, we don't plan to support these types of things within the build pipeline, as it comes as a non trivial support cost for us and we don't see that much value on it.
