### ISSUE TITLE
WASM 3.2 pre 3 template - When deleting an account user stays logged in until browser refresh

### ISSUE THREAD

**Issue by ar0311** [dotnet/aspnetcore#20492]
### Describe the bug
When deleting your account using the latest preview of Blazor Wasm (Hosted with Individual auth) after redirect you are still showing as logged in. After a browser refresh you are correctly showing as logged out.

### To Reproduce

dotnet new blazorwasm -au Individual --hosted

Register > Confirm > Login > Play Around > Click username > Click Personal Data > Click Delete Data

You are returned to app but the header bar still shows your user name as being logged in.

### Further technical details

Template version Blazor 3.2 preview 3
SDK 3.1.201

**Comment by javiercn** [comment]
@ar0311 thanks for contacting us.

This is a known issue and will be fixed in the next preview.

**Comment by ar0311** [comment]
Great, thanks!
