### ISSUE TITLE
netcore RedirectToActionPermanent  Can not jump

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20509]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/963966/netcore-redirecttoactionpermanent-can-not-jump.html)._

---
我新开的项目，RedirectToAction是可以在控制器之间跳转。 但是，有时候就是不能跳转。 请问我的是什么问题呢？代码如下：
  public async Task<ActionResult<ImportInfoSet>> PileAction(int id)
        {
            var impinfo =await _context. ImportInfoSet
                . Include(n=>n.ArticleSet)
                . FirstAsync(r => r.Id == id);
            return impinfo;
        }    

//理盘时，获取条码记录和位置
        [HttpGet("ArrangeCode/{id}/{storage}/{x}/{y}/{z}")]
        public async Task<ActionResult<ArticleSet>> FromBarCode(string id,string storage, double x, double y, double z)
        {
            var Cstorage = _context. SceneDiagramSet.Where(r => r.StorageName == storage)
                . Include(r=>r.ShelfSet)
                . First();
            if (Cstorage == null) return Content("请确定仓库。 ");
            var codes = id. Split('_');
            bool isDidui = codes[1]. ToLower() == "CODABAR". ToLower() || codes[1]=="2";
            //计算在货架的位置。
            if (isDidui)
            {
                var Vshelf = Cstorage.ShelfSet.Where(w => w.Type=="地堆" && w.SceneDiagramId == Cstorage.Id). FirstOrDefault();
                if (Vshelf == null)
                {
                    Vshelf = new ShelfSet { Type = "地堆", SceneDiagramId = Cstorage.Id, Name = "通用地堆" };
                }
                try
                {
                    
return RedirectToActionPermanent("PileAction", new { Id = codes[0] });
                }
                catch (Exception ex)

---
#### jinlinshao on 3/26/2020, 01:28 AM: 

我的想法是，跳转到别的action 返回新的类型。
#### jinlinshao on 3/26/2020, 02:25 AM: 

 另外，这是一个apiController<br>[Route(&quot;api/[controller]&quot;)]<br>    [ApiController]
#### Visual Studio Feedback System on 3/26/2020, 02:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### jinlinshao on 3/26/2020, 09:59 PM: 

经过试验，我新建一个控制器，如果用http模板，就会出错，如这样[httpget(&quot;ddd/{id}/{ji}/{x}&quot;]路由就会失效。没有参数的[httpget]就可以。

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
