### ISSUE TITLE
Compile issue with Microsoft.Extensions.Logging.LoggingBuilderExtensions.AddProvider

### ISSUE THREAD

**Issue by srulandhs** [dotnet/aspnetcore#20501]
Normally, I would do the following

```c#
using Microsoft.Extensions.Logging;
  :
ILoggingBuilder builder
builder.AddProvider(...)
```
this seems to work just fine. However, I recently encounter an issue where there was a conflict between Microsoft.Extensions.Logging and another third party namespace. Basically, both had a definitions for the LogLevel type.

To address this, I attempted to change the above code to:

```c#
using Microsoft.Extensions.Logging;
  :
Microsoft.Extensions.Logging.ILoggingBuilder builder
Microsoft.Extensions.Logging.LoggingBuilderExtensions.AddProvider(builder, ...)
```
This resulted in the following compiler error which I was unable to find a way to address.

Error
CS0433
The type 'LoggingBuilderExtensions' exists in both 'Microsoft.Extensions.Logging.Configuration, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.Extensions.Logging, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	

I can work around this by fully qualifying the third party type, but this still seems like an issue.

### Further technical details
SDK:   3.1.100 (force via global.json)
OS:    win 10/VS2019 (16.5.2, details attached)

[vs.info.txt.txt](https://github.com/dotnet/aspnetcore/files/4427539/vs.info.txt.txt)
[dotnet.info.txt](https://github.com/dotnet/aspnetcore/files/4427511/dotnet.info.txt)

**Comment by javiercn** [comment]
@srulandhs thanks for contacting us.

You should be able to get around this by using a type alias
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive

**Comment by davidfowl** [comment]
Can you provide a project that reproduces the problems

**Comment by BrennanConroy** [comment]
You can setup type aliasing in your csproj to also workaround the issue https://github.com/grpc/grpc-dotnet/issues/329#issuecomment-502309756

@maryamariyan Is this something we would be interested in fixing in 6.0? It's technically breaking if we change the extension method class name.

**Comment by maryamariyan** [comment]
seems related to https://github.com/dotnet/runtime/issues/33998

**Comment by BrennanConroy** [comment]
Ah yeah it does, thanks!
