### ISSUE TITLE
Edit Profile functionality stops working after introducing OpenIdConnectEvents in an Asp.Net Core 3.1 Blazor Server app using Azure B2C

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#20503]
I have an Asp.Net Core 3.1 Blazor server application using Azure AD B2C auth, which works fine including SignIn/Singup and Profile Edit. The relevant code in Startup.cs looks like this:

``` C#
services.AddAuthentication(AzureADB2CDefaults.OpenIdScheme)
            .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));
```

However, when I introduce the code below to intercept OnTokenValidated event, the OnTokenValidated fires when I click on SignIn; however, after signing in, when I try to edit profile, I see that OnTokenValidated still fires, and page tries to go to /AzureADB2c/Account/EditProfile but immediately returns back to Home page, without going to the Edit Profile page. I have verified that if I use any OpenIdEvent, even without any body, the current user cannot edit profile. Here is the final code in ConfigureServices that has this issue:

``` C#
services.AddAuthentication(AzureADB2CDefaults.OpenIdScheme)
            .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));

        //The code below causes Profile Editing to stop working. When logged in user clicks on 
        //Edit Profile link, there is a temporary redirect, but the user is sent back to home page, instead of Edit Profile page on Azure B2c site     
        services.Configure<OpenIdConnectOptions>(AzureADB2CDefaults.OpenIdScheme, options =>
        {
            options.Events = new OpenIdConnectEvents
            {
                OnTokenValidated = async ctx =>
                {

                }
            };
        });
```
### Further technical details
- ASP.NET Core version : 3.1.300-preview-015048
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Microsoft Visual Studio Professional 2019 Preview Version 16.6.0 Preview 2.0

**Comment by Tratcher** [comment]
The trouble is probably that B2C was already using those events you replaced.
https://github.com/dotnet/aspnetcore/blob/0d9f5e053f9f252e5da24173d24688bf9968f389/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/AzureADB2COpenIdConnectOptionsConfiguration.cs#L42-L47
Rather than making a new events class, can you re-use the existing one?
