### ISSUE TITLE
The second added auth service, doesn't get automatically the Signing keys for validate incoming JWT. 

### ISSUE THREAD

**Issue by kim3ds** [dotnet/aspnetcore#20502]
I need to authenticate against multiple client ids. One is Main.ClientId. Another one is in IncomingClients[0].ClientId. 
Signing keys for auth endpoint are specified to validate incoming JWT token. But they are constantly changing, and they could be automatically fetched by MS .NET libraries. and they are, but only when auth client is the only client I validate. 
I need to find a way how to validate multiple client ids without configuring signing keys.

**Comment by kim3ds** [comment]
https://stackoverflow.com/questions/60991115/asp-net-core-how-to-setup-2-publishers-of-jwt-token

**Comment by Tratcher** [comment]
What code do you have so far? Two calls to AddJwtBearer?

One of the trickiest parts is knowing which validator to use for which token. One option is to try both and catch any errors.
```
app.Use(async (context, next) => 
{
  try
  {
    var result1 = await context.AuthenticateAsync("bearer1");
  }
  catch (Exception)
  {
    var result2 = await context.AuthenticateAsync("bearer2");
  }
  // ...
  await next();
}
```

**Comment by kim3ds** [comment]
How to accept and validate JWT tokens from two different authorities using the same schema Bearer?
 
Requests with headers like:
Authorization: Bearer <jwt token with aud = client1>
Authorization: Bearer <jwt token with aud = client2>
 
I want to validate and accept both.
 
If I setup them like that:
 
var authBuilder = services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme);
authBuilder.AddJwtBearer(options =>
{
    options.Audience = clientId1;
    options.Authority = authority1;
});
token from one authority is good
I can setup authority2 the same way
 
I can setup BOTH but in that case I have to pull signing keys manually using /.well-known/openid-configuration and configure validation like that:
 

var authBuilder = services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme);
authBuilder.AddJwtBearer(options =>
{
    foreach (var item in authentication.IncomingClients)
        options.SecurityTokenValidators.Add(new CustomJwtTokenHandler(client2, authority2, signingKeys));

 

    options.Audience = client1;
    options.Authority = authority1;
});
 
 

public class CustomJwtTokenHandler : JwtSecurityTokenHandler
{
    private readonly string extraAudience;
    private readonly string extraIssuer;
    private readonly SecurityKey[] extraKeys;

 

    public CustomJwtTokenHandler(string extraAudience, string extraIssuer, IEnumerable<SecurityKey> extraKeys)
    {
        this.extraAudience = extraAudience;
        this.extraIssuer = extraIssuer;
        this.extraKeys = extraKeys.ToArray();
    }

 

    public override ClaimsPrincipal ValidateToken(string securityToken, TokenValidationParameters validationParameters, out SecurityToken validatedToken)
    {
        validationParameters.ValidAudience = extraAudience;
        validationParameters.ValidIssuer = extraIssuer;
        // TODO: force ASP .NET facilities fetch keys automatically from .well-known/openid-configuration and then from jwks_uri parameter
        validationParameters.IssuerSigningKeys = extraKeys;
        return base.ValidateToken(securityToken, validationParameters, out validatedToken);
    }
}
 
 
but is there a way to set it up without specifying keys manually? I see in .NET Core library code which pulls them automatically. I would like to re-use that functionality (which actually works for authority1!!!)

**Comment by kim3ds** [comment]
@Tratcher 
I have this code:

   ```
 services.AddAuthentication()
.AddJwtBearer("JwtBearer_1", options =>
{
    options.Audience = authentication.Main.ClientId;
    options.Authority = authentication.Main.Authority; // auth service_1 Url
    options.SaveToken = true;
    options.Events = GetJwtBearerEvents();
})
.AddJwtBearer("JwtBearer_2", options =>
{
    options.Audience = authentication.IncomingClients[0].ClientId;
    options.Authority = authentication.IncomingClients[0].Authority; // auth service_2 Url
    options.SaveToken = true;
    options.Events = GetJwtBearerEvents();
});

services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .AddAuthenticationSchemes("JwtBearer_1", "JwtBearer_2")
        .Build();
});
```
But I get the error: "No authenticationScheme was specified, and there was no DefaultChallengeScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action configureOptions)." What I need to do yet?
