### ISSUE TITLE
Compiling Blazor client fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20508]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/965848/compiling-blazor-client-fails.html)._

---
Trying to compile a blazor client side project (with core server and shared lib) fails but I don't understand how to fix this. (it would be nice with a bit more help along the way :) )

Compiler output:
>1>------ Build started: Project: DynamicNoiseMap.Client, Configuration: Debug Any CPU ------
>1>myBlazor.Client -> C:\Users\xxx\source\repos\BlazorTest\myBlazor\Client\bin\Debug\netstandard2.1\myBlazor.Client.dll
>1>Fatal error in Mono CIL Linker
>1>C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(259,5): error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.ComponentModel.ICustomTypeDescriptor System.Data.Entity.ModelConfiguration.Utilities.AttributeProvider::GetTypeDescriptor(System.Type)' in assembly: 'EntityFramework.dll'
>1> ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void System.ComponentModel.DataAnnotations.AssociatedMetadataTypeTypeDescriptionProvider::.ctor(System.Type)
>1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
>1>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
>1>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
>1>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
>1>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
>1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
>1>   --- End of inner exception stack trace ---
>1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
>1>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
>1>   at Mono.Linker.Steps.MarkStep.Process()
>1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
>1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
>1>   at Mono.Linker.Pipeline.Process(LinkContext context)
>1>   at Mono.Linker.Driver.Run(ILogger customLogger)
>1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
>1>   at Mono.Linker.Driver.Main(String[] args)
>1>C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(259,5): error : ILLink failed with exit code -532462766.
>1>Done building project "DynamicNoiseMap.Client.csproj" -- FAILED.
>2>------ Build started: Project: DynamicNoiseMap.Server, Configuration: Debug Any CPU ------
>2>DynamicNoiseMap.Server -> C:\Users\xxx\source\repos\BlazorTest\myBlazor\Server\bin\Debug\netcoreapp3.1\myBlazor.Server.dll
>========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

---
#### Visual Studio Feedback System on 3/27/2020, 02:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19431
