### ISSUE TITLE
Blazor Webassembly Hosted App with Individual Accounts Authentication throws error on debuging if Solution has spaces in Name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20512]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/971270/blazor-webassembly-hosted-app-with-individual-acco.html)._

---
I created a Blazor Webassembly app with hosted checked and changed authentication to Individual accounts. The name for the Solution was "Blazor Webassembly Hosted Test". When I first run the app I got an exception that told me that there was no assembly found with name "Blazor Webassembly Hosted Test.Client". The exception appeared in the configuration controller for the authorization endpoint. Did remember in the documentation that the client app after prerender connencts with hosting server and if you have authentication configured it will try to connect at the "_configuration/{client-id}" endpoint and the client-id by convention is the assembly name of the project  (which is based on solution name). I created another Solution but with "Blazor_Webassembly_Hosted_Test3" name and when I run the app I didn't get any exception which kinda confirms my presumtion that the client looks for the assembly name without spaces because in urls you dont have spaces except with encodings. Hopefully this issue gets resolved by the time Blazor Webassembly switches from preview to stable release.

---
#### Visual Studio Feedback System on 3/31/2020, 07:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@vsfeedback thanks for contacting us. We'll take a look at this issue and get back to you.
