### ISSUE TITLE
Is setting BlazorWebAssemblyEnableLinking to 'true' required? 

### ISSUE THREAD

**Issue by catlan** [dotnet/aspnetcore#20517]
[EDIT by @guardrex to fix the character encoding]

Is it possible that `<MonoLinkerI18NAssemblies>all</MonoLinkerI18NAssemblies>` is not taking into account when the linker is disabled? For development builds this seems to be the default since 3.2.0 Preview 2.

This is working for me:

```xml
<PropertyGroup>
  <BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>
  <MonoLinkerI18NAssemblies>all</MonoLinkerI18NAssemblies>
</PropertyGroup>
```

See also https://github.com/dotnet/AspNetCore.Docs/issues/15679

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861a95e9-b329-6408-3127-9806c50a00dc
* Version Independent ID: f1bb4fd6-29cd-4e11-e912-9c86b351bc31
* Content: [Configure the Linker for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/blazor/configure-linker.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/configure-linker.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @catlan.
That setting is actually used only by the linker. When linker is disabled, the effect is similar as having the setting set to `all` for linker-enabled scenario.
Is this not what you're observing?

**Comment by catlan** [comment]
No, what I'm observing is similar as having the setting set to `none`. 

Is there any debug information I can provide?

**Comment by mkArtakMSFT** [comment]
We will need a repro project, unless you experience this with a newly created project.

**Comment by catlan** [comment]
A newly created project adding these lines should do the trick:

```
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var test = Encoding.GetEncoding("Windows-1252");
```

Results in System.NotSupportedException: Encoding 1252 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
