### ISSUE TITLE
blazor successful authentication causes browser crash in VS 16.6.0 Preview 2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20511]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/975717/blazor-successful-authentication-causes-browser-cr.html)._

---
[regression] [worked-in:16.5.2]
I have a blazor webassembly application (preview 3), using AAD authentication.  In VS 16.6.2 Preview 2, if I authenticate successfully, the browser crashes.  I am using the current GA version of Edge Chromimum browser.  I have repeated this with IIS Express and Cassini, and it occurs identically.

The problem started when I changed the service principle in Azure to require user assignment.  Before that, it allowed successful authentications.

The problem does not occur in the non preview Visual Studio

---
#### Visual Studio Feedback System on 4/2/2020, 07:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@javier, can you please look into this? Thanks!

**Comment by javiercn** [comment]
@SteveSandersonMS closing this since it is the known debugger issue. Can you link that issue here? I'm not able to find it.
