### ISSUE TITLE
API ref docs for RemoteAuthenticatorView should document the supported set of actions

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#20510]
Since `RemoteAuthenticatorView.Action` is just a string, it's not clear what the supported set of actions are. It would be useful to document these in the API refs for this type.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/Models/RemoteAuthenticationActions.cs

https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L23-L26

It's pointed out in the xml comments, do we need something else? If so, can you file a doc bug and have it be filled with the content from the xml docs?

**Comment by danroth27** [comment]
The XML comment looks good to me. Any idea why this content isn't showing up in IntelliSense in VS?

![image](https://user-images.githubusercontent.com/1874516/78401175-001e5000-75ad-11ea-825a-6cdc7ef496e4.png)

I don't see the XML doc files in the NuGet package contents.

**Comment by danroth27** [comment]
Looks like all of our packages are missing XML doc files. I chatted with @mkArtakMSFT and we'll track fixing this with https://github.com/dotnet/aspnetcore/issues/18427.
