### ISSUE TITLE
BlazorServerTemplateWorks_IndividualAuth is hanging in CI builds

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#20520]
BlazorServerTemplateWorks_IndividualAuth is already quarantined, but it's also being explicitly skipped because it's causing hangs in the CI.

Ex: https://dev.azure.com/dnceng/internal/_build/results?buildId=587056&view=results

**Comment by mkArtakMSFT** [comment]
Closing as there was some work done here by @pranavkm to reduce the flakiness.
