### ISSUE TITLE
Area scaffolding is not working in .net core 5 preview 2

### ISSUE THREAD

**Issue by bhrugen** [dotnet/aspnetcore#20528]
### Describe the bug
Cannot scaffold area in .net core 5 preview 2

### To Reproduce
Create new project with individual user account and try to scaffold a new area.

### Further technical details
- ASP.NET Core version .NET 5 preview 2

**Comment by javiercn** [comment]
@bhrugen thanks for contacting us.

@vijayrkn this is a tooling issue, can you have someone take a look?

**Comment by vijayrkn** [comment]
We haven’t added support for any scaffolders in Net 5.0 preview2. All scaffolders will be available in Net 5.0 preview3. 

/cc @deepchoudhery

**Comment by vijayrkn** [comment]
This support is already available for 5.0 preview 3. Closing
