### ISSUE TITLE
Blazor - Static asserts from Razor Class Library can't be loaded when library project isn't in same solution 

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#20535]
### Describe the bug

I am trying to consume Razor Class Library in blazor app but static assets (e.g. js files) can't be loaded at run-time, library is separated project, not in same solution.
If I add library to same solution it is working.
I want library to be separated because it will be consumed by several apps.

### To Reproduce
1. Create Blazor webassembly standalone app;
2. Create Razor Class Library as separated solution;
3. Reference library to blazor app;
4. Add script to index.html;

```
    <script src="_content/RazorClassLibrary1/exampleJsInterop.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
```
5. Add using in _imports.razor.
`@using RazorClassLibrary1`

**Comment by javiercn** [comment]
@Lupusa87 thanks for contacting us.

Visual studio has no way to know about the project if it is not part of the solution I believe. You can add your project to multiple different solutions. That's the way to do it.

**Comment by Lupusa87** [comment]
@javiercn Thank you, it helped.
