### ISSUE TITLE
Blazor Authentication Additional Access Tokens cannot be retrieved

### ISSUE THREAD

**Issue by snapfisher** [dotnet/aspnetcore#20539]
### Describe the bug
Following the documentation in 

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1

Additional AAD tokens cannot be retrieved using Blazor Preview 3.2.0 3

### To Reproduce

I my main:

builder.Services.AddMsalAuthentication(options =>
            {
                var authentication = options.ProviderOptions.Authentication;
                authentication.Authority = "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011xxxx";
                authentication.ClientId = "93d053a6-718a-4219-9674-cc5c5adfxxxx";
                options.ProviderOptions.DefaultAccessTokenScopes.Add("93d053a6-718a-4219-9674-cc5c5adfxxxx/.default");
                options.ProviderOptions.AdditionalScopesToConsent.Add("https://management.azure.com/user_impression");
            });

Where the 93..Guid is my service principal GUID which I am using for application log in (which does work).

Then in the C# portion of index.razor, I injected 

@inject Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider AuthenticationService

And then call

        var tokenResult = await AuthenticationService.RequestAccessToken(
             new AccessTokenRequestOptions
             {
                 Scopes = new[] { "https://management.azure.com/user_impression" }
             });

        if (tokenResult.TryGetToken(out var token))
            {            
                functionkey = token.Value.ToString();
            }

token value throws an error, Object reference is not set to an instance of an object.  This occurs when accessing the value of the token.

Note that I have checked that https://management.azure.com/user_impression is set as a permission on my service principal in the azure portal.  I have also tried it with https://graph.microsoft.com/User.Read which is also on my service principal and is the exact sample as shown in the documentation.

Note also, that if instead I request the token as:

Scopes = new[] { "93d053a6-718a-4219-9674-cc5c5adfxxxx/.default" }

I do get a valid token back, however, it is, of course, unauthorized when I try to use it to call the management api (as expected)

### Further technical details

3.1.300-preview-015048

PS C:\Users\pfisher> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

I'm using the preview .net core version, but the GA visual studio 16.5.2 due to a different issue (which has already been reported)

**Comment by snapfisher** [comment]
I realized I had a typo in the above description.  The scope is "user_impersonation", not "user_impression", but you still get the same behavior as described.

**Comment by snapfisher** [comment]
This should possibly be a separate issue, but in trying to work around the problem, I noticed that this will not work either.

            string keyVaultName = "https://xxx.vault.azure.net";
            var client = new SecretClient(new Uri(keyVaultName), new ClientSecretCredential("72f988bf-86f1-41af-91ab-2d7cd011dxxx", "93d053a6-718a-4219-9674-cc5c5adfaxxx", "xxx"));
            KeyVaultSecret secretValue = await client.GetSecretAsync("xxx");
            functionkey = secretValue.Value;

This exact code works if copied into a .net console application.  I realize it's short circuiting all of the built in authentication, but I cannot see any valid reason it would not work.  It does not.  I can file this as a separate issue if folks think it's unrelated.  The error retrieved is "Failed to Fetch".

**Comment by javiercn** [comment]
@snapfisher blazor webassembly runs in the context of the browser, so i don't think `        var client = new SecretClient(new Uri(keyVaultName), new ClientSecretCredential("72f988bf-86f1-41af-91ab-2d7cd011dxxx", "93d053a6-718a-4219-9674-cc5c5adfaxxx", "xxx"));` and so on is going to work.

**Comment by javiercn** [comment]
@snapfisher

> Where the 93..Guid is my service principal GUID which I am using for application log in (which does work).

I'm not sure this is supported by msal.js even if it just happens to work. What I can say is that this is not an scenario we currently support, you need an app that is properly registered to use our package, as that's the scenario we are targetting.

**Comment by snapfisher** [comment]
I understand.  These were just two things I tried to work around the issue. 

Although, I don't actually understand why the browser can't generate a ClientSecretCredential given all the pieces, but if it can't, it can't.  Once the main issue is resolved, resolving this would not be important.  Thx.

**Comment by snapfisher** [comment]
You got me curious.  SO I went into the Azure portal and created a scope, and then changed the call to be this:

options.ProviderOptions.DefaultAccessTokenScopes.Add("api://93d053a6-718a-4219-9674-cc5c5adfaac5/Profile.Read");

I really think these are the same thing, I just put a V2 scope name on the same SP -- but ignoring that, I was able to log in like this, identical as before.  Unfortunately, I still can't access the other token.  The problem is still there.  So this is not the cause of the reported issue..

It was worth trying.....

**Comment by guardrex** [comment]
@snapfisher ... I'm working on that doc node almost daily, and there are some very rough spots right now during preview. For example, https://github.com/dotnet/AspNetCore.Docs/issues/17304 ...  **TL;DR** ... our portals are different, our portal scope configs are different, and our app `DefaultAccessTokenScopes` configs are different.

The reason that you see the `{SERVER API APP CLIENT ID}` in the scope URI is that it's an Azure portal *default value*. Now that I've had some experience and feedback from readers, I don't like the `{SERVER API APP CLIENT ID}` in the example. I think it's ok to just say `{SCOPE URI}` for the entire value. However, the topic still has to say that:
  * The portal may default part of the URI to the API Client Id.
  * The scheme might not be acceptable.

When you said ...

>  I just put a V2 scope name on the same SP

I assume you mean that you added a `v2.0` segment. What did you do exactly? **_Now, you have me curious_** :smile: if the delta that I'm seeing in the behavior of the supplied value is due to something like that.

**Comment by snapfisher** [comment]
Originally, I just used the SP appID with the .default scope, which “should be used for any MSAL v1 endpoint, which is also supported by MSAL in v2”.  This is documented a bit.  You can find it here:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-v1-app-scopes

Specifically:

[cid:image001.png@01D60D9C.907479A0]

However, for what I did for the V2 segment.  I went to the “Expose an API” page from the App Registrations section on the portal, to expose my SP as an API.  This gave me the “V2 API Scope”.

[cid:image003.png@01D60D9D.3E2643D0]



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
