### ISSUE TITLE
MVC like Html Helpers using RenderFragment?

### ISSUE THREAD

**Issue by robertjak** [dotnet/aspnetcore#20538]
How can I use RenderFragment in a method to generate a component dynamically in MVC  Html Helpers style (Blazor)? There was a hint here #16112 by @SteveSandersonMS but unfortunately without example.

What I do is:
> 
    public static RenderFragment RenderName(string name)
    { 
        return __builder => {
             <p>Name: <strong>@name</strong></p>         
         }; 
    }
and then calling it

> 
    @RenderName("Robert")

It works perfectly but I fear that you might remove this in next versions, it must be a hack, the parameter must be called exactly __builder otherwise I get compilation errors. I know I could write the RenderFragment code completely dynamically like in generated code behind, but it would be a nightmare to maintain - I need clean and colored Razor syntax.

BTW: why do I need this feature so badly? As an experienced application developer I know too well that nice, clean abstractions with components require very thorough requirement analysis in advance. In practice however, this is often not possible - so one ends up with leaky abstractions/components with too many messy parameters - or one makes a general "framework" from his own components which is hard to understand for others. Or even  uses 3rd party frameworks such as Telerik, DevExpress... 

I see a better alternative: a clever combination of components for application parts which are clear enough & stable, and for other parts the helper/MVC style. A smart combination. So I am looking for help how to make this possible with Blazor.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by SteveSandersonMS** [comment]
This is supported and we've started adding info about it to docs: https://github.com/dotnet/AspNetCore.Docs/blob/1e199f340780f407a685695e6c4d953f173fa891/aspnetcore/blazor/webassembly-performance-best-practices.md#defining-reusable-renderfragments-in-code

**Comment by Stamo-Gochev** [comment]
@SteveSandersonMS I am testing the functionality with a code similar to:
```razor
@code {
    RenderFragment<Input> InputRenderer = input => __builder =>
    {
        <input @oninput="@(input.OnInput)" />
    };
}
```
but this throws with a compilation error about the `@oninput` handler. Do you intend to support this in the future? This is handy in cases where you don't want to create a separate component, but reuse a simple fragment like the above.

**Comment by SteveSandersonMS** [comment]
@Stamo-Gochev Thanks for pointing that out. It is supported, but any code that references `this` (such as an event handler) has to be defined inside a method or constructor. So in this case you could use the following syntax:

```razor
@InputRenderer(someInput)

@code {
    RenderFragment InputRenderer(Input input) => __builder =>
    {
        <input @oninput="@(input.OnInput)" />
    }
}
```

TBH that's probably nicer syntax anyway.

**Comment by Stamo-Gochev** [comment]
@SteveSandersonMS I've logged an issue as this doesn't seem to be working https://github.com/dotnet/aspnetcore/issues/26729 It was [closed](https://github.com/dotnet/aspnetcore/issues/26729#issuecomment-706270770), but the syntax still throws an error, Can you re-check if I am missing something and post more info in https://github.com/dotnet/aspnetcore/issues/26729?
