### ISSUE TITLE
Problem with manually fetching objects from ioc container

### ISSUE THREAD

**Issue by HanJunJun** [dotnet/aspnetcore#20536]
### Describe the bug
I found that when the registered life cycle is AddScoped, the object manually obtained from the container and the object injected by the constructor are not the same.

### To Reproduce
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider svp)
        {
            EnginContext.Initialize(new GeneralEngine(app.ApplicationServices));
            app.AddWiseduConfigureProvider(env, svp, _configuration);
        }
var dbContext = EnginContext.Current.Resolve<ISysDeviceConfigRepository>();
var sql = $@"select a.* from SysDeviceConfig a left join SysDeviceVersion b on a.SysDeviceConfigId=b.SysDeviceConfigId
where b.SysDeviceVersionId='{item}'";
                            var config = dbContext.QueryBySql<SysDeviceConfig>(sql).Result.FirstOrDefault();
Code uploaded

**Comment by javiercn** [comment]
@HanJunJun thanks for contacting us.

@davidfowl thoughts?

**Comment by davidfowl** [comment]
Are you calling BuildServiceProvider anywhere in your code? Can you provide a sample that reproduces the problem?
