### ISSUE TITLE
Correlation failed for Blazor App with Multiple Organization Authentication via ngrok

### ISSUE THREAD

**Issue by wjvii** [dotnet/aspnetcore#20534]
### Is your feature request related to a problem? Please describe.
I start a new Blazor App that says Source: .NET Core 3.1.4 and select Work or School Accounts and in my case picked Multiple Organizations for Authentication. I let Visual Studio provision the app for authentication.

I then run the application in Visual Studio and get the local Url

I then run ngrok with something like:

ngrok http https://localhost:5001 -host-header="localhost:5001" 

also tried IIS with

ngrok http https://localhost:44389 -host-header="localhost:44389"

I get the following error:

Exception: Correlation failed.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Describe the solution you'd like
I would like for this to work or at least understand why it will not or cannot work. I read quite a few articles online and tried various same site cookie policies, additional redirect uris in the azure portal and a few other things and never came up with a combination that allowed the site to be accessed via ngrok.

**Comment by javiercn** [comment]
Thanks for contacting us @wjvii.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

**Comment by Tratcher** [comment]
It looks like ngrok is a diagnostics tool? Can you export a trace of the network traffic to share? These kinds of tools sometimes don't fully support cookies the same way that a browser would.

**Comment by wjvii** [comment]
@Tratcher, yes ngrok is tool to create public Urls for your development machine. My app needed a webhook and so I was trying that and found that despite thinking I had it all setup up correctly I could not authenticate through the public Url. 

https://ngrok.com/ for more information on the tool.

I feel sure you are on the right path and some articles I read talked about the same site cookies, etc and I tried a few of the options presented but none worked, at least not the way I set them up.

Happy to provide a trace, What tool would you like me to use to capture the trace?

**Comment by Tratcher** [comment]
Fiddler is a good trace too. Make sure to set the decryption option.

**Comment by javiercn** [comment]
@Tratcher I'm passing this to security since there's nothing Blazor specific here. (Authentication always happens before server-side Blazor apps start and uses the regular auth middleware).
