### ISSUE TITLE
AddRazorRuntimeCompilation suddenly stopped working in asp.net core 3.1 and Visual Studio  16.5.2

### ISSUE THREAD

**Issue by urza** [dotnet/aspnetcore#20542]
I have asp.net core 3.0 mvc app, with this in Startup.cs:
``` C#
public void ConfigureServices(IServiceCollection services)
        {
            var builder = services.AddControllersWithViews();
#if DEBUG
                builder.AddRazorRuntimeCompilation();
#endif
```
 It was working fine until I updated Visual Studio to lastest version:

Microsoft Visual Studio Community 2019 
Version 16.5.2
VisualStudio.16.Release/16.5.2+29926.136
Microsoft .NET Framework
Version 4.8.03752

Now when building the solution I got this exception:

**Error	CS1061	'IMvcBuilder' does not contain a definition for 'AddRazorRuntimeCompilation' and no accessible extension method 'AddRazorRuntimeCompilation' accepting a first argument of type 'IMvcBuilder' could be found (are you missing a using directive or an assembly reference?)**

I tried to migrate the project to .net core 3.1 and updgrade nuget package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation to latest version (3.1.3) but the error remains.

**Comment by orkunweb** [comment]
I also have the same problem. It suddenly stopped working in .net core 3.1. There isn't any error in my application. When I request the updated page, browser doesn't response. 

I tried many things but it doesn't improve.

(I use Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package 3.1.3 version)

**Comment by pranavkm** [comment]
Would you mind sharing a minimal repo app? I just tried this out and it seemed to be working fine.

**Comment by orkunweb** [comment]
I created a new project for the problem (.net core 3.1). Installed Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package 3.1.3 version. After I updated "welcome" text in Index.cshtml, I saved this file. But when I request this route in browser (/home/index), no any response. Browser just say "waiting for localhost". I share repo :

https://github.com/orkunweb/exampleForRuntimeUpdateViewsProblem.git

**Comment by pranavkm** [comment]
@orkunweb your repo worked fine for me. Usually the first compile takes a bit longer, but further compilations should be quicker. 

* Are you able to consistently reproduce this problem on a clean machine?
* If you are, it would help to grab debug logs from the application and attach it here. It might help diagnose  the issue.

**Comment by orkunweb** [comment]
There was no problem until three days ago. It was working great. I have no idea what it is. I will try on another machine. thanks for your answers.

**Comment by urza** [comment]
The project started working without any code or config change. I didn't even restarted my computer. I was just working on another project and today I opened this one and it builds without any errors. I don't know how to explain this.

**Comment by pranavkm** [comment]
@urza perhaps cached artifacts in VS or cached restore artifacts. If things are working fine, I'll go ahead and mark this issue as resolved.

**Comment by orkunweb** [comment]
Started compile mine today. I think it can't be a coincidence.

**Comment by paddotk** [comment]
I have this issue too. I wish there was a solution offered instead of just closing the ticket.

**Comment by orkunweb** [comment]
Open visual studio installer and click "Restore". When you do this, it will start working properly again.

**Comment by paddotk** [comment]
Turned out the required package wasn't installed correctly after all. The feedback of VS after the install attempt was a bit misleading, but I got it working :)
