### ISSUE TITLE
Blazor Question: Order/Index of ChildComponents rendered via ChildContent/RenderFragment

### ISSUE THREAD

**Issue by thomasclaudiushuber** [dotnet/aspnetcore#20553]
This is not an issue, but a question. (Repro is at the end of this post)
I came across this when I tried to wrap a few JavaScript components in Blazor.

Let's say I've created a component like this:

```
<List>
  <ListItem Value="One"></ListItem>
  <ListItem Value="Two"></ListItem>
  <ListItem Value="Three"></ListItem>
</List>
```

The ListItem has no UI, it's just a subclass of ComponentBase that get's the parent List via CascadingParameter.
 
Now I tried to do something like this:

```
<List>
  <ListItem Value="One"></ListItem>
  @if(showItemTwo)
  { 
    <ListItem Value="Two"></ListItem>
  }
  <ListItem Value="Three"></ListItem>

</List>
```

This works. I only have the problem that I don't know the index of that ListItem two. This means when I remove and add it, its value becomes always the last item in the List, as I don't know the index of the ListItem.

Is there a way to get that index of the rendered ListItem?

Of course I could explicitly create an Index property like this:

```
<List>
  <ListItem Value="One" Index="0"></ListItem>
  @if(showItemTwo)
  { 
    <ListItem Value="Two" Index="1"></ListItem>
  }
  <ListItem Value="Three" Index="2"></ListItem>

</List>
```

But I think there should be a more obvious way. 

Did I miss something, or is an override of BuildRenderTree the only way to solve this?

Here's a repro: https://github.com/thomasclaudiushuber/BlazorRenderFragmentPositionIssue

Any hints welcome.

Thanks,
Thomas

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should help: https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#use-key-to-control-the-preservation-of-elements-and-components

**Comment by thomasclaudiushuber** [comment]
Hi @mkArtakMSFT, thanks. I know the @key attribute, but don't know how this should work in this case.
