### ISSUE TITLE
Can learn form dotnetty? (Handles protocols and TCP long connections)

### ISSUE THREAD

**Issue by xuanyuan5005** [dotnet/aspnetcore#20554]
Can learn form dotnetty? (Handles protocols and TCP long connections)
eg:
     1,Receiving data processing
     2, protocol processing,like dotnetty
        https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Codecs/LengthFieldPrepender.cs
     3,ping message when there is no outbound traffic
        https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Handlers/Timeout/IdleStateHandler.cs

**Comment by davidfowl** [comment]
This isn't really relevant for ASP.NET Core itself. See https://github.com/dotnet/runtime/issues/1793 and https://github.com/davidfowl/bedrockframework
