### ISSUE TITLE
IHostBuilder not working while IWebHostBuilder in Linux in aspnet core 3.1 web api application

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#20566]
I have .net core web api project. I am running my application in both Windows and Linux

Problem is My application get starts and works in both linux and windows with IWebHostBuilder while equivalent(what i think so) code for using IHostBuilder didn't start my application in linux.

Please somebody give idea what wrong i am doing

Following currently works

```
   public static IWebHostBuilder BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args).
           ConfigureKestrel(serverOptions =>
           {
           }).UseIISIntegration()
           .UseStartup<StartupShutdownHandler>(); 
```
Following doesn't works in linux but works in windows

```
 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)        
        .ConfigureWebHostDefaults(webBuilder => webBuilder.UseKestrel().UseIIS().UseStartup<StartupShutdownHandler>());
```
I have to run my app on both windows and linux

**Comment by KamranShahid** [comment]
> public static IHostBuilder CreateHostBuilder(string[] args) =>
>             Host.CreateDefaultBuilder(args)        
>         .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<StartupShutdownHandler>());

I have tried above option. But what i see is My application starts in IIS (windows) but not on linux.
Trying to found out error

**Comment by Tratcher** [comment]
You'll need to check the server logs.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configuration

**Comment by KamranShahid** [comment]
> You'll need to check the server logs.
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configuration

My application is using log4net logging separately. My application is running as sytem service in linux .We have set logging as 
"Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "None",
      "System": "None",
      "Microsoft": "None"
    }
  },
to avoid logging there. But looks like needed to set it on to see what happened there.
Checking log in system service is bit hectic

**Comment by KamranShahid** [comment]
> You'll need to check the server logs.
> https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configuration

I am getting Error 
**No listening endpoints were configured. Binding to http://localhost:5000 by default.**
My service is being run with different port configured in service file like 

My service file have a line like 

ExecStart=/usr/bin/dotnet /MyApp/MyApp.Interfaces.dll --server.urls "http://0.0.0.0:8080;"

**Comment by Tratcher** [comment]
"server.urls" is considered obsolete and replaced by "urls". We transitioned to "urls" quite a while ago, but I don't see the associated annoucement.
WebHost checked both for backcompat. 
https://github.com/dotnet/aspnetcore/blob/d4a2fa1ceb3b9c10054da8a7c6a4bd61801aea18/src/Hosting/Hosting/src/Internal/WebHost.cs#L303
GenericHost does not.
https://github.com/dotnet/aspnetcore/blob/e3d3da3546aa2085aa39520f3c302d0672e5bab8/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs#L71

**Comment by KamranShahid** [comment]
> "server.urls" is considered obsolete and replaced by "urls". We transitioned to "urls" quite a while ago, but I don't see the associated annoucement.
> WebHost checked both for backcompat.
> https://github.com/dotnet/aspnetcore/blob/d4a2fa1ceb3b9c10054da8a7c6a4bd61801aea18/src/Hosting/Hosting/src/Internal/WebHost.cs#L303
> 
> 
> GenericHost does not.
> https://github.com/dotnet/aspnetcore/blob/e3d3da3546aa2085aa39520f3c302d0672e5bab8/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs#L71

I will try to update this in my service. problem is i already have deployed this service at multiple places. Will see how can i update My script regarding this.
Any way thanks for this precious information
