### ISSUE TITLE
Cannot connect to http://localhost:5000

### ISSUE THREAD

**Issue by jotway** [dotnet/aspnetcore#20565]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

I'm running Windows 10 and VS 2019 - both current versions.

When I try to browse to http://localhost:5000 I get the following.

![image](https://user-images.githubusercontent.com/20447364/78421615-a04aa680-768b-11ea-9d16-d5b89ab977ab.png)

I've followed the procedure for "Checking the connection" without success.

Note that I can browse to http://localhost.  

The system just can't handle the :5000

However, when I work through the diferent tutorial at https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=windows I can successfully browse to https://localhost:5001.
(Don't you just love software!?)

Can you help please?

**Comment by blowdart** [comment]
OK, we'll start from the beginning. 

- When you run your app a console window should open, does that happen?

If it does not there are a couple of things to look for
- Can you look at the Visual Studio toolbar, and look beside the run button; does it say IIS Express or does it say your project name?

![Annotation 2020-04-06 050736](https://user-images.githubusercontent.com/796298/78556849-937d9e00-77c4-11ea-8dbb-ca4a61d407c4.jpg)

- If it says IIS Express, then the port chosen is going to be pretty random, which would explain everything. When you hit run, or f5, the browser should get the port right in the window it opens, but you can discover it by right clicking on the IIS Express icon in the system tray;

![Annotation 2020-04-06 050926](https://user-images.githubusercontent.com/796298/78556999-dc355700-77c4-11ea-80cb-949569c4376c.jpg)

   - If it says your project name then when you start the project a console window will open; with content something like the following.  Check the URLs you see at the start of the console window. What are they? is http://localhost:5000 in there?

```txt
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\BarryDorrans\source\repos\WebApplication1\WebApplication1
```

**Comment by jotway** [comment]
Barry,

 

Thank you for your helpful reply.  

 

I’ll annotate your solution in green below.

**Comment by jotway** [comment]
Thank you for your work around.  I've pasted my answers to your questions in gree below.

![image](https://user-images.githubusercontent.com/20447364/78640689-c027d780-78e2-11ea-9d3c-a86df1174a7f.png)

**Comment by blowdart** [comment]
@Rick-Anderson One for docs perhaps?

**Comment by Rick-Anderson** [comment]
@blowdart  I'll take care of it and see if I can have these issues go to the docs repo, not your repo.

**Comment by blowdart** [comment]
Honestly it was nice to have a starter issue I can solve :)
