### ISSUE TITLE
Copy target required to provide custom Blazor WASM web.config

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#20569]
### Is your feature request related to a problem? Please describe.

Replace the *web.config* that Blazor WebAssembly publish produces in order to supply a custom file.

### Describe the solution you'd like

Use the normal approach:

1. Place a custom *web.config* at the root of the project.
1. Use the `<IsWebConfigTransformDisabled>` property in the project file.

It works for the *web.config* placed at *bin/Release/netstandard2.1* folder, but it doesn't work for the *web.config* placed at *bin/Release/netstandard2.1/publish* folder.

### Additional context

The framework already sets `<IsWebConfigTransformDisabled>` to `true` in order to do its own thing at ...

https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/Build/src/targets/Publish.targets#L9

... so there's no utility for a dev to use that approach for a published *web.config* unless they use a copy target ...

```xml
<Target Name="CopyWebConfigOnPublish" AfterTargets="Publish">
  <Copy SourceFiles="web.config" DestinationFolder="$(PublishDir)" />
</Target>
```

For now, I'm going to document the copy target approach with a companion issue to track this engineering in case something is done with this. Alternatively, I'll close the tracking issue if you want to stick with the copy target approach.

**Comment by javiercn** [comment]
Thanks luke,

I don't think we do anything in the hosted case. That is likely something VS/Publishing is doing already.

For the standalone case we do unconditionally generate a web.config file, we should change this to detect if you have one in your project root folder and avoid doing anything.

**Comment by guardrex** [comment]
> hosted case ... something VS/Publishing is doing already

Should we accept the current behavior as it is for hosted/Server (i.e., don't open an SDK issue and keep documentation to cover it), or should I open an SDK issue for that aspect?

**Comment by guardrex** [comment]
I better double-check the Server scenario. I have a feeling that I didn't copy over the tranform disable. I'll double-check that.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/issues/20490

We already got a report for this, so I'm closing this issue in favor of the one I just referenced. Feel free to add details on that one.
