### ISSUE TITLE
Blazor Wasm hosted, ReferenceOutputAssembly false and AuthenticationService.js

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#20567]
Accroding to this blog:

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Its now possible for the blazor host, to set the project reference to the blazor client to not reference the output assembly e.g here is the project reference in my host csproj file:

```
   <ProjectReference Include="..\Client\BlazorAppWithAuth1.Client.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
```
Because the client is just a "bunch of static files".

However the client wasm (when using the new templates for authentication) has this in it's index.html:

```
    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
```

This results in a 404 when the browser tries to load this js file, I am guessing because the host project no longer sees the `Microsoft.AspNetCore.Components.WebAssembly.Authentication` package reference which is added to the client csproj when `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>` is false on the project reference.

What is the correct way to resolve this?

I have tried adding the following to the host project but it didn't work;

```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="3.2.0-preview3.20168.3">
      <IncludeAssets>contentFiles</IncludeAssets>
    </PackageReference>

```

I'd like to avoid extracting a physical copy of the `AuthenticationService.js` file and adding it to the wwwroot folder of my host, because that defeats the purpose of serving up static assets from dependencies.

Note: If I remove the `<IncludeAssets>contentFiles</IncludeAssets>` then the host is able to serve up the javascript file, but it now also has a compilation reference to the binaries in that blazor package which is not the clean seperation I am looking for in terms of the host just seeing the blazor client as a bunch of "static files"

I also wasn't sure if `contentFiles` was the correct way to filter the package reference to include only the "static files" from a package. I couldn't find any documentation on that and would appreciate any pointer

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

I think that adding the dependency directly on the host and marking it to `ReferenceOutputAssembly=false` should do the trick. I imagine that what's going on is that the transitive references are not being picked up by the host project when `ReferenceOutputAssembly=false` and they need to be added explicitly.

**Comment by dazinator** [comment]
@javiercn - thanks, that worked.
