### ISSUE TITLE
How to use letencrypt with blazor in Linux Web App

### ISSUE THREAD

**Issue by AlexTeixeira** [dotnet/aspnetcore#20572]
Hello,

I'm trying to create enable SSL for my domain in Blazor Server App that is hosted in an azure Web App.

My issue is, that I'm not able to serve **/.well-known/** directory and subdirectories with my blazor app.

**Web App Information**

- B1 Linux web app
- Using .net core 3.1.0

**Static File Configuration**

Here my sample of code that should create and serve the folder.

```
public static class AcmeChallengeResponderExtensions
    {
        private const string WellKnownFolder = @".well-known";
        private const string WellKnownRequestPath = @"/.well-known";
        private const string AcmeChallenceFolder = @"acme-challenge";
        private const string WellKnownContentType = "text/plain";


        public static IApplicationBuilder UseAcmeChallengeResponder(this IApplicationBuilder app)
        {
            var rootFolderPath = Directory.GetCurrentDirectory();

            var root = new DirectoryInfo(rootFolderPath);
            if (!root.Exists)
                throw new ArgumentException("The provided folder does not exist");

            root.CreateSubdirectory(WellKnownFolder);
            root.CreateSubdirectory(Path.Combine(WellKnownFolder, AcmeChallenceFolder));
            
            app.UseStaticFiles(new StaticFileOptions
            {
                RequestPath = new PathString(WellKnownRequestPath),
                FileProvider = new PhysicalFileProvider(Path.Combine(rootFolderPath, WellKnownFolder)),
                ServeUnknownFileTypes = true,
                DefaultContentType = WellKnownContentType,
            });
            
            return app;
        }
    }
```

**Other Information**

I also tried to create **/.well-known/** in **wwwroot** folder, but if the path is not a file, I have the same issue.

Thanks for your help.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @AlexTeixeira.
@javiercn I think this is somehow related to static assets, isn't it? Can you please take a look Thanks!

**Comment by javiercn** [comment]
@AlexTeixeira thanks for contacting us.

There's nothing specific about Blazor here. I would suggest you start with making a regular web application work and then add Blazor.

You should be able to use your middleware provided you put it before `UseStaticFiles` and that your code is correct.

**Comment by AlexTeixeira** [comment]
Hi @javiercn,

Thanks for the answer.  So I should create a basic asp.net core app and then add blazor ? Am I right ?

I used the Blazor Server App template to create my app but I'm not able to serve some extra static folder from wwwroot or using staticFile middleware, is quite dissapointing...

And I can create a new webapp, but if I add blazor after all I should have the same issue because of the routing, no ?

Thanks for your answer

**Comment by javiercn** [comment]
Routing in Blazor is very low priority, so you shouldn't be affected by it. One way to be sure is to plug in your own static files middleware in front of the static files middleware and before app.UseRouting() and that should guarantee that you get to serve whatever file on disk you have.

That's the reason I asked you to start with an MVC app, so that you can troubleshoot your issue in a simplified environment, given that Blazor is unlikely to affect how that behaves.
