### ISSUE TITLE
Flakiness caused by lack of retries

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#20577]
Seems like we don't retry downloads which can load to flakyness when they fail (and they do quite often see https://github.com/dotnet/aspnetcore/pull/20561#issuecomment-609841197). 

@dougbu also thinks this is a general problem with the scripts that we have under eng/*.

**Comment by dougbu** [comment]
It's not just tests that are hurt here. A couple of the Windows jobs in https://dev.azure.com/dnceng/public/_build/results?buildId=590331 failed almost immediately due to https://nodejs.org flakiness.

**Comment by dougbu** [comment]
Some common patterns to look at are in eng/common/tools.ps1|sh Need to look at any scripts that run on CI or Helix (test) agents, probably most of what's in eng/scripts (though it's fine to ignore the VS installation stuff).
