### ISSUE TITLE
Virtual C# file variable automatically added within @code block

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#20584]
1. `dotnet new mvc`
1. Open `index.cshtml`
1. Type out:

```
@{
    if (1 < 2) {

    }
}
```

**Expected:** 
```
@{
    if (1 < 2) {

    }
}
```

**Actual:**
```
@{
    if (1 <__o 2) {

    }
}
```

the `__o` was automatically added after the `<` char was typed. This `__o` is a variable in the razor C# virtual file:

```
private static System.Object __o = null;
```

which shouldn't be showing up for the suggestions / autoreplacements.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen all yours to tackle :)

**Comment by NTaylorMullen** [comment]
Duplicate of https://github.com/dotnet/aspnetcore-tooling/pull/2994
