### ISSUE TITLE
generate minlength attribute for input tag-helper

### ISSUE THREAD

**Issue by carlin-q-scott** [dotnet/aspnetcore#20588]
### Describe the solution you'd like
I want the input tag-helper to use the browser built-in constraint attribute `minlength` when I set the MinLengthAttribute, or StringLength(Minimum) on a model property.

### Additional context
The MaxLengthAttribute and StringLength data model attributes generate the corresponding `maxlength` constraint attribute.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
