### ISSUE TITLE
What's up with blazor.server.js

### ISSUE THREAD

**Issue by lxman** [dotnet/aspnetcore#20585]
### Describe the bug
I'm trying to develop with netcore3.1. In a fresh boilerplate blazor server app, there is a reference in ```_Host.cshtml``` to ```_framework/blazor.server.js```. Visual Studio highlights this reference and says that it cannot find it. Sure enough, ```_framework``` is not present under ```wwwroot``` in the project.
I did some digging on my system and found that under ```C:\Users\michael\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\tools\blazor``` there is a ```blazor.webassembly.js``` but no ```blazor.server.js```.
The reason that I remark on this is that on another system that I work on, in a similar folder (3.0.0 preview 9) this file is present.
I am having significant difficulties with a project that I am trying to develop where I cannot get components to update properly, and I am wondering if this might be the culprit.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

VS 16.5.2
VS Code 1.43.2

**Comment by danroth27** [comment]
Hi @lxman. The blazor.server.js file is an embedded resource on the Microsoft.AspNetCore.Components.Server.dll assembly, which ships as part of the ASP.NET Core shared framework. While VS does typically try to validate that your script references are actually on disk at the specified path, VS should ignore blazor.server.js, which is included as part of the ASP.NET Core shared framework (it does on my machine). It sounds like something isn't working quite right with your Visual Studio version. Can you try repairing your VS installation?

**Comment by lxman** [comment]
Hmm, OK, that makes sense. Unfortunately the validation for VS has been a trouble spot for quite some time by my experience. Working with Blazor I constantly get validation errors (red squigglies) yet the program compiles and runs. Annoying, but I'm used to it by now.

Thanks for the info. I'll close this.

**Comment by danroth27** [comment]
> Working with Blazor I constantly get validation errors (red squigglies) yet the program compiles and runs. Annoying, but I'm used to it by now.

For Razor files this is a known issue that we are working on addressing with a total revamp of the Razor tooling system. It will take some time to address, but once it's done it should enable a much better, more consistent, and more feature rich experience.
