### ISSUE TITLE
Error Compiling .proto file

### ISSUE THREAD

**Issue by pplavetzki** [dotnet/aspnetcore#20583]
When using ```//``` for comments in the proto files, which is valid proto v3 syntax, code does not get generated or produces errors.  When using ```/* */``` syntax proto compiles correctly.

Using Grpc.Tools v2.28.1 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7223e694-85ba-4b95-96c8-68ae14753e7c
* Version Independent ID: 28ec8399-ba0e-c995-3ac2-b1f28e93331b
* Content: [gRPC services with C#](https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/basics.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/basics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by scottaddie** [comment]
@JamesNK Is this a bug? According to https://developers.google.com/protocol-buffers/docs/proto3#adding-comments, `//` is supported.

**Comment by JamesNK** [comment]
`//` is definitely supported. That is the syntax I use for comments in proto files.

You should log issues about code generation at https://github.com/grpc/grpc. Grpc.Tools is maintained in that repository.
