### ISSUE TITLE
<text> tag intellisense doesn't show up in the middle of typing text tag

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#20590]
Open Counter.cs and try typing,

![Screen-Recording-2020-04-06-at-4](https://user-images.githubusercontent.com/1579269/78614146-9909d100-7822-11ea-8d88-6305698b26dd.gif)

Note it doesn't work correctly at the first block whereas it works as expected in the second block.

**Comment by TanayParikh** [comment]
Related issue that @ryanbrandenburg found:

1. `dotnet new blazorserver`
2. Open `NavMenu.razor`
3. Paste in:

```
@functions{
    public void SomeOtherMethod()
    {
    }
}
 
@code {
    private bool collapseNavMenu = true;
 
    private string NavMenuCssClass => collapseNavMenu ? "collapse" : null;
 
    private void ToggleNavMenu()
    {
        collapseNavMenu = !collapseNavMenu;
    }
}
```

The `<text>` tag completion is available in `ToggleNavMenu` but not in `SomeOtherMethod`. 

There seems to be a context (C# vs HTML) recognition issue with text tag availability. Will be looking into this.

**Comment by TanayParikh** [comment]
Note, the similar:

```
@functions{
    public void SomeOtherMethod()
    {
    }
}
 
@code {
    private bool collapseNavMenu = true;
 
    private void ToggleNavMenu()
    {
        collapseNavMenu = !collapseNavMenu;
    }
}
```

does not exhibit the same issue (`<text>` completions available for `SomeOtherMethod`).
