### ISSUE TITLE
Razor code commenting VS LSP

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#20594]
VSCode automatically surrounds Razor code with `@* *@` when pressing Ctrl K + Ctrl C but this currently doesn't happen in VS LSP world.

**Comment by ajaybhargavb** [comment]
@NTaylorMullen I think we should do this as part of our polish. The experience is not that great without this.

**Comment by ajaybhargavb** [comment]
Moving this to the backlog until partner teams build support for this.

**Comment by NTaylorMullen** [comment]
Created a "declarative" code commenting issue since supposedly the work there is done: https://github.com/dotnet/aspnetcore/issues/21290
