### ISSUE TITLE
JavaScript interop calls cannot be issued at this time.

### ISSUE THREAD

**Issue by Toemsel** [dotnet/aspnetcore#20599]
Can't read the client's session storage in every state of the application. I do receive an exception "JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd"

Looking for answer, I came across [this post](https://github.com/dotnet/aspnetcore/issues/9613). However, the suggested solution (injecting IComponentContext and check whether the component is currently rendering) isn't applicable anymore.

The second [workaround ](https://github.com/dotnet/aspnetcore/issues/17282) does tell me when JS isn't available, but I would require to "wait/await" till JS is accessible again.

Moving the logic into `OnAfterRender` isn't possible, due to the component's limitation. (DxUpload)

### Further technical details
- ASP.NET Core version: 3.1.3, netcoreapp3.1
- Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /usr/bin/dotnetcore/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/bin/dotnetcore/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/bin/dotnetcore/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/bin/dotnetcore/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@Toemsel thanks for contacting us.

Can you provide more details about your scenario so that we can better understand what the issue is and what you are trying to accomplish?
