### ISSUE TITLE
Blazor Static Assets - don't serve directories prefixed with "."

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#20605]
### Describe the bug

The `StaticWebAssetsLoader` assumes all paths in the manifest are valid for serving up:

https://github.com/dotnet/aspnetcore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/Hosting/Hosting/src/StaticWebAssets/StaticWebAssetsLoader.cs#L43

So for example, it will serve from a base path like ".apps/foo"

However the standard `PhysicalFileProvider` (which comes into play after a publish and the assets are copied to the output dir) will not serve up content from directories in a folder prefixed with a dot - e.g ".apps/foo"

Go to a client wasm project and set:

```
 <StaticWebAssetBasePath>apps/.foo</StaticWebAssetBasePath>
```

Also make sure you set the `basePath` element in index.html accordingly to "apps/.foo"

Note: the "." in the path

Then run the host (in Development environment) and browse to "apps/.foo" - It will successfully serve up the app - thanks to the Static Web Assets file provider. 

![image](https://user-images.githubusercontent.com/3176632/78653227-bd18f100-78ba-11ea-9859-2064f21932f3.png)

However, when you`dotnet publish` the application and run it, it doesn't serve up any files from that directory at all, as then its the `PhysicalFileProvider` coming into play and by default it won't serve content from "." prefixed folders.

This technique of outputting static assets to a "." hidden folder is desirable when wanting to hide the static asset from being served up by default, so I can then "opt in" to serving the static assets to particular tenants who should have access by setting up my own file provider at runtime pointing to that "private" directory. If I allow all apps to be served up by default (by not putting them in a path under webroot that is prefixed with a "."), it means all tenants have access to all apps, and I can't control which tenants see which static content using my own logic. I am aware I could also do custom msbuild targets so that when the content is published it goes somewhere outside of the webroot directory, but this won't be constistent with the development experience and will involve more work than the fix I am proposing here.

If "StaticWebAssetsLoader.cs" can be fixed to honor the "." mechanism for ignoring paths (not setting up file provider) for static asset base paths that contain "." prefixes, then this will make development environment behaviour consistent with production, and provide a feature where by some content can now be hidden from being served up by static files automatically, giving the application a chance to implement it's more complex requirements over the serving of that content).

For additional background, I have multiple SPA's referenced from my host, and all SPA's are relevant to my app, but not all SPA's should be accessible to all tenants of my app, and the current static files stuff assumes that they should be (in Development environments). Dotnet publish "kind of" also assumes that they should be by virtue of copying all static assets to the "wwwroot" directory of the published application. However by virtue of the PhsyicalFileProvider behaviour for ignoring folders prefixed with "." and setting `StaticWebAssetBasePath` to a path with a dot prefix, I can get the behaviour I want and keep those assets "Hidden" by default.  However the static assets file provider comes into play on Development environments and doesn't obey the "." rule. I grant that the nature of this problem isn't critical because it only impacts behaviour on development environments - however it "would be nice" if this was consistent with the behaviour we will ultimately see in production / staging environments as it will allow us to verify things adequately before deploying onwards to those environments. 

For further background see #20580 

Note: I've logged this as a bug but it depends on your view point, it's a bug in that it's a difference in behaviour from PhysicalFileProvider which is used after a dotnet publish.

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

Thanks for the detailed explanation. I don't think this as a bug but as an enhancement. As you mention, this only happens in development, and it is not something we cared/considered supporting at the time, the main reason being because we are more worried when we are not able to serve files that should be served than the other way around.

Once thing that you could do for the development scenario is to add a middleware on your dev pipeline to filter those paths to behave the same way as the physical file provider. 

Another thing you could do is to use MSBuild to alter the paths the files are being copied to and copy them outside the `wwwroot folder` which would give you the exact behavior you are looking for without having to rely on the implementation of the physical file provider.

I'll be open to entertain this is the set of features we need to do is limited (for example just filter `.`) and not configurable. Otherwise, I think I don't want to add this complexity to SWA as there are other ways to achieve the scenario (like described above) and there is a significant complexity in aligning things together, specially if the filter behavior is configurable.

**Comment by dazinator** [comment]
Thanks @javiercn 

> more worried when we are not able to serve files that should be served than the other way around.

The only thing I'll add is that it's possible this will lead to that precise worry being realised, but in non development environments..A developer could set a StaticWebAssetBasePath  in their project to be dot prefixed, without being aware of the PhysicalFileProvider behaviour in production. For example ".MyApps". During development they will be under the illusion that everything will be served fine, but once they deploy to a non development environment they will wonder why they can no longer browse to their application and get 404's.

I grant that it might be a weird choice of path for a developer to chose!

I think the change would literally be a one liner to skip over adding a Static Assets File Provider if the last segment of the BasePath starts with a ".". The other Exclusions that physical file provider can include are all based on environmental things such as File system attributes which are expected to be different per environment anyway.

**Comment by dazinator** [comment]
> Another thing you could do is to use MSBuild to alter the paths the files are being copied to and copy them outside the wwwroot folder 

I would love to know what MSBuild property I need to add to change the path of the published assets - do you know what that is of the top of your head?

**Comment by javiercn** [comment]
@dazinator there is no property for that, you would need to write your own target.

**Comment by dazinator** [comment]
@javiercn 

> Another thing you could do is to use MSBuild to alter the paths the files are being copied to and copy them outside the wwwroot folder

Minor suggestion for a tweak - when I go down this route, I can then add my own StaticFilesMiddleware to the current tenants fork of the Middleware pipeline, configured with their own `IFileProvider` pointing to the SPA I want to serve them - this can be physically looking at the project wwwroot mapped from the manifest in Development mode, or the published location mapped to the private folder (outside the wwwroot directory) when not in development mode -i.e the published application. That mechanism works fine.

However `appBuilder.UseBlazorFrameworkFiles()` doesn't provide an overload that accepts an IFileProvider and is instead coupled to `IWebHostEnvironment.WebRootFileProvider`. This means its not possible for me serve up the "_framework/" files when using this approach.

To workaround this, i'm having to create my own copy of the `appBuilder.UseBlazorFrameworkFiles()`  method, but that can take an IFileProvider as an argument. It would be really handy if you could include such an overload in a future version..

**Comment by dazinator** [comment]
I managed to achieve my end to end story in the end, by copying a lot of code from internal extension methods etc, and refactoring it mainly to allow me to specify my own IFileProvider in various places.

However to stay focused on this specific issue, I had to change `StaticWebAssetsLoader` to ignore "." prefixed directories so it doesn't serve those up by default. This has multiple benefits:

1. Development environment becomes consistent with what happens for non development environments which end up using PhysicalFileProvider.
2.  It provides a mechanism to easily keep certain static content hidden from being served by default, without having to add any custom build targets. All you have to do is set  `StaticWebAssetBasePath` in the project to a path that includes a dot prefixed folder name: e.g ".apps" etc.

I also has to add a method that lets me get the content mappings from the manifest myself. This is so that later I can get the "hidden" assets paths, and set them up myself to be served to the respective tenants or only the audience that should have access to them. 

These two changes to `StaticWebAssetsLoader` are below:

```
 public class StaticWebAssetsLoader
    {

       // omitted for brevity..
        
        public static List<StaticWebAssetsReader.ContentRootMapping> GetStaticWebAssetsManifest(IWebHostEnvironment environment, IConfiguration configuration)
        {
            using (var manifest = ResolveManifest(environment, configuration))
            {
                if (manifest != null)
                {
                    var mappings = StaticWebAssetsReader.Parse(manifest).ToList();
                    return mappings;               
                }

                return null;
            }
        }     

        internal static void UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
        {
            var staticWebAssetsFileProvider = new List<IFileProvider>();
            var webRootFileProvider = environment.WebRootFileProvider;

            var additionalFiles = StaticWebAssetsReader.Parse(manifest)
                .Where(cr => !IsExcludedPath(cr.BasePath))
                .Select(cr => new StaticWebAssetsFileProvider(cr.BasePath, cr.Path))
                .OfType<IFileProvider>() // Upcast so we can insert on the resulting list.
                .ToList();

            if (additionalFiles.Count == 0)
            {
                return;
            }
            else
            {
                additionalFiles.Insert(0, webRootFileProvider);
                environment.WebRootFileProvider = new CompositeFileProvider(additionalFiles);
            }
        }

        private static bool IsExcludedPath(string basePath)
        {
            var split = basePath.Split('/', StringSplitOptions.RemoveEmptyEntries);
            if(split.Any(a=>a.StartsWith(".")))
            {
                return true;
            }

            return false;
        }

       // ommitted for brevity     
    }
```

Creating this modified `StaticWebAssetsLoader` was only step one, I then had to work out how to get used instead of the default internal one. Turns out it's used from within "WebHost" CreateDefaultBuilder() stuff. I had no way to swap my version in. I had to create an entire copy of `CreateDefaultBuilder()` method, but just calling my own modified `StaticWebAssetsLoader` instead of the asp.net core internal one. Yuck.

Please would you consider:

1. Either adopting these changes OR
2. Making it so I can swap in my own logic to prevent serving of "." directories without having to copy large amounts of internal code.

My next step was configuring a tenants middleware pipeline to serve a particular "private spa" and that yielded some interesting problems with "UseBlazorFrameworkFiles()" but I'll leave that for a seperate issue

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by javiercn** [comment]
As per the comment [here](https://github.com/dotnet/aspnetcore/issues/34890#issuecomment-894210487) the feature is working as expected
