### ISSUE TITLE
[Blazor] Run Arbitrary Javascript code with JsRuntime

### ISSUE THREAD

**Issue by Gchkh16** [dotnet/aspnetcore#20606]
It seems currently JsRuntime only supports calling already defined javascript functions by function name. It will be much better if JsRuntime could execute arbitrary javascript code passed as string.

**Comment by javiercn** [comment]
@Gchkh16 thanks for contacting us.

This is already possible, you can call `eval` and pass in whatever string you want. Although I don't recommend using that for the same reasons it is discouraged in other places. If you do it carelessly and using user input, you are opening yourself to XSS
