### ISSUE TITLE
Blazor WebAssembly ASP.NET Core hosted project does not copy the wwwroot to output

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/aspnetcore#20613]
Blazor WebAssembly ASP.NET Core hosted project does not copy the client project `wwwroot` to the output folder of server project when configuration is `Debug` or `Release`, except I use `Publish`.

if I run the docker or compose project, then access http://localhost I will get 404 not found. But if I access http://localhost/controller it works well.

This means it can not work properly for `docker-compose` debugging.

#### IDE
`Microsoft Visual Studio Community 2019 16.5.2`

#### .NET
```
λ dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.201
 Commit:    b1768b4ae7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

![image](https://user-images.githubusercontent.com/4510984/78692686-d0fd3b00-792c-11ea-9519-7dda1c489cf7.png)

![image](https://user-images.githubusercontent.com/4510984/78693628-18d09200-792e-11ea-8add-ac09533cd2be.png)

------------

### No `wwwroot` in the docker container

![image](https://user-images.githubusercontent.com/4510984/78694567-72858c00-792f-11ea-826d-ced96676f528.png)

**Comment by GF-Huang** [comment]
When I comment the `<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0-preview3.20168.3" PrivateAssets="all" />` of `xxx.Client.csproj`, it works fine.

**Comment by javiercn** [comment]
@GF-Huang thanks for contacting us.

This is by design. If you are using docker you either need to publish the application or manually map the static web assets paths that appear on the static web assets manifest when you boot up the container if you are trying to run the app without publishing.

**Comment by GF-Huang** [comment]
> @GF-Huang thanks for contacting us.
> 
> This is by design. If you are using docker you either need to publish the application or manually map the static web assets paths that appear on the static web assets manifest when you boot up the container if you are trying to run the app without publishing.

Could you tell me how do `manually map`? Thank you. 🌹
