### ISSUE TITLE
changing id in the edit form modifies also the path variable with the invalid id

### ISSUE THREAD

**Issue by DianaMounir** [dotnet/aspnetcore#20618]
# changing id in the edit form modifies also the path variable with the invalid id

# General

when using default scaffolding for a model with the CRUB operations
it generates the following code for the edit operation
```
[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }
            // ...
      } 
```
and we modify manually from the inspect element the id from 1 to 2 eg
```
from
<input type="hidden" data-val="true" data-val-required="The Id field is required." id="Id" name="Id" value="1" />
 
to
<input type="hidden" data-val="true" data-val-required="The Id field is required." id="Id" name="Id" value="2" />
```

it sees the following request

Request URL: https://localhost:44388/Movies/Edit/1
Request Method: POST
Status Code: 302 
with the following payload
```
Id: 2
Title: When Harry Met Sally
ReleaseDate: 0001-01-01
Genre: Romantic Comedy
Price: 7.99
__RequestVerificationToken: CfDJ8APqszQhrwZMgL7U-zrQ5tmhWPJyXxfHkmBTrw3qy2p5MxENTInlUtUUxOq9LfVMMLF-c3pUuG8hb69zItXnNa-0Yi_k9qzKTmSiile3yHFFCIQupjxJmvV4vjL3XtMg4NVWeXw9MVwbALSwlI8XbjM
```
## what is expected
that id = 1 , movie.Id = 2 and the condition id != movie.Id equals true and the request return 404
## what went wrong
that id = 2 , movie.Id = 2 and the condition id != movie.Id equals false and the request return 302
#version
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.1" />
  </ItemGroup>



</Project>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear what is the issue you're facing. Can you share a minimal repro project and point out what is the unexpected behavior you're observing?

Thanks!

**Comment by mkArtakMSFT** [comment]
We thought some more about this and we assume the existence of the `id` parameter on the `Edit` action is the confusing part. Is this it?
