### ISSUE TITLE
ASP.NET Core Logging Integration extension does not log after upgrade to 3.0/3.1

### ISSUE THREAD

**Issue by jbagley-iona** [dotnet/aspnetcore#20617]
### Describe the bug
Since upgrading to .NET core 3, the ASP.NET Core Logging Integration extension no longer seems to work.  Before upgrading, logs (to storage on Azure) were correctly produced.  After upgrading, logs are no longer produced.

I was able to work around this by directly calling UseAzureAppServices in Program.cs (as mentioned in #15381).  Upgrading the extension to the latest version (3.1.3) did not fix the issue. 

### Further technical details
- ASP.NET Core version 3.1.2

**Comment by anurse** [comment]
@BrennanConroy can you take a quick look at the package and see if you can repro this? I am having trouble locating the 3.0/3.1 bits in the site extension so there may be a packaging issue going on here :).

**Comment by DanielStout5** [comment]
Can confirm the exact same issue. For some reason the site extension version "5.0.0-preview-3-20215-14" is what was available for updating (weird that a preview is available like that...) and it also does not log.

**Comment by BrennanConroy** [comment]
> For some reason the site extension version "5.0.0-preview-3-20215-14" is what was available for updating

App Service doesn't seem to have a way to choose what version to install. We've unlisted the 5.0 preview package now. Try removing and re-adding the extension to get the 3.1.4 version.

**Comment by BrennanConroy** [comment]
3.1.4 site extension works.
