### ISSUE TITLE
[Blazor server-side] JS to Server crash on passing large HTML

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#20610]
### Describe the bug
Browser gets disconnected after calling dotnetref to invokeMethodAsync. Setting large HTML like base64 image or large href results into disconnection.

### To Reproduce
1) Create component with JS Invokable function like mine
```
    [JSInvokable]
    public void SetHtml(string html)
    {
        Model.Body = html;
    }
```
2) Call from Javascript via dotnetref
`dotnet.invokeMethodAsync("SetHtml", large_senseful_html_from_wysiwyg_it_doesnt_like_eg_base64_or_large_href_attribute);`

### Got Exceptions? Include both the message and the stack trace
No expcetion on server-side

Client side:
`Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.`

### Further technical details
- ASP.NET Core version 3.1.0
- VS 16.5

**Comment by javiercn** [comment]
@glararan thanks for contacting us. It is likely you are reaching the message limit, which by default is 32KB on SignalR, so realistically it is about 30-31KB for the app to use.

**Comment by glararan** [comment]
@javiercn length was about 47kB. Can I change limit or its not possible?

**Comment by javiercn** [comment]
It is possible although discouraged as there are security trade-offs from changing it. You can do so in the SignalR hub options. See [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-3.1&tabs=dotnet) for details.

I would suggest that instead you break the message into multiple chunks and perform multiple JS interop calls until you've received the full message, at that point you can assemble it and do whatever you want.

**Comment by javiercn** [comment]
I'm closing this issue as the original question has been answered.
