### ISSUE TITLE
Announcement: BadHttpRequestException's obsolete and replaced

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#20614]
## BadHttpRequestException's obsolete and replaced

`Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException` and `Microsoft.AspNetCore.Server.IIS.BadHttpRequestException` have been marked as Obsolete and have been changed to derive from the new `Microsoft.AspNetCore.Http.BadHttpRequestException`. The servers still throw their old exception types for for backwards compatibility, but the obsolete types will be removed in a future release.

See https://github.com/dotnet/aspnetcore/pull/20339 for the change.

### Version introduced

ASP.NET Core 5.0

### Old behavior

`Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException` and `Microsoft.AspNetCore.Server.IIS.BadHttpRequestException` derived from `System.IO.IOException`.

### New behavior

`Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException` and `Microsoft.AspNetCore.Server.IIS.BadHttpRequestException` are obsolete and derive from a new type `Microsoft.AspNetCore.Http.BadHttpRequestException` which derives from `System.IO.IOException`.

### Reason for change

To consolidate duplicate types and unify behavior across server implementations. An application can now catch the base exception `Microsoft.AspNetCore.Http.BadHttpRequestException` when using either Kestrel or IIS.

### Recommended action

Replace usages of `Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException` and `Microsoft.AspNetCore.Server.IIS.BadHttpRequestException` with `Microsoft.AspNetCore.Http.BadHttpRequestException`.

### Category

ASP.NET

### Affected APIs

[Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.badhttprequestexception?view=aspnetcore-1.1&viewFallbackFrom=aspnetcore-3.1)
[Microsoft.AspNetCore.Server.IIS.BadHttpRequestException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.iis.badhttprequestexception?view=aspnetcore-3.1)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by bachratyg** [comment]
Please don't forget HttpSys! It still throws plain IOExceptions where the other two already throw their own BadHttpRequest.

**Comment by Tratcher** [comment]
@bachratyg indeed, now that we have a unified type HttpSys can take advantage of it. Filed https://github.com/dotnet/aspnetcore/issues/20688. Not sure when we'll get to it though.

**Comment by bachratyg** [comment]
Sorry, didn't have time in the last post to find and link the original issue: https://github.com/dotnet/aspnetcore/issues/12409

**Comment by Tratcher** [comment]
The form size limits are a bit different. That's validating individual sections of the form rather than the whole body. I could see still wanting a 413 for some of those, but that's a bit more involved break unrelated to the servers.
