### ISSUE TITLE
CreateDefaultHost method doc not updated to mention static web assets.

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#20611]
## Describe the bug
Very minor nitpick:
I see that you have gone to lengths to keep this methods doc comment up to date historically:-

https://github.com/dotnet/aspnetcore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/WebHost.cs#L148

However it appears with the new StaticWebAssets stuff that was added, the comment could use updating to mention that.

**Comment by Tratcher** [comment]
Would also want to update ConfigureWebHostDefaults https://github.com/dotnet/aspnetcore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/GenericHostBuilderExtensions.cs#L25

**Comment by davidfowl** [comment]
@javiercn do the needful

**Comment by anurse** [comment]
@javiercn are you able to make this update? Trying to triage this :).

**Comment by javiercn** [comment]
It is marked as good first issue/help wanted. Can we leave it like that?

**Comment by davidfowl** [comment]
If you fill in what the comment is supposed to have. We shouldn’t leave the community to document our features

**Comment by anurse** [comment]
I'll just knock out a quick comment.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/20653

**Comment by javiercn** [comment]
@anurse too late :)

**Comment by anurse** [comment]
![A young man looks dejected and walks across a ridge overlooking a city](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FoXB0K4oFw3fck%2Fgiphy.gif&f=1&nofb=1)
