### ISSUE TITLE
MVC SimpleType Binder Should Handle Empty String to Guid binding Gracefully

### ISSUE THREAD

**Issue by vasont** [dotnet/aspnetcore#20620]
Do forgive me if there's a documented way to get the desired behavior. There were no good results using keywords I've added into this title. Looking at code, I don't see logic immediately that would afford the desired behavior.

### Is your feature request related to a problem? Please describe.

There exists a need to be able to pass a strongly-typed Guid parameter via a query, form, etc. using the built in Model Binding mechanisms where the binding is not stringent in exact formatting of the input value. 

Consider the following Example:
```C#
// Some model to take in as input in MVC request
public class MyModel
 {
​	public long RequiredId { get; set; }
​	public Guid NotRequiredId { get; set; }
}
....
[HttpGet]
IActionResult Get([FromQuery]MyModel model)
{
  if (model != null && this.ModelState.IsValid)
  {
    // passing GET ?RequiredId=1&NotRequiredId= or no NotRequiredId parameter will cause a ModelState.IsValid == false
  }
}
```
### Describe the solution you'd like
It is desirable that in the case where a Guid parameter is not specified in the query or is not a valid GUID that the resulting ModelState still be valid, but the Guid parameter will default to Guid.Empty instead of causing a model state failure.

Obviously, perhaps in some scenarios the existing behavior may be desired where a valid Guid is expected. In this case, I would assume one would rely on `ModelMetadata.IsRequired` property attribute OR an alternative may be to add a new ModelMetadata property named `ConvertInvalidGuidToEmpty` or `ConvertMissingGuidToEmpty` whatever the developer finds most appealing.

Using the original example, I believe the underlying code that needs to change is located in the following:
https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/SimpleTypeModelBinder.cs

An example of how this code could be modified is here:

```C#
    ....
    // insert on or about line 80
   // perhaps adding additional check  && !bindingContext.ModelMetadata.IsRequired 🤷‍♂ 
   else if (bindingContext.ModelType == typeof(Guid))
    {
       Guid.TryParse(value, out model);
     }
```

**Comment by vasont** [comment]
Below is a workaround to the issue and requires a custom binding provider and binder be implemented to override Guid bindings.

Create a file `GuidModelBinderProvider.cs`
```C#
    using System;
    using Microsoft.AspNetCore.Mvc.ModelBinding;

    /// <summary>
    /// This class is the provider for the custom GUID model binder.
    /// </summary>
    public class GuidModelBinderProvider : IModelBinderProvider
    {
        /// <summary>
        /// This method implements a new model binder for GUID types only.
        /// </summary>
        /// <param name="context">Contains the model binder provider context.</param>
        /// <returns>Returns a model binder if the type is for GUID</returns>
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            IModelBinder result = null;

            if (context?.Metadata.ModelType == typeof(Guid))
            {
                result = new GuidModelBinder();
            }

            return result;
        }
    }
```

Create a file `GuidModelBuilder.cs`
```C#
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc.ModelBinding;

    /// <summary>
    /// This class overrides the current GUID model binder and makes it a bit smarter in situations where the value is empty or invalid.
    /// The default returned value is to return an Empty Guid which for our purposes should mean the value passed was empty.
    /// </summary>
    /// <remarks>
    /// The GUID binder will cause an invalid model error if no GUID value is specified in the Request data. This is by default a situation that
    /// arises a lot in regard to an optional Guid identity value not being specified in Request.
    /// </remarks>
    public class GuidModelBinder : IModelBinder
    {
        /// <summary>
        /// This call is made to execute the binding.
        /// </summary>
        /// <param name="bindingContext">Contains the model binding context.</param>
        /// <returns>Returns the parsed GUID using TryParse instead of the harsher </returns>
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext == null)
            {
                throw new ArgumentNullException(nameof(bindingContext));
            }

            ValueProviderResult parameter = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);
            Guid result = Guid.Empty;
            Guid.TryParse(parameter.FirstValue, out  result);
            return Task.FromResult(result);
        }
    }
```

In your application `Startup.cs`

```C#
        public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddControllers(options =>
            {
                options.ModelBinderProviders.Insert(0, new GuidModelBinderProvider());
            });
        }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is the way we would recommend people to do it so closing this as resolved.

**Comment by vasont** [comment]
The work around seems like an excessive amount of code regarding something that could be a simple addition to the binder 🤷‍♂ :(
