### ISSUE TITLE
Closing than opening solution can result in LSPDocumentManager exceptions on tracking same document twice

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20629]
In a local scenario I tried closing/reopening a document and I got:
![image](https://user-images.githubusercontent.com/2008729/78725602-cae36c00-78e4-11ea-8ff0-80b977cfe3db.png)

**Comment by ryanbrandenburg** [comment]
Closing then opening the solution or the document?

**Comment by NTaylorMullen** [comment]
I believe it was the solution

**Comment by ryanbrandenburg** [comment]
This didn't repro, there's been a lot of work both on our side and and the VS side for LSP support recently, we think it might have been fixed already.

**Comment by NTaylorMullen** [comment]
Re-opening this. @ajaybhargavb was able to reproduce although not consistently. Either way this is real bad and we need to make sure this doesn't break

**Comment by ajaybhargavb** [comment]
I was able to reproduce this with 50% success by opening a document and editing it and while that is still open, `File->Close Solution` and then re-open the project and try to open the same file again.
