### ISSUE TITLE
Roslyn dependencies out of date

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#20626]
We are 22 days out of date on our ingestion of Roslyn dependencies. Currently under investigation.

**Comment by JunTaoLuo** [comment]
Looks like this could be due to our incorrect CPDs in aspnetcore which was set to Extensions.Logging. This may be fixed by https://github.com/dotnet/aspnetcore/pull/20627. Ops should monitor this to ensure the dependency is updated.

**Comment by JunTaoLuo** [comment]
Up to @pranavkm to close.

**Comment by pranavkm** [comment]
Spoke to @JunTaoLuo offline. We've picked up the pre-reqs as part of https://github.com/dotnet/aspnetcore/pull/20634, waiting for an official build to succeed before this issue can be closed.

**Comment by Pilchie** [comment]
:eyes:

**Comment by NTaylorMullen** [comment]
This looks to be fixed 5 days ago by https://github.com/dotnet/aspnetcore/commit/b29f1fa5eafb25dd6cf3947cc645b2e1c375f3fc

We also more recently took an update 2 hours ago: https://github.com/dotnet/aspnetcore/commit/ce85f28672f40ea5a69e509f3d9fc83cf90f5b5e

Closing this out.
