### ISSUE TITLE
Build ASP.NET Core apps with VB.Net now

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#20633]
I think we can say that VB.Net finally made it to ASP.NET Core
I published [eShopOnWeb_VB.NET](https://github.com/VBAndCs/eShopOnWeb_VB.NET) which is the VB.NET version of the Microsoft full web sample [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb)
[eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb) is a sample ASP.NET Core reference application, powered by Microsoft, demonstrating a single-process (monolithic) application architecture.
I created a VB.NET version of this app, using [Vazor](https://github.com/VBAndCs/Vazor) and [ZML](https://github.com/VBAndCs/ZML) to design MVC views and Razor Pages, because ASP.NET Core Doesn't provide a razor syntax that supports VB.NET.
I hope VB.NET developers found it helpful, and start creating their web applications targeting ASP.NET Core 3.1 using VB.NET and Vazor.

Here is [a project and item templates VXIS](https://github.com/VBAndCs/Vazor/blob/master/VazorTemplateSetup.zip?raw=true)
it setups these Vazor templates:
1- A Vazor project template for ASP.NET MVC Core 3.1 .
2- A Vazor project template for ASP.NET Web Pages Core 3.1 .
3- A VazorView item template to add a new vazor view (.vazor and .vbxml.vb files) to the MVC project.
4- A VazorPage item template to add a new vazor page (.cshtml, .cshtml.vb, and .vbxml.vb files) to the Razor Pages project.

And here is a [VSIX installer](https://github.com/VBAndCs/Vazor/blob/master/vbxmlCompletionProviderVSIX.zip?raw=true) to add Html5 AutoComplete in XML to your VS as an extension:
![untitled1](https://user-images.githubusercontent.com/48354902/78731288-9e107280-793f-11ea-8927-db336c28b6f9.jpg)

Give it a try, but notice it provide auto completion for HTML5 in VB.NET XML literals only inside vbxml tags:
```VB.NET
Dim x = <vbxml>
   <!—auto completion for HTML 5 is available here -->
</vbxml>
```

Note: You can press Ctrl+space after `<%` to get this block written for you:
```VB.NET
         <%= (Function()
                    Return < />
              End Function)()
         %>
``` 

where you can write vb conditions to form dynamic HTML parts as you want. You can also use loops but modify the lambda to be `Iterator Function` and `Yield` Html tags as you want.
Refer to [Vazor ReadMe](https://github.com/VBAndCs/Vazor/blob/master/README.md) for more details.

@reduckted @muratg @tb-mtg @brunojuliao @rynowak @CheungTatMing @VBDotNetCoder @simonmilne80 @NatShaw @SrqComputerguy @sreenathGanga1988 @mcurros @filippobottega @mrjohnr @beefydog @mevdschee @Baner041986 @hannespreishuber @Webbarrr @Gruski @hishamco
I think you could be interested in this, since https://github.com/dotnet/aspnetcore/issues/2738.

**Comment by hishamco** [comment]
@VBAndCs great work, I already start to build a Razor version for VB long time back, after awhile I saw your contribution for Vazor

Can we chat together will all the devs interested in VB.NET to see the best of the both approaches: Razor & XML literals and create an OSS suited for all VB developers

**Comment by VBAndCs** [comment]
@hishamco 
Thanks. Maybe we can discuss this here https://gitter.im/VB-NET/community?source=orgpage

**Comment by danroth27** [comment]
@VBAndCs Thanks for sharing this with the community! Since there isn't any product work being tracked by this issue I'm going to go ahead and close it, but feel free to continue the discussion on Gitter.

**Comment by VBAndCs** [comment]
I told the whole Vazor story here: https://github.com/VBAndCs/Vazor/blob/master/A-Vazor-story.md
And here is a short version in an article in Visual Studio Magazine:
https://visualstudiomagazine.com/articles/2020/04/10/vbnet-aspnetcore.aspx
