### ISSUE TITLE
VS project.razor.json serialization race conditions

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#20632]
Because of the size of the project.razor.json files we create when they are written to disk its handled as two different operations, so the FileSystemWatcher triggers twice. The first time it triggers theres a good chance that the json has not finished writing out to the file, so it will fail to deserialize and cause lots of trouble.

The solution we (Taylor) came up with is to write our project.razor.json's out as a temp file, then when its done delete the old file and rename the temp to non-temp. This DOES mean we'll have to make the piece on the language server side resilient by having like a 250ms buffer on updating project state after a project.razor.json change.

**Comment by NTaylorMullen** [comment]
This completed?

**Comment by ryanbrandenburg** [comment]
https://github.com/dotnet/aspnetcore-tooling/pull/1777
