### ISSUE TITLE
Blazor UseBlazorFrameworkFiles and IFileProvider 

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#20642]
### Is your feature request related to a problem? Please describe.
I have multiple blazor SPA's referenced from the aspnet core host. I need to conditionally serve up the correct blazor SPA on the root request path "/" based on who the tenant is (determined by the URL).

I could do this in 3.2 preview 1 by configuring the tenant specific fork of the middleware pipeline to serve that tenants blazor spa files only:

```
if(isTenantA)
{
     app.UseClientSideBlazorFiles<ClientA.Program>() 
    /// stuff 
    endpoints.MapFallbackToClientSideBlazor<ClientA.Program>("index.html") 
    
}
else
{
     app.UseClientSideBlazorFiles<ClientB.Program>() 
    /// stuff 
    endpoints.MapFallbackToClientSideBlazor<ClientB.Program>("index.html") 
}

```

However with 3.2 preview 2 and the move to static files this has proved to be not so easy. Firstly - all referenced SPA's are being served on their static asset base paths automatically - you can't pick and chose to only serve one of the other based on the tenant. To resolve this first problem i have already raised "#20605 - don't serve static assets in directories prefixed with dot". However even with that in place, I then need the ability to set up middleware to serve just a particular SPA - so that I can fork the middleware pipeline per tenant, and each tenant can have this middleware serve them there SPA.

The first issue I hit was that `UseBlazorFrameworkFiles` doesn't allow me to pass in a particular IFileProvider - instead UseBlazorFrameworkFiles is coupled to the Environment.WebRootFileProvider - so it basically means all SPA's must be resolvable by the `Environment.WebRootFileProvider` - in my case I want only some SPA's to be visible to particular tenants, so having them all resolvable via the `Environment.WebRootFileProvider` doesn't really work.

Here is the code I needed to serve up just a particular SPA on a particular path "/" in an isolated fashion (i.e IWebHostEnvironment.WebRootFileProvider cannot resolve these files as they are published to hidden" directories)

``` csharp
                IFileProvider staticFileProvider = spa.FileProvider; // I built this to point to SPA content in the "hidden" folder.
                var basePathPrefix = "/"; // the path you want to serve the SPA static content on. This may be different than the StaticAssetBasePath because multiple different SPA's must have different StaticAssetBasePath but you might want to serve any of them up on the root "/" based on who the tenant is.
               
                    // We have to serve blazor _framework static content up with special options.
                    c.MapWhen(ctx => IsBlazorFrameworkFileRequest(basePathPrefix, ctx), subBuilder =>
                    {                        
                        StaticFileOptions options = GetBlazorFrameworkStaticFileOptions(tenantDefaultSpa);
                        subBuilder.UseMiddleware<ContentEncodingNegotiator>(staticFileProvider);
                        subBuilder.UseStaticFiles(options);
                    });              

                // now serve non blazor framework specific content using ordinary options.
                var spaFileOptions = new StaticFileOptions() { FileProvider = staticFileProvider };
                c.UseStaticFiles(spaFileOptions);

```

Note: The entire `MapWhen()` portion was copied from the internals of `UseBlazorFrameworkFiles()` but modified to allow me to pass the `IFileProvider` around instead of using `Environment.WebRootFileProvider.` everywhere.

Note also that I am serving "_framework" files for _framework requests, and if not a "_framework" request, i'm serving the SPA's file using ordinary static options - this handles serving the whole of a blazor application. It would be helpful in my view if this logic was just wrapped up into a single higher level `UseBlazorSpa()` method that combines all the necessaries to just serve a particular blazor SPA.

### Describe the solution you'd like
I'd like to see at minimum:

- UseBlazorFrameworkFiles accept an optional IFileProvider as a parameter (that it also passes to `ContentEncodingNegotiator` etc) to allow using a specific IFileProvider to serve specific SPA content, as opposed to what it does now which is only use IWebHostEnvironment.WebRootFileProvider.

However for ease of use, it would also be good to have:

 - UseBlazorSpa(baseRequestPath, staticAssetsBasePath)
 - UseBlazorSpa(baseRequestPath, fileProvider)

which would do the following for you:

1. Construct an IFileProvider (if one not provided) to serve **only the SPA with the specified static asset base path**
    - In development environments, uses the static assets mappings xml file, in non development, resolves relative to the webroot directory.
2. Does what UseBlazorFrameworkFiles() does, but uses the specified file provider to only serve "_framework" files from that SPA using `MapWhen` to detect _framework requests and configuring StaticFileMiddleware appropriately.
3. Does UseStaticFiles() as I have shown above to serve the "oridinary" (non _framework) files for the SPA using the specified IFileProvider.

This would make serving a blazor SPA up as simple as:

```
appBuilder.UseBlazorSpa("/", "./apps/welcome-app");

```
- The first argument is the base request path to serve the SPA on - this allows it to be different from the static asset path which is something I don't think the current API's enable but is super useful.
- The second argument corresponds to the `<StaticWebAssetBasePath>./apps/welcome-app</StaticWebAssetBasePath>` in the client csproj.

it would be easy to fork the middleware pipleline to serve different apps to different tenants.
In conjunction with #20605 which allows referenced SPA projects to be hidden from being served by default this would be quite a cool feature and gets us back to what we could achieve in preview 1 but I think in a nicer way.

**Comment by javiercn** [comment]
Sorry, I'm failing to understand why we need all the plumbing that you are asking for. I've created a sample on how to do this that you can check here with a couple of options on how to do this.
Multiple apps:
https://github.com/javiercn/BlazorMultipleApps/blob/05a66d42c024baec7b9701b3eebf5ca8dd6f93b4/BlazorMultipleApps/Server/Startup.cs#L47-L58
Multiple apps using MapWhen
https://github.com/javiercn/BlazorMultipleApps/blob/13cefa97483641e08ee2c1d7eabee186147d4dd3/BlazorMultipleApps/Server/Startup.cs#L47-L71

The first one is the most straightforward one and what I expect most people to use. The second option gives you full control over what files get served when and allows you to literally perform any mapping you can think of.

**Comment by dazinator** [comment]
@javiercn 
Unless I am missing something, neither of those samples address serving the apps on the root path "/".

We use subdomain to distinguish tenants, so tenant A might be "foo.domain:80" and tenant B might be "bar.domain:80".

Is there a way currently to Map SPA1 to "/" for tenant A and SPA2 to "/" for tenant B?

I don't think there is becuase the assumption is that the static assets path, and the request path need to be the same, but that means both tenants can access the other SPA app just by browsing /SPA1 or /SPA2 and nothing will be served up on their root "/"

I am trying to convey here the need to select a different defualt SPA to serve on a tenants root when there are multiple to chose.

And yes.. this is a real life use case, we are building a platform, with multiple tenants, and the SPA we want to serve to the tenant is driven by the tenant type..

Here is a working sample that I have put together that enabled this - I had to change a few methods and copy a lot of the internal classes in to get it to compile:

https://github.com/dazinator/blazor-sample-multi-spa

If i can achieve those today without making any changes then obviously that would be my preferred route, and I'd be greatly appreciative if you could provide any more info!

**Comment by javiercn** [comment]
@dazinator I understand now. You can also do host based maching by updating the path after the match. See https://github.com/javiercn/BlazorMultipleApps/blob/master/BlazorMultipleApps/Server/Startup.cs#L48-L64

**Comment by dazinator** [comment]
Thanks @javiercn - I'll investigate that approach further!
How do I restore your project though as it seems to require preview4 packages which aren't available on my nuget feeds - assume I need to add a nuget feed source?

I think the path re-writing has the potential to uncover other issues - our middleware pipeline is not so straight forward so I am slightly hesitant, hopefully as the duration of the change to the path should be fairly limited in scope, hopefully there won't be any knock on side effects. I'll test to see if I uncover any issues.

I am also curios as to how this impacts the client side HttpClient --> Wont the client side HttpClient be making calls to the backend using its configured basepath e.g "/FirstApp/"? I can then see requests getting re-written to /FirstApp/FirstApp and then the endpoint routing still not matching it up to controllers once it reverts back to /FirstApp/.. - I'll run your sample and experiment.

Saying that, I do like the new API that I ended up with in my sample (perhaps I am biased) that solves this without having to amend the incoming path - I think it feels more intuitive to do this from a consumer perspective:

```
 app.MapWhen(ctx => ctx.Request.Host.Equals("firstApp.com"),
               (app) =>
               {
                   IFileProvider files = app.UseBlazorSpa("/", "FirstApp", Configuration);

                   app.UseRouting();
                   app.UseEndpoints(endpoints =>
                   {
                       endpoints.MapControllers();
                       endpoints.MapFallbackToFile("index.html",
                           new StaticFileOptions() { FileProvider = files });
                   });
               });  
```
Or another way you can do it my sample shows of creating a static asset file provider now seperately which might be useful in its own right:

```

                   / / Shows another way
                   var fileProvider = env.CreateStaticAssetsFileProvider("FirstApp", Configuration, "/"); // new extension method
                   app.UseBlazorSpa("/", fileProvider);  // new extension method - does combination of .UseBlazorFrameworkFiles(); and .UseStaticFiles(); but with the specified StaticAssets file provider.

                   app.UseRouting();
                   app.UseEndpoints(endpoints =>
                   {
                       endpoints.MapControllers();
                       endpoints.MapFallbackToFile("index.html",
                           new StaticFileOptions() { FileProvider = fileProvider });
                   });

```
Unsurprisingly - I like my own approach! (haha) but it came at a cost of copying lots of internal code which I don't like. I'll weigh up the tradeoffs. In the meantime if you could allow more flexibility around this in future so that we can avoid the path changing that would be really good.

**Comment by javiercn** [comment]
> How do I restore your project though as it seems to require preview4 packages which aren't available on my nuget feeds - assume I need to add a nuget feed source?

It should work with preview3 stuff.

I didn't update the base paths of the apps. Those should be "/" on their respectives "index.html" files.

The path rewriting should be fine, if you just undo it after the static files middleware. Routing, controllers, etc would use the original path from "/". I haven't tried E2E the host version, since I don't want to mess with my host files, but I'm pretty confident it should work.

**Comment by dazinator** [comment]
Just a note to say that i[n my enhancements branch](https://github.com/dazinator/blazor-sample-multi-spa/tree/enhancements) I've made some more changes and now all that is required is this:

```csharp
               app.MapWhen(ctx => ctx.Request.Host.Host.Equals("foo.localhost"),
               (app) =>
               {                   
                   app.UseBlazorSpa("/app2", ".private/spa2", Configuration, "/index.html");
               });

```

That's it... that lets you serve any blazor spa (static asset path), on any request path, and optionally enforces the fallback file route in one go. If you don't want the fallback file to be enforced there and then (i.e becuase your app doesnt fully own that URL space and you need to give the server the chance to handle requests in that URL space first, then you don't need to provide the last argument "fallbackFilePath", and you can use endpoint routing as before.

```
app.MapWhen((ctx) =>
            {
                return ctx.Request.Host.Host.Equals("localhost");
            },
                (app) =>
                {
                    var files = app.UseBlazorSpa("/", ".private/spa1", Configuration);

                    app.UseRouting();
                    app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapControllers();
                        endpoints.MapFallbackToFile("index.html",
                            new StaticFileOptions() { FileProvider = files });
                    });
                });

```

I'm so pleased with this that I might package it up into a nuget package. Next on my agenda is to also try the path re-write approach.

**Comment by dazinator** [comment]
@javiercn I'll close this for now as I have two possible resolutions for now. Thanks you.

**Comment by JulioPablo** [comment]
@javiercn  Hey, do you happen to know how I could add the client side blazor app inside a MVC view? In your examples, which are very helpful, you are returning a index.html, previously with the 3.1 preview I had it set up where the blazor app is inside a MVC view, I did this so the auth cookie would remain and also to share the main app's layout, keeping the navigation and so on.

But I'm not sure how I'd do this with preview 3.2 I tried setting it up similar to your example, but it always returned 404 when requesting for the blazor js file.
