### ISSUE TITLE
In a Directory.Build.props file, determine the Sdk value

### ISSUE THREAD

**Issue by kieronlanning** [dotnet/aspnetcore#20649]
In a `Directory.Build.props` file how can I determine if the project has the `Microsoft.NET.Sdk.Web` or the `Microsoft.NET.Sdk` referenced?

Aside from opening the entire file and using some Regex to pull the `Sdk` attribute value out from either the Project element, or an Import element and setting a property, I'm not sure of the best direction to take...

Currently I'm doing this, which isn't an ideal solution:

```
<PropertyGroup>
 <SdkProjectName>$([System.Text.RegularExpressions.Regex]::Match(`$([System.IO.File]::ReadAllText(`$(MSBuildProjectFullPath)`))`, `(?s-i)(?:^|\s|>)(?s-i)(?:^|\s|&gt;)&lt;\s*(?:Project|Import)\s(?:[^&gt;]*?)\s?Sdk\s*=&quot;(?&lt;sdkproj&gt;.*?)&quot;`).Groups['sdkproj'].Value)</SdkProjectName>
</PropertyGroup>    
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275b32fd-9419-e174-6fdf-75a0e8ab3a71
* Version Independent ID: f210fd34-23d8-b573-ce6f-9df02e49d80f
* Content: [ASP.NET Core Web SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/web-sdk?toc=%2Fdotnet%2Fcore%2Ftoc.json&bc=%2Fdotnet%2Fbreadcrumb%2Ftoc.json&view=aspnetcore-3.1)
* Content Source: [aspnetcore/razor-pages/web-sdk.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/web-sdk.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Pilchie** [comment]
This issue was moved to microsoft/msbuild#5255
