### ISSUE TITLE
RemoteAttribute and submit button don't work together in first time

### ISSUE THREAD

**Issue by ardacetinkaya** [dotnet/aspnetcore#20645]
I have a strange issue that I could not understand the reason.

I have an MVC application with some models. One of my view model has Remote data attribute in one property to do remote validation

```   
public class UserViewModel
{
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "E-Mail Address")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name = "Age")]
        [Remote("AgeControl", "Home",
            ErrorMessage = "Invalid age",
            HttpMethod = "post"
            )]
        public int Age { get; set; }
}
```
In my controller, there is suitable post action;

```    
        [HttpPost]
        public async Task<IActionResult> AgeControl(int Age, CancellationToken cancellationToken)
        {
            if (Age > 10 && Age < 20)
            {
                return new JsonResult(true);
            }

            return new JsonResult(false);
        }
```

Also I have a form which posts the view model, when I first click the button, just Remote validation post works with Valid state. But my exact post action does not fire. After a second click, my exact post action works.

If I remove the just Remote attribute, my exact post action works.

It seems that remote data attribute for validation prevents posts.

**Comment by dazinator** [comment]
Im no expert, not used Remote validation, but just a guess as I can't see your routing setup, but could it be that your [HttpPost] attribute needs a route template e.g. 
`[HttpPost("AgeControl")]` ?

**Comment by ardacetinkaya** [comment]
My validation action works fine, all my actions work fine. 
The problem is when [Remote] attribute is added to a property of the model, my POST actions does not work in first click of the action button. I have to click second time to post the form.
And this happens when just [Remote] attribute is there else everything works fine as it should be...

**Comment by ardacetinkaya** [comment]
And this is the simplest information output when I first click the submit button of my form. My form's submit does not fire in first, just the remote validation post.


```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'XXXXX.MyController.AgeControl (XXXXX.WWW)'

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "AgeControl", controller = "LandingPage", area = "", page = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult AgeControl(System.Guid, System.String) on controller XXXXX.MyController (XXXXX.WWW).

info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method XXXXX.MyController.AgeControl (XXXXX.WWW) - Validation state: Valid

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method XXXXX.MyController.AgeControl (XXXXX.WWW), returned result Microsoft.AspNetCore.Mvc.JsonResult in 214.3261ms.

info: Microsoft.AspNetCore.Mvc.NewtonsoftJson.NewtonsoftJsonResultExecutor[1]
      Executing JsonResult, writing value of type 'System.Boolean'.

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action XXXXX.MyController.AgeControl (XXXXX.WWW) in 242.1156ms

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'XXXXX.MyController.AgeControl (XXXXX.WWW)'

info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 259.8989ms 200 application/json; charset=utf-8
```

**Comment by dazinator** [comment]
I'm guessing still, but maybe something to do with the form edit context starting invalid, on first click the validation attribute has to run to check validity of the form before it can be posted - so it posts to validation endpoint. On second click, form has been validated, so it bypasses another remote validation check, and now posts to the actual form data.

Are you able to share the markup of your form? Does your controller have any other methods? (You have only shown the validation one, what about the submit one?)

**Comment by ardacetinkaya** [comment]
It is just a simple form.

```
       <form id="details" asp-action="Index">
                <div class="panel panel-default">
                    <h6 class=" text-uppercase">User Info</h6>
                    <hr class="dotted">
                    <div class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.Name)
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>

                        </dd>
                    </div>
                    <div class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.Email)
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </dd>
                    </div>
                    <div class="row">
                        <dt class="col-sm-3">
                            @Html.DisplayNameFor(model => model.Age)
                        </dt>
                        <dd class="col-sm-9">
                            @Html.DisplayFor(model => model.Age)
                            <input asp-for="Age" class="form-control" />
                            <span asp-validation-for="Age" class="text-danger"></span>
                        </dd>
                    </div>


                </div>
            </form>
        <div class="text-right">
            <input type="submit" form="details" id="btnsave"
                   value="Save" name="submit"
                   class="btn btn-primary" />

            <input type="submit" form="details" id="btnsubmit"
                   value="Submit" name="submit"
                   class="btn btn-primary" />
        </div>
```

And also my form's main POST action as follows;

```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(UserViewModel model, string submit, CancellationToken cancellationToken)
        {
			...................
			............
			......
			....
	}
```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by fbessone** [comment]
I had the same issue: when using RemoteAttribute my form had to be submitted twice because the first submit ended in Remote Validation method with no post.

In my case i had this submit button code:
`<button class="btn btn-primary" type="submit" name="submit">Modify</button>`

when i removed the name="submit" code it started working

`<button class="btn btn-primary" type="submit">Modify</button>`

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
