### ISSUE TITLE
IDX20803 error with multiple authentication schemes

### ISSUE THREAD

**Issue by qkhanhpro** [dotnet/aspnetcore#20643]
### Describe the bug
Following this documentation https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.1 , I would like to enable multiple authority for a single controller so I added 2 Jwt bearer schemes and follow the document

    services.AddAuthorization(options =>
    {
        var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(
            JwtBearerDefaults.AuthenticationScheme,
            "AnotherJwtBearerScheme");
        defaultAuthorizationPolicyBuilder = 
            defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
        options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
    });

### To Reproduce
Kill one of the two authorities, call controller with the JWT issued from the remaining authority.

Got Exceptions? Include both the message and the stack trace
IDX20803: Unable to obtain configuration from  [the-offline-authority]/.well-known/openid-configuration'

### Expected result
From the docs, "The controller then accepts requests with JWT issued by the first or second issuer". Which leaves me confused. Why is it required that all the authorities to be online or the whole operation fail? - is there any way around this?

### Further technical details
- Include the output of `dotnet --info`
Host (useful for support):
  Version: 2.1.15
  Commit:  d43032d4d9

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by Tratcher** [comment]
You're right, we assume the identity providers are stable resources. You should be able to suppress the failure by hooking into the event JwtBearerOptions.Events.OnAuthenticationFailed and returning NoResult.
https://github.com/dotnet/aspnetcore/blob/200f2c49be19b16e205b6744ae6791d11739fe7f/src/Security/Authentication/test/JwtBearerTests.cs#L602-L612

**Comment by qkhanhpro** [comment]
Thanks, @Tratcher It works nicely.
In my case, as I used options.JwtBearerEvents as I have been using AddIdentityServerAuthentication

**Comment by qkhanhpro** [comment]
@Tratcher I have a question on how to intercept only the IDX20803 error
Currently I am throwing the exception in the "else". Do you think that is safe for the normal flow?"

`OnAuthenticationFailed = (context) =>
                        {
                            if (context?.Exception?.Message != null && context.Exception.Message.StartsWith("IDX20803"))
                            {
                                context.NoResult();
                                return Task.FromResult(0);
                            }
                            else
                            {
                                throw context.Exception;
                            }
                        }`

**Comment by Tratcher** [comment]
No need for the else block, that's the default behavior if you don't call NoResult.
