### ISSUE TITLE
WS-Federation not working with .Net Core 3.1

### ISSUE THREAD

**Issue by wmmihaa** [dotnet/aspnetcore#20644]
### Describe the bug
We're migrating a ASP.net Framework (4.8) MVC app to .Net Core 3.1. The application is using WsFederation configured to use ADFS or AAD to route back the user to /account/ExternalLoginCallback. In the callback claims are fetched to populate a model and lastly redirected to /account/ExternalLoginConfirmation after which the user is created in our database (which we need).

We are redirected to the *ExternalLoginCallback*, but are unable to process the request as the ```AuthenticateResult:Succeeded``` is false and  ```ExternalLoginInfo``` is null. Looking through the entire HttpContext, I can see no cookies or headers related to the user.

## IMPORTANT
All settings are the same as with our .Net Framework web application, and we're using the same federation service!

```C#
public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
{
    var result = await HttpContext.AuthenticateAsync(IdentityConstants.ExternalScheme);  
    // result.Succeeded=> false  

   var info = await signInManager.GetExternalLoginInfoAsync(); 
    // info is null
//..
}.
```
We configure the WSFed in the ConfigureServices as:
```C#
var authServices = services.AddAuthentication();
authServices.AddWsFederation(externalLoginProvider.Domain, options =>
{
    options.Wtrealm = "api://9a6affaf-cbed-441c-a2c8-xxxxxxxxxxxxx";
    options.MetadataAddress = "https://login.microsoftonline.com/........";
    options.Wreply = "https://localhost:44390/Account/ExternalLoginCallback/Axians";
});

authServices.AddCookie();
```

### Further technical details
- ASP.NET Core version : **3.1**
- VS 2019

**Comment by blowdart** [comment]
@Tratcher

**Comment by Tratcher** [comment]
Wreply should not refer to a controller, it should refer to a unique path handled by the auth middleware like "https://localhost:44390/signin-wsfed". You'll be redirected to the ExternalLoginCallback after the auth middleware has processed the wsfed response and generated the IdentityConstants.ExternalScheme cookie.

ASP.NET Core's implementation is stricter about this than the ASP.NET one was.

**Comment by wmmihaa** [comment]
So what tells the middleware to redirect to ExternalLoginCallback?

BTW...I cannot tell you how thankful I am for your reply... I've been banging my head for days!

**Comment by wmmihaa** [comment]
Never mind the last comment

**Comment by wmmihaa** [comment]
I have progress now...
good news is my AuthenticateResult now comes back successfully, however the *GetExternalLoginInfoAsync* still results null :(

**Comment by Tratcher** [comment]
Can you give us a more complete view of your Startup class and Account controller?

@HaoK

**Comment by wmmihaa** [comment]
Everything works beautifully now. Again thank you @Tratcher.
