### ISSUE TITLE
Auto-closing HTML elements in cloud scenarios doesn't modify guests cursor position to be inbetween tags.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20651]
Our initial design for auto-closing tags doesn't work on LiveShare guests because all of our client / middlelayer logic only controls the host's cursor and the guest has one of their own. I talked to the LiveShare folks on ways to control the guest cursor but there's nothing officially supported without running logic on the client.

I was thinking we could detect cloud scenarios, attach to TextBuffers on the guest and then on seeing a `>` edit followed by another edit that starts with a `<` we could automagically move the cursor on the guest. I imagine it'd be infrequent that a user would type `><` outside of tag auto-complete. This approach wouldn't enable attribute and comment auto-completion but it'd at least get our tag auto-closing behavior working for guests.

The long term fix for this is to have the editor support snippets in OnTypeFormatting. That's highly unlikely to land "soon".

@ToddGrun / @ajaybhargavb thoughts?

**Comment by ajaybhargavb** [comment]
Interesting. What happens in the guest when the host starts typing after auto-closing happens?
`<div>host types here|</div>`

Does the guest now show this?
`<div></div>host types here|`

**Comment by NTaylorMullen** [comment]
Talked offline. The gist is that LiveShare diffs host/guest buffers and synchronizes them to allow the host/guest to simultaneously edit the same doc. Now in our language server client code we have special handling of OnTypeFormatting where we return 0 text edits and Apply our own and then move the cursor. The issue is that the "move the cursor" part only moves the hosts cursor so the guests is left at the end of the `</div>`
