### ISSUE TITLE
memory leak of BufferSegment in AspNetCore.SignalR.Client

### ISSUE THREAD

**Issue by BrannonKing** [dotnet/aspnetcore#20654]
Minimal example:
[SignalRPerformance.zip](https://github.com/dotnet/aspnetcore/files/4452750/SignalRPerformance.zip)

### Describe the bug
The attached file demonstrates an issue where the client code continually slows and leaks large amounts of memory. The memory leak is not slow. This is using .NET Core 3.1 out-of-the-box SignalR for the server. There's no leak on the server. The client is using Microsoft.AspNetCore.SignalR.Client 3.1.3.

### To Reproduce
Compile the two attached projects. Run the server followed by the client. Observe that the times on the client continually slow and that its memory continually increases.

An image of the profiler data from VS2019:
![leak](https://user-images.githubusercontent.com/1509322/78833502-39d6c880-79aa-11ea-9124-158c2662a5be.png)

**Comment by davidfowl** [comment]
This leak is client side?

**Comment by BrannonKing** [comment]
Trying to capture the allocation stack from the profiler:
![image](https://user-images.githubusercontent.com/1509322/78857283-3103e800-79e6-11ea-8d0e-25411e989221.png)

**Comment by BrannonKing** [comment]
One more:
![image](https://user-images.githubusercontent.com/1509322/78857434-a1ab0480-79e6-11ea-83f2-7b43088f9466.png)

**Comment by BrannonKing** [comment]
It still looks like it's the self-referential BufferSegment::Next that is the problem. Somehow we get a buffer loop. 

While you're working on BufferSegment, here's some commentary on that: there's no need for the `_next` field nor is there any need for the `NextSegment` property. Just use the property on the base class. The public setter on `NextSegment` is a violation of the encapsulation principle; you're clearly relying on the `SetNext` method to maintain the encapsulation there.

**Comment by BrannonKing** [comment]
One other thing to look at here: I can get the client-to-server calls in sub-millisecond times. However, the response from the server takes much longer than that. It shouldn't take that long; it shouldn't be so asymmetrical. (That's what the DIFF output in the attached test project was attempting to measure.)

**Comment by davidfowl** [comment]
There’s no issue with buffersegment it’s a linked list node. It’s designed in that strange way for performance reasons. It’s likely there’s an issue with a lack of back pressure being applied on the client side

**Comment by BrennanConroy** [comment]
> It’s likely there’s an issue with a lack of back pressure being applied on the client side

https://github.com/dotnet/aspnetcore/issues/17797

**Comment by BrannonKing** [comment]
If it was a backpressure issue than calling `GC.Collect` on the client should make the symptoms disappear. Doing so does not correct the leak although it does slow the leak from 20MB/s down to 10MB/s. (It could be that it just slows the entire process down.)

If it was an issue with the number of items in the cache, then the memory profiler data would show that the BufferSegment root was the cache container. That's not what the data show. The data shows that the BufferSegments kept in memory are all rooted by other BufferSegments. 

If the BufferSegments in RAM were all one chain, it would mean a chain of 20k BufferSegments after just 20 seconds of runtime. That's an 82MB chain but I have no transfers larger than 16KB. It's not just an 82MB chain, though, as the memory profiler shows that the inclusive size of many instances is over 100MB each. 

Please take a look at the sample. It demonstrates that the C# SignalR client is completely unusable. It's preventing me from moving my SignalR application from v2 to v3.

![image](https://user-images.githubusercontent.com/1509322/78900358-f9bc2800-7a33-11ea-8ad0-03a72a31f5cd.png)

**Comment by davidfowl** [comment]
> If it was a backpressure issue then calling GC.Collect on the client should make the symptoms disappear. Doing so does not correct the leak although it does slow the leak from 20MB/s down to 10MB/s. (It could be that it just slows the entire process down.)

It wouldn't. My guess is (and I haven't looked closely enough as yet) that the client just has all the memory backed up trying to process messages as fast as it can and the server is overwhelming it. Your code is doing a tight loop on the server side blasting out 4000 integers . The client can't keep up but we're allocating data and accepting more data from the server side and as a result the memory is backed up.

That's my current assessment of the above situation from looking at the code and knowing how the client works.

> Please take a look at the sample. It demonstrates that the C# SignalR client is completely unusable. It's preventing me from moving my SignalR application from v2 to v3.

I'll take that as feedback. We'll try to get this fixed quickly and patched to the existing 3.x client. 

I have to ask some questions though:
- Are you really sending that quickly from you server application or was this just a stress test? Does it represent your real traffic pattern?
- When you say move from v2 to v3 are you talking about .NET Framework SignalR to ASP.NET Core SignalR or from ASP.NET Core SignalR 2.x to 3.x?

In the .NET Framework version of SignalR, messages would just be dropped on the server side without notification if you were sending this fast. That's a bit different here in ASP.NET Core SignalR as things will be sent to clients directly and not stored on the server but as a result, things can back up.

@BrennanConroy do we have a similar example in our performance infrastructure today and are we measuring client memory? If not this is something we need to add.

**Comment by BrannonKing** [comment]
Thanks for the response; now we're making some progress! I like this theory that the client can't keep up.

My real server load is 200 of those large messages per second. The company has given me a goal to get it up to 1000. That gives me an opening for ~1ms of sleep. Amazingly enough, adding the 1ms of sleep after the SendAsync on the server allows this test client to keep up.

To reach my goal of 1000, I am looking to move from .NET Framework SignalR v2 to ASP.NET Core SignalR 2.x to 3.1+. 

The server is doing more processing than the client. The server is using two threads. If the server can send data faster than the client can process, then that means that the client must only be using one thread. Is that true? Do we invoke the `On(...)` handlers onto the thread that created them?

It would be useful for the client to expose some way to know that it's falling behind. I'd like the ability to specify that, for certain messages, I only care about the latest one, that we can drop all the messages in the middle. 

It would also be useful for the server to have an option to stall its work if the client is falling too far behind. Does the server have the "invoke" approach or is it only a "send" approach? How do I get my "On" handlers running in their own thread?

**Comment by davidfowl** [comment]
> The server is doing more processing than the client. The server is using two threads. If the server can send data faster than the client can process, then that means that the client must only be using one thread. Is that true? Do we invoke the On(...) handlers onto the thread that created them?

Client are using one "thread of execution" but it isn't single threaded. On handlers are processed sequentially. You can think of it like a queue of operations that fire one after the other. This it to prevent unintentional overlapping, you can obviously opt into that behavior yourself by using Task.Run within your handler.

> It would be useful for the client to expose some way to know that it's falling behind. I'd like the ability to specify that, for certain messages, I only care about the latest one, that we can drop all the messages in the middle.

I'd rather not add that level of control, you never had it in the old SignalR (which was much worse when it comes to dropping as you would never know). Messages all come over the same socket/pipe to a client and then they are dispatched to various On handlers sequentially. If can see a couple of options to improve things here:
1. What @BrennanConroy mentioned [here](https://github.com/dotnet/aspnetcore/issues/20654#issuecomment-611345256). Expose a knob to let consumers decide how much memory it can before it starts to aggressively throttle incoming data. Today there's no throttle and things can back up significantly as a result. This buffering also happens at the socket level not at the message level so there's no logical way at this point in the pipeline to determine what invocations to keep/drop etc.
1. We can expose an alternative pull model for more advanced scenarios where you can get an IAsyncEnumerable\<T\> for incoming messages. That would let the consumer decide the rate of messages.

The really nice thing about getting back pressure "right" is that once your handler is responsible for "releasing" backpressure, you can decide what to drop and what not to drop with a little indirection. 

> It would also be useful for the server to have an option to stall its work if the client is falling too far behind. 

That has other implications (like bad clients having the ability to stop sends to good clients).

> How do I get my "On" handlers running in their own thread?

Just Task.Run in your callback. that'll en-queue to the execution of your callback to the thread pool but it won't wait on the execution of the callback to dequeue another work item.

Here are 2 examples of how that would work:

Process all messages but fire and forget processing of the messages. This has unbounded uncontrolled growth (basically delegating to the thread pool for execution). It can also process messages out of order.

```C#
long dataReceived = 0;
int[] forSending = new int[400];
var listener = connection.On<int[]>("EatData", data =>
{
    Task.Run(() =>
    {
        Interlocked.Add(ref dataReceived, data.Length * sizeof(int));
        Buffer.BlockCopy(data, 0, forSending, 0, forSending.Length); // don't care if it's thread safe
    });

    return Task.CompletedTask;
});
```

This is a recipe for dropping messages using the new [System.Threading.Channels](https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/) in conjunction with SignalR.

```C#
var channel = Channel.CreateBounded<int[]>(new BoundedChannelOptions(5)
{
    FullMode = BoundedChannelFullMode.DropOldest
});

using var listener = connection.On<int[]>("EatData", data => channel.Writer.WriteAsync(data).AsTask());

await foreach (var data in channel.Reader.ReadAllAsync())
{
    Interlocked.Add(ref dataReceived, data.Length * sizeof(int));
    Buffer.BlockCopy(data, 0, forSending, 0, forSending.Length); // don't care if it's thread safe
}
```

**Comment by BrannonKing** [comment]
Thank you for the great explanation and examples. I agree with your sentiment that a client should not be able to stall the server (with the out-of-the-box experience).

I do think that it would be useful for the data handlers to know how many messages are queued up somehow. I think that's true for both the server and client. It could be done as optional extra parameters on the client or as a field in the server context.

The BoundedChannel stuff is interesting. It's similar to a project I wrote a few years ago named Kts.ActorsLite. Kts.ActorsLite also has a "most recent only" queue that would work well for my telemetry over SignalR.

**Comment by davidfowl** [comment]
@BrennanConroy lets get this fixed as part of .NET 5 and potentially backproted to 3.1 (maybe with a default for the threshold)

**Comment by davidfowl** [comment]
Oops, its being tracked
