### ISSUE TITLE
[Razor] DefaultVisualStudioMacDocumentInfoProvider must set DocumentInfo.Folders to non-null

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/aspnetcore#20663]
VSMac is seeing a nullref here:
http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/DocumentInfo.cs,254

The problem is here:
https://github.com/dotnet/aspnetcore-tooling/blob/3d5f76c18eca38a56ad16611f7768b81a1617789/src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioMacDocumentInfoFactory.cs#L41

The temporary fix is here:
https://github.com/KirillOsenkov/AspNetCore-Tooling/commit/66e53f857243bf1df6fdb2c26d17cf42620ee63e

We should probably bump Roslyn to a newer version, and it will include better overloads provided by @tmat

**Comment by NTaylorMullen** [comment]
Temporary fix for this is in. Waiting for a Roslyn build to get the "proper" fix for this.

**Comment by NTaylorMullen** [comment]
Actually I worked around the "proper" fix here: https://github.com/dotnet/aspnetcore-tooling/pull/1655. Closing this out.
