### ISSUE TITLE
[Blazor] Parameter and refresh problem

### ISSUE THREAD

**Issue by clintnetwork** [dotnet/aspnetcore#20664]
Hi,

I do this simple page, it works but after a refresh the page is blank!

Any idea guys?

```razor
@page "/support/ticket/{Id:guid}"

@Id

@code
{
	[Parameter]
	public Guid Id { get; set; }
}
```

Edit: I'm actually in this mode.
```razor
<component type="typeof(App)" render-mode="Server" />
```

Kind regards

**Comment by clintnetwork** [comment]
And also have a problem with `EditForm`!

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
