### ISSUE TITLE
[Blazor] EditForm and Parameters

### ISSUE THREAD

**Issue by clintnetwork** [dotnet/aspnetcore#20666]
Hi,

I create an `EditForm` in a page with a `[Parameter]` and I get an error `400` when I submit the form.

The problem seems to happen when the route contains a slash, by example `/support/submit" the form submission does not works.

Kind regards

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by clintnetwork** [comment]
Yes, I will try to do that!
