### ISSUE TITLE
[QUESTION] Memory Usage

### ISSUE THREAD

**Issue by vitidev** [dotnet/aspnetcore#20675]
Memory usage of 'hello world' application. Empty asp.net application with minimal startup and stub controller (Sdk="Microsoft.NET.Sdk.Web)

![Image 2](https://user-images.githubusercontent.com/2243958/78886857-8e8c4900-7a67-11ea-876b-63eeefc50f59.png)

But if we replace csproj with this content 

    <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp3.1</TargetFramework>
        </PropertyGroup>
        <ItemGroup>
          <PackageReference Include="Microsoft.AspNetCore.Owin" Version="3.1.3" />
        </ItemGroup>
     </Project>

it will be like that
![Image 4](https://user-images.githubusercontent.com/2243958/78887148-065a7380-7a68-11ea-8ff0-bae2019827fc.png)

Why the second variant consumes less memory? in both cases the kestrel is used, and in the second case an additional wrapper?

**Comment by javiercn** [comment]
@vitidev thanks for contacting us.

In the first case you are referencing the asp.net core shared framework, while in the second you are referencing probably the bare minimum set of things that make the app work.

**Comment by javiercn** [comment]
@halter73 or @Tratcher in case they want to add anything.

**Comment by vitidev** [comment]
@javiercn I do not see the difference. everything is available 
![изображение](https://user-images.githubusercontent.com/2243958/78891611-92709900-7a70-11ea-9e47-ac25101d38de.png)

also if check  AppDomain.CurrentDomain.GetAssemblies(); - is almost identical (in owin varian +1 additional package "Microsoft.AspNetCore.Server.Kestrel")

**Comment by davidfowl** [comment]
It's nothing to do with the shared framework, but everything to do with how the garbage collector is configured by default for Server vs Non-Server projects. When you pick the Web SDK it turns on ServerGC, which will use more memory by default but has much better performance characteristics.

You can read more it here https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals

There have also been improvements made in this area:
https://devblogs.microsoft.com/dotnet/middle-ground-between-server-and-workstation-gc/
