### ISSUE TITLE
QueryHelpers

### ISSUE THREAD

**Issue by clintnetwork** [dotnet/aspnetcore#20671]
Hi,

I use ParseQuery to get queries from the query string.
```csharp
var query = QueryHelpers.ParseQuery("/ticket-details/?ticket=8DE473F6-3DC6-4002-BE0F-EC4CE20445D81");
```

And I get this, I think it's a problem if this library does not parse correctly

```json
{
  "/ticket-details/?ticket": [
    "8DE473F6-3DC6-4002-BE0F-EC4CE20445D81"
  ]
}
```

Best regards

**Comment by davidfowl** [comment]
QueryHelpers.ParseQuery taks a query string, not a path an a querystring:

```C#
var query = QueryHelpers.ParseQuery("?ticket=8DE473F6-3DC6-4002-BE0F-EC4CE20445D81");
```

See the doc comment (as small as it is):

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.queryhelpers.parsequery?view=aspnetcore-3.1

> The raw query string value, with or without the leading '?'.

**Comment by clintnetwork** [comment]
Oh yeah my bad, however maybe it could be great to parse the complete URI if it's passed?

**Comment by davidfowl** [comment]
That would be a different API,  you can use URI to parse the url then get the query part and pass it in here

**Comment by claudiogodoy99** [comment]
you can use [FromQuery] in your endpoint controller, like this:
```
[HttpGet()]
public IActionResult Get([FromQuery(Name = "page")] string page)

```

https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1
