### ISSUE TITLE
Blazor ASP.NET Server: how to listen all IPs?

### ISSUE THREAD

**Issue by win32nipuh** [dotnet/aspnetcore#20676]
I build a Blazor Web app server, run it on machine but it responds on localhost only, i.e. http://localhost:5000 but does not respond when I query it from an exrternal host http://myhostIP:5000 

This myhostIP pinged ok. FW is off. In VS2019 in the project settings: App URL: https://localhost:5001;http://localhost:5000

But how to configure Blazor Web server to listen (all) hosts IP addresses using appsetings.json without hardcoding?

**Comment by javiercn** [comment]
@win32nipuh thanks for contacting us.

You can use `https://+:5001;http//+:5000` in launchSettings.json to make it listen on any host, or alternatively you can do the same thing by putting `"urls": `https://+:5001;http//+:5000` in appsettings.json (this last one I'm not so sure).

If this doesn't work for you, I'll let some other team member with more expertise on this area answer.

**Comment by win32nipuh** [comment]
> @win32nipuh thanks for contacting us.
> 
> You can use `https://+:5001;http//+:5000` in launchSettings.json to make it listen on any host, or alternatively you can do the same thing by putting `"urls": `https://+:5001;http//+:5000` in appsettings.json (this last one I'm not so sure).
> 
> If this doesn't work for you, I'll let some other team member with more expertise on this area answer.

I use as you wrote (https://+:5001;http//+:5000 in launchSettings.json) it but when I run the VS with  the server it writes me:  "Invalid URI: the hostname could not be parsed".

**Comment by davidfowl** [comment]
> but again to my question: I provide the app to user, how and where user can change settings to modify/listen ips or ports?

That's really up to you. You can read custom configuration and set the appropriate URLs or hard code a URL into the application itself.

**Comment by Oleg26Dev** [comment]
> > but again to my question: I provide the app to user, how and where user can change settings to modify/listen ips or ports?
> 
> That's really up to you. You can read custom configuration and set the appropriate URLs or hard code a URL into the application itself.

Ok, I can read the config, but how to set urls in an app?

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1#override-configuration

- https://andrewlock.net/5-ways-to-set-the-urls-for-an-aspnetcore-app/
- https://josephwoodward.co.uk/2017/02/many-different-ways-specifying-host-port-asp-net-core

**Comment by Oleg26Dev** [comment]
Thank you David

**Comment by Oleg26Dev** [comment]
I have tried to configure host:port without hardcoding, but the Blazor server-side app does not start in this case?

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.UseStartup<Startup>()
        .UseUrls(urls: new String[] { "http://*:6000", "https://localhost:6001" });
    });
```
If I remove the call .UseUrls(urls: new String[] { "http://*:6000", "https://localhost:6001" }); it starts . What is wrong? I see a console only with output but browser does not start

Microsoft.Hosting.Lifetime: Information: Now listening on: http://[::]:6000 Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:6001 Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down. Microsoft.Hosting.Lifetime: Information: Hosting environment: Development Microsoft.Hosting.Lifetime: Information: Content root path: ... Microsoft.Hosting.Lifetime: Information: Application is shutting down...

**Comment by davidfowl** [comment]
I believe 6000 is a reserved port. Try another one

**Comment by jsalichos** [comment]
> I have tried to configure host:port without hardcoding, but the Blazor server-side app does not start in this case?
> 
> ```
> public class Program
> {
>     public static void Main(string[] args)
>     {
>         CreateHostBuilder(args).Build().Run();
>     }
> 
>     public static IHostBuilder CreateHostBuilder(string[] args) =>
>     Host.CreateDefaultBuilder(args)
>     .ConfigureWebHostDefaults(webBuilder =>
>     {
>         webBuilder.UseStartup<Startup>()
>         .UseUrls(urls: new String[] { "http://*:6000", "https://localhost:6001" });
>     });
> ```
> 
> If I remove the call .UseUrls(urls: new String[] { "http://*:6000", "https://localhost:6001" }); it starts . What is wrong? I see a console only with output but browser does not start
> 
> Microsoft.Hosting.Lifetime: Information: Now listening on: http://[::]:6000 Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:6001 Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down. Microsoft.Hosting.Lifetime: Information: Hosting environment: Development Microsoft.Hosting.Lifetime: Information: Content root path: ... Microsoft.Hosting.Lifetime: Information: Application is shutting down...

Same excact problem here!

**Comment by davidfowl** [comment]
@jsalichos what's that, the port? Change it...

**Comment by jsalichos** [comment]
My mistake thank you. Actually I though it didn't work becouse I watched the console logging were I was expecting a task to give information about the background work it does. 
As soon as I hit the page, everything went as expected!
