### ISSUE TITLE
tag-helper should add "pattern" attribute when bound to a RegularExpression property

### ISSUE THREAD

**Issue by carlin-q-scott** [dotnet/aspnetcore#20681]
### Describe the solution you'd like
When I add a RegularExpression attribute to a model property, I'd like the tag-helper that is bound to that property to have the pattern attribute set to the regular expression.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to bake into the framework.
You can instead create a new tag helper with such functionality.
