### ISSUE TITLE
Blazor 3.2 preview 3 - debugging connectivity issue+

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#20683]
## Describe the bug
Upgraded my blazor host project from preview 2 to preview 3, and have configured it for web assembly debugging following this:

https://docs.microsoft.com/en-gb/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-3.1#vscode

Howeber upon starting my project I see this error repeat over and over:

```
      Connection id "0HLUSJUOJJNH6" started.
info: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Request starting HTTP/1.1 GET http://localhost:62807/_framework/debug/ws-proxy?browser=ws%3A%2F%2Flocalhost%3A49925%2Fdevtools%2Fbrowser%2F88f669fa-1f4c-419f-9b5e-080482834666
verb: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
      All hosts are allowed.
eror: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request.System.IO.FileNotFoundException: Cannot start debug proxy because it cannot be found at 'C:\Users\DarrellTunnell\source\repos\Foo\src\Foo.Server\bin\Debug\netcoreapp3.1\BlazorDebugProxy\Microsoft.AspNetCore.Components.WebAssembly.DebugProxy.dll'
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LocateDebugProxyExecutable(IWebHostEnvironment environment)
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

info: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Request finished in 109.417ms 500 text/plain
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[0]
      Connection id "0HLUSJUOJJNH6" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection id "0HLUSJUOJJNH6" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[0]
      Connection id "0HLUSJUOJJNH6" sending FIN because: "The client closed the connection."
dbug: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection id "0HLUSJUOJJNH6" stopped.

```

I don't see this error in a simple sample application created from scratch.
Any ideas what part must be failing for this to occur?

Here is my `launchSettings`:

```
{
  "useWebAssemblyDebugging": true,
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:62803/",
      "sslPort": 44309
    }
  },
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },    
    "SPA": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:62807/",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "http://localhost:62807/;https://localhost:62808/;",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }   
    }
  }
}

```

Am I right in thinking this falls within the responsibility of `appBuilder.UseWebAssemblyDebugging();`? I've tried to search for that method source code using github search to see what it does and perhaps figure out why its not working in my app, but couldn't find it so would appreciate a link to its location if possible? (Source link doesnt seem to work i.e I can't step into framework methods such as UseWebAssemblyDebugging). Thanks

### To Reproduce
I can't repro it in a vanilla project, and my app has a complex middleware pipeline (with per tenant forks and branches etc) - however if I can ascertain which bit of blazor would be responsible for this error message then perhaps I can focus my efforts there.

Got Exceptions? Include both the message and the stack trace: 
already included above.
-->

### Further technical details
- ASP.NET Core version
"version": "3.1.201"
- Include the output of `dotnet --info`
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

> Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

> Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

> .NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

> To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Version 16.6.0 Preview 2.1

**Comment by mkArtakMSFT** [comment]
Unfortunately, it looks like you have indeed missed some step/configuration during the migration.
We can't debug your application, but try to check the package versions your project is referencing.

**Comment by dazinator** [comment]
Hmm nope can't see an issue with that:

Directory.Build.props:

```
    <BlazorVersion>3.2.0-preview3.20168.3</BlazorVersion>
```

And in my server csproj:

```
    <ItemGroup Label="Blazor">
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="${BlazorVersion}" />       
    </ItemGroup>
```

And

```
  public void Configure(IApplicationBuilder appBuilder)
        {
            if (HostingEnvironment.IsDevelopment())
            {
                appBuilder.UseDeveloperExceptionPage();
                appBuilder.UseWebAssemblyDebugging();            
            }

```

I've checked the working example, and indeed in the Debug\netcoreapp3.1\ output folder after building the project is the folder: "BlazorDebugProxy" containing the "Microsoft.AspNetCore.Components.WebAssembly.DebugProxy.dll'"

In my non-working project that folder is no where to be seen.

What is responsible for creating that folder there during a build?

e.g this is no where to be found and I am not sure why...

```
'C:\Users\DarrellTunnell\source\repos\Foo\src\Foo.Server\bin\Debug\netcoreapp3.1\BlazorDebugProxy\Microsoft.AspNetCore.Components.WebAssembly.DebugProxy.dll'

```

**Comment by dazinator** [comment]
Oh wow...

So VS builds the solution fine:

![image](https://user-images.githubusercontent.com/3176632/78921377-b7730500-7a8c-11ea-8088-8cf3f78f92d8.png)


but if I drop to the command line and do a `dotnet build`:

![image](https://user-images.githubusercontent.com/3176632/78921551-facd7380-7a8c-11ea-814b-75c1bf0f15ac.png)

**Comment by dazinator** [comment]
- looks like the true bug is that even though I made a mistake here - check out the curly braces instead of parenthesis..

```
 <ItemGroup Label="Blazor">
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="${BlazorVersion}" />       
    </ItemGroup>

```

VS still built absolutely fine, yet dotnet build reported a build error. I typically build in VS so wasn't aware of the problem and spent the best part of an hour chasing red-herrings.

**Comment by mkArtakMSFT** [comment]
Glad you've figured this out, @dazinator.
This is indeed an inconsistent behavior. However, VS has some logic to optimize the builds and by doing so it doesn't restore the packages on every build. However, if you try to restore, it'll fail even in VS.

I recommend using VSFeedback to report that issue. Given that there is no any other action pending here I'm closing this issue.
