### ISSUE TITLE
GCM encryption not available on linux when using DataProtection

### ISSUE THREAD

**Issue by webczat** [dotnet/aspnetcore#20689]
It seems that DataProtection does not support gcm on linux, I get System.PlatformNotSupportedException stating that gcm is windows only.
That happens both in aspnetcore 3.1, and according to my code reading, also in current master.
I discovered that the AuthenticatedEncryptorFactory checks if the os is windows in the gcm case and throws, but https://github.com/dotnet/runtime/blob/master/docs/design/features/cross-platform-cryptography.md seems to state that dotnet core does support gcm on non windows. I haven't tested so it is still possible it is not supported in dotnet core 3.0/3.1, though.

**Comment by GrabYourPitchforks** [comment]
For context, there didn't exist managed GCM classes when this code was first written. So the DataProtection implementation necessarily had to p/invoke into Windows to perform the operation. Looks like the DataProtection layer never got the OS check removed once the managed classes came online.

**Comment by webczat** [comment]
I believe the gcm is openssl... although not sure what the DataProtection will use.

**Comment by blowdart** [comment]
Is there a specific reason why you want it, data protection already does both encryption and authentication anyway. Is it just for speed?

**Comment by webczat** [comment]
Well, I am just playing with aspnetcore stuff quite randomly, and noticed that this configuration does not work even though it is supported by api and is supported on linux in System.Security.Cryptography. So that comes a bit unexpected. Just came at this by accident.
I am not sure if the aes/gcm isn't considered more secure than aes/cbc+hmac...?

**Comment by daidnoggin** [comment]
We bumped into this today as well when trying to set the EncryptionAlgorithm to AES_256_GCM. For us, its a nice to have.

We're using DataProtection to encrypt many frequent payloads, so would prefer the speed if available.

**Comment by blowdart** [comment]
@bartonjs Jeremy are the GCM algorithms available under linux?

**Comment by GrabYourPitchforks** [comment]
The DataProtection stack currently special-cases a bunch of stuff for CNG, such as p/invoking `BCryptHashData` as part of its logic. Now that we have static one-shot hash functions in the BCL, we can start removing some of that custom logic and rely solely on the runtime's own implementation, which already chooses the most optimized thing for each platform. We could start relying on the built-in one-shot AESGCM implementation, and perhaps even the built-in one-shot AESCBC implementations if those are introduced in vNext.

**Comment by HaoK** [comment]
@GrabYourPitchforks I'm guessing you are talking about https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/DataProtection/DataProtection/src/Cng/GcmAuthenticatedEncryptor.cs#L219

So basically is the work here just to switch to the APIs in https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-5.0 or is it larger than just gcm?

**Comment by GrabYourPitchforks** [comment]
For GCM, switch to the `AESGCM` API that was introduced in net5.0. You can also replace the internal helper method `TimeConstantBuffersAreEqual` with calls to https://apisof.net/catalog/d74b7c22-9d0b-89f9-13d6-4491d7de18e1. There are a few other helper methods that can probably be simplified as well.

**Comment by brockallen** [comment]
I didn't follow the details here, but will this fix cause any breaking changes for existing DP keys if an app is migrating from .NET5 to .NET 6? IOW are existing DP keys compat with these code changes?

**Comment by HaoK** [comment]
I think there should be no changes, but I mostly was relying on the unit tests, I replaced the methods one at a time with only decrypt/encrypt and ensured the tests still functioned.  That said I'm new to these apis, so @GrabYourPitchforks will need to confirm

**Comment by GrabYourPitchforks** [comment]
@brockallen Per my comment at https://github.com/dotnet/aspnetcore/pull/29814#discussion_r569845462, allowing GCM to work cross-platform should not be a breaking change. The default authenticated encryption provider in the DataProtection stack writes only the requested algorithm family (AES_CBC_256+HMACSHA256, AES_GCM_256, etc.) to the key file. At runtime, an appropriate implementation is chosen based on the current OS. The recommended change is to flip the runtime code from "use CNG" to "use the new `AesGcm` class."

If the key file mandates a specific implementation; e.g., "thou shalt use CNG;" then that implementation will continue to be used. But the DataProtection stack doesn't emit such markers by default. That would only happen if somebody in app start went out of their way to configure the DataProtection stack to emit these markers.
