### ISSUE TITLE
Re-enable SDL validation once timeout and failure issues are resolved

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#20690]
* https://github.com/dotnet/arcade/issues/5219
* https://github.com/dotnet/arcade/issues/5220

**Comment by wtgodbe** [comment]
Should do this in 3.1 & master

**Comment by pranavkm** [comment]
master -> https://github.com/dotnet/aspnetcore/pull/20691
3.1 -> https://github.com/dotnet/aspnetcore/pull/20711

**Comment by dougbu** [comment]
This was fixed a while ago. Then we migrated to a separate pipeline for the checks.
