### ISSUE TITLE
Unclear behaviour for imperative policy authorization

### ISSUE THREAD

**Issue by FWest98** [dotnet/aspnetcore#20701]
Throughout various spots on GitHub and the official documentation, it is semi-clear that the imperative evaluation of an authorization policy (using IAuthorizationService.AuthorizeAsync) does not perform the actual authentication itself, in the [documentation for resource-based AuthZ](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-3.1#security-authorization-resource-based-imperative) it shows a disclaimer stating that authentication should have run before.

However, it is not immediately clear that this means that the `AuthenticationSchemes` attribute of a policy is not evaluated on authorization, and that the `RequireAuthenticatedUser()` does not necessarily mean that the associated Schemes are required for this to pass.

The usecase/example for this: I want to provide simple WsFed signin for the application, but to access "secure" parts of the interface, the user should re-login with MFA. Somewhat similar to how it works with Google and Microsoft, you have to re-auth for the account management interface.

In practice, I found the best way to approach this is to define two WsFed schemes, each linked to a different config on the ADFS server. Then I added an authorization policy as follows:
``` C#
services.AddAuthorization(options => {
    options.AddPolicy("MFA", policy => {
        policy.AuthenticationSchemes.Add("WsFed_MFA");
        policy.RequireAuthenticatedUser();
    });
});
```

This works perfectly fine when combined with the `AuthorizeAttribute`, and this is what is explained in [the documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#selecting-the-scheme-with-policies). However, in my use-case I want to change some parts of the UI based on whether they would have to re-login to do a certain action. Basically, I want to test whether this policy passes, and then toggle things in the UI. Again, I refer to [the documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/views?view=aspnetcore-3.1), and "naively" call `_authService.AuthorizeAsync(User, "MFA");` in the view. The user is set, which is required, using the AuthZ attribute on the controller. I would expect this to work.

However, at this point, it turns out that a single "AuthorizationPolicy" needs to be evaluated in two ways: both for AuthN and AuthZ. This is very opaque to me, without looking at the source code of all of this in detail. When just calling AuthZAsync, only the `DenyAnonymousAuthorizationRequirement` is tested, which does not take into account the AuthenticationSchemes you have set. This is explained nowhere and to be honest, does not make sense to me. The policy I defined above, to me, sounds like; "for this policy I accept users making use of scheme X, and I require the user to be authenticated (using scheme X)".

The only way to solve this, is to get a PolicyEvaluator and manually call both the AuthN and AuthZ functions, like the AuthZMiddleware is doing. However, then I run into issue https://github.com/aspnet/Security/issues/1341: the User is reset by calling the AuthN function.

All in all, this took me quite some time to figure out, and I think that at least somewhere in the docs for scheme selection using a policy, this should be pointed out. However, maybe for .NET 5, I would highly appreciate making these AuthZPolicies less opaque and make the separation between AuthN and AuthZ more explicit throughout the code.

**Comment by anurse** [comment]
The [doc on imperative auth](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-3.1#use-imperative-authorization) does show that if you want to do any Authentication actions (Forbid, Challenge, etc.) you need to do that explicitly:

```csharp
public async Task<IActionResult> OnGetAsync(Guid documentId)
{
    Document = _documentRepository.Find(documentId);

    if (Document == null)
    {
        return new NotFoundResult();
    }

    var authorizationResult = await _authorizationService
            .AuthorizeAsync(User, Document, "EditPolicy");

    if (authorizationResult.Succeeded)
    {
        return Page();
    }
    else if (User.Identity.IsAuthenticated)
    {
        return new ForbidResult();
    }
    else
    {
        return new ChallengeResult();
    }
}
```

In general, imperative authorization cannot trigger re-authentication since the two systems are not connected (The AuthZ service has no coupling to the AuthN system, it's only the AuthorizeAttribute logic itself that can couple those together for automatic challenging).

What kind of documentation updates do you think would help clarify this for you? We can definitely look at updates to make it clearer!

**Comment by FWest98** [comment]
Thanks for the quick feedback! Indeed, the imperative AuthZ page says that you "the following code samples assume authentication has run and set the User property", however in my case that was the case. Except for the fact that the authentication didn't run with the criteria set in the authorization policy.

So concrete improvements I would suggest:
For the docs: at [Limit identity by scheme / Selecting scheme with policies](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1#selecting-the-scheme-with-policies), mention that when using imperative AuthZ, the `AuthenticationSchemes` property of the policy is not evaluated when you only call AuthZAsync. If that would have been mentioned there, I would be annoyed by the hassle but it would be clear.
For the code: for example [here](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/AuthorizationPolicy.cs#L26) the comment is also quite deceptive. In practice, the requirements in the policy are not necessarily evaluated against these listed schemes.

For future versions of .NET (Core) I would suggest to try and resolve two unclear naming things (unclear in my view, maybe I see it incorrectly):
- The fact that the AuthZ**Attribute** also does AuthN, and
- the fact that an AuthZ**Policy** can also say something about AuthN behaviour (the schemes),

while all other AuthZ-related stuff does not do anything AuthN-related.

Concretely, you could split up the AuthZ attribute in two attributes, where for the AuthZ attribute the user can specify roles, claims, policies, etc; and in the new AuthN policy, the user can specify the schemes allowed. It might be good to add an "AutoAuthNAttribute" then as well, in style of what is being done with Antiforgery, to prevent entire codebases being littered with attributes.

To fix the second point, there are multiple ways to go about this. My interpretation of the `AuthenticationSchemes` property is that the policy passes (authz) if the current, already authenticated, user was authenticated using the listed schemes. You can argue that such a check should not be part of the AuthZ phase since AuthZ should only be concerned about the user itself, and not how they are identified: but then the attribute should be removed. Otherwise, I could envision adding a claim with the AuthNscheme used, to make this check actually possible in the AuthZ phase.

On a much higher level, it might be nice to look into supporting some kind of level of assurance in the auth systems. My use-case is only caused by "abusing" the current system to get this behaviour, but I don't know how useful this would be for other people.

**Comment by anurse** [comment]
One thing to note is that there **is** a component that can do both authentication and authorization like this, both MVC and SignalR use it to evaluate the `AuthorizeAttribute` (the attribute itself is just data, it doesn't do anything). If you want to, you can use this type to perform the AuthN (driven by the AuthZ policy). The `IPolicyEvaluator` service allows you to do this.

**Comment by FWest98** [comment]
Yes, that is also what I mentioned in my first post:

> The only way to solve this, is to get a PolicyEvaluator and manually call both the AuthN and AuthZ functions, like the AuthZMiddleware is doing. However, then I run into issue https://github.com/aspnet/Security/issues/1341: the User is reset by calling the AuthN function.

Of course, you can make a workaround that caches the old User value and re-sets it after the policy checking, but it is not an ideal solution. And of course, it doesn't change the confusing naming of things in some places, as outlined before.

**Comment by FWest98** [comment]
As far as I am concerned, this issue is not yet resolved. To summarize the discussion so far, let me describe the current state:

- You can define AuthN schemes in an AuthZ Policy
- AuthN schemes in an AuthZ Policy are only evaluated during AuthN, not during AuthZ
- The AuthZ attribute on a route performs both AuthN and AuthZ
- When doing imperative auth, you need to manually perform both AuthN and AuthZ with the targeted AuthZ Policy

So the following points I find strange, counter-intuitive, or not well-documented:
- If you desire strong separation between AuthN and AuthZ components, why does the user need to perform AuthN using the AuthZ Policy (`IPolicyEvaluator::AuthenticateAsync()`)? This is counter-intuitive and not explicitly documented.
- Why does the AuthZ Policy have anything to say about the AuthN methods? (in that you can specify schemes)
- There seems to be an inconsistency: when doing attribute-based operations, only an AuthZ attribute is sufficient and it will do both AuthN and AuthZ; but when doing imperative work, you need to do both explicitly.
- When `testing' if a policy passes (imperatively), you need to re-authN with that same policy for the schemes to be checked. However, from the perspective of the developer, the user might already be AuthN'd (using an AuthZ attribute for example) since HttpContext.User is set. It it not obvious to need to do AuthN again.

And to conclude, I would like for the following scenario's to be supported/documented:
- Supporting multiple `levels of assurance' in the Auth system, for example to require MFA for sensitive operations but not otherwise. This could be a completely new feature, I will make a new issue if desired.
- Supporting `testing' whether an AuthZ Policy passes, without that having effect on the state of the HttpContext
- Either further separating AuthN and AuthZ by pulling the auth scheme evaluation out of the AuthZ Policy (since they are evaluated during AuthN), or documenting this behaviour more clearly and explicitly.
