### ISSUE TITLE
Improve default Error page in the templates

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#20705]
Today, the default Error page in the templates includes the Activity.Current.Id in the rendered HTML. However, if the user has changed `Activity.DefaultIdFormat` to `ActivityIdFormat.W3C` it not a great experience.

The new W3C format encodes multiple pieces of information in a single string. The format is `version`-`trace-id`-`span-id`-`traceflags`.

The original intent was the user could copy the activity id into their log workspace verbatim (e.g., Application Insights) and find the associated telemetry.

However, given most users aren't expected to know the [W3C TraceContext spec](https://www.w3.org/TR/trace-context/), we can do better.

I propose the following changes:

- [ ] Render both the `trace-id` and `span-id` (instead of `ActivityId`) when the default id format is W3C
- [ ] Add an fwlink to [a doc](https://github.com/dotnet/AspNetCore.Docs/issues/17708) that explains what these values are and how to use them. 

I suspect this will become more prevalent once we make [W3C the default format](https://github.com/dotnet/runtime/issues/34787)

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
