### ISSUE TITLE
Visual Studio Community 2019 16.5.3 with Blazor App -> Add -> New Item -> Razor Component -> Route or component is not rendered

### ISSUE THREAD

**Issue by Ogglas** [dotnet/aspnetcore#20702]
### Describe the bug
Creating a new Razor Component via Visual Studio GUI -> Route or component is not rendered

### To Reproduce
Visual Studio Community 2019 16.5.3 -> Blazor App -> Add -> New Item -> Razor Component try to either navigate to the component or render it directly.

I'm following the official Blazor tutorial from Microsoft:

> Add a new Todo Razor component to the app in the Pages folder. In
> Visual Studio, right-click the Pages folder and select Add > New Item > Razor Component.
> Name the component's file Todo.razor. In other development environments, add a blank file to the Pages folder named
> Todo.razor.

https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1#build-a-todo-list

Done like this:

[![enter image description here][1]][1]

This creates a file that looks like this:

    <h3>Todo</h3>
    
    @code {
    
    }

Given that it has no routing I add `@page "/todo"` to the top, exactly like the example pages `Counter.razor` and `FetchData.razor` has. 

I then start the application but I can't navigate to 

[![enter image description here][2]][2]

I have tried renaming the route to different names, check the folder for any scrap files, created new files but there is nothing that I can find. 

No matter what I do the not found is hit from `App.razor`.

    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>

Now to the really weird part. If I copy the file Counter.razor and rename `@page` to whatever I want it will work. 

I then suspected this had something to do with encoding or hidden chars etc. But If I copy the entire working file content and only change `@page` it will still not work if the file was created from the UI. What could be the cause of this?

[![enter image description here][3]][3]

I have not modified anything else, everything done is simply add a new Blazor App -> Blazor Server App with Individual User Accounts -> Connect to an existing user store in the cloud (Azure AD B2C).

I can not add it as a component either. Adding `<Todo2 />` to `Index.razor` will show up but `<Todo />` will be blank. 

What could be the cause of this?

  [1]: https://i.stack.imgur.com/RxfkZ.png
  [2]: https://i.stack.imgur.com/Y7dWH.png
  [3]: https://i.stack.imgur.com/L0KkV.png

### Further technical details
- ASP.NET Core version -> .NET Core 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version -> Windows 10 Enterprise N -> Microsoft Visual Studio Community 2019 Version 16.5.3

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Ogglas** [comment]
Attached project. 

Visit `https://localhost:44382/todo` and it will work, visit `https://localhost:44382/todo2` and it will not work even though the content is the same. 

Create a new file via Add -> New Item -> Razor Component and try to either navigate to the component or render it directly and it won't work.

[BlazorAppTestVS.zip](https://github.com/dotnet/aspnetcore/files/4483780/BlazorAppTestVS.zip)

**Comment by pranavkm** [comment]
@Ogglas some of these files were removed from the project. If you edit `BlazorAppTest.csproj`, you can see these entries:

```xml
<Content Remove="Pages\Todo2.razor" />
<Content Remove="Pages\Todosss.razor" />
```

AFAIK, it's likely a VS behavior when it sees an item appear in multiple item groups. In your case, it's triggered by the presence of:

```
<ItemGroup>
    <Watch Include="..\**\*.razor" />
    <Watch Include="..\**\*.scss" />
    <Watch Include="..\**\*.cs" />
  </ItemGroup>
```

You should be able to remove `<Watch Include="..\**\*.razor" />` and `<Watch Include="..\**\*.cs" />` to avoid running in to this. They're added by default and do not need to explicitly added.

**Comment by Ogglas** [comment]
@pranavkm Thanks! Tested and indeed it was an `<ItemGroup>` error.
