### ISSUE TITLE
Blazor WebAssembly Hosted Template Can not authorize Authenticated User on Azure LinuxAppService

### ISSUE THREAD

**Issue by otaskiran** [dotnet/aspnetcore#20700]
Blazor WebAssembly Hosted Template Can not authorize Authenticated User on Azure LinuxAppService

I am using latest Blazor WebAssembly Hosted with Individual Authentication template. (Preview 3)
This template and server api authorization works on developer machine and Azure Windows AppService.
But same solution can not authorize user on Azure Linux App Service.
It returns 401 error.

**Comment by danroth27** [comment]
Hi @otaskiran. Can you show us how your signing key is configured for the app (presumably in *appsettings.json*)?

**Comment by otaskiran** [comment]
Hi Daniel,
I am using "Development" type identity server key.
It works on Windows appservice, but it does not work on Linux App Service.
I am not using special key.

`"IdentityServer": {
    "Clients": {
      "BlazorApp5.Client": {
        "Profile": "IdentityServerSPA"
      },
      "Key": {
        "Type": "Development"
      }
    }`

**Comment by danroth27** [comment]
@otaskiran Is this just for testing purposes then? We can take a look at why the "Development" key isn't working on App Service on Linux, but I just want to make sure you're aware that this setup is not intended for a production environment. For a production environment you need to setup a property signing certificate: https://docs.microsoft.com/aspnet/core/security/authentication/identity-api-authorization#deploy-to-production

**Comment by otaskiran** [comment]
Hi @danroth27,
Yes, it is for testing purpose. But it works on Windows app service.
I know, this will not usable on prod environment. 
But, I want to sure that identity server should be work on linux app service environment.
I want to see the webassembly works on linuxappservice with identity server.

**Comment by javiercn** [comment]
@otaskiran have you checked that you are forwarding the headers correctly? I would check that the request host is correct.

**Comment by mkArtakMSFT** [comment]
@shirhatti do you know whether there are any additional settings to be set with Linux app service, to ensure headers are properly forwarded?

**Comment by shirhatti** [comment]
See https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/

If you're using AppService for Linux, we're wiring up the forwarded headers middleware for you. If you're using AppService for Containers where you bring your own base image, you'll need to configure it manually.

cc @bradygaster
