### ISSUE TITLE
Is HTML5-validation supported?

### ISSUE THREAD

**Issue by pekspro** [dotnet/aspnetcore#20717]
In the documentation  it says for the [input tag helper](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-3.1#the-input-tag-helper):

>Generates HTML5 validation attributes from data annotation attributes applied to model properties. 

But if I have an property like this:

    [Required]
    [StringLength(10, MinimumLength = 5)]
    [Display(Name = "Computer name")]
    public string ComputerName { get; set; }

And then uses the input tag like this:

    <input asp-for="ComputerName" class="form-control" />

It becomes generated like this:

    <input class="form-control" type="text" data-val="true" 
    data-val-length="The field Computer name must be a string with a minimum length of 5 and a maximum length of 10." 
    data-val-length-max="10" data-val-length-min="5" 
    data-val-required="The Computer name field is required." id="ComputerName" 
    maxlength="10" name="ComputerName" value="">

There is no **minlength** and **required** attribute as expected. Also, the **form** tag is generated with the **novalidate** attribute which to my understanding [disables HTML5 validation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input).

I’ve also tried to [disable client-side validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#disable-client-side-validation). This removes the **novalidate** attribute on the **form** tag, but the **minlength** and **required** attribues is still missing.

To summary, is HTML5 validation supported as it mentioned in the documentation? 

[Issue 8573](https://github.com/dotnet/aspnetcore/issues/8573) is a bit related to this.

I’m asking only by curiosity :-)

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by XmlmXmlmX** [comment]
Wow, that's really hard to believe. Open for 2 years.

**Comment by javiercn** [comment]
We are going to use https://github.com/dotnet/aspnetcore/issues/8573 to track work in this area.

As for HTML5 validation specifically, we do not think it is a good fit as we identified some gaps compared to the current experience the last time we evaluated it.

**Comment by javiercn** [comment]
@denschub I would need to dig into the details (we had this discussion many months ago and the developer on point is no longer part of the team), but I believe some of them were:
* Different UIs across browsers.
* Customizing the UI
* Custom error messages
* Error summary
* Async validation

Some of these might be possible (even though at the expense of writing code), but in general html5 validation works very differently from our current validation system and we would like to maintain backwards compatibility where possible.

**Comment by denschub** [comment]
Understood, yeah. There's probably some things you can already do with native APIs. For example, an Error summary could be built by iterating over form elements and reading [`HTMLObjectElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/validationMessage). Custom error messages can be set via [`HTMLObjectElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity), etc. But I assume there's still a lot of things not possible, so feel free to [file an issue in the HTML spec](https://github.com/whatwg/html/issues) if you have any specific feature request!

None of that won't help with full backwards compatibility, of course. I was just curios, so thanks for the feedback!
