### ISSUE TITLE
Blazor: Attached properties (behaviors)

### ISSUE THREAD

**Issue by robertjak** [dotnet/aspnetcore#20715]
A feature request: Attached properties like in WPF framework - for cross cutting functionality among components (logic reuse). Or something like Knockout bindings or AngularJS attribute directives.

For instance, logic reuse among components in React can be a nightmare, there are some standard workarounds using higher order components, render props etc. but none of them is elegant and maintainable, in the end the components are nested endlessly. There are also hooks but these are certainly neither maintainable nor easy to understand. Attached properties would solve this problem perfectly.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not a good fit for Blazor app-model at this time.

**Comment by danroth27** [comment]
Seems related to #5607
