### ISSUE TITLE
[Blazor][Wasm] Consider making AuthorizationMessageHandler thread safe

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#20726]
**Edit made by @captainsafia**

This issue is a result of PR feedback in the PR below. Per Steve's comment (below):

> I know we're in the realms of pure theory here, but in theory there's a thread safety issue: _cachedHeader might still be null after _lastToken was assigned on another thread.

> Where possible it's good to account for thready safety even on Blazor WebAssembly now as we want to be enabling the threaded version of dotnet.wasm for 5.0.

This will need to be addressed if we support multiple threads in the WASM scenario.

**Comment by SteveSandersonMS** [comment]
For reference: https://github.com/dotnet/aspnetcore/pull/20682#discussion_r406839705

**Comment by mkArtakMSFT** [comment]
Moving this to .NET 8 Planning, given that the threading support is coming in .NET 8 for WASM runtime.
