### ISSUE TITLE
Unable to Debug Blazor WebAssembly 3.2.0 Preview 3 App

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20729]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/983111/unable-to-debug-blazor-webassembly-320-preview-3-a.html)._

---
The Visual Studio Debugger does not appear to work. I have no problem running apps just not able to debug in VS.
I have created a project using the template, pressed F5, set a breakpoint on the IncrementCount method and Navigated to the counter page and nothing.

---
#### Visual Studio Feedback System on 4/8/2020, 08:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you share some more details about your environment? This is not a feedback we've heard from others so would like to understand what's going wrong.

**Comment by DimitrisRousis** [comment]
The same happens to me too. When i hover on the breakpoint (the breakpoint is in the IncrementCount method) i see this message: "The breakpoint will not currenlty be hit No symbols have been loaded for this document."

**Comment by LeeActon** [comment]
I was having exactly the same issue, then I thought "maybe it's because I'm using **Firefox** as my browser"... so I switched to the latest **Microsoft Edge** and still had the same problem. Then I switched to **Chrome** and it works fine.

**Comment by DimitrisRousis** [comment]
I tried with Chrome but the problem still remain.

**Comment by mkArtakMSFT** [comment]
Glad that it worked out, @DimitrisRousis.
Can you share the version number of the Edge browser, when it opens up when you start the debugging session?

**Comment by LeeActon** [comment]
@mkArtakMSFT.

For me, debugging does not work in **Microsoft Edge Version 80.0.361.111 (Official build) (64-bit)** nor **Firefox 75.0 (64-bit).**

Everything works great in **Google Chrome Version 81.0.4044.92 (Official Build) (64-bit)**.

**Comment by mkArtakMSFT** [comment]
@LeeActon thanks for the info. The Edge version is the same as one of our team member has, and they are debugging just fine. we will look into this in our next sprint planning, as we're wrapping up Blazor WASM release.

**Comment by DimitrisRousis** [comment]
@mkArtakMSFT 
I tried on: 

- Microsoft Edge Version 81.0.416.53 (Official build) (64-bit)
- Google Chrome Version 81.0.4044.92 (Official build) (64-bit)

With both browsers the debugger works.

**Comment by mkArtakMSFT** [comment]
Thanks for confirmation, @DimitrisRousis. Glad that you've got debugging working for both browsers.
@LeeActon can you try to update to the version listed by @DimitrisRousis above (81.0.416.53) and see whether that fixes it?

**Comment by LeeActon** [comment]
@mkArtakMSFT, I updated to Microsoft Edge Version 81.0.416.53 (Official build) (64-bit), and the debugger still fails to work. Specifically, breakpoints say "This breakpoiint will not currently be hit. No symbols have been loaded for this document."

**Comment by LeeActon** [comment]
FYI, I just updated to Visual Studio: Version 16.6.0 Preview 3, and debugging now works in Edge.
It still works in Chrome, but still does NOT work in Firefox.

BTW, I'm ecstatic to be able to debug Blazor WebAssembly in VS. One working browser was good... now I have two... I can live without Firefox.

**Comment by mkArtakMSFT** [comment]
Glad that you got it working. Seems like there is no more action pending here. Closing this issue.

**Comment by LeeActon** [comment]
@mkArtakMSFT,

Ok, now I'm back to debugging not working, but now it's failing on all three browsers (Chrome, Edge, and Firefox).

It seems to be specific to my project because a simple project that is created from the standard template and unmodified works perfectly fine.

Looking at the modules that are loaded in the working and non-working scenarios, the "javascript debugger root session" and "localhost" processes are not loaded in the non-working scenario.
See the two attached images.

The source code for my application is on github at: https://github.com/SparksInTheSoftware/Sudoku.

As far as I can tell, there isn't anything different in how the working and non-working projects are built or launched.

Working:
![good](https://user-images.githubusercontent.com/5264590/79917168-d3589e00-83de-11ea-9bcf-3f2731a6c676.png)

Not working:
![bad](https://user-images.githubusercontent.com/5264590/79917169-d3f13480-83de-11ea-86d5-5d088db2a622.png)

**Comment by idscom** [comment]
Having the same issue on:
![image](https://user-images.githubusercontent.com/31682573/80563225-480f7780-899f-11ea-9991-b48775e17cb1.png)

![image](https://user-images.githubusercontent.com/31682573/80563318-93298a80-899f-11ea-9d36-9965e7143c69.png)

**Comment by LeeActon** [comment]
@mkArtakMSFT,

I updated to RC1, and I'm still unable to debug the project I posted earlier.

**Comment by NickAcPT** [comment]
I'm having the same issue on Visual Studio Community 2019 Preview 16.7.0 Preview 1.0.
Doesn't work with any browser.
