### ISSUE TITLE
Blazor using high CPU running background tasks that never finish

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20731]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/976276/blazor-using-high-cpu-running-background-task-that.html)._

---
<p>in a blazor server project I am working on I was finding there were some .razor code files that made the CPU run high and slowed down my computer signifiantly.<br>
when i close the particular code file, the background task would finish after a 10 secs or so and the cpu would go back to normal</p>
<p>I did a lot of searching on this and found multiple posts with responses but no answers (sorry didn’t keep any links).<br>
I have had this issue for many versions on VS both full versions and Preview versions.<br>
my current version is Microsoft Visual Studio Professional 2019 Version 16.4.3</p>
<p>I finally found out what was causing it in my situation.</p>
<p>in the bad code file I had a using statement with an extra space in it<br>
@using   HelpMaster_Web.Pages.Workflow;<br>
notice 2 spaces after the using.<br>
if i add the extra space to it now, my CPU goes real high and background tasks never finish running.<br>
then when I remove it again, after a little while it goes back to normal.</p>
<p>so I guess the bug is<br>
this shouldn’t keep the background tasks running forever<br>
and if it is an issue making the using statement invalid, it should underline it with a red squggily line and\or add it to the error list</p>

---
#### Roi Chen [MSFT] on 4/3/2020, 00:37 AM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:<br>
• Open Visual Studio Feedback tool.<br>
• Click the banner letting you know that you have problems requesting your attention.<br>
• Click this problem from the list<br>
• Click “View their request and respond” from the problem details banner<br>
• Add a comment, in the Attachments/Record: click Start Recording<br>
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.<br>
• When you’re done, choose the Stop Record button.<br>
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.<br>
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don’t appear on Developer Community.<br>
For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.<br>
We look forward to hearing from you!</p>

#### Scott Ward on 4/6/2020, 06:34 PM: 

Here is the Recording you requested<br>i had to stop the never ending background task state before i caould do this<br>I tried to do the recording while I made the background tasks were in the never ending state but that stopped the &quot;Please wait while we finish collecting additional information.&quot; screen from finishing, I was on a work skype call about 20mins in to the error collection and it was running for just over an hour in total and would not finish
#### Scott Ward on 4/6/2020, 11:17 PM: 

I have just updated​ my visual studio to <br><br>Microsoft Visual Studio Professional 2019<br>Version 16.5.2<br><br>and the initial issue seems to be resolved now, I no longer get the background tasks with &quot;running low priority background processes&quot; that was running forever.<br><br><br>but I now get a background task labeled &quot;Loading IntelliSense&quot; that never completes<br><br>it is not related to the double space after the @using as stated in the intial error report<br><br>it is running constantly all the time<br><br>it is also not as CPU intensive as the initial error
#### Visual Studio Feedback System on 4/9/2020, 10:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ScottyBlazor** [comment]
I found a workaround to the issue of the "IntelliSense loading" in background tasks that never stops from another post.
If you go to "Tools -> Options" "Environment -> preview features" and turn off the "Load projects faster" setting then the issue does not occur after reloading the solution

**Comment by allisonchou** [comment]
We've made a ton of perf improvements in the new, completely revamped Razor editor (VS 2022). Given this is the case, I'm going to close this issue out for now, but if you notice any issues with the new editor, please do file another issue. Thank you!
