### ISSUE TITLE
Attempting to change UserName and Password results in invalid credentials - can change either but not both

### ISSUE THREAD

**Issue by lxman** [dotnet/aspnetcore#20734]
### Describe the bug
I am working on a new blazor server application using Identity. If I change either UserName or Password this works as I expect. But when I try to change BOTH, it results in invalid login attempts.

### To Reproduce
See Github repo here: https://github.com/lxman/BlazorPasswordReset

Reference in particular ```ResetPassword.razor```. If I register my user, then proceed to this page, change the username/password, then logout - any attempts to log back in result in invalid credentials. I can change only the username or only the password (by commenting out the relevant code) and I can logout/login without issue.

### Further technical details
- ASP.NET Core version - 3.1
- Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

VS - 16.5.3

**Comment by blowdart** [comment]
What's happening here is you're mixing the user manager APIs, with adjusting the actual User object. That doesn't work, as you've discovered. You can't mix and match, you have to either stick to the user manager APIs, which don't provide a way to change usernames *or* start writing database code with EF, which doesn't end up working because our lookups are on the normalized email column.

There's a way to fudge it, @HaoK to provide.

**Comment by lxman** [comment]
FWIW, if I understand correctly what you are explaining properly, there is a reason that I had to go in that direction.

I have been facing what appear to be concurrency issues when accessing the DB via the inbuilt API's.

The project referenced is just a scratch project I made up to demo this particular issue. I have a much more extensive project that I am in the process of developing which I am unable to share due to its proprietary nature. Basically my experience is that, as I begin working with the Identity DB more extensively, and I try to call one of the async API's (the UserManager, for instance, only seems to offer async API's for many of the calls, IsInRoleAsync, for instance) that more often than not I will receive an error to the effect that a transaction was started on the database before another transaction had completed (or words to that effect).

The synchronous API's do not seem to have this issue.

The more I work with it, the more I get the impression that Identity integration into Blazor is at an alpha or beta level.

Thus far the only resolution that I have found is to use synchronous API's where they are provided or if they are not, inject an instance of ApplicationDbContext and work directly with that.

**Comment by HaoK** [comment]
The gist of it is, if you are manipulating the user poco object yourself, you will need to mimic the additional normalized properties for things to continue to work, i.e. UserName/Email and their associated NormalizedUsername/Email columns, basically.  For your repro, you probably need to also set email to match the username maybe?

**Comment by lxman** [comment]
So, are you saying that username/email have to be equivalent?

**Comment by HaoK** [comment]
No they don't have to, but that depends on how your app is using the apis. The templates by default use email as username
