### ISSUE TITLE
rename enum ignores cshtml files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20732]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/475042/rename-enum-ignores-cshtml-files.html)._

---
I have:

A cs class with an enum.
CS code that references that enum
CSHTML code that references the enum.

If I rename a member of the enum, the rename refactoring tool happily updates all occurrences of it in the CS files, but completely ignores cshtml references. Compiling shows these (ie they are directly referenced similar to:

@if (x == class.enum.item)
{
}

inside the cshtml, with the appropriate colouring by intellisense)

As the compiler and intellisense can detect these, the refactoring tool should too.

---
#### Visual Studio Feedback System on 3/3/2019, 07:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/4/2019, 11:26 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen putting this on your radar!

**Comment by NTaylorMullen** [comment]
This has definitely been a pain point of Razor development for a while. Thankfully we'll be addressing this in the .NET 5 wave as part of LSPification!

**Comment by allisonchou** [comment]
As Taylor mentioned above, this should be fixed by LSP-ification so closing out the issue.
