### ISSUE TITLE
Workaround for debugging issue with Blazor Webassembly 3.2.0 preview 3 PWA

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#20738]
I understand that Visual Studio debugging is not yet supported for blazor webassembly applications that have a service worker. However, I unregistered my service worker from the browser, cleared cache, and in Client's index.html, commented out the code that registers the service worker, as well as the manifest. However, I still cannot get debugging to work. 

`<!--<script>navigator.serviceWorker.register('service-worker.js');</script>-->`

On the other hand, I created a new webassembly project without selecting the PWA option, that can be debugged successfully.

Please suggest a workaround to debug a PWA project, even if it means temporarily commenting out some code. Thanks

**Comment by mkArtakMSFT** [comment]
Make sure you also unregister and remove the service worker from the browser dev-tools.
