### ISSUE TITLE
Cannot Access Database When ConnectionString is Retrieved from secrets.json

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20730]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/983096/cannot-access-database-when-connectionstring-is-re.html)._

---
<p>I am writing an ASP.NET Core 3.1 application using Entity Framework for database access.  I moved the connection string from appsettings.json to secrets.json via the Secret Manager.  I can retrieve other strings from secrets.json.  However, reading the connection string in the Startup.ConfigureServices method fails to create a functional DbContext.  ASP.NET Identity is enabled.  The statement in the method is:</p><pre>   services. AddDbContextPool&lt;VerityContext&gt;(options =&gt;             {                 object p = options. UseSqlServer(Configuration.GetConnectionString(&quot;VerityDb:ConnectionString&quot;));             });
</pre><p>        </p><p>The key in secrets.json is VerityDb:ConnectionString.  I can read the value outside the statement, but it fails.  How can I resolve this?</p> <p>Thank you.</p>

---
#### Visual Studio Feedback System on 4/9/2020, 01:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Leonard James on 4/9/2020, 08:23 AM: 

<p>I got this resolved!  See the discussion from Matthew Tester in his Pluralsight course, </p><p>Securing Application Secrets in ASP.NET Core.  The key is to use the format, ConnectionStrings:[App key for connection string}, in the secrets.json file. Then use the statement,</p><pre>services.AddDbContextPool&lt;[DbContext class name]&gt;(options =&gt;
    {
        object p = options.UseSqlServer(Configuration.GetConnectionString("[App key for connection string]"));
    });</pre><p class="">This worked.</p><p class="">This item can be closed.  Thank you.</p>
</pre>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@anurse can you please look into this? Thanks!

**Comment by anurse** [comment]
> I got this resolved! See the discussion from Matthew Tester in his Pluralsight course,

@mkArtakMSFT per this comment is sounds like the issue is resolved. Was there something else to look in to here?
