### ISSUE TITLE
VisualStudio - RazorComponents - IntelliSense

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/aspnetcore#20740]
### Describe the bug
VisualStudio Preview version 16.6.0 Preview 2.1 opening a new RazorComponent sits waiting with 'Waiting for IntelliSence to finish initializing...'
prompt
### Further technical details

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This issue has already been fixed and will be release in the upcoming VS preview release.
@NTaylorMullen do you have any more specific details about the fix? Would be great if you could dupe this with the original issue.

**Comment by NTaylorMullen** [comment]
@mkArtakMSFT most other dups are in VSTS. This might be the first in AspNetCore. @3GDXC stay tuned for the 16.6-preview3 release where it's fixed.
