### ISSUE TITLE
Blazor : Not able to import layout using layout directive in Razor Class Library(RCL) 

### ISSUE THREAD

**Issue by KishorNaik** [dotnet/aspnetcore#20753]
### Describe the bug
In razor class library(RCL), layout not applied by specifying **layout directive** in the **_Import.razor** file inside the RCL solution but if we specify layout using layout directive at component level then it will work.

I tested the above-said issue on the main blazor solution(server side) and it's working properly (Different  solution not added on this repository) but don't know, why layout directive not working on _Import.razor file inside the RCL solution.

Here is a github Repository.
https://github.com/KishorNaik/Blazor_Layout_Bug_RCL

In RCL(CustomerComponent) solution, check following three files.
- CustomerLayout.razor
- _Imports.razor
```razor
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.JSInterop

@using CustomerModule
@using CustomerModule.Shared


@*If we specify layout directive here then it will not apply layout.*@
@layout CustomerLayout`
```
- CustomerComponent.razor
```razor
@*If we specify layout directive at component level, then it will apply layout.*@
@*@layout CustomerLayout*@

@page "/customerview"

<h3>CustomerComponent</h3>

<a class="btn btn-danger" href="/">Redirect to Main Index Page</a>

@code {

}

````

Run the main blazor solution and find Customer page on NavBar section. Click on customer page link, it will not redirect to customer component nor applying layout.

**Comment by pranavkm** [comment]
@KishorNaik _Imports.razor is a parse time feature. The .razor has to be physically present for directives to be applied to other .razor files. A compiled `_Imports.razor` does not affect other razor files.
