### ISSUE TITLE
Blazor server: why it does not start?

### ISSUE THREAD

**Issue by Oleg26Dev** [dotnet/aspnetcore#20754]
I have tried to configure host:port without hardcoding, but the Blazor server-side app does not start in this case?

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder =>
    {
        webBuilder.UseStartup<Startup>()
        .UseUrls(urls: new String[] { "http://*:6000", "https://localhost:6001" });
    });

```

If I remove the call .UseUrls(urls: new String[] { "http://*:6000", "https://localhost:6001" }); it starts . What is wrong? I see a console only with output but browser does not start

Microsoft.Hosting.Lifetime: Information: Now listening on: http://[::]:6000 Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:6001 Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down. Microsoft.Hosting.Lifetime: Information: Hosting environment: Development Microsoft.Hosting.Lifetime: Information: Content root path: ... Microsoft.Hosting.Lifetime: Information: Application is shutting down...

**Comment by Oleg26Dev** [comment]
What is interesting, if I run this way:
1. launchSettings.json:
"applicationUrl": "https://localhost:5001;http://localhost:5000",
2.  webBuilder.UseStartup<Startup>()
        .UseUrls(urls: new String[] { "http://*:5000", "https://localhost:5001" });

then it starts ok and writes in the log:

> Microsoft.Hosting.Lifetime: Information: Now listening on: http://[::]:5000
> Microsoft.Hosting.Lifetime: Information: Now listening on: https://[::]:5001
> Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C 
>

**Comment by javiercn** [comment]
@Oleg26Dev thanks for contacting us.

This question is not specific to Blazor. From what I understand from similar issues, port 6000 is reserved for another app, I would suggest you try a different port. See [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#configureiconfiguration) for details

**Comment by Oleg26Dev** [comment]
Yes, it is not Blazor specific but ASP.NET Core specific.

It is not resolved. 
The port 6000 is not reserved for other app. The question is if I use these settings: 
launchSettings.json:
"applicationUrl": "https://localhost:6001;http://localhost:6000",
webBuilder.UseStartup()
.UseUrls(urls: new String[] { "http://*:5000", "https://localhost:5001" });

the server does not start.

**Comment by gbrantzos** [comment]
@Oleg26Dev try this on your appsettings.json file:

```
{
  // Rest of settings are omitted
  "AllowedHosts": "*",
  "Urls": "http://localhost:4100;http://localhost:4101"
}
```
Also remember that urls should be separated by semicolon (;) and not comma (,).
