### ISSUE TITLE
NpmScriptRunner.LaunchNodeProcess can't locate npm, but it exists 

### ISSUE THREAD

**Issue by brifly** [dotnet/aspnetcore#20750]
This ticket was already raised here:
https://github.com/dotnet/aspnetcore/issues/5246

Its closed with a solution that didnt work for me. I did find a working solution however -
It wont find npm if you are using node version manager (nvm) - npm must be explicitly installed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The actual installation mechanism doesn't matter. As long as the node is available on the PATH, it'll work. Seems like that installation mechanism doesn't set the PATH properly.
