### ISSUE TITLE
AutomaticReconnect on Java

### ISSUE THREAD

**Issue by aluzme** [dotnet/aspnetcore#20762]
When method withAutomaticReconnect implement on java or android client

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/8711

**Comment by anurse** [comment]
Closing as duplicate

**Comment by aluzme** [comment]
When library which support automaticereconnect on java release?

**Comment by anurse** [comment]
We have no committed date to ship this feature, it will be considered for a future release. The issue I linked is in the backlog meaning it isn't planned for the next release.
