### ISSUE TITLE
After migrate from .Net to >net Core Self Host not working

### ISSUE THREAD

**Issue by colotoon** [dotnet/aspnetcore#20768]
Hello all!

At Net Core 2 i using this easy sample Self-Host:
https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host

Aaaand, all working, thats great!

Ok.

BUT.

Now i`m want to use .Net Core 3.1 

Question #1 is: where i can found easy sample like at help topic upper?

And yes, i`m reading documentation, and cant found for topic with name "Self-Host".

Question #2: i`m dont need javascript/type-script/blazor clients samples, i need c# client code, where i can found it??

I need connect Net Core SignalR Self-Host server(will hosted as Docker container at Linux OS) with C# Client (at Windows OS).

How to???
Please help!

**Comment by davidfowl** [comment]
Asp.net core is always self hosted unless you’re running in IIS. Can you explain what problems you’re having?

**Comment by BrennanConroy** [comment]
The is sample code in https://docs.microsoft.com/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio for the .NET Client

**Comment by colotoon** [comment]
> The is sample code in https://docs.microsoft.com/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio for the .NET Client

thanks!
But where i can get server simple example code without IIS?
At github all examples only with IIS =(

**Comment by BrennanConroy** [comment]
What do you mean all examples are only IIS?
If you `dotnet run` the app or publish and `dotnet app.dll` then you can run the server without IIS.

**Comment by colotoon** [comment]
> What do you mean all examples are only IIS?
> If you `dotnet run` the app or publish and `dotnet app.dll` then you can run the server without IIS.

I mean, i need server example code, how to create hub as standalone console app, like at this topic:
https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host
Because, code from this topic not working in .Net Core Project =(

**Comment by BrennanConroy** [comment]
You can follow one of the tutorials and just ignore all the parts about JavaScript and html pages
https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio

**Comment by BrennanConroy** [comment]
Also, the docs you're looking at for ASP.NET SignalR which do not apply to ASP.NET Core SignalR.

**Comment by colotoon** [comment]
> You can follow one of the tutorials and just ignore all the parts about JavaScript and html pages
> https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio

I trying..... But, cant make this working, so many errors at the Startup class =\

https://drive.google.com/open?id=1B-mxe7VGP862XTx_2M7TXkvrN5NBcR2v

Can u make it working, plz, i dont know how to create working app... :'''(

**Comment by colotoon** [comment]
Or can u upload working example here:
https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/signalr/hubs

Like it was at .Net:

`
using Microsoft.AspNet.SignalR;
using Microsoft.Owin.Hosting;
using Owin;
using Microsoft.Owin.Cors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.SignalR.Hubs;
using Newtonsoft.Json;

namespace signalrServer
{
    class Program
    {

        static void Main(string[] args)
        {
            string url = "http://localhost:8888";

            using (WebApp.Start(url))
            {
                Console.WriteLine("Server running on {0}", url);
                Console.ReadLine();
            }
        }

    }


    class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseCors(CorsOptions.AllowAll);
            app.MapSignalR();
        }
    }

    public class MyHub : Hub
    {
        public Task Hello(string username, string msg)
        {
            Clients.All.serverMSG(username, msg);

            return Task.CompletedTask;
        }
    }
}


`

Easy working SignalR Server!

How to create same in .Net Core 3.1???

**Comment by davidfowl** [comment]
Example https://github.com/aspnet/SignalR-samples/tree/master/ChatSample

**Comment by colotoon** [comment]
> Example https://github.com/aspnet/SignalR-samples/tree/master/ChatSample

Its for IIS server sample, i need standalone console app, look at my code upper plz...
```c#
string url = "http://localhost:8888";

            using (WebApp.Start(url))
            {
                Console.WriteLine("Server running on {0}", url);
                Console.ReadLine();
            }
```

How make same at the Net Core???
How can I assign an application the port I need? (without using IIS server)

**Comment by davidfowl** [comment]
Like I said earlier, all ASP.NET Core applications are self hosted. That code runs both on IIS and outside of IIS (This might explain more https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-3.1&tabs=windows#hosting-models).

**Comment by davidfowl** [comment]
As for assigning the port you can look here:

```
webBuilder.UseStartup<Startup>().UseUrls("http://localhost:8888");
```

**Comment by colotoon** [comment]
> As for assigning the port you can look here:
> 
> ```cs
> webBuilder.UseStartup<Startup>().UseUrls("http://localhost:8888");
> ```

I did some working pair from ChatServer example + Net Client
Finally! 
Will working with this...
Great Thank U!
