### ISSUE TITLE
Handle concurrent request in SignalR.Core

### ISSUE THREAD

**Issue by hosseinRezaei188** [dotnet/aspnetcore#20778]
I'm developing a game and use SignalR.Core Version 3.1.0.0 for real-time events.my issue about handle concurrent request to same void. in one void i have a condition that this condition Affect on game sessions. when first person join to play a game, is checked if not exist ready players for game must set this person state to ready for play game. but in my code when two person join to game in same time (with different user entity and different nano second timestamp) both person for game get ready.without attention to my code condition!!

my supposition is when two person request to play a game, surely one person requested sooner than other person, so i have a one person in `availablePlayers `list before next person's request arrived.is wrong my supposition??

my code:

```
     public async Task<bool> Play(int userID, int level)
        {
            try
            {
                //get user data from subscribed users in GameHub
                var player = signalrClients.FirstOrDefault(x => x.ID == userID);
                if (player == null) return false;

                //get list persons that want to play game
                var availablePlayers = signalrClients.Where(x => x.WantedLevel == level &&
                x.IsWaitingForOpponent == true &&
                x.IsPlaying == false &&
                x.ID != userID).ToList();
   
                //problem is here, because two request arrive in same time availablePlayers count is zero
                //and dont create any gameSession
                if (availablePlayers.Count > 0)
                {
                    #region create game session
                    Game newSession = new Game()
                    {
                        Token = Guid.NewGuid(),
                        Level = level,
                        GameType = GameType.StrangerGame,
                        ListPlayer = new List<PlayerModel>()
                    };

                    #endregion
                    await LogGameSessionList(gameSession);
                }
                else
                {
                    player.IsWaitingForOpponent = true;
                    player.WantedLevel = level;

                }
                return true;

            }
            catch (Exception ex)
            {
                return false;
            }
        }

```

**Comment by BrennanConroy** [comment]
> my supposition is when two person request to play a game, surely one person requested sooner than other person, so i have a one person in `availablePlayers `list before next person's request arrived.is wrong my supposition??

You can't assume that. You'll have to write your application logic to be more robust.
