### ISSUE TITLE
[Blazor] input type time - really strange behavior when included in a component

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#20779]
hello guys, i met problem with using input time in my blazor project.

I will not speak about the binding timespan/DateTime/string wich is already discuss in other issues, and i have workaround solution for this.

So the workaround for me was to make a component wich take all the iput time parameter, and which take care to only update the hour and minute part of the date binded by the caller.
But when i use this component, a really strange behavior happen when the property step is set.
It make it impossible to write an hour/minute with two digit in this component (if i try to write 12 in the hour part for example, the binding will set first dd/mm/yyyy 01:00:00 and then dd/mm/yyyy 02:00:00).

If i remove the step attribute, everything work fine.
No problem also whan using arrow of input time, only when i write text

You can find a repro here : https://github.com/julienGrd/BlazorBugTimePicker
Play with the input time on home page with two digit number and you will see the problem

PS : if you don't reproduce with my repo, maybe its a culture related problem, im on french culture.
PS2 : sometimes it work, if you write really fast for example

thanks !

**Comment by julienGrd** [comment]
UPDATE

im able to reproduce this without a component. it seem is the format the problem, as long the datetime is rendered as hh:mm:ss, everything works fine. But if i remove the second part of the input (clic on it and suppr), the bug begin (if the step attribute is present).
so
 - example 1 : bug directly because the second part is not render (0)
````
<input type="time" class="form-control time-control" required 
       step="300"
       @bind="@date"/>
<span>result : @date.ToString()</span>

@code{
    protected DateTime date = DateTime.Now.Date.AddHours(12).AddMinutes(20);
}
````

 - example 2 : bug if we remove manually the last part of the component (the second part)
````
<input type="time" class="form-control time-control" required 
       step="300"
       @bind="@date"/>
<span>result : @date.ToString()</span>

@code{
    protected DateTime date = DateTime.Now.Date.AddHours(12).AddMinutes(20).AddSeconds(22);
}
````

**Comment by captainsafia** [comment]
Thanks for opening this issue, @julienGrd.

For now, I've only focused on the examples you provided [in this comment](https://github.com/dotnet/aspnetcore/issues/20779#issuecomment-612810917) to avoid debugging any issues in the custom component that might be unrelated to Blazor/HTML.

Considering the edge cases that the bug appears under, I suspect that this is an inconsistency in how the `step` attribute is handled by the browser. Some follow-up questions:

* Are you able to reproduce this in all browsers?
* What behavior are you attempting to achieve with the step property?

**Comment by julienGrd** [comment]
> For now, I've only focused on the examples you provided in this comment to avoid debugging any issues in the custom component that might be unrelated to Blazor/HTML.

Yes sure you are right, the simple example is enough to reproduce the bug, no need to focus on the component

> Considering the edge cases that the bug appears under, I suspect that this is an inconsistency in how the step attribute is handled by the browser

Sure ! So after testing in several browsers, I can confirm you I reproduce with these browsers
Chrome Beta 83.0.4103.34
Microsoft Edge based on chromium 83.0.478.25 
Chrome Official 81.0.4044.129 

I repeat, the bug appear if we manually remove the :ss of the component with suppr key or if we bind directly to a datetime without second.

On firefox 75 it seem OK, it seem impossible to remove the :ss part of the component, so everything works fine

I tried to change culture of my app to see if its related (actually it take my system culture so french), surpisely im unable to do that, even if i set the culture it come back every time to french (on server-side at least)
````
//on the main and on the initialized
var culture = new CultureInfo("en-US");
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
````

> What behavior are you attempting to achieve with the step property

Limit the way the user can enter time, for example for some field i want only value with 5 minutes step. I know this attribute will not "force" the user so it's not enough and i have to put additional code on my side,  but at least the arrow of the time component use it to around.

Good luck !

**Comment by captainsafia** [comment]
It looks like this is a browser-related issue and not much we can do about in Blazor ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Using_the_step_attribute)).

Things seem to work in Firefox because Firefox doesn't actually process the `step` attribute in the same way that other browsers do. It disregards it and just adds a second field.

> In Firefox, there are no arrows, so the step value isn't used. However, providing it does add the seconds input area adjacent to the minutes section.

The `step` attribute isn't respected at all in Edge and only works in Chromium-based browsers, but noticeably impacts the way validation/processing of the input is handled.

Since this attribute doesn't have consistent behavior across browsers, I'd recommend simulating its effects programmatically in an event handler by checking if the user provided input is within a particular interval.
