### ISSUE TITLE
UserManager return null for authenticated user in angular template

### ISSUE THREAD

**Issue by maxbl4** [dotnet/aspnetcore#20780]
### Describe the bug
Can't use UserManager.GetUser(HttpContent.User) to get the currently authenticated user. It returns null

### To Reproduce
1. Create new project from template: dotnet new angular -au individual
2. Add UserManager<ApplicationUser> to the WeatherForecastController and call await userManager.GetUserAsync(User)
3. Observe, that it always returns null. While the user is authenticated and controller actually returns data.
Looks like there is misconfiguration of claim remapping and identity options. Because UserManager expects sub claim and ClaimsPrincipal actually contains ClaimTypes.NameIdentifier
For now i can fix this by disabling claims remapping with this line in startup

   JwtSecurityTokenHandler.DefaultInboundClaimTypeMap = new Dictionary<string, string>();
### Further technical details
- ASP.NET Core version 
3.1.201
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Not applicable

**Comment by maxbl4** [comment]
Some investigation shows, that IdentityServer is overriding the default UserIdClaimType
https://github.com/IdentityServer/IdentityServer4/blob/c87a5e9f77a4ea724748505d2c6431c20edd5b0b/src/AspNetIdentity/src/IdentityServerBuilderExtensions.cs#L37

**Comment by maxbl4** [comment]
So the issue can be worked around by setting UserIdClaimType back to the default value. This can be done by adding the next line anywhere after AddIdentityServer

   services.Configure<IdentityOptions>(x => x.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier);

**Comment by javiercn** [comment]
@maxbl4 thanks for contacting us.

I believe UserManager is only meant to work with the identity from ASP.NET Identity or a compatible one. An alternative way of achieving what you want is to get the id and call the find method, but what you did also works.

**Comment by maxbl4** [comment]
Why do you close this? I use the default ASP.NET Identity for user management and authentication. IdentityServer is used to provide JWT tokens. And I describe the behavior from default asp.net core template. So any developer, who want to simply create a new project will face this issue.

**Comment by marek287** [comment]
No luck. After adding:
```
            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();
            services.Configure<IdentityOptions>(options =>
            {
                options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier;           
            });
```
```
    public class CurrentUserService : ICurrentUserService
    {

        private IHttpContextAccessor _httpContextAccessor;
        public CurrentUserService(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public string UserId { get { return _httpContextAccessor.HttpContext?.User?.FindFirstValue(ClaimTypes.NameIdentifier); } }
    }

UserId is still Null
```
