### ISSUE TITLE
Allow nested editor templates of the same type

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#20787]
When you call an editor template inside another editor template the inner editor template won't render (providing they both have the same model type).

For example say I have a string against my model to select an image URL. Now say I have an editor template called "SelectImage" with the following content:

```
@model string
...
@Html.Editor("Search")
...
```

This is called by feeding in the template name, e.g.:

`@Html.EditorFor(m => m.Image, "SelectImage")`

Where my default string editor template looks like the following:

```
@model string
<input asp-for="@Model" class="form-control" />
```

However the Search field within the SelectImage editor template returns an empty string.

This is an issue that has carried over from [ASP.NET](https://stackoverflow.com/questions/6811717/in-an-editor-template-call-another-editor-template-with-the-same-model).

I have traced the issue to the following lines in the [TempalteBuilder](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.ViewFeatures/src/TemplateBuilder.cs) class:

`if (_viewData.TemplateInfo.Visited(_modelExplorer))
{
    return HtmlString.Empty;
}`

I can understand it is there to prevent infinite loops if an editor template was to call itself. However if someone was to do that then they've made a mistake already and returning an empty string is not their desired result.

I would suggested the whole visited check is not needed, but if you insist on using it then atleast check the template name aswell.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we will invest in.

**Comment by nfplee** [comment]
I would like you to reconsider. I understand your reasoning is that this is using HTML helpers and nowadays the preferred way of doing things is using tag helpers. However there is no built in tag helper for the editor/display templates.

I use @DamianEdwards [tag helper pack](https://github.com/DamianEdwards/TagHelperPack/tree/master/src/TagHelperPack), but I didn't want to over complicate my original example.

Editor/display templates is a great feature and shouldn't simply be discarded whilst you focus all of your efforts on Blazor. There's plenty of developers who still use the tag/html helpers.

**Comment by nfplee** [comment]
I have come up with a temporary solution, that is to set a default value in the view data with the same name as the nested template.
