### ISSUE TITLE
Blazor Router not working

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#20786]
what i noticed is that on click of donation, it refresh loads the entire page again, whereas on click of other link it simply switches to component without causing the refresh load.

**Comment by nssidhu** [comment]
No matter what i do the new pages that i add always run into error **"Sorry, there's nothing at this address."**
I even copied everything from counter component and renamed it to differently and updated Navigate menu to this new name. it still resulted in routing error **"Sorry, there's nothing at this address."**

**My new page Donation**
```
@page "/donation"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }
}

```

**My routerPage**
```
@inject NavigationManager NavigationManager

<div class="top-row pl-4 navbar navbar-dark">
    <a class="navbar-brand" href="">AAAAA</a>
    <button class="navbar-toggler" @onclick="ToggleNavMenu">
        <span class="navbar-toggler-icon"></span>
    </button>
</div>

<div class="@NavMenuCssClass" @onclick="ToggleNavMenu">
    <ul class="nav flex-column">
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="oi oi-home" aria-hidden="true"></span> Home
            </NavLink>
        </li>
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="counter">
                <span class="oi oi-plus" aria-hidden="true"></span> Counter
            </NavLink>
        </li>
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="fetchdata">
                <span class="oi oi-list-rich" aria-hidden="true"></span> Fetch data
            </NavLink>
        </li>
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="donation" >
                <span class="oi oi-list-rich" aria-hidden="true"></span> Donations
            </NavLink>
        </li>
    </ul>
</div>


```

**I am using Visual Studio 2019 Preview version**
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.6.0 Preview 2.1
VisualStudio.16.Preview/16.6.0-pre.2.1+30001.183
Microsoft .NET Framework
Version 4.8.03761

**C:\Users\nssidhu>dotnet --list-sdks**
3.1.201 [C:\Program Files\dotnet\sdk]
3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

**C:\Users\nssidhu>dotnet --info**
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Are your pages in a separate assembly? If that is the case you need to add the assembly to the list of things for the router to scan. It can be done by passing the assembly into the "AdditionalAssemblies" for the router in the App.razor component (if you are using the default template).

**Comment by nssidhu** [comment]
No. its in the same assembly right next to counter.razor and fetchdata.razor under the pages folder

**Comment by nssidhu** [comment]
![blazorRoutingerror1](https://user-images.githubusercontent.com/3267605/79139779-8b9d9b00-7d7c-11ea-8005-04b807ec0955.png)
![BlazorRoutingError3](https://user-images.githubusercontent.com/3267605/79139821-9c4e1100-7d7c-11ea-91c2-14c6c4915200.png)

**Comment by nssidhu** [comment]
![blazorRoutingerror1](https://user-images.githubusercontent.com/3267605/79140020-f51da980-7d7c-11ea-936e-4e9146031da5.png)
![BlazorRoutingError3](https://user-images.githubusercontent.com/3267605/79140035-fc44b780-7d7c-11ea-9d89-900c3b5316bc.png)

**Comment by nssidhu** [comment]
![blazorRoutingerror1](https://user-images.githubusercontent.com/3267605/79140151-25654800-7d7d-11ea-80a2-41dbf964f03f.png)
![BlazorRoutingError3](https://user-images.githubusercontent.com/3267605/79140169-2c8c5600-7d7d-11ea-89d5-1a5bed011500.png)

**Comment by nssidhu** [comment]
Is there a way to check whats in the Route Table ?

**Comment by javiercn** [comment]
@nssidhu can you share a minimal repro project that showcases this issue?

**Comment by rabejens** [comment]
Check your `.csproj` file. I had the exact same problem, when I had the following in my `.csproj`:

```xml
  <ItemGroup>
    <Content Remove="Pages\SomeOtherPage.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\SomeOtherPage.razor" />
  </ItemGroup>
```

This somehow got in there when I added the page (I create Razor pages as Text fioles and rename them because the "New Razor Page" still creates old cshtmls).

When I removed these lines, the page started to work.

**Comment by KapteinBabbalas** [comment]
> Check your `.csproj` file. I had the exact same problem, when I had the following in my `.csproj`:
> 
> ```
>   <ItemGroup>
>     <Content Remove="Pages\SomeOtherPage.razor" />
>   </ItemGroup>
> 
>   <ItemGroup>
>     <None Include="Pages\SomeOtherPage.razor" />
>   </ItemGroup>
> ```
> 
> This somehow got in there when I added the page (I create Razor pages as Text fioles and rename them because the "New Razor Page" still creates old cshtmls).
> 
> When I removed these lines, the page started to work.

That Solved it for me.. Think this happened after some file renaming and refactoring in my case. Working now
