### ISSUE TITLE
Publish hosted PWA from VS is broken

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#20789]
Found during verification. Repro:

 * Create a new Blazor WebAssembly hosted + PWA project
 * Using the VS user interface, publish the "Server" project

Result:

```
Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(191,5): Error : Conflicting assets with the same path '/service-worker.js' for content root paths 'C:\Users\username\source\repos\BlazorApp45\Client\obj\Release\netstandard2.1\blazor\serviceworkers\wwwroot\service-worker.js' and 'C:\Users\username\source\repos\BlazorApp45\Client\wwwroot\service-worker.js'.
```

I'm pretty sure the issue was introduced here: https://github.com/dotnet/aspnetcore/commit/8232c6a4d86872ca2641c2b7379409240056aaef#diff-2d7c5407183e4a97df7698f63cd8a945L92-R181 (link seems not to work correctly, so search for `_OmitServiceWorkerContent` in the diff)

The code in that diff removes one of the two cases where `_OmitServiceWorkerContent` runs, and I think that's the case where it's needed when publishing from VS.

Most likely the fix is just to re-add `ResolveCurrentProjectStaticWebAssetsInputs` to the set of `BeforeTargets` there, but this could use input from @javiercn in case he had different intentions for how this should work.

**Comment by spiralni** [comment]
Any walkaround?

**Comment by SteveSandersonMS** [comment]
Recommended workaround until preview 5 is to publish from the command line.

**Comment by SebChy** [comment]
The problem still exists in preview 5.

**Comment by masoudafar** [comment]
The problem still exists in preview 5.

**Comment by IvanJosipovic** [comment]
I just hit this issue on Preview 5.

**Comment by ShockwaverReal** [comment]
Same here, darn!
PWA 3.2.0-preview5.20216.8
VS 16.6.0 Preview 3.0

ETA? Workarounds?

**Comment by javiercn** [comment]
This is fixed in RC. Didn’t make the cut to preview5

**Comment by ShockwaverReal** [comment]
Suggestions on how your typical NuGet guy can work this around then?

**Comment by SteveSandersonMS** [comment]
@ShockwaverReal Easiest workaround is to publish from the command-line instead (`dotnet publish -c Release`).

Or if your goal is to deploy to Azure App Service, consider deploying via Git (i.e., Kudu). This is much more useful than deploying from VS anyway. In your App Service, go to *Deployment Center*:

![image](https://user-images.githubusercontent.com/1101362/80703499-ce7ca400-8ada-11ea-9eb0-814a5de25b96.png)

... then choose *Local Git*:

![image](https://user-images.githubusercontent.com/1101362/80703597-f79d3480-8ada-11ea-89bb-09c3771df3ef.png)

... then App Service build service (Kudu) and click "Finish":

![image](https://user-images.githubusercontent.com/1101362/80703635-08e64100-8adb-11ea-8ec4-2db65f4ec08a.png)

Then it will give you the URL for a Git repo:

![image](https://user-images.githubusercontent.com/1101362/80703750-46e36500-8adb-11ea-90db-a8c15c48cde7.png)

Add this as an extra remote on your local repo (e.g., `git remote add azure <url>`) and you can push to it (`git push -u azure master`). To get the username/password, click on *Deployment Credentials* as you see in the screenshot above.

**Comment by ericdunn** [comment]
I get this on every build in VS, when trying to debug etc. 
2 workarounds for now if this helps anybody:
1) Do a clean before rebuild
2) Build from command line. 

if you're running a dotnet core hosted blazor app:
(From the server project folder)
dotnet watch run -p ..\Client\(projectname).Client.csproj

This of course doesn't help with debugging.

**Comment by ShockwaverReal** [comment]
Confirmed working with RC1.
Thanks!

**Comment by masoudafar** [comment]
what is RC1?

> Confirmed working with RC1.
> Thanks!

**Comment by ShockwaverReal** [comment]
> what is RC1?
> 
> > Confirmed working with RC1.
> > Thanks!

R(elease)C(andidate)1
Follow [this guide](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/) for creating/updating projects with RC1

**Comment by masoudafar** [comment]
> > what is RC1?
> > > Confirmed working with RC1.
> > > Thanks!
> 
> R(elease)C(andidate)1 (stated available yesterday)
> Follow [this guide](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/) for creating/updating projects with RC1
tnks
