### ISSUE TITLE
Configuration binding in ApiAuthorization.IdentityServer package is very limited

### ISSUE THREAD

**Issue by ngoquoc** [dotnet/aspnetcore#20783]
The option class structure defined in `ApiAuthorization.IdentityServer` package is very limited, which does not enable the full power of IdentityServer. AFAIK, this package eventually turns its specific configurations into `IdentityServer` configurations so IdentityServer can work. So I'm wondering why [this package "invents" a new configuration class](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/ApiAuthorization.IdentityServer/src/Configuration/ResourceDefinition.cs) for resource configuration:
```csharp
internal class ResourceDefinition : ServiceDefinition
{
    public string Scopes { get; set; }
}
```
It is completely understandable that the package needs to deal with some custom logic behind the scene so it introduces new configuration class. But why does it remove so many useful configurations in IdentityServer, namely `UserClaims` and `Scopes.UserClaims`?

For example, in IdentityServer, I can specify the bellow configurations in `appsettings.json` to tell it what are the claims I want to include in the access token when the client asks for the access to this API:
```json
"ApiResources": [
    {
      "Name": "api1",
      "DisplayName": "My API",
      "UserClaims": [ "my_custom_claim" ]
      "Scopes": [
        {
          "Name": "api1",
          "DisplayName": "My API"
        }
      ]
    }
  ]
```

While in this AspNetCore package, I can not. Currently I have to configure it by code in the Startup class, which is definitely worse option than appsettings configuration.

**Comment by javiercn** [comment]
@ngoquoc thanks for contacting us.

All those things are still available for you to configure, our goal is to streamline the configuration for the scenarios while still allowing you to harness the full power of IdentityServer.

For example, you can not setup user claims through configuration, but you can do so within code without problems by simply accessing the configured resource within the options callback.

**Comment by ngoquoc** [comment]
This is what I have in my `ConfigureServices()` as a work around just in case someone needs it:
```csharp
services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
    {
        foreach (var apiResource in options.ApiResources)
        {
            Configuration.GetSection($"IdentityServer:Resources:{apiResource.Name}:UserClaims")
                .Bind(apiResource.UserClaims);
        }
    });
```
