### ISSUE TITLE
dotnet publish leaving out local package dependencies 

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#20794]
I'm running into an issue after installing SDK 3.1.201 where dotnet publish is not publishing local package dependencies.  The project I am using references the blazor web assembly preview which I'm not sure if it is related to the issue. Adding the local package dependence directly to the published csproj does not seem to help either. 

See csproj below. The reference AppPotion.Sandbox is dependent on AppPotion.Api. The api dll's are not being include even if I add <PackageReference Include="AppPotion.Api" Version="2.0.0" /> directly to the csproj.

```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">
  <!--Base Template: dotnet new web -->
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!--Added manually to allow blazor wasm bundleing-->
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="3.2.0-preview3.20168.3" />
    <PackageReference Include="AppPotion.Sandbox" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppPotion.Bd.Client\AppPotion.Bd.Client.csproj" />
  </ItemGroup>

</Project>
```

**Comment by ericstj** [comment]
@Pilchie @danroth27 in case this is web or blazer  specific.  @dsplaisted in case it is sdk.

**Comment by javiercn** [comment]
We'll take a look.

**Comment by pranavkm** [comment]
This should be fixed as part of the preview4 release that went out earlier today. Let us know if you still see this after upgrading: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/

**Comment by groogiam** [comment]
Just upgraded my test project and it looks like that fixed the issue. Thanks.
