### ISSUE TITLE
When to use ChildContent and Why?

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#20798]
Usually I see this approach to create a Parent containing a Child. Valid to say Foo must have a parameter named `ChildContent`.
``` C#
builder.OpenComponent<Foo>(0);
//other n attributes
builder.AddAttribute(n+1, "ChildContent", (RenderFragment)((builder2) => {
    builder2.AddContent(n+2, "Hello from Foo");
}));
builder.CloseComponent();
```
But, at the same time, I can also achieve the same result not having the `ChildContent` parameter and just doing this.
``` C#
builder.OpenComponent<Foo>(0);
//other n attributes
builder.AddContent(n+1, "Hello from Foo");
builder.CloseComponent();
```
Then, When should I have a ChildContent? Why? Is there any benefit?

**Comment by EdCharbeneau** [comment]
If I understand the question correctly. ChildContent is needed explicitly when there are other RenderFragments and the ChildContent can't be implicitly assigned.

**Comment by yopez83** [comment]
> If I understand the question correctly. ChildContent is needed explicitly when there are other RenderFragments and the ChildContent can't be implicitly assigned.

Then, `EditForm` defines a ChildContent since implicitly doesn't know what its content will be. Instead delegate the responsibility of defining the content to the developer. However, if you have the control over what the content is (like in my second snippet above), there is no need for having a ChildContent, right?

**Comment by EdCharbeneau** [comment]
ChildContent is specifically intended to let a component act as a generic container or template. If you're not intending someone to set the inner content then ChildContent is not useful to you.

**Comment by yopez83** [comment]
Fair enough. Thanks
