### ISSUE TITLE
Warning about UseAuthorisation in Map

### ISSUE THREAD

**Issue by Freeesia** [dotnet/aspnetcore#20807]
### Describe the bug
If I implement `.UseRouting()` and `.UseEndpoints()` in and out of `app.Map()`, respectively, and `.UseAuthorization()` in `app.Map()`, I will get `ASP0001` warning.

### To Reproduce
``` C#
app.Map("/api", apiApp =>
{
    apiApp.UseRouting();
    apiApp.UseAuthentication();
    apiApp.UseAuthorization(); // ASP0001 warnings occur.
    apiApp.UseEndpoints(ep => ep.MapControllers());
});
app.UseRouting();
app.UseEndpoints(ep => ep.MapHealthChecks("/health"));
app.UseSpa(_ => { });
```

See `warning ASP0001: The call to UseAuthorization should appear between app.UseRouting() and app.UseEndpoints(..) for authorization to be correctly evaluated.`

### Expected

No warnings

### Further technical details
- ASP.NET Core version
  - 3.1
- Include the output of `dotnet --info`
```
.NET Core SDK (global.json を反映):
 Version:   3.1.200
 Commit:    c5123d973b

ランタイム環境:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  - VS Code 1.44
  - C# Extension(ms-dotnettools.csharp) 1.21.17

**Comment by blowdart** [comment]
@pranavkm this is your analyzer isn't it?

**Comment by Kahbazi** [comment]
@Freeesia What I'm about to say has nothing to do with the warning but it seems you would like to have two separate pipeline for your application. One for controllers and one for health check and spa, and you are using `UseRouting` and `UseEndpoints` middleware twice. As far as I know `UseEndpoints` middleware is bind to one source and it doesn't matter if you are using it in separate middleware. All the mapping goes to one source and `UseRouting` find the route from that one source.
The team could correct me if I'm wrong but if there's an controller and action which its path is not started with api, it will get executed in the second `UseEndpoints` middleware

**Comment by Freeesia** [comment]
@Kahbazi 
> you would like to have two separate pipeline for your application.

Yes.`UseSpa()` has a fallback feature that returns `index.html` for unknown paths, but I want to return a 404 error when a non-existent controller is called.
I was bothered to include health check in `/api`, but this time the problem came up when I decided not to include them in `/api`.

> As far as I know `UseEndpoints` middleware is bind to one source and it doesn't matter if you are using it in separate middleware. All the mapping goes to one source and `UseRouting` find the route from that one source.

Unfortunately, I don't understand the above, what does `one source` refer to?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
