### ISSUE TITLE
Supporting customizing query params in redirect URL for OpenID auth

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#20813]
It is a question!

I have a Blazor WASM SPA. It calls an external IdP authenticate interactive users. The SPA can then use the bearer token to call a seperate API.

How do we pass an additional parameter(option) with the AddOidcAuthentication extension method? The parameter should be added as a query string parameter to the login call of the IdP before redirect.
My code looks like:

builder.Services.AddOidcAuthentication(o => {
              o.ProviderOptions.Authority = "https://login.xservices.online";
              o.ProviderOptions.ClientId = "my-app";
              o.ProviderOptions.RedirectUri = "http://localhost:5000";
              o.ProviderOptions.PostLogoutRedirectUri = "/";
              o.ProviderOptions.ResponseType = "id_token token";
              o.ProviderOptions.DefaultScopes.Add("email profile openid");
            });
and now i need something like this: o.ProviderOptions.queryParam("bypass=true"); 
O maybe a can interfere before redirect to the IdP by catching an event?

Additional context
I used the following article as a basis: https://docs.microsoft.com/en-gb/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is currently not supported.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by gofrogi** [comment]
thank you for your answer. Is there a possibility to get the redirect URL, that will be generated from given ProviderOptions, before it will be sent to identity provider and patch it? In ASP.Net it was possible to do something like that:

options.Events.OnRedirectToIdentityProvider = ctx =>
                {
                    ctx.ProtocolMessage.Parameters.Add("bypass", "true");
                    return Task.CompletedTask;
                };

i have tried to go between in LocationChanged event, but was not able to get the real redirect URL.

**Comment by mkArtakMSFT** [comment]
@javiercn do you know?

**Comment by javiercn** [comment]
No, this is not possible with our current implementation.

**Comment by timcromarty** [comment]
I also have this requirement. Is there an idea what timeframe this may be implemented.  It's a blocker to implementing Blazor without it.
Alternatively, can AddOpenIdConnect be used in a Blazor WASM client?

**Comment by thisispaulsmith** [comment]
This issue has gone a little stale. 

The scenario of passing additional params to an identity provider seem common place. In Blazor server it's easy.

```csharp
options.Events = new OpenIdConnectEvents
{
  OnRedirectToIdentityProvider = (context) =>
  {
    context.ProtocolMessage.SetParameter("xxx", "xxx");
    return Task.CompletedTask;
  }
}
```

How are we suppose to achieve similar with Blazor WASM? Is there a workaround?

**Comment by Asshiah** [comment]
In fact, it is absolutely blocking to not be able to specify additional parameters 'in query string) for the login call to the IDP provider (Auth0 in my case) as we have no means to specify the audience for the API we need access to on top of simply authenticating.

**Comment by robertmclaws** [comment]
Kinda crazy this is not supported, given that passing additional parameters also lets you redirect the user back to the page they were on before the redirect was triggered.

**Comment by Jarrich** [comment]
Any update on this?

**Comment by GordonRudman** [comment]
Hi,

This issue was opened about a year ago now.
So is there any movement on this yet? 
It seems like a rather simple change that needs to be made in the MS libraries.

This is also a blocker for me because I can't specify the Audience I need when requesting access tokens to my APIs.
I'm using Auth0 as my IdP and followed their workaround to this bug (they allow you to specify a single fallback audience on their backend), but that only allows me to connect to a total of 1 APIs for all my applications, which is obviously not a workable solution. 

I'm using Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider.RequestAccessToken() which has an option to pass in AccessTokenRequestOptions as options, but that only lets me pass in Scopes and ReturnUrl.
So it looks like there is already a mechanism in place to handle this sort of thing, it just isn't complete yet.
Please can we get this fixed soon, or at least get a usable workaround to this situation?

Thanks

**Comment by ar0311** [comment]
I've used the following with Auth0 in Program.cs of the WASM project:


```
builder.Services.AddOidcAuthentication(options =>
       {
                // Configure your authentication provider options here.
                // For more information, see https://aka.ms/blazor-standalone-auth
                builder.Configuration.Bind("Auth0", options.ProviderOptions);
                options.ProviderOptions.ResponseType = "code";
                options.ProviderOptions.AdditionalProviderParameters.Add("audience", "<YOUR-API-URL-HERE>");
            });
```

You do not need to use the workaround of setting a default API in Auth0 by using the above code.

**Comment by Ewan-S** [comment]
> 
> 
> I've used the following with Auth0 in Program.cs of the WASM project:
> 
> ```
> builder.Services.AddOidcAuthentication(options =>
>        {
>                 // Configure your authentication provider options here.
>                 // For more information, see https://aka.ms/blazor-standalone-auth
>                 builder.Configuration.Bind("Auth0", options.ProviderOptions);
>                 options.ProviderOptions.ResponseType = "code";
>                 options.ProviderOptions.AdditionalProviderParameters.Add("audience", "<YOUR-API-URL-HERE>");
>             });
> ```
> 
> You do not need to use the workaround of setting a default API in Auth0 by using the above code.

Could you specify the version of the nuget packages and runtime you are using please. I'm using the latest full-release, version 5.0.4, and OidcProviderOptions doesn't define AdditionalProviderParameters.

**Comment by GordonRudman** [comment]
@ar0311 
Thank you so much for the response! It's much appreciated.
Unfortunately, like @Ewan-S, the 'AdditionalProviderParameters' property isn't available to me.
I'm however also using version 5.0.4 of the Nuget packages, so that's not really unexpected.

I'm assuming the change is available on .Net 6.0 perhaps? 
I tried to use .Net 6.0 a few days ago, but ran into all sorts of issues deploying to an Azure Web App, so rolled back to .Net 5.0 for now.

**Comment by ar0311** [comment]
Hi guys,

Sorry forgot to mention I'm on 6.0 pre2

**Comment by vanillajonathan** [comment]
The `AdditionalProviderParameters` property in Blazor 6 does not cover all use cases, it is static and cannot be used to dynamically add query parameters.

Example:
```cs
OnRedirectToIdentityProvider = (context) =>
{
    var tenant = context.Request.Query.FirstOrDefault(x => x.Key == "tenant");
    context.ProtocolMessage.SetParameter("tenant", tenant);
    return Task.CompletedTask;
}
```

**Comment by anktsrkr** [comment]
My scenario is - I have two API which means I have two audience created in Auth0 dashboard. And both APIs are working as expected.

However, when I am trying to invoke those APIs from Blazor WASM one of the API fetching data and the other one is getting invalid audience.

I am using .NET 6 where Team introduced `AdditionalProviderParameters `so for one of API I have added -

```
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("Auth0", options.ProviderOptions);
    options.ProviderOptions.ResponseType = "code";
    options.ProviderOptions.AdditionalProviderParameters.Add("audience", "https://quizapi.sarkaran.ml/");
    
});
```
Which seems to be working fine. However When I am adding another audience, it starts failing -

```
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("Auth0", options.ProviderOptions);
    options.ProviderOptions.ResponseType = "code";
    options.ProviderOptions.AdditionalProviderParameters.Add("audience", "https://quizapi.sarkaran.ml/");
    options.ProviderOptions.AdditionalProviderParameters.Add("audience", "https://weatherforecastapi.sarkaran.ml/"); // <- That seems to be not working.

});
```

I have tried by setting Default Audience from Auth0 Setting as well, but no luck. So my question is in case I need to call more than one API how to set the multiple audience?

**Comment by air1x1** [comment]
Wow, yea having a to dynamically change these values would be a wonderful addition.

I'm using Auth0's '[Invite Organization Members](https://auth0.com/docs/manage-users/organizations/configure-organizations/invite-members#specify-route-behavior)' and was having a heck of a time getting it to work using `Blazor` and `Webassembly`.

Thankfully, I stumbled on the `AdditionalProviderParameters` property using `ILSpy` and then found this post.

I was able to get `Invite Organization Members` to work by simply extracting the values from the query string when the application is loaded. It's defiantly not ideal but it works for my situation.

```csharp
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.AspNetCore.WebUtilities;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

var app = new WebAssemblyHost[1];
builder.Services.AddOidcAuthentication(options =>
{
    var navigationManager = app[0].Services.GetRequiredService<NavigationManager>();
    var uri = navigationManager.ToAbsoluteUri(navigationManager.Uri);
    if (QueryHelpers.ParseQuery(uri.Query).TryGetValue("invitation", out var invitation))
    {
        options.ProviderOptions.AdditionalProviderParameters.Add("invitation", invitation);
    }
    if (QueryHelpers.ParseQuery(uri.Query).TryGetValue("organization", out var organization))
    {
        options.ProviderOptions.AdditionalProviderParameters.Add("organization", organization);
    }
    builder.Configuration.Bind("Auth0", options.ProviderOptions);
    options.ProviderOptions.ResponseType = "code";
});
app[0] = builder.Build();
await app[0].RunAsync();
```

**Comment by mkArtakMSFT** [comment]
Thanks for your patience, everyone.
This is now supported as part of https://github.com/dotnet/aspnetcore/issues/42580
