### ISSUE TITLE
unable to ge controller name and method type in AuthorizationHandler  in dotnet core 3.1

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/aspnetcore#20814]
Hello, we updated our application from 2.2 to 3.1. we were using AuthorizationFilterContext to get the controller name in custom authorization. Now it is showing null. Actually our custom authorization needs controller name and method type to evaluate the requirements. but in dot net core 3.1 AuthorizationFilterContext is coming null. so please help me how can i get controller name and method type in custom filter? please help me solve this problem

**Comment by pranavkm** [comment]
If you're using endpoint routing, `Resource` is an instance of `Endpoint`. https://github.com/dotnet/AspNetCore.Docs/pull/17829/files has a sample of what getting the action descriptor from an `Endpoint` would look like.
