### ISSUE TITLE
CertificateAuthenticationFailedContext doesn't terminate the HTTP request

### ISSUE THREAD

**Issue by gsaggu** [dotnet/aspnetcore#20811]
[EDIT by guardrex to add the metadata. @gsaggu, use the **This page** feedback button and form at the bottom of any topic to have the metadata automatically added, which also automatically pings the author.]

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1

i did followed this documentation and certificate authentication works as expected. The issue i am having is when i invoke context.fail() inside OnCertificateValidated event the HTTP request doesn't get terminated.

It still keeps executing and reaching to api controller which is again protected by [Authorize] attribute

recently created a stackoverflow request 

https://stackoverflow.com/questions/61091896/certificateauthenticationfailedcontext-doesnt-terminate-the-http-request 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
Moved as this is not a docs issue.

This is expected, we cannot drop the connection due to how the interplay between connection and app code, nor would we expect to anyway, as the user may continue to a valid request.

**Comment by anurse** [comment]
From your StackOverflow post it sounds like it's still running the controller, which is definitely not expected. Can you provide a runnable sample that reproduces the problem so we can see the full context? It's possible there's something else about your application configuration that's causing an issue here.
