### ISSUE TITLE
Microsoft.Web.Xdt.Extensions shows up as a package dependency in Microsoft.AspNetCore.AzureAppServices.SiteExtension

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#20818]
Microsoft.AspNetCore.AzureAppServices.SiteExtension has a package dependency on Microsoft.Web.Xdt.Extensions, even though the reference is listed as PrivateAssets="all"

**Comment by Pilchie** [comment]
@BrennanConroy  - do you know what's up here?

**Comment by Pilchie** [comment]
Also @anurse since this is related to #20817 20817

**Comment by dougbu** [comment]
This is likely a problem in eng/targets/ResolveReferences.targets in particular `PrivateAssets="all"` metadata seems to be lost, producing a package with an unintended ref to an internal project that isn't even packable. Putting this on our build board&hellip;

**Comment by BrennanConroy** [comment]
Fortunately this doesn't seem to affect consumption of the package.

**Comment by anurse** [comment]
> Putting this on our build board

We should try to prioritize this. Let me know @dougbu if this isn't going to make it this "sprint" and we can look at what we can do. As @BrennanConroy says, it doesn't actually affect usage because Site Extension dependencies aren't even considered when Azure App Service installs them.

**Comment by dougbu** [comment]
Does this still happen now that we're using `JoinItems` in eng/ResolveReferences.targets❔ That only went in a few days ago.

**Comment by dougbu** [comment]
Or, do we need to port my `JoinItems` change to 'release/3.1' to fix this❔

**Comment by wtgodbe** [comment]
This was validating a build of master at SHA 2743965bc585c63e5ee2d44d129495c37ade7277 (5/4/20 at 8:39 AM)

**Comment by dougbu** [comment]
Ah, the problem is that we're trying to use `PrivateAssets="all"` in [Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj](https://github.com/dotnet/aspnetcore/blob/a9d702624a02ad4ebf593d9bf9c1c69f5702a6f5/src/SiteExtensions/LoggingAggregate/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj#L43). That should be `ReferenceOutputAssembly="false"` to work outside `@(PackageReference)` items.

Safest to include both metadata bits so the `@(Reference)` item works whichever the final item group it lands in.

**Comment by dougbu** [comment]
I can do this quickly if you're working elsewhere @wtgodbe. LMK

**Comment by wtgodbe** [comment]
@dougbu sure, go for it

**Comment by dougbu** [comment]
BTW I was wrong. The problem is in the static `<ItemGroup>`s in eng/ResolveReferences.targets. I'm looking at switching those to be inside a `<Target>` and using `<JoinItems>` to ensure metadata is preserved.

**Comment by dougbu** [comment]
I have a draft PR out for this but am not optimistic about it. We'll see&hellip;

(There's a fallback option but it's _really_ ugly.)

**Comment by dougbu** [comment]
e13368391b02

**Comment by dougbu** [comment]
See #20817
