### ISSUE TITLE
Intellisense for partial class not working

### ISSUE THREAD

**Issue by ahlurien** [dotnet/aspnetcore#20812]
When placing the code for a blazor component in a code behind file using a partial class the code runs ok, but Intellisense underlines the class members in red and says "the name x does not exist in the current context"

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen we'll need to fix this if this is real issue.

**Comment by mkArtakMSFT** [comment]
@ahlurien can you please confirm that you're seeing this with the latest VS preview release?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
