### ISSUE TITLE
Microsoft.AspNetCore.AzureAppServices.SiteExtension has dependency on non-shipping Microsoft.Web.Xdt.Extensions

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#20817]
In the latest 5.0 preview3 build, the Microsoft.AspNetCore.AzureAppServices.SiteExtension package, which is marked as shipping, has a dependency on a non-shipping package Microsoft.Web.Xdt.Extensions.

Should this package be marked as shipping at all? There are no other 5.0 versions listed on nuget.org

**Comment by anurse** [comment]
Is this different from https://github.com/dotnet/aspnetcore/issues/20818 ? Seems like we could track it in one issue.

**Comment by BrennanConroy** [comment]
@dougbu  This is the same as https://github.com/dotnet/aspnetcore/issues/20818 right?

**Comment by dougbu** [comment]
Right. This should also be closed by e13368391b0220ba4404f2c5f448fd5f2733a70b.
