### ISSUE TITLE
Local Razor LSP Editor completion always shows "Starting IntelliSense..."

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#20828]
Performing any completion HTML or C# result in:
![image](https://user-images.githubusercontent.com/2008729/79281944-bb29d180-7e68-11ea-9e86-1d001f53d772.png)

Can reproduce by:
- Download VSMaster
- Enable LSP Powered Razor Editor in the preview features
- Create a new Razor project
- Open a Razor file and type `@` or `<` to get C# or HTML completion respectively.

@AmadeusW is this an LSP client issue or a VS completion issue?

**Comment by AmadeusW** [comment]
This is controlled by "Partial Load Mode". @varunguptacode was the PM IIRC
Roslyn is [also investigating this issue](https://github.com/dotnet/roslyn/issues/43096)

**Comment by NTaylorMullen** [comment]
I actually think this has gone away. @ajaybhargavb / @ryanbrandenburg / @TanayParikh have you continued to see this?
