### ISSUE TITLE
Need help in understanding why host.Configuration["WeatherServiceUrl"] returns null

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#20823]
I'm referring to the  [sample code](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#blazor-webassembly) which purportedly demonstrates how to read a value from a default configuration source; I've added an appsettings.json file to my WebAssembly app with settings like: "WeatherServiceUrl": "http://worldweather.wmo.int/en/home.html", but host.Configuration["WeatherServiceUrl"] always returns null. What am I doing wrong ?

```
public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.Services.AddSingleton<WeatherService>();
        builder.RootComponents.Add<App>("app");

        var host = builder.Build();

        var weatherService = host.Services.GetRequiredService<WeatherService>();
        await weatherService.InitializeWeatherAsync(
            host.Configuration["WeatherServiceUrl"]);

        await host.RunAsync();
    }
}
```

**Comment by pranavkm** [comment]
Is your appsettings file located under `wwwroot`: https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#configuration?

**Comment by enetstudio** [comment]
Got it...problem solved...many thanks.
