### ISSUE TITLE
Blazor FileProviders

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#20820]
Does Blazer support using File Providers?
If yes, how to configure them to add my file provider? her to call this:
`AddRazorRuntimeCompilation(options => options.FileProviders.Add(myFp));`
If no, why not?

**Comment by SteveSandersonMS** [comment]
Could you clarify what your scenario is? Where are you trying to use a file provider, and for what purpose? And are you talking about Blazor Server or Blazor WebAssembly?

**Comment by VBAndCs** [comment]
I am trying to virtually provide the contents of the .razor file to the Blazor WebAssembly, so can I do this using a virtual file provider, like we can do with MVC views and Razor Pages?

**Comment by VBAndCs** [comment]
In the Blazor project crated by the webasm project template, 
I added a breakpoint on the first line of `Program.Main`, but execution never stops at it. Why?

**Comment by VBAndCs** [comment]
In the Blazor project crated by the webasm project template, 
I added a breakpoint on the first line of `Program.Main`, but execution never stops at it. Why?

**Comment by SteveSandersonMS** [comment]
@VBAndCs I'm afraid there is no concept of runtime compilation for `.razor` files, because unlike `.cshtml` files, they are always referenced in a strongly typed way. They are part of the same compilation process that builds your `.cs` files and cannot be compiled at runtime.

So I'm afraid what you're trying to do won't work.

However if you could describe more broadly what your goals are then I might be able to suggest a different approach.

**Comment by VBAndCs** [comment]
A different approach is to generate the c# razor classes myself from the blazor code. Could you please giveme the link to the class that generates the app.g.cs file from the app.razor file?

**Comment by SteveSandersonMS** [comment]
The Razor compiler is built as a tool called `rzc.dll` which is provided with `Microsoft.NET.Sdk.Razor`.

The sources for the Razor compiler are at https://github.com/dotnet/aspnetcore-tooling/tree/master/src/Razor

**Comment by VBAndCs** [comment]
@SteveSandersonMS 
Thanks. I will look at it

**Comment by VBAndCs** [comment]
I built the source but I get a runtime exception that .NET 5 Sdk preview 4 is missing. I can't find this ver anywhere.
