### ISSUE TITLE
Requesting to see FirstName and LastName - User.FindFirstValue(ClaimTypes.GivenName)

### ISSUE THREAD

**Issue by Devnsyde** [dotnet/aspnetcore#20821]
My request is similar to the following post that has already been closed:
https://github.com/dotnet/aspnetcore/issues/18348

I'd like to see the users's first name and last name. I think you would usually get that through ClaimTypes.GivenName

**Comment by blowdart** [comment]
Identity does not have first names, or last names, or anything other than username and password and email by default. So there's nowhere to get it from in this case, unlike the linked issue. If you have a custom schema you can do it yourself by scaffolding and overriding login, or via claims transformation.

**Comment by Devnsyde** [comment]
Ok. Nevermind then. I guess I assumed it was there when I type ClaimsType.GivenName its available just returns null.

**Comment by blowdart** [comment]
Nope, that's actually from LDAP and WS-Fed, because history. Some external identity providers will have it too, but standard core identity does not.
