### ISSUE TITLE
Validation Summary Not Rendering When Empty Causes Frontend Problems

### ISSUE THREAD

**Issue by bradlis7** [dotnet/aspnetcore#20822]
It looks like something recently changed with Validation Summary, and it's not rendering when there are no errors to show.

```
<div asp-validation-summary="ModelOnly"></div>
```

Results in nothing.

Note that MS [documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-3.1#the-validation-summary-tag-helper) is wrong, as it says this is the expected output: 

```
<div class="validation-summary-valid" data-valmsg-summary="true">
  <ul><li style="display:none"></li></ul></div>
```

When I attempt to add an error on the frontend, it throws an error:

```
$("#AccessRequestForm").validate().showErrors({"": "Model-level error."});
```

Error:

```
TypeError: element is undefined
    highlight 
    defaultShowErrors 
    showErrors 
```

I'm targeting "netcoreapp3.1". Using the following JS libraries:
jquery-validation 1.19.1, jquery-validation-unobtrusive 3.2.11.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as we haven't heard similar feedback from the community. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by bradlis7** [comment]
I gave a clear way of verifying the issue @mkArtakMSFT . Just because it's not common doesn't mean it's ok to ignore. Please reopen.
