### ISSUE TITLE
Set the AuthenticationResult via a new feature on the HttpContext

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#20847]
Today the authentication middleware resolved the `AuthenticateResult` for the current request/endpoint and stores the Principal on the HttpContext but doesn't store the other properties (Ticket, or AuthenticationProperties). Getting at these requires another call to AuthenticateAsync with the right scheme which can be a pain to get at. We should make this available via a feature on the HttpContext

cc @Tratcher @HaoK

**Comment by blowdart** [comment]
Could this be the result be extended out to give people that feature they want to return reasons from policies?

**Comment by HaoK** [comment]
We could do something similar for the authz middleware, but what would it be, like the result of the last authorization failure?

**Comment by blowdart** [comment]
Well you know there have been lots of requests for this sort of thing, including allowing information on why a policy failed, which mixes authn and authz in a way we don't like, but if this could be used it might make a lot of people happy.

**Comment by HaoK** [comment]
This isn't likely to be what you are looking for as it really only maps to the default authenticate call we do in the auth middleware

**Comment by blowdart** [comment]
Darn it :(

**Comment by anurse** [comment]
Is this servers? Feels more like security. Moving it for now.

**Comment by blowdart** [comment]
Told ya :) https://github.com/dotnet/aspnetcore/issues/21116

**Comment by BrennanConroy** [comment]
Reopening as this is something SignalR would like to have.

**Comment by BrennanConroy** [comment]
Idea: Using a DIM, we can add the Ticket to the `IHttpAuthenticationFeature`, then if the User is set by someone else the Ticket could be nulled out so we don't have inconsistency with the two values, and we would remap the User to the Ticket.User.

**Comment by blowdart** [comment]
@BrennanConroy As part of the signalr PR can you address this as well?

**Comment by BrennanConroy** [comment]
We'll need to rethink this change. Adding `AuthenticationTicket` to the `IHttpAuthenticationFeature` creates a circular reference between Http.Features and Authentication.Abstractions.

**Comment by BrennanConroy** [comment]
Looking through the code, would adding a new feature (`IAuthenticateResultFeature`) after https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L70 work?

**Comment by Tratcher** [comment]
You still have the issue of the ticket being out of sync with the User. How about adding the new feature, but implement it with a class that also implements IHttpAuthenticationFeature and does the user re-mapping?

**Comment by Tratcher** [comment]
Set it here:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Security/Authorization/Policy/src/PolicyEvaluator.cs#L52-L53

**Comment by BrennanConroy** [comment]
Why set it there and not right outside that call? Someone could replace the `IPolicyEvaluator`, so doing the work regardless of the implementation of that interface would be better.

**Comment by Tratcher** [comment]
Only to be consistent about assigning User vs Ticket. I don't know if anyone calls the IPolicyEvaluator outside of the middleware.

**Comment by HaoK** [comment]
Well its was intended so if you wanted to be able to mimic 'normal auth', you could use the policy evaluator, so I guess it should have the same semantics as setting the User today ideally
