### ISSUE TITLE
Make RequestServices work for cloned longpolling HttpContext

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#20846]
Today we return an empty IServiceProvider, instead, we should create a new scope and stash it on the connection https://github.com/dotnet/aspnetcore/blob/162817d3f05f62b54589af553396525e03986679/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionDispatcher.cs#L666.

**Comment by halter73** [comment]
We'll need to create a service scope ourselves that matches the connection lifetime.

**Comment by davidfowl** [comment]
Ya, see https://github.com/dotnet/aspnetcore/blob/162817d3f05f62b54589af553396525e03986679/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionDispatcher.cs#L663
