### ISSUE TITLE
IFeatureCollection has been disposed in ActionFilterAttribute

### ISSUE THREAD

**Issue by shuba-developer** [dotnet/aspnetcore#20840]
I'm using Net Core 3.1 for my web application. It's `sometimes` getting error in  `ActionFilterAttribute` when accessing `HttpContext`.
Startup.cs Configure

   `config.Filters.Add(typeof(RequestAuthorizationAttribute ));`

Class Implementing ActionFilterAttribute

    [AttributeUsage(AttributeTargets.Class)]
    public class RequestAuthorizationAttribute : ActionFilterAttribute
    {
        private readonly Ext.HttpClientApi client;
        private readonly IMemoryCache cache;

        public RequestAuthorizationAttribute(Ext.HttpClientApi client, IMemoryCache cache)
        {
            this.client = client;
            this.cache = cache;
        }

        public async override void OnActionExecuting(ActionExecutingContext context)
        {
            if (context.HttpContext.Request.IsValidRequest())
            {
				return;
			}
			
			var list = new List<UserAuthorization>();
			var userId = context.HttpContext.User.Identity.Name;
			if (cache.TryGetValue(userId, out object value))
			{
				list = value as List<UserAuthorization>;
			}
			else
			{
				var options = new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromHours(10));

				var url = "http://someurl.com/other/api";
				list = await client.Get<List<UserAuthorization>>(url, "result");
				// Save data in cache.
				cache.Set(userId, list, options);
			}
				
			var data = new ValidRequestViewModel
			{
				Success = false,
				Message = "Your request is invalid.",
				Data = new ValidRequestViewModel.DataError
				{
					Header = "Invalid User Request",
					List = list
				}
			};
		       //**error here. IFeatureCollection has been disposed**
			context.HttpContext.Session.Set("error", data.ToByteArray()); 
			context.HttpContext.Items.Remove("app_error");
			context.HttpContext.Items.Add("app_error", data);

			context.Result = new RedirectToRouteResult(new
			{
				action = "Error",
				controller = "Home",
				area = ""
			});
            
        }

Extension method consumed by the attribute

        public static bool IsValidRequest(this HttpRequest request)
        {
		//**cannot access request because it is considered as disposed object**
		if (request.Headers.TryGetValue("X-APP-CHECKOUT", out StringValues requestedWith))
		{
			//mycode goes here ....
		}
        }

**Comment by davidfowl** [comment]
Are you using the IHttpContextAccessor anywhere?

**Comment by shuba-developer** [comment]
Yes, in the my service as shown below

```
public interface IEmployeeService { }
public class EmployeeService : IEmployeeService 
{
	IHttpContextAccessor _accessor
	public Employee(IHttpContextAccessor accessor)
	{
		_accessor = accessor;
	}
	//other methods using the _accessor
}
```

**Comment by davidfowl** [comment]
Do you have any logic that's storing the HttpContext in a field or maybe holding on to it longer than the request itself?

**Comment by shuba-developer** [comment]
No, I don't

**Comment by davidfowl** [comment]
- Can you show me usage of the IHttpContextAccessor in EmployeeService ?
- Are you using application insights?

**Comment by shuba-developer** [comment]
I don't use application insights.

	public class DataContext : DbContext
    {
        readonly IConfiguration configuration;
        readonly IHttpContextAccessor accessor;

        public HttpContext HttpContext => accessor.HttpContext;

        public DataContext()
        {
        }

        public DataContext(DbContextOptions<DataContext> option, IConfiguration configuration, IHttpContextAccessor accessor)
          : base(option)
        {
            this.configuration = configuration;
            this.accessor = accessor;
        }
		
		public DbSet<Employee> Employees { get; set; }
	}
		
	public static class DataContextDbExtension
    {
        public static IEnumerable<EntityEntry<TEntity>> ServiceAdd<TEntity>(this DataContext context, params TEntity[] entities) where TEntity : class
        {
            var list = new List<EntityEntry<TEntity>>();
            foreach (var entity in entities)
            {
                var userName = context.HttpContext.User.Identity.Name;
                entity.SetDefaultBaseEntity(userName);
                var val = context.Add(entity);
                list.Add(val);
            }
            return list;
        }
		
	public static void SetDefaultBaseEntity<T>(this T entity, string value) where T : class
        {
            if (string.IsNullOrWhiteSpace(value))
                value = "SYSTEM";

            var bindingFlags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase;

            var type = entity.GetType();
            type.GetProperty("CreateBy", bindingFlags)?.SetValue(entity, value);
            type.GetProperty("CreateDate", bindingFlags)?.SetValue(entity, DateTime.Now);
            type.GetProperty("UpdateBy", bindingFlags)?.SetValue(entity, value);
            type.GetProperty("UpdateDate", bindingFlags)?.SetValue(entity, DateTime.Now);
            type.GetProperty("IsDelete", bindingFlags)?.SetValue(entity, false);
        }

    }
	
    public interface IEmployeeService : IServiceSingleKey<Employee, int>
    {
    }

    public class EmployeeService : IEmployeeService 
    {
        readonly DataContext context;
        public EmployeeService (DataContext context) => this.context = context;

        public async Task<int> AddAsync(Employee TEntity)
        {
            context.ServiceAdd(TEntity);
            return await context.SaveChangesAsync();
        }
    }

**Comment by davidfowl** [comment]
Can you share the stack trace for the exception?

**Comment by davidfowl** [comment]
Who accesses DataContext.HttpContext?

**Comment by shuba-developer** [comment]
`EmployeeService  `accesses it. I inject `DataContext` to the `EmployeeService` constructor where the `DataContext` contains `HttpContext` property and the property of `HttpContext` is accessed everywhere in the service

**Comment by shuba-developer** [comment]
> n you share the stack trace for the exception?

I'll post here if it's getting error

**Comment by davidfowl** [comment]
> EmployeeService accesses it. I inject DataContext to the EmployeeService constructor where the DataContext contains HttpContext property and the property of HttpContext is accessed everywhere in the service

I need to see more code where the HttpContext is being accessed. 

In theory this shouldn't happen at this state in the pipeline so it would be great if we had a stack trace and a repro of the issue.

**Comment by javiercn** [comment]
@shuba-developer thanks for contacting us.

In order for us to help you, we need you to provide a minimal repro project that demonstrates this issue.

**Comment by shuba-developer** [comment]
> @shuba-developer thanks for contacting us.
> 
> In order for us to help you, we need you to provide a minimal repro project that demonstrates this issue.

OK. I'll provide it soon

**Comment by shuba-developer** [comment]
> > EmployeeService accesses it. I inject DataContext to the EmployeeService constructor where the DataContext contains HttpContext property and the property of HttpContext is accessed everywhere in the service
> 
> I need to see more code where the HttpContext is being accessed.
> 
> In theory this shouldn't happen at this state in the pipeline so it would be great if we had a stack trace and a repro of the issue.

```
at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at WebExtension.WebApp.RequestAuthorizationAttribute.<OnActionExecuting>d__3.MoveNext() in E:\Projects\ENI\SourceCode\LIMS\WebExtension\WebApp\RequestAuthorizationAttribute.cs:line 84
```

**Comment by davidfowl** [comment]
Where’s the rest of the stack trace? Is that all?

**Comment by Tratcher** [comment]
`public async override void OnActionExecuting`

You can't use async void here. Is there a real async version of OnActionExecuting?

**Comment by davidfowl** [comment]
AHHHHH, how did I miss that!

**Comment by Tratcher** [comment]
Second report I've seen this week.

**Comment by shuba-developer** [comment]
> Where’s the rest of the stack trace? Is that all?

Yes it is. I changed the class name. 
From one of my team
```
System.ObjectDisposedException
  HResult=0x80131622
  Message=IFeatureCollection has been disposed.
Object name: 'Collection'.
  Source=Microsoft.AspNetCore.Http.Features
  StackTrace:
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Headers()
   at WebExtension.HttpRequestExtensions.IsAjaxRequest(HttpRequest request) in E:\SHUBA\PROJECT\ENI\code\WebExtension\Extensions\HttpRequestExtensions.cs:line 13
   at WebExtension.WebApp.AuthorizePrivilegeAttribute.<OnActionExecuting>d__3.MoveNext() in E:\SHUBA\PROJECT\ENI\code\WebExtension\WebApp\AuthorizePrivilegeAttribute.cs:line 67
```
From anothe one
```
at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature,TState](TFeature& cached, TState state, Func`2 factory)
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at WebExtension.WebApp.AuthorizePrivilegeAttribute.<OnActionExecuting>d__3.MoveNext() in E:\Projects\ENI\SourceCode\LIMS\WebExtension\WebApp\AuthorizePrivilegeAttribute.cs:line 84
```

**Comment by davidfowl** [comment]
@shuba-developer identified the bug in your logic, change async void to the other method to handle filters asynchronously [OnActionExecutionAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.actionfilterattribute.onactionexecutionasync?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_Filters_ActionFilterAttribute_OnActionExecutionAsync_Microsoft_AspNetCore_Mvc_Filters_ActionExecutingContext_Microsoft_AspNetCore_Mvc_Filters_ActionExecutionDelegate_
)

```C#
[AttributeUsage(AttributeTargets.Class)]
public class RequestAuthorizationAttribute : ActionFilterAttribute
{
    private readonly Ext.HttpClientApi client;
    private readonly IMemoryCache cache;

    public RequestAuthorizationAttribute(Ext.HttpClientApi client, IMemoryCache cache)
    {
        this.client = client;
        this.cache = cache;
    }

    public override async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        if (context.HttpContext.Request.IsValidRequest())
        {
			return;
		}
		
		var list = new List<UserAuthorization>();
		var userId = context.HttpContext.User.Identity.Name;
		if (cache.TryGetValue(userId, out object value))
		{
			list = value as List<UserAuthorization>;
		}
		else
		{
			var options = new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromHours(10));

			var url = "http://someurl.com/other/api";
			list = await client.Get<List<UserAuthorization>>(url, "result");
			// Save data in cache.
			cache.Set(userId, list, options);
		}
			
		var data = new ValidRequestViewModel
		{
			Success = false,
			Message = "Your request is invalid.",
			Data = new ValidRequestViewModel.DataError
			{
				Header = "Invalid User Request",
				List = list
			}
		};
	       //**error here. IFeatureCollection has been disposed**
		context.HttpContext.Session.Set("error", data.ToByteArray()); 
		context.HttpContext.Items.Remove("app_error");
		context.HttpContext.Items.Add("app_error", data);

		context.Result = new RedirectToRouteResult(new
		{
			action = "Error",
			controller = "Home",
			area = ""
		});

                await next();
    }
```

PS:  Never use async void in ASP.NET Core (https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1#do-not-use-the-httpcontext-after-the-request-is-complete)

And: 

https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#async-void
