### ISSUE TITLE
cookie consent stops working when setting SameSiteMode.

### ISSUE THREAD

**Issue by GusBeare** [dotnet/aspnetcore#20845]
In startup.cs if I have this:

 app.UseCookiePolicy();

Then cookie consent works.  I am using the _cookieConsentPartial method outline in the official docs.

However, if I add this:

app.UseCookiePolicy(new CookiePolicyOptions
{
   MinimumSameSitePolicy = SameSiteMode.Unspecified
});

Cookie consent stops working. i.e. the alert does not show.  This returns false:

  var showBanner = !consentFeature?.CanTrack ?? false;

Am I doing something wrong?

### Further technical details
- ASP.NET Core 3.1.3
- Visual Studio 16.5.3

**Comment by blowdart** [comment]
You need to merge the policies into one;

For example,

```c#
        services.Configure<CookiePolicyOptions>(options =>
        {
            options.CheckConsentNeeded = context => true;
            options.MinimumSameSitePolicy = SameSiteMode.None;
        });
```

Please note that Unspecified is probably a bad idea here, you really do want None for external auth, then add the browser checks as [documented](http://aka.ms/samesitecore).

**Comment by GusBeare** [comment]
thanks very much. I'll try that.  I switched to unspecified because I was finding that some PCs and Android devices with chrome were returning 400 errors for some ajax posts with it set to none.
