### ISSUE TITLE
blazor-wasm publishing missing satellite dll

### ISSUE THREAD

**Issue by GioviQ** [dotnet/aspnetcore#20849]
Please clone https://github.com/GioviQ/blazorboilerplate/tree/restructure

Publish using profile Release_CSB-win-x64

in \src\Server\BlazorBoilerplate.Server\bin\Release_CSB\netcoreapp3.1\publish\it-IT you find
BlazorBoilerplate.Localization.resources.dll

but in \src\Server\BlazorBoilerplate.Server\bin\Release_CSB\netcoreapp3.1\publish\wwwroot\\_framework\\_bin is missing \it-IT\BlazorBoilerplate.Localization.resources.dll

I see a lot of other satellite dlls included, but this is missing, so in webassembly I do not have Italian translation when I publish on my server. Instead running from Visual Studio it works.

It happens with Visual Studio 2019 16.5.3 and 16.5.4 installed today.

**Comment by pranavkm** [comment]
@GioviQ support for loading satellite assemblies is being added as part of 3.2-preview4 (which is releasing soon): https://github.com/dotnet/aspnetcore/issues/17016. Please try this again once the feature is available and let us know if you have any issues with it.

**Comment by GioviQ** [comment]
@pranavkm I do not understand anyway, why the satellite dlls of other nuget packages are correctly included. I will wait.

**Comment by GioviQ** [comment]
I upgraded as stated in https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/ but I experience the same issue.
The branch I used to test is https://github.com/enkodellc/blazorboilerplate/tree/development

**Comment by pranavkm** [comment]
@GioviQ can you share a minimal app that reproduces the problem?

**Comment by GioviQ** [comment]
@pakrym Please clone https://github.com/enkodellc/blazorboilerplate/tree/development then read the instructions in my first post.

**Comment by pranavkm** [comment]
@GioviQ is this specifically when publishing from VS? We're aware of an issue there that we're looking at addressing for rtm.

**Comment by GioviQ** [comment]
@pranavkm Yes

**Comment by pranavkm** [comment]
Tracking issue: https://github.com/dotnet/aspnetcore/issues/21355
