### ISSUE TITLE
error : rzc discover exited with code -2147450730

### ISSUE THREAD

**Issue by slishnevsky** [dotnet/aspnetcore#20857]
I have a .NET Core Angular project created with `dotnet new angular` long time ago.
It was fully working until today when I tried to run in VSCode with `dotnet run`, after installing .NET Core SDK 3.1.201, no code changes have been made. The app is working fine on Azure.

> C:\Users\Username\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error : rzc discover exited with code -2147450730. [C:\Users\Username\Projects\ProjectName\ProjectName.csproj]

```
    <RazorTagHelper
      Debug="$(_RazorDebugTagHelperTask)"
      DebugTool="$(_RazorDebugTagHelperTool)"
      ToolAssembly="$(_RazorToolAssembly)"
      UseServer="$(UseRazorBuildServer)"
      ForceServer="$(_RazorForceBuildServer)"
      PipeName="$(_RazorBuildServerPipeName)"
      Version="$(RazorLangVersion)"
      Configuration="@(ResolvedRazorConfiguration)"
      Extensions="@(ResolvedRazorExtension)"
      Assemblies="@(RazorReferencePath)"
      ProjectRoot="$(MSBuildProjectDirectory)"
      TagHelperManifest="$(_RazorTagHelperOutputCache)">
      <Output
        TaskParameter="TagHelperManifest"
        ItemName="FileWrites"/>
    </RazorTagHelper>

```

**Comment by pranavkm** [comment]
@slishnevsky the error code usually indicates that you're missing a version of the shared runtime. If you inspect the build output (or run `dotnet build`), it should specify the missing runtime version. Please note that .NET Core 2.2 has reached [end of life](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) and no longer receives critical security fixes. We recommend updating to a supported version of .NET Core..
