### ISSUE TITLE
Unable to use RootComponents twice on same page (Using Blazor Wasm for multiple / distinct areas of page)

### ISSUE THREAD

**Issue by Ecroyd** [dotnet/aspnetcore#20855]
### Describe the bug
It does not seem possible to instantiate the root components twice. Registering a component with:
```
builder.RootComponents.Add<SurveyPrompt>("SurveyPrompt");
```
and then using two SurveyPrompt tags in the html results in only one getting rendered.

### Use Case
I would like to initially use Blazor Wasm for the few interactive elements of my site, rather than letting Blazor handle the full website. This will allow my existing website to be otherwise unchanged.

Some of these elements (that I would like to use Blazor Wasm for) are repeated multiple times on the same page. Ideally I would like to add the Blazor Components to the page using JavaScript, but the API available in JavaScript did not appear to include this ability.

### To Reproduce
I originally started off with the template  Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview3.20168.3 but as I have changed things about and removed the routing, I think the following is the important parts.

I have a component declared in a **SurveyPrompt.razor** file

```
<div class="alert alert-secondary mt-4" role="alert">Please take our brief survey and tell us what you think.</div>
````

The following in a program.cs file

```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Text;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection;
using BlazorApp1.Client.Shared;

namespace BlazorApp1.Client
{
	public class Program
	{
		public static async Task Main(string[] args)
		{
			var builder = WebAssemblyHostBuilder.CreateDefault(args);
			builder.RootComponents.Add<SurveyPrompt>("SurveyPrompt");
			builder.Services.AddBaseAddressHttpClient();

			await builder.Build().RunAsync();
		}
	}
}
```

and in my served html I have:
```
<SurveyPrompt>Loading...</SurveyPrompt>
<SurveyPrompt>Loading...</SurveyPrompt>
<script src="_framework/blazor.webassembly.js"></script>
```

I would expect that the text "Please take our brief survey and tell us what you think" would appear twice on the page.

Instead, only the first SurveyPrompt instance is replaced.

### Further technical details
- IDE
Microsoft Visual Studio Community 2019 Preview
Version 16.6.0 Preview 2.1

- Include the output of `dotnet --info`
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
 [...]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
 [...]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 [...]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 [...]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Ecroyd** [comment]
I suspect the bug might relate to the use of document.querySelector in the attachRootComponentToElement method in Renderer.ts, as document.querySelector returns the first Element matched. I would expect the attachRootComponentToElement JS method to process all matched elements.

**How I think specifying RootComponents calls attachRootComponentToElement and therefore document.querySelector**

The following is how I came to that conclusion... on the assumption the blazor-wasm branch is the correct branch to be looking at.

_WebAssemblyHostBuilder_
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs
This is the class the RootComponents are set on. They are passed to WebAssemblyHost in the Build method.

_WebAssemblyHost_
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHost.cs
The RunAsyncCore method calls _renderer.AddComponentAsync for each rootComponent.

_WebAssemblyRenderer_ 
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Rendering/WebAssemblyRenderer.cs
The AddComponentAsync method on WebAssemblyRenderer invokes the attachRootComponentToElement JS method through the DefaultWebAssemblyJSRuntime.

_Renderer.ts_ 
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Rendering/Renderer.ts
I assume it is the attachRootComponentToElement method from Renderer.ts that WebAssemblyRenderer calls. This function uses document.querySelector which returns the first Element within the document that matches the specified selector.

**Comment by Ecroyd** [comment]
**Hacky work around**
The issue can be worked around by specifying the elements using ids instead. So it works if we update the main method to:
```
		public static async Task Main(string[] args)
		{
			var builder = WebAssemblyHostBuilder.CreateDefault(args);
			IJSRuntime jsRuntime = builder.Services.BuildServiceProvider().GetRequiredService<IJSRuntime>();
			var json = await jsRuntime.InvokeAsync<JsonElement>("getElementIdsForTag","SurveyPrompt");
			foreach(var id in json.EnumerateArray())
			{
				builder.RootComponents.Add<SurveyPrompt>($"SurveyPrompt#{id}");
			}
			builder.Services.AddBaseAddressHttpClient();
			await builder.Build().RunAsync();
		}
```
And the HTML is updated to:
```
    <SurveyPrompt id="a">Loading...</SurveyPrompt>
    <SurveyPrompt id="b">Loading...</SurveyPrompt>
    <script>
        window.getElementIdsForTag = (elementSelector) => {
            return Array.from(document.querySelectorAll(elementSelector)).map(a => a.id);
        };
    </script>
    <script src="_framework/blazor.webassembly.js"></script>
```

**Comment by javiercn** [comment]
@Ecroyd thanks for contacting us.

I don't think this is a capability we have focused our attention on for the time being (at least that I know of). The focus for Blazor WebAssembly for now has been to render a single component into the page (although we haven't prevented rendering multiple components) which represents your whole app.

That said, the approach with the selector I think is fine and is the way I would probably recommend someone wanting to produce instances of the same component to achieve it.

This is an area that might change in future versions as we better integrate Blazor within ASP.NET Core.

I'm going to close this issue as the current approach sounds fine to me.

/cc: @SteveSandersonMS in case he wants to add anything.

**Comment by SteveSandersonMS** [comment]
Yes, you absolutely can have as many root elements as you want. You just need to make each of them have a distinct CSS selector (for example, using an `id` or some other attribute).

Everything's working as expected here :)
