### ISSUE TITLE
Regression in build incrementalism for Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#20858]
Moving this issue over from email thread.

### Describe the bug
Changes made to a Blazor project are not reflected when running the project using:

```
$ dotnet build
$ dotnet run
```

### To Reproduce

1. Create a new Blazor WASM project.

```
$ dotnet new blazorwasm -o repro
```

2. Build and run the project using either VS or the CLI.

```
$ dotnet build
$ dotnet run
```

3. Make a modification to the project sources. For example, add a `Console.WriteLine` statement.

5. Build and run the project.

6. Observe that your source change in #3 "doesn't work".

### Further technical details
This was reproduced on preview4 bits for Blazor WASM.

**Comment by javiercn** [comment]
Looking into it.
