### ISSUE TITLE
Html.Kendo().Grid() throwing error on group by action .net 3.1 upgrade 

### ISSUE THREAD

**Issue by ashokghoghari** [dotnet/aspnetcore#20853]
I have used Html.Kendo().Grid() and was working fine with .net core 2.1.

It is stop working when i upgraded to .net core 3.1. If i use to drag a field to group by records with that specific field, it throws an error. It works well when i do 

dr = iqueryableData.**ToList()**.ToDataSourceResult(request);

It does not work when i use
dr = iqueryableData.ToDataSourceResult(request);

The problem here is, result data my have so many of items from which i would like only 20 items for pagination. Doing .tolist() would load all data into memory and is having performance impact.

Let me know the solution for this if any.

**Comment by javiercn** [comment]
@ashokghoghari thanks for contacting us.

It looks like this is a question about how to use ASP.NET Core with a third-party component. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag or file an issue with the component vendor to get support from them.

At the very least we would need details on what is failing and where, including a call stack and preferrably a minimal repro project that demonstrated the issue.
