### ISSUE TITLE
Blazer Client Side

### ISSUE THREAD

**Issue by shahidroofi** [dotnet/aspnetcore#20851]
Blazer Webassembly version will allow running c# on the client browser. As of now all the code that you put in @code or inline @ code will be exeucuting in that case on browser. But how to mix up with some server code or server side mark up?? 

As per hosting models its either server hosted or webassembly(client side). Realistically both server side and client side code will be required in same project. 

Will it be a possibility to have both and mix them in same? if not than how will we include the server side code in that? using web services for little server side will be an overhead it seeems.

**Comment by javiercn** [comment]
@shahidroofi thanks for contacting us.

I'm not sure what your specific question is, but to provide a short answer, we currently don't support client-side and server-side blazor apps in the same document/page.

**Comment by shahidroofi** [comment]
@javiercn thanks. That's exactly what i wanted to know and realized from implementation currently.
Will there any future plan for such? just incase..

**Comment by mkArtakMSFT** [comment]
Hi @shahidroofi.
The WebAssembly Hosted project template creates two separate projects out of the box, where there are two separate projects for client and for server. To share code, you can use the third `Shared` project. The current template has an example out of the box.
As for mixing both client and server code in the same project, this is not something we plan to do in the near future.

**Comment by shahidroofi** [comment]
thanks @mkArtakMSFT
