### ISSUE TITLE
Filter records by collection of parameter sets

### ISSUE THREAD

**Issue by hubert-wojtowicz** [dotnet/aspnetcore#20854]
### Is your feature request related to a problem? Please describe.
I was looking for solution described in more detail here [here](https://stackoverflow.com/questions/61226542/how-to-write-linq-query-retrieving-records-having-parameters-out-of-defined-coll).

What I want to acheive is to generate query like:
```
SELECT *
FROM Entity
WHERE ( SomeId_1 = SomeId AND DateAt_1 = DateAt)
    OR..
    OR (SomeId_N = SomeId AND DateAt_N = DateAt)
```
using LINQ extension methods over `IQuerable<Entity>` interface, for `Entity` having collumns (among others) `SomeId`, `DateAt`.

Lets assume I have:
```
class SomeIdAtPair
{
   public int SomeId { get;set; }
   public DateTime DateAt { get;set; }
}
```
and collection of parameters:
```
var pairs = new List<SomeIdAtPair>
{
    new SomeIdAtPair { ... },
    ...
};
```

Is it possible or will it be possible in EF Core 3.1+?

**Comment by javiercn** [comment]
Thanks for contacting us @hubert-wojtowicz 

It looks like this is not a question about how to use ASP.NET Core. You will get a better and faster answer if you file an issue directly in the [ef repo](https://github.com/dotnet/efcore).

**Comment by hubert-wojtowicz** [comment]
ups sorry.., it was by mistake
