### ISSUE TITLE
Blazor: add support for toggle event

### ISSUE THREAD

**Issue by leonardder** [dotnet/aspnetcore#20859]
### Is your feature request related to a problem? Please describe.
With Blazor, I'm trying to use the [Ontoggle](https://www.w3schools.com/jsref/event_ontoggle.asp) event of a html5 details element to render its content as soon as the element is toggled. However, when adding @ontoggle to the details element, the component fails to render.

### Describe the solution you'd like
Support the ontoggle element along with a dedicated EventArgs class that conveys the state of the element

### Additional context
I'm getting the following traceback in the Firefox web console:

```
[2020-04-15T14:30:16.586Z] Error: System.AggregateException: One or more errors occurred. (InvalidCharacterError: String contains an invalid character)

 ---> System.InvalidOperationException: InvalidCharacterError: String contains an invalid character

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

   --- End of inner exception stack trace --- blazor.server.js:15:27309
    log https://localhost:44378/_framework/blazor.server.js:15
    C https://localhost:44378/_framework/blazor.server.js:8
    S https://localhost:44378/_framework/blazor.server.js:8
    invokeClientMethod https://localhost:44378/_framework/blazor.server.js:1
    invokeClientMethod https://localhost:44378/_framework/blazor.server.js:1
    processIncomingData https://localhost:44378/_framework/blazor.server.js:1
    onreceive https://localhost:44378/_framework/blazor.server.js:1
    onmessage https://localhost:44378/_framework/blazor.server.js:1
```

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by leonardder** [comment]
What would be the best starting point to try this myself and possibly 
create a pull request?

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS any suggestions here?

**Comment by SteveSandersonMS** [comment]
@leonardder You'd want to do a PR against the `master` branch. Search inside the `src\Components` directory for the name of some other event handler to get a sense of how each event type is defined and what tests we implement for each one.

**Comment by Zoxive** [comment]
@pranavkm ontoggle appears to be unique to just the `<details>` element.

Would it still be registered in https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Web/EventHandlers.cs ?

Looks to be the case based on other non-global events in there, just want to check before i start going down that path.

**Comment by Zoxive** [comment]
`Support the ontoggle element along with a dedicated EventArgs class that conveys the state of the element`

Also i dont think we should have any args that convey if the element is open or closed. The javascript event itself has no such info, and just doesnt seem right to save a boolean with the current state somewhere.

**Comment by Zoxive** [comment]
So i've added the `EventHandler`, the event now shows up in razor syntax and will compile but doesnt fire.

I've been searching around the codebase (as a newbie to this repo, i could be missing something easily found..) cant seem to find where to wire up the actual event. I've been using finding usages everywhere but cant seem to find anything. Is there some sort of "magic" happening that connects these that would make it difficult to find? 

For example the `WebEventCallbackFactoryEventArgsExtensions` why are there 0 usages on this? (I also dont think i need to modify this as this new event has no special args and will take in the default EventArgs, but i thought maybe this would lead me to find what im looking for)

I wouldn't expect this to be in javascript somewhere? (Kind of defeats the whole web assembly thing)

**Comment by SamProf** [comment]
I will take care on this issue

**Comment by pranavkm** [comment]
Sorry @Zoxive I was offline when you pinged earlier.  @SamProf did you have the same questions as @Zoxive >
