### ISSUE TITLE
AddExternalScheme without configureOptions delegate

### ISSUE THREAD

**Issue by MintPlayer** [dotnet/aspnetcore#20852]
### Goal configuration for external providers

Microsoft.AspNetCore.Authentication.MicrosoftAccount etc @ 3.1.3

In startup.cs, I have the following services configuration

	services
		.AddDbContext<MintPlayerContext>(options =>
		{
			options.UseSqlServer(opt.ConnectionString);
		})
		.AddAuthentication()
		.AddJwtBearer();
		.AddFacebook()
		.AddMicrosoftAccount()
		.AddGoogle()
		.AddTwitter();

	services.AddIdentity<Entities.User, Entities.Role>()
		.AddEntityFrameworkStores<MintPlayerContext>()
		.AddDefaultTokenProviders();

	services
		.Configure<IdentityOptions>(options =>
		{
			...
		})
		.Configure<JwtBearerOptions>(options =>
		{
			...
		})
		.Configure<FacebookOptions>(options =>
		{
			...
		})
		.Configure<MicrosoftAccountOptions>(options =>
		{
			...
		})
		.Configure<GoogleOptions>(options =>
		{
			...
		})
		.Configure<TwitterOptions>(options =>
		{
			...
			options.RetrieveUserDetails = true;
		});

This throws the following exception for Facebook:

> ArgumentException: The 'AppId' option must be provided

This happens if I want to configure all the options separately (configure<Options>), instead of with the service-registration.

### Tracing

When tracing the error back to the source code (Thank you microsoft for making it possible to debug third-party libraries), I end up at:

https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Facebook/src/FacebookExtensions.cs#L13

Where the Core method is being called with an empty lambda instead of null.
Since this parameter is defined (not null), the following happens (in my case the AddOptions and the condition-statement are swapped):

https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/AuthenticationBuilder.cs#L48

![image](https://user-images.githubusercontent.com/48772716/79325089-da7c3980-7f10-11ea-8ff5-af470cede55f.png)

The Facebook/Twitter/... options are being configured with THE empty lambda provided at https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Facebook/src/FacebookExtensions.cs#L13 instead of my configuration.

The next step is validation, which fails because the configuration has somehow been overwritten with empty strings.

So currently I have to nest my configuration in the Add[ExternalProvider] call for this to work correctly.

### Describe the solution you'd like
_Is it possible for you folks to just pass a nullPointer instead of an empty lambda func, in the ASP.NET Core source code?_

https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Facebook/src/FacebookExtensions.cs#L13

**Edit:** This doesn't help since the AddSchemeHelper method unconditionally adds new options to the configuration at the following line:

https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/AuthenticationBuilder.cs#L41

I can also confirm that the Startup@ConfigureServices completes before the validate lambda https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/AuthenticationBuilder.cs#L43 is being executed)

**Comment by Kahbazi** [comment]
Hello @MintPlayer.
The configurations for authentication scheme are named. So if you want to configure authentication options without the provided extensions method, you have to pass the authentication scheme name to `Configure` method. 

```csharp
services.Configure<FacebookOptions>(FacebookDefaults.AuthenticationScheme, o =>
{
});
```

**Comment by MintPlayer** [comment]
Thanks, this works. Closing this.

Optionally this could be added to the docs (**Configure options seperately**):
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.1
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.1
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.1
