### ISSUE TITLE
Controller doesn't respect HttpClient cookies - custom Blazor auth

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#20850]
### Describe the bug
I just discovered a bug in my application. I implemented custom refreshless authentication few weeks ago. Now while I am testing it I discovered bug - Web API Controller doesn not respect cookies from HttpClient "occasionally". Let me describe my actions

There are two browsers, browser A, browser B. Both cookies cleared.
Browser A
- Login action
- Sending post via **HttpClient** with cookie: **.AspNetCore.Identity.Application=**
- Web API Controller shows cookie name **.AspNetCore.Identity.Application** value string.Empty ("")
- Browser is successfully logged in, cookies created
- Blazor saves via JS cookies to browser

Browser B
- Page reload action
- Sending get request to Web API Controller to get info if browser is logged in via **HttpClient** with cookie: **.AspNetCore.Identity.Application=**
- Web API Controller shows cookie with value from Browser A!
- Browser B shows username, acts as logged in Browser A.

Now here is funny thing
Browser B do some actions that requires call to get info about users in this time (other tab could release etc).
- So.. some action
- Sending get request to Web API Controller via **HttpClient** with cookie: **.AspNetCore.Identity.Application=**
- Web API Controller shows cookie **.AspNetCore.Identity.Application** value string.Empty ("") [THIS TIME CORRECTLY]
- Browser B shows not logged-in content

I hope this description tells you there is issue only one time, until action is done. Btw it works across different browsers. Definitely not browser issue. More like Controller issue

### Code
Header.razor (login func)
```
async Task LoginAsync()
{
    try
    {
        await (authStateProvider as IdentityAuthenticationStateProvider).LoginAsync(LoginModel);

        UserInfo userInfo = await (authStateProvider as IdentityAuthenticationStateProvider).GetUserInfoAsync();

        await JSRuntime.InvokeVoidAsync("AddLoginCookies", userInfo.Cookie);
        await localStorage.SetItemAsync("Login", userInfo.Cookie);
    }
    catch(Exception ex)
    {
    }

    StateHasChanged();
}
```

AuthorizeService (registered as Transient)
```
public async Task<UserInfo> GetUserInfo(string cookie)
{
    string json = await CreateClient(cookie).GetStringAsync("api/Authorize/UserInfo");

    return Newtonsoft.Json.JsonConvert.DeserializeObject<UserInfo>(json);
}

HttpClient CreateClient(string cookie = null)
{
    HttpContext context = contextAccessor.HttpContext;

    HttpClient client = clientFactory.CreateClient();
    client.BaseAddress = new Uri($"{context.Request.Scheme}://{context.Request.Host}");

    if(!string.IsNullOrEmpty(cookie))
        client.DefaultRequestHeaders.Add("Cookie", cookie);

    return client;
}
```

IdentityAuthenticationStateProvider (registered as Scoped)
```
async Task<string> GetCookiesAsync()
{
    try
    {
        string cookie = await localStorage.GetItemAsync<string>("Login");

        return $".AspNetCore.Identity.Application={cookie}";
    }
    catch(Exception ex)
    {
        return $".AspNetCore.Identity.Application={httpContextAccessor.HttpContext.Request.Cookies[".AspNetCore.Identity.Application"]}";
    }
}

public async Task LoginAsync(LoginViewModel model)
{
    await authorizeSvc.LoginAsync(model);

    NotifyAuthenticationStateChanged(GetAuthenticationStateAsync());
}

public async Task<UserInfo> GetUserInfoAsync()
{
    if (userInfoCache != null && userInfoCache.IsAuthenticated)
        return userInfoCache;

    userInfoCache = await authorizeSvc.GetUserInfo(await GetCookiesAsync());

    return userInfoCache;
}

public override async Task<AuthenticationState> GetAuthenticationStateAsync()
{
    ClaimsIdentity identity = new ClaimsIdentity();

    try
    {
        UserInfo userInfo = await GetUserInfoAsync();

        if (userInfo.IsAuthenticated)
        {
            IEnumerable<Claim> claims = new[] { new Claim(ClaimTypes.Name, userInfoCache.UserName) }.Concat(userInfoCache.ExposedClaims.Select(c => new Claim(c.Key, c.Value)));

            identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
        }
    }
    catch (HttpRequestException ex)
    {
        Console.WriteLine("Request failed:" + ex.ToString());
    }

    return new AuthenticationState(new ClaimsPrincipal(identity));
}
```

### Further technical details
- ASP.NET Core version 3.1.1
- VS 16.5

To code above: **CreateClient(string cookie = null)** string is not null during my debugging.

EDIT: dumping Controller request headers shows
`Request.Headers["Cookie"]	{.AspNetCore.Identity.Application=null; .AspNetCore.Identity.Application=CfDJ8NTjd87IGG1EtVfYbGnvK8H7MYzS6aAxZl2Dd3b3byNzwR4FZGsoOSvqZaO-uzCc8o-AYcWwisaj50HiOqvmWs-iWUaSaBoggXxONB5Hh_Ln3R_ceNwgWv7GdWL6JLstnZyZDDLlGQDwsDx3oqIBIWHMar1Kt5ZhVgRDgPUHMCEwyaeBY9lsIY_KnWZSEYWcZQkhkAZsp_FosOCxmS2Tq1GDBio1RLCBiK-DdnUq8y_hbvHB65i4A4-wrUW8TZfsQm5aaROdSNfUhYhOzAZ2h8HrmD-GXEUKVa0RYiY6Ao28_4YQqmJBzPWSS4aj56IPAYD6AZRdAjY5j6uIqdaDL2wEcUberlR_9CaTk-aJtNGykFyPjwODpFOcw2Qqq1rASlw8tAjzKFRYM4e6lt2B02x6N9MR8ocXpH1r3ZL8gVkNAUiVE3foHNyZtflZp2NIvddez0Ud5RuHecp775Opbc-EakEPt9e08WqLeKdtUszbn1G9goIGThhZ-eDevmMgp-47uU7LpIenvW5gSc0hZMDX0K9eO1X6mQJf5vGiQFj1wAVsf46JSw_9WJ2Te0sK3kAJWiwWP5HIVHIuK-9pcKr-5I5VZ6xrqsBWiGk33tk3Iwutv8z4jFgqc9gcXbZOU9OmpdZP_Bs08VnAFGGV6cHzfTF8pqVj9rjMQexU2uYexCndn9RJNDY4OGhlHs0HJYrSeVy-wBknRQZuKaetIdaXKNZo7WBjma0GPEy58MHgR85nio0j7tmwK_kKTx6kL2m9J9TVJV0c_bNKyIYgp2F2plQidua_x7YM3gc17gDTzVYBrKkgO0vtY7N5Yoq3C4jieOSDpHuZV5K-4tjLrzc}`

However question is.. where does the second one **.AspNetCore.Identity.Application** comes from. I create manually HttpClient.

**Comment by javiercn** [comment]
@glararan thanks for contacting us.

I don't think there's anything Blazor specific about this issue, so I'll let the security folks handle it. In general, if you are using client-side blazor we don't recommend you use cookies. if you are using server-side Blazor we recommend you use our authentication support and avoid implementing your own auth.

**Comment by glararan** [comment]
I agree.. its not blazor specific however I forgot to mention its server-side. Official authentication is not refreshless right now :( Waiting for support.

**Comment by glararan** [comment]
Workaround: dont use HttpClientFactory. Create it without factory. After Login/Register ask with same client instance for UserInfo, pass it to browser for writing down cookies for next requests with new instance :)

**Comment by blowdart** [comment]
Yea this doesn't seem identity/security related either, more HttpClientFactory, which would put it back to blazor.

But @Tratcher any ideas here?

**Comment by Tratcher** [comment]
When you say Browser A and B, are those two instances of the same browser (e.g. Chrome) on the same machine or two completely different browser types (e.g. Firefox and Edge) and/or different machines? Cookies are expected to cross between two instances of the same browser on the same machine.

**Comment by glararan** [comment]
@Tratcher We found this bug across machines. Then I tried to reproduce it myself with Browser A (Chrome), Browser B (Chrome Anonymous window), Browser C (MS Edge based on Chromium)

**Comment by anurse** [comment]
@glararan can you provide a runnable sample that reproduces the issue? It's really not clear to me exactly what you're trying to do. It sounds like you're taking cookies from the server and saving them to browser storage? That's definitely not recommended.

**Comment by glararan** [comment]
@anurse Almost have sample.. just figuring out why User.Identity.IsAuthenticated is always false in new project, lol. Funny thing I dont even need it working to get you repro :)

however: you are right. I am saving cookies to browser storage and also to cookies. Browser storage because its accessible from DI. If I inject IJSRuntime into C# class then I am not able to get clients cookies. 

What exactly I am doing? Well refreshless login. Because supported way implements only authentication via refreshing page.

Repo: https://github.com/glararan/20850/tree/master/20850

Steps:
Register account (it will not log you in.. broken, not needed)
Put breakpoint at **AuthorizeApiController:34**
Watch for property **HttpContext.Request.Cookies[".AspNetCore.Identity.Application"]**
Open browser B, load page
Property **HttpContext.Request.Cookies[".AspNetCore.Identity.Application"]** should be **""**
Login in browser A using register credentials
Watch property **HttpContext.Request.Cookies[".AspNetCore.Identity.Application"]** should have cookie "xxxx"
Do refresh in browser B. Cookies are exactly the same!

**Comment by anurse** [comment]
I see some really strange behavior in the repro app you shared. First off, you're using Blazor Server and then having the UI call an API on the same server. Since the UI itself is also running on the server this seems completely unnecessary, why are you calling the HTTP APIs instead of handling the auth logic directly?

Remember that in Blazor Server **all the .NET code is running in the server process**, unlike Blazor WASM where the code is running in the browser. There's no need to make HTTP requests back to yourself.

Also, when you make that call, it seems that you're using a singleton HttpClient. Since Blazor Server is running the UI on the server, this means that each browser instance is *sharing* the HttpClient and thus likely sharing the Cookie container. This is a big security problem since cookies will be shared across users.

**Comment by glararan** [comment]
@anurse There is need to call it via HTTP api because you cant modify headers for login. When I started refreshless auth I did it directly until I received error like:
`The response headers cannot be modified because the response has already started.`

Should IHttpClientFactory be Singleton which creates independently HttpClient like transient?

**Comment by anurse** [comment]
Right, you can't modify headers in Blazor Server UI code (such as event handlers) because **there is no response** at that time. You're running code on the server that will cause DOM updates to be sent to the client, there's no active HTTP request. Blazor is using HTTP requests (and WebSockets) to send DOM updates back and forth but the events themselves are not running in the context of an HTTP request.

> Should IHttpClientFactory be Singleton which creates independently HttpClient like transient?

No, it's intentional that it shares instances like this. It's not designed for cases where you have user-specific cookies like this. If you really need to use HTTP (I still think that's a wrong path to go down) then you'll want to create a separate HttpClient for each user.

**Comment by glararan** [comment]
@anurse Well then I dont see way how to login without HTTP request? If you have idea how to implement it I would be glad if you share it :)

I dont need header, SignInManager does :) Exception comes from SignInManager class which is in ASP.NET Core Identity part. As long as there is not official support for it I had to do it this way.

Yeah I went that way, creating HttpClient on my own with each request. If its by design then we can probably close the case

**Comment by Crasius** [comment]
@anure i got a similiar problem.
The reason why i want to use http is because the authentication service should not have to be a .net application/written in .net
Blazor is, at least for my understanding, an UI Framework - and should only handle UI related things. I dont want to implement the hole logic into this app/.net dependencies. When i want to change the UI to an WPF app, JS based SPA, Android app or whatever id like to, id be glad to not be stuck with my special blazor/.net implementation.

Do i lag of some understanding here? How would that kind of requirement be handeled?

**Comment by blowdart** [comment]
Closing as by design. @Crasius yours is a blazor design question, and best asked in a new issue.
