### ISSUE TITLE
XML Docs not generating intellisense in published Nuget component lib package for Blazor.

### ISSUE THREAD

**Issue by allan-mobley-jr** [dotnet/aspnetcore#20864]
### Describe the bug
During development, XML Docs generate intellisense when using the component. 

After packing and pushing to nuget.org via Azure Pipelines and then pulling down in a separate project for use, no intellisense is picked up for the component lib.

Not sure if using abstract component classes and partials is the hang up for this, but the functionality works just fine, just no intellisense for anyone using the library.

### To Reproduce

1. Create a component class library using partials and abstract inheritance .cs files, along with the .razor for markup-side of it. Add XML Docs.

2. Reference the project from a blazorwasm template project. See generated intellisense.

3. Package it and see if any intellisense is generated.

The source code for one example can be found [here](https://github.com/Mobsites/Blazor.TopAppBar/tree/master/src).

It depends on this shared abstract component lib found [here](https://github.com/Mobsites/Blazor.BaseComponents/tree/master/src).

### Further technical details
PS C:\Users\me\source\repos\Mobsites> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Using VS Online via self-hosted.

**Comment by pranavkm** [comment]
Your app isn't including xml dos in the NuGet package. See https://github.com/Mobsites/Blazor.BaseComponents/pull/2.

**Comment by allan-mobley-jr** [comment]
Thanks so much. I had no idea.
