### ISSUE TITLE
Model Binding for Dictionary<string, object> is not correctly working

### ISSUE THREAD

**Issue by hikalkan** [dotnet/aspnetcore#20868]
Following the [model binding document](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#dictionaries), I've created a sample controller:

````csharp
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

namespace DictionaryBindingError.Controllers
{
    [Route("test")]
    public class TestController : Controller
    {
        //Request example: http://localhost:56820/test/test1?dict[2]=B&dict[5]=E
        [Route("test1")]
        public ActionResult Test1(Dictionary<int, string> dict)
        {
            return Content(string.Join(", ", dict.Select(v => v.Key + "=" + v.Value)));
        }

        //Request example: http://localhost:56820/test/test2?dict[A]=C&dict[B]=D
        [Route("test2")]
        public ActionResult Test2(Dictionary<string, object> dict)
        {
            return Content(string.Join(", ", dict.Select(v => v.Key + "=" + v.Value)));
        }
    }
}
````

`Test1` method (which takes a `Dictionary<int, string>`) works as expected and returns `2=B, 5=E` as the result.

However, `Test2` method returns `A=, B=` while I expect `A=C, B=D`. Because values come as `null` in the dictionary, while keys are correct:

![image](https://user-images.githubusercontent.com/1210527/79375106-c3653800-7f60-11ea-91da-0e717bc4a23b.png)

I actually can see the values in the Request object:

![image](https://user-images.githubusercontent.com/1210527/79375226-fa3b4e00-7f60-11ea-98e5-ed11f343c281.png)

But somehow it doesn't bind the values to the dictionary.

Sample project that reproduces the problem: https://github.com/hikalkan/samples/tree/master/DictionaryBindingError

Note that this happens also for form binding, not only for query string binding.

Thanks.

**Comment by pranavkm** [comment]
Does a `Dictionary<string, string>` work?

**Comment by hikalkan** [comment]
`Dictionary<string, string>` works when I try, yes. However, for my case, changing it is hard since actually I am using a class as the parameter and it implements [a standard interface](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.ObjectExtending/Volo/Abp/Data/IHasExtraProperties.cs) I've defined in the framework level and changing it would be a big breaking change for the framework users and breaks other use cases.

It would be perfect if it adds everything to the dictionary as `string` and just works like `Dictionary<string, string>`.

Would you support this scenario please? Otherwise, is there any way that I override the behaviour?

**Comment by pranavkm** [comment]
MVC cannot determine how to bind to an opaque `object` data type. You could consider writing a custom model binder if keeping the data type is important to your app. https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding has some examples of this including one for polymorphic binding which is pretty close to what is being asked here.

**Comment by hikalkan** [comment]
I believe it should throw exception that explains it doesn't support Dictionary<string, object> or handle it in some way (like assuming the values are strings).

But OK, I will try to handle in some way.

Thanks. You can close if you don't want to make any code change.
