### ISSUE TITLE
Razor pages and Console apps

### ISSUE THREAD

**Issue by genifycom** [dotnet/aspnetcore#20860]
Where are we at with DotNet Core 3.1 and being able to run razor pages in a console app.

Why would we want to do this? Simple. Serverless apps need to be able to spin up instances to meet demand. For example say the index page is going to be hit hard, then separating this into a serverless instance makes perfect sense. The infrastructure can spin up multiple containers to address this page needs.

In this scenario, there is NO need for routing or MVC. We just need the ability to generate a single page and serve it. The templates can be shared so that other pages that use them (like headers, footers, menu) can pull them in as needed.

In the serverless world, it makes no sense to spin up kestrel, MVC etc, etc just for the container to serve up one page.

We have moved well beyond full web applications for everything. Serverless is our primary way of delivering web services now.

Can anyone help address this vital need?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
