### ISSUE TITLE
How to asynchronously initialize a Hub

### ISSUE THREAD

**Issue by udlose** [dotnet/aspnetcore#20866]
I am new to using SignalR and have downloaded and viewed the sample apps (which are very helpful).  The StockTicker example is closest to my needs.  However, I need to asynchronously initialize some data in the Hub (or comparing to the StockTicker example, the ConcurrentDictionary in the `StockTicker` class).

I've considered using a `Lazy<ConcurrentDictionary<string, string>>` with a `ValueFactory` but the `ValueFactory` needs to be `static` (or it won't compile).  Since I'm using ASP.NET Core DI to initialize the members, and one of these members is responsible for handling the initialization of the `ConcurrentDictionary`, I'm not sure sure the best way to do this.

How can I asynchronously initialize the `Hub`?

**Comment by davidfowl** [comment]
What exactly are you trying to do? What code do you want to write in the hub?

**Comment by udlose** [comment]
I apologize for the delay in response. My implementation is based off of the [StockTicker sample app for SignalR](https://github.com/aspnet/SignalR-samples/tree/master/StockTickR).

- I have a `FeatureFlagsHub` that is comparable to the `StockTickerHub` in the sample. 

- I have a `FeatureProvider` that is comparable to the `StockTicker` class in the sample.  The `FeatureProvider` is registered as a singleton and injected via .NET Core DI into the `FeatureFlagsHub`. 
- The `FeatureProvider` has a `FeatureRepository` (singleton) injected into it.
- The `FeatureProvider` has a `ConcurrentDictionary` that will be initialized by making an `async` call to the `FeatureRepository`.

Since constructors cannot have `async` calls, and the initialization of the `ConcurrentDictionary`
should only happen once, I wasn't sure how to do an `async` initialization from the `FeatureFlagsHub`.

**Comment by anurse** [comment]
@udlose have you considered doing the initialization of the `FeatureProvider` via a [background task](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)? That would initialize the data during startup. If you want it to be lazy-initialized on the first connection, using a `SemaphoreSlim` as you describe sounds like the right approach to me

**Comment by udlose** [comment]
> @udlose have you considered doing the initialization of the `FeatureProvider` via a [background task](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)? That would initialize the data during startup. If you want it to be lazy-initialized on the first connection, using a `SemaphoreSlim` as you describe sounds like the right approach to me. Or you could use a `Lazy<Task>` and await that task (after the first `await` completes, all the others will be synchronous, see https://devblogs.microsoft.com/pfxteam/asynclazyt/ for more info on this pattern)

Thank you for your prompt response!  I had come across `IHostedService` but thought it was geared for a Worker Service rather than an ASP.NET Core app. Is that not true?

I also considered [Stephen Cleary's AsyncLazy](https://blog.stephencleary.com/2012/08/asynchronous-lazy-initialization.html) (didn't know about the one the pfxteam did), but the problem is the value factory passed to the `Lazy` ctor needs to be a `static` and I have a true Singleton (no statics in it).  So, the injected `FeatureProvider` couldn't be used to make the call.

**Comment by anurse** [comment]
> Thank you for your prompt response! I had come across `IHostedService` but thought it was geared for a Worker Service rather than an ASP.NET Core app. Is that not true?

Nope, it's for any application that uses the Hosting/DI model. Worker services tend to *only* have Background Services but using them for background or initialization tasks in web apps is totally an intended scenario.



> I also considered [Stephen Cleary's AsyncLazy](https://blog.stephencleary.com/2012/08/asynchronous-lazy-initialization.html) (didn't know about the one the pfxteam did), but the problem is the value factory passed to the `Lazy` ctor needs to be a `static` and I have a true Singleton (no statics in it). So, the injected `FeatureProvider` couldn't be used to make the call.

I'm a little confused here. The value factory to a `Lazy` ctor doesn't have to be static unless the `Lazy` is in a static field. However, if you're OK with the constructor kicking off the initialization, you could also use a pattern like this (since `await`ing a `Task` is a thread-safe operation):

```csharp
public class MyService
{
	private readonly Task _initializedTask;

    public MyService(...)
    {
        // Start initialization, and stash the task, but do not await it
        // Absolutely DO NOT call .Wait or .Result ;)
        _initializedTask = DoInitializationAsync();
    }

	public async Task SomeMethodAsync()
    {
        await _initializedTask;
        // Move on with the operation.
    }
}
```

**Comment by udlose** [comment]
> I'm a little confused here. The value factory to a `Lazy` ctor doesn't have to be static unless the `Lazy` is in a static field. 

I had thought so too as I'd remembered using it as such. But ended up with some compile errors. 
 However, I now realize I'm an idiot - though I had marked the `Lazy<T>` as an instance member and not explicitly static, I was trying to inline the initialization (outside of the ctor) which, looking at it now, is obviously a static "context".  No wonder I was getting compilation errors.

This was my idiocacy:
`	private readonly Lazy<string> _lazy = new Lazy<string>(Initialize);
`

> ```cs
> public class MyService
> {
> 	private readonly Task _initializedTask;
> 
>     public MyService(...)
>     {
>         // Start initialization, and stash the task, but do not await it
>         // Absolutely DO NOT call .Wait or .Result ;)
>         // One thing to watch out for here: 
>         // The "synchronous code" in DoInitializationAsync, up to the first await that
>         // actually has to wait, may run inline, and the constructor won't return
>         // until you get to the first await.
>         // If you don't want that, use Task.Run(() => DoInitializationAsync());
>         // That will actually push the synchronous work over to the thread-pool
>         _initializedTask = DoInitializationAsync();
>     }
> 
> 	public async Task SomeMethodAsync()
>     {
>         await _initializedTask;
>         // Move on with the operation.
>     }
> }
> ```

Thank you for this example and I **greatly appreciate** the comments within them!

**Comment by anurse** [comment]
Yeah, that's a sneaky one :). Field initializers aren't quite the same as constructors.

Glad this helped!
