### ISSUE TITLE
Microsoft.AspNetCore.Http.HttpRequest.Form hangs in ASP.NET WebForms

### ISSUE THREAD

**Issue by Sina-Soltani** [dotnet/aspnetcore#20877]
### Describe the bug
I'm working on a nuget library which must be compatible with all ASP.NET products (WebForms, MVC and .NETCORE).
The project works with HttpContext. So I use the Microsoft.AspNetCore.Http.HttpContext as a wrapper and create different instances of it by using OWIN.

To make an instance of Microsoft.AspNetCore.Http.HttpContext I do so:
- For ASP.NET CORE I use the default IHttpContextAccessor.
- For ASP.NET MVC and ASP.NET WebForms I use the [Microsoft.AspNetCore.Owin 2.2.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Owin/2.2.0) package.

Everything works fine in Asp.Net Core and ASP.NET MVC applications. But In an ASP.NET WebForms application, the app hangs by reading the posted form.

```c#
if (request.HasFormContentType)
{
   var form = await request.ReadFormAsync(); // it hangs here
   // or
   var value= request.Form["key"]; // it hangs also here
}
```

### To Reproduce
- Create an ASP.NET WebForms web application
- Install [Microsoft.Owin.Host.SystemWeb 4.1.0](https://www.nuget.org/packages/Microsoft.Owin.Host.SystemWeb/4.1.0)
- Install [Microsoft.AspNetCore.Owin 2.2.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Owin/2.2.0)

Add the following codes in an aspx.cs file for a Button:
```c#
using System;
using System.Web;
using System.Web.UI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Owin;

protected void Button1_Click(object sender, EventArgs e)
{
   var owinContext = System.Web.HttpContext.Current.GetOwinContext();

   var owinEnvironment = owinContext.Environment;

   var aspNetCoreHttpContext = new DefaultHttpContext(new FeatureCollection(new OwinFeatureCollection(owinEnvironment)));

   if (aspNetCoreHttpContext.Request.HasFormContentType)
   {
      var form = aspNetCoreHttpContext.Request.ReadFormAsync().GetAwaiter().GetResult();
      // or
      var value = aspNetCoreHttpContext.Request.Form["key"];
   }
}
```
Run the application and click on the button.
Again, everything such as reading the query strings or writing the data in response work fine.
The problem is only when I want to read a posted form.

### Further technical details
- ASP.NET WebForms
- Nuget: [Microsoft.AspNetCore.Owin 2.2.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Owin/2.2.0)
- IDE: VS 2019 Community

**Comment by blowdart** [comment]
This isn't the right place for OWIN questions I'm afraid. Please open at issue at https://github.com/aspnet/AspNetKatana/issues

**Comment by blowdart** [comment]
Oh wait I take that back, because you're mixing Core.

**Comment by Sina-Soltani** [comment]
I updated the description for explaining the problem a bit better.

**Comment by blowdart** [comment]
@tratcher any thoughts?

**Comment by Sina-Soltani** [comment]
Here you can see the [OWIN implementation of IHttpContextAccessor](https://github.com/Sina-Soltani/Parbad/blob/master/src/Parbad.Owin/Http/OwinHttpContextAccessor.cs)
100% compatible with ASP.NET MVC 4+
And the only problem with it inside an ASP.NET WebForms is reading a posted form.

**Comment by Tratcher** [comment]
`ReadFormAsync().GetAwaiter().GetResult();` That's a red flag, WebForms really doesn't like blocked async calls. Does it work if you make the callstack fully async?

**Comment by Sina-Soltani** [comment]
@Tratcher I just tried it. It works! So the problem in WebForms is the GetAwaiter() methods.

**Comment by Sina-Soltani** [comment]
But it still hangs if I get the form like so:
```c#
var value = aspNetCoreHttpContext.Request.Form["key"];
```

**Comment by Tratcher** [comment]
Request.Form calls GetResult internally because there is only an async parser.

**Comment by Sina-Soltani** [comment]
@Tratcher Thank you.
