### ISSUE TITLE
Why <div>s can't be put inside a <dl> in Razor?

### ISSUE THREAD

**Issue by NagayamaToshiaki** [dotnet/aspnetcore#20886]
As of HTML5.2 or later, &lt;dl&gt;'s content model accepts &lt;div&gt;s as a parent of &lt;dt&gt;s and &lt;dd&gt;s.
https://www.w3.org/TR/html52/grouping-content.html#the-dl-element
But Razor doesn't allow me to do so, who says "They can't be nested."
HTML5.2以降では、&lt;dl&gt;のコンテンツモデルに&lt;dt&gt;&lt;dd&gt;を含んだ&lt;div&gt;が許されています。
しかし、Razorでは「要素'div'を要素'dl'内にネストすることはできません。」という注意が表示されてしまいます。注意なのでビルドは可能です。

### Describe the solution you'd like
Simply allow &lt;div&gt; to be a child of a &lt;dl&gt;.
現行仕様に合わせて&lt;dt&gt;&lt;dd&gt;を含んだ&lt;div&gt;を許可すべきです。

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@NagayamaToshiaki Razor doesn't special case tags in that way. What are you seeing that makes you believe a <div> can't be put inside a `<dl>`?

**Comment by NagayamaToshiaki** [comment]
Thanks for replying.
The message was a caution, so I could build it.
Come to think of it, this problem might be the Visual Studio's Intellisense.
Thus I am going to issue some feature request for VS about the compliance.
