### ISSUE TITLE
Uncaught exception when pressing  Ctrl+S on Blazor web server app hosted on Azure Appservice

### ISSUE THREAD

**Issue by saadsaeed01** [dotnet/aspnetcore#20897]
### Description
Hello 
I am working on Blazor Server application and have deployed it on Azure App Service. When I Click ctrl + s in my browser and click cancel afterwards:

![image](https://user-images.githubusercontent.com/33133831/79858322-af01bf00-83e8-11ea-9884-35ac05cab3de.png)

My buttons stop working. I keep clicking them but I  am not getting any result

### Exception
In my console I am getting the following error:
![image](https://user-images.githubusercontent.com/33133831/79438180-a413ec80-7fec-11ea-919d-b6a9974d7a69.png)

Please tell me what should I do I am not getting this error on localhost but on only on the deployed Azure App Service Instance.

### Further technical details
- ASP.NET Core version 3.1.101
- Microsoft Visual Studio Community 2019

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by saadsaeed01** [comment]
Ok. Thank you very much. We will create a sample Blazor App and deploy it on App Service. After that we will check that whether the Error is being produced again. I will update you soon.

**Comment by saadsaeed01** [comment]
@mkArtakMSFT Hello Artak. I hope you are fine. I have created a demo project and uploaded it on git. Here is the link of the repository
https://github.com/saadsaeed01/BlazorDemoAppForTesting

We have also publish this app to an Azure App Service instance. Here is the link to deployed app.
https://testsavebug.azurewebsites.net/counter

When we checked whether this error was getting reproduced in clean Blazor Application we found that it was getting reproduced. Here is the screenshot

![image](https://user-images.githubusercontent.com/33133831/79856760-37329500-83e6-11ea-80cc-b2710df2b930.png)

To reproduce this error just go the counter tab, press ctrl + s  and click cancel. 

![image](https://user-images.githubusercontent.com/33133831/79856933-72cd5f00-83e6-11ea-8705-fb7c384aae7f.png)

Afterwards the button stops working. When you go and check the console you will see the same error which I have posted above. 

 We have deployed this app on web app services located in two different resource groups. One of these resource group and web app service was new and created only for this purpose. Waiting for your kind response. Thank you.

**Further Technical Details**
This error occurs only on Chrome and Edge. Its not occurring on FireFox

**Comment by saadsaeed01** [comment]
> We have also published this app to an Azure App Service instance. Here is the link to deployed app.
> https://testsavebug.azurewebsites.net/counter
> 
> When we checked whether this error was getting reproduced in clean Blazor Application we found that it was getting reproduced. Here is the screenshot
> 
> ![image](https://user-images.githubusercontent.com/33133831/79856760-37329500-83e6-11ea-80cc-b2710df2b930.png)
> 
> To reproduce this error just go the counter tab and just press 'Click Me' button few times than press ctrl + s and click cancel. After that when you will click on that button again it will not respond
> 
> ![image](https://user-images.githubusercontent.com/33133831/79856933-72cd5f00-83e6-11ea-8705-fb7c384aae7f.png)
> 
> Afterwards the button stops working. When you go and check the console you will see the same error which I have posted above.
> 
> We have tested this issue on several resource groups with two different Azure account. Waiting for your kind response. Thank you.
> 
> **Further Technical Details**
> 
> * This error **occurs only on Chrome and Edge Chromium** after deploying on Azure. Its not occurring on **FireFox**
> * The error does not appear when running on any **browser** on **local machine**

**Comment by saadsaeed01** [comment]
Hello @mkArtakMSFT 

First of all I want to apologize that I mistakenly closed the issue. The issue is still **opened** and **valid**.

As it has been added to the backlog, we are now taking down the example Web App Service link provided above. Thanks

**Comment by javiercn** [comment]
I can repro this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to address in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
