### ISSUE TITLE
Testing: RedirectHandler incorrectly copies Authorization header to redirected requests

### ISSUE THREAD

**Issue by rmja** [dotnet/aspnetcore#20896]
### Describe the bug
The [RedirectHandler](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Testing/src/Handlers/RedirectHandler.cs) copies the `Authorization` header to redirected requests which is inconsistent behavior compared to the [default behavior](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.allowautoredirect?redirectedfrom=MSDN&view=netcore-3.1#remarks) of HttpClient.

This will incorrectly make tests pass that will fail when the tested routes are connected to with a real HttpClient.

### To Reproduce

The following test does not pass:

```
public class RedirectTests : IClassFixture<WebApplicationFactory>
    {
        private readonly HttpClient _client;

        public DocumentsTests(CustomWebApplicationFactory factory)
        {
            _client = factory.CreateClient();
            _client.DefaultRequestHeaders.Add(HeaderNames.Authorization, $"Bearer key");
        }

        [Fact]
        public async Task ShouldReturnUnautorhizedWhenRedirected()
        {
            var response = await _client.PostAsync("/EndpointThatReturnsRedirectToARouteThatRequiresAuthentication", content);
            Assert.Equal(401, response.StatusCode);
        }
   }
```

### Further technical details
- ASP.NET Core version 3.1
- VS

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by fagnercarvalho** [comment]
Hey @rmja, I could be missing something but the `WebApplicationFactory` behavior looks consistent with the `HttpClient` default behavior. The default values for both [`WebApplicationFactoryClientOptions.AllowAutoRedirect`](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Testing/src/WebApplicationFactoryClientOptions.cs#L48) and [`HttpClientHandler.AllowAutoRedirect`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=netcore-3.1) is true. In both cases the request headers will be copied over to the redirected route.
