### ISSUE TITLE
Move the [FromQuery] attribute to an abstract layer instead of Microsoft.AspNetCore.Mvc.Core

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/aspnetcore#20895]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.

Example: I am trying to write an ASP.NET Core Web API. Also, I gonna share some classes between the API project and the SDK project of the API. For example:

```csharp
    public class FaceBookAccessTokenModel
    {
        [FromQuery(Name = "client_id")]
        public string ClientId { get; set; }
        [FromQuery(Name = "client_secret")]
        public string ClientSecret { get; set; }
        [FromQuery(Name = "code")]
        public string Code { get; set; }
        [FromQuery(Name = "grant_type")]
        public string GrantType { get; set; }
        [FromQuery(Name = "redirect_uri")]
        public string RedirectUri { get; internal set; }
    }
```

I want to share the classes with both accessible in the API and in the SDK. But that ends with my SDK project depend on `Microsoft.AspNetCore.Mvc.Core`. And that is strange.

### Describe the solution you'd like

Move the `FromQueryAttribute` to an abstract layer project, like `System.ComponentModel.Annotations`. So I can use it without referencing `Microsoft.AspNetCore.Mvc.Core`

### Additional context

Nope

**Comment by mkArtakMSFT** [comment]
Thanks for contacting this. This is not something we plan to do.
