### ISSUE TITLE
How to use DataTokens in ASP.NET Core 3.1 when performing dynamic routing?

### ISSUE THREAD

**Issue by mohammadshahabrafiq** [dotnet/aspnetcore#20904]
I am using the class DynamicRouteValueTransformer built into ASP.NET Core 3.1 to perform dynamic controller routing as demonstrated in the code below.

```
public class UrlRouteTransformer : DynamicRouteValueTransformer
{
    public override ValueTask<RouteValueDictionary> TransformAsync(HttpContext httpContext, RouteValueDictionary values)
    {
        var controller = "home";
        var action = "index";

        //Make decision here on which controller and action to call. i.e call the database etc

        values["controller"] = controller;
        values["action"] = action;

        return new ValueTask<RouteValueDictionary>(values);
    }
}
```
This code is working as expected, but I want to know how you would set data tokens?

I have noticed the interface `IDataTokensMetadata` and could provide an implementation in this class and register it with the endpoint metadata collection but not sure if this is the right/or best way to proceed? 

Any advice/guidance would be greatly received.

I have asked this question on [Stackoverflow](https://stackoverflow.com/questions/61173951/how-to-use-datatokens-in-asp-net-core-3-1-when-performing-dynamic-routing) but no one is biting.

Thank you.

**Comment by davidfowl** [comment]
Can you say why you want to use DataTokens? What data are you trying to store and where are you trying to use it?

**Comment by davidfowl** [comment]
cc @rynowak

**Comment by mohammadshahabrafiq** [comment]
I want to use data tokens to store data associated with the route that  will be available to other upstream middle ware and also will be available to the controller. When processing my request I want to access the database once and get all the data I need i.e node data and set the route values and data tokens with this node. I have this working on and [asp.net 2.1](https://github.com/mohammadshahabrafiq/dukaan/blob/master/dukaan.web/Infrastructure/Routing/PageRoute.cs) app but I am attempting to migrate it to 3.1

**Comment by mkArtakMSFT** [comment]
@rynowak moving this to `discussions`. Feel free to bring back if there is some code change associated with this which need to happen.

**Comment by remus-corneliu** [comment]
@mohammadshahabrafiq , I'm trying to migrate from .net core 2.1 to 3.1 and also need information associated with a route. can you share how you've managed to add data tokens to route ? I've posted a question on [stackoverflow] as well. Also I've noticed in microsoft docs this

> Migrate RouteData.DataTokens to retrieve IDataTokensMetadata from the endpoint metadata. 

but didn't find any examples on how to use IDataTokensMetadata to register datatokens to a route.


(https://stackoverflow.com/questions/64959855/asp-net-core-3-1-does-not-set-useendpoints-mapcontrollerroute-datatoken)

**Comment by davidfowl** [comment]
Re-opening this as I took a look and it seems like we don't expose this information for action constraints. The RouteContext should be populated with the appropriate data tokens here but isn't today. It's also too early to retrieve this information from the HttpContext (we haven't selected an endpoint as yet)

**Comment by remus-corneliu** [comment]
Ok, so what can I do to retrieve the data after the endpoint has been selected but before it starts executing? What should I be using, can you point me to an example or something ?

**Comment by davidfowl** [comment]
@remus-corneliu you should be able to write a matcher policy to do the same thing. Can you share the logic you had in the action constraint?
