### ISSUE TITLE
[Blazor][Question] Is authorization on the _blazor endpoint required?

### ISSUE THREAD

**Issue by cubed-it** [dotnet/aspnetcore#20902]
Unfortunately I can't find an answer to my question myself, so I like to ask for any advice:

The following problem:

I have a custom authorization handler in my blazor server application. When a request comes in, this authorization is applied to the endpoint of the initial request.
This initial endpoint request is followed by two more calls to the "_blazor" endpoint, the negotiate and websocket upgrade calls.

My question now is, should the calls to "_blazor" also go through the authorization pipeline? Or is the security guaranteed internally through the negotiation and can I simply set AuthorizationHandlerContext.Succeed for requests on the "_balzor" route?

Thanks for any help! 🍪

**Comment by kmanpro** [comment]
I am wondering the same thing.
In our case we are using ASPNetCore MVC and integrating blazor into it using razor components.
Do we need to secure the "_blazor" endpoint is it already protected?
