### ISSUE TITLE
[Question]: How to use gRPC as a custom storage provider for Identity

### ISSUE THREAD

**Issue by jamiedumont** [dotnet/aspnetcore#20905]
I'm a developer that's new to C# and the .NET ecosystem and have been trying to find my way. One of my biggest sticking points has been the requirement for user authentication via gRPC.

I've got a working application that uses Identity with a custom gRPC storage provider. Effectively any `IUserStore` operations that would normally access the database (CRUD operations and all Identity's `FindBy*` methods) use a gRPC service that performs the required operation on the database instead. This works well, but it required a lot of time/code to implement so I'm looking to make it a proper custom provider so that I am able to easily add this functionality to new applications.

The idea is to have a central gRPC service backed by a SQL DB, with many Identity clients accessing it. My service remains pretty much the same, but it's the client I'm struggling with. I'd like using this client to be as simple as calling something like the `UseCassandraStores` in the [Cassandra storage provider](https://github.com/lkubis/AspNetCore.Identity.Cassandra/wiki/Initial-Setup), but this is where I get out of my depth.

I assume my "Client" needs to be a class library that contains my UserStore and RoleStore (along with my versions of the IdentityUser & Role, even though they remain identical to the original Identity versions). I can see from the Cassandra provider that I need to implement an IdentityBuilder, but I'm struggling to find advice/guidance on how to do so.

I realise that I'm too inexperienced to be trying to work out an extremely niche and probably overly complex solution. Can anyone either point me towards some docs/guides that help me solve this specific issue or to a much easier alternative for using Identity over a gRPC connection.

Thanks for taking a look, Jamie

**Comment by blowdart** [comment]
You would implement the UserStore and RoleStore and that's it. The client in this sort of thing is your web application, and that's just the .Add().

The identity builder part of it is just extension methods which set everything up, you could base it on the [Cassandra one](https://github.com/lkubis/AspNetCore.Identity.Cassandra/blob/master/src/AspNetCore.Identity.Cassandra/Extensions/IdentityBuilderExtensions.cs), and just replace their User and Role stores with yours, and that's it.

If by client here you mean what we traditionally think of as a client, say a desktop app talking to your service, then you need something different, you need a way to authenticate that desktop app to your web site. Is that what you actually mean by client?

**Comment by jamiedumont** [comment]
> Is that what you actually mean by client?

This is where I've probably got confused and used the wrong terminology.

When I say "client" I'm referring to the client of my gRPC service ([as per this](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1)), which is also the storage provider for Identity.

Here's the [repo](https://github.com/jamiedumont/Acusoft.Identity) I'm currently working in. It's not working and very messy, but should help to illustrate what I'm trying to achieve.

In short, I'd like to have a .NET Core web app (multiple in reality) that I can add Identity and the custom storage provider to quickly and easily with something approximating this, reducing the boilerplate needed to access the user data on the other side of the gRPC connection:
```
services.AddIdentity<ApplicationUser, ApplicationRole>()
        .UseGRPCStores()
        .AddDefaultTokenProviders();
```
The storage provider is the `.Client` project in the above repo and is just referencing the `.dll` for the `.Client` project which contains my `UserStore` and `RoleStore` along with the required models. Those stores then make a call to the DB via the gRPC service in the `.Server` project in the above repo.

That's what I'm trying for, but I think I've got lost in the weeds. I've been fighting exceptions in my test application (that I'm adding Identity to) because it can't find the services it needs, hence my question about the IdentityBuilder Extension. Do I need the application to create a gRPC client (as in [this](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1#configure-grpc-client) type of client) which then gets passed to the class library (the `.Client` project) through the builder?

**Comment by blowdart** [comment]
What exceptions are you seeing? Copying the Cassandra approach would be how I'd do it.

**Comment by jamiedumont** [comment]
Initially it was a lot of invalid type exceptions which I've slowly worked through, mainly caused around the type `TSession` that gets passed into the builder. In the case of Cassandra it's a `<Cassandra.ISession>` and in the very-similar / nearly identical RavenDB it's an `<IDocumentStore>`. I assumed that my analog to a DB connection would be a gRPC client, but that was what caused the long list of exceptions.

Eventually arriving at this (without any session/type passed in)...
```
public static class IdentityBuilderExtensions
    {
        public static IdentityBuilder UseGrpcStores(this IdentityBuilder builder)
           => builder
               .AddGrpcUserStore()
               .AddGrpcRoleStore();

        private static IdentityBuilder AddGrpcUserStore(this IdentityBuilder builder)
        {
            var userStoreType = typeof(UserStore<>).MakeGenericType(builder.UserType);

            builder.Services.AddScoped(
                typeof(IUserStore<>).MakeGenericType(builder.UserType),
                userStoreType
            );

            return builder;
        }

        private static IdentityBuilder AddGrpcRoleStore(this IdentityBuilder builder)
        {
            var roleStoreType = typeof(RoleStore<>).MakeGenericType(builder.RoleType);

            builder.Services.AddScoped(
                typeof(IRoleStore<>).MakeGenericType(builder.RoleType),
                roleStoreType
            );

            return builder;
        }
}
```
...gets the app using the provider to build and run, but all the Identity routes are non-existent which makes me think that something still isn't right in the builder.

Ultimately I think I need to understand dependency injection better as I think that's my issue here. 

Also, I'm looking into whether I even need gRPC to be communicating with the SQL db, as it seems to be going against the grain hugely (and massively against all my experience with other environments). gRPC was introduced as an additional "layer" of security amid concerns of the web app being compromised and exposing the SQL server machine to attack, but I think that might unnecessary. Can you tell I'm deep in the weeds on this project?

**Comment by blowdart** [comment]
If you're backing this with a SQL server, then I'd just talk direct to the SQL Server, because you're going to have to figure out gRPC auth on top of everything else, and that is rather limited.

While I can't comment on your exact scenario, if your web app was compromised, then someone will have credentials to call your gRPC service from that, which in turn allows them to write and read from your SQL server, which is almost as bad as getting a connection string (with the exception you may have better logging in your gRPC server. However if you're using a SQL server which isn't exposed to the internet at large there's no real pressing advantage I can think of here.

**Comment by jamiedumont** [comment]
That's been my gut feeling: gRPC doesn't bring much to the table as a security tool (quite right to). 

The team I just joined have little web experience but lots of C# / SQL, whereas I have lots of web experience with other languages and databases, but little of the Microsoft ecosystem. 

The domain contains a lot of sensitive data and there's a nervousness around connecting SQL Server to a web server that could provide a platform of attack. gRPC was suggested (and implemented in a prototype) as an additional layer of obfuscation. I've been the person that's had to wrap my head around gRPC and integrating it with everything else we needed (Identity for example) and I'm hesitant to say it's the "right call" given the huge amount of extra work and complexity it introduced.

I've just seen that you're "the .NET security person" so possibly the best person who could have answered this, but do you have links to any books/resources/docs/anything that I can use to convince the team that gRPC isn't required for extra security and the standard practices are "enough"?

**Comment by blowdart** [comment]
I don't I'm afraid. I can see what they're trying to do, by constraining database access, but heck you could do that via REST or even SOAP calls if they wanted something in between.

However I can't speak to your risk model, so I can't make the call on whether this is overkill for you or not.

**Comment by jamiedumont** [comment]
No worries. We had a look at it again and decided that gRPC was just a lot of extra work for very little gain.

That said, in the interim I did get the gRPC-backed custom store working as I wanted. I did indeed need to use the same approach as the Cassandra example but needed to understand how services are run a little more to get it all working together.

Thanks for your help!
