### ISSUE TITLE
using router parameters, dispose not triggered

### ISSUE THREAD

**Issue by kmuthukumar23** [dotnet/aspnetcore#20910]
Hi Team,

i have faced issue for disposing the objects in razor page using router parameter navigation. 

I have a following scenarios.  

Creating the blazor server application with sdk 3.1.3 

called the dispose method in 'Counter.razor' and 'FetchData.razor' files. it will works fine when we navigates to other razor page which means, if i am navigates to counter.razor from fetchdata.razor, the fetchdata.razor's dispose method called and also navigates from counter.razor to fetchdata.razor, counter.razor's dispose method called. Its not a problem.

Now i have created the another razor page named as 'Router.razor' . Here i have used the boolean router parameters. update these in NavMenu.razor. 

If the boolean value is true, the counter value is incremented when we click the counter button. If it is false, then the counter decrements when we click the counter button.

`@page "/counterroute/{Virtualize:bool}"`

Here boolean is  true then the counter increment enabled if it false then decrement enable in same button in Router.razor page.

Now i need to call the dispose method in 'Router.razor' when navigates the boolean value true page to false or viceversa. But dispose is not called. 

But navigates to other razor pages its called. 

How can i achive the dispose method while using router parameters.

I have attached the sample for reference.

Please suggest any solution for this.

using VS 2019 16.5.3 

[routerSample.zip](https://github.com/dotnet/aspnetcore/files/4489336/routerSample.zip)

**Comment by javiercn** [comment]
@kmuthukumar23 thanks for contacting us.

The dispose method is only called when the component is actually disposed. When the matched component from routing is the same the component is not destroyed and what happens is that SetParametersAsync is called. In your case you need to call dispose on the old data within OnParametersSetAsync
