### ISSUE TITLE
[Blazor] Emit button click from javascript

### ISSUE THREAD

**Issue by clintnetwork** [dotnet/aspnetcore#20920]
Hey,

I use jQuery and I've a `@onclick` parameter on a button when I call `.click()` from jQuery it does not execute the code Blazor side.

I also have this problem with input and change, when the code is changed from jquery it does not emit the @bind value

Best regards

**Comment by javiercn** [comment]
@clintnetwork thanks for contacting us.

Can you provide a minimal repro project that demonstrates the issue so that we can investigate?
