### ISSUE TITLE
Extremely weird caching issue in Blazor Webassembly 3.2.0 Preview 4

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#20926]
1. Create a brand new Blazor Webassembly 3.2.0 Preview 4 project with Auth option of In-App accounts and no PWA. Start the Server project in Visual Studio
2. Register a new user, login and browse to "Fetch Data" page.
3. Now go to Pages/FetchData.razor page and change the title like so:
`<h1>Weather forecast - Changed</h1>`
4. Start the Server project, and browse back to the "Fetch Data" page. The update to the page title is not visible. 

Edit: The workaround to see the updates appears to be to perform a Rebuild of the solution, every time a change is made to the code. 

---------------
Technical details:
VS Studio 2019 Version 16.6.0 Preview 3.0
Blazor Webassembly 3.2.0 Preview 4
Tested in IE Edge Chromium and Chrome browsers. Also tested in Incognito mode. This does **not** appear to be a browser cache issue.

**Comment by danroth27** [comment]
@bancroftway How are you starting the Server project? Ctrl-F5 or F5?

**Comment by bancroftway** [comment]
> @bancroftway How are you starting the Server project? Ctrl-F5 or F5?
@danroth27  I have tried both Ctrl-F5 and F5. Same results.

**Comment by danroth27** [comment]
There was an issue with the Microsoft.AspNetCore.Components.WebAssembly.Build package that was uploaded for the 3.2 Preview 4 release. The package has now been replaced with a fixed package. To get the fix, clear your local nuget cache (`dotnet nuget locals all -c`) and then restore again.

**Comment by jernejk** [comment]
Thanks, I had the same problem.
I found out that something might be using `%USERPROFILE%\.nuget\packages\microsoft.aspnetcore.components.webassembly.build`, so make sure that's removed!

I found a rogue Visual Studio instance which I had to kill via task manager.

Also, I got back ~10GB while doing this. :)
