### ISSUE TITLE
Child Component Re-rendering before parameter changed or StateHasChanged() called by parent

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#20925]
### Describe the bug
After the page loads, I click a button that reloads a table filled with data from EF Core. The table is in a child component (TableBody.razor) of the @page parent component (Index.razor). The child component receives an array of records to load into the table. For some reason, the table starts to refresh before EF Core has returned its results. The results are the only parameter sent to the child component.

The parameter isn't changed yet and StateHasChanged() isn't called, so what else would cause the child component to re-render?

### Further technical details
- ASP.NET Core version 3.1.2

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Mac 8.6 Preview build 3437
- Include the output of `dotnet --info`:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

Are you passing a task down to the child component and awaiting it during `OnInitializedAsync` or during `OnParametersSetAsync`? If so, the answer is that Blazor renders the component twice when async work happens:
* One time after it goes async.
* One time after the async work completes.

If this is not the case, please provide a minimal repro project that demonstrates the issue you are facing.

**Comment by mrlife** [comment]
Hi @javiercn, I'm not passing a task, only an array. Is there any way to trace what is triggering a refresh of a child component? 

As this involves EF Core, I haven't been able to produce a repro yet.

I have a breakpoint on the `SetParametersAsync()` in the child component, and that gets hit right after `CountAsync()` is called on the `iQueryable` in the parent component.

**Comment by mrlife** [comment]
@javiercn Looks like this was auto-closed and I don’t want this to get lost in the shuffle, so adding this comment.

**Comment by mrlife** [comment]
@javiercn Looks like this was due to `EventCallback` incorporating the behavior of `StateHasChanged`, per the [ASP.NET Core Blazor event handling docs page](https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1).

> There's no need to manually call StateHasChanged.

@guardrex 
Would be useful for the lifecycle docs page to be updated and include in one place all ways the lifecycle comes into play.

**Comment by guardrex** [comment]
Yes, that's fine ... there's an existing section that can be expanded a bit with a cross-link to the Event Handling topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#state-changes

... would you mind opening the issue from the bottom of the Lifecycle topic? **_I'm buried in Blazor Server scaffolding code at the moment._** ⛰️⛏️😅
