### ISSUE TITLE
Role claim is not returned in Blazor WebAssembly 3.2.0 Preview 4 application

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#20928]
1. Create a new Blazor WebAssembly 3.2.0 Preview 4 project with auth option of In-App accounts. 
2. Add a new role, register a new user and add it to the role. Verify the user belongs to the role by checking the AspNetUserRoles table
3. Add this code somewhere in FetchData.razor
```
<AuthorizeView>
    <Authorized>
        <ul>
            @foreach (var claim in context.User.Claims)
            {
                <li><span>@claim.Type</span>-<span>@claim.Value</span></li>
            }
        </ul>
    </Authorized>
</AuthorizeView>
```
4. Clean, Rebuild the solution, and start the server project and navigate to 'Fetch Data' page. The role claim is not present.
------------
Technical details:
VS Studio 2019 Version 16.6.0 Preview 3.0
Blazor Webassembly 3.2.0 Preview 4
Tested in IE Edge Chromium and Chrome browsers.

**Comment by javiercn** [comment]
@bancroftway that's not enough to enable roles.

Follow the steps described [here](https://github.com/dotnet/AspNetCore.Docs/issues/17649#issue-595771756)
