### ISSUE TITLE
dotnet core oauth2 not working

### ISSUE THREAD

**Issue by krishnamurthypradeep** [dotnet/aspnetcore#20939]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@krishnamurthypradeep thanks for contacting us.

Can you provide more details of what is that you think is not working and ideally a repro project with instructions on how to reproduce the issue?
