### ISSUE TITLE
[WebAssembly 3.2.0 Preview 4] Cannot consume scoped service 'Microsoft.Extensions.Logging.ILoggerProvider' from singleton 'Microsoft.Extensions.Logging.ILoggerFactory'.

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#20938]
hello guys, since the last webAssembly update i have error at startup of my app.
Cannot consume scoped service 'Microsoft.Extensions.Logging.ILoggerProvider' from singleton 'Microsoft.Extensions.Logging.ILoggerFactory'.

All my services are injected as scoped, and the problem is when i try to connect my personnalize logger (to call a controller on the log and not just log in the console)

````
builder.Services.AddLogging(b => b
                .AddMyLogger() // Add Blazor.Extensions.Logging.BrowserConsoleLogger
                .SetMinimumLevel(LogLevel.Trace));

public static ILoggingBuilder AddMyLogger(this ILoggingBuilder builder)
        {
            builder.Services.TryAddEnumerable(ServiceDescriptor.Scoped<ILoggerProvider, LoggerProvider>());
            builder.Services.Add(ServiceDescriptor.Scoped(typeof(ILogger<>), typeof(MyLoggerImplementation<>)));
            return builder;
        }

public class MyLoggerImplementation<T> :  ILogger<T>
````
I try to change the way i connect my  logger, like this, 
````
 builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<ILoggerProvider, LoggerProvider>());
````
but i met others problems
````
Cannot consume scoped service 'OneOfMyService' from singleton 'Microsoft.Extensions.Logging.ILoggerProvider'.
````

so i don't know how to solve this, maybe is not the good way to connect a personalize logger now, i was coding this by taking the code of BrowserConsoleLogger few month ago but i don't know how to do this now.

thanks for your help !

**Comment by smartprogrammer93** [comment]
@julienGrd Since ILoggerFactory is a defined as a singleton and depends on ILoggerProvider. you should change ILoggerProvider to be a singleton as well. in Blazor webassembly, singleton and scoped is the same thing. So logically you wont have a problem.

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

You could inject an IServiceProvider into your service and resolve the scoped dependency there. That should work for Blazor webassembly, but I would suggest you avoid having scoped dependencies in your ILogger.

**Comment by julienGrd** [comment]
OK guys is finally solve it by removing my scoped service to my ilogger implementaton, which is now singleton.
