### ISSUE TITLE
HTTP2: Log a debug message when connection reaches maximum active stream limit

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#20930]
It is common for HTTP/2 clients to queue requests when the maximum active stream limit is reached on a connection.

To help people debug this scenario it would be useful if Kestrel logged a debug message when a connection reaches the maximum active stream limit. e.g. the limit is 100 and the 100th active stream starts.

Note that this logging is different than this existing error logging in Kestrel when a client attempts to exceed the limit and the stream is refused.

@davidfowl @Tratcher @halter73 @shirhatti

**Comment by Tratcher** [comment]
Every time, or just the first time the limit is hit per connection?

**Comment by JamesNK** [comment]
I was thinking every time.

**Comment by anurse** [comment]
What about a counter as well? We could have a DEBUG level log (or maybe even TRACE given the counter?) and a counter "connections-exceeded-stream-limit" that is incremented each time a connection exceeds (or maybe just when it meets) it's stream limit. That would allow you to monitor the system and then turn up the logs when you want to see which connections are misbehaving.

**Comment by anurse** [comment]
Triage notes: Let's just use the Debug log for now, no counter (we're not sure that the count is that useful).
