### ISSUE TITLE
Adding echo statement to start command fixes timeout error.  Why?

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#20949]
I created new angular app using `dotnet new angular`.  
ran `npm install`

The app runs.

To update to the new angular libraries I deleted the ClientApp folder than ran the following:

`ng new ClientApp`
`npm install`

Running the app yields this:

> An unhandled exception occurred while processing the request.
TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.

I found [this article](https://jasontaylor.dev/asp-net-core-angular-9-upgrade/) that recommends the following change to package.json:

Change:

	"start": ng serve",

To this:

	"start": "echo Starting... && ng serve",

Much to my surprise this works. Why?  Is this really a fix or is there some other error it is masking?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We haven't yet implemented support for Angular 9. The article you're pointing to also refers to [this bug](https://github.com/dotnet/aspnetcore/issues/17277), which should also help. Closing this as a dupe.
