### ISSUE TITLE
Blazor wasm localization not working in preview 4

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#20945]
### Describe the bug
Blazor wasm localization is not working for components loaded from a separate razor class library. 

### To Reproduce
Steps:
1. Clone the repository - this is based on the original [example](https://github.com/pranavkm/LocSample) given in the official [docs](https://docs.microsoft.com/en-au/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1#blazor-webassembly) from @pranavkm 
https://github.com/Stamo-Gochev/LocSample

2. Run the app and open the index.razor page.

3. Change the culture from the culture selector

![localization](https://user-images.githubusercontent.com/1857705/79570786-be1ffe80-80c2-11ea-89d3-e4feaf76159e.gif)

### Expected result
The `<LocalizedComponent>` is localized.

### Actual result
Localization is not applied

### Addition info
I want to make a separate [razor class library](https://github.com/Stamo-Gochev/LocSample/tree/master/RazorClassLibrary1) that can be used in multiple projects and provide the localization of its components using `.resx` files, which are located in a [Resources](https://github.com/Stamo-Gochev/LocSample/tree/master/RazorClassLibrary1/Resources) folder. The [LocalizedComponent](https://github.com/Stamo-Gochev/LocSample/blob/55c61b7ace8578b0242e701aeff804b004ac019c/RazorClassLibrary1/Components/LocalizedComponent.razor#L6) relies on [IStringLocalizer](https://github.com/Stamo-Gochev/LocSample/blob/55c61b7ace8578b0242e701aeff804b004ac019c/RazorClassLibrary1/Components/LocalizedComponent.razor.cs#L10) for the localization from these `.resx` files.

@pranavkm How can this be achieved? Is this supported by wasm? If not, can you suggest an alternative for a third-party class library to provide component localization in its own assembly when used in a separate wasm project?

### Further technical details
- ASP.NET Core version: 3.1.201 (wasm preview 4)
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by pranavkm** [comment]
@Stamo-Gochev https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#resource-file-naming has some details about how `IStringLocalizer` calculates paths for localized resources. In general, class libraries that contain localized resources should use `ResourceLocationAttribute` to configure the folder containing their resx file. In your case, this would look like:

```C#
[assembly: ResourceLocation("Resources")]
```

since these files are located in a folder named `Resources`.

**Comment by Stamo-Gochev** [comment]
@pranavkm I added the [resource path](https://github.com/Stamo-Gochev/LocSample/commit/690ef4542f83f0f53b2e15db42bd17da2062122c), but the end result is the same - am I missing something?

**Comment by Stamo-Gochev** [comment]
@pranavkm I added the [resource path](https://github.com/Stamo-Gochev/LocSample/commit/690ef4542f83f0f53b2e15db42bd17da2062122c) to the library and to the [app](https://github.com/Stamo-Gochev/LocSample/commit/6f7a97dc5ddf2bcd507b57383ae35107b0df296f) as well, but the end result is the same - am I missing something?

**Comment by pranavkm** [comment]
@Stamo-Gochev the path for resx files is calculated from the type name. Your resx files in the RCL need to be in a the folder path /Resources/Components. 

I'd recommend reading the documentation I linked to earlier - it goes in to quite a bit of the details about how paths for resx files are calculated.

**Comment by Stamo-Gochev** [comment]
Thanks, I was able to get the default localization messages for the component, but what is the approach for allowing the users of the class library to override the default `.resx` files in their own apps? The current structure of the RCL is:
```
RazorClassLibrary1
├───Components
└───Resources                      
    └───Components 
	    └───LocalizedComponent.fr-FR.resx
```
Neither this:
```
LocSample
├───Pages                     
├───Resources                       
│   ├───Pages                       
│   └───RazorClassLibrary1          
│       └───Components  
			└───LocalizedComponent.fr-FR.resx
```
nor this:
```
LocSample
├───Pages                     
├───Resources                       
│   ├───Pages                       
│   └───RazorClassLibrary1.Components.LocalizedComponent.fr-FR.resx
```
works. Is that expected?

**Comment by SQL-MisterMagoo** [comment]
I have a working example based on @pranavkm 's sample repo if anyone is interested

The RCL project is here https://github.com/SQL-MisterMagoo/LocSampleResources

and the Blazor project is here https://github.com/SQL-MisterMagoo/LocSample
(I just added a reference to the package created by LocSampleResources and put the HelloWorld component on the index page - otherwise it is the same)
