### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Negotiate SPN with Port ignored

### ISSUE THREAD

**Issue by danstur** [dotnet/aspnetcore#20942]
Not sure if this is a bug or a feature request. It's at least unexpected, given that registering SPNs with port works fine with MSSQL. But it's hard to find documentation on this. 

### Describe the bug
Registering a SPN as `setspn -S HTTP/myservername.mydomain.com:5000 myuser` (notice port 5000) seems to be ignored by Kestrel. Registering the SPN as `setspn -S HTTP/myservername.mydomain.com myuser` work as expected. The error that appears is the same as in #20540 

The problem with the non-port version is that this means there can only be a single user that hosts asp.net core applications on a server (DNS aliases might work I guess, but that's rather roundabout). 

### To Reproduce
Use any default asp.net core template then add authentication as described [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#kestrel). Register the SPNs as described above and call any authenticated API from outside. 

I could upload a solution if this is required. 

### Further technical details
- ASP.NET Core 3.1
- Microsoft.AspNetCore.Authentication.Negotiate 3.1.0
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
AspNetCore isn't involved in SPN validation. The SPN is part of the Kerberos blob and is checked by the underling OS libraries.

The other key question here is do you know what SPN the client generates as part of the request? It's possible to decode the blob and see the raw value from the client. It won't matter what you configure for the server unless the client generates something that matches it.

**Comment by danstur** [comment]
@Tratcher Yeah I went digging through the code too and the ReflectedNegotiateState.cs class uses [AuthenticationHelper.NtAuth](https://github.com/dotnet/corefx/blob/a3ab91e10045bb298f48c1d1f9bd5b0782a8ac46/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L93) which sets the SPN to `HTTP/<HostName>`. So I don't think there's anything I can do here, but I might misread the code.

I'm just surprised that the way the SPNs seem to work for HTTP that there's no way to use multiple different users to host HTTP applications under the same user. I didn't find any documentation how the client determines the SPN though or if you can send multiple values. I'll see if I can find something out using Wireshark.

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/sql/reporting-services/report-server/register-a-service-principal-name-spn-for-a-report-server?view=sql-server-ver15
"HTTP SPNs do not require a port."
https://docs.microsoft.com/en-us/archive/blogs/autz_auth_stuff/how-to-name-a-spn-part-2
"If you are using the default port number for you application, then you don't need to add the port number when you are registering SPN because Internet Explorer knows that the port number should be ignored when requesting a Kerberos ticket. On the other hand, if you are using a different port number, e.g. 82, then everything becomes a bit trickier."
