### ISSUE TITLE
How to use QueryHelpers outside Asp.net core?

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/aspnetcore#20946]
### Is your feature request related to a problem? Please describe.
I am trying to use the `QueryHelpers` class from the `Microsoft.AspNetCore.WebUtilities` project in plain .net standard (so outside asp.net core).

Basically I want to write a client for Azure Durable Functions. Azure Durable Functions [returns a json object containing several URLs with query strings when triggering a durable function](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#start-orchestration). I would like to parse those query strings:

```json
{
    "id": "abc123",
    "purgeHistoryDeleteUri": "http://localhost:7071/runtime/webhooks/durabletask/instances/abc123?code=XXX",
    "sendEventPostUri": "http://localhost:7071/runtime/webhooks/durabletask/instances/abc123/raiseEvent/{eventName}?code=XXX",
    "statusQueryGetUri": "http://localhost:7071/runtime/webhooks/durabletask/instances/abc123?code=XXX",
    "terminatePostUri": "http://localhost:7071/runtime/webhooks/durabletask/instances/abc123/terminate?reason={text}&code=XXX"
}
```

Unfortunately I can't add a reference to `Microsoft.AspNetCore.WebUtilities` because it is not published as a separate nuget package.

### Describe the solution you'd like
One of these:
- Publish the underlying packages again so that they can be consumed by non-asp.net core projects
- Publish the publish the non-asp.net core-specific http classes separately

**Comment by Tratcher** [comment]
When you only need one class it might be simpler to copy that file into your project.

**Comment by hansmbakker** [comment]
In this case it is 2 classes (QueryHelpers needs another class from this project) but I can imagine that in general there are more of these classes.

In the past these utilities were in System.Web I believe but now that is gone.

**Comment by ryanelian** [comment]
> Unfortunately I can't add a reference to Microsoft.AspNetCore.WebUtilities because it is not published as a separate nuget package.

Excuse me, this might be the package you're looking for: (unless I'm mistaken)

https://www.nuget.org/packages/Microsoft.AspNetCore.WebUtilities/

I think I've used QueryHelpers in my Blazor Class Library project (which is .NET Standard not .NET Core) using that package.

**Comment by Tratcher** [comment]
We stopped producing that package in 3.0. Yes, you can use the old version if it doesn't cause version conflicts for you.

**Comment by hansmbakker** [comment]
Yes indeed, the package is not being produced anymore. I would find it helpful if it would be released again.

Would there be any downsides to enabling releasing it as a NuGet package?

**Comment by Tratcher** [comment]
We consolidated almoat everything into the shared framework. There are a lot of tradeoffs.

By the way, what framework are you targeting? We only support netcore now.

**Comment by hansmbakker** [comment]
I am using Uno / UWP / .net core for my client.

I would say that should work via netstandard?

Would like it if this functionality would be available outside asp.net core again!

**Comment by BrennanConroy** [comment]
This is not an API we are wanting to support outside of the shared framework at this time.

You can copy the source if you're interested in using this outside the shared framework.
