### ISSUE TITLE
Cannot use IAccessTokenProvider inside layout or child components

### ISSUE THREAD

**Issue by kostasxagoraris** [dotnet/aspnetcore#20947]
I m trying to use the sample application provided with a new webassembly blazor application (hotsed .net core) with identity server.

I tried to dynamically retrieve the menu from the server based on the logged in user.

 When I try to use 

 `var tokenResult = await AuthenticationService.RequestAccessToken();` 

this line of code within the 

NavMenu.razor page i get this:

 Unhandled exception rendering component: Cannot read property 'getAccessToken' of undefined

How can I use the accesstoken outside an authorized page (child components or layouts or the menu?

HEre is the full stack trace

blazor.webassembly.js:1 ﻿crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Unhandled exception rendering component: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       TypeError: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at Function.getAccessToken (https://localhost:44310/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4264)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at https://localhost:44310/_framework/blazor.webassembly.js:1:9740
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at new Promise (<anonymous>)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at Object.beginInvokeJSFromDotNet (https://localhost:44310/_framework/blazor.webassembly.js:1:9709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at _mono_wasm_invoke_js_marshalled (https://localhost:44310/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:161382)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at do_icall (wasm-function[6030]:0x10fe48)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at do_icall_wrapper (wasm-function[1890]:0x52a54)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at interp_exec_method (wasm-function[1115]:0x2551f)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at interp_runtime_invoke (wasm-function[5637]:0xf8709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at mono_jit_runtime_invoke (wasm-function[5089]:0xdf083)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 TypeError: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at Function.getAccessToken (https://localhost:44310/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4264)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at https://localhost:44310/_framework/blazor.webassembly.js:1:9740
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at new Promise (<anonymous>)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at Object.beginInvokeJSFromDotNet (https://localhost:44310/_framework/blazor.webassembly.js:1:9709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at _mono_wasm_invoke_js_marshalled (https://localhost:44310/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:161382)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at do_icall (wasm-function[6030]:0x10fe48)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at do_icall_wrapper (wasm-function[1890]:0x52a54)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at interp_exec_method (wasm-function[1115]:0x2551f)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at interp_runtime_invoke (wasm-function[5637]:0xf8709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at mono_jit_runtime_invoke (wasm-function[5089]:0xdf083)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2fbee40 + 0x00034> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`2[TRemoteAuthenticationState,TProviderOptions].RequestAccessToken () <0x2920628 + 0x00186> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2fc4808 + 0x0002c> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Olympus.Artemis.Client.Shared.NavMenu.OnInitializedAsync () [0x0005f] in C:\Users\Kostas\Source\Repos\Olympus.Artemis\Olympus.Artemis\Client\Shared\NavMenu.razor:37 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2cd5ba8 + 0x0014c> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2efd140 + 0x000c2> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 ﻿crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Unhandled exception rendering component: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       TypeError: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at Function.getAccessToken (https://localhost:44310/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4264)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at https://localhost:44310/_framework/blazor.webassembly.js:1:9740
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at new Promise (<anonymous>)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at Object.beginInvokeJSFromDotNet (https://localhost:44310/_framework/blazor.webassembly.js:1:9709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at _mono_wasm_invoke_js_marshalled (https://localhost:44310/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:161382)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at do_icall (wasm-function[6030]:0x10fe48)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at do_icall_wrapper (wasm-function[1890]:0x52a54)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at interp_exec_method (wasm-function[1115]:0x2551f)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at interp_runtime_invoke (wasm-function[5637]:0xf8709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at mono_jit_runtime_invoke (wasm-function[5089]:0xdf083)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 TypeError: Cannot read property 'getAccessToken' of undefined
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at Function.getAccessToken (https://localhost:44310/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4264)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at https://localhost:44310/_framework/blazor.webassembly.js:1:9740
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at new Promise (<anonymous>)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at Object.beginInvokeJSFromDotNet (https://localhost:44310/_framework/blazor.webassembly.js:1:9709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at _mono_wasm_invoke_js_marshalled (https://localhost:44310/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:161382)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at do_icall (wasm-function[6030]:0x10fe48)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at do_icall_wrapper (wasm-function[1890]:0x52a54)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at interp_exec_method (wasm-function[1115]:0x2551f)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at interp_runtime_invoke (wasm-function[5637]:0xf8709)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at mono_jit_runtime_invoke (wasm-function[5089]:0xdf083)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2fc2be0 + 0x00034> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`2[TRemoteAuthenticationState,TProviderOptions].RequestAccessToken () <0x2f54198 + 0x00186> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2fc6e60 + 0x0002c> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Olympus.Artemis.Client.Shared.NavMenu.OnInitializedAsync () [0x0005f] in C:\Users\Kostas\Source\Repos\Olympus.Artemis\Olympus.Artemis\Client\Shared\NavMenu.razor:37 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2cd5ba8 + 0x0014c> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2efe928 + 0x000c2> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Unhandled exception rendering component: Value cannot be null.
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Parameter name: source
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 System.ArgumentNullException: Value cannot be null.
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Parameter name: source
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) <0x319b018 + 0x00014> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Telerik.Blazor.Components.TelerikMenuBase`1[TItem].ItemFetched (System.Object id) <0x319a7d8 + 0x00036> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Telerik.Blazor.Components.TelerikMenu`1[TItem].<BuildRenderTree>b__0_0 (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder2) <0x3197f48 + 0x000c2> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent (System.Int32 sequence, Microsoft.AspNetCore.Components.RenderFragment fragment) <0x2dbe1e0 + 0x0001e> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.CascadingValue`1[TValue].Render (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder builder) <0x3197790 + 0x00010> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch (Microsoft.AspNetCore.Components.Rendering.RenderBatchBuilder batchBuilder, Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x2cd8878 + 0x00054> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch (Microsoft.AspNetCore.Components.Rendering.RenderQueueEntry renderQueueEntry) <0x2cd8308 + 0x0004c> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x2cd7970 + 0x00092> in <filename unknown>:0 
p.printErr @ blazor.webassembly.js:1

Here is the full code of  NavMenu.razor

`@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
 

@inject IAccessTokenProvider AuthenticationService
@inject NavigationManager Navigation
@using Olympus.Artemis.Shared

<div class="top-row pl-4 navbar navbar-dark">
    <a class="navbar-brand" href="">Olympus.Artemis</a>

</div>
<AuthorizeView>
    <Authorized>
        <TelerikMenu Data="@MenuItems"
                     UrlField="@nameof(MenuItem.Page)"
                     ItemsField="@nameof(MenuItem.SubSectionList)"
                     TextField="@nameof(MenuItem.Section)" Orientation="@MenuOrientation.Vertical" >
        </TelerikMenu>
    </Authorized>
    <Authorizing>
        Loading...
    </Authorizing>
</AuthorizeView>
@code {
    public List<MenuItem> MenuItems { get; set; }

    protected override async Task OnInitializedAsync()
    {

        var httpClient = new HttpClient();
        httpClient.BaseAddress = new Uri(Navigation.BaseUri);
        var tokenResult = await AuthenticationService.RequestAccessToken();

        if (tokenResult.TryGetToken(out var token))
        {
             httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token.Value}");
             MenuItems = await httpClient.GetJsonAsync<List<MenuItem>>("/api/Menu");
         }
    }
}
`

**Comment by javiercn** [comment]
@kostasxagoraris thanks for contacting us.

What Blazor version are you using?

**Comment by kostasxagoraris** [comment]
I had the version 3.2.0-preview3 and now I updated to the newest version 3.2.0-preview4 and the problem is still there

**Comment by kostasxagoraris** [comment]
Any news? Because the problem is very persistent,,
Thank you
