### ISSUE TITLE
CI unable to install dotnet-ef

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#20955]
Win7 and Win8 agents are failing in ProjectTemplates.Tests trying to install dotnet-ef.

```
Running 'C:\h\w\A3FF092E\p\sdk\x64/dotnet tool install dotnet-ef --global --version 5.0.0-preview.4.20215.1'
'C:\h\w\A3FF092E\p\sdk\x64/dotnet tool install dotnet-ef --global --version 5.0.0-preview.4.20215.1' completed with exit code '1'
Exception in InstallAspNetAppIfNeeded: System.InvalidOperationException: Command C:\h\w\A3FF092E\p\sdk\x64/dotnet tool install dotnet-ef --global --version 5.0.0-preview.4.20215.1 returned exit code 1
   at RunTests.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in C:\h\w\A3FF092E\w\B32B0A1A\e\RunTests\ProcessUtil.cs:line 144
   at RunTests.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in C:\h\w\A3FF092E\w\B32B0A1A\e\RunTests\ProcessUtil.cs:line 144
   at RunTests.TestRunner.InstallAspNetAppIfNeededAsync() in C:\h\w\A3FF092E\w\B32B0A1A\e\RunTests\TestRunner.cs:line 136
```

@HaoK  is working on adding more logs here.

https://dev.azure.com/dnceng/internal/_build/results?buildId=603871&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/internal/_build/results?buildId=604194&view=ms.vss-test-web.build-test-results-tab&runId=18998130&resultId=120299&paneView=debug
https://dev.azure.com/dnceng/internal/_build/results?buildId=604848&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/internal/_build/results?buildId=605130&view=ms.vss-test-web.build-test-results-tab&runId=19026724&resultId=120297&paneView=attachments
https://dev.azure.com/dnceng/public/_build/results?buildId=604460&view=ms.vss-test-web.build-test-results-tab

This one is a bit different:
`Tool 'dotnet-ef' is already installed.`
https://dev.azure.com/dnceng/public/_build/results?buildId=605452&view=ms.vss-test-web.build-test-results-tab&runId=19034852&resultId=120299&paneView=attachments

**Comment by anurse** [comment]
This is more of an infrastructure issue. It's not related to our installers.

**Comment by Tratcher** [comment]
@HaoK let us know if you can resolve this today. Otherwise we'll need to disable the affected tests since this is failing most Master builds.

**Comment by HaoK** [comment]
Just waiting for the PR checks here https://dev.azure.com/dnceng/public/_build/results?buildId=606091&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a

**Comment by HaoK** [comment]
Might need to just disable them for now, helix looks hung, but I'll get the fix in over the weekend at this rate

**Comment by HaoK** [comment]
Ubuntu job upload has been sitting there for 45 min

**Comment by HaoK** [comment]
Actually spoke too soon, helix checks are green, I'll need to back out the queue changes tho, and the linux check failed due to disk space again i guess? https://github.com/dotnet/aspnetcore/pull/20958/checks?check_run_id=596558412

**Comment by Tratcher** [comment]
I just merged a fix for the Linux issue. Rebase.

**Comment by HaoK** [comment]
Should be fixed by https://github.com/dotnet/aspnetcore/pull/20958
