### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by itfm** [dotnet/aspnetcore#20957]
**.NET CORE 3.0 VS 2019**
I transfered existing, working code to a new domain for testing. The domain is hosted on the same server, but has its own dedicated ip. I have a form that makes an ajax post to the the new test domain.  I get this standard cors error in the JS console when I look at it.

![image](https://user-images.githubusercontent.com/20067689/79594133-80af7700-80aa-11ea-9a40-a8d2641aec8d.png)

**Here is my relevant  CORS code:**
 ```
services.AddCors(options =>
            {
                options.AddPolicy(MyAllowSpecificOrigins,
                builder =>
                {
                    builder.WithOrigins("MY ORIGIN DOMAIN HERE");
                });
            });
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
           ...
...
...                    options.UseSqlServer(Configuration.GetConnectionString("ShopifyToFMToCambey_CoreContext")));
            
            
            
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseCors(MyAllowSpecificOrigins);
            app.UseMvc();
```

No errors appear in the IIS logs, no 500s or 403s anything like that in the console, it just appears CORS has stopped working when I moved the code to the test domain (I created a new build profile and just published to the new test directory, nothing special).  I've tried changing the cors policy to let everything in any origin, any header, any verb, basically I allowed anything and everything and the result was the same.

**Comment by claudiogodoy99** [comment]
Helloou.
That error look like something about your ajax request.
Did you try add Origin and Host headers in your ajax request?
Are you using Jquery to do ajax call?

**Comment by javiercn** [comment]
@itfm thanks for contacting us.

We don't have enough information to determine what is going on here. I would suggest you provide detailed traces about the request and responses from the server so that we can determine if there's a bug in here.
