### ISSUE TITLE
Trying to use WebSockets as SignalR transport via WWW Proxy

### ISSUE THREAD

**Issue by Arkasian** [dotnet/aspnetcore#20956]
# Issue Title
Trying to use WebSockets as SignalR transport via WWW Proxy

# General
Technical info at the beginning:
**OS**: Debian 10 "buster" (upgrade from Debian 9, kernel 4.19)
**SDK**: .NET Core SDK 3.1.100 is used to build.
**Runtime**: .NET Core Runtime 3.1.1 is used to deploy an app.
**WWW Proxy**: Apache 2.4.25
**ASP.NET Core SignalR** of version 2.4.1.

So my issue is: I want to use WS as a transport for my website, but whenever I will try to connect using it, SignalR throws the following error on client-side:
``
Firefox can’t establish a connection to the server at wss://dev-core.lukas-bownik.net/hubs/media?id=zbGWDjVqkGEOW47lSeWwqQ. signalr.min.js:16:109830
``
``
[2020-04-17T15:49:24.647Z] Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.
``
If you want to see it for yourself: [url to my dev instance of app](https://dev-core.lukas-bownik.net/Storage/Browse?path=%2FWallpapers_Gifs)
And here is my configuration for SignalR:
[Startup.cs](https://github.com/Arkasian/pika-core/blob/development/Startup.cs)
And here is my configuration for Kestrel for this app:
[Program.cs](https://github.com/Arkasian/pika-core/blob/development/Program.cs)
I think that there is something wrong, but I just can't see it, or is there any error inside Core or SR which makes it immpossible?
Correct me please, if I am mistaken.
Greetings!

**Comment by Arkasian** [comment]
Yea, I have enabled those. Apache successfully loads wstunnel mode and it is configured to use RewriteEngine, but I am not sure if I rewrite correctly. 
Could you please take a look at my VHost configuration to say if it is okay?
[apache.conf.txt](https://github.com/dotnet/aspnetcore/files/4494736/apache.conf.txt)

**Comment by BrennanConroy** [comment]
That seems fine. Does using localhost instead of 127.0.0.1 for websockets cause issues?

Could you show your [server logs](https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging)? It's be nice to see if the websocket request is reaching the server.

**Comment by Arkasian** [comment]
[access.log](https://github.com/dotnet/aspnetcore/files/4494818/access.log)
[error.log](https://github.com/dotnet/aspnetcore/files/4494822/error.log)
Yea, here you go, but I dont think it will help. There is nothing really interesting in there, but I dont see anything related to WS for now.

**Comment by anurse** [comment]
@Arkasian those aren't the server logs @BrennanConroy was asking for 😄. Take a look at the doc he linked: https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging - We're specifically looking for logs from the ASP.NET Core app while you attempt to make a connection rather than access/error logs from your proxy.

**Comment by Arkasian** [comment]
Oh, well, I guess I was pretty tired. I will try to turn loggin on Kestrel on. Then I will pass those.
