### ISSUE TITLE
Allow method to control inclusion/exclusion of ASPNETCORE_HOSTINGSTARTUPASSEMBLIES variable in web.config for Razor runtime compilation from publish profiles

### ISSUE THREAD

**Issue by PillowMetal** [dotnet/aspnetcore#20965]
Since the introduction of .NET 3.0 when Razor runtime compilation was no longer active by default, I have used the following reference in .csproj:

```cs
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.3"
    Condition="'$(Configuration)' == 'Debug'" />
```

and the following code in Startup.cs:

```cs
IMvcBuilder builder = services.AddControllersWithViews();
#if DEBUG
 if (_environment.IsDevelopment())
    _ = builder.AddRazorRuntimeCompilation();
#endif
```
I do this so that the several Razor runtime compilation files are only included in DEBUG builds but not RELEASE builds, and thereby the appropriate files, and only necessary files, are deployed to my Development, Staging, and Production web servers on publish (even though technically they are not needed on the Development server either but are referenced in Startup.cs so have to be in the DEBUG build configuration at least).

I now see that the .NET Core new app template in the 3.1.201 SDK has an implementation of Razor runtime compilation that involves including the package reference (without debug condition or privateassets="all") and a new variable in launchSettings.json ASPNETCORE_HOSTINGSTARTUPASSEMBLIES that references the assembly; no code in startup is needed.

This works of course, and has promise in that I could possibly now remove my Startup initialization code, and potentially even use PrivateAssets="All" on my package reference, so that the Razor runtime DLLs are not deployed to any web server, even Development.

However, I can no longer control the inclusion or exclusion of the Razor runtime compilation DLLs that get deployed on DEBUG and RELEASE builds when I publish, even if I add the DEBUG condition or PrivateAssets="All" on the package reference, because any change to launchSettings.json recreates the web.config file (and updates the .deps.json file) so that these DLLs must be included regardless of build configuration.

ASPNETCORE_ENVIRONMENT has the same issue, except that you can use 

```cs
<EnvironmentName>Development</EnvironmentName>
```
in the .pubxml file to dictate and override what is placed in web.config on publish.

I'm not sure if they already is someway to control this, but what I would like to see and would solve my problem is if there was a .pubxml element (like there is for Environment) that would allow me to specify ASPNETCORE_HOSTINGSTARTUPASSEMBLIES, and/or its value, is or is not to be included in web.config, much like the Environment can be specified for web.config.

**Comment by pranavkm** [comment]
@PillowMetal you could continue using the old pattern if it works fine. We considered using the same pattern in the template, however restore isn't configuration specific and switching between Debug and Release might result in weirdness. Of course if you're aware of this and understand how this works it works plenty well. It's just not a solution we could use in our templates. The side effect of this is that you end up with additional files in the publish output. 

If you'd like, you could write an msbuild target to remove these manually as a post-publish step.
