### ISSUE TITLE
An error that keeps comming

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20961]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/987386/an-error-that-keeps-comming.html)._

---
[regression] [worked-in:16.5.3]
I keep on getting this error message in my debugger:
CS0103 The name '__builder' does not exist in the current context

This shows in a copy of the razor page i'm using but with .g.cs behind it.
This is what i see on the page:

#line default
#line hidden
#nullable disable
        __builder. AddMarkupContent(0, "        \r\n");
#nullable restore
#line 69 "C:\Users\Eigenaar\source\repos\Projecten\BlazorServer\InfoCentrumUI\InfoCentrumUI\Snippets\OverigeFormulieren\AdvancedDropDownMenu.razor"
        dropDownMenu.TweedeId = int. Parse(e.Value.ToString());
    }

This keeps happening in every few hours. I even tried to use older versions from my projects from github.
Which use to work and they also give me the same error. Even when i didnt type any code. As soon as i start to run the
application the same message appears.	

I have reinstalled visual studio and it worked for a few hours but now it starts to happen again.
I didn't have this problem before until i updated it to this version: 16.5.3

Could you please help me with fixing this problem...

---
#### Visual Studio Feedback System on 4/13/2020, 02:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by yasirerkam** [comment]
i have this problem, is there a solution?  i tried a few things but error keeps comming

**Comment by yasirerkam** [comment]
i downgraded 16.5.1 just now but still getting same error.

**Comment by yasirerkam** [comment]
now this time ther is Visual Studio Compatibility with .net core 3.1.2 and vs 16.4.6.
I'm tired...

**Comment by yasirerkam** [comment]
I found a temporary solution: Using code behind

1. Create new class same name with your razor page. For example if your razor page name mypage.razor create mypage.razor.cs.
2. And than move your @code part to new class you created. 
3. Don't forget to make partial your new class.

**Comment by mkArtakMSFT** [comment]
Thanks for sharing extra details, @yasirerkam.
Have you tried the latest preview version of VS 16.6 ?
If yes, do you experience this issue with a newly created project or with an existing one?
