### ISSUE TITLE
Remove `textDocument/Hover` LSP Request Silent Failure

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#20962]
Catch all (https://github.com/dotnet/aspnetcore-tooling/pull/1800#discussion_r409947160) was added to ensure silent failure till Roslyn's support for `textDocument/hover` is inserted into VS. This issue is to track the removal of this catch all.

**Comment by NTaylorMullen** [comment]
Marking as blocked until Roslyn's hover support is in VS

**Comment by TanayParikh** [comment]
VS Insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/242979?_a=overview

**Comment by TanayParikh** [comment]
Due to https://github.com/dotnet/aspnetcore-tooling/pull/1807 we'll also need to wait on the insertion of the Language Server Client (for supporting multiple hover handlers) and WTE HTML LSP (for HTML `textDocument/hover` support).
