### ISSUE TITLE
Blazor: MouseEventArgs should include BoundingClientRect 

### ISSUE THREAD

**Issue by gmnenad** [dotnet/aspnetcore#20960]
When mouse events (like OnPointerDown, OnClick) are used to determine position on resizable element, we need entire BoundingClientRect. 

Not only are X and Y coordinates insufficient for that, but even adding  OffsetX and OffsetY ( from  #8241 ) is not enough if we need to determine relative position of click on resizable element.

Alternative used in JavaScript is to just call getBoundingClientRect(), but that would be significant latency hit for already **latency-challenged Blazor** : our server already received info about user click some 40ms later (assuming that is latency between browser and server ), and if we now use InvokeAsync to call JavaScript for current BoundingClientRect, it would waste another 40ms.

**Example:**

I needed virtual touch keyboard for my emulator of an old 8-bit computer,  if used from mobile devices that do  not have physical keyboard - and standard mobile software keyboard was not good fit due to reasons [explained here](https://eagle.azurewebsites.net/about#tcKeyboard).

Such virtual keyboard can be [seen here](https://eagle.azurewebsites.net/about#tcKeyboardComp) in enlarged form, if "keyboard example" collapsible is clicked to expand, or it can be seen here in actual [emulator application]( https://eagle.azurewebsites.net/orao/Manic%20Miner?Text=%0A~%0A~~3) , if browser is in portrait mode ( either from mobile device, or resizing desktop browser window to be narrow).

**Problem in that example:**
Keyboard need to be as large as possible, which means resizing to fit entire width of portrait browser window. Therefore positions of individual keys will not be at same absolute positions ( where OffsetX/Y could have helped), but will move depending on width of BoundingClientRect - influenced by width of current browser window or current mobile display.

In order to calculate which key was pressed on click, I would need either to call   getBoundingClientRect() on every pointer event (bad choice), or to make elaborate workarounds as [explained here ](https://eagle.azurewebsites.net/about#tcSession), which include my browser resize event, and calling JavaScript getBoundingClientRect() only on resizes, which minimize additional latencies ... but is fairly complex workaround for simpler cases.

**Solution Suggestion:**
Include BoundingClientRect within MouseEventArgs returned by MouseEvents ( and inherited for PointerEvents). That should not be additional performance cost ( I presume OffsetX/Y from  #8241 already call getBoundingClientRect, and in any case that call would  be done on JavaScript side ), and would actually replace need for OffsetX/Y since OffsetX ==  Mouse.X- BoundingClientRect.Left. 
But most importantly, **it would allow us to determine relative position of mouse event on element without additional JavaScript call.**

**Comment by javiercn** [comment]
@gmnenad thanks for contacting us.

We'll discuss this within the team and update the issue accordingly. Normally we try to avoid adding synthetic properties to our events and we just try to mimic the DOM events.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to include in the framework. We believe the following change would help users to handle similar scenarios easier on their own: https://github.com/dotnet/aspnetcore/issues/17552
