### ISSUE TITLE
Debug-level configuration not respected by logger

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#20969]
It appears that there has been a regression in support for configuring the logging builder using the `builder.Configuration` object. 

**To reproduce**
1. Create a new Blazor WASM project.

```
$ dotnet new blazorwasm -o logger-repro 
```

2. Create a wwwroot/appsettings.json file with the following contents.

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  }
}

```

3. Read from the configuration in the startup code.

```csharp
Console.WriteLine(builder.Configuration);
```

4. Add a set of logging statements to the `Counter` component.

```
@page "/counter"

@inject Microsoft.Extensions.Logging.ILoggerFactory factory
@using Microsoft.Extensions.Logging

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        var logger = factory.CreateLogger<Counter>();
        logger.Log(LogLevel.Information, "This is info.");
        logger.Log(LogLevel.Critical, "This is critical.");
        logger.Log(LogLevel.Debug, "This is debug.");
        logger.Log(LogLevel.Error, "This is error.");
        logger.Log(LogLevel.Warning, "This is warning.");
        logger.Log(LogLevel.Trace, "This is trace.");
        currentCount++;
    }
}
```

5. Run the app and observe that when you click the increment button the information, critical, error, and warning log levels are always displayed regardless of the default log level that has been configured.

**Comment by captainsafia** [comment]
🤦 This is actually working but the `AddConfiguration` invocation should be:

```
builder.Logging.AddConfiguration(builder.Configuration.GetSection("Logging"));
```

**Comment by captainsafia** [comment]
Closing as this was resolved in #20973.

**Comment by SteveSandersonMS** [comment]
@captainsafia Aha! I got confused by this just now, but [your answer](https://github.com/dotnet/aspnetcore/issues/20969#issuecomment-615490858) solved it.

I couldn't find any info on this in the docs. Do you think we're missing this? Or did I not look in the right place?

**Comment by captainsafia** [comment]
Our logging docs are located [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#create-logs-in-blazor) but they don't specifically call out needing to invoke `builder.Logging.AddConfiguration(builder.Configuration.GetSection("Logging"))` to use logging settings from appsettings.

I opened https://github.com/dotnet/AspNetCore.Docs/issues/18444 for this.
