### ISSUE TITLE
Calling base.BuildRenderTree(builder) from Customer component

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#20979]
### Questions
- Is it required or optional to call `base.BuildRenderTree(builder)` from a custom component? If required,
- Does it have to be in a specific order? In other words, should be located at the very top or bottom?

**Comment by javiercn** [comment]
@ylr-research thanks for contacting us.

If you are inheriting from ComponentBase it is required, otherwise your component won't re-render since ComponentBase makes sure that multiple synchronous calls to StateHasChanged only result in a single render.

**Comment by ylr-research** [comment]
@javiercn thanks. Does it matter if placed at the beginning or the end?
