### ISSUE TITLE
Blazor wasm linker fatal error after updating to preview 4

### ISSUE THREAD

**Issue by DreCorp** [dotnet/aspnetcore#20978]
AFTER updating to preview 4, `dotnet run` works fine, the app runs and works as intended, `dotnet publish` publishes to Debug folder with no issues, but `dotnet publish -c Release` gives a linker fatal error:
` ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor.HttpClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`

**Comment by Madajevas** [comment]
Just had same issue.
`dotnet clean -c Release`
`dotnet publish -c Release`
Did the trick.

**Comment by DreCorp** [comment]
Yes, thank you **Madajevas**, this fixed the issue.
