### ISSUE TITLE
'@bind="Prop"' not working in blazor server

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#20980]
how do i bind value to variable in blazor server
i have a razor .cshtml host file and i render the component like this:

```
<div class="flex-fill">
    ADMIN
    <component type="typeof(Admin)" render-mode="Server" />
</div>
<script src="~/_framework/blazor.server.js"></script>
```

![image](https://user-images.githubusercontent.com/43137837/79630669-90cf6100-8153-11ea-9dbb-411e3144d4ca.png)

![image](https://user-images.githubusercontent.com/43137837/79630579-c9bb0600-8152-11ea-9779-efdc2addf35c.png)

```
 @{
     public string Username { get; set; }
     public string Password { get; set; }
 }
```

the value is not updating the prop in any of the cases above

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
System.InvalidOperationException: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'sSybftOpF4fRcIDDG_-77eJLM3fnb-8A9fqdgzR02V8'.
System.AggregateException: One or more errors occurred. (InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.)
 ---> System.InvalidOperationException: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```
happens when i do `@bind="Username"`

EDIT:
!image(https://cdn.discordapp.com/attachments/169726586931773440/701272929970814976/unknown.png) 
is how it looks on my vs preview, i have tried turning resharper on and off

weirdly, when i create a new blazor server project, it will work and show the good colors, even with resharper, maybe this has to do with the component being integrated to an existing web app (razor pages)

**Comment by javiercn** [comment]
@ctigrisht thanks for contacting us.

You can't use `@bind` and `@onchange` at the same time.

**Comment by mkArtakMSFT** [comment]
It looks like you're using `@bind` in a `.cshtml` file. Blazor components are represented using `.razor` files and that's where `@bind` is known. Please fix your component too.

**Comment by ctigrisht** [comment]
> It looks like you're using `@bind` in a `.cshtml` file. Blazor components are represented using `.razor` files and that's where `@bind` is known. Please fix your component too.

this is a .razor file that is rendered from a .cshtml file, just like `_Host.cshtml` renders `App` or another component

**Comment by javiercn** [comment]
@ctigrisht I would suggest you look at the delta between your app and a new app, there might be something missing there that is causing this behavior.

**Comment by joseph-turk** [comment]
I am also experiencing this issue. I have added some routable components to an existing MVC app using the approach outlined [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#use-routable-components-in-an-mvc-app). This is a snippet where the binding is not working for me.

```
@page "/locations"

<div>
    <input @bind="SearchTerm" />
</div>

@code {
    private string SearchTerm { get; set; }
}
```

The SearchTerm property never updates.
