### ISSUE TITLE
Custom Attributes in Blazor Server Pages like ActionFilter in AspCore

### ISSUE THREAD

**Issue by mbedded** [dotnet/aspnetcore#20986]
I have an issue with custom Attributes to add logic via @attribute-Annotation in a Blazor-Page.
I posted the issue in the documentation repo at first. I was told this would be the correct place :)

As example i have in ASP Core an action with a parameter. With the annotation (ActionFilter) i want to verify the parameter before the Controller executes.

```
// Example code
[CheckProjectId] // Extends ActionFilterAttribute
public IActionResult DisplayProject(int projectId){
  return View();
}
```

The `CheckProjectAttribute` verifies if the ID exists. If true: Nothing happens. If false, there will be a redirect to "project not found view".

I would like to add such logic to Blazor Server.

Pseudocode
```
@page "/project/{projectId:int}"
@attribute [CheckProjectId]

<h1>Content</h1>
```

For me it seems that ActionFilter is not working for Blazor. Is there a different type i can use to inject logic into the workflow?
I could write something like

```
@code {
  protected override async Task OnInitializedAsync() {
    // Check parameter and do redirect if project not existing
  }
}
```

but this doesn't look good to me compared with attributes because i think it's cleaner to abort the request as early as possible instead of adding checks into every component itself and overwrite an additional method which is not needed in most components (in my case).

Thank you for your help.

--- 
_Original Issue:_
https://github.com/dotnet/AspNetCore.Docs/issues/17893

**Comment by javiercn** [comment]
@mbedded thanks for contacting us.

There is no such thing, ActionFilters are an MVC concept. If you want to enable something like this, the best you can do is create your own base class and have all your components inherit from it. There is no way for you to inject your own logic on third-party components.

**Comment by mbedded** [comment]
Is there a plan for the future to add something like this? I mean: The MVC Pipeline is very nice and it's easy to inject custom action for the "way in" and "way out" without much overhead.

Thank you very much for your quick response. I guess i will create a base class with those check-methods and call them in the "OnInitialized" method..
