### ISSUE TITLE
Blazor - Partial classes not recognised

### ISSUE THREAD

**Issue by LukeTOBrien** [dotnet/aspnetcore#20989]
Hi chaps!

What do I need for [partial class support](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#partial-class-support)?  
As the see in my screen below, I'm getting errors and I think I'm doing everything correctly.  
I also have this strang `_generated_` class (??)

![image](https://user-images.githubusercontent.com/16164373/79644843-6ad1ad00-81a3-11ea-9b36-04a9b30452be.png)

Target Framework: `.Net Standard 2.1`.  
When I right click on the `.razor` file, the `Custom Tool` is `MSBuild:RazorGenerateComponentDeclarationDesignTime`.  
When I do `dotnet --list-sdks`, the list contains
`3.1.201 [C:\Program Files\dotnet\sdk]`.  
I have installed the Web Assembaly template with `dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview4.20210.8`

This is a repo that I created on another machine, that other machine I have been using Blazor for a while now and partial class support works fine.

Any idea?  
When I can get on the other PC, I will check out what versions on everything it has.

**Comment by LukeTOBrien** [comment]
I just noticed that [3.2.0-preview4 was on the 16th April](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/)... So my other PC has a slightly older version.

So on the new template the `Startup.cs` is gone (breaking change) and the `*.Blazor` packages have changed to `*.Components.WebAssembly`.  
As an aside, personally I like the `Startup.cs`, you are alwas going to register your DI and adding the in Program main is not a good idea.  

I now think that I am having an issue with Visual Studio, not the compiler, as I can run the app despite VS showing build errors.

**Comment by LukeTOBrien** [comment]
Okay... So it turns out that I updated Visual Studio and then it magicly detected my patial classes...

My point about the `Startup.cs` still stands though, I would like to see it's return in future versions of the template.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like the only remaining point here is the ask to have a separate `Startup` class where you will register your services instead. Given that main part of this issue is unrelated to that, can you please close this issue and file a new issue with that request, so that we avoid confusion in the future?

**Comment by LukeTOBrien** [comment]
Okey dokey
