### ISSUE TITLE
Blazor Server Side - WebSocket closed with status code: 1006 ()

### ISSUE THREAD

**Issue by fiha8** [dotnet/aspnetcore#20984]
I have Blazor Server Side app working without any troubles locally, but when I put it on the server, I'm getting this anoying error very often, especially when using backend services:

`Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().`

Can't do anything until the page is refreshed.

I have read a lot in different topics, but haven't found a decent solution. Anyone knows, where exactly is the problem and how to figure it out. At least how to catch this error in the code to handle it?

I'm using the service with DbContext to handle DB operations. If I change the architecture to the API and Blazor UI with HttpClient ... could it help with this issue?

Thanks.

**Comment by fiha8** [comment]
I can only share the temporary solution. If you get this error, this script is waiting, if the server is back, and reloading the page automatically.

```JavaScript       
<script>
        var webSocket = new WebSocket("ws://yoursiteurl/_blazor");
        webSocket.onclose = function (event) {
            if (event.code == 1006)
            {
                async function waitAndReload() {
                    await fetch('');
                    location.reload(true);
                }
                waitAndReload();
            }
        };
</script>
```

But still looking for real solution, which is to avoid this error. Or at least better temporary solution, for example catch this error before and handle this reloading without page getting faded. 
Thanks.

**Comment by javiercn** [comment]
@fiha8 thanks for contacting us.

This sounds like an issue in your environment that is affecting websockets. Can you provide more details on what your environment looks like (from the browser to the server, please include gateways, reverse proxies, etc that might be in the middle).

I would check your configurations for those.

@anurse is there any signalr guidance about this? I believe that this has to do with the signalr websocket connection since that's what Blazor uses under the hood, can your team help out here?

**Comment by mkArtakMSFT** [comment]
@anurse can you please look into this? Thanks!

**Comment by anurse** [comment]
I agree with @javiercn 's initial investigation. The 1006 error code indicates that the server abruptly terminated the connection which means we'll need much more information about the server and network to find out why. We have a full guide to collecting the necessary diagnostics here: https://aka.ms/aspnet/signalr/troubleshoot

@fiha8 please let us know:

1. The browser you are using
1. Any proxies (Corporate Firewalls, etc.) that might be in use
1. The server OS and .NET Core version in use
1. Any server logs you can collect [using the instructions in the diagnostics guide](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging)

That will help us diagnose this further.

> @anurse can you please look into this? Thanks!

Yep, we'll take a look.

**Comment by fiha8** [comment]
Thank to all of you for your effort, but my apologies. Probably I've found the issue. I had to just increase Private Memory Limit in Application Pool. It was enough for my last app, seems like this app requires more. It looks like these troubles are away now. Thanks again, hope I didn't kill too much of your time.
