### ISSUE TITLE
dotnet.exe (2.1.513) exits on form input from dialog (file, color)

### ISSUE THREAD

**Issue by ajthegamedev** [dotnet/aspnetcore#20990]
# Description
Any form input that opens up a dialog to complete causes dotnet.exe to exit with code -1. Nothing important appears in the IISExpress logs either.

Specifically you can do this with the input types "file" and "color"

# Reproducing
Create a new ASP.NET Core Web Application

Insert the following anywhere in "/Views/Home/Index.cshtml":
```
<form>
	<input type="color" />
</form>
```

Run the application, click the color dialog, and select a color or hit cancel (doesn't matter).

The program '[15884] dotnet.exe' has exited with code -1 (0xffffffff).

This does not appear to stop the executing application in any way. But debugging is almost impossible.

# Version Info
Visual Studio 2017, 15.8.2
.NET Core SDK 2.1.513
.NET Core Runtime 2.1.17

# NuGet Versions (enforced by framework)
Microsoft.AspNetCore.App 2.1.1
Microsoft.AspNetCore.Razor.Design 2.1.2
Microsoft.NETCore.App 2.1.0

**Comment by javiercn** [comment]
@ajthegamedev thanks for contacting us.

Can you turn first chance exception on in Visual Studio and capture the callstack when this issue happens? I believe you are not correctly handling some error in your application.

**Comment by ajthegamedev** [comment]
Hi @javiercn sorry for the delay,

I've enabled all exceptions within "Exception Settings", all checked not just white-box defaults. The application exits when the color dialog is closed without breaking on any exceptions. I've also tried debugging as IISExpress and as the project name "WebApplication1". Do you have any other recommendations?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
