### ISSUE TITLE
Cannot post data to databasefrom EditForm with not logged user 

### ISSUE THREAD

**Issue by indieza** [dotnet/aspnetcore#21008]
Hello,
I try to post data in the database with not logged in user. When I click the submit button, noting is happened. I send the image of my Blazor component [https://ibb.co/5RsP2yY](url)
May you gave me more information about that. Thank you :)

**Comment by javiercn** [comment]
@indieza thanks for contacting us.

We don't have enough information to give you an answer. Could you please provide a minimal repro project so that we ca ntry and help you out?

**Comment by indieza** [comment]
Hello,
My repo is private so I add you as collaborator. Here is the are, where I use server-side Blazor
[https://github.com/indieza/SdvCodeWebsite/tree/master/SdvCode/SdvCode/Areas/SdvShop](url) 
Also when I try to submit some product comment when I am logged in, I cannot do it.
Here is the comment section
[https://github.com/indieza/SdvCodeWebsite/blob/master/SdvCode/SdvCode/Areas/SdvShop/Pages/Comments/CommentsSection.razor](url)

**Comment by indieza** [comment]
When I'm logged in and try to add new comment I receive that error message on the Chrome console
[https://ibb.co/RyBGVDn](url) 
Also, I want to gave access to not logged user to post some comments.

**Comment by indieza** [comment]
Hello, I find my mistake, I have ForeignKey conflict on adding some comment in database, because my structure is recursively, comment has parent comment of type comment. And when I add some data to the database, the ForeignKey was not nullable. Thank you for the support I appreciate it :)

**Comment by mkArtakMSFT** [comment]
Glad you've found the underyling issue, @indieza.
Closing as there are no pending investigations left here.
