### ISSUE TITLE
`dotnet new webapp --auth Individual` doesn't scaffold codes inside Identity folder

### ISSUE THREAD

**Issue by mrmowji** [dotnet/aspnetcore#21005]
### Describe the bug
Creating a new Razor Pages web app project with Individual authentication doesn't include any Identity code (Login, Register, etc.).

### To Reproduce
```bash
dotnet new webapp --auth Individual
```

Which outputs:
```
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/3.1-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on /.../MyProject.csproj...
  Restore completed in 11.92 sec for /.../MyProject.csproj.

Restore succeeded.
```

I got this `Areas` folder structure:
```
-- Areas
  -- Identity
    -- Pages
      -- _ViewStart.cshtml
```

### Further technical details
- ASP.NET Core version: 3.1.101
- Include the output of `dotnet --info`
```bash
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Code 1.44.2
- OS: Ubuntu 18.04.4 LTS

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is because the default Identity UI is now in a separate pacakge, which is being referenced by-default.
If you wish to customize the IdentityUI, you're free to do so by scaffolding individual or all parts of the default UI. You can read more about how to do this here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio
