### ISSUE TITLE
Unable to find document - Client Side Debugging

### ISSUE THREAD

**Issue by PylotLight** [dotnet/aspnetcore#21011]
### Describe the bug
When setting a breakpoint in VS Studio in client side code, I always get this type error:
// Unable to find document file:///D:/Documents/Scripting/C#\BlazorApp1\Client\Pages\FetchData.razor
This happens on new preview 4 templates as well.

### To Reproduce

Installed VSstudio with updated preview.
Setup new blazor preview 4 template with WASM and ASPNET Hosted options checked.
Set Breakpoint in client side code:
Got Exceptions? Include both the message and the stack trace
https://pastebin.com/AQQhNfAy
This debug output is everything up to first breakpoint, if I step once, its much of the same output.
### Further technical details
- ASP.NET Core version
![image](https://user-images.githubusercontent.com/7006124/79743547-1a478480-8348-11ea-96d3-2e331dc68653.png)

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015095
 Commit:    85c45057dc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19577
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015095\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
This occurs in both preview and non preview VS Studio
![image](https://user-images.githubusercontent.com/7006124/79743451-f126f400-8347-11ea-8e20-3aceec82ea91.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you try to rename the `C#` folder to something else to avoid the `#` character and see whether that fixes it? Thanks!

**Comment by PylotLight** [comment]
That does appear to have made a difference, thanks.

**Comment by mkArtakMSFT** [comment]
@lewing this seems to be an issue with the `#` in the file path. Will move to the `Mono` repo for investigation.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19616
