### ISSUE TITLE
app.UseMvcWithDefaultRoute(); not working in ASP.NET core MVC 3.1

### ISSUE THREAD

**Issue by Isuf9** [dotnet/aspnetcore#21010]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@Isuf9 thanks for contacting us.

Can you provide more details about what is not working here? What do you think it is supposed to work in a specific way and what is the actual behavior you are observing? Additionally, include a minimal repro project that demonstrates the issue?

**Comment by Isuf9** [comment]
Thanks for the comment,

I use into Configure method
app.UseMvcWithDefaultRoute();

, but this not working, I  read this article ->"This line works perfectly in ASP.NET Core 2.2 and routing works, however, in ASP.NET Core 3.0 it doesn't compile and displays the following error".

**Comment by javiercn** [comment]
@Isuf9 thanks for the details. I would suggest you follow the migration guide [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio) for details.
