### ISSUE TITLE
RazorTemplateEngine class not found after 3.0 update. After 3.0, use that class instead.

### ISSUE THREAD

**Issue by HDONGDeveloper** [dotnet/aspnetcore#21013]
RazorTemplateEngine class not found after 3.0 update.
After 3.0, use that class instead.

![image](https://user-images.githubusercontent.com/31230864/79751284-f0409300-8344-11ea-8d3a-98a19e7d7556.png)

**Comment by javiercn** [comment]
@HDONGDeveloper thanks for contacting us. I would suggest you check out the migration guide [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio) as it is likely you are missing some packages or settings in our project.

I would also suggest you create a new 3.0 project and checkout the differences between 2.2 and 3.0, and finally, **ASP.NET Core 3.0 is out of support, so you should be using ASP.NET Core 3.1 which is LTS**
