### ISSUE TITLE
This doesn't work with AWS Cognito

### ISSUE THREAD

**Issue by JSpring3** [dotnet/aspnetcore#21014]
I could not get your example working AWS Cognito.
It will send me back a valid ID token and a valid access token in the response but the example application does nothing with the two tokens so it doesn't display the name or show that you are logged in.

Here is my AWS Cognito Config
cc: @guardrex

```csharp
builder.Services.AddOidcAuthentication(options =>
{
    // Configure your authentication provider options here.
    // For more information, see https://aka.ms/blazor-standalone-auth

    options.ProviderOptions.Authority = "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ydUErvZQJ/";
    options.ProviderOptions.ClientId = "2m50t6m94ec7pcnuk4179k15sf";
    options.ProviderOptions.ResponseType = "token";
    options.ProviderOptions.RedirectUri = "https://localhost:5001";
    options.ProviderOptions.DefaultScopes.Add("aws.cognito.signin.user.admin");
    options.ProviderOptions.DefaultScopes.Add("email");
    options.ProviderOptions.DefaultScopes.Add("openid");
    options.ProviderOptions.DefaultScopes.Add("phone");
    options.ProviderOptions.DefaultScopes.Add("profile");

});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by blowdart** [comment]
If you capture the JWT and put it into a debugger like https://jwt.io/ does it have the claims you asked for?

**Comment by JSpring3** [comment]
> If you capture the JWT and put it into a debugger like https://jwt.io/ does it have the claims you asked for?

It does but it doesn't display on the blazor page...that is the issue at hand.

**Comment by javiercn** [comment]
@JSpring3 thanks for contacting us.

At the very least your response type should be `token id_token` I would suggest that you set it to `code` if AWS Cognito supports code+PKCE.

Do you see any error on the application console?

**Comment by JSpring3** [comment]
There are no console errors and no error codes in the network  tab.
The login is "successful" and redirects to the callback page but beyond that, no.
The AuthorizeView context is an AuthenticationState.User and displays the "NotAuthorized" block 
instead of the "Authorized" block. As I stated before, (now for the third time) I get a valid access and  id token back which can be seen in the network tab of Chrome tools. Changing the response type to token id_token generates an error.
```
<AuthorizeView>
    <Authorized>
        Hello, @context.User.Identity.Name!
        <button class="nav-link btn btn-link" @onclick="BeginSignOut">Log out</button>
    </Authorized>
    <NotAuthorized>
        <a href="authentication/login">Log in</a>
    </NotAuthorized>
</AuthorizeView>
```

**Comment by javiercn** [comment]
> The login is "successful" and redirects to the callback page but beyond that, no.

Do you mean `login-callback` or the return url, like `/fetchData`. Can you check the contents of the user claims principal? (As well as `AuthenticationStateProvider.GetAuthenticationState()` and `IAccessTokenProvider.RequestAccessToken().TryGetAccessToken(out var token)))`

It is impossible for us to test third-party providers, so providing us as much information as you can is the best way we can try and help you narrow down what's going on.

**Comment by brettwinters** [comment]
Just in case anyone else finds this issue. I can confirm that AWS cognito works using code flow with Blazor (ironically unlike Azure AD/B2C which doesn't [yet](https://github.com/MicrosoftDocs/azure-docs/issues/39201])

```c#
options.ProviderOptions.Authority = "https://cognito-idp.us-east-2.amazonaws.com/xxxxxxxx/";
options.ProviderOptions.ClientId = "xxxxxxxxx";
options.ProviderOptions.ResponseType = "code";
"openid profile email".Split(' ').ToList().ForEach(scope => options.ProviderOptions.DefaultScopes.Add(scope));

```

**Comment by JSpring3** [comment]
> Just in case anyone else finds this issue. I can confirm that AWS cognito works using code flow with Blazor (ironically unlike Azure AD/B2C which doesn't [yet](https://github.com/MicrosoftDocs/azure-docs/issues/39201%5D)
> 
> ```cs
> options.ProviderOptions.Authority = "https://cognito-idp.us-east-2.amazonaws.com/xxxxxxxx/";
> options.ProviderOptions.ClientId = "xxxxxxxxx";
> options.ProviderOptions.ResponseType = "code";
> "openid profile email".Split(' ').ToList().ForEach(scope => options.ProviderOptions.DefaultScopes.Add(scope));
> ```

I'm using the exact settings as you but the app doesn't display the user info even though the login was successful. What are you using for a callback url?

**Comment by brettwinters** [comment]
On Cognito's "App Client Settings" tab I'm using: 

Callback URL(s) : https://localhost:xxx/authentication/login-callback
Sign out URL(s) : https://localhost:xxx/authentication/logout-callback

xxx = your ports

Oh, one thing I noticed is that refresh tokens aren't [supported](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) so make sure your scopes don't include "offline_access" otherwise you'll get a 400 from AWS.

![image](https://user-images.githubusercontent.com/26474006/81618752-3f448a00-9412-11ea-9c3d-c3c47fe689b5.png)
