### ISSUE TITLE
Integration Test using HttpClientFactory and TestServer

### ISSUE THREAD

**Issue by martinisaksen** [dotnet/aspnetcore#21018]
### Is your feature request related to a problem? Please describe.
I am trying to write an integration test using `TestServer` for a web API that includes an `HttpClient` added via `services.AddHttpClient` that includes a custom message handler but there is no method on `TestServer` that allows me to get that configured `HttpClient`.

### Describe the solution you'd like
I would like to be able to get my configured `HttpClient` out of the `HttpClientFactory` so I can write integration tests against it using `TestServer`

### Additional context
My end goal is to test a package being consumed by a web API. This package adds metadata to incoming and outgoing calls (some of the metadata changes for each call, like a sequence id) and so I need to make multiple calls to make sure the metadata is correct and that the calls are still valid and processed correctly.

**Comment by Tratcher** [comment]
Like this? TestServer -> API Controller -> HttpClientFactory -> HttpClient with custom handler.

Inbound (TestServer) and outbound (HttpClient/Factory) are separate testing concerns unless you're trying to call back into the same site instance?

**Comment by anurse** [comment]
@martinisaksen Can you provide some code to illustrate the kind of test you're looking to write? That will help us identify the APIs or guidance we could provide to make it easier.

**Comment by martinisaksen** [comment]
Initially I was thinking I had to get the configured HttpClient out of the TestServer to call my second endpoint, but now realize that that is not how TestServer works.
I still have a problem using TestServer, and the problem is that I cannot call TestServer from within itself. My integration tests are trying to validate that a middleware and message handler are functioning and part of their logic is that a SequnceId gets incremented on every call and logged in each service. In practice this will be across multiple services but the logic would work if a service called itself too. I was hoping to use TestServer to speed up these tests, but when I have one endpoint call another endpoint in the same service (so same TestServer) it is unable to resolve itself.

Example:
```
[ApiController]
[Route("[controller]")]
public class FirstEndpoint : ControllerBase
{
    ...

    [HttpGet]
    public async Task<string> Get() {
        var httpClient = _clientFactory.CreateClient("TestHarness2");
         var response = await httpClient.GetAsync("SecondEndpoint");
         return $"Message from {nameof(FirstEndpoint)}";
    }
}

[ApiController]
[Route("[controller]")]
public class SecondEndpoint : ControllerBase
{
    ...

    [HttpGet]
    public async Task<string> Get() {
         return $"Message from {nameof(SecondEndpoint )}";
    }
}
```

The call to the second endpoint fails because it cannot resolve a URL that can connect to the TestServer. I've tried localhost and locahost:port but neither work.

I am don't see how using two TestServers would work either since the first TestServer would not know how to call the second TestServer.

**Comment by Tratcher** [comment]
> I am don't see how using two TestServers would work either since the first TestServer would not know how to call the second TestServer.

You build the backend TestServer first, get it's HttpClient/HttpMessageHandler, and pass that into the setup for the HttpClientFactory for the front end app.

You can do something similar with just one app by using a DelegatingHandler to break the chicken/egg cycle. You set up the HttpClientFactory to point to a DelegatingHandler instance, build the app, and then assign the DelegatingHandler's InnerHandler to point to TestServer's HttpMessageHandler.

**Comment by martinisaksen** [comment]
Thanks. Using the first option we ended up doing the following that works:

```
        /// <summary>
        /// Sets up the call chain in memory host and handlers.
        /// </summary>
        /// <returns></returns>
        public static HttpClient InitializeChain()
        {
            var httpMessageHandler3 = InitService3();
            var httpMessageHandler2 = InitService2(httpMessageHandler3);
            return InitTestHarness(httpMessageHandler2);
        }

        /// <summary>
        /// Service3 is the last in the chain
        /// </summary>
        /// <returns></returns>
        public static HttpMessageHandler InitService3()
        {
            var config = new ConfigurationBuilder()
               .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
               .AddJsonFile(appsettingsService3Path, optional: true, reloadOnChange: true)
               .AddEnvironmentVariables()
               .Build();

            var builder = new WebHostBuilder()
                .UseConfiguration(config)
                .UseStartup<Service3.Startup>();

            var server = new TestServer(builder);
            return server.CreateHandler();
        }

        /// <summary>
        /// Dependency on Service3
        /// </summary>
        /// <param name="chainableHandler"></param>
        /// <returns></returns>
        public static HttpMessageHandler InitService2(HttpMessageHandler chainableHandler)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile(appsettingsService2Path, optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();

            var builder = new WebHostBuilder()
                .UseConfiguration(config)
                .UseStartup<Service2.Startup>()
                .ConfigureTestServices(services =>
                {
                    services.AddHttpClient("ThirdService").ConfigurePrimaryHttpMessageHandler(_ => chainableHandler);
                });

            var server = new TestServer(builder);
            return server.CreateHandler();
        }

        /// <summary>
        /// Consumer of all.
        /// </summary>
        /// <param name="secondServiceHandler"></param>
        /// <returns></returns>
        public static HttpClient InitTestHarness(HttpMessageHandler secondServiceHandler)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile(appsettingsService1Path, optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();

            var builder = new WebHostBuilder()
                .UseConfiguration(config)
                .UseStartup<Service1.Startup>()
                .ConfigureTestServices(services =>
                {
                    services.AddHttpClient("SecondService").ConfigurePrimaryHttpMessageHandler(_ => secondServiceHandler);
                });

            var server =  new TestServer(builder);
            var client = server.CreateClient();
            return client;
        }
```

This was then called in the setup area for the tests.

Hope that is useful for any others that need to do something similar.
