### ISSUE TITLE
Can I use Azure SignalR Service when my app is hosted in AWS?

### ISSUE THREAD

**Issue by udlose** [dotnet/aspnetcore#21023]
I have a ASP.NET Core 3.1 REST API with SignalR (in the same app).  I am concerned about scalability since WebSocket connections are persistent and not ephemeral like HTTP Client connections.  My entire application is hosted in AWS ECS via FARGATE.  My first concern was to be able to publish to all connected clients when scaled beyond a single server.  I solved this using a Redis Backplane as recommended [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-3.1#redis-backplane).

I now have the concern over some of the disadvantages with using a Redis Backplane instead of Azure SignalR Service - from the documentation it states:

> The Azure SignalR Service advantages noted earlier are disadvantages for the Redis backplane:
> ......
> - A SignalR app must scale out based on number of clients even if few messages are being sent.
> - A SignalR app uses significantly more connection resources than a web app without SignalR.

I'm not sure how AWS will handle the scaling for me (if at all) for SignalR (there is very little documentation on it) so I'd like to investigate the use of [Azure SignalR Service](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-overview).

Given that my entire app is hosted in AWS, I'd like to know if I can use the Azure SignalR Service without having my app hosted in Azure.  In other words, can I only use Azure SignalR Service when my app is hosted in Azure?

**Comment by BrennanConroy** [comment]
> I'd like to know if I can use the Azure SignalR Service without having my app hosted in Azure

It should work fine, it's just that you'll likely have greater latency as your server app can't be hosted close to where the Azure SignalR Service is hosted. Whereas if you're using Azure you can host the App and the Service in the same DataCenter.

**Comment by udlose** [comment]
Ok, I figured there would probably be some latency. Scaling is more important so latency wont be an issue.

I assume then that since I currently have my .NET Core API and SignalR together, I'd need to separate them and place the SignalR piece in Azure SignalR service. How do I have the API communicate with the SignalR app now that they're separate?

**Comment by BrennanConroy** [comment]
I'm not really sure what you mean. You can add the Azure SignalR Service to your app. Here's the docs: https://docs.microsoft.com/azure/azure-signalr/signalr-quickstart-dotnet-core#add-azure-signalr-to-the-web-app

**Comment by udlose** [comment]
> I'm not really sure what you mean. You can add the Azure SignalR Service to your app. Here's the docs: https://docs.microsoft.com/azure/azure-signalr/signalr-quickstart-dotnet-core#add-azure-signalr-to-the-web-app

I think I understand how to configure the app to use Azure SignalR from adding the nuget and making the suggested code changes.  But don't I need to actually *host* at least the SignalR piece in Azure itself?

**Comment by BrennanConroy** [comment]
>  But don't I need to actually _host_ at least the SignalR piece in Azure itself?

No, I thought this was your original question. "Can I use Azure SignalR Service when my app isn't in Azure?"

As long as your app is configured correctly and can access the Azure SignalR Service endpoint then you can host it anywhere.

**Comment by udlose** [comment]
> > But don't I need to actually _host_ at least the SignalR piece in Azure itself?
> 
> No, I thought this was your original question. "Can I use Azure SignalR Service when my app isn't in Azure?"

You are correct - that was my original question.  Thank you for your patience :)

> 
> As long as your app is configured correctly and can access the Azure SignalR Service endpoint then you can host it anywhere.

I thought that at least something would have to be hosted in Azure.  My concern is about scaling properly and not causing port exhaustion.  Here is my setup:

- I have a single .NET Core 3.1.3 app serving as an API (no UI)
- It runs in an AWS FARGATE instance
- I added SignalR to my app via the following code (originally used `StackExchangeRedis` but will change it to `AddAzureSignalR` since I don't want to handle the scaling issue myself - i.e. [Redis alone can't do that](https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-3.1#tcp-connection-resources))

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR(hubOptions =>
                {
                    hubOptions.EnableDetailedErrors = Environment.IsLocal() || Environment.IsDevelopment();
                })
                .AddMessagePackProtocol()
                .AddAzureSignalR("my Azure Options/Connection string");

and

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<FeatureFlagsHub>("/hubs/feature-flags");
            });




Since all of the documentation on the QuickStart link you provided assumes your app is hosted in Azure, and mine will not be, what configuration is necessary in:

1. My app (is what I have sufficient above)
2. Azure itself

**Comment by BrennanConroy** [comment]
It looks like you have everything configured correctly. The only thing required to be in Azure is the SignalR Service itself. You should be able to run your app locally and see that it connects to the SignalR Service and your clients when connecting to the app will be redirected to the SignalR Service.
