### ISSUE TITLE
TagHelper hover does not work on LiveShare guests

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21029]
1. Download latest VSMaster
2. Check the "Enable LSP Powered Razor Editor" preview feature checkbox
3. Create or open a new Blazor project.
4. In Index.razor write `<Counter></Counter>`
5. Start a LiveShare session
6. Open a second Visual Studio and join that LiveShare session by going File ->Join LiveShare Session
7. On the guest try hovering over `<Counter>` and see that you don't get appropriate tooltips.

Left Host, Right Guest
![image](https://i.imgur.com/L2NqhPx.gif)

**Comment by ryanbrandenburg** [comment]
I poked at this for a while, talked with some folks and it seems this might be an issue with LiveShare rather than our code. We came to this conclusion because HoverHandler.cs is hit but RazorHoverEndpoint.cs is not. LiveShare should be asking both of those for results. They're going to look into it tomorrow, but for now I'm just going to mark this "blocked" and "external".

**Comment by ryanbrandenburg** [comment]
Possibly related "Fun Fact"^TM^: The guest can get HTML hovers that the host does not get. @NTaylorMullen is that expected.

**Comment by NTaylorMullen** [comment]
> The guest can get HTML hovers that the host does not get.

Are you saying that if you hover over something on the host nothing comes through where if you hover over something on the guest you get HTML info?

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen yeah, that's the case.

**Comment by ryanbrandenburg** [comment]
I poked at this a bit, it's the same cause. The Host is hitting RazorHoverEndpoint, but not HoverHandler, while the Guest does the opposite. But in this case the "real" data is on HoverHandler instead of RazorHoverEndpoint, so the guest is the lucky one to get results.

**Comment by ryanbrandenburg** [comment]
Annnd now the HTML part doesn't reproduce anymore.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg this works now right?

**Comment by ryanbrandenburg** [comment]
Yep, all good now.
