### ISSUE TITLE
[Epic] SignalR .NET Client should work well on Blazor WASM

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#21024]
We want to ensure the SignalR .NET Client works well on Blazor WASM. Initial testing shows that it does, but this is tracking additional follow-up work

* [x] https://github.com/dotnet/aspnetcore/issues/18697 Blazor (WASM) SignalR AccessTokenProvider issue (3.2.0-preview1)
* [x] Investigate functional testing for Blazor WASM environments.

**Comment by limefrogyank** [comment]
Have you tested authentication yet?  I can't seem to get the client to send the token using the `.WithUrl(uri, options)` overload where you set the `AccessTokenProvider`.  The server only sees the id query parameter in the websocket request.

**Comment by anurse** [comment]
@limefrogyank Yep, as you noted that's been identified and should be fixed in the 3.1.4 patch! But thanks for noting that specifically, I'd expect you're not the only one encountering that issue :).
