### ISSUE TITLE
Azure AD cannot disable challenge

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/aspnetcore#21027]
I am using Azure AD with a SPA, using the implicit grant flow, to get a bearer token from MSAL, then use it when making calls to my own dotnetcore 3 web api.
When a user tries to call an API that he doesn't have access to, the access denied is transformed into a redirect request

 http://localhost:5000/AzureAD/Account/AccessDenied?ReturnUrl=%2Fapi%2Ftenant%2Fall  

How do I disable that automatic challenge? I just want the API to return 403 Forbidden when an uanuathorized request is made - with a SPA, it makes no sense to redirect to some non existent Account page. 

I don't even understand what middlewhere even thinks there is an account page.

Services are configured as follows:

```
 services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            var azureAdOptions = new AzureADOptions();
            Configuration.Bind("AzureAd", azureAdOptions);
            services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options))
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

            services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options =>
            {
                options.Authority += "/v2.0";
                options.TokenValidationParameters.ValidateIssuer = true;
                options.TokenValidationParameters.ValidIssuers = new[]
                {
                    $"https://sts.windows.net/{azureAdOptions.TenantId}/"
                };
                // The web API accepts as audiences both the Client ID (options.Audience) and api://{ClientID}.
                options.TokenValidationParameters.ValidAudiences = new[]
                {
                    "api://chronosdev",
                    options.Audience,
                    $"api://{options.Audience}"
                };
            });

            services.AddAuthorization(options =>
            {
                var defaultPolicyBuilder = new AuthorizationPolicyBuilder(AzureADDefaults.BearerAuthenticationScheme, AzureADDefaults.AuthenticationScheme);
                defaultPolicyBuilder.RequireAuthenticatedUser();
                options.DefaultPolicy = defaultPolicyBuilder.Build();
            });

```

The Http pipeline is configured like this:

```
        /// <summary>
        /// Called by runtime to configure HTTP pipeline
        /// </summary>
        /// <param name="app">Application builder</param>
        /// <param name="env">Environment</param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app
                .UseStaticFiles()
                .UseHttpsRedirection()
                .UseFileServer()
                .UseRequestDecompression()
                .UseRouting()
                .UseCors(CorsPolicyName)
                .UseAuthentication()
                .UseAuthorization()
                .UseResponseCompression()
                .UseSwagger(c =>
                    c.PreSerializeFilters.Add((swagger, httpReq) =>
                    {
                        swagger.Servers = new List<OpenApiServer> { new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}" } };
                    }))
                .UseSwaggerUI(ConfigureSwaggerUI)
                .UseHttpException()
                .UseCheckAccountStatus()
                .UseEndpoints(endpoints =>
                {
                    endpoints.MapHub<AppHub>("/messages");
                    endpoints.MapControllers();
                });
        }
```
Any pointers? It's really hard to find any up to date examples with an angular SPA, MSAL, Implicit Grant, Azure AD and dotnetcore 3.0 API. 

(BTW I wanted to try to use OpenIDConnect to, but all I really care about is the SPA sending access tokens on all API requests - the OpenIDConnect route kept taking me down other paths. Maybe that isn't the right way to go? Any good examples that show the difference between AzureAD and OpenID RE Angular SPA + MSAL + implicit grant + dotnetcore Web API?)

**Comment by Tratcher** [comment]
`services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)` That should already result in 401s or 403s when the client is not authenticated. How do you have Authorize set up on your controllers?

**Comment by Tratcher** [comment]
Nevermind, I see the issue:
`var defaultPolicyBuilder = new AuthorizationPolicyBuilder(AzureADDefaults.BearerAuthenticationScheme, AzureADDefaults.AuthenticationScheme);`
When authentication fails it will call Challenge on both specified providers, even though these two aren't compatible to challenge at the same time.

API controllers should be marked separately with the AuthorizeAttribute to only use BearerAuthenticationScheme.

**Comment by johnkwaters** [comment]
The base class for my API controllers is marked with just [Authorize], is that sufficient?

```
    [Authorize]
    public class AuthControllerBase : ControllerBase
    {

```
I have some custom authorization attributes too, with custom policies, for instance

```
    [ScopeAuthorize(Scope.System)]
    public class TenantController : RepoController<Tenant, ITenantRepo, TenantInfoDTO,
    TenantInfoDTO, CreateTenantDTO, TenantDTO>
    {

```
And
```

    [FeatureAuthorize(Feature.ViewUsers, Feature.ViewTenants)]
        public override async Task<PagedResultSet<UserDTO>> GetAllAsync(UserSearchDTO request, CancellationToken cancellationToken)
        {
            return await base.GetAllAsync(request, cancellationToken);
        }

```
For these two I inject a Custom Auth Provider

```
    internal class CustomPolicyProvider : IAuthorizationPolicyProvider
    {

```
If I just remove

`AzureADDefaults.AuthenticationScheme`

Will the rest work the same?

**Comment by johnkwaters** [comment]
Update - it does all work as expected when I make your change, which is awesome. Curious as to why I need the commented out line below though
```

            services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                //.AddAzureAD(options => Configuration.Bind("AzureAd", options))
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

```
I get this error without that line:
`
DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'TrailheadChronos.Db.Helpers.SessionCacheHelper' can be invoked with the available services and parameters: Cannot resolve parameter 'Microsoft.Extensions.Caching.Memory.IMemoryCache cache' of constructor 'Void .ctor(Microsoft.Extensions.Caching.Memory.IMemoryCache, TrailheadChronos.Db.Interfaces.IUserRepo, TrailheadChronos.Db.Interfaces.IStaffRepo, TrailheadChronos.Abstractions.Interfaces.IUserContext, TrailheadChronos.Db.Interfaces.ITenantRepo, TrailheadChronos.Db.Interfaces.IRoleReportRepo, Microsoft.AspNetCore.Identity.RoleManager`1[TrailheadChronos.Db.Models.Identity.ApplicationRole], TrailheadChronos.Db.Interfaces.ITenantFeaturesRepo)'.
`
Is that line needed or not for the strict Bearer Token only API controller scenario? I can always inject other things I need that come with it, like IMemoryCache above.

Like I said it's hard to find a good minimal set of code for this setup.

**Comment by johnkwaters** [comment]
Final note - I added 

`services.AddSingleton<IMemoryCache, MemoryCache>();
`

To my DI setup and now I can start without 
`
                .AddAzureAD(options => Configuration.Bind("AzureAd", options))

`
Just

```
            services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

```

**Comment by johnkwaters** [comment]
OK... so add one more wrinkle to this scenario...

I want to user Jwt Bearer authentication, but two different kinds.

For all but one call, I want to use the standard Jwt Bearer token validation. But for ONE specif call, I want to receive an Azure AD idToken in the Auth Bearer {jwt} header.

I try add both like this in Startup:

     ```
       var azureAdOptions = new AzureADOptions();
            Configuration.Bind("AzureAd", azureAdOptions);

            services
                .AddAuthentication(authOptions =>
                    {
                        authOptions.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                        authOptions.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                        authOptions.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                    })
                .AddJwtBearer(
                    JwtBearerDefaults.AuthenticationScheme, options =>
                    {
                        var tokenOptions = Configuration.GetSection("Authentication").Get<TokenOptions>();
                        options.TokenValidationParameters = new TokenValidationParameters
                        {
                            ValidateIssuer = true,
                            ValidateAudience = true,
                            ValidateLifetime = true,
                            ValidateIssuerSigningKey = true,
                            ValidIssuer = tokenOptions.Issuer,
                            ValidAudience = tokenOptions.Audience,
                            IssuerSigningKey = new SymmetricSecurityKey(
                                Encoding.UTF8.GetBytes(tokenOptions.SigningKey))
                        };
                    })
                .AddAzureADBearer(
                    options => Configuration.Bind("AzureAd", options));
            
            services.AddAuthorization(options =>
            {
                options.DefaultPolicy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme, 
                        AzureADDefaults.BearerAuthenticationScheme)
                    .Build();
            });

```
My controller have an [Authorize] attribute, but one specific method I only want to call when the Azure AD idToken is the bearer:

```
        [HttpPost]
        [Route("register")]
        [Authorize(AuthenticationSchemes = AzureADDefaults.BearerAuthenticationScheme)]
        public async Task<TokenResponseDTO> RegisterAsync()
        {
            return new TokenResponseDTO();
        }

```
When testing this. the calls with my regular JWT all work. But the call with the Azure AD token fail with 401 Unauthorized. What am I missing?
