### ISSUE TITLE
Announcement: Package reference changes affecting some Extensions packages

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#21033]
As part of migration of extensions packages from dotnet/extensions to dotnet/runtime, as described in https://github.com/aspnet/Announcements/issues/411, we are also making packaging changes to some of the migrated Extensions packages. To better align with packaging rules in dotnet/runtime, if no API is referenced from a package dependency, it will be removed from the nuget packages. 

Users of the affected packages should add a direct dependency on the removed package dependency in their project if APIs from removed package dependency are used. For example package reference to `Microsoft.Extensions.Configuration` was removed from `Microsoft.Extensions.Configuration.Binder` since no API from the dependency is used in the package. Users of `Microsoft.Extensions.Configuration.Binder` who depend on APIs from `Microsoft.Extensions.Configuration` should add a direct reference to it in their project.

### List of affected packages

- [`Microsoft.Extensions.Configuration.Binder`](https://nuget.org/packages/Microsoft.Extensions.Configuration.Binder)
  Removed reference to `Microsoft.Extensions.Configuration` 
- [`Microsoft.Extensions.Hosting.Abstractions`](https://nuget.org/packages/Microsoft.Extensions.Hosting.Abstractions)
  Removed reference to `Microsoft.Extensions.Logging.Abstractions`
- [`Microsoft.Extensions.Logging`](https://nuget.org/packages/Microsoft.Extensions.Logging)
  Removed reference to `Microsoft.Extensions.Configuration.Binder` 
- [`Microsoft.Extensions.Logging.Console`](https://nuget.org/packages/Microsoft.Extensions.Logging.Console)
  Removed reference to `Microsoft.Extensions.Configuration.Abstractions` 
- [`Microsoft.Extensions.Logging.EventLog`](https://nuget.org/packages/Microsoft.Extensions.Logging.EventLog)
  Removed reference to `System.Diagnostics.EventLog` for the .NET Frameowrk 4.6.1 TFM
- [`Microsoft.Extensions.Options`](https://nuget.org/packages/Microsoft.Extensions.Options)
  Removed reference to `System.ComponentModel.Annotations` 
- [`Microsoft.Extensions.Configuration.Json`](https://nuget.org/packages/Microsoft.Extensions.Configuration.Json), [`Microsoft.Extensions.Logging.EventSource`](https://nuget.org/packages/Microsoft.Extensions.Logging.EventSource)
  Removed reference to `System.Threading.Tasks.Extensions` 

### Version introduced

5.0.0-preview4

### Old behavior

See the list of affected packages for packages references that were removed.

### New behavior

See the list of affected packages for packages references that were removed.

### Reason for change

Packaging policies were updated to better align with dotnet/runtime. Under the new policy, unused package references are removed from nupkgs during packaging.

### Recommended action

Users of the affected packages should add a direct dependency on the removed package dependency in their project if APIs from removed package dependency are used.

### Category

Extensions

**Comment by imsam67** [comment]
In my case, simply referencing the package directly did not work after upgrading my API app from ASP.NET Core 3.1 to .NET 5. For example, I had updated the `Microsoft.Extensions.Configuration` from `3.1.10` to `5.0`. This didn't work and I had to go back to version `3.1.10`. So, now everytime I check to see if there are any NuGet packages I need to upgrade, I see version `5.0` as a suggestion.

What is the right solution to this? Wait or some other solution? Here's a more detailed question I posted on SO.
https://stackoverflow.com/questions/64809716/could-not-load-file-or-assembly-microsoft-extensions-configuration-abstractions
