### ISSUE TITLE
[Blazor] option to load dotnet.wasm from external url

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#21042]
Blazor webassembly on startup now loads dotnet.wasm file from its corn folder _framework/wasm

 I want to have option to direct blazor.webassembly.js from where it should load dotnet.wasm file.

 We can use blazor.boot.json file for that, If developer provides external URL it should be used, if not default path (_framework/wasm/) will remain.

 dotnet.wasm file is static/same minimum within blazor release, so all apps built in this release uses same file.
 dotnet.wasm is about 762kb after compression.

 I want to put it on my cdn and use it in all my apps.

 Motivation:
 (please note that I am using azure storage static website hosting for my apps)
 1. When user visits any of my app dotnet.wasm file will be cached, visiting my another app will load it from cache and app will start faster (because url will be same) and regular payload (about 1.8mb) will be reduced to about 1mb (this is important part).
 2. If I have for example 10 apps I will use only one source for dotnet.wasm file and do not duplicate it 10 times which will save space in my storage (it is not critical but why not).
 3. When I publish apps I will exclude this file because it does not make sense to compress and upload it each time, in result deployment will speed up and I will do less transfer to azure storage (this is not critical too but why not).

 As far as I saw source code for that part of blazor it should not be too hard to implement this option and I hope some devs (like me) will be happy having it.

 Same can be done with dotnet.3.2.0-preview3.20168.1.js file which is compressed 55kb, so in total both will be about 800kb which is not small for blazor.

**Comment by javiercn** [comment]
@Lupusa87 thanks for contacting us.

We've added support for this recently and it will be out soon. See https://github.com/dotnet/aspnetcore/pull/20903 for details
