### ISSUE TITLE
Failed to fetch on launch for wasm project

### ISSUE THREAD

**Issue by PylotLight** [dotnet/aspnetcore#21057]
### Describe the bug
When pressing debug on VS, most of the time, the page appears with:
An unhandled error has occurred. Reload
Basically nearly everytime, a random file/dll will fail to load or fetch.

![image](https://user-images.githubusercontent.com/7006124/79870309-20ac2e00-8426-11ea-9ce4-a418b0a07610.png)
![image](https://user-images.githubusercontent.com/7006124/79870387-41748380-8426-11ea-82ac-169620e567b5.png)
![image](https://user-images.githubusercontent.com/7006124/79870327-26a20f00-8426-11ea-98d4-ffe62ea07538.png)
![image](https://user-images.githubusercontent.com/7006124/79870419-50f3cc80-8426-11ea-9752-940d6a9dc488.png)
Clicking reload always fixes it, and doesn't require a 3rd reload.
My aim is to always have all files loaded on project start.
### To Reproduce

Has occurred on all previews so far, as I use Blazor wasm. So it's been doing this since my first Blazor project.
### Further technical details
- ASP.NET Core version (newest?)
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015095
 Commit:    85c45057dc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19577
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015095\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS updated preview.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you happen to have a way to try this out on a different machine? We suspect there is something wrong with your current environment.

**Comment by PylotLight** [comment]
Interesting.
I synced my project to my work laptop, run debugging like 10 times and didn't get the issue once.
I've used the same browsers in both, both on slow insider builds.
Any idea what in the env could be causing the issue that I can test or change?

**Comment by javiercn** [comment]
@PylotLight it could be some state in your build, have you tried cleaning the bin and obj folders in your project?

You could check that the file is on the right path on disk too

**Comment by PylotLight** [comment]
It happens with new templates as well, so it can't be build related.
Has occurred on all Blazor previews as well. 

It's a different file or files every time, just random files don't load for some reason.

**Comment by pranavkm** [comment]
> Any idea what in the env could be causing the issue that I can test or change?

If you see this in a hosted template, you could turn on debug logging to see why the server is returning a 404.

**Comment by PylotLight** [comment]
Do you mean this logging?
Verbose logs are written to:
C:\Users\USER\AppData\Local\Temp\vscode-edge-debug.txt

It's my main machine, so not sure I want to reinstall Windows on it :P
Not sure what other logging you meant sorry for me to look at.

**Comment by PylotLight** [comment]
Attempted to look into it more.
![image](https://user-images.githubusercontent.com/7006124/80304709-22496d80-87fb-11ea-9ee7-2cc3aefa2397.png)
Not sure what this JS is trying to do, but it's failing for some reason.
![image](https://user-images.githubusercontent.com/7006124/80304717-30978980-87fb-11ea-87e2-c65b37cf260f.png)
