### ISSUE TITLE
GetFileInfo() is called multiple times for the same view path

### ISSUE THREAD

**Issue by majidmadadi** [dotnet/aspnetcore#21052]
I'm trying to write a custom FileProvider using [this tutorial](https://www.mikesdotnetting.com/article/301/loading-asp-net-core-mvc-views-from-a-database-or-other-location), and it works but one problem bothers me. When view engine loads a view from the database to compile it for the first time, the method GetFileInfo() is called two times for the same view path so it causes two round trips to the database thus affecting performance. 

To Reproduce just clone [this repo](https://github.com/mikebrind/RazorEngineViewOptionsFileProviders).

Asp.net core version 3.1
Visual Studio 2019

**Comment by pranavkm** [comment]
@majidmadadi different parts of the view engine pipeline may attempt to check for file existence. For a disk-based file system, it's not evident that this has a impact on performance. If you think it affects a database-backed file system, consider adding caching to your file provider implementation.

**Comment by majidmadadi** [comment]
Ok but I think it's not a good practice to create instances of objects to just check the existence of a unique entity.

**Comment by majidmadadi** [comment]
Thank you for your explanation.
