### ISSUE TITLE
Blazor Wasm 3.2-preview4 CORS problem in OIDC authentication

### ISSUE THREAD

**Issue by mwinkler** [dotnet/aspnetcore#21054]
Our corporate oidc provider does a roundtrip via AD FS (SAML request).
The AD FS server does not support CORS, so the authentication fails with the error 'Network Error'.

![image](https://user-images.githubusercontent.com/1729418/79859123-cf258400-83d0-11ea-8202-4ae32f7aedc5.png)

Is there a way to force the client to do the authentication not using ajax and do a proper redirect?

There is also the usecase, that the user has to provide a 2nd factor for the authentication and those information are not visible when the user is not proper redirected.

My oidc config:

```
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.Authority = "https://xxx/oauth/authorize";
    options.ProviderOptions.ClientId = "xxx";
});
```

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015095
 Commit:    85c45057dc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015095\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@mwinkler thanks for contacting us.

No, there is no way around it. Your provider needs to support CORS in the authorize endpoint if you are using an implicit flow and also in the token endpoint if you are using code.

**Comment by blowdart** [comment]
Given that ADFS is an older ASP.NET hosted under IIS you will be able to use the [IIS CORS module](https://docs.microsoft.com/en-us/iis/extensions/cors-module/cors-module-configuration-reference).

**Comment by javiercn** [comment]
@blowdart thanks! I didn't know that 😄
