### ISSUE TITLE
Blazor component cyclic dependency unchecked

### ISSUE THREAD

**Issue by theswanand** [dotnet/aspnetcore#21050]
### Components in Blazor are allowed to refer each other
Blazor components are allowed to have cyclic dependency without any compile time error or intellisense warning.

### To Reproduce
So I created a new project with BlazorServer. It has three pages as Index, Counter and FetchData. Insert the `<Counter />` component in Index.razor page and `<Index/>` component in Counter.razor page. To my surprise, the project was built successfully but struggling to run on browser.

### Further technical details
- ASP.NET Core version 3.1
- IDE: VS2019

**Comment by javiercn** [comment]
@theswanand thanks for contacting us.

That is by design, that problem is untractable in the general case and we don't try to solve it in the same way a compiler doesn't warn you when you have recursive calls that result in an infinite execution.
