### ISSUE TITLE
Additional SignalR configuration support for Redis

### ISSUE THREAD

**Issue by emilmuller** [dotnet/aspnetcore#21063]
Hi

I'm using SignalR with Redis as a backplane, which means that I'm using `AddStackExchangeRedis(...)` in `ConfigureServices`.

However, I'd also like to use Redis (the same server) for my own personal caching purposes, which means that I am calling `ConnectionMultiplexer.ConnectAsync(...)` elsewhere in my code.

This leads me to believe that SignalR does that as well, and that my app ends up with two instances of `IConnectionMultiplexer`, and probably two connection pools per node.

I would like to avoid this, and it would be nice to either be able to access SignalR's internal `IConnectionMultiplexer`, or to provide one for SignalR.

Kind regards, Emil

**Comment by BrennanConroy** [comment]
You should be able to do this by using the `ConnectionFactory` in the redis options. Where you provide the Connection to SignalR.

An example of the usage for other purposes is [here](https://docs.microsoft.com/aspnet/core/signalr/redis-backplane?view=aspnetcore-3.1#custom-behavior-for-connection-failures)

**Comment by emilmuller** [comment]
@BrennanConroy Ah! Great. I missed that :) Thanks
