### ISSUE TITLE
How to use the Lib Microsoft.AspNetCore.Authentication.Negotiate with ALD or free IPA domain servers?

### ISSUE THREAD

**Issue by megafetis** [dotnet/aspnetcore#21067]
### Is your feature request related to a problem? Please describe.
How to use the Lib Microsoft.AspNetCore.Authentication.Negotiate with other domain servers ALD or free IPA ? Without using Active Directory
Why NegotiateOptions doesnt contains PathToKeytab property?

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by blowdart** [comment]
It doesn't have that option because our main target for this right now is Active Directory.

As for path to keytab, it uses environment variables, 

```
export KRB5_KTNAME=/tmp/mymachine.HTTP.keytab
```

Is there a reason that's not sufficient?

**Comment by megafetis** [comment]
Do you have plans in the to support this features in future  ?
