### ISSUE TITLE
Possible Performance Improvement in Routing

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#21079]
`HttpMethodMetadata` gets an `IEnumerable<string>` to determine the methods for routing. I think the performance could be improved by replacing the http method instances with the ones in `HttpMethods` class.

```csharp
public HttpMethodMetadata(IEnumerable<string> httpMethods, bool acceptCorsPreflight)
{
    ...

    HttpMethods = httpMethods.Select(GetHttpMethodInstance).ToArray();

    ...
}

private static string GetHttpMethodInstance(string httpMethod)
{
    if (AspNetCore.Http.HttpMethods.IsGet(httpMethod))
    {
        return AspNetCore.Http.HttpMethods.Get;
    }

    ...

}
```

**Comment by javiercn** [comment]
@Kahbazi thanks for contacting us.

I'm not sure why that would be the case, it is likely that it doesn't have a perceptible impact in performance. Do you have any data that proves the current results in a measurable performance improvement?

**Comment by Kahbazi** [comment]
sudo bot label remove "Needs: Author Feedback"
sudo bot label add "Needs: Attention 👋"

I always wanted to do this :trollface:

Ok. Basically I'm trying to set all the http methods in routing from the `HttpMethods` static fields so we can leverage `ReferenceEquals` for comparison.
https://github.com/dotnet/aspnetcore/blob/06a85e5db2bb9159beb3b530bdf224a3ec60ad1b/src/Http/Http.Abstractions/src/HttpMethods.cs#L16-L25

I should have also mentioned that the `ReferenceEquals` should be checked first in `HttpMethodMatcherPolicy`. 

**Before**
https://github.com/dotnet/aspnetcore/blob/0517745c08d1bc85009f1ca41a41d77176eeea60/src/Http/Routing/src/Matching/HttpMethodMatcherPolicy.cs#L149
**After**
```csharp
if (!(object.ReferenceEquals(httpMethod, candidateMethod) || StringComparer.OrdinalIgnoreCase.Equals(httpMethod, candidateMethod)))

```

I created a benchmark [here](https://github.com/Kahbazi/HttpMethodMetadataPerfromamce) and this is the result.

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|  After | 1.835 us | 0.0217 us | 0.0182 us |
| Before | 1.930 us | 0.0307 us | 0.0410 us |

**Comment by javiercn** [comment]
@Kahbazi thanks for the details.

@rynowak do you have any thoughts here since you did extensive performance work in this area?

**Comment by rynowak** [comment]
The `ApplyAsync` code path is used in some cases, but generally most code will be going down this code path: https://github.com/Kahbazi/HttpMethodMetadataPerfromamce/blob/master/HttpMethodMetadataPerfromamce/BeforeHttpMethodMatcherPolicy.cs#L440

Basically `ApplyAsync` does a linear search, but its used in some non-mainline cases - basically when Razor Pages or dynamic routing policies are involved. It does a linear search because its meant to handle the cases where we *can't* precompute the data.

The graph-node code path is used in mainline cases where we know everything about the endpoints and can pre-compute the jumps. It would be interesting to see some optimization work done on that. 

I'm not totally against the idea, but so far this just seems like a pretty tricky change to make a micro-optimization. Like it's a little bit surprising that you call the constructor of a class, and as a result you get back a list with different objects in it.

**Comment by Kahbazi** [comment]
I change all http method equals check to be `ReferenceEquals` first. I also changed 
```
internal static readonly string PreflightHttpMethod = "OPTIONS";
```
to 
```
internal static readonly string PreflightHttpMethod = HttpMethods.Options;
```

For the benchmark I've add four different http methods ("Put", "Delete", "Post", "GET") and set `acceptCorsPreflight` to `true`. 

This is the result for when incoming method is GET
| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|  After | 5.805 us | 0.0374 us | 0.0350 us |
| Before | 6.036 us | 0.0792 us | 0.0661 us |

This is the result for when incoming method is OPTIONS
| Method |     Mean |     Error |    StdDev |   Median |
|------- |---------:|----------:|----------:|---------:|
|  After | 6.154 us | 0.0432 us | 0.0383 us | 6.149 us |
| Before | 8.707 us | 0.1709 us | 0.3492 us | 8.543 us |

**Comment by rynowak** [comment]
Did you test the graph-node code path? That's the main code that that gets used. 

It might be simpler to test this using one of our existing benchmarks: https://github.com/dotnet/aspnetcore/blob/master/src/Http/Routing/perf/Matching/MatcherGithubBenchmark.cs

**Comment by Kahbazi** [comment]
Thanks for pointing me to the benchmark. I've run `MatcherGithubBenchmark` once before my changes and once after. Here's my changes https://github.com/Kahbazi/AspNetCore/commit/4dea55751d393dba0aff15cdb1d0deb234b3573da and here are the result.

**Before :**

   Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |
--------- |---------:|----------:|----------:|-------:|---------:|
 Baseline | 384.2 ns |  7.015 ns |  6.562 ns |   1.00 |     0.00 |
 Dfa | 701.4 ns | 16.787 ns | 14.882 ns |   1.83 |     0.05 |

**After :**

   Method |     Mean |     Error |    StdDev | Scaled | ScaledSD |
--------- |---------:|----------:|----------:|-------:|---------:|
 Baseline | 383.6 ns |  4.553 ns |  4.259 ns |   1.00 |     0.00 |
 Dfa | 687.9 ns | 12.508 ns | 11.088 ns |   1.79 |     0.03 |

**Comment by rynowak** [comment]
That's pretty good then. Feel free to turn this into a PR 👍
