### ISSUE TITLE
ASP.NET (not Core) WebAPI in an SDK-based csproj - possible?

### ISSUE THREAD

**Issue by bzaar** [dotnet/aspnetcore#21077]
### Describe the bug
After switching to the "SDK-based" csproj format, my ASP.NET WebAPI app got into a weird state: when trying to run it in Visual Studio 2019, the IDE says:

 * (when using Sdk="Microsoft.NET.Sdk.Web") "Unable to run your project. The "RunCommand" property is not defined." or 
* (when using Sdk="Microsoft.NET.Sdk") "The project doesn't know how to run the profile IIS Express."

However, when running the project *in Rider, it does work* (serves requests as expected) but after each request I get the following messages in the console:

> Worker process has been started: 34284
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Code\Morpher.WebService.V3\Morpher.WebApi\bin\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\Code\Morpher.WebService.V3\Morpher.WebApi\bin\Morpher.WebService.V3.runtimeconfig.json file specifying the appropriate framework.
Worker process has been started: 21224
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Code\Morpher.WebService.V3\Morpher.WebApi\bin\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the C:\Code\Morpher.WebService.V3\Morpher.WebApi\bin\Morpher.WebService.V3.runtimeconfig.json file specifying the appropriate framework.

I.e. the worker process restarts twice per each request. Not ideal.

How do I get it to run without restarting and preferably from Visual Studio?

### To Reproduce

The changes I made to switch to the new csproj format are summarised in [this PR](https://github.com/morpher-ru/Morpher.WebService.V3/pull/64). Just open the branch in Rider and hit Ctrl-F5.

### Further technical details
- ASP.NET version: "Microsoft.AspNet.Mvc" Version="5.2.3"
- Visual Studio 2019 16.5.1
- Rider 2020.1.0
- Windows 10

**Comment by javiercn** [comment]
@bzaar thanks for contacting us.

This is not possible, sdk-based projects are not suited for traditional aspnet/webapi projects and it is likely you'll see a long trail of issues if you try to use them.
