### ISSUE TITLE
Razor TextMate colorization is lost following multiple statement blocks

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21071]
![image](https://user-images.githubusercontent.com/2008729/79912006-33971200-83d6-11ea-9e63-3d5d900ceb73.png)

**Comment by TanayParikh** [comment]
This test case can be simplified to:

```
<ul>

@if (true)
{
    <self_closing />
}

@if (true)
{

}
```

Where `<self_closing />` is any self closing tag.

![image](https://user-images.githubusercontent.com/14852843/80046647-0d4da100-84c0-11ea-8dd1-12e7bc1a4f60.png)

**Comment by ryanbrandenburg** [comment]
![image](https://user-images.githubusercontent.com/14987221/96312876-5e4ad780-0fc1-11eb-86a6-ac1f8d11d8c6.png)
Seems that this still happens to a lesser degree, the last @ here isn't  getting caught.

**Comment by ryanbrandenburg** [comment]
Does anyone remember if this was VS or VSCode? It doesn't have the label :(

**Comment by ryanbrandenburg** [comment]
Seems this was resolved either way:
VS
![image](https://user-images.githubusercontent.com/14987221/98400569-172c9100-2019-11eb-9659-f5c59f08850e.png)
VSCode
![image](https://user-images.githubusercontent.com/14987221/98400745-71c5ed00-2019-11eb-8060-860293e9b619.png)
