### ISSUE TITLE
Environment.MachineName returns "emscripten"

### ISSUE THREAD

**Issue by LukeTOBrien** [dotnet/aspnetcore#21086]
Hi there,

I am experimenting with porting some existing WinForms app to the web using Blazor, we have some business logic that retrieves the configuration settings for a given machine name.  
It seems in Web Assembly `System.Environment.MachineName` return "emscripten".  
The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.environment.machinename) for MachineName say:
> Gets the NetBIOS name of this local computer.

So "emscripten" is incorrect, I can understand that being returned as that may well be the [compiler name](https://emscripten.org/).  
Any chance of of correcting this and returning the actual machine name?

Thanks.

**Comment by alexwiese** [comment]
What would you expect it to return?

The server hostname when running on the server? The client hostname when running on the client? 

The machine name isn’t available on the client due to security/sand boxing.

**Comment by javiercn** [comment]
@LukeTOBrien thanks for contacting us.

This is not a blazor specific issue, but a mono issue. You'll get a better and faster answer if you file the issue directly in the [mono](https://github.com/mono/mono) repository since this is set by the runtime and Blazor doesn't have any control over it.

**Comment by LukeTOBrien** [comment]
Okay, thank you - Yes on the server I would expect the server machineName and on client the client machineName - But if it is not possible due to sandboxing then that answers my question.
