### ISSUE TITLE
ASP.NET Status codes include the status's description, but ASP.NET Core doesn't?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#21084]
When you head over to networking in any modern browser, and do a request with ASP.NET Core, the **Status Code** entry will only have the status code number printed, where as if you do the same thing on a ASP.NET application, you will see the status code + what it means.

For example, in ASP.NET Core you'd see the following: 200, 401, 301
In ASP.NET though, you'd see this: 200 OK, 401 Unauthorized, 301 Moved Permanently.

Is this a bug, if not, how can I make it mimic what ASP.NET is doing?

EDIT: Perhaps its the browser at fault?

When browsing Microsoft dev blogs, every request seems to print only the status code, but when you hit Microsoft's identity server, it prints the proper 200 OK status response.

**Comment by javiercn** [comment]
@SpiritBob thanks for contacting us.

This is likely a difference between HTTP/1.1 and HTTP/2. Status description messages are deprecated in HTTP/2 I believe.

I'll let more knowledgeable folks answer it.

**Comment by Tratcher** [comment]
Indeed, this is likely the difference between HTTP/1.x and HTTP/2. If you right click on the column headers you'll see protocol as an option. 
You can also try this with http vs https sites, since HTTP/2 needs https by default.

**Comment by SpiritBob** [comment]
Thank you for clearing that up, closing this issue as it's resolved.
