### ISSUE TITLE
BlazorLinkOnBuild has been renamed to BlazorWebAssemblyEnableLinking

### ISSUE THREAD

**Issue by huto1** [dotnet/aspnetcore#21092]
I get this error after updating one of my older projects. Now, if I go deeper, it will say I need to update my project files. Unfortunately, I cannot find anything similar to this. Does anyone know the location?Or maybe this is not fixable at all.

**BlazorLinkOnBuild has been renamed to BlazorWebAssemblyEnableLinking**

**Comment by javiercn** [comment]
@huto1 thanks for contacting us.

Check your csproj files, there will be a property `BlazorLinkOnBuild` on one of them

**Comment by huto1** [comment]
There are two files and this is what they contain. I've gone through all of them, I think. Or maybe there is some hidden csproj file, somewhere? 

> <?xml version="1.0" encoding="utf-8"?>
> <Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
>   <PropertyGroup>
>     <ActiveDebugProfile>IIS Express</ActiveDebugProfile>
>     <NameOfLastUsedPublishProfile>Default Settings</NameOfLastUsedPublishProfile>
>   </PropertyGroup>
> </Project>


> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>netstandard2.1</TargetFramework>
>     <OutputType>Exe</OutputType>
>     <LangVersion>7.3</LangVersion>
>     <RazorLangVersion>3.0</RazorLangVersion>
>   </PropertyGroup>
>   
>   <ItemGroup>
>     <PackageReference Include="BlazorInsights" Version="0.1.0" />
>     <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview9.19424.4" />
>     <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview9.19424.4" PrivateAssets="all" />
>     <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview3.20168.3" />
>     <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview9.19424.4" PrivateAssets="all" />
>     <PackageReference Include="Microsoft.AspNetCore.Components" Version="5.0.0-preview.2.20167.3" />
>     <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0-preview4.20210.8" />
>     <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0-preview4.20210.8" />
>   </ItemGroup>
> 
> </Project>

**Comment by pranavkm** [comment]
`Microsoft.AspNetCore.Blazor.*` have been renamed using it with the 3.2-preview4 packages wouldn't make sense. Please follow the instructions in https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/ to figure out how to upgrade your projects.  In addition, we wouldn't recommend referencing a 5.0 versioned `Microsoft.AspNetCore.Components` package in a 3.2 application.

**Comment by huto1** [comment]
@pranavkm Thank you. It seems that what was Blazor is now WebAssembly, except for Microsoft.AspNetCore.Blazor.HttpClient and the error I received was utterly wrong. Once I changed these packages, it worked.
