### ISSUE TITLE
Disable brotli precompression for Blazor WASM apps

### ISSUE THREAD

**Issue by henkmollema** [dotnet/aspnetcore#21094]
Is there a way to disable brotli precompression for Blazor WebAssembly (added in 3.2.0 Preview 4) apps or force it to use the gzipped files? 

We're currently hitting [a bug in Google Cloud](https://issuetracker.google.com/issues/147185337) which removes the `content-type: br` header from the response even though the client says it accepts brotli. This causes the browser to not understand the brotli compressed response. Gzip compression works fine.

**Comment by javiercn** [comment]
@henkmollema thanks for contacting us.

We don't have a way out of the box to disable just broli pre-compression, only full compression or no compression. What you can do, is remove the *.br files from disk after they are published

**Comment by henkmollema** [comment]
Thanks. I've added the following to my Dockerfile to remove the .br files:

```dockerfile
RUN rm -rf wwwroot/**/**/*.br && rm -rf wwwroot/**/*.br
```

**Comment by javiercn** [comment]
That sounds good.

Closing since it's been answered

**Comment by vchirikov** [comment]
Hm, looks like github pages doesn't support br too.
