### ISSUE TITLE
Consider a finalizer for HubConnection

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#21106]
If a HubConnection is not diposed, some resources (such as timers) will remain rooted (I think, right @BrennanConroy?). As long as the user calls `DisposeAsync`, this isn't a problem, but it can be easy to forget. Having a finalizer might help here. The finalizer could do the clean-up, or produce some kind of warning indicating it was not disposed.

@BrennanConroy, can you confirm a finalizer would even work here? If there are rooted objects, would the HubConnection actually be finalized? (Or is the HubConnection not directly being rooted?)

**Comment by BrennanConroy** [comment]
We did fix a timer rooting the HubConnection, so this might not be needed anymore. We'll need to try it out.

**Comment by anurse** [comment]
So still non-zero work :). We can track that here then.

**Comment by BrennanConroy** [comment]
> If there are rooted objects, would the HubConnection actually be finalized?

This is the issue. The HubConnection roots itself, we removed one example of this with the Timer change. However it looks like the ReceiveLoop itself is rooting the connection. In theory we could make the loop a static function and have a weak reference to the HubConnection and only grab the reference when needed. But that sounds like a lot of work for something with very little benefit.

**Comment by mkArtakMSFT** [comment]
@BrennanConroy what's the state of this issue? When is this expected to land?
