### ISSUE TITLE
[SignalR] Identify a suitable MessagePack library for the Java client to use

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#21107]
Epic https://github.com/dotnet/aspnetcore/issues/21022

Before we can actually implement the MessagePack Hub Protocol in the Java Client, we need to identify a suitable MessagePack library. Some of our requirements:

* Open-Source with permissive license.
* Must be relatively well-adopted.
* Must support the necessary data types described in [Hub Protocol](https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/docs/specs/HubProtocol.md#messagepack-msgpack-encoding) (we don't use anything funky so this should be straightforward)
* Ideally, it should support a "reader/writer" style API (like [Utf8JsonWriter](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter?view=netcore-3.1) and [Utf8JsonReader](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader?view=netcore-3.1)), a serialization API (like [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=netcore-3.1)) **and** support interop (i.e. be able to inject a serialized object into the output while using the writer API, and vice-versa for reading). This allows us higher performance without compromising user flexibility, and allows the user to configure the serializer without messing with the SignalR framing.

**Comment by wtgodbe** [comment]
The official Java implementation looks promising: https://github.com/msgpack/msgpack-java

- License is Apache 2.0
- [Core class](https://www.javadoc.io/doc/org.msgpack/msgpack-core/latest/org/msgpack/core/MessagePack.html) provides an API for deserializing objects from binary, [MessageUnpacker](https://www.javadoc.io/static/org.msgpack/msgpack-core/0.8.20/org/msgpack/core/MessageUnpacker.html)
- [Core class](https://www.javadoc.io/doc/org.msgpack/msgpack-core/latest/org/msgpack/core/MessagePack.html) provides an API for serializing objects from binary, [MessageBufferPacker](https://www.javadoc.io/static/org.msgpack/msgpack-core/0.8.20/org/msgpack/core/MessageBufferPacker.html) and [MessagePacker](https://www.javadoc.io/static/org.msgpack/msgpack-core/0.8.20/org/msgpack/core/MessagePacker.html)
- MessagePacker writes to a [MessageBufferOutput](https://www.javadoc.io/static/org.msgpack/msgpack-core/0.8.20/org/msgpack/core/buffer/MessageBufferOutput.html), implementing classes of which can write to an Array, Channel or OutputStream (pre-existing types from java.io)
- MessageUnpackager reads from [MessageBufferInput](https://www.javadoc.io/static/org.msgpack/msgpack-core/0.8.20/org/msgpack/core/buffer/MessageBufferInput.html), which has similar properties to MessageBufferOutput

Interop therefore seems baked in. It doesn't appear to have a static serializer like JsonSerializer, though. Still poking around.

**Comment by BrennanConroy** [comment]
Should be good to go, found a library
