### ISSUE TITLE
Is there a more elegant way to handle reset/cancel with Blazor EditForm?

### ISSUE THREAD

**Issue by charleskessler** [dotnet/aspnetcore#21110]
EditForm automatically updates the bound object which works great when creating a brand new model instance -- nice and tidy, and very efficient.

However, things get sticky when using EditForm to edit existing model instances. 

If I want to give the user the option to back-out of the edit mode -- click Cancel for instance -- I have to implement my component as such:
![image](https://user-images.githubusercontent.com/6663095/80024717-7ed02400-84ad-11ea-85e1-3568a40114b9.png)

Where I store a temp copy of the model (line 21 -- generated by MemberwiseClone), and when the Cancel button is clicked I restore the values of the original model using the temp copy (line 25-30)

This works well enough, but when dealing with dozens of models each with dozens of fields it gets to be a bit of a mess. I know I can use a library such as AutoMapper to make that task much easier, but it still feels very hacky to me.

Is there a more elegant solution to this problem?

**Comment by javiercn** [comment]
@charleskessler thanks for contacting us.

You are looking for undo functionality I think, and we don't have support for it out of the box. This is something you would need to build yourself.
