### ISSUE TITLE
HTML Completions Not Available in .Razor Files

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#21115]
As reported by @ToddGrun HTML completions aren't showing up in `.razor` files. Needs to be investigated / resolved P0.

**Comment by TanayParikh** [comment]
@NTaylorMullen here's the issue :)

**Comment by TanayParikh** [comment]
@NTaylorMullen filed: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109023

**Comment by NTaylorMullen** [comment]
Super nasty workaround here: https://github.com/dotnet/aspnetcore-tooling/pull/1817
The "undo" of this workaround is tracked here: dotnet/aspnetcore#21126
