### ISSUE TITLE
Windows Authentication not working with WPF Client and  SignalR - dotnetcore 3.1

### ISSUE THREAD

**Issue by dgroh** [dotnet/aspnetcore#21111]
### Describe the bug
I have an WPF Application which connects successfully to a SignalR Hub on a local IISExpress.
The WPF runs on client machine with active directory. 

In my WPF client I have the follwong code:

```csharp
_connection = new HubConnectionBuilder()
    .WithUrl('https://localhost:5001/signalR', opts =>
    {
        opts.UseDefaultCredentials = true;
    })
    .Build();
``` 

In my Api which has my Hub, I have added the implementation for `IUserIdProvider`

```csharp
public class NameUserIdProvider : IUserIdProvider
{
    public string GetUserId(HubConnectionContext connection)
    {
        return connection.User?.Identity?.Name;
    }
}
```

Unfortunately this line -> `connection.User?.Identity?.Name;` returns **null**.

That's how my **Startup.cs** is configured:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddLogging();

    services.AddAuthentication(IISDefaults.AuthenticationScheme);

    services.AddSingleton<IUserIdProvider, NameUserIdProvider>();

    services.AddSignalR(hubOptions =>
    {
        hubOptions.EnableDetailedErrors = true;
    });

    services.AddScoped<IBuildsService, BuildsService>();

}

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseHttpsRedirection();

        app.UseRouting();

        app.UseAuthentication();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapHub<SyncCodeHub>("/signalr");
        });
    }
```

### To Reproduce
1. Create a WPF Client .netcore 3.1
2. Create a API with .netcore 3.1 and as package SignalR Client 3.1.3
3. The API should receive the WPF user credentials when connected

### Further technical details
- ASP.NET Core version: **3.1**
- dotnet --info:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26
``` 

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

```
Microsoft Visual Studio Enterprise 2019
Version 16.5.1
VisualStudio.16.Release/16.5.1+29920.165
Microsoft .NET Framework
Version 4.8.03752
```

**Comment by BrennanConroy** [comment]
Have you setup windows auth for IIS Express? https://docs.microsoft.com/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio

**Comment by dgroh** [comment]
@BrennanConroy I had followed this link and the documentation is suggestive that by only adding `IISDefaults.AuthenticationScheme` should be enough also for IIS Express. That is why I was confused.

Then I just double checked that for **Debugger** -> IIS Express the `launchSettings.json` also had to be updated. So after updating `launchSettings.json` it has worked.
