### ISSUE TITLE
Allow custom handling of authorization failures (different status codes and/or messages depending on authorization requirement failure)

### ISSUE THREAD

**Issue by TheName** [dotnet/aspnetcore#21116]
Examples:
1. I'd like to return a 404 if the authorization handler cannot authorize a request because the resource is missing
1. I'd like to add a custom message to forbidden status code result if the authorization failure is specific to some requirement

Proposed solution:
1. The `PolicyAuthorizationResult` could include `AuthorizationFailure` from the authorization result - set in the `PolicyEvaluator`
1. `AuthorizationMiddleware` would take action (continue the pipeline or not) based on a result from a new service. That new service would in turn handle challenge and forbid actions. That new service could be names something like `IAuthorizationMiddlewareResultEvaluator`
1. The new service (i.e. named `IAuthorizationMiddlewareResultEvaluator`) could be decorated and this would create a possibility for custom evaluators which could take custom actions based on the specific `AuthorizationFailure` (i.e. if specific `IAuthorizationRequirement` has failed)

**Comment by TheName** [comment]
I'm not sure if this would help with open documentation issue -> https://github.com/dotnet/AspNetCore.Docs/issues/16751 - parented by https://github.com/dotnet/AspNetCore.Docs/issues/16191 - but I thought it's related and thus worth mentioning here

**Comment by anurse** [comment]
Triage: We likely can't prioritize building this ourselves in 5.0, but thanks for the PR! We'll take a look and if we can get it to good we can merge it and get the feature in early!

**Comment by TheName** [comment]
Happy to help :) 
If for whatever reason these code changes don't follow your plans - don't hesitate to reject the PR, but I'd be grateful for an explanation in such a case :) 

A bit on the side: is it at all possible to release it earlier than 5.0? like 3.2? or there are no such plans and the earliest possible release is 5.0?

**Comment by anurse** [comment]
5.0 is the next release. See the [.NET Core Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) for more details on timelines.

**Comment by HaoK** [comment]
Reopening for use in api-review

**Comment by HaoK** [comment]
@dotnet/aspnet-api-review can we review this at the next API meeting?

**Comment by HaoK** [comment]
Will close once I update the sample removing the decorator stuff

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/25503
