### ISSUE TITLE
Auth config formatting in Blazor WebAssembly projects 

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#21124]
If you create a Blazor WebAssembly app with authentication enabled, the config files have a couple of minor formatting issues

*appsettings.json* has an extra trailing comma in some cases:

```json
{
  "Local": {
    "Authority": "https:login.microsoftonline.com/",
    "ClientId": "33333333-3333-3333-33333333333333333"
  },
}
```

*appsettings.Development.json* is indented an extra space (tree spaces instead of two):

```json
{
   "Local": {
     "Authority": "https:login.microsoftonline.com/",
     "ClientId": "33333333-3333-3333-33333333333333333"
   }
}
```
```

```

**Comment by danroth27** [comment]
Perhaps we should also use a different section name than "Local" for the standalone Blazor app with individual user accounts case? I'm not really sure what local is referring to in this context. Would "Authentication" or "OIDC" be better?

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/21139. @danroth27 do you feel strongly about the `Local` name? Seems like low value.

**Comment by danroth27** [comment]
> do you feel strongly about the Local name?

@pranavkm I'll open a new issue. I think the problem is broader than just the property name in config. The UX experience for standalone Blazor WebAssembly + auth is a bit wonky right now. It confuses using local identities with ASP.NET Core Identity and using a remote third-party identity provider.
