### ISSUE TITLE
[SignalR] Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

### ISSUE THREAD

**Issue by amitvig22** [dotnet/aspnetcore#21122]
### Describe the bug
I have a scenario where my SignalR server and Client cannot run within the same origin because we would like to share the SignalR server for more than one origin. When i run the server locally and spin up an instance of a web based signalR client running within typescript i can connect and everything works. When i move my server to Azure and use the same locally running signalR client to connect to the server i get preflight request does'nt pass access control check. There are no CORs settings in the Azure app service. All the Cors settings are done in the server code. Code below.

The error i get in the browser is : Access to XMLHttpRequest at 'https://******.azurewebsites.net/chatHub/negotiate?negotiateVersion=1' from origin 'https://localhost:44392' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request. This works as expected locally but ends up not working correctly when running in Azure and connecting from a local client.
### To Reproduce

``` Startup.cs
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options => options.AddPolicy("MyCorsPolicy", builder =>
            {
                builder
                  .AllowAnyHeader()
                  .WithOrigins("https://localhost:44392/")
                  .SetIsOriginAllowed(origin =>
                  {
                      if (string.IsNullOrWhiteSpace(origin))
                          return false;

                      if (origin.ToLower().StartsWith("https://localhost"))
                          return true;
                      return false;
                  })
                  .AllowAnyMethod()
                  .AllowCredentials();
            }));
            ... //Authentication etc
            services.AddSignalR(hubOptions =>
            {
                hubOptions.EnableDetailedErrors = true;
            }).AddJsonProtocol();
        }

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseCors("MyCorsPolicy");
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseHttpsRedirection();
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Ping!");
                });
                endpoints.MapHub<ChatHub>("/chatHub");
            });
         }
```
In the typescript client i make the request as follows : 
```
const connection = new HubConnectionBuilder()
        .withUrl("https://******.azurewebsites.net/chatHub" , { accessTokenFactory: () => "TOKEN GOES HERE"})
        .configureLogging(LogLevel.Information)
        .build();
```

### Further technical details
- ASP.NET Core version - 3.1, SignalR version - @microsoft/signalR - 3.1.3
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - locally visual studio 2019, in Azure - Azure app service.

**Comment by BrennanConroy** [comment]
Can you look at the network tab in the browser and figure out where you're attempting to be redirected to?

**Comment by amitvig22** [comment]
> Can you look at the network tab in the browser and figure out where you're attempting to be redirected to?

Here is the request error on the console.
<img width="1898" alt="1" src="https://user-images.githubusercontent.com/1823977/80045705-21dc6a00-84bd-11ea-8c23-fec67cc7f3d2.png">
Here is where the snapshot of the network tab.
<img width="1919" alt="2" src="https://user-images.githubusercontent.com/1823977/80045712-2739b480-84bd-11ea-9aef-1ff7597d3a6b.png">

**Comment by BrennanConroy** [comment]
Can you gather debug logs from the server: https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging
And if possible provide a network trace: https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#network-traces

**Comment by amitvig22** [comment]
[server side logs.txt](https://github.com/dotnet/aspnetcore/files/4524334/server.side.logs.txt)


[network trace.txt](https://github.com/dotnet/aspnetcore/files/4524338/network.trace.txt)

**Comment by amitvig22** [comment]
Marking this issue as closed. This was tricky because it worked locally but did not work in Azure. After going over the application logs and network traces @BrennanConroy noticed something related to auth was causing a redirect. I set up authentication within Azure and since that is the first thing that runs, CORS from within the app doesn't get a chance to run. The way to handle this is to use CORS within Azure but as per documentation CORS within the App service is not supported for SignalR, one should note Authentication within Azure app service will result in issues with CORS.
