### ISSUE TITLE
Hosted Blazor WebAssembly apps with authentication enabled have config files that aren't used

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#21125]
Repro steps:

- Create an ASP.NET Core hosted Blazor WebAssembly project with authentication enabled using individual user accounts

Actual result:

- The Client project has both an *appsetting.json* file and an *appsettings.Development.json* file with a configured authority and client ID.

Expected result:

- The config files don't appear to be used, so it seems like they shouldn't be generated at all.

**Comment by javiercn** [comment]
Yep,

That's a bug.

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/21139
