### ISSUE TITLE
(VS) C# Pull Based Diagnostics

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#21121]
Repro:
1. `dotnet new blazorserver`
2. Open `Counter.razor`. Delete file contents. Save.
3. Paste in:
```

@NavMenuCssClass

@(NavMenuCssClass)

```
4. Save file.

Expected:
Red error squiggly under `NavMenuCssClass` as it doesn't exist.

Actual:
![Error Squigly](https://user-images.githubusercontent.com/14852843/80042218-492e3980-84b3-11ea-9a37-a14504ecad2c.gif)

**Comment by TanayParikh** [comment]
FYI: @NTaylorMullen. Is this dup of anything?

**Comment by NTaylorMullen** [comment]
> FYI: @NTaylorMullen. Is this dup of anything?

There's [one for VSCode](https://github.com/dotnet/aspnetcore/issues/14292) and we knew it'd be an issue for VS but didn't have an issue for it yet. So this is a good one to have!

**Comment by NTaylorMullen** [comment]
@CyrusNajmabadi did pull based diagnostics in Roslyn land in 16.8-Preview4?

**Comment by TanayParikh** [comment]
Blocked on: https://github.com/dotnet/roslyn/pull/47914

**Comment by TanayParikh** [comment]
VSTS Tracking Issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1236414

**Comment by TanayParikh** [comment]
Going to close this out as done in Preview 2 with the following notes;

- Codespaces are missing pull diagnostics (external, LSP Platform): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1180734
- Diagnostic flickering is still WIP (external, LSP Platform): https://github.com/dotnet/aspnetcore/issues/28030
- Trailing `;` diagnostic for explicit expressions (external, LSP Platform): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1249408 
- On-by-default pending (blocking the DDRIT tests) (external, Roslyn)

In terms of validation, you'll have to turn on the feature flag:

`Tools | Options | Text Editor | C# | Advanced | Razor Pull`
