### ISSUE TITLE
Changing content of textarea in code after manual change by user

### ISSUE THREAD

**Issue by livescribbles** [dotnet/aspnetcore#21130]
### Describe the bug
The content of textarea does not change thru code after it has been manually changed by user

### To Reproduce

Step 1. Create a blazor webassembly application
Step 2. In one of the pages (say Counter) add the following:
```
<textarea>@content</textarea>
<button @onclick="Click">Click</button>

@code {
	string content = "initial content";

	void Click()
	{
		content = "content changed from code";
	}
}
```
Step 3. Run the application and **type something** in the textarea
Step 4. Click on the button.

Result. textarea content does not change.
p.s.
If @bind property is used the content changes correctly

**Comment by julienGrd** [comment]
Indeed you have to re-render your component : you have to call StateHasChanged manually in this case
Why not use @bind ? except if you don't want your @content be synchronize with the text write by the user but i don't understand why a textareay (not readonly ) in this case

**Comment by javiercn** [comment]
@livescribbles thanks for contacting us.

As @julienGrd suggests, use `@bind`. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1) for details
