### ISSUE TITLE
Can i use JsonOutputFormatter.WriteObject function on 3.1 version ?

### ISSUE THREAD

**Issue by pttien** [dotnet/aspnetcore#21135]
I upgrade  my App from 2.2 version to 3.1.
I used JsonOutputFormatter.WriteObject in a Middle-Ware to custom the format of data ( add some properties to Json) before return to client
but in 3.1 version I can't find any ways to replace this logic.
can some one give me a solution ?

**Comment by javiercn** [comment]
@pttien thanks for contacting us.

Json.NET is not part of 3.+ by default, you can use the new system.text.json support. See [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#newtonsoftjson-jsonnet-support) for details on the update.

**Comment by pttien** [comment]
@javiercn Thanks for your answer ,
I will try it.
