### ISSUE TITLE
Routing broken when publishing default React.js project template to IIS 10.0

### ISSUE THREAD

**Issue by gvautour** [dotnet/aspnetcore#21137]
I created a new ASP.NET Core 3.1 Web Application project in Visual Studio 2019 using the React.js template. Without changing any code, I published to IIS 10.0 using the File System publish method and am having routing issues.

The site partly works, but the API is only available via the browser if I force a refresh (Ctrl+F5), a simple refresh or a visit to the API endpoint renders the single page app's default view.

E.g.
- https://dev.mydomain.com/myapp/                               -- this is the root of my SPA
- https://dev.mydomain.com/myapp/weatherforecast     -- this is the root of my single API endpoint which I will later change to /api/weatherforecast

**Comment by javiercn** [comment]
@gvautour thanks for contacting us.

It is likely that the react service worker is intercepting the request to the API, I would check on the network tab in your browser how the request is being handled.

**Comment by gvautour** [comment]
Indeed, the problem was related to the Chrome service worker, thank you.
