### ISSUE TITLE
Wasm framework for Blazor

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/aspnetcore#21144]
I know that Blazor has a interpreted mode and AOT mode.
But I think there should be a third way: a wasm framework built in the browsers. It should contain 
- all the common numeric, literal and date type operations and casting.
- Dom manipulation operations. 
- seneding requests to the server if needs (like Ajax).

Isn't this all what we need from client code?
If this wasm framework contained in all browsers, there is no need to download anything to the client except a pure wasm code targeting this framework.
Without a wasm framework, it will be a miss on the client, due to thousands of dlls coming from hundreds of sites using different web technologies targeting wasm. It can cause a dll hell, or consume the client storage very badly.
.Net core can have a wrapper to this wasm framework, that actually doesn't contain any code but the classes and method signatures.
So we can target this wrapper in manage code. This wrapper can provide the same names of .NET methods and classes can have the same names but staring with Wasm, such as WasmString, or belong to the Wasm namespace such as Wasm.String. This will make it very familiar and need zero time to learn.
If the wasm framework doesn't contain some advance or repeated functionality, we can write more classes targeting wasm framework, and download the dll to the client. this will minimal as the browser already has the common wasm framework used by all web technologies.
Is this possible and doable? Can it be better (less size and faster in development and production)?
If it is, I think MS should plan it with other companies involved with wasm.

**Comment by VBAndCs** [comment]
What do you think @SteveSandersonMS ?

**Comment by SteveSandersonMS** [comment]
To be honest I don't think this issue tracker is the right place for such a suggestion. You're talking about a general web platform feature, so it would make more sense to discuss it with standards bodies and browser makers.

> Without a wasm framework, it will be a miss on the client, due to thousands of dlls coming from hundreds of sites using different web technologies targeting wasm. It can cause a dll hell, or consume the client storage very badly.

There is no "DLL hell" equivalent for Blazor WebAssembly applications, since each application is self-contained and always has the right versions of its dependencies. As for storage, a typical Blazor WebAssembly application will not be significantly larger than other SPAs (on the order of a few megabytes). Dependencies can be shared across sites via CDN if desired.

I'll close this as external since it's about a general browser capability and not about the code in this repo. Hope that's OK!

**Comment by VBAndCs** [comment]
@SteveSandersonM
> on the order of a few megabytes

Only one mega can consume gegea on the client if he append thousands of sites over one year.
Worst: a few mega download for each client can consume the server bandwidth and slow down the traffic if it hosts popular sites.
MS abounded web forms to MVC because a few kilos resulting of the view state and not optimized html code. Every kilobyte in web counts.
Thanks.

**Comment by VBAndCs** [comment]
@SteveSandersonM
Let's escape the `External` part, and deal with this internally:
The nearest thing to what I need is this old project (I think MS was empracing this until 2013, as I downloaded a binary version once from msdn):
https://github.com/nikhilk/scriptsharp
It was converting C# code to JS but it provided the necessity API to use in C# to be mapped to objects used in JS like HTML DOM and JQuery … etc.
The classes in this API are just an empty rapper (methods and properties return nulls, and voids have empty bodies)
You can make use of this wrapper in development, and create a .NET wasm framework (regardless of the browsers), that targets wasm instead of JS and JQ. When compiling Blazor code to wasm, the wrapper code will be compiled to calls to the wasm framework, which will be downloaded to the client once for all Blazor sites he visits.
This will:
1. restrict developers from referencing unnecessary dlls.
2. save the time you use to strip out unused functionality from the dlls
3. Save client's space and server's bandwidth.
4. always use AOF compiled framework, because the framework is pre-built for .net Core and app independent.

Can we please discuss this?

**Comment by VBAndCs** [comment]
@SteveSandersonMS
Wasm team said they are working on interface-types:
https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md
I think this will allow us to contact with web API easily, so, we can just use the `wrapper` to call wep API through these interfaces. Do I get this right? I am not a wasm expert.
I hope you reopen this issue, so we can have a useful discussion. I don't know why this repo jumps to the close button too soon? Let the community share ideas at least for a few days.

**Comment by SteveSandersonMS** [comment]
If it helps, I’m happy to reopen this! I only closed it because it seems external to this repo. People are welcome to discuss it as much as they like, of course.

**Comment by VBAndCs** [comment]
@SteveSandersonMS 
Thanks 😊.
