### ISSUE TITLE
Blazor Routing Information

### ISSUE THREAD

**Issue by nikolayarhangelov-arnitek** [dotnet/aspnetcore#21140]
Hello, 
I am building a modular Blazor application with many pages and I am trying to create an Admin-only page used for diagnostics. The diagnostics would include a list of all routes in the Blazor app with their paths and authorization roles and policies.

My application already has such a list for the API controllers and actions, which is created using _IActionDescriptorCollectionProvider_. This approach also works for getting a list of all Razor pages in an MVP application.

The routing classes in Blazor are mostly internal and the [Router](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/Routing/Router.cs) doesn't expose its routes. It would be useful to have a cached collections of the Blazor pages that can be injected similar to _IActionDescriptorCollectionProvider_.

**Comment by pranavkm** [comment]
@nikolayarhangelov-arnitek the implementation of the Router component is an internal detail of Blazor and we do not think it's necessary for us to expose it's behavior as part of the public API surface. You should be free to copy it's content in your app and re-use it.

**Comment by nikolayarhangelov-arnitek** [comment]
Thanks for the quick feedback @pranavkm, I will investigate this.
