### ISSUE TITLE
Blazor Client can not get access token after login successfully

### ISSUE THREAD

**Issue by hieuluong1989** [dotnet/aspnetcore#21142]
I am using Blazor Webassembly Standalone with AAD. Login is ok, but I can not get access token by AuthenticationService.RequestAccessToken. The tokenResult is not null but when I get tokenResult.TryGetToken(out var token) it can not get token

I tried with https and http.
My repos: https://github.com/hieuluong1989/BlazorAAD
I also posted this issue https://github.com/dotnet/AspNetCore.Docs/issues/17963 cc: @guardrex

**Program.cs**

```
builder.Services.AddMsalAuthentication(options =>
            {
                var authentication = options.ProviderOptions.Authentication;
                authentication.Authority = "https://login.microsoftonline.com/...";
                authentication.ClientId = "...";
            });

```

**Index.razor**

```
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication

@inject HttpClient Http
@inject IAccessTokenProvider AuthenticationService

<button type="button" class="btn btn-secondary oi oi-loop-circular" @onclick="Search"></button>

@code {
    protected async Task Search()
    {
        var tokenResult = await AuthenticationService.RequestAccessToken();
        if (tokenResult.TryGetToken(out var token))
        {
            Http.DefaultRequestHeaders.Add("Authorization", $"Bearer {token.Value}");
            Console.Writeline($"Bearer {token.Value});
        }
    }
}
```

![](https://user-images.githubusercontent.com/52130197/80085996-02fcd700-8594-11ea-8916-c6009d7042e3.png)

**Software versions**
- .NET Core: 3.1.201
-  Microsoft.AspNetCore.Components.WebAssembly : 3.2.0-preview4.20210.8

**Comment by pranavkm** [comment]
@javiercn could you have a look?

**Comment by javiercn** [comment]
@hieuluong1989 thanks for contacting us.

Can you provide a minimal repro project that illustrates the issue?

**Comment by javiercn** [comment]
@hieuluong1989 thanks for contacting us.

You need to ask for a scope in order to get an access token.

**Comment by hieuluong1989** [comment]
@javiercn: Thank you for you replying. I tried to add scopes, then it worked. I missed this document
https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1#access-token-scopes
