### ISSUE TITLE
Can we restrict the child component type in RenderFragment property

### ISSUE THREAD

**Issue by BenLampson** [dotnet/aspnetcore#21141]
This is the Blazor component project case.
Can we restrict the child component type in RenderFragment property?

I create the container component but I can't restrict the child component type, I try to use the TagHelper but it seems not to work yet.

I want the code like this
There's a property in the container component.
```C#
[Child(CardAction)]
[Parameter]
public RenderFragment Actions { get; set; }
```
And I create the child item like this one:
```C# 
public partial class CardAction
{
 //My code...
}
```

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/12302. We're looking at addressing this as part of 5.0

**Comment by javiercn** [comment]
Closing in favor of #12302. @pranavkm if you have any reason to leave this open, please say so.
