### ISSUE TITLE
Need Access to HttpContext in GenerateNonce

### ISSUE THREAD

**Issue by ghstahl** [dotnet/aspnetcore#21148]
### Is your feature request related to a problem? Please describe.
In asp.net core 2 I was able to store IServiceProvider as a global, which I then used to get IHttpContextAccessor in GenerateNonce.
In asp.net core 3, I can't do that anymore.

A clear and concise description of what the problem is.
Example:
I would argue that if you are going to let me override stuff like OpenIdConnectProtocolValidator, you would give me access to the same context you have when you use my version.   I was using a cookie as an input in my nonce generation. 

### Describe the solution you'd like
I need access to the same context that you have as demonstrated in your code.  
```
            if (Options.ProtocolValidator.RequireNonce)
            {
                message.Nonce = Options.ProtocolValidator.GenerateNonce();
                WriteNonceCookie(message.Nonce);
            }
```
Your ```WriteNonceCookie``` has HttpContext knowledge. 

We could consider OpenIdConnectProtocolValidator to be an injectable scoped object instead of me doing a 
```  
options.ProtocolValidator = new MyOpenIdConnectProtocolValidator(){}
```
BTW: There is other parts of the design that let context be brought in from the outside like.
```
options.Events.OnTokenValidated = async context =>{}.
```
where context contains an HttpContext.

**Comment by Tratcher** [comment]
One improvement we've already made here in 5.0 is that there are new extensions to let you inject a service of your choice when configuring the options.
https://github.com/dotnet/aspnetcore/blob/13b73ed4a789522c1204729f2bb127a3b3e26cb5/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs#L20
That service probably needs to be a singleton though? Worst case you can inject IServiceProvider and create your own scope as needed.

Can you give the 5.0 code a try and see how far it gets you?

Note OpenIdConnectProtocolValidator is not a type that's AspNetCore aware, it comes from a general protocol library we depend on. It can't directly depend on or expose any of our types.

**Comment by ghstahl** [comment]
In v3 IServiceProvider, when I tried to make and use it globally it errored out with a disposed.
```
An unhandled exception has occurred while executing the request.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
``` 
So I think the same thing is going to happen here.  
So are you saying that the OpenIdConnectProtocolValidator may have to become context aware?

**Comment by Tratcher** [comment]
> In v3 IServiceProvider, when I tried to make and use it globally it errored out with a disposed.

How were you calling that?

> So are you saying that the OpenIdConnectProtocolValidator may have to become context aware?

No, I'm saying it can't be, it can't take those kind of dependencies.

**Comment by ghstahl** [comment]
I would say that you are GenerateNonce aware, so letting me inject something that is not OpenIdConnectProtocolValidator would work.  Or an injectable wrapper to OpenIdConnectProtocolValidator .  My overridden GenerateNonce doesn't rely on anything in OpenIdConnectProtocolValidator, but it needs data I stored in a cookie.  

```
Startup.Configure(IServiceProvider sp){
Global.ServiceProvider = sp;  // this is bad, because using it later on blows up.
}
```

**Comment by ghstahl** [comment]
Oh, and things are getting exciting cause I got David  Fowler involved and pointed out that GenerateNonce needs to be async.

**Comment by ghstahl** [comment]
@davidfowl showed be how to inject DI objects into my MyOpenIdConnectProtocolValidator().
So we can probably close this specific one.  

```
 authenticationBuilder.AddOpenIdConnect(scheme, scheme, options =>
{
                    services.AddOptions<OpenIdConnectOptions>()
                        .Configure<IServiceProvider>((options, sp ) =>
                        {
                            options.ProtocolValidator = new MyOpenIdConnectProtocolValidator(sp)
                            {
                                RequireTimeStampInNonce = false,
                                RequireStateValidation = false,
                                RequireNonce = true,
                                NonceLifetime = TimeSpan.FromMinutes(15)
                            };
                        });
}
```
The problem @davidfowl highlighted that I was doing the following in my GenerateNonce  override;
```
 var original = oidcPipelineStore.GetOriginalIdTokenRequestAsync(nonce).GetAwaiter().GetResult();
```
I made a separate issue [here](https://github.com/dotnet/aspnetcore/issues/21152)

**Comment by anurse** [comment]
Triage: closing as per last comment. The new injection API in 5.0 should make this simpler too since it's a short-hand for the workaround you've already used.

**Comment by ghstahl** [comment]
This is embarrassing.  The code @davidfowl compiled but it looks like OpenIdConnectHandler didn't pick up MyOpenIdConnectProtocolValidator.  I didn't catch that my GenerateNonce wasn't called until much later in the pipeline.  Can we please reopen this.

**Comment by ghstahl** [comment]
https://gist.github.com/ghstahl/9b7d92d4eea1e5cfee595ce29b805cb3
@davidfowl can  you take a look at how I am calling it.  
I know it takes up my validator when I do this;
```
 authenticationBuilder.AddOpenIdConnect(scheme, scheme, options =>
 {
                    options.Authority = record.Authority;
                    options.ProtocolValidator = new MyOpenIdConnectProtocolValidator();
}
```
But in that case I get no context.

**Comment by davidfowl** [comment]
Put it here https://gist.github.com/ghstahl/9b7d92d4eea1e5cfee595ce29b805cb3#file-myopenidconnectprotocolvalidator-L87. You keep nested it inside of other delegates, put it top level.

**Comment by ghstahl** [comment]
nope: Still no go.
https://gist.github.com/ghstahl/9b7d92d4eea1e5cfee595ce29b805cb3

**Comment by davidfowl** [comment]
Did the callback run?

**Comment by davidfowl** [comment]
Maybe it's running then you're overwriting it? It still seems like you're setting it twice in that method...

**Comment by ghstahl** [comment]
The 
```
 services.AddOptions<OpenIdConnectOptions>()
                        .Configure<IServiceProvider>((options, sp ) =>{}
```
approach never works.  No breakpoint is ever hit.
This gets hit
```
public class SimpleOpenIdConnectProtocolValidator : OpenIdConnectProtocolValidator
    {
        public override string GenerateNonce()
        {
            return Guid.NewGuid().ToString();
     //       return base.GenerateNonce();
        }

    }
....
                    options.ProtocolValidator = new SimpleOpenIdConnectProtocolValidator()
                    {
                        RequireTimeStampInNonce = false,
                        RequireStateValidation = false,
                        RequireNonce = true,
                        NonceLifetime = TimeSpan.FromMinutes(15)
                    };
```

**Comment by ghstahl** [comment]
In my case I have 2 OIDC external idps (google, and other).   I need to make sure that I set it for both, as they are each getting added via AddOpenIdConnect().
In my case its the same code for ProtocolValidator , but it doesn't need to be so setting it uniquely for each IDP has to be there.

**Comment by davidfowl** [comment]
If you can get me some minimal runnable repro, I can debug it, seems like it should work and I'm betting there's something else going on that you haven't shared.

**Comment by ghstahl** [comment]
@davidfowl 
here you go.
https://github.com/P7CoreOrg/for-david-oidc-generate-nonce

**Comment by davidfowl** [comment]
Change:

```C#
services.AddOptions<OpenIdConnectOptions>()
````

to

```C#
services.AddOptions<OpenIdConnectOptions>("oidc")
```

cc @HaoK turns out OptionsBuilder doesn't have an equivalent of `ConfigureAll`.

**Comment by HaoK** [comment]
OptionsBuilder shouldn't really have a configure all since its implicitly scoped to one named instance, that was the idea/design anyways.  Its basically configuring one named options instance

**Comment by HaoK** [comment]
So yeah if you want to configure all, you don't pass in the name and call it off of the service collection

**Comment by davidfowl** [comment]
@HaoK but then you don't have those overloads that take services.

**Comment by ghstahl** [comment]
@davidfowl that did it for the repo and my real project.  I am never going to remember this stuff so thank goodness this is a record for later searches.  So thanks and I will be sleeping well tonite.

**Comment by HaoK** [comment]
Ah yeah so that's a gap in the sugar I guess, ConfigureAll I wouldn't be surprised if noone uses
