### ISSUE TITLE
GenerateNonce, when called from OpenIdConnectHandler needs to be async

### ISSUE THREAD

**Issue by ghstahl** [dotnet/aspnetcore#21152]
OpenIdConnectHandler  relies on OpenIdConnectProtocolValidator, which I can replace during configuration.  
I override GenerateNonce().

Problem1:  GenerateNonce relies on downstream dependencies that are async.
```
public override string GenerateNonce()
{
...     
     // This is bad, file an issue to support making this call to GenerateNonce async.
        var original = _oidcPipelineStore.GetOriginalIdTokenRequestAsync(nonce).GetAwaiter().GetResult();
...
}
```
Problem 2:  OpenIdConnectProtocolValidator needs to be injectable, so that I can get access to service dependencies.

https://github.com/dotnet/aspnetcore/issues/21148
```
public class MyOpenIdConnectProtocolValidator : OpenIdConnectProtocolValidator
{
    private readonly IOIDCPipelineStore _oidcPipelineStore;
    private readonly IHttpContextAccessor _accessor;
    
    public MyOpenIdConnectProtocolValidator(IOIDCPipelineStore oidcPipelineStore, IHttpContextAccessor accessor)
    {
        _oidcPipelineStore = oidcPipelineStore;
        _accessor = accessor;
    }
}
```
 
[reference example](https://gist.github.com/davidfowl/94603ed0a8e2a3d6f61d5b8688c2b07d)

**Comment by anurse** [comment]
> OpenIdConnectHandler relies on OpenIdConnectProtocolValidator, which I can replace during configuration.

This type isn't owned by ASP.NET Core, it's from the `Microsoft.IdentityModel.Protocols.OpenIdConnect` library: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs

You should file an issue on [the repo that contains this type](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) to see if it can be added.

Closing this issue as the request is external to our product.
