### ISSUE TITLE
SignInResult failed when username and normalized username different asp.net identity

### ISSUE THREAD

**Issue by kuntalbose** [dotnet/aspnetcore#21151]
I am trying to check user's credential with bellow code 
`var signInResult = await this.signInManager.PasswordSignInAsync(username, password, false, false);`

But I found if `UserName` and `NormalizedUserName`  columns values are different then `SignInResult` returns faild .

For bellow values `SignInResult=Succeed `
UserName = ABC
NormalizedUserName = ABC

But for bellow values `SignInResult=Failed`
UserName = ABC@gmail.com
NormalizedUserName = ABC
or
UserName = ABC
NormalizedUserName = ABC@gmail.com

am I doing any mistake?

**Comment by blowdart** [comment]
Yes, you're not updating the normalized username. They have to be in sync, it's never going to work like that. 

Presumably you're updating the entity as there's no API for changing usernames on the store.  You need to pull the ILookupNormalizer out of DI and call NormalizeName on it when updating your entity.
