### ISSUE TITLE
Move SDL validation out of our builds

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#21158]
The engineering services team wants all repos to move SDL validation out of their repo builds, and instead run SDL validation as part of the ringed release pipeline. This means taking the SDL step out of our .yml files, and adding an SDL config file to our `eng` folder. Tracking that work here.

**release/3.1**

- [x] AspNetCore - https://github.com/dotnet/aspnetcore/pull/21153
- [x] AspNetCore-Tooling - https://github.com/dotnet/aspnetcore-tooling/pull/1823
- [x] Extensions - https://github.com/dotnet/extensions/pull/3201
- [x] EFCore - https://github.com/dotnet/efcore/pull/20736
- [x] EF6 - https://github.com/dotnet/ef6/pull/1653

**master**

- [x] AspNetCore - https://github.com/dotnet/aspnetcore/pull/21545
- [x] AspNetCore-Tooling - https://github.com/dotnet/aspnetcore-tooling/pull/1864
- [x] Extensions - https://github.com/dotnet/extensions/pull/3229
- [x] EFCore - https://github.com/dotnet/efcore/pull/20863
- [x] EF6 - https://github.com/dotnet/ef6/pull/1662

**Comment by blowdart** [comment]
Wait, does this not mean you'd get SDL warnings at the last possible minute? How often do ringed release pipelines run?

**Comment by wtgodbe** [comment]
I don't know how often they run, but this was the recommendation we got from the eng services team. Some stuff copied from the thread:

> I think the risk is minimal. As Priya noted today in tactics, once the initial Policheck triage is done, the delta is relatively minimal over time. This means that most of the time, Policheck is just taking up build time. Our eventual goal is to be down to a two hour build time. Part of the time spent today is in Policheck, endangering that ability. It does still mean that we will get Policheck results regularly as we get new builds, and it means that if we get a result that must be fixed prior to shipping, we’ll simply turn another build to fix it, and be back in two hours.

Adding @jcagme and @markwilkie who know more about the thinking behind this change

**Comment by wtgodbe** [comment]
@blowdart as an update, @jcagme is working on a validation pipeline that will run on a cadence (either daily or weekly). Repos can opt in (we're going to). This means we can pull SDL out of our builds while still getting regular validation

**Comment by blowdart** [comment]
Opt-in?! 

![giphy-downsized-large](https://user-images.githubusercontent.com/796298/81346501-3b5de400-906f-11ea-8884-cdfe37142d19.gif)
