### ISSUE TITLE
Bazor strongly-typed client error

### ISSUE THREAD

**Issue by mariohik** [dotnet/aspnetcore#21169]
I'm trying to implement a strongly-typed Blazor client, but when I access the page the error appears: STATUS_ACCESS_VIOLATION

I am attaching an example project:
[BlazorApp3.zip](https://github.com/dotnet/aspnetcore/files/4528535/BlazorApp3.zip)

**Comment by javiercn** [comment]
@mariohik thanks for contacting us.

What do you mean by a "strongly typed blazor client" can you provide more details of what you are trying to do?

**Comment by mariohik** [comment]
Hi @javiercn
Thanks for the quickly reply.

I encapsulated API calls in a service, as described on the blog: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available
Look at the example of FetchData.razor

**Comment by mariohik** [comment]
This error actually occurs when in DEBUG mode a page with OnInitialized or OnInitializedAsync.
If you run without DEBUG (CTRL + F5) the application runs smoothly.
You can try on FetchData.razor
[BlazorApp4.zip](https://github.com/dotnet/aspnetcore/files/4532340/BlazorApp4.zip)

![Anotação 2020-04-25 011405](https://user-images.githubusercontent.com/38980017/80270873-21e19300-8692-11ea-9d02-6ff49e9ec440.jpg)
![Anotação 2020-04-25 010913](https://user-images.githubusercontent.com/38980017/80270879-25751a00-8692-11ea-9932-854fd090062f.jpg)

**Comment by mkArtakMSFT** [comment]
@mariohik, I'm using your repro project (BlazorApp4.zip) you've provided and am able to navigate to and from (while debugging) the FetchData page. 
Everything works fine:

![image](https://user-images.githubusercontent.com/34246760/80408913-d6d7a380-887c-11ea-8c11-7788e6f607e7.png)


![image](https://user-images.githubusercontent.com/34246760/80408708-7fd1ce80-887c-11ea-9d2e-e1eca262e7ba.png)

Based on this it feels like you may have some issues with your VS installation, if you're still facing some issues. Please make sure you have the latest VS 2019 preview installed and if so, repair it.

**Comment by mkArtakMSFT** [comment]
I've just realized that you may have missed to actually add code for the WeatherClient in BlazorApp4 sample you planned to.
So I tried the original BlazorApp3.zip sample you've provided and I am successful with that app to:
![image](https://user-images.githubusercontent.com/34246760/80409716-35515180-887e-11ea-914b-9ea878434c6f.png)

**Comment by mkArtakMSFT** [comment]
Given this, make sure you have the latest .NET Core 3.1 SDK installed and the latest VS 2019 VS preview release.

**Comment by mariohik** [comment]
@mkArtakMSFT Yes, I have the latest version 3.1 of the SDK and reinstalled Visual Studio, but the error still occurs.
I have .NET 5 installed on the computer.
I will try to uninstall it and test again.

**Comment by mariohik** [comment]
Informing if someone has the same problem:
This error happens only when using Microsoft Edge Canary. With the stable versions of Edge and Chrome the application works correctly and it is possible to debug.
