### ISSUE TITLE
DefaultAntiforgery overrides a more restrictive cache policy

### ISSUE THREAD

**Issue by andyedinborough** [dotnet/aspnetcore#21176]
### Describe the bug
For our applications, we set the cache-control header on our responses with `must-revalidate` to ensure customers see the correct information if they click the back button. DefaultAntiforgery sets the cache-control header even though the header is already present with a value of `no-cache, no-store, must-revalidate`:

https://github.com/dotnet/aspnetcore/blob/master/src/Antiforgery/src/Internal/DefaultAntiforgery.cs#L387

We cannot add middleware to re-set it after DefaultAntiforgery has changed it, because the response has already started:

```
System.InvalidOperationException: The response headers cannot be modified because the response has already started.
   at void Microsoft.AspNetCore.HttpSys.Internal.HeaderCollection.ThrowIfReadOnly()
   at void Microsoft.AspNetCore.HttpSys.Internal.HeaderCollection.set_Item(string key, StringValues value)
```

Prior to netcoreapp3.1, we replaced `DefaultAntiforgery` with a class that inherited from it and overrode the `SetDoNotCacheHeaders` method to set the value as we needed.  Now that these types are internal, our only way to move forward is through reflection.

For reference, I had previously submitted a PR regarding this behavior: https://github.com/aspnet/Antiforgery/pull/136

### To Reproduce
Add middleware before `UseRouting` that sets the `cache-control` header to `no-cache, no-store, must-revalidate`. Create a view with a form. Observe that the cache header has been reverted.
 

### Further technical details
- netcoreapp3.1
- VS2019

**Comment by pranavkm** [comment]
@andyedinborough per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Directives):

> no-store
The response may not be stored in any cache. Although other directives may be set, this alone is the only directive you need in preventing cached responses on modern browsers. max-age=0 is already implied. Setting must-revalidate does not make sense because in order to go through revalidation you need the response to be stored in a cache, which no-store prevents.

It doesn't look like you need to set the `must-revalidate` header since `no-store` is more restrictive. Am I missing something?

**Comment by andyedinborough** [comment]
I will retest. In practice, we had to add `must-revalidate` to force the browser to reissue the request when clicking the back button.

**Comment by andyedinborough** [comment]
I've confirmed that without `must-revalidate`, Safari 13.1 and Firefox 75 (though seemingly fixed in 76), will serve the previous page when clicking back, without reissuing the request.  Chromium based browsers (specifically Edge, Brave, and Chrome itself) do reissue the request.

Fundamentally though, if there were some new keyword introduced for that header, developers would not be able to use it without changes to this code. The code is already parsing the header if it's present to issue a warning that the value is being overwritten. it would be trivial to change it to use that parsed result to set the header, so only the required properties are added.

**Comment by pranavkm** [comment]
@rynowak \ @JunTaoLuo here's to reviving old memories: https://github.com/aspnet/Antiforgery/pull/117. We could append to the header, or toss in `must-revalidate` to the mix by default.

/cc @blowdart \ @javiercn in case they have any thoughts on this.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by javiercn** [comment]
This was done as part of https://github.com/dotnet/aspnetcore/pull/27130
