### ISSUE TITLE
Blazor WASM Release mode JS interop deserialization issue

### ISSUE THREAD

**Issue by mlathan** [dotnet/aspnetcore#21170]
### Describe the bug
In a Blazor WebAssembly application JS interop can't deserialize structs back into C# in Release mode. More specifically, the problem arose with Point and SizeF. Both structs are the default ones in C# after deserialization. In Debug mode compilation the structs contain the data return from Javascript.

I guess this involes other struct/class types, too. Maybe it has something to do with the strong compression in release mode.

### To Reproduce

1. Download attached minimal [sample project](https://github.com/dotnet/aspnetcore/files/4528571/JsonDeserializationIssue.zip).
2. Use Visual Studio Version 16.6.0 Preview 3.0, Blazor WebAssembly 3.2.0-preview4.20210.8.
3. Use Debug mode.
4. Start app as Kestrel, not IIS Express, and open with Microsoft Edge  81.0.416.64 (64-Bit).
5. You see two buttons. Each button sends a C# struct by JS Interop to Javascript which returns the same data back to C#; `struct Point` and `struct SizeF`.
6. You see 1, 1 for Point and Size in the labels behind the buttons, which is Okay.
7. Quit app and use Release mode.
8. Do as told in 5. Now you see 0, 0 for Point and Size, which is Wrong. For further transparency see console in web browser. There C# and Javascript log what data was send, received and returned.

#### OS
Windows 10 64-Bit

#### IDE
Visual Studio 16.6.0 Preview 3.0

#### .Net Core
```
.NET Core SDK (according to "global.json"):
 Version:   3.1.300-preview-015095
 Commit:    85c45057dc

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015095\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@mlathan thanks for contacting us.

It is likely that the linker is not seeing the code being used and is taking away the members from the struct. See [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1) for details.
