### ISSUE TITLE
Blazor WASM linking omits the entire wwwroot\_framework\_bin dir when using DeployOnBuild

### ISSUE THREAD

**Issue by dfederm** [dotnet/aspnetcore#21178]
### Describe the bug
After upgrading to preview 5, when doing a release build (or a debug build with linking enabled), the entire `$(PublishDir)\wwwroot\_framework\_bin` dir is missing.

### To Reproduce
Have this in your project file:
```xml
<DeployOnBuild>true</DeployOnBuild>
```

Then build a release build or set
```xml
<BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>
```

```
>dir /S /B obj\amd64\Publish\wwwroot\_framework
obj\amd64\Publish\wwwroot\_framework\blazor.boot.json
obj\amd64\Publish\wwwroot\_framework\blazor.boot.json.br
obj\amd64\Publish\wwwroot\_framework\blazor.boot.json.gz
obj\amd64\Publish\wwwroot\_framework\blazor.webassembly.js
obj\amd64\Publish\wwwroot\_framework\blazor.webassembly.js.br
obj\amd64\Publish\wwwroot\_framework\blazor.webassembly.js.gz
obj\amd64\Publish\wwwroot\_framework\wasm
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.3.2.0-preview5.20216.1.js
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.3.2.0-preview5.20216.1.js.br
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.3.2.0-preview5.20216.1.js.gz
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.timezones.dat
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.timezones.dat.br
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.timezones.dat.gz
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.wasm
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.wasm.br
obj\amd64\Publish\wwwroot\_framework\wasm\dotnet.wasm.gz
```

Note that `DeployOnBuild=true` causes a publish to happen after a build. So something in the Blazor WASM MSBuild targets is missing the `_bin` dir entirely when using this process.

### Further technical details
.NET SDK version: 3.1.300-preview-015115

**Comment by dfederm** [comment]
While trying to come up with a minimal repro I found that this actually only repros in VS. Command-line works just fine.

**Comment by dfederm** [comment]
Digging through diag logs, this seems related to this:
```xml
  <Target
      Name="_LinkBlazorApplication"
      Inputs="$(ProjectAssetsFile);
              @(_BlazorManagedRuntimeAssembly);
              @(BlazorLinkerDescriptor);
              $(MSBuildAllProjects)"
      Outputs="$(_BlazorLinkerOutputCache)"
      Condition="'$(BuildingInsideVisualStudio)' != 'true' OR '$(DeployOnBuild)' != 'true'">
```

That condition is causing linking to not happen at all, which in turn causes the linker.output file to be missing, which causes the outputs to not get resolves and thus not copied during publish.

However, I can't seem to find that condition in actual source (left is GitHub, right is on my disk):
![image](https://user-images.githubusercontent.com/6445614/80228975-9bcb3b00-8604-11ea-9d28-e6e2612f6b66.png)

I'm fairly confused at this point. @pranavkm (most recent editor of Blazor.MonoRuntime.targets), do you know why the source doesn't match the NuGet package?

**Comment by javiercn** [comment]
@dfederm thanks for contacting us.

@dfederm can you point to the gh link where this is happening?

**Comment by dfederm** [comment]
@javiercn here's where I'm looking on the GH side: https://github.com/dotnet/aspnetcore/blob/master/src/Components/Blazor/Build/src/targets/Blazor.MonoRuntime.targets#L228

Maybe there's some release branch I need to look in instead of master, but I'd still expect to see all changes (including potentially unreleased ones) in master.

**Comment by javiercn** [comment]
Yeah, that's not the right branch. `blazor-wasm` is where the magic happens.

 https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Blazor/Build/src/targets/Blazor.MonoRuntime.targets#L228

**Comment by dfederm** [comment]
@javiercn Looks like it's the blazor-wasm branch I wanted to be looking at for the source. IMO it seems strange that you're sharing a repo but working in a completely unrelated branch.

Found the commit which added the condition to the target which is causing the regression: https://github.com/dotnet/aspnetcore/commit/ae569e2b48f66a2c4833319e82fcc74876c763ce by @SteveSandersonMS

**Comment by javiercn** [comment]
@dfederm it's because of delivery/shipping logistics. Our infrastructure for shipping is quite complicated and this is the easiest and fastest way to ship the wasm bits. Once they are out we'll go back to working on master for everything in 5.0

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by javiercn** [comment]
I had a conversation with @dfederm about this offline, let's revisit this if we have time.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Many things have changes in this area in .NET 5. Can you please validate the latest .NET 5 preview release and see whether this still repros? Thanks!

**Comment by javiercn** [comment]
I gave this a quick try with our 5.0 RC1 bits and its working for hosted and standalone Blazor WebAssembly apps.

@dfederm do you want to give it a try on your end to make sure we are good here?

You can use the nightlies from https://github.com/dotnet/installer or wait for RC1 to be released. I think this was fixed as a result of the changes we did on the build pipeline. Linking will happen at compile time vs at publish time as it was in the past.

I don't think we will be backporting this to 3.2, since we will be encouraging folks to move to 5.0 and the move should be straightforward.

@mkArtakMSFT I'm closing this issue now since I don't think we need to do any more actions here unless we hear that its not working (in which case, we will re-evaluate).

**Comment by javiercn** [comment]
I walk my statement back, I went to put on a test to confirm and there seems to be something broken in the publish pipeline here, both for console apps and Visual Studio.

I'm not sure if it's specific to this scenario or a more broad publish issue. It looks like the component dlls don't get copied over. @pranavkm do you have any thoughts?

I think I've seen similar CTI reports, were you looking into this area not so long ago?

**Comment by Pilchie** [comment]
@javiercn or @pranavkm - any updates here?

**Comment by pranavkm** [comment]
I'm not sure what issue @javiercn saw, but I don't see this with the rc1 (or newer bits). We'll talk about this when he's back.

**Comment by dfederm** [comment]
I've upgraded to .NET 5.0 and no longer see this issue BTW.

On an unrelated note though, the PublishDir nor PublishUrl seem to be overridable, so I have copy the published output after the fact.

```xml
  <Target Name="CopyToArtifactsPath" AfterTargets="FileSystemPublish">
    <ItemGroup>
      <Artifact Include="$(PublishUrl)\**" />
    </ItemGroup>
    <Copy SourceFiles="@(Artifact)" DestinationFiles="@(Artifact -> '$(BaseArtifactsPath)\$(AssemblyName)\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```

**Comment by pranavkm** [comment]
@dfederm could you file a separate issue to track this? Thanks!

**Comment by dfederm** [comment]
Can do

**Comment by dfederm** [comment]
Looks like I was wrong. I suppose that too was fixed in .NET 5.
