### ISSUE TITLE
Inconsistent version file compared to other frameworks

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#21177]
A change was made in https://github.com/dotnet/aspnetcore/pull/20166 that renamed the `.version` file to `Microsoft.AspNetCore.App.versions.txt`.  It's not clear why this change was made but now there's inconsistency between ASP.NET and the other frameworks.  Microsoft.NETCore.App, Microsoft.WindowsDesktop.App and the SDK all have a file named `.version`.

Repro steps:
1. Open https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.4.20223.12/dotnet-sdk-5.0.100-preview.4.20223.12-win-x64.zip
2. See the following files:
   * shared\Microsoft.AspNetCore.App\5.0.0-preview.4.20221.8\Microsoft.AspNetCore.App.versions.txt
   * shared\Microsoft.NETCore.App\5.0.0-preview.4.20221.7\\.version
   * shared\Microsoft.WindowsDesktop.App\5.0.0-preview.4.20222.5\\.version
   * sdk\5.0.100-preview.4.20223.1\\.version

There should be consistent naming amongst all the version files to make it easier for automation that consumes these files.  This name change was discovered because it broke the automation at https://github.com/dotnet/dotnet-docker/blob/fe5cedf3f4034a263fa2f118b606233cb708b1b4/eng/get-drop-versions.sh#L20.

**Comment by mthalman** [comment]
cc @wtgodbe

**Comment by wtgodbe** [comment]
I'm confused - neither the WindowsDesktop nor Microsoft.NetCore.App shared framework packages carry a file named `.version`. They have `Microsoft.WindowsDesktop.App.versions.txt` and `Microsoft.NetCore.App.versions.txt`, respectively. I was under the impression that the `.version` files were generated during release staging - @leecow is that not the case?

**Comment by wtgodbe** [comment]
And the reason for the name change is that Nuget disallows packing files whose names start with a dot:

> error NU5119: File 'C:\code\aspnet\aspnetcore\artifacts\obj\Microsoft.AspNetCore.App.Runtime\Debug.version' was not added to the package. Files and folders starting with '.' or ending with '.nupkg' are excluded by default. To include this file, use -NoDefaultExcludes from the commandline

**Comment by wtgodbe** [comment]
Actually, looks like this happens in the dotnet/installer repo:

https://github.com/dotnet/installer/blob/bad3a6db7a77182e89469eea1e7aec7dd5ca5173/src/redist/targets/GenerateLayout.targets#L417-L427

For whatever reason it stopped happening for AspNetCore after my change. Looking into it.

**Comment by wtgodbe** [comment]
I'm guessing that the `.version` file gets inserted by dotnet/installer, since for the 3 shared packs, each contains the contents of the corresponding shared framework's `runtimes` folder, flattened, plus a new file named `.version` (or in the case of AspNetCore, the versions.txt file from the root, for some reason). @wli3 @dsplaisted @sfoslund do you know how this `.version` file gets inserted into the SDK?

**Comment by leecow** [comment]
The only .version files we manage are in the /LTS, /Current, and MAJOR.MINOR/ storages. Example: https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/Current/latest.version. I don't know what drives the daily build files. 

@anurse in case he knows about the AspNetCore.App.versions change.

**Comment by wtgodbe** [comment]
ping @wli3 @sfoslund @dsplaisted, do you know where the `.version` files in the SDK come from? https://github.com/dotnet/aspnetcore/issues/21177#issuecomment-619132161

**Comment by wtgodbe** [comment]
Ah, actually looks like this might be related to the contents of the .zip archives, not the .nupkg's (thanks @JunTaoLuo). I'll look into including a `.version` file in our .zip.
