### ISSUE TITLE
Setting up Facebook as an Identity Provider

### ISSUE THREAD

**Issue by jlinstrum** [dotnet/aspnetcore#21188]
I may be getting ahead of this document (sorry), but I got the existing instructions working on my app (cool, thanks for the docs!) so I went on to add Facebook as an identity provider. I did this following the instructions at https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-facebook . On the Azure website I could run the the Azure AD B2C | User flows &gt; B2C_1_signupsignin1 &gt; "Run User Flow" and it seemed to work fine, creating a new identity, returning claims, etc.

However, when I try to log into my app (I made no changes to code), I get a nice new "log in using Facebook" button, but pushing the button generates the following error on my browser console: 

Refused to display 'https://www.facebook.com/login.php?skip_api_login=1&api_key= {...more stuff}' in a frame because it set 'X-Frame-Options' to 'deny'.

I'm guessing this is not a documentation problem, but maybe a problem with how the RemoteAuthenticatorView works, though it could be that the instructions for setting up Facebook need to be slightly different for webasm (the callback URL should be different maybe). In any case, I'm leaving the feedback here because I'm not sure where else to put it. Thanks for the great guide!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by javiercn** [comment]
@jlinstrum thanks for contacting us.

Seems like you are doing B2C auth and are federating with FB within B2C? Are you using our auth package for MSAL? Where do you get that login with FB button? we don't provide such functionality, is that part of the b2c experience? (once the pop-up has been opened or the app has redirected).

As per the reset password functionality, it's not something that msal.js supports, so neither do we.

**Comment by jlinstrum** [comment]
I am pretty much using as is the blazorwasm template with the -au IndividualB2C option, which adds the MsalAuthentication service. After testing the default local account option (which works fine), I went to the "Azure AD B2C | Identity providers" page on the Azure website and selected Facebook as an additional option for "New OpenID Connect Provider" (no changes to app code). After this the pop-up/redirect in my app shows something like "use facebook" as an additional sign-in option (so it must be part of the b2c experience). However, selecting this option leads to the error stated above.

I suspect this option may be very close to working, although that may just be my ignorance showing. In any case, allowing users to log on via third party identity providers was the main reason I tried Azure AD B2C rather than sticking with Identity Server for my app.

I'll open another issue for the password reset.

**Comment by jmprieur** [comment]
@jlinstrum : did you look at this sample: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C or https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-5-B2C

**Comment by jlinstrum** [comment]
Thanks for the links. I was not aware of these samples. They definitely look like they will give me a better feel for the subject. I will try to have a look in the next few days and see if they help. I notice they use a different service to get to the Microsoft identity platform endpoint. Maybe that's what the webasm template should be using? Anyway, I'll give it a look.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by jmprieur** [comment]
what is the webasm template, @jlinstrum ?

**Comment by guardrex** [comment]
@jmprieur He's referring to the Blazor WASM ASP.NET Core template at ...

https://github.com/dotnet/aspnetcore/tree/blazor-wasm/src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates/content/ComponentsWebAssembly-CSharp

... and covered in our Blazor WASM topics here ...

* https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1
* https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1

Side question for you @jmprieur ... It's a bit of an AAD scenario for me at the moment, but it will apply to B2C as well ...

Much (perhaps *all*) of the Azure docs+examples are on the new MS Identity platform (`Microsoft.Identity.Web` and friends). The package version is `0.0.1-preview`, which implies that it isn't supported for production workloads. However, it's described as "supported" and "recommended." Most/all of the prior guidance and examples are mothballed. I was looking at what we might be cross-linking today for our Blazor Server topic, but all I see now are Azure+Identity docs on the new MS Identity platform.

Is it correct thus far on this issue (and for anything else really) that the new Identity platform should be used/recommended by the Blazor docs? For example in working with web API tokens, the guidance would be for Blazor Server (as with any ASP.NET Core app) to be calling `AddSignIn` with `AddWebAppCallsProtectedWebApi` and `AddInMemoryTokenCaches` and following the guidance in https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration?tabs=aspnetcore?

**Comment by jlinstrum** [comment]
Sorry, I meant blazorwasm template with the  -au IndividualB2C option from the https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1 document. That template uses

services.AddAuthentication(AzureADB2CDefaults.BearerAuthenticationScheme) .AddAzureADB2CBearer...

under the Startup.ConfigureServices, whereas the example appears to replace that with

services.AddSignIn(Configuration).AddWebAppCallsProtectedWebApi...

That's just from a 5 minute look though. I'll give it more of a look as soon as I have a chance.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________
