### ISSUE TITLE
VS 2019 ASP.NET CORE 3.1 Build is slow after upgrading from VS 2017 Core 2.2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21186]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/996549/vs-2019-aspnet-core-31-build-is-slow-after-upgradi-1.html)._

---
[regression] [worked-in:VS 2019 February ]
VS 2019 ASP.NET CORE 3.1 Build is slow after upgrading from VS 2017 Core 2.2

The Buid appeared to work fine in VS 2019 during the first part of February 2020. I always keep my Visual Studio Version updated. So I would say that the last working version was then.
I also upgraded my computer to an Intel I9 with 64g/Mem and 1TB/SSD
 All my other apps work very quickly.

Build time has gone from about 30 seconds to about 5 minutes. 

This project consists of  137 small subprojects. 

I added the following to my Startup 
services.AddRazorPages().AddRazorRuntimeCompilation();

I have done the following items only temporarily to see details of the build:
1.NuGet restore is currently disabled. (This saved a bit of time)
2. Tools->Options->Project & Solutions->Build & Run->MS Project Build Output verbosity->Diagnostic

I have attached the Diagnostic for this.

---
#### Visual Studio Feedback System on 4/20/2020, 08:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Would you mind including your binary logs from VS? While the detailed logs are useful, they're not really human readable. Here's how you capture the binary logs: https://github.com/dotnet/aspnetcore/wiki/MSBuild-logging

By the way, your logs suggest that the build took a lot less than the time you listed:

```
1>Project Performance Summary:
1>     3735 ms  C:\Users\lespi\OneDrive\Documents\MA\VS\Projects\Core31\mycemetery31\mycemetery31\mycemetery31.csproj   1 calls
```
