### ISSUE TITLE
WebAssemblyHostBuilder.Configuration Move CreateDefault

### ISSUE THREAD

**Issue by geffzhang** [dotnet/aspnetcore#21180]
I'm trying to integrate Blazor's latest configuration API into the Abp framework and find it doesn't work, I've looked at the configuration code for the latest WebAssemblyHostBuilder, registered IConfiguration code https://github.com/dotnet/aspnetcore/blob/blazor-m/wasrc/components/webAssembly/WebAssembly/src/host/WebAssemblyBuilder.17 https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs#L338

My test code is here.： https://github.com/BlazorHub/ant-design-blazor/blob/abp/site/AntBlazor.Docs.Wasm/Program.cs

When I put this code comment, I can't work
https://github.com/BlazorHub/ant-design-blazor/blob/abp/site/AntBlazor.Docs.Wasm/Program.cs#L34

https://github.com/abpframework/abp/issues/394

Here we have to believe in how to integrate abp and blazor webassembly

**Comment by javiercn** [comment]
@geffzhang thanks for contacting us.

We'll look into this issue and update accordingly.

**Comment by davidfowl** [comment]
Why are you making a new configuration builder?

**Comment by geffzhang** [comment]
This is  abp configuration use configuration builder， before blazor preview 5 have not configuration builder，so I make a new configuration builder

**Comment by davidfowl** [comment]
builder.Configuration is a `ConfigurationBuilder` already so you don't need to create one.

**Comment by captainsafia** [comment]
As @davidfowl, the `WebAssemblyHostConfiguration` implements the interface of an IConfigurationBuilder and an IConfiguration object. As you mentioned, the IConfiguration service is also already registered in the DI.

Your code sample should looks as follows. You can use the existing ConfigurationBuilder without needing to create a new one.

```csharp
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("app");

builder.Configuration.AddJsonStream(stream);
```

The [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1) have more info on recommended patterns for using the configuration interface.

Give it a try and re-open the issue with a repro project if you run into any issues.
