### ISSUE TITLE
Antiforgery with Origin header

### ISSUE THREAD

**Issue by kanadaj** [dotnet/aspnetcore#21194]
### Is your feature request related to a problem? Please describe.

We have been having a long-term issue where users in certain situations are having problems submitting forms. The reason can be any number of things, from navigating on multiple tabs to mobile browsers and privacy extensions erasing cookies between GET and POST.

The main issue is that communicating this to end-users is _very_ difficult, so we have been considering ways to get around the issue. 

### Describe the solution you'd like

I reckon having the option to check the Origin header first and fall back to cookie validation if the Origin header is not present could be a possible solution. Sadly I am unfamiliar whether this would have any serious security implications, but if this is a reliable checking mechanism, it would be nice to see this as a configurable part of the framework.

I assume this can be implemented by implementing `IAntiforgery` or some such, but as a security-side feature this feels like something the framework itself should provide if it's viable.

**Comment by blowdart** [comment]
Origin can easily be faked or changed, just like referrer. It's not a security mechanism and this isn't suitable for CSRF protection.

**Comment by kanadaj** [comment]
@blowdart But then why is it part of the OWASP CSRF cheat sheet? https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#verifying-origin-with-standard-headers

Isn't Origin a forbidden header only alterable by the browser?

**Comment by blowdart** [comment]
You're relying on browser protection at that point, and that has proved problematic in the past. Also, browser extensions exist to mess with requests.

**Comment by kanadaj** [comment]
If a browser extension messes with the Origin header, that's not really scope of CSRF, is it?

**Comment by blowdart** [comment]
True, but we tend to be paranoid. The other problem is we can't make it unique per user, so shared applications on a shared domain is going to be able to stomp all over tokens meant for other sites.

**Comment by kanadaj** [comment]
So, if we assume that domain-sharing is a non-concern, and we're not a company handling money (if we were, I would probably add even more security, not try to reduce UX impact of the existing security), would something like this work?
```cs
        public async Task ValidateRequestAsync(HttpContext httpContext)
        {
            if (CheckOriginHeaders(httpContext))
            {
                return;
            }

            // Fallback to DefaultAntiforgery
            await _internalAntiforgery.ValidateRequestAsync(httpContext);
        }

        private bool CheckOriginHeaders(HttpContext httpContext)
        {
            if (httpContext.Request.IsHttps && (httpContext.Request.Headers.ContainsKey(HeaderNames.Origin) || httpContext.Request.Headers.ContainsKey(HeaderNames.Referer)))
            {
                var ub = new UriBuilder {Host = httpContext.Request.Host.Value, Scheme = "https"};
                var hostname = ub.ToString();
                if (httpContext.Request.Headers.ContainsKey(HeaderNames.Origin) && httpContext.Request.Headers[HeaderNames.Origin].ToString() == hostname)
                {
                    return true;
                }

                if (httpContext.Request.Headers.ContainsKey(HeaderNames.Referer) && (httpContext.Request.Headers[HeaderNames.Referer] + "/").StartsWith(hostname + "/"))
                {
                    return true;
                }
            }

            return false;
        }
```
with the only potential attack vector opened in this case being a browser somehow not protecting the Origin and Referer headers, correct?

The reason I'm even bothering is that we're seeing a fairly high number of antiforgery errors from legitimate users and get regular complaints, especially from mobile users. And as much as I prefer handling things securely, it's not a good user experience to run up against random errors even the developers can't quite explain, which seems to often lead to losing the content of massive forms...

**Comment by anurse** [comment]
Triage: Anti-forgery is an MVC concept so routing to `area-mvc`.

**Comment by blowdart** [comment]
@pranavkm As anti-forgery is a service can users just replace it and write their own easily?

**Comment by pranavkm** [comment]
> As anti-forgery is a service can users just replace it and write their own easily?

Yes. Going by the sample listed here: https://github.com/dotnet/aspnetcore/issues/21194#issuecomment-619653661, you could consider using a DI provider such as StructureMap to write an implementation that wraps ASP.NET Core's default implementation.
