### ISSUE TITLE
Razor Directive Attributes don't have documentation

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#21192]
With LSP preview switch on we get this when hovering:
![OnClickDirectiveNoDocumentation](https://user-images.githubusercontent.com/14987221/80253198-ab12ae80-862d-11ea-9903-68dc03883f2e.png)
In current LSP preview switch off we get:
![OnClickDirectiveWithDocumentation](https://user-images.githubusercontent.com/14987221/80253226-bc5bbb00-862d-11ea-956e-5ed37d185f65.png)
Let's try to get that documentation back in there.

**Comment by TanayParikh** [comment]
With the LSP preview switch off, the document gets treated as C#. As such we get rich C# hover support.

With the LSP preview switch on, we use the WTE hover support which provides us with the hover string as seen due to some other limitations with how VS processes markdown (we can't seem to be passing in markdown for the moment).

**Comment by TanayParikh** [comment]
@NTaylorMullen should this be moved to the backlog?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen should this be moved to the backlog?

I'm not sure quite yet. We're the ones who provide the hover info for the `EventCallback<Microsoft.AspNetCore.Components.Web.MouseEventArgs> EventHandlers.onclick`. That's typically derived from associated TagHelpers which harvest C# documentation.

Aka, when you hover over `@onclick` you should see this return data: https://github.com/dotnet/aspnetcore-tooling/blob/d6ab71d1973b98ff29c8cf9e4d0021addaa4b969/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs#L98

Problem is that data doesn't look to be capturing the docs for whatever reason.

**Comment by TanayParikh** [comment]
![image](https://user-images.githubusercontent.com/14852843/81119457-a7114700-8edf-11ea-963a-8a382ec177f0.png)

with the LSP preview switch on. I believe this is resolved. @ryanbrandenburg are you still seeing this?

**Comment by ryanbrandenburg** [comment]
That completion is definitely not coming from the LSP because it gets coloration. Maybe you need to close and re-open your document after turning the switch on?

**Comment by ryanbrandenburg** [comment]
Tested again on LSP:
![image](https://user-images.githubusercontent.com/14987221/81121872-90b9ba00-8ee4-11ea-8aeb-de35b8180b2f.png)
