### ISSUE TITLE
Blazor UserManager not supported, use case hole

### ISSUE THREAD

**Issue by bdnts** [dotnet/aspnetcore#21199]
### Describe the bug
More of an architecture conundrum than a bug.  
`UserManager` plus `SignInManager` are not officially supported in Razor Components (Blazor)
(https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1#authenticationstateprovider-service)  Expectation is to use `AuthenticationStateProvider`, `AuthorizeView`, etc.  This leaves a hole working with user accounts that are Signed Up, but not yet capable of Signing In, therefore cannot be authenticated and manipulated with AuthenticationStateProvider.

### To Reproduce
The use case is a simple registration flow, where email confirmation is required prior to SignIn.
A User can be in a registered state where they have Signed Up (lets say state 1), and confirmation email has been sent (state 2). Once confirmed, (state 3) Authentication is possible. While EmailConfirmed tracks that status in the Identity database, a RegistrationState Claim tracks overall progress (states 1-6).

A User in state 1 or 2 cannot sign in, and therefore is not accessible to AuthenticationStateProvider (because there is no current user). Only via UserManager, can the unauthenticated User information be retrieved (e.g. `UserManager.IsEmailConfirmedAsync()`, or RegistrationState claim [`UserManager.GetClaimsAsync()` etc.]) retrieved.  But `UserManager` isn't a supported approach (even though it works, for now.) Hence the conundrum.

Have I missed something, like

`var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync(TUser);`

?

**Comment by javiercn** [comment]
@bdnts thanks for contacting us.

Identity uses cookies and cookies require an HTTP response to be set. That makes this impossible to use with Blazor by definition. We don't recommend you implement your authentication UI using Blazor. For the pieces that require setting up a context the recommendation is to use MVC/Razor pages.

This is not something Blazor can/will solve. Identity is simply designed to work with traditional (server rendered) web applications and I don't think there's anything you can do about it if you are using cookies.
