### ISSUE TITLE
Restore Failed  from Source !

### ISSUE THREAD

**Issue by xiaguoli** [dotnet/aspnetcore#21207]
PS D:\Demo\aspnetcore> .\restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
Detected JDK in C:\Program Files\Java\jdk1.8.0_171 (via JAVA_HOME)
  C:\Users\xiagl\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20113.5\tools\Tools.proj 的还原在 377.25 ms 内完成。
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.3-servicing.20128.1/dotnet-runtime-3.1.3-servicing.20128.1-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.3-servicing.20128.1/dotnet-runtime-3.1.3-servicing.20128.1-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\Demo\aspnetcore\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.3-servicing.20128.1/dotnet-runtime-3.1.3-servicing.20128.1-win-x86.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.3-servicing.20128.1/dotnet-runtime-3.1.3-servicing.20128.1-win-x86.zip
dotnet-install: Adding to current process PATH: "D:\Demo\aspnetcore\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/aff82b2b-3c67-4d3f-8504-776219f3
  5de3/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1f72b231-60b4-423b-b5da-c82c45fa
  300b/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/84bde8d9-43d8-496f-8aaf-0b7be50c
  5430/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/de31b826-4bf4-4124-b6ba-e5af8f43
  c5e5/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1c64d2ed-4ebf-4497-ad63-5ea9ac77
  c815/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/cfc4da92-5a15-4edf-9c35-5246483c
  232b/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c9
  14a8/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/89836ee7-f4d9-4429-90a9-9e900578
  0b57/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9c2ea29a-00e0-4bae-b470-161fdab1
  f360/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9a659244-f0ba-4045-afa2-47be56f3
  b48b/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/aff82b2b-3c67-4d3f-8504-776219f3
  5de3/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1f72b231-60b4-423b-b5da-c82c45fa
  300b/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/84bde8d9-43d8-496f-8aaf-0b7be50c
  5430/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1c64d2ed-4ebf-4497-ad63-5ea9ac77
  c815/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/cfc4da92-5a15-4edf-9c35-5246483c
  232b/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/de31b826-4bf4-4124-b6ba-e5af8f43
  c5e5/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.internal.extensions.refs/index.json”重
  试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/89836ee7-f4d9-4429-90a9-9e900578
  0b57/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/aff82b2b-3c67-4d3f-8504-776219f3
  5de3/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1f72b231-60b4-423b-b5da-c82c45fa
  300b/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1c64d2ed-4ebf-4497-ad63-5ea9ac77
  c815/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microbuild.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.genapi/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  未能从“https://api.nuget.org/v3-flatcontainer/nuget.build.tasks/5.3.0/nuget.build.tasks.5.3.0.nupkg”下载包“NuGet.Build.Task
  s.5.3.0”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  未能从“https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencymodel/2.1.0/microsoft.extensions.dependency
  model.2.1.0.nupkg”下载包“Microsoft.Extensions.DependencyModel.2.1.0”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/wix/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.sourcelink.vsts.git/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers.toolset/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/internal.aspnetcore.buildtasks/index.json”重试“FindPackagesByIdAsync” 。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build.framework/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build.tasks.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync” 。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/84bde8d9-43d8-496f-8aaf-0b7be50c
  5430/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/de31b826-4bf4-4124-b6ba-e5af8f43
  c5e5/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1c64d2ed-4ebf-4497-ad63-5ea9ac77
  c815/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/cfc4da92-5a15-4edf-9c35-5246483c
  232b/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c9
  14a8/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/89836ee7-f4d9-4429-90a9-9e900578
  0b57/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9c2ea29a-00e0-4bae-b470-161fdab1
  f360/nuget/v3/flat2/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9a659244-f0ba-4045-afa2-47be56f3
  b48b/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/aff82b2b-3c67-4d3f-8504-776219f3
  5de3/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1f72b231-60b4-423b-b5da-c82c45fa
  300b/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/84bde8d9-43d8-496f-8aaf-0b7be50c
  5430/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1c64d2ed-4ebf-4497-ad63-5ea9ac77
  c815/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c9
  14a8/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9c2ea29a-00e0-4bae-b470-161fdab1
  f360/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/cfc4da92-5a15-4edf-9c35-5246483c
  232b/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/de31b826-4bf4-4124-b6ba-e5af8f43
  c5e5/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.internal.extensions.refs/index.json”重
  试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/89836ee7-f4d9-4429-90a9-9e900578
  0b57/nuget/v3/flat2/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/aff82b2b-3c67-4d3f-8504-776219f3
  5de3/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  未能从“https://api.nuget.org/v3-flatcontainer/nuget.build.tasks/5.3.0/nuget.build.tasks.5.3.0.nupkg”下载包“NuGet.Build.Task
  s.5.3.0”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.dotnet.genapi/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  未能从“https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencymodel/2.1.0/microsoft.extensions.dependency
  model.2.1.0.nupkg”下载包“Microsoft.Extensions.DependencyModel.2.1.0”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/wix/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.sourcelink.vsts.git/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.net.compilers.toolset/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/internal.aspnetcore.buildtasks/index.json”重试“FindPackagesByIdAsync” 。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microbuild.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build.framework/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build.utilities.core/index.json”重试“FindPackagesByIdAsync” 。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.build.tasks.core/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://api.nuget.org/v3-flatcontainer/microsoft.internal.extensions.refs/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c9
  14a8/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  对源“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9c2ea29a-00e0-4bae-b470-161fdab1
  f360/nuget/v3/flat2/microsoft.dotnet.platformabstractions/index.json”重试“FindPackagesByIdAsync”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
  未能从“https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/9c2ea29a-00e0-4bae-b470-161fdab
  1f360/nuget/v3/flat2/microsoft.internal.extensions.refs/3.1.0-rtm.19565.4/microsoft.internal.extensions.refs.3.1.0-rt
  m.19565.4.nupkg”下载包“Microsoft.Internal.Extensions.Refs.3.1.0-rtm.19565.4”。
  发送请求时出错。
    远程服务器返回错误: (503) 服务器不可用。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(124,5): error : 未能从“https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencymodel/2.1.0/microsoft.exte
nsions.dependencymodel.2.1.0.nupkg”下载包“Microsoft.Extensions.DependencyModel.2.1.0”。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(124,5): error : 发送请求时出错。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(124,5): error :   远程服务器返回错误: (503) 服务器不可用。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(124,5): error : 未能从远程源“https://api.nuget.org/v3-flatcontainer/wix/index.json”检索有关“Wix”的信息。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(124,5): error :   发送请求时出错。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(124,5): error :   远程服务器返回错误: (503) 服务器不可用。
Build failed.

**Comment by xiaguoli** [comment]
git tag v3.1.3

**Comment by dougbu** [comment]
Tags for security releases or other internal builds are rarely buildable. We're tracking the possibility of adding tags without internal-only feeds for 2.1 in #24119. If / when we do that, it should be easier to do something similar for 3.1 and later.

But, in general, we recommend building the `release/*` branches (release/3.1 in this case) and not individual tags. The tags are primarily to track what we released.
