### ISSUE TITLE
[Blazor] Javascript file did not updated automatically after publishing app new version

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#21205]
Hello,

 I am hosting blazor webassembly app on azure storage static website.

 I made some changes in c# side and in javascript interop file.

 Published app and browsed it with chrome, app got updated automatically as expected (some new version changes was applied) but javascript file was same in sources.

 After hard reload js file updated too and everything works well now.

 I can't tell all my users to make hard reload and they do not know when I publish new versions, so this is problem.

 Is there any way browser to get notified that old js files should be removed and new downloaded?

Thank you.

**Comment by javiercn** [comment]
@Lupusa87 thanks for contacting us.

This is out of Blazor's control and is something that you need to handle with whatever hosting you are using. This is "standard" HTTP caching techniques:
* Use ETags when serving the files
* Set a proper cache header when returning the JS responses.

Other than that if you need something like this, I can thing of a couple alternative strategies:
* Take control of the resource loading with your own service worker. That way you can set the fetch cache options to always force updating the resource.
* Download and insert the script on the page dynamically yourself.

**Comment by Lupusa87** [comment]
@javiercn Thank you, will follow your advices.
