### ISSUE TITLE
CLI does not set TFM net5.0 in .csproj

### ISSUE THREAD

**Issue by VARUN46** [dotnet/aspnetcore#21206]
### Describe the bug
When I Create a new application from Dotnet CLI the .csproj does not show correct TFM in .NET 5 Preview 3

### To Reproduce
Create A New Project using CLI, 
    dotnet new mvc -o WebApp5.Mvc -f netcoreapp5
Open .csproj
  ```
<PropertyGroup>
    <TargetFramework>netcoreapp5.0</TargetFramework>
  </PropertyGroup>
```

dotnet run

Additional Details:
Change To This:
```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
</PropertyGroup>

```
dotnet run

Both works correctly!!

### Further technical details
- ASP.NET Core version : 5.0.100-preview.3.20216.6 
- Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.3.20216.6
 Commit:    9f62a32109

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/setia/dotnet/sdk/5.0.100-preview.3.20216.6/

Host (useful for support):
  Version: 5.0.0-preview.3.20214.6
  Commit:  b037784658

.NET SDKs installed:
  3.1.201 [/home/setia/dotnet/sdk]
  5.0.100-preview.3.20216.6 [/home/setia/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/home/setia/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20215.14 [/home/setia/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/home/setia/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20214.6 [/home/setia/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version : VS Code 1.44.2 on Ubuntu

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is already being handled as part of https://github.com/dotnet/aspnetcore/pull/20748
