### ISSUE TITLE
Low performance under IIS

### ISSUE THREAD

**Issue by gurry** [dotnet/aspnetcore#21214]
### Description of the bug
For a certain URL scheme Asp.Net Core Web API application runs slow when hosted under IIS
### To Reproduce
1. Create a bare bones Asp.Net Core 3.1 Web API application with a single controller and single action method as shown below:
```C#
    [ApiController]
    [Route("[controller]")]
    public class TestController : ControllerBase
    {
        [HttpGet("{id}")]
        public ActionResult<int> Get(long id)
        {
            return 1;
        }
    }
```
As shown above the route for the method should be set up to receive GET requests for the URL `/test/<id>` where `id` is an integer.

2. Host this application in IIS
3. Set up perfmon on the server with the following two counters: W3SVC_W3WP(_Total)\Requests/Sec and Web Service Cache\Current URIs Cached
4. Run a load generator to call GET  `/test/<id>` with random `id`s within a small range such as 1 to 100 (i.e. with URLs within the range `/test/1` to `/test/100`). Notice that Requests/Sec counter rises immediately to a very high value and the performance is excellent.
5. Now run the load generator again with a bigger `id` range, such as 1 to 20000 (URLs in the range extending from `/test/1` to `/test/20000`). Notice that Requests/Sec stays low initially and only slowly ramps up to the performance levels in step 4. Also notice that this slow ramp-up correlates precisely with a slow ramp-up of the Current URIs Cached counter:
![Capture](https://user-images.githubusercontent.com/1068853/80296731-11690f80-879b-11ea-8acc-c9cb7cab873b.PNG)
Requests/Sec does not reach its full level until Current URIs Cached is as big as the size of the `id` range, i.e. until all the unique URIs sent by the load generator have been cached by IIS.
6. Run the same application under Kestrel and run the same tests. You see no slow ramp-up.

It appears that IIS's Output Caching feature is interfering with the app's performance. It seems to be adding latency to requests in order to cache all the unique URIs it sees. I have tried resolving the problem by turning off Output Caching both via web.config and IIS Manager UI, at the app level, website level as well as at the web server level, but the URI caching behaviour refuses to go away.

1. Is my conclusion that the issue is due to IIS Output Caching correct? Or is it a bug in an Asp.Net Core component such as the ANCM?
2. What is the right solution to this problem? 

### Further technical details
- ASP.NET Core version: 3.1.1
- Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- IDE: Visual Studio 2019 (16.4.4)
- IIS version: 10.0.14393.0

### Edit
By the statement "You see no slow ramp-up" for Kestrel above I mean to say that Kestrel immediately reaches a very high RPS rate as opposed to IIS which grows very slowly.

**Comment by anurse** [comment]
> 1. Is my conclusion that the issue is due to IIS Output Caching correct? Or is it a bug in an Asp.Net Core component such as the ANCM?

I expect it is indeed the reason your RPS increases. The lower RPS values are probably the more accurate uncached values. Kestrel doesn't do any built-in caching, so it won't exhibit the same behavior.

> 2\. What is the right solution to this problem?

I don't have a specific answer for you. It depends on the needs of your app.

**Comment by gurry** [comment]
Hi @anurse. 

Kestrel RPS jumps immediately to a high level as compared to IIS where it starts much lower and only slowly grows to the same level as Kestrel. So IIS's URI caching behaviour is not helping performance but hurting it. Sorry for not stating this explicitly.

I also want to add that this issue is not limited to GET requests, it also occurs with write requests like PATCH as long as you keep the URL scheme the same.

**Comment by benaadams** [comment]
Is this IIS on a dev machine or on a Window Server?

**Comment by anurse** [comment]
Well, IIS and Kestrel are completely different servers. It’s certainly possible that in your scenario IIS has a lower baseline RPS and the caching is what’s bringing it up to similar performance.

Having said that, the fact that non-GET requests experience the same curve **does** give us more to go on there. Those shouldn’t be cacheable.

If the issue is with IIS’s caching module though we’ll likely need to redirect to that team for further investigation.

**Comment by gurry** [comment]
@benaadams IIS is running on a Windows Server not a dev machine. The OS details are:
```
OS Name: Microsoft Windows Server 2016 Datacenter
OS Version: 10.0.14393 N/A Build 14393
```

@anurse My actual use case where I first saw the problem is a Web app receiving PATCH requests on a large variety of URLs with the same URL structure as above and updating corresponding rows in a DB.  Since every request goes to the DB, and IIS eventually is able to ramp up as high as Kestrel, IIS's baseline RPS can't be low.

The reason I provided the GET example above instead of PATCH was only because I felt that it is simpler to replicate, but I can see that it was misleading. I should've given a PATCH example.

**Comment by gurry** [comment]
@anurse @Tratcher Any update on this? If you guys can provide even some pointers about how to work around this problem, that'll be great. I'll also be happy to contribute code if a code change is required for the fix. 

The reason a solution to this problem is important to us is that we're migrating one of our core services from Asp.Net to Asp.Net Core for performance and this has become a significant blocker for that effort, delaying our ship date.

**Comment by shirhatti** [comment]
@gurry Couple of questions for you:

1. How are you measuring/observing the ramp up for Kestrel? Given that we don't have perfmon I wonder if the comparisons are indeed fair?

2. If I understood correctly, your hypothesis is that these requests are so incredibly naive that's is cheaper to serve than do a cache retrieval? If so, can you share the configuration you used to disable caching? (You may want to take a look at [tuning IIS](https://docs.microsoft.com/windows-server/administration/performance-tuning/role/web-server/tuning-iis-10)).
If possible, can you also collect FREB traces from your IIS hosted application (ideally a cold request trace and a warm request trace)? I'd be curious to see what's happening and where the execution time is being spent.

cc @bangbingsyb @jkotalik

**Comment by gurry** [comment]
Hi @shirhatti.

For Kestrel I measured the RPS on the client-side. My load generator client prints the current average RPS on the console as it sends requests. In the case of Kestrel that number jumps up immediately, but for the IIS-hosted app it stays low initially, which is also confirmed by perfmon running on the server-side.

> If I understood correctly, your hypothesis is that these requests are so incredibly naive that's is cheaper to serve than do a cache retrieval?

My use case is not GET requests actually, but PATCH requests. I gave the example of GET in my original post above only because I thought it'll be simpler, but I now realize it would've been clearer to use a PATCH example. So sorry for that. 

Given it's a PATCH request, IIS should not even be trying to do any caching, but it seems to be doing precisely that and wastes time in the process. The problem gets exacerbated due to the large diversity of URLs I"m sending (the `<id>` at the end keeps changing for every request). If I were calling the exact same URL every time it would've cached it only once and perhaps the problem wouldn't even have been noticeable, 

I reached the conclusion that IIS URL caching or output caching is to blame based purely on the Web Service Cache\Current URIs Cached perform counter. As you can see in the perfmon screenshot above, Current URIs Cached correlates perfectly with the ramp-up in RPS.

Note the it's not the cache _retrieval_ that's the cause of the problem, but requests getting _stored_ in the cache. At least that's what the name of the perfmon counter suggests. 

About disabling the cache, the way I did that is:

-  using the "Output Caching" setting for my web application in the IIS Manager as shown here:
![image](https://user-images.githubusercontent.com/1068853/83703355-f0fb6300-a62c-11ea-848e-5597c1df18a8.png)
- by setting `enabled="false"` under `<caching>` element in my `web.config`

Neither of them had any effect.

Thank you for the Tuning IIS link. I'll certain take a look and experiment with it. I'll also collect the FREB traces and get back to you.

I'm getting a sense you guys did not manage to reproduce the problem. Which tells me that I'm certainly doing something dumb. Had this been a real bug in IIS it'd have been so evident anyway that it would've been found long ago and fixed by now. So I hope that through this discussion and from your suggestions, I'll be able to find my mistake. 

That said, I still wonder why IIS is trying to cache URLs for PATCH requests. Even if it were not the cause of the problem, it would still be surprising behaviour.

Thank you for the help :).
