### ISSUE TITLE
Add support for `visibility` directive

### ISSUE THREAD

**Issue by mkArtak** [dotnet/aspnetcore#21211]
As a component library writer I want to make sure certain components stay internal to my library and can't be instantiated. It would be nice to be able to add `@visibility internal` at the top of my razor component.

For components, which are defined in `.cs` files only (like classes which derive from existing components), it's easy to do this.

Thinking some more about this, I'm not sure support for all the visibility attributes actually makes sense. I think `internal` is the only one which would be useful. That said, maybe `@internal` is a better option to go with:

```razor
@internal

@code {

}
```

**Comment by javiercn** [comment]
I think the discussion here is about public vs non-public.

I personally fail to see the value in allowing this, specially considering the drawbacks this has in terms of performance and complexity. Most/all of the primitives that we have in ASP.NET Core for doing things like this are required to be public (controllers and so on) and forcing to search through all the non-exported types has serious drawbacks (more types to scan/load) and increases the chances of mistakes in linking/assembly load causing a catastrophic app failure.

I guess the main value of this is that you can have "non-public" components, and that is most useful when you are writing a component library (an even then I can argue it's usefulness) but I don't think  this is something worth having when you are building an app.

It might seem a simple change, but this has ramifications in how we do reflection all over the framework and I don't think we've received (enough/any) feedback around it.
