### ISSUE TITLE
HtmlHelper is using ModelExpressionProvider instead of IModelExpressionProvider

### ISSUE THREAD

**Issue by hikalkan** [dotnet/aspnetcore#21219]
HtmlHelper is using `ModelExpressionProvider` ([see](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.ViewFeatures/src/HtmlHelperOfT.cs#L18)). But there is a [IModelExpressionProvider](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.ViewFeatures/src/IModelExpressionProvider.cs) interface you know. Is this a bug or by design?

It also uses [_modelExpressionProvider.GetExpressionText()](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.ViewFeatures/src/HtmlHelperOfT.cs#L378) method which is not available on the `IModelExpressionProvider` interface. Maybe that's the reason it is not injecting the interface. Would it be better to include this method to the interface?

I am asking because I want to replace/override `ModelExpressionProvider` but can not do it properly because of this.

Thanks.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen can you please look into this? Thanks!

**Comment by pranavkm** [comment]
> I am asking because I want to replace/override ModelExpressionProvider but can not do it properly because of this.

Can you elaborate on why you would need to do this?

**Comment by pranavkm** [comment]
As for your original question, adding an API to an interface is a breaking change. We intentionally chose not to break it when we added additional features to `ModelExpressionProvider`. We could consider making methods on it virtual, but it's a fairly low level type that we do not expect users to replace.

**Comment by hikalkan** [comment]
What I was trying to is that: AspNet Core Razor Page input tag helper doesn't support unobtrusive validation attributes when I use like `asp-for="MyCustomProperties["Prop1"]"`. MyCustomProperties is a `Dictionary<string,object>` here, so it can not get data annotation validation attributes for the Prop1 since it is not a typical class property, but only a value in a dictionary. However, I have a custom extension system and I can know "Prop1" validation attributes/rules and I want provide these attributes/rules to the tag helper so it can property generate the html attributes for the validation rules. That's not easy, I almost investigated all the related source code in the AspNet Core to find some extension points (by overriding some services). ModelExpressionProvider was one of them.

Anyway, I finally did it by replacing the AbpValidationHtmlAttributeProvider service ([see my implementation](https://github.com/abpframework/abp/blob/extra-properties/framework/src/Volo.Abp.AspNetCore.Mvc/Volo/Abp/AspNetCore/Mvc/ViewFeatures/AbpValidationHtmlAttributeProvider.cs#L48))

However, I still think if there is an interface defined for the `IModelExpressionProvider`, other services should use it. Using the concrete implementation from some classes is not a good practice. "adding an API to an interface is a breaking change" is not a breaking change normally, however your breaking change rule may be more sensitive, OK.

Thank you for your time.

**Comment by pranavkm** [comment]
Thanks for the explanation @hikalkan. MVC has a few places where an interface is substituted by an abstract class, It's a much easier sell to add APIs to the class versus make a breaking to an interface. If you think you still need to override the behavior of `ModelExpressionProvider`, we would consider a PR to make methods on it `virtual`. However, looks like you have a working solution (that looks fairly correct), so we could consider this issue resolved.

**Comment by hikalkan** [comment]
Thank you for your time @pranavkm you can close this :)
