### ISSUE TITLE
asp-action behave differently between ASP.NET Core 2.2 and 3.1 when Action Method has Async suffix

### ISSUE THREAD

**Issue by TheBlueSky** [dotnet/aspnetcore#21216]
While upgrading an application from ASP.NET Core 2.2 to 3.1 I noticed that `asp-action` TagHelper behave differently in these versions.

I am not sure this is intentional or not, or whether it was announced as a breaking change or not. Also, not sure if [this issue](https://github.com/dotnet/aspnetcore/issues/19927) is talking about the same thing or not; in my case, the link is not generated at all.

### Describe the bug
In ASP.NET Core 2.2, when using the Action Method name with `asp-action` TagHelper, the link is generated as expected. However, in ASP.NET Core 3.1, no link is generated if the Action Method has Async suffix.

For more details, see "To Reproduce" section.

### To Reproduce
1. Create an ASP.NET Core 2.2 Razor Pages application.
2. Add the Controller code; see Controller code below.
3. Add a link in Index.cshtml; see HTML code below.
4. Run the application and see that the link is generated correctly for `/Account/Logout`.

``` C#
// Controller code
public sealed class AccountController : Controller
{
    [Route("/Logout")]
    public async Task<IActionResult> LogoutAsync()
    {
        await this.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

        return this.RedirectToPage(ApplicationConstants.IndexPage);
    }
}
```
``` HTML
<!-- HTML code -->
<a asp-controller="Account" asp-action="LogoutAsync">Logout</a>
```

Repeat the same steps, but now create an ASP.NET Core 3.1. Run the application and see that there is no link generated and the rendered anchor tag is:

``` HTML
<a href="">Logout</a>
```

Lastly, remove `Async` from `asp-action` TagHelper:

``` HTML
<!-- HTML code -->
<a asp-controller="Account" asp-action="Logout">Logout</a>
```

Run the application and see that the link is generated as expected.

**Comment by pranavkm** [comment]
@TheBlueSky see https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#async-suffix-removal-from-controller-action-names, https://github.com/dotnet/docs/issues/14716

**Comment by TheBlueSky** [comment]
Thanks, Pranav; I should have completed the document until the end I guess :p
