### ISSUE TITLE
[Blazor] Button not firing when a page parameter is set

### ISSUE THREAD

**Issue by clintnetwork** [dotnet/aspnetcore#21212]
Hey,

I do not succeed to make a simple onclick to a button when a page parameter is set!

I have a bit snippet:

This does not work:
---
```razor
@page "/test/{Id:guid}"

<button class="btn btn-sm btn-secondary" @onclick="MakeTest">Test</button>

@code {
    [Parameter]
    public Guid Id { get; set; }

    private void MakeTest()
    {
        Console.WriteLine("Test");
    }
}
```

But this is work:
---
```razor
@page "/test"

<button class="btn btn-sm btn-secondary" @onclick="MakeTest">Test</button>

@code {
    private void MakeTest()
    {
        Console.WriteLine("Test");
    }
}
```

Incredible!

PS: using blazer server not wasm version

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
