### ISSUE TITLE
JavaScript InterOp Error when calling Javascript or Blazored.LocalStorage functions from OnInitializedAsync

### ISSUE THREAD

**Issue by educielo** [dotnet/aspnetcore#21217]
### Describe the bug
I am following a sample app from the NDC Oslo which is this app: https://github.com/SteveSandersonMS/presentation-2019-06-NDCOslo/tree/master/demos/MissionControl. I am doing a Server Side blazor and im following how the Jwt token is being implemented from this. 
I am calling an rest endpoint from OnInitializedAsync which needs getting the token from the local storage. The code to get the token throws the error below:

**JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.**

### To Reproduce

1. Create a new SSB project
2. Implement the **TokenAuthenticationStateProvider: AuthenticationStateProvider** from NDC Oslo resource
3. Login using a component and save the token
4. Call GetTokenAsync from OnInitializedAsync

**Exception Message:** JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- ASP.NET Core version: 3.1

**Comment by javiercn** [comment]
@educielo thanks for contacting us.

That's by design. The only place where it is safe to make JS Interop calls is from within OnAfterRender async. OnInitializedAsync can not be able to make JS calls when the app is for example pre-rendered. I suggest you move whatever call you need to OnAfterRenderAsync or change the way the component is rendered to avoid using JS interop during OnInitializedAsync

**Comment by educielo** [comment]
Thanks for the feedback absolutely right. But how would be the proper way to do the authorization since it also needs to check for local storage

**Comment by javiercn** [comment]
@educielo consider skipping pre-rendering for paths that require authorization? Otherwise you need to implement it in a different way for pre-rendering paths. You can't send JS interop calls before connected to the browser, there's no way around it.
