### ISSUE TITLE
Navigation bug when @page directive contains subfolder(s) and parameter(s)

### ISSUE THREAD

**Issue by Bronzato1** [dotnet/aspnetcore#21229]
### Describe the bug

I'm working on a Blazor WebAssembly project in Visual Studio Professional Preview Version 16.6.0 Preview 4.0.

It seems that when a @page directive contains both subfolder(s) and parameter(s) there is a bug when navigating to another page with @page directive containing a subfolder.

### To Reproduce

Let's create 2 pages:

####  \Pages\Firstpage.razor

@page "/myfolder/firstpage/{id:int}"
@code
{
    [Parameter]
    public int Id { get; set; }
}
This is firstpage
Link: <a href="/myfolder/secondpage">Goto secondpage</a>

####  \Pages\Secondpage.razor

@page "/myfolder/secondpage"

This is secondpage
Link: <a href="/myfolder/firstpage/2">Goto firstpage</a>
____________________________

First I navigate to /myfolder/firstpage/2. Then if I navigate to /myfolder/secondpage, I never reached this url and I got the error below:

![image](https://user-images.githubusercontent.com/13705487/80348333-ee5b6000-886d-11ea-89dc-3f50b9841133.png)

Remark 1: the bug is present if pages are physically located inside a subfolder or not. I mean I tested when pages are inside \Pages\Myfolder\Firstpage.razor or \Pages\Firstpage.razor independently the fact that @page directive contains subfolder like explained. 
 
Remark 2: there is no more problem if I remove the subfolder /myfolder/ inside the @page directive.

Remark 3: there is no more problem if I remove the parameter {id:int} inside the @page directive.

So the problem seems to be present when mixing both subfolder and parameter. Hope I'm clear.

### Further technical details

- ASP.NET Core version 3.1.3

- Include the output of `dotnet --info`

C:\Users\t_lan>dotnet --info
SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.300-preview-015115
 Commit:    cd8d468337

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015115\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Visual Studio Professional Preview Version 16.6.0 Preview 4.0.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @Bronzato1.

I attempted to reproduce this issue on preview5 and was not able to. Can you verify if you are able to reproduce this on the latest preview version?

Also, it would be helpful to share a project as a repro, in case there is something else impacting this that is not included in the bug report above.

**Comment by Bronzato1** [comment]
Ok, my apologies. I finally found the problem. Unfortunately I removed the instruction **base href** inside the **head** section of my **index.html** file.

`<base href="/" />`

So the problem was on my side. Please can you please close this issue.

**Comment by captainsafia** [comment]
Glad you resolved the issue. Happy coding!
