### ISSUE TITLE
Html.EditorFor(m => m.Form) won't find a correct EditorTemplate view if m.Form is property of abstract type

### ISSUE THREAD

**Issue by levdimov** [dotnet/aspnetcore#21228]
### Describe the bug
`Html.EditorFor(m => m.Model)` won't find a correct EditorTemplate view if `m.Model` is property of abstract type.

### To Reproduce
Let's have a view model which have a property of abstract type.
```csharp
public class ViewModel
{
    public FormModelBase Form {get; set;}
}
```

There are several classes that inherit from `FormModelBase` (`FormModelA`, `FormModelB`). Also there are EditorTemplate views named after those classes (`EditorTemplates/FormModelA.cshtml`, `EditorTemplates/FormModelB.cshtml`).

In a base view (which renders ViewModel object) I would like to render an editor via `Html.EditorFor(m => m.Form)` and expect it to render some of editor templates, depending on actual ViewModel.Form type, but it doesn't.

I did some debugging in ASP.NET Core code and discovered that `TemplateRenderer` is using metadata's `UnderlyingOrModelType`'s names for view discovering, but in this case `UnderlyingOrModelType`s are `FormModelBase` and `object`.

If it can't be fixed (breaking changes or whatever) are there any workarounds?

Thanks.

### Further technical details
- ASP.NET Core 2.1.* nuget packages @ net472

**Comment by levdimov** [comment]
Ok, workaround is pretty simple: just use EditorFor overload with `templateName` property which equals to `Model.Form.GetType().Name`. 

It worked in ASP.NET MVC 4 thus increasing migration difficulty.

**Comment by pranavkm** [comment]
@levdimov changing the implementation might be a difficult now especially given that we haven't had a lot of feedback in this area. In addition, you found one workaround to this. The other alternative would be to use the [UIHintAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.uihintattribute.-ctor?view=netcore-3.1#System_ComponentModel_DataAnnotations_UIHintAttribute__ctor_System_String_) to specify a template name.
