### ISSUE TITLE
The name 'code' does not exist in the current context

### ISSUE THREAD

**Issue by Kurt17P** [dotnet/aspnetcore#21222]
I was working on a Blazor server app, when 'suddenly' the error `CS0103 The name 'code' does not exist in the current context` occured after adding a new Razor page to an existing project via `Add / Razor page`. In VisualStudio the `@code` directive is not recognized and the build fails with the above error. The other pages in the project containing `@code` still compile without error and IntelliSense also recognizes them.

<img width="269" alt="Anmerkung 2020-04-26 225000" src="https://user-images.githubusercontent.com/30809933/80319407-4b282d80-8810-11ea-939b-b6b32c91ad3a.png">

This happens in different projects, even a new Blazor server app. I have restartet Windows and repaired Visual Studio Enterprise 2019.

To my surprise, I just found that adding a file manually (that is without scaffolding), it works. Now that I check, I found that `Microsoft.VisualStudio.Web.CodeGeneration.Design` Package updated from 3.1.1. to 3.1.2, so maybe this caused an error?

I found a previous issue reports that might be similar [here](https://github.com/dotnet/aspnetcore/issues/11347) but their suggestions did not work for me.

`dotnet --info` yields:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the VS Feedback to report this issue, so the team who owns the area can track the ask.
