### ISSUE TITLE
Blazor - creating empty component constructor at runtime and call parameterized constructor

### ISSUE THREAD

**Issue by Daendel** [dotnet/aspnetcore#21235]
Why doesn't Blazor create empty an empty constructor at runtime (so it can render the component) and later calls the parameterized (implemented) constructor using the parameters that are supplied in the HTML-attributes?

This way, no [Parameter]-attribute is needed on properties, they can become get-only and therefore don't have a state anymore.

It makes the whole component implementation way more clean and clear.

**Comment by javiercn** [comment]
@Daendel thanks for contacting us.

Blazor (Razor) just compiles to C#. As such, it can only call a constructor once to initialize a given object (that's how C#/.NET works) and having to call a constructor with a random parameter set makes the implementation way more complex.

Also, parameters in a component can change multiple times, so a constructor is not the right place for them. A component can just implement `IComponent` and the only responsibility there is to implement a very generic `SetParametersAsync` method that is called by the framework when the parameters change.

Only `ComponentBase` respects the `[Parameter]` attribute.
