### ISSUE TITLE
Persisting DataProtection keys to Azure Blob storage not possible from local IIS even when authenticated properly

### ISSUE THREAD

**Issue by DibyodyutiMondal** [dotnet/aspnetcore#21230]
I am trying to persist keys to azure blob storage and protect them with azure key vault. On my **local** setup, I am using IIS (not express). To allow the IIS AppPool to use azure services, i have configured the app pool identity to use my azure login, and in the applcationHost.config, I have used `setProfileEnvironment="true"`. Also, in my app, the first thing I do in ConfigureServices is set default culture to "en-in" (target audience)

I have followed all the relevant documentations from various pages on docs.microsoft.com

Following is the function that I call from ConfigureService() in Startup, to configure the DataProtecton.
```C#
 private void ConfigureDataProtection(IServiceCollection services)
        {
            AzureServiceTokenProvider tp = new AzureServiceTokenProvider();
            string token = tp.GetAccessTokenAsync("https://storage.azure.com/").Result;
            StorageCredentials credentials = new StorageCredentials(new TokenCredential(token));
            CloudStorageAccount storageAccount = new CloudStorageAccount(credentials, Configuration["AzureStorage:AccountName"], Configuration["AzureStorage:EndPoint"], true);
            CloudBlobClient client = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = client.GetContainerReference(Configuration["AzureStorage:Container"]);

            //error happens when executing this line
            container.CreateIfNotExistsAsync().Wait();

            services.AddDataProtection()
                .PersistKeysToAzureBlobStorage(container, "keys.xml")
                .ProtectKeysWithAzureKeyVault
                (
                    new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tp.KeyVaultTokenCallback)),
                    Configuration["AZKVDP"]
                )
                .SetApplicationName(Configuration["AppName"])
                .UseCryptographicAlgorithms(new Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorConfiguration()
                {
                    EncryptionAlgorithm = Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.EncryptionAlgorithm.AES_256_CBC,
                    ValidationAlgorithm = Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ValidationAlgorithm.HMACSHA512
                }); ;
        }
```

### Describe the bug
I keep getting a 403 error.
From what I gather, it seems to be time zone problem, unless I have made some mistake in my code. But my local PC is configured correctly. It's a normal Windows PC and syncs time from time.windows.com.

However, if you look at the stack trace below, you will notice that the `RequestDate` and `Time` are actually different. In fact, `Request Date` is nothing but my local time (IST) which is wrongfully tagged as GMT. I suspect this is the root cause of the error, because azure storage will deny requests which differ by 15 minutes, and my app is sending something with a timestamp 5 hours in the future.

### Stack Trace
```C#
System.AggregateException: One or more errors occurred. (This request is not authorized to perform this operation.)
 ---> Microsoft.Azure.Storage.StorageException: This request is not authorized to perform this operation.
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.Storage.Blob.CloudBlobContainer.CreateAsync(BlobContainerPublicAccessType accessType, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Storage.Blob.CloudBlobContainer.CreateIfNotExistsAsync(BlobContainerPublicAccessType accessType, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
Request Information
RequestID:14eabd68-101e-0043-3470-1cc87c000000
RequestDate:Mon, 27 Apr 2020 14:14:33 GMT
StatusMessage:This request is not authorized to perform this operation.
ErrorCode:AuthorizationFailure
ErrorMessage:This request is not authorized to perform this operation.
RequestId:14eabd68-101e-0043-3470-1cc87c000000
Time:2020-04-27T08:44:33.3926649Z
```

### Further technical details
- ASP.NET Core version
>NET Core 3.1
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.3.20216.6
 Commit:    9f62a32109

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.3.20216.6\

Host (useful for support):
  Version: 5.0.0-preview.3.20214.6
  Commit:  b037784658

.NET SDKs installed:
  2.1.800 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20216.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20215.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20214.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.3.20214.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio Community 2019 16.5

**Comment by blowdart** [comment]
OK, you said

"To allow the IIS AppPool to use azure services, i have configured the app pool identity to use my azure login, and in the applcationHost.config"

What do you mean by this? Is your machine Azure AD joined? What permissions on the storage container do you have set? Where is the exception coming from? (Full stack trace please)

What happens if you remove your culture setting?

**Comment by DibyodyutiMondal** [comment]
This exception is happening during App Startup, during the ConfigureServices() function call

Removing the culture setting, did not change anything,
Changing the time zone of my PC to GMT made the mismatch go away, but the error still happened, so this also does not change anything,

 Further reading and a deeper dive into azure active directory is increasingly pointing me in the direction of access permissions, ie, I'm beginning to think their is no bug, not in my code, nor in .net core. I shall keep you posted.

My PC is not AD joined. I have a personal Microsoft account, and I have no specific permission set on the storage account. (I will come back to this later)


PS: As soon as I confirm my hunch, I'll post a comment

**Comment by blowdart** [comment]
From your description it's highly unlikely you can get your application running under azure credentials. You'll have to authenticate another way. There's some samples around using certificates in the documentation.

**Comment by DibyodyutiMondal** [comment]
First and foremost, the issue of not being able to log in despite 'authentication' was caused by role-based access policies and firewall issues, ie, because I was not 'authorized' even if I was 'authenticated'. So, this is definitely not a bug.

That mismatch with the time made me think it was a bug, but it really wasn't. Thread culture played no part in this. System timezone did, however.

Somehow, I managed to put all the various bits and pieces together. My local IIS AppPool authenticates to Azure as me, thorough the CLI. My App Service authenticates as itself, and it's working smoothly so far. Excellent for certain development scenarios, like mine.

Should I close this issue? Or do you want me to keep it open to track the time thing, or file a new issue about it?

**Comment by DibyodyutiMondal** [comment]
Basically, I learnt that Azure is not Windows. You may be an owner, but that does not necessarily mean you can read or write to that resource! 
Some resources like Azure SQL Database has extra hoops to jump through, while some resources (like KeyVault) have a different way to configure authorization than others. It's all documented, though, can't complain about that.

The thing is, the quickstarts/examples are nice and they all show relationships really well between any two services, but it is largely left up to the developer to discover the nuances of what happens when 3-4 services are required to work in cohesion; as well as how those relationships interact differently in different environments...

**Comment by blowdart** [comment]
Hah, yes, I've been through that myself last week, when I was exploring MSIs. Doc updates will come.

You might want to look at the new, preview libraries from https://github.com/Azure/azure-sdk-for-net - the config code is cleaner and its easier to use MSIs (and as I go through everything their dev is updating the temporary preview instructions to mention permissions).

I also ended up writing an extension method,

```c#
public static class HostEnvironmentEnvExtensions
{
    public static bool IsAzureWebApp(this IHostEnvironment hostEnvironment)
    {
        return !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("WEBSITE_SITE_NAME"));
    }
}
```

which allows me to do things like this rather than mess with the current documented approach of #defines.

```c#
Host.CreateDefaultBuilder(args)
  .ConfigureAppConfiguration((context, config) =>
  {
    if (context.HostingEnvironment.IsAzureWebApp())
    {
      // We have to build here because the vault name is in appsettings.json
      // If it was in an environment variable we could take it out of context.Configuration.
      var appSettingsConfiguration = config.Build();

      var vaultUri = new Uri($"https://{appSettingsConfiguration["KeyVaultName"]}.vault.azure.net/");

      config.AddAzureKeyVault(vaultUri, new DefaultAzureCredential());
    }
  })
  .ConfigureWebHostDefaults(webBuilder =>
  {
    webBuilder.UseStartup<Startup>();
  });
```

**Comment by DibyodyutiMondal** [comment]
I did not use the #defines approach, but when I was taking Azure Keyvault out on a joyride as a configuration store, I remember having to instatiante an `AzureServiceTokenProvider` and then do some more stuff involving some callback. Compared to that, this `config.AddAzureKeyVault()` is so much more.... intuitive...

I will definitely look into the `Azure` SDK.

**Comment by DibyodyutiMondal** [comment]
Also, If anyone from the docs team needs help to make a quickstart for
1. an azure app service, that
2. talks to a static frontend on another domain (like netlify)
3. uses azure sql database to store data
4. uses azure storage to persist keys
5. uses azure keyvault to encrypt said keys at rest
6. would like to use local IIS or development.

I would be happy to provide steps on how I 
1. configured CORS from both the frontend and backend for both the local and cloud environment.
2. configured network access for the local and cloud environments
3 configured the RBAC and access policies for the azure resources
