### ISSUE TITLE
OwningComponentBase and RevalidatingServerAuthenticationStateProvider [Blazor Server]

### ISSUE THREAD

**Issue by michalczerwinski** [dotnet/aspnetcore#21232]
Currently the default RevalidatingServerAuthenticationStateProvider registration makes it imposible to use it in any scenario with OwningComponentBase for Blazor Server.

Facts:
* OwningComponentBase creates new scope.
* RevalidatingServerAuthenticationStateProvider is registered as scoped

Due to this in any service resolved by OwningComponentBase you cannot rely on RevalidatingServerAuthenticationStateProvider. Using RSASP in OwningComponentBase will cause a new service to be created and since the SetAuthenticationState was not set for this instance this will cause issue.

This is more like a design issue.

**Comment by javiercn** [comment]
@michalczerwinski thanks for contacting us.

OwningComponentBase will create a scope, but you can still get things from the global scope through the `@inject` or `[Inject] attributes`.

Only the services resolved from `ServiceProvider` or from `TService` (in case you are using OwningComponentBase<TService>` will have that scope.

**Comment by michalczerwinski** [comment]
Hi @javiercn 

This is exactly what I consider to be a bug. Currently using OwningComponentBase for resolving any service via ScopedServices makes it impossible to use RevalidatingServerAuthenticationStateProvider as it's dependecy.

In other words, no way of checking current user or permissions for any service resolved as OwningComponentBase ScopedService dependency.

I think what needs to be done is to make sure the sub-scope will return the same implementation of RevalidatingServerAuthenticationStateProvider as the outer scope. Without this any serious usage of OwningComponentBase is not possible, IMHO.

**Comment by javiercn** [comment]
@michalczerwinski I'm failing to understand what you are asking for. If you want a completely independent instance you use `ScopedServices` to resolve whatever service you want. Otherwise you simply use `[Inject]`.

What am I missing here?

**Comment by michalczerwinski** [comment]
The situation is: I want my service to be scoped and used by Blazor component. So far so good - I can go with OwningComponentBase.

But if my scoped service has dependency on RevalidatingServerAuthenticationStateProvider then the RevalidatingServerAuthenticationStateProvider doesn't work correctly in this case.

I think the RevalidatingServerAuthenticationStateProvider created in some scope should "inherit" the authentication state from "parents" (the first RevalidatingServerAuthenticationStateProvider which was created)
