### ISSUE TITLE
Misleading Error message in ts client .withURL()

### ISSUE THREAD

**Issue by jfheins** [dotnet/aspnetcore#21231]
When creating a signalR hub with an empty URL, the error message is misleading.

Repro case:

```
new HubConnectionBuilder()
      .withUrl('')
      .withAutomaticReconnect()
      .build();
```

I get this error message:
> The 'HubConnectionBuilder.withUrl' method must be called before building the connection.

Although it was called. The reason for this is that Arg.isRequired only checks for null and undefined (src/SignalR/clients/ts/signalr/src/Utils.ts) but the error is raised on any falsy value:
```
  if (!this.url) {
            throw new Error("The 'HubConnectionBuilder.withUrl' method must be called before building the connection.");
        }
```
(src/SignalR/clients/ts/signalr/src/HubConnectionBuilder.ts)

For backwards-compatibility I'd suggest to throw a more meaningful error message in the withURL method if a falsy value is passed.

**Comment by davidfowl** [comment]
@jfheins Would you like to contribute a fix?

**Comment by jfheins** [comment]
Yes, I'll give it a try shortly :-)

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/21295
