### ISSUE TITLE
Replace MVC's homebrew transcoding stream with System.Text.Encoding.CreateTranscodingStream

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#21243]
Once https://github.com/dotnet/runtime/issues/30260 is resolved

**Comment by GrabYourPitchforks** [comment]
The new API is now in.

**Comment by pranavkm** [comment]
Thanks. Waiting for a runtime update to update this.

**Comment by rynowak** [comment]
This is dream come true. 😍 Thanks @GrabYourPitchforks 😍
