### ISSUE TITLE
"Downgrade" Blazor framework debug messages from Log Level Debug to Trace

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/aspnetcore#21242]
Hi,

This is a minor request/suggestion specifically around Blazor Webassembly, although it may also apply to server.

By default the standard console logger in Blazor appears to only write messages to the console with a log level of warning or above. If a developer wants to include debug logging then you have to set the minimum trace level to debug in Program.cs:

`builder.Logging.SetMinimumLevel(LogLevel.Debug);`

However when you do this you get all of the debug messages from the Framework itself which makes it difficult to see the wood from the trees. 

Would it be possible to change the Framework messages to debug level "Trace". This would then allow us to choose between seeing all messages or just seeing our own!

Hope you're all well and thanks for reading!

**Comment by pranavkm** [comment]
@LaughingJohn you can use filters to configure log levels for specific categories: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-filtering:

```js
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning"
    }
  }
}
```

**Comment by LaughingJohn** [comment]
Thanks @pranavkm, that did the trick. Just in case anyone else stumbles across the same problem, I did this:
`            builder.Logging.SetMinimumLevel(LogLevel.Debug)
                .AddFilter("Microsoft", LogLevel.Warning);
`
The filter sets the minimum log level for a source, so  for"Microsoft" (I think it's anything beginning "Microsoft" ) only display warnings and errors.

Feel free to close this! Thanks again.
