### ISSUE TITLE
New overload of MediaTypeHeaderValue.IsSubsetOf with zero allocations

### ISSUE THREAD

**Issue by davidni** [dotnet/aspnetcore#21265]
Suggested by @Tratcher in https://github.com/microsoft/reverse-proxy/pull/80#discussion_r414696103

### Is your feature request related to a problem? Please describe.
Code duplication. The gRPC server stack, and now YARP, are doing this by hand.

### Additional context
Code locations that would benefit from this:
* YARP: [GRpcProtocolHelper.IsGRpcContentType](https://github.com/microsoft/reverse-proxy/pull/80#discussion_r414696103)
* gRPC server stack: [CommonGrpcProtocolHelpers.IsContentType](https://github.com/grpc/grpc-dotnet/blob/3ce9b104524a4929f5014c13cd99ba9a1c2431d4/src/Shared/CommonGrpcProtocolHelpers.cs#L26)

**Comment by anurse** [comment]
Triage: Seems legit ;). Let's do it.

**Comment by ilkayilknur** [comment]
I want to work on this one.

I will add a new overload `MediaTypeHeaderValue.IsSubsetOf(StringSegment)`. Parse and IsSubsetOf methods use StringSegment and don't allocate unless media type has parameters like text/plain;charset=utf-8;foo=bar;q=0.0. 
If media type has parameters, MediaTypeHeaderValue stores key/value pairs in Parameters collection.

https://github.com/dotnet/aspnetcore/blob/master/src/Http/Headers/src/MediaTypeHeaderValue.cs#L183

In this scenario, IsSubsetOf(StringSegment) needs to allocate to store and compare parameters. Any suggestions on this one?

**Comment by Tratcher** [comment]
IsSubsetOf doesn't need the parameters to produce an answer. It could stop parsing when it reaches the first parameter.

**Comment by ilkayilknur** [comment]
IsSubsetOf(MediaTypeValue) compares paramaters to produce an answer. https://github.com/dotnet/aspnetcore/blob/master/src/Http/Headers/src/MediaTypeHeaderValue.cs#L395 

Are you saying that the new overload doesn't need to compare the parameters?

**Comment by Tratcher** [comment]
We're not considering parameters in the gRPC examples above. Maybe we shouldn't be overloading IsSubsetOf but should do a different method like MatchesMediaType that doesn't consider parameters.

**Comment by ilkayilknur** [comment]
What about throwing an exception if the parameter contains parameters and direct users to use the other overload? or adding parameter support to the new overload for the feature parity? MatchMediaType name may be misleading because the method actually performs IsSubSetOf operations.

**Comment by Tratcher** [comment]
No, throwing for a common situation makes the API hard to use.

**Comment by ilkayilknur** [comment]
I understand. I agree with doing a different method then. If this is the final decision, I can start working on it :)

**Comment by Tratcher** [comment]
Give it a try and we'll see how it works. Thanks
