### ISSUE TITLE
Upload reliability

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#21262]
Similar to dotnet/aspnetcore#21185, but in the other direction. 

Examples:
* https://dev.azure.com/dnceng/internal/_build/results?buildId=615542&view=logs&j=0b850c37-f3ae-5bb9-a9fb-4f1e0fce2747&t=50d41e72-ce5e-50a3-efc7-c28c030be91c&l=425
* https://dev.azure.com/dnceng/internal/_build/results?buildId=618541&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=b8e57a46-4a1c-5752-600e-7a395fe90fb9&l=1904

**Comment by dougbu** [comment]
Have you contacted the First Responders about this issue? None of our code is involved in the problems seen in those builds. Basically, things go bad in build stages the Arcade team owns.

/cc @mattgal @riarenas @ilyas1974 @JohnTortugo

**Comment by ilyas1974** [comment]
I have opened https://github.com/dotnet/core-eng/issues/9677 to have our first responder team take a look at the issue.

**Comment by dougbu** [comment]
Closing this because dotnet/core-eng#9677 was resolved a while back
