### ISSUE TITLE
[Https] Certificate trust on linux

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#21266]
Figure out the required steps to make this work (at least for Ubuntu) and remove any potential existing issues.

**Comment by aloh86** [comment]
Javier, I'm trying to figure out how to do this on Fedora. Can you detail the steps you took?

**Comment by javiercn** [comment]
@aloh86 I don't have specific steps.

This issue is for tracking future work, but we haven't actually started on this.

**Comment by javiercn** [comment]
The plan here is to allow the "--trust" flag on Linux but print a link to a docs page where we will add per-distro instructions on how to do this.

**Comment by javiercn** [comment]
This was merged into RC1
