### ISSUE TITLE
Dependency Injection is not working in Asp.Net Core Blazor

### ISSUE THREAD

**Issue by DrXSsive** [dotnet/aspnetcore#21264]
Hi Guys,

I have a very strange problem in my Blazor project. I am using Dependency Inject to user my "CompanyService" service. Here is how I am registering my service

    // Servies Injection
    services.AddSingleton<UserService, UserService>();
    services.AddSingleton<CompanyService, CompanyService>();

And I am injecting that service in my razor component as

    @inject CompanyService CompanyService
    @inject NavigationManager NavigationManager

I need to pass these services to my ViewModel and I am doing like this (CompanesList is my Razor component name so it is constructor)

    public CompaniesList()
    {
        Context = new CompaniesListVm(NavigationManager, CompanyService);
    }

When I debug this code, I always get services as null (both NavigationManager, CompanyService). Here is my file position in my project

![Bug](https://user-images.githubusercontent.com/40558386/80424533-ff9a8000-88f2-11ea-9fe5-d587c445a8e9.PNG)

Can anyone please help me on this?

P.S I am also using MatBlazor for my UI.

Thank you

Regards
J

**Comment by kodiex** [comment]
Hi There, 
Injected services are not available in the CTOR of the component yet, use OnInitialized instead:

```
protected override void OnInitialized()
{
     Context = new CompaniesListVm(NavigationManager, CompanyService);
}
```

**Comment by DrXSsive** [comment]
Hi,

I worked, Thank you for the help.
