### ISSUE TITLE
Directive attribute completions are provided after colon

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21267]
![image](https://user-images.githubusercontent.com/2008729/80426157-02b55200-889a-11ea-8da4-71b6a512b6c3.png)

We should only be providing these attribute completions if there's whitespace prior to the cursor location and some sort of delimiter after it. i.e. `>` any sort of whitespace etc.

/cc @ToddGrun

**Comment by TanayParikh** [comment]
![image](https://user-images.githubusercontent.com/14852843/81103451-e6cb3500-8ec5-11ea-9b5b-620c13d44a3b.png)
Haven't been able to repro, @NTaylorMullen are you still running into this?

Could this be related to the synchronization issue with `textDocument/didChange` requests occurring out of order?

**Comment by NTaylorMullen** [comment]
> Haven't been able to repro, @NTaylorMullen are you still running into this?

Yes, re-invoke completions by dismissing then ctrl + space after the : still results in the original issue
