### ISSUE TITLE
@bind-Value two-way binding is not working

### ISSUE THREAD

**Issue by DrXSsive** [dotnet/aspnetcore#21276]
Hi,

Hope you all doing great. So, I created a form with some details and bound "MatTextField" to variable defined in VM with "@bind-Value" but when I change value in text box and try to get value in function, the value of bound variable is not updated. Here is my code:

        <EditForm Model="Context" OnValidSubmit="() => Context.UpdateCompany(companyid)">

            <DataAnnotationsValidator />

            <div class="mat-layout-grid" style="padding: 0px !important">
                <br />
                <div class="mat-layout-grid-inner">
                    <div class="mat-layout-grid-cell mat-layout-grid-cell-span-6">
                        <MatTextField @bind-Value="@Context.Name" Label="Name" Style="width:100%;"></MatTextField>
                        <br />
                        <br />
                        <ValidationMessage For="@(() => Context.Name)" />
                    </div>
                    <div class="mat-layout-grid-cell mat-layout-grid-cell-span-6">
                        <MatTextField @bind-Value="@Context.MasterKey" Label="Master Key" Style="width:100%;"></MatTextField>
                        <br />
                        <br />
                        <ValidationMessage For="@(() => Context.MasterKey)" />
                    </div>
                </div>
                
                <div class="mat-layout-grid-inner">
                    <div class="mat-layout-grid-cell">
                        <MatButton Raised="true" Icon="update" Type="submit">Update Company</MatButton>
                    </div>
                </div>
            </div>
        </EditForm>

This my Razor component. I have a VM class in this component which is initializing like this:

    private UpdateCompanyVm Context;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        Context = new UpdateCompanyVm(NavigationManager, CompanyService);
    }

And my VM has public properties

        [Required]
        public string Name { get; set; }

        public string Address { get; set; }

Now there is function in my VM which is called when form is submitted successfully. 

        public async Task UpdateCompany(string companyid)
        {
            StartLoading();

            RequestCreateCompany request = new RequestCreateCompany
            {
                Name = this.Name,
                Address = this.Address
            };

            ResponseObject<Company> serviceResponse = await _companyService.UpdateCompany(companyid, request);

            if (serviceResponse.IsSucceeded)
            {
                ShowSuccessMessage("Company updated successfully");
            }
            else
            {
                ShowErrorMessage(serviceResponse.Error);
            }

            StopLoading();
        }

Whenever this function is called, "this.Name" and "this.Address" have old values, although I change them in the text field in the front end.

Any help will be appreciated.

P.S I am using Matblazor from front end UI.

Thank you

Regards
J

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This seems to be an issue with the referenced component: `MatTextField`.
Also dropping the link to the Blazor Data Binding  docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1
