### ISSUE TITLE
Blazor 3.2 Preview 5 - API call ContentType not supported

### ISSUE THREAD

**Issue by rleath82** [dotnet/aspnetcore#21288]
<!--

With the new preview, I am no longer able to retrieve data from an API as I was before.
I'm getting the following error:

Unhandled exception rendering component: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'

My API is returning a serialized JSON string and I'm using the current HttpClient.GetFromJsonAsync way of calling from Blazor WASM. Any idea what the issue is?

**Comment by rleath82** [comment]
With the new preview, I am not able to retrieve data from my API as I was before this current preview.
I'm getting the following error:

Unhandled exception rendering component: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'

I did not have this issue before and was wondering what the issue may be? My API is returning a JSON string and I'm using the current HttpClient.GetFromJsonAsync WASM API call.

**Comment by pranavkm** [comment]
@rleath82 what's the content-type on your API response?

@Jozkee, filed https://github.com/dotnet/runtime/issues/35580 to consider improving the error message.

**Comment by rleath82** [comment]
It is returning a JSON string

**Comment by rleath82** [comment]
string jsonstr= JsonConvert.SerializeObject(items, Formatting.Indented);
return jsonstr;

**Comment by pranavkm** [comment]
Can you look at the HTTP request in the browser developer console and look at what it says for the Content-Type in the network tab:

![image](https://user-images.githubusercontent.com/174281/80529455-57190a00-894c-11ea-857b-3ab6405228b9.png)

`GetFromJsonAsync` requires the content-type to be `application/json` or `application/{media-type}+json`

**Comment by rleath82** [comment]
Ok, yeah it's returning text/plain; charset=utf-8

So that must be something new with the update then. So I need to return the JSON object instead?

**Comment by lengockyquang** [comment]
I having the same issue with blazor 3.2 web assembly. The content-type in response header is text/html instead of application/json.  Do we have any update on this issue ?

**Comment by rleath82** [comment]
@lengockyquang 
Apparently the response format wasn't to be in the format of text/plain. Your API should be returning the JSON object instead.

**Comment by Wolfeitz** [comment]
I appear to be receiving this same message from a scratch install of the new 3.1.300 .net.

dotnet new blazorwasm -au SingleOrg --api-client-id "{SERVER API APP CLIENT ID}" --app-id-uri "{SERVER API APP ID URI}" --client-id "{CLIENT APP CLIENT ID}" --default-scope "{DEFAULT SCOPE}" --domain "{TENANT DOMAIN}" -ho --tenant-id "{TENANT ID}" -o BlazorHostedExample

Log in - works great
Navigate to Fetch Data

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
System.NotSupportedException: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
  at System.Net.Http.Json.HttpContentJsonExtensions.ValidateContent (System.Net.Http.HttpContent content) <0x3254d20 + 0x0009a> in <filename unknown>:0 
  at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync[T] (System.Net.Http.HttpContent content, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x3254b18 + 0x00006> in <filename unknown>:0 
  at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T] (System.Threading.Tasks.Task`1[TResult] taskResponse, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x3103218 + 0x0011c> in <filename unknown>:0 
  at BlazorHosted.Client.Pages.FetchData.OnInitializedAsync () [0x0003c] in C:\1\Projects\BlazorHosted\Client\Pages\FetchData.razor:48 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2c52ce0 + 0x0013a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2f16b30 + 0x000b6> in <filename unknown>:0

**Comment by lengockyquang** [comment]
I think microsoft should update their documents asap after official version of blazor had been released

**Comment by pranavkm** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

Thanks!
