### ISSUE TITLE
HttpSys does not set DisplayName for Authentication Scheme Options

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/aspnetcore#21281]
### Describe the bug
``IISOptions``, ``IISServerOptions`` both have a property to set the Displayname. This is commonly used (e.g. IdentityServer) to show/hide buttons for the respective login protocols. If it is null, you hide the button.
Unfortunately HttpSys (which is kinda useful for integration testing of automatic (Negotiate) logins) never sets the DisplayName.
https://github.com/dotnet/aspnetcore/blob/c4f230195fd7fe325798c18b8c5f7e30523e7ac7/src/Servers/HttpSys/src/MessagePump.cs#L52-L55

May I suggest adding an ``AuthenticationDisplayName`` property to ``HttpSysOptions`` just like IISOptions or IISServerOptions and using it in the method above?
Example:
https://github.com/dotnet/aspnetcore/blob/c4f230195fd7fe325798c18b8c5f7e30523e7ac7/src/Servers/IIS/IISIntegration/src/IISOptions.cs#L15-L18

Related:
https://github.com/dotnet/aspnetcore/issues/5876 is a previous bug related to this, but was (automatically?) closed without further comments.
https://github.com/dotnet/aspnetcore/issues/14882 about DisplayNames

Workaround (if someone else needs that):
1. Replace ``IAuthenticationSchemeProvider`` with custom implementation (which delegates everything to the normal ``AuthenticationSchemeProvider`` 
2. Handle the AddScheme method manually, like
```csharp
public void AddScheme(AuthenticationScheme scheme)
{
    if (scheme.Name == HttpSysDefaults.AuthenticationScheme)
    {
        scheme = new AuthenticationScheme(scheme.Name, scheme.Name, scheme.HandlerType); // HttpSys has no DisplayName for some reason.
    }

   _baseProvider.AddScheme(scheme);
}
```

### Further technical details
- ASP.NET Core version: 3.1.3 (incl 5.0 preview)
C:\WINDOWS\system32>dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-preview.5.20224.12
 Commit:    a513655c3c

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20224.12\

Host (useful for support):
  Version: 5.0.0-preview.5.20224.4
  Commit:  64a95836ac

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.5.20224.12 [C:\Program Files\dotnet\sdk]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 16.5

**Comment by anurse** [comment]
Triage: Seems reasonable. Marking `help wanted` as we'd take a PR.
