### ISSUE TITLE
Use local secrets created by PowerShell Secrets Management

### ISSUE THREAD

**Issue by markm77** [dotnet/aspnetcore#21287]
Currently we can use local secrets created in a secrets.json for local dev. But PowerShell is currently previewing a cross-platform Secrets Management feature which will allow creating local secrets in CredMan (Windows), keychain (macOS) and keyring (Linux). Remote secrets can also be created with the same interface allowing creation of scripts that work in either situation.

See https://devblogs.microsoft.com/powershell/secret-management-preview-2-release/.

Would be great if we could easily use such local secrets as an alternative to secrets.json secrets for app development purposes.

**Comment by markm77** [comment]
Hi @javiercn,
Just to clarify that this is a request for a way to access PowerShell local secrets in C#. The secrets can be created and managed in PowerShell but currently there is no way to access them in C#. I am mentioning this as I noticed you applied a "area-commandlinetools" label which possibly is not correct?
BR,
Mark

**Comment by markm77** [comment]
I guess what I am requesting is an update to AddUserSecrets?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets?view=dotnet-plat-ext-3.1

**Comment by javiercn** [comment]
@markm77 thanks for the clarification.

Then I believe the right place to file the issue is in the [dotnet/runtime](https://github.com/dotnet/runtime)

**Comment by markm77** [comment]
Thanks @javiercn , have re-posted. Just for my understanding is AddUserSecrets now independent of ASP.NET Core and available to any C# library? Is that why you asked me to re-post?

**Comment by javiercn** [comment]
I believe that has always been the case, since it was in "Microsoft.Extensions". Nothing there depends on ASP.NET Core specific bits.

**Comment by markm77** [comment]
Okay, got it. Cheers!
