### ISSUE TITLE
Testable AppContext switches

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#21297]
**Problem:**

In servicing releases we sometimes add AppContext switches to opt-in or out of fixes. Unit testing switches is difficult because AppContext is static, and the shared state from one test will break another.

At the moment we have to manually verify that a switch works.

**Proposal:**

```cs
internal interface IAppContext
{
    bool TryGetSwitch(string switchName, out bool isEnabled);
}

internal class DefaultAppContext : IAppContext
{
    public bool TryGetSwitch(string switchName, out bool isEnabled)
    {
        return AppContext.TryGetSwitch(switchName, out isEnabled);
    }
}
```

One issue with this that I'm not sure about is visibility. Is there is a central place to add this interface that would let it be used everywhere. MVC and Kestrel and hosting and authentication and routing, etc.

Shared source would be an alternative but that would require different stacks to register the types with DI.

@rynowak @Pilchie

**Comment by blowdart** [comment]
I'd be careful here. As long as this doesn't enable runtime opt-outs, and preferably isn't in a shipped product it would be ok. AppContexts can be used to control vulnerability updates, and we don't want the ability to change that decision at runtime.

**Comment by JamesNK** [comment]
Any APIs added would be internal. The implementation would only change in unit tests.

**Comment by rynowak** [comment]
What I don't like about this is that I don't like it it introduces an abstraction, and requires new code to consume it - I think that has the same or higher risk level with more work than just ... not. I was trying to state this objection on my PR, but perhaps I wasn't super clear.

**note:** I'm making the assumption that we manually test our patch fixes with the real build that is going to customers before shipping it, and that we test the use of the switch. 

---

It's already easy to write testable code that uses appcontext. Make a boolean property (internal), initialize it from appcontext, and then write unit tests that change the property.

The code path that's *not being covered* by a unit test looks like this:

```
if (AppContext.TryGetSwitch("someswitch", out var value))
{
    MySetting = value;
}
```

---

Now consider what happens with this proposal. 

You *start* by making code changes to reference/copy `IAppContext`. (where is it defined?)

Is your component coming from DI? You need to add a constructor parameter (public API change).

Who registers `IAppContext` in DI? Is it registered in all of the cases you care about?

The net benefit to making these changes is you get to cover that `if` block from above in a unit test.

**Comment by JamesNK** [comment]
> where is it defined?
> Who registers IAppContext in DI?

This is the part I wasn't sure about. We don't have one central assembly to do these things.

> You need to add a constructor parameter (public API change).

A lot of types are internal, but yeah, if the type is public then this idea won't work.

A small amount of manual testing is simpler that overcoming all these problems. Closing.

**Comment by rynowak** [comment]
> AppContexts can be used to control vulnerability updates, and we don't want the ability to change that decision at runtime

FYI @blowdart - this is already a thing. `AppContext.SetSwitch`. I'd wager most customers already interact with app context through code vs other means.
