### ISSUE TITLE
[Question] Asp.net behavior for unhandled requests

### ISSUE THREAD

**Issue by aL3891** [dotnet/aspnetcore#21292]
Hello,
We had a discussion here today regarding what happens if you make a post to a non existent url in a Asp.net core site.

The question is, will the server read the entire request, including the body, even if it's not able to find a handler for the request? My assumption would have been "no", i thought it would just read the request method and url, discover that it can't handle the request, write a 404 response and close the connection.

My colleague however argued that the entire request would be read anyway and doing some testing in fiddler appears to validate this.

For my test I just create a blank asp.net core site, and make a large post request to some random, non existent url and fiddler reports all the bytes being sent. I also tried manually sending a request using httpclient and writing to the request stream, and it also seems to write all the data.

So what am I missing? am I simply wrong in my assumption that kestrel only reads as much as it needs from the request stream in order to handle the request? 

Is fiddler just not a good way to test this? Could it be a read buffer below the server (like in the os) that is consuming some of the posted data in advance? I'm sure the behavior is correct, I'm just trying to understand what's happening :) 

The background of this whole issue is that we have a bug in our client software (an app) that causes it to upload large amount of data, and one idea to fix it was to simply disable the url its uploading to. the question was if that would work or not.

**Comment by aL3891** [comment]
I've done some more testing using a custom client where I can change the way the request is sent as well as some custom middleware and I can see that

* The 404 response is sent right away
* The client is still sending at least some data (a few megabytes) after the response has been written
* I sometimes get a connection reset as i expect, and sometimes is able to send the entire request,

After talking to some folks i also learned that the http spec does say that server should either read the entire request (so that the connection is clean for the next request if the is one) or close the request, however i've yet to find a way to control this behavior in kestrel, perhaps there isnt one? 
maybe that could be done in middleware as well, i haven't tried that yet though.. I have some vague memories of being able to control this in iis somehow, but i've not been able to find that setting either..

i am doing these tests on localhost with http client

**Comment by Tratcher** [comment]
At the end of any request where the request body has not been fully consumed kestrel will attempt to drain the body for a non-configurable 5 seconds.
https://github.com/dotnet/aspnetcore/blob/b463e049b6aed02f94edcac8855b8b5c87d0989b/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs#L81
https://github.com/dotnet/aspnetcore/blob/b463e049b6aed02f94edcac8855b8b5c87d0989b/src/Servers/Kestrel/Core/src/Internal/Infrastructure/Constants.cs#L39

There's a tradeoff here. Connections can be expensive to establish so you want to re-use them if possible. But you also don't want to drain unneeded data forever.

Yes you can replace this behavior in middleware. What behavior do you actually want?

**Comment by aL3891** [comment]
aha, very interesting, thanks!

In this specific case i would like to close the connection as soon as possible. we had a bug in our mobile app where it would upload a ton of data to a kestrel endpoint, this caused us to use up alot of our users mobile data. We tried to just remove the endpoint temporarily but found that data was still uploaded.

I suppose there is also a general case of trying to attack a server by sending garbage requests to a non existent endpoint in an attempt to eat all the bandwidth.

Really my main motivation to asking this question was just to understand the behavior, i think the default behavior is fine, but it would be nice to have a way to terminate the connection as soon as the response is written, even if that is just some docs with a middleware sample.

Just for completeness, what would that middleware look like? just a middleware at the end of the pipeline that closes the connection?

**Comment by tebeco** [comment]
@guardrex 
Do you know if there are page on current documentation about these behaviors ?
If not, I'm not sure if it would make sense to document this or not either, just curious about thoughts on that matter

**Comment by guardrex** [comment]
It would be opened for the Kestrel topic at ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#feedback

... and it would be helpful if the middleware was provided 🏃‍♂️😅. If so, I think the update would go in quickly. If not, I think such an issue would sit for several months behind high-priority work.

**Comment by Tratcher** [comment]
The only way to prevent the draining logic is to forcefully close the connection via `HttpContext.Abort()`. The trouble is that there's no guarantee the client will get your response before they notice the connection was closed. You can try calling `HttpResponse.CompleteAsync()` before Abort to make sure the response is sent out, but that still doesn't guarantee client behavior.

Doing this for every 404 or redirect would be a bad idea, closing the connection is a big performance disruptor. It should only be done when you're sure there's a significant problem. E.g. If the client is doing this on a specific non-existent route, add a controller for that route and call Abort only for that path.

On a protocol level, you should consider making use of 100-continue's to avoid having the client uploading data before it gets an acknowledgement from the server.

@guardrex it's worth mentioning the drain timeout and that you can call CompleteAsync and Abort to avoid it, but it should only be recommended for severe error cases, not common ones like 404s.

**Comment by guardrex** [comment]
Recommend transferring this to the docs repo. I'll add the metadata so that at least until the docs team can get to it the approach will be visible via the open issues at the bottom of the Kestrel topic.

> upload a ton of data to a kestrel endpoint,

... which implies that a cross-link to the new content should appear in the *Additional resources* of the [File Uploads topic](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads).

**Comment by aL3891** [comment]
Sure, yeah i agree it should not be the default, just having it the docs is fine imo :) 

Thank you for the info @Tratcher!
I'll see about opening a docs pr for the page you linked @guardrex
