### ISSUE TITLE
Experiencing #7419 in latest preview release 3.2.0-preview5.20216.8

### ISSUE THREAD

**Issue by mpp** [dotnet/aspnetcore#21301]
Hi, I'm experiencing the bug shown in issue #7419 with the latest preview release (3.2.0-preview5.20216.8).

I have a page that respond to 2 URIs:
```
@page "/foos/{fooId}/bars"
@page "/foos/{fooId}/bars/{barId}/show"

[html]

@code
{
    [Parameter]
    public string FooId { get; set; }

    [Parameter]
    public string BarId{ get; set; }
}
```

When I navigate from `/foos/{fooId}/bars` to `/foos/{fooId}/bars/{barId}/show` the `barId` property is not set.
When, from the browser, I navigate directly to `/foos/{fooId}/bars/{barId}/show`, then the `barId` property is properly set.

Is there  a workaround?

**Comment by javiercn** [comment]
@mpp thanks for contacting us.

I don't think we ever implemented this behavior (despite what the referenced issue says)

**Comment by mpp** [comment]
Ok, thanks for letting me know.
I'll manage it in a different way.

**Comment by SteveSandersonMS** [comment]
Sorry, I wasn't able to reproduce a problem. Here's the full repro code I tried:

```razor
@page "/foos/{fooId}/bars"
@page "/foos/{fooId}/bars/{barId}/show"

<h1>FooId: @FooId</h1>
<h1>BarId: @BarId</h1>

<p><a href="foos/FooValue1/bars">Go to foos/FooValue1/bars</a></p>
<p><a href="foos/FooValue1/bars/BarValue1/show">Go to foos/FooValue1/bars/BarValue1/show</a></p>

@code
{
    [Parameter]
    public string FooId { get; set; }

    [Parameter]
    public string BarId { get; set; }
}
```

When navigating from the second link to the first one, I found that the `FooId` parameter was correctly cleared.
