### ISSUE TITLE
API Proposal : Getting stored reference to http methods

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#21308]
Based on #21079 and #21277 routing performance could be improved by comparing http methods by reference first. 

These two methods are needed. `bool Equals(string x, string y)` to check the equality of http methods and `string GetHttpMethod(string httpMethod)` for getting the stored reference of the http method.

```csharp
public static class HttpMethods 
{
    public static bool Equals(string x, string y)
    {
        return object.ReferenceEquals(x, y) || StringComparer.OrdinalIgnoreCase.Equals(x, y);
    }

    public static string GetHttpMethod(string httpMethod) => httpMethod switch
    {
        string method when HttpMethods.IsGet(method) => HttpMethods.Get,
        string method when HttpMethods.IsPost(method) => HttpMethods.Post,
        string method when HttpMethods.IsPut(method) => HttpMethods.Put,
        string method when HttpMethods.IsDelete(method) => HttpMethods.Delete,
        string method when HttpMethods.IsOptions(method) => HttpMethods.Options,
        string method when HttpMethods.IsHead(method) => HttpMethods.Head,
        string method when HttpMethods.IsPatch(method) => HttpMethods.Patch,
        string method when HttpMethods.IsTrace(method) => HttpMethods.Trace,
        string method when HttpMethods.IsConnect(method) => HttpMethods.Connect,
        string method => method
   };
}
```

/cc @rynowak @Tratcher

**Comment by halter73** [comment]
Do we need the Equals method? It looks like StringComparer.OrdingalIgnoreCase.Equals already short circuits immediately given reference equality.

https://github.com/dotnet/runtime/blob/d10a78217f61a1113624eff3747a17cf2907297a/src/libraries/System.Private.CoreLib/src/System/StringComparer.cs#L325

**Comment by halter73** [comment]
It also probably make sense to verify reference equality fails for at least GET and POST before doing full string comparisons in GetHttpMethod.

**Comment by rynowak** [comment]
@benaadams - the question I was actually trying to ask you was about this ^^^

If we create:

```C#
public class HttpMethods
{
   public static bool Equals(string x, string y) { }
}
```

Do we wipe out the perf-gain from writing for the single-comparison case:

```C#
        object.ReferenceEquals(x, y) || StringComparer.OrdinalIgnoreCase.Equals(x, y);
```

I'm suspect this because `StringComparer.OrdinalIgnoreCase.Equals()` also calls `object.ReferenceEquals` inside it's implementation. So I assume the reason why we use this pattern is because `StringComparer.OrdinalIgnoreCase.Equals` doesn't get inlined.

**Comment by benaadams** [comment]
Is `GetHttpMethod` acting like an intern(ish) method? Or translating user supplied strings into the `HttpMethods` string for later use?

The big advantage comes from when you are checking against multiple strings e.g. `GET`, `POST`, `HEAD` etc; then check them all with reference equality before moving to string.equals; generally you can then bypass the string.equals tests.

Kestrel always returns a `HttpMethods` value so it should be a fast checking against reference equality and one of those strings if the Method is coming from Kestrel.

**Comment by rynowak** [comment]
Approved, but we want to call the `GetHttpMethod` `GetCanonicalizedValue` instead. This needs to have a good doc comment explaining that it's for low level optimization and not something that's needed in the vast majority of cases.
