### ISSUE TITLE
EnvironmentName is not propagated from publish file to WebHostEnvironment

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#21310]
Based on [answers in this question](https://stackoverflow.com/questions/39238850/how-to-set-aspnetcore-environment-in-publish-file) 
and [this one](https://stackoverflow.com/questions/32548948/how-to-get-the-development-staging-production-hosting-environment-in-configurese) I am trying to propagate the current environment setting from my .pubxml file to my app when it runs.  Why is it ignored?

Here is .pubxml

	<PropertyGroup>
		<EnvironmentName>Stage</EnvironmentName>
		<LastUsedBuildConfiguration>Stage</LastUsedBuildConfiguration>
		
		
Generated web.config file (this is correct):

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <location path="." inheritInChildApplications="false">
		<system.webServer>

		  
			<environmentVariables>
			  <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Stage" />
			</environmentVariables>
		  </aspNetCore>
		</system.webServer>
	  </location>
	</configuration>

Startup.cs logging:

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            Log.Information("Configuration[\"ASPNETCORE_ENVIRONMENT\"] is {env}", Configuration["ASPNETCORE_ENVIRONMENT"]);
            Log.Information("WebHostEnvironment.EnvironmentName is {env}", env.EnvironmentName);

			
Log result:

> 2020-04-28 10:46:48.040 -07:00 [INF] Configuration["ASPNETCORE_ENVIRONMENT"] is null

> 2020-04-28 10:46:48.042 -07:00 [INF] WebHostEnvironment.EnvironmentName is Production

Issue 1:

I expect `WebHostEnvironment.EnvironmentName` to be reported as Stage.  What is the purpose of setting environment info in the .pubxml file and propagating to web.config if it is not respected in methods that report environment info? Within my code how do I retrive the EnvironmentName that is set in the .pubxml file?  [This document](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-3.1) provides an explanation how to set build configuration and environment but offers no guidence how to use the parameters at runtime.

Issue 2:

EnvironmentName is reported as Production.  It should be Stage - however if the configuration system is unable to find a place where the Environment is explicitly set it should default to something like Undefined.

Issue 3:

Based on my observations here and the discussion in the articles I cited this whole process appears to consist of different pieces that work independently of each other.  I think publish files, config files, launch files, OS variables, etc. should feed into and read from the configuration system in a predictable way.  The configuration system should apply overrides and fall back predictably if a value is not set in a certain place in code or the build script.

See also [this issue](https://github.com/aspnet/Hosting/issues/1440).

**Comment by Tratcher** [comment]
How and where are you running the app.

**Comment by sam-wheat** [comment]
Visual Studio 2019 latest, Publish option in solution explorer context menu.

**Comment by Tratcher** [comment]
Publishing to where? And then run how?

**Comment by sam-wheat** [comment]
Publishing to Azure to a running app service.
I can also repro this when publishing to a folder and running MyApp.exe.

**Comment by Tratcher** [comment]
The web.config does not apply when running the exe directly, only when running in IIS. It should work in Azure app service (Windows).

**Comment by sam-wheat** [comment]
It is now working in stage but not prod in Azure.  Presumably my error but I still don't know what.  

![image](https://user-images.githubusercontent.com/16885210/80633197-3a90d680-8a0d-11ea-9d8f-b11cd3ab5e23.png)

**Comment by anurse** [comment]
> however if the configuration system is unable to find a place where the Environment is explicitly set it should default to something like Undefined.

We very specifically use Production as the default value because we want to default to the most secure production-by-default configuration of various components (such as exception details pages, etc.)

> It is now working in stage but not prod in Azure. Presumably my error but I still don't know what.

I'm not quite sure how this correlates to your screenshot. Are you showing a screenshot from your production environment? It seems to show "Production" there.

**Comment by sam-wheat** [comment]
> We very specifically use Production 
This is not the tao of dotnet.   If it is not working I don't want it to lie to me.  I want it to fail in dev, not in prod.

> It seems to show "Production" there.
Sure looks like it's working doesn't it?  See also comment above.

**Comment by anurse** [comment]
I'm a little confused as to the issue at hand. Can you share a runnable sample project that reproduces the issue (along with steps to repro)?
