### ISSUE TITLE
Html.HiddenFor will never use htmlAttributes value for value attribute

### ISSUE THREAD

**Issue by levdimov** [dotnet/aspnetcore#21314]
### Describe the bug

`Html.HiddenFor(m => m.Property)` won't use `htmlAttributes` value for value attribute even if `m.Property` is null and/or there are no such key in ModelState.

### To Reproduce

Model:
```csharp
public class ViewForm
{
    [Required]
    public Guid? FormId { get; set; }
}
```

View:
```csharp
...

@Html.HiddenFor(m => m.FormId, new Dicitonary<string, object> { { "value", Guid.NewGuid() } })

...
```

FormId is not initialized, so it is null.

Actual result:
```html
<input data-val="true" data-val-required="The FormId field is required." id="FormId" name="FormId" type="hidden" value>
```

Expected result:
```html
<input data-val="true" data-val-required="The FormId field is required." id="FormId" name="FormId" type="hidden" value="2c0d312b-b21b-4ee3-9b8a-5b8790632f6d">
```

Documentation for HiddenFor clearly states:
> Returns an <input> element of type "hidden" for the specified expression. Adds a "value" attribute to the element containing **the first non-null value** found in: the ModelState entry with full name, the expression evaluated against Model, **or the htmlAttributes dictionary entry with key "value"**. See NameFor<TResult>(Expression<Func<TModel,TResult>>) for more information about a "full name".

### Further technical details
- ASP.NET Core 2.1.* nuget packages @ net472

**Comment by javiercn** [comment]
@levdimov thanks for contacting us.

The value comes from the property and can't be overriden by passing custom attributes. To achieve what you want, simply assign the value to the property in your model.

**Comment by levdimov** [comment]
Hey, @javiercn! Thank you for a quick response.

Could you plase explain how this correlates to what is written I docs for this method?

**Comment by javiercn** [comment]
@levdimov can you point the specific doc you are referring to?

**Comment by levdimov** [comment]
@javiercn I did reference it in the end.

Here is the link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.rendering.ihtmlhelper-1.hiddenfor?view=aspnetcore-2.1

In my scenario htmlAtributes' `value` is first non-null value so it should be written in input tag.

**Comment by levdimov** [comment]
@javiercn could this be a mistake either in docs or in the code? Docs sound quite misleading then.
