### ISSUE TITLE
Disponse FileStream not at time in Action

### ISSUE THREAD

**Issue by HLSS-Hen** [dotnet/aspnetcore#21313]
### Describe the bug
When I return `ControllerBase.File(fileStream,contentType,downloadName) `in `Action`, it warning me **CA2000**. If I use `Using` reserved word, whatever I use `try finally` or let it auto disponse, it throw exception of file has been closed.

### To Reproduce

```
string path = "[A  Accessible File's Path]";
string contentType = "[File's Type]"
string downloadName = "[Download Name]"

public class DemoController:Controller
{
    public IActionResult GetFileWithoutDisponse()
    {
        var stream = new FileStream(path, FileMode.Open);  // CA2000
        return File(stream, contentType, downloadName);
    }

    public IActionResult GetFileWithDisponse()
    {
        using var stream = new FileStream(path, FileMode.Open);
        return File(stream, contentType, downloadName); // Exception: File has been close
    }
}
```

### Further technical details
- ASP.NET Core version: .NET Core 3.1
- Include the output of `dotnet --info`:

> .NET Core SDK（反映任何 global.json）:
>  Version:   3.1.201
>  Commit:    b1768b4ae7
> 
> 运行时环境:
> 
> 
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.201\
> 
> Host (useful for support):
>   Version: 3.1.3
>   Commit:  4a9f85e9f8
> 
> .NET Core SDKs installed:
>   3.0.100 [C:\Program Files\dotnet\sdk]
>   3.1.201 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: `Microsoft Visual Studio Community 2019 Version 16.5.4`

- Nuget List:
```
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="3.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Contracts" Version="3.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Core" Version="3.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Templating" Version="3.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="3.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGenerators.Mvc" Version="3.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="NPOI" Version="2.5.1" />
    <PackageReference Include="System.Management" Version="4.7.0" />
```

**Comment by javiercn** [comment]
@HLSS-Hen thanks for contacting us.

You should not use `using` within your stream there, and you should simply ignore/supress the warning. If you pass a stream to File, the framework will take care of the disposal after is done with it.
