### ISSUE TITLE
Error while using Microsoft.AspNetCore.SignalR.Client. Works from Console but not from MSTest

### ISSUE THREAD

**Issue by abhiphirke** [dotnet/aspnetcore#21318]
I am using `SignalR` as a mechanism to exchange some simple notifications in our product suite. 

I am facing an issue with the `.Net Framework 4.7.2` and `AspeNetCore.SignalR.Client`. 
Attached is the sample code which has projects.

Solution `NotificationHub` includes a simple `ASP.Net Core 3.1` SignalR Hub that broadcasts received message.

Solution `NotificationTestProj` includes following SignalR clients:

1. `SpokeNet` is the .Net Framework 4.7.2 DLL that uses `Microsoft.AspNetCore.SignalR.Client`.
2. `SpokeNet.Test` is the simple MSTest (.Net Framework 4.7.2 ) project that uses `SpokeNet`.
3. `SpokeNet.Console` is the simple Console App (.Net Framework 4.7.2 ) project that uses `SpokeNet`.

**Issue:**
**When I run the `SpokeNet.Console` app**, everything works fine. There are no issues, no errors and broadcast messages are received.

**When I run the unit test in `SpokeNet.Test` project**, I get following exception at  new `HubConnectionBuilder().WithUrl()` call.

> Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### To Reproduce
See the attached sample code.

### Further technical details
- ASP.NET Core version: 3.1.3
- .Net Framework version: 4.7.2
- The IDE VS Professional 2019 16.5.3
- Output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
[SignalRErrorSample.zip](https://github.com/dotnet/aspnetcore/files/4551366/SignalRErrorSample.zip)

**Comment by BrennanConroy** [comment]
I'm not super familiar with how binding redirects, but it looks like your test project doesn't have any. If you copy the binding redirects from the SpokeNet project to the SpokeNet.Test project then the assembly load issue will go away.

**Comment by abhiphirke** [comment]
@BrennanConroy  Thanks for your hint. This helped make it work! This also helped in making work when it was being used as COM component from another C++ application.
