### ISSUE TITLE
Blazor Code format in VS2019 16.6.0 Preview4

### ISSUE THREAD

**Issue by BenLampson** [dotnet/aspnetcore#21316]
I write the code like this:
![image](https://user-images.githubusercontent.com/15414750/80578664-67f47900-8a3b-11ea-944b-5c8b70c44aaf.png)

If I press the ctrl+e+d.
The code style change to:
![image](https://user-images.githubusercontent.com/15414750/80578712-8195c080-8a3b-11ea-948e-d2cb369bf64a.png)

Currently, I close the code format feature. :cold_sweat:

**Comment by NTaylorMullen** [comment]
Thanks for the report @BenLampson! We'll be sure to address this as part of https://github.com/dotnet/aspnetcore/issues/14271
