### ISSUE TITLE
[Blazor Webassembly] Give JsonSerializerOptions to HttpClient Make result "empty"

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#21322]
Hello Guys,

It seem the new System.Text.Json Api can now handle ReferenceLoopHandling as suggest this issue (https://github.com/dotnet/aspnetcore/issues/21187#issuecomment-620936091). 

So i try implement this in my app to replace Newtonsoft.Json.

I precise i have this version of System.Net.Http.Json : 5.0.0-preview.3.20214.6

I configure my server project to activate this
````
pServices.AddMvc()
            .AddJsonOptions(options =>
             {
                 options.JsonSerializerOptions.ReferenceHandling = ReferenceHandling.Preserve;
             });
````

And my client project 
````
JsonSerializerOptions options = new JsonSerializerOptions()
        {
            ReferenceHandling = ReferenceHandling.Preserve
        };

var result = await sender.GetFromJsonAsync<T>(requestUrl, options);
````

I don't have errors, i retrieve an array with the correct amount of items, but all the properties are empty.

I notice is the same thing with an empty  JsonSerializerOptions, so it seem not related to this specific option or to the server project.

To reproduce in the default project, just add an empty option :
````
forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast", new System.Text.Json.JsonSerializerOptions());
//all the forecast here have theirs properties empty
````

Thanks !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

I don't think this is Blazor webassembly now since `GetFromJsonAsync` is coming from the new JSON extensions for HttpClient. That said, can you post more details about your model, make sure you have linking turned off (to ensure the linker is not removing things an causing the serialization to fail)

@pranavkm do you have any thoughts on this?

**Comment by pranavkm** [comment]
MVC 3.x's output formatter does not support features introduced in System.Text.Json 5.0. This includes the `ReferenceHandling` property. You're also missing the casing behavior configured by default by `GetFromJsonAsync`:

```C#
new JsonSerializerOptions()
{
    PropertyNameCaseInsensitive = true,
    ReferenceHandling = ReferenceHandling.Preserve,
}
```

**Comment by julienGrd** [comment]
> MVC 3.x's output formatter does not support features introduced in System.Text.Json 5.0. This includes the `ReferenceHandling` property. You're also missing the casing behavior configured by default by `GetFromJsonAsync`:
> 
> ```cs
> new JsonSerializerOptions()
> {
>     PropertyNameCaseInsensitive = true,
>     ReferenceHandling = ReferenceHandling.Preserve,
> }
> ```

It work by adding the PropertyNameCaseInsensitive  property, thanks !

What do you mean by "MVC 3.x's output formatter does not support features introduced in System.Text.Json 5.0" ?

Im actually in .net 5 preview in my server, so its OK for me ?

There is any way to achieve this (use System.Text.Json completely) or im stuck with NewtonSoft ?

Other question : is it possible to use both system on server ? For example use System.Text.Json generally but on some method/controller use newtonsoft ?

**Comment by pranavkm** [comment]
> What do you mean by "MVC 3.x's output formatter does not support features introduced in System.Text.Json 5.0" ?
https://github.com/dotnet/runtime/issues/30445 has some more context. MVC's output formatter currently only supports configuring the subset of features supported of S.T.Json 3.x. This should be resolved as part of the preview4 release.

> : is it possible to use both system on server ? For example use System.Text.Json generally but on some method/controller use newtonsoft ?
You can tell MVC what set of formatters to use to format an object:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.objectresult.formatters?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_ObjectResult_Formatters
