### ISSUE TITLE
Blazor WebAssembly Google authentication

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#21326]
I'm trying to add a third-party API (Google) to authenticate users in a Blazor WebAssembly app. When looking at the [Secure ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1#feedback) @javiercn mentioned to use this `builder.services.AddOidcAuthentication(options => { ... })`, but I can't find how to add the Client Secret, and so on. I'm wondering if there is any sample code about setting up Google authentication.

**Comment by javiercn** [comment]
@ylr-research thanks for contacting us.

Blazor WebAssembly is for single page applications. As such, you shouldn't use client secrets with it and as a result we don't expose it.

**Comment by ylr-research** [comment]
@javiercn Thanks, so there is not way to authenticate with Google or any other OIDC provider, then?

**Comment by javiercn** [comment]
@javiercn yes, but you need to use a public client and you can do implict flow or code + PKCE. I've personally done this with google without problems.

**Comment by Feroks** [comment]
@javiercn do you have a sample you can share?

I have tried to use default template with following implicit flow configuration::
``` csharp
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.Authority = "https://accounts.google.com/";
    options.ProviderOptions.ClientId = "MY_ID_HERE";
    options.ProviderOptions.ResponseType = "token";
    options.ProviderOptions.RedirectUri = "https://localhost:5001/authentication/login-callback";
    options.UserOptions.AuthenticationType = "google";
});
```

After i enter my credentials, i get "Completing login.." message and nothing happens. 
If i clear `ProviderOptions.DefaultScopes` and only add `profile`, then access token is saved in SessionStorage, but profile data is missing, hence Blazor thinks i am not authenticated.

I am clearly missing something.

**Comment by transcendair** [comment]
I too get "Completing login..." and nothing else. Please @javiercn tell us more about your success and what could be going wrong.

**Comment by javiercn** [comment]
I would open the devtools and check for errors in the console

**Comment by yopez83** [comment]
You can take a look at #21879. I was able to get it to work.

**Comment by transcendair** [comment]
What is working: On login attempt I get prompted with google signin page and successfully redirected back to app so google is seeing request and likes the URI source.

@yopez83 I lifted your code from#21879 but results are the same.

@javiercn  Seeing: info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
blazor.webassembly.js (1,9726)

Not trying to understand why it gets this far without a clientsecret.

**Comment by yopez83** [comment]
@transcendair look at the comment above by @javiercn. ClientSecret is not needed, SPAs cannot keep a secret. I bet that's why you're not required to provide one.  [This](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1) is the guideline I followed to get mine working.

**Comment by transcendair** [comment]
@yopez83 Would you be willing to send me a zip file of your working code? Thanks.

**Comment by Semos5245** [comment]
Would like a zip file of the working code as well here if you will @yopez83

**Comment by nzmangan** [comment]
@transcendair @Semos5245 did you manage to solve this as I am experiencing the same issue?
For what it is worth I am using AWS Congnito as the identity provider.

**Comment by transcendair** [comment]
@nzmangan  No. This is bleeding edge stuff. I don't have the time to debug it myself. One day this code will be as mature as the MVC templates in which you comment out a few lines in Startup.Auth.cs to enable app.UseGoogleAuthentication(). In the meantime hopefully someone will have the time to debug it and post their results.

**Comment by transcendair** [comment]
I have something that appears to be working. It's on [github](https://github.com/transcendair/BlazorApp). You'll google portal stuff to do including updating the secrets file (or you can just hardcode in Server/Startup). I used VS 2019 Preview v 16.17.0 Preview 1. You might also need to change the EmailConfirmed field for the user you add in dbo.AspNetUsers to true.

**Comment by ylr-research** [comment]
@transcendair I didn't need to do anything you mentioned above to get it working. If I have some time today, I will create a brand new project and zip it for you.

**Comment by Feroks** [comment]
@ylr-research he used Google authentication server side. We are interested in doing it on client side onyl. Can you create a repo instead of zip archive? I would like to see how you did it.

**Comment by transcendair** [comment]
@Feroks My understanding of WASM authentication, according to [this ](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1) article, is that a token is generated on the server side (which does the standard server based OIDC process) so what I have implemented is how WASM auth is done.

**Comment by Feroks** [comment]
@transcendair you can also do OIDC on Client side only. This is what me and OP tried to do.

**Comment by Semos5245** [comment]
@nzmangan Nope not yet.. My whole idea of doing this is to authenticate the user using one of the famous authentication providers (Google, Facebook, Twitter) and make my WebApi's have the capability to create new users (Basically sign in, if user doesn't exist, then create one) and give the client side app a JWT token in coordination of the provider he used to sign in.. Still working on it and i think i found it really.. will get done from it and send a zip if anyone would be interested

**Comment by javiercn** [comment]
Here is a sample of how to make google auth work https://github.com/javiercn/BlazorGoogleAuthSample/blob/master/GoogleAuth/Program.cs.

If you want an access token switch to id_token token and add the scope for the resource you want to access.

**Comment by Feroks** [comment]
@javiercn thank you for the repo. It seems that my problem was that i was using `token` instead of `id_token` 🤦
