### ISSUE TITLE
@microsoft/signalr - Unable to receive a message in the client side.

### ISSUE THREAD

**Issue by santosh-kh** [dotnet/aspnetcore#21323]
I'm not able to receive message from server to client when sending to specific client.
```csharp
_hubContext.Clients.Client(connectionId).BroadcastMessaage(message)
```
I'm passing connectionId as part of request header.
This is how i'm getting the connectionId in the client before making api call
```typescript
            this.hubConnection
                .start()
                .then(() => {
                    const hub = this.hubConnection;
                    const connectionUrl = hub['connection'].transport.webSocket.url;
                    const id = connectionUrl.split('id=')[1];
```
Message sent form OnConnectedAsync is received by client. 
```csharp
public override async Task OnConnectedAsync()
        {
            await Clients.Client(Context.ConnectionId).BroadcastMessaage("text").ConfigureAwait(false);
        }
```
### My observation
``` Context.ConnectionId``` is not matching  ```connectionUrl.split('id=')[1] ```
This works fine with @aspnet/signalr 

### Further technical details
- ASP.NET Core version 3.1
- @microsoft/signalr npm package version 3.1.3

**Comment by anurse** [comment]
The `id` query string value is not actually used for Clients.Client(...) in 3.1. We made a change to split the ID into two separate values in order to better protect against client-side forgery.

Parsing the ID out of the querystring is definitely not a supported way of getting the ID. There's a public `connectionId` property on `HubConnection` now which should provide the correct value. What happens when you try using that?

**Comment by santosh-kh** [comment]
Thanks for the quick response.
```HubConnection.connectionId``` solved the issue. 
I know only this [SignalR documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1) for asp.net core.
Let me know if any other place to refer.

**Comment by anurse** [comment]
In the sidebar of that page is a "JavaScript API Reference" link which leads you to API documentation on the types which might help out in the future. In particular, there's a doc on [HubConnection](https://docs.microsoft.com/en-us/javascript/api/@microsoft/signalr/hubconnection?view=signalr-js-latest) which includes the `connectionId` property.

Closing as the question has been answered.
