### ISSUE TITLE
[Blazor WASM]Request has been blocked by CORS policy

### ISSUE THREAD

**Issue by ZhangGaoxing** [dotnet/aspnetcore#21321]
### Describe the bug
I have a ASP.NET Core 3.1 WebAPI project and a Blazor WASM project. CORS works well when WebAPI is deployed locally. But when I deployed the web API on the Cloud Server, there was a CORS error.
![1](https://user-images.githubusercontent.com/15957347/80605598-dfd79900-8a65-11ea-8b5d-42782daaa9b6.jpg)

### To Reproduce
CORS configuration of WebAPI
``` C#
services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
        policy.WithOrigins(new[] { "http://MYDOMAIN.com", "http://localhost:38141" })
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials());
});
```
What puzzles me is that there is no CORS error when WebAPI runs locally. I didn't make any settings on Blazor. But I have a `HttpClientHandler`.
```C#
public class HttpJwtHandler : HttpClientHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var tokenService = ServiceProviderHelper.ServiceProvider.GetRequiredService<JwtAuthenticationStateProvider>();

        string token = await tokenService.GetTokenAsync();

        if (!string.IsNullOrEmpty(token))
        {
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token); 
        }

        return await base.SendAsync(request, cancellationToken);
    }
}
```

### Further technical details
```
PS C:\Users\zhang> dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.300-preview-015115
 Commit:    cd8d468337

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015115\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Blazor
```
Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview5.20216.8
```

**Comment by ZhangGaoxing** [comment]
If I add the code to my `HttpJwtHandler`, there are other errors
```C#
request = request.SetBrowserRequestMode(BrowserRequestMode.NoCors);
```

![2](https://user-images.githubusercontent.com/15957347/80607782-7b6a0900-8a68-11ea-9b4f-380baad46a29.jpg)

**Comment by javiercn** [comment]
@ZhangGaoxing thanks for contacting us.

I'm not sure what HttpJwtHandler does since that's not something that we ship. I would suggest a couple of things:
* Capture the outgoing network request from the browser and ensure it has all the bells ans whistles.
* Check the CORS response to make sure the appropriate headers are present.

I think that if you are doing a cross-origin request the request mode should be something different, like 'cors' since using NoCors will block the cross-domain request.

If you find a header is missing in the response, please include a minimal repro project with detailed instructions on how to reproduce the issue.

**Comment by stubclan** [comment]
I am having similar issue with dotnet  webapi.  I setup a sample webapi application and followed similar pattern below and the CORS issue was solved for me.
https://github.com/dotnet/aspnetcore/issues/16672#issuecomment-548131275

However, when I enabled the same setting in my existing API, CORS seems to be consistent. In Startup configurations, CORS setup can be affected by lots of things it seems. One could be your HTTP Client Handler. 

Have you tried disabling your Handler and Check if the issue persists?

**Comment by javiercn** [comment]
Closing since we haven't heard back in a while.

Using https://github.com/dotnet/AspNetCore.Docs/issues/18198 to track doc improvements in this area.

**Comment by ZhangGaoxing** [comment]
I found the cause of the problem. I looked at the log and found that it was because the server application threw an exception. But why does the client application report a CORS error. Ha-ha😂

**Comment by javiercn** [comment]
Likely because 500 responses don't contain CORS headers

**Comment by MTabakoglu** [comment]
I have the same problem, @ZhangGaoxing. what kind of error did you get on the server side? There is no problem in local.

**Comment by ZhangGaoxing** [comment]
@MTabakoglu Check the database settings😂
