### ISSUE TITLE
LocationChangedEventArgs.IsNavigationIntercepted is always false (WASM)

### ISSUE THREAD

**Issue by shadow-cs** [dotnet/aspnetcore#21320]
No matter how I change the location (I'm changing hash) the `IsNavigationIntercepted`  property is always `false`.

### Describe the bug

I expected that manual navigation or calling JS would set `IsNavigationIntercepted` to `true` but I always got `false`.

Maybe the problem is, I'm changing the hash and not the path (btw if I change the path the page reloads without any notification). Or maybe I failed to set-up navigation properly?

### To Reproduce

- Subscribe to `NavigationManager.LocationChanged`
- Update hash by hand in the browser (`IsNavigationIntercepted == false`)
- Change `window.location.hash` (`IsNavigationIntercepted == false`)
- Call `NavigationManager.NavigateTo` (`IsNavigationIntercepted == false`)

### Further technical details

- ASP.NET Core 3.1.300-preview-015115
- Windows 10.0.19041
- Chrome 81.0.4044.122

**Comment by javiercn** [comment]
@shadow-cs thanks for contacting us.

In all the cases you are describing the navigation is not intercepted. Navigation is intercepted when a user clicks an `a` link and so on. In the 2 first cases you described, Blazor doesn't have any chance to intercept the navigation at all, and in the 3rd case you are triggering it programmatically, so it is not intercepted.
