### ISSUE TITLE
Unable to remove breakpoint with Blazor WASM while debugging

### ISSUE THREAD

**Issue by StevenRasmussen** [dotnet/aspnetcore#21328]
When debugging a Blazor WASM project, if I set a breakpoint and then try to remove it while debugging, the breakpoint is still hit and execution stops even though the breakpoint has been "removed".

Environment:
Visual Studio 2019 Version 16.6.0 Preview 4.0
Blazor: v3.2.0-preview5.20216.8
Browser: MS Edge Version 81.0.416.64 (Official build) (64-bit)

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19682
