### ISSUE TITLE
Inject Custom Route Builder into Router

### ISSUE THREAD

**Issue by tankbob** [dotnet/aspnetcore#21332]
### Is your feature request related to a problem? Please describe.
I'm trying to use my own routing attributes to provide customized routing templates, this would also help with nested routing or any other convention based routing algorithm

### Describe the solution you'd like
Can we make ```Microsoft.AspNetCore.Components.Routing.Router``` able to take an injected service (or collection of injected services) that can translate from a Type to an array of route templates.  This service(s) could be then passed to ```Microsoft.AspNetCore.Components.Routing.RouteTableFactory.Create``` which would then use the service to get the array of templates instead of just looking for the route attribute.  The  existing code that looks up the route attribute could then be converted to one of these services.

**Comment by pranavkm** [comment]
@tankbob we think creating a custom routing component that suites your needs would be the way to go here. You're free to copy the implementation of the `Router` component and ancillary types to your own project.
