### ISSUE TITLE
Blazor Proj. TargetFramework 2.1 Publish is not giving exe file

### ISSUE THREAD

**Issue by ahmetsekmen** [dotnet/aspnetcore#21333]
I am publishing my cool blazor WASM app. Its not asp.net core service hosted. (Just WASM proj)
Using Visaul Studio 2019 (16.5.4)

>  <PropertyGroup>
>     <TargetFramework>netstandard2.1</TargetFramework>
>     <RazorLangVersion>3.0</RazorLangVersion>
>     <OutputType>Exe</OutputType>
>   </PropertyGroup>

Project Publishing output is not giving exe file. 
I want to execute my app(self hosting / kestrel)
But i couldn't

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Blazor WebAssembly apps don't produce `.exe` files. This is by design.
You can use the `Hosted` project template to get an exe from the server project.

**Comment by ahmetsekmen** [comment]
Thanks for informing.
Is it possible to host webassembly app with "cmd" ?
