### ISSUE TITLE
Rename the "Enable LSP Razor editor" feature flag to "Enable experimental Razor editor"

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21335]
@danroth27 / @mkArtakMSFT is "experimental" a good substitute for "LSP"?

**Comment by NTaylorMullen** [comment]
As part of this we should also update the description of the feature flag to mention the requirement to re-open documents

**Comment by ryanbrandenburg** [comment]
This PR is merged.
