### ISSUE TITLE
CompletionOptions from Multiple Language Servers Aren't Respected

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#21346]
If I add:

```csharp
AllCommitCharacters = new[] { ":", ">" },
```

to the `Razor.LanguageServer CompletionOptions` [here](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs#L155-L160) these characters aren't accepted to commit completions proposed by this language server. 

I have to add the commit char (`:`) to the `LanguageServerClient CompletionOptions` [here](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs#L21).

Now even though the `Razor.LanguageServer` proposes the completion, and doesn't have any commit characters specified in the `CompletionOptions`, `:`, which was specified in the `LanguageServerClient` successfully commits the completion.

This poses as issue in cases like [this](https://github.com/dotnet/aspnetcore-tooling/pull/1825/files#r417657332) where we want `:` to commit the `@onkeypress` razor directive attribute but not the `onkeypress` html attribute.

**Comment by TanayParikh** [comment]
Once this issue is resolved, https://github.com/dotnet/aspnetcore-tooling/pull/1825/files#diff-dddd024b99ebbf567eea61e984e7a9f6R21 needs to be updated to remove the `:` commit char. 

```csharp
AllCommitCharacters = new[] { ":", ">" },
```

also needs to be added to the `Razor.LanguageServer CompletionOptions` [here](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs#L155-L160) to allow for commits of Razor directive attributes and `<text>` tags.

**Comment by NTaylorMullen** [comment]
Should file a vsts issue to track this and make sure the LSP platform team knows about it

**Comment by TanayParikh** [comment]
https://github.com/dotnet/aspnetcore-tooling/pull/1825 has been merged in.

Created a VSTS issue and reached out to the appropriate team to see if we can get this issue resolved to support `CompletionOptions.AllCommitCharacters` from multiple language servers. Marking as blocked as it depends on an external dependency.

**Comment by TanayParikh** [comment]
The fix for this was merged in and inserted. Will verify once the new build propagates.

**Comment by TanayParikh** [comment]
Tried out the latest insertion, however the issue seems to persist. 

Investigated into the VS LSP codebase, and identified a potential issue. Following up with them on the existing [VSTS issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1117086).

**Comment by TanayParikh** [comment]
New [VSTS Issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1085910).

**Comment by TanayParikh** [comment]
Still blocked externally by [LSP Platform](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1085910), clearing milestone.

**Comment by TanayParikh** [comment]
This should be unblocked soon (LSP Platform just inserted this in).
