### ISSUE TITLE
some bug about http get url url parsing on .net core 3.1 ?

### ISSUE THREAD

**Issue by sgf** [dotnet/aspnetcore#21353]
### Describe the bug
The reason is:I think the design of webapi is terrible and relies too much on attributes. therefore I wanted to use my own ActionFilter instead of the built-in object(Action Paramaters) parsing.
I want to use url to pass json, because I like to use http get pass parameter. Everything had been smooth on the old code.
**but the bug stoped me.**
when i test old code New asp.net core web api i got some wrong result.
this is an internal bug,i can't do something on my filter to control it.

### To Reproduce

 ```C#
    [ApiController]
    [Route("[controller]/[action]")]
    public class WeatherForecastController : ControllerBase {

      public class ABC {
            public string A { get; set; }
            public string B { get; set; }
        }
//correct
       //public IActionResult Put(string id) {
           // return new JsonResult(id);
        //}
//incorrect
       public IActionResult Put(ABC id) {
            return new JsonResult(id);
        }
}
    public class Startup {
	  services.AddControllers(options => {
                options.Filters.Clear();
                options.Filters.Add(typeof(JsonFilter));throwing
            });
}
```
**when i use the  `Put(string id)`, its fine!
when i use the  `Put(ABC id)`,i got error:**

`https://localhost:44340/weatherforecast/put/?jsonrqdata={%22A%22:%22AA%22,%22B%22:%22BB%22}`
####The input was not valid
```json 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"|f1984e3f-44f0884ef2782e28.","errors":{"":["The input was not valid."]}}
```

### Further technical details
- Microsoft.AspNetCore.App 3.1.3
- Version:   3.1.201  
- vs 2019  16.5.4

I think that when I use ActoinFilter to take over Action parsing behavior, the built-in parameter parsing should not make any decision for me. Otherwise, when I encounter the above situation, I become uncontrollable.

https://github.com/sgf/CoreApiTestBugRP

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by sgf** [comment]
this is not about how to use ASP.NET Core.
i create this that because it seems the asp.net core changed Some behavior of  the ActionFilter.
Some behaviors that were supposed to work. In short, with the same input, I get different results. And this has no direct cause with my code, but the logic inside the asp.net core seems to have changed.
And I think this is a bug. I suggest you better try my repository and make a conclusion, or try to figure out what I am talking about? If I am not clear enough, please let me know and I can try to add it further.

**Comment by sgf** [comment]
Let me put it this way, after I defined the global ActionFilter, asp.net core should not bypass my ActionFilter anyway, the response message is: "The input was not valid". Because this is my own ActionFIlter's job (I Clear the defaults filters (the NoSpoortedFilter)). But I debug at the point of interruption of my ActionFilter, and did not hit, that is, the request is not intercepted by the asp.net core and even processed inside Well, this should not be the case.

**Comment by sgf** [comment]
The problem has already been solved.
the Reason is because:
in asp.net core web api the Model Binding Executing before the ActionFilter.
So i need disable the Model Binding.
then i search  how to disable Model Binding.
well,i got the result is:
```C#
  services.Configure<ApiBehaviorOptions>(options => {
                options.SuppressModelStateInvalidFilter = true;
            });
```
