### ISSUE TITLE
VS publishing is broken if you have resx files

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#21355]
The is the most severe of the loc-related publishing issues I found yesterday, since it breaks the most mainstream localization scenario.

**Repro setup:**

- Create Blazor WebAssembly "hosted" app
- At the root of the Client project, add a folder called "Resources"
- On that new folder, rightclick -> Add -> New Item -> "Resources file" named App.es.resx
- In the resx, add an entry named "MyString" with value "MyValue for es"
  - Note: leave "Access modifier" on default "No code generation" setting

**Verifying it works OK from command line:**

  - Using command line, `cd Server` and `dotnet publish -c Release`
    - Run `ls bin\Release\netcoreapp3.1\publish\wwwroot\_framework\_bin\es\`
      - Notice that a satellite assembly *is* present here
    - Run `more bin\Release\netcoreapp3.1\publish\wwwroot\_framework\blazor.boot.json`
      - Notice that `satelliteResources` lists the `es` assembly
    - Now `rm -rf bin\Release` to ensure you have a clean state for the next check

**Verifying it's broken from VS:**

  - Right-click the Server project and choose Publish
  - Select "Folder" and click Next/Finish until the dialog goes away
  - Click "Publish"
  - Back in the command line, try the same inspection steps as before:
    - Run `ls bin\Release\netcoreapp3.1\publish\wwwroot\_framework\_bin\es\`
      - This time it will tell you that the `es` directory does not exist here
    - Run `more bin\Release\netcoreapp3.1\publish\wwwroot\_framework\blazor.boot.json`
      - Notice that `satelliteResources` is now `null`

Obviously the localization can't work at runtime since the satellite assembly isn't there.

**Additional considerations for PWAs:**

For PWAs (apps that have a service worker assets manifest), this issue also results in the service worker assets manifest containing wrong information. If I recall correctly, the satellite assembly *was* listed in the service worker assets manifest even though it's not present on disk. At runtime then, the service worker tries to fetch the satellite assembly, gets back a 404, and reports it as an integrity check failure. This prevents the service worker from ever being installed.

**Comment by SteveSandersonMS** [comment]
As a sidenote, some good news :) Yesterday I thought I had **also** found two other bugs with loc+publishing:

 * Linker strips some localization APIs required
 * When having a default-culture resx file in addition to other cultures, blazor.boot.json's satelliteAssemblies collection is 'null'

However I've been trying to write up repro steps and in fact I can no longer repro either of those. My guess is that they were just extra symptoms of the real issue I'm reporting here. So in summary I now think there is only one real loc+publishing issue to report, which is the one mentioned above.

**Comment by SteveSandersonMS** [comment]
Hopefully the fix for this is https://github.com/dotnet/aspnetcore/pull/21347, but I thought I should write the issue up anyway.

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/21347
