### ISSUE TITLE
Facing deep link issue with our app after migrating to asp.net core 3.1 and Angular 8.

### ISSUE THREAD

**Issue by premchandpl76** [dotnet/aspnetcore#21359]
We have migrated our portal from (Angular 5 + Asp.Net Core 2.2 with MVC) to (Asp.Net Core 3.1 with MVC + Angular 8) . We used VS 2019 Angular template for the same.  

Our application is working fine with default route (https://localhost:44332). Request goes to the startup.cs and since user is unauthenticated, user is redirected to default route to HomeController where user gets challenged and once authenticated (in AAD), HomeController redirects user to correct angular route based on role.

However for any angular component direct path (Deep Link) (https://localhost:44332/<component>) in a private Window, request directly starts bootstrapping angular <component> without first getting user authenticated. Request never goes to HomeController, henceforth all api calls result in forbidden. It also appears that request is going into infinite redirects to same page/component as forbidden error messages from different api call keeps repeating.  

Note, same code was working fine with Angular 5 + ASP.Net Core 2.2 with MVC.

**Comment by javiercn** [comment]
@premchandpl76 thanks for contacting us.

Can you provide a minimal repro project that showcases the issue so that we can better understand your problem?

**Comment by premchand76** [comment]
This issue can be closed and we with different approach to solve the issue
