### ISSUE TITLE
Integration Testing Scoped Service?

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#21360]
I'm trying to add some integration tests to an ASP.NET Core 3.1 application which uses NHibernate instead of Entity Framework.

I've been following the [documentation](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1) and it was all pretty clear. But instead of AddDbContext, instead I said the following:

```
services.AddScoped(p => {
    var sessionFactory = p.GetRequiredService<ISessionFactory>();
    var session = sessionFactory.OpenSession();

    // Create the database
    new SchemaExport(configuration).Execute(false, true, false, session.Connection, null);

    return session;
});
```

Then before my call to client.GetAsync(url) in my test I populated some initial data like so:

```
using var scope = _factory.Services.CreateScope();
var session = scope.ServiceProvider.GetRequiredService<ISession>();

... Populate some initial data here
```

However whenever I tried to get the populated data in my controller, the data doesn't exist. 
I added a breakpoint in the factory callback inside my service registration and noticed that it was being called despite me stating AddScoped (I'd assume this would be for the lifetime of the test). This causes the session to be recreated and the data is lost.

My first thought was to look at how Entity Framework does it and it looks like the data context is a singleton. However this would require me to reset the data after every test.

Therefore I changed my service registration to the following:

```
services.AddScoped(p => {
    var sessionFactory = p.GetRequiredService<ISessionFactory>();

    if (_session != null && _session.IsOpen)
        return _session;

    var session = _session = sessionFactory.OpenSession();

    // Create the database
    new SchemaExport(configuration).Execute(false, true, false, session.Connection, null);

    return session;
});
```

This caches the service in a private field and returns the session as long as it still open (since it is disposed after each test runs). This works fine but I don't get why I need to do this.

**Comment by nfplee** [comment]
I think I've figured out why this happens. Since I create a new scope to populate the initial data then that is why the factory is called multiple times. Please correct me if I'm wrong.

However this creates a problem since we can't retrieve the scoped service without creating a scope.

**Comment by anurse** [comment]
> However whenever I tried to get the populated data in my controller, the data doesn't exist.

The controller is likely running in a different scope. **Every** call to `CreateScope` creates a brand new scope and any scoped DI services resolved within that scope are recreated from scratch. So if you are creating a scope, and populating some data in the service, that data is only present for instances **resolved specifically from that scope**. When the controller runs it **creates a new scope** so it gets a brand new object.

**Comment by nfplee** [comment]
Thanks @nurse, yeah that's what I discovered. It would be great if there was a hook to populate the initial data without creating a new scope using the WebApplicationFactory.
