### ISSUE TITLE
Allow Global Razor Methods Via Global RenderTreeBuilder And Add Region Syntax

### ISSUE THREAD

**Issue by TheFanatr** [dotnet/aspnetcore#21361]
Currently, the Razor Components syntax engine recognizes the following syntax as valid in `@code` blocks, but the generated source references a `RenderTreeBuilder` instance that does not exist.

```
void AddRazorToFile()
{
    @:This is Razor content that should be added to the render tree.
    @:It is unfortunate, however that the source to do so references a non-existent __builder.
}
```

The code generated is as follows.

```csharp
void AddRazorToFile()
{
    __builder.AddMarkupContent(87, "        This is Razor content that should be added to the render tree. ");
    __builder.AddMarkupContent(88, "        It is unfortunate, however that the source to do so references a non-existent __builder. ");
}
```

This is technically a bug, but I am filing a feature request instead as I believe the solution to this could involve allowing such "templated" methods in Blazor in general, as I will describe below, as opposed to simply showing an error.

The solution to this error naively is to declare the method somewhere that has access to `__builder`, but in doing so, another problem arises; the sequence numbers are totally off, leading to numerous problems such as exceptions being thrown that attribute values are being declared out of order to `RenderTreeBuilder.OpenElement` or `RenderTreeBuilder.OpenComponent` calls. `RenderFragment`s address this by using the `RenderTreeBuilder.AddContent` overload that accepts a `RenderFragment`, which uses the `RenderTreeBuilder.OpenRegion` and `RenderTreeBuilder.CloseRegion` APIs to adjust the numbers and not cause errors. [These APIs](https://github.com/dotnet/aspnetcore/blob/4e04b81415d28ced0cefff2b53bd3921b875ed30/src/Components/Components/src/RenderTree/RenderTreeBuilder.cs#L625), for some reason, are not public, and so such adjustment is not possible manually, causing these Razor-syntax-containing "templated" methods to be effectively useless.

My proposed solution to these issues are threefold. Firstly, the `RenderTreeBuilder.OpenRegion` and `RenderTreeBuilder.CloseRegion` APIs should be made public to allow scenarios where manual sequence adjustment is needed such as what will follow. Secondly, a global `RenderTreeBuilder` instance should be accessible by component classes. If `ComponentBase` cannot be modified to include such access, then I propose that the member be generated along with the markup. This would be used by callers of "templated" methods to provide the method with a `RenderTreeBuilder` instance. This would fix all the issues, but could be prohibitively clunky to use, so lastly, I propose the introduction of a new syntax in Razor as `$:` and `${ }`, which is similar to `@:` and `@{ }`, that would, for it's scope, set the global `RenderTreeBuilder` to the primary available builder used by the Razor code generator to render markup, and open then close a sequence region for every statement in the block's scope.

This would mean that it would be possible to declare "templated" razor methods, and use them like you would `RenderFragments` with decreased code complexity and cleaner syntax, as shown below.

```razor
$: RenderCoolButton();
<span>Woah</span>
${
    RenderCoolButton();
    RenderCoolButton();
    RenderCoolSection();
}
```

With the contents of `@code` as follows.

```
void RenderCoolButton() => <button type="button">Click This Button, It's Cool</button>
void RenderCoolSection()
{
    <div class="cool">
        This sure is a section of this document.
        <br />
        <strong>This part is pretty strong</strong>
    </div>
}
```

This is significantly better than what is needed on the declaration side for such members if the `RenderFragment` API is used. Firstly, if the markup needs to access instance data, the delegate needs to be regenerated for every call by using either a method or a non-auto property, and declaring blocks of markup has really finicky and odd syntax, with a lot of caveats. This is shown below.

```razor
RenderFragment AuthenticationDetails =>
@:@{
    <h5>Given Details</h5>

    <br />

    @:Handle: @AuthenticationData.Handle
    @:Password: @AuthenticationData.Password

    <br />
    <br />
}
; // This needs to be on a separate line or the parser gets confused and omits it.

RenderFragment AuthenticationDetails2 =>
<text>
    <h5>Given Details</h5>

    <br />

    @:Handle: @AuthenticationData.Handle
    @:Password: @AuthenticationData.Password

    <br />
    <br />
</text>
; // This needs to be on a separate line or the parser gets confused and omits it.
```

Though the call site is marginally simplified by only needing to use `@Delegate` instead of `$: Delegate();`, the declaration site is vastly simplified and much more intuitive. The verbosity of the call site can be addressed with syntax sugar such as having a semicolon inserted at the end of a `$:` statement and by possibly removing the parameter brackets entirely when no value provisioning is needed to the delegate. The syntax could also eventually be simplified to `$Delegate` with a possible tradeoff of increased implementation complexity. That being said it may even be possible to translate `$Delegate` into `OpenRegionRunAndCloseRegion(Delegate)` and `$Delegate("text")` into `OpenRegionRunAndCloseRegion(() => Delegate("text"))`, which is currently a fictional API but would be fairly trivial to implement.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will revisit support of `@:` in a later milestone. For now this is not supported.

**Comment by TheFanatr** [comment]
> We will revisit support of `@:` in a later milestone.

@mkArtakMSFT Just in case it isn't clear, this proposal is for allowing "templated" methods to be run like they are in Razor pages, but without the Blazor `RenderTreeFrame` sequence numbers being all over the place; this has very little to do with `@:`, and has a lot more to do with supporting some form of `RenderTreeBuilder` automatic region declaration within these methods or at the call site so that "templated" methods are executed like how `RenderFragment`s are, with `RenderTreeBuilder.OpenRegion` and `RenderTreeBuilder.CloseRegion` prepended and appended respectively to the markup generation of the method, so that exceptions such as the one below aren't encountered when such methods are used.

```
System.InvalidOperationException: Attributes may only be added immediately after frames of type Element or Component
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AssertCanAddAttribute()
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddAttribute(Int32 sequence, String name, String value)
```

After experimenting with this further, it would seem that both the declaration site and call site and the declaration site would need to be modified so that the following translation from a local "templated" method to a rendered one would be correct.

```
void AddRazorToFile()
{
    @:This is Razor content that should be added to the render tree.
    <br />
}
```

```csharp
void AddRazorToFile()
{
    __builder.AddMarkupContent(0, "        This is Razor content that should be added to the render tree. ");
    __builder.AddMarkupContent(1, "        <br> ");
}
```

With the call site as follows.

```razor
...
$: AddRazorToFile();
```

Which would get translated into the following.

```csharp
...
__builder.OpenRegion(43 /* or whatever the next sequence number is */);
AddRazorToFile();
__builder.CloseRegion();
```

This would make executing "templated" methods synonymous to executing `RenderFragment`s, as shown [here](https://github.com/dotnet/aspnetcore/blob/9025f63fc37d1d234e0dbdbf247c433e5a679f42/src/Components/Components/src/Rendering/RenderTreeBuilder.cs#L99), but with a simplified declaration site.

Note that in the original post I wrote that `RenderTreeBuilder.OpenRegion` and `RenderTreeBuilder.CloseRegion` are not public, which is untrue.

**Comment by TheFanatr** [comment]
Just to clarify, the exceptions that are currently encountered when using these "templated" methods are caused due to the sequence numbers being totally off, then when assertions run by `RenderTreeBuilder.AddAttribute` later in the markup generation verify that the call was after another `RenderTreeBuilder.AddAttribute`, `RenderTreeBuilder.OpenElement`, or `RenderTreeBuilder.OpenComponent` call, it appears to the algorithm that certain frames are out of order because the "templated" methods currently are given arbitrarily high sequence numbers. This means that the translation from the previous comment is currently more similar to the following.

```
void AddRazorToFile()
{
    @:This is Razor content that should be added to the render tree.
    <br />
}
```
```csharp
void AddRazorToFile()
{
    __builder.AddMarkupContent(97, "        This is Razor content that should be added to the render tree. ");
    __builder.AddMarkupContent(98, "        <br> ");
}
```

Thus, if the call site looks like the following, the translation is totally out of wack in terms of sequence numbers.

```razor
<br />
AddRazorToFile();
```
```csharp
__builder.AddMarkupContent(0, "        <br> ");
AddRazorFile();
```

This is because what is effectively being done here is as follows.

```csharp
__builder.AddMarkupContent(0, "        <br> ");
// Call to AddRazorToFile():
__builder.AddMarkupContent(97, "        This is Razor content that should be added to the render tree. ");
__builder.AddMarkupContent(98, "        <br> ");
```

**Comment by TheFanatr** [comment]
Here is an illustration of the above.
![image](https://user-images.githubusercontent.com/16641853/80768241-b6b71700-8afe-11ea-9fd0-0e23fdd893ea.png)

**Comment by TheFanatr** [comment]
I hid the comment above the last one because it is a bug unrelated to this, which I will file an issue for later.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
