### ISSUE TITLE
Exception in Razor Component is ignored during wasm execution

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#21364]
### Describe the bug
I have some parameter validation in a razor component used in my Blazor app. If the validation fails I throw an exception. In Blazor server side the error is detected and the error ui is activated. In Blazor client side the exception can be seen in the browser developer tools console but execution of the application continues. 

### To Reproduce

Code the following component in Fail.razor, include &lt;Fail /&gt; on your initial page:

```
"Hello, World!"
@code
{
   public override void OnInitialized()
   {
      // Real life, do some validation of parameters, here, just throw
      throw new ArgumentException("Informative argument exception message goes here");
   }
}
```

### Further technical details
Using 3.2.0-Preview5 Blazor wasm

```
C:\Solutions\OHI\Blazored.Toast>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015115
 Commit:    cd8d468337

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015115\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.803 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We already show a UI in an error situation, which we allow developers to customize as they wish. If you want to prevent any further interaction with the application, you can use that UI to do so. To learn more about this please have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1

**Comment by MarkStega** [comment]
This is not resolved -- I have the error UI html in place. Prior to preview5 this error UI was activated and the application stopped. With P5 the error is not getting activated.

**Comment by simonziegler** [comment]
Hi - I don't think you addressed this. Can you please re-open?
