### ISSUE TITLE
[Blazor] Server Side - Frequent 504 errors in AWS environment

### ISSUE THREAD

**Issue by MarcusBullock** [dotnet/aspnetcore#21369]
### Describe the bug
After deploying a blazor server side project to an Amazon Web Services environment via AWS Elastic Beanstalk, the website experiences frequent disconnects.

These disconnects do not happen locally when testing.

### To Reproduce

Deploy server side app via AWS Elastic Beanstalk, start the app, and leave it running after fetching some data.

After a minute or so, I get the following errors:
```
[2020-04-30T16:29:18.326Z] Error: Connection disconnected with error 'Error'.
```
and
```
Failed to load resource: the server responded with a status of 504 ()
```

Request Header:
```
Request URL: https://mywebserver/_blazor?id=UOPQELxzuEcaGbpNUQA01Q&_=1588264098305
Request Method: GET
Status Code: 504 
Remote Address: 3.11.236.203:443
Referrer Policy: no-referrer-when-downgrade
content-length: 550
content-type: text/html
date: Thu, 30 Apr 2020 16:29:20 GMT
server: awselb/2.0
status: 504
:authority: mywebserver
:method: GET
:path: /_blazor?id=UOPQELxzuEcaGbpNUQA01Q&_=1588264098305
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
content-type: text/plain;charset=UTF-8
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
x-requested-with: XMLHttpRequest
```

This issue is remarkably similar to this issue: https://github.com/dotnet/aspnetcore/issues/19094
with the obvious difference that this is an AWS environment.

Any help much appreciated

**Comment by BrennanConroy** [comment]
Can you check if your connection is using websockets or longpolling?

If it's using WebSockets, can you verify that you've configured WebSockets correctly with AWS.

If it's using LongPolling, you probably need to set the timeout in the Elastic Load Balancer to be greater than the default of 60 seconds. 110 seconds is probably safe. LongPolling issues requests and waits 100 seconds before canceling the request.

**Comment by MarcusBullock** [comment]
thanks for such a quick reply.

i set the timeout to be 110 seconds and everything seems to be working fine now, no disconnects or 504 errors.

cheers!
