### ISSUE TITLE
Blazor App Erros ao Usar Tradutor do Chrome

### ISSUE THREAD

**Issue by geraldons** [dotnet/aspnetcore#21374]
Execute qualquer APP de Demonstração do Blazer com o Chrome Tradutor e o mesmo apresentará erros.

blazor.server.js:15 [2020-04-30T18:16:35.125Z] Error: There was an error applying batch 14.
e.log @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
r @ blazor.server.js:15
e.processBatch @ blazor.server.js:15
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:8 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at e (blazor.server.js:8)
    at e (blazor.server.js:8)
    at Object.e [as removeLogicalChild] (blazor.server.js:8)
    at e.applyEdits (blazor.server.js:8)
    at e.updateComponent (blazor.server.js:8)
    at Object.t.renderBatch (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:15)
    at blazor.server.js:15
    at Object.next (blazor.server.js:15)
    at blazor.server.js:15
e @ blazor.server.js:8
e @ blazor.server.js:8
e @ blazor.server.js:8
e.applyEdits @ blazor.server.js:8
e.updateComponent @ blazor.server.js:8
t.renderBatch @ blazor.server.js:1
(anonymous) @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
(anonymous) @ blazor.server.js:15
r @ blazor.server.js:15
e.processBatch @ blazor.server.js:15
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:15 [2020-04-30T18:16:35.536Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read property 'removeChild' of null)
 ---> System.InvalidOperationException: TypeError: Cannot read property 'removeChild' of null
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---

**Comment by javiercn** [comment]
@geraldons thanks for contacting us.

I believe this can be google translator messing up with the dom in an unsupported way.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this as this is something the translator brakes not an issue in the app.
