### ISSUE TITLE
Blazor WASM Auth Iframe rendering full page

### ISSUE THREAD

**Issue by jbomhold3** [dotnet/aspnetcore#21376]
Version preview 5

The iframe for silent refresh is doing a full render of the website. Including components.

Also, the iframe sometimes randomly appears twice

![](https://i.gyazo.com/ea26ea77b665ecad93d2aaa9c5b4ca4c.png)

**Comment by javiercn** [comment]
@jbomhold3 thanks for contacting us.

We'll look into this and update the issue appropriately. Seems like you are using either Azure AD or Azure AD B2C. Is that correct?

**Comment by jbomhold3** [comment]
Yes B2C

**Comment by captainsafia** [comment]
@jbomhold3 Thanks for reporting this issue.

I wasn't able to reproduce this on 5.0-preview8. With regard to the two iframes that are rendered, it looks like each iframe has a different client ID. With MSAL.js V1, a new iframe is created for each application scope. Is there a change that the scopes on your authentication service are being modified between calls?

**Comment by jbomhold3** [comment]
This was for blazor-wasm-preview5 have not tested yet in 5.0

**Comment by captainsafia** [comment]
Thanks for the additional info. I'd recommend trying to repro this in 5.0-preview8 (or even better 5.0-rc1 which will include an upgrade to our MSAL.js dependency). If you're able to reproduce, please reopen this issue with a sample app so that we can investigate.
