### ISSUE TITLE
login is broken for new mvc -au individual (revised: email confirmation error message not displaying)

### ISSUE THREAD

**Issue by eskensberg** [dotnet/aspnetcore#21372]
## Steps to reproduce:
dotnet new mvc -au individual

## Expected behavior:
afte registering a user, to be able to login using user credentials

## Actual behavior:
when attempting to login, I receive "Invalid login attempt." 
tried it multiple times using sql database and new registered users. I checked the db, new users were registered succesfully, just login is broken.

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
using Microsoft.EntityFrameworkCore.SqlServer

**Comment by blowdart** [comment]
@eskensberg Are you not seeing a debug display after registration?
