### ISSUE TITLE
[Blazor] IServiceCollection does not contain a definition for AddBaseAddressHttpClient

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#21377]
I upgraded a WASM app to `3.2.0-rc1.20223.4` and now the following code no longer compiles.

```
public static async Task Main(string[] args)
{
	var builder = WebAssemblyHostBuilder.CreateDefault(args);
	builder.Services.AddBaseAddressHttpClient();
```

This is not mentioned in the upgrade notes. What is the solution?

**Comment by Dennisenzo** [comment]
It's in the notes of the previous preview.

Replace calls to AddBaseAddressHttpClient in Program.cs with builder.Services.AddSingleton(new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });.
