### ISSUE TITLE
Consider running Blazor integration tests with lower level brotli compression

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#21382]
![image](https://user-images.githubusercontent.com/174281/80757764-8add6680-8ae9-11ea-8a59-8b0a6bd07e20.png)

In RazorSDK, tasks support test only parameters that are controlled by "private" parameters: https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets#L104. We could do something similar here.

**Comment by javiercn** [comment]
That sounds fine with me, I didn't do it because I didn't have time and it didn't seem to impact time drastically (builds were still fast) but definitely something we can improve in 5.0
