### ISSUE TITLE
Infinite redirects post login in Azure App Service for .net core 3.0 app

### ISSUE THREAD

**Issue by melzoghbi** [dotnet/aspnetcore#21380]
Hi,

I have asp.net core web app that authenticates through implicit flow. the application works with no issues on my local, but when i deploy it this is the behavior i see in the browser:
1)  after i successfully login in the browser.
2) many redirects and then i see this error message: we couldn't sign you in!

![image](https://user-images.githubusercontent.com/11993393/80756733-e7d81d00-8ae7-11ea-9815-abef19b5f84a.png)

The local app and deployed used the same AAD Application configs, i just added the app url into the app registration. so all OpenIdConnect configs such as: tenant id, client id, client secret...etc are the same. the difference in the behavior is only after i deploy a version into azure app service.

This is a snippet of ConfigureServices()

```
 services.AddAuthentication(auth =>
            {
                auth.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
             .AddCookie()
             .AddOpenIdConnect(opts =>
             { 
Configuration.GetSection("OpenIdConnect").Bind(opts);
});

```

any one has insights how would i fix this in .net core 3.0 app?

**Comment by blowdart** [comment]
Firstly 3.0 isn't supported any more, so please, when you have the chance please update to 3.1?

Is the app URL HTTPS? Do you have the forwarding headers middleware installed?

**Comment by Tratcher** [comment]
Please share a decrypted fiddler trace file.
