### ISSUE TITLE
if await next() is used in app.Use the app.UseDeveloperExceptionPage() is not shown.

### ISSUE THREAD

**Issue by hhvdblom** [dotnet/aspnetcore#21381]
- If I code it like this it works but preferable is that the DeveloperExceptionPage shows up. 

- Another question why is the Body a Stream and not a memorystream. I want to add a page header to every page.

```
   /// <summary>
    ///     change Stream to MemoryStream.
    /// </summary>
    /// <remarks>
    ///     we want automatically placed a breadcrumb on the page, thats 
    ///     only possible if the page can be changed.
    /// </remarks>
    /// <param name="builder">application builder</param>
    /// <returns>return modified application builder</returns>
    public static IApplicationBuilder UseBufferedResponseBody(this IApplicationBuilder builder) => builder.Use(async (context, next) =>
    {        
        // use memorystream so body can be changed.
        using var bufferStream = new MemoryStream();
        var orgBodyStream = context.Response.Body;
        context.Response.Body = bufferStream;                

        // handle incoming request      
        try
        {
            await next();
        }

        // set error
        catch(Exception ex)
        {
            // set error for error page.
            IExceptionHandlerFeature exceptionHandlerFeature = new ExceptionHandlerFeature { Error = ex };
            context.Features.Set(exceptionHandlerFeature);

            // 512: ajax request generates the error, 513: page link generates the error
            context.Response.StatusCode = context.Request.Headers["X-Requested-With"] == "XMLHttpRequest" ? 512 : 513;
        }

        // if necessary redirect to another page 
        if (context.Response.StatusCode != StatusCodes.Status200OK && !context.Response.HasStarted)
        {
            // page errors.
            bool redirect = false;
            string path = null;
            switch(context.Response.StatusCode)
            {
                case StatusCodes.Status404NotFound:
                    redirect = true;
                    path = "/home/notfound";
                    break;                

                case StatusCodes.Status403Forbidden:
                    redirect = true;
                    path = "/home/notauthorized";
                    break;

                case StatusCodes.Status500InternalServerError:
                case 512:
                case 513:
                    redirect = true;
                    path = "/home/error"; 
                    break;
            }

            // redirect to notfound or notauthorized page.
            if (redirect)
            {
                // path to notfound or notauthorized page
                string originalPath = context.Request.Path.Value;
                context.Items["originalPath"] = originalPath;
                context.Request.Path = path;

                // reset endpoint/route values if already set
                context.SetEndpoint(endpoint: null);
                var routeValuesFeature = context.Features.Get<IRouteValuesFeature>();
                routeValuesFeature?.RouteValues?.Clear();

                // handle request to navigate to other page.
                await next();
            }
        }
          
        // copy the orginal body to te new memorystream.
        bufferStream.Seek(0, SeekOrigin.Begin);
        await bufferStream.CopyToAsync(orgBodyStream);
        context.Response.Body = orgBodyStream;                        
    });  
```

**Comment by Tratcher** [comment]
> * If I code it like this it works but preferable is that the DeveloperExceptionPage shows up.

Your handling all exceptions. The dev exception page won't work unless it can catch exceptions. In the template we deal with this by having the dev exception page enabled in development and the exception handler enabled in production. There's no way to do both at the same time, they're handling the same event.
https://github.com/dotnet/aspnetcore/blob/100823af0d50333b6ee10147a20b35196fcbbc7d/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L130-L139

Your first catch block needs to check HasStarted before modifying the response. See this example:
https://github.com/dotnet/aspnetcore/blob/100823af0d50333b6ee10147a20b35196fcbbc7d/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L94-L98

The `if (redirect)` block should also clear the MemoryStream contents.

> * why is the Body a Stream and not a memorystream. I want to add a page header to every page.

Buffering every response is extremely in-efficient. It adds a lot of memory overhead to your app and it adds latency for the client. Adding a header to every page is better accomplished as part of your MVC layout generation than by re-writing the content after the fact.
https://github.com/dotnet/aspnetcore/blob/100823af0d50333b6ee10147a20b35196fcbbc7d/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/Shared/_Layout.cshtml#L11-L12

**Comment by hhvdblom** [comment]
You are right! I am handling all exceptions in the try..catch. You know why? If I don't do that the Exceptions will not be handled by the DeveloperExceptionPage. What I am trying to say is that if you implement a app.Use the DeveloperExceptionPage won't fire if there is an exception in the await next().  

As a test: implement an app.Use with just a await next() in it and you will see the DeveloperExceptionPage won't show up. Comment the app.Use and the DeveloperExceptionPage will show up again.

I have a Index controller with
int x = 8;
int y = 8 / x;
so when the page is fired it will throw a divide by zero exception.

And yes I understand a buffered Memorystream is slower as a Stream, but it feels wrong that the Body cannot be changed.

**Comment by Tratcher** [comment]
Can you show the actual code for your basic broken example, including the relative positions of DeveloperExceptionPage and your Use?

**Comment by hhvdblom** [comment]
Chris, I am not at work right now but will post it monday.
