### ISSUE TITLE
ObjectResultExecutor could output a clearer log w.r.t the concrete type of ObjectResult

### ISSUE THREAD

**Issue by andrewjsaid** [dotnet/aspnetcore#21393]
### Is your feature request related to a problem? Please describe.

`ObjectResultExecutor` gives potentially misleading log. Specifically `"ObjectResultExecuting"` is define in `MvcCoreLoggerExtensions` as follows:
`Executing ObjectResult, writing value of type '{Type}'.`

The misleading part is when a controller returns, for example, a `NotFoundObjectResult(string)` or an `OkObjectResult(string)`. The logs look like this in either case:
`[Information] Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Executing ObjectResult, writing value of type 'System.String'.`

### Describe the solution you'd like
My suggestion is to output the declared runtime/real/concrete type of `ObjectResult` along the lines of
`Executing {ConcreteObjectResultType}, writing value of type '{Type}'.`

The above message is more useful because
1) It provides more detail as to what happened.
2) It does not leak implementation details of `NotFoundObjectResult`.

### Additional context
Of course, there are other ways to discover the same information (such as the Status Code) so this issue is not critical. Another point against this issue is that the `ControllerActionInvoker` does specify the runtime type of `ActionResult`.

**Comment by pranavkm** [comment]
> My suggestion is to output the declared runtime/real/concrete type of ObjectResult along the lines of
Executing {ConcreteObjectResultType}, writing value of type '{Type}'.

This sounds fine. Would you like to send us a PR for this change?

> It does not leak implementation details of NotFoundObjectResult.

Can you elaborate on this?

**Comment by andrewjsaid** [comment]
> This sounds fine. Would you like to send us a PR for this change?

Sure thing! I'll give it a try.

>It does not leak implementation details of NotFoundObjectResult.
Can you elaborate on this?

The more I try to write an explanation the less I'm sure what I meant. However, I think I meant that from the perspective of a somebody reading the logs, whether or not `NotFoundObjectResult` relies on the base class's `ExecuteResultAsync` is not relevant to my concerns and is thus an implementation detail.

**Comment by rynowak** [comment]
This seems like a nice improvement 👍

**Comment by docmaster2** [comment]
![перспектива](https://user-images.githubusercontent.com/51852126/81338313-15f3c900-90b5-11ea-8e0d-dae37e4944b9.jpg)
second improvement

**Comment by rynowak** [comment]
Thanks!

**Comment by docmaster2** [comment]
интересуют реквизиты картины,может быть ретро,модерн,современный стиль.
