### ISSUE TITLE
Debugging BlazorWebAssembly

### ISSUE THREAD

**Issue by PavanDhariwal** [dotnet/aspnetcore#21396]
When installing a progressive web app during debug, the following error is displayed on the next run.

An unhandled error has occured. Reload.

Installed following these steps [https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/](url). Visual Studio 2019 16.6 Preview

Steps to repoduce

1. Create a new Blazor Web Assembly project as a progressive web app
2. Build and debug under 'BlazorWebAssembly' option
3. Once the app has loaded, click the plus symbol in the address bar and install app. This will install and then reopen as a PWA
4. Stop your debug session
5. Try to debug again either via the play button, f5 or the debug menu in Visual Studio 2019
6. Error is displayed and the app doesn't load.

There is no way to uninstall the app. Clicking uninstall the app takes you to programs and features, where it is not displayed to uninstall.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by PavanDhariwal** [comment]
Just to add to this. You can delete the app from here but has no effect on running it.

C:\Users\{username}\AppData\Local\Temp

C:\Users\{username}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Chrome Apps

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we've seen in the past. If you have a small repro we'd be interested in looking into it.

**Comment by PavanDhariwal** [comment]
> Thanks for contacting us. This is not something we've seen in the past. If you have a small repro we'd be interested in looking into it.

Sure. Attached.
[DRA_Blazor.zip](https://github.com/dotnet/aspnetcore/files/4600712/DRA_Blazor.zip)

**Comment by captainsafia** [comment]
@PavanDhariwal It looks like the reproduction project you provided isn't a PWA. Perhaps you attached the incorrect file?

I went ahead and created a PWA app and wasn't able to repro the issue you saw. If you can provide:

* What version of Edge are you using?
* What is the stack trace for the error that is displayed when you are trying to debug

**Comment by PavanDhariwal** [comment]
Hey,

Apologies, I uploaded the wrong project. Please see attached and follow steps in original post.

Thanks,

Pavan
[BlazorWebAssembly.zip](https://github.com/dotnet/aspnetcore/files/4649152/BlazorWebAssembly.zip)

**Comment by captainsafia** [comment]
@PavanDhariwal Is the error that you refer to in your issue the on that is thrown in the console?

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Microsoft.AspNetCore.Components.Forms.InputTextArea requires a cascading parameter of type EditContext. For example, you can use Microsoft.AspNetCore.Components.Forms.InputTextArea inside an EditForm.
System.InvalidOperationException: Microsoft.AspNetCore.Components.Forms.InputTextArea requires a cascading parameter of type EditContext. For example, you can use Microsoft.AspNetCore.Components.Forms.InputTextArea inside an EditForm.
  at Microsoft.AspNetCore.Components.Forms.InputBase`1[TValue].SetParametersAsync (Microsoft.AspNetCore.Components.ParameterView parameters) <0x2cb8710 + 0x00056> in <filename unknown>:0 
```

If so, this is related to the use of the `InputTextArea` component in your Index.razor file. The [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1) have more information on how to use that component.

Removing the buggy code mentioned above, I am able to debug in both the browser and the PWA container.

**Comment by PavanDhariwal** [comment]
I can indeed confirm I am an idiot :-).
