### ISSUE TITLE
Blazor wasm AddJsonFile fails with error 

### ISSUE THREAD

**Issue by paul-wade** [dotnet/aspnetcore#21391]
Running the latest preview builds blazor wasm.
I've followed the instructions provided here https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#configuration

I'm getting the following error.
"blazor.webassembly.js:1 ﻿System.ArgumentException: The path must be absolute."
This is how I have wired my config in Program.
 builder.Configuration.AddJsonFile("appsettings.json", false, false);

I have added an appsettings.json file to wwwroot.

I could use some help figuring this out my eyes hurt.

**Comment by conficient** [comment]
Not sure if the AddJsonFile is meant to work in a Blazor WASM context but there is a way to load the appsettings.json from a `wwwroot` folder:
```c#
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);

            await LoadAppSettingsAsync(builder);

            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            await builder.Build().RunAsync();
        }

        /// <summary>
        /// Load appsettings.json from the  wwwroot folder
        /// </summary>
        /// <param name="builder"></param>
        /// <returns></returns>
        private static async Task LoadAppSettingsAsync(WebAssemblyHostBuilder builder)
        {
            // read JSON file as a stream for configuration
            var client = new HttpClient() { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) };
            // the appsettings file must be in 'wwwroot'
            using var response = await client.GetAsync("appsettings.json");
            using var stream = await response.Content.ReadAsStreamAsync();
            builder.Configuration.AddJsonStream(stream);
        }
    }
```
This should work okay (tested on Blazor WASM RC1)

**Comment by paul-wade** [comment]
Thanks @conficient that will be a good work around to get me going. If you look at the link I included. They do mean to support adding a config files with AddJsonFile 

additionally https://github.com/dotnet/aspnetcore/issues/19178 remarks that it is believed to be fixed with 3.1.102 of the sdk. I believe I am running the latest of everything however.

**Comment by pranavkm** [comment]
Blazor will load `appsettings.json` and `appsettings.{Environment}.json` by default as long as they're present in the wwwroot folder. Unless you're trying to load a differently named config file, you do not need to explicitly load files as pointed out by @conficient's sample.

**Comment by pranavkm** [comment]
@guardrex should we call this ^ out in the docs - https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#configuration?

**Comment by paul-wade** [comment]
@pranavkm I sort of felt the documentation was hinting at that. However my config is null if leave it out.

**Comment by pranavkm** [comment]
If you're still running in to this, could you share a minimal app that reproduces the problem?

**Comment by paul-wade** [comment]
@pranavkm Yes give me a few minutes to test again. Also are you saying that manually adding appsettings.json with AddJsonFile SHOULD raise the error I showed? I've not tested with another file name yet but the documentation says addjsonfile should work. It does not for me. latest vs2019 and a straight up new from template. reproduces for me.

**Comment by paul-wade** [comment]
@pranavkm I placed a new json file in wwwroot of my project and called builder.Configuration.AddJsonFile("test.json");

so the issue persists?

**Comment by pranavkm** [comment]
> Also are you saying that manually adding appsettings.json with AddJsonFile SHOULD raise the error I showed?

Yes. Blazor does not map the wwwroot as a file system. It does however download and configures wwwroot/appsettings.json file if present.

**Comment by paul-wade** [comment]
Then it seems the documentation is wrong and this sample is invalid?

builder.Configuration
    .Add(memoryConfig)
    .AddJsonFile("cars.json", optional: false, reloadOnChange: true);

**Comment by guardrex** [comment]
> should we call this ^ out in the docs

It's called out this way currently ...

> Blazor WebAssembly supports configuration from:
>
> * The File Configuration Provider for app settings files by default:
>   * *wwwroot/appsettings.json*
>   * *wwwroot/appsettings.{ENVIRONMENT}.json*
> * Other configuration providers registered by the app.

The *cars.json* example was my idea ... reviewed but untested in the heat of getting the issues closed.

@paul-wade Did you try placing your *cars.json* at the root of the project (i.e., not in the *wwwroot* folder)?

**Comment by paul-wade** [comment]
Hey @guardrex Yeah same error when the json file is in the project root.


System.ArgumentException: The path must be absolute.
p.printErr @ blazor.webassembly.js:1
put_char @ dotnet.3.2.0-preview5.20216.1.js:1
write @ dotnet.3.2.0-preview5.20216.1.js:1
write @ dotnet.3.2.0-preview5.20216.1.js:1
doWritev @ dotnet.3.2.0-preview5.20216.1.js:1
_fd_write @ dotnet.3.2.0-preview5.20216.1.js:1
write @ dotnet.wasm:1
console_write @ dotnet.wasm:1
mono_w32file_read_or_write @ dotnet.wasm:1
mono_w32file_write @ dotnet.wasm:1
ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_try_invoke @ dotnet.wasm:1
mono_runtime_invoke @ dotnet.wasm:1
mono_wasm_invoke_method @ dotnet.wasm:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0-preview5.20216.1.js:1
call_method @ dotnet.3.2.0-preview5.20216.1.js:1
set_task_result @ dotnet.3.2.0-preview5.20216.1.js:1
(anonymous) @ dotnet.3.2.0-preview5.20216.1.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.3.2.0-preview5.20216.1.js:1
window.Blazor._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
_mono_wasm_invoke_js_unmarshalled @ dotnet.3.2.0-preview5.20216.1.js:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_try_invoke @ dotnet.wasm:1
mono_runtime_invoke @ dotnet.wasm:1
mono_wasm_invoke_method @ dotnet.wasm:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0-preview5.20216.1.js:1
call_method @ dotnet.3.2.0-preview5.20216.1.js:1
(anonymous) @ dotnet.3.2.0-preview5.20216.1.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
a @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
y @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1

**Comment by guardrex** [comment]
Then, I'll wait to hear what @pranavkm thinks. We documented this (as you can see) *without saying* what path is expected. I suspect if this isn't a framework thing, we can address it in the doc when I know what to tell readers. At that point, they'd transfer this to the docs repo for work. However, let's see what the cause of this is before doing anything with the doc. At this point, it could be a real 🐞.

**Comment by paul-wade** [comment]
First I was wrong. The app settings are in fact being loaded automatically. I believe last night I had them set to embeded content while trying different things. I wonder if that is why they didn't load for me.

Might be good to update the template with a default appsettings if it isn't already planned. Being a preview there is obviously a lot of conflicting information out there. 
 

> The File Configuration Provider for app settings files by default:
> wwwroot/appsettings.json
> wwwroot/appsettings.{ENVIRONMENT}.json
> Other configuration providers registered by the app.

When I read this it left just enough uncertainty if it was saying those files would be picked up automatically or if I needed to add them like I would in other project types and they were "supported" in that addjsonfile would work. 

Maybe if it said something like "The File Configuration Provider will automatically look for and load appsettings.json or appsettings.{environment}.json located in the wwwroot folder"

Then again maybe I'm the only one who wondered what by default meant.

So thanks @pranavkm and @guardrex for your help with this. It is resolved for me.

**Comment by pranavkm** [comment]
Like I mentioned earlier, Blazor does not map the wwwroot folder to disk. If you need to load a different config file, you would need to download it and read from it (https://github.com/dotnet/aspnetcore/issues/21391#issuecomment-622303810). We really don't need to be showing that as part of the config documentation.

**Comment by guardrex** [comment]
@paul-wade Open an issue from the bottom of that topic with the **This page** feedback button+form. You can paste your comment into the body ☝️. I'll improve that section on the "default" based on your feedback. It should at least say ...

> loads configuration from ...

... over ...

> supports configuration from ...

**Comment by paul-wade** [comment]
> @paul-wade Open an issue from the bottom of that topic with the **This page** feedback button+form. You can paste your comment into the body ☝️. I'll improve that section on the "default" based on your feedback. It should at least say ...
> 
> > loads configuration from ...
> 
> ... over ...
> 
> > supports configuration from ...

Yeah I like that wording and its more concise than mine. Ill add the comment. thanks
