### ISSUE TITLE
Unknown Razor components should fail to compile

### ISSUE THREAD

**Issue by Discovery-support** [dotnet/aspnetcore#21394]
As a great believer that compile time error detection is far superior to runtime error detection...

When compiling...

1.  Razor components that are unknown (e.g. missing a Nuget package or a using statement) should throw a 'doesn't exist in the current context'?

2.  Unknown Component Razor Attributes (with an upper class first letter) should also throw an 'unknown component attribute error'?

**Comment by javiercn** [comment]
@Discovery-support thanks for contacting us.

We can't distinguish between an unknown component and a custom web component tag or anything similar that you might want to put in your markup, so this is not a direction we plan to take in the near future.
