### ISSUE TITLE
Add GitHub Discussions for https://github.com/dotnet/aspnetcore

### ISSUE THREAD

**Issue by donhuvy** [dotnet/aspnetcore#21400]
I see this beta feature of GitHub called `Discussion` is helpful. Can you add this feature to this repository? like this https://github.com/zeit/next.js/discussions

**Comment by Pilchie** [comment]
From a google search, that appears to be a beta feature that this repo doesn't have access to yet.

**Comment by Pilchie** [comment]
This is done now.
