### ISSUE TITLE
Blazor Server - Publish and include exe

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#21402]
I normally run ASP.NET Core apps using a Windows service, which requires an `.exe` file. I'm using Blazor now and see that the `.exe` is not published. How do I bring back the `.exe`?

### Further technical details
- ASP.NET Core version: 3.1.3
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VSMac 8.6 4387
- Include the output of `dotnet --info`:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

Server-side blazor applications are regular ASP.NET applications. when you publish there should be an exe in the output folder and you can even produce a single-file executable.

Based on your environment it seems you are building/publishing on Mac. I believe that might be affecting the actual result. To publish for a different OS you need to specify the runtime identifier (`-r win-x64 if you are using the command-line`)

**Comment by mrlife** [comment]
@javiercn I have this line in my Blazor project file. It's the same line I use in razor pages projects to produce the `exe`. Is this still correct?

`<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>`

**Comment by javiercn** [comment]
@mrlife I believe so, if not, you can try with `RuntimeIdentifier` instead. I would be surprised if that doesn't produce an exe on `bin/<<Config>>/netcoreapp3.1/win-x64/publish` (or similar).

Another thing to check is to make sure that `UseAppHost` is set to true. Not sure if that only affects the behavior of dotnet run or also publish, but that another thing to tweak.

Are you able to reproduce this behavior on a console app or on a non blazor app?

The publish process is not something we have really control of and it is likely that the issue is in the dotnet core SDK if any.

**Comment by mrlife** [comment]
Hi @javiercn I think `UseAppHost` is the previous way of doing it before 3.0. I followed this docs page for version 3.1 (viewing it for 2.2 shows the suggestions you had). https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio#manage-the-service

It looks like `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` works, but `<RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>` does not, though it used to.

How do I report this to the correct team?

**Comment by javiercn** [comment]
@mrlife I believe you need to open an issue [here](https://github.com/dotnet/sdk). If not, they will know where to transfer it.
