### ISSUE TITLE
Blazor Cache not working correctly in RELEASE mode

### ISSUE THREAD

**Issue by abbatepabloo** [dotnet/aspnetcore#21409]
### Describe the bug
A few days a go I opened this Issue: [https://github.com/dotnet/aspnetcore/issues/20524](url). 

I'm reporting the same behaviour using **Blazor 3.2.0 Release Candidate**.

**The browser is downloading files from server that should be taken from the cache storage.**

It's important to mention that all test must be done using **RELEASE** mode (not Debug).

### To Reproduce

- Create a new Blazor Assembly App (uncheck ASP.NetCore hosted)

- Change Solution Configuration to run in RELEASE mode

- Run the application (using IIS Express) and open the Browser Developer Tools once the browser is launched. You will watch, in the Network Traffic Tab, that all assemblies are downloaded from the server for the first time.

![image](https://user-images.githubusercontent.com/33328600/80833903-fa288880-8bc5-11ea-82ea-f3e9bc92009e.png)

- Verify that Cache Storage has an entry with all assemblies cached for this site:

![image](https://user-images.githubusercontent.com/33328600/80834106-76bb6700-8bc6-11ea-96d7-e4a165840603.png)
 
- Refresh the browser content and verify that the assemblies are used from the Cached Storage instead of being downloaded:

![image](https://user-images.githubusercontent.com/33328600/80834385-fb0dea00-8bc6-11ea-958d-1cb67cae4dab.png)

- Copy the url and use it to open a new browser window. Verify once again that cache is working and no assembly is dowloaded. Keep this window opened.

- Stop the application. In the browser you keep opened refresh the page and you will see the cache is still working.

- Without making any change rebuild the application. There is no need to run it, IIS Express will refresh the site anyway.

- Refresh the browser you has opened and you will see that assemblies are downloaded from IIS Express instead of being used from the cache.

![image](https://user-images.githubusercontent.com/33328600/80835685-a61fa300-8bc9-11ea-89f3-9779dd60a76f.png)

According to my understanding, if nothing has changed, Blazor should be using the cached assemblies instead of downloading them from the server. 

As mentioned in the prior issue, I believe  the assembly's cache hash is changing during the rebuild process and is forcing Blazor to reload them without any need. 

If you have a big application (with lot of assemblies) and simply rebuild it (o make a minimal change) the browser will download ALL assemblies instead of using the from the cache, so the customer will suffer a serious delay with every update.

Maybe I'm not understanding correctly how this sould work.

### Further technical details
- ASP.NET Core 3.1

SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.300-preview-015135
 Commit:    0b3c572e97

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015135\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2019 Preview - V 16.6.0 Preview 5

**Comment by javiercn** [comment]
@abbatepabloo thanks for contacting us.

This is due to the linker producing different outputs on each build, not really something we can directly control, although we might look in the future to improve the situation.
