### ISSUE TITLE
HttpContext.SignInAsync null

### ISSUE THREAD

**Issue by hermanthotan** [dotnet/aspnetcore#21403]
Please refer to the below git link.
https://github.com/hermanthotan/cookieidentity.git

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
@hermanthotan thanks for the github project, but please describe your scenario and the issue you had.

**Comment by hermanthotan** [comment]
@Tratcher I'm trying to use the HttpContext.SignInAsync by following this [article](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1)

/home/login
In this above code behind i'm hard-coded the claims and signIn, no issue and from the network i see that the cookies it set properly.

/home/index
In this it will get the current user & display isAuthenticated & name

I have stuck in this for sometimes, may I know which part i'm missing?

**Comment by Tratcher** [comment]
If you're trying to do this without Identity, then you need to remove Identity from your Startup.
https://github.com/hermanthotan/cookieidentity/blob/cfa55c9fa047fcd048f6e172230362d20bdf8715/Startup.cs#L48-L49

AddIdentity is overwriting some of the values you specified in AddAuthentication.

**Comment by hermanthotan** [comment]
@Tratcher If I comment out the above code yes it will work.

Is there work-around to use identity together with the cookies together?

**Comment by Tratcher** [comment]
Ah, that's a different task. Can I ask why you're tying to use a separate cookie from the one already provided with Identity?

**Comment by hermanthotan** [comment]
I have a website which is MVC that already have the Identity working fine, we extract out the severals functionality to API such as Identity to response with a token.
Since we have API Identity, It just makes sense to refactor the /Account/Login to call the API and Authenticate It. otherwise, we will have logic in Web and API.

**Comment by Tratcher** [comment]
The main problem with having two auth providers (Identity and Cookie) is that it becomes hard to use defaults. `AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)` sets cookies as your default, but then AddIdentity replaces that. You could reorder them if you really want cookies as the default. Even then, you'd need to specify the Identity auth schemes explicitly anywhere you wanted to use those.

**Comment by hermanthotan** [comment]
@Tratcher Thanks can Close this, will using the Identity as of now.
