### ISSUE TITLE
[blazor] dotnet.timezones.dat weights 0.5mb compressed

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#21414]
After Blazor WebAssembly 3.2.0 Preview 5 which added support for time zones I see in wwwroot\_framework\wasm folder new file dotnet.timezones.dat 459kb brotli compressed.

Blazor wasm was heavy enough without this and this added extra 0.5mb.

It seams too heavy for what it is doing, is this size normal or there can be bug?

What if I remove this file? I had correct local date time using simple js solution.

I am happy having time zone support without js, but for this heavy file addition price, not sure.

@SteveSandersonMS @danroth27

**Comment by pranavkm** [comment]
@Lupusa87 are you certain you aren't looking at the uncompressed size:

```
-a----         4/23/2020 12:23 AM         469533 dotnet.timezones.dat
-a----          5/1/2020  5:11 PM          63760 dotnet.timezones.dat.br
-a----          5/1/2020  5:11 PM         110398 dotnet.timezones.dat.gz
```

You can prevent the file from being published by setting `<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>` in your project file. You lose support timezone support in .NET, but the app should continue to work fine.

**Comment by Lupusa87** [comment]
@pranavkm Thank you so much.
 
 My mistake, you helped me to realize what happen.

 I am using my own small azure deploy utility to compress and upload files, it was missing .dat extension and left dotnet.timezones.dat uncompressed.

Now I see 62.3kb which is fully acceptable :)

Still good to know we have option to turn it off safely.
