### ISSUE TITLE
Test failure: Microsoft.Extensions.SecretManager.Tools.Tests.SecretManagerTests.SetSecrets

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#21413]
https://dev.azure.com/dnceng/internal/_build/results?buildId=626845&view=ms.vss-test-web.build-test-results-tab&runId=19576184&resultId=108990&paneView=debug

<details>
<summary>Error</summary>

```
Assert.Contains() Failure

Not found: No secrets configured for this application.

In value: Project file path /tmp/usersecretstest/5895c797-3631-4f05-91b9-2f2cd1566b31/TestProject.csproj.

Secrets file path /home/helixbot/.microsoft/usersecrets/53478d69-97a8-440a-8ce2-a8b0ebef4b74/secrets.json.

key1 = 1ec036ea-1f7d-42cb-9269-6265679a1afb
```

</details>

<details>
<summary>Stacktrace</summary>

```
at Microsoft.Extensions.SecretManager.Tools.Tests.SecretManagerTests.SetSecrets(Boolean fromCurrentDirectory) in /_/src/Tools/dotnet-user-secrets/test/SecretManagerTests.cs:line 87
```

</details>

**Comment by BrennanConroy** [comment]
I believe this is the same failure as https://github.com/dotnet/aspnetcore/issues/20219 which is being worked on/investigated by the runtime team

**Comment by BrennanConroy** [comment]
Test was skipped for non-flaky reasons and just unskipped. Letting it go to non-quarantined runs and we'll see if it's still flaky.
