### ISSUE TITLE
Authorization failed log entry when running default ASP.NET Core hosted Blazor WebAssembly app with auth enabled

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#21415]
Repro steps:

- Create an ASP.NET Core hosted Blazor WebAssembly app with auth enabled.
- Hit Ctrl-F5 to run the app
- Open the dev tools and look at the console output

Expected result: 

- Console is clean

Actual result:

Authorization failed log entry:

![image](https://user-images.githubusercontent.com/1874516/80849537-61e1d200-8bcc-11ea-979e-dd00c5e0b9be.png)

**Comment by mihaimyh** [comment]
This means that the user is not authenticated? Why does it checks for an authenticated user if the page doesn't have an `Authorize` attribute?

**Comment by danroth27** [comment]
@mihaimyh I think it might be because it needs to update the login display to show whether the user is logged in or not.

**Comment by mkArtakMSFT** [comment]
This message is being printed by the AuthorizeService and we have no control over the message. We can control the log level to not print this at all.

**Comment by mkArtakMSFT** [comment]
We will be handling this as part of https://github.com/dotnet/aspnetcore/issues/21472
