### ISSUE TITLE
DefaultSigningCredentialStore does not exist

### ISSUE THREAD

**Issue by tonibabieka** [dotnet/aspnetcore#21427]
AdSigningCredential public static method creates an ISigningCredentialStore singleton service returning a new DefaultSigningCredentialsStore instance of an non existing class. I gets an error. I discovered the issue testing some new blazor webassembly projects.
Thanks.

**Comment by tonibabieka** [comment]
It is at Identity level. The IdentityServerConfigurationExtensions AddSigningCredentials public static method creates a new DefaultSigningCredentialsStore an a new DefaultValidationKeysStore, and there is no class to do so.

**Comment by javiercn** [comment]
I believe you have updated your Identity Server to a version that is not compatible with the support we ship.

Closing this issue as you are mixing incompatible dependencies
