### ISSUE TITLE
WASM event callback binds blocks browser (Chrome) to re-render (CRP)

### ISSUE THREAD

**Issue by majda107** [dotnet/aspnetcore#21426]
#19203 # The issue

Okay, so I've started developing this svg rendering "engine" in blazor and found kinda strange behavior. I am rendering SVG's and moving them around with css `translate3d` transform, called via JS Interop (literally the only thing that my engine uses from javascript, otherwise it's all C# - wasm).

First of all, I've found out that every event callback invokes blazor re-render and it fires AfterRenderAsync and stuff, that makes sense because you want to render new data on some event change, however I am using events like `onmousemove` / `ontouchmove` that only change position which is being invoked via javascript, so I've disabled `ShouldRender` and enabling it by myself on data change.

So right now i basically hook  `onmousemove` / `ontouchmove` in blazor, and without re-rendering the component I call JSInterop on **clientside** to move the elements around, worked almost perfect with mouse so far, but when I've added `ontouchmove` (that probably fires **more frequently**?) things started to mess up.

![image](https://user-images.githubusercontent.com/19244007/80868629-3a5a3a80-8c9c-11ea-91cc-fc1301a2a409.png)

As you can see on this log taken during touch movement, I buffer CSS changes via JSInterop -> requestAnimationFrame and the browser (Chrome) does CRP after I slow my movement down (event is called less frequently) or I completely stop. 

(btw don't mind the **Re-rendering canvas** thing, i log this on mouseup / touchend and it has nothing to do with browser CRP rendering, tried this, don't worry)

![image](https://user-images.githubusercontent.com/19244007/80868688-860ce400-8c9c-11ea-8793-444237fa900b.png)

Here you can even see screenshot, where I back enabled `ShouldRender` making the component re-render each mouse/touch move and buffer CSS change `AfterRenderAsync`

You can check the live demo here: http://blaze.majdatrpkos.cz/, **however there is no console logging enabled**, works perfectly with mouse move on desktop, the bug occurs only if you have touch-enabled laptop (like I do) or smartphone. 

You can check the DOM and see that CSS values on canvas aren't changing that frequently as move occurs when you drag the canvas itself.

src: https://github.com/majda107/blaze-cards

Knowing this approach has no issues in pure js, I feel like there is something in WASM <-> JS binds **that prevent the browser from CRP re-render** and fire the event instead, since this loop finishes browser fires another event and this whole thing continues.

Also, this only happens in desktop version Chrome and many android browser, it seems to work perfectly fine in **desktop Firefox and desktop touch** support (I use touch-enabled laptop).

I am not sure if this is **bug or feature**, but is there any way to **fix this**? I think that my 'app' has an potential to be WASM built working css svg renderer, but this issue totally buries the idea.

### To Reproduce
- Hook `ontouchmove` on blazor component with either `ShouldRender` enabled or disabled
- Call JSInterop callback that changes `CSS` property and should be `css trigger`
- Try to use requestAnimationFrame?
- Use Google Chrome on desktop?

### Details
- Blazor clientside (WASM) 3.2.0-preview3.20168.3
- Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by majda107** [comment]
Playing around, trying to create better log to understand what's going on, take look at this...

this is example during `touchmove` event in desktop google chrome, see note that first `Frame delta` occurs after long time, browser CRP is like frozen until event callbacks calm down

![image](https://user-images.githubusercontent.com/19244007/80871102-033f5580-8cab-11ea-9852-22cc7c582c24.png)

Way of logging...

![image](https://user-images.githubusercontent.com/19244007/80871138-3c77c580-8cab-11ea-988f-9bd75b1c468c.png)


See working demo (I added logs) at: https://blaze.majdatrpkos.cz/
or repo with code at: https://github.com/majda107/blaze-cards

**Comment by majda107** [comment]
https://github.com/majda107/blaze-touch-issue

I made small example app that describes this issue, made me feeling more confident in my theory...

Entire code is in `Pages/Index.razor` and `move.js`

**Comment by majda107** [comment]
> https://github.com/majda107/blaze-touch-issue
> 
> I made small example app that describes this issue, made me feeling more confident in my theory...
> 
> Entire code is in `Pages/Index.razor` and `move.js`

Btw added working example JS app that does what I want / expect 

and also tried removing JSInterop completely and just using X/Y property of SVG element and blazor rendertree, same issue...

**Comment by mkArtakMSFT** [comment]
Thanks for detailed issue report, @majda107.
We have multiple SVG support related issues which we plan to handle all together during 5.0 timeframe. For now, parking this issue in the `next-sprint-planning` milestone to handle it together with the rest when we get to them.

**Comment by majda107** [comment]
> Thanks for detailed issue report, @majda107.
> We have multiple SVG support related issues which we plan to handle all together during 5.0 timeframe. For now, parking this issue in the `next-sprint-planning` milestone to handle it together with the rest when we get to them.

Okay so correct me now, I've removed everything that relates to SVG and even JS Interop and the issue still persists...

I mean, this is thing that should blazor and wasm handle without any issues and it may even be on a list of features but it's clearly broken.

 Broken code: 
```
@page "/"
@inject IJSRuntime IJSRuntime;

<h1>Hello, world!</h1>

<div class="canvas"
     @onmousedown="((e) => this.MouseDown((float)e.ClientX, (float)e.ClientY))"
     @onmousemove="((e) => this.MouseMove((float)e.ClientX, (float)e.ClientY))"
     @onmouseup="((e) => this.MouseUp((float)e.ClientX, (float)e.ClientY))"
     @ontouchstart="((e) => this.MouseDown((float)e.Touches[0].ClientX, (float)e.Touches[0].ClientY))"
     @ontouchmove="((e) => this.MouseMove((float)e.Touches[0].ClientX, (float)e.Touches[0].ClientY))"
     @ontouchend="((e) => this.MouseUp(0, 0))"
     @ontouchstart:stopPropagation="true"
     @ontouchmove:stopPropagation="true">

    @*<rect @ref="rectRef" x="@this.ToCoordString(this.movx)" y="@this.ToCoordString(this.movy)" width="40px" height="40px"></rect>*@

    @*<div @ref="rectRef" width="40px" height="40px"></div>*@

    <div @ref="rectRef" class="rect-div" style="@this.GetCssOffset()"></div>
</div>

@code {
    private float lastx;
    private float lasty;

    private float movx;
    private float movy;

    private bool mouseDown;

    private ElementReference rectRef;

    private string GetCssOffset()
    {
        return $"left: {this.movx.ToString("0")}px; top: {this.movy.ToString("0")}px;";
    }

    private string ToCoordString(float val)
    {
        return $"{val.ToString("0")}px";
    }

    private void MouseDown(float x, float y)
    {
        this.mouseDown = true;

        this.lastx = x;
        this.lasty = y;
    }

    private void MouseUp(float x, float y)
    {
        this.mouseDown = false;

        this.lastx = x;
        this.lasty = y;
    }

    private void MouseMove(float x, float y)
    {
        if (!this.mouseDown) return;

        var devx = x - this.lastx;
        var devy = y - this.lasty;

        movx += devx;
        movy += devy;

        this.lastx = x;
        this.lasty = y;
    }
}
```

https://github.com/majda107/blaze-touch-issue you can examine the entire repo here.

Same issue persists, no SVGs, no JS interop, pure wasm issue. I've rewritten entire scenario to **JS + Rust wasm and it works flawlessly**, so this is definitelly not wasm + chrome issue (can provide the code if interested)

Just as I said and thought, this has to be blazor <-> wasm binding issue and it's definitelly much bigger thing than 'svg bug that is planned to fix next sprint', it affects entire rendering tree -> DOM.



Just plug that code in component and see it running on some touch-enabled device...

**Comment by rogihee** [comment]
I made a prototype app with a canvas that does a lot of draw operations on a canvas in a tight loop (25-100ms), and I experienced the same performance degradation. I have not dug deeper as I suspected the issue came from using a Threading.Timer in C# and not something like a WebWorker or like you animationFrame.

There might be a real issue in heavy Blazor/Javascript interop, Vakhtangi Abashidze created JS fast data exchanger. I have not compared your repro with his solution, but perhaps you can investigate if this might help?
[https://github.com/Lupusa87/BlazorJsFastDataExchanger](https://github.com/Lupusa87/BlazorJsFastDataExchanger)

**Comment by majda107** [comment]
Will try, sounds interesting, thanks a lot. 

I've figured out to work around touch issue, but speed degradation persists smh.

**Comment by majda107** [comment]
> I made a prototype app that does a lot of draw operations on a canvas in a tight loop (25-100ms), and I experienced the same performance degradation. I have not dug deeper as I suspected the issue came from using a Threading.Timer in C# and not something like a WebWorker or like you animationFrame.
> 
> There might be a real issue in heavy Blazor/Javascript interop, Vakhtangi Abashidze created JS fast data exchanger. I have not compared your repro with his solution, but perhaps you can investigate if this might help?
> https://github.com/Lupusa87/BlazorJsFastDataExchanger

By the way, checking the repo, it claims JSInterop is slow, but that's not my issue. My issue is that blazor binds somehow block browser from invalidating, check this... https://github.com/dotnet/aspnetcore/issues/21444

But it's definitelly interesting and worth taking a look, thanks a ton!

**Comment by majda107** [comment]
> I made a prototype app that does a lot of draw operations on a canvas in a tight loop (25-100ms), and I experienced the same performance degradation. I have not dug deeper as I suspected the issue came from using a Threading.Timer in C# and not something like a WebWorker or like you animationFrame.
> 
> There might be a real issue in heavy Blazor/Javascript interop, Vakhtangi Abashidze created JS fast data exchanger. I have not compared your repro with his solution, but perhaps you can investigate if this might help?
> https://github.com/Lupusa87/BlazorJsFastDataExchanger

Once more, thanks a ton.

I've downloaded .NET 5 and linked .NET 5 preview Mono-wasm nugget, using `MonoWebAssemblyJSRuntime` in .NET 5 razor library and it seems to be **almost as** performant as rust/c++ version.

It's definitelly faster, than JSInterop bindinds, probably due to marshalling.

You can check demo here: https://blaze.majdatrpkos.cz/ (use **CTRL+SHIFT+R** to reload service worker), you can drag canvas, elements and multi-select with SHIFT

It's not cleanest solution, but seems to work so far, makes me wondering, could guys in microsoft somehow encapsulate `InvokeUnmarshalled` function? If it makes any sense, I can fork blazor and add it as a feature, submitting merge request.

**Comment by rogihee** [comment]
Looks cool and you should really thank Vakhtangi!

**Comment by captainsafia** [comment]
> It's not cleanest solution, but seems to work so far, makes me wondering, could guys in microsoft somehow encapsulate InvokeUnmarshalled function? 

I'm not sure what you mean by "encapsulate" here but `InvokeUnmarshalled` is part of the [public API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.webassembly.webassemblyjsruntime.invokeunmarshalled?view=aspnetcore-3.1) and is recommended for scenarios, such as yours, where performant JS Interop is required.

It seems like you've done quite a bit of iteration since the original issue was opened. Can you help clarify what the bug/feature ask is?
