### ISSUE TITLE
Re: Figure out WebAssemblyHttpMessageHandlerOptions

### ISSUE THREAD

**Issue by LukeTOBrien** [dotnet/aspnetcore#21435]
Hi chaps,

I see that in https://github.com/dotnet/aspnetcore/issues/19202 you removed the `WebAssemblyHttpMessageHandlerOptions` class in faviour of per request setting.  
[Configure HTTP fetch request options](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available/).

I have two projects, my SPA project and my WebAPI, both at differnent origions, I do my authenticanion on my WebAPI-side so I need *every* request to send cookies.  
Now that you have removed the global setting `WebAssemblyHttpMessageHandlerOptions` it's going to be a pain for me to set every request.

I do my requests like this:
```csharp
await Http.PostAsync($"{Global.Api}{ApiRoutes.IdentitySignIn}", HttpHelper.Put(SignInRequest));
```  
(`HttpHelper` is my own class)  
But will the `Post` and `Get` methods go now too? Will I have to use `Send` everywhere instead?

I think having a global `WebAssemblyHttpMessageHandlerOptions` was a good thing so I would say bring it back.

Luke

**Comment by javiercn** [comment]
@LukeTOBrien thanks for contacting us.

I would suggest you write a DelegatingMessageHandler and attach it to your HttpClient with the options you want/need for each of the origins so that you can attach the options in a single place?

We don't plan to bring back the global options.

**Comment by LukeTOBrien** [comment]
hmm, okay I will try that out, thanks!

**Comment by LukeTOBrien** [comment]
I just received:
>       Unhandled exception rendering component: Property UseCookies is not
supported.
> System.PlatformNotSupportedException: Property UseCookies is not
supported.
With the following code:
```csharp
            services.AddTransient(sp => new HttpClient(new
HttpClientHandler()
            {
                UseCookies = true
            });
```

What exact property does the `SetBrowserRequestCredentials` method set?
I have a `netstandard` shared 'Frameword' project and I would ideally like
put my logic there.
Is there any way I can set the request.credentials without referencing `
Microsoft.AspNetCore.Components.WebAssembly.dl`?

**Comment by LukeTOBrien** [comment]
I just received:
>       Unhandled exception rendering component: Property UseCookies is not supported.
> System.PlatformNotSupportedException: Property UseCookies is not supported.
With the following code:

```csharp
 services.AddTransient(sp => new HttpClient(new HttpClientHandler()
 {
    UseCookies = true
});
```

What exact property does the `SetBrowserRequestCredentials` method set?
I have a `netstandard` shared 'Frameword' project and I would ideally like
put my logic there.
Is there any way I can set the request.credentials without referencing `Microsoft.AspNetCore.Components.WebAssembly.dl`?

**Comment by javiercn** [comment]
@LukeTOBrien it sets some keys in the request properties dictionary, can't remember exactly what. I believe you can target netstandard referencing Microsoft.AspNetCore.Components.WebAssembly (since it's netstandard2.1).

You can decompile the dll and look at the extension methods if you really want to do this "yourself" but keep in mind that if you choose that path, it might not work in future versions if the implementation changes.

In my opinion, the easiest choices are to either reference `Microsoft.AspNetCore.Components.WebAssembly ` from within the package or create the handler in your app and pass it down to your library code.

**Comment by LukeTOBrien** [comment]
Okay, I will ref the dll as we as a netstandard world.  
The [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.http.webassemblyhttprequestmessageextensions.setbrowserrequestcredentials) says: ASP.NET Core 3.1 - So I wasn't sure
