### ISSUE TITLE
"Build ASP.NET Core from Source" doc page doesn't list cURL/Wget dependency for macOS/Linux

### ISSUE THREAD

**Issue by MaxHorstmann** [dotnet/aspnetcore#21430]
### Describe the bug
Minor documentation bug: on the [Build ASP.NET Core from Source](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md) documentation page, the [Install pre-requisites - macOS/Linux](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md#macoslinux) section doesn't list "cURL or Wget" as a requirement. Many Linux distros, such as Ubuntu, [don't](https://askubuntu.com/questions/756836/why-is-curl-not-installed-by-default) [include](https://askubuntu.com/questions/883669/how-to-install-wget-on-ubuntu-14-04) either by default.

### To Reproduce
The dependency on either cURL or Wget can be reproduced e.g. by trying to [build from source in a Ubuntu Docker container](https://github.com/MaxHorstmann/aspnetcore-docker-build): running these commands...

```
$ docker run -it ubuntu
$ apt-get update
$ apt-get -y install git nodejs default-jdk liblttng-ust0 libcurl4 libssl1.0.0 libkrb5-3 zlib1g libicu60 libgdiplus
$ git clone --recursive https://github.com/dotnet/aspnetcore
$ cd aspnetcore
$ ./build.sh
```

... produces this output:

```
...
Downloading 'https://dot.net/v1/dotnet-install.sh'
Trying to run 'wget -v -O /aspnetcore/.dotnet/dotnet-install.sh https://dot.net/v1/dotnet-install.sh' for maximum of 5 attempts.
/aspnetcore/eng/common/tools.sh: line 233: wget: command not found
Failed to execute 'wget -v -O /aspnetcore/.dotnet/dotnet-install.sh https://dot.net/v1/dotnet-install.sh'. Waiting 3 seconds before next attempt (2 out of 5).
/aspnetcore/eng/common/tools.sh: line 233: wget: command not found
Failed to execute 'wget -v -O /aspnetcore/.dotnet/dotnet-install.sh https://dot.net/v1/dotnet-install.sh'. Waiting 7 seconds before next attempt
```

Installing either cURL or wget (e.g. by adding it to the `apt-get -y install...` comment) fixes the issue.

### Further technical details
n/a - documentation only

**Comment by dougbu** [comment]
a39d9f20567d
