### ISSUE TITLE
Blazor .ConfigureAwait(true) DbContext "second operation started"

### ISSUE THREAD

**Issue by kodiex** [dotnet/aspnetcore#21434]
I suspect that asyc await behaves in Blazor different than excpected.

.ConfigureAwait(true) should be the default behaviour, I have evidence that calling an async method with .ConfigureAwait(true) behaves differently than call the method without it.

Without I have DbContext errors "second operation started" that disappear with .ConfigureAwait(true) on async methods.

I should be able to provide an example sln to repro the issue

**Comment by Boglen** [comment]
You should use @inherits OwningComponentBase<TService> to avoid "second operation started" error.

**Comment by mkArtakMSFT** [comment]
@JeremyLikness do you have guidance provided on how to handle this? Can you link it here?

**Comment by JeremyLikness** [comment]
Hi @mkArtakMSFT right now we are working on evolving the guidance. Existing document is here:

https://docs.microsoft.com/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di

We are tracking the updates in our docs repo:  [dotnet/EntityFrameworkDocs Issue 2025](https://github.com/dotnet/EntityFramework.Docs/issues/2025)

In essence, guidance is:

Most of the time you should create one `DbContext` per operation. For now you can inject `DbContextOptions` then use the `new` operrator to create a `DbContext` with a `using` statement. We will consider adding a factory for this in the future. 

For scenarios that require a longer-lived `DbContext`, such as edit forms that use change tracking, you should bring the `DbContext` in using `OwningComponentBase` and use a flag to prevent concurrent calls. 

We are working on both a sample project and documentation for this.
