### ISSUE TITLE
Blazor: Dynamic <Select> not setting selected value

### ISSUE THREAD

**Issue by schotime** [dotnet/aspnetcore#21432]
The following complete example demonstrates an issue when setting a selected value on a `<select>`.

Steps to reproduce: (Chrome and Firefox at least both have it)
1. Install Blazor RC WebAssembly
2. Create a new project using the --hosted template
3. Create a new razor file called example.razor and paste the example below in
4. Goto /example
5. Click on the First select list and choose 'Two', everything seems to work
6. Click on the First select list and choose 'Three'. The second list has not selected 'b' even though it is the value of the selected Tag and the select list has the option in it.

```cs
@page "/example"

<h1>Example</h1>

<div>
    Selected Item: @ItemId
</div>
<div>
    Selected Tag: @Tag
</div>

<select value="@ItemId" @onchange="SelectItem">
    @foreach (var item in Items)
    {
        <option value="@item.Id">@item.Name</option>
    }
</select>

<select @bind="Tag">
    @foreach (var tag in Items.Single(x => x.Id == ItemId).Tags)
    {
        <option>@tag</option>
    }
</select>

@code {

    public Item[] Items = new Item[]
    {
        new Item { Id = 1, Name = "One", Tags = new[] { "a", "b", "c" }},
        new Item { Id = 2, Name = "Two", Tags = new[] { "a", "c", "d" }},
        new Item { Id = 3, Name = "Three", Tags = new[] { "b", "c", "f" }},
    };

    public int ItemId { get; set; } = 1;

    public string Tag { get; set; }

    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string[] Tags { get; set; }
    }

    public void SelectItem(ChangeEventArgs e)
    {
        ItemId = Convert.ToInt32(e.Value);
        Tag = Items.Single(x => x.Id == ItemId).Tags.First();
    }
}
```

**Comment by schotime** [comment]
Is there a work around? cause I can't go to production with out this working.

**Comment by SteveSandersonMS** [comment]
It looks like a bug in the code above, if I'm understanding correctly. Your `<option>` elements for the "tags" don't have any `value` attribute, so they aren't matched.

The fix would be to change your "tags" options to render like this:

```razor
<option value="@tag">@tag</option>
```

I just tried this and it appears to work fine.

**Comment by schotime** [comment]
I just tried that and it does indeed fix my problem, so that's a good work around, however I think its still a bug. If there is no value shouldn't the text be used as the value?

In the HTML standard:

> The value attribute provides a value for element. The value of an option element is the value of the value content attribute, if there is one, or, if there is not, the value of the element's text IDL attribute.
> https://html.spec.whatwg.org/multipage/forms.html#the-option-element

or on the W3C Wiki

> Provides a value for element. If there isn't, the value of an option element is the textContent of the element.
> https://www.w3.org/wiki/HTML/Elements/option

Thoughts?

**Comment by SteveSandersonMS** [comment]
@schotime As a general rule we don't always try to be as loose as HTML permits. For example, Blazor doesn't allow mismatching tags, which HTML specs do try to make work via various recovery strategies.

In this specific case if there are sufficiently performant ways to allow that particular kind of looseness we'd certainly consider them. If you're interested in submitting a PR please have a look.

**Comment by schotime** [comment]
@SteveSandersonMS I appreciate the response. Obviously now that I know, its fine, and it only shows its head when you are doing dynamic stuff it seems. 

I'd be interested in having a look at a PR etc at some point. Any hints on where I should look, that would be great. Cheers.

**Comment by schotime** [comment]
Also a little bit confusing give the Value in the change event does grab the text

```cs
<select class="form-control" @onchange="(e) => IsBoolParam = bool.Parse(e.Value.ToString())">
    <option selected="@(!IsBoolParam)">False</option>
    <option selected="@(IsBoolParam)">True</option>
</select>
```
