### ISSUE TITLE
Add stopPropagation to all events rather than just one

### ISSUE THREAD

**Issue by simonziegler** [dotnet/aspnetcore#21438]
I have scenarios where I would like to stop propagation on all events from a `<div>` rather than just one. So instead of:
```
<div @onclick:stopPropagation="true" @onkeypress:stopPropagation="true" [... etc ...]>
    <p>Some content</p>
</div>
```
we would be able to have something with this kind of pattern (but I'm not suggesting syntax here):
```
<div @stopAllPropagation="true">
    <p>Some content</p>
</div>
```

**Comment by javiercn** [comment]
@simonziegler thanks for contacting us.

Can you tell us more about what scenarios do you find it useful on? This would help us prioritize the feature with respect to other features.

**Comment by simonziegler** [comment]
@javiercn thanks for the response and apologies for the delay. I’m working in a material theme component library github.com/BlazorMdc, and would like to find some way to expose all events from some elements on a component but to ignore those from elements that are declarative rather than interactive.

**Comment by danroth27** [comment]
@simonziegler Just checking to see if this is still functionality you are interested in? Or did you find an alternative solution?

**Comment by TanayParikh** [comment]
> @simonziegler Just checking to see if this is still functionality you are interested in? Or did you find an alternative solution?

/ping @simonziegler
