### ISSUE TITLE
Diagnostic tracing not logging to storage account.

### ISSUE THREAD

**Issue by jaymarf** [dotnet/aspnetcore#21447]
### Describe the bug
We are experiencing a issue logging to our storage account using the application logging feature for azure app services. The application does not log any of the diagnostic trace messages nor does it log the start and stopping of the website via iis logs in a none public cloud environment. 

### To Reproduce
Setup and deploy netcore application to app service, and enable diagnostic logging.

**Comment by BrennanConroy** [comment]
Are you still having issues?

Can you share the settings you changed in the app service?
