### ISSUE TITLE
ApiController Simple Type Not Converting FromBody vs FromForm

### ISSUE THREAD

**Issue by clockwiseq** [dotnet/aspnetcore#21449]
### Describe the bug
While creating an action on an `ApiController`, decorating the object being passed in (simple type, DateTime as an example) as `[FromBody]` requires special treatment by jQuery POST method.  If you attempt a simple POST method with a string value of the date _(i.e. 2020-03-14)_, the POST results in a 415 response.  Because I have not tested this in quite some time, I am not sure which release changed this behavior, nor am I 100% confident on whether or not it is jQuery or .NET Core that is causing the issue, but decorating the object parameter in the action as `[FromForm]` resolves the issue and the object is converted properly.  Granted, for my use case, there is an object model being passed in,

### [FromBody] Example (Does Not Work)
Action on the ApiController:
``` C#
[HttpPost]
public async Task<int> Post([FromBody] DateTime eventDate)
{
    // never makes it here as the server returns a 415 error code
    return 3;
}
```
javascript in the view:
``` javascript
function CreateEvent() {
    $.post(apiUri, '2020-03-14', function(response) {
        // never makes it here as the server throws a 415 error
        // also tried new Date('2020-03-14') among other date formats, and JSON.stringify
    });
}
```

### [FromForm] Example (Works)
Action on the ApiController:
``` C#
[HttpPost]
public async Task<int> Post([FromForm] DateTime eventDate)
{
    // this is a success
    return 3;
}
```
javascript in the view:
``` javascript
function CreateEvent() {
    $.post(apiUri, '2020-03-14', function(response) {
        // this works and the response is 3
        // my preferred format in date is MM/DD/YYYY and it works as well with the [FromForm] 
        // decorator
    });
}
```

### Further technical details
- ASP.NET Core 3.1
- MVC sample application from basic template in VS2019
- Include the output of `dotnet --info`
  .NET Core SDK (reflecting any global.json):
   Version:   3.1.201
   Commit:    b1768b4ae7

  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.18363
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

  Host (useful for support):
    Version: 3.1.3
    Commit:  4a9f85e9f8

  .NET Core SDKs installed:
    3.0.103 [C:\Program Files\dotnet\sdk]
    3.1.201 [C:\Program Files\dotnet\sdk]

  .NET Core runtimes installed:
    Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.0.3 [C:\Program 
 Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  Visual Studio Professional 2019 Version 16.5.4

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
