### ISSUE TITLE
`Microsoft.AspNetCore.SignalR.Client` and `Microsoft.AspNetCore.SignalR.Client.Core`, which one to use?

### ISSUE THREAD

**Issue by abhiphirke** [dotnet/aspnetcore#21451]
This is really a query rather than an issue.

With respect to `....SignalR.Client` and `....SignalR.Client.Core`: Both Nugets kind of confused me. I have not been able to locate any documentation which explains me the relation between the two and which one should I really use. I added `....SignalR.Client`, and it also included `....SignalR.Client.Core` as well.

Could you quickly explain or point me to relevant page/article. Thanks in advance for help!

**Comment by anurse** [comment]
Microsoft.AspNetCore.SignalR.Client is what you want. You’ll notice it depends upon the “.Core” package. The “.Core” package is the core protocol implementation with no HTTP support.

The [docs on the .NET client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio) specify the package to use.
