### ISSUE TITLE
WebSocket connections slow down after the first 15 connections 

### ISSUE THREAD

**Issue by kdavis** [dotnet/aspnetcore#21454]
### Describe the bug

After 15 instantly connecting websocket connections, ASP NET Core only accepts 1 new connection per second.

### To Reproduce

Basic ASP NET Core 3.1 webserver with this configuration:
```csharp
		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}

			app.UseWebSockets();
			app.UseMiddleware<WebSocketMiddleware>();

			app.UseStaticFiles();
		}
```

The websocket middleware (waiting for a message and closing socket):

```csharp
public class WebSocketMiddleware : IMiddleware
{
    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        if (!context.WebSockets.IsWebSocketRequest)
        {
            await next.Invoke(context);
            return;
        }

        WebSocket currentSocket = await context.WebSockets.AcceptWebSocketAsync();

        await ReceiveStringAsync(currentSocket, context.RequestAborted);

        currentSocket.Dispose();
    }

    private async Task<string> ReceiveStringAsync(WebSocket socket, CancellationToken ct = default(CancellationToken))
		{
			var buffer = new ArraySegment<byte>(new byte[8192]);
			using (var ms = new MemoryStream())
			{
				WebSocketReceiveResult result;
				do
				{
					ct.ThrowIfCancellationRequested();

					result = await socket.ReceiveAsync(buffer, ct);
					ms.Write(buffer.Array, buffer.Offset, result.Count);
				}
				while (!result.EndOfMessage);

				ms.Seek(0, SeekOrigin.Begin);
				if (result.MessageType != WebSocketMessageType.Text)
				{
					return null;
				}

				// Encoding UTF8: https://tools.ietf.org/html/rfc6455#section-5.6
				using (var reader = new StreamReader(ms, Encoding.UTF8))
				{
					return await reader.ReadToEndAsync();
				}
			}
		}
}
```

### Further technical details
- ASP.NET Core version 3.1
- VS Code 1.44.2
- Running via `dotnet run WebSocket.Server`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200     
 Commit:    c5123d973b  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18363
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
To confirm, you're using Kestrel?

What's the client look like?

**Comment by Tratcher** [comment]
Also, how big are the messages you're receiving? And/or how long do they take on average? ~1s?

**Comment by kdavis** [comment]
Hi Chris, 

Yes I'm using Kestrel and I'm sending messages about 20 characters in length. They're actually instantaneous.

**Comment by kdavis** [comment]
https://github.com/kdavis/websocket-limit

This project replicates the issue I'm seeing. Navigate to `http://localhost:5000/index.html` and connect 20 times. You'll start seeing 1 second delays while connecting...

**Comment by samsosa** [comment]
At first glance it sounds like a connection rate limit from the client browser to prevent DoS attacks.

Have you ever tried this with a second computer or a second browser (Firefox and Chrome, or Chrome and Chrome Incognito) simultaneously? Do you see this delay there as well?

**Comment by kdavis** [comment]
I tested it with JMeter, multiple browsers, multiple machines, multiple people from other places in the world to connect. Still getting the same issue.

**Comment by davidfowl** [comment]
There's no built in limit for concurrent connections. I'd suggest looking at counters https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters and maybe attaching a profiler.

The code you wrote isn't efficient but it shouldn't really matter for 15 connections. The other interesting thing is that you're reading a single stream then closing the connection, that's not a typical use of websockets. Is that intentional?

**Comment by kdavis** [comment]
It was a really basic example

**Comment by anurse** [comment]
We've definitely done performance tests with many more than 15 concurrent connections and not seen this issue. Can you share a runnable sample that reproduces the problem? It's possible there's something different about your code and seeing the full context would really help us understand that.

**Comment by davidfowl** [comment]
From that code sample, it’s like testing http1.0, client connects, sends a single websocket frame and then the server disconnects. As @anurse said, we’ve tested more than 15 connections (lots of live sites and services are using websockets, including stackoverflow). Can you share the end to end so we can help you diagnose the application?

**Comment by samsosa** [comment]
I probably found the problem. Synchronous code!

Your `PushMessages()` method blocks synchronously with `GetConsumingEnumerable()` and takes threads from the ThreadPool. New threads are created every few seconds, but this takes a second and this is the delay you see.


```csharp
public async void PushMessages()
{
	try
	{
		foreach (var message in _messages.GetConsumingEnumerable())
		{
			try
			{
				await SendStringAsync(message);
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
			}
		}
	}
	catch (Exception e)
	{
		Console.WriteLine(e);
	}
}
```

**Comment by samsosa** [comment]
You can try if it works better with the following function for `PostMessages()` ... even though it is not very nice either, but at least it should not block.

```csharp
public async void PushMessages()
{
	try
	{
		while (!_messages.IsCompleted)
		{
			while (_messages.TryTake(out var message))
			{
				try
				{
					await SendStringAsync(message);
				}
				catch (Exception e)
				{
					Console.WriteLine(e);
				}
			}

			// Returning the thread!
			await Task.Delay(10);
		}
	}
	catch (Exception e)
	{
		Console.WriteLine(e);
	}
}
```

**Comment by davidfowl** [comment]
Oh yeah, blocking code will have really negative effects on scaling. Also async void is something you should avoid on the server side (see more here https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md).

Replace your BlockingCollection\<string\> with Channel\<string\> (https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/)
