### ISSUE TITLE
Frequent rerendering fills up the GC Nursery

### ISSUE THREAD

**Issue by b-straub** [dotnet/aspnetcore#21452]
### Describe the bug
When a Webassembly page renders with high frequency the GC nursery section fills up rapidly and starts writing warnings to the console.

### To Reproduce

Add the ticker test page
[Ticker](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/ComponentsApp.App/Pages/Ticker.razor)

Change the update speed to a high frequency
`await Task.Delay(TimeSpan.FromMilliseconds(2));`

The Debug console will start emitting GC warnings
`L: GC_MINOR: (Nursery full) time 2.35ms, stw 2.37ms promoted 162K major size: 992K in use: 269K los size: 1024K in use: 16K`
….

### Further technical details
- ASP.NET Core version
Microsoft.AspNetCore.Components.WebAssembly 3.2.0-rc1.20223.4`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 Preview Version 16.6.0 Preview 5.0

**Comment by javiercn** [comment]
@b-straub thanks for contacting us.

I would expect something like this to be the case if you are rendering at 2ms. What is your expectation here?

**Comment by b-straub** [comment]
@javiercn My expectation is to clarify if it's OK that each render cycle generates and holds references to small objects. When I understand the SGEN logging correctly the _Nursery Full_ logging message indicates that no more objects can be allocated on the Nursery (aka Heap) and the GC starts collecting. When this is an expected behavior, everything is fine.
The 2 ms update has been chosen so that the GC logging occur quickly. I can imagine many use cases where views/pages need to be updated quickly.

**Comment by javiercn** [comment]
@b-straub I think so, the fact that the heap fills up only means that a gc needs to take place and free space. That's totally normal and expected. Trying to render every 2ms results in about 500 renders per second, which is more than what you can expect from any reasonable app, as it's more than 8 times than an app rendering at 60FPS (which is already quite high)

**Comment by rogihee** [comment]
Perhaps there can be some guidance in docs on advanced scenarios like this. Is a System.Threading.Timer the best solution (inside single treaded WASM runtime), is a JavaScript timer better (JS interop cost..), use a WebWorker, animationFrame...

**Comment by b-straub** [comment]
@rogihee I used for testing `Observables` from `System.Reactive` namespace.
