### ISSUE TITLE
Potentially Incorrect Error Text When CORS Middleware is Not Correctly Registered

### ISSUE THREAD

**Issue by JRousal** [dotnet/aspnetcore#21459]
### Describe the bug
When an endpoints requires a CORS policy to be registered but no CORS metadata is available in the pipeline for it the following error message is thrown:

InvalidOperationException: Endpoint {EndpointName} ({ProjectName}) contains CORS metadata, but a middleware was not found that supports CORS.
Configure your application startup by adding app.UseCors() inside the call to Configure(..) in the application startup code. The call to app.UseAuthorization() must appear between app.UseRouting() and app.UseEndpoints(...).

I believe the last sentence should read 'app.UseCors()' instead of 'app.UseAuthorization()'.

### To Reproduce

1. Create an endpoint requiring a CORS policy. 
2. Register the CORS middleware in the incorrect position in the pipeline.

### Further technical details
- ASP.NET Core version 3.1.102
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- IDE: VS2019

**Comment by pranavkm** [comment]
Thanks @JRousal. That is indeed a copy-paste error. Would you like to send us a PR to fix this?

**Comment by JRousal** [comment]
Looks like the current version of the code in master at `Microsoft.AspNetCore.Routing.EndpointMiddleware.ThrowMissingCorsMiddlewareException` already has the correct error text. Strange that this is still incorrect in release.

**Comment by pranavkm** [comment]
Ahh, looks like this was fixed in 5.0: https://github.com/dotnet/aspnetcore/commit/5f169dce1446693de1cd8d823a94665dd2d81040.

**Comment by JRousal** [comment]
Upon further checking, seems to have been resolved in #17892.

**Comment by Pilchie** [comment]
Closing resolved issue.
