### ISSUE TITLE
The first call to ProtectedBrowserStorage always timesout.

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#21463]
I am using blazor server side with Asp.net core 3.1 in visual studio 2019 preview.
Microsoft.AspNetCore.ProtectedBrowserStorage

The first call to  await  _protectedSessionStorage.SetAsync(USER_SESSION_OBJECT_KEY, user); always timeout.

On second click it works. Interestingly consecutive second call in the call does not work, it has to be second call via button click to execute the code second time

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Can you provide a minimal reproducible project that demonstrates your issue?
