### ISSUE TITLE
SignalR: sending dynamic objects

### ISSUE THREAD

**Issue by wmmihaa** [dotnet/aspnetcore#21469]
### Describe the bug
We have a dotnet core MVC app running SignalR. The application has been migrated from ASP.Net 4.8 where we often send dynamic objects or JObject to the client (JavaScript). These object originates from Json files, and are never typed. So we've just done:

```C#
var payload= NewtonSoft.Json.JsonConvert.DeSerializeObject(json);
client.Invoke("foo", payload);
```

Doing the same thing from SignalR (dotnet core), causes the client to **drop the connection** (which seams drastic to me):
```C#
var payload= NewtonSoft.Json.JsonConvert.DeSerializeObject(json);
 await client.SendAsync("foo", payload);
```
Is there a way we can transmit the payload without having a typed object. I don't have to use NewtonSoft, but I can't figure out how to use the new JsonSerializer to work with dynamic objects :(

PS. The code above is simplified...so sending raw JSON is not a preferred option either... ;)
### Further technical details
- ASP.NET Core version: *3.1*

**Comment by BrennanConroy** [comment]
A simple fix would be to switch to Newtonsoft.Json https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#use-newtonsoftjson-in-an-aspnet-core-30-signalr-project

The System.Text.Json library doesn't have as many features as Newtonsoft, so it's likely the specific payload you're sending fails to serialize and results in an error which will close the connection. If you look at Debug logs you can see the exception from the serializer.

**Comment by wmmihaa** [comment]
@BrennanConroy You are an absolute hero! 
Thank you!
