### ISSUE TITLE
IISRewrite Middleware appendQueryString

### ISSUE THREAD

**Issue by brianchance** [dotnet/aspnetcore#21464]
### Describe the bug
When using the IISRewriteModule, redirects with appendQueryString="true" only work if there is a ? in the redirect url.

### To Reproduce
Would expect this do work...
```
    <rule name="some rule" stopProcessing="true">
      <match url="^resource" />
      <action type="Redirect" url="/product" redirectType="Temporary" appendQueryString="true" />
    </rule>
```

To get this to work, you must append a ? to the action url...
```
    <rule name="some rule" stopProcessing="true">
      <match url="^resource" />
      <action type="Redirect" url="/product?" redirectType="Temporary" appendQueryString="true" />
    </rule>
```

### Analysis based on source
In RedirectAction (/Middleware/Rewrite/src/UrlActions/RedirectAction.cs)
If the url contains a ? (line 72), the request query string is appended to the query string of the url.
The else only adds the request query string if QueryStringDelete != true

The UrlRewriteFileParser (/Middleware/Rewrite/src/IISUrlRewrite/UrlRewriteFileParser.cs) uses the the second constructor (line 222) of RedirectAction which defaults queryStringDelete: true (line 39).

### Further technical details
- ASP.NET Core version - 3.1.3
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - VS2019 - Version 16.5.4

**Comment by brianchance** [comment]
Since the middleware is supposed to mimic IIS, I tested IIS and it does append the query string when there is not a ? in the url.

**Comment by anurse** [comment]
Yeah, that looks like it's a bug. Since you've done a great analysis of the code, would you be interested in contributing a Pull Request with the changes? We're happy to help you out!

**Comment by fstaffa** [comment]
I would like to implement a fix. Is this issue still free to take?

**Comment by jkotalik** [comment]
There is already a PR filed, I'm currently working on merging it (requires an announcement as it's a breaking change).

**Comment by fstaffa** [comment]
Thanks, not sure how I missed the PR
