### ISSUE TITLE
Revisit the messages we log and the log-level

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#21472]
We need to review what we log and at what level and need to make sure that the default log messages are not confusing in any way.

**Comment by mkArtakMSFT** [comment]
Closing as no customer complaints came up related to this.

**Comment by strizzwald** [comment]
Hi, can this be changed in future releases? Seeing this log message is quite confusing while debugging auth issues because there is no way to tell whether or not they are related to that log message.
