### ISSUE TITLE
Update Roslyn tooling dependency to 3.7.0-XYZ

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21470]
Roslyn is constantly publishing new packages under the 3.7.0 version; we need to update our dependency so we can consume latest bits from them. The latest thing we want to consume is the ExternalAccess.Razor changes that move more pieces from the old Razor ServiceHub project into ExternalAccess.Razor

/cc @tmat

**Comment by ryanbrandenburg** [comment]
Do we directly have packages for that other than Microsoft.Net.Roslyn.Diagnostics and Microsoft.Net.Compilers.Toolset?

**Comment by ryanbrandenburg** [comment]
Update for Microsoft.Net.Compilers.Toolset came through ~9 hours ago, but nuget only finds Microsoft.Net.Roslyn.Diagnostics on nuget.org.

**Comment by ryanbrandenburg** [comment]
This is going to depend on https://github.com/dotnet/roslyn/pull/43985/files.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg Re-opening this for now because I had to revert: https://github.com/dotnet/aspnetcore-tooling/pull/1907
