### ISSUE TITLE
Add open connections PollingCounter

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#21488]
There are counters for requests per second, total requests, failed requests and current requests; however there isn't a counter for the number of open connections (e.g. including connected clients in a keep-alive, but currently idle state)

This would be a good value to report.

/cc @davidfowl @NickCraver

**Comment by anurse** [comment]
#4769 seems to cover this, right? We're planning to look at that in the 5.0 timeline (as part of diagnostics for [YARP](https://github.com/microsoft/reverse-proxy)). If that issue doesn't cover it well, we can expand it.

**Comment by NickCraver** [comment]
There are built-in counters for the others but indeed I'd like to see connections. We'd definitely add them to our default metrics set for all Kestrel-enabled apps. I'm personally confused by #4769 because it's presented as events instead of counters and I'm not sure how that related to [the current Kestrel counters](https://github.com/dotnet/aspnetcore/blob/f3f9a1cdbcd06b298035b523732b9f45b1408461/src/Hosting/Hosting/src/Internal/HostingEventSource.cs#L85-L110) available.

**Comment by anurse** [comment]
> it's presented as events instead of counters 

For all our counters we also emit an event (when the EventSource is enabled). There are definitely counters listed there too.

> I'm not sure how that related to [the current Kestrel counters](https://github.com/dotnet/aspnetcore/blob/f3f9a1cdbcd06b298035b523732b9f45b1408461/src/Hosting/Hosting/src/Internal/HostingEventSource.cs#L85-L110) available.

That would be @davidfowl implementing those counters without checking the existing plan ;). We can certainly update the issue though.

**Comment by benaadams** [comment]
> > I'm not sure how that related to the current Kestrel counters available.

> That would be @davidfowl implementing those counters without checking the existing plan ;). We can certainly update the issue though.

The hosting counters (requests/s, requests in progress etc) work for all servers (i.e. Kestrel, IIS, HttpSys); however Hosting can't provide the current connection count because that works differently for all servers

**Comment by anurse** [comment]
Right. The issue I linked is for Kestrel specifically.

**Comment by BrennanConroy** [comment]
Should be fixed by https://github.com/dotnet/aspnetcore/pull/21649
