### ISSUE TITLE
Error "Assembly paths must be rooted" when referencing COM

### ISSUE THREAD

**Issue by hamermike** [dotnet/aspnetcore#21480]
### Describe the bug
Including a reference to a COM object causes the first build to fail while the subsequent build succeeds.

Error		The assembly path obj\Debug\netcoreapp3.1\Interop.{0}.dll is invalid. Assembly paths must be rooted.	{1}	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.CodeGeneration.targets	99	

### To Reproduce
Include a COM library reference to a ASP.NET Core project.

This issue has been referenced multiple times and has not been resolved.

There is a workaround described in this issue but it's far from ideal. This referenced issue also includes a sample project with the bug.
https://github.com/dotnet/aspnetcore/issues/5086

Second reference to the bug.
https://developercommunity.visualstudio.com/content/problem/899081/error-assembly-paths-must-be-rooted-when-referenci.html

### Further technical details
- ASP.NET Core 3.1.3
- Visual Studio 2019 16.4.3

**Comment by tenacioustechie** [comment]
This repo demonstrates the problem. 
https://github.com/tenacioustechie/ATEM-TallyLights

The COM library I'm referecing is the blackmagic ATEM switcher software & sdk
https://www.blackmagicdesign.com/au/support/family/atem-live-production-switchers

**Comment by tenacioustechie** [comment]
I've left a branch that has the issue. 
https://github.com/tenacioustechie/ATEM-TallyLights/tree/COMIssue

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by orellabac** [comment]
I think I am posting this too in my website blog but I have only found an ugly workaround:

1. Create a new project using the .NET Core Class Library template (I usually call it COMRefs).
2. Add your COM References to this library. Do not add any code, just build.
3. Take the Compiled Interop.* Libraries for example bin\Debug\netcoreapp3.1\Interop.CDO.dll and Interop.ADODB.dll and copy them to a Libs folder.
4. Now Right click your Web Application. Select Add COM Reference but now use the browse option and add the files from the Lib folder.
Remember that you .NET Core Web App must be set to x86 or x64 depending on your reference.
Now you can build and run

**Comment by drauch** [comment]
I think I've got a somewhat better workaround if your COM library does not contain any tag helpers:

Add the following to your csproj:
```
<Target Name="FixupComReferencesBeforeResolveTagHelperRazorGenerateInputs" BeforeTargets="ResolveTagHelperRazorGenerateInputs">
    <ItemGroup>
        <!-- Remove all your COM references, e.g., Interop.Excel in this case -->
        <RazorReferencePath Remove="obj\Debug\net5.0\Interop.Microsoft.Office.Interop.Excel.dll" />
    </ItemGroup>
</Target>
```

Best regards,
D.R.

**Comment by gekka** [comment]
Another workaround

``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <Target Name="resolveInteropOutputPath" BeforeTargets="ResolveComReferences"
          Condition="'@(COMReference)'!='' or '@(COMFileReference)'!=''">
    <PropertyGroup Condition=" '$(InteropOutputPath)' == '' ">
      <InteropOutputPath>$(MSBuildProjectDirectory)\$(IntermediateOutputPath)</InteropOutputPath>
    </PropertyGroup>
  </Target>
```

**Comment by vinodhmano** [comment]
Workaround that worked for me. 
1) Removed the COM reference 
2) Right click on the project -> Add -> COM Reference
3) Click on COM on the left and Browse
4) Navigate the DLL path. Usually it should be in C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Tools.Excel.v9.0\15.0.0.0__<gibrish>
5) Add it
6) Recompile the project.

I am running my api locally. I am not sure if it cause problem when deployed. But it works for now

**Comment by mkArtakMSFT** [comment]
Can someone please try this out with the latest 6.0 bits and confirm whether this works or not. Thanks

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
