### ISSUE TITLE
Alternative for System.Runtime.Caching in .net core?

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#21497]
I am using following for adding cache 

 ObjectCache defCache = MemoryCache.Default;
defCache.Add(key, o, new CacheItemPolicy { Priority = CacheItemPriority.Default });

And following for getting cache

  ObjectCache defCache = MemoryCache.Default;
                        return (T)defCache[key];

Problem with it i can't add null in cache

What should i use for in memory cache in .net core

I am getting Value cannot be null thrown from cache when trying to add null value
I just need it for object caching

**Comment by Pilchie** [comment]
You should take a look at the "Microsoft.Extensions.Caching.Memory" package.  Source for it for shipped versions is in dotnet/extensions, but has been moved to dotnet/runtime for .NET 5.0.

**Comment by KamranShahid** [comment]
I am using .net core 3.1
I were trying it but not able to create object of this class. later found out the correct git repository and posted a detail question there https://github.com/dotnet/extensions/issues/3226
Please check it

**Comment by Pilchie** [comment]
Thanks - closing this issue in favor of that one.
