### ISSUE TITLE
Weird stdoutLogFile behavior on Azure App Service 

### ISSUE THREAD

**Issue by pchimman** [dotnet/aspnetcore#21498]
One of my customer experienced facing the below issue after upgrading to the .NET CORE version to 3.1
![image](https://user-images.githubusercontent.com/64844681/81071592-8f978580-8f02-11ea-82a8-81f921393363.png)

The application is deployed in the Azure App Service.

The app starts failing when the stdout flag is set to true. During the startup of the process, we noticed that the app is using the below version of ASPNETCORE Module V2.

File Version: **13.1.19331.0**. Description: IIS ASP.NET Core Module V2. Commit: **62eee6e6d21c95668a9e9529dce6562cc6c9f3bf**

When we stdout flag is set to false, the app starts working and this time we see it uses the different version of AspNetCore module.

File Version: **13.1.19350.1**. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: **e276c8174b8bfdeb70efceafa81c75f8badbc8db**

Upon troubleshooting further, we came to know that the app starts failing when we set the stdoutlog path to stdoutLogFile=".\logs\stdout"

The moment we change the path to ‘stdoutLogFile= \\?\%home%\LogFiles\stdout Or D:\Home\Logfiles\stdout’, the app starts working with out any issues.

Is there any reason for this kind of behavior in the app service?

**Comment by holajan** [comment]
I have the same issue with web application on .NET 5.0 (v. 5.0.103)

**Comment by adityamandaleeka** [comment]
This was a bug in App Service that's just been fixed. The fix will roll out in an upcoming release. Closing this issue.
