### ISSUE TITLE
Cookie Auth not working with Https on IIS Express

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/aspnetcore#21495]
When creating a new Blazor App with Https enabled, cookie auth can't be used.

It does work without https OR with https without iis.

Version details:

VS 2019 Preview 16.6.0 Preview 5
ASP.NET Core Web App Project Templates: 3.1.4
Blazor WebAssembly App CLI v3.1.300-preview-015135

.NET Core 3.1
dotnet --version -> 3.1.300-preview-015135

Example, change the following files.

Index.razor to:
```
@page "/"

@inject HttpClient Http

<button @onclick="Click">Test</button>

@code {
    async Task Click()
    {
        try
        {
            await Http.GetFromJsonAsync<object>("WeatherForecast");
        }
        catch(Exception ex)
        {
            Console.WriteLine(ex);
        }
    }
}
```

WeatherForecastController.cs to:
```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BugRepro.Server.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet]
        public async Task<object> Get()
        {
            var identity = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.Name, "Test"),
                new Claim(ClaimTypes.Email, "test@test.test"),
            }, "Identity.Application", ClaimTypes.Name, ClaimTypes.Role);

            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(IdentityConstants.ApplicationScheme, principal);
            return Ok(new object());
        }
    }
}
```

Add to `ConfigureServices` in Startup.cs:
```
services.AddAuthentication().AddCookie("Identity.Application");
```

If you now start the application and use the `TEST` button, you will see the following error in the console (Firefox, but happens on other browsers as well):

```
﻿WebAssembly.JSException: TypeError: NetworkError when attempting to fetch resource. blazor.webassembly.js:1:37722
  at System.Net.Http.WebAssemblyHttpHandler.doFetch (System.Threading.Tasks.TaskCompletionSource`1[TResult] tcs, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x2d78dd8 + 0x00a54> in <filename unknown>:0 blazor.webassembly.js:1:37722
  at System.Net.Http.WebAssemblyHttpHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x2d50bf8 + 0x001be> in <filename unknown>:0 blazor.webassembly.js:1:37722
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) <0x2d55c38 + 0x00156> in <filename unknown>:0 blazor.webassembly.js:1:37722
  at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T] (System.Threading.Tasks.Task`1[TResult] taskResponse, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x2d57048 + 0x0010a> in <filename unknown>:0 blazor.webassembly.js:1:37722
  at BugRepro.Client.Pages.Index.Click () <0x2d236f0 + 0x00108> in <filename unknown>:0 blazor.webassembly.js:1:37722
```

I at first assumed it was some kind of CORS related issue, but it is not. A Test wihout iis express works.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.

**Comment by LunicLynx** [comment]
No this is a bug.

**Comment by javiercn** [comment]
@LunicLynx It is likely that you are trying to Deserialize 'object' and that is not supported. I would just return `Ok()` (no body) or a concrete type and update the client code appropriately.

**Comment by LunicLynx** [comment]
That  is just code to reproduce the issue, and I verified that it would work otherwise.

There is some exception thrown in the iis Express integration when using https and cookies auth.

**Comment by LunicLynx** [comment]
I just retried with Razor pages. Same Issue.

Code i used:

Index.cshtml.cs
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication6.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            var identity = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.Name, "Test"),
                new Claim(ClaimTypes.Email, "test@test.test"),
            }, "Identity.Application", ClaimTypes.Name, ClaimTypes.Role);

            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(IdentityConstants.ApplicationScheme, principal);
        }
    }
}
```

Add to ConfigureServices in Startup.cs:

```
services.AddAuthentication().AddCookie("Identity.Application");
```

**Comment by anurse** [comment]
Are you trying to use ASP.NET Core Identity? You're using the `IdentityConstants.AuthenticationScheme` value for your own cookie, which isn't recommended. Can you share a runnable sample that reproduces the issue? That way we can see if you've configured ASP.NET Core Identity as well as your own custom cookie auth and figure out if there's a conflict.

**Comment by LunicLynx** [comment]
This could be Windows Insider related, have to check on my work machine tomorrow.
@anurse The code above is actually the complete example, when starting with the default templates. I know that the code by it self does not make sense. This is intended. I tried to remove all fluff and reduce it to the problematic code. I would not do this in a real application.

**Comment by anurse** [comment]
Ok, it would really help to see the full context so can you produce a complete sample (i.e. something we can download or clone from git and run). It's really easy to miss steps in a description but code is clear ;).

**Comment by LunicLynx** [comment]
Here is a repo that reproduces the error:
https://github.com/LunicLynx/BugRepro_21495

1. Start it with HTTPS in IIS Express
2. Open the browser Tools
3. Click the TEST button
4. You should see an exception

Switch to selfhost with HTTPS, this suddenly works.

I'm on Windows Insider version: Build 19587.rs_prerelease.200313-1639

**Comment by mkArtakMSFT** [comment]
@HaoK can you please look into the provided repro project, thanks!

**Comment by HaoK** [comment]
I tried this on Windows10 Enterprise 18362.19h1_release.190318-1202, with VS2019 Version 16.7.0 Preview 1.0 and it doesn't repro

**Comment by HaoK** [comment]
The test button works and sends back a cookie on IISExpress Https
