### ISSUE TITLE
SignalR WebSockets - Error: There was an error with the transport.

### ISSUE THREAD

**Issue by mazxaxz** [dotnet/aspnetcore#21500]
### Describe the bug
Hey, I got a problem with WebSockets transport type. Since that, we are using LongPooling for now and it is working okayish. That thing is that if I want to connect to the hub with external application (node/js in browser) I get this error:  

`Error: Failed to start the connection: Error: There was an error with the transport.`

It might be the thing that my server does not support WebSockets transport type, but since we are working on a bash systems I haven't found solution yet. 
  
This is the list what I thought of that might cause the issue (some things may be missing): 
- client/server package versions
- ssl connections
- CORS (well not in a nodejs console app, but in browser)
- `endpoints.MapHub<>("...", o => o.Transports = HttpTransportType.WebSockets);` - no change
- `app.UseWebSockets()` manually - no change
- doesn't matter if it's executed inside docker container or at localhost
- actually had to use `skipNegotiations: true` since I get 404
- `@aspnet/signalr` and `@microsoft/signalr` differences

### To Reproduce
1. `dotnet new webapi`
2. Startup.cs. 
```c#
public void ConfigureServices(IServiceCollection services)
{
     services.AddControllers();
     services.AddSignalR();
}

public void Configure(IApplicationBuilder app)
{
     app.UseRouting();
     app.UseEndpoints(endpoints =>
     {
            endpoints.MapControllers();
            endpoints.MapHub<ChatHub>("/hub/chat");
     });
}
```
3. ChatHub.cs
```c#
public class ChatHub : Hub
{
}
```
4. .csproj should look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>YOUR_APP_NAME</RootNamespace>
  </PropertyGroup>
  
</Project>
```

5. Client (I used nodejs)
*index.js*
```js
const signalR = require("@microsoft/signalr");

let connection = new signalR.HubConnectionBuilder()
    .withUrl("http://localhost:5001/hubs/chat", { transport: signalR.HttpTransportType.WebSockets })
    .configureLogging(signalR.LogLevel.Debug)
    .build();

connection.start()
    .then(() => console.log("Connection started"))
    .catch(e => console.log(e));
```
*package.json*
```json
{
  "name": "signalr-web-client",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@microsoft/signalr": "^3.1.3"
  }
}
```

6. `dotnet run`
7. `node index.js`

### Further technical details
- dotnet and OS
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- node and npm
```
$ node -v
v12.13.0

$ npm -v
6.12.0
```
- IDE
```
JetBrains Rider 2019.2.4
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by BrennanConroy** [comment]
>     * actually had to use `skipNegotiations: true` since I get 404

Are you saying that WebSockets started working when you set this?

How is your server hosted? Is there a single instance?

**Comment by mazxaxz** [comment]
@BrennanConroy no no no, `skipNegotiations: false` (default) got me 404, when I changed it to `true` I'm getting transport error.

It's a single instance, good old `dotnet run` or out of the box F5 inside IDE. We are actually using SignalR on k8s cluster on production with LongPolling, because WebSockets error occurs there too.

**Comment by BrennanConroy** [comment]
Can you confirm that your app code is at the same endpoint as your client code is trying to connect to? In the code above your app is hosting the hub at "/hub/chat" but your client is trying to connect to "/hubs/chat". I assume it's a typo since you said LongPolling was working.

Can you share your server side logs? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging

**Comment by mazxaxz** [comment]
@BrennanConroy ye, that was a typo, endpoint is the same.
I'm gonna provide you the logs tomorrow, if thats ok :)

**Comment by mazxaxz** [comment]
@BrennanConroy ok, so actually there is no need to provide any logs.
It started to work after PC reset (who would have known :D), but the thing that messed up our production on k8s was the `[Authorize]` attribute causing Transport Error.

I'm gonna investigate that further and hopefully provide feedback in the future.
You can close the issue, thanks for "helping" :D

**Comment by mazxaxz** [comment]
Alright, so in my case this missing block was a problem:
```c#
services.AddAuthentication(x =>
    {
        x.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
    })
    .AddJwtBearer(options =>
    {
        var oidcAuthority = ...
        
        ...

        /* This block was missing */
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                var accessToken = context.Request.Query["access_token"];

                var path = context.HttpContext.Request.Path;
                if (!string.IsNullOrEmpty(accessToken) && path.StartsWithSegments("/hubs"))
                {
                    context.Token = accessToken;
                }
                
                return Task.CompletedTask;
            }
        };
        /* */
    });
```

Thank God we have a documentation for that:
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1
which I haven't read carefully.
