### ISSUE TITLE
.net core 3.1 web application terminates unexpectedly while running without giving any exception in visual studio 2019

### ISSUE THREAD

**Issue by mwaleedr** [dotnet/aspnetcore#21528]
I am running a .net core 3.1 web application in visual studio 2019 which terminates unexpectedly without giving any exception while running and when i see logs in windows event viewer i see there are two significant logs.
1. Application 'F:\Insignia Projects\Colaraz_Revamp\src\Services\Identity\Identity.API\' was recycled after detecting app_offline.htm.
 2. Application 'MACHINE/WEBROOT/APPHOST/IDENTITY.API' has shutdown. 
So I think the application termination is happening due to app_offline.htm, it is also important that there is no app_offline.htm is presented in my project. So please give me any suggestion about how to prevent this termination.

**Comment by anurse** [comment]
Are you just running from VS (i.e. F5 or Ctrl-F5) or publishing? VS does insert `app_offline.htm` files during publishing but shouldn't be doing that while running.

**Comment by mwaleedr** [comment]
Thanks @anurse for replying, i am running it in visual studio in debug mode and it is using IIS Express.
 I have also published it on iis and facing the same problem there, website suddenly say service is unavailable and there is no log in logs file but there are two logs in windows event viewer that i have discribed above.

**Comment by BrennanConroy** [comment]
Is there an app_offline file in your bin folder?

cc @BillHiebert

**Comment by mwaleedr** [comment]
@BrennanConroy there is no app_offline.htm in binfolder

**Comment by BrennanConroy** [comment]
Can you provide a repro app on GitHub?

**Comment by mwaleedr** [comment]
can't you give any suggestion without providing repository? @BrennanConroy

**Comment by BrennanConroy** [comment]
Could you set up debug logs via https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#aspnet-core-module-debug-log-iis so we can try to see where app_offline is coming from?

**Comment by mwaleedr** [comment]
i have set logs @BrennanConroy now the file aspnetcore-debug.log is being created, so do i need to share this file when i face service is unavailable problem?

**Comment by mwaleedr** [comment]
@BrennanConroy i have copied the file just after receiving the service is unavailable message,
[aspnetcore-debug.txt](https://github.com/dotnet/aspnetcore/files/4643150/aspnetcore-debug.txt)

**Comment by BrennanConroy** [comment]
@mwaleedr When you see the app recycle, are you modifying anything in the app folder? Like web.config, appsettings, code, etc.

@BillHiebert When does VS drop app_offline when debugging IIS apps?

**Comment by BillHiebert** [comment]
@BrennanConroy  it doesn't. I double-checked the code and we never write that file.

**Comment by mwaleedr** [comment]
@BrennanConroy i don't modify anything after app recycle and I don't need to modify anything because it automatically restarts after shutting down

**Comment by BrennanConroy** [comment]
> i don't modify anything after app recycle

Right, but are you doing anything before the recycle? We're trying to figure out why you're getting an app_offline file.

**Comment by mwaleedr** [comment]
what could i have been doing before recycle, it just restarts randomly

**Comment by mwaleedr** [comment]
@BrennanConroy i found today that the gap between two request was also causing the app to terminate. 
Basically this app is an identity server 4 app which i use to get token for my client apps. I was hitting api controller of my identity server 4 app instantly after getting token and this was creating service is unavailable error. Now what i did i place gap of 1 second between getting token and hitting api controller then i face that no error is being produced.
Do you think the time between two requests matter, if it does how to handle it on iis?

**Comment by BrennanConroy** [comment]
Could you install [processmonitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and add a filter to watch for the app_offline.htm file so we can see who is adding the file?

![image](https://user-images.githubusercontent.com/7574801/82501149-a2d15600-9aa9-11ea-9ccf-fdd3220e8777.png)

**Comment by mwaleedr** [comment]
@BrennanConroy  I have installed processmonitor but the result is now looking like this
![processMoniter](https://user-images.githubusercontent.com/43959790/82985200-0957f600-a00d-11ea-8c98-bbaee67350f7.png)

**Comment by BrennanConroy** [comment]
Could you save the filtered output to a file and provide that and take a look at the file generated event to see who created it?

**Comment by mwaleedr** [comment]
ok i can try it

**Comment by mwaleedr** [comment]
@BrennanConroy could you suggest an other way to solve this problem as i had told you that i observed the time gap between two requests is also causing the  application to terminate, how can i handle this.

**Comment by BrennanConroy** [comment]
> time gap between two requests is also causing the application to terminate

That seems unlikely unless there is a bug in the app that is terminating the process when the requests come in too quickly.

As of right now there isn't enough information for us to diagnose the problem further. Having a repro app would significantly help here. Also, figuring out who is writing the app_offline file and why will help.

If you think the "time gap between two requests" is the issue, then could you grab the application logs at debug or trace level and share them?

**Comment by mwaleedr** [comment]
Do you mean to share those logs which i had already shared with you once. Or do you mean logs which we create manually by implementing logging in our application.

**Comment by mwaleedr** [comment]
@BrennanConroy Do you mean to share those logs which i had already shared with you last time. Or do you mean logs which we create manually by implementing logging in our application.

**Comment by BrennanConroy** [comment]
Yeah your application logs https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging

**Comment by mwaleedr** [comment]
@BrennanConroy i have already implemented logging in my application. But i am unable to get help through this because nothing is logged when application terminates. The below are the log settings which i am using.
Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                .MinimumLevel.Override("System", LogEventLevel.Warning)
                .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.File(@"Logs\\identityserver4_log.txt")
                .WriteTo.Console(
                    outputTemplate:
                    "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}",
                    theme: AnsiConsoleTheme.Literate)
                .CreateLogger();

**Comment by mwaleedr** [comment]
This file i have recently copied after getting error.
[identityserver4_log.txt](https://github.com/dotnet/aspnetcore/files/4703840/identityserver4_log.txt)

**Comment by BrennanConroy** [comment]
> Also the file that was created has .pml extension. Which i am unable to upload

Rename the extension to .txt and share it

**Comment by mwaleedr** [comment]
[Logfile.txt](https://github.com/dotnet/aspnetcore/files/4705178/Logfile.txt)
Orignal name is Logfile.PML
@BrennanConroy

**Comment by BrennanConroy** [comment]
I don't see any writes of app_offline in that file. Did you capture this while reproducing the issue?

And again, if we could have a repro this would help significantly.

**Comment by MuhKuh7** [comment]
We have the same issue with IdentityServer using .net core 3.1.5

Event log also shows a restart caused by "app_offline.htm" every few minutes, which we confirmed is never created in the folder. We checked it using Process Monitor and by implementing a small console app to monitor the folder using `ReadDirectoryChangesW`.

Knowing that and looking at the code the only other path that leads to this specific event log message seems to be this one:
https://github.com/dotnet/aspnetcore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/AspNetCoreModuleV2/RequestHandlerLib/filewatcher.cpp#L229

I don't know however what would cause cbCompletion to return with 0 every few minutes and I don't understand the comment in the code about the "FCN overflow"
