### ISSUE TITLE
Cors no longer works

### ISSUE THREAD

**Issue by TehWardy** [dotnet/aspnetcore#21533]
I've noticed that with Chrome 76 there's an issue ...
   https://support.google.com/chrome/thread/11089651?hl=en

... That said, i'm seeing some requests fail and some succeed, and it appears that the CORS behaviour is somewhat inconsistent.

I have an API layer that for valid reasons actually doesn't care about CORS and needs to for good reason accept requests from anywhere.

I initialise CORS like this ...

```cs
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddMvcCore(options => options.EnableEndpointRouting = false)
        .AddDataAnnotations()
        .AddJsonOptions(options => options.JsonSerializerOptions.IgnoreNullValues = true)
        .AddCors(options => options.AddDefaultPolicy(builder =>
        {
            builder.AllowAnyHeader();
            builder.AllowAnyMethod();
            builder.SetIsOriginAllowed(origin => true);
            builder.AllowCredentials();
        }));
     ...
}

public void Configure(IApplicationBuilder app)
{
    ...
    app.UseCors(builder =>
    {
        builder.AllowAnyHeader();
        builder.AllowAnyMethod();
        builder.SetIsOriginAllowed(origin => true);
        builder.AllowCredentials();
    });
    ...
}
```

I'm seeing some calls fail and some succeed.
The google page seems to imply there are new headers or something?
I can't figure out wha these are but i'm asusming that aspnet core's CORS mechanism should just handle this for us.

The code in question is in an aspnet Core 3.1 application.

**Comment by javiercn** [comment]
@TehWardy thanks for contacting us.

Can you provide details on what the server response is to the request you are making (include the request and response from the browser/server) and well as a minimal repro project (the server portion at least) and what your expectation is? (What headers are not present in the response that you would expect to be present).

**Comment by TehWardy** [comment]
I don't know what the "new changes" are to the CORS standard I've just noticed that applications that worked have stopped both in the new edge and in chrome which from what I understand share webkit (maybe that's the cause).
As of this morning calls that used to succeed (not all but some) appear to be failing and I can't see why as my server logs all report that the requests made (both CORS and the follow on actual request) succeeded successfully.

From what I understand the existing request response life-cycle regarding OPTIONS requests are exhibiting the same expected correct behaviour as they did before.
Testing with POSTMAN reveals that i'm getting the same old expected 204's with the CORS headers allowing the subsequent request to take place (as i understand the CORS standard).

In chrome however having made the CORS call it then seems to reject it claiming a 502 from IIS which is part of the reason I ended up here, is there some discussion that you guys parhaps need to have with google to make sure aspnet core continues to function correctly despite their changes.

**Comment by TehWardy** [comment]
Some additional frustration ...
Chrome and Edge now filter the OPTIONS calls from the network tab in the dev tools so I don't know how to tell what's actually going on here from the browsers point of view.

As I mentioned about though, the server reports both a successful OPTIONS and paired other request and response.

To be clear ...
I'm not even convinced there's a problem with aspnet core here, this was just me trying to give  you guys some visibility of an issue i'm seeing that's affecting repsonses from what I believe is a working aspnet core service but results in a broken UI behaviour.

I'm reaching out in the hope that maybe you guys can spot something I can't and perhaps find a means to work around this.

**Comment by javiercn** [comment]
@TehWardy You could try and use fiddler to capture the response from the server (the 502).

I just spun an app and I have been able to do make cross-origin requests without issues without IIS, so I believe the only other reason you might be getting a 502 from IIS is due to something in your web.config that might be conflicting (rare, but I can't think of anything else).

To make sure I understand this correctly, are you saying that some requests fail and some requests succeed? Is it not all the time that this happens?

**Comment by TehWardy** [comment]
Ok This might not even be a CORS issue at all, just a huge coincidence.
I think this might be something new in my business logic that happens to present itself like a CORS failure on the front end.

I've noticed that our back end is crashing with ...

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'MyDbContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe. This could also be caused by a nested query being evaluated on the client, if this is the case rewrite the query avoiding nested invocations.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
```

... when I spin it up locally, I only caught this because in my own logging I noticed the app was starting up again after some requests (indication of a process drop I guess).

Any ideas how I debug / find out where / what might cause this?
EF is really starting to grind my gears :(

**Comment by javiercn** [comment]
You are not awaiting a query into a db context :(
