### ISSUE TITLE
how to get the Context.Items from Server

### ISSUE THREAD

**Issue by seeyouethan** [dotnet/aspnetcore#21530]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do get Context.Items but it has nothing.

the client is javascript ：
var connection = new signalR.HubConnectionBuilder().withUrl("http://localhost:54156/chatHub").build();

connection.MessageHeaders={‘name’:'liujingjie'}//if works

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

### Additional context
 
ex javascript has qs，but how can i delivery the qs in signalr latest?

**Comment by BrennanConroy** [comment]
I'm not really sure what you're trying to do. Could you please clarify.

`Context.Items` is server-side storage for a connection that is accessed inside of Hub methods.
I don't know what you're trying to do with `connection.MessageHeaders`, that isn't a thing.

**Comment by davidfowl** [comment]
Seems like @seeyouethan is trying to get data from the client to the server by trying to set properties on the client side connection. That doesn't work.

You can use the query string to accomplish that.
