### ISSUE TITLE
Blazor Server-Side Websocket closed with status code '1006' on real hosting

### ISSUE THREAD

**Issue by Domivan** [dotnet/aspnetcore#21546]
Good day!
Problem with server-side blazor.
On the real hosting, the application constantly loses connection with the server, reporting an error "websocket closed with status code 1006".
Already broke his head in search of a cause.
At the same time, the application works without problems on the local computer in development mode.
It got to the point that I decided to simulate everything from scratch.
It turned out that any blazor application loses its connection in the conditions of limitations of the iis server dedicated vitrual memory.
I created the start-up template of the blazor-server side application, didn’t add anything, published it on the local iis, in the iis settings I set 20Gb for virtual memory and 2Gb for allocated memory and I get websocket disconnections when the Click button on the Count page is clicked actively.
If you set the virtual memory size to 0, no shutdowns occur. But this does not meet the conditions of real hosting.
Friends, what's the problem?

**Comment by Domivan** [comment]
Conducted some research:
It seems that in the blazor sources there is a conflict of using a 32-bit library.
When IIS set to "allow to use 32-bit applications" to true
websockets are not disconnected

**Comment by javiercn** [comment]
@Domivan thanks for contacting us and thanks for the details!

We'll look into this issue and update it appropriately. Looping some SignalR folks and Server folks since they will know more.

@BrennanConroy @Tratcher @jkotalik do you have any thoughts on what can be at play here?

**Comment by BrennanConroy** [comment]
> 2Gb for allocated memory and I get websocket disconnections

What is the memory usage of your process when the websocket is disconnected? If you're hitting the 2Gb limit then IIS will restart the app and you'll lose all connections.

**Comment by Domivan** [comment]
Even the usual new blazor application template loses connection. I create a new application from the blazor srever side template, add nothing, publish it on IIS with a virtual memory limit and the socket will disconnect in a minute or two

**Comment by mkArtakMSFT** [comment]
Cleared the milestone so this doesn't slip through cracks.

**Comment by BrennanConroy** [comment]
Why are you configuring your Virtual Memory limit? By default it should be 0.

As you observed switching to 32 bit "fixes" the issue. This is likely because 64 bit is more aggressive with using virtual memory.

Also, you could try disabling server GC to see if less virtual memory is used.

**Comment by Domivan** [comment]
The virtual memory limit is strictly limited by the hosting provider; I cannot change this limit.

**Comment by Domivan** [comment]
Please share a solution to the problem. I found that all blazor server side applications somehow lose connection with error 1006, even the usual empty weather forecast template hosted on the IIS server. The time of occurrence of the error is not predictable. Reload the page after losing the connection is not a problem, but what about authorization? When disconnected, all authorization data is lost, you have to log in again.
If I’m wrong, provide a link to any blazor server side page that has no websocket shutdown

**Comment by BrennanConroy** [comment]
> Also, you could try disabling server GC to see if less virtual memory is used.

I mentioned one option, have you tried this out?

You can also try specifying the GC heap limit to keep memory down: https://github.com/dotnet/docs/blob/ed5a85b61908468f050220d8956a6769192f631f/docs/core/run-time-config/garbage-collector.md#systemgcheaphardlimitcomplus_gcheaphardlimit

**Comment by WayneHiller** [comment]
Anything new on this? I am having the same issue running the site in Kestrel.

**Comment by BrennanConroy** [comment]
If you're using Kestrel stand-alone then open a new issue. Otherwise the conversation above should solve the issue. Unless you have a different problem, in which case also open a new issue.

**Comment by mrlife** [comment]
@BrennanConroy I am having this issue on Windows with Apache. The connection is disconnected every few minutes and then reconnects. Sometimes, it has trouble reconnecting, and the app breaks. See the bolded "Error" below.

This is what the console looks like when the app is left idle:

> [Info] [2020-10-27T19:35:07.081Z] Information: Normalizing '_blazor' to 'https://MyURL/_blazor'. (blazor.server.js, line 1)
[Info] [2020-10-27T19:35:07.356Z] Information: WebSocket connected to wss://MyURL/_blazor?id=eXbNRQgEV0ypITcjFBbx8w. (blazor.server.js, line 1)
[Info] [2020-10-27T19:36:53.863Z] Information: Connection disconnected. (blazor.server.js, line 1)
[Info] [2020-10-27T19:36:56.871Z] Information: Normalizing '_blazor' to 'https://MyURL/_blazor'. (blazor.server.js, line 1)
[Info] [2020-10-27T19:36:57.167Z] Information: WebSocket connected to wss://MyURL/_blazor?id=OhoM5IM0eTBighz6OLpY3Q. (blazor.server.js, line 1)
**[Error] WebSocket network error: The operation couldn’t be completed. Socket is not connected (x2)
[Error] [2020-10-27T19:37:35.404Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'.
	(anonymous function) (blazor.server.js:1:5500)
	(anonymous function) (blazor.server.js:1:60705)
	(anonymous function) (blazor.server.js:1:47567)
	(anonymous function) (blazor.server.js:1:46604)**
[Info] [2020-10-27T19:37:38.405Z] Information: Normalizing '_blazor' to 'https://MyURL/_blazor'. (blazor.server.js, line 1)
[Info] [2020-10-27T19:37:38.696Z] Information: WebSocket connected to wss://MyURL/_blazor?id=OwqXfjS_pMdEpnLEqsdOQA. (blazor.server.js, line 1)
[Info] [2020-10-27T19:39:46.927Z] Information: Connection disconnected. (blazor.server.js, line 1)
[Info] [2020-10-27T19:39:49.930Z] Information: Normalizing '_blazor' to 'https://MyURL/_blazor'. (blazor.server.js, line 1)
[Info] [2020-10-27T19:39:50.258Z] Information: WebSocket connected to wss://MyURL/_blazor?id=YSG3JJDknVcRwl9crCxdWg. (blazor.server.js, line 1)

**Comment by mrlife** [comment]
@mkArtakMSFT I’m not sure it makes sense for this to be closed.
