### ISSUE TITLE
The ability to host multiple WASM apps inside one hosted project.

### ISSUE THREAD

**Issue by TaylorWatson** [dotnet/aspnetcore#21549]
Wondering if blazor has the ability to host multiple WASM apps inside a single hosted project.

Internally at my company we are testing using wasm apps for a lot of our internal apps. So far it's been going great, however most of the apps we would be building share a lot of resources and calls to same/common DBs.

Having a single hosted server app between many WASM apps would great for having a central repository. It would also make configuring third party API access much easier as there would only be one server app to configure among multiple webassembly apps and each could just pass the appropriate token.

For example, we could have internal.corp/app1 ... internal.corp/app2 ... etc.

This allows us to have a central url for our employee's to remember but still allows us to separate apps into their own containers making it much easier to manage than one large app.

**Comment by danroth27** [comment]
Hi @TaylorWatson. Thanks for sharing these details about your scenario! Makes sense. You can find a sample on how to set this up here: https://github.com/javiercn/BlazorMultipleApps. Let us know if you have additional questions!
