### ISSUE TITLE
Package validation failure for Microsoft.AspNetCore.AzureAppServices.SiteExtension

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#21543]
We hit the following in package validation:

> Microsoft.AspNetCore.AzureAppServices.SiteExtension.5.0.0-preview-5-20254-2.nupkg's dependency 'Microsoft.Web.Xdt.Extensions with versions: 5.0.0-preview.5.20254.2, not found neither locally nor in nuget.org

We should follow up to see if this is a real issue

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/issues/20818

**Comment by wtgodbe** [comment]
Ah, nice catch. Closing as dupe
