### ISSUE TITLE
Can using HttpClient release connections correctly?

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/aspnetcore#21559]
Can HttpClient release connections correctly using using.net CORE 3.x?Or do we continue to use static storage, dependency injection is not the solution we need, it is not elegant and flexible, I want to ask the question?Can you answer me?

**Comment by davidfowl** [comment]
Keep using the singleton. Nothing has changed in .NET Core 3.x. You can common on this issue https://github.com/dotnet/runtime/issues/33124
