### ISSUE TITLE
Any new Blazor component added is not found with routing

### ISSUE THREAD

**Issue by mkopara** [dotnet/aspnetcore#21563]
In blazor WA when I add a new page and define its route
@page "/test-page/page1" I am always getting a default NoFind error.

So I tried to copy/paste existing page and replace the content of that page with the contents of the previously working page, and it works fine.

Bottom line, any new page created using Visual Studio > New Item > Razor Component creates the same issue.

VS 16.5.3
PWA v.3.2.0-rc1.20223.4 
* project was upgraded from v.3.2.0-preview3.20168.3

**Comment by javiercn** [comment]
@mkopara thanks for contacting us.

Can you provide a minimal repro project and detailed steps to reproduce the issue?

If you are putting the page in a different assembly, you need to add it to the list of assemblies discovered by the router.

**Comment by mkopara** [comment]
In this particular case when any new component was added VS Build Action was by default setted as None. Changing it to Content resolved this issue. Not sure why default action is None as this can cause frequent issues.

**Comment by javiercn** [comment]
@mkopara I think that's something to do with your project/VS config. 

The default action for razor files is Content, but I'm glad that you sorted it out!
