### ISSUE TITLE
The Webapi result lost some value

### ISSUE THREAD

**Issue by magicdict** [dotnet/aspnetcore#21568]
### Describe the bug

The Webapi result lost some value

### To Reproduce

``` C#
public class POI
{
    public string Name { get; set; }

    public int Price { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public double lat { get; set; }

    public double lng { get; set; }

    public List<string> Comments { get; set; }

    public int CommentCount { get; set; }

    public List<WordCloudItem> WordCloud { get; set; }
}


public class WordCloudItem
{
    public string name;

    public int value;
}

public class SpotInfo : POI
{
    public string Type { get; set; }

    public string ALevel { get; set; }

    public string OpenTime { get; set; }

    public string ServiceTel { get; set; }

    public string IssueTel { get; set; }

    public string TrafficGuide { get; set; }
}

 services.AddMvc().AddJsonOptions(op => op.JsonSerializerOptions.PropertyNamingPolicy = null);

```
![image](https://user-images.githubusercontent.com/897796/81276750-07da8400-9086-11ea-9e76-026e6f29361b.png)

property WordCloud lost value...

### Further technical details
- ASP.NET Core version : 3.1.201
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by magicdict** [comment]
![image](https://user-images.githubusercontent.com/897796/81277342-df06be80-9086-11ea-85b6-d40e2c4f711b.png)

**Comment by pranavkm** [comment]
System.Text.Json does not support deserializing fields - https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#public-and-non-public-fields. You'll have to turn them in to properties:

```C#
public class WordCloudItem
{
    public string name { get; set; }

    public int value { get; set; }
}
```
