### ISSUE TITLE
Blazor - Multiple pages support

### ISSUE THREAD

**Issue by vd3d** [dotnet/aspnetcore#21574]
Hi,

Currently Blazor is made for SPA, of course we can split it with area but we can only have one
_Host.cshtml page for the entire application.

In my situation, each area is really different, and I need to include different CSS libs, JS libs etc...

So, I have try to play with MapFallbackToAreaPage/MapFallbackToPage etc... but I can't find any solution that really work !

What I wish is the ability to have a 'root' cshtml page per area, but not sure it is possible today ?

BTW, I have a post on stackoverflow about this:
https://stackoverflow.com/questions/61490973/blazor-multiples-area-custom-hostm-cshtml?noredirect=1#comment108802743_61490973

Is there a solution (and an example somewhere) ?

Thx

**Comment by javiercn** [comment]
@vd3d thanks for contacting us.

Can you give us more details about what you are trying to achieve? It's not clear from the initial text of the issue.

* Do you have 1 app or more than 1 blazor app?
* Do you want to render different root components of the same blazor app in different areas?
* Do you want to have multiple blazor apps and render each one of them in a separate area?

**Comment by vd3d** [comment]
Thanks,

It is not multiples app, it is the same application, but with multiples area.

Each area have a different:
- layout
-features
-reference to Javascript and CSS file

Imagine we have an admin area, a customer area (Like for a SASS) and a web site by example.
Each one can have its own cshtml file, without any relation !

**Comment by javiercn** [comment]
@vd3d that should be doable with the guidance I gave you. Use different MapFallbackTo overloads and set  the correct base tags on the pages and everything else should work just fine.

**Comment by vd3d** [comment]
Thanks,

Not sure your sample help, because in my case I don't have different URLs !

Here is what I've try:

```
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapBlazorHub();
                endpoints.MapBlazorHub("~/areas/my/_blazor");
                endpoints.MapFallbackToAreaPage("~/my/{*clientroutes:nonfile}", "/areas/my/pages/_Host", "My");
                endpoints.MapFallbackToPage("/_Host");
            });
```

And a lot of other combinations, but without any chance to make it work!
I need a default mapping, then a mapping per area !

I always got the same kind of error like: 

> AmbiguousMatchException: The request matched multiple endpoints. Matches: /_Host /_Host /_Host

**Comment by javiercn** [comment]
@vd3d ah, I didn't realize you were using server-side blazor. 

You only need a call to `MapBlazorHub()` and you need to change the route in `endpoints.MapFallbackToPage("/_Host");` otherwise it will always match any route containing `my` and that causes the ambiguity.

**Comment by vd3d** [comment]
Sorry, I don't understand... what do you mean by changing the route, it is the default route! Do you have an example ?
