### ISSUE TITLE
Is it possible to load template code which is razor code from a file or from sql table in Blazor?

### ISSUE THREAD

**Issue by Rahul-Narayanasamy** [dotnet/aspnetcore#21573]
Is it possible to render a template code/razor code(which may contain any razor code including if else conditions-swich cases- context- variables-etc.etc) ) from a file or database as string and compile it to executable Razor code at runtime?

**Comment by javiercn** [comment]
@Rahul-Narayanasamy thanks for contacting us.

No, this is not a Blazor feature and is not something we plan to implement. Razor components are compiled to C# clases in your assembly when your project is built and we don't support compiling them at runtime.
