### ISSUE TITLE
Forcing use of runtime version 2.2.x but still Microsoft.AspNetCore.Mvc.Razor loaded from 3.1

### ISSUE THREAD

**Issue by spsinghats** [dotnet/aspnetcore#21589]
Web server has both runtimes 3.1.3 and 2.2.2. Below is the dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

I run the asp .net core web app using below web.config:
`<aspNetCore requestTimeout="23:00:00" processPath="dotnet" arguments="--fx-version 2.2.2 --roll-forward Disable .\My.Web.dll" forwardWindowsAuthToken="false" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" startupTimeLimit="3600">`

And the My.Wen.runtimeconfig.json lokks like below:
`{
  "runtimeOptions": {
    "tfm": "netcoreapp2.2",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.2.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}`

I get below errors and website fails to launch.
`error CS0433: The type 'HeadTagHelper' exists in both 'Microsoft.AspNetCore.Mvc.Razor, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

error CS1705: Assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures' with identity 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
`
Why is the 3.1.0.0 version even being activated, even when roll forward is disabled?

**Comment by pranavkm** [comment]
@spsinghats are you able to share your project file? It's not very clear why your 2.2 app would be attempting to load a 3.x binary. Rollforwards shouldn't affect this. 

As an aside, 2.2 is no longer in support: https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle. We recommend upgrading to a supported LTS release.
