### ISSUE TITLE
Clarify how Blazor handles web.config in publish phase

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#21600]
Recently, we added support for user-provided web.config's in publish Blazor apps. However, the web.config must be in the root of the project.

We should consider:

- Whether it makes sense to add a warning to users who have added a web.config to another directory
- Whether we want to support web.config files in any directory in the future
- Documenting this caveat for users

**Comment by javiercn** [comment]
> * Documenting this caveat for users

Why do you think this is a caveheat? I would think this is expected since I can't think of any other way it can work?

> * Whether we want to support web.config files in any directory in the future

Is there any specific scenario you have in mind?

> * Whether it makes sense to add a warning to users who have added a web.config to another directory

I'm not sure this makes sense, after all we can't know what users want to do and their scenario might be legitimate?

**Comment by captainsafia** [comment]
> Why do you think this is a caveheat? I would think this is expected since I can't think of any other way it can work?

I responded to an issue from someone internal where they had their web.config in the `wwwroot` directory and were surprised by the resulting behavior:

* The web.config in the wwwroot directory is copied over to the wwwroot in the publish directory
* The standalone web.config is copied to the publish directory as well

So you get into this weird situation where there are two config files in your published output: yours and the standard one. This seems like buggy behavior, IMO.

> Is there any specific scenario you have in mind?

We got feedback about supporting having the web.config inside the `wwwroot` instead of outside it.

> I'm not sure this makes sense, after all we can't know what users want to do and their scenario might be legitimate?

I think it depends on how we approach the other questions. If we want to keep the behavior as is, we should probably add a warning so the user doesn't get into the weirdness described above.

**Comment by javiercn** [comment]
> * The standalone web.config is copied to the publish directory as well

On a hosted project? That sounds like a bug

**Comment by captainsafia** [comment]
This occurred on a standalone project. I think it is buggy in either case, especially since we currently claim in the docs that custom web.config's are respected without any caveats.

**Comment by captainsafia** [comment]
Looks like we already document this in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#use-a-custom-webconfig.
