### ISSUE TITLE
How to access client cert chain from custom middleware or callback?

### ISSUE THREAD

**Issue by and-rewsmith** [dotnet/aspnetcore#21606]
### Is your feature request related to a problem? Please describe.
I am in the process of migrating the [Azure iotedge](https://github.com/Azure/iotedge) codebase from aspnet 2.2 to 3.1. 

We currently make use of [an adapter](https://github.com/Azure/iotedge/blob/master/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Adapters/HttpsExtensionConnectionAdapter.cs#L196) to retrieve the client cert chain and save it for later use. We then can access the cert chain later with an[ HttpContext extension](https://github.com/Azure/iotedge/blob/master/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Extensions/HttpContextExtensions.cs).

According to the migration guide, we can no longer use adapters and will need to convert this to middleware. It seems that we do not need most of the logic currently in our adapter since a lot is duplicated in the [aspnetcore internal middleware](https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs). All we will need to do is access the client cert chain and save it in the ConnectionContext.

I haven't found a similar example or documentation detailing how to access the client cert chain from custom middleware. I am aware that the HttpsConnectionAdapterOptions provides a certificate validation callback that exposes the cert chain, however we need to shove the cert chain into the scope of the connection (which is inaccessible in this callback). 

Is accessing the client cert chain from custom middleware possible? I would try to do it the same way as in aspnetcore's HttpsConnectionMiddleware, but it seems that the logic relies on internal types. Any recommendations here would be super helpful 🙂

### Describe the solution you'd like
An explanation, example, or documentation for how to access the client cert chain from custom middleware or a callback which has the connection in scope.

**Comment by and-rewsmith** [comment]
We figured it out.

>  I am aware that the HttpsConnectionAdapterOptions provides a certificate validation callback that exposes the cert chain, however we need to shove the cert chain into the scope of the connection (which is inaccessible in this callback).

This callback I was using was the RemoteCertificateValidationCallback root-level in HttpsConnectionAdapterOptions. There is the same callback nested in OnAuthenticate.

Here is what it ended up looking like:
```
                                new HttpsConnectionAdapterOptions()
                                    {
                                        ServerCertificate = serverCertificate,
                                        OnAuthenticate = (context, options) =>
                                        {
                                            options.RemoteCertificateValidationCallback = (_, clientCert, chain, policyErrors) =>
                                            {
                                                TlsConnectionFeatureExtended tlsConnectionFeatureExtended = GetConnectionFeatureExtended(chain, context);
                                                context.Features.Set<ITlsConnectionFeatureExtended>(tlsConnectionFeatureExtended);
                                                return true;
                                            };
                                        },
                                        ClientCertificateMode = certificateMode,
                                        SslProtocols = sslProtocols
                                    });
```

**Comment by and-rewsmith** [comment]
Reopening as this didn't work. When I tried to do this I got the following exception:
```
<7> 2020-05-08 07:31:35.532 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 0.
<7> 2020-05-08 07:31:42.076 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel] - Connection id ""0HLVJ4546DPA7"" accepted.
<7> 2020-05-08 07:31:42.076 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel] - Connection id ""0HLVJ4546DPA7"" started.
<3> 2020-05-08 07:31:42.077 +00:00 [ERR] [Microsoft.AspNetCore.Server.Kestrel] - Unhandled exception while processing "0HLVJ4546DPA7".
System.InvalidOperationException: The 'RemoteCertificateValidationCallback' option was already set in the SslStream constructor.
   at System.Net.Security.SslStream.SetAndVerifyValidationCallback(RemoteCertificateValidationCallback callback)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
<7> 2020-05-08 07:31:42.078 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel] - Connection id ""0HLVJ4546DPA7"" stopped.
<7> 2020-05-08 07:31:42.078 +00:00 [DBG] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] - Connection id ""0HLVJ4546DPA7"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
<7> 2020-05-08 07:31:45.535 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Getting next batch for endpoint iothub starting from 0 with batch size 100.
<7> 2020-05-08 07:31:45.535 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Obtained next batch for endpoint iothub with batch size 0. Next start offset = 0.
```

**Comment by blowdart** [comment]
@tratcher

**Comment by Tratcher** [comment]
Use the HttpsConnectionAdapterOptions.ClientCertificateValidation property instead.
https://github.com/dotnet/aspnetcore/blob/95a22085303f9230b23294782c0ecd5668343641/src/Servers/Kestrel/Core/src/HttpsConnectionAdapterOptions.cs#L61

**Comment by and-rewsmith** [comment]
@Tratcher That won't work for us unfortunately. We would like to access the client cert chain when the connection is in scope so that we can do this:.

**Comment by Tratcher** [comment]
Oh, sorry. I think you're stuck unless/until we change this behavior in Kestrel. We should be able to move where we wire up the callback so that it becomes replicable.

**Comment by and-rewsmith** [comment]
@Tratcher Just to confirm, are you saying that implementing this is also not possible with custom middleware?

**Comment by Tratcher** [comment]
? At the moment you'd have to fork the Https middleware.

**Comment by and-rewsmith** [comment]
@Tratcher We looked at the internal implementation of the https middleware and came up with the following solution:

```
                                new HttpsConnectionAdapterOptions()
                                    {
                                        ServerCertificate = serverCertificate,
                                        OnAuthenticate = (context, options) =>
                                        {
                                            if (clientCertAuthEnabled)
                                            {
                                                options.ClientCertificateRequired = true;
                                                options.RemoteCertificateValidationCallback = (_, clientCert, chain, policyErrors) =>
                                                {
                                                    Option<X509Chain> chainOption = chain == null ? Option.None<X509Chain>() : Option.Some(chain);
                                                    TlsConnectionFeatureExtended tlsConnectionFeatureExtended = GetConnectionFeatureExtended(chainOption);
                                                    context.Features.Set<ITlsConnectionFeatureExtended>(tlsConnectionFeatureExtended);
                                                    return true;
                                                };
                                            }
                                        },
                                        ClientCertificateMode = ClientCertificateMode.NoCertificate, // we can override this in OnAuthenticate if using certs
                                        SslProtocols = sslProtocols
                                    });
```

**Comment by and-rewsmith** [comment]
@Tratcher I'm going to close the issue. You can open it again if this isn't the expected use case and think it needs fixing.

**Comment by Tratcher** [comment]
@and-rewsmith you're right, I overlooked that possibility.
