### ISSUE TITLE
Allow render fragments for Blazor components in MVC views

### ISSUE THREAD

**Issue by joseph-turk** [dotnet/aspnetcore#21603]
I am working on an MVC app that we are gradually adding Blazor components to. It would be great if there was support for passing razor content to the `ChildContent` parameter in a component that is being rendered in an MVC view.

This is what I'd like to be able to do:

```
<component type="typeof(MyComponent)" render-mode="ServerPrerendered">
  <p>Content to go inside ChildContent</p>
</component>
```

**Comment by javiercn** [comment]
@joseph-turk thanks for contacting us.

We'll discuss this request and update this issue accordingly.

**Comment by pranavkm** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by 944332213** [comment]
Is there any progress?I'm using 3.1.
If I use index. razor, but InputFile requires 5.0-preview.
If I use index.cshtml, Then I'm at &lt;component /&gt; Difficulty in passing RenderFragment ChildContent.
Are there any alternatives to upgrading to 5.0-Preview?

**Comment by 944332213** [comment]
> Is there any progress?I'm using 3.1.
> If I use index. razor, but InputFile requires 5.0-preview.
> If I use index.cshtml, Then I'm at <component /> Difficulty in passing RenderFragment ChildContent.
> Are there any alternatives to upgrading to 5.0-Preview?

In view of the file upload 3.1, I found this: <http://blog.stevensanderson.com/2019/09/13/blazor-inputfile/>
A better approach is still to recommend upgrading the project to 5.0

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
