### ISSUE TITLE
Blazor wasm not including "Authorization: bearer" http header in calls to controllers

### ISSUE THREAD

**Issue by Grizor1911** [dotnet/aspnetcore#21617]
Hi, I was migrating my project from Microsoft.AspNetCore.Blazor to Microsoft.AspNetCore.Components.WebAssembly when all the api controllers stop receiving the JWT authorization header. When I test the controllers from PostMan sending the token all is working fine.

The token is received by client from server correctly but seems is not saved or **not included** in the HttpClient GetAsync call. The response of the server is always **http error 401**.

I have used Blazored.LocalStorage and custom AuthenticationStateProvider in the client side.
This is a part of the AuthService.cs:

     if (loginResult.Successful)
     {
        await _localStorage.SetItemAsync("authToken", loginResult.Token); 
        ((ApiAuthenticationStateProvider)_authenticationStateProvider).MarkUserAsAuthenticated(loginResult.Token);
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", loginResult.Token);

        return loginResult;
     }

And part of ApiAuthenticationStateProvider.cs

      public void MarkUserAsAuthenticated(string token)
      {
            var authenticatedUser = new ClaimsPrincipal(new ClaimsIdentity(ParseClaimsFromJwt(token), "jwt"));
            var authState = Task.FromResult(new AuthenticationState(authenticatedUser));
            NotifyAuthenticationStateChanged(authState);
      } 

LoginResult is correct and no other error appears. Before trying to migrate the project to the last blazor template every was working correctly.

**Microsoft.AspNetCore.Components.WebAssembly version 3.2.0-rc1.20223.4**

I think it will be a little difficult to reproduce the error for you, but could you give me an idea of ​​what's going wrong, please ?

Thanks.

**Comment by javiercn** [comment]
@Grizor1911 thanks for contacting us.

Based on your description is impossible for us to know what can be going wrong. I would suggest you try to use our authentication options (token based too) instead of rolling your own auth.

If you can provide a repro project we can take a look, but with the current description we don't have enough information to help you.

**Comment by Grizor1911** [comment]
Thanks. I'll take a look. I will try to make a "minimal" repro project, but anyway, the issue can be closed.

**Comment by Grizor1911** [comment]
Note: I've noticed that the problem was that for some reason HttpClient.HttpDefaultHeaders.Authorization is changing to null between requests.
