### ISSUE TITLE
In VS cloud scenarios Peek Definition doesn't do anything

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#21611]
The `Peek Definition` command (`ALT + F12`) doesn't do anything in VS cloud scenarios.

Expected:
Peek to signature of method.

Actual:
![Peek Defn 2](https://user-images.githubusercontent.com/14852843/81372686-d8d90800-90af-11ea-881c-3d4ef3433278.gif)

**Comment by TanayParikh** [comment]
Possibly related to: https://github.com/dotnet/aspnetcore/issues/21070

**Comment by NTaylorMullen** [comment]
I'm actually surprised you get that command list item to begin with. Seems like a bug in the LSP platform editor to be honest

**Comment by TanayParikh** [comment]
Yeah that would make sense considering the other navigation commands aren't available either.

I'll create a VSTS issue.

**Comment by TanayParikh** [comment]
Closing out here as this is external https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1120900

**Comment by ajaybhargavb** [comment]
Btw PeekDefinition will cause a hang now but the fix for that is tracked here https://github.com/dotnet/aspnetcore/issues/22106.
