### ISSUE TITLE
api post not working when F5 refreshing

### ISSUE THREAD

**Issue by robertdunaway** [dotnet/aspnetcore#21623]
I'm currently on Blazor version

I'm getting a simple list during OnInitialized().  When first loading the page the data is returned.  If I press F5 to reload the page the GetTraceListRecords() is executed but I get this error.

![image](https://user-images.githubusercontent.com/7198243/81428396-3447dc00-912a-11ea-89a9-efcfa2c3c6a4.png)

    protected override void OnInitialized()
    {
        start = DateTime.Now.Millisecond;
        AppState.OnChange += StateHasChanged;

        GetTraceListRecords();

        base.OnInitialized();
    }

    private void GetTraceListRecords()
    {
        
            Task.Run(async () =>
            {
                TraceRecords = await Http.PostJsonAsync<List<TraceListEntity>>("api/GetTraceSearchRecords", AppState.User.TenantName);

                StateHasChanged();
            });

       
    }

**Comment by javiercn** [comment]
@robertdunaway thanks for contacting us.

Can you provide us with a minimal repro project so that we can determine if there is an issue here?
