### ISSUE TITLE
Blazor server-side and CSRF

### ISSUE THREAD

**Issue by TheCakeMonster** [dotnet/aspnetcore#21624]
I'm uncomfortable with the information available on Blazor server-side and CSRF protection. It looks like Blazor server-side can be vulnerable to CSRF because the protection in the platform might be incomplete; if this is not true then there is insufficient information on it for this to be obvious.

The problems seem to be threefold:

1) Protection seems to be based solely on CORS, which is still not supported by all browsers; caniuse.com suggests about 3% of UK users are still using a browser that doesn't support CORS but on which Blazor server-side will work, especially Opera Mini

2) There is no defence in depth in the protection available should CORS be incorrectly configured, not available, or compromised in a particular browser

3) The default in the templates is for CORS to be enabled for the Blazor hub, so the protection is OFF by default. This doesn't seem to fit with the principle of secure by default. Is there a good reason for it not being on by default?

Should there not be additional protection applied to the Blazor server-side communications infrastructure that ensures users of applications built with it are not susceptible to CSRF?

NOTE: This is based on limited research; I do not have sufficient knowledge of SignalR to have proven the issue with a real world sample.

**Comment by javiercn** [comment]
@TheCakeMonster thanks for contacting us.

* CORS is disabled by default in ASP.NET Core templates. You can't initiate a Blazor session from a separate origin unless you explicitly configure your app to do so.
* CORS is supported by all the browsers we support.
![image](https://user-images.githubusercontent.com/6995051/81582894-6c872e80-9365-11ea-8217-966bee006f70.png)
* You can disable CORS explicitly from the Hub endpoint if you need to do so. See [here](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/threat-mitigation?view=aspnetcore-3.1#cross-origin-protection) for details

In addition to that, all browsers that are supported by Blazor support samesite cookies which is our recommendation in that case.
