### ISSUE TITLE
'AuthenticationBuilder' could be found

### ISSUE THREAD

**Issue by ggraur** [dotnet/aspnetcore#21621]
hi,
I'm trying to implement google authentication method and I' m getting next error.

Error	CS1061	'AuthenticationBuilder' does not contain a definition for 'AddGoogle' and no accessible extension method 'AddGoogle' accepting a first argument of type 'AuthenticationBuilder' could be found (are you missing a using directive or an assembly reference?)	

the project file attached
[project file.txt](https://github.com/dotnet/aspnetcore/files/4600147/project.file.txt)

**Comment by blowdart** [comment]
You appear to be mixing of versions, for example you're targetting netcoreapp3, but using aspnet core libraries from 2.2.0, 5.0.0, netcoreapp 2.2.8 and more. Until you harmonize everything to the maximum version you're trying to target this is never going to work I'm afraid.

**Comment by ggraur** [comment]
Hi blowdart,
thanks, for your suggestion, 
I have solved the issue after installing "Microsoft.AspNetCore.Authentication.Google 3.0.0" from nuget gallery.
thanks,

**Comment by blowdart** [comment]
You're still mixing 5.00 preview pieces everywhere though, so really you need to syncronise everything to the main aspnet otherwise you will see unexpected behaviours

**Comment by ggraur** [comment]
i will do it,
thanks,
