### ISSUE TITLE
[LSP Editor] Creating a new Razor component is temporarily recognized

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21631]
Open a Blazor project. Right click the Pages folder and click Add -> RazorComponent. Try using that component in any file.

The component will be temporarily available and then will dissapear. Editing that added file will result in it showing up in IntelliSense again.

**Comment by TanayParikh** [comment]
Ignore this issue for validation; depends on https://github.com/dotnet/aspnetcore/issues/22594
