### ISSUE TITLE
Asp.Net Core Web API Google Authentication

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#21636]
Is there any docs about securing Web API with Google authentication? Most of documentation is for MVC or at least assuming an existing UI for login. My intent is to have a bear bone API (no views), and upon a request to secure endpoint to be redirected to Google consent page.

**Comment by Tratcher** [comment]
JwtBearer is designed for use in Web APIs. This looks like a good writeup: https://stackoverflow.com/a/48768183/2588374

**Comment by ylr-research** [comment]
@Tratcher interesting link, thank you. Really helpful. I see there’s still some people recommending to validate `aud`, even Google does, but the answer was never updated. Do you think the following is ok for that matter?
 ``` C#
 new GoogleJsonWebSignature.ValidationSettings{Audience = "ClientId"}
```

**Comment by Tratcher** [comment]
I can't speak to Google specific validation, you should check their guidance.

**Comment by blowdart** [comment]
Closing as answered
