### ISSUE TITLE
Running Blazor (ASP.NET hosted) app starts browser without extensions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21641]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1019896/running-blazor-aspnet-hosted-app-starts-browser-wi.html)._

---
[regression] [worked-in:16.6.0 Preview 4.0]
# Describe the bug
When running an ASP.NET Core hosted Blazor WASM app, it launches Chrome in some non-standard mode where extensions are not loaded / passwords are not saved.

# To Reproduce
1: Install a Chrome plugin (Redux DevTools for example)
2: Create an ASP.NET Core hosted Blazor WASM project
3: Run it
4: Start a new instance of Chrome (not just a new tab)
5: Navigate to the same URL
6: Compare the UI of Chrome

Expected: Plugins should be loaded in both
Actual: Plugins are only loaded in the manually started instance

This problem does not exist when creating an ASP.NET Core MVC web app.

---
#### Visual Studio Feedback System on 5/6/2020, 08:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This is because when debugging VS uses a new browser profile. This issue is being tracked at: https://github.com/dotnet/aspnetcore/issues/21540
