### ISSUE TITLE
Intermittent error when using JavaScript in OnAfterRenderAsync and having the console open

### ISSUE THREAD

**Issue by gavilanch** [dotnet/aspnetcore#21647]
### Describe the bug
In Blazor WebAssembly (RC1), I'm trying to execute a JavaScript function from a simple JavaScript file in the OnAfterRenderAsync method of a routable component. In the index.html file I also got a reference to jQuery from a CDN. For some reason, sometimes, when refreshing the page I get the error:

 _Unhandled exception rendering component: Could not find 'initializeCounterComponent' in 'window'._

Where initializeCounterComponent is the function from the JavaScript file that I want to execute.

### To Reproduce
1) Create a new Blazor WebAssembly project (this was tested with RC1)
2) Create a JavaScript file in the wwwroot and reference it from the index.html file.
3) Also reference jQuery in the index.html before the aforementioned js file (I have reproduced it with other libraries, like underscore.js):

```
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

```

4) In the Counter component, paste the following code:

```
protected async override Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        await js.InvokeVoidAsync("initializeCounterComponent");
    }
}
```

Where initializeCounterComponent is the name of the method in the JavaScript file.

5) Run the app (I use IIS Express)
6) Go to the Counter page
7) Press F12 to come chrome developers tool
8) Keep refreshing the page until the error happen

We ❤ code! Include a complete code listing or point us to a minimalistic GitHub repo.
Github repo: https://github.com/gavilanch/BlazorErrorConsole

Video: https://youtu.be/GIrN8RdjCrI

### Further technical details
- ASP.NET Core version: 3.2.0-rc1.20223.4
- Include the output of `dotnet --info`

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.300-preview-015135
>  Commit:    0b3c572e97
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015135\
> 
> Host (useful for support):
>   Version: 3.1.3
>   Commit:  4a9f85e9f8
> 
> .NET Core SDKs installed:
>   2.1.801 [C:\Program Files\dotnet\sdk]
>   2.2.401 [C:\Program Files\dotnet\sdk]
>   3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
>   3.1.102 [C:\Program Files\dotnet\sdk]
>   3.1.200 [C:\Program Files\dotnet\sdk]
>   3.1.201 [C:\Program Files\dotnet\sdk]
>   3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS 2019 Version 16.6.0 Preview 6.0

**Comment by gavilanch** [comment]
I added another library alongside jQuery, and the error occurs even more frequently (in my case, I added chartjs):

`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>`

Feels like it is some sort of race condition, so I did the following change in the index.html (I placed blazor last):

```
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
<script src="Utilities.js"></script>
<script src="_framework/blazor.webassembly.js"></script>
```

And that seems to fix the issue.

If the best practice is to have blazor.webassembly.js in the end of the list of scripts, I believe the documentation should say so.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Glad that you've found the solution to your problem. The scripts used by the components should be already available before Blazor starts up.
