### ISSUE TITLE
Blazor wasm project started from visual studio run clears browser local storage

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21642]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1014741/blazor-wasm-project-started-from-visual-studio-run.html)._

---
[regression] [worked-in:16.6.5]
When an app is started by running it from visual studio, the local storage values are cleared (test default new blazor project that does not access local storage in any way) - just as a test as I noticed my main program started to drop the local storage settings.

**If the blazor app is run directly from a google chrome browser, the local storage values are there.

If I then start app from IDE, no settings, and then start again from browser the settings are still there.

---
#### paul on 5/3/2020, 03:47 PM: 

<p>Any update on this ?</p><p>The local storage can be written to /read while the blazor wasm app is running. But if it is closed and started again from withing the vs ide, the local storage is all blank. All normal when the app is started with a chrome browser shortcut on the desktop. (i.e https://localhost:44370/)</p><p>Using chrome browser, vs updated to latest version/ all blazor packages to latest version.<br></p>

#### Visual Studio Feedback System on 5/4/2020, 00:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is going to be fixed in the VS 16.6 release. Closing this, as the issue has been fixed on the VS side.
