### ISSUE TITLE
Kestrel should automatically Advance HttpRequest.BodyReader if middleware doesn't

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#21645]
### Is your feature request related to a problem? Please describe.

If middleware reads from HttpRequest.BodyReader but doesn't advance (commonly because something threw between ReadAsync and when Advance would normally be called), an error will be logged and the underlying connection will be aborted:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLVJM2OF1559", Request id "0HLVJM2OF1559:00000002": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\Http1ContentLengthMessageBody.cs:line 129
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync() in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\Http1MessageBody.cs:line 47
```

### Describe the solution you'd like

If middleware reads from HttpRequest.BodyReader but doesn't advance, Kestrel should automatically advance HttpRequest.BodyReader in ConsumeAsync. We could still create a lower-level log (maybe Warning?) to indicated that the BodyReader wasn't properly advanced.

In order to make this work, Kestrel would need to start using a custom PipeReaders for all pipes including HTTP/2 and HTTP/1.1 chunked BodyReaders in order to track whether or not Advance was called.

### Additional context

Semi-related: https://github.com/dotnet/aspnetcore/issues/14727 (In that case it was Kestrel itself throwing without properly advancing the connection pipe though).

**Comment by Tratcher** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/17840?

**Comment by halter73** [comment]
Yep. I though I had already filed an issue. I was looking for an issue linked to #14727, but it was linked to #17723.
