### ISSUE TITLE
use EFCore in Blazor

### ISSUE THREAD

**Issue by pengqi1991** [dotnet/aspnetcore#21646]
context.Sports.FirstOrDefaultAsync();    will error  
but context.Sports.FirstOrDefault is true

**Comment by TomJD** [comment]
What is the error? 
I use `FirstOrDefaultAsync();` in my WASM project without troubles.

**Comment by javiercn** [comment]
@pengqi1991 thanks for contacting us.

Can you give us more information about your environment? is this issue related to server-side blazor or are you trying to use Entity Framework Core with Blazor webassembly?

**Comment by pengqi1991** [comment]
i make a mistake ,the entity may be null in the blazor page when oninitializedasync().the entity should be checked
