### ISSUE TITLE
[Blazor] IDisposable transient services are retained indefinitely

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#21652]
REPO: https://github.com/mrpmorris/BlazorBug-21652

Any object that implements IDisposable is held onto by the dependency container. This means that if a class implements IDisposable and is registered as Transient, it will remain in the Blazor app scope forever.

Create a service.
```
  public class MyDisposableTransientService : IDisposable
  {
    public readonly static ConcurrentBag<WeakReference<MyDisposableTransientService>> Instances
      = new ConcurrentBag<WeakReference<MyDisposableTransientService>>();

    public MyDisposableTransientService()
    {
      Instances.Add(new WeakReference<MyDisposableTransientService>(this));
    }

    void IDisposable.Dispose()
    {
    }
  }
```

Register it as a transient dependency.
```
public void ConfigureServices(IServiceCollection services)
{
  ...(omitted for brevity)...
  services.AddTransient<MyDisposableTransientService>();
}
```

Change Index.razor
```
<ul>
  @foreach(var item in MyDisposableTransientService.Instances.ToArray())
  {
    <li>
      Alive = @item.TryGetTarget(out MyDisposableTransientService _)
    </li>
  }
</ul>


@code
{
	protected override void OnInitialized()
	{
		GC.Collect(int.MaxValue, GCCollectionMode.Forced);
	}
}
```

1. Run the app
2. Navigate between Index and Counter repeatedly

The above code demonstrates that references are held until the user's session ends, causing a memory leak.

To prove the reproduction code is not responsible for holding on to the references, simply remove the IDisposable implementation and re-run.

**Comment by javiercn** [comment]
Related doc topic [here](https://github.com/dotnet/AspNetCore.Docs/issues/18786)
