### ISSUE TITLE
[Blazor] Initial value on two-way bound checkbox is not reflected in checkbox state

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#21653]
Change your Index.razor page like so

```
<input @bind-value=ShouldBeChecked type="checkbox"/> - ShouldBeChecked: @ShouldBeChecked

@code
{
	bool ShouldBeChecked = true;
}
```

Run the app.

Expected: The checkbox should be checked.
Actual: The checkbox appears unchecked.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please use `@bind-checked` instead.

**Comment by mrpmorris** [comment]
Ohhhhh, that'll need mentioning on blazor-university.com, thanks!

**Comment by mrpmorris** [comment]
Re-opening this for now so the follow-up question isn't forgotten about (by me).

@bind-checked doesn't compile. Surely it should, shouldn't it? If so, I will raise a ticket for that.

**Comment by mrpmorris** [comment]
@mkArtakMSFT I think your bot needs fixing.

**Comment by mkArtakMSFT** [comment]
`@bind-checked` indeed doesn't compile, but `@bind` works as expected.
@javiercn is this by-design?

**Comment by SteveSandersonMS** [comment]
I checked, and the `@bind-checked` attribute is not listed in the set of combinations supported in `BindAttributes.cs` (in the .Web project). I don't know why that one was not included - perhaps it was an oversight.

We could consider adding this. Though TBH there would be more value still in either supporting `@bind-value` on checkboxes, or adding some compiler warning/error if you try to do that.

**Comment by mrpmorris** [comment]
@SteveSandersonMS should `@bind-value` work?

**Comment by SteveSandersonMS** [comment]
No, HTML checkboxes have a `checked` state (not `value`) to indicate whether they are checked.
