### ISSUE TITLE
[Blazor WASM] Expose NotifyAuthenticationStateChanged on the AuthenticationStateProvider

### ISSUE THREAD

**Issue by Franklin89** [dotnet/aspnetcore#21669]
As described in the [Docs](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1#notification-about-authentication-state-changes) I have a user interface where I can change the role of the the user. I need to call `NotifyAuthenticationStateChanged` so that the components get informed, but just for this I do not want to implement a custom `AuthenticationStateProvider`. This seems to be a bit of an overhead and can result in security issues if I implement something that would be incorrect. Is there another way to force the event to be executed?

### Describe the solution you'd like
Either have a base class (maybe there is one then the docs should be updated) that I can inherit from and then register with the DI. Inheriting from `AuthenticationStateProvider` forces me to implement `GetAuthenticationStateAsync` which is not required for this case because in most cases the default implementation is ok. Or make the `NotifyAuthenticationStateChanged` available from injecting the default `AuthenticationStateProvider`.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by Franklin89** [comment]
Hi @mkArtakMSFT 
Any update on this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
