### ISSUE TITLE
[Blazor] Performing CRUD Operation Using Modal Bootstrap

### ISSUE THREAD

**Issue by imprathamesh** [dotnet/aspnetcore#21662]
Hello, 
Use Modal Boostrap to perform all CRUD Operation. The problem I am facing is 
when I click on save button for modal the data is inserted into database but the modal does not close and the data does not shown in html table. When I refresh the page then i see the inserted data.
I also use StatehasChanged() on insert/save button. But still its not working.

I need to close the modal manually and then need to refresh the page. 

Is there any solution on this issue in Blazor. My app is Blazor Server-Side

**Comment by javiercn** [comment]
Thanks for contacting us @imprathamesh.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.
