### ISSUE TITLE
[Blazor|Mvc] Make Microsoft.AspNetCore.Mvc.ViewFeatures.IComponentRenderer public

### ISSUE THREAD

**Issue by JvanderStad** [dotnet/aspnetcore#21666]
I have my own version of `ComponentTagHelper`

https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.TagHelpers/src/ComponentTagHelper.cs#L101

```c#
var componentRenderer = ViewContext.HttpContext.RequestServices.GetRequiredService<IComponentRenderer>();
var result = await componentRenderer.RenderComponentAsync(ViewContext, ComponentType, RenderMode, _parameters);
```

However `Microsoft.AspNetCore.Mvc.ViewFeatures.IComponentRenderer` is not marked as public.
To work around this, I use reflection. 

```c#
var type = Type.GetType("Microsoft.AspNetCore.Mvc.ViewFeatures.IComponentRenderer, Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60");
var componentRenderer = ViewContext.HttpContext.RequestServices.GetRequiredService(type);

var method = type.GetMethod("RenderComponentAsync");
Parameters[nameof(CascadingAuthenticationStateComponent.ComponentType)] = ComponentType.AssemblyQualifiedName;

var result = await (Task<IHtmlContent>)method.Invoke(componentRenderer, new object[] { ViewContext, typeof(CascadingAuthenticationStateComponent), RenderMode, Parameters });
```

please make `IComponentRenderer` public.

https://github.com/dotnet/aspnetcore/blob/602cb1dea59751a1297d674cddf7f0729c23e6ca/src/Mvc/Mvc.ViewFeatures/src/RazorComponents/IComponentRenderer.cs

**Comment by JvanderStad** [comment]
Technically it's in `area-mvc`, because it's a taghelper

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
