### ISSUE TITLE
Use function pointers in IISHttpServer

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#21672]
Convert these https://github.com/dotnet/aspnetcore/blob/aaaaf572fdf11088ee0efd205ff6834e16a36804/src/Servers/IIS/IIS/src/Core/IISHttpServer.cs#L25-L29 to use the new [function pointers feature in C#](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md)

cc @jkotas

**Comment by BrennanConroy** [comment]
Cool. Point to the feature please?

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspnetcore/issues/21512

**Comment by BrennanConroy** [comment]
Wrong link?
