### ISSUE TITLE
Can't blazor operate DOM directly?

### ISSUE THREAD

**Issue by andrew2558** [dotnet/aspnetcore#21678]
Is there a plan for this?

**Comment by danroth27** [comment]
Hi @andrew2558. Blazor is a UI component based framework where most of the DOM manipulation is handled for you. You author rendering logic in components, which then render to an in-memory representation of the DOM called a render tree. Blazor then keeps careful track of what actually needs to be updated in the DOM and handles those DOM updates very efficiently. You can also manipulate the DOM through JS interop, but that isn't the typical pattern and it can often interfere with Blazor's rendering algorithm.
