### ISSUE TITLE
Blazor background hosted services with PWA support

### ISSUE THREAD

**Issue by KuraiAndras** [dotnet/aspnetcore#21676]
It would be nice if blazor supported running IHostedServices or some other similar mechanism., which may persist when used in a PWA.

The example scenario would be some application which is prepared for offline mode, and wants do do work while the app is not in use. For example: pushing notifications on timers, cacheing online resources when connection is restored, etc.

Right now this can only be done in javascript, but it would be nice if this behavior could also be written in C#.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
