### ISSUE TITLE
Razor-Blazor - The type or namespace ComponentBase could not be found

### ISSUE THREAD

**Issue by KKacer** [dotnet/aspnetcore#21670]
"The type or namespace ComponentBase could not be found." (Razor file)
Earlier also reported similar bugs in previous releases,
In every version I remember bunch of similar issues,

Please check the video:
https://1drv.ms/v/s!AlScPmE9PLAKgScyqhahdXg4m1EY?e=9coSiJ

Some times I solve such issues with build, rebuild, quit, delete obj/bin, restart, etc, and some times some bugs keep bugging for a while. 
Some of these errors appears randomly, developers know how to tolerate and resolve them partially, but why?!

**why not resolving this and any similar issues forever?!**
(ASP.NET should know instantly about any namespace changes, imports, renamings, modules, directories, properties, instances, components and what else that matters and I think these will be the base of our programs.

Sorry that don't have time to recreate every error and report everything.
By the way, thanks to the Microsoft and Asp.net team for all the great works they have done.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
