### ISSUE TITLE
How can Nullable have such a runtime impact on asp.net core validation?

### ISSUE THREAD

**Issue by rui-ktei** [dotnet/aspnetcore#21680]
### Describe the bug
Similar problem here: https://github.com/dotnet/aspnetcore/issues/14451, but I'll describe the problem still.

### To Reproduce
Using .netcoreapp 3.1
```
dotnet new webapi -o MyApi
```
Create a DTO:
```
public class MyDto
{
    public string Something { get; set; }
}
```
Create a post entrypoint:
```
[HttpPost]
public string PostSomething(MyDto dto)
{
    return dto.Something;
}
```
Now POST a request to this entrypoint with empty JSON payload: `{}`. Now you get 400 back:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|752d6065-419d3ab9f0b42013.",
    "errors": {
        "Something": [
            "The Something field is required."
        ]
    }
}
```

I wonder how this decision has been made by asp.net team? It is declared in official documentation saying: "The compiler doesn't add any null checks or other runtime constructs in a nullable context. At runtime, a nullable reference and a non-nullable reference are equivalent." I might not be the best English reader in the world but I think this strongly suggests that enabling Nullable feature should NOT have runtime impact.

However, the truth says otherwise. I can see the logic you guys're using here: since Nullable is enabled, any previous strings that don't have a `?` means they should not be null, so we can make our users' life better to just add this automatic validation behavior in asp.net pipeline and, now, guaranteed you don't get null strings before your customers will get 400...

Well, it sounds nice but NO THANKS. I have legacy code and I want to use Nullable feature but I don't want it to have ANY runtime impact, ZERO. Second, this behavior is very silent and confusing in the beginning, I had no idea until I tested my code in runtime. Third, you have a validation framework already, I can just use [Required], so I don't need a second secret validation rule there.

This decision, just in my opinion, is a bit impractical. It makes perfect sense in developer's perspective, but failed to be a good real-world engineering decision. Whether you remove this "feature" or not is up to you and I won't stop using asp.net core framework just because of that, however this design is doubtful.

**Comment by pranavkm** [comment]
You can turn this feature off by configuring `SuppressImplicitRequiredAttributeForNonNullableReferenceTypes` in your Startup code:

```C#
services.AddControllers(options => options.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true);
```

See https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#required-attribute

**Comment by rui-ktei** [comment]
@pranavkm thanks for the help!
