### ISSUE TITLE
In Identity Invalid login attempt results in ExternalLogins.Count=0

### ISSUE THREAD

**Issue by H-Ashrafi** [dotnet/aspnetcore#21694]
### Describe the bug
In Identity Invalid login attempt results in ExternalLogins.Count=0
Even if you setup External login providers invalid login attempt with email will show the text that says 

> "There are no external authentication services configured. See <a href="https://go.microsoft.com/fwlink/?LinkID=532715">this article</a>
>                             for details on setting up this ASP.NET application to support logging in via external services." 

### To Reproduce

1. Create an ASP.Net core web app v3.1.
2. In visual studio right-click on project name and choose Add>New Scaffolded item>Identity.
3. check Override all files and create a new Data Context Class then click Add. This adds the latest nuget packages. At the time of writing this thread they are Identity.EntityFramworkCore v3.1.3, Identity.UI v3.1.3
4. Add an external login provider such as google.
5. Try to login with invalid Email and password.
6. Upon invalid login attempt the section for External login providers shows this text: There are no external authentication services configured...

### To Fix
Generate identity classes and pages through scaffolding. add line below to Login.cshtml.cs in OnPostAsync method.

```ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();```

**Comment by blowdart** [comment]
What version of identity and core are you targetting?

**Comment by H-Ashrafi** [comment]
> What version of identity and core are you targetting?

I updated my comment to show the versions and scaffolding. They are Identity.EntityFramworkCore v3.1.3, Identity.UI v3.1.3, ASP.Net core web app v3.1

**Comment by HaoK** [comment]
Scaffolding fix is here: https://github.com/dotnet/Scaffolding/pull/1337
