### ISSUE TITLE
[Blazor WebAssembly] Use different poco class between client and server

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#21692]
Hello guys, i actually develop a fresh blazor app in replacment on a Silverlight/Wcf app.

My goal is for now redevelop strictly the app, without main modification.

One stuff made by the original app was the ability to be completely separate, so the client( silverlight), have for example a dedicated class User with namespace MyNamespace, and the server (Wcf) have an another class User with the same namespace.

from the server, there is only one class User defined in server
from the client, there is only one class User defined in client

the transformation between the server User class and the client User class is performed automatically during the deserialization when the client receive the data.

I want to reproduce this behavior on my app. Have my server project sending server user class in the controllers and my clients project deserializing it in client user class.

I don't know how to do that, because the main problem is the server app depend of my client app (which is really strange by design). So the Server app will know two different user class, one on the server-side and one define in the client-side, and it will be definitively a problem.

So do you know how i can achieve this ? There is a way to totally separate client and server app ?

Or i need to redesign the app (it's a huge work, i reuse lot of code from the old app so i will have to rename everything) and for example use different class name or at least different namespace?

thanks for your help !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

You can try and use `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>` in the reference to your client project, but there will be some things you need to accomodate for in that case.

You'll have to make sure that your server project references directly all libraries with static web assets included in your app, and there might be other caveheats too.

**Comment by pranavkm** [comment]
You could also consider having different types on the server and the client. The type name doesn't appear on the wire.

**Comment by julienGrd** [comment]
@javiercn : im suprised but your solution work perfectly ! I can't use it for different reason but interesting to know !
@pranavkm : it can be a solution for sure ! but for now i can't really use this, because the code I reuse use the same class both in server and client side. I have to adapt on this situation
