### ISSUE TITLE
dotnet as service, empty journal entries

### ISSUE THREAD

**Issue by salorob** [dotnet/aspnetcore#21697]
Hi all,
Unsure where to ask, I'll continue asking here:

While running a dotnet core application as service like so:

```
[Unit]
Description=Modulio

[Service]
WorkingDirectory=/home/pi/modulio
ExecStart=/usr/local/bin/dotnet app/modulio.dll
Restart=always
RestartSec=10
TimeoutStopSec=10
SyslogIdentifier=modulio

[Install]
WantedBy=multi-user.target
```

I get allot of empty lines in systemstl status log (journal) with the dotnet identifier, like so:

```
pi@host:~ $ systemctl status modulio
● modulio.service - Modulio
Loaded: loaded (/lib/systemd/system/modulio.service; enabled; vendor preset:
Active: active (running) since Wed 2018-11-28 12:56:27 UTC; 1min 5s ago
Main PID: 7066 (dotnet)
CGroup: /system.slice/modulio.service
├─7066 /usr/local/bin/dotnet app/modulio.dll

Nov 28 12:57:25 host modulio[7066]: info: Modulio.Core.DataLogger[0]
Nov 28 12:57:25 host modulio[7066]:       Blablabla messages
Nov 28 12:57:26 host modulio[7066]: info: Modulio.Core.Engine[0]
Nov 28 12:57:26 host modulio[7066]:       Blablabla messages
Nov 28 12:57:26 host dotnet[7066]:
Nov 28 12:57:27 host modulio[7066]: info: Modulio.Core.Engine[0]
Nov 28 12:57:27 host modulio[7066]:       Blablabla messages
Nov 28 12:57:28 host dotnet[7066]:
Nov 28 12:57:30 host dotnet[7066]:
Nov 28 12:57:32 host dotnet[7066]:
```

The log is really flooded with empty lines like that, over 100mb worth in a few days.
does anyone know anything about this?

I'm not inserting empty lines to console anywhere, afaik.

Many thanks!

**Comment by Tratcher** [comment]
> May 11 10:04:01 sn393 dotnet[3361]: Error switching on NAT traversal: IP protection level cannot be controlled on this platform.

That doesn't seem aspnetcore related, but I did get an interesting hit on github:
https://github.com/gljohn/beacon-core/blob/9cd75d3e9cba9aade176b68d77c7409314141f07/src/Beacon.Lib/Beacon.cs#L50

Is this library or one like it in your dependency graph?  A Debug.WriteLine might explain the weird formatting.

**Comment by salorob** [comment]
That has to be it, many thanks!!
I'm using this library indeed. 

Is there an easy way (setting, environment variable) to make dotnet stop giving these Debug.WriteLine's? I will check. 

I could offcourse not add the AddConsoleLogging, that would probably fix it too. However, then I don't get my regular logging either...
