### ISSUE TITLE
Blazor WASM StandAlone Deploy with Azure DevOps

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#21691]
I have a project with a custom web.config ans a web.staging.config transform file.
Both are set to Content and copy always.

In my artifact I only get the base file.
No transform file at all.

I put /p:TransformWebConfigEnabled=false switch in my dotnet publish task, but there's still no transform file.

I don't undertand why, with ASP Net Core projects it works fine even without /p:TransformWebConfigEnabled=false

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Transformations aren't supported with Blazor WebAssembly apps. Moving this to the backlog to see how the rest of the community reacts to this ask.

**Comment by captainsafia** [comment]
@JulienM28 Do you have a repro project that you can share as a GH repo?

**Comment by JulienM28** [comment]
For now it's not a big problem to not have transformation, as we only use it to add http header to staging environment.
But I assume we will quickly want to add other headers or customize some stuff on IIS and it may won't be possible to do that at server level.

Thanks.

**Comment by pranavkm** [comment]
@JulienM28 we made some changes to the SDK in 5.0. If you continue seeing this after you update, please file an issue with a minimal app and we can investigate further.
