### ISSUE TITLE
Problem AND Solution: Default Example Blazor WebAssembly Solution fails to Load the FetchData page with error message "An unhandled error has occurred. Reload"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21698]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1024637/problem-and-solution-default-example-blazor-webass.html)._

---
**Problem:** Default Example Blazor WebAssembly Solution may (or may not) fail to Load on FetchData page with error message "An unhandled error has occurred. Reload"

Problem is easily recreatable and easily fixed.

When you create a brand new C# Blazor WebAssembly solution, the default example that is created contains one solution with three projects:

(Where [BlazorSolutionName] is the name you choose when creating the solution)

- Solution [BlazorSolutionName]
  - [BlazorSolutionName]. Client
  - [BlazorSolutionName]. Server
  - [BlazorSolutionName]. Shared

To Recreate Problem:
1. Install Visiual Studio Version 16.6.0 Preview 6.0 and Blazor WebAssembly 3.2.0 Preview 5
   - Instructions available at: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available/
2. Create a new Blazor App\Blazor WebAssembly App with "Configure for HTTPS" and "ASP.NET Core Hosted" both checked on.
3. Visual Studio will build an example solution by default.
   - Side note: Wish there was a radio button option when creating the solution to make an empty solution and projects.
4. Select Build\Rebuild Solution just to be sure entire solution builds successfully.
4. BEFORE running solution, single click on [BlazorSolutionName]. Client so it is bolded\highlighted.  Make sure it stays bold\highlighted.
5. Now run the solution.
6. You should see the sample solution load in the browser with "Home", "Counter", and "Fetch data" buttons on left side.
7. Click "Fetch data" and see that it doesn't load and gives error message at very bottom of page.
8. Close the browser to stop the application.
9. Now, single click on [BlazorSolutionName]. Server just so it is bolded\highlighted.
10. Now rerun the app and click on "Fetch data" and see that it runs successfully.

When you run the solution, it "might" fail on the FetchData page with an error message "An unhandled error has occurred. Reload" at times and then not at other times depending on which project you have bolded\highlighted.

**Reason Occurs:** 
This error occurs when the default project for the solution is anything but "[YourSolutionName]. Server".  You may see it some times and not other times depending on which project (client, server, or shared) you have highlighted when you run the solution.  This is because the example solution is installled with the default project set to "Current Selection".  The default project should be changed to:  "[YourSolutionName]. Server"

**Steps to Fix:** 
1. Right click on the Solution in Visual Studio
2. Select "Properties"
3. Change Radio Button selection "Current Selection" to "Single Startup Project"
4. Under "Single Startup Project" select [YourSolutionName]. Server
5. Click "Apply"
6. Click "OK"
7. Just to be sure, save all files and then rebuild project.
8. Now FetchData page should work at all times.
9. If still having problems reboot and re-try steps above.

Microsoft Visual Studio Community 2019 Preview
Version 16.6.0 Preview 6.0
Blazor WebAssembly 3.2.0 Preview 5
Microsoft .NET Framework - Version 4.8.03752

Hope this helps.

Todd Albers

---
#### Visual Studio Feedback System on 5/10/2020, 10:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### toddalbers solved on 5/10/2020, 08:34 AM, 0 votes: 

<p>Solution is provided in problem description above already.</p>

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/21699.
