### ISSUE TITLE
Identity UI's Logout.cshtml shouldn't pretend the user is logged out when accessed via GET

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/aspnetcore#21695]
When accessed via GET, the `Logout` page coming with the default Identity UI returns a message indicating that the user was successfully logged out, which is of course not true, as the user can only be logged out after a POST request with a valid antiforgery cookie/token (which is a good thing, as it prevents unsolicited logouts).

![image](https://user-images.githubusercontent.com/6998306/81572281-50a27d80-93a3-11ea-9743-7549036530f0.png)

Ideally, this - very misleading - message should be replaced by a confirmation form, offering the user the ability to properly and safely log out.

/cc @HaoK @blowdart

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
@blowdart Get to logout.cshtml is basically intended to be logout successful action, we can add logic to have it display a different message if the request is still authenticated I guess

**Comment by blowdart** [comment]
@kevinchalet was this just you typing the URL in, or did something link to it?

**Comment by kevinchalet** [comment]
I don't think the rest of Identity UI has a link to it.

In our case, we detected this surprising behavior when migrating an app using legacy authentication and good old <a href> links for the logout page.

When reaching that page via a link, it would make much more sense to have a confirmation form instead of a lying message pretending you're already logged out 😄

**Comment by kevinchalet** [comment]
BTW, the logout page also appears in the browser history, so you get the same message by navigating back to the previous page after logging out: if you re-log in after that, the message won't reflect your actual status.

**Comment by blowdart** [comment]
You made it lie sir, don't put this on us. In fact wasn't it you who reported it being a GET in the first place? :p

But yea, we can put a form in there if you're still authenticated, it's just a matter of prioritising.

**Comment by kevinchalet** [comment]
> You made it lie sir, don't put this on us.

Oh sure. I just blame you for not respecting the principle of least surprise :trollface: 

> In fact wasn't it you who reported it being a GET in the first place? :p

I don't think so, but logout on GET - without any form of confirmation - was definitely a bad thing (unless you run superlogout.com, of course).

Now, it's a bit different... we have same-site to protect us (even against our own will) :trollface:

**Comment by HaoK** [comment]
Self reminder not to close this issue until scaffolding is updated as well

**Comment by kevinchalet** [comment]
Thanks for fixing it! 👏
