### ISSUE TITLE
Find a way to prevent setting the Client project as `Startup` in the Blazor WASM hosted solution

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21699]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1024637/problem-and-solution-default-example-blazor-webass.html)._

---
**Problem:** Default Example Blazor WebAssembly Solution may (or may not) fail to Load on FetchData page with error message "An unhandled error has occurred. Reload"

Problem is easily recreatable and easily fixed.

When you create a brand new C# Blazor WebAssembly solution, the default example that is created contains one solution with three projects:

(Where [BlazorSolutionName] is the name you choose when creating the solution)

- Solution [BlazorSolutionName]
  - [BlazorSolutionName]. Client
  - [BlazorSolutionName]. Server
  - [BlazorSolutionName]. Shared

To Recreate Problem:
1. Install Visiual Studio Version 16.6.0 Preview 6.0 and Blazor WebAssembly 3.2.0 Preview 5
   - Instructions available at: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available/
2. Create a new Blazor App\Blazor WebAssembly App with "Configure for HTTPS" and "ASP.NET Core Hosted" both checked on.
3. Visual Studio will build an example solution by default.
   - Side note: Wish there was a radio button option when creating the solution to make an empty solution and projects.
4. Select Build\Rebuild Solution just to be sure entire solution builds successfully.
4. BEFORE running solution, single click on [BlazorSolutionName]. Client so it is bolded\highlighted.  Make sure it stays bold\highlighted.
5. Now run the solution.
6. You should see the sample solution load in the browser with "Home", "Counter", and "Fetch data" buttons on left side.
7. Click "Fetch data" and see that it doesn't load and gives error message at very bottom of page.
8. Close the browser to stop the application.
9. Now, single click on [BlazorSolutionName]. Server just so it is bolded\highlighted.
10. Now rerun the app and click on "Fetch data" and see that it runs successfully.

When you run the solution, it "might" fail on the FetchData page with an error message "An unhandled error has occurred. Reload" at times and then not at other times depending on which project you have bolded\highlighted.

**Reason Occurs:** 
This error occurs when the default project for the solution is anything but "[YourSolutionName]. Server".  You may see it some times and not other times depending on which project (client, server, or shared) you have highlighted when you run the solution.  This is because the example solution is installled with the default project set to "Current Selection".  The default project should be changed to:  "[YourSolutionName]. Server"

**Steps to Fix:** 
1. Right click on the Solution in Visual Studio
2. Select "Properties"
3. Change Radio Button selection "Current Selection" to "Single Startup Project"
4. Under "Single Startup Project" select [YourSolutionName]. Server
5. Click "Apply"
6. Click "OK"
7. Just to be sure, save all files and then rebuild project.
8. Now FetchData page should work at all times.
9. If still having problems reboot and re-try steps above.

Microsoft Visual Studio Community 2019 Preview
Version 16.6.0 Preview 6.0
Blazor WebAssembly 3.2.0 Preview 5
Microsoft .NET Framework - Version 4.8.03752

Hope this helps.

Todd Albers

---
#### Visual Studio Feedback System on 5/10/2020, 10:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### toddalbers solved on 5/10/2020, 08:34 AM, 0 votes: 

<p>Solution is provided in problem description above already.</p>

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by Andrew-Webb** [comment]
Preventing the `Client` project becoming the startup project would be a very nice-to-have in a Blazor WebAssembly ANC-hosted solution.  Because if the `Client` project does become the startup, it can lead to all sorts of weird problems.  In my case, it was a failure to find the appsettings*.json files.

I believe that if you delete your `.vs` folder and re-open the solution (or clone your solution's repo from GH and open in VS) then the `Client` project will become the startup project, so it can happen quite easily.

Yesterday I did delete my `.vs` folder (occasionally it's necessary when VS or ANC gets confused), and thereafter had weird problems with my app settings being null.  Today I realized what the problem was, and set the `Server` project to be the startup explicitly.

And I added the following defensive code to my Program.cs in the Server project, since my app settings weren't being loaded, and I _couldn't for the life of me_ figure out why (but now I know):-

```csharp
// Boilerplate.
private static IHostBuilder CreateHostBuilder(string[] args)
{
    return Host.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            // Ensure appsettings*.json files are non-optional (and not reloaded-on-change since the app will be in
            // a container).  By being non-optional, we'll fail fast with a nice error message if ASP.NET can't find the
            // files, instead of our app settings values being null while the app is running.  If the Client project gets
            // accidentally set as the 'Startup Project', this can lead to ASP.NET getting confused as to where to look for
            // the Server project's app settings files (i.e. it looks in the Client project's folder structure).
            JsonConfigurationSource jcs;
            foreach (var src in config.Sources)
            {
                jcs = src as JsonConfigurationSource;
                if (jcs != null)
                {
                    jcs.Optional = false;
                    jcs.ReloadOnChange = false;
                }
            }
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
}
```

**Comment by Bellarmine-Head** [comment]
I download Visual Studio 2022 Pro, on day of release.

I create a new Blazor WebAssembly app; .NET 6; ASP.NET hosted.

I innocently click on a file in the Client project, in the solution explorer.

I hit F5 to run... BANG!  it breaks.

This is not a good introduction to the world of Blazor WebAssembly for newcomers, who would likely have no clue as to what went wrong and how to fix it.

**Comment by Bellarmine-Head** [comment]
Does the project template system not have a way to say which (single) project in the solution is the startup?

If not, could not this be added?

But if it does, couldn't the Blazor WebAssembly project template(s) be updated to set the startup project correctly?  This surely wouldn't take very long and doesn't need to wait for .NET 7!

(But even fixing the project template wouldn't solve the problem of cloning your project anew from GitHub... even then you've got to remember to explicitly set the Client project to be the startup.  I get caught by this every so often.)

**Comment by joecss** [comment]
Still happening in 2023 with the stock sample Blazor server app on Visual Studio 2022 17.4.0.  I agree wholeheartedly this is a very poor experience for people trying to get started with Blazor.

**Comment by Bellarmine-Head** [comment]
Create a new Blazor app from the template, and eventually you are left with:-

* Solution startup project = Current selection
* the `Server` project just so happens to end up being currently selected

and so it works (so long as you hit F5 right away, and don't click elsewhere in the solution explorer).  But it's so brittle.  Sooner or later you will innocently run into this problem, and get very confused.  What can be wrong?  This worked two minutes ago!

But here we are nearly three years on, and Microsoft has made no response to this issue, nor any move to sort it out.  They just backlogged it.  I have noticed over the decades that they can develop these kind of blindspots.

```
I download Visual Studio 2022 Pro, on day of release.
I create a new Blazor WebAssembly app; .NET 6; ASP.NET hosted.
I innocently click on a file in the Client project, in the solution explorer.
I hit F5 to run... BANG! it breaks.
```

^^ ditto for day of release of .NET 7 in November 2022

@SteveSandersonMS - wouldn't it be nice to give users who are new to Blazor a less brittle, less error-prone experience?

**Comment by Bellarmine-Head** [comment]
Despite using Blazor WebAssembly from day one, this problem trips me up a lot.  I erase a repo from my hard disc, then sometime later fetch it from GitHub, and if I forget to explicitly set the startup project (which is often).... BANG!

**Comment by Bellarmine-Head** [comment]
The solution (no pun intended) is to move the startup project selection from the throwaway SUO fiile to the SLN file, which is where it should have been from the beginning.  These days, the choice of startup project is increasingly _not_ a user option or whim.

**Comment by mkArtakMSFT** [comment]
@sayedihashimi, @vijayrkn this seems more like a tooling ask, rather than a runtime issue. We don't have a good solution for how to fix this as the user intention can very well be to start client project on its own. Still, it's not something runtime can address so how would you like to proceed?
Maybe customers should file a VS feedback ticket for you to track ?

**Comment by Bellarmine-Head** [comment]
@mkArtakMSFT @sayedihashimi @vijayrkn 

> Maybe customers should file a VS feedback ticket

Customers already have, since February 2022 (with no feedback):-

https://developercommunity.visualstudio.com/t/Persist-startup-projects-in-solution-/1678968

**Comment by mkArtakMSFT** [comment]
Good, thanks @Bellarmine-Head. Closing this then.
