### ISSUE TITLE
Azure App Service memory dumps cannot be taken if more than 300-400 assemblies are loaded

### ISSUE THREAD

**Issue by aKzenT** [dotnet/aspnetcore#21703]
When deploying a .NET Core application as a azure app service with InProcess-Hosting activated and then taking a memory dump using Kudu (selecting w3wp process) always results in a memory dump file that is not readable by Visual Studio or most other tools.

Opening the memory dump in Visual Studio will not show any CLR Version and will not offer managed debugging. Clicking "Debug with Native Only" will say that that the memory file is corrupt. Opening the same file in WinDbg will display "Debugger could not find ntdll in module list, module list might be corrupt, error 0x80070057"

We are currently running .NET Core 3.1.1, but this issue was also present in previous versions. It doesn't matter if taking a mini-dump or full dump.

**Comment by BrennanConroy** [comment]
@mikem8361 do you remember if this was fixed or has a workaround? Both CLR and CoreCLR are loaded in the same process

**Comment by mikem8361** [comment]
I don't remember any problems with the minidump generation side of things. SOS needed a little work to deal with dumps with both CLR and .NET Core but that has been in the latest SOS for a while.

Can we get a sample dump with the problem?

**Comment by aKzenT** [comment]
I could share one privately if it helps.

**Comment by mikem8361** [comment]
What version of VS are you using to open the dump?

**Comment by aKzenT** [comment]
I'm using the latest 16.5.5, also tried with 16.5.1, but as I said I also have problems opening the dump with other tools.

I spent the last 2 days doing some experiments and can share the following findings:
I can successfully get a dump directly after the process starts. Only after a few requests or some time the process seems to get in a state where readable dumps are no longer possible. The bad mini-dumps are only about 551 kb in size, while the good dumps shortly after process start are about 8MB in size.

I then tried using procdump to get the dumps, which is able to successfully get a dump as well initially and then subsequently fails with a "Not enough storage" error code (notice the same process id in the two calls). There are however several gigabytes of space left on the drive, so this again seems to indicate to me some sort of process corruption going on.

> PS D:\home> d:\devtools\sysinternals\procdump -accepteula -mm 35064
> d:\devtools\sysinternals\procdump -accepteula -mm 35064
> 
> ProcDump v9.0 - Sysinternals process dump utility
> Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
> Sysinternals - www.sysinternals.com
> 
> [19:14:35] Dump 1 initiated: D:\home\w3wp.exe_200515_191435.dmp
> [19:14:47] Dump 1 complete: 8 MB written in 12.6 seconds
> [19:14:48] Dump count reached.
> 
> PS D:\home> d:\devtools\sysinternals\procdump -accepteula -mm 35064
> d:\devtools\sysinternals\procdump -accepteula -mm 35064
> 
> ProcDump v9.0 - Sysinternals process dump utility
> Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
> Sysinternals - www.sysinternals.com
> 
> [19:15:26] Dump 1 initiated: D:\home\w3wp.exe_200515_191526.dmp
> [19:15:26] Dump 1 error: Error writing dump file: 0x80070008
> Not enough storage is available to process this command. (0x80070008, -2147024888)
> 
> [19:15:27] Dump count reached.

As I said I can share the dumps if you want to take a look. Otherwise I would be grateful for any help to diagnose the root of this error.

**Comment by mikem8361** [comment]
It would be great if you could share a minidump with me privately.  I'm not sure the best way to do that.

**Comment by aKzenT** [comment]
Actually after digging some deeper these days, the error seems to be related to the total number of assemblies loaded. I can reproduce the error with a simple console application that loads 400 dummy assemblies (class library standard template). Somewhere between 300 and 400 assemblies, memory dumps can no longer be taken and the "Not enough storage" error appears.

While this seems like a lot, my "refs/" folder with only System&Microsoft assemblies has already 270 assemblies.

I don't need to run InProcess either. I can just start the application in Kudu console. I think it originally happended only InProcess since the worker process already comes with a lot of DLLs loaded, which pushes the process over this limit.

What I haven't figured out is why this happens only on Azure and not on my local development machine.

**Comment by mikem8361** [comment]
@gregg-miskelly and @chuckries have you ever heard of a bug like this? Loading minidumps in VS 16.5.5 with more than 300 modules?

**Comment by gregg-miskelly** [comment]
It sounds like a bug/limitation in the dbghelp.dll code that takes dumps (or the kernel APIs called by dbghelp.dll) rather than something in the consumer side.

@aKzenT when you said you can reproduce the problem with a simple console app, are you trying on your local machine? Or are you testing in Azure Web Sites?

**Comment by aKzenT** [comment]
@gregg-miskelly I can only reproduce this on azure app service, not locally. It doesn't need to run through IIS though, it's enough to start the console application from the console in Kudu.

**Comment by gregg-miskelly** [comment]
My **guess** is that you are running into a problem with the virtualization infrastructure in Azure App Services. I will follow up with the folks who own the dump writing and see if this problem is already known.

**Comment by gregg-miskelly** [comment]
@aKzenT Is your little console app test program something you can easily share? Could you share your corrupt dump as well?

**Comment by aKzenT** [comment]
Code including a "publish" directory with all libraries.
[ClassLibrary1.zip](https://github.com/dotnet/aspnetcore/files/4648998/ClassLibrary1.zip)

Memory dump:
[ConsoleApp1-e91576-05-19-07-54-50.zip](https://github.com/dotnet/aspnetcore/files/4649010/ConsoleApp1-e91576-05-19-07-54-50.zip)

**Comment by tatarincev** [comment]
We run into the same issue. All memory dumps are taken in Azure do not open. We tried in VisualStudio, dotMemory JetBrains, WinDbg preview, and PerfView.
WinDbg produced this error - `Debugger could not find ntdll in module list, module list might be corrupt, error 0x80070057.`
JetBrains - `Unable to import dump: The dump contains no CLR data`
Visual Studio did not show any CLR Version
PerfView - `HeapDump Error: Could not find a .NET Runtime in the process dump`

**Comment by safihamid** [comment]
Thanks for providing the repro code. We have verified the issue in App Service and have opened a work item from our side and are tracking a fix internally. Hopefully we can release a fix for this in the next few months.

**Comment by Shane32** [comment]
> We run into the same issue. All memory dumps are taken in Azure do not open. We tried in VisualStudio, dotMemory JetBrains, WinDbg preview, and PerfView.
> WinDbg produced this error - `Debugger could not find ntdll in module list, module list might be corrupt, error 0x80070057.`
> JetBrains - `Unable to import dump: The dump contains no CLR data`
> Visual Studio did not show any CLR Version
> PerfView - `HeapDump Error: Could not find a .NET Runtime in the process dump`

I have the same issue.

**Comment by safihamid** [comment]
The fix for this issue is in and will be deployed by next monthly release of Azure App Service. ETA is late September/Early October.

**Comment by ionmincu** [comment]
@safihamid any update on the Azure App Service issue?

**Comment by safihamid** [comment]
@ionmincu the fix is starting to roll out and should be finished within the next few weeks. If you go to the kudu(scm) site of your app and the 'Azure App Service' version (2nd line on homepage) starts with 90 or higher then you have the fix. If the number starts with 89 then the fix is not deployed to your region yet.

**Comment by MSEvanhi** [comment]
@aKzenT you filed a support request on Azure Managed Applications, please next time when filing a support ticket utilize the Azure Web Application option instead. If you would like to know more about Azure Managed Applications, you can view it on our documentation here: [Azure Managed Applications](https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/overview).

**Comment by safihamid** [comment]
FYI the fix is deployed everywhere now and this can be closed. Thanks
