### ISSUE TITLE
Survey: repo contribution experience

### ISSUE THREAD

**Issue by terrajobst** [dotnet/aspnetcore#21707]
We’ve been working as a team, and community, for five years in the dotnet org on the .NET Core project. Many of the same GitHub handles have remained constant over that time, some are new, and others have come and gone. Thanks to everyone that has contributed! We normally focus on how to improve the product, but we’re turning our focus to improving the open source project. We’ve created a survey to better understand your individual experience of participating and contributing in this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. If you don’t supply contact details, then responses will be anonymous.

[Survey](https://www.surveymonkey.com/r/ZLPVNX9?SourceRepo=dotnet%2Faspnetcore)

Thank you for your time!

### Discussion

For discussion, please go to https://github.com/dotnet/runtime/issues/36235.

**Comment by Pilchie** [comment]
This survey is now closed.
