### ISSUE TITLE
Add JWT Google OAuth to ASP.NET Core

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#21719]
I’m new to OAuth and I’d like to add Google authentication a Asp.Net Core project sample project I have. My goal is a customer request a protected endpoint, and I should redirect the user to authenticate. If authenticated successfully I should present some data. So far I was able to set up everything in the Developer Console. I just need some sample code on how to setup the middleware. If possible with JWT. Thanks beforehand.

This is how my `Startup.cs` looks like so far. I'm receiving a 401 when I run it.
``` C#
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

                })
                .AddJwtBearer()
                .AddGoogle(options =>
                {
                    var googleAuthNSection = Configuration.GetSection("Authentication:Google");

                    options.ClientId = googleAuthNSection["ClientId"];
                    options.ClientSecret = googleAuthNSection["ClientSecret"];
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthentication();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

![image](https://user-images.githubusercontent.com/12285372/81626272-32e80f00-93c9-11ea-8275-54b0c5766de2.png)

**Comment by yopez83** [comment]
@Tratcher, I have modified the `ConfigureServices` method to this,
``` C#
            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultAuthenticateScheme = GoogleDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = GoogleDefaults.AuthenticationScheme;
                })
                .AddJwtBearer();

            services.AddAuthentication()
                .AddGoogle(options =>
                {
                    var googleAuthNSection = Configuration.GetSection("Authentication:Google");

                    options.ClientId = googleAuthNSection["ClientId"];
                    options.ClientSecret = googleAuthNSection["ClientSecret"];
                    options.AccessType = "offline";
                });
```
As per the URL in the screenshot, I see Google is redirecting the request as intended, but I'm having another exception.
![image](https://user-images.githubusercontent.com/12285372/81741630-dd653e00-946c-11ea-8ea2-42694baac6d6.png)

**Comment by Tratcher** [comment]
AddGoogle only works with Cookies, not JwtBearer.

Are you trying to protect a page or a Web API? For a Web API you should be using only JwtBearer and handle the Jwt acquisition on the client side using a Google's SDK.

**Comment by yopez83** [comment]
Just protecting a Web API for now. Do you have any sample on how do I setup the JwtBearer options to get tokens from Google?

**Comment by Tratcher** [comment]
We don't have any first party samples for Google Jwt. Stackoverflow has several through.
https://stackoverflow.com/questions/48727900/google-jwt-authentication-with-aspnet-core-2-0

**Comment by yopez83** [comment]
Ok. I've copied the sample provided by Mikey and still get a 401, back to the beginning.

**Comment by yopez83** [comment]
@Tratcher I’ve tried many different approaches and so far I always get a 401. Btw, I read in SO the Google library is meant for browser interactive apps. Therefore, it is safe to say it isn’t the go to approach for authorization code flow, right? My ultimate goal is to have a Blazor WebAssembly (standalone) app, which calls a protected API endpoint (the Web API I’m working on now). Then the API delegates the authentication to Google. Makes sense?

**Comment by blowdart** [comment]
That approach is, well, somewhat complicated. You're asking for delegated or on-behalf of flows, and I don't know if google will support that in their login OIDC flows.

**Comment by brockallen** [comment]
Also, google's token server will never want to protect your APIs. Their token server is only meant for their APIs. You need your own token server to protect your APIs.
