### ISSUE TITLE
HTTP Error 500.0 - ANCM In-Process Handler Load Failure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21718]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/989551/http-error-5000-ancm-in-process-handler-load-failu-1.html)._

---
Hi,
I am getting this error after upgrading my solution to dotnet core 3.x. The solution was origialy created on dotent core 1.1 and after it was upgraded to dotner core 2.2 it worked fine. Then I tried update to dotnet core 3.x I am getting HTTP 500.0 error. In the event log I found an error "Unable to find hostfxr directory at C:\MY-SOLUTION-PATH\host\fxr". If I switch hosting model to Out of process it will start working.

Here is the same issue:
https://stackoverflow.com/questions/60820232/unable-to-find-hostfxr-directory-after-upgrade-net-core-3-x

---
#### Visual Studio Feedback System on 4/14/2020, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by BrennanConroy** [comment]
Can you share your web.config and how you're deploying the app?
And could you provide diagnostic logs https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#enhanced-diagnostic-logs

**Comment by janbernardcz** [comment]
It is happening in development environment. I want to run the application in Visual Studio for example in debug mode. I only run IIS Express from Visual Studio.

Here is the `web.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <httpProtocol>
      <customHeaders>
        <add name="X-Frame-Options" value="DENY" />
      </customHeaders>
    </httpProtocol>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Local" />
        <environmentVariable name="COMPLUS_ForceENC" value="1" />
      </environmentVariables>
    </aspNetCore>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="524288000" maxQueryString="32768" maxUrl="65536" />
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```
And here is the diagnostic log (I've replaced real path by C:\PathToMyProject and I also replaced name of the project for security reasons):
```
[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS Express\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 306964.. File Version: 13.0.19213.0. Description: IIS ASP.NET Core Module V2. Commit: 48840f13fad0609429034b95a3342e2a8c07fbf8.
[aspnetcorev2.dll] Resolving hostfxr parameters for application: 'C:\PathToMyProject\bin\Debug\netcoreapp3.1\myApp.App.exe' arguments: '%LAUNCHER_ARGS%' path: 'C:\PathToMyProject\'
[aspnetcorev2.dll] Known dotnet.exe location: ''
[aspnetcorev2.dll] Process path 'C:\PathToMyProject\bin\Debug\netcoreapp3.1\myApp.App.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2.dll] Checking application.dll at 'C:\PathToMyProject\bin\Debug\netcoreapp3.1\myApp.App.dll'
[aspnetcorev2.dll] Checking hostfxr.dll at 'C:\PathToMyProject\bin\Debug\netcoreapp3.1\hostfxr.dll'
[aspnetcorev2.dll] hostfxr.dll found app local at 'C:\PathToMyProject\bin\Debug\netcoreapp3.1\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'dotnet'
[aspnetcorev2.dll] Found dotnet.exe at 'C:\PathToMyProject\dotnet'
[aspnetcorev2.dll] Resolving absolute path to hostfxr.dll from 'C:\PathToMyProject\dotnet'
[aspnetcorev2.dll] Event Log: 'Application 'C:\PathToMyProject\' failed to start. Exception message:
Unable to find hostfxr directory at C:\PathToMyProject\host\fxr' 
End Event Log Message.
[aspnetcorev2.dll] InvalidOperationException 'Unable to find hostfxr directory at C:\PathToMyProject\host\fxr' caught at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\CommonLib\HostFxrResolutionResult.cpp:64 
[aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\HandlerResolver.cpp:68 
[aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\HandlerResolver.cpp:171 
[aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\applicationinfo.cpp:181 
[aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\applicationinfo.cpp:96 
[aspnetcorev2.dll] Event Log: 'Failed to start application '/LM/W3SVC/2/ROOT', ErrorCode '0x8007023e'.' 
End Event Log Message.
```

**Comment by PepeMtzCampos** [comment]
Hello,

I have the exact same problem. The only way to make it work besides switching hosting model to Out of process was to copy the 'host' folder and its contents from 'C:\Program Files\dotnet\' to the root folder of my project.

**Comment by LukeStephen** [comment]
I have the same exact problem. I can get the app to run using Visual Studio Code doing "dotnet run", but I can't get it to run using Visual Studio 2019.

**Comment by negi2u** [comment]
I am also having the same issue... :-| I was able to run my project for 3-weeks and now stuck with this issue for past 1 week. VS 2019 complains that my build has some error but there are no errors in any of the c# files.

**Comment by LukeStephen** [comment]
In project settings in VS 2019 I had to run it out of process and as 64bit then it worked

**Comment by shirhatti** [comment]
@janbernardcz Can you please share your `runtimeconfig.json` from your published output?

**Comment by jkotalik** [comment]
Also, if someone could share a runnable repro for us to investigate, that will also help our investigation.

**Comment by jkotalik** [comment]
@janbernardcz sorry for the delay. Where do you currently have dotnet installed on your machine? Also, random question, does your app name happen to end in `dotnet`? We had an issue that has been resolved with that.
