### ISSUE TITLE
form Tag Helpers causes 405

### ISSUE THREAD

**Issue by tango-charly** [dotnet/aspnetcore#21712]
Hi,
An issue occurs with html tag helper but not with razor c# helper.
It could be a misconfiguration, but i think the two ways have the same behavior.

### Describe the bug
When a web form is submitted with [Html Tag Hepler](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-3.1) 405 is thrown

Dummy/Sample/Index.cshtml
``` html
<!-- Works -->
@using (Html.BeginForm("Create", "Sample", new { area = "Dummy" }, FormMethod.Post))
{
  <input asp-for="Email" name="Email">
  <button type="submit">Soumettre</button>
}
<!-- 405 Method not allowed -->
<form asp-area="Dummy" asp-controller="Sample" asp-action="Create" method="Post">
  <input asp-for="Email" name="Email">
  <button type="submit">Soumettre</button>
</form>
```

### To Reproduce

SampleController.cs in Dummy Area
``` C#
    [Area("Dummy")]
    [Authorize]
    public class SampleController : Microsoft.AspNetCore.Mvc.Controller
    {
        [HttpGet]
        public IActionResult Index(Model model)
        {
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Model model)
        {
            return RedirectToAction("Index", "Sample", new { area = "Dummy", model  = model });
        }
    }
```
Model.cs
``` C#
public class Model {
  public string Email { get; set; }
}
```
Dummy/Sample/Index.cshtml
``` html
<!-- Works -->
@using (Html.BeginForm("Create", "Sample", new { area = "Dummy" }, FormMethod.Post))
{
  <input asp-for="Email" name="Email">
  <button type="submit">Soumettre</button>
}
<!-- 405 Method not allowed -->
<form asp-area="Dummy" asp-controller="Sample" asp-action="Create" method="Post">
  <input asp-for="Email" name="Email">
   <button type="submit">Soumettre</button>
</form>
```

_ViewImports.cshtml
``` html
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
``` 

If [HttpPost] Create is changed by [HttpPost] Index both works.

### Further technical details
- ASP.NET Core version 3.1
- Windows
 RID:         win10-x64

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.101 
  3.1.102 

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15
  Microsoft.AspNetCore.App 2.1.15 
  Microsoft.AspNetCore.App 3.1.1
  Microsoft.AspNetCore.App 3.1.2 [
  Microsoft.NETCore.App 2.1.15
  Microsoft.NETCore.App 3.1.1 
  Microsoft.NETCore.App 3.1.2 
  Microsoft.NETCore.App 3.1.3
  Microsoft.WindowsDesktop.App 3.1.1 
  Microsoft.WindowsDesktop.App 3.1.2
- Visual Studio 2019 Enterprise

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@NTaylorMullen can you please have a look at this? Thanks!

**Comment by NTaylorMullen** [comment]
@tango-charly would you mind providing a repro app for this? I've tried putting together the pieces you mentioned but I can't reproduce what you are seeing.

**Comment by tango-charly** [comment]
@NTaylorMullen ok i'm going to do a repo; I'm busy these days so it could take few days before i could do it.
