### ISSUE TITLE
Authentication in a server side Blazor project with the cookie authentication

### ISSUE THREAD

**Issue by mselinger75** [dotnet/aspnetcore#21726]
My problem is that when the cookie expires and then the user clicks a button a any of our blazor component, the authentition state provider still says that the user IsAuthenticated. My goal is to redirect the user to the login page.

Please could you provide me some guidance to detect and auto redirect the user to the login page when the cookie auth expires,

**Comment by javiercn** [comment]
@mselinger75 thanks for contacting us.

You can do this with a RevalidatingAuthenticationStateProvider I believe, by checking the security timestamp using the user manager.

Otherwise, you might be able to check the authentication properties during sign-in and flow those into the principal used by Blazor. At that point, you can check the expiration in your own AuthenticationStateProvider, return an unauthenticated user and then redirect to the login page when a user is not authorized.

**Comment by mselinger75** [comment]
Hey, i am sorry bothering again, but i can't find this anywhere in Blazor docs. 
i have create a default Blazor server side project with authentication support in VS2019.

this project uses RevalidatingServerAuthenticationStateProvider.
After i login i see application saved an auth cookie like with a name .AspNetCore.Identity.Application.
Can you please point me the code which checks this cookie presence in Blazor?

Then i added @attribute [Authorize] to both Home and Counter page.
When i refresh i see of course Not authorized until i login.

But the problem is, if I login, but then manually delete cookie in browser dev tools, i can still go to both Home and Counter page without any problem. 
So it looks like some piece of code checks auth cookie only during the first page load. 

Can you please point me out to a right direction - how can i implement cookie presence while switching between pages? 
RevalidatingServerAuthenticationStateProvider seems also not being called while switching Blazor pages.

Thanks!

**Comment by javiercn** [comment]
@mselinger75 that is correct.

Server-side Blazor uses websockets so there is no cookie involved after the initial request that sets up the application.

AFAIK our default authenticationstateprovider only grabs the contents of the authenticated principal when the circuit is started and uses as the result to getauthenticationstate.

You could implement your own ClaimsPrincipalFactory to add a claim with the expiration date of the cookie to the list of user claims, and then in your custom authenticationstateprovider compare the claim with the date with the current time to determine if the user is no longer authorized.

There is no way to check the cookie in Blazor apps as they use websockets and at that point there is no longer a request available.

**Comment by mselinger75** [comment]
@javiercn , Thank you! 
Do you maybe know a recommended way for Blazor to implement an analogue of cookies sliding expiration in ASP.NET Core? So like auto logout in case of e.g. 10 minutes inactivity? Otherwise extend "cookies" time for more 10 minutes?

**Comment by mselinger75** [comment]
@javiercn , 

>>>
You could implement your own ClaimsPrincipalFactory to add a claim with the expiration date of the cookie to the list of user claims, and then in your custom authenticationstateprovider compare the claim with the date with the current time to determine if the user is no longer authorized.
<<<

the problem with this is as I mentioned - if I go back and force between Home and Counter pages my custom authenticationstateprovider is not being triggered at all. It runs only at initial page load.
