### ISSUE TITLE
[blazor] Turn Off/On gzip and brotli compressing of published files 

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#21728]
Hello,

 Now when I publish blazor webassembly app it is generating uncompressed, gzip compressed and brotli compressed files.

 Can it be configured somehow which one developer wants to get?

 I personally want only uncompressed files because I do compression and azure static website deploy using my own [utility](https://github.com/Lupusa87/BlazorAzureDeploy), so I do not want to wait before VS will compress gzip and brotli lot of files and then I should care to remove them from published folder.

 Any option to turn generating compressed files off?

Thank you.

**Comment by javiercn** [comment]
@Lupusa87 there's an MSBuild flag to turn off compression. You can set BlazorEnableCompression to false to turn it off

**Comment by Lupusa87** [comment]
Thank you @javiercn 

It should be documented somewhere, is it?

For questions like this we do dot have to disturb you.

@danroth27 another blazor doc improvement idea.

**Comment by guardrex** [comment]
@Lupusa87 I just put the update in on https://github.com/dotnet/AspNetCore.Docs/pull/18555.

**Comment by Lupusa87** [comment]
@guardrex Thank you.

**Comment by jhancock4d** [comment]
This really needs to be a flag that we can pass to the dotnet publish command.

**Comment by javiercn** [comment]
@jhancock4d You can pass this as a flag with `-p:BlazorEnableCompression=false`

**Comment by jhancock4d** [comment]
@javiercn That's great! Is there a way to put this in a pubxml?

Both should be in the documentation btw.

**Comment by javiercn** [comment]
> @javiercn That's great! Is there a way to put this in a pubxml?

It's not a code API it's MSBuild, so there is no way other than our docs.

**Comment by guardrex** [comment]
The first approach already is. See the end of ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#compression

**Comment by jhancock4d** [comment]
To answer my own question yes you can add this to your PropertyGroup in the pubxml

<BlazorEnableCompression>false</BlazorEnableCompression>

Then you can have profiles configured for publishing that do this correctly. (super useful when using capacitor)
