### ISSUE TITLE
Blazor WebAssembly 3.2.0 Release Candidate

### ISSUE THREAD

**Issue by masoodafar-web** [dotnet/aspnetcore#21725]
i using Blazor WebAssembly 3.2.0 Release Candidate
What is this error?
**index.html???**
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://4sat.4100sat.com/index.html' with computed SHA-256 integrity 'F0cOY0YuSHsALIyroBPSwqnJ+cy4LiXDEPOw9NCG39w='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
```
or in local:**favicon.ico???**
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost:44318/favicon.ico' with computed SHA-256 integrity 'rolXg6EPar/b0V/M8X458MHZ5USegq5+r8aD5outkxM='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by javiercn** [comment]
@masoodafar-web thanks for contacting us.

Seems like for some reason the integrity in some of your assets is not correct. We generate hashes for all the assets and use those hashes when we request them to boot your app.

Is your deployment git based?

**Comment by masoodafar-web** [comment]
NO, my app published on folder and deploy on iis.
But before deploy I see this error ,too : in localhost????

**Comment by javiercn** [comment]
@masoodafar-web can you try and produce a minimal repro project that we can use for investigating this issue?

**Comment by masoodafar-web** [comment]
> @masoodafar-web can you try and produce a minimal repro project that we can use for investigating this issue?

yes ,please give me your email for add you to tfs?

**Comment by javiercn** [comment]
@masoodafar-web Unfortunately, we are not allowed to just look at proprietary code.

You'll have to setup a separate project somewhere public we can access, like a public github repo or uploading a zip file to this issue.

I would recommend you start a new project from scratch and add the minimal amount of code/files to reproduce thee issue.

**Comment by masoodafar-web** [comment]
i use asp core hosting 
can i create repo from client only?
Otherwise it will take a long time

**Comment by pranavkm** [comment]
> can i create repo from client only?

As long as it reproduces the issue, sure.

**Comment by stsrki** [comment]
@masoodafar-web I had the same problem a while ago. I think there was a problem with one of the nuget packages that was corrupted. Try cleaning the solution and then clear the local nuget cache by running the `dotnet nuget locals all -c`

**Comment by masoodafar-web** [comment]
@javiercn 
this is my project
https://github.com/masoodafar-web/4satBlazorCopy.git

**Comment by OrihuelaConde** [comment]
Same issue here #21383

**Comment by mkArtakMSFT** [comment]
After seeing multiple of these issues we now know that it's usually caused by an misconfiguration in the customer code. We will build this FAQ to help diagnose similar problem going forward: #22470
