### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation - net core 3.1.3 not working

### ISSUE THREAD

**Issue by alvinsy99** [dotnet/aspnetcore#21737]
Hi, Im new to .NET Core and I was tried to install the NuGet package in the following instruction but it didn't work as expected: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0&tabs=visual-studio#runtime-compilation

I have add the configuration line:

public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages().AddRazorRuntimeCompilation();
        }

But it still doesn't update the web page when changes are being saved.
I am using .NET Core 3.1.3 with Visual Studio 2019 on Mac

Please help
Thank you

**Comment by pranavkm** [comment]
Hi @alvinsy99, would you mind sharing a screen grab of your workflow? Are you refreshing the browser after making changes to the cshtml file and saving it?

**Comment by alvinsy99** [comment]
Hi @pranavkm,
Thanks for the response, I haven't created any file in the project because I'm learning .NET core through a online course so it is only a empty project. What I have done is adding the "services.AddRazorPages().AddRazorRuntimeCompilation();" in the Startup.css and try to change the "Hello World!" text into a different one. And I'm pretty sure that I have saved the Startup.css file plus reloading the web page.

<img width="1440" alt="Screen Shot 2020-05-12 at 11 51 57 pm" src="https://user-images.githubusercontent.com/47974833/81700485-0b1da780-94ac-11ea-81f7-5f13252bd588.png">

**Comment by pranavkm** [comment]
@alvinsy99 runtime compilation specifically works for changes to cshtml files. If you're looking for a way to rebuild your project on changes to C# files, consider using `dotnet watch` - https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1#run-net-core-cli-commands-using-dotnet-watch

**Comment by alvinsy99** [comment]
That explains a lot. 
Thank you very much @pranavkm
