### ISSUE TITLE
Blazor server side - Get Circuit specific data from static code

### ISSUE THREAD

**Issue by Crimp** [dotnet/aspnetcore#21738]
Our issue is related with [IHttpContextAccessor cannot be used reliably in some scenarios](https://github.com/dotnet/aspnetcore/issues/14975)
And we try to find out some appropriated solution for our needs. 

We have a legacy code from Asp.Net framework where we use HttpContext.Current to have access to some global data storage. Like this:
```C#
        private static Dictionary<string, object> GetSessionStoreExample() {
            HttpContext context = HttpContext.Current;
            if(context != null) {
                return GetSessionStoreExample(context);
            }
            return null;
        }
```

 This store can contain some global environment data in a context of the session and every session has separated store. Removing this approach and use DI won't be easy and even won't possible in some cases.

In the first iteration we have a look at IHttpContextAccessor for the same purpose - to make a wrapper around HttpContext and store a link on our storage. Like this:
```C#
        private static IHttpContextAccessor httpContextAccessor;
        private static Dictionary<string, object> GetSessionStoreExample() {
            HttpContext context = httpContextAccessor.HttpContext;
            if(context != null) {
                return GetSessionStoreExample(context);
            }
            return null;
        }
```

 But it turned out unreliable and in some cases not working. For example, in case of reconnection. 
After reconnection the CircuitHost is alive, has the same scope and renderer. Our application instance still available and feels good :) (It was created in scope service).  Except we have lost our global storage with HttpContext. Or in some cases HttpContext can be destroyed before all 'await' operations are finished. 

We are trying to write our own AsyncLocal store for our purposes to have more control on it life-cycle. I made an example and it works good but I'm not sure it's a right way.
To create store inside current logical call context I added a middleware:
```C#
    internal class ValueManagerStorageCreatorMiddleware {
        private readonly RequestDelegate next;
        public ValueManagerStorageCreatorMiddleware(RequestDelegate next) {
            this.next = next;
        }

        public async Task Invoke(HttpContext context, IValueManagerStorageAccessor storageAccessor) {
            IValueManagerStorage storage = new ValueManagerStorage();
            storageAccessor.Storage = storage;
            await next(context);
            storageAccessor.Storage = null;
        }
    }
```

And storage global accessor:
```C#
    internal sealed class ValueManagerStorageAccessor : IValueManagerStorageAccessor {
        public IValueManagerStorage Storage {
            get {
                return _storageCurrent.Value?.Storage;
            }
            set {
                StorageHolder storageHolder = _storageCurrent.Value;
                if(storageHolder != null) {
                    storageHolder.Storage = null;
                }
                if(value != null) {
                    if(storageHolder == null) {
                        _storageCurrent.Value = new StorageHolder { Storage = value };
                    }
                    else {
                        storageHolder.Storage = value;
                    }
                }
            }
        }

        private static AsyncLocal<StorageHolder> _storageCurrent = new AsyncLocal<StorageHolder>();
        private class StorageHolder {
            public IValueManagerStorage Storage;
        }
    }
```

But it works only during a connection, after reconnect we will have a new logical call context. To avoid this problem and reuse store from other call context I added the CircuitHandler which is registered as a **scope service**:
```C#
    internal class ValueManagerStorageSynchronizer : CircuitHandler {
        private readonly IValueManagerStorageAccessor storageAccessor;
        private IValueManagerStorage storage;
        public ValueManagerStorageSynchronizer(IValueManagerStorageAccessor storageAccessor) {
            this.storageAccessor = storageAccessor;
        }
        public override Task OnCircuitClosedAsync(Circuit circuit, CancellationToken cancellationToken) {
            storage = null;
            return base.OnCircuitClosedAsync(circuit, cancellationToken);
        }
        public override Task OnConnectionUpAsync(Circuit circuit, CancellationToken cancellationToken) {
            if(storage != null) {
                storageAccessor.Storage = storage;
            }
            else {
                storage = storageAccessor.Storage;
            }
            return Task.CompletedTask;
        }
    }
```

When OnConnectionUpAsync is occurred we store a link on the the storage and reassign it next time. It's why inside the ValueManagerStorageAccessor I use the same instance of the StorageHolder object.

Is it a right way or we missed something?

**Comment by javiercn** [comment]
@Crimp thanks for contacting us.

We recommend you pass in a parameter to the root component to use as a key for each circuit you start. See https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/threat-mitigation?view=aspnetcore-3.1#blazor-and-shared-state

**Comment by Crimp** [comment]
It would be nice if I can use just DI or parameters. A scoped service will be the best solution for it.  But most of our cross-platform modules are not aware of DI. Our legacy code pretty huge. Even in some cases DI isn't possible I think. For example: global access can be used from ORM to implement some logic inside a business object instance. 
For example, in this case the value can be stored and will be available for a customer during the session:
```C#
        public string Name {
            get {
                IValueManager<string> valueManager = ValueManager.GetValueManager<string>("myKey");
                if(valueManager.CanManageValue)
                    return valueManager.Value;
                else return "Some default value";
            }
            set {
                IValueManager<string> valueManager = ValueManager.GetValueManager<string>("myKey");
                if(valueManager.CanManageValue)
                    valueManager.Value = value;
            }
        }
```
  The ValueManager.GetValueManage function is static.

From DI point of it looks like scoped service without DI. 

The more important part that there are a lot of such code on the side of our customers. And it will be big breaking change. We understand that such way is out dated but everything has a price. it's why we want to evaluate all possible solutions.

**Comment by Crimp** [comment]
Sorry but also the the initial example is a bit simplified. I don't clear the link to the store here
```C#
    internal class ValueManagerStorageCreatorMiddleware {
        private readonly RequestDelegate next;
        public ValueManagerStorageCreatorMiddleware(RequestDelegate next) {
            this.next = next;
        }

        public async Task Invoke(HttpContext context, IValueManagerStorageAccessor storageAccessor) {
            IValueManagerStorage storage = new ValueManagerStorage();
            storageAccessor.Storage = storage;
            await next(context);
//no clear here
            //storageAccessor.Storage = null;
        }
    }
```
Because the store still can be used. The link will be cleaned inside the CircuitHost.DisposeAsync flow.
