### ISSUE TITLE
[Https] Issue when getting private key after being exported

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#21733]
When running the `dotnet-dev-certs` tool with the `--trust and --export-path --password` options simultaneously, we try to access the private key after the certificate has been exported.

This causes an underlying issue in .NET Core that causes the key to become unusable in future operations, which in turn causes a failure the next time we try to check for a valid certificate so we decide to generate a new one.

Repeating the problem over and over.

The fix will ultimately come from fixing the logic in .NET Core, but in the mean time, we can change our usage in the tool to avoid running into this specific issue.

**Comment by Pilchie** [comment]
:eyes:

**Comment by mkArtakMSFT** [comment]
@javiercn I assume we can close this now, given https://github.com/dotnet/runtime/pull/36312

**Comment by javiercn** [comment]
Yep
