### ISSUE TITLE
[SignalR] Get claims from signalr hub negotiate

### ISSUE THREAD

**Issue by tytannial** [dotnet/aspnetcore#21732]
With "accessTokenFactory" the Authorization Header has been written, but there is no claims.
![20200512150008](https://user-images.githubusercontent.com/11215623/81648600-8e65db80-9461-11ea-97a7-87ec65e37807.png)
![20200512150322](https://user-images.githubusercontent.com/11215623/81648894-046a4280-9462-11ea-8ddf-86c475110616.png)
![20200512150347](https://user-images.githubusercontent.com/11215623/81648939-164be580-9462-11ea-8789-71b8e0a2b6c3.png)

And I move "AuthorizeAttribute" from Hub to Hub's Action, Claims are worked.

- ASP.NET Core version 3.1

**Comment by BrennanConroy** [comment]
> And I move "AuthorizeAttribute" from Hub to Hub's Action, Claims are worked.

Could you be more specific here? Where are you observing no claims?
If you move the attrbitue from
```c#
[Authorize]
public class MyHub : Hub
{
}
```
to
```c#
public class MyHub : Hub
{
    [Authorize]
    Task Method()
    {
    }
}
```
then you're seeing claims?

**Comment by tytannial** [comment]
> > And I move "AuthorizeAttribute" from Hub to Hub's Action, Claims are worked.
> 
> Could you be more specific here? Where are you observing no claims?
> If you move the attrbitue from
> 
> ```cs
> [Authorize]
> public class MyHub : Hub
> {
> }
> ```
> 
> to
> 
> ```cs
> public class MyHub : Hub
> {
>     [Authorize]
>     Task Method()
>     {
>     }
> }
> ```
> 
> then you're seeing claims?

YES, but claims from "/DashBoardHub/negotiate?negotiateVersion=1" can not be get.

`
        var connection = new signalR.HubConnectionBuilder()
            .withUrl("/DashBoardHub", {
                accessTokenFactory: () => token
            })
            .withAutomaticReconnect()
            .configureLogging(signalR.LogLevel.Debug)
            .build();
`
"skipNegotiation: true", can skip negotiate but still no HubConnection establish successfully because of the claims are empty. [Authorize] on class level make it no claims but have auth token info.

**Comment by BrennanConroy** [comment]
Can you put a sample app that shows the issue on GitHub?

**Comment by tytannial** [comment]
> Can you put a sample app that shows the issue on GitHub?

https://github.com/tytannial/SimpleTemplate
Here's the code.

**Comment by davidfowl** [comment]
https://github.com/tytannial/SimpleTemplate/blob/master/SimpleTemplate.Web/Services/UserIdentityInfo.cs

The IHttpContextAccessor doesn't *really* work in SignalR applications today. It would be best to use 

```C#
var userId = Context.User.FindFirstValue("UserId");
if (!Guid.TryParse(userId, out Guid uid))
{
	return Task.CompletedTask;
}
```

**Comment by tytannial** [comment]
So the problem is the request doesn't get into hub, no ClaimsPrincipal been generated. Is there any solution for get ClaimsPrincipal outside the hub?

**Comment by davidfowl** [comment]
We pass the the claims from the http context to the hub (it’s actually the same user)

**Comment by tytannial** [comment]
![20200514094613](https://user-images.githubusercontent.com/11215623/81883434-d0a92d00-95c7-11ea-8205-dd3e4607de07.png)
😥

**Comment by tytannial** [comment]
I notice that when the [AuthorizeAttribute] on hub, the AuthorizationHandler is triggered first then the JwtBearerEvents.MessageReceived. But move [AuthorizeAttribute] to function, JwtBearerEvents.MessageReceived is first then the AuthorizationHandler.

**Comment by BrennanConroy** [comment]
Ah I think I see what's going on. Your middleware is setup like this:
```c#
app.UseAuthorization();
app.UseAuthentication();
```

Authorization is the process of allowing a "user" access to a resource. Authentication is the process of creating the "user". Because you run Authorization first, you don't have a user when the `AuthorizationHandler` runs.

Just switch it to:
```c#
app.UseAuthentication();
app.UseAuthorization();
```

**Comment by davidfowl** [comment]
Don't we have an analyzer for that @pranavkm ?

**Comment by pranavkm** [comment]
We have one for the ordering of UseRouting + UseAuthorization, but not this.

**Comment by davidfowl** [comment]
This should be next let’s track this one

**Comment by tytannial** [comment]
> Ah I think I see what's going on. Your middleware is setup like this:
> 
> ```cs
> app.UseAuthorization();
> app.UseAuthentication();
> ```
> 
> Authorization is the process of allowing a "user" access to a resource. Authentication is the process of creating the "user". Because you run Authorization first, you don't have a user when the `AuthorizationHandler` runs.
> 
> Just switch it to:
> 
> ```cs
> app.UseAuthentication();
> app.UseAuthorization();
> ```

Oh, Thanks, there words are too similar,and I correct these. With the "skipNegotiation: true" option, the other parts are functional!  🎉
But the negotiate request "/DashBoardHub/negotiate?negotiateViersion=1" still not working, "Authorization" bearer is in header but no "ClaimsPrincipal" generated correctly.😭

**Comment by BrennanConroy** [comment]
Could you grab server side logs please?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1

**Comment by tytannial** [comment]
With the debug log, I checked the dependence injection order again, and finally got it, thanks! I switch "services.AddSignalR()" after "services.AddAuthentication()" and "services.AddAuthorization()", then all works fine.

```cs
services.AddAuthentication();
services.AddAuthorization();
services.AddSignalR();
```
