### ISSUE TITLE
Cannot Authenticate with Keycloak OpenId

### ISSUE THREAD

**Issue by Keith3679** [dotnet/aspnetcore#21735]
### Describe the bug
I'm getting the following error in Postman when I try to make a call to my API:  

Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'master-realm, account'. Did not match: validationParameters.ValidAudience: 'lamp-app' or validationParameters.ValidAudiences: 'lamp-app'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

### To Reproduce

- Setup Keycloak
- Add JwtBearer package to API
- Request token in Postman
- Call API

### Further technical details
Startup.cs...

`       public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddDirectoryBrowser();

            // Authentication
            IdentityModelEventSource.ShowPII = true;
            
            
            
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(o =>
            {
                o.Authority = "http://localhost:8080/auth/realms/master";
                o.Audience = "lamp-app";

                o.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidAudiences = new string[] { "lamp-app" }
                };
                o.Events = new JwtBearerEvents()
                {
                    OnAuthenticationFailed = c =>
                    {
                        c.NoResult();

                            c.Response.StatusCode = 500;
                            c.Response.ContentType = "text/plain";
                            return c.Response.WriteAsync(c.Exception.ToString());
                        }
                    };
                o.RequireHttpsMetadata = false;
                o.SaveToken = true;
                o.Validate();
            });

            // Data Layers
            string dataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "LAMP");

            var jnlDirectory = Environment.GetEnvironmentVariable("JNLDIRECTORY") ?? Path.Combine(dataPath, "Jnls");
            services.AddSingleton<IJnlDataLayer>(new JnlFileSystem(jnlDirectory));

            var lampEventDirectory = Environment.GetEnvironmentVariable("LAMPEVENTDIRECTORY") ?? Path.Combine(dataPath, "Events");
            services.AddSingleton<ILAMPEventDataLayer>(new LAMPEventFileSystem(lampEventDirectory));

            // API Services
            services.AddSingleton<IJnlService, JnlService>();
            services.AddSingleton<IPlatformService, PlatformService>();
            services.AddSingleton<IDesignOptionService, DesignOptionService>();
            services.AddSingleton<ILAMPEventService, LAMPEventService>();

            services.AddSwaggerGen(c => { c.SwaggerDoc("v1", new OpenApiInfo { Title = "LAMP API", Version = "V1" }); });

            var cors = Environment.GetEnvironmentVariable("CORS");
            var origins = cors?.Split(',', StringSplitOptions.RemoveEmptyEntries);

            if (origins == null || origins.Length == 0)
            {
                origins = new string[] { "http://localhost", "http://localhost:3001" };
            }

            services.AddCors(options =>
            {
                options.AddPolicy("dev",
                builder =>
                {
                    builder.WithOrigins(origins)
                    .AllowAnyHeader()
                    .AllowAnyMethod();
                });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMiddleware<ExceptionMiddleware>();

            app.UseDefaultFiles(new DefaultFilesOptions
            {
                DefaultFileNames = new List<string> { "index.html" }
            });

            app.UseStaticFiles();

            app.UseAuthentication();

            app.UseRouting();

            app.UseCors("dev");

            app.UseAuthorization();

            app.UseSwagger();

            app.UseSwaggerUI(c => { c.SwaggerEndpoint("/swagger/v1/swagger.json", "LAMP API V1"); });

            app.UseSerilogRequestLogging();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }`

Controller...

`    [Route("api")]
    [EnableCors]
    [ApiController]
    [Authorize]
    public class WebAPIController : ControllerBase`

**Comment by Tratcher** [comment]
The token was issued for audiences `master-realm`, and `account`. You'll have to ask Keycloak why it was issued like that.

**Comment by Keith3679** [comment]
Thanks!  It did work when I added...

`ValidAudiences = new string[] { "master-realm", "account", "lamp-app" }`

I will try to address this with Keycloak.
