### ISSUE TITLE
Blazor-WebAssembly-Client-System.Text.Json.JsonSerializer.Deserialize does not work

### ISSUE THREAD

**Issue by bmcdonald01** [dotnet/aspnetcore#21736]
### Describe the bug
When using WebAssembly version of Blazor System.Text.Json.JsonSerializer.Deserialize it does not work.  It appears to silently fail and doesn't parse content.  Even though it is the string that was serialized.

### To Reproduce
I have included a sample solution with a Console application that works.  It includes Newtonsoft and System.Text.Json examples.  It serializes and deserializes.  Just set as start up project and see that Console works for both.  Set Wasm as startup and notice that NewtonSoft works but System.Text.Json does NOT work.

### Further technical details
I am running latest as of 5/11/2020 of VS 2019 preview and runtime

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015135
 Commit:    0b3c572e97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015135\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.513 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

[Test1.zip](https://github.com/dotnet/aspnetcore/files/4615583/Test1.zip)

**Comment by javiercn** [comment]
@bmcdonald01 thanks for contacting us.

Are you running in "Release" mode? it is likely that the linker is stripping some constructors/getters from your type as it doesn't see them being used and as a result of that the deserialization might fail silently.

See [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1) for details

**Comment by bfmsoft** [comment]
I am running in Debug.  Did you run the sample?  This is a stripped out project with barely anything in it and should just work?  Very simple example.

**Comment by bfmsoft** [comment]
If there is a way to "fix" this it would be great.  I am using NewtonSoft instead because it works.  It seems like I am doing something very basic.

**Comment by javiercn** [comment]
@bfmsoft We didn't take a look yet. I suggested the linker because it the root cause in most of the cases.

We'll take a look at the app and update the issue appropriately.

**Comment by bfmsoft** [comment]
Thank you.  I thought of the Linker but dont see why it would silently fail?  Can you point out how that can happen?  Just a link?  It would seem to throw an exception or something.

**Comment by javiercn** [comment]
If the linker strips the setter for example, system.text.json will silently ignore the property. When something is linked out the outcome can be an app that breaks or an app that doesn't behave as expected.

**Comment by javiercn** [comment]
The docs for the linker are here https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1 in case you didn't see the link before

**Comment by pranavkm** [comment]
System.Text.Json's deserialization is case sensitive by default. You'll need to configure it to deserialize it with with either camel case property naming or with case insensitivity for it to deserialize the json string in your WASM app. See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#case-insensitive-deserialization

**Comment by bmcdonald01** [comment]
It is capitalization it appears.  Turns out I knew about this but missed in my sample.  It the real application it appears that in the class it is set to Caps but the lower layer is converting to lower case.  Thanks.
