### ISSUE TITLE
Signalr IHubContext Documentation Issue

### ISSUE THREAD

**Issue by caseymarquis** [dotnet/aspnetcore#21749]
Sorry about the vague title, I'm not really sure where to file a suggestion for improving some aspnetcore documentation on 'docs.microsoft.com'.

In the signalr docs found here:
https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-3.1

The example which shows how to get an IHubContext instance from the middleware pipeline doesn't show the required call to next.Invoke(). Using the documentation as is results in portions of aspnetcore silently failing.

The example currently shows:
```C#
app.Use(async (context, next) =>
{
    var hubContext = context.RequestServices
                            .GetRequiredService<IHubContext<MyHub>>();
    //...
});
```

Changing it to the following might save some other users a few hours of debugging:
```C#
app.Use(async (context, next) =>
{
    var hubContext = context.RequestServices
                            .GetRequiredService<IHubContext<MyHub>>();
    await next.Invoke();
});
```

**Comment by BrennanConroy** [comment]
At the bottom of the page is a feedback section, where you can file feedback about the doc. Click the "This page" button to file an issue.
