### ISSUE TITLE
IdentityServer4 and Microsoft Account Issue - Error 404

### ISSUE THREAD

**Issue by steamprodz** [dotnet/aspnetcore#21743]
Hi!

I am using the next project, which has IdentityServer4 being set up already.
https://github.com/skoruba/IdentityServer4.Admin

Microsoft Account provider was added as an external provider and was working fine until the update of .NET Core from 2.2 to 3.1 (includes nuget packages update).

Now I am getting the following error message:
"HTTP Error 404.15 - Not Found
The request filtering module is configured to deny a request where the query string is too long."
The request length is about 2400 characters, which is way too big for the default limit (2048).

I cannot change the allowed length of the supported request in IIS settings, since Internet Explorer won't accept such a request.
I've been trying to use different settings inside the solution but nothing really works.

Would appreciate any help!

P.S.
Request url:
`https://localhost:44344/signin-microsoft?code=OAQABAAIAAAAm-06blBE1TpVMil8KPQ41_WJF9AV4de6UR3AB-ayEhQigzftd6JKISFafNCu7F3NjZXtfkdt4lxh43bJANx_NXfmBRRuPixgCTkTzvXnkz-9hDDhLEikYNTq5bi7AP3WQOe967mx1fp3Z5uj_xBSBydGlgGKymQMZZ6fQnPCY3KvalPhqubE0fKllOLu6wg_vR7lLOkCIquNi1FYp2YogjS9Q2hPG60xzc1jnrfSfwEXyQc2dtG1TdSPCncQ5Gl9Ab_fdGoZoHR51U7rryzn1qxtRY-KHUJWJ0KXvzVhOQnbXOVWcL-lQxFErWt-EvRoD9zJWupOd0wT8SVLZjvpzhIpugHi7mkl8EPrAqiE3fIcQyLfN9P7qLN41tuqPkoFtZh3sbYVWC9fjtmK47GGDXiKWh31HhGP2TK-mnGjZ9XzDZW9tv3bq3odoAhys_WQukka3peMlEGyByHfUCR3XyQj-jijU3mYf0vKsUrRfCaMR3Fyu7r0Yuz8W4QigrFaxF-fw6wG0bP0SV-YA5Pjj4eLozZx-Ws_vMvuvTZAzz5mWV2xlvgCSBbb-NWQOlij-q6Ks_hYOc9YSzwTdC47ygqkecJPzNdlOPDVTv3Ls-1kKrqX-Uk5SZfQ-M2ImnIrjyfQaNYG248Z3Lf6ZRRtACiVo9n5Fq-cS-BNG0NEMJTHNKA2WKzKm7IE3cgMl6FggAA&state=CfDJ8HhRPHtm6nJEnMVC86so7aLhyPNt8T0uZVbNC41-u41WmK06Ey4YkIKZEQlFFuVqBNgr2khpyfXfzmqX0dwfXrqdTZYaSlddZ7fPfEXZZwhp91IOCI709nDuzBmoc1HyPje7oo2EaUyGVMkYnRp7F_7w5hMrQ9NXWFSeN4OGjlzU18UVUXZXyxCL5U-Icm6f1CoaYITaq9ZX0J5TUCtvWLvVGZDsq4-KuZiaqrPsh6A6otNAF-OsQrkCHNNJjb4NiLBnBY-F6st3sXYGzkKOeMua4-U2A4Ii1AtFcEbSWLyfBSVRW9-V-cM0nKV2LSv_URFvmMwhtG1gSgD1KKkdneN8noY-AUvnpxJkmzfjIEh4o3lct8lL7Vn2RpEfAT4uC19PM6OQIA2jEZS9ibkMBnyPngLohLxWr0RPSe-7NFTgEhVGhHRi3ljT3Uq0sPhFM5FWlZutJCSEGEfQgru0_4yWGaps6ioHfbQpUPN2pu51ZRLq3lsTxPblzSJoocs82f0rc3pYwcKLAdUp-bAWIZtyK75ku-RYYN_X_nuSmlsq8qhF3jnv3a_BZa-HlRliNSLXdJQ3v0x0O-N3jXE5Kimj8X3pcGEGH0SWX66rPMKhMIREx5KQsTN2naF44UoyO7xW-m_COVN2Sany59e51-oibDi-Z5EwqHHm_YJfNms6fJrLQIzrVO8E1ih2v3dWXKxH4A8Q4TO-FJu5aJ6ROTvsLEw99CQUQ1rTOVn0CpyzFWirNREA6oJhPtXayH5bbsbCjT92vpLTew-VUWnYhK_F4Q1GJN1lqLXGZbKDU-OPfWdIqGcxAR_Gay6ZiJdDou_b9AIODrFD0WMBnIbKJPbYqCyjkgiagt7JxQh38Hf0ALJCwaW6MNAaHjiK7ylHkG6j6NXF1L-AZN0qT5vROi6RZtXftpNo0_45uzsPUzzbHtYuv_u4YcAiGNiqvyCf0kHhzt3ZzBCBlywtFFvLMCdDs4oJR6LPWQd-JBcUaC99RmktVSw49E2j9pqajAys9Jk1l6xhao7kB99rMJePSykN-3LIrkGBiFaZuf0YMZvZ_FvFFW-7PlZKx01lbhB2wyV9E-tJAmC31nWhhWelwsCrov1vy-yrsutCHgv_iuj42zAAMbwgviTfkR4pmAKwu1Ylvbyuup2D2J_3RvDppHWCqql2eeRh-AmTbu4WDu4dnbYtU-DzpEzPfAdSp7gkp3FGVG7UmiaYbKVA1umfnQaz0t6HR7HdbOtDyCRxQ9DnpHGkdHsITK2mJ8CHo4hiU7i9H4tWR-4neN4VSZEs-yeuP35Mk7pk2Mxqx48gSyIuAFM4-qL6qCx3A1WGYmh7n9zubC0z8B19SeanP5Hf34VtMQKdHUnoamo1SmzPuOMW&session_state=63a69eef-ce17-40a5-90d1-7eea816185a7`

Microsoft Account:
```
authenticationBuilder.AddMicrosoftAccount(options =>
{
      options.ClientId = externalProviderConfiguration.MicrosoftClientId;
      options.ClientSecret = externalProviderConfiguration.MicrosoftClientSecret;
 });
```

**Comment by Tratcher** [comment]
IdentityServer4 supplies a lot of extra state to this flow which is why the query gets so long. There are a few examples in that repo to address it:
https://github.com/IdentityServer/IdentityServer4/issues/407
https://github.com/IdentityServer/IdentityServer4/issues/55

**Comment by steamprodz** [comment]
I've came across this post
https://github.com/IdentityServer/IdentityServer4/issues/3502#issuecomment-517032676

It's noted it's not an issue of IdentityServer4.

I found a solution. If AD Azure authentication is used, you can simply add this (as you can find in IdentityServer4 docs):
```
public void ConfigureServices(IServiceCollection services)
{
    // configures the OpenIdConnect handlers to persist the state parameter into the server-side 
    IDistributedCache.services.AddOidcStateDataFormatterCache("aad", "demoidsrv");

    services.AddAuthentication()
        .AddOpenIdConnect("aad", "Azure AD", options =>
        {
            // ...
        });
} 
```

If you want to use Microsoft Account via `.AddMicrosoftAccount()` extension method, you can cache the State similarly to IdentityServer4 `.AddOidcStateDataFormatterCache()` method by implementing following service:
```
internal class ConfigureMicrosoftAccountOptions : IPostConfigureOptions<MicrosoftAccountOptions>
{
    private string[] _schemes;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public ConfigureMicrosoftAccountOptions(string[] schemes, IHttpContextAccessor httpContextAccessor)
    {
        _schemes = schemes ?? throw new ArgumentNullException(nameof(schemes));
        _httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor));
    }

    public void PostConfigure(string name, MicrosoftAccountOptions options)
    {    
        if (_schemes.Contains(name))
        {
            options.StateDataFormat = new IdentityServer4.Infrastructure.DistributedCacheStateDataFormatter(_httpContextAccessor, name);
        }
        // No schemes means use default Microsoft Account auth scheme
        else if (_schemes.Length == 0)
        {
            options.StateDataFormat = new IdentityServer4.Infrastructure.DistributedCacheStateDataFormatter(_httpContextAccessor, MicrosoftAccountDefaults.AuthenticationScheme);
        }
    }
}
```

Then you add the following extension method, which will inject the service:
```
public static IServiceCollection AddMicrosoftAccountStateDataFormatterCache(this IServiceCollection services, params string[] schemes)
{
    services.AddSingleton<IPostConfigureOptions<MicrosoftAccountOptions>>(
        service => new ConfigureMicrosoftAccountOptions(
            schemes,
            service.GetRequiredService<Microsoft.AspNetCore.Http.IHttpContextAccessor>())
    );

    return services;
}
```

And finally you call the extension method in `.ConfigureServices()`:
```
public void ConfigureServices(IServiceCollection services)
{
    // ...
    services.AddMicrosoftAccountStateDataFormatterCache();
    // ...
}
```

**Comment by anurse** [comment]
Triage: Closing as this is primarily an issue with certain token issuers, and it sounds like a workaround has been found.
