### ISSUE TITLE
Investigate ProjectTemplate tests failure to acquire dotnet new lock.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21748]
![image](https://user-images.githubusercontent.com/2008729/81735874-9403f700-944a-11ea-92ce-5d067f7616af.png)

https://dev.azure.com/dnceng/internal/_build/results?buildId=638406&view=ms.vss-test-web.build-test-results-tab&runId=19850116&resultId=120564&paneView=debug

Not sure the appropriate area/feature labels to mark this with so I haven't.

**Comment by Pilchie** [comment]
:eyes:

**Comment by pranavkm** [comment]
https://github.com/dotnet/aspnetcore/pull/21753 should address this. I'll add you to the PR @NTaylorMullen .

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm for handling the underlying issue.
Can you also unquarantine project template tests given that this is now resolved?

**Comment by pranavkm** [comment]
Done as part of https://github.com/dotnet/aspnetcore/pull/21831
