### ISSUE TITLE
Use AuthorizeAttribute without triggering a URL redirect on failure?

### ISSUE THREAD

**Issue by hempels** [dotnet/aspnetcore#21756]
Presently, when using ConfigureApplicationCookie and Authorize attributes, any failure will result in a redirect to the AccessDenied path. 

This creates a challenge for error reporting, etc, as the end user is not able to see the URL that was originally requested. It also makes troubleshooting more difficult as a page refresh will only ever result in reloading the access denied page (without attempting to re-authorize.)

Is it possible to configure the middleware to return the access denied status code page without redirecting, similar to UseStatusCodePagesWithReExecute?

**Comment by anurse** [comment]
There should be an event in the Cookie auth options that allows you to hook in to the Access Denied event and change the behavior based on path.

Also, if you're authorizing based on claims in the user, a simple refresh won't reload those. The claims are stored in the cookie and can only be refreshed by logging out and logging in again.

**Comment by hempels** [comment]
> There should be an event in the Cookie auth options that allows you to hook in to the Access Denied event and change the behavior based on path.

That is indeed an option, but there are some challenges that seem like they shouldn't be necessary to force middleware consumers to resolve. For example, how to render a razor view outside the context of a controller and write it to the response stream?

**Comment by hempels** [comment]
I'm not longer certain the above is an option. I've wasted hours on this and can't come up with a simple method to render a full view without a controller in context, and since the OnRedirectToAccessDenied event doesn't provide the original controller context, that's the state I'm in. It must be possible, but appears to absurdly complicated.

This really should be as simple as calling app.UseStatusCodePagesWithReExecute.

**Comment by blowdart** [comment]
This becomes an MVC question. @pranavkm ?

**Comment by pranavkm** [comment]
>  For example, how to render a razor view outside the context of a controller and write it to the response stream?

You could do something like this: https://github.com/aspnet/Entropy/blob/master/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs. There isn't much in terms of first class support for this.

**Comment by hempels** [comment]
> You could do something like this: https://github.com/aspnet/Entropy/blob/master/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs. There isn't much in terms of first class support for this.

Ya, I ended up doing basically that. It works, but it's kludgy. Would be nice to have it automatically apply when UseStatusCodePagesWithReExecute is called.

**Comment by mtozlu** [comment]
See #9039
