### ISSUE TITLE
[Blazor] component inheritance, rendering logic in base component

### ISSUE THREAD

**Issue by JvanderStad** [dotnet/aspnetcore#21764]
Follow up issue for #21664

My original issue was resolved with the following comment.

> You can use class file (.cs) to inherit from the abstract component class and that way you'll control exactly what you override.

However, I use Razor RenderFragments in the overriden class

eg.
```c#
public override void SetupColumns()
{
	this[nameof(OrganizationQueryModel.Id)].RazorTemplate = (OrganizationQueryModel context) =>
	@<div>
		<img class="img-thumbnail circle thumb96 d-inline-block m-0" src="@(LinkGenerator.GetPathByAction<OrganizationController>(x=>x.Picture(context.Id)))" />
	</div>;
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for the follow-up, @JvanderStad.
Reopening the original issue to continue the conversation in there for a better context.
