### ISSUE TITLE
.epub not found

### ISSUE THREAD

**Issue by MeysamMoghaddam** [dotnet/aspnetcore#21768]
Hi I'm going to use epub in my wasm project, but it also gives an error that it can't find the file.

in browser:
This localhost page can’t be foundNo webpage was found for the web address: https://localhost:44318/Content/Upload/SampleOrg.epub
HTTP ERROR 404

in console:
epub.js:3484 GET https://localhost:44318/Content/Upload/SampleOrg.epub 404

While this file is in my client project

**Comment by javiercn** [comment]
@MeysamMoghaddam thanks for contacting us.

You need to register the content type mapping in the static files provider. See [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1#fileextensioncontenttypeprovider) for details

**Comment by MeysamMoghaddam** [comment]
@javiercn Thanks, it's solved.
