### ISSUE TITLE
[Blazor] ServerSide Unstable Connection When HTTPS Enabled on Nginx

### ISSUE THREAD

**Issue by m1nicrusher** [dotnet/aspnetcore#21771]
### Describe the bug
When HTTPS is enabled (redirect 80 to 443) the website will be very unstable (frequent attempt of reconnection and CSS loss).
![image](https://user-images.githubusercontent.com/19246983/81779013-2f729600-9537-11ea-83b7-239217f22610.png)

### To Reproduce
1. Create a brand new project of Blazor ServerSide app.
2. Publish to be ready to run on Linux
3. Follow this document to configure everything. https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1
4. Before the "HTTPS configuration" part, everything works fine.
5. After "HTTPS configuration", unstable connection.

### Further technical details
- ASP.NET Core version: netcore3.1
- Include the output of `dotnet --info` (For both dev env and server env, see below)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS 2019 Version 16.5.4

Development Machine
```
> dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.201
 Commit:    b1768b4ae7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Server
```
# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@BrennanConroy can you please point to the "how to diagnose connectivity issues with SignalR" docs?

**Comment by BrennanConroy** [comment]
Could you please gather logs and a trace of the network traffic?
Instructions can be found: https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1

**Comment by m1nicrusher** [comment]
Hi all, when I was creating another test environment to provide the logs (On the document it says "Server-side logs may contain sensitive information"). I noticed that deleting this line from Nginx config file can fix the problem but I'm not sure if there will be anything insecure in the future:
```
limit_req  zone=one burst=10 nodelay;
```

It is from the section to redirect:
```
#Redirects all traffic
        location / {
            proxy_pass http://hellomvc;
            limit_req  zone=one burst=10 nodelay;
        }
```

**Comment by BrennanConroy** [comment]
Read the docs for [limit_req](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req) and decide what is best for your app.

But it sounds like you're probably hitting the limits and having some requests rejected by nginx.

If you're using LongPolling it's possible you could easily hit these limits as each message triggers a new HTTP request. WebSockets is definitely preferred, both for lower latency, and less HTTP requests.

**Comment by m1nicrusher** [comment]
> Read the docs for [limit_req](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req) and decide what is best for your app.
> 
> But it sounds like you're probably hitting the limits and having some requests rejected by nginx.
> 
> If you're using LongPolling it's possible you could easily hit these limits as each message triggers a new HTTP request. WebSockets is definitely preferred, both for lower latency, and less HTTP requests.

Hi, I'm pretty new to ASP.NET Core. A new project could suffer from this problem so how do I know if I'm using LongPolling or WebSockets and how do I change that? Thank you!

**Comment by BrennanConroy** [comment]
Look at your network traffic or logs and see what is being used. LongPolling will consist of a bunch of HTTP/HTTPS GET requests (and LongPolling being in the logs). WebSockets will have a single WS/WSS request with a 101 response code.

**Comment by m1nicrusher** [comment]
I did a fiddler trace and found a bunch of HTTPS GET and no WS/WSS request. How do I change to WebSockets?

**Comment by BrennanConroy** [comment]
Fiddler doesn't capture WebSocket traffic by default. It's a lot easier to see what transport you're using by looking at the logs on the server or browser, and looking at the network tab in the browser.

And if you find that you aren't using WebSockets, you likely need to change your nginx config to proxy websockets. https://www.nginx.com/blog/websocket-nginx/

**Comment by m1nicrusher** [comment]
> Fiddler doesn't capture WebSocket traffic by default. It's a lot easier to see what transport you're using by looking at the logs on the server or browser, and looking at the network tab in the browser.
> 
> And if you find that you aren't using WebSockets, you likely need to change your nginx config to proxy websockets. https://www.nginx.com/blog/websocket-nginx/

First, thank you for telling me this. 
However, there are still some problems. Here's What I did.

Firstly, I could see in the Console of my browser there is a line says ```Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.```
So I added these lines into the redirect section like this:
```
        #Redirects all traffic
        location / {
            proxy_pass http://hellomvc;
	    proxy_http_version 1.1; #Newly Added
   	    proxy_set_header Upgrade $http_upgrade; #Newly Added
    	    proxy_set_header Connection "Upgrade"; #Newly Added
            proxy_set_header Host $host; #Newly Added
        }
```
Now in console I could clearly saw something like "Websockets connected successfully" and got an 101 code. But the login part stopped working. It will return HTTP400 after I entered all the credential and click "Log In" (I'm using the pre-built authentication like the image below)
![image](https://user-images.githubusercontent.com/19246983/81953645-47d3d500-964b-11ea-9527-0376d5c6fb73.png)

Good news is when I re-added the line ```limit_req```. The unstable connection problem was gone but just can't login so I have to disable WebSockets for now...

**Comment by BrennanConroy** [comment]
The login page was working before adding WebSockets but isn't anymore? That is odd because the login page shouldn't have anything to do with WebSockets, unless normal HTTP traffic is running against the websocket changes you made to your nginx config, which might cause them to start behaving oddly.

Can you gather the server logs so we can try to see why the server responds with a 400? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1

Also, I noticed you followed the generic docs for Linux + nginx. I'm wondering if you could look at the blazor specific docs and see if there is something you're missing? https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.1#linux-with-nginx

**Comment by m1nicrusher** [comment]
> The login page was working before adding WebSockets but isn't anymore? That is odd because the login page shouldn't have anything to do with WebSockets, unless normal HTTP traffic is running against the websocket changes you made to your nginx config, which might cause them to start behaving oddly.
> 
> Can you gather the server logs so we can try to see why the server responds with a 400? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1
> 
> Also, I noticed you followed the generic docs for Linux + nginx. I'm wondering if you could look at the blazor specific docs and see if there is something you're missing? https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.1#linux-with-nginx

This is when WebSockets is enabled and
```
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {940036cc-a493-4641-abb3-7368647880eb} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /var/www/SAO
warn: Microsoft.EntityFrameworkCore.Infrastructure[10410]
      'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Remove the 'AddEntityFramework*' call as in most cases it's not needed and might cause conflicts with other products and services registered in the same service provider.
warn: Microsoft.EntityFrameworkCore.Infrastructure[10410]
      'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Remove the 'AddEntityFramework*' call as in most cases it's not needed and might cause conflicts with other products and services registered in the same service provider.
```
When I redirected to the log in page (I haven't entered any credential yet):
```
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {77ef5452-641f-48d6-8ae1-fc7d976cd118} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
I entered credential and clicked "Log in".
Nothing happened on Console.

I disabled WebSockets:
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /var/www/SAO
warn: Microsoft.EntityFrameworkCore.Infrastructure[10410]
      'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Remove the 'AddEntityFramework*' call as in most cases it's not needed and might cause conflicts with other products and services registered in the same service provider.
warn: Microsoft.EntityFrameworkCore.Infrastructure[10410]
      'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Remove the 'AddEntityFramework*' call as in most cases it's not needed and might cause conflicts with other products and services registered in the same service provider.
info: RayPhothusiatic.Areas.Identity.Pages.Account.LoginModel[0]
      User logged in.
```
Everything looked fine.

**Comment by pranavkm** [comment]
@blowdart would you know what might be causing this error:

> ---> System.Security.Cryptography.CryptographicException: The key {77ef5452-641f-48d6-8ae1-fc7d976cd118} was not found in the key ring.

**Comment by blowdart** [comment]
Yes, the key is not in the keyring :)

Which is weird, because I don't see any warnings about ephemeral keys, but you are on linux, so maybe the app restarted and keys were persisted. If this is in a container that's likely.

@m1nicrusher could you configure data protection so it [writes to a directory](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#file-system) that persists after a reboot.

**Comment by m1nicrusher** [comment]
> Yes, the key is not in the keyring :)
> 
> Which is weird, because I don't see any warnings about ephemeral keys, but you are on linux, so maybe the app restarted and keys were persisted. If this is in a container that's likely.
> 
> @m1nicrusher could you configure data protection so it [writes to a directory](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#file-system) that persists after a reboot.

Guys, the problem is getting weirder and weirder. I think the problem of "key" is another weird problem because I did a couple of tests of storing key into files and not storing key into files when both HTTPS on and off. It turns out it has nothing to do with the Login problem.

First I did a test **HTTPS off & Not Storing Key into Files**
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/TheRayWorldBundle/RayPhothusiatic
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {9e7bb96c-abf9-4598-89c6-41c5b73ca92c} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
info: RayPhothusiatic.Areas.Identity.Pages.Account.LoginModel[0]
      User logged in.
```
As you can see, it was complaining about key not found but I could log in without a problem.

Then I did a second test, **HTTPS off & Storing Key into Files**
I could already saw the key file in the folder I specified and I could also saw a warning about the key storing unencrypted which should be normal. However,
```
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {14662767-4ad2-4950-9373-4c395eddca15} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/TheRayWorldBundle/RayPhothusiatic
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {c60dd965-7d94-4394-ad60-3cb37639c038} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
info: RayPhothusiatic.Areas.Identity.Pages.Account.LoginModel[0]
      User logged in.
```
As you can see, it was still complaining about key not found somehow (the key it complained about was not the same key that it saved into file; they had different names). And logging in was still not a problem.

Then third test **HTTPS on & Storing Key into Files**
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /root/TheRayWorldBundle/RayPhothusiatic
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {9e7bb96c-abf9-4598-89c6-41c5b73ca92c} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
It magically stopped complaining about the unencrypted key problem. And when I entered all the credential and clicked log in button, nothing happened on console and my browser returned a 400 error right away.

I'm completely confused.

**Comment by m1nicrusher** [comment]
@pranavkm @blowdart @javiercn @BrennanConroy @mkArtakMSFT:
Hi all. 

It seems that I'm now having two separate issues that are **Login/out issue** and **Key Not Found issue**. The original issue which is **unstable connection issue** is purely about LongPolling being rejected by ```limit_req```. 

Because it has been fixed, I will open new issues about those respectively. There could be some connections between those issues so I will post the link here to refer the new issue.

https://github.com/dotnet/aspnetcore/issues/21933#issue-619886939

Thank you all for helping me out. I appreciate it a lot, for real.
