### ISSUE TITLE
core 3.1 garbage collector is lazy

### ISSUE THREAD

**Issue by tarastriska** [dotnet/aspnetcore#21770]
### Describe the bug
We have microservices running in docker/k8s.
During load memory usage increases which is fine.
But it never gets released. It grows and never goes down. We tried calling GC explicitly and it frees a lot of memory (for ex from 1.5 Gb to ~400Mb). This is the behavior when we don't set limits.
Does it mean that GC is not called if we have free available memory?

### Further technical details
- ASP.NET Core version 3.1

**Comment by javiercn** [comment]
@tarastriska thanks for contacting us.

That's the default behavior of the garbage collector, it tries to avoid doing work while there is memory available to consume. As you noticed, when you explicitly trigger the garbage collection it frees memory. I would read [here](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/) and [here](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc) about how it works.

There are several knobs you can tweak to adjust it to your preferences, but I would recommend you ask in [dotnet/runtime](https://github.com/dotnet/runtime) as they'll be able to give you better guidance.

**Comment by KrystofZacek** [comment]
I have noticed that too. It is horifying to watch RAM eaten having a long running service. The thing is one becomes unsure whether there is a memory a leak or just that the GC is lazy as hell.
