### ISSUE TITLE
The application randomly stops responding

### ISSUE THREAD

**Issue by smokedog2** [dotnet/aspnetcore#21773]
I have an application that randomly stops responding after upgrading from .net core 2.x to 3.1, maybe a few days, or a few weeks. After stopping the response, the resources are almost not consumed, and there is no log output. I suspect a deadlock. I have a 1g dump file, but I don't know how to analyze it.
Can someone help? Thanks!
Deployment environment
centos7.4 + docker

**Comment by javiercn** [comment]
@smokedog2 thanks for contacting us.

I would suggest you start by loading the process dump inside Visual Studio and looking at the list of Tasks in the parallel stacks window. See [here](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-a-parallel-application?view=vs-2019#using-the-parallel-stacks-window-threads-view) for details.

Alternatively, you can use Win DBG, load the sos library (dotnet tool install -g dotnet-sos) and either looking at the threads to see where they are blocked on, or running !DumpAsync --stacks to see the Tasks in the app and where they are waiting.

**Comment by smokedog2** [comment]
This is the information I saw through the command.

> dumpasync -stacks                                                                                                                                                                    
Statistics:
              MT    Count    TotalSize Class Name
00007f759069d310        1          128 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[centanet.com.Middleware.Redirect301Middleware+<Invoke>d__2, centanet.com]]
00007f759069c170        1          128 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[centanet.com.Startup+<>c+<<Configure>b__1_0>d, centanet.com]]
00007f7590138c70        1          128 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<StartAsync>d__23, Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets]]
00007f758fa3b468        1          128 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[System.Net.Http.HttpConnection+<FillAsync>d__87, System.Net.Http]]
00007f759069fb40        1          136 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequestsAsync>d__213`1[[Microsoft.AspNetCore.Hosting.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel.Core]]
00007f759069bc18        1          136 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Routing.EndpointMiddleware+<<Invoke>g__AwaitRequestTask|6_0>d, Microsoft.AspNetCore.Routing]]
00007f7590138830        1          136 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<DoSend>d__28, Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets]]
00007f759011e838        1          136 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher+<>c__DisplayClass8_0+<<StartAcceptingConnectionsCore>g__AcceptConnectionsAsync|0>d, Microsoft.AspNetCore.Server.Kestrel.Core]]
00007f759011e108        1          136 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Microsoft.AspNetCore.Connections.ConnectionContext, Microsoft.AspNetCore.Connections.Abstractions],[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener+<AcceptAsync>d__13, Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets]]
00007f759011d050        1          136 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<WaitForShutdownAsync>d__5, Microsoft.Extensions.Hosting.Abstractions]]
00007f759069dd08        1          144 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[centanet.com.Middleware.CustomStreamMiddleware+<Invoke>d__2, centanet.com]]
00007f7590699208        1          144 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeFilterPipelineAsync>g__Awaited|19_0>d, Microsoft.AspNetCore.Mvc.Core]]
00007f7590698060        1          144 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeNextResourceFilter>g__Awaited|24_0>d, Microsoft.AspNetCore.Mvc.Core]]
00007f75901362a8        1          144 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<DoReceive>d__26, Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets]]
00007f759069a4d0        1          152 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeAsync>g__Logged|17_1>d, Microsoft.AspNetCore.Mvc.Core]]
00007f7590135de8        1          152 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<ProcessReceives>d__27, Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets]]
00007f759011d510        1          152 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions]]
00007f75906a1cd0        1          160 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32, Microsoft.AspNetCore.Server.Kestrel.Core]]
00007f75906a17b8        1          168 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__12`1[[Microsoft.AspNetCore.Hosting.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel.Core]]
00007f758fa3bbe0        1          168 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ArraySegment`1[[System.Byte, System.Private.CoreLib]], System.Private.CoreLib],[System.Net.Http.HttpConnection+<ReadNextResponseHeaderLineAsync>d__84, System.Net.Http]]
00007f759069eb68        1          192 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__214`1[[Microsoft.AspNetCore.Hosting.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel.Core]]
00007f7590137b60        1          192 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<ProcessSends>d__29, Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets]]
00007f759069e150        1          200 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[centanet.com.Middleware.AlarmMiddleware+<Invoke>d__3, centanet.com]]
00007f758fa1eb20        4          544 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http],[Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<Timeout>d__6`1[[System.Net.Http.HttpResponseMessage, System.Net.Http]], Com.Ctrip.Framework.Apollo]]
00007f758fa1a490        4          576 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http],[System.Net.Http.RedirectHandler+<SendAsync>d__4, System.Net.Http]]
00007f758fa3df98        4          608 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http],[System.Net.Http.HttpConnectionPool+<SendWithNtConnectionAuthAsync>d__48, System.Net.Http]]
00007f75900d2b30        4          672 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[Com.Ctrip.Framework.Apollo.Util.Http.HttpResponse`1[[System.Collections.Generic.IList`1[[Com.Ctrip.Framework.Apollo.Core.Dto.ApolloConfigNotification, Com.Ctrip.Framework.Apollo]], System.Private.CoreLib]], Com.Ctrip.Framework.Apollo],[Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<DoGetAsync>d__4`1[[System.Collections.Generic.IList`1[[Com.Ctrip.Framework.Apollo.Core.Dto.ApolloConfigNotification, Com.Ctrip.Framework.Apollo]], System.Private.CoreLib]], Com.Ctrip.Framework.Apollo]]
00007f758fa1b490        4          704 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http],[System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__70, System.Net.Http]]
00007f758fa19b18        4          736 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http],[System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47, System.Net.Http]]
00007f75900d2eb0        4          896 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Com.Ctrip.Framework.Apollo.Internals.RemoteConfigLongPollService+<DoLongPollingRefresh>d__15, Com.Ctrip.Framework.Apollo]]
00007f758fa3cc98        4         1056 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Net.Http.HttpResponseMessage, System.Net.Http],[System.Net.Http.HttpConnection+<SendAsyncCore>d__53, System.Net.Http]]
Total 55 objects
In 13 chains.
         Address               MT     Size      State Description
00007f707c2471b8 00007f758fa3cc98      264         20 System.Net.Http.HttpConnection+<SendAsyncCore>d__53
Async "stack":
.00007f707c2472c0 (1) System.Net.Http.HttpConnectionPool+<SendWithNtConnectionAuthAsync>d__48
..00007f707c247358 (1) System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47
...00007f707c247410 (0) System.Net.Http.RedirectHandler+<SendAsync>d__4
....00007f707c2474a0 (0) System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__70
.....00007f707c2476a0 System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise
--------------------------------------------------------------------------------
00007f707c2476f8 00007f758fa1eb20      136          0 Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<Timeout>d__6`1[[System.__Canon, System.Private.CoreLib]]
Async "stack":
.00007f707c247780 (0) Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<DoGetAsync>d__4`1[[System.__Canon, System.Private.CoreLib]]
..00007f71bc01bd48 (1) Com.Ctrip.Framework.Apollo.Internals.RemoteConfigLongPollService+<DoLongPollingRefresh>d__15
--------------------------------------------------------------------------------
00007f713c154ee0 00007f758fa3cc98      264         20 System.Net.Http.HttpConnection+<SendAsyncCore>d__53
Async "stack":
.00007f713c154fe8 (1) System.Net.Http.HttpConnectionPool+<SendWithNtConnectionAuthAsync>d__48
..00007f713c155080 (1) System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47
...00007f713c155138 (0) System.Net.Http.RedirectHandler+<SendAsync>d__4
....00007f713c1551c8 (0) System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__70
.....00007f713c1553c8 System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise
--------------------------------------------------------------------------------
00007f713c155420 00007f758fa1eb20      136          0 Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<Timeout>d__6`1[[System.__Canon, System.Private.CoreLib]]
Async "stack":
.00007f713c1554a8 (0) Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<DoGetAsync>d__4`1[[System.__Canon, System.Private.CoreLib]]
..00007f71fc000ad0 (1) Com.Ctrip.Framework.Apollo.Internals.RemoteConfigLongPollService+<DoLongPollingRefresh>d__15
--------------------------------------------------------------------------------
00007f713c575568 00007f7590698060      144         -1 Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeNextResourceFilter>g__Awaited|24_0>d
Async "stack":
.00007f713c5755f8 (0) Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeFilterPipelineAsync>g__Awaited|19_0>d
..00007f713c575688 (0) Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeAsync>g__Logged|17_1>d
...00007f713c575720 (0) Microsoft.AspNetCore.Routing.EndpointMiddleware+<<Invoke>g__AwaitRequestTask|6_0>d
....00007f713c5757a8 (0) centanet.com.Startup+<>c+<<Configure>b__1_0>d
.....00007f713c575828 (0) centanet.com.Middleware.Redirect301Middleware+<Invoke>d__2
......00007f713c5758a8 (0) centanet.com.Middleware.CustomStreamMiddleware+<Invoke>d__2
.......00007f713c575938 (0) centanet.com.Middleware.AlarmMiddleware+<Invoke>d__3
........00007f713c575a00 (1) Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__214`1[[System.__Canon, System.Private.CoreLib]]
.........00007f713c575ac0 (0) Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequestsAsync>d__213`1[[System.__Canon, System.Private.CoreLib]]
..........00007f713c575b48 (0) Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__12`1[[System.__Canon, System.Private.CoreLib]]
...........00007f713c575bf0 (0) Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32
--------------------------------------------------------------------------------
00007f717c247a00 00007f758fa1eb20      136          0 Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<Timeout>d__6`1[[System.__Canon, System.Private.CoreLib]]
Async "stack":
.00007f717c247a88 (0) Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<DoGetAsync>d__4`1[[System.__Canon, System.Private.CoreLib]]
..00007f73fc01f378 (1) Com.Ctrip.Framework.Apollo.Internals.RemoteConfigLongPollService+<DoLongPollingRefresh>d__15
--------------------------------------------------------------------------------
00007f717c24a168 00007f758fa3b468      128          0 System.Net.Http.HttpConnection+<FillAsync>d__87
Async "stack":
.00007f717c24a1e8 (1) System.Net.Http.HttpConnection+<ReadNextResponseHeaderLineAsync>d__84
..00007f717c24a290 (21) System.Net.Http.HttpConnection+<SendAsyncCore>d__53
...00007f717c24a398 (1) System.Net.Http.HttpConnectionPool+<SendWithNtConnectionAuthAsync>d__48
....00007f717c247678 (1) System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47
.....00007f717c247730 (0) System.Net.Http.RedirectHandler+<SendAsync>d__4
......00007f717c2477c0 (0) System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__70
.......00007f717c2479a8 System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise
--------------------------------------------------------------------------------
00007f72bc478730 00007f758fa3cc98      264         20 System.Net.Http.HttpConnection+<SendAsyncCore>d__53
Async "stack":
.00007f72bc478838 (1) System.Net.Http.HttpConnectionPool+<SendWithNtConnectionAuthAsync>d__48
..00007f72bc4788d0 (1) System.Net.Http.HttpConnectionPool+<SendWithRetryAsync>d__47
...00007f72bc478988 (0) System.Net.Http.RedirectHandler+<SendAsync>d__4
....00007f72bc478a18 (0) System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__70
.....00007f72bc478c18 System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise
--------------------------------------------------------------------------------
00007f72bc478c70 00007f758fa1eb20      136          0 Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<Timeout>d__6`1[[System.__Canon, System.Private.CoreLib]]
Async "stack":
.00007f72bc478cf8 (0) Com.Ctrip.Framework.Apollo.Util.Http.HttpUtil+<DoGetAsync>d__4`1[[System.__Canon, System.Private.CoreLib]]
..00007f71bc01bac8 (1) Com.Ctrip.Framework.Apollo.Internals.RemoteConfigLongPollService+<DoLongPollingRefresh>d__15
--------------------------------------------------------------------------------
00007f737c037e78 00007f759011d050      136          0 Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<WaitForShutdownAsync>d__5
Async "stack":
.00007f737c037f00 (1) Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4
..00007f737c037f98 System.Threading.Tasks.Task+SetOnInvokeMres
--------------------------------------------------------------------------------
00007f743c59b7f0 00007f7590135de8      152          0 Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<ProcessReceives>d__27
Async "stack":
.00007f743c59b8c8 (0) Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<DoReceive>d__26
..00007f743c59baa0 (0) Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<StartAsync>d__23
--------------------------------------------------------------------------------
00007f743c59b958 00007f7590137b60      192          0 Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<ProcessSends>d__29
Async "stack":
.00007f743c59ba18 (0) Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<DoSend>d__28
--------------------------------------------------------------------------------
00007f743c59be18 00007f759011e108      136          0 Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener+<AcceptAsync>d__13
Async "stack":
.00007f71fc003650 (0) Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher+<>c__DisplayClass8_0+<<StartAcceptingConnectionsCore>g__AcceptConnectionsAsync|0>d
--------------------------------------------------------------------------------

**Comment by smokedog2** [comment]
Another point needs to be explained. After the application stopped responding, I only successfully dumped the file once, and at other times it always showed Writing dump to /root/.dotnet/tools/core_20200514_091451
...
Wait a few hours and still do
