### ISSUE TITLE
When blazor project opens in VS with .razor component displayed on startup then the class view content dissappears

### ISSUE THREAD

**Issue by KrystofZacek** [dotnet/aspnetcore#21779]
In VS2019 when I open a server-side Blazor project then the class view content dissapears if on VS startup a razor component page is to be displayed.

Example:
Say that I open VS2019 blazor project and a MsBox.razor file is to be automatically re-opened (from the last VS session). Then the class views content is displayed briefly and then dissappears.
The only way to get it back is to close all .razor files, close the VS and re-open it again. It seems that the VS .razor extension somehow crashes the class view on VS startup.

.NET Core SDK 3.1.202
VS2019 16.5.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
