### ISSUE TITLE
Rewrite ResourceLocation by [ResourceLocationAtrribute] with whitespace

### ISSUE THREAD

**Issue by anranruye** [dotnet/aspnetcore#21772]
private string GetResourcePath(Assembly assembly)
        {
            var resourceLocationAttribute = GetResourceLocationAttribute(assembly);

            // If we don't have an attribute assume all assemblies use the same resource location.
            var resourceLocation = resourceLocationAttribute == null
                ? _resourcesRelativePath
                : resourceLocationAttribute.ResourceLocation + ".";
            resourceLocation = resourceLocation
                .Replace(Path.DirectorySeparatorChar, '.')
                .Replace(Path.AltDirectorySeparatorChar, '.');

            return resourceLocation;
        }

https://github.com/dotnet/aspnetcore/blob/5a0526dfd991419d5bce0d8ea525b50df2e37b04/src/Localization/Localization/src/ResourceManagerStringLocalizerFactory.cs#L251

In this method of ResourceManagerStringLocalizerFactory class, line 251 should check resourceLocationAttribute.ResourceLocation is not whitespace before appending a dot, otherwise when rewrite the resource path of assembly with
`[assembly: ResourceLocation(" ")]`
to make the rootpath as resource path, it doesn't work.

Although null or empty string not allowed in the ctor of ResourceLocationAttribute, whitespace is valid.
Consider either make whitespace invalid, or add a check in ResourceManagerStringLocalizerFactory  code.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to  change.
