### ISSUE TITLE
URGENT Blazor missing Indexed Navigation Menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21785]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1006209/urgent-blazor-missing-indexed-navigation-menu.html)._

---
After all the VS 2019 updates that have been done for Blazor, why can't we navigate our code(objetcs,functions) ?
As solutions become bigger, it's getting harder and harder to use the Code Editor to Navigate files.
Is there an ETA on this basic feature?
Can you please add this feature ASAP ?
Thanks

---
#### Visual Studio Feedback System on 4/25/2020, 06:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Artak Mkrtchyan on 5/1/2020, 10:40 AM: 

<p>Thanks for contacting us. It’s not clear what specific feature you are missing here.</p>

#### Patrick Lapointe on 5/4/2020, 07:33 AM: 

<p>The code in Visual Studio always has a way to navigate objects/functions at the top part.</p><p>A combobox with the index of all objects and functions to navigate quickly.</p><p>This is missing in Blazor and is a huge drawback.</p><p>When will this basic feature be included in Visual Studio ?</p>

---
### Original Solutions
(no solutions)

**Comment by ajaybhargavb** [comment]
Thanks for the report. We don't have support for C# refactorings in Blazor yet. This will be handled as part of https://github.com/dotnet/aspnetcore/issues/18211.
