### ISSUE TITLE
When adding new item to Blazor project  VS should first of all offer Razor Component. Not Razor Page.

### ISSUE THREAD

**Issue by KrystofZacek** [dotnet/aspnetcore#21783]
When adding new item to Blazor project  VS should offer first of all Razor Component. Not Razor Page. Offering Razor Page instead of Razor Component might be extremely missleading for newbies and impractical for seasoned users.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We prefer to keep the order of items as is as the Blazor Server project is a usual ASP.NET Core Web application.

**Comment by KrystofZacek** [comment]
Blazor project is a project where we typically add razor components. Not razor pages. I have realized several SSB projects without adding a single razor page.
