### ISSUE TITLE
In Blazor project in Visual Studio in .razor components there should be the namespaces/classes/methods bar as in case of a .cs file

### ISSUE THREAD

**Issue by KrystofZacek** [dotnet/aspnetcore#21781]
In .razor components editor window in VS there should be the namespaces/classes/methods bar on top of the window as it is the case for normal .cs files.

That would simplify the navigation in big .razor component files a lot.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the VS Feedback to report this issue, so the team who owns the area can track the ask.
