### ISSUE TITLE
Supporting strongly-typed Ids and other simple value objects as Parameters by means of a TypeConverter

### ISSUE THREAD

**Issue by BenjaminCharlton** [dotnet/aspnetcore#21784]
My application uses strongly-typed Ids and value objects throughout. The pattern I'm following is explained in a four part blog here:

https://andrewlock.net/using-strongly-typed-entity-ids-to-avoid-primitive-obsession-part-1/

To see the benefit from using them they should be used consistently right up the edges of the application, such as in web APIs and EntityFramework. EFCore has made that easy, but Blazor hasn't (yet)

;-)

At the moment, I can't do this in my Blazor page:

`@page "/students/{id:StudentId}"`

Here, `StudentId` is a value object. It's an immutable wrapper class for a `System.Guid` (I have others for `System.Int` and `System.String` but they can all be expressed as primitive types).

I am happy to write a class derived from `System.ComponentModel.TypeConverter` for each of these value objects so that they can be created from a string passed in a URL. However, at the moment `RouteConstraint` class won't look for the converter and try to use it.

I'm speaking of the `CreateRouteConstraint` method of the  `RouteConstraint` class here:

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/Routing/RouteConstraint.cs

There is a switch statement to switch between 8 supported primitive types, 8 more nullable versions of those types and `default`.

It would be really helpful to me if it was also able to support types that were decorated with a `TypeConverterAttribute` allowing them to be converted to one of the supported primitive types.

There is one other place (that I have found, with help from @captainsafia) that would need to be changed to support my strongly-typed Ids. That is in the `MemberAssignment` class here:

https://github.com/captainsafia/aspnetcore/blob/master/src/Components/Components/src/Reflection/MemberAssignment.cs

It returns an object of type `IPropertySetter` from the method `CreatePropertySetter` but the object being returned never looks for a `TypeConverterAttribute` on the `Type targetType`. If it did, it could use the `ConvertTo` method of the converter to set the property value instead of throwing an `InvalidCastException`, which it does now.

I hope I've explained ok what I'm hoping to achieve. I would be interested to assist (if you trust me enough!) but I warn you I'm not at the same level as you guys are.

**Comment by mkArtakMSFT** [comment]
This is similar ask to #8493

**Comment by BenjaminCharlton** [comment]
Hi I see this is now closed but there are no notes about the implementation. Can we now code TypeConverters for strongly typed Ids and other value objects and pass them as parameters?
