### ISSUE TITLE
In Blazor project when exception is thrown in the markup part of .razor component then VS should show WHERE in the markup the exception was thrown.

### ISSUE THREAD

**Issue by KrystofZacek** [dotnet/aspnetcore#21782]
.razor component code consists of markup and @code part.
If exception is thrown in the code within @code part then VS shows where the exception comes from.

Unfortunately if the exception comes from the code embedded in the markup part then we get only an exception dialog without showing where the exception comes from.

It then may be very difficult to find the exception source in the markup.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Closing as we've made a lot of improvements in this area. If you're still facing an issue, please file a VS Feedback issue for this. Thanks!
