### ISSUE TITLE
angular-devkit progress shows many "fail: Microsoft.AspNetCore.SpaServices[0]" errors

### ISSUE THREAD

**Issue by SpiraMira** [dotnet/aspnetcore#21793]
### Describe the bug
Latest dotnet new angular generates projects with these build/run issues when
angular-devkit/build-angular progress option is set to true as in:

"architect": { "build": { "builder": "@angular-devkit/build-angular:browser", "options": { "progress": true,

Streaming Errors look like this:

`
fail: Microsoft.AspNetCore.SpaServices[0] <s> [webpack.Progress] 41% building 266/266 modules 0 active
`

Projects compile though. The only way to silence these errors is by changing the progress option back to false (which it is by default)

Anything to worry about?

### To Reproduce

dotnet new angular
in angular.json flip architect -> build -> options -> progress to **true**

### Further technical details

macOS Catalina
dotnet --version = 3.1.201
node -v = v12.16.3
npm -v = 6.14.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is a limitation in the system as we assume that whatever is written to the error stream is an actual error. Angular, in this case, uses that stream for progress update purposes. So if you'd like to get this resolved you'll need to raise this concern with Angular folks in their repo.
