### ISSUE TITLE
[Blazor] [Azure Storage] Incorrect content type

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#21809]
Hi,

I'm running into an issue when deploying Blazor WebAssembly app to Azure Storage (hosted as a static website).

I have first published the app from Visual Studio (latest preview) to a local folder. Then I uploaded all published files using Microsoft Azure Storage Explorer (latest version 1.13.0) to my Azure Storage container.

However, when I run the app in Chrome (the app runs fine in Edge) I get the following error when the app attempts to load JavaScript files:

_Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec._

The problem seems to be that Azure Storage Explorer uploads JavaScript file with content-type "text/plain" rather than "text/javascript". After manually correcting the content-type, the app worked fine.

Are you aware of this problem? This is not a good experience for a developer trying to publish Blazor app for the first time. Ideally, I'd like to be able to streamline the publishing experience by being able to upload files to Blob Storage directly from Visual Studio (with the proper content-type of course).

Thank you for your attention.

**Comment by Tratcher** [comment]
@danroth27

**Comment by danroth27** [comment]
Hi @daniel-p-tech. Thanks for sharing with us this feedback! Yes, we are aware of the issue. It isn't specific to Blazor. Depending on how you deploy your files to an Azure Static Website the mime types may not get setup correctly. Using the Azure Storage Explorer has this problem. We have notified the Azure Storage folks and they area aware of the issue. We are working with them to improve their support for static web site hosting.

Since this issue isn't specific to Blazor or ASP.NET Core, I'm going to go ahead and close it as answered. Let us know though if you have more questions!

@timheuer @ryanerdmann

**Comment by daniel-p-tech** [comment]
Thank you @danroth27 for your quick response. Your answer implies that there is a different mechanism for publishing Blazor app to Azure Static Website that doesn't have the issues that I raised. Can you or someone else point me in the right direction? Maybe this is something that should be properly described in the deployment section of Blazor documentation?

Thanks!

**Comment by danroth27** [comment]
> Your answer implies that there is a different mechanism for publishing Blazor app to Azure Static Website that doesn't have the issues that I raised. Can you or someone else point me in the right direction?

Other options are to use the Azure CLI, or the Azure Storage integration with Visual Studio Code.

> Maybe this is something that should be properly described in the deployment section of Blazor documentation?

Yes, this is something we are working to address.

**Comment by timheuer** [comment]
@daniel-p-tech check out my post to automate this using CI/CD and the Azure CLI https://timheuer.com/blog/deploy-blazor-app-to-azure-using-github-actions
