### ISSUE TITLE
Blazor _content folder

### ISSUE THREAD

**Issue by jbomhold3** [dotnet/aspnetcore#21808]
```<StaticWebAssetBasePath>apps/app1</StaticWebAssetBasePath>```
works to move _framework and _framework/bin to the correct base path

However, _content still outputs to root.

### Further technical details
- ASP.NET Core version Blazor WASM RC1

**Comment by javiercn** [comment]
@jbomhold3 thanks for contacting us.

StaticWebAssetBasePath controls the base path for the assets of a given project, not assets from referenced projects nor nuget packages. For that, you need to use MSBuild to change their paths.

**Comment by jbomhold3** [comment]
do you have an example of this?

**Comment by javiercn** [comment]
Something like this should do the trick. You'll have to play a bit with MSBuild to make it work, but this is the rough sketch.

```xml
<PropertyGroup>
<ResolveStaticWebAssetInputsDependsOn>
$(ResolveStaticWebAssetInputsDependsOn);
UpdateAssetsPaths;
</ResolveStaticWebAssetInputsDependsOn>
</PropertyGroup>

<Target Name="UpdateAssetPaths">
  <ItemGroup>
    <StaticWebAsset Condition="'%(StaticWebAsset.BasePath)' == '_content/Libraryx'">
      <BasePath>app/library1</BasePath>
    </StaticWebAsset>
  </ItemGroup>
</TargetPath>
```

**Comment by jbomhold3** [comment]
Thank you
