### ISSUE TITLE
Updated PWA notification

### ISSUE THREAD

**Issue by Apskalle** [dotnet/aspnetcore#21818]
If a newer version is available it is AFAIU downloaded in the background and used in the next session. 
I would want to notify the app user of it's existence and give an opportunity for it to be used directly (probably involving a reload/restart).

Is that possible? 

/M

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
