### ISSUE TITLE
SignalR Core Java Client support for JRE 1.7

### ISSUE THREAD

**Issue by hristijankiko** [dotnet/aspnetcore#21810]
### Describe the bug
I have a project which uses JRE 1.7 and it seems like the current version of the SignalR Java client requires JRE 1.8.

Any suggestions on how I can get around this?

### To Reproduce
What steps can we follow to reproduce the issue?
Try to use SignalR Core Java Client with JRE 1.7

![image](https://user-images.githubusercontent.com/8568277/81894643-9eadc000-95f3-11ea-8792-9098961c97cc.png)

**Comment by wtgodbe** [comment]
@hristijankiko do you have a strong reason for using 1.7? In general our recommendation here is to upgrade to 1.8 if possible

**Comment by hristijankiko** [comment]
Due to policies which are outside of our control we are not able to use a Java version later than 1.7. To make this work for us we will have to make modifications to the client ourselves. Since 1.7's end of life has passed long time ago I don't expect you guys to do major refactoring just to meet this requirement but thanks for letting me know.
