### ISSUE TITLE
RDLC report in asp core razor and mvc

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/aspnetcore#21811]
when will rdlc reports be avaialble to asp core razor or mvcapps?. very much needed. thanks

**Comment by javiercn** [comment]
@tnlthanzeel thanks for contacting us.

The component that you mention is not part of ASP.NET Core, so we don't have any specific information we can give you.

@danroth27 maybe you can route this to the right folks to provide an answer?

**Comment by tnlthanzeel** [comment]
> @tnlthanzeel thanks for contacting us.
> 
> The component that you mention is not part of ASP.NET Core, so we don't have any specific information we can give you.
> 
> @danroth27 maybe you can route this to the right folks to provide an answer?

thanks @javiercn
