### ISSUE TITLE
OpenIdConnect Access Token not a valid JWT

### ISSUE THREAD

**Issue by IonutArhire** [dotnet/aspnetcore#21813]
Using .Net Core 2.2 I encounter this issue where the TokenResponseReceivedContext doesn't contain a valid JWT access token:

```
public override Task TokenResponseReceived(TokenResponseReceivedContext context)
        {
            // context.TokenEndpointResponse.AccessToken is not a valid JWT but 
            // context.TokenEndpointResponse.IdToken is and 
            // context.TokenEndpointResponse.RefreshToken can be used to refresh the token and 
            // retrieve a correct access token

            return base.TokenResponseReceived(context);
        }
```
The access token starts with something like: `PAQABAAAAAAAm-06bl`...

It doesn't look like  a JWT token.

When I try to use the access token I get this error:

`CompactToken parsing failed with error code: 80049217`

Here is the configuration for oidc:
```
services.AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, c =>
                {
                    c.AccessDeniedPath = "/Home/Forbidden";
                    // The default setting for cookie expiration is 14 days. SlidingExpiration is set to true by default
                    c.ExpireTimeSpan = TimeSpan.FromHours(1);
                    c.SlidingExpiration = true;
                })
                .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, o =>
                {
                    o.ClientId = azureAdConfigs.ClientId;
                    o.ClientSecret = azureAdConfigs.ClientSecret;
                    o.Authority = "https://login.microsoftonline.com/common/";
                    o.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                    o.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    o.TokenValidationParameters = new TokenValidationParameters {ValidateIssuer = false};
                    o.Events = new MyAuthenticationEvents(_logger, Configuration);
                });
```

Down the authentication pipeline this method is called, setting the resource:

```
public override Task RedirectToIdentityProvider(RedirectContext context)
        {
            context.Options.Resource = "https://graph.microsoft.com";
            return base.RedirectToIdentityProvider(context);
        }
```

My final goal is to obtain an access token from the oidc framework and use that token to make authorized calls to the microsoft graph api. Currently, I can only get the access token by using the refresh token and a call to https://login.microsoftonline.com/common/oauth2/v2.0/token to refresh access token.

Any ideas?

**Comment by blowdart** [comment]
Is there a reason you don't want to use the AAD helpers? 

When you acquire an access token it's for your application, it's not for making calls to graph, you need token exchange at that point. Might I suggest you take a look at the new [Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) packages the AAD folks are previwing? It's aiming to simplify and centralize AAD access, including token exchange and graph calls. This is what we'll be transitioning to in 5.0

**Comment by IonutArhire** [comment]
Sorry for not responding...Thanks for the comment
