### ISSUE TITLE
Blazor ServerSide <Select> 'Required' attribute not working

### ISSUE THREAD

**Issue by chrdlx** [dotnet/aspnetcore#21812]
In a new Blazor project (using the default template) just add this code in any component you want:

```
<form>
    <select required>
        <option value="">TEST</option>
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
    <input type="submit" />
</form>
```

You'll find out that when you press the submit button when "Test" is selected,  the form submits, and it shouldn't because it's "required".  
The only way for this to work is to change the code to this:

```
<form>
    <select required>
        <option value=""></option>
        <option value="1">1</option>
        <option value="2">2</option>
    </select>
    <input type="submit" />
</form>
```

So when you remove the "TEST" text, somehow it works....    in both cases this simple HTML works if you're not using blazor.... Somehow Blazor only sets the select value to "" if there's no text inside the tag.  

So this doesn't work
  `     <option value="">TEST</option>`
but this does
  `    <option value=""></option>`

and both should popup the required browser validation.

Regards!!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. From your example it's only HTML and it's not clear how Blazor is involved. Please share a minimal repro project (ideally as a GitHub repo) so we can investigate this further.

**Comment by chrdlx** [comment]
Blazor is involved, because as I said, that HTML is inside a Blazor component, let me know if my initial explanation about how to repro this with the default blazor server template is unclear.

Add that HTML in any component you like.. Run it,  and you'll se that Browser's required validation doesn't trigger, as it should.  So that "HTML only"  works fine if you're not using Blazor...

How or why Blazor intersects the default behavior of only HTML it's not clear to me too =)

Thanks & Regards!

**Comment by chrdlx** [comment]
This happens in the latest LTS Release of .Net Core,   I just tried the same scenario in .Net Core 5 Preview 6 and this appears to be is resolved....

**Comment by SaebAmini** [comment]
Can confirm this also happens in Blazor Web Assembly 3.2.0

**Comment by captainsafia** [comment]
I believe this issue was resolved with the PR I submitted in https://github.com/dotnet/aspnetcore/pull/22978 which shipped as part of preview6.

I'll close this as solved. I don't believe this meets the par for backporting to 3.1.
