### ISSUE TITLE
LoginPage as Razor Component in Blazor WebAssembly

### ISSUE THREAD

**Issue by Sm1le291** [dotnet/aspnetcore#21826]
Hi! Is it possible to rewrite scaffolded LoginPage as Razor component and use SignInManager there to authorize user?
Now opening Login page takes more time than usual Razor Comonent.  And needs more efforts to support because actually it's rendered on server side. Could you give some examples or ideas about rewriting Login page as usual Razor component

**Comment by javiercn** [comment]
@Sm1le291 thanks for contacting us.

Blazor webassemby uses ASP.NET Core Identity + Open ID Connect to perform login so a redirect is required unless you are willing to perform the authentication within a pop-up window. Unfortunately, that is a feature we only support for Azure Active Directory (B2C) logins.

**Comment by Sm1le291** [comment]
@javiercn thanks for answer! No problem with redirect)
But how to get token and set cookies? How to reproduce PasswordSignInAsync method logic on client side? Is it possible?

**Comment by javiercn** [comment]
@Sm1le291 You would have to define an API endpoint or something like that. Potentially you could set cookies as the response to an API call, but it is not trivial to do in a secure way.

**Comment by Sm1le291** [comment]
@javiercn what exactly happens after entering data into fields is sending login, password and csrf token as a POST query to /Identity/Account/Login if I do so what will be unsafe?

**Comment by javiercn** [comment]
@Sm1le291 I haven't threat modeled something like that and It's not something that I can do ad-hoc. What I'm saying is that if you want to rewrite the UI you need to take all steps to ensure your design is secure. That's it.

**Comment by Sm1le291** [comment]
@javiercn I understand, thanks) I already explain that it's possible from our discussion and this is enough for me.
