### ISSUE TITLE
Blazor WebAssembly: Authorize attribute on Razor Page with Policy causes infinite loop

### ISSUE THREAD

**Issue by rogierhofboer** [dotnet/aspnetcore#21821]
Using the Authorize attrinute on a Blazor WebAssemblyAuthorize Razor Page with a Policy causes infinite loop since Microsoft.AspNetCore.Components.WebAssembly.Authentication version 3.2.0-preview4.20210.8.

Relevant code:

````c#
public static class Policies
{
    public const string TwoFactorAuthenticationRequired = "2FARequired";

    public static AuthorizationPolicy TwoFactorAuthenticationRequiredPolicy()
    {
        return new AuthorizationPolicyBuilder().RequireAuthenticatedUser()
            .RequireClaim("amr", "otp")
            .Build();
    }
}
````

Adding an Authorization Policy in Program.cs:

````c#
builder.Services.AddAuthorizationCore(configure =>
                configure.AddPolicy(Policies.TwoFactorAuthenticationRequired,
                    Policies.TwoFactorAuthenticationRequiredPolicy()));
````

Then when adding in the a razor page:
````c#
@attribute [Authorize (Policy = Policies.TwoFactorAuthenticationRequired)]
````

I've narrowed it down to:
```
Microsoft.AspNetCore.Components.WebAssembly.Authentication

3.2.0-preview3.20168.3 works
3.2.0-preview4.20210.8 through 3.2.0-rc1.20223.4 infinite loop
````
There were quite some changes in this component between March 26, 2020 (3.2.0-preview3.20168.3) and April 16, 2020 (3.2.0-preview4.20210.8) and I was not able to pinpoint the specific change causing this behaviour yet.

For the other Blazor WebAssembly components I can take any version up to and including the 3.2.0-rc1 version.

Browser console logging in case it loops:
````
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
````
Repeats until the browser protects itself from hanging.

Using only:
````
@attribute [Authorize]
 ````

works with all versions without causing a loop.

As far as I can tell the same and valid token comes back from IdentityServer4 (no changes on that side). The needed 2-factor authentication to get the mentioned claim is performed and the claim is available in the token. There are no errors logged on the IdentityServer4 side, just a successful token request.

IdentityServer4 logging:
````
[13:26:38|DBG|logger:Ccv.Sso.IdentityServer.RequestLoggerMiddleware|aid:5c74f5d7-2498-4b18-bbef-0628ab3a3716] Request arrived POST http://localhost:5678/sso/connect/token
[13:26:38|VRB|logger:IdentityServer4.Stores.ValidatingClientStore|aid:5c74f5d7-2498-4b18-bbef-0628ab3a3716] Calling into client configuration validator: IdentityServer4.Validation.DefaultClientConfigurationValidator
[13:26:38|DBG|logger:IdentityServer4.Stores.ValidatingClientStore|aid:5c74f5d7-2498-4b18-bbef-0628ab3a3716] client configuration validation for client testapp succeeded.
[13:26:38|INF|logger:Ccv.Sso.IdentityServer.RequestLoggerMiddleware|aid:5c74f5d7-2498-4b18-bbef-0628ab3a3716] Request handled POST http://localhost:5678/sso/connect/token with status 200 in 35ms
`````

In case of the loop, repeated many times...

**Comment by javiercn** [comment]
@rogierhofboer thanks for contacting us.

Can you provide a minimal repro project that showcases this issue?

Have you updated your App.razor as follows?
```razor
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                    @if (!context.User.Identity.IsAuthenticated)
                    {
                        <RedirectToLogin />
                    }
                    else
                    {
                        <p>You are not authorized to access this resource.</p>
                    }
                </NotAuthorized>
           <AuthorizeRouteView>
```

**Comment by rogierhofboer** [comment]
I didn't, but I have now updated App.razor. It doesn't make a difference.
I will try to come up with a project to reproduce the issue in an isolated setting.
