### ISSUE TITLE
WASM: Microsoft.JSInterop.JSException: Could not find 'AuthenticationService' in 'window'

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#21825]
I have a Blazor WebAssembly (SPA) app I want to add authentication to with Google. I installed the Nuget package as described here https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1#feedback. See below my `Main` method 

``` C#
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);

            builder.Services.AddOidcAuthentication(options =>
            {
                options.ProviderOptions.Authority = "https://accounts.google.com/";
                options.ProviderOptions.ClientId = "MyClientId";
                options.ProviderOptions.ResponseType = "code";
                options.ProviderOptions.RedirectUri = "https://localhost:44399/signin-oidc";

            });

            builder.Services.AddAuthorizationCore();

            builder.RootComponents.Add<App>("app");

            builder.Services.AddBaseAddressHttpClient();

            await builder.Build().RunAsync();
        }
```

### Exception
When I run it this is what I see in the console
![image](https://user-images.githubusercontent.com/12285372/81946444-58de0100-95cd-11ea-9c76-5cddc02d711c.png)

**Comment by javiercn** [comment]
@yopez83 thanks for contacting us.

I think you are likely missing a script reference in your Index.html. Create a new application template with authentication enabled and see the differences within Index.html

**Comment by yopez83** [comment]
Let me check that @javiercn. Thanks

**Comment by mkArtakMSFT** [comment]
Filed the docs issue to add the missing section in the `Overview` page.

**Comment by yopez83** [comment]
@javiercn you were right, I was missing the script and also some razor components. I agree with @mkArtakMSFT, it will be great if this is mentioned in the docs or better yet, to list the steps to create the project. Otherwise, people will continue to assume that just adding the Nuget package and the options to the middleware does the magic.

**Comment by guardrex** [comment]
To address this, I'm going to make our current *Additional resources* section remark ...

> Articles under this Overview provide information on authenticating users in Blazor WebAssembly apps against specific providers.

... into a section to make it clear that implementation guidance is in the individual provider topics with the base case, general OIDC coverage on the auth lib topic (the first one in the node). We have to be careful not to load *Overview* topics with config and implementation guidance. When we've done that in the past, it always ends in *tears* :cry:.

Thanks @yopez83 for calling this out.

**Comment by yopez83** [comment]
Thank you all for such prompt response.
