### ISSUE TITLE
Make AspNetCore.ApiAuthorization.IdentityServer .netstandard compatible

### ISSUE THREAD

**Issue by punjabier** [dotnet/aspnetcore#21820]
I was working on a demo project with clean architecture where I was about to put Context class in Infrastructure, But `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` is not `.netstandard2.1` compatible. So I had to make Infrastructure `netcoreapp3.1`

**Comment by javiercn** [comment]
@punjabier thanks for contacting us.

AspNetCore.ApiAuthorization.IdentityServer depends on ASP.NET Core specific functionality which targets netcoreappxx, so it can't be netstandard.
