### ISSUE TITLE
User with multiple roles fails authorization Blazor Webassembly preview 5

### ISSUE THREAD

**Issue by eduardogdo** [dotnet/aspnetcore#21836]
### User with multiple roles fails authorizations
I create a role based application with Blazor webassembly hosted server authentication. If the user have only one role and the **userinfo** endpoint return role as string everything is fine, but if user have multiples roles and the **userinfo** endpoint return role as string array the authorization fails.

### To Reproduce
This is my configuration in server **Startup.cs**:
```
services.AddDefaultIdentity<User>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

var identity = services.AddIdentityServer()
            .AddApiAuthorization<User, ApplicationDbContext>(options =>
            {
                options.IdentityResources["openid"].UserClaims.Add("role");
                options.ApiResources.Single().UserClaims.Add("role");
            });`

JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");
```
In my client project i have: 
```
<AuthorizeView Roles="Manager, Super Admin">
```
When the user return multiple roles the AuthorizeView fails even if the roles returned are the same evaluated

### Further technical details
- ASP.NET Core 3.1
- Blazor Webassembly preview 5

**Comment by javiercn** [comment]
@eduardogdo thanks for contacting us.

You need to use a custom account to map roles properly when there is more than one. See https://github.com/javiercn/BlazorAuthRoles/blob/master/Client/Program.cs#L23-L24 for details and a working sample
