### ISSUE TITLE
AzureADB2C user flow "Sign up" produces an error in the app

### ISSUE THREAD

**Issue by Krangth** [dotnet/aspnetcore#21837]
### Describe the bug
We started a new web app this week to try out b2c. We didn't have any issue using hooking into the "sign up and sign in" and "password reset" user flows. However, we wanted to put a link on the site to go directly to user registration. We created a "sign up" user flow and got the URL to go directly to this user flow from the "run user flows" screen. The user is able to successfully register their account, but when the user flow redirects back to the app and error is produced. The reply URL is the same one we use is the one we use for the other two flows "/signin-oidc" and is automatically populated in the "run user flow" screen. The error is obscured by the b2c error page (in our app) complaining that the environment is not set to "Development" even though it is. This appears to be a known issue. We enabled debug level log events in the logger and have pasted that below. The only two things that stand out are the GET to /signin-oidc instead of a post which is what the other two user flows do, and the message.State = null which could be related to the GET.

This is the screen that we get the correct end point from
![b2cRunUserFlow](https://user-images.githubusercontent.com/32482832/81970517-a79b9300-95ed-11ea-9264-7b5cd2a2d3fa.png)

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5019/signin-oidc
dbug: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
      Wildcard detected, all requests with hosts will be allowed.
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /signin-oidc does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1000]
      No candidates found for the request path '/signin-oidc'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[2]
      Request did not match any endpoints
dbug: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[10]
      message.State is null or empty.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[4]
      Error from RemoteAuthentication: OpenIdConnectAuthenticationHandler: message.State is null or empty..
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLVO5IP66R7U" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 62.0815ms 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5019/AzureADB2C/Account/Error
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /AzureADB2C/Account/Error does not match a supported file type
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      1 candidate(s) found for the request path '/AzureADB2C/Account/Error'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'Page: /Account/Error' with route pattern 'AzureADB2C/Account/Error' is valid for the request path '/AzureADB2C/Account/Error'
```

### To Reproduce
Just start a new app with .AddAzureADB2C and add a "sign up" only policy.

### Further technical details
- ASP.NET Core version 3.1

**Comment by anurse** [comment]
Can you provide a network trace of the requests the client is making throughout the process? A trace from [Fiddler](https://www.telerik.com/fiddler) would be best.

**Comment by Krangth** [comment]
I attached some screenshots here:
https://drive.google.com/drive/folders/16Y_lGEN0HrYfDdIlPr--FjInCg_UMk-7

Let me know if you need something more detailed.

**Comment by blowdart** [comment]
We really need the actual fiddler file I'm afraid, of the full flow. 

As this could contain secrets, you can email it to me at barry.dorrans@microsoft.com

**Comment by Krangth** [comment]
Okay, I will email you shortly.

**Comment by Krangth** [comment]
Email sent.

**Comment by Tratcher** [comment]
Got it, thanks. 

Oh, your id_token is being returned as a fragment. That should only happen in a SPA app when you're using a client side SDK, that flow doesn't work with AspNetCore's auth handler.
```
Location: https://localhost:5019/signin-oidc#id_token=eyJ0eXAiOiJKV1QiLCJhb...
```

> However, we wanted to put a link on the site to go directly to user registration.

The AspNetCore does not support OIDC logins initiated outside the app. All logins must start with a challenge issued from the auth handler in the application. This establishes some state, makes sure the login is correctly configured, and prevents some kinds of attacks.

So the real question here is how to initiate a challenge from the app that goes directly to the registration page.

**Comment by Tratcher** [comment]
Something like this?
https://github.com/dotnet/aspnetcore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/Areas/AzureADB2C/Controllers/AccountController.cs#L36-L45

Where the policy gets set to GET B2C_1_Just_Sign_Up

**Comment by Krangth** [comment]
Thanks for the information and suggestion. I'll have time to try tomorrow.

**Comment by Krangth** [comment]
Thank you. This suggestion worked correctly. I appreciate the help and patience with my slow replies.
