### ISSUE TITLE
A suitable constructor for type HttpConnectionFactory

### ISSUE THREAD

**Issue by LumiProj** [dotnet/aspnetcore#21839]
Hi,

I am using Core client using Xamarin Forms. Everything is working great but when I change the Xamarin.ios Link option to **"LinkAll"** then I am getting this error on chat initialisation.
I also tried to skip link .net Core library but no luck.

I have already looked into that issue https://github.com/aspnet/SignalR/issues/2933
but I want to publish my app with **LinkAll** option.
Please guide me how can I SKIP LINK the SignalR client.
I tried this setting but still not able to achieve the desired results.

**--linkskip=Microsoft.AspNetCore**

**ERROR**

**A suitable constructor for type 'Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.**

**Comment by BrennanConroy** [comment]
You probably need to customize the linking a bit, check out this doc https://docs.microsoft.com/xamarin/ios/deploy-test/linker?tabs=windows#preserving-code

**Comment by LumiProj** [comment]
Hi,

Well due to WebView issue I had to use LinkAll linking settings but Xamarin Forms sugested another solution to resolve that issue so first I resolved the WebView issue and the change the linking settings back to LinkSdkAssemblies and release the build and everything works fine.
But I use LinkAll link settings so I got the error back.

Anyways I achieved what I was looking for.

Thank you guys.
