### ISSUE TITLE
Support Semantic Colorization for ranges

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#21846]
We provide Semantic colorization right now, but because we supply the colors for a whole document every time it's not terribly efficient. Thankfully [there's a VSCode API for that](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-provider), that we need only implement. If we implement `DocumentSemanticTokensProvider.provideDocumentSemanticTokensEdits` and `DocumentRangeSemanticTokensProvider.provideDocumentRangeSemanticTokens` it should improve performance.

**Comment by ryanbrandenburg** [comment]
CC @gundermanc who might find this useful to review once it's ready.

**Comment by gundermanc** [comment]
@ryanbrandenburg, thanks!

**Comment by ryanbrandenburg** [comment]
This seems to depend on https://github.com/dotnet/aspnetcore/issues/20320. We get a type-load exception out of Omnisharp without the upgrade. I was able to complete the majority of this task and pushed it to a branch (https://github.com/dotnet/aspnetcore-tooling/tree/rybrande/SemanticRange), but since the above issue is a bit more involved I've put doing the finishing touches on it on hold for now. A separate PR will be completed to upgrade OmniSharp, then  we'll be able to merge the above branch (likely with some modifications to react to the new O# version)

**Comment by gundermanc** [comment]
@ryanbrandenburg are you also implementing support for the document (full document + edits/deltas) request messages?

**Comment by ryanbrandenburg** [comment]
@gundermanc and I talked offline, after the above branch we will have support for all three API endpoints/scenarios.
