### ISSUE TITLE
Compiling Razor views in a standard .NET Standard 2.0 class library

### ISSUE THREAD

**Issue by kapetan** [dotnet/aspnetcore#21842]
Hi,

In our setup we run ASP.NET Core 2.2 as part of a .NET Standard 2.0 class library. This library is in return used by a .NET Framework project and a .NET Core console application. So far it has been working great as we're only using the Web API part of ASP.NET (serving only JSON in the controllers). Now we would like to add Razor views, but can't figure out how to include the .cshtml files in the build so they're available for the library consumers.

Class library .csproj file (note sdk is not Microsoft.NET.Sdk.Razor nor Microsoft.NET.Sdk.Web):

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.2.1" />
  </ItemGroup>

</Project>
```

And the application is started with.

```csharp
IWebHost host = new WebHostBuilder()
  .UseKestrel()
  .UseUrls($"http://0.0.0.0:{port}")
  .ConfigureServices(services => {
      services
        ...
        .AddMvc()
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
  })
  .Configure(app => {
      app
        ...
        .UseWebSockets()
        .UseMvc();
  })
  .Build();

await host.StartAsync();
```

Is is possible to include the Razor views as part of the class library?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You will have to target the Razor SDK to be able to include views in your libraries: https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio

As a side note, ASP.NET Core 2.2 is already out of support, so we recommend upgrading to a supported version of the framework: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by kapetan** [comment]
That seems to work, thanks for the help.
