### ISSUE TITLE
I want set different Resource for each Layout

### ISSUE THREAD

**Issue by masoodafar-web** [dotnet/aspnetcore#21840]
hi
I use Blazor WebAssembly 3.2.0 Release Candidate
I want to set different css/js resources for each layout
What should I do?

**Comment by masoodafar-web** [comment]
hello eloo loo lo.........

**Comment by danroth27** [comment]
Hi @masoodafar-web. JS script tags and CSS link tags need to be added using the root page of your app (index.html, or _Host.cshtml). We don't support adding script tags and CSS links in components, including layout components. This is something we are looking at though for .NET 5: #10170.

**Comment by masoodafar-web** [comment]
Please do not respond sporadically :-|
I myself realize that this cannot be done in the component.That's why I asked you question.
I have two layout, one for the store and one for the social network ,in one project. What should I do?
#10170. In which part did this question be answered?

**Comment by danroth27** [comment]
Hi @masoodafar-web. Today you really only have two choices: 1. You can load everything up front in a single host page, or 2. You can split the functionality into separate pages that load different resources. This is simply a limitation with Blazor as it currently stands.
