### ISSUE TITLE
Typing equals doesn't automatically add "|" for component attributes

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#21857]
E.g,
`<Counter IncrementBy=|`

This looks to be an issue with [ProjectionProvider](https://github.com/dotnet/aspnetcore-tooling/blob/e2ce8c9809acd3860e77940a246e722af95495b4/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs#L98) returning null here.

**Comment by ajaybhargavb** [comment]
@TanayParikh is going to take a look at this as all his other items are blocked right now.

**Comment by TanayParikh** [comment]
No automatic `"|"` after `=` is pressed, is no longer an issue as [we removed](https://github.com/dotnet/aspnetcore-tooling/pull/1931/files#diff-ddd1bb48182f84f90a1d4255efd9e971L148-L153) the snippet support as the experience wasn't too consistent across the board between taghelper attributes, directive attributes, parameters, etc: https://github.com/dotnet/aspnetcore/issues/22228

However, that change was made 12 days after you created this issue, which makes me suspect this may be indicative of another issue. Investigating further.
