### ISSUE TITLE
OnInitializedAsync continues lifecycle execution after the first await completes.

### ISSUE THREAD

**Issue by Ellested** [dotnet/aspnetcore#21854]
### Describe the bug
Blazor/Razor components
OnInitializedAsync continues life cycle execution after the first await completes.
This could be an "optimization" thing, but it's pretty confusing if it has to stay like that.
I know that the method will trigger a new render, and everyone will be happy in the end - but I think this is an "unpredictable" behavior that can/will lead to confusion.

### To Reproduce
``` C#
    protected async override Task OnInitializedAsync()
    {
        await GetSomeData();
        // At this moment, the component is rendering and OnAfterRender handlers are called.
        // I would expect the whole method to complete before the lifecycle is continued
        await GetSomeOtherData();
        Console.WriteLine("Now I'm ready to continue...");
    }

....

    protected override void OnAfterRender(bool firstRender) {
        base.OnAfterRender(firstRender);
        Console.WriteLine("OnAfterRender");
    }

    protected override Task OnAfterRenderAsync(bool firstRender) {
        Console.WriteLine("OnAfterRenderAsync");
        return base.OnAfterRenderAsync(firstRender);
    }

```

Got Exceptions? Include both the message and the stack trace
-->

### Further technical details
- ASP.NET Core version
3.1.4
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@Ellested thanks for contacting us.

This is a fundamental behavior of the renderer designed to provide a good experience when performing asynchronous work. Renders can happen at any time they are requested and the logic behind this is that for cases where you are doing asynchronous work, like loading a table with data, you want to be able to display the table header or a similar "loading/progress" indicator before the data has been fully loaded.

This is also a behavior you can control by implementing your own component base class and providing your own semantics.

**Comment by Ellested** [comment]
Thanks for the prompt reply - that's actually really cool :-)

I kind of already knew this would be categorized as an optimization/feature thing, but I still believe this is very confusing to people when they first realize it, and it doesn't contribute, that the handlers are categorized as "life cycle". 

If these handlers are supposed to be called in a more "async/random" way, I would definitely prefer another semantic meaning than life cycle. In the current form it doesn't make any sense to me, that you continue to render stuff, when the initialization is not complete yet - sorry to say that.

If you wan't to make what you describe possible, add another handler that states clearly what it's use is. Now it is "random/unclear" what happens, depending on what task you await first in the OnInitializeAsync, which is not pretty for a framework method.

I already made a test with my own ComponentBase, but I think the nature of this problem is on a level below that, within the handling of tasks, and while you can use Task.WhenAll or similar to work around the problem, it's not what you aim for when writing async code in a sync/sequential fashion.

I will make another try, to make sure I didn't miss anything (and get back with what I find).

Thanks

**Comment by Ellested** [comment]
For the last part, I'm creating a new IComponent, and it seems that it should be possible to write something that works as I would expect. So forget about the last part.

Anyway, I think you should document what goes on in normal methods if you are keeping it as is. 

I mean someone might think they can do JSInterop's in OnAfterRender which needs code to be correctly initialized, and that's going to be a random affair depending on their code order and number of awaits.

**Comment by javiercn** [comment]
@Ellested this is documented [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#handle-incomplete-async-actions-at-render)

**Comment by Ellested** [comment]
Thanks for the pointer, I've been there before many times, and might have overseen some of it, since I've fallen into this "trap". However, I still think the naming is badly chosen. OnInitialize and OnInitializeAsync are fundamentally different in nature. I would rather have OnInitializeAsync named something along "defered initialization/loading" or similar - it does a completely different thing, and you're **not** ensured that anything is initialized at all. By intuition and common practice, you think that OnInitializeAsync is just the async version of OnInitialize, like in every other part of the .net framework. So this deferred loading/init should have it's own semantic naming, as the pattern is different. Just my 5 cents, and I'm still happy no matter what :-)
