### ISSUE TITLE
Inconsistent value for field

### ISSUE THREAD

**Issue by StephanAlexis** [dotnet/aspnetcore#21859]
### Describe the bug
Field value is inconsistent in different part of a blazor page (see code below)

### To Reproduce
When the page load, click once, the `<h3>@step</h3>` shows 2 but the `<p>@step</p>` in `@if (step == 3)` shows 3
```
<h3>@step</h3>
<div>
    @if (step == 1)
    {
        <p>@step</p>
    }
    @if (step == 2) { step++; }
    @if (step == 3)
    {
        <p>@step</p>
    }


    <button class="btn btn-primary" @onclick="click">click</button>
</div>
@code {
    private int step=1;

    private void click()
    {
        step++;
    }

}
```

### Further technical details
.NET Core SDKs installed:
  1.0.0-preview4-004233 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@StephanAlexis thanks for contacting us.

You are mutating the value, that is expected. Razor has the same semantics as C# code, so in your case `@if (step == 2) { step++; }` is incrementing the value from 2 to 3 and later ```    @if (step == 3)
    {
        <p>@step</p>
    }``` is being evaluated to true and displaying the value.

**Comment by StephanAlexis** [comment]
Yes what you is said is true but it's not what the issue is... did you test the code? the incositent is in the first line <h3>@step</h3>  showing 2 when the value of step is 3

**Comment by javiercn** [comment]
The value of @step is 3 only after `step++` has run. At the time `<h3>@step</h3>` is evaluated its value is 2, changing the value later doesn't affect previous evaluations.

**Comment by StephanAlexis** [comment]
thank you for your help. Shouldn't the `step++;` in the `@if (step == 2)` triggers the reevaluation of `<h3>@step</h3>`? in what circumstance does the reevaluation occur? does that mean I should only mutate a field in the `@code` section to trigger a reevaluation as in the click method which does trigger a reevaluation?

**Comment by javiercn** [comment]
No. Razor translates to C# code and `<h3>@step</h3>` is translated to something like `builder.OpenElement("h3"); builder.AddText(step); builder.CloseElement();...`.

Step is an integer, which is a value type and so is passed as a parameter by value, so it is not affected for changes done later in the sequence of statements.
