### ISSUE TITLE
Using SignalR in vscode extension - cannot find module

### ISSUE THREAD

**Issue by Johannes-B-stock** [dotnet/aspnetcore#21864]
### Describe the bug
I am using SignalR in a vscode extension and had some trouble getting it to package with webpack. It seems like there are a bunch of packages missing because SignalR only requests them dynamically so webpack can't detect them. But I need all packages for the packaged extension because when I start the extension in vscode I get the error Error: Cannot find module 'request'.
Right now I'm solving this through patching the SignalR package by replacing all requireFunc with a simple require but it would be nice if there could be a solution so I don't have to patch anymore. 

There is also another issue #10400 that seems to originate from the same issue. Since this is closed maybe this can be closed too but right now I'm still having this issue with version 3.1.3.

### To Reproduce
Create a vscode extension and pack it with webpack like recommended from vscode and try to start it. 

### Further technical details
- SignalR Typescript client v. 3.1.3
- vscode extension

**Comment by BrennanConroy** [comment]
This is fixed in 5.0. You can try out the following workaround instead of patching the SignalR package
https://github.com/dotnet/aspnetcore/issues/10400#issuecomment-506362739
