### ISSUE TITLE
Microsoft.AspNetCore.DataProtection.EntityFrameworkCore release for 2.1 LTS

### ISSUE THREAD

**Issue by leotsarev** [dotnet/aspnetcore#21867]
### Is your feature request related to a problem? Please describe.
I'm trying to migrate complex applications from .NET fw to Core/containers/Linux.
As first step, we are trying to migrate to ASP.NET 2.1 LTS on .NET Framework, while minimizing churn.
Our current solution for key sharing is file share. 
Our target solution for key sharing will be Microsoft.AspNetCore.DataProtection.EntityFrameworkCore (because we won't be able to use SMB protected file shares from inside container). 
Parts of application will be migrated into containers in their own timeframe, so I need a solution that works both from Core applications inside container and ASP.NET 2.1 LTS on .NET FW.

### Describe the solution you'd like
I'd like Microsoft.AspNetCore.DataProtection.EntityFrameworkCore to be released in version that is compatible with 2.1 LTS and do not drag references to unsuppored 2.2 ASP.NET

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We generally don't add features to older releases. You can consider writing your own implementation to handle this.

**Comment by leotsarev** [comment]
If anyone wondered, Microsoft.AspNetCore.DataProtection.EntityFrameworkCore from 2.2 could be successfully recompiled for 2.1 w/o code changes.
We deployed this solution in prod and it works very well
