### ISSUE TITLE
Problem with F# launch.json in webapi project --> issues with IIS express

### ISSUE THREAD

**Issue by jkone27** [dotnet/aspnetcore#21865]
### F# launch.json 
when changing the startup url (e.g. to show swagger page instead of root url),
generated .vs default host configuration for IIS is wrong, and shows un/existing added virtual paths and app pool and causing this IIS error

```
ANCM Multiple In-Process Applications in same Process ASP.NET Core 3
```

i had the issue together with swashbuckle aspnetcore (swagger) package but not sure if related

### To Reproduce

```
dotnet new api --language F#
```
add and configure swashbuckle aspnetcore package as default (with ui)

```
//configure services
        services.AddMvc() |> ignore
        services.AddSwaggerGen(fun c ->
            c.SwaggerDoc("v1", new OpenApiInfo( Title = "Persons API", Version = "v1" ))
        )  |> ignore

//configure
app.UseSwagger() |> ignore
        app.UseSwaggerUI(fun c ->
            c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1")
        ) |> ignore
```

and then change the launch.Settings.json to start with swagger at first page

``` json
"iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:53806/swagger",  //<--------- addition of /swagger causes the bug
      "sslPort": 44326
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Local"
      }
    },
    "TestWebAppFsharp": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Local"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
```

the resulting file in .vs folder used by IIS express to run, has un-needed virtual paths and app pools definition, making the runtime fail with this error :

https://stackoverflow.com/questions/58246822/http-error-500-35-ancm-multiple-in-process-applications-in-same-process-asp-ne

```
.vs\SolutionName\config\applicationhost.config
```

maybe to be forwarded to VisualStudio team/repo?

-->

### Further technical details
- ASP.NET Core version 3.1
- IDE: VS2019

**Comment by mkArtakMSFT** [comment]
@vijayrkn can you please look into this? This is `.vs` related.

**Comment by vijayrkn** [comment]
@bradygaster - You have a sample where this works correct?

**Comment by vijayrkn** [comment]
> @bradygaster - You have a sample where this works correct?

Never mind. Missed the F# part.

**Comment by bradygaster** [comment]
No - haven't done much in the F# space, regrettably. Have you reached out to the F# team?

**Comment by mkArtakMSFT** [comment]
@vijayrkn I'm moving this to the `discussions` milestone. Feel free to open an internal AzDO issue to track it.
