### ISSUE TITLE
CustomAccountFactory throwing exception

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#21879]
My goal was to display the picture and the email once the user is logged-in. So I changed the `LoginDisplay.razor` as follows,
``` C#
<AuthorizeView>
    <Authorized>
        <img class="user-img" title="@((CustomUserAccount)context.User.Identity).Email"/>
        <button class="nav-link btn btn-link" @onclick="BeginSignOut">Log out</button>
    </Authorized>
    <NotAuthorized>
        <a href="authentication/login">Log in</a>
    </NotAuthorized>
</AuthorizeView>
```
My guess was, I needed to add more claims so I can get the picture and the email. I may be doing it all wrong, but I thought this could be the [way](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#customize-the-user). Here is the error I get,

![image](https://user-images.githubusercontent.com/12285372/82070479-cc057700-96a2-11ea-94a3-50a76267aef8.png)

### CustomAccountFactory
``` C#
    public class CustomAccountFactory : AccountClaimsPrincipalFactory<CustomUserAccount>
    {
        public CustomAccountFactory(NavigationManager navigationManager, IAccessTokenProviderAccessor accessor) : base(accessor)
        {}

        public override async ValueTask<ClaimsPrincipal> CreateUserAsync(CustomUserAccount account, RemoteAuthenticationUserOptions options)
        {
            var initialUser = await base.CreateUserAsync(account, options);

            if (initialUser.Identity.IsAuthenticated)
            {
                ((ClaimsIdentity) initialUser.Identity).AddClaim(new Claim(ClaimTypes.Email, account.Email));
                ((ClaimsIdentity) initialUser.Identity).AddClaim(new Claim(ClaimTypes.Uri, account.Picture));
            }

            return initialUser;
        }
    }
```
### Main
``` C#
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient {BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)});

            builder.Services.AddOidcAuthentication<RemoteAuthenticationState, CustomUserAccount>(options =>
            {
                builder.Configuration.Bind("Local", options.ProviderOptions);
            }).AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, CustomUserAccount, CustomAccountFactory>();

            await builder.Build().RunAsync();
        }
```

**Comment by javiercn** [comment]
@yopez83 thanks for contacting us.

You are casting a ClaimsPrincipal to your CustomUserAccount type, that's not how this is intended to work. 

AuthorizeView always uses a claims principal, and in your case you need to call something like `context.User.Identity.FindFirst(ClaimTypes.Email)?.Value`

**Comment by yopez83** [comment]
See what I get,

'IIdentity' does not contain a definition for 'FindFirst' and no accessible extension method 'FindFirst' accepting a first argument of type 'IIdentity' could be found (are you missing a using directive or an assembly reference?)

**Comment by yopez83** [comment]
If I change the `AddOidcAuthentication` options to,

``` C#
            builder.Services.AddOidcAuthentication(options =>
            {
                options.ProviderOptions.DefaultScopes.Add("email");
                builder.Configuration.Bind("Local", options.ProviderOptions);
            });
```
and the `LoginDisplay.razor` to,
``` C#
<AuthorizeView>
    <Authorized>
        Hello, @context.User.Identity.Name!
        <button class="nav-link btn btn-link" @onclick="BeginSignOut">Log out</button>
    </Authorized>
    <NotAuthorized>
        <a href="authentication/login">Log in</a>
    </NotAuthorized>
</AuthorizeView>
```
everything works, please note I added the **email** scope.

Now, upon checking the SessionStorage from the browser, I see a set of Standard Claims was stored, and I have **picture** and **email**. My goal is to display those values at the `LoginDisplay.razor` component. However, see the only properties available,

![image](https://user-images.githubusercontent.com/12285372/82082039-4fc85f00-96b5-11ea-86d2-ee6a9abb6eef.png)

**Comment by javiercn** [comment]
@yopez83 I was typing out the C# in the browser, the exact sentence is not that, but it should be something close. This is the thing you're looking for https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal.findfirst?view=netcore-3.1#System_Security_Claims_ClaimsPrincipal_FindFirst_System_String_

**Comment by yopez83** [comment]
I was doing it wrong. Instead of `Identity.` I should do `User.`

**Comment by yopez83** [comment]
@javiercn, no compilation errors this time. However, `@context.User.FindFirst(ClaimTypes.Email)?.Value` displays null. There should be something missing since I see a claim stored with the email.

![image](https://user-images.githubusercontent.com/12285372/82093086-70e67b00-96c8-11ea-9569-b570ddbc7d83.png)

**Comment by javiercn** [comment]
@yopez83 just list the claims on the principal and pass the appropriate key to retrieve it?

**Comment by yopez83** [comment]
Never mind @javiercn , I got it to work. I just had to wire back up the `CustomAccountFactory` and everything worked. Here are is the result.
### Main
``` C#
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddTransient(sp => new HttpClient {BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)});

            builder.Services.AddOidcAuthentication<RemoteAuthenticationState, CustomUserAccount>(options =>
            {
                options.ProviderOptions.DefaultScopes.Add("email");
                builder.Configuration.Bind("Local", options.ProviderOptions);
            }).AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, CustomUserAccount, CustomAccountFactory>();

            await builder.Build().RunAsync();
        }
```
### CustomAccountFactory
``` C#
    public class CustomAccountFactory : AccountClaimsPrincipalFactory<CustomUserAccount>
    {
        public CustomAccountFactory(NavigationManager navigationManager, IAccessTokenProviderAccessor accessor) : base(accessor)
        {}

        public override async ValueTask<ClaimsPrincipal> CreateUserAsync(CustomUserAccount account, RemoteAuthenticationUserOptions options)
        {
            var initialUser = await base.CreateUserAsync(account, options);

            if (initialUser.Identity.IsAuthenticated)
            {
                ((ClaimsIdentity) initialUser.Identity).AddClaim(new Claim(ClaimTypes.Email, account.Email));
                ((ClaimsIdentity) initialUser.Identity).AddClaim(new Claim(ClaimTypes.Uri, account.Picture, ClaimValueTypes.String));
            }

            return initialUser;
        }
    }
```
### LoginDisplay.razor
``` C#
<AuthorizeView>
    <Authorized>
        <img src="@context.User.FindFirst(ClaimTypes.Uri)?.Value" 
             class="user-img" 
             title="@context.User.FindFirst(ClaimTypes.Email)?.Value"/>
        <button class="nav-link btn btn-link" @onclick="BeginSignOut">Log out</button>
    </Authorized>
    <NotAuthorized>
        <a href="authentication/login">Log in</a>
    </NotAuthorized>
</AuthorizeView>
```
