### ISSUE TITLE
start more than one dotnet core app using "dotnet"

### ISSUE THREAD

**Issue by brucezlata** [dotnet/aspnetcore#21875]
HI,
I am trying to run two *.dll which are dotnet core apps with the same endpoint urls. Can I?
for exmaple such CLI:
dotnet 1.dll 2.dll

any solution?

**Comment by javiercn** [comment]
@brucezlata thanks for contacting us.

I think you are looking at something like [tye](https://github.com/dotnet/tye), which can be used to orchestrate multiple app launches.

I don't think dotnet has that capability; if you want to ask for a feature I would recommend you file an issue in [dotnet/sdk](https://github.com/dotnet/sdk)

**Comment by Tratcher** [comment]
> with the same endpoint urls

Regardless of launching two processes, sharing urls is an issue. Two processes can't normally bind to the same endpoint. There are some features in the HttpSys server to allow this, but if you're using Kestrel you'll need a proxy to share the port.

**Comment by brucezlata** [comment]
@javiercn @tracychms thank you for reply.
