### ISSUE TITLE
Multiple blazor-client apps in single server.How use endpoints.MapFallbackToFile("index.html")

### ISSUE THREAD

**Issue by parad74** [dotnet/aspnetcore#21872]
How use endpoints.MapFallbackToFile("index.html") if there are multiple blazor-client with difference base?

Found several issues and read documentations. But didn't succeed.
https://github.com/dotnet/aspnetcore/issues/17997
https://github.com/dotnet/aspnetcore/issues/5659
https://github.com/dotnet/aspnetcore/issues/19744
https://github.com/dotnet/aspnetcore/issues/12705

Help to find how it use?
Thenks

**Comment by javiercn** [comment]
@parad74 thanks for contacting us.

There is a sample here https://github.com/javiercn/BlazorMultipleApps and we have an ongoing issue to add this to the docs.
