### ISSUE TITLE
Blazor wasm app EF (sqlite) include include child list fails

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21882]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1008513/blazor-wasm-app-ef-sqlite-include-include-child-li.html)._

---
Using a Blazor wasm app with aspnet core backen using EF (with a local sqlite file) to fetch a list of objects where each object (`MeasurementSite`) has a list of subobjects (`MapCornerCoordinates`) with http get command doesn't seem to work (Chrome reports error 500 response):

MeasurementSitesController:

```c#        
private readonly ModelContext _context;

[HttpGet]
public async Task<ActionResult<IEnumerable<MeasurementSite>>> GetMeasurementSite()
{
    var sites = await _context. MeasurementSite.Include(s => s.MapCornerCoordinates). ToListAsync();
    return sites;
}
```

SitesList.razor:

```
@code {
    private MeasurementSite[] sites;
    protected override async Task OnInitializedAsync()
    {
        sites = await Http.GetJsonAsync<MeasurementSite[]>("api/MeasurementSites");
    }
}
```

If I remove the `. Include(s => s.MapCornerCoordinates)` from the `var sites = await _context. MeasurementSite.Include(s => s.MapCornerCoordinates). ToListAsync();`call it works but I do not get the MapCornerCoordinates along.

In a desktop console program I can use the `. Include` method and that works as I thought it would.

---
#### Visual Studio Feedback System on 4/27/2020, 05:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### erth on 4/28/2020, 01:10 PM: 

(private comment, text removed)
#### erth on 4/28/2020, 01:13 PM: 

The problem is that I cannot get anything from the server even calling just the httpget:

```c#
sites = await Http.GetFromJsonAsync<MeasurementSite[]>("api/MeasurementSites");
```

(controller)

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DynamicNoiseMap.Shared;
using Microsoft.VisualBasic;
using BlazorLeaflet;

namespace DynamicNoiseMap.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MeasurementSitesController : ControllerBase
    {
        // ERTH: In order to be able to use the controller it needs a ctor with interface parameter
        // and
        // that interface needs to be registered in Startup.ConfigureServices()
        // services.AddScoped&lt;IModelContext, ModelContext&gt;();

        private readonly ModelContext _context;

        public MeasurementSitesController(IModelContext context) // needs to be an interface...
        {
            _context = (ModelContext)context;
        }

        // GET: api/MeasurementSites
        [HttpGet]
        public async Task&lt;ActionResult&lt;IEnumerable&lt;MeasurementSite&gt;&gt;&gt; GetMeasurementSite()
        {
            var sites = await _context.MeasurementSite.ToListAsync();
            
            //var sites = await _context.MeasurementSite.ToListAsync();
            //var mapcorners = await _context.MapCornerCoordinate.ToListAsync();
            //foreach (var s in sites)
            //{
            //    s.MapCornerCoordinates = mapcorners.Where(c =&gt; c.MeasurementSiteID.Equals(s.ID)).ToList();
            //}
            return sites;
        }
    }
}
```

But still the console app can get the (correct) data (using the QueryExamples method in the database creator program above.

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
> Chrome reports error 500 response

Can you include the exception stack trace? The request body should include it or you could attach a debugger to the server application.
