### ISSUE TITLE
Support dynamic cultures

### ISSUE THREAD

**Issue by hishamco** [dotnet/aspnetcore#21889]
AFAIK ASP.NET Core since the 1st version localization APIs don't support adding cultures at runtime, while there 're many requests and scenarios that require this feature, so it would be nice to add such feature, although the `resx` files require compilation, but there 're other provider such as: Portable Objects, Json .. etc doesn't require compilation at all

/cc @pranavkm @ryanbrandenburg @rynowak

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hishamco.
This is not something we plan do invest in.

**Comment by hishamco** [comment]
Is there a workaround for such thing, because different data sources such as databases, files or even resource managers (resx) may have different culture that could be added at runtime, I need a solution without restart the app
