### ISSUE TITLE
CS0103 The name '__builder' does not exist in the current context   BlazorAppDebugBug  Index.razor.g.cs

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#21883]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1023529/cs0103-the-name-builder-does-not-exist-in-the-curr.html)._

---
Visual Studio Preview Version 16.6.0 Preview 6.0 Windows 10
I was trying to build a small sample to illustrait the debugger not working properly and got this error which i believe should not occur when trying to compile. Steps I did were using the Blazor server template to generate the project, I only changed index.razor. That Blazor program is attached.

---
#### Visual Studio Feedback System on 5/8/2020, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by RaheelASI** [comment]
Hi I am getting below error while trying to insert HTML tag in for loop
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name '__builder' does not exist in the current context	BlazorAppComponent

**Comment by allisonchou** [comment]
Removing tooling tag as this seems to be a compiler issue.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
