### ISSUE TITLE
[Blazor] Ability to add a callback on the default onchange when Using @bind

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#21892]
### Is your feature request related to a problem? Please describe.
When working with Entity Framework Core in Blazor, it would be convenient to be able to bind to a tracked property so that when the element representing the property is changed, the change can be saved via Entity Framework Core as well.

### Describe the solution you'd like
```
<input type="checkbox" id="checkboxIsFavorite" @bind="User.IsFavorite" @onchange-callback="SaveContext">

@code {
    [Parameter]
    public Record User { get; set; } // this is already being tracked by EF Core

    // this function is called after the default onchange completes
    private async Task SaveContext() {
        // code that simply saves the db context, which will save the change to User.IsFavorite
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is currently not supported, but we plan to add support for this as part of https://github.com/dotnet/aspnetcore/issues/14365
