### ISSUE TITLE
RazorComponent failing to update from Signalr event

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#21897]
### Describe the bug
creating blazor server side application with a razor component/page that listens to events/messages from a signalr hub to update the component state fails to render.

### To Reproduce
create a razor component/page that listens to signalr events; the event fires and the state is updated yet the component/page fails to be updated.

```
@page "/"
@using Microsoft.AspNetCore.SignalR.Client
@inject NavigationManager NavigationManager

<h1>Hello, world!</h1>
Welcome to your new app.

<input type="text" @bind-value="@signalDateTime" />

@code {
    HubConnection hubConnection;
    string signalDateTime;
    protected override void OnInitialized()
    {
        base.OnInitialized();
    }
    protected override async Task OnInitializedAsync()
    {
        hubConnection = new HubConnectionBuilder()
            .WithUrl(NavigationManager.ToAbsoluteUri("/clockHub"))
            .Build();

        hubConnection.On<DateTime>("clockTick", onClockTick);

        await hubConnection.StartAsync();
    }
    protected async Task onClockTick(DateTime dateTime)
    {
        signalDateTime = dateTime.ToString();
        StateHasChanged();

        await Task.CompletedTask;
    }
}

```

**Comment by pranavkm** [comment]
Perhaps you're missing an `InvokeAsync` - https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state

**Comment by grahamehorner** [comment]
@pakrym thanks for the quick reply, I have tried wrapping the onClockTick code inside of the InvokeAsync this seem to have zero impact and Blazor still fails to update the client browser UI as I would expect.  I will create a repo showing the behaviour for reference as I think this is a use case developers would/could expect to have implementations outside of just using the in-built Blazor SignalR hub  ie. I'm hoping to hook mobile applications, web blazor applications and IoT devices via a SignalR hub

**Comment by davidfowl** [comment]
@grahamehorner can you show your code with invoke?
