### ISSUE TITLE
Detect drag-and-drop cancellation when user pressed the Escape key

### ISSUE THREAD

**Issue by arviedelgado** [dotnet/aspnetcore#21908]
### Describe the bug
On a drag and drop operation, the user can cancel the operation by pressing the `Escape` key.
The value of `DragEventArgs.DataTransfer.DropEffect` will be `none` in the `@ondragend` event.
However, `DragEventArgs.DataTransfer.DropEffect` is `null`.

### To Reproduce
``` C#
<div ondragover="event.preventDefault();" style="...">
    <div draggable="true" @ondragend=OnDragEnd style="..." />
</div>

private void OnDragEnd(DragEventArgs e)
{
	if (e.DataTransfer.DropEffect == "none") // but DropEffect is null
	{
		// the user cancelled the drag operation,
		// by pressing Escape key.
	}
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. At the moment, Drag & Drop is not supported out of the box, so you have to write your own JSInterop logic to handle this, hence handling the `Escape` key.

We do plan to bring support for Drag & Drop as part of https://github.com/dotnet/aspnetcore/issues/18754
