### ISSUE TITLE
Allow the usage of the ExceptionHandlerMiddleware without any configurations

### ISSUE THREAD

**Issue by ivanhoe-k** [dotnet/aspnetcore#21902]
### Is your feature request related to a problem? Please describe.
Relates to [ #21893](https://github.com/dotnet/aspnetcore/issues/21893)

### Describe the solution you'd like
The ExceptionHandlerMiddleware can be used by calling different extension methods that are defined in the ExceptionHandlerExtensions. One of those methods is parameterless that in my opinion should mean the ability to use it without any configurations. But it is not possible right now due to the exception I mentioned here [ #21893](https://github.com/dotnet/aspnetcore/issues/21893). If I understand correctly before using the parameterless version of the UseExceptionHander() extension method we should also provide options in ConfigureServices. I would say it's a little bit tricky and it would be great to allow not to specify any configurations in order to have the opportunity to use the default logic of the ExceptionHandlerMiddleware (logging, adding exception handler features to the response, etc.). 

I come up with this small suggestion because I do really need this feature in my project. The middleware handles unhandled exceptions out of the box and does everything to handle it properly (no CORS errors on the client side when the unhandled exception occurs [#2378](https://github.com/dotnet/aspnetcore/issues/2378)). I know that we can create our own middleware or define some stubs, like this

``` C#
app.UseExceptionHandler(
                errorApp => errorApp.Run(_ => Task.CompletedTask));
```
It doesn't look like the right way and in case of creating custom middlewares it looks to me like code duplication, the same as creating own exception when there is already suitable one out of the box.

**Comment by Tratcher** [comment]
How does that empty errorApp address the CORS issue? Or is that an additional problem you're trying to address?

With that empty erroApp you'd get almost the same behavior if you removed the middleware and used the server's default exception handling logic.
