### ISSUE TITLE
Unload AssemblyLoadContext int AspNetCore.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#21906]
I generate a controller dynamically at run time. I cannot uninstall AssemblyLoadContext. Can the official provide a way to remove references?

Steps:

1、 Run WebProject.
2、Click a button and generate  a controller named FooController. And this controller store in  a AssemblyLoadContext named "FooDomain".
3、Visit `https://localhost/api/Foo`, It works well.
4、Then I use `ApplicationPartManager` and `IActionDescriptorChangeProvider` to remove the controller.
5、Unload the `FooDomain`.  It not work. This domain can't be unloaded.

I know that references to assemblies or methods are keeping in many places within asp.netcore, but it is too difficult for me to remove these references. Can you provide a `method /  interface ` or specification to solve this problem?

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

/cc @davidfowl

**Comment by davidfowl** [comment]
@NMSAzulX we haven't done the work to make sure that all of the memory associated with an assembly goes away when it's unloaded. It's non trivial and low priority for the team. See https://github.com/dotnet/aspnetcore/issues/21744 for a similar issue.

**Comment by NMSAzulX** [comment]
@mkArtakMSFT @davidfowl  Thanks. Now, restarting the service may be the only solution.
At the same time, we hope that officials will pay more attention to the requirements of dynamic compilation in the future. :）Good luck.
