### ISSUE TITLE
Copy /Paste of code causes compile error no matter what (almost)

### ISSUE THREAD

**Issue by talldaniel** [dotnet/aspnetcore#21917]
### Describe the bug
I copied all of the code from a Component and pasted it into a blank component.  It creates three versions of these two errors for a total of six errors.  
Error	CS1513	} expected	Miscellaneous Files	  
Error	CS1022	Type or namespace definition, or end-of-file expected	 

I then removed all lines of code except for this one about popup, and it still creates the same errors.  
` 
@{
        private bool popup { get; set; }
}`

### To Reproduce
 
What steps can we follow to reproduce the issue?

1.  Create a component with both markup and code.
(I get an error about the .vssscc could not be found in your workspace, or you do not have permission to access it when creating a new component.)
2.  Make sure that component works correctly and compiles.
3. Create  a second empty component.
4. Paste the code from the working component to this new component and attempt to compile.
5.  When that fails, remove all but one line inside the code section and it still fail.
6.  Try various permutations to prove that somehow this file is tainted and not even the simplest single line of code will compile.
 

### Further technical details
- ASP.NET Core version using the latest version of VS as of 5/15/2020 and blazor server side using Windows 10 Pro  (system just built yesterday so everything was fresh)
 
### Work around
step 3B Copy code into Notepad
Step 3C Save Notepad (not sure if required)
Step 3D Copy the text in Notepad and continue to step 4.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
