### ISSUE TITLE
Is authentication in blazor wasm supported via popup or iframe for PWA?

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/aspnetcore#21919]
### Is your feature request related to a problem? Please describe.
The current implementation of authentication in blazor wasm application is not very well suited for an installed PWA (in standalone mode) because the navigation happens in main browser window/webview and hitting back to close the application will go through the authentication pages.

### Describe the solution you'd like
I would like to be able to configure authentication to use an iframe/popup (if it works in standalone PWA case).

**Comment by javiercn** [comment]
@nvmkpk thanks for contacting us.

The authentication support already uses an iframe to try and authenticate the user silently in case it was authenticated.

We don't support authenticating the user via a pop up.

Authentication works fine whether you have a PWA installed or not and in case you need to make the auth bits work offline, the recommended approach is to implement your own UserAccountClaimsPrincipal that stores the last authenticated user in local/session storage and returns it from there when you detect the app is offline and can't re-authenticate.

**Comment by nvmkpk** [comment]
>The authentication support already uses an iframe to try and authenticate the user silently in case it was authenticated.
Do you mean to say it uses iframe to check if the user was previously logged in? If that is the case then no that is not what I am asking for. I would like the initial login to happen in the iframe so that once it is removed, hitting back would not take the user back into the login pages..

>Authentication works fine whether you have a PWA installed or not
I am not saying it does not work. I am only saying after login if the user hits the back button I don't want the user to go through the login pages.

**Comment by nvmkpk** [comment]
@javiercn could you please provide an update on this?
