### ISSUE TITLE
dotnet new blazorwasm --hosted

### ISSUE THREAD

**Issue by crispsimpcrispy** [dotnet/aspnetcore#21911]
### Bug
HTTP Error 500.0 - ANCM In-Process Handler Load Failure, when using Blazor WebAssembly App which is ASP.NET Core hosted. 

### To Reproduce
1. Microsoft Visual Studio Community 2019 Version 16.5.4
2. Create new Blazor App
3. Select Blazor WebAssembly App and select ASP.NET Core Hosted
4. Build and Publish BlazorApp.Server
5. Web deploy to Thirdparty Windows Sever
6. HTTP Error 500.0 - ANCM In-Process Handler Load Failure encountered when accessing domain

.NET Core SDKs installed:  
  3.1.201 [C:\Program Files\dotnet\sdk]

### Fix One
change to OutOfProcess in the .csproj file before publishing
```csharp
<PropertyGroup>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
</PropertyGroup>
```

### Fix Two
Amend the WebConfig file on the webserver from
```csharp
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\BlazorApp.Server.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
```
Change from modules="AspNetCoreModuleV2" to modules="AspNetCoreModule"
```csharp
﻿<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\BlazorApp.Server.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
```
### Comments
is there anyway to leverage InProcess Hosting

**Comment by BrennanConroy** [comment]
Could you follow the [troubleshooting docs](https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#troubleshoot-on-iis) and share your logs?
