### ISSUE TITLE
Problem getting data from local storage with blazor for large files

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#21929]
I am using the function
var serialisedData = await js.InvokeAsync<string>("localStorage.getItem", key);
which interops with javascript.  It works fine for small amount of information.  However, if there is a large amount of information being returned it hangs.
For example, if i am retrieving a list of 24 objects, it works.  However, if the list contained over 100 objects for example, it hangs.  The data for sure saves with no problem.  However, upon retrieving, it does not even make it past the invokeasync function.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There are certain performance best-practices to follow when using JSInterop. The following article should help you with that: https://docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1#avoid-javascript-interop-to-marshal-data

**Comment by mrpmorris** [comment]
https://docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1#use-synchronous-and-unmarshalled-js-interop-apis-where-appropriate

**Comment by musictopia2** [comment]
I was using this with server side not web assembly.  The links are helpful for web assembly.  However, web assembly has not been officially released yet.  With server side, those options mentioned are not available.  Or is a person forced to wait for web assmebly to come out to see if it resolves it.  It would mean if its a server app, then still can't retrieve much data from local storage.  When testing, I was able to step through the javascript and can see i was able to retrieve it.  Its only getting stuck going from the javascript function to the c# again.

**Comment by Kylar182** [comment]
So essentially Blazor will never be able to handle large files? Or be a large file? I'm having issues where it just dies right about 50 MB total Application size. We've been using JSInterOp with IndexedDB but it looks like the project is dead until Blazor can do over 50MB. I'm guessing this is a WASM thing?
