### ISSUE TITLE
[Blazor Wasm] Update service worker

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#21926]
I have a PWA Blazor Wasm app with the DNS hosted on Cloudflare.
The issue I am getting is every time I am publishing a change to the app it seems that still the old version is being displayed in my browser. I investigated this further, even by manually and programatically invalidating Cloudflare's cache after publish but with no real effect.

Today I did a new publish and I started to look deeper into this issue because it is very annoying. What I saw is, even if I purge Cloudflare's cache the browser still delivers the content from the service worker installed in it. 

After I manually unregistered service worker (Chrome dev tools > Application > Service Workers) and reload the app all went good.

Is there a way to update service worker after a build/publish?

**Comment by MarkusRodler** [comment]
Does your app reports problems on the console that it has problems with subresource integrity? I had a similar problem because my assets are cached very long and the service worker does not request the updated ones because the url did not change.
I have written about that problem here in more detail: https://github.com/dotnet/aspnetcore/issues/17036

**Comment by mihaimyh** [comment]
> Does your app reports problems on the console that it has problems with subresource integrity? I had a similar problem because my assets are cached very long and the service worker does not request the updated ones because the url did not change.
> I have written about that problem here in more detail: https://github.com/dotnet/aspnetcore/issues/17036

No, I don't see this behavior.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please share the URL where your website is deployed? We may be able to extract some usuful information from there.

**Comment by mihaimyh** [comment]
> Thanks for contacting us.
> Can you please share the URL where your website is deployed? We may be able to extract some usuful information from there.

Sure, https://movingpicturesevents.ro/

Thank you.

**Comment by mihaimyh** [comment]
Just as a note, the app updated itself after few days. Can we control when the update is being done, for example to do it much often?

**Comment by SteveSandersonMS** [comment]
@mihaimyh You can change your service worker logic to anything you want. For information about the APIs available, see https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

Note that by default, the browser will check for updated and install them in the background on every page load. If in your case this was delayed by several days, the only explanation I can give is that something in your server-side host was continuing to serve older content for some period. You mention you're using Cloudflare so maybe they can help you with ensuring you're always service up-to-date content.
