### ISSUE TITLE
Use PipeWriter to write StaticFiles

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#21923]
We can avoid the extra copy and pinning when using Kestrel and just write the `FileStream` to the underlying `PipeWriter` directly.

**Comment by Tratcher** [comment]
This is the API to replace:
https://github.com/dotnet/aspnetcore/blob/5cfebf260f979948039d3e6f724d283f8a3a348d/src/Http/Http/src/SendFileFallback.cs#L22
https://github.com/dotnet/aspnetcore/blob/5a0c097ad4b0aef756cd92f2d593cda3fa223748/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.FeatureCollection.cs#L330-L333
https://github.com/dotnet/aspnetcore/blob/5cfebf260f979948039d3e6f724d283f8a3a348d/src/Http/Http/src/StreamResponseBodyFeature.cs#L89-L96

**Comment by Kahbazi** [comment]
Do you take PR for this?

Does this also need to change?
https://github.com/dotnet/aspnetcore/blob/b56f84131af2e1ece61241a016e191f5f2fe3fc0/src/Mvc/Mvc.Core/src/Infrastructure/FileResultExecutorBase.cs#L361

**Comment by davidfowl** [comment]
Static files still has custom logic to call a custom copy to async implementation as well

**Comment by davidfowl** [comment]
@Kahbazi  yes that also needs to change.

**Comment by jkotalik** [comment]
@davidfowl should we close this? You attempted to do this in https://github.com/dotnet/aspnetcore/pull/24851, but it was less performant.

**Comment by davidfowl** [comment]
Yes, I'll open a new, more general issue about static files performance improvements.
