### ISSUE TITLE
Polymorphic model binding in AspNetCore 3.1 Api

### ISSUE THREAD

**Issue by smadurange** [dotnet/aspnetcore#21939]
Hi, I'm trying to get custom model binding working with an api project following the guide [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#default-model-binder-limitations). However, it's really not helping.

I'm pretty much copying and pasting that code in an api project but it's not working. I suspect it's to do with the value provider not filling up the properties in the binding context because I only see `action` and `controller` keys in the `Items`. But I can't find a good resource to debug this issue anywhere.

My controller:
```
[ApiController]
[Route("test")]
public class TestController : ControllerBase
{
    [HttpPost]
    public IActionResult Test([FromBody] Device dto)
    {
        return Ok();
    }
}
```
Here, the `dto` is always `null`. Model binders and the entity classes are:

```
public abstract class Device
    {
        public string Kind { get; set; }
    }

    public class Laptop : Device
    {
        public string CPUIndex { get; set; }
    }

    public class SmartPhone : Device
    {
        public string ScreenSize { get; set; }
    }

    public class DeviceModelBinderProvider : IModelBinderProvider
    {
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            if (context.Metadata.ModelType != typeof(Device))
            {
                return null;
            }

            var subclasses = new[] { typeof(Laptop), typeof(SmartPhone), };

            var binders = new Dictionary<Type, (ModelMetadata, IModelBinder)>();
            foreach (var type in subclasses)
            {
                var modelMetadata = context.MetadataProvider.GetMetadataForType(type);
                binders[type] = (modelMetadata, context.CreateBinder(modelMetadata));
            }

            return new DeviceModelBinder(binders);
        }
    }

    public class DeviceModelBinder : IModelBinder
    {
        private Dictionary<Type, (ModelMetadata, IModelBinder)> binders;

        public DeviceModelBinder(Dictionary<Type, (ModelMetadata, IModelBinder)> binders)
        {
            this.binders = binders;
        }

        public async Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var modelKindName = ModelNames.CreatePropertyModelName(bindingContext.ModelName, nameof(Device.Kind));
            var modelTypeValue = bindingContext.ValueProvider.GetValue(modelKindName).FirstValue;

            IModelBinder modelBinder;
            ModelMetadata modelMetadata;
            if (modelTypeValue == "Laptop")
            {
                (modelMetadata, modelBinder) = binders[typeof(Laptop)];
            }
            else if (modelTypeValue == "SmartPhone")
            {
                (modelMetadata, modelBinder) = binders[typeof(SmartPhone)];
            }
            else
            {
                bindingContext.Result = ModelBindingResult.Failed();
                return;
            }

            var newBindingContext = DefaultModelBindingContext.CreateBindingContext(
                bindingContext.ActionContext,
                bindingContext.ValueProvider,
                modelMetadata,
                bindingInfo: null,
                bindingContext.ModelName);

            await modelBinder.BindModelAsync(newBindingContext);
            bindingContext.Result = newBindingContext.Result;

            if (newBindingContext.Result.IsModelSet)
            {
                // Setting the ValidationState ensures properties on derived types are correctly 
                bindingContext.ValidationState[newBindingContext.Result] = new ValidationStateEntry
                {
                    Metadata = modelMetadata,
                };
            }
        }
    }
```

**Comment by smadurange** [comment]
This issue seems to be a problem with value provider for "application/json". When I post it as form data, my `dto` is not `null`. But when I post data as "application/json", I get `null`. Please advise. Does this mean I need to implement a custom value provider for json if I need to leverage `IModelBinder`?

**Comment by pranavkm** [comment]
@smadurange formatters, which is what's used when JSON data, do not interact with the rest of the model binding \ value provider subsystem. For this scenario, you'd have to write a converter for the JSON library that you're using:

* https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to
* https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm

**Comment by smadurange** [comment]
@pranavkm Thanks for the information. I implemented a custom Json converter for NewtonSoft Json as below:

```
public class CustomConverter : Newtonsoft.Json.JsonConverter
{
    public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
    {
        throw new NotImplementedException();
    }

    public override object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
    {
        throw new NotImplementedException();
    }

    public override bool CanConvert(Type objectType)
    {
        return objectType.IsAssignableFrom(typeof(Device));
    }
}
```

And registered in DI like so

public void ConfigureServices(IServiceCollection services)
```
{
    services.AddControllers(o => { o.ModelBinderProviders.Insert(0, new DeviceModelBinderProvider()); })
        .AddNewtonsoftJson(o => o.SerializerSettings.Converters.Insert(0, new CustomConverter()));
}
```

However, when deserializing the DTO, this formatter is not getting called. It does get called when serialising the response. My request from Postman looks like

```
curl --location --request POST 'http://localhost:5000/test' \
--header 'Content-Type: application/json' \
--data-raw '{
    "ScreenSize": "1",
    "Kind": "SmartPhone"
}'
```

**Comment by pranavkm** [comment]
> It's not very transparent what happens to the request body and I can't see how/where to start debugging an issue like this

You should be able to turn up Debug logs and see what formatters \ model binders are being used. You could start off by trying to make sure this works without MVC involved with vanilla Newtonsoft.Json.

**Comment by smadurange** [comment]
Thanks for the advice and the pointers. Decided to side step the issue by not using a polymorphic model. But will try this.

**Comment by Goxiaoy** [comment]
It seems when using form data
the created newBindingContext contains 3 value providers
![image](https://user-images.githubusercontent.com/8577611/89302280-370c8b80-d69d-11ea-8092-b079d1c56477.png)
when using json, it has only one value provider
![image](https://user-images.githubusercontent.com/8577611/89302435-658a6680-d69d-11ea-90a9-5425c1685b14.png)

**Comment by jacekkulis** [comment]
Any updates? ;)

**Comment by smadurange** [comment]
@jacekkulis My team ran out of patience trying to get this to work :p We just added optional properties to the same model. Will probably come back to it at some point but it'd be quite helpful to have a tutorial/example on this in their documentation.

**Comment by jacekkulis** [comment]
I have tried with custom JSON converters (attribute + DI) both Newtonsoft and core one, custom type converter and as you have noticed custom model binder cannot handle json body.. I've end up with converting it manually in the model binder which is not the best practice.

**Comment by drock07** [comment]
So, I'm still confused as to the right way to approach this. So, for the Polymorphic model binding tutorial [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#polymorphic-model-binding), does that just not apply at all if you're building a Web API, using JSON? So, we can get the correctly bound model to the controller by just using converters from System.Text.Json/Newtonsoft?

@pranavkm is that what you're saying? Do you have any more guidance as to how to get that to happen?

Also, do you have any insight as to why the model binding system doesn't support JSON? Or if that's something that could be happening in the future?

**Comment by davidfowl** [comment]
We don't decompose JSON payloads into key value pairs then proceed to model bind these, instead, model binding delegates to the formatter in its entirety. The formatter uses a deserializer implementation that is a black box to the modeling binding system.

**Comment by paal-havnevik-visma** [comment]
> We don't decompose JSON payloads into key value pairs then proceed to model bind these, instead, model binding delegates to the formatter in its entirety. The formatter uses a deserializer implementation that is a black box to the modeling binding system.

Does this mean that trying to combine an input model (json from the request body) with a route parameter in the same action method will require 2 separate implementations for handling a custom type (one custom JsonConverter for the json input model and one custom model binder for the route param)?

Ie having an action like this:
```c# 
[HttpPut("things/{id}")]
public async Task<IActionResult> UpdateThing(ThingInputModel model, [FromRoute] CustomIdType id)
```

where `CustomIdType` is used both as a route parameterfor `id` and also inside `ThingInputModel` for `ForeignKeyId` :
```c# 
public class ThingInputModel {
        public CustomIdType ForeignKeyId {get; set;}
        public string OtherData {get; set;}
}
```

is going to require one custom `JsonConverter`:
```c# 
public class CustomIdTypeConverter : JsonConverter<CustomIdType> {...}
```
(which does not support DI directly, but might indirectly via hacking DI into a dummy JsonSerializerOptions instance)

and one custom `IModelBinder`:
```c# 
public class CustomIdTypeModelBinder : IModelBinder {...}
```
(which does support DI, and can be registered globally/via provider)
both doing the same conversions?


Background:
The `CustomIdType` is used to handle api requests where path parameters and/or input models have id's which can be either internal ids (ints) or external ids (strings), and automatically converting the external id (string) to internal id (int) before entering the controller code (via database lookups from an injected service).

**Comment by leksts** [comment]
This should do the trick for polymorphic model binding from the request body.

It is an adapted version of [this](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/Binders/BodyModelBinderProvider.cs) which calls a custom `ModelBinder` which in turn delegates the work to the framework `BodyModelBinder`.

```c#
public class DeviceBodyModelBinderProvider : IModelBinderProvider
{
    private readonly IList<IInputFormatter> formatters;
    private readonly ILoggerFactory loggerFactory;
    private readonly MvcOptions options;
    private readonly IHttpRequestStreamReaderFactory readerFactory;

    public DeviceBodyModelBinderProvider(
        IList<IInputFormatter> formatters,
        IHttpRequestStreamReaderFactory readerFactory,
        ILoggerFactory loggerFactory,
        MvcOptions options)
    {
        this.formatters = formatters;
        this.readerFactory = readerFactory;
        this.loggerFactory = loggerFactory;
        this.options = options;
    }

    public IModelBinder GetBinder(ModelBinderProviderContext context)
    {
        if (context.BindingInfo.BindingSource != null &&
            context.BindingInfo.BindingSource.CanAcceptDataFrom(BindingSource.Body) &&
            context.Metadata.ModelType == typeof(Device))
        {
            if (this.formatters.Count == 0)
            {
                throw new InvalidOperationException("this.formatters.Count == 0");
            }

            var subclasses = new[] { typeof(Laptop), typeof(SmartPhone), };

            var metadatas = new Dictionary<Type, ModelMetadata>();
            foreach (var type in subclasses)
            {
                var modelMetadata = context.MetadataProvider.GetMetadataForType(type);
                metadatas[type] = modelMetadata;
            }

            return new DeviceBodyModelBinder(this.formatters, this.readerFactory, this.loggerFactory, this.options, metadatas);
        }

        return null;
    }
}
```

```c#
public class DeviceBodyModelBinder : IModelBinder
{
    private readonly IList<IInputFormatter> formatters;
    private readonly ILoggerFactory loggerFactory;
    private readonly Dictionary<Type, ModelMetadata> metadatas;
    private readonly MvcOptions options;
    private readonly IHttpRequestStreamReaderFactory readerFactory;

    public DeviceBodyModelBinder(
        IList<IInputFormatter> formatters,
        IHttpRequestStreamReaderFactory readerFactory,
        ILoggerFactory loggerFactory,
        MvcOptions options,
        Dictionary<Type, ModelMetadata> metadatas)
    {
        this.formatters = formatters;
        this.readerFactory = readerFactory;
        this.loggerFactory = loggerFactory;
        this.options = options;
        this.metadatas = metadatas;
    }

    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        var modelKindName = ModelNames.CreatePropertyModelName(bindingContext.ModelName, nameof(Device.Kind));
        var modelTypeValue = bindingContext.ValueProvider.GetValue(modelKindName).FirstValue;

        ModelMetadata modelMetadata;
        if (modelTypeValue == "Laptop")
        {
            modelMetadata = metadatas[typeof(Laptop)];
        }
        else if (modelTypeValue == "SmartPhone")
        {
            modelMetadata = metadatas[typeof(SmartPhone)];
        }
        else
        {
            bindingContext.Result = ModelBindingResult.Failed();
            return;
        }

        var innerModelBinder = new BodyModelBinder(this.formatters, this.readerFactory, this.loggerFactory, this.options);

        bindingContext.ModelMetadata = modelMetadata;
        await innerModelBinder.BindModelAsync(bindingContext);
    }
}
```

Register like this:
```c#
services.AddControllersWithViews();
services.AddOptions<MvcOptions>().Configure<IHttpRequestStreamReaderFactory, ILoggerFactory>((options, readerFactory, loggerFactory) =>
{
    options.ModelBinderProviders.Insert(0, new DeviceBodyModelBinderProvider(options.InputFormatters, readerFactory, loggerFactory, options));
});
```

**Comment by robertok77** [comment]
> We don't decompose JSON payloads into key value pairs then proceed to model bind these, instead, model binding delegates to the formatter in its entirety. The formatter uses a deserializer implementation that is a black box to the modeling binding system.

When  POST of application/json then  CustomJsonConverter is called which is ok
but
when I register CustomModelBinder then the same POST calls this CustomModelBinder  instead.

In POST of application/json CustomModelBinder  is useless. 

Any suggestions?
