### ISSUE TITLE
[assembly: Microsoft.AspNetCore.Identity.UI.UIFrameworkAttribute("Bootstrap4")] causing The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' 

### ISSUE THREAD

**Issue by ZeroDarkThirty** [dotnet/aspnetcore#21946]
Getting a missing assembly reference error on the following, in the `myproj.AssemblyInfo.cs` file

`[assembly: Microsoft.AspNetCore.Identity.UI.UIFrameworkAttribute("Bootstrap4")]`

Content of csproj file: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DbContext.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.4" />
  </ItemGroup>
</Project>
```

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
- The IDE - Visual Studio Mac

**Comment by javiercn** [comment]
@ZeroDarkThirty thanks for contacting us.

Seems like something is wrong with the build, can you clean the bin and obj folders and try rebuilding afterwards?

**Comment by ZeroDarkThirty** [comment]
@javiercn I've tried that but it didn't work.

**Comment by javiercn** [comment]
@ZeroDarkThirty can you provide a minimal repro project that we can use for investigation?
