### ISSUE TITLE
Blazor WebAssembly size

### ISSUE THREAD

**Issue by jakubmaguza** [dotnet/aspnetcore#21943]
Hello!

First of all, thanks for blazor, it's amazing!

Recently I was doing some blazor app deployment and then I realize that clean blazor wasm template is using over 6mb without compression.

After enabling compression via .htaccess file, i managed to make ~2.7mb (example [here](https://dzisiajnauczylemsie.pl/BlazorTemplate/)).

My question: Is it maximum what I can do? This is app from wasm template, without any modification.

I don't have access to webserver machine, I'm deploying via FTP.

BR!

**Comment by javiercn** [comment]
@jakubmaguza thanks for contacting us.

I'm not sure what level of compression Apache is applying, but you can change the way Blazor loads resources during boot and take advantage of the pre-compiled assets.

See the section `Custom boot resource loading` on https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/ for how to plug it in.

Then you can load the gzip or brotli versions directly (using something like https://wicg.github.io/compression/ or something like https://github.com/google/brotli/tree/master/js) to decompress the stream client-side directly in the browser and pass down the decompressed version.

That way you can take advantage of the higher compression ratio that pre-compression gives you.

**Comment by mrpmorris** [comment]
Was that built as Debug or Release?

**Comment by jakubmaguza** [comment]
It is published using publish profile -> to directory, which is set in release mode
