### ISSUE TITLE
Could IWebAssemblyHostEnvironment be an IHostEnvironment subtype?

### ISSUE THREAD

**Issue by gulbanana** [dotnet/aspnetcore#21944]
I'm trying to get the environment name in Blazor code which could be either Blazor Server or Blazor WebAssembly. At the moment, there isn't a common abstraction to do that.

**Comment by javiercn** [comment]
@gulbanana thanks for contacting us.

We don't plan to do that as it would requiring us to take a dependency on additional assemblies, increasing size for little benefit.

I would suggest/recommend that instead you create your own wrapping abstraction and use it across your code-base, prepopulating it based on data from the environment.

**Comment by gulbanana** [comment]
Unfortunately, that's hard to do because this product is a library to be used from either blazor server or blazor wasm. Keeping the size down seems like a good tradeoff, though.
