### ISSUE TITLE
Additional `/` when committing completion

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#21954]
![Additional slash at end of commit](https://user-images.githubusercontent.com/14852843/82243683-e040b280-98f4-11ea-9d20-13fb23497db9.gif)

When committing a completion with `enter`, the existing `/` is added to the end, instead of being overwritten / being adapted in the insertion text.

**Comment by NTaylorMullen** [comment]
Does this work outside of LSP scenarios?

**Comment by ajaybhargavb** [comment]
> Does this work outside of LSP scenarios? Aka the old editor?

In the old editor, typing `/` doesn't bring up a new set of completions so the suggestion `/NewComponent>` will still remain and it works fine.

I believe we already reported this to @ToddGrun as part of an email in the past. @ToddGrun, fyi in case you weren't aware of this already.

**Comment by TanayParikh** [comment]
Thanks @ajaybhargavb. Confirmed working appropriately in the old editor.

**Comment by TanayParikh** [comment]
Confirmed with WTE (@jimmylewis). This was fixed and merged in this morning. Should be live by Wednesday.
