### ISSUE TITLE
SignalR Hub OnConnected fails to send message to the connection

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/aspnetcore#21955]
### Describe the bug
The OnConnected method fails to send messages to the client that has connected when using the Clients.All 
### To Reproduce
create a Signalr hub override the OnConnected method with a that has a call to Clients.All.Send 
not that the client that trigger the OnConnected doesn't receive the message however all other clients do.

**Comment by BrennanConroy** [comment]
We have that in a sample that works
https://github.com/dotnet/aspnetcore/blob/dad96ff3733f0088087be3a04ff8e357608a7744/src/SignalR/samples/SignalRSamples/Hubs/Chat.cs#L15

We'll need more info about what you're doing.
