### ISSUE TITLE
ResolveStaticWebAssetsInputs breaks --no-build

### ISSUE THREAD

**Issue by gulbanana** [dotnet/aspnetcore#21979]
This bug isn't the same as https://github.com/dotnet/aspnetcore/issues/20413 but has similar underlying causes: in Blazor WebAssembly 3.2.0, client-side projects use the SWA mechanism. This doesn't respect NoBuild for the ResolveReferencedProjectsStaticWebAssets target, so if you issue..
```
dotnet build
dotnet pack --no-build
```
..then any referenced projects will fail with NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked. Setting IsPackable=False doesn't help.

**Comment by gulbanana** [comment]
Here is a trivial repository that demonstrates the problem: https://github.com/gulbanana-bugs/repro-blazor-nobuild
As above, `dotnet build` then `dotnet pack --no-build` will reproduce the error.

**Comment by javiercn** [comment]
@gulbanana thanks for contacting us.

What are you trying to pack, the webassembly app?

**Comment by gulbanana** [comment]
in my real use case, i'm trying to pack a .sln which has many projects in it. a lot of them produce nuget packages and are IsPackable=True; others don't and are IsPackable=False. there happens to be a single webassembly app in it which isn't meant to be packed, but its presence in the solution prevents me from using `dotnet pack --no-build` at solution level.

**Comment by javiercn** [comment]
@gulbanana thanks for the additional details.

That makes sense, we'll have a look at this, since while we don't support packing webassembly apps, we shouldn't necessarily prevent pack at the solution level.

**Comment by gulbanana** [comment]
That would be great. At the moment, in the webassembly app - and in all projects which reference it, though those are also not packable - I have to work around the problem by changing Sdk= to manual props/targets imports and then overriding the Pack target to do nothing.

**Comment by gulbanana** [comment]
Would you accept a PR for this issue?

**Comment by captainsafia** [comment]
@gulbanana PR's are always welcome! However, it would be helpful if you shared a brief description of what you plan to do in the PR so we can hash out any major issues.

**Comment by javiercn** [comment]
This is fixed in 6.0 RC1
