### ISSUE TITLE
Visual Studio Razor Rename - C# / HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21978]
This is a big rock issue that tracks the overall status of the rename refactoring for Visual Studio. It has multiple parts but ultimately entails adding the general "rename" refactoring action to pieces of the Razor document.

Given the size of this issue it will most likely not be completed in one release.

## 16.7-preview2
- [x] Rename from C# inside of a Razor file into & outside of a Razor file - (https://github.com/dotnet/aspnetcore/issues/22377)

## 16.X
- [ ] Rename from C# outside of a Razor that impacts code inside of one.
- [ ] Rename from JavaScript inside of a Razor file into & outside of a Razor file

The action of "renaming" outside of a Razor file into one may not be a small work item and therefore is not required for the 16.7-preview2 release. 

The JavaScript rename support will be dependent on the HTML language server implementing this tech which is not slated for the 16.7-preview2 timeframe.

**Comment by NTaylorMullen** [comment]
Estimated days 1-5 days.

**Comment by ajaybhargavb** [comment]
Blocked on https://github.com/dotnet/roslyn/issues/45063

**Comment by ajaybhargavb** [comment]
Roslyn PR to support this, https://github.com/dotnet/roslyn/pull/47104

**Comment by NTaylorMullen** [comment]
Did this land for preview3?

**Comment by ajaybhargavb** [comment]
The external PR is now merged.
