### ISSUE TITLE
Visual Studio Razor Go to Implementation - C# / HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21976]
This is a big rock issue that tracks the overall status of go to implementation for Visual Studio. It has multiple parts but ultimately entails adding the general "go to implementation" navigation action to pieces of the Razor document.

Given the size of this issue it will most likely not be completed in one release.

## 16.7-preview2
- [x] Go to implementation from C# inside of a Razor file into & outside of a Razor file (https://github.com/dotnet/aspnetcore/issues/22254)

## 16.X
- [x] Go to implementation from C# outside of a Razor file into a Razor file
- [ ] Go to implementation from JavaScript inside of a Razor file into & outside of a Razor file

The action of "go to implementationing" outside of a Razor file into one may not be a small work item and therefore is not required for the 16.7-preview2 release. 

The JavaScript go to implementation support will be dependent on the HTML language server implementing this tech which is not slated for the 16.7-preview2 timeframe.

**Comment by NTaylorMullen** [comment]
Estimated 3 days

**Comment by ajaybhargavb** [comment]
Blocked on https://github.com/dotnet/roslyn/issues/45063

**Comment by ajaybhargavb** [comment]
This is done
