### ISSUE TITLE
Visual Studio Razor Go to Definition/Peek definition - C# / HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21975]
This is a big rock issue that tracks the overall status of go to definition for Visual Studio. It has multiple parts but ultimately entails adding the general "go to definition" navigation action to pieces of the Razor document.

Given the size of this issue it will most likely not be completed in one release.

## 16.7-preview2
- [x] Go to definition from C# inside of a Razor file into & outside of a Razor file - S-M (https://github.com/dotnet/aspnetcore/issues/22015)
- [x] Peek definition

## 16.X
- [x] Go to definition from C# outside of a Razor file into a Razor file
- [ ] Go to definition from JavaScript inside of a Razor file into & outside of a Razor file

The action of "go to definitioning" outside of a Razor file into one may not be a small work item and therefore is not required for the 16.7-preview2 release. 

The JavaScript go to definition support will be dependent on the HTML language server implementing this tech which is not slated for the 16.7-preview2 timeframe.

**Comment by NTaylorMullen** [comment]
3 days

**Comment by ajaybhargavb** [comment]
Blocked on https://github.com/dotnet/roslyn/issues/45063

**Comment by ajaybhargavb** [comment]
This is done
