### ISSUE TITLE
Impossible to place Ads in blazor

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#21970]
How can we place <script> tag ads like from adsense in blazor components?
Right now it is impossible to add an ad due to script tags not being allowed.

What i would suggest is to give a warning instead of error when putting a <script> saying something in the lines of "Do not modify the script using c#"
I also cannot suppress the error

**Comment by javiercn** [comment]
@ctigrisht thanks for contacting us.

The recommendation is that you place script tags on the hosting document for the application, whether that's `index.html` or your own `_Host.cshtml` if you are using Razor pages.

**Comment by ctigrisht** [comment]
> The recommendation is that you place script tags on the hosting document for the application, whether that's `index.html` or your own `_Host.cshtml` if you are using Razor pages.
@javiercn What i mean is that there are certain scripts that render on where the script tag is in markup
