### ISSUE TITLE
Is it possible to obtain FQDN (Full Qualified Domain Name) for authenticated user using Microsoft.AspNetCore.Authenticate.Negotiate library?

### ISSUE THREAD

**Issue by ostart** [dotnet/aspnetcore#21984]
### Is your feature request related to a problem? Please describe.
I am trying to obtain FQDN (Full Qualified Domain Name) for authenticated user using Microsoft.AspNetCore.Authenticate.Negotiate library but I can't.

**Comment by Tratcher** [comment]
What platform is this on, Windows or Linux?

**Comment by ostart** [comment]
> What platform is this on, Windows or Linux?

Both platform, but Windows is more preferable

**Comment by blowdart** [comment]
Out of interesting, what do you mean by FQDN here? Domain\Username, or an LDAP fully qualified name or something else?

**Comment by ostart** [comment]
> Out of interesting, what do you mean by FQDN here? Domain\Username, or an LDAP fully qualified name or something else?

Rather LDAP fully qualified name. https://en.wikipedia.org/wiki/Fully_qualified_domain_name

**Comment by blowdart** [comment]
Not yet. Potentially in 5. @JunTaoLuo

**Comment by JunTaoLuo** [comment]
@ostart just to clarify, you would like something like user@fully.qualified.domain.name.com or just the fully.qualified.domain.name.com part?

@Tratcher @blowdart I'm looking at our APIs and I'm also a little unsure where we would surface this information. Would we be adding a value to Principal.Identity.Claims?

**Comment by blowdart** [comment]
It could either be the subject property of every claim, or the UPN claim itself. The latter is probably easier to discover.

**Comment by JunTaoLuo** [comment]
Ah I see, adding this feature this seems doable in 5.0.

**Comment by ostart** [comment]
> @ostart just to clarify, you would like something like [user@fully.qualified.domain.name.com](mailto:user@fully.qualified.domain.name.com) or just the fully.qualified.domain.name.com part?

Yes, I would like to have something like  something like user@fully.qualified.domain.name.com . Now It's possible to obtain user@domain, but domain is just current domain, not FQDN. May be for some cases it's sufficient to have user@currentDomain, but i need to have user@fully.qualified.domain.name.com also. Thanx

**Comment by blowdart** [comment]
@ostart This doesnt' seem to be a standard ldap claim, subject name seems to be the closest, and while we could do it, it's in the format where the FDQN is in CN= with each step in the standard format.

As this doesn't seem to be a standard claim from LDAP we're hesitent to do this ourselves, as we'd like to stay close to teh standard. Is there a compelling reason you can't do processing from the subject name yourself?
