### ISSUE TITLE
CORS middleware should set 'Vary: Origin' header if policy has non-default IsOriginAllowed function

### ISSUE THREAD

**Issue by stephan-tolksdorf** [dotnet/aspnetcore#21988]
When setting a custom `IsOriginAllowed` function on the `CorsPolicy` by calling the `SetIsOriginAllowed` method on the `CorsPolicyBuilder` the HTTP responses will not contain a `Vary: Origin` header, even though that is probably required (unless one also sets at least two origins via `CorsPolicyBuilder.WithOrigins`),

Either `CorsService.PopulateResult` should unconditionally set `VaryByOrigin` on the `CorsResult` when the `CorsPolicy` has a non-default `IsOriginAllowed`, or the `CorsPolicyBuilder` should expose an explicit configuration option for controlling whether the `Vary: Origin` header is emitted. 

The behaviour regarding the `Vary` header should also be documented somewhere.

**Comment by pranavkm** [comment]
Thanks @stephan-tolksdorf. Would you consider sending a PR for this?

**Comment by stephan-tolksdorf** [comment]
I'd be happy to prepare a PR. What would be your preferred approach to fixing this issue? Setting `VaryByOrigin` in `PopulateResult` if the policy contains a non-default `IsOriginAllowed`?

**Comment by pranavkm** [comment]
Yeah. The service goes to some lengths to avoid unconditonally setting the Vary header, we would want to keep that: https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/CORS/src/Infrastructure/CorsService.cs#L122.

**Comment by GavinPower747** [comment]
Seems the original author hasn't been seen for a while here. Anyone mind if I take this one up?

**Comment by stephan-tolksdorf** [comment]
I'll resubmit the MR.
