### ISSUE TITLE
user.identity.name is null 

### ISSUE THREAD

**Issue by DENMODSupport** [dotnet/aspnetcore#21987]
Hi,
i have asp.net core 2.1 application and its using windows authentication. But for some user, user.identity.name is null but its working fine for other users. Do you have idea why it is null for some users alone?

**Comment by blowdart** [comment]
That's odd, you shouldn't be able to create a user with a blank name.

If you dump out all the claims in the WindowsIdentity what's there?

**Comment by Tratcher** [comment]
Are you also allowing anonymous users to access the site? When you enable Windows Auth there's a separate setting to disallow anonymous users.

**Comment by DENMODSupport** [comment]
do you mean that if i disable anonymous authentication, it will resolve the issue? how come it is happening for some users alone?

**Comment by DENMODSupport** [comment]
do you mean that i need to disable anonymous authentication in IIS or some other else?

**Comment by Tratcher** [comment]
You should check if anonymous authentication is enabled in IIS, yes. Enumerating all of the properties on the Identity like @blowdart suggested will also tell you if they're authenticated or anonymous.

**Comment by DENMODSupport** [comment]
@blowdart how to dump out all the claims in the WindowsIdentity?

**Comment by DENMODSupport** [comment]
> You should check if anonymous authentication is enabled in IIS, yes. Enumerating all of the properties on the Identity like @blowdart suggested will also tell you if they're authenticated or anonymous.

Anonymous authentication is disabled in iis but still it is null for some users alone

**Comment by blowdart** [comment]
For Razor Pages I'd do something like this in a page to dump the properties

```
<h2>User Properties</h2>
@{
    System.Security.Principal.WindowsPrincipal windowsPrincipal = User as System.Security.Principal.WindowsPrincipal;

    if (windowsPrincipal != null)
    {
        <p>User is a WindowsPrincipal</p>
    }
}

User has @User.Identities.Count() identities.

@for (int i = 0; i < User.Identities.Count(); i++)
{
    <h3>Identity #@i</h3>

    var identity = User.Identities.ElementAt(i);

    <p>IsAuthenticated : @identity.IsAuthenticated</p>
    <p>Name: @identity.Name</p>
    <p>AuthenticationType: @identity.AuthenticationType</p>
    <p>NameClaimType: @identity.NameClaimType</p>
    <p>RoleClaimType: @identity.RoleClaimType</p>

    if (identity.Claims.Count() > 0)
    {
        <table>
            <thead>
                <tr>
                    <th>Claim Type</th>
                    <th>Claim Value</th>
                    <th>Claim Issuer</th>
                </tr>
            </thead>

            @foreach (System.Security.Claims.Claim claim in identity.Claims)
            {
        <tr>
            <td>@claim.Type</td>
            <td>@claim.Value</td>
            <td>@claim.Issuer</td>
        </tr>
            }

        </table>
    }
}
```
