### ISSUE TITLE
AspNetCore.Mvc.Testing.targets wrong "%(FullPath)" evaluation

### ISSUE THREAD

**Issue by NDalvise** [dotnet/aspnetcore#21990]
I can't build my integration test project because of the "Microsoft.AspNetCore.Mvc.Testing.targets" file is not evaluating correctly the project's path.

I am working on a Windows 10 machine using Visual Studio 2019 (16.5.4).
In my solution, there are 2 projects: 

- a web API project (**project1**) 
- an integration testing project (**project2**) that depends on **project1**.

Both projects targets .NET Core 3.1 and all the NuGet packages are up to date.
**project2** has a dependency on the "Microsoft.AspNetCore.Mvc.Testing" package.

When I try to build **project2**, I receive the following error:
Tool -> MSBuild
Code -> MSB4023
File -> C:\Users\ND'Alvise\.nuget\packages\microsoft.aspnetcore.mvc.testing\3.1.4\build\netcoreapp3.1\Microsoft.AspNetCore.Mvc.Testing.targets
Line -> 56
Description -> Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "$([System.IO.Path]::ChangeExtension('C:\Users\ND'Alvise\source\repos\AspNetCoreWebAPI\AspNetCoreWebAPI\bin\Debug\netcoreapp3.1\AspNetCoreWebAPI.dll', '.deps.json'))". The given path's format is not supported.

It's not hard to understand what's happening: the path contains an apostrophe and the runtime evaluates it as a single quote. That brokes the string evaluation and lastly the build.

Obviously moving the whole solution to another directory (one without an apostrophe) is a nasty workaround and it can't be the way to fix this problem.

**Comment by javiercn** [comment]
@NDalvise thanks for contacting us.
 
@pranavkm Is this an MSBuild bug or are we not "encoding" things here properly here. I feel this is an MSBuild bug, since it should be safe to use the result of `%(FullPath)`?

@NDalvise I would suggest you move the repo/project to a folder without the `'` for now. I don't think there's any other workaround and I wouldn't have thought we had to care for things like this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've investigated this and this seems to be an issue caused by MSBuild. If this is an important scenario for you we recommend filing an issue against the MSBuild repo here: https://github.com/microsoft/msbuild
