### ISSUE TITLE
Update Omnisharp to Roslyn 3.7

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#22008]
We can't update to Roslyn 3.7 until Omnisharp does because types passed between our projects need to be recognized as of the same type.

@JoeRobich is there an ETA on OmniSharp taking 3.7?

CC @NTaylorMullen

**Comment by JoeRobich** [comment]
@ryanbrandenburg I'll look into getting it updated to a recent build tomorrow morning.

**Comment by NTaylorMullen** [comment]
fyi @captainsafia

**Comment by captainsafia** [comment]
Thanks @JoeRobich! Let us know how this goes today.

**Comment by captainsafia** [comment]
Synced with @JoeRobich out-of-GitHub. It looks like the Roslyn update will happen so we do not need to worry about reverting on our end.

**Comment by JoeRobich** [comment]
@captainsafia I updated OmniSharp to Roslyn 3.7. Will do a new release of OmniSharp once this goes in https://github.com/OmniSharp/omnisharp-roslyn/pull/1805. Then I can update the C# extension.

**Comment by JoeRobich** [comment]
New release of OmniSharp is live with Roslyn 3.7.0. https://github.com/OmniSharp/omnisharp-vscode/pull/3799 is the PR to update in the C# extension.

**Comment by JoeRobich** [comment]
And we now have a [new C# prerelease](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.19-beta3) using the new OmniSharp. Once the razor tooling it updated, we can get a build out to vendors for prerelease testing.
