### ISSUE TITLE
[Blazor] How to Pass 'For' to Child ValidationMessage

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#22009]
I'm creating this Razor Component to make it easy to add fields and create forms. It's "mostly" working, but the For argument doesn't get properly passed to the ValidationMessage. It works when I use this syntax directly on my page

    <div style="margin-bottom: 1rem" class="row">
        <div class="col-md-2">
            <Label For="@(() => Input.Address.City)" class="required" style="width: 100%" />
        </div>
        <div class="col-md-4">
            <RadzenTextBox style="display: block; width: 100%" @bind-Value="@Input.Address.City" Id="City" />
            <ValidationMessage For="@(() => Input.Address.City)" style="position: absolute" />
        </div>
    </div>

but not when using this Component

    <Field For="@(() => Input.Address.Email)" @bind-Value="@Input.Address.Email" Required="true" />

The For expression however does get passed to the Label component. How can I get it also working for the validation?

    @using System.Linq.Expressions;

    <div class="col-md-@LabelWidth">
        <Label For="@For" Component="@GetUniqueId()" @attributes="LabelAttributes" style="width: 100%" />
    </div>
    <div class="col-md-@Width">
        <RadzenTextBox @attributes="AdditionalAttributes" style="display: block; width: 100%" Id="@GetUniqueId()" />
        <ValidationMessage For="@For" style="position: absolute" />
    </div>

    @code {
        [Parameter(CaptureUnmatchedValues = true)]
        public IDictionary<string, object>? AdditionalAttributes { get; set; }

        [Parameter]
        public Expression<Func<string>>? For { get; set; }

        [Parameter]
        public string? Id { get; set; }

        [Parameter]
        public int Width { get; set; } = 10;

        [Parameter]
        public int LabelWidth { get; set; } = 2;

        [Parameter]
        public bool Required { get; set; } = false;

        private IReadOnlyDictionary<string, object>? LabelAttributes => Required ? new Dictionary<string, object>() { { "class", "required" } } : null;

        private string GetUniqueId()
        {
            if (For != null)
            {
                var expression = (MemberExpression)For.Body;
                return Id ?? expression.Member.Name;
            }
            return string.Empty;
        }
    }

As a second question, is there a better approach to issue a unique ID to the control so that the label is attached to the field? This won't work if fields of the same name are displayed several times on the page.

Anything else I should tweak in that code?

**Comment by mysteryx93** [comment]
I found the problem of why validation was failing: it wasn't validating child objects in cascade and I could fix it following these instructions

https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#nested-models-collection-types-and-complex-types

**Comment by mysteryx93** [comment]
Sorry the child object validation is a separate issue.

The original issue posted here remains.

Validation doesn't work here

   <TextField For="@(() => Input.FirstName)" Width="4" Required="true" @bind-Value="@Input.FirstName" />

But if I do it this way, it works.

    <Field For="@(() => Input.Address.FirstName)" Width="4" Required="true">
        <RadzenTextBox @bind-Value="@Input.Address.FirstName" class="form-control" id="FirstName" />
    </Field>

I changed all my TextField to setting ChildContent explicitely like this and it's working, but that doesn't explain why the first syntax fails.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
