### ISSUE TITLE
Understanding Enable Razor runtime compilation option.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#22006]
When I select the ` Enable Razor runtime compilation`  option during the creation of an ASP.NET Core project, I see no difference in the `Startup` or `Program` class but it works. How?

Actually I was expecting, there will be something as follows if I choose ` Enable Razor runtime compilation`  option:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllersWithViews().AddRazorRuntimeCompilation();
    }

**Comment by pranavkm** [comment]
The template uses hosting startup assembly - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-3.1 - to conditionally turn on runtime compilation in Development environments. If you inspect your app's launchSettings.json, you should see an additional reference to runtime compilation.

**Comment by TanvirArjel** [comment]
@pranavkm Got it! Thank you so much.
