### ISSUE TITLE
module/plugin model build in support

### ISSUE THREAD

**Issue by John0King** [dotnet/aspnetcore#22021]
### Is your feature request related to a problem? Please describe.
just an example : for a normal web site,  there is a front side of the website, and the manage  side of  the website, and normally manage side logic is not shared by the front side of the site. people want to develop independently (or  the manage side and front side is in the same place, and different feature separately), and for modular support, the current `app.Usexxx` is not very compatible (due to the Ioc).
for a **web app**, the plugin/modular can be extend by 
1. new Url, for example :  /modules/mymodule/index.html 
2. extend points like  XXXmanager .  for example :  `MunuManager.AddMenu()`
3.  ~~auto discovery by `type`~~  this should be replaced by  2,  each module can only discovery it's own  `type` 

for a **desktop app**, the plugin/moduar can be extend by
1. extend points like  XXXmanager .  for example :  `MunuManager.AddMenu()`
2. toolbar menu  (the menu it self can be use 1 to add,  or add configuration )

### Describe the solution you'd like

I hoping there is a build in abstractions of plugin (like the `ILogger` for Logging),
and complete independent website, can choose either self-host or host by other app as a plugin.
the `IApplicatonBuilder`  is already support for `app.Map()` `app.MapWhen()`  but there isn't have a "framework" to work with it .
the efforts already has by the dotnet/aspnet team
1. `IApplicationBuilder` is already support for `app.Map()` `app.MapWhen()`
2. `AssemblyLoaderContext` support Isolation for same assembly with different version
3.  `AssemblyLoaderContext` support unload
4.  "OrchardCore" as a modular framework
5. embed static files and the `_Content/ModuleAssembly/*`  this cause a issue that the assembly in app or module , that the path is different  (it can be the same by force using the `_Content/*`  like path, but it is not perferred  when it's the main assembly) , the static file should be extend in a module with `app.UseStaticFiles()`

missing part:
1. IServiceCollection/IServiceProvider support  parent/child partten ( for example in module,  use `TryAddChildService()` with a child `IServiceColletion`,  if the parent already has the service , it will not add by the module)

**Comment by javiercn** [comment]
@John0King thanks for contacting us.

It is not clear to us what you are trying to ask. We don't plan to offer a built-in module system within ASP.NET Core. We recommend using something like "Orchard core in those situations".

**Comment by davidfowl** [comment]
> AssemblyLoaderContext support unload

Except there are issues like these https://github.com/dotnet/aspnetcore/issues/21744 (and likely more)

> IServiceCollection/IServiceProvider support parent/child partten ( for example in module, use TryAddChildService() with a child IServiceColletion, if the parent already has the service , it will not add by the module)

There's no such thing as child services or child scopes but orchard does what it can to work around the problem. This isn't something we plan to address in a first class way anytime soon.

**Comment by John0King** [comment]
@davidfowl  
> Except there are issues like these #21744 (and likely more)

Doesn't this is why we need the build in modular abstraction ?  we need the build part like this (MVC, signalR ect.)  and third party middleware / service to support the modular abstraction ,
even asp.net core do not have a modular abstraction!!   but the the abstraction,  issue like #21744 will be considered (for example add `RemoeApplicationParts()`)

**Comment by John0King** [comment]
I recently read PHP YII framework ,  and it has a modular system by default ,  and I also search about java's  Spring  framework,  and looks like it has it too.
and today in asp.net core there isn't default modular system,  and create a simple modular system is easy  but create a  isolatable modular system is **hard** (most due to the assembly version problem) .

orchard is a greet project, and also the ABP.   
and today the problem is that the intergrate a  asp.net core web app create by others  never  be easy without direct host their app on OS (IIS subapp, or Nginx subPath ).

the `IApplicationBuilder`  support this "SubApp" from  asp.net core was born (`.Map()` and `.MapWhen()`) ,  but doesn't have modular system to use it !

if we have a modular system,  the Kestrel server will like iis that can host sub app

**Comment by davidfowl** [comment]
We have no plans to tackle this problem in the core framework.

**Comment by John0King** [comment]
@davidfowl 
I think the modular system **abstcation** is requrired, the reason is that even OrchardCore or someone who implement the Modular system   need some work in the core Framework to support modular load/unload behaviors (OrchardCore do not support Hot-Plugin-Plugout yet ,  but the old Orchard does support).

the benefits:
1. module load/unload will be take care in core framework and third party middleware
2. ecology-system ,  eliminate the disunity for different framework and less duplicate packages on nuget.org
3. more productive ,  u can add a full forms app  as a small feature to your web app if someone already write a forms app

**Comment by davidfowl** [comment]
I understand that you would like to add modules to ASP.NET Core as a first class concept but It’s not a direction we’re interested in supporting in a first class way. If you can come up with small features we can add to improve orchard core or to support your external module system then we can discuss those individually. 

I personally don’t want to natively add baggage to the core of the web framework that goes with support loading and unloading arbitrary components (middleware, routes, controllers etc) dynamically.  That can be done by an external project.

**Comment by John0King** [comment]
can this issues leave open ?
