### ISSUE TITLE
Blazor: Add code behind partial class automatically for each razor component.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#22024]
If we create a Razor Component named `Todo.razor` then please also create the code behind partial class `Todo.razor.cs` automatically. Currently, it's not adding the code behind partial class. We are to manually create the `Todo.razor.cs` file and then move the `@code` block to that file which is time-consuming.

**Reason:**  Most of the cases, components will have a lot of C# logic and we will have to separate that C# logic from HTML markup. It will be more efficient and productive if the code behind partial class is automatically created with an empty `@code` block.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do. Instead, we have an alternative proposal to have an option for this tracked at https://github.com/dotnet/aspnetcore/issues/21445
