### ISSUE TITLE
MiddlewareAnalysis package prevents multiple endpoint registration

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/aspnetcore#22025]
### Describe the bug

We have an application that uses [Ocelot library](https://github.com/ThreeMammals/Ocelot) that uses Microsoft.AspNetCore.MiddlewareAnalysis undercover.
Our code tries to register multiple custom endpoints, but `.UseEndpoints()` calls (except the first one) fail with
```
InvalidOperationException: The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance.
```

We've managed to reproduce the issue in an empty project and it turns out the reason of failure is `services.AddMiddlewareAnalysis();` call.

### To Reproduce
[OcelotSample.zip](https://github.com/dotnet/aspnetcore/files/4656951/OcelotSample.zip)

csproj:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.MiddlewareAnalysis" Version="3.1.1" />
  </ItemGroup>
```
startup.cs
```cs
		// This method gets called by the runtime. Use this method to add services to the container.
		public void ConfigureServices(IServiceCollection services)
		{
			// Works if commented out
			services.AddMiddlewareAnalysis();
		}

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			app.UseRouting();

			// Separate calls work fine.
			// `app.UseEndpoints(...); app.UseEndpoints(...);` does not throw
			app
				.UseEndpoints(endpoints => // ok
					endpoints.Map("test", async context =>
					{
						context.Response.ContentType = MediaTypeNames.Application.Json;
						var result = JsonConvert.SerializeObject("Hello!", Formatting.Indented);
						await context.Response.WriteAsync(result);
					}))
				.UseEndpoints(endpoints =>  // throws
					endpoints.Map("test2", async context =>
					{
						context.Response.ContentType = MediaTypeNames.Application.Json;
						var result = JsonConvert.SerializeObject("Hello!", Formatting.Indented);
						await context.Response.WriteAsync(result);
					}));
		}
```

Run the app, it should fail with InvalidOperationException error.

```
System.InvalidOperationException: The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance. To use Endpoint Routing with 'Map(...)', make sure to call 'IApplicationBuilder.UseRouting' before 'IApplicationBuilder.UseEndpoints' for each branch of the middleware pipeline.
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.VerifyEndpointRoutingMiddlewareIsRegistered(IApplicationBuilder app, DefaultEndpointRouteBuilder& endpointRouteBuilder)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
   at OcelotSample.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) 
```

NB: works fine if we use original app builder instead of fluent syntax:
```
	app.UseEndpoints(...);
	app.UseEndpoints(...); // does not throw
```

### Further technical details
- ASP.NET Core 3.1.3
```
PS > dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.1.300
 Commit:    b2475c1295
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019 15.6

**Comment by javiercn** [comment]
@ig-sinicyn thanks for contacting us.

That is by design. You shouldn't call `app.UseEndpoints` more than once. In the first case we can't really detect that you are doing it, but in the second case we do and throw accordingly.

**Comment by ig-sinicyn** [comment]
@javiercn There may be third-party libraries that do call .UseEndpoints() undercover (legacy UseSignalR() as example). So there is no way to guarantee that the recommendation is fulfilled.

At least, it should be documented and the code should produce human-readable diagnostic.

**Comment by javiercn** [comment]
@ig-sinicyn we discourage all libraries from calling `app.UseEndpoints` internally. I don't believe that `UseSignalR` does it, but if it does, it does it for legacy reasons, we'll likely change that in the future.

As for docs, there are docs [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#guidance-for-library-authors) about it.
