### ISSUE TITLE
LoggerMessage causing hang in windows service

### ISSUE THREAD

**Issue by andrew-vdb** [dotnet/aspnetcore#22030]
Using dot net core worker template, there is situation where a class fire an event and in the event handler, I call the action from LoggerMessage.Define

For some reason, it just hang without any reason
Using logger.LogError just works

Is there anything special about LoggerMessage? Threading wise

I found it silly to read documentation that this log is high performance but it hang my application
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-3.1

**Comment by BrennanConroy** [comment]
Could you share your startup code, or even better a repro app on GitHub?
