### ISSUE TITLE
How to change UserManager and RoleManager's lifetime

### ISSUE THREAD

**Issue by Blackleones** [dotnet/aspnetcore#22031]
Is it possible to change UserManager and RoleManager's lifetime after called `services.AddDefaultIdentity( ... )`. If not, is there another way to do that?

**Comment by blowdart** [comment]
Lifetime as in DI lifetime? What are you wanting to achieve by changing it?

**Comment by Blackleones** [comment]
There are some problems with concurrency on dbContext [(as you can see here)](https://github.com/dotnet/aspnetcore/issues/18340) and changing dbContext's lifetime to `Transient` not solve the problem because `UserManager / RoleManager` are `Scoped` so when asp.net create them, they are shared between multiple components and so they will use the same `dbContext (transient)` instance.

I know this is not a beautiful solutions, but I have to do that if I want to share  `UserManager / RoleManager` among multiple components. 

Another solution (already implemented) is to create a  `UserManager / RoleManager`  inside a new scope by  `IServiceProvider`.. but I don't like this solution because it hides more what is going on inside the component.

**Comment by blowdart** [comment]
If this is "just" for blazor, then no, doing things in a blazor idiomatic way as @javiercn suggests is the right way to go. 

My concern here is that people will try to make user manager and role manager singletons, rather the request scoped as they should be for asp.net apps. Allowing lifetime changes is too risky in that regard,

**Comment by blowdart** [comment]
You can take the code for `[AddDefaultIdentity()](https://github.com/dotnet/aspnetcore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/UI/src/IdentityServiceCollectionUIExtensions.cs)` and do it all manually, and adjust lifetimes that way, but it's not something we want to do in `AddDefaultIdentity()` because that's the common scenario.

**Comment by Blackleones** [comment]
@blowdart thanks you. I totally agree with your previous answer. Unfortunately blazer server-side has this concurrency problem when you want to use entity framework asynchronously among multiple components.
As I told before, I've just "solved" this problem creating a new scope from `IServiceProvider` but this is not an elegant way. Obviously this is a workaround and not a real solution.

The solution proposed by @javiercn works but there is a case where it not works: A component requires `UserManager` and `RoleManager`. I can't inherit `OwningComponentBase` twice. So one of the solution is change the lifetime of the two manager to transient.

I hope there will be a _fix_ for this problem but I don't know. It seems a problem related on how blazor is designed.

Anyway, thank you again.

**Comment by javiercn** [comment]
Creating a scope is not a workaround, it's the proper and recommended way to do it.

**Comment by Blackleones** [comment]
@javiercn, create a new scope generates a new problem with ConcurrencyTokens. I've just encountered this problem.

I have two components which both of them extend `OwningComponentBase` and get a new instance of `userManager` from 
```csharp 
UserManager = (UserManager<KairosUser>)ScopedServices.GetService(typeof(UserManager<KairosUser>))
``` 

- **Component A** shows a grid populated from `UserManager.Users` and for each row (user) there is a button that clears the email of related user.
- **Component B** updates user's email  given its username

Let's follow this scenario.

- **goal**: I want to update the user's email about the user with username = _test_ and then clear it through button inside the row related to the user with username _test._

1. I open the page that contains the **Component A**.
2. **Component A** is rendered.
3. I open **Component B** and give the username _test_ to it 

> - snapshot about **IdentityUser.ConcurrencyStamp** inside the grid (component A): **b8edf819-a06a-449c-95a0-b83f056af52b**

> - snapshot about **IdentityUser.ConcurrencyStamp** inside the component B:  **b8edf819-a06a-449c-95a0-b83f056af52b**

> - this means component A and component B seeing the same _test_ user

4. I update the _test_ user's email

> - snapshow about **IdentityUser.ConcurrencyStamp** inside the component B **1a68366b-f492-45b8-b6a0-7d70c634eb64** 

5. I refresh the grid

> - **(here is the problem)** snapshot about **IdentityUser.ConcurrencyStamp** inside the grid (component A):  **b8edf819-a06a-449c-95a0-b83f056af52b**

6. I click the button inside the _test_ user's row inside the grid and the **UserManager.UpdateAsync(user)** fail with the error: **ConcurrencyFailure**

The UserManager contained inside ComponentA still return the old IdentityUser because it didn't notice that UserManager contained inside ComponentB runs an update.

**Notes**
- I've tested this behavior with DbContext's lifetime set to `Transient` and `Scoped`

**Comment by sven5** [comment]
There are really issues with Blazor and UserManager, e.g. UserManager tracks user objects and that's not desired. 
I will workaround this by creating my own pieces from UserManager for my needs.

However, I think there _should_ be a way that UserManager and Blazor can work together.

**Comment by sven5** [comment]
@Blackleones 

Maybe I've found a possible workaround: just disable the IdentityContext's change tracking:

```
          services.AddDbContext<IdentityContext>(options =>
            {
                options.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
                options.UseSqlServer(
                    configuration.GetConnectionString("DefaultConnection"));
            }, ServiceLifetime.Transient);
```

**Comment by Blackleones** [comment]
@sven5  thank you. I will try it.

By the way, neither of those solutions looks like a "how to" or "best practices". They just look as a workaround. I think we need some improvement on identity for blazor.

**Comment by sven5** [comment]
I agree,

I also consider all of those solutions as workarounds or tricks. And yes, there should be some improvement in the Identity framework for Blazor. I think it would be possible to get Usermanager and RoleManager working with server-side Blazor.

**Comment by Blackleones** [comment]
@javiercn Thanks for your support. 
> Creating a scope is not a workaround, it's the proper and recommended way to do it.

I would like to report another strange behavior about creating *UserManager/RoleManager* from a new scope: 
My DbContext has a dependency on this custom service

```csharp
public class CurrentUserService 
    {
        private readonly AuthenticationStateProvider _authenticationStateProvider;

        public CurrentUserService(AuthenticationStateProvider authenticationStateProvider)
        {
            _authenticationStateProvider = authenticationStateProvider;
        }

        public async Task<string> GetUserName() 
        {
            var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
            var user = authState.User;
            return user.Identity.Name;
        }
    }
```

and the method `SaveChanges()` is overridden in a way that for each entity it adds some Audit info (who created/deleted/modified entities) retrieving the current user calling **CurrentUserService.GetUserName()** . That code generates the following exception `System.InvalidOperationException: GetAuthenticationStateAsync was called before SetAuthenticationState.` when it is called by _UserManager/RoleManager_ generated inside the new scope. Instead, it always works when I can call `myContext.SaveChanges()` directly.

Let me know if you need a sample project if you want to investigate it.

> Identity abstractions are not designed for usage within Blazor. Identity is designed for traditional web applications that follow a request/response model and leverage HTTP features like cookies that are not available in Blazor applications.

This sentence confused me. It seems that you suggest to not use the Identity Framework with Blazor.  Is it correct? I think I am wrong.

**Comment by javiercn** [comment]
> This sentence confused me. It seems that you suggest to not use the Identity Framework with Blazor. Is it correct? I think I am wrong.

I suggest you don't try building a UI for Identity using Blazor since Identity is designed to work on a request/response model and not over a stateful websocket connection. There will be things that you can potentially make work (like UserManager) and things that won't work at all, like SignInManager, but this is not a pattern we recommend you follow. 

The tried path for extending Identity is to use Razor pages and MVC, it is non-goal for us to build UIs for Identity using Blazor and we discourage you from doing so.

As per the original lifetime question, you should not change the DI lifetimes that Identity set on their services unless explicitly allowed by the API or you'll run into many hard to diagnose issues. For things that are IDisposable, the recommendation is that you create your own separate scope to use those dependencies, otherwise they'll live for the duration of the circuit.

**Comment by chitoiur** [comment]
> Maybe in the future we have an _AddBlazorIdentity_ extension method.

Given that this problem is mostly applicable to Blazor, rendering UserManager unusable in Blazor applications, I think this would be the most elegant solution.

**Comment by xavierpena** [comment]
@Blackleones I have the exact same issue, and I am trying to apply the same workaround as you did. I've posted [this question]() on StackOverflow to try to find a solution. If you could share your thoughts, it would be very useful... 

I wasn't expecting to invest so much time on trying to make those Identity features working, in fact it was a selling point for using Blazor (that is: having Identity working out of the box). I am just trying to add an UI on top of it to manage users and roles.
