### ISSUE TITLE
Blazor debugger wont load source files if there is special character in path

### ISSUE THREAD

**Issue by jakubmaguza** [dotnet/aspnetcore#22036]
### Describe the bug
As in title, if I have my source code let say in 'C:/Project C#/MyApp', debugger in both browser and visual studio refuse to load source code.
When I'm trying to debug in VS, the brakepoint is being hit, I can even see local variables for it, but instead of displaying file where actual brakepoint was set, VS is opening another tab with this info:
`Unable to retrieve source content (Unable to retrieve source content)`

Moving project to different directory solves this issue

### To Reproduce

1. Create project within `C:\Project C#\`
2. Try to debug

### Further technical details
- ASP.NET Core version 3.1

**Comment by captainsafia** [comment]
@pranavkm Is this possibly related to #14501?

**Comment by mkArtakMSFT** [comment]
Closing as a dupe.
