### ISSUE TITLE
ScriptTagHelper and asp-src-include skips a file?

### ISSUE THREAD

**Issue by dmcweeney** [dotnet/aspnetcore#22032]
### Describe the bug
We have a very simple script tag include as follows:

`<script type="text/javascript" asp-src-include="~/dist/npm/npm.*.js" asp-src-exclude="~/dist/npm/npm.syncfusion.js" asp-append-version="true"></script>
`

However we noticed that running on Azure App Service it skips a file that matches the above pattern:
I think it may be related to the size of the file in question:
Size: 31.9 MB (33,539,338 bytes)
Size on disk: 31.9 MB (33,542,144 bytes)

The file in question is deployed - I've verified using kudu,
If I change the above script include as follows (exclude skipped file) and add an explicit script include for the skipped file, it works:

```
<script type="text/javascript" asp-src-include="~/dist/npm/npm.*.js" asp-src-exclude="~/dist/npm/npm.skippedfile.js" asp-append-version="true"></script>
<script type="text/javascript" src="~/dist/npm/npm.skippedfile.js" asp-append-version="true"></script>
```

Initially I thought the problem was related to the version hash generation, due to the size of the file, but this works on the explicit script include.

If I run the app on localhost using visual studio 2019 / IIS Express, the problem does not happen.

### Further technical details
- ASP.NET Core version: 
3.1.3

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 16.5.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This doesn't seem to be something ASP.NET Core MVC specific.
Consider reaching out to the Azure AppService support for this.
