### ISSUE TITLE
OpenIdConnectHandler SaveTokens does not honor any previously set tokens.

### ISSUE THREAD

**Issue by CoderNumber1** [dotnet/aspnetcore#22033]
Any custom tokens set through `TokenResponseReceivedContext.Properties` are erased during authentication. This appears to be because the `StoreTokens` function does not build on the tokens already in that `AuthenticationProperties` object.

https://github.com/dotnet/aspnetcore/blob/b16a39f42a7bbdc438497f6ea3efe26008f3f0b7/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L927-L963

Because `AuthenticationProperties.StoreTokens(IEnumerable<AuthenticationToken> tokens)` clears all existing tokens and replaces them with the value of the `tokens` parameter, anything that was set earlier in the authentication process will be lost.

The reason this is such a big issue is that I'm tying into the `OpenIdConnectEvents.OnTokenResponseReceived` hook, and creating a custom token to be added. However because of what I've outlined above, this token does not survive. What I'm trying to do looks something like this:

```CSharp
services
    .AddOpenIdConnect(options =>
    {
        options.Events = new OpenIdConnectEvents
        {
            OnTokenResponseReceived = (context) =>
            {
                // I've omitted the actual generation of this token value for brevity.
                string customToken = GenerateCustomToken(context.ProtocolMessage.IdToken);

                var updatedTokens = context.Properties?.GetTokens()?.ToList() ?? new List<AuthenticationToken>();
                updatedTokens.Add(new AuthenticationToken() { Name = "custom-token", Value = customToken });

                context.Properties.StoreTokens(updatedTokens);

                return Task.CompletedTask;
            }
        };
    });
```

I would think that the `tokens` field in the snippet from the `OpenIdConnectHandler` above should be initialized to `properties.GetTokens().ToList()` instead of a new list. Any guidance how to to resolve this is greatly appreciated, thank you.

**Comment by Tratcher** [comment]
Workaround: When storing custom tokens also store the standard tokens yourself and disable the SaveTokens option.

> I would think that the `tokens` field in the snippet from the `OpenIdConnectHandler` above should be initialized to `properties.GetTokens().ToList()` instead of a new list.

Sounds plausible.

Priority: Low. This is the only report I've seen of this situation and there is a workaround.

**Comment by blowdart** [comment]
I don't think we can change this, it was designed to stomp. A change would mean having to decide what to do with duplicates

@CoderNumber1 can you look at Tratcher's workaround and see if that works for you?

**Comment by CoderNumber1** [comment]
I did not utilize @Tratcher's workaround, as I didn't want to impact things like the generation of the `expires_at` token and/or anything that might be added to the `SaveTokens` function later. Instead I used the `OnTicketReceived` to create the custom tokens later on after the access and identity tokens had already been stored, append the custom tokens to the existing collection, and save that new collection. Basically what I'm doing is very similar to what I outlined above, but in the `OnTicketReceived` hook instead. This seems to be working.

Regarding duplicates, since today it effectively removes anything that might be a duplicate by overwriting the entire collection, I would assume instead it could just check for/remove any existing tokens the `SaveTokens` function intends to save.

```diff
 private void SaveTokens(AuthenticationProperties properties, OpenIdConnectMessage message) 
 { 
-   var tokens = new List<AuthenticationToken>(); 
+   var tokens = properties.GetTokens()?.ToList() ?? new List<AuthenticationToken>();
  
     if (!string.IsNullOrEmpty(message.AccessToken)) 
     {
+        tokens.RemoveAll(t => t.Name == OpenIdConnectParameterNames.AccessToken);
         tokens.Add(new AuthenticationToken { Name = OpenIdConnectParameterNames.AccessToken, Value = message.AccessToken }); 
     }

     // I've omitted the rest of the function just for brevity.
}
```
