### ISSUE TITLE
How to override default RoleValidator

### ISSUE THREAD

**Issue by maykoestevez** [dotnet/aspnetcore#22044]
I trying to override the name validation duplication for the roles, here what I have

Startup file

```
 services.AddScoped<IRoleValidator<ApplicationRole>, 
                                                    WebIdp.Services.RoleValidator<ApplicationRole>>();

 services.AddIdentity<AplicationUser, ApplicationRole>(config =>
                {
                    config.SignIn.RequireConfirmedEmail = false;
                    config.Password.RequiredUniqueChars = 0;

                })
                .AddRoles<ApplicationRole>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddErrorDescriber<MultilanguageIdentityErrorDescriber>()
                .AddRoleManager<ApplicationRoleManager>();
```
When I debug my code my validator works but when I start creating a new role then I have two validators the default and mine in the rolManager Validators property, then it does my validation but after mine it goes to the next validator and fail, since the manager is tryng to check all the validations that it has.

I'm using Asp.net core 2.2

Do I am missing some configuration?

Thanks!!

**Comment by HaoK** [comment]
I guess you might need to remove the existing Rolevalidator from DI in ConfigureServices.  TryAddRoleValidator I would think should have prevented it from registering, you can inspect the services collection in ConfigureServices and ensure only your RoleValidator is registered

**Comment by maykoestevez** [comment]
I`m trying to add TryAddRoleValidator under AddIdentity, but it said IdentityBuilder' does not contain a definition for 'TryAddRoleValidator.


```
            services.AddIdentity<AplicationUser, ApplicationRole>(config =>
                {
                    config.SignIn.RequireConfirmedEmail = false;
                    config.Password.RequiredUniqueChars = 0;

                })
                
                .AddRoles<ApplicationRole>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddErrorDescriber<MultilanguageIdentityErrorDescriber>()
                .AddUserManager<ApplicationUserManager>()
                .TryAddRoleValidator<ApplicationRole>()
                .AddRoleManager<ApplicationRoleManager>();
```

Do I have to install something to use TryAddRoleValidator? I saw that tryAdd feature is available for dotnet 2.2 which is the version I`m using.

**Comment by HaoK** [comment]
No what you had before should already work, I meant add the validator like normal before AddIdentity and that should prevent identity from adding the default one.  If that doesn't work, then try removing any service descriptors from the service collection that aren't your role validator

**Comment by maykoestevez** [comment]
How do I remove those service descriptors? if there are any.

**Comment by maykoestevez** [comment]
Thanks, @HaoK!!

Like you mention I remove the default one just to keep my implementation.
   ```
services.AddScoped<IRoleValidator<ApplicationRole>, ApplicationRoleValidator<ApplicationRole>>();

            services.AddIdentity<AplicationUser, ApplicationRole>(config =>
                {
                    config.SignIn.RequireConfirmedEmail = false;
                    config.Password.RequiredUniqueChars = 0;

                })
                
                .AddRoles<ApplicationRole>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddErrorDescriber<MultilanguageIdentityErrorDescriber>()
                .AddUserManager<ApplicationUserManager>()
                .AddRoleManager<ApplicationRoleManager>();

                var defaultRoleValidator = services.FirstOrDefault(descriptor => descriptor.ImplementationType ==typeof(RoleValidator<ApplicationRole>));
                services.Remove(defaultRoleValidator);
```
 It looks like a work around but is working.
