### ISSUE TITLE
Blazor Attribute Splatting Fails with Int Values

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#22048]
Using Blazor in .NET 3.1

Creating a Razor Component, I'm taking in unmatched attributes and passing them to a child control

    <RadzenTextBox @attributes="AdditionalAttributes" />
    
    @code {
        [Parameter(CaptureUnmatchedValues = true)]
        public IDictionary<string, object>? AdditionalAttributes { get; set; }
    }

If I specify MaxLength on RadzenTextBox within the component, it works.

If I specify MaxLength when declaring the component, however, it fails.

    <TextField MaxLength="4" />

> System.InvalidOperationException: 'Unable to set property 'MaxLength' on object of type 'Radzen.Blazor.RadzenTextBox'. The error was: Unable to cast object of type 'System.String' to type 'System.Nullable`1[System.Int32]'.'

How can I get attribute splatting to work with other data types than string? That's kind of a serious limitation.

**Comment by gulbanana** [comment]
does it work with non-nullable ints?

**Comment by pranavkm** [comment]
In the absence of any information about the type of a parameter being passed, Blazor defaults to passing this as string. This would explain the error you're seeing here - the splatted parameter doesn't specify type information, so you receive a `string` type. You could either pass in an explicit integer value when you specify the `TextField` component or coerce it in to a int value as part of `TextField.OnParametersSet`.

**Comment by mysteryx93** [comment]
Is there at least a work-around of some kind?

**Comment by pranavkm** [comment]
> You could either pass in an explicit integer value when you specify the TextField component or coerce it in to a int value as part of TextField.OnParametersSet.

```C#
<TextField MaxLength="@((int)4)" />
```
