### ISSUE TITLE
Ideal SCSS-SASS solution in Blazor- Assemblies-Components-Main - designed and shown by a graph

### ISSUE THREAD

**Issue by KKacer** [dotnet/aspnetcore#22054]
### Brief: 
You can check the _"desired solution"_ section's designed architecture shown by an image.

### Background
I am trying to create a great development platform based on Blazor. What I care most is the re-usability of my components and the whole architecture over my projects.

Earlier I tried to explain the same needed feature, which I think I didn't explain well enough, and also didn't get a real feedback, in another hand couldn't find the needed features in the current roadmaps. 

My previous opened topic is located here:
[https://github.com/dotnet/aspnetcore/issues/21026](url)

Here is an important feature request similar to our topic in the below link, but what I am talking here should be implemented one level ahead of that, it should be a bare-bone for any component and blazor apps.
[https://github.com/dotnet/aspnetcore/issues/10170](url)

### Problem
Having full support of Sass (Scss) libraries in Asp.net Core and Blazor, especially in a modular architecture. 
I want .razor files aside from having their own SCSS files (which I know discussed earlier in github and already listed in your roadmap), understand SCSS the Sass way even from the referenced libraries, they shouldn't be compiled. (We may have the option to tell which scss is ready to be compiled and which will be used still just as a sass library for other sass files and components.
Also I think it may be the time to support Sass/Scss more natively, the only official thing for supporting Sass on Visual Studio and Asp.net core is:
[https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebCompiler](url)
which the time tells: _Last updated 	10/3/2018_
Front-end development is all about CSS, so we need to consider its future now, though Sass and SCSS were here for a long-time and yet every support we already have is partial and conditional.
In my opinion, Bootstrap, JQuery, 3rd party JS libs, etc were all past, so please forget these and instead try to move forward on the very basic support of Sass/Scss files.
I think and love to think that Blazor can be the future.

### Current Solution (Workaround)
There is no real solution currently.
For a workaround I used 2 tools designed by @stefanloerwald @excubo-ag
[https://github.com/excubo-ag/WebCompiler](url)
[https://github.com/excubo-ag/Blazor.LazyStyleSheet](url)

i created the below code in the process of learning his component/MSBuild and getting closer to the final desired result:
[https://github.com/KKacer/ScssStructure4](url)

This project is built just as a try to make that tool working in quite similar situations, though the structure is not perfect yet.

### Desired Solution

I designed the desired architecture
[https://postimg.cc/dL46PTdk](url)

I believe it should be done in parallel with #10170 or prior to that,
so when isolating components "SCSS files" we be able to access some other base/common SCSS files, such as variables etc, even in other assemblies.

**_Explain parts of the strategy by code:_**
(It will be updated in days)

`_ComponentsShared.scss
// (2nd level library, this library also like the 1st level one, shouldn't be compiled yet)
// Should be able to import
// SassLib; SassFiles/SassLib (_SassLib) (from the 1st library)
//  this way can specify the DLL and then the location, something similar to what we do in WPF, and 
// also may do in "App.razor" 

@mixin FullBorder {
    border: solid 3px $cOrange1;
}`

It could be good to be able to import Sass libraries (Scss files) located in our other base DLLs like:

SassLib; SassFiles/SassLib
(it will automatically import_SassLib, "_" in Sass means it shouldn't be compiled)

I have VS 16.5.4 Enterprise and will update it to 16.6 by tomorrow.
Also I am able and ready for the discussions on it if needed.

May Update this topic as we go on, and based on my next experiments.

I ask all the great Microsoft developers to consider this as a bare-bone for making a great development architecture.
 @danroth27 @SteveSandersonMS @javiercn 

Regards,
Kasra Kacer,
_25+ years experience of development. Front-end, Back-end, Brand owner_
_developed .net since 2001, developed CSS since 2001_

**Comment by mkArtakMSFT** [comment]
Thanks for your feature request.
We're going to consider all this as part of the [CSS Isolation](10170) work we already work on.
