### ISSUE TITLE
Unable to invoke SignalR Hub methods after a while

### ISSUE THREAD

**Issue by pielegacy** [dotnet/aspnetcore#22059]
### Describe the bug

In our application we use SignalR Core to maintain a constant connection between a client hosted agent and our Azure hosted API. One of the main requirements of this connection is that every minute the client will invoke a SignalR method to update the "heartbeat" of the agent. 

The heartbeat is set through two methods on the SignalR hub:

- `OnConnectedAsync`
  - The heartbeat is set on this event handler so that when the client connects the server is instantly notified that they are connected.
- `UpdateHeartbeatAsync`
  - A method called by the agent every minute to update the heartbeat details stored in the DB.

We have an instance of the application hosted in Azure App Service, when the application has been online for about a day the agent is no longer able to update their heartbeat using the `UpdateHeartbeatAsync` method.

If I restart the agent, the heartbeat is temporarily updated due to a successful call to `OnConnectedAsync`, however after a while the heartbeat begins to expire and the agent throws an error when attempting to invoke the method:

![image](https://user-images.githubusercontent.com/7465061/82508341-19bd2c00-9b48-11ea-98c3-4dc7252c62cc.png)

The only way we've found fixes this issue is a full restart of the API app service. One thing to note is we have this exact system in an ASP.NET Core 2.1 application and have not experienced this issue, it has only become notable whilst we have begun work on a new project in 3.1.

It is also worth noting that we are currently _not_ using Azure SignalR Service, just the Azure App Service.

### To Reproduce

It's hard to reproduce this issue as it often occurs out of hours and has only occurred in our Azure App Service, however I can provide is the hub implementation:

```cs
[Authorize]
public class TaskQueuesHub : Hub<ITaskQueuesHub>
{
    private readonly IServiceProvider _serviceProvider;
    private readonly IUserService _userService;
    private readonly ILogger<TaskQueuesHub> _logger;
    private readonly IHubContext<AgentsHub, IAgentsHub> _agentHub;

    public TaskQueuesHub(
        IServiceProvider serviceProvider,
        IUserService userService,
        ILogger<TaskQueuesHub> logger,
        IHubContext<AgentsHub, IAgentsHub> agentHub) : base(userService, logger)
    {
        _serviceProvider = serviceProvider;
        _userService = userService;
        _logger = logger;
        _agentHub = agentHub;
        _logger.LogInformation("TaskQueuesHub initialized!");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="hostName"></param>
    /// <returns></returns>
    public async Task UpdateHeartbeatAsync(string hostName)
    {
        string connectionIdSafe = (Context?.ConnectionId ?? "Unknown");
        try
        {
            _logger.LogInformation($"{connectionIdSafe} invoking 'UpdateHeartbeat'...");
            await UpdateAgentDetailsAsync(hostName);
            _ = _agentHub.GetTenantGroup(_userService).HeartbeatsUpdated();
            _logger.LogInformation($"{connectionIdSafe} invoked 'UpdateHeartbeat'!");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"{connectionIdSafe} failed to invoke 'UpdateHeartbeat'");
            throw ex;
        }
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    public override async Task OnConnectedAsync()
    {
        string connectionIdSafe = (Context?.ConnectionId ?? "Unknown");

        try
        {
            _logger.LogInformation($"{connectionIdSafe} getting hostname...");
            //when connected register the client with the database so we can send messages specifically to the client.
            var hostName = Context.GetHttpContext().Request.Query["host"].FirstOrDefault();
            if (!string.IsNullOrEmpty(hostName))
            {
                _logger.LogInformation($"{connectionIdSafe} updating agent details...");
                await UpdateAgentDetailsAsync(hostName);
            }
            await _agentHub.GetTenantGroup(_userService).HeartbeatsUpdated();
            _logger.LogInformation($"{connectionIdSafe} connected!");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"{connectionIdSafe} failed to connect...");
            throw ex;
        }
        finally
        {
            await base.OnConnectedAsync();
        }
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="exception"></param>
    /// <returns></returns>
    public override async Task OnDisconnectedAsync(Exception exception)
    {
        try
        {
            Entities.Agent agent;

            using (var scope = _serviceProvider.CreateScope())
            {
                using (var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    agent = dbContext.Agents.FirstOrDefault((a) => a.ConnectionId == Context.ConnectionId);
                    if (agent != null)
                    {
                        agent.ConnectionId = null;
                        dbContext.Update(agent);
                        await dbContext.SaveChangesAsync();
                    }
                }
            }

            if (exception != null)
            {
                _logger.LogError(exception, $"Connection {Context?.ConnectionId} ({agent?.HostName}) has died and subsequently been disconnected (Reason: {exception.Message})");
            }
            else
            {
                _logger.LogInformation($"Connection {Context?.ConnectionId} ({agent?.HostName}) has been disconnected");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to disconnect from TaskQueuesHub...");
        }
        finally
        {
            await base.OnDisconnectedAsync(exception);
        }
    }

    /// <summary>
    /// Updates the connection ID and heartbeat of the connected agent.
    /// </summary>
    /// <param name="hostName"></param>
    /// <returns></returns>
    private async Task UpdateAgentDetailsAsync(string hostName)
    {
        using (var scope = _serviceProvider.CreateScope())
        {
            using (var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>())
            {
                _logger.LogInformation($"Getting agent with hostname {hostName}");
                var agent = dbContext.Agents.FirstOrDefault((a) => a.HostName == hostName);
                //var agent = await agentRepo.GetOneAsync(e => e.HostName == hostName);
                agent.ConnectionId = Context.ConnectionId;
                agent.HeartBeat = DateTime.UtcNow;

                _logger.LogInformation($"Updating heartbeat...");
                dbContext.Update(agent);
                await dbContext.SaveChangesAsync();
                _logger.LogInformation($"Heartbeat updated for agent {agent.HostName} to {agent.HeartBeat}!");

            }
        }
    }
}
```

### Further technical details

- Using .NET Core version 3.1.103
- Client application uses .NET Core 3.1.103 with `Microsoft.AspNetCore.SignalR.Client` version `3.1.3`.
- App is hosted on Azure App Service (Windows), not using Azure SignalR Service.

**Comment by davidfowl** [comment]
I'd recommend turning on logging https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1 as a way to start debugging this. We won't be able to help without that.

In your Hub methods, you don't need to create a scope as the framework creates one for you per invocation. Just inject the DbContext in the constructor.

Context can't be null unless you're in a unit test and not setting it.

**Comment by pielegacy** [comment]
Thank you @davidfowl , I've got verbose logging enabled on the API end which is how I came to the conclusion this was only occurring on the method not the connected event.

I'll enable the verbose logging in the agent end and come back to you when I get something to work with, I realised shortly after posting this that HubContexts were transient so I've removed the service provider dependency resolution (this was used in an attempt to debug the problem).

**Comment by pielegacy** [comment]
I've left the connection running over the weekend and have retrieved this subset of logs, this includes the agent successfully connecting to the server and then eventually failing.

The only changes I've made my last comment and now was changing the transport to use Long Polling rather than Websockets, this was to ensure that the issue wasn't on our end/network related.

Even with long polling the issue persists.

[Agent.log](https://github.com/dotnet/aspnetcore/files/4674539/Connectivity.Issues.Agent.log)

[API.log](https://github.com/dotnet/aspnetcore/files/4674561/Connectivity.Issues.Server.log)

**Comment by BrennanConroy** [comment]
From SignalRs perspective it looks like everything is working fine.

Your client application is calling stop:
```
2020-05-22 21:16:06.674 +10:00 [INF] Checking agent vitals...
2020-05-22 21:16:06.675 +10:00 [ERR] Unhealthy heartbeat detected, resetting websocket connection.
2020-05-22 21:16:06.675 +10:00 [VRB] Waiting on Connection Lock in StopAsyncCore (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:469).
2020-05-22 21:16:06.675 +10:00 [VRB] Releasing Connection Lock in StopAsyncCore (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:513).
2020-05-22 21:16:06.675 +10:00 [DBG] Stopping HubConnection.
```

> `UpdateHeartbeatAsync`
> 
>     * A method called by the agent every minute to update the heartbeat details stored in the DB.

It doesn't look like this is being called every minute. Maybe a bug in your client logic.

**Comment by pielegacy** [comment]
For context on that logic, the heartbeat in the agent using the following code:

```cs
public async Task SendHeartbeatAsync(CancellationToken cancellationToken = default)
{
    try
    {
        await connection.InvokeAsync("UpdateHeartbeat", _hostName, cancellationToken);
        Heartbeat = DateTime.UtcNow;
        Logger.LogInformation($"Heartbeat updated to UTC {Heartbeat.Value}.");
    }
    catch (Exception ex)
    {
        Logger.LogError(ex, "Unable to update heartbeat for agent.");
    }
}
```

This `UpdateHeartbeat` invocation updates the value in the database, I've ran tests and can confirm that when this issue occurs the database is not updated which has given me the impression that `UpdateHeartbeat` is never called.

For debugging I have removed this logic, but previously the `cancellationToken` had a set value of 10 seconds before timing out so that we could make sure that the call completed in a valid amount of time. From what I can see it looks like `UpdateHeartbeat`'s invocation doesn't complete in a valid amount of time which is causing this.

For additional context, the closing of the connection uses this logic in the agent:

```cs
public bool IsHeartbeatHealthy => Heartbeat.HasValue && DateTime.UtcNow.Subtract(TimeSpan.FromMinutes(2.5)) < Heartbeat;

// Then, inside a minutely task:
 if (!IsHeartbeatHealthy)
{
    Logger.LogError("Unhealthy heartbeat detected, resetting websocket connection.");
    await connection.StopAsync();
}
```

As you can see despite the minutely heartbeat, I've got a safety threshold of 2 and a half minutes to provide some wriggle room in case there is some latency.

We have an implementation of this in .NET Core 2.1 which is working as expected, however I am open to making any changes to this logic if you feel this pattern is not doing us any favours. The only reason we implemented this in the first place was to ensure long running connections were kept alive, having worked with SignalR Core since the preview days we've come up with this solution to ensure there are no issues but I am open to suggestions.

**Comment by BrennanConroy** [comment]
> The only reason we implemented this in the first place was to ensure long running connections were kept alive

SignalR does this for you. If you look at the logs or network traffic, you'll see Ping messages, those are so that we make sure the underlying connection is still active. Otherwise you'll see the connection close and you can handle reconnecting or enable automatic reconnect.

> From what I can see it looks like `UpdateHeartbeat`'s invocation doesn't complete in a valid amount of time which is causing this.

From your logs the invocation takes less than 100 milliseconds to be sent and get a response.

**Comment by davidfowl** [comment]
The recommendation would be to remove your heartbeat code completely.

**Comment by pielegacy** [comment]
I'll remove the forced closing of the connection if the heartbeat is unhealthy, if any issues still persist past this I'll provide the logs as at least then there are no outside factors that should be causing this issue.

**Comment by pielegacy** [comment]
Removing the heartbeat assertion in the agent has shown that you are right and the agent is still connected to the API. 

It looks like the issue is in our code for ensuring the heartbeat is up to date, we implement the following hosted service to request the heartbeat from every agent:

```cs
public class AgentMonitoringService : IHostedService
    {
        private readonly ILogger<AgentMonitoringService> _logger;
        private readonly IHubContext<TaskQueuesHub, ITaskQueuesHub> _taskQueuesHubContext;
        private readonly IHubContext<AgentsHub, IAgentsHub> _agentsHubContext;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="taskQueuesHubContext"></param>
        /// <param name="agentsHubContext"></param>
        public AgentMonitoringService(ILogger<AgentMonitoringService> logger,
            IHubContext<TaskQueuesHub, ITaskQueuesHub> taskQueuesHubContext,
            IHubContext<AgentsHub, IAgentsHub> agentsHubContext) : base()
        {
            _logger = logger;
            _taskQueuesHubContext = taskQueuesHubContext;
            _agentsHubContext = agentsHubContext;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="stoppingToken"></param>
        /// <returns></returns>
        public async Task CheckForHeartbeatsAsync()
        {
            await _taskQueuesHubContext.Clients.All.RequestHeartbeat();
            _logger.LogDebug("Agent heartbeats requested, checking again in 1 minute.");
            await _agentsHubContext.Clients.All.HeartbeatsUpdated();
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Starting Agent Monitoring Service.");

            while (!cancellationToken.IsCancellationRequested) 
            {
                await Task.Delay(60000);
                await CheckForHeartbeatsAsync();
            }

            //return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Stopping Agent Monitoring Service.");
            return Task.CompletedTask;
        }
    }
```

From my understanding this service has been incorrectly implemented in `StartAsync`, as the initial task should not be a long running awaited task and instead should kick off something like a threading timer.

I will make this change and test it over the next couple of days, but I will close this issue as I can't see any issues with SignalR. Thanks again for your help, it's taught me a lot about debugging these issues 😊

**Comment by davidfowl** [comment]
Do you need this background service at all? What happens if you don't have it? What logic relies on the heartbeat in the database? There might be another more efficient way to do this...

**Comment by pielegacy** [comment]
We use this pattern to basically provide a visual indication in the UI as to when the last time the agent was successfully connected to the service.

When the request for a heartbeat is sent out over the service, the agents respond back with a SignalR method invocation on the API which stores the current UTC time against the record for the connected agent in the DB. 

We do this so that we can ensure the user has a visual understanding of what agents they have connected to their application and if they can be used by the app.

**Comment by davidfowl** [comment]
Sounds like a presence implementation, here's generally how you would do this with SignalR:

- Track all connections for each server in a concurrent dictionary, in OnConnectedAsync and in OnDisconnectedAsync remove the connection (you can use the connection id as the key). We'll call these "local connections".
- Next you need to do 2 things:
    1. On some interval, loop over all local connections and update the last seen time (heartbeat) in the database.
    2. After updating local connections, loop over all connections in the database that have "expired" the last seen time is above some threshold and remove them from the database. After doing this you send a message to the all connected clients notifying them of the disconnected clients.

**Comment by pielegacy** [comment]
Thank you for the recommendation, I'll log something internally to use this pattern only as I can see the benefit in checking the heartbeat this way as opposed to the old way

**Comment by davidfowl** [comment]
>  only as I can see the benefit in checking the heartbeat this way as opposed to the old way

- It handles the case where the app crashes and there are orphaned connections in the database that never triggered OnDisconnected.
- It does the heartbeat update in batches (single DbContext operation) instead of one per connection.
- It removes a bunch of codez
