### ISSUE TITLE
Microsoft Graph support

### ISSUE THREAD

**Issue by dcuccia** [dotnet/aspnetcore#22066]
The [Microsoft Graph API](https://github.com/microsoftgraph/microsoft-graph-toolkit) seems very cool. But Javascript.

Can we please have Blazor-ified Graph components, because C#?

**Comment by javiercn** [comment]
@dcuccia thanks for contacting us.

Those components seem to be Web Components. It should be pretty doable for you or anyone else to use them out of the box with a bit of JS interop to perform initialization.

This is not something we would tackle ourselves, but you can file an issue with the MS Graph folks if you want them to provide an out-of-the-box blazor experience.

**Comment by dcuccia** [comment]
@javiercn will do, thanks!

**Comment by dcuccia** [comment]
Breadcrumb to the Graph ticket: https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/82
