### ISSUE TITLE
Requirement to support Identity Tokens in Microsoft.AspNetCore.Components.WebAssembly.Authentication

### ISSUE THREAD

**Issue by allderidge** [dotnet/aspnetcore#22069]
Are there any plans to expose a reliable way of accessing the identity token obtained from the Identity Provider?

I require a means to send the users identity token to a backend web service in order to identify that user and authorise them dependent on groups claims present in the token. Ideally the token would be automatically refreshed in the background without triggering a restart of the Blazor app.

I have a working solution that obtains the token directly via Java Script interop using the following JS function after checking the user is authenticated in c# :

<code>
        class a {
            async getToken() {
                var user = await window.AuthenticationService.instance._userManager.getUser();
                return user.id_token;
            }
        }

        window.IdentityTokenFetch = new a();
</code>

The token retrieval in C# is:
<code>
        private readonly IJSRuntime _jsRuntime; // injected
        private readonly AuthenticationStateProvider _authenticationStateProvider; // injected

        public async Task<string> FetchTokenAsync()
        {
            var state = await _authenticationStateProvider.GetAuthenticationStateAsync();
            if (state.User.Identity.IsAuthenticated)
                return await _jsRuntime.InvokeAsync<string>(
                    "IdentityTokenFetch.getToken");
            return null;
        }

</code>

OIDC configuration in Program.cs is:
<code>
            builder.Services.AddOidcAuthentication(options =>
            {
                options.ProviderOptions.Authority = "https://login.microsoftonline.com/{directoryid}/v2.0";
                options.ProviderOptions.ClientId = "{applicationid}";
            });
</code>

This approach works but has limitations in that the identity token could have expired and isn't part of an official API.

I'm testing using Azure AD as a test Identity Provider using the standard non azure specific libraries. After configuring the application in Azure I can successfully obtain an identity token.

First raised as feedback to the documentation: https://github.com/dotnet/AspNetCore.Docs/issues/18401

cc: @guardrex

**Comment by javiercn** [comment]
@allderidge thanks for contacting us.

You should not use the ID token for authorization purposes. That's what the access token is for. I would recommend that in your case you change the configuration in your identity provider to include the information you need for authorization within the access token.

While your solution "works", I would discourage you from relying on the AuthenticationService API as that is an implementation detail we might change in the future.

As I said above, the appropriate way of doing this is to include the appropriate information in the access token, not use the ID token as a means for performing auth.

**Comment by allderidge** [comment]
I agree that in many scenarios the ID Token should not be used to authorise services.

This is for a scenario where there is only one service tied to one application registered with the Open ID Connect Provider. The service requires user profile information to record audit information against and group/role membership information in order to authorise that user. The ID token will only be consumed by the one application and is tied to that application via the aud claim. Generating and configuring an access token isn't required in this case.

For example; the ID token issued by Azure AD is perfect, it provides the users ID, name and email address along with their group membership information. I'm unsure how I would configure Azure AD to issue an access token with these claims.

FYI I'm porting a WPF based application that uses the C# Framework desktop Azure AD libraries (Microsoft.Identity.Client).

**Comment by javiercn** [comment]
@allderidge thanks for the details.

From a security perspective that's not right.  The ID token is for the app, which in this case is the Blazor Wasm app and not for the API (hosted in your server)

You can configure AAD to emit groups and anything you need into the access token. See [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-group-optional-claims) for details.

If you manage to make the groups, etc; appear on the ID token, you can make them appear on the access token too. That's the way we recommend doing this.

If we see more demand for accessing the ID token, we might consider adding APIs for this, but I don't think using the ID token for auth is a legit reason.

The main difference here is that in the first case you have a WPF app (and are likely talking directly to the DB) while in this case you have a SPA (way less trusted than a desktop app) and an API, which lives in a completely separate environment.

**Comment by allderidge** [comment]
@javiercn Thanks for the speedy reply.

FYI the WPF does operate in a similar way to the Blazor App, i.e. its runs as a smartclient in an un-trusted environment and communicates via Web Service Calls to backend services. So the Blazor conversion is pretty much a refactor of the non-ui code to remove framework and large nuget package dependencies combined with a re-write of the WPF forms as Razor pages attaching to the ViewModels.

We've benefited so far using the reduced complexity of just using the ID Token when integrating with different Open ID Connect providers as well as helping to reduce Azure AD configuration. From my perspective I don't see there being a difference between the ID token with openid profile and email scopes and an access token with the same claims. The server should not be able to use the ID token to request additional access tokens for resources unrelated to itself as the ID token is issued against a client that is specific to the one backend service.

I'll see how I get on with getting an access token from Azure AD using the library (and Microsoft.Authentication.WebAssembly.Msal), I haven't managed to get any access tokens generated so far.

**Comment by allderidge** [comment]
@javiercn I've updated the issue after some investigation.

I've successfully now retrieved an Access Token from Azure AD via the libraries.

In order to achieve this the response_type in the setup must be set to "id_token token" as follows:

<code>
           builder.Services.AddOidcAuthentication(options =>
            {
                options.ProviderOptions.Authority = "https://login.microsoftonline.com/{directoryid}/v2.0";
                options.ProviderOptions.ClientId = "{clientid}";
                options.ProviderOptions.ResponseType = "id_token token";
            });
</code>

With this change an access token can be retrieved with via:

`var requestAccessToken = await AuthenticationService.RequestAccessToken();
requestAccessToken.TryGetToken(out var at);`

With a standard Azure AD setup the access token issued is exactly the same as the ID token but I think this is Identity Provider specific behaviour. I could what I need though without direct access to internal Java Script variables.

The change makes sense when looking at the implicit flow in OIDC spec, but there might need to be support in the library to make it obvious.

Without this change the following happens when configured against Azure AD:

TryGetToken causes the following exception:
`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 80.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 80.. See InnerException for more details. ---> `System.Text.Json.JsonException:` The JSON value could not be converted to System.DateTimeOffset. Path: $.token.expires | LineNumber: 0 | BytePositionInLine: 80. ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a string.`

And the libraries make this request for the access token:
`https://login.microsoftonline.com/{directoryid}/oauth2/v2.0/authorize?
client_id={clientid}&
redirect_uri=https%3A%2F%2Flocalhost%3A44337%2Fauthentication%2Flogin-callback&
response_type=id_token&
scope=openid%20profile&
state=_state_&nonce=_nonce_&prompt=none&
id_token_hint=_id token hint_`

The response contains no access token : 
`https://localhost:44337/authentication/login-callback#id_token=_id token_&session_state=_session state_`

**Comment by javiercn** [comment]
@allderidge you should use the `Microsoft.Authentication.WebAssembly.Msal` if you are talking to AAD. Using OIDC client is possible, but you'll have to jump through several hoops.

Using the raw OIDC library against Azure AD is not something we actively test, since we ship a dedicated package for Azure AD scenarios.

See the docs [here](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1)
