### ISSUE TITLE
Make GenericWebHostService public

### ISSUE THREAD

**Issue by pableess** [dotnet/aspnetcore#22079]
I'm curious on the reasoning for making GenericWebHostService internal instead of public.

It would be useful to be able to host Http Workloads as a hosted service.

An example would be where you conditionally want to host Http services based on a HostConfiguration setting passed in via command line, environment variable or whatever.

With the current implementation I don't see how this is possible without ugly workarounds like having multiple hosts or needing to build a separate Configuration before creating and configuring the Host.

**Comment by Tratcher** [comment]
Registering the service isn't enough, you also have to configure it. The setup code is a little odd due to back compat concerns. That would probably have to be re-worked.
https://github.com/dotnet/aspnetcore/blob/f990751f549417bade35e4c98d3d6ca07ecba43f/src/Hosting/Hosting/src/GenericHostWebHostBuilderExtensions.cs#L9-L15

**Comment by BrennanConroy** [comment]
You can get settings from config on the builder with the `GetSetting` method. Then apply your conditional services to the builder.

```csharp
IWebHostBuilder.GetSetting("config_key");
```

**Comment by pableess** [comment]
Getting settings from within the ConfigureWebHostDefaults configuration callback doesn't help to determine if https services should be added based on host configuration settings.  At this point the WebHost has already been added.

**Comment by BrennanConroy** [comment]
> needing to build a separate Configuration before creating and configuring the Host

That's the expected behavior in this scenario.
