### ISSUE TITLE
Parsing a cookie fails when there is an invalid key in the cookie value

### ISSUE THREAD

**Issue by akosdudas** [dotnet/aspnetcore#22077]
### If cookie value contains `Discard` the entire cookie parsing yields an empty set

We are using `SetCookieHeaderValue.ParseList` (https://github.com/dotnet/aspnetcore/blob/master/src/Http/Headers/src/SetCookieHeaderValue.cs) to parse a Set-Cookie response. The http response from which the cookie is parsed is the following:

![image](https://user-images.githubusercontent.com/11335181/82560533-ed1e0a00-9b71-11ea-9dcb-2807b75a41c3.png)

This `Discard` in there makes the entire parse return an empty list. If this `Discard` is removed, or it is replaced with `Secure`, parsing succeeds.

#### Unit test project based on `Microsoft.NET.Sdk.Web`

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>

</Project>
```

#### Unit test code

```csharp
using Microsoft.Net.Http.Headers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CookieParserTest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            // Ok
            var cookies = SetCookieHeaderValue.ParseList(new[] { "PLAY_SESSION=aaa; Version=1; Path=/aaa/" });
            Assert.AreEqual(1, cookies.Count);

            // Ok
            cookies = SetCookieHeaderValue.ParseList(new[] { "PLAY_SESSION=aaa; Version=1; Path=/aaa/; Secure" });
            Assert.AreEqual(1, cookies.Count);

            // Fail
            cookies = SetCookieHeaderValue.ParseList(new[] { "PLAY_SESSION=aaa; Version=1; Path=/aaa/; Discard" });
            Assert.AreEqual(1, cookies.Count);
        }
    }
}
```

### Requires ASP.NET SDK
- Tested on ASP.NET Core version 3.1.4 (project is based on sdk `Microsoft.NET.Sdk.Web`)
- When using NuGet `Microsoft.Net.Http.Headers` 2.2.8 directly in a project based on `Microsoft.NET.Sdk` parsing is actually correct

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/blob/4e2584a04ad3fe42cf87dc20866bec45946952f5/src/Http/Headers/src/SetCookieHeaderValue.cs#L501-L507
Looks like `Discard=` would be allowed but not `Discard`. Not sure why it has that restriction, the RFC seems to allow just about anything.
https://tools.ietf.org/html/rfc6265#section-4.1.1
```
 set-cookie-string = cookie-pair *( ";" SP cookie-av )
 cookie-av         = expires-av / max-age-av / domain-av /
                     path-av / secure-av / httponly-av /
                     extension-av
 extension-av      = <any CHAR except CTLs or ";">
```

We shouldn't be discarding the values, we should be adding them to a `List<StringSegment> Extensions` so we can round trip the cookie back to a string if needed.

Looks like this behavior was changed in 3.0 by https://github.com/aspnet/HttpAbstractions/pull/1050. The issue claims `extension=value` caused a failure before, but it looks like `extension` might have been allowed by the old code and that PR unwittingly reversed it. Both should be allowed.

**Comment by ostorc** [comment]
Hi, I have started working on this issue and I want toi known before I start writing tests for this issue, if my implementation (#22181) looks good, or if there is anything which I should change. Thanks!
