### ISSUE TITLE
Provide a better user experience when the browser doesn't support WebAssembly

### ISSUE THREAD

**Issue by waelkdouh** [dotnet/aspnetcore#22095]
Currently when you run a blazor app inside IE the page gets stuck on the loading indicator. Its hard for new comers to understand that IE doesn't support webassembly.

It would be great if we can provide out of the box experience where users will be notified that the browser is not supported and suggest installing alternative browses.

**Comment by javiercn** [comment]
@waelkdouh thanks for contacting us.

This is something you can do yourself in the template by modifying the built-in template to show some more informative text, or by manually starting Blazor `Blazor.start`, capturing any loading error and displaying a more informative message, or check for `WebAssembly.instance` before calling Blazor.start

**Comment by waelkdouh** [comment]
Hi Javier what do you mean exactly by manually starting Blazor Blazor.start?

**Comment by javiercn** [comment]
@waelkdouh See the snippet in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#custom-boot-resource-loading. It returns a promise and you can decide what to do after it completes either successfully or with an error.

**Comment by waelkdouh** [comment]
But promises are not supported by IE 11. Its an es2015 feature.
