### ISSUE TITLE
Showing links based on user access to groups in AAD

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#22108]
Copied from DevDiv feedback ticket 1123477: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1123477

Hi, 

I am currently developing a website to enable my theatre group to be able to do things remotely but i am having some difficulties. 

I am unable to show links based on the access to groups in the AAD. here is the code i have. it just doesn't work.
I also have had an issue when i have logged in that im getting the error "You do not have permission to view this directory or page."

Controller/Startup are included in https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1123477

**Comment by blowdart** [comment]
As this has come from the VS feedback we don't really get enough information to figure out whats going on, or indeed the user.

So if you're the user of this feedback ticket you should have gotten a link to here, could you please post a sample repo. You may also want to examine your user principal to see if roles are actually present.

I'm moving this to discussions for now so it doesn't get auto-closed.
