### ISSUE TITLE
16.7-Preview2 - Validate Razor tooling in Visual Studio Codespaces

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22112]
## Instructions
It's up to you to validate all features, if applicable, done in the [16.7-preview2 milestone](https://github.com/dotnet/aspnetcore/milestone/103?closed=1) (not just your own). Given that this is tooling validation, features and bug fixes should be relatively easy to validate given they don't require complex setups to ensure something works.

As part of this process don't be afraid to experiment outside the context of the issues within the milestone.

## Filing issues
All issues found should be filed under the **Razor.Tooling** milestone and assigned to the **Razor Tooling vNext** project. Lastly give those issues the appropriate labels and mention them under this issue before closing.

## Completing validation

Once you're done with your validation, link to any issues found and then close this issue and unassign yourself. If you are the last to unassign yourself close the issue and move it to the "Done" column in the Razor Tooling vNext project.

## Validation Build

**Visual Studio Client Release:** @ajaybhargavb Could you please provide a link to the VS client release + ping this issue once things are unblocked? This can be pulled from the vsbuild dashboard.

**Visual Studio Server Release:** Once the Razor scenario has been unblocked you should be able to use the Internal Premium build.

**Comment by ryanbrandenburg** [comment]
This is impossible ATM because we don't have a way to have our latest tooling available within the VSCodespaces instance.
