### ISSUE TITLE
16.7-Preview2 / 5.0.0-Preview6 - Validate Razor tooling on Windows

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22110]
## Instructions
It's up to you to validate all features, if applicable, done in the [16.7-preview2 / 5.0.0-preview6 milestone](https://github.com/dotnet/aspnetcore/milestone/103?closed=1) (not just your own). Given that this is tooling validation, features and bug fixes should be relatively easy to validate given they don't require complex setups to ensure something works.

As part of this process don't be afraid to experiment outside the context of the issues within the milestone.

## Debug Adapter Test scenarios

- [x] Blazor WASM Hosted
- [x] Blazor WASM Standalone

## Filing issues
All issues found should be filed under the **Razor.Tooling** milestone and assigned to the **Razor Tooling vNext** project. Lastly give those issues the appropriate labels and mention them under this issue before closing.

## Completing validation

Once you're done with your validation, link to any issues found and then close this issue and move it to the "Done" column in the Razor Tooling vNext project.

## Validation Build
**O# release:** https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.22.0

You can install this VSIX by downloading the VSIX from above and then installing it by going to your extensions pane in VSCode -> Clicking the ... -> Install from VSIX
![image](https://user-images.githubusercontent.com/2008729/72949076-0df95e80-3d3c-11ea-8d25-aa9a82a29d2b.png)

**Comment by noahbkim** [comment]
Everything seems to pass besides the issue where the `=` and `:` commit characters appears in the resultant quotes:

```
<input @onkeypr|    (press =)
<input @onkeypress="=|">
```

**Comment by noahbkim** [comment]
Related issue here: https://github.com/dotnet/aspnetcore/issues/22150

**Comment by NTaylorMullen** [comment]
I assume this is done and can be closed out?

**Comment by captainsafia** [comment]
Yep!

**Comment by captainsafia** [comment]
New attach feature in debugger works on Windows.
