### ISSUE TITLE
 The oauth state was missing or invalid. Unknown location

### ISSUE THREAD

**Issue by DenVys** [dotnet/aspnetcore#22125]
I created simple ASP.NET Core 3 Web API application. I added new external login oauth provider (let it be Google) and nothing else. Also I created related oauth account that contains my app settings. After all I get this error. 

What I'm trying to do is to log in with external provider to get user data and then use it create JWT token. But everything fails after login provider response.

```
Exception: The oauth state was missing or invalid.
Unknown location
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

Call stack

```
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Worth to mention, that I can see the external provider login screen and I get a response from the external provider. But something on my side after a successful response goes wrong.
Also, I tried different providers (Google and GitHub) and in both cases I have the same result.
Here is a reproductable repo [github repo](https://github.com/DenVys/oauth-state-corruption)
- add clientid and serverid in appsettings.json
- run app
- call "https://localhost:44319/api/authentication/token?redirect=Hell&providerName=Google"
- log in using your account
- get exception

**Comment by Tratcher** [comment]
Here's your issue:
https://github.com/DenVys/oauth-state-corruption/blob/a5b2cc25e05ba1dd27766f139e8ffd589bc75b20/AuthService/AuthService/Startup.cs#L44
```
googleOptions.CallbackPath = "/api/authentication/ExternalLoginBack";
```
CallbackPath is not supposed to refer to a controller, it refers to a unique path handled by the auth middleware (defaults to /signin-google). It will redirect back to your controller when it's done.

**Comment by DenVys** [comment]
Okay. Thank you very much. But then which middleware is responsible for handling these requests ?
I removed googleOptions.CallbackPath option so now it is default. I updated signin app settings. And still, I have the same issue. 
I thought `services.AddAuthentication()` is enough. Am I wrong ?

**Comment by DenVys** [comment]
All right

Adding 
`services.AddRazorPages();` 
and 
```
app.UseEndpoints(endpoints =>
{
    ...
    endpoints.MapRazorPages();
});
```
fix the problem.
I wonder is it the right way to add signin-provider callback ?
Because, I don't use razor pages in this app at all. But I have to add the whole razorpages middleware. Is it okay ?

**Comment by blowdart** [comment]
The middleware responsible is the OAuth handler that the Google hander inherits from. 

If you look at the source it eventually ends up in [RemoteAuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs). 

There are a couple of things in here to look at here to understand what's going on

* [ShouldHandlerRequestAsync()](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L39) is where the decision is made if the handler is going to take care of the inbound request, which it does by looking at the CallbackPath in options

* That's in turn is checked in [HandleRequestAsync() ](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L44) which every [IAuthenticationRequestHandler](https://github.com/dotnet/aspnetcore/blob/5ff9ed68d1cf6c89d72d27a69b00ed0ecd34daed/src/Http/Authentication.Abstractions/src/IAuthenticationRequestHandler.cs) middleware has.

@pranavkm is MapRazorPages really necessary here for authentication middlewares to intercept requests?

**Comment by Tratcher** [comment]
> But then which middleware is responsible for handling these requests ?

`app.UseAuthentication();` handles those. Razor Pages shouldn't affect this at all...

Can you share a Fiddler trace file and the server debug logs?

Did you also update the github provider?
https://github.com/DenVys/oauth-state-corruption/blob/a5b2cc25e05ba1dd27766f139e8ffd589bc75b20/AuthService/AuthService/Startup.cs#L55

**Comment by DenVys** [comment]
So, you actually were right. There is no need for `services.AddRazorPages();` . I'm sorry, my bad. 
Anyway, the problem was that I'd misunderstood what is `options.CallbackPath` from ConfigureServices method in the first place. Thanks for your help.

For anyone who is searching here for answers working code is below (some lines are ommited).

#### startup.cs
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication()
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddGoogle(googleOptions =>
                {
                    googleOptions.ClientSecret = Configuration["..."];
                    googleOptions.ClientId = Configuration["..."];

                    // used to store auth result after sign in
                    googleOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme; 
                });

            services.AddControllers();
        }
```
```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            ....
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

#### authcontroller.cs
```
        // GET: api/authentication/token?...
        [HttpGet("token")]
        public ActionResult Auth()
        {
            var properties = new AuthenticationProperties()
            {
                // actual redirect endpoint for your app
                RedirectUri = $"/api/authentication/MyExternalLoginBack",
                Items =
                {
                    { "LoginProvider", providerName },
                },
                AllowRefresh = true,
            };

            return Challenge(properties, "Google");
        }
```
