### ISSUE TITLE
Incorrect C# Coloring Within .razor @code block

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#22123]
1. Create new blazorserver app
2. Open `Pages/FetchData.razor`

![image](https://user-images.githubusercontent.com/14852843/82619128-f1562180-9b89-11ea-962a-613fbaac3719.png)

Note: coloring of `DateTime.Now` and `await` is improper.

**Comment by KieranDevvs** [comment]
`await` is also highlighted wrong.

**Comment by ryanbrandenburg** [comment]
![image](https://user-images.githubusercontent.com/14987221/96312380-52124a80-0fc0-11eb-82d7-6ef70fa63773.png)
Seems to have been resolved.

**Comment by TanayParikh** [comment]
> ![image](https://user-images.githubusercontent.com/14987221/96312380-52124a80-0fc0-11eb-82d7-6ef70fa63773.png)
> Seems to have been resolved.

Does it work specifically `DateTime.Now` within a function as well?

**Comment by ryanbrandenburg** [comment]
That example was from within a function.
