### ISSUE TITLE
Blazor Hosted WebAssembly RTM(3.2) api calls error when published to Azure App Service

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#22128]
I created Blazor WebAssembly Hosted app using default template and enabled PWA during project creation.
The app works fine when running locally.

But when published to Azure App Service. the API call are failing.
The fetch eather data results into the following erro.
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
System.NotSupportedException: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
  at System.Net.Http.Json.HttpContentJsonExtensions.ValidateContent (System.Net.Http.HttpContent content) <0x217d6e8 + 0x0009e> in <filename unknown>:0 
  at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync[T] (System.Net.Http.HttpContent content, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x217d518 + 0x00006> in <filename unknown>:0 
  at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T] (System.Threading.Tasks.Task`1[TResult] taskResponse, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x21363e0 + 0x00150> in <filename unknown>:0 
  at BlazorApp3.Client.Pages.FetchData.OnInitializedAsync () <0x2103b68 + 0x000ee> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x1ed8e98 + 0x00154> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x20d7318 + 0x000ca> in <filename unknown>:0 

```

Other custom api calls are also failing for method not supported even though i have explicity marked httpost on the api method call.

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Check the content-type of the response in your API call. It likely is `application/text` or something like that, and as a result the client is failing to parse the response.

**Comment by nssidhu** [comment]
First thing, everything works fine when running locally. why ?
The error only occurs in the published version on Azure App Service.

secondly i did manually add content type and still runing into error, seems like it is getting ignored unless i am doing it incorrectly. If that matters this is using PWA & hosted app.

 ```
 Http.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");

```
Again want to highlight that this problem started appeargin after updating to RTM(3.2)

![HttpError](https://user-images.githubusercontent.com/3267605/82678012-83077280-9c0e-11ea-9af0-95a768327fb8.png)

**Comment by javiercn** [comment]
@nssidhu thanks for the additional details.

From what I can see in the response, the content-type is text/html. That likely means that you are not returning json from the server. I would check the response contents on the browser to further determine what's going on.

**Comment by nssidhu** [comment]
Here is another api call that is failing.
I am lost on how to fix this. 
As i mentioned earlier, this was all working fine untill i updated to RTM version of Blazor.

`POST https://sidblazorapp.azurewebsites.net/api/Account/Login 405 (Method Not Allowed)`

```
[AllowAnonymous]
[HttpPost]
[HttpOptions]
[Produces("application/json")]
public async Task<IActionResult> Login(SignInUserModel loginModel)
{
......................


}
```

![HttpError1](https://user-images.githubusercontent.com/3267605/82679584-bd720f00-9c10-11ea-9949-66cebb08dc21.png)

**Comment by nssidhu** [comment]
i understand issue is related to content-type, but not sure how to fix/get around it.
i can privately share the sample if that can help.

**Comment by javiercn** [comment]
@nssidhu a 405 is coming from the server.

Are you by any chance trying to do this cross-origin?

**Comment by nssidhu** [comment]
NO, this is using the the Hosted WebAessembly visual studio 2019 preview template.

It is very easy to reproduce, just create new Balzor WebAssembly using VS 2019 preview(most updated one) hosted app( with PWA also selected) and publish it to Azure App service.

It is still working fine locally on my machine, issue comes up in published version to Azure App Service.
(again issues started appearing after upgrade to blazor RTM version).

i tried the following on the server side, but that did not help either.

```
            .AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    );

                options.AddPolicy("signalr",
                    builder => builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()

                    .AllowCredentials()
                    .SetIsOriginAllowed(hostName => true));
            });
```

again i can share my sample if needed.

**Comment by nssidhu** [comment]
The problem is still unresolved and looks like a very major one.

**Comment by JoeGER94** [comment]
@nssidhu i agree with you. I ran into the same Problem. 
I played a little bit around with the template and always published it on local iis and suddently i ran into this error.
I started comparing my solution with a new standard template and found no differences yet.

**Comment by javiercn** [comment]
@nssidhu where in azure app service are you deploying your app? I just tried this and I'm not able to reproduce it.

**Comment by nssidhu** [comment]
Javiercn

i have published it to Azure App Service (windows based). 
[https://sidblazorapp.azurewebsites.net/].

I can consistantly reproduce it using the newsest template.
I have source code that i can share privately as well if that would help.

Since in the Blazor WebAssembly there are three project(client/Server/Shared), I am publishing the Client project, i just want to make sure i am publishing the right one.

**Comment by javiercn** [comment]
@nssidhu you need to publish the server project.

I can't repro this with the 3.2 RTM template, that's why I'm asking

**Comment by nssidhu** [comment]
I has earlier tried it, but will give it another try and update

**Comment by bancroftway** [comment]
I just encountered this issue. I did not even publish the app yet. I started the app from the basic VS template code; the app was working fine, and I simply cut-paste all the files from one folder to another for the purpose of checking it into a repo. Now I am encountering on the fetchdata page.

**Comment by nssidhu** [comment]
I was able to resolve the issue. In summary i ran into multiple problems after upgrade.

1) The main problem was due  to linker and Authorization used together, which broke my code when compiled in Release mode. That is the reason that it would work perfectly on my local machine, but failed when published to Azure App, becuase when publishing it would compile in release mode.
2) Secondly since i was creating Blazor Hosted WebAssembly with PWA, when i create brand new app and published it, since it was PWA it was still running the cached version of App which gave me impression that even the newly created app fails as well, whereas it was previous cached version which was running. To over come this i resorted to going into F12 mode and then doing "Empty cache and hard reload".
3) Looks like the failure for API calls was related to reading a config value in the startup which was missing on Azure App. there were other API call issue like method not support i am not sure how that got resolved(I am guessing i might have published client project instead of server project)

So in all i ran into multple issues and PWA; becuase it was caching the app locally aggravated my problems.

**Comment by MichaelJimma** [comment]
@nssidhu I still have this is issue for days and I couldn't resolve it. Could you please provide us a step by step guide how you resolved this issue.

**Comment by parad74** [comment]
The same problem if I publish WebAPI to folder  and run WebAPI from publish folder => error.
Run from VS => work without problem.

**Comment by parad74** [comment]
I found problem, my database was not includ in self-contaner (file <name>.db) and didn't find db when run from publish folder.

**Comment by HillPhelmuth** [comment]
I ran into this problem too, It results in publishing from the client rather than the server project. This drove me nuts, because I initially published from the server, but when I set up my CI/CD through Azure DevOps, it defaulted to publishing from the client project. Once I disconnected the ADO pipeline and republished from VS, all was fine.
