### ISSUE TITLE
Showing offset x and y for mouseeventargs

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22127]
I need the ability to show the x and y coordinates of the element being used on and not just the x and y relative to the entire window.   I know in javascript, there is the ability of showing that.  However, it would be too slow the javascript has to constantly communicate with the c# to give it that information.

**Comment by KieranDevvs** [comment]
You can use the DOM event `OnMouseMove` that accepts the argument `MouseEventArgs`.
The argument contains both the client position and the screen position of the mouse. If you want to find where the mouse is relative to an element, you can do some simple relative maths to calculate it.
![image](https://user-images.githubusercontent.com/21192520/82694862-eff52980-9c5b-11ea-9c5c-30bf8cd7d369.png)

**Comment by musictopia2** [comment]
How would somebody figure out the relative position?  For the example, i saw the x position was 329 but the width and height was 300.  That means if you wanted to know what position relative to that div, i know that javascript has offset x and y but that is not put into the MouseEventArgs.

**Comment by KieranDevvs** [comment]
@musictopia2 You can use JS interop to gather the element position and then you can use the delta between the client space to figure out the element mouse position offset. You only need to call the interop once to obtain the position of the element, and then you can bind this logic to events such as window resizing to update this thus bypassing performance concerns within the mouse move event.

I have done some digging and it would appear that the `MouseEventArgs` is getting `Offset` values but I don't believe they're in the current release. If you hold on, im sure they will be released soon (hopefully? See more within this current thread: https://github.com/dotnet/aspnetcore/pull/20478)

**Comment by arviedelgado** [comment]
`OffsetX/OffsetY` is added to `MouseEventArgs` here #20478

I also need this and actually the first thing I checked after the recent releases.

Apparently, this is only available if targeting .NET 5.0.0-preview.4.

**Comment by zHaytam** [comment]
When I installed .NET 5 preview4 and changed the `TargetFramework` in my Blazor WASM project to `net5.0`, I got the error `System.TypeLoadException: Could not resolve type with token 01000010 from typeref (expected class 'System.Threading.Tasks.Task' in assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')`, is that normal?

**Comment by arviedelgado** [comment]
> When I installed .NET 5 preview4 and changed the `TargetFramework` in my Blazor WASM project to `net5.0`, I got the error `System.TypeLoadException: Could not resolve type with token 01000010 from typeref (expected class 'System.Threading.Tasks.Task' in assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')`, is that normal?

.NET 5.0 preview4 currently doesnt support Blazor WASM #22208

**Comment by mkArtakMSFT** [comment]
This is going to be fixed in .NET 5.0 and the change has already been merged.
