### ISSUE TITLE
Changing blazor web assembly binary/framework location

### ISSUE THREAD

**Issue by NateKomodo** [dotnet/aspnetcore#22133]
### Is your feature request related to a problem? Please describe.
I am trying to host a blazor web assembly app via ASP.NET core. I want the server to serve index.html and provide the web api (All of this i have already done) but for the _framework folder with the binaries and wasms to be on an external CDN or S3 system. As far as im aware blazor just fetches _framework/files on the same site, which prevents the use of external CDNs

### Describe the solution you'd like
I'd like to be able to change the request path for the framework files, such as listing an external path for it to retrive the files from, such as a CDN.

**Comment by javiercn** [comment]
@NateKomodo thanks for contacting us.

This is possible already. See the [Custom boot resource loading](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/) section in this post.

**Comment by NateKomodo** [comment]
Didnt see that, thanks
