### ISSUE TITLE
[.NET Core SDK build 5.0.100-preview.5.20270.37] Message is Incomplete error in OpenMu app

### ISSUE THREAD

**Issue by DotNetAppCompatFeiWang** [dotnet/aspnetcore#22132]
### Describe the bug
Message is Incomplete error in OpenMu app
In signalr.js file we get this error:

signalr.js:2857 Uncaught Error: Message is incomplete

    at Function.TextMessageFormat.parse (signalr.js:2857)
    at JsonHubProtocol.parseMessages (signalr.js:4852)
    at HubConnection.processIncomingData (signalr.js:2357)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1923)
    at WebSocket.webSocket.onmessage (signalr.js:4740)

**Message on .NET 5 Prev5 :**
{"type":1,"target":"Initialize","arguments":[[{"maps":[],"id":0,"description":"Server 0","state":0,"onlinePlayerCount":0,"maximumPlayers":1000,"type":1},{"maps":[],"id":1,"description":"Server 1","state":0,"onlinePlayerCount":0,"maximumPlayers":1000,"type":1},{"maps":[],"id":2,"description":"Server 2","state":0,"onlinePlayerCount":0,"maximumPlayers":1000,"type":1}]

**Message on   .NET 5 Prev4 :**
{"type":1,"target":"Initialize","arguments":[[{"maps":[],"id":0,"description":"Server 0","state":0,"onlinePlayerCount":0,"maximumPlayers":1000,"type":1}],[{"settings":{"id":"abe33204-0ca9-4357-bb01-825aa1e96fab","client":{"id":"0b342393-7dc5-4d03-8999-a9dbfd0cb987","season":6,"episode":3,"language":1,"version":"MTA0MDQ=","serial":"azFQazJqY0VUNDhteEwzYg==","description":"Season 6 Episode 3 GMO Client"},"serverId":0,"description":"Connect Server (Season 6 Episode 3 English)","disconnectOnUnknownPacket":true,"maximumReceiveSize":6,"clientListenerPort":44405,"timeout":"00:01:00","currentPatchVersion":"AQMr","patchAddress":"patch.muonline.webzen.com","maxConnectionsPerAddress":30,"checkMaxConnectionsPerAddress":true,"maxConnections":10000,"listenerBacklog":100,"maxFtpRequests":1,"maxIpRequests":5,"maxServerListRequests":20},"id":65536,"description":"Connect Server (Season 6 Episode 3 English)","state":0,"onlinePlayerCount":0,"maximumPlayers":10000,"type":2}],[],[]]}
### To Reproduce

On the repo machine (https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1129671)
1) On CMD, navigate to C:\Users\appcompat\Documents\OpenMU
2) Run : dotnet MUnique.OpenMU.Startup.dll
3) Wait for admin panel to initialize
4)In Browser, Open http://localhost:1234/admin
Since "C:\Users\appcompat\Documents\OpenMU\MUnique.OpenMU.Startup.runtimeconfig.json" set to 5.0.0-preview.5.20269.6, app will use .NET5 runtime.  This is issue is not repro on .NET Core 3

### Further technical details
- ASP.NET Core version
 Microsoft.NETCore.App 5.0.0-preview.5.20268.9
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20270.37
 Commit:    b262a37641

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20270.37\

Host (useful for support):
  Version: 5.0.0-preview.5.20268.9
  Commit:  f3c276fe20

.NET SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.5.20270.37 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.5.20269.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20268.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.5.20269.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2019

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.5.20270.37: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.4.20258.7: Pass
3). Windows 10 RS5 X64 + .NET Core SDK build 3.1.300:Pass

**Expected Result:**
![expected](https://user-images.githubusercontent.com/34528520/82659401-38f8ae00-9c5b-11ea-916f-4ae0f871c953.PNG)

**Actual Result:**
![actual](https://user-images.githubusercontent.com/34528520/82659406-3ac27180-9c5b-11ea-85eb-8fec10a8708e.PNG)

cc @dotnet-actwx-bot

**Comment by BrennanConroy** [comment]
This is not an issue with SignalR.

Work is being done in System.Text.Json https://github.com/dotnet/runtime/pull/36936
