### ISSUE TITLE
Cookie authentication handler overwrites session key when signing in

### ISSUE THREAD

**Issue by yvztzn** [dotnet/aspnetcore#22135]
Why does [CookieAuthenticationHandler.HandleSignInAsync](https://github.com/dotnet/aspnetcore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L253) delete an existing session key if session store is being used?

```csharp
if (Options.SessionStore != null)
{
    if (_sessionKey != null)
    {
        await Options.SessionStore.RemoveAsync(_sessionKey);
    }
    _sessionKey = await Options.SessionStore.StoreAsync(ticket);
    var principal = new ClaimsPrincipal(
        new ClaimsIdentity(
            new[] { new Claim(SessionIdClaim, _sessionKey, ClaimValueTypes.String, Options.ClaimsIssuer) },
            Options.ClaimsIssuer));
    ticket = new AuthenticationTicket(principal, null, Scheme.Name);
}
```

Is there a reason not to do the following approach?

```csharp
if (Options.SessionStore != null)
{
    if (_sessionKey != null)
    {
        await Options.SessionStore.RenewAsync(_sessionKey, ticket);
    }
    else
    {
        _sessionKey = await Options.SessionStore.StoreAsync(ticket);
    }

    var principal = new ClaimsPrincipal(
        new ClaimsIdentity(
            new[] { new Claim(SessionIdClaim, _sessionKey, ClaimValueTypes.String, Options.ClaimsIssuer) },
            Options.ClaimsIssuer));
    ticket = new AuthenticationTicket(principal, null, Scheme.Name);
}
```

Renewing an existing session key with a new ticket solves our problem.

### The setup

We have configured our application so that it uses cookies as default scheme and OIDC as the default challenge scheme. We also use ProxyKit to allow our SPA to communicate with backend services without having access tokens flying around in the browser. Before forwarding the calls to the backend services we read out the access token and attach it to the forwarded request.

```csharp
app.Map("/backend-api", api =>
{
    api.RunProxy(async context =>
    {
        IConfigurationSection apim = this.Configuration.GetSection("ApiManagement");
        var forwardContext = context.ForwardTo(apim.GetValue<string>("BaseUrl"));

        var token = await context.GetUserAccessTokenAsync();
        forwardContext.UpstreamRequest.SetBearerToken(token);
        forwardContext.UpstreamRequest.Headers.Add("Ocp-Apim-Subscription-Key", apim.GetValue<string>("SubscriptionKey"));

        return await forwardContext.Send();
    });
});
```

The method `GetUserAccessTokenAsync()` is an extension method coming from [IdentityModel.AspNetCore](https://github.com/IdentityModel/IdentityModel.AspNetCore). It refreshes the access token if it is expired before handing it back to the caller. As part of the refreshing logic the new access token is being saved in the user's authentication session.

```csharp
AuthenticateResult result = await _contextAccessor.HttpContext.AuthenticateAsync();
// update authentication result properties with the new access token
await _contextAccessor.HttpContext.SignInAsync(result.Principal, result.Properties);
```

### The problem

In one view of the application our SPA executes 7 REST calls. Chrome executes only 6 of them and sends the 7th as soon as one of the 6 requests were answered. Meanwhile the session key has changed because of the refresh of the access token. For the 7th request `GetUserAccessTokenAsync()` returns null because its session key which comes from the cookie does not exist anymore. This results in an empty bearer token in the authorization header in the forwarded request. So it is very strange that the first 6 calls succeed but the 7th request fails due to 401.

Refreshing the view in the browser a second time will work because the 7th (and also the first 6) request will use the new updated cookie.

**Comment by blowdart** [comment]
@Tratcher Is this to avoid session fixation?

**Comment by Tratcher** [comment]
Just calling renew could cause a session fixation issue. We'd also want to ignore the _sesssionKey for a request if there wasn't an associated ticket available in the store. That way you'd get a new key if you had previously signed out but somehow recycled an old cookie.
https://github.com/dotnet/aspnetcore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L143-L148

Thoughts?

**Comment by yvztzn** [comment]
@Tratcher thank you for your response. I have difficulties following your point. That's also the reason for my late reply. I wanted to think about it.

> That way you'd get a new key if you had previously signed out but somehow recycled an old cookie.

If someone signs out, then the authentication ticket will be deleted from the ticket store.

https://github.com/dotnet/aspnetcore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L349-L352

That way, when the old cookie was recycled, authentication will still fail because of missing identity in the session store. Even for my proposed change because `EnsureCookieTicket()` comes before the execution of session store operations.

https://github.com/dotnet/aspnetcore/blob/2b7e994b8a304700a09617ffc5052f0d943bbcba/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L253-L266

Do I misunderstand you?

**Comment by Tratcher** [comment]
Good point, the sign-out example isn't valid.

I'd still recommend not re-using an old key if there was no matching entry in the ticket store. From the server's perspective these are different sessions. For example I've seen the ticket store used to implement sign-out-everywhere by revoking a session without the client present.

Your renew case might be fine though, there was a matching entry in the store and you're updating it.

**Comment by yvztzn** [comment]
@Tratcher 

> Your renew case might be fine though, there was a matching entry in the store and you're updating it.

Exactly, the store is always up-to-date with the latest authentication ticket.

Glad to see that it will be fixed in the next version.
