### ISSUE TITLE
Blazor wasm UdpClients

### ISSUE THREAD

**Issue by hanigan6** [dotnet/aspnetcore#22140]
### UdpClient Operation not supported
Can't open a Udp connection to talk to LAN devices. 

Occurring when I new up a UdpClient, does throw exception but it is all blank, or can't be view easily while debugging in vs2019.

Working through trying to create a Blazor WASM application to attach to a few LAN smart devices. Where i keep getting an Operation not supported on this Platform. I have found a few articles / issue threads which make it seem like WebSocket support should be supported as long as the wrappers for mono.wasm were there, however for use with the dotnet UdpClient, it appears that that support is not there.

Also I may not be correctly declaring the services through the blazor wasm 3.2 proj. 

### Code
razor component
```
@using System.Net.Sockets
@using System.Net
@inject UdpClient Udp

<button @onclick="@ClickMe">Init client</button>

@code {
    protected void ClickMe()
    {
       
        var ipEndPoint = new IPEndPoint(IPAddress.Any, 5300);
        Udp.Connect(ipEndPoint);
    }
```

I have also tried to add the services to both the projname.Client & projName.Server, program.cs and startup.cs files respectively. With having the page call out to a generic TypeClient class that I created. Always breaks on ```new UdpClient(endpoint)```

 Hopefully this is the right channel to go through. 

### Further technical details
- .Net Core 3.1 - Blazor[WASM] 3.2 - AspnetCore Hosted PWA
- VS2019

**Comment by hanigan6** [comment]
Browser  console error snippet
``` 
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) <0x2df2e48 + 0x0003c> in <filename unknown>:0 
  at System.Net.Sockets.UdpClient.createClientSocket ()
```

**Comment by javiercn** [comment]
@hanigan6 thanks for contacting us.

It is likely that UdpClient and TcpClient are not supported in mono running on WebAssembly as those capabilities are not available to the browser in JavaScript.

**Comment by hanigan6** [comment]
That's what I feared, oh well. I think I might be able to translate some of the stuff into a Websocket call. Or native apps/etc. But definitely throws a wrench in trying to use wasm/ blazor. 
I believe this issue was tracking the WebSocket stuff #10489 or any others that would be helpful?
Any plans to get support around these, or possibly a decent work around?

**Comment by javiercn** [comment]
@hanigan6 I believe you can already use websockets, but I wouldn't expect to be able to use TcpClient or UdpClient since those capabilities are not available in the Browser APIs. Blazor WebAssembly is constrained by the same restrictions as any other web app.
