### ISSUE TITLE
app on blazorserver template colored invalid

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#22149]
<img width="1440" alt="Screen Shot 2020-05-22 at 10 45 57 AM" src="https://user-images.githubusercontent.com/14987221/82694786-bf3fd080-9c18-11ea-8d14-0846adc6084e.png">
This repro's on Linux as well. This seems to be because app is a deprecated HTML tag, and also not a TagHelper. We should either remove the <app> tag for being deprecated, or if it has some sort of special significance in Blazor give it a semantic token and scope.

Props to @TanayParikh for noticing this.

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS given that `app` is deprecated do you have any thoughts here? Makes me think we should update the templates.

**Comment by SteveSandersonMS** [comment]
Yes, I think we were planning to shuffle the default template content about a bit for 5.0 and as part of that expected to change this root element. We'd just replace it with something like `<div id="app"></div>`.

**Comment by NTaylorMullen** [comment]
> Yes, I think we were planning to shuffle the default template content about a bit for 5.0 and as part of that expected to change this root element. We'd just replace it with something like `<div id="app"></div>`.

Is there an issue for that which I can dupe this with?

**Comment by mkArtakMSFT** [comment]
This will be resolved when this will be addressed: https://github.com/dotnet/aspnetcore/issues/11013

The behavior here, however, is by-design.
