### ISSUE TITLE
What is the recommended Polyfill solution from Microsoft for server-side Blazor support IE 11?

### ISSUE THREAD

**Issue by Rob-BZ** [dotnet/aspnetcore#22142]
The linked issue was not technically resolved as no solution was given. The Microsoft Docs
https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1

make a reference to "†Additional polyfills are required (for example, promises can be added via a Polyfill.io bundle)" However, Polyfill.io is a builder package that requires the user to know what Pollyfills are needed. What Pollyfills are needed for server-side Blazor to run in IE 11?

_Originally posted by @mkArtakMSFT in https://github.com/dotnet/aspnetcore/issues/9436#issuecomment-577830150_

**Comment by javiercn** [comment]
@Rob-BZ thanks for contacting us.

We don't have a specific list of polyfills we recommend. We suggest you look at the different community solutions and pick the one that works best for you.
