### ISSUE TITLE
Blazor - Button w/ Click Event using NavigationManager (Behavior)

### ISSUE THREAD

**Issue by svrebelo001** [dotnet/aspnetcore#22144]
### Describe the bug
-> Button with Click Event which has one line of code (NavigationManager.NavigateTo("\xxx")
-> Assume the button is in the middle of the page (with scrollbar). When we click, it goes Page Up before going to the page requested. Just wanted to know why this is happening and if its normal.

Note: I'm injecting using... (@inject NavigationManager NavigationManager)

It's not much.. but I want to make it simple in order to understand and get a little help in this :)

Thanks in advance

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
