### ISSUE TITLE
Blazor -Blazor Web Assembly- Unable to Launch debug adapter

### ISSUE THREAD

**Issue by rajeshkandati** [dotnet/aspnetcore#22146]
IDE: Visual Studio Enterprise 2019 16.6
Asp.net Core: Latest version

Steps to Reproduce.

1. Create Blazor Web Assembly Asp.net Core hosted template.
2. Check or change Windows Authentication to true on server project and Uncheck or change Anonymous Authentication to false.
3. Try to run the application.

Error: Failed to Launch Debug Adapter.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Windows Authentication is not supported at the moment but it'll work as soon as the #21466 is done.
