### ISSUE TITLE
Attribute Completions Capture Commit Character 

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#22150]
While validating https://github.com/dotnet/aspnetcore/issues/21062 & https://github.com/dotnet/aspnetcore/issues/21485: 

Discovered some completion commit issues in VSCode
- `<button @attrib|` press `=` -> `<button @attributes="=|"`
- `@onkey|` press `:` -> `@onkeydown=":|"`
- Taghelper attribute `<form ap-anti` press ` ` -> `<form asp-antiforgery=" |"`
- Taghelper attribute `<form ap-ar` press `=` -> `<form asp-area="=|"`

Thanks @noahbkim :)

**Comment by ryanbrandenburg** [comment]
CC @ajaybhargavb who has dealt with similar issues in the past.

**Comment by ryanbrandenburg** [comment]
Also seen on Mac.

**Comment by ryanbrandenburg** [comment]
Possibly related: `<div @onkeyp|` then hitting : will result in `<div @onkeypress=":"`.

**Comment by TanayParikh** [comment]
> Possibly related: `<div @onkeyp|` then hitting : will result in `<div @onkeypress=":"`.

Yep, that's point 2 😉

**Comment by TanayParikh** [comment]
Verified not a WTE issue. Investigating within our completion endpoints.

This issue only appears on VSCode (not VS), and is likely rooted in our completion snippet handling.

**Comment by TanayParikh** [comment]
Okay, if we want to get a fix in for the attributes, this is probably the best we can do for now:
![commit_char_minimum_fix](https://user-images.githubusercontent.com/14852843/82705976-83fbcc80-9c2d-11ea-9c02-1f94ab3764ab.gif)

The reason being, the `="|"` snippet logic doesn't actually take commit characters into account. Note, this is still an improvement over our current released version as we still complete the attribute, rather than just applying the commit char to wherever we are (ex. `@onkey` press `:` yields `@onkey:` in production).

As far as I can tell, there's nothing in the LSP spec which allows different [CompletionItem.InsertText](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.languageserver.protocol.completionitem.inserttext?view=visualstudiosdk-2019#Microsoft_VisualStudio_LanguageServer_Protocol_CompletionItem_InsertText) snippets for different commit characters. However, for the commit characters `:` and `=`, we need snippet texts of `:|` and `="|"` respectively. Right now it's indiscriminately applying the `="|"` to everything.

This is based on my current understanding and I'll confirm and update.

**Comment by TanayParikh** [comment]
Confirmed with @NTaylorMullen this is a known limitation of the LSP spec. We're removing snippet support for taghelper and directive attributes for now.

Being Tracked Here: https://github.com/dotnet/aspnetcore/issues/22228
