### ISSUE TITLE
Blazor Wasm performance optimization

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#22155]
As you know the performance in client-side Blazor (Wasm) is extremely poor, so I'm trying to detect what I can do better in my app to optimize the performance. 

How can I profile client-side Blazor?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Have a look at the [ASP.NET Core Blazor WebAssembly performance best practices](https://docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1) guide which was published recently.

As for how to profile client-side Blazor apps, @pranavkm do you have any suggestions regarding this?

**Comment by mkArtakMSFT** [comment]
@arivoir there is no a simple way to profile client-side Blazor apps at the moment.
