### ISSUE TITLE
Per Browser Tab Cookie Authentication

### ISSUE THREAD

**Issue by bgilbert6** [dotnet/aspnetcore#22167]
### Is your feature request related to a problem? Please describe.
Because cookie authentication is per domain, some cookie customization is required for per tab auth ability. As far as I can find the only customization you can do is change the cookie name on Startup.cs

### Describe the solution you'd like
It'd be nice if AddCookie had hooks for CookieWrite / CookieRead so a header value could be attached, thus allowing different ways of handling per browser tab authentication

### Additional context
The only way to actually get this working was a mess, and required hooking into OnSignedIn and reading the Set-Cookie header in order to write a new cookie with tab context information. In addition for Requests, the cookie needed to be renamed for what Cookie Authentication expect, which required messed reflection.

See messy code below:
https://gist.github.com/bgilbert6/43d6bb685d4d8d197264c453316f400a

**Comment by Tratcher** [comment]
There is a hook on the cookie auth options called the cookie manager. 
https://www.github.com/dotnet/aspnetcore/tree/master/src%2FSecurity%2FAuthentication%2FCookies%2Fsrc%2FICookieManager.cs

What kind of tab context would you use to differentiate? How do you keep the client from sending all the cookies? The request would quickly get too large.

**Comment by bgilbert6** [comment]
I was probably going to pass the tab context in a request header. Overall you wouldn't have more than 1 to 5 cookies. 

I'll take a look at cookie manager!

**Comment by bgilbert6** [comment]
Okay that was super easy compared to what I was doing before. If anyone needs this in the future here I forked ChunkingCookieManager and added the tab context key:

My tab context can come from a querystring OR request header, so you may want to edit that part in Startup.cs

https://gist.github.com/bgilbert6/dc8d87238ac471ca6c9bc2bcde2ced0b

**Comment by KieranDevvs** [comment]
It sounds like you really want to handle this on the server rather than the client. Form an identity consisting of multiple identities and then use form data on the client to signal server requests to operate said request for a given identity. The whole point of a cookie is to persist across the whole browser context.
