### ISSUE TITLE
Blazor WASM Server Hosted with Azure Signal R errors on WSS connection

### ISSUE THREAD

**Issue by mandalorianbob** [dotnet/aspnetcore#22162]
Previous Issue: https://github.com/dotnet/aspnetcore/issues/20714
To resummarize:
I tried to follow the guidelines for switching from a basic SignalR connection for testing to an actual Azure Signal R Service in a Blazor WASM Hosted app using the new 3.2 release. This app is just a single page where my users put in results, and these results are sent to a SignalR hub. Whenever I start up the app, it immediately tries to connect to a hub, and all of this works in the normal SignalR scenario. But since that scenario only supports a few connections I thought I'd switch to the Azure Signal R Service.

Unfortunately every time I get the same error:
```
dotnet.3.2.0.js:1 WebSocket connection to 'wss://corvustest.service.signalr.net/client/?hub=ifritrollresultshub&asrs.op=%2FifritRollResultsHub&negotiateVersion=1&asrs_request_id=J0BELHUGAAA%3D&id=UJmsenPLve-F4d4ztI1U7g4270c5e41' failed: HTTP Authentication failed; no valid credentials available
allocator @ dotnet.3.2.0.js:1
```

My ConfigureService looks like this:
```
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR()
                    .AddAzureSignalR();
            services.AddControllersWithViews();
            services.AddResponseCompression(opts =>
            {
                opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
                    new[] { "application/octet-stream" });
            });

        }
```
And my Configure looks like this:

```
  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebAssemblyDebugging();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<IfritRollResultsHub>("/ifritRollResultsHub");
                endpoints.MapFallbackToFile("index.html");
            });
        }
```

I even tried changing the hub to use LongPolling.
```
endpoints.MapHub<IfritRollResultsHub>("/ifritRollResultsHub", (options) => options.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.LongPolling);
```

That didn't actually change anything though. Same WSS error. My client connection is just the standard HubConnectionBuilder pointing to the hub. Unfortunately last time I just reverted back to the regular Signal R because I couldn't figure out how to enable LongPolling haha, so I never actually realized that this wasn't the issue.

Right now I'm running locally but last time I had this error pushing it to the server didn't change nor fix anything, so I'd rather not blow away my current site unless it's impossible for it work locally.

Lemme know if there's anything else that would help.

Thanks!

**Comment by BrennanConroy** [comment]
Setting the transport to LongPolling on the server-side when using the Azure SignalR Service wont cause the client to connect with LongPolling, because the client talks to the Service and not your app.
If you want LongPolling you can set it on the client side.

What version of the SignalR client are you using on the client? Is the client pointing to your app still or did you change the url to point to the Service (which would be wrong)?

**Comment by mandalorianbob** [comment]
Ah! That's where the error was!

The SignalR Client nuget package was 5.0 Preview 2. Downgrading to 3.14 or upgrading to Preview 4 both fixed the problem, so apparently it was just a bug in that one package.

Thanks!
