### ISSUE TITLE
the"resolve blazor runtime dependencies"task faild.

### ISSUE THREAD

**Issue by alirezasejdeii** [dotnet/aspnetcore#22177]
### Describe the bug
I have this bug in new version(3.2) of blazor.
I add this lines of code in my project but it`s not working.
```
<Target Name="_RemoveSatelliteAssemblies" BeforeTargets="_ResolveBlazorRuntimeDependencies">
  <ItemGroup>
    <_BlazorDependencyInput Remove="@(_BlazorDependencyInput->WithMetadataValue('AssetType', 'resources'))"  />
  </ItemGroup>
</Target>
```

and i trun on `<BlazorWebAssemblyEnableLinking>` but is is not working
### Further technical details
- ASP.NET Core
-Blazor

**Comment by javiercn** [comment]
@alirezasejdeii thanks for contacting us.

Can you provide a minimal repro project that showcases this issue?

**Comment by alirezasejdeii** [comment]
I add a starter project in this [link](https://github.com/alirezasejdeii/BlazorTest3).
my coworker say you must re install windows and visual studio , dose it true?

**Comment by alirezasejdeii** [comment]
@javiercn  I added a sample project for this issue in this [link](https://github.com/alirezasejdeii/BlazorTest3)
