### ISSUE TITLE
(Reopen) The list of component records is not valid. SignalR Reference

### ISSUE THREAD

**Issue by svrebelo001** [dotnet/aspnetcore#22175]
Hello!

I know this issue was already reported but I'm still experiencing this! I've made the latest updates (through Nuget Packages).

I've also tried to check all related topics but no one specify what's the solution.
Can someone give a quick help?

Thanks in advance

@inherits LayoutComponentBase

```
<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4 auth">
        <LoginDisplay />
    </div>

    <div class="content px-4 mt-2">
        @Body
    </div>
</div>

<RadzenDialog />
<RadzenNotification />
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @svrebelo001.
Please share more details about your scenario. With this set of details it's hard to understand what problem you're facing and when.
Also, share a small sample app so that we can reproduce the behavior to help us with investigation.

**Comment by svrebelo001** [comment]
@mkArtakMSFT I didn't specify the issue because this is a duplicate from other threads. I believe its something about rendering the page with components from different sides.

I've closed the issue because I decided to desactivate it and use a WebScoket (as recommended by VS - when I removed the SignalR dependency)
