### ISSUE TITLE
Blazor Localization Roadmap?

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#22178]
According [to this article](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1), 

> A limited set of ASP.NET Core's localization scenarios are currently supported: IStringLocalizer<> is supported in Blazor apps.

IStringLocalizer is supported, and that's about it. The problem with IStringLocalizer is that
1. It requires a separate resource file for each class -- which can grow exponentially in large projects
2. Changing a value in the default language requires editing all other languages, very messy and prone to errors
3. Some localized strings are shared between classes

I tried adding localization to validation attributes.

First with a custom DisplayNameAttribute with built-in localization. DataAnnotations Validation doesn't read this attribute though.

Then with Display(Name="FirstName", Type=typeof(Resources)), but it made the application crash (at least when the resource is in a different project).

So it seems there's really not much localization support at all for now... better leave out localization altogether.

I don't really need localization anyway, but wanted to structure my code in clean way that would make allowing localization easy. What are the plans for Blazer localization support in .NET 5? I'd be better to structure the code in a way that would be compatible for that.

IStringLocalizer really doesn't seem like a good solution... does it even work to localize DisplayAttribute for validation messages?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share a small repro app so that we can investigate the crash you're facing.

**Comment by mysteryx93** [comment]
It's not because of being in a different project; within the same project it also crashes.

```
System.InvalidOperationException: Cannot retrieve property 'Name' because localization failed.  Type 'HanumanInstitute.WebStore.Properties.Resources' is not public or does not contain a public static string property with the name 'ProcessOrderAddressFirstName'.
   at System.ComponentModel.DataAnnotations.LocalizableString.<>c__DisplayClass12_1.<GetLocalizableValue>b__2()
   at System.ComponentModel.DataAnnotations.LocalizableString.GetLocalizableValue()
   at System.ComponentModel.DataAnnotations.ValidationContext.GetDisplayName()
   at System.ComponentModel.DataAnnotations.ValidationContext.get_DisplayName()
   at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.TryValidate(Object value, ValidationContext validationContext, ValidationAttribute attribute, ValidationError& validationError)
   at System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(Object value, ValidationContext validationContext, IEnumerable`1 attributes, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.TryValidateProperty(Object value, ValidationContext validationContext, ICollection`1 validationResults)
   at Microsoft.AspNetCore.Components.Forms.ObjectGraphDataAnnotationsValidator.ValidateField(EditContext editContext, ValidationMessageStore messages, FieldIdentifier& fieldIdentifier)
   at Microsoft.AspNetCore.Components.Forms.ObjectGraphDataAnnotationsValidator.<OnInitialized>b__7_1(Object sender, FieldChangedEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.Forms.EditContext.NotifyFieldChanged(FieldIdentifier& fieldIdentifier)
   at Radzen.Blazor.RadzenTextBox.OnChange(ChangeEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I have a repro project, can I send it to you via email?

**Comment by mkArtakMSFT** [comment]
@mysteryx93 we don't need a private app for this - just a minimal repro app hosted in GitHub is what we're looking for.

**Comment by mysteryx93** [comment]
I have a minimal repro but won't put it on GitHub

**Comment by mkArtakMSFT** [comment]
@mysteryx93 to clarify, by minimal repro we refer to the minimum required changes on top of a new project, which will reproduce the issue. We are not interested nor we have enough resources to look into customer projects.
If you can provide such a repro project hosted in a GitHub public repo, we will try the scenario out.

**Comment by JvanderStad** [comment]
@mysteryx93 You can roll your own localizer. I'm using Json files and custom attributes to make it work in Blazor. I'm using translation over multiple projects.

> - It requires a separate resource file for each class -- which can grow exponentially in large projects

You can design your own strategy. I use one translation file (per language) per 'Area'.

> - Changing a value in the default language requires editing all other languages, very messy and prone to errors

Same here, design your own strategy. If you don't change your keys, create an 'override' mechanism

> - Some localized strings are shared between classes

You can share translations by using the same type. Merge multiple json files to share translations between different area's (base translation + custom translations).

```c#
	[Translation("Translation\\Shared")]
	public class SharedTranslation
	{
		//Dummy class to group localization, can stay empty
	}

	[Translation("Translation\\Button")]
	public class ButtonTranslation
	{
		//Dummy class to group localization, can stay empty
	}

	[Translation("Translation\\ValidationRules")]
	public class ValidationRulesTranslation
	{

	}
```

I used https://github.com/rwwilden/AspNet5Localization for inspiration

**Comment by mysteryx93** [comment]
@JvanderStad, it doesn't seem your solution has any reference to DataAnnotations to use and localize them

**Comment by mysteryx93** [comment]
ok here's a minimal repro
[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/4712891/BlazorApp1.zip)

**Comment by GioviQ** [comment]
@SteveSandersonMS 
Starting from this custom sql based localizer
https://github.com/damienbod/AspNetCoreLocalization/tree/master/src/Localization.SqlLocalizer
 and adding package Microsoft.AspNetCore.Components.DataAnnotations.Validation 3.2.0-rc1.20223.4,
I cannot find a way to localize data annotation error messages.

Is there a way to use my custom localizer factory?

I also read:
https://github.com/dotnet/aspnetcore/issues/12158
https://github.com/dotnet/AspNetCore.Docs/issues/17201

Thank you

**Comment by SteveSandersonMS** [comment]
The original issues described here no longer seem to apply, so I'm going to close this. If anyone still has issues in this area, could you please post a new issue describing your scenario directly? Thanks!

> It requires a separate resource file for each class -- which can grow exponentially in large projects

You can have whatever granularity you want. Have a single file for your entire application if you want.

> Changing a value in the default language requires editing all other languages, very messy and prone to errors

True. This is innate to how resx works and not something we control in `IStringLocalizer`.

> Some localized strings are shared between classes

Sounds like a restatement of the first point.

> DataAnnotations Validation doesn't read this attribute though

DataAnnotations validation now does read localization from attributes. Working Blazor example: https://github.com/SteveSandersonMS/CarChecker/blob/master/Client/Pages/Index.razor#L38
