### ISSUE TITLE
CPU high usage from typing in the IDE

### ISSUE THREAD

**Issue by talldaniel** [dotnet/aspnetcore#22183]
Using Windows 10 pro and Build 16.6.0 load a medium sized project (40,000 lines) and then type something in the IDE.  Especially use the backspace key.

On my six core AMD computer that runs at 3500 normally, it kicks into turbo and all six cores run around 80% to 100% and then slowly level off, but sometimes it then kicks back up to 100% again.

VS just rebooted itself after running at 100% as I was writing this.

Stop typing and wait for several minutes and watch the CPU go to near zero.  Type a keyword and spell it wrong.  Attempt to backspace to fix it, and watch it zoom to 90% to 100% cpu.  The IDE locks up for 10 to 20 seconds waiting and is unresponsive.
Almost any typing will cause it to use excess CPU, but it may be worse with the backspace key and a misspelled keyword, not sure.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
Also, consider the guidance provided here https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019 when filing an issue.

**Comment by talldaniel** [comment]
This is a good example of why I seldom report bugs
