### ISSUE TITLE
blazor 乱码的问题

### ISSUE THREAD

**Issue by koeltp** [dotnet/aspnetcore#22184]
组件的代码如下：
![image](https://user-images.githubusercontent.com/2775276/82747195-56e42100-9dc9-11ea-9b3e-406817ba184f.png)

界面显示如下：
![image](https://user-images.githubusercontent.com/2775276/82747226-7ed38480-9dc9-11ea-903f-2cfc7466b5b4.png)

其他的地方的汉字却可以显示正常。代码如下：
![image](https://user-images.githubusercontent.com/2775276/82747252-b5110400-9dc9-11ea-85f5-05a393c87eb9.png)
![image](https://user-images.githubusercontent.com/2775276/82747256-bb9f7b80-9dc9-11ea-932c-28d7db1794ed.png)

模板：blazor wasm
vs2019

**Comment by hez2010** [comment]
You may try resaving your code with UTF-8 or Unicode encoding and compiling them again.
你可以试试重新用 UTF-8 或 Unicode 编码保存你的代码后重新编译。

**Comment by koeltp** [comment]
thanks
