### ISSUE TITLE
Use IFormFile inside Child Entitys break the submittion 

### ISSUE THREAD

**Issue by AyhamNasser** [dotnet/aspnetcore#22187]
I have master Entity contains List of childs

```
public calss master
 {
public int Id {get;set;}
public List<child> Childs {get;set;}
}
public class child {
public int Id {get;set;}
public IFormFile Attachment {get;set;}
}

```

and the html Code 

```
<input type="text" name="Id" value ="1">
<input type="text" name ="Childs[0].Id" value = "25">
<input type="file" name ="Childs[0].Attachment ">
```
when submitting the data to Controller it's not mapped currectly if I removed IFormFile It's working file is there any solution for this issue ?

**Comment by davidfowl** [comment]
You can’t map an IFormFile in an EF model. It has to be translated to something that EF understands like a byte[] or Stream

**Comment by davidfowl** [comment]
@Pilchie @anurse Can we make sure the bots doesn't count weekends? Is that even a thing? Business day bot?

**Comment by Pilchie** [comment]
I've tweaked it so that the bot won't *run* to mark issues stale or to close them on weekends, but once it starts up again on Monday I don't see a way to have it not count that time :(
