### ISSUE TITLE
Adding partial namespaces in Blazor's razor markup

### ISSUE THREAD

**Issue by simonziegler** [dotnet/aspnetcore#22194]
### Is your feature request related to a problem? Please describe.
Not a problem, but this would improve maintainability for a moderate to large project composed from multiple libraries  (both regular C# netstandard and razor libraries).

### Describe the solution you'd like
Blazor's Razor markup doesn't support partial namespaces. I am building a suite of libraries and would like all of them to share a single top level namespace, say `foo`. The libraries would then apply namespaces:

- Library 1: `namespace foo.bar1` with components Bish.razor, Bash.razor and Bosh.razor.
- Library 2: `namespace foo.bar2`
- Library 3: `namespace foo.bar3`

The app consuming the libraries would then place `@using foo` and use the remainder of the namespace in a component tag. So for instance using the component Bish from library 1, the markup would be `<bar1.Bish ... />`.

This is geared towards maintainability and clarity of usage.

### Additional context
https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#import-components.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by simonziegler** [comment]
Thanks @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
