### ISSUE TITLE
There could be a aspnetcore bug in the repo, why don't you attend to the issues at hand before moving on to next issues 

### ISSUE THREAD

**Issue by skryptographer** [dotnet/aspnetcore#22199]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by Pilchie** [comment]
We regularly triage bug reports and evaluate the value of fixing them compared to the value of delivering new features, taking into account things like whether there is a workaround, how widely used the feature is, etc.
