### ISSUE TITLE
AAD hosted Blazor Webassembly - How to get subset of user's AD groups when user is member of large number of groups

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#22197]
### Describe the bug
I followed the instructions [here ](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1) to get a user's AD groups as claims. However, the user is member of a large number of groups, and I just see a single claim "hasGroups".

My question is: what is the suggested best practice/pattern to follow in such cases, as I am interested in retrieving only a few of the user's groups that match a string pattern. Where would I even write the code to perform this filter?

### Further technical details
- ASP.NET Blazor Webassembly 3.2.0
- .Net sdk version: 3.1.300
- Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 1.0

**Comment by docmaster2** [comment]
я не получаю письма подтверждения электронной почты.25.05.2020, 19:19, "Bancroftway Systems" <notifications@github.com>:
Describe the bug
I followed the instructions here  to get a user's AD groups as claims. However, the user is member of a large number of groups, and I just see a single claim "hasGroups".
My question is: what is the suggested best practice/pattern to follow in such cases, as I am interested in retrieving only a few of the user's groups that match a string pattern. Where would I even write the code to perform this filter?
Further technical details

ASP.NET Blazor Webassembly 3.2.0
.Net sdk version: 3.1.300
Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 1.0

**Comment by javiercn** [comment]
@guardrex any thoughts on this, since you wrote the original doc article?

**Comment by guardrex** [comment]
This is something that Azure docs call out. At 6 or more groups, they send `hasGroups`. They suggest making a Graph API call to `https://graph.microsoft.com/v1.0/users/{userID}/getMemberObjects`.

Reference: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims

> a few of the user's groups that match a string pattern

Graph API is going to send them all, then one would filter the ones they want to keep for a user on the app-side after they all come down.

Reference: https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0&tabs=http

**Comment by bancroftway** [comment]
The resolution is not clear. While I know how to make the graph api call, it's not clear where in the lifecycle to make the call to graph api call, and secondly, once we do get the list of groups back, to have that information be reflected in the token. Please provide a clearer guidance/sample.

**Comment by guardrex** [comment]
I suspect in the custom user factory, but @javiercn will let us know.

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#customize-the-user

**Comment by javiercn** [comment]
You can't put data in tokens as that would break the signature.

You can put claims in the user, but that is it. The UserClaimsPrincipalFactory is
