### ISSUE TITLE
Server side render blazor app but pass state to client to stop loading flash

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#22202]
### Is your feature request related to a problem? Please describe.
I want to take advantage of the blazor wasm application, but also have it rendered serverside for fast paint times and better SEO.
I have done that in this example here. However, the problem arises when loading data (e.g. the [FetchData page](https://github.com/srpeirce/Blazor-SSR/blob/master/Blender.Web/Client/Pages/FetchData.razor).

The data is statically rendered and show, however, when the wasm application loads it calls `OnInitializedAsync()` which causes the data to load again, and the page to flash.

### Describe the solution you'd like
I would like a seamless way to connect what has been rendered serverside to the client. If the component knows the state as rendered on the server then perhaps it can make a choice as to whether it calls the API again.

### Additional context
Let me know if any questions. The only way I can think of doing this now is pretty ugly/hacky...if there is already a way of doing this that would be great.

**Comment by mrpmorris** [comment]
Unfortunately, ShouldRender is ignored for the first render. If this were not the case then it would be quite trivial.
