### ISSUE TITLE
Unable to debug custom auth handler in blazor server-side

### ISSUE THREAD

**Issue by netbitshift** [dotnet/aspnetcore#22206]
Trying to write a custom authorization handler to do some additional checks.  
Using Windows authentication.
Cant seem to get the debugger to break in the handler.  What am I missing?
VS 2019 (build 16.4.2)
.NET Core 3.1.x

**Requirement**
```
public class ValidUserRequirement : IAuthorizationRequirement
{
    public bool MustBeValid { get; }

    public ValidUserRequirement(bool IsValid)
    {
        MustBeValid = IsValid;
    }
}
```
**Policy**
```
public static class Policies
{

    public const string IsValidUser = "IsValidUser";


    public static AuthorizationPolicy IsValidUserPolicy()
    {
        return new AuthorizationPolicyBuilder().RequireAuthenticatedUser()                                                  
                                               .Build();
    }
}
```
**Handler**
public class MyAuthHandler : AuthorizationHandler<ValidUserRequirement>
{

    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, ValidUserRequirement requirement)
    {    
        // will do checks against Db here
        return Task.CompletedTask;
    }
}

From **startup.cs**, ConfigureServices()
// Our services
services.AddAuthorization(config =>
{
    config.AddPolicy("IsValidUser", policy => policy.AddRequirements(new ValidUserRequirement(true)));
});
services.AddSingleton<IAuthorizationHandler, MyAuthHandler>();
services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>(); 

**Page-level attribute**

`@attribute [Authorize(Policy = Policies.IsValidUser)]   `

**App.razor**
```
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
 </CascadingAuthenticationState>
```

**Comment by javiercn** [comment]
@netbitshift thanks for contacting us.

We'll look into it and get back to you. @HaoK @blowdart is the policy being correctly configured here?

**Comment by netbitshift** [comment]
fyi - I created a new blazor-server app, chose windows authentication and did the same steps.  same thing - breakpoint in auth handler not hit.

**Comment by netbitshift** [comment]
Closing this, as I have shown by starting a new project from scratch and adding a handler,  its not a problem in the framework, but in  my code somewhere.
