### ISSUE TITLE
Unable to use ngrok for testig Blazor Web Assembly App

### ISSUE THREAD

**Issue by jose-applesox** [dotnet/aspnetcore#22204]
Using latest Visual Studio 2019 Preview 16.7.0 Preview 1.0
Attempting to connect to ngrok provided link I get
Bad Request - Invalid Hostname

Known Issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Why do you think this is an issue with Blazor WebAssembly?

**Comment by jose-applesox** [comment]
There is a resolved earlier thread at
https://github.com/dotnet/aspnetcore/issues/10592

I am trying to test my Blazor app on devices attached to my LAN.

I have tried Conveyor and ngrok.  

It's more of a dotnet issue than a web assembly issue.  Please advise if this issue belongs somewhere else.  Thanks.

**Comment by jose-applesox** [comment]
Was able to resolve this using the information at the link below.
https://www.jerriepelser.com/blog/using-ngrok-with-aspnet-core/
You have to invoke ngrok as follows.
ngrok http https://localhost:5001 -host-header="localhost:5001"

**Comment by jose-applesox** [comment]
Also works with Conveyor Visual Studio Extension as described in
https://www.jerriepelser.com/blog/use-conveyor-access-iis-app-over-internet/
