### ISSUE TITLE
WebAssemblyHostBuilder.CreateDefault() throws exception in Tests 

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/aspnetcore#22210]
Version: 3.1.300

### Describe the bug
When attempting to execute `WebAssemblyHostBuilder.CreateDefault()` in a test case the following exception occurs previously this has worked fine:

```
C:\Temp\Hosted\XUnitTestProject> dotnet test
Test run for C:\Temp\Hosted\XUnitTestProject\bin\Debug\netcoreapp3.1\XUnitTestProject.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.73]     XUnitTestProject.UnitTest1.Test1 [FAIL]
  X XUnitTestProject.UnitTest1.Test1 [1ms]
  Error Message:
   System.TypeLoadException : Generic method or method in generic class is internal call, PInvoke, or is defined in a COM Import class.
  Stack Trace:
     at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,T2,TResult](String identifier, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyJSRuntimeInvoker.InvokeUnmarshalled[T0,T1,T2,TResult](String identifier, T0 arg0, T1 arg1, T2 arg2)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.InitializeNavigationManager(WebAssemblyJSRuntimeInvoker jsRuntimeInvoker)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder..ctor(WebAssemblyJSRuntimeInvoker jsRuntimeInvoker)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.CreateDefault(String[] args)
   at XUnitTestProject.UnitTest1..ctor() in C:\Temp\Hosted\XUnitTestProject\UnitTest1.cs:line 10

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 3.9267 Seconds
```

### To Reproduce

To reproduce Create new Xunit project as follows

```
using Xunit;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

namespace XUnitTestProject
{
  public class UnitTest1
  {
    public UnitTest1()
    {
      var webAssemblyHostBuilder = WebAssemblyHostBuilder.CreateDefault();
    }

    [Fact]
    public void Test1() { }
  }
}
```
### dotnet info
```
C:\Temp\Hosted> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.805 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@StevenTCramer thanks for contacting us.

It's failing when trying to perform JS interop. I'm not 100% if we can replace the JSRuntime instance for testing purposes, but that's what is happening there.

Why are you trying to build the WebAssemblyHost in a unit test? (What piece are you trying to test?)

**Comment by StevenTCramer** [comment]
@javiercn I am doing Integration tests not just Unit tests and I try to make them as close to E2E as I can minus a browser.  This had been working on 3.1.200-preview.

I am currently trying to tease apart the pieces I actually need.

Could you send me a link to where `WebAssemblyHostBuilder CreateDefault` code is in the repo? Source Link takes me there but for the life of me I can't find it on GitHub.
Then I can review and see what has changed since the preview to cause this to fail and give you more helpful input.

Thanks.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs

**Comment by StevenTCramer** [comment]
@javiercn Oh blazor-wasm branch.... who knew.   Thanks! Will get back to you.

**Comment by mrpmorris** [comment]
@javiercn I'm not sure this is ready to close yet. There's still the issue of why it stopped working, and if it worked fully in a previous release or only in the preview. @StevenTCramer perhaps you could check if it worked in a previous release? https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by mrpmorris** [comment]
I don't think this is resolved.

**Comment by danroth27** [comment]
> and if it worked fully in a previous release or only in the preview

@mrpmorris `WebAssemblyHostBuilder` is Blazor WebAssembly specific, which has only had one supported release. This behavior may have changed to enable JS interop calls during app startup.

**Comment by StevenTCramer** [comment]
I am trying to determine where it was broken and then to see if possible to restore.  

Building ASPNet core locally is far from trivial.   I can't get the current master to build #21941 nor the wasm-branch.

And determining which code was used for the last known working sdk version `3.1.200-preview-014883`, given no tag, is not easy for me either. (guessing somewhere around e24f73e14b17de75bfc9eded0dd3e9887727b31e)

So I would like help resolve the issue.  I know the date of Preview 1 release was 2020-01-28

The last commit on the blazor-wasm that changed this file before Preview 1 was 

![image](https://user-images.githubusercontent.com/357219/83113669-2b777400-a0f2-11ea-919a-d07ba2c0b6e6.png)

So something after changed it.  But I need to be able to build and test to determine where and that is proving to be more challenging than I had hoped.

**Comment by javiercn** [comment]
As @danroth27 mentions here, this is not something we ever supported on an official release. From looking at the current code, there is no easy way around to allow changing the JS runtime.

If we see more demand for this I'm happy to take a look at what we can do to improve the situation here, but I would like to get more information on what are the types of things that this enables it and see if there are alternatives that can achieve the same result without requiring a change.

**Comment by StevenTCramer** [comment]
@javiercn 
In my Blazor Template I have been using WebAssemblyHostBuilder in my [Integration Tests.](https://github.com/TimeWarpEngineering/timewarp-templates/blob/master/Source/TimeWarp.Blazor.Template/content/TimeWarp.Blazor/Tests/Client.Integration.Tests/Infrastructure/TestingConvention.cs#L77)

In Blazor-State In particular these [JsonRequestHandlerTests](https://github.com/TimeWarpEngineering/blazor-state/blob/master/Tests/Client.Integration.Tests/Features/JavaScriptInterop/JsonRequestHandlerTests.cs) no longer function:

They had been working for a long time where I utilize the `BlazorWebAssemblyHost` which is now `WebAssemblyHostBuilder` in my [TestFixture](https://github.com/TimeWarpEngineering/blazor-state/blob/master/Tests/Client.Integration.Tests/Infrastructure/TestFixture.cs#L29).

**Comment by SteveSandersonMS** [comment]
It's not intended that `WebAssemblyHostBuilder.CreateDefault` should run outside the context of the browser runtime. That method is coupled to the browser because that's exactly the scenario it represents.

For unit tests, I'd recommend factoring out any startup logic that you want to call in unit tests into some new static method. Then you can call it both from your `Program::Main` as well as in any relevant unit tests. This gives you much more flexibility, because then you can have some services that are registered only in the browser, some only in unit tests, and some in both, just depending on where you put the registration logic.

The services that `WebAssemblyHostBuilder.CreateDefault` registers by default, such as the JS runtime and navigation services, are also coupled to the browser runtime (because again, that's precisely what the method is intended to be used for) so they also wouldn't work in unit tests, and is another reason why you'd want to register different implementation of those services for unit tests.
