### ISSUE TITLE
Blazor WASM - Breakpoint in NavMenu OnInitializedAsync is not hitting

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#22212]
### Describe the bug
I injected HttpClient into NavMenu component, then added OnInitializedAsync and called http request. Breakpoint goes red after page loads but even then if I do F5 breakpoint is not hitted.

Cant find if theres any common issue related to debugging? Server project is startup project.
I noticed I can try debugging via Chrome/Edge. I would like to stay within VS.

### Code
```
@code
{
    List<Menu> Menus { get; set; } = new List<Menu>();

    protected override async Task OnInitializedAsync()
    {
        Menus = await Http.GetFromJsonAsync<List<Menu>>("api/Menu/All"); // Breakpoint right here
    }
}
```

### Further technical details
- ASP.NET Core version 16.6
- Include the output of `dotnet --info` 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6
```

**Comment by javiercn** [comment]
@glararan thanks for contacting us.

The debugger takes a while to get everything setup and the code might run before the debugger is ready. If you put a task.delay(10000) or something like that before the breakpoint it should give the debugger enough time to get ready and stop in your breakpoint.

This is just a suggestion that has worked for me in the past.

**Comment by glararan** [comment]
@javiercn  works.
Would be nice to mention it in official documentation as workaround.. if it will be resolved in future
