### ISSUE TITLE
Support for full .NET Core runtime

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/aspnetcore#22213]
I have tried creating a few experiments with Blazor. I was under the impression that the full .NET Core runtime would be available with Blazor. When pulling in NuGet packages, I keep getting a range of different errors. Like `IWebProxy` not being available on this platform.

It would be nice to hear your thoughts on these issues. Is this runtime indeed a scaled-down version? Will it continue to be so and Blazor-specific packages need to be created?

**Comment by javiercn** [comment]
@ThomasArdal thanks for contacting us.

Blazor Webassembly is limited by the browser sandbox. Even though it targets netstandard2.1, some of the APIs that don't make sense won't work there. In general, Blazor WebAssembly can't be used to escape the browser sandbox, so things that are not available for browser applications like low level network primitives are not available and likely won't ever be unless the constraints for webassembly change.

As I said, the runtime is limited in capabilities by the functionality exposed to webassembly, but that might change in the future.

Providing a Blazor specialized package is fine, and we might change things in the future to make it easier to target webassembly specifically as a target.

**Comment by ThomasArdal** [comment]
It makes total sense. Being able to target blazor and a version would be awesome. I believe the current target against netstandard will cause a lot of problems for people going forward. Installing NuGet packages won't really work in a lot of cases.

Thank you for the quick reply 🙌

**Comment by javiercn** [comment]
> Installing NuGet packages won't really work in a lot of cases.

I would expect quite the opposite. Most nuget packages should work unless they try to do something that is not realistically achievable in the Browser. The majority of packages should work. 

We just need to be realistic in that it is unlikely that you can host a webserver in Blazor Wasm (for example) in the browser, in the same way you can't do it in JavaScript, but most packages should be fine.

**Comment by ThomasArdal** [comment]
Yeah, maybe you're right. I must have been unlucky with the packages I tried to install. The issue with one of the packages where that it exposed a property of type `IWebProxy` in the interface. So, without ever using that property, Blazor would log an error in the console when I reference that interface. Happened with other types that I don't remember. Of course, including these types is probably not that common.
