### ISSUE TITLE
Creating browser extensions with blazorwasm

### ISSUE THREAD

**Issue by tshemeng** [dotnet/aspnetcore#22211]
seems `dotnet publish` directory structure not work for creating browser extensions.

1. `_framework` folder begins with an underscore, and edge (chromium) reports "Cannot load extension with file or directory name _framework. Filenames starting with _ are reserved for use by the system."

2. framework/blazor.webassembly.js incompatible with edge, and console logs
    Failed to load resource: net::ERR_FILE_NOT_FOUND  _framework/blazor.boot.json:1
    TypeError: Failed to fetch                        blazor.webassembly.js:1 

is any plan blazorwasm to creating browser extension ?

**Comment by javiercn** [comment]
@tshemeng thanks for contacting us.

Creating a browser extension is not something we are currently targeting with Blazor WebAssembly in the current release.

I don't think we'll change the publish structure, but you should be able to change that yourself and perform a custom load of the blazor resources. See the [Custom boot resource loading](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available/) in this post for details

**Comment by mkArtakMSFT** [comment]
This is going to be handled as part of https://github.com/dotnet/aspnetcore/issues/22220
