### ISSUE TITLE
Can't build the project on local machine using instructions

### ISSUE THREAD

**Issue by GetTaxSolutions** [dotnet/aspnetcore#22222]
I'm trying to build project on my local machine. My environment installations are:

> PS D:\github\pubs\aspnetcore> dotnet --list-sdks 
> 
> 3.1.103 [D:\github\pubs\aspnetcore\.dotnet\sdk]
> 3.1.300 [D:\github\pubs\aspnetcore\.dotnet\sdk]
> 5.0.100-preview.5.20258.4 [D:\github\pubs\aspnetcore\.dotnet\sdk]
> PS D:\github\pubs\aspnetcore> dotnet --list-runtimes
> 
> Microsoft.AspNetCore.App 3.1.3 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 3.1.4 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 5.0.0-preview.5.20255.6 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 3.1.3 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 3.1.4 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 5.0.0-preview.5.20258.3 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 5.0.0-preview.6.20271.10 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.NETCore.App]
> Microsoft.WindowsDesktop.App 3.1.3 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.WindowsDesktop.App]
> Microsoft.WindowsDesktop.App 3.1.4 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.WindowsDesktop.App]
> Microsoft.WindowsDesktop.App 5.0.0-preview.5.20253.1 [D:\github\pubs\aspnetcore\.dotnet\shared\Microsoft.WindowsDesktop.App] 

I changed global.json to use dotnetcore SDK 3.1.300 and dotnet 3.1.300. Run scripts `./eng/scripts/InstallVisualStudio.ps1` and all components are there.
Run ./build.ps1 in console and show me these errors:

> D:\github\pubs\aspnetcore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1101: Unable to find package Internal.AspNetCore.Analyzers. No packages exist with t
> his id in source(s): https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json, https://dotnet.myget.org/F/sourcelink/api/v3/index.json, nuget.org
> D:\github\pubs\aspnetcore\eng\tools\RepoTasks\RepoTasks.csproj : error NU1101: Unable to find package Microsoft.Internal.Extensions.Refs. No packages exist w 
> ith this id in source(s): https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json, https://dotnet.myget.org/F/sourcelink/api/v3/index.json, nuget.org       
>   Failed to restore D:\github\pubs\aspnetcore\eng\tools\RepoTasks\RepoTasks.csproj (in 4.19 sec).
> Build failed.

It's the same when run ./build.cmd in `./src/Mvc` folder. When hit the endpoints from the error message they return some response. Also tried to invoke `./activate.ps1` before build and it's the same

**Comment by Tratcher** [comment]
See https://github.com/dotnet/aspnetcore/issues/21941

**Comment by dougbu** [comment]
@Tratcher should this issue be closed❔
