### ISSUE TITLE
Blazor WASM with linker enabled downloads unused dependencies during boot

### ISSUE THREAD

**Issue by isc30** [dotnet/aspnetcore#22230]
The linker in Blazor WASM is including dependencies that aren't in use (in normal scenarios these would be stripped out by the compiler, which is what happens with the linker disabled (ok)).

When adding a reference (RCL project/nuget) to a project with `Microsoft.AspNetCore.Components.WebAssembly.Build` and `BlazorWebAssemblyEnableLinking` set to `true`, the linker will add the dependency project as a boot dependency inside `blazor.boot.json` even if it's not used at all.

If this reference is **not** used, the linker should detect it and **not** add it as a boot project. I suspect the problem is somewhere where we take the linker output and enumerate the blazor binaries based on it.

This issue doesn't happen with `BlazorWebAssemblyEnableLinking` disabled (the unused project is not even inside `_framework/_bin`) but StaticWebAssets are still there (ok).

# To Reproduce

Please follow the steps to get this reproduced on your own repository.
In order to check the bug, [this minimal example repository with the bug](https://github.com/isc30/bugs/tree/aspnetcore/linker-issues) can be used.

### Properly Working Example: With no Linker
1. Create a Blazor WASM project (host)
1. Add `<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>`
1. Create a RCL project (lib) with a Component and `wwwroot/test.css` as StaticWebAsset
1. Reference `lib` from `host` and use the Component from it
1. Build and Run
1. The DLL of `lib` appears inside `blazor.boot.json` and gets downloaded during startup (ok)
1. Navigate to `_content/lib/test.css` and see that the StaticWebAsset is available (ok)
1. Remove the runtime usage of `lib` by not using the Component anymore so the compiler strips it out
1. The DLL of the project is no longer inside `blazor.boot.json` and doesn't get downloaded during startup (ok)
1. The StaticWebAsset `_content/lib/test.css` is still available (ok)

### Buggy Example: With Linker enabled
1. Use the project from the working example
1. Change it to use `<BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>`
1. Reference `lib` from `host` and use the Component from it
1. Build and Run
1. The DLL of `lib` appears inside `blazor.boot.json` and gets downloaded during startup (ok)
1. Navigate to `_content/lib/test.css` and see that the StaticWebAsset is available (ok)
1. Remove the runtime usage of `lib` by not using the Component anymore so the compiler strips it out
1. **The DLL of the project is still inside `blazor.boot.json` and still gets downloaded during startup (fail)**
1. The StaticWebAsset `_content/lib/test.css` is still available (ok)

# Further technical details
- ASP.NET Core version: 3.2.0-rc1.20223.4
- dotnet version: 3.1.201

# Comments
This is a rather big bug. When including a NuGet package and using a small portion of it, the linker will still add every sub-reference, even if not used and the DLL could be skipped.

This should still preserve StaticWebAssets from the projects that don't need a runtime.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The linker is only linking the framework binaries at the moment. We will be changing that in the future to trim also application binaries in the future.

**Comment by isc30** [comment]
Can we at least get an `ItemGroup` to be able to exclude some assemblies (and subassemblies) from the `blazor.boot.json`?
Disabling the linker seems useless in this situation
