### ISSUE TITLE
blazorwasm --hosted + docker + Fatal error in Mono IL Linker

### ISSUE THREAD

**Issue by Henkolicious** [dotnet/aspnetcore#22234]
### Describe the bug
`Fatal error in Mono IL Linker`. Might be specific to the current computer im on, because a very simular project worked just fine with docker on another machine. (<a href="https://github.com/Henkolicious/gRPC-blazor-wasm">other project</a>)

### To Reproduce
1. `dotnet new blazorwasm -n deleteme --hosted`
2.  `cd deleteme` and create the docker file (from below)
3. `docker build -t deleteme .`

Output
<pre>
$ docker build -t deleteme .
Sending build context to Docker daemon  2.786MB
Step 1/14 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
 ---> 2fe8fe202baf
Step 2/14 : WORKDIR /build
 ---> Using cache
 ---> 12af97a3521c
Step 3/14 : COPY . .
 ---> e68e95216762
Step 4/14 : RUN cd Server && dotnet restore
 ---> Running in 4d840a27e210
  Restore completed in 171.36 ms for /build/Shared/deleteme.Shared.csproj.
  Restore completed in 4.43 sec for /build/Server/deleteme.Server.csproj.
  Restore completed in 4.52 sec for /build/Client/deleteme.Client.csproj.
Removing intermediate container 4d840a27e210
 ---> 8fab3da4cc42
Step 5/14 : RUN cd Server && dotnet publish -c release -o /out
 ---> Running in bcfb03f6f1d3
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 35.17 ms for /build/Shared/deleteme.Shared.csproj.
  Restore completed in 41.79 ms for /build/Server/deleteme.Server.csproj.
  Restore completed in 41.88 ms for /build/Client/deleteme.Client.csproj.
  deleteme.Shared -> /build/Shared/bin/release/netstandard2.1/deleteme.Shared.dll
  Fatal error in Mono IL Linker
/root/.nuget/packages/microsoft.aspnetcore.components.webassembly.build/3.2.0/targets/Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'obj/release/netstandard2.1/deleteme.Client.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [/build/Client/deleteme.Client.csproj]
   ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'obj/release/netstandard2.1/deleteme.Client.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
     at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
     at Mono.Linker.LinkContext.Resolve(String name)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
/root/.nuget/packages/microsoft.aspnetcore.components.webassembly.build/3.2.0/targets/Blazor.MonoRuntime.targets(326,5): error : ILLink failed with exit code 134. [/build/Client/deleteme.Client.csproj]
The command '/bin/sh -c cd Server && dotnet publish -c release -o /out' returned a non-zero code: 1
</pre>

### Dockerfile
<pre>
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /build

COPY . .
RUN cd Server && dotnet publish -c release -o /out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build-env /out ./
ENTRYPOINT ["dotnet", "deleteme.Server.dll", "--urls", "http://*:5000"]
</pre>

### Further technical details
<pre>
$ docker --version
Docker version 19.03.8, build afacb8b
</pre>

<pre>
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
</pre>

Keep up to good work! :heart:

Kind regards,
Henrik

**Comment by javiercn** [comment]
@Henkolicious thanks for contacting us.

that docker file is missing context. You need to map all the projects in the solution into the container. From what I can tell, you are just mapping the server project and as a result the client project can't be found and the linker fails.

**Comment by Henkolicious** [comment]
The context of the Dockerfile is

<pre>
├── Client
├── deleteme.sln
├── Dockerfile
├── Server
└── Shared

directory: 3 file: 2
</pre>

**Comment by Henkolicious** [comment]
To be clear, `dotnet publish -c release -o out` from the Server folder works just fine with the dotnet CLI on a windows machine.
