### ISSUE TITLE
Fix warning "The OutputPath property is not set for project 'helix.proj'."

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22246]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during the Test Helix x64 step. Full warning text below:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(778,5): warning : The OutputPath property is not set for project 'helix.proj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [F:\workspace\_work\1\s\eng\helix\helix.proj]

@HaoK may know more about this one

**Comment by dougbu** [comment]
I think we set `<OutputPath />` to be intentionally empty to avoid creating an assembly. There are other ways to do that e.g.
``` msbuild
<Target Name="CopyFilesToOutputDirectory" />
<Target Name="CoreCompile" />
<Target Name="CreateManifestResourceNames" />
```

**Comment by HaoK** [comment]
Here's the arcade issue for this too https://github.com/dotnet/arcade/issues/1605

**Comment by dougbu** [comment]
Taking this because #22395 works and is less hacky than #22256

**Comment by dougbu** [comment]
d2b3eecedb63
