### ISSUE TITLE
Fix warning "	warning NU5118: File 'Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' is not added because the package already contains file 'Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json'"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22248]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during the SiteExtension build. Full warning text below:

> F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File 'F:\workspace\_work\1\s\.packages\Microsoft.AspNetCore.AzureAppServices.SiteExtension.5.0.x64\5.0.0-preview-6-20275-3\content\additionaldeps\shared\Microsoft.AspNetCore.App\5.0.0\Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' is not added because the package already contains file 'content\additionaldeps\shared\Microsoft.AspNetCore.App\5.0.0\Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' [F:\workspace\_work\1\s\src\SiteExtensions\LoggingAggregate\src\Microsoft.AspNetCore.AzureAppServices.SiteExtension\Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj]

> F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5118: File 'F:\workspace\_work\1\s\.packages\Microsoft.AspNetCore.AzureAppServices.SiteExtension.3.1.x86\3.1.3-servicing-20163-14\content\additionaldeps\shared\Microsoft.AspNetCore.App\3.1.0\Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' is not added because the package already contains file 'content\additionaldeps\shared\Microsoft.AspNetCore.App\3.1.0\Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' [F:\workspace\_work\1\s\src\SiteExtensions\LoggingAggregate\src\Microsoft.AspNetCore.AzureAppServices.SiteExtension\Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj]

**Comment by dougbu** [comment]
:eyes:

**Comment by BrennanConroy** [comment]
Starting in 5.0 it looks like, there are now architecture specific bits in the deps.json file.
```
"runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {},
"runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {},
"runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0": {},
```

None of these should affect the behavior of the site extension since it is for Windows only.

We can probably copy just one version of the file and ignore the other one.

**Comment by wtgodbe** [comment]
@BrennanConroy I'm confused, do you mean RID specific? Are there other bits the file that are x86?

**Comment by wtgodbe** [comment]
> Sure RID, architecture whatever you'd like to call the difference between an x64 build and an x86 build.

I meant that the snippet you pasted has all x64 bits 😆 but if the files are the same, that's good enough for me. I'll look into a fix today
