### ISSUE TITLE
Fix warning "7	warning MSB4011: "F:\workspace_work\1\s.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\BuildTasks.props" cannot be imported again."

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22244]
Part of #22240

Happens in many different build steps. Full warning text below (Note it's triggered by 3 different files being double-imported):

> F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\Settings.props(15,3): warning MSB4011: "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\BuildTasks.props" cannot be imported again. It was already imported at "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\BuildStep.props (5,3)". This is most likely a build authoring error. This subsequent import will be ignored. [F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\AfterSigning.proj]

> F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\ProjectLayout.props(8,3): warning MSB4011: "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\RepoLayout.props" cannot be imported again. It was already imported at "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\BuildStep.props (3,3)". This is most likely a build authoring error. This subsequent import will be ignored. [F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\AfterSigning.proj]

> F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\Settings.props(17,3): warning MSB4011: "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\DefaultVersions.props" cannot be imported again. It was already imported at "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\BuildStep.props (4,3)". This is most likely a build authoring error. This subsequent import will be ignored. [F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\AfterSigning.proj]

**Comment by dougbu** [comment]
:eyes:

**Comment by Pilchie** [comment]
This seems like an Arcade bug that could be fixed centrally from there?

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/22429
