### ISSUE TITLE
Reduce Build warnings to zero

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22240]
Using this as a tracking issue to get our repo down to zero recurring build warnings, so that we can turn on /warnaserror. Most common warnings are ranked below

Count | Warning | Notes | Issue
------------ | ------------- | ------------ | ----------
600+ | Atleast for one assembly start time was not obtained due to tag not present or parsing issue, total run duration will now be summation of time taken by each assembly | Happens while publishing quarantined test results | https://github.com/dotnet/aspnetcore/issues/22241
120+ | Could not parse Jtokens from F:\workspace\_work\1\s\artifacts\tmp\Release\ContainerSigning\2455\content\ReactRedux-CSharp\ClientApp\package-lock.json file. | Happens during Component Detection | https://github.com/dotnet/aspnetcore/issues/22243
28+ | CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. | Happens in all regular build steps | #22389
27 | warning MSB4011: "F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\BuildTasks.props" cannot be imported again. | Happens in most build steps | https://github.com/dotnet/aspnetcore/issues/22244
21 | Component Governance detected 5 security related alerts at or above 'High' severity. | Happens during Component Detection | https://github.com/dotnet/aspnetcore/issues/22252
18 | in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB). | Happens in the 6 main build jobs | #22390
10 | Converting null literal or possible null value to non-nullable type. | Happens in the 6 main build jobs | #22733
9 | Executable bit is not set on target script, sourcing instead of executing. | Happens during Setup Private Feed Credentials | https://github.com/dotnet/aspnetcore/issues/22245
4 | Microsoft.Common.CurrentVersion.targets(778,5): warning : The OutputPath property is not set for project 'helix.proj'. | Happens during Test Helix x64 | https://github.com/dotnet/aspnetcore/issues/22246
2 | warning NU5119: File 'F:\workspace\_work\1\s\artifacts\obj\RedistSharedFx.Layout\Release\win-x64\shared\Microsoft.AspNetCore.App\5.0.0-preview.6.20275.3\.version' was not added to the package. | Happens during SiteExtension build | https://github.com/dotnet/aspnetcore/issues/22247
2 | warning NU5118: File 'Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' is not added because the package already contains file 'Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json' | Happens during SiteExtension build | https://github.com/dotnet/aspnetcore/issues/22248
2 | unknown substitution variable ${shlibs:Depends} | Happens during Linux x64 Debian Installer build | https://github.com/dotnet/aspnetcore/issues/22249
1 | warning : This project has native dependencies which were not built. [F:\workspace\_work\1\s\src\SiteExtensions\Runtime\Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj] | Happens during SiteExtension build | https://github.com/dotnet/aspnetcore/issues/22250
1 | E2ETesting.targets(23,5): warning : Waiting for the other yarn instance to finish (7228) [F:\workspace\_work\1\s\src\ProjectTemplates\BlazorTemplates.Tests\BlazorTemplates.Tests.csproj] | Happens during Windows Template Tests | https://github.com/dotnet/aspnetcore/issues/22251

- [ ] https://github.com/dotnet/aspnetcore/issues/22241
- [x] https://github.com/dotnet/aspnetcore/issues/22243
- [x] https://github.com/dotnet/aspnetcore/issues/22244
- [x] https://github.com/dotnet/aspnetcore/issues/22245
- [x] https://github.com/dotnet/aspnetcore/issues/22246
- [x] https://github.com/dotnet/aspnetcore/issues/22247
- [x] https://github.com/dotnet/aspnetcore/issues/22248
- [x] https://github.com/dotnet/aspnetcore/issues/22249
- [x] https://github.com/dotnet/aspnetcore/issues/22250
- [x] https://github.com/dotnet/aspnetcore/issues/22251
- [ ] https://github.com/dotnet/aspnetcore/issues/22252
- [x] #22389 
- [x] #22390
- [x] #22630
- [x] #22632
- [x] #22635
- [x] #22733
- [x] #22992

**Comment by dougbu** [comment]
If we're going to use this to track project, suggest adding a checklist to the original description. If not, I'm unsure we need this issue in addition to the per-category ones.

**Comment by wtgodbe** [comment]
@dougbu I wanted to do that originally, but couldn't think of a good way to combine that with the info in the table - any suggestions? I'd be fine removing the descriptions but I'd at least want this issue to have the counts, links to the issues, and checkboxes

**Comment by dougbu** [comment]
Maybe just add a bunch 'o `- [ ] {PR link}` lines below the table?

**Comment by Pilchie** [comment]
I assigned areas to bunch of these so that triage will see them.  A couple landed in `area-infrastructure` or `area-platform` that @dotnet/aspnet-build might need to take a look at.

**Comment by dougbu** [comment]
We're getting worse instead of better. Now have ~930 warnings.

**Comment by javiercn** [comment]
@dougbu where are you seeing those? I looked at the last build and we are down to 50.

**Comment by dougbu** [comment]
@javiercn I made that comment 10 days ago. Things are much better and I only see 9 warnings in your #22703 PR 😺 However that PR does not quite "fix" this issue as advertised 😈

**Comment by javiercn** [comment]
@dougbu fair enough. Just trying to see where we are at for the DoI meeting today.
