### ISSUE TITLE
Minor performance improvement

### ISSUE THREAD

**Issue by Rickinio** [dotnet/aspnetcore#22242]
### Describe the bug
In this part of the code line 174 we create a new SortedDictionary but I think we don't need it since authorizationParts variable is already a SortedDictionary:
https://github.com/dotnet/aspnetcore/blob/94274d889714213c613b375407d19d3912340b8c/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L160-L174

**Comment by Tratcher** [comment]
It's copied because authorizationParts is still needed after computing the signature.
https://github.com/dotnet/aspnetcore/blob/94274d889714213c613b375407d19d3912340b8c/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L206

**Comment by Rickinio** [comment]
Thanks @Tratcher for your answer, please excuse my tunnel vision.
