### ISSUE TITLE
Fix warning 'Executable bit is not set on target script, sourcing instead of executing.'

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22245]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during 'Setup Private Feed Credentials' on non-windows builds. @dougbu claims this will be fixed by the next Arcade update.

Full warning text:

> ##[warning]Executable bit is not set on target script, sourcing instead of executing. More info at https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/bashnote.md

**Comment by dougbu** [comment]
I actually claimed https://github.com/dotnet/arcade/pull/4894 should have fixed it already. @riarenas haven't we picked up that change in this repo? If we have, why isn't the exec bit set correctly on eng/common/SetupNugetSources.sh in the CI?

**Comment by riarenas** [comment]
That changed flowed a long time ago, but I think there's a problem with that particular file right now: https://github.com/dotnet/arcade/issues/5346

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/22521
