### ISSUE TITLE
Fix warning "unknown substitution variable ${shlibs:Depends}"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22249]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during the Debian Installer step of the Linux x64 build. Warning text below:

> dpkg-gencontrol : warning : Depends field of package aspnetcore-runtime-5.0: unknown substitution variable ${shlibs:Depends} [/datadisks/disk1/workspace/_work/1/s/src/Installers/Debian/Runtime/Debian.Runtime.debproj]

> dpkg-gencontrol : warning : Depends field of package aspnetcore-targeting-pack-5.0: unknown substitution variable ${shlibs:Depends} [/datadisks/disk1/workspace/_work/1/s/src/Installers/Debian/TargetingPack/Debian.TargetingPack.debproj]

**Comment by Pilchie** [comment]
@JunTaoLuo are you the most familiar with how this works?

**Comment by JunTaoLuo** [comment]
I suppose, though it's been a while since I've taken a look.

**Comment by JunTaoLuo** [comment]
Ah I see, it's somehow related to how https://github.com/dotnet/aspnetcore/blob/master/src/Installers/Debian/tools/templates/debian/control#L16 is being used in the scripts. Looks like we don't need those values so we might be able to just remove them
