### ISSUE TITLE
Fix warning "Waiting for the other yarn instance to finish"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22251]
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during the "Pack templates" section of the Windows template test build, but is not consistent. Example: https://dnceng.visualstudio.com/internal/_build/results?buildId=659098&view=logs&j=80f594f0-dab9-53e4-691e-a6c036ec4279&t=f36e9154-5586-5099-12cf-73e26fd14ad0&l=54

Warning text:

> F:\workspace\_work\1\s\src\Shared\E2ETesting\E2ETesting.targets(23,5): warning : Waiting for the other yarn instance to finish (7228) [F:\workspace\_work\1\s\src\ProjectTemplates\BlazorTemplates.Tests\BlazorTemplates.Tests.csproj]

**Comment by HaoK** [comment]
This one might be a point in time thing, we should stop running ProjectTemplates entirely on azdo soon, ideally we want these all to run on helix and only helix.  We likely introduced the yarn warning when we split BlazorTemplate tests outs, in the short term maybe we could just stop building/running the ProjectTemplates that are already running on helix which would get rid of the yarn concurrency
