### ISSUE TITLE
Blazor PWA and Camera 

### ISSUE THREAD

**Issue by sowsan** [dotnet/aspnetcore#22259]
Can Blazor Web Assembly app with PWA use the device capabilities like a Camera?

https://stackoverflow.com/questions/57014675/is-it-possible-to-access-native-cell-phone-or-device-apis-using-blazor-to-access

**Comment by javiercn** [comment]
@sowsan thanks for contacting us.

If the APIs are accessible to JavaScript when the app is installed as a PWA. They should be available for Blazor too through JS interop.
