### ISSUE TITLE
Blazor RenderFragment to String 

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#22266]
I have Blazor Component as 
```razor
<pre class="language-html">
    <code class="language-html">@ChildContent</code>
</pre>

@code
{
    [Parameter]
    public RenderFragment ChildContent { get; set; }
}
```
now i am using component as 

```razor
<CodeBlock>
        <StepContent>
            <StepTitle>Shipping</StepTitle>
            <StepDescription>Choose your shipping options</StepDescription>
        </StepContent>
</CodeBlock>
```

I want to show RenderFragment as String, not as evaluated Dom Element.

### Actual Output

![current output](https://user-images.githubusercontent.com/45932883/82982357-a87bee00-a00b-11ea-85f8-036c1f6b8356.JPG)

### Expected Output

![expected](https://user-images.githubusercontent.com/45932883/82982367-afa2fc00-a00b-11ea-871c-ac5f3813bfb4.JPG)

### My different Approach 

If the component was designed to take string 
```razor 
    <CodeBlock Code="@str"/>
```
```cs
public string str = @"
        <StepContent>
            <StepTitle>Shipping</StepTitle>
            <StepDescription>Choose your shipping options</StepDescription>
        </StepContent>";
```
Use string as Parameter but with this there come many problems like escaping ``` " ```, Visually Ugly looking Component Code, etc.  Overall Complexity is increased.

#### I am hoping for a way to convert RenderFragment to string as current implementation gives evaluated Component.

Thank you.

**Comment by javiercn** [comment]
@sps014 thanks for contacting us.

There is no way to do this today within Blazor. We have support for this in the form of prerendering, but not anywhere else. It is unlikely we add something like this, since we haven't receive similar asks for it yet.

**Comment by mrpmorris** [comment]
In your component have a `<div style="display: none" @ref=MyContentRef`>@ChildContent</div>`

In `OnAfterRenderAsync` you can call some JavaScript to get the `innerHtml` of `MyContentRef` and then display that string in your `<code>`.

**Comment by sps014** [comment]
> In your component have a
> 
> ```
> <div style="display: none" @ref=MyContentRef`>@ChildContent</div>
> ```
> 
> In `OnAfterRenderAsync` you can call some JavaScript to get the `innerHtml` of `MyContentRef` and then display that string in your `<code>`.

That's worked ... Thanks..

**Comment by sps014** [comment]
@javiercn any plan to override ToString Method of RenderFragment in Future?

**Comment by javiercn** [comment]
@sps014 no. RenderFragment is also a delegate type, so I don't think that's even possible.

**Comment by sps014** [comment]
Oops didn't know that..  i am closing this issue for now as i have other workarounds to deal with current problem.

**Comment by benm-eras** [comment]
For what it's worth I would like to be able to access the the content of a tag/component as a string rather than a render fragment. In my case I am trying to make a component that simply passes markdown content to HTML. My desired `Markdown.razor` component:

```razor
<div class="some-container">
    @Html
</div>

@code {
    [Parameter]
    public RenderFragment ChildContent { get; set; }

    public string Html => Markdig.Markdown.ToHtml(this.ChildContent.ToString());
}
```

How I would use it:
```razor
<div class="foo">
    <Markdown>
        ## A Header of some description

       Paragraph 1

       Paragraph 2
    </Markdown>
</div>
```

Passing that as a parameter just feels dirty and I think I would prefer to just write the HTML at that point.
