### ISSUE TITLE
Visual Studio 2019 v 16.7.0 preview 1.0 + Blazor - removing the code on oncomplete

### ISSUE THREAD

**Issue by YordanYanakiev** [dotnet/aspnetcore#22268]
### Describe the bug
If I try to use code completion - the source inside "code" is been removed.
before:
![1s](https://user-images.githubusercontent.com/6534199/83011983-75455900-a023-11ea-8f9c-4f5dee9d8a3c.jpg)
after pressing enter:
![2s](https://user-images.githubusercontent.com/6534199/83011995-78404980-a023-11ea-97ec-afca76eb253a.jpg)

### To Reproduce
Start new Blazor webasm project.
In NavMenu page in the code start typing "override" and press enter in any method.

### Further technical details
- ASP.NET Core version : 3.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) 16.7 preview 1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Given that this is happening in the C# portion of the document we believe this is an issue with Roslyn. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
