### ISSUE TITLE
Blazor: Listing data in separate components breaks on deletion

### ISSUE THREAD

**Issue by andyschick** [dotnet/aspnetcore#22265]
### Describe the bug
Based on the WeatherForecast demo page, I have packed the individual forecast data into separate components. I also added a Delete action parameter, so the forecast entries can be deleted.
After the deletion the line count decreases but the displayed data is not correct.

**Example**: The forecast displays the weather from May 1st to May 5th.

**Expected behaviour:**
1. I delete the first line (May 1st)
2. the related forecast will be deleted from the "database"
3. the displayed line count decreases to 4
4. only the lines from May 2nd to May 5th will be displayed

**Actual behaviour**
1. I delete the first line (May 1st) **–– check**
2. the related forecast will be deleted from the "database" **–– check**
3. the displayed line count decreases to 4 **–– check**
4. only the lines _**from May 1st to May 4th**_ will be displayed **––** &#128562;

Please see the demo animation here:
https://1drv.ms/u/s!AvJrh4qUYMjbgQEN290LhyQlRtuc?e=NxsyK2

### To Reproduce
You can find the C# project here:
https://1drv.ms/u/s!AvJrh4qUYMjbgQLXqB7gchTvW96G?e=I7tt3n
Please run it and navigate to "Fetch data".

### Further technical details
IDE: Visual Studio 2019 v16.5.5

.NET Core SDK (gemäß "global.json"):
 Version:   3.1.202
 Commit:    6ea70c8dca

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mrpmorris** [comment]
Use `@key` when creating UI in a list

`<ForecastEntry @key=forecast.Date ForecastDate="forecast.Date" OnDelete="DeleteForecastEntry" />`

That'll fix your problem for now, but the behaviour is still unexpected.

**Comment by andyschick** [comment]
> Use `@key` when creating UI in a list

Thank you for this hint, it works fine for me.
Nevertheless, I would appreciate a sustainable solution out of the box.

**Comment by mrpmorris** [comment]
I agree that it appears to be unexpected behaviour.

Always do use `@key` for loop created UI though, it makes delate updates to your HTML more efficient. See https://blazor-university.com/components/render-trees/optimising-using-key/

**Comment by andyschick** [comment]
> Always do use `@key` for loop created UI though, it makes delate updates to your HTML more efficient. See https://blazor-university.com/components/render-trees/optimising-using-key/

Thanks for that learning. I will always do that from now on.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
