### ISSUE TITLE
TagHelper Insert Text Doesn't Work Appropriately When Re-Querying Completion

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#22261]
1. `dotnet new blazorserver`
2. Open `Pages/_Host.cshtml`
3. In the body, type `<form asp-`
4. Press `ESC` to close the completions
5. Re-trigger completions with `CTRL+SPACE`
6. Type `pa` and accept the completion for `asp-page`

Expected: `asp-page`
Actual: `asp-asp-page`

Note, this repros on the current released extension.

**Comment by allisonchou** [comment]
I believe this is a dupe of https://github.com/dotnet/aspnetcore-tooling/issues/4453
