### ISSUE TITLE
Blazor -Blazor Web Assembly- Unable to Launch debug adapter following Windows password change

### ISSUE THREAD

**Issue by timcromarty** [dotnet/aspnetcore#22273]
### Describe the bug
Following a change to my Windows password, attempting to run Blazor WebAssembly in Debug fails with the message "Unable to Launch debug adapter. Failed to connect..."

Visual Studio 16.6
Blazor 3.2

### To Reproduce
Build and run a Blazor web assembly application in debug.  Change the Windows password, Build and tun the application again.

### Workaround
Exit from Visual studio, Delete the .vs directory, restart Visual Studio.

**Comment by mkArtakMSFT** [comment]
@digeff can you please look into this? Thanks

**Comment by digeff** [comment]
@timcromarty Can you please upload %TEMP%\vscode-chrome-debug.txt right after this happens? (The log gets overwritten each time you launch the debugger)

**Comment by timcromarty** [comment]
Will do, just give me a couple of days.
Thanks

**Comment by mkArtakMSFT** [comment]
Closing as no further action left in here.
