### ISSUE TITLE
Question: Can We Contribute Code Relying On Source Generator?

### ISSUE THREAD

**Issue by ChayimFriedman2** [dotnet/aspnetcore#22301]
C# 9 will introduce the concept of source generators. ASP.NET makes heavy use of reflection currently (for example to find a controller), and migrating to source generator will mean faster startup & runtime (in expense of compile time).

So we ask: does the team have plans to start rewriting the framework slowly to adopt this new feature? And if not, is this something by design or because lack of resources, and contributions will be welcomed?

Also notice that currently source generators are available only for C# (I hope this will change in the near future), so we still need to provide a fallback for VB and F#, as well as previous versions of C# we support.

**Comment by javiercn** [comment]
@ChayimFriedman2 thanks for contacting us.

It is too early to tell. We will likely look into this in the future, but we don't have anything specific yet.
