### ISSUE TITLE
Identity override error in Blazor WebAssembly

### ISSUE THREAD

**Issue by bessobesso** [dotnet/aspnetcore#22306]
In Blazor WebAssembly there is an issue when overriding Identity UI. After you add Identity as scaffolded item, you get the exception when running the application:

InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Scripts'. To ignore an unrendered section call IgnoreSection("sectionName").

**Comment by blowdart** [comment]
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/22058
