### ISSUE TITLE
Feature request: Blazor attached properties

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#22316]
It would be great if Blazor would support something similar that Wpf has for attached properties to be able to modify existing html or razor components.

Eg
```
<button RichTextEdit.Action="Bold" RichTextEdit.Key="Ctrl+B">B</button>
```

The `RichTextEdit.Action` extended property in this case would write an additional value to the `class` list of the html button and the `RichTextEdit.Key` would build some keyboard event handler.

The extension properties should be able to use the `[CascadingParameter]' logic to access the RichTextEdit in this case.

Now when you want to extend existing components you need to use inheritance and or composition what causes a lot of 'unneeded' classes and in case of composition a lot of boilerplate code to forward the logic.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by njannink** [comment]
That is fine, I wouldn't expect it to be implemented pronto, But as I stated I think it would be a great addition to Blazor like in Wpf.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
