### ISSUE TITLE
Test failure: HttpsHelloWorld

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#22329]
https://dev.azure.com/dnceng/internal/_build/results?buildId=661928&view=ms.vss-test-web.build-test-results-tab&runId=20521988&resultId=121091&paneView=debug

<details>
<summary>Error</summary>

```
Error Message:
   Assert.Equal() Failure
           (pos 0)
Expected: Scheme:https; Original:
Actual:   <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML úúú
           (pos 0)
```
</details>

<details>
<summary>Stacktrace</summary>

```
  Stack Trace:
     at Microsoft.AspNetCore.Server.IIS.FunctionalTests.HttpsTests.HttpsHelloWorld(TestVariant variant) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/HttpsTests.cs:line 54
```
</details>

**Comment by jkotalik** [comment]
Closing as I added more logging and a potential fix. As this affects a large range of issues, the next time a test fails for this reason we'll file a new issue.
