### ISSUE TITLE
Opening Microsoft.AspNetCore.Razor.Language for editing

### ISSUE THREAD

**Issue by sharwell** [dotnet/aspnetcore#22325]
I checked out commit 2787157 (current master), but am not able to figure out which solution contains the project Microsoft.AspNetCore.Razor.Language. How can I open this for editing?

**Comment by Pilchie** [comment]
@JunTaoLuo for the question, as he did the migration of this code.

Note that in general, not all projects here are in solutions.  Solutions aren't the official source of truth, we use build.cmd.  Sln files are created for convenience.

**Comment by JunTaoLuo** [comment]
I did not add the migrated coded to any solution files yet. But it should be trivial, so I'll send a PR. I guess the most logical sln file to add these projects to would be src/Razor/Razor.sln
