### ISSUE TITLE
[Razor tooling LSP VS] try/catch/finally does not have proper coloring

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22330]
We probably missed adding a theme definition for try/catch statements.

![image](https://user-images.githubusercontent.com/2008729/83185414-ce72c280-a0df-11ea-83eb-fcbd38d1fa65.png)

**Comment by ryanbrandenburg** [comment]
![image](https://user-images.githubusercontent.com/14987221/96312193-f5af2b00-0fbf-11eb-9767-fdf578fb7a59.png)
Seems to have been fixed by something or other.
