### ISSUE TITLE
VS LSP: Revert revert of pre-booting language servers

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#22331]
We need to revert this PR https://github.com/dotnet/aspnetcore-tooling/pull/1940 after [this](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1132146) external issue is fixed.

**Comment by NTaylorMullen** [comment]
aspnetcore-tooling commit to revert: 0b8f2d759c2d29369353cdfd2f420116e8112011

**Comment by TanayParikh** [comment]
Part of Big Rock: https://github.com/dotnet/aspnetcore/issues/23524
