### ISSUE TITLE
[Blazor WASM] HttpClient ignoring headers added from 3rd party REST client library.

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/aspnetcore#22345]
I have a REST client library called PortableRest that makes it easy to write API client libraries. I'm trying to build out a new library for a really great API. The problem is, it uses a non-injected internal HttpClient instance, and the requests that are going over the pipeline work just fine in .NET Core, but when I drop it in a Blazor WASM app, it's not sending the Authorization headers in the CORS request.

![image](https://user-images.githubusercontent.com/1657085/83219174-a914a180-a13d-11ea-8a8e-98513f9c0817.png)

Since I can't control how the API is being used, I [added some code here](https://github.com/CloudNimble/PortableRest/blob/master/src/PortableRest/RestClient.cs#L586-L607) to try to set what the extension methods do internally, but that does not appear to have an effect.

I've also tried using reflection to load the `WebAssemblyHttpHandler` and pass it into the client, but I didn't see a behavior difference there either:
```csharp
    var wasmHttpMessageHandlerType = Assembly.Load("System.Net.Http.WebAssemblyHttpHandler")
        .GetType("System.Net.Http.WebAssemblyHttpHandler");
    var handler = (HttpMessageHandler)Activator.CreateInstance(wasmHttpMessageHandlerType);

    var client = new CourierClient(apiKey, handler);
    var request = new SendMessageRequest(some, parameters, here)
    {
        SomeProperty = "SomeValue"
    };
    var result = await client.SendMessageAsync(request).ConfigureAwait(false);
```

I could totally be doing this wrong, but it feels like a bug that I can't just drop in code to access a 3rd party API and it just works. A lot of downloadable 3rd party clients will be totally broken on Blazor if the HttpClient isn't drop-in (zero code changes) compatible.

**Comment by SteveSandersonMS** [comment]
If I understand correctly what you're asking, the behavior you're seeing is required by the CORS spec: https://stackoverflow.com/questions/52072001/the-authorization-header-is-not-sent-in-options-call-by-the-browser

If that is the case then the server-side logic is incorrect if it requires an authentication header on a CORS preflight, since no browser-based application would be able to do that.

**Comment by robertmclaws** [comment]
Ah that makes sense then. We have not experienced this problem in PortableRest before because server-side calls do not require an CORS preflight request. The fact that PortableRest is not presently adding the headers on those calls means no changes are necessary, and I'll follow up with the service we're calling to see if they can make the changes inside AWS to allow unauthenticated preflight requests. Thank you SO much for the quick response, and I'll close this issue.

Have a great weekend everyone, and keep up the amazing work! 👊🏻
