### ISSUE TITLE
Blazor WASM 3.2.0 PWA hosting in Azure

### ISSUE THREAD

**Issue by Sridhar-Narasimhan** [dotnet/aspnetcore#22352]
### Describe the bug
When hosting a new Blazor WASM and PWA enabled project in Azure, I am getting the below console error and it is not behaving as PWA because of service-worker issues. Not able to install the application as APP

**Browser console error** 
Failed to find a valid digest in the 'integrity' attribute for resource 'https://blazor.syncfusion.com/staging/pwacheck/index.html' with computed SHA-256 integrity 'chA9vyVFdxRQ16fU2feTVTwD0fjmqhwlZ93UwzLoOVo='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch

### To Reproduce
1. Create Blazor WASM PWA app with Visual Studio project template in Windows 
2. Publish the app
3. Host the published folder in Azure App service
4. Check the below link 
https://blazor.syncfusion.com/staging/pwacheck

### Further technical details
- ASP.NET Core version 3.1
- IDE - VS 2019 - Windows 10

**Comment by SteveSandersonMS** [comment]
Your `service-worker-assets.json` manifest specifies that `index.html` must have the hash `giUiNJlgVATak9INpTux+S07Po7KtIfCDhBlN4PSn4k=`, but your server is returning a response whose hash is `chA9vyVFdxRQ16fU2feTVTwD0fjmqhwlZ93UwzLoOVo=`.

So, something is modifying that file as part of how you're deploying or serving the file. Are you perhaps editing or transforming that file deliberately in some way?

I notice that it's *only* your `index.html` file that has an incorrect hash. For example, your `app.css` file correctly has the hash `BHNhq10T...` in both `service-worker-assets.json` and in the server's actual response.

**Comment by Sridhar-Narasimhan** [comment]
@SteveSandersonMS  Yes, I am changing the <base ref> to get it loaded in the specific site URL.

**Comment by SteveSandersonMS** [comment]
@Sridhar-Narasimhan You need to modify the `<base href>` *before* the integrity hashes are computed, otherwise you'll break the integrity checks. Here's an example of a build process that updates the base href before the integrity hashes are computed: https://github.com/SteveSandersonMS/BlazorOnGitHubPages/blob/master/.github/workflows/main.yml
