### ISSUE TITLE
Add ControllerBase method overloads for enriching ProblemDetails reponse with "detail" property

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#22357]
Currently, `ControllerBase` has two overloads of `NotFound`:

* `NotFound()`
* `NotFound(Object)`

The first produces a `NotFoundObjectResult` that ultimately generates a `ProblemDetails` object that looks like this:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "|fe918ccc-4080a43436455ab2."
}
```

The second serializes whatever's passed to it and dumps the result to the response. If what's passed to it is a `string`, you get just a string out, no `ProblemDetails`.

However, if you define the following on a class deriving from `ControllerBase`:

```csharp
public IActionResult NotFound(string detail)
    => Problem(statusCode: StatusCodes.Status404NotFound, detail: detail);
```

and invoke it via `return NotFound("foo");` you receive the following:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "detail": "foo",
  "traceId": "|fe918ccc-4080a43436455ab2."
}
```

Much better!

Questions:

1. Would it be desirable to add overloads of the various 400/500-status-returning methods on `ControllerBase` in this manner?
2. If so, what is the most "correct" way to define these methods? Is what I've got acceptable, or would it be more correct to define a `StatusCodeWithDetailResult` class and have a whole bunch of derived subclasses a la `StatusCodeResult`? Or...?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to add to the framework.
You can do this in your application if you wish.
