### ISSUE TITLE
Blazor Wasm with Microsoft.ML works in Release mode but not Debug mode

### ISSUE THREAD

**Issue by htram** [dotnet/aspnetcore#22358]
### Describe the bug
Standalone Blazor Wasm app using the Microsoft.ML package produces this error when running in Debug mode:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load the file 'Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

However, when running in release mode, everything works fine.

### To Reproduce

GitHub repo: https://github.com/htram/BlazorWasmML
Steps to reproduce:
  1) Open in VS2019 (dotnet version 3.1.300)
  2) Build and run the app in Debug mode.
  3) Launch from VS2019 by pressing F5
  4) Navigate to the page "Prediction" - page does not work.  Take note of the error about Microsoft.ML.StandardTrainers in the browser console.
  5) Repeat the steps above in Release mode, and everything works.
  

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Enterprise 2019
Version 16.5.5

**Comment by javiercn** [comment]
@htram thanks for contacting us.

We'll look into this issue and get back to you.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by mkArtakMSFT** [comment]
@bribrothers FYI
