### ISSUE TITLE
When publishing a web application using AddRazorRuntimeCompilation I get old Sdk files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22359]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1040835/when-publishing-a-web-application-using-addrazorru.html)._

---
[regression] [worked-in:16.5.5]
I use VS 2019 with the latest update (ver 16.6.0) and publish a web application to a folder.

When I checked the "refs"-folder files they suddenly are of an older version, e.g.:
- Microsoft.AspNetCore.Antiforgery.dll
- File version 3.100.220.6801
- Product version 3.1.2

Is this how it is supposed to be?

-----------------------------------------------------------------------------------------------------
Have the following runtime/sdk installed:

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---
#### Per Andersson on 5/20/2020, 03:09 AM: 

<p>I actually tried it on a computer with VS 2019 v. 16.5.5, and after installing the latest SDK it now has the same issue, publishing old files to the "refs"-folder, so it wasn't an issue that came with the upgrade, I just assumed it were.</p><p>------------ edit</p><p>I also now found that the 3.1.4-files is not available in the "C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref" folder, only 3.1.2 and 3.1.3.</p><p>Is it safe to use the earlier published 3.1.3 files until you fixed this issue?</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

#### Per Andersson on 5/20/2020, 03:52 AM: 

<p>I downloaded the "dotnet-sdk-3.1.300-win-x64" binaries instead of the installer, and found that the "packs/Microsoft.AspNetCore.App.Ref"-folder actually contains the older files (3.1.2), not the new ones.</p>

#### Visual Studio Feedback System on 5/20/2020, 08:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Per Andersson on 5/24/2020, 01:59 AM: 

And do note, the &quot;installer&quot; and the &quot;binaries&quot; packages have different &quot;packs\Microsoft.AspNetCore.App.Ref&quot; file versions, both tagged 3.1.2 though.<br>
#### Kevin Pilch [MSFT] on 5/26/2020, 10:55 AM: 

<p>Hi - can you describe exactly how you are publishing, and what “refs” folder you mean?</p>
<p>It’s by design that the reference pack “Microsoft.AspNetCore.App.Ref” isn’t always updated.  We normally try <em>not</em> to change the API surface area in servicing releases, and only ship an updated ref pack when we need to.</p>
<p>However, if you publish your app self-contained, you should be getting the implementation assemblies, not the reference assemblies in your publish output.</p>

#### Per Andersson on 5/26/2020, 00:24 PM: 

<p>Hi,</p><p>I'm publish a "Framework-Dependent" ASP.NET Core 3.1 web application to a "Folder", and then simply copy the files to a server.</p><p>The "refs" folder contain the files needed for the app to be able to compile views at runtime, and is copied to the "publish" folder when I run "Build/Publish".</p><p>To enable it all I installed the nuget "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation Version=3.1.4" and then added "services.AddRazorPages().AddRazorRuntimeCompilation()" to my "Startup" class.</p><p>This result in the "refs" folder being published along with the app files.</p><p>Now, when I do this using the latest VS 16.6.0 / SDK 3.1.300, the "refs" files are of an older version then when I'm using the previous VS 16.5.5 / SDK 3.1.202.</p><p>For example, the "Microsoft.AspNetCore.Antiforgery.dll" has the following properties;</p><p>With VS 16.6.0 / SDK 3.1.300</p><p> - File version 3.100.220.6801</p><p> - Product version 3.1.2</p><p> - Date 2020-01-18 17:35</p><p>With VS 16.5.5 / SDK 3.1.202</p><p>- File version 3.100.320.12812</p><p>- Product version 3.1.3</p><p>- Date 2020-02-29 04:25</p><p>So what I am asking is, how can it be that the "refs" folder files when using VS 16.6.0 / SDK 3.1.300 are older than when I use VS 16.5.5 / SDK 3.1.202?</p><p>One would expect they at least should be of the same product/file version than the previous SDK, or no, and it is okay that they suddenly are of an older version?</p><p>And even more confusing were when I found that the "refs" files in the downloadable "X64 binaries" package where newer than the one's in the "X64 installer" package.</p><p>The same sample file as above had the following properties in the SDK 3.1.300 "X64 binaries" package:</p><p> - File version 3.100.220.10506</p><p> - Product version 3.1.2</p><p> - Date 2020-02-05 23:22</p>

#### Kevin Pilch [MSFT] on 5/28/2020, 03:24 PM: 

<p>Hi <a rel="user" href="https://developercommunity.visualstudio.com/users/157373/03706de5-353b-6ec1-b1f1-7e5e6feb7e06.html" nodeid="157373">@Per Andersson</a>, are you on GitHub?  I'd like to migrate this to our GitHub repo so I can tag the relevant parties.</p>

#### Per Andersson on 5/28/2020, 10:12 PM: 

<p>Hi <a rel="user" href="https://developercommunity.visualstudio.com/users/951/2904c194-844a-4770-9298-753672609e83.html" nodeid="951">@Kevin Pilch [MSFT]</a> ... Great, and yes, I have an account with the same username/Microsoft account named "perason".</p>

---
### Original Solutions
(no solutions)

**Comment by Pilchie** [comment]
Also tagging @perandersson.

**Comment by perason** [comment]
Thanks...that did the trick

**Comment by wtgodbe** [comment]
Closing as this has been answered
