### ISSUE TITLE
Blazor EditContext.OnFieldChanged notify wrong item when a list is filter or sorted

### ISSUE THREAD

**Issue by aguacongas** [dotnet/aspnetcore#22355]
### Describe the bug
When the an `EditForm`'s model contains a list of stuff and we have an UI allowing the user to filter or sort this list. The event `EditContext.OnFieldChanged` will contains the item at index of the not filtered nor sorted list modified and not the good one.

### To Reproduce
```cs
@using System.ComponentModel.DataAnnotations

<EditForm EditContext="_editContext" OnValidSubmit="HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />
    @foreach (var stuff in _model.List)
    {
        <div>
            @stuff.Id 
            <InputText @bind-Value="stuff.Name" />
        </div>
    }
    <button type="submit">Submit</button>
</EditForm>
<button type="button" @onclick="Sort">Sort</button>
@code {
    private EditContext _editContext = new EditContext(new Model
    {
        List = new List<Stuff>
        {
                new Stuff(),
                new Stuff(),
                new Stuff(),
        }
    });

    private StuffComparer _stuffComparer = new StuffComparer();

    private Model _model => _editContext.Model as Model;

    private void Sort()
    {
        ((Model)_editContext.Model).List.Sort(_stuffComparer);
        StateHasChanged();
    }

    protected override void OnInitialized()
    {
        _editContext.OnFieldChanged += (sender, e) =>
        {
            Console.WriteLine((e.FieldIdentifier.Model as Stuff).Id);
        };
    }

    private void HandleValidSubmit()
    {
    }

    class Stuff
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        [Required]
        public string Name { get; set; }
    }

    class Model
    {
        public List<Stuff> List { get; set; }
    }

    class StuffComparer : IComparer<Stuff>
    {
        bool desc;
        public int Compare(Stuff x, Stuff y)
        {
            desc = !desc;
            if (desc)
            {
                return y.Id.CompareTo(x.Id);
            }
            return x.Id.CompareTo(y.Id);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/3294829/83267529-a610c400-a1c4-11ea-88b0-8b40e15d55a9.png)

### Further technical details
- Blazor 3.2

**Comment by adrianwright109** [comment]
Hi,

Check out this link: [https://blazor-university.com/components/render-trees/optimising-using-key/](https://blazor-university.com/components/render-trees/optimising-using-key/)

When using a collection/loop and you want to identify each item correctly in the collection you need to use the `@key` attribute.

Modify your code to include the `@key` attribute on the `<InputText />` component.  This will then track the correct component instances with the correct item from the collection.

E.g.
`<InputText @bind-Value="stuff.Name" @key="stuff.Id" />`

**Comment by aguacongas** [comment]
That fix the issue

**Comment by mrpmorris** [comment]
@aguacongas Please re-open this ticket. `@key` should be for optimising updates to make the deltas smaller, not for making the UI work correctly. This is a bug.

PS: I've simplified the example to eliminate the possibility of coder error.

```
@page "/"
@using System.ComponentModel.DataAnnotations

<EditForm Model=@_model>
	<DataAnnotationsValidator />
	<ValidationSummary />
	@foreach (var stuff in _model.List)
	{
		<div>
			@stuff.Id
			<InputText @bind-Value="stuff.Name" class="@stuff.Id" />
		</div>
	}
	<button type="submit">Submit</button>
</EditForm>
<button type="button" @onclick="Sort">Sort</button>

@code {
	private Model _model = new Model
	{
		List = Enumerable.Range(1, 3)
			.Reverse()
			.Select(x => new Stuff() { Id = x})
			.ToList()
	};

	private void Sort()
	{
		_model.List = _model.List.OrderBy(x => x.Id).ToList();
		StateHasChanged();
	}

	class Stuff
	{
		public int Id { get; set; }

		[Required]
		public string Name { get; set; }
	}

	class Model
	{
		public List<Stuff> List { get; set; }
	}
}
```

**Comment by mkArtakMSFT** [comment]
> @key should be for optimising updates to make the deltas smaller, not for making the UI work correctly. This is a bug.

I don't think that's the case. I believe the usage of `@key` is critical in identifying each item correctly, and it's not just optimization. In simple cases Blazor can do that without that attribute, but in more complex scenarios like `filtering` or `sorting` that matters. @SteveSandersonMS can you please confirm?

**Comment by mrpmorris** [comment]
In the case of validation,  the validation state is keyed on object instance + property name, so `@key` is not required and it should work without it.

But I'll wait and see if I am wrong.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please confirm whether my assumption above is correct or not?

**Comment by mkArtakMSFT** [comment]
Thanks @SteveSandersonMS. Looks like there is nothing else for us to tackle as part of this issue then.
