### ISSUE TITLE
Is a HostedService guaranteed to be started *after* the Startup.Configure method has run?

### ISSUE THREAD

**Issue by drauch** [dotnet/aspnetcore#22350]
The docs state, that a hosted service (I'm using ASP.NET Core 2.1) is started when:

> When using the Web Host, StartAsync is called after the server has started and IApplicationLifetime.ApplicationStarted is triggered.

I don't know if ApplicationStarted is executed _strictly_ after Startup.Configure has finished running. Is this guaranteed?

Best regards,
D.R.

**Comment by Tratcher** [comment]
Yes, Configure is always run before triggering ApplicationStarted (see BuildApplication).
2.1:
https://github.com/dotnet/aspnetcore/blob/9e38dcf1fc0335862e1ba6f19fc6a1f30e82ebb0/src/Hosting/Hosting/src/Internal/WebHost.cs#L140-L155
3.1:
https://github.com/dotnet/aspnetcore/blob/a9449cd20c2150917355d8ba7a30fa19b47569f7/src/Hosting/Hosting/src/Internal/WebHost.cs#L148-L166

What has changes is the ordering of IHostedService's being called. This was moved up in 3.0.
