### ISSUE TITLE
Azure AD B2C with .net core 3.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22366]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1034008/azure-ad-b2c-with-net-core-31.html)._

---
<p>Hi,</p><p>I'm developing an Asp.net Core 3.1 application, where I have tried setting up Azure AD B2C-authentication.</p> <p>I have followed one of the official tutorials, and the B2C Tennant and application seems to be OK.</p> <p>There is one issue I cannot resolve, and that is the .net core mvc application not finding the .well-known openid configuration from AD B2C.</p> <p>When I check the user flow in AD B2C I find that the .well-know is located:<a href="https://sensaino.b2clogin.com/4b844349-95b9-46c9-9570-e09af946e61d/v2.0/.well-known/openid-configuration?p=B2C_1_SiUpIn">https://{domain}.b2clogin.com/{DirectoryID}/v2.0/.well-known/openid-configuration?p=B2C_1_SiUpIn</a></p><p>When I Try using the standard .net core setup against AD B2C it will try to open the file at: https://login.microsoftonline.com/tfp/{DOMAIN}/B2C_1_SiUpIn/v2.0/.well-known/openid-configuration</p><p>I have tried several configuration changes without being able to get the .net core mvc app to point at the correct openid-configuration.</p> <p>My Configuration:</p><pre> &quot;AzureAdB2C&quot;: {     //&quot;Instance&quot;: &quot;https://{domain}.b2clogin.com/tfp/&quot;,     &quot;Instance&quot;: &quot;https://login.microsoftonline.com/tfp/&quot;,     &quot;ClientId&quot;: &quot;{application id}&quot;,     &quot;CallbackPath&quot;: &quot;/signin-oidc&quot;,     &quot;Domain&quot;: &quot;{domain}.onmicrosoft.com&quot;,     &quot;SignUpSignInPolicyId&quot;: &quot;B2C_1_SiUpIn&quot;,     &quot;ResetPasswordPolicyId&quot;: &quot;B2C_1_SSPR&quot;,     &quot;EditProfilePolicyId&quot;: &quot;&quot;   }  </pre><p>I have tried different Instances, which I have found in the documentation, but I cannot get any of them working.</p> <p>Are there anything I can do in my config to make my app reach the .well-known config for the correct user flow in AD B2C?</p> <p>Best Regards</p><p>Trond J. Undrum</p>

---
#### Visual Studio Feedback System on 5/15/2020, 02:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
Hey Trond, hopefully you say this, this is better asked of the b2c team at https://github.com/azure-ad-b2c/ - they will know the details of their platform.
