### ISSUE TITLE
Default Blazor App causes Browser error "crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22364]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1047003/default-blazor-app-causes-browser-error-crit-micro.html)._

---
<p>I created a fresh Blazor App with the checked options Progressive Web Application and <a href="https://ASP.NET">ASP.NET</a> Core as Backend. Then I started the created Client project and I see the working Blazor App in my Firefox Browser. After it, I clicked on the menu &quot;Fetch data&quot;.<br>
Then I opened the developer Tools in Firefox (F12) and it showed me:</p>
<pre>crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The provided ContentType &lt;span class=&quot;hljs-keyword&quot;&gt;is&lt;/span&gt; not supported; the supported types are &lt;span class=&quot;hljs-string&quot;&gt;'application/json'&lt;/span&gt; and the structured syntax suffix &lt;span class=&quot;hljs-string&quot;&gt;'application/+json'&lt;/span&gt;.
System.NotSupportedException: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
  at System.Net.Http.Json.HttpContentJsonExtensions.ValidateContent (System.Net.Http.HttpContent content) &lt;0x2df2c10 + 0x0009e&gt; in &lt;filename unknown&gt;:0 
  at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync[T] (System.Net.Http.HttpContent content, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) &lt;0x2df2a40 + 0x00006&gt; in &lt;filename unknown&gt;:0 
  at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T] (System.Threading.Tasks.Task`1[TResult] taskResponse, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) &lt;0x2d9cc20 + 0x00150&gt; in &lt;filename unknown&gt;:0 
  at Secretly.Client.Pages.FetchData.OnInitializedAsync () &lt;0x2d61ad8 + 0x000f8&gt; in &lt;filename unknown&gt;:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () &lt;0x2b2a990 + 0x00154&gt; in &lt;filename unknown&gt;:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) &lt;0x2d30098 + 0x000ca&gt; in &lt;filename unknown&gt;:0 
printErr https://localhost:44377/_framework/blazor.webassembly.js:1
    dotNetCriticalError https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/blazor.webassembly.js:1&lt;/span&gt;
    _mono_wasm_invoke_js_unmarshalled https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1&lt;/span&gt;
    mono_wasm_invoke_js_unmarshalled https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:0&lt;/span&gt;
    do_icall https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:1120745&lt;/span&gt;
    do_icall_wrapper https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:339006&lt;/span&gt;
    interp_exec_method https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:154115&lt;/span&gt;
    interp_runtime_invoke https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:1021006&lt;/span&gt;
    mono_jit_runtime_invoke https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:916474&lt;/span&gt;
    do_runtime_invoke https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:252761&lt;/span&gt;
    mono_runtime_try_invoke https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:53204&lt;/span&gt;
    try_invoke_perform_wait_callback https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:754597&lt;/span&gt;
    worker_callback https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:641129&lt;/span&gt;
    fire_tp_callback https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:1078598&lt;/span&gt;
    mono_background_exec https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.wasm:972459&lt;/span&gt;
    _mono_background_exec https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1&lt;/span&gt;
    pump_message https:&lt;span class=&quot;hljs-comment&quot;&gt;//localhost:44377/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1&lt;/span&gt;
</pre>

---
#### Visual Studio Feedback System on 5/25/2020, 04:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Waldemar Nowak on 5/26/2020, 09:58 PM: 

<p><em>Hints to developer working on this bug:</em></p><p>"Progressive Web Application" option is not relevant. However, I have noticed that problem appears when debugging session runs with "Set as Startup Project" on <strong>.Client</strong> project. When I set startup project on .<strong>Server</strong> project, then this bug does not occur. </p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
The server project needs to be setup as the startup project, otherwise the Server API fetchdata calls is not available and an error is returned from the developer server, which is not json and causes the error described here to happen.
