### ISSUE TITLE
Tooling repo build flakiness

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#22368]
There were a couple build failures recently in the tooling repo related to uploading the `RazorLanguageServer-[os].zip` files.
https://dev.azure.com/dnceng/public/_build/results?buildId=663296&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=2f0f1e20-badc-52e7-dbc6-29a52429fc6c

The public builds have both a Windows release and Windows debug leg, and during the failures I've observed so far both legs were trying to upload the same zip at the same time.

This might be unrelated, but regardless, we should avoid uploading the same file to the same location in two different legs.

**Comment by dougbu** [comment]
> This might be unrelated, but regardless, we should avoid uploading the same file to the same location in two different legs.

Agreed. We should _not_ push anything to BlobArtifacts unless it either has a unique name (including the build configuration if doing a matrix) or the upload only happens for Release builds. I have no idea why we need anything but test results from Debug builds. @NTaylorMullen any idea?

I also doubt this is a big task. No real reason to push it into a future sprint if I'm right.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen any idea?

We don't. Just an oversight 😄

I pushed it to the next sprint for now purely because we're already overloaded and I'm less familiar with how to wire everything together

**Comment by dougbu** [comment]
dotnet/aspnetcore-tooling@eef7deb29b82
