### ISSUE TITLE
Blazor DebugProxy returns undefined in Debugger.evaluateOnCallFrame or Runtime.evaluate

### ISSUE THREAD

**Issue by digeff** [dotnet/aspnetcore#22375]
### Describe the bug
We got stack traces in telemetry (see https://github.com/microsoft/vscode-js-debug/issues/485) which indicates that Blazor is returning undefined in the result field of Debugger.evaluateOnCallFrame or Runtime.evaluate. In the CDP protocol that field is not marked as optional, so it should never be undefined.

### To Reproduce
We got this stack trace from telemetry, so we don't know how to reproduce this issue

### Further technical details
Debugging Blazor in VS

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19890
