### ISSUE TITLE
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by arno0826** [dotnet/aspnetcore#22382]
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost:65029/swagger/index.html  
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.2\Microsoft.AspNetCore.WebUtilities.dll”。
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.2\Microsoft.AspNetCore.Http.Extensions.dll”。
引发的异常:“System.TypeLoadException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“System.TypeLoadException”(位于 System.Private.CoreLib.dll 中)
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Diagnostics.StackTrace.dll”。
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Reflection.Metadata.dll”。
“iisexpress.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Collections.Immutable.dll”。
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Infrastructure.Middleware.RequestResponseLoggingMiddleware.FormatRequest(HttpRequest request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Infrastructure.Middleware.RequestResponseLoggingMiddleware.FormatRequest(HttpRequest request)
   at Infrastructure.Middleware.RequestResponseLoggingMiddleware.Invoke(HttpContext context) in D:\XXXXXXXXXX
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I get this wrong error when I upgrade the project from asp.net core 2.2 to 3.1

**Comment by davidfowl** [comment]
This was an intentional braking change that was made. This method is internal and the new API is EnableBuffering https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-3.1
