### ISSUE TITLE
Possible unexpected behaviors caused by RequestLocalizationMiddleware

### ISSUE THREAD

**Issue by matteoumili** [dotnet/aspnetcore#22386]
https://github.com/dotnet/aspnetcore/blob/5c155d41477d0e79819fcba5af498fbee92fbe97/src/Middleware/Localization/src/RequestLocalizationMiddleware.cs#L147

In this line, the RequestLocalizationMiddleware sets the current thread culture to be the same as the one specified by the request.
Due to the fact that with async/await a thread can process simultaneously two different requests, can't this lead to unexpected behaviors if the thread process two requests with a different culture at the same time?

**Comment by pranavkm** [comment]
`Thread.CurrentCulture` and `CultureInfo.CurrentCulture` is backed by an `AsyncLocal`, so this should be fine

**Comment by matteoumili** [comment]
Sorry, I was looking CultureInfo source code in the wrong repository
