### ISSUE TITLE
How do you set the `Microsoft.Extensions.Hosting.IHostEnvironment.ApplicationName` used by the "Identity" area for Blazor WebAssembly?

### ISSUE THREAD

**Issue by TheMagnificent11** [dotnet/aspnetcore#22383]
I have created a new project using the Blazor WebAssembly template in Visual Studio 2019 (version 16.6), using "Individual User Accounts" for authentication.

It created an "Identity" scaffolded application area, which is a separate seems to be a standard ASP.Net Core MVC app.

I've set an environment variable called `DEVELOPMENT_APPLICATIONNAME` to my desired application name (as documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#applicationname)). 

However, the web page title and what appears in the "branding" above the navbar is still the name of the c-sharp project.

It appears the `Microsoft.Extensions.Hosting.IHostEnvironment.ApplicationName` does not pass from the main MVC application to the "Identity" area.

Am I doing something wrong or is this a bug/limitation of scaffolded application areas?

**Comment by javiercn** [comment]
@TheMagnificent11 thanks for contacting us.

I'm not really sure where you are trying to access the ApplicationName, if it is within Blazor WebAssembly or within ASP.NET Core Identity.

Within ASP.NET Core Identity the value is present and usable.
Blazor Webassembly doesn't have that concept and it is not flowed from the server to the client automatically.

**Comment by TheMagnificent11** [comment]
Well, it's not the Blazor app that needs to access the `ApplicationName` property.  The pages scaffolded for the Identity application area uses it to display the name of the application at the top of the navbar (in the Bootstrap "branding" section) and also in the HTML title-tag.

This issue may not have anything to do with Blazor; it may be an issue with Identity UI application area that is scaffolded to handles users accounts not honouring the environment variable set for the `ApplicationName`.

**Comment by TheMagnificent11** [comment]
It's an easy issue to replicate.
1. Create a Blazor app from the Visual Studio template, selecting "Individual Accounts" for authentication.
2. Add a `DEVELOPMENT_APPLICATIONNAME` environment variable to change the name of the application to something different to the c-sharp project name.
3. Run the application and click the "Register" link in the top-right of the page.
4. The application name displayed in the navbar will be the c-sharp project name and not the value set in the environment variable.

**Comment by mkArtakMSFT** [comment]
@TheMagnificent11 if you scaffold the identity pages, you have full control over each scaffolded page.
We don't plan to change this at the moment. If this turns out to be a common pain point, we'll reconsider this for the future releases.
