### ISSUE TITLE
[Blazor] @bind async

### ISSUE THREAD

**Issue by JvanderStad** [dotnet/aspnetcore#22394]
https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1

Data-binding takes place with the following syntax:
```razor
<input @bind="CurrentValue" />

@code {
    private string CurrentValue { get; set; }
}
```
this is equivalent of
```razor
<input value="@CurrentValue"
    @onchange="@((ChangeEventArgs __e) => CurrentValue = 
        __e.Value.ToString())" />
        
@code {
    private string CurrentValue { get; set; }
}
```
I can use the `setter` of the bound property to handle some extra logic

```c#
[Parameter]
public EventCallback<string> Callback { get; set; }

private string _value;
private string CurrentValue
{
	get => _value;
	set {
             _value = value;

             // extra logic

             // await Callback.InvokeAsync(value);   
             // above does not work, we are in the 'sync'-world
        }
}
```

I find myself starting with this pattern and then getting stuck because I need to call something async. I rewrite the thing to handle the events myself, but it feels a bit... not finished. It becomes a real pain if you have made a reusable component and you need to refactor a lot to make it work with the async call.

Can we introduce a convention to allow async calls with two way binding?

**Comment by JvanderStad** [comment]
Idea similar to the `Changed` postfix.

```razor
<input @bind="CurrentValue" />

@code {
    private string CurrentValue { get; set; }
    private Task<string> CurrentValueGetAsync()
    {
    }
    private Task CurrentValueSetAsync(string value)
    {
    }
}
```
You start out with a normal property and add `async` methods if required

**Comment by javiercn** [comment]
@JvanderStad thanks for contacting us.

We'll take a look at this issue and get back to you.

**Comment by JvanderStad** [comment]
What is the current recommended pattern to use when using two way binding with async calls?

**Comment by JvanderStad** [comment]
Reference https://github.com/dotnet/aspnetcore/issues/17099#issuecomment-556882628

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by JvanderStad** [comment]
@mkArtakMSFT Sure, no problem.
Do you have an answer to my question? I can't find it in the docs.

> What is the current recommended pattern to use when using two way binding with async calls?

**Comment by mrpmorris** [comment]
The current way to do it is to one-way bind the value, and from `@onchange` call your async method that will set your property vague and do other necessary async work.

**Comment by chrdlx** [comment]
> The current way to do it is to one-way bind the value, and from `@onchange` call your async method that will set your property vague and do other necessary async work.

The problem with that is that you lose all the datatype conversions/culture formatting/etc that @Bind provides....   
So now if you use value/onchange,  you have to format/convert everything from/to the property manually, which is a pain....

 I just stumbled upon with this same scenario an hour ago! I decided just to not make async DB calls....  =)

**Comment by mrpmorris** [comment]
Can you hook into an event on EditContext and then fire off your code if the name of the property changed is the one you are interested in?

**Comment by TLA020** [comment]
I have the same issue, having used a lot of "SPA" javascript frameworks. i'm used to computed properties like vue has and "watchers".

In one of my components i receive a property (Volume) from the store(stateContainer). This volume is updated by a socket event everytime someone on the app changes the volume of the player.

This Volume property i use to show a slider, when the user changes the slider, the setter of the property gets called, and i want to do a http request to change the volume.

After that all users get their volume updated by socket event that changes the volume value in the state/store.

Example:

` <MudSlider Immediate="false" @bind-value="@Volume" Min="0" Max="100">Volume</MudSlider>`

` C#  

public int Volume
    {
        get => StateContainer.Player.Volume;
        set
        {
            Console.WriteLine("Volume test");
          // await Actions.SetVolume(player.Id, value);
        } 
    }
`

**Comment by TLA020** [comment]
> I've ended up here too, am' I doing something wrong, is my programming approach incorrect? I too would like to allow async calls with two way binding please, thank you...

Try my suggestion. that works.

**Comment by mrpmorris** [comment]
two-way async binding doesn't make sense to me.
What it seems people are after is the ability to detect a change to an input, react asynchronously, and then update their model.

e.g. look-ahead searching when typing in a country.

This is already possible by having an input with a change event hooked up. It doesn't even need model binding.

Am I wrong?

**Comment by javiercn** [comment]
@mrpmorris partially.

There is some magic with `@bind` that you don't get with `attribute + event handler`, but that's why we are working on an improved `@bind` syntax that will allow you to run async code after the value has been bound.

**Comment by mrpmorris** [comment]
@javiercn Could you explain?

**Comment by javiercn** [comment]
@mrpmorris you can read more here https://github.com/dotnet/aspnetcore/issues/39837

I'm going to close this issue as a dupe, since the issue I pointed out superseeds this one.

**Comment by chrdlx** [comment]
> > I've ended up here too, am' I doing something wrong, is my programming approach incorrect? I too would like to allow async calls with two way binding please, thank you...
> 
> Try my suggestion. that works.

There has been a workaround since day 1, which is using the the "value" parameter and "onchange" events...  
The problem again,  is that you have to code the extra features that @bind provides yourself....    in your suggestion you're even using what it seems to be a state management system to simulate the 2 way binding that @bind provides out of the box... which I feel is totally overkill.

**Comment by kibblewhite** [comment]
> > I've ended up here too, am' I doing something wrong, is my programming approach incorrect? I too would like to allow async calls with two way binding please, thank you...
> 
> Try my suggestion. that works.

Hey @TLA020, thank you so much for your suggestion, it was noted and attempted as one of the first things we did.

Unfortunately, that approach won't work for me, I'm currently looking into a way to attach an attribute to the property that will trigger an async method now.

Apologies for not being able to explain it clearly. To give a little more background, it involves a WYSIWYG editor where the users who will implement this, don't want to and should not have to (as defined in our specifications) write their own methods to handle the situation of pushing values into the component, I think in the example you have provided it would mean that they will have to create their own "OnVolumeChanged" method. We are trying to avoid this, however from writing this comment, I'm having strange ideas of nesting a component inside of a component now **evil grin** lol
