### ISSUE TITLE
Blazor server not handling Http POST requests 

### ISSUE THREAD

**Issue by sencagri** [dotnet/aspnetcore#22398]
Hello,

I am trying to make a payment page with blazor server side. The payment service makes a Http POST request to a URL I gave them when making request. But I could not find a way to handle their callback request. I added a Razor Page like below :

```c#
namespace AktifBarkod.AktifPOS.Web.RestoranSipariş.Pages
{
    public class OdemeSonucModel : PageModel
    {
        [Inject]
        public SiparişService SiparişService { get; set; }

        public void OnGet()
        {

        }

        public void OnPost()
        {
            var options = new Options();
            options.ApiKey = "apikey";
            options.SecretKey = "secretkey";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            RetrieveCheckoutFormRequest request = new RetrieveCheckoutFormRequest();
            request.Token = SiparişService.ÖdemeToken.ToString();

            CheckoutForm checkoutForm = CheckoutForm.Retrieve(request, options);
        }
    }
}
```

I thought OnPost will handle the POST requests but it is not working. Is there any way to handle not GET requests in blazor app. 

Thanks.

**Comment by javiercn** [comment]
@sencagri thanks for contacting us.

* Did you create a .cshtml (Razor page?) inside the pages directory?
* Did you call MapRazorPages() within app.UseEndpoints?
* Did you try to post to the page directly from within fiddler?

**Comment by sencagri** [comment]
Yes. I created .cshtml page. MapRazorPages called. I both use payment service sandbox and POSTMAN app to send POST requests.

![1](https://user-images.githubusercontent.com/7950917/83350607-e481bc80-a345-11ea-9f67-a747f5a49fc3.png)
![Ek Açıklama 2020-05-31 135108](https://user-images.githubusercontent.com/7950917/83350608-e5b2e980-a345-11ea-9c75-5fc1bf4af090.png)

I am getting **400 Bad Request**

![3](https://user-images.githubusercontent.com/7950917/83350627-0e3ae380-a346-11ea-80d1-dd4538641190.png)

**Comment by javiercn** [comment]
@sencagri thanks for the details. 

It is very likely that you are missing an antiforgery token. 

Are you making a POST request from a server-side Blazor app into a razor page on the same app? Why not instead handle the form submission from within server-side Blazor?

**Comment by sencagri** [comment]
No. Payment service call my URL. I am not making POST request inside my application.

1-) I am making a request to payment service. They give me a special URL to go. And also, I give them a URL(which is my razor page) to return to my app.
2-) I navigate to the URL for process payment which is not my application.
3-) After they process the payment. They call my URL with POST request. If it were a GET request there would not be a problem.

And I could'nt understand what you mean by an antiforgery token. Are we supposed to use razor pages only in our application ? Can't we handle http requests coming from outside our application?

**Comment by javiercn** [comment]
@sencagri Razor pages has automatic CSRF protection, so what's likely happening is that in the postback to your response the page is checking for an antiforgery token in the request that doesn't exist.

You can put `@attribute [IgnoreAntiforgeryToken]` in your page and the request should go through

**Comment by sencagri** [comment]
This is great! It worked.

Thank you very much Javier for fast responses.
