### ISSUE TITLE
Fix warning: "in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB)."

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22390]
There are at least a dozen of these new warnings or the related "in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB).". See https://dev.azure.com/dnceng/internal/_build/results?buildId=664792&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=bcce746a-741e-59b7-adec-a4a82d8c5e52&l=2262 for example.

Looks like these warnings started with #22268.

Part of #22240.

**Comment by dougbu** [comment]
Also linked to "in webpack performance recommendations:" warnings, bringing the total new warnings up to at least 18.

**Comment by pranavkm** [comment]
@javiercn do you want to look? You are likely more familiar with this than I am:

```
##[warning]src\Components\WebAssembly\WebAssembly.Authentication\src\Microsoft.AspNetCore.Components.WebAssembly.Authentication.csproj(63,5): warning : (NETCORE_ENGINEERING_TELEMETRY=Build) in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
  This can impact web performance.
  Assets: 
    AuthenticationService.js (268 KiB)
```

**Comment by javiercn** [comment]
@pranavkm Yes, I'm not sure how we can get rid of these. I will investigate

**Comment by javiercn** [comment]
We can just disable the warning.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/22703
