### ISSUE TITLE
Is it possible to invoke components to the project by including the library in the blazor runtime

### ISSUE THREAD

**Issue by burakakca** [dotnet/aspnetcore#22399]

**Comment by javiercn** [comment]
@burakakca thanks for contacting us.

Can you please clarify what you are trying to achieve?

**Comment by burakakca** [comment]
I have the idea of downloading and using a widget while the project is live

**Comment by burakakca** [comment]
Like wordpress

**Comment by javiercn** [comment]
@burakakca I think you might be looking at something like [this](https://github.com/dotnet/aspnetcore/issues/5465) which is in our roadmap.

I'm closing this issue as a dupe of #5465.

For the time being we don't have a built-in solution, but you can look at some available third-party solutions.
