### ISSUE TITLE
Can't serve valid blazor.webassembly.js from Docker after upgrading to 3.2.0

### ISSUE THREAD

**Issue by MorganR** [dotnet/aspnetcore#22392]
### Describe the bug
After upgrading from Blazor Wasm 3.2.0-preview3.20168.3 to the 3.2.0 release, my docker container is sending invalid data when requesting blazor.webassembly.js. The browser says: `Uncaught SyntaxError: Invalid or unexpected token`. The contents look like garbage, eg. `RÍåH…zZ¬™¿¶ìÖæ'M—√`. This prevents any of my Blazor WASM code from running.

With the preview 3 release, I had no issues. The contents looked like valid javascript, and the app worked. I also have no issues when running locally from Visual Studio, whether that's with a debug build or a release build.

When the file contents are garbage, I also noticed that the HTTP response headers changed. The headers `content-encoding: gzip` and `vary: accept-encoding` are now missing. Maybe I'm seeing still-gzipped data? Hopefully that helps track down the bug.

The app is hosted in Asp.Net core.

### To Reproduce
I've recreated this in a simple repro here: https://github.com/MorganR/BlazorWasmIssue

Sync to [this commit](https://github.com/MorganR/BlazorWasmIssue/commit/abbe60733b8ec695bc00060400597eeb98c36986) for the broken version: abbe60733b8ec695bc00060400597eeb98c36986
Then sync to [this commit](https://github.com/MorganR/BlazorWasmIssue/commit/6f792f047cc15dcdfb6273c14d2618c11cf056f7) for the working (preview 3) version: 6f792f047cc15dcdfb6273c14d2618c11cf056f7

You can find the broken sample app running here: https://issue-repro-kjnd6hddpa-uc.a.run.app/
And the working (preview 3) version running here: https://issue-repro-preview3-kjnd6hddpa-uc.a.run.app/

### Further technical details
- ASP.NET Core version: 3.1.300
- Output of `dotnet --info` from my local comp:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The docker image uses official MS images; see the [Dockerfile](https://github.com/MorganR/MorganRoff/blob/master/Dockerfile) for details.

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Visual Studio 2019 - Version 16.6.0

**Comment by MorganR** [comment]
Ah turns out this is a Google Cloud Run issue with Brotli compression, which seems to be enabled by default after updating from the preview. Root issue with Cloud Run is here: https://issuetracker.google.com/issues/147185337

How can I disable Brotli compression? I've tried a few things based on https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.1#compression-with-secure-protocol, but have not succeeded.

**Comment by srpeirce** [comment]
Have you tried setting the options to NoCompression? 

```csharp
services.Configure<BrotliCompressionProviderOptions>(options => 
    {
        options.Level = CompressionLevel.NoCompression;
    });
```

**Comment by MorganR** [comment]
No, unfortunately I've tried that but it's still serving compressed Brotli data. It does seem to fix things locally when running with `ASPNETCORE_ENVIRONMENT` set to `Development`, but doesn't work when running in `Production` mode and deployed on Cloud Run. For some reason trying to run in `Production` mode locally is leading to completely different problems where no static files are serving at all (i.e. my custom css and the blazor.webassembly.js file both return 404).

I also tried deploying instances with:

```csharp
public void ConfigureServices(IServiceCollection services)
{
  services.AddResponseCompression(
    options =>	
    {	
      options.Providers.Add<GzipCompressionProvider>();
    });
    services.Configure<BrotliCompressionProviderOptions>(options =>
    {
      options.Level = CompressionLevel.NoCompression;
    });
}
```

and another one that additionally had:

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
  app.UseResponseCompression();
}
```

Unfortunately none of those changes worked. I wonder if it's actually possible to override the compression options being used for blazor framework files at all? Presumably the framework is setting its own compression options, since the files were initially compressed without me requesting it.

**Comment by MorganR** [comment]
Yup, looks like `app.UseBlazorFrameworkFiles()` [sets up compression options here](https://github.com/dotnet/aspnetcore/blob/78d6ce201ff955bac07899bdc7c54abe6bd57125/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L53) using a custom [ContentEncodingNegotiator](https://github.com/dotnet/aspnetcore/blob/78d6ce201ff955bac07899bdc7c54abe6bd57125/src/Components/WebAssembly/Server/src/ContentEncodingNegotiator.cs), but I don't actually see where/how this connects to the compression providers. It looks like maybe the framework files have been pre-compressed into static files, so for example a request for blazor.webassembly.js will retrieve blazor.webassembly.js.br or blazor.webassembly.js.gz if br or gzip compression are supported. If that's the case, then it looks like I can't modify this at all.

Hopefully someone from MSFT can confirm, and this can be a feature request to customize the compression options for framework files?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You should disable compression as you're trying to compress already compressed assets.

**Comment by mkArtakMSFT** [comment]
@javiercn can you add some info regarding how to do that? Thanks!

**Comment by javiercn** [comment]
You can use `BlazorEnableCompression` in your MSBuild file to disable static file compression if you want.

**Comment by MorganR** [comment]
Can confirm that solved my problem. Thanks folks! I added this to the WASM client project and to the ASPNET core server project:

```xml
<PropertyGroup>
  <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
</PropertyGroup>
```
