### ISSUE TITLE
Dependency Injection of IConfiguration is not working as expected in Blazor Webassembly project

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#22402]
1. Create a hosted Blazor wasm project
2. Create a new .Net Standard 2.1 library project. Set reference to this library project from the "Client" project
3. In the Library project, create a new class AppState, and inject IConfiguration in its constructor
4. Register AppState in Client's Program.cs like so:
`builder.Services.AddScoped<AppState>();` 
5.  Notice that any of the configuration values cannot be accessed inside the AppState class (i.e. they are returned as empty strings). Injecting IConfiguration inside a page/component and accessing config values on a page/component works, but not from inside AppState.

### Further technical details
- ASP.NET Core version: Blazor Wasm 3.2.0
- Include the output of `dotnet --info`: .Net Core 3.1.3
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 1.0

**Comment by pranavkm** [comment]
Can you share a minimal app that exhibits the problem? I am unable to reproduce this if I follow your steps. 

With a WASM hosted apps, there's two sets of appsettings - one in the Server that's used during prerendering and one in the Client that's used by WebAssembly. This might explain of the issues you're seeing here.
