### ISSUE TITLE
Blazor-wasm runtime issue: "Cannot wait on monitors on this runtime"

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/aspnetcore#22400]
### Describe the bug
Using async/await under certain conditions causes a runtime failure with Blazor, with the exception "Cannot wait on monitors on this runtime".

### To Reproduce
Please look at [the following repo](https://github.com/jan-johansson-mr/BlazorTaskIssue) that have a slight modification to the Blazor-wasm template to provoke the runtime exception.

The repo also show a work-around for the runtime issue.

The page that provokes the issue is the `fetchdata` page (e.g. fetching weather).

### Further technical details
- ASP.NET Core version 3.1.4
- Microsoft Visual Studio Community 2019 Preview Version 16.7.0 Preview 1.0
- dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Thanks

**Comment by javiercn** [comment]
@jan-johansson-mr thanks for contacting us.

Is the usage of `.Result` https://github.com/jan-johansson-mr/BlazorTaskIssue/blob/master/BlazorApp2/Pages/FetchData.razor#L65 that causes this issue.

The mono runtime is single threaded, so I would suggest you file an issue in the [mono repo](https://github.com/mono/mono).

**Comment by jan-johansson-mr** [comment]
Thanks,

I'll do that!

**Comment by JonTvermose** [comment]
I think we're running into the same issue. 
When we are in a synchronous context and needs to make a async http request, we recieve the same error message.
In our case we need to fetch string resources for a StringLocalizer from our backend api.
@javiercn Is there a workaround?

**Comment by javiercn** [comment]
@JonTvermose You'll have to architect around it. I suggest you extract the async work out of the sync code path and cache the results for use within the sync path.
