### ISSUE TITLE
An Issue of Blazor WebAssembly Localization

### ISSUE THREAD

**Issue by huazhenhz** [dotnet/aspnetcore#22417]
![ExceptionCausedBy blazorCulture get](https://user-images.githubusercontent.com/8695237/83414808-47f41300-a448-11ea-9642-08e2e0cee41b.png)

![ExceptionCausedBy blazorCulture get -Program](https://user-images.githubusercontent.com/8695237/83414853-5c381000-a448-11ea-9afb-10dd9c849aff.png)

Hello, Sir,
Blazor WebAssembly 3.2 GA, when we executed the code as below, the exception was caused.

```
var jsInterop = host.Services.GetRequiredService<IJSRuntime>();
var result = await jsInterop.InvokeAsync<string>("blazorCulture.get");
```

We need to know what the reason is.
Many Thanks!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It seems you're missing a configuration step.
The doc article here will help you with that: https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1

**Comment by huazhenhz** [comment]
![image](https://user-images.githubusercontent.com/8695237/83435625-c19af980-a466-11ea-9767-a22caf1830f9.png)
Can you help tell me about the relevant details?

**Comment by huazhenhz** [comment]
I saw the website you provided in the past.
But I haven't found the important information on it.

**Comment by huazhenhz** [comment]
![image](https://user-images.githubusercontent.com/8695237/83467087-270cdb80-a4a3-11ea-853b-9adabbf94daa.png)
In the "index.html", I added the code for "blazorCulture" as below:
```
<script>
        window.blazorCulture = {
            get: () => window.localStorage['BlazorCulture'],
            set: (value) => window.localStorage['BlazorCulture'] = value
        };
</script>
```
The program can run without errors.

**Comment by huazhenhz** [comment]
But the when we switch the current language from "en-US" to "zh-TW", we couldn't get the expected result.
![image](https://user-images.githubusercontent.com/8695237/83467528-5ec85300-a4a4-11ea-924b-c1333d521326.png)

**Comment by huazhenhz** [comment]
Solved, thanks!

**Comment by huazhenhz** [comment]
But we are disappointed that the Blazor WebAssembly still needs to depend on the JavaScript Block.
