### ISSUE TITLE
Calling AddIdentity().AddDefaultUI() causes custom endpoints to stop working (.NET Core 3.1.4)

### ISSUE THREAD

**Issue by machinewrapped** [dotnet/aspnetcore#22416]
### Describe the bug
I'm rebuilding a site in ASP.NET Core (3.1.4, was MVC before). I set up a number of custom endpoints which all route to the same controller action but with different optional parameters. This was working fine until I added scaffolded identity. After investigating, it is specifically the call to `AddDefaultUI()` which breaks the endpoints.

Building links to these endpoints with tag helpers _continues to work correctly_, producing the expected link for the custom endpoint, e.g.

```
<a asp-route="MoviesPerson" asp-route-person="@member.Name" asp-route-page="1">@member.Name</a>
```

correctly builds a link to a URL that matches this endpoint:

``` C#
                endpoints.MapControllerRoute(
                    name: "MoviesPerson",
                    pattern: "Person/{person}/{page}",
                    defaults: new { controller = "Movies", action = "Index", page = 1 }
                );
```

But when the URL /Person/Name/1 is visited a 404 is returned and the controller action is never hit.

Enabling Trace logging for Microsoft.AspNetCore.Routing I see that with `AddDefaultUI` commented out DfAMatcher matches a custom endpoint:

```
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: 1 candidate(s) found for the request path '/Person/Shinya Tsukamoto/1'
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: Endpoint 'TheSite.Controllers.MoviesController.Index (TheSite)' with route pattern 'Person/{person}/{page}' is valid for the request path '/Person/Shinya Tsukamoto/1'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request matched endpoint 'TheSite.Controllers.MoviesController.Index (TheSite)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'TheSite.Controllers.MoviesController.Index (TheSite)'
```

But with it uncommented DfaMatcher doesn't even see any candidates:

```
Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Debug: No candidates found for the request path '/Person/Shinya Tsukamoto/1'
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Debug: Request did not match any endpoints
```

### To Reproduce

As a minimal example, add a custom endpoint in `Configure`:

``` C#
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "MoviesPerson",
                    pattern: "Person/{person}/{page}",
                    defaults: new { controller = "Movies", action = "Index", page = 1 }
                );

                endpoints.MapDefaultControllerRoute();
                endpoints.MapRazorPages();
            });
```

And call `AddIdentity` in `ConfigureServices`:

``` C#
            services.AddIdentity<IdentityUser, IdentityRole>(options =>
            {
                options.User = new UserOptions() { RequireUniqueEmail = true };
                options.Password = new PasswordOptions()
                {
                    RequiredLength = 10,
                    RequiredUniqueChars = 4,
                    RequireDigit = false,
                    RequireLowercase = false,
                    RequireNonAlphanumeric = false,
                    RequireUppercase = false
                };
            })
            .AddRoles<IdentityRole>()
            .AddEntityFrameworkStores<IdentityContext>()
            .AddRoleManager<RoleManager<IdentityRole>>()
            .AddDefaultTokenProviders()
            //.AddDefaultUI()       //---- This line breaks endpoints
            ;
```

### Further technical details
- Tried with ASP.NET Core version version 3.1.3 and 3.1.4
- Using Visual Studio Community 2019

```
dotnet --info
>>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@machinewrapped thanks for contacting us.

Can you produce an actual minimal repro project that illustrates the issue? That greatly helps us avoid any missing detail that might be relevant.

**Comment by machinewrapped** [comment]
Hi, I created a fresh minimal project which illustrates the problem.

https://github.com/machinewrapped/Bugs/tree/master/RoutingFailure

The site as commited works fine - the various endpoints get used to build links and are routed correctly,

Uncommenting the call to AddDefaultUI in Startup.cs causes it to stop working -  the links still use the endpoints but DfaMatcher no longer considers them for routing.

I created the project without authentication initially then added it via Add New Scaffolded Item, since that's how I did it with my actual project, in case that makes a difference.

**Comment by br3nt** [comment]
Adding `AddDefaultUI` makes everything work as expected, however, according to [these docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0) `AddDefaultUI` shouldn't be needed.  

It says the following multiple times:
`If the Identity scaffolder was used to add Identity files to the project, remove the call to AddDefaultUI`.

Following [the code](https://github.com/aspnet/Identity/blob/feedcb5c53444f716ef5121d3add56e11c7b71e5/src/UI/IdentityBuilderUIExtensions.cs#L48) it seems to be doing a lot more than what I would want it to :/.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
