### ISSUE TITLE
Usage of app.UseAuthorization()

### ISSUE THREAD

**Issue by DENMODSupport** [dotnet/aspnetcore#22414]
Hi,
I want to know what is the use of app.UseAuthorization() in asp.net core application. what will happen if we didnt add it in startup.cs file

**Comment by blowdart** [comment]
Authorization won't happen. Simple as that.

**Comment by DENMODSupport** [comment]
is it mandatory to add this middleware for ASP.net core 2.1 app? Also in my app, user.identity.name is not working for some of the new users alone. Also we are using authorize attribute in our action methods but app.useauthorization middleware was not added in startup.cs file. do you have nay idea on that?

**Comment by blowdart** [comment]
I believe it's mandatory, @pranavkm ?

As for your other issue, please open a new issue for it.

**Comment by pranavkm** [comment]
AuthorizationMiddleware and `UseAuthorization` was introduced in 3.0 so you wouldn't be able to use it in a 2.2 application. Prior to this, MVC relied on authorization filters and SignalR had it's own implementation for auth.
