### ISSUE TITLE
Support Runtime Compilation of Razor Code Streams

### ISSUE THREAD

**Issue by kramffud** [dotnet/aspnetcore#22422]
Take Razor runtime compilation to the Nth degree.  Allow us to dynamically generate Razor code at runtime, feed that Razor stream to Razor.RuntimeCompilation and let it deliver HTML to the client.

Let us leverage the power of Razor model binding, tag-helper interpretation, partial views, RCL and its infusion of anti-forgery tokens and other security, but let us generate that Razor code at runtime according to the User's context, send the code to the runtime compiler and it sends the HTML to the User.

Is that possible w/o?

 ```
services.AddControllersWithViews()
    .AddRazorRuntimeCompilation(options => options.FileProviders.Add(
        new PhysicalFileProvider(appDirectory)));
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
