### ISSUE TITLE
Integrity checks failing on Asp.Net Core hosted Blazor Web assembly PWA deployed to Azure 

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#22425]
I deployed an asp.net core hosted Blazor webassembly PWA project to Azure, and I am getting integrity check failures, after which the service worker does not work correctly. 

The integrity check is likely failing because Azure is inserting AppInsights javascript code in the head section of index.html. Please see below screenshot.

Is there a suggested workaround for this issue?

![image](https://user-images.githubusercontent.com/13262438/83436980-88ca3880-a404-11ea-915e-e33081f603e3.png)

### Further technical details
- Blazor version: Blazor Wasm 3.2.0 
- .Net version: .Net Core 3.1.3
- (VS / VS Code/ VS4Mac) : Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something customers periodically are confused about. We will put together an FAQ to help customers investigate these issues on their own: https://github.com/dotnet/aspnetcore/issues/22470

**Comment by dazinator** [comment]
@bancroftway - just checking - could you be effected by: https://github.com/dotnet/aspnetcore/issues/22999

**Comment by bancroftway** [comment]
I am closing this issue because the integrity check is failing due to an automatic injection of appinsights javascript code snippet in index.html
