### ISSUE TITLE
Code disappears on override

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22438]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1050332/code-disappears-on-override.html)._

---
When I try to override the OnInitializedAsync method on a Blazor component, the whole @code block gets removed

---
#### Visual Studio Feedback System on 5/26/2020, 11:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Didn't mean to move this.
