### ISSUE TITLE
Server-side Blazor: Frequent LongPolling disconnects after I click on back browser button

### ISSUE THREAD

**Issue by fabiano-ferreira** [dotnet/aspnetcore#22443]
Hello! I am developing a Blazor Server application.

In this project I'm currently using:
 - Telerik Components;
 - EF Core with Microsoft SQL Server (version 12.0.6329.1)
 - Microsoft Identity Core
- Windows Server 6.2 (Build 9200) as the Web Server
- IIS Version 8.5.9600.16384

I just created a completely blank page. 

I also have a default not found page template.

<NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>

The problem happens after the Non-Existing page is displayed. If I click on the back browser button, I get the following error in my browser console (Chrome Version 83.0.4103.61):

[2020-06-01T23:43:13.514Z] Error: The list of component records is not valid.

I realized that this problem only happens in case I follow these steps:

- Open the blazor page (everything's ok)
- Wait for a timeout to happen with no page interaction (2 to 3 minutes) (everything's ok);
- Click on an invalid link (not existing in my Application yet) (everything's ok);
- Click on the browser back button (Error occurs)

This is the debug log at my browser console:

blazor.server.js:15 [2020-06-01T23:43:13.384Z] Information: Starting up blazor server-side application.
blazor.server.js:1 [2020-06-01T23:43:13.385Z] Information: Normalizing '_blazor' to 'https://<server>/_blazor'.
blazor.server.js:1 [2020-06-01T23:43:13.386Z] Debug: Starting HubConnection.
blazor.server.js:1 [2020-06-01T23:43:13.386Z] Debug: Starting connection with transfer format 'Binary'.
blazor.server.js:1 [2020-06-01T23:43:13.387Z] Debug: Sending negotiation request: https://<server>/_blazor/negotiate?negotiateVersion=1.
blazor.server.js:1 [2020-06-01T23:43:13.414Z] Debug: Selecting transport 'LongPolling'.
blazor.server.js:1 [2020-06-01T23:43:13.450Z] Debug: The HttpConnection connected successfully.
blazor.server.js:1 [2020-06-01T23:43:13.450Z] Debug: Sending handshake request.
blazor.server.js:1 [2020-06-01T23:43:13.478Z] Debug: Server handshake complete.
blazor.server.js:1 [2020-06-01T23:43:13.480Z] Information: Using HubProtocol 'blazorpack'.
blazor.server.js:1 [2020-06-01T23:43:13.480Z] Debug: HubConnection connected successfully.
blazor.server.js:15 [2020-06-01T23:43:13.514Z] Error: The list of component records is not valid.
e.log @ blazor.server.js:15
C @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.poll @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.connect @ blazor.server.js:1
e.startTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.createTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startWithStateTransitions @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
S @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
E @ blazor.server.js:8
start @ Location:145
(anonymous) @ Location:149
Show 37 more frames
blazor.server.js:1 [2020-06-01T23:43:13.514Z] Debug: Stopping HubConnection.
blazor.server.js:1 [2020-06-01T23:43:13.533Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting.
blazor.server.js:1 [2020-06-01T23:43:13.533Z] Information: Connection disconnected.
blazor.server.js:1 [2020-06-01T23:43:13.533Z] Debug: HubConnection.connectionClosed(undefined) called while in state Disconnecting.

**Comment by javiercn** [comment]
@fabiano-ferreira thanks for contacting us.

Try applying `@Attribute [ResponseCache(NoStore=true)]` to `_Host.cshtml` and see if that fixes the issue

**Comment by fabiano-ferreira** [comment]
Hi Javier! It worked! Thanks!
