### ISSUE TITLE
Upgrade to 3.2.0 results in ArgumentNullException at NavigationManager.Initialize uri parameter

### ISSUE THREAD

**Issue by char8cter** [dotnet/aspnetcore#22454]
- Describe the bug

I followed all the steps published on the blog to upgrade my existing projects to use Microsoft.AspNetCore.Components.WebAssembly 3.2.0. When I try to run the new project I get an ArgumentNullException in the NavigationManager.Initialize. Seems that the uri parameter is null for some reason. I am not sure what I need to configure for this to work as this happens immediately after entering the Main of the Client project when the call to  WebAssemblyHostBuilder.CreateDefault(args) is made.

- Exceptions

﻿System.ArgumentNullException: Value cannot be null. blazor.webassembly.js:1:36074
Parameter name: uri blazor.webassembly.js:1:36074
  at Microsoft.AspNetCore.Components.NavigationManager.Initialize (System.String baseUri, System.String uri) <0x2a14970 + 0x00014> in <filename unknown>:0 blazor.webassembly.js:1:36074
  at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyNavigationManager..ctor (System.String baseUri, System.String uri) <0x2a147a8 + 0x0000a> in <filename unknown>:0 blazor.webassembly.js:1:36074
  at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.InitializeNavigationManager (Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyJSRuntimeInvoker jsRuntimeInvoker) <0x298a270 + 0x00036> in <filename unknown>:0 blazor.webassembly.js:1:36074
  at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder..ctor (Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyJSRuntimeInvoker jsRuntimeInvoker) <0x297bbf8 + 0x00060> in <filename unknown>:0 blazor.webassembly.js:1:36074
  at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.CreateDefault (System.String[] args) <0x297ad40 + 0x00018> in <filename unknown>:0 blazor.webassembly.js:1:36074
  at Cabcall.Web.TTC.Client.Program.Main (System.String[] args) <0x297a468 + 0x00038> in <filename unknown>:0 blazor.webassembly.js:1:36074
  at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint (System.String assemblyName, System.String[] args) <0x2905558 + 0x0011a> in <filename unknown>:0 

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.514 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- IDE

Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 1.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting this. We have tests which confirm this is working as expected.
You can create a new project and diff it with your current project to find the missing bits.
