### ISSUE TITLE
Committing completion items removes surrounding brackets.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22455]
In Codespaces typing `[Para]` and completing the `Parameter` removes surrounding brackets
![nOWjmmHue2](https://user-images.githubusercontent.com/2008729/83481168-f05aa500-a451-11ea-9cc9-4ade4e660d8c.gif)

/cc @AmadeusW

**Comment by AmadeusW** [comment]
Is this 16.7-preview.2?
LSP code guesses the completion span. The short fix is to exclude braces from the span. The long term fix is to update VS completion to use LSP pattern of lazy & per-item span

**Comment by NTaylorMullen** [comment]
> Is this 16.7-preview.2?

VSMaster client and Internal Staging server skew as of yesterday.

I'll have to take a look at the C# completion spans but I imagine they wouldn't be doing anything special which would lead me to believe this is a root issue in either the LSP platform or CoreEditor. Especially given that completion starts when the user types `P` (an identifier).
