### ISSUE TITLE
Who can tell me how to create Razor Complie Enviroment?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#22457]
Now I am using roslyn for dyamic compliation.  But  It must use a node `<PreserveCompilationReferences>true</PreserveCompilationReferences>`  in .csproj. 
Then I make a library " A" like this: https://github.com/dotnetcore/Compile.Environment/blob/master/DotNetCore.Compile.Environment/build/DotNetCore.Compile.Environment.targets

Not works:
- I push it on nuget and named "A".
- Create a  library B which added libraryA from nuget. 
- Then push B to nuget.
- Create project C and adding library B from nuget.
- Run dynamic compliation . It failed.

Work well:
- replace "A" to "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation".
- C works well.

C --> B --> A   don't work
C--> B --> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation work well.

I have been bothered by it for a year. Can the someone help me?

**Comment by javiercn** [comment]
@NMSAzulX thanks for contacting us.

I don't think this is an area we expose for users to consume.

/cc: @NTaylorMullen

**Comment by NMSAzulX** [comment]
@javiercn Thank you for your reply. I hope there is a library that can transfer the environment to other class libraries, Razor can reuse it, and developers can reuse it. :)

**Comment by NMSAzulX** [comment]
So far, only Razor has achieved this function perfectly. @javiercn @NTaylorMullen

**Comment by NMSAzulX** [comment]
Is anyone here???

**Comment by NMSAzulX** [comment]
Hello? ? Is this difficult? Can the dynamically compiled environment be separated? Should I ask a question at Roslyn?

**Comment by pranavkm** [comment]
@NMSAzulX you'll need the target files to appear as part of `build` and `buildTransitive`. Here's what runtime compilation does: https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Razor.RuntimeCompilation/src/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.csproj#L31

**Comment by NMSAzulX** [comment]
@pranavkm Hello! What is DefaultNetCoreTargetFramework? Is this a variable in the new version of nuget? My project needs to be compiled into two versions, netstandard2.0 and netcoreapp3.0.

**Comment by javiercn** [comment]
No, that's part of our build infrastructure. You'll have to adapt what @pranavkm has suggested you to match your scenarios.
