### ISSUE TITLE
Cannot create MemoryStream in blazor (wasm)

### ISSUE THREAD

**Issue by zxyao145** [dotnet/aspnetcore#22458]
### Describe the bug
I'm trying to read a file in blazor (wasm), but I get an error result. All MemoryStream bytes are 0. The code is as follows, and I'm sure the bytes have data (I printed them in the console).

### To Reproduce

```
private async Task<Stream> CreateMemoStream(byte[] bytes)
{
	Stream s = new MemoryStream();
	await s.WriteAsync(bytes);
	s.Position = 0;
	await s.FlushAsync();
	//debug
	var br = new BinaryReader(s);
	var bytes2 = new byte[s.Length];
	br.Read(bytes2);
	Console.WriteLine(string.Join(',', bytes2));// here is "0,0,0,...,0"
	return s;
}
```

### Further technical details
- ASP.NET Core version: 3.1
- blazor WebAssembly 3.2.0
- VS 16.6.0

**Comment by javiercn** [comment]
@zxyao145 thanks for contacting us.

I'm not sure what's going on in your snippet, but that would be a runtime issue, which is better suited for the mono folks. I suggest you file an issue on the [mono repo](https://github.com/mono/mono) instead as they can give you a faster and better answer.
