### ISSUE TITLE
Changing AppSettings in Azure restarting the Worker Service

### ISSUE THREAD

**Issue by rangav** [dotnet/aspnetcore#22461]
### Describe the bug
When I change the app settings in azure, the worker service is re-started. Its working fine in Local

### To Reproduce
1. Create a worker service (default template) and create appsettings section and a value
2. Inject iOptions<AppSettings> in the worker constructor.
3. Publish to azure app service.
4. override the app settings value in azure with a new value
5. The worker service stopped ( goto webjobs section to see status)
6. After few seconds the service started again.

### Further technical details
- ASP.NET Core version 3.1

**Comment by rangav** [comment]
here is app configuration section

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
.ConfigureAppConfiguration((hostingContext, config) =>
{
    var env = hostingContext.HostingEnvironment;
    config.SetBasePath(env.ContentRootPath);
    config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: false, reloadOnChange: true);
    config.AddEnvironmentVariables();
})
.ConfigureServices((hostContext, services) =>
{
    services.AddLogging(s => s
            .AddConfiguration(hostContext.Configuration.GetSection("Logging"))
            .AddConsole(o => o.Format = ConsoleLoggerFormat.Systemd));

    services.Configure<AppSettings>(hostContext.Configuration.GetSection(AppSettings.ConfigurationName));

    services.AddHostedService<Worker>();
});
```

appsettings class
```csharp
public class AppSettings
    {
        public const string ConfigurationName = "AppSettings";

        public string AppName { get; set; }
    }
```

Worker Service Code
```csharp
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly AppSettings _appSettings;

        public Worker(ILogger<Worker> logger, IOptions<AppSettings> appSettings)
        {
            _logger = logger;
            _appSettings = appSettings.Value;
        }

        public override Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Worker started...");
            return base.StartAsync(cancellationToken);
        }

        public override Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Worker stopping....");
            return base.StopAsync(cancellationToken);
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                _logger.LogInformation($"AppSettings Value: {_appSettings.AppName}");

                await Task.Delay(30000, stoppingToken);
            }

            _logger.LogInformation("Worker shutdown...");

        }
    }
```

**Comment by Tratcher** [comment]
@bradygaster

**Comment by davidfowl** [comment]
That’s by design. Changing app settings in app service restarts the application

**Comment by bradygaster** [comment]
Just curious - were you on App Service Windows? Or Linux? Or Containers? Just curious.

**Comment by rangav** [comment]
It was deployed on App Service on windows, no containers.

**Comment by rangav** [comment]
Changing appsettings on web app will only reload settings without restarting app right?

It should be the same with worker service. Otherwise it will break all the long running jobs in background.

Again the StopAsync func never called.

From the config setting, reloadOnChange should reload settings only right? with out restarting app.
`config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)`

**Comment by ilmax** [comment]
@rangav AFAIK it restarts webapps as well

**Comment by rangav** [comment]
Is there any option to reload settings without restarting app?

**Comment by davidfowl** [comment]
Not using the app settings in the azure portal no. You would need to change the file on disk

**Comment by rangav** [comment]
Ok thanks for clarifying
