### ISSUE TITLE
How to get the authentication cookie string after HttpContext.SignInAsync()?

### ISSUE THREAD

**Issue by thepra** [dotnet/aspnetcore#22462]
I need that string to implement a mechanism for logout-from-all-devices, but without I have no way to figure out this mechanism. 
Is there a way to get such data?

**Comment by blowdart** [comment]
You don't need to. The cookie authentication middleware has the ValidatePrincipal event which allows you to examine the identity, and decide what to do with it. This can do what you want, on login you put in a value into a claim which is changed when your logout everywhere mechanism is triggered. In ValidatePrincipal you check that value and reject the principal and logout if it doesn't match.

See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#react-to-back-end-changes

**Comment by thepra** [comment]
After further search I found the way through:
```
var settingCookies = response.GetTypedHeaders().SetCookie;
```
which gives the list of setCookies, from which I can filter out the one from authentication like:
```
settingCookies?.First(sc => sc.Name == $".AspNetCore.{CookieAuthenticationDefaults.AuthenticationScheme}")?.Value.ToString();
```
It was quite an intense search for an answer to find, but [here](https://stackoverflow.com/questions/36899875/how-can-i-check-for-a-response-cookie-in-asp-net-core-mvc-aka-asp-net-5-rc1) it is.
So there is a way, but as answered by @blowdart the approach with a middleware might be a better solution, which I'll adapt and use. Thanks.
