### ISSUE TITLE
Suspected bug in Microsoft.AspNetCore.Identity.SignInManager<TUser>

### ISSUE THREAD

**Issue by xenophilios** [dotnet/aspnetcore#22471]
Dear Friends,

This report concerns the following method in the above class:

public virtual async Task<bool> ValidateSecurityStampAsync(TUser user, string securityStamp) =>
user != null && (!UserManager.SupportsUserSecurityStamp || securityStamp ==
await UserManager.GetSecurityStampAsync(user));

The method summary says that this method will always return "false" if the UserManager does not support security stamps.

From the code as it stands, it seems to me that it will always return "true" in this situation, unless "user" is null.

If the statement in the summary is what is truly intended, I would suggest amending the code to read as follows:

public virtual async Task<bool> ValidateSecurityStampAsync(TUser user, string securityStamp) =>
user != null && UserManager.SupportsUserSecurityStamp && securityStamp ==
await UserManager.GetSecurityStampAsync(user));

With best regards,

Eric Weinberger (xenophilios)
eukalemia@yahoo.com

**Comment by HaoK** [comment]
The code is correct

**Comment by HaoK** [comment]
If there is no user, there's no stamp to validate

**Comment by xenophilios** [comment]
If there is a user, but the UserManager does not support security stamps, it seems to me that the method will return "true". The summary says that it will return "false".

**Comment by HaoK** [comment]
The summary is worded poorly, I'll tweak it

**Comment by xenophilios** [comment]
Thank you.
