### ISSUE TITLE
Add Support for GeoJSON to the Static Files Middleware

### ISSUE THREAD

**Issue by uncheckederror** [dotnet/aspnetcore#22477]
### Is your feature request related to a problem? Please describe.

I am trying to add web maps to my ASP.NET Core MVC project. I want to load a static file from my wwwroot folder containing geometry for my map with the .geojson extension. With the default app.UseStaticFiles(); in my Startup.cs file this doesn't work.

### Describe the solution you'd like

I would like the ASP.NET Core static files middleware to serve up GeoJSON files by default and without additional configuration.

### Additional context

[Create your own GeoJSON file](http://geojson.io/)
[GeoJSON.org](https://geojson.org/)
[GeoJSON standard IETF RFC 7946](https://tools.ietf.org/html/rfc7946)

**Comment by uncheckederror** [comment]
I have created a [pull request](https://github.com/dotnet/aspnetcore/pull/22478) to address this issue. #22478

**Comment by blowdart** [comment]
From the comments in that file;

> We only plan to add new entries where we expect them to be applicable to a majority of developers such as being used in the project templates.

As our templates don't have any instance of GeoJSON this doesn't meet the bar for default inclusion and would be something you need to add yourself during configuration.

**Comment by uncheckederror** [comment]
Okay, fair enough.
