### ISSUE TITLE
Build up an FAQ for common integrity check problems in Blazor WebAssembly

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#22470]

**Comment by jfatticq** [comment]
does this FAQ already exist somewhere?

(I'm looking for some direction since even the blazor VS template app errors for me after the first run in localhost :( )

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/AspNetCore.Docs/pull/20146
