### ISSUE TITLE
How to make .razor files generator work in a component library

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#22489]
I've created a project where I would like to put some razor components into:

```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <RazorLangVersion>3.0</RazorLangVersion>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Forms" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="*" />
  </ItemGroup>
</Project>

I've added a .razor file

```html

@inherits Microsoft.AspNetCore.Components.ComponentBase

<h1>Test</h1>
@code {

}

``` 
But somehow, it seem that the razor generator is not started during build. When I try to reuse the component it doesn't work. What I am doing wrong?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please use the `razorclasslib` template to create a new project and compare it with the one you got - there should be some difference. In general, we recommend using that template for Razor Class Libraries and it'll give you a proper setup.
