### ISSUE TITLE
Cannot identify AuthorizeAttribute from ApiExplorer when using .RequireAuthorization()

### ISSUE THREAD

**Issue by ackginger** [dotnet/aspnetcore#22491]
### Describe the bug
There appears to be no way of identifying from `IApiDescriptionGroupCollectionProvider` that an endpoint is authorized when doing so via:
```
app.UseEndpoints(endpoints => { endpoints.MapControllers().RequireAuthorization(); });
```
No `AuthorizeAttribute` is present in `ControllerActionDescriptor.EndpointMetadata`, as it would be when using controller attributes. As far as I can see nothing authorization related is present in the ApiDescription objects in this scenario.

For context, I am migrating a 2.2 project which used `AuthorizeFilter` and it was previously possible to integration test that all endpoints are authorized correctly using ApiExplorer to check `ControllerActionDescriptor.FilterDescriptors` contains the filter.

In 3.0+ this filter doesn't exist as expected, but neither does the `AuthorizeAttribute` when added in this manner. It seems that `.RequireAuthorization()` uses an `AuthorizeAttribute` under the hood, but this information doesn't make its way to ApiExplorer.

To be clear, the authorization is working correctly in the running app, but this bug is preventing me testing as much as I would like.

### To reproduce
Simple mutation to the Azure single tenant template which reproduces this is here:
https://github.com/ackginger/authorize-attribute-repro
Obviously the auth isn't configured enough to actually work, but the ApiExplorer behaviour is identical to my real app and exemplified in a failing test.

### Further technical details
- ASP.NET Core version 3.1
- dotnet --info 
```
 .NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6
```

**Comment by pranavkm** [comment]
`ControllerActionDescriptor.EndpointMetadata` only reflects the metadata discovered on the controller action. Any metadata configured via the endpoint APIs do not show up here. It was primarily the reason we documented it as being infrastructure-only since it's a bit confusing to use. 

There's a couple of options you could use

a) You could decorate your controllers using `[Authorize]`. That should allow the metadata to show up in the property.
b) You could look up the metadata by reading from `EndpointDataSource`. 
```
var dataSource = serviceProvider.GetRequiredService<EndpointDataSource>();
var endpointMetadata = dataSource.Endpoints.FirstOrDefault(e => e.GetMetadata<ControllerActionDescriptor>() == myActionDescriptor);
```

**Comment by ackginger** [comment]
Perfect, thanks. 
Option b is definitely preferable for me since I want to avoid adding superfluous attributes.
