### ISSUE TITLE
Blazor server-side using HttpClient

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#22493]
### Description of the issue
I am trying to do blazor on top of a current mvc application.
I'm using server-side blazor but also want to keep the architecture of the project to be easy to turn into client sometime in the future. For that reason, I want to make http calls even in server side to my api endpoints. Also those api endpoints are reusable from other clients.

My application currently use Google authentication _only_ with no issue.
What I want to achieve is to have the browser credentials be passes via the http client and also not needing to specify the base address of the server. I see there is some work for client-side with [BaseAddressAuthorizationMessageHandler](https://github.com/dotnet/aspnetcore/blob/78d6ce201ff955bac07899bdc7c54abe6bd57125/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/BaseAddressAuthorizationMessageHandler.cs)

### What I would like as a solution
I would like to have a handy way to add `HttpClient` that take care of auth and base address for this specific scenario.
Using the same infrastructure as web assembly would be ideal.

### "Working" hack/workaround
Currently I managed to work around aka _hack_ it configuring `HttpClient` as a transient service on a middleware and manually reading the aspnet cookie and passing it as a default request header (it's very ugly):

```c#
// Startup.cs ConfigureServices

services.AddHttpContextAccessor();
services.AddTransient(s =>
{
    var uriHelper = s.GetRequiredService<NavigationManager>();
    var httpContextAccessor = s.GetRequiredService<IHttpContextAccessor>();
    var httpClient = new HttpClient()
    {
        BaseAddress = new Uri(uriHelper.BaseUri)
    };
    if (httpContextAccessor.HttpContext.Request.Cookies.TryGetValue(".AspNetCore.Cookies", out var cookieValue))
    {
        httpClient.DefaultRequestHeaders.TryAddWithoutValidation("cookie", $".AspNetCore.Cookies={cookieValue}");
    }
    return httpClient;
});
```

Is there any other prettier/clean way to do this ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You've got a reasonable solution here.
We don't have any baked-in solution for this similar to the one we have for Blazor WebAssembly.

@javiercn, do you have more to add?

**Comment by mrpmorris** [comment]
Don't register anything as Transient if it implements IDisposable.

https://blazor-university.com/dependency-injection/dependency-lifetimes-and-scopes/transient-dependencies/

**Comment by mikecasas** [comment]
Where does the Uri come from in the following?

``` BaseAddress = new Uri(uriHelper.BaseUri)```

**Comment by javiercn** [comment]
@mkArtakMSFT Yes.

IHttpContextAccessor is not a good fit for Blazor as it will not work as you expect. Capture anything you need from the request and pass it down to the root component as parameters, that is the guidance we provide on the docs. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-3.1#blazor-and-shared-state) for details
