### ISSUE TITLE
Docker Blazor WebAssembly Identity Server Core hosted 

### ISSUE THREAD

**Issue by Stefanbs23** [dotnet/aspnetcore#22499]
I am try to work with Docker with Blazor WebAssembly Identity Server(Store user accounts in-app) Core hosted,

I have create the default template in visual studio and set the appsettings.json with the key to load for IdentityServer and use the default IdentityServerSPA profile and set ASPNETCORE_ENVIRONMENT to Production.

Set all the forwarding headers to use, i try different forwarding headers, different profiles for IdentityServer and set the by hand with options i found on all places.

When i am go to the my new blazor page, I see the login screen, i will be login to Identity and go back to the blazor page, then i see my e-mail address and that I'm logged in, works great.

Than i will go to the page /fetchdata

I get the following message.
------
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
--
info: System.Net.Http.HttpClient.BlazorApp1.ServerAPI.LogicalHandler[100]
      Start processing HTTP request GET http://domainname.com:32811/WeatherForecast
--
info: System.Net.Http.HttpClient.BlazorApp1.ServerAPI.ClientHandler[100]
      Sending HTTP request GET http://domainname.com:32811/WeatherForecast
--
Failed to load resource: the server responded with a status of 401 (Unauthorized)
--
info: System.Net.Http.HttpClient.BlazorApp1.ServerAPI.ClientHandler[101]
      Received HTTP response after 95.1399ms - Unauthorized
-------
when i use localhost:32811 now problems, but with domainname.com:32811 gif this messages

Perhaps is something smalls.. but for now i don't see it more with many ours and days...

I'm using

Microsoft.AspNetCore.Components.WebAssembly.Server" Version="3.2.0"
netcoreapp 3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share a minimalistic project which will demonstrate this issue you're facing, so that we can investigate it.

**Comment by Stefanbs23** [comment]
Problem solved... 

What a good night's sleep does to a person. :)

services.AddIdentityServer(x => x.IssuerUri = "http://example.com:32811")
Did the trick
