### ISSUE TITLE
Blazor App Crashes in Debugger When Trying to View an Array

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#22495]
In an attempt to learn Blazor WebAssembly, I've created a test app in which an html button invokes a JavaScript function that stringifies an array of objects from an IndexedDB (called currBBDetails in the code below) and passes them to a Blazor method.  I've placed a break point on the first line of code in the Blazor method.  When the debugger breaks there, I can see that the passed-in array of json strings has the right count, but when I attempt to look at the contents of the array using the cursor triggered pull-down, the app terminates.  When I try to run it again, the browser asks me if I want to restore.  If I simply continue after the break point, the code runs as expected.   I assume there's a bug in here somewhere.

I am using VS Community 2019 v16.6.1 with AspNetCore v3.2.0 Components installed via NuGet, running on Windows 10.  

Steve

Here's the JS and Blazor code:

`// This function couldn't be written in TS because the DotNet reference triggered an error
async function passBBDetails()
{
    var jsonBBDetailsArray = [];
    for (var i = 0; i < currBBDetails.length; i++)
    {
        jsonBBDetailsArray.push(JSON.stringify(currBBDetails[i]));
    }
    var promise = DotNet.invokeMethodAsync('ME Web', 'PassBBDetailJsonArray', jsonBBDetailsArray)
        .then(function (result) { document.getElementById("convertedText").innerText = result; })
        .catch((event) => { console.error('StaticBlazorMethod error'); });`

`[JSInvokable]
    public static string PassBBDetailJsonArray(string[] jsonText)
        {
        List<BBDetail> listBBDetail = new List<BBDetail>();
        foreach (string json in jsonText)
            {
            BBDetail bbDetail = (BBDetail)JsonSerializer.Deserialize(json, typeof(BBDetail));
            listBBDetail.Add((BBDetail)bbDetail);
            }

        return "Pass BBDetail to Blazor SUCCESS.";
        }`

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19905
