### ISSUE TITLE
Is there any concrete example for Blazor WASM and Electron

### ISSUE THREAD

**Issue by JawadJaber** [dotnet/aspnetcore#22498]
As the Blazor WASM is out, I am looking for solid and recent foundation, documents, or example on how to start with Electron + Blazor WASM?

What is the milestone for this option?

**Comment by mkArtakMSFT** [comment]
We don't have any committed plans for Electron work .We have a sample when we've experimented with it, which can be found at: https://github.com/aspnet/AspLabs/tree/master/src/ComponentsElectron
