### ISSUE TITLE
Blazor Server - the circuit failed to initialize

### ISSUE THREAD

**Issue by dsmolen1** [dotnet/aspnetcore#22494]
I have published the BlazorApp1 app created by the VS2019 Blazor template to a production server. Since it is a sub-site, I made 3 changes: 1) in _Host.cshtml replaced the base tag with <base href="/BlazorApp1/" /> 2) in Startup.cs added app.UsePathBase("/BlazorApp1") 3) in web.config, changed the hostingModel to outofprocess and stdoutLogEnabled to true

When navigating to the site I almost always get the "Unhandled Exception Page must be reloaded" message. This is displayed in the browser console: (replaced my site with contoso)

[2020-06-02T18:39:49.445Z] Information: Normalizing '_blazor' to 'http://www.contoso.com/BlazorApp1/_blazor'. blazor.server.js:1:5212
[2020-06-02T18:39:49.936Z] Information: WebSocket connected to ws://www.contoso.com/BlazorApp1/_blazor?id=5yq6pI_jo1ByPZtskEjjmw. blazor.server.js:1:5212
[2020-06-02T18:39:50.132Z] Error: The circuit failed to initialize. blazor.server.js:15:27309
    log http://www.contoso.com/BlazorApp1/_framework/blazor.server.js:15
    C http://www.contoso.com/BlazorApp1/_framework/blazor.server.js:8
    S http://www.contoso.com/BlazorApp1/_framework/blazor.server.js:8
    invokeClientMethod http://www.contoso.com/BlazorApp1/_framework/blazor.server.js:1
    invokeClientMethod .../BlazorApp1/_framework/blazor.server.js:1
    processIncomingData .../BlazorApp1/_framework/blazor.server.js:1
    onreceive .../BlazorApp1/_framework/blazor.server.js:1
    onmessage .../BlazorApp1/_framework/blazor.server.js:1
[2020-06-02T18:39:50.141Z] Information: Connection disconnected. blazor.server.js:1:5212
Error: Invocation canceled due to the underlying connection being closed. blazor.server.js:1:20001

I can't find any other clues about what's happening. There are no exceptions shown in the log. Thanks for any help you can offer.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share the server-side logs and the exact repro steps so that we can try to investigate this.

**Comment by dsmolen1** [comment]
The server log only contains the usual info messages:
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://127.0.0.1:25384
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: E:\web\thesmolensc\htdocs\BlazorApp1

The url is www.thesmolens.com/blazorapp1.
The server is at discountasp.net. I think it is IIS 12.
As far as repro, I made the noted changes to the plain app, published to folder, changed the web.config as noted and ftp'd the published files.

**Comment by br0esel** [comment]
I dont know if its the same Problem. But i got the same "Error: The circuit failed to initialize." when i moved the _host.cshtml to another directory.
The fix is in my case was:
 <base href="~/Admin/" /> has to be lowercase.
When i replace it with <base href="~/admin/" /> it just works.

**Comment by dsmolen1** [comment]
br0esel: Thank you! It worked for me when I used all lowercase, but I could not use the tilde. So `<base href="/blazorapp1/" />` worked for me.

**Comment by mkArtakMSFT** [comment]
Glad you've got your issue resolved, @dsmolen1.
@javiercn is the `case sensitivity` by-design?
