### ISSUE TITLE
Loading time of Blazor WASM is extremely slow - some unclear delay in log files

### ISSUE THREAD

**Issue by GalEhrlich** [dotnet/aspnetcore#22496]
### Description

Just a short copy-paste from the server side log files indicating more then 16 seconds delay between Blazor WASM requests upon loading:
2020-06-03 09:10:53.035 +02:00 [INF] Request finished in 173.4402ms 304 application/octet-stream
2020-06-03 09:11:09.692 +02:00 [INF] Request starting HTTP/1.1 GET https://localhost:5001/_framework/_bin/Microsoft.AspNetCore.Http.Connections.Common.dll  

What is happening on the client side that can justify such a delay?
What can be done to optimize it?

### Configuration

* Which version of .NET is the code running on? - 3.1.300
* What OS version, and what distro if applicable? - Windows 10 Enterprise, Version 1909
* What is the architecture (x64, x86, ARM, ARM64)? - x64
* If relevant, what are the specs of the machine? - Intel Core i5-7200U

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we've observed. We will need a minimal repro project to investigate this.
