### ISSUE TITLE
Downloading the file from azure file storage gets hanged in blazor web assembly

### ISSUE THREAD

**Issue by harinichellappa1921** [dotnet/aspnetcore#22509]
### Describe the bug
Trying to download the file from azure file storage in blazor web assembly application. when checking whether cloudFileShare.Exists(), application gets hanged.

### To Reproduce
Code snippet to reproduce the issue.
 string fileReference = "GiantPanda.docx";
        CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(connectionString);
        CloudFileClient fileClient = cloudStorageAccount.CreateCloudFileClient();
        //Get file share
        CloudFileShare cloudFileShare = fileClient.GetShareReference(shareReference);
        if (cloudFileShare.Exists())
        {
            //Get the related directory
            CloudFileDirectory dir = cloudFileShare.GetRootDirectoryReference();
            if (dir.Exists())
            {
                //Get the file reference
                CloudFile file = dir.GetFileReference(fileReference);
                FileStream memoryStream = new FileStream("wwwroot/sample-data/GiantPandasaved.docx", FileMode.OpenOrCreate, FileAccess.ReadWrite);
                //Download file to local disk
                await file.DownloadToStreamAsync(memoryStream);
            }
        }

Microsoft.Azure.Storage.File - 11.1.6
Microsoft.AspNetCore.Components.WebAssembly - 3.2.0-preview2.20160.5

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/58329070/83664831-2df13680-a5e8-11ea-9b1d-3260b859e128.png)

### Further technical details
NET Core SDK (reflecting any global.json):
 Version:   3.1.300

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows

Host (useful for support):

**Comment by mkArtakMSFT** [comment]
@harinichellappa1921 if you switch to the async implementation of the APIs you're using, things may get fixed. Try to use `ExistsAsync()` instead.

**Comment by pakrym** [comment]
I think it's the case of using sync APIs that end up doing sync-over-async because of lack of better alternatives.

**Comment by Oredna** [comment]
ExistsAsync doesn't work in this case. Maybe change in the nuget package?

**Comment by pakrym** [comment]
Why doesn't `ExistsAsync` work? Do you get the same error?

**Comment by pakrym** [comment]
Oh, wait, my bad, you are using version 11 of the package. There is a new set of storage client libraries that do work with blazor, take a look at https://www.nuget.org/packages/Azure.Storage.Blobs

**Comment by Oredna** [comment]
Yes it works for me now, i dont know for @harinichellappa1921. It wasn't Azure.Storage.Files, but Azure.Storage.Files.Shares that did the trick. Thank you.
