### ISSUE TITLE
Error: Server returned handshake error: Handshake was canceled.

### ISSUE THREAD

**Issue by mugnap** [dotnet/aspnetcore#22500]
Hello,

I'm reporting an issue about SignalR Core 3.1. I have developed my web app (ASP.NET CORE) and locally (Visual Studio) everything works. Then I've deployed the web app to IIS (latest version) and everything works, at least on my side.
A user reported me, instead, that when he tries to connect using his Chrome browser latest version (on Windows), the SignalR connection does not get established and instead he gets this error in the browser's console:

Server returned handshake error: Handshake was canceled.

This issue seems very similar (if not the same) to issue #11089, but I don't know how to solve it. I'm attaching the error from the user.
![error](https://user-images.githubusercontent.com/56727454/83654099-e86b4400-a5bc-11ea-9c62-f7dd3f75218a.png)

At first I was thinking it was a server issue, but for me it works and for other users too. Then that user told me he can make it work under Edge and under Chrome on Linux. The issue is only with his Chrome (version 83) on Windows.

I only have one server and no multiple app pools or multiple instances of an app pool. But it does not seem to be a server-side issue, I least I think.

What can we check?
Thanks!

**Comment by BrennanConroy** [comment]
There is a large gap between the negotiate returning and the http connection starting which you can see in the logs between "selecting transport" and "SSE connected to". This will causes issues with the server killing the connection because the client took too long to send the handshake.

Could you share the server logs with us so we can try to see whats going on?

**Comment by mugnap** [comment]
I'm using latest IIS, how can I see server logs? I looked at the link you specified in issue #11089 however it speaks only about IIS Express in Visual Studio, not "real" IIS.

However, I think I've narrowed the problem: since I found on the Internet some issues regarding antivirus conflicts, I asked the user if he had antivirus: yes, he had Kaspersky, I told him to disable it and magically it worked. On the Internet I found similar issues with other antivirus (Bitdefender, AVG) and it seems quite a common issue. Why the antivirus may interfere with SignalR?

A side question: when I was looking to fix the problem server-side (but it turned out to be a client-side issue), I found an article saying that WebSockets are not enabled by default on IIS (https://docs.microsoft.com/en-us/iis/configuration/system.webserver/websocket) I checked my current IIS 10 setup and actually this feature is not enabled, but SignalR works anyway. So the question is: should I really enable WebSockets on my IIS server?
Thanks!

**Comment by mugnap** [comment]
Just a clarification on my last question: actually I noted that, without WebSockets protocol enabled on my IIS, everything was still working with SSE protocol. I installed WebSockets support in IIS and it started using WebSockets protocol. So everything is fine.

The only question still open is: why the antivirus may interfere with SignalR?
Thanks.

**Comment by shirhatti** [comment]
We have no idea if your anitivirus can interfere with websockets. I'd recommend reaching out to your antivirus vendor.
