### ISSUE TITLE
Blazor client-side showcase

### ISSUE THREAD

**Issue by bugproof** [dotnet/aspnetcore#22506]
It would be nice to have list of apps/websites using Blazor in production  (since it was released in may) if there are any.

**Comment by mrpmorris** [comment]
Is there anything on Awesome Blazor that suits your needs?
https://github.com/AdrienTorris/awesome-blazor/blob/master/README.md

**Comment by bugproof** [comment]
@mrpmorris These are only sample apps, I mean something like other js frameworks have, madewithvue, madewithreact, madewithsvelte. That's a big selling point for these frameworks. Maybe if Mixer streaming platform was using Blazor or some real app it would bring more people to learn and use blazor.
