### ISSUE TITLE
How to get Query String/ HTTP request in configure service method in Asp.net Core

### ISSUE THREAD

**Issue by Raja-Ashutosh** [dotnet/aspnetcore#22502]
How to get Query String/ HTTP request in configuring service method in Asp.net Core

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
