### ISSUE TITLE
Razor: With C#, typing a double equal to check if a variable is equal to something, causes razor to corrupt the code

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/aspnetcore#22510]
# Describe the bug
Razor page: with C#, typing a double equal to check if a variable is equal to something, causes razor to corrupt the code, in some pages.

### To Reproduce
In attached sample project, open "Pages\Plans\Index.cshtml". Add the line:
`if (plan ==)`
like in the attached picture.

![Razor - bad C# 1](https://user-images.githubusercontent.com/12361341/83665695-c57b6880-a599-11ea-8413-57a04ce59701.png)
![Razor - bad C# 2](https://user-images.githubusercontent.com/12361341/83665696-c57b6880-a599-11ea-9e86-2edb490369da.png)
[zzTempWeb2.zip](https://github.com/dotnet/aspnetcore/files/4724896/zzTempWeb2.zip)

### Further technical details
- ASP.NET Core version: 3.1
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
    Microsoft Visual Studio Community 2019
    Version 16.6.0
    VisualStudio.16.Release/16.6.0+30114.105
    Microsoft .NET Framework
    Version 4.8.03752

ASP.NET and Web Tools 2019 16.6.936.3669
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services 16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019 16.6.936.3669
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0 16.6.936.3669
Azure App Service Tools v3.0.0

C# Tools 3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear Recent 1.1.1
Clears recent projects and files lists

CSS Tools 2019 1.1.4
Provides additional features to the CSS editor in Visual Studio.

Microsoft Continuous Delivery Tools for Visual Studio 0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers 1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager 5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools 16.0.62004.28040
Microsoft SQL Server Data Tools

TypeScript Tools 16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package 1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview) 1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers 1.0
Visual Studio Tools for Containers

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our efforts in moving our Razor tooling over to an LSP powered model.

This should light up in the .NET 5 time frame

**Comment by Dean-NC** [comment]
@NTaylorMullen Thanks for letting me know. I don't follow the team that closely, so I wasn't aware you are in the process of re-writing the Razor tooling.

**Comment by allisonchou** [comment]
This issue is tagged as being fixed in the new editor, so I'm going to close this out.
If you notice the problem persists in the new editor, please let us know by filing another issue. Thanks!
