### ISSUE TITLE
Blazor Component's ChildContent does not get properly rendered due to asynchrony

### ISSUE THREAD

**Issue by fitdev** [dotnet/aspnetcore#22515]
The issue arises if there is logic (CS code) inside of a component's `ChildContent` (or for that matter any `RenderFragment`-based parameter) that _depends on the code outside of the component being rendered_.

### To Reproduce
Augment the default server-side template with 1 new file `ContainerA.razor` and a modified version of `Index.razor` page as shown:

### ContainerA.razor
```razor
<div>
  <h2>ComponentA[@MyProperty].ChildContent:</h2>
  @ChildContent
</div>

@code{
  [Parameter]
  public RenderFragment ChildContent { get; set; }
  [Parameter]
  public int MyProperty { get; set; } = 1;
}
```

### Index.razor
```razor
@page "/"

@for (int i = 0; i < 5; i++) {
  <ContainerA MyProperty="i">
    @* This line renders just fine and all the time (as expected) *@
    <p>Something outside of conditional</p>
    @if (i < 3) {
      // The line below does NOT EVER render, even though it should render 3 times (when i is 0,1,2)
      <p>Something that should render when i&lt;3</p>
    }
  </ContainerA>
}
```

### Explanation
When examining the generated output I noticed this inside of `BuildRenderTree(RenderTreeBuilder __builder)` for the `Index` page:

```cs
for (i = 0; i < 5; i = j + 1)
	{
		__builder.AddContent(4, "  ");
		__builder.OpenComponent<ContainerA>(5);
		__builder.AddAttribute(6, "MyProperty", RuntimeHelpers.TypeCheck<int>(i));
               // VVV - This is likely why the output is never rendered, since it is called sometime AFTER the main loop exits, hence i is always >4
		__builder.AddAttribute(7, "ChildContent", new RenderFragment(delegate(RenderTreeBuilder __builder2) 
		{
			__builder2.AddMarkupContent(8, "\r\n    ");
			__builder2.AddMarkupContent(9, "<p>Something outside of conditional</p>\r\n");
			bool flag = i < 3;
			if (flag)
			{
				__builder2.AddContent(10, "      ");
				__builder2.AddMarkupContent(11, "<p>Something that should render when i&lt;3</p>\r\n");
			}
			__builder2.AddContent(12, "  ");
		}));
		__builder.CloseComponent();
		__builder.AddMarkupContent(13, "\r\n");
		j = i;
	}
```
It appears that the generated code wraps the ChildContent inside of a delegate which is apparently called out of sync with the main loop during runtime. This results in the `i` being > 4, leading to the conditional inside of the loop to always be false, hence the content inside of conditional is never rendered.

This behavior is however unintuitive. And the scenario with loops or conditionals is quite common, where it is expected that the output will be generated sequentially. So, perhaps this can be somehow addressed.

### Workaround
For now I have found the following ugly workaround for `Page.razor`:
```razor
@page "/"

@{
  RenderFragment Workaround(int i) =>
  @<text>
    <p>Something outside of conditional</p>
    @if (i < 3) {
      <p>Something that should render when i&lt;3</p>
    }
  </text>;
}

@for (int i = 0; i < 5; i++) {
  <ContainerA MyProperty="i" ChildContent="Workaround(i)" />
}
```

As you can see the entirety of the `ChildContent` was removed from nice markup and represented as a parametrized `RenderFragment` that accepts `i` as a parameter. This works, but is really ugly and does not feel natural to use, especially for something more complex than this basic example.

### Further technical details
- ASP.NET Core version: 5.0.100-preview.4.20258.7
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.4.20258.7\

Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7

.NET SDKs installed:
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.4.20258.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS 2019 16.7 Preview 1

**Comment by SteveSandersonMS** [comment]
The issue is in this code:

```razor
@for (int i = 0; i < 5; i++) {
  <ContainerA MyProperty="i">
    (Making use of @i here)
  </ContainerA>
}
```

I know it's not obvious from the syntax alone, but everything inside the `<ContainerA>` gets compiled as a lambda. So it's equivalent to the following regular `.cs` code:

```cs
for (int i = 0; i < 5; i++)
{
    someListOfLambdas.Add(() => Console.WriteLine("The value is " + i));
}

foreach (var lambda in someListOfLambdas)
{
    lambda();
}
```

This will print out:

```
The value is 5
The value is 5
The value is 5
The value is 5
The value is 5
```

... because the variable `i` has taken the value 5 by the time the lambdas are executed. The equivalent thing happens too in your Razor code: by the time `<ContainerA>` renders its own child content, your `i` variable is 5, and hence the `i < 3` check will always give `false`.

The solution is to have a different variable inside the loop:

```
@for (int i = 0; i < 5; i++) {
  var copyOfI = i;
  <ContainerA MyProperty="i">
    (Making use of @copyOfI here)
  </ContainerA>
}
```

This captures a different variable for each iteration, so it never gets overwritten and will behave as you want.

I know this is somewhat unexpected if you didn't know it's compiled as a lambda, or if you were unaware of C#'s rules for how variables are hoisted into lambdas, but hopefully now you know you'll be able to avoid any issues with it!

For clarification, I don't think this is something we have any way of changing in Razor itself, since it's a native behavior of C# itself.

**Comment by fitdev** [comment]
@SteveSandersonMS Thank you very much for you timely and detailed explanation and suggested solution! I did not quite think about capturing the variable as you suggest, but it makes sense now.

The only issue you can perhaps address somehow is surfacing this behavior to developers. For example: provide some hints in the editor via analyzers, and/or notes in the docs about such a behavior. Because were the markup to contain static html instead, it would work properly; and it is only because of the way components are rendered (via lambdas as you said) that it does not work as expected.

On a side note, is there a way, perhaps via a design-time-only wrapper tag / syntax, to tell the Razor compiler that it should compile the code inside it without lambdas, so that this issue is avoided? Or perhaps this can be controlled via per-file option added as one of directives or something similar.

Perhaps such an approach may not work for Server / ServerPrerendered rendering, but for the moment I am using Static rendering and with it this would have worked perfectly since once rendered sent content is never changing.
