### ISSUE TITLE
Blazor WebAssembly Unauthorized on controller on hosted webpage with custom domain

### ISSUE THREAD

**Issue by RJGJanssen** [dotnet/aspnetcore#22516]
Hi All,

I'm experiencing issues with a deployed default Blazor WebAssembly project.
I want to use the default project as a startup for the development of the App Service.

Steps taken so far:
- Created default project
- Updated some default styling
- Setup CI / CD
- Setup Publish settings with database updates etc.
- Configured Azure App Service,
- Configured App Service Certificate
- Configured Azure Key Vault with certificate for using the signingCredential for IdentityServer.

So far so good, i've published the website under https://{appname}.azurewebsites.net/
Login works correct and also the FetchData page can be loaded. No problem at all.

But when i visit the website with the configured custom domains (secured with the App Service Certificate) at https://www.{appname}.nl and https://{appname}.nl at first the login works, so that's fine, but when i click the FetchData page and make the call to the WeatherForecastController it's returning the following error message in the DevTools monitor. FYI: The authorization header is sent to the controller containing the Bearer token. This one is received from the previous connect/token and connect/userinfo call. I'm not sure how to solve this, probably someone can help me out with this.

### Exceptions
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Response status code does not indicate success: 401 (Unauthorized).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode () <0x2435df8 + 0x00052> in <filename unknown>:0 
  at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T] (System.Threading.Tasks.Task`1[TResult] taskResponse, System.Text.Json.JsonSerializerOptions options, System.Threading.CancellationToken cancellationToken) <0x2334630 + 0x0012a> in <filename unknown>:0 
  at DeFieneAos.Client.Pages.FetchData.OnInitializedAsync () <0x22e1648 + 0x000ee> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x1f59658 + 0x00154> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x212e760 + 0x000ca> in <filename unknown>:0

**Comment by Tratcher** [comment]
Check the response www-authenticate header, it may have details about the auth failure. I just saw a similar case where the response header looked like this:

WWW-Authenticate: Bearer error="invalid_token", error_description="The issuer 'https://{custom.domain}' is invalid".
 
IdentityServer is set up to issue tokens for https://{custom.domain} but the API is setup to validate tokens using the default app service host.
https://identityserver4.readthedocs.io/en/latest/reference/options.html
https://stackoverflow.com/questions/45581536/can-we-set-a-static-issuer-in-identity-server-4

**Comment by RJGJanssen** [comment]
Hi Tratcher,

Thanks for the reply! I can find indeed that error message, but unfortunately the replies on that thread didn't bring success yet. I've added all 3 endpoints as ValidIssuer in the AddJwtBearer() option in the startup.cs but no success yet. 

It should be something in my configuration i think.

**Comment by spapaseit** [comment]
Hi @RJGJanssen, did you ever figure out what your issue was?

**Comment by xz013** [comment]
any solve ! i have same
