### ISSUE TITLE
Blazor WASM debugging in VSC unable to open browser

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#22527]
### Describe the bug

Edge doesn't open for WASM debugging in VSC.

### To Reproduce

Stock WASM app created from the 3.2 template and configured for Edge ...

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "browser": "edge"
        }
    ]
}
```

### Exception

![image](https://user-images.githubusercontent.com/1622880/83702141-68030e00-a5d1-11ea-83e5-93aba8b9ef09.png)

### Additional note

The error dialog suggests setting the runtime executable for Edge (`runtimeExecutable`), but I don't think that's possible (not without hacks perhaps). Edge docs don't reveal much info about how Edge is launched, and they certainly they don't speak to an executable that does it. Research seemed to indicate that Edge doesn't launch via an executable.

### Further technical details

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### VS Code

Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

### JavaScript Debugger (Nightly)

Version: 2020.6.317

### Microsoft Edge

Version: 44.18362.449.0

cc: @captainsafia

**Comment by captainsafia** [comment]
> The error dialog suggests setting the runtime executable for Edge (runtimeExecutable), but I don't think that's possible (not without hacks perhaps). 

The error dialog is coming up from VS Code's JS debugger.

I just gave this a go on a Windows VM and I was able to get the Edge browser to launch so this isn't a generic issue.

I suspect that the JS debugger is looking for Edge in a certain location and unable to find it there based on the particular installation on your machine.

**Comment by guardrex** [comment]
:smile: I'm glad u asked ...

> C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe

... **_and I found my EXE!_** :tada:

<img width="346" alt="Capture" src="https://user-images.githubusercontent.com/1622880/83785219-9bd44700-a656-11ea-9269-11413ab020a2.PNG">


That might permit me to enhance the Blazor security troubleshooting steps.

**Comment by captainsafia** [comment]
Yep! That would be it. The JS debugger looks for an edge installation on Windows in the local program data directory and under program files on Windows.

On macOS, it looks under the `/Applications` and `/Contents/Mac OS` directories for the executable.

**Comment by guardrex** [comment]
Are you saying that is or is not the right spot for the latest version of Windows 10?

Should I be taking steps to reinstall it ... or move it. 😨 ... *which is a little scary.*

**Comment by guardrex** [comment]
Done ...

*Hummmmm* 🤔 ... I didn't know that I wasn't on a stable release ...

<img width="422" alt="Capture" src="https://user-images.githubusercontent.com/1622880/83787931-24a0b200-a65a-11ea-83fa-f06595e23bff.PNG">

I guess I can try setting the path explicitly in *launch.json* and see what happens.

**Comment by guardrex** [comment]
It doesn't like the syntax in the file, and it doesn't work ...

<img width="777" alt="Capture" src="https://user-images.githubusercontent.com/1622880/83788481-de981e00-a65a-11ea-833a-6d21000568dd.PNG">

**Comment by mkArtakMSFT** [comment]
This issue was moved to microsoft/vscode-js-debug#504
