### ISSUE TITLE
Unable to Get Status Code for Unauthorized request in @microsoft/signalr

### ISSUE THREAD

**Issue by mars-boy** [dotnet/aspnetcore#22538]
Hi greetings,

I am able currently using JWT authentiction for signalr and It was all working fine. In Js client i'm unable to get status code for UnAuthorized request to send user to login page. My current code is as follows

```
services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(x =>
            {
                x.RequireHttpsMetadata = false;
                x.SaveToken = false;
                x.Events = new JwtBearerEvents
                {
                    OnMessageReceived = context =>
                    {
                        var accessToken = context.Request.Query["access_token"];

                        // If the request is for our hub...
                        var path = context.HttpContext.Request.Path;
                        if (!string.IsNullOrEmpty(accessToken) &&
                            (path.StartsWithSegments("/hubpoint")))
                        {
                            // Read the token out of the query string
                            context.Token = accessToken;
                        }
                        return Task.CompletedTask;
                    }
                };
                x.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    ValidateLifetime = true,
                    LifetimeValidator = (DateTime? notBefore, DateTime? expires, SecurityToken securityToken,
                                     TokenValidationParameters validationParameters) =>
                    {
                        return notBefore <= DateTime.UtcNow &&
                               expires >= DateTime.UtcNow;
                    },
                    ValidateIssuer = false,
                    ValidateAudience = false
                };
            });
```

```
[Authorize]
    public class AdminHub : Hub
```

Js Code.
---------

```
this.hubConnection = new signalR.HubConnectionBuilder()
      .withUrl(this.connectionURL+'?'+params, 
      { 
        skipNegotiation:true,
        transport: signalR.HttpTransportType.WebSockets,
        accessTokenFactory: () => token
      })
      .withAutomaticReconnect()
      .configureLogging(signalR.LogLevel.Error)
      .build();
```

```
this.hubConnection.start().then(() => {
      if (this.hubConnection.state == ConnectionState.Connected) {
        this.currentState = ConnectionState.Connected;
        this.connectionReady();
      }
    }).catch((err: HttpErrorResponse) => {
      debugger;
      console.log('error is ', err)
    });
```

The error that im catching currently is not giving any detailed information like errorcode its giving generic message like 'Failed to start connection. There was error with transport'

Flow is good till life time of token. Things getting worse when it got expired.

Thanks or your time. 
Any Suggestions.

**Comment by mars-boy** [comment]
Hi Any update please

**Comment by shirhatti** [comment]
@mars-boy Can you share a repro with your client code?

**Comment by halter73** [comment]
Unfortunately, the WebSocket API doesn't provide information about the HTTP status code. The spec forbids it.

> User agents must not convey any failure information to scripts in a way that would allow a script to distinguish the following situations:
> 
> - A server whose host name could not be resolved.
> - A server to which packets could not successfully be routed.
> - A server that refused the connection on the specified port.
> - A server that failed to correctly perform a TLS handshake (e.g., the server certificate can't be verified).
> - **A server that did not complete the opening handshake (e.g. because it was not a WebSocket server).**
> - A WebSocket server that sent a correct opening handshake, but that specified options that caused the client to drop the connection (e.g. the server specified a subprotocol that the client did not offer).
> - A WebSocket server that abruptly closed the connection after successfully completing the opening handshake.
> - In all of these cases, the the WebSocket connection close code would be 1006, as required by the WebSocket Protocol specification. [WSP]
> 
> Allowing a script to distinguish these cases would allow a script to probe the user's local network in preparation for an attack.

https://www.w3.org/TR/websockets/#feedback-from-the-protocol
