### ISSUE TITLE
Redis Session State in Net Core 2.2 deployed at AWS fails

### ISSUE THREAD

**Issue by ronaldo-o-reis** [dotnet/aspnetcore#22536]
A little context:

.Net Core 2.2 application Deployed at AWS using IIS

Have implemented REDIS according the aspnet doc [https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2] however we get the following exception:

`
    Session cache read exception, Key:65871781-f1f5-71d3-d4e8-a7e031f403eb System.TypeLoadException: Could not load type 'DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory' from assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'. at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server)
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54 at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1134 at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members) at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefresh(String key, Boolean getData) at Microsoft.AspNetCore.Session.DistributedSession.Load() fail: Microsoft.AspNetCore.Session.DistributedSession[6]
`

The problem occurs only at Session State cache while regular data has been cached successfully...

Any ideas?

**Comment by shirhatti** [comment]
As an FYI, .NET Core 2.2 is out-of-support- https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by BrennanConroy** [comment]
What version of Redis does `DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory` bring in?

In 2.2 there are two caching packages for the 2 versions of StackExchange.Redis, https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/ and https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis so you should check which one you are using and that the same StackExchange.Redis version is used by all dependencies in your project.

**Comment by ronaldo-o-reis** [comment]
Regrettable situation. 

Most people cannot just change the production application to version 3 out of the blue...

**Comment by ronaldo-o-reis** [comment]
> What version of Redis does `DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory` bring in?
> 
> In 2.2 there are two caching packages for the 2 versions of StackExchange.Redis, https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/ and https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis so you should check which one you are using and that the same StackExchange.Redis version is used by all dependencies in your project.

Have searched for "DotNetAgent.Instrumenter.Factories.Web.External.RedisTrackerFactory" and cannot find anything. This package seams to not exist.

The package I'm using is "Microsoft.Extensions.Caching.StackExchangeRedis"

**Comment by BrennanConroy** [comment]
Could you share your project.assets.json file?

Note: same issue https://github.com/StackExchange/StackExchange.Redis/issues/1480

**Comment by ronaldo-o-reis** [comment]
> Could you share your project.assets.json file?
> 
> Note: same issue [StackExchange/StackExchange.Redis#1480](https://github.com/StackExchange/StackExchange.Redis/issues/1480)

Hi. It is pretty big file (14,000 lines)...
