### ISSUE TITLE
How to inspect endpoint route patterns after parameter transformer applied?

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/aspnetcore#22545]
Hi. I am trying to write middleware that examines requests that have not been handled and attempts to redirect them. Specifically, it needs to check if adding a culture code prefix to the requested path would result in a matching endpoint.

To do so, I get a list of `RouteEndpoints` from the `EndpointDataSource`:

    var dataSource = context.RequestServices.GetRequiredService<EndpointDataSource>();
    var routeEndpoints = dataSource.Endpoints.Cast<RouteEndpoint>().ToList();

I then look for matches for the prefixed path:

    foreach (var ep in routeEndpoints)
    {
        var template = TemplateParser.Parse(ep.RoutePattern.RawText);
        var matcher = new TemplateMatcher(template, new RouteValueDictionary());
    
        if (matcher.TryMatch(prefixedPath, routeValues))
        {
            matches.Add((template, ep));
        }
    }
    
    var match = matches.OrderBy(c => RoutePrecedence.ComputeInbound(c.Template)).FirstOrDefault();

However, I have a `PageRouteTransformerConvention` registered with a `IOutboundParameterTransformer` to slugify route segments. The `RoutePattern` for the Razor Page route endpoints retrieved in this way does not reflect the transformation, so matches fail for these endpoints.

For example, a route pattern of `{lang:lang_code}/Folder/SomePage` is returned, whereas after the transformer is applied, this would be `{lang:lang_code}/folder/some-page`. Therefore, an attempt to match a failed request for `/folder/some-page` with a prefixed path of `/en-gb/folder/some-page` fails.

Is there a way to obtain `RouteEndpoints` where page route conventions have been previously applied?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@javiercn, @JamesNK do you have any recommendation regarding this? Thanks

**Comment by frankbuckley** [comment]
It seems the problem arises from a `IPageRouteModelConvention` which prefixes `AttributeRouteModel` templates.

This was implemented as per the [documentation here](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-3.1#model-conventions). However, it turns out you also need to add `PageRouteMetadata` to new selectors with a page route adjusted to reflect the changed template in the `AttributeRouteModel` (or amend the metadata of any edited existing selectors).

If implemented as per the documentation, and **without adding** a `PageRouteTransformerConvention`, then things work as expected:

![image](https://user-images.githubusercontent.com/5655810/83899957-30bb6b00-a751-11ea-8950-29eb5126ee66.png)

With the implementation remaining the same but with a `PageRouteTransformerConvention` added, then the prefixed route templates are overwritten:

![image](https://user-images.githubusercontent.com/5655810/83900155-86901300-a751-11ea-989a-b29479b5fe6d.png)

Updating the `PageRouteMetadata` seems to be required to fix this:

    var pageRouteMetadata = selector.EndpointMetadata.OfType<PageRouteMetadata>().SingleOrDefault();

    if (!(pageRouteMetadata is null))
    {
        selector.EndpointMetadata.Remove(pageRouteMetadata);

        var newPageRouteMetadata = new PageRouteMetadata("/" + _prefix + pageRouteMetadata.PageRoute, null);
        selector.EndpointMetadata.Add(newPageRouteMetadata);
    }

![image](https://user-images.githubusercontent.com/5655810/83901147-32d1f980-a752-11ea-979f-1241ccce29e3.png)

Am I missing something somewhere? If not, perhaps the documentation should be updated?
