### ISSUE TITLE
Unable to evaluate in Blazor Wasm

### ISSUE THREAD

**Issue by srudin** [dotnet/aspnetcore#22569]
### Describe the bug
Debugging generally works, my breakpoints are hit. However sometimes I cannot display all or some of the variables: The locals window, quick watch etc. simply display "Unable to evaluate" for all variables, objects etc. Therefore expanding an object (by clicking on the +) also doesn't work. Debugging without seeing any values is of course not very helpful...

I am using the newest releases of both VS2019 (16.6.1) and the .NET SDK (3.1.300). Is there something else I need to do?

### To Reproduce
Create a new client side Blazor app, set a breakpoint, debug.

@guardrex

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
If you would have to categorize, which are the most common things / expressions you'd expect to be evaluated which currently don't?

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19942
