### ISSUE TITLE
Renaming .dll to .bin in a Blazor Web Assembly

### ISSUE THREAD

**Issue by ricardocarpio** [dotnet/aspnetcore#22567]
I will appreciate any help for me to fix this problem.

Renaming .ddl to .bin in a Blazor Web Assembly resulted in an integriry error and the blazor.boot.json is blocked.  If I do not rename the .dll to .bin, it worked.  Below is what appears on the service worker application trace

Ricardo

![RenameDllToBin](https://user-images.githubusercontent.com/10228322/83844554-8f311b00-a74a-11ea-8e41-0a6942a050c6.png)

**Comment by ricardocarpio** [comment]
Hi Safia,
Please tell me if you will need some more information from me.
Just tried so many combinations.  

Regards,
Ricardo

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will adjust the documentation to fix the missing step in the script provided here: https://docs.microsoft.com/en-ca/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#change-the-filename-extension-of-dll-files

**Comment by mrpmorris** [comment]
@mkArtakMSFT what is the missing step?

**Comment by ricardocarpio** [comment]
Thank you, guys for the effort. I will check the script from time to time.

Regards,
Ricardo

**Comment by mihaimyh** [comment]
> If I remember correctly it was about adjusting the integrity hashes after the renames. @SteveSandersonMS or @javiercn can you please confirm?

@mkArtakMSFT How this can be done?

**Comment by ricardocarpio** [comment]
Hi Steve,

Yes,  I have the same concern as Artak.   How do I do it?  

Thanks,
Ricardo

**Comment by smartprogrammer93** [comment]
Title has a typo :p

**Comment by andresgbertola** [comment]
Hello @javiercn and @mkArtakMSFT,
I am having the same problem.
To test it, I created a new Blazor PWA WebAssembly (last version default template) project and deployed it in two different servers.
Installed the last .NET Core Hosting Bundle.

After publising it, I ran the script to rename dll files in the docs:

`dir .\_framework\_bin | rename-item -NewName { $_.name -replace ".dll\b",".bin" }
((Get-Content .\_framework\blazor.boot.json -Raw) -replace '.dll"','.bin"') | Set-Content .\_framework\blazor.boot.json`

And the serviceworker renaming code too:
`((Get-Content .\service-worker-assets.js -Raw) -replace '.dll"','.bin"') | Set-Content .\service-worker-assets.js
`

Then I deleted the compressed files:
```
wwwroot\service-worker-assets.js.br
wwwroot\service-worker-assets.js.gz
wwwroot\_framework\blazor.boot.json.br
wwwroot\_framework\blazor.boot.json.gz
```
But I am still getting the same error:

![wasm](https://user-images.githubusercontent.com/50872716/88389484-fbb0b980-cd8c-11ea-8214-af33cf71cea5.jpg)

As @ricardocarpio asked, what is the missing step? How do I adjust the integrity hashes?
I cannot find this of this in the docs.

Thanks

**Comment by Code-DJ** [comment]
Assuming Foo.dll and macOS, brotli installed using homebrew, you need to do the following:
1. Rename Foo.dll to Foo.bin
2. Recreate the gzip and brotli files using:
```
gzip -9kf Foo.bin
brotli -f Foo.bin -o Foo.bin.br
```
3. Now you need to recalculate the integrity hash using the following (assuming powershell):
```
$hasher = [System.Security.Cryptography.HashAlgorithm]::Create('sha256')
$hash = [Convert]::ToBase64String($hasher.ComputeHash([System.IO.File]::ReadAllBytes('{PATH TO FOLDER}/Foo.bin')))
$hash
```
4. Change the integrity (hash) value for Foo.dll in blazor.boot.json file as well as change Foo.dll to Foo.bin.
5. Finally, recreate the zip and brotli files for blazor.boot.json using:
```
gzip -9kf blazor.boot.json
brotli -f blazor.boot.json -o blazor.boot.json.br
```
6. Deploy and try it.

**Comment by javiercn** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/20852 There is a script here that will point out issues in the app when the modifications are done partially and will serve to validate the output of the modifications.
