### ISSUE TITLE
Documentation for component rendering fundamentals

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#22576]
This should cover when and why component (re)rendering will be called.

**Comment by guardrex** [comment]
Perhaps, this issue ties most directly to the open docs issue ...

**StateHasChanged Explained (vs base.InvokeAsync(StateHasChanged)**
https://github.com/dotnet/AspNetCore.Docs/issues/16119

... we could change the title of that docs issue to *Component rendering fundamentals*. The subject matter that Kevin Gates is asking about there seems like it would fall right in under this.

**Comment by SteveSandersonMS** [comment]
Written proposed content at https://github.com/dotnet/AspNetCore.Docs/issues/16119#issuecomment-758657222. Over to @guardrex for an opinion on where it should go.

**Comment by SteveSandersonMS** [comment]
Counting this issue as done and closing, since I've prepared [some content](https://github.com/dotnet/AspNetCore.Docs/issues/16119#issuecomment-758659807) and @guardrex is taking over to merge it into the docs (thanks!)
