### ISSUE TITLE
Property Declaration Type and Variable Not Colorized Appropriately

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#22577]
### Razor
![image](https://user-images.githubusercontent.com/14852843/83903434-fb902800-a712-11ea-8f14-457fe653bdf3.png)

### C#
![image](https://user-images.githubusercontent.com/14852843/83903528-2a0e0300-a713-11ea-9a2d-f6a5057af7fa.png)

Interestingly GitHub flavored markdown doesn't color it either 🤔 
```csharp
@code {    
    public string IncrementByStrProp { get; set; }
    public int IncrementByIntProp { get; set; }
    public string IncrementByStr = "bar";
    public int IncrementByInt = 0;
}
```

**Comment by ryanbrandenburg** [comment]
This is fixed by C# Semantic colorization. Still broken for VSCode, but it will be fixed when we move it to C# Semantic Colors, and there's already an issue tracking that.
