### ISSUE TITLE
Crash while debugging a Blazor page in a large project after hanging for a very long time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22584]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1064741/crash-while-debugging-a-blazor-page-in-a-large-pro.html)._

---
Crash while debugging a Blazor page in a large project after hanging for a very long time

Crash dump has been attached

---
#### Visual Studio Feedback System on 6/5/2020, 02:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#19924
