### ISSUE TITLE
Another crash dump from crash while working on a solution with a large Blazor project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22582]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1065590/another-crash-dump-from-crash-while-working-on-a-s.html)._

---
Another crash dump working on a solution with a large Blazor project

---
#### Visual Studio Feedback System on 6/4/2020, 10:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/22582
