### ISSUE TITLE
Add support for launching DebugProxy from `blazorwasm` debug type in VS Code

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#22587]
To support debugging in WSL and Codespaces, we need to move the logic that launches the DebugProxy in Blazor from our DevServer logic to the `blazorwasm` debug type.

To fully support remote debugging, there is some work required to add support for using a WebSocket-based transport when communicating with the browser launched over the users machine. This will be tracked in a separate issue at https://github.com/dotnet/aspnetcore/issues/29657.

**Comment by mkArtakMSFT** [comment]
@captainsafia moving these debugging related issues to RC1 but we need to re-evaluate together which ones will make it in.

**Comment by MarkusRodler** [comment]
It would be nice to mention this constraint in the docs: https://docs.microsoft.com/de-de/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio-code

**Comment by captainsafia** [comment]
cc: @guardrex Let's add a quick note in the Blazor WASM debugging docs that it currently only works for local scenarios.
