### ISSUE TITLE
Still, the Razor editing experience in the Blazor template is too slow.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1064747/여전이-blazor-템플릿의-razor-편집환경이-너.html)._

---
I installed the latest 16.70 Prev2, but it's still hell-like. 
InteliSense reactivity may be slow.
Typing delay is the problem.
When a letter is struck, there may be a delay of approximately 0.5 seconds.
Is this just me?

---
#### Visual Studio Feedback System on 6/4/2020, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Duplicate of: https://github.com/dotnet/aspnetcore/issues/22276
