### ISSUE TITLE
Change notifications not working in blazor

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22583]
I have a control that accepts method name.
Then I use reflection to run that command.
When I do it that way, then if anything changes while method is running, does not get updated unless I call StateHasChanged.

example is I have code like this
_execute.Invoke(_model, null);

_execute represents methodinfo.  The model is the model that holds the method.  I found out the method runs.  However, any data that changes is not being reflected in blazor.  Is there a workaround for it?  Because often times, its more flexible if you can send in a name and it can invoke that method so the control does not need to use event callbacks or even know which view model is being used but just an object.

**Comment by musictopia2** [comment]
Just wanted to give a little more.  I even tried to convert to a delegate and even change my process to send in a delegate and its still the same issue.  There are many cases where it would be more flexible for a control to not know anything about an underlying object being sent so its more flexible.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please share more details about what you're trying to do?
