### ISSUE TITLE
OpenDocument not called for newly added components

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#22594]
The [`DefaultRazorProjectService.OpenDocument`](https://github.com/dotnet/aspnetcore-tooling/blob/4cfabbc2072339506349dbaae8e6ba17f3b261a8/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs#L136) should be called and [subsequently generate the C# document](https://github.com/dotnet/aspnetcore-tooling/blob/4cfabbc2072339506349dbaae8e6ba17f3b261a8/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs#L163) when a new component is added through the triggering of the [`RazorDocumentSynchronizationEndpoint` Handler](https://github.com/dotnet/aspnetcore-tooling/blob/db430d646afb0f368748c8973b69343153e36fbf/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs#L91-L104). However, this call is never made and subsequently newly created components aren't generated until they're closed.

**Comment by TanayParikh** [comment]
Discussed with Taylor offline, appears to be an external issue in which the VS document creation isn't triggering the appropriate event. Reaching out for more details.

Thanks @NTaylorMullen!

**Comment by TanayParikh** [comment]
[VSTS Tracking issue for reference.](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1137043)

**Comment by NTaylorMullen** [comment]
@TanayParikh I believe this is fixed in VSMaster. Could you verify and do the needful?

**Comment by TanayParikh** [comment]
Verified when a new component is added, the [`DefaultRazorProjectService.OpenDocument`](https://github.com/dotnet/aspnetcore-tooling/blob/4cfabbc2072339506349dbaae8e6ba17f3b261a8/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs#L136) is called. 

Also verified newly added components have colorization + document is generated so completions work.

**Comment by TanayParikh** [comment]
Not working and getting:
```
System.InvalidOperationException: serverCodeProjectionBuffer is null.   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.ServerContainedLanguageSupport.ThrowInvalidOperationExceptionIfNull(Object o, String name)   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.ServerContainedLanguageSupport.EnsureBufferCoordinator()   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.ServerContainedLanguageSupport.InitContainedLanguage(IVsContainedLanguageFactory factory, IVsHierarchy containedLanguageHierarchy, UInt32 containedLanguageItemId, String containedLanguageFileExtension)   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.LiveShareServerContainedLanguageSupport.InitContainedLanguage()   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.LiveShareServerContainedLanguageSupport..ctor(ITextBuffer textBuffer, ITextView textView, IVsEditorAdaptersFactoryService adapterService)   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.ServerContainedLanguageSupport.EnsureConnected(ITextView textView, ITextBuffer textBuffer, IVsEditorAdaptersFactoryService adapterService, IProjectExportProvider webProjectExportProvider)   at Microsoft.WebTools.Languages.Html.VS.ContainedLanguage.Server.ServerContainedLanguageSupportViewTracker.OnTextViewConnected(ITextView textView, ITextBuffer textBuffer)   at Microsoft.WebTools.Languages.Shared.Editor.Controller.TextViewConnectionListener.<>c__DisplayClass28_1.<OnTextViewConnected>b__0()   at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action) --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--

```
