### ISSUE TITLE
MapBlazorHub() throws an InvalidOperationException if ASPNETCORE_DETAILEDERRORS is set to "1"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22592]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1057605/mapblazorhub-throws-an-invalidoperationexception-i.html)._

---
If the environment variable ASPNETCORE_DETAILEDERRORS is set to "1",  a call to _endpoints. MapRazorHub()_ throws the exception: _InvalidOperationException: Failed to convert configuration value at 'detailedErrors' to type 'System.Boolean'._

According to [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1#detailed-errors):

>Detailed Errors
>Determines if detailed errors should be captured.
>
>Key: detailedErrors
>Type: bool (true or 1)
>Default: false
>Set using: UseSetting
>Environment variable: ASPNETCORE_DETAILEDERRORS 

A value of "1" should be valid. 

If the environment variable ASPNETCORE_DETAILEDERRORS is set to "true", a call to *endpoints. MapRazorHub()* works as expected.

---
#### Visual Studio Feedback System on 6/1/2020, 01:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the next milestone. You can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).
