### ISSUE TITLE
Improvement To EventCallBack Structure

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22599]
One change that would be simple and powerful to allow more scenarios would be to make the Delegate public even though readonly instead of internal.
One good case where i need this is a situation where if I have to accomplish what i want with eventcallbacks instead of action delegates then i need to know which methodinfo it is because i have function that can look for whether the method can run by looking for the words Can and the methodName.  That only works if I can at least have readonly access to the delegate.  Or maybe at least give access to the MethodInfo it corresponds to.  The change should be as easy as changing from internal to public.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do / expose through the API.
