### ISSUE TITLE
Blazor Starter App doesn't display correctly in Microsoft Edge

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1059151/blazor-starter-app-doesnt-display-correctly-in-mic.html)._

---
On Microsoft Edge the navbar displays horizontally and there is no about link.  App displays correctly in Chrome and Firefox. It looks as though Edge is being treated like a mobile target with horizontal navbar accross the top and no About Link.  BTW Where does the about link go in mobile form factors?

---
#### Visual Studio Feedback System on 6/1/2020, 11:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What version of Edge are you targeting?

**Comment by jose-applesox** [comment]
My version of Edge is
Version 83.0.478.45 (Official build) (64-bit)

**Comment by mkArtakMSFT** [comment]
Thanks for the info. Given that this is not something we can reproduce nor we have heard similar feedback, we believe you may have switched to the mobile mode for the page.
Try to switching to the desktop mode by following the instructions provided here: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/#simulate-a-mobile-viewport
