### ISSUE TITLE
Problem with async calls to Blazor Server service

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22593]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1056622/problem-with-async-calls-to-blazor-server-service.html)._

---
<p>I am developing a Blazor Service page that retrieves a collection of entites from a database via a service.  All the samples show the calls to the service and the database as async.  This always results in a null collection.  When the calls are synchronous it works. (See diagram below.)  Am I missing something?</p> <p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/138777-async-svc-call-10.jpg"> Image:138777-async-svc-call-10.jpg</a></p><p></p>

---
#### Visual Studio Feedback System on 6/1/2020, 00:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-blazor** tag.
