### ISSUE TITLE
.Net CORE Internal Error (80131506) on ASP.NET Core Application Shutdown

### ISSUE THREAD

**Issue by musmuris** [dotnet/aspnetcore#22600]
We're running some ASP.NET Core apps and when IIS shuts them down they generate an error in Event Viewer

From our app log (ASP.Net core log)
```
2020-06-05 16:01:50.202 +00:00 [INF] Request finished in 127.8305ms 200 text/html
2020-06-05 16:22:48.329 +00:00 [INF] Application is shutting down...
```

Then in Event viewer

```
Information	05/06/2020 16:20:00	.NET Runtime	1022	None
Information	05/06/2020 16:22:49	IIS AspNetCore Module V2	1033	None
Information	05/06/2020 16:22:50	Windows Error Reporting	1001	None
Error	05/06/2020 16:22:50	VsJITDebugger	4096	None
Error	05/06/2020 16:22:50	.NET Runtime	1023	None
Error	05/06/2020 16:22:50	Application Error	1000	(100)
```

Error details:

```
Application: w3wp.exe
CoreCLR Version: 4.700.20.20201
.NET Core Version: 3.1.4
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC586B74D8 (00007FFC583F0000) with exit code 80131506.
```

```Faulting application name: w3wp.exe, version: 8.5.9600.16384, time stamp: 0x5215df96
Faulting module name: coreclr.dll, version: 4.700.20.20201, time stamp: 0x5e867108
Exception code: 0xc0000005
Fault offset: 0x00000000002c74d8
Faulting process id: 0xbc8
Faulting application start time: 0x01d63b529e488645
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.4\coreclr.dll
Report Id: cc5456d1-a748-11ea-80e1-509a4c5f1c8a
Faulting package full name: 
Faulting package-relative application ID: 
```

We have this on 2 different apps, each time I can correlate the shutdown to an entry in the event viewer.
This is on Windows Server 2012 R2 - not sure what to look for next?

**Comment by markdavieswlt** [comment]
We also have this error, but under a different circumstance.

We have moved from webforms to dotnet core, and the new app slows down after a little while, then grinds to a halt.
IIS obviously tries to recover, and we get this error when IIS tries to recover.
I'm not sure if this error is a side effect or cause of our slow performance.

**Comment by BrennanConroy** [comment]
Are you able to consistently repro this?

Can you gather server logs and IIS logs? https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1

If you can repro this locally, would you be willing to set up [WER](https://docs.microsoft.com/en-us/windows/win32/wer/windows-error-reporting) and provide the dump from the process?

**Comment by musmuris** [comment]
@BrennanConroy  Thanks. Yes it happens every time. Go to a web page, then wait for it to timeout and crash.  I can get the logs for you. As for WER it's on a production server that it happens - but I can probably get a dump out of hours - do I just need to set these https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps ?

**Comment by BrennanConroy** [comment]
Yep, those are the settings :+1:

**Comment by musmuris** [comment]
I got a crash dump mid-week and loaded into WinDbg and it looked like it was coming from a profiler. 

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffc63f774d8 (coreclr!ProfileEnter+0x00000000000000f8)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000001
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 00000000000000e8
Attempt to read from address 00000000000000e8
```

We have a 3rd party monitoring tool which hooks into IIS .NET and .NET Core to get details out.  I thought I had disabled it before but it still had hooks in as I've just removed it and rebooted the machine  and now it doesn't happen any more. i.e. the Apps shutdown without an error or crash.

Going full circle and re-installing it causes the crash once again.  I've included the analysis text from WinDbg below in case there's anything coreclr can do to mitigate it - but will submit the bug to the 3rd party supplier.

[windbg.txt](https://github.com/dotnet/aspnetcore/files/4774312/windbg.txt)

**Comment by musmuris** [comment]
Apparently their support said their current profiler doesn't support newer .NET Core versions (they fail to mention this elsewhere...) but they do have a beta update for us. So I guess that solves this one.

**Comment by BrennanConroy** [comment]
Glad you figured it out! We'll close since this is an issue with the 3rd party library.

**Comment by markdavieswlt** [comment]
Which profiler are you using? 
We are using 2 different profilers (on different servers) and have experienced silimar issue after a certain amount of time
