### ISSUE TITLE
Guidance about extending Blazor PWA Service worker with libraries such as WorkBox

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#22607]
In addition to the capabilities already provided by the service worker created/generated by the Blazor Wasm PWA template, I would like to extend my service worker with additional capabilities such as:

1. Caching some of my api responses
2. Using BackGroundSync for Post requests
3. Using different strategies for different types of assets such as StaleWhileRevalidate, NetworkFirst etc.

Ideally, I would like to use [WorkBox ](https://developers.google.com/web/tools/workbox) but at the same time, I still want to take advantage of the default build-time generation of the pre-cache manifest.

Could you please provide some guidance/example on how to incorporate something like WorkBox in the PWA service worker, and yet keep the service worker assets manifest intact, enjoying best of both the worlds :)

**Comment by javiercn** [comment]
@bancroftway thanks for contacting us.

That's exactly why we generate an assets manifest. If you want to use workbox or similar, you can modify your service worker code to use workbox and sill leverage the existing list of assets.

**Comment by pranavkm** [comment]
We discussed this during triage, and don't plan to provide explicit guidance on how to use 3rd party frameworks. If you have specific questions about how Blazor's PWA support would integrate, we might be able to help.
