### ISSUE TITLE
Initialize JS Interop on OnInitialized

### ISSUE THREAD

**Issue by imtrobin** [dotnet/aspnetcore#22617]
I have a JS interop (InvokeVoidAsync), It needs to be initialized properly in MainLayout before other components

I cannot use GetAwaiter ().GetResult () in OnInitialized, and OnInitializedAsync does not await, all components fires their OnInitializedAsync.

It is similar to https://github.com/dotnet/aspnetcore/issues/21854 but this JS interop is not retrieving data, it is to setup.

What's the recommended solution for this situation?

**Comment by mrpmorris** [comment]
What about having your layout not call `@Body` until after the first OnAfterRender?

**Comment by imtrobin** [comment]
The bot has closed this a bit too fast. I put more details here, the problem is two JS interop depends on each other.

https://stackoverflow.com/questions/62294319/blazor-two-js-interop-which-depend-on-each-other
