### ISSUE TITLE
Notifications Not Working in Blazor

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22614]
Here is my sample code;

public string UpdatedValue { get; set; } = "";
        public async Task RunTest()
        {
            UpdatedValue = "Starting;"
            await Task.Delay(20);
            UpdatedValue = "Test 1";
            await Task.Delay(20);
            UpdatedValue = "Test 2";
            await Task.Delay(20);
            UpdatedValue = "Finished";
        }

When I run the method, the only parts that show up on the UI is the Starting and Finishing.
That is wrong.  Since the value is being updated other times during the call, its supposed to rerender even for that and somehow its not.  How do you make it where it can rerender again.
I know I can call StateHasChanged but if a cross platform library is running the code, they are not going to know about it.  Besides, it would be really messy if StateHasChanged has to be called for every little change is done.  The way I would expect it to work is for each step of the process if the value changes, then it would automatically rerender.

**Comment by mrpmorris** [comment]
Blazor has no way of knowing your property value has been changed unless you call StateHasChanged()

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@mrpmorris 's answer is correct. Thanks!
