### ISSUE TITLE
React to EF Core breaking change: HasName -> HasDatabaseName

### ISSUE THREAD

**Issue by smitpatel** [dotnet/aspnetcore#22610]
EF Core obsolete HasName API on IndexBuilder. It should use new API in runtime model. Old Migration.Designer and ModelSnapshot should suppress obsolete warnings. 
As per https://github.com/dotnet/efcore/issues/8703, use migrations & Snapshot should have obsolete already in place.

@AndriySvyryd - Should I put obsolete around the API specifically or just do it in whole file as it is expected in user code?

**Comment by AndriySvyryd** [comment]
Whole file. 612 and 618
