### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by aekkasit114** [dotnet/aspnetcore#22621]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by blowdart** [comment]
This doesn't give us any information at all I'm afraid. Would you like to tell us what problem you're having?

**Comment by Pilchie** [comment]
This is just the template.  Going to go ahead and close. @aekkasit114 feel free to re-open with details.
