### ISSUE TITLE
Adding certain js files causes locals in debugger to not be evaluated

### ISSUE THREAD

**Issue by perilouspete** [dotnet/aspnetcore#22624]
Adding qrcode.js  from https://github.com/mebjas/html5-qrcode and referencing in index.html on Blazor Wasm causes a problem where I cannot inspect anything in debugger the breakpoint is hit but nothing is evaluated

even on the default project only adding that file and referencing qrcode.js causes debugger to become unstable

**Comment by pranavkm** [comment]
This issue was moved to mono/mono#19931
