### ISSUE TITLE
how can I make scrollview without js library?

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#22625]
I want make a scrollview component without js library, but I don't know how to handle dom with c# code, we should make function like **scrollTo**.
Is there any example for me?
thank you.

**Comment by srpeirce** [comment]
I don't think this is possible at the moment.

I might be wrong but I *think* that requires some of the APIs that are not available to webassembly. You may need to use the JS Interop!

>By itself, WebAssembly cannot currently directly access the DOM; it can only call JavaScript, passing in integer and floating point primitive data types. Thus, to access any Web API, WebAssembly needs to call out to JavaScript, which then makes the Web API call. Emscripten therefore creates the HTML and JavaScript glue code needed to achieve this.
https://developer.mozilla.org/en-US/docs/WebAssembly/Concepts

**Comment by srxqds** [comment]
but as this site: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1 said it not recommend that
> The preceding example modifies the Document Object Model (DOM) directly for demonstration purposes only. Directly modifying the DOM with JavaScript isn't recommended in most scenarios because JavaScript can interfere with Blazor's change tracking.

it means it can't handle dom with js in blazor?

**Comment by srpeirce** [comment]
I think that article is referring to manipulation of the DOM, e.g. you shouldn't add/remove/change elements. Some things like scrolling and focus can only be done via js - this should be fine given they have no side effects to the actual rendered HTML.

**Comment by mrpmorris** [comment]
I'm not familiar with it. Can you explain exactly what it is you need to do?

**Comment by srxqds** [comment]
will aspnetcore  support dom api in plan?

**Comment by srpeirce** [comment]
@srxqds At the moment this is a limitation of WebAssembly - this means until DOM manipulation support/APIs are added to WASM we will need JS interop in our Blazor application.

From what I understand it is possible/likely in the future, but not anytime soon. Somebody who watches wasm closer will likely give a more specific answer.

**Comment by srxqds** [comment]
why **aspnetcore** do not include **WebAssembly.Bindings** with https://github.com/mono/mono/tree/master/sdks/wasm/framework/src/WebAssembly.Bindings.

**Comment by srxqds** [comment]
I think the it can make dom manipulation like these repo **AngleSharp** https://github.com/AngleSharp/AngleSharp and **CsQuery** https://github.com/jamietre/CsQuery/tree/master/source/CsQuery

**Comment by mkArtakMSFT** [comment]
Closing as answered by @srpeirce.
