### ISSUE TITLE
Blazor webassembly with authentication slow on load

### ISSUE THREAD

**Issue by andrewwilkin** [dotnet/aspnetcore#22633]
Having installed the out of the box template (Blazor webassembly with server + individual authentication + PWA) and running the sample.

It appears that on initial app load it calls out to the OidcController which significantly slows down the main panel from appearing. 

Is there a way of changing this behaviour to improve the experience? Perhaps caching the response for the controller would improve things as from what I could see for a given ClientId the response did not change.

**Comment by javiercn** [comment]
@andrewwilkin thanks for contacting us.

You can use `AddOpenIdAuthentication` instead and provide the values for the config directly. You'll loose the automatic updates when you change the config on the server though.

We already do caching of the settings the first time we retrieve them and put them in session storage, but new sessions need to get the settings at least the first time.

**Comment by andrewwilkin** [comment]
Thanks for the explanation and will give it a go. 

What is somewhat disconcerting is that the sidebar loads before the main pane which would look worse to a user than not loading anything which could be managed with a single loading icon (two different states - loading and authorizing)

**Comment by javiercn** [comment]
@andrewwilkin you can configure the UI for the login display to provide a value while the authorization is being checked.

**Comment by andrewwilkin** [comment]
This is the contents of App.razor:

```csharp
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                <Authorizing>
                    <p>Authorizing</p>
                </Authorizing>
                <NotAuthorized>
                    @if (!context.User.Identity.IsAuthenticated)
                    {
                        <RedirectToLogin />
                    }
                    else
                    {
                        <p>You are not authorized to access this resource.</p>
                    }
                </NotAuthorized>
            </AuthorizeRouteView>
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

This is the contents of MainLayout.razor:
```csharp
@inherits LayoutComponentBase

<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4 auth">
        <LoginDisplay />
        <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
    </div>

    <div class="content px-4">
        @Body
    </div>
</div>
```

Despite this the sidebar appears whilst the app is authorizing (and the authorizing template is displayed in the main panel).

Can you point me in the right direction of how to change this behaviour, have not seen anything in any of the docs. Many thanks in advance.

**Comment by andrewwilkin** [comment]
Managed to get this working by doing this in the MainLayout.razor but not sure why this is necessary here:

```csharp
@inherits LayoutComponentBase

    <AuthorizeView>
        <Authorizing>
            Authorizing
        </Authorizing>
        <Authorized>
            <div class="sidebar">
                <NavMenu />
            </div>

            <div class="main">
                <div class="top-row px-4 auth">
                    <LoginDisplay />
                    <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
                </div>

                <div class="content px-4">
                    @Body
                </div>
            </div>
        </Authorized>
        <NotAuthorized>

            <div class="sidebar">
                <NavMenu />
            </div>

            <div class="main">
                <div class="top-row px-4 auth">
                    <LoginDisplay />
                    <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
                </div>

                <div class="content px-4">
                    @Body
                </div>
            </div>
        </NotAuthorized>
    </AuthorizeView>
```
