### ISSUE TITLE
Fix warning "LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification"

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22632]
Occurs during native build phase of Windows builds. Full text:
``` text
gtestd.lib(gtest-all.obj) : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification [F:\workspace\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\CommonLibTests\CommonLibTests.vcxproj]
```

I believe #22017 introduced this warning though I'm not sure why. Warning is present in aspnetcore-ci build [20200529.33](https://dev.azure.com/dnceng/public/_build/results?buildId=664695) of master just after #22017 went in as well as [20200529.29](https://dev.azure.com/dnceng/public/_build/results?buildId=664584), a validation build for that PR but not in the builds of master before then, at least where I checked.

Part of #22240.

**Comment by dougbu** [comment]
@Pilchie please assign someone more familiar than I with native builds and GoogleTest. Would take me a good while to figure out what's going on here.

**Comment by blowdart** [comment]
Of course /safeseh should not be turned off on non-test projects.

**Comment by dougbu** [comment]
Makes sense @blowdart 

/fyi neither `/EDITANDCONTINUE` nor `/SAFESEH` are directly mentioned in our sources. `/SAFESEH` likely comes from pasing `ImageHasSafeExceptionHandlers = True` to the compiler task by default. Think setting `%(Link.ImageHasSafeExceptionHandlers)` metadata to `false` in the test projects would be the right fix. But, I am guessing❕

**Comment by blowdart** [comment]
Sounds about right. But why do test projects need edit and continue? That would be better to disable wouldn't it?

**Comment by dougbu** [comment]
Absolutely no idea what would be better.

Some docs I saw implied edit-and-continue was associated with incremental linking and that's tied to building for Debug. If that's correct, could pass `/INCREMENTAL:NO` in when linking for Debug. Someone more familiar with the compiler options and associated `*.vcxproj` properties should know.

**Comment by Pilchie** [comment]
`INCREMENTAL` and `EDITANDCONTINUE` are the defaults I think, but we definitely don't need them enabled on our CI builds.

**Comment by Pilchie** [comment]
See https://docs.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally?view=vs-2019 and the pages nearby for docs on these.

**Comment by jkotalik** [comment]
@dougbu does CodeCheck need to build native code?

**Comment by dougbu** [comment]
@jkotalik the managed projects output warnings when the native assets aren't found. Is there something special about the CodeCheck step that differs from the rest of the build?

**Comment by dougbu** [comment]
Wahoo 🥇
