### ISSUE TITLE
Blazor ensure javascript dependencies are loaded before rendering component

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#22643]
**Problem description**
We run into the problem that javascript dependencies are not done loading yet when the `OnAfterRenderAsync` of a Blazor component is being called. We call an interop method in our javascript file and that one then fails because dependencies are not done loading. NodeJS fixes this by the require function and we could also use the [requirejs ](https://requirejs.org/) or [loadjs ](https://github.com/muicss/loadjs) libraries for this, but doesn't that have the same theoretical problem that those dependencies aren't ready loading yet before being called?

**Idea**
Possibly Blazor should get a way that components can define their dependencies and the Blazor runtime will ensure that these dependencies and also their dependencies are being loaded before the component is rendered. (Both javascript and stylesheets)

```
// MyComponent.razor
@stylesheet "_content/ThemeLibrary/theme.css"

#if DEBUG
   @script "https://cdn.jsdelivr.net/npm/package@1.0.0/package.js"
#else
   @script "https://cdn.jsdelivr.net/npm/package@1.0.0/package.min.js"
#endif
...
```

Also the `require` function should be available inside javascript when running Blazor WASM. This so javascript files can ensure that their dependencies are loaded before they are being used.

```
// MyInterop.js
require("jquery");
...
```

**Background**
https://github.com/stsrki/Blazorise/pull/941
https://github.com/oqtane/oqtane.framework/issues/518

Also help, advice or insights on the above issues are welcome

**Comment by javiercn** [comment]
@njannink thanks for contacting us.

I'm not sure exactly how you are loading deps:
* If you load them on page startup, you can put the scripts before the Blazor script and that should be all you need.
* You can also decide when to start Blazor itself if you need to perform some async initialization first.
* If you are trying to load scripts as part of rendering a component into a page and similar:
  * Beware that's dangerous because scripts unlike styles can't be unloaded.
  * If you are loading the scripts during OnInitializedAsync via JS interop (async) the app will render the first time it goes async and it is likely that your script hasn't loaded yet.
  * I would recommend making sure you only try to do JS interop inside OnAfterRender after OnInitializedAsync has run to the end. You'll likely need to use a flag in your component to keep track of this situation.

**Comment by njannink** [comment]
The scripts are being loaded like this

```
<body>
    <app>Loading...</app>

    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

    <!-- This is the interop script that depends on the quill.js script -->
    <script src="_content/Blazorise.RichTextEdit/blazorise.richtextedit.js"></script>

    <script src="_framework/blazor.webassembly.js"></script>
</body>
```

And sometimes on a first clean load we get the following [exception](https://user-images.githubusercontent.com/900302/83339452-41da2700-a2ce-11ea-9542-002bf76feeb6.png)

In the Oqtane framework they have a similar [issue](https://user-images.githubusercontent.com/15007083/82667777-7ed75700-9c06-11ea-99fa-452ec59679a8.png)

The javascript invoke from Blazor fails because somehow the files are not done loading yet. When you simulate a slow 3G connection this behavior is easier to reproduce.

**Comment by javiercn** [comment]
You can use autostart=false and start blazor once your components have successfully initialized. Something like
```html
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
  initAsync()
    .then(() => Blazor.start())
    .then(() => somethingElse());
</script>
```

**Comment by javiercn** [comment]
> The javascript invoke from Blazor fails because somehow the files are not done loading yet. When you simulate a slow 3G connection this behavior is easier to reproduce.

This sounds like your scripts are doing something asynchronously. A regular script tag is render blocking (meaning the Blazor script won't start running until the scripts above it have finally executed).

It can be that the library you are using delays the initialization until the DOM is ready, and that's what might be causing the issue you are seeing, but that is not specific to Blazor but to how HTML/JavaScript work.

**Comment by njannink** [comment]
Might be an issue inside quilljs then. I will have a look

**Comment by njannink** [comment]
The quilljs library uses a webpack factory method to build the Quill object. So possibly that factory hasn't finished running yet when our interop script initialize method is being called.

**Comment by njannink** [comment]
I dont really have a resolution yet since I didn't detect any `async` logic or `Promise` usage  in the quilljs file. Also not in my interop.js file that is being called from blazor

**Comment by javiercn** [comment]
@njannink I can give you a solution because this is an untractable problem in the end. I would suggest you delay Blazor start until the DOM is ready at the very least and see if that fixes your issue, but otherwise it's not clear there's anything we can do here.

**Comment by njannink** [comment]
How do I detect if the DOM is ready?

**Comment by javiercn** [comment]
You can attach to
https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event
or to
https://developer.mozilla.org/en-US/docs/Web/API/Window#Events
and call Blazor.start there

**Comment by njannink** [comment]
@javiercn thanks for your help
