### ISSUE TITLE
DataProtection - CryptographicException when using PersistKeysToStackExchangeRedis as Key Storage Provider

### ISSUE THREAD

**Issue by ynanech** [dotnet/aspnetcore#22648]
We have changed the key. Running through the console, we can see that the latest key has taken effect. However, after being hosted by IIS, we have collected many exceptions, indicating that we can't find the original key. What's the reason? We use .net core 3.1.3 and Windows Server 2019. I tried to restart IIS and recycle IIS resources many times, and also restarted the server.

Original key:10923260-256e-4b20-893a-1d70a685a0f4
Latest key:de3e3b49-cbfc-4539-81d1-59c7877b2f7a

Exception information:
`An exception was thrown while deserializing the token.Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {10923260-256e-4b20-893a-1d70a685a0f4} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)`

Console information:
`D:\WebSites\Yahu.LuckyLive\Web>dotnet Yahu.LuckyLive.Web.dll
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {de3e3b49-cbfc-4539-81d1-59c7877b2f7a}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
      Considering key {de3e3b49-cbfc-4539-81d1-59c7877b2f7a} with expiration date 2021-04-29 07:55:04Z as default key.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[4]
      Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[3]
      Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
      Using key {de3e3b49-cbfc-4539-81d1-59c7877b2f7a} as the default key.
dbug: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService[0]
      Key ring with default key {de3e3b49-cbfc-4539-81d1-59c7877b2f7a} was loaded during application startup.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[2]
      Failed to locate the development https certificate at '(null)'.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[1]
      Unable to locate an appropriate development https certificate.
dbug: Microsoft.AspNetCore.Server.Kestrel[0]
      No listening endpoints were configured. Binding to http://localhost:5000 by default.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000`

**Comment by blowdart** [comment]
Does this happen after an app reset? Are you making redis persistent (so it saves and reloads data when it is shut down and restarted?)

**Comment by ynanech** [comment]
This is the code I used
`           
 var redis = Configuration.GetSection("Redis").Get<RedisCacheOptions>();
 
var app = Configuration.GetSection("Security").Get<ApplicationOptions>();
            services.AddDataProtection()
                .SetApplicationName(app.Name)
                .SetDefaultKeyLifetime(TimeSpan.FromDays(app.KeyLife))
                .PersistKeysToStackExchangeRedis(StackExchange.Redis.ConnectionMultiplexer.Connect(
                    redis.Configuration), $"{redis.InstanceName}DataProtection-Api-Keys");`

**Comment by ynanech** [comment]
I use the console to check that the new key has taken effect. Running through IIS, I find that there are many exceptions pointing to the old key

**Comment by blowdart** [comment]
@BrennanConroy Another one, or the same issue?

**Comment by ynanech** [comment]
This project is used by 50000 users. Two days ago, I completed the key replacement. Now, everything is normal when I visit the website, but there are still some abnormal logs of old keys. I can't think of any other causes

**Comment by BrennanConroy** [comment]
> @BrennanConroy Another one, or the same issue?

Seems different. If something encrypted with the old key was trying to be decrypted by the new key would this be the error you get?

**Comment by blowdart** [comment]
Yes it would, sorry, was off yesterday so just wanted to flag you incase.

@ynanech When you say you completed the key replacement what key were you replacing?

**Comment by ynanech** [comment]
Your working hours are our nights. We have jet lag.
I used to use the following key: 
 id="10923260-256e-4b20-893a-1d70a685a0f4". 
`<key id="10923260-256e-4b20-893a-1d70a685a0f4" version="1">
	<creationDate>2020-04-29T05:52:57.7092793Z</creationDate>
	<activationDate>2020-04-29T05:52:57.6937119Z</activationDate>
	<expirationDate>2021-04-29T05:52:57.6937119Z</expirationDate>
	<descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
		<descriptor>
			<encryption algorithm="AES_256_CBC"/>
			<validation algorithm="HMACSHA256"/>
			<masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection">
				<value>****</value>
			</masterKey>
		</descriptor>
	</descriptor>
</key>
`

I changed the new key: 
id="2878c095-5edb-4a4d-992c-11f969572f07".
`<key id="de3e3b49-cbfc-4539-81d1-59c7877b2f7a" version="1">
	<creationDate>2020-04-29T07:55:04.740086Z</creationDate>
	<activationDate>2020-04-29T07:55:04.7264962Z</activationDate>
	<expirationDate>2021-04-29T07:55:04.7264962Z</expirationDate>
	<descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
		<descriptor>
			<encryption algorithm="AES_256_CBC"/>
			<validation algorithm="HMACSHA256"/>
			<masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection">
				<value>*****</value>
			</masterKey>
		</descriptor>
	</descriptor>
</key>
`

I manually deleted the key in the cache and set the new key with 'PersistKeysToStackExchangeRedis'.
Received many exception logs after setting，I don't know what caused this exception.

Running through the console, we can see that the latest key has taken effect. However, after being hosted by IIS, we have collected many exceptions, indicating that we can't find the original key. What's the reason? We use .net core 3.1.3 and Windows Server 2019. I tried to restart IIS and recycle IIS resources many times, and also restarted the server.

`00:04:48.7458 Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7] 
An exception was thrown while deserializing the token.Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {10923260-256e-4b20-893a-1d70a685a0f4} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
`

**Comment by blowdart** [comment]
Don't manually delete the key. Its needed to unprotect things that were protected with the older key.

You don't cycle keys. You add new ones. Old keys still remain, they're just not used to encrypt new things. This is exactly the same workflow as you'd have with X509 certificates. Old keys are still there, and remain there, even after expiry, just in case something needs decrypting.
