### ISSUE TITLE
Add api-key support to Microsoft.AspNetCore.TestHost to simplify auth testing

### ISSUE THREAD

**Issue by wallymathieu** [dotnet/aspnetcore#22644]
### Describe the solution you'd like

I'd like for a solution where it's possible to configure API-keys middleware in a similar manner as JWT middleware for asp.net core.

I've found the approach useful in order to test asp.net core sites that require auth for part of the behavior.

### Additional context

You can find an implementation I've used for a previous employer:

https://github.com/carable/carable.aspnetcore.authentication.apikey

**Comment by blowdart** [comment]
What are you seeking to test? Policies? An available User property?

**Comment by wallymathieu** [comment]
What I'm currently seeking to test is middleware that extends policies with custom logic. For Carable I used api-key to fake out JWT auth in API service tests.

**Comment by blowdart** [comment]
This sounds like integration tests rather than unit tests, and you can always just generate JWTs on the fly to exercise the "right" type of authentication in your integration tests anyway, rather than have a test only authentication type.

Adding a non-standard authentication middleware, even for just testing, seems rather overkill.

**Comment by wallymathieu** [comment]
Why it's a good thing to talk about. A coworker sent me the following link: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#mock-authentication , why the feature seems to exist already.

**Comment by wallymathieu** [comment]
@blowdart , yes, very much integration tests with a few things faked out (calling to outside services) and with an in memory database.
