### ISSUE TITLE
[Blazor] Accessing DotNetObjectReference object in JavaScript

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#22647]
Hi,

I use JavaScript interop to keep a collection of Blazor component references in order to perform some UI operations. I need to be able to find a particular component by invoking a JavaScript function and passing in a DotNetObjectReference as an argument. By inspecting the JavaScript object, there appears to be a sequential unique **_id** field representing an instance of a Blazor component that I can take advantage of.

Is this a valid approach? I could not find anything in the documentation.

Thanks.

```
    dropdownComponents: [],

    registerDropdownComponent: (button, dropdownMenu, component) => {
        let index = blazorTabs.findDropdownComponentIndex(component);
        if (index === -1) {
            blazorTabs.dropdownComponents.push({ button: button, dropdownMenu: dropdownMenu, component: component });
        }
    },

    findDropdownComponentIndex: (component) => {
        let index = -1;
        for (let i = 0; i < blazorTabs.dropdownComponents.length; i++) {
            if (blazorTabs.dropdownComponents[i].component._id === component._id) {
                index = i;
                break;
            }
        }

        return index;
    },
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `_id` is a private field intended only for internal usage. We do not advice using it as we may choose to break it any time. You should consider coming up with your own solution for this.
One way you can achieve this is adding the objects into an array on the JS side and using the index as an identifier when referring to them.
