### ISSUE TITLE
Blazor component parameter difference between field / property and folder location

### ISSUE THREAD

**Issue by mikea314** [dotnet/aspnetcore#22645]
Visual Studio 2019 16.6.1
.Net Core 3.1.4

If I use a .cshtml file in the /Pages folder which uses a .razor component, the component is initialized twice. First time correctly, the second time incorrectly.

If I move the .cshtml file to a sub-folder e.g. /Pages/Test , then the .razor component is only initialized once, with the correct values.

I have the following folder layout:
/Pages/Test/
  ./RazorShapeComponent.razor
  ./ShapeContainer.cs
  ./ShapeBase.cs
  ./ShapeTriangle.cs

/Pages/
  ./ShapeTest.cshtml
  ./ShapeTest.cshtml.cs

Where:
  ShapeTriangle extends ShapeBase
  ShapeContainer has a List<ShapeBase> Shapes (field or Property)

  RazorShapeComponent.razor takes a ShapeContainer Parameter
      [Parameter]
      public ShapeContainer ShapeContainer { get; set; }

  ShapeTest.cshtml.cs has: ShapeContainer MyShapeContainer { get; set; }
     MyShapeContainer is instantiated in the ctor

and:
  ShapeTest.cshtml uses the RazorShapeComponent
<component type="typeof(RazorShapeComponent)" render-mode="ServerPrerendered" param-ShapeContainer='@Model.MyShapeContainer' />

**Behaviour**
A) If ShapeTest is located in /Pages/ShapeTest.cshtml (https://localhost:44354/ShapeTest)
and ShapeContainer has a Field: List<ShapeBase> Shapes;

Then RazorShapeComponent.razor's OnInitialized() is called twice.
The first time, the ShapeContainer parameter is initialized correctly
![image](https://user-images.githubusercontent.com/393349/83978082-4d989f80-a905-11ea-8c54-3cf667f4a8f3.png)

The second time, the List<ShapeBase> is null
![image](https://user-images.githubusercontent.com/393349/83978031-f98dbb00-a904-11ea-8b3d-d53d5347c434.png)

B) If ShapeTest is located in /Pages/ShapeTest.cshtml (https://localhost:44354/ShapeTest)
and ShapeContainer has a Property: List<ShapeBase> Shapes {get;set;}

Then RazorShapeComponent.razor's OnInitialized() is called twice.
The first time, the ShapeContainer parameter is initialized correctly
![image](https://user-images.githubusercontent.com/393349/83978082-4d989f80-a905-11ea-8c54-3cf667f4a8f3.png)

The second time, the List<ShapeBase> is initialized but contains instances of the base type
![image](https://user-images.githubusercontent.com/393349/83978148-c697f700-a905-11ea-8279-d5b7afe05f55.png)

C) If ShapeTest is located in /Pages/Test/ShapeTest.cshtml (https://localhost:44354/Test/ShapeTest)
and ShapeContainer has a Property or Fied: List<ShapeBase> Shapes {get;set;}

Then RazorShapeComponent.razor's OnInitialized() is only called once and is initialized correctly.
![image](https://user-images.githubusercontent.com/393349/83978378-5ee2ab80-a907-11ea-9dac-fa5c83fafeba.png)

And the correct output is generated
![image](https://user-images.githubusercontent.com/393349/83978394-715ce500-a907-11ea-8c17-7dde087e4936.png)

[BugLog.zip](https://github.com/dotnet/aspnetcore/files/4742790/BugLog.zip)

Regards,
Michael

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how Blazor works. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mikea314** [comment]
Hi, this isn't a general query. Blazor isn't serializing complex parameters correctly under some circumstances. It's a bug.
