### ISSUE TITLE
Receive "The returnUrl field is required" validation error when enabling Nullable reference types

### ISSUE THREAD

**Issue by bzamora** [dotnet/aspnetcore#22656]
### Describe the bug

When enabling nullable reference types I receive a validation error "The returnUrl field is required" when navigating to:
`~/Identity/Account/Register`
or 
`~/Identity/Account/Login`

### To Reproduce

Start from a new aspnetcore identity template with individual account, all views scaffolded. Then enable [Nullable reference types ](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) in the project,

`<Nullable>enable</Nullable>`

Navigate to `~/Identity/Account/Register`. You should see in the validation summary 

"The returnUrl field is required" 

### Further technical details

- ASP.NET Core version Microsoft.AspNetCore.App 3.1.4

![image](https://user-images.githubusercontent.com/682399/84040769-5475ef80-a9a3-11ea-93fb-5c237f6005f7.png)

![image](https://user-images.githubusercontent.com/682399/84040876-77080880-a9a3-11ea-9802-86fcee496266.png)

**Comment by bzamora** [comment]
Changing the OnGetAsync parameter 

from
`public async Task OnGetAsync(string returnUrl = null)`

to 
`public async Task OnGetAsync(string? returnUrl = null)`

Solves the error. Maybe good to note in documentation somewhere as it took a bit to find the exact cause. Hopefully helps others...

**Comment by HaoK** [comment]
What do we want to do here @blowdart generating different scaffolding code based on nullability options is not something we currently are planning are we?

**Comment by blowdart** [comment]
Oh dear.

I honestly don't know, I'd assume that we want to support nullability, which in turn may need scaffolding changes. @Pilchie @DamianEdwards this is probably an opinion for you to weigh in on.

**Comment by Pilchie** [comment]
I'm confused as to how this causes a runtime error?  The nullable annotations in the C# compiler shouldn't change the generated code afaik.

**Comment by blowdart** [comment]
Closing in favor of aggregating issue, #25310
