### ISSUE TITLE
Blazor AuthorizeRouteView should have an "NotAuthenticated" property

### ISSUE THREAD

**Issue by EPinci** [dotnet/aspnetcore#22653]
### Is your feature request related to a problem? Please describe.
The current implementation of Blazor's AuthorizeRouteView does not allow to distinguish between a "not authorized" state (where you might want to display an error) and a "not authenticated" state (where it might be appropriate to redirect to a login page).
This make very difficult to properly manage sites/app with mixed public and authenticated contents.

### Describe the solution you'd like
I would like to see a "NotAuthenticated" property added to the class to handle such a case.
Additionally I would like to have support for automatic redirection to a login page if not authenticated as it now exists on MVC.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do.
What you can do instead, you can use the `User.IsAuthenticated` property to differentiate those cases.
