### ISSUE TITLE
Blazor Client Auth with AWS Cognito Slow

### ISSUE THREAD

**Issue by steven-pearson** [dotnet/aspnetcore#22651]
### Describe the bug
Issue when creating a standalone Blazor WebAssembly app and linking up Authentication (same process as described in https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1) using oidc authentication and using AWS Cognito as the authentication provider.

### To Reproduce
Create a new User Pool and App in AWS Cognito. Note the Cognito ID and the client ID and set in the app settings e.g. 
  "OidcProviderOptions": {
    "Authority": "https://cognito-idp.eu-west-2.amazonaws.com/eu-west-COGNITO_ID",
    "ClientId": "CLIENT_ID"
  },

### Exceptions (if any)
App tries to authenticate but huge delay of about 10 seconds until it redirects to the AWS login. An exception is shown in Javascript Console  'X-Frame-Options' to 'DENY' which appears to be the crux of the issue.  Switched out to using Azure B2C and the exception and delay disappear.

### Further technical details
- VS4Mac 8.6.2

dotnet info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.805 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.0.101 [/usr/local/share/dotnet/sdk]
  3.1.100-preview2-014569 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@steven-pearson thanks for contacting us.

This is likely an issue with your config in AWS. I don't know about AWS Cognito so I can't offer guidance on it, but it is likely you need to add your domain to the list of allowed domains/origins when using AWS Cognito, as to how to do that, I have no idea.

**Comment by steven-pearson** [comment]
Thanks for the reply, don't think that's the issue here.  The authentication works fine so the scopes, redirects etc all line up.  Another person had the same issue and switching to auth0 was fine.  I switched to AzureB2C to test and that was fine too. Have linked my SO question and related one.

https://stackoverflow.com/questions/62245922/standalone-blazor-webassembly-authentication-very-slow

https://stackoverflow.com/questions/61845477/blazor-webassembly-amazon-cognito/62258316#62258316

**Comment by javiercn** [comment]
@steven-pearson I can't comment on AWS Cognito specifics, but see https://github.com/aws-amplify/amplify-js/issues/1218#issuecomment-419323795 for more details.

This is an issue with AWS Cognito not being standard compliant. Seems like you not only can't sign-in silently, but you will likely not be able to refresh an access token silently via an iframe.

While we do our best to support as many providers as we can, we don't plan to change our implementation to support non OIDC compliant providers.

If you need to use AWS Cognito I would suggest you consider implementing your own JS interop layer (it can be done on top of our infrastructure to explicitly support AWS Cognito, look at how `Microsoft.Authentication.WebAssembly.Msal` is implemented), that said I would acknowledge this is not a trivial task, but we don't have the capacity to be supporting 3rd party providers if they are not compliant.

**Comment by steven-pearson** [comment]
Thanks for the update, makes sense.  Will either look to build that or switch out to B2C.  Closing this one.
