### ISSUE TITLE
Add build-time support for lazy-loading in Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#22669]
To support lazy-loading in Blazor, we need a way for users to identify that an assembly is lazy-loadable so that we can treat it correctly in the build steps. We need to:

- Add support for `BlazorLazyLoad` attribute in project file
- Add support for `dynamicAssembly` property in `blazor.boot.json`

**Comment by mrpmorris** [comment]
I think it would be better to identify lazy load in the app startup.
