### ISSUE TITLE
Razor -> Razor go-to-definition and friends do not work if other Razor file is closed

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22677]
1. Create a new Blazor app.
1. Open Counter.razor and in the `@code` section add `public static int DefaultIncrement`
1. Close Counter.razor
1. In Index.razor add `@{ var x = Counter.DefaultIncrement; }`
1. Go-to-definition on `DefaultIncrement` in Index.razor

**Expected:** Counter.razor is opened and the navigation request fulfilled
**Actual:** Nothing

There's a very high chance that this is an external limitation of VS' LSP platform.

/cc @ajaybhargavb

**Comment by ajaybhargavb** [comment]
This was broken due to the batch mapping requests change.
