### ISSUE TITLE
Rename ShouldRender

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#22682]
From https://github.com/dotnet/aspnetcore/issues/16381#issuecomment-375013560

`ShouldRefresh` makes sense in my head.

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

We don't plan to do this. This is a breaking change that will affect many people and it is not clear for us that there is value in it to justify breaking others nor that it makes it much clearer compared to the existing version.

Our priority is to maintain backwards compatibility as much as possible and make migrations to new versions easier, so we don't do these types of changes unless they are incredibly justified.
