### ISSUE TITLE
[Blazor] InvokeAsync is not synchronising access

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#22695]
### Describe the bug
A non reentrant service can be accessed by multiple threads even when the only access to that service is via InvokeAsync.

If my understanding is correct, multiple components in a server-side Blazor app should be able to synchronise (chain) tasks by using InvokeAsync.

### To reproduce

First, change the WeatherForcastService to prevent it being reentrant.
1. Add `private volatile int LockCount;`
2. Change `GetForecastAsync` to the following

```
public async Task<WeatherForecast[]> GetForecastAsync(DateTime startDate)
{
	if (Interlocked.CompareExchange(ref LockCount, 1, 0) == 1)
		throw new InvalidOperationException("Multi-thread access");

	try
	{
		await Task.Delay(500);
		var rng = new Random();
		return Enumerable.Range(1, 5).Select(index => new WeatherForecast
		{
			Date = startDate.AddDays(index),
			TemperatureC = rng.Next(-20, 55),
			Summary = Summaries[rng.Next(Summaries.Length)]
		}).ToArray();
	}
	finally
	{
		Interlocked.Decrement(ref LockCount);
	}
}
```

Next, change FetchData's `@code` section as follows.

```
@code {
	private WeatherForecast[] forecasts;

	protected override async Task OnInitializedAsync()
	{
		await InvokeAsync(async () =>
		{
			forecasts = await ForecastService.GetForecastAsync(DateTime.UtcNow);
		});
	}
}
```

Finally, edit Index.razor as follows

```
@page "/"
	<FetchData />
	<FetchData />
```

### Also...
If we pass `Index.InvokeAsync` to `<FetchData>` via a parameter and invoke via that, the service is still reentrant.

### Further technical details
- ASP.NET Core version 3.1
- The IDE (VS / VS Code/ VS4Mac) VS 16.6
- Include the output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

That's not the way it works. The synchronization context prevents multiple threads from running concurrently, but async code is able to interleave freely.

What happens in your case is that InvokeAsync the fist time executes up until the `Task.Delay` and then yield execution, at which point, the other component is rendered, InvokeAsync is called again and the callback tries to run (again up until Task.Delay) but throws before the condition you check at the beginning of the method.

The only guarantee that the synchronization context blazor provides is that continuations will run one at a time and in the context of the Blazor UI, but the order in which they do is not guaranteed and it is likely that if you are using asynchronous code they can run in different order.

**Comment by mrpmorris** [comment]
@javiercn This answer doesn't make much sense to me, let me explain why and perhaps we can work out where my ignorance lies :)

1. When I first call InvokeAsync the dispatcher will keep track of the Task I pass it as the most recent take to be enqueued (also the first one).
2. The task hits `await Task.Delay`. That gives other components a chance to execute.
3. The second component's code runs
4. That calls `InvokeAsync`
5. The Dispatcher sees the current Task is not yet completed, so uses `.ContinueWith` to ensure it runs afterwards
6. The first task's `Task.Delay` expires, and the code runs to the end of the method
7. The first task is now completed
8. The task now runs the second task (because of `ContinueWith`).

The first task (via InvokeAsync) yields, but that doesn't mean it has finished until the method runs to completion, so the second take via InvokeAsync shouldn't run it should be queued up.

**Comment by javiercn** [comment]
@mrpmorris the bit that you are missing is that when `InvokeAsync` is called within the `UI thread` it will execute the function right away.

**Comment by mrpmorris** [comment]
@javiercn In which case, shouldn't this execute in sequence as InvokeAsync is executed by a new task?

(FetchData component)
```
	protected override void OnInitialized()
	{
		Task.Run(() =>
		{
			_ = InvokeAsync(async () =>
			{
        await Task.Delay(15);
				forecasts = await ForecastService.GetForecastAsync(DateTime.UtcNow);
			});

		});
	}
```

**Comment by javiercn** [comment]
@mrpmorris It depends on whether `Task.Run` inlines the execution

**Comment by mrpmorris** [comment]
What about this variation?

```
protected override void OnInitialized()
{
	Task.Run(async() =>
	{
		await Task.Delay(15);
		await InvokeAsync(async () =>
		{
			forecasts = await ForecastService.GetForecastAsync(DateTime.UtcNow);
		});
	});
}
```

I'm trying to marry up the behaviour with what the documentation says:

> Blazor Server's synchronization context attempts to emulate a single-threaded environment so that it closely matches the WebAssembly model in the browser, which is single threaded. At any given point in time, work is performed on exactly one thread, giving the impression of a single logical thread. **No two operations execute concurrently.**

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state

This code is definitely executing concurrently.

**Comment by javiercn** [comment]
> This code is definitely executing concurrently.

I don't think so. As I mentioned above, what is happening is that the code for the 2nd component render is executing while the code for the 1st component render has yielded, but there is no code running on two separate threads at the same time. That's the difference between async code and concurrent code.

That code will run the same every time even if you remove the synchronization primitive and just use ++ on the variable. If you want to try and force it, try having 500 components, incrementing a static value on each of them, yielding and decrementing the value upon completion, and then displaying the value in a separate component.

If the components run concurrently you should see different results after a few executions. If the components run asynchronously but within a single thread, you will always see 0 as the final result.

**Comment by mrpmorris** [comment]
You are correct.

I have no idea how this Vodoo works, but it works exactly as you said it should.

**Comment by mrpmorris** [comment]
PS: @javiercn - I've added a sample demonstrating your assertions are correct.

https://github.com/mrpmorris/blazor-university/tree/master/src/RenderTrees/UsingInvokeAsync
