### ISSUE TITLE
Blazor template "log in"/"log out" language

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#22696]
The templates use "log in"/"log out" language, but the doc guidance is to avoid that terminology when possible ...

> Use sign in to describe starting a session on a computer, a device, a network, an app, or anywhere a username and password are required. Use sign out to refer to ending a session.
>
> Don't use log in, login, log into, log on, logon, log onto, log off, log out, logout, sign into, signin, signoff, sign off, or sign on unless these terms appear in the UI (and you're writing instructions).

Reference: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/sign-in-sign-out

Although the guidance states "unless these terms appear in the UI," the product unit here controls the UI for these templates. Apparently, there is (or was) a movement toward consistency across all of MS's products and services. For example, I think Azure has adopted "sign in"/"sign out" language everywhere.

Would it be possible to align the templates with the doc division (and Azure) guidance, including the method names (e.g., `BeginLogOut`)?

**Comment by javiercn** [comment]
@guardrex thanks for the issue.

Can you provide a list of specific proposals to change? It's not clear from the issue. 

The templates use Login/Logout afaik on things that are visible to the user. There are a few types that use SignIn/SignOut.

For things that are user visible, they would require breaking changes.

**Comment by guardrex** [comment]
On second thought, this would require a considerable amount of work for little benefit. It's well known what the templates display. If management wanted to align all of MS's products and services on common terminology, I think it would've been done by now. I don't think they're concerned about it.
