### ISSUE TITLE
Terminate socket connection completely

### ISSUE THREAD

**Issue by Sarper-Ekinci** [dotnet/aspnetcore#22700]
### Describe the bug
I am trying to terminate all connections with socket After I logout. when I logging out connection is disconnecting but I still receiving message from "ReceiveMessage" method. Is there any idea what
is wrong with code? 
my code seems below

```
initConnection() {
  this.connection = new signalR.HubConnectionBuilder()
            .withUrl("/chat", {
                accessTokenFactory: () => {
                    return token;
                }
            })
            .withAutomaticReconnect([0, 1000, 2000, 3000, 5000, 9000, 15000])
            .build();
  }
  Tasks(){
        this.connection.on("ReceiveMessage", this.ReceiveMessage);
  }
    async Disconnect(){
        this.connection.off("ReceiveMessage", this.ReceiveMessage);
        this.connection.stop().then(() => {
            delete this.connection
        }).catch(console.log);
    }

```

**Comment by BrennanConroy** [comment]
> when I logging out connection is disconnecting but I still receiving message from "ReceiveMessage" method

When you log out are you calling your `Disconnect` method?

Try `this.connection.off("ReceiveMessage");` without the function instance and see if that has the behavior you want.

**Comment by Sarper-Ekinci** [comment]
> > when I logging out connection is disconnecting but I still receiving message from "ReceiveMessage" method
> 
> When you log out are you calling your `Disconnect` method?
> 
> Try `this.connection.off("ReceiveMessage");` without the function instance and see if that has the behavior you want.

I am calling Disconnect method during logout. 

I had tried before, but there is not any different action. 

Am I need to do some thing on back-end to unsubscribe?

**Comment by BrennanConroy** [comment]
Can you explain your scenario some more.

Where are you seeing the unexpected messages?

**Comment by Sarper-Ekinci** [comment]
firstly, I want to connect to socket after user logged in. So, I created a class which is used for Real-time messaging. I call initConnection method and some configurations to create socket connection and also I call my tasks method to begin data transfer. I do not have any problem until here, After that; I want to terminate all my connections after user logged out.
When testing; I open 2 tab and same user is login for both. if I sent a message to one of them, I can receive the message from other one. If I logout someone, "server disconnected" is writing on console. if I sent a message from user which is login, I still see message from other user which is logout.

I hope, I could explain.

**Comment by BrennanConroy** [comment]
> If I logout someone, "server disconnected" is writing on console. if I sent a message from user which is login, I still see message from other user which is logout.

If you're still getting a message from the logged out user, then you aren't logged out. Make sure you're calling `connection.stop()` because it seems unlikely that you are if they are still getting messages.

If you could share your app on github that would help too.

**Comment by Sarper-Ekinci** [comment]
### SignalR Class
```
import  * as signalR from '@microsoft/signalr';
class SignalR {
    startConnection(){
        this.connection = null;
        this.initConnection();
        this.start();
        this.onreconnecting()
        this.onclose();
        this.Taskes();
    }
    initConnection() {
        const token = localStorage.getItem('access_token') ? JSON.parse(localStorage.getItem('access_token')): null;
        this.connection = new signalR.HubConnectionBuilder()
            .withUrl("/chat", {
                accessTokenFactory: () => {
                    return token;
                }
            })
            .withAutomaticReconnect([0, 1000, 2000, 3000, 5000, 9000, 15000])
            .build();
    }
    async  start() {
        try {
            await this.connection.start();
            console.log("connected");
        } catch (err) {
            console.log('error handle', err);
        }
    }
    onclose() {
        this.connection.onclose(async (res) => {
        });
    }
    Taskes() {
        this.connection.on("ReceiveMessage", this.ReceiveMessage);
    }
    ReceiveMessage = (user, message) => {
        console.log("ReceiveMessage",user, message )
    }
    onreconnecting() {
        this.connection.onreconnecting(error => {
            console.log("onreconnecting", error)
        });
    }
    SendMessage(text){
        this.connection.invoke("SendMessage", "sarper", text).catch(function (err) {
            return console.error(err.toString());
        })
    }
   
    async Disconnect(){
        this.connection.off("ReceiveMessage", this.ReceiveMessage);
        this.connection.stop().then(() => {
            delete this.connection
        }).catch(console.log);
    }

}

const signalRConnection = new SignalR();
export function startGlobalConnection(){
    signalRConnection.startConnection();
}
export default signalRConnection;
```
### Main Page

```
import React, { Component } from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons'
import setAuth from '../../Helper/setAuth';
import SignalR, { startGlobalConnection } from '../../Helper/SignalR'
export default class Main extends Component {
    constructor(props) {
        super(props)
        this.state = {
            text: ""
        }
        startGlobalConnection();
    }
    sendMes() {
        SignalR.SendMessage(this.state.text);
    }
    logOut() {
        SignalR.Disconnect().then(() => {
            localStorage.clear();
            setAuth(false);
            this.props.history.push(`/Login`);
        });
    }
    render() {
        return (
            <div className={`MainContent`}>
                <div className="logOut" onClick={this.logOut.bind(this)}><FontAwesomeIcon icon={faSignOutAlt} /></div>
                <input type="text" onChange={(el) => this.setState({ text: el.target.value })} />
                <button onClick={this.sendMes.bind(this)}>send</button>
            </div>
        )
    }
}

```

**Comment by BrennanConroy** [comment]
I meant more of a runnable app to try to repro the issue.

**Comment by Sarper-Ekinci** [comment]
I can not share whole code because company privacy.But also I can quickly prepare a program which is simulate this bug.
