### ISSUE TITLE
Linked CSS/JavaScript files no longer work in ASP.Net Core projects (changes not made to original file, or linked files not in Solution Explorer after re-opening project)

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/aspnetcore#22715]
### Describe the bug
With standard ASP.Net framework projects (4.x), you can add a "linked" .js JavaScript file in your project, where the file is really located outside the project folder. Any changes made to the file inside the project will be reflected in the original/master copy, and you can add a custom Target to your .csproj file that copies the latest version of the file to your project folder.
I've used this for 10 years, for several .js files that are shared across numerous projects, that don't get changed often. When they do change, I want to change it in the current project, but get the changes reflected to the original location, so that the next time other projects are built, they get the latest version.

In ASP.Net Core 3.x projects (haven't tried earlier versions), this no longer works. I've been working with @davidwengier at [https://github.com/dotnet/project-system/issues/6226](https://github.com/dotnet/project-system/issues/6226), who gave me several things to try, but none of them work (turning off EnableDefaultItems and/or EnableDefaultNoneItems). The problem will be 1 of 2 types: either the linked .js file that's currently build action "None" will get set to "Content" when the custom Target copies the file, OR by turning off EnableDefaultItems and EnableDefaultContentItems, and manually "including" files, the linked .js file will show correctly in Solution Explorer, but after closing/re-opening the solution, it no longer shows, even though it's still a "linked" file according to the .csproj file.

### To Reproduce
In a new .Net Core web project (empty is fine), add the wwwroot folder if it doesn't exist.

Add the following to the bottom of the .csproj file:
`
<Target Name="CopyLinkedContentFiles" BeforeTargets="Build">
	<Copy SourceFiles="%(Content.Identity)" DestinationFiles="%(Content.Link)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="'%(Content.Link)' != ''" />
    <Copy SourceFiles="%(None.Identity)" DestinationFiles="%(None.Link)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Condition="'%(None.Link)' != ''" />
</Target>
`

Right-click the wwwroot folder and choose "Add existing item", then point to a .js file that's outside the project directory...like "C:\temp\test.js", and choose the "Add as link" from the dialog's "Add" button dropdown menu. In Solution Explorer, you see the "link" icon for the .js file.

Build the project, and verify a copy of the .js file is now on disk at the wwwroot folder. After building, the "link" icon is gone from the file in Solution Explorer.

Open that .js file within the project and make a change and save it. Notice that it makes the change to the copy of the file within the project, not the original.

In the attached demo project, zzTempWeb2a_0.zip, it turns off EnableDefaultNoneItems. In demo zzTempWeb2a.zip, it turns off EnableDefaultNoneItems and EnableDefaultContentItems, and linked .js files work correctly (changes are made the original copy, and after building, the changed file is copied to the project's directory), **but after closing/re-opening the solution, Solution Explorer no longer shows the linked .js file**.

[zzTempWeb2a_0.zip](https://github.com/dotnet/aspnetcore/files/4753590/zzTempWeb2a_0.zip)
[zzTempWeb2a.zip](https://github.com/dotnet/aspnetcore/files/4753592/zzTempWeb2a.zip)

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

*****************
Microsoft Visual Studio Community 2019
Version 16.6.0
VisualStudio.16.Release/16.6.0+30114.105
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.6.936.3669
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
ASP.NET Web Frameworks and Tools 2019   16.6.936.3669

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear Recent   1.1.1
Clears recent projects and files lists

CSS Tools 2019   1.1.4
Provides additional features to the CSS editor in Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0

**Comment by javiercn** [comment]
@Dean-NC thanks for contacting us.

I would suggest you have an explicit itemgroup before the place where you link the file that removes that specific content from the itemgroup unconditionally

```xml
<ItemGroup>
  <Content Remove="wwwroot\file.js" />
  <Content Include="../../../shared/file.js Link="wwwroot\file.js" />
</ItemGroup>
```

**Comment by javiercn** [comment]
@davidwengier thanks for the clarification. We do have something for this, called Static Web Assets, but it requires the frontend files to live in a Razor Class Library and for the project to reference them. See [here](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#create-an-rcl-with-static-assets)

What I want to make sure is that we all understand this is not a scenario we claim to support, even though it worked in old ASP.NET this is not something we considered for ASP.NET Core. It might be possible to make it work with enough MSBuild trickery but its up to users who want to do this to figure out the MSBuild required to do so.

From my point of view, its easier to have the file linked to a separate path on the project, leave the copy in place and use the linked file for edits. That way you don't have to fight the MSBuild tooling nor the editor.

**Comment by Dean-NC** [comment]
@davidwengier Thanks for still looking into this.
@javiercn If it's not supposed to work, it's best to get the Visual Studio team to remove the ability to add a file as linked, when the Add Existing File dialog shows for Core projects, otherwise people naturally think it should work.

**Comment by davidwengier** [comment]
>  If it's not supposed to work, it's best to get the Visual Studio team to remove the ability to add a file as linked

Linked files work fine in Visual Studio, but they're designed to allow people to pretend that a file exists in a location that it doesn't really exist in. The problem you're seeing is specific to the case where you have a real file at that location too, the assumption in the system being that if you have a file there by that name, then that's probably the one that you want to use.

For the point of view of "What is the supported way of sharing front end files?" it seems like Static Web Assets is the answer, so this issue can probably be closed. We can continue discuss Visual Studio behaviour on the project system issue.

**Comment by javiercn** [comment]
I agree with @davidwengier here.

**Comment by Dean-NC** [comment]
@davidwengier  @javiercn  I've only recently switched to "Core" web applications from traditional ASP.Net, so I'm trying to adjust. Serious thanks to both of you for hanging in there to help me. I'm the kind to explore all options, to see what's best for me. I knew about Razor libraries, but didn't one purpose was static assets, so I'll look at that.

**Javier**, you mentioned: "linked the file with a different name like .original.ext and use that when modifying the file", and "put the linked file in a separate path and just use that for editing".  I sound ignorant here, but I don't quite get that, please give a detailed example, like if you have OriginalFile1.js that's located outside the project dir, how can changes be made to it, yet benefit the project. How do you add/include the shared file to the project?  Is the "CopyLinkedContentFiles" Target still used?  If so, what changes to it are needed?  Thanks!!

**David**, I'll still follow the project system issue, to see what comes out of that.

**Comment by javiercn** [comment]
> **Javier**, you mentioned: "linked the file with a different name like .original.ext and use that when modifying the file", and "put the linked file in a separate path and just use that for editing". I sound ignorant here, but I don't quite get that, please give a detailed example, like if you have OriginalFile1.js that's located outside the project dir, how can changes be made to it, yet benefit the project. How do you add/include the shared file to the project? Is the "CopyLinkedContentFiles" Target still used? If so, what changes to it are needed? Thanks!!

```xml
<ItemGroup>
  <Content Include="..\..\yourfile.js" Link="wwwroot\yourfile.source.js" />
  <Content Update="wwwroot\yourfile.js" CopyToPublishDirectory="false" />
</ItemGroup>
```

This should make the file appear under www\yourfile.js after you copy it, and the original file appear in wwwroot\yourfile.original.js, probably nested inside, but an alternative is to put it in any other path that does not interfere with the file you copy, like `Link="sources\yourfile.js"`

**Comment by Dean-NC** [comment]
@javiercn Thanks, that put me on the right track. I liked having a different "source" folder so that I could train my brain to use that when making edits, as supposed to expanding the .js file, since it would be too easy to change the parent one, instead of the master.  It does work, but after building, it curiously puts the web app's .exe in the js folder. **Is this a bug?**

![NewCopyTaskResult](https://user-images.githubusercontent.com/12361341/84549610-683c9100-acd6-11ea-9085-ac1ab36e81fc.png)

[zzTempWeb2a.zip](https://github.com/dotnet/aspnetcore/files/4773423/zzTempWeb2a.zip)

`
<ItemGroup>
<None Include="..\module1.js" Link="script-source\module1.js" />
<None Update="script-source\module1.js" CopyToPublishDirectory="false" />
</ItemGroup>

<Target Name="CopyLinkedFiles" BeforeTargets="Build">
<Copy SourceFiles="%(None.Identity)" DestinationFiles="wwwroot\js\common\%(Filename)%(Extension)" Condition="'%(None.Link)' != ''" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" />
</Target>
`

I also tried a **RazorClassLibrary** project added to the solution, and I was able to get that to work, meaning changes to .js files are done in the library, and I reference the library from the web app. But .js intellisense doesn't work.

There's a [StackOverflow article](https://stackoverflow.com/questions/59909704/js-css-intellisense-between-projects-in-vs-2019) that says to use an old-school `///<reference>` line in any .js file.

but it says it can't find my _content/RazorClassLibrary1/some-file.js. It's logged here: [https://github.com/dotnet/AspNetCore.Docs/issues/17484](https://github.com/dotnet/AspNetCore.Docs/issues/17484), so we'll see.

At least I have 2 ways to get it working.  Thanks again.
Would there be any difference, if we use "Shared Projects" feature of VStudio ??

**Comment by javiercn** [comment]
> But .js intellisense doesn't work.

Yes, we are working with the tooling folks to improve the experience here.

I'm closing this issue since the original issue has been addressed.

**Comment by Dean-NC** [comment]
@javiercn When using the different "source folder" method above, and copying the .js to the wwwroot\js folder, is it normal for the app's .exe to get put in the js folder? This only happens when I use this different source folder method.

**Comment by Dean-NC** [comment]
@javiercn There's a VStudio bug report here

[https://developercommunity.visualstudio.com/content/problem/1067564/visual-studio-2019-intellisense-not-working-for-cs.html](https://developercommunity.visualstudio.com/content/problem/1067564/visual-studio-2019-intellisense-not-working-for-cs.html)

where the Razor library intellisense is discussed. The author and myself noticed that intellisense works with an old-school reference statement, or if you're importing an es6 class from the library, but relative referencing must be used, and the number of levels up to the library is more than you think.
