### ISSUE TITLE
NugetPackage has wrong dot net core version

### ISSUE THREAD

**Issue by Gavin1Sinai** [dotnet/aspnetcore#22719]
Please could you update the dotnet core version on this project:
https://github.com/dotnet/aspnetcore/blob/v3.1.5/src/DataProtection/EntityFrameworkCore/src/Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.csproj

It's still 2.1, we need 3.1.

You can see 2.1 dependency on nuget:
https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.EntityFrameworkCore/

**Comment by blowdart** [comment]
Why do you think you need a 3.1 dependency? It doesn't need anything from there, it's fine targeting netstandard2.1, like the rest of data protection and it's deliberate, because people use it outside of asp.net

**Comment by Gavin1Sinai** [comment]
Hi, thanks for responding to me.

I am getting this error in the build server: 

**NU1202: Package Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 3.1.3 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 3.1.3 supports: netstandard2.1 (.NETStandard,Version=v2.1)**

This does not happen with DataProtection.

As you can see on Nuget, DataProtection has a different dependency profile to DataProtection.EntityFrameworkCore. See [Nuget Data Protection v3.1.3](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/3.1.3 ) vs. [Nuget Data Protection EntityFrameworkCore v3.1.3](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.EntityFrameworkCore/3.1.3).

From the DataProtection csproj file:
`    <TargetFrameworks>netstandard2.0;$(DefaultNetCoreTargetFramework)</TargetFrameworks>`

From the DataProtection.EntityFrameworkCore csproj file
`  <TargetFramework>netstandard2.1</TargetFramework>`

**Comment by Gavin1Sinai** [comment]
Hi, is there any update on this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Looks like the package is correct. We recommend filing an issue in the [`NuGet` repo](https://github.com/nuget/home) to get help with the error you're seeing `NU1202`.
