### ISSUE TITLE
Is the new IAuthorizationMiddlewareResultHandler flexible enough?

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/aspnetcore#22713]
Hey,

I'm currently playing with the new `IAuthorizationMiddlewareResultHandler` hook to determine if it's something I could leverage in OpenIddict's validation stack to help developers automatically map things like failed `ScopeRequirement` to proper standard 403 responses (with a `WWW-Authenticate` header containing `error=insufficient_scope` and `scope=[the missing scope]`).

`IAuthorizationMiddlewareResultHandler` uses an interesting approach, but it's not clear to me whether it offers enough flexibility or not:

  - Only one `IAuthorizationMiddlewareResultHandler` can be resolved by the authorization middleware, so it's hard to include one in a NuGet package without shadowing the existing one.
  - You can use service decoration, but it's a very fragile option as it relies on very strict registration order (we have the same issue with `ICorsPolicyProvider` that requires using decoration if you need to resolve policies from multiple places).

Instead of this approach, couldn't we have something similar to the authentication handler/authentication handler provider mechanism, where the authorization middleware would ask an hypothetical `IAuthorizationResultHandlerProvider` to provide an `IAuthorizationResultHandler` instance specific to the authentication scheme(s) used by `AuthorizationPolicy` and to the failed authorization requirement?

/cc @Tratcher

**Comment by HaoK** [comment]
Can you clarify why dropping in your own handler isn't sufficient?

**Comment by kevinchalet** [comment]
Because you can only have one `IAuthorizationMiddlewareResultHandler` per application, so if I replace the default one inside my library, I will potentially override the custom logic used by either another package or implemented by the developer using my library, which is not a nice thing to do.

**Comment by HaoK** [comment]
Right, its a basic extensibility point for the whole application

**Comment by kevinchalet** [comment]
Then we're back to my initial question: is this mechanism flexible enough?

Being able to return more details about why authorization failed has always been a recurring demand (https://github.com/aspnet/Security/issues/1359).

`IAuthorizationMiddlewareResultHandler` is probably a good start, but it requires that the developer implement custom logic to flow the authorization failure from the authorization stack up to the authentication handler (typically, by calling `Challenge` or `Forbid` with an `AuthenticationProperties` instance containing the error details). It would be much nicer if handlers writers could provide custom logic to handle this mapping logic, instead of relying on the end user to implement it manually.

It's also something that could be leveraged in the JWT handler developed by the ASP.NET team: let's say we eventually introduce a `ScopeRequirement` - which is now possible, as the format of `scope` is being standardized by https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-04. In this case, the JWT handler could easily return a 403 error with a `WWW-Authenticate` header containing the missing scope without requiring any custom code.

**Comment by HaoK** [comment]
Right, its just the initial starting point, something more complicated is out of scope for 5.0 most likely unless you wanted to take a stab at a PR

**Comment by TheName** [comment]
I don't feel being an expert on the topic but that sounds like a good idea to me.
But it'd be easier to tell if we saw some code in a PR :) 

For now I don't need that myself (the current solution is enough for my use-cases) and so I don't plan to prepare that PR myself but I'd happily see the implementation of that idea :) 
Maybe in some time I could try helping out with a PR, so please do notify if you'll start working on it @kevinchalet so we don't duplicate the work :)
