### ISSUE TITLE
Consider preventing usage of 2.2 on .NET Framework

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/aspnetcore#22711]
Currently, when adding an ASP.NET Core package to a project targeting .NET Framework using `dotnet add package` or Visual Studio, 2.2 is installed by default. Also, Visual Studio offers 2.2 as an upgrade to 2.1. This is because 2.2 is the latest version that works on .NET Framework.

I think this is undesirable and 2.1 should be offered instead, because 2.2 is out of support and 2.1 is not (see https://dotnet.microsoft.com/platform/support/policy/dotnet-core).

I think a solution could be to delist the 2.2 packages from NuGet.

**Comment by Pilchie** [comment]
@blowdart - you were looking into NuGet's obsoletion support.  Is this a scenario that is covered by that?

**Comment by blowdart** [comment]
No it is not.

**Comment by davidfowl** [comment]
cc @DamianEdwards

**Comment by JunTaoLuo** [comment]
@DamianEdwards @Pilchie who should we follow up with in order to figure out what we can do here?

**Comment by Pilchie** [comment]
@aortiz-msft - Do you know what options exist here?  Basically we have a set of packages, with versions:

2.1 -> 2.2 -> 3.0 -> 3.1

Where:

1. 2.1 is in support, 
2. 2.2 is out of support.
3. 3.0 is out of support.
4. 3.1 is in support, but supports .NET Core only.

The problem is that we'd like people using .NET Framework to stay on 2.1, instead of being pushed toward packages that are out of support.

Is there a way to do this today?  If not, what's the right way to request this as a feature?

**Comment by aortiz-msft** [comment]
The best path forward would be to publish a 2.3 version which is in support, but unlisting 2.2 from NuGet.org may be an option as well. NuGet packages follow semver versioning, so greater versions are always considered better than previous ones. 

cc @anangaur

**Comment by Pilchie** [comment]
These packages follow the .NET Core versioning story and lifecycle, so we won't be publishing a 2.3 or any newer versions that support .NET Framework.

Unlisting is a *potential* option, but we still see quite a large number of people using these, so we're concerned about something that drastic.  We're looking for a way to stop new people from adopting 2.2, while slowly moving people who are already using it off, not a drastic shock to all those using 2.2.

**Comment by wtgodbe** [comment]
@Pilchie do we have a story yet for customers who are affected by this behavior? Should we document that the version we suggest is 2.1 somewhere?

**Comment by DamianEdwards** [comment]
We could consider publishing 2.2.x versions of the packages that produce a build warning detailing that it's out of support. The warning can always be suppressed by people who wish to keep using it.

Also it seems NuGet supports a "legacy" or even "custom" reason for deprecation and provides for pointing to an alternate package and version along with a custom message to show to the user. Is there a reason we couldn't do that, deprecating the earlier versions and setting the alternate package to the supported version?

![image](https://user-images.githubusercontent.com/249088/110546553-7bed1a80-80e3-11eb-95e2-697cdba1f000.png)

**Comment by anangaur** [comment]
There is no build warning generated for deprecated packages. It shows up on package details page on nuget.org and VS PM UI for `installed` packages. Deprecation has always been thought off as informational in nature and not a build warning.

Deprecating and unlisting may be useful here. /cc: @JonDouglas

**Comment by DamianEdwards** [comment]
I had imagined the deprecation would at least show up in all places an **install** occurs. It seems somewhat toothless today without that. That would effectively make it a more instructional/friendly form of unlisting. Are there any plans to make advancements on where deprecation shows up?

**Comment by anangaur** [comment]
We are exploring options to improve the vulnerability story to show it at multiple places including at the time of restore. Deprecation can follow similar lead if required. May be informational by default, warning/error under an option. Good feedback for the next phase of this work. @JonDouglas
