### ISSUE TITLE
Allow inheriting classes for Microsoft.AspNetCore.Components.EventCallback

### ISSUE THREAD

**Issue by sean-mcl** [dotnet/aspnetcore#22718]
Hi,

i am currently trying to make a two-way binding to a component in blazor.
The data property uses the interface "IList<T>" as output type. (T now replaces any type).

```
[Parameter]
public IList<T> Data { get; set; }
[Parameter]
public EventCallback<IList<T>> DataChanged { get; set; }
```

**Whats not working:**

```

<Component @bind-Data="data"/>

List<T> data = new List<T>
{
    ...
};

// In component
await DataChanged.InvokeAsync(Data);
```
`CS1503: Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<System.Collections.Generic.List<T>>' to 'Microsoft.AspNetCore.Components.EventCallback'`

**Unfortunately, you must explicitly specify the interface type IList<T> for the event callback.**

```
IList<T> data = new List<T>
{
    ...
};
```

It would be good if the EventCallback would be a bit more tolerant there.

Related workitems: #15101

Thanks again for your great work!

Sean

**Comment by TanayParikh** [comment]
Hi. Thanks for contacting us. We're closing this issue as there was not much community interest in this ask for quite a while now. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
