### ISSUE TITLE
Obsolete v1 aad classes once v2 templates and libraries are available

### ISSUE THREAD

**Issue by blowdart** [dotnet/aspnetcore#22726]
Because we want to move folks. This is a tracking issue.

**Comment by blowdart** [comment]
Also look at microsoft account package

**Comment by JunTaoLuo** [comment]
This depends on https://github.com/dotnet/aspnetcore/issues/24024.

**Comment by JunTaoLuo** [comment]
FYI for future reference the work was done completed via two PRs: https://github.com/dotnet/aspnetcore/pull/24167 and https://github.com/dotnet/aspnetcore/pull/24268
