### ISSUE TITLE
Add DDRITs integration tests for Razor Codespaces scenarios

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22720]
We need to add integration tests that run on every VS insertion that verify the Razor experience.

Codespaces integration tests: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2FTests%2FNexus

**Comment by ajaybhargavb** [comment]
[PR for this](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/257587)

**Comment by ajaybhargavb** [comment]
The PR is now merged.
