### ISSUE TITLE
Examine Yarn.MSBuild for performance issues

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22723]
- source is in https://github.com/natemcmaster/Yarn.MSBuild
- according to @mmitche this SDK is a significant source of extraneous logging and slowdown in the aspnetcore-ci pipeline
    - @mmitche please some details on what you've seen to this issue
- in https://github.com/dotnet/aspnetcore/pull/22703#issue-431797138, @javiercn noted we can't use the task invocation to suppress specific warnings and this potentially hides issues we introduce in the future

**Comment by dougbu** [comment]
@Pilchie we don't really have `yarn` expertise on the build v-team. Should we track this in DoI?

**Comment by Pilchie** [comment]
@mkArtakMSFT - can your team take a look and see what can be done to help speed up our builds here?

**Comment by javiercn** [comment]
[This](https://classic.yarnpkg.com/en/docs/workspaces/) might be a thing we can leverage  to run yarn install once instead of N times.

**Comment by dougbu** [comment]
We may be able to do something here but I defer to @mkArtakMSFT and his team on whether the larger org ever gets to it. @dotnet/aspnet-build likely will not have time to do more than review the good work @mkArtakMSFT's team does.

**Comment by mkArtakMSFT** [comment]
There isn't anything specific here to act on now, instead we should brainstorm and come up with ways to speed this up, which we can do any time in the future too. Closing for now, as we have no plans to do such investigation now.

**Comment by javiercn** [comment]
I think we should consider this as part of infrastructure improvements and move away from Yarn in favor of going back to plain old npm.
