### ISSUE TITLE
16.7-Preview3 - Validate Razor tooling in Visual Studio Codespaces

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22728]
## Instructions
It's up to you to validate all features, if applicable, done in the [16.7-preview3](https://github.com/dotnet/aspnetcore/milestone/108?closed=1) (not just your own). Given that this is tooling validation, features and bug fixes should be relatively easy to validate given they don't require complex setups to ensure something works.

As part of this process don't be afraid to experiment outside the context of the issues within the milestone.

## Filing issues
All issues found should be filed under the **Razor.Tooling** milestone and assigned to the **Razor Tooling vNext** project. Lastly give those issues the appropriate labels and mention them under this issue before closing.

## Completing validation

Once you're done with your validation, link to any issues found and unassign yourself from this issue. If you are the last to unassign yourself close the issue and move it to the "Done" column in the Razor Tooling vNext project.

## Validation Build

**Visual Studio Client Release:** 

1. Install the "Preview" channel version in the "Extensions" tab https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3808656&view=results

![image](https://user-images.githubusercontent.com/2008729/84837336-b6120b80-afec-11ea-94b4-a91d1682515f.png)

Ensure the .NET Core workload is checked:

![image](https://user-images.githubusercontent.com/2008729/84843730-8cadab80-affd-11ea-91a6-e01fec0bcbf2.png)

2. Check the "Connect to Visual Studio Codespaces (private preview only)" preview feature checkbox
![image](https://user-images.githubusercontent.com/2008729/84837845-e908cf00-afed-11ea-9c79-e6c59fb2b81f.png)

**Visual Studio Server Release:** Use the 
![image](https://user-images.githubusercontent.com/2008729/84837275-8fec6b80-afec-11ea-8224-7e34098f0c40.png)

**Comment by NTaylorMullen** [comment]
Pinging here in case you missed on teams as well. Time for validation @ajaybhargavb @ryanbrandenburg @TanayParikh

**Comment by NTaylorMullen** [comment]
Finished my validation! Thanks @TanayParikh for your [comment](https://github.com/dotnet/aspnetcore/issues/21631#issuecomment-645065025), it saved me 😄

**Comment by TanayParikh** [comment]
Finished validations.

- https://github.com/dotnet/aspnetcore/issues/22120
Expected:
```
@if (true)
{
    |
}
```
Actual:
![222120](https://user-images.githubusercontent.com/14852843/84930844-c1197a00-b086-11ea-9033-714aa9f26ef0.gif)

**Comment by ajaybhargavb** [comment]
Finished my validation

**Comment by ryanbrandenburg** [comment]
Verified all, with 1 hiccup, when you do Open->Project/Solution it doesn't show csproj files as an option.
![image](https://user-images.githubusercontent.com/14987221/84965338-87b32f80-b0c3-11ea-894b-a3379975062b.png)

![image](https://user-images.githubusercontent.com/14987221/84965304-6b16f780-b0c3-11ea-90c3-c0fcd4d35f80.png)
