### ISSUE TITLE
Parameterize TFM from `net5.0` -> to `$(TargetTfm)`

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22737]
- so that we don't have to change 100s of files and we can work concurrently on `net6.0`

**Comment by dougbu** [comment]
Issue here it the number of hard-coded TFMs in `*.cs` and `*.nuget` and so on. Might even be able to reduce what's hard-coded in the project template files.

**Comment by pranavkm** [comment]
@dougbu is this still a thing now that we have a 6.0 branch?

**Comment by dougbu** [comment]
This isn't related to how we're branded or branching, it's about our default TFM and how many times it appears in our source code.

Bottom line, we'll do this while switching to target `net6.0`.

**Comment by Pilchie** [comment]
@dougbu should we update the milestone here?

**Comment by dougbu** [comment]
Yes, it's not mandatory for 5.0 and definitely not for RC1. Moved this to 6.0 because that's where we need to deal with `net6.0`.

**Comment by dougbu** [comment]
@halter73 please include this issue in your hand-off notes to @TanayParikh

**Comment by wtgodbe** [comment]
This was done a while ago
