### ISSUE TITLE
Fix warning "##[warning]SetCookieHeaderValueTest.cs(423,67): warning CS8600: (NETCORE_ENGINEERING_TELEMETRY=Build) Converting null literal or possible null value to non-nullable type."

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22733]
Happens in main product build

> ##[warning]SetCookieHeaderValueTest.cs(423,67): warning CS8600: (NETCORE_ENGINEERING_TELEMETRY=Build) Converting null literal or possible null value to non-nullable type.

Part of https://github.com/dotnet/aspnetcore/issues/22240

**Comment by wtgodbe** [comment]
@Tratcher @jkotalik @BrennanConroy seems to be related to https://github.com/dotnet/aspnetcore/pull/22181

**Comment by Tratcher** [comment]
Yeah, that PR was developed in parallel to the nullability changes and then merged.

**Comment by wtgodbe** [comment]
@Tratcher so is this already fixed?

**Comment by Tratcher** [comment]
No

**Comment by BrennanConroy** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/22838
