### ISSUE TITLE
No completion for <ul> tag

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22749]
![uy9whj9Av6](https://user-images.githubusercontent.com/1874516/84211928-632ad800-aa71-11ea-9e80-5df112c0ab22.gif)

Workaround:

- Closing and reopening VS made intellisense start working again.

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by NTaylorMullen** [comment]
This looks like a transient failure of the language server. If you're able to get the activity log for this that's help loads!

**Comment by danroth27** [comment]
[ActivityLog.zip](https://github.com/dotnet/aspnetcore/files/4755532/ActivityLog.zip)

**Comment by danroth27** [comment]
Here's roughly what I did to repro this issue:

- Create a new Blazor WebAssembly app
- Add *Todo.razor* to the *Pages* folder
- Close and reopen *Todo.razor* so colorization kicks in
- Define a `TodoItem` class at the root of the project
- In *Pages/Todo.razor* add the following field in the `@code` block: `List<TodoItem> todos = new List<TodoItem>`
- Close and reopen *Todo.razor*. At this point intellisense was broken for me.

**Comment by NTaylorMullen** [comment]
Figured this out. It's a combination of https://github.com/dotnet/aspnetcore/issues/22837 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1127327
