### ISSUE TITLE
Incorrect indentation in @code block when adding a newline after a member with a generic type

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22748]
![RiQFnF6Bm4](https://user-images.githubusercontent.com/1874516/84211803-10e9b700-aa71-11ea-8231-d58645412956.gif)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by NTaylorMullen** [comment]
This is most likely due to the generics on line 6. We need to start utilizing sub-language language-configuration.json's to workaround this.
