### ISSUE TITLE
Property snippet not working

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22744]
![V1U0xHUEu2](https://user-images.githubusercontent.com/1874516/84210751-640e3a80-aa6e-11ea-9861-4ba977d1f265.gif)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by kevinjpetersen** [comment]
I have this exact same issue with VS 2019 16.11 Preview 2 using WPF BlazorWebView (.NET 6 Preview 4). I've posted an issue on the Visual Studio Issue Tracker: https://developercommunity.visualstudio.com/t/Code-Snippets-doesnt-work-in-code-bloc/1453416

**Comment by NTaylorMullen** [comment]
lol I'm actually super surprised you're getting that snippet at all

**Comment by NTaylorMullen** [comment]
`prop` snippet now works with single tab-completion.
