### ISSUE TITLE
Potential race in SiteExtensions build

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#22741]
https://dev.azure.com/dnceng/internal/_build/results?buildId=678577&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=1b89928a-2219-5ef9-602f-f95beb3da4dc

There are hundreds of errors like:

> ##[error]atls.lib(stdafx.obj)(0,0): error LNK2001: (NETCORE_ENGINEERING_TELEMETRY=Build) unresolved external symbol "void __cdecl operator delete(void *)" (??3@YAXPAX@Z)

The issue seems to be that the build tries to create the 32 bit .dll for `aspnetcorev2_inprocess.lib` more than once.

CC @jkotalik @mmitche @dougbu

**Comment by wtgodbe** [comment]
> Creating library F:\workspace\_work\1\s\artifacts\bin\InProcessRequestHandler\Win32\Release\aspnetcorev2_inprocess.lib and object F:\workspace\_work\1\s\artifacts\bin\InProcessRequestHandler\Win32\Release\aspnetcorev2_inprocess.exp 

This line shows up in failing builds, but not green builds. This is despite the library being built earlier:

>  Creating library F:\workspace\_work\1\s\artifacts\bin\InProcessRequestHandler\Win32\Release\aspnetcorev2_inprocess.lib and object F:\workspace\_work\1\s\artifacts\bin\InProcessRequestHandler\Win32\Release\aspnetcorev2_inprocess.exp

**Comment by jkotalik** [comment]
Hopefully fixed by https://github.com/dotnet/aspnetcore/pull/22738.

**Comment by jkotalik** [comment]
Closing as fixed, let's reopen if we see the failure again.
