### ISSUE TITLE
Committing C# completion removes not operator (!)

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22752]
![nCkSI24b1w](https://user-images.githubusercontent.com/1874516/84212753-93737600-aa73-11ea-886b-b849536e9e0f.gif)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by NTaylorMullen** [comment]
@TanayParikh can you see if this is a variant of the brackets issue?

**Comment by NTaylorMullen** [comment]
Also, can you add curly braces to the list if they aren't there already to avoid that as well

**Comment by danroth27** [comment]
Here's an example of when a trailing curly brace gets removed:

![eWX0WVgEX2](https://user-images.githubusercontent.com/1874516/84213002-5e1b5800-aa74-11ea-96a6-11737cb8e530.gif)

**Comment by TanayParikh** [comment]
> Here's an example of when a trailing curly brace gets removed:
> 
> ![eWX0WVgEX2](https://user-images.githubusercontent.com/1874516/84213002-5e1b5800-aa74-11ea-96a6-11737cb8e530.gif)

https://github.com/dotnet/aspnetcore-tooling/pull/2002/commits/a56166ce61b4a6dc4da7f53d6bc68003bd680f0a

**Comment by TanayParikh** [comment]
> @TanayParikh can you see if this is a variant of the brackets issue?

Yep, fixed via https://github.com/dotnet/aspnetcore-tooling/pull/2002/commits/84d76835d270b500de032369b309eef991c57aaa

However, at this point, I feel like we're really overloading the `AllCommitCharacters` May be worth considering expanding the spec to better account for these characters?

**Comment by NTaylorMullen** [comment]
> However, at this point, I feel like we're really overloading the `AllCommitCharacters`. May be worth considering expanding the spec to better account for these characters?

Maybe, these are technically C# commit characters though
