### ISSUE TITLE
Asp.Net Core 3.1 JWT authorization : return Unauthorized (HTTP 401) 

### ISSUE THREAD

**Issue by ashokswain27** [dotnet/aspnetcore#22763]
Trying to secure the API with Azure AD. Please refer the belwo code snippet. It's a;ways using the 401 unauthorized. I have validated the token using jwt.io and compare the values while debugging.
It's returning the correct values for the issuer and audience.

### Describe the bug
Code snippet:
startup.cs:
```
// Add Authentication and authorization
services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
.AddJwtBearer("AzureAD", options =>
{
    options.Audience = Configuration.GetValue<string>("AzureAd:Audience");
    options.Authority = Configuration.GetValue<string>("AzureAd:Instance") + Configuration.GetValue<string>("AzureAd:TenantId");                 

    options.TokenValidationParameters = new TokenValidationParameters()
    {
        ValidIssuer = Configuration.GetValue<string>("AzureAd:Issuer"),
        ValidAudience = Configuration.GetValue<string>("AzureAd:Audience")
    };
}); 

Controller.cs:
 [Authorize(AuthenticationSchemes = AzureADDefaults.AuthenticationScheme)]
public class TestController : ControllerBase
{
}
```

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) : Visual studio 2019

**Comment by cmatskas** [comment]
Please note that ASP.NET Core has now a new library that makes creating protected APIs really easy to set up using the Microsoft.Identity.Web. You can find more info here https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis

**Comment by ashokswain27** [comment]
I am unable to track the debug logs? I tried to debug multiple times, it's automatically redirected to 401 error.

**Comment by blowdart** [comment]
The debug logs would appear in the VS output window.

**Comment by ashokswain27** [comment]
This is the error message in debug output wundow:

"message": "IDX20803: Unable to obtain configuration from: 'System.String'.",
    "type": "InvalidOperationException",
    "source": "Microsoft.IdentityModel.Protocols",
    "raw": "   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)\r\n   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)"
  }

**Comment by blowdart** [comment]
This seems to indicate that there are problems getting the metadata for your provider. Either the address is wrong, or you're blocking outbound connections. If it can't get the metadata it can't validate.

But like everyone else I'd advise looking at [Identity.Web](https://github.com/AzureAD/microsoft-identity-web)

**Comment by ashokswain27** [comment]
Yes, using the Identity.web code worked fine. I thought as it is preview mode, it should not be used. Thanks!

**Comment by blowdart** [comment]
It'll be out of preview in a couple of months as soon as we can onboard it into the templates :)

As you're up and running I'm going to close this. If you have problems with Identity web you can of course raise it in their repo.
