### ISSUE TITLE
Finally a chance to get rid of claim type mappings!

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/aspnetcore#22764]
With the 6.x release of the MS JWT handler, the mapping of artisanally crafted, spec-compliant claim types to their WS-* counterparts from the late 90ies is finally gone!

That means you can now get rid of this behavior in your OIDC and JWT handlers for v5! That's great!

I can totally understand that this is a breaking change, and you probably want to keep the wrong behavior by default for a little while. But maybe a simple opt-out switch is now possible? 

e.g.
```
// behave like a claims-based gentleman (defaults to false though)
options.LeaveMyClaimTypesAloneFfs = true;
```

Alternatively maybe

```
options.ClaimsActions.Clear();
```

Also imagine how many backlog issues you can finally close that are related to that problem. It's a win-win.

**Comment by damianh** [comment]
Kill it with 🔥

**Comment by blowdart** [comment]
We need to check for breaking changes other than this first.

@Tratcher to evaluate compat of the new version.

**Comment by chriskuech** [comment]
>defaults to false though

Considering how hard it is to bump the major version of .NET in legacy applications, defaulting to `false` will definitely prevent more headaches than defaulting to `true`.

**Comment by Tratcher** [comment]
@HaoK ready to close?

**Comment by HaoK** [comment]
As long as we aren't planning on doing any additional flags or clearing of defaults?

**Comment by Tratcher** [comment]
We'll let folks try the nightly or preview and see how disruptive it is for them.

@leastprivilege @damianh @kevinchalet

**Comment by HaoK** [comment]
We decided to add a new option on JwtBearerOptions that will allow setting MapInboundClaims

**Comment by HaoK** [comment]
There's now a new MapInboundClaims option on both Oidc and Jwt options which just set the flag on the default instance of the jwtsecuritytokenhandler
