### ISSUE TITLE
blazor 3.2.0 - add scaffolded item

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#22772]
Hi, I think for the webassembly template, adding a scaffolded item is not working properly. I would like to customize the login, for example.

InvalidOperationException: The following sections have been defined but have not been rendered by the page at ‘/Areas/Identity/Pages/Account/Manage/_Layout.cshtml’: ‘Scripts’. To ignore an unrendered section call IgnoreSection(“sectionName”).

several items are added, which I see as unnecessary. even deleting all that excess, I can’t get it to work.

in the previous stable version it still worked.

**Comment by danroth27** [comment]
Duplicate of https://github.com/dotnet/Scaffolding/issues/1325
