### ISSUE TITLE
Use containers for all Linux builds and tests

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22788]

**Comment by JunTaoLuo** [comment]
Keeping this open to track tests

**Comment by dougbu** [comment]
@HaoK is this still a big deal on the Helix side❔ Now that Core-Eng provisions agents so dynamically, I doubt using a single kind of Linux Helix agent would matter that much but want to confirm.

**Comment by HaoK** [comment]
I'm not sure exactly what this issue is tracking, I know @javiercn mentioned a long term idea of moving our builds/tests to working against a docker container so everything is preinstalled and we can just run it on helix queues.

**Comment by dougbu** [comment]
Not a huge deal and will likely mean creation of more images for us or Core-Eng to manage
