### ISSUE TITLE
CSS isolation: Template updates

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#22781]
This is one of the work items needed for #10170

Once all the other functionality is implemented, we need to update the project templates:

 * In all Blazor app types (Blazor Server, Blazor WebAssembly standalone + hosted) we want to update the host page so it includes `<link rel=Stylesheet href=_framework/style.css>` (or whatever URL we turn out to be using for the output from https://github.com/dotnet/aspnetcore/issues/22779)
 * For the RCL template, we should replace the existing `.css` example in `wwwroot` with the use of isolated CSS (`Component1.razor.css`).

**Comment by CodeChaser** [comment]
Thanks I was just looking for this and found that adding "<Link href="custom.razor.css" > does not work.  Look forward to this feature..

Tom
