### ISSUE TITLE
VS LSP: No html intellisense after closing and reopening Razor file

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#22791]
Steps:
- Get the latest VS Master
- Open a Blazor project and open Counter.razor
- Verify html intellisense works
- Close and reopen the file

Expected:
Everything still works

Actual:
Only tag helper intellisense is shown
![image](https://user-images.githubusercontent.com/1579269/84304701-c0746700-ab0d-11ea-99da-d0c747891676.png)

**Comment by ajaybhargavb** [comment]
Looks like the LSP platform team is aware of this and are working on a fix. I'll link the tracking issue here when I have it.

**Comment by ajaybhargavb** [comment]
[External tracking issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1128482)

**Comment by NTaylorMullen** [comment]
Fixed!
