### ISSUE TITLE
default route cannot match up url like "https://localhost:5001//?id=123",it will return to 404

### ISSUE THREAD

**Issue by aaa930811** [dotnet/aspnetcore#22809]
### Describe the bug
default route cannot match up url like "https://localhost:5001//?id=123"  ,it will return to 404,but it work well in aspnet mvc.Is it my routing problem?

`             app.UseEndpoints(endpoints =>`
          `  {`
            `    endpoints.MapControllerRoute(`
                  `  name: "default",`
              `      pattern: "{controller=Home}/{action=Index}/{id?}");`
            `});`

### Further technical details
- ASP.NET Core version 3.1

**Comment by javiercn** [comment]
@aaa930811 thanks for contacting us.

This might be a subtle difference between old ASP.NET and ASP.NET Core. 

It might be due to the server parsing the original Url differently or due to endpoint routing interpreting `//` as `Controller=''` in which case the 404 is expected.

**Comment by aaa930811** [comment]
What should I do if I want to be compatible with this double slash link?Our business includes a batch of QR codes with double slash links.

**Comment by javiercn** [comment]
@aaa930811 you can rewrite the url before it hits routing to make it match.
