### ISSUE TITLE
Curly Brace Range Highlighting

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#22804]
This issue tracks adding support for highlighting opening/closing braces in an VS LSP powered context.

Example of end result (as seen in VS Code):
![RangeHighlighting](https://user-images.githubusercontent.com/14852843/84329109-a2702c00-ab38-11ea-8627-d5e352dc2608.gif)

Related Roslyn Issue: https://github.com/dotnet/roslyn/issues/45062

FYI: @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Done actually 😄
