### ISSUE TITLE
Blazor - Issue Rendering NavMenu When Shared Folder Is Moved

### ISSUE THREAD

**Issue by MrOldham101** [dotnet/aspnetcore#22800]
Summary:

I have found that when you start moving the standard blazor template folder structure around you start to experience some weird behaviour, particularly with the shared folder. 

Steps:
1. Create a new blazor app using the standard template. 
2. Create a "Views" folder and move the "Shared" and "Pages" folders into the "Views" folder
3. Amend your _imports.razor so that it is using BlazorApp.Views.Shared
4. Amend the razor pages root by adding this line to your Startup.cs in the ConfigureServices function: services.Configure<RazorPagesOptions>(options => options.RootDirectory = "/Views/Pages");
5. Build and run your app

Issue:

The page will be rendered as expected apart from the NavMenu. This does not render at all even though the page body and the SurveyPrompt component (which is located in the shared folder right next to the NavMenu) renders perfectly. Furthermore, there are not IntelliSense errors or any other errors across the entire app.

EDIT -- I have just found that when inspecting the page and emulating a mobile screen ( so that the menu collapses ) the NavMenu renders perfectly.

**Comment by javiercn** [comment]
@MrOldham101 thanks for contacting us.

It is likely that you are missing some step in the transformation. If you produce a full repro we can take a look, but it is unlikely that there is an issue here, since components aren't affected by the location on disk (other than their namespace)

**Comment by MrOldham101** [comment]
> @MrOldham101 thanks for contacting us.
> 
> It is likely that you are missing some step in the transformation. If you produce a full repro we can take a look, but it is unlikely that there is an issue here, since components aren't affected by the location on disk (other than their namespace)

I thought that at first until I was able to duplicate the behaviour on both my Mac and on my PC. The component just does not render when it is not collapsed

**Comment by pranavkm** [comment]
Thanks for the issue report @MrOldham101 . We think this might be an issue with your application and this question is better suited for StackOverflow. If you think it's an issue with the framework, please file a new issue demonstrating why it's an issue with Blazor and we will investigate.
