### ISSUE TITLE
ServerPrerendered Blazor component in Razor pages doesn't serialize parameter correctly

### ISSUE THREAD

**Issue by jerome-raffalli** [dotnet/aspnetcore#22812]
> Visual Studio 2019 16.6.1
> .Net Core 3.1.4
> 
> Using ServerPrerendered the .razor component is initialized twice. First time correctly, the second time incorrectly.
> 
> I have the following folder layout:
> /Pages/Test/
> ./RazorShapeComponent.razor
> ./ShapeContainer.cs
> ./ShapeBase.cs
> ./ShapeTriangle.cs
> 
> /Pages/
> ./ShapeTest.cshtml
> ./ShapeTest.cshtml.cs
> 
> Where:
> ShapeTriangle extends ShapeBase
> ShapeContainer has a List of ShapeBase
> 
> RazorShapeComponent.razor takes a ShapeContainer Parameter
> [Parameter]
> public ShapeContainer ShapeContainer { get; set; }
> 
> ShapeTest.cshtml.cs has: ShapeContainer MyShapeContainer { get; set; }
> MyShapeContainer is instantiated in the ctor
> 
> and:
> ShapeTest.cshtml uses the RazorShapeComponent
> `<component type="typeof(RazorShapeComponent)" render-mode="ServerPrerendered" param-ShapeContainer='@Model.MyShapeContainer' />`
> 
> **Behaviour**
> Then RazorShapeComponent.razor's OnInitialized() is called twice.
> 
> The first time, the ShapeContainer parameter is initialized correctly
> ![image](https://user-images.githubusercontent.com/393349/83978082-4d989f80-a905-11ea-8c54-3cf667f4a8f3.png)
> 
> The second time, the List is initialized but contains instances of the base type
> ![image](https://user-images.githubusercontent.com/393349/83978148-c697f700-a905-11ea-8279-d5b7afe05f55.png)
> 
> [BugLog.zip](https://github.com/dotnet/aspnetcore/files/4742790/BugLog.zip)
> 
> Regards,
> Michael

Hello,
I encounter exactly the same problem as Michael. It was wrongly classified as a question, but this is a real issue.
Could you please reexamine it ?

This problem seams to be specific to ServerPrerendered mode, where components are initialized twice.
The first time, parameter is correctly deserialized, but second time the deserialization fails.

Workaround : serialize / deserialize complex types in a string parameter

Many thanks,
Jérôme

**Comment by javiercn** [comment]
@jerome-raffalli inheritance is not supported during prerendering.

Passing parameters during prerendering is subject to the limitations System.Text.Json imposes, among those, the lack of inheritance support.

As a result if you try to use inheritance the information in the derived type will be lost during deserialization.

This is not something that we plan to change; if you want to support this scenario you can do so by creating and applying your own converter following the docs [here](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#support-polymorphic-deserialization)
