### ISSUE TITLE
Blazor Get Current Page

### ISSUE THREAD

**Issue by imtrobin** [dotnet/aspnetcore#22817]
Hi, I like to get the current page object (not URL). Something like 

ComponentBase currentPage = Blazor.CurrentPage;

I need to do call a StateHasChanged to refresh it when I load in new localization.  I tried calling StateHasChanged on App.razor but it does propagate it down.

**Comment by javiercn** [comment]
@imtrobin thanks for contacting us.

There's no way to achieve that unless you pass down some delegate from the page itself to its child components. If you tell us more about your scenario we might suggest you a better option.

**Comment by imtrobin** [comment]
I'm loading localization data externally and storing it in a static variable. After it's loaded, I need to call notify all active pages StateHasChanged.

I store a static instance of the NavMenu, and that works, but not for the current active page.

**Comment by javiercn** [comment]
@imtrobin thanks for the details.

It's much easier if you use a cascading parameter to achieve this. When the language changes update the parameter and all interested components will be notified automatically.

See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#cascading-values-and-parameters) for details.

**Comment by imtrobin** [comment]
Thanks but I can't use casading parameter. It means all need to derive from the same base class, which is not in my case as I use different frameworks and third party libraries.
