### ISSUE TITLE
Uncaught RuntimeError: memory access out of boundsUncaught

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#22811]
### Describe the bug
![image](https://user-images.githubusercontent.com/5187024/84345699-9c358a80-abe0-11ea-95c0-0faa98379a96.png)

### Exceptions (if any)

stacktrace:
![image](https://user-images.githubusercontent.com/5187024/84346624-fe8f8a80-abe2-11ea-9a62-251bb04b83a0.png)

### Further technical details
- ASP.NET Core version: 3.2.0(WebAssembly)
- Include the output of `dotnet --info`: 3.14
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: vs2019 Version 16.6.1

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Brainykat** [comment]
Hi, am experiencing the same error
 
- ASP.NET Core version: 3.2.0(WebAssembly)
- Windows Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 3.1
- PWA app option checked

**Visual studio output** 
Debugging hotkey: Shift+Alt+D (when application has focus)
 Loaded 6.39 MB resources
This application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
Loaded 0.87 MB resources from cache
Loaded 5.52 MB resources from network
Uncaught RuntimeError: memory access out of boundsUncaught RuntimeError: memory access out of bounds mono_wasm_get_loaded_files
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28

**Comment by Brainykat** [comment]
@mkArtakMSFT

**Comment by srxqds** [comment]
I think create large string cause the problem in our project.

**Comment by Brainykat** [comment]
@srxqds Please expound  

> I think create large string cause the problem in our project.

**Comment by Brainykat** [comment]
Resolved the error.
I was using js interloop to store tokens in browser local storage
Closing the app without logging out i was not destroying my cookie in browser local storage
This somehow brought the above error
Clearing the Token memory on application end fixed this with subsequent runs
