### ISSUE TITLE
CORS middleware does not return Access-Control-Allow-Origin in response

### ISSUE THREAD

**Issue by NguyenCu** [dotnet/aspnetcore#22814]
I have added CORS middleware as in https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1

```
.AddCors(options =>
                {
                    options.AddPolicy("TestPolicy",
                        builder => builder.AllowAnyOrigin()
                            .AllowAnyHeader()
                            .WithMethods("GET"));
                })

app
                .UseRouting()
                .UseCors(_gatewayPublicPolicy)
                .UseEndpoints(endpoints => { endpoints.MapControllers(); });
```
When I call the API with 'Origin: *' in the request header, I receive Access-Control-Allow-Origin: * in the response header. 
But it I remove the Origin in the request header, then I do NOT have Access-Control-Allow-Origin in the response header any more.

To relax the CORS, we want to return Access-Control-Allow-Origin: * all the time regardless the requests. I have tried a lot of combination but never get it work! 

How could CORS always return Access-Control-Allow-Origin: *?

**Comment by javiercn** [comment]
@NguyenCu thanks for contacting us.

CORS is triggered based on the existence of the Origin header in the request, returning the response headers all the time is not a feature we have nor something we have intention to support. The browser will always send the Origin header and CORS it is meant for browsers, so I'm not sure why you would ever want to send CORS headers in the response without having received the Origin header in the request.

**Comment by javiercn** [comment]
@NguyenCu if you insist on doing this, you can write your own middleware that always appends the headers to the response, but it is not something I would recommend. Finally, for this to be useable in any way (which it isn't) you would also need to send other related CORS headers, not just Access-Control-Allow-Origin on the response.
