### ISSUE TITLE
IIS MaxRequestBodySize maxes at 2 GB instead of 4 GB.

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#22834]
https://github.com/dotnet/aspnetcore/blob/aaaaf572fdf11088ee0efd205ff6834e16a36804/src/Servers/IIS/IIS/src/Core/IISConfigurationData.cs#L22

This uses an int instead of a uint which causes the limit to default to 2 GB instead of 4 GB if the max value is specified.

**Comment by davidfowl** [comment]
Why backlog?

**Comment by jkotalik** [comment]
I get confused between backlog and next sprint planning.
