### ISSUE TITLE
Microsoft.dotnet-openapi dotnet tool require the highest Microsoft.NETCore.App version

### ISSUE THREAD

**Issue by wli3** [dotnet/aspnetcore#22835]
### Describe the bug
Microsoft.dotnet-openapi dotnet tool require the highest Microsoft.NETCore.App version.

In the package's runtimeconfig.json. It requires the highest Microsoft.NETCore.App version 3.1.5. That means if the user have 3.1.0-3.1.4, they cannot run it. [A report from twitter](https://twitter.com/thenickrandolph/status/1271104784007696391/photo/1).

Is there any reason to set it to the highest? If you use `PackAsTool=true`. SDK should set it to the most compatible runtime version. In most of the case, "Major.Minor.0", unless there is a security issue. The same logic will run for publishing `selfcontain=false`.

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.5"
    }
  }
}
```

### To Reproduce
Have a machine with 3.1.0 runtime. Install the tool. And it cannot run.

**Comment by captainsafia** [comment]
Closing this since the issue is resolved in .NET 6.0 and above and 3.1 is out of support.
