### ISSUE TITLE
Intellisense deletes my code and binding attributes in razor file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22841]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1057571/intellisense-deletes-my-code-and-binding-attribute.html)._

---
Hi,

If i click on a intellisense list item in a razor file, then my code and my binding attributes is deleted. (As can seen on the attached video)

Regards,
 Peter

---
#### Visual Studio Feedback System on 5/31/2020, 09:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/3/2020, 00:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our efforts in moving our Razor tooling over to an LSP powered model.

This should light up in the .NET 5 time frame.
