### ISSUE TITLE
Add support for push authentication

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#22845]
I would like users to be able to login using push authentication. So that when the user is in the process of logging in on the website, the user gets sent a push notification to the user's authenticator app (such as Microsoft Authenticator) on the user's mobile device. The user would be presented with a choice to either accept or deny the request.

**Comment by blowdart** [comment]
Given that there's no standard for this, and every authenticator app uses their own method this isn't something we'd consider.

**Comment by vanillajonathan** [comment]
Here goes some ramblings...

The web application needs to communicate to the client (the web browser) that it has received information about whether the user (through the authenticator app) has either approved or denied the authentication request. This can be done either through HTTP request polling or using a WebSocket connection.

The disadvantage of using a WebSocket is that it is not possible to send any HTTP headers, so you cannot send the authentication cookie, so you have to inform the browser that the authentication request has been approved and that the browser should perform a HTTP request to an endpoint which will login the user and set the authentication cookie.

The approach taken by login.microsoftonline.com is to use HTTP request polling.
The browser would poll an endpoint every second or so, and after a minute or so give up and stop polling and present information to the user that the authentication request has timed out.

The authenticator app would get the authentication request through push notifications using a hosted service such as [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/) (FCM), [Apple Push Notification service](https://developer.apple.com/notifications/) (APNs), or [Windows Push Notification Service](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview) (WNS).

If a custom authenticator app is used then the ASP.NET application would directly call the push notification service to send the authentication request to the authenticator app.
If a general-purpose authenticator app (such as Microsoft Authenticator, Google Authenticator, [Authy](https://www.twilio.com/docs/authy/api/push-authentications), [Auth0](https://auth0.com/docs/mfa/guides/configure-push), etc) is used the ASP.NET application would do a HTTP POST request to a authentication service provider which in turns uses makes use of a push notification service to send the authentication request.

The HTTP POST request would need to contain a correlation id and a user identifier (such as perhaps an email address) that the push notification service can use to communicate with the device(s) subscribing to push notifications. It needs to either send a code that it generates on the device using the [authenticator key](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.userstorebase-5.getauthenticatorkeyasync?view=aspnetcore-3.1) or receive a token that it sends back (as is done when sending a token over SMS or email).

```cs
[HttpGet]
public async Task<IActionResult> Authenticate(AuthenticationModel model)
{
    await NotifyAuthenticatorAsync(model.UserId, model.CorrelationId, model.CancellationToken);
    // Tell the client to wait for the response...
    return Ok();
}

private async Task NotifyAuthenticatorAsync(string userId, string correlationId, CancellationToken cancellationToken)
{
    var content = new AuthenticationRequest {
        UserId = userId,
        CorrelationId = correlationId
    };
    await _client.PostAsJsonAsync("https://api.auth.example/push", content, cancellationToken);
}

[HttpPost]
public async Task<IActionResult> AuthenticationResponse(AuthenticationResponseModel model)
{
    // Look up model.CorrelationId
    // Check if model.Status is "Approved" or "Denied".
    var user = await _userManager.FindByNameAsync(model.UserId);
    var result = await _userManager.VerifyTwoFactorTokenAsync(user, TokenOptions.DefaultAuthenticatorProvider, model.Code);
    return Ok();
}
```

```http
POST /push HTTP/1.1
Host: api.auth.example
Authorization: Bearer ACCESS_TOKEN
Content-Type: application/json

{
  "UserId": "alice@example.com",
  "CorrelationId": "11c43ee8-b9d3-4e51-b73f-bd9dda66e29c"
}
```

If you want to use a poll endpoint.
```cs
[HttpGet]
public async Task<IActionResult> AreWeLoggedInYet(Guid correlationId)
{
    if (_service.AreWeLoggedInYet(correlationId))
    {
        await _signInManager.TwoFactorAuthenticatorSignInAsync(code, false, false);
        return Ok("Yes!");
    }
    return Ok("No, but keep asking...");
}
```

Once the user chooses to approve or deny the authentication request the authenticator app could either send a HTTP POST request back directly to a endpoint on the ASP.NET application or to an authentication provider that in turn relays back that information to the ASP.NET application.

When the ASP.NET application has received information that the action taken on the  authentication request was to approve the request and verified that the attached code/token is valid it can use the `SignInManager` to login using [`SignInManager.TwoFactorSignInAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.twofactorsigninasync?view=aspnetcore-3.1) or [`SignInManager.TwoFactorAuthenticatorSignInAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.twofactorauthenticatorsigninasync?view=aspnetcore-3.1) depending on if you verify a token or a TOTP code.
