### ISSUE TITLE
Raise event when browser is resized.

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22852]
There can be cases where when the browser is resized, then needs to raise an event that somebody can run the code StateHasChanged.
Because there can be cases where when browser is resized, then the font sizes of something may have to be different.  Its also possible that positionings may change based on the new browser size.  Otherwise, a person still has to use javascript interop since i know that javascript can listen for events for browser size has changed.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

This is not something we currently plan to do in the near future as it can be achieved through JS interop. 

If you are asking for StateHasChanged to be called on all components when this happens, it is unlikely that we implement such feature. 

You can write a class that does JS interop, receives a callback and triggers an event when such callback is invoked and allow your components to subscribe to that event when they care about browser size changes.
