### ISSUE TITLE
Add .NET Framework assemblies to 5.0

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22853]
- and let their assembly versions change

**Comment by dougbu** [comment]
.NET Framework 4.7.2 has broad support across Windows versions and should be supported for w while. I'm basing this on https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework.

In any case, let's use the `net472` TFM when we fix this issue.

**Comment by Pilchie** [comment]
Consider using `net461` instead of `net472`, as it means that people on that framework won't fall into the `netstandard` version and end up with facade issues.

**Comment by dougbu** [comment]
Sounds good @Pilchie

**Comment by dougbu** [comment]
This issue is specific to implementation (not tooling) projects containing shipped `netstandard2.0` (or lower) assemblies

**Comment by wtgodbe** [comment]
Following files (and a few others) may need some tweaking of their `#if` blocks that are TFM-specific:

- src\DataProtection\Cryptography.KeyDerivation\src\PBKDF2\NetCorePbkdf2Provider.cs
- src\Identity\Extensions.Core\src\PasswordHasher.cs
- src\Shared\WebEncoders\WebEncoders.cs
- src\SignalR\common\Shared\MemoryBufferWriter.cs
- src\SignalR\common\Shared\PipeWriterStream.cs

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/25094
