### ISSUE TITLE
how to handle ws-fed encrypted security token?

### ISSUE THREAD

**Issue by balasherkar** [dotnet/aspnetcore#22868]

**Comment by blowdart** [comment]
Does the [WS-Fed](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1) middleware not work for you?

**Comment by balasherkar** [comment]
@blowdart i am using [WS-Fed](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1), but the security token received is encrypted using certificate.

**Comment by blowdart** [comment]
Microsoft.AspNetCore.Authentication.WsFederation lacks support for token encryption, so there's no support for it. We haven't prioritised it, because most STSes just sign, there's no real secrets in the token.

**Comment by balasherkar** [comment]
@blowdart I am able to achieve this by implementing Microsoft.IdentityModel.Tokens.ISecurityTokenValidator interface.
