### ISSUE TITLE
The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by HannahKiekens** [dotnet/aspnetcore#22865]
I am trying to move an IEmailSender implementation to a netstandard library
I get the following error:
The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' (are you missing an assembly reference?)

The interface should be in:...\packages\microsoft.aspnetcore.identity.ui\3.1.5\lib\netcoreapp3.1\Microsoft.AspNetCore.Identity.UI.dll

This is my project file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.5" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scoops.EntityFramework\Scoops.EntityFramework.csproj" />
  </ItemGroup>

</Project>
```

Test.cs:
```
namespace Scoops.Identity
{
    public class Test : IEmailSender
    {
        public Task SendEmailAsync(string email, string subject, string message)
        {
            return Task.CompletedTask;
        }
    }
}
```

I dont understand, this interface/namespace should be in Microsoft.AspNetCore.Identity.UI
What references am I missing ? My IEmailSender implementation works fine in a asp.net core project

**Comment by javiercn** [comment]
@HannahKiekens thanks for contacting us.

IEmailSender lives in the `Microsoft.AspNetCore.Identity.UI` package.

**Comment by HannahKiekens** [comment]
Its not as simple as that because it does not compile
https://github.com/HannahKiekens/IEmailSenderIssue

maybe Microsoft.AspNetCore.Identity.UI is missing some dependencies

**Comment by HannahKiekens** [comment]
Class1.cs(2,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\Hannah Kiekens\source\github\IEmailSenderIssue\ClassLibrary1\ClassLibrary1.csproj]
Class1.cs(7,27): error CS0246: The type or namespace name 'IEmailSender' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Hannah Kiekens\source\github\IEmailSenderIssue\ClassLibrary1\ClassLibrary1.csproj]

**Comment by javiercn** [comment]
@HannahKiekens You are likely missing a framework reference to asp.net core

**Comment by HannahKiekens** [comment]
The correct aswer is:
`<TargetFramework>netcoreapp3.1</TargetFramework>`
instead of
`<TargetFramework>netstandard2.1</TargetFramework>`
