### ISSUE TITLE
A suitable constructor for type 'Microsoft.Extensions.Localization.StringLocalizer could not be located

### ISSUE THREAD

**Issue by jclebrun** [dotnet/aspnetcore#22860]
My Blazor WebAssembly published to Azure Static Files gives the following error:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: A suitable constructor for type 'Microsoft.Extensions.Localization.StringLocalizer`1[CommandesAEmporter.Pages.Index]' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
System.InvalidOperationException: A suitable constructor for type 'Microsoft.Extensions.Localization.StringLocalizer`1[CommandesAEmporter.Pages.Index]' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

When run on my PC, it works fine. I am using the following in my project:

-Project Sdk="Microsoft.NET.Sdk.Web"--

  --PropertyGroup--
    --TargetFramework--netstandard2.1--/TargetFramework--
    --RazorLangVersion--3.0--/RazorLangVersion--
    --ServiceWorkerAssetsManifest--service-worker-assets.js--/ServiceWorkerAssetsManifest--
  --/PropertyGroup--

  --ItemGroup--
    --PackageReference Include="Azure.Storage.Blobs" Version="12.4.2" /--
    --PackageReference Include="Blazored.LocalStorage" Version="2.1.6" /--
    --PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0" /--
    --PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0" PrivateAssets="all" /--
    --PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0" PrivateAssets="all" /--
    --PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.4" /--
    --PackageReference Include="Microsoft.Extensions.Localization" Version="3.1.5" /--
    --PackageReference Include="System.Net.Http.Json" Version="3.2.0" /--
  --/ItemGroup--

  --ItemGroup--
    --ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" /--
  --/ItemGroup--

**Comment by javiercn** [comment]
@jclebrun thanks for contacting us.

This is likely due to to linking. I suggest you disable linking and check if that solves the issue and configure the linker following the steps described [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1) to avoid the problem.

**Comment by jclebrun** [comment]
@javiercn 
I added the following to the project file:
<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>

The error message changed from:
A suitable constructor for type 'Microsoft.Extensions.Localization.StringLocalizer1[CommandesAEmporter.Pages.Index]' could not be located.

to:
 A suitable constructor for type 'Microsoft.Extensions.Localization.StringLocalizer`1[CommandesCuisine.Shared.NavMenu]' could not be located.

Thanks for answering this issue.

**Comment by jclebrun** [comment]
I did add these 2 elements to the project definition:

<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>

<ItemGroup>
    <EmbeddedResource Update="Pages\Index.fr.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Pages\Index.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

and everything now works fine.

Thanks for your support.

**Comment by elemerick** [comment]
jclebrun i have the same problem with u please can you be more specific on what you have done to solve the issue? am trying and its not working

**Comment by jclebrun** [comment]
Hi, this is what I added to the project file. It seems Blazor is looking for the translation file (.resx of the index page) when it loads.
`<ItemGroup>
    <EmbeddedResource Update="Pages\Index.fr.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Pages\Index.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>`

Hope this help.

**Comment by elemerick** [comment]
in fact i am trying to publish this project it work well in visual studio but fails to load when you publish if you can help ill really appreciate! its a popular project: https://github.com/SteveSandersonMS/CarChecker
ps: je comprends le francais! merci davance

**Comment by jclebrun** [comment]
Quels sont les messages d'erreur quand tu publies le projet ?

**Comment by elemerick** [comment]
> Quels sont les messages d'erreur quand tu publies le projet ?

![image](https://user-images.githubusercontent.com/18500899/86956212-a780c500-c150-11ea-995e-56f6f447e2ca.png)

**Comment by elemerick** [comment]
merci champion j'ai pu corriger le problème en fait je devais juste effacer
les données du cache du navigateur! il essayait d'utiliser d'anciennes dll
une fois fait tout fonctionne bien! je te remerci vraiment pour ta
disponibilité ca ma bcp aidé à traverser ce problème
