### ISSUE TITLE
[Feature] Blazor Application on Mobile with Xamarin.Forms

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#22863]
Add possibility to run `Blazor` Application on Mobile with Xamarin.Forms
It allow to write single UI interface for Web and Mobile and just concentrate on writing bigness logic for Web version and Mobile version that has access to platform API

There is already existing `BlazorMobile` template that allow to run `Blazor` Application on top of `Xamarin.Forms` and `Electron.NET`:
https://github.com/Daddoon/BlazorMobile

### Is your feature request related to a problem? Please describe.
Consistent UI between all platforms and Platform specific features (Xamarin.Forms features or Browser features) on top of application

### Describe the solution you'd like
Would like to run Blazor App everywhere WebView or Browser is supported

**Comment by danroth27** [comment]
We now have an experimental project for running Blazor in mobile apps via Xamarin called the the [Mobile Blazor Bindings](https://aka.ms/mobile-blazor-bindings) that you should definitely check out. Let us know what you think!
