### ISSUE TITLE
Blazor WASM: The inner handler has not been assigned - Configure AuthorizationMessageHandler

### ISSUE THREAD

**Issue by paulguz** [dotnet/aspnetcore#22872]
cc: @guardrex 

_Originally posted on the Blazor Docs issues (because I was following the docs and it didn't work), but have been asked to repost here._

When trying to use the code in the section #configure-authorizationmessagehandler, I receive the erorr: 

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: The inner handler has not been assigned.

In a vanilla Blazor WASM app (from the template) have the following in Program.cs:

```
	builder.Services.AddTransient(sp =>
			{
				return new HttpClient(sp.GetRequiredService<AuthorizationMessageHandler>()
						.ConfigureHandler(
								authorizedUrls: new[] { $"https://api.mysite.com" },
								scopes: new[] { "scope1", "scope2" }))

				{
					BaseAddress = new Uri($"https://api.mysite.com")
				};
			});
```
I then call Http.GetFromJsonAsync and the above error occurs.

If I configure a named client (i.e. use AddHttpClient rather than AddTransient) otherwise identically, I don't get the error.

Is there something missing in the docs, or is it something I'm doing wrong?

**Comment by javiercn** [comment]
@paulguz thanks for contacting us.

That code snippet is wrong. Likely because you are not using HttpClientFactory. In that case you need to create an HttpClientHandler instance and assign it as the innerhandler of the AuthorizationMessageHandler manually.

@guardrex if this is in the docs, can you fix the snippet?

**Comment by guardrex** [comment]
It came in from the Preview 5 blog post at https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available/. It's the example code provided at the end of the *Attach tokens to outgoing requests* section, except that we changed the registration from `AddSingleton` to `AddTransient` later.

It might have gone stale at some point. It wasn't caught on https://github.com/dotnet/AspNetCore.Docs/pull/18616 when I made a minor change to it while adding the *Custom AuthorizationMessageHandler class* coverage.
