### ISSUE TITLE
Build action doesn't generate Views.dll for project asp net core 3.1

### ISSUE THREAD

**Issue by topnguyen** [dotnet/aspnetcore#22875]
### Describe the bug
I have migrated my project from 2.2 to 3.1 and try to use the recompile Views feature but it not working.

![image](https://user-images.githubusercontent.com/15808788/84508647-cd9b7c80-acec-11ea-9e16-8a1ba476c397.png)

### To Reproduce
Please access my repo: https://github.com/topnguyen/Goblin.Landing
Then build with `Release` mode (I have add `mvcCoreBuilder.AddRazorRuntimeCompilation();` for Debug mode)

### Exceptions
When building the project must have the Views.dll in the bin folder.

### Further technical details
- ASP.NET Core version 3.1

**Comment by javiercn** [comment]
@topnguyen thanks for contacting us.

It is disabled by default on 3.1. Check [this doc](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&tabs=visual-studio) for instructions on how to enable it.

**Comment by topnguyen** [comment]
Hi @javiercn 

Thank for your quick response.

Please take a look on my startup via https://github.com/topnguyen/Goblin.Core/blob/a24b6deaa6f551298440c4b44a663f15b8862d98/Goblin.Core.Web/Setup/BaseUiStartup.cs#L17

I have added Razor engine and Views already.

**Comment by javiercn** [comment]
@topnguyen You can create a new 3.1 project with runtime compilation enabled and check the differences between that and your project.

@pranavkm might know more, but I suggest you follow the docs to the letter and check the differences between your project and a working project first.

**Comment by topnguyen** [comment]
Hi @javiercn 

I followed your link few hours before and it doesn't work.

I have tried to create a new project, it have View.dll, but when I add the config below to prevent append target framework to build folder, it not have View.dll also.
`AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>`

I have compared with the new project and try to add same service but it doesn't work, could you take a look on my project?

**Comment by javiercn** [comment]
@topnguyen You are not referencing the Razor SDK. https://github.com/topnguyen/Goblin.Core/blob/a24b6deaa6f551298440c4b44a663f15b8862d98/Goblin.Core.Web/Goblin.Core.Web.csproj#L1

**Comment by topnguyen** [comment]
I found my project issue is duplicated Content makes the build cannot generate View.dll

After resolve it, now it generate the View.dll already.

Anyway, thank for your support and quick response @javiercn
