### ISSUE TITLE
@inject directive cannot be committed via typing "space" in VSCode

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22886]
In a document type `@inj` until you have the completion list selecting `inject`. Press `space` and see that it's not completed.

**Comment by TanayParikh** [comment]
![inject](https://user-images.githubusercontent.com/14852843/84833982-3cc2ea80-afe5-11ea-857c-db600c97d685.gif)

Not able to repro, am I missing something?

**Comment by adrianwright109** [comment]
This issue was reported to be in VSCode (see issue title) - looks like you're trying to repo in Visual Studio?

**Comment by TanayParikh** [comment]
> This issue was reported to be in VSCode (see issue title) - looks like you're trying to repo in Visual Studio?

You're absolutely right, missed that. Retrying.

**Comment by TanayParikh** [comment]
Okay got the repro in VSCode. Thanks.
