### ISSUE TITLE
Interop.Microsoft.Office.Interop.Word.dll is invalid. Assembly paths must be rooted

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22882]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1069474/interopmicrosoftofficeinteropworddll-is-invalidass.html)._

---
Blazor and com deos not work 'as advertized'.
Though my fiels do NOT report anu error in 'old' WPF and so on it does now:
'Interop.Microsoft.Office.Interop.Word.dll is invalid. Assembly paths must be rooted.'
This is my code: I need this for making PDF from Word docs, WIHOUT third party elements!

Microsoft.Office.Interop.Word.Application WordApp = new Microsoft.Office.Interop.Word.Application();
                    WordApp.Documents.Open(@sourceFile);
                    document. LetterAsByteArray = "NoData";
                    if (WordApp.Documents.Count > 0)
                    {
                        {
                        string uniqueFileName = Guid.NewGuid(). ToString() + "PDF";
                        string destFile = System.IO.Path.Combine(targetPath, uniqueFileName);
                        System.IO.Directory.CreateDirectory(targetPath);
                        System.IO.File.Copy(sourceFile, destFile, true);
                        foreach (Microsoft.Office.Interop.Word.Document currentWordDoc in WordApp.Documents)
                            {
                            currentWordDoc.SaveAs2(uniqueFileName, (0x11));
                            currentWordDoc.Close(SaveChanges: -1); //wdSaveChanges = -1 (&HFFFFFFFF)
                            document. LetterAsByteArray = uniqueFileName;
                            break;
                            }
                        WordApp.Quit(SaveChanges: 0); //wdDoNotSaveChanges = 0
                        }                        
                        }
                    WordApp.Quit();
Please help me.

Jan Ulehake, using MS software since 1982: no kidding!

---
#### Visual Studio Feedback System on 6/8/2020, 07:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Are you using the library in a Blazor Client / WebAssembly project?

**Comment by pranavkm** [comment]
Looks like a dup of https://github.com/dotnet/aspnetcore/issues/21480. Could you open a new issue if you think it's different? Thanks!
