### ISSUE TITLE
Event counters need to use Interlocked.Read

### ISSUE THREAD

**Issue by davidsh** [dotnet/aspnetcore#22888]
See: https://github.com/dotnet/runtime/pull/37619#discussion_r438406192

From @davidfowl 
>Hmm maybe we're tearing on 32 bit! 😄

**Comment by davidfowl** [comment]
Where’s the PR?

**Comment by davidsh** [comment]
>Where’s the PR?

I opened an issue for now. I can help do the PR too if you want after I fixed some runtime telemetry PRs. :)

**Comment by gfoidl** [comment]
I'm just writing some EventCounters and while looking for references I landed here 😉 
I'd like to fix this -- can you assign it to me? (or is @halter73 already working on this?)

**Comment by halter73** [comment]
I'm keeping myself assigned so I hopefully forget about it, but go for it @gfoidl. Thanks!
