### ISSUE TITLE
Couldn't able to connect with SQL server. Getting run time error in controllers where DbContext is added as Dependency Injection. 

### ISSUE THREAD

**Issue by senseihimanshu** [dotnet/aspnetcore#22880]
### Describe the bug
When I tried to pair the DbContext file in Controller using dependency injection. I couldn't able to access the API. It throws Internal Server Error 500 at each API request. I am using the MSSQL server and follow all the configurations of the EF core.

### To Reproduce

https://github.com/senseihimanshu/ARMS/tree/develop/arms-services/src/Arms.Api

### Further technical details
- dotnet core 2.2
- .NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- JetBrains Rider

**Comment by pranavkm** [comment]
Can you share the details of the exception being thrown?

**Comment by senseihimanshu** [comment]
Actually the problem was i made constructor private, Sorry!
