### ISSUE TITLE
Add an API to focus on elements

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#22892]
A common ask from Blazor users is the ability to perform trivial DOM operations without having to manually write the JavaScript / JSInterop code. Having the ability to focus on DOM elements is one of the more popular ones that we'd like to address. 

To solve this, we'd like to introduce `FocusAsync()` as an extension method to `ElementRef` types. Here's the usage we think would work the best:

```razor
@code {
  ElementRef myRef;

  protected override async Task OnAfterRenderAsync(bool first)
  {
      await myRef.FocusAsync();
      ...
   }
}
```

This would most likely use `JSInterop` for it's implementation, but it would be nice not to have to pass in the `IJSRuntime` instance.

Related issue with lots of feedback: https://github.com/dotnet/aspnetcore/issues/17472

**Comment by mrpmorris** [comment]
I wouldn't like to have to write code to focus an element. It would be better as a directive...

`<input @autofocus/>`

But I am not sure if it would be possible to make it work with custom components like `<InputText>`

**Comment by pranavkm** [comment]
@mrpmorris we have the linked issue open to consider addressing the `autofocus` attribute. We wanted to independently provide convenience APIs for `focus` and other DOM operations.
