### ISSUE TITLE
Java Script UI is not working in Blazor Server App

### ISSUE THREAD

**Issue by const1966** [dotnet/aspnetcore#22908]
Hello,
I'm having problem with an implementation of any of JS UI (say DateTimePicker) in Blazor Server Side app ( .NET Core 3.1 Framework).
Dev Env: Microsoft Visual Studio Professional 2019
Version 16.5.4
Microsoft .NET FRamework 4.7.03062

I just want to have DateTime Picker on my **Index.razor** page:
```
@page "/"

<h1>Hello, world!</h1>
Welcome to your new app.
<SurveyPrompt Title="How is Blazor working for you?" />

<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="md-form md-outline input-with-post-icon datepicker">
                <input type="text" id="orderDatePicker" class="form-control">
            </div>
        </div>
    </div>
</div>
```
Here is my **_Host.cshtml**:
```
@page "/"
@namespace BlazorAppDemo.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BlazorAppDemo</title>
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />

    <link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js" type="text/javascript"></script>

</head>
<body>
    <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" />
    </app>

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.server.js"></script>

    <script type="text/javascript">

        $('#orderDatePicker').datepicker({
            format: 'dddd, dd mmm, yyyy',

        });

    </script>

</body>
</html>

```

The issue I'm facing is when "blazor.server.js" reference is sitting within the ```<body>``` tag
```
    <script src="_framework/blazor.server.js"></script>
```
(where this is actually supposed to be), my "orderDatePicker" is not working (not showing Dates to pick).

![image](https://user-images.githubusercontent.com/66455659/83836819-a62c2a80-a6c2-11ea-8e63-fbfad9f36828.png)

But when I move 
```
    <script src="_framework/blazor.server.js"></script>
```
![image](https://user-images.githubusercontent.com/66455659/83837083-6e71b280-a6c3-11ea-84ec-cf0d0d0e2ea2.png)

from ```<body>``` to ```<head>``` the Picker works perfectly:

![image](https://user-images.githubusercontent.com/66455659/83836992-2c487100-a6c3-11ea-992d-3cec877d43a6.png)

Looks like my problem is resolved, but the new and bigger issue appears as a result of that move.
Exactly, **onclick** event is stopping to work on **Counter.razor** page:
```
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button> 
```
The Counter doesn't work while this worked well before the move.

Could anybody explain me why this is happening.
Thank you.

**Comment by mrpmorris** [comment]
If you navigate away from the page and then back, does it stop working again?

**Comment by const1966** [comment]
Just to clarify:
The issue is not with @onclick event as this is working properly when ```<script src="_framework/blazor.server.js"></script>``` is sitting in its native location, which is ```<body>``` of _Host.cshtml file.
Problem is that I cant make "DateTipme Picker" work unless I move ```<script src="_framework/blazor.server.js"></script>```  from ```<body>``` to ```<header>```.
But this move makes @onclick unworkable.
By the way it's not just @onclick, but @bind and similar @events which are using blazor.server.js for Server - Client communication.

The navigation back and forth of the Page isn't resolving the issue, obviously.
I'm looking for advise How To Make JS UI work in Blazor Server App.

I stuck with my project because of this issue.
Any ideas are appreciated.
Thank you

**Comment by mrpmorris** [comment]
When you change it so that it works. If you navigate away from the page and then back again, is it now broken again?

**Comment by const1966** [comment]
If the DateTimePicker works and I navigate away from the page and then back again - it's still working.

**Comment by mrpmorris** [comment]
I really wasn't expecting that answer :) Would you like to send me a small project that reproduces the problem and I'll have a look?

**Comment by const1966** [comment]
Here you go.
Ask me if any questions.
Thank you
[BlazorAppDemo.zip](https://github.com/dotnet/aspnetcore/files/4777545/BlazorAppDemo.zip)

**Comment by javiercn** [comment]
@const1966 thanks for contacting us.

Your issue is that Blazor hasn't finished loading by the time you run your script. The proper way to achieve what you are trying to accomplish is to define a function in the global scope and call it from OnAfterRenderAsync using JS interop. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1#detect-when-a-blazor-server-app-is-prerendering) for details.

**Comment by const1966** [comment]
Hi Javier,

Your suggestion does makes sense but I'm having issue with an implementation of one.
I crated Global Scope function in _Host.cshtml:
```
    <script type="text/javascript">

        window.ConvertArray = () => {
            $('#orderDatePicker').datepicker({
                format: 'dddd, dd mmm, yyyy',
            });
        }

    </script>
```
I'm calling this function as you suggested:
```
@code {

    protected async Task OnAfterRenderAsync()
    {
        await JSRuntime.InvokeVoidAsync("convertArray");

    }
}
```
But the issue is still there - DateTimePicker is not working.
(attaching my project for reference)
Am I missing anything?
[BlazorAppDemo.zip](https://github.com/dotnet/aspnetcore/files/4784303/BlazorAppDemo.zip)

Please advise

**Comment by javiercn** [comment]
@const1966 The casing is wrong
```
 await JSRuntime.InvokeVoidAsync("convertArray");
                           window.ConvertArray = () => {
```

**Comment by const1966** [comment]
Thank you Javier, but this doesn't work even after I fixed the casing.
Please advise.
