### ISSUE TITLE
Blazor "Registration is not supported." message never displayed

### ISSUE THREAD

**Issue by aguacongas** [dotnet/aspnetcore#22912]
### Describe the bug
When the `RemoteAuthenticatorView.ApplicationPaths.RemoteRegisterPath`  is null the user is alway redirected to *?returnUrl={loginPath}* and **Registration is not supported** is never displayed.

### To Reproduce
- Create a Blazor WASM application with authentication and default *Authentication.razor*
- Set `RemoteRegisterPath` to null.
- Click on the register link

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L202

**Comment by barahonajm** [comment]
I would like to work on this if everyone is agreed
