### ISSUE TITLE
Mvc.Performance benchmark failing to run: An assembly specified in the application dependencies manifest has already been found but with a different file extension

### ISSUE THREAD

**Issue by alefranz** [dotnet/aspnetcore#22915]
### Describe the bug
I'm unable to run the benchmarks in Microsoft.AspNetCore.Mvc.Performance due to an issue resolving the dependencies.

### To Reproduce
```powershell
.\build.ps1 -BuildManaged -Configuration Release
cd src\Mvc\benchmarks\Microsoft.AspNetCore.Mvc.Performance
dotnet run -c Release
# run benchmark 2
```

### Exceptions (if any)
// Execute: dotnet "32037691-5c3b-4f41-ae36-96fed54708cd.exe" --benchmarkName "Microsoft.AspNetCore.Mvc.Performance.HelperPerformanceBenchmark.RenderView(ViewPath: "~/Views/HelperPartialTagHelper.cshtml")" --job "Server=True, Toolchain=.NET Core 5.0, InvocationCount=1, RunStrategy=Throughput, UnrollFactor=1" --benchmarkId 4 in C:\dev\dotnet\aspnetcore\artifacts\bin\Microsoft.AspNetCore.Mvc.Performance\Release\net5.0\32037691-5c3b-4f41-ae36-96fed54708cd\bin\Release\net5.0
Error:
  An assembly specified in the application dependencies manifest (32037691-5c3b-4f41-ae36-96fed54708cd.deps.json) has already been found but with a different file extension:
    package: '32037691-5c3b-4f41-ae36-96fed54708cd', version: '5.0.0-dev'
    path: '32037691-5c3b-4f41-ae36-96fed54708cd.dll'
    previously found assembly: 'C:\dev\dotnet\aspnetcore\artifacts\bin\Microsoft.AspNetCore.Mvc.Performance\Release\net5.0\32037691-5c3b-4f41-ae36-96fed54708cd\bin\Release\net5.0\32037691-5c3b-4f41-ae36-96fed54708cd.exe'
ExitCode != 0
// Benchmark Process 5420 has exited with code -2147450740
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!

### Further technical details
This happens on current master https://github.com/dotnet/aspnetcore/commit/28b3ab82308c7d2f90894c9bac0f40333557acbb

**Comment by davidfowl** [comment]
I see the same thing.

cc @BrennanConroy

**Comment by BrennanConroy** [comment]
Yeah same, no idea what's going on.

Side-note, running the project from VS works (•_•)

**Comment by alefranz** [comment]
I actually get the same error when running it from VS. I'm on Version 16.7.0 Preview 2.0

**Comment by BrennanConroy** [comment]
Found the commit that broke it. https://github.com/dotnet/aspnetcore/commit/d5849f3534403caf665157c4e1045432a35e3951
That's the change from netcoreapp5.0 to net5.0. Not sure how it broke it though.

**Comment by alefranz** [comment]
Brilliant! thanks!
