### ISSUE TITLE
Guidance for handling Authentication in disconnected mode for ASP.Net Core hosted Blazor Wasm PWA

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#22926]
I have an Asp.net core hosted Blazor Wasm PWA, using Azure AD authentication. The app is required to support occasionally disconnected scenario.

Using a combination of the provided out of the box service plus Workbox, I have been able to cache my GET apis, and even support BackgroundSync of my POST apis, resulting in an app that supports good bit of functionality when offline. Once the app is up and running in the browser, if the network is disconnected and user hits Refresh or Ctrl-F5, the app reloads fine.

However, if the user closes the browser window, and later opens a new browser window, and navigates to the app url, the app loads but immediately opens an authentication popup to login.microsoftonline.com.

Is there a way to get around this issue such that the app can continue to function, especially if the previously acquired token might still be valid (i.e. was acquired less than an hour ago)? What possible workarounds are available such that the  user does not get the authentication popup if they are offline.

**Comment by javiercn** [comment]
@bancroftway thanks for contacting us.

We have docs for this. https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#interaction-with-authentication
