### ISSUE TITLE
Blazor Webassembly Dispose called before OnInitializedAsync completes

### ISSUE THREAD

**Issue by imtrobin** [dotnet/aspnetcore#22932]
I have a component that 

```
OnInitializedAsync 
   await  Task A
   await  Task B

Dispose

```
What I found is the order of calls can be 
```
   Task A
   Dispose
   Task B

```
This happens because one of my other component will refresh the page. Is that intended?

3.20

**Comment by javiercn** [comment]
@imtrobin thanks for contacting us.

That is perfectly normal and can happen if the component is removed before the async work completes. You should use a cancellation token source and trigger it on dispose to abort any further work.
