### ISSUE TITLE
Blazor __Builder does not exist in current context

### ISSUE THREAD

**Issue by fcbogle** [dotnet/aspnetcore#22942]
### Describe the bug
When I add a child Blazor component and compile the project I get the error in the subject line: `__Builder does not exist in current context.` The parent component is a series of pulldown lists that are used to obtain search Id's from a number of tables based on standard dbContext and Entity Framework Core. The user selects the pulldown items and submits a SearchSelection object to the child component which obtains the results of the specified query and presents the results. The code is working perfectly until I added the child component.

This code is taken from the parent Blazor component, the inclusion of the child component is right at the bottom. Child component named `SearchResults`

`@code {

    SearchSelection selection = new SearchSelection();

    static CancellationTokenSource source = new CancellationTokenSource();
    CancellationToken token = source.Token;

    IEnumerable<ManagerApiResponse> manager;
    IEnumerable<ClassificationApiResponse> classification;
    IEnumerable<ValidationApiResponse> validation;
    IEnumerable<GeographyApiResponse> geography;

    protected override async Task OnInitializedAsync()
    {
        manager = await apiService.GetAllManagers(token);
        classification = await apiService.GetAllClassifications(token);
        validation = await apiService.GetAllValidations(token);
        geography = await apiService.GetAllGeographies(token);
    }    

    Dictionary<DateTime, string> events = new Dictionary<DateTime, string>();

    void Change(object value, string name)
    {
        var str = value is IEnumerable<object> ? string.Join(", ", (IEnumerable<object>)value) : value;

        events.Add(DateTime.Now, $"{name} value changed to {str}");
        StateHasChanged();
    }

    void ChangeBound(object value, string name)
    {
        events.Add(DateTime.Now, $"{name} value changed to {value}");
        StateHasChanged();
    }

    private void HandleSubmit()
    {
        Console.WriteLine("Submiited selection object: ManagerId: " + selection.ManagerId + " ClassificationId: "
            + selection.ClassificationId + " GeographyId: " + selection.GeographyId + " ValidationId: " + selection.ValidationId);

        <SearchResults Selection="selection"></SearchResults>
    }`

### Further technical details
Here is my information about my system, I use a Mac (Catalina) and Visual Studio for Mac.

`.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.201 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
`

**Comment by javiercn** [comment]
@fcbogle thanks for contacting us.

Can you provide an actual minimal repro project that illustrates the issue? It is not clear from your snippet if that code accurately represents what's in your project. If that is the case, then this syntax is not supported. You can't have markup within a method body.

```
private void HandleSubmit()
{
    Console.WriteLine("Submiited selection object: ManagerId: " + selection.ManagerId + " ClassificationId: "
        + selection.ClassificationId + " GeographyId: " + selection.GeographyId + " ValidationId: " + selection.ValidationId);

    <SearchResults Selection="selection"></SearchResults>
}`
```

**Comment by fcbogle** [comment]
Hello @javiercn 
I'll give you access to the repo now. The code in question is within the .Web project and the other projects are also there should you need to access them. Two mins and you will have access. Thank you for the pointer about not having markup within a method body. Are their guidelines about where the markup can be placed? Regards

**Comment by javiercn** [comment]
@fcbogle we can't look at your code for compliance reasons, we need a specific minimal repro project that illustrates the issue that you are happy placing on a publicly accessible location.

The guidelines are that markup goes within the top level context of the Razor file. From what you seem to be trying to do, you just need to move the markup outside of the `code` block and put and `if` statement around it to avoid rendering the component before the user submits the query.

**Comment by fcbogle** [comment]
Hi @javiercn yes this call can be closed, I'll use the technology within the guidelines. Thank you
