### ISSUE TITLE
Incorrect attribute usage on ProducesResponseTypeAttribute

### ISSUE THREAD

**Issue by giggio** [dotnet/aspnetcore#22946]
### Describe the bug

According to [this comment](https://github.com/dotnet/aspnetcore/issues/20662#issuecomment-641552124) on issue #20662 from @mkArtakMSFT, `ProducesResponseTypeAttribute` is not supposed to be used on classes, only on methods. If this is the case, it should not have `AttributeTargets.Class`, as per:

https://github.com/dotnet/aspnetcore/blob/74857c3e352755fa4c924d73c615b3e9113ea1a8/src/Mvc/Mvc.Core/src/ProducesResponseTypeAttribute.cs#L13-L14

The incorrect attribute target is raising incorrect assumptions about how it's supposed to be used (which brought me to bring issue #20662).

**Comment by javiercn** [comment]
@giggio thanks for contacting us.

We'll discuss this change and update the issue appropriately.

**Comment by mkArtakMSFT** [comment]
Closing as we will address the behavior on the Analyzer instead.

**Comment by giggio** [comment]
@mkArtakMSFT why not simply remove `AttributeTargets.Class`? Wouldn't it be easier?
