### ISSUE TITLE
Blazor WebAssembly 3.2.0 - create and run your first Blazor WebAssembly app

### ISSUE THREAD

**Issue by James-Anastasi** [dotnet/aspnetcore#22948]
Hi, 
just starting with Blazor : not going so well for a first contact...

### Describe the bug
blazor webassembly app compatibility errors  3.2.0 not compatible with netstandard 2.1

just downloaded and installed dotnet-sdk-3.1.301-win-x64:
 * Installed without errors,
 * listed the templates (seems ok)
      Microsoft.AspNetCore.Components.WebAssembly.Templates
         Details:
           NuGetPackageId: Microsoft.AspNetCore.Components.WebAssembly.Templates
          Version: 3.2.0
          Author: Microsoft
          Templates:
           Blazor WebAssembly App (blazorwasm) C#
         Uninstall Command:
           dotnet new -u Microsoft.AspNetCore.Components.WebAssembly.Templates
 
When I run the command line to create the first Blazor App i get the following message :
D:\Documents\VisualStudioProjects>dotnet new blazorwasm -o BlazorAppA
The template "Blazor WebAssembly App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on D:\Documents\VisualStudioProjects\BlazorAppA\BlazorAppA.csproj...
  Determining projects to restore...
D:\Documents\VisualStudioProjects\BlazorAppA\BlazorAppA.csproj : error NU1202: Package Microsoft.AspNetCore.Components.WebAssembly 3.2.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.AspNetCore.Components.WebAssembly 3.2.0 does not support any target frameworks.
D:\Documents\VisualStudioProjects\BlazorAppA\BlazorAppA.csproj : error NU1202: Package Microsoft.JSInterop.WebAssembly 3.2.0 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.JSInterop.WebAssembly 3.2.0 does not support any target frameworks.
  Failed to restore D:\Documents\VisualStudioProjects\BlazorAppA\BlazorAppA.csproj (in 317 ms).

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

### To Reproduce
1) Install dotnet-sdk-3.1.301-win-x64
2) create first app with command line : dotnet new blazorwasm -o BlazorApp1
### Exceptions (if any)
None

### Further technical details
- ASP.NET Core version 3.1.301
- Include the output of `dotnet --info`
D:\Documents\VisualStudioProjects>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
uninstalled all ide's because had same problem in Visual studio community 16.6.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Do you see something similar with any other packages or only this one?

**Comment by danroth27** [comment]
@James-Anastasi Are you able to create a run a Console app or an ASP.NET Core web app?:

- `dotnet new console -o ConsoleApp1`
- `dotnet new webapp -o WebApp1`

Is there anything unusual or unique about your user directory where the NuGet packages get cached (*\users\<username>\.nuget\packages*), like special characters, spaces, etc.?

**Comment by danroth27** [comment]
Also try running `dotnet nuget locals all -c` to clear your local NuGet cache and see if that helps.

**Comment by James-Anastasi** [comment]
Tried a console APP: 

   D:\Documents\VisualStudioProjects>dotnet new console -o ConsoleApp
   The template "Console Application" was created successfully.

   Processing post-creation actions...
   Running 'dotnet restore' on ConsoleApp\ConsoleApp.csproj...
     Determining projects to restore...
    Restored D:\Documents\VisualStudioProjects\ConsoleApp\ConsoleApp.csproj (in 110 ms).

     Restore succeeded.

Cleared the local nuGet Cache and tried  the Blazor app again ....    IT'S ALIVE :)

Thanks for the quick and spot on reply

**Comment by James-Anastasi** [comment]
We can close the issue.
