### ISSUE TITLE
Feature request: email confirmation resend feature status.

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#22940]
A feature request to add the ability to resend email confirmations was mentioned here: https://github.com/dotnet/AspNetCore/issues/5410

Has anything been done regarding that feature request? I get that we can add that functionality ourselves, but if this is such a frequently requested feature then why not build it in?

I am pretty sure it does not matters but just in case it does, I am talking from a Blazor Webassembly project perspective.

Thanks.

**Comment by blowdart** [comment]
You couldn't do this in webassembly unless you were willing to put credentials inside your web assembly for a mail server which would be a horribly bad idea.

**Comment by rxelizondo** [comment]
I don't want to do this in Webassembly, I was trying to mention that I am using the `Blazor Webassembly Core hosted` built in template with `authentication` enabled... clearly I did a horrible job doing that!

Perhaps I linked the wrong issue, as of right now, when I create a Blazor Webassembly Core hosted project with authentication enabled (using the built in template), I see no option to resend a confirmation email. Are you saying that such functionality is now built in?

**Comment by blowdart** [comment]
We had concerns about it being used to spam folks, and if you have a valid login you should be able to send it again via the user management pages, but I think put off sending confirmations again due to spam concerns.

@haok is that right?

**Comment by HaoK** [comment]
No it should be back in again, as of 5.0 https://github.com/dotnet/aspnetcore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Login.cshtml#L45

**Comment by blowdart** [comment]
Resolving for 5.0
