### ISSUE TITLE
When change the <base Href= "/" /> in teh index.html, the blazor.webassembly.js file no longer can be downloaded

### ISSUE THREAD

**Issue by andyzhu** [dotnet/aspnetcore#22943]
### Describe the bug
created a sample project use **dotnet new blazorwasm --hosted true -o BlazorAppwithHost**
build and run the solution, everything works fine. Go to https://localhost:5001, get to see the Sample Blazor WebAssembly page

Now change the following inside the wwwroot\index.html file under the Client project, change the `<base href="/" />` to `<base href="/blazor/" />`. 
Build the solution without a problem
Now run the project and go to url : https://localhost:5001/blazor/
Now the error message says: "An unhandled error has occurred
Check the Browser devtools, and can see 
loading https://localhost:5001/blazor/_framework/blazor.webassembly.js returns 404, 
loading https://localhost:5001/blazor/_framework/bootstrap.min.css return 404 
and loading https://localhost:5001/blazor/_framework/app.css return 404.

What have I done wrong? 

### Further technical details
- ASP.NET Core version 
**dotnet --info**
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
IDE: VSCode

**Comment by javiercn** [comment]
@andyzhu thanks for contacting us. You also need to change where the Blazor files are exposed by passing `/blazor` to `UseBlazorFrameworkFiles`
