### ISSUE TITLE
DynamicControllerEndpointMatcherPolicy is broken

### ISSUE THREAD

**Issue by mitselplik** [dotnet/aspnetcore#22956]
I was attempting to use an implementation of the `DynamicRouteValueTransformer` class but kept getting unexpected results in testing.  I traced the problem back to the `DynamicControllerEndpointMatcherPolicy` which appears to be behaving in a manner I simply cannot explain.  I've never seen something like this before.

From the image below, it is apparent from the debug view of the `dynamicValues` variable that it is most definitely **NOT** null.  I also verified that my transformer class is being called and that a value is definitely being returned just prior to the execution of line 115.  And yet the code is failing to see that `dynamicValues` isn't null and is subsequently falling into the `if()` block as if it thinks the value is in fact null.  This nulls out the very endpoint I expect to be elected in the candidates and skips it entirely.

![image](https://user-images.githubusercontent.com/43304288/84675217-8df1b200-aef1-11ea-98a1-92542bbd8dc0.png)

### Further technical details
- ASP.NET Core version 3.1.4

**Comment by javiercn** [comment]
@mitselplik thanks for contacting us.

Can you provide a minimal repro project so that we can investigate?

**Comment by mitselplik** [comment]
Certainly.  I'll need a little time (maybe a day or so).  The only time I've ever seen something like this is when the binaries don't match the source.
