### ISSUE TITLE
Dotnet watch run working - supervisor working - Views not loading

### ISSUE THREAD

**Issue by mckinleyelliot** [dotnet/aspnetcore#22957]
Hello, I am a recent bootcamp grad trying to deploy a few of my first websites. I'm hosting on an AWS EC2 Ubuntu server with netcoreapp 2.2. Please keep in mind that I am a newcomer to coding and web development. My code is sloppy, because I've been trying to focus on fixing this problem for months! I'm unaware of how to make a repro that's much simpler than my "custom" project, my repo called cwdmapper.

When I navigate to my project folder and run "sudo dotnet watch run" I am able to access my app over the web, but when I use supervisor it won't load Views. It's following a redirect from the Controller, but won't load the Views. The error message I'm getting in my supervisor .out.log is:

```
Hosting environment: Production
Content root path: /var/www/cwdmapper/bin/Debug/netcoreapp2.2/publish
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
^[[40m^[[1m^[[33mwarn^[[39m^[[22m^[[49m: Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The key {09091f07-ec86-47ea-9e78-6a4c8d6ca2e0} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
^[[41m^[[30mfail^[[39m^[[22m^[[49m: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[3]
      The view 'Dashboard' was not found. Searched locations: /Views/iLcwdMapper/Dashboard.cshtml, /Views/Shared/Dashboard.cshtml, /Pages/Shared/Dashboard.cshtml
^[[41m^[[30mfail^[[39m^[[22m^[[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The view 'Dashboard' was not found. The following locations were searched:
/Views/iLcwdMapper/Dashboard.cshtml
/Views/Shared/Dashboard.cshtml
/Pages/Shared/Dashboard.cshtml
```

I've tried the following solutions to no avail:
https://github.com/dotnet/websdk/issues/238

I've messed with the settings in my supervisor config file, and it seems to be working fine.

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

IDE - VS Code 1.45.1 on macOS Catalina Version 10.15.4

Thank you so much to anyone who is able and willing to offer some insight as to why I can't get my Views to work!

**Comment by pranavkm** [comment]
Views are found relative to the `ContentRootPath`. In the ordinary case, this is the working directory. In the snippet you have listed, it looks like the content root is set to the publish folder (`/var/www/cwdmapper/bin/Debug/netcoreapp2.2/publish`) which is very strange. I would expect it to point to `/var/www/cwdmapper/` and for `/var/www/cwdmapper/Views/iLcwdMapper/Dashboard.cshtml` to be where the view file is located.
