### ISSUE TITLE
TypeScript + Blazor = strange error messages?

### ISSUE THREAD

**Issue by BararDiHoumes** [dotnet/aspnetcore#22953]
### Describe the bug
I am trying to make TypeScript to work with Blazor, but there is constantly issues with the namespace, and problems around the visibility and compiler.

### To Reproduce
- Create a blazor project.
- Create two .ts files inside the main wwwroot folder.
- Try to import one to another, and call a function from the last one from the blazor.

file MainLayout.razor
```
@inherits LayoutComponentBase
@inject IJSRuntime jSRuntime;

<div id="masterViewDiv" class="cesium-viewer"></div>
<button @onclick="onClick">sfsdfsaf</button>
<style>
    .cesium-viewer {
        height: 100vh;
        width: 100vw;
        z-index: 1;
        top: 0px;
        left: 0px;
    }
</style>

@code{
    override protected void OnAfterRender( bool firstRender )
    {
        base.OnAfterRender( firstRender );

    }
    public void onClick()
    {
        jSRuntime.InvokeVoidAsync( "test" );
    }
}
```
file master.ts
```
module master
{
    export function test(): void
    {
        window.alert( "test" );
    }
}

```
file one.ts
```
import * as Master from "master";

this.window[ "test" ] = Master .test;

```

- and is there some examples/guides which to be followed in order to make TS works with Blazor WebASM ?

### Exceptions (if any)
- different types.

### Further technical details
- ASP.NET Core version : 3.2
- Include the output of `dotnet --info`
- The IDE - VS Pro preview - the latest - automatic updating.

**Comment by javiercn** [comment]
@BararDiHoumes thanks for contacting us.

There's nothing specific about making typescript work with Blazor. As long as typescript compiles the files to js and that you reference those from within index.html or _Host.cshtml it should be fine.

I would check that you can make it work in a plain html file and then move that working solution to Blazor, but there should be no difference.
