### ISSUE TITLE
Setting maxAllowedContentLength in the web.config for IIS is not working anymore.

### ISSUE THREAD

**Issue by yepeekai** [dotnet/aspnetcore#22950]
Since 3.1, setting maxAllowedContentLength in the web.config for IIS is not working anymore. 
 Looking at the code, the default value for IISServerOptions.MaxRequestBodySize has been set to match the default value of IIS. The problem is that you now have to change this value at 2 places:
web.config (configuration/system.webServer/requestFiltering/requestLimits: attribute maxAllowedContentLength) and the IISServerOptions in startup.cs: services.Configure(options => { options.MaxRequestBodySize = null; });

This is counter intuitive... If we override the default value at one place, it should follow at the other...

**Comment by BrennanConroy** [comment]
Is your limit between 2GB and 4GB?

We have an issue with that right now https://github.com/dotnet/aspnetcore/issues/22834

**Comment by yepeekai** [comment]
It is about the ~30MB limit.  By default, it is set to 30MB in IIS and it is now set by default to 30MB in aspnetcore too.  So It is required to change both limits for this to work.

**Comment by BrennanConroy** [comment]
You shouldn't need to set it in both places. If you set the web.config one to some value, the ASP.NET Core one will be updated (assuming you don't set it in code).

**Comment by yepeekai** [comment]
It was set in the web.config and it stopped working when I updated aspnetcore.  I did try both possibility (setting it only in web.config, setting it only in startup) and both failed...  It only works when I set both.

I will update to the last version of aspnetcore 3.1.x and retest and I will update this issue with the result.

**Comment by BrennanConroy** [comment]
> I will update to the last version of aspnetcore 3.1.x and retest and I will update this issue with the result.

Made any progress here?

**Comment by yepeekai** [comment]
I installed 3.1.5 and tested again.  I confirm that it fails if one of the 2 settings is not present.

**Comment by macgyver76** [comment]
I can confirm as well. Works only when set in both places. (3.1.5)

**Comment by BrennanConroy** [comment]
We should fix the MaxRequestLimitWarning log at the same time.
