### ISSUE TITLE
Typing in a .razor file in a blazor project causes long pause followed by crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22967]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1076033/typing-in-a-razor-file-in-a-blazor-project-causes.html)._

---
Typing in a .razor file in a blazor project causes long pause followed by crash

---
#### Visual Studio Feedback System on 6/15/2020, 00:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/22276
