### ISSUE TITLE
[BUG[] Integrating shared project with Xamarin forms .NET standard 2.1

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#22963]
I am trying to share a .NET standard 2.1 library that has my models within it I don't want to take them out and have a duplicate library however I get the following error.
Is there anyway for me to get around this error without having to create a sep library for models.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.AspNet.Identity.Core 2.0.1 is not compatible with monoandroid90 (MonoAndroid,Version=v9.0). Package Microsoft.AspNet.Identity.Core 2.0.1 supports: net45 (.NETFramework,Version=v4.5)	RoundTable.Mobile.Android	D:\GitMaster\AppManager\RoundTableWMS.Mobile\RoundTable.Mobile\RoundTable.Mobile.Android\RoundTable.Mobile.Android.csproj	1

**Comment by blowdart** [comment]
No there's not. You need to have a separate library for your models. We don't expect folks to pull in any identity libraries into other project types, so we don't target mono in any way.
