### ISSUE TITLE
Blazor app routing error on adress bar | Github Pages

### ISSUE THREAD

**Issue by zafer-v3** [dotnet/aspnetcore#22961]
Hello,

https://zafer-v3.github.io/TurkishLiraHistory -> I can access this

https://zafer-v3.github.io/TurkishLiraHistory/fetchdata -> I can't acess directly sub adress.

I dont know why.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@zafer-v3 thanks for contacting us.

I believe this is a limitation of deploying to a static site. GH doesn't know anything about client-side routes so it doesn't server index.html and only does that on the root page.

**Comment by zafer-v3** [comment]
I try azure web sites and run cool than github pages :)

https://dollarsallary.azurewebsites.net/fetchdata

**Comment by SteveSandersonMS** [comment]
@zafer-v3 You might want to check [this example of a Blazor WebAssembly app on GitHub pages](https://github.com/SteveSandersonMS/BlazorOnGitHubPages) which works with deep linking (sub-addresses).

Internally the solution is https://github.com/rafrex/spa-github-pages

**Comment by zafer-v3** [comment]
I think Github teams solve this.
