### ISSUE TITLE
[Blazor] Enable docker support when creating a template from Visual Studio

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#22964]
Change the template to enable the checkbox.

**Comment by javiercn** [comment]
This is blocked on necessary tooling improvements to make sure it only applies to hosted blazor-wasm and that it gets applied to the server project.

**Comment by mkArtakMSFT** [comment]
@vijayrkn we need your help with the tooling side of this. Do you think this will make into Vs 16.8?

**Comment by vijayrkn** [comment]
Our 16.8 tooling schedule is full. I can get this added to our backlog but I can't commit to an ETA.

**Comment by mkArtakMSFT** [comment]
Thanks @vijayrkn!
@javiercn moving this issue to the `Next Sprint Planning`  - out of 5.0.

**Comment by mkArtakMSFT** [comment]
> Our 16.8 tooling schedule is full. I can get this added to our backlog but I can't commit to an ETA.

@vijayrkn any updates on this?

**Comment by vijayrkn** [comment]
This work is complete and is available in the newer version of Visual Studio. Closing.

**Comment by javiercn** [comment]
@vijayrkn Could you elaborate on this a bit? The issue is from 2020 and my memory does not go that far 😄
