### ISSUE TITLE
Blazor WebAssembly Automatic Token Renewal

### ISSUE THREAD

**Issue by lanik** [dotnet/aspnetcore#22971]
Please add automatic token renewal using the refresh token.

I am working on Blazor WebAssembly app which invoks method trought grpc. But after token expires it requires request to redirect to login page. This is not the best solution. 
There can be used refresh token to renew access token.

I am adding OIDC authentication from Microsoft.AspNetCore.Components.WebAssembly.Authentication
```csharp

builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("oidc", options.ProviderOptions);
});
```
And set some properties like this.
```json

{
  "oidc": {
    "Authority": "https://auth.kyberna.cz",
    "ClientId": "myBestId",
    "DefaultScopes": [
      "openid",
      "profile",
      "api",
      "offline_access"
    ],
    "PostLogoutRedirectUri": "/",
    "ResponseType": "code"
  }
}

```

When looking in source code you are using library js oidc-client.
This library has startSilentRenew method to silent renew access token with refresh token. Call of this method would be very helpful.

Maybe it would be also helpful to add Offline property to add automatically offline_access scope. 
 
Meanwhile I am fixing it by 
```csharp
 await _jsRuntime.InvokeVoidAsync("AuthenticationService.instance._userManager.startSilentRenew");
```

Thank you

**Comment by javiercn** [comment]
@lanik thanks for contacting us.

Our HttpMessageHandler already handles token expiration automatically.

We don't plan to support refresh tokens in the browser since they are not safe to use as the client can't hold on to secrets. You can configure the AuthorizationMessageHandler as part of the GRPC handler to support this.

**Comment by javiercn** [comment]
[Here](https://github.com/javiercn/BlazorGrpcAuth) is a working sample on how to tie auth + grpc-web together

**Comment by lanik** [comment]
Thank you. Its really helpfull.
