### ISSUE TITLE
Investigate ways to host Angular / React components as islands within a Blazor application

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#22974]
There is currently no mechanism in place to do this as each SPA framework needs to be in control of the DOM.
Blazor can have some markers to be used as islands within the DOM, which will indicate that changes within these sections of the DOM are allows, and let other SPA frameworks modify it as needed. That way, it can be possible to host any SPA framework components within a Blazor app.

This can make migration from existing SPA frameworks to Blazor easier.

Things we currently don't know are:
- Is this something customers need? Will this help anybody if built.
- Is this even possible and how easy will it be to support - we shouldn't build anything which is too fragile.

**Comment by SteveSandersonMS** [comment]
> Blazor can have some markers to be used as islands within the DOM, which will indicate that changes within these sections of the DOM are allows, and let other SPA frameworks modify it as needed

This is already the case. If a Blazor component renders an element that, as far as Blazor is concerned, will always be empty, then you're free to manipulate the DOM inside that element any way you want and Blazor won't interfere or get confused.

```razor
This is a Blazor component

<div id="my-seemingly-empty-div"></div>
```

... then in some JS code:

```js
const rootElem = document.getElementById('my-seemingly-empty-div');
doStuffToPopulateTheElement(rootElem); // For example, instruct React to render into this element
```

Is there anything else we need besides this?

**Comment by SteveSandersonMS** [comment]
Documented in https://github.com/dotnet/AspNetCore.Docs/pull/20091
