### ISSUE TITLE
Breaking change in IIS UrlRewrite support with query string

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#22972]
## Changes to appendQueryString in IIS UrlRewrite middleware

We are fixing a bug in the IIS UrlRewrite middleware which will append query strings by default instead of removing them. This is to stay consistent with what the IIS UrlRewrite Module's behavior.

### Version introduced

ASP.NET Core 5.0-preview7

### Old behavior

When having a rewrite rule like the following:

```xml
<rule name="MyRule" stopProcessing="true">
  <match url="^foo" />
  <action type="Redirect" url="/bar" redirectType="Temporary" appendQueryString="true" /> <!-- appendQueryString defaults to true -->
</rule>
```

This wouldn't actually append the query string. So a URI like `/foo?baz=1` wouldn't redirect to `/bar?baz=1` and instead `/bar`. `appendQueryString` defaults to true as well.

### New behavior

The new behavior fixes this behavior. Now the URI from the previous example would be `/bar?baz=1`.

### Reason for change

The previous behavior didn't match the IIS UrlRewrite Module's behavior. Our goal is to have our IIS UrlRewrite middleware match the module as much as possible, so porting between is seamless.

### Recommended action

If the behavior of removing the query string is preferred, you can change the action to have  `appendQueryString="false"` instead.

### Category

ASP.NET

### Affected APIs

[`Microsoft.AspNetCore.Rewrite.IISUrlRewriteOptionsExtensions.AddIISUrlRewrite(RewriteOptions, IFileProvider, String)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.rewrite.iisurlrewriteoptionsextensions.addiisurlrewrite?view=aspnetcore-3.1#Microsoft_AspNetCore_Rewrite_IISUrlRewriteOptionsExtensions_AddIISUrlRewrite_Microsoft_AspNetCore_Rewrite_RewriteOptions_Microsoft_Extensions_FileProviders_IFileProvider_System_String_)

[`Microsoft.AspNetCore.Rewrite.IISUrlRewriteOptionsExtensions.AddIISUrlRewrite(RewriteOptions, TextReader)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.rewrite.iisurlrewriteoptionsextensions.addiisurlrewrite?view=aspnetcore-3.1#Microsoft_AspNetCore_Rewrite_IISUrlRewriteOptionsExtensions_AddIISUrlRewrite_Microsoft_AspNetCore_Rewrite_RewriteOptions_System_IO_TextReader_)

[`Microsoft.AspNetCore.Rewrite.IISUrlRewriteOptionsExtensions.AddIISUrlRewrite(RewriteOptions, TextReader, Boolean)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.rewrite.iisurlrewriteoptionsextensions.addiisurlrewrite?view=aspnetcore-3.1#Microsoft_AspNetCore_Rewrite_IISUrlRewriteOptionsExtensions_AddIISUrlRewrite_Microsoft_AspNetCore_Rewrite_RewriteOptions_System_IO_TextReader_System_Boolean_)

[`Microsoft.AspNetCore.Rewrite.IISUrlRewriteOptionsExtensions.AddIISUrlRewrite(RewriteOptions, IFileProvider, String, Boolean)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.rewrite.iisurlrewriteoptionsextensions.addiisurlrewrite?view=aspnetcore-3.1#Microsoft_AspNetCore_Rewrite_IISUrlRewriteOptionsExtensions_AddIISUrlRewrite_Microsoft_AspNetCore_Rewrite_RewriteOptions_Microsoft_Extensions_FileProviders_IFileProvider_System_String_System_Boolean_)

This is the discussion issue for the following announcement: aspnet/Announcements#420

---
#### Issue metadata

* Issue type: breaking-change

**Comment by Tratcher** [comment]
> I am sorry if this is the wrong place to post this question but hopefully it will help clarify for others also. It sounds like the URL Rewrite functionality is included as middleware with .NET 5 and the module is no longer needed. Can you please clarify this? If so, is anything needed to enable it?

@dbowser The middleware has been available for several releases. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-3.1#when-to-use-url-rewriting-middleware

**Comment by KalleOlaviNiemitalo** [comment]
The announcement itself says "This is the discussion issue for the following announcement" 😂
