### ISSUE TITLE
Question: Calling protected API from non-Page level component in ASP.Net Core hosted Blazor Wasm application

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#22987]
I have a need to populate a dropdown by calling my api which has an [Authorize] attribute. This dropdown lives in the top nav of my application, and not in any of the pages. All my pages also have an Authorize attribute. I would prefer to call this api to populate the dropdown once in the beginning.

My problem is I am unable to find an elegant way/place in my client to place the code that will fetch the dropdown data from the api, and store it in my AppState container, to which the dropdown is bound to; I am looking for something commensurate to an App_Start type of an event on the client. Further, I even tried placing the component containing my dropdown inside MainLayout, but it fails when user first opens the app, because the code inside MainLayout to fetch the data from api runs before the app has a chance to authenticate and retrieve the token.

I can certainly hack my way through this problem, but I am looking for a suggested best practice to run such one-time code, especially if that code depends on retrieving data from a protected endpoint. And that we can avoid a race condition where multiple components are trying to call protected apis, catching AccessTokenNotAvailableException and performing redirect to the token service.

**Comment by SteveSandersonMS** [comment]
You could put your data-fetching component inside an `<AuthorizeView>` in your layout, e.g. in `MainLayout.razor`:

```razor
<AuthorizeView>
    <MyComponentThatFetchesProtectedData />
</AuthorizeView>
```

Then it will only be instantiated and rendered once the user is confirmed as logged-in.

**Comment by javiercn** [comment]
[Here](https://github.com/javiercn/BlazorShareData) is a sample of what @SteveSandersonMS is talking about.

**Comment by bancroftway** [comment]
I followed @SteveSandersonMS 's suggestion exactly, but I experienced the same race condition when opening the app in a new browser window. 

In the bottom left of the browser, I can see the app is stuck in an infinite loop, where it constantly tries to connect to login.microsoftonline.com, even though my page has already authenticated and user is able to interact with the page. Please see this screenshot. I can also try to put together a video demonstrating this issue. Thanks

![image](https://user-images.githubusercontent.com/13262438/84948679-ae686a80-b0b1-11ea-936e-0f5dc97552a5.png)
