### ISSUE TITLE
Blazor App HttpClient Property Credentials is not supported.

### ISSUE THREAD

**Issue by sassy224** [dotnet/aspnetcore#22986]
Sets NetworkCredentials for HttpClient in a Blazor WebAssembly app will throw exception:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Property Credentials is not supported.
System.PlatformNotSupportedException: Property Credentials is not supported.
  at System.Net.Http.HttpClientHandler.set_Credentials (System.Net.ICredentials value) <0x37096f0 + 0x0000c> in <filename unknown>:0 
```
Steps to reproduce
- Create a new Blazor WebAssembly App targets .Net Core 3.1 (all package versions are 3.2.0)
- Edit method IncrementCount in Counter.razor:
```
private void IncrementCount()
    {
        currentCount++;

        HttpClientHandler sHandler = new HttpClientHandler();
        sHandler.Credentials = new System.Net.NetworkCredential("username", "password", null);
        HttpClient client = new HttpClient(sHandler);
    }
```
- Run blazor, navigate to Counter, press button, error is shown in console.

That snippet code works fine in blazor server, or any asp net/net core website, or even in console app. 
Judging from exception, seems it's intended. Is there any way I can set credentials for HttpClient which is working for Blazor WebAssembly app and all other applications?

**Comment by javiercn** [comment]
@sassy224 thanks for contacting us.

It is likely that is not supported on the underlying WasmHttpHandler since that's not something you can achieve with the `fetch` APIs.

/cc:@pranavkm in case he wants to add anything
