### ISSUE TITLE
If the name of the parent folder of the project/solution's folder contains a space, some razor intellisense won't work

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/aspnetcore#22982]
**Visual Studio Version**:
Microsoft Visual Studio Community 2019
Version 16.6.0
VisualStudio.16.Release/16.6.0+30114.105
Microsoft .NET Framework
Version 4.8.03752

**Summary**:
If the name of the parent folder of the project/solution's folder contains a space, some razor intellisense won't work, in ASP.Net Core 3.1 projects.

**Steps to Reproduce**:
1. Create a folder on your drive named Temp or Test, then create a sub folder that has a space in the name, like _Project Test_.

2. Open Visual Studio, and create a .Net Core 3.1 web app, and for location, use the folder you created with the space in the name, _Project Test_. Make sure the “Place solution and project in the same directory” checkbox is turn on/selected.

3. Use ASP.Net Core 3.1, name the project TestCoreWeb1 and use the “Web Application” template.
    The final folder structure should be something like:
    C:\Temp\Project Test\TestCoreWeb1

4. Double-click the Index.cshtml page to open it in the razor editor. Anywhere in the page, type the following:

`<script src="`

After typing the opening double quotation mark, I do not get intellisense, because this project is located in a parent folder with a space in the name.

If you close Visual Studio, then remove the space from the parent folder, Intellisense works correctly.

**Expected Behavior**:
Razor intellisense still works even though there's a space in the parent folder's name

**Actual Behavior**:
Intellisense doen't work.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by Dean-NC** [comment]
@mkArtakMSFT  Who do you think might own it???
