### ISSUE TITLE
Service start timeout issue for self-hosted webserver as windows service

### ISSUE THREAD

**Issue by engfro** [dotnet/aspnetcore#22994]
Hi - working on this .netcore 3.1 project where we are hosting a self-contained webserver (http.sys w/windows auth) as a windows service. For the most part startup seems to be working fine, but we sometimes see this 30sec timeout issue during windowsservice-startup and have a hard time figuring out what is causing this behavior. We also have several regular .net framework 4.7.2 windows services, but they don't seem to suffer from the 30sec startup issue as the .net core one do.

I created this simple GitHub project https://github.com/engfro/WebFrontend which for the most part reflects our current setup. The problem seems to be that hostBuilder.Build(); can't finish it's execution within the default 30sec windows service startup intervall. Hoping for any pointers in what could be causing this startup issue.

Windows Error Reporting is enabled, but it hasn't registered any crashdumps yet for the application when the timeout issue occurs.

We've done some experimentation with the PublishReadyToRun parameter for dotnet publish command, but it doesn't seem to improve things too much.

Side note:
When we added the PublishSingleFile parameter to dotnet publish the application started to return 404 to css/js requests, but that is perhaps another issue.

**Comment by bfbrown** [comment]
Calling .ConfigureWebHost() instead of .ConfigureWebHostDefaults() fixed a similar timeout I had.

**Comment by engfro** [comment]
Ok, thanks - I'll test it out and see if it solves my issue as well. 
Did you find out what the actual difference between the two callse are?

From the docs it seems ConfigureWebHostDefaults() is the one to use (https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp/Program.cs), but it is worth a try to test your suggestion

**Comment by engfro** [comment]
Sample log output (still using ConfigureWebHostDefaults) - this one happened to start within 30 seconds, but that's not always the case
2020-06-18 08:42:19.049 +02:00 [WRN] Starting up ... (IsWindowsService=True)
2020-06-18 08:42:20.415 +02:00 [WRN] Start creating host builder
2020-06-18 08:42:20.479 +02:00 [WRN] Start CreateDefaultBuilder
2020-06-18 08:42:20.769 +02:00 [WRN] Done CreateDefaultBuilder
2020-06-18 08:42:20.769 +02:00 [WRN] Start ConfigureWebHostDefaults
2020-06-18 08:42:21.975 +02:00 [WRN] End ConfigureWebHostDefaults
2020-06-18 08:42:21.976 +02:00 [WRN] Start UseSerilog
2020-06-18 08:42:21.976 +02:00 [WRN] End UseSerilog
2020-06-18 08:42:21.976 +02:00 [WRN] Start UseWindowsService
2020-06-18 08:42:21.994 +02:00 [WRN] End UseWindowsService
2020-06-18 08:42:21.994 +02:00 [WRN] Done creating host builder
2020-06-18 08:42:21.994 +02:00 [WRN] Start building host
2020-06-18 08:42:33.114 +02:00 [WRN] Done building host
2020-06-18 08:42:33.115 +02:00 [WRN] Start running host (async)
2020-06-18 08:42:34.748 +02:00 [INF] User profile is available. Using 'C:\WINDOWS\system32\config\systemprofile\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2020-06-18 08:42:43.934 +02:00 [INF] Start
2020-06-18 08:42:43.979 +02:00 [INF] Listening on prefix: http://*:5000/
2020-06-18 08:42:43.990 +02:00 [INF] Now listening on: http://*:5000
2020-06-18 08:42:44.006 +02:00 [INF] Application started. Hosting environment: Production; Content root path: C:\Temp\Web Frontend Service\

**Comment by engfro** [comment]
Anyone from the aspnetcore crew that has any idea what could be causing this timeout issue? @Tratcher @javiercn

**Comment by engfro** [comment]
Calling ConfigureWebHost() instead of ConfigureWebHostDefaults() didn't fix our issue

**Comment by Tratcher** [comment]
> When we added the PublishSingleFile parameter to dotnet publish the application started to return 404 to css/js requests, but that is perhaps another issue.

That's a known issue https://github.com/dotnet/runtime/issues/36065

Your readme gives several different publish profiles. Which are you using in the examples above?

Do you have the same timing issues when you try to start the app normally, not from a windows service?

**Comment by Tratcher** [comment]
It's odd that even when it is starting, the Build step takes 11 seconds. 

The build step is primarily building the DI container which logging depends on, so it's not possible to log until it's done.

There are a few other things you can try to narrow the possibilities.
- Replace Host.CreateDefaultBuilder with `new HostBuilder` to create a minimal host.
- Replace ConfigureWebHostDefaults with ConfigureWebHost to create a minimal web server. [Already tried above]
- Try it without the webhost at all, just the HostBuilder.

**Comment by engfro** [comment]
Tried the _new HostBuilder()_ for a minimal host suggestion, but we had the same timeout issue on some of our VMs this morning so that didn't work out.

As a workaround - for us - we have written some custom code so one of our other services now act as a service monitor and tries to restart this particular service if it was not started succesfully. This seems to be working fine. 
So the trouble then seems to be that during deployment/server (re)start there are many (of our) services (.net 4.7.2 services) starting up and doing "heavy lifting" in the process, and when the .net core 3.1 service in turn tries to start up it always seems to get the short end of the stick and time out. The service monitor will then, after a configured interval of 5 minutes, try to restart the .net core service. And this works, most likely because the other services now have finished their internal migrations etc and are up'n'running

**Comment by Tratcher** [comment]
Sounds like you should delay starting the service until the others have started.

**Comment by rokx** [comment]
Is there a method to let windows know the service has started and after that configure the service as needed (ConfigureWebHostDefaults())?

**Comment by Tratcher** [comment]
@rokx to do that you'd implement your own ServiceBase derived class and not call UseWindowsService.

**Comment by marko-savic** [comment]
We had the same issue with the service timeout and .net core 3.1. 
Kestrel hosts Grpc, Blazor and we are using MongoDB and log4net.
After several days of trying to isolate an issue disabling Windows Defender seems to solve the problem.

**Comment by engfro** [comment]
@Tratcher Tried your suggestion and implemented a ServiceBase derived class and not call UseWindowsService. Seems to work mostly fine, BUT I'm now getting 404 for static content in wwwroot folder when run/hosted as a windows service. Running as a console app works fine.

Sample code here: https://github.com/engfro/WebFrontend

**Comment by Tratcher** [comment]
@engfro windows services start with a weird CurrentDirectory. You can override that like this:
https://github.com/dotnet/extensions/blob/6071f580f97b22109e99a96fbca22792b2c8e6c1/src/Hosting/WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs#L50

**Comment by engfro** [comment]
@Tratcher Thanks - that fixed the 404's

**Comment by sommmen** [comment]
I'm seeing the same issue when running our app on a customer machine. 
The customer machine i'm deploying this app to is not the fastest kid on the block, and especially a powercycle takes ages.
The startup of windows and the additional software takes a long time and the load is heavy during startup.

I'm running a very small ASP.NET core app using kestrel and `.UseWindowsService()`.
There's like 2 controllers and 3 endpoints total, and the only additional package is use is Serilog.

When I run this app from a customer machine and my development machine:
Running the app as a console app works without issue.
Running the app as a windows service works without issue.

However, now I set the startup type to 'automatic' and i powercycle the machine.
The service manager starts the app and i see it being logged to the logs.
Then the service shuts down. There is no error message, nothing in the windows event viewer.
I have not added logging from `IApplicationLifeTime` so i could do that next, perhaps i can log a shutdown request from the lifetime manager?

I do not see this behaviour in my development machine.
I Powercycle the machine, the service starts and stays on. 

The fix: Setting the windows service to startup-delayed. 
This seems to work on the customer machine and the app now  starts and stays on when the pc is booted.

I'm not too happy with this solution altough it works..

**Comment by sommmen** [comment]
I've found this seemingly related SO which also has a timeout issue. 
A User suggests to request more time via an own implementation of ServiceBase like suggested here before. 
It would be nice if the windows service lifetime manager from msdn would provide more guidance for dealing with a slow startup.

https://stackoverflow.com/questions/59987782/what-is-the-equivalent-to-the-servicebase-requestadditionaltime-in-net-core-usi
https://github.com/aspnet/Hosting/blob/master/samples/GenericHostSample/ServiceBaseLifetime.cs

**Comment by engfro** [comment]
@sommmen: Have you tried to drop the usage of .UseWindowsService() and instead write you own ServiceBase implementation? (sample code here: https://github.com/engfro/WebFrontend/blob/master/Startup.cs)

**Comment by dadude999** [comment]
> We had the same issue with the service timeout and .net core 3.1.
> Kestrel hosts Grpc, Blazor and we are using MongoDB and log4net.
> After several days of trying to isolate an issue disabling Windows Defender seems to solve the problem.

This seemed to work for me as well. It would be nice to know _why_ Defender caused this problem though!
