### ISSUE TITLE
Blazor - integrity checks fail on firefox over non secure connection but work in chrome

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#22999]
I have recently upgraded our asp.net core 3.1.0 hosted blazor app from blazor 3.2.0 preview 3 to 3.2.0.

We are noticing that we are gettting integritty check failures but only from Firefox. In google chrome it works fine. We have various developers all replicating the issue using clean installs of the latest version of firefox. The problem seems to be to do with the integrity check on blazor's dotnet script and we say that because thats the only script that we can see that uses a sha256 integrity check.

I noticed this issue: https://github.com/dotnet/aspnetcore/issues/22470 but it doesn't appear to cover our case because:

1. We don't push our published assets using git or kudo: Our flow is:
    - CI build is done by an Azure Devops Pipeline --> Hosted agent (latest windows) checks out code, and builds the solution and does a dotnet publish which is then uploaded as a zipped build artifact.
    - Azure DevOps "Releases" pipeline is then triggered which downloads the build artfifact, then does a DOCKER build, producing a docker image containing the published output.
    - push the docker image to ACR (Azure Container Registry)
   - deploy the image to an Azure App Service for Containers (windows) instance, - to a deployment slot.

We noticed that the site works fine in chrome (Version 83.0.4103.97 (Official Build) (64-bit))
However in latest firefox (77.0.1 (64-bit):

![image](https://user-images.githubusercontent.com/3176632/84773408-4728b880-afd4-11ea-8c7e-bbf81c1fa37f.png)

**Comment by javiercn** [comment]
@dazinator thanks for contacting us.

Can you tell us which file is having issues? Is it `dotnet.js`, `blazor.wasm` or any of the assemblies?

**Comment by dazinator** [comment]
@javiercn 
It seems to be on the `dotnet.js`. Here is the firefox concole output:

14:53:45.755
GEThttp://uniun-dev-pr159.azurewebsites.net/
[HTTP/1.1 304 Not Modified 222ms]

14:53:46.107
GEThttp://uniun-dev-pr159.azurewebsites.net/css/app.min.css
[HTTP/1.1 304 Not Modified 84ms]

14:53:46.122
GEThttps://fonts.googleapis.com/css?family=Montserrat&display=swap
[HTTP/2 200 OK 0ms]

14:53:46.134
GEThttps://fonts.googleapis.com/css?family=Open+Sans&display=swap
[HTTP/2 200 OK 0ms]

14:53:46.160
GEThttp://uniun-dev-pr159.azurewebsites.net/Scripts/clickAndPositionHandler.js
[HTTP/1.1 304 Not Modified 56ms]

14:53:46.161
GEThttps://use.fontawesome.com/releases/v5.10.2/css/all.css
[HTTP/2 200 OK 0ms]

14:53:46.177
GEThttp://uniun-dev-pr159.azurewebsites.net/js/gridblazor.js
[HTTP/1.1 304 Not Modified 72ms]

14:53:46.182
GEThttp://uniun-dev-pr159.azurewebsites.net/_framework/blazor.webassembly.js
[HTTP/1.1 304 Not Modified 57ms]

14:53:46.187
GEThttps://code.jquery.com/jquery-3.3.1.slim.min.js
[HTTP/1.1 200 OK 0ms]

14:53:46.225
GEThttps://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js
[HTTP/2 200 OK 0ms]

14:53:46.244
GEThttps://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js
[HTTP/2 200 OK 0ms]

14:53:46.772
GEThttps://fonts.googleapis.com/css?family=Montserrat&display=swap
[HTTP/2 200 OK 0ms]

14:53:46.787
GEThttps://fonts.googleapis.com/css?family=Open+Sans&display=swap
[HTTP/2 200 OK 0ms]

14:53:47.641
GEThttp://uniun-dev-pr159.azurewebsites.net/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

14:53:49.110
GEThttp://uniun-dev-pr159.azurewebsites.net/_framework/wasm/dotnet.3.2.0.js
[HTTP/1.1 304 Not Modified 327ms]

14:53:51.792 None of the “sha256” hashes in the integrity attribute match the content of the subresource. uniun-dev-pr159.azurewebsites.net
14:53:51.828 TypeError: NetworkError when attempting to fetch resource.

**Comment by dazinator** [comment]
Here it is again, with caching disabled:

![image](https://user-images.githubusercontent.com/3176632/84784814-a55c9800-afe2-11ea-9458-6a5d5478bec5.png)

I have noticed that the SSL cert is not trusted by Firefox (is the standard one that azure websites uses), and GET requests are sent over http rather than https. Could that be the cause of this issue? This didn't seem to be a problem before the upgrade from preview3

**Comment by dazinator** [comment]
I can confirm that it works in Chrome, but the difference with chrome, is that even though it doesn't trust the cert, it still requests the files over HTTPS not HTTP. Firefox seems to fall back to HTTP. Not sure why this would effect the hash check in anyway?

**Comment by javiercn** [comment]
@dazinator hmm, not sure why the cert is untrusted on Firefox, but on azurewebsites it should be. It is weird that it works on Chrome/Edge vs Firefox. Are you using a custom cert or a proxy that MiTM https traffic?

**Comment by javiercn** [comment]
This doesn't seem to be a problem with the file itself nor the hash since it works on Chrome/Edge. I would try to download the file from firefox directly and check the integrity manually.

**Comment by javiercn** [comment]
Sometimes browsers report an integrity issue when the actual cause is that the browser blocks the download or something similar. Do you have CSP enabled by any chance?

**Comment by dazinator** [comment]
@javiercn
- no content security policy is not enabled.
- no I am not using in special MITM or proxy, this is a vanilla app service (for windows containers) and here are the network settings (I have not set up any SSL cert so its using whatever azure serves up by default):

![image](https://user-images.githubusercontent.com/3176632/84786068-29fbe600-afe4-11ea-8c66-dee499c3c03d.png)

With respect to:
> This doesn't seem to be a problem with the file itself nor the hash since it works on Chrome/Edge. I would try to download the file from firefox directly and check the integrity manually.

Any directions for the easiest way to do that on windows would be much appreciated!
Assuming it is valid (as it works in chrome) this would indicate a firefox bug - and this would mean it should be easy to replicate or verify on the ms side?

**Comment by dazinator** [comment]
Here is a gist containing the dotnet script returned from firefox's GET request over http, which it then fails the integrity check on:

https://gist.github.com/dazinator/696cbd50223ab00a36c47c0fcf4598d3

Here is the equivalent which succeeds in chrome (requested over https):

https://gist.github.com/dazinator/818a4044bee1176886abe06a0d353ff7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by dazinator** [comment]
So as of yesterday evening - stuff magically started working in firefox. Firefox now reports that it trusts the SSL cert for our .azurewebsites.net site hosted in app service for windows containers, where as - previoulsy, when I was seeing this problem, firefox was reporting it didn't trust that certificate (we tested from multiple machines). Not sure what has changed but perhaps there was an azure misconfiguration issue with app service for windows containers regarding SSL that was recently fixed?

Also - it was still very odd that Chrome worked fine, but the result in firefox was this integrity issue.
Seeing as I can no longer reproduce this, I can't investigate any further.

**Comment by dazinator** [comment]
Ok I have narrowed it down even further.
The difference I am seeing between chrome and firefox appears to be:

1. Resource integrity checks in firefox seem to always fail if the script is requested over a non secure connection. This could be your https localhost if you don't have a cert that firefox trusts. It doesn't matter if you "make an exception" for the site in firefox as this doesn't add trust for the cert.
2 Resource integrity checks in chrome seem to succeed even if the script is requested over a non secure connection. Chrome doesn't care as much about MITM attacks it seems.

**Comment by javiercn** [comment]
@dazinator different browsers follow difference rules for certificate validation. I suspect this has ben an HTTPS certificate issue all along that manifested itself in the integrity issue by virtue of Firefox sending the requests over HTTP vs HTTPS.

I'm going to close this since there's no Blazor issue here. Thanks for following up with an update.

**Comment by dazinator** [comment]
@javiercn 
> I suspect this has ben an HTTPS certificate issue all along that manifested itself in the integrity issue by virtue of Firefox sending the requests over HTTP vs HTTPS.

Not quite..
If you run a blazor app locally on HTTP, and browse to it over HTTP in firefox, I am seeing resource integrity checks fail. It looks like to me firefox "requires" https for integrity checks to work. Then in addition to that, yes firefox also requires a valid cert - if you browse over HTTPS but with a non valid cert firefox will fallback to requesting assets over HTTP - but you can "make an excpetion" for the site - in which case firefox will send requests over HTTPS still - but as the connection is still deemed insecure - intgerity checks will fail.

So all in all, blazor fundamentally does not support Firefox if your site is hosted on HTTP. Is it worth documenting this somewhere?

**Comment by dazinator** [comment]
To elaborate a bit, I think the desired outcome from my perspective would be:

- Blazor apps can be served from a static file server on HTTP (for apps that really don't need HTTPS) and still work in firefox.

Which I think would mean something like:

- Give us a way to disable resource integrity checks when the site is served up over HTTP.

**Comment by javiercn** [comment]
> Not quite..
> If you run a blazor app locally on HTTP, and browse to it over HTTP in firefox, I am seeing resource integrity checks fail. It looks like to me firefox "requires" https for integrity checks to work.

This is a fair concern, but I'm not sure what we can do about it.

> If I want to host an application on HTTP and support firefox - how can I work around this without doing this: `<BlazorCacheBootResources>false</BlazorCacheBootResources>` whcich seems like it might be bad for performance? If supporting firefox means SSL is required or I have to take a perf hit, this would be good to know from the outset from the blazor docs - or alternatively have some issue open to track what can be done to improve this.

Resource caching already only works through HTTPS, I think disabling caching is the right way to go here. We can probably skip performing the integrity checks if the document is not in a secure context, since they are meaningless in that case and we don't do any caching.

Ultimately the right thing to do is to use HTTPS, but I have filed [this issue](https://github.com/dotnet/aspnetcore/issues/23082) to disable caching automatically over HTTP.

I don't believe that this affects chrome/edge since from what I understand caching requires a secure context.

**Comment by dazinator** [comment]
@javiercn 

> This is a fair concern, but I'm not sure what we can do about it.

The issue you have now created is the kind of thing I was looking for. Thank you.

**Comment by dazinator** [comment]
> Ultimately the right thing to do is to use HTTPS

Even when developing locally? If so you could consider backing that assertion by not having an HTTP binding present in all of the default blazor project templates!
