### ISSUE TITLE
User.identity and user.identity.name is null for only one user

### ISSUE THREAD

**Issue by DENMODSupport** [dotnet/aspnetcore#22995]
Hi,
User.Identity and User.Identity.Name is null for only one user while fetching the user id with domain in .cshtml page. But the same thing (User.Identity.Name) is working fine in one HTML page. In .cshtml page it was used under script section but in HTML page it was used under body section. This is the only difference i have seen in these two pages. 
Is there any alternative to fetch user id with domain? or Could you please help me to fix this issue for that user alone?

**Comment by blowdart** [comment]
What authentication type are you using? You say domain, so is this Windows authentication?

**Comment by DENMODSupport** [comment]
yes, it is windows authentication

**Comment by blowdart** [comment]
Strange indeed. 

- Is the user special in any way? 
- Are you hosting underneath IIS? If so is it set to require Windows Auth *and* disable anonymous auth?
- What does User.Identity.IsAuthenticated  return?

**Comment by DENMODSupport** [comment]
1. Is the user special in any way? No
2. Are you hosting underneath IIS? If so is it set to require Windows Auth and disable anonymous auth? Yes it is hosted in IIS. Windows authentication is enabled and disabled anonymous authentication.
3. What does User.Identity.IsAuthenticated return? As told earlier in one HTML page, User.Identity.IsAuthenticated returns true

**Comment by DENMODSupport** [comment]
Please provide an update on this.

**Comment by blowdart** [comment]
Can you share the cshtml page?
