### ISSUE TITLE
fieldset not working properly with blazor

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#23009]
when i use this code in an html page
```html
<fieldset>
        <legend>Test</legend>
        <svg width="39vw" id="sample" height="100%" viewBox="0 0 100 100" class="mainbackground sampletrain" xmlns="http://www.w3.org/2000/svg">
            <!--
        with relative unit such as percentage, the visual size
        of the square looks unchanged regardless of the viewBox
        -->
            <rect x="0" y="0" width="100%" height="100%" fill="aqua" />


        </svg>
    </fieldset>
```
it works perfectly.  However, when i do the same thing with blazor, it shows no borders.  I was able to work around the border issue by using css.  However, the top border does not show up if legend is used and the text for the legend was too big as well.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

Does it work if you remove bootstrap from the app?

**Comment by musictopia2** [comment]
How do you remove bootstrap from the app?  Since it shows that to begin with, then not sure if its even possible to remove.

**Comment by musictopia2** [comment]
I figured out by commenting the bootstrap it removed it.  When I did that, it worked perfectly.

**Comment by javiercn** [comment]
@musictopia2 I'm glad that you figured it out.

I'm closing this issue since it is not related to Blazor.
