### ISSUE TITLE
asp.net core 3.1 webapi use stream-based upload large file in chunks

### ISSUE THREAD

**Issue by myunQ** [dotnet/aspnetcore#23005]
How to use stream-based file upload in asp.net core 3.1 WebApi?

I need to upload large files in chunks, and it is a stream-based upload method.

I have read this document (https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1), but it doesn't seem to help me much.

**Comment by javiercn** [comment]
Thanks for contacting us @myunQ.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag.

I don't know what you mean by `stream-based`. If you want to split the file in chunks and upload each chunk separately, create an endpoint that receives the chunk data, the offset and the type and store each chunk separately or append them somewhere?

**Comment by myunQ** [comment]
Upload large files with streaming

**Comment by javiercn** [comment]
@myunQ can you provide a minimal repro so that we can try helping you?

**Comment by myunQ** [comment]
@javiercn Sorry, we don't have a budget, I mistakenly think it is free. Sorry, I will find another way.
