### ISSUE TITLE
Deployment file proliferation

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#23018]
### Bug description

When deploying my ASP.NET Core 3.1 Razor Pages web site, I am dismayed by the number of files produced.

This is a small website I've only been developing for a couple of weeks. The root directory has 76 files and folders. It appears there are about 15 language folders (I only need English), and the *runtimes* folder contains a bunch of subfolders that appear platform related (I only need Windows).

```
alpine-x64
linux-arm
linux-arm64
linux-armel
linux-musl-x64
linux-x64
linux-x86
osx-x64
unix
win
win-arm
win-arm64
win-x64
win-x86
```

The deployment uses *Framework-Dependent* mode.

A workaround for the language folders appears to be to set the *ExcludeAssets* property of the *Microsoft.VisualStudio.Web.CodeGeneration.Design* package to *All*.

After trying several other techniques to prevent the platform folders, I have still not found a workaround.

My question is why do I need to find a workaround? It feels like the developers don't really care how many files are in my deployment and so everything gets thrown in there. It's troubling that the developers do not share my values.

### Further technical details

.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@SoftCircuits thanks for contacting us.

> A workaround for the language folders appears to be to set the _ExcludeAssets_ property of the _Microsoft.VisualStudio.Web.CodeGeneration.Design_ package to _All_.

I wouldn't consider this a workaround.

@vijayrkn does Visual Studio not mark assets for exclusion when adding the scaffolder?

**Comment by mkArtakMSFT** [comment]
This issue was moved to dotnet/Scaffolding#1354

**Comment by vijayrkn** [comment]
@javiercn - we don't set it today. I have a pending PR for fixing this - https://github.com/dotnet/Scaffolding/pull/1138 but needs some additional changes on the vs side before this can be merged.
