### ISSUE TITLE
Try to dedupe helix content scripts with eng/scripts

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#23021]
Ideally we can copy scripts from eng/scripts that are identical

**Comment by dougbu** [comment]
👀

**Comment by dougbu** [comment]
From https://github.com/dotnet/aspnetcore/pull/23116#issuecomment-646392467:
> There really isn't much overlap, installnode.ps1 is the only other one really, although install chrome likely will be the next candidate once selenium tests light up

We're reused this issue a couple of times now. Should we track further de-duping in a new issue❔ Or, are you saying further work to minimize the somewhat-duplicated scripts isn't worthwhile❔

**Comment by HaoK** [comment]
Yeah its not worth it right now, there's only one file which is slightly different
