### ISSUE TITLE
System.Reflection.TargetInvocationException System.TypeLoadException: Could not load type of field

### ISSUE THREAD

**Issue by Nullstr1ng** [dotnet/aspnetcore#23028]
# Describe the bug
We are a company developing a system for a client which requires a chat functionality for Support. This client application is a Xamarin application and our server supports SignalR - WHICH IS TOTALLY WORKING flawlessly in any web app clients that connects to it.

Now for our Xamarin application, we're done in the first feature and we're at the 2nd iteration which requires Chat. I first installed that latest stable version of **microsoft.aspnetcore.signalr.client** version 3.1.5. Running the app and the splash screen loaded, the app terminates it self with throwing us

`06-17 03:16:35.213 I/MonoDroid(18297): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type of field 'Microsoft.AspNetCore.Http.Features.Authentication.HttpAuthenticationFeature:<Handler>k__BackingField' (1) due to: Could not resolve type with token 01000080 from typeref (expected class 'Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler' in assembly 'Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler member:(null)** `

We tried installing *Microsoft.AspNetCore.Http.Features* 2.2.0.0 with no luck. We downgraded the version of the pacakge *microsoft.aspnetcore.signalr.client* from 3.1.5 to 1.1.0 and we are now able to run the application.

Ok so that is working. 1.1.0 is working but we need the ConnectionId which is not available in 1.1.0 

Other web app clients are using 5.0 and not issues at all. Our Xamarin app doesn't work at version 5.0 down to 3x. It's just work with 1.1.0

### To Reproduce
I really do not know how to reproduce but it's simply installing microsoft.aspnetcore.signalr.client latest stable version from Xamarin.Forms 4.6.0.800 application

### Exceptions (if any)
`06-17 03:16:35.169 I/MonoDroid(18297): UNHANDLED EXCEPTION:
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
06-17 03:16:35.213 I/MonoDroid(18297): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type of field 'Microsoft.AspNetCore.Http.Features.Authentication.HttpAuthenticationFeature:<Handler>k__BackingField' (1) due to: Could not resolve type with token 01000080 from typeref (expected class 'Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler' in assembly 'Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Http.Features, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Http.Features.Authentication.IAuthenticationHandler member:(null)
06-17 03:16:35.213 I/MonoDroid(18297):   at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
06-17 03:16:35.213 I/MonoDroid(18297):   at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System/RuntimeTypeHandle.cs:265 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/rttype.cs:3809 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.VisualTypeConverter.Register (System.Reflection.Assembly assembly, System.Collections.Generic.Dictionary`2[TKey,TValue] mappings) [0x00019] in D:\a\1\s\Xamarin.Forms.Core\Visuals\VisualTypeConverter.cs:63 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.VisualTypeConverter.InitMappings () [0x0001a] in D:\a\1\s\Xamarin.Forms.Core\Visuals\VisualTypeConverter.cs:21 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.VisualTypeConverter.ConvertFromInvariantString (System.String value) [0x00007] in D:\a\1\s\Xamarin.Forms.Core\Visuals\VisualTypeConverter.cs:118 
06-17 03:16:35.213 I/MonoDroid(18297):   at MASKED.Business.Mobile.MASKED.UI.Pages.SupportPages.Support.InitializeComponent () [0x00056] in F:\EAP\MASKED\MASKED.Business.Mobile\MASKED.Business.Mobile.MASKED\obj\Debug
etstandard2.1\Pages\SupportPages\Support.xaml.g.cs:38 
06-17 03:16:35.213 I/MonoDroid(18297):   at MASKED.Business.Mobile.MASKED.UI.Pages.SupportPages.Support..ctor () [0x00008] in F:\EAP\MASKED\MASKED.Business.Mobile\MASKED.Business.Mobile.MASKED\Pages\SupportPages\Support.xaml.cs:13 
06-17 03:16:35.213 I/MonoDroid(18297):   at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
06-17 03:16:35.213 I/MonoDroid(18297):   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
06-17 03:16:35.213 I/MonoDroid(18297):    --- End of inner exception stack trace ---
06-17 03:16:35.213 I/MonoDroid(18297):   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00018] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:944 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/ReferenceSources/RuntimeType.cs:185 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/ReferenceSources/RuntimeType.cs:155 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/rttype.cs:5770 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00039] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/activator.cs:206 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/activator.cs:190 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.Activator.CreateInstance (System.Type type) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/activator.cs:134 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.Routing+TypeRouteFactory.GetOrCreate () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Routing.cs:193 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.Routing.GetOrCreateContent (System.String route) [0x00011] in D:\a\1\s\Xamarin.Forms.Core\Routing.cs:61 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.ShellSection.GoToAsync (Xamarin.Forms.NavigationRequest request, System.Collections.Generic.IDictionary`2[TKey,TValue] queryData, System.Nullable`1[T] animate) [0x0046f] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellSection.cs:424 
06-17 03:16:35.213 I/MonoDroid(18297):   at Xamarin.Forms.Shell.GoToAsync (Xamarin.Forms.ShellNavigationState state, System.Nullable`1[T] animate, System.Boolean enableRelativeShellRoutes) [0x005fd] in D:\a\1\s\Xamarin.Forms.Core\Shell\Shell.cs:571 
06-17 03:16:35.213 I/MonoDroid(18297):   at MASKED.Business.Mobile.MASKED.UI.Services.NavService.NavigateTo (MASKED.Business.Mobile.CoreLibrary.Enums.MASKED.Enum_Pages page, System.String query) [0x00046] in F:\EAP\MASKED\MASKED.Business.Mobile\MASKED.Business.Mobile.MASKED\Services\NavService.cs:22 
06-17 03:16:35.213 I/MonoDroid(18297):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
06-17 03:16:35.213 I/MonoDroid(18297):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <184f0c79b2a1439495b8bd198fbfb408>:0 
06-17 03:16:35.214 I/MonoDroid(18297):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <184f0c79b2a1439495b8bd198fbfb408>:0 
06-17 03:16:35.214 I/MonoDroid(18297):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <184f0c79b2a1439495b8bd198fbfb408>:0 
06-17 03:16:35.214 I/MonoDroid(18297):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.27(intptr,intptr)
06-17 03:16:35.243 D/Mono    (18297): DllImport searching in: '__Internal' ('(null)').
06-17 03:16:35.243 D/Mono    (18297): Searching for 'java_interop_jnienv_throw'.
06-17 03:16:35.243 D/Mono    (18297): Probing 'java_interop_jnienv_throw'.
06-17 03:16:35.243 D/Mono    (18297): Found as 'java_interop_jnienv_throw'.`

### Further technical details
- ASP.NET Core version - 3.1
- IDE: Visual Studio 2019 Pro

**Comment by BrennanConroy** [comment]
> in assembly 'Microsoft.AspNetCore.Http.Features, Version=2.2.0.0

Can you figure out who is referencing this version of the assembly? 3.1 of the SignalR client references 3.1 of that package, but it looks like your app is bringing in 2.2, which is wrong.

**Comment by MagicAndre1981** [comment]
open `project.assets.json` in `obj` folder and look where the 2.2.0 reference comes from.

**Comment by Nullstr1ng** [comment]
got these from project.assets.json

`Search "/2.2.0"" (51 hits in 1 file)
  F:\EAP\MASKED\MASKED.Business.Mobile\MASKED.Business.Mobile.CoreLibrary\obj\project.assets.json (51 hits)
	Line 42:       "Microsoft.AspNetCore.Authorization/2.2.0": {
	Line 55:       "Microsoft.AspNetCore.Connections.Abstractions/2.2.0": {
	Line 92:       "Microsoft.AspNetCore.Hosting.Abstractions/2.2.0": {
	Line 106:       "Microsoft.AspNetCore.Hosting.Server.Abstractions/2.2.0": {
	Line 135:       "Microsoft.AspNetCore.Http.Abstractions/2.2.0": {
	Line 175:       "Microsoft.AspNetCore.Http.Extensions/2.2.0": {
	Line 190:       "Microsoft.AspNetCore.Http.Features/2.2.0": {
	Line 277:       "Microsoft.AspNetCore.StaticFiles/2.2.0": {
	Line 293:       "Microsoft.AspNetCore.WebUtilities/2.2.0": {
	Line 363:       "Microsoft.Extensions.Configuration.FileExtensions/2.2.0": {
	Line 397:       "Microsoft.Extensions.FileProviders.Abstractions/2.2.0": {
	Line 409:       "Microsoft.Extensions.FileProviders.Physical/2.2.0": {
	Line 422:       "Microsoft.Extensions.FileSystemGlobbing/2.2.0": {
	Line 431:       "Microsoft.Extensions.Hosting.Abstractions/2.2.0": {
	Line 470:       "Microsoft.Extensions.ObjectPool/2.2.0": {
	Line 506:       "Microsoft.Extensions.WebEncoders/2.2.0": {
	Line 574:       "Microsoft.Net.Http.Headers/2.2.0": {
	Line 2533:     "Microsoft.AspNetCore.Authorization/2.2.0": {
	Line 2536:       "path": "microsoft.aspnetcore.authorization/2.2.0",
	Line 2546:     "Microsoft.AspNetCore.Connections.Abstractions/2.2.0": {
	Line 2549:       "path": "microsoft.aspnetcore.connections.abstractions/2.2.0",
	Line 2572:     "Microsoft.AspNetCore.Hosting.Abstractions/2.2.0": {
	Line 2575:       "path": "microsoft.aspnetcore.hosting.abstractions/2.2.0",
	Line 2585:     "Microsoft.AspNetCore.Hosting.Server.Abstractions/2.2.0": {
	Line 2588:       "path": "microsoft.aspnetcore.hosting.server.abstractions/2.2.0",
	Line 2611:     "Microsoft.AspNetCore.Http.Abstractions/2.2.0": {
	Line 2614:       "path": "microsoft.aspnetcore.http.abstractions/2.2.0",
	Line 2652:     "Microsoft.AspNetCore.Http.Extensions/2.2.0": {
	Line 2655:       "path": "microsoft.aspnetcore.http.extensions/2.2.0",
	Line 2665:     "Microsoft.AspNetCore.Http.Features/2.2.0": {
	Line 2668:       "path": "microsoft.aspnetcore.http.features/2.2.0",
	Line 2745:     "Microsoft.AspNetCore.StaticFiles/2.2.0": {
	Line 2748:       "path": "microsoft.aspnetcore.staticfiles/2.2.0",
	Line 2758:     "Microsoft.AspNetCore.WebUtilities/2.2.0": {
	Line 2761:       "path": "microsoft.aspnetcore.webutilities/2.2.0",
	Line 2900:     "Microsoft.Extensions.Configuration.FileExtensions/2.2.0": {
	Line 2903:       "path": "microsoft.extensions.configuration.fileextensions/2.2.0",
	Line 2947:     "Microsoft.Extensions.FileProviders.Abstractions/2.2.0": {
	Line 2950:       "path": "microsoft.extensions.fileproviders.abstractions/2.2.0",
	Line 2960:     "Microsoft.Extensions.FileProviders.Physical/2.2.0": {
	Line 2963:       "path": "microsoft.extensions.fileproviders.physical/2.2.0",
	Line 2973:     "Microsoft.Extensions.FileSystemGlobbing/2.2.0": {
	Line 2976:       "path": "microsoft.extensions.filesystemglobbing/2.2.0",
	Line 2986:     "Microsoft.Extensions.Hosting.Abstractions/2.2.0": {
	Line 2989:       "path": "microsoft.extensions.hosting.abstractions/2.2.0",
	Line 3029:     "Microsoft.Extensions.ObjectPool/2.2.0": {
	Line 3032:       "path": "microsoft.extensions.objectpool/2.2.0",
	Line 3074:     "Microsoft.Extensions.WebEncoders/2.2.0": {
	Line 3077:       "path": "microsoft.extensions.webencoders/2.2.0",
	Line 3165:     "Microsoft.Net.Http.Headers/2.2.0": {
	Line 3168:       "path": "microsoft.net.http.headers/2.2.0",
Search "MASKED" (28 hits in 4 files)`

In our Xamarin application, we have Services libraries which is is also used in out Business.Api which is running in our backend server. This library is written in class library .NetStandard 2.1 which is mainly written for the backend API.

**Comment by Nullstr1ng** [comment]
If i.e. I found the one that is referencing 2.2.0, can I just directly install Microsoft.AspNetCore.Http.Features 3.1.5  to those projects?

**Comment by Nullstr1ng** [comment]
I installed Microsoft.AspNetCore.Http.Features 3.1.5 to all the projects.. still getting the same error. Sorry, it's been 3 hours fighting with this one. 

SignalR.Client is working as it should in a clean Xamarin.Forms application.

**Comment by BrennanConroy** [comment]
Have you found out who is bringing in the 2.2 package?

**Comment by Nullstr1ng** [comment]
> Have you found out who is bringing in the 2.2 package?

How? I am only installing the microsoft.aspnetcore.signalr.client package in my core library for Xamarin. 

Though in my core library, there are dependencies which are written in .NetStandard 2.1 (ServicesLibrary.Client and some Utilities/Helpers) which is also being used in Business.Api (where all the API controllers reside). This ServicesLibrary.Client and the Utilities were written before we started the mobile app.

Here are the libraries where Microsoft.AspNetCore.Http.Features, Version=2.2.0.0 are installed and used in my CoreLib for Xamarin.  
(pointed by the arrow)  
![image](https://user-images.githubusercontent.com/260633/85018237-6b84c080-b19f-11ea-8999-51f3dab9d245.png)

**Comment by Nullstr1ng** [comment]
checking back 3.1.5 again

It looks like Microsoft.AspNetCore.Http.Features 3.1.5 is installed?
![image](https://user-images.githubusercontent.com/260633/85019388-5741c300-b1a1-11ea-88c6-dfeb5cc2bfbe.png)

**Comment by BrennanConroy** [comment]
You should probably update your other libraries too. Mixing versions isn't a great idea and also 2.2 is out of support.

**Comment by Nullstr1ng** [comment]
The error is coming from [Xamarin.Forms.Visual.Material](https://github.com/xamarin/Xamarin.Forms)

WHICH IS EXTREMELY WEIRD!!   
It doesn't sound like it's right but when I tried loading an empty page, everything is working! But when I added Visual="Material" it spits out the same error Microsoft.AspNetCore.Http.Features

Why devs at Xamarin?

closing this one now. But hunt down after 2 days

**Comment by MagicAndre1981** [comment]
[this package](https://www.nuget.org/packages/Xamarin.Forms.Visual.Material/) has no dependency to asp.net core.

The packages change causes nuget restore and the 2.2 was gone.

**Comment by Nullstr1ng** [comment]
> [this package](https://www.nuget.org/packages/Xamarin.Forms.Visual.Material/) has no dependency to asp.net core.
> 
> The packages change causes nuget restore and the 2.2 was gone.

Yes, I was checking the dependency graph as well and I did not see any asp.net core which is weird.

**Comment by Nullstr1ng** [comment]
following the stack trace
![image](https://user-images.githubusercontent.com/260633/85060495-ee297200-b1d7-11ea-8afe-821a27fd5d91.png)
