### ISSUE TITLE
Add some tests for ITicketStore for CookieAuth

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#23020]
Some context: https://github.com/dotnet/aspnetcore/pull/22732

**Comment by fstaffa** [comment]
Do I understand correctly that this is about adding tests to [CookieTests](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/test/CookieTests.cs ) for how [CookieAuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs) interacts with the ITicketStore from [CookieAuthenticationOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs)?

**Comment by HaoK** [comment]
Yup exactly that, test coverage for all the scenarios where ticket store is used

**Comment by fstaffa** [comment]
Thank you, will look into it and create a PR later this week

**Comment by blowdart** [comment]
Thank you @fstaffa!

I'm going to move this to backlog for now, once you're down please take it out of that milestone and we'll review the PR

**Comment by vaughanr** [comment]
Hi @blowdart @fstaffa,

I don't think this has been done. Could I give it a try?

**Comment by fstaffa** [comment]
I haven't started on it yet

**Comment by blowdart** [comment]
If @fstaffa hasn't started then sure, have at it :)

**Comment by vaughanr** [comment]
Great! I've started working on it. Just trying to cover a few reasonable scenarios.

**Comment by HaoK** [comment]
Have you guys  made any progress on adding tests for this?  If not I probably will do this as part of https://github.com/dotnet/aspnetcore/issues/41516
