### ISSUE TITLE
[Blazor Server Side] Setting @layout on _Imports.razor' project root folder freezes the project -- the browser page keeps loading forever

### ISSUE THREAD

**Issue by serge-wq** [dotnet/aspnetcore#23026]
### Describe the bug
Same issue as #11406. Just spent several hours trying to figure out what was happening. Maybe at least add a notice in the docs? Other than that, nothing new about this issue.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@serge-wq thanks for contacting us.

We'll get the docs updated. @guardrex can you put a warning on the section regarding layouts to warn people about this?
