### ISSUE TITLE
Is set value configuration.GetSection(“”).Value thread safe?

### ISSUE THREAD

**Issue by BrandoZhangTest** [dotnet/aspnetcore#23034]
I need to set in my asp.net core configuration a value from the header in every request. I'm doing like so:

```
public async Task Invoke(HttpContext context)
    {
        var companyId = context.Request.Headers["companyid"].ToString().ToUpper();
        configuration.GetSection("CompanyId").Value = companyId;

        await next(context);           
    }
```

It works fine. But is this the proper way? In case of multiple request at same time is there a risk of messing the values?

**Comment by Tratcher** [comment]
No, you shouldn't be modifying global state per request, at some point you'll hit a race condition.

Per request state should go into HttpContext.Items.
