### ISSUE TITLE
ModelBinder binding decimal value from JSON to long after rounding it instead of throwing error.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#23031]
I have the following model class:

    public class CreatePayoutRequestModel
    {
        public long UserId { get; set; }

        public byte AccountTypeId { get; set; }

        public decimal Amount { get; set; }

        public string Password { get; set; }
    }

In my ASP.NET Core Web API controller method, I am posting the following JSON body:

```
{
  "userId": 10.50, // decimal number
  "accountTypeId": 2,
  "amount": 10.5,
  "password": "Hello123"
}
```
Weirdly, ASP.NET Core model binder rounding the decimal value `(10.50)` to `11` and setting it to `UserId` instead of throwing error.

**Note: I am using Newtonsoft.Json as default mvc seriliazer.**

Now I have the following questions:
1. Why this weird behavior? Is it intended? If intended what is the reason behind this?
2. Is this is causing by `Newtonsoft.Json`?
3. How can I stop this weird behavior of deserialization/model binding?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This looks like a question for Newtonsof.Json instead. Consider asking it on https://github.com/JamesNK/Newtonsoft.Json
//cc @JamesNK

**Comment by TanvirArjel** [comment]
@mkArtakMSFT, Thank you. I was thinking so. By the way, now I shall test with `System.Text.Json`.

**Comment by TanvirArjel** [comment]
@JamesNK, I have submitted this (https://github.com/JamesNK/Newtonsoft.Json/issues/2353) but you have not responded yet. Could you please give me an idea of how can I overcome this.
