### ISSUE TITLE
Issue with jsRuntime.InvokeVoidAsync and float/decimal

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/aspnetcore#23037]
I have issue with jsRuntime.Invoke trying to pass float or decimal values to javascript.
I have an object that has float and decimal properties. 
In javascript, we get them as integers (e,x, 15.4355 -> 154355)

I have greek culture in my pc and i have setup CultureInfo as el-GR in Program.cs

```
System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("el-GR");
System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo("el-GR");
```

**Comment by javiercn** [comment]
@xrkolovos thanks for contacting us.

What's the culture in the browser?
