### ISSUE TITLE
AuthenticationHandlerProvider not caching handlers between requests

### ISSUE THREAD

**Issue by mikenorgate** [dotnet/aspnetcore#23057]
### Describe the bug
It seems like `AuthenticationHandlerProvider` is designed to cache the handlers in `_handlerMap` so that a new handler is not created for every request, however due to `AuthenticationHandlerProvider` being registered a scoped  a new one is created for every request. https://github.com/dotnet/aspnetcore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/Authentication.Core/src/AuthenticationCoreServiceCollectionExtensions.cs#L29

~~This causes a problem when using the `JwtBearerHandler` as it causes it to reload its configuration on every request, if you have a metadata endpoint set this results in a request to get the metadata on every request making the caching done by `Microsoft.IdentityModel.Protocols.ConfigurationManager` irrelevant~~ This is not the case as configuration manager is cached by `IOptionsMonitorCache`, however there is still the call to `CreateInstance` on every request in `AuthenticationHandlerProvider` which will impact performance

### To Reproduce
```
services.AddAuthentication(options =>
{
    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultForbidScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(o =>
{
    o.Authority = securityConfig.AuthorityAddress;
    o.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        RequireExpirationTime = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,        
        RequireSignedTokens = true
    };
});
```

### Further technical details
- ASP.NET Core version 2.2

**Comment by blowdart** [comment]
Handlers have per request state on them, like Http request. Nor is there a requirement for handlers to be threadsafe. Therefor this is by design.
