### ISSUE TITLE
C# Curly Brace Smart Indent Does Not Start On New Line

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23053]
From: https://github.com/dotnet/aspnetcore/issues/22120

Found during validations: https://github.com/dotnet/aspnetcore/issues/22728

For:
```CSHTML
@if (true) {|}
```

Expected:
```CSHTML
@if (true)
{
    |
}
```
Actual:
![222120](https://user-images.githubusercontent.com/14852843/84930844-c1197a00-b086-11ea-9033-714aa9f26ef0.gif)

**Comment by NTaylorMullen** [comment]
This represents what it takes for us to "do the right thing"

**Comment by ajaybhargavb** [comment]
Fixed by https://github.com/dotnet/roslyn/issues/47691, https://github.com/dotnet/aspnetcore-tooling/pull/2769 and https://github.com/dotnet/aspnetcore-tooling/pull/2779
