### ISSUE TITLE
Support wireshark-style connection logging in Kestrel

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#23067]
I basically want @AndyPook's PR (https://github.com/davidfowl/BedrockFramework/pull/75) to add "wireshark style logging" to Kestrel's built in connection logging middleware. Unlike in BedrockFramework, we might want to make it opt-in to avoid breaking existing users.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/25139
