### ISSUE TITLE
[Discussion] Kestrel disables HTTP/2 over TLS by default on incompatible Windows versions

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#23068]
*This is the discussion for the announcement https://github.com/aspnet/Announcements/issues/421*

## Kestrel disables HTTP/2 over TLS by default on incompatible Windows versions

To enable HTTP/2 over TLS on Windows, two requirements need to be met: 
- ALPN support. This is available starting with Windows 8.1 and Windows Server 2012 R2 
- A set of ciphers compatible with HTTP/2. THis is available starting with Windows 10 and Windows Server 2016

As such, Kestrel's behavior when HTTP/2 over TLS is configured has been changed to:
- Downgrade to `Http1` and log a message at the `Information` level when [`ListenOptions.HttpProtocols`](https://github.com/dotnet/aspnetcore/blob/c4c6e25a0660ffbcae2d81c979495ec9533ccaff/src/Servers/Kestrel/Core/src/ListenOptions.cs#L79) is set to `Http1AndHttp2`. Note this is the default value for `ListenOptions.HttpProtocols`.
- Throw a `NotSupportedException` when [`ListenOptions.HttpProtocols`](https://github.com/dotnet/aspnetcore/blob/c4c6e25a0660ffbcae2d81c979495ec9533ccaff/src/Servers/Kestrel/Core/src/ListenOptions.cs#L79) is set to `Http2`.

While Windows 8.1 and Windows Server 2012 R2 are considered as incompatible since they don't have the necessary ciphers by default, it is possible to update the Computer Configuration settings to use HTTP/2 compatible ciphers, see [documentation](https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-8-1). Once configured, HTTP/2 over TLS on Kestrel must be explicitly enabled by setting the app context switch `Microsoft.AspNetCore.Server.Kestrel.EnableWindows81Http2`, e.g. 

```C#
AppContext.SetSwitch("Microsoft.AspNetCore.Server.Kestrel.EnableWindows81Http2", true);
```

Note that no underlying support has changed. For example, HTTP/2 over TLS has never worked on Windows 8 or Windows Server 2012. The change here modifies how errors in these unsupported scenario are presented.

### Version introduced

ASP.NET Core 5.0 preview 7

### Old behavior

When HTTP/2 over TLS is configured:

| HttpProtocols | Windows 7, <br /> Windows Server 2008 R2, <br /> or earlier | Windows 8, <br /> Windows Server 2012 | Windows 8.1, <br /> Windows Server 2012 R2 | Windows 10, <br /> Windows Server 2016, <br /> or newer |
|---------------|-----------------------------------------------|--------------------------------|-------------------------------------|------------------------------------------|
| Http2         | Throw NotSupportedException                   | Error during TLS handshake     | Error during TLS handshake &ast;     | No error                                 |
| Http1AndHttp2 | Downgrade to Http1                    | Downgrade to Http1     | Error during TLS handshake &ast;     | No error                                 |

&ast;: Compatible cipher suites need to be configured to enable these scenarios.

### New behavior

When HTTP/2 over TLS is configured:

| HttpProtocols | Windows 7, <br /> Windows Server 2008 R2, <br /> or earlier | Windows 8, <br /> Windows Server 2012 | Windows 8.1, <br /> Windows Server 2012 R2 | Windows 10, <br /> Windows Server 2016, <br /> or newer |
|---------------|-----------------------------------------------|--------------------------------|-------------------------------------|------------------------------------------|
| Http2         | Throw NotSupportedException                   | Throw NotSupportedException     | Throw NotSupportedException &ast;&ast;     | No error                                 |
| Http1AndHttp2 | Downgrade to Http1                    | Downgrade to Http1     | Downgrade to Http1 &ast;&ast;     | No error                                 |

&ast;&ast;: Compatible cipher suites need to be configured and the app context switch `Microsoft.AspNetCore.Server.Kestrel.EnableWindows81Http2` need to be set to `true` to enable these scenarios.

### Reason for change

This change is made to ensure compatibility errors for HTTP/2 over TLS on older Windows versions are surfaced as early and as clearly as possible. 

### Recommended action

Ensure HTTP/2 over TLS is disabled on incompatible Windows versions. If HTTP/2 over TLS needs to be enabled for Windows 8.1 or Windows Server 2012 R2, ensure compatible cipher suites are configured and the app context switch is set to true, as discussed above.

### Category

ASP.NET

### Affected APIs

     "Not detectable via API analysis"

---
#### Issue metadata

* Issue type: breaking-change

**Comment by fowl2** [comment]
What's the reasoning for the app context switch?

**Comment by JunTaoLuo** [comment]
Given that the default ciphers on Windows 8.1 and Windows Server 2012 R2 won't work, we want to disable HTTP/2 over TLS on those Windows versions and throw or downgrade as appropriate. However, since it is possible to configure the cipher suites to something that is compatible with HTTP/2 over TLS we also want to give the user the ability to explicitly enable HTTP/2.

**Comment by michael-x** [comment]
Is there any documentation available on whether and when this works in Linux environments? What are the prerequisites for HTTP/2 on that platform? Does any of this affect Linux as well?

**Comment by blowdart** [comment]
The issue discusses the limitations of Windows, so it does not apply to Linux. 

HTTP/2 on Linux requires OpenSSL 1.0.2 or higher (e.g., Ubuntu 16.04) and that hasn't changed since the [original announcement](https://devblogs.microsoft.com/aspnet/asp-net-core-2-2-0-preview1-http-2-in-kestrel/).

**Comment by fowl2** [comment]
> we decided to use an app context switch to control this behavior instead of something like an option.

I mean, why require configuration in two places (Windows/registry + app context), why not just "light up" on any platform that supports what's required?

**Comment by JunTaoLuo** [comment]
Windows registry configuration cannot be avoided. Given that this is already a non-default scenario and already requires additional configuration changes, we don't want to detect whether the requirements for HTTP/2 over TLS have been met. The user is in the best position to make the decision of whether HTTP/2 over TLS needs to be supported and whether it's configured to do so, hence the app context switch. Again, we anticipate that this isn't a prevalent scenario.
