### ISSUE TITLE
Serverside Blazor _content component library

### ISSUE THREAD

**Issue by mattgenious** [dotnet/aspnetcore#23077]
### Describe the bug
When debugging a server side blazor application running visual studio 16.7.0 preview 2.0 and setting the ```ASPNETCORE_ENVIRONMENT``` variable to ```production``` the resultant site has no _content folder and component libraries like Blazorise do not work. 

### To Reproduce
Start a new blazor server side project everything default.
Install Blazorise as described here https://blazorise.com/docs/start/ (follow the server side path)
Change ```ASPNETCORE_ENVIRONMENT``` variable to ```production```
Debug in visual studio.

When making sure that there are no programmatic behavior differences between production and development environments the issue still occurs.

When publishing to folder and running the executable the same issue occurs.

When publishing to single executable the _content folder shows up and everything works.

When debugging with ```ASPNETCORE_ENVIRONMENT``` variable to ```development``` everything works.

### Further technical details
- ASP.NET Core version 3.1.400 - preview
- Visual Studio 16.7.0 Preview 2.0
- The only extra nuget packages installed are Blazorise.Bootstrap@0.9.0.3 and Blazorise.Icons.FontAwesome@0.9.0.3

```.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015151
 Commit:    0755a9e324

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015151\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]```

**Comment by javiercn** [comment]
@mattgenious thanks for contacting us.

Static web assets is only enabled by default during development. You can call `UseStaticWebAssets` explicitly on the HostBuilder to enable it unconditionally.
