### ISSUE TITLE
Blazor WebAssembly Errors in IIS

### ISSUE THREAD

**Issue by alanchinese** [dotnet/aspnetcore#23079]
Hello, I created a Blazor solution using Visual Studio 2019 v16.6.2 with "Configure for HTTPS" and "ASP.NET Core hosted" checked.  In Visual Studio, "Start without debugging" runs the application successfully.
I then publish to folder, create an IIS application and map the published path.  When I browse the application, the error message always displays "An unhandled error has occurred. Reload".
I watched [Blazor WebAssembly hosting in IIS](https://www.youtube.com/watch?v=k2qAuwNpM_s) (I didn't have the "Progressive Web Application" checked and didn't create a new site)
I have been following [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1)
I have also been looking at [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1)

Is there anyway to find out what I missed?  Thanks in advance!

**Comment by javiercn** [comment]
@alanchinese thanks for contacting us.

Can you provide us with more details about the errors you are seeing? Are you serving the published app over HTTPS?

**Comment by alanchinese** [comment]
This is the error message on the page - I believe it is the default error div.
![image](https://user-images.githubusercontent.com/41824167/85052466-d4434d00-b14d-11ea-8ee3-5dc9276839f0.png)
I am interested to learn how to catch the exception and display it on the page or throw it to a log.
I enabled ASP.NET Core Module debug log (IIS), but could not find anything.
Yes, I published the app over HTTPS.

**Comment by alanchinese** [comment]
Thank you.  I have the following errors:
![image](https://user-images.githubusercontent.com/41824167/85067685-f0eb7f00-b165-11ea-9522-9d036ca9f748.png)

**Comment by javiercn** [comment]
@alanchinese that looks like a configuration issue in IIS. Are you deploying to a virtual path or similar? In that case you might need to adjust your index.html to include the segment for the base path. in the `<base>` tag.

I would check that you can access `_framework/blazor.boot.json` from the browser and check where the app is trying to download it from the network tab to spot any difference.

**Comment by alanchinese** [comment]
That is it.  You nailed it Javier.  Thanks for the direction.  I was able to follow [App base path](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.1&tabs=visual-studio#app-base-path) to get it working.
I changed from
<base href="/">
to
<base href="/CoolApp/">
I wonder why the publishing the project does not include this in the index.html
Is there a way to automate adding this path in index.html other than a script?
Thanks a lot for your help on this.  I finally can get it going after half of a week of struggling.
