### ISSUE TITLE
Make dotnet-watch more efficient by only executing required tasks for known change types

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#23073]
## Overview
Today, dotnet-watch takes a very coarse-grained approach to automating the inner-loop of monitoring changes to project files, shutting down the running app, building the project, and launching the project again. Broadly speaking, it monitors all project files for changes, and when one occurs, shuts down the previous instance of "dotnet run" before executing "dotnet run" again. "dotnet run" itself will call "dotnet build", which implicitly calls "dotnet restore", then performs the actual build operation, before finally launching the built application using the settings from the project's "launchSettings.json" file.

For cmd line centric dev experiences, this approach leads to quite a lot of overhead and thus time that the developer is waiting after making a code change to seeing that change available in the running application.

To be more efficient, dotnet-watch should attempt to only perform tasks that are necessary based on the type of change that's detected. The CLI already supports suppressing many implied operations to avoid their cost if the invoker knows they're not required and dotnet-watch should try to take advantage of this.

## Proposal
The following changes are proposed, in priority order, to investigate and if feasible implement, to reduce the amount of time users have to wait when using dotnet-watch to help automate their dev workflow.

1. [x] If changes detected would not impact the file watch list, e.g. no project files or build files (Directory.Build.props and Directory.Build.targets) edited, then skip the invocation of the `GenerateWatchList` MSBuild target as this avoids extra launches of dotnet processes
1. [x] If changes detected would not impact NuGet packages installed, e.g. no project files, build files (Directory.Build.props and Directory.Build.targets), or nuget.config files edited, then skip the implicit NuGet restore on resultant build with the `--no-restore` flag
1. [ ] In Razor projects, if detected changes only include `.cshtml` files, only invoke the Razor compilation target of the containing project, as these are built into a separate assembly
1. [ ] Explicitly build only the projects that would be impacted by detected changes, based on the project reference graph, building each in turn with the `--no-dependencies` flag, in order to avoid the overhead of building projects with no changes
1. [ ] Keep the `VBCSCompiler` server process alive between detected changes to avoid it shutting down and having to incur its startup time cost on subsequent detected changes

## Stretch Ideas
Ideally, `dotnet watch` would perform all its tasks in-process, in order to avoid the repeated cost of launching another CLI instance on each change/operation. Each CLI process launch incurs the cost of OS process launch, CLR initialization, loading and JIT'ing of the CLI and dependent assemblies, and parsing and processing of CLI arguments passed. The cost of this is very noticeable and is avoided in stateful scenarios like Visual Studio. Imagine `dotnet watch` could load the CLI command assemblies directly into its own process and execute them inline, or perhaps the watch command itself should become part of the CLI so it can invoke other commands directly. As it is today, every time watch detects a change it results in **five** process starts to get the app compiled and launched again. Also every time watch evaluates the project with MSBuild it's another launch of `dotnet msbuild` and it does this on every file change detected.

@pranavkm

**Comment by brianrob** [comment]
I'm wondering if we can use MSBuild node re-use to avoid this many new msbuild processes.  I know some of these are "proxy" processes that just figure out that they need to call MSBuild, and then spawn a new process to call MSBuild, but others are actual MSBuild processes, and it seems that this scenario could benefit from the MSBuild processes remaining alive.  Of course we should also try to get rid of these "proxy" processes as best we can, since they're just overhead.

**Comment by DamianEdwards** [comment]
Here's a screenshot of procmon showing all process start events that occur when `dotnet watch` detects a file change:
![image](https://user-images.githubusercontent.com/249088/85899019-3e916880-b7b2-11ea-8500-a7d5f6d8181d.png)

Basically:
1. `dotnet watch` starts `dotnet msbuild /t:GenerateWatchList` to get the updated file watch list from the project (it assumes it might have changed)
1. The `dotnet msbuild` process turns around and starts msbuild via `dotnet exec msbuild.dll` to actually run the requested target from the first step. **These first two steps could likely be collapsed by changing `dotnet watch` to directly construct this process launch command line rather than relying on `dotnet msbuild` to run the GenerateWatchList target.**
1. `dotnet watch` then starts the app again by launching `dotnet run`
1. The `dotnet run` process then directly invokes MSBuild via `dotnet exec msbuild.dll` to perform the restore and build
1. Finally `dotnet run` then launches the app itself via the custom app exe (in this case `FrontEnd.exe`). **I believe someone said it's marginally quicker to actually use `dotnet app.dll` to avoid the AppHost having to locate the file so that's a micro-fix we could consider for `dotnet run`**

@brianrob also has a change in progress that would avoid the process hop for invocations of `dotnet msbuild` and `dotnet run` which if landed and replicated in `dotnet watch` could collapse the above list to just two process starts per file change: one to call `dotnet run` which would then call `dotnet app.dll`.

**Comment by pranavkm** [comment]
Thanks @DamianEdwards. This looks like a great list. I can start poking at the first couple of things on this list and we can start from there.

**Comment by pranavkm** [comment]
Closing this as we don't have any immediate plans in this space particularly since a lot of these are now substituted by hot reload.
