### ISSUE TITLE
Controller's base `Content` method has no overload for specifying a status code?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#23087]
If we ever wanted to return manually a `ContentResult` object, we could do so, and set our desired StatusCode by setting the `StatusCode` property of the object, but when using the `Content` API inherited from our `BaseController`/`Controller` class, we can't do that.

Why? Is this intentional?

**Comment by javiercn** [comment]
@SpiritBob thanks for contacting us.

Methods on Controller and ControllerBase are meant to be helpers that cover common scenarios. For `Content` the most common scenario is to return 200. We haven't received requests before for setting the status code when using `Content` and we don't want to clutter Controller and ControllerBase with more methods than they already have.

It is very unlikely we add an additional overload unless we hear more demand for it from other customers for the reasons stated above. If you need/want this, I recommend you create your own base class and create a helper method in there or alternatively set the status code after calling the method.
