### ISSUE TITLE
[Blazor][WebAssembly] Disable caching automatically in HTTP environments

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#23082]
Firefox doesn't handle integrity checks when serving from HTTP and they are `meaningless` since the integrity is compromised on the first request if its made over HTTP.

The fix here is to check `document.location.protocol === 'https:'` and disable caching and integrity validation automatically [here](https://github.com/dotnet/aspnetcore/blob/b458261227d6babe756944519b6746edeb89f1ed/src/Components/Web.JS/src/Platform/WebAssemblyResourceLoader.ts#L162-L188)

**Comment by Bigtalljosh** [comment]
@javiercn 
Hey! I'm taking a stab at this, it's way out my comfort zone but thought I'd give it a shot anyway.

**Comment by javiercn** [comment]
@Bigtalljosh no problem. We'll help you out if you run into issues!
