### ISSUE TITLE
Blazor WebAssembly 3.2, Dll files are blocking by McAfee Web Gateway

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#23084]
It seems even after renaming .dll to another extension some (corporate) firewalls are still blocking them:

![Capture](https://user-images.githubusercontent.com/549272/85016604-b50ae680-b172-11ea-93d1-17cdaff2f2d6.PNG)
![Capture2](https://user-images.githubusercontent.com/549272/85016525-90167380-b172-11ea-94e8-7a606425bb7c.PNG)

Is there any workaround for this except contacting the corporate admin team which will definitely won't unlock them?

**Comment by javiercn** [comment]
@mihaimyh thanks for contacting us.

You can try renaming the published output dlls as described [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#change-the-filename-extension-of-dll-files).

Please let us know if that solves your problem or if it still blocks the dlls. If that doesn't fix the problem, you can use a custom boot resource loader as described [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#custom-boot-resource-loading) where you have full control of the resource loading process.

**Comment by mihaimyh** [comment]
@javiercn I already renamed dlls like I mentioned initially. If you look closely to the screenshots the Microsoft.AspNetCore.Components.WebAssembly has the extension .myh instead of .dll

**Comment by javiercn** [comment]
@mihaimyh I missed the rename.

I would try creating a bundle with the file contents and use a custom boot resource loader to download the dlls.

**Comment by mihaimyh** [comment]
@javiercn I am not sure what do you mean with "custom boot resource", are there any docs for this?

**Comment by javiercn** [comment]
@mihaimyh you can alter the files in any way that let you get through the proxy, download them ahead of time and implement your own resource loader.
```js
...

<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
  Blazor.start({
    loadBootResource: function (type, name, defaultUri, integrity) {
      console.log(`Loading: '${type}', '${name}', '${defaultUri}', '${integrity}'`);
      switch (type) {
        case 'dotnetjs':
        case 'dotnetwasm':
        case 'dll':
            return await getDllContentsAsResponseObject(name, integrity);
        case 'timezonedata':
          return  `https://my-awesome-cdn.com/blazorwebassembly/3.2.0/${name}`;
      }
    }
  });
</script>
```

**Comment by mkArtakMSFT** [comment]
We will try to come up with a guidance on how to change the response format so that the antivirus and similar software products don't flag these going forward.

**Comment by mihaimyh** [comment]
@mkArtakMSFT Until then can you let us know if the guidance is based on @javiercn previous answer?

**Comment by mihaimyh** [comment]
Any update on this?

**Comment by pranavkm** [comment]
Given how infrequently we've seen this issue being reported, we're going to recommend using the solution listed in https://github.com/dotnet/aspnetcore/issues/23084#issuecomment-646027364 as a reasonable workaround. Please let us know if using that does not help and we might be able to provide further guidance.
