### ISSUE TITLE
Why configure Authorize filter on Logout page when LogoutModel has AllowAnonymous attribute?

### ISSUE THREAD

**Issue by nathanschopf** [dotnet/aspnetcore#23093]
Can someone explain the rational with this? I'm not really sure if this is an issue, or just for my own edification, but would definitely appreciate some sort of confirmation of my understanding. Is the following line below in IdentityDefaultUIConfigureOptions.cs unnecessary? As I understand, the [AllowAnonymous] has precedence and will always allow access to the page. So what's the point of configuring it in the options?

https://github.com/dotnet/aspnetcore/blob/3fcd84946cf63794a3913a79d47f5143ea0f30ae/src/Identity/UI/src/IdentityDefaultUIConfigureOptions.cs#L33

https://github.com/dotnet/aspnetcore/blob/3fcd84946cf63794a3913a79d47f5143ea0f30ae/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Logout.cshtml.cs#L17

**Comment by javiercn** [comment]
Hi,

Allow anonymous will guarantee you can access, but authorize will make sure we try to authenticate the user and populate the ClaimsPrincipal.

**Comment by nathanschopf** [comment]
Thank you for the explanation, @javiercn! While this makes total sense when reviewing the code for OnAuthorizationAsync in AuthorizationFilter I'm failing to produce a scenario where (after successfully logging in) the ClaimsPrincipal is _not_ set for a subsequent request where the Razor Page, or Controller _does not_ have the Authorize filter (or attribute) applied. Would you kindly provide such a scenario?
