### ISSUE TITLE
Add virtualization components

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23092]
Consider a component such as a list or a grid that needs to render hundreds of child component. At any given time, only a subset of components are visible in the viewport need to be rendered. This issue tracks adding a component that abstract the concept of virtualization, along with implementations for common virtualization scenarios such as grids and lists.

https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/Virtualization has should help you get started.

**Comment by mrlife** [comment]
This looks very cool. Is it for Server-Side and WASM? Is it intended to become a built-in component or serve as it is as a sample users can reference?
