### ISSUE TITLE
Ways to extend DefaultAuthorizationService (& co)

### ISSUE THREAD

**Issue by hansmbakker** [dotnet/aspnetcore#23094]
### Is your feature request related to a problem? Please describe.
Use case: I want to log requests, from properly signed in users that try to access things they have no permissions for, in a separate logging provider.
So the use case is around authorization (invalid roles) rather than authentication (user is logged in correctly).

I want to use a separate logging provider so that I can keep these logs separately (with different retention policy) from the normal application logs.

It seems difficult to add custom logic to the default authentication / authorization classes - it is not possible to extend their functionality. Instead you have to replace the whole class.

The methods in [`DefaultAuthorizationService`](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/DefaultAuthorizationService.cs) are not marked `virtual` and therefore they cannot be overridden.

Also, it does not provide events that you can attach to, or callbacks you can implement.

It seems you have to provide a completely new implementation of `DefaultAuthorizationService` (copy paste, adding in your own code) if you only want to respond to authorization success/failure.

### Describe the solution you'd like
Marking the methods in [`DefaultAuthorizationService`](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/DefaultAuthorizationService.cs) as `virtual` would be a quick fix.

Events / callbacks that you can implement (OnAuthorizationSucceeded / OnAuthorizationFailed) would also be possible.

In those methods it would be helpful to 

### Alternative approach?

If there is a better approach for the usecase `log requests, from properly signed in users that try to access things they have no permissions for, in a separate logging provider.` than the approach I was looking into (making this issue redundant) I would also be interested to hear it.

**Comment by hansmbakker** [comment]
This seems related to https://github.com/dotnet/aspnetcore/issues/7789 but I found it difficult to understand whether the solution to https://github.com/dotnet/aspnetcore/issues/7789 will solve my use case?

**Comment by blowdart** [comment]
The authorization service doesn't handle authentication. So making things virtual here won't help. Log providers can filter by namespace and log event. @HaoK to follow up with some docs or samples.

**Comment by HaoK** [comment]
@hansmbakker take a look at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1 the section under configure logging has a way to enable log levels for specfic namespaces, can you try that and just enable more detailed logging for the Authorization namespace?

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.AspNetCore.Authorization": "Information"
    }
  }
}
```

**Comment by hansmbakker** [comment]
@blowdart 
> The authorization service doesn't handle authentication.

My use case was not about authentication. Successfully authenticated people trying to access a resource for which they do not have the required roles/permissions are in the authorization stage. They are past the authentication stage already.

> Log providers can filter by namespace and log event

I believe filtering is not what I need?

- I want to direct the logs from `DefaultAuthorizationService` to a different physical data store, separate from the other logs.
- I want it to include data like the **user** that tried accessing the resource, and **what resource** the user was trying to access.

For this I am looking for a way to hook into the DefaultAuthorizationService code. If its methods would be virtual, I could inherit from `DefaultAuthorizationService ` and do

```csharp
public override async Task<AuthorizationResult> AuthorizeAsync(ClaimsPrincipal user, object? resource, IEnumerable<IAuthorizationRequirement> requirements)
        {
            var result = await base.AuthorizeAsync(user, resource, requirements);
            if (!result.Succeeded)
            {
                _customAuditLogger.LogForbiddenAccess(user, resource);
            }

            return result;
        }
```

I believe this is not possible by configuring the logging settings in the appSettings?

**Comment by HaoK** [comment]
If that's all you want to do, you can still do that by just wrapping an instance of DefaultAuthorizationService inside of a custom AuthorizationService and just delegating to it

**Comment by hansmbakker** [comment]
Yes, that would be a solution, too.

I guess that is not really in line with OOP concepts, but it should work - thank you for the suggestion!

Is extensibility still something that could be discussed for future releases?

**Comment by HaoK** [comment]
Sure, marking a few methods virtual is pretty much free, feel free to submit a PR if you want

**Comment by hansmbakker** [comment]
@HaoK done, please see #23143

**Comment by hansmbakker** [comment]
Please note: I did it only for `DefaultAuthorizationService` for now since I had a use case for that.

There are a lot of related classes and I could not oversee what other people might need regarding extensibility of them.

**Comment by blowdart** [comment]
@hansmbakker I believe (and someone should have sample code), you could use the filtering to have multiple loggers, and only have your "sensitive" logger react to the authentication and authorization log events, enabling you to send them elsewhere.

**Comment by hansmbakker** [comment]
@blowdart ok, that would solve part of the problem. However, the logging that `DefaultAuthorizationService` does is [hardcoded to `LoggingExtensions` marked as `internal`](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Core/src/DefaultAuthorizationService.cs#L98-L106). **It is not possible to modify what data points are logged**

**Comment by Tratcher** [comment]
You should still be able to hook up another log provider and filter which logs it captures.
