### ISSUE TITLE
very-slow-intellisense-in-blazor-project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23108]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1075952/very-slow-intellisense-in-blazor-project.html)._

---
I seem to have all the problems listed in the following problem:
https://developercommunity.visualstudio.com/content/problem/873214/very-slow-intellisense-in-large-blazor-project.html?inRegister=true

This is ​Still happening in VS 16.6.2
Once it starts happening usually have to reboot the entire VM. Just closing all instances of VS and the junk processes it leaves running doesn't clear it out.  Only happens when using Blazor apps.  Been editing standard .Net (4.7.2)  projects for days without a reboot without issues.  2 hours after starting to work on a SMALL blazor app, slow city.  Seems to be related to Intellisense. Always has background tasks seeming running constantly and TONS of ServiceHubs and other compiler processes running in the background.

---
#### Visual Studio Feedback System on 6/15/2020, 06:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We are aware of this issue and are tracking it as part of #22276
