### ISSUE TITLE
Medium/Big MainLayout.razor blows up IDE - Blazor ISSUES

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23105]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1078962/mediumbig-mainlayoutrazor-blows-up-ide-blazor-issu.html)._

---
I'm developing a MainLayout.razor with PWA, Blazor and editing MainLayout.razor freezes IDE only to copy from memory a single line <div class="main"> or just add in the end </div>.

---
#### Visual Studio Feedback System on 6/16/2020, 00:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something we're aware of an are addressing as part of #22276
