### ISSUE TITLE
MVC Model equals problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23109]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1076301/mvc-model-equals-problem.html)._

---
[regression] [worked-in:previous one]

In razor if I want to write 

```
  if (Model == null
```

If get this on the second time I hit equal sign:

```
 if (Model =Model=
```

It very annoying!!

---
#### Visual Studio Feedback System on 6/15/2020, 00:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our efforts in moving our Razor tooling over to an LSP powered model.

This should light up in the .NET 5 time frame.
