### ISSUE TITLE
NotFound route causes reload

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [dotnet/aspnetcore#23100]
### Describe the bug
Hi!

When using Blazor wasm, the not found route causes browser page reload, happens even in the clear visual studio template. 

### To Reproduce
Create a new blazor wasm(clientside) app with the create a navlink which has a href attribute value a non existing page path. When you click on that navlink it navigates to the right url, but the whole app reloads, like you would open the app on a new page or tab e.g. the loading text shows up then it shows the notfound component.

The router config:
```
<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
</Router>
```

### Short time solution
I created a page which catches any page which is not defined but it only works for one path segment

```
@page "/{Path}"

<h1>@Path not found </h1>

@code{
    [Parameter]
    public string Path { get; set; }
}
```

for multiple segment paths I would need to define every segment manually because wildcards are not allowed

From the docs:
`Catch-all parameter syntax (*/**) is not supported in Razor components (.razor).`
https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1#routing-with-urls-that-contain-dots

### Further technical details
Visual Studio 2019
dotnet core version 3.1.300

info from the csproj:
```
<PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest></PropertyGroup>
```

**Comment by javiercn** [comment]
@TheOnlyBeardedBeast thanks for contacting us.

Can you post the code you are using to define the `navlink` or a minimal repro project that illustrates the issue?

**Comment by TheOnlyBeardedBeast** [comment]
@javiercn sure. So I recreated the bug and upload it.

So I created an empty wasm blazor project based on the Visual Studio 2019 template and I added a new navlink to the navigation, you can find it here https://github.com/TheOnlyBeardedBeast/ErrorExample-NotFound

the navlink to testout the notfound behavior
```
<NavLink class="nav-link" href="nonexisting">
                <span class="oi oi-list-rich" aria-hidden="true"></span> Non existing
</NavLink>
```
the navlinks are here
https://github.com/TheOnlyBeardedBeast/ErrorExample-NotFound/blob/master/BlazorApp2/Shared/NavMenu.razor

The url changes, it even shows the right not found content, but an app reload happens on navigation. The realod does not happen between existing(found) pages which are defined.

the router config:
https://github.com/TheOnlyBeardedBeast/ErrorExample-NotFound/blob/master/BlazorApp2/App.razor

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by SteveSandersonMS** [comment]
This behavior is intentional. It's because for some URLs, you might want to use server-side rendering. So when the client-side code can't handle a given URL, we perform a full-page load in case the server wants to handle it. If the server doesn't handle it and just re-renders to client-side app, then we know that neither the client nor server can handle that URL, and that's when we display the "not found" page.

If this is a big problem for anyone then in the future we could consider adding a mechanism for saying not to do it, but it's not a priority in the short term.

**Comment by TheOnlyBeardedBeast** [comment]
@SteveSandersonMS thanks for the reply, yest it would be good to jave an option to disable this feature
