### ISSUE TITLE
Blazor template that has core functionality in one project, server app in one project and client app in one project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23101]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1082462/blazor-template-that-has-core-functionality-in-one.html)._

---
I could really go for a pre-generated template that pulls all the core fundtionality in to a core project, and the server side blazor into its own project, and the client side blazor into its own project, so I can start coding instead of trying to sort out the dependencies between the two individual templates to refactor into the common template.  Thanks.

---
#### Visual Studio Feedback System on 6/18/2020, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
It's not clear what the ask here is.

I'm not sure this is asking for a template that supports serverside and blazorwasm at the same time.

**Comment by javiercn** [comment]
This is not an issue we've heard much about so we're going to park it in our backlog to accumulate more feedback about. We will review it during our next release planning and act accordingly.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
