### ISSUE TITLE
working on Blazor WASM projects makes VS2019 go unstable and use a lot of CPU for no reason

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23104]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1079130/working-on-blazor-wasm-projects-makes-vs2019-go-un.html)._

---
When working on a new blazor (wasm/client) project in our .NET Core MVC project, visual studio becomes very slow and unstable after a few minutes of refactoring. When i restart VS it works fine again, then a few minutes later it again uses a lot of cpu making it almost impossible to work on the project. This is a brand new "blazor" project with just a few lines of code in it, and the mvc project we have added it to, usually works fine without this issue.

---
#### Visual Studio Feedback System on 6/15/2020, 07:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something we're aware of an are addressing as part of #22276
