### ISSUE TITLE
Blazor WASM debugging is constantly giving us issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23103]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1079193/blazor-wasm-debugging-is-constantly-giving-us-issu.html)._

---
- Breakpoints are out of sync
- Data cannot be evaluated
- Random crashes
- Async code runs very weird (if at all) and almost impossible to debug.
- Vs becomes unstable and slow after a few minutes.

This product is NOT ready for production :/

---
#### Visual Studio Feedback System on 6/16/2020, 00:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
To be able to keep track of all these issues, it would help to get separate issues filed in this repo.
And let's use this one to track the `Breakpoints are out of sync` issue. For that, @captainsafia can you please share the instructions on how to collect more logs.

**Comment by captainsafia** [comment]
[Here](https://github.com/dotnet/aspnetcore/issues/22012#issuecomment-637117329) are the instructions for collecting logs from the debugging session. Let me know if you have any follow-up questions!
