### ISSUE TITLE
NavigationManager.NavigateTo("/") returns to page

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23111]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1061354/navigationmanagernavigateto-returns-to-page.html)._

---
<p>@page &quot;/CpeLogin&quot;</p><p>
@layout EmptyLayout </p><p>@inject NavigationManager NavigationManager </p><p><br></p><p>&lt;button class=&quot;btn btn-sm seda-green-bkg text-white&quot; style=&quot;width:70px;&quot;  @onclick=&quot;RouteCPE_Home&quot;&gt;Login&lt;/button&gt;</p><p><br></p><p>@code{</p><p>void RouteCPE_Home()</p><p>{</p><p>  NavigationManager.NavigateTo(&quot;/&quot;);</p> <p>}</p><p>}</p>

---
#### Zabron Muyambo on 6/2/2020, 01:01 PM: 

<p>On clicking the button, the specified page only "flicks" for a mini second then control returns to the calling page (Page with the button). I have tried explicit routing like NavigationManager.NavigateTo("/index"), but the same thing happens. </p>

#### Visual Studio Feedback System on 6/3/2020, 03:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/4/2020, 10:21 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mrpmorris** [comment]
I don't think the info here is going to be enough on its own.

Can you provide a minimal project that reproduces the problem?
