### ISSUE TITLE
Automatically generated CRUD Razor Pages use bad layout

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23113]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1057722/automatically-generated-crud-razor-pages-use-bad-l.html)._

---
<p>It’s a very handy feature to be able to generate all the logic to implent CRUD operations. However, I don’t get the layout that is used.</p>
<p>The layout uses Bootstrap’s responsive classes, but not correctly. Specifically, it seems to use <code>col-md-4</code>, which makes a column one third the width of the container on medium screens and larger. But for some reason, it then places every control group in that same column.</p>
<pre>&lt;div class=&quot;row&quot;&gt;
    &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;col-md-4&quot;</span>&gt;
        &lt;form method=<span class=hljs-string>&quot;post&quot;</span>&gt;
            &lt;div asp-validation-summary=<span class=hljs-string>&quot;ModelOnly&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/div&gt;
            &lt;input type=<span class=hljs-string>&quot;hidden&quot;</span> asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Id&quot;</span> /&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;label asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Name&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;control-label&quot;</span>&gt;&lt;/label&gt;
                &lt;input asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Name&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-control&quot;</span> /&gt;
                &lt;span asp-validation-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Name&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/span&gt;
            &lt;/div&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;label asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.City&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;control-label&quot;</span>&gt;&lt;/label&gt;
                &lt;input asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.City&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-control&quot;</span> /&gt;
                &lt;span asp-validation-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.City&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/span&gt;
            &lt;/div&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;label asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.State&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;control-label&quot;</span>&gt;&lt;/label&gt;
                &lt;input asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.State&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-control&quot;</span> /&gt;
                &lt;span asp-validation-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.State&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/span&gt;
            &lt;/div&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;label asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.TotalSpots&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;control-label&quot;</span>&gt;&lt;/label&gt;
                &lt;input asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.TotalSpots&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-control&quot;</span> /&gt;
                &lt;span asp-validation-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.TotalSpots&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/span&gt;
            &lt;/div&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;label asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.AvailableSpots&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;control-label&quot;</span>&gt;&lt;/label&gt;
                &lt;input asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.AvailableSpots&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-control&quot;</span> /&gt;
                &lt;span asp-validation-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.AvailableSpots&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/span&gt;
            &lt;/div&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;label asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Notes&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;control-label&quot;</span>&gt;&lt;/label&gt;
                &lt;input asp-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Notes&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-control&quot;</span> /&gt;
                &lt;span asp-validation-<span class=hljs-keyword>for</span>=<span class=hljs-string>&quot;Location.Notes&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;text-danger&quot;</span>&gt;&lt;/span&gt;
            &lt;/div&gt;
            &lt;div <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;form-group&quot;</span>&gt;
                &lt;input type=<span class=hljs-string>&quot;submit&quot;</span> <span class=hljs-keyword>value</span>=<span class=hljs-string>&quot;Save&quot;</span> <span class=hljs-keyword>class</span>=<span class=hljs-string>&quot;btn btn-primary&quot;</span> /&gt;
            &lt;/div&gt;
        &lt;/form&gt;
    &lt;/div&gt;
&lt;/div&gt;
</pre>
<p>The result of this is the perfect layout for cell phones, but it uses the exact same layout on desktops!</p>
<p>I realize it’s up to the developer to customize the layout for their applications, but a little work here by someone who understands the responsive layout could really save some time.</p>
<p>I would probably put the <code>&lt;div class=&quot;row&quot;&gt;</code> inside the <code>&lt;form&gt;</code>. And then create a <code>&lt;div class=&quot;col-md-4&quot;&gt;</code> or <code>&lt;div class=&quot;col-md-6&quot;&gt;</code> for each control group. This would produce the same output on cell phones, but would place multiple control groups per row on desktops, and would make much better use of available space.</p>
<p>I have trouble understanding why it was done the way it was. The only conclusion I came up with is that it was decided the developer will deal with layout. But a much better guess could be made.</p>

---
#### Visual Studio Feedback System on 5/31/2020, 11:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/1/2020, 07:34 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Would you be interested in sending as a PR for this? We would happily consider it.

**Comment by SoftCircuits** [comment]
@mkArtakMSFT : Was that directed to me? I'm the original poster. Not sure what you're asking about a *PR*. Please clarify.

**Comment by SoftCircuits** [comment]
FWIW, I my example should be structured something like this. It would put each group on a separate line on mobile devices. And would use the full screen on large devices.

```
<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Location.Id" />
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Location.Name" class="control-label"></label>
                <input asp-for="Location.Name" class="form-control" />
                <span asp-validation-for="Location.Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Location.City" class="control-label"></label>
                <input asp-for="Location.City" class="form-control" />
                <span asp-validation-for="Location.City" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Location.State" class="control-label"></label>
                <input asp-for="Location.State" class="form-control" />
                <span asp-validation-for="Location.State" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Location.TotalSpots" class="control-label"></label>
                <input asp-for="Location.TotalSpots" class="form-control" />
                <span asp-validation-for="Location.TotalSpots" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Location.AvailableSpots" class="control-label"></label>
                <input asp-for="Location.AvailableSpots" class="form-control" />
                <span asp-validation-for="Location.AvailableSpots" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Location.Notes" class="control-label"></label>
                <input asp-for="Location.Notes" class="form-control" />
                <span asp-validation-for="Location.Notes" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
```

**Comment by bdavisjr** [comment]
form-group has been dropped from BS 5. So it's not longer in use.

**Comment by mkArtakMSFT** [comment]
Closing as we've updated to Bootstrap 5.
