### ISSUE TITLE
High memory and CPU usage when editing blazor razor files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23110]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1070585/high-memory-and-cpu-usage-when-editing-blazor-razo.html)._

---
My Visual Studio instance eats more than 2,5Gb RAM and 60-80% CPU (i7) when I editing blazor razor files. It lags and unresponsive.
(System logs attached.)

Regards,
 Peter

---
#### Fiona Niu[MSFT] on 6/10/2020, 02:41 AM: 

<p>Thank you for taking the time to log this issue! Could you please provide more information via the Visual Studio Feedback Tool(Help -&gt; Send Feedback -&gt; Report A Problem) so that we can conduct further research? The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:</p>
<pre><code>• Open Visual Studio Feedback tool.
• Click the banner letting you know that you have problems requesting your attention.
• Click this problem from the list
• Click &quot;View their request and respond&quot; from the problem details banner
• Add a comment, in the Attachments/Record: click Start Recording
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.
• When you're done, choose the Stop Record button.
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don't appear on Developer Community.
</code></pre>
<p>For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.</p>
<p>We look forward to hearing from you!</p>

#### Péter Németh on 6/10/2020, 07:20 AM: 

Ok, I did exactly the same, but I do it again.<br>How to reproduce?<br>Just develop a blazor project for few hours<br>Regards,<br> Peter
#### Péter Németh on 6/10/2020, 11:13 PM: 

Hi,<br><br>Thank you!<br>Yes, I can reproduce on every day, but it&#39;s not a simple step, or steps. You need open Visual Studio, open/create a blazor project, add/edit razor pages, css, html (not 2-3 lines) and work for 1-2 hours. It&#39;s a very long time for recording...<br><br>Another example: I let vs to run all night with an opened blazor project. I did not do anything, because I slept. Today morning vs uses 63% CPU and 1Gb ram. The RAM is ok, but what happening with my cpu? <br><br>So I understand that you need more informations and exact steps, but I can&#39;t record 1-2 hours of work, it&#39;s too long, also I can&#39;t record vs all night when it is idle. <br><br>Regards,<br> Peter<br>
#### Fiona Niu[MSFT] on 6/10/2020, 07:52 PM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/135903/PterNmeth.html">Péter Németh</a> Thanks for your reply. For performance issue, it would be very helpful if you provide the ETLTrace. Can you reproduce the high memory and CPU usage issue stably when editing blazor razor files(reproduce every time when editing)? If so, would you like to collect the requested information as above steps? Thanks for your help.</p>
<p>Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.</p>

#### Visual Studio Feedback System on 6/17/2020, 08:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue we track as part of #22276
