### ISSUE TITLE
Generalized support for kestrel-like request processing pipeline 

### ISSUE THREAD

**Issue by ardove** [dotnet/aspnetcore#23128]
I'm certain this has been asked before but I haven't been able to identify a similar issue so I'm going to try to paint a picture.

### Is your feature request related to a problem? Please describe.
I am trying to leverage scoped services in a generic host. I realize that there's a mechanism for doing this by creating your own scope (and maybe this is what Kestrel does), but I think it'd be great if kestrel (or some derivation thereof) supported a generalized mechanism for "listening" and "routing".  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task

Consider the use case for the generic host as a queue listener. 

With the Apache.NMS.Amqp library, you'd set up an event handler which gets invoked when a message is received. As part of that message receipt, I'd like to set up a logical "inbound request context" which I can use in other places (just like an HttpContext). The problem really applies to any type of service where you're "waiting for a request to come in" and then "wanting to execute something once you get one" (including an http listener). 

Here's a simplified example.
```
public interface IMessageHandler<in T>
{
    Task ProcessMessageAsync(T message, CancellationToken cancellationToken);
}

public class RequestContext
{
    public string CorrelationId { get; set; }
}

public class QueueListener<T> : IHostedService
{
    private readonly QueueListenerOptions _queueListenerOptions;
    private readonly IMessageHandler<T> _messageHandler;
    private readonly ILogger<QueueListener<T>> _logger;

    private IConnection _connection;

    public QueueListener(
        IOptionsMonitor<QueueListenerOptions> subscriberOptions, 
        IMessageHandler<T> messageHandler, 
        ILogger<QueueListener<T>> logger)
    {
        _queueListenerOptions = subscriberOptions.CurrentValue;
        _messageHandler = messageHandler;
        _logger = logger;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        var connectionFactory = new ConnectionFactory(_queueListenerOptions.ConnectionString)
        {
            UserName = _queueListenerOptions.Username, 
            Password = _queueListenerOptions.Password
        };

        _connection = connectionFactory.CreateConnection();
        _connection.ExceptionListener += exception => { _logger.LogError(exception, $"An error occurred while connecting to the broker via connection string '{_queueListenerOptions.ConnectionString}'"); };
        _connection.Start();

        ISession session = _connection.CreateSession(AcknowledgementMode.IndividualAcknowledge);
        IQueue queue = session.GetQueue(_queueListenerOptions.QueueName);
        
        IMessageConsumer consumer = session.CreateConsumer(queue);
        consumer.Listener += message => OnMessage(message, cancellationToken);
        
        return Task.CompletedTask;
    }

    private void OnMessage(IMessage message, CancellationToken cancellationToken)
    {
        // This is called with receipt of every message as an event handler
        //
        // How do I make this "RequestContext" available to other classes who care about this correlation id? 
        var requestContext = new RequestContext
        {
            CorrelationId = message.Properties["correlation-id"].ToString()
        };

        // Allow callers to provide their own implementation of a message processor which
        // know how to handle messages that (de)serialize to type T.
        //
        // If _messageHandler makes a request to a downstream service and I want to correlate the request to that service
        // back to this one, I need a way to pass along the correlation-id to that _messageHandler so that it can forward that. 
        // 
        // The obvious answer is to add RequestContext to the IMessageHandler.ProcessMessageAsync method signature, 
        // but, if that implementation calls 3 downstream services then each of the methods will require the RequestContext
        // as an input parameter to the method which needs it (and the callers are all required to know where to put that correlation
        // id in order to make it accessible via a standardized mechanism).
        //
        // With enough usage of this class, we end up with RequestContext sprinkled about everywhere instead of being something
        // that's available in a standard way (by taking a dependency on it and letting the DI framework figure out how to provide it
        // in a "request" or "message" scoped way). 
        //
        // Another answer is to leverage scope by wrapping the background service a scope that you define. 
        // https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task
        //
        // Another answer might be to allow folks to reconfigure how the request context concept is generated by abstracting the 
        // "Http Listener" concept in Kestrel into a "Request Listener" concept that applies to both "handle this http request"
        // and "handle this message".
        var deserializedMessage = JsonSerializer.Deserialize<T>(((ITextMessage)message).Text);
        _messageHandler.ProcessMessageAsync(deserializedMessage, cancellationToken).Wait(cancellationToken);

        // finally, acknowledge successful processing of the message
        message.Acknowledge();
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        if (_connection.IsStarted)
        {
            _connection.Stop();
        }
        _connection.Close();
        _connection.Dispose();

        return Task.CompletedTask;
    }
}
```

### Describe the solution you'd like
Ideally, there'd be a way to swap out the "listener" and define your own "router" so that when the listener receives a "message" to process, it could be funneled through the a middleware pipeline (custom begin/end logging, automatic request validation, custom authorization, etc.) and ultimately delivered to a "controller".

**Comment by davidfowl** [comment]
This isn’t really kestrel or asp.net core specific but it’s been discussed and prototyped in the past. We haven’t yet explored this area of trying to abstract the messaging system and there are lots of other systems that do this today in .net like NServiceBus.

**Comment by ardove** [comment]
Thanks @davidfowl. I wasn't sure where to raise this specific issue because of that, but it seemed to make sense here since it's where I encountered the problem.  

Is there a better place to raise ideas like this?

**Comment by tthiery** [comment]
@davidfowl I also think that .NET Core (maybe under ASP.NET Core brand) is missing a infrastructure for queues similar what it does for HTTP/gRPC/WebSockets. I mean, uses cases in the real world are either request/response pairs against HTTP/gRPC or are asynchronous message queues. I had hopes in some of the Bedrocks talks where MQTT was mentioned but that never showed up.

@ardove I took the liberty a year or two ago to create a generic [middleware pipeline](https://github.com/violetgrass/middleware) and used it a bit in my own projects. Replicating middleware was algorithmic/programming language fun but routing, controllers etc ... all the parts above ... are extensive and no longer a hobby project. Maybe that helps with your projects.

**Comment by davidfowl** [comment]
>  I had hopes in some of the Bedrocks talks where MQTT was mentioned but that never showed up.

Bedrock is much lower than this and is more about authoring the protocol layer itself.

> @ardove I took the liberty a year or two ago to create a generic middleware pipeline and used it a bit in my own projects. Replicating middleware was algorithmic/programming language fun but routing, controllers etc ... all the parts above ... are extensive and no longer a hobby project. Maybe that helps with your projects.

That's really cool!

@mconnew you were asking about this the other day, take a look at this project that explores more of that generic middleware model.

**Comment by ardove** [comment]
@tthiery that's awesome. I'm not sure it'll ultimately meet our production needs, but it was fun to poke through. thanks for sharing!
