### ISSUE TITLE
No access token found in HttpContext - multiple authentication schemes

### ISSUE THREAD

**Issue by mihalios** [dotnet/aspnetcore#23120]
I have configured two authentication schemes (both JWT Bearer, named differently):

```c#
services.AddAuthentication("scheme1")
	.AddJwtBearer("scheme1", options =>
	{
		// etc
	})
    .AddJwtBearer("scheme2", options =>
	{
		// etc
	});;
	
services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder("scheme1", "scheme2")
        .RequireAuthenticatedUser()
        .Build();
});
```

For access tokens that can be validated by scheme1 I can retrieve the access token from the request's headers:

```c#
var accessToken = await httpContext.GetTokenAsync("access_token");
```

However, for an access token that is issued by the authority corresponding to scheme2 there's no access token in the request. Debugging the HTTP request (via Swagger UI and Fiddler) I can see that the Authorization header is set though:

```
HEADERS
=======
Accept: text/plain
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer <obfuscated access token here>
Host: localhost:5001
Referer: https://localhost:5001/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
:method: GET
:authority: localhost:5001
:scheme: https
:path: /api/Test/Echo
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
```

If it helps, the token is retrieve via a Swagger UI login. In both cases the tokens are valid and verified by the corresponding scheme. 

EDIT:
I realised that if the Auth header is not validated by the default authentication scheme, "scheme1", then I need to do this instead:

```
var accessToken = await httpContext.GetTokenAsync("scheme2", "access_token");
```

Is there any way to retrieve the access_token without specifying a scheme?

EDIT2:
I've resorted to:

```
var accessToken = httpContext.Request.Headers["Authorization"].ToString().Split(" ")[1];
```

**Comment by blowdart** [comment]
JWT doesn't have the concept of access tokens, that's an OIDC concept. The authorization header is might be an access token for another system, but that's not a concept of the JWT handler.

Frankly I don't know how you're getting it in the first handler.

**Comment by wu-yafeng** [comment]
``` csharp
AddJwtBearer(options=>{
   options.SaveToken = true;
})
```

you should set SaveToken as true.
