### ISSUE TITLE
OpenIDConnect Options

### ISSUE THREAD

**Issue by vincentvc168** [dotnet/aspnetcore#23130]
How can I disable the default ClaimActions.DeleteClaim("ipaddr")? I need to get ipaddr. Thanks!

**Comment by blowdart** [comment]
https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/

`options.ClaimActions.Remove("ipaddr");`

**Comment by vincentvc168** [comment]
Thank you very much! It works greatly!
