### ISSUE TITLE
Error on OpenIdConnectAuthenticationHandler

### ISSUE THREAD

**Issue by juanan** [dotnet/aspnetcore#23136]
I have an SPA starting an oidc login that calls to an .Net core project that offers 2 login possibilities: local login with Identity server or external login with Azure AD.

If the user clicks on external login, the Azure AD login form is successfully shown but after login in with my office account I get this error on my redirect callback:

 ---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

This is the info that Azure sends to my callback

![image](https://user-images.githubusercontent.com/17723190/85109540-c7882d00-b211-11ea-9296-edce7407d62a.png)

Am I missing anything in the configuration?This is my Startup.cs class

![image](https://user-images.githubusercontent.com/17723190/85108601-4f6d3780-b210-11ea-9d7c-84c521225c23.png)

And this is my controller to challengue the external login

![image](https://user-images.githubusercontent.com/17723190/85108664-657af800-b210-11ea-8a41-c55ebddc4b42.png)

I would apprecciate any help, I can not figure out why its failing.

Many thanks.

Using .Net Core 3.1

**Comment by blowdart** [comment]
I would strongly suggest moving to the [new packages](https://github.com/AzureAD/microsoft-identity-web) produced by AAD themselves, as the current packages will be replaced with those soon. They also support the v2 endpoints by default, without any code changes, and finally allows you to validate issuer.

**Comment by juanan** [comment]
Many thanks @blowdart , I will use the new packages then.
