### ISSUE TITLE
SignInManager - configurable claim types

### ISSUE THREAD

**Issue by ramihamati** [dotnet/aspnetcore#23134]
It looks like SignInManager uses fixed claim types where the same types are configurable in the usermanager. There are multiple places where ClaimTypes can be replaced with Options.ClaimsIdentity.UserNameClaimType or Options.ClaimsIdentityUserIdClaimType

``` 
public virtual async Task<bool> IsTwoFactorClientRememberedAsync(TUser user)
 {
     var userId = await UserManager.GetUserIdAsync(user);
     var result = await Context.AuthenticateAsync(IdentityConstants.TwoFactorRememberMeScheme);
     return (result?.Principal != null && result.Principal.FindFirstValue(ClaimTypes.Name) == userId);
} 
```

Another issue would be that in this particular method the ClaimType should be NameIdentifier because it's being compared with userId

**Comment by blowdart** [comment]
This is specific to the two factor cookie, you haven't logged in at this point, it's the half way principal, so this is in fact right.
