### ISSUE TITLE
Add missing OffsetX and OffsetY events to TouchPoint class

### ISSUE THREAD

**Issue by DaveNay** [dotnet/aspnetcore#23153]
Issue #20478 addresses the `OffsetX` and `OffsetY` properties for `MouseEventArgs`, however these properties are not present in the `TouchPoint` class as part of `TouchEventArgs`

I would like to have the `OffsetX` and `OffsetY` properties to provide the following:

`OffsetX`   The X coordinate of the touch point relative to the left edge of the element that is the target of the current event.

`OffsetY`   The Y coordinate of the touch point relative to the top edge of the element that is the target of the current event.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will add this based on whether this is in the spec or not. Looks like this is not part of the spec yet.
If it is, can you please send the link to it please?

**Comment by DaveNay** [comment]
> Thanks for contacting us.
> We will add this based on whether this is in the spec or not. Looks like this is not part of the spec yet.
> If it is, can you please send the link to it please?

Thanks, although I am not sure what spec you are referring to.

**Comment by mkArtakMSFT** [comment]
Usually properties like these are defined in a standard. We usually use [MDN](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent) for this but it's not there.
