### ISSUE TITLE
SignalR client netstandard2.1 doesn't implement IAsyncDisposable

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#23163]
### Is your feature request related to a problem? Please describe.
I am using this package targeting netstandard2.1 (blazor wasm project):
```
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.5" />
```

The `HubConnection` class doesn't implement `IAsyncDisposable`, it does have a DisposeAsync method but it returns a Task. Has this been intentionally left?

```     
        public Task DisposeAsync();
```

### Describe the solution you'd like
Implement IAsyncDisposable

**Comment by BrennanConroy** [comment]
This was done in 5.0 https://github.com/dotnet/aspnetcore/pull/13179

You should still be able to use `await using hubConnection;` because the compiler should just be looking for a method named `DisposeAsync` that is awaitable.
