### ISSUE TITLE
[Feature] Easier JavaScript interoperate

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#23166]
`Blazor` Javascript interoperate is very unfriendly ... because Javascript is dynamic language and to interoperate we should through static type `JSRuntime`

Consider instead of:
```razor
@page "/call-js-example"
@inject IJSRuntime JSRuntime;

...

@code {
    // Quote (c)2005 Universal Pictures: Serenity
    // https://www.uphe.com/movies/serenity
    // David Krumholtz on IMDB: https://www.imdb.com/name/nm0472710/

    private MarkupString convertedText =
        new MarkupString("Select the <b>Convert Array</b> button.");

    private uint[] quoteArray = new uint[]
        {
            ...
        };

    private async Task ConvertArray()
    {
        var text = await JSRuntime.InvokeAsync<string>("convertArray", quoteArray);

        convertedText = new MarkupString(text);
    }
}
```
to do something like:
```razor
@page "/call-js-example"
@inject dynamic JSRuntime;

...

@code {
    // Quote (c)2005 Universal Pictures: Serenity
    // https://www.uphe.com/movies/serenity
    // David Krumholtz on IMDB: https://www.imdb.com/name/nm0472710/

    private MarkupString convertedText =
        new MarkupString("Select the <b>Convert Array</b> button.");

    private uint[] quoteArray = new uint[]
        {
            ...
        };

    private async Task ConvertArray()
    {
        var text = await JSRuntime.convertArray(quoteArray);
        convertedText = new MarkupString(text);
    }
}
```

### Is your feature request related to a problem? Please describe.
It will make interoperate with JavaScript easier

**Comment by javiercn** [comment]
@redradist thanks for contacting us.

This is not something we can do. You can't register components as `dynamic` within the dependency injection container, and even if you could, you would be limited to a single registration.

Even if you could, registering something as dynamic wouldn't help here, since you wouldn't get any intellisense and would at best get some "nicer" syntax. The plumbing required to enable a nicer syntax (implementing IDynamicProxyObject) is huge and the return value is low.

We don't plan to do this for the reasons stated above, if you wanted to, you could do this yourself by implementing IDynamicProxyObject within a type and delegating it to Invoke and InvokeAsync in an underlying IJSRuntime instance, but this is not something we will likely ever do within the framework.

**Comment by redradist** [comment]
@javiercn 
> 
> 
> @redradist thanks for contacting us.
> 
> This is not something we can do. You can't register components as `dynamic` within the dependency injection container, and even if you could, you would be limited to a single registration.
> 
> Even if you could, registering something as dynamic wouldn't help here, since you wouldn't get any intellisense and would at best get some "nicer" syntax. The plumbing required to enable a nicer syntax (implementing IDynamicProxyObject) is huge and the return value is low.
> 
> We don't plan to do this for the reasons stated above, if you wanted to, you could do this yourself by implementing IDynamicProxyObject within a type and delegating it to Invoke and InvokeAsync in an underlying IJSRuntime instance, but this is not something we will likely ever do within the framework.

Actually I think you did not get my idea ...
Actually even if it is not possible to  inject dynamic, it is possible to do something like this:
```razor
@page "/call-js-example"
@generator JSRuntime

...

@code {
    // Quote (c)2005 Universal Pictures: Serenity
    // https://www.uphe.com/movies/serenity
    // David Krumholtz on IMDB: https://www.imdb.com/name/nm0472710/

    private MarkupString convertedText =
        new MarkupString("Select the <b>Convert Array</b> button.");

    private uint[] quoteArray = new uint[]
        {
            ...
        };

    private async Task ConvertArray()
    {
        var text = await JSRuntime.convertArray(quoteArray);
        convertedText = new MarkupString(text);
    }
}
```
and:
```csharp
class JSRuntime {
    public string HandleAttributeAccess(string attributeAccess) {
        // attributeAccess is "await JSRuntime.convertArray(quoteArray)"
        // Converts to "await JSRuntime..InvokeAsync<string>("convertArray", quoteArray)"
    }
}
```

It will simplify working with `JavaScript` libraries and also conversion of `JavaScript` libraries to `Blazor` ;)
