### ISSUE TITLE
Blazor WebAssembly with Identity Server: Move ApplicationUser to the Shared Class Library

### ISSUE THREAD

**Issue by jjohnson3922** [dotnet/aspnetcore#23173]
I have created a new Blazor WebAssembly (ASP.NET Core Hosted) project with Individual User Accounts selected for authentication. I need to create a model in the shared class library that has a List of the class ApplicationUser called Users. I am attempting to move the ApplicationUser Model in Server.Models to Shared.Models but I recieve an error in the ApplicationDbContext class. This is because the class library cannot reference Microsoft.AspNetCore.Identity, but can reference Microsoft.AspNet.Identity.EntityFramework, 

The ApiAuthorizationDbContext can only take a TUser that is Microsoft.AspNetCore.Identity.IdentityUser. How can I make this work? Is it possible?

### To Reproduce
1. Create a new Blazor WebAssembly ASP.NET Core Hosted Application with Identity.
2. Create a folder in the Shared Library called Models.
3. Move ApplicationUser.cs from Server.Models to Shared.Models.
4. Update Namespace in ApplicationUser from Server.Models to Shared.Models
5. Update Reference in ApplicationDbContext to reference Shared.Models
6. Update Startup.cs in the Server Project to reference Shared.Models
7. Install Microsoft.AspNet.Identity.EntityFramework in the Shared class library. 
8. Add using Microsoft.AspNet.Identity.EntityFramework to ApplicationUser Class in the Shared class library. 

### Exceptions (if any)
The Type 'Shared.Models.ApplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'ApiAuthorizationDbContext<TUser>'. There is no implicit reference conversion from 'Shared.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'.

**Comment by blowdart** [comment]
Can we see your user class?
