### ISSUE TITLE
Add support for OAuth 2.0 client_id/client_secret to be passed through the authorization header

### ISSUE THREAD

**Issue by nlaveck** [dotnet/aspnetcore#23177]
### Is your feature request related to a problem? Please describe.

Currently, in order to support client credentials as described in [RFC 6749](https://tools.ietf.org/html/rfc6749#section-3.2.1), you have to create custom handler class that implements  `OAuthHandler`, override the `ExchangeCodeAsync` method, and write your own extension methods to AuthorizationBuilder as seen [here](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Fitbit/FitbitAuthenticationHandler.cs).

While this is probably the best way to add a new auth provider, it adds work to override the method and build out the header.  It also makes the.AddOAuth extension method unusable for this type of auth.  Since this is the suggested way that RFC 6749 recommends passing through client_id and client_secret through an authorization header using basic auth, not supporting this as a standard OAuth option seems pretty exclusive.

### Describe the solution you'd like
Either of these would be nice

1. Add a bool property to OAuthOptions to conditionally add Basic Auth header as described in RFC 6749.
2. Add a string or AuthenticationHeaderValue property to the OAuthOptions that will use it for the Authorization header in the token route.

### Additional context
Here's an example I ran into that's RFC 6749 complaint where I needed to write a custom provider to use the authentication middleware.
https://goto-developer.logmeininc.com/how-get-access-token-and-organizer-key

**Comment by Tratcher** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/10615

**Comment by nlaveck** [comment]
Closing issue since it is a duplicate.
