### ISSUE TITLE
i18n for blazor not available in vs code

### ISSUE THREAD

**Issue by fabianus76** [dotnet/aspnetcore#23184]
### Is your feature request related to a problem? Please describe.
It is great that you managed to integrate localisation and i18n into the first stable release of Blazor! But something strikes me about the actual situation: i18n is based on resx files and those are only editable in Visual Studio and they only compile in Visual Studio. Thus, i18n is not supported in Visual Studio Code. But vs code is such a charming IDE. I would love to know what are your plans for Blazor: are we bound to Visual Studio when it comes to develop globalized applications or do you pursue any plan to port i18n to vs code, too?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
If I understand you correctly, what you're looking for is a way to work with `resx` files in VS Code. Can you please confirm that I did get it right?

**Comment by fabianus76** [comment]
Hey thanks for your quick reaction. 
I see two possibilities: 
1) as you stated enable editing and live compilation (as in Visual Studio) for vs code
2) as an alternative to resx files why not propose json as a file format so that someone does not need an editor to created resource files

**Comment by mkArtakMSFT** [comment]
> 1. as you stated enable editing and live compilation (as in Visual Studio) for vs code

This is already two asks. For the first one (enable editing resx in VSCode it should be something to be reported in the https://github.com/microsoft/vscode repo.
For the second part of it, I'm not sure it's related to the resx in any way or not. If not, I think you're referring to this feature ask we already track here: #5456 

> 2. as an alternative to resx files why not propose json as a file format so that someone does not need an editor to create resource files

This one is not something we would do immediately. We  can sure track this as a feature ask and keep it on our backlog, to see how the community reacts to that ask, but again - we sure won't do anything on this immediately.
