### ISSUE TITLE
How to expose multiple-argument event with EventCallback?

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/aspnetcore#23182]
The current `EventCallback` only allows a single argument via `EventCallback<TArgs>`. Sometimes, I need to expose events with some arguments. For example, `EventCallback<MouseEventArgs,Foo>`.

As I am new to Blazor, it maybe my ignorance. Is there such a feature available? Or should it be the next feature that I can request?

**Comment by mrpmorris** [comment]
The standard is to create a class that holds all of the values you wish to pass on. Just like the. NET standard EventArgs approach.

**Comment by javiercn** [comment]
@pstricks-fans thanks for contacting us. @mrpmorris answer is correct.

Create a type for your event handler and add the properties there.
