### ISSUE TITLE
Asp.net core with f# Discriminated Unions may not not wrok well

### ISSUE THREAD

**Issue by z2665** [dotnet/aspnetcore#23185]
### Describe the bug
Asp.net core not wrok well with f# Discriminated Unions when include generic type

### To Reproduce

1.create asp.net core API template with F# lang
2.add a Discriminated Unions with  generic type into WeatherForecast.fs
```f#
type WeatherResult<'T> =
    | Weather of 'T
    | WeatherError
```
3. add action into WeatherForecastController
```f#
 [<HttpGet("get")>]
    member __.GetWeather()  =
        WeatherError   //this return type will be infer to WeatherResult<'a>
```
4. then use browser access the url https://localhost:5001/weatherforecast/get
5. then we get a error 404 not found
6. if we give a type to WeatherResult. it will work well like this
```f#
   [<HttpGet("get")>]
    member __.GetWeather()  =
        WeatherResult<string>.WeatherError
```
7.we can get the right result
```
{"tag":1,"isWeather":false,"isWeatherError":true}
```

### Further technical details
- ASP.NET Core version
```
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.301
 Commit:    7feb845744

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 版本 16.6.2

**Comment by javiercn** [comment]
@z2665 thanks for contacting us.

That is due how type inference works in F#. In the first case it will produce an open generic type, which MVC won't consider as a controller, while in the second case, it will produce a closed generic type which MVC will consider a controller. 

If your controller is not a generic type, then the issue is that the same thing described here is happening to the action and the right way to solve it is to be explicit about the return type.

That's why there's a 404 in the first case and a 200 in the second case. 

This is by design, the recommended approach for this is to be explicit about the type.

**Comment by z2665** [comment]
@javiercn  thanks for your answer.
I can know this is by design now. but this case in real world is hard to debug. That costs my all day to find the reason.
It can't trigger any  compile error or runtime error. Is there any way to find the problem quickly?

**Comment by javiercn** [comment]
Unfortunately no. It is not a compile error and having an open generic method is not a runtime error either. I'm not sure if you could write an analyzer or similar for F# that would warn you of that, but that would be the best option.
