### ISSUE TITLE
[.NET Core Identity] How to set option value dynamically from database

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/aspnetcore#23188]
Hi everyone. Currently, I need to change parameter value for my `IdentityOptions` dynamically from db. So, in my `ConsigureServices(...)` method in `Startup.cs`, I have:

    services.AddIdentity<AppUser, IdentityRole>(option =>
    {
        option.Lockout.MaxFailedAccessAttempts = 3; // I need to set this value dynamically from database when server starts
    }).AddEntityFrameworkStores<DataContext>()
      .AddDefaultTokenProviders();

I tried to inject `IOptions<IdentityOptions>` in my `Configure(...)` method but with no success:

    public void Configure(
        IApplicationBuilder app,
        DataContext dataContext,
        IOptions<IdentityOptions> identityOptions)
    {
        var sysPolicy = dataContext.SysPolicy.FirstOrDefault();
        identityOptions.Value.Lockout.MaxFailedAccessAttempts = sysPolicy.DisablePwdLoginFail;
    }

It throws an exception like this (it seems that I can't inject it on my `Configure`):

    System.Exception: Could not resolve a service of type 'Microsoft.AspNetCore.Identity.IOptions' for the parameter 'identityOptions' of method 'Configure' on type 'App.Startup'.

Any idea?

**Comment by HaoK** [comment]
You can try to implement it, see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1
```
services.AddOptions<IdentityOptions>()
    .Configure<DataContext d>(
        (o, d) => 
            o.Value.Lockout.MaxFailedAccessAttempts = d.SysPolicy.FirstOrDefault().DisablePwdLoginFail;
```

**Comment by justinushermawan** [comment]
Hi, I solved this by injecting `IOptions<IdentityOptions> identityOptions` on my `Configure` method in `Startup.cs`:

```
public void Configure(
    IApplicationBuilder app,
    DataContext dataContext,
    IOptions<IdentityOptions> identityOptions)
{
    ...
    identityOptions.Value.Lockout.MaxFailedAccessAttempts = sysPolicy.DisablePwdLoginFail;
    ...
}
```

Thank you.

**Comment by HaoK** [comment]
Great!
