### ISSUE TITLE
Foreign Object not working with blazor svg

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#23183]
When I use this code in blazor
<style>
        div {
            color: white;
            font: 18px serif;
            height: 100%;
            overflow: auto;
        }
    </style>
    <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">

        <polygon points="5,5 195,10 185,185 10,195" />

        
        <foreignObject x="20" y="20" width="160" height="160">
            
            <div xmlns="http://www.w3.org/1999/xhtml">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Sed mollis mollis mi ut ultricies. Nullam magna ipsum,
                porta vel dui convallis, rutrum imperdiet eros. Aliquam
                erat volutpat.
            </div>
        </foreignObject>
    </svg>

it renders nothing.  However, when i do the same thing with html, it works fine.  I even disabled bootstrap but same result.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

We have an issue tracking the work to properly enable SVG support. I'm closing this issue in favor of https://github.com/dotnet/aspnetcore/issues/23183 that collects all of them.
