### ISSUE TITLE
VS2019 Community shows red squiggly lines on renamed Razor components

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/aspnetcore#23186]
# Issue
There are distracting red squiggly lines on renamed Blazor components on 
Visual Studio 2019 Community version 16.6.1.

# How to reproduce

- Open Visual Studio 2019 Community.
- Create a new project `Blazor WebAssembly App` with default option. You will get only one project in the generated solution.
- Add a Blazor component to the `Shared` directory, name it whatever you want. Let's name it `Earth`.
- Use the `Earth` component in the `Index` page. In order to make sure it can run, optionally you can save and run it before proceeding to the next steps.
- Rename the `Earth` to, for example, `Saturn`. Optionally you can save it, clean the solution and rebuild. 
- Back to the `Index` page and change `Earth` to `Saturn`. You will see red squiggly lines on `Saturn`. Whether you clean and rebuild the solution, the lines still exist. 

It seems the issue is only on the visual appearance on the editor. The code is still fine to run.

Hopefully this report is useful for you!

By the way, I don't know where to report bugs on Visual Studio 2019 Community.  Feel free to close this issue if it is regarded as an out-of-topic issue here.

**Comment by mkArtakMSFT** [comment]
Thank you for your reported issue.
We believe this issue will be fixed by our efforts of updating our Razor tooling for .NET 5.
