### ISSUE TITLE
MailKit in Blazor WebAssembly

### ISSUE THREAD

**Issue by guillem-soler-suetta** [dotnet/aspnetcore#23197]
I am trying to send an email with Blazor WebAssembly with the library MailKit but it seems that I'm doing something wrong or it is not possible to do it. I tried the same code with a console app and worked perfectly.

The code I used: 
```
void SendEmail()
        {
            try
            {
                var mailMessage = new MimeMessage();
                mailMessage.From.Add(new MailboxAddress("from name", "myemail@gmail.com"));
                mailMessage.To.Add(new MailboxAddress("to name", "anotheremail@gmail.com"));
                mailMessage.Subject = "subject";
                mailMessage.Body = new TextPart("plain")
                {
                    Text = "Hello"
                };
                using (var smtpClient = new SmtpClient())
                {
                    smtpClient.Connect("smtp.gmail.com", 587, SecureSocketOptions.Auto);
                    smtpClient.Authenticate("myemail@gmail.com", "password");
                    smtpClient.Send(mailMessage);
                    smtpClient.Disconnect(true);
                }

            }

            catch (Exception ex)
            {
                message = ex.Message;
            }
        }
```

When executing the Send method it jumps to the _catch_ and the exception shown it's the following: 
![2020-06-21 10_21_16-Window](https://user-images.githubusercontent.com/41020916/85220191-de618780-b3a9-11ea-87b0-f491f3184b80.png)

I'm trying to use MailKIt to avoid using javascript libraries like smtpjs.

Thank you very much.

**Comment by robertsundstrom** [comment]
What happens if you try ```Console.WriteLine(ex)``` instead? Does that work?

**Comment by guillem-soler-suetta** [comment]
> What happens if you try `Console.WriteLine(ex)` instead? Can you see the error?

Already tried, but as you can see at the bottom of the picture. The exception doesn't show anything. I have the suspicion that no matter what error result jumping to the catch it won't show nothing.

**Comment by javiercn** [comment]
@guillem-soler-suetta thanks for contacting us.

It is unlikely than an smtp client is going to work in Blazor WebAssembly. Ultimately Blazor is subject to the same restrictions that any other application running in the browser. 

That means you can't create TCP or UDP connections since browsers don't allow that.

You'll likely need to do this from an endpoint on a server through a Rest API
