### ISSUE TITLE
[Kestrel] Allow custom URL scheme in endpoint configuration

### ISSUE THREAD

**Issue by ccvca** [dotnet/aspnetcore#23193]
### Problem
I am trying to create a WebApp, which receives Data via a custom TCP-bases protocol. So I've implemented my own ConnectionHandler.
```cs
class CustomProtocol : ConnectionHandler
```
This can be used via ListenX and UseConnectionHandler.
```cs
webBuilder.ConfigureKestrel(opt =>
{
  opt.ListenAnyIP(12345, cfg =>
  {
    cfg.UseConnectionHandler<CustomProtocol>();
  });
}).UseStartup<Startup>();
```
However, the possibility to configure the endpoints via configuration file/environment variable is lost, as all endpoints must be defined in ConfigureKestrel then.
> Microsoft.AspNetCore.Server.Kestrel: Warning: Overriding address(es) 'https://localhost:5001, http://localhost:5000'. Binding to endpoints defined in UseKestrel() instead.

### Proposed Solution
Enable definition of own protocol schemes, which allow the complete configuration of the endpoints again via configuration file.
e.g.
```cs
webBuilder.ConfigureKestrel(opt =>
{
  opt.RegisterScheme<CustomProtocol>(); //<-- Use class name as default scheme, overload available for customizing
}).UseStartup<Startup>();
```
And then extent the configuration file/ environment variable:
```json
...
  "applicationUrl": "CustomProtocol://localhost:12345;https://localhost:5001;http://localhost:5000",
...
```
Thus the full power of the configuration file (port and interface) can be used in the same way for own protocols. At the same time, this provides the ability to support other schemas in Kestrel, such as ws://.

### Alternative Solution
Allow the addition of endpoints without overwriting the endpoints from the configuration.

**Comment by Tratcher** [comment]
You might be able to do this today with named endpoints in config.

```
{
  "Kestrel": {
    "Endpoints": {
      "Custom": {
        "Url": "http://localhost:12345"
      },
      "https": {
        "Url": "https://localhost:5001"
      },
      "http": {
        "Url": "http://localhost:5000"
      },
```
```
webBuilder.UseKestrel((context, serverOptions) =>
{
        serverOptions.Configure(context.Configuration.GetSection("Kestrel"))
          .Endpoint("Custom", listenOptions =>
        {
                 listenOptions.UseConnectionHandler<CustomProtocol>();
        });
});
```

**Comment by ccvca** [comment]
Many thanks, it's not that obvious, as the scheme http is still there, but it is a nice solution at the moment.

For future readers: "ListenOptions" needs to be added, as Endpoint provides an EndpointConfiguration, not ListenOptions.
This is my working example:
```cs
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
  .ConfigureWebHostDefaults(webBuilder =>
  {
    webBuilder.UseKestrel((context, serverOptions) =>
    {
      serverOptions.Configure(context.Configuration.GetSection("Kestrel")).Endpoint("CustomProtocol", endpointConf =>
      {
        endpointConf.ListenOptions.UseConnectionHandler<CustomProtocol>();
      });
    }
    ).UseStartup<Startup>();
  });
```

@Tratcher Thanks for your solution. Please reopen, when you still see the need for custom scheme name feature. I'll close this for now, as I have a solution now.
