### ISSUE TITLE
getting started template Blazor Webassembly project doesn't compile

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/aspnetcore#23192]
Just follow the docs to create a Blazor Webassembly app on Mac 
(Catalina; 16Gb mem, plenty disk free).

https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code

```System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: Cipher Suite negotiation failure
```

Not a great getting started experience. Blazor for us at this point "doesnt work" (ok that's an exageration but you can get our frustration).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please share the full exception details and when exactly you get it?

**Comment by javiercn** [comment]
@mkArtakMSFT that's likely an issue negotiating SSL.

@Tratcher how do we diagnose things like this?

I don't think this might be specific to the customer machine, but not sure how to troubleshoot it.

@SogoGolf if you create an MVC or Razor Pages app, do you run into any issue running it? Did you run the dotnet dev-certs tool? `dotnet dev-certs https --trust` to make sure you have a valid and trusted certificate?

FWIW I don't think this is related to the HTTPS certificate, but lets tick all the boxes.

**Comment by SogoGolf** [comment]
I'll check this dev-certs tomorrow my time and let you know

**Comment by mkArtakMSFT** [comment]
While we're investigating this, @SogoGolf, you can use the `--no-https` when creating the template to unblock you for now.

**Comment by Tratcher** [comment]
I'd want to see the full exception stack trace before investigating further.
