### ISSUE TITLE
string constant for @page directive

### ISSUE THREAD

**Issue by ramihamati** [dotnet/aspnetcore#23195]
https://github.com/dotnet/aspnetcore/issues/15977

I just to add another request for the same feature as in 15977. 

According to the response of 15977:
"However if it becomes a common feature request we'll certainly consider it. Hope that's OK!"

**Comment by javiercn** [comment]
@ramihamati thanks for contacting us.

We'll continue gathering feedback on this, but just in case, you can achieve this by using `@attribute [Route(Constants.PageRoute)]` instead of `@page` and everything else should be the same.

**Comment by javiercn** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by ramihamati** [comment]
@javiercn 
Thanks, the attribute solution is good enough for me for now and I am sure that this is not a high priority for the moment
