### ISSUE TITLE
SpaProxy WebSocket protocol forwarding

### ISSUE THREAD

**Issue by stephtr** [dotnet/aspnetcore#23207]
### Describe the bug
When using `SpaProxy` for proxying a Websocket request/server which uses the `Sec-WebSocket-Protocol` header (in my case [Snowpack](https://www.snowpack.dev/)), [connecting to the server](https://github.com/dotnet/aspnetcore/blob/8541bf6c980558b14131620aea8a7c73af435050/src/Middleware/SpaServices.Extensions/src/Proxying/SpaProxy.cs#L244) fails with: "ws failed: The WebSocket client request requested '' protocol(s), but server is only accepting 'esm-hmr' protocol(s)."

The reason for this is that the `Sec-WebSocket-Protocol` header [gets copied](https://github.com/dotnet/aspnetcore/blob/8541bf6c980558b14131620aea8a7c73af435050/src/Middleware/SpaServices.Extensions/src/Proxying/SpaProxy.cs#L218) via `client.Options.SetRequestHeader`, but in case the response contains the `Sec-WebSocket-Protocol` header, the implementation of `WebSocketHandle` [checks whether the protocol had been set using `client.Options.AddSubProtocol`](https://github.com/dotnet/runtime/blob/1f4d0db2339c37d75723d063827fd2a4c6e2ecef/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L197), which obviously wasn't the case.

### To Reproduce
MVC Core app:
```c#
public void Configure(IApplicationBuilder app)
{
    ...
    app.UseSpa(spa => spa.UseProxyToSpaDevelopmentServer("http://localhost:8080"));
}
```
With a snowpack app listening on Port 8080. When necessary, I could create a sample repo.

### Exceptions (if any)
[Catched exception (SpaProxy#L246)](https://github.com/dotnet/aspnetcore/blob/8541bf6c980558b14131620aea8a7c73af435050/src/Middleware/SpaServices.Extensions/src/Proxying/SpaProxy.cs#L246): "The WebSocket client request requested '' protocol(s), but server is only accepting 'esm-hmr' protocol(s)."

### Fixed by
#23250

### Further technical details
<details><summary>dotnet --info</summary>
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-preview.5.20279.10
 Commit:    8139f1b74e

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20279.10\

Host (useful for support):
  Version: 5.0.0-preview.5.20278.1
  Commit:  4ae4e2fe08

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.5.20279.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.5.20279.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.5.20278.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.5.20278.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by stephtr** [comment]
I'm closing it, since the fix is already merged.
