### ISSUE TITLE
User is unable to read the page if the client device is offline

### ISSUE THREAD

**Issue by EKanadily** [dotnet/aspnetcore#23201]
when the internet is disconnected from server side blazor app the page try to reconnect . if failed it display an error message : "Reconnection failed. Try reloading the page if you're unable to reconnect" thus the user can NOT continue browsing the current page. i would like to say making the error message modal is unnecessarily preventing the user from at least continue reading the current page.

solution : make the error message non-modal so that if the page has some info ( e.g an article) the used can read the info offline.

**Comment by javiercn** [comment]
@EKanadily thanks for contacting us.

You can customize this error message and make it have any appearance you want. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#reflect-the-connection-state-in-the-ui) for details
