### ISSUE TITLE
Remote model validation with ApiController

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#23205]
I have this ApiController:

```c#
[ApiController]
[Route("/workspaces")]
public class WorkspaceController : ControllerBase
{
...
    [HttpGet("VerifyDomain/{domain}", Name = "Verify_Domain")]
    public IActionResult VerifyDomain(string domain) {
      return BadRequest(false);
    }
}
```
and I try to remote validate the model with this attribute

```c#
[Remote("Verify_Domain", HttpMethod = "GET")]
public string Domain { get; set; }
```
The above does not work so how can I validate the model using a `[Remote]` attribute in combination with `ApiController`?

**Comment by javiercn** [comment]
@marcuslindblom thanks for contacting us.

Are you trying to use MVC client-side Validation to perform the remote validation? That's what the remote attribute is for.

Can you describe your scenario in a bit more detail so that we can understand what's going on?

**Comment by marcuslindblom** [comment]
Sorry, I misunderstood this. Closing this issue.
