### ISSUE TITLE
Error on pasting/entering string of more than 16292 characters in Textarea in Blazor

### ISSUE THREAD

**Issue by saafh** [dotnet/aspnetcore#23208]
In Blazor, exceeding the string of more than 16292 characters in the <TextArea> raises an error: "**Attempting to reconnect to the server...**" (check the screenshot below)

![image](https://user-images.githubusercontent.com/16015359/85238169-faa20a80-b423-11ea-8670-b3cab2aa7d77.png)

**Observations:**
1. Regardless if it is one line consisting of 16292 characters or several lines with the total of 16292 characters raises the error.

2. Not only the error, the the binding variable has the value null after that limit of characters reached (if less than 16292 characters, the variable still holds the data)

3. Sometimes the error occurs on 16293 characters, most of the time the limit is 16292 haracters though.

4. if "oninput" event is not called, the error occurs when the focus is lost from the TextArea component.

**index.razor:**
`<textarea rows="@Rows"  @bind="@jsonString" @bind:event="oninput"  />`

**Test Data (16292 characters):**
`asjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsjkhajkasjahskjasjhasjahsja`

**Comment by javiercn** [comment]
@saafh thanks for contacting us.

This is caused because you are trying to send a message that is over the underlying default signalr limits, which are around 32K.

You can do two things to make this scenario work:
* Increase the message size limit for SignalR.
  * This is easy, but I would avoid doing so as it has attached security implications.
* Write a component and use JS interop to send the underlying text.
  * Instead of binding to a textbox directly, create a component that internally renders a text box, and use JS interop to receive the text in chunks, "merge" it together and emit an event that another component can bind to.

**Comment by saafh** [comment]
@javiercn I do not understand why are still dependent on JS. As I do not know JavaScript and want to avoid using JS as much as possible, this is disappointing that basic components are not usable the they should be. Whatever you told me to do with JSInterop, I simply do not understand yet. 

@mkArtakMSFT to me this is not resolved until the team makes the basic html component work properly without additional time waste and using JS or xyz. I am disappointed!

**Comment by javiercn** [comment]
> @javiercn I do not understand why are still dependent on JS. As I do not know JavaScript and want to avoid using JS as much as possible, this is disappointing that basic components are not usable the they should be. Whatever you told me to do with JSInterop, I simply do not understand yet.

Blazor's goal is to remove the majority of JavaScript from your app, but it doesn't aim to remove all as that is not possible (JS is the only language the browser understands).

For server side Blazor there are limits imposed in the length of messages sent from the client to the server for security reasons, and you have the ability to configure those limits based on the security characteristics of your solution. See [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1#buffer-management) for details.

> @mkArtakMSFT to me this is not resolved until the team makes the basic html component work properly without additional time waste and using JS or xyz. I am disappointed!

I understand that this might not be what you expected to hear, but I hope you can appreciate that these limits exist for security reasons and that in some cases, application authors will have to design components to work properly with the given security constraints.

We are considering things we can do in this area to make things easier/better. However, keep in mind that there are many other high priority features that are competing for resources and that it is likely that we don't prioritize this issue until we hear more feedback about it.
