### ISSUE TITLE
Microsoft.AspNetCore.Authentication.JwtBearer nighlty can't be installed on net5.0 projects

### ISSUE THREAD

**Issue by CPlusPlus17** [dotnet/aspnetcore#23202]
### Describe the bug
It is not possible to install the nightly version of Microsoft.AspNetCore.Authentication.JwtBearer within a net5.0 project.
The stable version 3.1.5 could be installed without problems.

### To Reproduce

Try to install or update JwtBearer to nightly version with this project settings:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
</Project>
```

### Exceptions (if any)

> Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0-preview.7.20319.8 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0-preview.7.20319.8 supports: net50 (.NETFramework,Version=v5.0)

### Further technical details
- ASP.NET Core version: Nightly 
- Include the output of `dotnet --info`:  Version:   5.0.100-preview.7.20318.21
- IDE: Rider

**Comment by blowdart** [comment]
@HaoK Might this be connected to the update of the underlying library?

**Comment by HaoK** [comment]
Havent merged that change yet

**Comment by blowdart** [comment]
Oh, build problems then? @dougbu can you take a look?

**Comment by dougbu** [comment]
@CPlusPlus17 your issue may be related to the version of desktop `msbuild` installed on your system. The error sounds very much like it's not new enough to truly understand the `net5.0` TFM.

To confirm: You have a version of Visual Studio older than 16.6 preview 2 installed and did _not_ build using `dotnet msbuild`?

**Comment by CPlusPlus17** [comment]
@dougbu 

I'm using rider and have no visual studio installed.
What I can see, it is using msbuild from the dotnet nighly installation:

Rider states to use C:\Program Files\dotnet\sdk\5.0.100-preview.7.20318.21\msbuild.dll, which is in the version 16.7.31007.

I tried it with the console command:

> dotnet add package Microsoft.AspNetCore.Authentication.JwtBearer -v 5.0.0-preview.7.20322.4

In that case it was successfully installed. Seems rider is not honoring the msbuild version provided by the .net framework.
I think we can close this one, I'll open an issue within jetbrains bug tracker about this problem.

Thanks!

**Comment by blowdart** [comment]
Closing as requested
