### ISSUE TITLE
[Feature] Blazor .resx localisation with Intellisense/TypeGeneration (Like Winforms)

### ISSUE THREAD

**Issue by MichaelPeter** [dotnet/aspnetcore#23214]
Hello dear Community,

I was suprised but I did not find any request for that, did I maybe oversee a roadmap point?
Or is it maybe implemented and I just did not find it? Also not yet shure what is the difficulty in implementing it.

I woul like to to use 
`<p>@NavMenuResources.MyString</p>`

instead of

```
@inject IStringLocalizer<NavMenu> NavMenuResources
<p>@NavMenuResources["MyString"]</p>
```

Here somebody tried it already but it would be nice if it would work out of the box.
Also it is pretty old for Blazor Standards, September 2019
https://gametorrahod.com/workaround-for-client-side-blazor-localization-with-resx/

It is maybe state of the art in javascript and a nice throwback to before 2002,
but it would be nice to have more than dictionary serialisation.

Thank you

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we have control over. This is a VS behavior and you may be able to find help about this behavior in VS docs.
And here is a great community blog post about it: https://gametorrahod.com/workaround-for-client-side-blazor-localization-with-resx/

**Comment by MichaelPeter** [comment]
Thank you for the answer :)

**Comment by MichaelPeter** [comment]
One last question, should I maybe contact the VS Team over user voice regarding this issue? Greetings Michael
