### ISSUE TITLE
IServiceProviderFactory not replacing ServiceProvider

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#23238]
I am starting with a vanilla aspnet core 3.1 web api project.

Full code below. I am attempting to substitute the default `ServiceProvider` with my own decorated version. However, it seems that even though my factory is called, the `IApplicationBuilder.Services` is not set to my IServiceProvider concrete type when the middleware pipeline is configured, and also if I inject IServiceProvider into a controller, it still seems to be the frameworks type that is being used.

Here is a complete code sample showing the issue, the two Debug.Asserts()'s are being hit and I would expect them not to be:

```csharp
  public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();                 
                })
            .UseServiceProviderFactory(new TestServiceProviderFactory());
    }

    public class TestServiceProviderFactory : IServiceProviderFactory<IServiceCollection>
    {
        public IServiceCollection CreateBuilder(IServiceCollection services)
        {
            return services;
        }

        public IServiceProvider CreateServiceProvider(IServiceCollection containerBuilder)
        {
            // decorate the built-in ServiceProvider.
            var inner = containerBuilder.BuildServiceProvider();
            return new TestServiceProvider<ServiceProvider>(inner);
        }
    }

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            var sp = app.ApplicationServices;
            Debug.Assert(sp.GetType() == typeof(TestServiceProvider<ServiceProvider>)); // fails

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }

    public class TestServiceProvider<TInnerProvider> : IServiceProvider
       where TInnerProvider : IServiceProvider, IDisposable
    {
        private readonly IServiceProvider inner;

        public TestServiceProvider(IServiceProvider inner)
        {
            this.inner = inner;
        }

        public object GetService(Type serviceType)
        {
            if (serviceType == typeof(IServiceProvider))
            {
                return this;
            }
            return inner.GetService(serviceType);
        }
    }

    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;
        private readonly IServiceProvider sp;

        public WeatherForecastController(ILogger<WeatherForecastController> logger, IServiceProvider sp)
        {
            _logger = logger;
            Debug.Assert(sp.GetType() == typeof(TestServiceProvider<ServiceProvider>)); // fails
        }

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }

    public class WeatherForecast
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

        public string Summary { get; set; }
    }

```

Am I missing some other key step to replacing the in-built service provider here?

**Comment by dazinator** [comment]
To add some background, the reason I need to decorate the `IServiceProvider` in the first place is because I need to intercept calls to `CreateScope()` so I can keep track of them. this would be possible via custom middleware, except by the time my middleware runs, ASP.NET Core seems to have already created a scope, and I cannot find any documentation about how to override that process. Therefore I figured if I decorate the IServiceProvider instead, and intercept calls to CreateScope() I can keep track of scopes that are created, irrespective of where or how they are created, and this seems cleaner to me - assuming it's actually possible to swap out implementation of IServiceProvider as I have always believed it possible to do so but never actually attempted until now.

**Comment by dazinator** [comment]
It seems the `IApplicationBuilderFactory` and the `IHost` don't get injected with the `IServiceProvider` that I create as per the above `TestServiceProviderFactory`. This in turn means `IApplicationBuilder.ApplicationServices` is not set to that IServiceProvider either.

**Comment by dazinator** [comment]
I think this is a general problem with my approach potentially but I am unsure of a better way to achieve what I need to.
I basically want to intercept whenever an `IServiceScope` is created so I can return my own decorated scope - for the purposes of keeping track of active scopes. The decorator would increment a global counter when it is created, and decrement it when it is disposed. I expect the functionality to grow a bit in the future, but this is my basic hook into visibility of active scopes accross the system.

It seems however, that - as the inner provider is still being Built() and I my outer `IServiceProvider` is just delegating calls to it, services like `IHost` and `IApplicationBuilderFactory` actually get `IServiceProvider`s injected, and these are resolved by the inner container's build() to be its own internal classes `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope`. - and therefore this completely bassed my outer `IServiceProvider` when any of those services go on to do things like `CreateScope()` etc.

So I looked more at CreateScope() in particular, but it doesn't seem possible to register my own `IServiceScopeFactory` for use with the native service provider - as per issue I have created here: https://github.com/dotnet/runtime/issues/38240

So I am kind of stuck.

**Comment by dazinator** [comment]
More specifically, trying to decorate the native ServiceProvider is not possible, because services that are resolved with it, and that have `IServiceProvider` or `IServiceScopeFactory` injected themselves, end up getting the internal service provider as a reference, and not the decorated version. This looks to do with the way the service provider uses a `CallSite` to satisfy those dependencies and these don't appear to be overrideble, i.e to provide a decorated implementation.

Therefore being able to intercept every call to CreateScope() on the native service provider by decorating it appears not possible at present. Is this something you could consider enabling - i.e allowing?

**Comment by akovac35** [comment]
I have the same issue and can confirm the sample code has the described effect.

**Comment by dazinator** [comment]
Im going to start to workaround this issue as I assume there will be no movement on it.

The framework has a bit of a pain area, stemming from:

1. You can't dispose of a disposable IServiceProvider safely unless you can account for all of its DI scopes (as singletons may be resolved and still in use via those DI scopes). For example these could be for active requests or for background jobs / message processing.
2. You can't account for all DI scopes robustly because any service registered for DI (like some of the default services, or perhaps third party .AddXyz() methods) could be accepting an IServiceProvider in its constructor and later using it to CreateScope(). There is no opportunity to track this scope creation.. Decorating the IServiceProvider to intercept calls to CreateScope() in order to track scopes  should work on paper, but in practice, it doesnt work as easily as it should do when using the Native service provider, because the native service provider always injects itself into such services that have that constructor param - not giving you any opportunity to create / inject the decorated version into the service. The workaround for this approach is to find and to override all such service registrations with your own factory method version of the registration, that will create the service but passing your decorator in to its constructor instead. This relies on tracking all such service registrations down First (such as IHost, IApplicationBuilderFactory etc).

Background context: in my scenario I am dealing with a multitenant application, and each tenant has its own IServiceProvider. I am looking to be able to restart a tenant without impacting others, by disposing and rebuilding that tenabr service provider - for example to load that tenants updated plugins, without impacting other tenants by stopping the entire application.

**Comment by davidfowl** [comment]
No this isn't possible. You need to implement a real container to get the transitive graph to work. I would use another container that supports these kinds of hooks.
