### ISSUE TITLE
Blazor WASM server prerendering - Unable to resolve HttpClient

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#23231]
### Describe the bug
I would like to prerender Blazor wasm via server-prerendering. I inject in MainLayout HttpClient. I registered on server-side HttpClient however I am getting exception

### To Reproduce
1) let MainLayout inject HttpClient (in my case MainLayout injects ApiAuthenticationStateProvider which injects HttpClient)
2) create _Host.cshtml
3) fallback to _Host
4) services registration
```
            services.AddHttpClient();

            // blazor services
            services.AddScoped<AuthenticationStateProvider, ApiAuthenticationStateProvider>();
            services.AddTransient<IAuthService, AuthService>();
            services.AddScoped<LayoutService>();
```
5) Exception

### Exceptions (if any)
Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'ApiAuthenticationStateProvider'.

### Further technical details
- ASP.NET Core version 3.1.5

Awesome would be if I could render server-side MainLayout and then replace it by WebAssembly version. Main purpose is to server proper SEO for Google

**Comment by javiercn** [comment]
@glararan thanks for contacting us.

I'm not sure `services.AddHttpClient` registers an HttpClient in DI automatically, maybe you need to add that registration resolving it from the factory.

`services.AddSingleton(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient(""));`

**Comment by glararan** [comment]
@javiercn your solution worked. Thanks

**Comment by mihaimyh** [comment]
@glararan Do you have a repo on GitHub with your code, I am also interested in this topic?

**Comment by glararan** [comment]
@mihaimyh unfortunately its private web site. However I can give you links where you can find something like that

like https://github.com/srpeirce/Blazor-SSR
