### ISSUE TITLE
Children Parameter

### ISSUE THREAD

**Issue by the-avid-engineer** [dotnet/aspnetcore#23248]
### Is your feature request related to a problem? Please describe.

I am trying to make a tabs component, but I don't like using a Cascading Parameter to do it. Feels like a lot of boilerplate.

Here's one way to do it, *with* Cascading Parameter.

`TabsComponent.razor`:

```
<div class="tabs">
    <div class="tab-list">
        <CascadingValue Name="tabs" Value="this">
            @ChildContent
        </CascadingValue>
    </div>

    @foreach (var tab in Tabs)
    {
        if (tab.Key == SelectedTabId)
        {
            <div class="tab-content">
                @tab.Value.Content
            </div>
        }
    }
</div>

@code {

    private Dictionary<string, TabComponent> Tabs { get; set; } = new Dictionary<string, TabComponent>();

    private string? SelectedTabId { get; set; }

    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    internal void AddTab(TabComponent tab)
    {
        if (Tabs.ContainsKey(tab.Id) == true)
        {
            return;
        }

        Tabs.Add(tab.Id, tab);

        StateHasChanged();
    }

    internal void ActivateTab(TabComponent tab)
    {
        SelectedTabId = tab.Id;

        StateHasChanged();
    }

    internal void RemoveTab(TabComponent tab)
    {
        if (Tabs.ContainsKey(tab.Id) == false)
        {
            return;
        }

        Tabs.Remove(tab.Id);

        StateHasChanged();
    }
}
```

`TabComponent.razor`:

```
@implements IDisposable

@if (TabsComponent != null)
{
    <button @onclick="Activate">
        @Label
    </button>
}

@code {

    [CascadingParameter(Name = "tabs")]
    public TabsComponent? TabsComponent { get; set; }

    [Parameter]
    public string Id { get; set; } = $"tab-{Guid.NewGuid()}"

    [Parameter]
    public RenderFragment? Label { get; set; }

    [Parameter]
    public RenderFragment? Content { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();

        if (TabsComponent != null)
        {
            TabsComponent.AddTab(this);
        }
    }

    internal void Activate()
    {
        if (TabsComponent == null)
        {
            return;
        }

        TabsComponent!.ActivateTab(this);
    }

    public void Dispose()
    {
        if (TabsComponent != null)
        {
            TabsComponent.RemoveTab(this);
        }
    }
}
```

Putting it all together looks something like this:

```
<TabsComponent>
    <TabComponent>
        <Label>Tab 1</Label>
        <Content>Tab 1 Content</Content>
    </TabComponent>
    <TabComponent>
        <Label>Tab 2</Label>
        <Content>Tab 2 Content</Content>
    </TabComponent>
</TabsComponent>
```

### Describe the solution you'd like

A new parameter type which injects components which are direct descendants.

```
[ChildrenParameter]
public TChildComponent[] Children { get; set; }
```

This would reduce the above razor files to:

`TabsComponent.razor`:

```
<div class="tabs">
    <div class="tab-list">
        @foreach (var tab in Children)
        {
            <button @onclick="() => ActivateTab(tab)">
                @tab.Label
            </button>
        }
    </div>

    @foreach (var tab in Children)
    {
        if (tab.Id == SelectedTabId)
        {
            <div class="tab-content">
                @tab.Content
            </div>
        }
    }
</div>

@code{
    private string? SelectedTabId { get; set; }

    [ChildrenParameter]
    public TabComponent[] Children { get; set; } = new TabComponent[0];

    internal void ActivateTab(TabComponent tab)
    {
        SelectedTabId = tab.Id;

        StateHasChanged();
    }
}
```

`TabComponent.razor`:

```
@code {
    [Parameter]
    public string Id { get; set; } = $"tab-{Guid.NewGuid()}";

    [Parameter]
    public RenderFragment? Label { get; set; }

    [Parameter]
    public RenderFragment? Content { get; set; }
}
```

Ahh. Much nicer, no?

### Additional context

It seems like this can work side-by-side with explicitly named render fragments.

On the flip side, it seems like this can NOT work with the implicit ChildContent render fragment.

Conceivably, you could make a table component, like so:

```
...
(not going to write everything out here, unless requested)
...

@code {
    [Parameter]
    public TRecord[] Data = new TRecord[0];

    [Parameter]
    public ColumnComponent<TRecord>[] Children { get; set; } = new ColumnComponent<TRecord>[0];

    [Parameter]
    public RenderFragment<TRecord>? Controls { get; set; }
}
```

Using it..

```
<TableComponent Data="@(new object[]{ 1, 2, 3 })">
    <ColumnComponent>
        <Header>Number</Header>
        <Row Context="record">@record.ToString("N")</Row>
    </ColumnComponent>
    <ColumnComponent>
        <Header>Parity</Header>
        <Row Context="record">@(record % 2 == 0 ? "Even" : "Odd")</Row>
    </ColumnComponent>
    <Controls Context="record">
        <button @onclick="CopyToClipboard(record)">Copy</button>
    </Controls>
</TableComponent>
```

Outputs..

```
<table>
   <tr>
       <th>Number</th>
       <th>Parity</th>
       <th></th>
   </tr>
   <tr>
       <td>1</td>
       <td>Odd</td>
       <td><button>Copy</button></td>
   </tr>
   <tr>
       <td>2</td>
       <td>Even</td>
       <td><button>Copy</button></td>
   </tr>
   <tr>
       <td>3</td>
       <td>Odd</td>
       <td><button>Copy</button></td>
   </tr>
</table>
```

**Comment by javiercn** [comment]
@the-avid-engineer thanks for contacting us.

I think that you can implement the same functionality without having to resort to a cascading parameter, specially for passing the component as the parent. If I were to implement something like a tab component I would do something like this:
TabPanel.razor
```razor
<div class="tabs">
    <div class="tab-list">
        @for(var i = 0; i < TabsData.Length; i++)
        {
          var tabData = TabsData[i];
           <Tab Parent="this" TabIndex="i" OnSelected="UpdateTabContent">
                <Title>
                  <!-- Markup for tab title -->
                </Title>
                <Content>
                  <TabContent Value="tabData" />
                </Content>
           </Tab>
        }
    </div>
    <div class="tab-content">
        @_selectedTabContent
    </div>
    }
</div>

@code {
  private (int index, RenderFragment content) _selection;

  public void UpdateTabContent((int index, RenderFragment content) selection) =>
      _selection = selection;

  public void SetDefaultContent(RenderFragment defaultContent){
    _selection = (0, default);
    StateHasChanged();
  }
}
```

Tab.razor
```razor
<div @OnClick="SelectTab">@Title</div>
@code{
  [Parameter] TabPanel Parent { get; set; }
  [Parameter] int Index { get; set; }
  [Parameter] RenderFragment Title {get; set; }
  [Parameter] RenderFragment Content {get; set; }
  [Parameter] EventCallback<(int index, RenderFragment content)> OnSelected {get; set; }

  public override void OnInitialized(){
    if(Index == 0){
      Parent.SetDefaultContent(defaultContent)
    }
  }

  public async Task SelectTab(){
    await OnSelected((Index, Content));
  }
}
```

You can already collect the children of a component using `@ref` and could do something within  `OnAfterRender(Async)` with it. Something like `[ChildrenParameter] public TabComponent[] Children { get; set; } = new TabComponent[0];` doesn't work in the Blazor rendering model because the parent doesn't know who their children are until they have rendered. (That's why `@ref` can only safely be used within OnAfterRender(Async))

Instead, the better way to achieve something like this is to pass in callbacks from the parent into the children components and let the child components invoke the callbacks to update the parent at the right time.

For that, you only need to rely on a CascadingParameter if your component doesn't allow passing down a RenderFragment, but it is much easier to rely on RenderFragments and their ability to capture values implicitly to implement this type of functionality.

**Comment by the-avid-engineer** [comment]
> If I were to implement something like a tab component I would do something like this:

It’s not clear to me from your example how you pass TabData to the TabsComponent.

> Something like [ChildrenParameter] public TabComponent[] Children { get; set; } = new TabComponent[0]; doesn't work in the Blazor rendering model because the parent doesn't know who their children are until they have rendered.

I am curious about how a component can have named render fragments as children if it doesn’t know about its children until they have rendered. (The component decides where to render them, right?)

**Comment by javiercn** [comment]
> I am curious about how a component can have named render fragments as children if it doesn’t know about its children until they have rendered. (The component decides where to render them, right?)

Not sure what you mean by this, Tab can have render fragments as children because the compiler does the work to capture those fragments and pass them as parameters to it from the parent component, you can look at the generated code for details on how this works.

**Comment by the-avid-engineer** [comment]
> > I am curious about how a component can have named render fragments as children if it doesn’t know about its children until they have rendered. (The component decides where to render them, right?)
> 
> Not sure what you mean by this, Tab can have render fragments as children because the compiler does the work to capture those fragments and pass them as parameters to it from the parent component, you can look at the generated code for details on how this works.

My feature request seems to require the same behavior

```
<TabsComponent>
    <TabThing Id="tab-1" Disabled="false" ...>
        <Label>Tab #1</Label>
        <Content>Content #1</Content>
    </TabThing>
</TabsComponent>
```

As you've said, `Label` is a RenderFragment, and gets passed to `TabThing` as a parameter. Additionally, `TabThing` other parameters (Id, Disabled, ...)

`TabThing` is something new (not a component, not a render fragment), and gets passed to `TabsComponent` as a parameter.
