### ISSUE TITLE
Azure app service - Blazor Webassembly App ASP.NET Core Hosted with Authentication - HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by rxelizondo** [dotnet/aspnetcore#23244]
When deploying a Blazor Webassembly App with ASP.NET Core Hosted and Authentication enabled to an Azure app service you get error `HTTP Error 500.30 - ANCM In-Process Start Failure`

To reproduce:

- Using the built in template, create a Blazor Webassembly App with ASP.NET Core Hosted and Authentication options enabled. 
- Change the identity database connection string to a database that can be access from the Azure app service where the application is begin deployed.
- Deploy the app and you should get `HTTP Error 500.30 - ANCM In-Process Start Failure`

Console output:

![Err](https://user-images.githubusercontent.com/13452107/85342967-63839400-b4b1-11ea-802b-6637f6f56089.png)

More info:

- If ran locally (from within Visual Studio) everything works fine.
- If I deploy the same app without authorization enabled everything works fine.
- Using standard 2019 Visual Studio (not preview) with target framework .NET Core 3.1.

Other issues related to error `HTTP Error 500.30 - ANCM In-Process Start Failure` but I suspect this is a different issue than previous ones.

Any help is greatly appreciated.

**Comment by javiercn** [comment]
@rxelizondo thanks for contacting us.

You need to provision a key to sign the tokens and configure the application to pick it up. See [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#deploy-to-production) for details.
