### ISSUE TITLE
Identity scaffolding;  override all files; generated code has an error in ExternalLogins.cshtml.cs

### ISSUE THREAD

**Issue by sarchibald-mdsol** [dotnet/aspnetcore#23240]
I added Microsoft.AspNetCore.Identity.UI (3.1.5) and other Identity dependencies to my project.
Added scaffold item / Identity;
Override ALL files;

Generated code will not compile. Error is in ExternalLogins.cshtml.cs, line 63:
```
return RedirectToPage();onException($"Unexpected error occurred removing external login for user with ID '{userId}'.");
```
the name "onException" does not exist in the current context
onException is unreachable code

Seems you have testing holes...

**Comment by sarchibald-mdsol** [comment]
Interesting. I tried it again, but left the text box for the layout page to use as blank, and the generated code now compiles fine...

**Comment by sarchibald-mdsol** [comment]
I take it back. It still fails. The errors didn't show up until I tried the first build.

**Comment by HaoK** [comment]
I can't reproduce this behavior @deepchoudhery have you seen anything like this?
