### ISSUE TITLE
DotNet Bazor List variable mixing data with few same page clients

### ISSUE THREAD

**Issue by itbankas** [dotnet/aspnetcore#23254]
### Describe the bug
I created a small Blazor app and have a really strange issue:
if few customers select Input date on the same page, FROMDATE variable is mixing between all 3 different sessions
On variable change, I am updating List from database

I tried
*to set variables as private
*remove {get; set;} 
*change shared component to *.razor

But still if one of them changes InputDate all of the 3 clients  get this date updated After 

I think this is an issue because if customer use sensitive information it could be got on another clients computer

### To Reproduce
1. Book.razor

```razor
<input type="date" name="fromdate" id="fromdate" autocomplete="off" placeholder="Choose date" required minlength="10" class="form-control" @bind="fromdate" @bind:format="yyyy-MM-dd" />

@code{
private DateTime fromdate = DateTime.Today;
private DateTime old_fromdate = DateTime.Today;
private List<order> all_orders = new List<order>();

    private async void Update()
    {
        Console.WriteLine("Update started");
        all_orders = await new DataController().GetOrders(room_id, fromdate);
        Console.WriteLine("Init Orders: " + room_id + ", " + fromdate);
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (old_fromdate != fromdate)
        {
            Console.WriteLine("Date changed");
            old_fromdate = fromdate;
            Update();
        }
    }
}
```

### Exceptions (if any)
No exception 

### Further technical details
Windows 10

DotNet --info
 It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
