### ISSUE TITLE
IdentityServer configuration without Entity Framework

### ISSUE THREAD

**Issue by nheath99** [dotnet/aspnetcore#23253]
### Is your feature request related to a problem? Please describe.
I want to use the [IdentityServerBuilderConfigurationExtensions.AddApiAuthorization](https://github.com/dotnet/aspnetcore/blob/6a4d79cfb8f8f93bad9ab9a041216ecb32e645fa/src/Identity/ApiAuthorization.IdentityServer/src/IdentityServerBuilderConfigurationExtensions.cs#L52) extension method, I am forced to use Entity Framework. I want to use my custom provider instead.
The StackOverflow issue below describes the problem I am having.
https://stackoverflow.com/questions/62051608/blazor-webassembly-authentication-with-identityserver4-asp-net-core-identity-an

### Describe the solution you'd like
The ideal solutuon would be to pass in my custom provider(s) to an extension method:

    services.AddApiAuthorization<User, CustomUserManager, ...>();

### Additional context
.

**Comment by blowdart** [comment]
The identity server extensions we have are for the simple scenarios, and this is by design. Once you go outside those, and using custom providers is outside those, you have to revert to configuring identity server with their own configuration options.
