### ISSUE TITLE
Integrate Blazor Wasm with Blazor ServerSide

### ISSUE THREAD

**Issue by fayzulla07** [dotnet/aspnetcore#23252]
I am developing an application on Blazor (client)
and I would like to use the Blazor (server) inside my application. How can I achieve this?

I searched for information on docs.microsoft.com and found only integration with razor pages
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/integrate-components?view=aspnetcore-3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not possible nor we plan to support it in the future.
