### ISSUE TITLE
Blazor Web Assembly - VS freezes while debugging, pasting text

### ISSUE THREAD

**Issue by pratip-bagchi** [dotnet/aspnetcore#23266]
The program devenv.exe version 16.6.30204.135 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 2178
 Hang type: Top level window is idle

Even with a boot strapping code is making the IDE hung

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
