### ISSUE TITLE
Blazor WebAssembly ClientWebSocket Credentials/Cookies

### ISSUE THREAD

**Issue by tmrobert8** [dotnet/aspnetcore#23269]
### Describe the bug
I have a websocket server on a specific domain/port that requires authentication (looks for a user.identity).  However, when I provide credentials - no authentication header is added to the initial handshake requests.

Likewise, if I try to send a cookie - the cookie isn't sent either.

### To Reproduce
```
            var cc = new CredentialCache();
            cc.Add(new Uri("wss://myservice.mydomain.com:55822"), "NTLM", new NetworkCredential("user", "password", "domain"));

            var cookies = new CookieContainer();
            cookies.Add(new Cookie("howdy", "this is a cookie", "/", ".mydomain.com"));

            var ws = new ClientWebSocket
            {
                Options = {
                    UseDefaultCredentials = false,
                    Credentials = cc,
                    Cookies = cookies
                }
            };

            await ws.ConnectAsync(new Uri("wss://myservice.mydomain.com:55822/"), CancellationToken.None);
```

Run the above in Blazor WebAssembly.  Please note that I can run the same code in a console app and it works correctly..

### Request headers
```
{"Request Headers (514 B)":{"headers":[{"name":"Accept","value":"*/*"},{"name":"Accept-Encoding","value":"gzip, deflate, br"},{"name":"Accept-Language","value":"en-US,en;q=0.5"},{"name":"Cache-Control","value":"no-cache"},{"name":"Connection","value":"keep-alive, Upgrade"},{"name":"Host","value":"myservice.mydomain.com:55822"},{"name":"Origin","value":"https://mylocalmachine.mydomain.com:44396"},{"name":"Pragma","value":"no-cache"},{"name":"Sec-WebSocket-Extensions","value":"permessage-deflate"},{"name":"Sec-WebSocket-Key","value":"OAR+n+P+bOt21Nqs1YzxFw=="},{"name":"Sec-WebSocket-Protocol","value":"undefined"},{"name":"Sec-WebSocket-Version","value":"13"},{"name":"Upgrade","value":"websocket"},{"name":"User-Agent","value":"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"}]}}
```

Note that there were no cookies sent via this request

### Response headers
```
{"Response Headers (150 B)":{"headers":[{"name":"Content-Length","value":"0"},{"name":"Date","value":"Tue, 23 Jun 2020 18:26:57 GMT"},{"name":"Server","value":"Microsoft-HTTPAPI/2.0"},{"name":"WWW-Authenticate","value":"Negotiate"},{"name":"WWW-Authenticate","value":"NTLM"}]}}
```

### Exceptions (if any)
Simply the exception throw via the 401

Firefox can’t establish a connection to the server at wss://myservice.mydomain.:55822/. dotnet.3.2.0.js:1:173928

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: WebSocket connection failure.
System.Net.WebSockets.WebSocketException (0x80004005): WebSocket connection failure. ---> System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.
  at WebAssembly.Net.WebSockets.ClientWebSocket.ConnectAsyncJavaScript (System.Uri uri, System.Threading.CancellationToken cancellationToken) <0x3b01d68 + 0x00450> in <filename unknown>:0 
  at WebAssembly.Net.WebSockets.ClientWebSocket.ConnectAsyncJavaScript (System.Uri uri, System.Threading.CancellationToken cancellationToken) <0x3b01d68 + 0x0049c> in <filename unknown>:0 
  at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore (System.Uri uri, System.Threading.CancellationToken cancellationToken, System.Net.WebSockets.ClientWebSocketOptions options) <0x3af0328 + 0x00204> in <filename unknown>:0 
  at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore (System.Uri uri, System.Threading.CancellationToken cancellationToken) <0x3aef4c8 + 0x001b2> in <filename unknown>:0 
  at Stuff.Web.Client.Data.Sow.StartAsync () <0x3a19a48 + 0x00212> in <filename unknown>:0 
  at Stuff.Web.Client.Pages.Index.OnAfterRenderAsync (System.Boolean firstRender) <0x3a02428 + 0x001b6> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x3540468 + 0x000ca> in <filename unknown>:0 blazor.webassembly.js:1:37761
```

#### browsers
Tried both Firefox and Chrome - they both ignore sending the NTLM/cookies

#### dotnet info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@tmrobert8 thanks for contacting us.

I don't think the handler on WebAssembly supports those things, since you can't do them with a plain websocket in JavaScript. For the cookie, it is likely that it needs to be setup ahead of time in a response from the server, and for the network credentials I don't think it is possible for the user to set them in the browser websocket.
