### ISSUE TITLE
Full document how to specify the project to debug in vs code or add the ability to specify the project for blazor wasm

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/aspnetcore#23265]
I cannot find anything in the documentation, intellisense or even guessing based on the properties of the vs code how to use the type: blazorwasm and specify which project in the folder should be debugged. It looks like this isn't possible and thus it blows up if there are multiple blazor projects in the same solution/directory.

So how does one go about specifying the project since this is a pretty basic requirement (site and admin site as an example)

Thanks!

**Comment by captainsafia** [comment]
@JohnGalt1717 You can try setting the `cwd` property in your `launch.json` to the path of the project. It will look something like `${workspaceFolder}/AdminSite` and `${workspaceFolder}/ClientSite`. You can maintain two different configurations for the admin and client site.

You might also need to set the `webRoot` in the configuration if the sites are served from different subdirectories. The launch configuration options are documented [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#launch-configuration-options).

**Comment by captainsafia** [comment]
Re-opening this. We will include a comment string in the default configuration that points to the documentation. This change will need to be made in the Omnisharp repo.

**Comment by captainsafia** [comment]
Closing as we have documented this now.
