### ISSUE TITLE
Remove LinkerWorkaround.xml

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23262]
We use a trimmer descriptor to work around some deficiencies in the BCL. For 5.0, this should be resolved within the BCL since these issues aren't specific to blazor. 

* [x] System.Runtime.InteropServices.JavaScript
* [x] System.ComponentModel (https://github.com/dotnet/runtime/issues/38582)
* [x] System.Text.Json.Serialization.*Converter (https://github.com/dotnet/runtime/issues/34449)
* [x] https://github.com/mono/linker/issues/1298

**Comment by eerhardt** [comment]
https://github.com/dotnet/runtime/issues/34449 has now been fixed, so the Json Converter entries can be removed.

I have investigated the System.ComponentModel entries, and they will be fixed with https://github.com/dotnet/runtime/issues/38582.

**Comment by eerhardt** [comment]
@pranavkm - With https://github.com/dotnet/runtime/pull/39973 this work should be unblocked now. All remaining LinkerWorkaround.xml entries can now be removed.

I can submit a PR for this today.
