### ISSUE TITLE
Support for x-forwarded-prefix

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#23263]
https://github.com/microsoft/reverse-proxy/issues/13#issuecomment-632524590

When requests traverse a reverse proxy it's common to change parts of the url like the scheme (TLS offloading). That information is sent to the app via additional x-forwarded-* headers. The Forwarded Headers middleware reads these headers and fixes up the request fields so that the application can still properly generate links.

One common manipulation that's not currently supported is to Trim the start of the request path and forward that missing information as part the x-forwarded-PathBase header.

Example:
Original url: https://external.com/pathbase/path?query
Transformed request:
http://internal/path?query
x-forwarded-proto: https
x-forwarded-host: external.com
x-forwarded-pathbase: /pathbase

x-forwarded-pathbase is now supported by YARP and enabled by default.
https://microsoft.github.io/reverse-proxy/articles/transforms.html

**Comment by damianh** [comment]
I've extended HttpOverride with this functionality https://github.com/ProxyKit/HttpOverrides

**Comment by pksorensen** [comment]
I did not get any pathbase headers and added it manually. Is this due to the PathRemovePrefix transform that i had to added it manually like below?
```
{
        "RouteId": "API",
        "ClusterId": "serviceprovider",
        "Match": {
          "Methods": [ "GET", "POST", "PUT", "DELETE", "PATCH" ],
          "Path": "/api/{**catchall}"

        },
        "Transforms": [
          { "PathRemovePrefix": "/api" },
          {
            "RequestHeader": "X-Forwarded-PathBase",
            "Append": "/api"
          }
        ]
      },

```

**Comment by krispenner** [comment]
@Tratcher I've been trying to get this to work myself and from searching it seems the more common header name used across other frameworks is `X-Forwarded-Prefix` I recommend searching yourself. Whereas if you search for `X-Forwarded-PathBase` only ASP .NET Core based results come up with most referencing back to this issue or the YARP project. Just thought maybe you should switch to what appears to be the more popular name of `X-Forwarded-Prefix` instead? Or are these some how different? From my understanding they appear to be identical in their usage.

Also if anyone else comes across this, I got this working (for my needs anyways) with the below code as I don't see any support from MS for it yet.

```cs
app.Use(async (context, next) =>
{
    if (context.Request.Headers.TryGetValue("X-Forwarded-Prefix", out var prefix))
    {
        context.Request.PathBase = prefix.Last();

        if (context.Request.Path.StartsWithSegments(context.Request.PathBase, out var path))
        {
            context.Request.Path = path;
        }
    }

    await next();
});
```

**Comment by Tratcher** [comment]
@krispenner can you give some references for that? Searching, I see a number of questions about it but very few actually supporting it.

**Comment by krispenner** [comment]
Hi @Tratcher, here are some of the examples I found and I could list another 20 if I kept going. There is obviously no standard for this yet, but I'm only suggesting using the `Prefix` name as it seems to be what the broader community is using in relation to this feature and it was also my first search as it seems more intuitive (at least to me). `PathBase` is very ASP.NET Core specific, is only found in relation to YARP (no other library that I can find) and I'd just prefer MS doesn't create any fragmentation if/when this becomes an official standard. Just my 2c.

- [Traefik reverse proxy](https://doc.traefik.io/traefik/middlewares/stripprefix/)
  - > The X-Forwarded-Prefix header can be queried to build such URLs dynamically.
- [Parasoft reverse proxy support](https://docs.parasoft.com/display/DTP20202/Reverse+Proxy+Support)
  - > Configure your reverse proxy to send the following headers to DTP: X-Forwarded-Prefix
- [GeneXus](https://wiki.genexus.com/commwiki/servlet/wiki?45983,ContextPath+Rewrite%3A+X-Forwarded+Headers+Support+%28App+behind+Reverse+Proxy%29,)
  - > There is a draft RFC request to Standarize a new Http Header for this scenario: "X-Forwarded-Prefix". However, is still not supported by many WebServers.
- [Apache Flask](https://www.reddit.com/r/flask/comments/gg2lg5/flask_app_behind_apache_reverse_proxy_in_subpath/)
  - > are you setting the x-forwarded-prefix header in your apache conf?
- [Kong API Gateway](https://github.com/Kong/kong/issues/6190)
  - > Kong will either send an existing X-Forwarded-Prefix header from a trusted sender or will generate a new X-Forwarded-Prefix header containing the entire path.
- [Spring Cloud API Gateway](https://github.com/spring-cloud/spring-cloud-gateway/issues/619)
  - > I was happy to see that X-Forwarded-Prefix was added in 2.0.2.RELEASE
- [Drupal support request](https://www.drupal.org/project/drupal/issues/3086483)
  - > I expected that Drupal respects HTTP_X_FORWARDED_PREFIX and add this prefix to all href
- [Humio](https://docs.humio.com/docs/installation/cluster/nginx-reverse-proxy/)
  - >Humio requires the proxy to add the header X-Forwarded-Prefix
- [ProxyPrefix library](https://pypi.org/project/proxyprefix/)
  - > WSGI middleware to prefix SCRIPT_NAME with X-Forwarded-Prefix header. For services behind a reverse proxy so their URLs contain the proxied path.

**Comment by Tratcher** [comment]
@krispenner thanks, that's a good list. I filed a matching issue for YARP.

**Comment by damianh** [comment]
This should probably happen in 6.0 otherwise one is looking at significant amount of time before it's in an LTS release and won't be aligned with YARP

**Comment by voroninp** [comment]
I see kong sets `x-forwarded-path` and `x-forwarded-prefix`

**Comment by andwi** [comment]
It seams to me that it should be quite straightforward to use the existing pattern in ForwardedHeadersMiddleware and also set PathBase based on the X-Forwarded-Prefix header, unless I have misunderstood something. Will you accept a PR for this even if this issue does not have the help-wanted label?

**Comment by Tratcher** [comment]
Sure, give it a try. FYI this will need a fair number of tests, like path encoding, replacing an exisitng PathBase, etc.

**Comment by andwi** [comment]
As requested by @adityamandaleeka in #49249 here are the proposed api changes for this feature.

```diff
namespace Microsoft.AspNetCore.HttpOverrides
{
    [Flags]
    public enum ForwardedHeaders
    {
+        XForwardedPrefix = 1 << 3,
-        All = XForwardedFor | XForwardedHost | XForwardedProto
+        All = XForwardedFor | XForwardedHost | XForwardedProto | XForwardedPrefix
    }

    public static class ForwardedHeadersDefaults
    {
+        public static string XForwardedPrefixHeaderName { get; } = "X-Forwarded-Prefix";
+        public static string XOriginalPrefixHeaderName { get; } = "X-Original-Prefix";
    }
}

namespace Microsoft.AspNetCore.Builder
{
    public class ForwardedHeadersOptions
    {
+        public string ForwardedPrefixHeaderName { get; set; } = ForwardedHeadersDefaults.XForwardedPrefixHeaderName;
+        public string OriginalPrefixHeaderName { get; set; } = ForwardedHeadersDefaults.XOriginalPrefixHeaderName;
    }
}
```

It occurred to me also that the expanded definition of ForwardedHeaders.All in combination with RequireHeaderSymmetry can be a breaking change when the X-Forwarded-Prefix header is not included in the http request. So not sure anymore if ForwardedHeaders.All should be expanded. Is this an acceptable breaking change? Maybe it's enough to mention it in the release notes since the workaround is to just use the individual flags you need? It would be very strange if ForwardedHeaders.All did not include all flags.

**Comment by halter73** [comment]
API Review Notes:

- Moving the original header value to an `X-Original` header is not as good as putting it in a feature, but is consistent with our other `X-Forwarded` headers.
- Anyone using `ForwardedHeaders.All` explicitly chose it. It's not the default for the middleware or anything like that. You need to recompile to pick up the new prefix because the enum value would be inlined.

API Approved!

```diff
namespace Microsoft.AspNetCore.HttpOverrides
{
    [Flags]
    public enum ForwardedHeaders
    {
+        XForwardedPrefix = 1 << 3,
-        All = XForwardedFor | XForwardedHost | XForwardedProto
+        All = XForwardedFor | XForwardedHost | XForwardedProto | XForwardedPrefix
    }

    public static class ForwardedHeadersDefaults
    {
+        public static string XForwardedPrefixHeaderName { get; } = "X-Forwarded-Prefix";
+        public static string XOriginalPrefixHeaderName { get; } = "X-Original-Prefix";
    }
}

namespace Microsoft.AspNetCore.Builder
{
    public class ForwardedHeadersOptions
    {
+        public string ForwardedPrefixHeaderName { get; set; } = ForwardedHeadersDefaults.XForwardedPrefixHeaderName;
+        public string OriginalPrefixHeaderName { get; set; } = ForwardedHeadersDefaults.XOriginalPrefixHeaderName;
    }
}
```
