### ISSUE TITLE
Changing favicon URL

### ISSUE THREAD

**Issue by hatem-chu** [dotnet/aspnetcore#23264]
Hello,

I'd like tu run my Blazor application with a subpath like: my_domain.com/my_subpath. 
To do this, I added this line to my Startup.cs:
`app.UsePathBase("/my_subpath/"); `
Then, Il added to my _Host.cshtml:
`<base href="/my_subpath/" /> `
Now, with this changes all works fine except the favicon.ico which url is still my_domain.com/favicon.ico instead of  my_domain.com/my_subpath/favicon.ico.

Any suggestion please?

Thanks,

Regards

**Comment by javiercn** [comment]
@hatem-chu thanks for contacting us.

I think this is a browser behavior where the favicon is always requested at the root of the domain. I would suggest you use a small piece of middleware to redirect the request for favicon.ico to subpath/favicon.ico. You can do this before the call to UsePathBase()

**Comment by javiercn** [comment]
You might also be able to do something like `<link rel="icon" 
      type="image/png" 
      href="http://example.com/myicon.png">`

See [here](https://www.w3.org/2005/10/howto-favicon) for details

**Comment by hatem-chu** [comment]
@javiercn 
I added this beforeUsePathBase():
 `RewriteOptions rewriteOptions = new RewriteOptions().AddRedirect("favicon.ico", "my_subpath/favicon.ico");
 app.UseRewriter(rewriteOptions);`
In my local machine, I get this error on my browser console: `GET http://localhost:5000/my_subpath/favicon.ico net::ERR_TOO_MANY_REDIRECTS`
In the server, I still get the root path.

Thanks
