### ISSUE TITLE
Google Authentication Not working. 

### ISSUE THREAD

**Issue by Sethmichael01** [dotnet/aspnetcore#23270]
I get a 404 page can't be found error after trying to authenticate with google in my .NET Core web app.
I get this error after choosing the account I want to you to login.
Error: No webpage was found for the web address: https://unifiedcamp.com/signin-google?state=CfDJ8FgDy3E-NgdMteo6azrxmI9HCCgEc3Zf0hcoqjg-8PtEj8bkME4BFV8Agh-xacojlFk4qupR0tQNriHi7_ycCUEZmWhVjiFsESdYyTFKsgq_zXTPmvHvxRDZM7gdnUj6eqSm5MrJiKGmnmiqbSCvZH90vMzjaITx99KttXlVDQFrbSS4woI-LHa-1wcobKTaq4mExvs2bULAre4mzyoois1R9E51vRrHOdo529hlIVObVs1zX_7e7HWE61ye4mLJ-sdzHz8N9qGzoSUVnF-uzYM&code=4%2F1AGa7kFi2spNbE90nS9DyawYAN4FVUfmcpEabn69VeNA2ZUUIxOgHXq-x_Ng8FdClfUDYFoOZ_uVfVVR4ZYsyBs&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=1&prompt=none#
I have temporarily removed the google auth because it is in production and do not want users to experience the issue at hand.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Tratcher** [comment]
Can you provide a copy of your Startup.cs?

This usually means you're missing a call to UseAuthentication.

**Comment by Sethmichael01** [comment]
Oh yesss!!! Thank you. I just added the UseAuthentication and it worked!!
