### ISSUE TITLE
Undisposed MemoryStream

### ISSUE THREAD

**Issue by pinki** [dotnet/aspnetcore#23271]
I just dove a bit into Identity's source code and saw that in [DataProtectorTokenProvider.cs](https://github.com/dotnet/aspnetcore/blob/cb35b902262535d831209996a2a0053f717dadb3/src/Identity/Core/src/DataProtectorTokenProvider.cs#L88) there's a `MemoryStream` that's not being disposed.

Proposal: Put the `MemoryStream` into a `using` statement to dispose it after use.

**Comment by GrabYourPitchforks** [comment]
Just a note from the runtime perspective: there are no negative consequences that will result from failing to dispose a `MemoryStream` instance. Other `Stream`-derived types (including any custom subclasses of `MemoryStream`) may contain custom dispose logic.

**Comment by pinki** [comment]
Ah, okay. I didn't know that. I always put it inside a `using`, because it implements `IDisposable`.
Thanks!

**Comment by blowdart** [comment]
We'd accept a PR for this :)
