### ISSUE TITLE
Tag helper intellisense fails if project.razor.json doesn't exist within the project directory

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#23281]
There are many cases when the obj/ directory doesn't exist within the project directory. In those cases, our language server needs to know to look for `project.razor.json` file in those directories.

[This](https://github.com/dotnet/aspnetcore-tooling/blob/d648c82b1374dc4424b711266eec804d298b223b/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs#L56) is the code that just checks within the project directory.

We already know about the real location of `project.razor.json` in the client [here](https://github.com/dotnet/aspnetcore-tooling/blob/d648c82b1374dc4424b711266eec804d298b223b/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs#L93). We need to flow that information over to the language server so it finds and monitors it correctly.

**Comment by NTaylorMullen** [comment]
@ajaybhargavb once this gets inserted you should be able to undo your DDRITs hacks 😄
