### ISSUE TITLE
Unable to get Offline Auth work

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#23286]
I have an Asp.Net Core hosted Blazor Wasm PWA with Azure AD authentication, and I followed the this [doc ](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#interaction-with-authentication) as well as [CarChecker ](https://github.com/SteveSandersonMS/CarChecker) sample to support authentication in offline mode. I browse to the website when I am connected to the network, and then I disconnect the network, close the browser and re-open the app, it still creates auth popup and also the LoginStatus stops showing my user name. Any guidance or sugestion on how to proceed next? 

![image](https://user-images.githubusercontent.com/13262438/85497673-f4d33300-b5a3-11ea-8149-5c85afe9d9de.png)

**Comment by javiercn** [comment]
@bancroftway thanks for contacting us.

Can you provide a minimal repro project so that we can make sure we don't miss any detail and can try to help you?

**Comment by bancroftway** [comment]
@javiercn  a repro is here: https://github.com/bancroftway/blazorissuesrepro/tree/offline-auth

I also created a small video to show the issue: https://www.youtube.com/watch?v=rYbNApLw318

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
