### ISSUE TITLE
Package version for ObjectGraphDataAnnotationsValidator

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#23289]
Hello,

I was using the ObjectGraphDataAnnotationsValidator to validate some fields in an EditForm
in a Web Assembly ASP.NET Core project
I noticed that the current version of the NuGet package is 3.2.0-rc1.20223.4.
Is this normal? Or should I use another package? What is the status for this package?
This package is described in [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)

**Comment by pranavkm** [comment]
@boukenka that package experimental that we were hoping to replace with fixes in the BCL in 5.0. That said, it should be perfectly fine to continue using it.

**Comment by mrpmorris** [comment]
@pranavkm did anyone ever look at my suggested validation changes?

**Comment by captainsafia** [comment]
@mrpmorris We did take a look at the suggested changes but it's not something that we intend on integrating into the framework. We think that this particular change would be better suited for a community project.

**Comment by mrpmorris** [comment]
They can't be done as a community project because changes were required to the Blazor classes, that's why I proposed something 100% backwards compatible.
