### ISSUE TITLE
AzureAdB2C Auth Code Flow not working IDX21336

### ISSUE THREAD

**Issue by Krangth** [dotnet/aspnetcore#23284]
### Describe the bug
My website can already connect to b2c using implicit flow without issue. I want to switch to code flow, but I'm getting the following error:

`Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: IDX21336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.`

This is the code I am using to connect:

            services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
                .AddAzureADB2C(options =>
                {
                    options.Instance = b2CConfiguration.Instance;
                    options.ClientId = b2CConfiguration.ClientId;
                    options.ClientSecret = b2CConfiguration.ClientSecret;
                    options.CallbackPath = b2CConfiguration.CallbackPath;
                    options.Domain = b2CConfiguration.Domain;
                    options.SignUpSignInPolicyId = b2CConfiguration.SignUpSignInPolicyId;
                    options.ResetPasswordPolicyId = b2CConfiguration.ResetPasswordPolicyId;
                });
                
            services.Configure<OpenIdConnectOptions>(AzureADB2CDefaults.OpenIdScheme, options =>
            {
                options.ResponseType = OpenIdConnectResponseType.Code;
                options.ClientId = b2CConfiguration.ClientId;
                options.ClientSecret = b2CConfiguration.ClientSecret;
            });

### Further technical details
- ASP.NET Core version 3.1

**Comment by loekd** [comment]
make sure to request an additional scope, the clientid / appid of your application:

```c#
            services.Configure<OpenIdConnectOptions>(AzureADB2CDefaults.OpenIdScheme, options =>
            {
                options.ResponseType = OpenIdConnectResponseType.Code;
                options.Scope.Add(b2CConfiguration.ClientId);
```

**Comment by blowdart** [comment]
I would suggest looking at the new [IdentityWeb](https://github.com/AzureAD/microsoft-identity-web) package from the AAD folks, as this is what will be used going forward and has better support for AAD B2C

**Comment by Krangth** [comment]
@loekd thank you very much. That was the solution.

@blowdart oh wow, thanks for that pro tip. I had no idea this other package existed. I just started using B2C around a month ago and haven't seen it in my various search results for information. Sounds like I should switch to it.

**Comment by blowdart** [comment]
Come 5.0 that new package will be the one we're using by default :)
