### ISSUE TITLE
[Question] Is there a way to throw an error if we receive a GET request with a body?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#23296]
As per specifications it's undesirable for many browsers/servers to include/parse the Body contents of a GET HTTP request. Does ASP.NET Core offer a way for us to handle/short-circuit requests that are considered "malformed" in that regard, or will we need to issue our own middle-ware in the pipeline to do the job?

**Comment by BrennanConroy** [comment]
> or will we need to issue our own middle-ware in the pipeline to do the job?

Yep, that's exactly what you'll need to do.

**Comment by SpiritBob** [comment]
Cheers!
