### ISSUE TITLE
Razor broken auto-formatting?

### ISSUE THREAD

**Issue by Laiteux** [dotnet/aspnetcore#23293]
Hello,

I'm having some troubles with Razor auto-formatting when mixing C# code with HTML:

![Demo](https://share.laiteux.dev/aeuoukbb)

Similar happens when using `Ctrl + K + D`:
![Demo](https://share.laiteux.dev/gbzpsacc)

How could this be fixed? Is this a normal behavior or a bug?

Kind regards,
Matt.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is a known issue we plan to address as part of VS 16.8 release.
The change will roll out as part of a bigger Razor redesign work, which will be available to customers starting VS 16.7 Preview 4 as an optional feature. More details will be available in the VS 16.7 Preview 4 release blog post.
