### ISSUE TITLE
Add a modal \ overlay component

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23319]
* Ability to overlay on any DOM element
* Ability to programmatically show and hide the events
* Optional ability to dismiss the overlay when clicking outside the overlay

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT  Should we move this out of the 5.0 milestone?

**Comment by mkArtakMSFT** [comment]
Closing as there is now a native HTML `dialog` element for this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
