### ISSUE TITLE
Blazor server tests are failing (non-template tests)

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#23312]
Please look up the failures from: https://dev.azure.com/dnceng/public/_test/analytics?definitionId=278&contextType=build

**Comment by pranavkm** [comment]
As part of https://github.com/dotnet/aspnetcore/pull/26519, we addressed the shorter timeouts that was the likely cause for the initial timeout. Closing the issue. The tests will become eligible to be unquarantined after Nov 2 2020.
