### ISSUE TITLE
In VS @code{<enter> results in opening and closing brackets being removed

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#23311]
type `@code{` then hit enter. When you hit `{` it will add a `}`, but as soon as you hit enter those will both be deleted.

**Comment by TanayParikh** [comment]
Expected:
![CodeBlock](https://user-images.githubusercontent.com/14852843/85600608-7659ae00-b602-11ea-9010-cf0f830ea40d.gif)

Actual:

![CodeBlockLost](https://user-images.githubusercontent.com/14852843/85600554-6fcb3680-b602-11ea-8472-e72fab33f315.gif)
