### ISSUE TITLE
Semantic tokens don't work when document is pre-loaded

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#23323]
Repro:
1. Launch a project with a solution, open a document with taghelpers.
1. Close the Solution.
1. Reopen it, see that it doesn't give semantic tokens on the already opened document.

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen this isn't reproing anymore. Did you find this to be a flaky/intermittent thing or was it every time?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen this isn't reproing anymore. Did you find this to be a flaky/intermittent thing or was it every time?

Every time for me

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/dotnet/aspnetcore-tooling/pull/2122.
