### ISSUE TITLE
Inconsistent requirement to specify auth scheme

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#23325]
MVC provides several ActionResults for interacting with the authentication infrastructure.
- ChallengResult
- ForbidResult
- SignInResult
- SignOutResult

These mirror and call similar methods on the HttpContext:
https://github.com/dotnet/aspnetcore/blob/5155e11120cf7ee2e07383225057f66512f00fde/src/Http/Authentication.Abstractions/src/AuthenticationHttpContextExtensions.cs

Problem: These results and their associated methods are inconsistent about their requirement to specify the AuthenticationScheme. E.g. ChallengeResult, ForbidResult, and SignOutResult do not require an auth scheme to be specified, but SignInResult does. The authentication scheme is optional on all of the underlying HttpContext APIs, falling back to the application defaults for each.

Proposal: AuthenticationScheme should be optional for SignInResult as well, and ControllerBase should add the appropriate overload to match.
```
        // Existing
        public virtual SignInResult SignIn(ClaimsPrincipal principal, AuthenticationProperties properties, string authenticationScheme);
        public virtual SignInResult SignIn(ClaimsPrincipal principal, string authenticationScheme);
        // New
        public virtual SignInResult SignIn(ClaimsPrincipal principal, AuthenticationProperties properties);
        public virtual SignInResult SignIn(ClaimsPrincipal principal);
```

This makes the APIs consistent and reduces the verbosity in the Actions.

Example in the wild:
https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L41-L48

**Comment by javiercn** [comment]
@Tratcher just to be clear, you are asking to add two additional overloads, not to change the existing ones. Is that correct?

**Comment by Tratcher** [comment]
Add two new ones, and the existing two should accept a null scheme.
