### ISSUE TITLE
VS LSP Razor editor is broken for projects with spaces in path

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#23336]
Repro:
- Create a BlazorApp in a path with spaces. (E.g, `C:\temp\path with spaces\BlazorApp`)
- Open Index.razor and type `@`

Expected:
C# intellisense

Actual:
![image](https://user-images.githubusercontent.com/1579269/85635765-8dfd5a80-b633-11ea-8893-fe8f53174afb.png)

Note: HTML intellisense is also broken in all sorts of ways

**Comment by NTaylorMullen** [comment]
This done?

**Comment by ajaybhargavb** [comment]
Yeah. Just tested on a Mac and everything seems fine. We need to watch out for file path issues during validation though.
