### ISSUE TITLE
Model Binding in .Razor files fails with properties connected

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/aspnetcore#23331]
### Describe the bug
Model Binding in Razor fails with properties connected

### To Reproduce

This works in MVC and Razor Pages .cshtml files
```csharp
<a href="/Traffic?userrepo=@context.User.Identity.Name@Model.Repos[i].Name" class="rgh-discussion-links">
    View Traffic for Repo since @Model.Repos[i].SyncSince
</a>
```

This does not work in a .razor file, however, this does work, yet not what I want
```csharp
<a href="/Traffic?userrepo=@context.User.Identity.Name @Model.Repos[i].Name" class="rgh-discussion-links">
    View Traffic for Repo since @Model.Repos[i].SyncSince
</a>
```
Note the space

### Exceptions (if any)
A ton of nonsense in the generated g.cs file
![image](https://user-images.githubusercontent.com/8878502/85633123-715e2400-b62d-11ea-8863-171b4a73fe86.png)

### Further technical details
- ASP.NET Core version - 3.1
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/8878502/85633027-470c6680-b62d-11ea-9451-313cfd9c20fb.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
**VS 2019** 
![image](https://user-images.githubusercontent.com/8878502/85633070-5986a000-b62d-11ea-9de5-3638419fe666.png)

**Comment by javiercn** [comment]
@isaacrlevin thanks for the report.

@NTaylorMullen do you have any thoughts?

Does it work if you put the contents of `@` within parenthesis?

**Comment by isaacrlevin** [comment]
I didn't try that, got around it by creating a var to hold it

```csharp
var foo = @context.User.Identity.Name@Model.Repos[i].Name
<a href="/Traffic?userrepo=@foo" class="rgh-discussion-links">
    View Traffic for Repo since @Model.Repos[i].SyncSince
</a>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not a pattern we recommend customers to use as it's somewhat confusing.
Another way you can do this is using `@(context.User.Identity.Name + Model.Repos[i].Name)`
