### ISSUE TITLE
[Question] Do we need to store JsonSerializerOptions if we do serialization out of the box?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#23343]
If we are in an action method and use the methods/objects provided there for supplying json, with no doubt the `JsonSerializerOptions` we configured will be used. But if for example somewhere in our API project we call the `System.Text.Serilization` API and want its options to be the ones used by the framework, do we need to supply an instance of them, or not?

Thank you!

**Comment by captainsafia** [comment]
@SpiritBob -- thanks for reporting this issue. We recommend posting questions like this on StackOverflow.
