### ISSUE TITLE
NewtonsoftJsonOutputFormatter should take declared type into account

### ISSUE THREAD

**Issue by DerPeit** [dotnet/aspnetcore#23346]
This issue is referring to https://github.com/dotnet/aspnetcore/blob/7aba2502f8370a63b5d94729c7a31ffe36bd409c/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonOutputFormatter.cs#L149 and I am not sure if I'd classify this as a bug or an enhancement.

The ``.Serialize``-Method has an overload which accepts a declared type which is especially useful if ``TypeNameHandling`` is a thing. E.g. if the serializer is configured to serialize type names when the actual type is different to the declared type the serializer can only render the type name for root objects if its declared type is specified during serialization explicitly.

Even though the context of type [``OutputFormatterWriteContext``](https://github.com/dotnet/aspnetcore/blob/7aba2502f8370a63b5d94729c7a31ffe36bd409c/src/Mvc/Mvc.Abstractions/src/Formatters/OutputFormatterWriteContext.cs) has a property named ``ObjectType`` its value is not passed to JSON.NET.

**Preconditions:**

- New ASP.NET Core API application has been set-up
- ``Microsoft.AspNetCore.Mvc.NewtonsoftJson`` NuGet is installed and configured properly with ``TypeNameHandling.Auto``

**Steps to reproduce:**

1. Add an empty class ``WeatherForecastBase``
2. Let class ``WeatherForecast`` derive from ``WeatherForecastBase``
3. Change the method ``WeatherForecastController.Get`` to

        [HttpGet]
        public IActionResult Get()
        {
            var rng = new Random();
            var forecast = new WeatherForecast
            {
                Date = DateTime.Now,
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            };

            return new OkObjectResult(forecast) { DeclaredType = typeof(WeatherForecastBase) };
        }

4. Run the project and navigate to ``https://localhost:5001/weatherforecast``

**Expected result:**

A json object with a type, e.g.

    {"$type":"WebApplication1.WeatherForecast, WebApplication1","date":"2020-06-25T16:12:19.016564+02:00","temperatureC":23,"temperatureF":73,"summary":"Balmy"}

**Observed result:**

A json object without a type, e.g.

    {"date":"2020-06-25T16:12:19.016564+02:00","temperatureC":23,"temperatureF":73,"summary":"Balmy"}

**Comment by pranavkm** [comment]
Thanks for the issue report @DerPeit. Changing this would be a breaking change at this point and it's unlikely we would consider it.  Since your issue contained spoke about `TypeNameHandling`, I'd like to say we do not recommend configuring this in your applications especially when working with untrusted input.

**Comment by DerPeit** [comment]
That's a pity because from my viewpoint the impact is relatively low, because

1. The developer must switch to Newtonsoft Json
2. The developer must turn ``TypeNameHandling`` on
3. The developer must explicitly set the ``DeclaredType`` property on the ``ObjectResult``. So there is no overload in the ``ApiController`` base class for the ``Ok`` method that actually touches that property.
4. It will only affect output and add a property ``$type`` which is very unlikely to be there with regular serialization.

But true, it's a breaking change strictly spoken. I'd be happy if you discussed it and maybe consider it.

**Comment by pranavkm** [comment]
> The developer must explicitly set the DeclaredType property on the ObjectResult.

Unfortunately that is not true. MVC implicitly unwraps certain types and configures this property: 

* https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ActionResultOfT.cs#L78
* https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ActionResultTypeMapper.cs#L40

**Comment by DerPeit** [comment]
I see. One more argument that this issue is a bug, though. :wink: But I get your point with the breaking change. What about combining the fix with a compatibility switch? I never looked at how this is implemented, but isn't this exactly what it was made for in the first place?
