### ISSUE TITLE
HTTP 304 response when using Http.sys for a request that should return a 200

### ISSUE THREAD

**Issue by ricmrodrigues** [dotnet/aspnetcore#23345]
### Describe the bug
Basically when requesting static files from a ASP.NET Core 3.1 web app without the appropriate request headers (If-None-Match for eg), I get an HTTP 304, incorrectly. This can come into a client that never had the file in the first place, causing a failure to load.

### To Reproduce

1) run the app locally but using httpsys as the web server
2) make a call to a static file that returns an ETag and a 200
3) make a subsequent call to the same with the ETag on the If-None-Match and get a 304
4) stop sending the ETag and verify you're still getting 304s

request looks like
```
GET https://.../vendor.5b4c15ae6ced0e36f7d3.js HTTP/1.1
User-Agent: PostmanRuntime/7.25.0
Accept: */*
Host: ...
Accept-Encoding: gzip, deflate, br
```

and response looks like
```
HTTP/1.1 304 Not Modified
Cache-Control: public, max-age=31536000
Content-Type: application/javascript
Last-Modified: Wed, 24 Jun 2020 16:55:03 GMT
Accept-Ranges: bytes
ETag: "1d64a48345b98c8"
Server: *** Microsoft-HTTPAPI/2.0
Request-Context: appId=cid-v1:49d13409-b199-43ea-a259-e4893160bf92
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Security-Policy: frame-ancestors https: http: ; script-src 'self' ...
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: master-only;
Referrer-Policy: same-origin
Date: Wed, 24 Jun 2020 21:34:26 GMT
```
### Further technical details
- ASP.NET Core version: 3.1

**Comment by Tratcher** [comment]
Theory: Static Files produces the first 304 response (correctly), and http.sys caches this. On the next request http.sys serves the 304 from cache based only on the URL, it doesn't check the if-modified headers. Does the http.sys cache even implement conditional headers? If not we should prevent it from caching 304s.
