### ISSUE TITLE
Blazor WebAssembly possible solution(s) for slow page load

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/aspnetcore#23342]
Hi,

So, one of the main drawbacks of Bazor wasm is the time it takes to be transferred to the browser, specially on slow networks. There's where traditional front end like Vue holds an edge. 
What about if the dotnet framework could be downloaded to the browser temporary files, like some images and so, and then be called when a blazor wasm page is being called/used? Wouldn't that solve a lot of issues and will eliminate the need to stripdown even further the dotnet dll's?
This would also aliviate the servers because they would not have to send the dotnet framework everytime a user accesses a blazor site, because the framework is already on the client side, from a previous visit to the same or another blazor website.
In a first approach maybe microsoft could toggle the new edge browser to have the dotnet framework in it, and that way they could display a hint on blazor sites accessed by another browser that that particular site loads faster on the new edge browser.

These are is my suggestions to this project.
Thanks for allowing me to give them.

Regards,
Ricardo

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for contacting us.

This is already how it works, the blazor assemblies will be downloaded only the first time, after that, we only request `blazor.boot.json` when the app starts and download new resources only if they have changed. In essence, we do our own client-side caching already using the browser cache APIs.

**Comment by javiercn** [comment]
In general, Blazor can't do anything that a regular Web app can't do.
