### ISSUE TITLE
Blazor EditContext.MarkAsUnmodified marks all fields as "invalid"

### ISSUE THREAD

**Issue by kristof12345** [dotnet/aspnetcore#23349]
### Describe the bug
After calling EditContext.MarkAsUnmodified() in a component all fields are marked as invalid. 
So instead of changing the css classes (on input tags) to "valid" they are changed to "invalid".

### To Reproduce
Try online at: https://blazorfiddle.com/s/39rn0sz3 (Just click on the clear button and see the result.)

```
<EditForm OnValidSubmit=@Finish EditContext=@EditContext>
    <DataAnnotationsValidator />
//Input fields
       <MatButton OnClick=@Clear >Clear</MatButton>
</EditForm>

    private void Clear()
    {
        Model.Clear(); //sets all model fields to null
        EditContext.MarkAsUnmodified();
    }
```

This "invalid" style should be "valid".
<img width="237" alt="Képernyőfotó 2020-06-25 - 17 44 25" src="https://user-images.githubusercontent.com/43353335/85752374-a9d42f80-b70b-11ea-854a-afd315a664d1.png">

### Further technical details
- ASP.NET Core version: 3.1
- VS for macOS

Thanks for the help.

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @kristof12345! We will mark this issue for investigation and look into it at a later time.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
