### ISSUE TITLE
Blazor Routing without routes

### ISSUE THREAD

**Issue by PhilippSonntagORGADATA** [dotnet/aspnetcore#23341]
Hello,

I have a kind of strange feature request. I'm working with an older api that doesn't allow normal, web-like routing with routes in the address bar. The user always has to go on an index page like a dashboard and navigate further, so routes could give the user a wrong sense of a stateless application, that isn't the case.
I'm currently forcing this behaviour by using auth guards in layouts on all routes except the index.

### Solution I'd like
An additional solution that would be nice, is to not display any routes at all. The user wouldn't be able to differentiate between routes, and can't navigate on invalid routes by accident. This could be implemented as an option of the NavigationManager.
I've already created a [solution on a fork](https://github.com/PhilippSonntagORGADATA/aspnetcore/blob/master/src/Components/Web.JS/src/Services/NavigationManager.ts) that doesn't write the routes in the address bar, but a direct integration in aspnetcore would be much better.

### Other options I already tried
I already tried to make a fallback page, that is some kind of a host for all components. You would have to use a project specific service to display different components on this fallback page. This behaviour did work without any changes of the user viewable route, but it wasn't as convenient as just not displaying the route to the user and using it internally.

### Additional context
For all projects that could benefit from this option, I'm using the latest version of server sided Blazor.

**Comment by javiercn** [comment]
@PhilippSonntagORGADATA thanks for contacting us.

I believe what you are looking for is hash based routing (or something like that).

Unfortunately that is not a feature we currently support. since all the browsers we target support HTML5 history APIs. 

If all you care about is the first request to the incoming page, you can probably codify the routes as if they were hash based routes (for example `index.html#!/client/route`) and use JavaScript once the page has been initialized to grab the path on the hash and pass it to the navigation manager.

**Comment by PhilippSonntagORGADATA** [comment]
@javiercn thanks for the fast response.

Hash based routing sounds nice, but it doesn't fit my needs exactly AFAIK. 
I was thinking of an option to disable routes in the browsers address bar completly. The user is supposed to think, that he's always on the same page without any route changes. 
Internally, the Blazor app can work as always with normal routing. The routes should just be hidden from the user.

If this doesn't work with the html5 history api, I have to find another way. It would just be very nice to have this kind of feature directly in Blazor.
