### ISSUE TITLE
Calling protected api from MainLayout.razor results in a loop, from an Azure AD Authenticated Blazor Wasm PWA

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#23363]
I have a Blazor wasm PWA, and I need to call an api only once, when the app starts. As per @SteveSandersonMS 's suggestion in [22987 ](https://github.com/dotnet/aspnetcore/issues/22987), I created a component without any markup to make the api call, and hosted this component inside an AuthorizeView tag in MainLayout.razor. The app is working fine, but seems to be stuck in a loop and keeps trying to navigate to login.microsoftonline.com

Reproduction is here: https://github.com/bancroftway/blazorissuesrepro/tree/protected-api-from-startup

Accompanying video is here: https://www.youtube.com/watch?v=wv5CMQZlcKA

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by robraytaylor** [comment]
I have encountered this issue also - been banging my head on it for a few days before I found this issue logged - is there any workaround for this issue? I want to load a custom Nav Menu from a protected API and I get the exact same issue

**Comment by vindberg** [comment]
Any update on this?

**Comment by mkArtakMSFT** [comment]
Can somebody please confirm if this is still an issue in .NET 8 ?
