### ISSUE TITLE
Make StateHasChanged and InvokeAsync public instead of protected methods in blazor

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#23362]
One good purpose of making them public is an extension method can be called that can call either StateHasChanged or even InvokeAsync.  Also, it will allow another scenario where if you have cascading values what you are cascading is yourself, then the child components can call the invokeasync.  There are many cases I found when a child component will run something on a timer but when it needs to change state, the parent needs to change state too.

**Comment by mrpmorris** [comment]
You don't need to call InvokeAsync on another component. Code executed via that is synchronised across all components.

As for updating the parenr. The component should expose an EventCallback that the parent can subscribe to. It's better to tell an interested party what happened (fire an event) than to tell it what to do about it (render yourself)

**Comment by musictopia2** [comment]
There are cases where I want it to do it by itself.  Otherwise, every time in the parent, I have to have extra code for it.  Also, I have found many cases where it was not synchronised across all components.  I had a case where I had the parent that called statehaschanged but it did not fire on all its children unfortunately.

**Comment by mrpmorris** [comment]
A parent won't trigger a render on its children unless it passes parameters into them.

A child won't cause a render of a parent unless the parent subscribes to an EventCallback that is triggered. 

Could you explain what you are trying to achieve? There might be a better way.

**Comment by musictopia2** [comment]
What I am trying to achieve is something like this.
I have a cross platform library that does lots of processes.  What should happen is if one of them shows the StateHasChanged, then when the cross platform calls the method, then for every component, it would call its statehaschanged.  I know in xaml in wpf, if there was a notifypropertychanged, then it would just change the property.  However, here, since we don't have that, ideally what should happen is the cross platform has an action delegate that the parent component subscribes to.  Then when the cross platform invokes statehaschanged, it should show it for all children.  If they at least had the 2 methods as public and not protected, then i can use cascading parameters.

**Comment by mrpmorris** [comment]
You are describing state management. Your components should subscribe to the changes in the state they consume and decide if they need to refresh.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

This is not a direction we plan to take, these are breaking changes that we don't plan to make.
