### ISSUE TITLE
Localization doesn't work as soon as my action has async code in it

### ISSUE THREAD

**Issue by mkArtak** [dotnet/aspnetcore#23382]
I've started looking into this [StackOverflow question](https://stackoverflow.com/questions/62535145/iviewlocalizer-does-not-work-sometimes-in-net-core-3-1?noredirect=1#comment110687787_62535145) and it seemed odd to me.
However, I've managed to repro this behavior.
Essentially, what's happening is that the localization doesn't work for the below `/bad` action, but works for the `/good` one:

```csharp
        [Route("/bad")]
        public async Task<IActionResult> Index(int id)
        {
            var item = await Task.Run(() => new object());
            return View(null);
        }

        [Route("/good")]
        public async Task<IActionResult> Index(string id)
        {
            var item = await Task.FromResult(new object());
            return View(null);
        }
```

The view is very straight forward:

```cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<h1>@Localizer["Category"]</h1>
```

The full repro project can be found here: https://github.com/mkArtak/LocRepro

**Comment by pranavkm** [comment]
In terms of async flow, result execution and action filters are siblings. Your code effectively looks like this:

```C#
static async Task Main(string[] args)
{
    await SetCultureActionFilter();
    Console.WriteLine(CultureInfo.CurrentCulture);
}

static async Task SetCultureActionFilter()
{
    await Task.Yield();
    CultureInfo.CurrentCulture = new CultureInfo("fr-FR");

    Console.WriteLine(CultureInfo.CurrentCulture);
}
```
Which outputs:

```
fr-FR
en-US
```

.NET Core stores `CultureInfo` on an `AsyncLocal` which only influence values that appear within it's async execution.

tl, dr: Use the localization middleware. Don't set the culture in an action filter.

**Comment by mkArtakMSFT** [comment]
Thanks Pranav!
