### ISSUE TITLE
Could we eliminate ComponentMarkupEncodingPass?

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#23384]
As part of perf investigations, I'm tracking down which parts of Blazor component rendering turn out to be the most expensive, and finding ways to reduce that.

One of the most expensive things is the use of markup blocks. These force the browser to go through its HTML parsing for every such block we insert. Frustratingly, we use markup blocks even just for plain whitespace (e.g., `\r\n\r\n`-type blocks). This is awkward because (1) markup blocks are expensive to insert, and (2) in most cases of whitespace, it's completely redundant anyway.

Separately I'm doing some work to trim whitespace more aggressively. But even after that's done, there will be some remaining cases where we use markup blocks even when plain text nodes would suffice.

From the comments in `ComponentMarkupEncodingPass.cs`, it seems like this is deliberate:

```
// We want to use AddMarkupContent to avoid aggresive encoding during prerendering.
// Specifically, when one of the following characters are in the content,
// 1. New lines (\r, \n), tabs(\t) - so they get rendered as actual new lines, tabs instead of &#xA;
// 2. Any character outside the ASCII range
```

I'm concerned about this because:

 * Having `\r`, `\n`, `\t` inside content will still be common even after my whitespace-removal work, since I'm not removing whitespace characters from within longer nodes - I'm only removing certain cases of nodes that are purely just whitespace.
 * The character-outside-ASCII-range restriction sounds very problematic for non-English applications, as they will be paying a significant extra perf cost

So my question is: **did we *really* implement ComponentMarkupEncodingPass only as a way of generating more readable prerendered HTML output**? Or is it for some other functional purpose?

Because if it is just to make the HTML sources easier to read, I would say that's nowhere near as important as making the application actually perform well. And hence we should eliminate `ComponentMarkupEncodingPass` entirely.

Note that the prerendered HTML sources are going to get less readable anyway because of my whitespace-removal work, and I'm totally fine with that :)

cc @ajaybhargavb @NTaylorMullen for their wisdom

**Comment by ajaybhargavb** [comment]
> did we really implement ComponentMarkupEncodingPass only as a way of generating more readable prerendered HTML output? Or is it for some other functional purpose?

While we got complaints(both internal and external) that the source code isn't readable, there is also one functional reason for this existing. See https://github.com/dotnet/aspnetcore/issues/7147. Having HTML entities like `&nbsp;` directly in the source would not be rendered correctly without this. Not sure if there a more performant way of addressing this if we're okay compromising on the source code readability.
For reference: Here are other issues reported in that area, https://github.com/dotnet/aspnetcore/issues/6185, https://github.com/dotnet/aspnetcore/issues/6875, https://github.com/dotnet/aspnetcore/issues/8511, https://github.com/dotnet/aspnetcore/issues/7495

**Comment by SteveSandersonMS** [comment]
Thanks for the info! That helps to clarify things.

So I would propose then that we change `ComponentMarkupEncodingPass` so that:

 * Whitespace handling is disabled by default, but can be turned on (i.e., revert to 3.x behavior) if the developer uses the new `@preservewhitespace` directive from #23385. I know that's technically breaking, but I'd put it in the same category of justification that applies to #23385 overall. We can document this as a single change to whitespace handling all-up.
 * HTML entity handling continues to apply unconditionally, since nobody ever wants functionally broken output

What do you think, @ajaybhargavb and @NTaylorMullen?

**Comment by ajaybhargavb** [comment]
Your proposal sounds good to me. cc @danroth27 who was involved when this was originally done.

> So I'm unsure why the original ComponentMarkupEncodingPass needed to do something special with them.

Which part are you referring to? I'm having trouble recalling.

**Comment by mkArtakMSFT** [comment]
Closing as this doesn't seem important at the moment.
