### ISSUE TITLE
Question: Will there be newer versions of Blazor Wasm 3.2.0 packages released before November

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#23388]
One of the questions being asked by our management, when we propose working on a Blazor project, is that since it is such a new technology, if there are critical bugs found, how and when the fixes will be available.

I assume that since Blazor is released as a set of packages, there would be new versions of these packages released...but I wanted to double-check if this assumption is correct. Any guesstimates when the next revision of 3.2.0 Blazor packages will be in preview, if any?

**Comment by javiercn** [comment]
@bancroftway thanks for contacting us.

We will evaluate incoming issues as we do with other products and will patch the ones we determine are severe enough to require servicing and those new packages will be released in the regular .NET Core patch schedule.

/cc: @danroth27

**Comment by danroth27** [comment]
Hi @bancroftway. 

Blazor WebAssembly now ships as part of the .NET Core 3.1 SDK. Any critical fixes for Blazor WebAssembly would be handled as part of our monthly .NET Core 3.1 patches. For example, we have couple of fixes coming with the July patch release. These patch updates are generally small and highly compatible.

The next major release of Blazor WebAssembly is happening with .NET 5. We just added Blazor WebAssembly to .NET 5 for [Preview 6](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-6/). .NET 5 is schedule to ship in Nov of this year. You can see the Blazor related features we are working on for .NET 5 in our [roadmap issue](https://github.com/dotnet/aspnetcore/issues/21514).

Please note that although Blazor WebAssembly 3.2 ships with the latest .NET Core 3.1 SDK, it does not inherit the LTS status of .NET Core 3.1. This was the first release of Blazor WebAssembly, and we prefer to ship something more than once before giving it LTS status. Blazor WebAssembly 3.2 is a *Current* release, which means that once we ship .NET 5 later this year you'll need to update within three months to stay in support. We expect .NET 5 to be a highly compatible release.

**Comment by bancroftway** [comment]
Thank you so much for providing clarification.
