### ISSUE TITLE
Being able to do multiple parameters for generics in blazor

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#23386]
I found a case where instead of one generic parameter, i needed to allow for 2 generic parameters.  Its a case where for example, a component where it needs to be enum and also some other class as well.  For example, there could be a list picker that is generic that is being used and one generic parameter is piece data and the other is an enum.  I know in a normal class, i do something like this
public class SimpleEnumPickerVM<E, PI> : SimpleControlObservable where PI : BaseGraphicsCP, IEnumPiece<E>, new()
        where E : struct, Enum

however, in blazor even when using partial classes, when i do the razor part, it won't allow the second parameter when using the typeparam.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

You use `@typaram` multiple times to specify multiple parameters. One time per parameter.
