### ISSUE TITLE
404 error when the webpi route contains "enterprise/enterprise"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23400]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077976/webpi-路由包含enterpriseenterprise时出现404错误.html)._

---
WebApi is no problem with the iis, iisexppress deployment test on the development machine, but the deployment to the server will occur with partial routing return 404 errors, and there is no error log, tested found to be in the request path "enterprise/enterprise" only occurs.
Attachment:
server.png is the server operating system version
dev.png for the developer operating system version
ent.png, enterprise.png settings for applications deployed on the server
ent_test.png, enterprise_test.png as postman test results

---
#### Visual Studio Feedback System on 6/16/2020, 02:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
