### ISSUE TITLE
Viusal Studio Solution (.sln) opened via Mapped Drive vs UNC Path

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23401]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/817253/viusal-studio-solution-sln-opened-via-mapped-drive.html)._

---
When openning a solution via a mapped network drive (for example: **V:\VisualStudio\Test.sln**) and build a "Microsoft.NET.Sdk.Web" project that and been added via a mapped network drive (**V:\VisualStudio\src\TestProject.csproj**) it incorrectly sets TestProject.StaticWebAssets.xml files (in both bin & obj folders) to:
```
<StaticWebAssets Version="1.0">
  <ContentRoot BasePath="_content/Martogg.Web.V3" Path="V:\VisualStudio\src\TestProject\wwwroot\" />
</StaticWebAssets>
```

When I run this web app in IIS I get error saying **V:\VisualStudio\src\TestProject\wwwroot** cannot be found.

However I have noticed if open the solution via a UNC Path (**\\TestServer\TestShare\VisualStudio\Test.sln**) and build the same project correct it sets the TestProject.StaticWebAssets.xml files to:
```
<StaticWebAssets Version="1.0">
  <ContentRoot BasePath="_content/Martogg.Web.V3" Path="\\TestServer\TestShare\VisualStudio\src\TestProject\wwwroot\" />
</StaticWebAssets>
```

The web app now run correctly on IIS.

Can this be fixed so that either UNC Paths or mapped drive paths can be used?

---
#### Visual Studio Feedback System on 11/13/2019, 01:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/19/2019, 06:22 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment]
Mapped drives are user specific. IIS runs as a different user account so it can't see your mapped drives.

**Comment by tb-mtg** [comment]
I also have noticed when using UNC paths in .csproj you lose the ability to view nested project references under dependencies which is a pain.  

Highlighted below are the nested dependencies of a solution on local c drive that show when using relative paths (on left) vs UNC paths (on right), 

![image](https://user-images.githubusercontent.com/12589600/85966160-3f203e00-ba02-11ea-94b3-396201e92361.png)


So if mapped paths cannot be used, what is best practice for <ProjectReference> paths in .csproj files that point to projects on network drives?
* Relative paths
* UNC path with host name using IP Address
* UNC path with host name using share name

**Comment by tb-mtg** [comment]
Same solution moved onto networked drive shows now nested project references at all.
 
![image](https://user-images.githubusercontent.com/12589600/85966291-9de5b780-ba02-11ea-9a46-ca57318e9ff3.png)

How can this be fixed?

**Comment by mkArtakMSFT** [comment]
@tb-mtg the comment regarding the solution structure is not something we control. Consider reporting that via VS Feedback.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
