### ISSUE TITLE
Adding a Blazor Component as link causes crashes and RZ10012 error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23402]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077698/adding-a-blazor-component-as-link-causes-crashes-a.html)._

---
Hi there,

Create a WebAssembly project with ASP.Net Core hosted
I have a Razor Component let's call MyComponent.razor
When I try to add this file as link to the project, VS crashes and/or component unusable

I don't touch the code at all, everything generated by VS
MyComponent.razor code is a copy & paste from SurveyPrompt.razor to make sure it's not my error.

I attached VS log and screenshots

Thanks,
Karoly

---
#### Visual Studio Feedback System on 6/15/2020, 00:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Karoly Herendi on 6/15/2020, 11:30 PM: 

<p>When I add same MyComponent.razor file to project (not as link) everything works fine.</p>

#### Visual Studio Feedback System on 6/17/2020, 11:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen FYI

**Comment by allisonchou** [comment]
This is tagged as being fixed in the new editor, so I'm going to close this out.
If you notice the problem persists, please let us know by filing another issue. Thanks!
