### ISSUE TITLE
Blazor Server Issues when Double Clicking

### ISSUE THREAD

**Issue by kevinandrewsde** [dotnet/aspnetcore#23416]
We recently published a production blazor website which is currently visited by about 10000 people daily. We are seeing numerous reports from users describing all kinds of problems which we could narrow down to a single persistent issue:

As soon as a button click Handler that is async Task or async void awaits anything, the UI accepts additional mouseclicks from users. The problem arises from an issue plaguing many mice nowadays, that they constantly double click after years of use due to hardware failure that many end-users do not recognize.

Even the most minor of connection lag to the server causes blazor to immediately execute the handler code a second time once the await line is hit. The problems that arise from this in production can be anything from ef core crashes due to multiple concurrent uses of a dbcontext to the addition of multiple items to say a shopping cart with "one" click.

 Is there any best practice to avoid this? I think its kind of impractical to have to wrap each and every button click handle or form submit handler with some sort of boolean construct to check whether it is currently executing. Making all handlers not async also fixes the problem but is not a route we whish to take.

The category of problems can be reproduced using any mouse macro software to cause two clicks within 5ms or so of each other and is especially problematic when calling ef core SaveChangesAsync from within a handler.

**Comment by mrpmorris** [comment]
How about adding `onclick=SomeJavaScript` (note the lack of @) to your button to disable it immediately? Then when your async code disables the button at the start and reenables at the end it should (hopefully) do what you want.

If they does work, create a component that wraps the html button.

**Comment by SayusiAndo** [comment]
> Is there any best practice to avoid this? I think its kind of impractical to have to wrap each and every button click handle or form submit handler with some sort of boolean construct to check whether it is currently executing. Making all handlers not async also fixes the problem but is not a route we whish to take.

How about introducing a variable representing whether the UI element was already clicked end the underlying business logic executed or not? You can either hook up to this whether the given HTML element, like button, is enabled or disabled, or you just can control that whether you execute the business logic or not.

Sounds like pain in the neck, but it works.

**Comment by javiercn** [comment]
@kevinandrewsde thanks for contacting us.

The right way to handle this is by having a tracking variable in your component that indicates that you are busy and checking/setting it on the handler and returning early.

```razor
<button disabled="@_busy" Value="do-stuff" />
code{
private bool _busy = false;

public async Task Handler()
{
    if(_busy) return;
    _busy = true;
   try
   {
       // do your thing
   }
   finally
   {
       _busy = false;
   }
}
}

You can encapsulate this behavior in a component to avoid having to repeat it every time.

**Comment by kevinandrewsde** [comment]
Thanks guys, I introduced a boolean and things seem better now over the course of today. I will be monitoring my logs in the coming days and will report back if I see anything suspicious.
