### ISSUE TITLE
Identity Framework Custom Login Page with Blazor

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#23417]
I'm converting Razor code to Blazor and am getting stuck at authentication. I found out that Blazor handles it completely differently than Razor and thus I cannot re-use the code for login/logout pages.

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1

Creating a new project uses a default Identity UI for main functionalities. However, "Add scaffolding items" only adds classic Razor pages. There is no way to see the code for the Blazor implementation.

May I suggest adding scaffolding items to add Blazor implementation of Identity Framework?

And until then, if I want to implement my own version of the pages, where can I find the source code?

Edit: [I found the source code here](https://github.com/dotnet/aspnetcore/tree/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account)

However, it's the same old Razor code, which means there is no Blazor implementation. Which means I should keep the same Razor login page as before?

This could work fine for general login, but I want to have a "register or login" step within the shopping cart -- there I'll need to implement it in Blazor. I haven't found anything online on the topic and it seems to be a delicate topic, so I'll wait for your response before looking further into it.

**Comment by javiercn** [comment]
@mysteryx93 thanks for contacting us.

ASP.NET Core identity is designed to work with traditional web applications. Implementing a native UI with Blazor for Identity is not recommended and is not a feature that we plan to add.  Identity relies on cookies for authentication, and is not something you can control from a server-side Blazor application that runs over a websocket, since there is no response to set the state for the cookie.

**Comment by mysteryx93** [comment]
Which brings an additional question. For the "Accept Cookies" button, how do you make that work in Blazor if you say you can't write cookies?

**Comment by javiercn** [comment]
@mysteryx93 because that is a cookie written on the client with JS for that purpose. Not an http only cookie that the server needs to set in response to an authentication request.

**Comment by mysteryx93** [comment]
OK so I should still use JS for the "Accept Cookies" button.

I found this solution to having a login button on a Blazor page; but I don't like that it posts the password in the URL, and it can't return the login error to display on the page.
http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4316/A-Demonstration-of-Simple-Server-side-Blazor-Cookie-Authentication.aspx

**Comment by mysteryx93** [comment]
Doesn't Blazor allow invoking client-side JavaScript, and thus setting cookies in that way?
