### ISSUE TITLE
[Blazor] Using IJSInProcessRuntime exclusively

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#23413]
Hi,

I'm only interested in Blazor WebAssembly and therefore I want to be able to use synchronous JavaScript interop in my entire application.

I was expecting injecting ```IJSInProcessRuntime``` into a component to work, however I receive the following error message:

**Cannot provide a value for property 'JSRuntime' on type 'XYZ'. There is no registered service of type 'Microsoft.JSInterop.IJSInProcessRuntime'**

I want to avoid casting ```JSRuntime``` to ```IJSInProcessRuntime``` on every call. I guess I can create a base component that will initialize private ```IJSInProcessRuntime``` field in ```OnInitialized``` method, but I think there should be a cleaner way to do this - or is there?

```
private IJSInProcessRuntime m_js;

protected override void OnInitialized()
{
    m_js = (IJSInProcessRuntime)JSRuntime;
```

Thanks.

**Comment by pranavkm** [comment]
```C#
// Program.cs
builder.Services.AddSingleton<IJSInProcessRuntime>(services => (IJSInProcessRuntime)services.GetRequiredService<IJSRuntime>());
```

**Comment by daniel-p-tech** [comment]
That's it, thanks!
