### ISSUE TITLE
[Discussion] Microsoft.AspNetCore.Components.*, Microsoft.JSInterop.* packages will no longer target netstandard2.1

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23424]
In 3.2, Blazor WebAssembly applications compiled to netstandard2.1. As of 5.0-preview7, both Blazor Server and Blazor WebAssembly applications will target .NET 5.0 (TargetFramework = `net5.0`). To better align with this change, the following Blazor packages will no longer target netstandard2.1:

* Microsoft.AspNetCore.Components
* Microsoft.AspNetCore.Components.Authorization
* Microsoft.AspNetCore.Components.Forms
* Microsoft.AspNetCore.Components.Web
* Microsoft.AspNetCore.Components.WebAssembly
* Microsoft.AspNetCore.Components.WebAssembly.Authentication
* Microsoft.JSInterop
* Microsoft.JSInterop.WebAssembly
* Microsoft.Authentication.WebAssembly.Msal

Blazor WebAssembly applications upgrading from 3.2 should update their target framework to net5.0 as part of updating their package references to 5.0. Libraries that reference one of these packages can either update their target framework to net5.0 or multi-target depending on their requirements.

**Comment by 304NotModified** [comment]
Does this mean that with the release of .NET 5, .NET Standard is dead/obsolete?

**Comment by pranavkm** [comment]
@304NotModified these specific packages are tied to the .NET runtime version which is why they are no longer being cross-compiled to netstandard. Packages that targeted netstandard in 3.x will continue to do so in 5.0. 

/cc @terrajobst in case you'd like to add more.
