### ISSUE TITLE
Shadow/virtual DOM in blazor

### ISSUE THREAD

**Issue by CristianBarragan** [dotnet/aspnetcore#23428]
### Is your feature request related to a problem? 

Since this request has been closed for comments, [6774](https://github.com/dotnet/aspnetcore/issues/6774), I would like to follow up about having a shadow DOM/virtual DOM implementation so the JS interop is only called when needed, therefore improving performance.

### Describe the solution you'd like
As part of this [reference types proposal](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) we are going to be able to have basic manipulation of tables inside Wasm. Phase 4 has been approved [June 23rd meeting](https://github.com/WebAssembly/meetings/blob/master/main/2020/CG-06-23.md#poll-on-advancing-to-phase-4). Firefox/Chrome implementation are in the way [roadmap](https://webassembly.org/roadmap/) and more will follow. With this new feature in wasm we are going to be able to hold references to JS/DOM objects. More at [Wasm DOM access and Reference types](https://stackoverflow.com/questions/62587845/wasm-dom-access-and-reference-types/62590701#62590701).

**Comment by SteveSandersonMS** [comment]
This is already the case. Blazor's rendering already uses something like a virtual DOM. The render output goes into RenderTree structures in .NET memory, which are then diffed against the previous tree so we can make minimal DOM updates.

The WASM spec changes for reference types might create opportunities for the underlying `dotnet.wasm` runtime to be implemented in more efficient ways in the future, but this won't force us to change any APIs that Blazor developers work with.

**Comment by CristianBarragan** [comment]
Render tree is an Incremental DOM, but it is using
