### ISSUE TITLE
Identity: Scaffolded Email.cshtml.cs missing Base64 encoding

### ISSUE THREAD

**Issue by mwhouser** [dotnet/aspnetcore#23438]
### Describe the bug

When you scaffold out the "Change Email" page, the page does not base64-encode the change email token. Thus, confirming the email change fails.

The generated token is already base64-encoded, so it survives the web-browser trip. However, the `ConfirmEmailChange` page explicitly base64-decodes the token before passing it to `_userManager.ChangeEmailAsync`.

### To Reproduce

1. Create a new ASP.NET Core MVC application w/ built-in user accounts.
2. Scaffold out the `Account\Manage\Email` page.
3. Check `Areas\Identity\Pages\Account\Manage\Email.cshtml.cs` in `OnPostChangeEmailAsync`

```csharp
var code = await _userManager.GenerateChangeEmailTokenAsync(user, Input.NewEmail);
var callbackUrl = Url.Page(
    "/Account/ConfirmEmailChange",
    pageHandler: null,
    values: new { userId = userId, email = Input.NewEmail, code = code },
    protocol: Request.Scheme);
```

Note that `code` is not base64-encoded. 

The reciprocal `ConfirmEmailChange` page base64-decodes the incoming `code`.

### To Resolve

Change to the following:

```csharp
var code = await _userManager.GenerateChangeEmailTokenAsync(user, Input.NewEmail);
code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
var callbackUrl = Url.Page(
    "/Account/ConfirmEmailChange",
    pageHandler: null,
    values: new { userId = userId, email = Input.NewEmail, code = code },
    protocol: Request.Scheme);
```

**Alternative resolution:**

Remove the base64-decode from `ConfirmEmailChange`. However, that makes the calling code assume the token is web-safe. 

So I like to make the token "black-box" and explicitly base64-encode it before transport.

### Further technical details
- ASP.NET Core version: 3.1
- Visual Studio Version: Community 2019, 16.6.0

**Comment by HaoK** [comment]
Note: this bug isn't in the UI, its only in the scaffolding code

**Comment by deepchoudhery** [comment]
Thanks @HaoK. Will go out in a servicing release soon for 3.1 and 5.0

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/Scaffolding/pull/1361
