### ISSUE TITLE
[Feature Request] Add @generator directive

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#23431]
`Blazor` Javascript interoperate is very unfriendly ... because Javascript is dynamic language and to interoperate we should through static type `JSRuntime`

Consider instead of:
```razor
@page "/call-js-example"
@inject IJSRuntime JSRuntime;

...

@code {
    // Quote (c)2005 Universal Pictures: Serenity
    // https://www.uphe.com/movies/serenity
    // David Krumholtz on IMDB: https://www.imdb.com/name/nm0472710/

    private MarkupString convertedText =
        new MarkupString("Select the <b>Convert Array</b> button.");

    private uint[] quoteArray = new uint[]
        {
            ...
        };

    private async Task ConvertArray()
    {
        var text = await JSRuntime.InvokeAsync<string>("convertArray", quoteArray);

        convertedText = new MarkupString(text);
    }
}
```
to do something like:
```razor
@page "/call-js-example"
@generator JSRuntime

...

@code {
    // Quote (c)2005 Universal Pictures: Serenity
    // https://www.uphe.com/movies/serenity
    // David Krumholtz on IMDB: https://www.imdb.com/name/nm0472710/

    private MarkupString convertedText =
        new MarkupString("Select the <b>Convert Array</b> button.");

    private uint[] quoteArray = new uint[]
        {
            ...
        };

    private async Task ConvertArray()
    {
        var text = await JSRuntime.convertArray(quoteArray);
        convertedText = new MarkupString(text);
    }
}
```
where `JSRuntime ` is custom class that handles request to generate code:
```csharp
class JSRuntime {
    public string HandleAttributeAccess(string attributeAccess) {
        // attributeAccess is "await JSRuntime.convertArray(quoteArray)"
        // Converts to "await JSRuntime..InvokeAsync<string>("convertArray", quoteArray)"
    }
}
```

It will simplify working with `JavaScript` libraries and also conversion of `JavaScript` libraries to `Blazor` ;)

### Is your feature request related to a problem? Please describe.
It will make interoperate with JavaScript easier
It also will help in other scenarios where user should generate bunch of code and it could be implemented in conjunctions with `Source Generators`

**Comment by mrpmorris** [comment]
I've read this a few times and can't work out what you are asking for.

You can inject your own dependency which uses IJSRuntime, or write extension methods. 

Can you explain why your suggestion is an improvement? Not that I carry any weight around here, I just like to understand things.

**Comment by redradist** [comment]
> 
> 
> I've read this a few times and can't work out what you are asking for.
> 
> You can inject your own dependency which uses IJSRuntime, or write extension methods.
> 
> Can you explain why your suggestion is an improvement? Not that I carry any weight around here, I just like to understand things.

It is improvement because it will allow easier to port JavaScript libraries without calling InvokeMethod<string>(...)

And also it will allow to add on the page generative classes, like `JSRuntime` class generator

It is actually similar how `dynamic` works in C#, but `dynamic` is handled by run-time, `@generator` directive will be handled by library

**Comment by mrpmorris** [comment]
Oh I see what you are asking for. How will it make it easier to port JavaScript libraries? Can you give an example?

**Comment by redradist** [comment]
> 
> 
> Oh I see what you are asking for. How will it make it easier to port JavaScript libraries? Can you give an example?

It will easier to convert JavaScript Application that uses JavaScript library
```javascript
...
callSomeStranger('Hey, dude !!');
...
```
this code will be converted to:
```csharp
...
JSRuntime.callSomeStranger('Hey, dude !!');
...
```

Next example:
```javascript
...
obj.callSomeStranger('Hey, dude !!');
...
```
this code will be converted to:
```csharp
...
JSRuntime.obj.callSomeStranger('Hey, dude !!');
...
```

Next example:
```javascript
...
window.setTimeout(...);
...
```
this code will be converted to:
```csharp
...
JSRuntime.window.setTimeout(...);
...
```

In the most code will be add just `JSRuntime` prefix that's all ;)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
