### ISSUE TITLE
Credit processing with Blazor Web Assembly

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#23446]
Is Blazor Team working with Credit card processors like paypal, BrainTree, Stripe and Square to come up with SDKS for Blazor WebAssembly ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to provide as part of the framework. We believe the community will come up with their own solutions to fill in this space. In many cases, such companies provide their own SDKs for different platforms.

**Comment by nssidhu** [comment]
I understand that it is not something Blazor team will do.
My question is more on creating awareness among partner community. I guess most of this organization would not even be aware of Blazor webassembly. I have tried to reaching out to couple of them and they either have not heard of it or there is nothing on their road map.

**Comment by mkArtakMSFT** [comment]
@danroth27 FYI

**Comment by danroth27** [comment]
@nssidhu Could you please point us at some of the partner SDKs that you are referring to? I assume these SDKs are based on JavaScript? If they are, then you should be able to use them through [JavaScript interop](https://docs.microsoft.com/aspnet/core/blazor/call-javascript-from-dotnet).

**Comment by nssidhu** [comment]
I tried PayPal, Braintree, Stripe they are not familiar with blazor and nothing on their roadmap.
Currently using JavaScript version of their SDK in blazing r to accept credit card.
Was wondering if blazor team engages third parties so that they build something for blazor in the payment processing area.
There are many more such payment processors like square, Razorpay etc.



Sent from Yahoo Mail for iPhone


On Monday, June 29, 2020, 9:48 AM, Daniel Roth <notifications@github.com> wrote:




@nssidhu Could you please point us at some of the partner SDKs that you are referring to? I assume these SDKs are based on JavaScript? If they are, then you should be able to use them through JavaScript interop.
