### ISSUE TITLE
PostConfigureCookieAuthenticationOptions cookie name prefix not working as expected

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/aspnetcore#23444]
On line 31 of `PostConfigureCookieAuthenticationOptions` located here:
https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Cookies/src/PostConfigureCookieAuthenticationOptions.cs

The code only sets a cookie name prefix if the name is already empty or null. That doesn't seem right -- it effectively prefixes itself to nothing and in the event of an existing name does not act as a prefix at all.

Thanks!

```cs
if (string.IsNullOrEmpty(options.Cookie.Name))
{
    options.Cookie.Name = CookieAuthenticationDefaults.CookiePrefix + name;
}
```

**Comment by Tratcher** [comment]
More context:
https://github.com/dotnet/aspnetcore/blob/cc3d47f5501cdfae3e5b5be509ef2c0fb8cca069/src/Security/Authentication/Cookies/src/PostConfigureCookieAuthenticationOptions.cs#L27-L34

`name` in this context is the authentication scheme name (e.g. `Cookie`, `External`, `Application`, etc.), not the assigned cookie name (or lack thereof).

**Comment by AndrewTriesToCode** [comment]
That makes sense of there is no cookie name set, but it there is one then the prefix is not used. 

Is the prefix only intended for when no name already exists?

**Comment by Tratcher** [comment]
> Is the prefix only intended for when no name already exists?

Correct. If you provide your own cookie name then you can call it whatever you want.
