### ISSUE TITLE
ModelMetadataType not work with Blazor

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#23442]
I have a project include two project in same **Solution Explorer**

- **First**: DbModelContextProvider (Class library)
- **Second**: AppApiProvider (MVC core api -v3.1.4)

In DbModelContextProvider  project i want create Metadata validation for **Department** 

```
public class DepartmentMetaData
{
        [Display(Name = "Department Name")]
        [Required]
        public string Name { get; set; }
}
```

Then create new class _Department_ but **partial**  class
```
[MetadataType( typeof(DepartmentMetaData))]
 public partial class Department
{
}
```

### Same code use with MVC core web app work success but when i want work with Blazor not work

**Comment by javiercn** [comment]
@zanyar3 thanks for contacting us.

That is an ASP.NET Core feature, not something that Blazor supports.
