### ISSUE TITLE
Consider bumping Wilson to 6.7.1

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/aspnetcore#23441]
The preview7 branch was updated recently to target Wilson 6.6.0... 

https://github.com/dotnet/aspnetcore/blob/b446ab7c6f28bb10879bd355afe08bbf283c7de3/eng/Versions.props#L192-L194

... but Wilson 6.7.0 was released yesterday, so ASP.NET Core should probably target it instead of 6.6.0.

Changelog: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.7.0

**Comment by blowdart** [comment]
@HaoK want to bump it again?

**Comment by HaoK** [comment]
For preview7 @blowdart ?

**Comment by blowdart** [comment]
Sure

**Comment by kevinchalet** [comment]
Updated the title as `6.7.1` was released last week 😄
