### ISSUE TITLE
Serve the runtime from CDN or combine the dll files into fewer requests

### ISSUE THREAD

**Issue by mustakimali** [dotnet/aspnetcore#23449]
I have been fascinated by Blazor and I like how quickly I got productive with it. Well done to the team and @SteveSandersonMS  for the amazing work there. 👏 

I noticed the client-side blazor downloads about 29 dll files. To reduce the latency and bandwidth, is there any way I can use a CDN to download the runtime from? or is there any way I could combine those into a single request?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and for all the good words about Blazor!

Blazor WebAssembly exposes `loadBootResource` API which allows customizing how the boot resources are loaded. You can utilize that to load the runtime from CDN, for example. You can find a sample on how to do that in the `Custom boot resource loading` section of the [3.2 - RC Release blog post](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-release-candidate-now-available).

**Comment by mkArtakMSFT** [comment]
As for combining the assemblies, @SteveSandersonMS may be better positioned to answer this?

**Comment by mkArtakMSFT** [comment]
After some further conversation offline, it seems there is not going to be much benefit from coming the assemblies. We don't plan to support a solution for this out of the box.

**Comment by SteveSandersonMS** [comment]
It's not advisable to combine all the files into one because then you'd lose the benefit of downloading them in parallel. It's only beneficial in cases where there would otherwise be hundreds of requests.
