### ISSUE TITLE
Resolving TagHelper scopes is very expensive due to substringing typenames

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23454]
Looking at several profiles the work done [here](https://github.com/dotnet/aspnetcore/blob/b13cb76c0aa1dd841b037b3c86980803c0c3a34b/src/Razor/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorTagHelperBinderPhase.cs#L466-L469) makes up roughly 23% of CPU time of a Razor parse due to how frequently we substring typenames when resolving TagHelpers. The larger the Blazor project the more time the method takes because it iterates over every TagHelper.

In the grand scheme of things this doesn't have a massive footprint; however, it's something we should probably fix given it's the "lowest" hanging fruit of our parsing perf issues.

**Comment by TanayParikh** [comment]
Part of Big Rock: https://github.com/dotnet/aspnetcore/issues/23524
