### ISSUE TITLE
The blazor project dont hvae startup.cs

### ISSUE THREAD

**Issue by alirezasejdeii** [dotnet/aspnetcore#23455]
I update my visual studio to last version and create new Blazor Web Assambly Project but My client application dont hvae startup file. Is it normal or is bug?

**Comment by Bartmax** [comment]
Blazor web assembly doesn't use startup.cs anymore. It's bootstrapped on program.cs

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This was indeed an intentional choice.

Thanks @Bartmax for answering.

**Comment by alirezasejdeii** [comment]
> Blazor web assembly don't use `startup.cs` anymore. It's bootstrapped on `program.cs`
> 
> checkout: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

Thank you for help.
