### ISSUE TITLE
Blazor WebAssembly adds base path to href tag after navigating to a page from another page

### ISSUE THREAD

**Issue by DenisKudelin** [dotnet/aspnetcore#23466]
I have the following base tag:
`<base href="/someroot/">`

Added link to css:
`<link rel="stylesheet" href="styles.css" type="text/css">`

Added 'a' tag
`<a href="somepage">link</a>`

Everything works ok for now.

Then we navigate to 'somepage' and blazor renders the page like that:

`<base href="/someroot/">`
`<link rel="stylesheet" href="someroot/styles.css" type="text/css">`

As we can see, Blazor added 'someroot' to the link tag and therefore it's not working, because we have "someroot/someroot" path. The issue occurs only after navigating from a relative link.

How can I fix that?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
