### ISSUE TITLE
AuthenticationStateProvider returns wrong information : robustness issue

### ISSUE THREAD

**Issue by ClubberLangG** [dotnet/aspnetcore#23462]
### Describe the bug
I have a blazor web application (server side) (with an identity-server and an API server) and somewhere in a page, before doing a specific remote call on a specific API (this API can only be called when you are authenticated) I also check if the current user is authenticated. Like this:

```
private async Task CallServerAPI()
{
    var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
    if (!authState.User.Identity.IsAuthenticated)
        return;

    await _myService.Update();
}
```

The problem is that in some situations, it is called... so, It seems it is the wrong way to protect my code ?

I have spend a lot of time trying to debug this problem and have noticed that I have the following cookies. If I delete one of theses cookies... it works again!

So,
1 - I don't know why I have theses cookies there? Can it be related to my logout that does not work well or partial cookies expirations ?
2 - How/when should I clear them ?
3 - How can I improve my code to avoid such problem, make it more robust ? (Wrong cookies situation etc) ?

So, it seems that the method depend of some cookies states, and when the state is not correct I got a crash !
It seems that this code is not robust...

### To Reproduce

![image](https://user-images.githubusercontent.com/67060390/86000176-76e0b300-ba0d-11ea-8f88-e10aefef68c7.png)

### Further technical details
- ASP.NET Core 3.2

**Comment by ClubberLangG** [comment]
@mkArtakMSFT It is a blazor server side app, so it is unrelated to wasm ;-)

Thx

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
