### ISSUE TITLE
Support for record types in MVC

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#23465]
The main area of focus is modelbinding/deserialization. For the most part it works, you can define record types and add properties with init only and so on and we should have no problem deserializing or binding to them, since the properties will be public and will have a setter.

We need to examine our support for record types with a "primary" constructor. For these types, I believe we don't have support out of the box. We need to evaluate the work needed to properly integrate with these types. The main issue arises from the fact that these types don't have a parameterless constructor and that can be used to create an instance of the object, and it is not possible to add one in code (as of the latest preview).

I believe the work required here is:
- [ ] Support records with primary constructors in all formatters.
- [ ] Support records with primary constructors in modelbinding.

I believe it is important that we support this syntax, since it significantly reduces the cognitive load of declaring a type. Consider a type hierarchy like a todo list:

```csharp
public class TodoList
{
    public string Title { get; set; }
    public List<TodoItem> Items { get; init; } = new ();
}

public class TodoItem
{
    public int Id { get; init; }
    public string Description { get; init; }
    public bool Done { get; init; }
}
```

Compare that to

```csharp
public record TodoList(string title, List<TodoItem> Items);
public record TodoItem(int Id, string Description, bool Done);
```

Not only the second definition is more succinct an clear, but it is also more correct and less verbose.
* You can't create records with missing data.
* You don't have to specify all property names when creating new instances.

For example:
* First case:
```csharp
new (){ Title ="Review pending issues", TodoItem = new List<TodoItem>() }
```
* Second case
```csharp
new("Review pending issues", new List<TodoItem>())
```

**Comment by javiercn** [comment]
Model metadata is also an area where we will likely have to do work. Mostly because with primary constructors the attributes will appear in the constructor parameters, so we need to grab them from there.

**Comment by mkArtakMSFT** [comment]
This is now done.
