### ISSUE TITLE
IServiceScope not releasing object

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#23460]
# Describe the bug
Blazor server-side has to use IServiceScope to get DatabaseContext to allow concurrent db query. However DatabaseContext is not disposed.

### To Reproduce
Implement simple method like this and call it.

```
        public async Task<List<Item>> GetAllAsync()
        {
            List<Item> items;

            using (IServiceScope scope = scopeFactory.CreateScope()) // |1|
            {
                using DatabaseContext db = scope.ServiceProvider.GetRequiredService<DatabaseContext>(); // |2|

                items = await db.Items.ToListAsync();
            }

            return items; // |3|
        }
```

I did 3 memory snapshots.

1. Snapshot on CreateScope()
2. Snapshot on GetRequiredService - new DatabaseContext in memory
3. Snapshot on return. DatabaseContext stays in memory - Count diff: 0. Suppose to be -1

Result: every time I navigate to page and calling GetAllAsync() gives me more memory consumption. 

Is my design bad? Did I miss anything? Docs says CreateScope should dispose all objects after using. Well its not.

Original method without snapshot tracking looks like:
```
        public async Task<List<Item>> GetAllAsync()
        {
            using (IServiceScope scope = scopeFactory.CreateScope())
            {
                using DatabaseContext db = scope.ServiceProvider.GetRequiredService<DatabaseContext>();

                return await db.Items.ToListAsync();
            }
        }
```

I had to adjust it to take snapshots.

### Further technical details
- ASP.NET Core version 3.1.4

**Comment by mrpmorris** [comment]
If you have lazy loading enabled then your retrieved objects will hold a reference to your DbContext. So make sure that is off, or you don't hold onto loaded objects for too long. 

Can you override DbContext Dispose to output a debug message to prove it is being disposed?  The scope should dispose it for you, so no need to do it explicitly.

**Comment by javiercn** [comment]
@glararan thanks for contacting us.

The disposable objects in a scope will be disposed, but they will remain in memory until the Garbage collector claims them. You can validate that by calling `GC.Collect()` after you've left the scope, and you should see that it is not in memory any more. (You might need to force a full collection)

**Comment by glararan** [comment]
> If you have lazy loading enabled then your retrieved objects will hold a reference to your DbContext. So make sure that is off, or you don't hold onto loaded objects for too long.
> 
> Can you override DbContext Dispose to output a debug message to prove it is being disposed? The scope should dispose it for you, so no need to do it explicitly.

@mrpmorris I am using eager loading. Not lazy loading.

@javiercn I called `GC.Collect() `and then  `GC.WaitForFullGCComplete();`. `DatabaseContext` count in next snapshot is not decreased :(

**Comment by mrpmorris** [comment]
Is DatabaseContext accidentally registered as a singleton?

**Comment by javiercn** [comment]
@glararan can you produce a minimal repro project so that we can investigate what's going on?

**Comment by glararan** [comment]
> Is DatabaseContext accidentally registered as a singleton?

@mrpmorris Not a chance.. as Transient
`services.AddDbContext<DatabaseContext>(options => { options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")); }, ServiceLifetime.Transient);`

**Comment by mrpmorris** [comment]
As a quick experiment, could you try registering as scoped?

**Comment by glararan** [comment]
> As a quick experiment, could you try registering as scoped?

@mrpmorris Count is not decreased even as scoped.

**Comment by javiercn** [comment]
@glararan If you are looking at the memory traffic, you can probably look at what is keeping it rooted (why the GC is not picking it up)

**Comment by glararan** [comment]
> @glararan If you are looking at the memory traffic, you can probably look at what is keeping it rooted (why the GC is not picking it up)

@javiercn well actually that was good point. I never done that before. As now looking at it I navigate out and in multiple times. I should have taken another snapshot outside method. DatabaseContext is no longer present in memory. However my memory increases every time I navigate into page, so I have to find memory leak elsewhere.

Thanks for supp!

**Comment by javiercn** [comment]
@glararan I'm glad we were able to come to a conclusion. 

Keep in mind that some memory growth is expected, specially when you run through new code paths in the framework, as we will create caches and other structures to speed up things for hot paths. That said, that growth is ultimately bounded to the number of types presents in your assembly, but want to make sure that a growth of a few hundred kylobites or a Mb or 2 is expected.

You only have a memory leak if you can prove that you can grow that in an unbound way.

**Comment by glararan** [comment]
@javiercn I have mem leak for sure. On production level app crashes every 2 hours because it runs out of memory. 6GB is not something that Blazor do itself. Just have to found where and what..
