### ISSUE TITLE
Custom Visual Studio Tab Titles for Razor Pages

### ISSUE THREAD

**Issue by thepigeonfighter** [dotnet/aspnetcore#23472]
### Custom Razor Pages Titles 

![Untitled](https://user-images.githubusercontent.com/33707144/86024932-9ec71b00-b9fb-11ea-8a36-54842ae0f98a.png)

As you can see from the above image this gets confusing really quickly, and this is only across three pages. I am not sure the best way of addressing this but maybe a different naming strategy in the title tab. Like "Area/Index.cshtml" or "Page/Index.cshtml" or something. That is a little clunky but I find myself cycling through multiple pages looking for the page I am trying to find.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
