### ISSUE TITLE
Publishing BlazorWasm Hosted with rid does not work

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23477]
`dotnet publish -r linux-x64` does not work.

**Comment by jinzhao1127** [comment]
@pranavkm , this issue still repro on 5.0 preview 8 20403.18, this issue fixed on which version?

**Comment by pranavkm** [comment]
@jinzhao1127 unfortunately the fix isn't making it until our RC1 release. For earlier releases, you might be able to get away by editing your Blazor WebAssembly project file like so:

```diff
-<Project Sdk="Microsoft.NET.Sdk.Web">
+<Project Sdk="Microsoft.NET.Sdk.Web" TreatAsLocalProperty="RuntimeIdentifier">
```

**Comment by v-yingfw** [comment]
@pranavkm This issue still repro in 5.0.100-preview.8.20406.14 after doing the above workaround.

**Comment by EmilyFeng97** [comment]
@pranavkm This issue still reproes in 5.0.100-preview.8.20412.11 after doing the above workaround. The result as below, could you help to have a look?
![image](https://user-images.githubusercontent.com/66412474/90104402-cdfcd600-dd76-11ea-911b-2f5909ba4b98.png)

**Comment by IIARROWS** [comment]
> @pranavkm This issue still reproes in 5.0.100-preview.8.20412.11 after doing the above workaround. The result as below, could you help to have a look?
My understanding is that you have to add that to just your CLIENT project, I did it and published, I also tried to the server project too, but the result is the same:

I get an error in the browser console (I have preview 7):

dotnet.5.0.0-preview.7.20364.11.js:1 Uncaught (in promise) Error: Could not find assembly: Microsoft.AspNetCore.Components.WebAssembly
    at Object.resolve_method_fqn (dotnet.5.0.0-preview.7.20364.11.js:1)
    at Object.bind_static_method (dotnet.5.0.0-preview.7.20364.11.js:1)
    at m (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
    at callRuntimeCallbacks (dotnet.5.0.0-preview.7.20364.11.js:1)
    at postRun (dotnet.5.0.0-preview.7.20364.11.js:1)
    at doRun (dotnet.5.0.0-preview.7.20364.11.js:1)
    at run (dotnet.5.0.0-preview.7.20364.11.js:1)
    at runCaller (dotnet.5.0.0-preview.7.20364.11.js:1)
    at removeRunDependency (dotnet.5.0.0-preview.7.20364.11.js:1)

**Comment by mkArtakMSFT** [comment]
@pranavkm should we update the `milestone` to `rc1` to match to when the fix will be out?
