### ISSUE TITLE
LSPProgressListener use `IProgress<T>` instead of GUID String Token

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23488]
The FAR Handler & LSPProgressListener are using a GUID string instead of a `IProgress<T>` due to a [bug on the LSP platform side of things.](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1081157)

Once that bug is fixed, we need to convert to using the `IProgress<T>` for the LSP communication. Note, this also involves moving from the temporary `SerializableReferenceParams` back to `ReferenceParams` in the FAR Handler.

**Comment by TanayParikh** [comment]
Still blocked externally.

**Comment by TanayParikh** [comment]
Still blocked externally. Backlogging as our current solution of using a GUID works in the interim till the external fix is in.

**Comment by ajaybhargavb** [comment]
@TanayParikh the external issue seems to be resolved. Is this still relevant for us to do at this point?

**Comment by TanayParikh** [comment]
I think our current solution should remain sufficient. I'd briefly looked into the external issue resolution, and I don't think the changes made would allow us to update our approach to using the `IProgress<T>` token. Closing this out, thanks.
