### ISSUE TITLE
System.Net.Http.Json 5.0.0-preview.6.20305.6 - Missing WriteJsonAsync extension method

### ISSUE THREAD

**Issue by ansarizafar** [dotnet/aspnetcore#23495]
I have used 
```
dotnet add package System.Net.Http.Json --version 5.0.0-preview.6.20305.6 
```
command to add  System.Net.Http.Json package and I am trying to use WriteJsonAsync extension method in my endpoint route but the extension method is not available. Why this extension method is missing.
```
                    await context.Response.WriteJsonAsync(user);       
or
                    await context.Response.WriteAsJsonAsync(user);                    


```

**Comment by halter73** [comment]
Thanks for the report.

I'm reopening this in the aspnetcore repo because WriteJsonAsync is part Microsoft.AspNetCore.Http.Extensions, and you shouldn't need an extra using to use an extension method. Extension methods are supposed to share a namespace with the type they are extendding.

**Comment by Tratcher** [comment]
@JamesNK

**Comment by halter73** [comment]
We already started discussing this on #23496. I didn't realize this was an intentional decision.

**Comment by JamesNK** [comment]
Hi @ansarizafar

We have moved the extension methods to Microsoft.AspNetCore.Http to make them more discoverable. In a future preview you will need to update the using statement.
