### ISSUE TITLE
Cannot drag & drop files into .cshtml/.razor files in Codespaces

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23494]
VSTS issue with the details: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1144851
PR with css/htmly fix: https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/257978

**Comment by TanayParikh** [comment]
Does this include dragging a (random) local `*.razor` file into codespaces? If so; getting:
![image](https://user-images.githubusercontent.com/14852843/87338531-321f4680-c4fa-11ea-8020-e89f00e39d65.png)

**Comment by NTaylorMullen** [comment]
> Does this include dragging a (random) local `*.razor` file into codespaces? If so; getting:

It does not. I'd file a new issue.

**Comment by TanayParikh** [comment]
> It does not. I'd file a new issue.

https://github.com/dotnet/aspnetcore/issues/23910
