### ISSUE TITLE
Update interface for OnNavigate handler in router

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#23499]
Ref https://github.com/dotnet/aspnetcore/pull/23290#discussion_r447339556.

I don't want to block on this for p7, but we could conceive of making this behave like a filter:

```C#
Action<NavigationContext> OnNavigate;

NavigationContext
{
   string BaseRelativePath { get; }
   bool Cancel { get; }
}
```

This saves you the trouble of having to return a value if all you needed to was inspect the route. I'm not convinced it's necessary, just some musings

**Comment by mrpmorris** [comment]
Should that Cancel also have a set? Or better still, a Cancel method so nobody can set it back to false?

**Comment by captainsafia** [comment]
Closing this since that API has changed a little bit as part of #22382 

@mrpmorris The `Cancel` property is a little obsolete now following some changes made to the PR. The new API interface for OnNavigate takes a path and a cancellation token.
