### ISSUE TITLE
UseKestrel async port binding is not working consistently

### ISSUE THREAD

**Issue by krishkalai** [dotnet/aspnetcore#23500]
Application type: Web API running on Service Fabric cluster

While binding Https port 443 asynchronously through UseKestrel() method, the binding is not working consistently. This app is hosted in a Windows container, whenever the container instance refresh happens https port binding is not occurring consistently. We are not seeing any error messages logged.

`public` static IWebHost BuildWebHost(string[] args) =>

             WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .ConfigureServices(services =>
                {
                    services.AddSingleton<IKeyVaultHelper, KeyVaultHelper>();
                })            
                .UseKestrel(async options =>
                {
                    
                    options.AddServerHeader = false;

                    var keyVaultHelper = options.ApplicationServices.GetService<IKeyVaultHelper>();
                    var encodedSecret = await keyVaultHelper.GetSecret("ClusterCertificate");
                    var certificate = Helper.GetCertificatefromBase64Encoding(encodedSecret);
                    options.Listen(IPAddress.Any, Configs.GetDockerKestrelSSLPort(), listenOptions =>
                    {
                        listenOptions.UseHttps(new HttpsConnectionAdapterOptions
                        {
                            ServerCertificate = certificate,
                        });
                    });
                })
                .UseStartup<Startup>()
                .Build();`

### Configuration
* Which version of .NET is the code running on?
 .Net Core 2.1
* What OS and version, and what distro if applicable?
 Service Fabric Node: Windows Server 2016 (version 1607)
Container Image: mcr.microsoft.com/dotnet/core/aspnet:2.1-nanoserver-sac2016
 
### Other information
* Do you know of any workarounds?
However if we make it a synchronous call, the port binding is occurring consistently.

**Comment by Tratcher** [comment]
UseKestrel is not an async API, you're doing async void there and spawning a background thread. Remove the async keyword.

**Comment by krishkalai** [comment]
@Tratcher Thanks for the clarification, this helps.

**Comment by davidfowl** [comment]
You should do this before binding to kestrel.
