### ISSUE TITLE
SignalR Regression in JSON Serialisation  3.14 vs 5.0.0-preview6

### ISSUE THREAD

**Issue by Ninds** [dotnet/aspnetcore#23509]
An object being sent back from the server back to the JS client is deserialised without problem on 3.1.5. However when using 5.0.0-preview6 we have the following error :
```
  Uncaught TypeError: Cannot read property 'Key' of undefined
      at HubConnection.<anonymous>((index):12)
      at signalr.min.js:16
      at Array.forEach (<anonymous>)
      at HubConnection.invokeClientMethod(signalr.min.js:16)
      at HubConnection.processIncomingData(signalr.min.js:16)
      at WebSocketTransport.HubConnection.connection.onreceive(signalr.min.js:16)
      at WebSocket.webSocket.onmessage(signalr.min.js:16)
```
Reproducer can be found   [here](https://gist.github.com/Ninds/78809a85cb913e0fef1000e62e8b9c35)

However the following code behaves as it should 
```csharp
public static void Main(string[] args)
        {
            var myOb = new MyClass(new Klass() { message = "hello" });
            var jsonString = JsonSerializer.Serialize(myOb);
            Console.WriteLine(jsonString);

            //3.1 prints  {"kv":{"Key":0,"Value":null},"klass":{"message":"hello"}}
            //5.0 prints  {"kv":{"Key":0,"Value":null},"klass":{"message":"hello"}}
        }
```

Also tried using an own struct instead of KeyValuePair with @Drawaes , but same issue.

**Comment by BrennanConroy** [comment]
Thanks for reporting this. Looks like a recent regression in the previews where the Json library provided a new option "DefaultIgnoreCondition" and we set it to `JsonIgnoreCondition.WhenWritingDefault` when it should probably be `JsonIgnoreCondition.Never`.

You can work around the issue locally by setting the json options in startup:
```c#
services.AddSignalR()
    .AddJsonProtocol(o =>
    {
        o.PayloadSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.Never;
    });
```
