### ISSUE TITLE
Allow for a thread-safe dictionary in HttpContext.Items

### ISSUE THREAD

**Issue by snappyfoo** [dotnet/aspnetcore#23507]
### Is your feature request related to a problem? Please describe.
The default ItemsFeature uses an ItemsDictionary, which internally uses a Dictionary. I would like to be able to easily configure it to use a ConcurrentDictionary instead so I don't have to worry about thread-safety when accessing the Items cache.

- I can use some middleware to replace the IItemsFeature so it uses a ConcurrentDictionary, but will miss out on some of the useful features of ItemsDictionary, such as an index accessor that returns null for missing values.
- I could create my own version of ItemsDictionary, borrowing its features but internally using a ConcurrentDictionary, but then I may get out of step with with other useful features- I don't want to deviate too much from default ASP.NET Core implementations.

### Describe the solution you'd like
Possible solutions that come to my mind, but there could be many better solutions:

- Make ItemsDictionary public instead of internal then either:
-- The existing constructor overload that takes an IDictionary can be used to pass in a ConcurrentDictionary
-- Make the EnsureDictionary() method protected so that a class can extend ItemsDictionary and create a ConcurrentDictionary instead of a Dictionary

**Comment by Tratcher** [comment]
Triage: Won't fix.

The entire HttpContext is explicitly not thread-safe. Trying to make parts of it thread safe is likely to result in confusion and incorrect usage. For example, even if you make the Items collection thread safe, fetching the collection from HttpContext is still not thread safe.
