### ISSUE TITLE
Don't set StatusCode in WriteAsJsonAsync

### ISSUE THREAD

**Issue by ansarizafar** [dotnet/aspnetcore#23516]
[Route to code](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi7s8HJpqnqAhWFyYUKHT7pDgsQwqsBMAJ6BAgKEAQ&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dj-33Uz32hG0&usg=AOvVaw0Wj569N0mgRNvJu3jGU9Ml) is a great new addition to Asp.net core. New Apis like WriteAsJsonAsync() and ReadFromJsonAsync() are great for creating lightweight endpoints without using API controllers.

Like  API controllers we should also have Ok() and BadRequest() methods available on HttpContext.Response object for sending proper response.

I would also like to suggest that WriteAsJsonAsync() should allow setting HttpStatus code. Currently StatusCode is set to 200 by this method.

**Comment by halter73** [comment]
> Like API controllers we should also have Ok() and BadRequest() methods available on HttpContext.Response object for sending proper response.

If middleware does nothing, the server will already return a 200 response with an empty body.

Would `HttpContext.Response.Ok()` be any different than `HttpContext.Response.StatusCode = 200`? I think with the latter it's more obvious what's going on. Just from the name, I don't know if `Ok()` is supposed to flush headers, set Content-Length to 0 or anything like that.

> I would also like to suggest that WriteAsJsonAsync() should allow setting HttpStatus code. Currently StatusCode is set to 200 by this method.

Does setting the `StatusCode` before `WriteAsJsonAsync()` not work?

**Comment by Tratcher** [comment]
MVC has methods like Ok and BadRequest because many MVC Actions return an IActionResult so it needs placeholders for these common response types. That's not needed when you're working directly with the HttpResponse. You can set the StatusCode and headers, call  WriteAsJsonAsync, and be done.

**Comment by ansarizafar** [comment]
@halter73 @Tratcher I am trying to write my on extensions methods OK(), BadRequest() and GetParameters() on HttpContext.  Here is the code

```
public static class HttpContextExtensions
{
    public static async Task Ok(this HttpContext context, Object value)
    {
        var disposableValue = value as IDisposable;
        if (disposableValue != null)
        {
            context.Response.RegisterForDispose(disposableValue);
        }

        if (value != null)
        {
            await context.Response.WriteAsJsonAsync(value);
        }
        else
        {
            context.Response.StatusCode = StatusCodes.Status200OK;
            context.Response.Headers.Add("Content-Type", "application/json");
            await context.Response.WriteAsync("");
        }
        await context.Response.CompleteAsync();
        context.Abort();
    }
    public static async Task BadRequest(this HttpContext context, Object error = null)
    {
        var disposableValue = error as IDisposable;
        if (disposableValue != null)
        {
            context.Response.RegisterForDispose(disposableValue);
        }

        context.Response.Headers.Add("Content-Type", "application/json");
        context.Response.StatusCode = StatusCodes.Status400BadRequest;
        if (error != null)
        {
            await context.Response.WriteAsync(error.ToString());
        }
        else
        {
            await context.Response.WriteAsync("");
        }
        await context.Response.CompleteAsync();
    }
    public static async Task<T> GetParameters<T>(this HttpContext context)
    {
        try
        {
            T value = await context.Request.ReadFromJsonAsync<T>();
            return value;
        }
        catch
        {
            await context.BadRequest("Invalid Parameters");
            return default;
        }
    }
}

``` 
I am facing two issues, WriteAsJsonAsync or WriteAsync doesn't stop further processing like API controller Ok and BadRequest methods. I would like to send response and cancel request but I am not able to do it. The second issue is WriteAsync() overwrite statuscode to 200 so setting the StatusCode before WriteAsJsonAsync() doesn't work. 

I am also trying to write GetParameters extension method to read body as Json and validate the model by using something like https://fluentvalidation.net/ 

I am coming from Nodejs and I really like Route to code feature. Please help me to write these extension methods.

**Comment by Tratcher** [comment]
> I am facing two issues, WriteAsJsonAsync or WriteAsync doesn't stop further processing like API controller Ok and BadRequest methods.

WriteAsJsonAsync shouldn't be used in an API controller, an API controller already has APIs for doing this.

> I would like to send response and cancel request but I am not able to do it. 
>         await context.Response.CompleteAsync();
>         context.Abort();

I'm not sure what you hope to accomplish by this. This is more likely to fail both the request and response.

> The second issue is WriteAsync() overwrite statuscode to 200 so setting the StatusCode before WriteAsJsonAsync() doesn't work.

Response.WriteAsync does not change status codes.

WriteAsJsonAsync does overwrite the status code to 200. @JamesNK  it should not do that, let's get that removed.
https://github.com/dotnet/aspnetcore/blob/912ab2bcb3c6d331279ed97ba7859ff319d611e6/src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs#L153
https://github.com/dotnet/aspnetcore/blob/912ab2bcb3c6d331279ed97ba7859ff319d611e6/src/Http/Http.Extensions/src/HttpResponseJsonExtensions.cs#L80
