### ISSUE TITLE
Blazor Webassembly : How to protect/encrypt client side local storage data

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#23513]
What are the options to encrypt data that is stored in client side local/session store when using Blazor Webassembky ?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
