### ISSUE TITLE
Cross-file C# support

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23531]
This is a big rock big rock that encompasses the three cross-file interactions we want to support with C#:

- [x] [Rename](https://github.com/dotnet/aspnetcore/issues/21978)
- [x] [Go to definition](https://github.com/dotnet/aspnetcore/issues/21975)
- [x] [Go to implementation](https://github.com/dotnet/aspnetcore/issues/21976)

Total 1 day

**Comment by ajaybhargavb** [comment]
Go to definition and go to implementation is on track for preview 1 insertion

**Comment by NTaylorMullen** [comment]
@ajaybhargavb should this be thrown in the in progressed block column?

**Comment by ajaybhargavb** [comment]
Yeah. I'll also move it to preview2.

**Comment by NTaylorMullen** [comment]
Rename support got moved to 16.9-Preview1 to reduce risk.

**Comment by ajaybhargavb** [comment]
The work here is done. Leaving this open to validate whether rename works after the necessary insertion.

**Comment by NTaylorMullen** [comment]
@ajaybhargavb this good?

**Comment by ajaybhargavb** [comment]
Yes
