### ISSUE TITLE
EventCallback can't use object type  

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#23539]
I want create a component with `EventCallback`  function, this function must work with each type like **(int, short, int?, double, ....).**
But i can not use `object` or 'T' generic  data type  with `EventCallback`  

**Example** 

- With `object`
 `public EventCallback<object> BindingValueChanged { get; set; }`

**Error:**
> `Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1973	'EventCallbackFactory' has no applicable method named 'CreateBinder' but appears to have an extension method by that name. Extension methods cannot be dynamically dispatched. Consider casting the dynamic arguments or calling the extension method without the extension method syntax.	iServicePayroll	D:\Project	182	Active
`
- With T 
`public EventCallback<T> BindingValueChanged { get; set; }`

### **Full Example with special data type with child component**

```
<select class="form-control" @bind="BindingValue">
    <option value="">-- selected --</option>
    <option value="1">Option 1</option>
    <option value="2">Option 2</option>
    <option value="3">Option 3</option>
</select>

@code {

    private int _value;

    [Parameter]
    public int BindingValue
    {
        get => _value;
        set
        {
            if (_value == value) return;
            _value = value;
            BindingValueChanged.InvokeAsync(value);
        }
    }

    [Parameter]
    public EventCallback<int> BindingValueChanged { get; set; }

}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
