### ISSUE TITLE
On-by-default Razor formatting

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23530]
- [x] Add support for C# [OnTypeFormatting](https://github.com/dotnet/aspnetcore/issues/23419) - 3 days
  - [x] `;` formatting
  - [x] `}` formatting
  - [x] `\n` formatting (~Blocked https://github.com/dotnet/aspnetcore/issues/23753~)
- [x] HTML formatting (https://github.com/dotnet/aspnetcore-tooling/pull/2445)
- [x] C# formatting (https://github.com/dotnet/aspnetcore-tooling/pull/2445)
- [x] Mixed formatting (https://github.com/dotnet/aspnetcore-tooling/pull/2445 and https://github.com/dotnet/aspnetcore-tooling/pull/2526)
- [x] Advanced mixed formatting (format on type and full formatting) (https://github.com/dotnet/aspnetcore-tooling/pull/2585)
- [x] Razor specific formatting (https://github.com/dotnet/aspnetcore/issues/25475)
- [ ] Respect client settings
  - [x] HTML
  - [ ] C#

**Comment by NTaylorMullen** [comment]
Thoughts on what 16.8-Preivew3 would include:

- Don't special case @code for pure C#
- HTML / Razor formatting
- Test infrastructure update for formatting.

**Comment by ajaybhargavb** [comment]
Tracking a list of known issues here, https://github.com/dotnet/aspnetcore/issues/26527
