### ISSUE TITLE
Support Better Ways Of Overriding OAuthChallengeProperties (specifically for GoogleChallengeProperties)

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/aspnetcore#23554]
### Is your feature request related to a problem? Please describe.
Trying to change `GoogleChallengeProperties.Prompt` to `select_account` is needlessly cumbersome/violates strongly typed items.

This can kind of be done using unique challenge endpoints per provider, but that breaks being able to use a single challenge endpoint and let each provider self-configure.

### Describe the solution you'd like
GoogleChallengeProperties should be some sort of configurable, either at the `AddGoogle` level or elsewhere.

Current solution looks like:
```csharp
var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider,
	$"/api/v0/authentication/provider/callback?returnUrl={returnUrl}");
properties.Parameters.Add("prompt", "select_account");
return new ChallengeResult(provider, properties);
```

Which seems far from desirable (does this to all providers).

We _may_ be able to do something like this (haven't tried):

```csharp
.AddGoogle(options =>
{
	/* snip */
	options.Events.OnRedirectToAuthorizationEndpoint = context => {
		context.Properties.Parameters.Add("prompt", "select_account");
		return Task.CompletedTask;
	};
})
```

But it's still one of those "we're not taking advantage of any platform-specific strongly typed configuration options.

If I'm missing something, documentation on this would be a huge plus, nothing I find on the docs give any hint on how to do this, there are tests that verify that it can be done on a per-challenge endpoint basis but that's a bit rough.

**Comment by blowdart** [comment]
We can't do strongly typed, because challenge is shared amongst providers, and so we'd lose that.

Closing as by design.

**Comment by StrangeWill** [comment]
Isn't it eventually called via `GoogleHandler` via `ChallengeAsync` -> `HandleChallengeAsync` -> `BuildChallengeUrl`? (I'm pretty unfamiliar with this and am just rolling through Github which is a bit clunky to try to get the big picture).

We could just use `GoogleChallengeProperties` if it was injected into the `GoogleHandler` class (as an `IOptions<>`) instead of a static class, right? Shoot I'd even be find being able to set this in `AddGoogle`.

Of course ideally, this would be the same for all OAuth providers, where their challenge properties were exposed/configurable.
