### ISSUE TITLE
Some German Capital letters are not counted as Capital

### ISSUE THREAD

**Issue by spoko** [dotnet/aspnetcore#23562]
### Describe the bug
If a user is using German (and Cyrillic, probably others too) keyboard for example, and enters a Capital letter for a password the validation 'o.Password.RequireUppercase = true;' does not pass.

### To Reproduce
1. Try to set a password with just one capital letter of the following list (some of the German ones only):
Ö, Ä, Ü

### Exceptions (if any)
"PasswordRequiresUpper"
"Passwords must have at least one uppercase ('A'-'Z')."

### Further technical details
- .net core 3.1
- Тhe output:
.NET Core SDK (reflecting any global.json):
Version: 3.1.100
Commit: cd82f021f4

Runtime Environment:
OS Name: Windows
OS Version: 10.0.18362
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
Version: 3.1.0
Commit: 65f04fb6db

.NET Core SDKs installed:
1.1.10 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.301 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.2.109 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE VS 2019

**Comment by Pilchie** [comment]
Hi - can you let us know what type of project you are using when this happens?

**Comment by spoko** [comment]
It`s a web app project

**Comment by ufcpp** [comment]
by design?
https://source.dot.net/#Microsoft.Extensions.Identity.Core/PasswordOptions.cs,36

**Comment by Pilchie** [comment]
@blowdart @HaoK any ideas?

**Comment by blowdart** [comment]
Oh nooooo

https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/PasswordValidator.cs#L108

@HaoK can we change this to use [IsUpper](https://docs.microsoft.com/en-us/dotnet/api/system.char.isupper?view=netcore-3.1) or IsLower?

(Unless someone would like to give us a PR, it's a nice first issue)

**Comment by Youssef1313** [comment]
I've opened a PR for this. But please note that this might be a breaking change.

**Comment by GrabYourPitchforks** [comment]
It's definitely a breaking change. The APIs are even publicly documented as concerning themselves only with ASCII, not with arbitrary Unicode characters. If the team decides to accept a change here it should be documented.

A nit: prefer to use `Rune.IsUpper` instead of `char.ToUpper`, as it's more correct. Not that it's all that common to use supplementary characters in passwords anyway, but if we're going to check this, may as well do it right. :)

Also, the team should reconsider whether these methods should be virtual at all. A method documented as "returns true if the input character is uppercase ASCII" has only one correct implementation. There's no need for an override.

**Comment by Youssef1313** [comment]
@GrabYourPitchforks I've removed "virtual" from my PR. That's a breaking change too, but hopefully no one will be overriding these methods in a real code.

Regarding the Rune, I'm not very familiar with them, a quick look at docs shows there's an explicit conversion from char to Rune, should I cast the char to Rune and pass the result to Rune.IsUpper and Rune.IsLower? or there's another approach?

**Comment by GrabYourPitchforks** [comment]
@Youssef1313 The conversion from `char` to `Rune` can fail at runtime. The easiest way to enumerate `Rune`s from a string is via `EnumerateRunes`, as shown below.

```cs
foreach (Rune r in theString.EnumerateRunes())
{
    // do something with 'r'
}
```

Removing _virtual_ from these methods, just like changing the behavioral contract of these methods, is a breaking change. The aspnet team can give guidance as to what types of breaking changes are acceptable for their scenarios.

If we were doing this within the runtime or BCL, we would probably not change the old `IsUpper` / `IsLower` / `IsAlphaNumeric` APIs. Instead, we'd mark them `[Obsolete]` and stop calling into them, but preserve their original behavior. The change to the validation logic would be contained entirely within the `ValidateAsync` method. This isn't to say that you must follow this course of action, just that it is _one_ possible course of action depending on what level of breaking change the aspnet team deems appropriate.

**Comment by GrabYourPitchforks** [comment]
Also consider that if you're trying to make a system that supports multiple languages throughout the world, some languages don't even have a concept of uppercase or lowercase characters. Any discussion regarding making the password validator more amenable to non-ASCII characters has to include these considerations.

**Comment by Youssef1313** [comment]
@GrabYourPitchforks Great. I'll wait for the team here to decide whether they accept the breaking change(s) introduced or not. Given that a very quick search on GitHub shows [a usage](https://github.com/delta-it/Coco.Web/blob/786cbba181ea7b249fb5dbe58b64ec282d2b23e8/Source/Coco.Server/Coco.Api.Framework/Security/CustomPasswordValidator.cs) where the PasswordValidator is inherited and the virtual methods are overriden with the same base implementation.

**Comment by blowdart** [comment]
Oof, ok this is horribly broken and may be widely breaking if we attempt to change it (as is all our localization in general here).

@Youssef1313 you can replace the validator yourself, via your own implementation and DI, and that's why you're going to have to solve it for yourself.
