### ISSUE TITLE
[Helix] Need to stop permanently modifying path on windows

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#23575]
Related to https://github.com/dotnet/core-eng/issues/10185

We made the paths get too long so dotnet-install stopped working on machines that don't get reimaged frequently, need to fixup runtests.cmd to stop permanently modifying the path

@pranavkm @MattGal

**Comment by HaoK** [comment]
Expected fix for this is to just switch to build in helix sdk support

**Comment by MattGal** [comment]
Is this work done?

**Comment by HaoK** [comment]
Should be fixed by https://github.com/dotnet/aspnetcore/pull/24968 this time
