### ISSUE TITLE
AzureAdB2C Password Reset Flow not working

### ISSUE THREAD

**Issue by Krangth** [dotnet/aspnetcore#23580]
### Describe the bug
The password reset button on the signup/signin flow produces an error in the application instead of forwarding to the password reset.

I tried this solution https://stackoverflow.com/a/41798673/2565663
The answer with 30+ upvotes, but it doesn't work because the challenge is sent to the signup/signin policy even though a different policy is specified.

```
public IActionResult PasswordReset(string returnUrl) 
{
    var properties = new AuthenticationProperties { RedirectUri = returnUrl};
    properties.Items[AzureADB2CDefaults.PolicyKey] = "B2C_1_Password_Reset"; 
    return Challenge(properties, AzureADB2CDefaults.AuthenticationScheme); 
}
```

### Further technical details
- ASP.NET Core version: 3.1

**Comment by blowdart** [comment]
@jmprieur any idea?

**Comment by Krangth** [comment]
After some messing around, things are working as expected. The password reset works by itself without any work around AND any AzureADB2CDefaults.PolicyKey that I set are not overridden. 

The culprit appears to be this code:
```
services.Configure<OpenIdConnectOptions>(AzureADB2CDefaults.OpenIdScheme, options =>
{
    options.Events = new OpenIdConnectEvents
    {
```

If I set options.Events then things start behaving weirdly. I only deleted that assignment statement.
