### ISSUE TITLE
Typo in AuthorizationMessageHandler.ConfigureHandler(...) summary

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23588]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1093578/typo-in-authorizationmessagehandlerconfigurehandle.html)._

---
The summary of AuthorizationMessageHandler.ConfigureHandler(...) reads

...
        // Summary:
        //     Configures this handler to authorize outbound HTTP requests using an access token.
        //     The access token is only attached if only attached if at least one of authorizedUrls
        //     is a base of System.Net.Http.HttpRequestMessage.RequestUri.
        ...

"[...] The access token is **only attached if only attached if** [...]"

---
#### siim.alas on 6/27/2020, 07:43 AM: 

<p>I am sorry, this is under the wrong category.</p>

#### Visual Studio Feedback System on 6/28/2020, 02:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 6/28/2020, 11:02 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/22371/files
