### ISSUE TITLE
login.microsoftonline.com CORS issue 

### ISSUE THREAD

**Issue by dochoss** [dotnet/aspnetcore#23589]
Hi ASPNetCore team,

I'm going crazy trying to figure this issue out and I'm hoping someone can help me.

I'm getting a CORS error at login.microsoftonline.com when using ASP.Net Core web API authentication/authorization.  I've followed examples and walkthroughs, but I'm still missing something.  When I load up the default "new project" sample in Visual Studio 2019 (New Project -> ASP.Net Core -> MVC with authorization) everything works fine.  When I use the exact same setup, same packages, almost the same Startup configuration, I get CORS error.  I'm not using MVC for my project, but rather static files in wwwroot with web API controllers.  If I have no `[Authorize]` attribute on my controller, everything works fine.  The AzureAD settings block in appsettings.json is identical, literally copy/pasted.  

I noticed that the default app doesn't make a request to login.microsoftonline.com at all, but my project does.  That request fails with the CORS error.  I'm not sure why.  `AllowedHosts` in appsettings is set to * on both projects.

To complicate the situation, if I manually enter the address for an API endpoint (https://myapp.azurewebsites.net/api/myendpoint), then the login request is successful. If I then open another browser tab and go to the root address, the cookie is already set and API data is shown successfully. So something is preventing the index.html page from getting to login.microsoftonline.com. My frontend is the static files generated by a VueJS project with `npm run build`, if that matters.

Could someone please take a quick look and help me figure out what I'm missing?

Default project (no modifications):
```
public void ConfigureServices (IServiceCollection services)
        {
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });
            services.AddRazorPages();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure (IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
        }
```

My project 
```
public void ConfigureServices (IServiceCollection services)
        {
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.AddControllers(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });

            // EF Core contexts here //
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure (IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseHttpsRedirection();

            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

**Comment by blowdart** [comment]
If you're using static files, there's going to be nothing to trigger the auth flow. How are you expecting the token to be acquired here? Via a redirect from authorize? Or do you want something more spa related?

**Comment by dochoss** [comment]
To be quite frank, I'm not entirely sure.  Here's what I'd like to have happen... User logs into the application via Azure Web App Easy Auth (now called Authorization and Authentication...I think?).  After that, I utilize the logged in user's GUID from Azure AD to handle some simple auth things in the app, like hiding sections of the UI based on the user's permissions.  I also want to be able to query Graph to get the user's photo and eventually some other information.  I know I can get an access token from the `/.auth/me` endpoint, but I'm not quite sure where to go from there.

Also, is there any way to test the `/.auth/me` endpoint functionality on localhost?

**Comment by blowdart** [comment]
EasyAuth is rather out of our hands I'm afraid, Azure Web Apps owns that, and it requires some middleware from them. It honestly sounds like you'd be better off using the newer Azure AD pieces, rather than easy auth. Take a look at https://github.com/AzureAD/microsoft-identity-web and see if it fits your needs better.

**Comment by dochoss** [comment]
Thanks, I appreciate the input.  I have tried this example and found it to have similar issues, but again, I think it may be me messing something up (well, obviously...).  Taking a look at this [Startup.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/1-1-MyOrg/Startup.cs), this seems to rely on Razor Pages, which I'm not using.  I hate to sound so dense, but could you help me out with adapting it to my situation?  I've copy/pasted all the relevant info from the sample above but I'm still getting CORS error from login.microsoftonline.com.  The sanitized error is below.

`Access to XMLHttpRequest at 'https://login.microsoftonline.com/<my tenant id>/oauth2/v2.0/authorize?client_id=<my client id>&redirect_uri=https%3A%2F%2Flocalhost%3A4001%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=<nonce token>&client_info=1&state=<long id>&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0' (redirected from 'https://localhost:4001/api/holds') from origin 'https://localhost:4001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Startup.cs selection
```
        public void ConfigureServices (IServiceCollection services)
        {
            #region Azure OIDC Sample

            // from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/1-WebApp-OIDC/1-1-MyOrg/Startup.cs
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
                // Handling SameSite cookie according to https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
                options.HandleSameSiteCookieCompatibility();
            });

            // Sign-in users with the Microsoft identity platform
            services.AddSignIn(Configuration);

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();

            #endregion

            // EF Core contexts are here //
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure (IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseHttpsRedirection();

            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseCookiePolicy();
            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
```

**Comment by blowdart** [comment]
You wouldn't be attempting to hit login via an XML request, but instead via a redirect.

I'd suggest asking the AAD folks what your best approach is here. They have samples over in https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code and https://github.com/Azure-Samples

**Comment by miqm** [comment]
in AppService set Action to take when request is not authenticated to Allow Anonymous. Unfortunately, you need to implement redirection to auth service (login.microsoftonline) on yourself. 

I struggle with this for some time and it appears, that EasyAuth is only meant to work with MVC, not webapis.

**Comment by miqm** [comment]
Regarding testing locally EasyAuth - check out this project - https://github.com/kirkone/KK.AspNetCore.EasyAuthAuthentication/

**Comment by blowdart** [comment]
Closing this as stale.
