### ISSUE TITLE
Minimize Newtonsoft.Json memory spikes during deserialization

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23597]
It seems that during deserialization the entire JSON graph is rooted. Since VS is a 32bit process large JSON responses blow up the memory potentially OOMing it.

**Comment by davidfowl** [comment]
Do you have a CPU and memory profile?

**Comment by NTaylorMullen** [comment]
> Do you have a CPU and memory profile?

Not CPU, but lots of memory dumps 😄

**Comment by NTaylorMullen** [comment]
This causes the spike:
![image](https://user-images.githubusercontent.com/2008729/86406184-82c7b180-bc67-11ea-9be6-a05a91b86bcb.png)
