### ISSUE TITLE
Components are rendered as simple html tags

### ISSUE THREAD

**Issue by Lionberg** [dotnet/aspnetcore#23609]
Hi.

Blazor does not render components if they have the same name, but located in different folders.

Structure:
MyApp/Profile/**role1**/ProfileControl.razor
MyApp/Profile/**role2**/ProfileControl.razor
MyApp/Profile/**role3**/ProfileControl.razor

And if in other component you use:
`<MyApp.Profile.role1.ProfileControl/>
`
then blazor will not render it. It will just use it as html tag.

I have tried to add _usings_ to _Imports file, but with no luck.

Bug workaround: You must have unique names of components.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
