### ISSUE TITLE
Blazor: EventCallback improvements

### ISSUE THREAD

**Issue by kristof12345** [dotnet/aspnetcore#23603]
Hi!

### 1. EventCallback multiple type arguments
It's often required to pass multiple parameters in an EventCallback. Now it can be done with a pair like this:
```
[Parameter]
public EventCallback<(string, int)> OnFinish { get; set; }
```
I'd be much better (especially in the parent component) to just use EventCallback<string, int> (multiple type arguments).

### 2. EventCallback without type arguments
If you don't need parameters you can write an EventCallback without type arguments, but when calling InvokeAsync() one parameter is required.
```
[Parameter]
public EventCallback OnClear { get; set; }
```
So instead of InvokeAsync(null) simply InvokeAsync() would be better.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will be open to the second proposal. Feel free to send us a PR to add the `InvokeAsync()` overload.

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by zbecknell** [comment]
Heck, I'll grab this one to add the `InvokeAsync()` overload.

**Comment by zbecknell** [comment]
Have a PR for the `InvokeAsync()` overload.  Now to wade into potentially adding multiple type arguments...

**Comment by mkArtakMSFT** [comment]
We've done the 2'nd suggestion above.
