### ISSUE TITLE
WebAssembly.Authentication - Not possible to define "Audience"

### ISSUE THREAD

**Issue by StefH** [dotnet/aspnetcore#23606]
### Describe the bug
The `OidcProviderOptions` does not provide an property for the "Audience".

### To Reproduce
When using [Auth0](https://auth0.com/) in a Blazor WebAssembly, this fails (because of invalid/short AccessToken ), this is because I cannot provide the "Audience".

The URL is like (audience is not present):
> https://stef-heyenrath.eu.auth0.com/authorize?client_id={CLIENT_ID}&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fauthentication%2Flogin-callback&response_type=token%20id_token&scope=openid%20profile&state=1c2b2f273d8b47f2ac662a8b099168a2&nonce=c9e47c1efd434d12a021700f00626ded&prompt=none

Is this _as designed_ or _bug_ or _missing functionality_?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This behavior is by-design. We don't provide to use any custom protocol extensions.
If you believe that this is important gap please point us to the Auth0 documentation, where that is stated.

**Comment by StefH** [comment]
@mkArtakMSFT 
Thanks for your reply.
For example see these links:
- https://community.auth0.com/t/understanding-how-the-audience-concept-actually-works/34011
- https://auth0.com/docs/tokens/guides/get-access-tokens

I think it would be useful if there was a way to extend the URL which specific protocol extensions.

**Comment by StefH** [comment]
@mkArtakMSFT 
I found out that this is possible by providing `extraQueryParams` (which is a dictionary) to the oidc-client.js.

However the `OidcProviderOptions` does not support extraQueryParams, so I did create my own implementation, see:
https://github.com/StefH/Blazor.WebAssembly.Authentication.Auth0/blob/master/src/Blazor.WebAssembly.Authentication.Auth0
