### ISSUE TITLE
Custom parameter types are failing without details

### ISSUE THREAD

**Issue by Thorium** [dotnet/aspnetcore#23612]
I have a hub having a method called "SearchCompanies" taking a single parameter.
If I modify this parameter to be type string, and call a server like this:
```javascript
connection.invoke("SearchCompanies", "Hello World").then(...
```
...it works. But if I instead would like to define a parameter on server side, and then send an object:
```javascript
const searchObject = {
    FoundedAfter : new Date(),
    CompanyName : ""
};
connection.invoke("SearchCompanies", searchObject).then(..._
```
that just fails:
> Response: Error: Failed to invoke 'SearchCompanies' due to an error on the server. InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.

All the properties in the server side object are correct, and I tried many combinations of case-sensitivities. The error message doesn't describe anything what is wrong. Not any kind of helps in the SignalR documentation how this works. 

The same object does pass perfectly between client and server on did work on full .NET Framework AspNet SignalR.

**Comment by Thorium** [comment]
Maybe consider adding the Newtonsoft.Json reference to this AspNetCore also, because it did so much better job in JSON serialization of AspNet SignalR than this current system...

**Comment by BrennanConroy** [comment]
You can switch to using Newtonsoft.Json by following the docs: https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-3.1&tabs=dotnet#switch-to-newtonsoftjson-1

**Comment by Thorium** [comment]
I can't get it work. It doesn't describe how to do AddNewtonsoftJsonProtocol in TypeScript/Javascript client.

**Comment by Thorium** [comment]
That helps, thanks.
Hopefully the default serialisation picks these features some day, or the default is moved to NewtonsoftJson.
