### ISSUE TITLE
Restricting what operations can be done on what path when using `JsonPatchDocument<T>`

### ISSUE THREAD

**Issue by EricStG** [dotnet/aspnetcore#23619]
### Is your feature request related to a problem? Please describe.
I am trying to use `JsonPatchDocument<T>` with models from Entity Framework, but it enables changes to all properties of the entity, including navigation properties, and we need to restrict what fields can be modified, and what operations can be applied.

### Describe the solution you'd like
I could use either of:
- Some way to annotate the models to specify what operations are allowed where
- The ability to apply the patch against a different type (ex: using a view model for the Patch that is a subset of the entity's properties) but validate the operations against both source and target types

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do in the near future.
