### ISSUE TITLE
Resolving DbContext on a Test project returns a DbContext with a wrong connectionString

### ISSUE THREAD

**Issue by zinov** [dotnet/aspnetcore#23613]
I have a test project that uses `IClassFixture `of a generic factory class. For example

```
public class WeatherForecastAcceptanceTest
    : IClassFixture<WebApi1ApplicationFactory<Startup>>, IDisposable
{
    .....
}
```

after the Startup class executes `ConfigureServices `and Configure methods it executes the `ConfigureWebHost `where I remove the original `DbContext `and add a new one that runs in memory.

```
public class WebApi1ApplicationFactory<TStartup>
    : WebApplicationFactory<TStartup> where TStartup : class
{
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureServices(services =>
        {
            //remove the injected DbContext and inject in-memory
            services.RemoveAll(typeof(DbContext));
            var connection = new SqliteConnection("Data Source=:memory:");
            services.AddDbContext<WebApi1DbContext>(
                options => options.UseSqlite(connection));

            var sp = services.BuildServiceProvider();
            using (var scope = sp.CreateScope())
            {
                //ERROR HERE WITH THE RESOLVED DbContext
                using (var dbContext = scope.ServiceProvider
                    .GetRequiredService<WebApi1DbContext>())
                {
                    try
                    {
                        dbContext.Database.OpenConnection();
                        dbContext.Database.EnsureCreated();
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }
            }
        });
    }
}
```

The `DbContext `that I am resolving has the original connectionString instead of InMemory, as a result, all my testings are inserting content on my original database.

Here is how I am using my WebApplicationFactory

```
public class WeatherForecastAcceptanceTest : IClassFixture<WebApi1ApplicationFactory<Startup>>, IDisposable
    {
        private WebApi1ApplicationFactory<Startup> _factory;
        private HttpClient _client;

        public WeatherForecastAcceptanceTest(WebApi1ApplicationFactory<Startup> factory)
        {
            _factory = factory;
            _client = factory.CreateClient();
        }

        [Fact]
        public async Task GetAll_ReturnsElements_WhenPostWasExecutedSucessfully()
        {
            // Arrange
        var weatherForecastForCreationDto = CreateRandomWeatherForecastForCreationDto();

        var content = new JsonContent(weatherForecastForCreationDto);
        //setting the content-type header
        content.Headers.ContentType = new MediaTypeWithQualityHeaderValue(HttpMediaTypes.WeatherForecastType1);

        //create an object
        using (var client = _factory.CreateClient())
        {
            //act
            var responsePost = await _client.PostAsync(ApiRoutes.WeatherForecast.CreateWeatherForecast, content);
            //assert
            responsePost.StatusCode.Should().Be(StatusCodes.Status201Created);
        }

        //check that the object was inserted
        using (var client = _factory.CreateClient())
        {
            _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(HttpMediaTypes.WeatherForecastType1));
            // Act
            var response = await _client.GetAsync(ApiRoutes.WeatherForecast.GetWeatherForecast);

            // Assert
            response.StatusCode.Should().Be(StatusCodes.Status200OK);
            var returnedGet = await response.Content.ReadAsAsync<WeatherForecastDto[]>();
            returnedGet.Should().Contain(dto => dto.Summary == weatherForecastForCreationDto.Summary);
        }
        }

        public void Dispose()
        {
            _client?.Dispose();
            _factory?.Dispose();
        }
    }
```

How can I resolve the in-memory `DbContext` that was injected?

**Comment by Bartmax** [comment]
You are removing the dbcontext but not all it's dependencies.
Normally when switching environments you want to add only the services required for that environment using the mechanism of your choice and not removing anything.

something like:
```c#
if (Enviroment.IsTesting()) {
    // add in memory dbcontext
} else {
    // add sql dbcontext
}
```

**Comment by zinov** [comment]
but I need to code that one the Startup of my application. The cons here are that my WebApi needs to be aware of a Testing project that is going to use In-Memory database in order to do the test. It is not following the single-responsability principle.
How can I remove all the dependencies from my testing project? Should I not expect to remove all the dependencies injected by `AddDbContext `when I call `services.Remove`?

**Comment by zinov** [comment]
> You are removing the dbcontext but not all it's dependencies.
> Normally when switching environments you want to add only the services required for that environment using the mechanism of your choice and not removing anything.
> 
> something like:
> 
> ```cs
> if (Enviroment.IsTesting()) {
>     // add in memory dbcontext

but I need to code that one the Startup of my application. The cons here are that my WebApi needs to be aware of a Testing project that is going to use In-Memory database in order to do the test. It is not following the single-responsability principle. What you call Testing here represents my UnitTest project?

> } else {
>     // add sql dbcontext
> }
> ```



> You are removing the dbcontext but not all it's dependencies.
> Normally when switching environments you want to add only the services required for that environment using the mechanism of your choice and not removing anything.
> 
> something like:
> 
> ```cs
> if (Enviroment.IsTesting()) {
>     // add in memory dbcontext
> } else {
>     // add sql dbcontext
> }
> ```

**Comment by Bartmax** [comment]
I'm suggesting you to change the environment for the tests.

**Comment by zinov** [comment]
In this case the application code needs to know then that it will have a test. Seems that is losing the single responsibility principle.
Why it can't be done properly from the test project? I mean, remove only the DbContext with all its dependencies. In the same way you have an AddDbContext I would suggest to create a RemoveDbContext embedded with the framework.
Every class injected should have the same mechanism to remove it, in that way you can mock any layer from your mock. That doesn't happens with the DbContext
