### ISSUE TITLE
[Kestrel] Certificate chains support

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#23623]
Right now Kestrel supports loading certificates from PFX files and PEM files, but it only loads one certificate.
* That forces the certificate chains to be resolved within the SSL stream which require going to the network to resolve the chain.
* There are new APIs on SslStream to provide the chain as well as the certificate to use that avoid having to fetch the chain from the network.
* We want to load entire certificate chains from PFX and PEM certificate files to pass them directly to SslStream and avoid having to resolve the chain.

**Comment by Pilchie** [comment]
Is this the same thing as #21513?

**Comment by javiercn** [comment]
@Pilchie I think so, or it overlaps a bit. David is taking care of it.

**Comment by Pilchie** [comment]
Okay, moving to 5.0.0-rc2 then.

**Comment by davidfowl** [comment]
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/23623
