### ISSUE TITLE
Safe storage of app secrets for Blazor Webassembly app

### ISSUE THREAD

**Issue by jesusarockias** [dotnet/aspnetcore#23620]
I am searching on the way for safe storage of app secrets in blazor webassembly application. We can find details for Server Side application as in below MSDN documentation.

https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows

How can we use these kind of secrets for Blazor WebAssembly application which completely runs in client browser?

My basic scenario is, need to keep the passwords, product key (licensing key) information out of application code. For example, we load license inside the static main method of Program.cs.

![image](https://user-images.githubusercontent.com/41784897/86389107-7701dc80-bcb3-11ea-9335-75a23a0b6bbf.png)

I have searched in documentation of blazor and not able to find any details for this. Please help me to find the recommended way resolving this in Blazor webassembly.

(for server-side, we have variety of option but for client-side what might be the recommended way)

**Comment by blowdart** [comment]
There is nothing we can recommend. Everything client side is readable. I'd suggest talking to your library provider and see what they say.

**Comment by mrpmorris** [comment]
Isn't this supposed to docs the problem? I have no idea how it could possibly work, but MS seems to think it will

https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1#protected-browser-storage-experimental-package

**Comment by javiercn** [comment]
@jesusarockias thanks for contacting us.

You can't store secrets safely within browser applications. If the library that you are using requires a license in code, I would suggest you keep that functionality in the server and consume it through API calls by authorized users from the client.

The moment you download the license to the client, its accessible for anyone to grab and do whatever they want with it.

@mrpmorris that's for server-side Blazor only.

**Comment by jesusarockias** [comment]
@javiercn Can we store as a text file or in .csproj file and access it using Reflection?

**Comment by javiercn** [comment]
@jesusarockias No. The dlls are downloaded to the browser, anything that gets downloaded to the browser can be opened and retrieved.

As @blowdart mentions, there is no safe way to store secrets on web applications since you don't have control over the hardware.
