### ISSUE TITLE
Blazor WebAssembly Msal breaks when attempting AD B2C Password Reset user flow

### ISSUE THREAD

**Issue by pheuter** [dotnet/aspnetcore#23638]
### Describe the bug
Blazor WebAssembly authentication (`Microsoft.Authentication.WebAssembly.Msal`) relies on a `state` query param passed to B2C [user flows](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview) to keep track of the authentication process and successfully log users in when they're redirected back into the app. Because Msal currently [does not support](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1#custom-user-flows) B2C user flows as first-class entities (at least for flows other than sign in, like password reset), we rely on manually building a user flow url (see example below), part of which is the `state` query param. If this param is completely left out, the Msal library will throw an unhandled error complaining that no state param was found.

This is an issue because we want to be able to handle the Password Reset user flow, which [by design](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview#linking-user-flows) throws an error back to the initiating app (`AADB2C90118`) and it becomes the app's responsibility to trigger the password reset as a separate user flow. As mentioned above, this currently happens by manually building the flow url, which brings us back to the original issue of populating the `state` query param.

### To Reproduce
Modify **Pages/Authentication.razor** to look similar to what I have below, which is designed to handle the AD B2C `AADB2C90118` error for linking sign in user flow with the password reset user flow:

```razor
@page "/authentication/{action}"

@using Microsoft.Extensions.Configuration;
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication

@inject NavigationManager NavManager
@inject IConfiguration Configuration

<RemoteAuthenticatorView Action="@Action" />

@code {
    [Parameter] public string Action { get; set; }

    protected override void OnAfterRender(bool firstRender)
    {
        if (Action == "login-failed")
        {
            var uri = NavManager.ToAbsoluteUri(NavManager.Uri);

            if (QueryHelpers.ParseQuery(uri.Query).TryGetValue("message", out var _loginError))
            {
                // Indicates that user attempted to initiate password reset flow
                if (_loginError.Single().Contains("AADB2C90118"))
                {
                    var resetPasswordFlow = Configuration["AzureAdB2C:ResetPasswordUserFlow"];
                    var clientId = Configuration["AzureAdB2C:ClientId"];
                    var redirectUri = $"{NavManager.BaseUri}authentication/login-callback";

                    var userFlowBuilder = $@"https://ourtenant.b2clogin.com/ourtenant.onmicrosoft.com/oauth2/v2.0/authorize
                        ?p={resetPasswordFlow}
                        &client_id={clientId}
                        &redirect_uri={redirectUri}
                        &nonce=defaultNonce
                        &scope=openid
                        &response_type=id_token
                        &prompt=login";

                    var userFlowUrl = String.Concat(userFlowBuilder.Where(c => !Char.IsWhiteSpace(c)));
                    NavManager.NavigateTo(userFlowUrl, forceLoad: true);
                }
            }
        }
    }
}
```

### Exceptions (if any)
```
blazor.webassembly.js?v=6:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unexpected error in authentication.: Hash does not contain state.
      AuthError: Unexpected error in authentication.: Hash does not contain state.
          at new t (http://localhost:5000/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js?v=2:16:24631)
```

### Further technical details
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@pheuter thanks for contacting us.

This functionality is not supported by msal.js so we don't support it either. If you need this functionality you'll have to provide your own provider implementation. You can see how the msal provider is implemented in this repo as a starting point.

**Comment by pheuter** [comment]
@javiercn Thanks for the response, I'll take a look at what a custom provider implementation might look like. To make sure I'm on the same page, are you referring to [AuthenticationService.ts](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts), or are there .net files you have in mind as well?

**Comment by javiercn** [comment]
@pheuter Yes.

**Comment by pheuter** [comment]
I'm noticing two different versions of that service:
- [Authentication.Msal](https://github.com/dotnet/aspnetcore/tree/master/src/Components/WebAssembly/Authentication.Msal/src/Interop) - relies on `msal`
- [WebAssembly.Authentication](https://github.com/dotnet/aspnetcore/tree/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop) - relies on `oidc-client`

Slightly confused as to which one is relevant, or how they potentially work together. Which one ends up getting exposed to Blazor WebAssembly app's `window.AuthenticationService`?

In my code, I have `<script src="_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js"></script>`, which suggests it's the Msal one, but then the oidc one is in the same package that exposes `RemoteAuthenticatorView.cs`.

**Comment by javiercn** [comment]
@pheuter Authentication.Msal contains the msal specific implementation for AAD and AAD B2C, and uses WebAssembly.Authentication which implements the fundamental authentication primitives in Blazor

**Comment by pheuter** [comment]
@javiercn I just noticed that there was a [PR merged](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/pull/60) that appears to address the issue of triggering a password reset redirect flow. It appears to suggest that there is now a fix for this in Msal.js v1.3.x, and Authentication.Msal is currently [lagging behind](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Interop/package.json#L16).

**Comment by javiercn** [comment]
@pheuter thanks for letting us know. We will update to the latest msal.js version on the next major release.

**Comment by pheuter** [comment]
@javiercn That's great news :) Looking at the PR, it may require a little code change other than bumping the version number. [This error check and loginRedirect call](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/pull/60/files#diff-c14be4e9ed0d4f03f27b10bf659d51c3R17-R24) will need to have some equivalent in the [AuthenticationService](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts#L281-L285), and [OidcProviderOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs) will probably need to support providing a separate Forgot Password authority like the PR does [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/pull/60/files#diff-11870008c19f5f706567b406f66c024cR15).

**Comment by pheuter** [comment]
Correction, I linked to OidcProviderOptions above, but mean to link to [MsalAuthenticationOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Models/MsalAuthenticationOptions.cs)

**Comment by pheuter** [comment]
I can take a look at getting a PR together to get these changes in to support password reset flow from Blazor WebAssembly. Would it be possible to get a hotfix release out sooner if I did that?

**Comment by javiercn** [comment]
@pheuter I'm not sure a patch would be a good fit for it, we can consider this for the next major release (November) if you are willing to consider sending us a PR. I would need to understand a bit better how password reset works to make sure we follow the recommended guidance.

Doing things like these in patches is problematic because if something regresses then we don't have a good path for fixing it quickly without forcing a ton of unplanned work on ourselves.

That said, we would be willing to accept a PR here if:
* It follows AAD B2C recommended guidance.
* There are no public API changes or are reasonable (I imagine at least we need to flow the password reset policy as an option down to the msal.js provider).
  * What about profile edit, does it follow the same pattern?
* There are no functional regressions in other areas caused by the update.
* This change aligns with the long term plans for msal.js and AAD B2C
  * I want to check to see if they recommend doing password resets like this or if they plan to implement this directly inside MSAL.js in a different way in the future.
  * This is because I want to avoid adding public API that gets obsoleted within months.

Does that make sense?

**Comment by pheuter** [comment]
@javiercn Makes sense. There's a [comment](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/pull/60#discussion_r416756381) on that password reset policy PR that suggests B2C is solving this issue internally by building password reset into their flows on the server side. Problem is I'm not sure what the timeline looks like there. If not for a hotfix PR that doesn't introduce any breaking changes, what are we supposed to do in the meantime to provide password reset to our users?

**Comment by javiercn** [comment]
> @javiercn Makes sense. There's a [comment](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/pull/60#discussion_r416756381) on that password reset policy PR that suggests B2C is solving this issue internally by building password reset into their flows on the server side. Problem is I'm not sure what the timeline looks like there. If not for a hotfix PR that doesn't introduce any breaking changes, what are we supposed to do in the meantime to provide password reset to our users?

You could start the password reset / edit profile flows from your own server host. You would configure B2C auth on the server (as if it was a traditional web app) and then have the edit profile and reset password buttons navigate to the server URL, which would automatically perform a challenge and send you to the appropriate B2C flow. 

Upon success, you would be sent back to the callback url on the server and then to the main page, and then the app restarts as normal.

There might be things that I don't foresee that might require adjustments, but I think this should work for the most part. I would suggest you register a 2nd redirect url to differentiate the flows started on the server from the flows started on the client, but that's should be it.

**Comment by pheuter** [comment]
Yeah I was afraid that was our only option left. Our current architecture is a Blazor Wasm app deployed to CDN and our server is actually just Azure Functions. Sounds like we'll want to create a new asp.net core web app to handle the password reset and edit profile flows.
