### ISSUE TITLE
URL Decode in Web API pipeline doesn't decode %2F to /

### ISSUE THREAD

**Issue by modestotech** [dotnet/aspnetcore#23633]
# URL Decode in Web API pipeline doesn't decode %2F to /

I have a `netcoreapp 3.1` project with `Microsoft.NET.Sdk.Web` SDK. 

When I pass the following URL Encoded string as param `O%2B19uvBBMBcVuRP4n03T%2FA%3D%3D` (original string is `O+19uvBBMBcVuRP4n03T/A==`). 
The parameter is decoded in the request pipeline, and I get:

- Expected:
  - O+19uvBBMBcVuRP4n03T/A==
- Actual
  - O+19uvBBMBcVuRP4n03T%2FA==

When I do the same conversion with `WebUtility.UrlDecode` and `HttpUtility.UrlDecode`, then getting the expected value. It for some reason fails to decode `%2F` to `/`. See [this repl](https://repl.it/repls/PalegreenGigaInverse) to confirm.

One workaround that could work is to let the pipeline decoding do "half the work", and then run `WebUtility.UrlDecode` to finish the decoding, but then the plus sign is transformed to a space ` ` in the decodification.

```
string paramId = "O+19uvBBMBcVuRP4n03T%2FA==";
string id = WebUtility.UrlDecode(paramId); // "O 19uvBBMBcVuRP4n03T/A==" 
```

Signature of controller and method:
```
[ApiVersion("1.0")]
[Area("Account")]
[Route("{version:apiVersion}/[controller]")]
[ApiController]
[Authorize]
public class CompanyController : CustomControllerBase
{
  // ...
  [HttpGet("{companyId}")]
  [Produces("application/json", Type = typeof(CompanyModel))]
  public async Task<IActionResult> Get(string companyId)
  {
    // ..

```

**Comment by Tratcher** [comment]
This is an FAQ that I hope will get addressed in MVC someday. I'm not finding a good summary on any of the linked issues so I'll add one here.

The server splits up the incoming request to path, query, headers, etc.. Then it un-escapes the request path to make routing easier. However, it can't un-escape `%2F` without changing the meaning of the path from a routing perspective. MVC or routing would need to un-escape the `companyId` value after matching the route.

Workarounds:
A) Move these values to the query
B) Don't use `/` in path values. You're using Base64 encoding, you should be using Base64Url encoding instead to avoid special characters like this.
https://en.wikipedia.org/wiki/Base64#URL_applications

Past issues:
https://github.com/dotnet/aspnetcore/issues/17864
https://github.com/dotnet/aspnetcore/issues/14170
https://github.com/dotnet/aspnetcore/issues/2655
https://github.com/dotnet/aspnetcore/issues/2669

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Our plan is to address this as part of #11544.
