### ISSUE TITLE
Update Microsoft.CodeAnalysis to RTM version

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23640]
Our builds use a fixed version of the compiler. For preview7 this was updated to a version that supports CSharp9. Before 5.0 ships we need to update this to a RTM version. This is slightly tricky because of different shipping schedules for runtime and compiler, so we need to make sure we figure out this early.

**Comment by pranavkm** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/25407

**Comment by dougbu** [comment]
@pranavkm why is this assigned to me if you're done the fix❔
