### ISSUE TITLE
nullreference execption mvc html helpers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23649]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/969459/nullreference-execption-mvc-html-helpers.html)._

---
[regression] [worked-in:16.5]
On any MVC project that is not Core 3.1 I get a null reference execption on all html helpers  
eg @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })

This happens even in teplates so I know there is no issue with the code. if you set the debugger to ignore the error the code runs perfectly

---
#### Visual Studio Feedback System on 3/30/2020, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 4/7/2020, 11:02 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by ajaybhargavb** [comment]
Possible dup of https://github.com/dotnet/aspnetcore/issues/23549 but in this case, VS doesn't crash. So keeping this open until we make sure.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The exception you're seeing is a First-Chance Exception, which has no impact on the runtime. Consider disabling that specific exception from the first chance exceptions list in VS tools: https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019
