### ISSUE TITLE
Consider also compressing the app assemblies (and its dependencies) during build

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23655]
https://github.com/dotnet/aspnetcore/pull/23611 compressed runtime assets, but does not compress the app assembly. This was based on incorrect data about how expensive it it gzip on assemblies that change frequently. We could squeeze a little more out of our build time compression by additionally compressing the app's assembly.

**Comment by mkArtakMSFT** [comment]
Closing as there has been no ask for this from the community.
