### ISSUE TITLE
Default template has unnecessary warning supressions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#23659]
`ApplicationDbContextModelSnapshot` has `#pragma warning disable 612, 618`. However, when I commented it, I didn't find any warnings. So the suppression seems unnecessary to me and can be removed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We don't plan to change this at the moment. Templates change periodically and we may end up updating this during next templates update.
