### ISSUE TITLE
ErrorViewModel in the default MVC template

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#23654]
In the default template, The `ErrorViewModel.cs` file resides in the `Models` folder. However, I believe it's better if it's in a `ViewModels` folder. An "Error" is not really an entity in the application; it's tied to a specific view (`Error.cshtml` in `Shared` folder). Even the class name tells that.

If you agree, I can submit a PR.

**Comment by mkArtakMSFT** [comment]
@LadyNaggaga assigning this to you to come up with guidance here.

**Comment by LadyNaggaga** [comment]
@Youssef1313 This a great observation.  And something we may consider in the future.  However, this change right now would affect how documentation has written on our site and that of our partners. Please know we will continue to discuss this suggestion.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
