### ISSUE TITLE
[Feature Request] Having Username in the default identity

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#23660]
Currently, when a user registers with the default identity, it asks only for an email. And in the database, email and username takes the same value. I *think* it's better experience to have a username besides the email.

I'd like also to know what is the correct way to achieve this result *currently*.

**Comment by blowdart** [comment]
This is by design. The templates are designed to keep things simple, with username and email address taking the same value.

We won't be changing the templates to ask for username as well. You can do this yourself by scaffolding out the UI and adjusting it to match your needs.
