### ISSUE TITLE
Make blazor internal routing classes public

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#23667]
**Blazor enhancement / extensibility request**

All routing related classes are unfortunately internal. I want to make a custom router based on registrations instead of `@page` annotations, but for this to work I have to copy all classes from the routing namespace to my own library because the blazor routing classes are marked internal.

https://github.com/dotnet/aspnetcore/tree/724c2e75a7415e67f9f5ad33fc72bf55507b8d59/src/Components/Components/src/Routing

Could these classes be made public?

**Comment by javiercn** [comment]
@njannink thanks for contacting us.

We don't make classes public if we can avoid it as that constrains us from evolving the framework in the future to add new features. 

If you are implementing your own router you should probably have your own abstractions for it. Our current router is designed to support basic routing in common cases and is not designed with extensibility in mind. Before we were to make anything public we would have to likely change many things to make it into something we would be happy making public.

I would suggest you either create your own abstractions from scratch or copy the implementations from the repository.

**Comment by njannink** [comment]
That is exactly what I did. But an exact copy of code is something that I normally would like to avoid. But I also understand your side.
