### ISSUE TITLE
how can I pass a paramter to blazor component?

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#23673]
the index.html
``` html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="x-test-id" content="@id" />
</head>
```
How can I pass id parameter to the view?

**Comment by javiercn** [comment]
@srxqds thanks for contacting us.

Are you talking about server-side Blazor or Blazor WebAssembly?

* Server-side Blazor components support receiving parameters through the Component tag helper.
* Passing parameters to Blazor WebAssembly from the client is not supported.

If you just want to put some data on the page, you can switch from using static html as your entry point to use a razor page as the entry point for the application.

**Comment by srxqds** [comment]
how to use a razor page as the entry point for the application
