### ISSUE TITLE
Fail to render @C# within @: razor

### ISSUE THREAD

**Issue by NatanBagrov** [dotnet/aspnetcore#23680]
### Describe the bug
Suppose we had a `<div>` like this:
```
<div id="@record.Id" class="col-md-12" @onmouseover="@(() => ProcessDepartmentRecord(record))">
```
This works ok.

Now, suppose you want to conditionally open different divs, for exapmle:
```c#
if (ProcessedDepartmentRecords.Contains(record.Id))
        {
            @:<div id="@record.Id" class="col-md-12">
        }
        else
        {
            @:<div id="@record.Id" class="col-md-12" @onmouseover="@(() => ProcessDepartmentRecord(record))">
        }
```
(and matching `@:</div>` at the end)
### To Reproduce
Written above.

### Exceptions (if any)
Compilation error
`  DepartmentRecords.razor(90, 55): [CS0103] The name 'onmouseover' does not exist in the current context`
`  DepartmentRecords.razor(90, 70): [CS1660] Cannot convert lambda expression to type 'string' because it is not a delegate type`

### How to do it?
If it is possible, please let me know the syntax, since I'm getting confused to all the `@` stuff.

### Further technical details
- ASP.NET Core version 3.1.5
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Rider 2020.1.3

**Comment by SayusiAndo** [comment]
Seems similar for me to this one: #19679

**Comment by NatanBagrov** [comment]
> Seems similar for me to this one: #19679

Indeed, looks similar.

**Comment by javiercn** [comment]
@NatanBagrov thanks for contacting us.

Using partially completed tags with `@:` is not supported in Blazor, since the compiler needs to be able to verify that all tags match appropriately for emitting the code. The recommendation is that you factor the code differently to allow for tags to be clearly balanced.

**Comment by NatanBagrov** [comment]
> @NatanBagrov thanks for contacting us.
> 
> Using partially completed tags with `@:` is not supported in Blazor, since the compiler needs to be able to verify that all tags match appropriately for emitting the code. The recommendation is that you factor the code differently to allow for tags to be clearly balanced.

Thank you for the reply, so the suggested "path" is to call the method event handler anyway, and place the branching logic inside? Thanks

**Comment by javiercn** [comment]
@NatanBagrov that's an option, another option is to do something like
```
@if(condition)
{
  <div id="@record.Id" class="col-md-12">
  ...
  </div>
}
else
{
  <div id="@record.Id" class="col-md-12" @onmouseover="@(() => ProcessDepartmentRecord(record))">
  ...
  </div>
}
```

**Comment by NatanBagrov** [comment]
> @NatanBagrov that's an option, another option is to do something like
> 
> ```
> @if(condition)
> {
>   <div id="@record.Id" class="col-md-12">
>   ...
>   </div>
> }
> else
> {
>   <div id="@record.Id" class="col-md-12" @onmouseover="@(() => ProcessDepartmentRecord(record))">
>   ...
>   </div>
> }
> ```

Oh, I forgot to address to this, when I asked for a suggestion -- The `...` inside is approx 50 lines long, so this is even worse practice I suppose ;)

**Comment by javiercn** [comment]
> Oh, I forgot to address to this when I asked for a suggestion -- The `...` inside is approx 50 lines long, so this is even worse practice I suppose ;)

You can wrap the contents within a component and then share them between the two branches?

**Comment by NatanBagrov** [comment]
> > Oh, I forgot to address to this when I asked for a suggestion -- The `...` inside is approx 50 lines long, so this is even worse practice I suppose ;)
> 
> You can wrap the contents within a component and then share them between the two branches?

I was considering it, but it sounds a bit "too much" for that matter, passing parameters, using cascades, etc...

**Comment by NatanBagrov** [comment]
Anyway, if you find that these "workaround" options are "not the best", maybe that is something worth supporting :)

**Comment by javiercn** [comment]
@NatanBagrov I believe you can also use conditional logic to set the handler, but the syntax might be more involved

```razor
@onclick="@(condition ? null : Handler)"
```

The problem with `@:` is that it allows you to write any type of unbalanced expression and it makes it really hard for the compiler to build the actual tree structure.

You could argue that we could support it for simple cases like the one you mention, but then the problem becomes that the boundary of what it is supported and what it is unsupported becomes blurry and that ends up being an issue.

We prefer to say that `@:` is not supported in Blazor since supporting that syntax is incredible complicated if not outright impossible.

For MVC/Razor is different because they don't need to produce valid markup, but for Blazor is critical.

I can't comment on your app, but there is always a balance when writing components. If you have a component that is already that big, it likely is doing more than it needs and it is likely best split into one or more smaller components, but to be honest that's a matter of opinion and style and it is up to you to decide what you feel is best for your app.

**Comment by NatanBagrov** [comment]
@javiercn Hmm I was not thinking `null` is possible. I'll check it out.

> You could argue that we could support it for simple cases like the one you mention, but then the problem becomes that the boundary of what it is supported and what it is unsupported becomes blurry and that ends up being an issue.
I totally agree with you here, and I also believe that either a full support should be provided, or none.

Thank you
