### ISSUE TITLE
Blazor doesn't detect state-change when state is changed in between async calls, requiring manual StateHasChanged()

### ISSUE THREAD

**Issue by SaebAmini** [dotnet/aspnetcore#23687]
### Describe the bug
I have a simple div element inside a component, which has a class set conditionally based on a boolean property on the component:
```
<div class='spinner-container @(!IsLoading ? "d-none" : "")'>
    <div class="spinner-border text-info" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
```

The code looks like this:

```
bool IsLoading { get; set; }

async Task HandleFormSubmit()
{
    try
    {
        await Task.Delay(10);
        IsLoading = true;
        await Task.Delay(5000);
    }
    finally
    {
        IsLoading = false;
    }
}
```

When HandleFormSubmit() is called (which is via an `@onsubmit="HandleFormSubmit"` on a `form` element), the div's class doesn't update to reflect the `IsLoading` state change. If I put an explicit `StateHasChanged()` after `IsLoading = true`, then it does update (but that's a bit... crap).

The more interesting bit is, if I move `IsLoading = true;` to before the first `Task.Delay`, Blazor somehow detects the state change and the div's class is updated.

### To Reproduce
The above should help reproduce this, but if you can't, then I'll make some time to create a repo for this (sorry, middle of work and a bit busy currently, but didn't want to just ignore/not report this as it seems quite important).

### Further technical details
- Blazor (Web Assembly) version 3.2
- Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@SaebAmini thanks for contacting us.

Blazor only triggers a render within an event handler in two situations. After all the synchronous code has completed and after all the asynchronous code has completed. It can't do better because it doesn't have access to the implementation of the method, only to the task that is returned by the handler.

To achieve what you want, I think you just need to setup `IsLoading = true` before the JS interop call, since at that point a render will be triggered. 

In other situations you need to call state has changed.

**Comment by SaebAmini** [comment]
Thanks for your quick reply @javiercn!

This is very interesting and a good gotcha to be aware of.

So to confirm, it's because the state-change is happening _in between_ the two async calls, and because the second async call (`Task.Delay`) takes a while to complete, Blazor doesn't detect and trigger a re-render, because you're saying once it encounters the first async call, then _all_ subsequent async calls need to be completed in the method for detection and re-render to happen?

> Blazor only triggers a render within an event handler in two situations. After all the synchronous code has completed and after all the asynchronous code has completed.

Do you mean all the synchronous code _before_ the first async call? confirming because there are still plenty of other bits of synchronous code left, even if I move `IsLoading = true` to the top, although they would be synchronous code in async code callbacks.

**Comment by javiercn** [comment]
@SaebAmini It works more or less like this. Your method gets conceptually transformed to something more or less like this:

```csharp
return Task.Delay(10)
  .ContinueWith(t => { IsLoading = true; /* here */ return Task.Delay(5000); })
  .ContinueWith(t => IsLoading = false)
```

Blazor only receives the returned task from this method. All we do is check whether the task completed (ran synchronously) and trigger a render or whether the task did not complete yet (it is running some async code). In this second case we do something like
```csharp
handlerTask.ContinueWith(t => StateHasChanged())
```

Which triggers the other render after the async work completes. The point is that we can know when the async work starts and when it ends, but there is no way for us to insert StateHasChanged calls at the point marked by the comment above.

**Comment by SaebAmini** [comment]
That makes sense. Thanks a lot for explaining @javiercn
