### ISSUE TITLE
Blazor unsubscribing from an Action<T> doesn't work

### ISSUE THREAD

**Issue by Ccry11** [dotnet/aspnetcore#23681]
Hi everyone,
maybe I'm doing something wrong but unsubscribing from an `Action<T>` inside Dispose function doesn't work on Balzor server side.

I have a `ProcessStatusService` that inherit from `IProcessStatus` interface:

```
   public class ProcessStatusService : IProcessStatus
    {
        public event Action<bool> ProcessExited;
        public void NotifyProcessExited(bool negativeStatusCode)
        {
            ProcessExited?.Invoke(negativeStatusCode);
        }
    }
```

IProcessStatus:
```
    public interface IProcessStatus
    {
        event Action<bool> ProcessExited;
        void NotifyProcessExited(bool negativeStatusCode);
    }
```

Inside `Index.razor` page the service is subscribed when the component is initialized.
A function `HandleStatusCodeNotification` inside `Index.razor` must be called when the action is invoked:

```
    protected override void OnInitialized()
    {
        ProcessStatusService.ProcessExited += (neagativeStatusCode) => HandleStatusCodeNotification(neagativeStatusCode);
    }
```

`HandleStatusCodeNotification:`
```
    public void HandleStatusCodeNotification(bool neagativeStatusCode)
    {
        if (neagativeStatusCode)
        {
            toastService.ShowWarning("Negative status code");
        }
        else
        {
            toastService.ShowSuccess("Positive status code");
        }
    }
```
The action is invoked from an external controller:

`_processStatusService.NotifyProcessExited(false);`

Everithing works fine here.
The problem comes when the unsubscription should occur.
`Index.razor` implements the `IDisposable` interface and the `Dispose` method is implemented, it is triggered when the component is trashed but the unsubscription to `ProcessExited` never occurs:
```
    public void Dispose()
    {
        ProcessStatusService.ProcessExited -= (neagativeStatusCode) => HandleStatusCodeNotification(neagativeStatusCode);
    }
```
The `HandleStatusCodeNotification` method is called every time the action is invoked even if I am on a different page where the subscription to `ProcessExited` has never been made.
Thanks

----------------------

.NET Core SDK:
 Version:   3.1.301
 Commit:    7feb845744

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

**Comment by javiercn** [comment]
@Ccry11 thanks for contacting us.

I think this is due to the fact that you are using a lambda expression. In general I believe that the same delegate instance needs to be used for subscribe and unsubscribe. You can check this with a console application, but as long as the dispose method is called, Blazor has done its part and the issue, based on my understanding, relies on your usage of events and delegates.

Create the delegate and store it into a field and then use that field in the subscribe/unsubscribe call to the event, that should work.

**Comment by Ccry11** [comment]
Hi @javiercn,
thank you for the quick response.
I think I have understand what you mean but I don't know how to do it.
I solved the problem in the following way:

I removed the `Action<T>` from `ProcessExited` and I defined a public `NegativeStatusCode` property which stores the value passed to `NotifyProcessExited` method
```
        public bool NegativeStatusCode { get; private set; }

        public event Action ProcessExited;
        public void NotifyProcessExited(bool negativeStatusCode)
        {
            NegativeStatusCode = negativeStatusCode;
            ProcessExited?.Invoke();
        }
```

Inside `index.razor` I removed the lambda expression which, as you said, probably was the cause of the issue:

```
    protected override void OnInitialized()
    {
        ProcessStatusService.ProcessExited += HandleStatusCodeNotification;
    }
```

At this point `HandleStatusCodeNotification` accepts no parameters and the value can be retrieved from `ProcessStatusService` injection

```
@inject ProcessStatusService ProcessStatusService
....
code {
    public void HandleStatusCodeNotification()
    {
        if (ProcessStatusService.NegativeStatusCode)
        {
            ToastrService.ShowWarning("Negative status code");
        }
        else
        {
            ToastrService.ShowSuccess("Stats Updated");
        }
    }
}
```

Probably this is not a best practice.
Please let me know what you think about this and it would be awesome if you could provide to me an example of the solution you proposed

**Comment by javiercn** [comment]
Actually, you can just do 
```csharp
        ProcessStatusService.ProcessExited += HandleStatusCodeNotification;
```
and that should work.

Otherwise, declare a field and store the lambda in a field before subscribing (and use the field to unsubscribe
