### ISSUE TITLE
pass Child Content through RenderFragment in Component Tag Helper 

### ISSUE THREAD

**Issue by lehoangphan** [dotnet/aspnetcore#23688]
I'm intergrating Blazor Component to Razor Page in my existing Project through this
`https://docs.microsoft.com/en-us/aspnet/core/blazor/components/integrate-components?view=aspnetcore-3.1`

But now i need to use Child Content but i can not pass `<vc:search-box></vc:search-box>` through the component tag helper 

`<component type="typeof(SideBarComponent)" 
                           render-mode="Static" 
                           param-ChildContent="<vc:search-box></vc:search-box>"/>`

thanks you

**Comment by javiercn** [comment]
@lehoangphan thanks for contacting us.

This is not a feature we currently have, but in general passing render fragments will be hard/impossible to do in any mode that isn't static. Delegates are not serializable and if you were able to pass them to a component you would not be able to receive them on a server context or on a webassembly context, so the only true use they have is for when you are rendering the UI statically (meaning you don't expect to have Blazor at all afterwards).

**Comment by SteveSandersonMS** [comment]
I would recommend creating a `.razor` component that references the component you want to render *with* the child content you want to pass, and then invoke that from your host `.cshtml` file.

As @javiercn says, you can't construct arbitrary Razor components from inside a `.cshtml` file, but you can construct them inside a `.razor` file and then reference that from your `.cshtml`.
