### ISSUE TITLE
call dom api scrollTo method in Microsoft Edge error, but it can work in chrome.

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#23697]
### Describe the bug

I use c# code to call dom api with using WebAssembly.Bindings from mono and WebAssembly.Dom from https://github.com/kjpou1/wasm-dom.

my code call **scrollTo** show in below:
```c#
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (scrollView == null)
            scrollView = Web.Document.GetElementById<HTMLDivElement>(C_LogScrollView);
        if (scrollView != null) // && _needScroll && _allowScroll)
        {
            scrollView.ScrollTo(0, scrollView.ScrollHeight);
        }
    }
```
### Exceptions (if any)

![image](https://user-images.githubusercontent.com/5187024/86594069-f56ac100-bfc8-11ea-9c8a-46d21a6b5b35.png)

### Further technical details
- ASP.NET Core version:  3.2
- Include the output of `dotnet --info` 3.1.4
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: windows

**Comment by javiercn** [comment]
@srxqds thanks for contacting us.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.

We think you are using a third-party component and that the issue being raised is not related to Blazor. We would suggest you contact the creators of the library you are using and seek help there or on stackoverflow.
