### ISSUE TITLE
Seeing 405 with Exception System.InvalidOperationException at Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter.OnActionExecuting

### ISSUE THREAD

**Issue by justConfused** [dotnet/aspnetcore#23718]
### Describe the bug
After the app restart we staring to seeing 405s from ResponseCacheFilter. We the following cache profiles
```
opt.CacheProfiles.Add("Default", new CacheProfile { NoStore = true, Location = ResponseCacheLocation.None });
opt.CacheProfiles.Add("PeopleProfile", new CacheProfile { Location = ResponseCacheLocation.Client, Duration = 1209600 }); // 14 days
```
### To Reproduce
Kill and restart the app net core app multiple time
### Exceptions (if any)
System.InvalidOperationException at Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter.OnActionExecuting

### Further technical details
- ASP.NET Core version 2.1

**Comment by pranavkm** [comment]
What's the exception message \ stack trace?

**Comment by justConfused** [comment]
{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter.OnActionExecuting","level":0,"line":0}

{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next","level":1,"line":0}
--
{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext","level":2,"line":0}
--

{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":3,"line":0}
--
{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow","level":4,"line":0}
--

{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next","level":5,"line":0}
--

{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext","level":6,"line":0}
--

{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext","level":6,"line":0}
--
 

{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":7,"line":0}
--
 
{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext","level":8,"line":0}
--

{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":9,"line":0}
--
{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow","level":10,"line":0}
--
{"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next","level":11,"line":0}
--
 {"assembly":"Microsoft.AspNetCore.Mvc.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext","level":12,"line":0}
--

{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":14,"line":0}
--
 
{"assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":13,"line":0}
--

**Comment by justConfused** [comment]
Hi @pranavkm I have added the most of stack here as best as I could. If it possible can I contact on you on teams my id anbitton@microsoft.com to share better information.

**Comment by pranavkm** [comment]
Do you happen to have an exception message? Going by the exception type and your app code, I'm going to guess you're running in to this error: https://github.com/dotnet/aspnetcore/blob/2.1.3/src/Mvc/Mvc.Core/src/Filters/ResponseCacheFilterExecutor.cs#L65-L70. You should be able to debug that though.
