### ISSUE TITLE
connect impapa with odbc in netcore

### ISSUE THREAD

**Issue by ClementeGao** [dotnet/aspnetcore#23719]
hi friend!  how connect impala with odbc or other in netcore

**Comment by SayusiAndo** [comment]
I did this 2 years ago. You need to use ODBC.

The Cloudera documentation can be found [here](https://docs.cloudera.com/documentation/other/connectors/impala-odbc/latest/Cloudera-ODBC-Driver-for-Impala-Install-Guide.pdf).

You can see a few example code in my questions in SO [here](https://stackoverflow.com/questions/53959319/why-this-well-working-query-against-impala-throws-error-via-odbc-driver) and [here](https://stackoverflow.com/questions/53948700/how-to-batch-inserts-via-impala-odbc).

If you find any error or something feel free to report it to Cloudera. They are going to fix it.

**Comment by ClementeGao** [comment]
thank you very much l will see document

**Comment by javiercn** [comment]
Thanks for contacting us @ClementeGao.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag.
