### ISSUE TITLE
FAR VSReferenceItem Not Given FS Location

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23723]
The FAR `VSReferenceItem.Location.Uri` [received](https://github.com/dotnet/aspnetcore-tooling/blob/093fc2e5d096012e8c125a896d4b22f84cb57458/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs#L178-L183) is a `vsls:` prefixed URI and not file system prefixed. The other `Location.Uris` we get (ex. for [Go To Def](https://github.com/dotnet/aspnetcore-tooling/blob/093fc2e5d096012e8c125a896d4b22f84cb57458/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToDefinitionHandler.cs#L101)), are prefixed with the file system.

Expected: `C:/Users/tanay/blazorserver/Pages/Counter.razor.g.cs`
Actual: `vsls:/Pages/Counter.razor.g.cs`

This results in the document mapping provider failing and FAR not working as expected in Liveshare.

FYI: @NTaylorMullen

**Comment by TanayParikh** [comment]
This is most likely an external issue, I've reached out to LSP Platform.

**Comment by TanayParikh** [comment]
Confirmed external LSP Platform issue. Likely recently introduced with LiveShare providing VSTS URIs.

**Comment by TanayParikh** [comment]
Created: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1154416

**Comment by TanayParikh** [comment]
Issue has been routed to Liveshare.

**Comment by TanayParikh** [comment]
Just tried with latest VS Master, and everything is working as expected again. No longer getting the `vsls:` prefix. Double checking if they've made changes to specifically address this, or if it was caught by something else.

**Comment by NTaylorMullen** [comment]
@TanayParikh should this be closed out given its marked as done? If not, please move to 16.8-Preview2 milestone

**Comment by TanayParikh** [comment]
Yes, closed out, thanks!
