### ISSUE TITLE
The package is missing the required nuspec file.

### ISSUE THREAD

**Issue by graphicsxp** [dotnet/aspnetcore#23734]
#16851 # Describe the bug
I have installed Microsoft.AspNetCore.Authentication.JwtBearer 3.1.5
It has a dependency on microsoft.identitymodel.protocols.openidconnect 5.5.0 but this package is missing a nuspec file. 
When I use nuget pack to create my own package I get the error : 

 error NU5037: The package is missing the required nuspec file. Path: \.nuget\packages\microsoft.identitymodel.protocols.openidconnect\5.5.0 

please upgrade to latest version of openidconnect which contains a nuspec file

### To Reproduce
try to pack nuget from a solution that reference the above package.

### Exceptions (if any)
 error NU5037: The package is missing the required nuspec file. Path: \.nuget\packages\microsoft.identitymodel.protocols.openidconnect\5.5.0

**Comment by Tratcher** [comment]
Duplicate of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1484
