### ISSUE TITLE
Login page shouldn't display if I already logged in

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#23732]
1. Create a new ASP.NET Core 3.1 MVC app with Individual User Accounts.
2. Run the app.
3. Create a new account.
4. Login with the new account
5. Go to localhost:port/Identity/Account/Login (the register page has same behavior too)
6. The page opens with the login form despite there is a logged in user.

    ![image](https://user-images.githubusercontent.com/31348972/86770750-77063180-c051-11ea-8b66-c1d4ef5f55cd.png)

I don't think the current behavior is good.

**Comment by javiercn** [comment]
@Youssef1313 thanks for contacting us.

You can change this behavior by overriding the login page. I think it is fine for the login page to be there, otherwise there are some scenarios like switching from one user to another that become much harder to implement.
