### ISSUE TITLE
Disable CA1822 on Asp.net Controller methods as well as Startup classes.

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/aspnetcore#23737]
CA1822 is provided as a work around on `ConfigureServices` as well as controller methods that don't access instance data such as the `loggger` etc.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've added them to avoid warnings in newly created projects. We prefer to keep these in for now.

**Comment by juliusfriedman** [comment]
See also https://github.com/dotnet/roslyn-analyzers/issues/3835#issuecomment-656930558
