### ISSUE TITLE
[Question] Unknown model binders for complex object types with [FromQuery] attributes

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#23733]
If we have a simple object with 2 properties - `Id`, `Name`, and is an argument in an action method, which argument is decorated with the `[FromQuery]` attribute, if we have a `IModelBinderProvider` implemented, we can see that the method with the following signature `IModelBinder GetBinder(ModelBinderProviderContext)` gets called multiple times.

The first call is expected, as `ModelBinderProviderContext.Metadata.ModelType` is the type of the complex object, but following that come binders for every type inside the class, i.e - `int` and `string` in our case. (`int` for the `Id`, `string` for the `Name` properties)

And upon further inspection, the string is actually the JSON representation of the actual string.

What the hell are those things? Their `ModelBinderProviderContext.BindingInfo.BindingSource` is set to null.
Every property inside `ModelBinderProviderContext.BindingInfo` for them is set to be null.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by pranavkm** [comment]
@SpiritBob for complex types, MVC will create a provider for each property unless you it finds a binder that can model bind the type. In addition, MVC does not support deserializing JSON from query.

**Comment by SpiritBob** [comment]
@mkArtakMSFT https://github.com/SpiritBob/ModelBinder

@pranavkm from what I can see my `IModelBinderProvider` class receives a provider for the complex type, followed by every property in them. Shouldn't it only receive the complex type, and if no provider is returned - to return the property providers of said type?

Or am I mistaking and those aren't the providers I receive, but something else? You can see the source code - `StringBinderProvider` class.
