### ISSUE TITLE
Blazor wasm - Referenced project fails to load when not rebuilding

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#23738]
**Bug description**

I moved part of the infrastructure code from my blazor wasm project to a new project. And now I'm getting a `FileNotFoundExecption - Could not load file or assembly` when Im running my blazor project. Only when I do a full rebuild it goes fine. Full exception and project files below. I use `Microsoft Visual Studio Professional 2019 - Version 16.6.3`

Any ideas what is causing this?

**Infrastructure project file**
```
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>xxx.Web.Client.Infractructure</RootNamespace>
    <BlazorWebAssemblyEnableLinking Condition="'$(Configuration)'!='Release'">false</BlazorWebAssemblyEnableLinking>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <LangVersion>latest</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
    <SourceRevisionId>build$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</SourceRevisionId>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.5" />
    <PackageReference Include="ReactiveUI.Blazor" Version="11.4.17" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.1" />
    <PackageReference Include="Tewr.Blazor.FileReader" Version="1.6.0.20166" />
  </ItemGroup>
</Project>
```

**Blazor wasm project file**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RuntimeIdentifiers>win10-x64;linux-x64</RuntimeIdentifiers>
    <RootNamespace>xxx.Web.Client</RootNamespace>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <TypeScriptTarget>ES2019</TypeScriptTarget>
    <TypeScriptModuleKind>System</TypeScriptModuleKind>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptOutFile>wwwroot\scripts\app.js</TypeScriptOutFile>
    <BlazorWebAssemblyEnableLinking Condition="'$(Configuration)'!='Release'">false</BlazorWebAssemblyEnableLinking>
    <LangVersion>latest</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
    <SourceRevisionId>build$([System.DateTime]::UtcNow.ToString("yyyyMMddHHmmss"))</SourceRevisionId>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise.Material" Version="0.9.1.1" />
    <PackageReference Include="Blazorise.Components" Version="0.9.1.1" />
    <PackageReference Include="Blazorise.DataGrid" Version="0.9.1.1" />
    <PackageReference Include="Blazorise.Icons.Material" Version="0.9.1.1" />
    <PackageReference Include="BuildWebCompiler" Version="1.12.405" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview3.20168.3" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="3.9.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="2.1.76" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\xxx.Client.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

</Project>
```

**Exception as shown in Chrome console**
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'xxxx.Web.Client.Infrastructure, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
> f.printErr @ blazor.webassembly.js:1
> put_char @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> doWritev @ dotnet.3.2.0.js:1
> _fd_write @ dotnet.3.2.0.js:1
> write @ dotnet.wasm:1
> console_write @ dotnet.wasm:1
> mono_w32file_read_or_write @ dotnet.wasm:1
> mono_w32file_write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
> do_icall @ dotnet.wasm:1
> do_icall_wrapper @ dotnet.wasm:1
> interp_exec_method @ dotnet.wasm:1
> interp_runtime_invoke @ dotnet.wasm:1
> mono_jit_runtime_invoke @ dotnet.wasm:1
> do_runtime_invoke @ dotnet.wasm:1
> mono_runtime_try_invoke @ dotnet.wasm:1
> mono_runtime_invoke @ dotnet.wasm:1
> mono_wasm_invoke_method @ dotnet.wasm:1
> Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
> call_method @ dotnet.3.2.0.js:1
> (anonymous) @ dotnet.3.2.0.js:1
> callEntryPoint @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> r @ blazor.webassembly.js:1
> v @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> n @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
> f.printErr @ blazor.webassembly.js:1
> put_char @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> doWritev @ dotnet.3.2.0.js:1
> _fd_write @ dotnet.3.2.0.js:1
> write @ dotnet.wasm:1
> console_write @ dotnet.wasm:1
> mono_w32file_read_or_write @ dotnet.wasm:1
> mono_w32file_write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
> do_icall @ dotnet.wasm:1
> do_icall_wrapper @ dotnet.wasm:1
> interp_exec_method @ dotnet.wasm:1
> interp_runtime_invoke @ dotnet.wasm:1
> mono_jit_runtime_invoke @ dotnet.wasm:1
> do_runtime_invoke @ dotnet.wasm:1
> mono_runtime_try_invoke @ dotnet.wasm:1
> mono_runtime_invoke @ dotnet.wasm:1
> mono_wasm_invoke_method @ dotnet.wasm:1
> Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
> call_method @ dotnet.3.2.0.js:1
> (anonymous) @ dotnet.3.2.0.js:1
> callEntryPoint @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> r @ blazor.webassembly.js:1
> v @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> n @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2a1ef08 + 0x000ce> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> put_char @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> doWritev @ dotnet.3.2.0.js:1
> _fd_write @ dotnet.3.2.0.js:1
> write @ dotnet.wasm:1
> console_write @ dotnet.wasm:1
> mono_w32file_read_or_write @ dotnet.wasm:1
> mono_w32file_write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
> do_icall @ dotnet.wasm:1
> do_icall_wrapper @ dotnet.wasm:1
> interp_exec_method @ dotnet.wasm:1
> interp_runtime_invoke @ dotnet.wasm:1
> mono_jit_runtime_invoke @ dotnet.wasm:1
> do_runtime_invoke @ dotnet.wasm:1
> mono_runtime_try_invoke @ dotnet.wasm:1
> mono_runtime_invoke @ dotnet.wasm:1
> mono_wasm_invoke_method @ dotnet.wasm:1
> Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
> call_method @ dotnet.3.2.0.js:1
> (anonymous) @ dotnet.3.2.0.js:1
> callEntryPoint @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> r @ blazor.webassembly.js:1
> v @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> n @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> blazor.webassembly.js:1    --- End of inner exception stack trace ---
> f.printErr @ blazor.webassembly.js:1
> put_char @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> doWritev @ dotnet.3.2.0.js:1
> _fd_write @ dotnet.3.2.0.js:1
> write @ dotnet.wasm:1
> console_write @ dotnet.wasm:1
> mono_w32file_read_or_write @ dotnet.wasm:1
> mono_w32file_write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
> do_icall @ dotnet.wasm:1
> do_icall_wrapper @ dotnet.wasm:1
> interp_exec_method @ dotnet.wasm:1
> interp_runtime_invoke @ dotnet.wasm:1
> mono_jit_runtime_invoke @ dotnet.wasm:1
> do_runtime_invoke @ dotnet.wasm:1
> mono_runtime_try_invoke @ dotnet.wasm:1
> mono_runtime_invoke @ dotnet.wasm:1
> mono_wasm_invoke_method @ dotnet.wasm:1
> Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
> call_method @ dotnet.3.2.0.js:1
> (anonymous) @ dotnet.3.2.0.js:1
> callEntryPoint @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> r @ blazor.webassembly.js:1
> v @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> n @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2a1ef08 + 0x000f6> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> put_char @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> doWritev @ dotnet.3.2.0.js:1
> _fd_write @ dotnet.3.2.0.js:1
> write @ dotnet.wasm:1
> console_write @ dotnet.wasm:1
> mono_w32file_read_or_write @ dotnet.wasm:1
> mono_w32file_write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
> do_icall @ dotnet.wasm:1
> do_icall_wrapper @ dotnet.wasm:1
> interp_exec_method @ dotnet.wasm:1
> interp_runtime_invoke @ dotnet.wasm:1
> mono_jit_runtime_invoke @ dotnet.wasm:1
> do_runtime_invoke @ dotnet.wasm:1
> mono_runtime_try_invoke @ dotnet.wasm:1
> mono_runtime_invoke @ dotnet.wasm:1
> mono_wasm_invoke_method @ dotnet.wasm:1
> Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
> call_method @ dotnet.3.2.0.js:1
> (anonymous) @ dotnet.3.2.0.js:1
> callEntryPoint @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> r @ blazor.webassembly.js:1
> v @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> n @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x2a1e830 + 0x00014> in <filename unknown>:0 
> f.printErr @ blazor.webassembly.js:1
> put_char @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> write @ dotnet.3.2.0.js:1
> doWritev @ dotnet.3.2.0.js:1
> _fd_write @ dotnet.3.2.0.js:1
> write @ dotnet.wasm:1
> console_write @ dotnet.wasm:1
> mono_w32file_read_or_write @ dotnet.wasm:1
> mono_w32file_write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write @ dotnet.wasm:1
> ves_icall_System_IO_MonoIO_Write_raw @ dotnet.wasm:1
> do_icall @ dotnet.wasm:1
> do_icall_wrapper @ dotnet.wasm:1
> interp_exec_method @ dotnet.wasm:1
> interp_runtime_invoke @ dotnet.wasm:1
> mono_jit_runtime_invoke @ dotnet.wasm:1
> do_runtime_invoke @ dotnet.wasm:1
> mono_runtime_try_invoke @ dotnet.wasm:1
> mono_runtime_invoke @ dotnet.wasm:1
> mono_wasm_invoke_method @ dotnet.wasm:1
> Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
> call_method @ dotnet.3.2.0.js:1
> (anonymous) @ dotnet.3.2.0.js:1
> callEntryPoint @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> i @ blazor.webassembly.js:1
> Promise.then (async)
> s @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> r @ blazor.webassembly.js:1
> v @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> n @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> (anonymous) @ blazor.webassembly.js:1
> blazor.webassembly.js:1   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint (System.String assemblyName, System.String[] args) <0x29d5528 + 0x00086> in <filename unknown>:0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Try creating the infrastructure project from the Razor Class Library project template. Your project is not properly setup. You can learn more about this in https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-3.1&tabs=visual-studio

**Comment by njannink** [comment]
@mkArtakMSFT  I changed my infrastructure project to the code below like when you create a new razor class library and I added a _imports.razor and a wwwroot folder, but I still have the problem described above. So the issue isn't resolved/closed with that

```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Craytive.BaselineZ.Web.Client.Infractructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="3.1.5" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.5" />
    <PackageReference Include="ReactiveUI.Blazor" Version="11.4.17" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.1" />
    <PackageReference Include="Tewr.Blazor.FileReader" Version="1.6.0.20166" />
  </ItemGroup>

</Project>
```
