### ISSUE TITLE
Calling Jquery methods from Blazor Wasm OnAfterRender is not working due to DOM not being ready

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#23740]
In my Blazor Wasm project, I call a javascript method using JsInterop. This javascript method in turn executes a Jquery code. The jquery code is **not** working as expected, presumably because the DOM is not ready, even though, as the name of OnAfterRender implies, it should be ready. The issue can be fixed by adding a few seconds delay inside OnAfterRender, which confirms DOM readiness issue.

The issue is reproduced here: https://github.com/bancroftway/blazorissuesrepro/tree/dom-readiness-issue

A small video I made to show the issue is here: https://youtu.be/PU9i5Tw4jKQ

### Further technical details
- ASP.NET Core version : 3.14
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 3.1

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by SteveSandersonMS** [comment]
In your repro code, you're trying to reference the elements with class `connectedSortable` before they are rendered.

**Comment by bancroftway** [comment]
@SteveSandersonMS, to implement your suggestion "You need to call your JS method only after the DOM elements it needs to reference have been rendered", what is the procedure...I thought the only way to do this was to call the JS method from OnAfterRender, which is what I am doing?

**Comment by MaQy** [comment]
The component is rerrendered when the list you are requesting asynchronously is ready. The easiest way is to check that the list of days is not null, the same thing you are doing in the Razor part.
