### ISSUE TITLE
C# -> Razor FAR of Razor Property Not Working

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23754]
This seems to be a new regression, was working as expected last time I'd tried this.  This works as expected _sometimes_. Thanks @dibarbet!

Repro:
1. `dotnet new blazorserver`
2. Add to `Counter.razor`
```
    [Parameter]
    public static string Name { get; set; }
```
3. Add to `Program.cs`, `Counter.Name;`
4. FAR from `Program.cs` on `Counter.Name`

Expected:
2 FAR results

Actual:
Just FAR result from `Program.cs`

**Comment by TanayParikh** [comment]
Verified[ `CSharpDocumentExcerptService` ](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpDocumentExcerptService.cs#L91-L93)is returning appropriate results.

**Comment by TanayParikh** [comment]
From the roslyn issue:
> Investigation notes:
The definition shows up (as the definition node) which should be clickable. This threw me off as I thought the definition was missing.
But the selecting the definition node to navigate to the definition tries to navigate to the generated file, which doesn't work so there's still a bug here.


So we'll probably need to update the actual document we're [sending](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpDocumentExcerptService.cs#L91-L93).

Unblocking

**Comment by TanayParikh** [comment]
https://github.com/dotnet/roslyn/pull/45956

Leaving this issue up to validate once the above is merged.

**Comment by NTaylorMullen** [comment]
@TanayParikh Given go-to-def/go-to-impl is landing in 16.8-Preview1 I assume this is as well?

**Comment by TanayParikh** [comment]
> @TanayParikh Given go-to-def/go-to-impl is landing in 16.8-Preview1 I assume this is as well?

Yes, assuming https://github.com/dotnet/roslyn/pull/45956 is part of 16.8-Preview1
