### ISSUE TITLE
Razor LSP: Pressing enter between {|} in C# should format correctly

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#23753]
We need to investigate how this happens in local C# and see how we can do it in the LSP world.

Expected:
![enterformatting2](https://user-images.githubusercontent.com/1579269/86847223-d586dc00-c060-11ea-9b14-605dff694d01.gif)

Actual:
![enterformatting](https://user-images.githubusercontent.com/1579269/86847027-9062aa00-c060-11ea-9c1a-d836b0430910.gif)

**Comment by Anduin2017** [comment]
It seems that this still happens.

Any further info about this?

Expected formatting:

![image](https://user-images.githubusercontent.com/19531547/89892899-f87d5080-dc09-11ea-9f00-bb9cb3a2b7db.png)

Actual formatting:

![image](https://user-images.githubusercontent.com/19531547/89892913-003cf500-dc0a-11ea-8220-48b9666a01c3.png)

**Comment by ajaybhargavb** [comment]
@Anduin2017 we are planning to address issues like those in our new [experimental razor editor](https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/). That progress is being tracked [here](https://github.com/dotnet/aspnetcore/issues/14271).

**Comment by ajaybhargavb** [comment]
Blocked on https://github.com/dotnet/roslyn/issues/47691

**Comment by ajaybhargavb** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/23053
