### ISSUE TITLE
optimize startup order

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#23769]
### Is your feature request related to a problem? Please describe.

when create a web project, it will automatically add a launchSettings.json file, i hope to start the application as the first startup item

**Expected Behavior**:

```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:31133",
      "sslPort": 44352
    }
  },
  "profiles": {
    "WebApplication1": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

```

**Actual Behavior**:

```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:31133",
      "sslPort": 44352
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "WebApplication1": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

```

**Comment by Varorbc** [comment]
If possible, it is best to delete the iis setting

**Comment by javiercn** [comment]
@Varorbc thanks for contacting us.

This is not a behavior we plan to change, since the default option is to deploy Kestrel behind IIS or another reverse proxy. 

You are free to change your launchSettings.json on created apps however you see fit to suit your scenarios.

**Comment by Varorbc** [comment]
@javiercn  In a development environment, why does a web project need a reverse proxy?

**Comment by javiercn** [comment]
@Varorbc because it best matches the common deployment scenarios. This has been the default setup since .NET Core 1.0; we don't plan to change this unless we find compelling reasons to do so.

**Comment by Varorbc** [comment]
@javiercn If in Linux or Mac environment, IIS is obviously not suitable

**Comment by Varorbc** [comment]
@javiercn reopen this issue?

**Comment by javiercn** [comment]
> @javiercn If in Linux or Mac environment, IIS is obviously not suitable

It is not used on Mac or Linux, only on Windows within Visual Studio.

As we stated before, this is not a behavior we plan to change, since this has been the historical default and we don't see a meaningful reason to disrupt all our existing customers with this change.

I understand that this might not match your expectations or preferences, but making these types of changes is not something we do unless we have an imperative reason since it wildly disrupts the existing experiences and offers no clear advantage that justifies it.

Hope that helps explain our reasoning.
