### ISSUE TITLE
Investigate numerous test failures on Windows.10.Amd64.Open agents

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#23760]
Most of the failures were an overall failure of the IIS.FunctionalTests work item e.g. in
- https://dev.azure.com/dnceng/public/_build/results?buildId=717313
- https://dev.azure.com/dnceng/public/_build/results?buildId=718828

Also see failures of
- Sockets.FunctionalTests in https://dev.azure.com/dnceng/public/_build/results?buildId=717313
- IIS.NewShim.FunctionalTests in https://dev.azure.com/dnceng/public/_build/results?buildId=717924
- Microsoft.AspNetCore.JsonPatch.Tests in https://dev.azure.com/dnceng/public/_build/results?buildId=718502
- IIS.NewHandler.FunctionalTests and Microsoft.AspNetCore.SignalR.Client.FunctionalTests in https://dev.azure.com/dnceng/public/_build/results?buildId=719173

Individual tests are _sometimes_ as failing but normally only a work item problem is reported. A DMP file was collected for many of the failures, indicating the test assembly timed out.

----

Note there may be other issues lurking here; some of the failures above may be unrelated.

In addition, a common error in the console log might indicate an overall setup issue:
``` text
C:\h\w\BA5A0A33\w\A9560943\e\RunTests\RunTests.csproj : error NU1101: Unable to find package system.memory. No packages exist with this id in source(s): https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
C:\h\w\BA5A0A33\w\A9560943\e\RunTests\RunTests.csproj : error NU1103: Unable to find a stable package Microsoft.CSharp with version (>= 4.4.1)
C:\h\w\BA5A0A33\w\A9560943\e\RunTests\RunTests.csproj : error NU1103:   - Found 440 version(s) in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json [ Nearest version: 5.0.0-alpha.1.19524.13 ]
  Failed to restore C:\h\w\BA5A0A33\w\A9560943\e\RunTests\RunTests.csproj (in 961 ms).
```

**Comment by ryanbrandenburg** [comment]
It seems that the report there is just as it says, that feed doesn't have Microsoft.CSharp v4.4.1 or any version of System.Memory. What is most puzzling about this is how that doesn't cause the build to fail every time.

@HaoK for Helix knowledge. @HaoK do you have any guesses as why that would fail silently?

**Comment by HaoK** [comment]
I'm not sure, we've had that issue for a long time that it complains about those when trying to restore for the helix runner.  It doesn't seem to cause any issues on the runs though.  You are talking about these errors specifically right?

```
C:\h\w\B090090E\w\ADFD09AF\e\RunTests\RunTests.csproj : error NU1103: Unable to find a stable package Microsoft.CSharp with version (>= 4.4.1)
C:\h\w\B090090E\w\ADFD09AF\e\RunTests\RunTests.csproj : error NU1103:   - Found 440 version(s) in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json [ Nearest version: 5.0.0-alpha.1.19524.13 ]
C:\h\w\B090090E\w\ADFD09AF\e\RunTests\RunTests.csproj : error NU1101: Unable to find package system.memory. No packages exist with this id in source(s): https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
```

Not every run will have those warnings, but I've seen it quite frequently:

Here's an example run that doesn't have the restore errors:

```
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-141abfbed7ef4dc981/ProjectTemplates.Tests--net5.0/console.affcfd26.log?sv=2019-02-02&se=2020-07-29T12%3A54%3A03Z&sr=c&sp=rl&sig=7W05PlHugjh1hb%2FXnbmTT7vk7Y1vuNIYmeo4fYy9Pz8%3D
```

**Comment by ryanbrandenburg** [comment]
@HaoK How could it be that not all runs encounter those errors, given that there's only one NuGet source being consulted and it doesn't contain the requested packages? That would imply that the build is non-deterministic as to which NuGet it consults, or as to which packages it attempts to download. Both seem like pretty crazy prospects.

**Comment by HaoK** [comment]
The version of the sdk/runtime does change somewhat frequently, maybe the feed isn't updated at the same cadence that we get new versions of runtime/sdk?

**Comment by BrennanConroy** [comment]
Hao, can you explain why you changed the restore feed for windows only here: https://github.com/dotnet/aspnetcore/commit/a806ae62c3847cfe6a83082cebda04e1a40c21ff#diff-28e9118e047c42bc3f4f81273511de75R33

Is it because of the weird ARM issues? And should we perhaps have both nuget.org and dotnet5 feed specified?

**Comment by HaoK** [comment]
Ah right, restore wasn't working with just the normal feed, yeah maybe the errors will go away if we just have both feeds, I can try that

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/23863

**Comment by HaoK** [comment]
Logs look clean on the windows 10 queue I checked, https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-23863-merge-7358a3f80c18467a91/Diagnostics.EFCore.FunctionalTests--net5.0/console.ab788e99.log?sv=2019-02-02&se=2020-07-30T19%3A21%3A57Z&sr=c&sp=rl&sig=PlaFIQPoaJsfWlvC%2BIJErNusFm4RMq1%2Bv8A2qYE4NOs%3D

Compared to one with the restore errors on the same queue:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-98777dbbf161404db8/Diagnostics.EFCore.FunctionalTests--net5.0/console.d459f8e3.log?sv=2019-02-02&se=2020-07-30T02%3A18%3A31Z&sr=c&sp=rl&sig=lvLcoAuoP%2F4tdHFX7KmhNrSLSlxL0VhJzGE%2BdqNULKc%3D

**Comment by halter73** [comment]
Should we close this issue since "close this issue, helix timeouts were increased, and the nuget feed errors are fixed" as @BrennanConroy  mentioned in dotnet/aspnetcore-internal#3642?

**Comment by dougbu** [comment]
Sure, we can always create new issues if similar problems show up
