### ISSUE TITLE
netcore 3.1 deadlock

### ISSUE THREAD

**Issue by JunCores** [dotnet/aspnetcore#23767]
envoriment：centos

After running on Linux for a period of time, all interfaces are not returned. Through ActionFilter, we can see that we have entered OnActionExecuting, but we have not entered OnActionExecuted. The content in the contoller is also executed, but it does not return. After 20 minutes, other interfaces can return normally

**Comment by davidfowl** [comment]
Are you writing blocking code? Are you using task.result? Can you use dotnet counters to collect performance counters for your application?

**Comment by javiercn** [comment]
@JunCores thanks for contacting us.

It is not clear to us what you are trying to indicate with _all interfaces are not returned_. From what we can tell, you are suggesting that some request gets stuck while running inside `OnActionExecuting`.

We don't have enough information to determine there is an issue here, I would suggest you do the following:
* Capture a memory dump with `dotnet-dump` and analyze it to understand where exactly the request gets stuck.
  * You can probably achieve this by looking at the callstack on the executing threads.

**Comment by JunCores** [comment]
> Are you writing blocking code? Are you using task.result? Can you use dotnet counters to collect counters for your application?

only one interface use task.result，but no call it ,all interfaces are not returned.

**Comment by JunCores** [comment]
> * dotnet-dump

I'm trying to upgrade to 3.1.5, which is currently 3.1.3. I suspect there is something wrong with this version

**Comment by JunCores** [comment]
> @JunCores thanks for contacting us.
> 
> It is not clear to us what you are trying to indicate with _all interfaces are not returned_. From what we can tell, you are suggesting that some request gets stuck while running inside `OnActionExecuting`.
> 
> We don't have enough information to determine there is an issue here, I would suggest you do the following:
> 
> * Capture a memory dump with `dotnet-dump` and analyze it to understand where exactly the request gets stuck.
>   
>   * You can probably achieve this by looking at the callstack on the executing threads.

stuck like this screenshot
[http://juncores.top/images/1.png](url)

**Comment by javiercn** [comment]
@JunCores Alternatively you could try an produce a minimal repro project and detailed steps to reproduce this issue so that we can try and help you, but I suspect there is something that you added to the pipeline that is causing thread starvation, so as @davidfowl mentions I would suggest you check for usages of task.Result or task.Wait() as potential culprits.

Unfortunately, a screenshot doesn't give us enough information to investigate

**Comment by JunCores** [comment]
> Unfortunately, a screenshot doesn't give us enough information to investigate

only this controller use Task
`  public async Task<AjaxRspJson> Upload(List<IFormFile> file, string attrName, string sourceId)
        {
            var result = new AjaxRspJson { RspCode = (int)ResultEnum.Success };
            long size = file.Sum(f => f.Length);
            var listDic = new List<Dictionary<string, object>>();
            var attrAll = entityCoreDataAccess.GetEntityAttr(entityName);
            var fileList = new List<EnclosureModel>();
            var hostImg = new SettingGroupBus().GetImgHost();
            foreach (var formFile in file)
            {
                var attr = entityCoreDataAccess.GetSingleAttr(attrAll, $"{entityName}.{attrName}");
                if (attr == null)
                {
                    throw new Exception("不存在该属性");
                }
                var fileExt = GetFileExt(formFile.FileName);
                if (!String.IsNullOrEmpty(attr["atta_format"].ToString()))
                {
                    var extCollection = attr["atta_format"].ToString().Split(',');
                    if (!extCollection.Contains(fileExt))
                    {
                        throw new Exception($"不允许上传{fileExt}后缀文件");
                    }
                }
                var fileDic = new Dictionary<string, object>();
                var time = DateTime.Now;
                var returnPath = Path.Combine("UploadFiles", entityName, attrName, time.ToString("yyyy"), time.ToString("MM"), time.ToString("dd"));
                var path = Path.Combine("wwwroot", returnPath);
                var imgPath = Path.Combine(Directory.GetCurrentDirectory(), path);
                if (!Directory.Exists(imgPath))
                {
                    Directory.CreateDirectory(imgPath);
                }
                var newName = GetFileName(formFile.FileName);
                imgPath = Path.Combine(imgPath, newName);
                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(imgPath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                    var id = Guid.NewGuid().ToString("N");
                    fileDic.Add("ID", id);
                    fileDic.Add("Path", hostImg + Path.Combine(returnPath, newName).Replace("\\", "/"));
                    fileDic.Add("Name", formFile.FileName);
                    listDic.Add(fileDic);
                    var enModel = new EnclosureModel
                    {
                        enclosureid = id,
                        enclosurename = formFile.FileName,
                        source_ent = entId,
                        source_id = sourceId,
                        create_user_id = JwtOperation.GetUserId(userInfo),
                        enclosureurl = Path.Combine(path, newName).Replace("\\", "/"),
                        enclosure_filesize = formFile.Length.ToString(),
                        enclosure_fileext = fileExt,
                        enclosure_origname = formFile.FileName,
                        enclosure_filetype = formFile.FileName
                    };
                    fileList.Add(enModel);
                }
            }
            if (fileList.Count > 0)
            {
                entityCoreDataAccess.SaveEnclosure(fileList);
                result.ObjectData = listDic[0];
            }
            result.RspMsg = "操作成功";
            return result;
        }`

**Comment by Pilchie** [comment]
@javiercn @davidfowl - does the provided code help all all?  Something `IFormFile` based perhaps?

**Comment by javiercn** [comment]
@Pilchie I think it is ultimately impossible to trace this to a framework problem without a minimal repro project or a memory dump. I'm not the most familiar person with te server internals, but I doubt there are things there that can cause a deadlock. @halter73 or @Tratcher can confirm.

Reading the code provided I can't spot anything that would be problematic, but in many cases things that seem innocent end up being the culprit, that's why ultimately a repro or a memory dump is required.

One thing that I would say is that if this were to be a framework problem we would have seen more reports for it at this point.

**Comment by JunCores** [comment]
> I think it is ultimately impossible to trace this to a framework problem without a minimal repro project or a memory dump. I'm not the most familiar person with te server internals, but I doubt there are things there that can cause a deadlock. @halter73 or @Tratcher can confirm.
> 
> Reading the code provided I can't spot anything that would be problematic, but in many cases things that seem innocent end up being the culprit, that's why ultimately a repro or a memory dump is required.
> 
> One thing that I would say is that if this were to be a framework problem we would have seen more reports for it at this point.



> @javiercn @davidfowl - does the provided code help all all? Something `IFormFile` based perhaps?

当我升级 .net runtime 3.1.5,似乎已经4天没出现之前的问题了

**Comment by Pilchie** [comment]
Closing based on lack of information here.  If this happens again, please capture a dump as @javiercn requested above and either re-open, or file a new issue.  Thanks!
