### ISSUE TITLE
.net Core 3.1 interface with the flutter framework request causes a 502 503 error

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/aspnetcore#23770]
Net Core 3.1 requests multiple interfaces simultaneously. It is normal that a **flutter** Framework request will cause a 502 503 error.Net Core 2.1, same code, this seriously affects the production version, I don't know where to start, of course the project has synchronous and asynchronous operations,
The very strange thing is that if I didn't request with the **flutter** framework, I would have no problem with other pressure measurements

**Comment by javiercn** [comment]
@JHeLiu thanks for contacting us.

It is not clear what you are trying to communicate. If you are seeing 502 or 503 responses, can you capture logs or stacktraces for exceptions so that we can try and help you determine what's going on?

**Comment by JHeLiu** [comment]
@javiercn 
No logs?It seems like 502 or 503 did not come into the site at all, it is the framework https://flutter.dev/ request, the stress test software will not
