### ISSUE TITLE
Debug support for typescript inside a razor class library

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#23781]
Is it possible to debug typescript files from a razor class library? I use currently webpack and a source map is generated, too. But the breakpoints in the typescript files inside the razor class library are not hit.

**Comment by javiercn** [comment]
@TFTomSun thanks for contacting us.

Are you talking about debugging from the browser or from Visual Studio?

**Comment by TFTomSun** [comment]
from Visual Studio

**Comment by SteveSandersonMS** [comment]
If the source map is an "inline" one (that is, the source map data is embedded in the generated `.js` file), then it should definitely work.

TBH I would have expected an external source map to work as well, but there are more moving parts in this case so it's believable something might be interfering.

**Comment by TFTomSun** [comment]
@SteveSandersonMS how can I modify the typescript compiler to generate that inline source map? I'm using the typescript msbuild package

**Comment by SteveSandersonMS** [comment]
Did you try configuring it in `tsconfig.json`? https://www.typescriptlang.org/tsconfig#inlineSourceMap

**Comment by samminnella** [comment]
@SteveSandersonMS TypeScript debugging (breakpoints) still not working for me with VS 16.9.3 if the TS source file is in a razor component library. I have tried inline source maps and it still does not work. If the TS file is in the blazor server project debugging works as expected. This is sort of an important thing to have working for obvious reasons.

**Comment by TFTomSun** [comment]
In case someone is interested in a workaround. It's possible to edit and debug linted typescript files when they are linked from the RCL into the Blazor app. I've written a small Target that does this. Simply place it into your Blazor app and reference the RCL that you want to debug directly. The target supports only ProjectReferences but PackageReferences should be easy to support as well.

```xml
<Target Name="CreateLinks" BeforeTargets="BeforeBuild">
		
		<PropertyGroup>
			<LinkedFilesGitIgnorePath>wwwroot\_content\.gitIgnore</LinkedFilesGitIgnorePath>
			<LinkedFilesGitIgnoreContent>*</LinkedFilesGitIgnoreContent>

			<LinkCommand>mklink /J "wwwroot\_content\%(ProjectReference.Name)" "..\%(ProjectReference.Name)\wwwroot"</LinkCommand>
		</PropertyGroup>

		<WriteLinesToFile Condition="Exists('$(LinkedFilesGitIgnorePath)') == false"
						   File="$(LinkedFilesGitIgnorePath)"
						   Lines="$(LinkedFilesGitIgnoreContent)"/>
		<Exec Condition="Exists('wwwroot\_content\%(ProjectReference.Filename)') == false" Command="mklink /J wwwroot\_content\%(ProjectReference.Filename) ..\%(ProjectReference.Filename)\wwwroot"/>
	</Target>

```

**Comment by mkArtakMSFT** [comment]
This should work now.
