### ISSUE TITLE
Test hang: ServerComparison.FunctionalTests

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#23780]
Original issue: https://github.com/dotnet/aspnetcore-internal/issues/3638

Tasks on the heap
![image](https://user-images.githubusercontent.com/6995051/86917638-3d2d3d80-c0da-11ea-9c0e-31cb0ebd359d.png)
Threads
![image](https://user-images.githubusercontent.com/6995051/86917677-59c97580-c0da-11ea-836b-d70b562d2db1.png)

AzDO build
https://dev.azure.com/dnceng/public/_build/results?buildId=720647&view=results

Link to the captured dump:
https://microsoft-my.sharepoint.com/:u:/p/jacalvar/EW8PU2LiFWVPtCMn3ry_Em0BK6UmSVK1LEzewDoUGTasBw?e=5oqEN9

**Comment by BrennanConroy** [comment]
Closing, doesn't seem to have enough info and we don't see hangs in runs for the past few months.
