### ISSUE TITLE
Render Fragment with multiple parameters

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#23790]
I do know there is render fragments that allow one generic parameter.  However, it would be good if there can be a render fragment that can be used that can send back 2 or even 3 parameters.  This would be useful in a case if somebody is creating a component that is looping through 2 areas and needs to send not just one value but up to even 3 of them.

**Comment by SteveSandersonMS** [comment]
Using the one available parameter, you can pass as many values as you want using a tuple. This gives you the same strong typing and ability to give names to each of the values as you'd get if there was a `RenderFragment<T0, T1, T2, T3, T4, ...>`.
