### ISSUE TITLE
Corrupted values when looping through to create components

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#23791]
Here is a sample that returns 4 4 times instead of incrementing by one.

```
@for (int i = 0; i < 4; i++)
{
    <EditForm Model="this">
        @i
    </EditForm>
}
```

In any component, if you use the code you see above, you will see it always returns 4 each time which was the last value of i and not 0, 1, 2, 3 which is expected.

**Comment by SteveSandersonMS** [comment]
People often report this. Unfortunately it's simply the behavior of C# as a language. See https://medium.com/@unicorn_dev/how-to-capture-a-variable-in-c-and-not-to-shoot-yourself-in-the-foot-d169aa161aa6 for details.

Simple workaround:

```
@for (int i = 0; i < 4; i++)
{
    var currentIndex = i;
    <EditForm Model="this">
        @currentIndex
    </EditForm>
}
```

Note that Blazor doesn't control the behavior of C#, so this is not something we could change.
