### ISSUE TITLE
form,header,query add naming policy

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#23802]
### Is your feature request related to a problem? Please describe.
I hope that the data of header, form and query can support the naming policy, just like JSON data

**Comment by pranavkm** [comment]
@Varorbc can you elaborate on what you're trying to do and what is it that's blocking you?

**Comment by Varorbc** [comment]
My model class looks like this:

class OauthParameters
{
    public string ClientId {get; set;}

    public string ResponseType {get; set;}

    public string RedirectUri {get; set;}
}
so I'd like to bind query strings like client_id, response_type and redirect_uri to it.

If the data is JSON, I just need to add a naming policy. Query header form, can you also add a naming policy?

.AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver()
    {
        NamingStrategy = new SnakeCaseNamingStrategy()
    });

**Comment by pranavkm** [comment]
This is not a feature we plan on adding. The closest we have is to supply a name via one of the model binding attributes e.g. `[ModelBinder(Name = "response_type")] public string ResponseType { get; set; }`

**Comment by Varorbc** [comment]
@pranavkm I need a global configuration of naming rules, rather than binding them one by one. If I had 100 models, it would be a huge job

**Comment by Varorbc** [comment]
@pranavkm Is it possible to reopen the issue and move to the backlog

**Comment by pranavkm** [comment]
@Varorbc adding features to model binding are high cost and have a high risk of breaking users. We generally do not consider new features in that that area unless we have very compelling reasons. Unfortunately at current, this issue wouldn't meet our bar.
