### ISSUE TITLE
Build incrementalism goes wrong for precompressed files after each package update

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#23808]
---

**IMPORTANT NOTE:** If you're using Blazor 3.2.x, **this issue does not affect you**. Even if you see an error message that looks the same, **your issue has a different underlying cause**. This specific issue only affects the 5.0 branch. Please don't report 3.2.x issues on this thread.

---

We used to have this problem before, then fixed it, and now it's back (perhaps since the re-plat on 5.0).

Each time I update the `master` branch to pull in new incoming packages, all my Blazor WebAssembly apps stop working with integrity check errors. To fix it, it's necessary to delete the `bin`/`obj` directories in the project then rebuild.

The underlying reason is that the existing build output contains pairs like this:

```
-rwxr-xr-x 1 4096   16256 Jul  8 06:58 System.Net.dll
-rw-r--r-- 1 4096    8591 Jul  8 18:03 System.Net.dll.gz
```

Notice how the `.dll.gz` file is newer than the `.dll` file. However,

 * System.Net.dll is version 5.0.0-preview.8.20357
 * System.Net.dll.gz is version 5.0.0-preview.8.20354

... it's an older version! I think that what happens is that when upgrading to newer packages, it's possible that the locally-placed `.gz` file was created more recently than the externally-created uncompressed file.

This issue won't just affect people working against our sources. It will also affect real apps, because every time you change version on a NuGet dependency, it's possible that your precompressed file was locally created more recently than the uncompressed file you're getting from the external source.

**Comment by pranavkm** [comment]
This was resolved as part of the WebAssembly SDK. We now use the absolute path as part of the input path calculation.
