### ISSUE TITLE
Consider porting https://github.com/dotnet/aspnetcore/issues/19050 fix to 3.1

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23816]

**Comment by pranavkm** [comment]
cc @captainsafia \ @mkArtakMSFT

**Comment by captainsafia** [comment]
As part of this port, we want to include [the PR I submitted earlier](https://github.com/dotnet/aspnetcore/issues/19050) that ensures that disconnects happen on all browsers and the new PR to resolve the issue with the reconnect modal showing on Firefox.

**Comment by captainsafia** [comment]
Backport is completed.
