### ISSUE TITLE
Create a .editorconfig that abides by our coding standards

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#23812]
- [ ] Requires License header
- [ ] `_` prefixed private variables
- [ ] insert_final_newline = true

**Comment by paulomorgado** [comment]
Create the editorconfig as much complete as possible.

The way it is makes it very hard to collaborate as it doesn't shield from the developer's preferences in Visual Studio.

**Comment by allisonchou** [comment]
We [have an editorconfig](https://github.com/dotnet/aspnetcore-tooling/blob/main/.editorconfig) now, so closing out this issue. 😄
