### ISSUE TITLE
Can't get instance component after render parent 

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#23823]
I want get instance child component by `@ref` after `true` my condition but can't and `prop is null` 

### Code not error
```
 <Child @ref="MyChild" />

<button @OnClick="(() => MyChild.SomeFunctionCall)"> Call Child Function </button> 
@code{
   public Child  MyChild;
}

```

### Code error
```
if(isLoad) // condition line
{
   <Child @ref="MyChild" />
}

<button @OnClick="(() => { isLoad = true;
                                              StateHasChanged();
                                              MyChild.SomeFunctionCall; //call function child
                                            })"> Click me </button>
@code{
   public Child  MyChild;
}

```

> I want after call `StateHasChanged` run **condition line** after return to **call function child**

### If change code to below after `two click work `

```
<button @OnClick="(() => { 
                                           if(!isLoad){
                                              isLoad = true;
                                              StateHasChanged();
                                            }else
                                                 MyChild.SomeFunctionCall;
                                            })"> Click me </button>
```

### If change call function child in condition always **null** 

```
if(isLoad) // condition line
{
   <Child @ref="MyChild" />
    MyChild.SomeFunctionCall;
}
```

**Comment by mrpmorris** [comment]
The ref cannot be set by Blazor until after the component it refers to has been rendered, up until then it doesn't exist.

That's why the second click of your button works. First render it is null, then it is created and rendered, then the second click has a reference to work with.

You should execute your child function in OnAfterRenderAsync.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like your function call is incomplete. You're missing the parentheses:
`MyChild.SomeFunctionCall()`.
