### ISSUE TITLE
Very strange buffering with messages to a particular group

### ISSUE THREAD

**Issue by Prinsn** [dotnet/aspnetcore#23824]
### Describe the bug
We currently are using SignalR, serverless, to do messaging to our client app.

Everything appears to work fine, and has been working fine, for months.

However, on the latest new Azure Function that we've added, it's been noted that messages targeting group "3" will get buffered until any other group has a message _or_ 3 messages are sent to group 3, at which point the client will receive all messages simultaneously.

It has been otherwise isolated to group 3 (in lieu of actually testing every number, but no one has observed it except on 3, across a random sampling of other numbers), and is _always_ of the same pattern of having 2 messages buffered and the third having all three received by the server.

The client is also connected via what is presented as a websocket in Chrome's dev tools (I don't know if that means it is correctly a WS or if it just displays WS and it can be in any fallback state)

### To Reproduce

I don't have a way to offer reproduction because it's between an angular consumer (as the only means of even being aware that the messages get sent) and the backend which is doing nothing but sending the message, but it is peculiar to the point that it is reproducible in the project itself between multiple members.

After this occurs, the behavior is no longer observed, only recurring on a server restart.

### Exceptions (if any)

No exceptions, or even wrong behavior.  Once the client receives all of its messages, it responds to all of them exactly as if the server just sent three distinct messages.

### Further technical details
- ASP.NET Core version
Dependency is at 2.2.8 for server for both ASP and base .NET Core
Does not exist on the functions, but function dependencies are at 2.2.0 for .NET Core, as well as the SignalR project.
For the project, SignalR.Management is at 1.2.3, and Azure.WebJobs.Extensions.SignalRService is at 1.0.2

- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS 2019, various, approx Version 16.6.2

**Comment by BrennanConroy** [comment]
You might want to move this issue to https://github.com/Azure/azure-signalr
Also, ASP.NET Core 2.2 is out of support, you should try moving to 3.1 or downgrade to 2.1.

**Comment by Prinsn** [comment]
Wasnt aware there was azure distinct.

But... 2.1 is in support but 2.2 isnt?

**Comment by BrennanConroy** [comment]
> But... 2.1 is in support but 2.2 isnt?

Correct https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle

**Comment by Prinsn** [comment]
Weird.

Well, thanks for the information.

I'll look into Azure repo and see if that's not the cause and post there.

**Comment by BrennanConroy** [comment]
Issue moved to https://github.com/Azure/azure-signalr/issues/963
