### ISSUE TITLE
How to stream live concerts from device and show to client using webrtc?

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/aspnetcore#23849]
I need to create a web application using .net core to stream from some device that will record some concerts and etc. I need to stream these concerts from the device and show it to the user of the website. I kinda read about webrtc and it looks helpful for my specific requirement. Anybody can give me solutions on how to manage these processes and make concerts live for the user. Thanks!

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the asp.net-core tag to reach a wider audience.
