### ISSUE TITLE
AddHttpMessageHandler not using correct scope in Blazor Wasm app

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#23847]
### Describe the bug
When using Microsoft.Extensions.Http AddHttpClient and AddHttpMessageHandler<T>, the instance of T belongs to a different ServiceProvider than the ServiceProvider used to generate a Blazor page - even though T is registered as scoped.

### To Reproduce
Create a new Blazor WASM project

Add NuGet reference Microsoft.Extensions.Http

Create a class as follows
```
	public class MyDelegatingHandler : DelegatingHandler
	{
		private readonly IServiceProvider ServiceProvider;

		public MyDelegatingHandler(IServiceProvider serviceProvider)
		{
			ServiceProvider = serviceProvider;
		}

		protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{
			Console.WriteLine("Http service provider hash = " + ServiceProvider.GetHashCode());
			return base.SendAsync(request, cancellationToken);
		}
	}
```

In `Program.cs` remove the registration of HttpClient and replace it with the following
```
			builder.Services.AddScoped<MyDelegatingHandler>();
			builder.Services
					.AddHttpClient("local", c => c.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
					.AddHttpMessageHandler<MyDelegatingHandler>();
```

Edit `FetchData.razor`
Remove the injection of HttpClient and relace it with
```
@inject IHttpClientFactory HttpClientFactory
@inject IServiceProvider ServiceProvider
```

Replace `OnInitializedAsync` with the following code
```
protected override async Task OnInitializedAsync()
{
	var httpClient = HttpClientFactory.CreateClient("local");
	Console.WriteLine("Page service provider hash = " + ServiceProvider.GetHashCode());
	forecasts = await httpClient.GetFromJsonAsync<WeatherForecast[]>("sample-data/weather.json");
}
```

Now run the app, open the console window in the browser, and navigate to the Fetch Data page. 

### Expected
The hash code for the page and the http delegate should be the same.

### Actual
They are different, therefore they are both running within separate IServiceProvider containers.

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

HttpClientFactory controls the lifetime of the clients and the handlers. The recommendation is to register the handlers as transient.

**Comment by mrpmorris** [comment]
HI @javiercn - Is HttpClientFactory registered as Singleton or Scoped?

**Comment by javiercn** [comment]
@mrpmorris IHttpClientFactory is a singleton I believe, but it is best to check the sources.

**Comment by mrpmorris** [comment]
@javiercn I'm afraid your suggestion isn't a suitable solution. It seems that a Transient service will resolve dependencies as Transient too, and so not receive a reference to the service scoped to the current user.

I'll report it in another repository, thanks.
