### ISSUE TITLE
Add support for partial attribute name selector (current not a css selector) , and build in  class/attr taghelper

### ISSUE THREAD

**Issue by John0King** [dotnet/aspnetcore#23844]
### Is your feature request related to a problem? Please describe.
`class` is one of the thing we dealing with it every day in razor, it is a sample that I inspired by angular's class helper and attributes helper
```razor
<a class="active">link</a> and it should be
@if(condition == true)
{
    <a class="active">link</a>
}
else
{
    <a class="active">link</a>
}
``` 

and I create a `ClassHelperTagHelper` for doing this

```razor
 <a class.active="condition == true">link</a>
```

but I facing a probelm:   if I target '*'  then  all html tag  must either be `<tag ></tag>` or `<tag />`  the html5 element like `<meta charset="utf-8">` are not allowed.

### Describe the solution you'd like

support a new "partial attribute name selector" 
```
"[^class.]"   will match  <tag class.on  class.be  class.good />
"[$-class]"  will match <tag  a-class  b-class c-class />
this will also support  `[^attr.^='val-']`    and will match  <tag attr.for='val-good' />
```

and  **add build in Class Helper and Attr Helper**

### Additional context

this is my `ClassHelperTagHelper`

```C#
[HtmlTargetElement(Attributes = "[k-helper]", TagStructure = TagStructure.Unspecified)]
    public class ClassHelperTagHelper : TagHelper
    {
        private readonly HtmlEncoder _htmlEncoder;
        public ClassHelperTagHelper(HtmlEncoder encoder)
        {
            _htmlEncoder = encoder;
        }
        public const string ClassDicPrefix = "class.";

        [HtmlAttributeName("classes", DictionaryAttributePrefix = ClassDicPrefix)]
        public IDictionary<string, bool?> Classes { get; set; } = new Dictionary<string, bool?>(StringComparer.Ordinal);

        public override int Order => 100;
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            var classes = this.Classes.Where(x => x.Value == true).Select(x => x.Key);
            foreach(var key in classes)
            {
                output.AddClass(key, _htmlEncoder); // may I ask to remove the htmlencoder requirement ?
            }

            var notClasses = this.Classes.Where(x => x.Value == false).Select(x => x.Key);
            foreach(var c in notClasses)
            {
                output.RemoveClass(c, _htmlEncoder);
            }
            // if  the value is null, then we don't process it , so  if it exists will keep exists 
        }
    }

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @NTaylorMullen can you help with this? Thanks!

**Comment by NTaylorMullen** [comment]
@John0King are you just trying have your TagHelper attach to some attribute name prefix? If that's the case you can suffix your HtmlTargetElement attributes with `*` to denote that: https://github.com/dotnet/aspnetcore/blob/f5b6039add50ea84ddb151cd6daf5207119dc116/src/Mvc/Mvc.TagHelpers/src/FormActionTagHelper.cs#L26

Also, if you want to automatically capture all of those attributes in a dictionary you can also utilize a Dictionary<string, string> object to represent that as well: 
https://github.com/dotnet/aspnetcore/blob/f5b6039add50ea84ddb151cd6daf5207119dc116/src/Mvc/Mvc.TagHelpers/src/FormActionTagHelper.cs#L155

**Comment by John0King** [comment]
@NTaylorMullen   Thank for the answer,  and  will  the  `class helper `  and `attr helper`  be a build in `TagHelper`  in asp.net core 5

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Thank for the answer, and will the `class helper ` and `attr helper` be a build in `TagHelper` in asp.net core 5.
> consider of this case :

We don't currently have the bandwidth to add that feature for .NET 5 but we definitely encourage ASP.NET Core users to implement and distribute that level of feature as class libraries for all to use!
