### ISSUE TITLE
Blazor Page: Ability to denote a route constraint without mapping to a Parameter

### ISSUE THREAD

**Issue by Rauce** [dotnet/aspnetcore#23846]
I would like to be able to denote a route constraint in a Blazor page without having to map to an actual parameter.

For example, the Blazor documentation gives the following route constraint example:

```
@page "/Users/{Id:int}"

<h1>The user Id is @Id!</h1>

@code {
    [Parameter]
    public int Id { get; set; }
}
```

It would be useful to not have to map this to a parameter, but still match the constraint, something like this:

```
@page "/Users/{:int}"

<h1>I don't care what the id is.</h1>
```

Why? I have various routes in my Blazor app as follows:

/{guid}/Page1
/{guid}/Page2
/{guid}/Page3

The guid here represents a context (i.e. an employee, organisation, whatever), which is parsed and processed in the `Layout` of these pages. I need the guid to be in the URL so that the context can be restored from a direct link or browser refresh. But I am currently having to create a pointless unused parameter in Page1, Page, Page3, etc. to make the route matching work.

Just a suggestion!

**Comment by javiercn** [comment]
@Rauce thanks for contacting us.

We don't think there is a lot of value in supporting this at the cost of deviating from the common set of patterns used across asp.net core for routing. Would simply using a "discard" parameter not work? After all, you might not care about it on your component, but for routing purposes you have a "parameter"
