### ISSUE TITLE
There is a problem with the handling of the base address in the Blazor project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23858]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1106045/blazor项目对基地址的处理有问题.html)._

---
I have a Blazor website with a virtual path of "/Home" and its base address is "/Home/"
An exception occurs when I ask "http://sf0.xin:8100/Home?asd".

---
#### Feedback Bot on 7/8/2020, 01:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

The trailing slash is significant and should be removed. @SteveSandersonMS can confirm.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
