### ISSUE TITLE
Properties/serviceDependencies.json being added

### ISSUE THREAD

**Issue by csijake** [dotnet/aspnetcore#23851]
I'm not sure when or why this started happening, but all of a sudden my ASP.NET Core projects are generating two new files on build:

### serviceDependencies.json

```json
{
  "dependencies": {
    "secrets1": {
      "type": "secrets"
    }
  }
}
```

### serviceDependencies.local.json

```json
{
  "dependencies": {
    "secrets1": {
      "type": "secrets.user"
    }
  }
}
```

## Questions / Issues

1. Why did this start happening all of a sudden? I haven't changed framework versions or upgraded VS recently.
2. Are these files supposed to be checked in to source control, or ignored? (They currently aren't in the [VisualStudio .gitignore template](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore).)
3. Is there a setting that can prevent them from being generated?

## Technical Information

VS 2019 Pro - Version 16.6.1  
Project's target framework: `netcoreapp2.2`  
`dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@csijake thanks for contacting us.

These files are related to a Visual Studio feature, it is not something that the ASP.NET Core team produces. You read the details about it [here](https://devblogs.microsoft.com/aspnet/configuring-azure-services-and-emulators-using-visual-studio/).

I'm not sure if there is a way to turn it off. If you want to get a better and faster answer, file an issue through the Visual Studio [report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) dialog.

**Comment by Pilchie** [comment]
Closing as external.
