### ISSUE TITLE
Unexpected (?) memory behaviour when using multiple route attributes with route parameters

### ISSUE THREAD

**Issue by siimv** [dotnet/aspnetcore#23850]
### Describe the bug
I use attribute routing and I have quite many controllers. Each controller has multiple routes that it should match, for example:
```
[Route("test")]
[Route("{language:length(2)}/test")]
[Route("{version:int}/{language:length(2)}/test")]
```
In my case, this results about 2.8GB memory usage after first request (which is also slow, next requests respond fast). From the memory profiler I see a lot of objects related to `DfaNode` and `Endpoint` (also many related collections).

It doesn't seem to matter which type of constraints I use (built-in or custom) and removing the constraints (leaving just `{language}` doesn't affect much. It also doesn't matter if I add routes through `Route` attributes or use some conventions to do that.

If I use any single one (or any two) of the those routes, then memory consumption is acceptable. Adding one more route increases memory consumption even more.

Now, I understand that having a lot of routes (even more, having multiple "parallel routes") increases memory usage due to route parsing and matching, but so high usage seems a little bit odd.

### To Reproduce
Repro: https://github.com/siimv/AttributeRouteMemoryUsage

It contains controller files (each has 63 controllers having 3 methods each):
- TestControllersWithSimpleRoute, memory ~30mb
Using routes `[Route("test1")]`
- TestControllersWithSimpleAndSingleConstrainedRoute, memory ~80mb
Using routes ``` [Route("test1")]
    [Route("{language:length(2)}/test1")]```
- TestControllersWithMultipleConstrainedRoute, memory ~139mb
Using routes ```[Route("{language:length(2)}/test1")]
    [Route("{version:int}/{language:length(2)}/test1")]```
- TestControllersWithSimpleAndMultipleConstrainedRoutes, memory ~2.5gb
Using routes ```[Route("test1")]
    [Route("{language:length(2)}/test1")]
    [Route("{version:int}/{language:length(2)}/test1")]```

### Further technical details
- ASP.NET Core version 3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by Pilchie** [comment]
Also tagging @JamesNK here.

**Comment by siimv** [comment]
I did some more investigation and found `DfaGraphWriter` class (since memory was related to the `DfaNode`-s). And the graph kind of explodes when introducing route constraints.

Here are some most simple examples:
_I didn't include here the route `/route-graph`, as it is single controller method defined as `[Route("/route-graph"), HttpGet]`_ 

Normal usage:
````C#
[Route("test1")]
public class Test1Controller : ControllerBase
{
    [Route("method-1"), HttpGet]
    public IActionResult Get()
    {
        return Ok();
    }
}

[Route("test2")]
public class Test2Controller : ControllerBase
{
    [Route("method-2"), HttpGet]
    public IActionResult Get()
    {
        return Ok();
    }
}
````
This produces nice simple graph (_graph_simple.txt_ in attachments).

When adding single constrained route, like:
```C#
[Route("test1")]
public class Test1Controller : ControllerBase
{
    [Route("method-1"), HttpGet]
    public IActionResult Get()
    {
        return Ok();
    }
}

[Route("test2")]
[Route("{language:length(2)}/test2")]
public class Test2Controller : ControllerBase
{
    [Route("method-2"), HttpGet]
    public IActionResult Get()
    {
        return Ok();
    }
}
```
It produces kind of multiplied graph, containing nodes like _/test2/test2/method-2_, _/test1/test2/method-2_,  _/route-graph/test2/method-2/_, etc.
It doesn't matter how I add the routes - method and/or controller level and prefixed with / or not.
Graph is in attachment _graph_complex.txt_.

Hope this helps a bit.

[graph_complex.txt](https://github.com/dotnet/aspnetcore/files/4960997/graph_complex.txt)
[graph_simple.txt](https://github.com/dotnet/aspnetcore/files/4960999/graph_simple.txt)

**Comment by javiercn** [comment]
@siimv thanks for the details. We've already traced this to an issue when there are literal segments after a starting parameter segment. You can work around it for now by preceding all parameter segments with a literal prefix.

We are working on a fix and we'll likely patch it in a future release.

**Comment by siimv** [comment]
Thanks for the tip, I was looking for workaround, but didn't find it yet. 

We are migrating our applications to .NET Core 3.1 currently and have to think if we wait for the patch before finishing or try to work around it.
