### ISSUE TITLE
Unable to add reference of Library project in Client project in Blazor webassembly 

### ISSUE THREAD

**Issue by arunc700** [dotnet/aspnetcore#23866]
Hi Team, I am trying to add my library project in Client project but it is not adding successfully. it showing warning as you can see in attached screenshot project. Could you please help?

![image](https://user-images.githubusercontent.com/48315448/87191332-d6926480-c311-11ea-93ba-bfb65ae0f2ae.png)

![image](https://user-images.githubusercontent.com/48315448/87191428-06da0300-c312-11ea-964e-30fb1f33e035.png)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
