### ISSUE TITLE
Application immediately shuts down due to non-existent "app_offline.htm"

### ISSUE THREAD

**Issue by BennieCopeland** [dotnet/aspnetcore#23860]
### Describe the bug
My ASP.Net Core 3.1 self contained application using ANCMv2 shuts down after one second of starting up. In the event log it states that it shut down after detecting "app_offline.htm" when no "app_offline.htm" file exists in the application root directory or higher. This happens both in process and out of process.

### To Reproduce
I _suspect_ it might be caused by updating several LiteDb files located in the application root directory. It appears to stop happening once those files stop being written to. Running procmon, I see repeatedly:
```
FASTIO_NETWORK_QUERY_OPEN {approot}\app_offline.htm NAME NOT FOUND
IRP_MJ_DIRECTORY_CONTROL {approot} SUCCESS
```
until this message where upon it seems to fail
```
IRP_MJ_DIRECTORY_CONTROL {approot} NOTIFY CLEANUP
```

I can't find anything else very relevant 

### Further technical details
Running on Windows 2012 R2 with IIS 8.

**Comment by shirhatti** [comment]
Could you please collect and share [enhanced diagnostic logs](https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?#enhanced-diagnostic-logs) from ANCM?
