### ISSUE TITLE
[Blazor WebAssembly] Component can refresh all components

### ISSUE THREAD

**Issue by ShadyNagy** [dotnet/aspnetcore#23879]
It will be good to have a refresh or rerender function to be called in the component to force rerender all other components.

I am trying to do login then need all components to change the status to be logged in but that not happened as I need to make the custom event to handle that.

It will be better to call one function so rerender all the components.

**Comment by javiercn** [comment]
@ShadyNagy thanks for contacting us.

I saw that you and @SteveSandersonMS had a discussion on the PR, should we just close this issue?

**Comment by ShadyNagy** [comment]
@javiercn, yes thanks :)
