### ISSUE TITLE
[Blazor] Blazor WebAssembly Unable to expand the Exception variable in try catch while Debuggging

### ISSUE THREAD

**Issue by syedqutub** [dotnet/aspnetcore#23871]
In a Blazor WebAssembly app. while debugging, can not expend the exeption variable in try catch. even the `Console.WriteLine(e)` does not work.
`try{
}catch(Exception e){
Console.WriteLine(e);
}`

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#20105
