### ISSUE TITLE
Enhance default template with identity

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#23877]
I believe it's a good practice to not use `IdentityUser` class directly, but to create a class (commonly named `ApplicationUser`) that inherits from `IdentityUser`.

```csharp
public class ApplicationUser : IdentityUser
{
}
```

One of the benefits that come to mind (not sure if there are other benefits too) is for easier customization later on (adding new properties to the default Identity).
With the current template, I believe many developers will stick to keep using `IdentityUser`, then they need to customize it. It's harder in my opinion to add the new `ApplicationUser` class in an existing large app that uses `IdentityUser`.

If the default template has `ApplicationUser` class that's being used, developers will usually stick with it, and that will be better for them later.

**Comment by blowdart** [comment]
We used to do that, but we had lots of comments about how noisy the templates were, and how many classes were added, so it went away to address those.

As you can do it yourself, I'm afraid this is by design.
