### ISSUE TITLE
Blazor: Server-side passing of data between pages

### ISSUE THREAD

**Issue by wondering639** [dotnet/aspnetcore#23884]
### Is your feature request related to a problem? Please describe.
Feature request, related to this issue:
Example: I have a page _add_ which will add an item to the database on _OnValidSubmit_ and then redirect to a page _list_. On the page _list_ I want to show a success message like "item added".

I want to show the success message "item added" only once. If the user refreshes the page, it shall be gone. So a route parameter which is passed via the URL seems to be the wrong thing, as this will survive refreshes.

Using session involves the risk that the _list_ page is called between the navigation from the _add_ page to the _list_ page. Besides that with direct passing of data, the code would be easier (see solution)

### Describe the solution you'd like
NavigationManager.NavigateTo("/list", someCustomObject);
someCustomObject shall be directly passed to the _list_ page in memory, not via URL. (remember, this feature request is intended for server-side Blazor)

**Comment by Stryxus** [comment]
Why not just make a ClientState class? That is what i did although im not of use on how it worked because iv converted to WebAssembly since then.

**Comment by wondering639** [comment]
> Why not just make a ClientState class? That is what i did although im not of use on how it worked because iv converted to WebAssembly since then.
Can you elaborate more on this? I yet can't imagine what is your idea.

**Comment by NatanBagrov** [comment]
@wondering639 You create a class (for example `ClientState`), register it as Singleton (`services.AddSingleton(...)`), and inject it through your app.
Think of this class as a dictionary (keys to objects).

When you need to switch pages, you just add the data you wish to store to that class, and pop it in your new page.
This is the simplest solution...

**Comment by mkArtakMSFT** [comment]
Looks like folks have answered this already. Thanks everyone!

**Comment by wondering639** [comment]
Thank you all for your support! Note that Singleton survives a refresh. For me a scoped service fits better. But yes, then no addition to Blazor is needed, as this is already built-in :-)

**Comment by NatanBagrov** [comment]
> Thank you all for your support! Note that Singleton survives a refresh. For me a scoped service fits better. But yes, then no addition to Blazor is needed, as this is already built-in :-)

I just gave you the simplest most straight forward way. Of course you should alter it to fit your needs :) Good luck
