### ISSUE TITLE
[Identity] The default UI for login request for Email, but in the code behind (post) uses the email as UserName for signing in

### ISSUE THREAD

**Issue by NO1225** [dotnet/aspnetcore#23887]
When using the Visual studio to make a new asp.net core app with authentication, the default UI implemented for the signIn request for an email, but in the code behind it submit the email instead of the user name, as you can see in line 73 in this file 
https://github.com/dotnet/aspnetcore/blob/53682c0548d7449e2b760825fbaa630a0a90d25e/src/Security/samples/Identity.ExternalClaims/Pages/Account/Login.cshtml.cs

I think searching for the user related to that email then using it in signing in is a better approach in making the default UI more useful

**Comment by blowdart** [comment]
This is by design. To keep things simple in the templates we treat the email address and the username as the same, and syncronise them.

If you want to treat them seperately you need to scaffold out and change the generated UI.
