### ISSUE TITLE
Signalr Java AutoConnect, OnConnected Event and Ondisconnect Event

### ISSUE THREAD

**Issue by JLesuperb** [dotnet/aspnetcore#23890]
### Is your feature request related to a problem? Please describe.
With Signalr Java we haven't an event on connection change, on connect or on disconnect.

### Describe the solution you'd like
we can have an option for auto reconnect with on connect event and disconnect event

**Comment by BrennanConroy** [comment]
OnConnect is observable by Start returning successfully. OnDisconnect has the OnClosed callback that you register for.

Auto reconnect is being tracked by https://github.com/dotnet/aspnetcore/issues/8711
