### ISSUE TITLE
Razor and HTML hovers don't work in CodeSpaces until edit

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#23904]
![image](https://user-images.githubusercontent.com/14987221/87336678-149cad80-c4f7-11ea-901a-fb24c11a0ec7.png)
But it does work for C#:
![image](https://user-images.githubusercontent.com/14987221/87336937-7ceb8f00-c4f7-11ea-89f6-3ca9b8ff7c58.png)
HTML hovers seem to work again if an edit is made to the file.

**Comment by NTaylorMullen** [comment]
Closing as duplicate of: https://github.com/dotnet/aspnetcore/issues/23905 just due to amount of detail.
