### ISSUE TITLE
FAR in LiveShare doesn't work

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#23909]
![image](https://user-images.githubusercontent.com/14987221/87339941-3c424480-c4fc-11ea-96de-6d2a3f1bcc7f.png)
1. New Blazor WASM app.
1. Open NavMenu.Razor
1. FAR on collapseNaveMenu inside code block.

**Comment by NTaylorMullen** [comment]
@TanayParikh Do we already have a GitHub issue for this to dupe against?

**Comment by TanayParikh** [comment]
Yep: https://github.com/dotnet/aspnetcore/issues/23723
