### ISSUE TITLE
Backing documents being shown for Razor files in CodeSpaces and using directive unnecessary from _Imports.razor

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#23903]
Note NavMenu.razor.g.cs.

![image](https://user-images.githubusercontent.com/14987221/87332398-5a09ac80-c4f0-11ea-92af-72811548eedc.png)

**Comment by NTaylorMullen** [comment]
If the fix for this is as simple as generating an extra pragma warning disable around our using statements then this should be a small if not an XS. However, if that doesn't work the cost of this will increase.

**Comment by ryanbrandenburg** [comment]
VS seems to ignore pragmas for this particular code once I hacked my changes from AspNetCore into the AspnetCore-Tooling experimental instance. I also found [this issue](https://github.com/dotnet/roslyn/issues/45966) (filed not long after this) which seems to imply that erroneously showing these warnings is not a Razor-specific problem.

**Comment by ryanbrandenburg** [comment]
Of note, at least on latest VS Master this doesn't have to be CodeSpaces, regular local does it too.

**Comment by NTaylorMullen** [comment]
This should be resolved once we move to pull based diagnostics

**Comment by TanayParikh** [comment]
Confirmed fixed via pull-based diagnostics (confirmed locally).
