### ISSUE TITLE
Codespaces HTML Hovers don't work until changes made in file

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23905]
1. `dotnet new blazorserver`
2. Open `Counter.razor`, hover over `<h1>` on line 3. => No hover result
3. Make some changes in the file, save. Hover over `<h1>` again => Hover results

Expected:
![image](https://user-images.githubusercontent.com/14852843/87337114-c936cf00-c4f7-11ea-80b4-a3ba1feb43a4.png)

Thanks @ryanbrandenburg

**Comment by ajaybhargavb** [comment]
I tried this out and I am getting hovers even the first time.

**Comment by NTaylorMullen** [comment]
> I tried this out and I am getting hovers even the first time.

Definitely odd. Will probably have to debug through to see if the hover endpoint in WTE is being called. Can easily verify by looking at the HTML LanguageServerClient logs in the output pane

**Comment by ajaybhargavb** [comment]
I take it back. I tried this locally. Didn't see codespaces in the title.

**Comment by allisonchou** [comment]
Given Codespaces isn't a priority, I'm going to close out this issue for now, feel free to re-open if deemed necessary.
