### ISSUE TITLE
VS LSP: Typing @{ results in @__builder{}

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#23908]
This is a pretty jarring experience.
Typing `@{` in a .razor document results in `@__builder{}` due to our current completion commit behavior. 

We do some special magic to workaround this in VSCode. We should do something similar in VS.

**Comment by NTaylorMullen** [comment]
Hmm, we should investigate removing commit characters from our completion items if we only have `@` in the document

**Comment by ryanbrandenburg** [comment]
@TanayParikh had to revert my fix. It seems that IsIncomplete is not yet respected, and without it `@DateT`<pause>Enter inserts empty text (result `@`).

**Comment by NTaylorMullen** [comment]
If we can't fix this now due to lacking CoreEditor dependencies please talk with @AmadeusW to find the VSTS issue and move this issue to blocked in progress

**Comment by ryanbrandenburg** [comment]
The story @AmadeusW reported was https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1142478.

**Comment by TanayParikh** [comment]
Another way this issue materializes.

Type `@(`. Depending on the speed of completion, we could get the completion list after `@`, resulting us to commit the first item with the `(` commit character, instead of the intended explicit expression.

![ExplicitExpression](https://user-images.githubusercontent.com/14852843/88351226-6d93ef00-cd0a-11ea-8bb6-ca213c49d1c7.gif)

**Comment by TanayParikh** [comment]
Works with `<` and ` ` as well.

![LessThanCompletion](https://user-images.githubusercontent.com/14852843/88351320-b6e43e80-cd0a-11ea-8148-d4c6f7ee9aa3.gif)

**Comment by ajaybhargavb** [comment]
@TanayParikh, we should probably file a separate issue for what you are seeing. The fixes for VS and VSCode will be different.

**Comment by TanayParikh** [comment]
> @TanayParikh, we should probably file a separate issue for what you are seeing. The fixes for VS and VSCode will be different.

Sure thing; https://github.com/dotnet/aspnetcore/issues/24267

**Comment by ryanbrandenburg** [comment]
I believe that [this PR](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/262002) should either fix this issue or allow us to fix it. So leaving this marked as blocked until then. His estimate was some time next week.

**Comment by NTaylorMullen** [comment]
This is no longer blocked is it?

**Comment by NTaylorMullen** [comment]
Should this be moved into inprog?

**Comment by TanayParikh** [comment]
Repros in codespaces still.

**Comment by NTaylorMullen** [comment]
> Repros in codespaces still.

And now you beat me!
