### ISSUE TITLE
Trying to compile the source code of asp.net core, execute the restore command, and report the following error (尝试自己编译asp.net core的源代码，执行restore 命令，报以下错误)

### ISSUE THREAD

**Issue by MrLBQ** [dotnet/aspnetcore#23919]
Failed to install dotnet runtime '' from public location.
D:\aspnetcore-master\build.ps1 : The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.
At line:1 char:126
+ ... ulture = '';& 'D:\aspnetcore-master\build.ps1' -all -nobuild -restore ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (LASTEXITCODE:String) [build.ps1], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,build.ps1

**Comment by pygyme** [comment]
## 1. 安装最新Git for Windows，并下载源码

1.1  从 https://git-scm.com 下载最新版本，并安装好

1.2 下载源码
```
git clone --recursive https://github.com/dotnet/aspnetcore
```
1.3 切换分支
```
git checkout v3.1.6
```

## 2. 安装Visual Studio相关组件
```
PS D:\aspnetcore> .\eng\scripts\InstallVisualStudio.ps1 -Edition Professional
```
注：即使你已经安装Visual Studio，也还是使用这个脚本再次安装，否则会因为缺少组件，而导致错误

## 3. 安装Node.js和OpenJDK

3.1 Node.js
从 https://nodejs.org 下载最新版本，安装并配置淘宝npm镜像

3.2 OpenJDK
从 https://adoptopenjdk.net 下载 OpenJDK 11 最新版本，安装并设置 JAVA_HOME 环境变量

## 4. 还原整个项目

由于众所周知的网络问题，在进行 restore 时，请使用代理服务器。

4.1 配置代理服务器

在 CMD 或 PowerShell 里面，执行以下命令进行配置：
```
set http_proxy=127.0.0.1:12345; set https_proxy=127.0.0.1:12345;
```
注：记得替换命令中的代理地址

4.2 还原项目

```
PS D:\aspnetcore> .\restore.cmd
```

经过上述操作，应该能够正常还原和编译项目。

**Comment by dougbu** [comment]
@Yuta-K19418 now that #25418 / 5e60fb1a92d7273dcbd83ca73ae15c82495269e2 is merged, is anything more needed before we close this issue❔

**Comment by niufwshd** [comment]
I meet the same problem today!

**Comment by dougbu** [comment]
@niufwshd please open a new issue describing the details of your problem. We should have closed this one some time ago.
