### ISSUE TITLE
Publish issue: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'

### ISSUE THREAD

**Issue by Equanimaster** [dotnet/aspnetcore#23913]
### Static HTML included as partial Throw error on Publish.
Had following code that read /Content/Home/en/*.html
And include it as <partial>

`@{
    string path = "/wwwroot/Content" + Model;
    DirectoryInfo di = new DirectoryInfo("." + path);
    FileInfo[] files = di.GetFiles("*.html", SearchOption.AllDirectories);

    foreach(FileInfo file in files)
    {
        <partial name="~@path/@file.Name" />
    }
}`

On debugging environment everything works fine.
On Publish: have the next error:
**InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery at line <partial name="~@path/@file.Name" />**

### To Reproduce

https://github.com/Equanimaster/AntiforgeryIssue
Build this project, then Publish to Folder and run on IIS.

### Tried fixes
- Included all sorts of Nugets that has Antiforgery inside.
- Included all sorts of options related to Antiforgery.dll to be included on Publish.

### Found fix
- To include file content as @Html.Raw(File.ReadAllText("./path/to/file.html"));

**Comment by javiercn** [comment]
@Equanimaster thanks for contacting us.

The reported issue looks weird, I would defer to @pranavkm since he's more knowledgeable in this area, but I don't believe rendering html files is something we've ever supported. I can see how it can potentially work in development since it might be tapping on to runtime compilation and treating the html file as a razor file, but ultimately the html file won't get compiled into the razor assembly and I imagine that will cause it to fail in published apps.

**Comment by Equanimaster** [comment]
Then its a bigger issue anyway, because you must throw error during development. Must be a consistency between environments.

**Comment by pranavkm** [comment]
@Equanimaster view compilation requires that ref assemblies are available. During build, these are made available via framework references and packages. A published app does not have access to these and uses ref assemblies which you have disabled: https://github.com/Equanimaster/AntiforgeryIssue/blob/master/AntiforgeryIssue.csproj#L5. Removing this should likely get your app working. 

I'd concur with @javiercn's suggestion and avoid treating arbitrary markup files as views.

**Comment by Equanimaster** [comment]
You do realize that this are default settings that are causing problem.
But beside that, why error is "Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'"
If antiforgery nowhere is used?
You for sure can insist and close this issue, for me you have clarified the situation.
But for future generations, this misleading Exception should be changed.
Just try to google "Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'".
