### ISSUE TITLE
Cannot drag & drop .razor/.cshtml files into Codespaces

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23910]
Drag a local `.razor` file into a `Codespaces` window. I get the following:

![image](https://user-images.githubusercontent.com/14852843/87341044-c808a080-c4fd-11ea-9eb9-81c79d96f6c5.png)

This either needs to be a silent failure if we can't support arbitrary drag/drop or the `.razor file needs to be opened up.

**Comment by TanayParikh** [comment]
VSTS Issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1144851

**Comment by allisonchou** [comment]
Given Codespaces is no longer a priority, I'm going to close out this issue for now, feel free to re-open if deemed necessary.
