### ISSUE TITLE
Component begins rendering before function called in OnParametersSetAsync() finishes

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#23923]
### Describe the bug
I have an awaited function called from `OnParametersSetAsync()` that doesn't finish before the component begins rendering. Properties populated in the running function are still `null` when it tries to render. It looks like the render begins when I `await` an EF Core database call.

### To Reproduce
I put a breakpoint on the property usage in the `HTML` section and another breakpoint on the EF Core database call in the function awaited in `OnParametersSetAsync()`. In the middle of the latter running, the breakpoint in the `HTML` is hit.

**What could cause this? Shouldn't the render start after everything in `OnParametersSetAsync()` has finished?**

### Exceptions (if any)
Null exception on the property that will be set when the EF Core database call finishes

### Further technical details
- ASP.NET Core 3.1.5
- Visual Studio for Mac 8.7.1802
- dotnet --info

.NET Core SDK (reflecting any global.json):
Version: 3.1.301
Commit: 7feb845744

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.15
OS Platform: Darwin
RID: osx.10.15-x64
Base Path: /usr/local/share/dotnet/sdk/3.1.301/

Host (useful for support):
Version: 3.1.5
Commit: 65cd789777

.NET Core SDKs installed:
3.1.100 [/usr/local/share/dotnet/sdk]
3.1.101 [/usr/local/share/dotnet/sdk]
3.1.102 [/usr/local/share/dotnet/sdk]
3.1.200 [/usr/local/share/dotnet/sdk]
3.1.201 [/usr/local/share/dotnet/sdk]
3.1.202 [/usr/local/share/dotnet/sdk]
3.1.300 [/usr/local/share/dotnet/sdk]
3.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

This is by design. Blazor components that extend ComponentBase render twice:
* When the synchronous code has finished to run.
* After the asynchronous code has finished running.

**Comment by mrlife** [comment]
@javiercn Even when using RenderMode of Server? If so, which is the synchronous code in this case, the HTML section? How does one populate properties before the HTML is rendered?

**Comment by mrlife** [comment]
@SteveSandersonMS Can anyone else comment specifically on how this is supposed to work?

**Comment by javiercn** [comment]
@mrlife when prerendering several renders happen, but the renderer will wait explicitly for the all components to be done an acquire "quiescence" before serializing the state

**Comment by mrlife** [comment]
@javiercn I'm not using prerendering in my project due to `RenderMode` being set to `Server` instead of `ServerPrerendered`. Is it prerendering anyway?

**Comment by javiercn** [comment]
@mrlife try out this component and see if it helps clarify things. (Replace Index.razor in a new app, for example).

```razor

<p>@_value</p>

@code{
  private string _value = "Uninitialized";

  protected override async Task OnInitializedAsync()
  {
      _value= "Before going async";
      await Task.Delay(5000);
     _value= "After resuming the async work";
     // Blazor will trigger an automatic render for the component when an async lifecycle method completes
  }
}
```

**Comment by javiercn** [comment]
@mrlife no, it is not prerendering if you don't set it to prerendering. On a synchronous method a single render request happens, on an asynchronous method two happens, one after finishing the synchronous work (typically before the first "await") and then one after the async method completes

**Comment by mrlife** [comment]
@javiercn Thank you, that code does illustrate something that I haven't explicitly seen before. A few questions:

- Is this sync/async double render documented anywhere?
- What about in the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#composition-with-tasks) where it says "if any portion of an operation is asynchronous, the entire operation is asynchronous."
- In my `OnParametersSetAsync()`, I only have code that is `await`ed... any way to determine what Blazor is considering synchronous in this situation?

**Comment by javiercn** [comment]
@mrlife Blazor looks at the task returned by the method, it triggers a render right away and if the task has not completed it queues a continuation on the task that will trigger a render if the task completes successfully.

**Comment by mrlife** [comment]
@javiercn I'm having some trouble applying your response to my questions. Any way to address them directly?

**Comment by javiercn** [comment]
@mrlife sure, let me clarify

> * Is this sync/async double render documented anywhere?
Yes, see [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1#handle-incomplete-async-actions-at-render)
> * What about in the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#composition-with-tasks) where it says "if any portion of an operation is asynchronous, the entire operation is asynchronous."

That is still the case, but an asynchronous operation still has a synchronous portion which happens before the code does a truly asyncrhonous operation. In the example above the syncrhonous part is all the sentences up to the `await Task.Delay`

> * In my `OnParametersSetAsync()`, I only have code that is `await`ed... any way to determine what Blazor is considering synchronous in this situation?

Blazor doesn't consider anything to be synchronous or asynchronous. That's simply how asynchronous code works. If it helps you visualize directly, this is what component base does. See [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/ComponentBase.cs#L229-L262)

**Comment by mrlife** [comment]
@javiercn Thank you. So, basically, I need to ensure any property used in the `HTML` portion of the `.razor` file is initialized to be non null or only accessed conditionally based on something that is non null until the lifecycle methods have a chance to complete, then the second render will be the successful render I'm looking for.

**Comment by javiercn** [comment]
@mrlife yep

**Comment by mrlife** [comment]
@javiercn This helped a lot, thank you!

One thing I noticed is that the following code only triggers the synchronous render (`IsSearching` is updated in the `HTML`) if the asynchronous `Task.Delay(1)` is commented out. Are some asynchronous calls different than others to Blazor?

```c#
private async Task FormSubmitted()
    {
        IsSubmitted = true;
        //await Task.Delay(1);
        await DoSearch();
    }
```

**Comment by mrlife** [comment]
@javiercn This helped a lot, thank you!

One thing I noticed is that the following code only triggers the synchronous render (`IsSearching` is updated in the `HTML`) if the asynchronous `Task.Delay(1)` is commented out. Are some asynchronous calls different than others to Blazor?

```c#
private async Task FormSubmitted()
    {
        IsSubmitted = true;
        //await Task.Delay(1);
        await DoSomething();
    }
```
