### ISSUE TITLE
NuGet with Azure DevOps Services feeds need login from 3.1.4

### ISSUE THREAD

**Issue by stantoxt** [dotnet/aspnetcore#23921]
It will cause nuget restore problem and the error is here.

`1.NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-extensions-877455ff/nuget/v3/index.json `

`2.NuGet.targets(128,5): error : Response status code does not indicate success: 401 (Unauthorized)`

It will redirect to microsoft login page if load the url in browser.

How I can build source code successfully.

**Comment by Tratcher** [comment]
Are you trying to build from the git label 3.1.4? Or from the release/3.1 branch?

**Comment by stantoxt** [comment]
Sorry,I built from lable, I am testing release/3.1 branch.

**Comment by stantoxt** [comment]
@Tratcher thanks,it works.
