### ISSUE TITLE
[API Suggestion] Add Helper Methods for adding Metadata to Controller and Action at Runtime

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#23922]
There's no clear way on how to add `Metadata` to specific MVC `Endpoint`. 
It's good to have such API to add `Metadata` like this

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers()
        .AddControllerMetadata("Home", x =>
        {
            x.Metadata.Add(10);
        })
        .AddActionMetadata("Home", "Index", x =>
        {
            x.Metadata.Add(20);
        });
});
```
This could be the implementation
```csharp
public static class ControllerActionEndpointConventionBuilderExtensions
{
    public static ControllerActionEndpointConventionBuilder AddControllerMetadata(this ControllerActionEndpointConventionBuilder builder, string controllerName, Action<EndpointBuilder> convention)
    {
        builder.Add(x =>
        {
            var controller = x.Metadata
                .OfType<ControllerActionDescriptor>()
                .Where(x => x.ControllerName == controllerName)
                .FirstOrDefault();

            if (controller != null)
            {
                convention(x);
            }
        });
        return builder;
    }

    public static ControllerActionEndpointConventionBuilder AddActionMetadata(this ControllerActionEndpointConventionBuilder builder, string controllerName, string actionName, Action<EndpointBuilder> convention)
    {
        builder.Add(x =>
        {
            var controller = x.Metadata
                .OfType<ControllerActionDescriptor>()
                .Where(x => x.ControllerName == controllerName && x.ActionName == actionName)
                .FirstOrDefault();

            if (controller != null)
            {
                convention(x);
            }
        });
        return builder;
    }
}
```

The same principal could be applied to other frameworks (SignalR, RazorPage, ...)

cc/ @davidfowl

**Comment by davidfowl** [comment]
It's not needed for signalr because you map a single hub at a time.

MVC does have a way to do this already but it isn't as convenient as described here, though I don't know that we need more ways to describe the same thing.

What scenario do you have in mind for this? 

cc @javiercn @pranavkm

**Comment by javiercn** [comment]
@davidfowl I somewhat agree with your view. You can already achieve this with an attribute or an ApplicationModelConvention, so I'm not sure what value does it have to do it here, while I can see the potential downside in startup perf from repeated look-ups for a specific endpoint.

Also the logic is not correct since an action can result in multiple endpoints being defined, so `FirstOrDefault` will make it unpredictable.

**Comment by Kahbazi** [comment]
> It's not needed for signalr because you map a single hub at a time.

But can each method in a hub, has different metadata?

> What scenario do you have in mind for this?

I have nothing in mind. I just thought that this might be a good API to have.

**Comment by javiercn** [comment]
> But can each method in a hub, has different metadata?

Nope, the metadata and the endpoint is for the hub, methods on the hub are not endpoints.

> I have nothing in mind. I just thought that this might be a good API to have.

We don't add public APIs unless we have a good scenario in mind. Doing so increases our maintenance cost, can limit our options in the future and pollutes the API surface making other features harder to find.

Given that we don't have a clear scenario that would benefit from having this API, I'm going to close the issue for now. If we hear feedback about it, we can reconsider.
