### ISSUE TITLE
Inaccurate stack trace output with NullReferenceException in View (MVC)

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#23946]
With a System.NullReferenceException thrown by Microsoft.AspNetCore.Server.Kestrel, the line shown as being the problem line was not where the exception occurred. This was confirmed to not be an issue with compliation/runtime optimization changing execution/line numbers; the highlighted line follows around the (falsely) suspected line, which wasn't actually related to the exception.

Scenario:

In a controller action, a <string,string> key-value pair was added to the ViewData object, for the purpose of passing a variable to JavaScript in the view, to be used on the client. A mistake was made with the following code in the view (.cshtml):

```
<script>
    const ITEM_NAME = "@Html.Raw(ViewData["ItemName"].ToString())"
</script>
```

The mistake here was that the View is shared between multiple controller actions, but only certain actions initialize that particular key-value pair in the ViewData object, leading to a null reference when trying to call `ToString()` on a non-existing dictionary entry.

However, in the stack trace for the exception, an earlier line in the file was highlighted as causing the problem:

`<div class="new-order modal @(Model.isNew ? "active" : "")">`

If some filler code was added before or after that line (to artificially change the line number), the problem line, according to the stack trace, followed along with it. **Removing the `ToString()` call on the ViewData object removed all issues.**

This made it appear that trying to reference the `isNew` property of the view model was the issue, as if the view model was null, although the view model had several other properties that were already successfully used in previous lines. 

After commenting out the (false) problem line shown above, the exception remained (of course), but the new problem line, according to the stack trace, was yet another perfectly valid de-referencing of the Model object, still unrelated to the exception caused by `ToString()`.

I suspect that maybe removing any and all references to the view model object would have finally revealed the real problem line, but I did not test that theory.

**Comment by captainsafia** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
