### ISSUE TITLE
SignInManager.RefreshSignInAsync(); does not update the User claims data

### ISSUE THREAD

**Issue by perpetualintelligence** [dotnet/aspnetcore#23944]
### Describe the bug
SignInManager.RefreshSignInAsync() does not refresh the user claims. 

### To Reproduce
I have ActiveEnvironment (Test or Live) property in the IdentityUser class.  I use CustomClaimsPrincipalFactory to add the active environemnt to the user claim. This code is working fine.

Now when user change the environment I have following code that updates the user environment and then updates the claims using SignInManager.RefreshSignInAsync(). However the claim does not update at all.  I added a Debug.Assert() to show that the Controller.User still has the old claim.

```
          // To show the issue get the old environment from the claim
          Applications.Common.Environment oldEnvironmentFromClaim = Enum.Parse<Applications.Common.Environment> 
           (User.FindFirstValue(WebConstants.UserActiveEnvironmentClaim));

            // Change environment and update user
            // The model.NewEnvironment is different from old environment
            user.ActiveEnvironment = model.NewEnvironment;
            await UserManager.UpdateAsync(user);

            // Now update the claims.  Here CustomClaimsPrincipalFactory  correctly updated the claim.
            await SignInManager.RefreshSignInAsync(user); 

            // To show the issue get the environment from claim again
            Applications.Common.Environment newEnvironmentFromClaim = Enum.Parse<Applications.Common.Environment>(User.FindFirstValue(WebConstants.UserActiveEnvironmentClaim));

            // THIS IS THE ISSUE the old and new claim are same.
            Debug.Assert(oldEnvironmentFromClaim != newEnvironmentFromClaim, "Environment claim is not updated, but user is updated in the back-end store");
```

### Further technical details
- ASP.NET Core version 3.1
- IDE Visual Studio 2019

**Comment by blowdart** [comment]
You are misunderstanding what RefreshSignIn does - it re-reads the claims from the cookie and updates the cookie. If you want to refresh the claims you should call SignIn again.
