### ISSUE TITLE
Kestrel support for "path based" TLS renegotiation.

### ISSUE THREAD

**Issue by avparuch** [dotnet/aspnetcore#23948]
### Is your feature request related to a problem? Please describe.

We have a reverse proxy running on ASP.NET Core, hosted in IIS in-process. During the initial TLS handshake with the client, the server is configured to *not* ask for a client certificate. However, if the path of the request contains, say "pksecure", IIS triggers a TLS renegotiation and sends a client certificate request.

The following configuration in IIS is how it works:

```xml
<location path="pksecure">
    <system.webServer>
      <security>
        <access sslFlags="Ssl, SslNegotiateCert, SslRequireCert"/>
      </security>
    </system.webServer>
</location>
```

### Describe the solution you'd like

We would like Kestrel to have the same capability. This is supported on IIS, both in ASP.NET Core and ASP.NET

**Comment by Tratcher** [comment]
That feature is outdated and will not be added to kestrel.

See the following doc for an alternative.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#optional-client-certificates

**Comment by avparuch** [comment]
The linked document does not capture the same scenario. The recommendation there is using a separate hostname to mimic optional client certificates. However, the required scenario is the ability to keep the hostname the same and however renegotiate TLS based on path. The renegotiation of TLS is necessary because path is a http construct and the initial TLS handshake is already done by then and we are choosing to change the parameters of TLS based on http constructs.

**Comment by Tratcher** [comment]
That model isn't going to work anymore, renegotiation is obsolete in modern protocols. It's prohibited by the HTTP/2 spec and has been complete removed from TLS 1.3 (HTTP/3 & QUIC).

Even in HTTP/1.1 it was problematic. It could cause a POST request to deadlock if the request body filled up the TCP window and blocked the renegotiate packets.

The proposal outlined in the linked doc should work with all existing implementations and protocols. I understand that it will require some application redesign, but you'll need to address that in the long term anyways.

**Comment by avparuch** [comment]
Makes sense. I didn't know it was prohibited by Http/2. This is a good thing, this gives us leverage when talking to partners to put this pattern on the deprecation path.

**Comment by Tratcher** [comment]
Interestingly TLS 1.3 does define a new way to request the client certificate after the connection has been established, it's called post-handshake authentication.  https://tools.ietf.org/html/rfc8446#section-4.6.2

However, this feature is also explicitly prohibited for use with HTTP/2 https://tools.ietf.org/html/rfc8740#section-3. I wonder if HTTP/3 will support it.

Either way, it's still better to use a strategy that works across all versions.

**Comment by Tratcher** [comment]
Re-opening. The downstream customers have found that switching to the recommended alternatives is too breaking for their clients.

This is blocked pending work in SslStream. Once SslStream supports it then it should be a small amount of work to wire that up to TlsConnectionFeature.GetClientCertificateAsync.
https://github.com/dotnet/aspnetcore/blob/bf51aa5bfc50a1061c83c49c2273f920a2c22116/src/Http/Http/src/Features/TlsConnectionFeature.cs#L19

**Comment by Tratcher** [comment]
> I wonder if HTTP/3 will support it.

No they won't. https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#section-4.4

> A server MUST NOT use post-handshake client authentication (as defined in Section 4.6.2 of [TLS13]), because the multiplexing offered by QUIC prevents clients from correlating the certificate request with the application-level event that triggered it (see [HTTP2-TLS13]). More specifically, servers MUST NOT send post-handshake TLS CertificateRequest messages and clients MUST treat receipt of such messages as a connection error of type PROTOCOL_VIOLATION.

That limits the usefulness of this feature to HTTP/1.x.

**Comment by davidfowl** [comment]
@Tratcher do we need to design any new API here once https://github.com/dotnet/runtime/issues/49346 is in?

**Comment by Tratcher** [comment]
The existing GetClientCertificateAsync API should cover it.
https://github.com/dotnet/aspnetcore/blob/bf51aa5bfc50a1061c83c49c2273f920a2c22116/src/Http/Http/src/Features/TlsConnectionFeature.cs#L19

**Comment by davidfowl** [comment]
Will the sync API be blocking? I think it should return null.

**Comment by Tratcher** [comment]
> Will the sync API be blocking? I think it should return null.

The property will return the current value, if any. That's how HttpSys works now.

**Comment by Tratcher** [comment]
HttpSys does have one other API controlling this:
https://github.com/dotnet/aspnetcore/blob/1453c5bd2cf886f6846d2cc00b8106dbd0fdbd53/src/Servers/HttpSys/src/ClientCertificateMethod.cs#L21-L24

**Comment by Tratcher** [comment]
@davidfowl raises a good point that people using the cert auth handler will still have to be careful not to deadlock POST requests for the reasons outlined above, auth runs before model binding consumes the request body. We'll want to consider mitigations to at least make it fail instead of deadlock.

**Comment by Tratcher** [comment]
Here's Kestrel's current implementation:
https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/Servers/Kestrel/Core/src/Internal/TlsConnectionFeature.cs#L37-L40

And here's where the client cert is currently assigned:
https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L201

It may be interesting to note that a renegotiation may cause some/all of these other fields to change:
https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L202-L208

**Comment by davidfowl** [comment]
Cache that allocation 😄
