### ISSUE TITLE
ProtectedBrowserStorage : Loading error with IE 11

### ISSUE THREAD

**Issue by Kattabomane** [dotnet/aspnetcore#23950]
### Describe the bug
When using the ProtextedBrowserStorage with Blazor Server Side, it is not possible to load the Blazor application on IE11.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/60187320/87529104-ccb08e80-c68e-11ea-8192-0dc5c1a58a68.png)

### Further technical details
- ProtectedBrowserStorage : 0.1.0-alpha.19521.1
- ASP.NET Core version : 3.1.0
- Include the output of `dotnet --info` : 3.1.100
- The IDE (VS / VS Code/ VS4Mac) : VS2019 on Windows 10

**Comment by javiercn** [comment]
@Kattabomane thanks for contacting us.

This is an experimental package and we don't claim to have support for IE11 on it. The likely issue here is that the JS file uses ES6 syntax which is not compatible with IE11.
