### ISSUE TITLE
Update aspnetcore/docs/BuildFromSource.md to indicate which components are required for which bits of this repo

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#23957]
According to https://github.com/dotnet/aspnetcore/issues/15873#issuecomment-399317900:

> node is only needed if you're trying to build the Blazor repo, and Java is only needed to run Selenium for the e2e tests. If you just want to try out C# in the browser you don't need either of those things.

Regardless of how amusing/sad/embarassing it is to have any portion of a .NET repo depend on Java in any way shape or form, I imagine that very few people will want to install the bloatware that is Java just to build the C# projects. It would be helpful if `BuildFromSource.md` was updated to note what components are required by which areas, so that people can only install those they need to do the thing they want. It would also be useful if this was extended to the VS components - for example, why do I need to install freaking .NET Framework targeting packs and SDKs for building a .NET Core repo?

**Comment by dougbu** [comment]
We have decided instead to track the requirements in individual README.md files. See #27561.
