### ISSUE TITLE
Imports.razor availability

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#23955]
I checked the docs on `Imports.razor` and didn't see anything about these situations:

1. `_Imports.razor` cascades `@inject` directives but not `@using` directives from the base `_Imports.razor` into the `Pages` folder. I am using backing `.razor.cs` files; is cascading a feature or possibly a side effect of using `.razor.cs` files?

2. Placing an `_Imports.razor` in the `Pages` folder partially works: `@inject` directives work, however `@using` directives do not. I am using backing `.razor.cs` files; is that a dealbreaker for receiving `@using` directives from `_Imports.razor`?

### Further technical details
- ASP.NET Core 3.1.5
- Visual Studio for Mac 8.7.1802
- dotnet --info

.NET Core SDK (reflecting any global.json):
Version: 3.1.301
Commit: 7feb845744

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.15
OS Platform: Darwin
RID: osx.10.15-x64
Base Path: /usr/local/share/dotnet/sdk/3.1.301/

Host (useful for support):
Version: 3.1.5
Commit: 65cd789777

.NET Core SDKs installed:
3.1.100 [/usr/local/share/dotnet/sdk]
3.1.101 [/usr/local/share/dotnet/sdk]
3.1.102 [/usr/local/share/dotnet/sdk]
3.1.200 [/usr/local/share/dotnet/sdk]
3.1.201 [/usr/local/share/dotnet/sdk]
3.1.202 [/usr/local/share/dotnet/sdk]
3.1.300 [/usr/local/share/dotnet/sdk]
3.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by guardrex** [comment]
:ear: I'll open a docs issue for this shortly.

**Comment by mrlife** [comment]
@guardrex Thanks. I'm sure this is the desired behavior, thought.

Shouldn't everything in `_Imports.razor` cascade or nothing? Why don't `@using` directives in the `_Imports.razor` file in the `Pages` folder work?

**Comment by mrlife** [comment]
@guardrex Thanks. I'm not sure this is the desired behavior, though.

Shouldn't everything in `_Imports.razor` cascade or nothing? Why don't `@using` directives in the `_Imports.razor` file in the `Pages` folder work?

**Comment by guardrex** [comment]
I mean we need to document any deviations from *what is expected*, so I'll open an issue on that basis.

The unexpected behavior that I hit while working with the file was that one can't secure an entire app by applying an `[Authorize]` attribute with the `@attribute` directive via the file. I ask about it on https://github.com/dotnet/AspNetCore.Docs/pull/19162. btw @javiercn ... that PR should be a quick review.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

`@using` statements in `.razor` files will only be applied to `.razor` files and not to `.cs` files.

**Comment by mrlife** [comment]
@mkArtakMSFT Thank you for clarifying that. Would there be any drawback to implementing an `_Imports.razor.cs` file that would do what `_Imports.razor` does except for the backing files?
