### ISSUE TITLE
Make one or more Razor Nexus DDRIT tests to be non-experimental

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#23964]
Follow up to https://github.com/dotnet/aspnetcore/issues/22720

To make this happen, we'll need to be sure that it passes reliably locally and on the experimental runs first.

**Comment by NTaylorMullen** [comment]
This done?

**Comment by ryanbrandenburg** [comment]
The second part.

**Comment by ryanbrandenburg** [comment]
Completed by https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/266524
