### ISSUE TITLE
CTS should be disposed

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#23967]
A static analysis tool identified this CancellationTokenSource as a resource that needs to be disposed.
https://github.com/dotnet/aspnetcore/blob/38126419b803c6fd1946645aabff98aa239d2b79/src/Hosting/Hosting/src/WebHostExtensions.cs#L24
It should be as easy as making this method async/await and adding a using statement.

**Comment by sharwell** [comment]
📝 The last time I checked, `CancellationTokenSource` will only allocate unmanaged resources that need to be freed if you create the source with `CreateLinkedTokenSource`.

**Comment by Tratcher** [comment]
They also need to be disposed if the haven't been canceled. It stops the timer and unregisters the callbacks.

**Comment by BrennanConroy** [comment]
> A static analysis tool identified this CancellationTokenSource as a resource that needs to be disposed.

What analyzer is this, and can we enable it for our repo(s)?
