### ISSUE TITLE
Any plans for maximum session size property?

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2398]
_From @wysisoft on Tuesday, August 22, 2017 9:44:08 PM_

Are there any plans for a property that sets a maximum size for total user session, and throws an exception if its exceeded? Any recommendations on how I can simply accomplish this? (currently using redis distributed cache)

_Copied from original issue: aspnet/Session#185_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, August 23, 2017 5:18:19 AM_

No plans for this yet, but it's an interesting idea.

Some workarounds:
- You have full access to the data from ISession so it would not be difficult to enforce your own limit via a helper method, middleware, etc.. e.g. enumerate the session and total the size of the elements.
- It should not be hard to copy and override the ISessionStore implementation to enforce this. 
https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionServiceCollectionExtensions.cs#L27

**Comment by JunTaoLuo** [comment]
Given that there are workarounds to achieve this effect, It's unlikely we'll implement this unless there's more demand for this issue.
