### ISSUE TITLE
Limit .Net Core log files to X number of days

### ISSUE THREAD

**Issue by BrandoZhangTest** [dotnet/aspnetcore#23988]
I am trying to  limit the number of log files created in the .net core .\logs\stdout folder. 

For example: I want to retain only the last 10 days of files in .\logs\stdout folder.

**Comment by gfoidl** [comment]
You can use something like https://github.com/serilog/serilog-sinks-file

See [Log creation and redirection](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#log-creation-and-redirection) for further info.

**Comment by BrennanConroy** [comment]
Generally we recommend you turn off console log redirection except for specific times when you need them, or use a 3rd party logging provider which provides that behavior for you.
