### ISSUE TITLE
Add logging scope for session

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2400]
_From @davidfowl on Wednesday, July 12, 2017 11:23:57 AM_

The session middleware should create a scope with the session id so that it's possible correlate session across multiple requests for logs.

_Copied from original issue: aspnet/Session#181_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, July 12, 2017 11:30:13 AM_

Implementation question: do you use the cookie value or the cached session instance id. The cookie value is likely longer lived than the cache instance.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
