### ISSUE TITLE
Using aspnetcore as git module for the version v3.1.6 can't compile because of dependency of remote protected packages

### ISSUE THREAD

**Issue by joaoantunes** [dotnet/aspnetcore#24013]
I've made a git module of aspnetcore from version v3.1.6

I've imported Microsoft.AspNetCore.ResponseCaching, and when I try to compile it provides this errors:

![image](https://user-images.githubusercontent.com/224836/87689226-dbc33980-c77f-11ea-8ed1-b914bbcabead.png)

If I make dotnet restore it gives the following error:
PM> dotnet restore
  Determining projects to restore...
C:\Program Files\dotnet\sdk\3.1.302\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-extensions-be18161f/nuget/v3/index.json. [C:\distributed-middleware-cache\DistributedResponseCachingMiddleware.sln]
C:\Program Files\dotnet\sdk\3.1.302\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized).

**Comment by Tratcher** [comment]
You mean 3.1.6? I suggest trying the release/3.1 branch instead.

**Comment by joaoantunes** [comment]
Yes, 3.1.6 sorry I fixed the typo.

So I should use "git checkout tags/v3.1.0"?

**Comment by joaoantunes** [comment]
I have able to restore the packages using v3.1.0,
But now it provides this issue:

![image](https://user-images.githubusercontent.com/224836/87703889-6a8d8180-c793-11ea-9e30-919cfd26dee9.png)

Do I need to compile those dependencies? How?

**Comment by Pilchie** [comment]
You should be able to use the `3.1.6` tag, *but* you need to modify the `NuGet.config` to remove the internal sources.  They are present to allow us to build security fixes in private without disclosure ahead of time, but we try to tag the actual SHA we built from, which means it still references those internal feeds.

**Comment by joaoantunes** [comment]
Using git submodules I can't change the submodule code since the submodule is yours. 

The only solution is to make a fork and change that?

Can you provide an example what to change in a NuGet.cofig?

**Comment by Pilchie** [comment]
You'd want to remove the `darc-int` lines:

https://github.com/dotnet/aspnetcore/blob/62c098bc170f50feca15916e81cb7f321ffc52ff/NuGet.config#L7-L11

**Comment by Pilchie** [comment]
Tagging @dotnet/aspnet-build, since we were discussing this problem the other day.

**Comment by wtgodbe** [comment]
You could also change your submodule to check out release/3.1: `git checkout release/3.1`

**Comment by dougbu** [comment]
If submodules aren't set up correctly, use `git checkout --recurse-submodules release/3.1` or `git submodule sync --recursive; git submodule update --init --force --recursive` to be sure you've got things consistent.
