### ISSUE TITLE
Cache RazorSourceDocument SyntaxTree when Open

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24030]
![image](https://user-images.githubusercontent.com/14852843/87708265-4dd35880-c757-11ea-9ca8-a762b0600ef1.png)

We're doubling up the `ProcessDesignTime` work between the actual document generation and razor diagnostics. 

https://github.com/dotnet/aspnetcore/blob/b8261dfe9d13bf87cbcf84885ed13effe431b8ee/src/Razor/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorProjectEngine.cs#L246-L256

We should be able to cache the latest document. Thanks @NTaylorMullen!

**Comment by allisonchou** [comment]
I think this is a compiler issue, feel free to transfer over to the tooling repo if I'm wrong.

**Comment by TanayParikh** [comment]
Closing this, as we will be focusing on the elimination of design time builds in the near future, and this will not be an issue any more.
