### ISSUE TITLE
Asp Net Core Individual User Accounts Authentication requires login depsite [AllowAnonymous] tag.

### ISSUE THREAD

**Issue by JamieMair** [dotnet/aspnetcore#24039]
### Describe the bug
I have created a web app based on the Blazor Web Assembly template in VS 2019 with ASP.NET core hosting and individual user accounts. I have a CRUD API controller that allows read operations using the [AllowAnonymous] tag and requires authorization for the others. I am trying to access the read operation from the api, but this redirects to the login page. I want to allow unauthenticated users to be able to read from the API without logging in, but not be able to create, update or delete the data.
 
### To Reproduce
- Make a Blazor Web Assembly template in VS 2019 with ASP.NET core hosting and individual user accounts
- Add a CRUD API that has [Authorize] tags on some methods and [AllowAnonymous] on the HttpGet operation
- Call that API from the blazor web assembly client with the HttpClient class. 
- Get an error from the HttpClient call that includes a redirect to the login page.

### Further technical details
<details><summary>Software details</summary>
Microsoft Visual Studio Community 2019 Version 16.6.4

.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

**Comment by javiercn** [comment]
@JamieMair thanks for contacting us.

The ASP.NET Core authentication support for APIs is based on Open ID Connect (JWT Bearer tokens) and the normal API response you'll get for that is a 401. The authorization system for the API doesn't have a way of knowing where you should go for authenticating since Authorization and Authentication are completely decoupled in that case.

Given that you are using Blazor WebAssembly, my recommendation is that when you receive a 401 response from the server you use the NavigationManager.NavigateTo method to send the user to `authentication/login` and that will start the authentication process.

**Comment by JamieMair** [comment]
When I request information using Postman, the response is a 200 OK, with the data I needed, that does not include any form of authentication or login redirects. The issue that I am having is that the call in Blazor Web Assembly using HttpClient is throwing an error that says authentication is needed, which includes a redirect to the login page.

**Comment by JamieMair** [comment]
After some investigation, I found that this issue is happening since authentication web tokens are being added to the Http requests in the Program.cs of the web assembly app:
`.AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>()`
Is there a way to specify which message handler to use when you make a request?

**Comment by JamieMair** [comment]
In case anyone is reading this and still needs solutions, it seems that the links below better detail the problem and the solutions:
[Dev.to blog post](https://dev.to/j_sakamoto/how-to-send-http-requests-to-public-api-without-access-token-on-an-authentication-enabled-blazor-wasm-app-4a5n)
[MS Documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client)
