### ISSUE TITLE
FileBufferingReadStream CopyToAsync Performance problem.

### ISSUE THREAD

**Issue by avparuch** [dotnet/aspnetcore#24032]
When buffering a response using FileBufferingReadStream: initially, the stream's Position and Length are both 0. Based on the code in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L160-L188, CopyToAsync chooses a buffer size of 1. 

When the stream is say, 16KB, this triggers a FileStream.GetLengthInternal() call 16,384 times and causes a big CPU spike for requests that are buffered to disk. 

Please see attached profiler trace.
![GetLengthInternal](https://user-images.githubusercontent.com/55294511/87715806-bffd6a80-c762-11ea-8e3a-ec173cc3196a.PNG)

We are currently solving this issue by calling the overload of CopyToAsync that accepts an explicit buffer size (we chose 16KB).

**Comment by Tratcher** [comment]
For reference, CopyToAsync is being called as a simple way to fully buffer the data.

We have a DrainAsync extension that can also be used for this (but we should still fix CopyToAsync).
https://github.com/dotnet/aspnetcore/blob/425c196cba530b161b120a57af8f1dd513b96f67/src/Http/WebUtilities/src/StreamHelperExtensions.cs#L15

Fixing this is tricky, the Stream.CopyToAsync code that does this check isn't virtual. We may have to talk to the runtime team about how FileBufferingReadStream implements CanSeek, Length, etc..
