### ISSUE TITLE
Misleading documentation in StreamResponseBodyFeature

### ISSUE THREAD

**Issue by Thiez** [dotnet/aspnetcore#24049]
The documentation of `StreamResponseBodyFeature` has the following documentation on its `CompleteAsync` method:

```csharp
/// <summary>
/// This calls StartAsync if it has not previoulsy been called.
/// It will complete the adapted pipe if it exists.
/// </summary>
/// <returns></returns>
public virtual async Task CompleteAsync()
```

However, the method does not appear to call `StartAsync` at all. The documentation should either be updated to remove the line about calling `StartAsync`, or the method body should be updated so that it *does* call `StartAsync`. I am not familiar enough with the internals to know which one of these options is correct.

I suppose the typo in 'previoulsy' can be fixed as well :)

**Comment by Tratcher** [comment]
We should have it call StartAsync.
