### ISSUE TITLE
Routing public API nullability issue

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#24042]
![image](https://user-images.githubusercontent.com/303201/87738010-85fa9a00-c830-11ea-8c9c-2b9936bff699.png)

https://github.com/dotnet/aspnetcore/blob/1455aaeff118aeaf2b0ab5f1627c2c8ca5df7f11/src/Http/Routing/src/Patterns/RoutePatternFactory.cs#L58

defaults should allow null

@pranavkm

**Comment by javiercn** [comment]
This is why I hate these PRs :) It's super easy to miss something like this. Thanks @JamesNK for catching that.
