### ISSUE TITLE
SessionSample improvements

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2405]
_From @Rick-Anderson on Monday, October 10, 2016 11:55:15 PM_

[samples/SessionSample/Startup.cs](https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L24)
- [x] Consider removing the SQL connection string. We want to avoid copy/paste and this encourages checking in secrets. At least change the name from `ASPNET5SessionState` to something like `SessionStateCache`
- [ ] add a comment with a fwlink to https://docs.asp.net/en/latest/performance/caching/distributed.html

_Copied from original issue: aspnet/Session#130_

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, October 11, 2016 9:20:25 AM_

It's a comment, to give the devs an idea for how to use the SQL Server implementation of `IDistributedCache`, I don't think it's a worth because using SQL Server implementation requires some setup before we use it, but for production I'm agree with you to use the secrets

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, June 14, 2017 3:39:53 PM_

@Rick-Anderson We'd be happy to consider PRs on this. Putting this in the backlog for now because of the heavy workload in many other areas.

**Comment by Tratcher** [comment]
Improved by https://github.com/aspnet/Session/pull/199

**Comment by davidfowl** [comment]
Should this be moved to docs
