### ISSUE TITLE
[Blazor] execute check at high level to redirect to another page

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#24054]
hello guys, i have some trouble with my blazor webassembly webapp when the user decide to refresh the page (with f5 for example).

I can't maintain a stable state concerning my data so if its happen i prefer disconnect him and and redirect him to the login page.

im able to suscribe to the onload js event and call method of one to my component to disconnect the user, it work. but in this method, if i try to redirect to the login page with the NavigationManager its not work (it stay on the current page, no redirection)

I try another way, in my layout on the OnInitialized method i check if my user is not connected and if im not on the login page, if its the case i redirect to the login page. It works, but the problem is the current page will run her lifecycle with inconsistend data so it will sometimes crash. So there is a way to do that at another level to be sure the current page will not be loaded ? 

I wait for yours suggestions, don't hesitate if you have better idea to achieve what i want !

thanks !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

I would suggest you do this directly within the App.razor component. Wouldn't that be simpler for you than having to deal with the layout and other concerns?

**Comment by julienGrd** [comment]
> @julienGrd thanks for contacting us.
> 
> I would suggest you do this directly within the App.razor component. Wouldn't that be simpler for you than having to deal with the layout and other concerns?

Yes it can be ! how i can do that ? for me the app.razor contains only the main point of the app without code.

this is my actual App.razor
````
<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="routeData" DefaultLayout="typeof(Components.Layouts.MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(Components.Layouts.MainLayout)">
            <Is.Geckos.Blazor.Client.Components.Pages.Main.PageFallBack />
        </LayoutView>
        
    </NotFound>
</Router>
````

**Comment by javiercn** [comment]
@julienGrd define a `@code` block, inject NavigationManager, check the Url property on it within `OnInitialize` and trigger the navigation?

**Comment by julienGrd** [comment]
> @julienGrd define a `@code` block, inject NavigationManager, check the Url property on it within `OnInitialize` and trigger the navigation?

sometimes im really dumb, i was thinking App.razor was kind of special component without code, but it seem to be a classic component with all lifecycle.

using the initialized of this component make the job perfectly, thanks for your help, the subject is close
