### ISSUE TITLE
Dot net core Code publish takes too long time.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24069]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1091662/dot-net-core-code-publish-takes-too-long-time.html)._

---
Hi,
Good Afternoon.
I am a Dot net developer using visual studion 2019 latest version of community version. I am doing a project using .net core with angular 8 and sql server database. I did not use any entity framework. When I am publish the code its take about 20 to 40 minuits. Can you help me out from this?

---
#### Feedback Bot on 6/27/2020, 07:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### sprasad.sipu on 6/28/2020, 09:19 PM: 

Ok,<br>Thank you. Wating for the solution.
#### Feedback Bot on 6/28/2020, 11:02 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
When publishing, Angular project runs `npm install`, which ends up downloading all the npm packages to your development machine. This is quite significant in size and with slow internet connection can take long time.
You can confirm this by navigating to the `/ClientApp` folder and run `npm install` manually.
