### ISSUE TITLE
IAsyncEnumerable should work with ActionResult<T>

### ISSUE THREAD

**Issue by TimPosey2** [dotnet/aspnetcore#24061]
### Is your feature request related to a problem? Please describe.
Currently, you cannot use `ActionResult<T>` in an ASP.NET Core controller API along with `IAsyncEnumerable<T>`. 

### Describe the solution you'd like
Ideally, a developer should be able to return the `IAsynEnumerable<T>` and it is implicitly converted to `ActionResult<T>`. Developers should be able to mix return types as well, for example returning `BadRequest()` where appropriate and also returning the `IAsyncEnumerable<T>` data. The data should be streamed back appropriately to the Json/Media Formatter without needing to cause a full buffering of the data into another `List<T>` or other collection type.

### Additional context
This currently does not work. It will cause compiler error that says `"Cannot implicitly convert type 'System.Collections.Generic.IAsyncEnumerable<T>' to 'Microsoft.AspNetCore.Mvc.ActionResult<System.Collections.Generic.IAsyncEnumerable<T>>'`:
```

public async Task<ActionResult<IAsyncEnumerable<int>> GetSomeData()
{
   if (!ModelState.IsValid)
     return BadRequest("You forgot some data");
 
   IAsyncEnumerable<int> myData = myDataRepository.GetSomeData();
   return myData;
}
```

Instead, currently you have to do something like this:

```

public async Task<ActionResult<IEnumerable<int>> GetSomeData()
{
   if (!ModelState.IsValid)
     return BadRequest("You forgot some data");
 
   IAsyncEnumerable<int> myData = myDataRepository.GetSomeData();
   
   List<int> data = new List<int>();
   await foreach (int i in myData)
        data.Add(i);

    return data;
}
```

**Comment by captainsafia** [comment]
Thanks for opening this issue, @TimPosey2! Please review the following references for guidance with this question

* https://stackoverflow.com/questions/4280592/c-sharp-generic-implicit-cast-on-interface-failed/4280626#4280626
* https://github.com/dotnet/aspnetcore/issues/3224#issuecomment-397376517
