### ISSUE TITLE
Listen on all sockets provided by systemd socket activation

### ISSUE THREAD

**Issue by onyxmaster** [dotnet/aspnetcore#24067]
### Is your feature request related to a problem? Please describe.
[Currently](https://github.com/dotnet/aspnetcore/blob/68cc5e7846240bacc146854dfc6a175e30ff0f60/src/Servers/Kestrel/Core/src/Systemd/KestrelServerOptionsSystemdExtensions.cs#L39), when using systemd activation, the ASP.NET Core only listens on the first passed socket (`SD_LISTEN_FDS_START`, equal to 3). This prevents using multiple listening sockets in [systemd socket definition](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#ListenStream=). systemd [passes](https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html) the number of file descriptors via `%LISTEN_FDS%`, but currently the code doesn't take this into account.

### Describe the solution you'd like
The issue is quite easy to fix, in fact I hacked a [simple inline solution](https://github.com/drivenet/ocsp-responder/commit/834a8f23e73f68393d055b15e0cfa71e424c83a6#diff-9df42d5e5b06b758ed23a39c0a16a6a7R101) to this issue, but I believe that it should be improved at the source.
I'm willing to provide a PR along the lines of the solution described above, but first I would like to know if there is any interest in this. 

I understand that a backport to 2.1/3.1 is quite unlikely, but I have to ask if it is possible (given that the changes are probably going to be very localized and we're stuck on 2.1/3.1 for the near future).
If backport is not possible, I would also like to ask if us providing a nuget package with "improved" version of `UseSystemd` is OK.

Since I did some previous work on related functionality, tagging @halter73 because he helped me last time with review and integration.

**Comment by halter73** [comment]
@onyxmaster Thanks for finding this! We backlogged this for work in a future release, but I'd be happy to take a PR sooner. The logic "simple inline solution" does look like what we want in KestrelServerOptionsSystemdExtensions.

**Comment by davidfowl** [comment]
We don’t backport but a PR for this feature seems fine as long as it’s something natively supported by systemd. You should keep shopping that package to work out any oddities that may result from this feature
