### ISSUE TITLE
Polyfill C# statements until snippet support is available.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24064]
C# snippets power every statement in the C# experience. Given C# has removed their snippet support this means that LSP scenarios no longer have access to those snippets when typing things like `@using` etc:

![using](https://user-images.githubusercontent.com/14852843/87751394-bdc2fc80-c7b2-11ea-8628-e2f28df3dd71.gif)

We should add these C# completion items if they don't already exist in the completion list returned in C# scenarios until the VS LSP snippet experience is ironed out.

**Comment by NTaylorMullen** [comment]
Close out https://github.com/aspnet/AspNetCore-ManualTests/issues/128 once completed.

**Comment by ryanbrandenburg** [comment]
Just so I'm solid on this, this is something we would have to do on the VS and VSCode side because we want to check the results from C# to make sure we're not duplicating?
