### ISSUE TITLE
Razor files created using the "Add->Razor Component" in VS19 don't register correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24068]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1108251/razor-files-created-using-the-add-razor-component.html)._

---
When working on a Blazor/Razor ServerSide project, and using the right click menu on solution explorer to create a new Razor file, the resulting file does not register correctly in Blazor.

Views using the component don't show up in purple and tags in the IDE are red squiggled.

If however I right click and Add->New Empty File, then call that file something.razor, the IDE does register it correctly, and it does show up in intellisense, and it is rendered in purple in views.

Both the first file and the second file are given exactly the same content.

---
#### Peter Shaw on 7/9/2020, 07:58 AM: 

<p>Forgot to mention.</p><p>VS Version is : </p><p>Microsoft Visual Studio Community 2019 Preview<br>Version 16.7.0 Preview 3.1</p>

#### Feedback Bot on 7/9/2020, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/12/2020, 08:05 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
This was fixed in the 16.8-Preview1 milestone. Please download the latest release to see the fix.
