### ISSUE TITLE
ObsoleteAttribute Not Working For Razor Component Parameters

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#24071]
### Describe the bug
When using the ObsoleteAttribute for Parameters in Razor Components, the compiler ignores them and does not produce CS0618 warnings or errors.

### To Reproduce
```
    [Obsolete("This property is obsolete. Use MyParameter2.", false)]
    [Parameter]
    public string MyParameter1 { get; set; } 

    [Parameter]
    public string MyParameter2 { get; set; } 

```
   ...
```
<MyComponent MyParameter1="test" />
```

### Exceptions (if any)
No exception is produced - the compiler ignores the attribute.

### Further technical details
- ASP.NET Core 3.1.4
- Microsoft Visual Studio Community 2019 Preview Version 16.6.0 Preview 6.0

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
