### ISSUE TITLE
Support generic version of Get[Type] & Set[Type] in ISessionCollection

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2407]
_From @hishamco on Saturday, February 28, 2015 1:34:41 PM_

There are many cases the require using more than Int & String, It will be nice if there's a generic version of getting and setting Session objects. I hope to see something like

```
context.Session.Get<bool>("isLoggedIn") 
```

_Copied from original issue: aspnet/Session#3_

**Comment by aspnet-hello** [comment]
_From @Eilon on Sunday, March 1, 2015 12:34:15 PM_

The problem with having fully generic type support is that there is no standard way to convert from an object to a completely arbitrary type. The critical thing to keep in mind with session state is that all data must be serializable because session state might (and often is) on a remote server. This means that complex object graphs or "live" objects cannot be used in session state.

If there are some specific types that you think should be added, we can certainly look at those (e.g. `bool`).

**Comment by aspnet-hello** [comment]
_From @davidfowl on Sunday, March 1, 2015 1:01:05 PM_

We could also look into allowing a generic <T> overload that requires an implementation of an interface, ISerializer to go from T -> byte[]. Somebody can plug in protobuf or [bond](https://github.com/Microsoft/bond)

**Comment by aspnet-hello** [comment]
_From @hishamco on Sunday, March 1, 2015 1:20:45 PM_

You're right @Eilon the object must be serializable, but what i mean is to introduce something like what @davidfowl suggest or we can do something like this

```
if(obj.GetType().IsSerializable)
{
...
}
```

**Comment by aspnet-hello** [comment]
_From @hishamco on Thursday, March 26, 2015 3:22:12 PM_

@davidfowl @Eilon If this may helps the developer to use various types such as bool, DataTable and so on, I can start to plug protobuf or bond

**Comment by aspnet-hello** [comment]
_From @davidfowl on Tuesday, April 7, 2015 12:31:44 AM_

/cc @Tratcher @lodejard

**Comment by aspnet-hello** [comment]
_From @lodejard on Tuesday, April 7, 2015 12:05:50 PM_

+1 for @davidfowl 's earlier suggestion. I like the idea of a set of `byte[] <-> T` formatters the web dev can add explicitly.

Though TBH, I think you would probably add that system as a different service which takes the ISessionCollection as a dependency. Separation of concerns between session provider and the data formatting, ya know.

**Comment by aspnet-hello** [comment]
_From @hishamco on Thursday, April 9, 2015 4:45:07 AM_

@davidfowl @lodejard i think it will be nice if we can provide getting and setting the primitive data types out of the box and let web devs to implement ISerializer for custom and complex objects

**Comment by aspnet-hello** [comment]
_From @hishamco on Sunday, May 3, 2015 4:09:03 AM_

This is a prototype for `ProtobufSessionFormatter` that implements `ISessionFormatter` which is suggested here https://github.com/aspnet/HttpAbstractions/pull/286

``` c#
public class ProtobufSessionFormatter<T> : ISessionFormatter<T>
    {
        public ProtobufSessionFormatter()
        {
            if (typeof(T).IsValueType==false)
            {
                var members = GetPublicMembers();
                RuntimeTypeModel.Default.Add(typeof(T), false).Add(members);
            }
        }

        private string[] GetPublicMembers()
        {
            return typeof(T).GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).Where(m=>m.MemberType==MemberTypes.Field||m.MemberType==MemberTypes.Property).Select(m => m.Name).ToArray();
        }

        public T Deserialize(byte[] value)
        {
            T obj;
            using (var ms = new MemoryStream(value))
            {
                obj= Serializer.Deserialize<T>(ms);
            }
            return obj;
        }

        public byte[] Serialize(T value)
        {
            byte[] data;
            using (var ms = new MemoryStream())
            {
                Serializer.Serialize(ms, value);
                data = ms.ToArray();
            }
            return data;
        }
    }
```

**Comment by aspnet-hello** [comment]
_From @muratg on Friday, September 11, 2015 2:07:22 PM_

I don't believe we will be implementing something like this in V1.  Putting it in backlog for now.

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, September 11, 2015 2:21:44 PM_

Thanks @muratg, hope to be in consideration in the future

**Comment by aspnet-hello** [comment]
_From @OlsonDev on Thursday, March 24, 2016 2:58:38 AM_

Understandable that you wouldn't implement everything in V1 but how about support for the "easy" ones?

``` c#
// Not valid syntax, just conveying a list of types to support
public T Get<T>(string key) where T : 
    byte,
    sbyte,
    int,
    uint,
    short,
    ushort,
    long,
    ulong,
    float,
    double,
    char,
    bool,
    decimal,
    System.Guid,
    string {
    // basically struct, without the ability to have nested reference types (like an actual struct type)
    // ...
}

public T Get<T>(string key) where T : struct, IConvertible {
    if (!typeof(T).IsEnum) throw new ArgumentException("T must be an enum");
    // ...
}
```

`Int32` & `String` alone is pretty limited. :confused:

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, March 24, 2016 9:16:38 AM_

We're not necessarily opposed to adding at least some of these, but I doubt a lot of apps store a `decimal` as a standalone value in session state :smile:

**Comment by aspnet-hello** [comment]
_From @304NotModified on Thursday, March 24, 2016 9:34:56 AM_

Well an (serializable) object storing in session would be nice. (and also bools etc)

**Comment by aspnet-hello** [comment]
_From @OlsonDev on Thursday, March 24, 2016 9:44:37 AM_

I find it strange you picked on `decimal`; `ushort` seems a much better candidate to pick on. :stuck_out_tongue: 

``` c#
var price = HttpContext.Session.Get<decimal>("one-time-discounted-price-offered");
```

Either way, I listed all of the primitive types as I figured the code would be pretty simple.

Personally, I'd much prefer to use `Get<Int32>()` over `GetInt32()`; better/faster IntelliSense/ReSharper refactoring options.

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, April 28, 2017 4:48:45 PM_

@muratg is the closing mean that this will not support?!! It was in the backlog

**Comment by aspnet-hello** [comment]
_From @muratg on Friday, April 28, 2017 5:18:06 PM_

Bringing back for re-triage.

**Comment by davidfowl** [comment]
This should be a layer on top of session

**Comment by hishamco** [comment]
So, there's no plan to support them out of the box

**Comment by davidfowl** [comment]
Nope.
