### ISSUE TITLE
The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible.

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24074]
Reported with an RC1 SDK on a vanilla Blazor WASM project:

```
D:\aspperf5>dotnet build -c Release
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
 
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20367.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(178,5): error NETSDK1032: The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible. [D:\aspperf5\aspperf5.csproj]
```

**Comment by pranavkm** [comment]
The workaround seems to be to clear out the `TargetPlatform`. @akoeplinger do you happen to know what might be triggering this error?

FYI @steveharter

**Comment by akoeplinger** [comment]
> The workaround seems to be to clear out the TargetPlatform. @akoeplinger do you happen to know what might be triggering this error?

Sorry I only saw this now. It looks like an SDK issue to me, if you look at [Microsoft.NET.RuntimeIdentifierInference.targets#L178](https://github.com/dotnet/sdk/blob/5734242453cd80894d75fb4c20bbd9bd2f77588d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets#L178) this should only happen when `PlatformTarget` is not `AnyCPU`. Maybe something recently changed in the SDK to set this to the host platform?

**Comment by pranavkm** [comment]
I'm not seeing this in a rc1 SDK. Perhaps this is something specific to the runtime repo.
