### ISSUE TITLE
[Bug] Asp.net Core issue with authorisation attribute always denied  and Roles core 3.1

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#24087]
I took a bit of time and reproduced this in a minmal repo for you guys hope you can understand what is going on, also how does one say give edit and delete roles to say which user can edit or delete and if restricted send them to the same error page.
Please see full details below

### Describe the bug
When a user is added to the role of manager and you go to a test controller with the decoration as 
 [Authorize(Roles = "manager")]

You will always get the access denied message, which is incorrect.  

### To Reproduce
 Clone the Minmal Viable Testing Repo at 
https://github.com/davidbuckleyni/AuthorisationRepoMS

### Visual Information
Youtube video showing the issue within this repo 

https://www.youtube.com/watch?v=jkUDdt77mFk&feature=youtu.be
1. Change the AppSettings to point to SQL Server

1a) run a.net core add migrations have the dal projector selected in pm console see the txt. File tooling for the context commands.  
  
1b) update database 

2. Login with the user davidbuckleyweb@outlook.com and password Test12345! this will be seeded via the class in helpers folder MISDBContextSeedData
3. Goto Manage roles in the Hyperlinks above click mange on the user above in the grid under the manager role click save to assign the user check the sql table should be as per below

![image](https://user-images.githubusercontent.com/5619229/87854206-31c2e900-c908-11ea-8024-181653a2de7e.png)

Roles Table
![image](https://user-images.githubusercontent.com/5619229/87854215-3e474180-c908-11ea-9ff0-fa8a8cbff2e3.png)

### Exceptions (if any)
Go back to home page click the test hyper link you will recive an access denied message

Repo Url : https://github.com/davidbuckleyni/AuthorisationRepoMS

### Could be wrong
I believe i could be missing some code in the login pages which i have scaffold for you in pages folder to be same as i have it in my app.

Also register page might need some logic to assign the role but the documeantion is that poor surrounding the login and register pages what is needed there in terms of roles.

### Further technical details
Microsoft Visual Studio Community 2019
Version 16.6.4
VisualStudio.16.Release/16.6.4+30309.148
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA907
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.956.60315
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.956.60315
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.956.60315
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.956.60315
Azure Functions and Web Jobs Tools

BusinessObjectEditor   1.0
Information about my package

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Code alignment   14.1.107.0
Code alignment helps you present your code beautifully, enhancing clarity and readability.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

CreateLayoutWizard   1.0
Create layout wizard.

DevExpress Reporting Extension   1.0
A Visual Studio extension that invokes the Report Designer editor for report definition REPX files.

DevExpress Reporting Tools Extension   1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.104.25275
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Package Installer   2.0.103
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

Progress Telerik UI for ASP.NET AJAX Extension   2020.2.612.1
Progress® Telerik® UI for ASP.NET AJAX Extension

Progress Telerik UI for Xamarin Extension   2020.2.612.1
Progress® Telerik® UI for Xamarin Extension

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

Syncfusion ASP.NET Core (Essential JS 1) Project Templates   18.1.0.42
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion Essential JS 1 components.

SyncfusionXamarinMenu Extension   1.0
SyncfusionXamarinMenu Visual Studio Extension Detailed Info

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1062 (d16-6@41e1f0e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by davidbuckleyni** [comment]
Hi @blowdart is that reproducible example more to what you guys need to diagnose the issue. I'm sure am missing some logic in login pages to assign the roles once a user been granted access.

**Comment by davidbuckleyni** [comment]
Hi @blowdart  i found the issue it was the following line.

    .AddClaimsPrincipalFactory<MyUserClaimsPrincipalFactory>();  //<---- add this line 

How ever I am puzzeled why adding an custom claim factory would cause the role authorisation to brake.

This can be closed if you feel the above is the correct answer

**Comment by blowdart** [comment]
How strange, @HaoK could you take a look-see?

**Comment by HaoK** [comment]
You need to make sure you derive from the UserClaimsPrincipalFactory that takes roles into account, the one that takes TRole

https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Core/src/UserClaimsPrincipalFactory.cs#L110
