### ISSUE TITLE
Investigate test failure on helix: DotNetMuxerTests.FindsTheMuxer

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#24082]
After the [latest arcade update](https://github.com/dotnet/aspnetcore/pull/23978), this test has started failing. We need to investigate if this test is valuable and if not just remove it.

cc @dougbu @BrennanConroy

**Comment by lukas-lansky** [comment]
Strange thing that Arcade update breaks [caused null to be returned from here](https://github.com/dotnet/aspnetcore/blob/5a0526dfd991419d5bce0d8ea525b50df2e37b04/src/Shared/CommandLineUtils/Utilities/DotNetMuxer.cs#L54). Any ideas @riarenas @missymessa ? Maybe something to do with https://github.com/dotnet/arcade/issues/5402 ?

**Comment by missymessa** [comment]
> Strange thing that Arcade update breaks [caused null to be returned from here](https://github.com/dotnet/aspnetcore/blob/5a0526dfd991419d5bce0d8ea525b50df2e37b04/src/Shared/CommandLineUtils/Utilities/DotNetMuxer.cs#L54). Any ideas @riarenas @missymessa ? Maybe something to do with [dotnet/arcade#5402](https://github.com/dotnet/arcade/issues/5402) ?

Ricardo's change here was not promoted to .NET Eng - Latest, and was reverted yesterday.

**Comment by BrennanConroy** [comment]
It caused MainModule to return testhost.exe
