### ISSUE TITLE
Issue with Blazor WebAssembly Azure AD and scopes

### ISSUE THREAD

**Issue by AnthonyDewhirst** [dotnet/aspnetcore#24093]
HI, 

I have an issue I believe to be with BlobClient in the sdk, I raised the following issue there: [issue 12298](https://github.com/Azure/azure-sdk-for-net/issues/13298#issuecomment-655517469 ) however I have gotten very little help.

All detail requested in Bug Report can be found there. I don't know how if you can transfer the bug? 

I have a full [repo ](https://github.com/AnthonyDewhirst/BlazorADandBlobs)that only needs little change: secrets added pointing to a storage account, the set up of the SA is detailed in the issue above. 

But to repeat part of the detail, here are what I believe to be the main issues:

I log in using the ms provided services to a work account tennant and request user impersonation scope by default.
I then use a custom TokenCredential to wrap the IAccessTokenProvider.  This seems to not find it locally, make another call to get the access token (this I don't think should be happening as I already fetched on login) I can then get access to the blobs.
However, I then attempt to download the blob and get errors. If this is the first attempt to download the blob, it seemingly works, but then after that it fails. By first time, I mean if I have done this for an hour or so. (Sorry, don't have specifics on this).
Could this be an HttpClient issue?

On a side note I am struggling to get anything other than Info logging or above to log to the browser console and I can't always get the debugger to attach hence why I am having so much difficulty getting anywhere with this issue.

Any help would be much appreciated. 
I am a seasoned dev, but very late to the game with Blazor.

**Comment by MarkSFrancis** [comment]
Is it possible to recreate this issue with the BlobClient in a dotnet console app, or is it a problem that's specific to Blazor?

It might also be helpful to the dotnet team if you could trim down your repo project to be the bear minimum to reproduce the bug, rather than the full app that it is now.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please provide more details, per @MarkSFrancis 's comment above.

**Comment by AnthonyDewhirst** [comment]
Hi, I have just simplified the project as best I can. I think everything that is left is the minimum to show the issue.
Most of this is boilerplate stuff copied from MS docs.
I can work on a console version using an access token and the client later tonight. But I think the real issue comes from the redirects which I won't be able to do in a console app. The only thing this will prove is that the client code works with an access token using my provider, but I think that this is important so I will do that to rule that out.

**Comment by AnthonyDewhirst** [comment]
I have now added the simple console client. However, all it proves is asking for the same scope and using that access token does indeed give access to the blob.
I still think this is an issue with the code flow using msal in blazor.

To get the console to work I had to add a new application type to the app registration and the redirect url as well.
I corrected a silly mistake in the main blazor app as well where during my tiredness I had gotten the loginDisplay and the logout display code the wrong way around. For a small moment I did hope that this was the issue, but no dice.

**Comment by AnthonyDewhirst** [comment]
OK, so I have spent some more time, found one issue and changed a few bits, I now believe that I have the auth side working.
I have also used the blob api within web assembly and it works just fine everytime.
If someone could just check over the way I use the token that would be great but otherwise I am going to throw this back over to the storage team.

**Comment by captainsafia** [comment]
@AnthonyDewhirst Glad you were able to figure this out. We'll close this issue now. If you run into any more Blazor-related issues, please let us know.
