### ISSUE TITLE
Proposal: Create interface for Startup class

### ISSUE THREAD

**Issue by SetTrend** [dotnet/aspnetcore#24094]
From a software architect's perspective, I have a bad feeling with a startup class not implementing an interface and yet being required to fulfill an interface, at least for `ConfigureServices()`.

Despite that fact that we all "know" what methods to implement, shouldn't a base class in the ASP.NET Core framework be more robust?

Is there any hard reason for taking this design approach? Wouldn't it be feasible to introduce an Interface, like `IServiceConfiguration`?

**Comment by Tratcher** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/11050

**Comment by SetTrend** [comment]
Ah, thanks for pointing to that discussion. I didn't find it when I was searching. Probably did something wrong here.
