### ISSUE TITLE
Falsely redirected to localhost when access denied. The server is hosted behind a reverse proxy.

### ISSUE THREAD

**Issue by Banyc** [dotnet/aspnetcore#24101]
### Describe the bug
Falsely redirected to localhost when access denied. The server is hosted behind a reverse proxy. Which means that the server has a domain.

### To Reproduce

Build a server behind a reverse proxy and cause a redirection after access denied.

### Exceptions (if any)

No exception.

### Further technical details
- ASP.NET Core version
  - 3.1
- Include the output of `dotnet --info`
  - shown following:
  ```
  Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777
  ```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  - unrelated

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1 for guidance on working with proxies.

**Comment by Banyc** [comment]
> See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1 for guidance on working with proxies.

The documentation seems to be not helpful.

After adding the header, the same issue persists.

**Comment by Banyc** [comment]
I guess it has something to do with the `Location` header in the 302 response from ASP.NET Core server. I wonder what source the `Location` header is extracted from.

**Comment by Banyc** [comment]
I believe it is the responsibility of the reverse proxy, not ASP. Problem solved.
