### ISSUE TITLE
Allow debugging assemblies that are lazily-loaded

### ISSUE THREAD

**Issue by fred-perkins** [dotnet/aspnetcore#24106]
### Describe the bug
When debugging an assembly loaded using the `AppDomain`. The assembly is loaded using the `Load(byte[] rawAssembly, byte[] rawSymbolStore)` method similar to the one on the `Assembly` class. The debugger refuses to step through to the code found in an external assembly and all attempts to step into will fail. 

### To Reproduce
This can be easily reproduced using this publicly available repository: [PluginTest](https://github.com/fred-perkins/PluginTest).
To test the issue run the [Server Application](https://github.com/fred-perkins/PluginTest/blob/master/PluginTests/Server/PluginTests.Server.csproj). You will be presented with the following page:
![image](https://user-images.githubusercontent.com/16350595/87920634-630af880-ca71-11ea-8f79-55a28a756234.png)

The `Load 'InnerPlugin' Plugin` button provides an in assembly variation of a Plugin which can debugged inside the [Index.razor](https://github.com/fred-perkins/PluginTest/blob/master/PluginTests/Client/Pages/Index.razor) - See the `LoadInnerPlugin` method.

The `Load 'StandalonePlugin' Plugin` however exposes the debugging issue, where the assembly is loaded from an array of bytes, with the PDB supplied as well. Attempting to step into the `plugin.Initialise();` expression will show the issue - Inside the `LoadStandalonePlugin` method in the same [Index.razor](https://github.com/fred-perkins/PluginTest/blob/master/PluginTests/Client/Pages/Index.razor).

### Exceptions (if any)
No exceptions are raised inside visual studio or the browser.

### Further technical details
- ASP.NET Core version: 5.0.0-preview.6.20312.15
- Dotnet Info:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Using Visual studio 16.7.0 Preview 3.0, Enterprise

**Comment by fred-perkins** [comment]
Another similar issue with this style of assembly loading: https://github.com/enkodellc/blazorboilerplate/issues/264

**Comment by captainsafia** [comment]
@mkArtakMSFT I think we should track this for rc1 as a tooling follow-up to the lazy-load work.

**Comment by mkArtakMSFT** [comment]
Let's see if we can find a cheap solution for this in RC1.

**Comment by captainsafia** [comment]
@lewing This is the issue that we can use to brainstorm solutions to the problem of adding debugging support for assemblies that are lazily-loaded after the application (and debugging proxy) has been launched.
