### ISSUE TITLE
For Blazor Webassembly, display details of the error (message, stacktrace) within the blazor-error-ui element.

### ISSUE THREAD

**Issue by jonasarcangel** [dotnet/aspnetcore#24108]
Aside from toggling the visibility of the blazor-error-ui element when encountering an error, I would like the Blazor error handler to also send error details (message, stack trace) for display.

**Comment by captainsafia** [comment]
Note: for implementing this, we'll have to make sure that stack traces don't end up being shown in production environments.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
