### ISSUE TITLE
Blazor Server Side : automatic reconnection to the server

### ISSUE THREAD

**Issue by vd3d** [dotnet/aspnetcore#24103]
### Describe the bug
I have a Blazor server side app, when my computer sleep then wake-up... the server connection is lost.
From a "production" point of view... it is not acceptable, so I have try several possible solutions but none
really work.

1) I have see the documentation about the Circuit, but didn't find any clear way to use it. ie when / how to use it for automatic reconnection. Can it be used for such purpose.

2) I have see other posts here, like: https://github.com/dotnet/aspnetcore/issues/10325
I have add the code proposed by @danroth27 , but no reconnection occur !

I have also check others like: https://stackoverflow.com/questions/58404533/how-can-i-change-the-could-not-reconnect-to-the-server-text-in-blazor

3) Sometimes that are exception inside the application, it seems to break the whole application.
After an exception, the whole application stop to work, any click on any button etc... nothing respond :-(

So, I'm looking for an example, and/or at least some guidance, to make the application way more robust.
 ;-)

Thanks a lot

### To Reproduce
FYI, my app is online www.socloze.com , but can't go in production until I find a robust way to fix this :-(

Any help is really appreciated. Thx

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @vd3d.
For #1, we have recently updated the documentation for Circuits. Please have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#modify-the-reconnection-handler and let us know if you are still missing something in there.

For #2, which is your main concern, we will investigate this further and get back to you at a later time.

**Comment by mkArtakMSFT** [comment]
For #3 the behavior is by-design. The reason is that unhandled exceptions can potentially bring the application to an unknown state. Developers should make sure all calls which can potentially throw are handled.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
