### ISSUE TITLE
Support more parameters for `RenderFragment`

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#24114]
### Is your feature request related to a problem? Please describe.

In Blazor, I have a situation where I need `RenderFragment<T1, T2, T3>`. The specific use case it to abstract some template content so that I can provide multiple implementations for it. This can so far only be emulated with a tuple, i.e. `RenderFragment<(T1, T2, T3)>`.

### Describe the solution you'd like

Similarly to `Func`/`Action`, there could be `RenderFragment<T1, ...TN>`.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
In general, we try to avoid introducing many ways for doing the same thing. That said, we recommend to either using the Tuple syntax or introducing a helper type.

@javiercn I remember you had some specific opinion about these overloads. Do you want to share your thoughts here? Thanks

**Comment by mkArtakMSFT** [comment]
@stefanloerwald thanks for your effort. After some further discussions about this we've decided not to take this change. We're going to close the PR addressing this.
