### ISSUE TITLE
SourceTextDiffer `SourceText.ContentEquals(SourceText)` Call is Expensive

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24127]
[This](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SourceTextDiffer.cs#L72) particular call is fairly expensive and is contributing to a slowdown in the typing/tag autocompletion scenarios. 

Call Path (Total Time / Self Time):
![image](https://user-images.githubusercontent.com/14852843/87983091-acb50c80-ca8c-11ea-9d51-7b054f4ee814.png)

Related Functions (Self Time):
![image](https://user-images.githubusercontent.com/14852843/87983251-ee45b780-ca8c-11ea-97af-2d9a006b76b3.png)

The image also includes some related calls (`LineInfo+get_Item`, `GetSubText` which may also have room for optimizations). Note, ProcessDesignTime optimizations are being tracked [separately](https://github.com/dotnet/aspnetcore/issues/24081). 

CC/ @ajaybhargavb

**Comment by ajaybhargavb** [comment]
Hmm looks like ContentEquals isn't optimized for line content like I thought. We might be better off just looping through the line content and do a character by character comparison.

**Comment by TanayParikh** [comment]
Tried a bunch of different implementations for line equality comparison, however none of them made a impactful difference on perf to justify moving away from the library functionality. 


Default:
|                                           Method |      Mean |     Error |    StdDev |   Op/s |    Gen 0 |    Gen 1 |    Gen 2 |   Allocated |
|------------------------------------------------- |----------:|----------:|----------:|-------:|---------:|---------:|---------:|------------:|
|           'Line Diff - One line change (Typing)' |  1.017 ms | 0.0040 ms | 0.0036 ms | 983.41 |   7.8125 |        - |        - |   686.61 KB |
|   'Line Diff - Significant Changes (Copy-paste)' | 18.961 ms | 0.0634 ms | 0.0529 ms |  52.74 |        - |        - |        - |   754.62 KB |

---

Char by char comparison:
|                                            Method |      Mean |     Error |    StdDev |   Op/s |    Gen 0 |    Gen 1 |    Gen 2 |   Allocated |
|------------------------------------------------- |----------:|----------:|----------:|-------:|---------:|---------:|---------:|------------:|
|           'Line Diff - One line change (Typing)' |  1.129 ms | 0.0022 ms | 0.0021 ms | 885.68 |        - |        - |        - |   125.94 KB |
|   'Line Diff - Significant Changes (Copy-paste)' | 18.686 ms | 0.2008 ms | 0.1676 ms |  53.52 |        - |        - |        - |   191.13 KB |

---

Precomputed line by line hashes (GetHashCode with possible collisions):
|                                          Method |        Mean |      Error |     StdDev |     Op/s |   Gen 0 |  Allocated |
|----------------------------------------------- |------------:|-----------:|-----------:|---------:|--------:|-----------:|
|         'Line Diff - One line change (Typing)' |    911.7 us |   5.346 us |   4.464 us | 1,096.83 | 19.5313 | 1626.72 KB |
| 'Line Diff - Significant Changes (Copy-paste)' | 18,701.2 us | 222.953 us | 208.550 us |    53.47 |       - |  941.56 KB |

---


Cache computed hashes (hashcodecombiner):
|                                          Method |      Mean |     Error |    StdDev |   Op/s |  Gen 0 | Allocated |
|----------------------------------------------- |----------:|----------:|----------:|-------:|-------:|----------:|
|         'Line Diff - One line change (Typing)' |  1.481 ms | 0.0140 ms | 0.0131 ms | 675.24 | 3.9063 | 427.13 KB |
| 'Line Diff - Significant Changes (Copy-paste)' | 18.838 ms | 0.1382 ms | 0.1293 ms |  53.09 |      - | 341.92 KB |

---



 Cache computed hashes (hashcodecombiner + copyto static buffer) + long lines (over 3k chars) removed
|                                         Method |        Mean |     Error |    StdDev |     Op/s |  Gen 0 | Allocated |
|----------------------------------------------- |------------:|----------:|----------:|---------:|-------:|----------:|
|         'Line Diff - One line change (Typing)' |    982.3 us |  2.289 us |  2.029 us | 1,017.99 | 3.9063 |    427 KB |
| 'Line Diff - Significant Changes (Copy-paste)' | 18,500.7 us | 43.645 us | 40.826 us |    54.05 |      - | 341.86 KB |
 
 Original + long lines (over 3k chars) removed:
|                                          Method |        Mean |     Error |    StdDev |     Op/s |  Gen 0 |  Gen 1 | Allocated |
|----------------------------------------------- |------------:|----------:|----------:|---------:|-------:|-------:|----------:|
|         'Line Diff - One line change (Typing)' |    974.5 us |  2.149 us |  2.010 us | 1,026.19 | 7.8125 | 0.9766 | 685.92 KB |
| 'Line Diff - Significant Changes (Copy-paste)' | 18,724.4 us | 39.656 us | 37.094 us |    53.41 |      - |      - | 753.99 KB |

---

 `return oldLineText.GetChecksum().SequenceEqual(newLineText.GetChecksum());`
|                                            Method |      Mean |     Error |    StdDev |   Op/s |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|------------------------------------------------- |----------:|----------:|----------:|-------:|---------:|---------:|---------:|----------:|
|           'Line Diff - One line change (Typing)' |  8.165 ms | 0.0425 ms | 0.0397 ms | 122.48 |  46.8750 |        - |        - |   5.01 MB |
|   'Line Diff - Significant Changes (Copy-paste)' | 27.499 ms | 0.3700 ms | 0.3280 ms |  36.36 |  62.5000 |        - |        - |   5.14 MB |

---

Hashing Functions:
|           Method |       Mean |      Error |     StdDev |    Op/s |   Gen 0 | Allocated |
|----------------- |-----------:|-----------:|-----------:|--------:|--------:|----------:|
|      GetHashCode |   290.0 us |  0.6500 us |  0.6080 us | 3,447.9 |       - |       0 B |
| HashCodeCombiner |   352.6 us |  3.3842 us |  3.1656 us | 2,836.3 |       - |       0 B |
|              MD5 | 2,813.8 us | 24.9302 us | 23.3197 us |   355.4 | 19.5313 | 1520128 B |
|             SHA1 | 2,817.6 us | 34.9636 us | 32.7050 us |   354.9 | 19.5313 | 1680128 B |
|           SHA256 | 4,432.0 us | 49.3119 us | 46.1264 us |   225.6 | 15.6250 | 1840128 B |
