### ISSUE TITLE
Determine if a drag operation was canceled 

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#24124]
Once a drag operation is complete, a dragend event is fired at the source of the drag. This event will fire if the drag was successful or if it was cancelled. One can then use the dropEffect property to determine the kind of operation, If the dropEffect property has the value none during a dragend, then the drag was cancelled. Otherwise, the effect indicates which operation was performed.

Blazor raises the OnDragEnd event correctly, however the DropEffect is always null and thus it is not possible to determine if the drag operation was cancelled.

```
    public void OnDragEnd(DragEventArgs args)
    {
        DragResult = args.DataTransfer.DropEffect;  // **DropEffect is always null**
    }

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
