### ISSUE TITLE
Video is not loaded when the source is set in an async method

### ISSUE THREAD

**Issue by koryphaee** [dotnet/aspnetcore#24123]
When the source of a HTML5 video is bound to a property and that property is set in `OnParametersSetAsync()` the video won't load automatically. It has to be loaded with an additional call to `load()`. The issue only occurs when the property is set in an async method. I assume it's a timing problem where the browser tries loading the source before the async method finishes and the source is set.

I have created a minimal example here: https://blazorfiddle.com/s/w3njyii9.
Since I don't know how long this will be saved here is the component code:

    <video id="vid" controls>
        <source src="@Source" type="video/webm"/>
    </video>

    <video controls>
        <source src="http://dl5.webmfiles.org/big-buck-bunny_trailer.webm" type="video/webm" />
    </video>

    <button onclick="document.getElementById('vid').load()">Load</button>

    @code {
        public string Source { get; set; }

        protected override async Task OnParametersSetAsync()
        {
            // simulate an API call
            await Task.Delay(10);
            Source = "http://dl5.webmfiles.org/big-buck-bunny_trailer.webm";
        }
    }

The first video will not load properly while the second one will. Clicking the load button will cause an explicit call to `load()`. This will cause the first video to also be loaded correctly.

I can reproduce this using Blazor from the latest .NET Core 3.1 version in Chrome 84.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
