### ISSUE TITLE
C# Semantic Colorization

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24126]
TBD

**Comment by ryanbrandenburg** [comment]
Here's how I see the data-flow here:
1. Razor receives semantic legend request, retrieves request from c# and appends Razor's own legend.
1. Razor receives semantic token request.
1. Call through to C# semantic colorization service (we'll probably start out hitting the Full document request every time, but a later optimization would be to use their range request too. Edits become a trickier proposition).
1. Translate positions for C# backing to razor file (where matching).
1. Collate Razor and C# results.
1. Return adjusted/combined results as per LSP spec.

Unfortunately this seems like a rather linear (though involved and fiddly) work-item so I don't know that it makes a lot of sense to sub-divide it further.

Edit: I was putting this all in the original post but I realized I was putting words in @NTaylorMullen's mouth.

**Comment by NTaylorMullen** [comment]
Need to re-evaluate this in 16.8-Preview3. Roslyn wont be landing this in preview1

**Comment by NTaylorMullen** [comment]
Note: Roslyn's implementation of this will be in a private build of VS for 16.8-Preview4. 

Reach out to @dibarbet and he can point you to the right folks or to the build if needed.

**Comment by BrunoBlanes** [comment]
So @dibarbet, hypothetically, if someone like me would want to try said internal build, just for fun and feedback of course, would it be possible?

**Comment by dibarbet** [comment]
@BrunoBlanes the internal build is just the first step - @ryanbrandenburg will have to implement the razor functionality on top of it.  Unfortunately that VS build will not be available publicly :(.  I think the only way to try it out at that point would be to manually checkout and build the VS extensions from the appropriate roslyn and aspnet branches.

Once I know the roslyn branch it will be landing in I can point you to it if you'd like.

**Comment by BrunoBlanes** [comment]
Ah, I undestand it know, thanks!

**Comment by BrunoBlanes** [comment]
@dibarbet I saw that this issue was closed and merged, I was wondering if it was shipped with RC 2 because I still have issues with razor components colorization in that version of the SDK.

**Comment by ryanbrandenburg** [comment]
@BrunoBlanes you will need 16.9 Preview1 or higher with the Experimental Razor editor enabled in order to benefit from this issue. Unfortunately 16.9 Preview1 isn't available yet, but if you still have problems once it is and you try it out file an issue and we'll look into it.

**Comment by BrunoBlanes** [comment]
Cool, thanks for the update, I'll wait for 16.9.
