### ISSUE TITLE
Tracking: avoid suppressing SYSLIB0001 in shipping sources

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/aspnetcore#24138]
There are a few cases in the sources where aspnet is comparing `if (encoding == Encoding.UTF7) { /* do something */ }`. Since this accesses the `Encoding.UTF7` property getter, a warning is produced.

From https://github.com/dotnet/docs/issues/19274:

__If you're trying to compare an `Encoding` instance against `Encoding.UTF7`__, consider instead performing a check against the well-known UTF-7 code page (`65000`). This has the dual advantage that it both avoids the warning and handles some edge cases (such as somebody having subclassed `UTF7Encoding`).

```cs
void DoSomething(Encoding enc)
{
    // don't perform the check this way; it produces a warning and misses some edge cases
    if (enc == Encoding.UTF7)
    {
        // encoding is UTF-7
    }

    // instead, perform the check this way
    if (enc != null && enc.CodePage == 65000)
    {
        // encoding is UTF-7
    }
}
```

**Comment by mkArtakMSFT** [comment]
@pranavkm is this something on the platform level or on MVC?

**Comment by pranavkm** [comment]
IIRC, there's two usages of this in HttpAbstractions. /cc @Tratcher

**Comment by Tratcher** [comment]
Every UTF7 instance in AspNetCore is in a check that prevents its usage:
https://github.com/dotnet/aspnetcore/search?q=UTF7&unscoped_q=UTF7
https://github.com/dotnet/aspnetcore/blob/a4dd539b40fe5fd69c2a968987bc6b9efb305979/src/Http/WebUtilities/src/MultipartSectionStreamExtensions.cs#L38-L42
https://github.com/dotnet/aspnetcore/blob/a4dd539b40fe5fd69c2a968987bc6b9efb305979/src/Http/WebUtilities/src/FormPipeReader.cs#L51-L55
https://github.com/dotnet/aspnetcore/blob/a4dd539b40fe5fd69c2a968987bc6b9efb305979/src/Http/Http/src/Features/FormFeature.cs#L280-L284

**Comment by GrabYourPitchforks** [comment]
I clarified the breaking change doc a bit. The reason we discourage checks against `Encoding.UTF7` directly is that:

```cs
var a = Encoding.UTF7;
var b = new UTF7Encoding();
Console.WriteLine(a == b); // prints "False"

var a = Encoding.UTF7;
var b = Encoding.GetEncoding("utf-7", EncoderFallback.ExceptionFallback, DecoderFallback.ExceptionFallback);
Console.WriteLine(Equals(a, b)); // prints "False"
```

The code page check is the more reliable way to perform this check.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/28913
