### ISSUE TITLE
Cannot render raw json response from HttpTrigger

### ISSUE THREAD

**Issue by pheuter** [dotnet/aspnetcore#24133]
# Context
I'm building out an Azure Functions F# Class Library project and would like to use [FSharp.Json](https://vsapronov.github.io/FSharp.Json/) as the main (de)serialization library so that I can handle discriminated unions, options, and other F# types more idiomatically as I read and write json via HttpTrigger functions. In order to do that, I would like to turn off the default MVC OutputFormatters so that I can pass through my custom serialized Json instead.

# Setup
I have created a Startup file that looks like this:

```fsharp
type Startup() =
    inherit FunctionsStartup()

    override _.Configure(builder: IFunctionsHostBuilder) =
        builder.Services.AddMvcCore(fun options ->
            options.OutputFormatters.RemoveType(typeof<StringOutputFormatter>)
            options.OutputFormatters.RemoveType(typeof<SystemTextJsonOutputFormatter>))
        |> ignore

module Assembly =
    [<assembly:FunctionsStartup(typeof<Startup>)>]
    do ()
```

And then in my HttpTrigger I attempt to serialize my types using the third partly library and respond back with a json:

```fsharp
let run ([<HttpTrigger(...)>] req: HttpRequest) =
    async {
        let! result = ...

        // string
        let serializedUsers = Json.serialize result

        req.HttpContext.Response.ContentType <- "application/json"
        return serializedUsers
    }
    |> Async.StartAsTask
```

# Problem
What ends up happening is my json string gets double encoded, meaning it is returned to the user as a json string containing my json array, instead of an actual json array. This suggests that there is still some automatic formatting taking place after my serialized json string is returned from the HttpTrigger, despite my removing the OutputFormatters in Startup.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/92698/87974185-a8422100-ca97-11ea-8caa-eb9cd4899bde.png">

# Possible alternative?
If not via OutputFormatters, is there any way that I can have an HttpTrigger function return a raw JSON string with the proper `application/json` Content-Type without having it be re-encoded by the framework?

Perhaps something like `Content("", "application/json")` that's available in ASP.NET Core MVC?

**Comment by captainsafia** [comment]
@pheuter Thanks for opening this issue! We don't believe that this is an issue related to MVC. Can you reach out to the functions team with this problem to see if they can provide insight.

https://github.com/azure/azure-functions

**Comment by pheuter** [comment]
Hi @captainsafia, thanks for the response! I was afraid you might suggest that, I initially opened up this issue in that repo, but noticed that the response time is significantly longer than on this one, and the problem is related to certain MVC features like OutputFormatters so figured I'd give it a go. This is currently affecting our development significantly so some urgency would go a long way.

**Comment by captainsafia** [comment]
@pheuter Totally understand. I'd recommend StackOverflow or other support avenues for this. Your code looks fine from an MVC perspective but something funky might be going on with the libraries used.
