### ISSUE TITLE
How to Authenticate to SignalR with Azure AD on a Web API

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#24135]
---
**Issue moved from SignalR/SignalR#4485**
- Please respond to @greenygh0st.

---

_From @greenygh0st on Monday, July 20, 2020 10:26:41 PM_

So we are current running on Angular application on top of a .NET Core Web API - both are protected by Azure AD. These pieces are working as expected and the user requested are properly validated against Azure AD authentication. However, when I try to add a SignalR hub and I add the authorize attribute to it the Angular application is unable to authorize to the hub. If I remove the Authorize attribute then the Angular application connects to SignalR running on the Web API.

Angular Connection Code
```
public startConnection = () => {
    const hubUri = environment.apiUri;
    this.hubConnection = new signalR.HubConnectionBuilder()
                            .withUrl(hubUri, {
                              accessTokenFactory: () => this.authService.getCurrentAccessToken(),
                              skipNegotiation: true,
                              transport: signalR.HttpTransportType.WebSockets
                            })
                            .build();

    this.hubConnection
      .start()
      .then(() => {
        console.log('Connection started');
      })
      .catch(err => {
        console.log('Error while starting connection: ' + err);
      });
  }
```

Relevant Startup.cs
```
services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                 .AddAzureADBearer(options => {
                     Configuration.Bind("AzureAdSignIn", options);
                 });

...

app.UseCors(AllowedOrigins);
app.UseHttpsRedirection();
app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<EventHub>("/es");
                endpoints.MapControllers();                
            });
```

So my question is how is this properly done? I have not been able to find any specific documentation on how to authenticate SignalR to Azure AD. 

Thank you for your time!

**Comment by BrennanConroy** [comment]
You likely need to add some custom logic to grab the "access_token" value from the query string and set the bearer token.
Take a look at the docs for JWT auth for an example https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#bearer-token-authentication

**Comment by greenygh0st** [comment]
I am familiar with how to handle if the API were generating the tokens and the authorization was handled by AddJwtBearer method.
```
.AddJwtBearer
   options.Events = new JwtBearerEvents
   ...get the token from the query string
```

It doesn't seem like the AddAzureADBearer had a comparable Events object. So essentially it seems like what you are saying is that Azure AD tokens have to be manually verified? But how does that work with the token audience?

With the Web API, when it receives the client MASL token it retrieves its own token from Azure AD (each token is intended for a specific audience). So I am trying to understand how to square this all up with SignalR. SignalR would then need its own Azure AD identity/access token as well?

**Comment by BrennanConroy** [comment]
I think you should be able to call `.AddJwtBearer(AzureADDefaults.JwtBearerAuthenticationScheme, options => { ... })` in order to configure the settings

**Comment by greenygh0st** [comment]
Okay I'll give that a try ASAP and see if that works. Thanks!

**Comment by greenygh0st** [comment]
So this oddly throws a builder error `Scheme already exists: Bearer`

![image](https://user-images.githubusercontent.com/1551020/87996567-4940d400-cab8-11ea-9b07-c95072cc5605.png)

When I comment out the .AddJwtBearer and add back .AddAzureADBearer it works as before.

**Comment by BrennanConroy** [comment]
@Tratcher What is the correct way to use AzureAD Bearer Auth with a query string value for the token?

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1#configure-the-underlying-openidconnectoptionsjwtbearercookie-options

**Comment by greenygh0st** [comment]
Is there any more specific direction you can give in using this? The documentation seems a bit sparse on explanation.

I would assume that services.Configure<JwtBearerOptions> is used in conjunction with .AddAzureADBearer() and are the options then similar to the OnMessageReceived example?

**Comment by BrennanConroy** [comment]
You would use both `.AddAzureADBearer()` and the `services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options ...)` method, the options will be of type `JwtBearerOptions` which correlates to the `OnMessageReceived` example.

**Comment by greenygh0st** [comment]
Sorry for the delay on this. Been swamped this week. Will try to review today or Monday if this resolves it I will close the ticket.

**Comment by greenygh0st** [comment]
The above suggestion is still causing an error. So the below code returns the following error: `failed: HTTP Authentication failed; no valid credentials available`

```
// original code - works correctly with Azure AD backed Web API
services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                 .AddAzureADBearer(options => Configuration.Bind("AzureAdSignIn", options));

// added per recommendation
services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options => {
    options.Events = new JwtBearerEvents
    {
        OnMessageReceived = context =>
        {
            var accessToken = context.Request.Query["access_token"];

            // If the request is for our hub...
            var path = context.HttpContext.Request.Path;
            if (!string.IsNullOrEmpty(accessToken) &&
                (path.StartsWithSegments("/es"))) // hub url
            {
                // Read the token out of the query string
                context.Token = accessToken; // does get called 👍 
            }
            return Task.CompletedTask;
        }
    };
});
```
This is the same token we send to the API for other API requests which is obtained by the Angular client application from Azure AD. When used in this way there are no issues, it just fails with SignalR. Is there something missing from this code? Or is there something specific that has to be done with Azure AD itself?

**Comment by greenygh0st** [comment]
Any thoughts further thoughts?
