### ISSUE TITLE
Request OpenIdConnectHandler._configuration visible in child class 

### ISSUE THREAD

**Issue by tai-yi** [dotnet/aspnetcore#24143]
My application is integrated an OIDC provider, the op refresh JWKS everyday,  my application got `SecurityTokenSignatureKeyNotFoundException`  everyday on every instance.

The Oidc manager refresh time is default value(1h).

In the OpenIdConnectHandler, just request refresh oidc configuration, but it will work on next request.

I add a retry logic when I got `SecurityTokenSignatureKeyNotFoundException`,  but doesn't work, because the variable `_configuration`  is not null.

code in `OpenIdConnectHandler`
```C#
if (_configuration == null && Options.ConfigurationManager != null)
 {
      Logger.UpdatingConfiguration();
     _configuration = await Options.ConfigurationManager.GetConfigurationAsync(Context.RequestAborted);
}
```

**Comment by tai-yi** [comment]
**Update**
Right now, I am using Reflection set `_configuration` to null.

```C#
public class KeyRingOpenIdConnectHandler : OpenIdConnectHandler
    {
        private OpenIdConnectMessage _codeFlowMessage;

        private readonly static Lazy<System.Reflection.FieldInfo> _lazyConfigurationField = new Lazy<System.Reflection.FieldInfo>(() =>
            {
                return typeof(OpenIdConnectHandler).GetField("_configuration",
                    System.Reflection.BindingFlags.Public |
                    System.Reflection.BindingFlags.NonPublic |
                    System.Reflection.BindingFlags.Instance |
                    System.Reflection.BindingFlags.GetField |
                    System.Reflection.BindingFlags.SetField);
            });

        public KeyRingOpenIdConnectHandler(IOptionsMonitor<OpenIdConnectOptions> options, ILoggerFactory logger, HtmlEncoder htmlEncoder, UrlEncoder encoder, ISystemClock clock) : base(options, logger, htmlEncoder, encoder, clock)
        {
        }

        protected override async Task<HandleRequestResult> HandleRemoteAuthenticateAsync()
        {            
            var result = await base.HandleRemoteAuthenticateAsync();
            if (result.Failure is SecurityTokenSignatureKeyNotFoundException && Options.RefreshOnIssuerKeyNotFound)
            {
                _lazyConfigurationField.Value.SetValue(this, null);
                Logger.LogInformation("Retry HandleRemoteAuthenticate on TokenSignatureKeyNotFound.");
                return await base.HandleRemoteAuthenticateAsync();
            }
            return result;
        }

        protected override async Task<OpenIdConnectMessage> RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
        {
            if (_codeFlowMessage == null)
                _codeFlowMessage = await base.RedeemAuthorizationCodeAsync(tokenEndpointRequest);
            return _codeFlowMessage.Clone();
        }
    }
```

**Comment by Tratcher** [comment]
> My application is integrated an OIDC provider, the op refresh JWKS everyday

It's standard practice to rotate keys so that the old keys are still valid for a period after the new keys are introduced. Are they not doing this?

We've discouraged anyone from deriving from OpenIdConnectHandler, it's not well factored for that kind of extensibility.

> The Oidc manager refresh time is default value(1h).

The default is 1 day.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a55020dba088171882bc3b4da3882772dd6ff3d2/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L48
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a55020dba088171882bc3b4da3882772dd6ff3d2/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs#L134

If they're properly rotating keys then I suggest changing the interval on the ConfigurationManager to 11 hours. That should give you plenty of leeway to get fresh keys.

I do not recommend forcing a validation retry, it was intentionally not designed for that. That retry pattern lets the client send invalid tokens that force the server to to significant extra work. This has been used as a DOS vector in the past.

**Comment by tai-yi** [comment]
@Tratcher , thanks for correcting my impression about default `AutomaticRefreshInterval`. 

I think decrease `AutomaticRefreshInterval` could not avoid the issue, see below time line.
```
app|---------▷------▷------▷          
-op|---------------------◕
...0---4--8--12--16--20--24--28--32--------> t
```
▷ get oidc config
◕ op rotate key

For DOC vector, I don't have any idea, but I see there is a `MinimumRefreshInterval` in ConfigurationManager, and I cached the `_codeFlowMessage`.

**Comment by Tratcher** [comment]
That's what overlapping key rotation is for. Ask you op about that.

**Comment by tai-yi** [comment]
Here is the suggestion from my OIDC support😂:

`I suggest to you, to either request to the JSWK endpoint on every token validation or to perform a cache update, once the validation fails to ensure, the validation fails not because of an outdated signing key`

**Comment by Tratcher** [comment]
@blowdart any comment or references about key rotation best practices?

@tai-yi for future reference, what provider is this?

**Comment by blowdart** [comment]
I think you've said it all. I know Azure are aware of the need for better key rotation in AAD, and they're also aware retrieving the keys on each request is not a valid solution.

**Comment by tai-yi** [comment]
@Tratcher our entiprise OIDC service is provided by PingID.

**Comment by blowdart** [comment]
There's not a lot we can do here, We would consider such a drastic key change, without an overlap period rather strange, and their advice to retrieve on every request is a DoS waiting to happen, and caching would mean each validation would be blocking, as you wait to see if the cache needs updating.

**Comment by tai-yi** [comment]
@blowdart , thanks for your help.

I there is 16 keys show in JWKS response.
I have written console app to observe the key routate behavier, they routate 8 keys about every 12 hours.

The key point is the new token issued from OIDC should not use the newest key, they should give some time to help the key distribution.

In current situation, looks retry OIDC sign in callback token validation is better, seems no better idea.
