### ISSUE TITLE
EnableSessionLock option for SessionOption and default to false

### ISSUE THREAD

**Issue by xboxeer** [dotnet/aspnetcore#24148]
### Is your feature request related to a problem? Please describe.
This is a question comes from a Stackoverflow question [Enable asp.net core session](https://stackoverflow.com/questions/62563250/enable-asp-net-core-session-locking)
### Describe the solution you'd like
Add another property in SessionOption class named EnableSessionLock, default to false, when setting to true, session lock is enable.
Meanwhile, to support a lock, add GetLock and RleaseLock method in the IDistributedCache interface so that the underlying session storage can implement the lock function 

### Additional context
In our docs I understand that Session behavior is different from ASP.NET that it is currently none locking by design. However in future asp.net core version, can we make it a _by default_ ? since for our customer, to achieve a lock enabled session may requires a lot of code working, and this will bringing lots of issue if their code is not robust enough

**Comment by Tratcher** [comment]
There are no plans to support locked sessions, they cause significant scalability and implementation problems. These scenarios are better addressed working directly with an application database.
