### ISSUE TITLE
Esempio

### ISSUE THREAD

**Issue by JoeVigGitHub** [dotnet/aspnetcore#24145]
### Logs & Exceptions

Please collect the data below before reporting your issue to aid us in diagnosing the root cause.

#### Activity log
[Here](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019#to-examine-the-activity-log) are the instructions on how to generate/acquire one.

#### Razor Language Server Client log

<details>
<summary>Razor Language Server Client Log Output</summary>

Paste log output here

</details>

#### HTML Language Server Client log

<details>
<summary>HTML Language Server Client Log Output</summary>

Paste log output here

</details>

### Further technical details
- VS version (Help => About Microsoft Visual Studio, i.e. 16.8.0 Preview 1 30313.27...). If in Codespaces there will be two versions (server and client), please provide both.
- Scenario (Local, LiveShare, Codespaces)

### Pre-requisite checklist
- [ ] Steps to reproduce the issue
- [ ] Visual Studio Activity Log attached.
- [ ] Razor Language Server client logs included.
- [ ] HTML Language Server client logs included

**Comment by TanayParikh** [comment]
Thank you for filing an issue. 

I don't see any specifics on the issue (just the issue template), was something else to be included?
