### ISSUE TITLE
Incredibly slow compile/build time for Blazor project

### ISSUE THREAD

**Issue by hesuruio** [dotnet/aspnetcore#24156]
We have a fairly large Blazor project and the compile/build time takes around 4 minutes.

We tried building in the following scenarios with similar results:

- build using VS 16.6.4 stable
- build using VS 16.7.0 Preview 4.0
- build using VS Code 1.47.2
- build using command line dotnet build --no-incremental

I have attached a binary log from the command line build.
[msbuild.zip](https://github.com/dotnet/aspnetcore/files/4954619/msbuild.zip)

**From Visual Studio:**
Target Performance Summary:
        * ms  AssignTargetPaths                          3 calls
        * ms  CopyAdditionalFiles                       10 calls
        * ms  GetCopyToOutputDirectoryItems              1 calls
        * ms  GetNativeManifest                          5 calls
        * ms  GetTargetFrameworks                        6 calls
        * ms  GetTargetPath                              9 calls
        * ms  GetTargetPathWithTargetPlatformMoniker     8 calls
        * ms  ResolveCurrentProjectStaticWebAssetsInputs   2 calls
        * ms  _GetCopyToOutputDirectoryItemsFromThisProject   3 calls
        * ms  _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences   1 calls
        * ms  _GetProjectReferenceTargetFrameworkProperties   3 calls
        * ms  _PopulateCommonStateForGetCopyToOutputDirectoryItems   3 calls
        * ms  _SplitProjectReferencesByFileExistence     3 calls
        0 ms  RazorGenerateComponentDefinition           1 calls
        0 ms  RazorComponentGenerate                     1 calls
        0 ms  DesignTimeXamlMarkupCompilation            1 calls
        0 ms  ResolveCodeAnalysisRuleSet                 1 calls
        0 ms  _GenerateRazorAssemblyInfo                 1 calls
        0 ms  RazorComponentGenerateCore                 1 calls
        0 ms  RazorGenerate                              1 calls
        0 ms  _HashRazorComponentInputs                  1 calls
        0 ms  _RemoveRazorDeclartionsFromCompile         1 calls
        0 ms  PrepareForRazorComponentGenerate           1 calls
        0 ms  ResolveRazorComponentInputs                1 calls
        0 ms  ResolveRazorConfiguration                  1 calls
        0 ms  BeforeCompile                              1 calls
        0 ms  AfterBuild                                 1 calls
        0 ms  InitializeSourceControlInformation         1 calls
        0 ms  GenerateTargetFrameworkMonikerAttribute    1 calls
        0 ms  _SetTargetFrameworkMonikerAttribute        1 calls
        0 ms  GenerateMSBuildEditorConfigFile            1 calls
        0 ms  GenerateMSBuildEditorConfigFileShouldRun   1 calls
        0 ms  PrepareForRazorGenerate                    1 calls
        0 ms  _CollectTargetFrameworkForTelemetry        1 calls
        0 ms  ComputeRunAnalyzers                        1 calls
        0 ms  _GenerateCompileInputs                     1 calls
        0 ms  CoreBuild                                  1 calls
        0 ms  PrepareForRun                              1 calls
        0 ms  _ResolveRazorTargetPath                    1 calls
        0 ms  CopyFilesToOutputDirectory                 1 calls
        0 ms  ComputeDependencyFileCompilerOptions       1 calls
        0 ms  _CopySourceItemsToOutputDirectory          1 calls
        0 ms  _CopyOutOfDateSourceItemsToOutputDirectory   1 calls
        0 ms  GetTypeScriptCopyToOutputDirectoryItems    1 calls
        0 ms  _RemoveComponentAnalyzer                   1 calls
        0 ms  GetCopyToOutputDirectoryXamlAppDefs        4 calls
        0 ms  _PrepareForStaticWebAssets                 3 calls
        0 ms  ResolveStaticWebAssetsInputs               3 calls
        0 ms  GetCurrentProjectStaticWebAssets           2 calls
        0 ms  _RazorGetCopyToOutputDirectoryItems        3 calls
        0 ms  _RazorPrepareForRun                        1 calls
        0 ms  RazorCompile                               1 calls
        0 ms  PrepareForRazorCompile                     1 calls
        0 ms  GenerateRazorTargetAssemblyInfo            1 calls
        0 ms  ResolveRazorCompileInputs                  1 calls
        0 ms  _ResolveGeneratedRazorCompileInputs        1 calls
        0 ms  CreateSatelliteAssemblies                  1 calls
        0 ms  _GenerateSatelliteAssemblyInputs           1 calls
        0 ms  Compile                                    1 calls
        0 ms  AfterCompile                               1 calls
        0 ms  CleanXsdCodeGen                            1 calls
        0 ms  _BeforeVBCSCoreCompile                     1 calls
        0 ms  SetWin32ManifestProperties                 1 calls
        0 ms  GenerateAssemblyInfo                       1 calls
        0 ms  PrepareResources                           1 calls
        0 ms  ExpandSDKReferences                        1 calls
        0 ms  ResolveSDKReferences                       1 calls
        0 ms  PrepareProjectReferences                   3 calls
        0 ms  ResolvePackageDependenciesForBuild         3 calls
        0 ms  AddTransitiveFrameworkReferences           1 calls
        0 ms  ResolveRazorGenerateInputs                 3 calls
        0 ms  GetReferenceAssemblyPaths                  1 calls
        0 ms  GetFrameworkPaths                          1 calls
        0 ms  BuildOnlySettings                          1 calls
        0 ms  BeforeBuild                                1 calls
        0 ms  EnableIntermediateOutputPathMismatchWarning   1 calls
        0 ms  CollectPackageReferences                   1 calls
        0 ms  _CheckForObsoleteDotNetCliToolReferences   1 calls
        0 ms  _GetProjectJsonPath                        1 calls
        0 ms  _CheckForNETCoreSdkIsPreview               1 calls
        0 ms  _CheckForUnsupportedCppNETCoreVersion      1 calls
        0 ms  _CheckForUnsupportedNETCoreVersion         1 calls
        0 ms  ResolveFrameworkReferences                 1 calls
        0 ms  AfterResolveReferences                     1 calls
        0 ms  Build                                      1 calls
        0 ms  ResolveReferences                          1 calls
        0 ms  ResGen                                     1 calls
        0 ms  CreateCustomManifestResourceNames          1 calls
        0 ms  AfterResGen                                1 calls
        0 ms  PrepareResourceNames                       1 calls
        0 ms  _ComputeNETCoreBuildOutputFiles            3 calls
        0 ms  BeforeResGen                               1 calls
        0 ms  SplitResourcesByCulture                    1 calls
        0 ms  ExpressionBuildExtension                   1 calls
        1 ms  _ComputeUserRuntimeAssemblies              1 calls
        1 ms  GetAssemblyVersion                         1 calls
        1 ms  _RazorCopyFilesToOutputDirectory           1 calls
        1 ms  GetRazorTargetAssemblyAttributes           1 calls
        1 ms  CoreGenerateAssemblyInfo                   1 calls
        1 ms  _HashRazorGenerateInputs                   1 calls
        1 ms  _SetEmbeddedWin32ManifestProperties        1 calls
        1 ms  CoreResGen                                 1 calls
        1 ms  _ComputePackageReferencePublish            3 calls
        1 ms  _FixupRazorReferencePathForRazorCompile    1 calls
        1 ms  _DefaultMicrosoftNETPlatformLibrary        3 calls
        1 ms  GenerateCompiledExpressionsTempFile        1 calls
        1 ms  IncludeTransitiveProjectReferences         3 calls
        1 ms  ValidationExtension                        1 calls
        1 ms  AddSourceRevisionToInformationalVersion    1 calls
        1 ms  PreXsdCodeGen                              1 calls
        1 ms  AssignRazorComponentTargetPaths            1 calls
        1 ms  BeforeResolveReferences                    1 calls
        1 ms  _CheckForCompileOutputs                    1 calls
        2 ms  CreateGeneratedAssemblyInfoInputsCacheFile   1 calls
        2 ms  IncrementalClean                           1 calls
        2 ms  ResolveLockFileAnalyzers                   3 calls
        2 ms  _CheckForLanguageAndFeatureCombinationSupport   3 calls
        2 ms  _GetRestoreProjectStyle                    1 calls
        2 ms  _CreateRazorTargetAssemblyInfoInputsCacheFile   1 calls
        2 ms  GetAssemblyAttributes                      1 calls
        3 ms  UpdateAspNetToFrameworkReference           2 calls
        3 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
        4 ms  ResolveTargetingPackAssets                 1 calls
        4 ms  _ResolveComponentRazorGenerateInputs       1 calls
        4 ms  CheckForDuplicateItems                     1 calls
        5 ms  AssignProjectConfiguration                 3 calls
        6 ms  ResolveLockFileCopyLocalFiles              3 calls
        6 ms  ApplyImplicitVersions                      3 calls
        6 ms  _CopyFilesMarkedCopyLocal                  1 calls
        7 ms  _CreateStaticWebAssetsInputsCacheFile      3 calls
        9 ms  RazorGenerateComponentDeclaration          1 calls
       11 ms  ResolveAssemblyReferenceRazorGenerateInputs   1 calls
       12 ms  CheckForImplicitPackageReferenceOverrides   3 calls
       12 ms  GenerateStaticWebAssetsManifest            3 calls
       12 ms  _CleanGetCurrentAndPriorFileWrites         1 calls
       12 ms  ProcessFrameworkReferences                 3 calls
       13 ms  _ResolveRazorGenerateOutputs               1 calls
       14 ms  _GenerateCompileDependencyCache            1 calls
       17 ms  GenerateBuildDependencyFile                1 calls
       23 ms  _ResolveRazorComponentOutputs              1 calls
       32 ms  ResolvePackageAssets                       3 calls
       32 ms  PrepareForBuild                            1 calls
       33 ms  ResolveLockFileReferences                  3 calls
       35 ms  _HandlePackageFileConflicts                1 calls
       50 ms  FindReferenceAssembliesForReferences       1 calls
      120 ms  ResolveReferencedProjectsStaticWebAssets   3 calls
      186 ms  ResolveAssemblyReferences                  1 calls
      330 ms  ResolveProjectReferences                   1 calls
      373 ms  _ComputeReferenceAssemblies                1 calls
      572 ms  RazorCompileComponentDeclaration           1 calls
     1602 ms  ResolveTagHelperRazorGenerateInputs        1 calls
     3097 ms  RazorCoreGenerate                          1 calls
    242346 ms  CoreCompile                                1 calls
        (* = timing was not recorded because of reentrancy)

Task Performance Summary:
        * ms  AssignTargetPath                          14 calls
        * ms  CallTarget                                 2 calls
        * ms  MSBuild                                    5 calls
        0 ms  Telemetry                                  1 calls
        0 ms  ReadLinesFromFile                          1 calls
        0 ms  Delete                                     2 calls
        0 ms  ResolveCodeAnalysisRuleSet                 1 calls
        0 ms  GetAssemblyVersion                         1 calls
        0 ms  AssignCulture                              1 calls
        0 ms  ResolveFrameworkReferences                 1 calls
        0 ms  GetPackageDirectory                        6 calls
        0 ms  RemoveDuplicates                           2 calls
        0 ms  ShowPreviewMessage                         1 calls
        1 ms  ApplyImplicitVersions                      3 calls
        1 ms  GetFrameworkPath                           1 calls
        1 ms  Message                                    4 calls
        1 ms  Hash                                       8 calls
        1 ms  FindUnderPath                              5 calls
        1 ms  MakeDir                                    4 calls
        1 ms  CheckForDuplicateFrameworkReferences       3 calls
        2 ms  GetRestoreProjectStyleTask                 1 calls
        2 ms  Touch                                      2 calls
        3 ms  CheckIfPackageReferenceShouldBeFrameworkReference   4 calls
        3 ms  ResolveAppHosts                            3 calls
        3 ms  CheckForDuplicateItems                     3 calls
        3 ms  WriteLinesToFile                           8 calls
        4 ms  Copy                                       3 calls
        4 ms  ResolveTargetingPackAssets                 1 calls
        5 ms  ProcessFrameworkReferences                 3 calls
        5 ms  AssignProjectConfiguration                 3 calls
        5 ms  ConvertToAbsolutePath                      1 calls
        7 ms  JoinItems                                  3 calls
       11 ms  GenerateDepsFile                           1 calls
       11 ms  CheckForImplicitPackageReferenceOverrides   3 calls
       11 ms  GetReferenceNearestTargetFrameworkTask     1 calls
       12 ms  RemoveDir                                  1 calls
       17 ms  ResolveNonMSBuildProjectOutput             1 calls
       22 ms  ResolvePackageFileConflicts                1 calls
       31 ms  ResolvePackageAssets                       3 calls
       32 ms  FindAppConfigFile                          1 calls
      186 ms  ResolveAssemblyReference                   1 calls
     1596 ms  RazorTagHelper                             1 calls
     3082 ms  RazorGenerate                              1 calls
    242910 ms  Csc                                        2 calls
        (* = timing was not recorded because of reentrancy)

Build succeeded.
    0 Warning(s)
    0 Error(s)

**Comment by pranavkm** [comment]
@hesuruio could you try disabling `Nullable` in your `Pbs.Skipper.Gui` project? We had one other issue report where the generated Razor code performed poorly with the compiler's nullability analysis.

**Comment by hesuruio** [comment]
Hi @pranavkm! Thanks for your assistance. That made a significant difference. Close to 27s now from 4 minutes. So is there an issue already raised around nullability and Razor? I would say having `Nullable` enabled is especially important on a large project.

**Comment by pranavkm** [comment]
https://github.com/dotnet/aspnetcore/issues/22945 here's the duplicate issue. The repro app in that issue was particularly contrived which is one of the reasons we didn't dig in to further. If you are able to share a minimal repro that replicates the problem, it'd help.

**Comment by dodyg** [comment]
This problem persists on .NET 5 RC1 btw. In our project `<Nullable>disable</Nullable>` makes a big difference.

**Comment by pranavkm** [comment]
@dodyg do you have a minimal app that reproduces the issue?

**Comment by dodyg** [comment]
I don't but I'll be happy to send you over our in-progress project source code so you can see it yourself. Just let me know the mechanism to submit it.
