### ISSUE TITLE
Blazor components updation issue

### ISSUE THREAD

**Issue by weshall1994** [dotnet/aspnetcore#24155]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by weshall1994** [comment]
please help me to solve this issue.

**Comment by javiercn** [comment]
@weshall1994 thanks for contacting us.

Could you provide the necessary information for us to help you? It's not clear what your issue is.

**Comment by weshall1994** [comment]
Actually I am adding 100 items to the list , the items added to the list
completes within  .010 ms in code but ui takes 14 secs to update

**Comment by javiercn** [comment]
@weshall1994 thanks for the additional details. Can you provide a minimal repro project so that we can understand why the update is taking so long?

Is this server-side blazor or blazor webassembly?

**Comment by weshall1994** [comment]
Server side blazor
