### ISSUE TITLE
Blazor: display name of element/component when duplicate @key encountered

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#24152]
Creating this for tracking.  Submitting a PR in a moment.

**Comment by captainsafia** [comment]
@javiercn Assigning to you to drive PR to completion.

**Comment by mkArtakMSFT** [comment]
@captainsafia @javiercn I just noticed this wasn't on the project board. What is the state of this issue? Should this be marked as `Done` now?

**Comment by captainsafia** [comment]
@mkArtakMSFT Yes -- this is done and will ship with RC1.
