### ISSUE TITLE
Issues within Visual Studio when selecting both Azure AD and Docker Linux support

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet/aspnetcore#24151]
I'm not sure if this is the correct location as this issue deals with Visual Studio and this repository looks to be largely geared toward `dotnet new`. If I'm not in the right spot, feel free to close or forward me elsewhere.

----

Recently, I created a project within Visual Studio. I selected .NET Core MVC. I enabled the options for Azure AD Auth (single organization) and Docker container support with Linux.

Upon publishing my container to an Azure Web app for Containers, I noticed that the redirect URI was specified as always using `http`. 

I opened an issue here: https://github.com/dotnet/aspnetcore/issues/22572

It turns out I needed to do some additional work to enable header forwarding in order for Azure AD auth to work within the container.

I'm hoping that we could get this added to the templating engine so that applications would work out of the box. 

I'd be happy to send along a PR if someone points me in the right direction.

Thanks for all you do!

**Comment by javiercn** [comment]
@grinrag this is the right repo for the aspnetcore templates.

**Comment by Tratcher** [comment]
What version are you using? This should have been addressed back in 3.0. See https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/

@bradygaster

**Comment by SeanKilleen** [comment]
Sorry, I'd missed this in a bunch of notifications. 

@Tratcher I was using Visual studio 2019 with latest updates at the time and .NET Core 3.1 installed. When using the templates, I had to manually add the change for it to work.

Are you saying that you're currently unable to reproduce it with the steps I provided?

**Comment by sebastienros** [comment]
After some investigation, I confirm that the headers forwarder middleware is registered, but it's only enabled if the `ASPNET_ForwardedHeaders_Enabled` environment variable is equal to `true`, or if the `appsettings.json` contains the `"ForwardedHeaders_Enabled": true` setting, or if the Docker file defined the ENV.

However when running the template in VS neither of these are set from what I experienced.

```json
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "qualified.domain.name",
    "TenantId": "22222222-2222-2222-2222-222222222222",
    "ClientId": "11111111-1111-1111-11111111111111111",
    "CallbackPath": "/signin-oidc"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

![image](https://user-images.githubusercontent.com/1165805/132412032-5c75ae64-c12b-436b-a604-a992a3701263.png)

**Comment by bradygaster** [comment]
@Tratcher Might be good to put the setting into the template, but set to `false` - that way it could cue customers to the existence of the setting and potentially ease this process for other folks.

**Comment by Tratcher** [comment]
Where? It's set to true in the actual docker file when published. I wouldn't expect it in appsettings.json since that would conflict with the docker file, but maybe launchsettings.json?

**Comment by sebastienros** [comment]
> It's set to true in the actual docker file when published

Can you point me to the file? I tried with 3.1 templates.

**Comment by Tratcher** [comment]
It's here:
https://github.com/Azure-App-Service/ImageBuilder/blob/0901682fa83f20ecd1ccab6612e8d357dcd15150/GenerateDockerFiles/dotnetcore/debian-9/Dockerfile#L56

**Comment by sebastienros** [comment]
> in the actual docker file

How is the file you shared related to the one that is generated with the template? In the templates the based image is the standard aspnet runtime one. 

```
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
```

**Comment by sebastienros** [comment]
I see, these images are used when we upload/publish a .NET app as is, not when a Docker option is selected in VS.
So this doesn't apply in this case and confirms the problem. IMO the simplest change would be to add the setting to the docker file template, and maybe a few others that the one you pointed at has. If not just for discoverability like Brady is saying.

**Comment by sebastienros** [comment]
@vijayrkn Should I transfer this issue somewhere, or is there a bug in VS I can point to instead?

**Comment by vijayrkn** [comment]
There is an internal tracking bug on our side to set this app setting while publishing to App Service Container. This change is already implemented and should be available in the next update of Visual Studio. I think we can close this issue here.
