### ISSUE TITLE
git clone failing on MessagePack submodule checkout

### ISSUE THREAD

**Issue by NaivE2k4** [dotnet/aspnetcore#24157]
Hello!
I want to build 3.1 from source, so i'm cloning repository.
Current command looks like this
`git.exe clone --progress --recursive --branch release/3.1 --origin asp31-3 -v --depth 1 "https://github.com/aspnet/AspNetCore.git" "D:\ASPNETCOREREPO\asp31-3"`

It goes good, but in the end it outputs this line:
`error: Server does not allow request for unadvertised object 8861abdde93a3b97180ac3b2eafa33459ad52392
Fetched in submodule path 'src/submodules/MessagePack-CSharp', but it did not contain 8861abdde93a3b97180ac3b2eafa33459ad52392. Direct fetching of that commit failed.
`

I tried different command options, googled and looked for issues here, but couldnt find the answer.

**Comment by javiercn** [comment]
@NaivE2k4 thanks for contacting us.

That looks weird. I would suggest you try git submodule init; git submodule update to see if the problem persists. Not sure about what the `--depth 1` flag does, I would recommend you simply do `git clone --recursive https://github.com/aspnet/AspNetCore.git`

**Comment by NaivE2k4** [comment]
> @NaivE2k4 thanks for contacting us.
> 
> That looks weird. I would suggest you try git submodule init; git submodule update to see if the problem persists. Not sure about what the `--depth 1` flag does, I would recommend you simply do `git clone --recursive https://github.com/aspnet/AspNetCore.git`

Very sorry, it appears that my git is kinda broken, checkout worked on another machine! @javiercn javiercn Sorry for taking your time!
