### ISSUE TITLE
Add nullable annotations to identity

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#24165]
For example, GetUserAsync method in UserManager class can return null, but it's not marked with nullable annotation.

**Comment by Youssef1313** [comment]
Note: I think this deserve to be addressed for version 5.0.

**Comment by blowdart** [comment]
@HaoK More nullable in addition to https://github.com/dotnet/aspnetcore/issues/22656

**Comment by blowdart** [comment]
Also linking https://github.com/dotnet/aspnetcore/issues/24201

**Comment by blowdart** [comment]
Closing in favor of aggregating issue, #25310
