### ISSUE TITLE
Enable ICU in blazor

### ISSUE THREAD

**Issue by lewing** [dotnet/aspnetcore#24174]
Since the blazor platform code calls directly into the runtime rather than using the normal initialization code it doesn't have the logic to load the icudt.dat file into the runtime that is required to enable icu.  It will need to copy `icudt.dat` from the runtime pack and insert it into memory using `offset = this.mono_wasm_load_bytes_into_heap (bytes)` and `this.mono_wasm_load_icu_data (offset)` and only do the logic in https://github.com/dotnet/aspnetcore/pull/24163 if that file doesn't exist

**Comment by lewing** [comment]
cc @pranavkm @SteveSandersonMS

**Comment by pranavkm** [comment]
Thanks @lewing. Is this available in the p8 branch?

**Comment by lewing** [comment]
not yet, merge to p8 pr soon

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/39739

**Comment by lewing** [comment]
@pranavkm @mkArtakMSFT  merged in preview8 now
