### ISSUE TITLE
Identifying if a request has a body

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#24175]
It's difficult to check if an HTTP request has a body without actually calling read on that body. The caller might not want to call read because that can have side-effects like 100-continue, throwing, etc.. YARP is one example where we need to know if there is a request body before calling read (https://github.com/microsoft/reverse-proxy/pull/336) because YARP doesn't call read itself, it generates an HttpContent object for HttpClient to call read on.

In HTTP/1.0 a request body must be indicated by a Content-Length.
In HTTP/1.1 a request body must be indicated by a Content-Length or Transfer-Encoding: chunked.
In HTTP/2 (and 3?) Content-Length is optional and Transfer-Encoding: chunked is prohibited. You only know there is no body if you've received the END_STREAM flag.

Http.Sys/IIS have a history of faking HTTP/2 as HTTP/1.1. For requests with bodies and no Content-Length it will add a fake Transfer-Encoding: chunked header.

For YARP it's easy to check for the Content-Length and chunked headers, but checking if an HTTP/2 request has a body on Kestrel isn't possible today.

Proposal: Kestrel should also add a fake header. Either:
- Content-Length: 0 for any request without a body, or
- Transfer-Encoding: chunked for HTTP/2+ request with a body, same as Http.Sys/IIS.

**Comment by Tratcher** [comment]
Note there have been similar complaints about TestServer. If we have Kestrel set at fake header then TestServer should match that.

https://github.com/dotnet/aspnetcore/pull/24107
https://github.com/dotnet/aspnetcore/issues/13273

**Comment by damianh** [comment]
With respect to #21677 may I suggest re-opened issues don't remain "locked and limited to collaborators"?

**Comment by Tratcher** [comment]
@damianh good point, I hadn't noticed the bot locked it. Unlocked.

**Comment by Tratcher** [comment]
#24984 completed the work for all but IIS due to some testing issues. I'll keep this open to address the IIS scenario, but might move it to the next milestone.
