### ISSUE TITLE
A problem on Chrome 84

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/aspnetcore#24184]
I have a child component called `Earth` as follows.

```
<button @onclick="Toggle">
    @if (isMoving)
    {
        <text>Stop Spinning</text>
    }
    else
    {
        <text>Start Spinning</text>
    }
</button>

@code {
    private bool isMoving = true;

    private void Toggle()
    {
        isMoving = !isMoving;
        Console.WriteLine(DateTime.Now);
    }
}
```

It is consumed in a parent routable component named `Index` as follows.
```

@page "/"

<Earth />
```

Running on Chrome version 84 I got a strange result as follows.

![test](https://user-images.githubusercontent.com/50270635/88122029-a8eeca80-cbf1-11ea-8319-0fb65633171e.png)

However, there is no problem on Microsoft Edge version 84.

Feel free to close this issue if it is irrelevant here. Thank you!

#Edit

The minimal project to reproduce the problem can be found in my repository as follows. Note that most people cannot reproduce this issue. I don't know why.

https://github.com/pstricks-fans/ChromeIssue

![Screenshot](https://user-images.githubusercontent.com/50270635/88212127-f108fe00-cc80-11ea-98a8-98d0ea16ae60.png)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by pstricks-fans** [comment]
@mkArtakMSFT : A link to the requested minimal project to reproduce the issue has been added. Thank you.

**Comment by pranavkm** [comment]
@pstricks-fans I tried your app on Chrome 85.0.4 and it no longer reproduces. Feel free to reopen this if you continue seeing this with the updated browser.
