### ISSUE TITLE
Razor Misinterprets JavaScript < Symbol

### ISSUE THREAD

**Issue by KatoFett** [dotnet/aspnetcore#24181]
This is using ASP.Net Core 3.1. The Razor compiler can misread any `<` symbols inside of a `<text></text>` element. For example, this will not compile:

![image](https://user-images.githubusercontent.com/67660601/88120037-4c52c780-cb7f-11ea-988a-fc0eb3134d28.png)

![image](https://user-images.githubusercontent.com/67660601/88120093-67bdd280-cb7f-11ea-81c9-0417b346f720.png)

One workaround is to wrap the `<` symbol in an `Html.Raw()`
![image](https://user-images.githubusercontent.com/67660601/88120618-9a1bff80-cb80-11ea-93b5-23be0aaefb47.png)
But I've seen this throw off JavaScript Intellisense.

Another workaround is to encapsulate the offending for-loop and every line inside with `@:`
![image](https://user-images.githubusercontent.com/67660601/88120225-aa7faa80-cb7f-11ea-9de2-821ee2bb6f2e.png)

While this "solution" works, it can get quite cumbersome when you have a for-loop with 50 lines nested inside.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by KatoFett** [comment]
I would think that recreating this issue would be relatively quick and easy but if an entire project is necessary then I should have one up within a week (busy week).
