### ISSUE TITLE
Remove/disable manual response chunking

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#24186]
If the application specifies a `Transfer-Encoding: chunked` response header then kestrel takes that as a signal that the app has implemented its own chunking and so the server should not auto-chunk. It's not clear that this feature has ever been used as intended, but it does keep breaking apps that are forwarding responses from HttpClient.

Example:
https://github.com/microsoft/reverse-proxy/blob/b2482f606a7dbcbc9b9797b04aed51138da0bd8d/src/ReverseProxy/Service/Proxy/HttpProxy.cs#L589-L594

Proposal: Disable and or remove this feature. Consider adding an option or quirk to re-enable it just in case anybody was using it.

**Comment by davidfowl** [comment]
After giving this more thought, I think removing it is the right decision.

**Comment by halter73** [comment]
I'm all in favor of removing this behavior without a way to configure it via KestrelServerOptions. This behavior has been in Kestrel since pre-1.0, so it's still probably worth adding an AppContext switch just in case.

**Comment by Kahbazi** [comment]
I want to take this issue, but I need a little guidance. Is this the method that needs to be changed?
https://github.com/dotnet/aspnetcore/blob/a67c217976899db93563353daa6276e438fe677b/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1070

**Comment by Tratcher** [comment]
Yeah, probably a change around line 1089 to set _autoChunk if there's already a chunked header. 

Have you seen how we use AppContext for compat switches?

**Comment by Kahbazi** [comment]
> Have you seen how we use AppContext for compat switches?

No.

**Comment by Tratcher** [comment]
Here's an example:
https://github.com/dotnet/aspnetcore/pull/24264/files#diff-9cd158b5cd3cc1183d04bce0f4268654R13-R27

**Comment by Tratcher** [comment]
Ah, here's the wiki I was looking for. https://github.com/dotnet/aspnetcore/wiki/Quirks-mode-switches-in-patches

**Comment by Tratcher** [comment]
Triage: We initially thought this was a Kestrel specific behavior that was both inconsistent and annoying. However, we've now realized that it's implemented consistently across IIS, HttpSys, and Kestrel, and the IIS behavior is out of our control. While it remains annoying, we've decided to leave it here because at least it's consistent.
