### ISSUE TITLE
Performance regression in preview 4 to 7

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [dotnet/aspnetcore#24199]
I usually test previews on a reverse proxy app that has a decent load (10-20 million requests per minute).

The current one is using .net5 preview3, and it was a bit faster then 3.1, but preview4-7 its consistently slower. 

![image](https://user-images.githubusercontent.com/1174384/88177298-02a9c180-cbff-11ea-9d08-c0390a45fc4b.png)

This regression is consistent, 4 to 7 has the same performance.

The machines are running on aws, they have the same machine type and the same linux version (Amazon Linux) and the same version of docker. The only thing that i change is literally the number of the preview on the DockerFile.

Doing some profiling on windows (i'm still struggling a bit to profile on linux) the only thing that seems to change is the scheduling on the Thread Pool and the sockets performance that seems a bit slower, but that's on windows.

My apologies for an issue that is not very actionable, if you need more details ill do my best to provide. 
If there is another channel for this kind of feedback, or this is undesired feedback please let me know.

**Comment by Pilchie** [comment]
@sebastienros can you follow up to get a trace and take a look at what's going on?

**Comment by Rodrigo-Andrade** [comment]
Got a collect on the machine outside docker (its slower inside docker), but this here is weird: 

![image](https://user-images.githubusercontent.com/1174384/88253518-a55a5280-cc88-11ea-883c-e7b63074fb14.png)

System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested() takes a long while some times.

**Comment by sebastienros** [comment]
I have asked another dev if there are known regressions onthe TP for preview7. 
Have you tried with the nightly build of .NET ? Check for the "master" column on this page: https://github.com/dotnet/installer#installers-and-binaries

Something to note is that if the latest, or even preview7 in this case, is still faster than 3.1, it will probably not be looked at for 5.0 as we are getting closer to shipping RCs.

In the meantime you might want to give me some sample .NET app that you think shows the regression so I can measure it myself. Including the kind of payload you use, the methodology (machines, tools), and the numbers you got.

**Comment by sebastienros** [comment]
Maybe I id read the issue too quickly, are you saying that anything version between preview4 up to preview7 is slower than 3.1 on your tests?

**Comment by Rodrigo-Andrade** [comment]
@sebastienros yes

**Comment by sebastienros** [comment]
Then please provide ways to repro the issue, because we are only seeing improvements in perf from 3.1 to 5.0 preview.
And would it be possible for you to share traces on 3.1 and preview 7 so we can see what code paths induce the long  EnsureThreadRequested calls? I can provide you with a shared driver to upload these

**Comment by Rodrigo-Andrade** [comment]
@sebastienros I managed to get traces from preview3 and preview7, you can message me the link.

**Comment by sebastienros** [comment]
But sure we really care about preview 3 in this case but more about .NET 3.1 since you say the regression is from this version. Also can you share your benchmarking strategy, and if possible the kind of code is running? Is we can't report the issue we won't be able to fix it.

**Comment by Rodrigo-Andrade** [comment]
@sebastienros I don't think i get it, preview3 is the last version that don't have the regression, its closer to the code on preview7 (so should be easier to see what changed)? 

The app is a reverse proxy , so a Middleware that forwards requests with HttpClient, so most of the time is spent on kestrel and HttpClient.

For tracing i'm using dotnet-trace on a aws ec2 machine with 8 virtual cores. Both traces were made on the same machine.

Ill try to make a small repro, if you still want the traces let me know.

**Comment by davidfowl** [comment]
cc @kouvel

**Comment by Rodrigo-Andrade** [comment]
Made a repro:

https://gist.github.com/Rodrigo-Andrade/dabd77a2df360b75ace7e9391fabcddc

Tests on the same machine (aws ec2 c5.2xlarge).

.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     amzn
 OS Version:  2018.03
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /root/dotnet3.1/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/root/dotnet3.1/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/root/dotnet3.1/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/root/dotnet3.1/shared/Microsoft.NETCore.App]

Timmings:

4385.93
3045.00
3042.74
3069.86
3074.63

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.3.20216.6
 Commit:    9f62a32109

Runtime Environment:
 OS Name:     amzn
 OS Version:  2018.03
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /root/dotnet3/sdk/5.0.100-preview.3.20216.6/

Host (useful for support):
  Version: 5.0.0-preview.3.20214.6
  Commit:  b037784658

.NET SDKs installed:
  5.0.100-preview.3.20216.6 [/root/dotnet3/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.3.20215.14 [/root/dotnet3/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20214.6 [/root/dotnet3/shared/Microsoft.NETCore.App]

Timmings:

4059.56
2951.67
2906.33
2962.40
2993.35

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.6
 Commit:    0684df3a5b

Runtime Environment:
 OS Name:     amzn
 OS Version:  2018.03
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /root/dotnet7/sdk/5.0.100-preview.7.20366.6/

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  5.0.100-preview.7.20366.6 [/root/dotnet7/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [/root/dotnet7/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [/root/dotnet7/shared/Microsoft.NETCore.App]

Timings:

3463.12
2827.01
2796.74
2765.77
2749.04

**Comment by sebastienros** [comment]
Thanks. We already have a proxy scenario similar to what you did, but using different machine (3). And in our tests it's much faster with 5.0.

Before I try to run your app, or simulate the same payload on our benchmarks, it looks like the numbers are better in preview 3 and even better in preview 7. Why are you saying there is a regression? Do I read it wrong?

**Comment by Rodrigo-Andrade** [comment]
Its indeed a bit better than 3.1, but its far worse then preview3. I guess the regression here in from preview3 not 3.1. Still, its slower.

**Comment by NinoFloris** [comment]
@Rodrigo-Andrade I may also have trouble reading this but how is 

```
Timings:
4059.56
2951.67
2906.33
2962.40
2993.35
```
for preview 3 better than 

```
Timings:
3463.12
2827.01
2796.74
2765.77
2749.04
```
for preview 7?

**Comment by Rodrigo-Andrade** [comment]
Duh, i messed the order of things, retested and you are right, still seeing the increase in cpu on production tho 🤔. Back to investigating i guess, sorry for the lost time.

**Comment by sebastienros** [comment]
And more CPU usage on a benchmark is good sign. It means it spends less time waiting for io or a lock.

**Comment by Rodrigo-Andrade** [comment]
Not in production, throughput is the same with higher cpu (round robin load balancing).

**Comment by Rodrigo-Andrade** [comment]
@sebastienros just a followup, after analyzing my traces, my guess was that something was wrong at the socket scheduling, after reading https://github.com/dotnet/runtime/pull/34945 and https://github.com/dotnet/runtime/pull/37974, I configured my app with:
0 IOQueues
export DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS=1
export DOTNET_SYSTEM_NET_SOCKETS_THREAD_COUNT=4  (half the cores)
and cpu droped a lot with equal throughput:

![image](https://user-images.githubusercontent.com/1174384/88448847-390e5900-ce18-11ea-87f1-dba380297841.png)

So, the new settings for my workload had a massive performance penalty. Don't know why yet...

**Comment by davidfowl** [comment]
@Rodrigo-Andrade it might be worth collecting some counters to see if there any any significant differences (looking at some of the threadpool counters might help)

**Comment by Rodrigo-Andrade** [comment]
@davidfowl previous to the change, it was stable at about 8-10 threads, ill take a look at the current one.

**Comment by davidfowl** [comment]
Can you use dotnet counters to collect all of the counters?

**Comment by Rodrigo-Andrade** [comment]
@davidfowl 

Current:

[System.Runtime]
    % Time in GC since last GC (%)                                 0
    Allocation Rate (B / 1 sec)                           62,407,576
    CPU Usage (%)                                                 19
    Exception Count (Count / 1 sec)                                0
    GC Heap Size (MB)                                            398
    Gen 0 GC Count (Count / 1 sec)                                 0
    Gen 0 Size (B)                                               192
    Gen 1 GC Count (Count / 1 sec)                                 0
    Gen 1 Size (B)                                         9,066,896
    Gen 2 GC Count (Count / 1 sec)                                 0
    Gen 2 Size (B)                                        59,660,376
    IL Bytes Jitted (B)                                      711,046
    LOH Size (B)                                          19,079,592
    Monitor Lock Contention Count (Count / 1 sec)                 16
    Number of Active Timers                                      234
    Number of Assemblies Loaded                                   96
    Number of Methods Jitted                                   8,428
    POH (Pinned Object Heap) Size (B)                      9,439,104
    ThreadPool Completed Work Item Count (Count / 1 sec)       9,264
    ThreadPool Queue Length                                        0
    ThreadPool Thread Count                                       10
    Working Set (MB)                                             533

Default settings:

[System.Runtime]
    % Time in GC since last GC (%)                                 1
    Allocation Rate (B / 1 sec)                           70,278,144
    CPU Usage (%)                                                 32
    Exception Count (Count / 1 sec)                                0
    GC Heap Size (MB)                                             73
    Gen 0 GC Count (Count / 1 sec)                                 1
    Gen 0 Size (B)                                        13,685,440
    Gen 1 GC Count (Count / 1 sec)                                 1
    Gen 1 Size (B)                                         6,260,896
    Gen 2 GC Count (Count / 1 sec)                                 0
    Gen 2 Size (B)                                        56,477,728
    IL Bytes Jitted (B)                                      704,863
    LOH Size (B)                                          19,139,216
    Monitor Lock Contention Count (Count / 1 sec)                 31
    Number of Active Timers                                      340
    Number of Assemblies Loaded                                   96
    Number of Methods Jitted                                   8,366
    POH (Pinned Object Heap) Size (B)                      2,491,016
    ThreadPool Completed Work Item Count (Count / 1 sec)      26,841
    ThreadPool Queue Length                                        0
    ThreadPool Thread Count                                       10
    Working Set (MB)                                             504

**Comment by Rodrigo-Andrade** [comment]
In the default settings, the thread pool oscillates more (2-6). The new config it moves by 2 at most.

**Comment by davidfowl** [comment]
@Rodrigo-Andrade I'd like to compare without your settings (which basically avoid the thread pool) to see if anything stands out.

**Comment by Rodrigo-Andrade** [comment]
@davidfowl ? i just did, the second one is on the default settings

**Comment by davidfowl** [comment]
Default on preview3 and default on preview7?

**Comment by Rodrigo-Andrade** [comment]
those are all on preview7

**Comment by davidfowl** [comment]
I was asking for the difference in counters between the preview3 run and preview7 defaults.

**Comment by Rodrigo-Andrade** [comment]
Formatted for your delight:

|Preview  3| |
| :---        |          ---: |
|% Time in GC since last GC (%)                       |          0|
|Allocation Rate (B / 1 sec)                          | 54,207,360|
|CPU Usage (%)                                        |         25|
|Exception Count (Count / 1 sec)                      |          0|
|GC Heap Size (MB)                                    |         92|
|Gen 0 GC Count (Count / 1 sec)                       |          1|
|Gen 0 Size (B)                                       |        192|
|Gen 1 GC Count (Count / 1 sec)                       |          1|
|Gen 1 Size (B)                                       |  4,656,168|
|Gen 2 GC Count (Count / 1 sec)                       |          0|
|Gen 2 Size (B)                                       | 67,817,856|
|LOH Size (B)                                         | 20,011,432|
|Monitor Lock Contention Count (Count / 1 sec)        |          2|
|Number of Active Timers                              |        263|
|Number of Assemblies Loaded                          |         95|
|ThreadPool Completed Work Item Count (Count / 1 sec) |     15,228|
|ThreadPool Queue Length                              |          0|
|ThreadPool Thread Count                              |         10|
|Working Set (MB)                                     |        325|

|Preview  7| |
| :---        |          ---: |
|% Time in GC since last GC (%)                      |          1|
|Allocation Rate (B / 1 sec)                         | 70,278,144|
|CPU Usage (%)                                       |         32|
|Exception Count (Count / 1 sec)                     |          0|
|GC Heap Size (MB)                                   |         73|
|Gen 0 GC Count (Count / 1 sec)                      |          1|
|Gen 0 Size (B)                                      | 13,685,440|
|Gen 1 GC Count (Count / 1 sec)                      |          1|
|Gen 1 Size (B)                                      |  6,260,896|
|Gen 2 GC Count (Count / 1 sec)                      |          0|
|Gen 2 Size (B)                                      | 56,477,728|
|IL Bytes Jitted (B)                                 |    704,863|
|LOH Size (B)                                        | 19,139,216|
|Monitor Lock Contention Count (Count / 1 sec)       |         31|
|Number of Active Timers                             |        340|
|Number of Assemblies Loaded                         |         96|
|Number of Methods Jitted                            |      8,366|
|POH (Pinned Object Heap) Size (B)                   |  2,491,016|
|ThreadPool Completed Work Item Count (Count / 1 sec)|     26,841|
|ThreadPool Queue Length                             |          0|
|ThreadPool Thread Count                             |         10|
|Working Set (MB)                                    |        504|

**Comment by Rodrigo-Andrade** [comment]
@davidfowl
