### ISSUE TITLE
Nullable warnings in default identity's Register & Login razor pages

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#24201]
### Describe the bug

The default code for login & register pages generates a couple of nullable warnings (CS8625, CS8602, CS8618)

### To Reproduce

1. Create an ASP.NET Core 3.1 MVC project with identity.
1. Opt-in Nullable Reference Types feature. (`<Nullable>enable</Nullable>` in csproj)
1. Scaffold Register & Login page
1. See the warnings

What's the current correct fix on the developer's side? Is this issue planned to be fixed for 5.0?

**Comment by blowdart** [comment]
Again, linking to existing #22656

**Comment by Youssef1313** [comment]
@blowdart Any information on the correct action that I should take?
Is there a better solution than just suppressing the warnings?

**Comment by blowdart** [comment]
Suppress for now. No identity templates or scaffolding have any annotations right now.

**Comment by roji** [comment]
@Youssef1313 ideally the templates themselves would nullable-compatible, but we're not there yet.

**Comment by blowdart** [comment]
Closing in favor of aggregating issue, #25310
