### ISSUE TITLE
Should AntiForgery use ITlsTokenBindingFeature for DataProtection?

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2420]
_From @Tratcher on Monday, April 11, 2016 2:56:45 PM_

See https://github.com/aspnet/Security/issues/773
https://github.com/aspnet/Antiforgery/blob/0c81df859145801d2846ccbdc9af5830fa791f63/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgeryTokenSerializer.cs#L55

Only apply it if AntiforgeryOptions.RequreSsl is true.

_Copied from original issue: aspnet/Antiforgery#76_

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, June 14, 2017 2:58:39 PM_

@Tratcher @blowdart - I believe this still isn't doable in 2.0.0, is that correct?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, June 14, 2017 3:04:06 PM_

Correct, still backlogged.

**Comment by Eilon** [comment]
@blowdart - should we move this to 2.2.0?

**Comment by blowdart** [comment]
It's awaiting token binding, so I'd consider this blocked until token binding arrives. @Tratcher

**Comment by Eilon** [comment]
What's the latest on when we expect that to arrive?

**Comment by Tratcher** [comment]
We haven't started. 2.2 at the earliest.

**Comment by Eilon** [comment]
@Tratcher I'm OK with that. @blowdart ?

**Comment by blowdart** [comment]
Well it's blocked without it, so sure :)

**Comment by Eilon** [comment]
Moved to 2.2.0.

**Comment by mkArtakMSFT** [comment]
Moving out to 3.0 as there is no support for this yet.

**Comment by mkArtakMSFT** [comment]
@Tratcher, is this still blocked?

**Comment by pranavkm** [comment]
@Tratcher \ @blowdart do we expect the blocking issue to be resolved in 6.0? If not, I plan to close this issue. We can always revive this issue once we're unblocked.

**Comment by blowdart** [comment]
No. Token binding appears to have fallen by the wayside. So ... I'll close this.
