### ISSUE TITLE
Auto Generated JSInterop wrapper from TypeScript defnitions

### ISSUE THREAD

**Issue by plkumar** [dotnet/aspnetcore#24208]
Blazor is awesome, has a lot of potential, one area of improvement  (for C# developers) is enabling the to generate a quick C# JSInterop wrapper from TypeScript Defnition, this will help the C# Developer quickly leverage readily available JS Frameworks into Blazor apps.

### Describe the solution you'd like
JS Interop wrappers can be generated from TypeScript TypeDefinitions by using TypeScript language services or TypeScript AST

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
