### ISSUE TITLE
ControllerBase.ValidationProblemDetails(ValidationProblemDetails) does not populate properties like type, detail, etc.

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#24203]
Consider:

```csharp
public class FooValidationProblemDetails : ValidationProblemDetails
{
    public IEnumerable<string> Foo { get; set; }
}
```

```csharp
public class FooController : ControllerBase
{
    public IActionResult Foo()
    {
        return ValidationProblem(new FooValidationProblemDetails
        {
            Foo = new[] { "bar" },
        });
    }
}
```

Actual result:

```json
{
  "foo": [
    "bar"
  ],
  "type": null,
  "title": null,
  "status": 400,
  "detail": null,
  "instance": null
}
```

Expected result:

```json
{
  "foo": [
    "bar"
  ],
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "detail": null,
  "instance": null,
  "traceId": "|108bc361-489f83dfe37f0993."
}
```

What is the correct way to achieve the expected result?

**Comment by pranavkm** [comment]
That particular overload expects the caller to populate the details. Other overloads exist that will use the defaults: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.validationproblem?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_ControllerBase_ValidationProblem_System_String_System_String_System_Nullable_System_Int32__System_String_System_String_Microsoft_AspNetCore_Mvc_ModelBinding_ModelStateDictionary_

**Comment by IanKemp** [comment]
Then what would be the simplest way to add properties to a standard `ValidationProblemDetails` bad request response?

**Comment by pranavkm** [comment]
You could use the factory to produce the validation problem and add to the Extensions:

```C#
var problem = ProblemDetailsFactory.CreateValidationProblemDetails();
problem.Extensions["Foo"] = new { "bar" };
return ValidationProblem(problem);
```

**Comment by IanKemp** [comment]
Thanks @pranavkm , got something working that I'm mostly happy with:

```cs
public interface IValidationProblemDetails
{
    // nothing - marker interface
}
```

```cs
public class FooValidationProblemDetails : ValidationProblemDetails, IValidationProblemDetails
{
    public IEnumerable<string> Foo { get; set; }
}
```

```cs
public class FooController : ControllerBase
{
    public IActionResult Foo()
    {
        return ValidationProblem(new FooValidationProblemDetails
        {
            Foo = new[] { "bar" },
        });
    }

    // the magic!
    protected IActionResult ValidationProblem(IValidationProblemDetails additionalContext)
    {
        if (additionalContext == null)
            throw new ArgumentNullException(nameof(additionalContext));

        var validationProblemDetails = ProblemDetailsFactory.CreateValidationProblemDetails(HttpContext, ModelState);

        foreach (var publicProperty in additionalContext.GetType().GetTypeInfo().DeclaredProperties) // so we don't get the props defined on ValidationProblemDetails
        {
            validationProblemDetails.Extensions.Add(publicProperty.Name, publicProperty.GetValue(additionalContext));
        }

        return ValidationProblem(validationProblemDetails);
    }
}
```

Response:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "detail": null,
  "instance": null,
  "traceId": "|108bc361-489f83dfe37f0993.",
  "Foo": [
    "bar"
  ],
  "errors": {}
}
```

Deserialising the above response back to `FooValidationProblemDetails` also works perfectly!

My only remaining gripe is that `Foo` in the response is not automagically lowercased to `foo`, as is normal for model properties. Are the standard JSON output formatters not active at this stage of the pipeline? Do you have any suggestions to overcome this, besides applying explicit `JsonPropertyName` declarations?

**Comment by IanKemp** [comment]
No, this issue is not resolved. @pranavkm please can you respond to my above question?

**Comment by pranavkm** [comment]
> Are the standard JSON output formatters not active at this stage of the pipeline? Do you have any suggestions to overcome this, besides applying explicit JsonPropertyName declarations?

AFAIK, System.Text.Json does not change the casing for dictionary values. You could write a custom converter or use Newtonsoft.Json and configure it to apply the casing behavior to dictionary entries.

**Comment by IanKemp** [comment]
Oh right, I forgot that the extra properties are ultimately just entries in the Extensions dictionary. I think I can live with that little niggle.

Thank you for your assistance @pranavkm , we can consider this well and truly closed now. :)
