### ISSUE TITLE
Colors and "Squiggles" flash on and off when a project first loads in VS

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#24209]
### Describe the bug
When you first launch a project in VS colors and "error squiggles" flash in and out. eventually settling in a stable and correct possition.

### To Reproduce
1. install this copy of LSP client: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/262728?
1. Open a razor file.
1. It gets colorized.. then squiggles appear.. then colors disappear.. then a few seconds later the colors return.

### Further technical details
- Not available
- Not available
- VS 30322.33.master

**Comment by ryanbrandenburg** [comment]
I got a repro here and investigated further. This only happens for components defined within the project. My working theory is that the project.razor.json (which is now persistent across project loads) is loaded in a "good" state, then as the project searches for components and does compilation of local components it updates that understanding before the local components are done. Then eventually the local components finish loading and things get re-applied.

If the above is true we think that's likely to be "by design" for now, as we don't currently have a way of knowing when a project is "ready".

**Comment by ryanbrandenburg** [comment]
@dibarbet, am I correct in thinking we don't have a way from Roslyn to know when a project is "ready"? Is there was some Roslyn API we just didn't know about (or that was coming soon) it would be really useful to us.

**Comment by dibarbet** [comment]
@ryanbrandenburg this is the API we use to know if we've been told about all the projects - http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Workspace/VisualStudioWorkspaceStatusServiceFactory.cs,127 - it's a VS API so you should be able to use it.

Note that this can take quite a while and doesn't mean that some projects aren't loaded.  In local scenarios we still colorize and show diagnostics before this completes (even though they could change).

I'm not certain though what is happening if all colors are disappearing though.

**Comment by ryanbrandenburg** [comment]
@dibarbet thanks for pointing me to that API, it's exactly what we needed!

In most scenarios there will already be a complete project.razor.json file from the previous session to run things off of, so users shouldn't experience a delay in colors or diagnostics, even if it takes quite a while. In the case that we don't have a pre-existing project.razor.json to run off of we'll start serializing ASAP (this scenario shouldn't flash anyway, just progressively load more info).

The reason for colors showing and disappearing is mostly on our end: When things are first loaded there is probably already a project.razor.json (which drives most of our TagHelper behavior) from the previous session. As projects load and update they override that (probably complete) version with their incomplete knowledge. This is especially noticeable for components which were declared in this project as they need to be indexed and CodeGen'ed before they can be serialized.

Thanks for the clarification that this doesn't mean all projects have completed loading, but the additional delay seems sufficient to improve the experience so we'll go for it.
