### ISSUE TITLE
Consider changing Router lazy loading flow to be based on EventCallback<T>

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#24215]
This would be desirable because then developers can understand `OnNavigateAsync` as being equivalent to any other event handler, in that:

 * It causes the host page to re-render both synchronously and asynchronously
 * Any cancelled tasks will be discarded

If we don't do it, and keep it as `Func<NavigationContext, Task>`, then the host page won't re-render in response to navigation (only the `Router` and its descendants will). This is a bit of an obscure edge case, but would be surprising and would be hard to fix without a breaking change in the future.

Just for the sake of preserving where we got to, [here's a quick sketch of how EventCallback<T> could be used for this](https://gist.github.com/SteveSandersonMS/501e0609890b4b1205ec81f10a37ee27).

**Comment by SteveSandersonMS** [comment]
cc @captainsafia

**Comment by captainsafia** [comment]
> It causes the host page to re-render both synchronously and asynchronously

This is roughly related to the problem outlined in #24211 in that we will need to to ensure that when a re-render is invoked we don't actually render the route component until the `OnNavigateAsync` task has completed. Specifically for the `StateHasChanged` call that is invoked when the task is started in our event handling logic (less so for when `StateHasChanged` is called once the async event callback is completed).

**Comment by captainsafia** [comment]
I've gonna ahead and implemented this in the PR linked above.

Overall, the migration to an EventCallback has helped to greatly simplify the invocation loop for OnNavigateAsync. We're able to get rid of all of the conditional rendering logic.

However, there's some things to figure out around the handling for cancellations in the event callback.

Previously, we were able to detect when the user cancelled the OnNavigateAsync task without using the cancellation token and throw an error if that was the case.

With this new model, the cancellation is automatically swallowed by the event-handling logic in the component implementation so we're unable to handle this edge case (or notify the user).

We've had similar issues with regard to cancelled operations such as this one around how TimeoutExceptions that are suppressed (see https://github.com/dotnet/aspnetcore/issues/21384).
