### ISSUE TITLE
Blazor WebAssembly app with IndividualB2C auth unable to retrieve access token

### ISSUE THREAD

**Issue by pheuter** [dotnet/aspnetcore#24216]
# Problem

My standalone webassembly app is successfully able to initiate an AAD B2C sign in user flow, which returns back to the app with an id token and my user is authenticated, but I am unable to use the HttpClient to make calls to my API because the auth flow never sent back an access token, despite my confirming that the `scope` query parameter properly contained the API permission:

<img width="1098" alt="Screen Shot 2020-07-22 at 3 26 13 PM" src="https://user-images.githubusercontent.com/92698/88220946-b6c44000-cc31-11ea-85f2-14e09a45c811.png">

I believe it has something to do with MSAL.js passing along `id_token` instead of `token` for the **response_type** query parameter, but I have no idea why that happens or how I can control that. I have followed the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1#access-token-scopes) to setup an access token scope as you can see from the code I share below, but that doesn't seem to work. That is to say, it properly passes it along in the `scope`, but an access token is never generated:

```
Microsoft.AspNetCore.Components.WebAssembly.Authentication.AccessTokenNotAvailableException: 'https://mytenant.onmicrosoft.com/api/api.write'
```

# Configuration

**appsettings.json**

```json
{
  "AzureAdB2C": {
    "Authority": "https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/B2C_1_SignIn",
    "ClientId": "<MY_APP_CLIENT_ID>",
    "ValidateAuthority": false
  }
}
```

**Program.cs**

```csharp
private const string ApiScope = "https://mytenant.onmicrosoft.com/api/api.write";

builder.Services.AddHttpClient("ServerAPI",
        client => client.BaseAddress =
            new Uri(builder.Configuration.GetValue<string>("ApiBaseUrl")))
    .AddHttpMessageHandler(sp => sp.GetRequiredService<AuthorizationMessageHandler>()
        .ConfigureHandler(
            new[] { builder.Configuration.GetValue<string>("ApiBaseUrl") },
            new[] { ApiScope }));

builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAdB2C", options.ProviderOptions.Authentication);
    options.ProviderOptions.Cache.CacheLocation = "localStorage";
    options.ProviderOptions.DefaultAccessTokenScopes.Add(ApiScope);
});

builder.Services.AddOptions();
builder.Services.AddAuthorizationCore();
```

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.16
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.2.0" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="3.2.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.6" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.1" />
  </ItemGroup>

</Project>
```

**Comment by mkArtakMSFT** [comment]
@javiercn FYI, in case there is something urgent to be addressed here.

**Comment by pheuter** [comment]
@mkArtakMSFT This is currently breaking our app on production, is there a quick fix/workaround in the meantime?

**Comment by javiercn** [comment]
@pheuter You can replace the service implementation from [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts) with your own and either troubleshoot the issue that way or use your own implementation with a fix in case there is an issue.

**Comment by pheuter** [comment]
@javiercn I built aspnetcore source on the `release/3.1` branch and was not able to reproduce the issue locally. However, it occurred to me that, this time, I was testing it on Edge whereas before I was using Safari. Could it be that the issues described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas) are causing the Msal auth flow to fail on Safari? If so, is this something that will be fixed once WebAssembly.Msal switches over to Msal.js v2.0? Is there an ETA on that?

**Comment by RevFry** [comment]
I noticed the same issue. So I set the ResponseType to "id_token token" and now it fails on the call back and hangs at "Completing login..." I can see in the call back uri all the info it needs but for some reason it doesn't like parsing my access token?

I tried stepping through it once in the dubugger but the js being minified doesn't help make it readable.

**Comment by diogomota** [comment]
Seeing the same behaviour using Okta as IDP https://github.com/dotnet/aspnetcore/issues/25453 (apologies for the duplicate. Just saw this now !)

**Comment by captainsafia** [comment]
@pheuter We'll be shipping an upgrade to MSAL.js v2 in RC1. If you'd like to try it out early, you can grab a [daily build of the SDK](https://github.com/dotnet/installer#installers-and-binaries) and try the flow with the upgraded JS bits.

**Comment by mkArtakMSFT** [comment]
This should be fixed now, correct @javiercn ?

**Comment by javiercn** [comment]
@mkArtakMSFT I do not think this is an issue in the framework but an issue in the service configuration. The scopes are being requested correctly but the service is not granting them, so the configuration on AAD B2C needs to be updated to grant the scopes to that app.

**Comment by javiercn** [comment]
@pheuter I am going to close this issue because much has changed since the original report and is very likely any issue in this area has already been addressed. If that is not the case, please let us know.

Please note that currently the app needs to be registered as a SPA in AAD B2C and the flow we'll do is code+PKCE. We do not support implicit flows any longer.
