### ISSUE TITLE
Whats the resolution of 22052?

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#24218]
I have exactly the same issue with the latest VS 2019 preview like described in this issue:

https://github.com/dotnet/aspnetcore/issues/22052

@mkArtakMSFT The issue is marked as fixed. Whats the resolution?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TFTomSun.
Couldn't recall the details. Please file a new issue describing the problem you're facing and we will triage it with the team.
