### ISSUE TITLE
update IdentityServer in Microsoft.AspNetCore.ApiAuthorization.IdentityServer 

### ISSUE THREAD

**Issue by michaeldz** [dotnet/aspnetcore#24223]
Please update IdentityServer4.dll (and related libraries) till v4.x Currently it is v3.0.0
New library incompatible with 3.x. If I include new versions of the libraries in project I receive exception when run application on configuration phase.

**Comment by javiercn** [comment]
@michaeldz thanks for contacting us.

This is on our roadmap.

**Comment by javiercn** [comment]
This has been updated now to IdentityServer 4.0.4
