### ISSUE TITLE
Utilize SourceGenerators in Razor compilation

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24222]
We currently have a compilation server that is used to optimize our use of Roslyn for startup scenarios. Now that [SourceGenerators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) are a thing we can run all of our C# introspection logic inside of the Roslyn compiler and remove the need for our build compilation server entirely. This will also optimize our `dotnet build` path to resolve TagHelpers in a more first-class & performant way.

We've also had other bugs filed that would be resolved by this: https://github.com/dotnet/aspnetcore/issues/17742

**Comment by adrianwright109** [comment]
@NTaylorMullen @pranavkm is this issue a duplicate of #26902?

**Comment by pranavkm** [comment]
Good catch. 👍🏽
