### ISSUE TITLE
FromRoute / FromQuery binding failed

### ISSUE THREAD

**Issue by Goleven** [dotnet/aspnetcore#24234]
`

        [HttpDelete]
        [Route("{ids}")]
        public async Task<IActionResult> DeleteProjectMaterialAsync([FromRoute] string[] ids)
        {
            await _projectMaterialService.DeleteProjectMaterialAsync(ids);

            return Ok();
        }
`
first, can i use this way?

when i request the api with (http://localhost:8001/api/ProjectMaterial/1,2)

it looks like that

![image](https://user-images.githubusercontent.com/34236843/88275302-bdc18000-cd0f-11ea-9a8a-ad15e9fcb8ba.png)

the second question

`

    [HttpGet]
    [Route("List")]
    public async Task<IActionResult> GetUserList([FromQuery] UserFilterDto dto)
    {
        var result = await _userService.GetUserList(dto);
            
        return Ok(result);
    }

    public class UserFilterDto
    {
            public string Name {get; set;}
            
            public string SearchItem {get; set;}

            public IEnumerable<OrderRuleInfo> OrderRules { get; set; }
    }

    public class OrderRuleInfo
    {
        public string PropertyName { get; set; }

        [DefaultValue("desc")]
        public string SortType { get; set; }
    }
`

when i request by this way, It works

![image](https://user-images.githubusercontent.com/34236843/88276497-b7340800-cd11-11ea-91da-1088a7bd0d92.png)

but it's not work, like this,

![image](https://user-images.githubusercontent.com/34236843/88276841-4c370100-cd12-11ea-861f-5c789915c4ba.png)
![image](https://user-images.githubusercontent.com/34236843/88276853-52c57880-cd12-11ea-9e01-938c20e59566.png)

![image](https://user-images.githubusercontent.com/34236843/88276983-87393480-cd12-11ea-9456-38203d4acee9.png)

**Comment by pranavkm** [comment]
* The support formats for model binding arrays \ collections is described here: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#collections

* MVC does not support deserializing a JSON payload from query. You could consider reading the value as a string and manually deserializing it.

**Comment by Goleven** [comment]
> * The support formats for model binding arrays \ collections is described here: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1#collections
> 
> 
> 
> * MVC does not support deserializing a JSON payload from query. You could consider reading the value as a string and manually deserializing it.

thank you for the answer.
It will be support in the future ?

**Comment by pranavkm** [comment]
> It will be support in the future ?

We do not plans on supporting this in the future. You can send JSON over the body and MVC will deserialize it.
