### ISSUE TITLE
Conditional Blazor HTML / CSS etc...

### ISSUE THREAD

**Issue by vd3d** [dotnet/aspnetcore#24232]
Hi,

In C# we have conditional compilation, like:

#ifdef DEBUG
...
#endif

If will be useful to have the same for HTML/Blazor files. By example, with the same code base I wish to create
a desktop web site, and also a mobile version (or kind of Feature-Flag). It has to be at compile time to
minimize the file size (all about optimization)

### Describe the solution you'd like

add something like:

 @ifdef DEBUG
...
@endif

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You can use conditional pragmas within code blocks. Simply add `@{}` block wherever you want in the `.razor` file and add the pragmas there.
