### ISSUE TITLE
Backport Microsoft.AspNetCore.WebUtilities.QueryHelpers fix from master to next maintenance releases?

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#24239]
This file has a fix on master https://github.com/dotnet/aspnetcore/blob/master/src/Http/WebUtilities/src/QueryHelpers.cs#L134 that is not present in the currently released versions of ASP.NET Core e.g. https://github.com/dotnet/aspnetcore/blob/v3.1.6/src/Http/WebUtilities/src/QueryHelpers.cs

If this is something the team thinks would add value, I'd be happy to submit a PR to backport this fix (incl tests) in 3.1.next and 2.1.next, but not sure how that would work with respect to from where I should branch and to where the PR should be set to merge into.

**Comment by Pilchie** [comment]
In order to justify servicing, this needs to be a blocking issue without a decent workaround.  In this case, it seems like a workaround would be to copy those to your own project.

**Comment by IanKemp** [comment]
> In order to justify servicing, this needs to be a blocking issue without a decent workaround. In this case, it seems like a workaround would be to copy those to your own project.

Understood.
