### ISSUE TITLE
Always crash when typing Guid.NewGuid() in razor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24248]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1112789/always-crash-when-typing-guidnewguid-in-razor.html)._

---
Hi,
I'm developing an Blazor application. Visual studio always crash when I try to write below sentence inside a razor file:
>Guid divId = Guid.NewGuid();

---
#### Feedback Bot on 7/15/2020, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/15/2020, 03:13 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
The work here is to see if this is fixed by LSPification.

**Comment by NTaylorMullen** [comment]
Fixed by LSPification
