### ISSUE TITLE
2019 16.7 Preview 4: LSP Razor highlights HTML comments incorrectly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24249]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1112729/2019-167-preview-4-lsp-razor-highlights-html-comme.html)._

---
(This is a regression compared to the old non-LSP Razor service.)

The new Razor syntax highlighting won't color HTML comments in green. The two lines in the attached screenshot should be colored the same.

---
#### Feedback Bot on 7/14/2020, 11:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/15/2020, 02:47 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
This is most likely an issue in us not mapping VS classifications to the proper text mate type

**Comment by chucker** [comment]
Aforementioned screenshot, for the curious:

![Screen Shot 2020-07-14 at 20 35 02](https://user-images.githubusercontent.com/20194/88326362-41866700-cd26-11ea-82cf-4fe1e9c2222c.png)

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg should we track this as part of your HTML colorization parity work?

**Comment by ryanbrandenburg** [comment]
Yeah, this should be fixed by my semantic colorization in Razor HTML work.

**Comment by ryanbrandenburg** [comment]
With my new Razor HTML work:
![image](https://user-images.githubusercontent.com/14987221/95611394-a3e23000-0a16-11eb-983c-4304a8b1abb2.png)
