### ISSUE TITLE
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler throws exceptions with object types in description instead of actually useful values

### ISSUE THREAD

**Issue by js8080** [dotnet/aspnetcore#24256]
### Describe the bug
I have an ASP.NET Core Web API that is using JWT for authentication / authorization and when the JWT validation fails, I get a `Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException` exception like this:

> info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
>       Failed to validate the token.
> Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.Text.StringBuilder'.
> Exceptions caught:
>  'System.Text.StringBuilder'.
> token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.

and this:

> info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
>       Bearer was not authenticated. Failure message: IDX10503: Signature validation failed. Keys tried: 'System.Text.StringBuilder'.
>       Exceptions caught:
>        'System.Text.StringBuilder'.
>       token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.

Notice the _Keys tried_ and _Exceptions caught_ values are just `System.Text.StringBuilder`
That's not very helpful and I'm sure not intentional.

This is with Microsoft.AspNetCore.Authentication.JwtBearer 3.1.2

### To Reproduce

I enable the JWT authentication like this in my ConfigureServices method:

```C#
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options => { });  // options will be configured by JwtAuthenticationConfigurationOptions

services.AddAuthorization(options =>
{
            var defaultAuthorizationPolicyBuilder = new AuthorizationPolicyBuilder(JwtBearerDefaults.AuthenticationScheme);
            defaultAuthorizationPolicyBuilder = defaultAuthorizationPolicyBuilder.RequireAuthenticatedUser();
            options.DefaultPolicy = defaultAuthorizationPolicyBuilder.Build();
});
```
I then submit a web request to my API Controller method with an invalid key specified and I get these not so useful exceptions.

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.301
>  Commit:    7feb845744
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  20.04
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /usr/share/dotnet/sdk/3.1.301/
> 
> Host (useful for support):
>   Version: 3.1.5
>   Commit:  65cd789777
> 
> .NET Core SDKs installed:
>   3.1.301 [/usr/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS Code 1.47.2

**Comment by Tratcher** [comment]
Duplicate of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1471
