### ISSUE TITLE
Codespaces Hover Contains GUID

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24260]
### Describe the bug
Hover leads to:
![image](https://user-images.githubusercontent.com/14852843/88345701-61ecfc00-ccfb-11ea-8eb7-280c88dd74c1.png)

Expected:
![image](https://user-images.githubusercontent.com/14852843/88345734-7a5d1680-ccfb-11ea-980c-b68e4c027219.png)

### To Reproduce
1. Launch VS CodeSpaces
2. `dotnet new blazorserver`
3. `Pages/Counter.razor`
4. Hover over `@currentCount` on line 5. 

**This occurs spontaneously, usually at launch (and subsequently resolves itself).**

Issue reported by CTI so I don't have the logs, however both @ryanbrandenburg and I have seen this issue before.

### Pre-requisite checklist
- [x] Steps to reproduce the issue
- [ ] Visual Studio Activity Log attached.
- [ ] Razor Language Server client logs included.
- [ ] HTML Language Server client logs included

**Comment by NTaylorMullen** [comment]
No longer applicable.

**Comment by TanayParikh** [comment]
> No longer applicable.

I'm 70% sure I've seen this in GitHub Codespaces fairly recently. I'll update if I see it again to be sure.
