### ISSUE TITLE
VS Local & Codespaces Go To Def / FAR / Peek Def Not Functioning

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24261]
### Describe the bug
Razor Go To Def / FAR / Peek Def doesn't work in VS Local & Codespaces

### To Reproduce
1. Launch VS CodeSpaces
2. `dotnet new blazorserver`
3. `Pages/Counter.razor`
4. Go to definition / FAR / Peek Defn `currentCount` on line 14.

Actual Go To Def / FAR: Nothing Happens
Actual Peek Definition: **VS Crashes** ☠️ 

Issue reported by CTI so I don't have the logs, I've validated the issue with 16.7.0 Preview 5.0 Codespaces.

### Pre-requisite checklist
- [x] Steps to reproduce the issue
- [ ] Visual Studio Activity Log attached.
- [ ] Razor Language Server client logs included.
- [ ] HTML Language Server client logs included

**Comment by ajaybhargavb** [comment]
Fixed in https://github.com/dotnet/aspnetcore-tooling/pull/2267
