### ISSUE TITLE
Make it easier to use authentication and authorization in ASP.NET Core

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#24275]
A lot of effort is required to get started with setting up security for ASP.NET Core to use with standard OIDC servers. At present it is easy to setup as a standalone or securing using Azure AD, Azure B2C. 

It would help loads, if a template existed for ASP.NET Core API projects and ASP.NET Core UI projects which would use a separate default OIDC implemented server for authentication, authorization. 

For example, to secure an API protected using access tokens or reference tokens with introspection, only 3 parameters would be required to configure. Token management is solved, the Startup class code is added, and the parameters are read from the configuration. If you require extras like claims mapping, special validation, extra OIDC configurations, this could be then added. 

At present you need to start from scratch with an empty project.

The discussion for this started on twitter.

@DamianEdwards @davidfowl @blowdart 

Greetings Damien

**Comment by davidfowl** [comment]
@damienbod Can you make a proposal?

**Comment by mihaimyh** [comment]
Also interested in this.
