### ISSUE TITLE
Unable to build solution after cloning the repo

### ISSUE THREAD

**Issue by topagarwal** [dotnet/aspnetcore#24270]
I am using Windows 10 and have followed the instructions on this wiki. https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
 Did update VS using the install script, did restore and opened the MVC project using startVs script. The build failed, so used command line build.cmd to build the project.

I am getting this error:
<pre>
.\build.cmd "C:\AspNetCoreSrcCode\src\Mvc\Mvc.sln" /p:Configuration=Debug
WARNING: No default group of projects was specified, so building the managed and native projects and their dependencies. Run `build.cmd -help` for more details.
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.

  Determining projects to restore...
  Tool 'dotnet-serve' (version '1.7.125') was restored. Available commands: dotnet-serve

  Restore was successful.
  All projects are up-to-date for restore.
dotnet-install: .NET Core Runtime version 2.1.18 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-rc.1.20370.4 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-rc.1.20370.4 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: ASP.NET Core Runtime version 3.1.4 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Internal.AspNetCore.Analyzers -> C:\AspNetCoreSrcCode\artifacts\bin\Internal.AspNetCore.Analyzers\Release\netstandard1.3\Internal.AspNetCore.Analyzers.dll
  RepoTasks -> C:\AspNetCoreSrcCode\artifacts\bin\RepoTasks\Release\net5.0\RepoTasks.dll
  RepoTasks -> C:\AspNetCoreSrcCode\artifacts\bin\RepoTasks\Release\net472\RepoTasks.dll

MSBUILD : error MSB1008: Only one project can be specified.
Switch: C:\AspNetCoreSrcCode\src\Mvc\Mvc.sln

For switch syntax, type "MSBuild -help"
Build failed.
build.cmd completed
</pre>

Any help on how to build the projects will be great. I tried building RepoTask project and also commenting <pre><_RepoTaskAssemblyFolder Condition="'$(MSBuildRuntimeType)' != 'core'">net472</_RepoTaskAssemblyFolder> </pre> in RepoTasks.tasks but still getting same error. Please let me know if you need any additional info to help me here.
Thanks.

**Comment by javiercn** [comment]
@topagarwal thanks for contacting us.

I would suggest you try and build from the root with just build.cmd and then try to open the solution, or alternatively just call the build.cmd file available within src\Mvc (not sure if that's what you did)

**Comment by topagarwal** [comment]
Hi,
Initially i build from the root and gave path of MVC solution file. Aftr your sugeesting I tried running build.cmd from within MVC project on MVC.sln. In both the cases got same result.

<pre>
C:\AspNetCoreSrcCode\src\Mvc> .\build.cmd .\Mvc.sln

  Determining projects to restore...
  Tool 'dotnet-serve' (version '1.7.125') was restored. Available commands: dotnet-serve

  Restore was successful.
  All projects are up-to-date for restore.
dotnet-install: .NET Core Runtime version 2.1.18 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-rc.1.20370.4 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: .NET Core Runtime version 5.0.0-rc.1.20370.4 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\x86\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: ASP.NET Core Runtime version 3.1.4 is already installed.
dotnet-install: Adding to current process PATH: "C:\AspNetCoreSrcCode\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Internal.AspNetCore.Analyzers -> C:\AspNetCoreSrcCode\artifacts\bin\Internal.AspNetCore.Analyzers\Release\netstandard1.3\Internal.AspNetCore.Analyzers.dll
  RepoTasks -> C:\AspNetCoreSrcCode\artifacts\bin\RepoTasks\Release\net5.0\RepoTasks.dll
  RepoTasks -> C:\AspNetCoreSrcCode\artifacts\bin\RepoTasks\Release\net472\RepoTasks.dll

MSBUILD : error MSB1008: Only one project can be specified.
Switch: .\Mvc.sln

For switch syntax, type "MSBuild -help"
Build failed.
build.cmd completed
</pre>

**Comment by javiercn** [comment]
@topagarwal You don't have to pass the solution file to the build script.

@dotnet/aspnet-build can you help out here?

**Comment by topagarwal** [comment]
Ah..Thanks. I ran build.cmd inside MVC project and now I am able to move little further. However still build failed but now due to different error:
<pre>
Build FAILED.

C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(21,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(22,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(23,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(24,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(25,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components\Debug\net5.0\Microsoft.AspNetCore.Components.AssemblyInfo.cs(27,12): error CS0579: Duplicate 'System.Resources.NeutralResourcesLanguageAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Components\src\Microsoft.AspNetCore.Components.csproj]
    0 Warning(s)
    11 Error(s)

Time Elapsed 00:01:42.41
Build failed.
build.cmd completed
</pre>

I'm getting errors in Visual studio (v 16.6.2)  as well, so am trying to go build.cmd route.

**Comment by topagarwal** [comment]
Any suggestions?

**Comment by topagarwal** [comment]
I did git pull origin HEAD and rebuild the projects from command line form withing MVC project and now I am getting these errors:

C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(21,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(22,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(23,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(24,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(25,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Forms\Debug\net5.0\Microsoft.AspNetCore.Components.Forms.AssemblyInfo.cs(27,12): error CS0579: Duplicate 'System.Resources.NeutralResourcesLanguageAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Forms\src\Microsoft.AspNetCore.Components.Forms.csproj]
C:\AspNetCoreSrcCode\src\Razor\Microsoft.NET.Sdk.Razor\src\Microsoft.NET.Sdk.Razor.csproj(101,5): error MSB3026: Could not copy "C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\net46\Microsoft.NET.Sdk.Razor.Tasks.dll" to "C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\sdk-output\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\sdk-output\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll' because it is being used by another process.
C:\AspNetCoreSrcCode\src\Razor\Microsoft.NET.Sdk.Razor\src\Microsoft.NET.Sdk.Razor.csproj(101,5): error MSB3027: Could not copy "C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\net46\Microsoft.NET.Sdk.Razor.Tasks.dll" to "C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\sdk-output\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll". Exceeded retry count of 1. Failed.
C:\AspNetCoreSrcCode\src\Razor\Microsoft.NET.Sdk.Razor\src\Microsoft.NET.Sdk.Razor.csproj(101,5): error MSB3021: Unable to copy file "C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\net46\Microsoft.NET.Sdk.Razor.Tasks.dll" to "C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\sdk-output\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll". The process cannot access the file 'C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\sdk-output\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll' because it is being used by another process.
C:\AspNetCoreSrcCode\src\Razor\Microsoft.NET.Sdk.Razor\src\Microsoft.NET.Sdk.Razor.csproj(101,5): error MSB4181: The "Copy" task returned false but did not log an error.
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(20,12): error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(21,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(22,12): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(23,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(24,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(25,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\Microsoft.AspNetCore.Components.Authorization.AssemblyInfo.cs(27,12): error CS0579: Duplicate 'System.Resources.NeutralResourcesLanguageAttribute' attribute [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
C:\AspNetCoreSrcCode\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net5.0\RazorDeclaration\CascadingAuthenticationState.razor.g.cs(16,26): error CS8646: 'IDisposable.Dispose()' is explicitly implemented more than once. [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
obj\Debug\net5.0\RazorDeclaration\CascadingAuthenticationState.razor.g.cs(19,33): error CS0111: Type 'CascadingAuthenticationState' already defines a member called 'BuildRenderTree' with the same parameter types [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
CascadingAuthenticationState.razor(7,39): error CS0102: The type 'CascadingAuthenticationState' already contains a definition for '_currentAuthenticationStateTask' [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
CascadingAuthenticationState.razor(13,27): error CS0102: The type 'CascadingAuthenticationState' already contains a definition for 'ChildContent' [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
CascadingAuthenticationState.razor(15,29): error CS0111: Type 'CascadingAuthenticationState' already defines a member called 'OnInitialized' with the same parameter types [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
CascadingAuthenticationState.razor(23,18): error CS0111: Type 'CascadingAuthenticationState' already defines a member called 'OnAuthenticationStateChanged' with the same parameter types [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
CascadingAuthenticationState.razor(32,22): error CS0111: Type 'CascadingAuthenticationState' already defines a member called 'System.IDisposable.Dispose' with the same parameter types [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
obj\Debug\net5.0\RazorDeclaration\CascadingAuthenticationState.razor.g.cs(59,103): error CS0102: The type 'CascadingAuthenticationState' already contains a definition for 'AuthenticationStateProvider' [C:\AspNetCoreSrcCode\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
    0 Warning(s)
    34 Error(s)

Time Elapsed 00:00:41.14
Build failed.
build.cmd completed

**Comment by dougbu** [comment]
1. It's not clear you're using the current HEAD from this repo. @Pilchie deleted the src/Mvc/Mvc.sln file back on the 8th and there's a Mvc.slnf file in that directory now.
2. Duplicate attributes sometimes show up after a previous build aborted. Recommend cleaning the repo e.g. `git clean -dfx -e .dotnet/ -e .tools/`. Add `-e .vs/ -e .vscode/` if you're confident the VS settings aren't messed up.
3. As @javiercn said, do not pass a `*.slnf` file (or a `*.sln` file in our old world) into `build.cmd`. If you want to build a subset of the repo using `build.cmd`, use the files in the lower-level directories e.g. src/Mvc/build.cmd and &hellip;/build.sh.

**Comment by topagarwal** [comment]
Thanks, doing git clean helped. I guess I once build without taking the latest and it was causing the issue.
Now the build from cmd line is fine. However I am still unable to run MVC sandbox project.
<pre>
C:\AspNetCoreSrcCode\src\Razor\Microsoft.NET.Sdk.Razor\src\build\netstandard2.0\Microsoft.NET.Sdk.Razor.ScopedCss.targets(71,3): error MSB4062: The "Microsoft.AspNetCore.Razor.Tasks.DiscoverDefaultScopedCssItems" task could not be loaded from the assembly C:\AspNetCoreSrcCode\artifacts\bin\Microsoft.NET.Sdk.Razor\Debug\sdk-output\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
18>Done building project "MvcSandbox.csproj" -- FAILED.
</pre>

**Comment by dougbu** [comment]
@topagarwal if the original issue is resolved, please close it and file a new one about the MVC sandbox project. We'd like to route that new issue correctly.

**Comment by topagarwal** [comment]
ok.  I have created a discussion https://github.com/dotnet/aspnetcore/discussions/24353.
https://github.com/dotnet/aspnetcore/discussions/24353 Please let me know if it should be moved to issues.

Thanks for the help.
