### ISSUE TITLE
Visual Studio 16.7.0 Preview 4 - building large Blazor/Razor project is extremely slow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24290]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1114118/visual-studio-1670-preview-4-building-large-blazor.html)._

---
We have a pretty large Blazor project. It takes roughly 4 minutes for each build. I have attached a build log.

---
#### Roi Chen [MSFT] on 7/15/2020, 09:27 PM: 

<p>Thank you for taking the time to log this issue!<br>
In order for us to investigate further, please provide more information by recording your repro steps via the Visual Studio Feedback Tool (Help -&gt; Send Feedback -&gt; Report A Problem). The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace). Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool – <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">full instructions</a><br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.<br>
We look forward to hearing from you!</p>

#### cristian.recoseanu on 7/21/2020, 08:18 AM: 

Here is the summary:<br>Target Performance Summary:<br>        * ms  AssignTargetPaths                          3 calls<br>        * ms  CopyAdditionalFiles                       10 calls<br>        * ms  GetCopyToOutputDirectoryItems              1 calls<br>        * ms  GetNativeManifest                          5 calls<br>        * ms  GetTargetFrameworks                        6 calls<br>        * ms  GetTargetPath                              9 calls<br>        * ms  GetTargetPathWithTargetPlatformMoniker     8 calls<br>        * ms  ResolveCurrentProjectStaticWebAssetsInputs   2 calls<br>        * ms  _GetCopyToOutputDirectoryItemsFromThisProject   3 calls<br>        * ms  _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences   1 calls<br>        * ms  _GetProjectReferenceTargetFrameworkProperties   3 calls<br>        * ms  _PopulateCommonStateForGetCopyToOutputDirectoryItems   3 calls<br>        * ms  _SplitProjectReferencesByFileExistence     3 calls<br>        0 ms  RazorGenerateComponentDefinition           1 calls<br>        0 ms  RazorComponentGenerate                     1 calls<br>        0 ms  DesignTimeXamlMarkupCompilation            1 calls<br>        0 ms  ResolveCodeAnalysisRuleSet                 1 calls<br>        0 ms  _GenerateRazorAssemblyInfo                 1 calls<br>        0 ms  RazorComponentGenerateCore                 1 calls<br>        0 ms  RazorGenerate                              1 calls<br>        0 ms  _HashRazorComponentInputs                  1 calls<br>        0 ms  _RemoveRazorDeclartionsFromCompile         1 calls<br>        0 ms  PrepareForRazorComponentGenerate           1 calls<br>        0 ms  ResolveRazorComponentInputs                1 calls<br>        0 ms  ResolveRazorConfiguration                  1 calls<br>        0 ms  BeforeCompile                              1 calls<br>        0 ms  AfterBuild                                 1 calls<br>        0 ms  InitializeSourceControlInformation         1 calls<br>        0 ms  GenerateTargetFrameworkMonikerAttribute    1 calls<br>        0 ms  _SetTargetFrameworkMonikerAttribute        1 calls<br>        0 ms  GenerateMSBuildEditorConfigFile            1 calls<br>        0 ms  GenerateMSBuildEditorConfigFileShouldRun   1 calls<br>        0 ms  PrepareForRazorGenerate                    1 calls<br>        0 ms  _CollectTargetFrameworkForTelemetry        1 calls<br>        0 ms  ComputeRunAnalyzers                        1 calls<br>        0 ms  _GenerateCompileInputs                     1 calls<br>        0 ms  CoreBuild                                  1 calls<br>        0 ms  PrepareForRun                              1 calls<br>        0 ms  _ResolveRazorTargetPath                    1 calls<br>        0 ms  CopyFilesToOutputDirectory                 1 calls<br>        0 ms  ComputeDependencyFileCompilerOptions       1 calls<br>        0 ms  _CopySourceItemsToOutputDirectory          1 calls<br>        0 ms  _CopyOutOfDateSourceItemsToOutputDirectory   1 calls<br>        0 ms  GetTypeScriptCopyToOutputDirectoryItems    1 calls<br>        0 ms  _RemoveComponentAnalyzer                   1 calls<br>        0 ms  GetCopyToOutputDirectoryXamlAppDefs        4 calls<br>        0 ms  _PrepareForStaticWebAssets                 3 calls<br>        0 ms  ResolveStaticWebAssetsInputs               3 calls<br>        0 ms  GetCurrentProjectStaticWebAssets           2 calls<br>        0 ms  _RazorGetCopyToOutputDirectoryItems        3 calls<br>        0 ms  _RazorPrepareForRun                        1 calls<br>        0 ms  RazorCompile                               1 calls<br>        0 ms  PrepareForRazorCompile                     1 calls<br>        0 ms  GenerateRazorTargetAssemblyInfo            1 calls<br>        0 ms  ResolveRazorCompileInputs                  1 calls<br>        0 ms  _ResolveGeneratedRazorCompileInputs        1 calls<br>        0 ms  CreateSatelliteAssemblies                  1 calls<br>        0 ms  _GenerateSatelliteAssemblyInputs           1 calls<br>        0 ms  Compile                                    1 calls<br>        0 ms  AfterCompile                               1 calls<br>        0 ms  CleanXsdCodeGen                            1 calls<br>        0 ms  _BeforeVBCSCoreCompile                     1 calls<br>        0 ms  SetWin32ManifestProperties                 1 calls<br>        0 ms  GenerateAssemblyInfo                       1 calls<br>        0 ms  PrepareResources                           1 calls<br>        0 ms  ExpandSDKReferences                        1 calls<br>        0 ms  ResolveSDKReferences                       1 calls<br>        0 ms  PrepareProjectReferences                   3 calls<br>        0 ms  ResolvePackageDependenciesForBuild         3 calls<br>        0 ms  AddTransitiveFrameworkReferences           1 calls<br>        0 ms  ResolveRazorGenerateInputs                 3 calls<br>        0 ms  GetReferenceAssemblyPaths                  1 calls<br>        0 ms  GetFrameworkPaths                          1 calls<br>        0 ms  BuildOnlySettings                          1 calls<br>        0 ms  BeforeBuild                                1 calls<br>        0 ms  EnableIntermediateOutputPathMismatchWarning   1 calls<br>        0 ms  CollectPackageReferences                   1 calls<br>        0 ms  _CheckForObsoleteDotNetCliToolReferences   1 calls<br>        0 ms  _GetProjectJsonPath                        1 calls<br>        0 ms  _CheckForNETCoreSdkIsPreview               1 calls<br>        0 ms  _CheckForUnsupportedCppNETCoreVersion      1 calls<br>        0 ms  _CheckForUnsupportedNETCoreVersion         1 calls<br>        0 ms  ResolveFrameworkReferences                 1 calls<br>        0 ms  AfterResolveReferences                     1 calls<br>        0 ms  Build                                      1 calls<br>        0 ms  ResolveReferences                          1 calls<br>        0 ms  ResGen                                     1 calls<br>        0 ms  CreateCustomManifestResourceNames          1 calls<br>        0 ms  AfterResGen                                1 calls<br>        0 ms  PrepareResourceNames                       1 calls<br>        0 ms  _ComputeNETCoreBuildOutputFiles            3 calls<br>        0 ms  BeforeResGen                               1 calls<br>        0 ms  SplitResourcesByCulture                    1 calls<br>        0 ms  ExpressionBuildExtension                   1 calls<br>        1 ms  _ComputeUserRuntimeAssemblies              1 calls<br>        1 ms  GetAssemblyVersion                         1 calls<br>        1 ms  _RazorCopyFilesToOutputDirectory           1 calls<br>        1 ms  GetRazorTargetAssemblyAttributes           1 calls<br>        1 ms  CoreGenerateAssemblyInfo                   1 calls<br>        1 ms  _HashRazorGenerateInputs                   1 calls<br>        1 ms  _SetEmbeddedWin32ManifestProperties        1 calls<br>        1 ms  CoreResGen                                 1 calls<br>        1 ms  _ComputePackageReferencePublish            3 calls<br>        1 ms  _FixupRazorReferencePathForRazorCompile    1 calls<br>        1 ms  _DefaultMicrosoftNETPlatformLibrary        3 calls<br>        1 ms  GenerateCompiledExpressionsTempFile        1 calls<br>        1 ms  IncludeTransitiveProjectReferences         3 calls<br>        1 ms  ValidationExtension                        1 calls<br>        1 ms  AddSourceRevisionToInformationalVersion    1 calls<br>        1 ms  PreXsdCodeGen                              1 calls<br>        1 ms  AssignRazorComponentTargetPaths            1 calls<br>        1 ms  BeforeResolveReferences                    1 calls<br>        1 ms  _CheckForCompileOutputs                    1 calls<br>        2 ms  CreateGeneratedAssemblyInfoInputsCacheFile   1 calls<br>        2 ms  IncrementalClean                           1 calls<br>        2 ms  ResolveLockFileAnalyzers                   3 calls<br>        2 ms  _CheckForLanguageAndFeatureCombinationSupport   3 calls<br>        2 ms  _GetRestoreProjectStyle                    1 calls<br>        2 ms  _CreateRazorTargetAssemblyInfoInputsCacheFile   1 calls<br>        2 ms  GetAssemblyAttributes                      1 calls<br>        3 ms  UpdateAspNetToFrameworkReference           2 calls<br>        3 ms  _CheckForInvalidConfigurationAndPlatform   1 calls<br>        4 ms  ResolveTargetingPackAssets                 1 calls<br>        4 ms  _ResolveComponentRazorGenerateInputs       1 calls<br>        4 ms  CheckForDuplicateItems                     1 calls<br>        5 ms  AssignProjectConfiguration                 3 calls<br>        6 ms  ResolveLockFileCopyLocalFiles              3 calls<br>        6 ms  ApplyImplicitVersions                      3 calls<br>        6 ms  _CopyFilesMarkedCopyLocal                  1 calls<br>        7 ms  _CreateStaticWebAssetsInputsCacheFile      3 calls<br>        9 ms  RazorGenerateComponentDeclaration          1 calls<br>       11 ms  ResolveAssemblyReferenceRazorGenerateInputs   1 calls<br>       12 ms  CheckForImplicitPackageReferenceOverrides   3 calls<br>       12 ms  GenerateStaticWebAssetsManifest            3 calls<br>       12 ms  _CleanGetCurrentAndPriorFileWrites         1 calls<br>       12 ms  ProcessFrameworkReferences                 3 calls<br>       13 ms  _ResolveRazorGenerateOutputs               1 calls<br>       14 ms  _GenerateCompileDependencyCache            1 calls<br>       17 ms  GenerateBuildDependencyFile                1 calls<br>       23 ms  _ResolveRazorComponentOutputs              1 calls<br>       32 ms  ResolvePackageAssets                       3 calls<br>       32 ms  PrepareForBuild                            1 calls<br>       33 ms  ResolveLockFileReferences                  3 calls<br>       35 ms  _HandlePackageFileConflicts                1 calls<br>       50 ms  FindReferenceAssembliesForReferences       1 calls<br>      120 ms  ResolveReferencedProjectsStaticWebAssets   3 calls<br>      186 ms  ResolveAssemblyReferences                  1 calls<br>      330 ms  ResolveProjectReferences                   1 calls<br>      373 ms  _ComputeReferenceAssemblies                1 calls<br>      572 ms  RazorCompileComponentDeclaration           1 calls<br>     1602 ms  ResolveTagHelperRazorGenerateInputs        1 calls<br>     3097 ms  RazorCoreGenerate                          1 calls<br>    242346 ms  CoreCompile                                1 calls<br>        (* = timing was not recorded because of reentrancy)<br><br>Task Performance Summary:<br>        * ms  AssignTargetPath                          14 calls<br>        * ms  CallTarget                                 2 calls<br>        * ms  MSBuild                                    5 calls<br>        0 ms  Telemetry                                  1 calls<br>        0 ms  ReadLinesFromFile                          1 calls<br>        0 ms  Delete                                     2 calls<br>        0 ms  ResolveCodeAnalysisRuleSet                 1 calls<br>        0 ms  GetAssemblyVersion                         1 calls<br>        0 ms  AssignCulture                              1 calls<br>        0 ms  ResolveFrameworkReferences                 1 calls<br>        0 ms  GetPackageDirectory                        6 calls<br>        0 ms  RemoveDuplicates                           2 calls<br>        0 ms  ShowPreviewMessage                         1 calls<br>        1 ms  ApplyImplicitVersions                      3 calls<br>        1 ms  GetFrameworkPath                           1 calls<br>        1 ms  Message                                    4 calls<br>        1 ms  Hash                                       8 calls<br>        1 ms  FindUnderPath                              5 calls<br>        1 ms  MakeDir                                    4 calls<br>        1 ms  CheckForDuplicateFrameworkReferences       3 calls<br>        2 ms  GetRestoreProjectStyleTask                 1 calls<br>        2 ms  Touch                                      2 calls<br>        3 ms  CheckIfPackageReferenceShouldBeFrameworkReference   4 calls<br>        3 ms  ResolveAppHosts                            3 calls<br>        3 ms  CheckForDuplicateItems                     3 calls<br>        3 ms  WriteLinesToFile                           8 calls<br>        4 ms  Copy                                       3 calls<br>        4 ms  ResolveTargetingPackAssets                 1 calls<br>        5 ms  ProcessFrameworkReferences                 3 calls<br>        5 ms  AssignProjectConfiguration                 3 calls<br>        5 ms  ConvertToAbsolutePath                      1 calls<br>        7 ms  JoinItems                                  3 calls<br>       11 ms  GenerateDepsFile                           1 calls<br>       11 ms  CheckForImplicitPackageReferenceOverrides   3 calls<br>       11 ms  GetReferenceNearestTargetFrameworkTask     1 calls<br>       12 ms  RemoveDir                                  1 calls<br>       17 ms  ResolveNonMSBuildProjectOutput             1 calls<br>       22 ms  ResolvePackageFileConflicts                1 calls<br>       31 ms  ResolvePackageAssets                       3 calls<br>       32 ms  FindAppConfigFile                          1 calls<br>      186 ms  ResolveAssemblyReference                   1 calls<br>     1596 ms  RazorTagHelper                             1 calls<br>     3082 ms  RazorGenerate                              1 calls<br>    242910 ms  Csc                                        2 calls<br>        (* = timing was not recorded because of reentrancy)<br><br>Build succeeded.<br>    0 Warning(s)<br>    0 Error(s)
#### cristian.recoseanu on 7/21/2020, 08:18 AM: 

Here is the summary:<br>Target Performance Summary:<br>        * ms  AssignTargetPaths                          3 calls<br>        * ms  CopyAdditionalFiles                       10 calls<br>        * ms  GetCopyToOutputDirectoryItems              1 calls<br>        * ms  GetNativeManifest                          5 calls<br>        * ms  GetTargetFrameworks                        6 calls<br>        * ms  GetTargetPath                              9 calls<br>        * ms  GetTargetPathWithTargetPlatformMoniker     8 calls<br>        * ms  ResolveCurrentProjectStaticWebAssetsInputs   2 calls<br>        * ms  _GetCopyToOutputDirectoryItemsFromThisProject   3 calls<br>        * ms  _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences   1 calls<br>        * ms  _GetProjectReferenceTargetFrameworkProperties   3 calls<br>        * ms  _PopulateCommonStateForGetCopyToOutputDirectoryItems   3 calls<br>        * ms  _SplitProjectReferencesByFileExistence     3 calls<br>        0 ms  RazorGenerateComponentDefinition           1 calls<br>        0 ms  RazorComponentGenerate                     1 calls<br>        0 ms  DesignTimeXamlMarkupCompilation            1 calls<br>        0 ms  ResolveCodeAnalysisRuleSet                 1 calls<br>        0 ms  _GenerateRazorAssemblyInfo                 1 calls<br>        0 ms  RazorComponentGenerateCore                 1 calls<br>        0 ms  RazorGenerate                              1 calls<br>        0 ms  _HashRazorComponentInputs                  1 calls<br>        0 ms  _RemoveRazorDeclartionsFromCompile         1 calls<br>        0 ms  PrepareForRazorComponentGenerate           1 calls<br>        0 ms  ResolveRazorComponentInputs                1 calls<br>        0 ms  ResolveRazorConfiguration                  1 calls<br>        0 ms  BeforeCompile                              1 calls<br>        0 ms  AfterBuild                                 1 calls<br>        0 ms  InitializeSourceControlInformation         1 calls<br>        0 ms  GenerateTargetFrameworkMonikerAttribute    1 calls<br>        0 ms  _SetTargetFrameworkMonikerAttribute        1 calls<br>        0 ms  GenerateMSBuildEditorConfigFile            1 calls<br>        0 ms  GenerateMSBuildEditorConfigFileShouldRun   1 calls<br>        0 ms  PrepareForRazorGenerate                    1 calls<br>        0 ms  _CollectTargetFrameworkForTelemetry        1 calls<br>        0 ms  ComputeRunAnalyzers                        1 calls<br>        0 ms  _GenerateCompileInputs                     1 calls<br>        0 ms  CoreBuild                                  1 calls<br>        0 ms  PrepareForRun                              1 calls<br>        0 ms  _ResolveRazorTargetPath                    1 calls<br>        0 ms  CopyFilesToOutputDirectory                 1 calls<br>        0 ms  ComputeDependencyFileCompilerOptions       1 calls<br>        0 ms  _CopySourceItemsToOutputDirectory          1 calls<br>        0 ms  _CopyOutOfDateSourceItemsToOutputDirectory   1 calls<br>        0 ms  GetTypeScriptCopyToOutputDirectoryItems    1 calls<br>        0 ms  _RemoveComponentAnalyzer                   1 calls<br>        0 ms  GetCopyToOutputDirectoryXamlAppDefs        4 calls<br>        0 ms  _PrepareForStaticWebAssets                 3 calls<br>        0 ms  ResolveStaticWebAssetsInputs               3 calls<br>        0 ms  GetCurrentProjectStaticWebAssets           2 calls<br>        0 ms  _RazorGetCopyToOutputDirectoryItems        3 calls<br>        0 ms  _RazorPrepareForRun                        1 calls<br>        0 ms  RazorCompile                               1 calls<br>        0 ms  PrepareForRazorCompile                     1 calls<br>        0 ms  GenerateRazorTargetAssemblyInfo            1 calls<br>        0 ms  ResolveRazorCompileInputs                  1 calls<br>        0 ms  _ResolveGeneratedRazorCompileInputs        1 calls<br>        0 ms  CreateSatelliteAssemblies                  1 calls<br>        0 ms  _GenerateSatelliteAssemblyInputs           1 calls<br>        0 ms  Compile                                    1 calls<br>        0 ms  AfterCompile                               1 calls<br>        0 ms  CleanXsdCodeGen                            1 calls<br>        0 ms  _BeforeVBCSCoreCompile                     1 calls<br>        0 ms  SetWin32ManifestProperties                 1 calls<br>        0 ms  GenerateAssemblyInfo                       1 calls<br>        0 ms  PrepareResources                           1 calls<br>        0 ms  ExpandSDKReferences                        1 calls<br>        0 ms  ResolveSDKReferences                       1 calls<br>        0 ms  PrepareProjectReferences                   3 calls<br>        0 ms  ResolvePackageDependenciesForBuild         3 calls<br>        0 ms  AddTransitiveFrameworkReferences           1 calls<br>        0 ms  ResolveRazorGenerateInputs                 3 calls<br>        0 ms  GetReferenceAssemblyPaths                  1 calls<br>        0 ms  GetFrameworkPaths                          1 calls<br>        0 ms  BuildOnlySettings                          1 calls<br>        0 ms  BeforeBuild                                1 calls<br>        0 ms  EnableIntermediateOutputPathMismatchWarning   1 calls<br>        0 ms  CollectPackageReferences                   1 calls<br>        0 ms  _CheckForObsoleteDotNetCliToolReferences   1 calls<br>        0 ms  _GetProjectJsonPath                        1 calls<br>        0 ms  _CheckForNETCoreSdkIsPreview               1 calls<br>        0 ms  _CheckForUnsupportedCppNETCoreVersion      1 calls<br>        0 ms  _CheckForUnsupportedNETCoreVersion         1 calls<br>        0 ms  ResolveFrameworkReferences                 1 calls<br>        0 ms  AfterResolveReferences                     1 calls<br>        0 ms  Build                                      1 calls<br>        0 ms  ResolveReferences                          1 calls<br>        0 ms  ResGen                                     1 calls<br>        0 ms  CreateCustomManifestResourceNames          1 calls<br>        0 ms  AfterResGen                                1 calls<br>        0 ms  PrepareResourceNames                       1 calls<br>        0 ms  _ComputeNETCoreBuildOutputFiles            3 calls<br>        0 ms  BeforeResGen                               1 calls<br>        0 ms  SplitResourcesByCulture                    1 calls<br>        0 ms  ExpressionBuildExtension                   1 calls<br>        1 ms  _ComputeUserRuntimeAssemblies              1 calls<br>        1 ms  GetAssemblyVersion                         1 calls<br>        1 ms  _RazorCopyFilesToOutputDirectory           1 calls<br>        1 ms  GetRazorTargetAssemblyAttributes           1 calls<br>        1 ms  CoreGenerateAssemblyInfo                   1 calls<br>        1 ms  _HashRazorGenerateInputs                   1 calls<br>        1 ms  _SetEmbeddedWin32ManifestProperties        1 calls<br>        1 ms  CoreResGen                                 1 calls<br>        1 ms  _ComputePackageReferencePublish            3 calls<br>        1 ms  _FixupRazorReferencePathForRazorCompile    1 calls<br>        1 ms  _DefaultMicrosoftNETPlatformLibrary        3 calls<br>        1 ms  GenerateCompiledExpressionsTempFile        1 calls<br>        1 ms  IncludeTransitiveProjectReferences         3 calls<br>        1 ms  ValidationExtension                        1 calls<br>        1 ms  AddSourceRevisionToInformationalVersion    1 calls<br>        1 ms  PreXsdCodeGen                              1 calls<br>        1 ms  AssignRazorComponentTargetPaths            1 calls<br>        1 ms  BeforeResolveReferences                    1 calls<br>        1 ms  _CheckForCompileOutputs                    1 calls<br>        2 ms  CreateGeneratedAssemblyInfoInputsCacheFile   1 calls<br>        2 ms  IncrementalClean                           1 calls<br>        2 ms  ResolveLockFileAnalyzers                   3 calls<br>        2 ms  _CheckForLanguageAndFeatureCombinationSupport   3 calls<br>        2 ms  _GetRestoreProjectStyle                    1 calls<br>        2 ms  _CreateRazorTargetAssemblyInfoInputsCacheFile   1 calls<br>        2 ms  GetAssemblyAttributes                      1 calls<br>        3 ms  UpdateAspNetToFrameworkReference           2 calls<br>        3 ms  _CheckForInvalidConfigurationAndPlatform   1 calls<br>        4 ms  ResolveTargetingPackAssets                 1 calls<br>        4 ms  _ResolveComponentRazorGenerateInputs       1 calls<br>        4 ms  CheckForDuplicateItems                     1 calls<br>        5 ms  AssignProjectConfiguration                 3 calls<br>        6 ms  ResolveLockFileCopyLocalFiles              3 calls<br>        6 ms  ApplyImplicitVersions                      3 calls<br>        6 ms  _CopyFilesMarkedCopyLocal                  1 calls<br>        7 ms  _CreateStaticWebAssetsInputsCacheFile      3 calls<br>        9 ms  RazorGenerateComponentDeclaration          1 calls<br>       11 ms  ResolveAssemblyReferenceRazorGenerateInputs   1 calls<br>       12 ms  CheckForImplicitPackageReferenceOverrides   3 calls<br>       12 ms  GenerateStaticWebAssetsManifest            3 calls<br>       12 ms  _CleanGetCurrentAndPriorFileWrites         1 calls<br>       12 ms  ProcessFrameworkReferences                 3 calls<br>       13 ms  _ResolveRazorGenerateOutputs               1 calls<br>       14 ms  _GenerateCompileDependencyCache            1 calls<br>       17 ms  GenerateBuildDependencyFile                1 calls<br>       23 ms  _ResolveRazorComponentOutputs              1 calls<br>       32 ms  ResolvePackageAssets                       3 calls<br>       32 ms  PrepareForBuild                            1 calls<br>       33 ms  ResolveLockFileReferences                  3 calls<br>       35 ms  _HandlePackageFileConflicts                1 calls<br>       50 ms  FindReferenceAssembliesForReferences       1 calls<br>      120 ms  ResolveReferencedProjectsStaticWebAssets   3 calls<br>      186 ms  ResolveAssemblyReferences                  1 calls<br>      330 ms  ResolveProjectReferences                   1 calls<br>      373 ms  _ComputeReferenceAssemblies                1 calls<br>      572 ms  RazorCompileComponentDeclaration           1 calls<br>     1602 ms  ResolveTagHelperRazorGenerateInputs        1 calls<br>     3097 ms  RazorCoreGenerate                          1 calls<br>    242346 ms  CoreCompile                                1 calls<br>        (* = timing was not recorded because of reentrancy)<br><br>Task Performance Summary:<br>        * ms  AssignTargetPath                          14 calls<br>        * ms  CallTarget                                 2 calls<br>        * ms  MSBuild                                    5 calls<br>        0 ms  Telemetry                                  1 calls<br>        0 ms  ReadLinesFromFile                          1 calls<br>        0 ms  Delete                                     2 calls<br>        0 ms  ResolveCodeAnalysisRuleSet                 1 calls<br>        0 ms  GetAssemblyVersion                         1 calls<br>        0 ms  AssignCulture                              1 calls<br>        0 ms  ResolveFrameworkReferences                 1 calls<br>        0 ms  GetPackageDirectory                        6 calls<br>        0 ms  RemoveDuplicates                           2 calls<br>        0 ms  ShowPreviewMessage                         1 calls<br>        1 ms  ApplyImplicitVersions                      3 calls<br>        1 ms  GetFrameworkPath                           1 calls<br>        1 ms  Message                                    4 calls<br>        1 ms  Hash                                       8 calls<br>        1 ms  FindUnderPath                              5 calls<br>        1 ms  MakeDir                                    4 calls<br>        1 ms  CheckForDuplicateFrameworkReferences       3 calls<br>        2 ms  GetRestoreProjectStyleTask                 1 calls<br>        2 ms  Touch                                      2 calls<br>        3 ms  CheckIfPackageReferenceShouldBeFrameworkReference   4 calls<br>        3 ms  ResolveAppHosts                            3 calls<br>        3 ms  CheckForDuplicateItems                     3 calls<br>        3 ms  WriteLinesToFile                           8 calls<br>        4 ms  Copy                                       3 calls<br>        4 ms  ResolveTargetingPackAssets                 1 calls<br>        5 ms  ProcessFrameworkReferences                 3 calls<br>        5 ms  AssignProjectConfiguration                 3 calls<br>        5 ms  ConvertToAbsolutePath                      1 calls<br>        7 ms  JoinItems                                  3 calls<br>       11 ms  GenerateDepsFile                           1 calls<br>       11 ms  CheckForImplicitPackageReferenceOverrides   3 calls<br>       11 ms  GetReferenceNearestTargetFrameworkTask     1 calls<br>       12 ms  RemoveDir                                  1 calls<br>       17 ms  ResolveNonMSBuildProjectOutput             1 calls<br>       22 ms  ResolvePackageFileConflicts                1 calls<br>       31 ms  ResolvePackageAssets                       3 calls<br>       32 ms  FindAppConfigFile                          1 calls<br>      186 ms  ResolveAssemblyReference                   1 calls<br>     1596 ms  RazorTagHelper                             1 calls<br>     3082 ms  RazorGenerate                              1 calls<br>    242910 ms  Csc                                        2 calls<br>        (* = timing was not recorded because of reentrancy)<br><br>Build succeeded.<br>    0 Warning(s)<br>    0 Error(s)
#### Feedback Bot on 7/22/2020, 08:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hesuruio** [comment]
Hi! It turned out to be the issue already reported around Nullable and Razor components.
[https://github.com/dotnet/aspnetcore/issues/24156](url)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will use the referenced issue to track this. Closing as a dupe.
