### ISSUE TITLE
Razor component in <table> element renders twice

### ISSUE THREAD

**Issue by ThatFlashCat** [dotnet/aspnetcore#24294]
### Describe the bug
When placed within a table element, razor components will render once within the table and once outside the table. This occurs within a .NET Core MVC project that has the necessary services added for Blazor server (not the WASM version) to function. I have created a razor component and placed it within a `<table>` element without `<tr>` or `<td>` elements. The behavior varies for the three render modes:

- ServerPrerendered: the component renders twice, once inside the table and once outside it. The component inside the table is interactive while the one outside is not.
- Static: the component renders once outside of the table despite being declared within it and is not interactive.
- Server: the component renders once within the table as expected and is interactive.

For static and server rendered components the only unusual part is the placement of the former outside of the table it was declared in. However, all three modes behave as they should if placed inside `<table><tr><td></td></tr></table>` as a table would typically be declared. I still think the behavior of razor components within a bare `<table>` element is bugged and there are valid use cases for placing components directly within tables. I discovered this bug on a project where the table footer is composed of a partial view and the rows are razor components (allowing for easy editing in an otherwise static page). It would be inconvenient to be forced to move the table fully within the razor component.

### To Reproduce

1. Create a default MVC project and follow the instructions [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/integrate-components?view=aspnetcore-3.1#prepare-the-app) to add blazor to the app.
2. Create a razor component with minimal code. I'm using the default counter component from the blazor template.
3. Create a `<table>` element and use the `<component>` tag to add the component you created to the page. I have [included a repository](https://github.com/ThatFlashCat/BlazorTableBugRepro) reproducing this issue on the home/index page.

### Exceptions (if any)
Not applicable

### Further technical details
- ASP.NET Core version: 3.1.302
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version Visual Studio 2019 16.6.5

**Comment by javiercn** [comment]
@ThatFlashCat thanks for contacting us. 

This is expected since I'm assuming you are prerendering. The app gets rendered once on the server and then the state is discarded.

**Comment by ThatFlashCat** [comment]
That makes sense, but why is the prerender occurring outside of the `<table>` element?

**Comment by javiercn** [comment]
@ThatFlashCat I didn't see the repro you included.



> For static and server rendered components the only unusual part is the placement of the former outside of the table it was declared in

This is troublesome, scecifically for static components, which only end up as regular markup on the page. Can you check the httpresponse on the network tab?

I can't think of a way in which a static rendered component can be rendered in a different position it was called on. 

For a server component I can understand there might be a bug in how it inserts itself when it goes interactive, but the other two sound suspicious.

**Comment by ThatFlashCat** [comment]
@javiercn The repro is there but I put it inside a hyperlink toward the end of my initial post, but I added the link here as well: https://github.com/ThatFlashCat/BlazorTableBugRepro

I took a look at the http response and found something very odd.

This part of the razor component:
```cshtml
<table>
    <component type="typeof(Counter)" render-mode="Static" />
</table>
```
Shows up like this in the httpresponse:
```html
<table>
    <p>Current count: 0</p>
<button class="btn btn-primary">Click me</button>
</table>
```
As it should, so no issue there, but when I inspect the elements in the page, I see this:
```html
<p>Current count: 0</p>
<button class="btn btn-primary">Click me</button>
<table>
 ```
I'm seeing this on the index page of the repro I included above.


</table>```

**Comment by javiercn** [comment]
@ThatFlashCat thanks for the details.

Than can just be the browser. I believe `table` items don't accept random things, and as part of parsing the browser might decide to take them out. I would have to check the HTML5 spec to confirm, but I know the parsing algorithm does things like that in other scenarios.

**Comment by ThatFlashCat** [comment]
That would make sense. I observed this behavior in Chrome 84, Firefox, and Edge (Chromium based).

**Comment by ThatFlashCat** [comment]
I'm going to close this unless you have anything else to add @javiercn. Thanks for your help!
