### ISSUE TITLE
Explicit Expression Completions Not Working

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24292]
![image](https://user-images.githubusercontent.com/14852843/88424809-10984780-cda3-11ea-91fe-65594c3105e3.png)

TagHelper attributes (non-Blazor) fall over in completion scenarios: Aka a `true` completion item is expected here 

`<form asp-antiforgery="tr|">`

**Comment by ajaybhargavb** [comment]
Fixes in https://github.com/dotnet/aspnetcore-tooling/pull/2267.
