### ISSUE TITLE
[Blazor wasm hosted] Missing satellite assemblies in output folder when publishing a hosted Blazor wasm project

### ISSUE THREAD

**Issue by stavroskasidis** [dotnet/aspnetcore#24298]
### Describe the bug
In a blazor wasm **hosted** project, when you have a project with resources referenced by both the client and the server project, publishing the server project the satellite assemblies are not copied over to the output folder. 

They are however copied (and compressed) correctly to the "**wwwroot/_framework/_bin**" folder.

### To Reproduce
1. Create a new Blazor wasm hosted project named "**BlazorApp1**".
2. Add a .resx file in "**BlazorApp1.Shared**" called **StringResources.resx** (public code generation).
3. Add a string key/value in that file -> Test | "Test".
4. Add a .resx file in "**BlazorApp1.Shared**" called **StringResources.el.resx** (no code generation).
5. Add a string key/value  in that file -> Test | "Τεστ".
6. Go to folder "**BlazorApp1\Server**" and run `dotnet publish -c Release`
7. See that the **"el"** folder containing the translations is missing from the "**BlazorApp1\Server\bin\Release\netcoreapp3.1\publish**" folder. 
It is however present (as expected) in the "**BlazorApp1\Server\bin\Release\netcoreapp3.1\publish\wwwroot\\_framework\\_bin**" folder.

#### Extra steps to validate that something in blazor tooling causes it

8. Remove the following from the **Blazor1.Server** project:
* The project reference to **Blazor1.Client**
* The package reference to `Microsoft.AspNetCore.Components.WebAssembly.Server` 
* Blazor startup code in `Startup.cs`
```
//Remove these to be able to compile
//app.UseWebAssemblyDebugging();
//app.UseBlazorFrameworkFiles();
```

9. Go to folder **"BlazorApp1\Server"** and run `dotnet publish -c Release` again.
10. The "**el**" satellite folder appears now correctly in the publish output.

### Further technical details
- SDK Version 3.1.302

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which we track as part of #21406
