### ISSUE TITLE
Microsoft.AspNetCore.Authentication.JwtBearer - Jwks Endpoint

### ISSUE THREAD

**Issue by brunohbrito** [dotnet/aspnetcore#24309]
### Is your feature request related to a problem? Please describe.
I'm trying to change the default Jwks uri. Because my environment isn't an OAuth2 & OpenId. So we don't have a open discovery document. We only have an Authentication API who expose a JWKS endpoint. But it seems there isn't a easy way to accomplish that at `Microsoft.AspNetCore.Authentication.JwtBearer`.

### Describe the solution you'd like
Some way to change JWKS Uri in a more easy way. If we analyze another components for node and java. They have a built-in feature. E.G: auth0 [node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken/blob/master/README.md#L218)

```node
// line 218
var client = jwksClient({
  jwksUri: 'https://sandrino.auth0.com/.well-known/jwks.json' // <-- easy way to change for anything else
});
```

### Additional context
A cache time, for performance issues. Actually NIST says to change cryptographic keys every years. But nowadays 90 days is a good practice. So the API doesn't need to get the public keys at every request.

**Comment by Tratcher** [comment]
The discovery document and the keys are downloaded at the same time here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a55020dba088171882bc3b4da3882772dd6ff3d2/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs#L89-L106

We haven't seen demand for separating those operations.

Normally if you weren't using a discovery document you'd create a OpenIdConnectConfiguration instance with all the options and keys and assign it to JwtBearerOptions.Configuration.
https://github.com/dotnet/aspnetcore/blob/e3501ddd4a9c292fb43b89bf50676def919c13cd/src/Security/Authentication/JwtBearer/src/JwtBearerOptions.cs#L76-L82

You could also provide a JwtBearerOptions.ConfigurationManager that let you provide local configuration and remote Jwks.

Most of the pieces are available and they include caching and rollover support. Here's how we put them together:
https://github.com/dotnet/aspnetcore/blob/e3501ddd4a9c292fb43b89bf50676def919c13cd/src/Security/Authentication/JwtBearer/src/JwtBearerPostConfigureOptions.cs#L53-L58

OpenIdConnectConfigurationRetriever should be the only one you need to replace/customize.

**Comment by brunohbrito** [comment]
@Tratcher I really understand that is unusual requirement, but don't you think that it's because normally developers don't care about security at all?

Actually .NET Jwt basically has 2 simple options: Jwt with OAuth2 & OpenId, when we specify the authority, or symetric keys.

Symetric keys are too simple and OAuth2 too complex. Maybe a intermediate scenario is a JWKS endpoint to prevent developers and teams sharing the key.

If we google "Jwt c# example" almost 99% of examples uses a symetric key as example and they dont mention the flaws about such decision. And in my opinion we lack of support on .Net to show how simple is to expose a jwks_uri and at same time keep it as simple as oauth2 API example.

But if we check at [Java spring boot](https://docs.spring.io/spring-security-oauth2-boot/docs/2.0.0.RC2/reference/htmlsingle/#boot-features-security-oauth2-resource-server) or node as well. They keep this "intermediate scenario" in the first page of docs. Which means more options for those who cares about it and easy for us to spread a better solution than simple symetric keys without the complexity of an oauth2.

Maybe we can go deeper and build another native component in ASP.NET Core to generate and share a jwks_uri with just few line of codes? This one is just a dream, but it could come true... who knows lol....

**Comment by Tratcher** [comment]
Let's get it working at all and then we can look for ways to simply it. Try tweaking the OpenIdConnectConfigurationRetriever and let me know if that works for you.

**Comment by brunohbrito** [comment]
@Tratcher I got the job done. I'll show first how it was before and after your directions.

// Before
```csharp

// Startup.cs
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.RequireHttpsMetadata = true;
                    options.SaveToken = true;
                    // Extension method
                    options.SetJwksOptions(new JwkOptions(Configuration["JwksUri"]));
                });
        }

    public static class JwksExtension
    {
        public static void SetJwksOptions(this JwtBearerOptions options, JwkOptions jwkOptions)
        {
            if (options.TokenValidationParameters == null)
                options.TokenValidationParameters = new TokenValidationParameters();

            if (options.TokenValidationParameters.IssuerSigningKeyResolver == null)
                options.TokenValidationParameters.IssuerSigningKeyResolver = new JwkRetriever(jwkOptions).IssuerSigningKeyResolver;
        }
    }
    public class JwkRetriever
    {
        private static readonly HttpClient HttpClient = new HttpClient();

        public JwkRetriever(JwkOptions jwkOptions)
        {
            Options = jwkOptions;
        }

        public JwkOptions Options { get; }
        public JwkList LastResponse { get; private set; }
        public IEnumerable<SecurityKey> IssuerSigningKeyResolver(string token, SecurityToken securityToken, string kid, TokenValidationParameters validationParameters)
        {
            if (LastResponse == null || LastResponse.When.Add(Options.KeepFor) < DateTime.Now)
            {
                var jwkTask = GetJwks();
                jwkTask.Wait();
                LastResponse = new JwkList(jwkTask.Result);
            }

            return LastResponse.Jwks.Keys;
        }

        private async Task<JsonWebKeySet> GetJwks()
        {
            var response = await HttpClient.GetAsync(Options.JwksUri);
            var responseString = await response.Content.ReadAsStringAsync();
            return new JsonWebKeySet(responseString);

        }
    }
```

After your directions, I got it already has cache. So I don't need to deal with such complexity. So now it's like this:

```csharp

    // Startup.cs
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.RequireHttpsMetadata = true;
                options.SaveToken = true;
                    // Extension method
                    options.SetJwksOptions(new JwkOptions(Configuration["JwksUri"]));
            });
    }
    public static class JwksExtension
    {
        public static void SetJwksOptions(this JwtBearerOptions options, JwkOptions jwkOptions)
        {
            var httpClient = new HttpClient(options.BackchannelHttpHandler ?? new HttpClientHandler())
            {
                Timeout = options.BackchannelTimeout,
                MaxResponseContentBufferSize = 1024 * 1024 * 10 // 10 MB 
            };

            options.ConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
                jwkOptions.JwksUri.OriginalString,
                new JwksRetrieverNew(),
                new HttpDocumentRetriever(httpClient) { RequireHttps = options.RequireHttpsMetadata });
        }
    }

    public class JwksRetrieverNew : IConfigurationRetriever<OpenIdConnectConfiguration>
    {
        public Task<OpenIdConnectConfiguration> GetConfigurationAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
        {
            return GetAsync(address, retriever, cancel);
        }

        /// <summary>
        /// Retrieves a populated <see cref="OpenIdConnectConfiguration"/> given an address and an <see cref="IDocumentRetriever"/>.
        /// </summary>
        /// <param name="address">address of the jwks uri.</param>
        /// <param name="retriever">the <see cref="IDocumentRetriever"/> to use to read the jwks</param>
        /// <param name="cancel"><see cref="CancellationToken"/>.</param>
        /// <returns>A populated <see cref="OpenIdConnectConfiguration"/> instance.</returns>
        public static async Task<OpenIdConnectConfiguration> GetAsync(string address, IDocumentRetriever retriever, CancellationToken cancel)
        {
            if (string.IsNullOrWhiteSpace(address))
                throw LogHelper.LogArgumentNullException(nameof(address));

            if (retriever == null)
                throw LogHelper.LogArgumentNullException(nameof(retriever));

            var doc = await retriever.GetDocumentAsync(address, cancel).ConfigureAwait(false);
            LogHelper.LogVerbose("IDX21811: Deserializing the string: '{0}' obtained from metadata endpoint into openIdConnectConfiguration object.", doc);
            var jwks = new JsonWebKeySet(doc);
            var openIdConnectConfiguration = new OpenIdConnectConfiguration()
            {
                JsonWebKeySet = jwks,
                JwksUri = address,
            };
            foreach (var securityKey in jwks.GetSigningKeys())
                openIdConnectConfiguration.SigningKeys.Add(securityKey);

            return openIdConnectConfiguration;
        }
    }
```

I feel good with new implementation, because it uses the JwtBearer components and I'm not going to reinventing the wheel.

But what I don't like is to reuse the component `OpenIdConfiguration`. It may lead developers for some kind of misconception. under the hood we're not using OpenId.

**Comment by Tratcher** [comment]
> But what I don't like is to reuse the component OpenIdConfiguration.

Our JwtBearer implementation is fundamentally based on OpenIdConnect. That it works for anything else is more of a coincidence. We're unlikely to add first class support for other protocols unless they are major standards like OIDC.

You're welcome to propose ways to make this easier to extend though.
