### ISSUE TITLE
.razor.css changes don't trigger VS's fast up-to-date check

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#24300]
Repro:

 * Add a `.razor.css` file to the project and build it
 * Edit your `.razor.css` file and try building again

Expected:

 * VS should rebuild the project

Actual:

 * VS says the project is already up-to-date and doesn't build it, so the change doesn't really take effect

cc @javiercn

**Comment by SteveSandersonMS** [comment]
Actually my VS instance is behaving crazily and doing the same thing even for `.cs` files, so I can't really conclusively say what's going on. My suspicion though is that unless we do something to tell VS to look at `.razor.css` changes in its fast-up-to-date check, it won't.

**Comment by javiercn** [comment]
I'll give it a try. 

We need to add them to the up to date marker or something like that.

**Comment by SteveSandersonMS** [comment]
I tried adding the following to my csproj:

```xml
<UpToDateCheckInput Include="@(Content->WithMetadataValue('Extension', '.razor.css'))" />
```

However it doesn't work - it behaves the same as if that isn't there. I think we should prioritise investigating this, because if we end up needing a VS change to fix this, we'll want to know ASAP.

**Comment by javiercn** [comment]
This is part of what I'm working on as part of the css isolation follow-ups

**Comment by javiercn** [comment]
BTW,

this likely doesn't work because the extension will be ".css" and omit the ".razor" bit.

> ```
> <UpToDateCheckInput Include="@(Content->WithMetadataValue('Extension', '.razor.css'))" />
> ```

You can hook into a target to add the itemgroup after the list of ScopedCssInput items has been computed.

**Comment by bignorm64** [comment]
@SteveSandersonMS 

> this likely doesn't work because the extension will be ".css" and omit the ".razor" bit.
> 
> > ```
> > <UpToDateCheckInput Include="@(Content->WithMetadataValue('Extension', '.razor.css'))" />
> > ```

I am having this issue in preview 8 and tried the above suggestion without the '.razor' bit but it made no difference however after doing a bit of searching on UpToDateCheckInput I found an issue that said unless an 'input' also had an 'output' then including a file had no effect so I changed the 'Build action' of the CSS file to 'Content' and then it worked.
