### ISSUE TITLE
Default value for [Parameter] / optional parameter values. 

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#24301]
**Problem:**
In many situations, a component is expected to have a 'default' behavior. There is no way to assign a default value to Parameters which is visible outside the component (in situ assignments at property setter/ in OnInitialized aren't visible outside). This is exactly like optional arguments in C# methods. This will make the code less cluttered. 

**Suggested Solution:**
An argument to [Parameter] that specifies the default value at compile time. 

**For example:**

Current:
FooComponent.razor

```
Hello @Count 

@code
{
[Parameter]
public int Count {get;set;}
}
```

FooParent.razor

```

<FooComponent />
// Count is set to 0
```

Proposed:

FooComponent.razor

```
Hello @Count 

@code
{
[Parameter(default : 5)]
public int Count {get;set;}
}
```
FooParent.razor

```
<FooComponent />

//Count is set to 5
```

**Comment by javiercn** [comment]
@mayur-ekbote thanks for contacting us. 

Does
```csharp
[Parameter]
public int Count {get;set;} = 5;
```

not work for you?
