### ISSUE TITLE
Running MvcSandbox sample project from source through ANCM fails with 500.33 error

### ISSUE THREAD

**Issue by seangwright** [dotnet/aspnetcore#24304]
### Describe the bug
Building the source works well when following the instructions [outlined in BuildFromSource.md](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md).

However, when trying to run [MvcSandbox](https://github.com/dotnet/aspnetcore/tree/master/src/Mvc/samples/MvcSandbox) in Visual Studio using ANCM, the ANCM integration fails with `HTTP Error 500.33 - ANCM Request Handler Load Failure`.

### To Reproduce
Follow the steps in [BuildFromSource.md](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md) and try to run the `MvcSandbox` project through ANCM.

### Exceptions (if any)
```
HTTP Error 500.33 - ANCM Request Handler Load Failure
Common solutions to this issue:
Make sure Microsoft.AspNetCore.App is referenced by your application.
Specific error detected by ANCM:
Could not find the assembly 'aspnetcorev2_inprocess.dll' referenced for the in-process application. Please confirm the Microsoft.AspNetCore.Server.IIS or Microsoft.AspNetCore.App is referenced in your application.
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526
```

### Further technical details

I'm working out of the `release/3.1` branch since I'm working on 3.1 projects, so the instructions are slightly different from `master` currently.

As noted in [this comment](https://github.com/dotnet/aspnetcore/issues/16976#issuecomment-552526565)

> we haven't done the work to get inprocess working in samples because we removed the dependency on building native by default.

This isn't a huge issue since running the app through Kestrel works fine, but maybe it would be helpful to add a README.md to the [MVC README.md](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/README.md) to indicate ANCM cannot be used or to a new README.md in the MvcSandbox folder.

I just spent 3 hours trying to get this to work thinking I had VS, the SDK, or the ANCM module misconfigured... 🤦‍♂️.

I'd be happy to make a PR!

I appreciate how (relatively) painless it was to get the source running locally, so thanks for the work that went into that.

**Comment by pranavkm** [comment]
> I'd be happy to make a PR!

@seangwright. It'd be great if you could add it to BuildFromSource. The problem isn't specify to MvcSandbox but most runnable apps in the repository.

FYI @jkotalik

**Comment by seangwright** [comment]
👍 Should I branch off `master` or is there a release branch I should use?

**Comment by pranavkm** [comment]
Master works fine.
