### ISSUE TITLE
Include interfaces for UserManager and other Identity managers.

### ISSUE THREAD

**Issue by srajkovic** [dotnet/aspnetcore#24319]
### Is your feature request related to a problem? Please describe.
I am trying to unit test my custom code around registration, but its difficult to mock the dependency on the UserManager, since it's injected as a concrete class instead of an interface, and the constructor has lots of a dependencies, which means Moq can't easily construct a mock using `new Mock<UserManager<UserType>>`.

### Describe the solution you'd like
An interface IUserManager (same for all the other managers) that can be injected, and makes it easier to use Moq to mock these dependencies and test code that depends on them, just using `new Mock<IUserManager<UserType>>`. The interface can just have all the same members as the UserManager class has now.

### Additional context
The Moq error I get:
```
Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: Microsoft.AspNetCore.Identity.UserManager`1[[<UserType>, <Assembly>, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
    Could not find a parameterless constructor.
```
I believe I can use [this constructor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1.-ctor?view=aspnetcore-3.1#Microsoft_AspNetCore_Identity_UserManager_1__ctor_Microsoft_AspNetCore_Identity_IUserStore__0__Microsoft_Extensions_Options_IOptions_Microsoft_AspNetCore_Identity_IdentityOptions__Microsoft_AspNetCore_Identity_IPasswordHasher__0__System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Identity_IUserValidator__0___System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Identity_IPasswordValidator__0___Microsoft_AspNetCore_Identity_ILookupNormalizer_Microsoft_AspNetCore_Identity_IdentityErrorDescriber_System_IServiceProvider_Microsoft_Extensions_Logging_ILogger_Microsoft_AspNetCore_Identity_UserManager__0___) with Moq, but now I have to mock 9 interfaces (or pass nulls if that doesn't cause other problems) instead of just being able to Mock one.

**Comment by davidfowl** [comment]
Big interfaces like this are born fragile as we keep adding functionality to these types, they are god objects.

**Comment by blowdart** [comment]
As David says, using an interface would make adding or changing functionality far too difficult. Avoiding an interface is by design.
