### ISSUE TITLE
use  Microsoft.Extensions.FileProviders.Embedded ，when file name is xx.cs.xx ResourcePath is wrong

### ISSUE THREAD

**Issue by luoyunchong** [dotnet/aspnetcore#24314]
### Describe the bug

I use **Microsoft.Extensions.FileProviders.Embedded**  

When the embedded file name is in the form of xxxx.cs.xxxx. 

ResourcePath  value  cannot be recognized

![image](https://user-images.githubusercontent.com/18613266/88462150-c49cee00-cedb-11ea-8549-5f8e6e284e36.png)

code is simple,
```
using Microsoft.Extensions.FileProviders;
using System;
using System.IO;
using System.Reflection;
using System.Text;

namespace FileTest
{
    class Program
    {
        static void Main(string[] args)
        {

            string[] paths = {
                "ABC.html.txt",
                "ABC.cs.txt"
            };

            foreach (var path in paths)
            {
               Embedded("./" + path);
            }

            Console.WriteLine("over!");
        }

        static void Embedded(string path)
        {
            IFileProvider fileProvider = new ManifestEmbeddedFileProvider(Assembly.GetExecutingAssembly());
            IFileInfo fileInfo = fileProvider.GetFileInfo(path);
            string text;
            using (Stream stream = fileInfo.CreateReadStream())
            {
                using var streamReader = new StreamReader(stream, Encoding.UTF8, true);
                text = streamReader.ReadToEnd();
            }
            Console.WriteLine(text);
        }
    }
}

```
### To Reproduce

[FileTest.zip](https://github.com/dotnet/aspnetcore/files/4976003/FileTest.zip)

### Exceptions (if any)

   at Microsoft.Extensions.FileProviders.Embedded.Manifest.ManifestFileInfo.CreateReadStream()
   at FileTest.Program.Embedded(String path) in C:\Users\Computer\Desktop\FileTest\Program.cs:line 32
   at FileTest.Program.Main(String[] args) in C:\Users\Computer\Desktop\FileTest\Program.cs:line 21

### Further technical details
- ASP.NET Core 3.1
```
C:\WINDOWS\system32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20175
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]
```
-  Microsoft Visual Studio Enterprise 2019 Preview
版本 16.7.0 Preview 3.1

**Comment by mkArtakMSFT** [comment]
@javiercn any recommendation where this should go? (mvc or platform) ?

**Comment by javiercn** [comment]
Use ManifestFileEmbeddedProvider which is designed to be full-fidelity or instead of that, use static web assets if possible. This is a known limitation of EmbeddedFileProvider we don't plan to address.

**Comment by javiercn** [comment]
Also, not sure if this moved to the runtime repo

**Comment by luoyunchong** [comment]
Thanks,I use **Microsoft.Extensions.FileProviders . physical**  can also solve my problem
