### ISSUE TITLE
OnConnected called before OnDisconnected when leaving page

### ISSUE THREAD

**Issue by Bleron213** [dotnet/aspnetcore#24313]
Hello.

**Describe the Bug:**
We have an application that is running on Angular and .NET Core, for which it also utilizes SignalR with Automatic Reconnecting. The methods which we have overrided and have logic inside of them are **OnConnected** and **OnDisconnected**. 

When running the application in localhost, the order of the methods when _refreshing the page_ is
1. OnDisconnected is called
2. OnConnected is called

When running the application in Azure Web Apps, the order of the methods called suddenly changes. When refreshing the page:
1. OnConnected is called first
2. OnDisconnected is called after

I've tested it with logs, and the OnDisconnected method is almost always after the OnConnected when the application is hosted.

Which logically shouldn't happen, since the Client disconnects first and then reconnects.
**To Reproduce:**
A SignalR project needs to be hosted on Azure Web Apps.
```
public override Task OnDisconnectedAsync(Exception exception)
{
     using (StreamWriter outputFile = new StreamWriter(@".\MethodsCalled.txt", true)) // loging code
     {
           outputFile.WriteLine("OnDisconnectedAsync Called");
     }
     return base.OnDisconnectedAsync(exception);
}

public override Task OnConnectedAsync()
{
    using (StreamWriter outputFile = new StreamWriter(@".\MethodsCalled.txt", true)) // loging code
    {
         outputFile.WriteLine("OnConnectedAsync Called");
    }
    return base.OnConnectedAsync();
}
```
Front end code:

```
 this.hubConnection = new signalR.HubConnectionBuilder()
       .withUrl("url to hub", { accessTokenFactory: () => token })
       .configureLogging(signalR.LogLevel.Debug)
       .withAutomaticReconnect([0, 3000, 5000, 10000, 15000, 30000])
       .build();

this.hubConnection
      .start()
      .then(() => {
          console.log('Connection started');
      })
      .catch((err) =>
         console.log('Error while starting connection:' + err)
);

```
*Further technical details:*

- ASP.NET Core version: 3.1.301
- Since it's working locally as expected, not not when hosted I'm not sure whether the dotnet --info will be of any use. However, I'll attach it below:

```
NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```
- The IDE: Visual Studio 2019.

**Comment by davidfowl** [comment]
Can you also log the connection id? It's not possible to tell if there's an issue without logging the id

**Comment by BrennanConroy** [comment]
This seems normal, if you disconnect ungracefully then the disconnect will run at some "arbitrary" time in the future and a new connection can occur before the old one is disconnected.

**Comment by Bleron213** [comment]
Hi @davidfowl, I apologize for the delay. Here are the logs
Local Logs:
```
_-- this is where I log in initially_
OnConnectedAsync Called
Connected with SessionId: f9b8b1e6-06ea-4c87-a552-3c276e7a6b3e
Connected UserId: 98cc712f-fdf1-4f48-9750-5341faba5ee0
Connected ConnectionId: sb1OhCzSoVAtImR71-83rg
Timestamp:7/28/2020 9:12:23 AM

_-- this is where I refresh the browser_

OnDisconnectedAsync Called
Disconnected with SessionId:f9b8b1e6-06ea-4c87-a552-3c276e7a6b3e
Disconnected UserId: 98cc712f-fdf1-4f48-9750-5341faba5ee0
Disconnected ConnectionId: sb1OhCzSoVAtImR71-83rg
Timestamp:7/28/2020 9:12:35 AM

OnConnectedAsync Called
Connected with SessionId:f9b8b1e6-06ea-4c87-a552-3c276e7a6b3e
Connected UserId: 98cc712f-fdf1-4f48-9750-5341faba5ee0
Connected ConnectionId: 1neWv1g-fQIAzf5OjU7gHA
Timestamp:7/28/2020 9:12:43 AM

```
The order of the methods locally never seems to change. It's always OnDisconnected first and OnConnected after, which is the behaviour I'm expecting.

Here are the logs from the hosted application on the web:
```
_-- this is where I log in_

OnConnectedAsync Called
Connected with SessionId:a8c52b41-35c8-4857-88c9-c883b054025f
Connected UserId: 98cc712f-fdf1-4f48-9750-5341faba5ee0
Connected ConnectionId: q9Quom5a3taoUfMTTqx01A
Timestamp:7/28/2020 7:42:21 AM

_-- this is where I refresh the browser_

OnConnectedAsync Called
Connected with SessionId:a8c52b41-35c8-4857-88c9-c883b054025f
Connected UserId: 98cc712f-fdf1-4f48-9750-5341faba5ee0
Connected ConnectionId: eOjR0_cvhcAOqwPP2m69xw
Timestamp:7/28/2020 7:42:30 AM

OnDisconnectedAsync Called
Disconnected with SessionId:a8c52b41-35c8-4857-88c9-c883b054025f
Disconnected UserId: 98cc712f-fdf1-4f48-9750-5341faba5ee0
Disconnected ConnectionId: q9Quom5a3taoUfMTTqx01A
Timestamp:7/28/2020 7:42:36 AM

```
The order of the method is important because once the user logs in, I add his UserId & SessionId to a map, and once the user disconnects I remove the user from that map. In this case, once I refresh the browser the user gets removed from the map, and once the user reconnects he gets added again to that map, with the correct connectionId. Since this workflow is failing when the application is hosted, the communication fails despite the SignalR link having been established correctly.

**Comment by Bleron213** [comment]
Hi @BrennanConroy . Thanks for the info. If this is the normal behavior, then should **OnDisconnected** method be called after the **OnConnected** method when the application is working locally?

**Comment by davidfowl** [comment]
@Bleron213 I'm confused what you are asking. Each connection is unique so OnConnected will always fire before OnDisconnected otherwise something is awry. The fact that connections for different users can fire OnConnected and OnDisconnected in different order is irrelevant, the only important thing is that you'll have an OnConnected fired for ever OnDisconnected event.

**Comment by Bleron213** [comment]
@davidfowl Thanks for the explanation. I'm closing the issue now.
