### ISSUE TITLE
DefaultAuthorizationService Unable to locate claim type matching specified value. Blazor WASM.

### ISSUE THREAD

**Issue by Flash619** [dotnet/aspnetcore#24312]
# Describe the bug
I have created a custom AuthorizationPolicyProvider to add functionality to the DefaultAuthorizationPolicyProvider. This new provider will look for a claim `granted_authority` and  require that the value be present in the claim by means of a new AuthorizationPolicy. 

```c#
    public class AuthorizationPolicyProvider : DefaultAuthorizationPolicyProvider
    {
        public AuthorizationPolicyProvider(IOptions<AuthorizationOptions> options) : base(options)
        {
        }

        public override Task<AuthorizationPolicy> GetPolicyAsync(string policyName)
        {
            if (!policyName.StartsWith(PermissionAuthorizeAttribute.PolicyPrefix, StringComparison.OrdinalIgnoreCase))
            {
                return base.GetPolicyAsync(policyName);
            }

            var permissionNames = policyName.Substring(PermissionAuthorizeAttribute.PolicyPrefix.Length).Split(",");

            var policy = new AuthorizationPolicyBuilder()
                .RequireClaim("granted_authority", permissionNames)
                .Build();

            return Task.FromResult(policy);
        }
    }
```

I then extend AuthorizeView to attempt to achieve the desired functionality.

```c#
    public class PermissionAuthorizeView : AuthorizeView
    {
        [Parameter]
        public string[] Permissions
        {
            set => Policy = $"{PermissionAuthorizeAttribute.PolicyPrefix}{string.Join(",", value)}";
        }        
        
        [Parameter]
        public string Permission
        {
            set => Permissions = new string[] {value};
        }

        public PermissionAuthorizeView() : base()
        {
        }
    }
```

When I attempt to use my custom PermissionAuthorizeView component, I receive the following message in console.

> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
>       Authorization failed. These requirements were not met:
>       ClaimsAuthorizationRequirement:Claim.Type=granted_authority and Claim.Value is one of the following values: (location.read)

However, when reviewing my active claims I see the following claim.

`granted_authority: ["location.read","user.read","status.submit","status.read","status.modify_own","weather.read","location.update","location.create","location.delete"]`

To review the active claims, I used the following code.

```c#
    protected override async Task OnInitializedAsync()
    {
        var auth = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        var user = auth.User;
        var claims = user.Claims;
        foreach (var claim in claims)
        {
            await Console.Error.WriteLineAsync($"{claim.Type}: {claim.Value}");
        }
    }
```

Based on the information above. I can see that the `granted_authority` claim does exist, and that it does have a value of `location.read`.

For this reason I believe authorization should succeed instead of fail. 

I have the exact same code working on a .NET Core rest api (all except for the Balzor component). It seems to work fine on the server side API, however when using Blazor WASM I end up with this issue. 

### Further technical details
- Libraries Used:
```
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview3.20168.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-preview.6.20312.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="5.0.0-preview.6.20312.15" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-preview.6.20312.15" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="5.0.0-preview.6.20312.15" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0-preview.6.20305.6" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0-preview.6.20305.6" />
```

- Include the output of `dotnet --info`
> .NET SDK (reflecting any global.json):
>  Version:   5.0.100-preview.6.20318.15
>  Commit:    4356580024
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\
> 
> Host (useful for support):
>   Version: 5.0.0-preview.6.20305.6
>   Commit:  4ba9ecaabd
> 
> .NET SDKs installed:
>   3.1.301 [C:\Program Files\dotnet\sdk]
>   5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
> JetBrains Rider 2020.2 EAP 7

**Comment by javiercn** [comment]
@Flash619 thanks for contacting us.

I don't know what can be going wrong in your app, we would need a minimal repro project to investigate. That said, I believe that instead of extending defaultAuthorizationPolicyProvider you should simply configure the default policy within the authorization system and leave the default implementation as it is.

You can do so by calling `services.AddAuthorization(o => o.DefaultPolicy = new AuthorizationPolicyBuilder(o.DefaultPolicy).RequireClaim(...).Build())`

Overriding the authorization policy provider is only meant to be used when you want to change the source of the policies or the way they are combined (to come from the Db and so on).

**Comment by Flash619** [comment]
@javiercn Thanks for your reply.

For a minimal repo project, would you also need the auth server that is interacting with the spa? Or would you only need the code for the spa? 

I'll try your recommendation and comment the results once I have some. 😄

**Comment by mkArtakMSFT** [comment]
@javiercn leaving this for you to drive. Thanks!

**Comment by Flash619** [comment]
So far I have gone through the code for my rest api which is written in .net core 3.1. I have the exact same code in each, the only exception is that the Blazor SPA WASM app is using AuthorizeView. The .net core implementation works without issue. 

I'm not sure how AuthorizeView accesses claim data for the current user, but it seems like its not finding the correct data.

**Comment by Flash619** [comment]
@javiercn I was able to find another issue directly related to this issue [here](https://github.com/dotnet/aspnetcore/issues/23895). I followed the source code you provided and was able to implement a customized AccountClaimsPrincipalFactory.

Everything is working as expected now. Thanks again for your help!
