### ISSUE TITLE
Onended Event Blazor didn't fire.

### ISSUE THREAD

**Issue by SvenMind2** [dotnet/aspnetcore#24323]
### Describe the bug
I'm currently working on a Playlist Video Website. Therefore I wanted to utilize the @onended event Tracker on my Video Element. But the event doesnt fire on the end of the Playback. I tried it with direct HTML Tag and it worked pretty fine.
To be clear, at the moment I only try to manipulate the source DOM. I didnt implemented the play after changing the source. I also tried it with other outputs like a Popup or Manipulating Text => same Result.

I call the same function "OnInitialized" and everything also works pretty fine.

### To Reproduce
Html
```HTML
<video autoplay="autoplay" @onended="NewVideo">
        @videoUrl
</video>
```
@code Block
```c#
 private void NewVideo()
    {
        videoUrl = new MarkupString($"<source src=\"videos/{tv.GetRandomVideoFileName()}\" type=\"video/mp4\">");

    }
```

### Further technical details
- ASP.NET Core version 3.1
- dotnet info:
``` 
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Visual Studio Community 16.6.5
- Standard Kestrel coming with creating a Blazor Project.

**Comment by JonathanFL** [comment]
This also seems to be happening for me in the following project:

Visual Studio 2019 Version 16.7.2
Blazor WebAssembly with PWA enabled

My alternative so far have been to hook up on the event from JavaScript in a someway bad way. I overwrote OnAfterRenderAsync and invoke a js script, when the DOM has been rendered.

`
private bool initialized_audio_onended_js_script = false;
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        
    }else{
        if(!initialized_audio_onended_js_script){
            await jsRuntime.InvokeVoidAsync("jsfunction.onended", "currently_playing_song");
            initialized_audio_onended_js_script = true;
        }
    }
}`

where "jsfunction.onended" is a function in a JS script file and the "currently_playing_song" is the ID of the audio tag.

The event "onfocus" do work in the .razor file, but other events i haven't received events on (haven't tried all).

**Comment by amartens181** [comment]
Is there a reason this isn't higher priority? The events are recommended in intellisense, indicating they are supported; if they are not, they would ideally be hidden so developers know the event is not supported. 
Do the events not work because the audio/video element events do not bubble?
