### ISSUE TITLE
When debugging in iis express  Open(cacheName) resolvse with null value, though cacheName matches

### ISSUE THREAD

**Issue by ATerentjev** [dotnet/aspnetcore#24321]
I apologize if the question is incorrect, perhaps someone will tell you where to ask the question more correctly. The problem
 occurs when working with CashStorage in iis express. I asked a question first here [https://github.com/w3c/ServiceWorker/issues/1524](https://github.com/w3c/ServiceWorker/issues/1524)  and was told that it might be a problem with the browser error tracker. The problem arises when the program is launched in iis express in VS 2019 (in Google Chrome there is no error), So:

The mapbox uses the following code
```

var sharedCache ;

function cacheOpen() {

if (window$1.caches && !sharedCache) {
    sharedCache = window$1.caches.open(CACHE_NAME);
}
function enforceCacheSizeLimit(limit ) {
cacheOpen();
if (!sharedCache) { return; }

sharedCache
    .then(function (cache) {
        if(!cache)   return;
        cache.keys().then(function (keys) {
            //debugger;
            for (var i = 0; i < keys.length - limit; i++) {
                cache.delete(keys[i]);
            }
        });
    });
}
```
I insert the line if (!cache) return; to fix my problem, but I would like to understand why this is happening. Here [https://w3c.github.io/ServiceWorker/#cachestorage](https://w3c.github.io/ServiceWorker/#cachestorage)  ` I read

>     If cacheName !matches key, then I expect that promise wil resolve with new Cache, not undefined.

Can anyone explain to me what I'm wrong about?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It seems that you're trying to report an issue related to the browser behavior, which you observe when debugging, correct?
Is that Microsoft Edge?

**Comment by ATerentjev** [comment]
I am using Google Chrome Версия 84.0.4147.89 (Официальная сборка), (64 бит)

**Comment by Pilchie** [comment]
@Tratcher or @vijayrkn - any ideas how to route this?

**Comment by Tratcher** [comment]
Reading through a few of the linked issues I see that this is a blazor project.

They made some progress on this thread:
https://bugs.chromium.org/p/chromium/issues/detail?id=1110313

**Comment by Pilchie** [comment]
Looks like this was a chromium issue.  The bug @Tratcher mentioned is now closed, and several people on the thread said things worked for them.  Closing as external.
