### ISSUE TITLE
Why user has to type his email on reset password page?

### ISSUE THREAD

**Issue by pawepaw** [dotnet/aspnetcore#24331]
I'm integrating forgot password mechanism into my system right now and I'm wondering why user has to type his e-mail together with password and password confirmation on reset password pages? Isn't token enough to find user in database?

I'm asking because it isn't popular to ask user for email (he clicked link to reset password moment ago from his mail box) and it's not perfect UX, does it has something to do with the security of the mechanism?

**Comment by blowdart** [comment]
It's just an extra hurdle to stop someone attempting mass password resets. It won't be changed.

**Comment by pawepaw** [comment]
ok, thanks for clarification.
