### ISSUE TITLE
.NET 5 and Blazor Server Application Combination is not working in IE11

### ISSUE THREAD

**Issue by jesusarockias** [dotnet/aspnetcore#24336]
.NET SDK - 5.0.100-preview.7.20366.6

Visual Studio - 16.7.0 Preview 5.0

We can reproduce it with default counter component by clicking it count value will not be updated.

Polyfill: https://github.com/Daddoon/Blazor.Polyfill

**Note**: it is working without any issue for .NET Core 3.1

**Comment by javiercn** [comment]
@jesusarockias thanks for contacting us.

Can you provide a call stack so that we might be able to help? (Server logs and/or Browser logs). Note that the polyfills you are using might need updates based on the 5.0 version of the JS code.

**Comment by jesusarockias** [comment]
Sorry. I am not able to open the development tool since IE browser stopped working. So, I have attached the sample here.
https://filebin.net/mea7n8of2vy465t0

**Comment by mkArtakMSFT** [comment]
Thanks for sharing your project.
There has been some changes in .NET 5 which will require for the community owned IE11 polyfills to be updated. We don't own these nor maintain. Feel free to file an issue with them.
