### ISSUE TITLE
Runtime dependency out of date

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24348]
Blocked on https://github.com/dotnet/aspnetcore/pull/24277 due to failing integration tests.

**Comment by TanayParikh** [comment]
Tried `dotnet test` with 5.0.100-rc.1.20377.3 from https://github.com/dotnet/installer however it doesn't have the requisite fix yet.

**Comment by dougbu** [comment]
@TanayParikh and @wtgodbe shouldn't this issue be closed now❔
