### ISSUE TITLE
Blazor server confusion with onclick

### ISSUE THREAD

**Issue by lxman** [dotnet/aspnetcore#24355]
Minimum repro here: https://github.com/lxman/TestCommunicate

So, in short, I am creating a list of SubComponent's on the index page. The first thing I am seeing is that whenever each SubComponent is initially created, the onclick seems to be firing. Is this normal? Or have I set something up incorrectly? The objective is to create a list of these things, then when I click on one of them, it disappears from the list, but I can't seem to get the signalling worked out.

One other odd thing I have seen as well. In attempting to figure this out, I moved my list initialization code from OnInitialized to OnAfterRender. When I do, I see that OnAfterRender is only called a single time with firstRender=true. I'm a bit confused by this as well. I'm still learning here, but I have experienced that OnInitialized, etc. are called twice during component setup with Blazor server. I assumed (but admittedly never actually tested) that since their is a firstRender bool it would be called once true and once false. If this isn't the case, what is the purpose of the bool?

C:\Users\michael>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@lxman thanks for contacting us.

> So, in short, I am creating a list of SubComponent's on the index page. The first thing I am seeing is that whenever each SubComponent is initially created, the onclick seems to be firing. Is this normal? Or have I set something up incorrectly? The objective is to create a list of these things, then when I click on one of them, it disappears from the list, but I can't seem to get the signalling worked out.

Do you have any evidence that the OnClick is being fired without you doing anything? (Do you see the component writeline statement in the log output?)

> One other odd thing I have seen as well. In attempting to figure this out, I moved my list initialization code from OnInitialized to OnAfterRender. When I do, I see that OnAfterRender is only called a single time with firstRender=true. I'm a bit confused by this as well. I'm still learning here, but I have experienced that OnInitialized, etc. are called twice during component setup with Blazor server. I assumed (but admittedly never actually tested) that since their is a firstRender bool it would be called once true and once false. If this isn't the case, what is the purpose of the bool?
> 
> C:\Users\michael>dotnet --info

The component renders twice because you are using prerendering, which renders the contents and discards the results after producing the initial static HTML and then renders the app again in interactive mode after it reconnects.
https://github.com/lxman/TestCommunicate/blob/master/TestCommunicate/Pages/_Host.cshtml#L20

**Comment by lxman** [comment]
Thank you for the thoughtful response.

The first issue I have resolved. After some research last night I learned about the difference between ```onclick``` and ```@onclick```. Then after that I learned about the ```key``` property. This has resolved my issues here.

The second question I am still curious about. I realize why ```OnInitialized``` and family fire twice due to prerendering. What confuses me is why ```OnAfterRender``` only fires once, with ```firstRender``` set to true. It seems a little non-intuitive to me the purpose of having the bool there when in effect you never see it in its false state AFAICT.

I won't hold this issue open for that, though, since it's more a matter of curiosity to me.

Thanks again.

**Comment by javiercn** [comment]
> What confuses me is why `OnAfterRender` only fires once, with `firstRender` set to true. It seems a little non-intuitive to me the purpose of having the bool there when in effect you never see it in its false state AFAICT.

OnAfterRender only fires after the browser acknowledges a render batch has been successfully applied. It doesn't fire during prerendering because Blazor "never truly finishes" the render loop within prerendering.

We don't run OnAfterRender during prerendering because that's the place we tell developers to put their JS interop code (which guarantees them that JS interop is available for them to use) and access to the browser is not available during prerendering.
