### ISSUE TITLE
Feature Request - Reusable razor component without polymorphism

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#24352]
### What problem are you trying to solve?
Here is a simplified version of what I am trying to solve.

I am working on a razor component that uses a `<select>` to choose the value of a property on a tracked entity.

I have a base `Dropdown` class and multiple classes that derive from it, e.g. `Color`, which is a property on the tracked entity.

To make the razor component generic enough, I pass in a `List<Dropdown>` created from a `List<Color>`.

After the `<select>` is changed, I want to assign the new choice to the `Color` on the tracked entity.

There is no way I can find to set the `Color` property directly - razor component doesn't know it's a `Color` and no way to create a `Color` object using its type and the values from the `List<Dropdown>` corresponding to `<select>` value.

Without polymorphism support, is there a way it can be accomplished, or is it a current limitation?

### Describe the solution you'd like
This is an idea:

```
// I'm using reflection in my code, but for this example, I'm leaving it out for simplicity
var createdColor = [create a new Color based on the chosen Dropdown and a passed in Type of Color];
trackedEntityColorProperty = createdColor;
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This seems to be the same as #7268. Can you please confirm whether we got this right?

**Comment by mrlife** [comment]
@mkArtakMSFT This case is different - it doesn't have a child component or templated component. I basically hoped for a way to pass in a type, e.g. `Color`, and be able to create a new instance of that with an instance of the type it derives from, i.e. `Dropdown`. I think `@typeparam` may only for displaying content in a templated component.

**Comment by mkArtakMSFT** [comment]
Thanks for additional details. It's not still clear then what you're looking for.
Maybe you can share with us a small sample assuming the feature you're looking for is available and point us to the exact usage of it?

**Comment by mrlife** [comment]
@mkArtakMSFT Thanks for your consideration. I will go with another approach for this and close this out.
