### ISSUE TITLE
The Module DLL C:\Program Files (x86)\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll failed to load. The data is the error.

### ISSUE THREAD

**Issue by HakamFostok** [dotnet/aspnetcore#24368]
### Describe the bug

Here is an excellent description of the error <br/> 100% percent exactly to what I faced: (https://stackoverflow.com/questions/54176640/the-module-aspnetcorev2-dll-failed-to-load) <br/>

I will copy the StackOverflow question here if you do not want to go there and read the question and its solution

<hr />
Recently I tried installing ASP.NET Core/.NET Core: Runtime & Hosting Bundle version 2.2 on a machine running Windows Server 2008 R2 SP1. However, after installing IIS stops working and gives 503 Service unavailable error for all applications hosted in it. After checking the application pools I see that the pools just shuts down.

In the event viewer I can see the following error message -

The Module DLL C:\Program Files (x86)\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll failed to load. The data is the error.

I have tried setting the pool to both 32/64 bits, but the error is the same. Did anybody else face this problem or have solution for this?

<hr />

Simply the problem is that `Microsoft Visual C++ 2015 Redistributable` does not exist on the server. <br/>
When I installed it, everything worked like charm.

**I spent 1 month to discover this problem, I just wanted to suggest the following : 
when installing ASP.NET CORE Hosting bundle 3.1.x why the not giving an error which says `Hosting bundle can not be downloaded because Microsoft Visual C++ 2015 Redistributable is not exists`
If I faced this imaginary error message when I was installing ASP.NET CORE Hosting Bundle, I would immediately install Microsoft Visual C++ 2015 Redistributable and I would save one month of efforts for me and for my become-angry client**

I really like Microsoft, I am working with its technologies from about 10 years, but because of some errors like these I am really going crazy, I started to consider to move to node.js even I am a loyal Microsoft client.

Please, I am suggesting one of two things:

1. Prevent ASP.NET CORE Hosting Bundle from installing if the Microsoft Visual C++ 2015 Redistributable dependency does not exist, Of course with a very very clear error message.

2. Install Microsoft Visual C++ 2015 Redistributable automatically (if not already exists) when Installing ASP.NET CORE Hosting Bundle (this would be much better)

**Here is another question on StackOverflow which describes the same problem**
https://stackoverflow.com/questions/54368738/failed-to-load-aspnetcorev2-dll-hosting-asp-net-core-2-2-on-iis7

**Comment by BrennanConroy** [comment]
> Recently I tried installing ASP.NET Core/.NET Core: Runtime & Hosting Bundle version 2.2

2.2 is out of support. Starting in 3.1 this should no longer be an issue as libc is statically linked now.

**Comment by HakamFostok** [comment]
I faced this problem with .NET Core 3.1.5 Hosting Bundle

Not with .NET Core 2.2

**Comment by HakamFostok** [comment]
I can reproduce the problem because of the it is realted to the machine not to the code
but here what you can use to reproduce the problem

1.  .NET Core Hosting Bundle 3.1.5
2. IIS 7.5
3. any machine without `Microsoft Visual C++ 2015 Redistributable`

Try it yourself, the problem does not solved with .NET Core 3.1 as you mentioned
