### ISSUE TITLE
Webassembly does not support crypto packages

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#24362]
I've started updating a large webassembly project from 3.2 to net5.0 (preview 7). The only stumbling block is that when we generate hashed tokens in the app we use System.Security.Cryptography.

When a function in this package is called an exception is raised:
`The type initializer for 'Crypto' threw an exception`

I'm assuming this package is not (yet) supported in the net5.0 wasm runtime. There are a couple of issues related to this:
* Where can one get a list of all supported packages?
* Is it not possible to do this check at compile time and emit a warning or error? 
* Are there any workarounds for this specific package?

**Comment by campersau** [comment]
You can follow https://github.com/dotnet/runtime/issues/39756 maybe some of your questions will be answered there.

**Comment by bfmsoft** [comment]
I am seeing this too.  This worked in 3.2 but ported to 5.0 and get this now.  I am looking for a work around.
