### ISSUE TITLE
Blazor NavLink Page Refresh Issue

### ISSUE THREAD

**Issue by xamlsharp** [dotnet/aspnetcore#24394]
### Subject
The Blazor WASM NavLink component refreshes the entire page when navigating to the default (root) page from a path-segmented page.

### Details
When navigating to a page with a directive that specifies a path segment (e.g. @page "/mypath/mpage") and then navigating back to the default route (e.g. @page "/"), Blazor performs a full application refresh. However, if navigating to other pages at the same base level, Blazor correctly loads pages without performing a full refresh.

In my estimation, all navigation within the same app should not perform a full refresh unless otherwise specified.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by xamlsharp** [comment]
Hi Artak,

It turns out that the reason why path segmented navigation wasn't working properly was because my "index.html" file did not contain "<base href="/" />" in the head tag. I'm closing this issue since the use of the base tag in Blazor is apparently a design decision.
