### ISSUE TITLE
StaticFileContext.SendAsync doesn't catch TaskCanceledException.

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2439]
_From @SergeySomkov on Saturday, November 11, 2017 3:05:57 AM_

After client aborts http request, StreamCopyOperation.CopyToAsync throws TaskCanceledException.
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendAsync>d__46.MoveNext()
```
The exception is not handled inside StaticFileContext.SendAsync. It is handled by Kestrel and it logs the following event:
- Connection id "{ConnectionId}": An unhandled exception was thrown by the application.
- LogLevel: Error
- Category: Microsoft.AspNetCore.Server.Kestrel
- EventId: 13

I'm wondering how is it even possible since StaticFileContext.SendAsync contains the following code:
```
try
{
  using (var readStream = _fileInfo.CreateReadStream())
  {
    // Larger StreamCopyBufferSize is required because in case of FileStream readStream isn't going to be buffering
    await StreamCopyOperation.CopyToAsync(readStream, _response.Body, _length, StreamCopyBufferSize, _context.RequestAborted);
  }
}
catch (OperationCanceledException ex)
{
  _logger.LogWriteCancelled(ex);
  // Don't throw this exception, it's most likely caused by the client disconnecting.
  // However, if it was cancelled for any other reason we need to prevent empty responses.
  _context.Abort();
}
```

_Copied from original issue: aspnet/StaticFiles#222_

**Comment by muratg** [comment]
@sergeysomkov Did you end up figuring out what was wrong?

**Comment by KhalilMohammad** [comment]
I am having same problem.Upload works sometimes

**Comment by muratg** [comment]
@KhalilMohammad How often does it break? Could you please share a simple app that reproduces this issue? A GitHub repo would be great!

**Comment by Tratcher** [comment]
Is it the same stack trace?

**Comment by KhalilMohammad** [comment]
Yes same stack trace,  I will share a git report soon

**Comment by Tratcher** [comment]
Can you share the log? StaticFileContext is expected to log the error but at a lower priority.

**Comment by JunTaoLuo** [comment]
Given we haven't heard back for a long time, I'm closing this. We can investigate if there are repros and logs provided.
