### ISSUE TITLE
Recommendation for integrating Blazor and WebForms application

### ISSUE THREAD

**Issue by jesusarockias** [dotnet/aspnetcore#24398]
I have a WebForms application and Blazor application. And, using IFrame the webform application is integrated into Blazor. 

Do you have any other best way for this?

**Note**: I aware that both are different applications but posted this query for just conformation whether I am moving in the correct direction.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.  There is no supported way for integrating Blazor into a WebForms application.
