### ISSUE TITLE
Blazor webassembly is not hitting Breakpint

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/aspnetcore#24403]
Hi,
I have converted a boot strap template into Blazor. But for some reason, the breakpoint is not getting hit during debugging in Vs 2019. Can you please provide some insights on the same https://github.com/VenkateshSrini/BlazorBootStartTheme. The issues is in the LearningContent.Razor in  this repo.

**Comment by captainsafia** [comment]
Hello @VenkateshSrini  -- can you share where you are trying to place the breakpoint?

**Comment by VenkateshSrini** [comment]
In the pages folder in the MyComp.KPortal.Client there is a page called LearningContent.Razor. In that I have a method called `protected override async Task OnInitializedAsync()`
In that I put the break point on second line

**Comment by captainsafia** [comment]
@VenkateshSrini There's a known issue with breakpoints inside `OnInitializedAsync`. You can check out https://github.com/dotnet/aspnetcore/issues/24411 for more info and a resolution.
