### ISSUE TITLE
Blazor/OnInitialized - Cannot hit breakpoint.

### ISSUE THREAD

**Issue by sroy2020** [dotnet/aspnetcore#24411]
Created as per request in [Unable to hit breakpoints for Blazor in VS or the browser](https://github.com/dotnet/aspnetcore/issues/24176).

==================================================================================

Hi,

We can't hit a breakpoint that is set inside of OnInitiliazed. We can hit a breakpoint in other lifecycle event methods like OnAfterRender (we added a dummy loop). We can hit a breakpoint in other non-lifecyle related methods. Most of our code is in the "razor.cs" but we also tried from ".razor" without success. **The funny thing is that it's working fine with the template (dotnet new blazorwasm -o BlazorApp --no-https).** It's almost like the communication between VS debugger and the browser (Chrome) is not fully in place by the time OnInitialized is called.

**It was working fine few weeks ago.**

VS: 16.6.5
ASP.Net Core: 3.2.1

Regards

**Comment by captainsafia** [comment]
@sroy2020 Thanks for opening this issue.

> It's almost like the communication between VS debugger and the browser (Chrome) is not fully in place by the time OnInitialized is called.

This assessment is correct. The DebugProxy takes some time to launch so breakpoints in `OnInitialized` lifecycle methods might not be hit. We recommend adding a wait/delay at the start of the method body to give the proxy some time to launch before setting the breakpoint.

@guardrex We've been getting a lot of questions about this so we should make a note in our docs about it.

**Comment by sroy2020** [comment]
Hi,

OK, we'll try. BTW, if I'm not mistaken we saw same the issue with other OnInitilaized even when the DebugProxy was ready (maybe I was day dreaming). Of course, we'll try again and keep you posted.

Thanks

**Comment by guardrex** [comment]
@sroy2020 I haven't tried using a compiler directive like that in a Razor component's code block (https://github.com/dotnet/AspNetCore.Docs/pull/19378/files). It should work, but let me know if you have trouble with it.
