### ISSUE TITLE
Include .SCSS as a first-class citizen (particularly in projects using the Razor editor)

### ISSUE THREAD

**Issue by craigajohnson** [dotnet/aspnetcore#24420]
(Original discussion as part of [https://github.com/dotnet/aspnetcore/issues/10170])

At the moment there are external preprocessing options for .SCSS files. This does work.

Ideally, there would be deep integration of .SCSS directly into the project, editing, and build experience.

Elements of this integration could include:

- Support for an scss/sass block in a .Razor file
- Compilation options for the .scss file within the project system
- Intellisense for .scss variables, functions, import paths, etc., within the .scss file itself
- Background compilation of the dependency tree for Intellisense within the .Razor view and to surface import errors early

Is this essentially an .scss language service?

**Comment by mkArtakMSFT** [comment]
Please note, that this will require some node-tooling support, which further complicates this feature.

**Comment by craigajohnson** [comment]
What is the dependency on node if the app is, say, solely a Blazor app with no npm dependencies?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
