### ISSUE TITLE
Unable to access localhost urls when debugging with Kestrel in VS Codespaces

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#24424]
Repro:

- Create a Blazor app and open it using codespaces
- Select Kestrel as the default server
![image](https://user-images.githubusercontent.com/1579269/88861862-bab50c80-d1b3-11ea-993c-766b1e17924d.png)
- Press F5
- Go to https://localhost:5001

Expected:
App loads successfully

Actual:
404

**Comment by khalidabuhakmeh** [comment]
Make sure you have the dev certs installed and updated to your latest SDK version.

**Comment by ajaybhargavb** [comment]
Looks like this is tracked in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1158246 and the fix has already been merged.
