### ISSUE TITLE
Add FAR Reference Code behind Filtering Codespaces

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24423]
Not working in codespaces https://github.com/dotnet/aspnetcore/issues/24073

fyi/ @ryanbrandenburg

**Comment by TanayParikh** [comment]
The [`RazorLSPConventions.IsRazorCSharpFile(referenceItem.Location.Uri)` check](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs#L173) is failing and consequently it bypasses all our remapping and filtering logic. 

The `referenceItem.Location.Uri` is `blazorserver/Pages/Counter.razor` instead of the generated C# file. It appears the results are already mapped for us. Is this a result of @dibarbet's changes?

cc/ @NTaylorMullen @ajaybhargavb

**Comment by ajaybhargavb** [comment]
> The referenceItem.Location.Uri is blazorserver/Pages/Counter.razor instead of the generated C# file. It appears the results are already mapped for us. Is this a result of @dibarbet's changes?

Yes. This is expected after @dibarbet's changes.
