### ISSUE TITLE
CodeLens in C# doesn't show if unmapped Razor line exists

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24425]
Repro:
1. Create new MVC Web Application
2. Open `ErrorViewModel`'
3. Try and expand the CodeLens:

Actual:
![image](https://user-images.githubusercontent.com/2008729/88861911-dfa97f80-d1b3-11ea-8691-b76ab152149b.png)

Expected:
only 3 entries that represent: 
![image](https://user-images.githubusercontent.com/2008729/88861929-e89a5100-d1b3-11ea-8c77-02b2db16c24b.png)

Note:
There's a great chance this is an external issue.

/cc @TanayParikh because of the FAR association.

**Comment by TanayParikh** [comment]
16.8-Preview1?

**Comment by NTaylorMullen** [comment]
> 16.8-Preview1?

Total mistake 😄

**Comment by NTaylorMullen** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/issues/24351
