### ISSUE TITLE
Razor mismatched namespace in generated code for assigned attribute values

### ISSUE THREAD

**Issue by koliyo** [dotnet/aspnetcore#24435]
### Describe the bug
The generated razor code does not resolve namespaces using `global::`, which gives conflicts in the generated code.

For example, I have a library, generated from Swagger, with the namespace `Onshape`

And I have eg `Onshape.Model.DocumentsGetWorkspacesResponse200Workspaces` class.

For my razor files I additionally have this structure: `Pages/Onshape`, which gives the namespace `AgxOnshape.Client.Pages.Onshape`.

In the razor files i am using `@using global::Onshape.Model`, which works fine in most circumstances.

However, it does not work when passing such a class instance as an attribute:
```
        <WorkspaceList Workspaces="@eWorkspacesResponse.Workspaces"/>
```

because this generates
```cs
                    __builder3.AddAttribute(70, "Workspaces", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Collections.Generic.IEnumerable<Onshape.Model.DocumentsGetWorkspacesResponse200Workspaces>>(
```

This would be resolved if the generator prepended `global::` to the resolved types!

Note, the namespace resolution works if I don't use the type as an attribute value, but only locally in a razor component.

Related to #12116

### To Reproduce
See above example

### Further technical details
```
Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We plan to address this as part of #18757
