### ISSUE TITLE
Large blazor webassembly publish size increase from 3.2 to net5.0

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#24433]
When porting an existing webassembly application from 3.2 to net5.0 (preview 7) the published size increased from about 7MB to 22MB.

Whilst the 7MB is on the large side, it is still just about managable (it is a LOB app), but with > 20MB it is problematic.

* Is this to be expected for the current version of net5.0?
* Is the intention to reduce the webassembly deployment size before the release of 5.0?

**Comment by javiercn** [comment]
@tn-5 thanks for contacting us.

From what I can infer you are not using linking during the publish step. In 3.2 we used to trim unused assemblies even if we didn't link the application. In 5.0 we've moved to use the linker that ships with the SDK and we haven't implemented that functionality since we expect people to link their apps during publish to minimize the application size.

@pranavkm is there anything here you want to add?

**Comment by danroth27** [comment]
Hi @tn-5. A default Blazor WebAssembly app when published should only be ~2MB of total transfer size when linked and compressed. You can reduce the size even further to ~1.6MB if you remove a bunch of the optional stuff added by the template (Bootstrap, timezone data, etc.). It sounds like your published app may not be linked. Can you confirm whether you have disabled the linker in your project file?

For .NET 5 we now provide a much larger API surface area and we rely even more heavily on the linker to reduce the size of the app. During development, this can mean the app looks larger, but when published, linked, and compressed the total transfer size of the app should still be only ~2MB. By the time we ship .NET 5 our goal is that that the transfer size of a default Blazor WebAssembly app should be no bigger than what it was with Blazor WebAssembly 3.2.

**Comment by tn-5** [comment]
Are there any specific guidelines on enabling linking, specifically is it possible to force linking in a debug environment?

We do not use the standard configurations (such as "Release") in our project, so it is unclear how to configure a specific configuration to use linking. We do have the following in the project file:
`<BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>`
but it does not seem to make a difference in the published size.

**Comment by pranavkm** [comment]
Blazor uses the .NET SDK's trimmer and can be configured by using it's options. https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained goes over some of these options. That said trimming should be enabled by default, you have to opt out.

The published output for a Blazor app has 3 copies of most items, the file as-is as well as gziped and brotli compressed files. However, you only ever serve one set of these files. If you happened to use the folder size, your estimates might be a bit skewed. Using the network transfer size in the browser should get you what the app size as seen by users. 

If you the browser download sizes are at closer to 20MB number, I'd love to dig more in to it. If you could get me binary logs from your publishing your application that would help. To get the bin logs, 
* run `dotnet publish /bl`
* Attach the `msbuild.binlog` file created in the working directory.

**Comment by tn-5** [comment]
I've managed to do some testing with different publish configurations and can verify that although the app size is larger on net5.0 than 3.2 it seems correct when used with the `Trim unused assemblies` option selected.
For the project template as is published the download from the server is just less than 3Mb, for the net5.0 version it is about 5.5Mb.

**Comment by danroth27** [comment]
@tn-5 That still seems larger than it should be. Is response compression enabled on the server?
