### ISSUE TITLE
Web API wont run immediately on IIS after Idling

### ISSUE THREAD

**Issue by LokiMutua** [dotnet/aspnetcore#24436]
# Issue Title

.NET Core Web API not working immediately after idling for while.

# General
Did a .NET Core Web API and hosted on IIS. Apparently when the API stays long without hits, when you try it throws 500 error. After trying several times it works. I have set the application pool to always run but still its not helping. Any suggestions to fixing above.
Am running .NET Core v3.1.302

**Comment by Tratcher** [comment]
There should be an error logged to go with that 500. Check the event viewer and all logs.
