### ISSUE TITLE
Wasm with Identity server doesn't work with IIS

### ISSUE THREAD

**Issue by hanhmyle** [dotnet/aspnetcore#24437]
Hi,
I'm hoping to get an answer. I've been trying to deploy blazor webassembly with IdentityServer (Individual user account) on asp.net core hosted but I have no success so far. 
Here are the steps.
1. Create blazor webasembly app
2. Choose Individual User account
3. Check on asp.net core hosted and progressive web app.
4. Run update-database
5. Create Self-Signed SSL Certificate for IIS
6. On appsettings, set identiyserver key:
"IdentityServer": {
    "Key": {
        "Type": "File",
        "FilePath": "ssl2020.pfx",
        "Password": "ssl2020"    
		}
    }
7. Publish the project to IIS

Everything works on localhost. When it goes to IIS, i can see account manage page. Create an account or login will fail.
Can someone please help? I've developed the app and now I can't deploy.
Thank you so much!

**Comment by Tratcher** [comment]
Any error logs? I suspect the self signed certificate is giving you trouble. What if you Import that as a trusted cert in the cert store?

**Comment by hanhmyle** [comment]
Yes, this is the error
Failed to load resource: the server responded with a status of 500 ()
https://localhost/Identity/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DBlazorAppHanh.Client%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%252Fauthentication%252Flogin-callback%26response_type%3Dcode%26scope%3DBlazorAppHanh.ServerAPI%2520openid%2520profile%26state%3D1bb38cd1b130403aa299253b4e839430%26code_challenge%3DQYlkvEbL6SA605JfNP1fOulPTP6rhTpTypI8C4TRy3c%26code_challenge_method%3DS256%26response_mode%3Dquery

Can you give me tips how to import the cert to cert store? It's new to me.
Thank you!

**Comment by javiercn** [comment]
@Tratcher I'm almost 100% sure it's not the self-signed certificate. If the error happens during register/login, it's likely that the database is not correctly set up.

**Comment by hanhmyle** [comment]
@javiercn it works locally. It only happens when I published to IIS (same database, same credentials)

**Comment by Tratcher** [comment]
You'll want to get the detailed error from the server logs.

**Comment by javiercn** [comment]
@hanhmyle thanks for contacting us.

Did you make sure the database is created and that you ran the appropriate migrations? From what I understand your issue is within Account/Login, Account/Register and the failure is happening at that point? Meaning, are you able to render the Login/Register pages successfully and then the error happens afterwards?

As @Tratcher mentions you want the detailed error logs, you can get those by adding "detailedErrors": true to your appsettings or setting `ASPNETCORE_DETAILEDERRORS=true` as an environment variable.

**Comment by hanhmyle** [comment]
@javiercn thank you so much for your instruction. turned the detailerror flag on and found the problem. It was my sql server refused remote connection. I fixed it and now I am able to deploy. 
Thanks again.

**Comment by javiercn** [comment]
Closing since the issue has been resolved.
