### ISSUE TITLE
Wasm on IIS doesn't have option to install the app

### ISSUE THREAD

**Issue by hanhmyle** [dotnet/aspnetcore#24447]
Hi,
I'm struggling to deploy wasm application on IIS.
Steps to produce:
Create blazor webasembly app
Check on asp.net core hosted and progressive web app.
Publish the project to IIS
On IIS server, i setup the app in port 85. So it will be http://www.myapp.com:85
I also setup https port 443.
After the deployment, the app is running fine. Just that I can't see the option to install the app.
I tried: 
http://www.myapp.com:85
https://www.myapp.com
but neither gives me an option.
Please shed me a light.
Thank you!
![image](https://user-images.githubusercontent.com/43523575/88961929-8e080000-d25a-11ea-8ff6-9b8939e2b371.png)

**Comment by javiercn** [comment]
@hanhmyle thanks for contacting us.

Did you make sure that the service worker is referenced on the index.html and that the file is downloaded into the browser? Are there any errors in the browser console?

**Comment by hanhmyle** [comment]
Yes, the error is from service worker just as you said.
(index):1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://devcareweb01/') with script ('https://devcareweb01/service-worker.js'): An SSL certificate error occurred when fetching the script.

I am not sure if I set it up right. I have a dev server ServerA hosting multiple websites so I assign mine as http://ServerA.com:86
Then I setup https for this website with self-signed ssl.
![image](https://user-images.githubusercontent.com/43523575/89038397-20f57880-d2f5-11ea-908e-863f4525f7d6.png)
Then when I access https://ServerA.com, I got the service worker problem.
Do you think I didn't do right on the website setup? Note, it works properly on localhost and I can see the plus sign to install the app.
Thank you!

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
