### ISSUE TITLE
Abstractions for Microsoft.AspNetCore.Mvc.RazorPages

### ISSUE THREAD

**Issue by a-ctor** [dotnet/aspnetcore#24444]
As far as I tell there are no abstractions available for `Microsoft.AspNetCore.Mvc.RazorPages`. It would be nice to have an abstractions project instead of having to reference the full package.

In my case, I am trying to implement a custom filter. Since razor pages cannot use the `IActionFilter`/`IAsyncActionFilter` I additionally need to implement `IPageFilter`/`IAsyncPageFilter`. Those types do not exist in the MVC NuGet package so an explicit reference to `Microsoft.AspNetCore.Mvc.RazorPages` is needed. As I am writing those components as part of a framework I do not want to pull in the whole Razor Page package since that will end up as a dependency for all customers regardless of them using razor pages.

My current workaround has all the types that depend on RazorPages in their own project with an explicit dependency on RazorPages. But this is not optimal since I have to duplicate filter attributes (one for the action filter and one for the page filter) and customers have an additional dependency to include. So instead it would be great to have a NuGet package that provides the abstractions for the razor pages.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. RazorPages does not ship as a separate package and it is referenced through framework reference. Given this, there is no point in having a separate abstraction package.
