### ISSUE TITLE
How do I pass parameters such as System.string [] to the Blazor (WASM) application

### ISSUE THREAD

**Issue by Nuan-Yang** [dotnet/aspnetcore#24461]
Hi engineer: I have a question about Blazor (WASM) for you to ask.
I am a blazor fan in China, and My English is not very good,forgive me.
The following is the translation:
How do I pass the string[] argument to my Main function in my Blazor (wasm) using dotnet.3.2.js and Blazor.webassembly. Js.
I passed in a ["#app"] But the console indicated that I could not convert to the system.string[] type.

Here is the incoming parameter function I implemented by modifying Blazor. Webassembly. Js

 callEntryPoint: function(e) {		
            h("Microsoft.AspNetCore.Components.WebAssembly", 
        "Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker", "InvokeEntrypoint")(e,["#app"])
        },
and call callEntryPoint("BlazorApp1")
I hope you can help me with my questions. Thank you

**Comment by Nuan-Yang** [comment]
I want to pass an array variable into Blazor.webassembly. Js by calling the js function and passing it into my app's main function

**Comment by Nuan-Yang** [comment]
app code:   
public static async Task Main(string[] args)
{
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>(args[0]);
            builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            await builder.Build().RunAsync();
 }

**Comment by SteveSandersonMS** [comment]
This is a totally valid question, but unfortunately we don't currently supply a method for passing parameters to the entrypoint. The startup logic [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L68) is hardcoded to supply no parameters. We can certainly look at adding support for passing through parameters in the future.

In the meantime, as an alternative you could add whatever data you want to supply as a global JS object, e.g.,

```html
<!-- Put this script block above the one that loads blazor.webassembly.js -->
<script>
    window.getStartupParams = function() { return ['first', 'second', 'third']; };
</script>
```

... and then in your .NET code in `Main`, read it back by making a JS interop call:

```cs
public static async Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    var js = (IJSInProcessRuntime)builder.Services.BuildServiceProvider().GetRequiredService<IJSRuntime>();
    var myParams = js.Invoke<string[]>("getStartupParams");

    // ... etc ...
}
```

**Comment by Nuan-Yang** [comment]
> This is a totally valid question, but unfortunately we don't currently supply a method for passing parameters to the entrypoint. The startup logic [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L68) is hardcoded to supply no parameters. We can certainly look at adding support for passing through parameters in the future.
> 
> In the meantime, as an alternative you could add whatever data you want to supply as a global JS object, e.g.,
> 
> ```
> 
> <script>
>     window.getStartupParams = function() { return ['first', 'second', 'third']; };
> </script>
> ```
> 
> ... and then in your .NET code in `Main`, read it back by making a JS interop call:
> 
> ```cs
> public static async Task Main(string[] args)
> {
>     var builder = WebAssemblyHostBuilder.CreateDefault(args);
>     var js = (IJSInProcessRuntime)builder.Services.BuildServiceProvider().GetRequiredService<IJSRuntime>();
>     var myParams = js.Invoke<string[]>("getStartupParams");
> 
>     // ... etc ...
> }
> ```

Thanks bro, it's working.
and Can you help me with one of my other problems?
How can I run multiple Blazor (WASM) apps on one page?
When I open a Demo app (Blazor app), I cannot open the same app or open another demo app,in a web page.
As far as I know, the reason for the problem is related to the fact that dotnet.js does not have exit function in web mode, but the specific reason is not well understood. If you know the relevant reason, I hope you can help me.
Here is one of my test sites at http://www.nuanyang.club.
The password for account test is 123456.
Now I can only use the following code to open the same application multiple times or run multiple applications simultaneously, but I can't do anything about multiple applications.
code:

>if (firstRun) {
>            //setting start app dll and runtime url
>             bootAppBaseUrl = option.baseAppUrl.toString();
>              //This sentence you can think of as starting to run Blazor. Webassembly. Js
>               dotnetRuntime(bootOption);
>               //firstRun = false;
>           }
>          else {
>                var r = "[Microsoft.AspNetCore.Components.WebAssembly] " + "Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker" + ":" + "InvokeEntrypoint";
>              BINDING.bind_static_method(r)("BlazorApp1", null);
>            }

thanks for your help.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We do not debug customer applications. For these types of issues `StackOverflow` may be a better place to ask.
