### ISSUE TITLE
FieldIdentifier accessor changed from protected to protected internal

### ISSUE THREAD

**Issue by MariovanZeist** [dotnet/aspnetcore#24463]
Hi Team,

Recently the accessor for the FieldIdentifier property in the InputBase<TValue> class was changed from protected to protected internal. This prohibits the use of this property in descendant classes.

### Is your feature request related to a problem? Please describe.
I have created a component library with specialized InputBase descendants. In which FieldIdentifier is used for displaying error messages, and also to notify the EditContext that a field has changed. 
Now that this field isn't (easily) accessible anymore. I would have to either use FieldIdentifier.Create (Which seems like a waste, as expression parsing doesn't come cheap) or hack my way around it using reflection. neither option seems great.

### Describe the solution you'd like
Make the accessor protected again, instead of protected internal

**Comment by SteveSandersonMS** [comment]
Apologies - I suspect this was unintentional. We'll discuss and probably find a way of putting it back, assuming I'm not missing some essential reason why we wanted a breaking change here. It's very unlikely that we did want to have a breaking change here.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not clear what is the exact issue you're facing. `protected internal` is more accessible than just `protected`.

**Comment by MariovanZeist** [comment]
Ahum. You are totally correct of course. This isn't an issue at all.
