### ISSUE TITLE
Migrate Razor's Remote OOP support to be .NET Core service hub compatible

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24476]
Roslyn is making the move to .NET Core service hub's meaning we'll need to also make that transition.
Example PR of this transition in Roslyn: https://github.com/dotnet/roslyn/pull/46026
![image](https://user-images.githubusercontent.com/2008729/89059987-092eec00-d317-11ea-8099-20575cfcf34a.png)

**Comment by NTaylorMullen** [comment]
@genlu @tmat Will this be ready for us to migrate to in 16.8-Preview3 or 16.8-Preview4?

**Comment by tmat** [comment]
Can you target netstandard2.0? If so, you can switch immediately, no need to wait for Roslyn.

**Comment by NTaylorMullen** [comment]
> Can you target netstandard2.0? If so, you can switch immediately, no need to wait for Roslyn. Then the only remaining thing would be the json file.

I believe we could target netstandard2.0 but I'm wondering if that adds any value on its own. Or could we also add the json file and it just be ignored until you all are ready to enable it?

**Comment by tmat** [comment]
It definitely adds value. At last we will know it works on Core (and all dependencies). You can add the json file as well i guess. That's just a small detail though.

**Comment by genlu** [comment]
@tmat so for OOP components targeting netstandard2.0, do they still need separate folders for desktop and core (to avoid picking up dependencies deployed for core being picked up when running on desktop servicehub)?

**Comment by tmat** [comment]
We would not be running our ServiceHub process on Desktop and won't provide an option to do so. Instead, the fallback would be an option to move Roslyn completely in-proc. So I don't think Desktop loader would have any problem.

IDK how the ServiceHub .NET Core loader is configured to answer the question of whether it can/should load assemblies from the same directory as the loader in VS process does.

**Comment by NTaylorMullen** [comment]
Moving to Preview4 to not forget about this but ultimately this will get done in 16.9 when Roslyn lands the support

**Comment by NTaylorMullen** [comment]
As part of this we should also include the serverGC bits needed. Example PR: https://devdiv.visualstudio.com/DevDiv/_git/VSUnitTesting/pullrequest/286926?_a=files

**Comment by NTaylorMullen** [comment]
Associated OOM VSTS issues:
- https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1258678

**Comment by genlu** [comment]
@NTaylorMullen We have finally got Roslyn targeting netstandard2.0 properly, you should be unblocked now :)
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.CodeAnalysis.Remote.ServiceHub&protocolType=NuGet&version=3.9.0-4.21064.28&view=overview

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen We have finally got Roslyn targeting netstandard2.0 properly, you should be unblocked now :)

Nice! We recently started compiling our bits for netstandard2.0 out of the box so I assume all we need to do is add a serviceHub.json file then right?

Also, what timeframe should I aim to get Razor changes in for?

**Comment by genlu** [comment]
> what timeframe should I aim to get Razor changes in for

Don't have a concrete timeline yet, still under discussion. So there's no hurry in terms of adding the new servicehub json. That said, it'd be great if you can try the new package w/o suppressing those warnings and see if everything works.

**Comment by NTaylorMullen** [comment]
> Don't have a concrete timeline yet, still under discussion. So there's no hurry in terms of adding the new servicehub json. That said, it'd be great if you can try the new package w/o suppressing those warnings and see if everything works.

Is there a tracking issue that we can follow?

**Comment by genlu** [comment]
I think NU1701 in [this proj ](https://github.com/dotnet/aspnetcore-tooling/blob/9caaa2c62a93b4421d0247c8e95df79e83c2faaa/src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj#L18)is caused by referencing Roslyn?

**Comment by NTaylorMullen** [comment]
> I think NU1701 in [this proj ](https://github.com/dotnet/aspnetcore-tooling/blob/9caaa2c62a93b4421d0247c8e95df79e83c2faaa/src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj#L18)is caused by referencing Roslyn?

Ah ok ya

**Comment by NTaylorMullen** [comment]
Marking as blocked until pre-requisites from Roslyn front are completed.
