### ISSUE TITLE
Blazor password features doesn't fully work in latest template

### ISSUE THREAD

**Issue by jvallejoa** [dotnet/aspnetcore#24474]
Hello,
Here the bug:
Blazor latest update doesnt display eye/eye-slash to **show/hide** password when user types at login/register razor pages.
Web Browser: **Google Chrome**
<img width="687" alt="ErrorBlazor" src="https://user-images.githubusercontent.com/8346875/89048894-0e3f6b80-d316-11ea-9a36-b0e7023ac89b.png">

Thanks in advance,
Juan

**Comment by blowdart** [comment]
What version of .NET Core are you using? Latest doesn't really give us enough to go on.
