### ISSUE TITLE
Add computed Razor syntactic colorization

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24483]
This would make it so our language server decorated more then just components with semantic information. This would enable us to simplify our TextMate grammar for syntactic colorization and ultimately have a more accurate Razor colorization scheme in LSP scenarios.

Things that aren't colored today that we should consider coloring in our semantic endpoint:
- HTML elements
- HTML attributes
- Razor metacode
- Razor directives

Ultimately this would enable us to have a better colorization of embedded HTML (inside of C# blocks) for things that typically fail today because of how difficult it is to represent every various scenario in which HTML can exist.

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen what metacode is there besides `@` and the `functions` of `@functions`?

**Comment by ryanbrandenburg** [comment]
What about razor comments?
