### ISSUE TITLE
Url.Action doesn't include action name when there are more parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24480]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1121898/urlaction-doesnt-include-action-name-when-there-ar.html)._

---
Hi, this is simple one.
I have default route defined like this:

```
app. UseEndpoints(endpoints =>
{
	endpoints. MapDefaultControllerRoute();
	endpoints. MapControllers();
});
```

Now, I call:
`Url.Action("GroupCategoryView", new { id = "(sheetGroupId)", categoryId = "(categoryId)"})`

I was expecting address like:
`/Document/GroupCategoryView/(sheetGroupId)?categoryId=(categoryId)`
(Document is my controller name), but instead it gives:

`/(sheetGroupId)?categoryId=(categoryId)`

---
#### Feedback Bot on 7/23/2020, 03:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/23/2020, 10:58 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### ajachocki on 7/24/2020, 01:55 AM: 

<p>After I removed HttpGet attribute from controller method it started working. So maybe this was my mistake. And one should not use those attributes on not api controllers.</p>

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment]
> After I removed HttpGet attribute from controller method it started working. So maybe this was my mistake. And one should not use those attributes on not api controllers.

It sounds like there's more going on here than what's provided in the original comment. We would probably need a repro project to continue investigating this further.
