### ISSUE TITLE
Headers configuration file

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2448]
_From @sebastienros on Tuesday, April 25, 2017 6:09:52 PM_

Like it was done in System.Web I'd like to be able to set default headers like `max-age` per folder.
The first thing I want to do when serving static file is define this header.

An implementation could look for a specific file in the folder the file is served, using the same `FileProvider` as the options. This can already be done using code by altering the `Response` but configuration is better in this case IMO.

_Copied from original issue: aspnet/StaticFiles#188_

**Comment by davidfowl** [comment]
@sebastienros how strongly do you feel about this one?

**Comment by sebastienros** [comment]
I think it's more about configuration options. Having a file per folder is a nice convention, but for a framework at least being able to set it by configuration would be the minimum. Look at web.config and what we could achieve without resorting to building and deploying an app. Super useful. Same for mime-type mappings for instance.

If that was the responsibility of a middleware this could be done on more than just static files. But if it needs to be configured differently for some folders, or patterns (common enough I assume) then it would have to be baked in the static file one.

However there not even a thumbs up on this one, maybe nobody cares?

**Comment by davidfowl** [comment]
Right m. It doesn't match the style of what we've built with ASP.NET. We've added configuration where people have asked or where we thought it made sense (like kestrel). Static files hasn't come up much, so I'm gonna close this.
