### ISSUE TITLE
Update jQuery dependency to the latest version

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#24490]

**Comment by mkArtakMSFT** [comment]
@HaoK can you please handle this for identity, scaffolding and the templates? Thanks!

**Comment by HaoK** [comment]
Sure, just to confirm 3.5.1 is latest jquery this is talking about right?

**Comment by mkArtakMSFT** [comment]
Yes, to the latest please.

**Comment by HaoK** [comment]
This work was already done as far as I can tell

https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/wwwroot/lib/jquery (3.5.1)

https://github.com/dotnet/aspnetcore/tree/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/wwwroot/lib/jquery (3.5.1)

https://github.com/dotnet/aspnetcore/tree/master/src/Identity/UI/src/wwwroot/V4/lib/jquery (3.5.1)

https://github.com/dotnet/Scaffolding/tree/master/src/VS.Web.CG.Mvc/Templates/Identity/Bootstrap4/wwwroot/lib/jquery (3.5.1)
