### ISSUE TITLE
Native Print functionality in Blazor Weassembly

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#24504]
I am looking for No-Prompt Print functionally, which will be initiated by user.
I am creating app for Kiosk, and want some thing to be printed on click of button without any prompts to the printer.
I should be able to print to label printer or any other printer.

**Comment by pranavKVP** [comment]
@nssidhu until you find better solution, this can be useful.
Using Firefox, open about:config page
Click "Accept the Risk and Continue"
Type "print.always_print_silent" in Search preference name
Set value to true by clicking on switch button.
Get more info here. https://support.mozilla.org/en-US/kb/firefox-enterprise-kiosk-mode

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is indeed a browser-specific functionality.
You will need to find your-browser specific options similar to what @pranavKVP suggested for Firefox.
