### ISSUE TITLE
Remove connection-specific headers for HTTP/2 and HTTP/3

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#24502]
[Spec](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-field-formatting-and-compre) for HTTP/2 and HTTP/3 states that connection-specific headers should be removed.

> Such intermediaries SHOULD also remove other connection-specific fields, such as Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade, even if they are not nominated by the Connection field.

I want to create a PR for this issue. Is there any special way to add methods for clearing headers in `HttpHeaders.Generated.cs` since it's generated? 
https://github.com/dotnet/aspnetcore/pull/24315/files/fb66a4e496ba49e3976731ad91be84fbafc9c936#diff-af588a349fd0f3044d4e05739c9c4293R8010-R8015

/cc @Tratcher

**Comment by Tratcher** [comment]
The source for that generated file is called KnownHeaders. You edit it like this:
https://github.com/dotnet/aspnetcore/pull/24315/files/fb66a4e496ba49e3976731ad91be84fbafc9c936#diff-9d6067e45fb1196b82da0a0e7c96040e
Then you run the CodeGenerator project. I usually just CTL+F5 to run it in VS, but you should be able to `dotnet run` it as well.
https://github.com/Kahbazi/AspNetCore/tree/fb66a4e496ba49e3976731ad91be84fbafc9c936/src/Servers/Kestrel/tools/CodeGenerator
