### ISSUE TITLE
[Blazor WASM] Breakpoints don't work in Brave

### ISSUE THREAD

**Issue by ivan-prodanov** [dotnet/aspnetcore#24506]
My issue is similar to [[Blazor WASM] Breakpoints not being hit in Visual Studio](https://github.com/dotnet/aspnetcore/issues/22179)

I was struggling to find out why breakpoints don't work at all even though I'm using the latest VS (16.6.5).

Turns out my default browser was Brave (based on Chrome). It works in Chrome, but is there any particular reason it doesn't work in Brave?

**Comment by pranavKVP** [comment]
It's happening because of Visual Studio fails to launch debug adapter.
I don't think it's a browser specific problem.
you might get error message in dialog sometimes and look for Output window for more details.
Happening with me as well with same VS version and project type.

**Comment by captainsafia** [comment]
@ivan-prodanov Are you able to debug inside Brave when using our browser debugging experience which is documented [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#debug-in-the-browser)?
