### ISSUE TITLE
How to access to database in worker service when published as windows service?

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/aspnetcore#24511]
I've created worker service on .net core 3.1. I published it to folder and using powershell registered new windows service.When I start service it should connect to database and get records from db.It throws Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "exmapleDB" requested by the login. The login failed. Login failed for user 'NT AUTHORITY\SYSTEM'. Any suggestions?

**Comment by blowdart** [comment]
Run the server under credentials that have access to the database, or let system have database access. [Windows has some recommendations](https://docs.microsoft.com/en-us/windows/win32/ad/service-logon-accounts), this isn't something a framework addresses.
