### ISSUE TITLE
Return JsonResult() but ContentType is   "text/plain; charset=utf-8"

### ISSUE THREAD

**Issue by clpgit** [dotnet/aspnetcore#24515]
Return JsonResult() but ContentType is   "text/plain; charset=utf-8"

**Comment by alexyarosh98** [comment]
Seems like it's not a default behavior and you should check custom middlewares. Additionally, you can try to set ContentType property in JsonResult object equals to "application/json".
`
return new JsonResult(/*your object*/) { ContentType = "application/json" };
`

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
