### ISSUE TITLE
IFormFile and FormFile conflict

### ISSUE THREAD

**Issue by csalgo70** [dotnet/aspnetcore#24517]
### Describe the bug

I have an Azure Function which is http triggered and iterates over the POST files to process them. As long as I use IFormFile it seems to work but if I try to convert it as FormFile I keep getting an error that it cannot convert from IFormFile to FormFile.

If I look in the debugger it does show IFormFile as Microsoft.AspNetCore.Http.FormFile and the documentation seems to mention that as available https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.formfile?view=aspnetcore-3.1 

If I try to cast, It shows me "The type or namespace name 'FormFile' does not exist in the namespace '**Microsoft.AspNetCore.Http**". This seems correct as it only exists in **Microsoft.AspNetCore.Http.Internal**

There seems be a conflict between different versions of IFormFile. 

One in Microsoft.AspNetCore.Http.IFormFile from Microsoft.AspNetCore.Http.Features ( 2.1.0.0 ) and FormFile in **Microsoft.AspNetCore.Http.Internal** derives from IFormFile ( though not sure which one )

### To Reproduce

Create a simple Azure Function (Function Runtime Version: 3.0.13901.0).

 public async Task<IActionResult> UploadFilesAsync(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "files")]
            HttpRequest req,
            ILogger log)
{
....
var inputFiles = req.Form.Files;
  foreach (var inputFile in inputFiles)
            {
                var f = inputFile as Microsoft.AspNetCore.Http.Internal.FormFile; // issue here.
                
}

### Exceptions (if any)

You would get runtime exception 

System.Private.CoreLib: Exception while executing function: UploadPhotos. FileMicroService: Could not load type 'Microsoft.AspNetCore.Http.Internal.FormFile' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### Why do I want to convert ?

I want to make this a durable azure function with upload single file being Activity and I ran into serialization issues passing just the interface and hence all this.

### Installed nuget pkgs

![image](https://user-images.githubusercontent.com/2498081/89130107-2ac6d980-d4b7-11ea-9c4b-a8689bbc85c9.png)

### Further technical details
- ASP.NET Core version 

  dotnet --version 
    3.1.301

- Include the output of `dotnet --info`
  dotnet --info                                                                                                      
    .NET Core SDK (reflecting any global.json):
    Version:   3.1.301
    Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Tratcher** [comment]
That type was moved from Http.Internal.FormFile to Http.FormFile in 3.0.
https://github.com/dotnet/aspnetcore/pull/11429/files#diff-5950fbb0a19cf2b66b89cc405e4f9867

It looks like you're trying to use 2.x dependencies on the 3.1 runtime.

**Comment by csalgo70** [comment]
But as you can see from my packages I didn't include any of these versions myself. They are the implicit dependencies from just creating the Azure function. Let me try creating another new azure function just to make sure that is the issue.

**Comment by csalgo70** [comment]
The issue still persists 

### Repro steps

1. I upgraded my .net core to 3.1.0

2. Create new Azure function sample with simple http trigger.

3. Replace the code with this 

```csharp
[FunctionName("HttpExample")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]
            HttpRequest req,
            ILogger log)
        {
            var formData = await req.ReadFormAsync();
        
            var inputFiles = req.Form.Files;

            if (inputFiles == null)
            {
                return new BadRequestObjectResult(new string("Missing Files to upload"));
            }

            var folder = formData["folder"].ToString();

            if (string.IsNullOrWhiteSpace(folder))
            {
                return new BadRequestObjectResult(new string("Missing folder field"));
            }

            foreach (var inputFile in inputFiles)
            {
                var f = inputFile as FormFile;
            }
                
            return new OkResult();
        }
```

You can see that the **FormFile** still shows up under **Microsoft.AspNetCore.Http.Internal**

![image](https://user-images.githubusercontent.com/2498081/89136794-4dbeb100-d4ea-11ea-8fdd-ff709af13b47.png)

### Run time excepton is thrown.

[8/3/2020 12:59:54 AM] Executed 'HttpExample' (Failed, Id=a68f691d-2e50-4867-b056-371aa4fa96ad)
[8/3/2020 12:59:54 AM] System.Private.CoreLib: Exception while executing function: HttpExample. HttpFuncExample: Could not load type 'Microsoft.AspNetCore.Http.Internal.FormFile' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by csalgo70** [comment]
It looks like it uses Microsoft.AspNetCore.Http 2.2.2 which seems like the latest version.

**Comment by davidfowl** [comment]
There's are 2 issues you're running into:
- Types that were previously in the internal namespace are now either actually internal or moved elsewhere.
- The code shouldn't be casting to form file. I'm assuming that's for illustration because it's broken to assume you can cast to a specific implementation when the public API is typed as the interface.

I'm not exactly sure that there's anything to do here.

**Comment by csalgo70** [comment]
I haven't added anything extra. Its just a new azure func code. Shouldn't it work out of the box. I still see the FormFile in Microsoft.AspNetCore.Http.Internal and public. I do need to cast because there is another serilization issue with passing IFormFile to an Activity where it needs a concrete implementation.

namespace Microsoft.AspNetCore.Http.Internal
{
    public class FormFile : IFormFile
    {

**Comment by davidfowl** [comment]
@csalgo70 it should work out of the box. I'd recommend filing an issue here https://github.com/Azure/azure-functions-host/issues

**Comment by csalgo70** [comment]
Thanks @davidfowl I have created the issue there and closing it here.
