### ISSUE TITLE
Suspect setting Thread.CurrentThread.CurrentUICulture in middleware will not always work in async methods

### ISSUE THREAD

**Issue by wpqs** [dotnet/aspnetcore#24529]
### Problem
I had hoped to use a Cookie to store the user's culture setting as determined in middleware (RequestCultureProvider) because I suspect storing it Thread.CurrentThread.CurrentUICulture will not work in async methods as it seems there is no guarantee that the running thread will be the same as one used for the setting made by my middleware. Unfortunately, in .NET Core (unlike in Framework) after you add a cookie to the HttpResponse.Cookies collection, it does NOT immediately become available in the HttpRequest.Cookies collection; you must wait until after the response has been sent to the client - see [Issue 24442](https://github.com/dotnet/aspnetcore/issues/24442). 

### Solution  I would like
I would like .NET Core to make a cookie set in HttpResponse.Cookies collection become immediately available in the HttpRequest.Cookies collection - i.e. same behaviour as Framework; see  [Microsoft Docs - remarks](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.cookies?view=netframework-4.8)

In the meantime is there another way to store culture settings as determined in middleware so that they are available in async page methods whilst processing the same client request?  Storing culture in session data doesn't work for me due to the cost overhead of implementing a distributed cache. 

It is possible that I am overthinking this problem and that .Net Core guarantees that if  Thread.CurrentThread.CurrentUICulture is set in middleware then the same value will be set in any thread allocated to service the same client request. Can anyone point me to the documentation that explains this?

**Comment by benaadams** [comment]
You can create a `static AsyncLocal<T>` and set it early in the middleware pipeline

https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netcore-3.1

Its value will persist across async calls until the original one returns

**Comment by benaadams** [comment]
Perhaps simpler is to store it in the `HttpContext.Items` dictionary; then you can access that value throughout the request also without doing something custom

**Comment by benaadams** [comment]
Note the AsyncLocal route you can subscribe to change notifications with the `AsyncLocal<T>(Action<AsyncLocalValueChangedArgs<T>>)` callback and set the `Thread.CurrentThread.CurrentUICulture` when it changes in the callback have the thread's culture change automatically to match.

**Comment by Tratcher** [comment]
> I would like .NET Core to make a cookie set in HttpResponse.Cookies collection become immediately available in the HttpRequest.Cookies collection

It was an intentional choice not to do this in Core. Those cookies represent the client state, not the server state. The server should track its own state using any of the mechanics proposed above.

**Comment by blowdart** [comment]
As @Tratcher commented.

The old, framework way has led to a lot of problems and incorrect assumptions. For example, during the same site updates I found that customers would be confused when it was set in a cookie in the request, which is a nonsense, that doesn't get shared with the server, neither do path restrictions, or the secure flag, however the "matching" architecture where we had cookies set in request also mirror in response forced this incorrectness.

HttpContext.Items is probably the best approach here.
