### ISSUE TITLE
Remove etags from StaticFiles

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2453]
_From @muratg on Tuesday, September 27, 2016 4:27:07 PM_

_Copied from original issue: aspnet/StaticFiles#159_

**Comment by aspnet-hello** [comment]
_From @henryhe9999 on Sunday, October 23, 2016 12:51:28 PM_

Why?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Sunday, October 23, 2016 2:26:24 PM_

There is concern that the e-tag generation algorithm is not sufficient. Right now it only considers the length of the file and the last modified date. Hashing the actual contents of the file would be too resource intensive.

Note these concerns are theoretical, no customer issues have been reported and this algorithm has been in use for 3+ years (Katana and ASP.NET Core).

**Comment by aspnet-hello** [comment]
_From @davidfowl on Sunday, October 23, 2016 2:40:26 PM_

> Note these concerns are theoretical, no customer issues have been reported and this algorithm has been in use for 3+ years (Katana and ASP.NET Core).

Nobody complained about the performance of the static file middleware in katana because it was likely very rarely used over IIS. The performance is pretty abysmal in comparison.

It might be worth looking at what other file server implementations do to generate etags.

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, November 2, 2016 1:57:40 PM_

Since this is a breaking change, triaging in 2.0.0 for now.

**Comment by aspnet-hello** [comment]
_From @RehanSaeed on Tuesday, April 11, 2017 7:00:14 AM_

Any updates on what the story here is going to be for 2.0?

**Comment by aspnet-hello** [comment]
_From @ChadNedzlek on Friday, April 21, 2017 2:49:11 PM_

This needs to at least be an option. The overly simplistic algorithm is causing collisions (since changing the file size slight recently after it was previously modified is totally normal). Which causes our site to just fall apart as we get mismatched JS files as some are fetched from cache, and others not. It just broke one of our production deployments, and we have very few options to fix the issue other than to random touch files until the site works again.

So I'm reporting a customer issue.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, April 21, 2017 3:04:43 PM_

@ChadNedzlek Yours is the first report of this being a problem in the wild. Can you give some more details on how it broke? E.g. before and after examples of the size, date, and etag?

**Comment by aspnet-hello** [comment]
_From @ChadNedzlek on Friday, April 21, 2017 3:39:45 PM_

Unfortunately, I can't manage to get it to reproduce anymore... I rebuilt all the files and redeployed to our production server to unblock our customers and everything seems to have changed.

I'm not sure what the exact state was, unfortunately, but we'd only changed the file a small bit (and it was only 5800 bytes, which should have fit in the noise of the FileTime, and the modified times were 4/03/2017 and 4/21/2017, which should be wildly far apart), but browsers were (incorrectly) caching some of the files returned from app.UseStaticFiles() and not others.

**Comment by aspnet-hello** [comment]
_From @bgever on Wednesday, September 13, 2017 2:33:22 AM_

We've hit exactly the same issue in a production environment, and appears to be caused by a browser *feature*, and not the ETag algorithm.

Hitting refresh (with caching enabled) repeatedly should show that sometimes the browser will not reload all static resources from the server, and instead load from cache. In chrome denoted with `(from file cache)` or `(from memory cache)` after the HTTP status code.

The same problem is described in https://github.com/bhauman/lein-figwheel/pull/464 where you can also find a link to the [Chromium blog confirming this behavior](https://blog.chromium.org/2017/01/reload-reloaded-faster-and-leaner-page_26.html).

>  To improve the stale content use case, Chrome now has a simplified reload behavior to only validate the main resource and continue with a regular page load.

As discussed in the linked PR, the use of the `Cache-Control: no-cache` header should force the browser to always contact the server, and since it still sends the `If-None-Match` header due to the `ETag` of the previous response, the new request will be responded with a `HTTP 304 Not Modified`.

**Comment by dazinator** [comment]
Is there any update on this? It would be nice to know if ETag's is sticking around or being removed from staitc files middleware, and if there is a known issue, perhaps it should be documented on the docs site.

**Comment by Tratcher** [comment]
It's not happening for 2.2 at least. We haven't triaged it for 3.0.

**Comment by davidfowl** [comment]
@Tratcher if this is something we want to do, it could be marked as up for grabs.

**Comment by Tratcher** [comment]
Closing do to lack of feedback.
