### ISSUE TITLE
[Blazor] Chain properties don't work properly 

### ISSUE THREAD

**Issue by AntonOnyshch** [dotnet/aspnetcore#24530]
### Describe the bug
If I will change instance of my property inside my class Blazor will be still keeping previous instance.

### To Reproduce

This is simple JS code example.
```
class BaseClass {
    context;
    contextList = new Array();

    constructor() {
        this.contextList.push(new ContextClass(1));
        this.contextList.push(new ContextClass(2));
    }

    setContext(id) {
        const _id = parseInt(id);
        for (let i = 0; i < this.contextList.length; i++) {
            if (this.contextList[i].id === _id) {
                this.context = this.contextList[i];
            }
        }
    }
}
class ContextClass {
    id = 0;

    constructor(id) {
        this.id = id;
    }

    showId() {
        console.log(this.id);
    }
}
window.test = new BaseClass();
```

My C# code:
```
private void IncrementCount()
    {
        await jsRuntime.InvokeVoidAsync("test.setContext", 1);
        await jsRuntime.InvokeVoidAsync("test.context.showId");

        await jsRuntime.InvokeVoidAsync("test.setContext", 2);
        await jsRuntime.InvokeVoidAsync("test.context.showId");
    }
```

**I expect to see in console: 1 and then 2.
What I see is: 1 and 1;**

### Further technical details
- Net Standard 2.1
- Blazor Standalone
- Microsoft.AspNetCore.Components.WebAssembly 3.2.1

**Comment by mrpmorris** [comment]
Change `private void` to `private async Task`

This will allow the caller to `await` it, so then Blazor will know when your method has finished so it can re-render.

**Comment by SteveSandersonMS** [comment]
The issue here is that JS interop caches the lookups from function name to function instance. That is, `test.context.showId` gets cached.

This caching is important for performance so it's not something we'd change. However, if you want to avoid this, it's not difficult: just call a JavaScript function that calls whatever you want in a non-cached way. For example, also define in JS:

```js
function callShowId() {
    test.context.showId();
}
```

... and then from .NET do `await jsRuntime.InvokeVoidAsync("callShowId");`.

**Comment by AntonOnyshch** [comment]
Of course I will use it as a workaround because I don't know how to avoid this caching.
But what if you want to call this **test.context.instance1.instance2.show().**
And my context will be changing time by time.

**Comment by SteveSandersonMS** [comment]
> But what if you want to call this test.context.instance1.instance2.show().

If you pass the identifier to your own JavaScript function, you can use any logic you like to identify the actual function instance to call on to.

**Comment by AntonOnyshch** [comment]
Would you provide some code?
I mean if I have method "show()" in my "instance2" I don't want to create copy of that method inside my "test" class.

**Comment by SteveSandersonMS** [comment]
Imagine a JS function like this:

```js
function callMyOtherFunction(otherFunctionName) {
    var otherFunction = myLogicForFindingTheOtherFunction(otherFunctionName);
    return otherFunction.apply(this, arguments);
}
```

Now if you call that via JS interop, you can invoke any function you like with any args you like. You get to control how the target function instance is identified by implementing `myLogicForFindingTheOtherFunction`.
