### ISSUE TITLE
Intermittent problems starting Azure App Services: “500.37 ANCM Failed to Start Within Startup Time Limit”

### ISSUE THREAD

**Issue by agenne** [dotnet/aspnetcore#24535]
Our app services are experiencing the problem, that they can’t be **restarted** by the hosting environment (ANCM).

Our production subscription consists of up to 8 different app services and the problem can randomly harm one of them ore some of them. The problem can occur several times a week, or just once a month.

The bootstrapping procedure of our app services is not time consuming.

The last occurrence of the problem has this log entries within the eventlog:

**Failed to gracefully shutdown application 'MACHINE/WEBROOT/APPHOST/XXXXXXXXX'.**

followed by:

**Application '/LM/W3SVC/815681839/ROOT' with physical root 'D:\home\site\wwwroot' failed to load coreclr. Exception message: Managed server didn't initialize after 120000 ms**

In most cases the problem can be resolved by manually stopping and starting the app service. In some cases we had to do that twice.

We are not able to reproduce that behavior locally.

The App Service Plan is S2 and we actually use just one instance.

The ASP.NET Core Version is 3.1.3

The documentation of the Http error 500.37 recommends: "You may need to stagger the startup process of multiple apps."

But there is no hint of how to do that.

How can we ensure that our app services are restarted without errors.

**Comment by jkotalik** [comment]
We just filed an issue for this last week: https://github.com/dotnet/aspnetcore/issues/24485

The best way to work around this for now is to increase the startupTimeLimit in a web.config: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#attributes-of-the-aspnetcore-element,

**Comment by jkotalik** [comment]
Going to close this as a dup for #24485
