### ISSUE TITLE
Test `AssemblyVersion`s of everything in shared Fx and targeting pack

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#24541]
All assemblies in the shared FX and targeting pack should have `Major.Minor.0.0` `AssemblyVersion`s. In addition, all of these assemblies should reference _only_ assemblies with the similar `AssemblyVersion` i.e. all should end with `.0.0`.

Our shared FX tests currently check only versions listed in the .deps.json file, not the shipped assemblies. The targeting pack tests check `AssemblyVersion` of shipped assemblies but not their references.

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/25474
