### ISSUE TITLE
Blazor webassembly publish to IIS does not generate correct web.config [Net5.0 Preview7]

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#24568]
On Net5.0 Preview7 publishing a standalone Blazor webassembly app to IIS generates the incorrect web.config. It generates the web config as if it were a serverside web config.

### Steps to reproduce

* Create new blazor app from template in Visual Studio, select ".net5.0", "Blazor Webassembly app", "Create"
* Build & check it works
* Select publish, webdeploy to IIS, default options
* Publish

When opening the app it gives an error: `HTTP Error 500.31 - Failed to load ASP.NET Core runtime`

Inspecting the web config shows that it is a blazor server app web config (with aspnetcore module handler etc)

### Manual web.config also does not work

If a correct Blazor webassembly web.config is supplied as part of the project, this correct web.config is published to the destination, but the publish process transforms the web config by adding the following:
` <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\XXXXX.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />`

This causes the app to fail when opening the page. 

Manually deleting these lines fixes the issue.

**Comment by danroth27** [comment]
@mkArtakMSFT This is still reproduceable with the latest .NET 5 Preview 8 build.
