### ISSUE TITLE
Antiforgery token validation failed When Use Request.BodyReader.ReadAsync() in Middleware

### ISSUE THREAD

**Issue by calanchenlins** [dotnet/aspnetcore#24562]
### Describe the bug
I want Log Request.Body's content In CustomMiddleware, However It Cause Exception: 

		2020-08-03 20:56:36.935 +08:00 [INF] Antiforgery token validation failed. The antiforgery token could not be decrypted.
		Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
		 ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
		   at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
		   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
		   at System.Convert.FromBase64CharArray(Char[] inArray, Int32 offset, Int32 length)
		   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
		   --- End of inner exception stack trace ---
		   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
		   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.DeserializeTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet, AntiforgeryToken& cookieToken, AntiforgeryToken& requestToken)
		   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
		   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
		   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)

By Debugging the ASP.NET Core' source code,I found that HttpContext.Request.ReadFormAsync() return Duplicate Content In DefaultAntiforgeryTokenStore.GetRequestTokensAsync().
 If I Use HttpContext.Request.Body.ReadAsync() to replace of HttpContext.Request.BodyReader.ReadAsync() In CustomMiddleware, It working properly. I dont't know it's a bug or something else.Can someone point out to me why? 

### To Reproduce

1. Create a ASP.NET Core Web project through Template
2. Add  `app.UseMiddleware<RequestBufferingMiddleware>();` in Configure method in  Startup.cs file

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews(options =>
            {
                options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
            });
        }
		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{

			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
			else
			{
				app.UseExceptionHandler("/Home/Error");
				app.UseHsts();
			}

			app.UseMiddleware<RequestBufferingMiddleware>();

			app.UseHttpsRedirection();
			app.UseStaticFiles();
			app.UseRouting();
			app.UseAuthorization();
			app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllerRoute(
					name: "default",
					pattern: "{controller=Home}/{action=Index}/{id?}");
			});
		}

3. `RequestBufferingMiddleware.cs`

		public class RequestBufferingMiddleware
		{
			private readonly RequestDelegate _next;
			private readonly ILogger _logger;
			public RequestBufferingMiddleware(RequestDelegate next, ILoggerFactory loggerFactory)
			{
				_next = next;
				_logger = loggerFactory.CreateLogger<RequestBufferingMiddleware>();
			}
			public async Task InvokeAsync(HttpContext context)
			{
				context.Request.EnableBuffering();
				try
				{
					//this Make an exception:'Antiforgery token validation failed. The antiforgery token could not be decrypted.'
					var body = await context.Request.BodyReader.ReadAsync();
					var planText = Encoding.UTF8.GetString(body.Buffer.ToArray());

					// this working properly
					//var buffer = new byte[1000];
					//var bodyLength = await context.Request.Body.ReadAsync(buffer, 0, 1000);
					//var planText = Encoding.UTF8.GetString(buffer.AsSpan().Slice(0, bodyLength));
					
					//log Request.Body's content
				}
				finally
				{
					context.Request.Body.Position = 0;
					context.Request.Body.Seek(0, SeekOrigin.Begin);
				}

				// Call the next delegate/middleware in the pipeline
				await _next(context);

				try
				{
					var form = await context.Request.ReadFormAsync();
				}
				catch (Exception ex)
				{
					var t = ex.Message;
				}
			}
		}

4. Controller and View

        [HttpPost]
        public IActionResult Submit()
        {
            return Content("1");
        }
		
		<div class="row">
			<div class="col-sm-6">
				<form asp-action="Submit">
					<fieldset>
						<div class="form-group">
							<button class="btn btn-primary">Yes</button>
						</div>
					</fieldset>
				</form>
			</div>
		</div>

5. IFormCollection Data:

		Exception IFormCollection Data:
		
		Key:"__RequestVerificationToken"
		Value: "CfDJ8OcSJsaJ5z9JijiyWLMQ9ETDWQIAYAxlZu8qapJHkL2HLUp6GhtSkavaTimD3uNcB9Rcl6kstHw9SVwI0UNY2G7SzuJZt3Z5-pDwDciyq0fQehPjOPJU6NnihEciTFOm9wsJs7MTX44ePrCA-Z-Rz68__RequestVerificationToken=CfDJ8OcSJsaJ5z9JijiyWLMQ9ETDWQIAYAxlZu8qapJHkL2HLUp6GhtSkavaTimD3uNcB9Rcl6kstHw9SVwI0UNY2G7SzuJZt3Z5-pDwDciyq0fQehPjOPJU6NnihEciTFOm9wsJs7MTX44ePrCA-Z-Rz68"
		
		Expect IFormCollection Data:
		
		Key:"__RequestVerificationToken"
		Value: "CfDJ8OcSJsaJ5z9JijiyWLMQ9ETDWQIAYAxlZu8qapJHkL2HLUp6GhtSkavaTimD3uNcB9Rcl6kstHw9SVwI0UNY2G7SzuJZt3Z5-pDwDciyq0fQehPjOPJU6NnihEciTFOm9wsJs7MTX44ePrCA-Z-Rz68"

### Further technical details
- ASP.NET Core version: Microsoft.AspNetCore.App 3.1.4 
- .NET Core SDK version:  3.1.300
- VS version: Microsoft Visual Studio Community 2019  16.6.0

**Comment by Tratcher** [comment]
Calling BodyReader.ReadAsync requires a call to BodyReader.Advance after it or you leave the reader in an invalid state. That's not the exception I would have expected though.

**Comment by mkArtakMSFT** [comment]
@Tratcher is this really `MVC` ?
Also, what are the next steps here?

**Comment by Tratcher** [comment]
It's not clear how the above buffering code would cause that antiforgery error, someone will need to investigate. The antiforgery component needs better error reporting at a minimum, it seems to be masking a body error.

**Comment by calanchenlins** [comment]
> Calling BodyReader.ReadAsync requires a call to BodyReader.Advance after it or you leave the reader in an invalid state. That's not the exception I would have expected though.

Thank you for your reply. This is a problem caused by the wrong usage of PipeReader: Before we read to the end of PipeReader ,we can't sets the position within the InnerStream of PipeReader.
`RequestBufferingMiddleware.cs`

        public async Task InvokeAsync(HttpContext context)
        {
            context.Request.EnableBuffering();
            try
            {
                // Before we read to the end of HttpContext.Request.BodyReader(When ReadResult.IsCompleted is true)
                // we can't sets the position within HttpContext.Request.Body
                // otherwise, HttpContext.Request.BodyReader will repeatedly read the stream after the Position 
                var body = await context.Request.BodyReader.ReadAsync();

                // Correct Usage:
                // var body = await context.Request.BodyReader.ReadToEndAsync();

                context.Request.BodyReader.AdvanceTo(body.Buffer.Start);

                // Before read HttpContext.Request.Body, we have to sets the position within HttpContext.Request.Body
                context.Request.Body.Position = 0;
                // read HttpContext.Request.Body...

                // In the method of FormPipeReader.ReadFormAsync(), it will read to the end of HttpContext.Request.BodyReader
                var body2 = await context.Request.BodyReader.ReadToEndAsync();
                context.Request.BodyReader.AdvanceTo(body2.Buffer.Start);

            }
            catch (Exception ex) { }
            finally{}

            // Call the next delegate/middleware in the pipeline
            await _next(context);
        }
        public static async ValueTask<ReadResult> ReadToEndAsync( this PipeReader pipeReader, CancellationToken cancellationToken = default) 
        {
            while (true)
            {
                var body = await pipeReader.ReadAsync();
                if (body.IsCompleted)
                {
                    return body;
                }
                pipeReader.AdvanceTo(body.Buffer.Start, body.Buffer.End);
            }
        }
