### ISSUE TITLE
System.TypeLoadException: Method get_ClientCorsOrigin is not implemented in ApiAuthorizationDbContext

### ISSUE THREAD

**Issue by yakeer** [dotnet/aspnetcore#24582]
Updated IdentityServer4 from 3.1.4 to 4.0.4,
and Microsoft.AspNetCore.ApiAuthorization.IdentityServer from 3.1.4 to latest stable.

All dependencies are in latest version.

When I run my project, I get a System.TypeLoadException: Method get_ClientCorsOrigin is not implemented in ApiAuthorizationDbContext

Not sure if it's IdentityServer4 issue, or ApiAuthrozationDbContext...
But anyone else is facing this issue?

**Comment by blowdart** [comment]
We don't support IS 4 yet. It will be supported in 5.0
