### ISSUE TITLE
The razor component will not be recognized when the Blazor project name starts with System.*

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24604]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/861187/当blazor项目项目名称采用比较长的名称时-razor组件将不可被识别.html)._

---
When I create new project names that are shorter, such as Host Service or System.Host Service, the razor component is recognizable, but when I use a longer name such as System.Host Service.Lora Service, the razor component will not be recognized.
The test environment is the official Blazor template, the difference is the length of the project name
The problem is NavMenu / . . Sometimes recognized and sometimes not recognized, compilation runs and does not function properly.

inherits Layout ComponentBase

div class "sidebar"
    NavMenu /
</div>

div class "main"
    div class "top-row px-4"
        a href"https://docs.microsoft.com/aspnet/target-_blank-about-</a>
    </div>

div class """""""""""""""""""""""""""""""""
        @Body
    </div>
</div>

---
#### Feedback Bot on 12/18/2019, 10:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/19/2019, 10:08 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
We're tracking addressing this via https://github.com/dotnet/aspnetcore/issues/18757
