### ISSUE TITLE
Cleanup versions a bit

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#24608]
This is about following up on e13368391b02 as discussed starting at https://github.com/dotnet/aspnetcore/pull/21567#issuecomment-668267663.

- [x] Remove the Internal.AspNetCore.Analyzers project and all references to it
    - We no longer have pub-ternal types outside analyzers and tools. Therefore, we don't need to warn about them anymore.
    - Remove `$(DisablePubternalApiCheck)` settings too
- [ ] Move from Yarn.MSBuild 1.15.2 to 1.22.4
    - This version is mentioned in both global.json and eng/Tools.props. The versions should match between those files.
- [x] Update `AddContent` target in Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj to set **5.0** package versions based on the projects
    - Remove the redundant `@(PackageReference)`s for the 5.0 packages earlier in the project file
    - Move comments about changing how these references are handled down into the `AddContent` target and call out the need to do this when switching to `net6.0`
- [x] Move the `MsQuicPackage.*` versions from QuicSampleClient and QuicSampleApp projects to eng/Versions.props

**Comment by Pilchie** [comment]
@dougbu Should we move this to rc2?

**Comment by dougbu** [comment]
@pranavkm fixed the first bullet with #24693 and I fixed the third bullet with #25406. Both changes are in RC1 and I'd forgotten to check them off here.

Agree the remainder should happen in RC2.

**Comment by Pilchie** [comment]
Is this GA or 6.0 now?

**Comment by dougbu** [comment]
What remains is just cleanup and the existing bits work. So, 6.0.

**Comment by JunTaoLuo** [comment]
Last item was done in https://github.com/dotnet/aspnetcore/pull/28420.
