### ISSUE TITLE
Allows developers to customize communication components.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#24611]
I'm trying to use Kestrel to customize my own communication components, customize my own protocols, and need to use the "multiplexing" feature and "HPACK cache" in HTTP2.

We need a high-performance communication component and use our own specific protocols. We expect to use Kestrel as the communication engine and use the multiplexing feature.

But we don't know how to use Kestrel to customize TCP/UDP protocol. Is there any relevant documentation?

**Comment by BrennanConroy** [comment]
In 5.0 you can use [System.Net.Connection](https://github.com/dotnet/runtime/issues/1793) for implementing your own TCP transport.

Our internal HPACK and HTTP2 types are likely going to stay internal, but it's open source, so feel free to fork/copy the code! Make sure to keep it up to date in that case.

**Comment by NMSAzulX** [comment]
@BrennanConroy Thanks. Can I use Kestrel and System.Net.Connection to implement this requirement?
