### ISSUE TITLE
Can't make nested components

### ISSUE THREAD

**Issue by ATerentjev** [dotnet/aspnetcore#24621]
Dear Gurus!
Sorry, if the question is related to my lack of experience. I am trying to make a component library for working with a mapbox from blazor. Now I have a main component  MapBoxView, that displays a map and MapboxGeocoder, wich used for finding  objects . Each of component has a procedure OnFirstAfterRenderAsync():
```
        protected async override Task OnFirstAfterRenderAsync()
        {
            await base.OnFirstAfterRenderAsync();
            Dictionary<string, object> o = new Dictionary<string, object>();
            ...
            await JsInvokeAsync<object>("mapgl.mymap.initMap", o);
        }
```
and
```
        protected async override Task OnFirstAfterRenderAsync()
        {
            await base.OnFirstAfterRenderAsync();
            Dictionary<string, object> o = new Dictionary<string, object>();
            o.Add("container", container);
            await JsInvokeAsync<object>("mapgl.mygeocoder.initGeocoder", o);
        }
```
When in demo program I use code:
```
@page "/"

<MapBoxView zoom=@_zoom container=@containerName mapCenter=@centerOfView>
</MapBoxView>

<MapBoxGeocoder Id="geocoder">
</MapBoxGeocoder>
```
then all works fine, and I get the picture I want:
![map_with_geocoder](https://user-images.githubusercontent.com/67376268/89538152-e0b95d00-d802-11ea-87c6-1999ac59f821.png)
But when I use next code:
```
    <MapBoxView zoom=@_zoom container=@containerName mapCenter=@centerOfView>
        <MapBoxGeocoder Id="geocoder">
        </MapBoxGeocoder>
    </MapBoxView>

```
That is, I put the nested component in the main one, then the geocoder (left bottom window with text - Search on the picture)  is not shown and  the program does not enter the procedure   OnFirstAfterRenderAsync() of MapBoxGeocoder component.
   Main component MapBoxView has razor code:

```
@namespace MapBoxBlazor

@inherits BaseMapBoxView

    <div id='mapContainer'>
    </div>

```
What am I doing wrong? How to do it right?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
