### ISSUE TITLE
query array params order not preserved

### ISSUE THREAD

**Issue by dab0bby** [dotnet/aspnetcore#24622]
Controller parameter:
```
[FromQuery] string[] sorts
```

When calling api with query params like: `...?sorts=z&sorts=m&sorts=a&sorts=b` all the values are then available in the `sorts` array but sorted. So the result looks like: `["a", "b", "m", "z"]`

Expected: order of same-name query parameters is preserved: `["z", "m", "a", "b"]`

Using:
-  ASP.NET Core version 3.1

**Comment by blowdart** [comment]
That's not guarenteed by the HTTP spec I'm afraid.

**Comment by Tratcher** [comment]
I'm not able to repro this on 3.1 with either of these samples:
```

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!\r\n");

                    foreach (var pair in context.Request.Query)
                    {
                        foreach (var value in pair.Value)
                        {
                            await context.Response.WriteAsync($"{pair.Key}={value}\r\n");
                        }
                    }
                });
            });
```

```
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<string> Get([FromQuery] string[] sorts)
        {
            return values;
        }
    }
```

I get the original ordering each time.

**Comment by dab0bby** [comment]
@Tratcher I will try to create a small repo showcasing that problem

**Comment by javiercn** [comment]
@dab0bby thanks for contacting us.

This is not a feature MVC has. We don't guarantee ordering then you bind parameters that way unless you explicitly specify the order within the query parameter `sorts[0]=z` and so on, and even in that case I'm not sure if its something that works for query parameters
