### ISSUE TITLE
Blazor WASM apps should fully trim Microsoft.Extensions.* assemblies

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#24634]
Today, when publishing a Blazor WASM app, we are telling the ILLinker to trim `Microsoft.Extensions.*` assemblies, but only at a "type granularity" level. Meaning, if some part of the Type is used, preserve the whole Type.

https://github.com/dotnet/aspnetcore/blob/6c35e2e84d8c15dfcbd8ce38b3cc843f28ffccac/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Components.Wasm.targets#L372-L377

This causes unnecessary bloat in the produced app because there are types in `Microsoft.Extensions.*` where some unused code is pulling in more `System.*` assemblies (e.g. System.Diagnostics.DiagnosticSource.dll), causing even more unused code to be compiled in the app.

With the recent work done in Extensions to make them linker-friendly:

* https://github.com/dotnet/runtime/pull/40227
* https://github.com/dotnet/runtime/pull/40294
* https://github.com/dotnet/runtime/pull/40431

we should be able to remove the "type granularity" clauses for these assemblies now that they are linker safe.

Using a recent `rc1` build, I'm seeing the following size savings in IL:

|            | Uncompressed IL      | Compressed IL (.br)    |
|------------|----------------------|------------------------|
| master     | 2,426,368 bytes      | 852,236 bytes          |
| PR         | 2,339,328 bytes      | 822,834 bytes          |
| Difference | 87,040 bytes (85 KB) | 29,402 bytes (28.7 KB) |

cc @SteveSandersonMS @pranavkm @marek-safar

**Comment by SteveSandersonMS** [comment]
Thanks @eerhardt!

**Comment by samsp-msft** [comment]
Once complete, does this mean that the Microsoft.AspNetCore.* and Microsoft.Extensions.*  assemblies should just get standard TrimMode=Trim behavior?

**Comment by eerhardt** [comment]
My thinking is that only `Microsoft.Extensions.* ` assemblies will get the standard TrimMode=Trim behavior. I don't think anyone has done the work to make all the `Microsoft.AspNetCore.*` assemblies to be linker-safe. @davidfowl has started on some of the server side assemblies, but I don't think the Blazor WASM assemblies have been made linker-safe yet.

**Comment by davidfowl** [comment]
Nice!
