### ISSUE TITLE
Add script command to sql-cache tool

### ISSUE THREAD

**Issue by glatzert** [dotnet/aspnetcore#24635]
### Is your feature request related to a problem? Please describe.
I am trying to create the tables for distributed sql cache via the dotnet tool "sql-cache".
This works well, as long a I am developing and have full database access, but it's not working for scenarios, where I lack of access rights.

### Describe the solution you'd like
Add `dotnet sql-cache script`, so the neccessary commands are written to the stdout and can easily be copied to an textfile.

**Comment by ajcvickers** [comment]
@mkArtakMSFT @Pilchie I thought this was part of Caching.SqlServer, but apparently it is not. It's not an EF thing, so I'm out of ideas.

**Comment by mkArtakMSFT** [comment]
@Tratcher, @pranavkm, @javiercn do you happen to know who owns this tool in our team?

**Comment by javiercn** [comment]
@JunTaoLuo maybe?

**Comment by Pilchie** [comment]
We don't (yet), have an up-for-grabs label, but I don't think we'd be against a contribution here.  It's quite late for the .NET 5 release, so it's likely something that would end up in .NET 6 though.

**Comment by Tratcher** [comment]
It's called [help wanted](https://github.com/dotnet/aspnetcore/labels/help%20wanted) in this repo. We also have [good first issue](https://github.com/dotnet/aspnetcore/labels/good%20first%20issue) for easier items.
