### ISSUE TITLE
DbContext aborts  query execution with Blazor Server Side

### ISSUE THREAD

**Issue by danirdd92** [dotnet/aspnetcore#24642]
Hi Team,

I'm using Blazor Server Side with Ef Core for Data Access on a small project of mine.

I have an issue with my DbContext failing to retrieve data resulting in a null reference exception inside my components.

### Steps to reproduce

Please clone [this ](https://github.com/danirdd92/BlazorEFCoreIssue) repo for your convenience.
and use the sql script provided bellow to create the Db the app's context attached to.
[FullDbCreationScript.zip](https://github.com/dotnet/aspnetcore/files/5039167/FullDbCreationScript.zip)

once everything is place just lunch the app and go to the TestingGrounds in order to reproduce the bug.
 
As far as the issue provided I checked the logs and something particular stood out

fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database 'ShiftsDb' on server '(localdb)\MSSQLLocalDB'.
fail: **Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'ShiftManager.Data.Models.ShiftsDbContext'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.**

While debugging I also noticed strange behaviour, although it queries for the Dates table alone
the debugger traced into the DbContext OnModelCreating into the Shifts tables for some reason.

### Further technical details
Using latest stable version of Ef Core, .Net Core SDK and VS
Using SqlServer as Db Provider
Using Windows 10 Latest stable build

**Comment by javiercn** [comment]
@danirdd92 thanks for contacting us.

You are trying to execute multiple queries simultaneously.

The recommendation is that you use `OwningComponentBase<YourDbContext>` to make sure each component gets its on db context instance (You need to remove `@inject and use component.Service instead)` or that you create and dispose a dbcontext per query/operation
