### ISSUE TITLE
it spends a lot of time from request starting to executing endpoint

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#24645]
#### In the  product environment, it spends a lot of time from request starting to executing endpoint, resulting the entire request executing very slowly. This problem did not occur in the development environment

![log](https://user-images.githubusercontent.com/5714438/89611886-e53c4f00-d8b0-11ea-8c5e-c61d7db676ba.jpg)

```
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.200
 Commit:    c5123d973b

运行时环境:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by javiercn** [comment]
@Varorbc thanks for contacting us.

Can you provide a minimal repro project so that we can investigate?

**Comment by Varorbc** [comment]
@javiercn Sorry, I may not be able to provide you with a reproduction project, but I can tell you what happened. I have solved the problem. The reason is that there is a time-consuming code in my authorization filter that caused this problem. But what bothers me now is the output order of the logs. During the debugging process, I found that the console had already printed the log line'exectuting endpoint...' before the authorization filter was executed, but the time-consuming code was in In the authorization filter, can you tell me the printing order of the logs?

translate by google

**Comment by pranavkm** [comment]
@Varorbc we haven't heard a lot of feedback about the log messages as yet. An endpoint is the first thing that gets picked and executed (when you have endpoint routing), and the message `Executing endpoint` reflects this. If we hear more feedback for this, we'll reconsider this message.

**Comment by Varorbc** [comment]
@javiercn today the issue appeared again, it should not be caused by the issue I said last time I guess.please give me some suggestions that I can investigate this issue myself? thank you
