### ISSUE TITLE
Blazor: Websocket switching session

### ISSUE THREAD

**Issue by macleysousa** [dotnet/aspnetcore#24649]
### Describe the bug
# Websocket switching session
When you have two different sessions connected on the same network, at certain times the system is causing the exchange of these sessions.

In some cases, one session can control the other.

**This is causing a breach in the security of my system.** Has anyone been through this and know how to solve this problem?

![websocket session](https://raw.githubusercontent.com/macleysousa/filestoissues/master/websocket%20session.gif)

### Further technical details
- ASP.NET Core version = `3.1.6`
- Include the output of `dotnet --info`
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-ef": {
      "version": "3.1.6",
      "commands": [
        "dotnet-ef"
      ]
    }
  }
}
```

**Comment by javiercn** [comment]
@macleysousa thanks for contacting us.

Please note for future security issues a github issue is not the best place to report them. Please consider using our coordinated disclosure route, as highlighted when you created issues. Security issues reported through secure@microsoft.com are eligible for our bug bounty program. Github issues are not eligible.

Are you able to reproduce this in a Blazor server application created from scratch?

**Comment by macleysousa** [comment]
> @macleysousa obrigado por nos contatar.
> 
> Por favor, note que para problemas de segurança futuros um problema de github não é o melhor lugar para denunciá-los. Por favor, considere usar nossa rota de divulgação coordenada, como destacado quando você criou problemas. Problemas de segurança relatados através [de secure@microsoft.com](mailto:secure@microsoft.com) são elegíveis para o nosso programa de recompensa de bugs. Os problemas do Github não são elegíveis.
> 
> Você é capaz de reproduzir isso em um aplicativo de servidor Blazor criado do zero?

At the moment I am updating everything possible on my computer to create a new project from scratch and test it.

**Comment by macleysousa** [comment]
> @macleysousa thanks for contacting us.
> 
> Please note for future security issues a github issue is not the best place to report them. Please consider using our coordinated disclosure route, as highlighted when you created issues. Security issues reported through [secure@microsoft.com](mailto:secure@microsoft.com) are eligible for our bug bounty program. Github issues are not eligible.
> 
> Are you able to reproduce this in a Blazor server application created from scratch?

At the moment I am updating everything possible on my computer to create a new project from scratch and test it.

**Comment by javiercn** [comment]
> At the moment I am updating everything possible on my computer to create a new project from scratch and test it.

If you are able to repro this in an application created from scratch can you send us details to `secure@microsoft.com`?

From what I can tell in the "video" the changes seem to be coming from your "main.js" file, which strongly indicates you have some sort of static event/singleton service on the app that is enabling the shared state.

**Comment by javiercn** [comment]
I'm going to lock and close this issue since any future conversation should happen through secure@microsoft.com
