### ISSUE TITLE
ChallengeResult RedirectUri ignored after a delayed login in

### ISSUE THREAD

**Issue by TestO2015** [dotnet/aspnetcore#24643]
### Describe the bug
I have a ChallengeResult authenticating with Azure AD which doesn't return to the RedirectUri configured, if the user sits on the login page for several minutes before actually signing in. It works fine if the user logs in immediately.

The setup includes:
 - Azure AD authentication through OpenId Connect
 - CallbackPath: "~/signin-oidc"
 - A login API

        [AllowAnonymous]
        [HttpGet("Login")]
        public IActionResult Login()
        {
            return Challenge(new AuthenticationProperties
            {
                RedirectUri = "http://google.com",
            }, OpenIdConnectDefaults.AuthenticationScheme);
        }

Instead the user lands on the CallbackPath and a 500 error as a result. The login itself is successful - the token is received but the user lands on the wrong page.

I expect for the login request to follow a path along the lines:

    .Net Core App > Azure AD login page > .Net Core App callback path > Redirect Uri 

### To Reproduce
Please let me know if I can provide more information or if it's necessary to try create a demo App to reproduce the issue.

### Further technical details
- ASP.NET Core version: 3.1

**Comment by javiercn** [comment]
@TestO2015 thanks for contacting us.

Is this happening with Microsoft.AspNetCore.Authentication.AzureAd.UI or are you using your own codebase? We recommend you try and move to the new Microsoft.Identity.Web package in the first case and see if that fixes your issue.

**Comment by Tratcher** [comment]
How long? There are several cookies involved that have short expectations (~15 minutes).

https://github.com/dotnet/aspnetcore/blob/973a97fc4b0ac2c125bcb3872a271b608ff1b13e/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L324

The server logs should say that either the nonce or correlation cookie is missing.

**Comment by TestO2015** [comment]
@javiercn I'm not using Microsoft.AspNetCore.Authentication.AzureAd.UI because I'll need to support other Identity Providers beyond Azure AD. The only package I reference is:

    Microsoft.AspNetCore.Authentication.OpenIdConnect

Does Microsoft.Identity.Web work with other Identity Providers?

@Tratcher I'd say within 10 minutes but I'll try your suggestions.

Thanks.

**Comment by blowdart** [comment]
The correlation timeout is at https://github.com/dotnet/aspnetcore/blob/288bb9622d4dbfde52833e57940175277c6de921/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs#L118

We do consider 15 minutes "reasonable", so there's no real action here for us.
