### ISSUE TITLE
Balzor wasm AD B2C hosted app 

### ISSUE THREAD

**Issue by spkiran** [dotnet/aspnetcore#24659]
Instructions to create Balzor wasm AD B2C hosted app followed from here:
[](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)

**Issue:**
in Client app : \wwwroot\appsettings.json "Authority":  tag is missing separation between instance and domain. Missing "/" and needed to be manually added.

xxxxxx.b2clogin.comxxxxxx.onmicrosoft.com
fix
xxxxxx.b2clogin.com/xxxxxx.onmicrosoft.com

**Comment by guardrex** [comment]
@spkiran ... Are you using the [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C article](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c)?

If so, the instruction for [Create the app](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c#create-the-app) specifies the AAD B2C instance (`{AAD B2C INSTANCE}`) with a trailing slash (see the *Example* column of the table) for the `dotnet new` command. Did you provide the trailing slash? If so, you should've received it in the `Authority` in the app settings file.

**Comment by spkiran** [comment]
https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c

Yes I am using that and I noticed the comment about trailing slash. Confusing as heck. But I am glad its there now I see it.

thanks. issue closed.
