### ISSUE TITLE
HTTPS dev certs on OSX Catalina results in PR_END_OF_FILE_ERROR error

### ISSUE THREAD

**Issue by pseudoramble** [dotnet/aspnetcore#24651]
### Description

I am updating an existing ASP.NET Core API project to use HTTPS during development. I do not see any particular exceptions occurring during or after startup. When it has finished starting up, I attempt to navigate to the site and I am getting a connection refused-like error:

![image](https://user-images.githubusercontent.com/12829967/89647900-5584a980-d88c-11ea-917f-2b32392bd19f.png)

I have what I think is the normal configuration for my Startup.cs Configure method:

```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseCors(...);
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            ...
        }
```

### Configuration

.NET Core 2.2.8.
OSX Catalina
x64

### dotnet --info

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.110 [/usr/local/share/dotnet/sdk]
  2.2.207 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Other information

A few things I have checked so far:

1. The certificate appears to be valid and fully trusted in the Key Store. I have recreated them multiple times using `dotnet dev-certs https --clean` and then `dotnet dev-certs https --trust`.
2. In Firefox I had originally trusted old versions of these certificates for localhost:5001. So I went through and removed those to attempt to retrust them.
3. I have tried to check a variety of settings I've read _could_ cause this issue (disabled firewall/AV temporarily, checked that browsers accept proper certificates, etc).
4. I have run openssl to try and see if I can get any additional. Here's the output from that:

```
openssl s_client -connect localhost:5001
CONNECTED(00000005)
4671245932:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.140.1/libressl-2.8/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1596804831
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by javiercn** [comment]
@pseudoramble thanks for contacting us.

Seems like you are using .NET Core 2.2.8 which is out of support as per our support policy. See [here](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for details.

We recommend you upgrade to an LTS version like 3.1 or 2.1 as a first step to see if that solves your problem.

**Comment by pseudoramble** [comment]
Thanks for the feedback. We're very aware and actively working on moving away from 2.x for this reason. Our other codebases are already there, but this was newly adopted and not there yet.

I will try on a 3.x codebase and confirm that the issue is resolved and follow up if the issue persists.
