### ISSUE TITLE
Dependencies are not included when publishing to IIS via MSDeploy from VS 2019

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/aspnetcore#24654]
Files in packages like ```Microsoft.EntityFrameworkCore``` and ```Microsoft.AspNetCore.Mvc.NewtonsoftJson``` are not included when publishing an ASP.NEt Core app. No matter framework dependent or self-contained.

They are in the ```Release``` folder but not output to ```publish``` (even when just publishing to a folder)

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```
SDK: .NET 5.0 Preview 7
Visual Studio 2019 (Version 16.8.0 Preview 1.0)

My reference:

```
 <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.0-preview.7.20365.19" />
```

**Comment by robertsundstrom** [comment]
It is not just that library but all other dependencies will not get published either.

```Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.EntityFrameworkCore, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

**Comment by robertsundstrom** [comment]
I think it broke when I updated to the latest preview of Visual Studio.

**Comment by gmalignon** [comment]
I have exactly the same problem, I can't publish any more because of that. 
It's not because of the new version of VS.

I think I figured out why:
Microsoft.CodeAnalysis 3.7.0, Microsoft.CodeAnalysis.CSharp 3.7.0, Microsoft.CodeAnalysis.Common 3.7.0 Nuget packages  were released on 08/05/2020 but other components are still looking for the previous versions.
I don't think they should have been released yet.

Here's one of the error messages:
 warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration.Templating 5.0.0-preview.7.20370.3 depends on Microsoft.CodeAnalysis.CSharp (>= 3.7.0-3.20269.11) but Microsoft.CodeAnalysis.CSharp 3.7.0-3.20269.11 was not found. An approximate best match of Microsoft.CodeAnalysis.CSharp 3.7.0-3.final was resolved.

**Comment by robertsundstrom** [comment]
I'm in the same situation. Cannot publish. Is there a workaround?

**Comment by robertsundstrom** [comment]
Well, no dependencies except Microsoft dependencies are being published to the folder.

**Comment by robertsundstrom** [comment]
Works in VS for Mac. All files are published.

**Comment by gmalignon** [comment]
I don't have access to a Mac so I'm still unable to publish updates.
Does anyone know how to fix this? I tried going back to previous versions of Microsoft.CodeAnalysis but it still doesn't work.

The 2 files that have a dependency problem are the following ones:

1) Warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration.Templating 5.0.0-preview.7.20370.3 depends on Microsoft.CodeAnalysis.CSharp (>= 3.7.0-3.20269.11) but Microsoft.CodeAnalysis.CSharp 3.7.0-3.20269.11 was not found. An approximate best match of Microsoft.CodeAnalysis.CSharp 3.7.0-3.final was resolved.

2) Warning NU1603: Microsoft.VisualStudio.Web.CodeGeneration.Utils 5.0.0-preview.7.20370.3 depends on Microsoft.CodeAnalysis.CSharp.Workspaces (>= 3.7.0-3.20269.11) but Microsoft.CodeAnalysis.CSharp.Workspaces 3.7.0-3.20269.11 was not found. An approximate best match of Microsoft.CodeAnalysis.CSharp.Workspaces 3.7.0-3.final was resolved.

It says it's resolved but the deps.json is missing third party dependencies. Also even the Microsoft dependencies have different versions than the correct deps.json file.

I am using Visual Studio 16.8 Preview 1 (Visual Studio 16.7.0 doesn't work either) and the latest .Net 5.0 Preview (7).

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by gmalignon** [comment]
It's a rather large project, I don't know how I could provide a sample project.

What I did is manually revert to the previous versions of whatever nuget packages that got updated (back to the same way as when everything was working fine) in the .csproj file, then I used the deps.json from when Visual Studio was publishing correctly and I'm able to publish in the mean time.

**Comment by gmalignon** [comment]
I just know it's definitely the release of Microsoft.CodeAnalysis  3.7.0 on 08/05 which caused this problem.

**Comment by robertsundstrom** [comment]
Related to this? #24769
