### ISSUE TITLE
Please document breaking changes for #22164

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet/aspnetcore#24656]
Hi,

I'm the author of the [FluentValidation](https://github.com/FluentValidation/FluentValidation) library. Preview 7 unfortunately broke our integration with ASP.NET due to the changes in https://github.com/dotnet/aspnetcore/commit/902e735b27dea536ad868d13aa74d0e12017fa0f#diff-d930ca39121ff5a6afabf920467f4c7b (which were made for #22164). 

The fix was pretty simple (adding an additional method override in our ValidationVisitor), but it took a long time to figure out what had broken because this change to `ValidationVisitor` isn't documented anywhere (as far as I can see). Although this is not a compiler error, it *is* a breaking change in behaviour. 

Please could this change be documented somewhere?

Thanks!  

// cc @pranavkm

**Comment by pranavkm** [comment]
Sorry about that @JeremySkinner. I should have checked with you when I changed the type. Are you able to workaround the change or would you us to revisit it? I can post an announcement if it's the former.

**Comment by JeremySkinner** [comment]
No problem! Yes I was able to [work around just fine](https://github.com/FluentValidation/FluentValidation/pull/1474/files#diff-af6b0abd2d85e03aad226266268a718f) once I understood what had changed. An announcement sounds good to me, thanks! 🤗

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/issues/24656.
