### ISSUE TITLE
macOS build failing for branches targeting release/3.1

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#24667]
Something funky is afoot with the Kestrel tests in macOS on the 3.1 branch. PR builds are failing.

See https://dev.azure.com/dnceng/public/_build/results?buildId=760973&view=results.

We need to address this so that we can merge in patches to 3.1.

**Comment by dougbu** [comment]
@captainsafia this issue can be closed as fixed, can't it❔

**Comment by captainsafia** [comment]
Yep, we fixed this in October I believe. Closing.
