### ISSUE TITLE
ServerEventTest.EventDuringBatchRendering_CanTriggerDOMEvents failed

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24688]
```
---- Assert.Equal() Failure
Expected: Change event on item First with value a\nChange event on item First with value ab\nChange event on item First with value abc
Actual:   Change event on item First with value abc
```

Failure in https://dev.azure.com/dnceng/public/_build/results?buildId=762015&view=artifacts&type=publishedArtifacts

**Comment by javiercn** [comment]
Test is not quarantined any longer and hasn't failed in the last 30 days.

**Comment by BrennanConroy** [comment]
It sort of is
https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Components/test/E2ETest/ServerExecutionTests/ServerEventTest.cs#L22-L23

But I'll remove it from quarantine if you believe it's good now.
