### ISSUE TITLE
Bug in Blazor Razor Editor

### ISSUE THREAD

**Issue by mazizi88** [dotnet/aspnetcore#24698]
### Describe the bug
The new Razor editor crash Visual Studio when opening large razor file.
Visual Studio 16.6.5.

**Comment by NTaylorMullen** [comment]
@mazizi88 could you please try your repro on the latest Visual Studio (16.8-Preview1 as of now) and see if it reproduces? If it still does would you mind providing a repro application for us to investigate further.
