### ISSUE TITLE
Form group tag helper asp-action with nameof an async action result in wrong url

### ISSUE THREAD

**Issue by hmdhasani** [dotnet/aspnetcore#24702]
After migrating to ASP Core 3.1 because of https://github.com/dotnet/aspnetcore/issues/4849
some of my form urls broke and that's because of using nameof():

```
<form asp-action="@nameof(FilesController.CreateAsync)">
</form>
```

the html result is:
```
<form action="/Files/CreateAsync" method="post">
</form>
```
while the correct url is :
```
<form action="/Files/Create" method="post">
</form>
```

this can be in other url generation ways like UrlHelperExtensions methods , too

**Comment by pranavkm** [comment]
@hmdhasani the Async suffix is trimmed by default for controller actions. See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#async-suffix-removal-from-controller-action-names for ways to mitigate this.

**Comment by hmdhasani** [comment]
OK, thanks.
As an improvement suggestion as we have nameof() in C# that prevent some errors (like by refactoring) it could be nice if we can use nameof in these situations like it was in ASP Core 2

**Comment by pranavkm** [comment]
@hmdhasani thanks we've heard this feedback a few times and would very much like to come up with a solution for it. In the meanwhile, if you turn off the feature, you should be able to continue using `nameof` as before.
