### ISSUE TITLE
Blazor JS interop with webpack: Function cannot be found at runtime - although it is there in browser console

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#24703]
I am using 3rd party libs in my Blazor application (currently only moment.js for demo purposes). Together with babel and webpack, I am bundling the 3rd party libs into one JS file.

When running the application I get this error:

![image](https://user-images.githubusercontent.com/888718/89714933-56a7fa80-d9a2-11ea-8335-181ca54ded08.png)

But, as you can see above in the screenshot, in the console window the moment function is there.
Something must be wrong ;-)

The repro cannot be found here:
https://github.com/ChristianWeyer/blazor-jsinterop-repro

Thanks,
-Christian

**Comment by captainsafia** [comment]
@ChristianWeyer What happens if you move the script tag that loads your bundle above the script tag that loads the framework's JavaScript files?

**Comment by ChristianWeyer** [comment]
Hi!
Thanks for this idea - I tried it, but nothing changed in behavior.

**Comment by pranavkm** [comment]
@ChristianWeyer the string passed to the `InvokeAsync` needs to the qualified path of the JavaScript function. In this case, `ThirdPartyLibs.moment().format()` is not only a path but also includes method invocation. Your options are to either write a JS function that allows this be called via JSInterop or use `eval`. We're also considering adding support for JS Object references in the future which might help here.

**Comment by ChristianWeyer** [comment]
How would the eval() call look like here @pranavkm ?

**Comment by pranavkm** [comment]
Possibly: `InvokeAsync<string>("eval", "ThirdPartyLibs.moment().format()");`

**Comment by ChristianWeyer** [comment]
Thanks for the hint. This works.
Looking forward to full JS object refs support.
