### ISSUE TITLE
Long running websockets using IIS

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2470]
_From @garcus on Thursday, April 20, 2017 6:50:20 AM_

I have a problem when I have long running websocket connections open and the server is recycled from IIS (or website stopped). I thought I'd handle closing open websockets in a registered ApplicationStopping handler in ApplicationLifetime but it is never called. As long as I have open websockets I have no way of controlling the recycle-process.

Is this right, or am I missing something? Shouldn't it be possible to either force open websockets to be closed on recycle (as an option) or even better, be able to register a handler with appropriate actions to prevent process from hanging around until all websockets are closed from client side ?

_Copied from original issue: aspnet/WebSockets#169_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, April 20, 2017 7:56:00 AM_

@pan-wang @shirhatti

**Comment by aspnet-hello** [comment]
_From @garcus on Friday, November 10, 2017 10:03:20 AM_

Any chance of finding a solution to this issue ? A workaround perhaps ? 
At this moment I'm forced to script process kill to be able to deploy new websites as the IIS-stopped websites are kept open by long running websocket connections to the kestrel-process.

**Comment by aspnet-hello** [comment]
_From @pan-wang on Friday, November 10, 2017 10:14:42 AM_

As websocket connection holds IIS pipeline, apppool recycling will have to wait for the close of the websocket connection till the apppool shutdown timeout is hit (default 90 seconds). One workaround is to set the timeout value to a smaller value if you have the permission to update IIS apppool settings.

ANCM itself does not listen to IIS AppPool shutdown notification yet and thus will not be able to notify the backend about shutting down.  Will change the design to address this scenario in the future if possible.

**Comment by davidfowl** [comment]
@BrennanConroy should we delete these tests?

**Comment by davidfowl** [comment]
> ANCM itself does not listen to IIS AppPool shutdown notification yet and thus will not be able to notify the backend about shutting down. Will change the design to address this scenario in the future if possible.

@jkotalik is this still true with in proc?

**Comment by jkotalik** [comment]
No, we listen for that.
