### ISSUE TITLE
Unable to Build SignalR on master with visual studio

### ISSUE THREAD

**Issue by tebeco** [dotnet/aspnetcore#24719]
Hello everyone ;)

### Describe the bug
As I am trying to create a branch to ask about a strange behavior that was found in `SignalR` with `IAsyncEnumerable` (`ChannelReader` are ok though), I find myself in a situation where I managed to build this repo throught `build.cmd` but VS seems affected with, lots of razor `testassets` created to make it raise error

eg: generated files for test and error parsing
- side effect 1: makes it impossible to build unrelated SLN > SignalR
- side effect 2: can't run SOME samples
  a sample created with  `dotnet new worker` somehow managed to start while webapi project won't build

### To Reproduce
Follow the docs :
https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
```
> mkdir temp1234
> cd temp1234
> git clone --recursive https://github.com/dotnet/aspnetcore
> cd aspnetcore

> ./eng/scripts/InstallVisualStudio.ps1 -Channel Preview
(had nothing to install)

> npm i -g yarn

> ./restore.cmd
(ok)

> ./build.cmd
(ok)

> cd ./src/signalr/
> ./startvs.cmd

CTRL+SHIFT+B
```

![image](https://user-images.githubusercontent.com/2266487/89735283-a5689980-da61-11ea-96e7-4afe250ae902.png)
These files should never been taken care about during SignalR build especially if these are `testassets` supposed to crash the build :(

![image](https://user-images.githubusercontent.com/2266487/89735165-e1e7c580-da60-11ea-90f1-c57abc61deb1.png)

### Further technical details
- ASP.NET Core version
  `master` (commit `983e7ed635f4d128edce4191b51869bd7be8aced`)

- Include the output of `dotnet --info`
Not sure if relevant here since it's driven by `global.json` / `startvs.cmd` (from the SHA1 given)
```
{
  "sdk": {
    "version": "5.0.100-rc.1.20379.10"
  },
  "tools": {
    "dotnet": "5.0.100-rc.1.20379.10",
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2019 Enterprise Preview 16.8 Preview 1

**Comment by Kahbazi** [comment]
Have you run `git submodule update --init --recursive`?

**Comment by tebeco** [comment]
Hello @Kahbazi 

As shown, I used `git clone --recursive https://github.com/dotnet/aspnetcore` which is supposed to do the same "at clone time"
And you can also see that `restore.cmd` and `build.cmd` worked.

This issue is present only in Visual Studio because these files are `testassets` for "Integration Test" that are expecting "failure".
The issue is that somehow these file would need to be excluded for build to have 0 side effect on other project.

I don't know If there was changes in VS, I updated to 16.8 preview1. I can't tell if 16.6 or 16.7 is affected too

**Comment by pranavkm** [comment]
@tebeco are these projects loaded in your solution? The solution filter for SignalR only loads a subset of projects which does not include Razor. Here's what I see when I run `startvs.cmd`:

![image](https://user-images.githubusercontent.com/174281/89838650-9d236380-db20-11ea-9e58-59228662dae1.png)

**Comment by tebeco** [comment]
I think it's not loaded either no, but VS still seems to build it.

Though i notice it happens only with new sample I added with `dotnet new webapi`

it took me ~1hours to understand that this cannot work any work (`Msft.Anc.App` does not exists because it's this repo)
and i had to pull done every single dependencies just like other samples

Though it seems to still trigger razor build and then these test some how
I can push a fork with a repro if you want

**Comment by tebeco** [comment]
@pranavkm 
(I'm using VS preview 16.8 <== no idea if side effect)

I'm not sure, but now it seems to be ok on master when I build from VS, though if I:
* go to `./src/SignalR/samples`
* `dotnet new console -n Foo"
* Edit `csproj` for `TargetFramework`

What goes really bad / not works:
## Dotnet cli + Slnf
* close VS
* go to "sln folder" level 
* `dotnet add sln ./src/SignalR/samples/Foo`
* edit `slnf` manually by simply adding a JSON line to point to the project
==> does not show at all in solution explorer after on `./startvs.cmd`
==> Attempt to "Add Existing Items" (Project already added in Hidden Folder)

## Using VS UI
(reset previous change to sln / slnf, but still have files from `dotnet new console -n Foo`)
* `./startvs.cmd`
* open Solution Explorer
* Add existing project 
* `./src/SignalR/samples/Foo/Foo.csproj`

What happens:
* Sometime it asks if I want to update slnf, not always (have fun)
* The `slnf` goes really bad in `git diff` => there's some sort of "full reoder", I did not check why / if alphabetic / else ? (maybe @kendrahavens have more info on that)
* I reset almost ALL changes inside `slnf` except this "new line" for that new project, to be sure it's not the source of the bug
* the `sln` only show changes on that new project nothing else
* build from `./build.cmd` works (either from root level or from `./src/SignalR`
* Rebuild all (fails)

now ... for `console` project it CAN works (I had these error on `console` this morning when trying to "GIF it")


But for `webapi`, It seems that in `dotnet/aspnetcore` I have to use `<Reference` for each project I consume instead of relying on `Microsoft.AspNetCore.App`
I basically copy pasted 
* the content of `JwtSample` and removed `Identity` / `StaticFile`
* content of `Programs.cs`
* trimmed `Startus.cs` to `UseRouting` and `UseEndpoint(endpoints => {})` <== not even Controller anymore
* I do confirm the `csproj` contains `<GenerateRazorAssemblyInfo>false</GenerateRazorAssemblyInfo>`

Rebuild all:
All error from previous screenshots
I cannot see any "Razor" project loaded at all

As you can see Studio display no `Project` and I tried to expand `Solution explorer`, I can't see anything suspucious
![image](https://user-images.githubusercontent.com/2266487/89931497-865a3b00-dc0c-11ea-9b06-7054fdb3b0a1.png)

**Comment by dougbu** [comment]
@tebeco we changed a few things in this repo to enable successful command-line builds on machines without Visual Studio 16.8. But, 16.8.0 preview 1.0 _should_ be fine. I for example have 16.8.0 preview 2.0 -- the current public preview version -- and can open and build this filtered solution just fine.

But, `.\startvs.cmd` uses the default version of VS for opening `*.slnf` files which is not necessarily what `.\build.cmd` will choose. Double-check under Help ➡️ About Microsoft Visual Studio while in the IDE. If that's not the version InstallVisualStudio.ps1 updated, change the association.

What's worse is we don't currently have documentation pointing out the 16.7 or 16.8 (we're actually not sure) requirement for building in VS. 16.5 works fine from the command line but we don't have a clear idea of what goes wrong with earlier versions (in part because we tend to be on the bleeding edge of VS versions here). If you're accidentally using an earlier version of VS, please post the text of the errors you hit from the Output window in the IDE before fixing the problem (if you possible).

**Comment by tebeco** [comment]
> I for example have 16.8.0 preview 2.0 -- the current public preview version --

what :D ?
![image](https://user-images.githubusercontent.com/2266487/90312155-899e4100-df02-11ea-8435-0043996d0b7b.png)

I usually use `./eng/scripts/InstallVisualStudio.ps1 -Channel Preview` to enforce the `Preview` channel from `dotnet/arcade` since I do use `Vs Enterprise Preview`, is that a bad idea ?

Regarding the orignal issue, It seems that my last attempt did worked.
Si I'm going to close it. I hope I'll be able to push a branch, originally a repro for a bug found in `Signalr` with `IAsyncEnumerable` :)


Thx a lot for you time here. I'm a bit disapointed that I did not found explicitly the culprit though :(
I suspect that it's a mix of 
* `dotnet/aspnetcore` projects cannot consume `Microsoft.AspNetCore.App` in this specific SLN
* Custom target to use `<Reference`
* few bug around `slnf` that does not save it on `Add existing project` unless i explicitly `Save as Solution Filtter` <== just found today that this is a mandatory `Right click` since `Ctrl+Shift+S` does not save it
* glitches with Roslyn CodeFix in `16.8 preview1`
  * `TaskCancelledException` when I press `Ctrl+.` => Crash Roslyn until Vs is restarted
  * ghost process for `dotnet.exe` when closing Visual => `.vs/` is locked by this
  * Error list is never cleared until VS is restarted + `.vs/` manually deleted <== this caused equivalent issue in almost empty repository and can be a lead

**Comment by tebeco** [comment]
Even though this issue is closed, can someone confirm this :

`dotnet/aspnetcore` sample projects cannot consume `Microsoft.AspNetCore.App` in this specific SLN ?
By this I mean that this won't work : `dotnet new webapi -n Foo`
Add this project to the `sln` and try to build
IIRC the error was something like
`Unable to consume Microsoft.AspNetCore.App`

Which is imported by this `<Project Sdk="Microsoft.NET.Sdk.Web">`
But also, at the same time this meta package is supposed to be the "output artifact" of that repo.
Chicken / Egg pb I suppose ?

**Comment by dougbu** [comment]
> Chicken / Egg pb I suppose ?

Pretty much. This repo defaults to ensuring `Microsoft.AspNetCore.App` is not available because it creates `Microsoft.AspNetCore.App`. We have some special-case `msbuild` code for a few projects that must build against the latest shared framework components but it isn't something I recommend copying.

Easiest thing to test against the very latest is to build this repo with whatever local changes you want, `. activate.ps1` or `. activate.sh`, then create and build projects elsewhere using that environment.

**Comment by tebeco** [comment]
@dougbu 
can you tell me if this `slnf` / branch builds for you ? I think I found out few way to work with new `csproj` in the repo .... but I seriously don't ever ever want to do that again :(

https://github.com/tebeco/aspnetcore/tree/repro-bug-iae-signalr-duplex/src/SignalR

(I'll create a dedicated issue tomorrow for the bug associated with that branch)

**Comment by dougbu** [comment]
Given what I said about ensuring `Microsoft.AspNetCore.App` is not available, why are you adding those projects to your fork❔ That approach is a dead end and I am unable to take the time to help you with it.

**Comment by tebeco** [comment]
Well there's few things mixed up here
* I should have removed it, I just forgot that
* It's a `Remove` because I was trying to enforce the fact someone, something was still throwing explicit error about it
* I THINK (not sure yet), that I have issue when adding `Msft.Azure.SignalR`, probably other transitive that somehow still looks for it

So, yeah I'll remove the `Remove`, I just forgot it was here from few days ago, my bad
