### ISSUE TITLE
New [ApiMethod] attribute?

### ISSUE THREAD

**Issue by Eneuman** [dotnet/aspnetcore#24715]
The [ApiController] attribute was a great addition and made the plumbing smaller when working with APIs. 

However, the attribute can only be set on the controller. Many applications are using MVC together with JQuery today. I.e a MVC view renders a table that then gets populated by using a Ajax call to a method in the same controller.

Since ApiController cannot be used here, it would be awesome if there was a [ApiMethod] attribute that could be used on methods. The attribute should do the same thing as the ApiController does (add model validation and return a ProblemDetails if a exception occurs).

**Comment by pranavkm** [comment]
@Eneuman the behavior for API controllers is produced using a set of conventions. While we do not intend to add support for an `ApiMethodAttribute`, you could do something similar by authoring a convention \ application model provider and executing MVC's conventions:

* https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ApplicationModels/ApiBehaviorApplicationModelProvider.cs
* https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-3.1
