### ISSUE TITLE
Blazor Wasm VS Studio Template starter app with ASP.NET hosted selection is not showing User name after AD B2C authentication

### ISSUE THREAD

**Issue by spkiran** [dotnet/aspnetcore#24711]
Steps followed
1) Created Blazor Wasm app with asp.net hosted check mark.
2) Implement AD B2C hosted security following this article:
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1

3) Run the app. Sign up with giving (Display name, surname, given name, user name). Basically all the names from the default user attributes.
4) Login with the registered user. 
5) Implemented this code in Client Side APP's Startup.cs file

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(AzureADB2CDefaults.BearerAuthenticationScheme)
                .AddAzureADB2CBearer(options => Configuration.Bind("AzureAdB2C", options));
          
            services.Configure<JwtBearerOptions>(
                AzureADB2CDefaults.JwtBearerAuthenticationScheme, options =>
                {
                    options.TokenValidationParameters.NameClaimType = "name";
                });
            services.Configure<IdentityOptions>(options =>
            options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier);

            services.AddControllersWithViews();
            services.AddRazorPages();
        }

6) No user name displayed and its null. Please see the attached screenshot

![Annotation 2020-08-08 180202](https://user-images.githubusercontent.com/10189277/89721333-f44efa00-d9a1-11ea-8979-6ad7715510d6.png)

**Comment by pranavkm** [comment]
Can you try reading the JWT token by copying at visiting http://jwt.ms? Perhaps you have something misconfigured.
