### ISSUE TITLE
Error:  `.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\` was not found

### ISSUE THREAD

**Issue by softworkz** [dotnet/aspnetcore#24729]
### Branch

Current **release/3.1** branch

### Describe the bug

Running the .\Restore.cmd command ends with an error about missing VC props and targets

### To Reproduce

```
git clone https://github.com/dotnet/aspnetcore.git

cd aspnetcore

git checkout release/3.1

git submodule update --init --recursive

.\restore.cmd
```

### Exceptions (if any)
```
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj(31,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import>  declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\IISLib\IISLib.vcxproj(28,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\InProcessRequestHandler\InProcessRequestHandler.vcxproj(30,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\OutOfProcessRequestHandler\OutOfProcessRequestHandler.vcxproj(30,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\RequestHandlerLib\RequestHandlerLib.vcxproj(28,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\CommonLibTests\CommonLibTests.vcxproj(30,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the<Import> declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\CommonLib\CommonLib.vcxproj(28,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
F:\Projects\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\gtest\gtest.vcxproj(31,3): error MSB4019: The imported project "F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

### Workaround

Can be fixed by copying over those files from a Visual Studio installation, e.g.:

```
xcopy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC" ".tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\" /S
```

**Comment by dougbu** [comment]
Two possibilities:
1. You do not have at least VS 16.5 with the components listed in the global.json file installed on your Windows machine
2. You were attempting to build between 407b623cdf44 (four days ago) and 7efec87a141f (merged this morning). Though it wasn't documented during that window, builds failed unless you had at least VS 16.**7** installed with the same components as above.

Please retry with current HEAD commit after confirming your VS installation is up-to-date.

**Comment by softworkz** [comment]
Hi @dougbu,

thanks a lot for replying. I'm afraid, neither 1. nor 2. applies.

This happens when building the `release/3.1` branch, so it can't be 2.


It occurred on both installations we tried. In both cases it was VS 16.6.

It's unlikely due to an incomplete VS installation, because copying the missing files from the Visual Studio installation to that folder could fix it.

**Comment by dougbu** [comment]
Ah, sorry, I misread the original description.

Paths like F:\Projects\aspnetcore\.tools\msbuild\16.3.0-alpha\ are a clear indication machine does not have a Visual Studio installation with the necessary components. The infrastructure wouldn't fall back to the local (`xcopy`-able) `msbuild` installation unless that's the case. See https://github.com/dotnet/aspnetcore/blob/9e635724c00120d0e28be6ae83a76dfe11f06f6c/global.json#L17-L24 for a description of what you need.

You can also look at the options available in eng/scripts/InstallVisualStudio.ps1 to update your particular edition of Visual Studio.

**Comment by softworkz** [comment]
@dougbu 

Hi Doug,

thanks for the explanation, but I'm not sure whether it applies to our (me & my colleague's) case.

Actually we do have the VC components installed, which is why we could fix the problem by copying the missing files from our Visual Studio installation (16.6):

`xcopy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC" ".tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\" /S
`

**Comment by dougbu** [comment]
That copy doesn't make the right Windows SDK available to the build and doesn't make it clear your VS installation is complete enough to be used. Windows SDKs are installed under `C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\` and you should have a couple of directories in there named `10.0.17134.0`.

**Comment by softworkz** [comment]
Oh you're absolutely right - it's the SDK which was not available. It looked like a VS issue..

Thanks a lot for taking the time to help me out!
Kind regards,
softworkz
