### ISSUE TITLE
[SSL/Transport Error] Unable to restore master branch with 5.0.100-rc.1.20379.10

### ISSUE THREAD

**Issue by tebeco** [dotnet/aspnetcore#24722]
Hello everyone ;)

### Describe the bug
As I am trying to restore the repository I'm hit by

```
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream.
```

![image](https://user-images.githubusercontent.com/2266487/89739398-a4933000-da80-11ea-8fb8-a45c1d7923f1.png)

It's the second day in a row it happens, and only at the end of the say, not sure if it's related to an outage or a cache somewhere, or ISP ...
The workaround described bellow only worked for less than 24h I would say, and worked again today

### To Reproduce
Follow the docs :
https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
```
> mkdir temp1234
> cd temp1234
> git clone --recursive https://github.com/dotnet/aspnetcore
> cd aspnetcore

> ./eng/scripts/InstallVisualStudio.ps1 -Channel Preview
> npm i -g yarn
> ./restore.cmd
fails
```
I've just update Windows Insider Dev channel, and I hope there's nothing broken about Certificate :D
Hello everyone ;)

### Describe the bug
As I am trying to restore the repository I'm hit by

```
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception.
C:\dev\github\tebeco\aspnetcore\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream.
```

### To Reproduce
Follow the docs :
https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
```
> mkdir temp1234
> cd temp1234
> git clone --recursive https://github.com/dotnet/aspnetcore
> cd aspnetcore

> ./eng/scripts/InstallVisualStudio.ps1 -Channel Preview
> npm i -g yarn
> ./restore.cmd
fails
```
I've just update Windows Insider Dev channel, and I hope there's nothing broken about Certificate :D

### More digging
It seems to fail on `dotnet tool restore` (At first)
Yesterday I had the exact same issue
* ran `dotnet tool restore`  => takes VERY LONG TIME => same error
* deleted `global.json` => `dotnet tool restore` => went weird because `dotnet/arcade`
* `dotnet nuget locals --clear all` => same issue

### Workaround
Editing `global.json` to use `preview7` (because, well I also use `preview7` on side project)
From:
```json
{
  "sdk": {
    "version": "5.0.100-rc.1.20379.10"
  },
  "tools": {
    "dotnet": "5.0.100-rc.1.20379.10",
...
```
To preview7
```json
{
  "sdk": {
    "version": "5.0.100-preview.7.20366.6"
  },
  "tools": {
    "dotnet": "5.0.100-preview.7.20366.6",
```

At that time `restore.cmd` works and if I `git checkout global.json` and re-run `restore.cmd` it works again.
I don't get it

### Further technical details
- ASP.NET Core version
  `master` (commit `983e7ed635f4d128edce4191b51869bd7be8aced`)

- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/2266487/89739414-d3a9a180-da80-11ea-8d67-4474d1dc68db.png)

### Further technical details
- ASP.NET Core version
  `master` (commit `983e7ed635f4d128edce4191b51869bd7be8aced`)

- Include the output of `dotnet --info`

**Comment by pranavkm** [comment]
This issue was moved to NuGet/Home#9893
