### ISSUE TITLE
RouteConstraints aren't linker friendly

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#24723]
Today RouteConstraints are described by a [RouteOptions.ConstraintMap](https://github.com/dotnet/aspnetcore/blob/983e7ed635f4d128edce4191b51869bd7be8aced/src/Http/Routing/src/RouteOptions.cs#L83). The issue with this approach is the linker doesn't have way to know that these types are activated elsewhere in the system. We need an API that lets us describe adding a constraint that is type safe and lets us describe that we want to preserve constructors:

```C#
public class RouteOptions
{
    public void AddParameterPolicy<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]T>(string text) where T : IParameterPolicy;
    public void AddParameterPolicy(string text, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]Type constraintType);
}
```

This would let the linker know that these constraint types should be kept around.

Here's the current warning:

```
C:\dev\git\aspnetcore\src\Http\Routing\src\ParameterPolicyActivator.cs(93,13): Trim analysis warning IL2006: Microsoft.AspNetCore.Routing.ParameterPolicyActivator.CreateParameterPolicy(IServiceProvider,Type,String): The parameter 'parameterPolicyType' of method 'Microsoft.AspNetCore.Routing.ParameterPolicyActivator.CreateParameterPolicy(IServiceProvider,Type,String)' with dynamically accessed member kinds 'None' is passed into the implicit 'this' parameter of method 'System.Type.GetConstructors()' which requires dynamically accessed member kinds 'PublicConstructors'. To fix this add DynamicallyAccessedMembersAttribute to it and specify at least these member kinds 'PublicConstructors'. [C:\Users\davifowl\source\repos\WebApplication60\WebApplication60\WebApplication60.csproj]
```

**Comment by mkArtakMSFT** [comment]
@davidfowl we don't plan to handle this in 6.0 If you neither, feel free to move to backlog.

**Comment by pranavkm** [comment]
API review:

The API is approved. We we want to prevent users from mutating `Routeoptions.ConstraintMap` since that could again introduce trimmer unfriendly behavior. We think the best way to do this is to annotate the property with `RequiresUnreferencedCodeAttribute` and make a note that says the warning can be suppressed if all they are doing is reading the dictionary.
