### ISSUE TITLE
AmbiguousMatchException: `Area` attribute is required even with folder structure

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#24733]
### Describe the bug
I used [Area folder structure](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.1#area-folder-structure) but still I got `AmbiguousMatchException` for any url.

### To Reproduce
I have this controller in my area:
```
// ~/Areas/Dashboard/Controllers/HomeController.cs
public class HomeController : Controller
{
    public IActionResult Index() => View();
}
```

And this is my HomeController:
```
// ~/Controllers/HomeController.cs
public class HomeController : Controller
{
    public IActionResult Index() => View();
}
```
`UseEndpoints` section:
```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "dashboard",
        pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}"
	);

    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}"
	);	
});
```

The only way to fix this is using `[Area]` attribute.

P.S: if you are going to close the issue and say the `[Area]` attribute is required, please explain what is the point of folder structure then?

### Further technical details
- ASP.NET Core version: 3.1

**Comment by pranavkm** [comment]
MVC doesn't look at folder structures, just the `Area` attribute. You're free to organize it in any directory structure you want (although view lookups would be affected). We've found that using this specific structure is what most of our users found useful, which is why we continue using it.
