### ISSUE TITLE
Microsoft.AspNetCore.Authentication.OpenIdConnect - Unable to change nonce expiration time

### ISSUE THREAD

**Issue by hashmed** [dotnet/aspnetcore#24739]
Hi all. I have created new sample IdentityServer4 (with UI) and consuming MVC Client app, hosting them both locally.
If I try to login with sample user within 15 minutes of opening login page, everything works fine.

However, I am unable to allow users to log in if the login page has become stale (opened for more than default 15 minutes).

I have modified OpenIdConnect configuration in the consuming MVC app by adding these to lines in order to increase remote authentication timeout (correlation cookie) and nonce expiration:
![image](https://user-images.githubusercontent.com/11403710/89792719-3ce2f080-db25-11ea-901d-a90bef3794c4.png)

Inspecting the response in chrome after navigating to login page, the cookie values are correct (24h in future, minus 2h of time zone difference)
![image](https://user-images.githubusercontent.com/11403710/89792770-479d8580-db25-11ea-819f-5e0d58bec217.png)

But if I leave the page opened for more than 15 minutes and try to log in, I get the following error:
![image](https://user-images.githubusercontent.com/11403710/89792813-55530b00-db25-11ea-8407-3a5f8cc35d7f.png)

As if the change was not applied - it is reporting that nonce had expired and showing default lifetime of 15 minutes.

What am I missing here? Where is the mismatch coming from?
I've tried clearing cookies, using incognito, both Chrome and Edge - the result is always the same.

I've already asked question here - https://github.com/IdentityServer/IdentityServer4/issues/4728
but was pointed here by brockallen.

**Comment by blowdart** [comment]
The nonce cookie lifetime is completely seperate to the actual nounce lifetime. 

A nonce lifetime of 15 minutes to complete a login seems quite reasonable. If your users aren't doing it within 15 minutes then that may indicate some usability problems.

The nonce is generated in the Options.ProtocolValidator, which is part of AD's protocol package. That has a nounce lifetime property, so you can extend it that way, I just wouldn't recommend it, especially for something as long as 24 hours.

**Comment by Tratcher** [comment]
More specifically, the cookie timeout is derived from the nonce timeout by default, you need to change the NonceLifetime.
https://github.com/dotnet/aspnetcore/blob/fb5dd8564e53fd9df5fcb8c7970b454b6632d972/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L324

**Comment by hashmed** [comment]
Thank you so much, I've been able to make it work by using nonce lifetime property in Options.ProtocolValidator.

@blowdart 15 minutes does seem quite reasonable time for completing login, that's true, but only if user is actively trying to login at that time.
In my case, active session expires and user is redirected to login page (this can happen in another tab, while user is doing something else). Now, if more than 15 minutes pass, page becomes stale, and login attempts on that page result in an error.

So I'm thinking of extending the nonce lifetime to at least 8h, which would be length of average work shift. That way users would be able to login freely throughout the work day.
Do you think this is a liabilty or security concern? Increasing the lifetime that much?

**Comment by Tratcher** [comment]
How about redirecting them to "your session expired, click here to log in again" page? That's what my bank does.

**Comment by blowdart** [comment]
Yea, was going to suggest the same thing :)
