### ISSUE TITLE
Consider setting no-cache headers when creating a new circuit

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24743]
The fix here is to add the meta tag to the `_Host.cshtml`:

```html
<meta http-equiv="Cache-Control" content="no-store" />
```

The more appropriate fix is to do this as part of the renderer.

**Comment by mkArtakMSFT** [comment]
Closing as we are not sure that this is useful.

**Comment by mkArtakMSFT** [comment]
FYI @javiercn
