### ISSUE TITLE
Remove XunitRunnerVisualStudioVersion from Version.props after Arcade update

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24750]
To get tests running, AspNetCore's versions.props file explicitly specifies a version for XunitRunnerVisualStudio:

https://github.com/dotnet/aspnetcore/pull/24685/files#diff-8b8f08ffbf7b863fb3700c1718eeb4cbR282

Once https://github.com/dotnet/arcade/pull/5908 is merged and an Arcade update is available, this can be removed.

**Comment by dougbu** [comment]
@pranavkm why remove the property when it matches what Arcade provides and keeps all xUnit properties together❔ Arcade doesn't provide versions for many of the xUnit packages we use. And, we have a history of staying ahead of Arcade versions (admittedly, that's not the case for the few xUnit versions Arcade has at the moment).

**Comment by pranavkm** [comment]
I think @dougbu asked me to file this issue - see https://github.com/dotnet/aspnetcore/pull/24685#discussion_r467346468.

**Comment by dougbu** [comment]
Changed my mind on the value
