### ISSUE TITLE
Fail to process migration for postgresql when publish to IIS via web deploy

### ISSUE THREAD

**Issue by howardgod** [dotnet/aspnetcore#24768]
I'm not sure if it related to aspnet core or vs 2019 issue.

Prerequisite:
1. Windows server 2016 
2. IIS 8.5
3. Web deploy 3.6
4. Visual studio 2019 16.8 preview 1.0
5. Blazor WebAssembly App with ASP.Net core hosted
6. PostgresSQL 12

Issue:
I have a blazor webassembly app with postgresSQL need to publish to IIS through Web deploy.
Web deploy without ef migrations, everything works fine.

If I setup migration's db connection string, and do web deploy, it always throw exception with error message "ERROR_INVALID_CONNECTION_STRING"

And I have try several combination of connection string. e.g.
"Host=localhost;Database=test;Username=postgres;Password=secretpassword"
"Host=localhost;Database=test;User Id=postres;Password=secretpassword"

It won't work.

I'm confident that my connection string is valid. Because I use this connection string to make my web app to connect to postgresql both on my local machine and remote server.

I have always try for MySQL, and it won't work either.

However, it will work in SQL server.

So did web deploy's migration only works for SQL server? Or did I miss something?

thank you

Howard

**Comment by Pilchie** [comment]
@ajcvickers @bricelam any ideas here?

**Comment by ajcvickers** [comment]
@Pilchie I believe SQL Server is the only engine supported by Web Deploy. @vijayrkn should be able to confirm?

**Comment by vijayrkn** [comment]
Yes, it supports only SQL server

**Comment by ajcvickers** [comment]
@howardgod We are working on better database deployment from EF Core including cross-platform/cross-database support. We would appreciate your input on https://github.com/dotnet/efcore/issues/19587.

**Comment by howardgod** [comment]
OK, NP.
Thanks for clarifying.
