### ISSUE TITLE
[Blazor] Error: Could not find assembly: Microsoft.AspNetCore.Components.WebAssembly

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#24769]
Hello,

When I publish blazor wasm to azure static website it is giving error: Could not find assembly: Microsoft.AspNetCore.Components.WebAssembly.

It happend only last time I updated project.

I have latest VS 2019, dotnet and blazor nuget packages.

When I run balzor wasm locally it runs perfect.

I checked and found that published blazor.boot.json is different than in bin/release folder, it is missing some assemblies like Microsoft.AspNetCore.Components.WebAssembly.

When I create new blazor wasm project and publish, it has correct blazor.boot.json file including Microsoft.AspNetCore.Components.WebAssembly and another assemblies paired with dlls in framework folder.

I was not able to find reason why publishing is generating less files in framework folder and different blazor.boot.json.

Please help.

![Untitled](https://user-images.githubusercontent.com/40779557/89853229-e0042c00-db5e-11ea-81b1-05cf911aae26.png)

![Untitled2](https://user-images.githubusercontent.com/40779557/89853236-e2ff1c80-db5e-11ea-82e4-21993392bb6e.png)

![Untitled3](https://user-images.githubusercontent.com/40779557/89853241-e4c8e000-db5e-11ea-9a7d-d35ee6a0d660.png)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by Lupusa87** [comment]
Hello, when I create new blazor webassembly app, publish it and browse with IIS I see this issue.

I was wrong up re new app, I had previously created blazor wasm template for preview 7 and it works perfect, not new created app.

I guess this caused latest VS update because nothing else changed and everything was working before that.

My current VS version is 16.8.0 Preview 1.0

I have published new created blazor wasm app [here](https://github.com/Lupusa87/BlazorApp2P7) if it helps, it is not touched, just template.

**Comment by robertsundstrom** [comment]
@Lupusa87 Have you tried to publish to a folder using VS for Mac? I have had success with that before. I will try again once all my tools are working as they should.

**Comment by Lupusa87** [comment]
> @Lupusa87 Have you tried to publish to a folder using VS for Mac? I have had success with that before. I will try again once all my tools are working as they should.

I am working on windows machine.

**Comment by Lupusa87** [comment]
I am closing this issue.

I have managed to solve it but I do not know how because I tried several steps like reinstalling sdks, visual studio, emty nuget cache and etc.

There was somewhere the problem but I do not know where exactly.
