### ISSUE TITLE
Blazor MonoLinker.exe: Need to ship Mono.Cecil.Pdb.dll next to MonoLinker.exe

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/aspnetcore#24765]
MonoLinked.exe is currently being shipped here:
`C:\Users\kiril\.nuget\packages\microsoft.aspnetcore.components.webassembly.runtime\3.2.0\tools\monolinker`
It includes Mono.Cecil.dll but it doesn't include Mono.Cecil.Pdb.dll.

As a result there's a first-chance exception during MonoLinker execution (although seems to be benign it's better to be clean):

```
Could not load file or assembly 'Mono.Cecil.Pdb, Version=0.11.1.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.

  | mscorlib | System.Reflection.Assembly.Load Line 364
-- | -- | --
  | Mono.Cecil | Mono.Cecil.Cil.SymbolProvider.GetSymbolType
  | Mono.Cecil | Mono.Cecil.Cil.SymbolProvider.GetReaderProvider
  | Mono.Cecil | Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader
  | monolinker | Mono.Linker.LinkContext.SafeReadSymbols
  | monolinker | Mono.Linker.LinkContext.RegisterAssembly
  | monolinker | Mono.Linker.LinkContext.Resolve
  | monolinker | Mono.Linker.LinkContext.ResolveReferences
  | monolinker | Mono.Linker.Steps.LoadReferencesStep.ProcessReferences
  | monolinker | Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly
  | monolinker | Mono.Linker.Steps.BaseStep.Process
  | monolinker | Mono.Linker.Pipeline.ProcessStep
  | monolinker | Mono.Linker.Pipeline.Process
  | monolinker | Mono.Linker.Driver.Run
  | monolinker | Mono.Linker.Driver.Execute
  | monolinker | Mono.Linker.Driver.Main
```

I found the source here but I'm not sure it's the latest:
https://github.com/dotnet/blazor/tree/master/src/Microsoft.AspNetCore.Components.WebAssembly.Runtime

@pranavkm

**Comment by pranavkm** [comment]
@sbomer there's an issue in the linker repo that tracks this. Can we figure this out for 5.0? It's fairly unlikely we'll fix this for 3.2.

**Comment by sbomer** [comment]
I couldn't find the related linker issue. I don't know about the `microsoft.aspnetcore.components.webassembly.runtime` package, but the `ILLink.Tasks` does contain `Mono.Cecil.Pdb.dll` alongside `illink.dll` so I expect this is not an issue in 5.0.

**Comment by KirillOsenkov** [comment]
Cool, we can close this issue then. Just for my curiosity, where's the source to ILLink.Tasks?

**Comment by sbomer** [comment]
Here you go! https://github.com/mono/linker/tree/master/src/ILLink.Tasks
