### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Rewrite.Internal.RedirectRule' from assembly 'Microsoft.AspNetCore.Rewrite, Version=3.1.6.0

### ISSUE THREAD

**Issue by keggster101020** [dotnet/aspnetcore#24760]
### Describe the bug
I'm attempting to use create an instance of `RedirectRule` but run into the following exception when doing so through a dependent assembly:

Could not load type 'Microsoft.AspNetCore.Rewrite.Internal.RedirectRule' from assembly 'Microsoft.AspNetCore.Rewrite, Version=3.1.6.0

### To Reproduce

1. Create an ASP.NET Core v3.1 application (we'll call it `A`)
2. Create a .netstandard2.0 class lib (call it `B`)
3. Add a project dependency `A -> B`
4. Install nuget package: `Microsoft.AspNetCore.Rewrite v2.2.0` to project `B`
5. Create a new Middleware in project `B`
6. Instantiate `new RedirectRule("a","b",200)` in the newly created Middleware
7. Register Middleware in project `A`
8. Run solution 
 
### Exceptions (if any)

Could not load type 'Microsoft.AspNetCore.Rewrite.Internal.RedirectRule' from assembly 'Microsoft.AspNetCore.Rewrite, Version=3.1.6.0

### Further technical details
- ASP.NET Core version 3.1
- .netstandard version 2.0
- Visual Studio 2019 v16.7.0

**Comment by pranavkm** [comment]
As part of 3.0, we removed most of our pubinternal types from our API surface. See https://github.com/aspnet/Announcements/issues/377. For 3.x, the type was made internal. 

/cc @jkotalik what's the recommended replacement for this API?

**Comment by jkotalik** [comment]
I believe we recommend calling [RewriteOptions.AddRedirect](https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/Rewrite/src/RewriteOptionsExtensions.cs#L59). Is there any reason why you need to directly instantiate the RedirectRule?

**Comment by keggster101020** [comment]
@jkotalik I ended up calling `RewriteOptions.AddRedirect`, as you mentioned, as a workaround. The reason I was trying to create this directly was because I had a requirement which ended up having me create a custom redirection middleware, but I wanted to utilize `IRule` (and subsequently `RedirectRule()` + other custom IRule impls) still to back my middleware.

**Comment by jkotalik** [comment]
Okay glad that worked as a work around.

Do you still envision a future need to instantiate RedirectRule/RewriteRule? We could consider making those public in a future release, however it wasn't intended for those to ever be publicly consumed.

**Comment by keggster101020** [comment]
I'm fine to continue consuming it through the extension method. 

IMO there might be value in having Redirect/RewriteRule exposed since users can access IRule outside of RewriteOptions. My situation might be a little unique, but the workaround feels a little wonky when looking at it. Since I'm utilizing RewriteOptions only as a wrapper around `IList<IRule>` (I don't have a need for IFileProvider)

Ex:
```csharp

public IList<IRule> GetRules()
{
    // can't create IList<IRule>() when RedirectRule is needed. list.Add(new RedirectRule()) isn't valid
    var options = new RewriteOptions(); 

    options.Add(new MyCustomRule("source", "destination");
    options.AddRedirect("source2", "destination2");

    return options.Rules; 
}
```

Either way, can the nuget package for this be updated as well? Since currently RedirectRule is still exposed under `Microsoft.AspNetCore.Rewrite.Internal`
