### ISSUE TITLE
Add support for msgpack in signalr-client-c++ library

### ISSUE THREAD

**Issue by mprather** [dotnet/aspnetcore#24776]
### Is your feature request related to a problem? Please describe.
We're attempting to incorporate signalr into a c++11 app that will analyze a lot of sensor data. Our goal is to produce a status report page that would allow multiple lab users to view what is occurring on the target linux platform in near real-time.  As a compliment, we also have several analysis tools that can recreate data for replay purposes. These two scenarios allow operators see how sensors are progressing through time.

We've been working with C# demos signalr along with various msgpack libraries to understand the impact of using the protocol. We put together a demo in C# last month and we finally managed to set time aside to start working on c++. In the past week, we started working on a prototype that would incorporate a .net core signalr hub we built earlier and a new c++11 app that would send out update info. We finally got the signalr-c++ client building on both Windows and Linux. The last piece was getting msgpack data integrated into our prototype. Spent the whole day working through serialization issues and server errors... only to finally realize that the c++ client is only setup to work with json.

### Describe the solution you'd like
msgpack support is needed in the signalr-c++ library

**Comment by BrennanConroy** [comment]
Tracking with https://github.com/dotnet/aspnetcore/issues/30494
