### ISSUE TITLE
HTML Parity Colorization

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24774]
Razor allows HTML in and outside of C# and everywhere inbetween. The relationships in where it can and cannot exist pose a huge burden on our syntax classifier in Razor. We could invest heavily in our TextMate grammar variant of colorization and most likely get to a 99% compatibility level; however, that being said it'd be near impossible to upkeep. Given we already have an understanding of the intricacies of HTML we should do the quick fix to colorize these pieces to later enable (when we have C# semantic colorization) a simpler syntax grammar syntax grammar to better interoperate with "something" colorizing them.

- [x] [Semantically color HTML portions of the document (not JavaScript, not CSS)](https://github.com/dotnet/aspnetcore/issues/24483)
- [x] [Fix our CSS colorization](https://github.com/dotnet/aspnetcore/issues/21522)
- [x] Briefly investigate our TextMate grammar. Are there any simplifications we can make?
- [x] Validate https://github.com/dotnet/aspnetcore/issues/24249

**Comment by NTaylorMullen** [comment]
Moving to 16.8-Preview4

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg is there any more to do here?

**Comment by ryanbrandenburg** [comment]
The only thing remaining is to verify https://github.com/dotnet/aspnetcore/issues/21522 once new builds of VS are available, but everything Christian says checks out, so we can call that done and verify it when we do vilification if we're so inclined.
