### ISSUE TITLE
Add support for C#'s "Fully qualify" light bulb in C# sections of a Razor file in VS

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#24778]
The idea behind this issue is to enable users to `ctrl + .` -> fully qualify a piece of C# that is not properly included.

**Comment by TanayParikh** [comment]
Blocked on: https://github.com/dotnet/aspnetcore/issues/25250

Prioritizing that and other tasks, pushing this to preview 4.
