### ISSUE TITLE
[Blazor WASM] global exception handler does not catch unhandled exceptions thrown from fire-and-forget async methods

### ISSUE THREAD

**Issue by brettwinters** [dotnet/aspnetcore#24787]
### Describe the bug
Exceptions thrown from async methods are swallowed without hitting the global handler (i.e. no "gold bar at the bottom of the screen" as reported in [reported here](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-3.1)

### To Reproduce
```c#
<button class="btn btn-primary" @onclick="@(() => NonAsync() )">NonAsync - caught</button>
<hr />
<button class="btn btn-danger" @onclick="Async_1">Async_1 - not caught</button>
<hr />
<button class="btn btn-danger" @onclick="@(async () => await Async_2())">Async_2 - caught</button>

@code{

    //caught by index.html handler
    void NonAsync()
    {
        throw new NotImplementedException();
    }

    //not caught by index.html handler
    void Async_1()
    {
        Task.Run(async () =>
        {
            await Task.Delay(500);
            throw new NotImplementedException();

        });
    }

    //await exception / caught by index.html handler
    async Task Async_2()
    {
        await Task.Delay(500);
        throw new NotImplementedException();
    }
}
```

### Exceptions (if any)
Sync, and special Async cases where I await the result are handled, but in fire-and-forget cases, the exception is swallowed leaving the app in an error state but user/developer are unaware. I would expect that all unhandled exceptions should be caught by the global handler

### Further technical details
- Blazor WASM 3.2.0
- .NET Core SDK Version:   3.1.400
- VS 16.7.0

**Comment by pranavkm** [comment]
Exceptions thrown from async void methods are unobserved. This is a behavior of .NET and isn't Blazor specific. We recommend not doing this or using your mechanism to bubble up exceptions from such methods.
