### ISSUE TITLE
Add Forwarded header to known headers

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#24788]
[RFC 7239 - Forwarded HTTP Extension](https://tools.ietf.org/html/rfc7239)

> The "Forwarded" HTTP header field is an OPTIONAL header field that,
   when used, contains a list of parameter-identifier pairs that
   disclose information that is altered or lost when a proxy is involved
   in the path of the request.

**Comment by Tratcher** [comment]
Probably not until we have an implementation in the repo that uses it.

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/5978
