### ISSUE TITLE
Could you expose the classes about Quic as public

### ISSUE THREAD

**Issue by kerryjiang** [dotnet/aspnetcore#24782]
Right now, the classes about Quic like QuicListener, QuicConnection and QuicStream are internal.

Do you have a plan to change their access modifier to public? It allows some other libraries to use these classes.

**Comment by gfoidl** [comment]
For reference: https://github.com/dotnet/aspnetcore/issues/15271
Maybe this gives you the information you look for.

**Comment by kerryjiang** [comment]
OK, let me follow that thread.

Thank you!
