### ISSUE TITLE
no standard authorization on Server-Side Blazor

### ISSUE THREAD

**Issue by Drak0sha13** [dotnet/aspnetcore#24785]
### Is your feature request related to a problem? Please describe.
I have a non-standard authorization. Each user has a list of pages that they can visit. This list may change during execution, of course. The "Index" page can also be blocked. 
I decided to make a Middleware class, but it only helps for "**Index**" pages and pages specified via the browser's address bar, for the rest of the pages I get "/_blazor...". 
there is no protection from the developer here, the developer may forget to hide the link.
 I found "**NavigationManager.NotifyLocationChanged**". This is a centralized place where I can see which page the user requested before calling "**NavigationManager.LocationChanged**". I would like to check the availability of access rights to this page at this point and return 403 or 302. But there is no method redefinition in this class. The "**RemoteNavigationManager**" class is also hidden and there are no overrides. The CircuitHost class strongly references "**RemoteNavigationManager**". 
The next place is **Router** and **AuthorizeRouteView** class, where I can do this, but again there is no override. I need to write again. Is there a way to simplify this task?

### Describe the solution you'd like
I think the best place for this task is to implement **MyRemoteNavigationManager**, via the new "**IServerNavigationManager**" interface.

### Additional context
I wouldn't want to write my own "**AuthorizeView**"on every page. I would like to do authorization in one place before calling "**Navigation Manager.LocationChanged**". 
_I'm sorry about the automatic translation._

**Comment by pranavkm** [comment]
We generally do not recommend rolling your own authorization. However, if you must, you could either create your own `AuthorizedRouteView` component. You could also use the `AuthenticationState` cascading parameter as documented in https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1#notification-about-authentication-state-changes.
