### ISSUE TITLE
Working with accentuated letters give unexpected results

### ISSUE THREAD

**Issue by csillagd** [dotnet/aspnetcore#24783]
Hi!
My test project is a Blazor WASM 5.0.0-preview.7.20365.19. 
The following (example) code does not operate correctly when I try to work with accentuated letters.

    void example()
    {
        var mystrings = new List<string>();

        mystrings.Add("Aladár");
        mystrings.Add("Béla");
        mystrings.Add("Éva");
        mystrings.Add("Kovács Béla");

        var finded = mystrings.FindAll(x => x.ToLower().StartsWith("bé"));

        Console.WriteLine(finded[0]); //the output is: B鬡
    }

The expected output is "Béla", not "B鬡". The above code with Blazor WASM 3.2.1 works correctly.

Thank You!

**Comment by pranavkm** [comment]
Localization and globalization are unavailable in preview7, this could very well be a result of that. The other possibility is that your file's encoding is incorrect. I'll recommend waiting for preview8 to see if this is fixed if encoding isn't the issue. If you continue seeing it after upgrading to preview8, please file a new issue and we'll investigate.
