### ISSUE TITLE
VS inserts unwanted csproj items when copy/pasting .razor.css files

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#24790]
I have a project with some `.razor.css` files. When copy-pasting them (e.g., to duplicate the file with a new name), it adds unwanted junk to the csproj. Currently I have got the following, which breaks compilation and has to be removed manually:

```xml
  <ItemGroup>
    <None Remove="Pages\AllGrid.razor.css" />
    <None Remove="Pages\Grid - Copy - Copy.razor.css" />
    <None Remove="Pages\Grid - Copy.razor.css" />
    <None Remove="Pages\Grid.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\AllGrid.razor.css" />
    <Content Include="Pages\Grid - Copy - Copy.razor.css">
      <DependentUpon>Grid - Copy.razor.css</DependentUpon>
    </Content>
    <Content Include="Pages\Grid - Copy.razor.css">
      <DependentUpon>Grid.razor.css</DependentUpon>
    </Content>
    <Content Include="Pages\Grid.razor.css" />
  </ItemGroup>
```

**Comment by pranavkm** [comment]
@NTaylorMullen \ @ajaybhargavb do you happen to know how this needs to be resolved?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen \ @ajaybhargavb do you happen to know how this needs to be resolved?

Oh goodness, no idea. We'll have to query others who have more context.

@davkean is this on the CPS front that handles this?

**Comment by davkean** [comment]
To avoid unexpected behavior, VS is trying to avoid including a file multiple times in both None/Content. Looks like the SDK has them included under globs in None.

What is the end result you are expecting? And what Item do you expect these css files to be under?

**Comment by SteveSandersonMS** [comment]
We expect the csproj not to include any explicit references to these files individually.

The desired UX is the same as when copy/pasting a `.cs` file in VS's Solution Explorer - it doesn't add anything to your csproj.

Do you think the problem is in the SDK with how it matches them with globs? Is there a recommended pattern we should follow for populating itemgroups in a different way to avoid having VS think it should update the csproj when copy/pasting items?

**Comment by davkean** [comment]
It's hard to tell, can you paste the entire project? How did you add first css file originally?

VS has a few rules:

1) It tries to avoid including a file more than once; that is the `<None Remove="" />`
2) It maintains the "item type" when you copy and paste, that will be the reason the "- Copy" files have an item type of `<Content/>`

I can't tell why the first <Content /> item was added. Our defaults have [CSS as "Content"](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ProjectItemsSchema.xaml#L27) which probably disagrees with the SDK you are using.

**Comment by SteveSandersonMS** [comment]
Sure, I'm using .NET 5.0.100-rc.1.20407.13 and VS 16.8.0 Preview 1.0, and here's my entire csproj before adding any `.razor.css` files:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AnalysisLevel>4</AnalysisLevel>
  </PropertyGroup>

</Project>
```

FYI this project was created via `dotnet new blazorserver` using the 5.0.100-rc.1.20407.13 SDK.

Weirdly I can no longer repro this problem at all. I've tried creating `.razor.css` files in a bunch of places and copy/pasting them, renaming them, and today it's not adding anything to the csproj. It's hard to think of what I was doing wrong before that should legitimately have resulted in that content being added to my csproj, but without being able to repro it I can't really make any more concrete statement.

@davkean @javiercn Unless either of you have ideas for what might repro this, I propose just to close it. If others encounter the issue perhaps they will discover repro steps.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS should we close this now

**Comment by javiercn** [comment]
No, we are investigating this.

**Comment by SteveSandersonMS** [comment]
When resolving this, please check if https://github.com/dotnet/aspnetcore/issues/25841 is also resolved as I think it's the same underlying cause.

**Comment by zHaytam** [comment]
Not sure if this will help but, the issue doesn't only occur when copy/pasting css files, but also when creating them.  
I just created a new project using .net 5 rc1, and I'm not sure when exactly the issue started, but right now whenever I create a new css file that is supposed to become scoped, the csproj file gets updated with content such as:
```
<ItemGroup>
    <Content Remove="Components\DiagramContainer.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\DiagramContainer.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <Watch Remove="Components\DiagramContainer.razor" />
    <Watch Remove="Components\DiagramContainer.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\DiagramContainer.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\DiagramContainer.razor" />
  </ItemGroup>
```

I'm still unsure how to reproduce this at 100%.

**Comment by SteveSandersonMS** [comment]
OK, I looked into this and found it has nothing to do with Blazor or the Razor SDK. I can repro the same problem with plain old `.cs` files in a default new Console Application project. So I think it's purely a VS issue.

### Repro steps, based on VS 16.8.0 Preview 3.1:

1. Create a new .NET Core C# Console Application project
2. In Solution Explorer, select `Program.cs`
3. Press Ctrl+C then Ctrl+V. This will create a new file called `Program - Copy.cs`
4. Select `Program - Copy.cs` and right-click then choose *Rename*
5. Enter the new name `Program.cs.blah` (or any other `.cs.*` extension) and press enter
6. Look at your `.csproj` (after File -> Save All or doing a build gesture)

Expected: `.csproj` remains clean and tidy with no extra entries compared with when the project was first created
Actual: VS has added the following:

```xml
  <ItemGroup>
    <None Remove="Program.cs.blah" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.cs.blah" />
  </ItemGroup>
```

### Demo video

![vs_copy_paste_bug](https://user-images.githubusercontent.com/1101362/94149958-7622b600-fe70-11ea-85b6-a5e25c7eddd6.gif)

### Why this matters

1. It's bad to produce nonsense in the csproj that developers have to revert manually or might accidentally commit to source control.
2. When the `csproj` contains these bogus `<Compile>` entries, it causes any number of problems in the SDK. For example, if you have an extra entry for `SomeFile.razor.css`, then the Razor SDK will give a compile error saying you have a duplicate `.razor.css` file entries.

@davkean Can you suggest where would be best to report this? Is this part of the project system something that you work on?

**Comment by davkean** [comment]
See my comment here: https://github.com/dotnet/aspnetcore/issues/24790#issuecomment-672826638. This behavior is as per the original design.

- The default SDK has a glob similar to `<None Include="*.*" Exclude="*.cs" />
- When you rename the .cs file to "blah", it tries to maintain the existing item type via `<Compile Include="Program.cs.blah" />`, but if it was to do that - it would now be included in two items; None and Compile. 
- It adds the `None Remove="Program.cs.blah" />` to prevent that.

There is likely something in the default globs for the SDK you are using that that includes .css files in the `None` item, resulting in above.

**Comment by davkean** [comment]
Here is the bug: 

By default, VS says `.css` files end up in the `<Content/>` item type: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/Items/ProjectItemsSchema.xaml#L27. 

The Web inherits the .NET SDK which says that .css files outside of `wwwroot` end up in the `<None />` item. That is the cause.

**Comment by SteveSandersonMS** [comment]
OK, thanks for clarifying. So if I follow this correctly, this issue will occur when a developer:

 * Copy/pastes a `.css` file from inside `wwwroot` to outside it (or vice-versa)
 * Or, renames a compile-type file (e.g., `.cs`) to `.css` anywhere

... because in both cases VS is trying to preserve the original file's categorisation. If so, the mechanics of the issue do make sense, so thanks very much for clarifying the details!

To be honest I do question the design of trying to preserve the file type when pasting or renaming. It feels like it's a hangover from an earlier era where project files listed every single item. In the newer world where project files don't list every file explicitly but rather match based on patterns, it's really uncommon for any developer to want to create single-file exceptions to the normal build rules. I personally suspect it's far more common, when renaming a file, that the developer's intent is to change the file type, not to create a special exception where the file has a different type than implied by its extension/location. Apologies if I'm missing awareness of some common cases where people do want that, I just can't think of any from my own experience :smile:

> What item type do you want these css? That will determine the owner of the bug.

I don't want to change the build configuration. If `wwwroot/**/*.css` is historically `Content`, and other `.css` is historically `None`, then I guess that has to remain the case to avoid breaking people's builds.

What I would ideally like is for VS not to try to generate exceptions to these rules implicitly when people perform common gestures like copy or rename. But I appreciate you may have reasons that I don't know about why it's important for VS to do so.

**Comment by SteveSandersonMS** [comment]
@dotnet/aspnet-blazor-eng I'm closing this as external.

**Comment by mkArtakMSFT** [comment]
Filed an [internal issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1248429) to track this.
