### ISSUE TITLE
Feature request: Blazor syntax to exit render block - reduce indentation in large razor files

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#24793]
In complex blazor pages a common pattern is to check that a value is not null before including the markup. This invariably leads to increased indentation which in large pages reduces the general readability.

A typical example is something like:
```
<p>Example</p>
<div>
   @if (Value == null)
   {
     <p>Error - value not initialised</p>
   }
   else
   {
       <div>
           .... Rest of markup
           @if (OtherValue == null)
           {
               <p>Error - Othervalue not initialised</p>
           }
           else
           {
                <more markup / components...
           }
       </div>
       <p>Text 2</p>
   }
</div>
<p>Text1</p>
```

### Proposed feature

The markup indentation can be substantially reduced and made more readable if there was a way to "break", "exit" or "return" from the current render block, i.e. skip the rest of the markup and continue after the current element is closed.

Proposal would be to introduce something like:
```
<p>Example</p>
<div>
   @if (Value == null)
   {
     <p>Error - value not initialised</p>
     @break  <!-- Continue to render Text1 below -->
   }
   <div>
      .... Rest of markup
      @if (OtherValue == null)
      {
          <p>Error - Othervalue not initialised</p>
          @break  <!-- Continue to render Text2 below -->
      }
      <more markup / components...
   </div>
   <p>Text 2</p>
</div>
<p>Text1</p>
```

**Comment by NTaylorMullen** [comment]
Hi thank you for your feedback this is not a feature we plan on adding. That being said if it garners enough attention it's something we may consider in the future.
