### ISSUE TITLE
ASP0000 link is incorrect

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#24807]
https://github.com/dotnet/aspnetcore/blob/a738d1ccfba4e6fcf7927a1a04cdbb52ff28610d/src/Analyzers/Analyzers/src/StartupAnalyzer.Diagnostics.cs#L31

the link is https://aka.ms/AA5k895 which goes to https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2 and that's not helpful.

It should go to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#ASP0000 which will work after https://github.com/dotnet/AspNetCore.Docs/pull/19468 merges. You can see it now at [this link](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1&branch=pr-en-us-19468#ASP0000)

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT can you update the link to https://aka.ms/AA5k895  to go to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#ASP0000 ?

**Comment by Pilchie** [comment]
@Rick-Anderson I added myself and you to the security group that owns most of the ASP.NET Core doc links, but I don't see that one.  It may be propagation delay of the group though.

**Comment by mkArtakMSFT** [comment]
That one is owned by @rynowak. I've asked him to transfer the ownership, but he's away at the moment. Will fix the link as soon as the ownership is fixed.

**Comment by mkArtakMSFT** [comment]
@rynowak has transfer the ownership and I've fixed the link.
