### ISSUE TITLE
Publish Blazor Web Assembly to Azure - not working

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#24803]
Using Microsoft Visual Studio Enterprise 2019 Preview - Version 16.8.0 Preview 1.0

![image](https://user-images.githubusercontent.com/8482283/89937642-a9d5b380-dc15-11ea-83ac-56de2a9bf917.png)

I tried other settings which allow me to publish but the app is not working afterwards.

**Comment by captainsafia** [comment]
@vijayrkn It looks like the validation on the target runtime doesn't allow the user to set the target runtime to `blazor-wasm` when publishing to Azure. Do you have any insight on this?

**Comment by captainsafia** [comment]
@pranavkm Can you check to see if we have a CTI scenario for this?

**Comment by vijayrkn** [comment]
@captainsafia - The fix needs to be on the VS side. We currently block all non-windows RIDS to App Service windows. Can you please create a VS bug for this?

**Comment by vijayrkn** [comment]
@anvillan - FYI

**Comment by anvillan** [comment]
Ok. I will take a look.

**Comment by Postlagerkarte** [comment]
@captainsafia @anvillan : Is there an immediate workaround so that I at least get my app published or do we have to wait for a fix?

**Comment by vijayrkn** [comment]
You can manually update the RID in the backing file under properties\publishprofiles\profilename.pubxml. You can find the property name by setting any other value from the UI.

**Comment by captainsafia** [comment]
Closing as this is external and was resolved in 16.8 Preview 2.
