### ISSUE TITLE
[Feature Request] Add dependecy managment for Razor Class Libraries

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#24801]
Often Razor Class Libraries enforce users to add libraries css, js files to html

### Describe the solution you'd like
Provide mechanism for injecting Razor Class Library dependencies without enforcing user to add it directly

### Additional context
I have already implemented small solution and use it internally for my libraries, but it would be nice if it would be supported by Blazor WebAssembly https://github.com/redradist/BlazorDependencies

**Comment by javiercn** [comment]
@redradist thanks for contacting us.

It might be tempting to try and inject scripts automatically, as it looks straightforward for simple cases. However, there are many challenges that arise from importing resources automatically in the general case. 

Importing assets automatically is a very complicated problem that has to deal with same of the similar concerns that package managers have to.
For an automatic "import system" you need to take into account:
* Order of the files within a given package/project.
* How to handle conflicts between packages importing different versions of the same library.
* Order of the files between packages/projects.
* How to handle when multiple assets are available as options in the package.
* etc.

Our approach is to simply make all the assets available to you at build and publish time and to give you control over what content you bring into your app and how.

For the reasons described above, this is not something we plan to do at the moment. This might not be what you are expecting to hear, but we hope you understand that we don't think this is a problem we should necessarily solve and that it would take resources away from other features we think will help more users. In the end, a mechanism like this can be implemented on top of the support we provide as you did within your package.

**Comment by redradist** [comment]
> 
> 
> @redradist thanks for contacting us.
> 
> It might be tempting to try and inject scripts and other resources automatically, as it looks straightforward for simple cases. However, there are many challenges that arise from importing resources automatically in the general case.
> 
> Importing assets automatically is a very complicated problem that has to deal with same of the similar concerns that package managers have to.
> For an automatic "import system" you need to take into account:
> 
>     * Order of the files within a given package/project.
> 
>     * How to handle conflicts between packages importing different versions of the same library.
> 
>     * Order of the files between packages/projects.
> 
>     * How to handle when multiple assets are available as options in the package.
> 
>     * etc.

@javiercn Yes, I know all this issues and ...

>     * Order of the files within a given package/project.
I have implemented order of dependencies between packages

>     * How to handle conflicts between packages importing different versions of the same library.
User in conflict situation will need to insert script and css directly

>     * Order of the files between packages/projects.
See above, I have implemented order of dependencies between packages

>     * How to handle when multiple assets are available as options in the package.
I have also implemented it

And if you will add dependency managment in Blazor WebAssembly directly then we could eliminate .json file as I have created

> 
> For the reasons described above, this is not something we plan to do at the moment. This might not be what you are expecting to hear, but we hope you understand that we don't think this is a problem we should necessarily solve and that it would take resources away from other features we think will help more users. In the end, a mechanism like this can be implemented on top of the support we provide as you did within your package.

It will not take resources away, because I have already implemented most of the features in https://github.com/redradist/BlazorDependencies
You just need to take my implementation
