### ISSUE TITLE
Built in Swipe Gestures for Blazor

### ISSUE THREAD

**Issue by bsuruncle** [dotnet/aspnetcore#24805]
Have the ability to swipe without implementing your own JavaScript

**Comment by captainsafia** [comment]
@bsuruncle Have you tried integrating a third-party JavaScript library for swipe gestures? Have you had any issues with the integration that made this difficult?

**Comment by bsuruncle** [comment]
I have implemented a working swipe gesture using JavaScript. The issue I have come across is that it is not compatible with some DevExpress components, I have reached out to them for this.

I asked about built in swipe gestures as Blazor is branding itself as not needing to use JavaScript.
[cid:image001.png@01D670A7.89039110]

**Comment by captainsafia** [comment]
Thanks for elaborating, @bsuruncle. We don't plan on adding built-in support for swipe gestures into the framework at this time. We'd recommend implementing/leveraging community components for this.
