### ISSUE TITLE
Error using Azure AD B2C Flow in Blazor WebAssembly using Twitter Identity Provider

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspnetcore#24811]
### Describe the bug
When setting up Azure AD B2C support for a blazor app, we are getting the error below when selecting the Twitter Identity Provider, the flow works when using Facebook Identity Provider, but not when using Twitter Identity Provider.

"Refused to frame 'https://api.twitter.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"

### To Reproduce
1. Follow the steps at: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1

2. Setup Facebook and Twitter Identity Providers for the Azure B2C Flow

3. Try log in selecting the Twitter Identity Provider.

Ahuthentication happens but, the console shows the error message below and redirection does not happen
"Refused to frame 'https://api.twitter.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by captainsafia** [comment]
@efonsecab Thanks for reporting this issue! We'll investigate this and get back to you.

Note: we are currently working on updating the MSAL.js dependency in Blazor which should affect this scenario moving forward.

**Comment by captainsafia** [comment]
@efonsecab Hello Eduardo! I've been able to successfully integrate a social auth scenario (Github auth) after our upgrade to MSAL v2. I'd recommend you try this with RC1. You can find nightly builds [here](https://github.com/dotnet/installer#installers-and-binaries).

If you run into issues with the latest build, please open a bug and let us know!
