### ISSUE TITLE
[Helix] dotnet-watch and templates tests rely on sdk version runtime being installed

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#24825]
As part of switching to only using built in sdk support, it uncovered that dotnet-watch functional tests and the project template tests require the runtimes from the sdk to pass.  The PR originally would only link the sdk and install the runtime, these two tests were the only ones that failed without also symlinking the runtimes from the sdk

Specifically, these tests do not work against only the latest aspnet runtime bits + sdk, it'd be nice to fix this so we don't have to link the sdk included runtimes (assuming this behavior is not expected)

See https://github.com/dotnet/aspnetcore/pull/24287

**Comment by dougbu** [comment]
> it uncovered that dotnet-watch functional tests

dotnet-watch tests still need the SDK's runtimes because they target `netcoreapp3.1`. Some of the Razor tests are in the same boat.

> the project template tests require the runtimes from the sdk to pass

This is no longer true.

**Comment by dougbu** [comment]
Unless `dotnet watch`, lots of Razor, and their tests, move out of dotnet/aspnetcore, this issue is is not actionable. Suggest closing.
