### ISSUE TITLE
MARS TDS header contained errors

### ISSUE THREAD

**Issue by meirib** [dotnet/aspnetcore#24831]
Microsoft.AspNetCore.Identity.EntityFrameworkCore V3.1.6

This error occurs spontaneously:
**Microsoft.Data.SqlClient.SqlException** (0x80131904): The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.

**Comment by blowdart** [comment]
@ajcvickers

**Comment by ajcvickers** [comment]
@meirib Please file an issue on https://github.com/dotnet/SqlClient and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
