### ISSUE TITLE
Expose `preventScroll` on ElementReference.FocusAsync

### ISSUE THREAD

**Issue by JuanElements** [dotnet/aspnetcore#24852]
Add an overload to ElementReference.FocusAsync that accepts `preventScroll` as an option:

```C#
public static ValueTask FocusAsync(this ElementReference elementReference, bool preventScroll);
````

----------------------------------

 I should probably add a new issue for this but I think FocusAsync() should also include `preventScroll` flag

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus

------

### Describe the bug
On Blazor server side, when you apply autofocus on your inputs the attribute is not being respected:

- At the first time, you can see the `autofocus` being applied but loses it after the page fully load
- When you use the navigation bar the `autofocus` is not applied at all

### To Reproduce
Create a page with the followin code:
```html
<input type="text" name="name" />

<input type="text" name="name1" autofocus />
```

Expected: If you don't do anything while the page loads the autofocus must be aplied

**Comment by pranavkm** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/17472

**Comment by barahonajm** [comment]
I am seeing every issue related with this closed so just to make it clear:

We are going to have a new API that lets us focus by calling `ref.FocusAsync()` but we will not be able to add `autofocus` to our normal html elements because it will not work?

**Comment by pranavkm** [comment]
@barahonajm sorry I meant to reopen the other issue. You are correct in your summary though.

**Comment by barahonajm** [comment]
Got it, I believe normal html functionality like `autofocus` should be preserved but I know it is hard so at least `FocusAsync` solves the problem.

 I should probably add a new issue for this but I think FocusAsync() should also include `preventScroll` flag

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus

**Comment by pranavkm** [comment]
We can repurpose this issue to track adding that option.

**Comment by pranavkm** [comment]
FYI @MackinnonBuck

**Comment by ryanclarke** [comment]
Do you like the proposed implementation of adding a `bool preventScroll` parameter to the method? Do you prefer an overload method or a optional parameter?

**Comment by pranavkm** [comment]
@ryanclarke we would want a new overload. Modifying the current method would be a breaking change which we want to avoid.

**Comment by ryanclarke** [comment]
I'll start working on this enhancement. Thanks for your help.

**Comment by ryanclarke** [comment]
Just to clarify, since the nature of this issue seems to have changed over time.

Solving this issue should not mess with `autofocus`, it should simply add a `preventDefault` `boolean` parameter to an new overload of `FocusAsync`.

Acceptance criteria is that focusing on an off-screen element using this new method would not scroll the page.

**Comment by ryanclarke** [comment]
I'm not going to have the time to work on this. Sorry. Anyone else can take it.

**Comment by propil5** [comment]
I will start working on this.

**Comment by KonstantinAlexeevich** [comment]
I want to try, if it possible

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/28686
