### ISSUE TITLE
Blazor InputDate Error in FireFox

### ISSUE THREAD

**Issue by frablaser** [dotnet/aspnetcore#24854]
I use an InputDate control as:
```
                    <div class="form-group">
                        <label for="@("Birthdate" + usr.UsrId.ToString())">@L["lblBirhdate"]</label>
                        <InputDate @bind-Value=usr.PusrBirhdate class="form-control" id="@("Birthdate" + usr.UsrId.ToString())" @onkeypress="OnDateKeyPress" required/>
                        <ValidationMessage For="() => usr.PusrBirhdate" @Required="true" />
                    </div>

``` 

### Describe the bug

When I press the number: 0  in any date fields, it try to validate the date as in this example, the mouth as: 00

![image](https://user-images.githubusercontent.com/29067539/90065601-89136980-dcba-11ea-956e-abb0578d4cb8.png)

I get as soon as the keypress is done, an unhandled error exception as 

![image](https://user-images.githubusercontent.com/29067539/90065870-ed362d80-dcba-11ea-9823-2d4bf32ccd05.png)

```
System.InvalidOperationException: InvalidCharacterError: String contains an invalid character
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)


```
### To Reproduce
Insert an InputDate in a Blazor page, Open it in a Firefox browser.
`<InputDate  class="form-control" id="Birthdate" required/>`

Run it, insert a 00 for the month by typing only 0

### Exceptions (if any)
System.InvalidOperationException: InvalidCharacterError: String contains an invalid character
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

### Further technical details
- ASP.NET Core version 3.1.3
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version : VS 2019 Version 16.7.1

**Comment by captainsafia** [comment]
This issue is actually a little different from the other date input bug reports that I've seen.

@frablaser Can you upload your repro to a GitHub repo?

**Comment by frablaser** [comment]
Hi CaptainSafia,

Note that I use the FluentValidation, it could be where it bumping into...

Here is the github: [https://github.com/frablaser/ErrorDateFireFox](https://github.com/frablaser/ErrorDateFireFox)

**Comment by frablaser** [comment]
Ho I forgot to say that could be have something to see with the french format yyyy-MM-dd, the inputdate could not handle the "-" may be? Or it comes from a very very hold Mozilla International date handling error...?!

In the other hand, I tried to set the format as : @bind-Value:format="yyyy/MM/dd" to get ride of the wrong character error, but nothing, rien, nada, that still following the OS format... 🙄

**Comment by frablaser** [comment]
Finally, I found the problem, it was the damned @Required="true" who fail with the FluentValidation...  You can clode it...

**Comment by captainsafia** [comment]
Glad you tracked down the issue! Closing this now.
