### ISSUE TITLE
AmbiguousMatchException: The request matched multiple endpoints. Matches

### ISSUE THREAD

**Issue by Varorbc** [dotnet/aspnetcore#24865]
### How do I configure the routing template, so I can be browse the below url?

/weatherforecast/getlist
/weatherforecast/getlist?id=1

```
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet("GetList")]
        public int GetList()
        {
            return 2;
        }

        [HttpGet("GetList")]
        public int GetList(int id)
        {
            return id;
        }
    }
}


```

**Comment by javiercn** [comment]
@Varorbc thanks for contacting us.

You have two ambiguous routes. Routing doesn't look at the query string to disambiguate. We suggest you check [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-precedence-and-endpoint-selection-order) for details.

**Comment by Varorbc** [comment]
@javiercn If I configure as follows, I cannot browse the url  with '?id'

```
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet("GetList")]
        public int GetList()
        {
            return 2;
        }

        [HttpGet("GetList/{id}")]
        public int GetList(int id)
        {
            return id;
        }
    }
}


```

**Comment by javiercn** [comment]
That's because you have two routes
```
WeatherForecast/GetList
WeatherForecast/GetList/{id}
```

Your solution might be 
```
namespace WebApplication1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet("GetList")]
        public int GetList([FromQuery] int? id)
        {
            return id ?? 2;
        }
    }
}
```

**Comment by Varorbc** [comment]
it requires users to do logic processing work. It worked well in asp.net.  but now I can’t browse directly after upgrading to asp.net core. Is there a better solution?

**Comment by javiercn** [comment]
@Varorbc The old web api convention routes are not part of the current MVC routing conventions. You can implement what you need through routing extensibility or by implementing your own `IActionConstraint`

**Comment by Varorbc** [comment]
This kind of browsing with '?' Is a very common browsing, and also conforms to the HTTP protocol. Can it be implemented in the current routing conventions.?

**Comment by javiercn** [comment]
@Varorbc unfortunately not, changing the default routing conventions would be a huge breaking change for all our existing customers, so this is not something we plan to do.

As we said, the extensibility is there if you want to implement your own Web API-like routing conventions.

**Comment by Varorbc** [comment]
@javiercn This is a very meaningful thing, method overloading is also very common, I hope you can consider compatible upgrades and join the plan. For the huge breaking change you mentioned, I think it does not exist, because existing customers will not have the same routing template.
