### ISSUE TITLE
Replace the default Blazor favicon.ico with something better.

### ISSUE THREAD

**Issue by tomironkko** [dotnet/aspnetcore#24863]
### Default favicon.ico too bland
While developing and having many tabs open in browser, the default favicon of the wasm template is too light in color and is very easily missed, and in general, bland looking.

### Solution
Default templates favicon.ico to be replaced with something more colorful, maybe even with the Blazor icon, or similar.
### Screenshot
This is the current template favicon.ico:
![image](https://user-images.githubusercontent.com/30999998/90107493-8dd72c80-dd51-11ea-8ea5-5bb7e7c16b20.png)

**Comment by javiercn** [comment]
@tomironkko thanks for contacting us.

We haven't heard enough feedback about this being a problem so it is unlikely we prioritize, but we will reconsider if we hear significant demand for it.
