### ISSUE TITLE
DirectoryNotFoundException: microsoft.aspnetcore.identity.ui\3.1.5\staticwebassets\V4\

### ISSUE THREAD

**Issue by chucklu** [dotnet/aspnetcore#24869]
might related to https://github.com/dotnet/aspnetcore/issues/19292

### Describe the bug
Encounter the exception DirectoryNotFoundException: microsoft.aspnetcore.identity.ui\3.1.5\staticwebassets\V4\, however I have verified the directory exists. How could it be possible asp.net core can not find the existing directory？

### To Reproduce
Have no idea how to reproduce, just encounter the problem. Just create a IIS application, and set the physical path to the site source code

### Exceptions (if any)
```
> DirectoryNotFoundException: C:\Users\username\.nuget\packages\microsoft.aspnetcore.identity.ui\3.1.5\staticwebassets\V4\
> Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
> Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root)
> Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider..ctor(string pathPrefix, string contentRoot)
> Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader+<>c.<UseStaticWebAssetsCore>b__2_0(ContentRootMapping cr)
> System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.MoveNext()
> System.Linq.Enumerable.OfTypeIterator<TResult>(IEnumerable source)+MoveNext()
> System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
> System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
> Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
> Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
> Microsoft.AspNetCore.WebHost+<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
> Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass8_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
> Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
> Microsoft.Extensions.Hosting.HostBuilder.Build()
```

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.400
>  Commit:    035fb2aa2f
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.400\
> 
> Host (useful for support):
>   Version: 3.1.7
>   Commit:  fcfdef8d6b
> 
> .NET Core SDKs installed:
>   3.1.400 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Professional 2019
Version 16.7.0
It works fine if I setup the wbeiste project as startup project and click F5 to run the site through IIS Express.

**Comment by Tratcher** [comment]
That's missing a slash? `C:\Users\username.nuget\` -> `C:\Users\username\.nuget\`

**Comment by chucklu** [comment]
@Tratcher  No, the slash exists, it seems a bug  of github show `C:\Users\username\.nuget `as quote

**Comment by Tratcher** [comment]
Ah, nevermind. Always use ``` for data blocks.

**Comment by javiercn** [comment]
@chucklu thanks for contacting us.

It seems like you are running the app in development on IIS. It might be that the IIS user doesn't have access to that folder?

**Comment by chucklu** [comment]
@javiercn  Thanks, I just grant  iis_iusrs with full control of the .nuget folder, the problem was resolved.
