### ISSUE TITLE
Is there any plan to replace `Json.NET` with `System.Text.Json` in `Microsoft.AspNetCore.NodeServices` package?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#24867]
As we know `System.Text.Json` is default .NET Core app's json serializer atm. so adding `Json.Net`/`Newtonsoft.Json` just because some packages like `Microsoft.AspNetCore.NodeServices` needs it is not good an option. I'm wondering why you didn't replace it yet.

**Comment by javiercn** [comment]
@dehghani-mehdi thanks for contacting us.

Microsoft.AspNetCore.NodeServices is obsolete and we are not currently investing on it. See https://github.com/dotnet/aspnetcore/issues/12890 for the announcement.
