### ISSUE TITLE
[Blazor] Automatically importing static resources inside nuget packages

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#24878]
I know this problem has been commented before, but every time someone tries to use our components it bumps into the problem that the components doesn't find the JavaScript files. 
People is used to install nuget packages and use them. They don't expect having to add things manually to be able to use them. Nuget works seamlessly in every platform but Blazor. It's really annoying having to explain every customer they "forget" to add those references manually.
I know you said this is complicated, but it is really something that must be addressed. I'm sure there are options if there is will to fix it.

**Comment by SteveSandersonMS** [comment]
As of .NET 5, we now have ways that component authors can achieve this.

 * For CSS, if you use scoped CSS files (`MyComponent.razor.css`), then that will be loaded automatically from your RCL without any other steps needed.
 * For JS, if you [import JavaScript modules](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references), this will happen without the RCL consumer having to add any `<script>` tags

These approaches avoid problems with defining the loading order or specifying which subsets of resources are required.

These are the approaches that we plan to enable for now. Hopefully as the community gets used to using them, we'll learn more whether there are any further limitations to solve with them. As such I'll now close this.
