### ISSUE TITLE
[feature request]Compoent tree iterator

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#24873]
Compoent tree iterator. ComponentBase provider api like **GetChildBy<T>(string id)**, **GetChildrenBy<T>()**, GetChildAt(int index)**.

**Comment by javiercn** [comment]
@srxqds thanks for contacting us.

This is not a functionality we plan to offer at the time, you can use Component reference to access a given rendered component instance from a parent component.

**Comment by srxqds** [comment]
OK
