### ISSUE TITLE
@arivoir There are many challenges that arise from importing resources automatically. Importing assets automatically is a very complicated problem that has to deal with same of the similar concerns that package managers have to.

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#24877]
@arivoir There are many challenges that arise from importing resources automatically. Importing assets automatically is a very complicated problem that has to deal with same of the similar concerns that package managers have to.

For an automatic "import system" you need to take into account:
* Order of the files within a given package/project.
* How to handle conflicts between packages importing different versions of the same library.
* Order of the files between packages/projects.
* How to handle when multiple assets are available as options in the package.
* etc.

This is a non trivial problem to solve and we chose not to try and solve it at this point; it is also not likely we try to solve it in the future either. This is also something that is also additive. All the information regarding the static web assets for the app is available at build time and nothing prevents anyone from using that information to create a partial view or set of partial views that automatically import the assets. That said, if you do that then you will have to handle all the concerns above (and possibly more).

Our approach is to simply make all the assets available to you at build and publish time and to let you choose what content to bring into your app.

@michaeldaw I hope this also answers your question. We experimented with the automatic imports in the past, but it turns out its really complicated to get right on the general case, so when we productionized the feature we decided to scope it out.

@arivoir Are you still experiencing any issue here? If so please reopen this issue and provide the following info:
* Is the app a standalone blazor wasm app? (This is a known issue)
* Does the problem repro with the latest preview?
* Can you provide a minimal repro github repo we can clone to further investigate the issue?

_Originally posted by @javiercn in https://github.com/dotnet/aspnetcore/issues/13279#issuecomment-531799402_

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/issues/24878
