### ISSUE TITLE
Blazor (WASM) Failed to find a valid digest in the 'integrity' attribute for resource (caching)

### ISSUE THREAD

**Issue by Kayomez** [dotnet/aspnetcore#24874]
Running the project on my local machine in incognito has no issues. If I go onto the website on my Chrome then there are no issues. If I go onto the website on another browser or in incognito then the page won't load. Telling me it's a caching issue only. I have no idea why that would be.

The project is WASM but it's prerendered on the server first.

Error as shown in Chrome:
`Failed to find a valid digest in the 'integrity' attribute for resource 'https://controltheescape.co.uk/_framework/_bin/Newtonsoft.Json.dll' with computed SHA-256 integrity 'l6nw4t7IpsbpGr2JA9KzOyKZ3lrcSXkeiCu/Ar1R5MU='. The resource has been blocked.
(index):1 Unknown error occurred while trying to verify integrity.
blazor.webassembly.js:1 Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.throw (blazor.webassembly.js:1)
    at u (blazor.webassembly.js:1)`

I don't know how to reproduce this because it's started happening after a release where I made no significant changes (few razor component adjustments)
[This is the site](https://controltheescape.co.uk/)

- .NET Standard 2.1
- Visual Studio 2019

**Comment by javiercn** [comment]
@Kayomez thanks for contacting us.

It is likely that there is something wrong with your deployment, check that the files haven't been modified after publishing or re-deploy again and see if the issue goes away.

**Comment by Kayomez** [comment]
I've deployed multiple times in the same fashion with no difference. I deleted the files manually and then uploaded them to no avail. How can the cache be affecting this?

**Comment by Kayomez** [comment]
I just tried on another device and it won't even work locally, I share the files across OneDrive. Is it possible that could be having an impact?
