### ISSUE TITLE
[question] how to create component when it is realy needed other than define in razor.

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#24871]
define MyDialog.razor
```c#
<div></div>
```

can we create the ** MyDialog** when we need show it, like:

```c#
MyDialog dialog = new MyDialog();
dialog.AddToParent(parent);
```
instead of:
```c#
<parent>
<MyDialog></MyDialog>
</parent>
```

**Comment by javiercn** [comment]
@srxqds thanks for contacting us.

This is not the way Blazor works. The framework is in control of the lifetime of the components. You can use a component reference. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#capture-references-to-components) if you need to get a hold of a child component after the parent application has rendered.
