### ISSUE TITLE
Server-Side Blazor - Images cause significant increase in SignalR Message usage?

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#24887]
We are seeing on Blazor server-Side pages, that have a good number of `<img src="image link" />` tags that the message count for the request goes way up in the backing Azure SignalR Service and really eats into the daily max connections. Was wondering if anyone else has seen this and has any thoughts of how to mitigate this?

Any thoughts are appreciated. Thanks!!

### Further technical details
dotnet core 3.1.4

**Comment by javiercn** [comment]
@chassq thanks for contacting us.

Can you give us more details about how you are using image tags? Are you using regular image links or are you using data urls to serve the images "inline".

There's no reason for regular images to cause an spike like the one you are suggesting is happening.

If you can produce a minimal repro project (a public repo on github is great) that shows the issue, that will allow us to help you further.

**Comment by chassq** [comment]
Hey @javiercn, seems you are correct it does not seem to be the images themselves causing our spike at this time. Going to close this. Thanks for the input!
