### ISSUE TITLE
The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized - Blazor Client with .NET 5.0.0-preview.7.20364.11

### ISSUE THREAD

**Issue by Ibro** [dotnet/aspnetcore#24889]
### Describe the bug
I have an issue in one of my projects that uses Blazor WASM. I can't share the code on GitHub. However, I managed to reproduce it few times.

### To Reproduce
Reproducing the issue with a new application through template is a bit hard. It worked few times for me, but it seems to be rather sporadic.

dotnet new blazorwasm --auth Individual --hosted

Using .NET 5 preview 7, create new Blazor WebAssembly Application, ASP.NET Core hosted, Individual User Accounts authentication.
Add latest preview of Microsoft.AspNetCore.SignalR.Client package to the Shared project:
`<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.0-preview.7.20365.19" />`

Update, I found the cause, it seems to be another package that sneaked into my project references and not SignalR.Client.
` <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.0-preview.7.20365.19" />`

Try to build the application.

https://github.com/Ibro/TestBlazorClient5

### Exceptions (if any)

`Error	NETSDK1073	The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized	TestBlazorClient5.Client	C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets 316`

### Further technical details
- Same issue occurs on both Windows 10 and Ubuntu (WSL 2 hosted).
- ASP.NET Core 5 preview 7
- .NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.6
 Commit:    0684df3a5b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100-preview.7.20366.6/

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  5.0.100-preview.7.20366.6 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

- VS Code / Visual Studio 16.6.5

**Comment by javiercn** [comment]
@Ibro thanks for contacting us.

What you are seeing is normal and by design. You are refencing `Microsoft.AspNetCore.Identity.UI` in your [shared](https://github.com/Ibro/TestBlazorClient5/blob/master/TestBlazorClient5/Shared/TestBlazorClient5.Shared.csproj) project, which is why its being transitively referenced on your client project.

You should limit the references in the Shared project to packages that don't try to pull the AspNetCore shared framework.
