### ISSUE TITLE
Throw build time error for invalid BlazorWebAssemblyLazyLoad property

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#24880]
https://github.com/dotnet/aspnetcore/pull/24866#issuecomment-673571454

**Comment by barahonajm** [comment]
I believe this will need to be implemented as following:
```xml
<Error
    Text="Unable to find $(OutDir)$(_BlazorOutputPath)%(BlazorWebAssemblyLazyLoad.Identity) (are you missing an assembly reference?)"
    Code="RAZORSDK1007"
    Condition="!Exists('$(OutDir)$(_BlazorOutputPath)%(BlazorWebAssemblyLazyLoad.Identity)')" />
```
and be called before `GenerateBlazorWebAssemblyBootJson` right?

If that is the case, I can make PR for this although I don't know what code should put in the error

**Comment by captainsafia** [comment]
@barahonajm Yep -- something like that should do the trick.
