### ISSUE TITLE
Typing self closing component tag results in `@` character being inserted

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#24895]
![npecv1nFEI](https://user-images.githubusercontent.com/1874516/90197950-2044f380-dd85-11ea-87fd-cb600cc40174.gif)

Version 16.8.0 Preview 2.0 [30413.8.master]
Preview Razor editor

@NTaylorMullen

**Comment by TanayParikh** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/23908?

**Comment by NTaylorMullen** [comment]
Nah, this looks like our DirectiveAttributeTransition completion item is being provided too aggressively.

**Comment by NTaylorMullen** [comment]
This looks to still fail in Codespaces scenarios. LiveShare must be doing something interesting to muck with our responses. Tracking issue: https://github.com/dotnet/aspnetcore/issues/26520

**Comment by TanayParikh** [comment]
Literally beat me to it by a second:
![24895](https://user-images.githubusercontent.com/14852843/94873883-4e4dc800-0405-11eb-9320-7194665ef507.gif)

**Comment by NTaylorMullen** [comment]
💪
