### ISSUE TITLE
Remove HTTP/2 pseudo headers from request primary headers

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#24897]
Kestrel now optimizes how it processes request static indexes - https://github.com/dotnet/aspnetcore/pull/24730

HTTP/2 pseudo headers will usually be sent as static indexes so there is no need to have them in the "primary headers" which are checked for first.

**Comment by Tratcher** [comment]
For context, you didn't do this in your PR because the KnownHeaders generated code kept breaking, right?

**Comment by JamesNK** [comment]
Yes. We'll see whether it still happens if it is the only change to KnownHeaders...
