### ISSUE TITLE
SignalR - Multiple Streaming from One Hub Class

### ISSUE THREAD

**Issue by Malayp** [dotnet/aspnetcore#24904]
Hi, 

I have a Hub class, where I have around 5-6 streaming methods. All these methods are steaming huge amount of data.
1. If I am streaming from only one method ( removing all other methods except one ), then its working fine. 
2. But if all those methods are started streaming at a time then its taking a huge amount of time.

**Comment by BrennanConroy** [comment]
Can you provide more info?

If you only stream from one method does that mean you're sending the same amount of data as all 5-6 methods combined and it's faster or you're only sending one methods worth of data?

How much time are we talking? 1 second, 1 minute etc.

How much data are you sending?

Can you provide code?

**Comment by Malayp** [comment]
Hi @BrennanConroy 

Thank you for you response.

If you only stream from one method does that mean you're sending the same amount of data as all 5-6 methods combined and it's faster or you're only sending one methods worth of data?
-> I am sending 5 types of data from different 5 methods and it's difficult to send all these data from one method.

How much time are we talking? 1 second, 1 minute etc.
-> For one method (streaming maximum size 200 MB) is taking 40-50 second, but if all methods stream at a time then its taking around 7-8 minute.

How much data are you sending?
->The minimum data is around : 14MB and the maximum is around : 200MB. Its only for testing but the real time data can be in GB.

Can you provide code?
-> Please find below code

public async IAsyncEnumerable<LogDTO> GetEAsyncStreams([EnumeratorCancellation] CancellationToken cancellationToken)
{
	foreach (var s in eData)
	{
		yield return new LogDTO
		{
		   FormattedData = s.FormattedData
		};
	} 
}

**Comment by BrennanConroy** [comment]
So the issue is you're not really making use of IAsyncEnumerable. Your streaming method is fully synchronous so it blocks other streaming methods from running until it completes. I'd recommend either switching to the ChannelReader example as shown in https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.1#server-to-client-streaming or at a minimum putting an `await Task.Yield();` at the top of your streaming method.

**Comment by Malayp** [comment]
Thank you for your quick replay @BrennanConroy :)

I have tested, for one method it's streaming asynchronously.
According to you I have added `await Task.Yield();` at the top of all streaming methods, but the result is same.

I have also tried using ChannelReader : 
Here I found that, If I am not adding `await Task.Delay(delay, cancellationToken);`, then ChannelReader is acting as synchronous process.

**Comment by BrennanConroy** [comment]
When 1 method is used, you're sending ~200MB in 50 seconds? And when 5 methods are used you're sending ~1 GB in 7 minutes?

In a perfect world you would want all 5 methods to be in parallel and take 50 seconds total?

How fast is your internet connection, how much CPU is the server using in both scenarios?

Can you provide a repro app with fake data?

**Comment by Malayp** [comment]
When 1 method is used, you're sending ~200MB in 50 seconds? And when 5 methods are used you're sending ~1 GB in 7 minutes?
-> Yes

In a perfect world you would want all 5 methods to be in parallel and take 50 seconds total?
-> Yes, That's what I want

How fast is your internet connection, how much CPU is the server using in both scenarios?
-> It's in localhost only, both Server and Client are in same system. Server is using 60% of CPU at max then gradually decreases to 0% when streaming finishes.

Can you provide a repro app with fake data?
-> I am really sorry, I don't have any fake data as such. I sent you a sample of a method, like that only I have 5 methods.

One additional Point:
-> If I separating all methods to separate hubs(5 Hub classes and each hub class has one stream method), then with the same scenario, it's working fine. I mean all streams are completing in expected time.
