### ISSUE TITLE
Support dynamic port in a range for kestrel web server 

### ISSUE THREAD

**Issue by xboxeer** [dotnet/aspnetcore#24903]
### Describe the bug
We have a stackoverflow [threads ](https://stackoverflow.com/questions/63163056/how-do-you-configure-kestrel-to-use-a-random-dynamic-port-from-a-defined-range-o)asking how to config kestrel web server to listen against a range of port dynamicly. I searched our docs only found [this one](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#transport-configuration) . In the docs it said we can use 0 to tell kestrel to listen to a dynamic port, but does that dynamic port has a range? If not, can we add this feature?

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Tratcher** [comment]
Port 0 is implemented by the Socket library, kestrel doesn't implement it directly.

Do you have examples where this is supported by any other server?

**Comment by xboxeer** [comment]
Hi Tratcher,
That's a good point, I did a quick search against different server and different web framwork. looks for server, the only support setting a port staticly in config file. For web framework, spring boot support a ranged port in application.yml like below
`server.port: ${random.int(5000,5100)}`

**Comment by xboxeer** [comment]
@Tratcher to achieve the same in asp.net core kestrel, there seems to be no build in feature either in config or kerstrel extension method. What I come cross is when calling UseUrls, define a random port number using random.next(minPort, maxPort), but this will leads to a port conflict for sure, of course we can use a try catch to capture the port conflict exception and re-generate a random port but that's not seems to be very elegent. Do you think we can implement the same like sprint boot did?

**Comment by Tratcher** [comment]
I don't see how other than internalizing that try/catch loop.

I'd start with asking how much more valuable this is than the existing port 0 support? Is there a functional reason to the range limit or is it asthetic?

**Comment by xboxeer** [comment]
mainly for a multi-instance server side application, if i decide not to use a container cluster solution such as kubernates, my request need to specify the exact port number or port range(can be done in client side), if kesterl can not help me setup a dynamic ranged port, this user cases can not be implmented. I understand for a real complex system, we will usually use k8s to address these issue. but if the system is still at baby step stage, a ranged dynamic port would be very helpful.

**Comment by Tratcher** [comment]
Clients can specify a port range? Can you share an example?

**Comment by xboxeer** [comment]
> We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).


In this reference docs, there is a statement  **Consider asking these questions on StackOverflow.**, what is the so called  _these question_ here?

**Comment by Tratcher** [comment]
That's referring to investigations more than feature requests. Though in this case there would need to be some research on how to implement a port range feature, which the community could help with. Feature requests that include proposals for how to implement them are much easier to evaluate and act on.

**Comment by xboxeer** [comment]
@Tratcher Thanks for explaining. Regarding to the client specify port range in your previous reply, I'm writing one but seems the try catch loop can not address the ranged port issue, I'm looking for a new way to achieve this(Maybe use some api to detect if a port is in use directly)

**Comment by xboxeer** [comment]
> > (Maybe use some api to detect if a port is in use directly)
> 
> We've tried that in our tests but found it too vulnerable to race conditions (e.g. it gets taken just after you check it). Port 0 is the best we've managed because the Socket API can check and reserve the port atomically.

I got your point, I think we can close this one since it's already moved to backlog
