### ISSUE TITLE
[Blazor wasm] User.Identity.IsAuthenticated only in Identity part, cookies present

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#24911]
### Describe the bug
I created project WebAssembly + Sign in via Identity Server. Login + Register works. Blazor signs me in. However in _Host or controller action user is not authenticated. Cookies for sign in are present. If I do breakpoint inside _LoginPartial user is marked as authenticated. I am missing point why its not authenticated outside Identity library.

Startup server
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<DatabaseContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddDefaultIdentity<ApplicationUser>().AddEntityFrameworkStores<DatabaseContext>();

            services.AddIdentityServer().AddApiAuthorization<ApplicationUser, DatabaseContext>();

            services.AddAuthentication().AddIdentityServerJwt();

            services.AddControllersWithViews();
            services.AddRazorPages();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
                app.UseWebAssemblyDebugging();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseIdentityServer();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
```

Startup blazor
```
        public static async Task Main(string[] args)
        {
            WebAssemblyHostBuilder builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddHttpClient("Project.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)).AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

            builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("Project.ServerAPI"));

            builder.Services.AddApiAuthorization();

            await builder.Build().RunAsync();
        }
```

### To Reproduce
1. Create webassembly project using asp.net core + standalone sign in
2. Move index.html to server as _Host
3. Put breakpoint into _Host
4. Refresh -> Check User.Identity.IsAuthenticated => false

### Further technical details
- ASP.NET Core version 3.1.5

**Comment by javiercn** [comment]
@glararan thanks for contacting us.

This is by design, the only authenticated pieces of the app are the ones the server and the API endpoints that have Authorize on it. The default authentication scheme is set to authenticate APIs that receive JWT Bearer tokens on the `Authorization` header.

If you want to authenticate the user in a razor page or view, you can use the Identity application scheme along with the AuthenticationService in AspNetCore to retrieve the user or use a PolicyScheme to setup the allowed authentication schemes based on the conditions you care about (for example the request path)

**Comment by glararan** [comment]
Oh,

Then what I need to change if I would like to stick to templated part just getting User.Identity.IsAuthenticated (true) in _Host + Controllers? Change scheme to cookies?

**Comment by javiercn** [comment]
Call https://github.com/dotnet/aspnetcore/blob/master/src/Http/Authentication.Abstractions/src/IAuthenticationService.cs#L21 to retrieve the user using `IdentityConstants.ApplicationScheme` or use [Authorize] passing `IdentityConstants.ApplicationScheme` and optionally `[AllowAnonymous]` if you want to authenticate the users with Identity but allow anonymous users.

**Comment by glararan** [comment]
Oh ok, thanks. Didnt know about this
