### ISSUE TITLE
Blazor index.html should mimic the top level site

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#24910]
Rather than
```html
<div id="app">Loading...</div>
```
the `index.html` should have
```html
<div id="app">
    <div class="page" b-vehgu10x1i>
        <div class="sidebar" b-vehgu10x1i>
            <div class="top-row pl-4 navbar navbar-dark" b-sjoxlt10a7></div>
        </div>
        <div class="main" b-vehgu10x1i>
            <div class="top-row px-4" b-vehgu10x1i></div>
            <div class="content px-4" b-vehgu10x1i>Loading...</div>
        </div>
    </div>
</div>
```

I was going to make a change to the template; however with the scoped css https://github.com/dotnet/aspnetcore/pull/24380 it additionally needs the specific attribute for the css to work (e.g. `b-vehgu10x1i` and `b-sjoxlt10a7` above); which I'm not sure how to do.

This change means while the page is loading assets rather than starting as

![image](https://user-images.githubusercontent.com/1142958/90251154-2db9b680-de35-11ea-847a-d32b70381856.png)

It instead starts at

![image](https://user-images.githubusercontent.com/1142958/90251174-34482e00-de35-11ea-86a6-b0eec3892f38.png)

Which is both less bleak and a less jarring transition to

![image](https://user-images.githubusercontent.com/1142958/90251189-3ad6a580-de35-11ea-87fb-53fbf5b8172e.png)

It also makes the experience perceptively seem to load faster

/cc @javiercn @SteveSandersonMS @mkArtakMSFT

**Comment by khalidabuhakmeh** [comment]
May I suggest a spinner instead of `...`? https://getbootstrap.com/docs/4.4/components/spinners/

**Comment by javiercn** [comment]
@benaadams thanks for contacting us.

This seems like a good change to me, I'm not sure how @danroth27 or @SteveSandersonMS feel about it.

That said, you are right that with the scoped css work that we've done, it is hard to replicate this behavior on the static html, so I'm not sure what we can do here.

We are working on client-side prerendering which could work here as an alternative if we were to just display loading during prerendering and render the actual components once the app has started (after the first render), but honestly, I'm not sure there is not much we can do in 5.0 I think.

Devs are always able to change this in their app, so this reduces the priority here, so we can decide to do it at any point, but I acknowledge this scenario is hard to do with the way the current template is structured.

**Comment by benaadams** [comment]
Full prerendering is obviously more desirable, though a larger task

Full prerender: https://testblazor.z20.web.core.windows.net/prerender/

Current default: https://testblazor.z20.web.core.windows.net/regular/

**Comment by mihaimyh** [comment]
@benaadams Do you have a repo for your pre-render example?

**Comment by benaadams** [comment]
@mihaimyh I did it manually as example, by loading the regular and copying out the `<div id="app">...</div>` html; then pasting it over the `<div id="app">Loading...</div>` in `wwwroot/index.html`

**Comment by TanayParikh** [comment]
Thanks all for the input, I'm going to close this out in favor of https://github.com/dotnet/aspnetcore/issues/37199 which covers the Blazor WASM initial loading story.
