### ISSUE TITLE
VS2019 Custom TagHelper Intellisense Not Working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24913]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1141437/vs2019-custom-taghelper-intellisense-not-working.html)._

---
[severity:I'm unable to use this version of Visual Studio]
I designed custom TagHelpers and used them on Razor pages but there is no Intellisense and no coloring, but they are available for standard tag helpers like <a asp-for ... and others in VS2019 but all work in VS2017

---
#### Feedback Bot on 8/9/2020, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/9/2020, 11:46 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Do you happen to have the appropriate `@addTagHelper *, YourProjectsAssemblyName` for your project?
