### ISSUE TITLE
CSHTML code changes are not applied in debug.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#24914]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1133128/cshtml-code-changes-are-not-applied-in-debug.html)._

---
1. Create the MVC scaffolding for a page.
Conroller ViewModel should include:
    `MyViewModel.CanSeeTitle = true;`
    `MyViewModel.CanSeeSubTitle = true;`

2. Create a basic CSHTML
```
@if(Model.CanSeeTitle)
{
<h1>My Test Page</h1>
}
```
*NOTE: Do not include CanSeeSubTitle property on the CSHTML page yet

3. Run the web app so you can see the page.
4. Now, put a break point on `@if(Model.CanSeeTitle)` in the CSHTML
5. Refersh the page
6. When it catches the break point, below the break point insert an @if statement using the property "CanSeeSubTitle" in the CSHTML
```
@if(Model.CanSeeTitle)
{
<h1>My Test Page</h1>
}
@if(Model.CanSeeSubTitle){
    <h2>I'm here...</h2>
}
```

5. Hit continue

Result: The Subtitle is not displayed
Expected: Subtitle is displayed

I have tried stopping the project, cleaning and rebuilding, etc....
Nothing seems to work. Only after many cache clearings and refreshes does the code finally take hold and work.

I can reproduce on FireFox, IE11, Edge and Chrome.
The debugger will continually skip the resolution of the if statement like it doesn't exist.

---
#### Feedback Bot on 8/2/2020, 10:47 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/3/2020, 01:12 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thanks for your feedback. For ASP.NET Core projects targeting 3.1 and later, you have to enable runtime compilation to be able to edit your views once the application is running. See https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&tabs=visual-studio#enable-runtime-compilation-in-an-existing-project
