### ISSUE TITLE
Incorrect Intellisense when using "@bind" in a .razor file

### ISSUE THREAD

**Issue by AndrewPetz** [dotnet/aspnetcore#24921]
### Describe the bug
I'm working through [part 2 of the Blazor Workshop](https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/02-customize-a-pizza.md). Typing `@bind` in a .razor file brings up incorrect Intellisense options:

![image](https://user-images.githubusercontent.com/7032619/90298442-ea247400-de57-11ea-9ef5-c6ad834a6c22.png)

Pressing "=" at this point automatically inserts `@BindAttributes=""`. [Here's](https://gfycat.com/diligenthandsomekid) a gif.

### To Reproduce

I'm using Visual Studio Professional 2019 Version 16.7.1 with the experimental Razor editor enabled in Preview Features.

[Here](https://github.com/AndrewPetz/blazor-intellisense-issue) is the repo I made for this issue. To reproduce:

1. Open BlazingPizza.Client/Shared/ConfigurePizzaDialog.razor
1. On line 12, type `@bind` and press `=`
1. `@BindAttributes=""` should be automatically entered instead of `@bind=""`

### Logs & Exceptions

Please collect the data below before reporting your issue to aid us in diagnosing the root cause.

#### Activity log
I don't know how useful this will be for this issue, but [here](https://gist.github.com/AndrewPetz/ae5f6879f7a0818d09165d657c990ace) is the ActivityLog.xml.

#### Razor Language Server Client log

Gist [here](https://gist.github.com/AndrewPetz/bf3a17b693db697d911bdab663571840).

#### HTML Language Server Client log

<details>
<summary>HTML Language Server Client Log Output</summary>

Info: Finding descriptor for initialize
Info: Starting: Routing Request (2) initialize
Info: Converting params for Request (2) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
Info: Finished: Routing Request (2) initialize in 69ms
Info: Finding descriptor for initialized
Info: Starting: Routing Notification initialized
Info: Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams
Info: Finished: Routing Notification initialized in 212ms
Info: Finding descriptor for textDocument/didOpen
Info: Created attribute htmlyLSP::file:///C:/Users/nanno/Documents/GitHub/BlazorApp/save-points/00-get-started/BlazingPizza.Client/Shared/ConfigurePizzaDialog.razor__virtual.html
Info: Looking for handler for descriptors textDocument/didOpen
Info: Checking handler textDocument/didOpen:Microsoft.WebTools.Languages.Html.LanguageServer.Html.OperationHandlers.TextDocumentHandler
Info: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentRegistrationOptions
Info: Document Selector [htmlyLSP, file]
Info: Starting: Routing Notification textDocument/didOpen
Info: Converting params for Notification textDocument/didOpen to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Finished: Routing Notification textDocument/didOpen in 160ms
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 48ms
Info: Finding descriptor for textDocument/didOpen
Info: Created attribute htmlyLSP::file:///C:/Users/nanno/Documents/GitHub/BlazorApp/save-points/00-get-started/BlazingPizza.Client/App.razor__virtual.html
Info: Looking for handler for descriptors textDocument/didOpen
Info: Checking handler textDocument/didOpen:Microsoft.WebTools.Languages.Html.LanguageServer.Html.OperationHandlers.TextDocumentHandler
Info: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentRegistrationOptions
Info: Document Selector [htmlyLSP, file]
Info: Starting: Routing Notification textDocument/didOpen
Info: Converting params for Notification textDocument/didOpen to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams
Info: Finding descriptor for textDocument/didOpen
Info: Created attribute htmlyLSP::file:///C:/Users/nanno/Documents/GitHub/BlazorApp/save-points/00-get-started/BlazingPizza.Client/Pages/Index.razor__virtual.html
Info: Looking for handler for descriptors textDocument/didOpen
Info: Checking handler textDocument/didOpen:Microsoft.WebTools.Languages.Html.LanguageServer.Html.OperationHandlers.TextDocumentHandler
Info: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentRegistrationOptions
Info: Document Selector [htmlyLSP, file]
Info: Finding descriptor for textDocument/didOpen
Info: Created attribute htmlyLSP::file:///C:/Users/nanno/Documents/GitHub/BlazorApp/save-points/00-get-started/BlazingPizza.Client/Shared/MainLayout.razor__virtual.html
Info: Looking for handler for descriptors textDocument/didOpen
Info: Checking handler textDocument/didOpen:Microsoft.WebTools.Languages.Html.LanguageServer.Html.OperationHandlers.TextDocumentHandler
Info: Registration options OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentRegistrationOptions
Info: Document Selector [htmlyLSP, file]
Info: Finished: Routing Notification textDocument/didOpen in 48ms
Info: Starting: Routing Notification textDocument/didOpen
Info: Converting params for Notification textDocument/didOpen to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams
Info: Finished: Routing Notification textDocument/didOpen in 78ms
Info: Starting: Routing Notification textDocument/didOpen
Info: Converting params for Notification textDocument/didOpen to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidOpenTextDocumentParams
Info: Finished: Routing Notification textDocument/didOpen in 12ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Finished: Routing Notification textDocument/didChange in 28ms
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 4ms
Info: Finding descriptor for textDocument/hover
Info: Found attributes 0, 
Info: Starting: Routing Request (3) textDocument/hover
Info: Converting params for Request (3) textDocument/hover to OmniSharp.Extensions.LanguageServer.Protocol.Models.HoverParams
Info: Finding descriptor for $/cancelRequest
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.Hover, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was (null)
Info: Finished: Routing Request (3) textDocument/hover in 185ms
Info: Starting: Routing Notification $/cancelRequest
Info: Converting params for Notification $/cancelRequest to OmniSharp.Extensions.JsonRpc.CancelParams
Info: Request 3 was not found to cancel
Info: Finished: Routing Notification $/cancelRequest in 3ms
Info: Finding descriptor for textDocument/hover
Info: Found attributes 0, 
Info: Starting: Routing Request (4) textDocument/hover
Info: Converting params for Request (4) textDocument/hover to OmniSharp.Extensions.LanguageServer.Protocol.Models.HoverParams
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.Hover, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was (null)
Info: Finished: Routing Request (4) textDocument/hover in 1ms
Info: Finding descriptor for textDocument/hover
Info: Found attributes 0, 
Info: Starting: Routing Request (5) textDocument/hover
Info: Converting params for Request (5) textDocument/hover to OmniSharp.Extensions.LanguageServer.Protocol.Models.HoverParams
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.Hover, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was (null)
Info: Finished: Routing Request (5) textDocument/hover in 26ms
Info: Found attributes 0, 
Info: Finding descriptor for textDocument/didChange
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 5ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 11ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 3ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/completion
Info: Found attributes 0, 
Info: Starting: Routing Request (6) textDocument/completion
Info: Converting params for Request (6) textDocument/completion to OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionParams
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList
Info: Finished: Routing Request (6) textDocument/completion in 43ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Finished: Routing Notification textDocument/didChange in 51ms
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 70ms
Info: Finding descriptor for textDocument/completion
Info: Found attributes 0, 
Info: Starting: Routing Request (7) textDocument/completion
Info: Converting params for Request (7) textDocument/completion to OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionParams
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList
Info: Finished: Routing Request (7) textDocument/completion in 17ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Found attributes 0, 
Info: Finding descriptor for textDocument/didChange
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Finished: Routing Notification textDocument/didChange in 10ms
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 1ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 23ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 12ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 16ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 3ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 5ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 16ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 0ms
Info: Finding descriptor for textDocument/_ms_onAutoInsert
Info: Found attributes 0, 
Info: Starting: Routing Request (8) textDocument/_ms_onAutoInsert
Info: Converting params for Request (8) textDocument/_ms_onAutoInsert to Microsoft.WebTools.Languages.Html.LanguageServer.Shared.AutoInsert.AutoInsertParams
Info: AutoInsert request in file:///C:/Users/nanno/Documents/GitHub/BlazorApp/save-points/00-get-started/BlazingPizza.Client/Shared/ConfigurePizzaDialog.razor__virtual.html at (11, 111).
Info: AutoInsert result: Replacing 0 characters at 429 with "" and placing caret at 1
Info: Result was System.Threading.Tasks.Task`1[[Microsoft.WebTools.Languages.Html.LanguageServer.Shared.AutoInsert.AutoInsertResponse, Microsoft.WebTools.Languages.Html.LanguageServer, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]
Info: Response value was Microsoft.WebTools.Languages.Html.LanguageServer.Shared.AutoInsert.AutoInsertResponse
Info: Finished: Routing Request (8) textDocument/_ms_onAutoInsert in 42ms
Info: Finding descriptor for textDocument/completion
Info: Found attributes 0, 
Info: Starting: Routing Request (9) textDocument/completion
Info: Converting params for Request (9) textDocument/completion to OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionParams
Info: Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList, OmniSharp.Extensions.LanguageProtocol, Version=0.15.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
Info: Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList
Info: Finished: Routing Request (9) textDocument/completion in 5ms
Info: Finding descriptor for textDocument/didChange
Info: Found attributes 0, 
Info: Starting: Routing Notification textDocument/didChange
Info: Converting params for Notification textDocument/didChange to OmniSharp.Extensions.LanguageServer.Protocol.Models.DidChangeTextDocumentParams
Info: Finished: Routing Notification textDocument/didChange in 9ms

</details>

### Further technical details
- VS version: Visual Studio Professional 2019 Version 16.7.1 with the experimental Razor editor enabled in Preview Features
- Scenario: Local

### Pre-requisite checklist
- [x] Steps to reproduce the issue
- [x] Razor Language Server client logs included.
- [x] HTML Language Server client logs included

**Comment by NTaylorMullen** [comment]
@AndrewPetz it looks like you are using ReSharper for your C# experience which is why you're not getting the expected completions. I'd suggest reaching out to ReSharper with this bug. Thank you for your awesome report though!
