### ISSUE TITLE
Error after updating Microsoft.AspNetCore.ApiAuthorization.IdentityServer to version 3.1.7

### ISSUE THREAD

**Issue by RwnRchrds** [dotnet/aspnetcore#24940]
After updating the following package to version 3.1.7:

- Microsoft.AspNetCore.ApiAuthorization.IdentityServer

I receive this error on application start up:

`System.TypeLoadException: 'Method 'GetAllAsync' in type 'IdentityServer4.Stores.InMemoryPersistedGrantStore' from assembly 'IdentityServer4, Version=3.0.0.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b' does not have an implementation.'`

**Comment by som-nitjsr** [comment]
Can you please add some more details how to reproduce it.

**Comment by blowdart** [comment]
You've also updated to identity server 4. We target Identity Server 3.

See https://github.com/dotnet/aspnetcore/issues/24223
