### ISSUE TITLE
Renaming in C# Code Does Not Get Applied in Razor Markup

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#24949]
Renaming in a C# file a class, field or method  that is referenced in Razor markup does not get applied to the markup code.  I am using VS Community 2019 v16.7.1 with AspNetCore 3.2.1.

**Comment by ajaybhargavb** [comment]
Thanks for the report @CincySteve. We're working on this. You can track it here, https://github.com/dotnet/aspnetcore/issues/21978.
