### ISSUE TITLE
Blazor WASM keep reload resources  

### ISSUE THREAD

**Issue by IdanFan** [dotnet/aspnetcore#24954]
Hello ,
I noticed that my Blazor WASM project keep reload the resources for no reason.(keep sending the same request again and again, include authentication request as /connect/token)
Things that I already know so far : 
1. The problem is not happening for any user , I mean that the problem is happening only in my chrome (the other browsers on the same pc works fine and don't have the problem) so I checked the chrome from a pc I didn't ever joined the website before and the problem is not showing up.
2. I cleared all browser website resources so it will download all again from my server but the problem keep happening, the only thing I can think about maybe it related to that that this is my default browser and I used it to debug my project for the last few months.
It caused my website to crash so I can't publish my website till I fix it because it may happen to more users (?)
3.The problem is happening only when I on the client side - I means that when I'm in the login page for example(which in the server project) , the problem is not happening ,but it keeps reload the resources after I successfully logged in and redirected to index page.
4.It happens only on my production linux machine, when I ran it on debug or run the production version locally (on my testing pc) the problem is not happening.

I can't reproduce the problem because I didn't notice when or why it's started happing till my web crashed.
I updated to the latest packages yesterday and that didn't resolve the problem.

gif showing the problem : 
https://gfycat.com/reliablefarawaycurlew

**Comment by javiercn** [comment]
@IdanFan thanks for contacting us.

It looks like there is an issue in the way you've configured authentication in your app, since the static resources are being redirected to an authentication related endpoints.
