### ISSUE TITLE
Api returns index.html instead of Json in Blazor WebAssembly AspNetCore Hosted

### ISSUE THREAD

**Issue by WieszKto** [dotnet/aspnetcore#24967]
Hello
I created this project [https://github.com/WieszKto/BlazorOneTableIdentity](https://github.com/WieszKto/BlazorOneTableIdentity) in Blazor Webassembly Asp.net core hosted is an example of asp.net core identity implementation in blazor.
Unfortunately sometimes I got an error:

> 
> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100].
>       Unhandled exception rendering component: The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.

I noticed that when hitting the api at the start of a page, the index.html file from the wwwroot folder is returned instead of a Json format authentication response.
Changing StartUp project to Client and again to Server does not help

Now, to fix the bug, I have set Launch to Project for Server, and disabled Launch Browser for Client

No less a bug that was in Preview is also in the current version
[Same problem in Preview 5](https://github.com/dotnet/aspnetcore/issues/21288)

### To Reproduce

Using the example of my project [https://github.com/WieszKto/BlazorOneTableIdentity](https://github.com/WieszKto/BlazorOneTableIdentity), you need to undo the commitment "Change Launch to Project and disable Launch Browser in client to fix ... " 
Then change StartUp to Client, turn on applications, change StartUp to Server and turn on applications again

The error can also show itself without changing StartUp project to Client

The same issue i see in this project 
[https://github.com/stavroskasidis/BlazorWithIdentity](https://github.com/stavroskasidis/BlazorWithIdentity)
You can also test it on this project without removing the last commit

### Further technical details
- ASP.NET Core 3.1 (Server)
- ASP.NET Standard 2.1 (Client)
- VS2019 Community 16.7.1

.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64

**Comment by javiercn** [comment]
@WieszKto thanks for contacting us.

Seems like you are implementing your own authentication support. We recommend people to use the built-in authentication support we provide.

It's not clear to us what the issue you are referring to is. Can you provide detailed steps and a clear error of what's not working and what you are expecting to happen?

**Comment by WieszKto** [comment]
The problem is that sometimes the API that is on the server side does not return data as if it was not working. The problem is only in Blazor Webassembly AspNetCore Hosted.
For me, this problem manifests itself as
This is a good return of data from the server:
![GoodResponse](https://user-images.githubusercontent.com/43013797/90423673-2a386080-e0bd-11ea-9863-9c20e5ed4b24.jpg)

But sometimes he can return an index.html file, so there are errors
![BadResponse](https://user-images.githubusercontent.com/43013797/90423904-94510580-e0bd-11ea-93d2-f12edf6973fa.jpg)

As if StartUp project was set to Client instead of Server (although until the first time the error occurred it was not changed)

The problem is with IIS Express so I don't know if this is a problem with Blazer or VS2019.

What does he expect? Repairs :D
It is problematic to reset the page and check if this time the request will go to API or not

**Comment by mihaimyh** [comment]
I solved this by adding the following in Startup.cs in server project:

```endpoints.Map("api/{**slug}", HandleApiFallback);
```

```
private Task HandleApiFallback(HttpContext context) { context.Response.StatusCode = StatusCodes.Status404NotFound; return Task.FromResult(0); }
```

**Comment by captainsafia** [comment]
Thanks for reporting this issue.   We'll consider your feedback as part of an existing issue (#21699).
