### ISSUE TITLE
Action link injects passed Id when opening same page

### ISSUE THREAD

**Issue by pamanes** [dotnet/aspnetcore#24977]
hi,

We have an MVC Project with a controller called Pricing and inside a view called Create where id is optional, when we hit the page with an id, the action link we have on the _Layout page to go to the same page is created with the passed id, is this correct? shouldn't it be blank?

the code we have for the link on the layout page is:

`<a asp-area="" asp-controller="Pricing" asp-action="Create">Create</a>`

passing an explicit blank asp-route-id seems to fix the issue like this:

`<a asp-area="" asp-route-id="" asp-controller="Pricing" asp-action="Create">Create</a>`

Our ConfigureServices has this line:
`services.AddMvc(option => option.EnableEndpointRouting = false);`

and our Configuration has this line:
`app.UseMvcWithDefaultRoute();`

this is .Net Core 3.1 on Microsoft Visual Studio Enterprise 2019 (Version 16.6.5)

thanks,

**Comment by pranavkm** [comment]
Legacy routing uses ambient values from the current route when constructing new routes. This is fixed in endpoint routing where the ambient `id` value is not used when constructing the action link.
