### ISSUE TITLE
Blazor client PWA does not update

### ISSUE THREAD

**Issue by genifycom** [dotnet/aspnetcore#24973]
If you create a Blazor client PWA and it is published and runs, when the PWA code is updated the App reports "An unhandled error has occurred Reload". The app will not reload until the Site Settings (at least in Chrome) "Clear Data" is run.

This precludes us from having updates automatically deployed to clients.

**Comment by captainsafia** [comment]
>  "An unhandled error has occurred Reload". 

Can you share the stack trace for this exception? It should be displayed in the console output in the Developer Tools of your browser.

**Comment by genifycom** [comment]
This is what is shown in the Dev tools console
Unknown error occurred while trying to verify integrity.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https:/xxxx/_framework/_bin/WebAssembly.Bindings.dll' with computed SHA-256 integrity 'AWSHAkByLIJv4X227ilklONKUqZC02qN08KlyOrhJ1E='. The resource has been blocked.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @genifycom.
Please share more details about how you publish your app.
