### ISSUE TITLE
[Discussion] Obsoleting DatabaseErrorPage middleware

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#24987]
Discussion for https://github.com/aspnet/Announcements/issues/432

## Obsoleting DatabaseErrorPage

With the introduction of [extensible handlers for `DeveloperExceptionPage`](https://github.com/dotnet/aspnetcore/issues/8536), we are planning to obsolete the `DatabaseErrorPageMiddleware` and its associated extension methods in .NET 5.0 with further plans to remove them in .NET 6.0. The functionality will instead be provided by `DatabaseDeveloperPageExceptionFilter` and its extension methods instead.

### Version introduced

ASP.NET Core 5.0 RC 1

### Old behavior

`DatabaseErrorPageMiddleware` and its associated extension methods were not obsolete.

### New behavior

`DatabaseErrorPageMiddleware` and its associated extension methods are now obsolete.

### Reason for change

We are migrating the existing database error page middleware to the new extensible API for `DeveloperExceptionPage`.

### Recommended action

1. Remove uses of `DatabaseErrorPageMiddleware`in your app:

```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDatabaseErrorPage();
    }
    ...
}
```

2. Ensure `DeveloperExeptionPage` and `MigrationsEndpoint` are added to your app:

```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseMigrationsEndPoint();
    }
    ...
}
```

3. Add `DatabaseDeveloperPageExceptionFilter` to your services:

```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDatabaseDeveloperPageExceptionFilter();
    ...
}
```

### Category

ASP.NET

### Affected APIs

  [`Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.diagnostics.entityframeworkcore.databaseerrorpagemiddleware)
  [`Microsoft.AspNetCore.Builder.DatabaseErrorPageExtensions.UseDatabaseErrorPage`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.databaseerrorpageextensions.usedatabaseerrorpage)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by Pilchie** [comment]
:eyes:

**Comment by JunTaoLuo** [comment]
FYI there was a small update since the original announcement. In the "Recommended acction", the second step has been updated to note that `UseMigrationsEndPoint` should also be added to ensure functionality originally configured by `UseDatabaseErrorPage` is maintained.
