### ISSUE TITLE
Blazor WASM Authentication - TryGetToken returns RequiresRedirect Status after MSAL Login - Version 3.2.1

### ISSUE THREAD

**Issue by Sagar-Vaja** [dotnet/aspnetcore#24995]
### Describe the bug
Using MSAL (With Azure Active Directory), after a successful login (when calling AccessTokenProvider.RequestAccessToken, the method tokenResult.TryGetToken(out var token) returns a null token value because tokenResult has RequiresRedirect Status.

### To Reproduce
Just generate a new MSAL project using:
`dotnet new blazorwasm -au SingleOrg --client-id "{CLIENT ID}" --tenant-id "{TENANT ID}"`

And to reproduce, consider the following code in index.razor (with an Authorize attribute)
@code {
    [Inject] private IAccessTokenProvider AccessTokenProvider { get; set; }
    protected override async Task OnInitializedAsync()
    {
        var tokenResult = await AccessTokenProvider.RequestAccessToken();
        
        if (tokenResult.TryGetToken(out var token))
        {
            if (token == null)
                throw new Exception("Access token is null");
        }
    }
}
The request was successfully authenticated so I should get a token

![tokenResult output](https://user-images.githubusercontent.com/58077896/90483703-bb0d4b80-e152-11ea-8904-52de1ef70b99.png)

**Comment by javiercn** [comment]
@Sagar-Vaja thanks for contacting us.

That likely means that it wasn't able to get the token silently and that you need to request the required scopes during the login so that silent token provisioning can work.

**Comment by Sagar-Vaja** [comment]
@javiercn Thanks for the solution.

Requested for the additional scopes during login & it worked perfect
