### ISSUE TITLE
[Blazor] UI freeze with WebAssembly/SignalR

### ISSUE THREAD

**Issue by RomainAn** [dotnet/aspnetcore#24994]
Hi everyone,

First i would like to thanks you all for the amazing job you did, and how much you made Blazor grow and make it super interesting.

Still, i have some concerned about the issue using WebAssembly 3.2.0, .NET Core hosted (3.1.302).
I'm currently doing a real-time application that is doing cryptocurrency orderbook viewer (Retrieving data from websockets with SignalR).
Somehow, the UI is freezing or extremely slow even there is maximum 5-10 refresh per seconds.
I keep having GC_Minor happening and there is freezes when i get GC_MAJOR_SWEEP.

I tried to avoid doing allocations as much as i can.
On every incoming messages i am calling StateHasChanged()
Also, i tried to profile using Chrome and 99% is wasted on mono_jit_runtime_invoke.

Should be consider to not use Blazor WebAssembly for high-frequency tasks ?

Have a great day,

Ro

**Comment by captainsafia** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by captainsafia** [comment]
> Should be consider to not use Blazor WebAssembly for high-frequency tasks ?

It depends on what you're doing with each task and whether the tasks is compute intensive.

**Comment by Rymix** [comment]
Hello Captainsafia thank you for your messages, i will provide you a minimalistic repo as soon as possible.
Tasks aren't intensive, this is just displaying informations within tables (and later on, drag and drop on theses tables)

I discover yesterday that if i send multiple updates without any Thread.Sleep() within my .NET Core API/SignalR hub, the UI is freezing.
I found that sending update only every 50ms or 100ms the UI is not freezing.
So probably the update rate is too high or faster than the re-rendering of the UI.

Is there a way to away the GC getting called too much ?

**Comment by pranavkm** [comment]
We generally wouldn't recommend doing `Thread.Sleep` in a Blazor App. That said, a minimal application might help us to investigate what might be incorrect/

**Comment by RomainAn** [comment]
Hey @pranavkm, i'm not using any Sleep within the client, i tried to do that in the TradingHub in the server just for testing purpose.
I partially solved this issue by not calling StateHasChanged() every message from the SignalR Socket.
I just check the last update of the view, and i refresh only if the last refresh is >= X ms.
I think blazor isn't meant to handle multiple concurrent refresh.
