### ISSUE TITLE
Validate unimported completions don't break the Razor experience in VSCode

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#25008]
O# is looking to add support for unimported completions here: https://github.com/OmniSharp/omnisharp-roslyn/pull/1896

We don't currently remap text edits so I'd imagine VSCode would start barfing mentioning how it can't apply the TextEdit to the virtual C# file/Razor file.

Marking as blocked until they complete their PR.

**Comment by 333fred** [comment]
@NTaylorMullen I'm planning on making the feature optional, probably off by default. I can add a note to the option in vscode that it's not supported with razor projects.

**Comment by 333fred** [comment]
Also, I just added support for override completion, and while the support isn't yet in vscode yet, that also contains additional text edits and isn't currently planned to be an option. If it's important, I can add an option there as well to use legacy completion until you implement text edit remapping.

https://github.com/OmniSharp/omnisharp-vscode/pull/3986

**Comment by NTaylorMullen** [comment]
> PR for that issue is out now.

If I build the O# repo locally will that allow me to test out the latest and greatest fixed?

**Comment by 333fred** [comment]
You should just be able to use the `latest` tag.

**Comment by NTaylorMullen** [comment]
Just tried out the override support and looks like we have some work to do 😄 
![DsIiXixH7Y](https://user-images.githubusercontent.com/2008729/91897627-6936ec00-ec4f-11ea-8277-cfa10baa100a.gif)


I've filed the "enablement" of this here: https://github.com/dotnet/aspnetcore/issues/25509
