### ISSUE TITLE
Extend Blazor WebAssembly OidcProviderOptions to accept extra parameters on authentication  

### ISSUE THREAD

**Issue by nahidf** [dotnet/aspnetcore#25004]
When adding OpenId Connect authentication on the application, there is often requirement to pass extra parameters to Idp, there is not such an option on Blazor WebAssembly OpenIdConnect provider. 

### Is your feature request related to a problem? Please describe.

This feature will help passing extra parameters to Idp on authentication using OpenId Connect, here is some examples 

1. Passing user context to Idp when using IdentityServer4. [Blog reference](https://developers.de/2019/11/29/how-to-pass-custom-parameters-in/)

2. Passing audience to Idp when using Auth0. [Blog Reference](https://auth0.com/docs/quickstart/webapp/aspnet-core/01-login)

Same scenarios are applicable using Blazor WebAssembly.  

### Describe the solution you'd like

To add this feature there is two options: 

1. Extend  [OidcProviderOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs) to add `extraQueryParams`. This solution is like what is done on [oidc-client-js](https://github.com/IdentityModel/oidc-client-js/blob/dev/src/OidcClient.js#L65)
This is the easiest solution to go with, to implement all we need to do is to add following code on [OidcProviderOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs)

```
        [JsonPropertyName("extraQueryParams")]
        public IDictionary<string, string> ExtraQueryParams = { get; } = new Dictionary<string, string>();
```

I also believe this option matches the current design.

2. Extend  [OidcProviderOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs) to add `OnRedirectToIdentityProvider` event. This solution is like what is done on [OpenIdConnectOptions](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs) by adding [OnRedirectToIdentityProvider](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/OpenIdConnect/src/Events/OpenIdConnectEvents.cs#L34)

### Additional context

There has been [similar issue](https://github.com/dotnet/aspnetcore/issues/23606) opened before, It was closed with comment that 

> This behavior is by-design. We don't provide to use any custom protocol extensions

As mentioned above the OpenId Connect extensions on ASP.NET Core provides this feature and I'm not sure if Blazor WebAssembly is any different. 
This feature is for protocol extensions but it is not specific for any custom provider or library.

**Comment by nahidf** [comment]
I will be getting started to open PR for this

**Comment by Asshiah** [comment]
StefH provided an implementation for the Auth0 Audience use case here:
https://github.com/dotnet/aspnetcore/issues/23606
https://github.com/StefH/Blazor.WebAssembly.Authentication.Auth0
https://www.nuget.org/packages/WebAssembly.Authentication.Auth0/

The thing is it is not generic for any querystring parameters and non official.

**Comment by braidenstiller** [comment]
In addition to Asshiah's comment, while the above linked solution does work, there doesn't appear a way to drive dynamic query string parameters based on task, e.g. passing additional parameters for sign up vs logging in.

The proposed OnRedirectToIdentityProvider event would solve this.
