### ISSUE TITLE
Delay in Blazor Debugging Startup with Visual Studio Community 2019 & Chrome

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#25016]
Break points in my OnInitialized override code do not work on a relatively small test Blazor Wasm PWA app.  I am using VS Community 2019 V16.7.1 with AspNetCore v3.2.1 and Chrome v84.0.4147.125.

The same problem occurs in a much bigger app and, in fact, break points elsewhere in the code don't activate unless I wait around 5 seconds.  In the latter case, I have setup a test scenario in which I keep clicking on a button to see if/when the break point stops execution.  It eventually does after about 5 seconds from when the app is fully rendered.  In case it's relevant, the latter app is also experiencing [this problem](https://github.com/dotnet/aspnetcore/issues/24706).

It appears there is a delay in the startup of the debugger.  

If this isn't a known problem, I would be happy to streamline the small app for posting, assuming the streamlined version exhibits the same behavior.  I am not particularly adept at GitHib, so please bear with me.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @CincySteve!

This is indeed a known issue that we have been tracking over at https://github.com/dotnet/aspnetcore/issues/23473. We plan on shipping improvements to this experience in .NET 5.
