### ISSUE TITLE
Renaming Fully Qualified Component Loses Namespace

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#25021]
![ComponentRenameLosesNamespace](https://user-images.githubusercontent.com/14852843/90572321-9623d300-e168-11ea-86d6-148bd6ad82a2.gif)

Expected:
`<SomeNamespace.ComponentName>` -> rename `ComponentName` to `ComponentName2` -> becomes `<SomeNamespace.ComponentName2>` (loses the namespace)

Actual:
`<SomeNamespace.ComponentName>` -> rename `ComponentName` to `ComponentName2` -> becomes `<ComponentName2>` (loses the namespace)

**Comment by NTaylorMullen** [comment]
Note: Rename does not work in Codespaces
