### ISSUE TITLE
Renamed Component From Different Namespace Not Recognized

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#25022]
Renaming a component part of a different namespace isn't recognized until the file is closed and re-opened.

Counter.razor:
```
@using SomeSpace

<Component3></Component3>
```

Component3.razor:
```
@namespace SomeSpace
```

Rename in Counter.razor from `Component3` to `Component4`.

Expected: `Component4` is recognized

Actual: Not recognized

![RenamedComponentNotRecognized](https://user-images.githubusercontent.com/14852843/90572660-7214c180-e169-11ea-8833-82dba30e4c92.gif)

**Comment by NTaylorMullen** [comment]
Isn't this just because in the background we're discovering TagHelpers for the newly changed file?

**Comment by TanayParikh** [comment]
Ah yeah, that's it.

**Comment by NTaylorMullen** [comment]
In the future we could technically try and "update" the TagHelpers in place to make the TagHelpers how  up immediately  but that's risky in its own right
