### ISSUE TITLE
Cannot signin using HttpContext.SignInAsync in Chrome

### ISSUE THREAD

**Issue by shuba-developer** [dotnet/aspnetcore#25031]
I'm developing an application using `ASP.Net Core MVC 3.1`  with `CookieAuthentication`.  I'm facing a problem where it fails to sign-in in `Chrome` but runs well when using `Microsoft Edge` or `Mozilla Firefox`.
AccountController

	var claims = new List<Claim> {
		new Claim(ClaimTypes.Name, user.UserName, ClaimValueTypes.String),
		new Claim(ClaimTypes.Authentication, usr.Result.AccessToken, ClaimValueTypes.String),
		new Claim(ClaimTypes.Email, usr.Result.Email, ClaimValueTypes.String),
		new Claim(ClaimTypes.NameIdentifier, user.AppId, ClaimValueTypes.String),
		new Claim(ClaimTypes.GivenName, usr.Result.FullName, ClaimValueTypes.String),
		new Claim(ClaimTypes.GroupSid, usr.Result.GroupName ?? "", ClaimValueTypes.String),
		new Claim("EmailSupport",generalseting.EmailSupport ?? "", ClaimValueTypes.String),
		new Claim("UserId", usr.Result.UserId, ClaimValueTypes.String),
		new Claim("DepartmentId", usr.Result.DepartmentId, ClaimValueTypes.String),
		new Claim("DepartmentName", usr.Result.DepartmentName ?? "", ClaimValueTypes.String)
	};

	var userIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme, "", "");
	await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
		new ClaimsPrincipal(userIdentity),
		new AuthenticationProperties
		{
			ExpiresUtc = DateTime.UtcNow.AddHours(10),
			IsPersistent = true,
			AllowRefresh = true
		});

Startup.cs

	services
	.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
	.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
	{
		options.Cookie.SameSite = SameSiteMode.None;
		options.Cookie.HttpOnly = false;
		options.LoginPath = new PathString("/account/login");
		options.LogoutPath = new PathString("/account/logout");
		options.ExpireTimeSpan = TimeSpan.FromHours(10);
		options.ReturnUrlParameter = "/";
	 //options.Cookie.Expiration = TimeSpan.FromHours(10);
	});
	services.Configure<CookiePolicyOptions>(options =>
	{
	 options.CheckConsentNeeded = context => false;
		options.MinimumSameSitePolicy = SameSiteMode.None;
	});

**Comment by Tratcher** [comment]
Can you share the response headers? Is this https? SameSiteMode.None also requires the `secure` attribute witch will be included by default for https requests.

**Comment by shuba-developer** [comment]
This is http, not https. This is the screenshot of the response headers.
![c817da75-3f26-4662-8424-90b88bef3407](https://user-images.githubusercontent.com/55694652/90610679-fb8ec700-e22f-11ea-9b93-69e081fda784.jpg)

**Comment by Tratcher** [comment]
You can't use SameSiteMode.None on http. Use https or remove SameSiteMode.None.

There is no set-cookie header in that response, was that the request where you called SignInAsync?

**Comment by shuba-developer** [comment]
Yes. It was.  I'll remove that line. I'll update soon if it works or not

**Comment by shuba-developer** [comment]
It's now resolved. Thank you
