### ISSUE TITLE
[Feature Request] IApplicationFeatureProvider ability to access IServiceProvider ( specifically for Logging)

### ISSUE THREAD

**Issue by vllama** [dotnet/aspnetcore#25067]
### Is your feature request related to a problem? Please describe.
I am using an implementation `IApplicationFeatureProvider` and would like to log from the `PopulateFeature `method.
I know that by the time `PouplateFaeture `gets called, the `IServiceProvider `is already built from the `IServiceCollection`.
```
services.AddMvcCore()
    .ConfigureApplicationPartManager(manager => {
        manager.FeatureProviders.Add(new MyCustomFeatureProvider(/*services*/));
});
```

The Only way I can see about doing this now, is to pass in `IServiceCollection `to the constructor and call
`BuildServiceProvider()` which seems incorrect to me.

### Describe the solution you'd like

Possibly have `IApplicaitonFeatureProvider `expose the `IApplicationBuilder `instance being used in Configure?

**Comment by javiercn** [comment]
@vllama thanks for contacting us.

While that is the case in the majority of scenarios, unfortunately that's not a guarantee (for example that is not the case if you use AddControllersAsServices). For that reason we can't do this.

Could you give us a bit more detail on what you are trying to accomplish? We might be able to suggest alternative routes for it.

**Comment by vllama** [comment]
Thanks for the Reply,

What I am trying to accomplish is use dynamically generated Controllers, because our application has a plugin architecture which allows our different clients to plug in different Domain objects. (Ie. custom tables and fields), or azure tables, or web services as models.

While that all works, I have to instantiate our models into the application part using something like
  `typeof(ReadOnlyController<>).MakeGenericType(pocoType)`,  with a bunch of  if statements selecting different controller types based on the base interface of pocoType.  

I would like to abstract that away as a service with configuration, and use DI to, as well as have access to the logging facilities in this context. 

Right now the only way to see if something is wrong is to throw exceptions and fail the startup.

Thanks,

**Comment by pranavkm** [comment]
One way to go about this would be to capture state as part of the feature provider and defering the DI lookup until you have access to the service provider. Our current architecture does not allow for injecting DI context in the IApplicationFeatureProvider and it's not something we intend on changing in the near future.

**Comment by thanh81** [comment]
> m trying to accomplish is use dynamically generated Controllers, because our application has a plugin architecture which allows our different clients to plug in different Domain objects. (Ie. cu

I'm creating something similar.   I only have 1 base type of controller that all my models fit with so i dont have the specific concern you have.   Have you been able to load these in during runtime instead of startup?  That's where I'm stuck.   

Really cool concept of plugin for these.   What I'm doing is I'll have clients generate pocos but all of them fit a certain basecontroller.   I assume you have a handful of base controllers for this where you'll generate base on this.   Perhaps you can have 1 generic base controller that takes in a generic T of the object?

**Comment by vllama** [comment]
Yes I have been able to get this working by  caching all my poco type controllers by name and namespace  like this:
`private readonly Lazy<Dictionary<string, ILookup<string, Type>>> _cache;`
and then doing a big if statement for my different templates depending on some poco type interfaces  or properties. and calling MakeGeneric

then I implemented IApplicationFeatureProvider<ControllerFeature> to return the right controller
I used 
`	var existingControllers = feature.Controllers.ToList();` to compare and make sure that there are no name conflicts.
