### ISSUE TITLE
Microsoft.AspNetCore.Mvc.NewtonsoftJson does not exist in the publish folder

### ISSUE THREAD

**Issue by 78fede78** [dotnet/aspnetcore#25079]
This problem occurs after updating Microsoft.AspNetCore.Mvc.NewtonsoftJson to version 3.1.7
I have this error: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version = 3.1.7.0
This file is located in the publish folder: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version = 3.1.6.0
The file 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version = 3.1.7.0 was not copied to the publish folder

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by 78fede78** [comment]
Ho provato a creare un piccolo progetto ma il problema non si è verificato.
Il problema si è verificato solo sul mio progetto principale ma non posso condividere il codice.

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________
