### ISSUE TITLE
Consider normalizing path used for Discriminator

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2507]
_From @BrennanConroy on Tuesday, September 19, 2017 9:13:00 AM_

https://github.com/aspnet/DataProtection/blob/46dadbb18683164a918873f43624aee3b5b0510c/src/Microsoft.AspNetCore.DataProtection/Internal/HostingApplicationDiscriminator.cs#L23

One specific instance where I hit this was running an app from the command line produced a cookie in my browser. And then running the exact same app without any changes from VS Code would fail to unprotect the cookie because VS Code environment returned `e:/...` and command line environment returned `E:/...`

_Copied from original issue: aspnet/DataProtection#276_

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, October 13, 2017 12:03:13 PM_

This would probably end up being platform specific - because it shouldn't be case sensitive on windows, but should on linux.

Is there a path normalization function? (You'd be doing the work yourself anyway)

**Comment by blowdart** [comment]
Revisit as part of #2512 2512

**Comment by mkArtakMSFT** [comment]
Looks like the decision in the referenced issues was `Won't fix`. @blowdart should this be closed then?
