### ISSUE TITLE
Unexpected licenses in MusicStore javascript files 

### ISSUE THREAD

**Issue by omajid** [dotnet/aspnetcore#25076]
Most of the files in the [MusicStore sample](https://github.com/dotnet/aspnetcore/tree/master/src/MusicStore) don't include explicit license headers, so I assume they fall under the same license as ASP.NET Core: [Apache 2.0](https://github.com/dotnet/aspnetcore/blob/master/LICENSE.txt)

However, the javascript file in the MusicStore project have license headers that aren't a normal open source license.

These files include a license that's very restrictive:

- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.validate.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.validate.min.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.validate.unobtrusive.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.validate.unobtrusive.min.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.validate-vsdoc.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/modernizr-2.6.2.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/respond.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/respond.min.js

These 2 files mention a copyright, but not a license. Perhaps you can add a license header too?

- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.signalR-2.0.1.js
- https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/samples/MusicStore/wwwroot/Scripts/jquery.signalR-2.0.1.min.js

**Comment by omajid** [comment]
cc @dleeapho @leecow

**Comment by Pilchie** [comment]
Agreed.  The music store sample is pretty stale.  I wonder if it's still providing us the sort of benefit it was intended for.

**Comment by omajid** [comment]
Any chance the licenses could be fixed up or the non-open-source files be removed?

**Comment by omajid** [comment]
Any chance this will be fixed by 5.0 GA?

**Comment by Pilchie** [comment]
It's quite unlikely at this point.

**Comment by Pilchie** [comment]
I'm going to look at this along with #18873 early in .NET 6.

**Comment by Pilchie** [comment]
I think all of these files just got removed in https://github.com/dotnet/aspnetcore/pull/27853.
