### ISSUE TITLE
Unskip UserSecret tests

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#25109]
https://github.com/dotnet/runtime/issues/41117 caused some test failures in UserSecrets.

In order to unblock dep updates we are skipping the failing tests until the bug is fixed.

Skipped tests in https://github.com/dotnet/aspnetcore/pull/25090

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/37101

**Comment by halter73** [comment]
[Remove_Is_Case_Insensitive](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Tools/dotnet-user-secrets/test/SecretManagerTests.cs#L196-L197) is still skipped because of this issue. I'm not sure if it should be unskipped. @BrennanConroy

**Comment by BrennanConroy** [comment]
I think they should be unskipped, they were 100% failing before I believe, so if they pass when unskipped then we should be good.
