### ISSUE TITLE
Unexpected Markup Element Name Despite Fully Qualified / Added Using

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#25105]
The semantic colorization is coming through but it still claims it's unexpected. It resolves itself with document close and re-open. 

![image](https://user-images.githubusercontent.com/14852843/90831385-702d3880-e2f8-11ea-9ab5-08ab932c306a.png)

---

![NamespaceIssueTyped](https://user-images.githubusercontent.com/14852843/90831355-5f7cc280-e2f8-11ea-9563-199201faf8df.gif)

Would this be expected for some reason?

**Comment by NTaylorMullen** [comment]
> Would this be expected for some reason?

Definitely not expected. I'll throw it in Preview4. This is bad 😄

**Comment by TanayParikh** [comment]
![image](https://user-images.githubusercontent.com/14852843/92795680-6b8ef980-f365-11ea-9fa7-e705eba62d81.png)

Still seeing this in a clean blazorserver project after making a change to the file (in codespaces).

**Comment by NTaylorMullen** [comment]
@TanayParikh do you still see this happen on your box? I haven't been able to reproduce.

**Comment by TanayParikh** [comment]
> @TanayParikh do you still see this happen on your box? I haven't been able to reproduce.

I don't think I've seen this recently. We can probably close this out and re-open if it persists.

**Comment by NTaylorMullen** [comment]
Closing out as no longer reproing. Probably fixed this somewhere along the line.
