### ISSUE TITLE
Investigate why SingleFileExe tests fail in Helix

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#25103]
As part of https://github.com/dotnet/aspnetcore/pull/24925 we added tests to verify views + singlefile exe work. These appear to be failing on Helix. I've verified on a couple of different clean machines that the changes work correctly. I suspect the test setup isn't correct. Punting it to get the feature in.

**Comment by javiercn** [comment]
@pranavkm is this still the case?
