### ISSUE TITLE
Can't debug ASP.NET Core 3.1 using IIS Express. Always yields HTTP 404.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25129]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1152944/cant-debug-aspnet-core-31-using-iis-express-always.html)._

---
I don't seem to be able to debug my ASP.NET Core Web API using IIS Express.

I'm always getting a *404 File not found* response when using **IIS Express** configuration.

When I use **Kestrel** for debugging, everything works fine.

! [Kestrel / IIS Express results] (https://i.stack.imgur.com/1nZV1.png)

(Corresponding [discussion can be found here](https://stackoverflow.com/questions/63216066/asp-net-core-web-api-not-served-over-iis-express-why/63300599?noredirect=1#comment112211813_63300599).)

I zipped and added my Visual Studio 2019 solution to this case, so you can reproduce the issue for yourself.

Steps to reproduce:

1. Unzip VS 2019 solution attached and open in Visual Studio 2019.
1. Select "WebAPI" as start project.
1. Select "IIS Express" configuration for debugging.
1. Launch debugger.

Result: No matter which URL you enter, it always returns a _404 File not found_.

Now ...
1. Stop debugging.
1. Select "WebAPI" configuration for debugging.
1. Launch debugger.

Result: Everything works as expected.

---
#### Feedback Bot on 8/17/2020, 07:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Pilchie** [comment]
@vijayrkn - any ideas here?

**Comment by vijayrkn** [comment]
@SetTrend - Thanks for the repro project. Just tried running the app on IISExpress first and it worked but then running on Ketrel gave the 404 error. 

![image](https://user-images.githubusercontent.com/3981619/91085930-061bd880-e603-11ea-945d-d3f717a3999c.png)

So this issue doesn't seem to be specific to IISExpress but the HttpsRedirection in startup not pointing to the right port. 

@BillHiebert & @Tratcher - In case they know why the redirection fails.

**Comment by Tratcher** [comment]
@vijayrkn https redirection shouldn't be related, IIS isn't configured for https either in the launchsettings.json. Did you change the launch settings?

**Comment by Tratcher** [comment]
Oh, I see. That launchsettings gives the servers different paths, `http://localhost:52772/Users` vs `http://localhost:5000`. Why is it set up that way?

**Comment by SetTrend** [comment]
@Tratcher: If your question is addressed to me - that's the default from the ASP.NET Core project template scaffold.

**Comment by SetTrend** [comment]
@Tratcher: Sorry, I misunderstood your question: I have been fiddling around with paths to see if there's any change. Unfortunately, that didn't work out. The different paths don't make a difference.
