### ISSUE TITLE
Buttons not working inside iframe that open blazor page

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25130]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1152544/buttons-not-working-inside-iframe-that-open-blazor-1.html)._

---
<p>Buttons not working inside iframe that open blazor page ,i added buttons that call method in parent  component (save) ,it works fine without iframe but it doesn't work in iframe.</p> <pre><code>&lt;td&gt;</code></pre><pre><code>&lt;button @onclick=&quot;@(e =&gt; { currency. ViewMode = &quot;visible&quot;; currency. EditMode = &quot;collapse&quot;; Save(currency. ISOCode, currency. Name, currency. MinorUnit, false); })&quot; class=&quot;btn btn-primary m-1&quot;&gt;Save&lt;/button&gt;</code></pre><pre><code>&lt;button @onclick=&quot;@(e =&gt; { currency. ViewMode = &quot;visible&quot;; currency. EditMode = &quot;collapse&quot;; })&quot; class=&quot;btn btn-primary m-1&quot;&gt;Cancel&lt;/button&gt;</code></pre><p>

</p><pre><code>&lt;/td&gt;</code></pre>

---
#### Feedback Bot on 8/17/2020, 07:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
