### ISSUE TITLE
After the recent update getting this error in mvc file whenever complied

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25133]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1142502/after-the-recent-update-getting-this-error-in-mvc.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:16.7.0]
Severity	Code	Description	Project	File	Line	Suppression State
Error		rzc generate exited with code -2147450730.	EmployeeManagementPractice	C:\Program Files\dotnet\sdk\3.1.400\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.CodeGeneration.targets	150

---
#### Feedback Bot on 8/10/2020, 02:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/10/2020, 10:38 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
The error code `-2147450730' usually indicates that the runtime isn't installed. Could you try repairing the VS install to see if it address your issue?
