### ISSUE TITLE
Visual Studio Error is poluted with error from SLN when using SLNF

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25131]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1151312/visual-studio-error-is-poluted-with-error-from-sln.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:16.8 Preview1]
To reproduce the issue, just follow how to build dotnet/aspnetcore
https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md

once you managed to run `restore.cmd` and `build.cmd`:
```sh
cd ./src/SignalR
./startvs.cmd
```

And just wait and/or build the solution, and take a peek at the `Error List` panel

Fun fact:
These are from `IntegrationTest` project and are not supposed to get attention from Visual Studio like this as they are supposed to validate that the Parser detects error.

Side effect:
Unable to properly find error when doing anything in the repository

---
#### Feedback Bot on 8/16/2020, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by BrennanConroy** [comment]
Can you please provide more info, I have 16.8 preview1 and it's working fine.
