### ISSUE TITLE
Blazor Components as True Objects, Like WinForms UserControl

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#25154]
I am in the process of porting a WinForms app to Blazor.  The ability to reuse much of my previous code is WONDERFUL!  The one thing I haven't been able to replicate without some custom logic is a UserControl, which is similar to a Blazor component with one major difference, unless I'm missing something fundamental.

May app in Blazor is Single Page.  I render in a panel of that page one of 20 or so Blazor components that reflect the UI of an entity the user has chosen to work on via a list of entities that are select-able in one of the other panels.  As long as the user selects an entity that maps to a Blazor component that's different than the one that's current displayed, all is well.  The new component renders in the layout panel where the old component was rendered, and the user continues.  However, if the user chooses an entity whose Blazor component is the same as the one that's currently rendered, I have to execute a bunch of custom code that causes the Blazor component (parent and children) to re-render with the data that's associated with the new entity the user selected.  In Winforms, I could instantiate and display multiple instances of a UserControl (i.e. Blazor component), each of which had the data associated with the entity encapsulated within it.  Since I can't explicitly instantiate multiple copies of the same Blazor component that is to be rendered in the same location on the page, each with its own data, I have to add custom logic to force the Blazor component to re-render with the "current" data.

Perhaps I have totally missed something.  If not, this strikes me as an important architectural enhancement to Blazor.  Please embarrass me with a currently available solution, or consider this as a future enhancement (by which point I will have created a custom solution designed around events and data states).

Steve

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's unclear what specifically is needed from Blazor here.
Can you please clarify the scenario a bit more?

**Comment by CincySteve** [comment]
This issue is not about something not working, it is about adding a capability to Blazor that enables it to function from the developer’s standpoint like a true object-oriented capability in which the data associated with a Blazor component can be encapsulated within it without custom rendering logic.

As I said, the model for this is a UserControl in WinForms.  UserControls and Blazor Components are conceptually the same in my view, but their implementations are different.  See [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.usercontrol?view=netcore-3.1) for a description of a UserControl.

To illustrate using my app, see the 3 partial screen shots below.  These show a portion of a Blazor Layout that has a user navigation Blazor component on the left (the part in black), and one of a set of “Building Block” Blazor components on the right, each of which contains 4 child Blazor components represented by the boxes.  The particular Building Block that’s displayed on the right is driven by the row the user clicks in the navigator.

If the user is looking at “Financial Info” and then clicks “Gail Job” (which use different Building Block Blazor components), the component on the right will re-rendered to display the Employment component and its data, regardless of where the data is stored (i.e. inside or outside the component).  

But if the user is looking at “Gail Job” and then clicks on “Steve Job” (both of which are associated with the Employment component), the component doesn’t re-render.  In that case, if the data that’s bound to the Employment component (and all its children) is declared/stored outside those components, then the new data associated with “Steve Job” will display, without a re-render, if/when the app overwrites the “Gail Job” data with the “Steve Job” data.  But if the bound data is declared within the component (which is a core object-oriented concept), it will not display without the app forcing the Employment component and all its children to re-render via calls to StateHasChanged() or otherwise update its data, more like a procedural versus object-oriented architecture.

My thought is to enable the developer to wrap Blazor components in a class the developer can instantiate into objects (including multiple instances of the same component, with different encapsulated data, as reflected in Gail Job and Steve Job) and to provide a mechanism to render those objects.  Then, when the user clicks on Steve Job, the app will direct Blazor to render the Steve Job component object, replacing the Gail Job one.

I hope this is clear and a reasonable enhancement idea.  I have developed code that works with the current architecture, but think an enhancement like this is appropriate.

![UserControl1](https://user-images.githubusercontent.com/18602722/91312559-5ec5af80-e782-11ea-8f28-7d9a6156757f.JPG)
![UserControl2](https://user-images.githubusercontent.com/18602722/91312561-5ec5af80-e782-11ea-9725-a1d75045587c.JPG)
![UserControl3](https://user-images.githubusercontent.com/18602722/91312562-5ec5af80-e782-11ea-9773-447f8f6a1773.JPG)

**Comment by SteveSandersonMS** [comment]
Within Blazor, and other UI frameworks that are based around diffing (for example React) to compute updates, the notion of a "component" is *not* quite the same as a WinForms-style "control" instance.

Within WinForms/WebForms and related frameworks, there's a control tree that developers can arbitrarily inspect and mutate. The framework is not maintaining old/new versions of the control tree and is not responsible for diffing to observe those changes.

However, in Blazor (and similar UI frameworks), a component is something that the framework creates for you and manages the lifecycle of, based on its observations about diffing the parent component's render output. It wouldn't make sense to let developers mutate the tree of components directly as this would mean that subsequent diffs become meaningless.

You can still do what you want, it's just that what you need to instantiate is a model object that you create. For example, create a data model that holds lists of `Employee` class instances. Then you can mutate this list arbitrarily. Separately from that you'll have some `<FinancialInfoDisplay>` component that iterates through your list of `Employee` instances and for each one renders (for example) a `<EmployeeInfoDisplay>` component, passing in the `Employee`.

By following this kind of pattern, you get to set up whatever kind of model structure you want, and can freely mutate it any way you like. The UI framework projects this into a set of UI components automatically without you having to be concerned about instantiating or destroying those UI component instances. In effect it's the same thing that you're asking for, just at one additional level of abstraction.
