### ISSUE TITLE
Microsoft.AspNetCore.App.Ref FrameworkList.xml "Path" should be relative to the nupkg root

### ISSUE THREAD

**Issue by wli3** [dotnet/aspnetcore#25167]
### Describe the bug
Microsoft.AspNetCore.App.Ref FrameworkList.xml "Path" should be relative to the nupkg root.

### To Reproduce

In Microsoft.NETCore.App.Ref FrameworkList.xml 

```xml
<File Type="Managed" Path="ref/netcoreapp5.0/Microsoft.CSharp.dll" AssemblyName="Microsoft.CSharp" PublicKeyToken="b03f5f7f11d50a3a" AssemblyVersion="5.0.0.0" FileVersion="5.0.20.25106" />
```

In Microsoft.AspNetCore.App.Ref
```xml
  <File Type="Managed" Path="Microsoft.AspNetCore.Antiforgery.dll" AssemblyName="Microsoft.AspNetCore.Antiforgery" PublicKeyToken="adb9793829ddae60" AssemblyVersion="3.1.0.0" FileVersion="3.100.320.12812" />
```

related https://github.com/dotnet/sdk/issues/12098

**Comment by dougbu** [comment]
@wtgodbe I confirmed FrameworkList.xml files from Microsoft.NETCore.App.Ref and Microsoft.WindowsDesktop.App.Ref use relative `Path` values, not just the filename. We're the odd ones out.

@wli3 it seems little or nothing actually uses `Path` values.
1. What might use the values in the future❔
2. Did you find "other targeting pack producers having this problem"❔
3. Are we at all likely to break someone somewhere who expects just a filename❔

**Comment by wli3** [comment]
I need to add a hack to workaround this in SDK https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L252

please fix this so I can remove the hack

**Comment by wtgodbe** [comment]
Other repos use https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/src/CreateFrameworkListFile.cs, while we carry our own custom version of that task: https://github.com/dotnet/aspnetcore/blob/c8e249e8d9a532f8e2773d80ca3310478961cbeb/eng/tools/RepoTasks/CreateFrameworkListFile.cs. We should be able to just start using the Arcade task.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/26622

**Comment by wtgodbe** [comment]
@wli3 should I backport the fix to 3.1?

**Comment by wli3** [comment]
only 6.0 branch is good enough. I will change the logic starting 6.0

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/26622
