### ISSUE TITLE
AzureADB2C forcing implicit flow in custom sign up action

### ISSUE THREAD

**Issue by Krangth** [dotnet/aspnetcore#25171]
We want to have a special link to take the user directly to a register user flow. 
We followed the code here https://github.com/dotnet/aspnetcore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Azure/AzureAD/Authentication.AzureADB2C.UI/src/Areas/AzureADB2C/Controllers/AccountController.cs#L26

However, when our custom controller issues the challenge, the 'response_type' is always 'id_token' instead of 'code' and we get an error about implicit flow being disabled.

How can we specify the 'response_type' and probably client_id scope?

**Comment by blowdart** [comment]
This is probably best asked of the AAD folks.

I'd strongly suggest looking at swapping to I[dentity.Web](https://github.com/AzureAD/microsoft-identity-web/), the new way to interact with AD, which will come out of preview at the same time as we launch .NET 5, and will be in the .NET 5 templates.
