### ISSUE TITLE
Missing dll's after dotnet publish for a blazor wasm app

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#25188]
Running `dotnet publish` for a blazor wasm client and server app including grpc web results in some dll's missing.
The missing dll's in this case are e.g. `Grpc.Core.Api`, `Grpc.Net.Client`, and `Grpc.Net.Common`.

Probably due to the `Compressing Blazor WebAssembly publish artifacts. This may take a while...` step in a publish?

However, this leads to a crash in the client application:
![image](https://user-images.githubusercontent.com/5054780/90059174-094dc500-dce3-11ea-8731-97d5810d688b.png)

### To Reproduce:

1. Create a simple blazor wasm client and server with grpc web.
2. Run `dotnet publish -c Release -f net5.0 -o ./app`
3. Run the app

### Configuration

```sh
λ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.6
 Commit:    0684df3a5b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1
```

**Comment by ElderJames** [comment]
After I upgraded to Preview 8, blazor wasm throw an error `MONO is not defined` at debug running.

**Comment by mkArtakMSFT** [comment]
> This isn't a runtime issue. Sounds like something in blazor preview 7 linking wasn't including all referenced assemblies.
> 

@lewing, @pranavkm was there any follow-up work happening here from your side?

**Comment by msschl** [comment]
Still not fixed for 5.0 rc-1

**Comment by msschl** [comment]
Adding `<PackageReference Include="Grpc.Core.Api" Version="2.32.0" />` resolves the issue for a publish.
But it also breaks local development:

![image](https://user-images.githubusercontent.com/5054780/93383772-6699e080-f864-11ea-940e-e32d2f86d22f.png)

**Comment by pranavkm** [comment]
@msschl do you have a sample app that reproduces the issue? I just tried updating one of our samples to rc1 - https://github.com/SteveSandersonMS/BlazorGrpcSamples/pull/3 - and it appears to be working fine both during build and publish.

**Comment by pranavkm** [comment]
FYI @JamesNK in case this sounds familiar.

**Comment by JamesNK** [comment]
I've never seen this before.

**Comment by msschl** [comment]
Ok I found the issue:

In my `Client.csproj` I referenced the `Grpc.Net.Client` with the attribute `PrivateAssets="All"` specified. This caused the error.
After removing the attribute `dotnet publish` works as expected. 👍🏽
