### ISSUE TITLE
Invalid guid parameter handling.

### ISSUE THREAD

**Issue by huseyingoztok** [dotnet/aspnetcore#25187]
I'm using aspnet core 3.1. When the type of my action parameters is guid, I want to redirect HttpNotFound if the value that comes up is invalid guid. 

`[HttpGet ("{id: guid} / {xId: guid}")] `

this attribute provides this for me, but I want it to be for all actions.

**Comment by javiercn** [comment]
@huseyingoztok thanks for contacting us.

If we understand correctly, what you want is to return a 404 on all actions where you've defined a GUID parameter and it's not a valid GUID?

The way to achieve that is by defining the constraint inline. Routing doesn't know about what types the values you want to use are and it only cares about the shape of the string coming in. 

For that reason you need to specify the constraint inline within the parameter, there's no way to do it globally.

That said, you can write an ApplicationModelConvention, look at the parameters on an action and update the route templates to include the constraint on the parameters you want to bind as GUIDs.
