### ISSUE TITLE
View Blazor Rendered Html

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#25195]
I have tried to find a way to view the html rendered by a Blazor component, but haven’t found one.  “View page source” in the browser only shows the index.html.  This would be a big debugging aid.  If this doesn’t exist, please consider this to be a feature request.  Otherwise, please direct me to the feature.  Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You can use the `Elements` tab in the browser dev tools to view the DOM.

**Comment by CincySteve** [comment]
@mkArtakMSFT I appreciate the suggestion to use the Element tab in dev tools and have been doing that to understand what my code is rendering.  But unless I am not seeing how to use it efficiently (certainly a real possibility despite having played with the Chrome Settings and using it a fair amount to look at my rendered html), I find it is tedious to have to expand the <app> tag down to the html I need to look at.  

I'm thinking it is a reasonable suggestion to add a Blazor feature request related to this, obviously not at a high priority given all the other issues that need to be address.  What would seem most straightforward is for the OnAfterRender event to have an overloaded version that includes a derivative of  EventArgs that included a string of the rendered html.  That would give developers easy visibility to what their component code is doing, without deprecating the current OnAfterRender event.  And it would work regardless of what browser the developer is using.
