### ISSUE TITLE
NavigationManager.NavigateTo ignores base URI

### ISSUE THREAD

**Issue by MV10** [dotnet/aspnetcore#25204]
I'm altering a large Blazor server-side app which was originally developed under IIS Express (with localhost etc) to support deployment to an IIS virtual directory. Parts of the app have data-driven navigation where pages are referenced just as they're declared in the `@page` directives (e.g. `/mycontent`). We've specified the virtual directory in startup with `UsePathBase` so we were surprised when calls like this ignore the base:

```csharp
NavManager.NavigateTo("/mycontent", forceLoad: true);
```

Instead of `https://site.com/virtualdir/mycontent` it navigates to `https://site.com/mycontent` which 404s.

It's easily fixed, but is this intentional, or is this a bug?

(Edit: Probably worth noting that `ToAbsoluteUri` also ignores the base.)

**Comment by javiercn** [comment]
@MV10 thanks for contacting us.

You need to setup the base url with the document `base href` tag on your `_Host.cshtml` that's the only thing Blazor will use to determine the base url.

**Comment by MV10** [comment]
@javiercn thanks, I have specified `base href`, but I used `~/` ... is that a problem? I confirmed it expands appropriately when it reaches the browser.

**Comment by mkArtakMSFT** [comment]
You cannot use `/` to navigate
