### ISSUE TITLE
Using subfolders breaks WebApplicationFactory.CreateClient() in .NET 5.0

### ISSUE THREAD

**Issue by marcantoinebouchard** [dotnet/aspnetcore#25201]
### Describe the bug
Using subfolders breaks WebApplicationFactory.CreateClient() in .NET 5.0.

### To Reproduce
https://github.com/marcantoinebouchard/TestAPI
1. Create an empty solution
2. Create an ASP.NET Core 5.0 WebApi project under a subfolder (here "WeatherAPI" under "./Weather/")
3. Create a xUnit test project under the same folder
4. Write a simple test using the WebApplicationFactory (add a reference to Microsoft.AspNetCore.Mvc.Testing and to the project created in step 2)
5. Run the test

System.IO.DirectoryNotFoundException is thrown. It works well targeting .net core 3.1.

### Exceptions
  Message: 
    System.IO.DirectoryNotFoundException : C:\Users\{...}\source\repos\TestAPI\WeatherAPI\
  Arborescence des appels de procédure: 
    PhysicalFileProvider.ctor(String root, ExclusionFilters filters)
    PhysicalFileProvider.ctor(String root)
    HostBuilder.CreateHostingEnvironment()
    HostBuilder.Build()
    WebApplicationFactory`1.CreateHost(IHostBuilder builder)
    WebApplicationFactory`1.EnsureServer()
    WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
    WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
    WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
    WebApplicationFactory`1.CreateClient()

**Comment by mfjerome** [comment]
We hit this issue when trying to upgrade our solution to .NET 5-preview.7, which include integration tests leveraging the `WebApplicationFactory` to create a test server.

**Comment by marcantoinebouchard** [comment]
This problem is fixed using RC1

**Comment by SteveSandersonMS** [comment]
Thanks, closing as fixed.
