### ISSUE TITLE
Update to RC1 SDK

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#25214]
Once the RC1 SDK is available, we should use it. Includes some new analyzers that will require https://github.com/dotnet/aspnetcore/issues/25213 to be resolved, as well as some code that should improve the reliability of our dotnet-watch tests (https://github.com/dotnet/aspnetcore/issues/24841). We'll also want to be on VS16.7 by then

CC @pranavkm @BrennanConroy @dotnet/aspnet-build

**Comment by wtgodbe** [comment]
Previous work is here: https://github.com/dotnet/aspnetcore/pull/25081

**Comment by dougbu** [comment]
Reassigning since @pranavkm has #25421 open and close to ready

**Comment by dougbu** [comment]
Thanks @pranavkm for 690c7173146129d0e595d0dd075cbaa27ed84ebd❕
