### ISSUE TITLE
JSInterop tests fail after updating SDK

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#25213]
Updating to a new SDK (`5.0.100-rc.1.20420.10` or newer) brings in new analyzers that complain about https://github.com/dotnet/aspnetcore/blob/faf1d80af1b0521ed120f767efd630999200a02e/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs#L91. After updating to:

`var tcs = new TaskCompletionSource<TValue>(TaskCreationOptions.RunContinuationsAsynchronously);`

Tests like `Microsoft.JSInterop.Infrastructure.DotNetDispatcherTest.EndInvokeJS_WithNullValue` fail with `expected true, got false`. It appears the tests relied on that line being inline instead of async. We should decide if we want to remove the async continuation, or fix up the tests. See https://github.com/dotnet/aspnetcore/pull/25081/files#r474412604

We'll want to update to the RC1 SDK once it ships, so we should try to get this fixed by the beginning of rc2

**Comment by pranavkm** [comment]
@SteveSandersonMS can you help with this?

**Comment by captainsafia** [comment]
Closing this as it is now done.
