### ISSUE TITLE
[Blazor server side] have two different ILogger between "client" code and "server" code

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#25228]
Hello guys, I have a blazor app which can run in client and server mode.

In client mode, I have an ILogger implementation on the server, and another ILogger implementation for the client app. It's perfect because i want to log differently, not the same information, not at the same place.

In server mode, because it's a unique app, i have an unique implementation of ILogger. so the question is : What the best way to do that ?

For now, The best idea i have is to create my own implementation of ILogger with two different method LogServer and LogClient.
For the unhandled exception, it will fall in one of the classic Ilogger method Log, and i have to decide which "mode" i have to use, it seem i can't make better.

Do you have better implementation or some guideline for that ?

Thanks !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

What are you trying to achieve, log at different levels depending on whether you are using client/server?

**Comment by julienGrd** [comment]
No it's a bit more tricky.

i want the same result wether i run in server mode or in webassembly mode. 

I want to log "by client" on client app (not client mode, client app, so for example all the code inside my components, the events etc), for example create one file by login and date.
On server app I want to have a unique file by date, not depending on which client what at the origin of the exception.

My other idea is to scope everything by session/signalr id, even the "server" code. Maybe it will be more simple ? and if there is no id, it will be a "general" server exception so i will be log it in a general file. What about it ?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
