### ISSUE TITLE
UseHttpsRedirection and MapHealthChecks

### ISSUE THREAD

**Issue by mjnorman** [dotnet/aspnetcore#25221]
### Describe the bug
When utilizing HttpsRedirection, MapHealthChecks, and ForwardHeaders there should be a way to exclude health checks from https redirection.  This is especially useful as when behind an nginx firewall handoff for SSL as in hosted environments such as Cloud Foundry.  The Load Balancer is going to check the health endpoint of its configured servers just using a `GET /health HTTP` for example since its members are added as HTTP.  When issuing a call to the health endpoint the middlewares redirect the call to HTTPS, and as such the health check fails because it is not getting the expected `200` and instead receives a `307`.

### To Reproduce
Can be reproduced using the sample projects [here](https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample) by just adding `services.AddHttpsRedirection` and `app.UseHttpsRedirection()` to the `BasicStartup.cs` file.

### Further technical details
<details>
<summary>Click to expand</summary>
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.102 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  2.2.301 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
</details>

**Comment by Tratcher** [comment]
If all traffic is coming through nginx, have you considered moving your https enforcement there?

**Comment by Tratcher** [comment]
Implementation note: exclusions for routes/endpoints are hard in this case as the UseHttpsRedirection component is usually placed early in the pipeline, before the routes are evaluated.

**Comment by mjnorman** [comment]
I can possibly get the monitor query changed to https.  It could also be possible to remove the ssl handoff and carry it through to the app. This would be an exception for the way the company has it configured. I was hoping there might have already been a way to make the exclusion, but expected it to be difficult since like you said, it is early in the pipeline.

________________________________

**Comment by Tratcher** [comment]
I meant something like this: https://linuxize.com/post/redirect-http-to-https-in-nginx/

**Comment by mjnorman** [comment]
I guess that could work.  However it seems problematic to attempt to use nginx buildpack and dotnetcore buildpack for this scenario in a Cloud Foundry environment, but will definitely try this.  

Thinking along different lines, would mimicking the HttpsMiddleMiddleware work as well?  I am simplifying here due to the fact that ssl will always be 443 due to handoff at LB in our scenario.  Most is straight copy/paste from the HttpsMiddleMiddleware.


```c#
    public class EnforceHttpsMiddleware {
        private readonly RequestDelegate _next;

        public EnforceHttpsMiddleware (RequestDelegate next) {
            _next = next;
        }

        public async Task InvokeAsync (HttpContext context) {

            if (!context.Request.Path.Equals("/health") && !context.Request.IsHttps) {
                var host = context.Request.Host;
                host = new HostString(host.Host);

                var request = context.Request;
                var redirectUrl = UriHelper.BuildAbsolute(
                    "https",
                    host,
                    request.PathBase,
                    request.Path,
                    request.QueryString);

                context.Response.StatusCode = StatusCodes.Status307TemporaryRedirect;
                context.Response.Headers[HeaderNames.Location] = redirectUrl;

                Log.Debug("Redirecting to https: {redirectUrl}", redirectUrl);

            }

            // Call the next delegate/middleware in the pipeline
            await _next (context);
        }
    }
```

**Comment by Tratcher** [comment]
Yes, custom middleware is always an option when you are sniffing for specific paths. That can be hard to generalize though.

Note you need to return in that if block so you don't call next for http requests.

**Comment by mjnorman** [comment]
Ok thank you very much for your feedback, and the catch on the missing return.
