### ISSUE TITLE
[5.0] Allow Enum.IsDefined validation to be performed during the model-binding phase

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#25233]
Currently in 3.1, model binding succeeds if any integer value is specified for an enum, **even if that value is not defined in that enum**. For example:

```csharp
public enum FooBar
{
    Baz = 1,
    Quux = 2,
};

var badFooBar = (FooBar)0; // assume 0 is passed through from an http request - this succeeds in the model-binding phase
```

The way around this is by using a validator that calls `Enum.IsDefined`, which is simple to implement. But validation happens later in the pipeline, thus you incur an unnecessary performance penalty on a request that is going to be rejected anyway. Another issue is that the validator's error message is going to be different to the model binder's error message.

Will 5.0 support rejecting enums with undefined values **in the model-binding phase**? Looking at the source of [`EnumConverter`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs) in 5.0 it seems like the answer is "no", in which case my follow-up question: is this something that it would be valuable to support?

(Apologies if this should've been asked in corefx instead - I'm not entirely sure where the boundary between STJ and model-binding lies, and hence who would potentially be responsible for this.)

**Comment by pranavkm** [comment]
With input formatting, MVC relies on the formatter to deserialize the input body, in your case System.Text.Json. If you need to customize the behavior here, an issue in the dotnet/runtime would be appropriate. While they address the issue, you could consider authoring a custom converter to handle this as you see fit.
