### ISSUE TITLE
Blazor Client-Side consuming Web API with Windows Authentication

### ISSUE THREAD

**Issue by smarteez17** [dotnet/aspnetcore#25231]
I being have some problems calling an API with has Windows Authentication nothing is working. The set up I have a Standalone API hosted and In the services I want to call . Please can you provide and example as I look on the net and cant find anything
here my code  

 public class UserData : IUserData
    {
        private readonly HttpClient _httpClient;

        public UserData(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<List<Menu>> GetAllMenu()
        {

            var response = await _httpClient.GetAsync("https://localhost:44372/api/user/get");
            var content = await response.Content.ReadAsStringAsync();

            var products = JsonSerializer.Deserialize<User>(content, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return products.menus;
        }
    }
}

In Angular we do it as following how do we do it in blazor 

  getUser(): Observable<User> {
    const httpHeaders = new HttpHeaders();
    httpHeaders.append('Content-Type', 'application/json');
    return this.httpClient.get<User>(environment.baseUrl + environment.userUrl, {
      headers: httpHeaders,
      withCredentials: true,
    });
  }

**Comment by mkArtakMSFT** [comment]
@smarteez17 try this:

```csharp
var request = new HttpRequestMessage(...);
request.SetBrowserRequestCredentials(BrowserRequestCredentials .Include);
```
