### ISSUE TITLE
[Blazor Server side] circuit is disconnected after browser refresh even with a beforeunload

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#25236]
Hello guys, in my blazor app i have implemented a beforeunload event in js to prevent the user leave the app or refresh accidentaly.

````
$(window).on("beforeunload", (function () {
    return "êtes vous sur de vous vouloir fermer l'application ?";
}));
````

I web assembly mode, it works great.

But in server mode, the circuit is disconnected before the user decide what to do.

 I see it by put a breakpoint in the Dispose of my services.

I don't know which piece of code run the disconnect, the stack trace is external (  i see for example this in the stack	Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry.TerminateAsync(Microsoft.AspNetCore.Components.Server.Circuits.CircuitId circuitId)

It is a normal behavior ? there is a workaround ?

thanks !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please confirm what version of Blazor you're using?

**Comment by mkArtakMSFT** [comment]
Also, please make sure you register the `beforeunload` handler before any other registered handlers for that event. Also consider using `preventDefault` to stop propagation: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by julienGrd** [comment]
@mkArtakMSFT In net 5.0 preview 6 but same thing in preview 8. I put a preventDefault but same effect

**Comment by captainsafia** [comment]
@julienGrd Thanks! The fact that it repros on both versions means that it is not related to some changes we recently made to this disconnect logic.

I'd recommend trying a few things:

1. Make sure you define your event listener before the `blazor.server.js` script is loaded.
2. Set `{ capture: true }` in the options for your event listener.
3. Invoke `event.stopImmediatePropogation()` at the start of your event listener callback.

Try these things out one-by-one. If none of them work, let us know and we can dig in further.

**Comment by julienGrd** [comment]
@captainsafia thanks it finally works by putting event.stopImmediatePropagation(); in the event.

````
window.addEventListener('beforeunload', (event) => {
                // Cancel the event as stated by the standard.
                event.preventDefault();

                event.stopImmediatePropagation();
                // Chrome requires returnValue to be set.
                event.returnValue = 'êtes vous sur de vous vouloir fermer l\'application ?';
            });//, true

````

subject is closed !
