### ISSUE TITLE
[Blazor WASM] Breakpoints not being hit in Visual Studio

### ISSUE THREAD

**Issue by Gaz83** [dotnet/aspnetcore#25232]
### Describe the bug
My issues is exactly the same issue as this one [[Blazor WASM] Breakpoints not being hit in Visual Studio #22179](https://github.com/dotnet/aspnetcore/issues/22179)

Breakpoints do not hit in Visual Studio when debugging Blazor WASM client projects.

### To Reproduce

- Using Visual Studio create a new Blazor WebAssembly project without HTTPS and with ASP.Net Core hosted
- The solution should be created with three projects: x.Client, x.Server, and x.Shared
- Open Counter.razor file in the Client project and set a breakpoint on currentCount++ line
- Start the Server application by hitting F5 and observe the breakpoint
- The breakpoint will be disabled with message "The breakpoint will not currently be hit. No symbols have been loaded for this document."
- Use the application in the browser- navigate to Counter page and click "Click me" button
- The UI will update correctly, however, the breakpoint will not get hit in Visual Studio

### Further technical details
ASP.NET Core 3.1.7
Visual Studio 2019 16.7.2
Microsoft.AspNetCore.Components.WebAssembly.Templates 3.2.1

**Comment by Gaz83** [comment]
Just to add, been speaking to someone on chat and their output from the server is different from mine.

I get this

info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Git Repositories\BlazorApp2\BlazorApp2\Server

Whereas they get this

info: Microsoft.Hosting.Lifetime[0]
Now listening on: `localhost:5000`
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
Content root path: C:\Users\miste\source\repos\BlazorApp8\Server
info: Microsoft.Hosting.Lifetime[0]
Now listening on: `127.0.0.1:50973`
info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
Content root path: C:\Users\miste\source\repos\BlazorApp8\Server\bin\Debug\netcoreapp3.1\BlazorDebugProxy\
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
Request starting HTTP/1.1 GET `localhost/…`
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
Executing endpoint '/ws-proxy HTTP: GET'

**Comment by Gaz83** [comment]
Looks like a repair install of visual studio solved the problem. 
I noticed that Visaul Studio code had no issues and, when debugging, it always launched a new browser window. 
Visaul Studio was always launching a new tab on my existing browser windows.

After repair, visual studio started launching a new browser window. Not sure if that means anything to anyone.

**Comment by mkArtakMSFT** [comment]
Glad that you've got your issue solved. Closing as there is no pending action here.
