### ISSUE TITLE
[Blazor] Strategy for non reentrancy on dom event 

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#25240]
Hello guys, i meet problems on my blazor app with the non reentrancy
indeed, when i double click on a button, the event behind is launch twice. and it's normal. 

to avoid that, actually i do
````
private bool _isLoading= false;

        protected void MyEvent()
        {
            if (!_isLoading)
            {
                  _isLoading = true;
                 MyTreatment()
                _isLoading= false;
             }

````

I would like to know if there is a guideline or helpers i can use to apply this logic on non reentrency, because write this kind of code in all events of my app is a bit a pain...

thanks !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

We don't have anything out of the box for that (other than guidance, which is to do what you are doing).

If you find yourself doing that a lot, you can potentially write a component that takes care of the reentrancy concerns and have it be the one that deals with the event. Something like:
```razor
<Handler @onclick="HandleClick" Context="loading">
   <input type="button" disabled="@loading" />
</Handler>
```

**Comment by julienGrd** [comment]
OK its something i was expected, i think i will deal manually on each event, in any case i have to update my code in each place.

Subject is close for me
