### ISSUE TITLE
Blazor deep linking does not work with parameters that include a dot

### ISSUE THREAD

**Issue by kdubau** [dotnet/aspnetcore#25249]
### Describe the bug
Routes with parameters will 404 if the parameter value contains a dot (`.`). 

### To Reproduce

Repro repo: https://github.com/kdubau/BlazorDeepLinkBug

Deep link navigate to https://localhost:5001/counter/value - it works as expected.

Now deep navigate to https://localhost:5001/counter/val.ue - it 404s.

### Exceptions (if any)

I don't see anything logged about it.

### Further technical details
I have reproduced this in .NET Core 3.1 and .NET 5 Preview 7 in Visual Studio 2019 16.8 Preview.

```.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013437 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19374.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download```

**Comment by kdubau** [comment]
Okay I found this: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#routing-with-urls-that-contain-dots 

But I am unsure how to make this work in my Blazor WASM app hosted with ASP.NET Core.

While that doc suggest Blazor Server, I tired it anyway and got:

```System.InvalidOperationException: Invalid template '{**AppId}'. The character '*' in parameter segment '{**AppId}' is not allowed.```

**Comment by kdubau** [comment]
It seems to work just fine if we include a trailing slash like so:  https://localhost:5001/counter/val.ue/

**Comment by javiercn** [comment]
@pranavkm thanks for contacting us.

By default trailing segments that contain a dot are "considered" files by the system, hence we don't fallback to render a razor page. You can change this by specifying whatever pattern you want in endpoints.MapFallbackToFile. The default pattern is {**path:nonfile} and that's what causes the routes with the . in the last segment to be ignored

**Comment by pranavkm** [comment]
Using this issue to track adding a doc article for this. @guardrex in case you have a bit of extra time.

**Comment by guardrex** [comment]
@kdubau We have some new content for catch-alls with WASM at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0#catch-all-route-parameters

... for .NET 5 preview at the upcoming RC1 (mid-September).

> You can change this by specifying whatever pattern you want in endpoints.MapFallbackToFile

I'll get the `endpoints.MapFallbackToFile` alternative behavior option covered, but I'm not going to be on RC1 until RC1 actually lands.

**Comment by guardrex** [comment]
@pranavkm ... You can close this now. I just put up https://github.com/dotnet/AspNetCore.Docs/pull/19764.

If ur busy, you don't need to look at it ... I'll get a review on it after RC1 lands.

If you have a minute tho to :eyes: that now, I'll adjust to any feedback you have.
