### ISSUE TITLE
ASP.NET Core Authentication app - UseHttpsRedirection on 443 causes too many redirects error

### ISSUE THREAD

**Issue by constantintaivan** [dotnet/aspnetcore#25255]
Hello,

I'm deploying an authenticated ASP.NET Core 3.1 app to Ubuntu server based on Apache2 and Kestrel configuration.
Locally, I'm able to have a seamless login flow keeping same https protocol. 
When deployed, since Index page has the Authorized attribute, my app was redirected to http (I need to keep https), but when accessing directly the Login page the https protocol is kept as well as is happening with Anonymous pages (so the certificate is already in place).
I did use the UseHttpsRedirection logic as recommended but ended up in a redirect loop (ERR_TOO_MANY_REDIRECTS). I found that might be related to apache2 redirection and used the X-Forwarded-Proto as following, but without success.

<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

Is there any settings I'm missing for Apache2 or app itself?

Refs:
https://github.com/dotnet/aspnetcore/issues/3086
https://github.com/dotnet/aspnetcore/issues/3176

Thank you

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

**Comment by constantintaivan** [comment]
It's fixed now, https is kept as expected. 
Solved also the wrong redirect to Google OAuth Sign-In as I was getting the error on Correlation failed-Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler, due to the missing Secure cookie attribute (SameSite=None scenario). I was pretty sure if fixing the redirect issue I was able to sign in on Chrome too.

Thank you very much!
