### ISSUE TITLE
[Templates] Update ShowProfile to avoid Base64 encoding images

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#25254]
https://github.com/dotnet/aspnetcore/blob/release/5.0-preview8/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/ShowProfile.razor#L71-L72

**Comment by pranavkm** [comment]
@javiercn can you follow up with @JunTaoLuo ?

**Comment by pranavkm** [comment]
@mkArtakMSFT can you be responsible for making sure this gets resolved?

**Comment by JunTaoLuo** [comment]
Should someone more familiar with the blazor templates be making this change? As for this particular fix, as @javiercn mentioned in email:

> As to how to update the code, we can do two things:
> 1) Show something different than the image and avoid this problem all together
> 2) Create an API endpoint on the server that takes some id or similar and use that to issue a query to graph and return the image directly. Something like
> 
>  ```C#
> [HttpGet("photo)]
> public IActionResult Photo()
> {
>   var photo = await GraphServiceClient.Me.Photo.Content.Request().GetAsync();
>   return File(photo,"image/jpeg");
> }
> ```
> ```html
> <img style="margin: 5px 0; width: 150px" src="photo" />
> ```
> On the image tag you set the source image to a link on the server and on the server you retrieve and serve the image as a stream, the browser will automatically do the request to the server to show the image when the tag is inserted on the page.

I could try to make the change verbatim but I'm not familiar with these templates soI would prefer to defer to someone else more knowledgeable.

**Comment by mkArtakMSFT** [comment]
We're going to remove the Base64 image section out of the template.

**Comment by pranavkm** [comment]
Resolved in 5.0 using https://github.com/dotnet/aspnetcore/pull/26253
