### ISSUE TITLE
SignalR HubConnection is unable to execute the negotiate call, receiving HTTP error 413: Payload Too Large

### ISSUE THREAD

**Issue by alexeystrakh** [dotnet/aspnetcore#25262]
### Describe the bug

In our Ionic application, we use [aspnet/signalR](https://www.npmjs.com/package/@aspnet/signalr) package to connect our backend service running asp.net core (netcoreapp3.1) web API. On the backend we use `Microsoft.AspNetCore.SignalR` package (1.1.0) and `Microsoft.Azure.SignalR` (1.5.0). For most accounts the application works fine but for specific accounts it breaks with the inability to establish a connection to SignalR service: HTTP error 413 "Payload Too Large", in response I can also see the error details: `AccessToken must not be longer than 4K.`. I have verified the access token, it's well below the limit, it's 1k in size. Please find the sample of HTTP request and response for the `negotiate` API call:

```
POST /signalr/negotiate?AppBundleId=my.app.bundle.id HTTP/1.1
Host: mywebapi.azurewebsites.net
Connection: keep-alive
Content-Length: 0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
X-Requested-With: XMLHttpRequest
Authorization: Bearer <my_bearer_token_1k_length>
Content-Type: text/plain;charset=UTF-8
Accept: */*
Origin: http://localhost:8100
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8100/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

And the response is HTTP error 413 "Payload Too Large":

```
HTTP/1.1 413 Payload Too Large
Transfer-Encoding: chunked
Vary: Origin
Server: Kestrel
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:8100
Request-Context: appId=cid-v1:app-id-guid
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=app-afinity-id;Path=/;HttpOnly;Domain=mywebapi.azurewebsites.net
Date: Wed, 26 Aug 2020 00:46:37 GMT
```

### To Reproduce

1. Start the app and wait until the HubConnection.Start method is expected
2. Monitor HTTP requests

Result: HubConnection is unable to connect with error `Payload Too Large`, the negotiate request returns 413 error
Expected result: HubConnection is able to connect

### Exceptions (if any)

- HubConnection is unable to connect with error `Payload Too Large`
- The negotiate request returns 413 error and error in response `AccessToken must not be longer than 4K.`

### Further technical details
- ASP.NET Core version: netcoreapp3.1
- The IDE: VS

**Comment by BrennanConroy** [comment]
https://github.com/Azure/azure-signalr/issues/249

**Comment by alexeystrakh** [comment]
hi @BrennanConroy thanks for the reference, it looks similar, my error is 413 in my case my effect looks the same. I also found a similar issue on (SO here)[https://stackoverflow.com/questions/56769490/accesstoken-must-not-be-longer-than-4k]. That's why I verified the total size of headers and specifically the AccessToken size which is around 1k (well below 4k limit). I posted the exact request with header above, just stripped the JWT token for security reasons but its size is 1k.

Do you still think it can be connected and I need to decrease the header size?

**Comment by BrennanConroy** [comment]
> Do you still think it can be connected and I need to decrease the header size?

Yes, if you have further issues follow up on the Azure/azure-signalr side.
