### ISSUE TITLE
Blazor Server app initial connection issues when the web servers are behind a load balancer

### ISSUE THREAD

**Issue by jkarra2020** [dotnet/aspnetcore#25269]
Hello, I am trying to deploy a Blazor **server** application on Pivotal cloud foundry - with Nginx reverse proxy and Kestrel web server. When I try to run on more than 1 instance, the websocket connection intermittently fails (works fine with 1 instance). 

I did read about the Azure SingalR service, but is not an option since we are not deploying the app to Azure. I tried out the Redis backplane, but we could not get to set the nginx with sticky session as our org does not permit that.

I tried playing around with the HubConnection settings, specifically using websocket transport and Kestrel settings but that did not help much.

I understand that forcing the clients to use Websockets and skipNegotiate set fixes the issue on Clients. Is there anything similar that I could do for the server app.

What are the other options I could try. Please help me with getting this to work.

Here is the error message I got from the Developer tools -
Websocket connection to failed: Error during webSocket handshake: unexpected response code: 404
Filed to start the ttransport "WebSockets" Error: There was an error with the transport.

Network HRM from developer tools attached.
[WebSocketsErrorHRM.txt](https://github.com/dotnet/aspnetcore/files/5129404/WebSocketsErrorHRM.txt)

**Comment by javiercn** [comment]
@jkarra2020 thanks for contacting us.

Your load balancer needs to have sticky sessions enabled. Check [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1#linux-with-nginx) for details

**Comment by jkarra2020** [comment]
Unfortunately, our organization doesn't let sticky session enabled on the Nginx load balancer. Is there any other way we can get this working.

**Comment by javiercn** [comment]
@jkarra2020 unfortunately no. This is a requirement for server-side Blazor since it needs to support reconnection to the server if the client looses the connection.

**Comment by jkarra2020** [comment]
Thanks for your response.
