### ISSUE TITLE
HttpRequestException is too vague for HubConnection.StartAsync

### ISSUE THREAD

**Issue by BrannonKing** [dotnet/aspnetcore#25278]
The authentication module on my SignalR server gives a variety of different status codes depending upon what kind of authentication failure there was. However, the SignalR client gives me no way to extract the specific status code returned. Instead, the `StartAsync` method throws a `HttpRequestException` that might have the status code textually. Can you expose the actual status code returned?

**Comment by BrennanConroy** [comment]
Looks like a dupe of https://github.com/dotnet/aspnetcore/issues/17304
Have you tried this in 5.0? It looks like the linked Runtime issue has been fixed so there should be status codes now.

**Comment by BrannonKing** [comment]
I agree that the merged fix is sufficient. Thanks for pointing that out. Now I just need to update to .NET 5...
