### ISSUE TITLE
CSS Isolation pseudo elements

### ISSUE THREAD

**Issue by limefrogyank** [dotnet/aspnetcore#25276]
### Describe the bug
Using the new CSS Isolation techniques in blazor, almost everything works well except for psuedo-elements `::after` and `::before`.  If I have this element layout inside a component:
```
<div class=@($"ms-Checkbox {(_isChecked ? "is-checked" : "")} {(_reversed ? "reversed" : "")} {(Disabled ? "is-disabled" : "")} {(_indeterminate ? "is-indeterminate": "")} {ClassName}")
     style=@Style
     @ref="RootElementReference">
    <input type="checkbox"
           id=@Id
           class=@($"ms-Checkbox-input mediumFont" )
           checked=@_isChecked
           disabled=@Disabled
           @onchange="InternalOnChange"
           aria-disabled=@Disabled
           aria-label=@AriaLabel
           aria-labelledby=@AriaLabelledBy
           aria-describedby=@AriaDescribedBy
           aria-posinset=@AriaPositionInSet
           aria-setsize=@AriaSetSize />
    <label class=@($"ms-Checkbox-label")
           for="@Id">
        <div class=@($"ms-Checkbox-checkbox")>
            <i class=@($"ms-Checkbox-checkmark ms-Icon ms-Icon--CheckMark") aria-hidden="true"></i>
        </div>
        <span class=@($"ms-Checkbox-text")>@Label</span>
    </label>
</div>
```
Then when I try to add an `::after` pseudo element to anything internal, it won't work.  Something like this:
```
.ms-Checkbox.is-indeterminate ::deep .ms-Checkbox-checkbox::after {
        content: "";
        border-radius: var(--effects-RoundedCorner2);
        position: absolute;
        height: 10px;
        width: 10px;
        top: 4px;
        left: 4px;
        box-sizing: border-box;
        border-width: 5px;
        border-style: solid;
        border-color: var(--semanticColors-InputBackgroundChecked);        
        transition-property: border-width, border, border-color;
        transition-duration: 200ms;
        transition-timing-function: cubic-bezier(.4, 0, .23, 1);
    }
```
I have to use the `::deep` combinator for any sub-element's `::after` or `::before` pseudo-element to work.  Without the `::deep`, the resulting scoped-styles.css has the blazor root element attribute stuck on the end of `::after`.  
```
.ms-Checkbox.is-indeterminate .ms-Checkbox-checkbox::after[b-u37k08jd7q] {
```
With the `::deep` combinator, it puts the blazor root element attribute on the preceding set of class names.
```
.ms-Checkbox.is-indeterminate[b-u37k08jd7q]  .ms-Checkbox-checkbox::after {
```
This seems like a workaround to me.  I had assumed the purpose of `::deep` was to allow styles to affect child **components**, not child elements within the same component.  The rest of my child elements are styled properly without the `::deep` tag.  

### To Reproduce
Create a component that uses the `::after` pseudo-element on a sub-element within the component.  It won't work without using ::deep.

### Further technical details
- .NET5-preview8
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- VS 16.8.0 preview 2.0

**Comment by campersau** [comment]
Looks like https://github.com/dotnet/aspnetcore/issues/25268

**Comment by limefrogyank** [comment]
Looks like I should have re-run my search for issues since last night... doh!
