### ISSUE TITLE
Using the Redis backplane with Clients.GroupExcept and Clients.Client

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#25289]
---
**Issue moved from SignalR/SignalR#4494**
- Please respond to @DinoSourcesRex.

---

_From @DinoSourcesRex on Wednesday, August 26, 2020 9:14:14 PM_

I am attempting to scale out my signalr application. I am mainly using `Clients.GroupExcept` and `Clients.Client`. I was expecting the backplane to relay all these messages between the nodes.

I have not done anything particularly crazy with my configuration to my knowledge.

### Expected  behavior
Messages should be relayed across the backplane to the other nodes connected to redis.

### Actual behavior
Messages are not sent / received by the other nodes connected to redis.

### Steps to reproduce
Startup configure service:
```
services.AddSignalR().AddRedis(options =>
{
    options.Configuration.EndPoints.Add(configuration.GetValue<string>("RedisEndpoint"));
    options.Configuration.ChannelPrefix = "SomeKey";
});
```

Startup configure:

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapHub<BaseHub>("/signalr");
});
```

BaseHub, for arguments sake, lets say it just sends:

```
await _hub.Clients.GroupExcept("Group1", Context.ConnectionId).SendAsync("action",object);
await _hub.Clients.Client(Context.ConnectionId).SendAsync("action",object);
```
---
I'm happy to provide a sample project if that will help someone point me in the right direction for a fix.

**Comment by BrennanConroy** [comment]
Are all your servers using the same endpoint and channel prefix?

A repro app would be helpful.

**Comment by DinoSourcesRex** [comment]
Well! Building that app ended up helping me find the issue. Totally nothing to do with SignalR and everything to do with me misconfiguring some URLS / app settings.

Thanks @BrennanConroy
