### ISSUE TITLE
FileUpload follow ups

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#25282]
* Harden the documentation for IBrowserFile to make it clear that these properties are provided by the client and are untrusted
* Do some prelimnary validation on IBrowserFile. For e.g.  throw if File.Size is negative. 
* Consider renaming ToImageFileAsync -> RequestImageFileAsync
* Add a InputFile.MaxFileSize = 15MB and a InputFile.MaxAllowedFiles = 3
* Don't document samples with MemoryStream

**Comment by mkArtakMSFT** [comment]
This is done as part of https://github.com/dotnet/aspnetcore/pull/25248
