### ISSUE TITLE
Implement support for cloud DPAPI

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2529]
_From @GrabYourPitchforks on Thursday, October 9, 2014 6:19:27 PM_

Currently Antares and most other hosting providers store machine keys in plain text in applicationHost.config. We store our keys in %HOME%, but still in plain text. We can't use DPAPI because it's not meant for scale-our scenarios such as these. We need to convince Antares and other hosters to make a CryptProtectData-like API for our consumption. One possible implementation would be for us to read a DLL path from the system registry, then to look for a CryptProtectData-like export from that module.

_Copied from original issue: aspnet/DataProtection#22_

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
