### ISSUE TITLE
DateTime returns wrong time after updating target framework to net5.0 (Blazor)

### ISSUE THREAD

**Issue by pureggerstefan** [dotnet/aspnetcore#25303]
After updating a Blazor WebAssembly App to .net5.0 a problem with DateTime occurs. When using e.g. DateTime.Now, it does not access the local time on my machine, instead it returns the current UTC-Time instead of the expected CEST. Changing any of my settings on the local machine does not affect the given value. With the previous used framework (.netstandard2.1), this problem does not occur.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. What version of .NET SDK are you using? We have fixed something similar in 5.0 Preview 8.

**Comment by pureggerstefan** [comment]
@mkArtakMSFT Thank you for your response, I was using the preview 7 by the time of the issue, after updating my .NET SDK to preview 8, the problem was solved.

**Comment by mkArtakMSFT** [comment]
Glad that it's solved now. Closing the issue.
