### ISSUE TITLE
Blazor WASM: Use several languages resources in the same component

### ISSUE THREAD

**Issue by fjallemark** [dotnet/aspnetcore#25308]
### Cannot load resources from other language in a Blazor Component
I have a component that shall use a language code in retrieved data to decide which language to use for displaying labels. In the same component I therefore need to have access to all my languages satellite DLL:s. But only the language DLL:s for the selected language in the browser seems to be downloaded. Is there a way to force all satellite assemblies to be downloaded and available in the browser app? Will this solve my problem? Or does it require some new features?

As show in the example below, using an other culture than the requested by the browser får the GetString method returns NULL.

```
private static string GetLanguageString(string? language, string key, string? englishText = null)
        {
            if (language is null) return key;
            if (englishText is null) englishText = key;
            var resourceManager = new ResourceManager(typeof(App));
            
            //This works server side but not on Blazor WASM, returns null if other language than provided by the browser
            var culture = new CultureInfo(language);
            var languageText = resourceManager.GetString(key, culture);
            // ------------------------------------------------

            if (languageText is null) return englishText;
            return languageText.Equals(englishText, StringComparison.OrdinalIgnoreCase) ? englishText : $"{englishText}/{languageText}";
        }
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
