### ISSUE TITLE
Antiforgery token in asp.net core with angular 9

### ISSUE THREAD

**Issue by MohamedSahir** [dotnet/aspnetcore#25306]
![token antifrgery](https://user-images.githubusercontent.com/20682302/91420670-a3307880-e872-11ea-83de-d1aa486eba92.png)

Question
https://stackoverflow.com/questions/63603141/400-bad-request-csrf-angular-8-with-no-razor-pages.

Angular is running separate port and .net core running separate port.

Version:
Angular 9
Dotnet core 3.1
 84.0.4147.135 

When loading with this get pop up an error security breach if a disable chrome security. it works.
![image](https://user-images.githubusercontent.com/20682302/91425514-db3aba00-e878-11ea-923f-90a2033996b7.png)

Error : Bad Request 400 .

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will leave this question to be handled in your StackOverflow post as this repo is not a good fit for general questions.
