### ISSUE TITLE
[Blazor server] 404 on .properties file

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#25312]
Hello guys, im unable to access a .properties file in a blazor server app.

In webassembly app, i was using 
````
var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".properties"] = "application/octet-stream";
app.UseStaticFiles(new StaticFileOptions { ContentTypeProvider = provider });
````
and it work great.

But in server mode, put this code broke the app with a 404 on blazor.server.js

so how i can handle that ?

thanks !

**Comment by javiercn** [comment]
@julienGrd apologies for the late response

This is because blazor updates the StaticFilesOptions in the file provider, you can do

```csharp
`services.Configure<StaticFileOptions>(o => ...)`
```

to configure the options there.
