### ISSUE TITLE
Kestrel bug while making a http call from F5 load balancer

### ISSUE THREAD

**Issue by ranjithchev** [dotnet/aspnetcore#25319]
### Describe the bug
We have a dotnet core application which uses kestrel to expose our API's. We are running our kestrel server only supporting http requests as our F5 load balancer will receive https requests from the UI and remove the certs and send it as a http request to our final kestrel web server. 

Because we use F5 as the load balancer F5 hits one of our endpoint called /healthcheck which will return a 200 status if it is up and running by which F5 detects if the host is up or not. What is happening in our case is that the F5 /healthcheck call is failing with the following error

```
Endpoint hit by F5:
GET /healthcheck\r\n

Error:
Connection id “0HM20J3RU7FR1” bad request data: “Invalid request line: ‘GET /healthcheck\x0D\x0A’”
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: ‘GET /healthcheck\x0D\x0A’
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)

```

Please note that the same F5 healthcheck setup works if we run a nodejs server using express. What is kestrel doing that express does not or handle.

Thanks
Ranjith

### Further technical details
- ASP.NET Core 3.0
- Visual studio 2017

**Comment by blowdart** [comment]
Is this a BIG-IP? They send, by default, an HTTP 0.9 request, which Kestrel will reject.

It looks like you can configure the f5 devices to be, well, more modern in their requests. https://support.f5.com/csp/article/K2167 

Could you try adding the HTTP/1.0 as suggested in the f5 documentation?
