### ISSUE TITLE
ControllerBase.User.Identity is null for all users after a period of time

### ISSUE THREAD

**Issue by pantoast** [dotnet/aspnetcore#25313]
### Description
I have a Blazor Webassembly project secured with IdentityServer4 using role based authentication. The site is published and deployed on IIS. Many of the site's API methods make use of the ControllerBase.User property, usually in conjunction with the UserManager to get information about the current user. This all works fine most of the time, but eventually it stops. Logs show that the User object's Identity property is null, and there are no Claims. There is 1 Identity in the Identities property, however this appears to be an empty object with no name, role claim type, and IsAuthenticated set to false.

The time period it takes for this to fail so far seems to be random. The site has sometimes been fine for days, and other times it will take less than a day before it stops working. Recycling the application pool solves the issue. Perhaps resource related? When the issue occurs, users are still able to login using the scaffolded ASP identity pages. They are also able to view their profile information. But all other API calls fail for the reasons outlined above. After recycling the application pool, the site runs without issue. It does not appear to be related to any specific users, but rather is site-wide.

I am unable to reproduce this while debugging as of yet.

### Code
**Startup.ConfigureServices**
```
public void ConfigureServices(IServiceCollection services)
{
	services.AddDbContext<MyDbContext>(cfg =>
	{
		cfg.UseSqlServer(_configuration.GetConnectionString("DefaultConnection"), builder => builder.MigrationsAssembly(typeof(MyDbContext).Assembly.FullName));
	});

	services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
		.AddRoles<IdentityRole>()
		.AddEntityFrameworkStores<MyDbContext>();

	services.AddIdentityServer()
		.AddApiAuthorization<ApplicationUser, MyDbContext>(options => {
			options.IdentityResources["openid"].UserClaims.Add("name");
			options.ApiResources.Single().UserClaims.Add("name");
			options.IdentityResources["openid"].UserClaims.Add("role");
			options.ApiResources.Single().UserClaims.Add("role");
		});

	JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");

	services.AddAuthentication()
		.AddIdentityServerJwt();

	services.Configure<IdentityOptions>(options => options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier);

	services.AddControllersWithViews();
	services.AddRazorPages();

	services.AddMvc();
	services.AddResponseCompression(opts =>
	{
		opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
			new[] { "application/octet-stream" });
	});

	services.AddControllers(options =>
	{
		options.OutputFormatters.RemoveType<HttpNoContentOutputFormatter>();
	});

	services.AddSignalR();
	services.AddMemoryCache();
   //my services here
}
```

**Startup.Configure**
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	app.UseDeveloperExceptionPage();
	if (env.IsDevelopment())
	{
		//app.UseDeveloperExceptionPage();
		app.UseWebAssemblyDebugging();
		env.WebRootPath = Path.Combine(Directory.GetParent(Directory.GetCurrentDirectory()).FullName, "Client", "wwwroot");
	}
	else
	{
		app.UseExceptionHandler("/Error");
		// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
		app.UseHsts();
	}

	app.UseHttpsRedirection();
	app.UseBlazorFrameworkFiles();
	app.UseStaticFiles(GetStaticFileConfiguration());

	app.UseRouting();

	app.UseIdentityServer();
	app.UseAuthentication();
	app.UseAuthorization();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapHub<TestHub>("/testHub");
		endpoints.MapRazorPages();
		endpoints.MapControllers();
		endpoints.MapFallbackToFile("index.html");
	});
}   
```

**Relevant section from appsettings.json**
```
"IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Name": "CN=*.mykey.com"
    },
    "Clients": {
      "MyClient": {
        "Profile": "IdentityServerSPA"
      }
    }
  },
```

### Further technical details
- Developed using ASP.NET Core version 3.1
- Blazor Webassembly 3.2.0
- IdentityServer4
- .NET core runtimes installed on the server:
```
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by pantoast** [comment]
I will work on trying to get a repro project setup, however due to the fact that the issue has only been reproduced when deployed it could take some time to confirm that my repro project has the same issue. Thanks.

**Comment by pantoast** [comment]
I've reproduced the issue in a more bare bones Blazor Webassembly solution. The code can be found here:
https://github.com/pantoast/BlazorAuthIssueRepro

Since making my original post, I experimented with different recycle times in IIS for my original project. Originally the application pool was set to recycle every 29 hours (the default). However, because manually recycling the app pool would fix the issue whenever it occurred, I began reducing the recycle time interval. Eventually I had it as low as 2 hours and noticed the issue seemed to be occurring _more_ frequently. Because of this I disabled automatic recycling. Since making the change about 40 hours ago it hasn't happened again. I'm continuing to keep an eye on it though.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
