### ISSUE TITLE
Fully implement nullable support in Identity templates.

### ISSUE THREAD

**Issue by blowdart** [dotnet/aspnetcore#25310]
Identity templates are not yet compatible with the ongoing nullable work.

After the 5.0 release we should go through everything and make sure it works.

For example,

https://github.com/dotnet/aspnetcore/issues/24201
https://github.com/dotnet/aspnetcore/issues/24165
https://github.com/dotnet/aspnetcore/issues/22656

**Comment by BForderRP** [comment]
Please don't kick the can 2 major versions down the road on fixing this. dotNET 6 needs this fix.

**Comment by mikekistler** [comment]
All specific instances mentioned here appear to be fixed, so we're closing this as done. But if there are any other instances please open a new issue for this.
