### ISSUE TITLE
Need to click button twice to update InputTextArea when EditForm's Model is bound to the same thing

### ISSUE THREAD

**Issue by modulardev2** [dotnet/aspnetcore#25326]
### Describe the bug
I wanted to have an InputTextArea, and a button that changes it. The InputTextArea needed to have an EditContext, so I put an EditForm around it with Model set to the same thing that the InputTextArea was bound to. If I type something in the box and my cursor remains in it, I had to click the button twice to update it. Maybe this wasn't the correct way to do it in the first place, but I found it odd that I had to click the button twice to update the text area.

Also, I noticed that it works fine if the button is placed outside of the EditForm.

### To Reproduce
```
@code {
    string Thing = "";
}

<EditForm Model="Thing">
    <InputTextArea @bind-Value="Thing"></InputTextArea>
    <button type="button" @onclick="@(() => { Thing = "test"; })">Test</button>
</EditForm>
```

### Further technical details
Framework: .NET Core 5 Preview 8
Microsoft Visual Studio Community 2019 Preview Version 16.8.0 Preview 2.0

**Comment by MarvinKlein1508** [comment]
@modulardev2 try to add StateHasChanged(); after your changed the variable.

**Comment by modulardev2** [comment]
@MarvinKlein1508 That didn't seem to work. Still have to click it twice.

**Comment by MarvinKlein1508** [comment]
Hi @modulardev2 

I have just looked into the network analysis of Firefox. This issues seem to be coming from the event change once you leave the focus of the textarea. This event triggers JS.RenderBatch which is re-rendering some part of the UI. However, because of the re-render of the section, your mouse click is not registered, which results in your issue. 

This is not specific to InputTextArea. The other Input controls have the same behaviour.

-Marvin

**Comment by modulardev2** [comment]
Yes, you're right, I was just able to recreate it with InputText, so I'm assuming that others have the same problem.
Thanks for finding that

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
