### ISSUE TITLE
Test failures and hangs due to Selenium/Chrome issues

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#25322]
We have seen a lot of CI failures/hangs in due to issues with Chrome and Selenium. The investigation is ongoing but the affected tests have been disabled to unblock CI. This issue tracks fixing those tests and re-enabling them.

**Comment by SteveSandersonMS** [comment]
Note that the fix here also needs to be backported to `release/3.1` so the tests can be enabled there too.
