### ISSUE TITLE
Ability to Debug Blazor WASM without manually changing base href

### ISSUE THREAD

**Issue by gfs** [dotnet/aspnetcore#25320]
### Is your feature request related to a problem? Please describe.
If you deploy your WASM bundle it needs the correct base href set.

For example, for https://github.com/Microsoft/OAT we host our blazor app at https://microsoft.github.io/OAT, thus the base href for publishing must be `/OAT/`.

However, for debugging it appears to not be configurable where to tell IIS or ASP to host the WASM bundle, it defaults to `/`.  Since our base href is set to `/OAT/` this means you get this error page unless you manually reconfigure the base href for debugging.

![image](https://user-images.githubusercontent.com/98900/91480270-95b9c500-e857-11ea-88eb-7461ac9aeea7.png)

### Describe the solution you'd like
I'd like a way to configure the debug launchers to host at the specified base href, or for them to properly configure themselves.

### Additional context
```
> dotnet --version
3.1.401
```

**Comment by Xyncgas** [comment]
hahah I mean it's exactly the pattern, you have to change the base everytime, like yea I wonder if we can automate this process, at least to set the base differently for publishing, and after that if you are moving it to another host say from azure to aws to whatever then you can change the base manually

**Comment by Xyncgas** [comment]
I just started playing with blazor 3 days ago and I've noticed it too

**Comment by Xyncgas** [comment]
yea I'll just do it myself using a script for now

**Comment by captainsafia** [comment]
Have you tried modifying the `applicationUrl` property in appsettings.json to a URL containing the base href?

**Comment by gfs** [comment]
I tried changing the applicationUrl in `launchSettings.json` to `https://localhost:port/OAT/` with the following results:

Here's the `launchSettings.json`
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:57251/OAT/",
      "sslPort": 44301
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/OAT/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "OAT.Blazor": {
      "commandName": "Project",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/OAT/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001/OAT/;http://localhost:5000/OAT/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

IIS Hosted
![image](https://user-images.githubusercontent.com/98900/91750082-57821580-eb77-11ea-91f6-31fd5c69b2c0.png)

ASP.NET Hosted
```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```

Changing the application url via `appSettings.json` isn't documented anywhere I could find, so I'm not sure what format to use.  The documentation for [App Settings](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1) doesn't mention application url.

**Comment by captainsafia** [comment]
Quick follow-up on this, you should be able to configure this using the following `launchSettings.json`:

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:56361/subdir/",
      "sslPort": 44343
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/subdir/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "BlazorApp2": {
      "commandName": "Project",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/subdir/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

Note: If you are using Kestrel, you'll need to call `builder.UseBasePath(new PathString("/subdir"))` to register the base path. You don't need to do the same for IIS.

@guardrex I guess we should document this somewhere. Not sure how frequent a scenario this is, it might suffice to have it documented in this issue.

**Comment by rogihee** [comment]
I ran into this issue as well and it would be great to support the change of the base url of the debugged app, to reflect how it would work in production. 

Just FYI: I think the scenario is quite common not for blank slate projects but projects that need to migrate slowly and where you convert 1 area to a WebAssembly app. Like, us :-).

**Comment by captainsafia** [comment]
@rogihee Thanks for chiming in. We've added documentation on how to debug applications running under a base href. Check out the docs in the PR linked above. You'll need to modify some settings files.

**Comment by captainsafia** [comment]
@mkArtakMSFT Closing this issue since @guardrex and I have got this documented.

There's some work to do to support this in the VS Code extension but I'll open a separate issue for that.
