### ISSUE TITLE
Enable PlatformCompatibilityAnalyzer for the repo

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#25332]
The PlatformCompatibilityAnalyzer can warn developers when non-supported APIs are used. This would have allowed us to avoid https://github.com/dotnet/aspnetcore/issues/25259.

**Comment by Pilchie** [comment]
Looks like @pranavkm has already done some of this as part of the SDK upgrade in #25421

**Comment by mkArtakMSFT** [comment]
I opened this to add a note that we will be getting this somewhat automatically as we get new SDK update.

**Comment by mkArtakMSFT** [comment]
@pranavkm feel free to use this or dupe this with an issue where you make SDK update.

**Comment by mkArtakMSFT** [comment]
@pranavkm isn't this now resolved as you had the new SDK update PR merged ?
