### ISSUE TITLE
New CTI test scenario for SignalR + Blazor WebAssembly E2E verification

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#25331]
To avoid running into issues similar to [this one](https://github.com/dotnet/aspnetcore/issues/25259) we need to have some E2E validation in place. This issue is tracking the effort to onboard a new CTI validation scenario.

**Comment by BrennanConroy** [comment]
Done https://github.com/aspnet/Tooling-ManualTests/pull/1100
