### ISSUE TITLE
Passing arguments to onclick

### ISSUE THREAD

**Issue by ataraxia89** [dotnet/aspnetcore#25336]
I'm trying to call a method from an onclick but all the suggestions I've tried online haven't worked. The most popular one is:

```
onclick="@(() => ShowEditPersonDialog(personId))"
```

...where ShowEditPersonDialog is:

```
public void ShowEditPersonDialog(string personId)
{
    // Do some stuff
}
```

...however the onclick code throws the compiler error:

```
Cannot convert lambda expression to type 'object' because it is not a delegate type
```

**Comment by NTaylorMullen** [comment]
@ataraxia89 do you happen to have an `@` in front of your `onclick`?

**Comment by ataraxia89** [comment]
@NTaylorMullen I've tried both ways, this is the full context of my code:

```
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var applicationUser in ApplicationUsers)
            {
                string userId = applicationUser.Id;
                Guid? personId = applicationUser.PersonId;

                <tr>
                    <td>@applicationUser.Email</td>
                    <td>@applicationUser.PersonName</td>
                    @if (personId != null)
                    {
                        <td>
                            <button class="btn btn-block btn-primary" @onclick="() => ShowEditPersonDialog(personId)" style="color: rgb(255, 255, 255); background-color: rgb(49, 56, 215);" @type="button">Edit Person</button>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>
```

As it is above the component loads up until the first button on the first row (there are 4 users - 4 rows should load) then the button doesn't render properly and an unhandled exception is thrown:

[![Blazor application exception][1]][1]

I've tried:

- `@onclick="() => ShowEditPersonDialog(personId)"` - exception shown above
- `@onclick="(e) => ShowEditPersonDialog(e, personId)"` - exception shown above
- `@onclick="e => ShowEditPersonDialog(e, personId)"` - exception shown above
- `@onclick="@(e => ShowEditPersonDialog(e, personId))"` - exception shown above
- `@onclick="(e) => ShowEditPersonDialog(e)"` - exception shown above
- `@onclick="e => ShowEditPersonDialog(e)"` - exception shown above
- `@onclick="@(e => ShowEditPersonDialog(e))"` - exception shown above
- `@onclick="() => ShowEditPersonDialog()"` - exception shown above
- `@onclick=@"() => ShowEditPersonDialog(personId)"` - doesn't compile, syntax errors
- `@onclick="@(() => ShowEditPersonDialog(personId))"` - exception shown above
- `onclick="() => ShowEditPersonDialog(personId)"` - compiles, runs and renders but the button doesn't respond
- `onclick="@(() => ShowEditPersonDialog(personId))"` - doesn't compile - Cannot convert lambda expression to type 'object' because it is not a delegate type
- `onclick="(e) => ShowEditPersonDialog(e, personId)"`- compiles, runs and renders but the button doesn't respond
- `onclick="e => ShowEditPersonDialog(e, personId)"` - compiles, runs and renders but the button doesn't respond
- `onclick="@((e) => ShowEditPersonDialog(e, personId))"` - doesn't compile - Cannot convert lambda expression to type 'object' because it is not a delegate type
- `onclick="@(e => ShowEditPersonDialog(e, personId))"` - doesn't compile - Cannot convert lambda expression to type 'object' because it is not a delegate type
- `onclick="@(e => ShowEditPersonDialog(e))"` - doesn't compile - Cannot convert lambda expression to type 'object' because it is not a delegate type

  [1]: https://i.stack.imgur.com/IjwlG.png

**Comment by ataraxia89** [comment]
This issue has been answered here >> https://stackoverflow.com/a/63691221/5449886
