### ISSUE TITLE
backgroundservice starts multiple times

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/aspnetcore#25345]
I have backgroundservice on asp.net core 2.1 webapi project. I am logging StartAsync and I saw that StartAsync starts multiple times during service work.

I am using backgroundservice template from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio. And I injected it in Startup.cs as services.AddHostedService<T>(); I wrote log when it starts and it starts multiple times while my project hosted on IIS still works. How this is possible and why it starts BackgrounService multiple times? Maybe the reason is using services.AddHostedService<TestBGService>(); instead of using services.AddSingleton<IHostedService, TestBGService>();

**Comment by Tratcher** [comment]
Can you share the logs and relevant code?

Some possibilities:
- the whole site is restarting
- you've enabled web garden mode and started multiple instances of your site.
- you've registered your service multiple times.

**Comment by shahinjabbar** [comment]
I am using IHostedService to register backgroundservice in startup.cs.
