### ISSUE TITLE
@inject in vscode

### ISSUE THREAD

**Issue by HaoZhiYing** [dotnet/aspnetcore#25340]
@Inject not recognized

**Comment by TanayParikh** [comment]
Can you please confirm you're on the latest VS Code C# extension (should be 1.23.1 as of today). 

Just tried it out locally and I'm seeing completions for `@inject`:
![image](https://user-images.githubusercontent.com/14852843/91752558-5d79f580-eb7b-11ea-85ef-a9f8125c71e7.png)

Is that the issue you were facing?

**Comment by HaoZhiYing** [comment]
![image](https://user-images.githubusercontent.com/14025507/91936725-06168980-ed23-11ea-9df2-87ca463d88cc.png)
1、F12 definition not found
2、There are no tips for writing

**Comment by HaoZhiYing** [comment]
![image](https://user-images.githubusercontent.com/14025507/91940553-37468800-ed2a-11ea-8e2a-47772e40a8cb.png)

**Comment by HaoZhiYing** [comment]
![image](https://user-images.githubusercontent.com/14025507/91941279-8a6d0a80-ed2b-11ea-874a-761a8cdf9f01.png)

**Comment by HaoZhiYing** [comment]
![image](https://user-images.githubusercontent.com/14025507/91941459-d6b84a80-ed2b-11ea-9223-21a65478c0e6.png)

**Comment by TanayParikh** [comment]
> 1、F12 definition not found
> 2、There are no tips for writing

1. Which element are you trying to F12 on?
2. I'm assuming this is referring to missing [intellisense](https://code.visualstudio.com/docs/editor/intellisense)/completions. Where are you missing the completions, would you be able to provide a .gif to illustrate the issue?

Also, could you kindly confirm which version of the VS Code C# extension you're running.

**Comment by HaoZhiYing** [comment]
1、F12 prompt missing reference
2、F12 AppConfiguration Object
3、Import namespace not in effect ( file: _ViewImports.cshtml )

**Comment by HaoZhiYing** [comment]
1，F12 prompt missing reference
2，F12 AppConfiguration Object
3，import namespace is not valid（in file ：_ViewImports.cshtml）
4、Vscode version News
![image](https://user-images.githubusercontent.com/14025507/92063472-c0fb6180-edcd-11ea-9648-0da2e9014014.png)
![image](https://user-images.githubusercontent.com/14025507/92063491-d1abd780-edcd-11ea-9128-a9976e96ff53.png)

**Comment by TanayParikh** [comment]
Adding for triage.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
