### ISSUE TITLE
Blazor Feature Request: Support for Pipes

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#25346]
Original fetaure request: #12389 

> It will be good if there is Pipes feature as in Angular
> 
> `<p>The hero's birthday is {{ birthday | date }}</p>`

The difference with existing extension method is, that (pure) pipes are not reevaluated if the input does not change. In some cases it can be huge performance boost. Take a pipe that sorts an array as an example.

Pipe also creates an instance which can have it's own state, unlike C#'s extension methods.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
