### ISSUE TITLE
Document how to integrate static files provider with Blazor Server

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#25354]
This is important to avoid issues like https://github.com/dotnet/aspnetcore/issues/25312

**Comment by guardrex** [comment]
I think what we did covers it ...

* File content type provider in Blazor Server - https://github.com/dotnet/AspNetCore.Docs/pull/19483
* https://docs.microsoft.com/aspnet/core/blazor/fundamentals/additional-scenarios#static-files

**Comment by javiercn** [comment]
Here is the content for this:
Server-side Blazor adds an embedded file provider to the Static files static provider within configuration to serve the files Blazor server applications need to run.
If you need to customize the file provider used by the static files middleware, we recommend you do this through `services.Configure<StaticFileOptions>(options => { ... })` or that alternatively you plug-in a second static files middleware that skips serving `_framework/blazor.server.js`. For example:
```csharp
  app.MapWhen(ctx => !ctx.Request.Path.StartsWithSegments("_framework/blazor.server.js", subApp => subApp.UseStaticFiles(new StaticFileOptions(){...})));
```
