### ISSUE TITLE
JSObjectReference API review

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#25355]
* Create interfaces `IJSObjectReference` and `IJSInProcessObjectReference`
* Make `JSObjectReference` and `JSInProcessObjectReference` internal
* Update `IJSObjectReference` and `IJSInProcessObjectReference` to have the same set of extension methods as `IJSRuntime` and `IJSInProcessRuntime`.
* Remove protected static JSCallResultType ResultTypeFromGeneric<TResult>() and make it internal or use shared code
* Consider annotating WebAssembly specific JSRuntime types with SupportedOSPlatform attribute

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck shoudl this be closed now?

**Comment by MackinnonBuck** [comment]
Yes, closing.
