### ISSUE TITLE
OpenApiReference add support for yaml

### ISSUE THREAD

**Issue by jkone27** [dotnet/aspnetcore#25351]
### openapi client generation via csproj
the current openapi generation experience via **OpenApiReference** is very nice, thought it could be extended to support also **yaml** file (as using nswag): https://github.com/RicoSuter/NSwag/wiki/YAML-support

assuming that the feature works with C# source generators as it generates types in /obj folder as partial classes,
i guess it should be possible to postpone that (verifying that the file extension is either .json or yaml) and if so calling this step before the actual code generation

which i believe might be already using this piece of code now?
https://github.com/RicoSuter/NSwag/wiki/CSharpClientGenerator

**Comment by mkArtakMSFT** [comment]
@bradygaster thoughts on this?

**Comment by jkone27** [comment]
this actually already works nowadays
