### ISSUE TITLE
[Templates] Blazor-server with Identity is broken

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#25353]
This is an issue with the template. The fix would be to use a different set of _LoginPartial files, one for OrgAuth and for IndividualAuth similar to  the Razor Pages template: https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/Shared/_LoginPartial.OrgAuth.cshtml.

We'll be addressing this for rc1. In the meanwhile, you can workaround this issue by editing the `Areas\Identity\Pages\Shared\_LoginPartial.cshtml` file in your project file to change all instances of `asp-area="MicrosoftIdentity"` to `asp-area="Identity"`

```diff
- <a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-page="/Account/Register">Register</a>
+ <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
```

**Comment by javiercn** [comment]
@JunTaoLuo did we fix this as part of @jmprieur merged PR? Or is this still an issue? If that's the case, @JunTaoLuo can you work this out?

**Comment by jmprieur** [comment]
@javiercn : it was not yet

**Comment by mkArtakMSFT** [comment]
@jmprieur do you plan to fix this? We will be entering QB approval mode tomorrow, so can we do this early? Thanks!

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo assigning to you to help merge the PR @jmprieur will be sending here.

**Comment by captainsafia** [comment]
@JunTaoLuo Can this be closed now?

cc: @mkArtakMSFT

**Comment by JunTaoLuo** [comment]
No let's keep it open so I can address the comments from the previous PR. I'll move it out of rc1 though.
