### ISSUE TITLE
Add support for unique phone numbers, find user by phone number in Identity

### ISSUE THREAD

**Issue by rsoulard** [dotnet/aspnetcore#25368]
I am trying to allow users to use a phone number for authentication. This would be made easier if I was able to: 

1. Require unique phone numbers.

1. Find users by their phone numbers.

### Describe the solution you'd like
I would like for there to be an addition property added to [`UserOptions`](https://github.com/dotnet/aspnetcore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Extensions.Core/src/UserOptions.cs) called `RequireUniquePhoneNumber` with the corresponding code added to [`UserValidator`](https://github.com/dotnet/aspnetcore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Extensions.Core/src/UserValidator.cs) in order to ensure unique phone numbers per user in this layer. This would require that the method `FindByPhoneNumberAsync` be added to [`UserManager`](https://github.com/dotnet/aspnetcore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/Extensions.Core/src/UserManager.cs) which would also aid in authenticating users by their phone number.

**Comment by blowdart** [comment]
This has been requested before, but it's rare enough for it to be an edge case, and not something we're going to consider I'm afraid.
