### ISSUE TITLE
Razor component discovery should use 'SkipAnalyzers'

### ISSUE THREAD

**Issue by chsienki** [dotnet/aspnetcore#25365]
In #25292 the component discovery CSC pass was modified to pass analyzers, as Source generators are now included and removing them can cause builds to fail.

The warning level was also set to 0 in order to hide duplicate warnings. This means that analyzers, which can only emit diagnostics, are running but won't have any functional change on the build. In dotnet/roslyn#46669 we introduced a new parameter for this scenario `SkipAnalyzers` this will skip the execution of analyzers passed to the compiler, but still allow any source generators to run,

(note: analyzers can currently issue errors, which will prevent the component discovery from succeeding and failing the build. Skipping the analyzers will skip this step, but the same analyzers will run as part of the second phase build and issue an error there instead, which is functionally the same from the users perspective).

**Comment by Pilchie** [comment]
:eyes:

**Comment by Pilchie** [comment]
This is also impacting our ability to add PublicAPI baselines to projects in this repo that use Razor.

**Comment by pranavkm** [comment]
@Pilchie we're blocked on updating the SDK  - https://github.com/dotnet/aspnetcore/pull/25421. Once that goes in, we should be able to start using this option - https://github.com/dotnet/aspnetcore/pull/25736.
