### ISSUE TITLE
deploying an angular project to iis

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25364]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1159264/deploying-an-angular-project-to-iis.html)._

---
I have an angular 8 project that will not publish to iis.   I am using webdev.   The npm install works.  The npm build "--prod" throws an error

Browserslist: caniuse-lite is outdated. Please run next command `npm update`

ERROR in scripts.04caf2cfc54e2806cc77.js from Terser
Unexpected token: operator (=) [scripts.04caf2cfc54e2806cc77.js:969,26]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular_qr_reader_2@0.0.0 build: `ng build "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular_qr_reader_2@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dnishimoto. BOISE\AppData\Roaming\npm-cache\_logs\2020-08-21T21_59_24_316Z-debug.log
C:\Users\dnishimoto. BOISE\source\repos\ESICode\Angular QR Reader 2\Angular QR Reader 2.csproj(52,5): Error MSB3073: The command "npm run build -- --prod" exited with code 1.

1>Build failed. Check the Output window for more details.
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

---
#### Feedback Bot on 8/24/2020, 02:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/24/2020, 07:29 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
