### ISSUE TITLE
Upgrading from Net Core 3.1 to NET 5 Preview 7 Microsoft.Extensions.Hosting error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25363]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1145839/upgrading-from-net-core-31-to-net-5-preview-7-micr.html)._

---
[severity:Other]
When I upgraded a test solution to NET 5 Preview 7,
at compiler time an error occurs, event without any reference to the assembly.

Even if this error the compiled app runs just fine.

I'm using last VS 2019 Community Preview with last Preview components.

>23>Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Hosting, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
>23>File name: 'Microsoft.Extensions.Hosting, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>23>   at MenphisSI.HostContainer.Program.Main(String[] args)

---
#### Feedback Bot on 8/12/2020, 01:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like you haven't properly migrated your app and have incorrect dependencies in your dependency graph. Please review all the dependencies and make sure they all target .NET 5.
