### ISSUE TITLE
ProducesAttribute hides HTTP 404 / behavior is counterintuitive

### ISSUE THREAD

**Issue by GoldenCrystal** [dotnet/aspnetcore#25385]
### Describe the bug

I filled this issue as a bug because the behavior I initially encoutered seems to clearly be a bug, but I more generally wanted to open a discussion on the actual behaviour of `ProducesAttribute`, which I found confusing compared to `ConsumesAttribute`.

#### The "actual bug"

This is what triggered my investigation into the behavior of the attribute ands its sibling `ConsumesAttribute`, and led me to discover that it didn't work as I expected:

* `ProducesAttribute` unexpectedly messes with `BadRequestObjectResult`. (Sometimes overwrite a 404 with a 406 😉)
* `ProducesAttribute` totally ignores its own `StatusCode` property, while it could be used to *not alter* `ObjectResult` whose `StatusCode` does not match. (caveat: `ProducesAttribute.StatusCode` is not nullable 😕)

#### The confusing behavior

Altough it is succintly explained in the second sentence of the docs, the actual implications of putting a `Produces` attributes are IMO counterintuitive compared to putting the closely-related `Consumes`.

> A filter that specifies the expected Type the action will return and the supported response content types. The ContentTypes value is used to set ContentTypes.

The first sentence is perfectly fine, and exactly what (I think) anyone would expect: This attribute can serve as documentation and indicate what content types can be returned.
The second sentence, however…

* Feels a bit "One more thing…" (As if this feature was not originally intended and added later on)
* Hardly makes any sense unless you take time to follow the links to find that (`ProducesAttribute.`)`ContentTypes` is not the same as (`ObjectResult.`)`ContentTypes`

As the `Consumes` attribute actually plays a role in content negociation *and* action selection, it'd be logical to assume that `Produces` would play a similar role (filter the actions based on the `Accept` header sent by the client) cf. issue #3891 where the question was already raised.

As part of the content negociation, I (do now) understand why `ProducesAttribute` interacts with `ObjectResult.ContentTypes`; it's the only way to force the automatic content negocation to use different content types.
But, if anything, I really expected the attribute to block requests before an action was executed (which is also a form of content negociation), as in some cases, actions can be costly, and/or produce side effects. (DB update)

### To Reproduce

In a basic ASP.NET Core API template, add the following controller:

````csharp
[Route("api/[controller]")]
[ApiController]
public class ImagesController : ControllerBase
{
    private static readonly byte[] SpacerGif = new byte[]
    {
        0x47,0x49,0x46,0x38,0x39,0x61,0x01,0x00,0x01,0x00,0x00,0x00,0x00,0x21,0xF9,0x04,
        0x01,0x00,0x00,0x00,0x00,0x2C,0x00,0x00,0x00,0x00,0x01,0x00,0x01,0x00,0x00,0x02,
    };

    // GET api/values/5
    [HttpGet("{id}")]
    [Produces("image/gif")]
    public IActionResult Get([Range(1, int.MaxValue)] int id)
        => new FileContentResult(SpacerGif, "image/gif")
        {
            FileDownloadName = FormattableString.Invariant($"image-{id}.gif"),
        };
}
````

For reference, call `http://localhost:5000/api/images/1` and notice that it works as expected. (Downloads an image named `image-1.gif`)

Now call `http://localhost:5000/api/images/0`

Result: Error 406 (Not Acceptable)
Expected: Error 404 (Bad Request) with details as JSON (Like without the `Produces` attribute)

This happens because there is no `IOutputFormatter` knowing how to format a `ProblemDetails` into `image/gif`… Which isn't really unexpected.

NB: You could argue that this scenario is unrealistic because I'm not using content negociation for the output here. However, the same would happen if I returned a `ImageBlueprint` that could be transformed to either SVG or GIF using two pecific `IOutputFormatter`: Those formatters wouldn't know how to transform the `ProblemDetails` in the `BadRequestObjectResult`.

### To sum up

1. I really want to be able to use this attribute to indicate what "non standard" (relative to the app) or explicit Content-Types are returned by an API, even if its not being generated by an `ObjectResultInstance`. (This stills seems to be the main point of the attribute)
  However, the attributes interferes quite badly with model validation if you didn't register a corresponding output formatter, or if your `IOutputFormatter` instance can only format specific object types. (See repro above)
  And even if we had a formatter for that, maybe we just always want our errors to be surfaced as JSON. (Which would be a sensible choice, I think)

2. I understand the behavior of overriding the `ContentTypes` of `ObjectResult` when there is one, but I was expecting/would also like the attribute to filter the requests before executing the action, thus avoiding costly computations, database updates, etc.
  Even better would be to include the `ProducesAttribute` in the process of action selection, similar to `ConsumesAttribute`. (See #3891 again)
  Implementing this would de-facto provide the request filtering behavior, as the action that should be filtered would simply not be chosen at all due to the mismatched content type.

I don't believe that implementing either the filtering or the `Produces`-based action selection would break any serious scenario¹, as by placing the attribute, you are already implying (and in the case of `ObjectResult`, forcing) that you won't return a content type other than the one(s) specified.

¹ Of course, you can still produce a different content type by using a `IActionResult` that is not `ObjectResult`. But that would just be evil… or a terrible mistake.

### Further technical details
ASP.NET Core 2.2 / ASP .NET Core 3.1 / ASP.NET Core 5.0 Preview 8

````
SDK .NET Core (reflétant tous les global.json) :
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.516 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-alpha.1.19564.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
````

**Comment by captainsafia** [comment]
@GoldenCrystal Are you still able to reproduce the issue with .NET 6?

I haven't been able to reproduce with the parameters that you specified above. Can you share a complete repro project?

> This happens because there is no IOutputFormatter knowing how to format a ProblemDetails into image/gif… Which isn't really unexpected.

> Result: Error 406 (Not Acceptable)
> Expected: Error 404 (Bad Request) with details as JSON (Like without the Produces attribute)

Do you mean that you expect a 400 status code and received a 406? I was able to get a 400 response from both scenarios.

**Comment by GoldenCrystal** [comment]
@captainsafia Sorry for the late reply, but I took some time to check this and I can confirm it to work on my side !
(And yes, sorry, I wrote 404 instead of 400 😶)

I'm closing this issue then 🙂
