### ISSUE TITLE
Helix daily test failing during build

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#25397]
Failure: https://dev.azure.com/dnceng/public/_build/results?buildId=793118&view=results

Log:
```
/home/vsts/work/1/s/.dotnet/sdk/5.0.100-rc.1.20379.10/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1047: Assets file '/home/vsts/work/1/s/artifacts/obj/Microsoft.AspNetCore.App.Runtime/project.assets.json' doesn't have a target for 'net5.0/linux-arm64'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. You may also need to include 'linux-arm64' in your project's RuntimeIdentifiers. [/home/vsts/work/1/s/src/Framework/App.Runtime/src/Microsoft.AspNetCore.App.Runtime.csproj]
```

Needs investigation.

**Comment by dougbu** [comment]
Taking this. It cropped up in https://dev.azure.com/dnceng/public/_build/results?buildId=804251, a build I ran for #25663 and I think I see the problem: The Helix daily jobs `restore` separately in their `--arch arm64` jobs and don't pass that command-line argument into the `restore` command. Simple thing is to remove the separate `restore` steps.

**Comment by dougbu** [comment]
12f92dbc8ca7
