### ISSUE TITLE
Razor testassets restore race

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#25396]
Failure: https://dev.azure.com/dnceng/internal/_build/results?buildId=790800&view=results

Logs:
```
F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-rc.1.20379.10\NuGet.targets(128,5): error : Cannot create a file when that file already exists. [F:\workspace\_work\1\s\src\Razor\test\testassets\RestoreTestProjects\RestoreTestProjects.csproj]
```

cc @mkArtakMSFT  to assign for investigation

**Comment by pranavkm** [comment]
This is no longer how Razor tests execute as part of the SDK. Closing.
