### ISSUE TITLE
Blazor Wasm RemoteAuthenticatorView does not redirect to an external LogOutSucceededPath

### ISSUE THREAD

**Issue by tonibabieka** [dotnet/aspnetcore#25398]
In a Blazor webassembly client application I changed the default LogOutSucceededPath Url to a regular server login razor page, "/Account/LogIn" and it is not redirected to it, the correct url "https://localhost:5001/Account/Login is displayed in the browser Address Bar but the RemoteAuthenticatorView is still the displayed page.

### Further technical details
- NET 5 Sdk - Preview 8
- Microsoft Visual Studio Community 2019 Preview - Versión 16.8.0 Preview 2.0

Thanks

**Comment by javiercn** [comment]
@tonibabieka thanks for contacting us.

The logout page needs to be within the Blazor application. You can have a page there that forces a navigation to wherever you want.
