### ISSUE TITLE
Blazor wasm: CSS isolation not working with blazor built-in forms components

### ISSUE THREAD

**Issue by Khaon** [dotnet/aspnetcore#25409]
### Describe the bug

CSS Isolation introduce in preview 8 is working fine with regular html elements but it is not working with the [built-in components](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0)

![image](https://user-images.githubusercontent.com/6811304/91646184-d7f82780-ea4c-11ea-9270-164ede5bb041.png)

### To Reproduce
A sample project to reproduce the issue can be found there:
https://github.com/Khaon/blazor-css-isolation

Index.razor and Index.razor;css are the page you look at
https://github.com/Khaon/blazor-css-isolation/tree/master/BlazorApp10/Pages

### Further technical details
- ASP.NET Core version: **5.0.100-preview.8.20417.9**
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Professional 2019 Preview
Version 16.8.0 Preview 2.0

**Comment by MikeIxTech** [comment]
Did you try to use the ::deep selector (https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-8/)

**Comment by SteveSandersonMS** [comment]
@MikeIxTech is correct. The idea of CSS isolation is that components don't pick up styles from each other by default - they are isolated :)

So if you want your `Index.razor.css` styles to influence a child component like `InputText`, you do need to use `::deep`. For example, in your `Index.razor.css`:

```css
::deep ﻿.red-color {
    color: red;
}
```
