### ISSUE TITLE
Add comments on method in which aspnetcore version like"since 3.0.0" to show on which version we get this method

### ISSUE THREAD

**Issue by xyz0822** [dotnet/aspnetcore#25401]
Add comments on method with "since 2.0.0" to show on which version we get this method
Example: 
```
        /// <summary>
        /// since 3.0.0
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
```

**Comment by Tratcher** [comment]
While version history is useful information, adding it to every API doc comment does not seem like the best way to provide this. This information seems more appropriate in external API docs or tooling.

E.g. https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost?view=aspnetcore-3.1
```
ASP.NET Core
3.1 3.0 2.2 2.1 2.0
```

**Comment by halter73** [comment]
I recommend using https://apisof.net/ to see which APIs are available in various releases. API docs like docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost?view=aspnetcore-3.1 already let you use a dropdown to select what release you want to see APIs for.
