### ISSUE TITLE
Parsing/Validating a JWT token with invalid `exp` field fails on core 31.

### ISSUE THREAD

**Issue by matra774** [dotnet/aspnetcore#25419]
###   Bug description
JwtPayload.Exp throws if tokens contains a DateTIme instead of numeric value

###   Expected behavioud
It should return null

### Details

The documentation of `System.IdentityModel.Tokens.Jwt.JwtPayload.Exp` states :
>If the 'expiration' claim is not found OR could not be converted to <, null is returned.

However this is not the case. `Exp` property geter throws an exception if values is a Datetime. Here is a sample token

```
{
  "exp": "2020-09-08T21:18:18.5297739+02:00",
  "name": "tojename"
}

```

Please note that the payload is incorrect (`exp` should be a numeric type as per https://tools.ietf.org/html/rfc7519#section-4.1.4)

The `JwtPayload.GetIntClaim()` tires exception of type `FormatException`, `InvalidCastException` and `OverflowException`, but it does not handle `InvalidCastException` which is thrown by `DateTime.IConvertible.ToDouble`

As a consequence of this bug JwtSecurityTokenHandler can not be used to validate if the signatur eon the token is correct (ignoring invalid exp field).

Sample code: 

  public static void ValidateTokenBug()
    {

      const string mySecret = "sladkjlkjsdhflksjdhf2389764238kjldhflskjdfhlksjdhflkjsflkdjfhkldjfhg3487968340975kdlfjhglkjdfhg3904875093847";

      // This token is invalid - ext filed contains DateTIme instead of numerif value
      const string token =
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDIwLTA5LTA5VDEwOjU0OjAwLjA2ODAyMDUrMDI6MDAiLCJuYW1lIjoidG9qZW5hbWUifQ.2_OEkBcRfCIOpLwTXAUtGeoKuehETs5yELulfkXyyPU";

      var mySecurityKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(mySecret));

      var tokenHandler = new JwtSecurityTokenHandler();
      try
      {
        tokenHandler.ValidateToken(token, new TokenValidationParameters
        {
          ValidateIssuerSigningKey = true,
          IssuerSigningKey = mySecurityKey,
        }, out SecurityToken validatedToken);
      }
      catch (Exception ex)
      {
        Console.WriteLine("ValidateToken failed: " + ex);
        
      }
      Console.WriteLine("Validation OK");
    }
`

### Further technical details
* OS: win 10
*dotnet --info

```
NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by blowdart** [comment]
" the token is correct (ignoring invalid exp field)"

That does mean that the token simply isn't correct, and I'm ok with it being rejected. What's your scenario here for wanting to accept an invalid token, especially one where you can't validate expiry and risk accepting things that shouldn't be accepted?

**Comment by matra774** [comment]
My scenario is interop with some legacy service that created invalid token. This is not critical issue for me, I am just pointing out inconsistency in implementation/documentation.

The implementation ignores exp if it sets to "foo", but not if it set to a DateTime.
The documentation states that invalid values are ignored, but they are not for DaateTime.

**Comment by blowdart** [comment]
Documentation we can fix easily :)

**Comment by blowdart** [comment]
OK issue created in the JWT library repo. You may want to follow that, we don't own the code in question so I'm going to close this as external.
