### ISSUE TITLE
Unable to restore and compile ASP.NET source code from tag 3.1.7

### ISSUE THREAD

**Issue by karthikrathinavelu** [dotnet/aspnetcore#25410]
### Describe the bug
I'm trying to compile ASP.NET source code in my local system and it is failing during restore.cmd step

### To Reproduce
R:\source\repos\aspnetcore>git clone --recursive https://github.com/dotnet/aspnetcore
R:\source\repos\aspnetcore>git checkout v3.1.7
R:\source\repos\aspnetcore>.\restore.cmd
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
Detected JDK in C:\Program Files\Java\jdk-14.0.2 (via JAVA_HOME)
  Determining projects to restore...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command wit
h --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\rkart\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20213.4\tools\Tools.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-extensions-784b0ffa/nuget/v3/index.j
son. [C:\Users\rkart\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20213.4\tools\Tools.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\rkart\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.
20213.4\tools\Tools.proj]
Build failed.

### Exceptions (if any)
Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected in C:\Program Files.
Detected JDK in C:\Program Files\Java\jdk-14.0.2 (via JAVA_HOME)
  Determining projects to restore...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): warning : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command wit
h --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet` [C:\Users\rkart\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20213.4\tools\Tools.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-extensions-784b0ffa/nuget/v3/index.j
son. [C:\Users\rkart\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.20213.4\tools\Tools.proj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\rkart\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.
20213.4\tools\Tools.proj]
Build failed.

The issue didn't occur from v3.0.0 tag
The same issue has been reported in stackoverflow a few days back : https://stackoverflow.com/questions/63458687/try-compile-asp-net-core-3-1-7-from-source

**Comment by blowdart** [comment]
It's because it includes a security update, and the package feed for those is private. You can try removing the internal feeds as detailed in https://github.com/dotnet/sdk/issues/11795
