### ISSUE TITLE
Disconnected SignalR implementation for ServerSide Blazor

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#25415]
I like the blazor server side concept using SignalR which is connected.
Can it not be made disconnected, so that it can handle more clients, becuase current connected architecture has scaling issues.
There are many applications that can take advantage of it by using polling nature instead.
1) Flight status usuall you only want to check or get flight status every minute or so, so connected client just waste the resource.
    There is no need of realtime information, just need to poll to get information every minute or so(or let it be configurable by user)
2) Let user load the page and be diconnected and reconnect again when user is ready to get more details.
   There could be form that user can take of minute or more to fill and he staying connected is just wasting the resource, let him conitnue submiting the form once he clicks submit button, 
  By not holding on live connecttion server could be serving ohter clients and thereby increase the scaling nature.
3) I understand there is a webassembly version of Blazor that can help achieve all this, but it is very heavy on dowload.

Would like to know what prevents servside blazor from using disconnected implementation of SignalR rather than connected one? We are listning to events on client side anyway.

You could have both versions, let user opt between realtime one or disconnected one for the server side blazor. 
The serverside already has a hughe advantage by keeping client thin, excep that it cannot scale really good.

**Comment by BrennanConroy** [comment]
@mkArtakMSFT Doesn't this sound like a Blazor feature? Not sure what the SignalR work here is.

**Comment by nssidhu** [comment]
yes it is for Blazor, Blazor serverside uses SignalR for Client to Server Comminucation.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
