### ISSUE TITLE
AuthenticationOptions.AddScheme() should declare displayName as nullable

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/aspnetcore#25422]
The display name is an optional thing and is typically not set for handlers that are not meant to be publicly listed. As such, the `AuthenticationOptions.AddScheme()` method should declare the `displayName` parameter as nullable (`string` -> `string?`).

https://github.com/dotnet/aspnetcore/blob/1268b6ee64f4b484d2c3b21a61a6f9a58731cfb0/src/Http/Authentication.Abstractions/src/AuthenticationOptions.cs#L52-L63

@HaoK @Tratcher

**Comment by Tratcher** [comment]
@pranavkm

**Comment by blowdart** [comment]
To be taken into account in https://github.com/dotnet/aspnetcore/issues/25310

**Comment by kevinchalet** [comment]
@blowdart is it open to external contributions? Having to use the null-forgiving operator when calling this method is a bit ugly... 😃

**Comment by pranavkm** [comment]
@kevinchalet feel free to send a PR to the release/5.0 branch.

**Comment by HaoK** [comment]
@blowdart this API isn't part of identity, the lowest auth apis had nullable done in 5.0, so something like this should probably be fixed in 5.0

**Comment by blowdart** [comment]
If it doesn’t chain anything else then sure. If it does open a rabbit hole then no.

**Comment by kevinchalet** [comment]
PR sent: https://github.com/dotnet/aspnetcore/pull/25480 😄
