### ISSUE TITLE
Feature Request - Blazor support for flow control statements in razor markup

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#25424]
### Current usage of flow control statements in razor files

Some time ago I raised this issue: https://github.com/dotnet/aspnetcore/issues/24793#issue-676989822 which was closed as "Won't fix". I believe there is some merit in consdering possible solutions to this in more detail.

Razor files allow C# code to be embedded in markup. This includes all C# syntax, including flow control statements such as `return`, `break`, `continue` etc.

Using these statements correctly can simplify the markup & make the pages more readable. 

Example:
```
@if (Value == null)
{
    <p>Error - value not initialised</p>
}
else
{
    <div>
        .... Rest of markup
        @if (OtherValue == null)
        {
            <p>Error - Othervalue not initialised</p>
        }
        else
        {
            <more markup / components...
        }
    </div>
}
```

Can be modified to:

```
@if (Value == null)
{
    <p>Error - value not initialised</p>
    return;
}
<div>
    .... Rest of markup
    @if (OtherValue == null)
    {
        <p>Error - Othervalue not initialised</p>
    }
    else
    {
        <more markup / components...
    }
</div>
```

This works and generates the correct render tree.

However, using flow control statements in the razor markup is error prone, since the above (valid) syntax may lead an unexperienced developer to then assume the following can be done:
```
@if (Value == null)
{
    <p>Error - value not initialised</p>
    return;
}
<div>
    .... Rest of markup
    @if (OtherValue == null)
    {
        <p>Error - Othervalue not initialised</p>
        return;
    }
    <more markup / components...
</div>
```

This is invalid since the second return will leave the "div" element unclosed. Similarly, if this `return` were inside a component instance the component would have not have been closed properly. In some cases these scenarios give a compile time syntax error, in others not.

### Possible improvements

1. Do not allow flow control statements to be used in this context - raise compile time error
2. Provide documentation guidelines on how to use (or not) flow control statements in razor files
3. Change the code generated by the razor files to make it more friendly towards using flow control statements

Option [3] above is my preferred solution which I'll describe in more detail below

### Preferred solution - Code generation updated to support flow control statements in razor files

Looking at the various C# flow control statements it is probable that `return` and `goto` cannot be used reliably in razor files and should be avoided. This is easy to document and relatively simple for users to understand.

My proposal is to update the code generator so that the following syntax is valid:
```
@if (Value == null)
{
    <p>Error - value not initialised</p>
    break; /* Completes rendering for this page/component */
}
<div>
    .... Rest of markup
    @if (OtherValue == null)
    {
        <p>Error - Othervalue not initialised</p>
        break; /* Continues rendering at "More content" */
    }
    <more markup / components...
</div>
<p>More content</p>
```

### Implementaton of proposed solution

In order to support `break` in the code above the code generation can be updated to wrap all blocks which have to be closed in a ```do { ... } while (false);``` wrapper. 

This means the razor code above would translate into the following pseudo code:
```
@do {
    if (Value == null)
    {
        <p>Error - value not initialised</p>
        break;
    }
    <div>
       @do {
            .... Rest of markup
            if (OtherValue == null)
            {
                <p>Error - Othervalue not initialised</p>
                break;
            }
            <more markup / components...
        } while (false);
    </div>
} while (false);
```

I've downloaded the latest aspnetcore source, and modified it to support the above and it seems to work properly. The affected areas in the code are:
1. `ComponentRuntimeNodeWriter`
`WriteMarkupElement` and `WriteComponent` need to support this. 
2. `DefaultDocumentWriter`
This needs to be updated to update the overall `BuildRenderTree` function to allow the flow control to work at the top level of the razor page. It is slightly more involved since the actual code is shared in many places but there are several possible options to pass a parameter from `DefaultDocumentWriter` to `BuildScope` to `CSharpCodeWritingScope` to get the required behaviour.

Please review this proposal, I'd be happy to submit a PR for this or discuss alternative solutions for this issue.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.

**Comment by tn-5** [comment]
Can anyone provide any sensible reason as to why this is not even considered for implementation? Or even discussed?

It is a relatively trivial implementation with 100% backward compatibility and expands the syntax that can be used in razor files to make it much for user friendly in certain scenarios.

**Comment by stefanloerwald** [comment]
I'll try to offer my reasoning as to why this wouldn't be ideal.

Reading the code
```cs
@if (Condition)
{
   break;
}
```
will make me, as a C# developer, want to find the loop that I'm breaking out of. But I wouldn't see that loop, as that's actually just the `do {} while(false);` loop that you would generate on every component/element. As the author of the markup, I don't get to see that, therefore a `break` (or `continue`) is not intuitive at all.

This non-intuitive behavior would only be "solvable" by understanding what the generated code looks like. But so does the existing approach: `return` breaks out of a very specific sequence of instructions. Not understanding what these are might lead to errors or incorrect behavior. So in essence: usage of `return` requires an understanding of the instructions that the markup gets compiled to. Your proposed solution would not change that.

The best advice I think one can give: don't use `return`. If the nesting becomes too much, maybe introducing a new component is a better approach.

**Comment by tn-5** [comment]
Thanks for the input. I think part of the reasoning behind my proposal was that, if implemented, the break/continue can be reliably used anywhere and produce correct output.

Using return not only requires understanding the generated code, but even so it may break in future releases if for some reason the code generation is updated.

I think regardless of this it would be good if the official documentation could be updated to provide guidelines for using flow control, even if it is as simpler as "don't use".

As to using components, for the "standard" multipage wizard layout we are currently using (all components) we already indent 6 levels before doing the actual content. Maybe this can be restructured: It is level 1 = check page initialised, 2 = wizard, 3 = wizardpages group, 4= specific wizard page, 5 = explicit page template (multiple renderfragments are used within the page so default childcontent cannot be used), page content @ level 6. Within this typically some display / editing is presented of a specific object. So, the first line is to check if that is null - this moves the real content to the 7th level of indent. Not really sure how this can be simplified.

Currently we are using a "return" for the top level check - this removes one level, but I know using return is fundamentally not a good idea and the safety of using it is dependent on knowing how the code is generated.

**Comment by stefanloerwald** [comment]
I agree that documentation should discourage the use of `return` within markup. While syntactically valid, the likelihood of experiencing semantically invalid code is pretty much guaranteed (unless exclusively used at top level).

`return` could technically be made safer by producing
```cs
builder.OpenElement(0, "div"); // or: builder.OpenComponent...
try
{
   // any content, attributes etc
}
finally
{
   builder.CloseElement(); // or: builder.CloseComponent
}
```

instead of

```cs
builder.OpenElement(0, "div"); // or: builder.OpenComponent...
// any content, attributes etc
builder.CloseElement(); // or: builder.CloseComponent
```

But even though that's possible, I see no significant upside and two downsides:

- potentially worse performance
- the behavior of a return would still be very hard to understand

So I can only repeat my recommendation: Don't use `return` in markup.
