### ISSUE TITLE
[Authentication.Negotiate] How to specify enable mechanics during negotation

### ISSUE THREAD

**Issue by PTEC3S20** [dotnet/aspnetcore#25434]
Hi,

I'm currently trying to use this nuget : https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Negotiate/3.1.7 and I have some difficulty to find where I could indicate which token mechanics will be allowed to authenticate. In my case, I would like to disable NTLM from negotiation (so server won't indicate this mechanics during GSS-API negotiation and reject token using this mechanic).

I was looking at this documentation : https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.negotiate.negotiateoptions?view=aspnetcore-3.0 and seach for sample online. The closer parameter I finded is AuthenticationSchemeOptions.Validate, however I didn't find any sample using it and its documentation didn't specify what kind of string this method needs.

So there is my questions :
•	Is there a way to indicate which mechanics is allowed (or disabled) by the server during the negotiation ?
•	If it is, how can I do it ?

Thanks for taking time looking at my case.
Regards, 
Martin Médaillon

**Comment by Tratcher** [comment]
NTLM can't be disabled in the API, only in the registry. Note the middleware will only ever challenge for `Negotiate`, but the operating system may choose to fall back to NTLM.
