### ISSUE TITLE
ArgumentNullException thrown by JsonPatchDocument.ApplyTo in JObjectAdapter.TryAdd

### ISSUE THREAD

**Issue by EcoleKeine** [dotnet/aspnetcore#25431]
### Describe the bug
 Exception when JsonPatchDocument.ApplyTo JObject with null object

### To Reproduce
`

        [Fact]
        public void JsonPatchJObjectNullBug()
        {
            var jsonPatch = new JsonPatchDocument();
            jsonPatch.Add("/Obj", new ExpandoObject());
            jsonPatch.Copy("/NullObj", "/Obj/Copy");

            {
                dynamic obj = new ExpandoObject();
                obj.NullObj = null;
                jsonPatch.ApplyTo(obj);//ok
            }

            string jsonPatchJson = JsonConvert.SerializeObject(jsonPatch);
            var jsonPatchFromJson = JsonConvert.DeserializeObject<JsonPatchDocument>(jsonPatchJson);
            //Obj:{} is Deserialize to JObject

            {
                dynamic obj = new ExpandoObject();
                obj.NullObj = null;
                jsonPatchFromJson.ApplyTo(obj);//exception
            }
        }

        class POCO
        {
            public object Obj { get; set; }
            public object NullObj { get; set; }
        }

        [Fact]
        public void JsonPatchJObjectNullBug2()
        {
            var jsonPatch = new JsonPatchDocument();
            jsonPatch.Add("/Obj", new JObject());
            jsonPatch.Copy("/NullObj", "/Obj/Copy");
            {
                object obj = JsonConvert.DeserializeObject(@"{Obj:{},NullObj:null}");
                //NullObj:null is Deserialize to JToken
                jsonPatch.ApplyTo(obj);//ok
            }
            {
                object obj = JsonConvert.DeserializeObject<POCO>(@"{Obj:{},NullObj:null}");
                //NullObj:null is Deserialize to null
                jsonPatch.ApplyTo(obj);//exception
            }
        }
`

### Exceptions (if any)
 System.ArgumentNullException : Value cannot be null. (Parameter 'o')

    ValidationUtils.ArgumentNotNull(Object value, String parameterName)
    JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
    JToken.FromObject(Object o)
    JObjectAdapter.TryAdd(Object target, String segment, IContractResolver contractResolver, Object value, String& errorMessage)
    ObjectAdapter.Add(String path, Object value, Object objectToApplyTo, Operation operation)
    ObjectAdapter.Copy(Operation operation, Object objectToApplyTo)
    Operation.Apply(Object objectToApplyTo, IObjectAdapter adapter)
    JsonPatchDocument.ApplyTo(Object objectToApplyTo, IObjectAdapter adapter)
    JsonPatchDocument.ApplyTo(Object objectToApplyTo)

### Further technical details
- ASP.NET Core version 3.1
- Microsoft.AspNetCore.JsonPatch 5.0.0-preview.8.20414.8

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/pull/29410
