### ISSUE TITLE
Uncaught (in promise) RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by sbchong** [dotnet/aspnetcore#25449]
### Describe the bug
Now, I want to use blazor framework to upload a picture file, but I cannot find a nice official component. So I use Javascript to read a file to a base64 string, I encountered an error ：when the size of my uploaded file exceeds 200kb, the browser will prompt **Uncaught (in promise) RuntimeError: memory access out of bounds**

### Further technical details
- ASP.NET Core version 3.1
- VS 16.7.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sbchong.
We have added a new `InputFile` component in Blazor in RC1 which will help you avoid all the JSInterop.

**Comment by mkArtakMSFT** [comment]
https://github.com/dotnet/aspnetcore/issues/12205
