### ISSUE TITLE
MultipartFormDataContent extension method that takes IFormFile

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#25445]
I have a ASP.NET application that uploads the file it receives to a backend file storage microservice. So the user uploads the file to the ASP.NET application which in turn uploads it to a microservice.

If ASP.NET Core provided a `Add` extension method for the [`MultipartFormDataContent`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.multipartformdatacontent) class that accepted a [`IFormFile`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfile) as the parameter, you could do:

```cs
var content = new MultipartFormDataContent();
content.Add(model.File, "file");
```

Now you have to do:
```cs
var file = new StreamContent(model.File.OpenReadStream());
file.Headers.ContentType = new MediaTypeHeaderValue(model.File.ContentType);
var content = new MultipartFormDataContent();
content.Add(file, "file", model.File.FileName);
```

## Extension method
```cs
public static class MultipartFormDataContentExtensions
{
    public static void Add(this MultipartFormDataContent content, IFormFile file, string name)
    {
        var stream = new StreamContent(file.OpenReadStream());
        stream.Headers.ContentType = new MediaTypeHeaderValue(file.ContentType);
        content.Add(stream, name, file.FileName);
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do. The extension method is tiny and we encourage people to add it to their apps if they want.
