### ISSUE TITLE
Blazor - Oidc implicit flow - HttpClient with HttpMessageHandler doesn't store the returned token

### ISSUE THREAD

**Issue by diogomota** [dotnet/aspnetcore#25453]
### Describe the bug
Hi,

I've been implementing OidcAuthentication on a blazor app (client side). Following the docs here:
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1&tabs=visual-studio

and to get and use tokens in the httpClient calling the backend service I've followed the docs from:
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1

Taking the sample Blazor template as an example.
The login link at the top right works fine. It redirects to Okta for the authentication and returns back to the blazor app with the correct user name displayed on the top nav bar.

The problem I'm having is with the HttpClient using a token. These are the two main issues:

1- If I use the Login button in the nav bar to login, and then trigger an action that uses the HttpClient, it still redirects again to okta for authentication (even though the user is already authenticated and the blazor app captured that (the user name is correctly displayed in the navbar))

2- After the HttpClient redirects to the okta login page, the authentication succeeds and it goes back to the blazor page, but the httpClient remains unauthenticated and will once again redirect to the Okta login page.  
(On the console the exception that is being caught is the AccessTokenNotAvailableException, as if the token is not recorded by the httpClient...)

From the Okta logs, I can see that the authentication succeeds but the httpClient doesn't seem to store the token...

### To Reproduce

Program.cs:

```
public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddOidcAuthentication(options =>
            {
                options.ProviderOptions.Authority = "https://Mydomain.okta.com/oauth2/default";
                options.ProviderOptions.ClientId = "MyClientId";
            });

            //We need a custom AuthorizationMessageHandler because the backend is at api.example.com and our blazor client
            //is at example.com
            builder.Services.AddHttpClient("AuthenticatedClient",
                    client => client.BaseAddress = new Uri("http://api.example.co.uk"))
                .AddHttpMessageHandler(sp => sp.GetRequiredService<AuthorizationMessageHandler>()
                    .ConfigureHandler(
                        new[] {"http://api.example.co.uk"},
                        scopes: new[] { "openid" }));

            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>()
                .CreateClient("AuthenticatedClient"));
            
            await builder.Build().RunAsync();
        }
```

page: AccountSettings.razor

```
@page "/accountsettings"
@using Web.Services.AccountManagement.Dtos
@inject HttpClient Client
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
@using Newtonsoft.Json

<h3>AccountSettings</h3>

<h4>@details.FirstName</h4>
<h4>@details.LastName</h4>
<h4>@details.Email</h4>
<button @onclick="Click">Go</button>

@code {
    [Parameter] public UserDetails details { get; set; }

    public async void Click(MouseEventArgs ev)
    {
        try
        {
            Client.BaseAddress = new Uri("http://api.example.co.uk");
            var a = await Client.GetAsync("/account/details");
            a.EnsureSuccessStatusCode();

            var content = await a.Content.ReadAsStringAsync();
            var x = JsonConvert.DeserializeObject<UserDetails>(content);
            details = x;
        }
        catch (AccessTokenNotAvailableException e)
        {
            e.Redirect();
        }
    }
}
```

Looking at the okta logs:

The request url from the httpClient is: 
`/oauth2/default/v1/authorize?client_id=MyClientId&redirect_uri=https%3A%2F%2Flocalhost%3A44395%2Fauthentication%2Flogin-callback&response_type=id_token&scope=openid%20profile&state=75f021a78ca947cfb62b9de731405ba6&nonce=f8ddd541652e4c0a9d7048d2f24494e8`

and a similar request being made from the swagger page for the backend api is:
` /oauth2/default/v1/authorize?nonce=SWAGGER&scope=openid&response_type=token&client_id=MyClientId&redirect_uri=http%3A%2F%2Fapi.example.co.uk%2Fapi%2Foauth2-redirect.html&state=TW9uIEF1ZyAzMSAyMDIwIDE4OjAxOjE2IEdNVCswMTAwIChCcml0aXNoIFN1bW1lciBUaW1lKQ%3D%3D`

Both these requests are marked in the Okta logs as: `OAuth2 authorization implicit access token request: Success`   (and it works in the swagger page).  I assume there is something preventing the HttpClient on the blazor side from recording the token?

All other pages in the Blazor project are unchanged from the blazor client demo template.

**Comment by diogomota** [comment]
Also followed the example from @javiercn on: BlazorGrpcAuth  ---> https://github.com/javiercn/BlazorGrpcAuth/blob/master/BlazorGrpcAuth/Client/Program.cs

But it appears to be configured in the same way 😕 (except for the base address that must be different because the api is not in the app base uri)

**Comment by diogomota** [comment]
Just an update on this.

It looks like indeed something is broken in the AuthorizationMessageHandler.
I registered the httpClient without the AuthMessageHandler,  got the token from IAccessTokenProvider and injected it into the ClientHttp header and everything works.  So it seems like the token is there, the message handler just isn't capturing it.

Program.cs:

```
(...)
 builder.Services.AddOidcAuthentication(options =>
            {
                options.ProviderOptions.Authority = "https://MyDomain.okta.com/oauth2/default";
                options.ProviderOptions.ClientId = "MyUser";
                options.ProviderOptions.ResponseType = "id_token token";
            });

builder.Services.AddHttpClient("AuthenticatedClient",
                client => client.BaseAddress = new Uri("http://api.example.uk"));
//Note no Message Handler
builder.Services.AddSingleton(sp => sp.GetRequiredService<IHttpClientFactory>()
                .CreateClient("AuthenticatedClient"));
(...)
```

and getting the token from IAccessTokenProvider:
AccountSettings.razor:

```
@code {

    [Parameter]
    public UserDetails details { get; set; };

    public async void Click(MouseEventArgs ev)
    {
        var tokenResult = await TokenProvider.RequestAccessToken();

        tokenResult.TryGetToken(out var token);

        Client.BaseAddress = new Uri("http://api.example.co.uk");
        Client.DefaultRequestHeaders.Add("Authorization",$"Bearer {token.Value}");
        var a = await Client.GetAsync("/account/details");

        var content = await a.Content.ReadAsStringAsync();
        details= JsonConvert.DeserializeObject<UserDetails>(content);
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by diogomota** [comment]
Hi @mkArtakMSFT   here is a demo project: https://github.com/diogomota/BlazorWasmOidcBug/

Tested with my okta IDP settings and the issue is reproducible here. Is just a case of updating the IDP provider settings to use a test one

**Comment by javiercn** [comment]
@diogomota this looks wrong.

https://github.com/diogomota/BlazorWasmOidcBug/blob/3525222d26a540181c6fee6a3bf90b211c973f20/BlazorApp1/BlazorApp1/Program.cs#L29-L34

You are not requesting a scope for an access token, so you are likely not getting one back. We won't send an ID token in the handler.

**Comment by diogomota** [comment]
@javiercn I'm requesting the openId scope (which is already in `options.ProviderOptions.DefaultScopes`  on the AddOidcAuthentication() call.

Just tested with Postman, and It is able to get an access token from the request (The request url from postman matches the one sent by the blazor App) 

Might be misunderstanding your message.. How would you expect the scope for an access token to be requested?

**Comment by javiercn** [comment]
I'm expecting you to get two tokens, I would suggest you put a breakpoint on AuthenticationService.js and see what comes back out of the library when it provisions the token, but it seems to me that you are only requesting the openid scope, which will give you an id token.

I don't know how Okta works, but you most likely need to request an additional scope for an API in order to get an access token. Note that using the id token for auth is not something we support.

**Comment by diogomota** [comment]
It looks like the AuthenticationService.Js is getting the two tokens, Id and access.

Placed a breakpoint in:
```
t.SigninResponse = function() {
                function e(t) {
                    var r = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : "#";
                    !function(e, t) {
                        if (!(e instanceof t))
                            throw new TypeError("Cannot call a class as a function")
                    }(this, e);
                    var n = i.UrlUtility.parseUrlFragment(t, r);
                    this.error = n.error,
                    this.error_description = n.error_description,
                    this.error_uri = n.error_uri,
                    this.code = n.code,
                    this.state = n.state,
                    this.id_token = n.id_token,
                    this.session_state = n.session_state,
                    this.access_token = n.access_token,
                    this.token_type = n.token_type,
                    this.scope = n.scope,
                    this.profile = void 0,
                    this.expires_in = n.expires_in
                }
```

and both id and access_token fields are populated after the blazor redirect.  (I also configured Okta to always send an access token for scope = openId (that is why the postman call with the same parameters retrieves the accessToken)

So it looks like the access token is being lost between the handover from JS to C#...

Still doesn't explain why using the IAccessTokenProvider to get a token works just fine. I was under the impression that AuthorizationMessageHandler just used IAccessTokenProvider in the background?

**Comment by diogomota** [comment]
@javiercn  I found the exact line where things go wrong.

I created my own AuthorizationMessageHandler, exactly the same as the one on the repo with one single change on the `sendAsync` method:

```
(...)
if (_lastToken == null || now >= _lastToken.Expires.AddMinutes(-5))
                {
                    var tokenResult = _tokenOptions != null ?
                        await _provider.RequestAccessToken(/*_tokenOptions*/) :    //My chage: never use_tokenOptions
                        await _provider.RequestAccessToken();
(...)
```
Essentially I'm bypassing the use of _tokenOptions  and everything now works as expected.

Looking at the `RequestAccessToken` method, in `RemoteAuthenticationService.cs`   it seems like the only difference between calling with or without options, is this line:

`var result = await JsRuntime.InvokeAsync<InternalAccessTokenResult>("AuthenticationService.getAccessToken", options);`

so this works fine:
`var result = await JsRuntime.InvokeAsync<InternalAccessTokenResult>("AuthenticationService.getAccessToken");`

this doesn't (capture the token):
`var result = await JsRuntime.InvokeAsync<InternalAccessTokenResult>("AuthenticationService.getAccessToken", options);`

Unfortunately that now goes into JS land and the getAccessToken method is painful to read.

Let me know if I can do anything more on my side to debug this.

**Comment by wynnytsky** [comment]
@diogomota 
I had the same issue with BlazorWASM + PKCE.  Seeing at how you referenced "http://api.example.co.uk" in both places I followed your example, replacing my reference to BaseAddressAuthorizationMessageHandler with AuthorizationMessageHandler, and bam that worked!

Both the version in the original video and the latest one here don't work:
https://github.com/okta/samples-blazor/blob/master/web-assembly/hosted/okta-hosted-login/okta-blazor-web-assembly-example/Client/Program.cs

In this screen shot of the intellisence it says the request URL must be in the supplied white list for the access token to be returned.  I didn't even need to specify scopes.
![image](https://user-images.githubusercontent.com/1315399/95895954-7d473080-0d59-11eb-983b-5890f8c63add.png)
