### ISSUE TITLE
Verify limits on JS interop

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#25451]
Add E2E test showing the maximum sizes for transferred data, plus include this info in docs.

**Comment by pranavkm** [comment]
@SteveSandersonMS were you alluding to the limits here: https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/InputFile/RemoteBrowserFileStreamOptions.cs? We have coverage for file size limits and number limits in our e2e tests and they've been documented.

**Comment by SteveSandersonMS** [comment]
No, I was referring to things like "maximum string length" in arguments and return values for regular JS interop calls (not `InputFile`).

> We have coverage for file size limits and number limits in our e2e tests and they've been documented.

Are you referring to `InputFile` here, or something more general?

**Comment by pranavkm** [comment]
Let me know if you still think this is important to do. Seeing we haven't seen a lot of queries in this space, I'm closing this.

**Comment by SteveSandersonMS** [comment]
Nah, closing is fine. I'm not sure what was the original context for opening this. I'm sure that the current work with binary/stream interop is going to result in us having more test scenarios in this area as well as more tools available to developers to overcome any limits.
