### ISSUE TITLE
DefaultHttpResponse throws null ref when trying to access Cookies, even when using null check, only from bots

### ISSUE THREAD

**Issue by jeffputz** [dotnet/aspnetcore#25454]
### Describe the bug
I'm attempting to set a cookie with the following code ([source is here](https://github.com/POPWorldMedia/POPForums/blob/f52c9a99d1090bb1ff1b776be9f3ea253ab7eb91/src/PopForums.Mvc/Areas/Forums/Services/TopicViewCountService.cs#L39)):
```
var context = _httpContextAccessor.HttpContext;
context.Response?.Cookies?.Append(CookieKey, topic.TopicID.ToString());
```
...where the context accessor is inserted via DI. However, per the stack trace listed below, `Microsoft.AspNetCore.Http.DefaultHttpResponse.get_Cookies()` throws a null ref exception. What's even more strange is that it only occurs with search indexing bots. So far I've logged errors from Bing, Google, webmeup, brandwatch, mj12bot, semrush, grapeshot and others. It's __always__ a bot.

My assumption is that even if the `Cookies` property in my code was null, it shouldn't fail, and stack trace is throwing from within the `DefaultHttpResponse` code. Two interesting points though:
* It's always a bot when this error is logged.
* It seems to have started when I migrated the site to a Linux app service on Azure (was previously a Windows based app service on Azure).

### To Reproduce
I can't reproduce this locally. While I'm recording the full headers of the search bots, nothing stands out as a reason that for the cookie `get` on `DefaultHttpResponse` to throw. For fun though, here are some typical headers, this one from Bing:
```
Cache-Control: no-cache
Connection: Keep-Alive
Pragma: no-cache
Accept: */*
Accept-Encoding: gzip, deflate
From: bingbot(at)microsoft.com
Host: coasterbuzz.com
Max-Forwards: 10
User-Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
X-Client-IP: 40.77.167.62
X-Client-Port: 17849
X-WAWS-Unencoded-URL: /Forums/Topic/first-park-for-the-2002-season
CLIENT-IP: 40.77.167.62:17849
X-ARR-LOG-ID: 66fbfb17-df14-425f-8571-192af0f32d6d
DISGUISED-HOST: coasterbuzz.com
X-SITE-DEPLOYMENT-ID: coasterbuzz
WAS-DEFAULT-HOSTNAME: coasterbuzz.azurewebsites.net
X-Original-URL: /Forums/Topic/first-park-for-the-2002-season
X-Original-Proto: http
X-ARR-SSL: 4096|256|C=GB, S=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA|CN=coasterbuzz.com
X-AppService-Proto: https
X-Forwarded-TlsVersion: 1.2
X-Original-For: [::ffff:172.16.3.1]:11898
```

### Exceptions (if any)
```
NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.AspNetCore.Http.DefaultHttpResponse.get_Cookies()
   at PopForums.Mvc.Areas.Forums.Services.TopicViewCountService.SetViewedTopic(Topic topic)
   at PopForums.Mvc.Areas.Forums.Services.TopicViewCountService.ProcessView(Topic topic)
   at PopForums.Mvc.Areas.Forums.Controllers.ForumController.Topic(String id, Int32 pageNumber)
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Further technical details
* ASP.NET Core version: 3.1.7 (SDK 3.1.401)
* Running on Linux Azure App Service, self-contained deployment

**Comment by Tratcher** [comment]
@pranavkm, do the `ResourceInvoker.Rethrow` calls in that stack imply a different exception was already thrown before they ended up on this call path?

**Comment by pranavkm** [comment]
It's usually MVC rethrowing a previously captured exception after allowing filters to decide if they want to handle it: https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/Infrastructure/ResourceInvoker.cs#L1424-L1445

**Comment by Tratcher** [comment]
Ok, nevermind.

@jeffputz this seems like the kind of error you'd get due to multi-threaded access to the HttpContext. Is there any parallel processing on these requests? I don't see anything obvious in your controller.

**Comment by jeffputz** [comment]
@Tratcher no, nothing exotic at all. Like I said, I didn't even start seeing it until flipping to a Linux app service, and found it even stranger that the bots were the only user agents showing in the errors. It feels environmental.

**Comment by Tratcher** [comment]
The main thing that would have changed there is a shift from IIS in-process to Kestrel. Kestrel does some interesting things to re-use HttpContext instances, which is the next most likely source of this, but that doesn't explain why only bots would hit it.

**Comment by jeffputz** [comment]
Yes, it's weird, and even more weird that it's on the response, where anywhere in the stack I would assume a cookie collection, even empty, would exist. I looked at the aspnet source and I don't entirely understand what's going on, and I don't understand why the getter itself throws the exception.

**Comment by Tratcher** [comment]
ResponseCookiesFeature would have to return null, 
https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L118
Which it's never supposed to do, it's supposed to lazily create a new instance.
https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L51-L52
https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L19

@benaadams you played with FeatureReferences most recently, interested in taking a look?

**Comment by jeffputz** [comment]
I got one today finally that is **not** a bot, it's a phone.
```
Connection: Keep-Alive
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Host: coasterbuzz.com
Max-Forwards: 10
User-Agent: Mozilla/5.0 (Linux; Android 10; Pixel 3a XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Mobile Safari/537.36
X-Client-IP: 74.125.73.143
X-Client-Port: 37459
Purpose: prefetch
Sec-Fetch-Site: none
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: empty
X-WAWS-Unencoded-URL: /Forums/Topic/how-do-gravitrons-work
CLIENT-IP: 74.125.73.143:37459
X-ARR-LOG-ID: 77d84f2d-1b61-47fa-83ab-a3477b35c1c0
DISGUISED-HOST: coasterbuzz.com
X-SITE-DEPLOYMENT-ID: coasterbuzz
WAS-DEFAULT-HOSTNAME: coasterbuzz.azurewebsites.net
X-Original-URL: /Forums/Topic/how-do-gravitrons-work
X-Original-Proto: http
X-ARR-SSL: 4096|256|C=GB, S=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA|CN=coasterbuzz.com
X-AppService-Proto: https
X-Forwarded-TlsVersion: 1.2
X-Original-For: [::ffff:172.16.3.1]:18726
```

**Comment by benaadams** [comment]
The only why I can see this happening is if `DefaultHttpResponse.Uninitialize()` had been called which defaults out the `_features` collection (called at the end of the request)

https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http/src/Internal/DefaultHttpResponse.cs#L40-L43

Meaning `Collection` is null in `FeatureReferences<TCache>`
https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http.Features/src/FeatureReferences.cs#L33

Which would then `null` ref in `UpdateCached`
https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http.Features/src/FeatureReferences.cs#L83-L91

However... `UpdateCached` is only called by `Fetch` which has a guard check for `Collection` being null where it throws an `ObjectDisposed` exception (line 70)

https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Http/Http.Features/src/FeatureReferences.cs#L64-L79

So this would mean the Context/Request/Response is disposed while the `Fetch` method is still accessed and the request is finished while it is still active, so concurrent activity; most likely from a missed `await`.

Nothing jumping out at me why that would happen looking at the code in this section
```csharp
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.get_Cookies()
   at PopForums.Mvc.Areas.Forums.Services.TopicViewCountService.SetViewedTopic(Topic topic)
   at PopForums.Mvc.Areas.Forums.Services.TopicViewCountService.ProcessView(Topic topic)
   at PopForums.Mvc.Areas.Forums.Controllers.ForumController.Topic(String id, Int32 pageNumber)
```

Wondering what the `lambda_method` is here
```
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
```
As `TaskOfActionResultExecutor.Execute` is correctly awaiting the result
https://github.com/dotnet/aspnetcore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/Infrastructure/ActionMethodExecutor.cs#L178-L182

But I also don't see a lambda

**Comment by Tratcher** [comment]
Makes sense. I don't see any missed awaits in that callstack either. The closest I see are these which are using .Result instead of await, but they shouldn't 
https://github.com/POPWorldMedia/POPForums/blob/f59c397383ce73cd6c41297e078073471df3b2ad/src/PopForums.Mvc/Areas/Forums/Authorization/PopForumsAuthorizationMiddleware.cs#L22
https://github.com/POPWorldMedia/POPForums/blob/f59c397383ce73cd6c41297e078073471df3b2ad/src/PopForums.Mvc/Areas/Forums/Authorization/PopForumsAuthorizationMiddleware.cs#L32

I'm not sure there's much else we can investigate here unless you can get a more restricted repro.

**Comment by jeffputz** [comment]
@Tratcher yeah, those shouldn't change the outcome. I'll update that (remnant of the pre-async days), but I think a property that throws a null ref in the getter is not ideal regardless. I can't check to see that it's null before calling it since it's framework code. That it only happens with bots and only since moving to a Linux app service feels like there's an environmental edge case that hasn't been covered.

**Comment by jeffputz** [comment]
Just to confirm, updating the above middleware to be async did not change the outcome, as expected.

**Comment by benaadams** [comment]
I can put a patch in to stop the null ref https://github.com/dotnet/aspnetcore/pull/25892; but that will just return a `ObjectDisposedException` instead, so wouldn't help in practical terms

**Comment by jeffputz** [comment]
@benaadams that's a better exception, but, while I'm not a designer of frameworks, a property that throws when checking it seems like a bad idea. It makes the whole thing feel like a leaky abstraction, where you need deep understanding of the underlying code.

**Comment by Tratcher** [comment]
@jeffputz The standing theory is that this is caused by an invalid use-after-disposed call happening somewhere, likely due to an async issue. The ObjectDisposeException just makes that more clear. We still need to track down the original issue.

**Comment by davidfowl** [comment]
I took at look and haven't seen anything strange as yet either.

**Comment by jeffputz** [comment]
I'm seeing it right in the CI build now, which is straight out of my git repo. Again, didn't start seeing it until I flipped to Linux app services. Same stack trace.

```
Connection: Keep-Alive
Accept: text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml
Accept-Encoding: gzip,deflate
Host: popforumsdev.azurewebsites.net
Max-Forwards: 10
User-Agent: Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)
X-Client-IP: 185.191.171.9
X-Client-Port: 12314
X-WAWS-Unencoded-URL: /Forums/Topic/this-is-my-first-new-topic
CLIENT-IP: 185.191.171.9:12314
X-ARR-LOG-ID: ccd1e808-0707-4c1d-ad26-79c1f086cf48
DISGUISED-HOST: popforumsdev.azurewebsites.net
X-SITE-DEPLOYMENT-ID: popforumsdev
WAS-DEFAULT-HOSTNAME: popforumsdev.azurewebsites.net
X-Original-URL: /Forums/Topic/this-is-my-first-new-topic
X-Original-Proto: http
X-ARR-SSL: 2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 5|CN=*.azurewebsites.net
X-AppService-Proto: https
X-Forwarded-TlsVersion: 1.2
X-Original-For: [::ffff:172.16.5.1]:56193
```

**Comment by Tratcher** [comment]
After reviewing this again I don't think we'll be able to investigate further without a more isolated repro of the issue.

Other things to consider:
- Are you using any of the app service loggers or Application Insights? They've had a history of trying to touch the HttpContext from a background thread.

**Comment by mattcottam91** [comment]
I think I'm seeing a similar bug, or at least a similar effect.

We're running integration tests on the dotnet core 3.1-buster docker image (which looks like it's on dotnet sdk 3.1.403).

We have some tests checking authorisation logic which occasionally fail with a null reference on the last line of the below snippet:
```
var context = ContextAccessor.HttpContext;
var request = context.Request;
var query = request.Query;
```
The stack trace shows that it hits DefaultHttpRequest and fails on the Query get, and digging through the code I independently came to the same conclusion as @benaadams above - that something somewhere is calling Uninitialize on the request. Googling that issue was what brought me here.

What also stood out is the comment from @jeffputz that it was only when flipping to Linux - we only see it on our CI server (running a Linux docker image), and never running tests locally on windows machines, so that would explain that. I'll try doing some runs via the same docker image locally to see if I can reproduce it that way.

I appreciate there's not much to go on so far, and the root causes may be different. Just giving you another data point in case it helps at all. I'll let you know if I find anything else too, and let me know if any more info would be helpful.

**Comment by davidfowl** [comment]
@mattcottam91 What's the call stack in your case?

**Comment by mattcottam91** [comment]
Hi @davidfowl, thanks for the quick reply.

Having poked around over the weekend, I noticed that we've still got App Insights initialisation code active in our integration tests, and I have a sneaking suspicion we're running into https://github.com/microsoft/ApplicationInsights-dotnet/issues/1635 (but as it's a weird race condition no-one's managed to pin down yet, it's hard to prove). We've probably only seen it in tests so far because our application's still in development, so we only get the necessary load in that scenario.

I've removed the App Insights logic from our integration tests and will see how it goes over the next few days. Assuming it goes away in our tests I'll take my message over to that thread. But I'll update here if the issue doesn't go away and it seems like something else is the culprit (and will give an example call stack).

So apologies but I suspect we may be seeing a slightly different issue to the OP.

**Comment by jeffputz** [comment]
Weird, I didn't get the notification for this being updated three weeks ago. Sorry...

@Tratcher I'm not using any kind of monitoring or anything interesting... it's a straight deployment of the [POPWorldMedia/POPForums](https://github.com/POPWorldMedia/POPForums) project running from the CI pipeline on an Azure Linux app service, but I have other instances of it that log the same error.

Let me reiterate this though: It didn't start happening until I moved all of those instances to Linux app services. And it still only happens from bots, creating a lot of noise. It's kind of reassuring that @mattcottam91 only sees it in a Linux environment too. That smells like there's something in the abstraction between the framework bits and HTTP stack. It's also reassuring to see #27655 reported same.

I go back to the thing where it's problematic that a property getter would ever cause a null ref exception. I mean, if it's null, then it should be null, right? When I put the conditional access qualifiers in the code of my original stack above (`context.Response?.Cookies?.Append(...`), Resharper even warns me, "Conditional access qualifier expression is known to be not null." The framework bits disagree. :)

**Comment by davidfowl** [comment]
> I go back to the thing where it's problematic that a property getter would ever cause a null ref exception. I mean, if it's null, then it should be null, right? When I put the conditional access qualifiers in the code of my original stack above

There's definitely a bug here but the reason these sorts of things usually happen is because of concurrency. If you end up in a situation where some other code is running that clears out the state you're holding onto.

We usually see this with `IHttpContextAccessor` because it allows its easy to use it outside of the request context.

We may need to get a process dump to narrow this down and find the issue.

**Comment by Tratcher** [comment]
On Windows you were probably using the default IIS server, where on Linux you'll always use Kestrel. That does change some of the implementation and also some timings.

@davidfowl isn't Kestrel the only place that we pool HttpContexts?

**Comment by davidfowl** [comment]
The HttpContext isn't going to be pooled when using the IHttpContextAccessor but the underlying state will be reset though it should happen in such a way that makes the HttpContext access disposable before doing so. This shouldn't be an issue unless things were being referenced in a multithreaded way anyways. 

But that's a good assumption. We need to figure out if it's kestrel where this behavior shows up and if there's any concurrency being introduced into the http request pipeline

**Comment by jeffputz** [comment]
In this case, I am going through `IHttpContextAccessor`, but it's downstream one layer into a typical request (from a controller action, to a service class), so it hasn't traveled back up the middleware at this point. In the old days I remember passing around `HttpContext` from the controller, which was horrible because of all the test setup. In fact, that's why my test coverage isn't as great because I threw all of those tests away!

Are bots known to do anything naughty like drop the connection in the middle of a request, and would Kestrel work differently with that?

**Comment by davidfowl** [comment]
Dropping the connection in the middle of the request is fine, disposing things happens when the middleware pipeline returns, not when the connection dies. That's why @Tratcher was asking if there are any async voids in the project earlier.

**Comment by jeffputz** [comment]
@davidfowl nope, nothing like that. Even if there was, presumably I could then repro this locally on Windows.

**Comment by Tratcher** [comment]
@jeffputz on Windows are you testing it against Kestrel or IIS? Try Kestrel.

**Comment by jeffputz** [comment]
@Tratcher I've tried Kestrel, and I've tried against live instances on Linux Azure app services. I can't figure out exactly what's making the bot hits different, even setting up the same headers with Postman requests. I can't get it to fail.

**Comment by jeffputz** [comment]
Kind of weird to let the bot close unresolved things.

**Comment by Tratcher** [comment]
This was moved to Discussions after we'd exhausted all of the theories. We can re-open it if a more reliable repro becomes available.

**Comment by jeffputz** [comment]
Where in discussions? I mean, you still have a property that can throw an exception when it's accessed, which you can see in the source code. That seems like a really poor design choice.

**Comment by Tratcher** [comment]
I meant the discussions milestone.

We know the design is brittle in multi-threaded environments. That's a deliberate trade-off for the performance we wanted to achieve. That's why we spent most of this thread trying to figure out where the suspected cross-thread modifications were coming from. Without some indication of where that modification is happening it's hard to investigate further.

**Comment by davidfowl** [comment]
@jeffputz There's definitely a bug here but we don't know how to reproduce, that said, we should re-open it until we can investigate further. Our best guess is based on other bugs that look like this from the past that it's multithreaded access as @Tratcher says. Is it still showing up for you?

**Comment by jeffputz** [comment]
@davidfowl thank you. Keep in mind that, it's an anecdote, but I didn't see this until moving to Linux app services, so it may be something in that abstraction between the fx and the OS.

**Comment by davidfowl** [comment]
@jeffputz if you can still reproduce the issue on windows, this guide might help you capture a dump https://github.com/microsoft/ApplicationInsights-dotnet/issues/1524#issuecomment-1146848272.
