### ISSUE TITLE
[Blazor] New Parent Component Service Lifetime

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#25472]
Hi,

I have a somewhat complex UI scenario that deals with nested components that need to communicate with each other. Some of the components are reliant on 3rd party components with whatever limitations they have, so the most practical implementation of the communication mechanism is to create a service that the components subscribe to in order to invoke/handle various events.

The problem with this approach is that I somehow need to pass the service instance to the components down the hierarchy - I used the concept of the ``CascadingValue`` to achieve this - please take a look at the outline of my UI below.

ParentComponent.razor
```
@inject MyServiceService MyService

<CascadingValue Value="MyService">
    <CompoentA />
</CascadingValue>

<div>...some UI...</div>

<CascadingValue Value="MyService">
    <ComponentB />
</CascadingValue>
```

ComponentA.razor
```
<div>.. some UI...</div>
<Component C>
```

ComponentC.razor.cs
```
[CascadingParameter]
public MyService MyService { get; set; }
```

MyService in the example is registered with scoped lifetime.

Would it make sense to create a new service lifetime "ParentComponent" ensuring that when injecting MyService into any component that is a descendant (and any of its descendants) of the parent component, it would use the parent's instance of the service? I'd like to avoid using ``CascadingValue`` completely if possible. Maybe there is a different approach that I'm not aware of?

Thanks!

**Comment by mrpmorris** [comment]
You can descend your component from OwningComponentBase<MyService>. Blazor will create a new service scope and you'll get a new instance of your Scope service that you can cascade.

Note that if a child component asks for the service via `@inject` then you'll get the original service insurance and not the newly created one.

This will hopefully help https://blazor-university.com/dependency-injection/component-scoped-dependencies/owningcomponentbase-generic/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. CascadingValue passes down the specific instance you want. In your case, if you pass in the instance the parent component has, then that's exactly what all the child components will get. This seems to cover the scenario you're interested in.
