### ISSUE TITLE
Running `dotnet watch run` doesn't rebuild for changes to component specific CSS 

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25483]
Repro steps:

- Install .NET 5 Preview 8
- Create a new Blazor WebAssembly app
- Run `dotnet watch run` on the new project
- Modify *Shared/MainLayout.razor.css*

Expected result:

- The app is rebuilt and restarted

Actual result:

- The  app is not rebuilt and restarted

> Note: Running `dotnet watch run` should **not** rebuild and restart the app for changes to normal CSS files. These can just be reloaded in the browser.

@pranavkm

**Comment by pranavkm** [comment]
We changed this fairly recently as part of fixing https://github.com/dotnet/aspnetcore/issues/22219. Could you grab a fairly new SDK and give this a try?

**Comment by danroth27** [comment]
Still repros with 5.0.100-rc.1.20451.8

**Comment by danroth27** [comment]
Still repros with RC2
