### ISSUE TITLE
[Blazor] Disable Javascript output from blazor.server.js

### ISSUE THREAD

**Issue by flacidsnake** [dotnet/aspnetcore#25492]
After logging in, the access token used to connect to SignalR is printed to the browser console

Should be a way of disabling this.

**Comment by melikpehlivanov** [comment]
Hello, @flacidsnake. Please take a look [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#javascript-client-logging)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @flacidsnake have you tried configuring the log-level as pointed out by @melikpehlivanov?

**Comment by flacidsnake** [comment]
Hi @melikpehlivanov , thank you for your response. I'm injecting SignalR with services.AddSignalR() in the Startup.cs file. How can I access then to the HubConnectionBuilder to modify the logging level?

Thanks

**Comment by melikpehlivanov** [comment]
Hi, it's good to hear that you've resolved your problem. Please consider closing the issue!
