### ISSUE TITLE
BlazorDebugProxy in published out

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#25497]
When I do a `dotnet public -c Release ...` the published output contains a `BlazorDebugProxy`. I wouldnt expect any debug helpers in a publised release version. Is there any way to omit this from being added to the published output?

**Comment by captainsafia** [comment]
@njannink Not at the moment. If you're interested in this feature, I'd recommend putting a "thumbs up" reaction on this older reported issue (#25102).

I'll close this issue out as a dupe.
