### ISSUE TITLE
rzc discovered exited with code -532462766

### ISSUE THREAD

**Issue by sfernandez131** [dotnet/aspnetcore#25498]
I'm attempting to build a new ASP.NET app. To test that it's working, as soon as Visual Studio 2019 v16.7.2 has finished creating the app I launch it. During the build I get the error mentioned in the title.

My dotnet versions are:
2.1.809 [C:\Program Files\dotnet\sdk]
3.1.302 [C:\Program Files\dotnet\sdk]
3.1.401 [C:\Program Files\dotnet\sdk]
5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

I've tried it with target framework .NET Core 3.1 and .NET 5. Both produce the same error.

**Comment by pranavkm** [comment]
@sfernandez131 could you look at the VS Build output? It might have more content that indicates what went wrong.

**Comment by sfernandez131** [comment]
I just fixed it by adding a global.json and specifying:
{
  "sdk": {
    "version": "3.1.401"
  }
}

I have the "Use previews of the .NET Core SDK" ticked under Options > Environment > Preview Features. Typically that works fine but I guess it didn't with ASP.NET.
