### ISSUE TITLE
Project fails compilation after upgrading to lates preview (Version 16.8.0 Preview 2.1)

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#25525]
I am using Blazor Hosted WebAssembly application and after upgrading it to latest version(Version 16.8.0 Preview 2.1) it started
failing the build with the following error, there is one more similar error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'string' to 'in Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame'	GetInLine.Client	XXXXXGetToken.razor.g.cs	187	Active

  ```
 protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "id", "container");
            __builder.OpenElement(2, "div");
            __builder.AddAttribute(3, "class");
            __builder.OpenElement(4, "div");
            __builder.AddAttribute(5, "class", "row text-center");
            __builder.OpenElement(6, "div");
            __builder.AddAttribute(7, "class", "col col-auto");
            __builder.OpenElement(8, "button");
            __builder.AddAttribute(9, "class", "btn btn-success");
            __builder.AddAttribute(10, "type", "button");
            __builder.AddAttribute(11, "id", "btnfullscreen");
            __builder.AddAttribute(12, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 31 "XXXXXXXXXinGetToken.razor"
                                                                                             () => { JSRuntime.InvokeVoidAsync("toggleFullScreen"); }
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Also, are you targeting .NET 5.0 or .Net Standard 2.1?

**Comment by kenleese** [comment]
https://github.com/dotnet/aspnetcore/issues/25267#issuecomment-681850250 ?

**Comment by nssidhu** [comment]
<TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>

**Comment by mkArtakMSFT** [comment]
Thanks @nssidhu.
We still will need a small repro to investigate this.

**Comment by Phloog** [comment]
I can reproduce this, and I have a workaround: Search for empty attributes in your HTML (e.g. <img src="foo.png" alt="" />  - the alt="" is an empty attribute) or attributes without values at all (e.g.  <input name="foobar" disabled>  -  the "disabled"). Change them to contain anything (e.g. alt=" " with a space in the quotes, disabled="1" works as well).
