### ISSUE TITLE
WebAssembly benchmark app includes PDBs in publish output

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#25533]
Repro:

 * `cd src\Components\benchmarkapps\Wasm.Performance\TestApp`
 * `dotnet publish -c Release`
 * `more bin\Release\net5.0\publish\wwwroot\_framework\blazor.boot.json`
 * Notice that the `pdb` entry contains items

Having PDBs in the publish output substantially worsens the benchmark results, since the presence of these files causes us to start up the runtime with debugging enabled.

As far as I know, this bug only applies to the `Wasm.Performance` app, not to real apps using the real SDK, so it's not as catastrophic as it would be. However we do want the benchmark results to be representative of real apps otherwise they aren't useful and might mislead us.

**Comment by SteveSandersonMS** [comment]
Sidenote: I'm no longer sure what causes PDBs to be included or excluded, since it's not clear we have logic in the Razor SDK to control that. We should look into re-enabling the following test (about whether PDBs are published for real apps) as soon as we can: https://github.com/dotnet/aspnetcore/issues/25135 - possibly immediately if the SDK update we were waiting for has now arrived.

**Comment by mkArtakMSFT** [comment]
This is going to be addressed with an SDK update, which is happening as part of #25081

**Comment by pranavkm** [comment]
```
src\Components\benchmarkapps\Wasm.Performance\TestApp> ls .\bin\Release\net5.0\publish\wwwroot\_framework\*.pdb | Measure-Object

Count             : 0
```
