### ISSUE TITLE
OnGet does not support page parameter

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#25537]
### Problem Summary

I am unable to use `page` as a parameter name to my `OnGet()` method.

### Details

I'm trying to add paging to my */Index* page.

So I coded things like:

**Page**

    @page "{page?}

**Code**

    public async Task<IActionResult> OnGetAsync(string page)
    {
        // ...
    }
    
But when `OnGetAsync()` is called with the URL *https://www.domain.com/page=5*, the `page` parameter contains "/Index". It contains the name of the current page instead of the query argument.

If I change the name of my query argument to just `p`, then it works just fine.

### Solution
I can't tell if this is some intended feature. But `page` would actually be a pretty common query argument name to use. I don't see any advantage to what it's doing, but either way I should be able to use a parameter with the name I choose.

### Additional context

This is an ASP.NET Core 3.1 Razor Pages project. Visual Studio version 16.7.2.

**Comment by javiercn** [comment]
@SoftCircuits thanks for contacting us.

`page` is a reserved route value used to identify the razor page an action is routed to, similar to `controller` and `action` in MVC.

**Comment by SoftCircuits** [comment]
@javiercn Thanks for the explanation. I was thinking there was something like that going on. However, "page" might just be the most common query argument name. So this doesn't seem like a very good idea to me.

**Comment by javiercn** [comment]
This isn't something that we can or plan to change, it would be a massive breaking change.
