### ISSUE TITLE
Highlighting is "lagging" behind when using the new razor editor

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#25531]
The new razor editor behaves different when highlighting keywords.  While typing there is no highlighting - it only kicks in when you terminate the statement.  

This is not just cosmetics because direct highlighting gives you immediate feedback that the token is valid and enables you to ctrl-click on the valid token to further inspect it.  

Old:

![classic](https://user-images.githubusercontent.com/8482283/91970522-0fe6bf80-ed18-11ea-9793-97256effc456.gif)

New:

![new](https://user-images.githubusercontent.com/8482283/91970535-16753700-ed18-11ea-9ca2-d4fe9a27dc20.gif)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This was an intentional change we've made in the new Razor editor.
