### ISSUE TITLE
Code snippets are not displayed in razor editor

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#25530]
No Code snippets are working in either the experimental razor editor or the classic one.  Also reported here https://github.com/dotnet/aspnetcore/issues/8904#issuecomment-659273387

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 2.0

![codesnp](https://user-images.githubusercontent.com/8482283/91969192-09efdf00-ed16-11ea-8f86-d5154071c14c.gif)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which we track as part of https://github.com/dotnet/aspnetcore/issues/22744
