### ISSUE TITLE
Blazor: expose 'replace' parameter in NavigationManager.NavigateTo

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#25540]
### Is your feature request related to a problem? Please describe.
I want to maintain some of my view state in the URL, such as the currently selected tab.  I can and do use `window.history.replaceState` for this, but the `NavigationManager.Uri` is then out of sync.  I'd like to be able to keep the `Uri` in sync, as I'm using it to help manage this state.  I need to get the `Uri` synchronously so I can't just call `location.href` using interop.

#### Simple option
I believe the simplest solution would be to make `NavigationManager.Uri` settable publicly so I can then perform this task myself.  I don't want to have to implement my own `NavigationManager` just for this purpose. It is already clear in the docs that setting `Uri` doesn't trigger `LocationChanged`, which again, is my desired behavior, so hopefully making this public isn't too big of a concern.

#### Fancier option
The other option is to expose the `replace` that already exists in `navigateTo()` in `NavigationManager.ts`.  However... I don't want to trigger `OnParametersSet` in my scenario, and I think this would do so by default.  Personally, I'd like to submit a PR for the first option and leave this one on the table.

**Comment by javiercn** [comment]
@zbecknell thanks for contacting us.

I don't think we want to make the setter public, it will cause confusion between that and the NavigateTo method. Exposing the option in NavigationManager to replace the state would be the preferred approach, in fact we added that to the .ts file becasue we needed it on auth, but we couldn't add that to NavigationManager during the Blazor webassembly release.

I think this has been an oversight on our part and we should enabled the API in NavigationManager, but I don't think we can do anything about it for 5.0.

That said, I'll leave it here for consideration in our triage process.

**Comment by zbecknell** [comment]
That's certainly understandable to avoid confusion.  I'll look for a workaround for the time being.

**Comment by MariovanZeist** [comment]
I am interested in working on this issue.

As this will include an API change I will propose the following change:

A change to the NavigateTo function in the NavigationManager class
by adding an optional boolean parameter that can be set to true to replace the current Uri in the browser history.
If set to false, (or not supplied) it will do the default action and push the new Uri onto the browser history stack.

So change the function from:
` public void NavigateTo(string uri, bool forceLoad = false)`

To:
` public void NavigateTo(string uri, bool forceLoad = false, bool replace = false)`

**Comment by campersau** [comment]
Has this been fixed by https://github.com/dotnet/aspnetcore/pull/33751 ?

**Comment by SteveSandersonMS** [comment]
Why yes it has. Thanks for pointing that out!
