### ISSUE TITLE
Please consider X-Forwarded-Proto in DefaultAntiforgery.CheckSSLConfig

### ISSUE THREAD

**Issue by provegard** [dotnet/aspnetcore#25559]
### Is your feature request related to a problem? Please describe.

I have an application for which I have enabled antiforgery support. I'd like the antiforgery cookie to be secure, so I have set:

    services.AddAntiforgery(options =>
    {
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
    });

I run the application in a Kubernetes cluster in GCP. The cluster is configured so that HTTPS traffic is terminated at the load balancer - after that it's HTTP.

This means that I get the following error:

> System.InvalidOperationException: The antiforgery system has the configuration value AntiforgeryOptions.Cookie.SecurePolicy = Always, but the current request is not an SSL request.

To clarify: The user visits the application using HTTPS, but the traffic between the load balancer and the Kubernetes pod is HTTP.

### Describe the solution you'd like

The load balancer sends the following header:

     X-Forwarded-Proto: "https"

It would be nice if `DefaultAntiforgery.CheckSSLConfig` considered this header and accepted SecurePolicy = Always if the original request is HTTPS.

**Comment by Tratcher** [comment]
Our guidance is to manage forwarders in a central location rather than to make every possible component aware of them. See:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1
