### ISSUE TITLE
Revisiting How do I pass parameters such as System.string [] to the Blazor (WASM) application #24461

### ISSUE THREAD

**Issue by PSCRIMS** [dotnet/aspnetcore#25550]
Steve Sanderson gave a suggestion using a Javascript code. The issue was closed.

The problem that I have is that if I want to write a Blazor Webassembly app that take variables as input parameter I have no way of doing this, i.e. I write an app that should take 4 parameters and the app is always called with these parameters in order, so that I can write them as singletons and use in my app. I am new to Blazor but it looks like a much needed feature.  Maybe I am wrong. if so, feel free to correct me.

I've been bouncing between Blazor server and Webassembly. On the server version I was able to intercept the app in program.cs and using straight C# (not even razor syntax) accomplish that but then I ran into a problem of how to contact another URI with these and additional parameters entered by the user (as I mentioned I am new to Blazor)

If not, any idea as to a time frame to implement this?

Thanks is advance

Paul Rosemberg

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
For now we recommend using the approach pointed out in https://github.com/dotnet/aspnetcore/issues/24461.
In the long term we will try to expose an API to allow this.

**Comment by PSCRIMS** [comment]
Looking forwards.
