### ISSUE TITLE
Successfully deploying .NET 5.0 preview 8 AspNetCore hosted Blazor WebAssembly to Azure requires manual copying of _framework folder

### ISSUE THREAD

**Issue by rollandjb** [dotnet/aspnetcore#25569]
### Describe the bug
A self-contained .NET 5.0 preview 8 AspNetCore hosted Blazor WebAssembly app deployed to Azure App Service fails to run with the browser console message `blazor webassembly Uncaught ReferenceError: MONO is not defined`.

> Please note that a workaround is described below.

### To Reproduce

With .NET 5.0 preview 8 installed, proceed as follows:

1. Create a new ASP.NET Core hosted blazor webassembly project.

    `dotnet new blazorwasm -ho -o Preview8Test`

2. Prepare the publish artefacts:
    
    From the solution folder, `Preview8Test`, execute:

    `dotnet publish --configuration Release --runtime win-x86 --self-contained -o .local/win-x86`

    > `.local` is just a non-git utility folder

3. Compress the contents of `.local/win-x86` and zip deploy the resulting archive to Azure app service

4. Browse to the app service and observe the error:

    `Uncaught ReferenceError: MONO is not defined`

### To Work around

1. Prepare the publish artefacts as before:

    `dotnet publish --configuration Release --runtime win-x86 --self-contained -o .local/win-x86`

2. Prepare the Client publish artefacts

    `dotnet publish -c Release Client -o .local/browser-wasm`

3. Replace the contents of `.local/win-86/wwwroot/_framework` with the contents of `local/browser-wasm//wwwroot/_framework`

4. As above, compress the contents of `.local/win-x86` and zip deploy the resulting archive to Azure app service

5. Expect success

### Comments

- Perhaps the `--self-contained` flag is inappropriately being applied to the Client publish

- Performing the publish from the `Server` project result in error:

   `...'project.assets.json' doesn't have a target for 'net5.0/browser-wasm'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. You may also need to include 'browser-wasm' in your project's RuntimeIdentifiers.`

- I tried, to no avail, to use the **.NET 5.0 preview 8** extensions with a zip deploy of a standard publish command. The result was HTTP Error 503 Service Unavailable.
- I am running this on a B2 service plan

### Further technical details
- ASP.NET Core version: 5.0.100-preview.8.20417.9
- Include the output of `dotnet --info`
```
   .NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.8.20417.9/

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.6.20318.15 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.7.20366.6 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.8.20417.9 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

   VS Code 1.48.1 on MacOS 10.15.6 (19G2021)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Glad that you've found the workaround already.
This is a known issue which is being tracked by #25188.
