### ISSUE TITLE
@alfkonee It looks like the debugging proxy may be crashing. Is this by any chance a PWA?

### ISSUE THREAD

**Issue by Murilobdo** [dotnet/aspnetcore#25567]
@alfkonee It looks like the debugging proxy may be crashing. Is this by any chance a PWA?

_Originally posted by @danroth27 in 
https://github.com/dotnet/aspnetcore/issues/25566

my application is pwa

**Comment by mkArtakMSFT** [comment]
Closing as we will try to address this as part of the referenced issue.
