### ISSUE TITLE
Add method to tell a blazor app that the requested ressource for a parameter razor component could not be found

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#25564]
### Is your feature request related to a problem? Please describe.
I have a page which can be visited by Parameter, e.g. 
`@page "/Customer/{CustomerNumber:int}"`

In my overritten method `OnParametersSetAsync` I check if my customer exists. If not I want to trigger the NotFound area.

### Describe the solution you'd like
Perhaps you can add a method to the NavigationManager which tells my blazor app that the requested page is not found.
Or
Provide a method in the component it self which can be used to validate the parameters and trigger a not found exception.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
