### ISSUE TITLE
Missed IAccessTokenProvider service

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/aspnetcore#25561]
I have blazor standalone wasm project and i want to authenticate user with [Aditional scenario](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1)

so, startup code in main function is :

    ```
        builder.Services.AddOptions();
            builder.Services.AddAuthorizationCore();
           
            builder.Services.AddScoped<AuthStateProvider>();
            builder.Services.AddScoped<AuthenticationStateProvider>(s => s.GetRequiredService<AuthStateProvider>());
            builder.Services.AddScoped<AuthenticationService>(s => new ExtendAuthenticationService());

            builder.Services.AddTransient<AuthMessageHandler>();
            builder.Services.AddHttpClient("ServerAPI", client => client.BaseAddress = AppModelContext.BaseUri).AddHttpMessageHandler<AuthMessageHandler>();
            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("ServerAPI"));


then injected property in login form to create HttpClient instance :

```
         [Inject]
        public IHttpClientFactory ClientFactory { get; set; }
```

then in login function

```
public async void Login()
{
   var Client = ClientFactory.CreateClient("ServerAPI");
  .
  .
  .
}
```

on create instance of httpclient line, this exception will thrown:

Unhandled Exception:System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider' while attempting to activate 'AppModel.Services.Authentication.AuthMessageHandler'.

- blazor WebAssembly 3.2.0
- IDE : VS 2019

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What are you trying to achieve by customizing the `AuthenticationStateProvider`?

**Comment by ehsangfl** [comment]
I have an existing authentication service (CORS), and try to use existing AuthenticationService.
the code of AuthStateProvider is 

```

    public class AuthStateProvider : AuthenticationStateProvider
    {

        AuthenticationService Api;

        public AuthStateProvider(AuthenticationService api)
        {
            this.Api = api;
            api.LoggedIn += OnLoggedIn;
            api.LoggedOut += OnLoggedOut;
        }

        private void OnLoggedOut(object sender, AuthenticationEventArgs e)
        {
            NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(new ClaimsPrincipal(e.User))));
        }

        private void OnLoggedIn(object sender, AuthenticationEventArgs e)
        {
            NotifyAuthenticationStateChanged(GetAuthenticationStateAsync());
        }

        public async override Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            var identity = new ClaimsIdentity();
            var userInfo = GetCurrentUser();
            if (userInfo != null && userInfo.Identity.IsAuthenticated)
            {
                var claims = new[] { new Claim(ClaimTypes.Name,Api.User.Identity.Name)}.Concat(WebContext.Current.User.Roles.Select(c => new Claim(ClaimTypes.Role, c)));

                identity = new ClaimsIdentity(claims, "Authentication");
            }
            return new AuthenticationState(new ClaimsPrincipal(identity));
        }

        private IPrincipal GetCurrentUser()
        {
            if (Api.User.Identity.IsAuthenticated) return Api.User;
            return null;
        }
```

**Comment by javiercn** [comment]
Thanks for contacting us.

Seems that you are trying to implement your own authentication system. `IAccessTokenProvider` is part of our authentication system, so you either use the built-in auth, or you remove anything that depends on it.

**Comment by ehsangfl** [comment]
thanks for your answer.

this is not "Authentication System". I want to use my "Authentication API" only.
this Authentication api is worked on all platforms of my enterprise app (Asp.net web forms,silverlight,MVC (Knockout binding),Xamarin forms, etc... this application has more than 12 years old
we must use it, cause of data layer repository, that exists and worked on all platform

If we dont use it, we must write a new data repository for blazor platform. and this is not good for reuse existing code.

we use all built-in authentication system parts, like AuthorizeView, AuthorizeAttribute, CascadingAuthenticationState, etc...

I think there must be a way, that we can use our "Authentication API", or describe how to implement an "Authentication System"
based on your offer, if we want to remove all your authentication system, there is not any document to manage ASP Identity's token (cookie) on blazor wasm plaform.
how can we use this cookie, without your built-in authentication system?
Thanks
BR

**Comment by TheAnachronism** [comment]
I have the same issue.
Any news on this?
