### ISSUE TITLE
Date issue in DevExpress Datagrid in asp.net core

### ISSUE THREAD

**Issue by Prachi2801** [dotnet/aspnetcore#25571]
We are using Devexpress version 15 for datagrid in .net core. We have column as "Updated At", in this column value comes from the database. And we have another column which is a runtime column "Updated At Local(UTC + X)" X based on the timezone of client machine, it can be …-2, -1, 1, 2, 3… and so on. In "Updated At Local(UTC + X)" it takes date time from the "Updated At" Column and converts it into the local timezone and displays it in Updated At Local (UTC + X) column.but what happens is when we drag and drop "Updated At Local (UTC + X)" from the column chooser to the data grid, it shows #Err in "Updated At Local(UTC + X)" column.
Any Suggestions would be helpful.

settings.Columns.Add(m => m.ReviewCycle.SubmissionDate, col =>
    {
        col.ApplyDateColumnSettings();
        col.Visible = false;
    });

    settings.AddLocalTimeColumn(c => c.ReviewCycle.SubmissionDate, "SubmissionDateLocal", "Submission Date Local", Model.UtcOffset);

   public static MVCxGridViewColumn AddLocalTimeColumn<T>(this GridViewSettings<T> settings, Expression<Func<T, object>> dataFieldFunc, string name, string caption, int utcOffset)
        {
            if (dataFieldFunc == null)
                throw new ArgumentNullException("dataFieldFunc");

            var body = dataFieldFunc.Body as MemberExpression;

            if (body == null)
            {
                var ubody = (UnaryExpression)dataFieldFunc.Body;
                body = ubody.Operand as MemberExpression;
            }

            var dataFieldName = body.Member.Name;

            var column = settings.Columns.Add(name);
            column.Caption = $"{caption} (UTC {(Math.Sign(utcOffset) >= 0 ? "+" : "-")}{utcOffset / 60})";
            column.UnboundType = DevExpress.Data.UnboundColumnType.DateTime;
            column.UnboundExpression = $"AddMinutes([{dataFieldName}], {utcOffset})";
            column.Visible = false;
            column.Settings.AllowHeaderFilter = DefaultBoolean.False;
            column.Settings.AllowGroup = DefaultBoolean.False;
            column.Settings.AllowFilterBySearchPanel = DefaultBoolean.False;
            column.Settings.AllowSort = DefaultBoolean.False;
            column.Settings.AllowAutoFilter = DefaultBoolean.False;
            column.PropertiesEdit.DisplayFormatString = "dd MMM yyyy HH:mm";
            return column;
        }

        public static void ApplyDateColumnSettings(this MVCxGridViewColumn column)
        {
            column.Settings.AllowHeaderFilter = DefaultBoolean.True;
            column.SettingsHeaderFilter.Mode = GridHeaderFilterMode.DateRangeCalendar;
            column.PropertiesEdit.DisplayFormatString = "dd MMM yyyy HH:mm";
        }

**Comment by javiercn** [comment]
Thanks for contacting us @Prachi2801.

It looks like this is a question about how to use a third party component. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core tag.
