### ISSUE TITLE
Improve template titles and icons

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/aspnetcore#25576]
In Visual Studio we are working on a feature that will [show the community templates in the New Project Dialog](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/#comment-7162).
As a part of that, we are getting rid of the "One ASP.NET" dialog for ASP.NET Core. Since the ASP.NET Core projects will no longer be in the context of the One ASP.NET dialog, we should improve the titles and icons. I've looked at all the templates and have suggestions below. For the titles, the recommendation is to use the same titles that are displayed when using `dotnet new`.

### Empty Web
![image](https://user-images.githubusercontent.com/1283154/92144882-5e15c480-ede5-11ea-9511-6363b9ae0466.png)

 - Suggested title: ASP.NET Core Empty
 - Icon: need language adornment

### API
![image](https://user-images.githubusercontent.com/1283154/92145608-76d2aa00-ede6-11ea-978e-aac349487ae8.png)

 - Suggested title: ASP.NET Core Web API
 - Icon: needs language adornment

### Web app
![image](https://user-images.githubusercontent.com/1283154/92145670-910c8800-ede6-11ea-9c3e-6454b61e8943.png)

 - Suggested title: ASP.NET Core Web App
 - Icon: needs language adornment

### MVC
![image](https://user-images.githubusercontent.com/1283154/92145740-ada8c000-ede6-11ea-8b42-c1d1a135204e.png)

 - Suggested title: ASP.NET Core Web App (Model-View-Controller)
 - Icon: needs language adornment

### Angular
![image](https://user-images.githubusercontent.com/1283154/92146688-117fb880-ede8-11ea-97a4-c7a6eed180e6.png)

 - Suggested title: ASP.NET Core with Angular
 - Icon: would be nice to have language adornment, but since it's C# only it's less important than the other ones

### React
![image](https://user-images.githubusercontent.com/1283154/92146812-425fed80-ede8-11ea-9881-fffe1d8d6af8.png)

 - Suggested title: ASP.NET Core with React.js
 - Icon: would be nice to have language adornment, but since it's C# only it's less important than the other ones

### React.js and redux
![image](https://user-images.githubusercontent.com/1283154/92146915-67ecf700-ede8-11ea-981b-7f99f7dbc952.png)

 - Suggested title: ASP.NET Core with React.js and Redux
 - Icon: would be nice to have language adornment, but since it's C# only it's less important than the other ones

@mkArtakMSFT @Pilchie @vijayrkn @timheuer

**Comment by javiercn** [comment]
@danroth27 FYI

/cc: @Pilchie

**Comment by danroth27** [comment]
The proposed template titles look good to me.

I don't think we should add language adornments to the Angular/React icons. That will make it look like we somehow have a C# version of these JS frameworks 😋.

@DamianEdwards FYI.

**Comment by sayedihashimi** [comment]
Thanks Dan

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/25630 Related PR

**Comment by Pilchie** [comment]
Closing as the PR was merged into the RC2 branch.
