### ISSUE TITLE
Dotnet Core Project Migrated from 2.2 to 3.0.1 build fails 

### ISSUE THREAD

**Issue by eshwar-crystal** [dotnet/aspnetcore#25583]
# Dotnet Core 3.0.1 Project Build Fails with AuthenticationDescription error
I have been running a 2.2 project for the last 12 months and I migrated to 3.0.1 on the basis of Microsoft's documentation. The new migrated project fails with one build error as follows:

Models\ManageViewModels\ManageLoginsViewModel.cs(12,22): error CS0246: The type or namespace name 'AuthenticationDescription' could not be found (are you missing a using directive or an assembly reference?) [C:\ErpOneCore\ErpOneCore.csproj]
Be as descriptive as you can with your title.

# General
I learn that the following class is deprecated

Microsoft.AspNetCore.Http.Authentication;
and I have placed the following Using statement in the ManageLoginsViewModel.cs file
using Microsoft.AspNetCore.Authorization.Policy;

I also tried creating a new dotnet core 3.0.1 project with the following switches
dotnet new mvc --auth Individual
and it does not create the AccountController classes at all. In other words I am unable to check what new classes/views are being created when Individual authentication is specified. The comparison would have given me a hint on how to change the class files...

I have attached the following files for your reference
csproj
startup.cs
program.cs
ManageLoginsViewModel.cs
[ManageLoginsViewModel.zip](https://github.com/dotnet/core/files/3901444/ManageLoginsViewModel.zip)

Could you help to fix:
1) Why dotnet new mvc --auth Individual does not create the classes for authentication
2) How to fix the build error shown above in the migrated project?
Thanks
Eshwar

**Comment by Pilchie** [comment]
Moving to aspnetcore - @HaoK / @javiercn / @blowdart Any suggestions.

**Comment by blowdart** [comment]
The advice from Cory is the right starting point. Scaffold identity and compare/contrast. There's no other way,

**Comment by eshwar-crystal** [comment]
Yes, I did the same thing – scaffolded identity and compared and changed..

Eshwar

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
