### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AuthenticationHandler should make BuildRedirectUri() virtual

### ISSUE THREAD

**Issue by DrEsteban** [dotnet/aspnetcore#25580]
### Is your feature request related to a problem? Please describe.
We're building an ASP.NET Core 3.1 app, hosted in a Linux container with Azure WebApps.  We're integrating with GitHub to provide authentication/identity for the app.

GitHub requires that the "redirect URI" passed on OAuth calls **exactly** match what's been configured on the GitHub App registration. Unfortunately, the [AuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/Security/Authentication/Core/src/AuthenticationHandler.cs) code is building a redirect URI with the wrong Scheme (HTTP vs HTTPS) which is causing GitHub to reject the OAuth calls.  I believe this is happening because Azure WebApps provides TLS termination for the backing applications, so from the application's perspective the call _is_ coming over HTTP.

There are 2 places where this bites us: on Challenge and on exchanging the code for a token.  The Challenge is fairly straightforward to fix, because we can override the virtual `BuildChallengeUrl()` from [OAuthHandler](https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/Security/Authentication/OAuth/src/OAuthHandler.cs):
```C#
protected override string BuildChallengeUrl(AuthenticationProperties properties, string redirectUri)
{
    return base.BuildChallengeUrl(properties, redirectUri.Replace("http://", "https://"));
}
```

However, the same can't be said for the token exchange flow, because OAuthHandler's `HandleRemoteAuthenticateAsync()` calls `BuildRedirectUri()` (from the AuthenticationHandler base class) right before the call to `ExchangeCodeAsync()`. So we've resorted to this fairly hacky solution:
```C#
protected override Task<OAuthTokenResponse> ExchangeCodeAsync(OAuthCodeExchangeContext context)
{
    var fixedContext = new OAuthCodeExchangeContext(context.Properties, context.Code, context.RedirectUri.Replace("http://", "https://"));
    return base.ExchangeCodeAsync(fixedContext);
}
```

There are plenty more places in the authentication pipeline where `BuildRedirectUri()` is used, but luckily that isn't affecting us (yet).

### Describe the solution you'd like
A lot of this could be avoided if `BuildRedirectUri()` were **virtual**, so that child classes could provide the exact redirectURI they want instead of having the framework try to be smart about it.  There are plenty of reasons why you'd want to customize the redirectURI, and the `BuildRedirectUri()` is the lowest-level method that controls this.  The alternative is placing hacky overrides in multiple places of the auth flow.

**Comment by Tratcher** [comment]
Our guidance is to manage proxy issues like this in a central location rather than to make every possible component aware of them. See:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

**Comment by Tratcher** [comment]
> There are plenty of reasons why you'd want to customize the redirectURI

Do you give examples that don't involve proxies?

**Comment by DrEsteban** [comment]
@Tratcher  Thanks so much for the suggestion!  That solved my issue nicely, didn't occur to me :)

Admittedly most of the scenarios I was thinking of did involve proxies. I suppose there could be a very edge-case scenario where your auth server endpoint is different than your webapp (and the auth server redirects you back to the webapp once OAuth is complete), but that's probably not very common.

I do still believe that making that method virtual is a low-cost change that would help alleviate these types of problems/confusions, although perhaps there is a security implication to doing that I'm not aware of!  Feel free to close this issue if this would ultimately be undesirable.

**Comment by blowdart** [comment]
Making the method virtual doesn't make sense for us as we'd have to do it in multiple handlers which react to forwarded headers. Auth shouldn't be a special case. I'm afraid the forwarding middleware is the only solution we have and that we'd consider.
