### ISSUE TITLE
Add Rename to Right Mouse Click in Blazor Components

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25597]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1109855/add-rename-to-right-mouse-click-in-blazor-componen.html)._

---
<p>VS Community 2019 supports Rename in Blazor components by hitting Ctlr-R twice.  Like other environments, this should be added as an option in the drop down on a right mouse click on a variable or method name.</p>

---
#### Feedback Bot on 7/12/2020, 08:53 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by TanayParikh** [comment]
This effort is being tracked with https://github.com/dotnet/aspnetcore/issues/21978.
