### ISSUE TITLE
Blazor Base Class Approach

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25599]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1041157/blazor-base-class-approach.html)._

---
<p>While creating a component in blazor, if we use the partial class approach, the component and code-behind class become nested. We will like this feature with the base class approach also maybe after the </p><pre>@inherits CounterBase

</pre>

---
#### hassan3130 on 5/20/2020, 04:44 AM: 

<p>It would be nice if we are able to navigate to the base clas by right clikcing also.</p>

#### Feedback Bot on 5/21/2020, 02:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### hassan3130 on 6/13/2020, 02:24 AM: 

<p>I think I found a nice way to do this</p>

**Comment by mkArtakMSFT** [comment]
Glad that you've found a solution to your problem, hassan3130.
We're closing this issue. If you happen to have another issue related to Blazor or Blazor tooling, feel free to file a new issue in this repo.
