### ISSUE TITLE
Change Blazor file extension

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25593]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1151130/change-blazor-file-extension.html)._

---
Please change blazor file extension from .blazor into something different(.blazor is horrible)
These extensions below are nice.
.rhtml
.rxhtml

---
#### Feedback Bot on 8/17/2020, 00:54 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.
