### ISSUE TITLE
Add Inline Null Check Feature

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1147562/add-inline-null-check-feature.html)._

---
It would be great if you could add an inline null check, like this one from Groovy on Grails:

myString?. trim()

So that the Trim() or ToString() or whatever action will not take place if the string is null.

---
#### Feedback Bot on 8/13/2020, 00:52 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Null-conditional operators are supported in ASP.NET Core projects.
Can you please provide more details about your project in which you don't have support for this?

We assume, you may be using pre-ASP.NET Core framework (ASP.NET) which doesn't have support for this. For ASP.NET we don't plan to add support for this operator.
