### ISSUE TITLE
Change ASP.NET Core's default web root directory from wwwroot to WebRoot

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25590]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1058611/change-aspnet-cores-default-web-root-directory-fro.html)._

---
Regarding https://docs.microsoft.com/de-de/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1 the default directory for a ASP.NET Core project's web root is **wwwroot**.

This is not only hard to pronounce, it also doesn't follow the naming convention for folders (e. g. **Controllers** or **Views** which is PascalCase).

Besides that, the method to change that directory is called Use**WebRoot** and not Use**WwwRoot** and therefore it would make more sense if the default folder would be **WebRoot** instead of **wwwroot**.

---
#### Feedback Bot on 6/1/2020, 07:08 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by BrennanConroy** [comment]
That would have been a nice change years ago but,
we're not changing this now, it's not worth the breaking change.

**Comment by Zerotask** [comment]
@BrennanConroy 
I can understand, that this would be a breaking change.
A possible solution to avoid a breaking change would be a backwards compatibility:
new templates will use **WebRoot** as the default directory and the code will look for this directory first. If it doesn't exist, it will check for the directory **wwwroot**.
If you upgrade your project and continue to use the wwwroot directory, it's all fine. Perhaps there are other issues with this solution I'm not aware of.
