### ISSUE TITLE
blazor.boot.json to blazor.boot.xml

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25592]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1156346/blazorbootjson-to-blazorbootxml.html)._

---
Just a suggestion for blazor webassembly
I was checking if possible to deploy published blazor webassembly to  sharepoint subsite
turned out is possible after I follow this guy repository `https://github.com/smjltd/BlazorPoint`

but in the step number 3 "Allow .json in Central admin"
and I am not Sharepoint administrator.
It need a lot of approval processes just to enable .json in sharepoint in where I work

So just wondering if possible  "blazor.boot.json" (or anything that is json) we could have "blazor.boot.xml" file or what ever file extension is allowed in Sharepoint, I know javascript is easier since it is already an object, 

Another suggestion might perhaps just rename all json files to something else, but keep the content as json

---
#### Feedback Bot on 8/21/2020, 02:04 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by javiercn** [comment]
Thanks for contacting us.

We recommend configuring sharepoint to be able to serve json files properly.

/cc: @danroth27
