### ISSUE TITLE
Provide AddDefaultIdentity alternative that doesn't provide default UI

### ISSUE THREAD

**Issue by micka190** [dotnet/aspnetcore#25596]
### Is your feature request related to a problem? Please describe.
I am trying to handle user account management on an ASP .NET Core application with my own UI implementation.
For example, I'd like to have passwords and two-factor authentication under the same page. This is simple enough to do, HTML-wise, but it has a glaring issue: the `AddDefaultIdentity` method call implicitly calls the `AddDefaultUI` method.

```csharp
public static IdentityBuilder AddDefaultIdentity<TUser>(this IServiceCollection services, Action<IdentityOptions> configureOptions) where TUser : class
{
    services.AddAuthentication(o =>
    {
        o.DefaultScheme = IdentityConstants.ApplicationScheme;
        o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddIdentityCookies(o => { });

    return services.AddIdentityCore<TUser>(o =>
    {
        o.Stores.MaxLengthForKeys = 128;
        configureOptions?.Invoke(o);
    })
        .AddDefaultUI() // <------------------ call here
        .AddDefaultTokenProviders();
}
```

Obviously, this can be avoided by copying the method's implementation, writing my own small method and removing that particular line. But I have a few concerns regarding this, most notably: How safe is this in the long run? As the framework evolves and new versions come out, I expect that this method's behavior may be subject to change. As such, copying the implementation and removing the call to `AddDefaultUI` seems more like a path than a fix to me (and a potentially harmful one if the method's behavior changes in the future).

### Describe the solution you'd like
I'm wondering if it'd be possible to toggle the call to `AddDefaultUI` either through a method parameter or something similar to the framework's current `services.AddX(options => {...})` predicate system.

Something like changing the method's implementation to look like this:

```csharp
public static IdentityBuilder AddDefaultIdentity<TUser>(this IServiceCollection services, Action<IdentityOptions> configureOptions, bool useDefaultUI = true) where TUser : class
{
    services.AddAuthentication(o =>
    {
        o.DefaultScheme = IdentityConstants.ApplicationScheme;
        o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddIdentityCookies(o => { });

    var builder = services.AddIdentityCore<TUser>(o =>
    {
        o.Stores.MaxLengthForKeys = 128;
        configureOptions?.Invoke(o);
    })
        .AddDefaultTokenProviders();
    
    if (useDefaultUI)
    {
        builder.AddDefaultUI();
    } 
    return builder;
}
```

### Additional context
Additionally, I've found some recommendations to just use the `AddIdentity` method, however that method's implementation seems to be drastically different than the `AddDefaultIdentity` one, so I'm unsure whether it's better or not.

If someone from the ASP.NET Core team could comment on the best way to handle this in the mean time, it'd be greatly appreciated!

**Comment by blowdart** [comment]
As the recommendations you've seen state, you shouldn't use DefaultIdentity, that does our opinionated defaults, which include our opinionated UI. Making part of a default optional moves away from it being the default bits that get you at a good starting point, including a UI.

This isn't something we'd consider I'm afraid.
