### ISSUE TITLE
Create New Project - Blazor App

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25595]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/999613/create-new-project-blazor-app.html)._

---
I think it would be a good idea to split Blazor App into two groups - Blazor Server App and Blazor WASM app so that there is no need to make a second selection on the blazor project screen.

---
#### Feedback Bot on 4/21/2020, 00:56 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by javiercn** [comment]
@danroth27 do you have any thoughts?

We don't think we plan to do this at the moment.
