### ISSUE TITLE
Razor HTML  nested @if errors when @ is not needed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25598]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/989783/razor-html-nested-2.html)._

---
In Razor html you can use @if blocks which is really nice, but if you use it while you are already in a @ block, you get an error.

```
@if (Model.IsEdit)
{
  --some html --
  @for (int a; a< b; a++) 
  {
    --some html --
  }
}

```
This produces an error on the @for line.
Why?? If it is not needed to put an @ there, then just ignore it.
Sometimes there is a lot of HTML and you can't always directly see you are already inside an @ block.

The little red wave-thingy indicating there is an error isn't very clear when it is below just one character.

Just don't throw an error, but gray it out as not needed, please?

---
#### Feedback Bot on 4/14/2020, 11:58 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The reason the `@` is not needed is that because you're already within a C# context, and for C# that character has a different meaning. This is by-design.
