### ISSUE TITLE
Update Razor Class Library template to use CSS isolation

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25600]
Update the Razor Class Library template to use CSS isolation for Component1.razor, as the styles are component specific.

**Comment by javiercn** [comment]
@danroth27 I tentatively plan to do this,

but it is lower on my list than some routing work I need to finish. In case someone wants to pick this up.

**Comment by SteveSandersonMS** [comment]
Reopening. Due to a bad rebase, this functionality got lost from its original PR.

The new PR for it is at https://github.com/dotnet/aspnetcore/pull/25870
