### ISSUE TITLE
One or more compilation references may be missing. If you're seeing this in a published application, set 'CopyRefAssembliesToPublishDirectory' to true in your project file to ensure files in the refs directory are published.

### ISSUE THREAD

**Issue by mmokhtari** [dotnet/aspnetcore#25610]
hello
im using asp.net core 3.1
im seprateing my shared things like html helper tag helper and so on on another assembly with target framework  .net core 3.1
when im trying to refrence the html helper extentions namespace im getting this error
The type or namespace name 'Framework' does not exist in the namespace 'MusigarSystem.Web' (are you missing an assembly reference?)
@using MusigarSystem.Web.Framework.UI

i set <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory> as error told but it does not fix problem

**Comment by javiercn** [comment]
@mmokhtari thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?
