### ISSUE TITLE
NullReferenceException in SignalR's DefaultHubDispatcher

### ISSUE THREAD

**Issue by mbashov** [dotnet/aspnetcore#25612]
`DefaultHubDispatcher` calls [`DisposeAsync`](https://github.com/dotnet/aspnetcore/blob/v5.0.0-preview.8.20414.8/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L139) on a null reference if `IServiceScopeFactory.CreateScope` throws an exception [here](https://github.com/dotnet/aspnetcore/blob/v5.0.0-preview.8.20414.8/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs#L114), so `NullReferenceException` is thrown from the `finally` block, overwriting the original exception. This happens when the application is stopping and dispatcher methods are called after `IServiceProvider` is disposed.

**Comment by BrennanConroy** [comment]
I'm guessing your app is being shutdown ungracefully? If so, we can't really guarantee cleanup to be clean either.

We can do a little cleanup here and move the `CreateScope` call outside of the try catch so the original exception is preserved.

**Comment by mbashov** [comment]
The shutdown is not graceful, but it is still reasonable to expect an exception from a disposed `IServiceProvider` in this case, not a NRE, isn't it?

**Comment by davidfowl** [comment]
Yes absolutely it just makes it a lower priority.
