### ISSUE TITLE
Publishing a Blazor Web Assmbly App results in 404s for pdb files

### ISSUE THREAD

**Issue by georgekosmidis** [dotnet/aspnetcore#25614]
While publishing a Blazor WebAssembly app to Azure:
![bwasm](https://user-images.githubusercontent.com/5938872/92236119-13637d80-eeb5-11ea-922f-d9b4a5edab76.png)

Source code: https://github.com/georgekosmidis/ImageToText
Azure DevOps: https://dev.azure.com/georgekosmidis/Blazor.ImageToText
Published to: https://i2t.azurewebsites.net/
(.NET Standard 2.1)

Possible relation with (or duplicate to) #18545

**Comment by javiercn** [comment]
@georgekosmidis thanks for contacting us.

Thanks for contacting us. Can you try this out with one of our 5.0 preview releases? (Preview8 or later)

**Comment by javiercn** [comment]
We think this might be related to https://github.com/dotnet/aspnetcore/issues/21178

**Comment by georgekosmidis** [comment]
Sorry for the delay, build and published with .NET 5-latest, same results...

**Comment by georgekosmidis** [comment]
For anyone ending up in this issue, the solution was to configure the publishment for release:

```- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c Release'
```

For more details, check the `release-azure-pipelines.yml`  here: https://github.com/georgekosmidis/ImageToText
