### ISSUE TITLE
Blazor changed ErrorMessage for RequiredAttribute is ignored

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#25611]
### Describe the bug
I have a property which has the Attribute [Required] assigned to. The error message depends on an attribute from the class so I cannot set the error message directly via [Required(ErrorMessage = "xxx")]

So I change the error message in the constructor of my class with reflection:

```
foreach (var property in this.GetType().GetProperties())
{
	var attribute = property.GetCustomAttribute<RequiredAttribute>();

	if (attribute != null)
	{
		switch (property.Name)
		{
			case nameof(Vorname):
				attribute.ErrorMessage = $"Name {nummer} is required";
				break;
			default:
				break;
		}
	}
}
```

The message is set correctly for the attribute, however ValidationSummary and ValidationMessage still shows "Field xxx is required" instead of my later set message.

### To Reproduce
Create a property and assign [Required] attribute. In the constructor of the object that hold my property change the ErrorMessage with reflection just as I showed in my code above

### Further technical details
- ASP.NET Core version 3.1.401
- VS 16.7.2
- Include the output of `dotnet --info`
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

That is not something we recommend and something we don't support. The instance you are mutating is not the same instance the runtime is looking at.
