### ISSUE TITLE
ReactNative x Signalr Webpack @microsoft/signalr-protocol-msgpack error

### ISSUE THREAD

**Issue by fabiobarboza7** [dotnet/aspnetcore#25618]
Hi, I'm trying to use @microsoft/signalr-protocol-msgpack in my react-native application in order to receive hubConnectionProtocol in binary instead json. The package works well with ReactJs but in React Native it has a bug when trying to load it dependencies. To make my question more clear see the prints below:

Code:

<img width="911" alt="Captura de Tela 2020-09-04 às 10 19 13" src="https://user-images.githubusercontent.com/39923194/92243594-17cd6d80-ee98-11ea-9774-007b3027b4ed.png">

Mobile error:

```error: Error: Unable to resolve module `buffer` from `node_modules/@microsoft/signalr-protocol-msgpack/dist/cjs/MessagePackHubProtocol.js`: buffer could not be found within the project.```

![WhatsApp Image 2020-09-04 at 10 20 00](https://user-images.githubusercontent.com/39923194/92243706-42b7c180-ee98-11ea-931b-33bcf3bccf17.jpeg)

So, from my side I did all react-native suggestions but I'm pretty sure that maybe it needs t add react native dependencies on it.

Thank you folks

**Comment by BrennanConroy** [comment]
Looks similar to https://github.com/dotnet/aspnetcore/issues/13805?

**Comment by fabiobarboza7** [comment]
> Looks similar to #13805?

Seems to be the same but actually I don't have that problem when I don't need the msgpack. So when using only `@microsoft/signalr` it works, different from #13805.  It only complains when I try to use `.../signalr-protocol-msgpack`

**Comment by BrennanConroy** [comment]
I see, can you try adding a dependency on the [buffer](https://www.npmjs.com/package/buffer) npm package and see if that resolves it?

**Comment by fabiobarboza7** [comment]
> I see, can you try adding a dependency on the [buffer](https://www.npmjs.com/package/buffer) npm package and see if that resolves it?

I did it and when I run it ask to add one more, and keep going asking adding dependencies from last dependency.

**Comment by BrennanConroy** [comment]
> I did it and when I run it ask to add one more, and keep going asking adding dependencies from last dependency.

I don't know what that means.

I tried a simple react-native project with messagepack and it worked fine. I did use the browser instead of android, so is this issue only specific to android?

There are people that have complained about buffer with react-native before https://github.com/facebook/react-native/issues/14796, there might be something you can add to your shim.js to make buffer work?

**Comment by fabiobarboza7** [comment]
> > I did it and when I run it ask to add one more, and keep going asking adding dependencies from last dependency.
> 
> I don't know what that means.
> 
> I tried a simple react-native project with messagepack and it worked fine. I did use the browser instead of android, so is this issue only specific to android?
> 
> There are people that have complained about buffer with react-native before [facebook/react-native#14796](https://github.com/facebook/react-native/issues/14796), there might be something you can add to your shim.js to make buffer work?

Hi, thank you Brennan for your feedback. What I mean is, if I follow your suggest ("...adding a dependency on the buffer") after installing it to cover the messagepack needs, a new module is required, the next one, dependency from messagepack called "assert", when I add "assert" it goes asking others and so on.

So, I'm not sure if I understood that you could run a simple react-native android app using signalR and the binary protocol (messagePack), if so, can you share it and I will compare just to make sure?

Answering you about IOS, I didn't tested it. It works fine for web application (vue, reactJs, pure html,css) but goes to that deep dependency error when build in ReactNative.

**Comment by BrennanConroy** [comment]
> can you share it and I will compare just to make sure?

It was just a simple app following the [docs](https://reactnative.dev/docs/environment-setup) and using the Tabs project. Then adding the signalr and signalr-protocol-msgpack and creating and starting a new hub connection on the first tab.

**Comment by fabiobarboza7** [comment]
Hi folks, ok, after couple of months I went back to the project and still facing the same error. So, to make sure that I did all suggestions from @BrennanConroy I initialized a really simple app with *ReactNative (Android) > @microsoft/signalr and @microsoft/signalr-protocol-msgpack*. Follow docs instructions and I gotta the exacly same error.
