### ISSUE TITLE
Blazor: display attempted value in error "Unable to set property '{prop}' on object of type '{type}'."

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#25625]
This is for tracking purposes, as I'll submit a PR in a moment.

For me, this is a simple change that'd help track down bugs quicker when receiving this exception.

**Comment by javiercn** [comment]
@zbecknell thanks for contacting us.

We are locking down the release and we want to be cautious about what we take, we will revisit this change in our next planning meeting, but it is likely this will end up in 6.0, since we want to play safe.

Thanks for the contribution!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue per https://github.com/dotnet/aspnetcore/pull/25626#issuecomment-689685313 comment.
