### ISSUE TITLE
Blazor Intellisense not working with 3rd party components

### ISSUE THREAD

**Issue by sjbthfc2** [dotnet/aspnetcore#25622]
Hi,

I am trying to use AntDesign and MatBlazor with the release version of Blazor with Visual Studio 2019 16.7.2 ant the Razor intellisense will not recognise any of the components from these libraries. It gives syntax errors in the markup:

![image](https://user-images.githubusercontent.com/3796984/92259391-15d2d100-eecf-11ea-8925-3343e07923a9.png)

![image](https://user-images.githubusercontent.com/3796984/92259519-30a54580-eecf-11ea-9770-d396594552ed.png)

I have added @using AntDesign (and for MatBlazor) in the _Imports.razor file and Program.cs has the correct service setup:

`builder.Services.AddAntDesign();`

I have restarted Visual Studio and re-booted, but nothing seems to fix this issue.

Any ideas what is wrong with the tooling here?

Many thanks

**Comment by sjbthfc2** [comment]
Any development with this issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you see the same errors when you build in the command line (`dotnet build`) ?
