### ISSUE TITLE
Cannot navigate to the symbol under the caret.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25633]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1173358/cannot-navigate-to-the-symbol-under-the-caret-6.html)._

---
[severity:I'm frustrated, but able to complete my work]
I recently started getting this error message.  I'm using Blazor WebAssembly.  I don't know why this problem is now occurring but it's difficult not being able to quickly find where variables are defined.

I'm sure this will be fixed in some update but if there is a work-a-round for now, that would really help.

Thanks,
Bob

---
#### Feedback Bot on 9/4/2020, 01:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We tried this out but couldn't repro this issue and are able to go to definition for a similar variable without hitting any issues: ![GoToDef](https://user-images.githubusercontent.com/14852843/92289498-883eb380-eec5-11ea-8176-a08fd211e00d.gif)
Please share a small repro project so we can try out using that.
