### ISSUE TITLE
Update the ASP.NET Core hosted Blazor WebAssembly template to use _Host.cshtml

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25631]
Currently the ASP.NET Core hosted Blazor WebAssembly uses a static index.html file. It would be more flexible to instead use a *_Host.cshtml* file like the Blazor Server template does. The root `App` component could then be setup using the component tag helper with `RenderMode.WebAssembly`. This would make it easier for the user to turn on prerendering if that's what they want to do. Note that I'm **not** proposing that we enable prerendering by default, as that adds a bunch of additional complexity for the user.

**Comment by javiercn** [comment]
How do you want this to work with PWAs?

**Comment by danroth27** [comment]
From discussing with Javier: We would potentially need to generate hashes for a couple of things on the fly, since the content of the "index.html" can now be dynamic.

**Comment by mkArtakMSFT** [comment]
Closing as this is not needed any more.
