### ISSUE TITLE
Project to help create F# lang support on razor pages

### ISSUE THREAD

**Issue by sksallaj82** [dotnet/aspnetcore#25632]
I tried to find some support to see if this was even possible. This was related to an [issue 16306](https://github.com/dotnet/aspnetcore/issues/16306) from two years ago and I'm interested to know if anything changed since then.

I saw someone got pretty close 11 years ago creating fshtml pages in razor, but its crude. Perhaps we could look into how it was done and port some of that logic into this project. I'm pretty sure there are more than enough contributors in the F# community than would love to see this aspect come to fruition. This might also benefit the [Bolero ](https://fsbolero.io)project as well, since most of the logic in F# are done separately in behind the scenes on a separate file, rather than using the powerful connection of adding HTML and code on the same razor file.

https://www.infoq.com/news/2011/01/Razor-Extensions/
https://github.com/dahlbyk/FSRazor

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We do not have plans to support this.
