### ISSUE TITLE
Issue with binding to an html select

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25634]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170058/issue-with-binding-to-an-html-select.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:16.7.2 and 16.8 Preview 1]
Hey everyone,

I am facing an issue with the latest VS Preview 2.1. I have the following code:

```
@if (Position.PositionBenötigtSeriennummer)
        {
            <div class="col-12">
                <div class="widget">
                    <div class="widget-head">
                        <div class="icon"><i class="fa fa-barcode"></i></div>
                        <h3>Seriennummer</h3>
                    </div>
                    <div class="widget-body">
                        <select @ref="seriennummerSelect" class="form-control" @bind="Seriennummer">
                            <option value="">Seriennummer auswählen...</option>
                            @foreach (var seriennummer in Seriennummern)
                            {
                                <option value="@seriennummer">@seriennummer</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
        }
```

My code behind file:

```
private ElementReference seriennummerSelect;
jsRuntime.InvokeVoidAsync("blazorHelpers.selectDefaultIndex", seriennummerSelect); // In a button click event
```

Now I am getting the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'string' to 'in Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame'	WK5-Blazor	F:\wk5-programs\WK5-Blazor\obj\Debug\netcoreapp3.1\Razor\Pages\Lagerregal\ArtikelAnsicht.razor.g.cs	317	Active

If I try to compile my solution in the latest non preview version, everything works fine.

---
#### Feedback Bot on 9/1/2020, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### marvingross solved on 9/1/2020, 07:20 AM, 0 votes: 

<p>Just found the solution on Github.</p><p>https://github.com/dotnet/aspnetcore/issues/25267</p><p>Looks like it will be fixed in .NET Core 5.0 RC1.The workaround with the global.json file works.</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and glad that you've found #25267 is resolving your issue.
