### ISSUE TITLE
css isolation works in blazor client, but not blazor server

### ISSUE THREAD

**Issue by ysmoradi** [dotnet/aspnetcore#25645]
### Describe the bug

Blazor Client (Web assembly) is able to fetch ["_framework/scoped.styles.css"](https://github.com/ysmoradi/BlazorDualMode/blob/master/BlazorDualMode/Web/Pages/_Host.cshtml#L20), but Blazor server's fetch request for "_framework/scoped.styles.css" results into 404 not found

### To Reproduce

I've a dual mode blazor project located at https://github.com/ysmoradi/BlazorDualMode
If I use BlazorClient by setting
```xml
<BlazorMode>Client</BlazorMode>
```
in [Directory.build.props](https://github.com/ysmoradi/BlazorDualMode/blob/master/Directory.build.props#L4), css isolation works properly. (Just set BlazorDualMode.Api and hit Ctrl+F5)

But after i switch to blazor server by setting
```xml
<BlazorMode>Server</BlazorMode>
```
in [Directory.build.props](https://github.com/ysmoradi/BlazorDualMode/blob/master/Directory.build.props#L4) (Needs VisualStudio restart + Set BlazorDualMode.Web as startup project and hit Ctrl+F5), browser's request to fetch
```xml
<link href="_framework/scoped.styles.css" rel="stylesheet" />
```
results into 404 not found )":

### Exceptions (if any)
N/A

### Further technical details
- ASP.NET Core version 5 Prev 8
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.400 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 16.8.2 Enterprise

**Comment by javiercn** [comment]
@ysmoradi thanks for contacting us.

The url for the scoped styles in server-side Blazor is `_content/project/scoped.styles.css` this is something we've changed as part of our RC2 release to match Blazor webassembly, so it'll always be at `/project.styles.css` after RC2, unless you use a different `StaticWebAssetBasePath` in which case, that will be respected.

**Comment by ysmoradi** [comment]
Thanks
I wasn't able to make it work with any of followings:
```html
    <link href="_content/project/scoped.styles.css" rel="stylesheet" />
    <link href="_content/BlazorDualMode.Web/scoped.styles.css" rel="stylesheet" />
    <link href="_content/project/project.styles.css" rel="stylesheet" />
    <link href="_content/BlazorDualMode.Web/project.styles.css" rel="stylesheet" />
```
)":

**Comment by javiercn** [comment]
@ysmoradi sorry, It should be `<link href="_content/BlazorDualMode.Web/_framework/scoped.styles.css" rel="stylesheet" />`. If you are unsure, create a new server-side Blazor application and check the link tag.
