### ISSUE TITLE
RequestObjectURLAsync() as BrowserFileExtensions

### ISSUE THREAD

**Issue by barahonajm** [dotnet/aspnetcore#25641]
### Description

`<InputFile>` is looking good!

Primary I would like to request a way to get a `ObjectURL` it will allow as to immediately display the content as a `<img>` or even display a full PDF within a `<iframe>` (In case of blazor server this can be a way to avoid stream all the data to the server for certain scenarios)

https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

### Describe the solution you'd like

I believe it should be a method on `BrowserFileExtensions`

```csharp
public static ValueTask<string> RequestObjectURLAsync(this IBrowserFile browserFile);
```

### Additional
Although it may be too early to request this as it is still a work in progress, but I would like to callout the idea of making the BrowserFile independed of the `<InputFile>`. I was envisioning something that looks complicated to implement and possible not worth it but I was wondering if this would be possible someday:

**Example 1:**

```csharp
return await _jsRuntime.InvokeAsync<string>("URL.createObjectURL", browserFile);
```
(👆 I know this can be resolved by adding RequestObjectURLAsync to BrowserFiles)

**Example 2:**
Interact with `IndexingDB API` like this

```csharp
return await _jsRuntime.InvokeVoidAsync("storeFile", browserFile);
```

```javascript
function storeFile(blob)
  let objectStore = db.transaction(['files_to_make_loads_faster'], 'readwrite').objectStore('files_to_make_loads_faster');

  let record = {
    file: blob,
  }

  let request = objectStore.add(record).
```
(☝ And this can also be resolved by providing some utilities like the "ProtectedLocalStorage")

If `BrowserFile` can be made in such a way it can easily be passed in any place where a `File` is received it can potentially become a workaround for the scenarios above and possible others while we wait for Native Implementations

**Comment by barahonajm** [comment]
🙀 `IJSObjectReference` is magic!

I think it may be enough to add `JSObjectReference FileReference` into `IBrowserFile`, with that we can easily call things like this:

```csharp
string returnValue = await JSRuntime.InvokeAsync<string>("URL.createObjectURL", jsReference);
```

👆 That works perfectly and looks flexible enough to me (Just my thoughts)

**Comment by TanayParikh** [comment]
Hi @barahonajm, thanks for contacting us. I believe this is the same as https://github.com/dotnet/aspnetcore/issues/27983, I'm closing this out as a duplicate as that issue has additional community engagement.
