### ISSUE TITLE
SignalR randomly times out looking for blazorpack implementation when running on IIS

### ISSUE THREAD

**Issue by FraktalInverTer** [dotnet/aspnetcore#25658]
### Describe the bug
I have a razor view with a blazor component loaded with Html.RenderComponentAsync. On first load, the blazor component loads, but refreshes of the page randomly leads to SignalR timeout and Handshake was canceled.

_This problem only occurs for me when published to IIS, not during debug._

Looking at the debug logs I notice that a working call and a crashing call behave the same up until the point where the blazorpack implementation is found. A bad call never gets to that point.

Working call:
```
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[FoundImplementationForProtocol] @ 2020-09-05T23:54:01.2850138+02:00
      => RequestPath:/_blazor RequestId:80000058-0000-9400-b63f-84710c7967bb, SpanId:|2c15415b-40a7170dc6fde902., TraceId:2c15415b-40a7170dc6fde902, ParentId: => TransportConnectionId:3mX6VRGgvWr7iAPPYUvg4A
      Found protocol implementation for requested protocol: blazorpack.
```

Bad call:
```
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[ResumingConnection] @ 2020-09-05T23:58:31.0529793+02:00
      => RequestPath:/_blazor RequestId:8000004e-0004-e000-b63f-84710c7967bb, SpanId:|2c15419a-40a7170dc6fde902., TraceId:2c15419a-40a7170dc6fde902, ParentId: => TransportConnectionId:lS4jTAwArv6y8R0jA3j7Vw
      Resuming existing connection.
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[CleanupCycleStart] @ 2020-09-05T23:58:39.1195883+02:00
      Starting HttpMessageHandler cleanup cycle with 1 items
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[CleanupCycleEnd] @ 2020-09-05T23:58:39.1196205+02:00
      Ending HttpMessageHandler cleanup cycle after 0.0011ms - processed: 0 items - remaining: 1 items
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[HandshakeCanceled] @ 2020-09-05T23:58:46.0575506+02:00
      => RequestPath:/_blazor RequestId:80000024-0002-a700-b63f-84710c7967bb, SpanId:|2c154199-40a7170dc6fde902., TraceId:2c154199-40a7170dc6fde902, ParentId: => TransportConnectionId:lS4jTAwArv6y8R0jA3j7Vw
      Handshake was canceled.
```

### To Reproduce
Simple repro uploaded here: https://github.com/FraktalInverTer/BlazorTimeoutSignalR

Publish solution to IIS (this is boilerplate startup project with identity and login page scaffolded so you might have to setup identity server certificate and identity connection for your machine).
Click login button. 
The Login page should display a blazor component at the top of the page with the text: "Blazor is working great!"
Refresh page a few times after eachother. Suddenly the page gets stuck and after a long timeout the handshake is cancelled and refreshes of the page will not show the "Blazor is working great!" blazor component until it randomly starts working again.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/6247762/92322188-1171f980-f030-11ea-8c85-34351f0c6bee.png)

![image](https://user-images.githubusercontent.com/6247762/92322209-2babd780-f030-11ea-9761-b53853e79b2e.png)

Debug logs from working call and crashing call attached:

[workingcall.txt](https://github.com/dotnet/aspnetcore/files/5179291/workingcall.txt)

[crashingcall.txt](https://github.com/dotnet/aspnetcore/files/5179293/crashingcall.txt)

### Further technical details
- ASP.NET Core version 3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Enterprise 2019
Version 16.6.5

**Comment by FraktalInverTer** [comment]
Experimented a bit more and noticed that if I comment out the service worker's fetch event handler like so:

`//self.addEventListener('fetch', event => event.respondWith(onFetch(event)));`

The blazor component renders stable every time.

I thought maybe it was related to caching and played around with disabling caching for calls to the _blazor endpoint, but even if I replace the code of the fetch event handler with a direct fetch, the unstability remains and blazor crashes randomly.

```
async function onFetch(event) {
    return fetch(event.request);
}
```

I'm now thinking that it might not be a bug in Blazor, maybe it's some weird effect that intercepting fetch calls with service workers has on SignalR. I can't tell though. Anyone knows what is going on? Bug or is the service worker interceptor just incompatible with SignalR?

**Comment by BrennanConroy** [comment]
Looks like you figured out what was wrong. Closing as resolved.
