### ISSUE TITLE
Illogical user validation in Microsoft.AspNetCore.Identity.UI

### ISSUE THREAD

**Issue by fjallemark** [dotnet/aspnetcore#25659]
I have just created a default application with Blazor Wasm and Individual Users authentication with Entity Framework Core and Sql Server.

I find it illogical that the UI request an **Email address** but validate it against **UserName** in the database. I changed the UserName in the database to a real name but left the Email unchanged and then login failed when I used the email-address in the Email-field on the login-page.

When you register, the entered email-address in Registration Page is stored both as UserName and Email, which is ok. But I find it useful to change the username to anything, because this is the *displayed name* while the Email-address is an unique identification of the user. Even if the user changes the Email-address, they are required to confirm it before logging in again.

**Comment by blowdart** [comment]
Yes, this does keep arising. The templates, for simplicity, treat username and email as almost the same, but I'm afraid it's not going to change any time soon as no feature work is currently planned for identity.
