### ISSUE TITLE
where is the source code of Libuv ?

### ISSUE THREAD

**Issue by sunny868** [dotnet/aspnetcore#25665]
Now ,we are porting coreclr to arch mips64 https://github.com/gsvm/coreclr ，but I found there is no RID linux-mips in Libuv package that be needed in dotnet/aspnetcore. and I want to suport it for mips64 but I dont now where is the source code of Libuv package. so can you give me a link of source code or support it for mips64?

**Comment by BrennanConroy** [comment]
Our Libuv transport is no longer being worked on and is obsolete in 5.0 https://github.com/aspnet/Announcements/issues/424

The native build is located at https://github.com/aspnet/libuv-build if you want to fork it and make modifications.

**Comment by sunny868** [comment]
Thanks.

**Comment by sunny868** [comment]
we are porting .NET CORE for mips64 architecture . https://github.com/gsvm/coreclr
aspnetcore need mips64 libuv.so , so I submitted a PR at  https://github.com/aspnet/libuv-build , I hope it can be merged and update Libuv.nupkg to nuget.org for this.
Thanks

**Comment by BrennanConroy** [comment]
> no longer being worked on and is obsolete in 5.0

It's very unlikely we will merge that PR.

> fork it and make modifications

Like I said, you can fork the code base and make your own package.

cc @Pilchie @halter73

**Comment by sunny868** [comment]
oh, I see

**Comment by Pilchie** [comment]
@sunny868 you said:

> aspnetcore need mips64 libuv.so

Do you actually need that, or does the sockets transport work already?  If the sockets transport works, I would suggest just letting people use that.  That's what we are doing for Windows ARM64, instead of producing a Windows ARM64 builds of libuv.

**Comment by sunny868** [comment]
Im not very sure. After I builed aspnetcore v3.1.7 by
 `./build.sh --configuration Debug /p:DisableCrossgen=true /p:PortableBuild=true /p:SkipTests=true`
there are many libuv.so for arm64 and x64 but not mips64 at artifacts/ path

./artifacts/bin/PlaintextApp/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/PlaintextApp/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/PlaintextApp/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/PlaintextApp/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/Libuv.FunctionalTests/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/Libuv.FunctionalTests/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/Libuv.FunctionalTests/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/Libuv.FunctionalTests/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/SystemdTestApp/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/SystemdTestApp/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/SystemdTestApp/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/SystemdTestApp/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/Libuv.BindTests/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/Libuv.BindTests/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/Libuv.BindTests/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/Libuv.BindTests/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Tests/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Tests/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Tests/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Tests/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/Kestrel.SampleApp/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/Kestrel.SampleApp/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/Kestrel.SampleApp/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/Kestrel.SampleApp/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Performance/Debug/netcoreapp3.1/runtimes/linux-arm64/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Performance/Debug/netcoreapp3.1/runtimes/linux-x64/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Performance/Debug/netcoreapp3.1/runtimes/linux-armel/native/libuv.so
./artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Performance/Debug/netcoreapp3.1/runtimes/linux-arm/native/libuv.so

**Comment by Pilchie** [comment]
Okay, I would ignore that for now.  That should only be necessary if someone uses the now obsolete `UseLibuv()` extension method.   Otherwise, the sockets transport is the default.
