### ISSUE TITLE
Default HTML form submit prevented

### ISSUE THREAD

**Issue by 7timus** [dotnet/aspnetcore#25666]
https://github.com/dotnet/aspnetcore/blob/a190fd34854542266956b1af980c19afacb95feb/src/Components/Web/src/Forms/EditForm.cs#L127

When added default for submit event is prevented and HTML form action not executed.

Maybe you can change "**builder.AddMultipleAttributes(1, AdditionalAttributes)**" to be set as last one, so we can override default attributes?

**Comment by javiercn** [comment]
@7timus thanks for contacting us.

Can you clarify what you are trying to achieve? Why don't you want to use the OnSubmit event handler method?

**Comment by 7timus** [comment]
Sorry, missed notification. 
I was thinking of sending POST request from client using html form to  avoid using HttpClient and have HTTP context on backend (Server side hosted blazor). And overwrite default HTML form onsubmit event to avoid redirect. 
By moving little lower: "**builder.AddMultipleAttributes(1, AdditionalAttributes)**" there would be an option for users to overwrite your provided OnSubmit attribute.
