### ISSUE TITLE
GET request to POST Action with overload causes loop/high cpu usage

### ISSUE THREAD

**Issue by devel112** [dotnet/aspnetcore#25667]
### Describe the bug
GET request to POST Action with overload causes loop/high cpu usage

### To Reproduce
public class ProductsController : Controller {

public IQueryable<Product> GetProducts(DbContext db, param) { ... }

[HttpPost]
	[AllowAnonymous]
	public async Task<ActionResult<GetProductsDto>> GetProducts([FromBody] GetProductsParametersDto param, CancellationToken cancellationToken){ ... }

}

### Further technical details
- ASP.NET Core version: 3.1.7
- Include the output of `dotnet --info`
- Windows 10 and Windows server

**Comment by javiercn** [comment]
@devel112 thanks for contacting us.

In order for us to investigate this issue, could you please provide a minimalistic repro project that illustrates the problem?

**Comment by devel112** [comment]
Sorry - problem with rate limiter middleware - note to self: ALWAYS provide repro
