### ISSUE TITLE
In React/Angular templates, vary page title to match content

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#25676]
Currently the SPA templates have a fixed `<title>` that doesn't change as you navigate around. There are features in the corresponding SPA frameworks, or at least 3rd-party packages, that can change the title dynamically.

This was originally reported at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163086

**Comment by mkArtakMSFT** [comment]
Closing as low priority.
