### ISSUE TITLE
Get IJSObjectReference from ElementReference

### ISSUE THREAD

**Issue by barahonajm** [dotnet/aspnetcore#25685]
### Description

It will be awesome if we can get a `IJSObjectReference` from an `ElementReference` so we can easily start calling js methods of the html tags like this:

```razor
<main @ref="MainElement">

</main>

@code
{
    private ElementReference MainElement { get; set; }
    private async Task SomeAsyncMethod()
    {
        List<string> attributes = await MainElement.InvokeAsync<List<string>>("getAttributeNames")
    }
}
```

### Additional context
There is a verbose workaround for (at least from what i know):

Have a .js file with the following code
```javascript
export function getJSObjectReference(elementReference) {
    return elementReference;
}
```

and use that js file like follow to get a `IJSObjectReference`

```razor
<main @ref="MainElement">

</main>

@code
{
    private ElementReference MainElement { get; set; }
    private async Task SomeAsyncMethod()
    {
        IJSObjectReference module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./<yourjsfilename>");
        IJSObjectReference mainElementObject = await module.InvokeAsync<IJSObjectReference>("getJSObjectReference", MainElement);

        List<string> attributes = await mainElementObject.InvokeAsync<List<string>>("getAttributeNames")

       //dispose
    }
}
```

**Comment by javiercn** [comment]
@barahonajm thanks for contacting us.

I'm not certain that's something we want to enable, since it will encourage all sorts of DOM queries/manipulations that can result in:
* Code with bad performance.
* Code that pierces the Blazor abstraction and breaks the DOM model it has.

**Comment by barahonajm** [comment]
Yes, totally agree on the risks, I am fine on not having this now as it is not too complicated to get one, plus I only had the need of this a couple of times.

But I will not lie `IJSObjectReference` it's a very convenient way of interact with, maybe we can have an implementation based on `ElementReference` so we can avoid memory consumption (just throwing ideas)

**Comment by javiercn** [comment]
Memory consumption is not the issue here, the granularity of the invocations is what can cause bad performance issues. People can naively start taking JSObjectReferences and all the small DOM api methods that are thought/designed with the idea of being run "inline" not across the network.

The result is an app you think it performs well locally only to find out when you deploy it that it behaves poorly.

**Comment by barahonajm** [comment]
Got it, I was thinking only on webassembly when I request this (where I belive calls are cheap) but your are completely right. Thanks for the quick response and explanation.
