### ISSUE TITLE
Ability to compose view components from invoke code 

### ISSUE THREAD

**Issue by brgrz** [dotnet/aspnetcore#25687]
### Is your feature request related to a problem? Please describe.

I am trying to compose view components in code. I might have one generic component and multiple specific components each of which does some specific prep work and calls the Invoke() of the generic component which does the rendering.

Unfortunately it is not working at all. 

I know we can compose in markup but that requires view models at all intermediate levels. The solution I'm looking for works through method calls with parameters which is more convenient. See the example below

### Describe the solution you'd like

**Provide a mechanism to call/handover the execution from one view component to another.**

```
public class ComponentA : ViewComponent
{
	public async Task<IViewComponentResult> InvokeAsync(...)
	{
		// ... do some prep work

		// hand over to ComponentB
		return await new ComponentB().InvokeAsync(...);     // doesn't work

		// also tried this but obviously won't work because the return type is different
		var helper = new DefaultViewComponentHelper(
		  sp.GetRequiredService<IViewComponentDescriptorCollectionProvider>(),
		  HtmlEncoder.Default,
		  sp.GetRequiredService<IViewComponentSelector>(),
		  sp.GetRequiredService<IViewComponentInvokerFactory>(),
		  sp.GetRequiredService<IViewBufferScope>());

		return await helper.InvokeAsync<ComponentB>(...);	// return type is IHtmlContent

	}
}

public class ComponentB : ViewComponent
{
	public async Task<IViewComponentResult> InvokeAsync(...)
	{
		// ... prepare the viewmodel

		// render
		return View(vm);

	}
}
```

### Additional context

Composition in Razor markup using the <vc> tag helpers does work but it requires additional overhead in terms of mutiple view model classes (or one huge do-it-all class) to pass data and parameters that are relevant at multiple levels in composition hierarchy.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please share more details about what you expect to work and how it doesn't?

**Comment by brgrz** [comment]
I'm not sure I can. The example code above should give you clue what I'm trying to achieve. Basically I'd like to handover/forward processing from one Invoke/InvokeAsync within one component to a Invoke/InvokeAsync in another component, via code that is.

If I do this in ComponentA

return await new ComponentB().InvokeAsync(...);

it does not work. It just proceeds with rendering the view for ComponentA instead of switching over to ComponentB.

Now I don't know whether this should already work using the above code (meaning, something else is wrong in my project) or do we need a completely new mechanism to enable this behaviour.

**Comment by pranavkm** [comment]
> it does not work. It just proceeds with rendering the view for ComponentA instead of switching over to ComponentB.

That would be C# code calling C# code. I'm not sure why that wouldn't work. I can understand if it throws because none of the services on `ComponentB` are initialized, but that does not appear to be the case. You could use `IViewComponentHelper` in your component if you want to exactly simulate how a view component invocation works inside of your view, but it's really no different from invoking it the way you did here.

**Comment by brgrz** [comment]
I'll try to provide sample code within a clean project hopefully over the weekend.

I have a couple more suggestions regarding view components, their composition, view finding/rendering but would only discuss them if there's planned investment from MS team in this area in the foresable future?
