### ISSUE TITLE
get access to CSS Isolation identifier 

### ISSUE THREAD

**Issue by huunab** [dotnet/aspnetcore#25683]
### Description
Although we can access the css isolation identifier by filtering with the prefix 'b-' on any `ElementReference` of the component, it will be great if we can have access to the full current identifier for the component in an easy way.

### Describe the solution you'd like
It can be a property on the Component

```csharp
public string ScopeId { get; set; }
```

### Additional context
The scoped id will allow us to filter (accurately) the css rules specific to the component in use.

**Comment by javiercn** [comment]
@barahonajm thanks for contacting us.

What do you want to use that for?

Note that we intentionally strived away from a design that involved any type of runtime support/cost.

**Comment by barahonajm** [comment]
I see, currently I am using this for two things:

- I am getting all the `cssrule` associated with the component by the scope id
- I am adding a new scoped `cssrule` dymically full of css variables and I need it to be scoped so I need the ID

It's not too hard to obtain the ID filtering by the prefix `b-` but I don't know how lileky is to have another attribute with the same prefix generated by the user for its own use.

If having the scopeid is not possible maybe changing the prefix to reduce the posibility of coincidences will help

**Comment by javiercn** [comment]
Several things:
* You can define the "scope identifier" to use for a given component at build time via MSBuild.
* You can grab the info about which scope belongs to which file and generate a build artifact you can use at runtime.

> * I am adding a new `cssrule` dymically full of css variables and I need it to be scoped so I need the scope ID

Not sure what this means, but you could create an empty rule on the CSS file associated with the component and then override that rule?

That said, seems like what you are trying to do is pretty advanced. I'm not sure we would do anything about it unless we have a clear set of scenarios we think are valid and we hear enough feedback about it.

**Comment by barahonajm** [comment]
Well in escense what I am doing is a nuget package that let's you interact with the scoped css is the same way `CSSOM` let's you do, altought the most important feature will be to bind css variables into c# variables so it is easy to build highly personalized UI with less code, something similar to what "Fast.desing" do using the power of css variables.

By the way bind css variables with c# variables could be a good feature for blazor 😊😊

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @barahonajm.
For now we recommend to adhere to the mechanism you use currently.

**Comment by TanayParikh** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
