### ISSUE TITLE
FileNotFoundException using lazy loading

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25692]
I'm getting a transient `FileNotFoundException` when using lazy loading.

Repro steps
- Install .NET 5 RC1 SDK: 5.0.100-rc.1.20452.10
- Clone https://github.com/danroth27/BlazorNet5Samples and check out the [lazy-loading](https://github.com/danroth27/BlazorNet5Samples/tree/lazy-loading) branch
- Run the app
- Click on the lazy loading tab
- Toggle the WebAssembly switch to load the app on WebAssembly

Expect result:
- Page correctly loads on WebAssembly

Actual result:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'MyComponents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'MyComponents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'MyComponents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by captainsafia** [comment]
Dan and I sorted this out. The problem was in the if-statement that evaluated whether or not assemblies should be loaded at a certain route.

**Comment by danroth27** [comment]
Thanks @captainsafia for helping debug my code! :laugh:
