### ISSUE TITLE
[Blazor] Missing EventCallback.Ivoke method?

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#25696]
Hi,

I have a somewhat complex UI scenario that deals with nested components that need to communicate with each other. Some of the components are reliant on 3rd party components with whatever limitations they have, so the most practical implementation of the communication mechanism is to create a service that the components subscribe to in order to invoke/handle various events.

Herein lies a potential problem. One of the components needs to handle an event triggered by the service and update a value that is bound to its parent component. My understanding of the framework is to create EventCallback that the child component can then invoke - but there appears to be only asynchronous option to raise the callback. As you can see in my code snippet, I am forced to declare my custom event handler as ```async``` and then ```await``` the EventCallback invocation - this may or may not be a problem. My app runs fine, but I'm not sure if this constitutes some sort of an anti-pattern. General guidance is to declare ```async void``` only on top-level event handlers, which is not my case.

Why not have a synchronous option to invoke EventCallback? All I need to do is update a simple string property.

Thank you!

```
[Parameter]
public string Value { get; set; }

[Parameter]
public EventCallback<string> ValueChanged { get; set; }

private async void MyService_OnSomethingChanged(IEnumerable<string> xyz)
{
    ...
    await ValueChanged.InvokeAsync(Value);
    StateHasChanged();
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is by design as we don't want to introduce blocking calls in customer apps.
What you've got is correct and that's what we recommend.
If you don't care about the event invocation result, you can absolutely fire and forget the call without awaiting it.
