### ISSUE TITLE
ProtectedBrowserStorage feature moved to ASP.NET Core shared framework

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#25691]
As part of the 5.0-rc2 release, the `ProtectedBrowserStorage` feature has been moved to the ASP.NET Core shared framework. In 5.0-preview8, the feature was available as a part of the Microsoft.AspNetCore.Components.Web.Extensions package but was only usable in Blazor Server. In 5.0-rc1, the feature was available as part of the Microsoft.AspNetCore.Components.ProtectedBrowserStorage package which references the Microsoft.AspNetCore.App shared framework. As part of 5.0-rc2, a package reference is no longer needed to reference and use the feature.

## Instructions for upgrading from preview8

* Remove the `Microsoft.AspNetCore.Components.Web.Extensions` package reference 
* Replace the `Microsoft.AspNetCore.Components.Web.Extensions` using with `Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage`
* Remove the call to `AddProtectedBrowserStorage` from your Startup.

## Instructions for upgrading from rc1

* Remove the `Microsoft.AspNetCore.Components.ProtectedBrowserStorage` package reference 
* Replace the `Microsoft.AspNetCore.Components.ProtectedBrowserStorage` using with `Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage`
* Remove the call to `AddProtectedBrowserStorage` from your Startup.

**Comment by boukenka** [comment]
@pranavkm I think you mean "_but was only usable in ~~Blazor WebAssembly~~ Blazor Server apps_". Right ? (According to https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-8)

**Comment by J-Vin** [comment]
Wow! There is so much going on with this, I cannot tell what is what. Bless y'all for dealing with all you do. I wish I could blink and make it easier...
