### ISSUE TITLE
Blazor WASM PWA built on net5.0 preview 8 not generating service-worker-assets.js

### ISSUE THREAD

**Issue by houstonhaynes** [dotnet/aspnetcore#25700]
### Describe the bug
When attempting to build a Blazor WASM client using net5.0 preview 8 \obj\Debug\net5.0\browser-wasm\service-worker-assets.js is not being built

### To Reproduce
See repo

https://github.com/houstonhaynes/BlazorError_dotnet5

### Exceptions (if any)
Error	MSB3954	Failed to compute hash for file 'obj\Debug\net5.0\browser-wasm\service-worker-assets.js' because it does not exist or is inaccessible.	SPA1.Client	C:\Users\h3tec\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\5.0.0-preview.6.20312.15\targets\ServiceWorkerAssetsManifest.targets	59	

### Further technical details
- ASP.NET Core version 5.0 preview 8
- VS Community Version 16.8.0 Preview 2.1

**Comment by javiercn** [comment]
@houstonhaynes thanks for contacting us.

Can you try with the nightly builds to see if this is still an issue for you? The build pipeline has undergone significant changes and it might have been fixed in a later preview.

**Comment by houstonhaynes** [comment]
Will do. I'll report findings after updating and rebuilding. 

I noticed the csproj forces the specific build number after wildcarding at 8(*) -- which strikes me as a bit high-touch for these scenarios.

Would be nice if the wildcarfing stayed in place.

**Comment by houstonhaynes** [comment]
@javiercn I'm pulling the installer from here 
![image](https://user-images.githubusercontent.com/8174976/92524880-b1b65280-f1d7-11ea-804c-d885ac98de83.png)

Yielding this installer : dotnet-sdk-5.0.100-rc.2.20458.7-win-x64\

and getting this error

`NETSDK1112	The runtime pack for Microsoft.NETCore.App.Runtime.browser-wasm was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'browser-wasm'.	SPA1.Client	C:\Program Files\dotnet\sdk\5.0.100-rc.2.20458.7\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	
`
which runtime should I be using? what am I mising? I have to admit it's been years since I've dabbled with daily builds in .NET so I plead no lo contedre if I missed a step.

**Comment by pranavkm** [comment]
@houstonhaynes removing the WebAssembly.Build package allows the project to build using the preview8 SDK. There's more juggling involved when migrating to the rc1 SDK that we will include as part of release notes. Until then, I'll recommend staying with a publicly released SDK.

**Comment by houstonhaynes** [comment]
> @houstonhaynes removing the WebAssembly.Build package allows the project to build using the preview8 SDK. There's more juggling involved when migrating to the rc1 SDK that we will include as part of release notes. Until then, I'll recommend staying with a publicly released SDK.

I'm actually not certain where this contradicts @javiercn - as it's 1) not clear on what I *should* do, only what I should *not* do... and 2) shows no observable difference when the .Build reference is removed.

Care to try again?  Maybe a "Hey here's the canonical list of refs you *should* use" because all I have found out so far is that anything I've tried in terms of documentation is wrong and the "help" here has been marginal at best. 

Thanks.

**Comment by houstonhaynes** [comment]
Why did I bother putting the project up on GitHub so that the responses here clearly haven't actually gotten the thing to build?

Don't just throw rocks at the window, guys. Take two minutes and show me what to *actually* do to make it work.

**Comment by pranavkm** [comment]
For our preview releases, we use our release notes to document migration guides. For e.g. if you look at our preview7 release notes - https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-7/#upgrade-existing-blazor-webassembly-projects it tells you to remove the Build package. 

I also sent a PR to your repo https://github.com/houstonhaynes/BlazorError_dotnet5/pull/1 after verifying that removing the package actually causes the project to build and run.

**Comment by houstonhaynes** [comment]
Still doesn't build. 

<sarcasm>Thanks for all of the super helpful advice.</sarcasm>

![image](https://user-images.githubusercontent.com/8174976/92664634-59578180-f2b9-11ea-9e98-067a71c0139f.png)

**Comment by houstonhaynes** [comment]
Final note: it's poor form to close someone's issue when the original author has not confirmed the fix. 

Check that into your process repo...

**Comment by szalapski** [comment]
I amhaving a similar issue, but my error is `C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(379,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'. `  Not sure if it is related.  Here is a link in case it helps: https://stackoverflow.com/questions/63993294/there-was-no-runtime-pack-for-microsoft-aspnetcore-app-available-for-the-specifi
