### ISSUE TITLE
Analyzers should be invoked only in a single phase when compiling Razor projects 

### ISSUE THREAD

**Issue by mavasani** [dotnet/aspnetcore#25703]
@pranavkm - should we move this aspnetcore to adjust the targets?

_Originally posted by @Pilchie in https://github.com/dotnet/roslyn/issues/47350#issuecomment-687458061_

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn/issues/47350#issuecomment-687398014 for details

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of #25365
