### ISSUE TITLE
Css Isolation for Asp.Net Core Web Application for .cshtml files

### ISSUE THREAD

**Issue by tanekim77** [dotnet/aspnetcore#25713]
CSS isolation feature has been now implemented in .net 5 preview 8 for Blazor, and I confirmed it's working in Blazor.

However, it seems that css isolation feature is not working in traditional Asp.Net Core Web Application.
Is this feature being planned for the traditional Asp.Net Core Web Application?
If not, it would be great if it will be planned.

For example, if there is a Login.cshtml, and if I create Login.cshtml.css, I would like the content of Login.cshtml.css to be automatically injected into <style> portion of Login.cshtml.

**Comment by Acmion** [comment]
You can use Blazor Server in an ASP.NET Core Web App to create statically rendered HTML components. I'd imagine that the component CSS would be scoped with this configuration.

This blog post touches the matter:
[andrewlock.net/dont-replace-your-view-components-with-razor-components/](andrewlock.net/dont-replace-your-view-components-with-razor-components/)
