### ISSUE TITLE
Blazor - ondrop event doesn't return file object

### ISSUE THREAD

**Issue by pandiyarajm93** [dotnet/aspnetcore#25721]
I have bind **@ondrop** event into my **div** element, while drag and drop local image into div, **DragEventArgs** doesn't return **file object** details.

**Razor code**

`<div @ondrop="@OnDrop"></div>`

`
@code{

        internal void OnDrop(DragEventArgs args)

        {

            var files = args.DataTransfer.Files;

        }

}
`

output:

![image](https://user-images.githubusercontent.com/54373337/92388497-fb019600-f134-11ea-8433-c2b6b651a4e1.png)

**_How to get file Info from DragEventArgs?_**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We plan to cover this as part of #18754
