### ISSUE TITLE
Suggested performance improvements for the JSObjectReference API implementation

### ISSUE THREAD

**Issue by JinShil** [dotnet/aspnetcore#25723]
https://github.com/dotnet/aspnetcore/blob/a190fd34854542266956b1af980c19afacb95feb/src/JSInterop/Microsoft.JSInterop/src/JSInProcessObjectReferenceExtensions.cs#L23

I believe there is an important opportunity for a performance improvement here.  If you call `Invoke<object>` it will attempt to serialize the Javascript function's return value only to throw it away.  

It is possible in C#, Javascript, and other languages to call a function and not utilize its return value.  There are many APIs that add return values for the benefit of chaining, but those return values are not always utilized in a single function call.  For example, see [`PIXI.Graphics.LineTo`](http://pixijs.download/release/docs/PIXI.Graphics.html#lineTo).  That implementation returns the `Graphics` object instance to enable chaining.  When creating an API wrapper in C#, that return value will almost never be utilized. 

I tested an alternate implementation with the Pixi JS API to avoid serializing the return value, and it resulted in a 15% performance improvement.

I believe the same optimization can be made for the `InvokeVoidAsync` implementations.

Please note that this also causes problems when the return value contains circular references.  The `InvokeVoid` call will fail trying to serialize the return value, even though the caller has no need for it.

**Comment by javiercn** [comment]
@JinShil thanks for contacting us.

If you can `Invoke<object>` we can't make assumptions at runtime over whether or not you will use the value. At best, we could offer an analyzer that detects these cases and suggest calling InvokeVoidAsync instead.

For InvokeVoid not serializing the return value, there's still the need to return the completion. It obviously have a perf impact if the return value is big and wasteful.

I believe we have a similar issue to this one filed somewhere, but I can't tell for sure.

With all this in mind, I would say that it is important to understand that while you can hold references to JavaScript objects now, our goal is not to enable chatty fine-grained JavaScript interop and that even in the case where you can use JS objects directly, we recommend you carefully plan the JS interop operations in your apps.

From our point of view, it is better to prefer sporadic `coarse JS interop` calls over `frequent granular JS interop calls`, in a similar way as the guidance offered for service-to-service communications.

**Comment by JinShil** [comment]
> If you can `Invoke<object>` we can't make assumptions at runtime over whether or not you will use the value. At best, we could offer an analyzer that detects these cases and suggest calling InvokeVoidAsync instead.
> 
> For InvokeVoid not serializing the return value, there's still the need to return the completion. It obviously have a perf impact if the return value is big and wasteful.

Forgive me if I'm making a false assumption, but I'm specifically referring to the `IJSInProcessObjectReference.InvokeVoid` implementation linked in the first comment.  I don't see why `InvokeVoid` couldn't have a special case implementation that would avoid serializing the return value.  But, maybe I don't understand.

> From our point of view, it is better to prefer sporadic coarse JS interop calls over frequent granular JS interop calls, in a similar way as the guidance offered for service-to-service communications.

I understand, but if we have to do half of our implementation in Javascript, then Blazor is not fulfilling its potential.  Are there no performance optimizations that can be made in C#/Javascript interop so we don't have to always reach for Javascript when we need performance.  Will there be, perhaps, something equivalent to PInvoke in the future?  I was very excited about Blazor and the JSObjectReference API, but my hopes were squashed after I actually tried the implementation.  The performance is really quite bad.  

I also added a few comments at https://github.com/dotnet/aspnetcore/commit/8a2f29bb539497f79ac3ac1f7d8c35efe88e6dce.  Or maybe I should file issues instead.

**Comment by javiercn** [comment]
> Forgive me if I'm making a false assumption, but I'm specifically referring to the `IJSInProcessObjectReference.InvokeVoid` implementation linked in the first comment

The title said JSObjectReference and got me confused.

> I understand, but if we have to do half of our implementation in Javascript, then Blazor is not fulfilling its potential. Are there no performance optimizations that can be made in C#/Javascript interop so we don't have to always reach for Javascript when we need performance.

This mostly depends on the type of application that you are building, however, the goal of Blazor is not to replace JavaScript, but to minimize the need to use it.

Our goal is not to transpile C# to JS, but to author C#/.NET apps within the context of the browser, and that means sometimes you'll need to reach for JavaScript and depending on the type of app you are building the percentage will vary.

For example, if you try to write an app that "renders" on a Canvas element, chances are you'll have to write more JavaScript to handle the canvas interactions more efficiently if you need "ultimate" performance.

There is unlikely to be a more seamless integration in the near future between Blazor (or other platform compiled to wasm) and JS until there are mechanisms available in WASM to do so, like the ability to hold JS object references in WASM and so on and viceversa in a way they can interoperate efficiently at the platform level.

Ultimately, for Blazor it depends on what you are trying to write. If you only care about WASM, you can go as far as using the unmarshalled JS interop, but that will prevent your app/library from working in other contexts (like server-side Blazor) and if you design your library in such way, even if it worked in other contexts, the performance would be bad.

As I said, our goal is not that we replace JavaScript completely, but that you can write most of your application in C# and only require using JavaScript for the types of things that benefit from it, like hot paths in your app that involve many JS calls.

I hope this helps explain or goals and reasoning better.

That said, if we can optimize things on the in process JS runtime, that's always a good thing to do/goal to have.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will track the work in this area as part of #16632
