### ISSUE TITLE
Blazor Standalone WebAssembly project in VS Code doesn't honor applicationUrl in launchSettings.json

### ISSUE THREAD

**Issue by jongio** [dotnet/aspnetcore#25739]
### Describe the bug
I set this in launchSettings.json

```json
"applicationUrl": "https://localhost:1081;http://localhost:1080",
```

Hit F5 in VS Code

The app starts with:
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:1081
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:1080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
```

Browser launches, but it launches to localhost:5001, not :1080

### To Reproduce

1. Change applicationUrl in launchSettings.json to a port other than 5001
2. Hit F5
3. It will try to launch 5001

### Workaround

Put this in launch.json
```
{
    // Use IntelliSense to find out which attributes exist for C# debugging
    // Use hover for the description of the existing attributes
    // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "browser": "edge",
            "url": "http://localhost:1080"
        }
    ]
}
```

> This launches a browser, but the site will not load unless I manually go the page, and breakpoints are not hit.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
```
WebApp$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
Version: 1.49.0-insider (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-09T08:15:09.223Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

azsdke2e
azsdke2e2

**Comment by danroth27** [comment]
@captainsafia

**Comment by captainsafia** [comment]
Tagging this as help wanted for the sprints.

To make this change, you'll need to modify the Razor extension for VS Code in the aspnetcore-tooling repo ([ref](https://github.com/dotnet/aspnetcore-tooling/tree/1d37accabf3a482edf02a3d341b4ac4b04e5e4f4/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug)).

In particular, the change will need to be made in the launch code of the `blazorwasm` debug configuration type at https://github.com/dotnet/aspnetcore-tooling/blob/1d37accabf3a482edf02a3d341b4ac4b04e5e4f4/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts.

We'll need to add some logic that reads the `launchSettings.json` file in the current workspace, fetches the `applicationUrls` fields, and sets the `url` provided to the browser launch type based on this.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
