### ISSUE TITLE
dotnet-watch live browser reload not working in Preview 8

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/aspnetcore#25753]
I recently started a new .NET 5 MVC project and wanted to use `dotnet-watch` and the integrated live reload functionality instead of my middleware component. 

Live Reload works with my middleware component enabled.

So I removed it, and just used `dotnet-watch` to run the application expecting the same behavior without the middleware. However, I see no browser refresh and there's no injected JavaScript code or script link that should be there to handle the live reload refresh code on the client.

I can't find any instructions anywhere on how this is supposed to work. Is this functionality enabled by default or is there some switch (there should be if there's not).  

*updated*

I created another brand new project and ran that immediately after creation and that did kind of worked:

* Live Reload works for Razor Views (MVC in my case)
* Live Reload does not work for: HTML, CSS, JS files

In short it works for a new project, but not for my project (startup code below).

### To Reproduce
Initially I had tried this on the new project as soon as it was created and it didn't work. However, I just retried this by creating a new scratch project and running `dotnet watch run`, and that does seems to work with Live Reload happening **but only for Razor views/pages**, not for other static content as it should.

For reference - here's my startup code - nothing outlandish in there:

```cs
  public void ConfigureServices(IServiceCollection services)
        {
            // Replace StringLocalizers with Db Resource Implementation
            services.AddSingleton(typeof(IStringLocalizerFactory),
                typeof(DbResStringLocalizerFactory));
            services.AddSingleton(typeof(IHtmlLocalizerFactory),
                typeof(DbResHtmlLocalizerFactory));

            services.AddWestwindGlobalization(opt =>
            {
                // the default settings comme from DbResourceConfiguration.json if exists
                // you can override the settings here, the config you create is added
                // to the DI system (DbResourceConfiguration)

                // Resource Mode - from Database (or Resx for serving from Resources)
                opt.ResourceAccessMode = ResourceAccessMode.DbResourceManager;  // .Resx

                // // Make sure the database you connect to exists
                // opt.ConnectionString = "host=.;database=localizations;uid=localizations;pwd=local";

                // Database provider used - Sql Server is the default
                opt.DataProvider = DbResourceProviderTypes.PostgreSql;

                // The table in which resources are stored
                opt.ResourceTableName = "localizations";

                opt.AddMissingResources = false;
                opt.ResxBaseFolder = "~/Properties/";

                // Set up security for Localization Administration form
                opt.ConfigureAuthorizeLocalizationAdministration(actionContext =>
                {
                    // return true or false whether this request is authorized
                    return true;   //actionContext.HttpContext.User.Identity.IsAuthenticated;
                });

            });


            // set up and configure Authentication - make sure to call .UseAuthentication()
            services
                .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)

                .AddCookie(o =>
                {
                    o.LoginPath = "/account/signin";
                    o.LogoutPath = "/account/signout";
                    o.SlidingExpiration = true;
                    o.ExpireTimeSpan = new TimeSpan(30, 0, 0, 0);
                    o.Cookie.Name = "ww_ws";
                });

            // Add Business Objects to ServiceCollection
            var busFactory = new BusinessFactory();
            busFactory.DefaultInitializtion(services);

            services.AddRazorPages();
            services.AddControllersWithViews()
                .AddNewtonsoftJson()
                .AddViewLocalization()
                .AddDataAnnotationsLocalization();

            // this *has to go here* after view localization has been initialized
            // so that Pages can localize - note required even if you're not using
            // the DbResource manager.
            services.AddTransient<IViewLocalizer, DbResViewLocalizer>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                //app.UseExceptionHandler("/Home/Error");
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            var supportedCultures = new[]
            {
                new CultureInfo("en-US"),
                new CultureInfo("en"),
                new CultureInfo("de-DE"),
                new CultureInfo("de")
            };
            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("en-US"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            });

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseStatusCodePages( new StatusCodePagesOptions
            {
                //HandleAsync = (ctx) =>
                //{
                //    if (ctx.HttpContext.Response.StatusCode == 404)
                //    {
                //        throw new HttpRequestException("Page not  found", null, statusCode: System.Net.HttpStatusCode.NotFound);
                //    }

                //    return Task.FromResult(0);
                //}
            });

            app.UseAuthentication();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });
        }
```

I verified with an info request that the application is in fact running Preview 8. There is no `global.json` that overrides the latest SDK usage (AFAIK - would be nice if dotnet-start would actually display the runtime/sdk it's using to launch), but am assuming since dotnet --info shows the latest in use from the web folder, that's what's getting used.

### Expected
To clarify - new project it works, my project it doesn't. However, my project's startup is pretty simple and I can't see what could cause this not to work in my specific application. I would expect this to work with my project as there's nothing in the startup code that should affect external live reload behavior.

Furthermore, even in the project where Live Reload works it doesn't refresh changes in:

* Static HTML pages
* CSS File
* JavaScript files

It seems it only works with Razor Views/Pages which is not quite enough. Support resources should also refresh. 

### Further technical details
- ASP.NET Core .NET 5 P8 
- on Windows 10

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  2.1.514 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by DamianEdwards** [comment]
You mentioned you tried this in a new project from VS. This feature is limited to only `dotnet watch run` right now so launching from VS won't work. Did you try launching the new project from the cmd line with `dotnet watch run`, without any `Startup.cs` changes?

**Comment by RickStrahl** [comment]
Sorry I wasn't clear: I **created** the project in VS, but am **running** from the command line.  FWIW, I have done that before (not with the new one) and added dotnet-watch to `LaunchSettings.json` and that actually worked fine when I did try that.

**Comment by RickStrahl** [comment]
So I just tried this again with a new project and... it works. 

Ok... I have no idea what's different then, because as you can see the project I'm working on has nothing that should affect the loading of text

**Comment by danroth27** [comment]
@pranavkm Can we auto refresh without rebuilding when static content (HTML, CSS, etc) changes?

@mkArtakMSFT We still have a known issue with component specific CSS files (.razor.css), which looks like it may have fallen through the cracks: #25483

**Comment by pranavkm** [comment]
@RickStrahl dotnet-watch currently does not watch static assets which would explain why you would see this behavior. You can [configure it](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1#customize-files-list-to-watch) to additionally watch these files. However that means that it will end up doing a rebuild \ restarting the process. For 6.0, we're going to look at how we could avoid the unnecessary build when all that needs to happen is a browser refresh.

**Comment by RickStrahl** [comment]
I don't even know how to respond to this...

So you're saying you didn't bother to review the use cases of how developers are likely to actually use this feature? And that even though that's [laid out pretty clearly](https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload) in the core component that this concept is based on. As it is now, the feature set in `dotnet watch` is a half measure and will cause me not to bother with it and instead continue to use the middleware, which actually does what the expected and commonly supported by other dev platforms behavior is.

On top of that adding the capability to refresh static content would be isolated in the Socket server (and the file watcher for the extra extensions I suppose) but that's hardly a difficult issue to deal as it merely conditionally needs to decide whether recompile is required. The only sticking point is that it would likely require additional configuration settings.

Speaking of config settings, this feature also needs to be configurable - you need to be able to turn it off or exclude folders/extensions potentially.  But who knows maybe all that is there and hidden, but wait... there's no documentation or even a road map that describes how this is supposed to work within the context of `dotnet watch`.

**Comment by DamianEdwards** [comment]
We fully intend to add support for static files and change-specific optimized refreshing in the future, hopefully well before 6.0 (as this is wholly contained in the SDK and thus can be improved during SDK feature-band updates). As is often the case we had to make prioritization decisions due to time and scope constraints.

As @pranavkm pointed out, `dotnet watch` today already supports configuration via MSBuild and environment variables and any features can/should integrate/extend that. I believe there are new switches in .NET 5 to allow disabling the `dotnet watch` auto-refresh feature.

With regards to documenting the new capabilities introduced in .NET 5, @pranavkm can you please follow up on that?

**Comment by pranavkm** [comment]
> With regards to documenting the new capabilities introduced in .NET 5, @pranavkm can you please follow up on that?

There's a PR out for it: https://github.com/dotnet/AspNetCore.Docs/pull/19815/files

**Comment by RickStrahl** [comment]
Thanks - it's a bit frustrating to see that this is trickling out in steps which really isn't all that useful - it pretty much has to all work to be really useful. The static file functionality 

So off the top of my head what's needed at minimum is:

* turn off auto-refresh
* Exclude a subfolder, exclude specific files/filespec

Looks like the first feature is already in there via the `DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH` which works although not documented (yet) - thanks. Also think this one is important enough it probably warrants a command line switch?

I also wonder if that feature should be turned on by default - it does certainly have potential side effects. 

For example, I'm working on a new project right now that has a Localization Admin form up with current context. If auto-refresh is enabled that page gets blown away along with active page I'm working on when I really need that page to stay alive and not refresh. That's fine as long as it's configurable or better yet if certain folders/extensions/files can be excluded. (I shouldn't complain about this because this doesn't work in my component either :smile:)

**Comment by RickStrahl** [comment]
So to get back to the original message. Updated to RC1 over the weekend and the built-in `dotnet-watch run`  Live Reload functionality still isn't working in my actual live project. 

I just can't see what could possible cause that occur. Anybody have any ideas what else to look at? (startup code is in the root message)

**Comment by pranavkm** [comment]
You can get `dotnet watch` to print some debug messages as part of running an app: `dotnet watch --verbose run`.  For e.g. here's what I see:

```C#
watch : dotnet-watch is configured to launch a browser on ASP.NET Core application startup.
watch : Refresh server running at ws://127.0.0.1:49231
```

`Debug` logs (for the `Microsoft` filter) from the app should also include a few messages about the middleware being loaded and if it decides to modify the response:

```
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly Microsoft.AspNetCore.Watch.BrowserRefresh
...
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware[1]
      Response markup is scheduled to include browser refresh script injection.
....
dbug: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware[2]
      Response markup was updated to include browser refresh script injection.
```

For the middleware to be injected `dotnet watch` requires the app to target netcoreapp3.1 or later and for the `Properties/launchSettings.json` to say that it allows launching a browser:

```json
    "MyApp": {
      "commandName": "Project",
      "launchBrowser": true, <-- this flag
```

**Comment by DamianEdwards** [comment]
We're tracking a few items to improve this in an upcoming release:
- #27047 Refresh on static file change
- #27046 Ensure new files are detected
- #27048 Make new config options configurable via MSBuild

**Comment by DamianEdwards** [comment]
Closing this issue now that `dotnet watch` uses Hot Reload by default in .NET 6, before falling back to auto-restart when applying code changes fails ("rude edits"), along with the completion of a few of the outstanding requests from above. Any problems can be opened as new specific issues.
