### ISSUE TITLE
Blazor ondblClick event is not working in IPad Pro IOS 10.3 

### ISSUE THREAD

**Issue by vickynatraj** [dotnet/aspnetcore#25757]
ondblClick event bound to div element is not working in specific IPad Pro IOS 10.3 version. It is working in latest version of IOS. While double taping in IPAD. instead of navigating, page gets zoomed.

ondblClick event is not triggered.   

### Describe the bug
ondblClick event is not triggering in IOS 10.3 version

### To Reproduce

@page "/"
@inject NavigationManager Navi

<div @ondblclick="DblClicked">
Double click here to Navigate to Counter Page
</div>
@code{
    public void DblClicked(MouseEventArgs Args)
    {
        Navi.NavigateTo("/counter");
    }
}

### Exceptions (if any)

  No Exception thrown

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015203
 Commit:    b1dcd32553

Runtime Environment:
Sample: [DoubleClickEvent.zip](https://github.com/dotnet/aspnetcore/files/5200960/DoubleClickEvent.zip)

 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015203\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
- VS 2019 Professional 16.6.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not Blazor specific. It's how this event is handled on iOS in general. We recommend going to [StackOverflow](https://www.stackoverflow.com) for further guidance.
