### ISSUE TITLE
Code that previously built now refuses to build after update to latest VS19

### ISSUE THREAD

**Issue by shawty** [dotnet/aspnetcore#25765]
### Describe the bug
Project that previously built fine, now refuses to build since update to VS2019 Preview V16.8.0 Preview 2.1

### To Reproduce
Simple repo that fails is here : https://github.com/shawty/blazorSSBemptyattfail

To reproduce from scratch

1. Open Visual Studio Community 2019 Version 16.8.0 Preview 2.1
2. Start A New Server Side Blazor Project Targeting .Net Core 3.1
3. Add a component to the shared folder called "TestComponent" with the following code in

![image](https://user-images.githubusercontent.com/1876454/92750127-afdac380-f37e-11ea-9fd2-d895d8c0c766.png)

4. Modify the index page as follows

![image](https://user-images.githubusercontent.com/1876454/92750209-c41ec080-f37e-11ea-9329-9c40b5388f4a.png)

5. Build the solution, the build will fail with the following error

![image](https://user-images.githubusercontent.com/1876454/92750326-def13500-f37e-11ea-824f-c4bbb172727b.png)

### Logs & Exceptions

Please collect the data below before reporting your issue to aid us in diagnosing the root cause.

No crashes experienced, so no logs collected

### Further technical details
Full VS Details

![image](https://user-images.githubusercontent.com/1876454/92750632-2e376580-f37f-11ea-8a14-ab326818e4c0.png)

Basic OS and System details

![image](https://user-images.githubusercontent.com/1876454/92750984-7eaec300-f37f-11ea-8e78-f318e3aff7f8.png)

My previous version before upgrading was "Visual Studio Community Preview 16.7.0 Preview 3.1"

If I remove the attribute and/or add a string following the equals with content in the issue is resolved.  That content can be anything including whitespace/space char, t his problem only persists if the attribute value is empty or missing completely.

**Comment by shawty** [comment]
My previous was a preview version too Stefan (Same version, but preview build)

Is this a bug in the new preview then?

**Comment by mkArtakMSFT** [comment]
Related to #25267. This issue has been fixed in .NET 5.0 RC1.
