### ISSUE TITLE
Investigate Diagnostics.FunctionalTests on 20H1

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#25768]
Diagnostics.FunctionalTests are currently skipped on Windows.10.Amd64.Server20H1.Open
https://github.com/dotnet/aspnetcore/blob/3386289caaec38a818f8a02112c438c90d24c02f/src/Middleware/Diagnostics/test/FunctionalTests/Diagnostics.FunctionalTests.csproj#L8

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-25627-merge-aa0ff5d62c91480dbd/Diagnostics.FunctionalTests--net5.0/console.28592c19.log?sv=2019-02-02&se=2020-09-25T06:19:47Z&sr=c&sp=rl&sig=xNXQV%2BECMXlBGpxzsMYHYqg3XRlCLzp8KIjIv1%2FYUBw%3D

```
C:\h\w\BFF70A8C\w\AC170943\e>call RunPowershell.cmd mssql\InstallSqlServerLocalDB.ps1   || exit /b 1 
"PS: Running 'C:\h\w\BFF70A8C\w\AC170943\e\mssql\InstallSqlServerLocalDB.ps1' "
Installing SQL Server 2016 Express LocalDB

Downloading 'SqlLocalDB.msi' to 'C:\h\w\BFF70A8C\w\AC170943\e\mssql\obj\SqlLocalDB.msi'.
The term 'C:\h\w\BFF70A8C\w\AC170943\e\mssql\Download.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
https://github.com/dotnet/aspnetcore/blob/6de6ba907271a652e77c98a262e7ab6409c27930/eng/helix/content/mssql/InstallSqlServerLocalDB.ps1#L34
$PSScriptRoot seems to return a different value than before, Download.ps1 is over here:
https://github.com/dotnet/aspnetcore/blob/6de6ba907271a652e77c98a262e7ab6409c27930/eng/scripts/Download.ps1
Maybe this is a change in powershell? The old windows agents were running a very old version of Windows 10 (RS1?).

The new value seems to be more in line with the definition of $PSScriptRoot:
"If used inside a PowerShell script, it automatically defined the fully-qualified filesystem path to the directory that contains the script file." https://riptutorial.com/powershell/example/27231/-psscriptroot. It's looking for Download.ps1 in the same directory as  InstallSqlServerLocalDB.ps1.

**Comment by BrennanConroy** [comment]
@TanayParikh Looks like someone saw this before and you've fixed it now 😆 
Want to look into un-skipping on the queue referenced above?

**Comment by halter73** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/29701.

**Comment by halter73** [comment]
And here I thought the issue was so old that it must be a flaky network share or something or else it would have been fixed already.

**Comment by TanayParikh** [comment]
> Want to look into un-skipping on the queue referenced above?

Sure thing; https://github.com/dotnet/aspnetcore/pull/29707 (assuming that's what you meant, if not let me know 😄)
