### ISSUE TITLE
Blazor: Compiler type check for named cascading parameters

### ISSUE THREAD

**Issue by philippdolder** [dotnet/aspnetcore#25762]
### Is your feature request related to a problem? Please describe.
When the type of the member bound to a named *CascadingValue*, e.g. `<CascadingValue Value="@this.model" Name="Model" />` and the member of the component that is consuming this cascading value through `[CascadingParameter(Name = "Model")]` do not match this value will, as expected, be `null` or whatever the default value of the type is (or what the developer chose as the initial value of the property).

### Describe the solution you'd like
I believe it should be possible to figure out during compile time that there is a type mismatch in the component hierarchy, similar to how it's done when a parameter directly bound to a component has a type mismatch. This would help detect this type of problems very early. Especially when doing refactorings.

I am fully aware that this could only work with named cascading values, as the unnamed by design match by type.

### Additional context

**Comment by javiercn** [comment]
@philippdolder thanks for contacting us.

That's not generally possible since you can pass in a variable and we don't have insight into that. You can avoid that problem by defining a constant that you use in the name parameter as well as in the attribute definition.
