### ISSUE TITLE
Microsoft.AspNetCore.App 2.1.1 restricts versions of Microsoft.EntityFrameworkCore.SqlServer 3.1.x

### ISSUE THREAD

**Issue by phatcher** [dotnet/aspnetcore#25769]
### Describe the bug
The Microsoft.AspNetCore.App restricted the allowed version of EF Core to <2.2,  given that 3.1 supports netstandard2.0 is there a reason for such a tight boundary?

Rationale is to take advantage of the improvements in EF Core without having to port the application to netcore3.1

### To Reproduce
Reference Microsoft.EntityFrameworkCore.SqlServer 3.1.x from a netcoreapp2.1

**Comment by Pilchie** [comment]
In what way does it restrict it?  Tagging @ajcvickers .

**Comment by phatcher** [comment]
There's a nuget package restriction, so you get a compile time error.

I can see why though as some of the namespaces differ between EF Core 2.1 and 3.x, e.g. System.Data.SqlClient vs Microsoft.Data.SqlClient and there was also some refactoring e.g. DbQuery<T> vs DbSet<T>

**Comment by ajcvickers** [comment]
EF Core was in the shared framework until 3.0.  It looks like everything in the shared framework is restricted in this way, which is presumably by-design from the ASP.NET side, since in general these things won't work with newer versions.

**Comment by JunTaoLuo** [comment]
I believe that these "guardrails" were added since mix and matching packages and runtimes is not supported. The intention is that to use 3.1 packages, you should be on netcoreapp3.1.
