### ISSUE TITLE
.NET Core 3.x.x installer language in Portuguese instead of English

### ISSUE THREAD

**Issue by RomBrz** [dotnet/aspnetcore#25763]
# Issue Title

.NET Core 3.0.x and 3.1.0 installers using different language to installation instead of the language of the download, seems like that prior to 3.x.x the installers runs at system language, and with 3.x.x runs with server location.

# General

The behavior of the installer changed with .NET Core 3.x.x. For example, if i go to the official download site and pickup the .NET Core 2.1.14 Server Bundle (english site), download and execute it on a server, the installer will be in English language.
If i download the .NET Core 3.0.1 Server Bundle on the same official site, and execute on the same server, the installer will be in Brazilian Portuguese language. The same occurs with 3.0.0 and the new 3.1.0.

The server is with English language, but region set to Brazil. So seems like the behavior changed with the 3.0.0. 

This is normal? This is expected? Does this affect the behavior of the server? (All installed in english, but only with .NET 3.x.x installed in PT-BR).

Prior to .NET Core 3.x.x, for example, i'm from Brazil, and download the .NET Core. I would install on a server with english language and region settings set to Brazil.

**Comment by BrennanConroy** [comment]
@joeloff Is this something we can fix for 5.0?

**Comment by joeloff** [comment]
@BrennanConroy I haven't looked at this in a while, but if we're just missing the LCID folder and its content it should be simple enough

**Comment by BrennanConroy** [comment]
Do you have cycles to look at this or is there someone else you can recommend?

**Comment by JunTaoLuo** [comment]
It looks like the 1033 folder is present: https://github.com/dotnet/aspnetcore/tree/release/3.1/src/Installers/Windows/WindowsHostingBundle/1033. FYI this is the release/3.1 branch and it looks that that folder has been present since at least 3.1.2. 

@joeloff what did you mean when you said that the 1033 and LCID folders are missing?

**Comment by joeloff** [comment]
I meant the 1033 entry is missing from https://github.com/dotnet/aspnetcore/blob/790c4dc2cf59e16e6144f7790328d563ca310533/src/Installers/Windows/WindowsHostingBundle/Bundle.wxs#L47

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/29065, https://github.com/dotnet/aspnetcore/pull/29066
