### ISSUE TITLE
Blazor not loading external css (_content) when changing the ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by darren-zdc** [dotnet/aspnetcore#25786]
# Describe the bug
Blazor server is not able to load the external css file when changing the ASPNETCORE_ENVIRONMENT to something other than the default, like `Local`. I tried it in a blank new Blazor server app, and it can be reproduced.

### To Reproduce
1. Use the default Blazor server app template
2. Download a sample nuget Blazor library, like (`Blazord.Typeahead`) or any Blazor class library
3. Add this line to the head of `_Host.cshtml`
```html
    <link href="_content/Blazored.Typeahead/blazored-typeahead.css" rel="stylesheet" />
```
4. Launch the app in IIS, and check the resources. Everything should be fine without an error
5. Add another `appsettings.Local.json` to the project with the same content as in the `appsettings.Development.json` file
6. Go to `Launchsettings.json`, and change the `"ASPNETCORE_ENVIRONMENT": "Development"` to `"ASPNETCORE_ENVIRONMENT": "Local"`
7. Relaunch the app, you will see a 404 error in the browser console about the resources

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/36833304/92809097-4e205680-f38a-11ea-9fdd-733a9f4ef69f.png)

### Further technical details
- ASP.NET Core version
3.1.401
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/36833304/92809642-cdae2580-f38a-11ea-96a3-8c9cb65884d7.png)
![image](https://user-images.githubusercontent.com/36833304/92809288-7a3bd780-f38a-11ea-9596-ba5c944816aa.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
![image](https://user-images.githubusercontent.com/36833304/92809694-da327e00-f38a-11ea-8ffd-f3b8307f7672.png)

**Comment by SteveSandersonMS** [comment]
@javiercn I had a look around to see where the decision is made about whether to enable SWA (based on the environment) and couldn't immediately spot what code varies the SWA behavior based on environment. I know you're busy at the moment so please don't rush to answer this - just when you're ready!

**Comment by darren-zdc** [comment]
Found a workaround here
https://dev.to/j_sakamoto/how-to-deal-with-the-http-404-content-foo-bar-css-not-found-when-using-razor-component-package-on-asp-net-core-blazor-app-aai
