### ISSUE TITLE
CORS issue with SignalR 'Access-Control-Allow-Credentials' header in the response is '' 

### ISSUE THREAD

**Issue by sai0893** [dotnet/aspnetcore#25789]
I are unable to connect to our SignalR hub:

Access to XMLHttpRequest at 'my app url' <from origin 'my website url>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

![image](https://user-images.githubusercontent.com/71103473/92813718-62427300-f3df-11ea-9161-3f758a136e15.png)

Trying to connect using HubConnectionBuilder in Typescript something like below:

```
const connection = new signalR.HubConnectionBuilder()
            .withUrl("sample url")
            .build();
```

And in ConfigureServices():
```
services.AddCors(options => options.AddPolicy("SignalRPolicy", builder =>
                    {
                        builder
                        .WithOrigins("Sample Origins")
                        .WithMethods("GET", "POST")
                        .AllowAnyHeader()
                        .AllowCredentials();
                    }));

//
services.AddMvc();
//
services.AddSignalR().AddAzureSignalR(//endpoints);
```

Configure():

```
app.UseCors("SignalRPolicy");
app.UseEndpointRouting();
 app.UseAzureSignalR(routes =>
            {
                routes.MapHub<TestHub>("/sampleHub");
            });

            app.UseMvc();

```
Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@BrennanConroy can you suggest the right config to use in this case? Thanks!

**Comment by BrennanConroy** [comment]
The policy looks fine assuming you have the correct origin(s) set.

Can you share the response headers for the failed OPTIONS request?

**Comment by sai0893** [comment]
Below are response headers:

Request ID: 87a959a1-dbfb-44d2-9338-23678c70dab8
HttpResponseCode: OK
Headers:
['Access-Control-Allow-Origin' :: '(app url); ' //which we had set in builder.WithOrigins()
['Access-Control-Allow-Headers' :: 'authorization,x-requested-with; '
['Access-Control-Allow-Methods' :: 'POST; '
['Access-Control-Expose-Headers' :: 'authorization,x-requested-with; '
['x-ms-request-id' :: 'a1f8bbeb-bc52-4d43-b631-2eb9544b8843; '
['Date' :: 'Thu, 17 Sep 2020 15:49:05 GMT; '



![image](https://user-images.githubusercontent.com/71103473/93504559-4555f480-f937-11ea-927d-57b10ddc73ec.png)
