### ISSUE TITLE
Error unprotecting the session cookie (in development and deployment) .Net Core 3.1

### ISSUE THREAD

**Issue by Chewhern** [dotnet/aspnetcore#25801]
In my startup.cs , 

I have added the **"services.AddSession();"** in **ConfigureServices**.

I have added the **"app.UseSession();"** in **Configure**

and then there's **"app.UseAuthorization();"** in **Configure by default**

whenever I run it through **assembly(dll file after publish)** or in development mode.

The following error did happen ..

warn: Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The payload was invalid.
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

What can I do to solve this ?

**Comment by blowdart** [comment]
What OS are you using? What version of ASP.NET Core are you using? What does your startup.cs file contain?

And what does "run it through assembly(dll file after publish)" mean here?

**Comment by Chewhern** [comment]
I am using Ubuntu 16 LTS VPS(OS)

3.1 ASP.Net Core

Startup.CS:

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDistributedMemoryCache();

            services.AddSession();

            services.AddRazorPages();

            services.AddHostedService<FreezeDBAccountBackgroundSchedule>();

            services.AddHostedService<FreezeExceedSizeDBAccount>();

        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseSession();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }

The .dll is actually an published version of my personal application after doing **"dotnet publish"** in respective ASP.Net Core folder..

In my latest project I am sure that during development runtime... , the following warning didn't appear but when I do **"dotnet (project dll file)"** command in console, it did gives the following above warning .. whenever I surf through my webpages ..

**Comment by andreweberle** [comment]
I too am having the same issue, I have following the advice from this [https://github.com/dotnet/aspnetcore/issues/2520](GitHub Link) however nothing I do is stopping the warnings in event viewer.

**Comment by andreweberle** [comment]
After a few days debugging, I found that having `services.AddHttpContextAccessor();` was causing the problem, <br>so I did this instead `services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();`<br> I'm not sure if this is a real fix or not, however the warnings are no longer showing in event viewer when deployed on IIS 8.5

**Comment by Chewhern** [comment]
Any method that I can use to solve this ?

**Comment by blowdart** [comment]
You're on Linux. Data Protection cannot persist keys on linux without configuration, so it's using memory to hold the keyring, and when the app restarts, or you hit another instance of the app, where the keyring is different. Your logs will have had a warning on starting.

You need to decide where the keyring should be stored (file system, redis,  azure data storage, something else entirely) and [configure data protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1) within your app to use it.
