### ISSUE TITLE
[Discussion] Obsoleting AzureAD.UI and AzureADB2C.UI APIs and packages

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#25807]
Discussion for https://github.com/aspnet/Announcements/issues/439

## Obsoleting AzureAD.UI and AzureADB2C.UI APIs and packages

In ASP.NET Core 2.1, integration with Azure Active Directory (AzureAD) and Azure Active Directory B2C (AzureAD B2C) authentication was provided by the [Microsoft.AspNetCore.Authentication.AzureAD.UI](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.AzureAD.UI) and [Microsoft.AspNetCore.Authentication.AzureADB2C.UI](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.AzureADB2C.UI). The functionality provided by these packages was based on the AzureAD v1.0 endpoint. 

Starting in .NET 5.0 integration with AzureAD and AzureAD B2C authentication will be provided by [Microsoft.Identity.Web](https://www.nuget.org/packages/Microsoft.Identity.Web) which is based on Microsoft Identity Platform (formerly known as AzureAD v2.0 endpoint). As such, we are deprecating the old APIs in the AzureAD.UI and AzureADB2C.UI packages.

### Version introduced

ASP.NET Core 5.0 Preview 8

### Old behavior

These APIs were not Obsolete.

### New behavior

They are now Obsolete.

### Reason for change

We are migrating the functionality to MSAL APIs provided by Microsoft.Identity.Web, which is built from [this repository](https://github.com/azuread/microsoft-identity-web).

### Recommended action

Follow the documentation at https://github.com/azuread/microsoft-identity-web/wiki. Specifically instructions on how to use Microsoft.Identity.Web APIs for [web apps](https://github.com/azuread/microsoft-identity-web/wiki/web-apps) and [web api apps](https://github.com/azuread/microsoft-identity-web/wiki/web-apis) for how to use the new APIs from Microsoft.Identity.Web. 

### Category

ASP.NET

### Affected APIs

Note: the types listed here and all their members are obsolete. The individual members are not listed to keep the list brief.
* [`Microsoft.AspNetCore.Authentication.AzureADAuthenticationBuilderExtensions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azureadauthenticationbuilderextensions)
* [`Microsoft.AspNetCore.Authentication.AzureAD.UI.AzureADDefaults`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azuread.ui.azureaddefaults)
* [`Microsoft.AspNetCore.Authentication.AzureAD.UI.AzureADOptions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azuread.ui.azureadoptions)
* [`Microsoft.AspNetCore.Authentication.AzureADB2CAuthenticationBuilderExtensions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azureadb2cauthenticationbuilderextensions)
* [`Microsoft.AspNetCore.Authentication.AzureADB2C.UI.AzureADB2CDefaults`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azureadb2c.ui.azureadb2cdefaults)
* [`Microsoft.AspNetCore.Authentication.AzureADB2C.UI.AzureADB2COptions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azureadb2c.ui.azureadb2coptions)

---
#### Issue metadata

* Issue type: breaking-change

**Comment by JunTaoLuo** [comment]
FYI @jmprieur I expect this discussion for our breaking change to convert to using Microsoft.Identity.Web to generate a fair amount of discussion.

**Comment by Pilchie** [comment]
:eyes:
