### ISSUE TITLE
FrameworkReference build error with Microsoft.Identity.Web and Radzen.Blazor

### ISSUE THREAD

**Issue by dakahler** [dotnet/aspnetcore#25825]
There is an interaction between these two packages that causes a build error. More strangely, if you then remove one of the references, the build error persists. However, adding either of them on their own on a fresh project builds fine.

Repro

Create new Blazor WebAssembly hosted project with the project template in Visual Studio 16.8 Preview 2. Select .net 5.0 target.
Add references to the Client project: Microsoft.Identity.Web (latest preview); Radzen.Blazor
Build
Error: C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(318,5): error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

The `Microsoft.identity.Web` package is meant to be used on server. As a guide, you can see how this is done in a new Blazor WebAssembly app when you enable auth.

Also, have a look at https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio
