### ISSUE TITLE
Fix shared framework on Helix

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#25835]
Found in https://github.com/dotnet/aspnetcore/pull/25587

Windows shared runtime is installed in Linux and OSX Helix queues.

Need to:
1. Install shared runtime for the correct platform in Helix
2. Fix tests that assume the Windows runtime is always installed.

**Comment by HaoK** [comment]
Note: when this is fixed, we can also remove the SkipHelixArm on the project templates tests

**Comment by JamesNK** [comment]
@JunTaoLuo Looks like I created two issues for this. Is it a dupe of https://github.com/dotnet/aspnetcore/issues/27044

Can @HaoK's change be made now?

**Comment by JunTaoLuo** [comment]
I'll try it, but I think so.

**Comment by HaoK** [comment]
Your other PR makes it so the windows binaries work everywhere again?  Nice :)
