### ISSUE TITLE
Incorrect Errors shown in Visual Studio

### ISSUE THREAD

**Issue by pomeara** [dotnet/aspnetcore#25847]
Visual studio shows a lot of incorrect errors when using blazer and a simple code mistake is made.

In this situation I open a command line and run "dotnet build" and this shows the single error not the endless incorrect errors that are shown in visual studio.

To reproduce this create a blazer application in Visual Studio and then make a simple error and watch the crazy # of errors spat out in the IDE and then run a "dotnet build" in a command window

This is driving me crazy and I am surprised that such a problem has been released and not picked up by the team, this makes people not want to use Visual Studio as it's just so bad at picking up correct errors when running .net core applications

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem as well as share details about the VS you're using.
