### ISSUE TITLE
Blazor WASM Unable To Load System.Management.Automation

### ISSUE THREAD

**Issue by jrhodnik** [dotnet/aspnetcore#25844]
### Describe the bug
When using the preview of Blazor WASM and attempting to utilize the Microsoft.PowerShell.SDK package, Blazor WASM is unable to load the System.Management.Automation.dll. Am I asking too much to run a PowerShell host in-browser?

### To Reproduce
 - Create new Blazor WASM project. Update project file according to [this guide.](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-7/)
 - Add `Microsoft.PowerShell.SDK` package reference
 - Do something with a `PowerShell` host

Example repo [here](https://github.com/jrhodnik/PowerShellTests).

### Exceptions (if any)
`Could not load file or assembly 'System.Management.Automation, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.`

### Further technical details
 - Browser doesn't attempt to load DLL from server at all. No network request for it.

**Comment by fMichaleczek** [comment]
I already try on Blazor 3.2 with success, but it need change on PowerShell code . And end, there is a problem to use webclient API because it's async and PowerShell doesn't how to handle the one thread model of WASM.

**Comment by fMichaleczek** [comment]
@jrhodnik I open an issue in the PowerShell repo, could you close this one ?

**Comment by jrhodnik** [comment]
@fMichaleczek Yes, thank you!
