### ISSUE TITLE
Prevent Multiple Login ( Identity )

### ISSUE THREAD

**Issue by ArminShoeibi** [dotnet/aspnetcore#25858]
Hi, I am trying to make some mechanism to prevent multiple login with ASP.NET Core Identity, but  I realized that this mechanism isn't implemented in ASP.NET Core Identity.

Please provide an easy way to use this feature like IdentityOptions items.

**Comment by blowdart** [comment]
This isn't something we would consider for identity, it's outside the typical use case, especially when multiple logins are hard to define.
