### ISSUE TITLE
Give better error description, log errors in Windows Event Log where available when app bootstrap fails

### ISSUE THREAD

**Issue by brgrz** [dotnet/aspnetcore#25862]
### Is your feature request related to a problem? Please describe.

Trying to run an asp.net core app on Windows Server with incorrent or missing Hosting bundle results in 

```
Server Error

500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
```

Actually we had the .NET Core 3.1.8 runtime installed but the Hosting bundle was not installed (it happens).

**What shouldn't have happen is spending couple of hours trying to nail down the issue and doing so without any errors being logged anywhere.**

### Describe the solution you'd like

Since this happens before the app is bootstrapped/running and no logging mechanism can work in this case the platform/framework should provide exception/error details and log them in Event Log or in the root of the application, maybe /log or similar.

Also the error message details provided by IIS could be better, I only discovered this was runtime related because the Task Manager was missing dotnet.exe processes and the error message (see the screenshot below) looks somewhat .NET Framework-ish.

### Additional context

![dotnetcore-bootrstraperror](https://user-images.githubusercontent.com/193816/93028042-7cfc2e00-f611-11ea-8ae5-330344656914.png)

**Comment by JunTaoLuo** [comment]
This sounds like something that IIS itself needs to consider. I don't think there's anything we can do in aspnetcore.

**Comment by BrennanConroy** [comment]
This error happens before anything we own so there isn't any code we can improve to fix this. However we can look at adding something to our docs for this type of error.

https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0#500-internal-server-error

There should be logs from IIS for this though. Event logs should show something.
The log should look something like: https://docs.microsoft.com/troubleshoot/iis/not-start-reenable-shared-configuration

**Comment by brgrz** [comment]
These types of errors usually have their logs in Event log but nothing was present this time, we checked multiple times.

Great news on adding a warning to docs.

**Comment by adityamandaleeka** [comment]
> This error happens before anything we own so there isn't any code we can improve to fix this. However we can look at adding something to our docs for this type of error.
> 
> https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0#500-internal-server-error

Assigning to @HaoK for the doc update. This can be done after 6.0 locks down.

**Comment by HaoK** [comment]
Docs updated in https://github.com/dotnet/AspNetCore.Docs/pull/24138
