### ISSUE TITLE
Failure to Install Microsoft.AspNetCore.AppRef

### ISSUE THREAD

**Issue by jt4000** [dotnet/aspnetcore#25860]
When I tried installing Microsoft.AspNetCore.AppRef in my webapplication in .net core 3.1.

```
Severity    Code    Description Project File    Line    Suppression State
Error       Package 'Microsoft.AspNetCore.App.Ref 3.1.3' has a package type 'DotnetPlatform' that is not supported by project 'xxxxxx'.             


Severity    Code    Description Project File    Line    Suppression State
Error   NU1213  The package Microsoft.AspNetCore.App.Ref 3.1.3 has a package type DotnetPlatform that is incompatible with this project. 
```

I tried google around but I don't get any good feedback.

Do you guys have any experience about this case?

Thank you!

**Comment by eugeneogongo** [comment]
>This package is an internal implementation of the .NET Core SDK and is not meant to be used as a normal PackageReference.

The above is from the NuGet package.
[NuGet package page](https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/3.1.8)

**Comment by blowdart** [comment]
Why do you believe you need a manual reference to this package? What are you trying to achieve?

**Comment by jt4000** [comment]
> Why do you believe you need a manual reference to this package? What are you trying to achieve?

In asp.net core 2.2 you are enable to install "Microsoft.AspNetCore.App" and when I tried to do the same approach for .net core 3.1. it doesn't work. 


![data](https://user-images.githubusercontent.com/14993569/93026444-42d95f00-f606-11ea-9d59-7e0e4a09575a.png)

**Comment by eugeneogongo** [comment]
What primarily are you trying to achieve? We find a way forward 😊

**Comment by jt4000** [comment]
> What primarily are you trying to achieve? We find a way forward 😊

It is used for connection between front  (reacjtjs or angular) and backend without any obstacle
