### ISSUE TITLE
Ho to Dynamically emit the Script & Css Tag based on environment variable in index.html ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#25878]
I am using Square to process payment in Blazore Hosted WebAssembly 3.1. (Not using .Net 5)

Square has different JavaScript URL for SandBox and Production which need to be put into Head of Index.html.

How can i dynamically emit related Script tag based on the Envrionment i am running in, like DEV to emit SandBox URL and Prod to use Live Square URL to their javascript

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
`.html` files are static and you can't modify the content.
Consider swapping your `Index.html` file with `_Host.cshtml` file in the Server project and change the fallback route (in the Startup.cs) to the new `_Host.cshtml` file. Take a look at the [.NET 5.0 RC1 release announcement blog post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/comment-page-2/#blazor-webassembly-prerendering) and look into the Blazor WebAssembly prerendering section.

**Comment by nssidhu** [comment]
I tried to follow the article but running into compile issue.

![image](https://user-images.githubusercontent.com/3267605/95668149-940d3d80-0b35-11eb-8710-869b0da8ab72.png)

**Comment by nssidhu** [comment]
The article is missing lots of details.
I was able to get it working by following the article below.
[https://jonhilton.net/blazor-wasm-prerendering/]
Ultimately I concluded it is not worth going through all the pain of restructuring an app unless it gets further simplified
