### ISSUE TITLE
Script error when using Blazor Server with Edge 44

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25874]
Repro steps:

- Install .NET 5 RC2 SDK
- `dotnet new blazorserver`
- `dotnet run`
- Browse to the app in Edge 44 (old Edge, not the Chromium based one)

Expected result:

- App loads and functions

Actual result:

```
SCRIPT1002: SCRIPT1002: Syntax error blazor.server.js (1,67838)
```

App doesn't function: Counter doesn't work.

This worked in .NET 5 Preview 8, but looks like it regressed in RC1.

**Comment by danroth27** [comment]
While we technically only support the latest browser versions, I think we should fix this one. Enterprises control when the new Edge gets rolled out, so it will take some time for new Edge to completely replace the old one.

**Comment by mrpmorris** [comment]
Hi @danroth27 

I am seeing a different error similar in nature to this one.
https://github.com/dotnet/aspnetcore/issues/26090

**Comment by SteveSandersonMS** [comment]
@danroth27 Can you close this one when there are updated docs/announcement? I'm assigning it to you until then.

**Comment by mkArtakMSFT** [comment]
I believe this has been addressed https://github.com/aspnet/Announcements/issues/441.
@danroth27 can we close this now?

**Comment by mrpmorris** [comment]
Is there an event in Blazor js or something that will fire for unsupported browsers, so I can display an error message?
