### ISSUE TITLE
VS4Mac can't run freshly created Blazor WASM

### ISSUE THREAD

**Issue by rspaulino** [dotnet/aspnetcore#25888]
### Describe the bug

Can't run Blazor Wasm

```
Cannot use file stream for [/Users/.../TodoW/TodoW/bin/Debug/net5.0/TodoW.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/.../TodoW/TodoW/bin/Debug/net5.0/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/Users/.../TodoW/TodoW/bin/Debug/net5.0/TodoW.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/Users/.../TodoW/TodoW/bin/Debug/net5.0/TodoW.runtimeconfig.json' file and specify the appropriate framework.
```
### To Reproduce

Create a new net5.0 Blazor wasm and click run

### Further technical details
- ASP.NET Core version
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-rc.1.20451.17" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-rc.1.20451.17" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0-rc.1.20451.14" />
  </ItemGroup>

</Project>

```
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-rc.1.20452.10/

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
VS4Mac 8.8 Preview(8.8 build 2120)
```

**Comment by pranavkm** [comment]
@thaystg do you happen to know what version of VS (Mac) this will be addressed in?

**Comment by thaystg** [comment]
No, I don't know...

**Comment by mrward** [comment]
Debugging Blazor WASM projects with .NET 5 rc1 is broken in VS Mac 8.8 preview 3 and older 8.8 versions. There are a few problems.

1) VS Mac does not recognise Blazor projects due to the Sdk change from web to "Microsoft.NET.Sdk.BlazorWebAssembly.
   - This is causing error about 'libhostpolicy.dylib' since VS Mac is not running it as a Blazor project.
   - This has been fixed but did not make it into VS Mac 8.8 preview 3.
2) Debugging does not end the dotnet process
   - With 1) fixed there are still problems here. Some of these problems I believe also affect VS on Windows.

The only workaround would be to use .NET 5 preview 3 or .NET Core 3.1, with a global.json file to pin the SDK for the solution to the older SDK.

**Comment by rspaulino** [comment]
I appreciate all the internal feedback but it's very misleading/fragmented from the announcement, the only experience that work is using VS19 everything else is chaos and for it to be call RC1 is very uninspired, I understand the complexity of too many moving parts but a runtime without the tooling aren't much for developers.

I just wish the announcement would have been more clear about the experience, it would have save me a few hours.

**Comment by ShadyNagy** [comment]
As I can see this bug still there 

```powershell
docker exec -i -e ASPNETCORE_HTTPS_PORT="32836" -w "/app" 8bb652861bd9f147df8797e08a708f376d5837614d698e1e0744f97810e9b712 sh -c ""dotnet" --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net5.0/BlazorApp6.dll\" | tee /dev/console"
Cannot use file stream for [/app/bin/Debug/net5.0/BlazorApp6.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/bin/Debug/net5.0/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/app/bin/Debug/net5.0/BlazorApp6.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/app/bin/Debug/net5.0/BlazorApp6.runtimeconfig.json' file and specify the appropriate framework.
```
