### ISSUE TITLE
settings from secrets.json not loading in blazor wasm app

### ISSUE THREAD

**Issue by fingers10** [dotnet/aspnetcore#25893]
I have an API Key that needs to be used in my blazor wasm app. However I don't want to place the value in `appsettings.json` to make sure the `API Key` doesn't get into my source control. One such way to achieve is to use `secrets.json` in ASP.NET Core. But the value from `secrets.json` is not loading in my `Program.cs`.

**`appsettings.json:`**

```json
{
  "APIKey": "appsettings.json"
}
```

**`Program.cs:`**

```c#
var builder = WebAssemblyHostBuilder.CreateDefault(args);

Debug.WriteLine($"APIKey:{builder.Configuration["APIKey"]}"); // works appsettings.json is logged in output window
```

If I move the key from `appsettings.json` to `secrets.json`

**`secrets.json:`**

```json
{
  "APIKey": "secrets.json"
}
```

then output window log is empty. **`secrets.json`** no longer works in blazor wasm?

### Further technical details
- ASP.NET Core version - 3.1
- Include the output of `dotnet --info`
```cmd
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd
```
- The IDE (VS) you're running on, and it's version - **Visual Studio - `16.7.3`**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You shouldn't be sending any secrets to the client as they can be easily compromised / inspected.
The pattern we recommend to use in these situations is to let server handle dealing with any sensitive information and passing the resulting data back to the client.

As for your particular situation, `secrets.json` is designed to stay on the server.

**Comment by fingers10** [comment]
So how to handle these situations? An API call to server from `Program.cs` and get the key?

**Comment by blowdart** [comment]
Even if you do that the secret is still client side. Just because it's not in the source doesn't make it any less discoverable, it'd just take a debugger.

Proxy calls to an authenticated api through a facade service server side, and keep the secret server side. Or look at oauth and have your users authenticate to the service individually.

**Comment by fingers10** [comment]
@blowdart Thanks for the suggestion. But I need the Key to render my UI components.
 `builder.Services.Add3rdPartyUIComponents("APIKEY")` in this license key can be read from browser and can be used by anyone right?

**Comment by blowdart** [comment]
I leave that answer to the blazor folks. If it's going to be readable from a browser, going into source control doesn't seem like much worse :)

**Comment by fingers10** [comment]
@mkArtakMSFT what's your opinions on this? Especially to use 3rd party UI components, Key is needed and how to keep those safe?
