### ISSUE TITLE
Define actions without controllers

### ISSUE THREAD

**Issue by suraciii** [dotnet/aspnetcore#25891]
### Is your feature request related to a problem? Please describe.
I'd like to define actions without controllers, but currently, all actions need to be placed in their controllers
In other words, I want to use actions at class level, per action per class per .cs file, organized by folder structure rather than controllers

### Describe the solution you'd like
I'd like to define actions like this:
```csharp
[HttpPost("posts/{postId}/comments")]
[Authorize]
[MyCustomFilter]
public class CommentOnPost : ActionBase
{
    public override async Task<ActionResult<Comment>> Execute([FromBody]CreateCommentRequest request)
    {
        var user = HttpContext.User;
        // do stuff
        return Json(createdComment);
    }
}
```

I tried to use endpoints to implement this, but that will lose those fancy feather (filters, model binding and validation, etc.)
And I also tried to use single action controllers (each controller only has one action), but it looks heavy and tricky

Is that a good idea? provide a way to define only actions without controllers?

**Comment by davidfowl** [comment]
Consider using https://github.com/ardalis/ApiEndpoints

**Comment by csyszf** [comment]
@davidfowl Thanks for replying, this solution met my needs and I'll try it, but I still expect there will be a native/official way to do that :)

**Comment by davidfowl** [comment]
There won't be an official way, at least there is no plan to do so. I'd recommend using that library and giving any feedback and learnings about using it to the team.

**Comment by davidfowl** [comment]
cc @halter73 @glennc

**Comment by suraciii** [comment]
This can be achieved by net6's minimal API now.
