### ISSUE TITLE
Blazor: List virtualization does not take into account list item changes

### ISSUE THREAD

**Issue by dantronik-markus** [dotnet/aspnetcore#25899]
To preface: I don't know whether this is a bug report or a feature request. I'll settle for feature request for now.

### Describe the bug
I've tested the list virtualization feature as of Blazor 3.0rc1. My component is a tree structure and looks like this:
https://gist.github.com/dantronik-markus/54d1999f327cb97efee9430aff594740 where TreeView is the name of the component.

When I click the expander to toggle the child items, then they do get toggled. However, the item state gets reset to 
```
ChildNodes = null;
ChildrenLoaded = false;
```
when the virtualization happens causing my previous branches to be collapsed.

### Is your feature request related to a problem? Please describe.
I'm trying to make changes to items in a list rendered using virtualization (e.g. for persisting collapsed / expanded state of a tree structure).

### Describe the solution you'd like
```Virtualize``` should have a Synchronize method of some sort or a flag that allows it to store / persist state changes.

**Comment by mkArtakMSFT** [comment]
FYI @SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
After thinking some more about this we recommend calling `StateHasChanged` on the component which holds the Virtualization component inside. This will force reevaluation and things should be re-rendered correctly.
If you hit an issue with this approach, please file a new issue.

/cc @guardrex can you please update the docs to account for this guidance? Thanks!

**Comment by guardrex** [comment]
Will do.

**Comment by sergey-su** [comment]
Notifying that the proposed fix did not work for an alleged duplicate. See  https://github.com/dotnet/aspnetcore/issues/26110#issuecomment-696272190

**Comment by guardrex** [comment]
Open a new issue @sergey-su  and please put a `cc: @guardrex` in your opening comment.

**Comment by dantronik-markus** [comment]
I can confirm that the proposed fix did not work for me either. At best, it caused the tree items to be expanded when scrolling up and collapsed when scrolling down.
