### ISSUE TITLE
Blazor WebAssembly SignalR does not use WebSocket transport in net5.0-rc1

### ISSUE THREAD

**Issue by campersau** [dotnet/aspnetcore#25913]
### Describe the bug
When using Blazor WebAssembly SignalR does not use WebSocket transport but Long Polling instead.

### To Reproduce
Checkout https://github.com/campersau/blazor-signalr-test which includes a server and clients (important file is [`Index.razor`](https://github.com/campersau/blazor-signalr-test/blob/master/SignalRBlazorTest/Pages/Index.razor)). Looking at the dev tools only long polling fetch requests are being made and no websocket connection.

![image](https://user-images.githubusercontent.com/4009570/93246328-e81e3f80-f78c-11ea-94e6-9dcb78d3336c.png)
[HAR file](https://github.com/campersau/blazor-signalr-test/blob/master/localhost.har?raw=true)

Console output when adding logging to SignalR client:
```
Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport: Starting transport. Transfer mode: Text.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: HttpConnection Started.
Microsoft.AspNetCore.SignalR.Client.HubConnection: Using HubProtocol 'json v1'.
Microsoft.AspNetCore.SignalR.Client.HubConnection: HubConnection started.
```

### Further technical details
- ASP.NET Core version: 5.0.100-rc.1.20452.10
- Microsoft Visual Studio Enterprise 2019 Preview Version 16.8.0 Preview 3.0

**Comment by Pilchie** [comment]
:eyes:

**Comment by ar0311** [comment]
Can someone point me to why WebSockets are no longer supported on Blazor WASM?

**Comment by campersau** [comment]
@ar0311 see the corresponding PR https://github.com/dotnet/aspnetcore/pull/25922
So SignalR WebSockets should finally work again in rc2.

Standalone WebSockets should work now though.

**Comment by msschl** [comment]
Same issue for me

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/25922
