### ISSUE TITLE
Consider cross-compiling projects to target DefaultNetCoreTargetFramework

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#25917]
We have a handful of projects in the repo that do not cross-compile to .NET Core. The reference assemblies in .NET Core carry nullability and platform compatibility annotations and there are currently no plans to make this work on down level tfms.

Updating these projects to additionally cross-compile to `$(DefaultNetCoreTargetFramework)` seems like a small cost for the richer compile time we gain:

* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/SignalR/clients/csharp/Client/src/Microsoft.AspNetCore.SignalR.Client.csproj
* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/SignalR/clients/csharp/Client.Core/src/Microsoft.AspNetCore.SignalR.Client.Core.csproj
* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/SignalR/clients/csharp/Http.Connections.Client/src/Microsoft.AspNetCore.Http.Connections.Client.csproj
* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/SignalR/common/Protocols.NewtonsoftJson/src/Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson.csproj
*  https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/SignalR/common/Protocols.MessagePack/src/Microsoft.AspNetCore.SignalR.Protocols.MessagePack.csproj
* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/SignalR/server/StackExchangeRedis/src/Microsoft.AspNetCore.SignalR.StackExchangeRedis.csproj
* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/Features/JsonPatch/src/Microsoft.AspNetCore.JsonPatch.csproj
* https://github.com/dotnet/aspnetcore/blob/ce16ff0a51a74811674228835696e5cc78494fd7/src/Logging.AzureAppServices/src/Microsoft.Extensions.Logging.AzureAppServices.csproj

**Comment by wtgodbe** [comment]
The only 2 that still don't target `DefaultNetCoreTargetFramework` are https://github.com/dotnet/aspnetcore/blob/master/src/Features/JsonPatch/src/Microsoft.AspNetCore.JsonPatch.csproj and https://github.com/dotnet/aspnetcore/blob/master/src/Logging.AzureAppServices/src/Microsoft.Extensions.Logging.AzureAppServices.csproj
