### ISSUE TITLE
[Blazor] Cannot publish Release-sized apps any more

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#25924]
.NET 5 RC1
VS Version 16.8.0 Preview 3.0

1: New Blazor WebAssembly app
2: Immediately publish it to a folder

The size is 16.7 MB (up fro 10,1 MB btw)

3: Delete the contents of the publish folder
4: Change the publish configuration from Release to Debug
5: Publish

The size is now 43 MB

6: Delete the contents of the publish folder
7: Change the publish configuration back to Release
8: Publish

The size of the publish folder is still over 40MB

This seems to be because the file `Properties\PublishProfiles\FolderProfile.pubxml` retains a setting `<SelfContained>false</SelfContained>` even when the publish mode is set back to `Release`. Removing that item results in 16.7 MB builds again.

**Comment by mkArtakMSFT** [comment]
@vijayrkn do you want to track this in AzDO? Please dupe it against this issue.

**Comment by vijayrkn** [comment]
The question is why does setting <SelfContained>false</SelfContained> increase the publish size? Do you see this same behavior when you set this property in the csproj as well? 

Adding @pranavkm since it could be something in the blazor sdk copying RID specific files when this property is set. Nothing in this report is pointing me to an obvious VS tooling error here.

**Comment by mrpmorris** [comment]
@vijayrkn I just created a new Blazor Wasm app, without even building it I did a Publish to folder (Release) and it was 42.3 MB in size (selfContained was set to false by default in the pubxml file).

Changing my property group as follows resulted in a published wwwroot folder 41.4 MB in size.
```
	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<SelfContained>false</SelfContained>
	</PropertyGroup>
```

**Comment by vijayrkn** [comment]
@mrpmorris And this happens even outside of VS is it?

**Comment by mrpmorris** [comment]
@vijayrkn could you tell me what the exact command line text is you'd like me to execute?

**Comment by vijayrkn** [comment]
just `dotnet publish` from project root

**Comment by mrpmorris** [comment]
@vijayrkn 

```
dotnet new blazorwasm -n Tester
dotnet build -c Release
dir .\bin\Release\net5.0\ /s
```

Results in a collection of files over 34 MB, and the structure isn't something that could be published (there is no index.html file)

```
[ref]
[wwwroot]
Tester.dll
Tester.pdb
Tester.StaticWebAssets.xml
```

Where the wwwroot folder is empty except for a `_framework` folder. So the `dotnet publish` command line isn't working correctly at all by the look of it.

**Comment by vijayrkn** [comment]
@mkArtakMSFT - Since this issue is not specific to VS & it happens even from dotnet publish, it would be best for some one from your team to take a look.

**Comment by javiercn** [comment]
@mrpmorris I don't believe this is longer a problem, but if it is, please feel free to comment and we'll reopen

**Comment by mrpmorris** [comment]
Looks like you are correct, thank you @javiercn
