### ISSUE TITLE
signalr  WebSockets  Connection disconnected

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/aspnetcore#25920]
At some point when an event occurs, a disconect occurs on the web client side
How to diagnose the problem?

```
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.7">
```

At some point, when an event occurs 
`await Clients.Group(Id).SendAsync("ReceiveMessageChatAsync", messageInfo, _response);`
, a disconect occurs on the web client side. How to diagnose the problem?

disconnected does not happen all the time, but at some point. sending messageInfo, _response   - Json

does not show obvious errors

log:
1374bb54-0751-4a06-928d-4c1597ae37b6:395 887
Utils.ts:178 [2020-09-15T19:25:55.625Z] Debug: Selecting transport 'WebSockets'.
Utils.ts:178 [2020-09-15T19:25:55.626Z] Trace: (WebSockets transport) Connecting.
Utils.ts:174 [2020-09-15T19:25:55.663Z] Information: WebSocket connected to wss://localhost:44301/NHUB?id=rqIlFbKiYiBvXwXAyi-Nug.
Utils.ts:178 [2020-09-15T19:25:55.663Z] Debug: The HttpConnection connected successfully.
Utils.ts:178 [2020-09-15T19:25:55.663Z] Debug: Sending handshake request.
Utils.ts:178 [2020-09-15T19:25:55.664Z] Trace: (WebSockets transport) sending data. String data of length 32.
Utils.ts:174 [2020-09-15T19:25:55.664Z] Information: Using HubProtocol 'json'.
Utils.ts:178 [2020-09-15T19:25:55.666Z] Trace: (WebSockets transport) data received. String data of length 3.
Utils.ts:178 [2020-09-15T19:25:55.667Z] Debug: Server handshake complete.
Utils.ts:178 [2020-09-15T19:25:55.667Z] Debug: HubConnection connected successfully.
Utils.ts:178 [2020-09-15T19:25:55.668Z] Trace: (WebSockets transport) sending data. String data of length 131.
Utils.ts:178 [2020-09-15T19:25:55.669Z] Trace: (WebSockets transport) data received. String data of length 44.
Utils.ts:178 [2020-09-15T19:26:10.032Z] Trace: (WebSockets transport) socket closed.
Utils.ts:178 [2020-09-15T19:26:10.033Z] Debug: HttpConnection.stopConnection(undefined) called while in state Connected.
Utils.ts:174 [2020-09-15T19:26:10.033Z] Information: Connection disconnected.
Utils.ts:178 [2020-09-15T19:26:10.033Z] Debug: HubConnection.connectionClosed(undefined) called while in state Connected.
Utils.ts:174 [2020-09-15T19:26:10.034Z] Information: Connection reconnecting.
Utils.ts:174 [2020-09-15T19:26:10.034Z] Information: Reconnect attempt number 1 will start in 0 ms.
Utils.ts:178 [2020-09-15T19:26:10.037Z] Debug: Starting connection with transfer format 'Text'.
Utils.ts:178 [2020-09-15T19:26:10.037Z] Debug: Sending negotiation request: https://localhost:44301/NHUB/negotiate?negotiateVersion=1.
Utils.ts:178 [2020-09-15T19:26:10.050Z] Debug: Selecting transport 'WebSockets'.
Utils.ts:178 [2020-09-15T19:26:10.050Z] Trace: (WebSockets transport) Connecting.
Utils.ts:174 [2020-09-15T19:26:10.056Z] Information: WebSocket connected to wss://localhost:44301/NHUB?id=hLFJ0F01FngIdS9aIZM4NQ.
Utils.ts:178 [2020-09-15T19:26:10.057Z] Debug: The HttpConnection connected successfully.
Utils.ts:178 [2020-09-15T19:26:10.057Z] Debug: Sending handshake request.
Utils.ts:178 [2020-09-15T19:26:10.057Z] Trace: (WebSockets transport) sending data. String data of length 32.
Utils.ts:174 [2020-09-15T19:26:10.058Z] Information: Using HubProtocol 'json'.
Utils.ts:178 [2020-09-15T19:26:10.060Z] Trace: (WebSockets transport) data received. String data of length 3.
Utils.ts:178 [2020-09-15T19:26:10.060Z] Debug: Server handshake complete.
Utils.ts:174 [2020-09-15T19:26:10.060Z] Information: HubConnection reconnected successfully.
1374bb54-0751-4a06-928d-4c1597ae37b6:395 887

**Comment by BrennanConroy** [comment]
Can you collect your server side logs?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging

**Comment by EvgenyPrikhodko** [comment]
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Failed writing message. Aborting connection.
System.Text.Json.JsonException: A possible object cycle was detected which is not supported



Thanks, figured it out. How to use "Microsoft.AspNetCore.Mvc.NewtonsoftJson" for signalr?

**Comment by BrennanConroy** [comment]
> How to use "Microsoft.AspNetCore.Mvc.NewtonsoftJson" for signalr?

You can't. Instead you can use the Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson package. https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-3.1&tabs=dotnet#switch-to-newtonsoftjson-1
