### ISSUE TITLE
[Blazor] Published build is not significantly smaller (and sometimes larger)

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#25926]
.NET 5 RC1
VS Version 16.8.0 Preview 3.0

Note 1: That when testing the network sizes I am clearing out all browsing data in Chrome and then opening an incognito window to load the page.

Note 2: This is not related to issue https://github.com/dotnet/aspnetcore/issues/25924

### Scenario 1: Only Slightly smaller

When I create a new Blazor WebAssembly app and run it, the console says "blazor loaded 8.86 MB resources. This application was built with linking (tree shaking) disabled. Published applications will be significantly smaller."

But when I publish the app and upload it to a host (Azure static website) the total size of the download is 7.7 MB

### Scenario 2: Actually larger when deployed

For my own app when running from VS the console message says size of the download is 9.8 MB (the network tab says 10 MB). When uploaded to an Azure static website Chrome's network tab says it downloaded 13.7 MB 

https://github.com/mrpmorris/the-periodic-table-of-elements-game

Note: These apps are published by right-clicking the project and then selecting the Folder Publish option. The resulting binaries are then copied to Azure Static Website (Azure Storage) with Azure Storage Explorer.

@SteveSandersonMS thinks compression may be disabled. See comment on this closed ticket: https://github.com/dotnet/aspnetcore/issues/25902#issuecomment-693450574

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like the Compression isn't enabled for your project. We are working on enabling support for .NET and Blazor in Azure Static Web Apps, which will support proper compression. For now you can look at https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#compression
