### ISSUE TITLE
Get Code Action Identifiers From Roslyn

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#25939]
Currently we determine the type of code action via heuristics (ex. ends with `Path` for fully qualifying `System.IO.Path`). Optimally, we could get some kind of id/enum from roslyn which identifies the `kind` of the code action. This issue tracks adding support for this.

This would likely require expanding `VSCodeAction` to support a `Kind`. Alternatively we could add the `Kind` as part of `VSCodeAction.Data`.

This issue may require changes from LSP Platform / O#.

https://github.com/dotnet/aspnetcore-tooling/pull/2501#discussion_r489030237

**Comment by TanayParikh** [comment]
Pushing this to Preview3. [PR is in progress](https://github.com/dotnet/roslyn/pull/48951), but haven't had time to complete it this cycle due to [pull-diagnostics](https://github.com/dotnet/aspnetcore/issues/21121).

**Comment by TanayParikh** [comment]
Blocked pending design review (Roslyn is considering making the `ProviderName` a part of the public API).

**Comment by TanayParikh** [comment]
Design review notes;

- Taking the Provider Names approach using `PredefinedCode{Fix,Refactor}ProviderNames` to allow Razor to filter out which Code Actions are made available to the user.
  - Doc comments in PredefinedCode{Fix,Refactor}ProviderNames.cs detailing the human process for refactors / new code action additions
  - Will consume Provider Name from `string[] CodeAction.CustomTags`

**Comment by TanayParikh** [comment]
Tracking issue for Roslyn: https://github.com/dotnet/roslyn/issues/4919

**Comment by TanayParikh** [comment]
External, better idea of prioritization by EOW.

**Comment by TanayParikh** [comment]
Should be landing shortly, unblocking the Razor use case.

**Comment by TanayParikh** [comment]
The external work has been started. 

Step 1; add the custom tags property for Code Actions: https://github.com/dotnet/roslyn/pull/51456

**Comment by NTaylorMullen** [comment]
@TanayParikh moved to in progress since you're kicking booty here 😉
