### ISSUE TITLE
Cant build Blazor WASM project on Linux with 5.0 RC1

### ISSUE THREAD

**Issue by ar0311** [dotnet/aspnetcore#25930]
### Describe the bug
When using the Snap installed 5.0 RC1 SDK, unable to build/publish a Blazor WASM Project

### To Reproduce
Ubuntu 18.04
Install dotnet-sdk beta channel snap according to instructions at https://snapcraft.io/dotnet-sdk
Create new blazorwasm project --- dotnet-sdk.dotnet new blazorwasm -o blazorwasm
Build it --- dotnet-sdk.dotnet build

### Exceptions (if any)
$ dotnet-sdk.dotnet build
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '5.0.0-rc.1.20451.14' was not found.
    - The following frameworks were found:
        3.1.8 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  
  You can resolve the problem by installing the specified framework and/or SDK.
  
  The specified framework can be found at:
    - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0-rc.1.20451.14&arch=x64&rid=ubuntu.18.04-x64
/snap/dotnet-sdk/100/sdk/5.0.100-rc.1.20452.10/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets(125,3): error : rzc rewritecss exited with code 150. [/home/ubuntu/blazorwasm50/blazorwasm50.csproj]

Build FAILED.

/snap/dotnet-sdk/100/sdk/5.0.100-rc.1.20452.10/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets(125,3): error : rzc rewritecss exited with code 150. [/home/ubuntu/blazorwasm50/blazorwasm50.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:28.02
### Further technical details
- ASP.NET Core version - 5.0 RC 1
- Include the output of `dotnet --info`
$ dotnet-sdk.dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/100/sdk/5.0.100-rc.1.20452.10/

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  5.0.100-rc.1.20452.10 [/snap/dotnet-sdk/100/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [/snap/dotnet-sdk/100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [/snap/dotnet-sdk/100/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
CMD Line

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've addressed this issue in 5.0 RC2 as part of #14432 
If you have the .NET SDK in the PATH, it should work.
