### ISSUE TITLE
Blazor WebAssembly is loading unnecessary dll.

### ISSUE THREAD

**Issue by GTmAster** [dotnet/aspnetcore#25949]
I'm trying to use Blazor WebAssembly hosted by ASP.NET Core. After implementing a page, I saw in Chrome DevTools many of unnecessary dlls are transmitted to client. There is an example of situation. Let's assume we have following structure of projects in the solution:
```
BlazorApp.Client (contains Blazor pages)
    Reference to BlazorApp.Shared
BlazorApp.Server (contains ASP.NET core)
    Reference to BlazorApp.Client
    Reference to BlazorApp.Shared
BlazorApp.Shared (contains shared classes)
    Reference to ClassLibrary
ClassLibrary (contains some more shared classes)
    NuGet reference to AWSSDK.Core
    MyEnum.cs (enum, which is used in Blazor page; not using AWS SDK)
```
So basically BlazorApp.Shared project has reference to some other project, which could have many nuget packages. Minimum code to reproduce the issue is available in repo [https://github.com/GTmAster/blazor-treeshake](https://github.com/GTmAster/blazor-treeshake)

My assumption is Mono Linker does a tree shaking in Release build, so all unused code and libraries will be excluded from resulting web assembly. But when I run my app, I see it loads AWSSDK.Core.dll from the server. Code in BlazorApp.Client doesn't use it, as well as the code in BlazorApp.Server and in BlazorApp.Shared. It is only loaded, because it is referenced in ClassLibrary.

![DevTools](https://i.stack.imgur.com/jE7UF.png)

Am I getting the wrong idea about Mono Linker tree shaking? Is the only way to exclude this dll from shipping is to move MyEnum to BlazorApp.Shared and break BlazorApp.Shared -> ClassLibrary reference?

### To Reproduce
Minimum code to reproduce the issue is available in repo [https://github.com/GTmAster/blazor-treeshake](https://github.com/GTmAster/blazor-treeshake)

### Further technical details
- ASP.NET Core version: 3.1.402
- dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE : Visual Studio 2019 16.7.3, app is run via command line outside IDE

**Comment by SteveSandersonMS** [comment]
> Mono Linker does a tree shaking in Release build,

Tree shaking (linking) happens on publish only.

Could you please try publishing your application and see if you still think it loads unnecessary assemblies? Thanks!

**Comment by GTmAster** [comment]
@SteveSandersonMS 
Tried with publish `dotnet publish -c Release BlazorApp.sln`. AWSSDK.Core.dll is still loaded by client.

**Comment by SteveSandersonMS** [comment]
Can you clarify why you think `AWSSDK.Core.dll` is unnecessary? During publish, the linker removes anything that's not reachable by a chain of calls from your main application assembly. So if it's still there after publish, that suggests it can get called by your code.

**Comment by SteveSandersonMS** [comment]
By default the linker only strips code from framework assemblies, not from NuGet packages you reference.

@pranavkm Do you know if we have docs anywhere on how to customize what gets linked?

**Comment by GTmAster** [comment]
@SteveSandersonMS It's definitely not used. There is no call to AWS SDK anywhere.

**Comment by pranavkm** [comment]
This should help: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming-options#trimmed-assemblies.

**Comment by GTmAster** [comment]
@pranavkm 
Thanks for the link to documentation about trimming. I have added following properties to BlazorApp.Client.csproj and BlazorApp.Shared.csproj:
```
	<PublishTrimmed>true</PublishTrimmed>
	<TrimMode>link</TrimMode>
	<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
```

But it didn't help. AWSSDK.Core.dll is still loaded by browser. Am I missing here something?

**Comment by Pilchie** [comment]
Re-opening.  This probably shouldn't have been in Discussions.

Ping @SimonCropp
