### ISSUE TITLE
Prevent login two person with one account in Identity core

### ISSUE THREAD

**Issue by ekhtiari** [dotnet/aspnetcore#25940]
I need a feature that when I Login by an account nobody can login by this account before I logoff.
I can do it now by use a new claim in Identity cookie or add new Boolean  filed to AspnetUser table but if user close browser or lost connection to server he can login again. 

thanks

**Comment by blowdart** [comment]
That's beyond what we aim identity at, it's not often asked for and not something we'd consider implementing.

**Comment by ekhtiari** [comment]
@blowdart thanks for reply . i think this behavior was better check inside Identity Functions that we implement new one.
I create new boolean field for aspnetusers table and when user login or logoff this field set with correct property . and finally if user's browser closed suddenly i set this field with signalR oncloseConnection function
