### ISSUE TITLE
Started on fresh Windows 10, issue with MSBuild 16.8.0

### ISSUE THREAD

**Issue by dshyryayev** [dotnet/aspnetcore#25956]
Hi, team

I have started on absolutely fresh Windows 10.
I have followed all instructions on this page:

https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md

There was a good success on this: restore.cmd

But when I've opened VS 2019 Professional edition, I've got this error:

Error:
C:\Projects\open-source\aspnetcore\src\DefaultBuilder\src\Microsoft.AspNetCore.csproj : error  : The project file cannot be opened. Version 5.0.100-rc.1.20452.10 of the .NET Core SDK requires at least version 16.8.0 of MSBuild. The current available version of MSBuild is 16.7.0.37604. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

Please also look at attachment:
![Image 243](https://user-images.githubusercontent.com/5845770/93349592-84c3fa00-f7ec-11ea-96d8-2365383ece53.png)

**Comment by Tratcher** [comment]
There was an sdk break recently that now requires VS 16.8.0-preview 2 to compile.

**Comment by dshyryayev** [comment]
@Tratcher , where I can download VS 16.8.0-preview 2?

**Comment by Tratcher** [comment]
https://visualstudio.microsoft.com/vs/preview/

**Comment by dshyryayev** [comment]
It worked! Thank you!

**Comment by zeinali0** [comment]
Isn't any way to update installed VS 2019 to preview version?

**Comment by Tratcher** [comment]
No. The preview and stable versions are installed separately because sometimes the preview breaks.
