### ISSUE TITLE
Getting error on making connectionwith server via microsoft/signalr

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/aspnetcore#25950]
hello, we are facing an issue in making a connection with the server via signalr, we are using **_@microsoft/signalr_** library in react js to connect with dotnet core 3.1 but getting the following error. Please help us to sort this issue
'''**
    Connection failed:  Error
    at new HttpError (Errors.ts:20)
    at XMLHttpRequest.xhr.onerror (XhrHttpClient.ts:76)**
'''

**Comment by BrennanConroy** [comment]
Can you collect a network trace when the issue occurs?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#collect-a-network-trace-with-fiddler-preferred-option

**Comment by bilalmalik777** [comment]
please go through the attached file to investigate the trace. let me through if face any difficulty to understand this file
[localhost.txt](https://github.com/dotnet/aspnetcore/files/5236961/localhost.txt)

**Comment by bilalmalik777** [comment]
Thanks @BrennanConroy for you assistance, issue has been resolved
