### ISSUE TITLE
Html.DisplayFor ignores subclass display templates for model properties

### ISSUE THREAD

**Issue by danports** [dotnet/aspnetcore#25955]
`@Html.DisplayFor(model => model.Widget)` ignores the actual type of `Model.Widget` and only uses the declared type of the `Widget` property to look up display templates. This is confusing and unhelpful, especially considering that `@Html.DisplayForModel()` does look up the display template based on the actual type of the model (even when the `@model` directive specifies a parent class).

Simple repro here: https://github.com/danports/aspnetcore-subclassdisplaytest

When you run the repro project, note that the `Home/Index.cshtml` view ignores the `Subwidget.cshtml` display template. If you change the `DisplayFor` call to `@Html.DisplayFor(model => model.Widget, "Subwidget")` you can force the subclass display template to render, so I could use `@Html.DisplayFor(model => model.Widget, Model.Widget.GetType().Name)` as a workaround for this issue for now.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
