### ISSUE TITLE
Browser Link does not work with Blazor applications

### ISSUE THREAD

**Issue by Ajdthomson** [dotnet/aspnetcore#25953]
I am trying to achieve greater productivity in Blazor WASM application razor markup changes. As per [this announcement](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/), auto-rebuild functionality is working great using Ctrl-F5 and IIS Express. 

However I believe it should also be possible for the browser to refresh using Browser Link functionality but this does not work.

Steps to reproduce

- Visual Studio 16.7.3
- Create new Blazor WebAssembly App (ASP.NET Core hosted)
- Add Microsoft.VisualStudio.Web.BrowserLink package
- Configure Startup.cs configure using `app.UseBrowserLink();`
- Ctrl-F5 to run without a debug session
- On Browser Link Dashboard click "View in Browser"

The application is launched in the configured browser but no browser link connection is made. On inspecting the application, the expected javascript has not been injected.

Is this functionality possible using a different configuration?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We do not plan to support Browser Link for Blazor applications.
For .NET 5.0 release we have invested in an alternative mechanism for improving the inner-loop performance using dotnet-watch and enabling it to work with VS. In 6.0 we plan to invest more into this area by handling #5456.
