### ISSUE TITLE
Flaky test: Various dotnet watch tests

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#25967]
https://dev.azure.com/dnceng/public/_build/results?buildId=816781&view=ms.vss-test-web.build-test-results-tab&runId=25995950&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=122319

https://dev.azure.com/dnceng/public/_build/results?buildId=817399&view=ms.vss-test-web.build-test-results-tab&runId=26020760&paneView=debug

Two seem related to https://github.com/dotnet/sdk/issues/13649, which I filed.

**Comment by pranavkm** [comment]
Slightly less blocked. We've contributed a fix to resolve the underlying issue to the SDK. Once it becomes available, we can pick it up our repo and tests can be unquarantined.

**Comment by pranavkm** [comment]
These tests were unskipped / unquarantined as part of migrating to the SDK repo.

**Comment by jkotalik** [comment]
@pranavkm There are still a good number of tests that are quarantined with this issue (https://github.com/dotnet/aspnetcore/blob/93342c7823404542af4f540d899a20ef1fb23bd9/src/Tools/dotnet-watch/test/GlobbingAppTests.cs). Should we either:
1. Delete the GlobbingAppTests.cs
2. Keep this issue open with these failures still present.

**Comment by pranavkm** [comment]
We should be able to merge this soon: https://github.com/dotnet/aspnetcore/pull/29722

**Comment by mkArtakMSFT** [comment]
As the linked 5.0 PR is now merged, should this be closed now? @pranavkm?
