### ISSUE TITLE
empty_input_scopes_error error when using MSAL Auth

### ISSUE THREAD

**Issue by dfederm** [dotnet/aspnetcore#25961]
### Describe the bug
When using MSAL auth, I receive a `empty_input_scopes_error` error.

This possibly seems related to https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1943. If so, upgrading the package may be a reasonable solution.

### To Reproduce
```cs
            // In ConfigureServices
            builder.Services
                .AddMsalAuthentication(options =>
                {
                    options.ProviderOptions.Authentication.Authority = "https://login.microsoftonline.com/" + webApiSettings.TenantId;
                    options.ProviderOptions.Authentication.ClientId = webApiSettings.ClientId;

                    options.UserOptions.RoleClaim = "roles";

                    // Cache in local storage instead of the default session storage so that auth will persist across windows/tabs.
                    options.ProviderOptions.Cache.CacheLocation = "localStorage";
                });

        // In a Service
        var tokenRequestOptions = new AccessTokenRequestOptions { Scopes = new[] { $"{webApiSettings.ClientId}/.default" } };
        AccessTokenResult tokenResult = await _authenticationService.RequestAccessToken(tokenRequestOptions);
```

### Exceptions
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: empty_input_scopes_error: Scopes cannot be passed as null, undefined or empty array because they are required to obtain an access token. Given Scopes: 
      ClientConfigurationError: empty_input_scopes_error: Scopes cannot be passed as null, undefined or empty array because they are required to obtain an access token. Given Scopes: 
```

### Further technical details
- .NET version: 5.0.100-rc.1.20452.10

**Comment by dfederm** [comment]
I was able to work around this issue by adding this to the `AddMsalAuthentication` call:
```cs
options.ProviderOptions.DefaultAccessTokenScopes = webApiSettings.ScopesList.ToList();
```

I believe the problem is here: https://github.com/dotnet/aspnetcore/blob/b98b74a59c3a6b0466015bc3d00485ac83540d92/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts#L78-L92

The default access token scopes are used there, rather than the one provided in the access token request.

**Comment by captainsafia** [comment]
#26232 contains a fix for some issues where the scopes are not propagated directly. Note that you'll still need to configure the scopes in your application config as documented [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1).
