### ISSUE TITLE
No RC1 package for Microsoft.AspNetCore.Components.Web.Extensions

### ISSUE THREAD

**Issue by dfederm** [dotnet/aspnetcore#25970]
### Describe the bug
The latest version of Microsoft.AspNetCore.Components.Web.Extensions is 5.0.0-preview.8.20414.8. However, this version is not compatible with RC1 since OSPlatform.Browser was removed in https://github.com/dotnet/runtime/pull/40373. This was fixed already in https://github.com/dotnet/aspnetcore/pull/24652, but because there is no RC1 package for Microsoft.AspNetCore.Components.Web.Extensions, protected browser storage is effectively broken.

### To Reproduce
Use Microsoft.AspNetCore.Components.Web.Extensions 5.0.0-preview.8.20414.8 with RC1

### Exceptions (if any)
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: System.Runtime.InteropServices.OSPlatform System.Runtime.InteropServices.OSPlatform.get_Browser()
System.MissingMethodException: Method not found: System.Runtime.InteropServices.OSPlatform System.Runtime.InteropServices.OSPlatform.get_Browser()
   at Microsoft.AspNetCore.Components.Web.Extensions.ProtectedLocalStorage..ctor(IJSRuntime jsRuntime, IDataProtectionProvider dataProtectionProvider)
   ...
```

### Further technical details
- .NET 5.0.100-rc.1.20452.10

**Comment by dfederm** [comment]
[This post](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#upgrade-an-existing-project) says:
> If you’re using the new Microsoft.AspNetCore.Components.Web.Extensions package, update to version 5.0.0-preview.9.*. This package doesn’t have an RC version number yet because we expect to make a few more design changes to the components it contains before it’s ready to ship.

But [that package](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Web.Extensions) doesn't have a preview9 version either.

**Comment by pranavkm** [comment]
@dfederm thanks for the issue. We're working on releasing an updated version of this package. I'll post an update once it's published to NuGet.org.

**Comment by dfederm** [comment]
Also note that there is another package:

```xml
<PackageReference Include="Microsoft.AspNetCore.Components.ProtectedBrowserStorage" Version="5.0.0-rc.1.20451.17" />
```

But when using that, I get:

```
System.PlatformNotSupportedException: Microsoft.AspNetCore.Components.ProtectedBrowserStorage.ProtectedLocalStorage cannot be used when running in a browser.
   at Microsoft.AspNetCore.Components.ProtectedBrowserStorage.ProtectedBrowserStorage..ctor(String storeName, IJSRuntime jsRuntime, IDataProtectionProvider dataProtectionProvider)
   at Microsoft.AspNetCore.Components.ProtectedBrowserStorage.ProtectedLocalStorage..ctor(IJSRuntime jsRuntime, IDataProtectionProvider dataProtectionProvider)
```

Which is interesting :)

**Comment by pranavkm** [comment]
The error message you're seeing is intentional - we do not want to give you any illusions that you secrets can be stored by WebAssembly. In rc2, we moved the feature in to ASP.NET Core to better reflect this - https://github.com/aspnet/Announcements/issues/436.

**Comment by pranavkm** [comment]
A preview9 version of the package is now available at https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Web.Extensions/5.0.0-preview9.20467.1. We think some of the features in this package need more time to bake and they will not be RTMing as part of the 5.0 release. (cc @danroth27)
