### ISSUE TITLE
AddMsalAuthentication

### ISSUE THREAD

**Issue by curelom** [dotnet/aspnetcore#25977]
AddMsalAuthentication missing from .net 5 release candidate Blazor and can find no documentation for replacement.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We can verify that the package is there and the API is also there. https://www.nuget.org/packages/Microsoft.Authentication.WebAssembly.Msal/5.0.0-rc.1.20451.17
Please make sure you're using the correct package reference.
