### ISSUE TITLE
We need blazor runtime compilation.

### ISSUE THREAD

**Issue by 1002527441** [dotnet/aspnetcore#25999]
Hello dotnetCore developers.

We are using Blazor server app for our project, but we spent a lot of time for debug as re-complie code while the code was changed.

if we have Blazlor runtime compilation, we could save much time on compilation.
I think this is important features, we expect to have it.

**Comment by dimohy** [comment]
I feel the same demand.

Already the Razor and Blazor environments are great. But in some ways it's not modern.

Let's take an example. At this point, the comparison can pinpoint the problem and see the relative differences.

A. I modified the CSS file. After saving, you can immediately view the changed results in your web browser. Here, it is an almost instantaneous time within 0.5 to 1 second.

B. I added the Style to the Razor page of Blazor server and saved it to check the result. And wait for the changed result on the web page. Only one page in Razor was modified and styled. It should withstand a waiting time of about 14-18 seconds. There are about 80 pages composed of Razor and about 10 components composed of Razor.

This highlights the need to reconfirm the applied case, not the specific case.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We plan to improve the inner-loop performance for .NET 6.
We track that as part of #5456.
