### ISSUE TITLE
Blazor WASM Memory usage

### ISSUE THREAD

**Issue by theunis-allegiance** [dotnet/aspnetcore#25996]
Hi all,

Hope you guys can help me clear up some concerns that I have. I really hope it's something that I am missing.

We have been actively developing Blazor WASM applications since the start of the year, and have about 3 in production. There is just one concern that both me and my team have, and that's memory usage. We are seeing differing usages between browsers, and not as in a couple of megabytes, but actually up to 450MB difference between browsers, and in some cases even more.

I initially thought it might be due to something we are doing wrong, or not disposing something, but as a test I have created a blank new blazor-wasm project and took it for a test drive.

The following is observed.

In Chrome v85.0.4183.102
We launch the application via F5 and then click between the Home, and Counter pages. The RAM that the application is consuming then suddenly jumps up to ~600MB.

In Microsoft Edge "Edgium" v85.0.564.51
We do exactly the same, and see the RAM usage jump from 150MB up to 250MB.

In Firefox 80.0.1
We also do the same scenario, and this one really baffles me. The RAM usage stays at a constant 6-7MB.

Taking this into account, the other browsers from start consumes up to 150MB, where Firefox stays at a constant 7MB with no drastic spikes. I check Task Manager as well to ensure the Firefox Browser Task Manager is not at fault here.

Can someone please explain this to me? Are we missing something? Is it maybe the Chromium engine?

As a side note, one of our developer can quickly get one of our applications to run up to 4GB of RAM with just navigating, thus causing the browser to crash. I have also done the same with the latest .NET 5 RC1 and the same is still happening.

Couple of technical details.

dotnet --version 3.1.401

    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.0" />

If this is not enough info, please let me know what else is required.

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This might be related to Debugging as we don't have debugging support for Firefox and that's where you see no such effects.

Can you share a sample repro project which causes the Chrome to crash?

**Comment by stoepa** [comment]
So after further investigation, we have pinpointed the issue and it does not seem related to Blazor. It seems to be one of the third party packages we use. I will take it up with them, for those interested its MatBlazor and specifically there MatSelect component. It continues creating the inner UL element on page navigation and never destroys them from the DOM,thus creating multiple DotNetObjectReferences and they never dispose. 

Just to add to my question why is it that Firefox uses much less memory in terms of WASM? Or is this a question I should pose to the respective browsers? 

You can see the memory usage with the blazor-wasm template, no need for additional packages, just the template project.
