### ISSUE TITLE
StringAsTempFile with stream

### ISSUE THREAD

**Issue by generik0** [dotnet/aspnetcore#26001]
Hi

The current implementation of StringAsTempFile for nodes services only passes a string for content.
We have some rather large content we are passing and could save memory by allowing streams to be written

so along with:
```c#
public StringAsTempFile(string content, CancellationToken applicationStoppingToken)
```

we also get:
```c#
public StringAsTempFile(Stream content, CancellationToken applicationStoppingToken)
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We have deprecated NodeServices in .NET 3.0 and then removed in .NET 5 per https://github.com/aspnet/Announcements/issues/379.
Having said that, we don't plan to add new features to older supported version of the framework.
