### ISSUE TITLE
Blazore Webaasembly 3.01: Passing complex Object as Route Parameters

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#26010]
When in try to pass complex object as parameter, it just passes the typename of the Object. 
What are the options to pass in complex Object when navigating to different component/page ?

This is what i have tried @page "/showLocation/{SelectedOrgLocation}"

Page which is sending information navManager.NavigateTo($"ShowLocation?SelectedOrgLocation={data}");

**Comment by chrissainty** [comment]
The URL is just a string, you can't pass complex objects that way. Instead you could use a state service or perhaps pass the identifier of the object such as an ID and then retrieve it on the destination page.

**Comment by mkArtakMSFT** [comment]
Thanks for your answer, @chrissainty.

**Comment by chrdlx** [comment]
I guess you could serialize {data} to JSON, and encode it in base64 for the URL.....  then do the opposite to recover it from the URL.
