### ISSUE TITLE
Add EventSource/EventCounter tracing and metrics for ResponseCaching

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2601]
_From @anurse on Wednesday, November 1, 2017 3:15:24 PM_

Some events listed below. The goal is to find issues that will help users solve problems so if these aren't going to do that job, feel free to suggest/discuss others!

* `Microsoft-AspNetCore-ResponseCaching` EventSource
    * `CacheSets` - Counts the number of created items
    * `CacheRemoves` - Counts the number of explicitly removed items
    * `CacheHits` - Counts the number of successful cache lookups
    * `CacheMisses` - Counts the number of failed cache lookups
    * Eviction? Where does it happen and can it be tracked here?
 
See https://gist.github.com/anurse/af1859663ac91c6cf69c820cebe92303 for some guidance on adding EventSources and EventCounters to ASP.NET projects.

_Copied from original issue: aspnet/ResponseCaching#141_

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
