### ISSUE TITLE
SignalR - Javascript Client - Access-Control-Allow-Credentials Required

### ISSUE THREAD

**Issue by ilushka85** [dotnet/aspnetcore#26011]
We are using the Javascript client and on the Azure side have a function app tied to SignalR Service.

We need to have allowed Origin be: * as it is a white label solution with custom domains per client.

The problem is that the current Javascript Client for SignalR forces the use of Access-Control-Allow-Credentials which will not allow a * origin.  Is there a way to make the javascript client not force:  Access-Control-Allow-Credentials ?

**Comment by eugeneogongo** [comment]
Hi @ilushka85 ,

The CORS is implemented by the browser by default as a security mechanism. There is workaround if your backend is implemented using Asp.net core.
Below is a code snippet of how to declare your CORS. The code doesn't require you to list accepted origins.

```
  builder.Services.AddCors(x => x.AddPolicy(name: "CorsRule", pb =>
                pb.AllowAnyHeader()
                    .AllowAnyMethod()
                    .SetIsOriginAllowed(_ => true)
                    .AllowCredentials()
            ));
```

**Comment by ilushka85** [comment]
But its not just about CORS... its specifically about Access-Control-Allow-Credentials. why can't Access-Control-Allow-Credentials be set to off for this library as a configuration option when using it? If the host does not support it?

**Comment by eugeneogongo** [comment]
Under the hood, SignalR uses cookies. Credentials must be allowed in order for cookie-based sticky sessions to work correctly. They must be enabled even when authentication isn't used.

**Comment by BrennanConroy** [comment]
In 5.0 an option was added to the client to disable credentials.
https://docs.microsoft.com/aspnet/core/signalr/configuration?view=aspnetcore-5.0&tabs=javascript#configure-additional-options

Make sure you aren't relying on Cookies if you enable this.

**Comment by ilushka85** [comment]
So it says it must be enabled for Azure App Service what about Azure Function with SignalR Service?   How do we resolve the need for any domain access while using azure function + SignalR.   I know the workaround exists for regular .net core app but that workaround can't be used for azure function

**Comment by BrennanConroy** [comment]
> must be enabled for Azure App Service

It should probably be rephrased a bit. It's required on App Service if you're using multiple instances. Since you're using the SignalR Service it makes the client sticky with the query string.

**Comment by ilushka85** [comment]
So if I am to understand we can disable authentication and since we are using AzureFunction + SignalR service it will work just fine?

**Comment by BrennanConroy** [comment]
I'm not sure why you're including Functions in this issue. CORS is a browser feature and I don't think Functions runs in a browser.

**Comment by ilushka85** [comment]
I am including functions since right now to have it work we had to enable authentication for cors on Azure Functions for the client side library to work and because its enabled we have to specify the domain in azure functions cors list

**Comment by BrennanConroy** [comment]
Oh I see, I thought you were connecting to an app in Azure App Service. Azure Functions != Azure App Service, so yes, you're fine disabling credentials with Functions (unless you're wanting to include your own cookie information of course).
