### ISSUE TITLE
Request for blazor.boot.json returns 404 when running the default Blazor WebAssembly template 

### ISSUE THREAD

**Issue by Shivonpvyshak** [dotnet/aspnetcore#26022]
### Describe the bug
I was working on Blazor Web assembly projects and was working fine until i upgrade my Microsoft Visual Studio Enterprise 2019
to Version 16.7.3. After then when ever i ran my  Blazor Web Assembly project i was getting a 404 

### Exceptions (if any)
SyntaxError: Unexpected end of JSON input
at Object. (http://localhost:44394/_framework/blazor.webassembly.js:1:30734)
at http://localhost:44394/_framework/blazor.webassembly.js:1:30237
at Object.next (http://localhost:44394/_framework/blazor.webassembly.js:1:30342)
at i (http://localhost:44394/_framework/blazor.webassembly.js:1:29088)

### Further technical details
I was referring to the thread https://github.com/dotnet/aspnetcore/issues/13166 and i tried all the resolution steps mentioned, but none worked in my case.

So at-last i tried below steps and that resolved my issue. Am writing this for helping  anyone else who have similar issue 

Resolution - Cleared the Nuget Package Manager Cache

Under Menu - Tools ->Options-> Nuget Package Manager ->Clear All NUGet Cache(s)

This resolved my issue. Hope this will help who have similar issue

**Comment by mkArtakMSFT** [comment]
Thanks for sharing your experience, @Shivonpvyshak.
We will keep an eye on similar issues in case more people hit it. For now we're closing this.
