### ISSUE TITLE
VaryByCustom

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2602]
_From @AdnanCukur on Wednesday, October 25, 2017 12:21:13 AM_

I have a Claim in my ClaimsPrincipal object, it contains a boolean, and I need the response cache to vary by this boolean. 

In MVC 5 I could easily do this with a VaryByCustom string, but I can't figure out how to solve this issue in .NET Core, is this feature missing ?

_Copied from original issue: aspnet/ResponseCaching#140_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, October 25, 2017 5:24:28 AM_

This has not been implemented. The only extension beyond HTTP caching is VaryByQueryKeys.

**Comment by JunTaoLuo** [comment]
This will be considered as part of the work on OutputCaching: https://github.com/dotnet/aspnetcore/issues/27387.
