### ISSUE TITLE
Option to have blazor app being the first descendant of body without removing body content

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#26035]
I want to have an option to place my blazor app being the first child on the body tag.

With current bits, when using builder.RootComponents.Add("#app") you end with 
```
<html>
<body>
    <div id="app"> // (I want app to be here)
         <-- app razor component here
    </div>
    <scripts ... />
</body>
</html>
```
instead if we can "replace" the div with id app we can have the root element be part of the app so we can have app.css and get scoped support and have better control on the output html.

so I can set the div inside app.razor:
```
<div id="app">
<Router AppAssembly="@typeof(Program).Assembly">
   ... 
</Router>
</div>
```
```
<html>
<body>
    <div id="app" b-f75xsoxj3z> <--  app razor component

    </div>
    <scripts ... />
</body>
</html>
```
Proposed api may be `builder.RootComponents.Add("#app", replaceElement: true);` 

another way could be using a html comment placeholder instead of an actual element, similar to <text> for razor.

**Comment by mrpmorris** [comment]
You achieve this by editing App.razor and wrapping the contents in a `<div>` with whatever class or Id you wish.

**Comment by Bartmax** [comment]
I want to be the first child of body.

I dont want:
`<body><div id="app"><div id="app-real"></div></div></body>`

**Comment by captainsafia** [comment]
Thank you for your feedback. We don't plan on modifying any APIs in Blazor to support this.

We recommend leveraging some of the component tag helpers that are used to support pre-rendering scenarios to implement your scenario, in addition to some of the solutions discussed in the thread.

**Comment by Bartmax** [comment]
what's the reason for not supporting app as first child of body ? Why we need to bloat the html with unneeded tags?

**Comment by mrpmorris** [comment]
In .NET 5 you can set `id=App` on the element you want to be the app element. I'm not sure if there is something wrong with this or not, but I set the id of `<body>` to `app` and it worked.

**Comment by Bartmax** [comment]
the problem setting `body` is that it gets replaced everything that's is inside.
so:
```
<body id="app">
<div id="blazor-error"> .... </div>
<script src="..."/>
</body>
```
the script tag (and everything inside the body) is removed, hence my proposal to replace the inner tag instead of append.
I honestly think it should be the default behavior. The option to use an html comment tag will also works `<!--#app -->`
