### ISSUE TITLE
Controllers in class library being exposed without calling AddApplicationPart

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#26034]
### Describe the bug
I have an asp.net core project (netcoreapp3.1) which references a class library that has other controller that I do not want exposed. My understanding is only controllers in the entry dll will be wired up unless AddApplicationPart is called with the assembly of the other controllers. This does not appear to be happening as all the controllers in all referenced libraries are being wired up and can be called from the one application.

### To Reproduce
My add controllers call is here. Nowhere do I call AddApplicationPart

```
services.AddControllers(op =>
                {
                    //work around for https://github.com/RicoSuter/NSwag/issues/2328
                    foreach (var formatter in op.OutputFormatters
                        .OfType<ODataOutputFormatter>()
                        .Where(it => !it.SupportedMediaTypes.Any()))
                    {
                        formatter.SupportedMediaTypes.Add(
                            new MediaTypeHeaderValue("application/prs.mock-odata"));
                    }
                    foreach (var formatter in op.InputFormatters
                        .OfType<ODataInputFormatter>()
                        .Where(it => !it.SupportedMediaTypes.Any()))
                    {
                        formatter.SupportedMediaTypes.Add(
                            new MediaTypeHeaderValue("application/prs.mock-odata"));
                    }
                }).AddJsonOptions(o =>
                {
                    //preserve poco casing
                    o.JsonSerializerOptions.PropertyNamingPolicy = null;
                });
```

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by pranavkm** [comment]
> My understanding is only controllers in the entry dll will be wired up unless AddApplicationPart is called with the assembly of the other controllers. This does not appear to be happening as all the controllers in all referenced libraries are being wired up and can be called from the one application.

MVC attempts to discover and find controllers from all projects that are referenced by the entry assembly. `AddApplicationPart` is meant as way to include assemblies that aren't referenced by the app. There isn't much in terms of a feature to prevent an assembly from being discovered. However you should be able to remove it after the fact using `ConfigureApplicationManager`:

```C#
services.AddControllers(...).ConfigureApplicationPartManager(partManager => /* Remove parts here */);
```

**Comment by groogiam** [comment]
That did the trick. Thanks for your help.
