### ISSUE TITLE
Blazor pseudoelements when using a preprocessor

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#26044]
When using a sass preprocesor I found no way to use ::deep and pseudo selector to have an output rule like:

`button[b-fm2ddfvifg]:hover`

```
button {
  // ...
  & ::deep:hover {
    color: #212529;
   }
```

will create `button[b-fm2ddfvifg] :hover` rule (note the space between the attribute `[xxxx]` and `:hover`)

and if I leave the space out:

```
button {
  // ...
  &::deep:hover {
    color: #212529;
   }
```

the result rule will be: `button[b-fm2ddfvifg]::deep:hover` (`::deep` token not recognized) because I believe the `::deep` token needs an space before.

I also tried
```
button {
  // ...
  ::deep &:hover {
    color: #212529;
   }
```
but in this case, the output rule is: `[b-fm2ddfvifg] button:hover {`

Not sure if this (an similar scenarios) is fixed in https://github.com/dotnet/aspnetcore/pull/25270, sorry if that's the case.
But since this is using a preprocessor with token `&` i think it may be important to support `::deep` without an space.

**Comment by captainsafia** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by TanayParikh** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
