### ISSUE TITLE
Updating cached vary by rules need to set the correct expiration

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2605]
_From @JunTaoLuo on Monday, July 10, 2017 3:32:32 PM_

Currently it uses the expiration information from the newer entry but this is incorrect since the entry being replaced may have a longer expiration. This could potentially lead to the situation where a valid cached response remains in the cache but the vary by rule entry that is used to retrieve it is expired and removed from the cache.

_Copied from original issue: aspnet/ResponseCaching#133_

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
