### ISSUE TITLE
.Net core Identity lockout, not working expected

### ISSUE THREAD

**Issue by iozcelik** [dotnet/aspnetcore#26054]
I try to enable lockout feature but I am not successed. Each time, I check database, AccessFailedCount is increase to 1 but after that again it turn to 0. What's wrong?

My codes are:

```
//Login page code

    public async Task<IActionResult> OnPostAsync(string returnUrl = null) {
        returnUrl = returnUrl ?? Url.Content("~/");

        if (ModelState.IsValid) {

            var result = await _signInManager.PasswordSignInAsync(Input.UserName, Input.Password, Input.RememberMe, lockoutOnFailure: true);
            if (result.Succeeded) {

                _logger.LogInformation("User logged in.");
                return LocalRedirect(returnUrl);
            }
            if (result.RequiresTwoFactor) {
                return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
            }
            if (result.IsLockedOut) {
                _logger.LogWarning("User account locked out.");
                return RedirectToPage("./Lockout");
            }
            else {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return Page();
            }
        }

        // If we got this far, something failed, redisplay form
        return Page();
    }


//services code 
// Lockout settings.
options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
options.Lockout.MaxFailedAccessAttempts = 2;
options.Lockout.AllowedForNewUsers = true;
```

- `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- Visual Studio 2019 (16.7.3)

**Comment by blowdart** [comment]
What is your actual flow here? That is, what are you doing? 
Are you just typing in the wrong username and password again and again or something else? 
Is multi-factor auth enabled for the user you're testing?

And what version of asp.net core and asp.net core identity are you using?

**Comment by iozcelik** [comment]
In debug mode, I am testing and just use wrong password only. Username is true and find user. Because when I look database AccessFailedCount change. 

Multi factor is not enabled. 

<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />

Asp.net core is 3.1.8. Dotnet info is not enough for that. Actually every package is lastest. Because it is test project. I recently created.

**Comment by blowdart** [comment]
When you create the test project. which version are you targeting? You have 3.1 installed, but your identity is from 2.2.x, which is a no-longer supported version. We've had some instances of lockout not happening, which have been fixed previously, so I'm trying to rule those out.

**Comment by iozcelik** [comment]
Ok, I see then Visual studio has a bug. Because I select find and install lastest package. And I target .net core 3.1. Not install identity package manually.

**Comment by blowdart** [comment]
Ah no, it's not a bug. 3.x includes a lot of packages as part of the target selection. You don't need packages for identity, and security, and lots of other things, they're just there, you don't need to find and install.

**Comment by iozcelik** [comment]
@blowdart however in that case I have all 2.2.x package for identity and as you said some of them came default. I scaffolded items so I need to add other packages but that time I just select find and install lastest package. At nuget there is no higher version of Identity package.

![image](https://user-images.githubusercontent.com/10682780/93634759-d1305500-f9f9-11ea-9333-1f628953069d.png)

**Comment by blowdart** [comment]
Scaffolding shouldn't do that, and no packages should be in a clean application.

@deepchoudhery @vijayrkn do you have any ideas what could be causing this?

**Comment by iozcelik** [comment]
Ok, I open all new project. Clear everything. I look up database carefully and I see lockout date ise set but not lockout column.
![image](https://user-images.githubusercontent.com/10682780/93660490-2d29c680-fa58-11ea-87d4-77607e4210df.png)
Lockout enddate in UTC. My timezone is UTC+3. So the time is 09:13. That mean five minutes later after my wrong login attemps.

**Comment by iozcelik** [comment]
I understand why that happened. I change setting after added user, so it does not effect existing users.

**Comment by blowdart** [comment]
OK, so does this happen before your customization or after? Lockout end dates far in the past are absolutely fine. Those columns don't clear.

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
