### ISSUE TITLE
App.razor conflicts namespace App.XYZ

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#26051]
I'm trying to integrate Blazor-Server into my existing MVC project.

The problem is, that my namespaces starts with "App.XYZ".

So when I add the "App.razor" file to my project root, I get tons of errors that "App" is a type and not a namespace.

Obviously I could do "global::App.XYZ" but that's pretty ugly IMO.

**Is there a way to change the default name for "App.razor"?**

**Comment by SteveSandersonMS** [comment]
Yes, you can rename App.razor to anything else, such as Root.razor. Then replace references to the type App with the new type name Root.
