### ISSUE TITLE
Microsoft.AspNetCore.App.Ref 3.1.8 doesn't contain System.IO.Pipelines.xml: missing API docs

### ISSUE THREAD

**Issue by dagood** [dotnet/aspnetcore#26068]
### Describe the bug
https://www.nuget.org/packages/Microsoft.AspNetCore.App.Ref/3.1.8 doesn't contain `System.IO.Pipelines.xml`, even though it has `System.IO.Pipelines.dll`. My understanding is this leaves users without documentation when they use `System.IO.Pipelines` through ASP.NET Core.

https://www.nuget.org/packages/System.IO.Pipelines/4.7.2 does have this doc XML file in it, so this may just be an issue with how the XML files are redistributed by ASP.NET.

There are also a number of other files in the package without matching XML files, but I'm assuming that's the same issue.

@omajid originally reported this at https://github.com/dotnet/source-build/issues/1686, I'm filing this to track an upstream fix. Once it's fixed in an updated targeting pack, we'll uptake in source-build in the same servicing cycle.

### To Reproduce

Download the nupkg (zip), open it, look in `ref\netcoreapp3.1\`. This also shows up when you install the SDK in e.g. `C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1`:

```
#> ls 'C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\*.dll' | %{ $_.FullName.Replace('.dll', '.xml')} | ?{ -not (test-path $_) }
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\Microsoft.Win32.Registry.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Diagnostics.EventLog.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.IO.Pipelines.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Security.AccessControl.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Security.Cryptography.Cng.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Security.Cryptography.Xml.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Security.Permissions.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Security.Principal.Windows.xml
C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.8\ref\netcoreapp3.1\System.Windows.Extensions.xml
```

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/26146
