### ISSUE TITLE
Error getting value from 'TempData' 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26080]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1181062/error-getting-value-from-tempdata.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:16.7.2]
when I run a rest endpoint with 3 or more levels in the url. 
**ex:** https://localhost:4003/v1/first/second/third or: https://localhost:4003/v1/first/second/{id}
**like this works fine:** https://localhost:4003/v1/first/second or: https://localhost:4003/v1/first/{id}
It started after I upgraded to version **16.7.3** my co-workers on version **16.7.2** or below works normal

---
#### Feedback Bot on 9/10/2020, 10:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
