### ISSUE TITLE
Add options for cookie handling

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2609]
_From @gpeipman on Wednesday, March 8, 2017 2:56:24 AM_

It would be nice if there are options for cookies handling. Two things I can propose:

1. Option to ignore all cookies (they are often used for client-side stuff only in public sites)
2. Option to give names of cookies to ignore

Second option is specially important as currently it is not possible to use Application Insights with response caching as AI uses cookies when browser-side diagnostics are enabled. I think in this case request cookies must be just copied to response to not delete them.

_Copied from original issue: aspnet/ResponseCaching#113_

**Comment by aspnet-hello** [comment]
_From @JunTaoLuo on Wednesday, March 8, 2017 11:31:11 AM_

This could be useful. It would be another reason we need https://github.com/aspnet/ResponseCaching/issues/52.

**Comment by aspnet-hello** [comment]
_From @gpeipman on Sunday, March 12, 2017 1:36:48 AM_

I made copy of classes in 1.1 branch to my prototype solution and commented out the check for cookie header. Application Insights started working after this.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, March 17, 2017 3:58:53 PM_

Doesn't ResponseCaching already ignore all Set-Cookie headers?

**Comment by aspnet-hello** [comment]
_From @gpeipman on Saturday, March 18, 2017 5:17:51 AM_

It doesn't ignore these. It doesn't cache if this header is present.

**Comment by aspnet-hello** [comment]
_From @RehanSaeed on Tuesday, July 18, 2017 9:21:14 AM_

https://github.com/aspnet/ResponseCaching/issues/128 is related. No caching also occurs if the Authorization HTTP header is present.

My proposal is that when the Authorization HTTP header is present, the cached entry should be taken, the Authorization and Set-Cookie HTTP headers on it should be updated from the current request and the response returned. #52 would mean we could do this ourselves but I think the above should be built in to the middleware.

**Comment by JunTaoLuo** [comment]
We'll look into this scenario when planning for Output Caching: https://github.com/dotnet/aspnetcore/issues/27387
