### ISSUE TITLE
VS removes newly created files in csproj when including extra extensions to watch

### ISSUE THREAD

**Issue by zHaytam** [dotnet/aspnetcore#26097]
### Describe the bug
I have a Blazor WASM project and I'm using `dotnet watch run`. In order to reload the project when other types of files are changed (css, cs, ...), I added the following snippet:
```
<ItemGroup>
    <Watch Include="**\*.js;**\*.css;**\*.cs;**\*.razor;**\*.html" />
</ItemGroup>
```
The problem now is that everytime I create a new file with one of the extensions above (e.g. Test.razor or Test.razor.css), I get the following entries added to my csproj file, which stops the application from running:
```
<ItemGroup>
    <Content Remove="Components\Test.razor" />
  </ItemGroup>

  <ItemGroup>
    <Watch Remove="Components\Test.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\Test.razor" />
  </ItemGroup>
```

### To Reproduce

1. Create a new Blazor WASM project (using .NET 5 rc1)
2. Add the above `<Watch ... />` entry
3. Try to create new files

### Further technical details
- SDK: 5.0.100-rc.1.20452.10
- IDE: Visual Studio 2019 Version 16.8.0 Preview 3.0

**Comment by pranavkm** [comment]
We might have to use an attribute on `Content` to make this work (e.g. `<Content Update=".." Watch="true" />`). In the meanwhile, you might be able to make this work by registering these items inside of a target:

```xml
<Target Name="AddMyWatchItems BeforeTargets="GenerateWatchList">
  <ItemGroup>
    <Watch Include="**\*.js;**\*.css;**\*.cs;**\*.razor;**\*.html" />
   </ItemGroup>
</Target>
```
