### ISSUE TITLE
It becomes empty app tag in WebAssemblyPrerendered 

### ISSUE THREAD

**Issue by MeysamMoghaddam** [dotnet/aspnetcore#26094]
I want to use WebAssemblyPrerendered but when i put in render-mode="WebAssemblyPrerendered", app tag It becomes empty after load.How do I solve it?

![to-gif](https://user-images.githubusercontent.com/65253484/93665935-8a8d3a00-fa8f-11ea-855b-172f94336592.gif)

**Comment by MeysamMoghaddam** [comment]
Tnx
Resolved This Issue 
https://github.com/dotnet/aspnetcore/issues/25971#issuecomment-694927576

**Comment by mkArtakMSFT** [comment]
Thanks. Glad that you were able to resolve your issue.
