### ISSUE TITLE
[Blazor] Another script error when using Blazor Server with Edge 44

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#26090]
Similar to https://github.com/dotnet/aspnetcore/issues/25874 (Edge version 44) but the location of the script error is different.

blazor.webassembly.js (1,1723)

This worked in .NET Core 3.1, but the vanilla Blazor Wasm app (I also selected PWA) made with .NET 5 RC1 fails with the above error.

**Comment by SteveSandersonMS** [comment]
Verified it's the same issue as #25874:

![image](https://user-images.githubusercontent.com/1101362/93754465-b1677f80-fbf9-11ea-935b-33af8d95f835.png)

![image](https://user-images.githubusercontent.com/1101362/93754506-c217f580-fbf9-11ea-9145-041f5d9c70d8.png)

Closing as duplicate
