### ISSUE TITLE
Multiple Google Auth Doesn't

### ISSUE THREAD

**Issue by solkh** [dotnet/aspnetcore#26103]
I need to use 2 Google Auth for my ASP Core 3.1 website:
1- simple sign in using Google (for simple users)
2- sign in using google with google drive scopes (for admins only)

But Google Auth returns with an error for the second registered google Auth client
_The same code used to work fine one ASP Core 2.2_

Here is my code at Startup.cs:
```
services.AddAuthentication()
	.AddGoogle("Google", o =>
	{
		// Google sign in
		o.ClientId = "ClientId1";
		o.ClientSecret = "ClientSecret1";
		o.AccessType = "offline";
		o.SaveTokens = true;
		//...
	})
	.AddGoogle("Google2", o =>
	{
		// Google sign in for drive syncing
		o.ClientId = "ClientId2";
		o.ClientSecret = "ClientSecret2";
		o.AccessType = "offline";
		o.SaveTokens = true;
		o.Scope.Add(DriveService.Scope.Drive);
		o.Scope.Add(DriveService.Scope.DriveFile);
		//...
	});
```

Here is the code for requesting the external auth:
```
public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = provider == "Google2" ? Url.Action(nameof(AddGoogleLoginCallback), "Account", new { returnUrl }, Request.Scheme) : Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl }, Request.Scheme);
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }
```

### Exceptions
I get this exception after authentication and redirecting to /signin-google, whenever I try to authenticate the user for the second google client only (in this case "Google2"), the first one works fine.

```
An unhandled exception occurred while processing the request.
Exception: The oauth state was missing or invalid.
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

### Further technical details
- ASP.NET Core version 3.1
- VS Enterprise 2019 16.7.3

**Comment by Tratcher** [comment]
Start by setting the o.CallbackPath to a unique value for each instance. Something like `/signin-google-drive`.

**Comment by solkh** [comment]
It worked !
Thanks a lot
