### ISSUE TITLE
[Blazor] File new Net5 Blazor WASM project with VS Preview throws an exception on F5

### ISSUE THREAD

**Issue by sturlath** [dotnet/aspnetcore#26108]
Vanilla F5 run of the NET 5 Blazor WASM project throws an error and can´t be run.

### Describe the bug
Without changing any code at all I get the following exception
`System.ArgumentNullException: 'Value cannot be null. Arg_ParamName_Name'`

```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0-rc.1.20451.14\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: No output has been recevied from the application.
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
   at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.0-rc.1.20451.17\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.0-rc.1.20451.17\Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0-rc.1.20451.14\System.Net.WebSockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0-rc.1.20451.14\System.Security.Principal.Windows.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
An unhandled exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.dll
Value cannot be null.
```
Here is how it looks like in Visual Studio
![image](https://user-images.githubusercontent.com/2386572/93711416-a94a0a00-fb3d-11ea-9509-66b8feb33431.png)

### To Reproduce
1. File new Blazor .NET 5 project in VS Community 2019 Preview (no code change)
2. Check ASP.NET Core hosted
3. Press F5

I have done this a few times and I always get the same result.

Here are some logs [BlazorLogFile.txt](https://github.com/dotnet/aspnetcore/files/5251675/BlazorLogFile.txt)

### Further technical details
Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 3.0
VisualStudio.16.Preview/16.8.0-pre.3.0+30509.190
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   16.8.440.34356
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2045103+0e85a8dca3c03eb94268b98270319e79ce608a48
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.440.34356
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.440.34356
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.440.34356
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.8.31 (e09a7a8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Reset Tool Windows   1.0.11
Collapse all tool windows except the ones you really need visible and gain 10-33% faster Visual Studio startup times and a fresh starting point every day.

SQL Server Data Tools   16.0.62009.04150
Microsoft SQL Server Data Tools

Syncfusion ASP.NET Core Project Templates   16.1.0.32
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion ASP.NET Core components.

Syncfusion ASP.NET Core Project Templates   18.2.0.44
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion ASP.NET Core components.

Syncfusion Xamarin Project Templates   13.4.0.53
A multi-project template for building iOS, Android, and Windows apps using Syncfusion Xamarin components.

Syncfusion Xamarin Toolbox   16.2.0.19
Syncfusion Essential Studio for Xamarin Toolbox Visual Studio extension.

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

TypeScript Tools   16.0.20902.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20428.2+068ebd3c599bc5a47163a18b8b90d2fe5517186e
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.202 (master@c843c47)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.471 (remotes/origin/d16-8@ce5800ecd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.99 (898d8e1)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.3 (d16-8/b352be8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-8@a807961
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   13.22.1.23 (8318026f1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Pre-requisite checklist
- [x] Steps to reproduce the issue
- [x] Razor Language Server client logs included.
- [ ] HTML Language Server client logs included

**Comment by campersau** [comment]
See https://github.com/dotnet/aspnetcore/issues/25897#issuecomment-692755051

**Comment by sturlath** [comment]
Clean/rebuild and shutting VS down doesn't change anything **BUT** if I restart my computer it works for the first time but **NOT** after that. Could this be some process that's interfering?

**Comment by campersau** [comment]
Here are more details https://github.com/dotnet/core/issues/5200#issuecomment-692361736 and a workaround https://github.com/dotnet/aspnetcore/issues/25887#issuecomment-693487470

**Comment by sturlath** [comment]
Ok thank you @campersau ! The workaround works perfectly thank you. Closing this issue now.
