### ISSUE TITLE
Asp Net Core with Signalr not allowing clients beyond 5000 concurrent users

### ISSUE THREAD

**Issue by Gopichandar** [dotnet/aspnetcore#26106]
I have hosted a Asp Net Core Site in a Kestrol,  I have configured the IIS with reverse proxy to Kestrol server.  Wehn I try to do a stress test on the server by simulating multiple clients, It was not going beyond 5000 requests.  

Here is the Http error that I get.

Status:  503.2 Concurrent request limit exceeded. 
URL:  http://..../signalr/negotiate?negotiateVersion=1

How to increase the limit?

Framework:  .Net Core 3.1.8
Hosted in Kestrol Reverse proxy with IIS
Server:  Windows Server 2012 R2
IIS version : 8.5

**Comment by BrennanConroy** [comment]
You need to increase the concurrent limit in IIS
https://github.com/SignalR/SignalR/wiki/Performance#max-concurrent-requests-per-application

For AspNetCore: We should add some logs about this

**Comment by Gopichandar** [comment]
> We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

I wonder why there is restriction in IIS.  Anyway, thanks for the guidance.
