### ISSUE TITLE
SegmentReadStream should override CopyTo when available

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2610]
_From @JunTaoLuo on Tuesday, February 7, 2017 4:42:26 PM_

In https://github.com/dotnet/corefx/issues/11342 `CopyTo` was made virtual. We should override this with the same logic as `CopyToAsync` to avoid the unnecessary calls to `Read` in the `SegmentReadStream`.

_Copied from original issue: aspnet/ResponseCaching#105_

**Comment by JunTaoLuo** [comment]
SegmentReadStream has long been removed.
