### ISSUE TITLE
WebSocket ReceiveAsync hangs forever on server

### ISSUE THREAD

**Issue by gdalsnes** [dotnet/aspnetcore#26117]
NetCore\AspNetCore 3.1.8
Kestrel, running in debug
Simple example, middleware doing
var ws = await context.WebSockets.AcceptWebSocketAsync();
await ws.ReceiveAsync(buff, CancellationToken.None);

Client connect:
var ws = new ClientWebSocket();
await ws.ConnectAsync(new Uri("ws://host/ws/test"), CancellationToken.None);
await ws.ReceiveAsync(buff, CancellationToken.None);

Pull out network cable. After a while, client throws WebSocketException (as expected).
But server is "blocking" on ReceiveAsync forever. Seems there is something wrong with the pingpong logic? Pingpong is keeping the client alive but server does not care when client stops responding to pingpong and will Recieve forever in vain. I don't see how WebSocket can be usable in real life with this behaviour?

**Comment by gdalsnes** [comment]
After being assigned area-websockets I see 3 other cases complaining about the same and being closed.
In any case, this is higly inconsistent that the client actually closes while the server does not. And can accept it if you also change the client to also hang forever:-D

**Comment by wanton7** [comment]
I've been battling with problem that in client (a Chrome brower on Windows 10) when .close() doesn't seem to do anything. After that .close call WebSocket connection will timed out in about 60 seconds so it will end at some point with exception "Unexpected Message". RequestAborted CancellationToken is also not set at all.

**Comment by BrennanConroy** [comment]
Triage notes: The WebSocket on the server side will send Pings every 2 minutes by default. The problem is that the RFC doesn't say that you should kill the connection if a Pong isn't received in response to a Ping so the WebSocket is just going to stay open. If you wait for the TCP timeout (which could be 15+ minutes on Windows) then you will see that the WebSocket is closed at that point.

We are tracking this sort of issue in https://github.com/dotnet/aspnetcore/issues/24614

**Comment by gdalsnes** [comment]
> 
> 
> If you wait for the TCP timeout (which could be 15+ minutes on Windows) then you will see that the WebSocket is closed at that point.
> 
My observations are different. After pulling plug, ClientWebSocket timeout after approx 30 seconds. Server\Kestrel never time out (I waited for hours). This may be related to the different socket options used in client and Kestrel. It may be problematic with leaking resources that a WebSocket never timeout, neither via socket options nor via pingpong. So to me this seems like a double fault.
Client error:
```
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
```
