### ISSUE TITLE
Default authentication scheme not being honoured

### ISSUE THREAD

**Issue by YuKitsune** [dotnet/aspnetcore#26119]
### Describe the bug
When specifying a default authentication scheme in the `Startup.ConfigureServices()` method, the specified scheme is not honoured when authenticating.

### To Reproduce

Startup.cs:
```cs
public void ConfigureServices(IServiceCollection services)
{

    services.AddIdentity<ApplicationUser, IdentityRole>(
        options =>
            {
                // Options omitted for simplicity
            })
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultTokenProviders();
    
    // Using JWT as an example
    services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(
        options =>
            {
                // Options omitted for simplicity
            });
}
```

AccountController.cs:
```cs
[Authorize]
public class AccountController : Controller
{
    // Actions omitted for simplicity
}
```

Despite `JwtBearerDefaults.AuthenticationScheme` being specified as the default authentication scheme in the startup file, cookies are still used, and I'm unable to use JWT Bearer Tokens to authenticate. Attempting to authenticate with a JWT retults in a 405 response.

Logs from invoking `/Account`:
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Identity.Application was challenged.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 9.5928ms 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5001/Account/Login?ReturnUrl=%2FAccount
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '405 HTTP Method Not Supported'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '405 HTTP Method Not Supported'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 8.7565ms 405
```

### Interim solution
The easiest workaround is to specify the authentication scheme in the `AuthorizeAttribute` on each Controller or Action:
```cs
[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
public class AccountController : Controller
{
    // Actions omitted for simplicity
}
```

Logs from invoking `/Account` with the scheme specified in the `AuthorizeAttribute`:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:5001/Account
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
```

This serves as a quick workaround, but does not solve the actual issue, and is impractical for my usecase.

### Further technical details
- ASP.NET Core version 3.1.8
- Output of `dotnet --info`
```
NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
    - Microsoft Visual Studio Community 2019 Version 16.6.2
    - JetBrains Rider 2020.2.3

I will link to a repo with eamples shortly

**Comment by YuKitsune** [comment]
I've created an example project reproducing the bug: https://github.com/YuKitsune/AspNetCore.AuthBug
Username: Administrator
Password: Password123!@#

Authenticating in works fine
<img width="1098" alt="Screen Shot 2020-09-21 at 9 22 17 pm" src="https://user-images.githubusercontent.com/25342760/93761094-88260e00-fc50-11ea-9f5e-dae6f0cf93d0.png">

There are two actions in the `HomeController` which require Authorization, `AuthRequired`, which just has `[Authorize]` on top, and `AuthRequiredSchemeSpecified`, which has `[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]`

### Without making any changes to Postman:

After calling `Authenticate`, a new Cookie is entered into Postman:
<img width="1098" alt="Screen Shot 2020-09-21 at 9 24 33 pm" src="https://user-images.githubusercontent.com/25342760/93761266-d89d6b80-fc50-11ea-88d8-1d3283f43ad5.png">

I can now send a request to `AuthRequired` without specifying a Bearer token:
<img width="1098" alt="Screen Shot 2020-09-21 at 9 25 28 pm" src="https://user-images.githubusercontent.com/25342760/93761332-f965c100-fc50-11ea-8c81-e021cb44de3e.png">

Sending a request to `AuthRequiredSchemeSpecified` yeilds a 401 response
<img width="1098" alt="Screen Shot 2020-09-21 at 9 25 52 pm" src="https://user-images.githubusercontent.com/25342760/93761373-084c7380-fc51-11ea-87dc-56398e610b12.png">

### After removing the cookie from Postman
After removing the cookie from Postman, `AuthRequiredSchemeSpecified` returns a 401 as expected:
<img width="1098" alt="Screen Shot 2020-09-21 at 9 28 39 pm" src="https://user-images.githubusercontent.com/25342760/93761616-6c6f3780-fc51-11ea-9a17-dd04c1d270f0.png">

But `AuthRequired` returns a 404 response...
<img width="1098" alt="Screen Shot 2020-09-21 at 9 28 56 pm" src="https://user-images.githubusercontent.com/25342760/93761642-76913600-fc51-11ea-9b95-9eeaf6a36924.png">

Once the Bearer token has been specified, `AuthRequired` still returns a 404, but `AuthRequiredSchemeSpecified` returns the expected result:
<img width="1098" alt="Screen Shot 2020-09-21 at 9 30 30 pm" src="https://user-images.githubusercontent.com/25342760/93761753-adffe280-fc51-11ea-90a0-d1e252f05c67.png">

#### Extra notes:
- In `Startup.cs:38`, the `configureOptions` parameter (`Action<JwtBearerOptions>`) does not get invoked until the first time a request it sent to `AuthRequiredSchemeSpecified`.

### Expected result
Given that in the `Startup.cs:37`, the default Authentication Scheme is being set to JWT Bearer, I would expect that both `AuthRequired`, and `AuthRequiredSchemeSpecified` would return a 401 (Unauthorized) response without any bearer token specified, and when a valid token is specified they would return a 200 (OK) response with the specified content.
Since that Is not the case, I believe there may be a bug when resolving the default authentication scheme when requests are received.

**Comment by blowdart** [comment]
services.AddIdentity() sets the default to cookies (and calls AddAuthentication behind the scenes). 

So, even if you try to set it again to JWT, cookies has already "won". This is by design, as AddIdentity is a helper that's doing a bunch of work for folks that don't want to know or care about setting up schemes, cookie auth, login pages and so on.

And we don't expect identity UI pages to work with JWT anyway, those are interactive browser pages, so JWT is not a suitable authentication scheme.

So, what is the actual scenario you are trying to achieve with multiple authentication schemes?

**Comment by YuKitsune** [comment]
I'm essentially trying to make a REST API which uses JWTs for authenticating users. I plan on having a Blazor, Xamarin, and WPF front-end eventually, so a REST API with ASP.NET Core Identity for the user management logic, and JWTs for authenticating would be really convenient in my use case.

Is there a different method I could call, other than `services.AddIdentity()` which will configure Identity services, but not pages and cookies? I know there is `services.AddIdentityCore()`, but that doesn't add any of the services.

Also, would it be worth mentioning that `services.AddIdentity()` invokes `AddAuthentication` and uses cookies by default in the documentation? Or even have an alternative method for using JWTs?

**Comment by blowdart** [comment]
In this case what I'd do is leave the default as cookies for identity and on your APIs specify JWT. There are multiple alternate ways for this.

1) In the authorize attribute

```
[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
```

2) In policy

```
services.AddAuthorization(options =>
{
    options.AddPolicy("Api", policy =>
    {
        policy.AuthenticationSchemes.Add(JwtBearerDefaults.AuthenticationScheme);
        policy.RequireAuthenticatedUser();
    });
});
```

3) With a virtual scheme, where you use code to pick which one you want.

```
services.AddAuthentication("VirtualScheme")
    .AddPolicyScheme(
        "VirtualScheme",
        "VirtualSchemeDisplayName",
        options =>
        {
            // Pick your scheme logic
            options.ForwardDefaultSelector = context =>
            {
                return "Scheme";
            };
         })
    .AddCookie(...)
```
4) Via scheme forwarding, where you put code to select in each individual scheme

```
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
  .AddCookie(options =>
  {
      // Forward any requests that start with /api to that scheme
      options.ForwardDefaultSelector = ctx => 
      {
          return ctx.Request.Path.StartsWithSegments("/api") ? "Api" : null;
      }; 
      ...
   });
```
But with all of that AddIdentity is always going to want user pages, even Identity Server uses Identity's user pages for user management, it's just the nature of it.

**Comment by YuKitsune** [comment]
I've had a bit of a dig around the code and realised that the `SignInManager` is meant for use with cookie authentication... 

In that case, I can use `services.AddIdentityCore()` along with `services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)`, and just change up some of the old `SignInManager` calls, and it all works as expected. 

I think updating the documentation to make it more clear, and maybe making a JWT specific SignInManager implementation which avoids using cookies might've helped. I'll make a PR shortly!

**Comment by blowdart** [comment]
SignInManager is for ASP.NET Identity. There's no support for JWT in Identity. So making a SignInManager, or indeed anything else that is identity linked for JWT makes no sense from a product POV I'm afraid. Documentation updates sure, SignInManager PRs, no, please don't spend any time on it.

**Comment by YuKitsune** [comment]
Ah, okay. I think I've misunderstood the scope of ASP.NET Identity. Happy for this to be closed instead.
