### ISSUE TITLE
PreServed Data In Blazor WebAssembly

### ISSUE THREAD

**Issue by MeysamMoghaddam** [dotnet/aspnetcore#26118]
Hello, I hope you are happy 💯 
how can I serve big Data(from api request) for clients look like twitter Home page that wherever you go, nothing has changed when you return (not init and render again)

I do not want to Component reinitialize Or Dispose
Is there a principled way?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We recommend using some cache service, which will hold the data you want to keep between navigation events and when navigating back to the component you're interested in, re-draw the UI using pre-cached data from that service. https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1&pivots=webassembly

**Comment by MeysamMoghaddam** [comment]
What do you mean by re-draw the UI?
If the data is large, it will take a long time to load when it returns!!:(

**Comment by MeysamMoghaddam** [comment]
This issue has been resolved!!!!!!  How about?

**Comment by captainsafia** [comment]
We don't provide support for this feature out of the box in Blazor.

In addition to caching, you'll likely want to leverage JS interop to retrieve the scroll position before the user navigates away, store in in local storage, then read from the stored value and programmatically scroll to it when the user returns to the page.
