### ISSUE TITLE
Blazor-Server: Remove InputFile (StateHasChanged) before file.OpenReadStream()

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#26112]
Full test-project:
https://github.com/alienwareone/BlazorServerFileUploadProgressTest

`"Cannot read property '_blazorFilesById' of null TypeError: Cannot read property '_blazorFilesById' of null at a..."`

https://github.com/alienwareone/BlazorServerFileUploadProgressTest/blob/master/BlazorServerFileUploadProgressTest/Pages/FileUpload.razor#L30-L36

I also added a workaround for this problem:
https://github.com/alienwareone/BlazorServerFileUploadProgressTest/blob/master/BlazorServerFileUploadProgressTest/Pages/Workaround.razor#L31-L35

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There is no support for removing the InputFile before reading it. The workaround you've used is reasonable.
