### ISSUE TITLE
Blazor: Server Side, Render issue after SQL Server OpenAsync throws Exception

### ISSUE THREAD

**Issue by WayneHiller** [dotnet/aspnetcore#26114]
I Have run into a strange Rendering issue after a call to the SQL Server SqlConnection OpenAsync call throws an Exception.

VS version 16.7.3

I changed the Default Blazor project Counter page to this to reproduce.

```
@page "/counter"

<h1>DB Connection Test</h1>

<div>
    @msg
</div>
<br />
<button @onclick="DbConnectAsync">
    DB Connect Aysnc
</button>

@code {
    private string msg = "Ready";

    private async Task DbConnectAsync()
    {
        try
        {
            msg = "Connecting...";
            var cn = new System.Data.SqlClient.SqlConnection("Data source=.\\None;Connection Timeout=5");
            await cn.OpenAsync();
        }
        catch(Exception x)
        {
            msg = x.Message;
        }
    }
}

```

The first click on the button correctly updates the UI, a second click will not update the UI, the third click will. Wait at least 5 seconds between clicks.

I have tried with other types of Exceptions and they did not have this issue.

**Comment by mkArtakMSFT** [comment]
This doesn't look Blazor specific.
@ajcvickers do you happen to know what may cause this behavior?

**Comment by mkArtakMSFT** [comment]
@WayneHiller can you share more details about what your'e trying to accomplish?

**Comment by WayneHiller** [comment]
I have a page that handles App Configuration, part of that is gathering DB connection info and also updating the databases when required. There is a Validate button that validates the connection info then checks if a update is needed. As long as the Validation method does not get an Exception from SqlConnection OpenAsync all is fine. If it does throw an Exception I display the error. The user can adjust the info they entered and Click Validate again to re-check the connection info. The issue is the second click on Validate will not update the UI at all. During the Validate the UI is updated to Show a label that is is validating and the button is hidden etc.

First Validate btn Click.

![image](https://user-images.githubusercontent.com/1186731/93799127-93971c00-fbf3-11ea-8ef4-e3c46c28a793.png)

Result.

![image](https://user-images.githubusercontent.com/1186731/93799225-b6293500-fbf3-11ea-849d-806f1860d6ac.png)

Clicking the Validate button again will not update the UI, the third click will.

**Comment by WayneHiller** [comment]
The test code I first posted at the top shows the issue, I have tried manually throwing many other Exception types with no issues. There is something happening specifically when the SqlConnection Open/OpenAsync throws an exception.

**Comment by ajcvickers** [comment]
@WayneHiller Are you waiting long enough for the exception to be thrown? In my experience it can take some time for this kind of exception to be thrown, even when a low value for connection timeout is used.

Also, the DbConnection is not being disposed, which is a bug, but shouldn't result in bad behavior in this case.

**Comment by WayneHiller** [comment]
@ajcvickers Note that code was just a quick test to reproduce. The Exception is thrown in 5 seconds. I can step through the code in the debugger and it is executing as it should.

**Comment by ajcvickers** [comment]
Then no more ideas from me.

**Comment by WayneHiller** [comment]
I have tested various other SQL Server ADO exceptions from SqlCommand etc and they all work as expected. It is only an Exception from SqlConnection Open/OpenAsync that causes Blazor to stop updating the UI and only for the next event from that same button click. Other events on the page will update the UI correctly.

**Comment by captainsafia** [comment]
It looks like this is not an issue with Blazor in particular. We've moved this over to the Discussions milestone and will leave it open in case it can be resolved there. We don't plan on investigating a fix in Blazor though.

**Comment by WayneHiller** [comment]
@captainsafia How was it determined that it is not an issue in Blazor? What would cause Blazor to stop updating the UI after an exception from SqlConnection Open is caught. Could other exception types have the same effect?
