### ISSUE TITLE
Scoped DI for Blazor webassembly based on Page

### ISSUE THREAD

**Issue by smartprogrammer93** [dotnet/aspnetcore#26127]
### Is your feature request related to a problem? Please describe.
Yes i would like to create a scoped service that has a lifetime of the page its running on.

### Describe the solution you'd like
We know that when you register a service as scoped in Blazor webassembly, it is treated like a singleton. 
This is very confusing to new developers that are used to scoped service in MVC or Pages. 

I also understand that scoped service in Blazor server is based on connection. so as long as the browser maintains that connection the service will still be valid even if the user requests different page.

I understand that changing this is a breaking change but it has very valid use cases.

**Comment by smartprogrammer93** [comment]
As a work around, i currently create scope on initialization of application and keep that scope stored in a singleton service, and everytime a NavigationManager.LocationChanged event happens i dispose of the old scope and create a new one. the problem with this approach is if i change the location but i dont change the page, e.g from "/category/1" to "/category/2" it does fire the locationChanged event while the same page is still alive. Currently this is not giving me any problems but i am thinking it might in the near future. if anyone has a solution to this please let me know.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You can achieve what you're looking for by using `OwningComponentBase` type. The following article will help you learn more about it: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#utility-base-component-classes-to-manage-a-di-scope
