### ISSUE TITLE
No whitespace between two span elements if there's an if-block between them

### ISSUE THREAD

**Issue by ok345** [dotnet/aspnetcore#26129]
Normally there is a space between 2 span elements. If the second span for example is wrapped in an if-block, then there is no space betweeen the two elements. So it's an inconsistent behavior. 
We're using version 3.1.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This behavior is by-design.

**Comment by ok345** [comment]
How can I prevent this behavior in 3.1, so that the whitespace is always preserved?

For example this code:
<span>Text1</span>
<span>Text2</span>
produces:
Text1 Text2

but
<span>Text1</span>
@if (true)
{
    <span>Text2</span>
}
is rendered as:
Text1Text2
without whitespace.
