### ISSUE TITLE
Expose policy provider to allow override for default response caching behaviour

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2612]
_From @JunTaoLuo on Tuesday, January 24, 2017 12:25:21 PM_

Currently https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/Internal/Interfaces/IResponseCachingPolicyProvider.cs is not exposed publicly. This type will need some work but exposing it will allow user overrides for checks on what is deemed cacheable, when response caching should apply, and expiry checks for cache entries. 

_Copied from original issue: aspnet/ResponseCaching#96_

**Comment by aspnet-hello** [comment]
_From @asser-dk on Monday, November 20, 2017 7:44:57 AM_

Being able to manipulate the cache entries would be great.

We have some data which doesn't change very often but which is accessed very frequently, however; when the data changes we would like to clear the cache immediately. Currently we're in-memory caching inside our business logic but it would be so much cleaner and simpler if we could somehow just clear the response cache for a given endpoint.

**Comment by JonasSamuelsson** [comment]
Is this something you'd be willing to consider for 3.1?

**Comment by namnik** [comment]
hi dears;
we very very need to have " response caching" without authentication!
please implement this feature!

**Comment by tanveerbadar** [comment]
Updating the link to point at asp.net core [version](https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/ResponseCaching/src/Interfaces/IResponseCachingPolicyProvider.cs).

**Comment by JunTaoLuo** [comment]
This is one of the main motivation for our work on Output Caching: This will be considered as part of the work on OutputCaching: #27387. The design and discussion will continue there.
