### ISSUE TITLE
Blazor WASM: Programmatically set layout for a page or component

### ISSUE THREAD

**Issue by zachion** [dotnet/aspnetcore#26122]
### Describe the solution you'd like
Ideally we would need the ability to specify layouts for each component or page programmatically, like the following example:
```
if (condition)
        {
            @layout MainLayout
        }
        else
        {
            @layout LoginLayout
        }
```
or 
```
<AuthorizeView>
    <Authorized>
        @layout MainLayout
    </Authorized>
    <NotAuthorized>
          @layout LoginLayout
    </NotAuthorized>
</AuthorizeView>

```

### Additional context
Currently if we try this we get syntax highlight error and we are unable to do so:
![image](https://user-images.githubusercontent.com/15831038/93744603-cabcfb80-fbfa-11ea-9d62-3c870bafff56.png)
![image](https://user-images.githubusercontent.com/15831038/93744565-b973ef00-fbfa-11ea-9ca0-5725737a29f2.png)

Project does not build either:
![image](https://user-images.githubusercontent.com/15831038/93747228-12de1d00-fbff-11ea-8ae0-bd080447d704.png)

**Comment by boukenka** [comment]
@zachion I am confronted with a similar scenario. It would be nice if there was an easy way to assign the layout programmatically.

**Comment by BruceHunter** [comment]
Being able to control which layout seems to be at the "page" component level. It does not seem, nor have I found a way to have a child component of the page component be able to change the layout.

I have kinda solved this problem by doing the following.

Create a MainLayout.razor

```
@inherits LayoutComponentBase

<AuthorizeView>
    <NotAuthorized>        
        <SubLayoutUnsecured Body="@Body"></SubLayoutUnsecured>
    </NotAuthorized>
    <Authorized>
        <SubLayoutSecured Body="@Body"></SubLayoutSecured>
    </Authorized>
</AuthorizeView>
@code {
}
```

Abviously, you will need to add more logic here, but you get the idea. Anonoymous for example or a specific route being loaded etc.

Then move the markup into Sub components like such.

SubLayoutSecured.razor
```
<div>
@body
</div>
@code {
    [Parameter]
    public RenderFragment Body { get; set; }
}
```

SubLayoutUnsecured.razor
```
<div>
@body
</div>
@code {
    [Parameter]
    public RenderFragment Body { get; set; }
}
```

**Comment by SteveSandersonMS** [comment]
You can use the `<LayoutView>` component to render an arbitrary block of content (such as a `@page` component, or any other component, or any other block of Razor markup) within an arbitrary layout.

**Comment by BruceHunter** [comment]
Well, I'm glad I know that know. 

So to build on what @SteveSandersonMS stated above. Please correct me if I'm wrong, but I just tested this.

- MainLayout.razor (default)
- AnotherLayout.razor

In your component, wrap markup with LayoutView like such.

```
<LayoutView Layout="@typeof(AnotherLayout)">
<div></div>
</LayoutView>
```

**Comment by BruceHunter** [comment]
So... it looks like I wasn't to far off from my first post with the SubLayout components.

If you need to switch out an entire page layout, I had to do the following.

**MainLayout.razor** - Don't put any markup here, only @Body
```
@inherits LayoutComponentBase

@Body

@code {
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
    }
}
```

**PrimaryLayout.razor** - Put Markup you were going to put in MainLayout.razor here.
Wrap components with:
```
<LayoutView Layout="@typeof(PrimaryLayoutLayout)">
<div></div>
</LayoutView>
```

Wrap components with:
**SecondaryLayout.razor** - Secondary markup etc.
```
<LayoutView Layout="@typeof(SecondaryLayout)">
<div></div>
</LayoutView>
```

If you don't do it like this, then when you put markup in MainLayout and then want to swap out to SecondaryLayout it will be a merge of the two. I'm sure that is fine if you want this, but I want to be able to swap out the default layout completely.

**Comment by zachion** [comment]
Hello, I appreciate your help but I am stuggling to absorb the information on here, and the LayoutView is somewhat not fully documented as of yet. 
All examples I see on the web are for the App.razor file with something like this:
```
 <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <p>Sorry, there's nothing at this address.</p>
        </LayoutView>
    </NotFound>
```
Can you elaborate a bit further with a full example of how to use this and assuming that all layouts I am intending to use will have their own @body fragments.

**Comment by SteveSandersonMS** [comment]
@zachion It sounds to me like what you want is an alternative to the normal `RouteView`. The normal built-in `RouteView` looks for a layout given by a compile-time attribute on the target page. Instead, you want to use different logic for choosing a layout.

You can do this fairly straightforwardly by creating your own alternative to `RouteView`. For example, add a file called `CustomRouteView.razor` to your project, containing:

```razor
@using Microsoft.AspNetCore.Components.Rendering

<AuthorizeView>
    <Authorized>
        <LayoutView Layout="typeof(MainLayout)" ChildContent="(RenderFragment)RenderPageWithParameters" />
    </Authorized>
    <NotAuthorized>
        <LayoutView Layout="typeof(OtherLayout)" ChildContent="(RenderFragment)RenderPageWithParameters" />
    </NotAuthorized>
</AuthorizeView>

@code {
    [Parameter] public RouteData RouteData { get; set; }

    private void RenderPageWithParameters(RenderTreeBuilder builder)
    {
        builder.OpenComponent(0, RouteData.PageType);
        foreach (var kvp in RouteData.RouteValues)
        {
            builder.AddAttribute(1, kvp.Key, kvp.Value);
        }
        builder.CloseComponent();
    }
}
```

... then in `App.razor`, replace `<RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />` (or `AuthorizeRouteView` with `<CustomRouteView RouteData="@routeData" />`.

The logic I've shown here will pick between two layouts `MainLayout` and `OtherLayout` depending on whether the user is authorized. If you want more complex logic, you could replace all its markup with:

```razor
<LayoutView Layout="ChooseLayout()" ChildContent="(RenderFragment)RenderPageWithParameters" />
```

... and then in your `@code` block add a method called `ChooseLayout` that returns the `Type` corresponding to whichever layout you want to use.
