### ISSUE TITLE
Css selector is not working on built-in components. 

### ISSUE THREAD

**Issue by Ariansh** [dotnet/aspnetcore#26137]
consider that I am using css isolation for a component. I create a class in css and assign it to a HTML element (take input type=text  in razor file. it works fine. but if I assign it to InputText component. it does assign the class to the rendered element but doesn't include the b... identifire to element. so it wont read that class. I tried many work arounds yet no success. 

sample codes are:

.razor:
 <InputText id="Code" @bind-Value="@TheCode" class="col-md-12 CodeStyle"/>
.razor.css
.CodeStyle{
   background-color: #000000;
}

i used both:
- .net 5 Rc1
- .net 5 preview 8

**Comment by SteveSandersonMS** [comment]
You need:

```css
::deep .CodeStyle{
background-color: #000000;
}
```

The whole idea of CSS scoping is to limit the styles to your component. The `InputText` component is a separate component, so its styling is not affected by scoped styles. You can use `::deep` to escape from the scoping and influence descendant components.

**Comment by Ariansh** [comment]
Thank you Steve. i'v checked that but I suppose that time i had a different mistake in my code. it is resolved.
