### ISSUE TITLE
On Blazor component Loop Foreach iterate only one time

### ISSUE THREAD

**Issue by piercarlo62** [dotnet/aspnetcore#26135]
Hello to everybody,
I have this strange behaviour:

Premises:
Net Core 5.0 RC1
Blazor webassembly environment.
Razor Component (Page)
The page retrieve from the server (Api) a list of a class -> List<WorkSheetDto>:

```
`    public class WorkSheetDto
    {
        public WorkSheetDto()
        {
            Fields = new List<WorkSheetFieldDto>();
            Assignments = new List<WorkSheetAssignmentDto>();
        }
        public WorkSheetDto(WorkSheetDto item)
        {
            Id = item.Id;
            Protocol = item.Protocol;
            TemplateId = item.TemplateId;
            Template = item.Template;
            Fields = new List<WorkSheetFieldDto>(item.Fields);
            Assignments = new List<WorkSheetAssignmentDto>(item.Assignments);
            Checked = item.Checked;
        }
        public int Id { get; set; }
        public string Protocol { get; set; }
        public int TemplateId { get; set; }
        public TmkSheetTemplateDto Template { get; set; }
        public TmkLayoutTemplateDto SelectedLayoutTemplate { get; set; }
        [CustomListValidator(false)]
        public List<WorkSheetFieldDto> Fields { get; set; }
        [CustomListValidator(true)]
        public List<WorkSheetAssignmentDto> Assignments { get; set; }
        public List<WorkTaskDto> WorkTasks { get; set; }
        public bool Checked { get; set; }
`
```
The foreach loop like following -> Where AssignedSheets is the List<WorkSheet> on component side,
 ```
@foreach (var workSheet in AssignedSheets)
{
       some othe components here omissed for brevity.......
}
```

On the same component a button that on click do following:

```
    void SelectAll(bool flag)
    {
        foreach (var item in AssignedSheets)
        {
            item.Checked = flag;
        }
    }
```
So set to true or false the property Checked of every WorkSheet.

The component everytime I click the button execute the SelectAll loop and the render of component, but........

On the first click the "@foreach (var workSheet in AssignedSheets)" is iterated correctly, so can display the correct state.

But on the second click the SelectAll on code execute correctly but the foreach on component does not execute, so I can change the values or each of the WorkSheet property Checked without that it would be reflected,  the page is rendering but the foreach on Component  does not iterate/execute.

No errors in no-where, not in code, not in javascript, not in wasm.

Some tip ?, because I cannot guess what is happening.

Thanks in advance for helping

**Comment by SteveSandersonMS** [comment]
Could you please post a complete example of the code you're having trouble with? Ideally as a minimal project on GitHub.

Otherwise I'm afraid it's difficult to understand how exactly your code is structured and hence why it's not doing what you want.

**Comment by piercarlo62** [comment]
Sorry But here the developer is stupid !!!! (Me)

I found the problem and nothing regarding Blazor, on one Parent Component I setted Should Render false and I forget it.

No problems at all.

Sorry next time I will be more carefull before write.

Bye

Piercarlo
