### ISSUE TITLE
Error Microsoft.AspnetCore.Mvc.Api.Analyzers 

### ISSUE THREAD

**Issue by shpsyte** [dotnet/aspnetcore#26130]
### Describe the bug
I've installed the Microsoft.AspnetCore.Mvc.Api.Analyzers and when I try to restore I get these errors:

Unable to load the service index for source https://api.nuget.org/v3/index.json.
The SSL connection could not be established, see inner exception
The remote certificate is invalid according to the validation procedure

### To Reproduce
Insall the package Microsoft.AspnetCore.Mvc.Api.Analyzers using this command:
dotnet add package Microsoft.AspnetCore.Mvc.Api.Analyzers

try restore
dotnet restore

### Exceptions (if any)
Unable to load the service index for source https://api.nuget.org/v3/index.json.
The SSL connection could not be established, see inner exception
The remote certificate is invalid according to the validation procedure

### Further technical details
**OpenSSL 1.1.1g  21 Apr 2020**

.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.810 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by pranavkm** [comment]
This issue was moved to NuGet/Home#10057
