### ISSUE TITLE
Investigate request `no-cache` behaviour

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2613]
_From @JunTaoLuo on Tuesday, January 24, 2017 12:23:08 PM_

In the current implementation, for requests with a `no-cache` directive, cache lookup is skipped but response capture and cache store still occurs. The RFC only specifies that the cache cannot use a stored response to satisfy the request without validation but explicitly says nothing regarding the response.

This means that for requests with `no-cache`, writes to the cache will still occur and will overwrite any existing cached entries for the same resource. This can lead to a large amount of potentially wasted writes and we should determine if this behaviour is common in other implementation of HTTP caching.

Note that this can be resolved with user provided implementations of the `IResponseCachingPolicyProvider` but that is not currently exposed publicly. Regardless, we should investigate whether the current implementation should be the default behaviour.

_Copied from original issue: aspnet/ResponseCaching#95_

**Comment by aspnet-hello** [comment]
_From @muratg on Friday, February 3, 2017 10:30:34 AM_

Assigning to @JunTaoLuo for investigation.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll investigate this unless there's more demand for this issue.
