### ISSUE TITLE
Document Kestrel breaking changes, new API and new config in 5.0

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#26141]
We need to update/write conceptual docs to reflect breaking changes, new API and new config in 5.0.

1. New kestrel event counters (https://github.com/dotnet/aspnetcore/pull/21649)
  a) Related: https://github.com/dotnet/AspNetCore.Docs/issues/18272
2. PEM support (https://github.com/dotnet/aspnetcore/pull/23584)
  a) Related: https://github.com/dotnet/AspNetCore.Docs/issues/19113
3. Automatic config reload (https://github.com/dotnet/aspnetcore/pull/21072 & https://github.com/dotnet/aspnetcore/pull/22528)
4. SNI from config (https://github.com/dotnet/aspnetcore/pull/24286)
5. Async ServerOptionsSelectionCallback UseHttps() overload (https://github.com/dotnet/aspnetcore/pull/25390)
6. Use platform-default TLS/SSL protocol versions by default (https://github.com/dotnet/aspnetcore/pull/22437)
7. Obsolete the Libuv transport (https://github.com/dotnet/aspnetcore/pull/23480)
8. "SslProtocols" settable via config (https://github.com/dotnet/aspnetcore/pull/22910)
9. "ClientCertificateMode" settable via config (https://github.com/dotnet/aspnetcore/pull/24076)

The following APIs are new, but might not warrant conceptual docs.

1. custom request header decoder API to Kestrel (https://github.com/dotnet/aspnetcore/pull/23233)
2. Inline scheduler option for Sockets transport (https://github.com/dotnet/aspnetcore/pull/24638)
3. Add SocketTransportOption to enable/disable WaitForData (https://github.com/dotnet/aspnetcore/pull/19396)

@Pilchie Would it be better to move this to https://github.com/dotnet/AspNetCore.Docs?

**Comment by Pilchie** [comment]
Tagging @mkArtakMSFT for thoughts on whether this should move to the Docs repo or stay here.  *Personally* I spend a lot more time here.

**Comment by davidfowl** [comment]
@halter73 seems like we didn't fix the KestrelServer breaking change.

**Comment by halter73** [comment]
We should fix it.
