### ISSUE TITLE
blazor.server.js references WebAssembly types

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26148]
As part of the InputFile changes, Wasm specific code was added to blazor.server.js file. This isn't a problem in itself, except it's poor code hygiene and there's a small chance we break something by using APIs that do not work in one of the platforms.

**Comment by captainsafia** [comment]
Oh! Just realized you were talking about the `blazor.server.js` file, not the `blazor.wasm.js` file in the PR feedback. Yep, this is unexpected.

Tangentially: it might still be worth it to export the wrapped `mono_wasm_add_assembly` from the runtime.

**Comment by pranavkm** [comment]
>  it might still be worth it to export the wrapped mono_wasm_add_assembly from the runtime.

I don't follow. Is this about moving a feature to the runtime (rather than us having to cwrap it)?

**Comment by captainsafia** [comment]
We would move the `cwrap` invocation to the runtime repo [here](https://github.com/dotnet/runtime/blob/a5faa95e499d3d790739be71e5879a34c220e397/src/mono/wasm/runtime/library_mono.js#L76-L87). Then in our codebase, we can call it like MONO.mono_wasm_add_assembly, similar to what we do for loading timezone info for example ([ref](https://github.com/dotnet/aspnetcore/blob/6654e9d57a8c9f1ac744dd20db37f936df20e23e/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L494)).

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/28944.
