### ISSUE TITLE
Review logged messages

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2615]
_From @JunTaoLuo on Wednesday, October 5, 2016 6:06:13 PM_

Review the messages that are logged added in https://github.com/aspnet/ResponseCaching/pull/65. Also make sure the messages are at the correct level.

_Copied from original issue: aspnet/ResponseCaching#68_

**Comment by aspnet-hello** [comment]
_From @muratg on Thursday, May 25, 2017 3:39:06 PM_

@glennc Are you able to look into this for preview2, or should we move it out to preview3.

**Comment by JunTaoLuo** [comment]
Doesn't look like we need this anymore.
