### ISSUE TITLE
RazorPagesTemplate_IndividualAuth

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#26153]
This test was [quarantined](https://github.com/dotnet/aspnetcore/issues/19716) back in march, fixed, but never unquarantined. It's now failing for a new reason.
https://dev.azure.com/dnceng/public/_test/analytics?definitionId=331&contextType=build
```
Expected next link on /Identity/Account/ForgotPassword to be /Identity/Account/Register but it was /.
Expected: True
Actual:   False
   at Templates.Test.Helpers.AspNetProcess.ContainsLinks(Page page) in /_/src/ProjectTemplates/Shared/AspNetProcess.cs:line 177
   at Templates.Test.Helpers.AspNetProcess.AssertPagesOk(IEnumerable`1 pages) in /_/src/ProjectTemplates/Shared/AspNetProcess.cs:line 140
   at Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth(Boolean useLocalDB) in /_/src/ProjectTemplates/test/RazorPagesTemplateTest.cs:line 204
--- End of stack trace from previous location ---
```

This has failed every run in master since 9/11, making it the test with the second highest failure rate.

**Comment by pranavkm** [comment]
@HaoK \ @javiercn looks like a bug \ change to the template?

**Comment by mkArtakMSFT** [comment]
@HaoK please investigate this - let's understand what's the cause and we can decide what to do with it then.

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/commit/ecc2ba16b8d20d5180d272f4f548e5b8a02461f0#diff-abd3a137a46293571e38178ab2525a29 changed some link ordering, the MVC template tests were updated but these were not since they were quarantined :(  Fix is to just update the tests with the same ordering changes

**Comment by HaoK** [comment]
@Tratcher so this test should be safe for me to unquarantine as part of the fix then?

**Comment by HaoK** [comment]
Seems bad to have this test in quarantine if we can avoid it at all...

**Comment by Tratcher** [comment]
Go ahead, it was consistently passing before this regression.
