### ISSUE TITLE
KeyBuilder and hashed keys

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2616]
_From @JunTaoLuo on Wednesday, September 21, 2016 11:56:48 AM_

Currently keys are strings. We may want to consider creating an abstraction of KeyBuilder that only creates a string for IDistributedCache based stores and use an object as the key for IMemoryCache based stores. We may also want to consider adding support for hashing the keys to a constant length

_Copied from original issue: aspnet/ResponseCaching#54_

**Comment by muratg** [comment]
Backlogging this one.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue. However, we might consider this during the design of Output Caching.
