### ISSUE TITLE
Rename (F2) on a component parameter renames the component tag

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#26165]
Repro steps:
- Using VS 16.8 Preview 4, with the new Razor tooling
- Open a Blazor project
- In Index.razor try to rename the Title attribute on the SurveyPrompt component by hitting F2

Expected result:
- F2 does nothing (yet) for component parameter attributes

Actual result:
- F2 shows the rename text box auto filled with the attribute name
- Completing the rename then renames the component tag, not the attribute

**Comment by TanayParikh** [comment]
So to implement this properly, we need LSP platform to support [`textDocument/prepareRename`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareRename). I've created a [VSTS issue here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1222641).
