### ISSUE TITLE
Blazor CSS Isolation RC1 Change tracking Issue

### ISSUE THREAD

**Issue by chrdlx** [dotnet/aspnetcore#26175]
I've found out that when you're using CSS Isolation in a particular component.... i.e.   Component.razor / Component.razor.css
If you make changes to the .css file,  you need to REBUILD (NOT JUST BUILD) the project,  and this is a big time consuming issue, since it starts building all the dependencies too.
 When you make changes to the .razor file,  a build is just enough,  you don't need to rebuild.  

 So it seems changes are not being tracked in these .razor.css files...  this happens using visual studio and dotnet watch.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed in RC2 release.
