### ISSUE TITLE
Redis response cache store

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2617]
_From @JunTaoLuo on Wednesday, September 21, 2016 11:51:04 AM_

Currently Redis will be exposed through the DistributedResponseCacheStore but the API of IDistributed cache could be a limiting factor. We may bypass that abstraction and design a RedisResponseCacheStore to take advantage of more features of redis.

_Copied from original issue: aspnet/ResponseCaching#53_

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
