### ISSUE TITLE
RedirectUri not firing after ChallengeAsync with "Windows" AuthenticationScheme

### ISSUE THREAD

**Issue by germansak** [dotnet/aspnetcore#26178]
### Describe the bug
I'm working on a new version of a Site that's behind IIS with Windows Authentication. I need to implement "Change User" functionality (or "Logout")
Previous version is on Asp.Net framework and this functionality was implemented handling the "TSWA-Last-User" cookie which forced the browser to show a dialog to input user and password

I've searched for the same functionality in net core and the closest I've found was to call ChallengeAsync

 In ConfigureServices
`
services.AddAuthentication(IISDefaults.AuthenticationScheme);
`

In Configure
```
app.Use((context, next) =>
{
    if (context.Request.Path.Equals("/logout") && context.Request.Method == "POST")
    {
        return context.ChallengeAsync(IISDefaults.AuthenticationScheme, new AuthenticationProperties
        {
            RedirectUri = "/"
        });
    }
}
```

What happens is that when calling POST on logout it triggers authentication but when it has to redirect to home page ("/") it does not and keeps on asking for credentials in an infinite loop

Isn't it intended to ask for credentials because of the Challenge call and then redirect to home page or am I missing something (or doing something terribly wrong)?

Been searching for several days and couldn't find anything

BTW I'm using Blazor Server Side for the site

Thanks in advanced!

### Further technical details
- dotnet --info
_SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7
Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.20215
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\_
- Running Visual Studio 2019

**Comment by blowdart** [comment]
Windows authentication is meant to silently challenge and login the current domain user, it's not meant for switching or otherwise being someone else. That you managed to get this to work in another system is frankly astounding. I don't even know what TSWA-Last-User is.

You're not doing anything wrong, challenge in this case with all browsers that support Windows Auth starts an automatic login. You can't do what you want to do.

**Comment by germansak** [comment]
> Windows authentication is meant to silently challenge and login the current domain user, it's not meant for switching or otherwise being someone else. That you managed to get this to work in another system is frankly astounding. I don't even know what TSWA-Last-User is.
> 
Hi Barry, thanks for your quick response!
Yes, I know it's supposed to work that way but it's a requirement that I need to implement
This way, I can login from the browser, even when I'm not inside the company intranet, just entering my domain credentials from any computer. I don't know if there are security issues doing it (surely they are) but I don't know other way to solve this.

The code implemented in the previous version of the site (ASP.Net MVC) was:

```
public ActionResult Logout()
{
    HttpCookie cookie = Request.Cookies["TSWA-Last-User"];
    if (User.Identity.IsAuthenticated == false || cookie == null || StringComparer.OrdinalIgnoreCase.Equals(User.Identity.Name, cookie.Value))
    {
        string name = string.Empty;
        if (Request.IsAuthenticated)
        {
            name = User.Identity.Name;
        }
        cookie = new HttpCookie("TSWA-Last-User", name);
        Response.Cookies.Set(cookie);
        Response.AppendHeader("Connection", "close");
        Response.StatusCode = 0x191;
        Response.Clear();
        Response.Write("Unauthorized. Reload the page to try again...");
        Response.End();
        return RedirectToAction("Index");
    }
    cookie = new HttpCookie("TSWA-Last-User", string.Empty)
    {
        Expires = DateTime.Now.AddYears(-5)
    };
    Response.Cookies.Set(cookie);
    return RedirectToAction("Index");
}
```
That triggered a prompt for credentials in Chrome and then reloaded the page
I copied it from a StackOverflow answer and it worked fine so I left it.

Is there any other way to implement this kind of functionality, I mean, to switch user from the browser?

**Comment by blowdart** [comment]
There are lots of security reasons why you shouldn't expose integrated/windows authentication on the internet. If you wanted to support internet and intranet logins then Active Directory Federated Services is the right way to go about this, but that's still going to automatically log you in when you're on your intranet.

I am unaware of any way to supported switch users in the browser like this (it's called integrated authentication for good reason!)

**Comment by germansak** [comment]
Ok Barry, thanks for your time. I'm going to dig into this a little more because I need to solve this to implement this new version of the site. Maybe ADFS is the solution. Unfortunately, I don't get to choose the infrastructure or server configurations in order to make this work the correct and secure way.

Thanks again and have a good day

**Comment by blowdart** [comment]
ADFS will also prepare you for any subsequent move cloudwards, because you'll be using OIDC/OAuth, rather than something windows specific.

I'm going to close the issue, because it's out of our hands, and is down to how the authentication protocol and browsers work.
