### ISSUE TITLE
Configure the linker for internationalization documentation needs updating

### ISSUE THREAD

**Issue by marek-safar** [dotnet/aspnetcore#26176]
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1#configure-the-linker-for-internationalization documentation needs to be updated to reflect .NET5 globalization changes.

**Comment by pranavkm** [comment]
It's been updated for 5.0: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-5.0
