### ISSUE TITLE
InputTextArea delays to show binded data

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#26183]
### Describe the bug
I have a Model for an EditForm called KundenInput. The page can be visted by a parameter called kundennummer. Whenever I do this, I create a new model based on my parameter. Almost every attribute from my model is bind to an Input element.

All binds are displayed directly when a new model is created, however if I use the InputTextArea component and bind a value there, it is getting displayed with a large delay. This happens for every InputTextArea in this EditForm. When I change the InputTextAre to an InputText it is also directly displayed to the user.

I recorded a small video which excatly shows what I mean. Moreover, I am showing you the creation of my KundenInput in it.
https://www.youtube.com/watch?v=ilKQWTmQyYk

### To Reproduce
I am not quite sure when this behaviour happens. I've created a new default Blazor server app and tried to reproduce the same behaviour. There is also a very small delay here but not mentionable. Perhaps it has something todo with the size of my EditForm. My EditEdit Form has 49 InputText components, 16 InputSelects and 14 InputCheckboxes. 

In my main project I have a component which can be visited in two ways:
```
@page "/Kunden/{Kundennummer:int}"
@page "/Kunden/Anlage"
```

I have two classes. The first one represents data from a database, and the second is a clone of this data which is used as my input where the user can manipuliate the data.

Both classes have a method to create a new object of the other class and copy it's values.
E.G.
```
public static KundeInput ToInput(this Kunde kunde)
{
	var input = new KundeInput(kunde.KUND_A_NR)
	{
		Notiz = kunde.KUND_WK5_A_NOTIZ,
		Amtsgericht = kunde.KUNDZU_A_AMTSGERICHT,
		Anrede = kunde.KUND_A_ANREDE ?? "Sehr geehrte Damen und Herren",
		Bonus = kunde.KUND_L_BONUS
		/* More values */
	}
}
```
		
In OnParametersSetAsync I am checking for any parameter.
```
protected override async Task OnParametersSetAsync()
{
	if (Kundennummer > 0)
	{
		Modus = EditMode.Bearbeiten;

		var kunde = Kunde.GetKunde(Kundennummer.ToString());
		if (kunde != null)
		{
			Input = kunde.ToInput();
			
			kundeExists = true;
			/* More Logic */
		}
	}

	/* More Logic */
	await base.OnParametersSetAsync();
}
```

### Exceptions (if any)
---

### Further technical details
- ASP.NET Core version 3.1.402
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

VS 16.7.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's hard to know what's causing this. We will need a minimalistic repro project to be able to investigate this. Please share one when you have and we will look into it.
