### ISSUE TITLE
Blazor Localization issue with Resources Folder

### ISSUE THREAD

**Issue by hishamco** [dotnet/aspnetcore#26184]
While I'm working on a sample demo for Oqtane, I have some resources that I put in the `Resources` folder, some in folder hierarchy similar to what we did in MVC or RazorPages. What I notice is after the compilation the culture folder is created in the `bin` folder but the there's no compiled resources in there, I'm not sure if it's a bug or limitation in blazor

/cc @pranavkm

**Comment by pranavkm** [comment]
@hishamco could you share a minimal app that reproduces this? It does not reproduce with a vanilla app from the templates, but maybe there's something specific about how Oqtane is configured that's affecting it.

**Comment by hishamco** [comment]
Try to add  a resx inside `Resources/Folder/Index.fr.resx` in your Blazor repo, where `Folder` is the parent for your component, I'm sure the compiler will not create a resources file as `fr/AssemblyName.Folder.Index..resources.dll`

**Comment by hishamco** [comment]
If the resx files beside the component everything is working fine, in case of `AddLocalization()` without specifying the resources path

**Comment by pranavkm** [comment]
I don't see that in a regular web app either. In either case, a `fr/AssemblyName.resources.dll` is created. What am I missing?

**Comment by hishamco** [comment]
Strange!! Are you using Server-Side or WebAssembly Blazor? The issue I'm facing with WASM, any idea?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by hishamco** [comment]
@mkArtakMSFT I will struggle to create a minimal repo

@pranavkm one more thing related to localization is localization from external assembly that will be loaded at runtime support or is there any limitation?

**Comment by ylr-research** [comment]
@hishamco I do have a working Blazor WASM app with localization and no issues so far.
 
See a snippet from `Program.cs`
```C#
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");
```
And here is a snapshot of my Resources folder

![image](https://user-images.githubusercontent.com/63487874/94042306-62f0e700-fd99-11ea-8c26-a2048dea091a.png)

I would say you may want to try adding `/Folder` to the end of the `ResourcesPath`, like this:
```C#
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources/Folder");
```

**Comment by hishamco** [comment]
Thanks for your input @ylr-research, regarding

> I would say you may want to try adding /Folder to the end of the ResourcesPath

I knew that :) could you please try to add a component named `Index.razor` in folder say `Test`, so the resources should be located into `Resources/Test/Index.es.resx` and see if it works

**Comment by hishamco** [comment]
@mkArtakMSFT  the bot change the labels that you set every time ;)

**Comment by mkArtakMSFT** [comment]
That's ok  - we do look at these 👍
We won't be able to help out here without a repro project, as we can't reproduce this.
Will park this in the `Next sprint planning` milestone and hopefully will have a repro shared here when we get to it during our sprint planning meetings in the future.

**Comment by hishamco** [comment]
@ylr-research could please let me know if you test the case that I mentioned in my last thread?

**Comment by hishamco** [comment]
@mkArtakMSFT I will try to provide a repo once @yaeldekel replied to me

Thanks

**Comment by hishamco** [comment]
I will close this for now, coz I test all the cases I have on an empty Blazor template and works as expected, seems something goes wrong on the project I have

Thanks
