### ISSUE TITLE
Blazor / AzureAd authentication has CORS errors

### ISSUE THREAD

**Issue by augaldecr** [dotnet/aspnetcore#26182]
# Issue Title

Blazor rc1 and Office 365 auth doesn't work

# General

I just created the project Blazor Wasm with single org authentication and show the CORS error

**Comment by BruceHunter** [comment]
Getting this with .net 5

dotnet new blazorwasm -au IndividualB2C --aad-b2c-instance "valuehere" --client-id "valuehere" --domain "valuehere" -o projectnamehere -ssp "B2C_1_signin"

**Comment by captainsafia** [comment]
@javiercn This looks like the same CORS issue we were debugging last month. Any updates on the fix for that from the identity team?

**Comment by captainsafia** [comment]
Hi folks -- the problem with CORS issues on Azure AD should be resolved now. Please try again and open a new issue if the problem persists.

**Comment by javiercn** [comment]
This is likely an issue with the redirect url being incorrectly registered. The redirect URL needs to be registered as a SPA url on the portal.
