### ISSUE TITLE
Create SemanticToken Snapshot tests

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26186]
Just like https://github.com/dotnet/aspnetcore-tooling/blob/2749fac6eccd59d3223649e8c6f6cff88daec4e6/src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/README.md we want to test the actual results given to our VSCode instance (currently tests only cover `Microsoft.AspNetCore.Razor.LanguageServer` functionality).

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg we have these don't we?

**Comment by ryanbrandenburg** [comment]
It's not EXACTLY the same since we don't have tests specifically for VSCode functionality, but I think it's reasonable to call this completed.
