### ISSUE TITLE
Extensibility for user operations of cached responses

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2618]
_From @JunTaoLuo on Wednesday, September 21, 2016 11:13:28 AM_

We may want to expose an extensibility point for users to modify the cached response. There are two instances where this can occur and we can add the extensibility to one or both. First is when the middleware first receives the response and is about to store it in cache. Second is when the middleware has retrieved the item from cache and is about to use it to serve a request. A scenario that may require this is for stripping out a few headers in an otherwise cacheable response. 

_Copied from original issue: aspnet/ResponseCaching#52_

**Comment by JunTaoLuo** [comment]
We'll revisit extensibility in Output Caching: https://github.com/dotnet/aspnetcore/issues/27387
