### ISSUE TITLE
Cache related warning headers

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2619]
_From @JunTaoLuo on Thursday, September 15, 2016 2:50:04 PM_

Need to revisit this to see what warnings we may want to send along with cached responses. For example, if no original expiry information is explicitly stated, we currently use a default expiration of 10s. In this case, we should send the warning 113 - "Heuristic expiration"

_Copied from original issue: aspnet/ResponseCaching#41_

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
