### ISSUE TITLE
Blazor Server razor components debugging doesn't show variable value on hover

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26196]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1181061/blazor-razor-components-debugging-doesnt-show-vari.html)._

---
[severity:It's more difficult to complete my work]
IDE:Visual Studio 2019 16.7.3
Framework:.Net Core 3.1
Project Type:Blazor Server
[Option→Suppress JIT optimization on module load]:Enabled

Debugging Blazor razor components in Visual Studio when I hover mouse over a variable, it shown its type not its value..

---
#### Feedback Bot on 9/10/2020, 10:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
@CyrusNajmabadi @tmat @dibarbet, @lewing investigated this elsewhere:
![image](https://user-images.githubusercontent.com/2008729/93933592-b9e1b800-fcd6-11ea-8e56-1ff76a59f42a.png)

Has anything changed in regards to dynamic file info mappings (that's what powers the C# in this scenario) & the debugger recently?

**Comment by dibarbet** [comment]
@NTaylorMullen this is the LSP razor editor right?  The only thing I can think of is that there was a slightly different debugger services when running with the C#_LSP content type.

Do you know when this started showing up?  the ticket looks like it's 16.7

**Comment by NTaylorMullen** [comment]
> Do you know when this started showing up? the ticket looks like it's 16.7

oh geez, ya that's odd. We just got a CTI report from 7 days ago about this starting to happen in VSMain: https://github.com/aspnet/AspNetCore-ManualTests/issues/203#issuecomment-696422854 (let me know if you don't have access)

**Comment by NTaylorMullen** [comment]
FYI @captainsafia
