### ISSUE TITLE
Incorrect Textmate Colorization After Comment

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#26207]
![image](https://user-images.githubusercontent.com/14852843/93948829-477fd080-fcf4-11ea-8c93-74dd52ac5fc3.png)

```cshtml
@code {

        // {
        //     // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
        //     Dispose(disposing: false);
        // }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
}
```

**Comment by ajaybhargavb** [comment]
Moving to 16.9. FYI @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
Seems we're still seeing this after https://github.com/dotnet/aspnetcore/issues/24126, but to a lesser degree:
![image](https://user-images.githubusercontent.com/14987221/95247381-a6e8e080-07ca-11eb-8d88-2bb3295d8b09.png)
Note that the `(`'s and `;`'s which were previously green are now the expected black color, but the `disposing` is green (in both places). I suspect either C# isn't returning us values for those sections or we aren't mapping them correctly/at-all. Will need more investigation.

**Comment by ryanbrandenburg** [comment]
![image](https://user-images.githubusercontent.com/14987221/95917969-e467e380-0d5f-11eb-8f71-097726dfc97a.png)

This will be fixed when everything is inserted. We did a change which resolves it, and there's also a change (from a different direction) coming from VSLanguageServerClient.
