### ISSUE TITLE
No-cache fields

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2620]
_From @JunTaoLuo on Thursday, September 15, 2016 2:45:33 PM_

Some directive such as `no-cache` may contain fields which can be stripped from the response after which the response can be deemed cacheable. 

_Copied from original issue: aspnet/ResponseCaching#40_

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
