### ISSUE TITLE
Revalidation

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2621]
_From @JunTaoLuo on Thursday, September 15, 2016 2:25:34 PM_

No current mechanism exist for revalidating a stale entry in the response cache. We may want to support the cache-control extensions listed in https://tools.ietf.org/html/rfc5861, in particular the `stale-while-revalidate` directive.

_Copied from original issue: aspnet/ResponseCaching#39_

**Comment by aspnet-hello** [comment]
_From @muratg on Thursday, May 25, 2017 3:41:27 PM_

@sebastienros What's your thoughts on this? Are you able to take this one?

**Comment by aspnet-hello** [comment]
_From @sebastienros on Thursday, May 25, 2017 4:07:53 PM_

To me it's less important than gating, but I have some users who asked for it strongly to prevent response lags. I think we should have it on a milestone.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
