### ISSUE TITLE
Can't return HttpResponseMessage from a controller

### ISSUE THREAD

**Issue by fkucuk** [dotnet/aspnetcore#26216]
### Describe the bug
I have a 4.7.2 application and I'm trying to rewrite it in .net core 3.1.

I have a method in a controller below. Of course, the real code is different I receive some parameters and generate a URL, etc. But the idea is the same. I am trying to reflect another server's response.

```csharp
[Route("images")]
    public async Task<HttpResponseMessage> GetImage()
    {
        Uri uri = new Uri("https://img-lcwaikiki.mncdn.com/mnresize/1024/-/pim/productimages/20202/4353414/l_20202-0w9011z8-hrz_a.jpg", UriKind.Absolute);
        using (HttpClient client = new HttpClient())
        {
            return await client.GetAsync(uri);
        }
    }
```

But interestingly, .net framework and core act totally different.

Framework, returns the image as I expected: https://imagereflectorframework.azurewebsites.net/images.

But core returns a json in the body: https://imagereflectorcore.azurewebsites.net/images.

I've checked the Microsoft Documentation, they are the same for Sytem.Net.Http.HttpClient class both in netCore 3.1 and .net Framework 4.7.2.

### To Reproduce
To reproduce you can create a fresh netCore and .netFramework apps. Add the code I've mentioned up as a new rest endpoint.

BTW I've created a repo for this projects: https://github.com/fkucuk/imagereflectorhttpclient

**Comment by Tratcher** [comment]
HttpResponseMessage is not a supported controller response type, that only worked in the old WebApi framework. You have to copy the response headers yourself and then return the stream.

**Comment by pranavkm** [comment]
Thanks for the issue report @fkucuk. The [WebAPICompatShim library](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-2.1#compatibility-shim) that was supported until the 2.1 release allowed returning HttpResponseMessage from specific controller actions. Unfortunately this isn't supported in 3.1 or later releases. We are investigating bringing back targeted support for some of the feature set to make migration.

There are a couple of options:

* Our recommendation would be to construct an `ActionResult` and copy the headers the way @Tratcher described it.
* You could have a register a formatter that can write a HttpResponseMessage. Here's the formatter from WebApiCompatShim for reference: https://github.com/dotnet/aspnetcore/blob/release/2.1/src/Mvc/Mvc.WebApiCompatShim/src/Formatters/HttpResponseMessageOutputFormatter.cs
