### ISSUE TITLE
Middleware between AuthenticationMiddleware and AuthorizationMiddleware runs before authentication is complete when default authentication scheme does not succeed even though a non-default authentication scheme succeeds.

### ISSUE THREAD

**Issue by Mubashwer** [dotnet/aspnetcore#26214]
### Describe the bug
Middleware between `AuthenticationMiddleware` and `AuthorizationMiddleware` runs before authentication is complete when default authentication scheme does not succeed even though a non-default authentication scheme succeeds.

### To Reproduce
* Setup a middleware between `AuthenticationMiddleware` and `AuthorizationMiddleware` e.g. `UserContextMiddleware` here
```
app.UseAuthentication();
app.UseMiddleware<UserContextMiddleware>();
app.UseAuthorization();
```

* Configure authentication with two schemes. One is default and the other is not.

* Make a request in which the non-default authentication scheme will succeed and the default authentication scheme will not succeed.

* UserContextMiddleware will be executed before the handler for the non-default authentication scheme is executed. (Bug!)

### Further technical details
- ASP.NET Core version 3.1
- Visual Studio 2019

**Comment by Tratcher** [comment]
Can you provide a more complete example? Preferably as a GitHub repo that can be cloned and run.

**Comment by blowdart** [comment]
UseAuthentication() only runs for the default scheme, it takes either specifying the scheme in policy or attributes for alternate schemes to take affect, which is what the authorization middleware provides.

So yes, what you're seeing is expected, and by design.

**Comment by Mubashwer** [comment]
I see. I was expecting authentication middleware to handle all authentications and authorisation middleware to handle all authorisations.

**Comment by Mubashwer** [comment]
> Can you provide a more complete example? Preferably as a GitHub repo that can be cloned and run.

I presume the example repo won't be necessary after @blowdart's example.

**Comment by blowdart** [comment]
I can see why you'd think that, but once you get outside the realms of default authentication schemes then authentication has no idea what to do, until something else tells it what to do. 

Now, you could use a virtual authentication scheme to provide a way to keep it all self contained, but unless you truly need that sort of thing it's just easier to accept this is how it all works.

**Comment by Mubashwer** [comment]
I understand. We only need two ways of authentication temporarily as we were migrating to OpenId authentication. So we are not facing this problem anymore.

**Comment by blowdart** [comment]
Fair enough, then I'll close the issue :)
