### ISSUE TITLE
Npm module @microsoft/signalr is dependencies to deprecated library

### ISSUE THREAD

**Issue by Sin333** [dotnet/aspnetcore#26220]
### Deprecated WebSockets(SignalR) dependencies
Hi guys I see so strange dependencies to obsolete npm module "request".
URL: [https://www.npmjs.com/package/request](https://www.npmjs.com/package/request).
Are you planing remove this library or maybe revert to another library in "@microsoft/signalr"? Because it's maybe critical for security some projects.

**Comment by Sin333** [comment]
![image](https://user-images.githubusercontent.com/16017825/94019815-e1aa4c00-fdba-11ea-8fc7-d958b33c48a5.png)
request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by BrennanConroy** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/19420

We changed our dependencies in 5.0

**Comment by Sin333** [comment]
Okey thanks you, I will waiting update)
