### ISSUE TITLE
Viewing Razor Component file crashes Visual Studio when component is located in RCL with multitarget setup

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26227]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1191109/viewing-razor-component-file-crashes-visual-studio.html)._

---
[severity:It's more difficult to complete my work]
### Viewing Razor Component file crashes Visual Studio when component is located in RCL with multitarget setup

With the attached project i can reproduce the problem 100% of a time.

Steps to reproduce:
-Open the attached solution file
-finde the project Node.Base and open Shared/Components/NodeGraph.razor
->VS crash

When opening a razor component for editing from the solution explorer the file will open but visual studio will immediately crash and restart.
The problem appears because the component is located in the RCL. The problem has to do with the way my RCL is set up (multitarget).
Moving the component back to Nodexr will enable you to open the component without crash.

---
#### Robert Acksel on 9/20/2020, 03:00 AM: 

<p>the problem arises with this lines</p><pre>&lt;PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" /&gt; 
</pre><pre>&lt;RazorLangVersion&gt;3.0&lt;/RazorLangVersion&gt;<br></pre><p>But not being able to use MVC support, i can not make an RCL for Blazor WebAssembly projects</p><p>See this docs for reference https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio#include-mvc-extensibility</p>

#### Feedback Bot on 9/21/2020, 00:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/21/2020, 02:10 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by ryanbrandenburg** [comment]
@RobertAcksel I'm not able to reproducing this issue, but I suspect I just haven't set my project up the way you have. You referenced an attached solution but I don't see it (on GitHub or the original developercommunity issue). Would it be possible for you to make that (or a similar project which displays this behavior) available on GitHub (or some other means)? Thanks!
