### ISSUE TITLE
PolicyBuilder.AddAuthenticationSchemes changes how the HttpContext Principal is handled

### ISSUE THREAD

**Issue by psaxton** [dotnet/aspnetcore#26231]
### Describe the bug
Using the `JwtBearerOptions.Events.OnTokenValidated` property when adding a JWT bearer authentication scheme (`AuthenticationBuilder.AddJwtBearer`), the `HttpContext.Principal` property can be altered or replaced. If an authorization policy is then applied which explicitly requires that authentication scheme using the `.AddAuthenticationScheme` method of the policy builder, then the alterations to the `HttpContext.Principal` made in the scheme are lost. If the authorization policy does not explicitely require the authentication scheme, the `HttpContext.Principal` alterations are kept as expected.

### To Reproduce
Code to set up the service collection as described:
```csharp
public void ConfigureServices(IServiceCollection services)
{
	services.AddAuthentication(CustomPrincipalScheme)
		.AddJwtBearer(CustomPrincipalScheme, options =>
		{
			options.Events = new JwtBearerEvents
			{
				OnTokenValidated = context =>
				{
					context.Principal = new CustomPrincipal(context.Principal);
					return Task.CompletedTask;
				}
			};
			options.IncludeErrorDetails = true;
			options.TokenValidationParameters = new TokenValidationParameters
			{
				IssuerSigningKey = Constants.SecurityKey,
				ValidIssuer = TestIssuer,
				ValidAudience = TestAudience,
			};
		});

	services.AddAuthorization(options =>
	{
		options.AddPolicy(ExplicitSchemePolicy, policyBuilder =>
			policyBuilder
				.AddAuthenticationSchemes(CustomPrincipalScheme)
				.RequireClaim("scope", TestScope)
				.RequireAssertion(context => context.User is CustomPrincipal)
		);

		options.AddPolicy(ImplicitSchemePolicy, policyBuilder =>
			policyBuilder
				.RequireClaim("scope", TestScope)
				.RequireAssertion(context => context.User is CustomPrincipal)
		);
	});

	services.AddMvc();
}
```

Minimal code repro has been posted as a repo with tests demonstrating the problem [here](https://github.com/psaxton/AuthPolicyRepro). Tags have been provided reproducing the bug in netcoreapp2.2 and netcoreapp3.1 frameworks.

### Further technical details
- ASP.NET Core version
  - Microsoft.AspNetCore.App 2.2.8
  - Microsoft.AspNetCore.App 3.1.7
- Include the output of `dotnet --info`
    C:\> dotnet --info
    .NET Core SDK (reflecting any global.json):
     Version:   3.1.401
     Commit:    5b6f5e5005
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.17763
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\3.1.401\
    
    Host (useful for support):
      Version: 3.1.7
      Commit:  fcfdef8d6b
    
    .NET Core SDKs installed:
      2.2.102 [C:\Program Files\dotnet\sdk]
      2.2.109 [C:\Program Files\dotnet\sdk]
      2.2.207 [C:\Program Files\dotnet\sdk]
      3.1.107 [C:\Program Files\dotnet\sdk]
      3.1.401 [C:\Program Files\dotnet\sdk]
    
    .NET Core runtimes installed:
      Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    
    To install additional .NET Core runtimes or SDKs:
      https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  - *VS Code*
        Version: 1.49.0 (system setup)
        Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
        Date: 2020-09-10T13:22:08.892Z (1 wk ago)
        Electron: 9.2.1
        Chrome: 83.0.4103.122
        Node.js: 12.14.1
        V8: 8.3.110.13-electron.0
        OS: Windows_NT x64 10.0.17763
  - *Visual Studio 2019*
        Version 16.7.2
        ASP.NET and Web Tools 2019 -- 16.7.532.28833
        ASP.NET Core Razor Language Services -- 16.1.0.2035807+72d099b...
        ASP.NET Web Frameworks and Tools 2019 -- 16.7.532.28833

**Comment by blowdart** [comment]
CustomPrincipals flat out aren't supported. Everything is ClaimsPrincipal now. Sometimes, if you're lucky we won't touch your principal and it "might" work, but it's more likely not to.

Have you tried this without a custom principal? What do you need one for?

**Comment by psaxton** [comment]
@blowdart I am refactoring our AAA code to use multiple authentication schemes and authorization profiles to satisfy new requirements. My current implementation uses the CustomPrincipal as a sort of user context. User specific resources are attached to the custom principal and used in  the action methods of controllers and potentially further down the stack.

It is understood that overwriting the Principal on the context will not be an optimal solution. New schemes and profiles will not continue this pattern. *However*, it still feels wrong that simply requiring the authentication scheme which is already being used in an authorization profile changes the side effects of that authentication scheme; The Type provided to the OnTokenAuthenticated delegate has a setter for the Principal and I can find no official documentation indicating that it should not be used.

One potential path forward is to add claims by adding an IIdentity to the claims principal within OnTokenAuthenticated, rather than replacing it outright. e.g.

```csharp
OnTokenValidated = context =>
{
	context.Principal.AddIdentity(
		new ClaimsIdentity(new[] { new Claim("AuthScheme", CustomPrincipalScheme) }),
		// ...
	);
	return Task.CompletedTask;
}
```

I have tried this in the test setup linked in this issue and it appears to work. There will be a need to provide values which will not be included in the client supplied token for some of the authentication schemes. The concern is that I may again find a scenario where the Principal is changed outside of our code. This project has many hundreds of controller actions and this refactoring is a significant undertaking. I would like to ensure that it is done correctly rather than having to revisit this if there may be another configuration in which the context principal is unexpectedly modified.

**Comment by blowdart** [comment]
We don't promise anywhere we won't stomp on your principal/identity during auth, because that's rather what auth does, take information from the rest and construct an identity from it.

@Tratcher / @HaoK any best practice/suggested approach here?

**Comment by psaxton** [comment]
I understand other stages of the AAA pipeline may overwrite the principal just as we have done. It seems weird that simply asserting the scheme is used for an Authorization profile would change the observed behavior. Generally assertions are assumed to be side-effect free.

**Comment by HaoK** [comment]
Its not the require assertion that has a side effect, its `.AddAuthenticationSchemes(CustomPrincipalScheme)` setting a scheme triggers explicit authentication which is why the principal is updated

**Comment by psaxton** [comment]
I am not opposed to closing this ticket if there is nothing more to be considered.
