### ISSUE TITLE
Gated incoming requests

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2623]
_From @JunTaoLuo on Thursday, September 15, 2016 2:13:40 PM_

In Orchard CMS, there was a feature where multiple incoming requests will block until the response for the first one is generated and is used to satisfy all waiting requests. Will need to investigate how this can be supported, either within the middleware or by the user given the available extensibility points.

cc @sebastienros 

_Copied from original issue: aspnet/ResponseCaching#37_

**Comment by aspnet-hello** [comment]
_From @muratg on Thursday, May 25, 2017 3:42:55 PM_

@sebastienros How much do you want this? Would you like to talk design, and possibly send a PR?

cc @glennc

**Comment by aspnet-hello** [comment]
_From @sebastienros on Thursday, May 25, 2017 3:54:28 PM_

/cc @rynowak as he was key in the decision to have it in tag helpers.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
