### ISSUE TITLE
ApiExplorer not handling multiple routes on same action method correctly

### ISSUE THREAD

**Issue by domaindrivendev** [dotnet/aspnetcore#26234]
### Describe the bug

Given the following action method bound to multiple routes:

```csharp
[HttpGet]
[Route("foo")]
[Route("bar/{id}")]
public IActionResult Get(int id = 0)
```

As expected, the ApiExplorer surfaces two `ApiDescription` instances, one for each route. However, for the first route "foo", the `ApiDescription` includes the `id` path parameter, despite the fact that it's not part of the route template. For example, here's the ApiExplorer data (serialized as json):

```
[
  {
    relativePath: "Test/foo",
    httpMethod: "GET",
    parameters: [
      {
        name: "id",
        source: {
          displayName: "Path",
          id: "Path",
          isGreedy: false,
          isFromRequest: true,
        },
      }
    ],
  },
  {
    relativePath: "Test/bar/{id}",
    httpMethod: "GET",
    parameters: [
      {
        name: "id",
        source: {
          displayName: "Path",
          id: "Path",
          isGreedy: false,
          isFromRequest: true,
        },
      }
    ],
  },
]
```

### To Reproduce

```
> git clone git@github.com:domaindrivendev/ApiExplorerIssue.git
> cd ApiExplorerIssue
> dotnet run

Then navigate to "http://localhost:5000/apidescriptions" to see the ApiExplorer data
``` 

### Further technical details
- ASP.NET Core version: 3.1

**Comment by domaindrivendev** [comment]
Here's the corresponding downstream issue that was originally created in Swashbuckle.AspNetCore:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1834

**Comment by domaindrivendev** [comment]
In the meantime, if you're really stuck you could wire up an `IOperationFilter` (see readme) that detects this anomaly and corrects it by removing the parameter from the `operation.parameters` collection.

**Comment by frankracis-work** [comment]
I had the filter look at ApiDescription.ParamaterDescriptions, and if In==Path and !IsRequired, removed it from the operation.Parameters list.     I don't know that this will work for every case, but it was enough for my routes.

**Comment by brunolins16** [comment]
@domaindrivendev the short answer for that is, you could workaround it by setting `ApiBehaviorOptions.SuppressInferBindingSourcesForParameters` to `true`. Eg.:

``` csharp
builder.Services.Configure<ApiBehaviorOptions>(options => {
    options.SuppressInferBindingSourcesForParameters = true;
});
```

Now, to give you more details. When your controller is annotated with `[ApiController]` it will be applied some conventions and one of them is the `InferParameterBindingInfoConvention` that will basically do what is described here [ApiBehaviorOptions.SuppressInferBindingSourcesForParameters Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apibehavioroptions.suppressinferbindingsourcesforparameters?view=aspnetcore-6.0)

![image](https://user-images.githubusercontent.com/12376385/149391417-770152ca-8055-4a62-bee7-526185e8e07f.png)

As you can see, in your case you do have a route where the parameter is included in the route, that means this parameter will be inferred as `Binding` from `Path` and that will affect how Swashbuckle deal with the route and setting both as `FromPath` and `Required`.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/45875d5e222f9f7369b6e5f31e1ece112fa81aaa/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs#L23

Once you have the property `SuppressInferBindingSourcesForParameters` set as true the binding source will not be inferred and you will have the behavior that you are looking for:

``` json
{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPISample",
    "version": "1.0"
  },
  "paths": {
    "/WeatherForecast/foo": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "Foo",
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/WeatherForecast/bar/{id}": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "Bar",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": { }
}
```

Just remind that it is a global configuration that will affect all API controllers that might cause some issues to your current APIs.

**Comment by brunolins16** [comment]
@domaindrivendev In addition to my previous comment, it is a bug and it should be work correct without you need to change the `SuppressInferBindingSourcesForParameters` but while we do not have a fix, that is the option other than the option you mentioned about `IOperationFilter`

**Comment by halter73** [comment]
> Once you have the property `SuppressInferBindingSourcesForParameters` set as true the binding source will not be inferred and you will have the behavior that you are looking for

Doesn't this change the actual behavior of the controller and not just the ApiExplorer model? Based on the linked docs, I would expect that the `id` parameter would no longer be inferred to come from the path in the `"/WeatherForecast/bar/{id}"` case (although the swagger indicates otherwise). Do you have to use param attributes after setting `SuppressInferBindingSourcesForParameters` to true?

**Comment by brunolins16** [comment]
> Doesn't this change the actual behavior of the controller and not just the ApiExplorer model? Based on the linked docs, I would expect that the `id` parameter would no longer be inferred to come from the path in the `"/WeatherForecast/bar/{id}"` case (although the swagger indicates otherwise). Do you have to use param attributes after setting `SuppressInferBindingSourcesForParameters` to true?

@halter73, exactly that is why I included a small disclaimer (below) at the end. However, I tested it and the parameter binding still working, without adding the attributes, for me but I did not check exactly why.

![image](https://user-images.githubusercontent.com/12376385/149584295-a56cc79d-3a07-413a-8e85-b6b190fcc563.png)
