### ISSUE TITLE
5.0 docs: PEM support

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#26240]
PEM support (https://github.com/dotnet/aspnetcore/pull/23584)

Related: https://github.com/dotnet/AspNetCore.Docs/issues/19113

**Comment by jkotalik** [comment]
@javiercn would you be able to take this doc issue?

**Comment by jkotalik** [comment]
bump @javiercn

**Comment by halter73** [comment]
@javiercn I think this is just a tracking issue for https://github.com/dotnet/AspNetCore.Docs/issues/19113

**Comment by blowdart** [comment]
Hah, I was looking for the docs an hour ago to help someone in CSE do weird things. No wonder I couldn't find it.
