### ISSUE TITLE
Partial responses and range requests

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2624]
_From @JunTaoLuo on Thursday, September 15, 2016 2:09:20 PM_

Currently we don't cache partial responses with status code 206. These responses are cacheable but right now the user will need to override our cache policy providers to cache them. Also there is no current mechanism to coalesce overlapping partial responses and no way to serve a portion of the response given range requests.

_Copied from original issue: aspnet/ResponseCaching#36_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, September 15, 2016 2:20:24 PM_

One subset of this functionality would be easy to implement, the ability to handle range requests when the full body is available in the cache. Range requests should already work today, we just ignore the range header. If we checked the range header we could send a subset of the body with a 206 status instead.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
