### ISSUE TITLE
5.0 docs: "SslProtocols" and "ClientCertificateMode" settable via config

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#26246]
* [ ] "SslProtocols" settable via config (https://github.com/dotnet/aspnetcore/pull/22910)
* [ ] "ClientCertificateMode" settable via config (https://github.com/dotnet/aspnetcore/pull/24076)

**Comment by Tratcher** [comment]
These are already covered under the SNI section, but could use mentions elsewhere. I'll add a few.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#sni-in-configuration
