### ISSUE TITLE
5.0 docs: Document WriteAsJsonAsync and ReadFromJsonAsync extension methods

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#26250]
Extension methods were added in 5.0 to make it easier to read and write JSON without using a web framework like MVC.

Mentioned here - https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-6/

Where is a good place to put this documentation?

**Comment by jkotalik** [comment]
@JamesNK have you gotten the chance to look into this?

**Comment by JamesNK** [comment]
I'm reaching out to people to figure out where to put these docs and how to frame them.
