### ISSUE TITLE
Option for WeakReference caching 

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2625]
_From @benaadams on Saturday, July 2, 2016 8:37:10 PM_

So cached items can be evicted on GC rather than having infrequently accessed items remaining cached in memory until expiry (utilizing [sample for caching weak references](https://github.com/aspnet/Caching/commit/a197fe623325e67f5a9a33f759499bcd4828d235) by @Tratcher)

Related #8 "Option for disk-backed cache"

_Copied from original issue: aspnet/ResponseCaching#9_

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, August 10, 2016 2:34:08 PM_

After doing perf investigation, we may end up bringing this back to 1.1.

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
