### ISSUE TITLE
Duplicate Templates showing

### ISSUE THREAD

**Issue by 274188A** [dotnet/aspnetcore#26264]
Environment: Visual Studio Enterprise 2019 Preview
16.8.0 Preview 3.1

### Describe the bug
Seeing Duplicate Templates for Blazor Server and Blazor wasm

### To Reproduce
Click `Create a new project`
Select `Blazor App`
Click Next
Select .NET 5.0 in the dropdown

Shows the following (demonstrating the two difference template sources):
![image](https://user-images.githubusercontent.com/40014477/94110743-b0db1d00-fe75-11ea-8fa7-eaed0bb11a03.png)

![image](https://user-images.githubusercontent.com/40014477/94110849-d7995380-fe75-11ea-9465-e8d00264e666.png)

We will close this issue if:
I see one template for `Blazor Server App` and `Blazor WebAssembly App`

### Output from "dotnet new -u"
Currently installed items:
  Microsoft.DotNet.Common.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.5.0
      Version: 5.0.0-rc.1.20431.3
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.5.0

  Microsoft.DotNet.Common.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.2.1
      Version: 1.0.2-beta3
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.2.1

  Microsoft.DotNet.Test.ProjectTemplates.2.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.2.1
      Version: 1.0.2-beta4.20420.1
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.2.1

  Microsoft.DotNet.Web.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.3.1
      Version: 3.1.7
      Author: Microsoft
    Templates:
      Blazor Server App (blazorserver) C#
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      ASP.NET Core gRPC Service (grpc) C#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (webapp) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
      Worker Service (worker) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.3.1

  Microsoft.Identity.Web.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.Identity.Web.ProjectTemplates
      Version: 0.4.0-preview
      Author: Microsoft
    Templates:
      Blazor Server App (Microsoft identity platform) (blazorserver2) C#
      Blazor WebAssembly App (blazorwasm2) C#
      ASP.NET Core Web App (Microsoft identity platform) (webapp2) C#
      ASP.NET Core Web App (Model-View-Controller, Microsoft identity platform) (mvc2) C#
      ASP.NET Core Web API (Microsoft.Identity.Platform) (webapi2) C#
    Uninstall Command:
      dotnet new -u Microsoft.Identity.Web.ProjectTemplates

  Microsoft.AspNetCore.Components.WebAssembly.Templates
    Details:
      NuGetPackageId: Microsoft.AspNetCore.Components.WebAssembly.Templates
      Version: 3.2.1
      Author: Microsoft
    Templates:
      Blazor WebAssembly App (blazorwasm) C#
    Uninstall Command:
      dotnet new -u Microsoft.AspNetCore.Components.WebAssembly.Templates

  Microsoft.DotNet.Web.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.5.0
      Version: 5.0.0-rc.1.20451.17
      Author: Microsoft
    Templates:
      Blazor Server App (blazorserver) C#
      Blazor WebAssembly App (blazorwasm) C#
      ASP.NET Core Empty (web) C#
      ASP.NET Core Empty (web) F#
      ASP.NET Core gRPC Service (grpc) C#
      Razor Class Library (razorclasslib) C#
      ASP.NET Core Web App (webapp) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) C#
      ASP.NET Core Web App (Model-View-Controller) (mvc) F#
      ASP.NET Core Web API (webapi) C#
      ASP.NET Core Web API (webapi) F#
      Worker Service (worker) C#
      Worker Service (worker) F#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.5.0

  Microsoft.DotNet.Common.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.3.1
      Version: 3.1.7
      Author: Microsoft
    Templates:
      Class library (classlib) C#
      Class library (classlib) F#
      Class library (classlib) VB
      Console Application (console) C#
      Console Application (console) F#
      Console Application (console) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.3.1

  Microsoft.DotNet.Test.ProjectTemplates.3.1
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.3.1
      Version: 1.0.2-beta4.20420.1
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.3.1

  Microsoft.DotNet.Common.ItemTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Common.ItemTemplates
      Version: 5.0.0-rc.1.20431.3
      Author: Microsoft
    Templates:
      dotnet gitignore file (gitignore)
      global.json file (globaljson)
      NuGet Config (nugetconfig)
      Solution File (sln)
      Dotnet local tool manifest file (tool-manifest)
      Web Config (webconfig)
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Common.ItemTemplates

  Microsoft.DotNet.Wpf.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Wpf.ProjectTemplates
      Version: 5.0.0-rc.1.20451.6
      Author: Microsoft
    Templates:
      WPF Application (wpf) C#
      WPF Application (wpf) VB
      WPF Class library (wpflib) C#
      WPF Class library (wpflib) VB
      WPF Custom Control Library (wpfcustomcontrollib) C#
      WPF Custom Control Library (wpfcustomcontrollib) VB
      WPF User Control Library (wpfusercontrollib) C#
      WPF User Control Library (wpfusercontrollib) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Wpf.ProjectTemplates

  NUnit3.DotNetNew.Template
    Details:
      NuGetPackageId: NUnit3.DotNetNew.Template
      Version: 1.8.1
      Author: akharlov
    Templates:
      NUnit 3 Test Project (nunit) C#
      NUnit 3 Test Item (nunit-test) C#
      NUnit 3 Test Project (nunit) F#
      NUnit 3 Test Item (nunit-test) F#
      NUnit 3 Test Project (nunit) VB
      NUnit 3 Test Item (nunit-test) VB
    Uninstall Command:
      dotnet new -u NUnit3.DotNetNew.Template

  Microsoft.DotNet.Test.ProjectTemplates.5.0
    Details:
      NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.5.0
      Version: 1.0.2-beta4.20420.1
      Author: Microsoft
    Templates:
      Unit Test Project (mstest) C#
      Unit Test Project (mstest) F#
      Unit Test Project (mstest) VB
      xUnit Test Project (xunit) C#
      xUnit Test Project (xunit) F#
      xUnit Test Project (xunit) VB
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.5.0

  Microsoft.DotNet.Web.ItemTemplates
    Details:
      NuGetPackageId: Microsoft.DotNet.Web.ItemTemplates
      Version: 5.0.0-rc.1.20451.17
      Author: Microsoft
    Templates:
      Protocol Buffer File (proto)
      Razor Component (razorcomponent) C#
      Razor Page (page) C#
      MVC ViewImports (viewimports) C#
      MVC ViewStart (viewstart) C#
    Uninstall Command:
      dotnet new -u Microsoft.DotNet.Web.ItemTemplates

  Microsoft.Dotnet.WinForms.ProjectTemplates
    Details:
      NuGetPackageId: Microsoft.Dotnet.WinForms.ProjectTemplates
      Version: 5.0.0-rc.1.20451.14
      Author: Microsoft
    Templates:
      Windows Forms (WinForms) Application (winforms) C#
      Windows Forms (WinForms) Application (winforms) VB
      Windows Forms (WinForms) Control Library (winformscontrollib) C#
      Windows Forms (WinForms) Control Library (winformscontrollib) VB
      Windows Forms (WinForms) Class Library (winformslib) C#
      Windows Forms (WinForms) Class library (winformslib) VB
    Uninstall Command:
      dotnet new -u Microsoft.Dotnet.WinForms.ProjectTemplates

  Peachpie.Templates
    Details:
      NuGetPackageId: Peachpie.Templates
      Version: 1.0.4
      Author: peachpie, Petr Houska, Jakub Misek
    Templates:
      Class library (classlib) PHP
      ASP.NET Core WordPress App (wpdotnet) C#
      Console Application (console) PHP
      ASP.NET Core Empty (web) PHP
    Uninstall Command:
      dotnet new -u Peachpie.Templates

### Visual Studio Info
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 3.1
VisualStudio.16.Preview/16.8.0-pre.3.1+30516.212
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA652
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.442.31521
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2046102+2078c50b948ee8c2e2072fc69f5147b15e456b56
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.442.31521
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.442.31521
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.442.31521
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.30403.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62009.04150
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20902.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.30509
Visual C++ for Linux Development

Visual F# Tools   16.8.0-beta.20428.2+068ebd3c599bc5a47163a18b8b90d2fe5517186e
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by mkArtakMSFT** [comment]
@vijayrkn what information would be needed here to understand what's causing this?

**Comment by vijayrkn** [comment]
Adding @phenning - How are template duplicates removed when they installed from both CLI & SDK?

**Comment by phenning** [comment]
What should happen is the highest nupkg version should win. 

If the identities of the packages changes - we'd use both, but the group Ids would also need to differ.

**Comment by phenning** [comment]
@mkArtakMSFT, @vijayrkn  which is exactly is what is happening here. 

I'd bet anything those blazor templates from the identity package have different group identities, but the same name and description as the standard blazor template.  They may have different names/descriptions in template.json, but the entries in the hostfile or strings.json are probably exactly the same.

```
Microsoft.Identity.Web.ProjectTemplates
Details:
NuGetPackageId: Microsoft.Identity.Web.ProjectTemplates
Version: 0.4.0-preview
Author: Microsoft
Templates:
Blazor Server App (Microsoft identity platform) (blazorserver2) C#
Blazor WebAssembly App (blazorwasm2) C#
```

**Comment by mkArtakMSFT** [comment]
@jmprieur what is the guidance here? Should the experimental Identity packages be uninstalled already?

@274188A we believe you have both 5.0 SDK as well as experimental Identity packages installed, which bring in duplicate templates.

**Comment by 274188A** [comment]
I ran the uninstall command to fix: 

`dotnet new -u Microsoft.Identity.Web.ProjectTemplates`

**Comment by jmprieur** [comment]
@mkArtakMSFT : it depends. 
The experimental Identity package also brings .NET Core 3.1. For customers who want to use .NET 5.0, yes.
