### ISSUE TITLE
Publish ASP.NET Core app deploy code analysis dll

### ISSUE THREAD

**Issue by Gambero81** [dotnet/aspnetcore#26269]
When publish an ASP.NET Core app, all the code analysis modules related to packages used in the application are published.

Can be avoided to publish these assemblies, who are useful only in debug?

**Comment by pranavkm** [comment]
@Gambero81 do you mean the Microsoft.CodeAnalysis.* dlls? Those are added as part of runtime compilation. Depending on if you use the feature in a published app, you could choose to manually remove it. Unfortunately we cannot do that by default because some apps use that when it's published.

**Comment by Gambero81** [comment]
Yes, i can't figure how are used in a published app, are they related to static code analysis? I can understand a debug deploy, but also for release? What's a sample case of use?
Thanks

**Comment by pranavkm** [comment]
Those assemblies contain the compiler used to compile views at runtime. It's not uncommon to see rely on this in their published app.
