### ISSUE TITLE
Windows Authorization works in debug on IIS Express but not in IIS server

### ISSUE THREAD

**Issue by LeviBickel** [dotnet/aspnetcore#26275]
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64

I have been fighting what seems to be a configuration error or a bug in ASP.Net Core 3.1. I am attempting to take in a Windows Authentication user and check if this user is in an AD group that has been specified in the appsettings.json. While in the debug mode locally running IIS Express everything works correctly. The user is authenticated, and the check for the AD group succeeds.

I publish this project to a folder and copy it to my internal IIS server which is connected to the domain. I have configured the IIS server (Windows Server 2016 / IIS Version 10) for windows authentication and disabled anonymous authentication. When I attempt to navigate to the application I get the error in the attached screenshot. 
![Error](https://user-images.githubusercontent.com/42508566/94219502-35dd2b00-fea4-11ea-8e4c-8093cd50398c.PNG)

ClaimsTransformer Code:

```csharp
public class ClaimsLoader
{
public static string Role { get; set; }
public static bool IsInGroup(ClaimsPrincipal User, string GroupName)
{
    bool check = false;
    var user = (WindowsIdentity)User.Identity;
    if (user.Groups != null)
    {
        foreach (var group in user.Groups)
        {
            check = group.Translate(typeof(NTAccount)).ToString().Contains(GroupName);
            if (check)
                break;
        }
    }
    return check;
} 
}
```

Controller code:
```csharp
if (ClaimsLoader.IsInGroup(User, _config.GetValue<string>("Admin")))
{
    ClaimsLoader.Role = "Administrator"; 
}
else if (ClaimsLoader.IsInGroup(User, _config.GetValue<string>("Modify")))
{
    ClaimsLoader.Role = "Modify";
}
else
{
    ClaimsLoader.Role = "";
}
```

Based on the articles I have read, this is the way to do this. Most are referencing .net core 2.0 so has something changed between the versions making this obsolete? I find it very frustrating that this works on IIS Express with windows Authentication but not on IIS. I have attached my IIS windows authentication settings which is working. It is the role conversion that doesn't work in IIS. I am not using SignalR to my knowledge. 
![IIS Authentication](https://user-images.githubusercontent.com/42508566/94014013-2eb10280-fd68-11ea-98f5-78abb0aeee9c.PNG)
![Providers](https://user-images.githubusercontent.com/42508566/94014014-2f499900-fd68-11ea-8e70-08b91952f331.PNG)
![WinAuth](https://user-images.githubusercontent.com/42508566/94014015-2f499900-fd68-11ea-9b4d-7288220e3e75.PNG)

This is my first post on here so, please let me know if I missed some information that is needed.

**Comment by blowdart** [comment]
Can we see your startup.cs file please (after you've removed any secrets).

Your error shows an error in CheckAdGroupRequirement, at line 36, but you're not giving us that line, or that class.

**Comment by LeviBickel** [comment]
> Can we see your startup.cs file please (after you've removed any secrets).
> 
> Your error shows an error in CheckAdGroupRequirement, at line 36, but you're not giving us that line, or that class.

So sorry for the confusion. I put the wrong error, that was from another attempt. I have edited the original post with the correct error.

**Comment by blowdart** [comment]
We're still going to need to see your startup.cs I'm afraid,

**Comment by LeviBickel** [comment]
> We're still going to need to see your startup.cs I'm afraid,

`using Macro.Data;
using Macro.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Server.IISIntegration;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Macro
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
        
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddControllersWithViews();

            services.AddDbContext<MacroContext>(options =>
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddAuthentication(IISDefaults.AuthenticationScheme);
           
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
`

**Comment by blowdart** [comment]
You are missing an ` services.AddAuthorization();` after services.AddAuthentication().

Is this in process or out of process IIS hosting?

**Comment by LeviBickel** [comment]
> You are missing an ` services.AddAuthorization();` after services.AddAuthentication().
> 
> Is this in process or out of process IIS hosting?

I have added services.AddAuthorization() with no change. This is running in process.

**Comment by blowdart** [comment]
@shirhatti this seems IIS related so can you have someone take a look?

**Comment by LeviBickel** [comment]
@blowdart or @shirhatti Has there been any progress on the IIS front?

**Comment by blowdart** [comment]
Let me email IIS people

**Comment by LeviBickel** [comment]
@blowdart Thank you!

**Comment by shirhatti** [comment]
@LeviBickel I'm able to repro what you're reporting.

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Security.Claims.ClaimsIdentity' to type 'System.Security.Principal.WindowsIdentity'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void* toTypeHnd, Object obj) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs:line 374
```

@Tratcher can I get your help to investigate this? I have a  captured dump/live repro handy

**Comment by Tratcher** [comment]
@shirhatti do you have the full stack trace? Who is trying that hard cast?

**Comment by shirhatti** [comment]
@LeviBickel My hypothesis is that the behavior you're observing is because you don't have anonymous authentication disabled

Can you post the relevant section from your applicationHost.config?

```xml
    <location path="AppPool2">
        <system.webServer>
            <security>
                <authentication>
                    <anonymousAuthentication enabled="false" />
                </authentication>
            </security>
        </system.webServer>
    </location>
```

**Comment by LeviBickel** [comment]
@shirhatti Thank you for the response. I have my web.config file below not too sure if this is what you are asking for. I have anonymous authentication disabled in IIS which is in the screenshots in my original post. Copying the security section you have above results in a 500.19 error stating that line is locked. IIS will not read the authentication settings in the GUI with that line added either. Removing the line results in IIS returning to the state in the screenshots. Anonymous Authentication is disabled and Windows authentication is enabled.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\Macro.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>`

**Comment by shirhatti** [comment]
This will be present in the `C:\Windows\System32\inetsrv\config\applicationHost.config`

**Comment by LeviBickel** [comment]
@shirhatti Thank you. This is what was under the affected application:
`<system.webServer>
            <security>
                <authentication>
                    <anonymousAuthentication enabled="false" />
                    <windowsAuthentication enabled="true" useKernelMode="true">
                        <extendedProtection tokenChecking="None" />
                    </windowsAuthentication>
                </authentication>
            </security>
        </system.webServer>`

**Comment by shirhatti** [comment]
@Tratcher Looks like our hypothesis that the authenticated user is the anonymous identity is incorrect. Any other ideas?

**Comment by Tratcher** [comment]
Not without a repro app.

**Comment by LeviBickel** [comment]
@Tratcher  here is a link to my repo. Again this will run in iis express using using Visual Studio 2019 debug but, not in full IIS.

https://github.com/LeviBickel/Macro

**Comment by BrennanConroy** [comment]
Triage: We think you're still authenticated with an anonymous identity and this only repros on your environment.

Can you try this on a clean machine to see if it's an environmental issue?
You may need to contact [support](http://support.microsoft.com/supportforbusiness/productselection?sapId=ef53b119-5f8c-7343-2a0f-f5008a1399b9) to figure out what is going on.

**Comment by LeviBickel** [comment]
@BrennanConroy Thank you for your assistance. So, everything looks right to you? I guess I will be contacting support. I tried on a new server with the same result.

**Comment by LeviBickel** [comment]
Yikes, just went to open a ticket and it costs $500. Guess this will go unsolved and I will attempt to recreate the project with individual accounts or something.

**Comment by BrennanConroy** [comment]
I'm sorry about that 😢 

Unfortunately, we have been unable to repro the issue with your app on our machines. Closing as we can't do anything more here.
