### ISSUE TITLE
.NET5 RC1: WebAssemblyPrerendered with authentication enabled

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#26270]
Trying to activate WASM pre-rendering gets a lot more involved and complicated when you are beyond a Hello World app. E.g. if you have authentication in your Blazor WASM client and want to do pre-rendering, you get this exception:

```
InvalidOperationException: Cannot provide a value for property 'AuthenticationStateProvider' on type 'Microsoft.AspNetCore.Components.Authorization.CascadingAuthenticationState'. There is no registered service of type 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider'.
Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)

```

Is there a best practice here to solve this?

.cc @guardrex 

.NET 5 SDK: 5.0.100-rc.1.20452.10

**Comment by guardrex** [comment]
Thanks @ChristianWeyer ... Cross-linking the [docs issue (dotnet/AspNetCore.Docs #19503)](https://github.com/dotnet/AspNetCore.Docs/issues/19503) for my visibility to this.

**Comment by ChristianWeyer** [comment]
Just a quick check @captainsafia @javiercn: do you know when we can see a viable solution for the issue at hand?
(Including https://github.com/dotnet/aspnetcore/issues/27592)

Thanks a lot.

**Comment by danroth27** [comment]
We're working on this as part of #27592.
