### ISSUE TITLE
Create feature interface for opting in/out of server side caching.

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2627]
_From @Tratcher on Friday, June 12, 2015 10:08:31 AM_

Needs design

_Copied from original issue: aspnet/ResponseCaching#5_

**Comment by aspnet-hello** [comment]
_From @benaadams on Sunday, April 24, 2016 4:03:54 PM_

Caching Attribute? Also paths from config so recompile not needed.

Method/Controller etc might not want to use the CacheControl header for the server in memory cache.

Or cache to disk > x Bytes; would want to integrate with static files in some way so it doesn't save to disk again; unless its transformed like gzipped.

**Comment by Varorbc** [comment]
any progress?


https://github.com/filipw/Strathweb.CacheOutput/issues/217

**Comment by JunTaoLuo** [comment]
Work will be tracked in https://github.com/dotnet/aspnetcore/issues/27387
