### ISSUE TITLE
Responses to POST can be cached for future GET methods

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2628]
_From @darrelmiller on Tuesday, June 9, 2015 5:59:22 PM_

https://github.com/aspnet/ResponseCaching/blob/chrross/initial/src/Microsoft.AspNet.ResponseCaching/CachingContext.cs#L39

This is a weird one that requires using GET as the cache key instead of using the original request method.

_Copied from original issue: aspnet/ResponseCaching#4_

**Comment by JunTaoLuo** [comment]
It's unlikely we'll implement this unless there's more demand for this issue.
