### ISSUE TITLE
CSS isolation error when Blazor component Nuget packaged 

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#26292]
@mkArtakMSFT I'm facing one more issue related to CSS. The above mentioned isolated CSS was working with WebAssembly projects when Razor Class Library project was referenced directly. **But when it is packaged to Nuget and used via Nuget package** not directly from project reference. Got this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The scoped css file 'C:\Users\Major\.nuget\packages\majorsoft.blazor.components.loading\0.9.1-rc.1.20452.10\contentFiles\any\net5.0\LoadingPage.razor.css' was defined but no associated razor component was found for it.	Blazor.Components.TestApp (Samples\Blazor.Components.TestApp)	C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.ScopedCss.targets	97	
```

_Originally posted by @majorimi in https://github.com/dotnet/aspnetcore/issues/26144#issuecomment-697930110_

**Comment by pranavkm** [comment]
Thanks @majorimi this looks like a bug in our SDK.

**Comment by majorimi** [comment]
Probably. But it is still RC so have time to fix... Thanks.

Please also check is **"Scoped CSS merge"** works or not? What I mean by that what if a Blazor project uses an internal Component Library (e.g. project reference) with Scoped CSS. And also references some external 3rd party (e.g. Nuget packages) with with Scoped CSS. 

**In that case will the 2 different CSS merged into `"_framework/scoped.styles.css"`? Or one will override the other?**

**Comment by captainsafia** [comment]
@majorimi Can you share a repro project?

**Comment by majorimi** [comment]
@captainsafia Sure [here it is](https://github.com/majorimi/blazor-components/tree/dev/update-demo-app-to-nuget).

I'm developing a set of Blazor components and for testing I have 2 TestApps (one `WebAssembly` and one `Server hosted`). These are referencing the Razor Class Libraries as project ref. So I can test any changes by running the apps locally.

The issue is happening in the **demo/Blazor.Components.DemoApp**. This app is [deployed here](https://blazorextensions.z6.web.core.windows.net/) to show the usage of my components. And it is intended to use the components from [Nuget](https://www.nuget.org/profiles/Blazor.Components). But it has a build error with `scoped CSS` from Nuget package.

Thanks for your help.

**Comment by javiercn** [comment]
> In that case will the 2 different CSS merged into one file `"_framework/scoped.styles.css"`? Or one will override the other?

The two files will be concatenated together (the one from the referenced project and the one from the NuGet package). We have however, changed this in RC2 and the files will be brought in directly via an `import` directive relative to the application path bundle.

**Comment by javiercn** [comment]
I'm not able to reproduce the issue with the repro you provided, I've looked at the msbuild binlog and it works as expected. I would suggest you check your environment to ensure you are using the RC1 SDK, clean the bin and obj folders on the projects and perform a clean build.

If your issue still persists, then please try to come up with a minimal repro project that showcases the issue and detailed instructions on how to reproduce it. It's easy for us to do things differently and don't trigger the issue you are seeing.

**Comment by majorimi** [comment]
Thanks for checking it. Have you built the specified branch: **`dev/update-demo-app-to-nuget`**. I have separated out the non building code to a new branch since it would make CI/CD pipeline fail. `master` branch works.
- Yes I have checked `.NET5 RC1` installed...
- Cleaned the `bin` and `obj`. 

Still got the same build error. I also have CI pipeline in Azure Devops  which runs on a clean machine. Added a step to install `version: '5.0.100-rc.1.20452.10'`. And build fails there too. Very weird issue...

/opt/hostedtoolcache/dotnet/sdk/5.0.100-rc.1.20452.10/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets(97,3): error : The scoped css file '/home/vsts/.nuget/packages/majorsoft.blazor.components.loading/0.9.30-rc.1.20452.10/contentFiles/any/net5.0/LoadingPage.razor.css' was defined but no associated razor component was found for it. [/home/vsts/work/1/s/demo/Blazor.Components.DemoApp/Blazor.Components.DemoApp.csproj]
##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1**

![image](https://user-images.githubusercontent.com/7632824/94602548-50911480-0295-11eb-8b89-9563d25a5ffc.png)

**Comment by majorimi** [comment]
- Created a brand new `.NET 5 Blazor WebAssembly` project.
- Installed my Nuget package `dotnet add package Majorsoft.Blazor.Components.Loading`

**Immediately got the same build error. Is it possible that the Nuget package is broken?**

Here is the .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Majorsoft.Blazor.Components.Loading" Version="0.9.30-rc.1.20452.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-rc.1.20451.17" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-rc.1.20451.17" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0-rc.1.20451.14" />
  </ItemGroup>
</Project>
```

Even added the packaged component to the Index.razor:
![image](https://user-images.githubusercontent.com/7632824/94607685-82f24000-029c-11eb-8c21-56000bd91458.png)

**Comment by javiercn** [comment]
@majorimi ah, I think I know what it's happening.

It looks like somehow the file got added as part of the nuget package as content and that's causing the issue.

**Comment by majorimi** [comment]
Hmm I was using the standard .Net Packaging  form on the project's properties window. But don't really understand the problem. CSS and JS resources should be packaged anyway. Otherwise how you can distribute these resources in case of your component Nuget packaged?

**Comment by javiercn** [comment]
@majorimi they are scoped css files, so the original css sources are not packaged, only the generated assets.

**Comment by majorimi** [comment]
Ok. Please check my .csproj file: https://github.com/majorimi/blazor-components/blob/master/src/Blazor.Components.Loading/Blazor.Components.Loading.csproj

As I can see it does not specify that CSS should be resource. I don't have .nuspec file specified separately. Just using 'dotnet pack' 
So probably there's the issue...

**Comment by javiercn** [comment]
@majorimi I believe we fixed something in this area in RC2, so I would suggest you try using a nightly build from [here](https://github.com/dotnet/installers) to see if that fixes your issue.

Alternatively, you can likely set pack to false explicitly and that should hopefully do it.

**Comment by majorimi** [comment]
Yes I have got similar answers for other issues to use RC2. However it requires private Nuget feed as well since RC2 packages not published yet... Anyway let's wait for the official RC2 release. It should come in few days.

**Comment by HaoK** [comment]
@majorimi let us know if this works once you have tried things on RC2

**Comment by majorimi** [comment]
Ok will try out with RC2 and let you know.
Meanwhile this should be labeled as bug since the default .Net Packaging generates a wrong Nuget package.

**Comment by pranavkm** [comment]
Feel free to reopen this if you continue seeing this after upgrading to rc2.

**Comment by majorimi** [comment]
I can confirm that this issue was fixed with .NET5 RC2 update. Thanks.
