### ISSUE TITLE
[Blazor] Improving Debugging Experience

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#26290]
Hi,

Are you planning on substantially improving the debugging experience in the upcoming release? As it stands, the debugger is very incomplete and for any moderately complex task I end up using ``Console.WriteLine`` rather than the actual VS debugger. It's becoming a point of frustration with Blazor and the productivity suffers. Same thing with Razor editor crashing and the lack of hot reload, but these deficiencies are less critical.

Thank you for your attention.

**Comment by captainsafia** [comment]
We've made quite a few improvements to the debugging experience in .NET 5. I'd recommend trying the latest .NET 5 RC for these improvements. If you have particular problems with debugging, please open another issue with the relevant details.
