### ISSUE TITLE
Correct `ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders` test

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#26306]
See failure in #26188. [Debug details in build](https://dev.azure.com/dnceng/public/_build/results?buildId=829632&view=ms.vss-test-web.build-test-results-tab&runId=26450600&resultId=121980&paneView=debug) just show
``` text
Assert.False() Failure
Expected: False
Actual:   True

Stack trace
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders() in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 896
--- End of stack trace from previous location ---
```
About the same information is visible in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-26188-merge-8bbb6fc7bcbc494d95/Libuv.FunctionalTests--net5.0/console.9953b7bd.log The server logs in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-26188-merge-8bbb6fc7bcbc494d95/Libuv.FunctionalTests--net5.0/ResponseTests_ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders.log seem to indicate a normal client closed connection -> FIN progression.

**Comment by Tratcher** [comment]
This appears to be libuv specific and libuv has now been removed. Ready for unquarantine.
