### ISSUE TITLE
Activity.Baggage read from client should preserve items order

### ISSUE THREAD

**Issue by AndreyTretyak** [dotnet/aspnetcore#26303]
### Describe the bug
On receiving `Activity.Baggage` items in the `Correlation-Context` they are added to the current `Activity` using `AddBaggageItem()` method [here.](https://github.com/dotnet/aspnetcore/blob/c97a0020d8bab6d895bf821f6e47ee8722aa17d5/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L276) This method adds items to the beginning of the list, so on receiving `Key1=value1,Key2=value2` we would add `Key2=value2,Key1=value1` to the `Activity.Baggage`.

This is important because `Activity` allows having multiple items with the same key in the `Baggage` and `GetBaggageItem(string key)` returns the first item in the list with the required key. So if we have `Key1=value1,Key1=value2` then `GetBaggageItem("Key1")` will return `value1`, but after transfer order will reverse and it will return `value2`. The result would be changing depending on the number of transfers there were in the call chain and become practically unpredictable.

**Comment by mkArtakMSFT** [comment]
@Tratcher not sure whether this belongs here so please adjust if necessary.
