### ISSUE TITLE
TryMapToProjectedDocumentRange Returns Projected Range Where End < Start

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#26315]
![image](https://user-images.githubusercontent.com/14852843/94227265-cf113f00-feae-11ea-9601-9b8e4934d5a7.png)

**Comment by TanayParikh** [comment]
Counter.razor:
Occurs when you drag from end of `@using System.Diagnostics` to end of `@page "/counter"`.

Start: L88 C47
End: L75 C24

Which makes sense in terms of where `System.Diagnostics` and the page attribute are in the generated file.

In that case, is this really a bug? We should definitely have better handling in which if `end < start` then have `TryMapToProjectedDocumentRange` return false, but other than that I think this may actually be "expected" behavior.

cc/ @NTaylorMullen @ajaybhargavb @ryanbrandenburg 

```cshtml
@page "/counter"
@using System.Diagnostics

<h1>Counter</h1>

<p>Current count: @currentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

<SomeNewTag></SomeNewTag>


@code {
    private int currentCount = 0;

    public Counter(int currentCount)
    {
        this.currentCount = currentCount;
        Debugger.Launch();
    }

    private void IncrementCount()
    {
        currentCount++;
        System.Diagnostics.Debugger.Launch();
    }
}
```

Counter.razor.g.cs:

```csharp
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace blazorserver6.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\blazorserver\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\blazorserver\_Imports.razor"
using Microsoft.AspNetCore.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\blazorserver\_Imports.razor"
using Microsoft.AspNetCore.Components.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\blazorserver\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\blazorserver\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\blazorserver\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\blazorserver\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\blazorserver\_Imports.razor"
using blazorserver6;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\blazorserver\_Imports.razor"
using blazorserver6.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\blazorserver\Pages\Counter.razor"
using System.Diagnostics;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/counter")]
    public partial class Counter : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 12 "C:\blazorserver\Pages\Counter.razor"
       
    private int currentCount = 0;

    public Counter(int currentCount)
    {
        this.currentCount = currentCount;
        Debugger.Launch();
    }

    private void IncrementCount()
    {
        currentCount++;
        System.Diagnostics.Debugger.Launch();
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
```

**Comment by TanayParikh** [comment]
Ping @NTaylorMullen @ajaybhargavb @ryanbrandenburg

**Comment by NTaylorMullen** [comment]
Just to clarify End > Start when comparing generated/non-generated locations only correct? If that's the case then the "TryMapToProjectedRange" should fail if it can't map both start and end. Doesn't make sense to map one and not the other

**Comment by TanayParikh** [comment]
> Just to clarify End > Start when comparing generated/non-generated locations only correct? If that's the case then the "TryMapToProjectedRange" should fail if it can't map both start and end. Doesn't make sense to map one and not the other

Not quite. For a given range `x`, projected range `p(x)`, `End < Start => p(x).End < p(x).Start`. Essentially `p(x).Start`, the starting point from the razor file when projected onto the generated file, occurs after `p(x).End`, which is the ending point from the razor file when projected onto the generated file. Thereby we get a negative & invalid range. Does that make sense?

**Comment by ajaybhargavb** [comment]
@TanayParikh, could you include the callstack of what leads to the `TryMapToProjectedDocumentRange` call?

**Comment by TanayParikh** [comment]
> @TanayParikh, could you include the callstack of what leads to the `TryMapToProjectedDocumentRange` call?

That's the first image in the description.

**Comment by ajaybhargavb** [comment]
> That's the first image in the description. Can try to repro and get another one if that one isn't clear.

I couldn't find the actual call in the image. But looking more, I already understand why this happens. Because the `TryMapToProjectedDocumentRange` is basically implemented as two calls to `TryMapToProjectedDocumentPosition` for start and end and it this case it just happens to return a correct range because of using appearing before other things in the document. 

I would say we should just return false, if the input range is invalid (end > start). Do we start having other issues if we enforce that restriction?

**Comment by TanayParikh** [comment]
> I couldn't find the actual call in the image. But looking more, I already understand why this happens. Because the `TryMapToProjectedDocumentRange` is basically implemented as two calls to `TryMapToProjectedDocumentPosition` for start and end and in this case it just happens to return a correct range because of using appearing before other things in the document.

Exactly.

> I would say we should just return false, if the input range is invalid (end < start).

Yep, totally agree. 

> Do we start having other issues if we enforce that restriction?

I haven't encountered anything particular, but I don't see how that would cause other issues considering a `end < start` is in invalid range regardless.

**Comment by NTaylorMullen** [comment]
Ahhh ok I definitely follow now. Ya I agree, if the range is invalid we should return false.
