### ISSUE TITLE
Blazor isolated/scoped CSS and JS should be minified in release mode.

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#26322]
I'm using the new .NET 5 Blazor features which are awesome. Like CSS and JS isolation. However when publishing the app by using CLI: `dotnet publish -c Release` and examining the output package noticed that `<link href="_framework/scoped.styles.css" rel="stylesheet" />` is not minified. I think **isolated CSS and JS files should be automatically minified during Release publish or provided a new config to minify.**

**Other option would be to use 3rd party tools in IDE to minify CSS and JS. Which will create  e.g. `<component>.razor.min.css` file. And when app published with `-c release` config the minified contents should be selected and merged into _framework resources.**

It would make the final Blazor app smaller which is one of the main goal of the team, I believe. Thanks.

**Comment by majorimi** [comment]
So I have a "simple" proposal for this with the least amount of change required. I think only `MSBuild` scripts should be changed:

- [x] Just let developers to use 3rd party CSS and JS minification tools
- [ ] During `dotnet publish` or `Nuget packaging` collect and package all resources:
  - [x] JS files: from `wwwroot` all (*.js) `<name>.js` and `<name>.min.js`
  - [ ] CSS files: `<component>.razor.css` and `<component>.razor.min.css` and bundle all the content into 2 files: `scoped.styles.css` and `scoped.styles.min.css` if any.

With this solution the publish output and Nuget packages will be a bit bigger. Since it will contain original and minified resources as well. **But this would not impact the App download size.** And minification can be configured during deployment...

### CSS usage:
App can be configured with the deployed `index.html` content:
- `<link href="_framework/scoped.styles.css" rel="stylesheet" />` for original CSS **or**,
- `<link href="_framework/scoped.styles.min.css" rel="stylesheet" />` for minified CSS

### JS usage:
I think JS content bundle is not supported so individual JS files must be referenced individually, unlike scoped CSS. **However 3rd party tools can be used and if it is outputting bundled + minified content to `wwwroot` according to the proposal `MSBuild` scripts should collect it.**

#### .NET Core 3.1 "stlye"
App can be configured with the deployed `index.html` content:
- `<script src="_content/<package>/<file or bundle>.js"></script>` for original JS **or**,
- `<script src="_content/<package>/<file or bundle>.min.js"></script>` for minified JS

#### .NET5
Since .NET5 RC1 we JS interop modules. In this case developers must have some config to decide which resource to load. 
- await jsRuntime.InvokeAsync<JSObjectReference>("import", "./_content/<package>/<file or bundle>.min.js"); for original JS **or**,
- await jsRuntime.InvokeAsync<JSObjectReference>("import", "./_content/<package>/<file or bundle>.js"); for original JS

_Also in release mode publish and Nuget pack might can detect `scoped.styles.min.css` exists and generate `index.html` with the correct `href`. But it is a nice to have, I think._

@mkArtakMSFT @danroth27 
Do you think it is a feasible design proposal? If yes, can it be fitted into .NET5 final release?

**Finally document and emphasize out minifications are supported in Blazor with usage examples.** Since as I can see (in .NET5 RC1 version) `*.min.js` files are already packaged. Not sure if it is a new feature. But could not find mentioning of that minified JS files should be imported into released Blazor Apps. All existing 3rd party components shows their usage with non minified JS content import...

Keep up the good work 👍 Thanks.

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @majorimi.

We plan on documenting best practices for this in https://github.com/dotnet/AspNetCore.Docs/pull/19956.
