### ISSUE TITLE
ProtectedSessionStorage not more available in 5.0.0-preview.9.20467.1

### ISSUE THREAD

**Issue by tossnet** [dotnet/aspnetcore#26321]
In a Blazor Server project, I just updated the Nuget package **Microsoft.AspNetCore.Components.Web.Extensions** 5.0.0-preview.8.20414.8 to 5.0.0-preview.9.20467.1

And automatically the method  **ProtectedSessionStorage** is no longer accessible.

If I switch back to version 5.0.0-preview.8.20414.8

**Comment by campersau** [comment]
Not sure if preview 9 should exist in the first place. (Also the correct version would be [`5.0.0-preview9.20467.1`](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Web.Extensions) without a `.` between `preview` and `9`)
In rc1 it got moved to [`Microsoft.AspNetCore.Components.ProtectedBrowserStorage`](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.ProtectedBrowserStorage) and in rc2 it will be in the shared fx https://github.com/dotnet/aspnetcore/issues/25534

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. As @campersau has pointed out, we've moved the component. You can read more about the change here: https://github.com/aspnet/Announcements/issues/436
