### ISSUE TITLE
Add support for Kestrel return non-ASCII headers in response

### ISSUE THREAD

**Issue by yunfandev** [dotnet/aspnetcore#26334]
### Describe the bug
When I try to create a reverse proxy using asp.net core with the library [reverse-proxy](https://github.com/microsoft/reverse-proxy/) for [my blog](https://yunfan.dev), which has the following response header:

```text
access-control-allow-credentials: true
access-control-allow-origin: *
cache-control: public, max-age=0
content-encoding: gzip
content-type: text/html; charset=utf-8
date: Fri, 25 Sep 2020 10:15:43 GMT
etag: W/"9127-u+4Jv+RfD2erbftmcMqr2DT5eig"
status: 304
strict-transport-security: max-age=315360000; includeSubDomains; preload
vary: Origin
x-powered-by: traefik(made with ❤️ with go)
```

It throws an expectation, `InvalidOperationException: Invalid non-ASCII or control character in header: 0x00E2` 😂😂😂

### To Reproduce

Set any non-ASCII header in the response.

### Exceptions (if any)

`InvalidOperationException: Invalid non-ASCII or control character in header: 0x00E2` 

### Further technical details
  ```text
  .NET Core SDK (reflecting any global.json):
  Version:   3.1.402
  Commit:    9b5de826fd

  Runtime Environment:
  OS Name:     Windows
  OS Version:  10.0.19042
  OS Platform: Windows
  RID:         win10-x64
 ```

**Comment by yunfandev** [comment]
Origin issue: https://github.com/microsoft/reverse-proxy/issues/440

**Comment by blowdart** [comment]
If we do this, it needs to be off by default, because, as we all known, that is, as the error indicates, an illlegal header, which should be rejected.

**Comment by yunfandev** [comment]
@blowdart 

Agree. As long as it can be manually turned on when acting as a reverse proxy.

**Comment by yunfandev** [comment]
It looks like there is already a similar issue: [Allow non-ASCII characters in response header values](https://github.com/dotnet/aspnetcore/issues/4727)

**Comment by davidfowl** [comment]
Closing as dupe
