### ISSUE TITLE
Token authentication not working for grpc-web

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#26339]
---
**Issue moved from grpc/grpc-dotnet#1063**
- Please respond to @vrao1020.

---

_From @vrao1020 on Friday, September 25, 2020 1:17:46 AM_

### What version of gRPC and what language are you using?
2.31.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
SDK - 3.1.401

### What did you do?
I have a .net core API that hosts a GRPC service. The packages I am using are Grpc.AspNetCore and Grpc.AspNetCore.Web to call GRPC from a browser. I have basic authorization attribute (no policy or role based auth - just token needs to be valid for the API) on the GRPC service:

![image](https://user-images.githubusercontent.com/39545085/94214383-50a4a500-fe8e-11ea-9cc7-226e506286bb.png)

CORS is setup to allow any header/method from localhost:4200 where I am testing my local angular app. When I send a request with a token, authentication always fails.

![image](https://user-images.githubusercontent.com/39545085/94214497-93ff1380-fe8e-11ea-80b2-e01e14a458b8.png)

When the Authorize attribute is removed, the GRPC call is resolved successfully (do note it says token validated because even though I removed authorize attribute from the service, I am still passing the token in below screenshot):
![image](https://user-images.githubusercontent.com/39545085/94214759-4df67f80-fe8f-11ea-8d25-49418e77508b.png)

I also tested calling the GRPC service from a .net core client instead of angular client (using a GrpcWebHandler). The same token is used in both instances and it is successful when using the .net core grpc client but not the angular client. Authorize attribute is enabled during this test:
![image](https://user-images.githubusercontent.com/39545085/94214936-d9701080-fe8f-11ea-8c1a-1a0e68197d3f.png)

Just to confirm that the authorization header is being passed successfully to the GRPC service, I removed the authorize attribute and called the service from both the angular and .net core clients:

**When called from .net core grpc client:**
![image](https://user-images.githubusercontent.com/39545085/94215219-beea6700-fe90-11ea-8b6f-c64a66119344.png)

**When called from angular grpc client:**
![image](https://user-images.githubusercontent.com/39545085/94215292-0bce3d80-fe91-11ea-9353-82b4ebf1ef59.png)

### What did you expect to see?
The token is successfully validated and successful response from the GRPC service

### What did you see instead?
Authorization failure even though the token is valid and passes validation when sent from a .net core client

### Anything else we should know about your project / environment?
Angular 10 and using https://github.com/ngx-grpc/ngx-grpc library for sending grpc requests from the angular app to the GRPC service in the .net core API

**Comment by vrao1020** [comment]
This issue can be closed - there is a custom middleware interfering with my request causing authentication and CORS to not work correctly.  I disabled it and its working correctly now.

**Comment by blowdart** [comment]
Closing as requested :)
