### ISSUE TITLE
Asp.net Blazor RC1 Virtualize Component – items limit

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#26354]
Virtualize component seems not to support more than 700_000 elements. 

If you have less elements, you can scrool till the end of the list. If you have more elements and scroll till the end of the list, last elements are not loaded.

I’ve attached a simple test project based on blazor project template. You can change the variable mCount to test with different list sizes.

[WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/5287088/WebApplication1.zip)

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @Jarek300.

This issue is a result of the browser's limitations on the height of a scrollable region, as opposed to a limitation in Blazor itself.
