### ISSUE TITLE
Unable to render conditional closing and opening tag

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/aspnetcore#26368]
### Describe the bug
I have a requirement as per which withing a parent div I will have to render only three div inside it. So if there are 7 elements in collection, there will be 3 parent div. The first Div will have 3 child elements and second also and the third div will have one element

### To Reproduce

```
@foreach (var element in collection.element)
{
 int childCount=1;
if(childCount==1)
  <div classs="innerParent">

<div class="child">@elemet.Title</div>

@if(childCount==3)
{
childCount=1
 </div>

}
@childCount++;
}
```
The above code is throwing an error.

### Further technical details
- ASP.NET Core version - .NET core 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) : VS

**Comment by Pilchie** [comment]
Can you give details of what error you are seeing?

**Comment by VenkateshSrini** [comment]
It is not compiling

**Comment by Pilchie** [comment]
What compiler error message are you getting.  Please paste the exact error message.

**Comment by VenkateshSrini** [comment]
The error is 
**Severity	Code	Description	Project	File	Line	Suppression State
Error		Unclosed tag 'div' with no matching end tag.	BlazorComponent.Client	D:\Venkatesh\ASPNETCore\Blazor\BlazorComponents\Client\Pages\Counter.razor	19**
The code is as below
```@if(SampleString.Any())
{
    foreach (string s in SampleString)
    {
        if(childCount==1)
        {
            <div id="Parent">
        }
        @if(childCount==3)
        {
            </div>
        }
  }
}```	

It also give bracket mismatch error. Even with the Naked eye it can be seen that the brackets are matching properly . If we just </div> in the 6th line after the opening div all error will vanish. This is a very important fix that needs to be made other ost of the layouts cannot be created in Blazor

**Comment by pranavkm** [comment]
Thanks for the feedback @VenkateshSrini. Razor does not support tags being closed inside conditional blocks.

**Comment by VenkateshSrini** [comment]
But this is very important to get it done is there a way I can achieve it ?

**Comment by VenkateshSrini** [comment]
Is there some work around you can suggest for this please ?

**Comment by csharper2010** [comment]
You should create a C# extension method that generates chunks of maximum 3 items out of your collection thus returning an IEnumerable<IEnumerable<T>> out of your IEnumerable<T>.

Then you loop over the outer items creating the divs with class innerParent. And inside you loop over the inner items creating the child divs.
