### ISSUE TITLE
Angular 10 / 11 (Ivi)

### ISSUE THREAD

**Issue by blogcraft** [dotnet/aspnetcore#26372]
Is there going to be support for Angular 10 or 11 and Ivi? Current template fails to update because old dependencys.

**Comment by AR-May** [comment]
Please take a look at this issue. It seems this concerns the template from your repo.

**Comment by pranavkm** [comment]
@LadyNaggaga could you respond?

**Comment by snebjorn** [comment]
Are you accepting PRs for this? Seems like it should be rather simple to fix

**Comment by blogcraft** [comment]
It's sad how nobody cared in the team.
