### ISSUE TITLE
Thousands of ObjectDisposedException in WebUserTelemetryInitializer per day

### ISSUE THREAD

**Issue by JeroenJSmit** [dotnet/aspnetcore#26381]
### Describe the bug
We are seeing thousands of System.ObjectDisposedException traces being logged in Application Insights originating from WebUserTelemetryInitializer with the following stack trace and exception information:

AI (Internal): [Microsoft-ApplicationInsights-Core] [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebUserTelemetryInitializer, exception message - System.ObjectDisposedException: Request has finished and HttpContext disposed.
Object name: 'HttpContext'.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed()
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features()
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.TelemetryInitializerBase.Initialize(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

### Exceptions (if any)

See the description

### Further technical details
All Microsoft.AspNetCore.* assemblies are currently at the latest greatest (3.1.8)
Microsoft.ApplicationInsights.AspNetCore itself is latests as well (2.15.0)

**Comment by Pilchie** [comment]
@shirhatti do you know how to route this?

**Comment by shirhatti** [comment]
@JeroenJSmit Can you please file an issue at https://github.com/microsoft/ApplicationInsights-dotnet?

@cijothomas FYI

**Comment by JeroenJSmit** [comment]
Done, see https://github.com/microsoft/ApplicationInsights-dotnet/issues/2074

**Comment by Pilchie** [comment]
Thanks - closing this as external.
