### ISSUE TITLE
QRCode/BarCode Scanning and Direct Printing in POS

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#26393]
Looking for feature POS system level features in Blazor WebAssembly
Are there any plans to prodive features like Scanning/Reading QRCode & Barcodes from mobile devices when using Blazor WebAssembly?
Any plans on providing Direcrt Reciept Printing(No prompt) from Modbile Devices ?

Blazor Applications as of today cannot be used on POS systems which usually requires scanning barcodes and printing reciepts from Mobile Devices.

POS is huge untapped market which will help explode the growth of blazor in those areas if those features are provided.

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

We haven't received similar requests in the past for this type of functionality, this is not something we plan to tackle, There might be existing solutions out there that can be wrapped within JS interop to achieve this scenario.
