### ISSUE TITLE
Blazor Hosted PWA WebAssembly 3.1 How to prevent download of dll from shared project

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#26396]
I am using Blazor Hosted WebAssembly 3.1 application. There are certain Libraries in the shared Shared Project which are only needed on the server side project. I don't want those DLL to be downloaded to webassemblyclient.
I have tried the following offlineAssetsExclude  but it still downloads those libraries on the client.
How can i prevent those files from downloading to client(For now without upgrading to .NET) ?

```
self.importScripts('./service-worker-assets.js');
self.addEventListener('install', event => event.waitUntil(onInstall(event)));
self.addEventListener('activate', event => event.waitUntil(onActivate(event)));
self.addEventListener('fetch', event => event.respondWith(onFetch(event)));

//Braintree.dll
//Microsoft.EntityFrameworkCore.
//SendGrid.dll
//Stripe.net.dll
const cacheNamePrefix = 'offline-cache-';
const cacheName = `${cacheNamePrefix}${self.assetsManifest.version}`;
const offlineAssetsInclude = [ /\.dll$/, /\.pdb$/, /\.wasm/, /\.html/, /\.js$/, /\.json$/, /\.css$/, /\.woff$/, /\.png$/, /\.jpe?g$/, /\.gif$/, /\.ico$/ ];
const offlineAssetsExclude = [/^service-worker\.js$/, /(Braintree.dll)/, /(Microsoft.EntityFrameworkCore.)/, /(SendGrid.)/, /(Stripe.net.)/,/(Twilio.)/ ];

async function onInstall(event) {
    console.info('Service worker: Install');

    self.skipWaiting();
    // Fetch and cache all matching items from the assets manifest
    const assetsRequests = self.assetsManifest.assets
        .filter(asset => offlineAssetsInclude.some(pattern => pattern.test(asset.url)))
        .filter(asset => !offlineAssetsExclude.some(pattern => pattern.test(asset.url)))
        .map(asset => new Request(asset.url, { integrity: asset.hash }));
    console.log(assetsRequests);

    //const assetsRequests1 = self.assetsManifest.assets
    //    .filter(asset => offlineAssetsExclude.some(pattern => pattern.test(asset.url)))
    //    .map(asset => new Request(asset.url, { integrity: asset.hash }));
    //console.log(assetsRequests1);

    await caches.open(cacheName).then(cache => cache.addAll(assetsRequests));
}

async function onActivate(event) {
    console.info('Service worker: Activate');
    event.waitUntil(self.clients.claim());
    // Delete unused caches
    const cacheKeys = await caches.keys();
    await Promise.all(cacheKeys
        .filter(key => key.startsWith(cacheNamePrefix) && key !== cacheName)
        .map(key => caches.delete(key)));
}

async function onFetch(event) {

    let cachedResponse = null;
    if (event.request.method === 'GET') {
        // For all navigation requests, try to serve index.html from cache
        // If you need some URLs to be server-rendered, edit the following check to exclude those URLs
        const shouldServeIndexHtml = event.request.mode === 'navigate';

        const request = shouldServeIndexHtml ? 'index.html' : event.request;
        const cache = await caches.open(cacheName);
        cachedResponse = await cache.match(request);
    }

    return cachedResponse || fetch(event.request);
}

/* updated again 2020-09-28 12:00 AM */
```

![image](https://user-images.githubusercontent.com/3267605/94481197-fb71d780-019c-11eb-8820-7220ef1a0c4b.png)

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

You shouldn't reference those libraries in a library referenced by a blazor webassembly application if you don't want those libraries to be part of the blazor webassembly payload.

If the Blazor Webassembly application references those libraries directly or transitively they will be included in the download payload.

**Comment by nssidhu** [comment]
Webassembly does not reference them.

**Comment by javiercn** [comment]
If you are referencing a shared library and that library references those libraries, they are referenced transitively.

**Comment by nssidhu** [comment]
I get your point, shared Project is being referenced in Client/Webassembly Project. 
I was hoping that excluding it from Service-worker would not download it, what is that meant for ? only PWA Part ?
So other than refactoring is there anyother option ?

**Comment by javiercn** [comment]
@nssidhu that is only for PWA applications to avoid caching something.

Unfortunately, other than potentially fiddling with the linker to trim those libraries I don't think there is an alternative other than refactoring to take out those dependencies.

Our recommendation is that you refactor that shared library to avoid referencing those libraries, if you decide to try linking things out, that can cause issues at runtime if any type from that library needs to ever be loaded for some reason, so it is best to avoid the dependency at compile time alltogether.

**Comment by nssidhu** [comment]
Here is the interesting scenario, if you could help throw some light on how to resolve it.
In the shared library i am using entityFramework and those entities/model are being used on client side hence the reference is made to shared project on the client side. but i definately don't the entityframework dlls on the client side.
So how do i allow download of model class but prevent the download of entityframework dll. The whole reasoning behind shared project was the reuse, otherwise if i move the entity framework into server project i would have to create seperate DTO in shared project.

Any links on how to tweak the linkers ?

**Comment by javiercn** [comment]
@nssidhu what is EF specific about your models?

If you have DbContext and things like that on the shared project, I would move those to the server project, they don't make any sense on a shared library. 

For your model, there's normally nothing EF specific about them, they are normally just POCO classes.

Finally, I would say that reusing the EF models across the stack, while possible, is a bad form of reuse, since you are coupling your entire stack to EF. It might make more sense to pay the price of writing a DTO for your classes, or use a shared interface that multiple classes implement.

If you are in 5.0, you can likely make this easier for yourself by writing a source generator that does it for you automatically.
