### ISSUE TITLE
API ref docs

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26397]
This issue tracks filling in the blanks in our API ref docs. We'd like to make sure all public API surface in our types are documented and that we're able to enable the doc warning [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591) in our projects. 

Later this week, we'll follow up on doing a pass on APIs that are commonly used by project templates and user code to figure out if we need expand on the documentation coverage there or if the language can be simplified. We want to incorporate more of our concept docs too if it is helpful. Feel free to do an initial pass on areas that you're working on to also cover this.

* [x] Hosting, Http Abstractions, Routing (@captainsafia)
* [x] Servers
  - [x] IIS (@jkotalik)
  - [x] Kestrel (@javiercn)
  - [x] HttpSys (@wtgodbe)
* [x] Middleware
    - [x] Static files, HttpsPolicy, Diagnostics,  HostFiltering, ResponseCaching, HttpOverrides (@juntaoluo)
    - [x] Localization, Localization.Routing, ResponseCompression (@SteveSandersonMS)
    - [x] WebSockets (@BrennanConroy)
    - [x] HealthChecks, CORS (@JamesNK)
   -  [x] Session, Diagnostics.EntityFrameworkCore, MiddlewareAnalysis, , HeaderPropagation,  NodeServices (@halter73) 
   - [x] Rewrite (@jkotalik)
* [x] Security - Authentication, CookiePolicy (@pranavkm)
* [x] MVC
* [x] Components (@HaoK)
* [x] SignalR (@BrennanConroy)
* [x] Identity, IdentityUI (@HaoK)
  
Once a project has 100% doc coverage, consider enabling warnings for missing docs by adding this to your project file:

```xml
<NoWarn>$(NoWarn.Replace('1591', ''))</NoWarn>
```

**Comment by HaoK** [comment]
@pranavkm just double checking in case we supposed to be swapped MVC/Components for you and Security/Auth for me?

**Comment by pranavkm** [comment]
Ping people still assigned to this issue.

**Comment by halter73** [comment]
I'm still working on some [last-minute 5.0 fixes](https://github.com/dotnet/aspnetcore/issues/26560). I wonder if it wouldn't make more sense for me to take Kestrel and someone else to take "Session, Diagnostics.EntityFrameworkCore, MiddlewareAnalysis, , HeaderPropagation, NodeServices", but I can still do a first draft for those API docs.

**Comment by pranavkm** [comment]
>  wonder if it wouldn't make more sense for me to take Kestrel and someone else to take "Session, Diagnostics.EntityFrameworkCore, MiddlewareAnalysis, , HeaderPropagation, NodeServices", 

Sure, if you feel you'd be more productive that way. I've been trying to mix things up to see if we can benefit from getting a secondary perspective authoring the content while the area owner reviews the content.

**Comment by jkotalik** [comment]
@pranavkm @SteveSandersonMS @javiercn will you all be able to handle these API docs soon?

**Comment by SteveSandersonMS** [comment]
@jkotalik Yes, submitted https://github.com/dotnet/aspnetcore/pull/26889

**Comment by javiercn** [comment]
@pranavkm this is done now

**Comment by dougbu** [comment]
@javiercn, @JunTaoLuo, and @pranavkm does this mean we can remove the `$(NoWarn)` setting for CS1591 errors and get rid of `<NoWarn>$(NoWarn.Replace('1591', ''))</NoWarn>` overrides❔

**Comment by JamesNK** [comment]
We should explore inverting it so there is no CS1591 in NoWarn by default. Remove CS1591 from top-level msbuild NoWarn and remove the NoWarn overrides. There will be projects where it needs to be added back (e.g. all test projects)

**Comment by pranavkm** [comment]
The NoWarn we have in the project files was to workaround an Arcade default: https://github.com/dotnet/arcade/blob/4873d157a8f34f8cc7e28b3f9938b32c642ef542/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L94. We could follow @JamesNK suggestion and apply the workaround by default while letting individual projects undo it. Filed https://github.com/dotnet/aspnetcore/issues/27106 to track this.

**Comment by dougbu** [comment]
1. We also have the following making 1591 a non-error:
https://github.com/dotnet/aspnetcore/blob/da7fead48635c4c9881828627c859440792f13b3/Directory.Build.props#L97

2. We already had #12067. I therefore closed #27106.
