### ISSUE TITLE
Update gRPC package references in templates for 5.0 GA

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#26403]
Before shipping 5.0 GA, we need to update the versions of the gRPC packages used in templates.

**Comment by JamesNK** [comment]
Waiting on 2.32.0 to be published on NuGet.org.

Everything is ready in grpc-dotnet code - https://github.com/grpc/grpc-dotnet/pull/1061

I've sent a follow up email to ask it to be done soon.

**Comment by Pilchie** [comment]
@JamesNK okay to close this now?
