### ISSUE TITLE
Blazor debugging in VS Code doesn't bind breakpoints

### ISSUE THREAD

**Issue by connor4312** [dotnet/aspnetcore#26412]
### Describe the bug
I've mentioned before but realized I never file a bug. I'm not able to successfully debug into a "hello world" blazor project. I can run the app, but when I try to set breakpoints (e.g. on `currentCount++;` on the hello world app) they never get bound.

### To Reproduce

1. Follow the steps here: https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-3.1#vscode
1. Set a breakpoint on Counter.razor line 14
1. Run the app, increment the counter

### Exceptions (if any)

none

### Further technical details
- ASP.NET Core: 3.1.402
- C# extension 1.23.2
- VS Code 1.49.2 with js-debug 1.49.8
- I've tried this process occasionally over the last several months, it's not a recent regression.
- dotnet --info:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Log file: [vscode-debugadapter-0.json.gz](https://github.com/dotnet/aspnetcore/files/5295808/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
Diego asked whether debugging in Chrome directly worked; I didn't see sources there either

![](https://memes.peet.io/img/20-09-353efe0d-8a68-49b7-b568-dd81ca779b80.png)

He suggested it might be due to a bad blazor proxy version. I'm not sure how to check this.

**Comment by digeff** [comment]
I noticed in the log that you are not getting scriptParsed events for the C# source files

**Comment by captainsafia** [comment]
@connor4312 Can you reproduce this behavior with the latest .NET 5 RC2 found at https://github.com/dotnet/installer?

There were substantial changes between the debug proxy shipped in 3.2 and the one that will ship with .NET 5, so I want to confirm if this is buggy behavior in the older version or newer one.

Usually, if the `scriptParsed` event is not emitted, there was a problem fetching or reading the PDB file.

**Comment by connor4312** [comment]
Hm, I'm not able to create a new blazor project on a fresh install of rc2. Do I need to wait for nuget packages to be published?

```PS E:\Downloads> dotnet --version
5.0.100-rc.2.20478.8
PS E:\Downloads> dotnet new blazorwasm -o helloworld5
The template "Blazor WebAssembly App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/5.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on E:\Downloads\helloworld5\helloworld5.csproj...
  Determining projects to restore...
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Components.WebAssembly with version (>= 5.0.0-rc.2.20475.17)
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 5.0.0-rc.1.20451.17 ]
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Components.WebAssembly.DevServer with version (>= 5.0.0-rc.2.20475.17)
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest version: 5.0.0-rc.1.20451.17 ]
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
E:\Downloads\helloworld5\helloworld5.csproj : error NU1102: Unable to find package System.Net.Http.Json with version (>= 5.0.0-rc.2.20475.5)
...
```

**Comment by captainsafia** [comment]
Yes, you'll need to add the NuGet feed in a config file like so.

```
<configuration>
  <packageSources>
    <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by connor4312** [comment]
Thanks for the steps! I added that and got it running, but it doesn't seem like much changed -- I still don't hit breakpoints in VS Code, or see `scriptParsed` events for razor files in the js-debug logs. Like before I don't see razor files in the alt+shift+d page when running `dotnet run` either (previously I could alt+shift+d from the running app in a new browser instance, now it looks like I need to separately run the app)

![](https://memes.peet.io/img/20-09-b06dbf77-532c-401c-82ad-11e6de6b24dc.png)

**Comment by captainsafia** [comment]
Thanks for following up -- this is definitely spooky.

I suspect that there is something about the browser version/device setup that is affecting this scenario since our CTI tests haven't picked up anything. 

I wasn't able to repro the same on a project built from 5.0.0-rc.2.20465.7. To cover our bases, can you upload a zip of the project used?

**Comment by ar0311** [comment]
I'm seeing the same, can bind breakpoints on Mac w/ RC2 but not Windows
