### ISSUE TITLE
6.0 docs: HTTP/3 in ASP.NET Core

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#26415]
What is the usability of HTTP/3 with ASP.NET Core in 5.0? If we intend for people to try it out with 5.0 it should have docs.

@jkotalik

**Comment by jkotalik** [comment]
I have a draft of the doc/blog post in specs; I'll update it accordingly.

**Comment by wtgodbe** [comment]
Add this info to the docs: https://github.com/dotnet/aspnetcore/issues/34858#issuecomment-895550588
