### ISSUE TITLE
Error CS1705: reported in Azure Devops but not locally. Required version not available. How to fix?

### ISSUE THREAD

**Issue by MichelleGorrellUK** [dotnet/aspnetcore#26427]
I have a Blazor WASM app that calls Server side APIs. It works well and compiles, runs and passes all unit and integration tests locally. However, the Server-side test project fails to build in the DevOps pipeline with the following message:

**CSC : error CS1705: Assembly 'Microsoft.AspNetCore.TestHost' with identity 'Microsoft.AspNetCore.TestHost, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Hosting.Server.Abstractions' with identity 'Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [D:\a\1\s\Support.DataConductor.ServerTests\Support.DataConductor.ServerTests.csproj]**

(In the test project, I have set up a Microsoft.AspNetCore.TestHost.TestServer for integration testing.)
The error message suggests I reference Microsoft.AspNetCore.Hosting.Server.Abstractions, Version=3.1.0.0 but the highest available version of this assembly in NuGet appears to be version 2.2.0.0.
Is this mis-reported? Can you advise?

In Azure Devops the build log starts:_
2020-09-29T14:41:43.9074137Z ##[section]Starting: Build solution
2020-09-29T14:41:43.9215225Z ==============================================================================
2020-09-29T14:41:43.9215568Z Task         : Visual Studio build
2020-09-29T14:41:43.9215865Z Description  : Build with MSBuild and set the Visual Studio version property
2020-09-29T14:41:43.9216154Z Version      : 1.166.2
2020-09-29T14:41:43.9216369Z Author       : Microsoft Corporation
2020-09-29T14:41:43.9216698Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
2020-09-29T14:41:43.9217092Z 
...
_The failing project has these entries (solution name supressed):_
2020-09-29T14:42:51.8155439Z Project "D:\a\1\s\XXXX.sln" (1) is building "D:\a\1\s\Support.XXXX.ServerTests\Support.XXXX.ServerTests.csproj" (11) on node 1 (default targets).
2020-09-29T14:42:51.8156442Z PrepareForBuild:
2020-09-29T14:42:51.8156789Z   Creating directory "bin\Release\netcoreapp3.1\".
2020-09-29T14:42:51.8159246Z   Creating directory "obj\Release\netcoreapp3.1\".
2020-09-29T14:42:52.2951361Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): Warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Hosting" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
_Then similar warnings:_

MSB3277 ... conflicts between different versions of "Microsoft.AspNetCore.Hosting" that could not be resolved.
MSB3277 ... conflicts between different versions of "Microsoft.AspNetCore.Hosting.Abstractions" that could not be resolved.
MSB3277 ... conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions" that could not be resolved.
MSB3277 ... conflicts between different versions of "Microsoft.AspNetCore.Mvc.Abstractions" that could not be resolved.
MSB3277 ... conflicts between different versions of "Microsoft.AspNetCore.Mvc.Core" that could not be resolved.
MSB3277 ... conflicts between different versions of "Microsoft.AspNetCore.Routing" that could not be resolved.

Here is the local output from dotnet --info:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by pranavkm** [comment]
Are you able to share a minimal app that reproduces the problem? It's hard for us to determine what the issue is without inspecting the application's references.

**Comment by MichelleGorrellUK** [comment]
To do so, I will need to create a new app and a new project and pipeline in DevOps. Then insert some sample code and crucially, an integration test project that uses the same refs. It may take some time...

**Comment by pranavkm** [comment]
Are you able to share the contents of `Support.DataConductor.ServerTests.csproj`? Might help a bit.

**Comment by MichelleGorrellUK** [comment]
Hi, I've constructed a demo app and will make it available shortly.

(Sent from my telephone)

________________________________

**Comment by MichelleGorrellUK** [comment]
I have created a trimmed version of the failing app available now at: https://github.com/MichelleGorrellUK/CS1075BuildDemo
Although I replaced all data and attributes specific to our project, it still fails in the same way in an Azure Build pipeline. Note, the app builds and runs locally on my dev machine and the sample integration test runs and passes.
The test calls the same TestServer set-up as the original app.

**Comment by MichelleGorrellUK** [comment]
Thanks to @pranavkm I can now build my projects in Azure Devops. They were fixed by changing the sdk in the failing test project file to `<Project Sdk="Microsoft.NET.Sdk.Web">.`
I think it would be useful to a wider audience if someone with greater insight than me could explain why the error CS1705 message was generated, and how the fix works.
Also, could the  error message be refined to more directly help other users in these circumstances? It seems to recommend an impossible change without helping to identify the real problem.
