### ISSUE TITLE
Missing space when using an if statement within a blazor server app

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#26426]
### Describe the bug
I am displaying buttons based on a condition. However, the DOM gets no space after the if statement. When I put all buttons within the if statement, it works just fine.

### To Reproduce
I created a small repo which shows exactly what I mean.
https://github.com/MarvinKlein1508/BlazorConditionalSpacing

Or you can just paste this snippet:
```
<button class="btn btn-primary" @onclick="SwitchOptions">Show more options</button>
<br />
<div class="toolbar">
    @if (moreOptions)
    {
        <button class="btn btn-info">Option 1</button>
        <button class="btn btn-success">Option 2</button>
    }
    <button class="btn btn-primary">Option 3</button>
</div>

@code {
    bool moreOptions = false;

    private void SwitchOptions()
    {
        moreOptions = !moreOptions;
    }
}
```

Toolbar CSS:
```
.toolbar {
    text-align: right;
    padding-bottom: 0.5em;
}
```

### Further technical details
- ASP.NET Core version 5.0.0-rc.1.20451.17
- Include the output of `dotnet --info`
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- Version 16.8.0 Preview 3.1

**Comment by pranavkm** [comment]
Thanks for the issue report @MarvinKlein1508. Starting in 5.0, Blazor will strip significant white space as described in: https://github.com/aspnet/Announcements/issues/426. Consider using `@preservewhitespace true` is preserving whitespace is required.

**Comment by MarvinKlein1508** [comment]
@pranavkm oh this totally flew under my radar. However could you provide a way to enable/disable this feature section based?

In my example it is only needed to set it to true within a short section of my component. So I won't lose any performance which could have been saved.

I am thinking about something like this:
```
<div class="toolbar">
    @preservewhitespace true
    @if (!Auftrag.Gepackt)
    {
        <button type="button" class="btn btn-danger"><i class="fa fa-ban"></i></button>
        <button type="button" class="btn btn-warning"><i class="fa fa-pause-circle"></i></button>
    }

    <button type="button" class="btn btn-primary"><i class="fa fa-info-circle"></i></button>
    @preservewhitespace false
</div>
```

**Comment by pranavkm** [comment]
Directives in Razor don't have such fine grained granularity. I'm not sure if using a HTML entity `&nsbsp;` is preserved by the parser. @SteveSandersonMS?

**Comment by MarvinKlein1508** [comment]
@pranavkm yes, when I put a `&nbsp;` there manually, it stays. However, there is too much space then.
