### ISSUE TITLE
inheritdoc doesn't show on docs browser

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#26434]
`<inheritdoc>` doesn't show up on the ASP.NET API Browser. 

For example:
https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Http/WebUtilities/src/FileBufferingWriteStream.cs uses inheritdoc.

But https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.filebufferingwritestream?view=aspnetcore-3.1 doesn't actually show details for inherited docs.

cc @scottaddie I heard this works in VS with intellisense, what do we need to do to get this working?

**Comment by scottaddie** [comment]
@jkotalik I copied you on an email with @mimisasouvanh. Mimi can help us determine how to move forward.

**Comment by mimisasouvanh** [comment]
@jkotalik @scottaddie  I've created an internal item to track this. Thank you for your feedback!

**Comment by dougbu** [comment]
Where are we on the work to support `/// <inheritdoc />`❔ We make extensive use of this in the dotnet/aspnetcore repo.

**Comment by wtgodbe** [comment]
@mimisasouvanh is there any update on this issue?

**Comment by BrennanConroy** [comment]
cc @Pilchie for visibility

**Comment by mimisasouvanh** [comment]
We are very close to supporting <inheritdoc />. I will have an update in the next coming weeks.

**Comment by wtgodbe** [comment]
Looks like this is supported now - closing
