### ISSUE TITLE
[Blazor-Wasm] API call from Blazor Client cannot be authenticated with IdentityServer4

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#26431]
We have attached a zip with some sample source to try and setup a very basic Blazor (wasm) Client -> API call using Identity Server 4 v4. The logins seem to work fine. However when we attempt to make a call from the Blazor client to the API the authorization fails. If we remove the [authorize] attribute from the weather forecast controller the request goes through just fine so we think it has to do with the API request not receiving something it needs to authenticate the request? Nothing seems to show up in our logs.

Using:
IdentityServer4 v4.1.0
Dotnet Core 3.1.8
Serilog 3.4.0

[src.zip](https://github.com/dotnet/aspnetcore/files/5300449/src.zip)

We already posted this on the IdentityServer4 GitHub issues page (see: https://github.com/IdentityServer/IdentityServer4/issues/4927). Brock Allen's response was to see if the Blazor team had any ideas or thoughts.

Any input is welcome.

Thanks!

**Comment by pranavkm** [comment]
@chassq we spent a couple minutes looking at your sample app and it looks like you have things misconfigured. The authority on the client does not match the one configured on the server:

```
authorizedUrls: new[] { "https://localhost:44380" },

options.Authority = "https://localhost:44376";
```

We recommend starting from a new project template and looking at the code generated there.

**Comment by chassq** [comment]
We have made some adjustments per your comments above but with no luck. Can you specify which template we should consider looking at? We have looked at the 2 Blazor project templates (hosted and stand alone using User Accounts) but cannot tell from the code what the configuration might be. We have also tried using the IdentityServer4 templates but with no luck so far on how this is supposed to be set. 

Any other input or ideas is most welcome.

**Comment by snickler** [comment]
@chassq  - This is due to you defining an audience in the API. You will need to remove the audience and instead set `ValidateAudience = false` within the TokenValidationParameters.

https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html#configuration

**Comment by chassq** [comment]
**Just a follow up:**

We did get this to work. Thanks for everyone's (@pranavkm and @snickler ) input! The issue was resolved after we:

1) Updated to dotnet 5.0 (not sure if this really had to do with anything but wanted to mention it).
2) Switched from IISExpress to Kestrel (again not sure if that came into play but that is what we ended up with).
3) **Per @snickler set ValidateAudience = false.**
4) We actually left the authority urls as is. API = options.Authority = "https://localhost:5000"; Blazor Client = authorizedUrls: new[] { "https://localhost:5002" }

Attached our working code as example.
[src.zip](https://github.com/dotnet/aspnetcore/files/5321397/src.zip)
