### ISSUE TITLE
Confirm CodeActionParams.Context.SelectionRange Use

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#26435]
Issue was due to some recent changes in LSP platform where they now give a `CodeActionParams.Range` which reflects the start of the line, instead of at the start of the area we want to act on. They still provide the "old"  selection range in `CodeActionParams.Context.SelectionRange`. Updated our logic to consume that instead if it's available.

This issue is meant to track the external follow-ups.

https://github.com/dotnet/aspnetcore-tooling/pull/2515

**Comment by NTaylorMullen** [comment]
Any status on this?
