### ISSUE TITLE
HttpRequest does not contain a definition for 'BodyReader'

### ISSUE THREAD

**Issue by markentingh** [dotnet/aspnetcore#26444]
I'm working on a Nuget package (Output type: class project) which is being used as a .NET Core middleware (https://github.com/datasilk/core). I'm using this middleware in some of my other ASP.NET Core projects by including it as a git submodule directly in these ASP.NET Core projects and have made various changes to the source code for this middleware via those projects.

The time comes for me to `git pull` changes for this middleware from the various projects I use it in into the standalone project folder for the middleware, and I realize that I'm getting a build error when trying to build a Package for Nuget.

In my ASP.NET Core projects, I can build easily with this middleware included as a git submodule, but when trying to build a Package from the middleware's own Visual Studio solution, I get an error:

```HttpRequest does not contain a definition for 'BodyReader'```. 

I know BodyReader is a part of .NET Core 3.0+, I have my middleware project using .NET Core 3.1 for the target framework, and I'm using Microsoft.AspNetCore 2.2 Nuget package as a dependency for the middleware project. 

I'm pulling out my hair trying to figure out why it works just fine in my ASP.NET Core 3.1 projects, but when in a standalone class project, it doesn't recognize BodyReader. 

Why isn't there a Nuget Package for Microsoft.AspNetCore 3.1.8? Why do I have to use 2.2?

**Comment by pranavkm** [comment]
A lot of the packages that were published during 2.x were removed as part of 3.0. Please see the instructions in https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference to see how to migrate your libraries to target 3.1 or cross-compile to support older ASP.NET Core versions.

**Comment by markentingh** [comment]
Thank you for the quick response

**Comment by markentingh** [comment]
Awesome, I added the following to my `csproj` file and everything works now

```
<ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

Also, I removed my Nuget package reference for Microsoft.aspNetCore 2.2. Thank you so much for your help, @pranavkm
