### ISSUE TITLE
Question: Razor Language Server Protocol (LSP) for MVC 5

### ISSUE THREAD

**Issue by tompazourek** [dotnet/aspnetcore#26454]
Just read about the [New experimental Razor editor for Visual Studio](https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/).

**Will this new Razor editor support editing of the ASP.NET MVC 5 Razor, or is it strictly for the new ASP.NET Core Razor?**

If it did, it might be a way to resolve Razor Intellisense issues with MVC 5 projects using the new SDK-style project system (see https://github.com/dotnet/project-system/issues/2670#issuecomment-700837291). I'm just curious.

Thanks for the information, I'm glad to learn more about this cool feature.

**Comment by NTaylorMullen** [comment]
Hi @tompazourek I'm glad you're as excited about this new effort as we are! The first iterations of the experimental Razor editor will not support the pre-existing ASP.NET MVC 5 Razor skew; however, it is something we may re-evaluate in the future 😄

**Comment by tompazourek** [comment]
@NTaylorMullen Thanks, good to know.

**Comment by CZEMacLeod** [comment]
@NTaylorMullen Just a quick note to say that this would be a major boost for those still having to handle legacy applications and frameworks. Using the [RazorGenerator.MsBuild](https://github.com/RazorGenerator/RazorGenerator) package in an SDK style project produces class libraries with UI that can be much more easily edited and managed etc. with just a bare-bones legacy ASPNET5 project in the old format but editing Razor files is the major hurdle for maintenance.
I understand that most effort will have to go into supporting new tech, but this would really help enable editing, maintaining and migrating legacy code.

**Comment by tompazourek** [comment]
@CZEMacLeod I agree, as noted in my comment https://github.com/dotnet/project-system/issues/2670#issuecomment-706069024, Rider actually doesn't have the Intellisense issues as VS on older ASP.NET MVC 5 projects so maybe Rider is the way to go for legacy apps.
