### ISSUE TITLE
Any way to access or get the metadata of the cache.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#26459]
For say, I am setting a cache as follows:

    var cacheKey = "TestKey";
    byte[] utf8Bytes = JsonSerializer.SerializeToUtf8Bytes<T>(obj);
    DistributedCacheEntryOptions options = new DistributedCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromDays(30));
    await distributedCache.SetAsync(cacheKey, utf8Bytes, options);

And I retrieve the cache value as follows:

    byte[] utf8Bytes = await distributedCache.GetAsync("TestKey");

Is there any way to get the `SlidingExpiration` value of the above cache by its cache key?

**Comment by Tratcher** [comment]
No, you'd have to encode that information as part of the value.

**Comment by TanvirArjel** [comment]
@Tratcher Thank you. Any plan of adding such functionality?
