### ISSUE TITLE
Blazor WASM .NET 5 RC2 and Azure Cosmos DB - System.Security.Cryptography.Algorithms is not supported on this platform

### ISSUE THREAD

**Issue by ylr-research** [dotnet/aspnetcore#26450]
### Bug
I have a vanilla Blazor WASM (standalone) application reading a container from Azure Cosmos DB. Before upgrading to .NET 5 RC1 it was working fine. This is the same application I had issues with in #26043. After upgrading packages to RC2 I still get exceptions (see image below) in the Developer Console.

### Program.cs
``` C#
public class Program
{
	public static async Task Main(string[] args)
	{
		var builder = WebAssemblyHostBuilder.CreateDefault(args);
		builder.RootComponents.Add<App>("app");

		builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
		builder.Services.AddHttpClient();
		builder.Services.AddSingleton<CosmosClient>(serviceProvider =>
		{
			IHttpClientFactory httpClientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

			CosmosClientOptions cosmosClientOptions = new CosmosClientOptions
			{
				HttpClientFactory = httpClientFactory.CreateClient,
				ConnectionMode = ConnectionMode.Gateway
			};

			return new CosmosClient("<endpoint-connectionString>", cosmosClientOptions);
		});

		await builder.Build().RunAsync();
	}
}
```

### Packages
```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-rtm.20479.13" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-rtm.20479.13" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.13.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0-alpha.1.20420.3" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0-alpha.1.20420.3" />
```
### Exceptions
![image](https://user-images.githubusercontent.com/63487874/94636113-3f023980-02a2-11eb-8573-162af418457d.png)

**Comment by campersau** [comment]
Similar to https://github.com/dotnet/runtime/issues/42384, https://github.com/dotnet/aspnetcore/issues/26123 but for a different type.

Some types were brought back in rc2 (https://github.com/dotnet/runtime/issues/40076) but I don't think `HMACSHA256` was one of them.

https://github.com/dotnet/runtime/blob/b1ca1f4eb040e42045718e265775f79eea982d32/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/HMACSHA256.cs#L17-L18

So I am not sure if rc2 would be enough for https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1865 .

**Comment by javiercn** [comment]
@ylr-research thanks for contacting us.

As described by @campersau this is a known limitation in 5.0.

**Comment by HaoK** [comment]
We believe things are better in RC2, @lewing can you confirm?

**Comment by lewing** [comment]
SHA256 hashes are in net5.0 but not HMACSHA256 so this will still fail.

**Comment by ylr-research** [comment]
I have installed the RC2 (see image) and the must current packages, and this still fails.
![image](https://user-images.githubusercontent.com/63487874/94972920-680c0f80-04d8-11eb-9ce8-05b1502d623b.png)

``` XML
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-rtm.20502.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-rtm.20502.9" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.13.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0-alpha.1.20420.3" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="5.0.0-rtm.20502.9" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0-alpha.1.20420.3" />
```

**Comment by ylr-research** [comment]
as a matter of fact, here it is where AzureCosmos SDK is defaulting the encryption method.
![image](https://user-images.githubusercontent.com/63487874/94973484-d56c7000-04d9-11eb-8056-69582b3347a7.png)

**Comment by ealsur** [comment]
The code uses `byte[] hashPayLoad = stringHMACSHA256Helper.ComputeHash(payload.Buffer);` which seems to have this implementation: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Authorization/SecureStringHMACSHA256Helper.cs#L20

Currently I don't see anything in the public contract of the SDK to inject your implementation, I'm guessing that the hash is part of the contract of the service, right @j82w?

**Comment by lewing** [comment]
@ealsur I suspect it is https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Authorization/StringHMACSHA256Hash.cs rather than the SecureString version

**Comment by j82w** [comment]
@lewing [SecureString isn't recommended](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md) for new development.

**Comment by lewing** [comment]
right, I was just trying to point out the correct file

**Comment by mkArtakMSFT** [comment]
@HaoK can you please continue the investigation here. Folks are claiming above that this wasn't resolved in RC2.

**Comment by lewing** [comment]
This will not be fixed in .NET 5.0 see the discussion here https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1865#issuecomment-703016492

We hope to address this for 6.0 by adapting some of the apis.

**Comment by mkArtakMSFT** [comment]
Thanks @lewing.
Closing this as there is nothing we can do here. @ylr-research please use the referenced issue to track progress.
