### ISSUE TITLE
Implicit converstion of `ObjectResult` to `ActionResult<T>` looses `Value`

### ISSUE THREAD

**Issue by doak** [dotnet/aspnetcore#26460]
### Describe the bug
Some controller endpoint returns an `ActionResult<T>` using `ControllerBase.Ok(response)`. `response`  itself is a valid instance of type `T` (i.e. non-null).
Accessing the passed-through `response` through `ActionResult<T>.Value` returns **always** `null`, though `response` was not `null`.

I am not absolutely sure if I am using the API like intended.
Please let me know and don't hesitate to ask if you need more information.

### To Reproduce
Code to show the potential issue is available in this repository:
https://github.com/doak/ActionResultOfT-looses-Value/blob/master/test.cs

I would expect that all printed lines include the original response (the string), but the output is this:
```
Response1: message1
Response2: message2
Response3: 
Response3: message3
```

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
    ```
    .NET Core SDK (reflecting any global.json):
    Version:   3.1.402
    Commit:    9b5de826fd

    Runtime Environment:
    OS Name:     debian
    OS Version:  
    OS Platform: Linux
    RID:         debian-x64
    Base Path:   /usr/share/dotnet/sdk/3.1.402/

    Host (useful for support):
    Version: 3.1.8
    Commit:  9c1330dedd

    .NET Core SDKs installed:
    2.1.810 [/usr/share/dotnet/sdk]
    3.1.402 [/usr/share/dotnet/sdk]

    .NET Core runtimes installed:
    Microsoft.AspNetCore.All 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

    To install additional .NET Core runtimes or SDKs:
    https://aka.ms/dotnet-download
    ```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:
  VS Code:
   ```
    Version: 1.49.2
    Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
    Date: 2020-09-24T16:26:09.944Z
    Electron: 9.2.1
    Chrome: 83.0.4103.122
    Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
    OS: Linux x64 5.8.0-1-amd64
    ```

**Comment by HaoK** [comment]
@doak this behavior is by design, we don't unwrap the result by default
