### ISSUE TITLE
Unable to link with a Javascript file if it is added as a link

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26466]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1201413/unable-to-link-with-a-javascript-file-if-it-is-add.html)._

---
[severity:It's more difficult to complete my work]
Dotnet Core 3.1 Razor Pages

wwwroot/js/myscript.js <= added as a link.

Later in my cshtml page. I try to add using:

<script src="~/js/myscript.js" asp-append-version="true"></script>

Unfortunately myscript.js is not loaded. I do not have problem with cs / cshtml added as a link.

---
#### Feedback Bot on 9/27/2020, 00:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/27/2020, 01:54 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
