### ISSUE TITLE
Blazor CSS isolation does not work for migrated NET Core 3.1 projects

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#26464]
### Describe the bug
I wanted to try out the new razor css isolation feature from .NET 5. However something seems to be wrong when you port an existing project from .NET Core 3.1 over. All CSS rules seemed to be ignored.

### To Reproduce
I created a small repo with brand new projects.
https://github.com/MarvinKlein1508/BlazorCssIsolation

The first one was created with .NET Core 3.1 and in the .csproj file I have changed `netcoreapp3.1` to `net5.0`

The second project was created directly as .NET 5 project.

I added the same Index.razor.css to both projects with the same rule. The new project applies them, the old does not.

### Exceptions (if any)
None

### Further technical details
- ASP.NET Core version: 5.0.0-rc.1.20451.17
- Include the output of `dotnet --info`
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- Visual Studio 2019 Version 16.8.0 Preview 3.2

**Comment by chrdlx** [comment]
Hello!! You're missing a new line in the index.cshtml added in the .net 5 template which is:

<link href="_content/BlazorCssIsolationNewNet5/_framework/scoped.styles.css" rel="stylesheet" />

You need to add this in your 3.1 project in order to load the styles!!
Regards!!

**Comment by javiercn** [comment]
@chrdlx thanks for investigating.

@MarvinKlein1508 please follow @chrdlx guidance and let us know if that doesn't solve this issue.
