### ISSUE TITLE
[Discussion] Updated Blazor browser support for .NET 5

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#26475]
## Updated Blazor browser support for .NET 5

.NET 5 introduces a variety of [new Blazor features](https://github.com/dotnet/aspnetcore/issues/21514), some of which are not compatible with certain older browsers. We are updating the list of browsers supported by Blazor in .NET 5 accordingly.

In .NET 5 we will no longer support Blazor Server with Microsoft Internet Explorer 11. Note that Blazor WebAssembly was already not supported with Microsoft Internet Explorer 11.

There are also known incompatibilities in Blazor Server and Blazor WebAssembly with [Microsoft Edge Legacy](https://support.microsoft.com/en-us/help/4533505/what-is-microsoft-edge-legacy) in .NET 5 that we do not plan to address. The [new Microsoft Edge](https://www.microsoft.com/edge) based on Chromium is supported and is recommended instead.

### Version introduced

5.0

### Old behavior

Blazor Server previously supported Microsoft Internet Explorer 11 with sufficient polyfills. Blazor Server and Blazor WebAssembly were also previously functional in Microsoft Edge Legacy.

### New behavior

Blazor Server in .NET 5 will no longer be supported with Microsoft Internet Explorer 11. Blazor Server and Blazor WebAssembly are also no longer fully functional in Microsoft Edge Legacy.

### Reason for change

New Blazor features in .NET 5 are not compatible with these older browsers and use of these older browsers is diminishing. [Windows support for Microsoft Edge Legacy is also ending on March 9, 2021](https://support.microsoft.com/en-us/help/4533505/what-is-microsoft-edge-legacy) and [Microsoft 365 apps and services will end support for Microsoft Internet Explorer 11 by August 17, 2021](https://docs.microsoft.com/lifecycle/announcements/m365-ie11-microsoft-edge-legacy).

### Recommended action

We recommend upgrading from these older browsers to the [new Microsoft Edge](https://www.microsoft.com/edge), which is fully supported. For Blazor apps that still need to continue to support these older browsers, we recommend using .NET Core 3.1 LTS. The set of supported browser platforms for Blazor in .NET Core 3.1 LTS remains unchanged and is documented here: https://docs.microsoft.com/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1.

**Comment by mrpmorris** [comment]
@danroth27 
I'm disappointed you aren't going to support legacy Edge. Can you include some kind of polyfill JS file that we can add to our index.html if we want to support older versions? That's one of the good things about Angular et al, they don't abandon existing support for browsers.

I am currently having to downgrade my .NET5 Blazor WASM app because of this :(

**Comment by danroth27** [comment]
@mrpmorris We don't currently have any plans to provide specific polyfills for restoring Legacy Edge support, but you can see the changes that are currently required here: https://github.com/dotnet/aspnetcore/pull/26132

**Comment by mrpmorris** [comment]
On this subject. Do you know of any polyfills for emulating wasm on IE11 so I can try to get some 2.1 assemblies to run?

**Comment by danroth27** [comment]
Early on in the Blazor project we experimented with cross compiling the runtime to asm.js in order to support IE11, but it had lots of issues and the experience wasn't great, so we dropped it and focused our efforts on WebAssembly.

**Comment by lucashutyler** [comment]
Just ran into Legacy Edge not being supported today. Is there a recommended solution to display a "browser not supported" message for incompatible browsers?

**Comment by Daddoon** [comment]
Just in case some people are interested, i just updated [Blazor.Polyfill](https://github.com/Daddoon/Blazor.Polyfill) project for Internet Explorer 11 support with Blazor server-side.

At least the template is working perfectly, the only thing i have noted is that IE11 does not have the "disconnection trying to reconnect" HTML behavior if the server is stopped or unreachable, something may be improved here.

No Legacy Edge support (i was not even aware) atm.

Of course it's nothing official from Microsoft, so usage at your own risk, but it may be a possible workaround if stuck with old company using very old browsers.
