### ISSUE TITLE
no runtime pack for Microsoft.AspNetCore.App available (.NET 5.0.100-rc.1.20452.10

### ISSUE THREAD

**Issue by erikthysell** [dotnet/aspnetcore#26477]
Updated to Visual Studio Version 16.8.0 Preview 3.0 and in my Blazor WASM test project I have the following packages.
```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-rc.1.20451.17" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-rc.1.20451.17" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0-rc.1.20451.14" />

```
All shows yellow triangles under Dependencies->Packages.
Result that I cannot clean, nor build or rebuild the project.
All I get is the following error message:

> Rebuild started...

> 1>------ Rebuild All started: Project: BlazorWasmOnlyTest2, Configuration: Debug Any CPU ------
> 1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
> 1>C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(379,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.
> 1>Done building project "BlazorWasmOnlyTest2.csproj" -- FAILED.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by marcpopMSFT** [comment]
@pranavkm take a look?

**Comment by pranavkm** [comment]
It's very likely that you haven't migrated your projects correctly. Can you follow the instructions here: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-3.1&tabs=visual-studio#update-blazor-webassembly-projects and verify you have the right SDK and properties in your project file?

**Comment by sala91** [comment]
Yes, can confirm, no changes.

**Comment by sala91** [comment]
It seems it might be related to something included in the project, unfortunately, not easy to figure out what causes it other by going down on it one-by-one - https://stackoverflow.com/a/64023951
