### ISSUE TITLE
User Claims always empty when calling API from server-side Blazor app

### ISSUE THREAD

**Issue by Kizari** [dotnet/aspnetcore#26484]
### Describe the bug
The bug occurs when calling an API method on the same server from a server-side Blazor app via injected HttpClient. When the request is received by the API Controller, the User Claims (i.e. HttpContext.User) are empty (the object is not null, but all the values are default).

### To Reproduce
Add an identity-based DbContext, add default Authentication and Authorization, and inject a scoped HttpClient in Startup. Inject the HttpClient into a razor component in the Server-Side Blazor application and call a method from any API controller that is part of the same project. The Authentication cookie will be present in the browser, and the information in the default AuthenticationStateProvider will be as expected, but the HttpContext.User object will be empty at the API controller.

### Exceptions (if any)
No exceptions as the object is not null, just empty.

### Further technical details
- ASP.NET Core 3.1
- Visual Studio 2019 Community 16.7.4

.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### What I have tried
I have tried manually adding the cookie to the HttpClient via the following code:

```
                services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
                services.AddScoped<HttpClient>(s =>
                {
                    var httpContextAccessor = s.GetRequiredService<IHttpContextAccessor>();
                    string authToken = httpContextAccessor.HttpContext.Request.Cookies[".AspNetCore.Identity.Application"];

                    var client = new HttpClient(new HttpClientHandler
                    {
                        UseCookies = false
                    });

                    if (authToken != null)
                        client.DefaultRequestHeaders.Add("Cookie", $".AspNetCore.Identity.Application={authToken}");

                    var request = httpContextAccessor.HttpContext.Request;
                    client.BaseAddress = new Uri($"{request.Scheme}://{request.Host}/");
                    return client;
                });
```

This failed as httpContextAccessor is always null. I understand that SignalR doesn't have an HttpContext due to using websockets, but I'd still expect it to at least be there during Http Requests, such as when the app is first loaded, when the page is refreshed, or when an API method is called.

I have tried setting HttpOnly to false on the cookie and retrieving it through JSInterop to attach to the HttpClient. This failed as the API request would trigger before the Interop call completed.

I have tried countless different Startup configurations from the Microsoft documentation (Server-Side Blazor, Auth, .NET Core, etc) and any other source I could find. I have gone through many many StackOverflow questions as well with similar topics, but none of the solutions in any of those fixed the issue.

**Comment by pranavkm** [comment]
@Kizari have a look at the sample here to retrieve the cookie to used in your HttpClient: https://github.com/javiercn/blazor-server-aad-sample/blob/master/BlazorServerAuthWithAzureActiveDirectory/Pages/_Host.cshtml#L23-L33

**Comment by Kizari** [comment]
Thanks @pranavkm.

This isn't quite the exact same scenario, but I was able to adapt it to suit my needs.

For anyone else experiencing this issue, the fix was as follows:

**_Host.cshtml (if using Razor Pages)**

```
@{
    var token = HttpContext.Request.Cookies[".AspNetCore.Identity.Application"];
}

<app>
    <component type="typeof(App)" param-Token="token" render-mode="ServerPrerendered" />
</app>
```

I was using an MVC view rather than a Razor page in my example though. If doing it this way, get the token in the controller instead and pass it down to the view, for example:

**HomeController.cs**

```
[HttpGet]
public IActionResult Index()
{
    var token = HttpContext.Request.Cookies[".AspNetCore.Identity.Application"];
    return View(token);
}
```

**Index.cshtml**

```
@model string

...

<component type="typeof(App)" render-mode="ServerPrerendered" param-Token="@Model" />
```

And finally, regardless of which method is used, modify the Blazor app to apply the authentication cookie to HttpClient so that the User data will be present in API calls.

**App.razor**

```
@inject HttpClient HttpClient

...

@code
{
    [Parameter] public string Token { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        HttpClient.DefaultRequestHeaders.Add("Cookie", $".AspNetCore.Identity.Application={Token}");
    }
}
```
