### ISSUE TITLE
Adding New Razor View Does not work

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/aspnetcore#26485]
Started a new Blazor Server.
Added a new Razor View (NewPage.CSHTML)
Gave it @Page \"NewPage\" and \<h1>NewPage\<h1>

**when I navigate to the URL I get error "Sorry, there's nothing at this address."**

Deleted NewPage.cshtml
Made a copy of _Host.cshtml 
Renamed it to NewPage.cshtml
changed the code.

**Gave it @page "NewPage" and \<h1>NewPage\<h1>**

As if adding new Razor View no longer work.

I tried on both  <b>Visual Studio Enterprise 2019 16.7.5 </b>and **Visual Studio Enterprise 2019 Preview 16.8.0 Preview 3.2**

**Comment by javiercn** [comment]
@Sharaf-Mansour thanks for contacting us.

Razor views are for clasical web applications (MVC/Razor pages) you need to create a Razor component and use the `@page` directive.

The difference is that the file extension has to be `.razor`.

**Comment by Sharaf-Mansour** [comment]
@javiercn I understand.
But I use Razor Views to create charts using am4charts. Before it was working fine. I already have over 9 Working views.
When I add a new Razor view I can not Access it.
I must make a copy from an **Old** Razor view that is already working and then use it as a new Razor view.

**Comment by javiercn** [comment]
@Sharaf-Mansour I'm not sure I'm understanding what you mean.

From what I can infer, you are trying to move or mix & match a Blazor app with a traditional MVC/Razor pages app? And by that I mean that, some part of the app is developed entirely within Blazor and the rest is a Razor pages app. Is that the case?

If you are having problems linking to a Razor page, you can use `target=_blank` on the link Blazor will not intercept the link.

Does that help?

If this is not what you are asking, can you provide a bit more detail in what you are trying to achieve so that we can try and help you better?

**Comment by SteveSandersonMS** [comment]
Perhaps the issue is this:

```
@page "NewPage"
```

It should be this:

```
@page "/NewPage"
```

Please let us know if you're still having trouble. If so, can you provide a minimal application that reproduces the problem? Thanks!

**Comment by Sharaf-Mansour** [comment]
@SteveSandersonMS It worked thanks for your time sir. I am sorry for the mistake I am still learning.
@javiercn I have used Razor views and bind it with public static strings to get data from DataAccess to CSHTML.
I do not  know if what I am doing is the correct way or not but it works for me.

**Comment by Sharaf-Mansour** [comment]
@javiercn If you are familiar with Am4charts it uses JS to create Charts. 
I had to figure out a way to Copy a string value from C# into JS and create Dynamic JS data Property named after a C# value without using JS interop the way it intend to be used.
So here is what I did.
Step 1.
Create a public static C# class and add public static string property in it.
``
    public static string MyPublicStaticString {get;set;}
``
Step 2. bind the value into CSHTML h1 tag for example with the bind (@MyPublicStaticString)
``<h1 id="1234" style="display: none">@MyPublicStaticString</h1>
``
Step 3. write JS code that gets the innerHTML value
``        var x = document.getElementById("1234").innerHTML;
``
Step 4. Push x inside JS Data as Property name it looks like this
 
![image](https://user-images.githubusercontent.com/55330747/94843046-6f6de300-041c-11eb-8386-b55a1b8df460.png)
I started Blazor last year and I start learning C# 2 years ago. I am in love with Blazor but I have no idea how to achieve this with only C#

**Comment by Sharaf-Mansour** [comment]
I did a little improvement using Linq to do null check since I use fixed index values. 
![image](https://user-images.githubusercontent.com/55330747/94927990-4bb1a800-04c3-11eb-9756-7618b9375c8e.png)
I wish JS interop was much easier  but I am just happy that it works in the end.
I think I am still new to this there is a lot to learn.
I have this dream that one day Blazor will be a single code base technology that can work on all platforms with MVU pattern I can not wait for MAUI. (Blazor <3 MAUI).
