### ISSUE TITLE
Razor Semantic Token Performance

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26481]
Now that our Razor Semantic token requests also shell out to CSharp's Language Server I noticed a slowdown. We should do what we can to reduce that, here are some ideas:
- [x] Cache requests to CSharp Semantic Tokens (we already have some caching mechanisms, check that CSharp is benefiting from that and if it's not make it so)
- [ ] Improve speed on the CSharp side. (Obviously the empty-cache first response cannot be faster than the CSharp LSP, so lets see if the processing on that side is a significant problem or can be sped up).
- [x] Check for hotspots. (We may be doing silly things in our Semantic Token processing which a profiler would tell us about.)

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg how much of this is still actionable?

**Comment by ryanbrandenburg** [comment]
None of it really, after doing our profiling (and fixing the low-hanging fruit) Semantic tokens doesn't seem to be more or less performant than any call which results in "chatty" checks to the C# LSP, and those seem to be (at least in part) driven by Threading wait time. Closing this.
