### ISSUE TITLE
MultipartSection body stream corruption when accessed out of sequence

### ISSUE THREAD

**Issue by amjad-twalo** [dotnet/aspnetcore#26490]
### Describe the bug
We get corrupted data when accessing the MultipartSection.Body stream outside of the MultipartReader.ReadNextSectionAsync() loop. 
We don't want to read the streams uploaded in the request immediately, and instead we want to do it on demand in the background. We can successfully read the first section, but the following sections contain corrupted data.

### To Reproduce

``` C#
public async void TestMultipartReader()
{
    var request = CreateRequest();

    var reader = new MultipartReader(request.GetMultipartBoundary(), request.Body);
    reader.BodyLengthLimit = 4 * 1024 * 1024 * 6;
    MultipartSection section;

    // Accessing the streams inside ReadNextSection loop works just fine
    // while ((section = await reader.ReadNextSectionAsync().ConfigureAwait(false)) != null)
    // {
    //    var image = Image.FromStream(section.Body);
    //    Assert.NotNull(image);
    // }

    // Accessing the streams outside the ReadNextSection loop works for the first MultipartSection only
    // Next streams are corrupted and cause an ArgumentException in Image.FromStream
    List<Stream> streams = new List<Stream>();
    while ((section = await reader.ReadNextSectionAsync().ConfigureAwait(false)) != null)
    {
        streams.Add(section.Body);
    }

    foreach (var stream in streams)
    {
        var image = Image.FromStream(stream);
        Assert.NotNull(image);
    }
}
```
For easier reproduction, this is how we generate a sample request:

``` C#
private static string _boundary = "--boundary123";

private HttpRequest CreateRequest()
{
    var context = new DefaultHttpContext();
    var request = context.Request;

    using (var stream1 = File.OpenRead(TestImagePath1))
    using (var stream2 = File.OpenRead(TestImagePath2))
    {
        var content = CreateContent(stream1, stream2);

        request.Body = content;
        request.Headers.Add("Content-Type", "multipart/form-data; boundary=" + _boundary);
        request.Headers.ContentLength = content.Length;
        request.EnableBuffering();

        return request;
    }
}

private MemoryStream CreateContent(Stream stream1, Stream stream2)
{
    string multipartBoundary = _boundary;
    string sectionHeaders = "Content-Type: image/jpeg\r\n";

    var before = Invariant($"--{multipartBoundary}\r\n{sectionHeaders}\r\n");
    var middle = Invariant($"\r\n--{multipartBoundary}\r\n{sectionHeaders}\r\n");
    var after = Invariant($"\r\n--{multipartBoundary}--");

    var bytesBefore = Encoding.UTF8.GetBytes(before);
    var bytesMiddle = Encoding.UTF8.GetBytes(middle);
    var bytesAfter = Encoding.UTF8.GetBytes(after);

    var memoryStream = new MemoryStream();
    memoryStream.Write(bytesBefore, 0, bytesBefore.Length);
    stream1.CopyTo(memoryStream);
    memoryStream.Write(bytesMiddle, 0, bytesMiddle.Length);
    stream2.CopyTo(memoryStream);
    memoryStream.Write(bytesAfter, 0, bytesAfter.Length);

    memoryStream.Seek(0, SeekOrigin.Begin);

    return memoryStream;
}
```
### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.513 [C:\Program Files\dotnet\sdk]
  2.1.515 [C:\Program Files\dotnet\sdk]
  2.1.516 [C:\Program Files\dotnet\sdk]
  2.1.517 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Enterprise 2019
Version 16.7.3

**Comment by amjad-twalo** [comment]
Thanks @Tratcher for the answer.
Actually, we are calling HttpRequest.EnableBuffering() before reading any section, and I double checked while debugging and MultipartReader's _innerStream is always seekable.
From what I understand EnableBuffering is there to enable a scenario such as ours, or am I missing something?

**Comment by Tratcher** [comment]
I should have read your sample more closely 😁. Yes it should work with buffering enabled. Note request.EnableBuffering() is a no-op here because the request body is already a seekable MemoryStream.

I simplified the repro and realize what you're missing is a Seek on the streams. That's needed for the reasons I explained above, the MultipartReader can't find the next section until it's read the end of the current one.

```c#
using Microsoft.AspNetCore.WebUtilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp7
{
    class Program
    {
        static Task Main(string[] args)
        {
            return TestMultipartReader();
        }

        public static async Task TestMultipartReader()
        {
            using var stream1 = new MemoryStream(Encoding.UTF8.GetBytes(new string('1', 2560)));
            using var stream2 = new MemoryStream(Encoding.UTF8.GetBytes(new string('2', 2560)));

            var content = CreateContent(stream1, stream2);

            var reader = new MultipartReader(_boundary, content);
            reader.BodyLengthLimit = 4 * 1024 * 1024 * 6;
            MultipartSection section;
            /*
            // Accessing the streams inside ReadNextSection loop works just fine
            while ((section = await reader.ReadNextSectionAsync().ConfigureAwait(false)) != null)
            {
                Console.WriteLine("Multipart Stream:");
                Console.WriteLine(await section.ReadAsStringAsync());
            }
            */
            // Accessing the streams outside the ReadNextSection loop works for the first MultipartSection only
            // Next streams are corrupted and cause an ArgumentException in Image.FromStream
            List<Stream> streams = new List<Stream>();
            while ((section = await reader.ReadNextSectionAsync().ConfigureAwait(false)) != null)
            {
                streams.Add(section.Body);
            }

            foreach (var stream in streams)
            {
                Console.WriteLine("Stream:");
                stream.Seek(0, SeekOrigin.Begin);
                var data = new StreamReader(stream).ReadToEnd();
                Console.WriteLine(data);
            }
        }

        private static string _boundary = "boundary123";

        private static MemoryStream CreateContent(Stream stream1, Stream stream2)
        {
            string multipartBoundary = _boundary;
            string sectionHeaders = "Content-Type: image/jpeg\r\n";

            var before = $"--{multipartBoundary}\r\n{sectionHeaders}\r\n";
            var middle = $"\r\n--{multipartBoundary}\r\n{sectionHeaders}\r\n";
            var after = $"\r\n--{multipartBoundary}--";

            var bytesBefore = Encoding.UTF8.GetBytes(before);
            var bytesMiddle = Encoding.UTF8.GetBytes(middle);
            var bytesAfter = Encoding.UTF8.GetBytes(after);

            var memoryStream = new MemoryStream();
            memoryStream.Write(bytesBefore, 0, bytesBefore.Length);
            stream1.CopyTo(memoryStream);
            memoryStream.Write(bytesMiddle, 0, bytesMiddle.Length);
            stream2.CopyTo(memoryStream);
            memoryStream.Write(bytesAfter, 0, bytesAfter.Length);

            memoryStream.Seek(0, SeekOrigin.Begin);
            /*
            Console.WriteLine(new StreamReader(memoryStream).ReadToEnd());

            memoryStream.Seek(0, SeekOrigin.Begin);
            */
            return memoryStream;
        }
    }
}

```
