### ISSUE TITLE
Need a free option for Identity/Claims Management in ASP core

### ISSUE THREAD

**Issue by weedkiller** [dotnet/aspnetcore#26499]
**From today Identity Server is no longer free** 

I work for mom and pops stores who cant afford to be in this position. There was a huge commitment to using your framework and lot of work has gone in by @skoruba  and others here.

So, for the health of the project we need to see an option to use a different backend other than Identity Server. I just hate that MS dropped the ball on something so important. This core component should have been a feature in the main framework.

**Comment by mihaimyh** [comment]
MS offers identity services with Azure, I don't think they will be interested in your proposal.

**Comment by blowdart** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/26489
