### ISSUE TITLE
In /src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs's HandleAuthenticateAsync method, ConfigurationManager.RequestRefresh will never be respected

### ISSUE THREAD

**Issue by a3qz** [dotnet/aspnetcore#26504]
### Describe the bug
In JwtBearerHandler.cs.HandleAuthenticateAsync(), it appears that ConfigurationManager.GetConfigurationAsync is only called when the configuration is null.  It is possible to configure it such that it will call RequestRefresh if an error due to a key rollover happens, but it does not seem like there is any route where the request refresh actually does anything? From what I can see, the refresh only actually happens on the call to getconfigurationasync, which wouldn't happen since config is never set to null
### To Reproduce
Not really reproducable, just calling out an issue in a file/
 if (_configuration == null && Options.ConfigurationManager != null)
                {
                    _configuration = await Options.ConfigurationManager.GetConfigurationAsync(Context.RequestAborted);
                }

                            // Refresh the configuration for exceptions that may be caused by key rollovers. The user can also request a refresh in the event.
                            if (Options.RefreshOnIssuerKeyNotFound && Options.ConfigurationManager != null
                                && ex is SecurityTokenSignatureKeyNotFoundException)
                            {
                                Options.ConfigurationManager.RequestRefresh();
                            }

_configuration is never reset to null, so I don't see how the requested refresh would ever happen until a service restart.  

### Further technical details
- ASP.NET Core version : Latest

**Comment by a3qz** [comment]
Furthermore, GetConfigurationAsync reads from a cache, so what really is the optimization save here by not calling so long as it is not null?

**Comment by Tratcher** [comment]
JwtBearerHandler's lifetime is only for a single request, each request gets a new one. The requested refresh will happen for the next request. 

> Furthermore, GetConfigurationAsync reads from a cache, so what really is the optimization save here by not calling so long as it is not null?

This is about a request using a consistent configuration for all stages. We wouldn't want the config to change part way through or you could get inconsistent results.

**Comment by a3qz** [comment]
That makes sense, thanks @Tratcher
