### ISSUE TITLE
Light bulbs aren't working in Codespaces

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#26515]
First off, this is most likely an external issue but logging here because we'll need to be the ones doing the initial investigation.

Issues:
1. Component light bulbs aren't showing via ctrl + . (you must do right click => quick info)
2. C# light bulbs aren't showing up at all

**Comment by TanayParikh** [comment]
![CodespacesComponent](https://user-images.githubusercontent.com/14852843/94873059-0b8af080-0403-11eb-9ca7-a89d04284127.gif)

Diagnostics misaligned as well...

Why is semantic colorization working on an unrecognized component? cc/ @ryanbrandenburg

**Comment by TanayParikh** [comment]
Tried this out on VS Main, Liveshare Guest. It's working as expected there. Would that indicate any regression has since been addressed?

**Comment by NTaylorMullen** [comment]
> Why is semantic colorization working on an unrecognized component? cc/ @ryanbrandenburg

Is this on LiveShare guest or codespaces?

**Comment by TanayParikh** [comment]
> > Why is semantic colorization working on an unrecognized component? cc/ @ryanbrandenburg
> 
> Is this on LiveShare guest or codespaces?

CodeSpaces

**Comment by ryanbrandenburg** [comment]
The semantic tokens part of this looks like a stale-state problem, and as you pointed out the hover (and misaligned diagnostic) leads me to believe that it's not a problem specifically within SemanticTokens.

**Comment by TanayParikh** [comment]
I'm not seeing component (add using/fqn) lightbulbs in code spaces

**Comment by NTaylorMullen** [comment]
I was

**Comment by NTaylorMullen** [comment]
Pushing to 16.9-P2 to re-validate

**Comment by TanayParikh** [comment]
> Pushing to 16.9-P2 to re-validate

Couldn't validate as I ran into https://github.com/dotnet/aspnetcore/issues/27777.

**Comment by NTaylorMullen** [comment]
No longer reproduces with latest. Just validated.
