### ISSUE TITLE
How to call the controller part Dynamically in the Server-side Blazor application ?

### ISSUE THREAD

**Issue by Indrajith-Sync** [dotnet/aspnetcore#26529]
I need to call the Controller part from the razor section to remove the image stored locally. I tried the following way which works fine, but it refreshes the page after the remove action. Is there any other way to call the controller part without page refreshing ?

**Below is the controller from **CallController** function:**

**Index.Razor**

@code {
private async Task CallController()
    {
        await Http.PostAsJsonAsync("https://localhost:44348/api/Image/Remove", fileName);
    }
}

**The received controller part for removing the local image stored:**

**Controller.cs**

[HttpPost]
[Route("api/Image/Remove")]
public void Remove([FromBody] string fileName)
{
   string targetPath = hostingEnv.ContentRootPath + "\\wwwroot\\Images";
   fileName = targetPath + $@"\{fileName}";
    if (System.IO.File.Exists(fileName))
    {
       System.IO.File.Delete(fileName);
    }
}

Any idea of achieving this scenario, is much appreciated?

**Comment by javiercn** [comment]
@Indrajith-Sync thanks for contacting us.

It seems you are trying to call a controller on the same machine as your server-side Blazor application using HTTP Client?

We would recommend against this and instead suggest that you factor the business logic out into a common service and call it directly from the blazor application.

**Comment by Indrajith-Sync** [comment]
Yes, @javiercn . I want to perform an controller action from apllication end using the Http. It refreshes the page as like form support. Okay can you share any reference links for achieving this sceanrio ?

**Comment by Indrajith-Sync** [comment]
@javiercn , Any refrence links for achieving the senario using an service ?
