### ISSUE TITLE
In Codespaces typing out a self-closing tag auto-inserts @

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#26520]
This is the same as https://github.com/dotnet/aspnetcore/issues/24895 but in a Codespaces scenario.

**Comment by TanayParikh** [comment]
![24895](https://user-images.githubusercontent.com/14852843/94873883-4e4dc800-0405-11eb-9320-7194665ef507.gif)

**Comment by TanayParikh** [comment]
Possibly related; https://github.com/dotnet/aspnetcore/issues/23908 also still repros in code spaces.

**Comment by NTaylorMullen** [comment]
No longer valid
