### ISSUE TITLE
Scaffolding command in official documentation is broken (on Linux, at least)

### ISSUE THREAD

**Issue by john01dav** [dotnet/aspnetcore#26524]
### Describe the bug
The following scaffold command from [this page in the official documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=netcore-cli#scaffold-register-login-logout-and-registerconfirmation) is broken:

```dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout;Account.RegisterConfirmation"```

### To Reproduce
Here are the exact commands that reliably reproduce the bug on my system, including my attempts to fix it (installing requested packages) and the exact error messages:
```
[david@blue c#-projects]$ cd /tmp                    
[david@blue /tmp]$ dotnet new webapp --auth Individual -o WebApp1
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/3.1-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on WebApp1/WebApp1.csproj...
  Restore completed in 102.71 ms for /tmp/WebApp1/WebApp1.csproj.

Restore succeeded.

[david@blue /tmp]$ cd WebApp1 
[david@blue WebApp1]$ dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout;Account.RegisterConfirmation"
Building project ...
Scaffolding failed.
Add Microsoft.VisualStudio.Web.CodeGeneration.Design package to the project as a NuGet package reference.
To see more information, enable tracing by setting environment variable 'codegen_trace' = 1.
RunTime 00:00:04.36
[david@blue WebApp1]$ dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design                                                                                            
  Writing /tmp/tmpuDeUwH.tmp
info : Adding PackageReference for package 'Microsoft.VisualStudio.Web.CodeGeneration.Design' into project '/tmp/WebApp1/WebApp1.csproj'.
info : Restoring packages for /tmp/WebApp1/WebApp1.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.visualstudio.web.codegeneration.design/index.json 19ms
info : Package 'Microsoft.VisualStudio.Web.CodeGeneration.Design' is compatible with all the specified frameworks in project '/tmp/WebApp1/WebApp1.csproj'.
info : PackageReference for package 'Microsoft.VisualStudio.Web.CodeGeneration.Design' version '3.1.4' added to file '/tmp/WebApp1/WebApp1.csproj'.
info : Committing restore...
info : Generating MSBuild file /tmp/WebApp1/obj/WebApp1.csproj.nuget.g.props.
info : Writing assets file to disk. Path: /tmp/WebApp1/obj/project.assets.json
log  : Restore completed in 515.17 ms for /tmp/WebApp1/WebApp1.csproj.
[david@blue WebApp1]$ dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout;Account.RegisterConfirmation"
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
Please install the following packages to your project for scaffolding identity: Microsoft.EntityFrameworkCore.SqlServer
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:04.68
[david@blue WebApp1]$ dotnet add package Microsoft.EntityFrameworkCore.SqlServer                                                                                                     
  Writing /tmp/tmpbouOSr.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.SqlServer' into project '/tmp/WebApp1/WebApp1.csproj'.
info : Restoring packages for /tmp/WebApp1/WebApp1.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.sqlserver/index.json 153ms
info : Package 'Microsoft.EntityFrameworkCore.SqlServer' is compatible with all the specified frameworks in project '/tmp/WebApp1/WebApp1.csproj'.
info : PackageReference for package 'Microsoft.EntityFrameworkCore.SqlServer' version '3.1.8' added to file '/tmp/WebApp1/WebApp1.csproj'.
info : Committing restore...
info : Writing assets file to disk. Path: /tmp/WebApp1/obj/project.assets.json
log  : Restore completed in 420.98 ms for /tmp/WebApp1/WebApp1.csproj.
[david@blue WebApp1]$ dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout;Account.RegisterConfirmation"
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
A file matching the name Account.Register.cs.cshtml was not found within any of the folders: 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:05.93
[david@blue WebApp1]$ 
```

### Exceptions (if any)
See previous section

### Further technical details
ASP.NET Core version is in `dotnet info`. The issue takes place when using solely the `dotnet` command with no IDE.
```
$ dotnet --info                                                                                                                                                  
.NET Core SDK (reflecting any global.json):
 Version:   3.1.108
 Commit:    c423b556b5

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.108/

Host (useful for support):
  Version: 3.1.8
  Commit:  05a0c8f6b1

.NET Core SDKs installed:
  3.1.108 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
@deepchoudhery are you able to investigate this?  FYI @vijayrkn

**Comment by john01dav** [comment]
While waiting for this to be fixed, is there some place that I can download a fully scaffolded project to learn how to have accounts in my asp.net core apps? I'm about to be forced into a different backend framework, as a framework that I can't do authentication in is useless to me, but I really don't want to give up EFCore.

**Comment by mkArtakMSFT** [comment]
Ping @vijayrkn, @deepchoudhery

**Comment by jmgsalaices** [comment]
Hi
Affter the my large investigation for Scaffold Identity in CLI in Vs Code using dotnet aspnet-codegenerator. I haved many problems for the recent versions of .Net Core for ubuntu. Then Im take the radical decition for the genearte Scaffold Identity on Microsonft Visual Studio 2019 Installing a virtual Machine for Windows 10.
Affter I make commit in my git reopository and then open the project Visual Studio Code.
In conclution this is was the solution if you want Customize Login/Register Template.

**Comment by vijayrkn** [comment]
@deepchoudhery - Can you please prioritize this issue. Looks like the scaffolding is broken in non-windows environments.

**Comment by jmgsalaices** [comment]
> @deepchoudhery - Can you please prioritize this issue. Looks like the scaffolding is broken in non-windows environments.

https://github.com/dotnet/AspNetCore.Docs/pull/8752/commits/d3343a61f78b0e574a31c2df72215ed5d81a3198

**Comment by deepchoudhery** [comment]
yep will do.

**Comment by mkArtakMSFT** [comment]
@deepchoudhery any updates on this? Thanks!

**Comment by deepchoudhery** [comment]
@mkArtakMSFT this is fixed with the new 3.1.5 and 5.0.2 package out.
Use dotnet tool update dotnet-aspnet-codegenerator -g --version 3.1.5/5.0.2 depending on if you are targeting .netcoreapp3.1 or net5.0.

Apologize for the lengthy delay on this fix and appreciate all the feedback.

**Comment by mkArtakMSFT** [comment]
Reopening this issue per

**Comment by deepchoudhery** [comment]
@CKarakasSdet Could you detail on a couple things :
- Command used
- Error received
- Package versions for CodeGeneration (and EF/Identity if used) from .csproj

**Comment by CKarakasSdet** [comment]
> @CKarakasSdet Could you detail on a couple things :
> 
> * Command used
> * Error received
> * Package versions for CodeGeneration (and EF/Identity if used) from .csproj

Hello there. I am currently using Visual Studio 2019 For Mac. 
I used right click on controller folder and selected scaffolding from the menu > MVC controller with read / write actions but it gives error with the rest as well. 
Error is: 
Scaffolding failed.
Add Microsoft.VisualStudio.Web.CodeGeneration.Design package to the project as a NuGet package reference.
To see more information, enable tracing by setting environment variable 'codegen_trace' = 1.
RunTime 00:00:02.51

Scaffolding failed. 
assuming the following would help the best. 

<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.6"><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
</PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.6" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.6" />
  </ItemGroup>

**Comment by CKarakasSdet** [comment]
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.6"><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
<PrivateAssets>all</PrivateAssets>
</PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.6" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.6" />
  </ItemGroup>

**Comment by deepchoudhery** [comment]
Hmm this seems like an issue with build dependencies on VS Mac. I assume you have already tried it but try a clean and build/rebuild.

**Comment by CKarakasSdet** [comment]
yes I did.

**Comment by mkArtakMSFT** [comment]
@deepchoudhery what are the next steps here? Can you ping someone from VS4Mac side here?

**Comment by mkArtakMSFT** [comment]
Ping @deepchoudhery

**Comment by adityamandaleeka** [comment]
@deepchoudhery Ping.

I'm also moving this out of the "Next sprint planning" milestone.

**Comment by deepchoudhery** [comment]
@adityamandaleeka @mkArtakMSFT Oops missed these pings. Will address documentation issues right before GA since I'll be updating it for the entire project then. Ty

**Comment by adityamandaleeka** [comment]
@deepchoudhery Can this be closed now?
