### ISSUE TITLE
Add UserSecrets also on Local environment

### ISSUE THREAD

**Issue by lkurzyniec** [dotnet/aspnetcore#26539]
Currently `CreateDefaultBuilder()` adds `UserSecrets` only for Development env.
https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/src/WebHost.cs
```cs
if (env.IsDevelopment())
{
    var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
    if (appAssembly != null)
    {
        config.AddUserSecrets(appAssembly, optional: true);
    }
}
```

### Solution
I would like to have `UserSecrets` also for Local env.
```cs
if (env.IsDevelopment() || env.IsEnvironment("Local")) // or env.IsLocal() would be even better with a bit more changes
{
    var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
    if (appAssembly != null)
    {
        config.AddUserSecrets(appAssembly, optional: true);
    }
}
```

### Additional context
Usually Development env is a first stage of deploying whole solution (like QA). But earlier we have Local development on local machine where we have own configuration of environment (ie docker, sql server, etc). This requires to have separate `appsettings.Local.json` file with local settings (ie urls, passwords, server names, queues etc). I don't want to commit my local secrets, so I'm using `UserSecrets` to keep them safe.

If you would like to I can create a PR for that.

**Comment by Tratcher** [comment]
You can check this custom environment in your own app and add UserSecrets yourself. I don't see why we would modify the default host for a custom environment?

**Comment by davidfowl** [comment]
Agreed with @Tratcher

**Comment by lkurzyniec** [comment]
We could have a long discussion about is it `Stage` a custom env or not, why there is missing `Qa` env ;)

I just see that nowadays typically we have at least 2 envs where we are deploying whole solution - Dev and Prod. Is there something in between like Qa or Stage it's not a matter right now. But, before we anything deploy to Dev, we are making Local development and we are using local environment, like docker and/or locally installed app/tools. 
I just thought it would be nice to show everyone that developing and testing changes locally is very important, so having `appsettings.Local.json` file with local settings is a recommended approach. Going forward, keeping safe our secrets and using `User Secrets` is also recommended way. Having them added by default builder for a Local env would be a step further for both local testing and keeping safe our secrets.

If you don't like my idea, don't follow my thoughts, you can close this ticket, I have no problem with that ;)
