### ISSUE TITLE
Blazor Server how can i set the time for timeout when a user is offline?

### ISSUE THREAD

**Issue by Xeddon** [dotnet/aspnetcore#26534]
I use a default blazor Server project.
When the visitor go offline for longer than 20 minutes (default) the connection can not be restored. When the visitor go online the rejected function is called. I want that the hide function get called after maybe 1 hour.
How can i increase this time?

```
Blazor.defaultReconnectionHandler._reconnectionDisplay = createOwnDisplay();
        function createOwnDisplay() {
            return {
                hide: () => {
                    alert("You are online now and can continue");
                },
                rejected: () => {
                    alert("Your SignalR connection closed because you are 20 minutes or longer offline. This rejected is what need to be changed");
                    location.reload();
                }
            };
        }
```

**Comment by pranavkm** [comment]
You could configure https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.circuitoptions.disconnectedcircuitretentionperiod?view=aspnetcore-3.1 to change the timeout duration. Note that the longer the timeout, the longer server resources are retained for clients that have been disconnected.

See https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-3.1 for our conceptual docs that discusses this in detail.
