### ISSUE TITLE
Blazor component not getting recognized if #region is nearby

### ISSUE THREAD

**Issue by JonasRolstad** [dotnet/aspnetcore#26535]
### Blazor component not getting recognized because of #region
I'm developing in VS19 on a Blazor serverside application. 
The blazor component would just not be recognized as a component, but VS was determined that it was a class (aiming at the Blazor-component.razor.cs file). - and makes the build fail.
What was werid was that VS19 further up in the code had no problem recognizing other components (& the one I was trying to put out).

![image](https://user-images.githubusercontent.com/49019963/94922946-5d8f4d00-04bb-11eb-880f-ececda25b07f.png)

Turns out this was causing the issue:
"#region Personalia

#endregion" 

The moment I remove the "region"-code part the bottom components gets recognized. 
I can also add this to fix it on line 75:
`@var fixVar = "strange";`
![image](https://user-images.githubusercontent.com/49019963/94923031-8283c000-04bb-11eb-852b-f5f56cf44e25.png)

But the moment a blazor component comes right after a #region then it will fail.

While writing this I did notice that I was trying to add this #region in the .razor file, but it's all inside bracets of a "if(loaded){ }" - so in my head it should work as in the .cs file.

I rarely use #region in the first place, but the error it gives put you on a error-hunt where you believe you are missing some references or @usings.

### To Reproduce
In a Blazor component/page: place two components in the .razor file and put this between them:
"#region anyText

#endregion" 
Make sure the components and region are all inside a "@if(something) { }"-bracket

### Exclusions 
Doesn't happen when outside { }-brackets in the .razor file as #region will just be seen as html text.

**Comment by javiercn** [comment]
@JonasRolstad thanks for contacting us.

I don't think `#region` works within non-code fragments. I'd generally suggest you avoid them or use `@{ #region Start }` and `@{ #endregion }` instead, but I don't think `#region` is part of the Razor language in general.

/cc: @ajaybhargavb @NTaylorMullen
