### ISSUE TITLE
Kestrel dev certificate woes

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#26536]
### Describe the bug
Start my aspnet core project in VS 2019
Chrome warns me the certificate isn't trusted.
From the logs I can see kestrel is using the following certificate:

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[0]
      Using development certificate: CN=localhost (Thumbprint: 69BFE2859C3D9265666AE4328EB5ABF49B9D68E3)

```

However that certificate doesn't exist in the windows certifcate store.
It expired in July:

![image](https://user-images.githubusercontent.com/3176632/94927070-b1993200-04b9-11eb-9350-a163e8e90058.png)

I tried:

```
dotnet dev-certs https --clean
```

Which removed a bunch of certs, none of which were the one.

Then:

```
dotnet dev-certs https --trust

```

Problem still persists.

how do I remedy this?

### To Reproduce
Good question.

Here is info from my project file if it helps:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
```

### Further technical details
- ASP.NET Core version: 5.0.0-rc.1.*
- Include the output of `dotnet --info`
> 5.0.100-rc.1.20452.10
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 3.0

**Comment by davidfowl** [comment]
cc @javiercn

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dazinator .
Do you happen to run this in a container?

**Comment by dazinator** [comment]
@mkArtakMSFT  no not using containers. I am going to close this now as it seems to have resolved itself for the time being. Perhaps it was chrome caching something... will re-open if it crops up again.

**Comment by dazinator** [comment]
Re-opened as I am still hitting this issue.

**Comment by dazinator** [comment]
![image](https://user-images.githubusercontent.com/3176632/96452422-e83caf80-1210-11eb-80e6-710327f76a56.png)

**Comment by dazinator** [comment]
![image](https://user-images.githubusercontent.com/3176632/96452521-099d9b80-1211-11eb-8184-6436d2652d3e.png)

**Comment by dazinator** [comment]
I have searched the windows certificate store but I cannot find (under machine, or current user) such a certficate (i.e for localhost expiring on 25/07/2020)

**Comment by javiercn** [comment]
@dazinator Can it be that you have some code that is loading an exporting version of the developer certificate you are not aware of?

I would recommend just in case cleaning up `%APPDATA%\ASP.NET\Https` and grabbing the thumbprint for the certificate and running `Get-ChildItem cert:\ -Recurse | where -Property Thumbprint -EQ <<thumbprint>>` on Powershell to try and find it that way.

Also, just to make sure we are not missing anything, can you confirm that you are not using IIS? (Normally the port for Kestrel is 5001 unless you explicitly change it).

**Comment by dazinator** [comment]
> Also, just to make sure we are not missing anything, can you confirm that you are not using IIS? (Normally the port for Kestrel is 5001 unless you explicitly change it).

Yeah we are using kestrel, we don't use the default port, we've changed it to 62808 under the launch profile:

```
 "ProjectA": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "https://localhost:62808/",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "http://localhost:62807/;https://localhost:62808/;",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },


```

> Can it be that you have some code that is loading an exporting version of the developer certificate you are not aware of?

Nope. The entry point looks fairly typical for an asp.net core application, we configure kestrel against the following config section:

```
{
  "urls": "http://*:62807;https://*:62808",
  "Kestrel": {
    "Limits": {     
      "KeepAliveTimeout": "00:00:30"
    }
  }
}

```

> I would recommend just in case cleaning up %APPDATA%\ASP.NET\Https 

Thanks - this has helped pinpont the issue.
I noticed there was a `pfx` file in this folder named after my project executable.
When I deleted it, and started my project I saw this new log output:

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[0]
      Failed to locate the development https certificate at 'C:\Users\***\AppData\Roaming\ASP.NET\https\foo.pfx'.
```

Low and behold, the act of deleting that file, and restarting the project, has now caused the invalid cert in chrome to go away, and the latest cert (in the store) to apply and all is well:

![image](https://user-images.githubusercontent.com/3176632/96461292-1b387080-121c-11eb-9949-c188fe560214.png)

So I think perhaps this could be considered a bug? i.e the .pfx file in that directory acts as a type of "cache" and when you clean the certificate store (using this dotnet certs tool) - it doesn't clean this cache, and therefore kestrel continues to use the old pfx file (and therefore cert). If I have missed the docs about cleaning this cache I apologise.

**Comment by javiercn** [comment]
@dazinator might be, we only pick that cert as a last resource and it is typically used for containers, so at some point you used containers with this app and have a config key for the certificate password in your user secrets for the project which is what is triggering the app trying to load that cert. I'm not sure why that is taking precedence over the cert in the certificate store though.

**Comment by dazinator** [comment]
@javiercn

> so at some point you used containers with this app and have a config key for the certificate password in your user secrets for the project which is what is triggering the app trying to load that cert

Yep, we have a particular build / debug configuration for running the app inside a container that we used in the past. 

> I'm not sure why that is taking precedence over the cert in the certificate store though.

Yeah I am guessing this must be a bug. I'll leave this issue open but feel free to close if you think otherwise.

**Comment by dazinator** [comment]
.. and also just to confirm, the following user secret _is indeed present_ in the secret store:

`Kestrel:Certificates:Development:Password`

**Comment by javiercn** [comment]
For future reference, reading up the code, seems like we prefer the certificate file if we find the key on the settings.

**Comment by tdesmet** [comment]
I have been hitting this issue as well, deleting the file helped. Perhaps this can be documented somewhere?

Also I don't see Kestrel:Certificates:Development:Password anywhere

**Comment by jessicah** [comment]
I have run into this issue myself. The reference about `%APPDATA%\ASP.NET\Https` was on point in my case. I deleted the certificate apparently relating to my project, `BoltMembership.pfx` matching the name of my solution.

In my case, my project has been upgraded over time from .net core 3.x to .net 5.0 previews to release. After deleting that certificate, it now uses the machine wide certificate generated by `dotnet dev-certs https --trust`. Calls to `--clean` and `--trust` had no effect on my project due to that other (expired) certificate.

**Comment by rlightner** [comment]
I was having the same experience as @jessicah. Deleted `%APPDATA%\ASP.NET\Https` and it fixed it for me as well.

**Comment by brailowsky** [comment]
Same issue here (.net core 3.1), tried the "dotnet dev-certs https --clean" (and --trust) a few times.
Only after deleting the .pfx file in %APPDATA%\ASP.NET\Https things got back to work.

**Comment by steveoh** [comment]
Where is the corresponding `%APPDATA%\ASP.NET\Https` on macos?

**Comment by javiercn** [comment]
`~/.aspnet/https`

**Comment by adityamandaleeka** [comment]
@pratiksanglikar Can you please take a look? It sounds like the docker tooling is leaving behind an out-of-date cert.

**Comment by pratiksanglikar** [comment]
@adityamandaleeka, I am not sure how docker tooling leaves behind an expired cert.
All we do is check for a valid https cert using command `dotnet dev-certs https --trust --check` and if we don't find a valid cert, then we trust and export a cert using command - `dotnet dev-certs https --trust -ep "%APPDATA%\ASP.NET\https\<project-name>.pfx" -p <password>`.

My guess is that the certificate expired after it was created.
If that is the case, if the user is using docker tools again -
`dotnet dev-certs https --trust --check` should return an error and we create another cert.
And if the user isn't using docker tooling, I am not sure what docker tooling can do to remove any expired certs.

**Comment by dazinator** [comment]
> @adityamandaleeka, I am not sure how docker tooling leaves behind an expired cert.
> All we do is check for a valid https cert using command `dotnet dev-certs https --trust --check` and if we don't find a valid cert, then we trust and export a cert using command - `dotnet dev-certs https --trust -ep "%APPDATA%\ASP.NET\https\<project-name>.pfx" -p <password>`.
> 
> My guess is that the certificate expired after it was created.
> If that is the case, if the user is using docker tools again -
> `dotnet dev-certs https --trust --check` should return an error and we create another cert.
> And if the user isn't using docker tooling, I am not sure what docker tooling can do to remove any expired certs.

In my case, I had two different launch configurations in VS - one for launching the solution with docker, and another for launching it directly without docker. When launching without docker, the presence of this user secret `Kestrel:Certificates:Development:Password` causes the host to load the ssl cert from `%APPDATA%\ASP.NET\Https` which had expired  long time ago. When launching with docker, I think this is the cert that would get bind mounted into the container? The dotnet dev certs tool commands don't appear to do anything with this cert so I assume it is generated for use with docker. So the issue as I see it is that when not using docker, the host should not use this cert just because a secret is present called ``Kestrel:Certificates:Development:Password` - it should only use the cert when you are actually launching with docker. The secret is used to infer you are launching with docker it seems even when you aren't.

**Comment by adityamandaleeka** [comment]
@ldillonel

**Comment by rhires** [comment]
I just had this issue, when running with Kestrel as the webserver on localhost; I know this because the port is 7192, vs the IIS Express port of 44363, and when I changed the certificate name in %APPDATA%\ASP.NET\Https to no longer match the name of the project, Kestrel then chose the correct new certificate.

**Comment by adityamandaleeka** [comment]
This is being tracked in https://github.com/microsoft/DockerTools/issues/362
