### ISSUE TITLE
Multiple hubs per connection

### ISSUE THREAD

**Issue by tsproesser** [dotnet/aspnetcore#26537]
I know this is an old question

- https://stackoverflow.com/questions/11764360/multiple-signalr-connections-hubs-on-your-website
- https://github.com/aspnet/SignalR/issues/456
- https://github.com/aspnet/SignalR/issues/955

but never led to a satisfying answer and are archived, so I can't ask there. Since long-term I'm going to need this feature I wanted to ask if the decision to have a conneciton per hub is final (so I need to code a workarong [single hub injecting multiple services, service / method selection via hub message]) or if there is any little I do not need to reinvent the wheel :)

**Comment by BrennanConroy** [comment]
This is not something we are going to add to Asp.Net Core SignalR.
An alternative to injecting all the services in your Hub constructor is to resolve the `IServiceProvider` and manually resolve your dependencies in the hub methods.

**Comment by davidfowl** [comment]
To add to this, in the future we'll be looking at new transports that remove the networking cost of multiple hubs without changing the mapping of hubs to connections.

**Comment by tsproesser** [comment]
> To add to this, in the future we'll be looking at new transports that remove the networking cost of multiple hubs without changing the mapping of hubs to connections.

What "networking cost" are you talking about? You mean adding a flag with every message telling what hub should process it? Any idea when this implementation will be released?

And for now, just like @BrennanConroy said, go with one hub, inject a `IServiceProvider` and put a flag for Service / Method to invoke with every message I guess?

Thank you!

**Comment by davidfowl** [comment]
> What "networking cost" are you talking about? You mean adding a flag with every message telling what hub should process it? Any idea when this implementation will be released?

Single client opening multiple connections to talk to multiple hubs.

**Comment by tsproesser** [comment]
> > What "networking cost" are you talking about? You mean adding a flag with every message telling what hub should process it? Any idea when this implementation will be released?
> 
> Single client opening multiple connections to talk to multiple hubs.

Sorry, I still didn't get it ... Are you planning to find a solution "single connection per multiple hubs"? Or is this something not going to happen?
