### ISSUE TITLE
Disable antiforgery cookie by default

### ISSUE THREAD

**Issue by CrossBound** [dotnet/aspnetcore#26545]
By default adding an antiforgery token to an ASP.NET Core app by using `services.AddAntiforgery` will automatically send back the antiforgery token in a cookie. Moreover there does not appear to be any way to tell the API to not send back the cookie. For example, trying something like this
```csharp
services.AddAntiforgery(builder =>
{
    builder.Cookie = null;
});
```
does not work and will result in an exception (null not allowed).

The only method that I can find to remove this cookie is to name it something knowable:
```csharp
services.AddAntiforgery(builder =>
{
    builder.Cookie.Name = "XSRF-TOKEN";
});
```
and then remove it from the response within some custom middleware right before it is sent to the client
```csharp
Context.Response.OnStarting(() =>
{
    Context.Response.Cookies.Delete("XSRF-TOKEN");
    return Task.CompletedTask;
});
```

There are certainly some scenarios where sending the value in a cookie will be required, but this is not best practice and should be disabled by default. At the very least it should disable-able without requiring custom middleware to remove the cookie.

I suggest at a bare minimum enabling the cookie to be disabled through the `AntiforgeryOptions` with either a `SuppressCookie` field similar to the `SuppressXFrameOptionsHeader` field or by letting us set the `Cookie` field to null and letting that indicate to not send a cookie with the response.

[https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html) 
![image](https://user-images.githubusercontent.com/11417093/94947840-f023f200-04a3-11eb-99c1-406bb32a75ab.png)

**Comment by blowdart** [comment]
_this is not best practice and should be disabled by default_

Sorry, but no. The advantages to turning out CSRF protection by default for form POSTs, and starting part of the pair in a cookie far outweighs any risk of a misconfigured server that logs cookie values and the need to make an application stateful to use sessions.

To take quote from the OWASP cheat sheet and say that we're not using "best practice" is misunderstands the cheat sheet, given that 

1) In the section before the text you quote the cheat sheet says "It is strongly recommended to research if the framework you are using has an option to achieve CSRF protection by default before trying to build your custom token generating system. For example, _.NET has built-in protection that adds a token to CSRF vulnerable resources_." (emphasis added)

2) Further down the cheat sheet discusses [the technique we use](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie).

**Comment by CrossBound** [comment]
Let me clarify.

First: I am in no way suggesting _CSRF_ should be disabled. I fully agree that it provides many advantages. I am only asking for the ability to disable **_the cookie_**. 

Second: The risk or 'bad practice' I'm concerned about is not at all related to something on the server requiring state or logging the cookie values (I assume the cookie content is encrypted anyway). My concern centers around the fact that if you store the token in a cookie and then use that cookie on the server side to validate the request you are still open to a CSRF attack. Further more a miss-configured cookie could possibly leak the token if an XSS vulnerability exists.

Third: You are correct, I did not realize ASP.NET Core was using the Double Submit Cookie technique. I had looked at the documentation page you refer to (https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1), but I don't remember any reference at all to the Double Submit Cookie technique being used or any other reference to why the cookie was being sent back. I will go back and read the page again to verify I have not simply overlooked it.

Maybe the documentation page could simply be updated to include that information??

**Comment by blowdart** [comment]
If we disable the cookie, it has to be replaced with something. What would you suggest replaces it that works in every case that the cookie works in now, taking into account we can't require sessions?

**Comment by CrossBound** [comment]
If ASP.NET Core is using the double submit cookie technique with 2 different pieces that have to be taken together then I don't suggest any replacement for the cookie. This was the piece of information I was missing. Makes much more sense now, hence the reason I suggest documentation.
