### ISSUE TITLE
Make OAuth "access denied" error codes extendable?

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#26540]
### Is your feature request related to a problem? Please describe.

Some OAuth providers use non-standard or additional `"error"` values to indicate that a user has cancelled out of sign-in/authorization using OAuth.  Examples include Apple and LinkedIn:

  * https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/424
  * https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/480

By default these cause an unhandled exception in the application and bypass the `HandleAccessDeniedErrorAsync()` functionality as the `error` value is not exactly `"access_denied"`.

https://github.com/dotnet/aspnetcore/blob/56fa9413a6855be0b66287c510403af353f94167/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L75

At present the only fix for this is to override the `HandleRemoteAuthenticateAsync()` method and additional check for other error codes that should be treated as the same scenario.

### Describe the solution you'd like

The ability to configure additional error codes in `OAuthOptions` that can be optionally treated as "access denied".

For example, this could potentially be achieved via configuration:

```csharp
services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddCookie(options =>
{
    options.LoginPath = "/signin";
    options.LogoutPath = "/signout";
})
.AddLinkedIn(options =>
{
    options.ClientId = "my-client-id";
    options.ClientSecret = "my-client-secret";
    // New collection property that allows the status codes to be extended by configuration
    // By default it would contain "access_denied".
    options.AccessDeniedErrorCodes.Add("user_cancelled_authorize");
    options.AccessDeniedErrorCodes.Add("user_cancelled_login");
});
```

### Additional context

As this is the second time AspNet.Security.OAuth.Providers has had to implement custom handling for something that in theory should "just work" because of custom error codes, I thought it would be worth suggesting this functionality for .NET 6.

If however the OAuth spec is desired to be matched to exactly, with no deviation or ability to be customised/extended without "breaking the glass" as the above linked PRs have done with additional custom user code, then feel free to close.

**Comment by blowdart** [comment]
That's not unreasonable, but it's arguable whether user cancellation is the same as an authorization server denying access.

Perhaps a different event altogether?

**Comment by Tratcher** [comment]
It looks like in the apple example they were already overriding HandleRemoteAuthenticateAsync for other reasons so extensibility wouldn't help there? The fix you did for linked in looks quite reasonable for addressing something off-spec.

The OAuth base class is intended to cover the standard spec behaviors and give you the extensibility to address deviations. It seems to be doing that pretty well in your examples. Do you have many more examples of custom error codes returned by different services? Adding more granular extensibility just for LinkedIn doesn't seem warranted.

**Comment by martincostello** [comment]
If this was to be actioned, then I think an event would also be an acceptable solution.

For the Apple provider it was refactored previously to allow the parameters to come from either the Form or the Query.

Otherwise they are both pretty much just copy-paste from the base class with no changes other than the `error` values to treat as "access denied".

From our perspective, we only have Apple and LinkedIn as examples of providers where we've had to do this. The "ick" factor of the extensibility for this scenario is that it's otherwise pretty much line for line identical, rather than just overriding a very small and specific part, like [`FormatScope()`](https://github.com/dotnet/aspnetcore/blob/bbf7c8780c42e3d32aeec8018367037784eb9181/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L300) for example.

**Comment by blowdart** [comment]
If it's only two providers, I'm meh. It needs a bunch more for us to consider making a feature, when work arounds exist.

it's not surprise one is apple :)

Martin if you can indicate this is more common and the custom code path is super ikky, then please reopen with examples.
