### ISSUE TITLE
AddRedirectToHttpsPermanent issuing temporary redirect?

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#26543]
`AddRedirectToHttpPermanent appears to be issuing a 307 temporary redirect.

I have the following configuration in my Razor Pages application startup.

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseStatusCodePagesWithReExecute("/ErrorCode", "?code={0}");
        app.UseHsts();

        // Redirect to HTTPS and www prefix
        RewriteOptions options = new RewriteOptions()
            .AddRedirectToHttpsPermanent()
            .AddRedirectToWwwPermanent();
        app.UseRewriter(options);
    }

And yet if I attempt to access the HTTP version of my website, it appears I'm getting a temporary redirect (307).

```
Request URL: http://www.insiderarticles.com/
Request Method: GET
Status Code: 307 Internal Redirect
Referrer Policy: no-referrer-when-downgrade
Location: https://www.insiderarticles.com/
Non-Authoritative-Reason: HSTS
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Edg/85.0.564.63
```

Can anyone tell me how to make this work?

### Further technical details
- ASP.NET Core 3.1
- VS2019 16.7.4 (Windows)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Tratcher** [comment]
I think that redirect is happening on the client due to HSTS. See the `Non-Authoritative-Reason: HSTS` header.
https://stackoverflow.com/questions/34108241/non-authoritative-reason-header-field-http

**Comment by SoftCircuits** [comment]
@Tratcher I removed `app.UseHsts()` but it's still returning a 307. Please don't mark this as resolved yet.

It is a little confusing. `UseHsts()` is added by default, `UseRewriter()` seems like the only method that supports permanent redirects, and [Microsoft](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio) says to use `UseHttpsRedirection()`. I would think anyone with HTTP would want a permanent redirect. It should be the default.

**Comment by Tratcher** [comment]
HSTS is cached very heavily so combining it with UseHttpsRedirection functions like a permanent redirect. We only recommend permanent redirects for production scenarios, in development we recommend temporary redirects.

**Comment by SoftCircuits** [comment]
> HSTS is cached very heavily so combining it with UseHttpsRedirection functions like a permanent redirect. We only recommend permanent redirects for production scenarios, in development we recommend temporary redirects.

I'm sorry, I'm not sure I follow. The documentation for `UseHttpsRedirection()` seems to state clearly it is a temporary redirect. Is there some documentation that describes when it's a permanent redirect? All I want to do is redirect to HTTPS and WWW. Seems like this would be a standard request.

And all of this is taking place on the live site. As you can see from the question, it's my live home page on the web.

**Comment by Tratcher** [comment]
Yes, UseHttpsRedirection uses a temporary redirect status code, but adding HSTS means that the client will "permanently" use https. HSTS is more permanent than even a permanent redirect status code because it applies to the whole domain, not a specific URL, and can be cached for months or years.

**Comment by Tratcher** [comment]
I understand wanting to combine the HTTPS and WWW redirects, but HSTS means that people won't be hitting the HTTPS redirect very often so combining them isn't essential.

**Comment by SoftCircuits** [comment]
> Yes, UseHttpsRedirection uses a temporary redirect status code, but adding HSTS means that the client will "permanently" use https. HSTS is more permanent than even a permanent redirect status code because it applies to the whole domain, not a specific URL, and can be cached for months or years.

I'm also thinking in terms of telling Bing and Google that my URL has changed.

So, given what I'm trying to do, am I correct that you recommend I use the approach in my initial post on this?

**Comment by Tratcher** [comment]
Yes, your original sample is fine.
