### ISSUE TITLE
Blazor Virtualize Bug with updating UI

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#26557]
When incorporating Virtualize component in .Net 5 RC1, I have noticed that the UI does not update when the underlying collection is modified. I have already tried setting the Itemsize both in markup and css. This issue has been difficult to reproduce as the UI updates correctly with simple WeatherForecast objects. Therefore, I have recorded a video of this issue [here](https://www.youtube.com/watch?v=ezoW6y5ACUw). Thanks

**Comment by pranavkm** [comment]
@bancroftway we fixed a few issues with Virtualize in the rc2 milestone. Could you try grabbing our nightlies from : https://github.com/dotnet/installer#installers-and-binaries and see if it resolves the issue?

**Comment by bancroftway** [comment]
@pranavkm  This issue indeed has been fixed in the nightly build. Thank you so much
