### ISSUE TITLE
HTML Semantic colorization fails for @using directives

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26553]
Actual:
![image](https://user-images.githubusercontent.com/14987221/94965206-ed2efe80-04af-11eb-9fc5-3723fa7a7d3b.png)

Expected:
![image](https://user-images.githubusercontent.com/14987221/94965227-f4560c80-04af-11eb-8061-c1cf47030471.png)

**Comment by NTaylorMullen** [comment]
I think the correct thing to do here is HTML semantic colorization should just be handling the `@` transitions and ignoring the rest (textmate colorization + C# semantic colorization will do the needful)

**Comment by ryanbrandenburg** [comment]
Yeah, that was the intention, but something clearly went off the rails along the way.
