### ISSUE TITLE
scoped.styles.css available when run via CLI or VSCode, but not when run with Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26561]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1200688/scopedstylescss-available-when-run-via-cli-or-vsco.html)._

---
[severity:It's more difficult to complete my work]
I'm using the standard ASP Hosted Blazor Wasm project template, but I created a new RCL where I moved the MainLayout and NavMenu components. The RCL is only referenced by the Client project.

When I run my application using Visual Studio (either IIS Express or Project Launch options, using either Debug or Release config) there is no problem the first time, but when I change anything in the solution and run again, I receive a 404 for `_framework/scoped.styles.css`.

I'm using Visual Studio Version 16.8.0 Preview 3 along with SDK 5.0.100-rc.1.20452.10, although I noticed the issue at least three versions ago.

This issue is not present when I run the project using either the CLI or VSCode.

I can fix the site by either cleaning the server project and running again, or by referencing the RCL in the Server project directly.

---
#### Feedback Bot on 9/26/2020, 07:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by ElectricHavoc** [comment]
I'm also having this issue ( Blazor Server Side nothing fancy ). F5 isn't picking up scoped css changes. dotnet watch run does. Triggering a forced rebuild works, I suspect the engine not picking up the changes, or it thinks the css is static still.

Latest of all components VS Preview / RC1 - If I can get some time for a repo sln, I'll try to post one.

**Comment by mkArtakMSFT** [comment]
This should have been fixed as part of https://github.com/dotnet/aspnetcore/issues/24337 in RC2 release. Please try out the nightly RC2 build and let us know if you still face this issue.

**Comment by ElectricHavoc** [comment]
Installed 5.0.100-rtm.20507.2, (successful build, but now scoped.styles.css is getting a 404). - Checking docs for new sig...?

**Comment by ElectricHavoc** [comment]
Inspecting the obj folder, it does look like signature changed from:

~/[AssemblyName]/_framework/scoped.styles.css
to 
~/[AssemblyName].styles.css

Which works, although now I have other JSInterop issues I didn't have before.

**Comment by mkArtakMSFT** [comment]
Thanks for confirming, @ElectricHavoc.
If you're facing any other issues, please file separate bugs and we can look into these.

**Comment by ABIOLI-COM** [comment]
I just downloaded the Preview 4, and now I'm having the same problem, apparently.
I can see I have a '.../obj/debug/net5.0/scopedcss/bundle/[AssemblyName].styles.css, the contains the correct generation of the component CSS files, but how can I refer and use it in my Index.html page?

**Comment by ElectricHavoc** [comment]
@ABIOLI-COM 

See https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-2/
