### ISSUE TITLE
Razor HTML Semantic Tokens don't handle minimized attributes

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26563]
Case:
```html
<p attr />
```
Will cause a NotImplementedExcpetion to throw from within the SyntaxTreeWalker. That's because it's currently providing an invalid kind.

**Comment by ryanbrandenburg** [comment]
Fixed by https://github.com/dotnet/aspnetcore-tooling/pull/2583/files.

**Comment by TanayParikh** [comment]
Moving from triage to done.
