### ISSUE TITLE
Visual Studio is not publishing it's Blazor binaries properly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26562]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1101878/visual-studio-is-not-publishing-its-blazor-binarie.html)._

---
<p>Hello,</p><p>I think there is something fundamentally broken with my Visual Studio. I tried to repair but this didnt help. Tried uninstall visual studio and installed the community preview version. So the problem is that .dll files are properly copied to the project folder. Instead of using 109 files, it only takes 5. These files are the single page application files - all the DLLs, javascript and HTML that make up the website. When the installation builds - nothing is generated. Before, I haven’t got this kind of problem. My blazor app is not loaded fully, i don’t see anything, because there is no libraries in place.</p><p>I will copy the contents of the compile output. Maybe it will help. You can find in text file <a href="https://developercommunity.visualstudio.com/storage/attachments/144716-shouldbe.txt">shouldbe.txt</a> attached. This is how it outputs in project <a href="https://developercommunity.visualstudio.com/storage/attachments/144718-itis.txt">itis.txt</a>. In image files you can see the how it should look <a href="https://developercommunity.visualstudio.com/storage/attachments/144715-image.png">image.png</a> (assemblies are added) and how it looks now : <a href="https://developercommunity.visualstudio.com/storage/attachments/144714-issue1.png">issue1.png</a>. </p><p>Thank you.</p>

---
#### Feedback Bot on 7/5/2020, 08:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/6/2020, 00:40 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've made a fix recently for a bug, which caused similar issues. Please try the latest released preview version (RC1) and see whether you can repro it.
