### ISSUE TITLE
New Razor editor has some C# completion gaps

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#26578]
I am having a hard time with new Razor Editor - it often gets in my way:

That is how it looks in .cs file:

![good](https://user-images.githubusercontent.com/8482283/94991771-76fccb80-0585-11eb-8f7d-3b923d1743e3.gif)

That is my experience with the new Razor Editor:

![bad](https://user-images.githubusercontent.com/8482283/94991773-79f7bc00-0585-11eb-9624-af2055b61868.gif)

It seems to suggest (random) things with are then selected or it removes my characters.

Please advise!

**Comment by NTaylorMullen** [comment]
> I am having a hard time with new Razor Editor - it often gets in my way:

Love your feedback, and your gifs! A lot of these issues will actually be resolved in the 16.9-Preview1 timeframe. You can expec tthe new editor will have consistent completion experiences as outside of C#. /cc @AmadeusW & @dibarbet

**Comment by NTaylorMullen** [comment]
This has been resolved in the latest release.
