### ISSUE TITLE
[Blazor] Advice on where to report VS template change

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#26579]
Not really a Blazor bug, but something that does affect Blazor.

I won't go into detail about what the problem is (unless you are casually interested), but the cause of the problem ultimately is that the default code template that VS creates for the Dispose pattern sets the `bool` indicator for already-disposed at the end of the method when really it should be at the start.

I have no idea where to suggest this is changed and to present my argument. Can anyone help?

**Comment by blowdart** [comment]
Best route would be the built in feedback mechanism in VS, under the help menu is "Send Feedback"

**Comment by mrpmorris** [comment]
Thanks!
