### ISSUE TITLE
Should not allow changing health check name in health check implementation

### ISSUE THREAD

**Issue by weichch** [dotnet/aspnetcore#26572]
### Describe the bug
[`HealthCheckRegistration.Name`](https://github.com/dotnet/aspnetcore/blob/master/src/HealthChecks/Abstractions/src/HealthCheckRegistration.cs#L180) can be changed in health check implementation. This causes some issues:
- It defeats the purpose of [`ValidateRegistrations`](https://github.com/dotnet/aspnetcore/blob/master/src/HealthChecks/HealthChecks/src/DefaultHealthCheckService.cs#L158) method called in constructor of `DefaultHealthCheckService`
- One health check can override another health check's result, but all two will always run
- If registration name is immutable, `HealthCheckServiceOptions.Registrations` can be a dictionary, then `DefaultHealthCheckService.ValidateRegistrations` is no longer needed

Name is always needed when creating `HealthCheckRegistration` and repo search suggests the property setter is not used anywhere, so I guess it could be safely removed. The risk is this might be a potential breaking change which can break third-party code if any set the `Name` property.

Fix might look like https://github.com/weichch/aspnetcore/pull/2/commits/a21cd3caa88ba7fe5e19f81645c313400000ac37 if we only worry about the third bullet point above in this https://github.com/dotnet/aspnetcore/issues/26573 thread.

### To Reproduce

This unit test breaks:

```
private class NameChangingCheck : IHealthCheck
{
    public Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context,
        CancellationToken cancellationToken = default)
    {
        // Oh no!
        context.Registration.Name = "A";
        return Task.FromResult(HealthCheckResult.Unhealthy());
    }
}
    
[Fact]
public async Task CheckAsync_CheckRegistrationNameTest()
{
    var service = CreateHealthChecksService(builder =>
    {
        builder.AddCheck<NameCapturingCheck>("A");

        // Initially the check is added with name of B
        builder.AddCheck<NameChangingCheck>("B");
    });
    
    var results = await service.CheckHealthAsync();
    
    // Assert
    // This will never pass because there is no B anymore, and there are two A's
    // And this defeats the purpose of ValidateRegistrations method in DefaultHealthCheckService
    Assert.Collection(
        results.Entries,
        actual => Assert.Equal("A", actual.Key),
        actual => Assert.Equal("B", actual.Key));
}
```

### Exceptions (if any)

No exceptions.

### Further technical details
- ASP.NET Core version: 5.0.0-rc.1.20451.17

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Given that we haven't received other similar feedback and this will be a breaking change, we would prefer not to make it.
