### ISSUE TITLE
Allow save errored request information before ExceptionHandlerMiddleware clears HttpContext

### ISSUE THREAD

**Issue by weichch** [dotnet/aspnetcore#26574]
### Is your feature request related to a problem? Please describe.
I'm trying to write a custom exception handler middleware based on the out of the box one but allows converting exceptions to responses by convention. 

One thing I'm struggling with is the `ExceptionHandlerMiddleware` currently [clears endpoint and route information](https://github.com/dotnet/aspnetcore/blob/master/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L109) before it runs the `ExceptionHandler` delegate, so it is impossible to save information about the errored request in the `ExceptionHandler`.

For example, if I have a controller action decorated with my own exception handling metadata:
```
class MyController : Controller
{
    [MapException("error-handler-path")]
    public IActionResult MyAction() { }
}
```
The `MapException` attribute is cleared before my `ExceptionHandler` runs, so I have no chance to access the attribute.

The current workaround I'm using is adding a middleware after the `ExceptionHandlerMiddleware`, which extracts information I need before propagating the exception. You could see it [here](https://github.com/weichch/ExceptionMapper/blob/master/src/libraries/RabbitSharp.ExceptionMapper.AspNetCore/EndpointExceptionMappingMiddleware.cs#L67).

But, I don't like it. The extra middleware looks identical to `ExceptionHandlerMiddleware`, and it seems to me the same exception capturing process now happens in two different middleware components, and obviously mine is redundant if the default `ExceptionHandlerMiddleware` allows me to save request information before it clears HTTP context.

### Describe the solution you'd like
A new option in `ExceptionHandlerOptions` which allows access to the errored `HttpContext` before it gets cleared out.

For example:
```
public class ExceptionHandlerOptions
{
    public Action<HttpContext>? BeforeClearHttpContext { get; set; }
}
```

We could discuss the solution if the feature is not narrowly defined, and I'm happy to assist with the implementation if possible.

**Comment by Tratcher** [comment]
It might make sense to always capture the endpoint and route values in the error feature like it captures the request path today.
https://github.com/dotnet/aspnetcore/blob/ca1f9f532f540f16732e8d8b4990fbae1578786b/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L116

**Comment by weichch** [comment]
@Tratcher Yes, that will also do. I didn't realize `IRouteValuesFeature.RouteValues` has a setter. So was trying to avoid making a copy of the dictionary if possible.

**Comment by Kahbazi** [comment]
@Tratcher Is this issue up for grab?

**Comment by Tratcher** [comment]
Do you want to start by proposing an API?

**Comment by weichch** [comment]
The way I handled this in [my library](https://github.com/weichch/ExceptionMapper/blob/master/src/libraries/RabbitSharp.ExceptionMapper.AspNetCore/EndpointExceptionMappingMiddleware.cs#L165) is creating a new feature which contains two properties:

```
interface IEndpointExceptionFeature
{
    Endpoint? Endpoint { get; set; }
    RouteValueDictionary? RouteValues { get; set; }
}
```

I always captured the context and set the feature to `HttpContext`. Not sure if that's considered a breaking change, but if so, we could have a boolean value in `ExceptionHandlerOptions` to specify whether the capture is needed.

**Comment by Tratcher** [comment]
Hmm, the rout values collection is currently cleared rather than replaced. That makes capturing it problematic. It might be better to null out the property and let routing make a new one. 
https://github.com/dotnet/aspnetcore/blob/ca1f9f532f540f16732e8d8b4990fbae1578786b/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L156

**Comment by weichch** [comment]
> It might be better to null out the property
That would be a breaking change?

In my code, I create a copy of the route values using `RouteValueDictionary.FromArray(routeValues.ToArray())` before it gets cleared out.

**Comment by Tratcher** [comment]
> > It might be better to null out the property
> 
> That would be a breaking change?

I don't know if that feature is expected to be populated or not. We could also remove the IRouteValuesFeature which would avoid the issue since the app needs to be prepared for the feature not to be there.

**Comment by Kahbazi** [comment]
@Tratcher We could introduce a new `IExceptionHandlerEndpointFeature` which hold `Endpoint` and `RouteValueDictionary`
```
public interface IExceptionHandlerEndpointFeature
{
    Endpoint? Endpoint { get; set; }
    RouteValueDictionary? RouteValues { get; set; }
}
```
and set the feature before `ClearHttpContext` and also remove `IRouteValuesFeature` from features like you suggested or set the `IRouteValuesFeature.RouteValues` to null. The implementation would create a new dictionary if it's null.
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Http/Http/src/Features/RouteValuesFeature.cs#L20-L30

**Comment by Tratcher** [comment]
That sounds feasible. If IEndpointFeature and IRouteValuesFeature are not set then there's no need to set IExceptionHandlerEndpointFeature either.

Go ahead and try it.
