### ISSUE TITLE
blazor.server.js getClosestDomElement

### ISSUE THREAD

**Issue by bmarkov** [dotnet/aspnetcore#26589]
### Describe the bug

Issue in blazor.server.js

The following line 5568:

var c = i.getClosestDomElement(o).ownerDocument

i.getClosestDomElement(o) could return null, if o is a #comment or #textnode type of Node.

**Comment by javiercn** [comment]
@bmarkov thanks for contacting us.

We don't have enough context to determine this is an issue, can you provide more information about what is failing and hopefully a minimal repro project we can use to reproduce the issue?

**Comment by bmarkov** [comment]
We had an issue in one of our Blazor component implementations. Inside a DIV tag, we have a comment tag. It initially works Ok, but after re-render, we get an error in  blazor.server.js about getClosestDomElement(o) returning null and so throwing an Exception that it cannot access ownerDocument. "o" in this case was a HTML comment tag and as such it does not have ownerDocument. There is a bug on our side of course, but I think that in your code you also need to check whether the returned object is null and then get the ownerDocument.  

Hope this helps.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
