### ISSUE TITLE
[Blazor] Member value is shared between components, bug?

### ISSUE THREAD

**Issue by mwinkler** [dotnet/aspnetcore#26597]
### Describe the bug
I build a tree component witch is nesting itself for each child branch. The component has a member `Expanded` to define, if the child branch is shown/expanded.
The problem is, that if the member `Expanded` gets changed due the `@onclick` event, the value is also changed in its sibling components of the `foreach` loop.
I tried to add a `@key="node"` on the child component, but it doesn't help.

### To Reproduce
`Tree.razor`
```
@foreach (var node in Nodes ?? Enumerable.Empty<Node>())
{
    <div style="margin-left:2rem">
        <button @onclick="Toggle">@(Expanded ? "-" : "+")</button> Node
        @if (Expanded)
        {
            <Tree Nodes="node.Childs" />
        }
    </div>
}

@code {
    public class Node
    {
        public IEnumerable<Node> Childs { get; set; }
    }

    bool Expanded;

    [Parameter] public IEnumerable<Node> Nodes { get; set; }

    void Toggle() => Expanded = !Expanded;
}
```
`Index.razor`
```
@page "/"

<Tree Nodes="items" />

@code {
    IEnumerable<Tree.Node> items = new[]
    {
        new Tree.Node { Childs = new[] { new Tree.Node(), new Tree.Node() } },
        new Tree.Node { },
        new Tree.Node { },
        new Tree.Node { Childs = new[] { new Tree.Node(), new Tree.Node() } }
    };
}
```
Here is a example of the behavior:
![blazor-tree](https://user-images.githubusercontent.com/1729418/95028694-68f09d00-06a2-11eb-9a25-6e4eeb1e740b.gif)

What could be the problem here? Is this a bug?

### Further technical details
- ASP.NET Core version -> 5.0.100-rc.1.20452.10

**Comment by SteveSandersonMS** [comment]
This isn't a bug. You only have one variable called `Expanded` and are sharing it across everything in your `@foreach` loop.

I suspect what you intend to do instead is have `Expanded` be a member of `Node` (alongside `Childs`), so that each separate node has its own expansion status.
