### ISSUE TITLE
Blazor WebAssembly How can i trigger method in child component from Parent Component also by passing some parameter

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#26595]
I am using blazor webassembly 3.1
I have a need to execute a method in the child component from parent component.
I can find plenty of examples on how to update parent via events, but could not find any example on doing the reverse.
I  want to fire this method after certain time has elapsed from parent.
Any links to samples will be appreciated.

**Comment by glararan** [comment]
Use `@ref` - https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#capture-references-to-components there is an example

**Comment by nssidhu** [comment]
That works
