### ISSUE TITLE
Drop-in component for ASP Identity Administration, Portals, UI, SSO, Claims, Token, Multi.Tenant Management

### ISSUE THREAD

**Issue by papyr** [dotnet/aspnetcore#26594]
### Is your feature request related to a problem? Please describe.
I have been watching/waiting few yrs. patiently, however some recent changes have forced me to request -- Microsoft _revisit_ this for their developer community, keeping in mind some of the pricing out there compares to the salaries of 10 to 15 developers in Bangladesh, Vietnam, India, Philippines etc.

**Core & Basic need, yet very complex and critical.**

There's a _void in .NET native drop-in solution, unlike the Java, PHP Stacks etc_, where there are _many native drop in Identity Administration & Management Frameworks_ options that are leveraged across all their platforms seamlessly by developers, for e.g. the J2EE Pluggable Identity Management Framework or `JSR 168` or `JSR 286` or` JSR-351` or `JSR-375`. 

Why is this important? because using Java or PHP, it has allowed easy, clear, core and basic functionalities in those native stacks. As a result if you look `JSR 168` or `JSR 286` or` JSR-351` or `JSR-375` [Multi-tenants, Group to roles, or to claims vice versa is so easy vs. NET](https://javaee.github.io/security-spec/spec/jsr375-spec.html#_group_to_role_mapping) , mobile devices, portals, they all work seamlessly and cohesively with security fixes managed by either IBM or SalesForce or Oracle or Red Hat etc. This is enables developer to be productive right out of the gate.

In `.Net there is void`/very limited support, always requiring a combination of 3rd parties as a barrier to entry & adoption of ASP app. This is non-trivial for developers and security vulnerability that requires the attention of Microsoft Experts. 

Example: We have private information sharing site non OSS for the community almost free (pay if you want), and when we started with web forms, then Simple Membership, the Identity, Identity 2 ASP MVC we had implement much of it on top of these from scratch, when we moved to .Net Core it was another effort. Besides the development there was a lot of confusion on the internal concepts and how they now meant new things. Roles, Claims, Federation, SAML then SAML 2.0 and then Open ID 2.

### Describe the solution you'd like

1. A drop-in is extensible solution that supports ASP Identity eco-system, Administration, UI, SSO, Token, Multi-tenant Management
2. A configuration section to turn on-off the various features.
3. Embedded into VS Templates (remove Identity Server etc.)

### Additional context
The current options and the pricing eliminate many of the existing applications from continuing usage on the .NET stack without extensive retooling or completely abandoning the MS framework.

**Its really high time MS address this core gate-keeping feature!!**
![imgonline-com-ua-dexifnVLV6EByWXmE](https://user-images.githubusercontent.com/12733414/95019492-a66a1180-0633-11eb-967b-2f0b8401323c.jpg)

**Comment by blowdart** [comment]
No. When I locked one thread I didn't mean for others to spawn.
