### ISSUE TITLE
Determine file path of razor page at runtime 

### ISSUE THREAD

**Issue by pureggerstefan** [dotnet/aspnetcore#26603]
Greetings,

is there a possible way to determine the file path of the current .razor-Page displayed in Blazor wasm? For example when using localization and you want to access to resource files named same as the .razor's page path and need to it to the code behind.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We recommend using the capability of looking up resources by types. `IStringLocalizer` allows to do that: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#make-the-apps-content-localizable
