### ISSUE TITLE
Problem with OpenIdConnect

### ISSUE THREAD

**Issue by DHOFM** [dotnet/aspnetcore#26604]
Hi,
I try to connect with OIDC to a Governikus Autent Server. When the .../token URL is requested Autent requires client & secret as an authorization header. In RedeemAuthorizationCodeAsync in the OpenIdConnect Class the Header is not set. When I manipulate the request in the debugger like this: 
`requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Basic",Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes("client:secret)));
`
it works.

This must be done before
` var responseMessage = await Backchannel.SendAsync(requestMessage); `
in your class

The attend server requires it because of RFC 6749  - see it here: https://tools.ietf.org/html/rfc6749#section-2.3.1

Is this a general problem with your Library or what can I do to get the header set?

I use OIDC like this:
```

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddAuthentication(options => {
           options.DefaultScheme =  CookieAuthenticationDefaults.AuthenticationScheme;
           
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie()
 
        .AddOpenIdConnect(o =>
   {
       o.ClientId = "clientf";
       
       o.ClientSecret = "secret";
       o.SignInScheme="auth1";      
       
       o.Authority = "https://...";
       o.ResponseType = "code";
       
       o.CallbackPath = new PathString("/Home/Response");
        o.Scope.Clear();
        o.Scope.Add("openid");
        
   });`
```

Kind regards,

Dirk

**Comment by Tratcher** [comment]
>    Alternatively, the authorization server MAY support including the
   client credentials in the request-body using the following
   parameters: client_id... client_secret...

That's what is supported by this OIDC library.

https://github.com/dotnet/aspnetcore/issues/10615 is an open issue for supporting the `Basic` auth header format.

**Comment by Tratcher** [comment]
You can customize this today either by setting the OpenIdConnectOptions.Backchannel.DefaultRequestHeaders or by replacing OpenIdConnect.Events.OnAuthorizationCodeReceived to do the code redemption yourself.

**Comment by DHOFM** [comment]
@Tratcher Thanks for your response. The server will not support including the client credentials in the request-body, that was told to me by the vendors support. So I need to pass the Header. As you mentioned there are two possibilities. I could use the event like `o.Events.OnAuthorizationCodeReceived = async context =>
        {`

or I could use OpenIdConnectOptions.Backchannel.DefaultRequestHeaders which I would prefer. So if I do it like this:
`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddAuthentication(options => {
           options.DefaultScheme =  CookieAuthenticationDefaults.AuthenticationScheme;
           
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie()
 
        .AddOpenIdConnect(o =>
   {
       o.ClientId = "clientf";
       
       o.ClientSecret = "secret";
       o.SignInScheme="auth1";      
       
       o.Authority = "https://...";
       o.ResponseType = "code";
       o.Backchannel.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes("...")));
       o.CallbackPath = new PathString("/Home/Response");
        o.Scope.Clear();
        o.Scope.Add("openid");
        
   })`

The Backchannel is null which triggers an Exception:

`Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>.Configure(string name, TOptions options) in ConfigureNamedOptions.cs
Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string name) in OptionsFactory.cs
Microsoft.Extensions.Options.OptionsMonitor<TOptions>+<>c__DisplayClass11_0.<Get>b__0() in OptionsMonitor.cs
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy<T>.CreateValue()
System.Lazy<T>.get_Value()
Microsoft.Extensions.Options.OptionsCache<TOptions>.GetOrAdd(string name, Func<TOptions> createOptions) in OptionsCache.cs
Microsoft.Extensions.Options.OptionsMonitor<TOptions>.Get(string name) in OptionsMonitor.cs
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.InitializeAsync(AuthenticationScheme scheme, HttpContext context) in AuthenticationHandler.cs
Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, string authenticationScheme) in AuthenticationHandlerProvider.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in AuthenticationMiddleware.cs
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in AuthorizationMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) in DeveloperExceptionPageMiddleware.cs
`


Could you give me an advice how I can set it? 

Kind regards,

Dirk

**Comment by DHOFM** [comment]
@Tratcher Thanks for your response. The server will not support including the client credentials in the request-body, that was told to me by the vendors support. So I need to pass the Header. As you mentioned there are two possibilities. I could use the event like `o.Events.OnAuthorizationCodeReceived = async context =>
        {`

or I could use OpenIdConnectOptions.Backchannel.DefaultRequestHeaders which I would prefer. So if I do it like this:
`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddAuthentication(options => {
           options.DefaultScheme =  CookieAuthenticationDefaults.AuthenticationScheme;
           
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie()
 
        .AddOpenIdConnect(o =>
   {
       o.ClientId = "clientf";
       
       o.ClientSecret = "secret";
       o.SignInScheme="auth1";      
       
       o.Authority = "https://...";
       o.ResponseType = "code";
       o.Backchannel.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes("...")));
       o.CallbackPath = new PathString("/Home/Response");
        o.Scope.Clear();
        o.Scope.Add("openid");
        
   })`

The Backchannel is null which triggers an Exception:

`Microsoft.Extensions.Options.ConfigureNamedOptions<TOptions>.Configure(string name, TOptions options) in ConfigureNamedOptions.cs
Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string name) in OptionsFactory.cs
Microsoft.Extensions.Options.OptionsMonitor<TOptions>+<>c__DisplayClass11_0.<Get>b__0() in OptionsMonitor.cs
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy<T>.CreateValue()
System.Lazy<T>.get_Value()
Microsoft.Extensions.Options.OptionsCache<TOptions>.GetOrAdd(string name, Func<TOptions> createOptions) in OptionsCache.cs
Microsoft.Extensions.Options.OptionsMonitor<TOptions>.Get(string name) in OptionsMonitor.cs
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.InitializeAsync(AuthenticationScheme scheme, HttpContext context) in AuthenticationHandler.cs
Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, string authenticationScheme) in AuthenticationHandlerProvider.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in AuthenticationMiddleware.cs
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in AuthorizationMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) in DeveloperExceptionPageMiddleware.cs
`


Could you give me an advice how I can set it? 

Kind regards,

Dirk

**Comment by DHOFM** [comment]
Sorry for closing

**Comment by Tratcher** [comment]
You can set the Backchannel to `new HttpClient()`. Normally it would be created from some of the other Backchannel* properties, but it's fine to create it yourself.

**Comment by DHOFM** [comment]
@Tratcher Thanks very much, that works so far. But now I get an infinite loop, I described it here: https://github.com/dotnet/runtime/issues/43090#issuecomment-704308980
 After successful authorization - it jumps back to call the servers login page after the codechallenge came back to my callback url

**Comment by blowdart** [comment]
Closing as resolved because the bot is asleep.
