### ISSUE TITLE
warning about TopLevelParameterNameAnalyzer

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26609]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1205966/warning-about-toplevelparameternameanalyzer.html)._

---
[severity:Other]
I converted to .net core 5 rc a solution, and inside this solution I have a project created with the React Asp Template.
I compile the program and runs but I have this warning 

Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

---
#### Feedback Bot on 10/2/2020, 04:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/5/2020, 09:44 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for the issue report. Please look at https://github.com/dotnet/aspnetcore/issues/14723#issuecomment-588389938 for ways to address the issue. The bug is a result of reference to an ASP.NET Core 2.2 package that is currently out of support.
