### ISSUE TITLE
Renaming to existing tracked file name under git causes error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26613]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1206605/renaming-to-existing-tracked-file-name-under-git-c.html)._

---
[severity:It's more difficult to complete my work]
I am using the git integration with Visual Studio 2019. An example of the problem is if I have two files, "Index.razor", which is tracked, and "Index1.razor", which is not tracked. If I rename "Index.razor" to "Index2.razor",then right when I rename "Index1.razor" to "Index.razor", I get the error below.

I categorized this problem as "more difficult" because I don't know what effect this error is having on my project and files and git tracking.

```
  <entry>
    <record>3183</record>
    <time>2020/10/01 08:27:05.930</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.InvalidOperationException: Can not track document that's already being tracked file:///C:/.../source/repos/WEB/Pages/Index.razor&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServer.ContainedLanguage.DefaultLSPDocumentManager.TrackDocument(ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServerClient.Razor.RazorContentTypeChangeListener.RazorBufferCreated(ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.LanguageServerClient.Razor.RazorContentTypeChangeListener.ContentTypeChanged(ITextBuffer textBuffer, IContentType oldContentType, IContentType newContentType)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation.BufferFactoryService.&lt;&gt;c__DisplayClass90_1.&lt;BufferContentTypeChanged&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

---
#### Feedback Bot on 10/2/2020, 03:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.

**Comment by allisonchou** [comment]
This issue is tagged as being fixed in the new editor, so I'm going to close this out.
If you notice the problem persists in the new editor, please let us know by filing another issue. Thanks!
