### ISSUE TITLE
Razor Semantic Tokens should not be requesting the entire C# document

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26624]
Right now the Razor semantic tokens endpoint requests the entire C# document every time, but this is very inefficient. We need to start requesting only what we need. I see this as two scenarios:
- Request the edit since our last request on a textDocument/semanticTokens/edit request.
- Request only the document ranges which we are able to re-map and are requesting (both `textDocument/semanticTokens` and `textDocument/semanticTokens/range`.

This will possibly mean making multiple requests against the C# LSP and possibly entail maintaining multiple `razor/provideRazorSemanticToken*` endpoints on all platforms, so we'll want to think the design through thoroughly.

**Comment by allisonchou** [comment]
Addressed via https://github.com/dotnet/aspnetcore-tooling/pull/3450.
