### ISSUE TITLE
OIDC Infinite Loop

### ISSUE THREAD

**Issue by DHOFM** [dotnet/aspnetcore#26633]
Hi,
I mentioned a problem with the authorization header here: https://github.com/dotnet/aspnetcore/issues/26604#issuecomment-703767331

If I manipulate the header and the authorization works, I get an infinite loop.
The login is called, I authorize with German nPA, RedeemAuthorizationCodeAsync is triggered, the Callback URL is called and the OpenIdConnect Handler jumps back to the login from which the loop repeats again.

This is how I use it:
```

`   public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddAuthentication(options => {
           options.DefaultScheme =  CookieAuthenticationDefaults.AuthenticationScheme;
             
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })

        .AddCookie("auth1")
        
        .AddOpenIdConnect(o =>
   {
       o.ClientId = "...";
       
       o.ClientSecret = "...";
       o.SignInScheme="auth1";   
     
       
       o.Authority = "https://....";

       o.ResponseType = "code";
 
       o.CallbackPath = new PathString("/Home/Response");


        o.Scope.Clear();
        o.Scope.Add("openid");`
```

Not using Cookies will result in an Exception. Is it a problem with the cookie Authentication so that the login is called again? I test with localhost on Mac OS that shouldn't be the problem...

Regards,

Dirk

**Comment by Tratcher** [comment]
The CallbackPath should point to a unique path handled by the OIDC auth handler, it should not point to a controller.

If you're still stuck in a loop after that then please share a fiddler trace.

**Comment by DHOFM** [comment]
Im on Mac OS with no Fiddler installed, but I could share Wireshark or the network calls under Chrome if it helps. But if I understood you right I need to handle the OIDC auth with the Callback Path. Do you have an example because at the moment it is an controller...

**Comment by Tratcher** [comment]
AddOpenIdConnect will handle requests to the CallbackPath, you do not. Use the default value.

A Chrome trace works too.

**Comment by DHOFM** [comment]
so signin-oidc should be the callback URL?

**Comment by Tratcher** [comment]
Yes the default CallbackPath is `/signin-oidc`, register that with the service provider.

**Comment by DHOFM** [comment]
Thanks that helps a lot, so I will register that with the service provider and change
`o.CallbackPath = new PathString("/Home/Response");`

to 

`o.CallbackPath = new PathString("/signin-oidc");`

then it should work?

**Comment by Tratcher** [comment]
That's the default, you don't need to set CallbackPath. Try it and see.

**Comment by DHOFM** [comment]
Hi,
the server provider changed the URL and i use the default but the problem remains the same. Here is the Chrome Log, I anonymized the URL and clientID:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/27775323/95447794-95d2d780-0962-11eb-911f-7463ff1c0aea.png">

**Comment by DHOFM** [comment]
Additional information: After successfully Authorization in German Ausweisapp the URL is called: https://authentidtest.xyzde/signin-oidc?code=...&state=...

While this request is pending `protected override async Task<HandleRequestResult> HandleRemoteAuthenticateAsync()`
in the OpenIDConnectHadnler Class is called

**Comment by Tratcher** [comment]
The screenshot doesn't have enough information, we'd need the full trace exported to a file. The location header and cookies are important. You can send it to the e-mail in my profile if you want to keep it private.

**Comment by DHOFM** [comment]
Thanks. I have sent you the .har (JSON) log file to your e-Mail.

**Comment by Tratcher** [comment]
Your cookies and redirects all look fine, the OIDC flow completes and you end up with the `.AspNetCore.auth1` cookie. The question is why does /Home/Privacy reject it. Can you share the Startup code where you configured the Authentication, as well as how you marked the Privacy page as requiring auth?

**Comment by DHOFM** [comment]
Hi,
i am back right now and have sent you the files by mail, without credentials. Thanks a lot.

Kind regards,

Dirk

**Comment by Tratcher** [comment]
You've set the default scheme to `CookieAuthenticationDefaults.AuthenticationScheme`, but then added cookies with a different name: `.AddCookie("auth1")`. You get successfully signed in with the auth1 cookie, but then the app doesn't read that cookie when checking Authorize. Remove the name parameter from AddCookie so it uses the default and remove SignInScheme from AddOpenIdConnect so it also uses the default. 

Note OAuth Basic credentials should be FormUrlBase64 encoded, not just Base64 encoded.

app.UseAuthentication should come before app.UseAuthorization in Configure.

**Comment by DHOFM** [comment]
Thank you very much. Now it works :) One more question, I expect Claims like name, given_name and so on. But I only get:
`http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
b3f89e5b-edfc-41fb-9175-d168ecdb855a
http://schemas.microsoft.com/claims/authnclassreference
high
http://schemas.microsoft.com/claims/authnmethodsreferences
eid
http://schemas.microsoft.com/claims/authnmethodsreferences
de
auth_time
1603115056`


Maybe I need to ask the service provider, how it is encoded, because their specification lacks the information

Kind regards,

Dirk

**Comment by Tratcher** [comment]
Yeah, that's a question for your provider.

**Comment by DHOFM** [comment]
One more question I see a options.ClaimActions.MapUniqueJsonKey Extension in the Documents but I have no such extension - ClaimAction has only an add Method, am I missing something or is it removed?

**Comment by DHOFM** [comment]
Hi, I use this way now, I think it is not the correct way, but it works: 
`   o.ClaimActions.Add(new UniqueJsonKeyClaimAction("birthdate", "birthdate", "birthdate"));`

It's that what MapUniqueJsonKey should do...

**Comment by Tratcher** [comment]
They're extension methods so you need the right `using` namespace to include them.
https://github.com/dotnet/aspnetcore/blob/f54b590804ecacc328d9050ee1bdbaede9fb57a1/src/Security/Authentication/OpenIdConnect/src/ClaimActionCollectionUniqueExtensions.cs#L8

**Comment by DHOFM** [comment]
Wow i was of the opinion, I included all necessary namespaces, sorry for this stupid question. Works perfectly now, thanks a  lot 👍

**Comment by Tratcher** [comment]
No stupid questions, only stupid computers 😁.
