### ISSUE TITLE
Unable to dotnet run app on Mac, runs in Visual Studio 2019

### ISSUE THREAD

**Issue by dinonovak** [dotnet/aspnetcore#26641]
I am using macOS Catalina 10.15.7
.net core SDK installed is:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd
```

I have a Blazor Server up, that is running in Visual Studio 2019 without problems.
When I try to run the same app with dotnet run it is stuck and web server is never started
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.86
Using launch settings from /Users/dino/Codings/globtikseamanapplication/BlazorClient/Properties/launchSettings.json...

```

this is launchsettings.json
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:54209",
      "sslPort": 44381
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "BlazorClient": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please configure the logging in your application to the most detailed level and share the produced logs afterward: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging

**Comment by dinonovak** [comment]
Hi,

here is log level I have set up un appsettings.json

`  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Debug",
      "Microsoft.Hosting.Lifetime": "Debug"
    }`

Attached is log file
[dotnetrunlog.txt.zip](https://github.com/dotnet/aspnetcore/files/5343051/dotnetrunlog.txt.zip)
