### ISSUE TITLE
[Blazor WebAssembly] MS Graph Authentication Issue

### ISSUE THREAD

**Issue by mohamedcherifmo** [dotnet/aspnetcore#26655]
I'm trying to use AddMsalAuthentication with state as well as OfflineAccountClaimsPrincipalFactory, when the user logs in the application sees them as not logged in until a refresh and then everything works correctly

Add the following to program.cs
  builder.Services.AddMsalAuthentication<ApplicationAuthenticationState>(options =>
            {
                builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
                options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/Calendars.ReadWrite");
                options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/Tasks.ReadWrite");
                options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/Calendars.Read");

                options.ProviderOptions.LoginMode = "Redirect";
            })
            .AddAccountClaimsPrincipalFactory<ApplicationAuthenticationState,OfflineAccountClaimsPrincipalFactory>();

Publish the application and configure the tenant etc...

Click on login --> enter username and password for Azure AD.

The page will redirect back to the Blazor app however will still show "Login" button.
If i click F5 (refresh) the offline claim is added to indexdb and now shows authenticated user

- ASP.NET Core version 5 RC1

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mohamedcherifmo** [comment]
I tried creating a new minimal app and the same behavior doesn't occur in it. I will close the bug until i figure out what was wrong with my full package

**Comment by mohamedcherifmo** [comment]
It occured again in the new project, i can't really say for sure what's causing it since i reverted back the code and it still occured.

Here's a minimal version of the app
https://github.com/mohamedcherifmo/DoZen.BlazorClient

**Comment by mohamedcherifmo** [comment]
Is there a solution / workaround for it today?, will this be included in .net 5 release you mean?

**Comment by javiercn** [comment]
We do not think that this issue reproduces any longer. Please update to .NET 7.0 and let us know if you still face the issue.
