### ISSUE TITLE
Fix scaffolded`ResendEmailConfirmation.cshtml` error and success message handling

### ISSUE THREAD

**Issue by ibraheemdev** [dotnet/aspnetcore#26667]
The default scaffolded identity `ResendEmailConfirmation.cshtml`contains this code:
```cs
if (user == null)
{
  ModelState.AddModelError(string.Empty, "Verification email sent. Please check your email.");
  return Page();
}
```

Shouldn't the error be something like: `User not found`? At the end of the `OnGet` handler, it returns the same success message as a model error:
```cs
ModelState.AddModelError(string.Empty, "Verification email sent. Please check your email.");
return Page();
```

**Comment by blowdart** [comment]
This is a deliberate choice, to reduce the number of ways usernames can be enumerated by a potential attacker.

**Comment by ibraheemdev** [comment]
Then shouldnt it always redirect to a success message page? That would maintain security and improve UX.
