### ISSUE TITLE
dotnet watch run should allow properties forwarded to msbuild

### ISSUE THREAD

**Issue by an-dr-eas-k** [dotnet/aspnetcore#26662]
Currently I build projects with custom properties defined like GenerateFullPaths=true

With
```
dotnet watch run 
```
I cannot specify this custom property.

The crucial source code is found following this line:

https://github.com/dotnet/aspnetcore/blob/3ea1fc7aac9d43152908d5d45ae811f3df7ca399/src/Tools/dotnet-watch/src/Internal/MsBuildFileSetFactory.cs#L153

Please add a possibility to define msbuild properties passed on to build process.

**Comment by jkotalik** [comment]
@pranavkm ?

**Comment by fvoronin** [comment]
Maybe this issue should be transferred to dotnet/sdk ?

**Comment by szbotms** [comment]
Is there any update on this?
Thousands of us are waiting for this to be fixed.

**Comment by pranavkm** [comment]
Unfortunately not at this moment. The recommendation would be to configure these properties in the MSBuild file if you need them to work with watch. Moving this to backlog as it's not planned work for 6.0.

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/sdk/pull/31054
