### ISSUE TITLE
We hope that mobileblazorbindings can become an official project of Microsoft as soon as possible

### ISSUE THREAD

**Issue by 199621616** [dotnet/aspnetcore#26665]
I don't know if it's appropriate to open this request here. stay 
https://github.com/dotnet/aspnetcore/issues/26625#issuecomment704201049
Please vote for the relevant questions, and if you can't find them, create a new one for each question, mkartakmsft said. In this way, we can actually track these requests. Otherwise, many requests will be lost / forgotten（ https://github.com/dotnet/aspnetcore/issues/26625#issuecomment704410736）。 So it opened up here.

_MobileBlazorbindings in the experiment has got a good response. We hope that it can become a formal project of Microsoft as soon as possible, and can provide complete functions, so that users can focus on their own business logic, especially the hybrid applications. It seems to have a chance to surpass electron, more streamlined but more powerful._

**Comment by javiercn** [comment]
@199621616 thanks for contacting us.

Putting this on your radar @Eilon

**Comment by RChrisCoble** [comment]
I can't vote for this one enough. Blazor combined with MBB is a ticket to take .Net code to the web, then subsequently reuse basically all of that work to create iOS/Android apps with the exact same code.  

Don't try that with MAUI.

@Eilon make it happen!!!

**Comment by mkArtakMSFT** [comment]
Closing this as the work is tracked in another repo:  https://github.com/xamarin/MobileBlazorBindings
