### ISSUE TITLE
Authentication.ts

### ISSUE THREAD

**Issue by f9analytics** [dotnet/aspnetcore#26668]
### Describe the bug
When  loading Authentication.ts in VS CODE I receive the following error.
`

### To Reproduce

Simply Load the File in VS Code.

### Exceptions (if any)
`Property 'getUser' in type 'MsalAuthorizeService' is not assignable to the same property in base type 'AuthorizeService'.
  Type '() => Promise<object | undefined>' is not assignable to type '() => Promise<StringDict | undefined>'.
    Type 'Promise<object | undefined>' is not assignable to type 'Promise<StringDict | undefined>'.
      Type 'object | undefined' is not assignable to type 'StringDict | undefined'.
        Type 'object' is not assignable to type 'StringDict | undefined'.
          Type 'object' is not assignable to type 'StringDict'.
            Index signature is missing in type '{}'.`

### Further technical details
- ASP.NET Core 5.rc1
- The IDE VS Code/Win 10
- NPM
`{
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.9',
  cldr: '37.0',
  http_parser: '2.9.3',
  icu: '67.1',
  llhttp: '2.1.2',
  modules: '72',
  napi: '7',
  nghttp2: '1.41.0',
  node: '12.19.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.39.0',
  v8: '7.8.279.23-node.44',
  zlib: '1.2.11'
}`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We use this type successfully and it's not part of the public API service.
Can you share more details about what you're trying to do with it?

**Comment by f9analytics** [comment]
interface AuthorizeService {
    // getUser(): Promise<StringDict | undefined>;
    getAccessToken(request?: AccessTokenRequestOptions): Promise<AccessTokenResult>;
    signIn(state: any): Promise<AuthenticationResult>;
    completeSignIn(state: any): Promise<AuthenticationResult>;
    signOut(state: any): Promise<AuthenticationResult>;
    completeSignOut(url: string): Promise<AuthenticationResult>;
}

Comment Out GetUser()
