### ISSUE TITLE
"500.31 ANCM Failed to Find Native Dependencies" after installing patch updates

### ISSUE THREAD

**Issue by huysentruitw** [dotnet/aspnetcore#26673]
For a customer, we have multiple web-applications deployed to multiple on-premise VM's (hereafter 'locations'). The applications target dotnet3.1 and use ASP.NET Core 3.x with Angular 10. They're hosted in IIS and running in-process. 

Each month, the IT department installs security patches, which includes updates from .NET Core and ASP.NET Core Runtimes. They use software from _Ivanti_ to install the patches. The day after installing the patches, they have a reboot window in which they reboot all patched machines.

The install logs from previous update (3.1.5 to 3.1.7):

![image](https://user-images.githubusercontent.com/4618744/95377403-cc690d80-08e2-11eb-914b-2d4637adf1b5.png)

Now, there's one location where installing those patches breaks all web-applications running on that IIS instance until we reboot the machine or restart the IIS service. We had this when upgrading .NET Core & ASP.NET Core from 3.1.5 to 3.1.7 and again from 3.1.7 to 3.1.8.

The error we see when browsing to the application is: `HTTP Error 500.31 - ANCM Failed to Find Native Dependencies`.

The eventlog shows this (after installing 3.1.8):
![ANCM error](https://user-images.githubusercontent.com/4618744/95377076-549ae300-08e2-11eb-9564-b75fe110044b.jpg)

After we restart IIS or reboot the machine, all web-applications are working again correctly.

Other locations haven't shown this problem and the only thing special about that one location (where it fails) is that the web-applications on that machine are used 24h a day. So our guess is that when no applicationpools are running the updates work just fine, but when there is one or more application pools in use, things go south.

This is a serious bug as production cannot continue when this issue comes up so we need to come up with a proper solution.

My ideas so far are:
- Hosting out-of-process, as in kestrel with IIS as reverse proxy, but we have never done this + some of the applications need windows authentication 🤞
- Removing .NET Core & ASP.NET Core patch updates from the update scripts and install updates manually during the reboot window _if_ we think about them 😓
- Make our applications 'self-contained' and ship the entire runtime with the application 🤨

The problem with the first option will probably be the lack of windows authentication. The problem with the last 2 options is that we're essentially freezing the version and (security) patch updates will no longer get installed. The 3rd options might not even solve it.

We will probably go for option number 2 now so we don't get into trouble but we are seeking for a more sustainable solution.

Any help or new insights to this problem are welcome.

**Comment by huysentruitw** [comment]
Updated the ANCM error message in my post. I first thought it was 500.30, but we found a screenshot in our mails where it shows the 500.31 error.

**Comment by BrennanConroy** [comment]
@joeloff Any ideas here with regards to the installer and needing to reboot the machine?

**Comment by joeloff** [comment]
If the files are in use, modifying IIS (removing the old module and installing a new one), will likely trigger a reboot from Restart Manager to complete pending file renames. Insofar the IIS installation is concerned, it does stop and start some services.

@jkotalik would know which IIS services are stopped and restarted. AFAIK, it's not a simple _net stop/start_ operation

The ANCM installation log might help to shed some light on whether it was successful in stopping and restarting. 

Pending file renames is completely under the control of the OS and they only take effect after a reboot. You might be able to save time by completely stopping IIS, applying the update and then restarting. That way you should be able to avoid the locked files that trigger the renames, and restarting IIS should be faster than restarting a whole machine.

**Comment by jkotalik** [comment]
Triage notes: going to chat internally about this with @shirhatti

**Comment by huysentruitw** [comment]
Pinging to see if there's any update regarding this issue.

**Comment by huysentruitw** [comment]
Just read this article https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/

Does this mean we can no longer ignore .net updates and self-containing will be the only way to avoid this problem?

**Comment by joeloff** [comment]
@huysentruitw ignore in what way? If you have automatic updates (UA) enabled for other Microsoft products, it will include the .NET Core update. There are ways to opt out of it, though if you're in an enterprise environment, updates are usually managed through group policy. For servers the policies are usually different and allow the admins to determine when to apply them.

**Comment by wtgodbe** [comment]
@jkotalik @shirhatti did you wind up thinking of a good solution for this?

**Comment by jkotalik** [comment]
We didn't get the chance to discuss this yet, @shirhatti feel free to schedule some time.

**Comment by jkotalik** [comment]
Current hypothesis:

When the 3.1.8 runtime was installed, the msi engine starts both an uninstall on 3.1.7 and install for 3.1.8. If the files are in use for 3.1.7 (because they are used by IIS) then all 3.1.7 files will be pending restart ([MsiSystemRebootPending](https://docs.microsoft.com/en-us/windows/win32/msi/msisystemrebootpending)). Then, when the app starts again, for some reason the roll forward logic thinks 3.1.8 is installed (maybe due to this [reg key](https://github.com/dotnet/aspnetcore/blob/master/src/Installers/Windows/SharedFramework/Product.wxs#L66), even though the folder isn't present with respect to the w3wp process. So when the app starts up again, it tries to use 3.1.8 even though it isn't done installing.

@joeloff does this hypothesis seem likely to you? Also, how does the installer check if any dotnet processes are currently running s.t. it gives the right warning saying you need to reboot? Maybe it isn't checking for w3wp?

**Comment by joeloff** [comment]
The upgrade model that ANCM follows is to schedule RemoveExistingProducts (seq 6601) after InstallFinalize (seq 6600). This model has some performance benefits, but also limits what you are allowed to do during a major upgrade. When you upgrade from 3.1.7 to 3.1.8, the 3.1.8 install is applied on top of 3.1.7 and then 3.1.7 is removed at the end. I do agree that if something like w3p is restarted after the pending file rename is registered, but before the machine reboots to complete the rename the behavior can be unexpected.

@jkotalik The locked files are calculated early on during the InstallValidate action. Most of the heavy lifting is done by the Restart Manager in the OS. AFAIK, the action simply processes the results it gets back from RM. There is some logic to find actual applications (e.g. resolve potential window handles to provide more detailed information) if you were running the MSI with a full UI install. We would need to look at the OS code to determine how the MSI engine and RM actually interacts.

Below is from another install (5.0.1) where dotnet.exe was locked, but it shows what to look for in the logs. Again, this will all depend on how RM reports information:

```
Action start 12:40:38: InstallValidate.
MSI (s) (34:44) [12:40:38:315]: Note: 1: 2205 2:  3: _RemoveFilePath 
MSI (s) (34:44) [12:40:38:315]: PROPERTY CHANGE: Modifying CostingComplete property. Its current value is '0'. Its new value: '1'.
MSI (c) (44:A0) [12:40:38:347]: RESTART MANAGER: Session opened.
MSI (s) (34:44) [12:40:38:362]: RESTART MANAGER: The user chose to go on with the installation, although a reboot will be required.
MSI (s) (34:44) [12:40:38:362]: Note: 1: 2727 2:  
The setup must update files or services that cannot be updated while the system is running. If you choose to continue, a reboot will be required to complete the setup.
```

The last part is the actual message that the MSI would have shown when run in full UI mode.

Then, when InstallFinalize executes it will log more details

```
MSI (s) (34:44) [12:40:40:862]: Product: Microsoft .NET Host - 5.0.1 (x64). The file C:\Program Files\dotnet\dotnet.exe is being used by the following process: Name: dotnet , Id 13144.
MSI (s) (34:44) [12:40:40:862]: Verifying accessibility of file: dotnet.exe
Info 1603.The file C:\Program Files\dotnet\dotnet.exe is being held in use.  Close that application and retry.
```

**Comment by dougbu** [comment]
@jkotalik this is another issue about updating ANCM files while IIS is running. Handle pleazzze

**Comment by dougbu** [comment]
After some conversations on this topic, we're closing because there's no better option than ensuring the service is shut down while doing the upgrade. Both ANCM itself and the .NET runtime are likely locked if IIS is up and the particular site is in use.

Bottom line,
1. Shut down IIS
2. To be extra careful, kill any `dotnet` processes that remain
3. Perform the bundle installation
4. Start IIS
