### ISSUE TITLE
Add LoggedTest to Components E2E and Blazor template tests

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#26679]
The LoggedTest infrastructure is now available to Components E2E and Blazor template tests, however it isn't being used yet as that probably requires some knowledge around those tests to use it correctly.

Here is the change to fix the infrastructure and add the logging to the other template tests.
https://github.com/dotnet/aspnetcore/pull/26507

**Comment by HaoK** [comment]
Keeping this open to track doing this as well for components

**Comment by HaoK** [comment]
Blazor templates is done, components will be done automatically when we switch over to the new playwright infrastructure so resolving this issue, remaining work will be done as part of https://github.com/dotnet/aspnetcore/issues/31159
