### ISSUE TITLE
Please Help! I get this error when i try to lauch my web app using local IIS - HTTP Error 500.0 - ANCM In-Process Handler Load Failure 

### ISSUE THREAD

**Issue by Pitchpool** [dotnet/aspnetcore#26672]
Troubleshooting steps:

    Check the system event log for error messages
    Enable logging the application process' stdout messages
    Attach a debugger to the application process and inspect

For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526

**Comment by BrennanConroy** [comment]
Have you tried the troubleshooting steps?

**Comment by Pitchpool** [comment]
I have tried troubleshooting but I haven't been successful. I have been on this issue for days now and it's quite fraustrating

**Comment by Pitchpool** [comment]
When I launch my application from VS 2019 everything works perfectly. But when I try to deploy to my local IIS for testing I experience this problem

**Comment by BrennanConroy** [comment]
> I have tried troubleshooting

Specifically the ones listed in the error?
```
Check the system event log for error messages
Enable logging the application process' stdout messages
```

What do your event logs show and can you share them?
Have you enabled stdout logs and can you share them?
