### ISSUE TITLE
Blazor, MVVM, ICommand

### ISSUE THREAD

**Issue by virzak** [dotnet/aspnetcore#26677]
### Is your feature request related to a problem? Please describe.

Not being able to use [ICommand](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.icommand) is an inconvenience with blazor.

Here is a [commit](https://github.com/virzak/blazor-wasm/commit/6b15c5f5dc61e333c3dbfec41fd09dd40cd5302f) in a fork of [JeremyLikness/blazor-wasm](https://github.com/JeremyLikness/blazor-wasm) which uses ICommand

Having to use `@onclick="@(() => Model.DecrementCommand.Execute(true))"` is not ideal. Other than that it seems to work well.

### Describe the solution you'd like

Passing ICommand to button markup would be perfect. In @JeremyLikness excellent [article](https://blog.jeremylikness.com/blog/2019-01-04_mvvm-support-in-blazor/) Blazor is described as in "early state", which is not so early now, correct?

### Additional context

There is a large MVVM WPF application which needs to move to the web, so using Blazor would help avoiding rewriting a lot of code into Typescript. The idea is to share as much code as possible between Blazor and WPF. Still exploring this idea, but at this point it seems that we'll need to convert ViewModel primitives to be platform agnostic: [Point](https://docs.microsoft.com/en-us/dotnet/api/system.windows.point) => [PointF](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.pointf) as well as creating a "base" class for MouseEventArgs of [Wpf](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.mouseeventargs) and [Web](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.web.mouseeventargs)

Using ICommand has additional benefit of moving business logic out of razor files. [Decrement](https://github.com/JeremyLikness/blazor-wasm/blob/96954561b3676180972d651e3f8e92939d17843e/MvvmPattern/MvvmPattern/Shared/Age.razor#L12-L25
) method is now in .cs file and can be shared across platforms.

This solution uses Microsoft.Toolkit.Mvvm @Sergio0694 

Looks like there was a prior discussion on this #16331

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This ask is not aligned with our vision and we have no plans to implement this as part of the framework. This is a great opportunity for the community to come up with solutions and we encourage users who are interested in those models use community-based solutions.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
