### ISSUE TITLE
Office Web Add-in development using C# / Blazor

### ISSUE THREAD

**Issue by Lux44** [dotnet/aspnetcore#26675]
[Office add-ins ](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins) are a powerful tool to extend the functionality of the Office applications. The new Office add-in platform is based on an embedded web site, interaction with client application and documents is accomplished using Office.js JavaScript APIs.

Would it be possible to use Blazor to develop Office add-ins in C#, as Blazor supports JavaScript interop?

It would provide more seamless migration path for existing VSTO add-ins. Also it sounds great if ".NET Everywhere" includes Office.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a good feedback for the Office team. We recommend using the Office feedback functionality for this: https://support.microsoft.com/en-us/office/send-feedback-or-report-an-issue-a557a90a-828c-482f-8a71-f933499e70f4
