### ISSUE TITLE
response headers do not contain grpc-accept-encoding and accept-encoding

### ISSUE THREAD

**Issue by new2helm** [dotnet/aspnetcore#26697]
I have a grpc service which uses kestrel web-server. When I hit an endpoint the response headers I received are 

Response headers received:
content-type: application/grpc
date: Wed, 07 Oct 2020 17:53:36 GMT
server: Kestrel
Response contents:
{
  "status": "SERVING"
}
Response trailers received:
(empty)
Sent 0 requests and received 1 response

I want the headers to also report 

Response headers received:
accept-encoding: identity,gzip
content-type: application/grpc
grpc-accept-encoding: identity,deflate,gzip
Response contents:
{
  "status": "SERVING"
}
Response trailers received:
(empty)
Sent 0 requests and received 1 response

For incorporating this, I added 

services.AddGrpc((options) =>
options.ResponseCompressionLevel = CompressionLevel.Optimal;
options.ResponseCompressionAlgorithm = "gzip";

but this doesn't effect the headers that are being returned. It still gives me the same header response.

**Comment by JamesNK** [comment]
The `grpc-accept-encoding` header is only sent by the server if the client uses a compression scheme the server doesn't support. This is correct according to the gRPC compression specification.

`accept-encoding` is never set by gRPC.

Why do you want those headers to be sent by the server?

**Comment by new2helm** [comment]
I have 2 grpc services which are using grpc_health_probe for liveness and readiness check. 

One of the service which has the following response header is gving me error: health rpc failed: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR

Response headers received:
content-type: application/grpc
date: Wed, 07 Oct 2020 17:53:36 GMT
server: Kestrel
Response contents:
{
"status": "SERVING"
}
Response trailers received:
(empty)
Sent 0 requests and received 1 response


whereas the other grpc service which has the following response headers, passes the grpc_health_probe 

Request metadata to send:

(empty)
Response headers received:
accept-encoding: identity,gzip
content-type: application/grpc
grpc-accept-encoding: identity,deflate,gzip
Response contents:
{
  "status": "SERVING"
}
Response trailers received:

(empty)

Sent 0 requests and received 1 response

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc/blob/master/doc/compression.md

`grpc-accept-encoding` only needs to be sent in the response if a requested compression format isn't supported, or a compressed message is sent in the request that isn't supported.

`accept-encoding` is not used by gRPC.

You need to look at logging related to your error to find out what the problem is.
