### ISSUE TITLE
[Blazor WebAssembly] Error when deploying on IIS even though code works in debug mode

### ISSUE THREAD

**Issue by mohamedcherifmo** [dotnet/aspnetcore#26698]
I updated the fetch data function to retrieve from an external source and enabled it to read from localStorage as well using the following code:

```csharp
 protected override async Task OnInitializedAsync()
    {
        Console.WriteLine("Initialize Fetch Data");
        
         var locallyStoredArticles= await JS.InvokeAsync<string>(
               "sessionDoZenStorage.getItem", "NewsInfo");

        if (locallyStoredArticles != null)
        {
           Console.WriteLine("locallyStoredArticles is not null");
           articles = JsonSerializer.Deserialize<NewsArticle[]>(locallyStoredArticles);
           

        }
        StateHasChanged();
        var newsInfo = await Http.GetStringAsync("https://localhost:44307/weatherforecast");
     articles = JsonSerializer.Deserialize<NewsArticle[]>(newsInfo);
         await JS.InvokeVoidAsync("sessionDoZenStorage.setItem",
                      "NewsInfo", newsInfo);
                      
   StateHasChanged();
      
    }
```

The code works as expected in debug mode, but once i publish on IIS i get the following errors in the console:

* Assertion at /__w/1/s/src/mono/mono/metadata/threads.c:354, condition `<disabled>' not met

Uncaught (in promise) message: "Program terminated with exit(0)"
name: "ExitStatus"
status: 0

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mohamedcherifmo** [comment]
Here you go
Sample code in the link below
https://github.com/mohamedcherifmo/MonoError

**Comment by joadan** [comment]
I have the same problem, works in debug but fails when I publish to github pages, tried to disable linker but no luck.

**Comment by dantronik-markus** [comment]
This is the same cause as https://github.com/dotnet/runtime/issues/42628 and *apparently*, the fix is not yet part of 5.0rc2.

**Comment by joer33304** [comment]
What is the status here ? This is a SEVERE blocker and not fixed in official 5 release. I get this when publishing to Azure using windows app service. Works fine in debug and release mode LOCALLY.

**Comment by yashizuko** [comment]
Im having this issue, not sure where to hit my head, in my case is blazor server, but the oddity of the situation is the same, Deployed on Azure windows app service

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please try the .NET 6 release and see whether that resolved your issues.

**Comment by dantronik-markus** [comment]
I haven't had this issue in a while now, but maybe others can chime in as well just to make sure.

**Comment by mkArtakMSFT** [comment]
@yashizuko can you file a separate issue and provide a minimal repro for it in  a public GitHub repo?

As for this issue, it seems to be fixed already, so we're closing this issue.
