### ISSUE TITLE
Out of sync database and code causes a Gateway Timeout 504 rather than an Internal Server Error 500

### ISSUE THREAD

**Issue by alexanderkenney** [dotnet/aspnetcore#26695]
### Describe the bug
When a database schema and source code, containing repository methods for retrieving data from the database, is out of sync the server responds with a Gateway Timeout 504 rather than the expected Internal Server 500 response.

### To Reproduce
Amend a model to add an additional value. In my case it was a nullable boolean on a User model. Do not update the database. Run the code against the database. Run a controller method that utilises the amended model. The expected behaviour is for an Internal Server 500 error to be returned. Instead a Gateway Timeout 504 error is returned. 

### Exceptions (if any)
Gateway Timeout 504 returned from controller back to web application, instead of an Internal Server 500 error.

### Further technical details
- ASP.NET Core 3.1 API
- EF 3.1.8
- SQL Server 2015
- Angular Web App
- VS4Mac you're running on, and it's version
- Azure dev, staging and prod environments

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Also, can you share more details about the scenario? Also, where the app is hosted?
