### ISSUE TITLE
Debugging Blazor Server apps with circuit issues needs to be easier.

### ISSUE THREAD

**Issue by anthcool** [dotnet/aspnetcore#26705]
Make it stupid simple to debug Blazor Server apps that throw circuit errors stating only to turn on detailed exceptions, but when done, don't give any better information after the fact.

_Originally posted by @anthcool in https://github.com/dotnet/aspnetcore/issue_comments/705685842_

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Also, what is the "more detailed information" that you expect to see and where exactly?

**Comment by anthcool** [comment]
@mkArtakMSFT
I personally don't have a project or know of how to get a reproducible project up that throws this exact error at the moment.  If I hit it again though, I'll take note and then try to reproduce and share here.

As for the detailed information, just better or more information on why the error occurred so it can be resolved.  It just seems next to impossible to resolve with just that error alone displayed to us.  I tend to backtrack if possible a bit of code or do some things with the code, and it eventually goes away, but have no idea what was causing the issue to keep it from happening again.

**Comment by pranavkm** [comment]
Thanks @anthcool. We have https://github.com/dotnet/aspnetcore/issues/24108 to track some work around improving the error experience in Blazor Server. 

> If I hit it again though, I'll take note and then try to reproduce and share here.

We'd be happy to get more feedback on what we could do to improve the experience. If you have concrete suggestions, that would be great.
