### ISSUE TITLE
Users lose sessions after restart kestrel service on Linux .NET Core 3.1

### ISSUE THREAD

**Issue by HashemGo** [dotnet/aspnetcore#26719]
### Describe the bug

our app need updates every day but when i upload updates i should restart kestrel service on Linux
Users logged Out and they should login again, that make them lost some work for them

i hope if is there any way to restart kestrel service without users logged out
### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
- The IDE VS

**Comment by Tratcher** [comment]
That's usually caused by the use of ephemeral encryption keys for the auth cookies. You should see a warning log about that when the app starts up. The fix is to save the encryption keys to disk.
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1#persistkeystofilesystem

**Comment by HashemGo** [comment]
> That's usually caused by the use of ephemeral encryption keys for the auth cookies. You should see a warning log about that when the app starts up. The fix is to save the encryption keys to disk.
> https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1#persistkeystofilesystem

Thank you so much, it's really helpful

this is my full Code for anyone need this

`        public IConfiguration Configuration { get; }
        public IWebHostEnvironment env { get; }
        public Startup(IConfiguration configuration, IWebHostEnvironment environment)
        {
            Configuration = configuration;
            env = environment;
            Fill = new FilterString();
        }`

`
    public void ConfigureServices(IServiceCollection services)
        {
            string path = "";
            if (env.IsDevelopment())
            {//Development
                path = Path.GetFullPath("wwwroot").Replace("\\wwwroot", "");
            }
            else
            {//Linux
                path = Path.GetFullPath("wwwroot").Replace("/wwwroot", "");
            }
            services.AddDataProtection()
.PersistKeysToFileSystem(new DirectoryInfo(path));
}
`
