### ISSUE TITLE
Change ViewCompiler to Public?

### ISSUE THREAD

**Issue by j4587698** [dotnet/aspnetcore#26723]
I want to add .views.dll at runtime.
But all ViewCompilerProvider like RuntimeViewCompilerProvider and DefaultViewCompilerProvider can't have a method like Modify()。
it will create a ViewCompiler at first use using the current PartManager.
If I modify PartManager at runtime,there will be no changes to the viewcompiler.
I want to rewrite ViewCompilerProvider but to many class is internal.I will rewrite RuntimeViewCompiler,CSharpCompiler,RazorReferenceManager etc.
If ViewCompiler is public, rewriting ViewCompilerProvider will be a simple matter.

**Comment by javiercn** [comment]
@j4587698 thanks for contacting us.

Can you clarify to us what you are trying to accomplish?

**Comment by j4587698** [comment]
```
            var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test", "RazorClassLibrary1.dll"));
            var assemblyView = AssemblyLoadContext.Default.LoadFromAssemblyPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test", "RazorClassLibrary1.Views.dll"));
            var viewAssemblyPart = new CompiledRazorAssemblyPart(assemblyView);
            
            var controllerAssemblyPart = new AssemblyPart(assembly);
            _partManager.ApplicationParts.Add(controllerAssemblyPart);
            _partManager.ApplicationParts.Add(viewAssemblyPart);
```
this code only running at Startup.

Now I can use 
```
    public class MyActionDescriptorChangeProvider : IActionDescriptorChangeProvider
    {
        public static MyActionDescriptorChangeProvider Instance { get; } = new MyActionDescriptorChangeProvider();

        public CancellationTokenSource TokenSource { get; private set; }

        public bool HasChanged { get; set; }

        public IChangeToken GetChangeToken()
        {
            TokenSource = new CancellationTokenSource();
            return new CancellationChangeToken(TokenSource.Token);
        }
    }
```
Startup.cs
```
            services.AddSingleton<IActionDescriptorChangeProvider>(MyActionDescriptorChangeProvider.Instance);
            services.AddSingleton(MyActionDescriptorChangeProvider.Instance);
```
Action:
```
            MyActionDescriptorChangeProvider.Instance.HasChanged = true;
            MyActionDescriptorChangeProvider.Instance.TokenSource.Cancel();
```
Effective controller,But views doesn't work。

**Comment by j4587698** [comment]
@javiercn 
I uploaded a sample project。https://github.com/j4587698/RCLTest
It can work, but if I also want to use RuntimeCompilation, I will rewrite CSharpCompiler, RazorReferenceManager, etc.
If RuntimeViewCompiler is public, I just need to rewrite RuntimeViewCompilerProvider .

**Comment by javiercn** [comment]
@j4587698 are you trying to add the views dynamically after startup or just during the startup phase?

**Comment by j4587698** [comment]
@javiercn 
after startup, In Action or dll is add

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do.

**Comment by j4587698** [comment]
@mkArtakMSFT why controller can modify at runtime, views can't?
