### ISSUE TITLE
IAsyncDisposable.DisposeAsync not called on Blazor component when tab is closed

### ISSUE THREAD

**Issue by cornem** [dotnet/aspnetcore#26737]
### Describe the bug
A Blazor page can implement `IAsyncDisposable`. When navigating between pages, `DisposeAsync` gets called. However, when a browser tab is closed, `DisposeAsync` does not appear to be called.

If I implement `IDisposable` instead, `Dispose` gets properly called both when navigating away from the page, and closing the browser tab.

### To Reproduce
- Create a new Blazor server app
- Add a page `Index.razor`
- Add a code-behind file `Index.razor.cs` with the following content:

```csharp
public partial class Index : IAsyncDisposable
{
    [Inject]
    private ILogger<Index> Logger { get; set; } = default!;

    protected override void OnInitialized()
    {
        Logger.LogInformation("Index page initialized.");
    }

    public async ValueTask DisposeAsync()
    {
        Logger.LogInformation("Index page disposed.");
    }
}
```

- Set a breakpoint inside `DisposeAsync`
- Run the app, and navigate to the Index page. Close the tab and notice how the breakpoint isn't hit.

### Further technical details
- ASP.NET Core version: 5.0.0 RC1
- Output of `dotnet --info`:

.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
The renderer needs to implement DisposeAsync
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/RenderTree/Renderer.cs#L759
