### ISSUE TITLE
AspNetCore.Mvc Controller base is not unable to resolve URL by segments correctly

### ISSUE THREAD

**Issue by d1mnewz** [dotnet/aspnetcore#26730]
### Describe the bug

Controller has the route attribute `[Route("api/dimko/)]` attached. Once creating the endpoint with `[Route("/must-not-be-nice")]`, it is not resolved under `/api/dimko/` but under root, such as `~/must-not-be-nice`.
![image](https://user-images.githubusercontent.com/11834902/95555878-1bb25980-0a1b-11eb-9d14-5a9bbc2e6526.png)

### To Reproduce

Please follow the link to repo - https://github.com/d1mnewz/ApiThingTest

### Further technical details
- ASP.NET Core 3.1.

**Comment by javiercn** [comment]
@d1mnewz tanks for contacting us.

This is by design, if you prefix the route with `~/` or `/` it signals MVC to not combine the route and interpret it verbatim. If you want the route to combine you only use "must-not-be-nice" at the action level.
