### ISSUE TITLE
Foreach is formatted wrong within an InputSelect component

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#26736]
### Describe the bug
I want to add options with a foreach loop to an InputSelect component within a razor component. However VS sets the curly braces on wrong positions. It works if I do the exactly same thing within an `<select>` element.

See:
![razor_foreach](https://user-images.githubusercontent.com/32510006/95581594-8bcfd800-0a39-11eb-8c1a-cb3834d67aff.gif)

### Further technical details
Version 16.8.0 Preview 3.2. It is a bit better with the new experimental razor editor but still not perfect. 

.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by NTaylorMullen** [comment]
@ajaybhargavb assigning to you to validate that the new LSP powered formatter treats this correctly.

**Comment by ajaybhargavb** [comment]
Investigated this. This is happening because the Razor design time C# code is generated like,
```
builder.AddAttribute("...", "...", () => {
foreach(...)
{
...
}
});
```
which results in extra indentation for foreach.

A possible fix here would be to modify the design time code generation to not put it inside lambdas.

**Comment by NTaylorMullen** [comment]
> A possible fix here would be to modify the design time code generation to not put it inside lambdas.

Hmm, actually shoot. not sure we can because that'd change how it functionally operates. Aka, variables declared inside of that lambda aren't accessible outside of it.

**Comment by ajaybhargavb** [comment]
Forgot to update here. Spoke to @pranavkm about this and yes, we can't simply remove the lambdas. Need to come up with something more involved. This isn't a simple fix anymore :(

**Comment by NTaylorMullen** [comment]
> This isn't a simple fix anymore :(

Is there a way we can "do nothing" in an effort to "do no harm"?

**Comment by ajaybhargavb** [comment]
I think that will take a similar amount of effort anyway. Detecting we're in such a scenario is the hard part. After that it wouldn't be too hard to even special case this and make it work.

**Comment by NTaylorMullen** [comment]
> I think that will take a similar amount of effort anyway. Detecting we're in such a scenario is the hard part. After that it wouldn't be too hard to even special case this and make it work.

Ah ok. Ya I think special casing isn't awful. That being said, if the compiler changes it'd break this which of course would be fortunate but I assume our DDRIT tests would pick up on it once we've expanded them a bit more.
