### ISSUE TITLE
AuthenticationScheme missing in NetCore 3.1

### ISSUE THREAD

**Issue by RiazAnwar** [dotnet/aspnetcore#26735]
For Authentication I am currently using services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)..
I am looking into using 3.1 but AuthenticationScheme shows error. How can I do it in 3.1?

Error	CS1061	'object' does not contain a definition for 'AuthenticationScheme' and no accessible extension method 'AuthenticationScheme' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?

**Comment by Tratcher** [comment]
You need to add a nuget dependency for JwtBearer:
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/3.1.8

**Comment by RiazAnwar** [comment]
I have already added this https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/3.1.8 but AuthenticationScheme shows error.

**Comment by RiazAnwar** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;

namespace CoreApiTesting
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
        public object JwtBearerDefaults { get; set; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("defaultcorspolicy",
                        builder =>
                        {
                            //builder.WithOrigins("*").AllowAnyHeader()
                            //            .AllowAnyMethod();
                            builder.AllowAnyOrigin().AllowAnyHeader()
                                            .AllowAnyMethod();
                        });
            });

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
             {
                 options.TokenValidationParameters = new TokenValidationParameters
                 {
                     ValidateIssuer = true,
                     ValidateAudience = true,
                     ValidateIssuerSigningKey = true,
                     ValidIssuer = "http://mysite.com", //some string, normally web url,
                      ValidAudience = "http://mysite.com",
                     IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("my_secret_key_12345"))
                 };

                 options.Events = new JwtBearerEvents
                 {
                     OnAuthenticationFailed = context =>
                     {
                         if (context.Exception.GetType() == typeof(SecurityTokenExpiredException))
                         {
                             context.Response.Headers.Add("Token-Expired", "true");
                         }
                         return Task.CompletedTask;
                     }
                 };
             });

            services.AddControllers();

        }


        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseCors("defaultcorspolicy");

            app.UseAuthentication();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}

**Comment by RiazAnwar** [comment]
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)  This show error...

**Comment by Tratcher** [comment]
Oh, remove the line `public object JwtBearerDefaults { get; set; }`, it's causing a compiler error because the local property is preferred over the class.

**Comment by RiazAnwar** [comment]
Oh ThankYou So much ...it works for me
