### ISSUE TITLE
Possibility to disable error_description in http response

### ISSUE THREAD

**Issue by RikiRC** [dotnet/aspnetcore#26745]
Hi, I have a question if there is a possiblity to add feature that will allow to disable error_description in http response from https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L236 ? Because as RFC6750 (https://tools.ietf.org/html/rfc6750#section-3) says:

"If the protected resource request included an access token and failed authentication, the resource server SHOULD include the "error" attribute to provide the client with the reason why the access request was declined. The parameter value is described in Section 3.1. **In addition, the resource server MAY include the "error_description" attribute to provide developers a human-readable explanation that is not meant to be displayed to end-users.** It also MAY include the "error_uri" attribute with an absolute URI identifying a human-readable web page explaining the error.  The "error", "error_description", and "error_uri" attributes MUST NOT appear more than once."

Actually in http response I am receiving one of the following error descriptions, that I don't want to be shown to end-users in http response:
WWW-Authenticate: Bearer error="invalid_token", **error_description="The signature is invalid"**
WWW-Authenticate: Bearer error="invalid_token", **error_description="The token expired at 'xx/xx/xxxx xx:xx:xx'"**

And as we know it is good practice to show as little as possible in production environments.

**Comment by Pilchie** [comment]
@blowdart ?

**Comment by blowdart** [comment]
In theory your oauth client should be branching on these and reacting accordingly (refreshing, going though login again etc.), and not displaying them to end users. End users sending bearer tokens without some sort of aware client is an odd scenario to me.

I guess we could have a flag that could be enabled to not send the extra details, but probably not by default, as it may break existing clients. We'd even take a PR for it.

@Tratcher for a second opinion.

**Comment by Tratcher** [comment]
> In theory your oauth client should be branching on these and reacting accordingly (refreshing, going though login again etc.), and not displaying them to end users. End users sending bearer tokens without some sort of aware client is an odd scenario to me.

These weren't added for programmatic users but for tech support and debugging. It's saved a lot of tech support hours having the error readily available in the request trace.

> And as we know it is good practice to show as little as possible in production environments.

Yes, it's good to avoid leaking internal information, but in this case errors are intentionally very limited and shouldn't be exposing anything that's not already available to the client by examining the JWT themselves.

It's already possible to customize this header and disable these fields using the Events.Challenge API. I don't see a need to add an additional option.
https://github.com/dotnet/aspnetcore/blob/be472db60f4711404ba5de268f7b9d4a887926f8/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L218-L231
https://github.com/dotnet/aspnetcore/blob/be472db60f4711404ba5de268f7b9d4a887926f8/src/Security/Authentication/JwtBearer/src/JwtBearerEvents.cs#L59-L62
https://github.com/dotnet/aspnetcore/blob/be472db60f4711404ba5de268f7b9d4a887926f8/src/Security/Authentication/JwtBearer/src/JwtBearerChallengeContext.cs#L35-L58

**Comment by blowdart** [comment]
OK, as it's already possible, if painful, this doesn't seem to need a specific open. Closing.
