### ISSUE TITLE
Semantic tokens for C# parameters and other identifiers overridden by TextMate

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26753]
In the following code `thing` will be green because of the TextMate Grammar.
```razor
@code{
    // {
    // }
    public void Thing(string thing)
    {
    }
}
```

Current:
![image](https://user-images.githubusercontent.com/14987221/95628374-c5e9ab80-0a32-11eb-913e-aba146eded30.png)
 This also happens inside a Component which takes a C# response:
![image](https://user-images.githubusercontent.com/14987221/95628417-d863e500-0a32-11eb-8b60-2c4fd251c4a8.png)

There are two problems here:
1. For the `// {` part our TextMate grammar got off track and decided that the comment never ended, so it's trying to set the comment scope to everything.
1. Semantic Tokens are being overridden by TextMate scopes in some cases. The specific case here is that the `Identifier` classification is taking priority over everything else. This is a problem on the VSLanguageServerClient side that @gundermanc is looking into. The solution would probably be that Semantic Tokens always "win".

**Comment by gundermanc** [comment]
To add some detail for point 2:
- We're encountering previously 'by-design' behavior in the core of the Visual Studio Editor: when there are overlapping classifications, editor merges them at the classification level of granularity, by ordering the ClassificationFormatDefinitions topologically by their `[Order]` attributes, and then giving preference to the first/last, I don't remember which. I've pasted an example below. You could fix this by ordering your classifications relative to the core editor's comment classification, as defined by [PredefinedClassificationTypeNames.Comment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.standardclassification.predefinedclassificationtypenames.comment?view=visualstudiosdk-2019)

```csharp
        [Export(typeof(EditorFormatDefinition))]
        [UserVisible(true)]
        [ClassificationType(ClassificationTypeNames = CssClassificationTypeName.CssComment)]
        [Name(CssClassificationTypeName.CssComment)]
        [Order(After = "HTML Priority Workaround", Before = LanguagePriority.FormalLanguage)]
        internal sealed class CommentClassificationFormat : ClassificationFormatDefinition
        {
            internal CommentClassificationFormat()
            {
                ForegroundColor = Colors.DarkGreen;
                DisplayName = Resources.DisplayName_CSS_Comment;
            }
        }
```
- There's a [pending experience](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1165251) for making this entire scenario more extensible. I don't have an ETA for this at the moment. The specific feature request here, to enable wholesale prioritization of colors based on the tagger they came from (TextMate, local tagger, or LSP semantic tokens tagger), is being tracked [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1184616). I am planning on costing this Monday, but given that this requires fundamental changes to the Editor design, it may be too expensive to tackle before we get to the rest of the experience, probably post 16.9.

**Comment by ryanbrandenburg** [comment]
Here's another case we should check when we fix this:
![image](https://user-images.githubusercontent.com/14987221/103803822-f7f4b480-5005-11eb-84b7-e00ccac5076c.png)

**Comment by NTaylorMullen** [comment]
A similar VSTS issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1260231
