### ISSUE TITLE
Refresh / Rebuild .net core Razor Class Library View markup on save

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/594585/refresh-net-core-mvc-view-markup-on-save-from-all.html)._

---
<p>For example. I have my primary .net core mvc project. And I have a Razor Class Library where all of my Identity stuff is stored. My RCL uses Area &gt; Identity &gt; Views &gt; Login.cshtml and has the routes registered appropriately. <br><br>From my experience, it seems any changes to the login.cshtml markup requires a full stop / re start of the debugging session / refresh browser to view the changes within the browser. It would be nice to do whatever rebuild / updates it would require behind the scenes on save to just click save after editing the markup and refresh the browser and the updates would be visible without having to restart the debugging session.</p>

---
#### Jane Wu [MSFT] on 6/5/2019, 02:18 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by troyji** [comment]
Have you enabled runtime compilation and added a file provider for your RCL?

```cs
public void ConfigureServices(IServiceCollection services)
{
    ...

    services.Configure<MvcRazorRuntimeCompilationOptions>(options =>
    {
        var libraryPath = Path.GetFullPath(
            Path.Combine(HostEnvironment.ContentRootPath, "..", "MyClassLib"));
        options.FileProviders.Add(new PhysicalFileProvider(libraryPath));
    });
}
```
Documentation: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?#enable-runtime-compilation-for-a-razor-class-library

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/30245. The overall work around hot reload should address this.
