### ISSUE TITLE
Blazor InputFile - Maximum number of files selection for upload

### ISSUE THREAD

**Issue by arvindram11** [dotnet/aspnetcore#26756]
### Is your feature request related to a problem? Please describe.
Is there a way to restrict the number of files that the user can select (when multiple is set for an InputFile component)? I understand that there is a way to process only "X" number of files when using the eventArgs.GetMultipleFiles, but when the user selects a large number of files (I tried about 300), the connection is lost on the browser to the server (it displays attempting to reconnect but then throws an exception).

Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.

I am trying with the Blazor Server (not Web Assembly) because we have dependencies on other .net libraries (third party) that don't appear to work well with WASM (get encoding errors when trying to use those in WASM).

### Describe the solution you'd like
A way to let the user know that too many files were selected in 1 attempt and let them recover and add more files (if needed).  For ex. if I am selecting 300 files (each file about 2000Kb), then exception is displayed in the console, but all a normal user would see is the "Attempting to reconnect to server message".  If there is a way to either intercept in Blazor code or in a try/catch exception when the number of files exceed what SignalR can handle, that would be mighty helpful.

### Additional context
Using .net core 5.0 RC1
VS 2019 16.8.0 Preview 3.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The current API exposes the number of files uploaded already. It's up to the developer to add the validation logic. At this point we have no plans to make it part of the framework.

**Comment by arvindram11** [comment]
I am not sure what you meant by the API exposes the number of files uploaded.  In the file selection dialog, there is nothing restricting the user (if "multiple" directive is set) from picking say 500 files (each about 1 MB each as an example).  When this happens (and when the user clicks the "Open" button in the file open dialog), the session disconnects and the page is reloaded (and anything that the user has done prior to that is lost).

![image](https://user-images.githubusercontent.com/33095601/95777308-ed8b7e80-0c93-11eb-985f-97e1d1e7ffcd.png)
