### ISSUE TITLE
get full url address in aps mvc core

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26759]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/839652/get-full-url-address-in-aps-mvc-core.html)._

---
I think it will help web developer a lot if they could simply find out an action full url address, for example:

We have a controller named 'ProductController' and an action named 'Find', and a parameter named 'int id', and method type is 'GET'

if Visual Studio could give me simply '/Product/Find?id', it would be very helpfull.

Maybe by right clicking on action and a context menu 'Copy Link>' which have a list of "Routing" in startup, and user select one routing pattern, and the visual studio generate relative link.

I'm usually use these urls for ajax requests, which doesn't have a view to right click and select 'View in Browser', to get the final url.
Thanks alot, Monjezi, H.

---
#### Feedback Bot on 12/3/2019, 02:10 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This ask is not aligned with our vision and we have no plans to implement this ask. Of course, you're always welcome to fork this codebase and build off of it!

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
