### ISSUE TITLE
Blazor WebAssembly login is redirecting to localhost instead of public URL

### ISSUE THREAD

**Issue by jonasarcangel** [dotnet/aspnetcore#26757]
When trying to sign-in, it is redirecting to http://localhost:5008/connect/authorize instead of the public URL.

Test site: http://167.172.118.170/authentication/login

Identity Server configuration:
```
            services.AddIdentityServer(options =>
            {
                options.IssuerUri = "https://167.172.118.170/";

            })
                .AddApiAuthorization<ApplicationUser,
                ApplicationIdentityDbContext>(); 

```
Repository: https://github.com/jonasarcangel/BlazorLoginNetworkErrorIssue/blob/master/src/MyProject.Data.Identity/Extensions.cs

Host is configured as follows in Startup.cs:

```
            app.Use(async (ctx, next) =>
            {
                ctx.Request.Scheme = "http";
                ctx.Request.Host = new HostString("167.172.118.170");
                await next();
            });

```
Repository:
https://github.com/jonasarcangel/BlazorLoginNetworkErrorIssue/blob/master/src/MyProject.Web.Server/Startup.cs

Authentication.razor does not provide any option on how to provide server URL.

Repository:
https://github.com/jonasarcangel/BlazorLoginNetworkErrorIssue/blob/master/src/MyProject.Web.Client.Shell/Pages/Authentication.razor

**Comment by jonasarcangel** [comment]
The following returns a mix of URL's. http://167.172.118.170/.well-known/openid-configuration

**Comment by jasebanico** [comment]
I have found the solution. I need to set it as:

app.Use((ctx, next) => 
{
    ctx.SetIdentityServerOrigin("http://167.172.118.170");
    return next();
});
