### ISSUE TITLE
dotnet watch crashes when ignored file is deleted

### ISSUE THREAD

**Issue by JeroenBos** [dotnet/aspnetcore#26768]
My set-up: an ASP.NET Core project, in which there's a directory with a JS project.
I have a file `/home/<my_project_dir>/my_project.csproj`, which contains:
```
 <ItemGroup>
    <Watch Exclude="**/node_modules/**" />
  </ItemGroup>
```   

When I execute the command `cd /home/<my_project_dir> && dotnet watch build` building and watch works. But when I do webpack on my JS project in `/home/<my_project_dir/js` the dotnet watcher exists with this error:

```
watch : The file watcher observing '/home/<my_project_dir>/' encountered an error: Could not find file '/home/<my_project_dir>/js/node_modules/.postcss-load-config.MODULES'.
```

which is weird for two reasons:

- the watcher should not crash when a file is deleted
- the file should have been ignored in the first placed.

Two more facts:
- running the webpack command _consistently_ crashes the dotnet watcher.
- I can't reproduce manually by simply creating the same file in the same directory and deleting it

Further information:
- dotnet 3.1.401
- Unbuntu 18.04
- (happy to oblige with anything else)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
