### ISSUE TITLE
Html.DisplayFor needs an additional overload

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26762]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1067986/htmldisplayfor-needs-an-additional-overload.html)._

---
`Html.DisplayFor()` is commonly used like this:

```cs
@Html.DisplayFor(m => m.Property)
```

But it is also used like this:

```cs
@foreach (var item in Model.Items)
{
    <tr>
        <td>@Html.DisplayFor(m => item. Name)</td>
        <td>@Html.DisplayFor(m => item. Description)</td>
    </tr>
}
```

The two calls to `Html.DisplayFor()` within the loop seem silly to me. Shouldn't there be an overload of `Html.DisplayFor()` that doesn't require the model property identifier for cases like this where the item being displayed is not a property of the model?

Is this possible? Is there a reason why `IHtmlHelper` always requires a model type? Could it be circumvented for this case?

---
#### Feedback Bot on 6/8/2020, 03:09 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This ask is not aligned with our vision and we have no plans to implement this ask. Of course, you're always welcome to fork this codebase and build off of it!

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
