### ISSUE TITLE
Debug and continue in asp.net with code changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26760]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/517323/debug-and-continue-in-aspnet.html)._

---
<p>One of the best things Microsoft has done is to have debug and continue in desktop and console. But ASP.net web application still does not have it up to that scale which is making our life difficult as it needs a whole application to restart if changes made in global resources or app code. Why changes are not allowed and if there is a dependency, you have everything from OS, Web server to SDK, make required changes friends.</p><p>Its time killing and make our life difficult to make software faster. I am sure it's difficult for some reason at your end otherwise this would have given. Please do something as web development will be as same as the desktop with this amazing tool on this universe. I was happy once as web application allowd to do so but we run our application from IIS as we can't depend of any port as our URL are fixed to read souce CSS, JS etc.</p><p>I have been using .net from more than 10 years and I still love working with new SDK you have as I see Microsoft as the best software product based company which keep improving its product features and that what makes a trade the leader in the true mean. Please do think about it and have it in the upcoming days.</p><p>Thanks</p><p>Ranjit Kumar Singh</p><p>Project Lead (Microsoft Tech Wing, CSM Technology)</p>

---
#### Blair Wang [MSFT] on 4/3/2019, 11:28 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We plan to address this as part of #18486
