### ISSUE TITLE
i want a feature to obtain the visitor's IP adress from blazor components.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26763]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1135615/i-want-a-feature-to-obtain-the-visitors-ip-adress.html)._

---
i want a feature to obtain the visitor's IP adress from blazor components.

the current workarounds are insanely unclean and messy, and ruin the design of my projects.

---
#### Feedback Bot on 8/4/2020, 10:46 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by mkArtakMSFT** [comment]
Moving to StackOverflow as this is not something we plan to provide as part of Blazor.
