### ISSUE TITLE
Find mutually exclusive asp.net core helper tags in editor / compile time

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26761]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/827782/find-mutually-exclusive-aspnet-core-helper-tags-in.html)._

---
For example, if you give a button a `asp-page-handler` tag and a `asp-action` tag Visual Studio will not highlight it or give any error when you compile your project, but you will get an exception when the page is rendered:

>InvalidOperationException: Cannot determine the 'formaction' attribute for <button>. The following attributes are mutually exclusive:
>asp-route
>asp-controller, asp-action
>asp-page, asp-page-handler

It would be good if visual studio could report these errors during development.

---
#### Feedback Bot on 11/20/2019, 11:36 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This ask is not aligned with our vision and we have no plans to implement this ask. Of course, you're always welcome to fork this codebase and build off of it!

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
