### ISSUE TITLE
[master] Get IndividualAuth template tests working on Helix

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#26776]
Tests may be failing on Helix because they do not have the TemplateTests.props overrides in their environment. Binary logs clearly show the published projects are building using the SDKs default, 5.0.0 version of Microsoft.AspNetCore.App and not the just-built version e.g. &hellip;\e\sdk294\x64\packs\Microsoft.AspNetCore.App.Ref\\**5.0.0-rc.2.20466.8**\ref\net5.0\Microsoft.AspNetCore.Http.Abstractions.dll. Not sure why the problem is specific to IndividualAuth tests.

Error:
``` text
...\e\Templates\BaseFolder\AspNet.jvkjhfr1m0h\Startup.cs(45,17): error CS1705: Assembly 'Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore' with identity 'Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Http.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Http.Abstractions' with identity 'Microsoft.AspNetCore.Http.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [...\e\Templates\BaseFolder\AspNet.jvkjhfr1m0h\AspNet.jvkjhfr1m0h.csproj]
```

Specific tests skipped in #24983:
- `Templates.Test.IdentityUIPackageTest.IdentityUIPackage_WorksWithDifferentOptions()`
- `Templates.Test.MvcTemplateTest.MvcTemplate_IndividualAuth(useLocalDB: False)`
- `Templates.Test.MvcTemplateTest.MvcTemplate_IndividualAuth(useLocalDB: True)`
- `Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth(useLocalDB: False)`
- `Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth(useLocalDB: True)`

Details are available in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-24983-merge-b23d059ca16f4f5fb9/ProjectTemplates.Tests--net5.0/AspNet.di2py1qzril.binlog for example. See build https://dev.azure.com/dnceng/public/_build/results?buildId=836250 for other examples.

When restoring these tests after fixing them, note all previously had `[SkipOnHelix("cert failure", Queues = "All.OSX")]` applied.

**Comment by HaoK** [comment]
Probably specific to Individual auth due to the fact that they depend on EF

**Comment by dougbu** [comment]
Maybe @HaoK but I suspect the difference is really about depending on something _not_ in the shared framework but built in the dotnet/aspnetcore repo. That is, the real problem is **all** of the template tests run against the Microsoft.AspNetCore.App assemblies included in the SDK rather than what we just built.

The problem will very likely be hidden automatically once the SDK includes dotnet/aspnetcore assemblies with 6.0.0.0 assembly versions. But, it's a real problem after that point nonetheless. Means we're only testing the templates completely in the project template tests that run on build agents.

**Comment by HaoK** [comment]
@dougbu looks like your changes, or something else has resolved the issue with these tests, is there any follow up work that needs to be done here other than reenabling the tests, or did you take care of that in the dependency update PR?

**Comment by dougbu** [comment]
@HaoK my changes in #26788 likely fixed things. They certainly made so that template test projects now build and run against the just-built Microsoft.AspNetCore.App.* assemblies. But, no, I didn't reenable the tests in that PR.

Suggest updating the title and description of #26823 and making it non-Draft.
