### ISSUE TITLE
TempData entry is not deleted when redirecting

### ISSUE THREAD

**Issue by nphmuller** [dotnet/aspnetcore#26798]
### Describe the bug
An entry in TempData is normally deleted after it's been read. When using the default TempData provider (which uses cookies) the entry is not deleted after it's been read when returning a redirect ActionResult (like `RedirectToPage()`).

### To Reproduce
- `git clone https://github.com/nphmuller/tempdata-cookie-redirect.git && cd tempdata-cookie-redirect`
- `dotnet restore && dotnet run`
- Click on Privacy. A random message is now shown in the nav bar (which is saved and read via TempData).
- On the Privacy Page click on `Read tempdata and redirect to index`.

Expected result: User is redirected to Index page and the random message is __not__ shown.
Actual result: User is redirected to Index page and the random message is still shown.

### More info
This is the code that's responsible for setting and reading the TempData value (in `Privacy.cshtml.cs`):
``` c#
public void OnGet()
{
    TempData["tempdata-redirect-test"] = "hi " + new Random().Next();
}

public IActionResult OnPost()
{
    var _ = TempData["tempdata-redirect-test"];
    return RedirectToPage("/Index");
}
```

Initially I expected it to be a browser quirk (the browser simply ignoring the `set-cookie` header during a redirect). However, after copying the `set-cookie` value and setting the cookie manually I discovered that the old (not cleared) TempData value was still set in the cookie value.

### Further technical details
> ASP.NET Core 3.1.8
> dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by nphmuller** [comment]
As a workaround I called `TempData.Save()` in `OnPost`:
``` c#
public IActionResult OnPost()
{
	var _ = TempData["tempdata-redirect-test"];
	TempData.Save(); // added
	return RedirectToPage("/Index");
}

```

**Comment by kacomsrd** [comment]
I just observed this behavior too. 
It may be **minor**, but since browsers don't delete session cookies anymore (when they are set to *continue where you left off*), this data may be around for a **very long time**, adding unnecessary baggage to every request.

**Comment by michalsznajder** [comment]
I think I have it the same. And it breaks logic of one time alerts for me. I store error message in TempData when doing PRG pattern.

**Comment by Fardin7** [comment]
I think Tempdata is big trouble in asp.net Core , for me it just keep only one key, and then when I used the keep() and peak() method  it keeps nothing between 2 requests

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
