### ISSUE TITLE
[Blazor] Parallel API calls seem to run sequentially in Chrome

### ISSUE THREAD

**Issue by vyacheslav-mikhaylov** [dotnet/aspnetcore#26795]
### Describe the bug
Parallel API calls runs sequentially in Google Chrome in WebAssembly if **DevTools are closed**.

### To Reproduce
Run multiple parallel tasks in WebAssembly calling, for instance, an API. 
Introduce artificial delay on API side to ensure requests are running in parallel.
Combine calls into list of tasks and do await Task.WhenAll(listOfRequests).
Measure total execution time and see it equals to ServerSideDelay*NumberOfRequest in Chrome.

Run the same code with Developer Tools Opened in Chrome - works significantly faster, and it is visible in the network tab that requests are running in parallel.
Run the same code in Safari - works significantly faster.

### Further technical details
- ASP.NET Core 3.1
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

- Rider 2020.2.4
- Chrome 85.0.4183.121
- Safari 15610.1.28.1.9

**Comment by mrpmorris** [comment]
Could you post repro code? I suspect the issue might be in your code

**Comment by vyacheslav-mikhaylov** [comment]
```
    private async Task IncrementCount()
    {
        currentCount++;
        var sw = Stopwatch.StartNew();
        var tasks = Enumerable.Range(0, 10).Select(x => Http.GetFromJsonAsync<HelloResponse>("hello")).ToList();
        await Task.WhenAll(tasks);
        sw.Stop();
        queryTime = sw.ElapsedMilliseconds.ToString();
    }
```

**Comment by mrpmorris** [comment]
That's how Task.WhenAll works. You are waiting for them all to complete, that doesn't mean 2 haven't completed 2 seconds before.

This will illustrate:


```
var sw = Stopwatch.StartNew();
var tasks = Enumerable.Range(1, 10).Select(async x => {
	await Task.Delay(x * 250);
	Console.WriteLine($"Completed {x} after {sw.ElapsedMilliseconds} ms");
}).ToArray();
await Task.WhenAll(tasks);
sw.Stop();
Console.WriteLine($"Total time {sw.ElapsedMilliseconds} ms");
```

Output:

```
Completed 1 after 319 ms
Completed 2 after 557 ms
Completed 3 after 804 ms
Completed 4 after 1058 ms
Completed 5 after 1311 ms
Completed 6 after 1571 ms
Completed 7 after 1809 ms
Completed 8 after 2063 ms
Completed 9 after 2311 ms
Completed 10 after 2557 ms
Total time 2558 ms
```

**Comment by vyacheslav-mikhaylov** [comment]
How does Task.WhenAll work? lol. Seriously? 
What's the point to make extra async/await wrapping if you await array of tasks anyway? Just to do a console output on completion? That's not the problem.

My task is to run all the requests in parallel, not sequentially. If you would put my code in the sample Blazor WebAssembly you would have noticed different behaviour according to the reproduction steps specified above.

**Comment by mrpmorris** [comment]
"lol. Seriously?" - Are you asking me, or being rude?

If your tasks actually do some async work (like awaiting an Http response) then they will execute in the background. If your code is just synchronous code wrapped in a Task because you think it will give you multiple threads then that is not the case.

**Comment by vyacheslav-mikhaylov** [comment]
Could you please check my code? Do you see synchronous code inside lambda? Looks like you trying to teach me async programming without reading the code provided. Let's focus on the bug reported.

**Comment by mrpmorris** [comment]
I tried it with a server call too. Works exactly as expected, running in parallel.

The problem with your code is that it is incomplete. You don't show your server code, you don't show the output generated, and you don't show what you think the output should be. I therefore have no other option than to write the sample app myself and test it, at which point I see that it is not doing what you claim it is doing.

May I suggest you post a full repro? Also, may I suggest when someone is trying to help you that you are not rude to them? Your childish mockery is against the ettiquette guide for posting issues/comments on this repository.

Thank you.

**Comment by vyacheslav-mikhaylov** [comment]
I will make a repository with reproduction code and post here.

Also, may I suggest you to be careful trying to suspect or teach others before figuring out their experience level? Ones could have 20+ years of development expertise.

**Comment by mrpmorris** [comment]
I too have 20+ years of development expertise. I do not assume that I know anything, nor do I assume that anyone else does. There is always something we don't know. I don't feel one should ever be offended by someone telling them something they might already know.

The fact is, your report was inadequate - incomplete steps, missing output, no expected output specified. I tried to help you but for some reason you find information offensive. I'm going to unsubscribe from notifications for this ticket now and you'll have to wait for someone else to help you. Which is a shame, because considering the fact that I have it working perfectly fine there is a good chance I'd have spotted what the mistake is that you've probably made.

**Comment by vyacheslav-mikhaylov** [comment]
Listen, don't you think that "I suspect the issue might be in your code" (the thing you started with) might be treated offensive especially if you provide recommendations with zero relation to the subject? I expect something line "Sorry, there is no problem with your code, my suspicious were wrong, could you please share repro project because I can't reproduce it with information provided"

**Comment by mrpmorris** [comment]
To be clear. I said I suspect the error is in your code because I created a test and observed that async tasks are being executed in parallel in Chrome - not because I have any reason whatsoever to think you are a rubbish coder.

Without seeing the actual code (which wasn't provided) my suspicion was that the problem is in your code. I'm sorry you took my words as an insult - I don't know you so have no basis on which to judge your programming abilities (not that I see even the most basic errors as a problem experts don't experience).

**Comment by vyacheslav-mikhaylov** [comment]
https://github.com/vyacheslav-mikhaylov/BlazorTasksBugRepro

**Comment by mrpmorris** [comment]
This isn't a problem with task parallelism in Blazor, it is a limitation in Chrome.

Chrome will only let a single request exist for the same URL at a time, so if you make 50 requests for /hello it will only make one request at a time. If however you request /hello?id={x} then it will request them all immediately.

You can prove this restriction also exists in JavaScript like so...

 1. Add the following to your `Counter.razor` file, and add a button that executes it.

```
	private async Task DoJS()
	{
		queryTime = "calculating";

		var sw = Stopwatch.StartNew();
		await JSRuntime.InvokeVoidAsync("doRequests", 30);
		sw.Stop();

		queryTime = sw.ElapsedMilliseconds.ToString();
	}

```

 2. Add this script file to your blazor project and reference it from index.html

```
window.doRequests = function (count) {
	for (var i = 0; i < count; i++) {
		let current = i;
		fetch("https://localhost:6001/hello?i=" + i).then(response => {
			return response.json();
		}).then(hello => {
			console.log("Finished " + current + " " + hello)
		});
	}
};
```

**Comment by vyacheslav-mikhaylov** [comment]
Thank you. It is helpful.

**Comment by mrpmorris** [comment]
@vyacheslav-mikhaylov Should this be closed now as it is not Blazor related?

**Comment by vyacheslav-mikhaylov** [comment]
> @vyacheslav-mikhaylov You are welcome. Should this be closed now as it is not Blazor related?

Sure, let's close it. Thanks again.

**Comment by mrpmorris** [comment]
Thanks for posting the C# solution. Perhaps you could post this as a question on StackOverflow with an answer too? I'm sure others will spot this at some point.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out here, @mrpmorris!
