### ISSUE TITLE
[5.0 RC1] Syntax error in blazor.webassembly.js in Edge 

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/aspnetcore#26799]
Create a new Blazor WASM application and try to run it in "old" MS Edge browser. Application will not start. In browser console you will see:
SCRIPT1002: Syntax error  blazor.webassembly.js (1,1723)

Tested in fully updated Windows 10 1909 with "old" Edge browser
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

I have seen the same problem in fully updated Windows 10 2004.

Maybe it is related to https://github.com/dotnet/aspnetcore/issues/26219

**Comment by mrpmorris** [comment]
See https://github.com/dotnet/aspnetcore/issues/26475#issuecomment-706247372

**Comment by Andrzej-W** [comment]
Thank you @mrpmorris for the link. Hopefully Microsoft will force Edge update on relatively new Windows versions like 1903, 1909 and 2004. I don't know why, but I still have an old Edge version. On two computers I have made updates manually but on the third one I still have Edge version 18.
