### ISSUE TITLE
Unable to change result of ValidateAntiforgeryTokenAuthorizationFilter

### ISSUE THREAD

**Issue by ondmal** [dotnet/aspnetcore#26808]
I am trying to unify the error results of my Web API methods. I want to have single field (called problemId) in every response of not succesfully processed request. See this page (https://medium.com/@matteocontrini/consistent-error-responses-in-asp-net-core-web-apis-bb70b435d1f8) for explanation, what I am trying to do.

The only use case I am not able to resolve is when there is no valid antiforgery token in the request (I am using standard AutoValidateAntiforgeryTokenAttribute). The generated tresult looks like this:

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "Bad Request",
  "status": 400,
  "traceId": "00-ae1e0bf702a715478b2cc897330ef47b-1878e9f914555249-00"
}

and I need it would look like this:

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "Bad Request",
  "status": 400,
  "traceId": "00-ae1e0bf702a715478b2cc897330ef47b-1878e9f914555249-00"
  "problemId":"123345566"
}

I am not able to use "UseStatusCodePagesWithReExecute" (like in case of AuthorizationAttribute) because the response body content is not empty. Maybe custom ProblemDetailsFactory could help me (I did not try) but the DefaultProblemDetailsFactory is internal and sealed and I really do not like the idea to copy whole class internal code to my codebase and make just minor change.

Maybe the right solution is to generate empty response body so StatusCodePages can be used or make some public extensible ProblemDetailsFactory .

Thanks for any help.

**Comment by ondmal** [comment]
Finally a I found solution using IAlwaysRunResultFilter:

```
    public class ActionResponseProblemIdEnricherFilter : IAlwaysRunResultFilter, IOrderedFilter
    {
        private readonly IProblemIdAccessor _problemIdAccessor;

        public ActionResponseProblemIdEnricherFilter(IProblemIdAccessor problemIdAccessor)
        {
            _problemIdAccessor = problemIdAccessor;
        }

        /// <inheritdoc />
        public void OnResultExecuting(ResultExecutingContext context)
        {
            if (context.Result is ObjectResult objectResult && objectResult.Value is ProblemDetails problemDetails)
            {
                problemDetails.Extensions.TryAdd("problemId", _problemIdAccessor.GetProblemId());
            }
        }

        /// <inheritdoc />
        public void OnResultExecuted(ResultExecutedContext context)
        {
        }

        public int Order => -10001; // Must run before ClientErrorResultFilter
    }

```

Anyway, I still have one question. Even both Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter and Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter implement IAsyncAuthorizationFilter,  it looks like they behave different to IAlwaysRunResultFilter.

In case of  ValidateAntiforgeryTokenAuthorizationFilter the IAlwaysRunResultFilter is called and I am able to change the result.
In case of AuthorizeFilter (AuthorizeAttribute) the  IAlwaysRunResultFilter is NOT called so I am not able to change the result (even if I set Order to int.MinValue).

So it looks like the IAlwaysRunResultFilter is NOT ALWAYS run :)  Is here anybody who can explain me whether such behavior is by design?

**Comment by pranavkm** [comment]
Hi @ondmal, in 3.0 or newer applications, with endpoint routing, authorization applied using `AuthorizeAttribute` is handled by `AuthorizationMiddleware`. This middleware executes before MVC and short-circuits the request on a failed auth. 5.0 adds a way to customize the handling of the response from this middleware, you could use that to configure the response: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/customizingauthorizationmiddlewareresponse?view=aspnetcore-5.0 if you'd like.
