### ISSUE TITLE
MessagePack min version update for Microsoft.AspNetCore.SignalR.StackExchangeRedis before .NET 5.0

### ISSUE THREAD

**Issue by jasonycw** [dotnet/aspnetcore#26801]
### Is your feature request related to a problem? Please describe.
Currently we are using .NET Core 3.1 for all our production projects and sometimes I see the following error
```
System.TypeLoadException: Could not load type 'MessagePack.MessagePackBinary' from assembly 'MessagePack, Version=2.2.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be'.
at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Internal.RedisProtocol.WriteInvocation(String methodName, Object[] args, IReadOnlyList`1 excludedConnectionIds)
```
I think the problem is that the `Microsoft.AspNetCore.SignalR.StackExchangeRedis` v3.1.8 is not totally compatible with `MessagePack` v2+ according to https://github.com/dotnet/aspnetcore/issues/18074
On the branch for .NET 5, there are already new `MessagePack` changes which should fix the problem.

However, according to https://github.com/aspnet/Announcements/issues/405
`MessagePack` below v1.8.x has some security issue which was fixed in v1.9.3 and that's the reason why we explicitly referenced the latest `MessagePack` 8 months ago.
Without explicit reference, `Microsoft.AspNetCore.SignalR.StackExchangeRedis` v3.1.8 just take `MessagePack` >=1.7.3.7 which has the security issue.

### Describe the solution you'd like
Update the `Microsoft.AspNetCore.SignalR.StackExchangeRedis` to take `MessagePack` >=1.9.3 in v3.1.8.1 or v3.1.9 before .NET 5 package update
Or even better, include support for v2.+ directly before .NET 5

### Additional context
Current implementation in [`v3.1.8`](https://github.com/dotnet/aspnetcore/blob/v3.1.8/src/SignalR/server/StackExchangeRedis/src/Internal/RedisProtocol.cs#L39-L71)
https://github.com/dotnet/aspnetcore/blob/c75b3f7a2fb9fe21fd96c93c070fdfa88a2fbe97/src/SignalR/server/StackExchangeRedis/src/Internal/RedisProtocol.cs#L39-L71
Implementation in [`master`](https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/server/StackExchangeRedis/src/Internal/RedisProtocol.cs#L40-L75)
https://github.com/dotnet/aspnetcore/blob/ab973d23fb5fc3b00d37ba63182b5bb14dc02803/src/SignalR/server/StackExchangeRedis/src/Internal/RedisProtocol.cs#L40-L75

**Comment by BrennanConroy** [comment]
The announcement explicitly calls out that you need to add the MessagePack dependency yourself:
```diff
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="3.1.0" />
+   <PackageReference Include="MessagePack" Version="1.9.3" />
  </ItemGroup>
</Project>
```
It also says that MessagePack 2.X is not compatible, so don't use any of those versions.

**Comment by jasonycw** [comment]
Yes, but I am wondering why don't explicitly make the current `Microsoft.AspNetCore.SignalR.StackExchangeRedis` to a `MessagePack` min version of 1.9.3.

Why set it up to >=1.7.3.7 when it's know to have security issue?
