### ISSUE TITLE
Microsoft.AspnetCore.Identity.UI  override access denied path

### ISSUE THREAD

**Issue by madshaun1984** [dotnet/aspnetcore#26813]
I've added the following to my Startup.cs, but i am finding that the AccessDeniedPath isn't working to make use of a customized Access Denied page.

`

            services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // Use the groups claim for populating roles
                options.TokenValidationParameters.RoleClaimType = "roles";
                options.AccessDeniedPath = new PathString("/Account/AccessDenied"); // This isn't being used??
            });

            //Adding authorization policies that enforce authorization using Azure AD roles.
            services.AddAuthorization(options =>
            {
                options.AddPolicy(AuthorizationPolicies.AssignmentToUserReaderRoleRequired, policy => policy.RequireRole(AppRole.UserReaders));
                options.AddPolicy(AuthorizationPolicies.AssignmentToDirectoryViewerRoleRequired, policy => policy.RequireRole(AppRole.DirectoryViewers));
            });

            services.AddControllersWithViews(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser() /* Comment this line to remove Authorization site wide */
                    .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            }).AddMicrosoftIdentityUI();
            services.AddRazorPages();
`

Essentially, all I'm trying to do is add a message that prompts the user to try signing out then back in again to see if the issue persists (for changing role tokens).

What options do I have besides not using the Microsoft.AspNetCore.Identity.UI library?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `AccessDeniedPath` setting is being overriden when you're calling `AddMicrosoftIdentityUI`. Consider moving the `Configure<OpenIdConnectOptions>` call in the bottom as follows:

```csharp

        //Adding authorization policies that enforce authorization using Azure AD roles.
        services.AddAuthorization(options =>
        {
            options.AddPolicy(AuthorizationPolicies.AssignmentToUserReaderRoleRequired, policy => policy.RequireRole(AppRole.UserReaders));
            options.AddPolicy(AuthorizationPolicies.AssignmentToDirectoryViewerRoleRequired, policy => policy.RequireRole(AppRole.DirectoryViewers));
        });

        services.AddControllersWithViews(options =>
        {
            var policy = new AuthorizationPolicyBuilder()
                .RequireAuthenticatedUser() /* Comment this line to remove Authorization site wide */
                .Build();
            options.Filters.Add(new AuthorizeFilter(policy));
        }).AddMicrosoftIdentityUI();

 services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
        {
            // Use the groups claim for populating roles
            options.TokenValidationParameters.RoleClaimType = "roles";
            options.AccessDeniedPath = new PathString("/Account/AccessDenied"); // This isn't being used??
        });

        services.AddRazorPages();

```

**Comment by madshaun1984** [comment]
Hi @mkArtakMSFT,

Apologies for the delay in response. I have tried this (prior / post opening this issue), yet the Access Denied prompt shown is still the one from the Microsoft.Identity.UI lib.

Could this be an error of some sort? As it seems your suggestion matches what I originally thought, yet in my case, its not working as expected.

Thanks!
