### ISSUE TITLE
Blazor won't run from html file from Apache

### ISSUE THREAD

**Issue by jelmerveen** [dotnet/aspnetcore#26818]
### Describe the bug

The webapplications says:

 Loading....

I open up Developers console it says:

```None of the “sha256” hashes in the integrity attribute match the content of the subresource.```

### To Reproduce

I scaffold a new app using the template in Visual Studio 2019 Community 
(as is, I don't check any boxes)

**Scaffold app**
File -> new Project -> Blazor App

**Then I create a release build**
Select _Release_ from the dropdown

Build -> Build Solution

**Deploy app**
I navigate to the folder in my %project%/bin/Release/netstandard2.1/wwwroot

I select all the files and place them on my server, behind Apache Webserver

I navigate to my website, error immediately occurs.

### Further technical details
I run the latest version of Visual Studio Community

**Comment by captainsafia** [comment]
@jelmerveen This issue you're reporting is related to the integrity checks that Blazor does on assemblies when they are fetched from the server.

Your Apache server might be modifying the response in such a way that the incorrect hash is computed for the same assemblies. You can check out the documentation page at https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#resolve-integrity-check-failures for more help here.
