### ISSUE TITLE
Azure B2C Blazor WASM not working without implicit grant settings (some property missing)

### ISSUE THREAD

**Issue by ShadyNagy** [dotnet/aspnetcore#26811]
### Describe the bug
I try azure template for B2C Blazor WASM but it is not working without implicit grant settings

### Fixes
Microsoft.Authentication.WebAssembly.Msal version 3.2.1 missing 2 properties
in MsalProviderOptions.cs
```csharp
public string LoginMode { get; set; } = "popup";
```
and in MsalAuthenticationOptions.cs
```csharp
public IList<string> KnownAuthorities { get; set; } = new List<string>();
```

- Have to use msal-browser 2 not msal-browser 1.x.x in package.json
```json
"@azure/msal-browser": "^2.0.0"
```

- Have to use latest [AuthenticationService.ts](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts)

### To Reproduce
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
```powershell
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE VS 16.8.0 Preview 3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've added support for this in .NET 5.0. Please update to the latest RC release.

**Comment by StevenTCramer** [comment]
@mkArtakMSFT Please reopen.

If 3.1 isn't supported then why bother making 3.1 templates?  

https://developer.microsoft.com/en-us/identity/blogs/microsoft-identity-web-is-now-generally-available/

Explicitly references 3.1 templates.

![image](https://user-images.githubusercontent.com/357219/95772074-5ac7ff80-0ce6-11eb-9b1f-53ff7b6086bd.png)

**Comment by ShadyNagy** [comment]
@mkArtakMSFT thanks for your reply. But if that not supported why Azure not telling it is supported only for net5? Small changes even can be done in one typescript file will be hard!

**Comment by ShadyNagy** [comment]
Anyone have the same problem and want to use 3.1 can use this modified JS

https://github.com/ShadyNagy/b2c-blazor-wasm-31

**Comment by StevenTCramer** [comment]
@ShadyNagy Seems to be working for me.  Thanks
