### ISSUE TITLE
[Blazor WASM] Localization with Pre-rendering enabled

### ISSUE THREAD

**Issue by TomJD** [dotnet/aspnetcore#26810]
**QUESTION**
How do I register the service for DI?

**The problem:**
I am trying to enable localization in Blazor WASM Pre-rendered using `IStringLocalizer`. 
It works fine when pre-rendering is not enabled.

_Index.razor_
```
@page "/"
@inject IStringLocalizer<App> Localize

<h1>@Localize["Hello World"]</h1>
```

_Program.cs_
```
[...]
builder.Services.AddLocalization(options => options.ResourcesPath = "Resources");
builder.Services.AddBlazoredLocalStorage();

 var host = builder.Build();
[...]
await host.RunAsync();
```

**Exception**
InvalidOperationException: Cannot provide a value for property 'Localize' on type 'BlazorApp2.Client.Pages.Index'. There is no registered service of type 'Microsoft.Extensions.Localization.IStringLocalizer`1[BlazorApp2.Client.App]'.

**Tech:**
- .NET 5 RC-1
- Blazor WASM (with pre-rendering)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You can register the necessary services by adding the same localization services on the server `Startup` class.

**Comment by TomJD** [comment]
Thank you.

I have added to `Startup.cs` on the server project the following 2 lines and seems to work.

```
services.AddLocalization();
services.AddBlazoredLocalStorage();
```

Not sure if it is correct however, that the services need to be registered twice: once on the client and once on the server.
