### ISSUE TITLE
Including ApiController attribute results on an Unsupported Media Type

### ISSUE THREAD

**Issue by zinov** [dotnet/aspnetcore#26828]
Web Api project, .net core version: 3.1

My API didn't have the ApiController attribute and I was including it as part of the new changes to integrate later with swagger.
**Problem**:
All my get request were working before normally with my Endpoint. After including the attribute I got an UnsupportedMediaType error.

My original API controller looks like this:

`    [Authorize]
    [Route("api/tenants/{tenantId}/policies")]
    [EnableQuery]
    public class PolicyController : BaseController
    {
          ....
    }
`
my new change: 

`    [Authorize]
     [ApiController]
    [Route("api/tenants/{tenantId}/policies")]
    [EnableQuery]
    public class PolicyController : BaseController
    {
          ....
    }
`
my Action method:

`[HttpGet(Name = nameof(GetPoliciesByTenant))]
        public async Task<IActionResult> GetPoliciesByTenant(Guid tenantId, PolicyResourceParameterDto polResParamDto)
        {
            ....
        }
`

From the client, I was passing an **Accept** header with **application/json** which is one of the default formatters that .net core has.  I think this is a bug. Please let me know if you need more details.

**Comment by pranavkm** [comment]
For `ApiControllerAttribute`, we wanted to keep the rules for determining where an object gets bound simple and unambigious. One of the decisions was to treat complex types as always being bound from the body. While this makes it obviously weird for GET / HEAD requests that do not have a body, the rules are much less ambiguous if an action supports multiple HTTP verbs.

Our recommendation would be to apply the `[FromQuery]` attribute for complex types that are being bound from the query string.

**Comment by zinov** [comment]
@pranavkm the problem is not passing the parameters using the **[FromQuery]** as you suggested. With the **ApiController** attribute, there is no need to include FromQuery in that case. My problem is that I am getting an UnsupportedMediaType, and that depends as it says on the MediaType you are passing which by default is **application/json**
