### ISSUE TITLE
Adding gRPC Service Reference problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26820]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1211151/adding-grpc-service-reference-problem.html)._

---
I think VS2019 not use HTML/2 request
: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

---
#### Feedback Bot on 10/8/2020, 11:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by JamesNK** [comment]
Is your port using TLS? If it isn't using TLS then additional configuration is required when using gRPC

Instructions:

https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1#call-insecure-grpc-services-with-net-core-client
