### ISSUE TITLE
Support HTML embedded language diagnostics.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#26830]
- [x] (External) Move the message interceptor layers into the contained language framework:
  - https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/282267
![image](https://user-images.githubusercontent.com/2008729/95796116-e9199280-0ca0-11eb-8f68-4b9713a073cd.png)
- [x] Intercept our virtual HTML buffer diagnostics and remap them onto the Razor document.

**Comment by TanayParikh** [comment]
Filtering HTML diagnostics needs diagnostic code annotations. Tracked via: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1257401

**Comment by TanayParikh** [comment]
Continuation: https://github.com/dotnet/aspnetcore/issues/27563

**Comment by TanayParikh** [comment]
Filtering HTML Diagnostics Not Needed for .razor: https://github.com/dotnet/aspnetcore/issues/28654
