### ISSUE TITLE
Add local LSP editor DDRITs tests

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#26831]
The primary work here is to take the tests we wrote for Nexus and create equivalents for our local LSP editor. That way we can understand when changes break Nexus vs. Local Razor scenarios.

**Comment by TanayParikh** [comment]
@ryanbrandenburg safe to push this out to Preview 3? I'm still blocked on my DDRIT tests being checked into Codespaces, so they definitely won't be available for local. 

https://github.com/dotnet/aspnetcore/issues/26978
https://github.com/dotnet/aspnetcore/issues/26980
https://github.com/dotnet/aspnetcore/issues/26979
https://github.com/dotnet/aspnetcore/issues/26976

**Comment by ryanbrandenburg** [comment]
Yeah there's no way we get this ready in time at this point, we'll have to push out.

**Comment by ryanbrandenburg** [comment]
Finished in https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/323844. Further work tracked by https://github.com/dotnet/aspnetcore/issues/32623.

**Comment by TanayParikh** [comment]
🎉
