### ISSUE TITLE
what is "An Access Token" in SignalR Java client

### ISSUE THREAD

**Issue by MeysamMoghaddam** [dotnet/aspnetcore#26845]
i use jwt token in my aspnet core host.how to use this token in java project

sample token
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWV5c2FtLm1vZ2FkZGFtIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxNTVmYzQzOC1iOTMxLTRhMzAtOTkzMC1kYTE0YzMzNGJiYjUiLCJTZWN1cml0eVN0YW1wIjoiU1RCWkNaMlZQSlNaUjVBTlBLWklPMlBJSkZPQ09YQ0ciLCJGdWxsTmFtZSI6ItmF24zYq9mFIiwiVXNlck5hbWUiOiJtZXlzYW0ubW9nYWRkYW0iLCJVc2VySWQiOiIxNTVmYzQzOC1iOTMxLTRhMzAtOTkzMC1kYTE0YzMzNGJiYjUiLCJVc2VyR2VuSWQiOiIzNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNjM0MDc3MzQyLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0In0.9NzAAolF5XgBcWH2lP9WDLcYQiNDBzkW-IzVppaSe40`

and this my java code:

`HubConnection hubConnection = HubConnectionBuilder.create("MY HUB URL HERE")
    .withAccessTokenProvider(Single.defer(() -> {
        // Your logic here.
        return Single.just("An Access Token");
    })).build();`

What exactly is "An Access Token" ?

my login method genarate token

**Comment by BrennanConroy** [comment]
> What exactly is "An Access Token" ?

The sample token you provided above is "An Access Token". Generally you'll put logic in `withAccessTokenProvider` to return an access token instead of hard-coding a token value.

**Comment by MeysamMoghaddam** [comment]
Do you have a sample? Because I can not send messages to a specific user.But I easily send messages to everyone
[sample](http://pishtazan.bppir.com/Content/upload/bandicam%202020-10-14%2013-26-46-061.gif)

Please guide me further
