### ISSUE TITLE
Changes in .razor.css file in an RCL not picked up without a rebuild

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#26843]
Repro steps:

- Install 16.8 Preview 4 with .NET 5 RC2
- Create a Blazor Server app
- Add an RCL to the solution and reference it from the app
- Add `Component1` to the Index age
- Run the app
- Edit *Component1.razor.css* and save
- Refresh the browser - changes don't show up
- Build the app and refresh the browser - changes don't show up
- Rebuild the app and refresh the browser to see the changes

Expected result:

- Editing .razor.css in RCL causes app to auto rebuild. Refreshing the browser should show the changes

Actual result

- Auto rebuild doesn't occur and changes aren't shown

Workaround:

- Rebuild the app and refresh the browser.

**Comment by danroth27** [comment]
@pranavkm

**Comment by captainsafia** [comment]
@javiercn Should we expect this work? If so, can we make a fix for this in .NET 5?
