### ISSUE TITLE
Bug Bash!

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#26858]
## Goal

Build an actual application using a Razor based framework and log any issues found. This could be done in Blazor, MVC or Razor pages. If you're familiar with one of the frameworks I'd encourage you to try and spend more time in your Razor files by even writing some nested C# classes 😉 

## Getting setup

1. Install the latest Dogfood VS build: https://aka.ms/vs/dogfood/install
1. Check the `.NET Core cross-platform development` workload:
![image](https://user-images.githubusercontent.com/2008729/96774236-8f008780-139a-11eb-9eda-e0404729bf12.png)

1. Enable the experimental Razor editor feature flag (Tools -> Options -> Preview Features):
![image](https://user-images.githubusercontent.com/2008729/96622238-8c306480-12be-11eb-9002-32e3905a228f.png)
1. Restart VS
1. Go!

## Tutorials

If you're having a hard time landing on a specific app you'd want to build or you're new to the Razor area you can always try out some of the pre-existing tutorials/workshops that have been done in the past:

- [Blazor Workshop](https://aka.ms/blazor-workshop)
- [Blazor Todo List](https://docs.microsoft.com/aspnet/core/tutorials/build-a-blazor-app)
- [Chat with SignalR](https://docs.microsoft.com/aspnet/core/tutorials/signalr-blazor-webassembly)
- [MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-3.1)
- [Razor pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio)

## Filing issues

1. File an issue [using this template](https://github.com/dotnet/aspnetcore/issues/new?labels=area-razor.tooling%2C+feature-razor.vs&template=razor_tooling.md).
2. Leave a comment on this bug bash issue with a link to your newly created issue.

Don't worry about filing duplicate issues unless you know it's a duplicate f rom the start. We can always de-dupe later.

**Comment by danroth27** [comment]
Another idea is to port https://aka.ms/aspnetcorebugrank to Blazor.

**Comment by NTaylorMullen** [comment]
My bug bash project: To create a Blazor powered web editor for Blazor in the new Blazor editor!

![image](https://media2.giphy.com/media/XkDyB1jCZMxUs/giphy.gif?cid=ecf05e470nbt4sc9vgek6zut9xoq24jk4i0pvprb9fcnt9ug&rid=giphy.gif)

**Comment by ryzngard** [comment]
I'm going to be boring and see if I can get a flash card app going for my studies 😋

**Comment by NTaylorMullen** [comment]
- https://github.com/dotnet/aspnetcore/issues/27129

**Comment by TanayParikh** [comment]
- https://github.com/dotnet/aspnetcore/issues/27127
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1237695/

**Comment by dibarbet** [comment]
https://github.com/dotnet/aspnetcore/issues/27133

**Comment by ryanbrandenburg** [comment]
- https://github.com/dotnet/aspnetcore/issues/27135
- https://github.com/dotnet/aspnetcore/issues/27128

**Comment by danroth27** [comment]
- [Razor C# colorization editor](https://github.com/dotnet/aspnetcore/issues/27134)

**Comment by ajaybhargavb** [comment]
[Razor LSP colorization slightly off intermittently](https://github.com/dotnet/aspnetcore/issues/27137)

**Comment by allisonchou** [comment]
https://github.com/dotnet/aspnetcore/issues/27141 - Double diagnostics in error list after building

**Comment by dibarbet** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/20278

**Comment by NTaylorMullen** [comment]
@pranavkm @captainsafia @javiercn @SteveSandersonMS @HaoK We plan to triage Bug bash issues next Tuesday. Please file any issues before then.

**Comment by captainsafia** [comment]
* Unhandled exception after editing renamed Razor file (#27620)
* HTML element selection from completions doesn't autofill (#27621)
* Unexpected exception when editing new class file (#27622)

**Comment by NTaylorMullen** [comment]
Triaged the issues. Thank you for all your bashing!
