### ISSUE TITLE
PathString.FromUriComponent(string) should not decode %2F to forward slash

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2686]
_From @Tratcher on Monday, November 6, 2017 4:03:42 PM_

%2F, an escaped `/` is one of the only characters that should not be un-escaped by FromUriComponent. All other characters can correctly be round tripped by ToUriComponent, but %2F creates ambiguity if unescaped.
https://github.com/aspnet/HttpAbstractions/blob/c0f937239a0a099b73c67c96ab9e1c875952f67f/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L175

_Copied from original issue: aspnet/HttpAbstractions#959_

**Comment by muratg** [comment]
This is a (subtle) breaking change. Putting this in 3.0.0. If there's more demand, we can reconsider this.

**Comment by muratg** [comment]
Backlogging this to see if we'll get see any customer demand.

**Comment by thefringeninja** [comment]
I just bumped into this. I have a route like `/streams/{streamId}` where `streamId` should be allowed to have a `/` in it. I figured I could simply encode it with `Uri.EscapeDataString` but it gets converted back before it hits my middleware. I assume the solution is to replace `/` with `%2f` first and then encode _that_?

**Comment by muratg** [comment]
cc @anurse

**Comment by dasMulli** [comment]
I've had this issues 2 years ago and we decided to work around it instead of trying to make it work (wanting to RESTfully address some Dynamics NAV entity that used slashes in the names). Even if this worked in ASP.NET Core, we didn't feel comfortable that different client stacks, load balancers, reverse proxies etc. would work without issues.

**Comment by thefringeninja** [comment]
Hmmm, I just tested this using curl. Kestrel is decoding everything properly, so it is either `HttpClient` or `HttpClient` + `TestServer` that's causing the issue.

**Comment by Tratcher** [comment]
Fixed by https://github.com/dotnet/aspnetcore/issues/28965
