### ISSUE TITLE
Blazor Wasm Pwa Publish issue with scoped styles.

### ISSUE THREAD

**Issue by WayneHiller** [dotnet/aspnetcore#26862]
### Describe the bug

I have a demo app that is based on the default Blazor Webassembly (Hosted) project with PWA support.

Running under development everything works fine. After I publish the scoped css keys do not match between the html and css.

_framework/scoped.styles.css in the browser:
```
/* /Shared/MainLayout.razor.rz.scp.css */
.page[b-qpynkl53tm] {
    position: relative;
    display: flex;
    flex-direction: column;
}
```

Html in the browser:
```
<div class="page" b-fq9e6ufsuu="">
...
</div>
```

Any idea as to why these keys do not match?
I have tried clearing everything out of the browser cache and different ports many times. I tried just a fresh project in VS with no changes and it worked as expected.

### Further technical details
- ASP.NET Core version: 5.0.100-rc.1.20452.10
- Win 10 x64 VS 16.8.0 Preview 3.2

Updated to:
- ASP.NET Core version: 5.0.100-rc.2.20479.15
- Win 10 x64 VS 16.8.0 Preview 4

**Comment by WayneHiller** [comment]
I updated VS to Version 16.8.0 Preview 4.0 and now both my problem project and the one created directly from VS return a 404.

```
Request URL: https://localhost:5001/_framework/scoped.styles.css
Request Method: GET
Status Code: 404 
Remote Address: [::1]:5001
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by WayneHiller** [comment]
Updated VS to Version 16.8.0 Preview 4.0
Still having the same issue. Should those scoped css keys remain the same or change after rebuilding/Publishing?

**Comment by chassq** [comment]
Not sure if this helps or not but it seems once upgrade to RC2 we had to deprecated the line

`<link href="_framework/scoped.styles.css" rel="stylesheet" />`

and add instead 

`<link href="QuickstartHosted.Client.styles.css" rel="stylesheet" />` - QuickstartHosted.Client is the name of our assembly.

Before we did this we were getting a blazor.boot.json fetch error. Once we made the change the error went away.

**Comment by WayneHiller** [comment]
@chassq Ya I had to change that but it did not fix the issue.  It is strange that it works fine until I publish the app.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by WayneHiller** [comment]
@mkArtakMSFT I wish I could reproduce this in a project. When I create a new project in VS and then publish it works correctly. What I am trying to figure out is what to look for in my current project. I guess I could try slowly removing things from my project until it starts publishing correctly.

**Comment by WayneHiller** [comment]
There seems to be some kind of caching issue when publishing. If I make changes to the scoped styles and build I see the changes in the browser when running in VS. When I publish the {projectname}.styles.css file does not update it's date. I do have it set to Delete Existing Files in the publish profile.

**Comment by RugerSR9** [comment]
I second this issue on RC2. After changing my link to `<link href="ProjectName.styles.css" rel="stylesheet" />` as @chassq  recommended above, my site loads just as expected from VS. After publishing to IIS, the styles are still loaded (per devtools) but they are not actually loaded onto the page for whatever reason. There are no errors in the console or network tabs.

**Comment by WayneHiller** [comment]
@RugerSR9 I am playing with the issue right now. What I found is that I have to change my solution to Release Config, do a Rebuild and then publish. I think publish only does a build by default and that is not enough to regenerate the scoped css file.

**Comment by RugerSR9** [comment]
@WayneHiller I can't say that I am noticing an incorrect timestamp on my builds *.styles.css file. In fact, I had even completely deleted my **bin** folder to make sure it wasn't anything being referenced incorrectly within that. I attempted a clean & rebuild after switching my project to Release explicitly and still face the same issue.

**Comment by WayneHiller** [comment]
@RugerSR9 did you compare the css keys between the html and css in the {projectname}.styles.css file loaded into the browser?

```
<div class="page" b-fq9e6ufsuu="">
...
</div>
```

You could try adding this to your client project
```
<ItemGroup>
    <!-- Added to fix issue:
          https://github.com/dotnet/aspnetcore/issues/26862 
          https://github.com/dotnet/aspnetcore/issues/26884
    -->
    <UpToDateCheckInput Include="**\*.razor.css" />
  </ItemGroup> 
```

**Comment by RugerSR9** [comment]
@WayneHiller thanks for pointing me to the css keys, still getting a feel for how this process works. Keys in my html do not match any keys within the *.styles.css file. I did try adding the `<UpToDateCheckInput...` tag into my .csproj based on the other issue you attached but it didn't change anything for me. Will continue to play with it and post an update if I have any luck.

**Comment by WayneHiller** [comment]
@RugerSR9 Are you running the latest VS Version 16.8.0 Preview 4.0? I my case switching to the Release config in VS and then doing the Rebuild regenerated the {PN}.styles.css file. Then publishing copied it to the wwwroot folder.

**Comment by RugerSR9** [comment]
@WayneHiller Yes sir, Visual Studio Enterprise 2019 16.8.0 Preview 4.0

**Comment by pranavkm** [comment]
@WayneHiller do you happen to have a set of steps that consistently reproduces the problem? I've been playing around with this for a bit but I don't see any issues here. We had a couple of fixes around VS not causing builds to kick off on changes to scoped css files very recently that are now available as part of the 5.0-RTM SDK - https://github.com/dotnet/installer#installers-and-binaries. I don't think that necessarily solves the problem you're seeing here, but it might be worth a shot.

**Comment by WayneHiller** [comment]
There is an issue above that I referenced that is the same issue I think. I had vs in debug config and then did a publish (release) but I don't think publish is doing a rebuild so it was not updating the css file. The old one got copied into the wwwroot folder there for none of the css keys matched.

**Comment by RugerSR9** [comment]
I’ll see if I can’t clean up my project and create a repo for it tomorrow morning.

**Comment by WayneHiller** [comment]
https://github.com/WayneHiller/BlazorWasmPwa

This is a project created from VS. Blazor Wasm Hosted Pwa.

With VS in Debug config. I edit the MainLayout.razor.css .page background-color.
Build and run from VS.
Publish (Release).
Run published app and refresh browser. Often the background color is not updated.

**Comment by pranavkm** [comment]
Thanks @WayneHiller. I was able to reproduce the problem with the RC2 SDK. The newest RTM SDK from  https://github.com/dotnet/installer#installers-and-binaries appears to resolve the issue. It effectively has the same fix that you've listed in your project file. 

Could you try updating and let us know if that helps?

**Comment by WayneHiller** [comment]
After installing the SDK 5.0.100-rtm.20515.8

I get an error when rebuilding the project.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Microsoft.NETCore.App.Runtime.browser-wasm with version (= 5.0.0)
  - Found 437 version(s) in dotnet5 [ Nearest version: 6.0.0-alpha.1.20420.2 ]
  - Found 6 version(s) in nuget.org [ Nearest version: 5.0.0-rc.2.20475.5 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in DevExpress 19.2 Local
  - Found 0 version(s) in github
  - Found 0 version(s) in nuget.telerik.com	Blazor Wasm Kendo 2.Client	D:\Development\Tests\Blazor Wasm Kendo 2\Client\Blazor Wasm Kendo 2.Client.csproj	1	

```

**Comment by pranavkm** [comment]
Shoot. You'll have to wait for the RTM release to be made public before you can start using the 5.0 RTM SDK. Consider using the workaround you had discovered until then.

**Comment by WayneHiller** [comment]
Ya for now just need to do a rebuild. RTM is getting close, YAY!
