### ISSUE TITLE
Support Azure DevOps Extension development using Blazor

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/aspnetcore#26865]
### Is your feature request related to a problem? Please describe.
**Azure DevOps Extension** currently can **only be developed using Node.js**

There have been feature request for Azure DevOps Extension development to support Blazor last few months
- https://github.com/dotnet/aspnetcore/issues/14794
- https://developercommunity.visualstudio.com/idea/425875/develop-azure-devops-extensions-using-blazor.html
- https://github.com/dotnet/aspnetcore/issues/15284
- https://developercommunity.visualstudio.com/content/problem/704085/building-blazor-devops-extensions.html
- https://stackoverflow.com/questions/57652842/using-a-net-class-library-in-nodejs-app-using-blazor

### Describe the solution you'd like
With the support of Blazor WASM client in .NET5, perhaps it is now more feasible to implement such request.

[Node.js now supports WASM and it is possible to run a .wasm file in nodejs](https://www.joyent.com/blog/improved-wasm-support-coming-to-node)

With the release of Blazor WASM client in .NET5. I would like the community to vote if there is sufficient interest to making the Client Side Blazor (Mono which executes the C# DLLs) to run inside NodeJS so that it is possible to develop Azure DevOps Extension using Blazor and c#

The first step towards that request is FIRST to create a label =>  <code>**DevOpsBlazorExtension**</code>

This will allow the community to track the interest and to feedback how important the community see this as an important feature request for the ASP.NET Team and the need for the team to work with the Azure DevOps team.

**Comment by MarkKennedyAveva** [comment]
Does .NET 5 even work in DevOps? I tried to deploy a course project for grad school and had to use .NET Core 3.1

**Comment by GeorgeS2019** [comment]
@MarkKennedyAveva  Your question is not related to making Blazor WASM Client with mono runtime to run within Node.js. The support for .NET5 is within the mono runtime, independent of Azure DevOps issue you raised.

**Comment by GeorgeS2019** [comment]
Not sure if this is relevant for discussion. Please feedback.
[**Using npm packages with Blazor**](https://medium.com/swlh/using-npm-packages-with-blazor-2b0310279320)

**Comment by MarkKennedyAveva** [comment]
That is a good example of using the interop to consume a Node package. But we're trying to serve up a DevOps extension using Blazor.

**Comment by GeorgeS2019** [comment]
@MarkKennedyAveva I do not have the overview, I would like to encourage the community to gather potentially related and relevant issues here so over the next few months, the interest will grow to the extend that both the Asp.Net and Azure DevOps teams will seriously make Blazor and C# Azure DevOps Extension development possible.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not an area our team owns. We recommend submitting this feedback to the Azure DevOps related feedback channels.

**Comment by mkArtakMSFT** [comment]
@danroth27 FYI in case you want to follow-up with the AzDO folks internally.

**Comment by GeorgeS2019** [comment]
@mkArtakMSFT  and @danroth27   I know I keep pushing this.  I see the combination of Azure DevOps Extension written in Blazor will deliver impact that will deliver win-win to both the Blazor (Microsoft future Web development) and Azure DevOps ( Microsoft future fast iterative project management). I just need time to convince the Microsoft team. :-)
