### ISSUE TITLE
Cookie not being saved/available in request, when it's added right before a call to `Challenge`?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#26880]
We have a normal action method, in which we do the following:

```
CookieOptions cookieOptions = new CookieOptions
{
    IsEssential = true,
    SameSite = SameSiteMode.None,
    Secure = true,
    HttpOnly = false
};

HttpContext.Response.Cookies.Append("helpmework", "1", cookieOptions);

// Return scenarios
return Challenge(authenticationProps, scheme); // Request following this call does not contain above cookie
return Ok(); // next request will successfully contain above cookie, regardless if in the context of a Challenge.
```

Basically if we end the method with a call to `Challenge`, parts of the code that continue running from the `Challenge`, don't end up having the added cookie. If we first add the cookie (in a separate request), and then try to do the above with `Challenge`, we can see the cookie just fine.

So the problem seems to be that if I add a cookie in the same request that I wish to authorize via `Challenge`, the cookie won't be present in `HttpContext.Request` following the `Challenge` call.

I think the cookie is not saved until the actual response is sent, which might explain why this happens.

**EDIT:** 
Upon further inspecting, `HttpContext.Response` in the context of `Challenge`, has a header `Set-Cookie` equal to
 ```
{helpmework=4; path=/; secure; samesite=none,.AspNetCore.OpenIdConnect.Nonce.CfDJ8Bv5Uj-pfwRMh6MKXPri8w0sN5BGRP3AeZYQp7ylkWriq4K7NwsYOnI0b4mim3v6K-9x3nq7sOavOWgsq3nO_ZUgILumnHA_UE1sXwG4opIwEtMUyRqzH_0WPzzmv__YLW008LL0KfKD0mYgbubf4QYNjqkEbxbLE_zOOlMPUBWNa3Wl5jxgEbWi83d_QwH9Lti3LLmt77Yyy-WuTmy1tEprgE87BKtHshuKWwhJhtta96xUdrBhjXSHzkcgP9h0O7IGJZCOXRBW6YnKTnTKn28=N; expires=Wed, 14 Oct 2020 08:30:40 GMT; path=/signin-oidc-okta; secure; samesite=none; httponly,.AspNetCore.Correlation.okta.zSv3-10u92yZzP1ZJyvEZPmsnOkKPHtbWQ8AdaAXNUE=N; expires=Wed, 14 Oct 2020 08:30:40 GMT; path=/signin-oidc-okta; secure; samesite=none; httponly}
```

**Comment by blowdart** [comment]
What typoe of authentication are you using?

**Comment by SpiritBob** [comment]
OpenID connect

**Comment by Tratcher** [comment]
> I think the cookie is not saved until the actual response is sent, which might explain why this happens.

This is always the case for Asp.Net Core cookies, regardless of Challenge. Request cookies and response cookies are kept apart so you can distinguish between the client's current state and their future state.

**Comment by blowdart** [comment]
Ah indeed, I missed that you were using HttpContext.Request.

**Comment by SpiritBob** [comment]
Thank you @Tratcher for clearing this up, I'm closing this as you guys have a lot more important matters to dive deep into.

The best alternative in this case is to use the `Items` property and store my information there.
