### ISSUE TITLE
Console errors for Release published Blazor app with .NET5 RC2

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#26888]
I have upgraded my App to .NET5 RC2 all works and lots of bugs was fixed. Thanks.

However when I publish the app in Release config then I see a few new error messages in the Browser Console log. Application seems working fine though:

![image](https://user-images.githubusercontent.com/7632824/95991372-fb283c00-0e2c-11eb-9226-c94df8ec6989.png)

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://blazorextensions.z6.web.core.windows.net/css/app.css' with computed SHA-256 integrity 'kfFHrAyz9Im9Sueq4gpkz6PjAqTa22pn7nt+gnZQNfY='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
Failed to find a valid digest in the 'integrity' attribute for resource 'https://blazorextensions.z6.web.core.windows.net/_framework/blazor.webassembly.js' with computed SHA-256 integrity 'zjnMdINC6+UOsAEnIZMXZHpX+PiGCSu9n7GoJcGapJQ='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The following docs article will help you find the cause for the error: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#resolve-integrity-check-failures

**Comment by majorimi** [comment]
Ok, thanks. Probably this was the error. I'm hosting WebAssembly app as Static files in Azure Blob. And routing works if the ErrorPage is also the `Index.html`. So when someone want to navigate to a page first I always get a 404 from Azure Blob.
Not sure why is this occurred only now. Actually I don't even get these errors anymore and I was not redeploying the app...

"The web server's response is an error **(for example, a 404** - Not Found or a 500 - Internal Server Error) instead of the file the browser requested. This is reported by the browser as an integrity check failure and not as a response failure."
