### ISSUE TITLE
RFC 8187 - Character Encoding for Headers

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2688]
_From @benaadams on Thursday, September 14, 2017 10:47:59 PM_

From https://github.com/aspnet/KestrelHttpServer/issues/2063

Hot off the presses (September 2017) https://tools.ietf.org/html/rfc8187

Indicating Character Encoding and Language for HTTP Header Field Parameters

> @Tratcher  Hmm, interesting choices. It only applies to key value pairs within headers, and is ASCII compatible, so I don't foresee making any changes to Kestrel. Microsoft.Net.Http.Headers in HttpAbstractions looks like the most obvious consumer/producer of such values. ContentDispositionHeaderValue already supports this because it was designed for use in multipart MIME bodies: https://github.com/aspnet/HttpAbstractions/blob/5128efe0e88eaa176d4231ff62d754de59bb0edd/src/Microsoft.Net.Http.Headers/ContentDispositionHeaderValue.cs#L347
>
> Move to HttpAbstractions?

_Copied from original issue: aspnet/HttpAbstractions#940_

**Comment by ahsteele** [comment]
Any chance of this getting worked on anytime soon?

**Comment by davidfowl** [comment]
Until we have something concrete
