### ISSUE TITLE
Update ElementReference for hidden elements to the default value

### ISSUE THREAD

**Issue by hazaip** [dotnet/aspnetcore#26886]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
I have an ElementReference property on my RazorComponent, and when the element gets hidden by some wrapping logic (if statement for example evaluates false makes element not to render anymore), then the ElementReference property value does not get updated by the time OnAfterRender() gets called. In case I use the ElementReference in JsInterop, I would get an error, and no way to check if the element is still valid.

### Describe the solution you'd like
It would be great if ElementReferences would get updated on rendering cycle, and if they don't get rendered, than they just fall back to default(ElementReference) value. This way one may check with a comparer that the ElementReference value is default meaning the element is not rendered.

**Comment by javiercn** [comment]
@hazaip thanks for contacting us.

We don't clear element references by default as that would require additional work on each component render. We recommend that instead you wrap your OnAfterRender logic that uses the element reference with the same guard you used to render it.
