### ISSUE TITLE
With Visual Studio Preview 4 the build doesn't generate anymore the scoped.styles.css file.

### ISSUE THREAD

**Issue by ABIOLI-COM** [dotnet/aspnetcore#26884]
I have a simple client-server Blazor WebAssembly solution (just the generated code, plus some testing), and using css isolation (SCSS file setup to generate the corresponding .razor.css files) I had automatically a scoped.styles.css file to include in the Index.html file (<link href="_framework/scoped.styles.css" rel="stylesheet" />).
After downloading the Preview 4, yesterday, I noticed that this file is not generated anymore.
I can see there's an equivalent file .../obj/debug/net5.0/scopedcss/bundle/[AssemblyName].styles.css, but it's not copied to the wwwroot/_framework folder, as it was before.
I don't know if I've lost anything, in the conversion (I updated all the libraries in the various projects), or how to setup this copy of the file (since it was all automatic, I never investigated the details).
I read the Release Notes about the Preview 4, but I didn't find anything about this problem...

**Comment by javiercn** [comment]
@ABIOLI-COM thanks for contacting us.

We place this file now at the root of the wwwroot folder for the project and use the convention `[AssemblyName].styles.css` to refer to it.

**Comment by ABIOLI-COM** [comment]
Very strange, because for me it's not generated... Is there anything to modify, in the project, or configuration, or something?

**Comment by mkArtakMSFT** [comment]
@ABIOLI-COM can you try to start from a new project and see what's different in your case?

**Comment by ABIOLI-COM** [comment]
I had to create a new test application from scratch, to see how it works... Sorry, I understood, now... Thanks!!!

**Comment by WayneHiller** [comment]
This is related https://github.com/dotnet/aspnetcore/issues/26862

I found you have to do a Rebuild of the solution, build does not seem to generate/update it

**Comment by javiercn** [comment]
There's a bug that we are currently fixing. You can add
```xml
<ItemGroup>
   <UpToDateCheckInput Include="**\*.razor.css" />
</ItemGroup>
```

For visual studio to pick up the updates.
