### ISSUE TITLE
Cannot use IJsRuntime from Within Identity Framework

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#26898]
In Blazor, if I create a button and run this when the form is submitted, JSRuntime works.

    await jsRuntime.InvokeVoidAsync("eval", "document.cookie = ''");
    await signInManager.SignInAsync(user, false, null).ConfigureAwait(false);

BUT... if I move the jsRuntime line into the Identity processing chain, in this case, in a class overriding CookieAuthenticationHandler, then it throws this error.

> System.InvalidOperationException: 'JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.'

First, the error message is wrong because the page is fully rendered. Second, how can I make it work?

**Comment by Pilchie** [comment]
Tagging @HaoK and @javiercn for the identity part.

**Comment by javiercn** [comment]
@mysteryx93 thanks for contacting us.

`IJSRuntime` is not designed to work with the HTTP pipeline in ASP.NET Core. You are trying to execute JS in the context of an HTTP request which is not possible.

Identity and Identity UI are designed to work in an HTTP Based context, trying to use them outside of that context is not supported. While individual components might "work" we don't recommend their usage outside of a Request/Response pipeline (like in Blazor case).

This is not something we plan to change in the future. Our recommendation is to leave the authentication part of the application as a classic request/response web application and rely on redirects for setting up the auth context for the blazor application.

**Comment by mysteryx93** [comment]
Yet I'm so close to making it work. If I can't run IJSRuntime from the HTTP pipeline, is there a way to pull the cookie value out of the HTTP pipeline to access it from the page afterwards? A shared service should be able to achieve that, although it wouldn't be pretty?

**Comment by javiercn** [comment]
@mysteryx93 Unfortunately, there is no straightforward answer we can give you for your problem. While we try our best to help everyone, we don't have the resources to address issues around unsupported scenarios. We suggest posting your question to StackOverflow to try and get help
