### ISSUE TITLE
Routing fails with catch all when gRPC service is enabled.

### ISSUE THREAD

**Issue by Dreamwalker666** [dotnet/aspnetcore#26896]
### Description

When you are trying to perform a catch all on a sub route (not site route) it fails with a 404 error.  This only happens when a gRPC service is enabled.

### To Reproduce

* Create a standard gRPC service using the normal template
* Modify the default response endpoint line to the route below

`endpoints.MapGet("/test/{*_}", async context =>`

* Now run the site 
* Navigate to [https://127.0.0.1:5001/test/test ](https://127.0.0.1:5001/test/test)
* You will receive a 404 error
* Comment out the line 

`//endpoints.MapGrpcService<GreeterService>();`
* Now using the test link it now works and gives the standard "Communitcation with gRPC...." message

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  1.0.0-preview2-003131 [c:\program files\dotnet\sdk]
  1.0.4 [c:\program files\dotnet\sdk]
  2.0.0 [c:\program files\dotnet\sdk]
  2.0.2 [c:\program files\dotnet\sdk]
  2.0.3 [c:\program files\dotnet\sdk]
  2.1.4 [c:\program files\dotnet\sdk]
  2.1.103 [c:\program files\dotnet\sdk]
  2.1.104 [c:\program files\dotnet\sdk]
  2.1.202 [c:\program files\dotnet\sdk]
  2.1.500 [c:\program files\dotnet\sdk]
  2.1.503 [c:\program files\dotnet\sdk]
  2.1.700 [c:\program files\dotnet\sdk]
  2.1.801 [c:\program files\dotnet\sdk]
  2.1.802 [c:\program files\dotnet\sdk]
  2.2.103 [c:\program files\dotnet\sdk]
  3.1.403 [c:\program files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@Dreamwalker666 thanks for contacting us.

You are likely running into [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference)

**Comment by Dreamwalker666** [comment]
> @Dreamwalker666 thanks for contacting us.
> 
> You are likely running into [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference)

Yes this is exactly the issue, placing `AppContext.SetSwitch("Microsoft.AspNetCore.Routing.UseCorrectCatchAllBehavior", true);` in Main fixed the issue.
