### ISSUE TITLE
razor view CS0246 The type of namespace OwnClassLib could not be found

### ISSUE THREAD

**Issue by esukmonica** [dotnet/aspnetcore#26892]
Not sure if it is the right place. This is not a CORE application. If wrong, could you please point me out to the right place. Thanks

I have a MVC web app targeting framework 4.7.2. It has a reference to a dll (which also targets 4.7.2). 
I can use the dll no problem in the .cs files, however when I try to use it in the .cshtml files, it gives me the error: "CS0246 The type of namespace OwnClassLib could not be found ..."

The web.config under the "Views" folder contains the namespace: 
`<add namespace="OwnClassLib"/> `
Please note that this was working. Not sure when the problem started, as I haven't been working with the views for quite a while. As I added one today I notice this problem. 

**Technical details**
- ASP.NET Web Application (.NET Framework)
- Microsoft Visual Studio Professional 2019 Version 16.7.6
- Output of dotnet --info:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pranavkm** [comment]
@esukmonica thanks for your issue. Could you please file this issue through the VS feedback tool so that it gets routed to the correct team? Thanks! 

Here's a guide to filing such an issue: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
