### ISSUE TITLE
Excessive use of 'internal' modifier on default implementations hinders extensibility

### ISSUE THREAD

**Issue by troyji** [dotnet/aspnetcore#26900]
Types in the namespace `Microsoft.AspNetCore.Mvc.Razor` are generally well designed for extensibility.  However, the excessive use of the `internal` modifier on default implementations makes them very difficult to extend in practice.

The `RazorViewEngine` is designed as a dependency chain of interface / default implementation pairs.  While the interfaces are public, the majority of the default implementations are internal.  Because of this, if you choose to replace any one link of the chain, you are forced to also replace all of the default implementations in the rest of the chain.

For example, consider the following chain of types:
`public interface IRazorViewEngine`
`public class RazorViewEngine : IRazorViewEngine`
`public interface IRazorPageFactoryProvider`
`internal class DefaultRazorPageFactoryProvider : IRazorPageFactoryProvider`
`public interface IViewCompilerProvider`
`internal class RuntimeViewCompilerProvider: IViewCompilerProvider`
`public interface IViewCompiler`
`internal class RuntimeViewCompiler : IViewCompiler`
`internal class CSharpCompiler`
`internal class RazorReferenceManager`

If you wanted to change something simple in `RuntimeViewCompilerProvider`, you would be unable to inherit & override it.  Instead, you would have to re-implement the entire class.  Furthermore, you do not have access to create an instance of `RuntimeViewCompiler` that you need to return from the provider, so it must be re-implemented as well.  In turn, you must also re-implement `CSharpCompiler` and `RazorReferenceManager`.  Furthermore, helper libraries such as `ViewPath` and `MvcRazorLoggerExtensions` are also internal and must be replaced.

In practice, you would either need to copy the source code for all of these dependencies into your own project and reconcile them each time you upgrade the framework version, or you would have to leverage reflection to bypass the visibility restriction and take on the risks and burden associated.

The [Engineering Guidelines](https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines#when-to-use-internals-vs-public-and-when-to-use-internalsvisibleto) explicitly discourage the use of internals.  The issues outlined here are a good representation of the side-effects of over-utilizing them.  I request for an evaluation and loosening of the visibility of default implementations throughout the framework to make extensibility more approachable.

I would hope to have these loosened before 5.0 ships, though I may be too late to the party.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like we didn't update our engineering guidelines to reflect on our learnings over time.
We've changed our philosophy regarding the usage of `internal`. We will update the guidance to avoid further confusion.
As for the types you're referring to, we don't plan to change these to `public`. You can learn more about the reasons behind this from [this thread](https://github.com/dotnet/aspnetcore/issues/4932).

If you happen to have a good reason for a specific type to be made public, please file a separate issue and share details justifying the ask.

**Comment by mkArtakMSFT** [comment]
https://github.com/dotnet/aspnetcore/issues/26937
