### ISSUE TITLE
AddAzureWebAppDiagnostics does nothing when running in a Linux Docker container on Azure Web Apps

### ISSUE THREAD

**Issue by mgnsm** [dotnet/aspnetcore#26903]
According to the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#azure-app-service-provider), calling `AddAzureWebAppDiagnostics()` in an ASP.NET Core application that is deployed to an App Service app in Azure should write application logs to the file system assuming that application logging has been enabled.

This however doesn't seem to work. I can't find any log messages written using the `Microsoft.Extensions.Logging.ILogger<TCategoryName>` API on the file system.

Is the documentation wrong or am I missing something? Isn't this supposed to work for containerized Docker apps as well?

Steps to reproduce:

1. Create an ASP.NET Core web application in Visual Studio 2019 using the API template with Docker support enabled.

2. Log something in the `Get()` method of the generated `WeatherForecastController` controller:

        [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            _logger.LogInformation("Weather forecasts requested...");
            ...
        }

3. Install the `Microsoft.Extensions.Logging.AzureAppServices` NuGet package.

4. Modify the `CreateHostBuilder` method of the `Program` class according to the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#azure-app-service-provider):

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddAzureWebAppDiagnostics();
                })
                .ConfigureServices(serviceCollection => serviceCollection
                    .Configure<AzureFileLoggerOptions>(options =>
                    {
                        options.FileName = "azure-diagnostics-";
                        options.FileSizeLimit = 50 * 1024;
                        options.RetainedFileCountLimit = 5;
                    }).Configure<AzureBlobLoggerOptions>(options =>
                    {
                        options.BlobName = "log.txt";
                    })
                    )
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });`

5. Use the Azure CLI to create an Azure Container Registry (ACR) and a web app:

        az login
        az group create --name rg-test
        az configure --defaults group=rg-test
        az configure --defaults location=northeurope
        az appservice plan create --name plan-test --is-linux --number-of-workers 1 --sku B2
        az acr create --name <acr-name> --sku Basic --admin-enabled

        docker build -f "C:\ProjectFolder\SampleApp\Dockerfile" "C:\ProjectFolder\SampleApp" 
            -t sampleapp
        az acr login --name <acr-name>
        docker tag sampleapp <acr-name>.azurecr.io/sampleapp:latest
        docker tag sampleapp <acr-name>.azurecr.io/sampleapp:1
        docker push <acr-name>.azurecr.io/sampleapp:1

        az webapp create --name <webapp-name> 
            --plan plan-test 
            --deployment-container-image-name <acr-name>.azurecr.io/sampleapp:1 
            --docker-registry-server-user <acr-name> 
            --docker-registry-server-password 88Tt4r/X3zcqxQoASpvL3bWDKATnb8IQ

        az webapp log config --name <webapp-name> 
            --application-logging 
            --detailed-error-messages 
            --docker-container-logging filesystem 
            --failed-request-tracing 
            --level information 
            --web-server-logging filesystem`

4. Browse to http://&lt;webapp-name&gt;.azurewebsites.net/weatherforecast.

5. Try to find the log message using the Cloud Explorer in Visual Studio or the REST API at https://&lt;webapp-name&gt;.scm.azurewebsites.net/.

If I add a console logger by calling `logging.AddConsole()` right after `logging.ClearProviders()` in the `CreateHostBuilder` method, the log message gets written to the `*_default_docker.log` file and is displayed under Settings->Container Settings in the Azure portal but the `AzureAppServicesFile` provider doesn't seem to work as expected and documented.

The same issue has been reported on Stackoverflow [here](https://stackoverflow.com/questions/59592417/how-to-configure-azure-app-service-logging-provider-for-an-asp-net-core-app).

**Comment by adamtuliper** [comment]
Same question here, working through an issue now with logging in Azure and trying to find the best way to do this from a Linux container in an app service. We already log to app insights, but also want the standard logs to show our log data

**Comment by shirhatti** [comment]
I'm closing this issue since this isn't the idiomatic way to get to your application logs in AppService Linux. The guidance is emit your logs using the Console Logger.

If you want your logs available in your Azure Storage account, use the diagnostic settings blade to archive your logs to a storage account.

![image](https://user-images.githubusercontent.com/4734691/129631537-cc9058c2-3a25-47a4-a9cb-4a09f08e4206.png)
