### ISSUE TITLE
Blazor WebSocket error on Windows and Apache

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#26907]
I noticed that route navigation stops working after going to a different browser tab and then back to the Blazor app tab. I checked the console and see these errors that I don't get during development (on macOS).

> WebSocket connection to 'wss://MyURL/_blazor?id=d-c3S6Gm041nZqCHhtBcGQ' failed: Unexpected response code: 200
> Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.

### Further technical details
- ASP.NET Core version: 3.1.8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're working on [reverting a change](https://github.com/dotnet/aspnetcore/pull/26894) in a 3.1 patch, which would result in similar behavior. Can you please review the related issue and see whether that's what's you're facing.
if not, please share more details about your scenario (how you're switching tabs - programmatically or not) and a small repro app to help us investigate this further.

**Comment by mrlife** [comment]
@mkArtakMSFT I'm seeing this above error on page load. Then again about 2 minutes later without interacting at all with the page. Then a third time about 2.5 minutes after that. A second after that third set of errors, there's this error. This is without interacting with the page at all after loading it.

> Error: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> Error: Circuit has been shut down due to error.

From reading the related issue, I'm not sure since I'm not interacting with the page at all. Does the new information in this comment help?

**Comment by mkArtakMSFT** [comment]
Thanks for additional details, @mrlife.
It looks like there may be some misconfiguration with your Apache server. have a look at the [How to deploy](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1) docs - they may help.

**Comment by mkArtakMSFT** [comment]
Closing this as there doesn't seem to be anything for us to do here.

**Comment by mrlife** [comment]
@mkArtakMSFT Thanks, I didn't realize Blazor had specific requirements beyond hosting ASP.NET Core apps.
