### ISSUE TITLE
MAUI (UI design) Studio for .NET 6

### ISSUE THREAD

**Issue by rodmac1** [dotnet/aspnetcore#26918]
PROBLEM
The design surface for ASP.NET in Visual Studio is falling further behind compared to Google's approach with Flutter. The design pane does not render a page as it should look, is limited in terms of styling and is currently unstable - format a section of an ASP.NET page, make a few edits and do a few undos/redos and you'll see what I mean.

SUGGESTION
I would like to see a best in class UI design tool aka 'MAUI Studio' for building HTML/SVG/XAML front ends, something akin to Flutter and supported by graphics design software companies e.g. Corel Corporation and Adobe.

**Comment by mkArtakMSFT** [comment]
@danroth27 can you please take a look at this? Thanks!

**Comment by danroth27** [comment]
Hi @rodmac1. We don't have any plans to build a visual designer for ASP.NET Core. Our team focus primarily on framework investments. We are however planning to invest in [hot reload](https://github.com/dotnet/aspnetcore/issues/18486) so that you can see the impact of your changes as you make them during development.

**Comment by rodmac1** [comment]
Hi Daniel. I really don't get what MS is up to anymore, it has just become another IBM to me. You've given up on the Windows moniker (your shop window - screens everywhere), failed on mobile and Edge is going nowhere. Hot reload will do nothing to change this and Google and Apple will retain the crown. The only UI/UX effort is Surface+Office or Xbox. Clearly Office is mega revenue but the rest is totally bizarre when I believed until now you could have delivered to screens everywhere. But today I'm clear on one thing - it's time to dump VS and C# and invest time in Dart & Flutter. Without a compelling UI front end in what is visually a very competitive market, and indeed that is what attracted me to the VS story in the first place, I simply don't feel I can promote my services using the MS tool stack anymore. It's been quite clear to me the control vendors are shifting towards Flutter too. I appreciate you getting back to me and wish you good luck. Rod

**Comment by danroth27** [comment]
Hi @rodmac1. I may have missed something, but does Flutter have a visual designer experience like you are requesting? I thought they also provide a hot reload experience similar to what we are working on. I did find [Flutter Studio](https://flutterstudio.app/), but it seems to come from a third party. There are third party offerings for rapid app development with Blazor. [Radzen](https://radzen.com) is one that I'm aware of. It's just not an area our team has decided to invest in - instead our focus is on making the ASP.NET Core & Blazor frameworks as good as we can, and then let the community innovate on top of that.

**Comment by rodmac1** [comment]
Hi Daniel,

I hear you and get the direction. The problem you face is there's nothing
out there that quite puts out enough icing to cover the cake you're baking.

I used to love CorelDraw. Imagine drawing a button control just as you
wanted it to appear, double clicking on it and building upon your Blazor or
MAUI framework!

I remember when I first walked into a PC shop back in the early '80s - and
saw Windows 2 - and it was "wow"! I remember back in the mid '90s dragging
and dropping a VB control onto a Windows form at night school, double
clicking and starting coding - another "wow". What I was seeing was real
visual innovation, and I could create on top of this! .NET Birmingham (UK)
2000 another "wow" (actually I'll lay claim to sowing the seeds for C# via
your Michael Edwards back in the late 90's through my continued 'terrier'
dialogue and crazy ideas). I was MS critical but MS enthusiastic too.
Actually I've been a Windows enthusiast ever since Window 2, but have felt
MS lost their 'visual compass' in the mobile era - always trying to copy
and never to innovate - and their confidence to market Windows and all
things visual. It's often not enough to copy a competitor, but to deliver
do something truly original. Blazor begins to rekindle that spirit.

The issue with CSS and indeed XAML is they are pigs to render and position
elements from scratch, get very complex very quickly, and that is where
design tools are really needed. 3 of the 4 main vendors I know of have let
me play around with their Blazor controls. Every one of them falls over on
CSS styling. In fact I told Telerik over a 50 minute interview (hey, they
gave me an Amazon voucher) they needed your support so they could go out
and create some design tools with a WYSIWYG output. But I really do believe
you need a player like Adobe or CorelDraw to help you deliver. The most
interesting of the controls bunch is Infragistics with their 'design to
code' offering and already they've latched onto some of my comments thro'
your columns.

I see a whole bunch of screens out there and an opportunity not to
get too fouled up on mobile failure, but rather to go out there and fill
them up! Forgive me if I have appeared somewhat zealous or wanting for
features that are never going to happen, but give up waiting for Google to
do something first and innovate, innovate, innovate!

Best,
Rod
