### ISSUE TITLE
Add an AddOpenIdConnect extension that accepts generic TOptions : OpenIdConnectOptions

### ISSUE THREAD

**Issue by osagga** [dotnet/aspnetcore#26919]
The current list of `AddOpenIdConnect` AuthenticationBuilder extensions only support taking in actions to configure the `OpenIdConnectOptions` type

https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs#L70

https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs#L55

https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs#L41

This pattern is very limiting, since it makes it messy to support multiple OIDC providers, each with a different options configuration (that's configured individually using the `ConfigureOptions` pattern to take advantage of Dependency Injection when setting the client id/secret). This causes complications like the ones mentioned in https://github.com/dotnet/aspnetcore/issues/11972.

One possible solution that would fix this issue and improve the extensions is to add an extension that takes in a generic `TOptions` type that's derived from `OpenIdConnectOptions`, that way the user can do something like

```c#
services
    .AddAuthentication()
        .AddOpenIdConnect<GoogleOpenIdConnectOptions>("Google")
        .AddOpenIdConnect<MicrosoftOpenIdConnectOptions>("Microsoft")
```

And setup the options configure for each option separately, without worrying about setting up a single options configure class to handle both of them.

This pattern is similar to how the OAuth extensions are already setup here:
https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OAuth/src/OAuthExtensions.cs#L59-L61

https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OAuth/src/OAuthExtensions.cs#L46-L48

Its also what the OAuth-based Google, MicrosoftAccount packages take advantage of here:
https://github.com/dotnet/aspnetcore/blob/697b397b9b764b2b1aaa3488ecbed01183cdd5cd/src/Security/Authentication/MicrosoftAccount/src/MicrosoftAccountExtensions.cs#L21-L22
https://github.com/dotnet/aspnetcore/blob/697b397b9b764b2b1aaa3488ecbed01183cdd5cd/src/Security/Authentication/Google/src/GoogleExtensions.cs#L21-L22

I can work on a PR that adds the generic extension to the list of extensions [here](https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs#L15), but let me know if I'm missing something, or if there's a reason why this wasn't added already.

**Comment by Tratcher** [comment]
So `.AddOpenIdConnect<GoogleOpenIdConnectOptions>` would still still want an `Action<GoogleOpenIdConnectOptions>` paramter to configure the options like OAuth does, right?

> (that's configured individually using the ConfigureOptions pattern to take advantage of Dependency Injection when setting the client id/secret)

Can you expand on this and include examples? You need to be careful with the various ConfigureOptions patterns, named options, etc.. They also have implications for service lifetimes.

**Comment by osagga** [comment]
>So .AddOpenIdConnect<GoogleOpenIdConnectOptions> would still still want an Action<GoogleOpenIdConnectOptions> paramter to configure the options like OAuth does, right?

Yeah sorry I didn't implicitly write the full signature, but it would be something like this:
```
public static AuthenticationBuilder AddOpenIdConnect<TOptions>(this AuthenticationBuilder builder, string authenticationScheme, string displayName, Action<TOptions> configureOptions)
            where TOptions : OpenIdConnectOptions, new()
        {
            ...
        }
```

>Can you expand on this and include examples? You need to be careful with the various ConfigureOptions patterns, named options, etc.. They also have implications for service lifetimes.

I'll explain how my code setup was, and how I was affected by this when migrating from OAuth to OpenIdConnect.

I'm working on application that needs to support multiple SSO providers (`Google` and `Microsoft` for now, could be more later), I started by using the `Microsoft.AspNetCore.Authentication.MicrosoftAccount` and `Microsoft.AspNetCore.Authentication.Google` packages (as recommend in the docs [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-3.1&tabs=visual-studio)).

To setup the options for both of those providers, I couldn't use the configuration provider `IConfiguration` since I need to load up the client id/secret from AWS's secrets manager, (AWS doesn't have an official Configuration provider built to load up secrets through the configuration interface).

So I register the providers like this
```c#
services
                .AddAuthentication()
                    .AddGoogle()
                    .AddMicrosoftAccount();
```

And I created the following classes to setup both the `GoogleOptions` and `MicrosoftAccountOptions`

`ConfigureGoogleAuthenticationOptions.cs`
```c#
public class ConfigureGoogleAuthenticationOptions : IConfigureNamedOptions<GoogleOptions>
```

`ConfigureMicrosoftAccountAuthenticationOptions.cs`
```c#
public class ConfigureMicrosoftAccountAuthenticationOptions: IConfigureNamedOptions<MicrosoftAccountOptions>
```

And I regsietred both classes as follows in the `Startup.cs`
```c#
services.ConfigureOptions<Configuration.ConfigureGoogleAuthenticationOptions>();
services.ConfigureOptions<Configuration.ConfigureMicrosoftAccountAuthenticationOptions>();
```

Now I'm able to setup the options in whichever way I want (using dependency injection to get the values from AWS secrets manager) and life was good.

But then I started to require more scopes and also saw https://github.com/dotnet/aspnetcore/issues/10037#issuecomment-678358952 and https://github.com/dotnet/aspnetcore/issues/6486, and the conclusion was that I should probably migrate to OIDC based authentication, instead of OAuth. I tried to see if `Microsoft.AspNetCore.Authentication.MicrosoftAccount` or `Microsoft.AspNetCore.Authentication.Google` upgraded to be OIDC based, but there were still using OAuth, so I decided to just setup the OIDC handlers myself, but the big issue I noticed is that the OIDC extensions don't support using custom options type (derived from `OpenIdConnectOptions`), so my setup would not work as it's right now. So after looking more into it, I just went with something like this

```c#
services
                .AddAuthentication()
                    .AddOpenIdConnect("Google", o =>
                        {
                            ServiceProvider serviceProvider = services.BuildServiceProvider();
                            var _secretProviderService = serviceProvider.GetService<ISecretProviderService>();
                           
                            // ... code omitted for simplicity ...

                            // get the secret from the secret provider
                            var googleOAuthSecret = _secretProviderService.GetSecretJSONAsync<GoogleOAuthSecret>(googleOAuthSecretName).Result;

                            o.ClientId = googleOAuthSecret.ClientId;
                            o.ClientSecret = googleOAuthSecret.ClientSecret;

                            // ... code omitted for simplicity ...

                            serviceProvider.Dispose();
                        }
                    ).AddOpenIdConnect("Microsoft", o =>
                        {
                            ServiceProvider serviceProvider = services.BuildServiceProvider();
                            var _secretProviderService = serviceProvider.GetService<ISecretProviderService>();

                            // ... code omitted for simplicity ...

                            // get the secret from the secret provider
                            var microsoftOAuthSecret = _secretProviderService.GetSecretJSONAsync<GoogleOAuthSecret>(microsoftOAuthSecretName).Result;

                            o.ClientId = microsoftOAuthSecret.ClientId;
                            o.ClientSecret = microsoftOAuthSecret.ClientSecret;

                           // ... code omitted for simplicity ...

                            serviceProvider.Dispose();
                        }
                    );
```

This setup works, but kinda annoying that I had to build the service provider myself, it also generates a warning (since I'm creating multiple instances of a singleton service, but I'm disposing it at the end, so hopefully its fine). So that's why I created this issue, to see if its possible that I add that generic extension, which should fix my setup to go back to the way it was before.

Let me know if you have any questions, and if there's an easier way that I'm not seeing. Thanks!

**Comment by Tratcher** [comment]
> but kinda annoying that I had to build the service provider myself, 

In fact you should _never_ be calling BuildServiceProvider as it messes up the service lifetimes.

So what this new generic options extension unblocks is this?
```
public class ConfigureMicrosoftOpenIdConnectOptions: IConfigureNamedOptions<MicrosoftOpenIdConnectOptions>
{
    public ConfigureMicrosoftOpenIdConnectOptions(ISecretProviderService dependency) { }
```

Which you could mostly do today, but you'd need to check the options names first?
```
public class ConfigureOpenIdConnectOptions: IConfigureNamedOptions<OpenIdConnectOptions>
{
    public ConfigureOpenIdConnectOptions(ISecretProviderService dependency) { }
```

**Comment by osagga** [comment]
>In fact you should never be calling BuildServiceProvider as it messes up the service lifetimes.

Oh no, I guess I should address this soon, thanks for the heads up, any more documentation about what exactly is wrong with calling `BuildServiceProvider`?

> So what this new generic options extension unblocks is this?

Yes

> Which you could mostly do today, but you'd need to check the options names first?

I'm honestly not too familar with named options, I know they exist, but I kinda tried to avoid using them, its also not clear what name will be passed to the options when configured, is it `authenticationScheme`, `displayName` from this extension?
https://github.com/dotnet/aspnetcore/blob/8b741bd9c6a2a89f1bf373a26fed7eefc9a9a400/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectExtensions.cs#L70

I honestly still prefer if I can pass completely different option types (for each provider, like I had it before), and split the configuration based on that, since it gives me better class management, and separation of provider specific options setup. It would also allow me to create extensions like the `.AddGoogle()` and `.AddMicrosoftAccount()` that I can build (or update in this repo) to be OIDC based. What do you think?

**Comment by Tratcher** [comment]
The name passed in would be the authenticationScheme.

**Comment by Tratcher** [comment]
An new extension like this wouldn't be added until at least 6.0, a year from now, so let's see what can be done with named options first.

**Comment by blowdart** [comment]
@tratcher While you're looking at named options, I'm putting this into discussions. If it can't be done that way, then it can go into next sprint planning for 6.
