### ISSUE TITLE
.Net 5 RC2 Blazor Wasm PWA service worker not working correctly with "pwa-update" component during local development

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#26916]
In a brand new .Net 5 RC2 Blazor Wasm PWA project, I wanted to use the ["pwa-update"](https://github.com/pwa-builder/pwa-update) component from the PWABuilder team, to provide a nicer update experience to my users. I have used this same component in .Net Core 3.1 in the past. 

So inside the index.html, I replaced this line of code:

`<script>navigator.serviceWorker.register('service-worker.js');</script>`

with 

```
<script type="module">
        import 'https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate';
</script>
<pwa-update updatemessage="An update for the app is available" swpath="service-worker.js"></pwa-update>
```
Now, even during local development, when I update any code, I get a message: "An update for the app is available". When I inspect the generated service worker (service-worker.js) in the browser, I see that manifest version timestamp is changing between each rebuild e.g.:

`/* Manifest version: L2M+eiM3 */`

This is distracting to the developers when developing locally, so is it possible to generate the unique manifest version in the service-worker.published.js only, rather than in service-worker.js. Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You can set the version to a constant value for a debug build by setting the `ServiceWorkerAssetsManifestVersion` property in your `.csproj` file.
