### ISSUE TITLE
Static site generator like VuePress, Hexo etc.

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#26929]
I thought it would be awesome to build a static site generator based on Blazor for documentation and static blogs.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is something which came up few times. While this is a good idea, this is not something we would like to make part of the framework at the moment. You can see how similar conversations evolved in the past by reading through https://github.com/dotnet/aspnetcore/issues/5658 and https://github.com/dotnet/aspnetcore/issues/14581.

**Comment by hikalkan** [comment]
We've created an open source project that reads content from a GitHub repository (with Markdown format) and generates a documentation web site like https://docs.abp.io/
Actually, the web site is not static, but it can be something you may interest in. It is built with AspNet Core Razor Pages, not Blazor.
(there is a document to explain how to use it: https://docs.abp.io/en/abp/latest/Modules/Docs)
