### ISSUE TITLE
Blazor Wasm Hosted Signalr Core Error 'WebSocket connection failed: HTTP Authentication failed; no valid credentials available' after upgrade from .net 5 rc1 to rc2

### ISSUE THREAD

**Issue by seraj654** [dotnet/aspnetcore#26926]
### Describe the bug
In blazor wasm i try to connect to a hub. and i use IAccessTokenProvider. in rc1 everything works fine... but after upgrade to .net 5 rc2, I have error in console. 
This error : "WebSocket connection failed: HTTP Authentication failed; no valid credentials available" full error paste bellow...
i try change transport to LongPolling... then fixed!

this code have error:

`_hubConnection = new HubConnectionBuilder()
                .WithUrl(NavigationManager.ToAbsoluteUri("/userHub"),
                    options =>
                    {
                        options.AccessTokenProvider = () => Task.FromResult(token.Value);
                    })
                .WithAutomaticReconnect()
                .Build();`

and this code doesn't:

`_hubConnection = new HubConnectionBuilder()
                .WithUrl(NavigationManager.ToAbsoluteUri("/userHub"),
                    options =>
                    {
                        options.Transports = HttpTransportType.LongPolling;
                        options.AccessTokenProvider = () => Task.FromResult(token.Value);
                    })
                .WithAutomaticReconnect()
                .Build();`

### Exceptions
dotnet.5.0.0-rc.2.20475.5.js:1 WebSocket connection to 'wss://localhost:44350/contactHub?id=5rtvHSpPP-wypw6I9DUF0A&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MDI3NTEzMTMsImV4cCI6MTYwMjc1NDkxMywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNTAiLCJhdWQiOiJDaGF0b3J5LlNlcnZlckFQSSIsImNsaWVudF9pZCI6IkNoYXRvcnkuQ2xpZW50Iiwic3ViIjoiNzNjNmQzYzgtZjM0ZS00M2JjLWIwMjAtNWQzZThjN2M3OTliIiwiYXV0aF90aW1lIjoxNjAyNzQ5MjU2LCJpZHAiOiJsb2NhbCIsImp0aSI6Ijg5MUJBNzcwQjlCRkMwQzk0ODNDNUQ5REVDNDgzREM5Iiwic2lkIjoiOEY1NjgzOENDNENERjUxQUQwNEFFMkMzMjI0RUI0RDEiLCJpYXQiOjE2MDI3NTEzMTMsInNjb3BlIjpbIkNoYXRvcnkuU2VydmVyQVBJIiwib3BlbmlkIiwicHJvZmlsZSJdLCJhbXIiOlsicHdkIl19.Nba-aRBMRB9oabJ3nFSziX_4YZK9duMA2ikoDNWsn7zAXnCTn0MLwEl5wM8riHH5wupqY8N8eS874mHN34WXtz7119bEHKGNdy_ZyqsSk7BbyOV4s_ZXgaJOci2V4F1yWbdSn5c9F9NZmNzRTeoCZFgS1gs37D-UGGgwj55gqpsILwg7CuAadmPI1e5nU0KwxrgXRQ6udAD-DxSaiKK_p9u6_C-fonFm7skjjq9m9B6jx8qYrtHnzRc8R14Xch-KBQwGp9d-tbOxjhMD8DHHF7PrW1uU21RsL6rm4iD6pTn2uYVvnT_P7xFrZLWx4lTq_UhdgiNPGvWvwnb1rbJsXQ' failed: HTTP Authentication failed; no valid credentials available

### Further technical details
- ASP.NET Core version : Asp .Net Core 5 RC2
- Microsoft Edge

**Comment by BrennanConroy** [comment]
Can you get the server side logs (debug level) and see if there are any errors with auth?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging

**Comment by seraj654** [comment]
`
IdentityServer4.Events.DefaultEventService: Information: {
  "ClientId": "Chatory.Client",
  "ClientName": "Chatory.Client",
  "Endpoint": "Token",
  "SubjectId": "73c6d3c8-f34e-43bc-b020-5d3e8c7c799b",
  "Scopes": "Chatory.ServerAPI openid profile",
  "GrantType": "authorization_code",
  "Tokens": [
    {
      "TokenType": "id_token",
      "TokenValue": "****wCbw"
    },
    {
      "TokenType": "access_token",
      "TokenValue": "****79zA"
    }
  ],
  "Category": "Token",
  "Name": "Token Issued Success",
  "EventType": "Success",
  "Id": 2000,
  "ActivityId": "80000088-0002-ff00-b63f-84710c7967bb",
  "TimeStamp": "2020-10-16T13:42:21Z",
  "ProcessId": 2648,
  "LocalIpAddress": "::1:44350",
  "RemoteIpAddress": "::1"
}
IdentityServer4.Hosting.IdentityServerMiddleware: Information: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.UserInfoEndpoint for /connect/userinfo
IdentityServer4.ResponseHandling.UserInfoResponseGenerator: Information: Profile service returned the following claim types: sub preferred_username name
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: New connection RtyEtR9UQAnaPXpco8ZrhA created.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Sending negotiation response.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: New connection OSl5KXSVv9Mnd4UpJ_Xq3g created.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Sending negotiation response.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Establishing new connection.
Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync started.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Establishing new connection.
Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync started.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Resuming existing connection.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver: Debug: Found protocol implementation for requested protocol: json.
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Completed connection handshake. Using HubProtocol 'json'.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Resuming existing connection.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver: Debug: Found protocol implementation for requested protocol: json.
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Completed connection handshake. Using HubProtocol 'json'.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Resuming existing connection.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Resuming existing connection.
`

**Comment by BrennanConroy** [comment]
Why are there 2 connections? And which one failed?

What browser are you using?
How is your auth configured?

**Comment by seraj654** [comment]
I have 3 hubs...
Chrome, Edge, FireFox
Identity Server 4 - Blazor Wasm Hosted Template - no any additional configuration. 

Just web socket Transport have problem after upgrading to RC2.

**Comment by BrennanConroy** [comment]
Are you grabbing the access token from the query string for your auth?

I'm guessing you need to do something similar with Identity Server as we show for JwtBearer https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#bearer-token-authentication
