### ISSUE TITLE
Enhance JsonPatchDocument Support: Generator and Ability to Detect Changes

### ISSUE THREAD

**Issue by JacobAtchley** [dotnet/aspnetcore#26922]
It would be really nice if the framework "out of the box" supported generating a patch document from two objects.
example:
`var patchDocument = new JsonPatchDocument(original, modified)`

It would also be nice to know if the `.ApplyTo` function could tell you if any fields were changed.
This way you could reduce another trip to the data store to persist the changes. 

example: 
```
var wasModified = jsonPatchDocument.ApplyTo(viewModel);

if(wasModified)
{
    repo.Save(viewModel);
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to make part of the framework. We this this is a better fit for an external library, perhaps a community project.
