### ISSUE TITLE
Blazor E2E tests don't run after building from VS (but do from commandline)

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#26930]
There's something wrong with copying the SWA manifest when building from VS. It shows up at `artifacts\bin\Components.TestServer\Debug\net6.0`, but the E2E test application actually runs from `src\Components\test\E2ETest\bin\Debug\net6.0`. @javiercn says the file is meant to be copied as part of the build process, but this only happens when building from the commandline, not from VS.

The result is that all the WebAssembly E2E tests, and many of the Server E2E tests, fail because the browser can't load the initial page, because assets like `blazor.webassembly.js` can't be loaded.

**Comment by HaoK** [comment]
@SteveSandersonMS are you still seeing issues with this?  I just tried running the tests in VS today and things seemed fine:

I did a VS build of functional tests, and there was a weird issue where VS wouldn't run the tests until I restarted VS, but I was able to run all the functional tests in VS after restarting VS via startvs.cmd

**Comment by SteveSandersonMS** [comment]
It's been a while since I last tried it. I'll reopen this if it happens again when I next try it.

**Comment by javiercn** [comment]
I think we collaterally fixed this as part of another fix we did to static web assets in the past, but I might be wrong. I haven't experienced it either in a long time.

**Comment by SteveSandersonMS** [comment]
Unfortunately this does not appear to be fixed.

To reproduce the issue, the important thing is to make a change to the tests and do the build from inside VS, not on the command line. It won't repro if you have previously built in the command line and then didn't change the tests.

**Comment by SteveSandersonMS** [comment]
@HaoK @mkArtakMSFT Reopening as per above.

**Comment by HaoK** [comment]
Thanks for figuring out the repro steps @SteveSandersonMS I'll take a look this week

**Comment by HaoK** [comment]
Repro steps: Delete bin directory in Components.E2E, In VS: run only both RenderMarkupBlock tests, see that Server version passes, WASM version fails (due to missing static assets, 404 errors)

**Comment by javiercn** [comment]
@HaoK is the `<<project>>.staticwebassets.xml` file being copied to the output folder?

**Comment by HaoK** [comment]
I see the Wasm.Authentication.Client/Server ones, but yeah the new files that show up when you build on command line are StandaloneApp.StaticWebAssets.xml, TestContentPackage.StaticWebAssets.xml and Wasm.Performance.TestApp.StaticWebAssets

**Comment by HaoK** [comment]
Interesting, yeah so if I delete everything from the bin directory, none of the static web assets are regenerated when VS runs

**Comment by HaoK** [comment]
@javiercn found the issue and has the fix PR in https://github.com/dotnet/sdk/pull/15917
