### ISSUE TITLE
Update ASP.NET Core Engineering Guidance

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#26937]
We've changed our philosophy over time regarding what are the best practices, but we never reflected on that in our [Engineering Guidance](https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines#when-to-use-internals-vs-public-and-when-to-use-internalsvisibleto) document.

We'll use this issue to review the doc and update it.

**Comment by pranavkm** [comment]
Done as part of https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines/58147322248af4148149d70aa4c19c7d1efada67
