### ISSUE TITLE
Remove MusicStore (E2E tests have been disabled since Mar 2019)

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26940]
https://github.com/dotnet/aspnetcore/blob/master/src/MusicStore/test/MusicStore.E2ETests/MusicStore.E2ETests.csproj#L10.

**Comment by mkArtakMSFT** [comment]
Given that these tests have not been running for this long, they seem to add no value. We already have alternative mechanisms for testing.
@BrennanConroy, @Tratcher, @davidfowl let us know if you have a good argument against this.

**Comment by Tratcher** [comment]
> We already have alternative mechanisms for testing.

What else covers this level of integration testing?

**Comment by pranavkm** [comment]
CTI tests have been used to capture some of the E2E scenarios we previously had with MusicStore. Are there scenarios these tests cover that aren't captured by CTI (I know for example targeting specific operating systems such as Windows Server Nano is one of them)? If they are reasonable we should consider adding CTI coverage for it.

**Comment by Tratcher** [comment]
FYI there's an outstanding ask to remove the OAuth credentials from the app because they're trigger automated alerts.
https://github.com/dotnet/aspnetcore/blob/f83817e183f705825c829dc058a2304709b23358/src/MusicStore/samples/MusicStore/Startup.cs#L87-L121

We should just remove the whole app at this point.

**Comment by blowdart** [comment]
Agree with Chris, it's simpler from a compliance perspective to kill it, making it compliant would involve moving creds to an approved secret mechanism, and then putting the creds for the secret mechanism in a deployment pipeline which you'd need to keep up to date.

@mkArtakMSFT / @pranavkm if this could be killed as a matter of urgency it'd make life easier for the MSRC threat hunting folks  to concentrate on real issue.
