### ISSUE TITLE
Changes to *.razor.css requires an explicit build in Visual Studio to refresh

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26956]
1) Create a new Blazor app in VS
2) Try modifying a .razor file and refresh the browser without (re)building in VS.
3) Notice that the browser picks up changes
4) Do the same thing with a .razor.css file. Notice that it does not change. A Ctrl+F5 is required to pick up changes here.

**Comment by campersau** [comment]
Maybe the same as    https://github.com/dotnet/aspnetcore/issues/26843 ?

**Comment by pranavkm** [comment]
@campersau the SDK I picked up included a fix for it.

**Comment by javiercn** [comment]
@pranavkm is this still a thing?

**Comment by mkArtakMSFT** [comment]
Closed as Hot Reload mitigates this.
