### ISSUE TITLE
[Blazor Server] Component parameter with custom set accessor crashing build

### ISSUE THREAD

**Issue by cr4z** [dotnet/aspnetcore#26954]
I have a very simple problem. I have a Blazor component with a parameter. I have a get and set accessor, with custom logic on the set. But when the parent component uses the parameter, the build crashes. It only crashes whenever I use the 'value' keyword. I've also recreated this on a blank template.

I suppose that this is because 'value' isn't actually reading the value passed in by the parent component?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
