### ISSUE TITLE
Template precedence overrides order in controller routing.

### ISSUE THREAD

**Issue by CameronAavik** [dotnet/aspnetcore#26952]
### Describe the bug
I have two routes for which there exists a URL that matches both routes.
I added an `Order` to the route attribute, but the route with the higher template precedence was chosen instead.

### To Reproduce
I created a new empty ASP.NET Core 5 project with the following `Startup` and controller. Everything else in the project was left the same.

```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseRouting();
        app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
    }
}

[ApiController]
public class TestController : ControllerBase
{
    [Route("{test}", Order = 0)]
    public IActionResult OrderIsZero(string test) => Content("Order = 0");

    [Route("test", Order = 1)]
    public IActionResult OrderIsOne() => Content("Order = 1");
}
```

Steps to reproduce:
1. Run the application
1. Hit the URL `/blah`. Observe that the response is `Order = 0`
1. Hit the URL `/test`.

Expected: I see `Order = 0`
Actual: I see `Order = 1`

I expected to see `Order = 0` because the two routes both match the attribute, and according to the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#url-matching) the order is prioritised higher than the template precedence.

> The list of endpoints is prioritized according to:
> - The RouteEndpoint.Order
> - The route template precedence

### Further technical details
I initially saw this issue on ASP.NET Core 3.1, but have also reproduced it on ASP.NET Core 5
Here is the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935
```

**Comment by javiercn** [comment]
@CameronAavik thanks for contacting us.

I'm unable to repro this issue, I get 0 in both cases which is what I would expect since the Order 1 trumps the higher precedence on the second route.
