### ISSUE TITLE
Blazor-WASM- CurrentCulture date formats wrong for some cultures

### ISSUE THREAD

**Issue by bignorm64** [dotnet/aspnetcore#26957]
### Describe the bug
Blazor WASM globalization & localization documentation says that the current culture is set based on the user's browser settings which does work but the values for the DateTimeFormat.ShortDatePattern and LongDatePattern are wrong for some cultures, specifcally en (NZ), en (AU), and en (GB, OXENDICT) (probably more but these are the only ones I looked at)

### To Reproduce
Include a Razor page with the following content in your Blazor WASM project and browse to the page. Then add the languages above to your browser, select one and refresh the page.

The short date formats for these cultures are all M/d/yyyy and should be d/M/yyyy and the long date formats are dddd, MMMM d, yyyy but they should be dddd, d MMMM, yyyy.

```html
@page "/localizationinfo"
<h3>Current Culture Values</h3>

<table>
    <thead>
        <tr>
            <th>Setting</th>
            <th>Value</th>
        </tr>
    </thead>
    <tr>
        <td>DisplayName</td>
        <td>@CultureInfo.CurrentCulture.DisplayName</td>
    </tr>
    <tr>
        <td>ShortDatePattern</td>
        <td>@CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern</td>
    </tr>
    <tr>
        <td>LongDatePattern</td>
        <td>@CultureInfo.CurrentCulture.DateTimeFormat.LongDatePattern</td>
    </tr>
    <tr>
        <td>AbbreviatedDayNames</td>
        <td>
            @foreach (var dayName in CultureInfo.CurrentCulture.DateTimeFormat.AbbreviatedDayNames)
            {
                var value = $"{dayName}";
                @value
            }
        </td>
    </tr>
    <tr>
        <td>CurrencySymbol</td>
        <td>@CultureInfo.CurrentCulture.NumberFormat.CurrencySymbol</td>
    </tr>
    <tr>
        <td>NumberDecimalSeparator</td>
        <td>@CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator</td>
    </tr>
</table>
```

### Further technical details
- ASP.NET Core version 5.0.100-rc.2.20479.15
- Visual Studio 2019 Preview 16.8.0 Preview 4

**Comment by campersau** [comment]
Here are two similar issues:
https://github.com/dotnet/runtime/issues/43398
https://github.com/dotnet/runtime/issues/43449
Maybe this helps: https://github.com/dotnet/runtime/issues/43398#issuecomment-709408036

**Comment by bignorm64** [comment]
Thanks @campersau I hadn't found those issues as I was only searching in this repo.

Adding 
```xml
<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
```
to the csproj file sorted it. Was rather confusing as things like the currency symbol were there but date formats were not.

From the comments on those issues looks like the documentation has been updated too but not showing just yet.

**Comment by javiercn** [comment]
@bignorm64 thanks for contacting us.

I'm closing this issue since @campersau answer is correct and you've found the solution.
