### ISSUE TITLE
Blazor - Equivalent to Vue Watch for a Parameter

### ISSUE THREAD

**Issue by ziadakiki** [dotnet/aspnetcore#26958]
Coming from a VueJS background to Blazor, I can't find an equivalent to the Vue watcher in Blazor.

To elaborate, in Vue, one could watch for changes on a certain property, for example:
```
watch: {
   somethingId(newValue) {
      // Do something, this actually watches the somethingId for change and trigger this function
   }
}
```
I can't seem to find an equivalent to Blazor, I tried to achieve that using a custom property's getter/setter but this does not work in all cases (it is actually more similar to computed properties in vue and not a watch).
I was also advised to check for `INotifyProperyChanged` but as far as I could tell this is not applicable to Blazor.

Is there a way to achieve this?

**Comment by javiercn** [comment]
@ziadakiki thanks for contacting us.

We don't provide an out of the box solution for observing model changes. The Blazor model is similar to other UI programming models in that the application needs to explicitly tell the framework when the state has changed and a re-render is required.

The best way you can likely do this is using something like `IObservable<T>` to define your properties and then register an observer on them.

**Comment by ziadakiki** [comment]
For future readers, I ended up implementing a state container (a similar concept to Vuex in VueJS) to store the common values that I'm looking to observe (instead of passing them as Parameters) and throwing events upon their changes. This is documented in [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1&pivots=webassembly#in-memory-state-container-service).

Let's say we need to watch/observe the changes to somethingId, similar to the example above:

1. Create a SomethingStateContainer class with the following:
```
public class SomethingStateContainer
{
    public event Action<int> OnSomethingIdChanged; // Or any type, here SomethingId is an int

    private int _somethingId = 0;
    public int SomethingId {
        get => _somethingId;
        set {
            _somethingId = value;
            OnSomethingIdChanged?.Invoke(value);
        }
    }
}
```
This service is then added as a singleton within the `Program.cs` (if using Blazor WebAssembly):
```
builder.Services.AddSingleton<SomethingStateContainer>();
```

2. Each component looking to listen on changes done over this variable can do so as follows:
Inject the SomethingStateContainer within the Blazor component:
```
@inject SomethingStateContainer SomethingStateContainer
```
Add an event listener (and dispose it when done):
```
protected override async Task OnInitializedAsync()
{
    SomethingStateContainer.OnSomethingIdChanged += YourCallbackFunction;
}

public void Dispose()
{
    SomethingStateContainer.OnSomethingIdChanged -= YourCallbackFunction;
}
```
Where the YourCallbackFunction is the function that you wish to execute (In this case it takes an int as an input):
```
private void YourCallbackFunction(int id)
{
    // Do something
}
```
