### ISSUE TITLE
PersistKeysToStackExchangeRedis leaks ConnectionMultiplexer ?

### ISSUE THREAD

**Issue by IB38** [dotnet/aspnetcore#26963]
Hi there,

I have a question about `Microsoft.AspNetCore.DataProtection.StackExchangeRedisDataProtectionBuilderExtensions.PersistKeysToStackExchangeRedis(this IDataProtectionBuilder builder, IConnectionMultiplexer connectionMultiplexer, RedisKey key)`

The way extension method works, it seems like it leaks ConnectionMultiplexer, there is no way to properly dispose of it? 
Its impossible to use DI for ConnectionMultiplexer because of how AddDataProtection and PersistKeysToStackExchangeRedis work. 
DataProtectionProvider doesn't take ownership either.
And obviously you can't just dispose of it after calling PersistKeysToStackExchangeRedis because that would break database factory delegate.

Am i misunderstaing something? Every code example gives lines similar to this:
```
public void ConfigureServices(IServiceCollection services)
{
    var redis = ConnectionMultiplexer.Connect("<URI>");
    services.AddDataProtection()
        .PersistKeysToStackExchangeRedis(redis, "DataProtection-Keys");
}
```
with ConnectionMultiplexer being just left out.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. According to the [documentation](https://stackexchange.github.io/StackExchange.Redis/Basics.html) the mentioned type instances are not supposed to be disposed. We are following the guidance here.
