### ISSUE TITLE
Blazor WebAssembly doesn't include custom web.config when publishing

### ISSUE THREAD

**Issue by cornem** [dotnet/aspnetcore#26965]
### Describe the bug
The [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#use-a-custom-webconfig) states:

> To use a custom web.config file, place the custom web.config file at the root of the project folder and publish the project.

However, when I add a `web.config` file to the project root, and run `dotnet publish -c Release` with .NET 5 RC2, the `web.config` isn't copied to the `publish` folder. Only the `wwwroot` folder is there.

### To Reproduce
- Create a new Blazor WebAssembly project using `dotnet new blazorwasm`
- Add a `web.config` at the project root
- Run `dotnet publish -c Release`
- Navigate to `project\bin\Release\net5.0\publish` and observe the `web.config` isn't there

### Further technical details
```console
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
Thanks @cornem for the issue report.

@vijayrkn this appears to be the result of the `PublishIISAssets` change in the Publishing SDK https://github.com/dotnet/sdk/blob/master/src/WebSdk/Publish/Targets/CopyTargets/Microsoft.NET.Sdk.Publish.FilterFiles.targets#L30-L33.

How do you feel about adding a check to the target verify that a project targets the WebSDK?:

```diff
<Target Name="_FilterIISAssets"
- Condition="'$(PublishIISAssets)' == 'false'"
+ Condition="'$(PublishIISAssets)' == 'false' AND '$(UsingMicrosoftNETSdkWeb)' == 'true'"
```

**Comment by vijayrkn** [comment]
@pranavkm I thought you mentioned that WebSdk is not used in the case of Blazor. Is that not the case?

**Comment by pranavkm** [comment]
The publishing SDK gets used though.

**Comment by vijayrkn** [comment]
Oh, I didn't know that. I thought you directly called into the targets.  In that case, adding the condition makes sense. 

Also we should add it to the default check - https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets#L33

**Comment by pranavkm** [comment]
Sounds good. I can get something ready for it.

@cornem in the meanwhile, consider setting `<PublishIISAssets>true</PublishIISAssets>` in your project file. It should help publishing the web.config without any adverse affect to your app.

**Comment by Pilchie** [comment]
@pranavkm Is there an update here? Today is the last day for changes for 5.0 without starting to affect schedule.

**Comment by pranavkm** [comment]
Sorry, we discussed this on Monday and we think updating our docs to call out this new behavior seems sufficient.

**Comment by pranavkm** [comment]
Docs added as part of https://github.com/dotnet/AspNetCore.Docs/pull/20243.

**Comment by vijayrkn** [comment]
@pranavkm - is this the short-term plan or the long term plan as well?

**Comment by pranavkm** [comment]
@vijayrkn unless we hear otherwise, we're going to recommend using this flag in user's projects.
