### ISSUE TITLE
CSS Isolation Follow-up

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#26964]
### Describe the bug

This is the follow up of CSS Isolation #26493. 
The problem remains.
The CSS style is not applied.
I have tried with and without ```::deep.```
No success.

[BlazorApp.zip](https://github.com/dotnet/aspnetcore/files/5390768/BlazorApp.zip)

PS: If I create and reference an individual CSS file with the same CSS content as the index.razor.css file, it works.

![coding](https://user-images.githubusercontent.com/16502423/96244496-6c3f2f00-0fa6-11eb-945d-93b4ca5da5eb.png)
![exemple](https://user-images.githubusercontent.com/16502423/96244499-6d705c00-0fa6-11eb-9aff-d0b33a88c4c0.png)

### Further technical details

ASP.NET Core .NET 5.0 RC2
Google Chrome Version 86.0.4240.75 
Visual Studio 16.8.0 Preview4.0
Blazor Web Assembly

**Comment by SteveSandersonMS** [comment]
When you have `::deep` at the start of a selector (for example `::deep .xxx` in your code), this will match any `.xxx` element that is nested inside any element rendered by your component. But it does *not* match `.xxx` elements that are not nested inside any element rendered by your component.

That's what's happening here. If you look in your rendered DOM structure, the `<input class="xxx">` is *not* nested inside any element rendered by `Index.razor`.

To fix this, you need to change `Index.razor` to wrap any element around its output. For example change it to:

```razor
<div>
    <EditForm ...>
        <InputText ... />
    </EditForm>
</div>
```

This is a bit of a weird edge case with CSS scoping and `::deep`, so we'll add info about it to the docs. Thanks for pointing this scenario out!

**Comment by boukenka** [comment]
@SteveSandersonMS Thanks! Closing the issue then. 😄
