### ISSUE TITLE
Upgrade to Net 5.0 nightly build errors 

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#26969]
### Describe the bug
We are trying to maintain a separate branch of our project with the latest .Net 5.0 nightly build as of every Friday.  This has been working up until today.  I am receiving multiple errors after upgrading the versions today.

I have been following:  https://github.com/dotnet/installer
- 5.0.100 RTM Installer for Windows x64
- Added the nuget package source: <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />

### Further technical details
- Visual Studio Version 16.8.0 Preview 4.0

PS C:\Users\rsurles> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rtm.20515.8
 Commit:    d4436c7f87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rtm.20515.8\

Host (useful for support):
  Version: 5.0.0
  Commit:  2d8e19f188

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100-rtm.20515.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

Errors:

![image](https://user-images.githubusercontent.com/37274814/96269431-fa5beb00-0f8f-11eb-81e7-68c159a10692.png)

Project file:

![image](https://user-images.githubusercontent.com/37274814/96269577-2aa38980-0f90-11eb-86cc-54e993666057.png)

**Comment by javiercn** [comment]
@roysurles thanks for contacting us.

@dotnet/aspnet-build can you help out here?

**Comment by wtgodbe** [comment]
The issue is that the stable packages aren't available on the usual feeds yet. Once we switch to stable branding, we have to publish every build to a new, unique feed per build, since we do multiple stable builds of each repo, so if we published each one to the same feed, the newest would overwrite the previous feeds. Until we actually ship RTM, you won't be able to access the stable packages without doing some very specific magic to find the feeds where each stable package exists. I recommend downgrading to the SDK you were using before, and only using the RTM SDK once we actually ship it publicly.

**Comment by roysurles** [comment]
What is the exact version number of .Negt 5.0 RC2?  And What is the nuget package source for this?

File --> New Project --> Blazor WebAssembly 5.0 has numerous errors and does not even run?

![image](https://user-images.githubusercontent.com/37274814/96290424-2e450980-0fac-11eb-9594-39e6bb8f3336.png)

![image](https://user-images.githubusercontent.com/37274814/96290458-3c932580-0fac-11eb-8331-143279e08642.png)

**Comment by wtgodbe** [comment]
Apologies, I hope you were able to find a workaround for this - .Net 5 has just been released, so you should now be able to upgrade to that: https://dotnet.microsoft.com/download/dotnet/5.0
