### ISSUE TITLE
TextMate classifications occasionally override semantic classifications.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#26975]
This is a tracking issue for the Core editor: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1184616

**Comment by ryanbrandenburg** [comment]
Once this is done we need to revert the workaround portions of https://github.com/dotnet/aspnetcore-tooling/pull/2954/files. That means un-commenting all the elements in the TextMate grammar and make VisitMarkupLiteralAttributeValue return a MarkupAttributeValue instead of a quote.
