### ISSUE TITLE
HttpSysRequestDelegationFeature - DelegationRule.Dispose() - Call to HttpCloseUrlGroup Fails with result ERROR_INVALID_PARAMETER

### ISSUE THREAD

**Issue by NGloreous** [dotnet/aspnetcore#26989]
### Describe the bug
I'm still looking into the details of why this is failing with a result of 87 (ERROR_INVALID_PARAMETER). Regardless I'm not even sure this call should be made for cases when the caller attached to the URL group because it was created by someone else. 

### To Reproduce
Need to run this code on a preview version of vNext Windows and you'll also need the fix in PR #26983 otherwise you'll hit the nullref issue.

```C#
namespace Sample
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            var delegator = app.ServerFeatures.Get<IServerDelegationFeature>();
            var rule = delegator.CreateDelegationRule("DefaultAppPool", "http://*:80/");
            rule.Dispose();
        }
    }
}
```

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Server.HttpSys.MessagePump[21]
      HttpCloseUrlGroup; Result: 87
```

**Comment by Tratcher** [comment]
Which specific windows build number did you test?

**Comment by NGloreous** [comment]
I'm currently testing on 20239 from the base2 branch but I've hit it on other builds also. I can try a recent preview next week just to make sure it's still an issue there.

**Comment by shirhatti** [comment]
I'm on 20190 from public insiders and I'm not seeing it. It must have been one of the recent changes

**Comment by NGloreous** [comment]
Got confirmation from the http.sys dev that we shouldn't be calling HttpCloseUrlGroup on this URL since the process didn't create it we are just using it. The ERROR_INVALID_PARAMETER error is coming from an access check that fails since this process didn't create it

**Comment by shirhatti** [comment]
The reason it doesn't repro in the current test is because both the delegator and delegatee are in the same process 🤦‍♂️
