### ISSUE TITLE
Unable to use serilog in API hosted in Windows Service. Error 1053

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26986]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1208000/unable-to-use-serilog-in-api-hosted-in-windows-ser.html)._

---
[severity:It's more difficult to complete my work]
I have create a .net core 3.1 API project and am hosting this in a Windows Service (windows 10 latest).

When I start my project from Visual Studio, my API runs as a console application and performs the configured API functionality and logging without problem. When I register that same .exe as a windows service, the service will not start. When I remove serilog configuration from the Main method in Program.cs file, the windows service starts and works as expected. Specifically, when I comment out the line  "var config = builder. Build();" and republish the project, my service will start normally. Any help would be much appreciated.

public static void Main(string[] args)
        {
            var builder = new ConfigurationBuilder();
            BuildConfig(builder);
            var config = builder. Build();
            string logdbPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + @"\EPDAPI\log.db";

Log.Logger = new LoggerConfiguration()
                . ReadFrom.Configuration(config)
                . Enrich.FromLogContext()
                . WriteTo.SQLite(logdbPath)
                . CreateLogger();

Log.Logger.Information("Application Starting");

EnableDapperCustomTypeHandlers();

CreateHostBuilder(args)
                . UseWindowsService()
                . UseSerilog()
                . Build()
                . Run();

}

public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                    . ConfigureServices((context, services) =>
                    {
                        services. AddSingleton<ISQLiteDataAccess, SQLiteDataAccess>();
                        services. AddSingleton<IContactData, ContactData>();
                        services. Configure<KestrelServerOptions>(context. Configuration.GetSection("Kestrel"));
                    })

. ConfigureWebHostDefaults(webBuilder =>
                    {
                        webBuilder.ConfigureKestrel(serverOptions =>
                        {
                            // Set properties and call methods on options
                        })
                        . UseStartup<Startup>();
                    });                    
                    
}

static void BuildConfig(IConfigurationBuilder builder)
        {
            builder. SetBasePath(Directory.GetCurrentDirectory())
                . AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                . AddJsonFile($"appsettings.{ Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
                . AddEnvironmentVariables();
        }

my appsettings.json file contains a small section on serilog

"Serilog": {
    "MinimumLevel": "Information",
    "Override": {
      "Microsoft": "Information",
      "System": "Warning"
    }
  },

---
#### Feedback Bot on 10/2/2020, 05:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/8/2020, 11:36 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This would be a good question to ask to the [`serilog` community](https://github.com/serilog/serilog).
That said, this most probably is an issue with the identity (which the Windows service is running under) not having enough permissions. When you start the app yourself, it runs under your own user account which obviously does have the necessary rights.
