### ISSUE TITLE
Provide access to the current request URL from within a TagHelper

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26988]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1173602/provide-access-to-the-current-request-url-from-wit.html)._

---
When writing a custom TagHelper, it would be useful if there was a way to access the current request URL.

I've found several methods for doing this on the Web, but they either rely on older versions of .NET or they require external setup. The latter makes it difficult to create a TagHelper component that is easily plugged into other applications.

Back in WebForms, I know we had `HttpContext.Current`. It would be nice if there was a way to accomplish this.

---
#### Feedback Bot on 9/4/2020, 02:48 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `TagHelper` has a [ViewContext](https://github.com/dotnet/aspnetcore/blob/3f5275194f5926daddea71641ef9dafef771284f/src/Mvc/Mvc.Razor/src/TagHelpers/UrlResolutionTagHelper.cs#L113-L115) property, which grants you access to the current `HttpContext` instance, through which you can access all the details of the `Request` object.
