### ISSUE TITLE
"UseAspNetCoreSharedRuntime" workaround doesn't work when updating TFM

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#26992]
(Description stolen from https://github.com/dotnet/aspnetcore/pull/26788#issuecomment-710700038)

When we update the TFM, we're getting errors like the following:

> C:\code\aspnet\aspnetcore\.dotnet\sdk\6.0.100-alpha.1.20472.11\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3106: Assembly strong name "C:\code\aspnet\aspnetcore\.dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0-rc.2.20466.8\Microsoft.AspNetCore.Antiforgery.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [C:\code\aspnet\aspnetcore\src\Tools\dotnet-watch\src\dotnet-watch.csproj]

Note the bad path to the .dll - it should be `C:\code\aspnet\aspnetcore\.dotnet\packs\Microsoft.AspNetCore.App.Ref\5.0.0-rc.2.20466.8\ref\net5.0\Microsoft.AspNetCore.Antiforgery.dll`. The cause of this is that we're now getting the reference path from the FrameworkList.xml file, which has bad path data, as per https://github.com/dotnet/aspnetcore/issues/25167. This is happening because the FrameworkReference to `Microsoft.AspNetCore.App.Ref` has a 5.0 version, but a 6.0 TFM, meaning that in this code: 
https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L110-L118

`targetingPackDllFolder` points to a folder that doesn't exist (a `net6.0` folder inside of the 5.0 package). This causes the SDK to determine it can't use file names to resolve references, here: https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L267-L272

Which causes the SDK to fall back to using the framework list: https://github.com/dotnet/sdk/blob/44f381b62d466565639d51847c9127afbe7062a9/src/Tasks/Microsoft.NET.Build.Tasks/ResolveTargetingPackAssets.cs#L237-L239. 

Presumably this is only happening in dotnet-watch because it uses the `UseAspNetCoreSharedRuntime` workaround logic: https://github.com/dotnet/aspnetcore/blob/34bd2b9750933dd99a6ba09dca29b9cdbbf00a4b/src/Tools/dotnet-watch/src/dotnet-watch.csproj#L18-L19. We can fix our 3.1 FrameworkList file as part of being defensive about this, but we're still doing sort of the wrong thing here by giving the SDK a reference to a 5.0 SDK with a 6.0 TFM, and it's causing it to do a weird thing - it seems possible that there are other weird things happening due to the same cause.

CC @dotnet/aspnet-build

**Comment by dougbu** [comment]
Microsoft.AspNetCore.Watch.BrowserRefresh.csproj is the only project left using this workaround in #26788. That project is probably fine because it targets `netcoreapp3.1`.

Is this issue intended to track restoring the dotnet-watch and dotnet-watch.Tests projects❔ Or, is this about finding a better workaround❔

**Comment by wtgodbe** [comment]
> Is this issue intended to track restoring the dotnet-watch and dotnet-watch.Tests projects❔ Or, is this about finding a better workaround❔

Finding a better workaround so this doesn't happen next time we bump the TFM

**Comment by dougbu** [comment]
I'm pretty sure when we updated from `netcoreapp3.1` to `netcoreapp5.0`, this workaround was fine. @dsplaisted @wli3 has the logic in the .NET SDK changed significantly since then❔ (Thought @wli3 said we didn't need to fix `%(Path)` metadata for 3.1.)

Because dotnet-watch.csproj also set `$(DoNotApplyWorkaroundsToMicrosoftAspNetCoreApp)`, the fix would likely be in eng/Workarounds.targets. @wtgodbe do you want to try merging #26991, cherry-picking the squashed commit into this branch, and undoing the dotnet-watch changes locally❔ That may be enough given the `%(Path)` metadata should be correct for 5.0.

**Comment by dougbu** [comment]
I think we're done here because we both centralized the TFM-related workarounds and improved them as part of the transition to `net6.0`. Anything I'm forgetting @wtgodbe and @JunTaoLuo❔ Please confirm we're done otherwise&hellip;

**Comment by wtgodbe** [comment]
> I think we're done here because we both centralized the TFM-related workarounds and improved them as part of the transition to net6.0. Anything I'm forgetting @wtgodbe and @JunTaoLuo❔ Please confirm we're done otherwise…

The issue was specifically when we were using an SDK branded n+1, that still contained a frameworkReference to a targeting pack branded n. The SDK doesn't expect the mismatch, which causes it to calculate incorrect .dll locations. I believe we fixed that behavior by fixing our `RuntimeList.xml` file, but I'm not 100% sure - we could close this with the belief that it won't happen again next time, but keeping it open might make the issue easier to find if it does happen again.

**Comment by dougbu** [comment]
> we could close this with the belief that it won't happen again next time, but keeping it open might make the issue easier to find if it does happen again.

I doubt we'll need this issue to remember problems we've had w/ the big shared runtime and SDK version changes. In addition, our workaround logic is now centralized and (fairly ❔) hardened.
