### ISSUE TITLE
Feature: Hosting multiple blazor spa's with shared base DLLs

### ISSUE THREAD

**Issue by jelmerveen** [dotnet/aspnetcore#27008]
### Is your feature request related to a problem? Please describe.
I'm trying to 'merge' two seperate blazor apps together, more like multipage, so they all share the same base DLLs for the runtime. But both projects have a different SHA256 for the DLLs in the json file.

### Describe the solution you'd like
I would like to be able to re-use the DLLs necessary for the blazor runtime environment across multiple standalone blazor applications, so that you only download the DLLs that have not been downloaded.

 example: when you ran BlazorApp1 in the browser you got the base DLLs + BlazorApp1.dll, if you switch to BlazorApp2, you only need to download BlazorApp2.dll

**Comment by mrpmorris** [comment]
Are you describing lazy loading, which is part of the upcoming Net5 release?

**Comment by jelmerveen** [comment]
After reading the docs on lazy loading, It has similarities. But as I understand it's only within one blazor app?
I would like to run N blazor apps, which all share the common dll's between them.

To elaborate, if I scaffold 3 apps from template, the boot.json has different sha256 everytime. But I would think it should be idempotent (at least for the shared dlls required to run any blazor, e.g. system.dll or mscorlib.dll) but if i scaffold three times the app, i get for those base dlls 3 different sha256. Do when I access all of these apps, I have to download all those dll's 3x. (and then they are cached) instead of 1x and accessing the other 2 apps only downloads the app specific dll(s).

**Comment by mrpmorris** [comment]
@jelmerveen Sounds like you want some kind of CDN, is that right? If so, you'd have to settle for DLLs that haven't been stripped down during the release build. Details on how to do that are here

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1#control-linking-with-a-configuration-file

**Comment by jelmerveen** [comment]
@mrpmorris Thank you for your reply! I've read the article and this is again something for a single app.

Here are code snippets from 2 cleanly created blazor apps from a template in the latest visual studio community: 

App 1
```"resources": {
    "assembly": {
      "App1.dll": "sha256-CEdJSECXhcmUnDIKSeAyhdQKv63k0F9EyUpkRTTFCUY=",
      "Microsoft.AspNetCore.Components.dll": "sha256-p0qxUXCDhFNsIq4cE6YYH9aVBUQl1bWezx6+AJwA32Y=",
      "Microsoft.AspNetCore.Components.Web.dll": "sha256-+Toiq42LuQ+Y9l2KI5kHSjau4BrkE4qJWWKDwWeWxSU=",
      "Microsoft.AspNetCore.Components.WebAssembly.dll": "sha256-cEb3cIREO+BOF938Cj9GftfhAugO1OXg+e8K2KON58Y=",
      "Microsoft.Bcl.AsyncInterfaces.dll": "sha256-jzHgXWAvWMkKIGFjZoT84tbe72E+H7CvTr\/Dryh4QPs=",
      "Microsoft.Extensions.Configuration.Abstractions.dll": "sha256-NEPzKrOGIdmtwFfGP1u3A1Uds3Gje5+hOVLqX9le1Ek=",
      "Microsoft.Extensions.Configuration.dll": "sha256-h0CwtfTQyGU4edVgHMqywIoYNJzFl0UgvE2HxNEOllM=",
      "Microsoft.Extensions.Configuration.Json.dll": "sha256-4hGCt7tk6RHzQyZdJDjxqKMwCHTcvNj1HPtUTPhwA4k=",
      "Microsoft.Extensions.DependencyInjection.Abstractions.dll": "sha256-MhdvNgRkmZiLbbcklkEndYz8f8ycZURcSLonW8Q\/pcg=",
      "Microsoft.Extensions.DependencyInjection.dll": "sha256-ZiGtOd1OsZs9Z9c4HF8OLiMvYq0tzS421+dCK6OUVc0=",
      "Microsoft.Extensions.Logging.Abstractions.dll": "sha256-1GXi73BL7MnLPtI4aXSRclDOsWeskagXuf6XmhbgbzA=",
      "Microsoft.Extensions.Logging.dll": "sha256-zgp98FQFCum+gNqpGYLacCD4XeMsUDCo2TA1FTZ6tIs=",
      "Microsoft.Extensions.Options.dll": "sha256-9U9tm2NheNH8j5t9H2IFSCNh7KJWiQK\/cg9H1QIpR\/c=",
      "Microsoft.Extensions.Primitives.dll": "sha256-LYSlJrBVYsAaHe31apKH1+\/6o2qDLHLCnwPGCrA3b0Q=",
      "Microsoft.JSInterop.dll": "sha256-3cbvJEo8k8VJVQwyEZWWQ6yGRFQW8\/219DaOnmsX3e4=",
      "Microsoft.JSInterop.WebAssembly.dll": "sha256-zV\/OfJNfNsG404X30Pwkdymdh1KmZpTVEmG\/JNFVc\/k=",
      "mscorlib.dll": "sha256-0iDxd1Up08sXFg+oAQPKx+8B2j3rmtvbWVsj0xkMQ34=",
      "System.Core.dll": "sha256-CU63v8KdwdyiEt\/KyVW9skLtgh82gLoIPper+2j15Qk=",
      "System.dll": "sha256-PrEOSaLWZRMzTpYdFddsd6xRn92K2FH1QwtIekL+j8k=",
      "System.Net.Http.dll": "sha256-zgobE32Fwa5rW6w25aBxvfXlkgR\/sGWJxapqPKIUCAM=",
      "System.Net.Http.Json.dll": "sha256-1stezxVTwt+7JAZYucZxpZWh0JbPqy4kfLFPVFh1fsA=",
      "System.Net.Http.WebAssemblyHttpHandler.dll": "sha256-Gz8ZzjH+VB1Lw3fYjdj2FUZPyLrO0Et0W97LoBrbMDc=",
      "System.Runtime.CompilerServices.Unsafe.dll": "sha256-ZSfrDXM\/mGrUAn5yqyqafCxq\/YEIO7q45RuBUYgFCRw=",
      "System.Text.Encodings.Web.dll": "sha256-Pq52p57ySTHxVJKdLnOJBTYTQrrk0wTi0QJmoa766FE=",
      "System.Text.Json.dll": "sha256-mwdAIP1ERl2CtMiArEdivhd4XrLX4ARTDU09s4t\/t4g=",
      "WebAssembly.Bindings.dll": "sha256-FKfZ398tsb2d3pQ55nmRjYZMirsmuxLw4kETWgeDRuM="
    },
```
App 2
```
      "App2.dll": "sha256-j2Ywtb5kJHR9JkAHopttbIvzoV6O5CIkQickuFBVIgo=",
      "Microsoft.AspNetCore.Components.dll": "sha256-8lwLydxqmp3KbJ2lRvffxYdedvyX73vO5iJgWih8mYs=",
      "Microsoft.AspNetCore.Components.Web.dll": "sha256-xSMAYStA3DceJU898UM2NSj0CndXtnuCkYwSniCjsdc=",
      "Microsoft.AspNetCore.Components.WebAssembly.dll": "sha256-jkJA35ND2oYeo1jQdKqr5sOtLGRXXCdvJGi12dLGfNg=",
      "Microsoft.Bcl.AsyncInterfaces.dll": "sha256-jzHgXWAvWMkKIGFjZoT84tbe72E+H7CvTr\/Dryh4QPs=",
      "Microsoft.Extensions.Configuration.Abstractions.dll": "sha256-BPy\/z6JOth\/Dc6g2xCZ0BgJkuzujUpbwPxa5xmpQ7g8=",
      "Microsoft.Extensions.Configuration.dll": "sha256-SMfeBAurfx0ccFIVEt0nbzK2+gpx6Q\/W6CCOENyr7jc=",
      "Microsoft.Extensions.Configuration.Json.dll": "sha256-4ioAJqhxHhxNVc5U5c3+ThfUhVNMbYyGOZbFblv42BU=",
      "Microsoft.Extensions.DependencyInjection.Abstractions.dll": "sha256-xRIqWGfnSxlliDNmlpivTg1UEpuLjFnVosHppglmpAY=",
      "Microsoft.Extensions.DependencyInjection.dll": "sha256-DAa5lAynCvCZWSRu6yfh\/njykFKdYtMyFvpwZ1AqOxA=",
      "Microsoft.Extensions.Logging.Abstractions.dll": "sha256-vrM6KJuH5aMSymaIVvAHWKbFWNk+bygB8paH8Izv7LI=",
      "Microsoft.Extensions.Logging.dll": "sha256-eliQE\/U73\/ECkgEJAt0UgojZ9sUyiUi6E8HkYk5xu8w=",
      "Microsoft.Extensions.Options.dll": "sha256-W8VC\/z7rCBlCs1o2u9L2a080rWxLn5EJApRjYCxiJ0Y=",
      "Microsoft.Extensions.Primitives.dll": "sha256-nXrWIpY0Iosknkh96rT3zSp6wii1AGmdHdklgIlbFRY=",
      "Microsoft.JSInterop.dll": "sha256-VvpOhCacWfG9MrdyFFqPdaIljuImNodBENB03zWiLN0=",
      "Microsoft.JSInterop.WebAssembly.dll": "sha256-Mh\/luMRUW5nFb4QPzMxi+HtdB5PJQ5H7RliKQvl3tXE=",
      "mscorlib.dll": "sha256-v8itb+K1LHamODdaCQ+l8RRPg2pcKfrcs6QgA\/KSJrE=",
      "System.Core.dll": "sha256-ypidy0\/odgbhrtrgDTj49+GpGcl5KlQCS+3NOMOhZ3M=",
      "System.dll": "sha256-FWNWkVO9ENx\/QyyjAmcTQ0aBFMllv1Z4OGarhauET+4=",
      "System.Net.Http.dll": "sha256-Y+oNYOCn\/vFprq+9bHmLjz4fg40rLUHo9zolQPBtygk=",
      "System.Net.Http.Json.dll": "sha256-P7qqPdfBZ5rdTn9\/w5eaP6d1DHl1T3Mvk+azzZB6\/VM=",
      "System.Net.Http.WebAssemblyHttpHandler.dll": "sha256-qJsxe\/CNTE7fVaX6FHCaf3YlbgXIuFJ2CU55jc7ZIMs=",
      "System.Runtime.CompilerServices.Unsafe.dll": "sha256-PX9fc5Upe8xwvGVV34Zaf9u05OrKXIzf4Ekbmd9ZYYQ=",
      "System.Text.Encodings.Web.dll": "sha256-k\/79nOHFINFDeDMn7BcR9aJqtGh\/pZtqCYY5xzdMkZU=",
      "System.Text.Json.dll": "sha256-BjgtXpowV5NN9mGizWAiHKtn3Wgsif\/wGK9lAAWMR6g=",
      "WebAssembly.Bindings.dll": "sha256-YBdxqaZLYo9SOUyObkF\/9j1KG8WI1L35tDeXDcgXj68="
```

As you can see they both include a lot of the same DLLs, but they have other hashes, so the browser will download them again.
It's more of a multipage approach what I'm trying to do.

My feature request is about eliminating the different hashes of the shared DLLs, I am not sure why these keep changing for each scaffolded new app. Do you calculate them time based?

Also added a picture of what the general gist is. This drawn scenario is not feasable, but if the hashes of the shared DLLs would be the same. Then from the same domain the DLLs would not be downloaded again i presume. Which would help drop the load for a multi page setup.

![blazor feature](https://user-images.githubusercontent.com/43730771/96376581-2473ff80-1180-11eb-905e-5e9178e82f0e.png)

**Comment by javiercn** [comment]
@jelmerveen thanks for contacting us.

Blazor apps are linked to reduce the size so it is hard/impossible to share the runtime unless you give up on linking. If you were to do that then you should be able to share the runtime dlls by loading them from a single source with a custom boot loader.

**Comment by jelmerveen** [comment]
@javiercn Thank you for pointing that out, I'm going to experiment with the custom bootloader! 
Good to know they are already slimmed down.
