### ISSUE TITLE
Please seprate out Kestrel from ASP.net 

### ISSUE THREAD

**Issue by rishavs** [dotnet/aspnetcore#27002]
### Is your feature request related to a problem? Please describe.
I prefer creating web services in a language than in a framework, and an immense macro framework like ASP.net does not works for people like me. I'd rather have something akin to golangs net/http or node's express which allows me to focus on the language, and not on learning the framework.

### Describe the solution you'd like
For this, the dot net core ecosystem needs to have a barebones http server implementation which can be built upon. and for that Kestrel needs to be a separate entity, with its own usage/extensibility docs. Kestrel used to be separate AFAIK, and having it be its own thing (albeit it can still be a part of the larger aspnet core family) will make it easier for app dev to use it for simple low ceremony webdev (it could be that this is still trivial to in the current state of aspnetcore, in which case some docs/articles teaching how would be welcome).

### Additional context
for a non "magical", low framework overhead webdev experience, the standard net/http implentation in golang is a great example.

**Comment by davidfowl** [comment]
cc @glennc @halter73

**Comment by davidfowl** [comment]
FWIW take a look at https://github.com/featherhttp/framework

**Comment by wtgodbe** [comment]
@davidfowl are there plans to do something like this in the dotnet org?

**Comment by BrennanConroy** [comment]
We have no plans to separate Kestrel from this repo.
