### ISSUE TITLE
Error while building aspnetcore repo

### ISSUE THREAD

**Issue by MCCshreyas** [dotnet/aspnetcore#27003]
# Describe the problem
So, I am following this (https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md) guide for building aspnetcore repo on local. So on step 3 when I ran `restore.cmd` from the command line (normal CMD, not PowerShell), am getting the following error screen after restoring. I have followed all the instructions and installed prerequisites as well, but not sure why I am getting this error. 
![image](https://user-images.githubusercontent.com/17148381/96338105-80b82000-10a9-11eb-8ac4-bc0bf64bf294.png)

### Further technical details
```
E:\.NET\aspnetcore>dotnet --info

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
That error usually indicates that you do not have the VS pre-reqs installed. Did you follow the instructions listed here: https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md#step-2-install-pre-requisites?

**Comment by MCCshreyas** [comment]
@pranavkm I do have Visual studio latest preview installed with required SDK and workload. And I think error is occurring while building some C++ specific stuff. But I do have C++ development workload installed.

**Comment by MCCshreyas** [comment]
@captainsafia

**Comment by captainsafia** [comment]
Yeah, this one is gnarly. I've run into it before on a Windows machine where I had multiple versions of VS installed. Some things that you can try:

1. Verify that MSBuild is installed (it should be).
2. Set the `VCTargetsPath` environment variable to a path where the build files associated with the C++ workload can be found. This will usually be in the Visual Studio folder in Program Files. You can find guidance one how to set this path via Google.

Admittedly, none of the above worked for me when I ran into this issue. I ended up resolving it by uninstalling older versions of VS (nuclear option) and repairing my VS 16.8 install. Hope this was helpful!

**Comment by MCCshreyas** [comment]
Hi @captainsafia , some days ago I had the Visual studio (Non-preview) version installed. But after I installed VS latest preview, I did uninstall the old version. So that is OK. 
>Set the VCTargetsPath environment variable to a path where the build files associated with the C++ workload can be found. 
I will give a try to this. 

Thanks for the reply! :) 
I will let you know the outcome!

**Comment by MCCshreyas** [comment]
And also I do have one more concern, in BuildFromSource README file. The prerequisite is to install Visual Studio 2019 and not the Preview version. 
I think it's better to suggest to install a preview version because the repo source gets to build on top of the preview version of the upcoming release and one cannot use the preview version on Visual Studio (non-preview edition), it needs a preview version of VS to work upon preview releases or the code which relies on the preview version.

**Comment by captainsafia** [comment]
> I think it's better to suggest to install a preview version because the repo source gets to build on top of the preview version of the upcoming release and one cannot use the preview version on Visual Studio (non-preview edition), it needs a preview version of VS to work upon preview releases or the code which relies on the preview version.

Yeah, this is good feedback. I believe we discussed not including the specific version in the doc since it changes depending on the time and what SDK we reference in our `global.json` file at the time. But we should consider another way to address this.

**Comment by MCCshreyas** [comment]
> > I think it's better to suggest to install a preview version because the repo source gets to build on top of the preview version of the upcoming release and one cannot use the preview version on Visual Studio (non-preview edition), it needs a preview version of VS to work upon preview releases or the code which relies on the preview version.
> 
> Yeah, this is good feedback. I believe we discussed not including the specific version in the doc since it changes depending on the time and what SDK we reference in our `global.json` file at the time. But we should consider another way to address this.

More than 95% of the time we are referencing alpha or beta releases in `global.json` and not stable releases. And preview releases won't work in non-preview VS, it has to preview release of VS to work on previews. So I think it's better to mentioned using the latest VS preview release. 

Because let's see person **A** clone this repo and opened in VS (non-preview), he/she will get prompt like cannot find required SDK, because VS cannot work on preview SDK. 
Then he/she goes to the internet and again download the preview release of VS to work upon, and hence he/she will have now 2 versions of VS installed one is a preview and one is stable and moreover he/she might get build errors while building this repo just like I am facing because two versions of VS are now conflicting, and hence a bad experience to first time user and ultimately, he/she might even lose interest in contributing. 

Because of which I think it's better to suggest people use Visual Studio Preview (The latest release) to work upon.

**Comment by MCCshreyas** [comment]
So, today I managed to solve this problem. 
What I did is like I updated the VS to the latest preview release, then I opened `Visual Studio 2019 Developer Command Prompt v16.8.0-pre.5.0` and navigated to the cloned repo. Then first I ran `clean.cmd` and then I ran `restore.cmd` and finally it worked. :)

**Comment by captainsafia** [comment]
@MCCshreyas Glad that worked for you. I'll keep this in mind as a recommendation for folks who run into this in the future.

Closing this issue as resolved.
