### ISSUE TITLE
Allow template option `Configuration.MultiTenancy.IsEnabled = true;`  Global DataFilter for Tenant entities 

### ISSUE THREAD

**Issue by papyr** [dotnet/aspnetcore#27006]
###  Please allow  `Configuration.MultiTenancy.IsEnabled = true;`  Global DataFilter for Tenant entities enabled/Disabled _options_.
ASP templates should be configurable to allow Global Data Filters projected on tenant specific data.

### There are many options as listed below, the default should allow something easy and quick for the developer to switch on.

1. Using database per tenant strategy
2. Using shared database for tenants
3. Multi-tenant EF Core database context with security net
4. Loading tenants configuration
5. Missing tenant middleware
6. Tenants provider to get current tenant
7. Tenant-based dependency injection
8. Unit-testing multi-tenant database context (coming soon)
9. Multi-tenant configurable composite commands

### There are many lib options often don't get maintained, some get left out or fall off
But this is a good example 

- https://github.com/gpeipman/AspNetCoreMultitenant
- https://stackify.com/writing-multitenant-asp-net-core-applications/

**Comment by javiercn** [comment]
We recommend using something like Orchard Core to support these types of scenarios.

**Comment by papyr** [comment]
Sorry, working for Microsoft but _how can you not be clear_ on what **`supporting Multi-Tenancy`** is???

Look at the number of up votes from your developer community here... they all seem to get it and are asking for it!

![image](https://user-images.githubusercontent.com/12733414/98446603-83c49000-20ec-11eb-8b4b-090f3d648503.png)

**Comment by davidfowl** [comment]
We build an extensible platform so we don't always need to provide all of the pieces to the puzzle. We also need to make sure feature like this one in particular can work without making the design of what we have inefficient (that's one of the main concerns I have). As long as it's possible to build a multi-tenant solution on the foundation easily we as a team don't need to build in support for it *and* those many components required in specific kinds of applications.

I think multi tenancy and SASS is important and needs to be possible to do with our components.

**Comment by papyr** [comment]
Tenancy sits on the platform infrastructure, including hosting, gateways, portals and more!. 

Its clear you many in the MS world are unaware and **have not read those standards**, or are disconnected from the developers need. So, IMHO its not an opinion for you to be heavy handedly closing this, 
### **its an industry standard in pretty much** all the stacks, there are so many examples of well organized and prescribed approaches on these since they also pertain to security! Leaving this open could also make MS vulnerable to the fact that they neglecting security on purpose after repeated attempts by the community asking them to fix this critical need. There are so so many developers who are asking for this before you closed the voting here and user voice!

![image](https://user-images.githubusercontent.com/12733414/98471657-e33da100-21bb-11eb-83ed-4aac0087b1cb.png)

To your point, people can extend or customize, like the razor engine etc. but a native implementation is required and missing in the stack, it hinders adoption for smaller organizations and startups.

**Comment by davidfowl** [comment]
I don't know what you mean by industry standard. There are many 3rd party plugins that add an opinionated way to do multi tenancy with ASP.NET Core to build SASS application (and there are people using ASP.NET Core to build multi tenant applications just fine)

This GitHub issue should be used to discuss concrete concerns and difficulties with various existing. approaches and to suggest what we might do to ease that pain.

Gross generalizations and talk of "industry standards" are non constructive.

**Comment by papyr** [comment]
If you don't know what those standards are click on the link, there is not a gross generalization, these are committees and boards and publications. Are you really at Microsoft!!!

If multi-tenancy is not concrete then what is is, Fiction?? hahahahaaa

You must arrogant to ignore **the highest one of the highest rate & requested feature on Microsoft own poll**.
