### ISSUE TITLE
Ability to declare child content that do not set aside component re-render encapsulation

### ISSUE THREAD

**Issue by Liander** [dotnet/aspnetcore#27017]
The re-render condition of a specified component is based on if any attribute value has changed, but that is set aside if you have declared child content (implicit parameter) to a component. That occurs even in cases when that content markup is static. In that case the component starts to re-render whenever the parent component renders independent of the state of any attribute set to the child.

The current working is by design, so I am not claiming this is a bug. This is an enhancement request that the framework can test for change also for child content markup set on components. 

### Is your feature request related to a problem? Please describe.
The problem:
``` html
// The user component below will re-render only when the Name attribute is changed: (Nice!)
<User Name=@UserName>
</User>

// Passing static content markup changes its behavior to render whenever the parent renders instead: (can be improved)
<User Name=@UserName>
  <p>Hello world</p>
</User>

// Consequence of nesting components: (only leaf component gets active re-render guard; can be improved)
<User Name=@UserName >  // dismissed re-render guard
   <UserProfile>  // dismissed re-render guard
      <UserImage> // active re-render guard
      </UserImage>
   </UserProfile>
</User>
```
Description:
I think the intuition would say that having static content that doesn’t change should not change the condition for re-render the component `User`. In this situation it would be reasonable to have the condition for re-render to still be when a change of the attribute `Name` occurs.

That behavior continues recursively when nesting further, so in effect it will only be the innermost component that will exhibit an active re-render guard. When I say nesting, I mean it from the parent perspective like the code given above passing content to child. The components themselves will also generate content which is not the content I am referring to here. I am referring to content in the form of passing markup as template value to child. It would be reasonable that it only re-renders when `Name` changes also in this case of nested static contents.

Let us examine it a bit. Markup is transformed to building a render-tree model of '`RenderTreeFrame`'s of attributes, component & element scopes, and text contents. A test is performed when rendering by walking down the tree to see if the arguments to components have changed; if changed, the attribute values are passed to the component and the component specified will also start to re-render, and if not changed the previous result will be reused. The receiving component (`User` in this case) will receive attributes as property values and the content markup is received as a `ChildContent` property. Now, I think it would be reasonable to believe that frames are built and tested at call-site to see if the component should render. After all, that is how we have declared the markup, so it is reasonable to think the tree model reflects that. 

However, that is not the case. The building of the tree for the content part is delegated to be performed at receiver site wherever used instead. It also builds multiple times if used at multiple places in the `User` component. The reason is that the `ChildContent` is receiving a `RenderFragment` delegate (i.e. in the form builder => ...) and it is also what is implicitly set as the attribute value for the content set on the component. Therefor there are no frames to test against at the call-site. Now, you might think I am heading to suggest introducing another receiving type that contains the frames, so the diffing could conceptually occur to say if the User component should render or not, and then construct a `RenderFragment` when used inside `User` instead. That is not what I am going to suggest, although I think it is an exercise useful to reflect upon because it would have the characteristics I am after, namely having something that can be tested for change and at the same time would produce the same result in the `User` component.

What I am going to suggest has a common theme for all situations where I think the mechanism for capturing change can be improved. That is, *to embrace the fact that the value to be set as property value should not always be the value to test for equal rendering result*. That was intended to be my main takeaway in this issue #21915.

Although that conclusion is the same, I will bring up an alternative implementation proposal that is a bit different from the previous one and use it for the problem stated in the heading. But I should emphasis that implementation details of this is not my main message.

### Describe the solution you'd like
Proposal:
Let us define two types of attributes. One for values tested for change through the value itself, like today. And another of type `IValueProvider<T>` having a method to test for equal render result and a method to get the value to be set to the component. For a `RenderFragment` it could look like
``` csharp
    public interface IValueProvider<T>
    {
        public RenderFragment GetAttributeValue();
        bool RenderEquals(IValueProvider<T> other);
    }

    public class RenderFragmentProvider : IValueProvider<RenderFragment>
    {
        private RenderTreeBuilder _renderTree;

        RenderFragmentProvider(RenderFragment renderFragment)
        {
            _renderTree = new RenderTreeBuilder();
            renderFragment(_renderTree);
        }

        public RenderFragment GetAttributeValue() => builder => builder.AddRegion(_renderTree);

        public bool RenderEquals(IValueProvider<RenderFragment> other)
        { // diff the _renderTree
        }
    }
```
In this way there is way to test for change and a value for setting the attribute value, like previous proposal but organized little differently. One can use similar constructions of separated value and compare-value for `EventCallback` and certain complex types but that is for another time. I want this to be discussed first.

In Angular I think the process is to compare expression strings and evaluating those if different. To some extent a testable value-provider is a generalization of that to support more specialized types.

A side note: To expand on this idea even further you could consider introducing *constrained* render fragments (like a `ContentFragment<T> where T:IComponent`) for content passing and have correspondingly a builder type that can only add components of a certain type, without needing to change the type on the receiving end (to avoid confusion with existing `RenderFragment<T>`). It could be given as a property on the C# parameter attribute, for example like `[Parameter(OfType=typeof(Column))]` in a grid, and let that be an indication for tooling to use a `ContentFragmentProvider<Column>` (still inheriting `IValueProvider<RenderFragment>`) that would take a `ContentFragment<T>` which would give compile-time error (probably a casting error) when an incompatible type is trying to be added to some `ContentFragmentBuilder<T>` that only has API accepting components of T. The frames copying will be into a `RenderFragment` as before upon access.

Another side note: This issue discusses passing `RenderFragment` and how to test it, which potentially have dependencies to parent state via closures. Framework changes for that can be applied without any user code changes and just giving more conservative re-renders. That is not the case for template parameters with a context parameter of type `RenderFragment<T>`. In that case you have dependency to some item applied by the *child* component plus potentially some closure into parent state. It is the closure dependencies that would need to define the re-render guard from parent to child in this case, so current behavior needs to remain for current syntax. My current thinking is that you could introduce another syntax where you make this explicit by adding an additional parameter for the any parent state dependency (if such exist) and having the delegate being generated in a static member instead to guarantee it won’t take any (further) closures to instance state. The re-render test would then be on state of that added parameter instead.

For very long I somehow got the impression that the plan was to address some of these cases (and others like event-handlers) through some one-time binding mechanism. That has some overlap with this since a lot of times when you get the impression that change detection should be performed better are when dealing with static things, but doing it in this way would be more complete, robust and cover more scenarios.

Summary:
I think a framework design where a testable value-provider (or some other way of having the value tested for equal rendering set different from the attribute value) will facilitate for more cases where testing for change can be improved where this mentioned problem of passing child content is one such case. For those it could be through evaluating render-tree content at call-site and use that to test change and to copy render-tree frames where its used in child component.

### Additional context
Attaching runnable code showing current behavior. Again, I am not claiming it is a bug, but I do think it could be improved. All User components could be rendered only ones here since they are not declared with any dynamic content.
![BlazorChangeDetection](https://user-images.githubusercontent.com/4334883/96362514-2e6d1280-112e-11eb-8deb-626c89e5ed99.gif)
[ExploreChangeDetection.zip](https://github.com/dotnet/aspnetcore/files/5397232/ExploreChangeDetection.zip)

**Comment by Liander** [comment]
@SteveSandersonMS I post this issue partly as a continuation to the conversation we had recently in #25356 regarding documentation of this. I feel it is a bit hard to have real discussions around design in the format of issue-tracking. I apologize if I left a lot of confusion and I hope this more extensive description will make things clearer. I would be very interested to hear your thoughts.

**Comment by SteveSandersonMS** [comment]
Thanks for the suggestion.

On one hand, I'm not certain this is a great idea, because any component that receives a `RenderFragment` cannot really know whether its output is fixed or not. A `RenderFragment` is a `Delegate`, so it can do anything when you invoke it, and might make use of any mutable state to produce different outputs. That's why it's intentionally treated as a mutable parameter. If developers think their `RenderFragment` produces fixed output but it actually varies, then the UI will just weirdly fail to update and people will get confused. 

On the other hand, we've already said we're open to having some way of marking certain `[Parameter]` properties as being excluded from change detection. This might be defined on the parameter type, or on the `[Parameter]` attribute, or maybe both. If it was possible to do this on arbitrary parameters, then as a special case you could do it on `ChildContent`:

```
[Parameter(IsFixed = true)] public RenderFragment ChildContent { get; set; }
```

...which I think is exactly what you're asking for.

**Comment by Liander** [comment]
> A RenderFragment is a Delegate, so it can do anything when you invoke it, and might make use of any mutable state to produce different outputs.

Sure, but in this context, are you referring to the fact that the child component can re-render (upon user action and similar) without the parent has been rendered so any dynamic state change will not go through the content specified in parent component? Note that when the parent re-renders the content with its tree in the provider will obviously be updated and tested.
```html
private UserObject _user;
<User>
   <span>Hello @_user.Name</span>
</User>
```
I actually think it is quite reasonable to reuse the state used when rendering the parent containing the content declaration, so it will be the `Name` when parent renders that will be used in `User` above. But that is a change of behavior. Perhaps that causes the need to specify the provider explicitly which I hoped to avoid. 

About using a `IsFixed` parameter:

> ```csharp
> [Parameter(IsFixed = true)] public RenderFragment ChildContent { get; set; }
> ```
> ...which I think is exactly what you're asking for.
> 

No, not at all unfortunately ☹. 

With the proposal you can set
```html
<User>
   <span>Hello World!</span>  // static, and will only render ones
</User>
<User>
   <span>Hello @_user.Name</span>  // dynamic, but only re-render when render tree of content is different which is when @_user.Name is different.
</User>
```
And I would have preferred this behavior to be the default without any flag on the parameter, since you will not know if you are going use a component setting static or dynamic content.

There are times where I do think it make sense to specify change-detection behavior at the receiving property or on type, but driven on this idea would be more along:
```csharp
[Parameter(ValueProvider = typeof(StaticValueProvider)]  // ok, this is same as saying IsFixed
Guid _guid;

[Parameter(ValueProvider = typeof(ShallowObjectProvider))] 
WeatherForecast _weatherForecast;

[Parameter(OfContentType = typeof(Column))]
RenderFragment _columns;

[Parameter]    // was hoping for built-in ValueProvider for RenderFragment supporting both static and dynamic state
RenderFragment ChildContent;  
```
I guess a component knows if it renders itself (have event-callback or if it render when used in some parent) so I guess a testable value provider could be given explicit also for RenderFragment.

@SteveSandersonMS Do these exemples clearify what I am after? It much more general than static content.

**Comment by SteveSandersonMS** [comment]
It sounds to me like you want the diffing system to change how it passes `RenderFragment` parameters so that, when there is a `RenderFragment` parameter, we first evaluate (render) it into some temporary buffer and compare its output with the previous render output. And then we treat that parameter as changed only if its output changed.

If so that's an interesting idea but:

 1. It would only work for `RenderFragment`, not `RenderFragment<T>`, since it's the recipient component that provides the `T` values as part of its own rendering
 2. It would come with some perf cost because not only would we have to render the `RenderFragment` into a temporary buffer, we'd have to copy that output into the recipient's output buffer, and somehow walk through the data to rewrite various indices to make it valid in its new location.

I'm not confident I've understood all the other things you're suggesting. Perhaps you feel there are ways to make it more general still or to mitigate the perf impact. If so that's great, though of course we also have to allow for the additional implementation complexity and possible compatibility concerns.

If my interpretation is correct, then I agree this is a valid suggestion! However the tradeoffs are delicate and I can't promise we'd take this on in the short term.

**Comment by Liander** [comment]
1. Sure, as mentioned earlier. It is discussed in somewhat more detail in the attached code. Let me know if it is unclear.
2. No, I do not expect hardly any performance cost. Before I suggested the ability to have a comparable model side by side with the attribute value in the render-tree-frame, but here it is instead encapsulated in the same object which allows it to be optimized for reuse between test and render. Feel free to discuss this in more detail when you debug the provided code.

It is really about getting a comparable render tree model that *represents the meaning of last render* of a component so the comparison during updates also represents that. As you know, todays problem lies in that attribute values of dynamic state are *not modeled to represent its meaning of last render* and thus render trees with such values are not comparable for equality. But that can be improved!

I guess I hoped for a somewhat more collaborative effort. This time around I will provide runnable code so different aspects can be debugged. I hope that helps. I also included some other models for other dynamic values.

There are a few points I want you to recognize in the provided code/demo:
1. models for dynamic values can be developed by users for specific needs and by community plugins for common scenarios.
2. to support a contract of such models (called `IDynamicValue` in the demo code) requires relatively small changes in the framework. See FrameworkChanges folder, especially if you phase changes to support `RenderFragment<T>` for later which requires more tooling changes.
3. it can be an opt-in feature with no cost if not chosen.
 
@SteveSandersonMS I really really want you to understand the concept of having a comparable model for values that are not comparable today to get a comparable render tree model between renderings when having such values. Regarding the model for `RenderFragment` I do think you can get it for zero cost with the outlined changes, which might make it as a contender to be used as a built-in model, but that is secondary to the framework capability of using custom models for these ‘dynamic values’. Let me know if something is unclear.

![ExploreChangeDetection-Before](https://user-images.githubusercontent.com/4334883/102282003-3845a300-3f30-11eb-9143-3f86ae93a699.gif)
![ExploreChangeDetection-After](https://user-images.githubusercontent.com/4334883/102282034-47c4ec00-3f30-11eb-9d18-a198f377fbbb.gif)
[ExploreChangeDetection2.zip](https://github.com/dotnet/aspnetcore/files/5699155/ExploreChangeDetection2.zip)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
