### ISSUE TITLE
A blazor app behind ingress controller

### ISSUE THREAD

**Issue by hodjaev** [dotnet/aspnetcore#27019]
### Is your feature request related to a problem? Please describe.
I am trying to publish a blazor web app inside a container behind an ingress-nginx controller and the url looks like https://domain.com/blazorapp1. But some resources cannot be loaded since the app thinks that it works from the root of https://domain.com.
I have made changes in two files,
_Host.cshtml `<base href="~/" />` to `<base href="/blazorapp1/" />` 
and in Startup.cs add line with `app.UsePathBase("/blazorapp1");` 
then it worked.
But what if I didn't have access to the source code, just had a prepared container image?
These issue brings another problem of tight coupling - the app must know about the environment where it is being published.
How to be with local development, change that lines of code everytime I want to work locally?
I don't know how to configure azure pipelines to build container images properly.

### Describe the solution you'd like
Ability to configure a blazor app through env variables to tell it the root url.

**Comment by javiercn** [comment]
@hodjaev thanks for contacting us.

> I have made changes in two files,
> _Host.cshtml `<base href="~/" />` to `<base href="/blazorapp1/" />`
> and in Startup.cs add line with `app.UsePathBase("/blazorapp1");`
> then it worked.
> But what if I didn't have access to the source code, just had a prepared container image?

Couldn't you in that case pass in the value through IConfiguration and apply it to the two places where you need to change it? That way you could set the value in an environment variable when you boot the container.

**Comment by hodjaev** [comment]
Ok, thanks
