### ISSUE TITLE
Input fields should not show null for empty strings

### ISSUE THREAD

**Issue by Martin-Andersen** [dotnet/aspnetcore#27012]
### Is your feature request related to a problem? Please describe.
When I bind a string to an input control and the string is null the control shows null instead of nothing/empty
This is very annoying. When a user wants to create a new contact then first name, last name is null and showing null on the form.

Please correct this. 

### Describe the solution you'd like
Don' show null for empty strings

**Comment by blowdart** [comment]
What UI is this? MVC / Razor Pages / Blazor?

**Comment by javiercn** [comment]
@Martin-Andersen thanks for contacting us.

As @blowdart mentions, what part of the stack are you using? I don't believe anywhere in our stack we have this behavior, but I might be wrong.

**Comment by Martin-Andersen** [comment]
Blazor wasm has this behavior

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
