### ISSUE TITLE
SignalR token in java not work

### ISSUE THREAD

**Issue by MeysamMoghaddam** [dotnet/aspnetcore#27028]
Followers of conversations in :
[what is "An Access Token" in SignalR Java client](https://github.com/dotnet/aspnetcore/issues/26845)

please check this [replay](https://github.com/dotnet/aspnetcore/issues/26845#issuecomment-711133733)

Please guide me further

**Comment by BrennanConroy** [comment]
Does your auth token contain a `NameIdentifier` claim? How are you determining the "fromUserId" when calling `Clients.User(...)`?

You can read more about users in https://docs.microsoft.com/aspnet/core/signalr/groups?view=aspnetcore-3.1

**Comment by MeysamMoghaddam** [comment]
@BrennanConroy 

> Does your auth token contain a NameIdentifier claim?

yes
(Encoded string in this image is `Token` in `return Single.just(Token);`)
![jwt](https://user-images.githubusercontent.com/65253484/96548651-1b3b7d80-12bb-11eb-842c-5ca239bce29c.png)


> How are you determining the "fromUserId" when calling `Clients.User(...)`?

"fromUserId" is Id in AspNetUsers table for example: 83fa5ceb-d57b-4d22-ac59-332a3a67e86c

And In Db

![AspNetUser](https://user-images.githubusercontent.com/65253484/96549360-3eb2f800-12bc-11eb-92e4-4629830a7075.png)

in Startup.cs

`services.AddSingleton<IUserIdProvider, IdBasedUserIdProvider>();`

![IdBased](https://user-images.githubusercontent.com/65253484/96549009-bcc2cf00-12bb-11eb-9023-fd2960281db9.png)

Please help me, I'm tied up!!!

**Comment by BrennanConroy** [comment]
What is `predicate.Type == "sub"`? Are there actually any claims that match that? If you used the default (which uses `NameIdentifier`) then you would probably see it working.

Also, have you added `[Authorize]` to your Hub class?

**Comment by MeysamMoghaddam** [comment]
> What is predicate.Type == "sub"? Are there actually any claims that match that?

ok It was not needed and I removed it.
in hub class `Context.UserIdentifier` is "UserId" And it works properly in web.
But it still does not work properly in Java.

> have you added `[Authorize]` to your Hub class?

no

Please provide an example

**Comment by BrennanConroy** [comment]
Can you provide a sample app please.

Also, collecting a network trace and server-side logs would be helpful. https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1
