### ISSUE TITLE
Blazor WASM preventDefault not work on Firefox

### ISSUE THREAD

**Issue by kochol** [dotnet/aspnetcore#27027]
### Describe the bug
I have a link in my Blazor app like below it works fine in server mode and when I switch to WASM it also works on chrome but it is not working on FireFox and redirect the page to the home page.
```
<a href="" @onclick="@( async e => await NavigateToTransaction(Id))" @onclick:preventDefault>
```

### To Reproduce
Create WASM project and test @onclick in an a tag on firefox. Maybe for firefox you have to return false to stop default behavior of clicks.

### Further technical details
- ASP.NET Core version 3.1.402
- Blazor 3.2.1

**Comment by kochol** [comment]
It seems the onclick does not work at all in WASM mode on Firefox

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
