### ISSUE TITLE
Move IFeatureCollection and friends to Microsoft.Extensions.Primitives

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2702]
_From @davidfowl on Saturday, May 20, 2017 12:46:19 AM_

The `IFeatureCollection` isn't tied to HTTP and we'd like to use it for non http things. Ideally it would be part of the primitives package and `Microsoft.AspNetCore.Http.Features` would contain http specific features.

_Copied from original issue: aspnet/HttpAbstractions#845_

**Comment by ObsidianMinor** [comment]
I'd love to see this done in the near future as I have a framework I'm working on that could really use it. Is there anyway I can help expedite this?

**Comment by davidfowl** [comment]
Massive breaking change. We might need to live with the legacy....

**Comment by NinoFloris** [comment]
So this is not going to happen I presume? It's a shame though, super useful outside of HTTP as part of other host models and abstractions

**Comment by davidfowl** [comment]
@NinoFloris can you file an API request on https://github.com/dotnet/runtime? It'll help if it's coming from a real customer scenario.
