### ISSUE TITLE
Extend OpenIdConnect middleware with an option to skip TokenValidation, or alternative solutions.

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#27021]
### Is your feature request related to a problem? Please describe.
I had a specific scenario, in which I needed to modify on a per-connection basis the parameters being sent to the identity provider for every OIDC request. I tackled that problem by using one of the provided events - `OpenIdConnectOptions.Events.OnRedirectToIdentityProvider`.

Naturally, that required to also subscribe to another event, which was `OpenIdConnectOptions.Events.OnAuthorizationCodeReceived` as I was using the authorization code flow.

The issue came then, that the initially supplied configuration in `OpenIdConnectOptions`, which contained `TokenValidationParameters` was always being used for token validations, but in my case those parameters were invalid - as every request was being modified for possibly a different authority/client, the issuer saved initially in those `TokenValidationParameters` was invalid.

Hence, I always got an exception stating that validation failed.

I fixed the problem by extracting the logic found in lines [691](https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L691) to [758](https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L758) of `OpenIdConnectHandler` with slight alterations to some of the private methods used in that segment, and making all of that, part of the method I used for `OpenIdConnectOptions.Events.OnAuthorizationCodeReceived`, and then building the `AuthenticationTicket` via a call to `AuthorizationCodeReceivedContext.Success()`, which short-circuits all of the logic in the handler below that point, as seen [here](https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L657).

### Describe the solution you'd like
The core issue here is that the call to [ValidateToken](https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L691) in `OpenIdConnectHandler` is mandatory, which in my specific use-case results in an invalid state.

There are various solutions to this issue:

- We could make the method `ClaimsPrincipal ValidateToken(string idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, out JwtSecurityToken jwt)` in [OpenIdConnectHandler](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs) be `protected virtual`, which would allow us to modify the passed in `validationParameters` by deriving from that class.

- We could add a `bool` property in `OpenIdConnectOptions`, which can be used to skip validating the token, or instead create a new event -  `OnTokenValidation`, which similarly to other events, accepts an object that has a `HandledTokenValidation` property that signals if validation was handled, and validate it for the user if it wasn't.

### Additional context
If it comes down to actually fixing this issue, I'd be happy to create a pull request, be it my first time doing so!

**Comment by blowdart** [comment]
Skipping token validation seems a really bad idea, regardless of the use case.

To be clear about your actual use case, you want to adjust the token validation parameters (or really the service configuration) on a per request basis? Given that configuration affects more than a single request (the redirect out, and the validation back), what do you want to configure it on? Are you attempting some sort of multi-tenancy here? If so, how are you selecting your tenant, what criteria do you use?

**Comment by SpiritBob** [comment]
@blowdart The use-case is in correlation with a multi-tenancy, yes. Right now, I get the tenant initially (in `OnRedirectToIdentityProvider` event) via accessing `HttpContext.Items` property, which contains an identifier I can use later, to get what I need.

But because the event `OnRedirectToIdentityProvider` is called in `HandleChallengeAsyncInternal`, and `OnAuthorizationCodeReceived` is called in `HandleRemoteAuthenticateAsync`, they are in different `HttpContext`, so in `OnRedirectToIdentityProvider` I create a cookie to store temporarily that identifier, which later gets used yet again in `OnAuthorizationCodeReceived` to fetch the tenant information.

Every tenant has a different Identity Provider with their corresponding Client ID and Client Secret.

It would be very bad practice to create a million `OpenIdConnect` handlers, each one for a specific tenant, hence why I went with the above approach.

I'm adjusting the Client Id, Client Secret, and Authority on every single OIDC request, but sadly the token validation parameters have their issuer set to the initially configured one, and I'm unable to change them, hence I get an exception (which I had to fix by extracting part of the logic in `OpenIdConnectHandler` as explained above.)

**Comment by blowdart** [comment]
Are your endpoints publishing metadata? The reason I ask is that the jwt handler itself isn't ours, it belongs to aad and so we'd have to explore with them a way to better cache metadata on a tenant basis, which in turns needs a more standard way of defining a tenant, or a way to have a tenant specific pipeline, which is basically creating multiple handlers, because the overhead is in the cached token verification information, and of course you don't want to retrieve that on every request.

Multi-tenancy has been a much-asked for feature, which the team has pushed back on, pointing out that most people just want auth multi-tenancy and it would be better served by making auth multi-tenant aware. As the auth owner it's falling to me to look at where the effort should go. Can I ask what else in your app varies according to tenant? (for example, database connect strings, image urls, configuration files, favourite pair of pyjamas etc.), which will help me put together a survey to gather feedback on what we need to do for 6.0, and help me stop any implicit basises based on my just caring about security :)

**Comment by SpiritBob** [comment]
Sorry, could you define "publishing metadata"?

I think the only thing that varies per tenant are the connection strings, which is probably the biggest difference for any multi-tenant application.

**Comment by blowdart** [comment]
Providers don't have to give you the keys you use for validation, that doesn't work in any real world scenario where keys rotate. There is a standard metadata url that jwt issuers can use which exposes the keys being used to sign the jwt.

**Comment by SpiritBob** [comment]
Thank you, I'm using Identity Server 4, which provides a metadata endpoint, as per OpenID Connect specifications. Likewise, the OIDC middleware that I've created to handle multi-tenancy is for Okta, which too offers a metadata endpoint, which you can get to by only knowing the authority. I'm altering the authority per OIDC request for Okta, as every tenant has their own Okta OIDC configuration.
