### ISSUE TITLE
Default authentication scheme is excuted when AuthenticationSchemes is set to non-default scheme

### ISSUE THREAD

**Issue by luoxlgh** [dotnet/aspnetcore#27025]
### Describe the bug
We have two authentication shemes named "custom1" and "custom2". The code is:
```
var authBuilder = services.AddAuthentication("custom1");
authBuilder.AddJwtBearer("custom1", options =>
{
    options.EventsType = typeof(Custom1AuthJwtBearerEvents);
});
authBuilder.AddJwtBearer("custom2", );
```
The controller code is:
`[Authorize(AuthenticationSchemes = "custom2")]`

The above authentication scheme would run into Custom1AuthJwtBearerEvents, and the authentication result is failed. But the result doesn't affect custom2's authentication result.

**Comment by blowdart** [comment]
Which version of asp.net are you running?

**Comment by luoxlgh** [comment]
> Which version of asp.net are you running?

aspnet core 3.1

The authentication result is always correct, but we fount it run into Custom1AuthJwtBearerEvents when debug.

**Comment by blowdart** [comment]
This makes sense. The default authentication scheme always runs. The authorization attribute runs other schemes, on top of the default.

You can either not have a default at all, or move the default authentication into the default authorization policy.
