### ISSUE TITLE
Identity as UI LoginModel+InputModelcode missing

### ISSUE THREAD

**Issue by kofifus** [dotnet/aspnetcore#27022]
My project is using a scaffolding Identity as UI 

If I reflect over all types:

```
foreach (var t in Assembly.GetExecutingAssembly().GetTypes()) ..
```

the loop goes over a type called: `MyApp.Areas.Identity.Pages.Account.LoginModel+InputModel`

However if I search my project for "LoginModel+InputModel" it is not there.

If the code is missing then as far as I understand it should not be returned by ` Assembly.GetExecutingAssembly().GetTypes()`

Thanks!

**Comment by blowdart** [comment]
To be clear, you haven't scaffolded them out, but you still have the identity UI assembly present - is that correct?

**Comment by kofifus** [comment]
I did scaffold login, register and logout and I have the relevant pages/classes created, but I don't have `MyApp.Areas.Identity.Pages.Account.LoginModel+InputModel`
