### ISSUE TITLE
Blazor WASM may have memory leak when sending large files with HttpClient from InputFile component

### ISSUE THREAD

**Issue by jeffputz** [dotnet/aspnetcore#27023]
### Describe the bug
When I attempt to use an `InputFile` component and iterate over 10,000 files, and post them using `HttpClient`, the memory footprint of the tab grows until it crashes. The behavior is consistent in Chrome/Edge, but FireFox appears to aggressively wipe out chunks now and then when it gets close to running out of memory.

### To Reproduce
I'm working on a [personal music locker service OSS project](https://github.com/POPWorldMedia/MLocker), and it has to upload thousands of files to an API. In small batches, it works fine. I believe I'm disposing of all the things. If I remove the `HttpClient` call and instead just read byte arrays into memory, these do not appear to create a memory problem. The files are typical MP3's of 3 to 10 MB each.

[Here's the component](https://github.com/POPWorldMedia/MLocker/blob/8fac9f500ec71431d7ee31ab6b5e89aa61f0cdff/src/MLocker.WebApp/Pages/Upload.razor#L1) doing the iteration:

```csharp
private async Task OnInputFileChange(InputFileChangeEventArgs e)
{
	var count = e.FileCount;
	var current = 1;
	var files = e.GetMultipleFiles(1000000);
	foreach (var file in files)
	{
			_percentage = Convert.ToInt32(Math.Round((decimal)current / count * 100, MidpointRounding.ToPositiveInfinity));
			await using var stream = file.OpenReadStream(100000000);
			var isSuccess = await MusicService.Upload(file.Name, stream);
			if (!isSuccess)
			{
				_showErrors = true;
				_errors.Add(file.Name);
			}
			current++;
			stream.Close();
			await stream.DisposeAsync();
	}
	await MusicService.UpdateSongs();
	_percentage = 0;
}
```

And here's the [`MusicService.Upload()` method](https://github.com/POPWorldMedia/MLocker/blob/8fac9f500ec71431d7ee31ab6b5e89aa61f0cdff/src/MLocker.WebApp/Repositories/UploadRepository.cs#L26):

```csharp
public async Task<bool> UploadFile(string fileName, Stream stream)
{
    if (stream.Length == 0)
        return false;
    using var content = new MultipartFormDataContent();
    content.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data");
    using var streamContent = new StreamContent(stream, Convert.ToInt32(stream.Length));
    content.Add(streamContent, "file", fileName);

    var apiKey = await _config.GetApiKey();
    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(apiKey);
    using var response = await _httpClient.PostAsync(ApiPaths.Upload, content);
    streamContent.Dispose();
    content.Dispose();
    var result = response.IsSuccessStatusCode;
    response.Dispose();
    return result;
}
```
`_httpClient` is injected as described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1). I wonder why the upload is "handled by the browser" instead of some wholly managed code version of `HttpClient`.

In Chrome/Edge, you can watch the task manager for the tab's memory to increase linearly until it runs out of memory and dies. This is around 2,500 files on my machine (about 20 gigs on the browser tab). On Firefox, when it gets close to running out of memory, it drops several gigs at a time. Firefox does survive longer at around 6,200 files, but interestingly it doesn't update the progress bar the entire time (the `_percentage` above is bound to a Bootstrap progress bar).

### Exceptions (if any)
n/a

### Further technical details
- ASP.NET Core version: v5.0 RC2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS2019 preview

**Comment by javiercn** [comment]
@jeffputz based on your description there seems to be no memory leak here.

I would say the scenario you are describing here is stretching the limits of what InputFile is able to do, and you might be better off handling this bit directly within JavaScript for such a large amount of files.

As to what is happening here, I believe that this is likely a bug in Chrome/Edge that continue to allocate memory until the browser itself crashes. 

I'm saying that based on the fact that I don't see anything obviously wrong with this code nor with the code in the inputfile component that handles the stream and based on the fact that as you mention, Firefox will free up several gigs of memory, which makes me believe this has to do with how the browser implementation manages the memory and that is the ultimate cause of the crash, since as you mention, Firefox seems to be dealing with the situation correctly.
