### ISSUE TITLE
Blazor wasm - setting culture on startup errors

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#27036]
I am upgrading a blazor wasm application that, previously set the culture on startup like this:

```    
    public class Program
    {
        private static WebAssemblyHost _host;
        public static async Task Main(string[] args)
        {
            CultureInfo.CurrentCulture = new CultureInfo("en-GB");
            _host = CreateHostBuilder(args).Build();     
            await _host.RunAsync();
        }
    }

```

Since upgrading to RC2 this throws in the browser:

![image](https://user-images.githubusercontent.com/3176632/96467503-e4b22400-1222-11eb-8d35-95dcfc652534.png)

The solution indicates adding some property to the csproj to allow all globalisaton data to be loaded - it assumes if its being set on startup then you want to allow culture to be changed at runtime. However in my case I just want to specify the particular culture. How do I specify "en-GB" for instance without having to load all culture data?

**Comment by pranavkm** [comment]
Hi @dazinator, you can configure the WebAssembly application culture as part of Blazor.start:

```js
        Blazor.start({
            applicationCulture: 'en-GB'
        });
```

https://github.com/dotnet/AspNetCore.Docs/pull/20231 covers adding this to our docs.

**Comment by dazinator** [comment]
That works, thanks for a quick turnaround!
