### ISSUE TITLE
[NET 5.0] Use SignarR server in console app (Sdk="Microsoft.NET.Sdk")

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#27031]
Hello guys, i try actually to create a console app :
- which can expose signalr hub
- which can be deployed with clickOnce

I'm able to create a console app which expose signalr hub, the is a lot of examples, but the project need to be of type "Microsoft.NET.Sdk.Web".
With this type of project, it seem i don't have the wizard to deploy my app with clickOnce (maybe the problem is here)

If i create a classic console app (Sdk="Microsoft.NET.Sdk"), I have the clickOnce wizard when i publish, 
But with this type of project, it seem i don't have everything to make my signalr hubs working.

I try to install manually nuget package Microsoft.AspNetCore but even with this im unable for example to find a reference to ConfigureWebHostDefaults.

So there is a way actually to do this in .NET 5.0 ? 

thanks !

**Comment by BrennanConroy** [comment]
You should be able to use Microsoft.NET.Sdk if you add `<FrameworkReference Include="Microsoft.AspNetCore.App" />` to your csproj.

I'm not familiar with the "clickOnce wizard" so if you want that to work you might have to find the owners of it and ask them.

**Comment by julienGrd** [comment]
@BrennanConroy thank you it works perfectly !
