### ISSUE TITLE
NullReferenceException is thrown by Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler

### ISSUE THREAD

**Issue by hankovich** [dotnet/aspnetcore#27035]
`RedirectHandler` [is added by default](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Testing/src/WebApplicationFactoryClientOptions.cs#L74) to a `HttpClient` produced by `WebApplicationFactory<TEntryPoint>`.

When the server returns a result with one the following codes

- 301 Moved Permanently
- 302 Found
- 307 Temporary Redirect
- 308 Permanent Redirect

but without a `Location` header, `NullReferenceException` is thrown [here](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Testing/src/Handlers/RedirectHandler.cs#L137).

For all mentioned status codes rfc7538 and rfc7231 say 'The server **SHOULD** generate a Location header field', so it's not required.

Expected behavior: Exception is not thrown, response is returned as is (like HttpClient does in the same situation).

**Comment by marcusturewicz** [comment]
Can this be closed?

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/pull/28276.
