### ISSUE TITLE
feature “Control Startup class activation” doesn't work

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27039]
Help with feature “Control Startup class activation”
->

```
 var host = Host.CreateDefaultBuilder()
            .ConfigureWebHost(builder =>
            {
                builder.UseStartup(context => new Startup(logger));
            })
            .Build();
```
When I use Project Sdk=”Microsoft.NET.Sdk.BlazorWebAssembly”, I get error: ‘IHostBuilder’ does not contain a definition for ‘ConfigureWebHostDefaults’
When I set Project Sdk=”Microsoft.NET.Sdk.Web”, project see ConfigureWebHostDefaults, but project doesn’t work….

**Comment by pranavkm** [comment]
FYI @tatti9018. The announcement repo is not meant for general purpose issues.

**Comment by tatti9018** [comment]
Sorry for wrong place. Waiting for help

**Comment by captainsafia** [comment]
@tatti9018 Can you share what you're trying to do here?

**Comment by tatti9018** [comment]
I created Blazor Client side project - template base on .net 5 rc2
and I want to use feature “Control Startup class activation” -> https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#control-startup-class-activation

**Comment by mkArtakMSFT** [comment]
Thanks for the details, @tatti9018.
`Startup` is not a concept we use in Blazor WebAssembly apps. As a result, the referenced content is not applicable to Blazor WebAssembly.
Can you share more details why you're trying to use that approach in your app?

**Comment by tatti9018** [comment]
> `Startup` is not a concept we use in Blazor WebAssembly apps. As a result, the referenced content is not applicable to Blazor WebAssembly.
  
Thanks for answer. I misunderstood this feature.
