### ISSUE TITLE
Empty cookie header is added by Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler

### ISSUE THREAD

**Issue by hankovich** [dotnet/aspnetcore#27037]
CookieContainerHandler [is added by default](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Testing/src/WebApplicationFactoryClientOptions.cs#L78) to a `HttpClient` produced by `WebApplicationFactory<TEntryPoint>`.

It [adds a `Cookie` header](https://github.com/dotnet/aspnetcore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Testing/src/Handlers/CookieContainerHandler.cs#L46) even if there are no cookies to add.

Steps to reproduce:

```
var client = new WebApplicationFactory<Startup>().CreateClient();
var result = await client.GetStringAsync("/health"); 
```
The request to `/health` was send along with `Cookie: `.

Expected behavior: No header is added when there are no cookies to add.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @hankovich.
Feel free to send us a PR if you think you have a solution. We will consider it.
