### ISSUE TITLE
New `dotnet watch run` options should be configurable in the project file

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#27048]
`dotnet watch run` added [new configuration options in .NET 5](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1#dotnet-watch-configuration). These are currently only configurable via environment variables. We should support setting these options via MSBuild properties, which could be set in the target project file. Values from MSBuild should override any values set via environment variables.

Environment variable | MSBuild property
--- | ---
`DOTNET_WATCH_SUPPRESS_MSBUILD_INCREMENTALISM` | `DotnetWatchSuppressMsbuildIncrementalism`
`DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER` | `DotnetWatchSuppressLaunchBrowser`
`DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH` | `DotnetWatchSuppressBrowserRefresh`

**Comment by mkArtakMSFT** [comment]
Closing as nobody asked for it.
