### ISSUE TITLE
How to handle multi value cookies in ASP.NET Core?

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2704]
_From @304NotModified on Friday, May 5, 2017 9:03:14 AM_

In the full .NET framework we have support for multi value cookies. e.g. a cookie could have multiple values:

```c#
HttpCookie aCookie = new HttpCookie("userInfo");
aCookie.Values["userName"] = "patrick";
aCookie.Values["lastVisit"] = DateTime.Now.ToString();
```

See also [the docs about `HttpCookie.Values` on MSDN](https://msdn.microsoft.com/en-us/library/system.web.httpcookie.values%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) and [ASP.NET Cookies Overview on MSDN](https://msdn.microsoft.com/en-us/library/ms178194.aspx?f=255&MSPPError=-2147217396).

With ASP.NET Core, the multi value cookie seems to be gone. There is no `HttpCookie.Values` and [`HttpRequest.Cookies`](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.http.httprequest#Microsoft_AspNetCore_Http_HttpRequest_Cookies) returns a [`IRequestCookieCollection`](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.http.irequestcookiecollection#Microsoft_AspNetCore_Http_IRequestCookieCollection) which like a  `dictionary` from `string` to `string`

How should I now create and read multi value cookies in ASP.NET Core? How could I read the multi value cookies created in Full ASP.NET and read them in ASP.NET Core? 

_Copied from original issue: aspnet/HttpAbstractions#831_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, May 5, 2017 9:06:56 AM_

That's all additional formatting within the cookie value. No there's no support for that in Core, but it could be layered on top of the existing APIs.

**Comment by aspnet-hello** [comment]
_From @304NotModified on Friday, May 5, 2017 1:16:01 PM_

any idea what the formatting was? Was it encoded as an URL (key1=a&key2=b)? That's unclear to me.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, May 5, 2017 1:36:43 PM_

Does it matter? Are you trying to read cookies from System.Web? Or do you just need your own format?

**Comment by aspnet-hello** [comment]
_From @304NotModified on Friday, May 5, 2017 1:39:11 PM_

I thinking to support the old style, for NLog.Web. But maybe it's unneeded hassle, not sure about that.

**Comment by davidfowl** [comment]
We have no API for this. We'd need an API proposal for it and if we do this, it wouldn't be part of the built in cookie collection. It would need to be something opted into per cookie (like a parser).
