### ISSUE TITLE
`dotnet watch` doesn't detect new files being added

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#27046]
We have received reports that when using `dotnet watch` to monitor changes to a project, adding new files is not detected. We should investigate the extent of this issue (e.g. which operating systems, path depth, file types, etc.) and look at ways to fix it.

**Comment by RickStrahl** [comment]
I got a PR for this recent in my LiveReload repo and added it in there. Basically the original code I had didn't check for directory creation or new file creation although files would be picked up after initial creation.

This PR addressed those scenarios:

https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload/pull/30

**Comment by jkotalik** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/8321
