### ISSUE TITLE
How to set ServerCertificateCustomValidationCallback in Blazor WASM ?

### ISSUE THREAD

**Issue by tatti9018** [dotnet/aspnetcore#27050]
In Blazor Server side on Authentication I can write

```
services.AddAuthentication()..
            .AddOpenIdConnect(options =>
                {
 options.BackchannelHttpHandler = new HttpClientHandler
                    {
                        ServerCertificateCustomValidationCallback = (sender, cert, chain, policyErrors) =>
                        {                                
                                return true;                                
                        }
                    };
});
```

How can I set ServerCertificateCustomValidationCallback in Blazor WASM(Oidc Authentication)?

Because options haven't similar properties in OidcAuthentication

```
builder.Services.AddOidcAuthentication(options =>
            {
 options.ProviderOptions.Authority =hostUrl;
                options.ProviderOptions.ClientId = clientId;
});
```

**Comment by javiercn** [comment]
@tatti9018 thanks for contacting us.

You don't have control over those settings when you are in a Browser context, what are you trying to achieve by doing that?

**Comment by tatti9018** [comment]
Api uses self signed certificate.

**Comment by captainsafia** [comment]
@tatti9018 If you're deploying your application to production, you'll need to make sure that the certificate is trusted.

For local development, you can try trusting the local cert on your machine. Alternatively, you can try running Edge with web security checks disabled by running the `edge.exe –ignore-certificate-errors`. **Note: this is only for development. Don't use this browser for anything else.**
