### ISSUE TITLE
FxCop error report

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#27058]
```csharp
        public async Task<IActionResult> Password(PasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
```
In this case FxCop will return a CA1062 error:Validate arguments of public methods
But the ModelState can't be valid if the model is null.

So there's something to do here.

**Comment by captainsafia** [comment]
@terrajobst Can you transfer this to the dotnet/rosyln-analyzers for their input on this?

**Comment by pranavkm** [comment]
FYI @mavasani.

**Comment by mavasani** [comment]
CA1062 is a generic rule which does not understand project/platform specific public APIs that guarantee non-null input from all callsites. In general, all public APIs can be invoked with null inputs, hence the CA1062 violation here is by design.

**Comment by mkArtakMSFT** [comment]
Thanks @mavasani .

@JulienM28 based on @mavasani  response above consider not using FxCop in your project.
