### ISSUE TITLE
Rename the types in Microsoft.Net.Http.Headers

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2706]
_From @davidfowl on Monday, April 10, 2017 12:19:36 AM_

When using this library in a project that has `HttpClient` there are type conflicts everywhere.

_Copied from original issue: aspnet/HttpAbstractions#813_

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, June 26, 2017 2:49:08 PM_

Prefix with something? Or something different?

**Comment by natemcmaster** [comment]
Removing from Backlog and assigning to @muratg for re-triage.

Per our last discussion w.r.t. shared frameworks and packages, we do not plan to ship this as a standalone NuGet package anymore. We are interested in either (A) making this API part of corefx or (B) making the API entirely internal:

- (A) Consider moving this into corefx
  * Need to work with the corefx team to de-dup our APIs and merge them together where possible
  * Update our source code to use new corefx APIs and remove them from this repo
- (B) Investigate making this internal
  * Currently exposed in AspNetCore.Http.Extensions

cc @Tratcher @Eilon @davidfowl

**Comment by Tratcher** [comment]
How would internal work in this case? They types are used in several other packages.

**Comment by natemcmaster** [comment]
This is part of the "more investigation required". We need more data on just how many public APIs would be affected.

**Comment by muratg** [comment]
@Tratcher could you please take the helm on this one?

**Comment by Tratcher** [comment]
Discussed this with @davidfowl. Recommend backlog / won't fix for 3.0. Un-assigning.

**Comment by davidfowl** [comment]
This isn't happening. We should look at re-unifying with the BCL types (assuming they get spanified).
