### ISSUE TITLE
blazor client awaited methods not executed after first await

### ISSUE THREAD

**Issue by Krangth** [dotnet/aspnetcore#27064]
### Describe the bug
`OnAfterRenderAsync` exits before the all code executes. Only the first line I await is ever executed. If I add `await Task.Delay(1000);` as the first line of code then the code works correctly. If I add it as the last line of code then it has no affect and the code returns to only the first await executing. 

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await JsRuntime.Create(Map, linkWithToken);
            foreach (var marker in Map.Markers)
            {
                await JsRuntime.AddMarker(Map, marker, new MouseEvent { LatLng = marker.Position });
            }
        }
    }

### Further technical details
- ASP.NET Core version 5.0.0-rc.2.20475.6
- VS 2019 Preview 16.8.0 Preview 4

**Comment by captainsafia** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Krangth** [comment]
ehh, okay. That will take some time. I was hoping the answer would be simple for why things were not being awaited. I'll reply again in a few days when I've had time to isolate the code.
