### ISSUE TITLE
 [Blazor] Virtualize component has to render the placeholder in the first render cycle

### ISSUE THREAD

**Issue by LeonSpors** [dotnet/aspnetcore#27060]
### Describe the bug
The placeholder is not shown after the first render cycle.

### To Reproduce
See [this repo](https://github.com/LeonSpors/br-blazor-virtualize-placeholder-render).

### Further technical details
- .NET 5 RC2
- VS 2019 Preview 16.8.0 Preview 4
```bash
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]```

**Comment by captainsafia** [comment]
@LeonSpors Can you share what behavior you expect here?

**Comment by LeonSpors** [comment]
I do expect that it shows the placeholder first. Or could you provide an option to configure this behavior?

**Comment by SteveSandersonMS** [comment]
I think the reason is that `<Virtualize>` doesn't know the size of the scroll area until *after* the first render (because that's the first time when an element exists so we can measure its size). As such it doesn't know how many items to render until after the first render cycle, and thus it doesn't render any, and hence there are no placeholders to show. So overall it sounds like it's by design, unless I'm misunderstanding the request.

If this is a major problem in your application please let us know (with details about why) and we can try to help you come up with a different way to show the kind of UI you need.

**Comment by LeonSpors** [comment]
Indeed, its still a problem in my case. Let me explain to you what I am doing. Actually it begins with a data request in the very first render cycle. This data request contains the identifier of any possible shown object. Afterwards I do render the '<Virtualize>' component and it shows nothing until the first request of item set is completed. This can take a while sometimes. I would like to have some placeholder here.

Summarized I do have the count of objects before I render the '<Virtualize>' component.

**Comment by SteveSandersonMS** [comment]
@LeonSpors I see. Sounds like the unusual thing about your situation is that you know the item count *before* the you retrieve the first chunk of data. The more common case is finding out the item count as part of retrieving the first chunk. We could consider adding a feature for this in the future if we get evidence that it's a more common scenario than we thought.

In the meantime I'd recommend modelling the "loading" phase as part of your own component logic. For example, have an `isLoading` bool flag that you set to true initially, and set back to false at whatever time makes sense in your case (e.g., after the first chunk is loaded). Then in the markup portion of your component, use that flag to toggle some other "loading" indicator. If you wanted, you could use CSS to position the loading indicator on top of the `<Virtualize>` element so it appears integrated.
