### ISSUE TITLE
Add asp-append-version support to video > source HTML tag

### ISSUE THREAD

**Issue by bradlis7** [dotnet/aspnetcore#27074]
### Is your feature request related to a problem? Please describe.
I'd like to use asp-append-version for video > source tag, but it doesn't work for this tag.

### Describe the solution you'd like
Here's the markup I am using.

```
<video>
<source src="vid.mp4" asp-append-version="true"/>
</video>
```

Make it work as it does on an `<img>` tag.

**Comment by bradlis7** [comment]
I'm using a workaround found at https://stackoverflow.com/a/45088852/179311 for anyone needing this feature.

### Extension

```C#
public static class HttpContextExtensions {
    public static string AddFileVersionToPath(this HttpContext context, string path) {
        if (path.StartsWith("~")) {
            path = context.RequestServices.GetRequiredService<IUrlHelper>().Content(path);
        }
        return context
            .RequestServices
            .GetRequiredService<IFileVersionProvider>()
            .AddFileVersionToPath(context.Request.PathBase, path);
    }
}
```

### Usage in Razor File

```HTML+Razor
<video poster="@(Context.AddFileVersionToPath("~/assets/video1.png"))">
    <source src="@(Context.AddFileVersionToPath("~/assets/video1.webm"))" type="video/webm"/>
    <source src="@(Context.AddFileVersionToPath("~/assets/video1.mp4"))" type="video/mp4"/>
</video>
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
