### ISSUE TITLE
what is  NonShipping ?

### ISSUE THREAD

**Issue by wjkhappy14** [dotnet/aspnetcore#27086]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error : “F:\aspnetcore\artifacts\packages\Debug\NonShipping\”not exist 。 [F:\aspnetcore\AspNetCore.sln]

**Comment by javiercn** [comment]
@wjkhappy14 thanks for contacting us.

That means artifacts that we generate as part of the build but aren't "shipped" in the sense they are not distributed through nuget or the SDK or other means.

**Comment by wjkhappy14** [comment]
thks ,but how to resolve  ? i want   build/debug by myself ...
