### ISSUE TITLE
`dotnet watch run` shouldn't disable the browser refresh logic injection on Linux

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#27081]
`dotnet watch run` today disables the logic that facilitates the auto-browser launch and refresh feature when running on Linux, as determining the browser to launch isn't straightforward on Linux (on Windows and Mac we can just `Process.Launch` the URL and the OS does the rest).

Assuming the appropriate config value is present in the `launchSettings.json` file, `dotnet watch run` should still wire-up the app for browser refresh when on Linux, even if it can't launch the browser itself.

**Comment by pranavkm** [comment]
This was resolved as part of https://github.com/dotnet/sdk/pull/15340.
