### ISSUE TITLE
Placeholder not showing in virtualized content

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspnetcore#27080]
### Describe the bug
When using `<Virtualize>` with `<Placeholder>` the placeholder content is not rendering despite the whitespace of the yet-to-be-virtualized content showing.

### To Reproduce
Repo: https://github.com/timheuer/BlazorPlaceholderBug - is a modified default template adding more to the weather data service and changing `FetchData.razor` to use `Virtualize`

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

**Comment by mkArtakMSFT** [comment]
@timheuer it looks like you're trying to render an already-loaded list in your virtualize component. To virtualize consider specifying the `ItemProvider` instead. That will allow you to virtualize the loading of the items.

**Comment by SteveSandersonMS** [comment]
I think the reason why you sometimes see whitespace while scrolling is just that it takes some nonzero time to render each chunk of data. We can get the real item data there just as fast as we could get the placeholder there, so there's no reason why we'd use the placeholder - we just show the real data as fast as possible.

**Comment by timheuer** [comment]
@mkArtakMSFT I'm just following the docs :-) https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0#placeholder

There is no indication that `Placeholder` should only be used with ItemsProvider where the items are also virtualized.  

I recommend 
- [ ] Update the docs to make clear that `Placeholder` really is only useful with ItemsProvider @danroth27 
- [ ] Can we have an analyzer that would have clued me in to this absent documentation?
