### ISSUE TITLE
Microsoft.AspNetCore.Mvc.ModelBinding.ModelAttributes is public but its constructors are not

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#27096]
### Is your feature request related to a problem? Please describe.
I have developed a custom implementation of `IModelMetadataProvider` that extends `EmptyModelMetadataProvider` and overrides the `CreatePropertyDetails` method to modify the list of attributes that are returned on model properties. In order to accomplish this, I need to create my own instances of `ModelAttributes` that contain the actual attributes that I want ASP.NET Core to use for the properties - the `GetAttributesForProperty` methods defined on `ModelAttributes` are not sufficient.

However, all of `ModelAttributes`'s properties are read-only, so I cannot mutate the existing instances returned by the implementation on `EmptyModelMetadataProvider` (which is actually just delegating to `DefaultModelMetadataProvider`). And all `ModelAttributes`' constructors are `internal`, so there is no way for me to create an instance (or even a subclass). I'm forced to resort to reflection to obtain and invoke the relevant constructor to create the `ModelAttributes` instances I require, which is sub-optimal for many reasons.

### Describe the solution you'd like
Simple: change the access modifier of the constructor `internal ModelAttributes(IEnumerable<object> typeAttributes, IEnumerable<object> propertyAttributes, IEnumerable<object> parameterAttributes)` to `public`. I'm willing to submit a PR for this if the team is happy to allow this change.

Complex: implement a pluggable `IModelAttributesProvider` infrastructure using DI to completely abstract out the concept of retrieving model metadata. This is a better long-term approach but has additional overhead and complexity that might make it infeasible, especially considering it will likely see little use.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to do, as it adds more fragile extensibility areas to the framework.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by IanKemp** [comment]
I thought the whole point of a framework was extensibility.

Clearly I was wrong.
