### ISSUE TITLE
Cannot use Scoped dependencies in HealthCheck services

### ISSUE THREAD

**Issue by mustafasadikot** [dotnet/aspnetcore#27099]
Hi Team,

I have a factory(IDomainScopeFactory) that provides EF core contexts based on settings that I set from a middleware. The factory and other providers are registered as scoped services in the startup.cs.

I want to create a HealthCheck service(AddSystemHealthChecks) that uses the same factory for creating contexts. Hence I have added them as dependencies in my HealthCheck provider. I have registered the HealthCheck provider as Scoped service in startup and still some of my services become transient inside the factory. Not sure why!!!

     public static IServiceCollection AddSystemHealthChecks(
        this IServiceCollection services)
    {
      services.AddScoped<DBContextHealthCheck>();
      IHealthChecksBuilder healthChecksBuilder = services.AddHealthChecks();
      healthChecksBuilder.AddCheck<DBContextHealthCheck>("Model Context");

      return services;
    }
    public class DBContextHealthCheck : IHealthCheck   {
    private readonly IDomainScopeFactory _domainScopeFactory;
    private readonly IAmbientDbContextLocator _ambientDbContextLocator;

    public DBContextHealthCheck(IDomainScopeFactory domainScopeFactory, IAmbientDbContextLocator ambientDbContextLocator)
    {
      _ambientDbContextLocator = ambientDbContextLocator;
      _domainScopeFactory = domainScopeFactory;
    }

      public class DBContextHealthCheck : IHealthCheck
     {
      private readonly IDomainScopeFactory _domainScopeFactory;
      private readonly IAmbientDbContextLocator _ambientDbContextLocator;
  
    public DBContextHealthCheck(IDomainScopeFactory domainScopeFactory, IAmbientDbContextLocator ambientDbContextLocator)
    {
      _ambientDbContextLocator = ambientDbContextLocator;
      _domainScopeFactory = domainScopeFactory;
    }

    public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
      {
      try
      {
        using (var scope = _domainScopeFactory.Create())
        {
          var dbContext = _ambientDbContextLocator.Get<ModelContext>();
          var canConnect = await dbContext.Database.CanConnectAsync();
          if (canConnect)
          {
            return HealthCheckResult.Healthy();
          }
          else
          {
            return HealthCheckResult.Unhealthy();
          }
        }
      }
      catch (Exception ex)
      {
        return new HealthCheckResult(context.Registration.FailureStatus, exception: ex);
      }
    }
  }

 .NetCore version - 3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This seems to be an issue with your factory code. From scanning through your description it sounds like the factors keeps creating new instances every time the `create` is called, which seems correct. And you seem to expect that the instances shouldn't be created rather reused.
There doesn't seem to be any indication that there is anything wrong with the framework here. If you have further questions regarding this we recommend using `StackOverflow` forum to get help with identifying the issue in your code.
