### ISSUE TITLE
Blazor WASM : .NET 5 RC2 : Looking for non referenced native DLLs. Resource has been Blocked  

### ISSUE THREAD

**Issue by mclose90** [dotnet/aspnetcore#27097]
### Describe the bug
We recently upgraded our working project to .NET 5 RC2 from .NET 5 RC1 and without any code changes began to see the error in the screenshot provided. The only change that we made was to update the .NET version. These Lua dlls are native windows c++ dlls that we use from one library on select projects but are not ever loaded by the one in question. 

This issue only presents itself after publish and so far none of our engineers have seen this issue while working with Blazor through visual studios 2019 preview while running debug only occurs when the project is published. 

![image](https://user-images.githubusercontent.com/41022806/96742579-134e0d00-1391-11eb-8401-4b6c6cc6b9ee.png)

The publish wwwroot/_framework folder does contain this:
![image](https://user-images.githubusercontent.com/41022806/96743282-d1719680-1391-11eb-8750-a878797d4207.png)
 
Where in our native x86 / x64 folders that we use on other projects does contain the lua files :
![image](https://user-images.githubusercontent.com/41022806/96743381-f2d28280-1391-11eb-8cf6-e46d98a2a82f.png)

I played with copying them directly to the _framework folder to see if somehow we could work around this issue for the near future. After many combinations I found that moving the lua51 files from the x64 folder and the lua53 & luajit files from the x86 folder directly to the _framework folder would satisfy the blazor.webassembly.js script but this is not ideal.

### To Reproduce

1.) Clone down : https://github.com/mclose90/Net5RCDllIssue

2.) Publish the Blazor Project 
![image](https://user-images.githubusercontent.com/41022806/96746174-e7cd2180-1394-11eb-8dbf-3802d0516e01.png)

3.) Open the published wwwroot folder with VS Code 
![image](https://user-images.githubusercontent.com/41022806/96746381-1e0aa100-1395-11eb-8fba-2f5867ea8c4f.png)

4.) I then host the files with the VS Code Extension Live Server
![image](https://user-images.githubusercontent.com/41022806/96746514-42ff1400-1395-11eb-98c4-91ecc9436bb2.png)
Once the extension is installed just goto the wwwroot folder and start the webserver.
![image](https://user-images.githubusercontent.com/41022806/96746612-5dd18880-1395-11eb-9f75-52619edd0ba2.png)

5.) Web page should open and you will see the error that is being received. 
![image](https://user-images.githubusercontent.com/41022806/96746711-7772d000-1395-11eb-96dd-9c8e112135b8.png)

**Comment by javiercn** [comment]
@mclose90 thanks for contacting us.

Blazor webassembly doesn't support native dependencies (even if they are not loaded), we would recommend you factor those dependencies out of your Blazor Webassembly application

**Comment by mclose90** [comment]
Why does the blazor js even look for those files at all?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mclose90.
Can you please share a small repro project so that we can look into this?

**Comment by mclose90** [comment]
> Thanks for contacting us, @mclose90.
> Can you please share a small repro project so that we can look into this?

https://github.com/mclose90/Net5RCDllIssue

Please see the reproduce section of original post for step by step

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
