### ISSUE TITLE
Handle HTML '!' and don't yellow-bar on unexpected SyntaxKinds in TagHelperSemanticRangeVisitor

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#27100]
Currently if you do something like `<!input/>` in a razor file you will get a yellow-bar in VS because the TagHelperSemnaticRangeVisitor doesn't know what to do with that type and throws a `NotImplementedException`. Firstly we should handle the `!` properly, and secondly let's do a more gentle `Debug.Fail` instead of a `NotImplementedException`. That way if we don't know what to do with a SyntaxKind we'll be warned in Develop mode, but end-users won't get frustrating errors.

**Comment by TanayParikh** [comment]
@ryanbrandenburg can we move this to `Done` from `Triage`?
