### ISSUE TITLE
Tabs/spaces from the ASP.NET Core Razor Language Services options are not respected

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#27101]
I'm facing several issues when editing `.razor` files which contain HTLM markup and C# code as well in Visual Studio 2019. Most of the problems occur when editing the `@code { }` block.

Issues:

- VS ignores TAB settings I'm using "Keep tabs" setup and in some cases it works but sometimes new lines inserted with spaces
- Indentations work really hectic as well, writing open and close braces `{ }` and breaking them into new lines
- Typing in constant values e.g. numbers `x = 0` getting irrelevant IntelliSense support and will replace value `0` to some random type or keyword...
- IntelliSense autocomplete duplicates leading `_` to `__` e.g.: `_activeItem` to `__activeItem`

**Underscore naming issue:**
![image](https://user-images.githubusercontent.com/7632824/96767125-5ed9d880-13dc-11eb-80a1-3708a7690bd5.png)
![image](https://user-images.githubusercontent.com/7632824/96767283-9c3e6600-13dc-11eb-9660-cfafcb5eae09.png)

**Tab settings:**
![image](https://user-images.githubusercontent.com/7632824/96766398-503ef180-13db-11eb-895a-981c6a52e444.png)

 **Irrelevant suggestions:**
![image](https://user-images.githubusercontent.com/7632824/96767639-140c9080-13dd-11eb-8d95-38aae4e3c8b9.png)

**Comment by VincentVespa** [comment]
I'm also experiencing these issues, but with an additional issue that causes Intellisense to autocomplete where it will complete with the highlighted suggestion after I hit **any** non-alphanumeric key.  It makes VS extremely irritating to work with.
![razorissue](https://user-images.githubusercontent.com/35957106/101980330-28754880-3c2a-11eb-909d-5d4ff8d2f87c.gif)

**Comment by NTaylorMullen** [comment]
> I'm also experiencing these issues, but with an additional issue that causes Intellisense to autocomplete where it will complete with the highlighted suggestion after I hit **any** non-alphanumeric key. It makes VS extremely irritating to work with.

This should be fixed in 16.9 😉

**Comment by NTaylorMullen** [comment]
Intent here is to talk with @danroth27 on what the expected experience is for end users and then make sure the "right thign" happens whether it be supporting or not supporting different langauge configurations for tabs/spaces

**Comment by allisonchou** [comment]
Resolved in https://github.com/dotnet/aspnetcore-tooling/pull/3317.
