### ISSUE TITLE
@{ block format on type adds New Line on pressing ';'

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27102]
![BracketNewLine](https://user-images.githubusercontent.com/14852843/96770718-8eb1bd80-1395-11eb-9727-67c2cb514d97.gif)

I was anticipating either:
 
1. Final space added-> `@{ Debugger.Launch(); }`
2. Both new lines

```
@{
    Debugger.Launch();
}
```

**Comment by NTaylorMullen** [comment]
This still repros on latest 16.9-Preview3

**Comment by sharwell** [comment]
This one is rough. `FormattingContext.Indentations` assumes that each line starts in one context, and contains at most 1 transition to a different context. The formatter cannot represent lines with more than one context switch, such as single-line elements that transition and then transition back.
