### ISSUE TITLE
API templates unnecessarily install JwtBearer and OpenIDConnect packages

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27105]
Run `dotnet new api`. Open the generated csproj

**Expected**

We should have a single reference to the Swashbuckle package

**Actual**

The template includes JwtBearer and OpenIdConnect packages

**Comment by MCCshreyas** [comment]
Hi @pranavkm, I was not able to replicate this issue.  
![image](https://user-images.githubusercontent.com/17148381/97070344-311bac00-15f5-11eb-8049-46ee7f763aba.png)

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/pull/28495
