### ISSUE TITLE
Consider enabling CS1591 in AspNetCore by default for src projects

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27106]
This check ensures every public API has a XML doc associated with it. As part of https://github.com/dotnet/aspnetcore/issues/26397 we enabled this in a fair majority of the projects in the repo. For 6.0 we could invert it so that projects have to opt out of this. This should help us narrow down projects missing documentation and correct them.

**Comment by dougbu** [comment]
This duplicates #12067
