### ISSUE TITLE
.Net 5 RC2 - Blazor Wasm - AAD B2C SignUpSignIn catch error 'AADB2C90118' to start Password Reset userflow

### ISSUE THREAD

**Issue by TeguSolutions** [dotnet/aspnetcore#27119]
Hello,

I am working on a Blazor Wasm project. I have just updated the project to the actually latest .Net 5 SDK, because I needed the LoginMode = "Redirect" feature for AAD B2C.
The AAD B2C is correctly set up and working from Azure and from the app as well.
The used userflows are: 
- Sign up and sign in (Recommended)
- Password reset (Recommended)

But I would like to initiate the password reset from the signup/signin flow. For this I need to catch the 'AADB2C90118' error message as I read, although the Authentication component is not triggered at all, meanwhile the expected response is visible for a moment. After some redirects the signup/signin page is shown again,

The used packages are:
Microsoft.AspNetCore.Components.WebAssembly - 5.0.0-rc.2.20475.5
Microsoft.AspNetCore.Components.WebAssembly.DevServer - 5.0.0-rc.2.20475.5
Microsoft.Authentication.WebAssembly.Msal - 5.0.0-rc.2.20475.5
Microsoft.Extensions.Http - 5.0.0-rc.2.20475.5
System.Net.Http.Json - 5.0.0-rc.2.20475.5

The Blazor app is .Net hosted with the server app, although it is not relevant because I am running without it.

The related stackoverflow question is:
https://stackoverflow.com/questions/64446655/blazor-wasm-with-aad-b2c-signupsignin-userflow-reset-password-how-to-catch-a

Can you please check it and give me feedback, that it should work, or it is a bad approach from me?

**Comment by javiercn** [comment]
@Satukan thanks for contacting us.

This is not a feature we support at the time, since there isn't/wasn't msal support for it at the time. We might consider supporting this in the future if we hear more feedback about it.

**Comment by Satukan** [comment]
Alright, I understand and the status is clear.
Thank you.

**Comment by javiercn** [comment]
@Satukan I'm keeping this open so that we can consider it on our planning process for the next release

**Comment by HMoen** [comment]
@TeguSolutions, we are sticking to the "Standard" user flows and the redirect (instead of popup) login mode for our app (WASM backed by API management) per https://github.com/dotnet/aspnetcore/issues/23638 until the next major release which will hopefully address this.

**Comment by morganc9** [comment]
Hello,
I need this feature as well... Can't see how I could use B2C in my blazor app if my users can't reset their password whenever they forget it.

**Comment by AlbertoPa** [comment]
> @Satukan I'm keeping this open so that we can consider it on our planning process for the next release

Just a note: the msal library has been upgraded in 5.0.3: https://github.com/dotnet/aspnetcore/pull/29226

**Comment by AlbertoPa** [comment]
This seems obsolete because AD B2C implemented self-service password reset, which is entirely done via the AD page.

**Comment by javiercn** [comment]
This is not needed. See [Set up a password reset flow - Azure AD B2C | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended) for details
