### ISSUE TITLE
.NET 5 rc2 AuthenticationSchemeOptions.ForwardDefaultSelector does not allow null to be returned with Nullable reference types

### ISSUE THREAD

**Issue by desjoerd** [dotnet/aspnetcore#27111]
### Describe the bug
The property [ForwardDefaultSelector](https://github.com/dotnet/aspnetcore/blob/25bd01f17d5f01fc78bea5eb5308b2c0d79e2889/src/Security/Authentication/Core/src/AuthenticationSchemeOptions.cs#L90) does not allow a null return because it's a `Func<HttpContext, string>` but I think it should be `Func<HttpContext, string?>` as in the summary of the property it is suggested that you should return null when you don't want to forward the authentication to a different scheme.

### To Reproduce
Add this to the ConfigureServices with `<Nullable>Enable</Nullable>` in the project.

```csharp
services.AddAuthentication()
    .AddCookie(options =>
    {
        options.ForwardDefaultSelector = ctx => 
            ctx.Request.Path.StartsWithSegments("/api", StringComparison.OrdinalIgnoreCase) ? "Bearer" : null;
    });
```

### Further technical details
- ASP.NET Core version 
5.0.0-rc.2.20475.17
- Include the output of `dotnet --info`
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 4.0

**Comment by pranavkm** [comment]
Thanks @desjoerd for the feedback. Looks like we missed updating the nullability of this API when annotating this assembly. It's unlikely we're going to be able to address this for 5.0. Consider suppressing the warning at the callsite for the time being. We should be able to address this in 6.0.

**Comment by desjoerd** [comment]
I already suppressed the error but wanted to give a heads-up so it can be fixed :).

You can close the issue or keep it open if it is used for tracking the fix

**Comment by lukefulliton** [comment]
I am interested in submitting a pull-request with the recommended code change outlined in the original description of this bug/issue.  Would my pull-request be permitted and considered even though the issue is already added to the next spring planning milestone?  @Tratcher @blowdart @pranavkm

**Comment by blowdart** [comment]
Apologies @lukefulliton, you asked just as I went on vacation.

Any PR wouldn't make it until .NET 6.0

**Comment by blowdart** [comment]
@pranavkm You merged a PR for this, did it fix the issue? If so can you close

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/pull/28214.
