### ISSUE TITLE
Auto-completing `@oninput` with `=` does not insert `""`

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#27129]
![wH85cu6bs2](https://user-images.githubusercontent.com/2008729/96936739-787e2d00-147b-11eb-9dbc-de16eece6f2a.gif)

**Comment by TanayParikh** [comment]
https://github.com/dotnet/aspnetcore-tooling/pull/1931

**Comment by NTaylorMullen** [comment]
We removed this  feature wholesale.
