### ISSUE TITLE
Completion Pop-out Wrong Location

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27127]
![Pop-out completion wrong location](https://user-images.githubusercontent.com/14852843/96936855-b3806080-147b-11eb-9e32-6257c0ffb788.gif)

**Comment by NTaylorMullen** [comment]
Putting in 16.9-P3 only to forward to platform to properly fix.

**Comment by NTaylorMullen** [comment]
No repro for me either.
