### ISSUE TITLE
Completion Variables Should Be Preferred Over Keywords

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27132]
Variables should be preferred over keywords.

![UnexpectedCompletionRankings](https://user-images.githubusercontent.com/14852843/96937281-a152f200-147c-11eb-9ca3-8924d4fdec80.gif)

**Comment by NTaylorMullen** [comment]
Goal here in 16.9-P3 is to validate that this is indeed fixed.

**Comment by NTaylorMullen** [comment]
@TanayParikh we believe this is fixed. If you could validate and close out ❤️

**Comment by TanayParikh** [comment]
Confirmed, working as expected now!
