### ISSUE TITLE
Razor C# colorization inconsistency

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27134]
With the new Razor editor in 16.9 P2 [30621.305.main]:

In C#
![image](https://user-images.githubusercontent.com/1874516/96937521-2e964680-147d-11eb-9dfa-e4e458fa730a.png)

In Razor:
![image](https://user-images.githubusercontent.com/1874516/96937547-38b84500-147d-11eb-8a35-65d49d6fbece.png)

**Comment by NTaylorMullen** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/26753
