### ISSUE TITLE
Typing `"` in an @onclick attribute does not auto-insert an ending `"`

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#27131]
![GmkJYVdxCc](https://user-images.githubusercontent.com/2008729/96937048-25f14080-147c-11eb-820a-a3c218b92dd8.gif)

**Comment by NTaylorMullen** [comment]
Putting in 16.9-P3 only to forward to platform to properly fix.

**Comment by NTaylorMullen** [comment]
Note: This is 99% chance external. The goal here is to gather enough information so we can file a bug on the CoreEditor so they know what's going on Etienne will be a good point of contact for this.

**Comment by allisonchou** [comment]
From investigating, WebTools needs to add a new auto-completion case for `"` - filed and provided additional details at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1267534.
Razor will also need to respond to these changes by adding support for `"` in our AutoInsertHandler. This should be a very minor change.

**Comment by allisonchou** [comment]
So it looks like the "proper" solution (according to an email thread with Etienne) may actually be to support language-configuration.json's AutoClosingPair property, tracked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1086473/. 

Unfortunately, there doesn't seem to be an ETA on when this task may be completed, but if this is a big user ask, we may want to ask the Editor team to prioritize it.

**Comment by NTaylorMullen** [comment]
Awesome, thanks Allison! Feel free to close this issue out as "duplicate"
