### ISSUE TITLE
Razor: typing quote overwrites assignment operator

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27138]
Version 16.9.0 Preview 2.0 [30621.305.main]
New Razor editor

I'm getting some weird behavior where typing a quote completes in strange and interesting ways. The issues start about half way through in the following GIF:

![MR6Gb1isBV](https://user-images.githubusercontent.com/1874516/96937874-fb07ec00-147d-11eb-84e4-baf311b93d12.gif)

**Comment by NTaylorMullen** [comment]
@danroth27 could you please re-validate this on latest dogfood builds (16.9-P2+)

**Comment by NTaylorMullen** [comment]
Validated on latest 16.9-Preview2. No longer an issue.
