### ISSUE TITLE
Double diagnostics in error list after building

### ISSUE THREAD

**Issue by allisonchou** [dotnet/aspnetcore#27141]
![doublediag](https://user-images.githubusercontent.com/16968319/96939285-82a32a00-1481-11eb-8241-c6c6bc24da0d.png)

Double diagnostics for an invalid/undefined variable appeared after trying to build a WebAssembly app.

**Comment by NTaylorMullen** [comment]
@allisonchou could you please try seeing if this reproduces on the latest VSMaster builds.

**Comment by allisonchou** [comment]
@NTaylorMullen I'm still seeing this in the latest main build (30712.122.main).
Not all errors are duplicated, but some seem to be:
![DoubleBuildErrors](https://user-images.githubusercontent.com/16968319/99014976-b44f6400-2508-11eb-8d33-fe74b9526156.gif)

**Comment by TanayParikh** [comment]
![image](https://user-images.githubusercontent.com/14852843/99298287-7a87a180-2817-11eb-88e4-7a2ea7fcbb1d.png)

This is still an issue with pull-diagnostics (verified locally on Main).

The source of the error seems to not be razor, notice the duplicated entries contain a "clickable"/linked error code, a value for the `Project` and a value for `Suppression State`.

**Comment by TanayParikh** [comment]
So this is due to a mix of C# push diagnostics on build & razor pull diagnostics. When both C# and razor pull diagnostics flags are enabled, this issue doesn't persist. Closing out with the acknowledgement that until both C# & Razor are using pull diagnostics by default, the issue will remain.

**Comment by NTaylorMullen** [comment]
@danroth27 so technically this means our new Razor editor will get duplicate diagnostics from building for a while. How "end of the world" does that sound?

**Comment by danroth27** [comment]
It's certainly not great, but not the end of the world.
