### ISSUE TITLE
Razor CSharp SemanticTokens can be out of date

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#27143]
![ce608ef3-c0a2-41b7-ad65-90f1a223ad91](https://user-images.githubusercontent.com/14987221/96939133-fee93d80-1480-11eb-9824-43259bbf1285.jpg)
The above Debug assertion was hit when someone did `@cod` (wait for completion) `E<enter>` in the middle of their Razor file.

I'm pretty sure what's happening here is that the version of the CSharp buffer on the C# language server and the version being tracked in Razor are not the same.

One solution I talked about with Taylor was to have ProvideSemanticTokensAsync start returning the HostDocumentSyncVersion. Once we have the HostDocumentSyncVersion the Razor LSP can try again or return null (rely on a retry from the client) if it's happened a couple times in a row.

**Comment by ryanbrandenburg** [comment]
Taylor also suggested trying to do a smart diff between the version of C# that the SemanticToken used and the one that we were comparing against.

**Comment by ryanbrandenburg** [comment]
I haven't seen this or anything like it in a little while, and I know that the Platform team did a lot of work in this area, so if it doesn't reproduce it might have already been fixed.

**Comment by NTaylorMullen** [comment]
Should validate if this still happens and if not to close it out.

**Comment by ryanbrandenburg** [comment]
No repro. @gundermanc did a lot of work in this area from the platform side, so it's not surprising it works now.
