### ISSUE TITLE
Missing intellisense for field in Razor component

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27149]
Version 16.9.0 Preview 2.0 [30621.305.main]

No intellisense for `specials`, which is a field in my Razor component:

![image](https://user-images.githubusercontent.com/1874516/96941749-1c6dd580-1488-11eb-9410-40a40e838cf7.png)

Here's the view of the code with the `specials` field:

![image](https://user-images.githubusercontent.com/1874516/96941755-2394e380-1488-11eb-81e0-9a1f73d7aced.png)

**Comment by NTaylorMullen** [comment]
Duplicate of: https://github.com/dotnet/aspnetcore/issues/27138
