### ISSUE TITLE
Razor curly brace sometimes isn't colorized correctly

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#27145]
![image](https://user-images.githubusercontent.com/1579269/96940937-e7608380-1485-11eb-89fb-7706e588cc9c.png)

Expected:
![image](https://user-images.githubusercontent.com/1579269/96940961-ff380780-1485-11eb-9243-598fe7de8bbb.png)

**Comment by NTaylorMullen** [comment]
Ajay did a boo boo and didn't capture logs. Unfortunately have to close.
