### ISSUE TITLE
Uncolored Attribute Value (App.razor)

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27148]
![image](https://user-images.githubusercontent.com/14852843/96941532-85088280-1487-11eb-80cb-b6635da5a1dd.png)

**Comment by ryanbrandenburg** [comment]
Seems like a dupe of https://github.com/dotnet/aspnetcore/issues/26975.

**Comment by NTaylorMullen** [comment]
> Seems like a dupe of #26975.

Ya I agree. @ryanbrandenburg now that you've worked around that locally could you validate that Tanay's scenario is also fixed and if so close this out? Opening the App.razor in a default template should be sufficient

**Comment by ryanbrandenburg** [comment]
Colorization is correct in App.razor now, closing.
