### ISSUE TITLE
Razor directive attribute completion when typing HTML attribute value

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27147]
Version 16.9.0 Preview 2.0 [30621.305.main]
New Razor editor

When typing the value for my `class` attribute ("pizza") I see directive attribute completions:

![image](https://user-images.githubusercontent.com/1874516/96941389-24794580-1487-11eb-9e2e-d5043b912eed.png)

**Comment by NTaylorMullen** [comment]
@danroth27 could you please re-validate this on latest dogfood builds (16.9-P2+)

**Comment by NTaylorMullen** [comment]
Validated on latest preview2. No longer repros.
