### ISSUE TITLE
Add WebSockets compressions support

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2715]
_From @vanillajonathan on Monday, September 19, 2016 2:26:50 PM_

The `WebSocket` class does not have support for extensions. Which is part of the rfc6455 standard:
https://tools.ietf.org/html/rfc6455#section-9

It should read the `Sec-WebSocket-Extensions` HTTP header from the client.

The `WebSocket` class does not expose a `Extensions` property.

_Copied from original issue: aspnet/HttpAbstractions#711_

**Comment by aspnet-hello** [comment]
_From @vanillajonathan on Monday, September 19, 2016 2:30:48 PM_

Depends on upstream support in `System.Net.WebSockets`.

Depends on issue dotnet/corefx#11874.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, September 19, 2016 8:10:27 PM_

Did you have any specific extensions you want to use?

**Comment by aspnet-hello** [comment]
_From @vanillajonathan on Tuesday, September 20, 2016 1:36:44 AM_

No, this exposes to the server the extension(s) that the client requests.
Then the server have to negotiate with the client and send back which extensions it supports.

Then any extension has to be implemented by the client and the server on top of this which only exposes the requested extension.

**Comment by 0x53A** [comment]
Just wanted to say that I am interested in having websocket compression support.

I assume that compression - just like other performance related stuff - is not something people actively express their interest in, until their app becomes too slow.

This would probably a big win for signal-r and a lot of other libraries using websockets.

**Comment by Tratcher** [comment]
Fyi the runtime prerequisites are tracked by https://github.com/dotnet/runtime/issues/20004

**Comment by Tratcher** [comment]
A new WebSocket compression API was approved in Runtime for 6.0: https://github.com/dotnet/runtime/issues/31088#issuecomment-754854011

We'll need to react to this. Bumping out of backlog but keeping it as blocked.

**Comment by Tratcher** [comment]
https://github.com/dotnet/runtime/pull/49304 has merged with new compression support. We should pick up a new runtime with the changes shortly.
