### ISSUE TITLE
No completion offered for property

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27151]
Version 16.9.0 Preview 2.0 [30621.305.main]
New Razor editor

I'm not getting any completion for the `ImageUrl` of `PizzaSpecial` instance in this case:

![image](https://user-images.githubusercontent.com/1874516/96942270-863aaf00-1489-11eb-90e9-53b26359fe92.png)

If I manually type everything out the code does eventually resolve:

![image](https://user-images.githubusercontent.com/1874516/96942331-aa968b80-1489-11eb-9fe2-0f219cd656d6.png)

**Comment by NTaylorMullen** [comment]
Duplicate of: https://github.com/dotnet/aspnetcore/issues/27138
