### ISSUE TITLE
Reduce FormReader allocations

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2716]
_From @davidfowl on Wednesday, September 7, 2016 10:50:26 PM_

1000 requests (I ran a console app in a loop) yields the following.

``` C#
while (true)
{
    Console.WriteLine("Press any key to run");
    Console.ReadLine();

    for (int i = 0; i < 1000; i++)
    {
        var formReader = new FormReader("name=David&Age=12&Developer=Chris");

        var form = formReader.ReadForm();
    }
}
```

![image](https://cloud.githubusercontent.com/assets/95136/18338415/713cdeaa-754d-11e6-8094-eec70572c9c1.png)

_Copied from original issue: aspnet/HttpAbstractions#707_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Friday, March 10, 2017 10:23:17 PM_

This is post 2.0.0 once we have pipelines + span in place

**Comment by davidfowl** [comment]
@jkotalik did this and its now insanely fast 😄
