### ISSUE TITLE
Calling a web api on form post in blazor disconnects the appliaction on page load in .net 5.0

### ISSUE THREAD

**Issue by PremKumarMadhanRaj** [dotnet/aspnetcore#27161]
I need to call a web API controller passing some values to perform some action on form post. To achieve this I have created a form dynamically using script in client end with a input (assigning the value to be passed to the API method) and assigning form action as the API URL. But in .NET 5.0, when page reloads on form post the blazor application gets disconnected at once and application gets crashed.

Is there any possible way to achieve this without using client form post so that I can overcome this page reload and application disconnection issue.!!!

**Comment by javiercn** [comment]
@PremKumarMadhanRaj thanks for contacting us.

Is this blazor server or blazor webassembly?

**Comment by PremKumarMadhanRaj** [comment]
@javiercn this occurs in Blazor server..

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
In Blazor server you don't have to explicitly call an API. Instead, call it as a simple method on a controller class from your code. Please note, that I've made an assumption here that the API you're calling is on the same server.
