### ISSUE TITLE
Make RequestHeaders a struct

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2717]
_From @Yves57 on Sunday, September 4, 2016 1:51:14 AM_

`RequestHeaders` are generally allocated one time per request (see the [Response Caching Context](https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingContext.cs#L36) or my PR about compression in `BasicMiddleware` for example), and it is a small object.
So I suppose it would be be better for the GC to make it `struct` instead of `class`.

_Copied from original issue: aspnet/HttpAbstractions#700_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Monday, September 5, 2016 7:21:46 PM_

+1, I think these things need an overhaul. They are mostly used to get a typed view of the stringy header collection. The parsing code also needs a do-over 😄

**Comment by aspnet-hello** [comment]
_From @rynowak on Tuesday, September 6, 2016 8:44:55 AM_

Yes, you can't really use these today in perf-sensitive code. We avoid them in MVC 99% of the time for this reason.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, September 6, 2016 10:13:03 AM_

Breaking change?

Also, when we tried this before with IOwinContext/Request/Response the compiler wouldn't allow it because it thought there were issues with the mutable properties (even though there weren't any actual issues because the properties were mutating non-struct state).

**Comment by aspnet-hello** [comment]
_From @Yves57 on Tuesday, September 6, 2016 12:05:44 PM_

In my compression middleware PR, I just removed 'RequestHeaders' allocation, and I use the low level `StringWithQualityHeaderValue.TryParseList()` code.

But at least I think it would be nice to have extension methods like

```
public static IList<StringWithQualityHeaderValue> GetAcceptEncoding(this IHeaderDictionary headers)
```
- No breaking change
- Easy to implement because everything already exists
- Clearer user code
- No perf problem
- Not necessary to use a [KnowListParsers](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/HeaderDictionaryTypeExtensions.cs#L210) map :-)

**Comment by aspnet-hello** [comment]
_From @davidfowl on Tuesday, September 6, 2016 12:11:28 PM_

Agreed. We can make the breaking changes for v2. All of the existing APIs can be avoided in our code base though. We can also
Improve the quality of the code to be less allocatey without breaking the contract.

**Comment by aspnet-hello** [comment]
_From @muratg on Wednesday, September 7, 2016 2:13:00 PM_

Breaking change. We'll reconsider in 2.0

**Comment by davidfowl** [comment]
Too late
