### ISSUE TITLE
Cloning at tag v3.1.9 has incorrect versions in global.json

### ISSUE THREAD

**Issue by IanKemp** [dotnet/aspnetcore#27171]
`sdk:version` and `tools:dotnet` are set to `3.1.107` which is the SDK for v3.1.7. Updating these fields to `3.1.109` ensures the correct SDK version is installed.

`tools:runtimes:dotnet/x64` is set to `$(MicrosoftNETCoreAppInternalPackageVersion)` which causes `dotnet-install` to download `https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.8-servicing.20420.1/dotnet-runtime-3.1.8-servicing.20420.1-win-x64.zip` which is incorrect. Forcing this value to `3.1.9` correctly uses/downloads the v3.1.9 runtime. I have no idea what `$MicrosoftNETCoreAppInternalPackageVersion` is or where it is set, and honestly I couldn't be bothered.

`tools:vs:version` is set to `16.3`, should be `16.4`.

If you're going to provide build scripts, make sure they're correct for the version being built, or don't supply them at all.

**Comment by IanKemp** [comment]
Seems that 3.1.8 is hardcoded somewhere, with the result that all artifacts get versioned and built as such.

**Comment by IanKemp** [comment]
Ahhh, ok, it's `eng/Version.props` which is still referencing 3.1.8 everywhere. That needs to be updated to whatever the correct versions of 3.1.9 are too.

Seems like cf7c11172d7a9c889df78498d10c0bf4631f766b fixed the `AspNetCorePatchVersion` at least. Then b5bc2cbf5fb2eced69fabace925e2b2720817d77 fixed the packages. I arbitrarily chose to checkout 6aa39db54403eff1609abb7d1e3be81008a773f0 and I am now getting 3.1.9 versions as expected. However, `global.json` remains at the incorrect versions I noted in my first comment.

**Comment by IanKemp** [comment]
The tl;dr appears to be that whoever tagged `v3.1.9` didn't update the build scripts to the correct version beforehand. That tag should be deleted and the repo re-tagged as `v3.1.9` at the appropriate commit - whatever that may be.

**Comment by wtgodbe** [comment]
Apologies, looks like you're right - the correct commit is d12868dd7c10ff0433c16b06d3b59d03c40d987a. I've just updated it - https://github.com/dotnet/aspnetcore/releases/tag/v3.1.9

@rbhanda it looks like the drop for 3.1.9 had multiple Aspnetcore versions in the manifest, and the automation chose the older one. I'll try to make sure that the drops are clean in the future, but it'd also be good if the tagging automation defaulted to choosing the newest rather than the oldest
