### ISSUE TITLE
Error when running InstallVisualStudio.ps1 with VS 2017 installed

### ISSUE THREAD

**Issue by TopperKain** [dotnet/aspnetcore#27183]
### Describe the bug
Attempting to run the script "InstallVisualStudio.ps1" with VS 2017 (but not 2019) installed results in an exception.

This appears to be due to the use of "vswhere" parameter (-sort) introduced in VS 2019.

### To Reproduce

One a machine with VS 2017 installed (but not 2019)
- Open powershell
- Clone the aspnetcore repo
- From within the root of the repo, run the command `./eng/scripts/InstallVisualStudio.ps1`
- This will result in an error

### Exceptions (if any)

```
ConvertFrom-Json : Invalid JSON primitive: Visual.
At C:\src\aspnetcore\eng\scripts\InstallVisualStudio.ps1:85 char:110
+ ... format json -sort -prerelease -products $productId | ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

### Further technical details
- ASP.NET Core version is the current code from the master branch as of 10/23/2020.
- Include the output of `dotnet --info`
```
A compatible SDK version for global.json version: [6.0.100-alpha.1.20472.11] from [C:\src\aspnetcore\global.json] was not found

Host (useful for support):
  Version: 2.1.23
  Commit:  b61e1596d6

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.519 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2017 15.9.28 on Windows 10 1909.

**Comment by TopperKain** [comment]
I got this working by removing the sort parameter, which is not be necessary for the subsequent steps. This change worked when I only had VS2017 installed and after I had installed VS 2019.

**Comment by dougbu** [comment]
> which is not be necessary for the subsequent steps

@TopperKain this isn't quite true because we need to match the latest version in a channel and cannot specify the channel on the command line. That is, `-latest` won't work consistently if you're e.g. updating the Preview channel but happen to have a more recent version from the Release channel.

That said, we could switch to using PowerShell to sort the objects in the `$installations` array.

**Comment by dougbu** [comment]
Done in 9b6103989c0a. Thanks again @TopperKain
