### ISSUE TITLE
Fix the line endings in the appsettings. Development.json file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27182]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Fix-the-line-endings-in-the-appsettings/1217713)._

---
[severity:It bothers me. A fix would be nice]
When I create a new Visual Studio ASP.NET Core web project, choose the empty template, when I open appsettings.json , all is fine but  when I open appsettings. Development.json, I alwasy get the nagging "Inconsistent line endings" dialog box... can you please fix that in the template?
(latest visual studio 2019 16.7.5)

Also do check the other projects.

---
#### Feedback Bot on 10/13/2020, 07:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2020, 02:09 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### visualstudio on 10/14/2020, 02:32 AM: 

<p>I think all developers who opens that file (appsettings.Development.json) is impacted by the issue. What I want is that the file in the template gets its line-ending fixed so that you are not presented with that dialog below:</p><p> </p><p><img alt=""><br></p><p><img alt=""></p>

#### visualstudio on 10/14/2020, 02:34 AM: 

(private comment, text removed)
#### visualstudio on 10/14/2020, 02:34 AM: 

<p>using the ASP.NET Core 3.1 web project MVC template </p>

---
### Original Solutions
(no solutions)

**Comment by MCCshreyas** [comment]
Hi @mkArtakMSFT, I have experienced this issue quite a lot.  When I did some research here that I found that it's an issue of Line endings inconsistency between JSON files in the project template. 
The [appsettings.json](https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/appsettings.json) has Windows (CRLF) line ending, whereas [appsettings.Development.json](https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/appsettings.Development.json) has Unix (LF) line ending. 
I have found this inconsistency in other project templates also, so I just wanted to ask what should be the correct line endings that every project should follow for now at least for JSON formatted files!?  
Thanks !
