### ISSUE TITLE
Violation of "CA1031: Do not catch general exception types" in DefaultHealthCheckService

### ISSUE THREAD

**Issue by jinek** [dotnet/aspnetcore#27180]
Method **DefaultHealthCheckService.RunCheckAsync** has general catch block (excluding only two situations) which catches almost all exceptions, which makes this method not transparent for exception propogation.

I believe the instruction ``` when (ex as OperationCanceledException == null)``` which is also commented with "// Allow cancellation to propagate if it's not a timeout." is written exactly because of that violation brings problem. But this is the only one case which is excluded and still other infinite number of cases remains. In the health-check itself, we don't know how the pipeline looks like, which middlewares are being executed and which exceptions are expected by them. For example, lets imagine that we have **Http500MiddleWare** which we want to return HTTP 500 in case of any unhandled exception in the pipeline.

From the perspective of the health-check itself, it seems to me, that we don't know whether it's healthy or no. This catch means, that it's impossible to determine the state, and that current execution call is now in corrupted state (Additionally, it's possible that entire application is now corrupted). 
In fact, even if the check was success it's possible that TaskScheduler raised some exception, or even Log could raise NullReferenceException signalling about the bug in the logger itself. 

I hope this way briefly I've described my idea/concerns. I believe there are many resources including documentation, StackOverflow where the same idea is described, for example:

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031?view=vs-2019

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/

I see, that in other repositores developers reproduce the same idea of catching all exceptions without re-throwing them. Which I believe leads to what catching everything usually leads to )

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What you're describing is exactly how the HealthChecks system is designed and is expected to catch all exceptions and treat those as `failures`. That said, there doesn't seem to be any evidence here that this behavior is incorrect. We're closing this issue.

**Comment by jinek** [comment]
@mkArtakMSFT 
But, please, have a look at the code:

```
when (ex as OperationCanceledException == null)
```

This means that what you are describing ("expected to catch all exceptions and treat those as failures") is not true. This one is an example of why rule CA1031 is supposed not to be broken.

And we practically can not know all the situations and exception flows which are used by developers. Consider the customer throwing exception **SpecialSecurityException** during health check or possibly any other request handler. It is awaited by middleware to stop the execution, abort the socket and may be black-list the IP address or similar. Now, because of general catch we are continuing the request handling, returning the result and not doing the supposed handling of that exception.
