### ISSUE TITLE
AspNetCore repo is missing attribution to JSON.NET in 3PN

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27185]
@ahsonkhan pointed this out. https://github.com/dotnet/aspnetcore/blob/master/THIRD-PARTY-NOTICES.txt is missing attribution for this which means packages like Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson and Microsoft.AspNetCore.Mvc.NewtonsoftJson are also missing this attribution in the 3PN carried by the package.

**Comment by pranavkm** [comment]
FYI @Pilchie

**Comment by Pilchie** [comment]
We don't actually ship Newtonsoft.Json, right?  We just have a package reference to it, in which case I don't believe we need a 3PN?

**Comment by pranavkm** [comment]
There's a THIRD-PARTY-NOTICES.TXT inside these packages which appears to be a direct copy of $RepoRoot\THIRD-PARTY-NOTICES.TXT. That file should likely include the attribution.

**Comment by Pilchie** [comment]
But why though?  We don't ship Newtonsoft.Json anymore - it's not part of the shared framework, it's just a package reference.  Our packages don't contain the Newtonsoft.Json code.

**Comment by DamianEdwards** [comment]
Isn't it still shipped in the razor compiler?
![image](https://user-images.githubusercontent.com/249088/97063177-037e2680-1553-11eb-9566-91000059285c.png)

**Comment by Pilchie** [comment]
Okay. Sounds like we should tee this up for servicing then.

**Comment by ahsonkhan** [comment]
It might be worth spot-checking other "standalone" packages as well for their 3PN.

**Comment by pranavkm** [comment]
Re: other packages, `Microsoft.AspNetCore.DataProtection.StackExchangeRedis` might need a similar treatment.

**Comment by dougbu** [comment]
I'm confused. The 3PN file has a whole `License notice for Newtonsoft.Json` section. Is this just a JSON.Net / Newtonsoft.Json mixup❔

**Comment by dougbu** [comment]
Assigning to @pranavkm for the decision on closing this (with no action)

**Comment by wtgodbe** [comment]
ping @pranavkm

**Comment by pranavkm** [comment]
Yup, I must have overlooked the attribution. Closing.

**Comment by ahsonkhan** [comment]
> packages like Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson and Microsoft.AspNetCore.Mvc.NewtonsoftJson are also missing this attribution in the 3PN carried by the package.

This was the underlying issue. The concern wasn't whether that the 3PN at the root of the GitHub repo has attribution mention but rather **that the NuGet package itself doesn't contain that info in its 3PN**.

For example, look at this:
https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/
![image](https://user-images.githubusercontent.com/6527137/103033569-90276f80-4517-11eb-809c-e91a3d76c9a2.png)
[THIRD-PARTY-NOTICES.TXT](https://github.com/dotnet/aspnetcore/files/5736937/THIRD-PARTY-NOTICES.TXT)

> There's a THIRD-PARTY-NOTICES.TXT inside these packages which appears to be a direct copy of $RepoRoot\THIRD-PARTY-NOTICES.TXT. That file should likely include the attribution.

This statement doesn't seem to hold true, and it should. That could be a reasonable fix. Just adding it to the 3PN in the root of the repo might not be enough, i.e. https://github.com/dotnet/aspnetcore/pull/27186

**Comment by ahsonkhan** [comment]
> ~Re: other packages, `Microsoft.AspNetCore.DataProtection.StackExchangeRedis` might need a similar treatment.~
> 
> Just read @Pilchie's comment. Disregard.

I believe it does, yes. The 3PN within the repo on GitHub and the 3PN within the NuGet package needs attribution to `StackExchange.Redis` since it is a dependency.

https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection.StackExchangeRedis/5.0.1
![image](https://user-images.githubusercontent.com/6527137/103033960-a97ceb80-4518-11eb-81fe-80ae61a0a7e3.png)
