### ISSUE TITLE
Merge QueryString & Query Properties

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2719]
_From @niemyjski on Monday, May 30, 2016 8:05:48 AM_

Currently the request object has a `Host` property that has `Host.Host` and `Host.Port` and it makes it easier to get that info. There is one place to look.  But when it comes to the query string there are inconsistencies and it's not as discoverable. At first I saw the QueryString property and looked in intellisense for QuerySring but didn't even think to look for Query after working with Host and some of the other complex property types. 

There is a `Query` property that gives you a parsed query string and then a `QueryString` property that builds up the Query into a single string. It would be nice if the `IQueryCollection` had a ToString() implementation to display the query string, but at the same time it should be separated out and not responsible for building it. Which is why I see there are two properties. With this said I guess the question is, should these be merged into a complex type that has both QueryString and Query or just an Extension Method that builds the query string from IQueryCollection?

_Copied from original issue: aspnet/HttpAbstractions#644_

**Comment by aspnet-hello** [comment]
_From @niemyjski on Monday, May 30, 2016 8:12:20 AM_

Only closest issue we found on slack was: https://github.com/aspnet/HttpAbstractions/issues/50

**Comment by aspnet-hello** [comment]
_From @MaximRouiller on Monday, May 30, 2016 8:15:01 AM_

I know that in the past, it was represented as a list KeyValuePair.

Why is this now a string only? It doesn't seem like there's an actual way to extract that information without re-parsing it. 

Unless it's a write-only structure, it should allow us to parse it at the very least.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, June 1, 2016 12:44:33 PM_

Why are you adding values to the request query?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, June 1, 2016 1:37:05 PM_

Your usage does not appear to be related to the issues you mentioned above.

We're in the process of finalizing v1.0 and are unlikely to make structural changes at this point. If you see performance issues those are best conveyed via profiler traces.

**Comment by aspnet-hello** [comment]
_From @niemyjski on Wednesday, June 1, 2016 10:47:26 PM_

I've updated this issue based on further investigation.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, June 2, 2016 10:32:30 AM_

Thanks, that's a clearer description. 

I'm still trying to figure out why your scenarios discuss query building on the request. Most of the request properties are provided to deconstruct the raw HTTP into useful components. The request target is deconstructed into PathBase, Path, and QueryString. QueryString is further deconstructed into Query key value pairs. The Query property is index into to retrieve individual values.  Query is not mutable and I don't know why you'd use it to build a QueryString when you already have the original.  One reason for keeping the QueryString property is that it's useful for generating redirect links like `newScheme + "://" + Host + PathBase + Path + QueryString`. It's also available for scenarios where the query contains something other than key value pairs.

Are there additional scenarios we should be addressing?

**Comment by aspnet-hello** [comment]
_From @niemyjski on Tuesday, June 7, 2016 6:21:42 AM_

@Tratcher I only included a sample to adding to query as a user might want to build up there own query string using it and return it in a header... Most cases users will not modifying it and I will not be.. But it's a valid scenario... My thing is I saw query string and didn't even look for query, it sounded like something I shouldn't be touching (Query as in a database query etc, not something I'd look for for a key value pair that makes up the query string).

**Comment by aspnet-hello** [comment]
_From @muratg on Thursday, June 9, 2016 9:52:13 AM_

Triaging out of 1.0.0 and we'll have another look once we RTM.

**Comment by davidfowl** [comment]
Too late
