### ISSUE TITLE
Running a Blazor Web App from VS Mac 2019 - 404 Error Blazor.WebAssembly.js

### ISSUE THREAD

**Issue by zshubailat** [dotnet/aspnetcore#27191]
### Describe the bug
I used the built in templates to create a Blazor app on VS for Mac. When running by clicking the run button (Debug -> Safari) or (Debug->Edge) I get the "Loading...." page. I checked the Dev Tools and saw that there's a 404 error with Blazor.Webassembly.js not found.
I checked the bin folders wwwroot and Blazor.Webassembly.js does in fact exist.

If I use Terminal and do a dotnet run, the app worked correctly.

Facing an issue trying to run from VS Studio for Mac

### To Reproduce
New project from template and run **from VS Studio**

### Exceptions (if any)
Running through terminal with **dotnet run**

### Further technical details
- ASP.NET Core version 3.1.402
- .NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.401 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
- VS Studio for Mac 2019 8.7.8 (build 4)

**Comment by zshubailat** [comment]
Update: if I manually copy the _framework directory from
...location of projects..../Projects/MyBlazorApp/MyBlazorApp/bin/Debug/netstandard2.1/wwwroot
to
...location of projects..../Projects/MyBlazorApp/MyBlazorApp/wwwroot

the running template works (including debugging) - note: I upgraded to preview versions (8.8 building 1532 or later) but that on its own didn't solve the issue. Seems that the issue is that when clicking run from VS Studio, the IDE is not using the right configuration (Debug in this case to set the wwwroot and copy all files there). Perhaps a configuration issue on my side? I only used the template

**Comment by javiercn** [comment]
@zshubailat thanks for contacting us.

You shouldn't need to copy the files to get the project to work. A few questions:
* Does it work from the command-line?
* Can you check that the environment the server is running is Development? Otherwise static web assets won't be on by default and you'll have to turn them on explicitly in your project via a call to `host.UseStaticWebAssets()` explicitly.

**Comment by zshubailat** [comment]
It works from the command line. 

I'm attaching the configuration view

<img width="970" alt="Screen Shot 2020-10-26 at 9 20 33 AM" src="https://user-images.githubusercontent.com/8337418/97187033-14c56e00-17b3-11eb-8a84-7d62e3c95670.png">
<img width="973" alt="Screen Shot 2020-10-26 at 9 21 01 AM" src="https://user-images.githubusercontent.com/8337418/97187038-17c05e80-17b3-11eb-8c94-25f061c56bf8.png">


> @zshubailat thanks for contacting us.
> 
> You shouldn't need to copy the files to get the project to work. A few questions:
> 
> * Does it work from the command-line?
> * Can you check that the environment the server is running is Development? Otherwise static web assets won't be on by default and you'll have to turn them on explicitly in your project via a call to `host.UseStaticWebAssets()` explicitly.

**Comment by javiercn** [comment]
@zshubailat thanks for the additional details, one last question. Is this a webassembly standalone project from what I can tell? (No asp.net core server)

**Comment by zshubailat** [comment]
> @zshubailat thanks for the additional details, one last question. Is this a webassembly standalone project from what I can tell? (No asp.net core server)

Correct, it is a standalone. I also made a copy of one that ran well properly in VS (Windows) and got the same issue. 

Many thanks in advance for your help

**Comment by mkArtakMSFT** [comment]
@mrward can you please look into this ? Looks like something is broken in VS4Mac for Blazor projects. Thanks!

**Comment by mkArtakMSFT** [comment]
Also, @mrward please let us know how you'd like to track this.

**Comment by mrward** [comment]
Can you provide more details on how the project was created? I am not able to reproduce this. My steps:

1. Open VS Mac 8.7.8. (.NET Core 3.1.402 installed).
2. File - New Solution
3. Select Web and Console - App - Blazor WebAssembly App and click Next.
4. Leave options unchanged and click Next.
5. Provide project name, solution name and location and click Create.
6. Select Microsoft Edge in the main toolbar.
7. Run - Start Debugging.
8. Blazor WebApp loads and you can view all the pages and use it.

I am not using Big Sur, which has various other known problems with VS Mac, but not sure if that is related.

**Comment by zshubailat** [comment]
I was facing this issue running VS Mac 8.7.8 and found an article on docs.microsoft.com that instructed me to us 8.8 preview and  .Net Core 3.1.403 on MacOS Catalina 10.15.7

No sure why IDE not picking the path to t/Projects/MyBlazorApp/MyBlazorApp/bin/Debug/netstandard2.1/wwwroot where the _framework sits. Does it have anything to do with Soft-Mode Debug? - I added the version of Mono that I have as the last screenshot for reference

Here are the screenshots of what I did to reproduce
<img width="912" alt="Screen Shot 2020-10-27 at 5 49 25 AM" src="https://user-images.githubusercontent.com/8337418/97251397-d793c700-1818-11eb-9fd9-c93521ad49f8.png">
<img width="908" alt="Screen Shot 2020-10-27 at 5 50 09 AM" src="https://user-images.githubusercontent.com/8337418/97251424-e67a7980-1818-11eb-928c-0dfb9b88a9ae.png">
<img width="911" alt="Screen Shot 2020-10-27 at 5 50 35 AM" src="https://user-images.githubusercontent.com/8337418/97251435-eed2b480-1818-11eb-8ad6-bc036ddfec38.png">
<img width="1955" alt="Screen Shot 2020-10-27 at 5 51 42 AM" src="https://user-images.githubusercontent.com/8337418/97251447-f6925900-1818-11eb-9d3f-374881c70659.png">
<img width="978" alt="Screen Shot 2020-10-27 at 5 58 26 AM" src="https://user-images.githubusercontent.com/8337418/97251745-81735380-1819-11eb-9391-b545afeb764f.png">
<img width="973" alt="Screen Shot 2020-10-27 at 5 59 38 AM" src="https://user-images.githubusercontent.com/8337418/97251794-9e0f8b80-1819-11eb-96bb-9b589e011846.png">
<img width="747" alt="Screen Shot 2020-10-27 at 6 05 43 AM" src="https://user-images.githubusercontent.com/8337418/97252359-d95e8a00-181a-11eb-89f8-a08717383648.png">
<img width="746" alt="Screen Shot 2020-10-27 at 6 10 48 AM" src="https://user-images.githubusercontent.com/8337418/97252523-35291300-181b-11eb-981e-6271878ded35.png">
<img width="407" alt="Screen Shot 2020-10-27 at 6 12 27 AM" src="https://user-images.githubusercontent.com/8337418/97252639-86d19d80-181b-11eb-81bf-df84fbd0818d.png">
<img width="407" alt="Screen Shot 2020-10-27 at 6 13 14 AM" src="https://user-images.githubusercontent.com/8337418/97252714-b385b500-181b-11eb-9a05-5e1a96737a97.png">

**Comment by mrward** [comment]
Not able to reproduce the problem you are seeing in VS Mac 8.8.0.2829. I have the same Mono as you, the same .NET Core sdk, the same macOS. It works OK for me.

Soft debug mode is not used for Blazor projects. The .NET Core debugger is used.

**Comment by mrward** [comment]
OK playing around with this, the space in the path seems to be the problem for some reason. I created a folder on my external drive to try and match your path, because I was suspicious about the space and then the Blazor project does not get passed the loading page.

**Comment by zshubailat** [comment]
Yup! That's it, I created a project on the partition that doesn't have spaces in the name and it worked

**Comment by zshubailat** [comment]
Thank you very much @mrward ... what a catch!!!

**Comment by mrward** [comment]
There is still a bug here in VS Mac since `dotnet run` is fine. I have filed an internal bug against VS Mac for this and will take a look at fixing this problem.

**Comment by mrlife** [comment]
@mrward

> I am not using Big Sur, which has various other known problems with VS Mac, but not sure if that is related.

Is Big Sur now supported with the latest VS Mac preview?

**Comment by mrward** [comment]
@mrlife - There still seems to be some problems running on Big Sur reported on the forums. I have not upgraded my own machine to Big Sur yet.

**Comment by zshubailat** [comment]
I upgraded to Big Sur and there's a different issue with relation to https which I will post a question about. If go into the project options -> ASP.Net and I remove the https://localhost:5001 and keep the http://localhost:5000 all runs well (I was facing an error).

I tried dotnet run --https and I ended up with the same issue 
![image](https://user-images.githubusercontent.com/8337418/99237513-41dccd80-2801-11eb-96a4-99d08901a80a.png)

Details:
Process:               dotnet [54215]
Path:                  /usr/local/share/dotnet/dotnet
Identifier:            dotnet
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        dotnet [54199]
Responsible:           Terminal [54146]
User ID:               501

Date/Time:             2020-11-16 11:40:29.708 +0200
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        23A2805D-E7A3-269E-8C0A-F04D40FC6C3D

Sleep/Wake UUID:       062A5BDC-AC0E-485C-A950-4F5478E377C9

Time Awake Since Boot: 87000 seconds
Time Since Wake:       52000 seconds

System Integrity Protection: enabled

Crashed Thread:        12

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [54215]

Application Specific Information:
BUG IN CLIENT OF LIBPLATFORM: Trying to recursively lock an os_unfair_lock

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff202e88e2 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff2031ae6f _pthread_cond_wait + 1254
2   libcoreclr.dylib              	0x000000010fe155db CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) + 347
3   libcoreclr.dylib              	0x000000010fe15270 CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) + 464
4   libcoreclr.dylib              	0x000000010fe19c5c CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int, int) + 2028
5   libcoreclr.dylib              	0x000000010fe19f42 WaitForMultipleObjectsEx + 82
6   libcoreclr.dylib              	0x000000010ffa582b Thread::DoAppropriateWaitWorker(int, void**, int, unsigned int, WaitMode) + 1243
7   libcoreclr.dylib              	0x000000010ffa0460 Thread::DoAppropriateWait(int, void**, int, unsigned int, WaitMode, PendingSync*) + 48
8   libcoreclr.dylib              	0x00000001100d47c0 CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*) + 64
9   libcoreclr.dylib              	0x000000010ffa6740 Thread::Block(int, PendingSync*) + 32
10  libcoreclr.dylib              	0x000000010ff9e140 SyncBlock::Wait(int, int) + 544
11  libcoreclr.dylib              	0x0000000110200d4c ObjectNative::WaitTimeout(bool, int, Object*) + 188
12  ???                           	0x000000011e730da4 0 + 4805823908
13  ???                           	0x000000011e745650 0 + 4805908048
14  ???                           	0x000000011e7454f4 0 + 4805907700
15  ???                           	0x000000011e79b766 0 + 4806260582

**Comment by zshubailat** [comment]
Note: Seems that something happened to the dev-cert when I upgraded to Big Sur. I recall the upgrade asking me for the password of the Keychain during the update (maybe I made a mistake at this point).

In any case, a dotnet dev-certs --clean followed by a dotnet dev-certs --trust fixed things (I was prompted again in visual studio for the password of the Keychain)
