### ISSUE TITLE
Blazor OIDC Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by zHaytam** [dotnet/aspnetcore#27196]
### Describe the bug
I current have:

- Keycloak as an IDP (http://localhost:8080)
- Blazor frontend (https://localhost:44310)

I'm using the following auth (PKCE) config in Blazor:
```
builder.Services.AddOidcAuthentication(options =>
            {
                builder.Configuration.Bind("Local", options.ProviderOptions);
                //options.ProviderOptions.ResponseType = "id_token token";
                options.ProviderOptions.ResponseType = "code";
                options.UserOptions.RoleClaim = "roles";
            }).AddAccountClaimsPrincipalFactory<OidcRolesClaimsPrincipalFactory>();
```

When I log in for the first time, I get redirected to Keycloak and back to Blazor and everything works well.  
If i refresh the page (e.g. F5), then I receive the following error in the browser console:
```
AuthenticationService.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8080') does not match the recipient window's origin ('https://localhost:44310').
```

The weird thing is, everything about the auth still works so I don't really see a problem.  
I believe the requested frame is `login-status-iframe.html`.

### Further technical details
- ASP.NET Core version 5 RC2
- Google Chrome

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by zHaytam** [comment]
I mean there is an actual error in the console but okay.
