### ISSUE TITLE
CSS Isolation doesn't automatically recompile updated file in Blazor WASM

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#27193]
### Describe the bug
When updating a `Component.razor.css` file and starting the app again, the stylesheet is not updated.

### To Reproduce

Create e Razor Component and add an isolated CSS file to it. Try updating just the file between builds. The updated file will not be provided with the assembly to the browser, instead it provides the old one.
I did try this with browser caching disabled. My workaround is to manually rebuild the application.

### Further technical details
- ASP.NET Core 5 RC 2
- `dotnet --info`:

```
C:\Users\bruno>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20185
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- Microsoft Visual Studio Community 2019 Preview Version 16.8.0 Preview 5.0

**Comment by javiercn** [comment]
@BrunoBlanes thanks for contacting us.

We fixed this in RTM, there was an issue with the visual studio fast up-to-date check

**Comment by BrunoBlanes** [comment]
Awesome, do you know which preview version will it be shipped in?

**Comment by javiercn** [comment]
@BrunoBlanes RTM

**Comment by BrunoBlanes** [comment]
Thanks.
