### ISSUE TITLE
How to replace x-powered-by header in aspnetcore 3.1

### ISSUE THREAD

**Issue by yaobo-lab** [dotnet/aspnetcore#27192]
when replace response header  "X-Powered-By"  with  middleware
here is code:

    
          app.Use(async (context, next) =>
            {
                // no key X-Powered-By
                var Keys = context.Response.Headers.Keys; 
               // context.Response.Headers.Remove("X-Powered-By")  no effect 
                context.Response.Headers.Add("X-Powered-By", new StringValues("New Powered"));               
                await next();
            });

            app.UseEndpoints(e =>
            {               
                e.MapControllers();
            }); 

but  Response tow X-Powered-By; and how to replace it?

![image](https://user-images.githubusercontent.com/21329253/97079665-7efdd780-1628-11eb-8d29-500eafff7f95.png)

**Comment by blowdart** [comment]
That second one isn't coming from ASP.NET, but from IIS.

To remove it, use web.config. The following entries do it for me.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.web>
    <httpRuntime enableVersionHeader="false"/>
  </system.web>
  <system.webServer>
    <security>
      <requestFiltering removeServerHeader="true" />
    </security>
    <httpProtocol>
      <customHeaders>
        <remove name="X-Powered-By"/>
      </customHeaders>
    </httpProtocol>
  </system.webServer>
</configuration>
```
