### ISSUE TITLE
Blazor templates in .net5 are not backwards compatible with .net core 3.1 templates

### ISSUE THREAD

**Issue by marin-bratanov** [dotnet/aspnetcore#27203]
# Describe the bug

The new project templates in .net5 (RC2 at the time of writing) have a `<div class="page">` as the root element in `MainLayout.razor`. Removing this element breaks the layout of the project - the content is misplaced. Having this element in a .net 3.1.x project breaks the layout of that project - the content is misplaced then.

> Sample of the problematic element (in comments)

```razor
@*<div class="page">*@
    <div class="sidebar">
        <NavMenu />
    </div>

    <div class="main">
        <div class="top-row px-4">
            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
        </div>

        <div class="content px-4">
            @Body
        </div>
    </div>
@*</div>*@
```

>Why is this a problem 

This is a problem for project templates and documentation of component vendors - I can see no straightforward way to reconcile and document this breaking change so that end users will not get the short end of the stick. There are two options, and both of them are problematic:

* Try to explain options and .net version variations in the existing resource. 

    * **Why this is not a solution**: This will result in code examples that cannot be copy-pasted into projects, and confusion for the end users. Either those wanting the new bits can have issues because docs use 3.1 versions (which is the LTS), or those wanting stability and the LTS will have issues because docs are showcasing the latest bits.

* Make an entire new copy of your documentation/tutorial/template for .net 5.

    * **Why this is not a solution**: This is very time-consuming, likely to require a lot of manual effort, infrastructure reworking, and is not future-proof - adding more and more content will make your docs/templates/examples muddy and unclear, and people are still likely to find or use the wrong one and have issues. Moreover, maintaining entire copies of a lot of explanations just because 1 element was added to a default layout people will throw away anyway is a lot of extra work for no benefit. The CSS Isolation feature can be showcased without this element too.

### To Reproduce

Compare the CSS and layout of a `dotnet new blazorserver` between .net 5 and 3.1. Here's an example: of the problem https://github.com/telerik/blazor-docs/pull/156

### Proposed solution

Use the CSS from the .net core 3.1 templates and remove the newly added  `page` div. If you choose to, you can still keep some of the styles in a scoped stylesheet.

The goal is that you can generate a project in either version, use any third party components and follow their docs, and easily switch between those version by swapping out, for example, the `<TargetFramework>` tag in the `.csproj` file.

**Comment by marin-bratanov** [comment]
A second look showed something I had missed - there is no longer the `<app>` DOM element. This element is probably present in stylesheets and cascades already rely on it, because it was an integral part of the HTML layout of your app. Is this change here to stay?

![app-element-gone](https://user-images.githubusercontent.com/5746515/97110842-0a886e80-16e4-11eb-9e57-7c49acfcdb8e.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While we do try hard to make sure the framework stays compatible from release to release we don't make any guarantees for templates to stay the same / be compatible.
