### ISSUE TITLE
Blazor Server Side on refresh page and click on href shows => Error: Circuit has been shut down due to error.

### ISSUE THREAD

**Issue by trajkovdimitar** [dotnet/aspnetcore#27212]
### Describe the bug
Error: Circuit has been shut down due to error.
![image](https://user-images.githubusercontent.com/45421293/97197115-8d293080-17ad-11eb-9e86-d94b1199979c.png)

### To Reproduce
There was a similar bugs reported for application crashing on click on href for mail and phone. My problem is on click on regular href, it crashes and shows the error below for 1-2 seconds and than continues to work regularly like nothing happened. This also happens on refresh.

### Exceptions (if any)

This is from the output info:
Microsoft.Azure.SignalR.ServiceConnection: Warning: Received message for connection h2nasrjBzvqDZ21_cy9n9Oe0a35er28 which does not exist.

### Further technical details
- ASP.NET Core version  3.1.402.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Can you also confirm whether the experience is the same if you not use Azure SignalR service?

**Comment by trajkovdimitar** [comment]
If you want i can explain you the problem again. In this moment, i am unable to provide a minimalistic repro project. I removed, also i can confirm that the experience is the same without Azure SignalR service.

**Comment by trajkovdimitar** [comment]
Also i should mention this seems to be happening only when the link is leading to outside of the application, which in our case is another Blazor server side application. I created a new project, can`t really notice if there is an error, since it is basically empty project and it is fast.

**Comment by mkArtakMSFT** [comment]
Thanks for the additional details. We will still need a small repro. Get back to us when you can and we will try to investigate this then.
