### ISSUE TITLE
Investigate tooling to help with version to version migration

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27214]
Similar to `ng upgrade`, the idea here is to explore tooling that can making migrating from one version of .NET Core to the next easier. We can start by looking at verticals such as MVC, Blazor and go from there to a more general purpose tool for .NET Core.

**Comment by davidfowl** [comment]
Looks like we punted this one.

**Comment by pranavkm** [comment]
Yup. I think we might want to work with the upgrade-assistant here. They are in a better position to build and service this.
