### ISSUE TITLE
You can't use skipNegotiation with the Azure SignalR Service.

### ISSUE THREAD

**Issue by iaydogdu-telecloudvision** [dotnet/aspnetcore#27210]
You can't use skipNegotiation with the Azure SignalR Service.

_Originally posted by @BrennanConroy in https://github.com/dotnet/aspnetcore/issues/23002#issuecomment-644832849_

Hello , ı get  ERROR:"There was an error with the transport." when ı use mobile ios safari or chrome. When ı use local browser there is not any problem.
.Net Core 3.1 React project and ı use @microsoft/signalr": "^3.1.9"  on client-side.

var connection= new HubConnectionBuilder()
    .withUrl( myProjectUrlHub ,{skipNegotiation: true,
    transport: HttpTransportType.WebSockets})
    .configureLogging(LogLevel.Debug)
    .build();

**Comment by davidfowl** [comment]
You can't skip negotiation without passing the direct service URL. This is by design.

**Comment by iaydogdu-telecloudvision** [comment]
Thanks , but when ı remove the negotiation got
 Error:"Unable to connect to the server with any of the available transports.WebSockets failed.Error:There was an error with the transport".

var connection= new HubConnectionBuilder()
.withUrl( myProjectUrlHub ,HttpTransportType.WebSockets)
.configureLogging(LogLevel.Debug)
.build();

**Comment by davidfowl** [comment]
This is a bug in the client. We're currently not handling this case properly today. This should only be evaluated after the *real* negotiate response, not the redirect.

**Comment by BrennanConroy** [comment]
David what do you think the bug is? It isn't clear to me what the issue is with the details mentioned.

**Comment by davidfowl** [comment]
You should be able to specify the transport when working with the service. The negotiate response should only be evaluated for transports when the final response comes back. The redirect response shouldn't be interrogated for transports.

**Comment by BrennanConroy** [comment]
> The negotiate response should only be evaluated for transports when the final response comes back. The redirect response shouldn't be interrogated for transports.

I'd be very surprised if we were looking at transports during the redirect.
https://github.com/dotnet/aspnetcore/blob/bb5efb768ce9fde27a599a7333d8ab0e4a0fa8cb/src/SignalR/clients/ts/signalr/src/HttpConnection.ts#L242-L270

@iaydogdu-telecloudvision could you share you client logs please? And possibly the network trace from the browser or fiddler?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#network-traces

**Comment by iaydogdu-telecloudvision** [comment]
Today  we have deployed the demo on server and it is working clearly. I will check my local configurations again deeply, it seems as that  is a problem about my local situation.
