### ISSUE TITLE
Investigate tooling to migrate from NET Fx to .NET Core 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27215]
This issue tracks exploring the idea of producing tooling that can assist in migrating from .NET Fx to .NET Core (3.1). We can focus on MVC 5 \ WebAPI -> MVC Core and see what sort of tooling support we can introduce here.

**Comment by mkArtakMSFT** [comment]
Moved to `backlog` as we have no work planned in .NET 6 timeframe for this.

**Comment by Tratcher** [comment]
Much of this effort has moved to https://github.com/dotnet/systemweb-adapters.
