### ISSUE TITLE
[Performance] Yarp

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#27225]
Improve performance for components used by Yarp (https://github.com/microsoft/reverse-proxy).

Areas of interest:

- Optimize the performance of header copy

**Comment by Tratcher** [comment]
- Profile the proxy request processing pipeline

**Comment by Tratcher** [comment]
> * Optimize the performance of header copy

We've already worked on this and don't expect much further improvement.

**Comment by sebastienros** [comment]
> We've already worked on this and don't expect much further improvement.

Do you know what would be necessary to make some gains? Even if it is breaking things, or improvement in lower stacks.
I assume there is a difference between "not being able to" and "technically not possible".

Also, please suggest other areas to investigate.

**Comment by Tratcher** [comment]
Most of the identified bottlenecks with headers are in System.Net.Http.HttpRequestMessage.Headers and would require some fundamental changes to how the APIs work. YARP needs to ship with 3.1 APIs so redesigning that part is out of scope for now.

We also tested what the theoretical best case would be for headers and it was less than a 5% improvement. I expect we can get better improvements for less effort elsewhere.

For low hanging fruit start by profiling the middleware and HttpProxy components, those run per request and haven't had any perf work done yet:
https://github.com/microsoft/reverse-proxy/tree/05a60d0ae5913d73e7a1f12d4cc50e9011081a30/src/ReverseProxy/Middleware
https://github.com/microsoft/reverse-proxy/blob/05a60d0ae5913d73e7a1f12d4cc50e9011081a30/src/ReverseProxy/Service/Proxy/HttpProxy.cs
