### ISSUE TITLE
Reuse existing Blazor components from a web app in a Blazor hybrid desktop app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27235]
### Summary

As a [developer], I want to [build hybrid desktop apps using my existing web UI assets (potentially the entire app)] so that [I can build cross-platform UI that leverages my existing web UI investments and has a consistent UI presence].”

> Note: This is a proposed experience for .NET 6 and not yet committed.

**Comment by RChrisCoble** [comment]
Big vote of approval on this one.  I thought Mobile Blazor Bindings could do this already though?  Is this bringing MBB directly into ASP.Net?

**Comment by danroth27** [comment]
@RChrisCoble Thanks for your interest in this scenario! We're proposing an Epic for .NET 6 to bring in support for building hybrid desktop apps with Xamarin & Blazor into the platform as a supported feature. The Mobile Blazor Bindings experimental project does have some of these capabilities already and will inform the work we are proposing here for .NET 6. In parallel, the Mobile Blazor Bindings will continue to be used to experiment with future looking native app scenarios with Blazor.

**Comment by mkArtakMSFT** [comment]
This is already possible.
