### ISSUE TITLE
Use native controls alongside web-rendered UI in a Blazor hybrid desktop app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27239]
### Summary

As a [developer], I want to [use native controls in my Blazor hybrid desktop app alongside my existing web UI assets] so that [provide a native app experience for key user experiences (like native menus and file pickers)].”

> Note: This is a proposed experience for .NET 6 and not yet committed.

**Comment by sinand99** [comment]
Mixing native and web controls is a bad idea. It will cause tons of bugs which will create headaches for developers.
