### ISSUE TITLE
AuthenticationHandler<TOptions>.AuthenticateAsync does not accept CancellationToken

### ISSUE THREAD

**Issue by nothrow** [dotnet/aspnetcore#27230]
### Is your feature request related to a problem? Please describe.

In my project, I implement my own `AuthenticationHandler`, which requests some information from external service in it's `AuthenticateAsync` method. 

When the request is cancelled, I would like to be able to cancel call to given service as well.

### Describe the solution you'd like
Have `CancellationToken` parameter of virtual `AuthenticationHandler<TOptions>.AuthenticateAsync` method.

**Comment by Tratcher** [comment]
You can use the HttpContext.RequestAborted CancellationToken in that scenario.
https://github.com/dotnet/aspnetcore/blob/cf25717e3615a3ce9c183ecb7ba2f6a5735353d6/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L609
