### ISSUE TITLE
FormFeature.ReadForm is Sync over Async

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2723]
_From @benaadams on Friday, October 30, 2015 3:11:44 AM_

 Avoid Sync-over-Async http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx

_Copied from original issue: aspnet/HttpAbstractions#456_

**Comment by aspnet-hello** [comment]
_From @glennc on Thursday, January 7, 2016 10:19:22 AM_

@davidfowl are we going to do anything about this? Seems unlikely at this point.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Thursday, January 7, 2016 10:26:43 AM_

Backlog as it's pretty easy to work around (just put a middleware in the pipeline that does an async read).

**Comment by aspnet-hello** [comment]
_From @benaadams on Monday, February 6, 2017 7:26:19 PM_

@blowdart @DamianEdwards just mentioning as stuff like this is trending on twitter; if twitter trended for useful things.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Monday, February 6, 2017 7:38:20 PM_

The reason this isn't *as* bad as your typical sync over async is because you can always pre-load the form in middleware (or in MVC it happens in another component asynchronously before hitting user code) and in that case, the property acts like a cache.

**Comment by aspnet-hello** [comment]
_From @benaadams on Monday, February 6, 2017 7:45:09 PM_

Ah, so its already handled if you use MVC, is only if you go raw or custom? (and ReadFormAsync is available)

**Comment by aspnet-hello** [comment]
_From @davidfowl on Monday, February 6, 2017 8:43:46 PM_

Right, MVC doesn't automagically read the body but if you use model binding then it does and accessing Form is a n00p.

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Monday, February 6, 2017 8:49:26 PM_

The much worse one in my opinion is `HttpContext.Session` if I recall.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, February 6, 2017 9:44:55 PM_

Yeah, depending on your store. There's also an async way to load it but nobody does it for you. We could make an MVC attribute for that.

**Comment by davidfowl** [comment]
We handle this by throwing by default for sync IO
