### ISSUE TITLE
Light-up platform specific functionality in individual Blazor components in a Blazor hybrid desktop app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27236]
### Summary

As a [developer], I want to [light-up platform specific functionality in my Blazor hybrid desktop app] so that [I can take advantage of platform specific capabilities while reusing my existing web UI].”

> Note: This is a proposed experience for .NET 6 and not yet committed.

**Comment by mkArtakMSFT** [comment]
No remaining work left in here.
