### ISSUE TITLE
Blazor Server - Calling javascript in dispose causes error on page reload

### ISSUE THREAD

**Issue by physix99** [dotnet/aspnetcore#27248]
When you call a javascript function from within a Dispose method, if you navigate to an external page or refresh the page, the yellow error bar appears, and the following is logged in the local console:

`VM190 blazor.server.js:19 [2020-10-27T11:46:30.425Z] Error: Circuit has been shut down due to error`

It appears the javascript function is called correctly, as you can see in this demo repository.

https://github.com/physix99/BlazorServer-DisposeError

I've put the Dispose code in this component:

https://github.com/physix99/BlazorServer-DisposeError/blob/master/BlazorApp5/Shared/SurveyPrompt.razor

If you refresh the index page you'll see the issue. It's not a massive problem on this demo repo as the index pages loads very quickly, but if the page takes a while to load or the external page it just looks weird.

Thanks

**Comment by javiercn** [comment]
@physix99 thanks for contacting us.

You are calling an async method within a synchronous function, that can cause issues. What is the actual exception being thrown?

**Comment by physix99** [comment]
Hi,

Sorry it was my bad.

I didnt realise my Visual Studio Preview wasn't up to date, so I was actually running RC1. I've just updated to RC2 and its fixed the issue.
