### ISSUE TITLE
Allow trace_log_writer to be an opt-in feature in the signalr-client-c++ library

### ISSUE THREAD

**Issue by mprather** [dotnet/aspnetcore#27240]
### Is your feature request related to a problem? Please describe.
The trace log writer used by the signalr c++ library eats up a lot resources and arguably is not the same construct as OutputDebugStringA when compared against the non-windows implementation. The biggest problems is that on systems that are heavily taxed (i.e. busy w/ calculations), spending time on logging strings is costly. 

### Describe the solution you'd like
It would be really nice if the use of the trace_log_writer class and all logging could be made as an opt-in compile time feature. Guard the feature with a define, which can then be easily turned on/off in the cmake files or natively by defining/undefining the right value.

**Comment by BrennanConroy** [comment]
We can consider that.

Whats wrong with passing a no-op logger in?

**Comment by mprather** [comment]
Thanks for the quick response. Aren't the strings constructed even if you pass in a custom no-op logger? This is the same problem as setting the logging level to none. The strings are still created and passed to the logger::log method (only to be ignored), right?

**Comment by mprather** [comment]
I would like to propose a possible fix. The built-in logging is quite costly, especially when trying to push data at 100Hz. We've reduced/minimized string creation as much as we can but performance tests show that we continue to incur a large penalty due in part to the logging api. The current implementation requires all strings are allocated and managed even if in the end they are not used.  On top of that, the fact that logging is not the same in Windows vs Linux compilations is a problem.

I would like to fork the current tree and have my team work on a fix that uses lambdas to defer string allocates until they are needed.

This is the rough outline. 

A template method that accepts a lambda, which is called to only when the logging level is valid.
 
        template<typename StreamWritingCallback>
        static void Write(Level level, StreamWritingCallback&& x) {
          if (level != Level::None && level <= currentLevel) {
            std::cout << x();
          }
        }  // End of Write

Thus the calls to the logger become...

  Logger::Write(Level::Verbose, [&]() { return "my string that is not created and managed until the level matches. " ; });

Would the team be interested in such a fix? If we do this, even if we don't make the feature a compile-time opt in, the perf benefit of not allocating strings and passing them around will be substantial.  I would like to make all of the logging guarded by a flag so that it all can just go away but this is step 1.

**Comment by BrennanConroy** [comment]
We're planning on having a compile-time opt-out for logging, and I'd prefer that over designing a new logging API right now.

The current logging also adds additional text to the logs which will incur even more string allocations and that would likely need to be taken into consideration when designing faster logging. But since we are focusing on functionality right now, perf is mostly on the back-burner.

**Comment by mprather** [comment]
Ok. Figured I'd offer. Please keep perf in mind as you work through the next set of changes. We are pushing tons of data through our apps and it would be nice to continue using SignalR to give us some insight in real-time.

**Comment by BrennanConroy** [comment]
We'd gladly accept a PR to add the compile switch for logging :)

Otherwise, I will try to get to it sooner rather than later.

**Comment by mprather** [comment]
Here's a preliminary plan.  

In the cmake file, declare an option.

```
option(signalRLogger       "Enable the logging feature" Off)
```

Then use a generator expression to add the necessary define based on the option setting.

```
target_compile_definitions(target PRIVATE $<$<BOOL:${signalRLogger}>:SIGNALR_USE_LOGGER>)
```

The remain changes would simply be blocking out the relevant code sections with #if defined SIGNALR_USE_LOGGER.

Couple of questions that emerge:
- Does this sound reasonable? Or did you envision something different?
- Would the cmake option path work with vcpkg?

**Comment by BrennanConroy** [comment]
>     * Does this sound reasonable? Or did you envision something different?

Sounds about right, I'd prefer keeping it similar to other options, example
`set(WALL true CACHE BOOL "Enable all warnings.")`

>     * Would the cmake option path work with vcpkg?

I'm not sure if there is a good way to make it work, but it looks like you can pass envrionment variables to the build with https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md#vcpkg_keep_env_vars

**Comment by mprather** [comment]
This might be a 6 wks before we can commit to this endeavor. I think the combo of making code changes + creating a custom vcpkg that we can use for testing will certainly influence how quickly a pr can come together. Will that rough timeline work?

**Comment by BrennanConroy** [comment]
I'm not sure we should make this a compile switch, I've currently gone with the approach of checking the log level first so we don't call into the logger anymore if you turn logging off. This avoids the string allocations. There is some follow up we can do to avoid calling `std::string.append(...)` in some cases by passing multiple `char*` to the internal logger class, but these are also avoided with the current log level checks.

**Comment by mprather** [comment]
Ok. I've been heads down trying on a different project and was planning to return to this topic in the coming weeks. So, it's good timing for both of us it seems. I'll review the latest changes and go from there.
