### ISSUE TITLE
MSB4018 The RazorTagHelper task failed unexpectedly - after VS upgrade

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/aspnetcore#27249]
After upgrading to the Latest Preview of VS, I opened an existing project that compiled successfully in prior version of VS.  It showed and error message in the error list which I have not been able to resolve.

Note that others have had the same issue: https://stackoverflow.com/questions/64354562/vs-2019-fails-to-build-project

### Describe the bug
MSB4018 The RazorTagHelper task failed unexpectedly.  

Output window shows this message: 
2>C:\Users\Greg\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018: The "RazorTagHelper" task failed unexpectedly.
2>C:\Users\Greg\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018: System.InvalidOperationException: DOTNET_HOST_PATH is not set

### To Reproduce
Open an existing .net core 2.2 app in VS 16.8.0 Preview 5.0.
Build the project. 
The Error will be displayed in the Error window and the project cannot be run.

**Comment by pranavkm** [comment]
@gregoryagu it looks like there are changes to the 5.0 SDK that make it incompatible with .NET Core 2.2 apps. While we attempt to avoid such incompatibilities, ASP.NET Core 2.2 has been [out of support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for some time now so it's difficult for us to capture these kinds of regressions. 

* We would strongly encourage targeting a supported version of ASP.NET Core to ensure continued support.
* As a short term fix, you can acquire a 3.1 SDK (from https://dotnet.microsoft.com/download/dotnet-core/3.1) and add a `global.json` file to your project to pin the SDK.

```js
{
  "sdk": {
    "version": "3.1.403"
  }
}
```

**Comment by gregoryagu** [comment]
Ok, thank you for the replay, will close.

**Comment by EnginYuvaktas** [comment]
installing Microsoft.NET.Sdk.Razor is fixed my issue

**Comment by sdktraceur** [comment]
@EnginYuvaktas Thank you!

**Comment by stefanro2000** [comment]
@EnginYuvaktas  it compiled, thanks for your solution
