### ISSUE TITLE
Investigate the performance of OwinFeatureCollection

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2724]
_From @davidfowl on Saturday, October 10, 2015 8:10:35 PM_

OwinFeatureCollection is functional but we should understand the performance characteristics of using it within the ASP.NET 5 pipeline.

_Copied from original issue: aspnet/HttpAbstractions#436_

**Comment by davidfowl** [comment]
Not a mainstream scenario we want to spend time making fast.
