### ISSUE TITLE
Blazor WASM PWA on Azure Static Web Apps auto fetch after a new deploy

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/aspnetcore#27258]
When I deploy a new update to my Azure Static Web App. my clients must do a hard refresh (Ctrl + Shift + R) in order to clear cache and see the new updates.
So what I did is I made few changes in service-worker.published.js 
```JS
const CACHE_VERSION = 1.02;
const cacheName = `${cacheNamePrefix}${self.assetsManifest.version + CACHE_VERSION}`;
```
Now every time I make a new deploy I have to manually update the CACHE_VERSION so it forces the client to re-Fetch new update.
I do not know if the old fetched data gets removed or not.
And also is there a way to automate this step?

**Comment by SteveSandersonMS** [comment]
When you publish the application, it automatically appends a unique token corresponding to your application version (calculated as a hash of the hashes of all your service worker assets manifest entries). This causes the browser to fetch updated PWA resources in the background automatically, so there shouldn't be any steps you need to take manually.

As for why you were not seeing updates, my guess is that the updates are in fact being delivered in the background. If this is not the case, it's possible you've changed something about how your PWA is built/published that prevents the default update mechanism working.

You can read more about this, and the caveats for how PWAs are updated, in the docs at https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#caveats-for-offline-pwas

**Comment by Sharaf-Mansour** [comment]
@SteveSandersonMS One of my users opened the site a week after it has been updated and he was seeing the old design.
After I told him to press 'CTRL+Shift+R' in the hope page because if he did it on any other page he gets ERROR 404.
the app Reload and he gets the new update.
So I thought maybe service worker cache name did not change or something 
I changed it manually and it worked!.. 
I am using .Net5 RC2.

**Comment by SteveSandersonMS** [comment]
> One of my users opened the site a week after it has been updated and he was seeing the old design.

That sounds like one of the caveats of an offline-first PWA mentioned in the docs at https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#users-may-run-any-historical-version-of-the-app.

**Comment by Sharaf-Mansour** [comment]
@SteveSandersonMS When I made the app 1st time. I did not check the PWA box at the beginning.
Instead I had to apply it manfully from one of your Repos I think 'Git hub pages examples' I could not find a checkbox in my project probertites that makes my Blazor WASM into PWA. it would be nice to have one.

**Comment by SteveSandersonMS** [comment]
@Sharaf-Mansour Agreed! That would be a great feature.
