### ISSUE TITLE
Blazor route matching order issue

### ISSUE THREAD

**Issue by r-work** [dotnet/aspnetcore#27250]
I have three pages:

`A: "/{*Page}"`: shown when requested page is not found, looks it up in the database and renders it, otherwise shows 404.

`B: "/Users"`: list of users.

`C: "/Users/{Id:int}"`: show user info based on the provided id.

**The problem:**
If I request "About" it goes to `A` finds it in the database and page is rendered. ✔️
If I request "Users" it goes to `B` and page is rendered. ✔️
If I request "Users/1" it goes to `A`. ❌

Why is it ignoring `C`?

**dotnet version**
5.0 rc2

**Comment by javiercn** [comment]
@r-work thanks for contacting us.

Are you using asp.net core 3.1? Try the [following](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference)

```csharp
 AppContext.SetSwitch("Microsoft.AspNetCore.Routing.UseCorrectCatchAllBehavior", true);
```

**Comment by r-work** [comment]
@javiercn sorry forgot to mention the dotnet version, it's 5.0 rc2.
Tried that, it didn't work unfortunately.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by r-work** [comment]
@javiercn, @mkArtakMSFT 

Here is a minimal repro repo as requested: https://github.com/r-work/BlazorIssue

Default template with the following files changed:

* **_CatchAll.razor**: Added
* **Users.razor**: Added
* **Index.razor**: modified, cleared content and added link to Users

**Comment by r-work** [comment]
@Sharaf-Mansour I've set the data type to string by mistake in the repro, changed it now.
Yes I guess that could be a workaround for the moment. Thanks for the info.
