### ISSUE TITLE
AddRazorRuntimeCompilation not working when working directory is changed

### ISSUE THREAD

**Issue by Waexu** [dotnet/aspnetcore#27259]
I'm using newest .Net 5 RC2. For some reason when I run debug, working directory is set to project directory, not "bin\Debug\net5.0-windows". That causes some problems because I use some shared files from other projects (they are all copied into one folder on build) so it's important for me to have working dir in $(TargetDir).  I tried to achieve it with 2 ways:
1) Change launchSettings.json like this:

```
  "profiles": {
    "WWW": {
      "commandName": "Project",
      "workingDirectory": "$(TargetDir)",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
}
```

2) Change .csproj like this:

```
<PropertyGroup>
	<RunWorkingDirectory>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\</RunWorkingDirectory>
</PropertyGroup>

```
both of these ways worked however RazorRuntimeCompilation is not working when I change working directory. Any suggestions?

**Comment by pranavkm** [comment]
Thanks @Waexu for the issue report. Runtime compilation uses (through layers of indirection), the `AppContext.BaseDirectory` to determine the root directory for views. Changing the working directory via MSBuild the way you've done does not affect this affect. 

You could consider configuring runtime compilation to additionally use this as source of views:

```C#
.AddRazorRuntimeCompilation(options => options.FileProviders.Add(new PhysicalFileProvider(...));
```
