### ISSUE TITLE
Razor Service crashing

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27257]
Tracking for: https://github.com/OmniSharp/omnisharp-vscode/issues/4152

**Comment by TanayParikh** [comment]
Also validate: https://github.com/OmniSharp/omnisharp-vscode/issues/4152#issuecomment-717215854 doesn't happen after the service boots.

**Comment by TanayParikh** [comment]
Assigning to @ryanbrandenburg as he was looking into this, if that's not the case feel free to unassign :)

**Comment by ryanbrandenburg** [comment]
Current thinking is this is a problem on the O# side, so marking this as internal.
