### ISSUE TITLE
Publish Blazor Server or WASM to iOS/Android

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#27252]
### Is your feature request related to a problem? Please describe.
Build once, publish to iOS and Android in addition to web

### Describe the solution you'd like
New `RuntimeIdentifier`s for iOS and Android

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You can try out the [Mobile Blazor Bindings](https://aka.ms/mobile-blazor-bindings) project even today.

**Comment by SteveSandersonMS** [comment]
Since this is better covered in the Mobile Blazor Bindings repo (linked above), I'll close this.
