### ISSUE TITLE
Should StringValues implement Equals?

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2726]
_From @Tratcher on Wednesday, September 2, 2015 10:27:00 AM_

StringValues does not currently implement Equals (or GetHashCode).  MVC implements their own wrapper that has Equals. If so, what should be considered equal?
"string" == new[] { "string" }?
string.Empty == null?
null == new[] { null }?
"value1,value2" == new[] { "value1", "value2" }?
Ordinal?

_Copied from original issue: aspnet/HttpAbstractions#384_

**Comment by aspnet-hello** [comment]
_From @atifaziz on Wednesday, September 2, 2015 10:53:42 AM_

Since `StringValues` is logically just an array of strings with some internal optimizations, its equality and hashing should behave like that of an array when being checked for [structural equality](https://msdn.microsoft.com/en-us/library/system.collections.istructuralequatable%28v=vs.110%29.aspx). That would provide the least surprises and yet still permit some customization when needed (e.g. ignore case when comparing each element).

**Comment by aspnet-hello** [comment]
_From @glennc on Thursday, September 3, 2015 10:16:29 AM_

@Tratcher can you round up @lodejard and @davidfowl to get an answer for this now-ish?

**Comment by aspnet-hello** [comment]
_From @davidfowl on Friday, October 30, 2015 2:23:19 AM_

@rynowak we did this right?

**Comment by aspnet-hello** [comment]
_From @khellang on Friday, October 30, 2015 2:49:54 AM_

@davidfowl https://github.com/aspnet/Common/commit/35333347a6c0c4ccc6cbe3723f17e01ab2bd543a

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, October 30, 2015 8:15:19 AM_

@davidfowl - it implements `.Equals`. We should think about removing some of the overloaded `==` operators. Right now if you try to compare with null you get an error about ambiguity when you should get the 'Hey, it's a struct buddy' error.

**Comment by Tratcher** [comment]
Closing as stale. StringValues has changed a lot since 2015.
