### ISSUE TITLE
Support Code Hot Reload (EnC) for Razor

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27269]
Related to [Hot Reload for ASP.NET Core](#18486)

Support Code Hot Reload (Edit and Continue/EnC) for Razor, including:
- Razor Views/Pages in ASP.NET Core
- Razor Components in Blazor Server
- Razor Components in Blazor WebAssembly
- Razor Components in Blazor Desktop WebView

**Comment by mkArtakMSFT** [comment]
@DamianEdwards should we close this already?

**Comment by DamianEdwards** [comment]
Yep I think so!
