### ISSUE TITLE
Improve repo development experience on VS Code and VS4Mac

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#27260]
Our current setup experience for the aspnetcore repo is designed to work best with Visual Studio (thinking about things like our `startvs` scripts, our solution filters, debugging through multiple projects, etc).

We should invest some time into making the experience on VS Code and VS4Mac good for new contributors. This can include things like:

- Adding more VS Code launch configurations for different project scenarios (e.g. running test apps, tests, etc)
- Providing a more complete set of default extensions for VS Code
- Adding git hooks to alert users of common issues in their PR (e.g. bad formatting, no API updates, etc)

...and probably more.

**Comment by Pilchie** [comment]
We should also investigate adding a `devcontainer.json` so that VSCode remote can get a container with all of our dependencies in it more easily.

* https://code.visualstudio.com/docs/remote/devcontainerjson-reference

**Comment by wtgodbe** [comment]
@captainsafia what are your thoughts on the current state of this?

**Comment by captainsafia** [comment]
I think we can probably close this out.

With C# Dev Kit, the experience for running tests in the repo is much improved.

The one hiccup is that VS Code doesn't have the best support for `slnf` files at the moment so you end up having to deal with the `.sln` files that the extension auto-generates but that's something that might evolve on the extension side.
