### ISSUE TITLE
Hot deploy CSS changes in Blazor Apps

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27275]
- Changing CSS doesn't require re-running the build, just copying over the file 
- CSS isolation in Blazor requires the build though

**Comment by Joren-Thijs** [comment]
I love Blazor but in terms of CSS Blazor still has some catching up to do.
Not only would it be nice to have scss support out of the box.
But recompiling scss on file changes and injecting the new styling without refreshibng the browser page would be really awesome.

**Comment by SteveSandersonMS** [comment]
@pranavkm Should we close this as done?
