### ISSUE TITLE
Docs: Add summaries to ASP.NET Core namespaces

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#27286]
ASP.NET Core namespaces don't have summary descriptions. Compare:

[ASP.NET Core API Reference](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-5.0) vs [.NET API Reference](https://docs.microsoft.com/en-us/dotnet/api/?view=net-5.0).

Namespaces don't have `///` comments, and so are documented in [dotnet/AspNetApiDocs](https://github.com/dotnet/AspNetApiDocs/) XML files. Namespace XML files aren't overwritten by doc sync.

Information about how to write a namespace summary: https://github.com/dotnet/dotnet-api-docs/wiki/Summary:-Namespace

---

There are 159 namespaces to do, so lots of work for everyone. I've tried to give people namespaces that they worked on or are familiar with. Search for your GitHub name in the browser to highlight your namespaces.

- [x] AspNetCore Namespace | @JamesNK
- [x] Microsoft.AspNetCore Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Antiforgery Namespace | @pranavkm
- [x] Microsoft.AspNetCore.ApiAuthorization.IdentityServer Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Authentication Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.AzureAD.UI Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.AzureADB2C.UI Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.Certificate Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.Cookies Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.Facebook Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.Google Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.JwtBearer Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.MicrosoftAccount Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.Negotiate Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.OAuth Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.OAuth.Claims Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.OpenIdConnect Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.OpenIdConnect.Claims Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.Twitter Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authentication.WsFederation Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authorization Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authorization.Infrastructure Namespace | @HaoK
- [x] Microsoft.AspNetCore.Authorization.Policy Namespace | @HaoK
- [x] Microsoft.AspNetCore.AzureAppServices.HostingStartup Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Builder Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.Builder.Extensions Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.Components Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Authorization Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.CompilerServices Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Forms Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.RenderTree Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Rendering Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Routing Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Server Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Server.Circuits Namespace | @captainsafia
- [x] Microsoft.AspNetCore.Components.Web Namespace | @captainsafia
- [x] Microsoft.AspNetCore.ConcurrencyLimiter Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.Connections Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.Connections.Features Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.CookiePolicy Namespace | @wtgodbe
- [x] Microsoft.AspNetCore.Cors Namespace | @wtgodbe
- [x] Microsoft.AspNetCore.Cors.Infrastructure Namespace | @wtgodbe
- [x] Microsoft.AspNetCore.Cryptography.KeyDerivation Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.EntityFrameworkCore Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.Infrastructure Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.KeyManagement Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.Repositories Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.StackExchangeRedis Namespace | @jkotalik
- [x] Microsoft.AspNetCore.DataProtection.XmlEncryption Namespace | @jkotalik
- [x] Microsoft.AspNetCore.Diagnostics Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Diagnostics.HealthChecks Namespace | @JamesNK
- [x] Microsoft.AspNetCore.HeaderPropagation Namespace | @Tratcher
- [x] Microsoft.AspNetCore.HostFiltering Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting.Builder Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting.Server Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting.Server.Abstractions Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting.Server.Features Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting.StaticWebAssets Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Hosting.WindowsServices Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Html Namespace | @halter73
- [x] Microsoft.AspNetCore.Http Namespace | @halter73
- [x] Microsoft.AspNetCore.Http.Connections Namespace | @halter73
- [x] Microsoft.AspNetCore.Http.Connections.Features Namespace | @halter73
- [x] Microsoft.AspNetCore.Http.Extensions Namespace | @halter73
- [x] Microsoft.AspNetCore.Http.Features Namespace | @halter73
- [x] Microsoft.AspNetCore.Http.Features.Authentication Namespace | @halter73
- [x] Microsoft.AspNetCore.Http.Headers Namespace | @wtgodbe
- [x] Microsoft.AspNetCore.HttpOverrides Namespace | @wtgodbe
- [x] Microsoft.AspNetCore.HttpsPolicy Namespace | @wtgodbe
- [x] Microsoft.AspNetCore.Identity Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Identity.EntityFrameworkCore Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Identity.UI Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Identity.UI.Services Namespace | @JamesNK
- [x] Microsoft.AspNetCore.JsonPatch Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.JsonPatch.Adapters Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.JsonPatch.Converters Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.JsonPatch.Exceptions Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.JsonPatch.Helpers Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.JsonPatch.Operations Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.Localization Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.Localization.Routing Namespace | @SteveSandersonMS
- [x] Microsoft.AspNetCore.MiddlewareAnalysis Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Mvc Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.Abstractions Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.ActionConstraints Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.ApiExplorer Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.ApplicationModels Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.ApplicationParts Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.Authorization Namespace | @javiercn
- [x] Microsoft.AspNetCore.Mvc.Controllers Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Mvc.Core.Infrastructure Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Mvc.Cors Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Mvc.DataAnnotations Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Mvc.Diagnostics Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Mvc.Filters Namespace | @pranavkm
- [x] Microsoft.AspNetCore.Mvc.Formatters Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.Formatters.Xml Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.Infrastructure Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.Localization Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.ModelBinding Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.ModelBinding.Binders Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.ModelBinding.Metadata Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.ModelBinding.Validation Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.NewtonsoftJson Namespace | @dougbu
- [x] Microsoft.AspNetCore.Mvc.Razor Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.Razor.Compilation Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.Razor.Infrastructure Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.Razor.TagHelpers Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.RazorPages Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.Rendering Namespace | @TanayParikh
- [x] Microsoft.AspNetCore.Mvc.Routing Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.TagHelpers Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.Testing Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.Testing.Handlers Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.ViewComponents Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.ViewEngines Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.ViewFeatures Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure Namespace | @ajaybhargavb
- [x] Microsoft.AspNetCore.Owin Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Razor.Hosting Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Razor.Runtime.TagHelpers Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Razor.TagHelpers Namespace | @JamesNK
- [x] Microsoft.AspNetCore.ResponseCaching Namespace | @Tratcher
- [x] Microsoft.AspNetCore.ResponseCompression Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Rewrite Namespace | @Tratcher
- [x] Microsoft.AspNetCore.Routing Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Routing.Constraints Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Routing.Matching Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Routing.Patterns Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Routing.Template Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Routing.Tree Namespace | @JamesNK
- [x] Microsoft.AspNetCore.Server.HttpSys Namespace | @jkotalik
- [x] Microsoft.AspNetCore.Server.IIS Namespace | @jkotalik
- [x] Microsoft.AspNetCore.Server.IIS.Core Namespace | @jkotalik
- [x] Microsoft.AspNetCore.Server.IISIntegration Namespace | @jkotalik
- [x] Microsoft.AspNetCore.Server.Kestrel Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Server.Kestrel.Core Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Server.Kestrel.Core.Features Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Server.Kestrel.Https Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Namespace | @sebastienros
- [x] Microsoft.AspNetCore.Session Namespace | @JunTaoLuo
- [x] Microsoft.AspNetCore.SignalR Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.SignalR.Protocol Namespace | @BrennanConroy
- [x] Microsoft.AspNetCore.StaticFiles Namespace | @JunTaoLuo
- [x] Microsoft.AspNetCore.StaticFiles.Infrastructure Namespace | @JunTaoLuo
- [x] Microsoft.AspNetCore.TestHost Namespace | @JunTaoLuo
- [x] Microsoft.AspNetCore.WebSockets Namespace | @JunTaoLuo
- [x] Microsoft.AspNetCore.WebUtilities Namespace | @JunTaoLuo
- [x] Microsoft.JSInterop Namespace | @SteveSandersonMS
- [x] Microsoft.JSInterop.Infrastructure Namespace | @SteveSandersonMS
- [x] Microsoft.Net.Http.Headers Namespace | @JunTaoLuo

**Comment by JamesNK** [comment]
I've tried to give people namespaces that they worked on or are familiar with. Search for your GitHub name in the browser to highlight your namespaces.

- [ ] Microsoft.AspNetCore Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Antiforgery Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.ApiAuthorization.IdentityServer Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Authentication Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.AzureAD.UI Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.AzureADB2C.UI Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.Certificate Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.Cookies Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.Facebook Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.Google Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.JwtBearer Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.MicrosoftAccount Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.Negotiate Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.OAuth Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.OAuth.Claims Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.OpenIdConnect Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.OpenIdConnect.Claims Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.Twitter Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authentication.WsFederation Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authorization Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authorization.Infrastructure Namespace | @HaoK
- [ ] Microsoft.AspNetCore.Authorization.Policy Namespace | @HaoK
- [ ] Microsoft.AspNetCore.AzureAppServices.HostingStartup Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Builder Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.Builder.Extensions Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.Components Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Authorization Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.CompilerServices Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Forms Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.RenderTree Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Rendering Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Routing Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Server Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Server.Circuits Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.Components.Web Namespace | @captainsafia
- [ ] Microsoft.AspNetCore.ConcurrencyLimiter Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.Connections Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.Connections.Features Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.CookiePolicy Namespace | @wtgodbe
- [ ] Microsoft.AspNetCore.Cors Namespace | @wtgodbe
- [ ] Microsoft.AspNetCore.Cors.Infrastructure Namespace | @wtgodbe
- [ ] Microsoft.AspNetCore.Cryptography.KeyDerivation Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.EntityFrameworkCore Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.Infrastructure Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.KeyManagement Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.Repositories Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.StackExchangeRedis Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.DataProtection.XmlEncryption Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.Diagnostics Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Diagnostics.HealthChecks Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.HeaderPropagation Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.HostFiltering Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting.Builder Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting.Server Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting.Server.Abstractions Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting.Server.Features Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting.StaticWebAssets Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Hosting.WindowsServices Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Html Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http.Connections Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http.Connections.Features Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http.Extensions Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http.Features Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http.Features.Authentication Namespace | @halter73
- [ ] Microsoft.AspNetCore.Http.Headers Namespace | @wtgodbe
- [ ] Microsoft.AspNetCore.HttpOverrides Namespace | @wtgodbe
- [ ] Microsoft.AspNetCore.HttpsPolicy Namespace | @wtgodbe
- [ ] Microsoft.AspNetCore.Identity Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Identity.EntityFrameworkCore Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Identity.UI Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Identity.UI.Services Namespace | @javiercn
- [ ] Microsoft.AspNetCore.JsonPatch Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.JsonPatch.Adapters Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.JsonPatch.Converters Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.JsonPatch.Exceptions Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.JsonPatch.Helpers Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.JsonPatch.Operations Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.Localization Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.Localization.Routing Namespace | @ryanbrandenburg
- [ ] Microsoft.AspNetCore.MiddlewareAnalysis Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.Abstractions Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.ActionConstraints Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.ApiExplorer Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.ApplicationModels Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.ApplicationParts Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.Authorization Namespace | @javiercn
- [ ] Microsoft.AspNetCore.Mvc.Controllers Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Mvc.Core.Infrastructure Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Mvc.Cors Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Mvc.DataAnnotations Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Mvc.Diagnostics Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Mvc.Filters Namespace | @pranavkm
- [ ] Microsoft.AspNetCore.Mvc.Formatters Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.Formatters.Xml Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.Infrastructure Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.Localization Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.ModelBinding Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.ModelBinding.Binders Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.ModelBinding.Metadata Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.ModelBinding.Validation Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.NewtonsoftJson Namespace | @dougbu
- [ ] Microsoft.AspNetCore.Mvc.Razor Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.Razor.Compilation Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.Razor.Infrastructure Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.Razor.TagHelpers Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.RazorPages Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.Rendering Namespace | @TanayParikh
- [ ] Microsoft.AspNetCore.Mvc.Routing Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.TagHelpers Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.Testing Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.Testing.Handlers Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.ViewComponents Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.ViewEngines Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.ViewFeatures Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Owin Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Razor.Hosting Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Razor.Runtime.TagHelpers Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.Razor.TagHelpers Namespace | @ajaybhargavb
- [ ] Microsoft.AspNetCore.ResponseCaching Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.ResponseCompression Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Rewrite Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.Routing Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Routing.Constraints Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Routing.Matching Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Routing.Patterns Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Routing.Template Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Routing.Tree Namespace | @JamesNK
- [ ] Microsoft.AspNetCore.Server.HttpSys Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.Server.IIS Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.Server.IIS.Core Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.Server.IISIntegration Namespace | @jkotalik
- [ ] Microsoft.AspNetCore.Server.Kestrel Namespace | @halter73
- [ ] Microsoft.AspNetCore.Server.Kestrel.Core Namespace | @halter73
- [ ] Microsoft.AspNetCore.Server.Kestrel.Core.Features Namespace | @halter73
- [ ] Microsoft.AspNetCore.Server.Kestrel.Https Namespace | @halter73
- [ ] Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic Namespace | @halter73
- [ ] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Namespace | @halter73
- [ ] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Namespace | @halter73
- [ ] Microsoft.AspNetCore.Session Namespace | @JunTaoLuo
- [ ] Microsoft.AspNetCore.SignalR Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.SignalR.Protocol Namespace | @BrennanConroy
- [ ] Microsoft.AspNetCore.StaticFiles Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.StaticFiles.Infrastructure Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.TestHost Namespace | @Tratcher
- [ ] Microsoft.AspNetCore.WebSockets Namespace | @JunTaoLuo
- [ ] Microsoft.AspNetCore.WebUtilities Namespace | @JunTaoLuo
- [ ] Microsoft.JSInterop Namespace | @SteveSandersonMS
- [ ] Microsoft.JSInterop.Infrastructure Namespace | @SteveSandersonMS
- [ ] Microsoft.Net.Http.Headers Namespace | @JunTaoLuo

**Comment by JamesNK** [comment]
Example PR for adding namespace descriptions: https://github.com/dotnet/AspNetApiDocs/pull/168

**Comment by dougbu** [comment]
@JamesNK the examples you sited are for the 5.0 docs. Which branch should we target in our docs PRs to get the changes into those views❔

**Comment by JamesNK** [comment]
Target master for now. I'll enquire about how versioning works in that repo.

**Comment by dougbu** [comment]
Including this in the DoI project for discussion in that context

**Comment by wtgodbe** [comment]
Closing as these are all down now

**Comment by JamesNK** [comment]
Some new namespaces were added in .NET 5 that weren't in the list and don't have docs. I'll handle adding them.

**Comment by jkotalik** [comment]
@JamesNK did you get the chance to finish this?
