### ISSUE TITLE
Calling async action in asp.net core means file in formData is lost from c# API method

### ISSUE THREAD

**Issue by Sam-Davis** [dotnet/aspnetcore#27288]
.net core version 3.1.8

I can read a file from the form-data and save it as expected. However, when I do an async action, the stream closes and the file is no longer there. Removing the async action means that it works again. I need to do an async query to save the file in the correct place.

```
    [Route("uploadFile")]
    [AllowAnonymous]
    public  async void uploadFile()
    {
        var files = HttpContext.Request.Form.Files;
        if (files != null)
        {
            var file = files.FirstOrDefault();
            var fileName = file.FileName; 

            using (var input = file.OpenReadStream())
            {
                  var id = "someId";
                  await Task.Delay(TimeSpan.FromSeconds(2));
                  // after doing this async action, the file and stream are no longer accessible. 
                  ...
```

**Comment by javiercn** [comment]
@Sam-Davis thanks for contacting us.

Don't use `async void` in your controller action. Use `async Task` instead so that the framework can wait until you are done.

**Comment by davidfowl** [comment]
You should also be using ReadFormAsync. 

@pranavkm i think it's time we write that analyzer

**Comment by mkArtakMSFT** [comment]
We have an issue already for tracking the analyzer work. Resolving this issue as `answered` per @javiercn 's comment above.

**Comment by Sam-Davis** [comment]
Thanks yes, I can confirm this resolved the issue! I was planning to do that after, just didn't expect the return type to have an effect on this particular behavior.
