### ISSUE TITLE
CertificateAuthenticationHandler: Event if no certificate is present 

### ISSUE THREAD

**Issue by martinoss** [dotnet/aspnetcore#27292]
I would like to protect my application, so it can only be accessed using a valid client cert (mutual authentication).
The application should run on an Azure App Service, and I configured IIS to require a client certificate.
Basically, I did the implementation described [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#use-certificate-authentication-in-azure-web-apps).
Things are working like described, but one thing bothers me:
If the webserver accidentally doesn't require a client cert, none of the events (OnAuthenticationFailed, OnCertificateValidated) are fired and clients are able to access the application without any restriction (in my case, a SoapCore endpoint). 
I would like to ensure in my application code, that all requests fail if no certificate is present. 

I suggest to let authentication fail (raise event OnAuthenticationFailed)->  if no certificate is present (see location below), or at least there should be an option for this behavior. 

https://github.com/dotnet/aspnetcore/blob/bde720cea3231968f1e80d182185510dcb1cd1c0/src/Security/Authentication/Certificate/src/CertificateAuthenticationHandler.cs#L68

**Comment by blowdart** [comment]
_clients are able to access the application without any restriction_

But that's not true. Putting [Authorize] on an endpoint, or globally, will ensure that only authenticated clients make it through. If SoapCore isn't allowing you to use that approach then it's a lack on their part.

**Comment by martinoss** [comment]
You're totally right. I just figured out how to bring **Authorize** to SoapCore. 

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)
        .AddCertificate(options => 
        {                    
            options.Events = new CertificateAuthenticationEvents
            {
                OnCertificateValidated = context =>
                {
                    // Add additional validation
                    return Task.CompletedTask;
                }
            };
        });

    services.AddAuthorization();
    services.AddSingleton<IMyService, MyService>();
    services.AddSoapCore();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseHttpsRedirection();
    app.UseRouting();
    app.UseCertificateForwarding();
    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.UseSoapEndpoint<IMyService>((options) =>
        {
            options.Path = "/myservice";
            options.Binding = new BasicHttpBinding(); // binding;
            options.SoapSerializer = SoapSerializer.XmlSerializer;
        })
        .RequireAuthorization();
    });
}
```
