### ISSUE TITLE
Unify test/publish for helix/local scenarios

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#27296]
This work item is tracking the unification of local and helix testing, specifically around introducing the ability to build/publish test assets in such a way that the tests are able to run via a new 'config' like mechanism that points at the appropriate assets in a way that makes it easy to configure (local vs helix runs).

**Comment by HaoK** [comment]
Meeting notes:
- Goal is to make it easy to be able to run tests against the output of a "dotnet publish" on a test directory that's been xcopied as is (this will give us helix compatibility for free)
- We will use the existing https://github.com/dotnet/aspnetcore/tree/master/src/Mvc/Mvc.Testing/src package to prototype this.
- Idea is to have this package generate a new json file on disk that replaces the attribute burning for things like content roots
- Need to also ideally encompass the Selenium e2e props files too in some way https://github.com/dotnet/aspnetcore/blob/master/src/Shared/E2ETesting/E2ETesting.props
- Need to define the appropriate content layout for referenced projects (side by side/subdirs) etc.

@dotnet/aspnet-blazor-eng please review my notes

**Comment by captainsafia** [comment]
> Need to also ideally encompass the Selenium e2e props files too in some way

Can you clarify what you mean by this?

From what I recall from the meeting, we were talking about selenium to the extent that it also has a JSON-based config. Not sure where the props file comes in here...

**Comment by HaoK** [comment]
Good catch, wrong file, I meant this one: https://github.com/dotnet/aspnetcore/blob/master/src/Shared/E2ETesting/selenium-config.json
