### ISSUE TITLE
Blazor Type Constraint Doesn't Work with Fody.PropertyChanged

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#27308]
I created a blazor component with type constraint of INotifyPropertyChanged

Setting the generic property to an instance of this class works.

    public class CartSettings : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    }

If I set it to an instance of this class, however, it doesn't work. Using Fody.PropertyChanged

    [PropertyChanged.AddINotifyPropertyChangedInterface]
    public class CartSettings { }

> Error CS0311 The type 'CartSettings' cannot be used as type parameter 'TViewModel' in the generic type or method 'ViewModelRegion<TViewModel>'. There is no implicit reference conversion from 'CartSettings' to 'System.ComponentModel.INotifyPropertyChanged'.

The second syntax should be working.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We recommend bringing this issue up with the referred library authors in [their repo](https://github.com/Fody/Fody)

**Comment by SimonCropp** [comment]
Fody only works after the initial compile. It is a post-processing action. So for fody to run on the resulting assembly, the initial code has to be compilable. So in the above scenario, the AddINotifyPropertyChangedInterface approach cant be used.
