### ISSUE TITLE
Why TryUpdateModel cannot bind data to ModelState?

### ISSUE THREAD

**Issue by meaning1** [dotnet/aspnetcore#27305]
Here is my action:
```
public async Task<IActionResult> Test() {

            FieldValue f = new FieldValue { Id = 1, Name = "n1" };
            var updateResult = await TryUpdateModelAsync(
                f,
                "");
            if (ModelState.IsValid)
            {
            }
            
            return Ok();
        }
```
FieldValue:
```
[ModelBinder(BinderType = typeof(TestModelBinder))]
    public class FieldValue
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public class TestModelBinder : IModelBinder
    {
        public async Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var model = new FieldValue { Id = 1, Name = "a" };
            bindingContext.Result = ModelBindingResult.Success(model);
        }
    }
```
result:
![image](https://user-images.githubusercontent.com/55533760/96101072-a279a180-0f07-11eb-916d-2c81df4cd859.png)

**Comment by captainsafia** [comment]
@meaning1 The [custom IModelBinder docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-6.0) have mo information on how to implement your IModelBinder but based on the code sample that you've provided there's no `FieldValue` passed in as an argument to your `Test` method. Model binding expects the target value to be passed in as an argument to the action method.
