### ISSUE TITLE
Strongly typed Request/ResponseHeader properties should return readonly collections

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2730]
_From @Tratcher on Thursday, January 15, 2015 10:49:04 AM_

Users may write the following code:
`httpRequest.GetTypedHeaders().SetCookie.Add(myCookie);`

However, this will fail silently because SetCookie.get returns a collection of parsed values that is disconnected from the underlying response headers collection.

The correct code is:
`httpRequest.Headers.Append(HeaderNames.SetCookie, myCookie);`
or
`httpRequest.GetTypedHeaders().SetCookie = myCookies;`

To make sure users do not experience hard to debug silent failures have the IList returned by these properties be read only. We could also switch to IEnumerable.

Alternative: It might be possible to return an IList implementation that was actually bound to the underlying header collection and did live modifications, but that would be significantly more complicated. We can make that work later if there is a strong desire for it.

_Copied from original issue: aspnet/HttpAbstractions#169_

**Comment by davidfowl** [comment]
Can we still change this?

**Comment by Tratcher** [comment]
Here's the API for the example given above:
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Http/Http.Extensions/src/ResponseHeaders.cs#L192

Changing the return type to an IReadOnlyList would be an API breaking change. We could change the implementation to return a collection that would throw if someone tried to modify it, but that's a runtime breaking change.

In practice, I haven't seen people make this mistake very often so we can close this issue.
