### ISSUE TITLE
Asp.net core web api hosted as windows service stucks at startup.

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [dotnet/aspnetcore#27312]
# Asp.net core web api hosted as windows service stucks at startup.

I have created an Asp.net core web api (with Reactjs) application and hosted as windows service. My Operating system is Windows 10 x64.  During the application startup, sometime it takes more time, so windows service is marked as not responding and failed to start. 

# General

Asp.net core version: v3.1.1
Target Framework: v3.1
Target Runtime  win10-x64
Deployment mode: self-contained

I have developed and Asp.net Core Web API (Reactjs for Frontend, used Wisual Studio project template) project. and generated self-contained build and deployed into windows 10x64 PC. 

Main functionality of my app is to listen for web socket connection, based on the message payload from web socket client, it will connect to an external device either via COM port or TCP IP socket (external device will act as tcp server, my windows service will act as tcp client). 

i am following Singleton design pattern for creating objects which deals with COM port and TCP connections. mostly my application will be deployed into each individual PC and act as thick client as we can't access the COM Port directly from web app runs on browser application. so that the web page runs on browser (http://locahost:5000/) can communicate to locahost web socket server and it further communicate with external device through local com port or LAN TCP/IP.  i followed this method to overcome that issue and no external traffics to this localhost server. only one client will connect to this localhost web socket server at a time. i will distrubute my application binaries to my end users, they will install it as windows service and use normal web browsers to access it.

now the problem is, sometime my web api takes more time to start. as i am running my web api app as windows service, windows service marks it as not responding and failed to start. i am using nlog to log the errors and warnings. i put log for each and every single lines in startup.cs, but no clue for the startup stuck issue. i followed below steps to resolve the issue, but nothing worked.

1. set my windows service to start automatically during os restart.
2. set recovery options (restart 3times if the windows service got stopped unexpectedly).

now, my problem is windows services try restart application 2nd time as it does not respond in the 1st try. 2nd time i am getting an error that port 5000 is already in use. so, it tries 3rd time and that time also port 5000 is already in use.

it hurts me heavily, kindly support me to resolve this issue.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by Mohamed-Abubucker** [comment]
Hi @mkArtakMSFT ,

Actually i know how to use ASP.NET core, i am working with ASP.NET for a long time. my issue is not related to learning or development. my issue is related to asp.net core deployment as windows service.

normally windows service will be started within 30seconds, but my asp.net core app tooks more than 30 seconds for startup and it leads to windows service startup failure.

As i configured my windows service to be automatically start while OS restart and i enabled set recovery options (restart 3times if the windows service got stopped unexpectedly), if the my asp.net core app is not responding within 30seconds while startup, in windows services console, its marked as "failed to start" and it tries to start again ( because recovery options set to true).

while it tries to start my asp.net core app for that 2nd time after "startup failure", its getting port 5000 is already in use. 

its just because that 1st time my asp.net core app took more time to start, so window services console marked it as failed to start, but after few seconds later,  my asp.net core app is up and running on port 5000.

i think i explained the issue clearly. 

the issue is my asp.net core app is took more than 30seconds for startup and windows service console considers, its itoo much delay. i can't see anyoption on windows service console or OS level to increase the startup time for my windows service. as i searched on the internet, increasing windows service startup timeout is not a good practice.

kindly help me to fix this startup timeout issue in asp.net core application level. even while debug the app from visual studio also i faced this issue. especially running the app with kestral web server (without IIS), it stuck to start up.

**Comment by snakefoot** [comment]
Startup delay maybe caused by not printing expected lifetime-logging to console: https://github.com/NLog/NLog.Web/wiki/Hosting-Lifetime-Startup-Messages

**Comment by Mohamed-Abubucker** [comment]
Hi @snakefoot ,

Thanks for your suggestion, i will try it out and get back to you.
