### ISSUE TITLE
(SDK Issue) Solutions with C# Razor projects and VB projects cause gold bar

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27310]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Solutions-with-C-Razor-projects-and-VB-/1201115)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.8 preview 1]
Create a solution with NET 5.0 projects, including at least one C# Razor project (Razor Class Library and/or Blazor) and at least one VB project

EXPECTED - Should be able to edit and compile without gold bar warnings

ACTUAL - Intermittently, a NullReferenceException gold bar appears (see attached log file)

The log message contains source "Razor Language Services" with the following message for EACH VB project:

Error encountered from project 'c:\SPOT\Main\SPOT. Platform\SPOT. Platform.API.Gateway\SPOT. Platform.API.Gateway.vbproj': System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicParseOptions' to type 'Microsoft.CodeAnalysis.CSharp.CSharpParseOptions'.at Microsoft.CodeAnalysis.Razor.DefaultProjectWorkspaceStateGenerator. <UpdateWorkspaceStateAsync>d__17.MoveNext()

---
#### Feedback Bot on 9/26/2020, 08:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Sara Liu [MSFT] on 9/27/2020, 11:04 PM: 

<p>Dear customer, thank you for your feedback and I am sorry to hear that you are running into this issue.<br>
According to your description, I tried to test it locally on the same VS version, but unable to reproduce this issue. What’s the project type of the VB project? If you create a new .NET 5.0 Console project and add a C# Razor Class Library and a VB .Net Core console project, does this issue happens or not.<br>
Did you meet this issue before or on the previous VS versions? If not, please check if the VS upgrade or have you install any extensions that maybe affects it.</p>

#### Craig Johnson on 9/28/2020, 09:57 AM: 

<p>Sara - The VB project is an ASP.NET core web app (&lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt;). Perhaps that is why the Razor Language Service is considering the project within its scope and since Razor is only C# then the error mentioned above is happening?</p><p>Error encountered from project ‘c:\SPOT\Main\SPOT.Platform\SPOT.Platform.API.Gateway\SPOT.Platform.API.Gateway.vbproj’: System.InvalidCastException: Unable to cast object of type ‘Microsoft.CodeAnalysis.VisualBasic.VisualBasicParseOptions’ to type ‘Microsoft.CodeAnalysis.CSharp.CSharpParseOptions’.at Microsoft.CodeAnalysis.Razor.DefaultProjectWorkspaceStateGenerator.&lt;UpdateWorkspaceStateAsync&gt;d__17.MoveNext()</p><p>The attached VS log (not the ones that are automatically included but the one I attached) shows this error.</p><p>Thank you!</p>

#### Sara Liu [MSFT] on 9/29/2020, 02:27 AM: 

<p>Hi Craig, thanks for your update. Would you please share how do you create the VB.NET ASP.NET Core web app? I tried to search around and cannot found this project template when I try to create a new project, should I install any required workloads or individual component? </p><p>Looking forward your information and that will help to reproduce this issue, thanks.</p>

#### Craig Johnson on 9/29/2020, 08:27 AM: 

<p>Hi Sara - if you create a VB .NET Core Console App, then swap in the &lt;Project&gt; line above, it will become a web app (I'm hoping that alone is sufficient to repro the issue)</p><p>&lt;Project Sdk="Microsoft.NET.Sdk.Web"&gt;</p><p>The solution causing the issue for me has:</p><p>- A VB.NET ASP.NET Core web project</p><p>- A Razor Class Library project</p><p>- A Blazor Server project</p><p>- A Blazor WebAssembly project</p><p>Thank you!</p>

#### Sara Liu [MSFT] on 9/30/2020, 02:18 AM: 

<p>Hi Craig, thanks for your detail information. I tried to follow it to create the solution, but successfully build it like the following:</p><p><img src="https://developercommunity.visualstudio.com/storage/attachments/159012-vsrazorvb.png"></p><p>Would you please try to close VS and upgrade to the latest version 16.8.0 Preview 3.2 to test it?</p>

#### Craig Johnson on 9/30/2020, 09:49 AM: 

<p>Thank you, I upgraded yesterday and will see if this continues.</p><p>It is an intermittent issue - it is able to build always but then occasionally during editing it will pop up the gold bar and the log file then has the note (which I think is indicative of some oversight or assumption that all projects in the solution are C# projects):</p><p>System.InvalidCastException: Unable to cast object of type ‘Microsoft.CodeAnalysis.VisualBasic.VisualBasicParseOptions’ to type ‘Microsoft.CodeAnalysis.CSharp.CSharpParseOptions’.at Microsoft.CodeAnalysis.Razor.DefaultProjectWorkspaceStateGenerator.&lt;UpdateWorkspaceStateAsync&gt;d__17.MoveNext()</p>

#### Craig Johnson on 9/30/2020, 03:32 PM: 

(private comment, text removed)
#### Sara Liu [MSFT] on 10/2/2020, 01:23 AM: 

<p>Hi Craig, thanks for your sharing and I found the same error message that you shared before inside the log file, </p><p>would you mind trying to uninstall and reinstall VS 2019 preview and see if it continues to be broken?</p>

#### Feedback Bot on 10/14/2020, 04:45 AM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Craig Johnson on 10/14/2020, 08:32 AM: 

<p>Sara, I have updated to Visual Studio 16.8 preview 4 and it is happening on multiple machines.</p><p>I worry that 16.8 will ship and this will continue. It seems clear that there is an assumption being made by some level of the Razor toolchain that any web project is a C# project</p>

#### Feedback Bot on 10/15/2020, 02:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/15/2020, 03:21 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
The repro is to create a VB project and then change its SDK to look like a more web project. That being said ASP.NET Core Razor doesn't really support VB. The correct fix for this is for the Razor SDK to not include the `DotNetCoreRazor or DotNetCoreRazorConfiguration` project capabilities in VB scenarios.

Moving over to the compiler side because of this.

**Comment by NTaylorMullen** [comment]
@mkArtakMSFT  @pranavkm put this in the compiler area because I didn't see an SDK one?
