### ISSUE TITLE
Logging: Tracking state changes for http context

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2732]
_From @yishaigalatzer on Tuesday, December 2, 2014 2:53:52 PM_

Moved from aspnet/MVC#1630.

The general design idea is to add logging to HttpContext when certain things happen.
#### HttpContext

Authenticate
Abort
Dispose
SetFeature
AcceptWebSocket ?
#### HttpResponse

Status code changed
Header replaced (which is also added)
OnSendingHeaders firing - Should probably be in the server.
OnSendingHeaders registrations
Body replaced
SignIn
SignOut
Challenge

_Copied from original issue: aspnet/HttpAbstractions#153_

**Comment by aspnet-hello** [comment]
_From @avanderhoorn on Tuesday, December 30, 2014 9:00:28 PM_

Any progress on this one?

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, December 31, 2014 8:10:46 AM_

Sorry, no progress yet. This does sound like a very important feature for debugging wacky stuff going on in an app. Just not sure where it lines up in the overall priorities, so we can't make any promise right now about when this work will happen.

**Comment by davidfowl** [comment]
Not happening
