### ISSUE TITLE
Blazor page authorise does not work as expected. 

### ISSUE THREAD

**Issue by alexwhite68** [dotnet/aspnetcore#27327]
I am running Visual Studio for Mac Community Edition 8.8 Preview (8.8 build 2899)

Creating a standard Blazor WebAssembly app,
Target Framework: .Net Core 3.1
Authentication: Individual Authentication (in-app)
ASP.Net Core Hosted = ticked
Progressive Web Application  = ticked

Call the Project and Solution demo999
Create the project

Weather Forecast does not load it just says loading

Now update all the NuGet packages at the solution level

Now you are presented with the login dialog as expected.

So now you want to drop that API call out of needing to be authorized. 

So changing the top of FetchData.razor to
```razor
@*@attribute [Authorize]*@
@attribute [AllowAnonymous]

@inject HttpClient Http
@inject IHttpClientFactory ClientFactory

Modify the bottom of the FetchData.razor file to

    [AllowAnonymous]
    protected override async Task OnInitializedAsync()
    {
        try
        {
            var client = ClientFactory.CreateClient("demo999.ServerAPI");
            forecasts = await client.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");
        }
        catch (AccessTokenNotAvailableException exception)
        {
            exception.Redirect();
        }
    }
```

Now go into program.cs for the client and modify the following

```csharp
builder.Services.AddHttpClient("demo999.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));
//.AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

// Supply HttpClient instances that include access tokens when making requests to the server project
builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("demo999.ServerAPI"));
```

It does not work, either the data does not load or the login boxes are presented, I have read a number of documents including the following:-

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1

I have tried having two http clients one authenticated and one not, the FetchData.razor page does not seem to like switching between the two, it takes two debug sessions to make it switch to the right one if that makes sense.

What I am seeing is if I try to switch between authorised and non authorised by making the right changes, it takes 2 debugging sessions for it to work right normally it's like it's remembering (caching) something between sessions.

I would expect to have a number of pages that need authorising and some that don't within most web apps that I would create, it seems the authentication system is caching something.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by alexwhite68** [comment]
This can be closed I missed the [Authorize] attribute on the API endpoint, it was still there, which does beg the question of maybe for me and my style of projects just get rid the attribute on all but confidential data api's and let the client handle the authorisation rather than it being multi layered.
