### ISSUE TITLE
AspNet missing power for real enterprise Web app development.

### ISSUE THREAD

**Issue by netroby** [dotnet/aspnetcore#27324]
Hello, i am new developer with asp.net, but many years deveopment experience with Java, PHP.

When i tried to understand asp.net , and try to design and develope a real business web app. It's hard works.

For example, If we development a Online Store system.

We need build the (Admin, Sales, Customer, Front) module for each targed user.

The simple MVC of asp.net not well support for this.

There should be ( [Module, Controller, Action] +  Data Model Layer  + RPC + Tools) design

Module: each big part should be orgnization under module.

Controller : real business, such as [payment, GiftCode,  account, product list, product detail]

Action:  make a billing,  find the post code, chat with the sales. send forget password.

Data Model Layer; Accees the MySQL, Postgres, Redis, 

RPC: call other internal or third party  service.

Tools: send email, send sms notify, price calculator, event bus

Asp.net missing these part.

User may found it is hard to build a success web app within  Asp.net,  Too many things to do with it.

But the Ruby On Rails, and Spring boot / Spring cloud provide much more power to deal with these.

See spring boot family

![image](https://user-images.githubusercontent.com/66301650/97550861-2b670180-1a0d-11eb-9146-75fc3dc1418c.png)

May tools and modules can help us.

What's next to go , Asp.net.

**Comment by damianh** [comment]
> Module: each big part should be orgnization under module.

In my very honest opinion you are absolutely correct in this respect. I have two blog posts on this subject which should not have been needed to be written.

- https://dhickey.ie/2018/06/09/aspnet-core-nested-apps/
- https://dhickey.ie/2020/10/20/aspnet-core-3-nested-apps/

It's unfortunate that we lost the ability to be modular when the team moved away from OWIN.

**Comment by netroby** [comment]
@damianh  another problem may be : the core team member have no experience to write a huge web app, (like Amazon, NewEgg)

So they can not figure out what need to do if we want to build such a project.

**Comment by damianh** [comment]
@netroby ASP.NET, nor any other framework, will help if you team lacks capability / experience. Consider using a low-code platform instead.

**Comment by javiercn** [comment]
@netroby thanks for contacting us.

We provide some guidance on how to structure large applications that you can review [here](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/) as well as [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/).

For a general entry point you can check [here](https://dotnet.microsoft.com/learn/aspnet/microservices-architecture)

With regards to "modules" it is a very overloaded concept, but one way to map it is 1 module 1 assembly, MVC will pick modules from class libraries without issues.

WRT your comments on controllers and actions I agree with you, but that it's up to the app developer. 

The guides referenced above should provide more detail and come with a reference sample project that details it. See it [here](https://github.com/dotnet-architecture/eShopOnContainers)

For RPC we provide support for building REST APIs and gRPC services and we automatically generate clients for them. You can expose REST APIs using Open API to integrate with other third-parties. See [here for gRPC](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1) and [here for REST APIs with Open API](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-3.1)

For Data access there are multiple solutions out there with support for a wide range of providers, including the most common ones. 

We build and ship an ORM (Entity Framework) and there are other community based options available like NHibernate or Dapper amongst others. See [here](https://docs.microsoft.com/en-us/ef/core/) for EF docs.

With regards to "tools" there are many open source projects you can leverage like MailKit for sending email or mass transit for service bus or commercial offerings from Microsoft like Azure Communications Service or Azure Service Bus as well as commercial offerings from third parties.

I hope this helps bringing some clarity to some of the options that you have available in the .NET landscape and help you with some of your questions.
