### ISSUE TITLE
DI improvements for new developers

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27340]
For new develpers DI is complex, and maybe we can somehow hide it from them, so they don't need to deal with it.

**Comment by gfoidl** [comment]
> For new develpers DI is complex

While true, they still should learn about DI so they are able to use it's full power and don't fall back to wrong patterns (which results most often in untestable code) which they'll revert never or some time in the future when problems arise.

DI in ASP.NET Core is quite easy for new devs. Call Add{Singleton, Scoped, Transient} and used the registered types as ctor-arguments.

I think the most confusion may arise from "scoped" and about the disposing-behaviour.

This is at least what I observed in several forums.

**Comment by adityamandaleeka** [comment]
Any objection to moving this to the "Backlog" milestone?

**Comment by davidfowl** [comment]
I think we close it.
