### ISSUE TITLE
Competitive analysis to evaluate how ASP.NET stand in relation to other frameworks

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27343]
Frameworks to consider.
- Node
- Go
- ...

What is covered ?
- at this point this is unknown. Further conversations are required to figure out how far we want to go with this investigation...

**Comment by mkArtakMSFT** [comment]
@davidfowl, @glennc now that I look back, I'm wondering whether we really need this. Should we just close this issue?

**Comment by davidfowl** [comment]
yup
