### ISSUE TITLE
Simplify API-building experience without controllers

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27347]
- Make it possible to move code as is from Ability to copy code from an endpoint handler to a controller (MapAction)
  - [x] MapAction MVP (#29684)
  - [x] Add new "MapAction" overloads (#30448)
  - [x] MapAction Benchmarks (#29915)
- Move model-binding out of MVC
- Enable a model of `use only what you need`
- ~Ship controllers in libraries~ (out-of-scope)
- ~try to get middleware-like perf with MVC actions~ (out-of-scope)

**Comment by halter73** [comment]
Next steps:

1. Prototype a non-source-gen version of MapAction (see source-gen version [in uController](https://github.com/davidfowl/uController/blob/aa8bcb4b30764e42bd72d326cb2718a4d4eaf4a9/src/uController.SourceGenerator/uControllerGenerator.cs#L57)). Runtime-generation (expression trees allowed). This could avoid intellisense/overload resolution issues the source-gen version has to deal with.

2. Design what a possible reflection API for lambda attributes might look like. See [the houdini meeting notes](https://github.com/aspnet/specs/blob/3153c67f07db02bca638e8e8e913ba4d09b331ec/design-notes/houdini/meeting-notes-2020-12-02.md#c-language-features-we-want).

```C#
Endpoints.MapPost("/api/todos/{id}", [Authorize] async (HttpContext http, TodoDbContext db, [FromBody] Todo inputTodo) =>
{
    var todo = await db.Todos.FindAsync(inputTodo.Id);
    if (todo == null)
    {
        http.Response.StatusCode = 404;
        return;
    }

    todo.IsComplete = inputTodo.IsComplete;
    await db.SaveChangesAsync();
    http.Response.StatusCode = 204;
});
```

**Comment by rcollette** [comment]
To me EndPoints.MapPost looks like a Route attribute turned into a method that takes an action as a parameter.

I'm not sure what the value in that is, but happy to be schooled.

**Comment by halter73** [comment]
Forgot about this one. Replace by #32378
