### ISSUE TITLE
IdentityRole constructor only sets name and has no overload for normalized name

### ISSUE THREAD

**Issue by Luk164** [dotnet/aspnetcore#27354]
## Summary

IdentityRole constructor only sets name and has no overload for normalized name. This causes problems when creating roles, as ASP.net core compares roles to normalized name, not name.

## Motivation and goals

At this time, creating new role like this "`new IdentityRole("Admin")`" would cause an error on comparison as normalized name would stay NULL. Fixing this would prevent this simple mistake from occuring.

## In scope

One possible solution is to automatically assign normalizedName from constructor or create a constructor overload that allows to specify normalizedName.

## Risks / unknowns

I do not see any, if you explicitly set normalizedName to something else than name.ToUpperInvariant() there is probably an intent behind it.

## Examples

new IdentityRole(name) instead of IdentityRole(name) {NormalizedName = name.ToUpperInvariant()}

## Proposed design

Something similar to this:
```
public IdentityRole(string roleName, string normalizedName = NULL) : this()
        {
            Name = roleName;
            if (normalizedName == NULL)
            {
                   NormalizedName = roleName.ToUpperInvariant();
            }
            NormalizedName = normalizedName;
        }
```

**Comment by blowdart** [comment]
What do you mean by "_ASP.net core compares roles to normalized name, not name._"?

IsInRole takes no opinion on normalization at all.

**Comment by Luk164** [comment]
@blowdart 
`@attribute [Authorize(Roles = "Admin")]` Will result in `InvalidOperationException: Role ADMIN does not exist.` Even RoleManager needs to update the value in it's Create method (though it does so in a bit more complex way). I wanted the roles to be added on database migration, so I could not use RoleManager to create them and this issue popped-up.

**Comment by blowdart** [comment]
Wait that shouldn't throw at all, just fail. There's no existence check at that point, it should be using the User instance and calling IsInRole() on it. 

@HaoK @pranavkm any idea what's going on?

**Comment by Luk164** [comment]
@blowdart Wait let me post a few screenshots.

**Comment by Luk164** [comment]
Failure: 
![image](https://user-images.githubusercontent.com/30559213/97633539-8bbd6980-1a34-11eb-8c29-f577bd42d7bc.png)

**Comment by Luk164** [comment]
For the demonstration a manually set admin normalizedName to NULL:
![image](https://user-images.githubusercontent.com/30559213/97633623-ae4f8280-1a34-11eb-8882-d14379e24560.png)

**Comment by Luk164** [comment]
Excuse me I posted the wrong check, it is actually this one that throws `_userManager.IsInRoleAsync(identityUser, "Admin")`

**Comment by Luk164** [comment]
Excuse me it seems I posted the wrong thing, it is actuall `_userManager.AddToRoleAsync(user, "Admin");` that throws.

**Comment by Luk164** [comment]
@blowdart I made a mistake, the perpetrator was the AddToRole, not IsInRole

**Comment by blowdart** [comment]
Ah. Can you post your code for creating a role and then adding a user? You have to go through the stores for all of it, you can't mix and match stores with ef with whatever else.

**Comment by Luk164** [comment]
@blowdart  This is currently the best I could come up with for the role seeding. The GenerateIdentityRole automatically sets the NormalizedName so it ends up in database in correct state.

```
protected override void OnModelCreating(ModelBuilder builder)
        {
            //TODO: Create better role seeding
            builder.Entity<IdentityRole>().HasData(GenerateIdentityRole("Admin"), GenerateIdentityRole("Customer"),
                GenerateIdentityRole("Worker"));

            base.OnModelCreating(builder);
        }

        private static IdentityRole GenerateIdentityRole(string name)
        {
            return new IdentityRole(name) {NormalizedName = name.ToUpperInvariant()};
        }
```

**Comment by Luk164** [comment]
The user is created by default identity page and role is the assigned later on.

**Comment by blowdart** [comment]
@HaoK what's the best way to seed roles? I'd kind of expect this sort of weirdness as it's not done through the role store.

**Comment by Luk164** [comment]
@blowdart Well now it stopped working completely for some reason and even going to older commit is not helping...
I was trying to add roles during configuration through injected roleManager but something went horribly wrong it would seem. I will fix it tomorrow.

**Comment by Luk164** [comment]
Found this tutorial, seems like a good place to start https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1

**Comment by Luk164** [comment]
@blowdart I found another interesting caveat - adding user to role seem to update immediately, but logging out and back in is enough to fix this. Any way to force reauthentication after adding user to a role? Prefferably w/o having to go through the login again?

**Comment by blowdart** [comment]
The logging out and logging in thing is an artifect of how it all works. Obviously you don't want a database hit on every request, so when a user logs in their identity information is written to a cookie, name, roles et al. Then, at a configurable interval, around [30 minutes by default](https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/SecurityStampValidatorOptions.cs) we'll check if the backend database record has changed, and refresh the cookie contents. 30 minutes is a resonable default for scalability, You can configure the number lower, but your database load will obviously go up. 

If you were actually the user at this point you can call RefreshSignInAsync() on the SignInManager. Yes, another manager. It's the managers that coordinate everything, which is why writing to the database directly is generally a bad idea :)

**Comment by Luk164** [comment]
@blowdart Yeah I can see that. We just wanted the basics (like roles) to be present in the db the moment it is created, not added at the last moment during programs initialisation. I am currently proceeding according to the tutorial above. Hope it does not slow down initialisation too much.

Also, I noticed that even when the Db is emptied (cleared it out manually during testing) if the browser had a valid cookie it is still accepted, even though the login would reject him. Can this be accounted for somehow? (Sorry I know this is a bit off topic but it is related to my problem)

**Comment by blowdart** [comment]
Nope, that's how it works (and a bunch of others do it that way too). Again, you'd have to configure identity to check the database more frequently,

**Comment by Luk164** [comment]
@blowdart Allright, I will leave that one as is and fix it if it ever becomes an issue. BTW I am running server-side blazor, if that changes anything.

**Comment by HaoK** [comment]
I'm not sure if there's any questions that still need answer here, with respect for NormalizedName, that's not something for the POCO to set, its a field that the store uses to update the normalized value, as its a configurable service, the constructor should not be responsible for keeping the value updated.

**Comment by Luk164** [comment]
> I'm not sure if there's any questions that still need answer here, with respect for NormalizedName, that's not something for the POCO to set, its a field that the store uses to update the normalized value, as its a configurable service, the constructor should not be responsible for keeping the value updated.

Yeah I see the bigger picture now. Though I do have one question, do we have to manually create the initialization method? Seems like a lot of code that can be easily automated. Like a method that accepts an array of roles and makes sure they are created in a correct way.
