### ISSUE TITLE
Proposal to change the access modifier from a few classes

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#27363]
## Summary

Proposal to change the following classes' access modifier from `internal` to `public`:

- `Microsoft.AspNetCore.Mvc.ViewFeatures.FormatWeekHelper`
- `Microsoft.AspNetCore.Mvc.ViewFeatures.NameAndIdProvider`
- `Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateRenderer`
- `Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingHelper`

## Motivation and goals
With the rise of Web Components implementations, like [FAST](https://fast.design), there will probably also be a rise in authored Razor Pages tag helpers to decrease the amount of boiler plate HTML code.

When building my own version of the `Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper` for the FAST Design's `<fast-text-field>` I had to copy paste public methods from all of the afore mentioned classes because they were not accessible. It doesn't seem right coping in code that is already in the ASP.NET Core assembly.

## In scope
1. Evaluate the possible risks of changing access modifiers.
2. Make use of C#'s nullable feature.

## Out of scope
Wouldn't want to make any braking changes.

## Risks / unknowns
I think developers that leverage Tag Helpers will see this as a great reduction in code writing and I don't think this will impact future enhancements. However, changing the access modifier could be a concern.

## Examples
It could possibly reduce the amount of code necessary for writing a simple tag helper with support for property binding implementation by more then 50%.

**Comment by BrunoBlanes** [comment]
Would also be nice to make the following fields `protected` instead of `private`.

```c#
namespace Microsoft.AspNetCore.Mvc.TagHelpers
{
    /// <summary>
    /// <see cref="ITagHelper"/> implementation targeting &lt;input&gt; elements with an <c>asp-for</c> attribute.
    /// </summary>
    [HtmlTargetElement("input", Attributes = ForAttributeName, TagStructure = TagStructure.WithoutEndTag)]
    public class InputTagHelper : TagHelper
    {
        private const string ForAttributeName = "asp-for";
        private const string FormatAttributeName = "asp-format";

        [...]
    }
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While many of our customers asked us to expose different internal areas from the framework, we can't do some of these asks unless we here that being a blocker for a wider community.
The main reason is that by exposing internals we're limiting our ability to fix things without breaking changes.

Having said that, this particular ask is not popular either, so we won't be changing the types you're requested to be public.
