### ISSUE TITLE
.NET 5 not Work in VS ent 16.7.7

### ISSUE THREAD

**Issue by SpringHgui** [dotnet/aspnetcore#27361]
.NET 5 rc2 is Latest version
VS ent 16.7.7 is Latest version

**Comment by BrunoBlanes** [comment]
ASP.NET Core's latest RC release depends on the .NET 5 RC 2 SDK which is only supported on Visual Studio 16.8 Preview 4 and later. [Here](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-2/#get-started) is the blog post.
