### ISSUE TITLE
How can multiple WASM projects share a hosted architecture as a Subpath

### ISSUE THREAD

**Issue by Yuanxw612** [dotnet/aspnetcore#27365]
How multiple wasm projects share a hosted implementation, in the form of subpath firstapp and secondapp on http://www.name.com/firstapp and http://www.name.com/secondapp for a visit.How to implement debug

**Comment by Yuanxw612** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#hosted-deployment-with-multiple-blazor-webassembly-apps  

I tried according to the document, but did not achieve the corresponding target correctly. The resource file could not be accessed normally, because I did not know whether it was feasible.

**Comment by javiercn** [comment]
@Yuanxw612 thanks for contacting us.

Check-out [the following sample](https://github.com/javiercn/BlazorMultipleApps) and see if that helps you get unblocked.

We are not sure what you mean by "sharing" but if you mean loading dlls from a single location for both projects, you'll likely have to disable linking and write a custom boot resource loader to change the location of where the files are being loaded.

**Comment by Yuanxw612** [comment]
@javiercn I downloaded the example and made the following changes, which I expect to use in a different path under a domain name

```
app.MapWhen(ctx => ctx.Request.Path.Equals("/firstapp"), first =>
            {
                first.Use((ctx, nxt) =>
                {
                    ctx.Request.Path = "/FirstApp" + ctx.Request.Path;
                    return nxt();
                });
                first.UseBlazorFrameworkFiles("/FirstApp");
                first.UseStaticFiles();

                first.UseRouting();
                first.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapFallbackToFile("/FirstApp/{*path:nonfile}", "FirstApp/index.html");
                });
            });

            app.MapWhen(ctx => ctx.Request.Path.Equals("/secondapp"), second =>
            {
                second.Use((ctx, nxt) =>
                {
                    ctx.Request.Path = "/SecondApp" + ctx.Request.Path;
                    return nxt();
                });
                second.UseBlazorFrameworkFiles("/SecondApp");
                second.UseStaticFiles();

                second.UseRouting();
                second.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapFallbackToFile("/SecondApp/{*path:nonfile}", "SecondApp/index.html");
                });
            });
```
But it doesn't work properly when I debug
![image](https://user-images.githubusercontent.com/15828095/97689012-f07cd080-1ad5-11eb-8675-dfd2090bde22.png)

![image](https://user-images.githubusercontent.com/15828095/97689277-4a7d9600-1ad6-11eb-9eaa-6a1b8014b6b3.png)

These 404 resource path is https://localhost:44302/FirstApp/css/bootstrap/bootstrap.min.css。

I don't know what to do to implement this feature, please help me

**Comment by javiercn** [comment]
@Yuanxw612 look at your csproj files and the csproj files in the projects. They have a "StaticWebAssetBasePath" property you need to change.

**Comment by Yuanxw612** [comment]
I downloaded the source code directly to make the changes， the project is https://github.com/javiercn/BlazorMultipleApps
StaticWebAssetBasePath has been modified,

```
 <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <StaticWebAssetBasePath>FirstApp</StaticWebAssetBasePath>
  </PropertyGroup>

```
```
<PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <StaticWebAssetBasePath>SecondApp</StaticWebAssetBasePath>
  </PropertyGroup>
```

**Comment by Yuanxw612** [comment]
In.NET Core 5.0 I implemented it the following way, but I don't know if there are any other issues

```
app.UseBlazorFrameworkFiles("/FirstApp");
            app.UseBlazorFrameworkFiles("/SecondApp");
            app.UseStaticFiles();

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("/FirstApp/{*path:nonfile}", "FirstApp/index.html");
                endpoints.MapFallbackToFile("/SecondApp/{*path:nonfile}", "SecondApp/index.html");
            });
```

**Comment by javiercn** [comment]
@Yuanxw612 we have discovered a regression in 5.0 that prevents this from working, but it will be fixed in one of the following patch releases. Here is the issue tracking the fix https://github.com/dotnet/aspnetcore/issues/27776

I'm closing this issue in favor of the other.
