### ISSUE TITLE
Have a way to generate CSS in C# for Blazor

### ISSUE THREAD

**Issue by nerocui** [dotnet/aspnetcore#27362]
Currently in Blazor, styling is plain `CSS`. A lot of npm based SPA framework use `CSS preprocessors` like `SASS` and `LESS`, but these tools are based on `npm` and are hard to integrate into the dotnet workflow in the best practice. React has also moved onto `jss` where style is defined in `JavaScript` and compiled into `CSS`.

Blazor should have something similar, where the developer can define styles of a component in C# classes and use them in the component tag.

For example
```razor
@using MyProject.Styles.Components
<div class="@CardStyle.Container">
    <h3 class="@CardStyle.Title">Title Text</h3>
    <p class="@CardStyle.Description">Description</p>
    <div class="@CardStyle.Actions">
        <button class="@CardStyle.ButtonSecondary">
            Cancel
        </button>
        <button class="@CardStyle.ButtonPrimary">
            Confirm
        </button>
    </div>
</div>
```
and the C# code can be like
```csharp
namespace MyProject.Styles.Components
{
    public class CardStyle : IStyleGenerator
    {
        public static string Container = new Style
        {
            Width: Style.Size.FromRem(20),
            Height: Style.Size.FromRem(30),
            Padding: Style.FourSidedSize.FromPixel(15, 10, 15, 0),
            MarginLeft: Style.Size.FromRem(1)
        }.Build();

        public static string Title= new Style
        {
            FontSize: Style.Size.FromPixel(24),
            FontColor: Style.Color.FromHex("000000"),
            FontFamily: Style.FontFamily.FromString("Helvetica"),
        }.Build();

        public static string Description= new Style
        {
            FontSize: Style.Size.FromPixel(15),
            FontColor: Style.Color.FromHex("000000"),
            FontFamily: Style.FontFamily.FromString("Helvetica"),
        }.Build();

        public static string Actions = new Style
        {
            Width: Style.Size.FromRem(16),
            Height: Style.Size.FromRem(26),
            Padding: Style.FourSidedSize.FromPixel(10, 5, 10, 3),
        }.Build();

        public static string ButtonSecondary = new Style
        {
            Width: Style.Size.Auto,
            Height: Style.Size.Auto,
            BackgroundColor: Style.Color.Red,
            Padding: Style.FourSidedSize.FromPixel(5, 3, 5, 3),
        }.Hover(x => x.BackgroundColor = Style.Color.Green)
        .Not.LastChild(x => x.MarginRight: Style.Size.FromRem(1))
        .Build();

        public static string ButtonPrimary = new Style
        {
            Width: Style.Size.Auto,
            Height: Style.Size.Auto,
            BackgroundColor: Style.Color.Green,
            Padding: Style.FourSidedSize.FromPixel(5, 3, 5, 3),
        }.Hover(x => x.BackgroundColor = Style.Color.FromRgb(123,111, 0))
        .Not.LastChild(x => x.MarginRight: Style.Size.FromRem(1))
        .Build();
    }
}
```
Each style block is a `Style` object with a call to a `Build()` method that returns the generated class name. The generated `CSS` source code will then be inserted into the pages.

This way, everything will work with `dotnet watch run`. Dev will be able to see style changes when the browser automatically refreshes.

**Comment by javiercn** [comment]
@nerocui thanks for contacting us.

This is a very opinionated way of authoring your CSS. I don't think this a direction we want to take at the moment. It'll be something expensive to build and maintain and we don't think there is any blocker for anyone else on the community to build something like this. Are we missing something?

**Comment by sps014** [comment]
@nerocui great proposal.

**Comment by BrunoBlanes** [comment]
@nerocui are there any advantages to a "C# compiled to CSS" code?I 'd love to do everything in C#, but it this doesn't seem to make code writing any easier given that VS already supports CSS validation and autocompletion in IntelliSense.

**Comment by nerocui** [comment]
> @nerocui are there any advantages to a "C# compiled to CSS" code?I 'd love to do everything in C#, but it this doesn't seem to make code writing any easier given that VS already supports CSS validation and autocompletion in IntelliSense.

My vision is more align with scss, less or jss where better syntax can help code management and readibility. Being in C# also means style change can be iterated faster with hot reload. It's still gonna be compuled into css in production.

**Comment by nerocui** [comment]
> @nerocui thanks for contacting us.
> 
> This is a very opinionated way of authoring your CSS. I don't think this a direction we want to take at the moment. It'll be something expensive to build and maintain and we don't think there is any blocker for anyone else on the community to build something like this. Are we missing something?

Thanks for your time and reply. I did think about prototyping it. But I wasn't sure how to insert CSS code in the wwwroot folder. I wanted to look into source generation, but that seemed like to be for C# only.

**Comment by robertsundstrom** [comment]
This is not something that should be part of Blazor. It is the web, and we need a community and not Microsoft to build everything.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
