### ISSUE TITLE
Better modules support

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27388]
## Summary

We should try to better support modularity. As part of that we need to look into: 
- Investigate what are ASP.NET specific concepts which needs to be cleaned up when unloading assemblies
- Find out how exactly we load assemblies in the code and whether there are better ways to do that

This is not about to make plugins available out of the box, rather how to make it possible to easily build plugins on top of the framework.

This is potentially related to `Hot Reload` effort.

### People with more context
@davidfowl, @shirhatti, @halter73, @pranavkm 

## Motivation and goals

1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by WeihanLi** [comment]
😭

**Comment by davidfowl** [comment]
Please look at orchard core as an alternative. It has a thoughtfully designed module system that can be used in any ASP.NET Core application today.
cc @sebastienros
