### ISSUE TITLE
Developers can safely trim ASP.NET apps to reduce their deployment payloads

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27384]
## Summary

This is a big effort to help with better trimming of the library with the goal of reducing the size of a published app.
There are some design choices we've made which make it hard to trim unused code (broadly, anything that uses reflection)
As part of this effort those designs should be reviewed to see whether we can find better alternatives. 

### People with more context
@davidfowl, @halter73, @javiercn, @captainsafia

## Motivation and goals

This is part of a bigger plan to make the higher level frameworks trimmable (see https://github.com/dotnet/runtime/issues/43543).

We also want to make sure people can host web servers as part of cloud infrastructure as small single file executables.

Longer term, we want to make sure that ASP.NET Core can work in full AOT mode without reflection and this is the first stage of that journey.

## In scope

We want to make sure we can trim ASP.NET Core applications with confidence by default. Our target for .NET 6 is APIs only. This includes:

## Out of scope

We're not going to focus on applications with Web Applications at the moment. Web Applications with Razor views won't be explicitly trimmable in .NET 6.

## Risks / unknowns

Testing is one of the really hard things to cover when doing linking. To get 100% coverage you need to basically re-run all of the tests with the appropriate code linked.

**Comment by Pilchie** [comment]
:eyes:

**Comment by danmosemsft** [comment]
Making this a user story to parallel the base libraries story.

**Comment by mkArtakMSFT** [comment]
Marking with both area-labels as this is a cross-cutting effort.

**Comment by danroth27** [comment]
Related issues (query based on linker-friendliness label):

- https://github.com/dotnet/aspnetcore/issues/24725
- https://github.com/dotnet/aspnetcore/issues/24724
- https://github.com/dotnet/aspnetcore/issues/24723
- https://github.com/dotnet/aspnetcore/issues/29913
- https://github.com/dotnet/aspnetcore/issues/24705

**Comment by Pilchie** [comment]
See also https://docs.microsoft.com/en-us/dotnet/core/deploying/prepare-libraries-for-trimming, which has details on what to do here.

**Comment by mkArtakMSFT** [comment]
Moving the remaining work to the .NET 8 Planning milestone to handle in the future.

**Comment by mkArtakMSFT** [comment]
@JamesNK what is left to be done here? I know for Blazor we still have work to do. Is there anything else related to trimming on your side, or can I file a new Blazor-specific issue and close this?

**Comment by JamesNK** [comment]
Blazor and razor. @eerhardt youre probably closer to this than I am now. Major gaps in AspNetCore trimming/AOT story?

**Comment by davidfowl** [comment]
I think this should be closed and more specific issues can be opened.

**Comment by richard-collette-precisely** [comment]
> I think this should be closed and more specific issues can be opened.

But who, that knows the specific issues, is going to file it @davidfowl ?

**Comment by davidfowl** [comment]
Doesn't matter, this issue no longer serves a purpose.

**Comment by eerhardt** [comment]
For Blazor we already have:

* [Make Blazor WebAssembly apps fully trimmable (dotnet/aspnetcore#49409)](https://github.com/dotnet/aspnetcore/issues/49409)
* [[Blazor] Enable Blazor apps running inside of ASP.NET Core to be Native AoT compiled (dotnet/aspnetcore#51598)](https://github.com/dotnet/aspnetcore/issues/51598)

For SignalR, the core + JSON protocols have been made trim and AOT compatible in .NET 9. [[Trimming] SignalR (dotnet/aspnetcore#41704)](https://github.com/dotnet/aspnetcore/issues/41704) is still open to track the remaining 2 protocols: MessagePack and SE.Redis.

For MVC, we have [[Trimming] MVC (dotnet/aspnetcore#41767)](https://github.com/dotnet/aspnetcore/issues/41767).

The other areas listed on https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-9.0#aspnet-core-and-native-aot-compatibility are:

* "Other authentication" (besides JWT)
* Session
* Spa

**Comment by mkArtakMSFT** [comment]
Thanks @JamesNK, @davidfowl and @eerhardt. Closing this now. I've created two more issues:
- https://github.com/dotnet/aspnetcore/issues/58787
- https://github.com/dotnet/aspnetcore/issues/58786

As for the SPA point, we don't think that area needs to support trimming.
