### ISSUE TITLE
Address file-locking issue in IIS

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27395]
## Summary

When someone wants to deploy an app to IIS, they currently require either an external tool or to know that they need to drop the file `app_offline` to the directory to shutdown the app. If someone tries to deploy the app without doing this, files will be locked as they are currently being used.

This is a regression from .NET Framework, which used shadowcopying. This is a proposal to add some sort of shadow copying implementation to ANCM, giving customers an option to not have to worry about locked files.

### People with more context
@jkotalik, @davidfowl, @Tratcher 

## Motivation and goals

- Improve a long time customer painpoint which hasn't been addressed.
- Deliver a complete solution which specifically targets locked files
- Address tradeoffs with shadow copying.

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

- Increased disk space usage due to shadow copies.
- Differences in file locations need to be handled by user code.
- Cost of copying every file to a different directory.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by jkotalik** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/3793
