### ISSUE TITLE
Document why using IHttpContextAccessor is discouraged

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27392]
### People with more context
@halter73 

## Motivation and goals

1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by adityamandaleeka** [comment]
There's a remark already on the IHttpContextAccessor doc here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-5.0

@davidfowl suggested adding an aka.ms link to those remarks pointing to the [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-5.0#do-not-store-ihttpcontextaccessorhttpcontext-in-a-field) section that talks about IHttpContextAccessor usage.

**Comment by JamesNK** [comment]
The remarks should say:

* Say that it is discouraged and why. We already have this.
* Discuss what we recommend: getting the current HttpContext from the executing request. How someone should do this will vary depending upon the app framework they are using. e.g.
  * minimal APIs should add a HttpContext parameter
  * MVC should get it from ControllerBase
  * [gRPC should use GetHttpContext](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-5.0&tabs=visual-studio#resolve-httpcontext-in-grpc-methods)
  * SignalR should use [GetHttpContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.gethttpcontextextensions.gethttpcontext?view=aspnetcore-5.0).
* Discuss scenarios when it should be used, i.e. there is no alternative. I believe this is when it is not possible to pass the HttpContext from the request to a piece of executing code.

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT should I transfer this to https://github.com/dotnet/AspNetCore.Docs/issues ?

**Comment by halter73** [comment]
This could probably be merged with https://github.com/dotnet/AspNetCore.Docs/issues/7721.

**Comment by adityamandaleeka** [comment]
Moved this to a different milestone since NSP is getting cleared out. In reality, the milestone is the one in https://github.com/dotnet/AspNetCore.Docs/issues/7721

**Comment by adityamandaleeka** [comment]
Closing; this was done in https://github.com/dotnet/AspNetCore.Docs/issues/7721
