### ISSUE TITLE
Add Documentation IJSUnmarshalledRuntime and mono BINDING.js

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#27391]
For fast jsInterop IJSUnmarshalledRuntime seems best choice but there is no documentation or any thing for it. Also underlying BINDING.js methods are  undocumented.
Please provide documentation and
Please
Add support for many parameters in Invoke method IJSUnmarshalledRuntime ie.
```cs
Runtime.InvokeUnmarshalled<R,T1,T2,T3,T4,T5,T6>(....);//something like this
```
and how can we invoke void function from it, like in IJSRuntime there is InvokeVoidAsync() ,

```cs
Runtime.InvokeVoidUnmarshalled<T1,T2,T3>(....);//something like this
```
there is no alternative to it in IJSUnmarshalledRuntime.
Please provide some sort of roadmap or insight on this.

**Comment by david-uk-hash** [comment]
Yes please i am also in for this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Have you seen this documentation: https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0&preview=1#consider-making-unmarshalled-calls
Is there something else you're looking for?

**Comment by sps014** [comment]
@mkArtakMSFT sorry but page doesn't contain all the information .
suppose I need to pass more than 5 variables to a js function, in that case I have to fall back to IJSInProcessRuntime,
there must be a way to achieve this in single invoke.
```js
function foo(a,b,c,d,e,f)
{
      ....
     return num;
}
```
i can't invoke from IJSUnmarshalledRuntime
```cs
iJSUnmarshalledRuntime.Invoke<int,int,int,int,int,int>("foo",a,b,c,d,e); //❌

```
as this will throw error that the function doesnot expect more than 3 argument.

so to achieve this i need to do
```cs
iJSInProcessRuntime.Invoke<int>("foo",a,b,c,d,e); //✔️
```
this works but this does marshalling , and in my high performance scenario this ruins most of the stuff.

Also how can i pass a class object to Unmarshalled function and then use it in js ?

```cs
 iJSmarshalledRuntime.Invoke<object>("take",new GameObj());
``` 

what should i have to do in JS, as 

```js
function take(obj)
{
// how to unwrap obj now 😢
// as BINDING and Blazor.Platform is undocumented

}
```

how to convert mono obj to JS object ?
