### ISSUE TITLE
HealthCheck logging CandidateNotFound and "Request did not match any endpoints"

### ISSUE THREAD

**Issue by leofmoura** [dotnet/aspnetcore#27396]
### Describe the bug
HealthChecks is logging "No candidates found for the request path '/health-check'".

### To Reproduce
1. Using version 3.1.3 of package netcoreapp3.1\Microsoft.Extensions.Diagnostics.HealthChecks.dll
2. Hosting on Azure WebApps, we seen a log of tracing logs with CandidateNotFound and "Request did not match any endpoints"
3. The startUp contains the simple code: 
`app.UseHealthChecks("/health-check", new HealthCheckOptions()
            {
                AllowCachingResponses = false
            });`

### Expected behavior
I do not expect to have these tracing messages, once the request is finally well executed, this disturbs a bit the logging.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by JamesNK** [comment]
I think you have two options to avoid this logging message:
1. Move `UseHealthChecks` above `UseRouting`
2. Remove `UseHealthChecks` and add `MapHealthChecks` inside `UseEndpoints`.

**Comment by leofmoura** [comment]
Thanks James, it works just file the MapHealthChecks.

BTW, nice talk at .NetConf!
