### ISSUE TITLE
blazor wasm hosted and api Is it possible to share a project

### ISSUE THREAD

**Issue by Yuanxw612** [dotnet/aspnetcore#27402]
blazor wasm hosted and api Is it possible to share a project.
i hope wasm  http://www.xxx.com/{wasm project} , api http://www.xxx.com/apis

I tried it and there seemed to be a problem，resource loading 404

**Comment by Yuanxw612** [comment]
In.NET Core 5.0 I implemented it the following way, but I don't know if there are any other issues

app.UseBlazorFrameworkFiles("/app1");
            app.UseBlazorFrameworkFiles("/app2");
            app.UseStaticFiles();

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("/app1/{*path:nonfile}", "app1/index.html");
                endpoints.MapFallbackToFile("/app2/{*path:nonfile}", "app2/index.html");
            });

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Yuanxw612.
What you've got in your last post is correct. Just make sure you also update the `<base href="" />` in the index.html to match the URL you've configured: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&amp%3Btabs=visual-studio&tabs=visual-studio#app-base-path
