### ISSUE TITLE
Blazor WebAssembly和Blazor Server能否在同一个项目混合使用

### ISSUE THREAD

**Issue by ghd258** [dotnet/aspnetcore#27412]
Blazor WebAssembly和Blazor Server能否在同一个项目混合使用

**Comment by david-uk-hash** [comment]
Kindly post in English so that we can understand and offer a working solution. 
Thank you.

**Comment by Pilchie** [comment]
Bing Translate says this is: "Whether Blazor WebAssembly and Blazor Server can be used in the same project"

**Comment by mkArtakMSFT** [comment]
@ghd258 can you please clarify what exactly you want here? Is this ask about hosting Blazor WebAssembly app in a Blazor Server app and having both models on the same page?

**Comment by ghd258** [comment]
1、hosting Blazor WebAssembly app in a Blazor Server app and having both models on the same page?  

2、in the same project  A page use Blazor Server  B page use Blazor WebAssembly  ？

**Comment by mkArtakMSFT** [comment]
#1 is not supported at this point. As of right now we don't plan to make this possible.
