### ISSUE TITLE
IHostedService blocks Http requests

### ISSUE THREAD

**Issue by aussieweever** [dotnet/aspnetcore#27415]
I have a Web API project using dotnet 3.1 works fine until I added a hosted service. I tried to debug under IIS express and run it under IIS, both have the same behavior that the application stop handling Http requests. The one under IIS returns HTTP Error 500.37 - ANCM Failed to Start within startup time limit. The one under IIS express never expires and just keeps loading. Also tried with Postman and have the same result.

I can resolve this issue by using Autofac to register the hosted service. Also I created a brand new Web Api project, and can 100% reproduce this issue. The default _WeatherForecast_ API will be blocked without using Autofac.

**Startup.cs**

```C#
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
        // public ILifetimeScope AutofacContainer { get; private set; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddHostedService<DataCheckService>(); // remove this line when using Autofac
        }

        // Enable following code when using Autofac
        // public void ConfigureContainer(ContainerBuilder builder)
        // {
        //     builder.RegisterType<DataCheckService>()
        //         .AsImplementedInterfaces()
        //         .SingleInstance();
        // }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```

**My background service**

```C#
    public class DataCheckService: IHostedService, IDisposable
    {
        private readonly ILogger _logger;

        public DataCheckService(ILogger<DataCheckService> logger)
        {
            _logger = logger;
        }

        private void DoWork(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Doing job...");
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                DoWork(cancellationToken);
                await Task.Delay(TimeSpan.FromMinutes(1), cancellationToken);
            }
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        public void Dispose()
        {
            _logger.LogInformation("Disposing");
        }
    }
```
Any suggestions? The thing confuses me is why it works when using Autofac.

**Comment by davidfowl** [comment]
The Start task is about a synchronously starting, not running. The host won't start properly until the task returned from start completes. You need to dispatch that long running task (I recommend you use a background service for this) with a Task.Run and ignore the result (at least in Start)

**Comment by Tratcher** [comment]
https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs

**Comment by aussieweever** [comment]
@davidfowl @Tratcher Thanks I see what you mean. 

Just wonder why it works when using Autofac

**Comment by Tratcher** [comment]
Is it an ordering issue? If your IHostedService were registered after the web app hosted service then the web service would start before yours and you wouldn't notice the blockage.
