### ISSUE TITLE
NullReferenceException in InputTagHelper if input has no asp-for attribute filled

### ISSUE THREAD

**Issue by Pankraty** [dotnet/aspnetcore#27414]
### Describe the bug

If I introduce a custom TagHelper derived from `InputTagHelper` for `type=input` the page rendering start to fail with `NullReferenceException` if there is an input of type `submit` that does not have `asp-for` property filled. Filling that property with some property name prevents such error but looks like a mere workaround, not a fix.

The most probable cause of the issue is [this fragment](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.TagHelpers/src/InputTagHelper.cs#L175) :
```
            var metadata = For.Metadata;
            var modelExplorer = For.ModelExplorer;
            if (metadata == null)
            {
                throw new InvalidOperationException(Resources.FormatTagHelpers_NoProvidedMetadata(
                    "<input>",
                    ForAttributeName,
                    nameof(IModelMetadataProvider),
                    For.Name));
            }
```
When `For` property is null NRE is thrown. But I do not understand why this only happens when custom TagHelpers are defined so I did not take responsibility for providing a fix.

### To Reproduce

Here is the repository reproducing the issue https://github.com/Pankraty/taghelper-issue/commits/master

* Pankraty/taghelper-issue@fb26482bf59e111db57427839fd52ebeddfc2657- add a simpliest for with `<input type="submit" />` - works OK
* Pankraty/taghelper-issue@57e7ec4657d3173bdb2788141ed55d2900e0efe4 - add a custom TagHelper that does absolutely nothing, the page rendering starts to throw `NullReferenceException`
* Pankraty/taghelper-issue@dab332ddee54ca8ab60feb36bacfc0412477617a - fill-in `asp-for` attribute with absurdly meaningless value, the exception is gone.

The same can be reproduced with other types of inputs (e.g. `input type="checkbox" />`) if they don't have `asp-for` attribute.

### Exceptions (if any)

`Object reference not set to an instance of an object.`
```
   at Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore.Views_Home_Index.<<ExecuteAsync>b__11_0>d.MoveNext()
```

### Further technical details
- ASP.NET Core version 
3.1.0.0 (FileVersion 3.100.320.12812)
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.514 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
-- Visual Studio 2019 (16.7.2)
-- JetBrains Rider 2020.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `asp-for` is a key property for the InputTagHelper. If this is limiting your component, we recommend deriving your custom tag helper from it's parent type instead.

**Comment by Pankraty** [comment]
Hi @mkArtakMSFT ! Thanks for the answer but I'd like to notice that documentation for the method states
```
        /// <remarks>Does nothing if <see cref="For"/> is <c>null</c>.</remarks>
        /// <exception cref="InvalidOperationException">
        /// Thrown if <see cref="Format"/> is non-<c>null</c> but <see cref="For"/> is <c>null</c>.
        /// </exception>
```
(https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.TagHelpers/src/InputTagHelper.cs#L140)

In my case both `Format` and `For` are nulls but the method still throws the exception, and it's not the `InvalidOperationException` but `NullReferenceException` which for me looks like an indication of some missed part of logic.

bfdeda797df054a4ae8a6fa9250e65f07cd63a1e - this commit seems to break that logic. And I think this part has to be restored:
```
if (For == null)
{
     // Regular HTML <input/> element. Just make sure Format wasn't specified.
     if (Format != null)
     {
         throw new InvalidOperationException(Resources.FormatInputTagHelper_UnableToFormat(
             "<input>",
             ForAttributeName,
             FormatAttributeName));
    }
}
```

I can submit a PR if you agree.
