### ISSUE TITLE
Memory leakage when using 'return' during rendering logic

### ISSUE THREAD

**Issue by zachneu** [dotnet/aspnetcore#27429]
I have a blazor component with a loop for creating the gui based on data in some List<>
There is some conditions need to be met to generate the view.
The code is like
@foreach(var myVar in myList)
{
if (myConditon == false)
continue;
<b>myGui</b>
}

By a typo, i wrote "return" and not "continue" and this caused the view to never be generated and all memory on the developer machine beeing consumet by the application (59GB!)

There is no reading of new data in the foreach loop. only some linq queries on existing List<>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@SteveSandersonMS do you happen to remember a different issue tracking some work to prevent the bad usage of `return` in similar situation?

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Yeah, I do faintly remember that. However I don't recall how it was phrased in the previous report, and hence haven't been successful in searching for it. Maybe we should use this issue to track that problem now.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
