### ISSUE TITLE
@AYanuseuskaya Yeah, it looks like the `blazor.boot.json` is not getting generated for some reason. It looks like your using the default template and the build output says it built cleanly, but this file is not being produced or is somehow being deleted. We've seen other reports of this issue (#12637, aspnet/blazor#1469, #11547). We did find in one case (#11034) that the file was getting deleted by antivirus software. Can you check to see if that might be happening on your machine? Maybe try disabling your antivirus software temporarily and then rebuild and run?

### ISSUE THREAD

**Issue by eXapppk** [dotnet/aspnetcore#27427]
i am Getting the same issue but in my case i don't have any antivirus just working with windows defender i also turn off real-time protection but when i rebuild the application  "service-worker-assets.js" from compressed folder and blazor.boot.json from the framework folder and my referenced project removed. to verify the scenario I told, I have a copy of my project then I manually copy these mentioned files  any past in the required location then run the application the application run successfully but after first run i rebuild the application the above mentioned files again removed from the solution and getting error of not found these files.

**Comment by Tratcher** [comment]
This is a continuation of #13166?

**Comment by mkArtakMSFT** [comment]
Closing as this was already reported here: https://github.com/dotnet/aspnetcore/issues/27428
