### ISSUE TITLE
Discussion on Blazor's data refresh mechanism

### ISSUE THREAD

**Issue by wzxinchen** [dotnet/aspnetcore#27425]
### Is your feature request related to a problem? Please describe.
My native language is not English, so this description was translated by Google.
Define the words, refresh means re-render
I have been studying Blazor for a long time. I have my own Blazor component library. I have also read the source code of Blazor. I have some questions and I want to discuss it.
As far as I know, Blazor has a forced refresh mechanism, the method is called StateHasChanged.
In the Angular or Vue frameworks that I have contacted, it seems that there is no such refresh mechanism, or I have not used it, but the problem is that I can develop applications without using it, such as an application that displays the time regularly.
But for Blazor, not calling StatehasChanged will cause many functions to be impossible, such as timing display of time.

I am curious why this is, is there any magic in Angular or Vue? Later, I studied the mechanisms carefully and found that their mechanisms are actually quite simple, just using the JS proxy mode. C# can also perform dynamic proxying. Why doesn't Blazor do this?

The core of the current Blazor refresh mechanism is StateHasChanged. EventCallBack also calls StateHasChanged internally. If this method is called, it will be refreshed in most scenarios and will cause cascading to refresh all sub-components to avoid sub-component refreshing. It's just the ShouldRender method and a very loose method of judging whether the parameter has changed. If the parameter changes, it will be refreshed. However, the judgment logic of this method is too loose.

### Describe the solution you'd like
My thought is, why can't we use dynamic proxy to accurately grasp the refresh timing and avoid unnecessary refresh as much as possible?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and sharing your concerns regarding the approaches we've taken.
This was an intentional choice for us. We as well as anyone else at this point can build on top of the current framework and introduce the concepts similar to `INotifyPropertyChange` which can help with automating all this cycle.
That said, we've chosen to stick to low-level C# concepts giving complete freedom to the developers about how they want to build apps.
