### ISSUE TITLE
Blazor Files Automatically Removed or not producing properly.

### ISSUE THREAD

**Issue by eXapppk** [dotnet/aspnetcore#27428]
i am Getting the same issue but in my case i don't have any antivirus just working with windows defender i also turn off real-time protection but when i rebuild the application "service-worker-assets.js" from compressed folder and blazor.boot.json from the framework folder and my referenced project removed. to verify the scenario I told, I have a copy of my project then I manually copy these mentioned files any past in the required location then run the application the application run successfully but after first run i rebuild the application the above mentioned files again removed from the solution and getting error of not found these files.
![BlazorError](https://user-images.githubusercontent.com/72805759/97839335-d58fa380-1d03-11eb-9400-54f2d09da514.PNG)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
 We've made a lot of improvements in this area in 5.0
Can you give it a try and let us know whether you're still facing that issue? Thanks!

**Comment by eXapppk** [comment]
Yes the above is resolved by updating Microsoft.AspNetcore.Components.WebAssembly.Build (from 3.2.1 to  v5.0.0-preview.6.20312.15).

**Comment by mkArtakMSFT** [comment]
Thanks for confirming this, @eXapppk. we recommend moving to 5.0 (it'll be releasing soon) to avoid this issue.
