### ISSUE TITLE
CSC: warning AD00001

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/aspnetcore#27439]
### Describe the bug
When running a CI build I get that warning all the time. Note that still dispite the warning the built application still runs fine. This is a multi-project single-solution project with no nested projects.

```
CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/home/runner/work/X/X/Y.Z/Y.Z.csproj]
```

### To Reproduce
The sub project that causes that exception has the following csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Y.Common/Y.Common.csproj" />
        <ProjectReference Include="..\Y.User\Y.User.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.8" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>../Modules/Debug</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>../Modules/Release</OutputPath>
    </PropertyGroup>

</Project>
```

The built dll is intended to be linked at runtime by another application in the same solution. The problem only rises when running `dotnet build` at the root of the solution.

### Exceptions (if any)
'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.

### Further technical details
- ASP.NET Core version 3.1.x. Not exactly sure as I'm using GitHub Actions CI
- Include the output of `dotnet --info`
> I don't have access to a terminal over SSH in GitHub Actions so cannot tell for the CI build.
> I know at least that the CI build is running ubuntu-latest and uses actions/setup-dotnet@v1.6.0 in order to download and install the .NET Core SDK.
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
JetBrains Rider under Linux (VS Code is not as powerfull as VS for windows, and because of the cross platform nature of the project, best option is Rider).

After more investigation it is reproducible under a local computer running Pop! OS 20.10 distribution based on Ubuntu 20.10:
- `dotnet --info` on the local computer gives:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     pop
 OS Version:  20.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

The exact same error is generated on this computer and always points to csproj I gave here.

**Comment by pranavkm** [comment]
Thank you for your bug report. https://github.com/dotnet/aspnetcore/issues/14723#issuecomment-588389938 details some of the causes and resolution for the bug fix.

In this particular case, I can see that your app continues to reference a 2.2 version of MVC. Migrating it by targeting the Web SDK and removing obsolete package references should help: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#remove-obsolete-package-references
