### ISSUE TITLE
AspNetCore 3.1 validation bug with model from a NuGet Package?

### ISSUE THREAD

**Issue by PedroAMCoelho** [dotnet/aspnetcore#27448]
Hi, I have a solution with a .NET Core 3.1 project. This project has a NuGet package dll as one of its dependencies and such NuGet package has several models. We have controller endpoints in this .NET Core 3.1 project that expect models from this NuGet package as parameters. However, when I perform a request to any of these endpoints, validation errors are thrown for non-nullable reference type properties. As we have lots of string properties, you can imagine that a couple of errors are arising.

This issue seems quite related to these ones:
https://github.com/dotnet/aspnetcore/issues/14812
https://github.com/dotnet/aspnetcore/issues/16654

Nonetheless, differently from the issues above, inheritance does not seem the core issue here, as the properties involved in the errors are not from a base class. Moreover, my project is .NET Core 3,1 and not 3.0, as it was the case in these previous issues.

I tried the turnaround suggested on issue 14812 and set _SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true_. It worked, but it would be important to have this fixed once and for all.

Edit: Additional info: The NuGet package is a class library with .NET Standard 2.1 version as Target Framework. I believe this is an important missing information.

Edit2: I tried to update the NuGet package Target Framework version to .NET Core 3.1, but the error persisted.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will revisit a decision we had here to see whether we can have a runtime behavior to enable `Required` attribute for non-nullable reference types.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
