### ISSUE TITLE
Published Blazor Isolated Style Names Not Matching

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27446]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Published-Blazor-Isolated-Style-Names-No/1224611)._

---
[severity:Other] [regression] [worked-in:16.8 Preview 3.1 or 16.8 Preview 3.2]
When I'm running locally in debug mode, things are working correctly. Once I publish/deploy, the new isolated stylesheet styles at <Project>.styles.css aren't named to match their references in the html. For example, the tag attribute in the html may be b-774aojd2aj, but the related style in the stylesheet may say .something[b-2py4zgu4nx] instead of .something[b-774aojd2aj], preventing it from working.

---
####  on 10/17/2020, 11:23 AM: 

<p>Also, if I publish in Debug mode, it seems to work fine.</p>

#### Feedback Bot on 10/18/2020, 11:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/19/2020, 01:57 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
