### ISSUE TITLE
Add using light bulb execution results in malformed @page directive

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#27453]
1. Create a new Razor Pages project
2. Add an `@functions` block with a method
3. Write `Debugger` and invoke the "add using" light bulb.
![UPooUZq54E](https://user-images.githubusercontent.com/2008729/97918214-9d3f9380-1d0a-11eb-87b5-38df91ad2294.gif)

**Comment by dibarbet** [comment]
woops meant to leave a comment - I wasn't able to repro this

**Comment by NTaylorMullen** [comment]
> woops meant to leave a comment - I wasn't able to repro this

Was it in a Razor pages project? I was able to reproduce in VS and VSCode

**Comment by NTaylorMullen** [comment]
Just validated this still happens for me on latest 16.9-Preview3

**Comment by TanayParikh** [comment]
> woops meant to leave a comment - I wasn't able to repro this

Note; this might've been because we disabled the lighbulbs in the `@function` blocks with https://github.com/dotnet/aspnetcore-tooling/pull/2637. The underlying issue will repro from @code blocks.
