### ISSUE TITLE
Enable existing selenium tests to run cross-platform

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27458]
Currently these run only on Windows.

**Comment by mkArtakMSFT** [comment]
@javiercn I remember you mentioned this and said that you're experimenting with some other framework which is cross-platform. Do you have an existing issue tracking this? If so, feel free to dupe this.

**Comment by javiercn** [comment]
@mkArtakMSFT I'm currently experimenting with it, but we can use this issue to track.

I'll self-assign.

**Comment by javiercn** [comment]
@mkArtakMSFT closing this issue in favor of https://github.com/dotnet/aspnetcore/issues/27610
