### ISSUE TITLE
Razor Tooling shows bogus warning for nested 'Frame' tag "Element requires end tag" / "missing matching start tag"

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#27450]
### Describe the bug

If you have a tag named `Frame` (such as by having a file `Frame.razor`) then if you nest it within itself you get a warning.

This syntax:

```xml
<Frame>
    <Frame></Frame>
</Frame>
```

Gives this pair of warnings:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Element 'Frame' requires end tag.	BlazorApp1	C:\Users\elipton\source\repos\BlazorApp1\BlazorApp1\Pages\Index.razor	1	
Warning		End tag is missing matching start tag	BlazorApp1	C:\Users\elipton\source\repos\BlazorApp1\BlazorApp1\Pages\Index.razor	3	
```

![image](https://user-images.githubusercontent.com/202643/97907191-bdb32200-1cf9-11eb-9b2b-eb8492439930.png)

### To Reproduce

1. File / New Blazor Server Project
1. Create a file `Pages/Frame.razor` with any contents (feel free to add a `ChildContent` to it but it doesn't matter)
1. Go to another file such as `Pages/Index.razor` and use the new `Frame` tag you created, and then try to nest it within itself: `<Frame><Frame></Frame></Frame>`

And you get green warning squigglies on the outer `<Frame>` tag. Interestingly, you also don't get Intellisense for the inner `Frame` tag - it's as if the IDE doesn't want you to type it.

### Logs & Exceptions

N/A

#### Activity log (only needed if VS crashes)

N/A

#### Language Server logs

Will provide if needed.

### Further technical details

```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 4.0
VisualStudio.16.Preview/16.8.0-pre.4.0+30608.117
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

ASP.NET and Web Tools 2019   16.8.544.20707
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2047412+61e28256c4cc2f7440cda06218667b711c678afd
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.544.20707
For additional information, visit https://www.asp.net/
```

### Pre-requisite checklist
- [ ] Steps to reproduce the issue
- [ ] Razor Language Server client logs included.
- [ ] HTML Language Server client logs included

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

**Comment by Eilon** [comment]
Nice, it does fix that issue! But then it causes another issue 😦 

It doesn't want to auto-complete the end tag, and for the nested one it does not even offer the correct choice:

![image](https://user-images.githubusercontent.com/202643/97931752-2fec2c80-1d23-11eb-931e-35e6f2c557f1.png)

**Comment by Eilon** [comment]
And it isn't to do with it being the inner tag. If I try to auto-complete the outer tag it also doesn't want to help me:

![image](https://user-images.githubusercontent.com/202643/97931815-58742680-1d23-11eb-95b4-0ab51b0636a3.png)

**Comment by Eilon** [comment]
And it still seems fairly specific to the word `<Frame>`. I've tried many other names and they all work. Is there something special about this name? Or it's a weird coincidence?

**Comment by Eilon** [comment]
Also the editor doesn't want to auto-complete the `</close>` tag of tags I accept via Intellisense.

In this scenario:

![image](https://user-images.githubusercontent.com/202643/97931954-a6892a00-1d23-11eb-9c87-ee44a7697e8f.png)

Normally when I type the `>` to close it, VS will insert the closing tag for me, but here it doesn't. If I do a regular HTML tag, such as `<a>` then when the `>` is typed it fills in `<a></a>` but not with Razor tags.

**Comment by TanayParikh** [comment]
> And it still seems fairly specific to the word `<Frame>`. I've tried many other names and they all work. Is there something special about this name? Or it's a weird coincidence?

It _may_ be because the `<frame>` tag is [reserved](https://www.tutorialspoint.com/html/html_frames.htm#:~:text=HTML%20Frames.%20HTML%20frames%20are%20used%20to%20divide,the%20tables%20are%20organized%3A%20into%20rows%20and%20columns.) within HTML.

**Comment by Eilon** [comment]
Ah yes I forgot about that ancient tag!

**Comment by NTaylorMullen** [comment]
Totally see the same thing! 
![image](https://user-images.githubusercontent.com/2008729/98030803-6a5ad580-1dc6-11eb-8572-778b08c795e0.png)

@Eilon could you log a separate issue about the completion issue and we can investigate further?

**Comment by Eilon** [comment]
@NTaylorMullen I opened https://github.com/dotnet/aspnetcore/issues/27502 to track the lack of auto-complete for the close tag.

**Comment by allisonchou** [comment]
This issue is tagged as being fixed in the new editor, so I'm going to close this out.
If you notice the problem persists in the new editor, please let us know by filing another issue. Thanks!
