### ISSUE TITLE
Razor transitions / C# in HTML comments doesn't get colored correctly

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#27454]
**VS:**
![image](https://user-images.githubusercontent.com/2008729/97919025-f0661600-1d0b-11eb-917f-fe0fa951a4d5.png)

We get slightly better colorization in VS because of C# semantic colorization; however we're still lacking transitions.

**VSCode:**
![image](https://user-images.githubusercontent.com/2008729/97919059-04aa1300-1d0c-11eb-8bdc-55368b036df8.png)

**Comment by ryanbrandenburg** [comment]
Pretty sure this is fixed by https://github.com/dotnet/aspnetcore/issues/26975.

**Comment by NTaylorMullen** [comment]
> Pretty sure this is fixed by #26975.

It also happens in VSCode though.

**Comment by ryanbrandenburg** [comment]
Wait, do we actually WANT C# code inside a comment to get colorized? I have been operating under the assumption that "inside a comment === comment green".

**Comment by NTaylorMullen** [comment]
> Wait, do we actually WANT C# code inside a comment to get colorized? I have been operating under the assumption that "inside a comment === comment green".

In an HTML comment it's super applicable to have valid C# code in it 😄. So HTML comments = yes

**Comment by ryanbrandenburg** [comment]
This was fixed by https://github.com/dotnet/aspnetcore-tooling/pull/2858.
