### ISSUE TITLE
Investigate runtimeconfig.json loading issues on App Service

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27469]
We have received some issue where customers have seen app startup failures due to the following error on app services:

```
Invalid runtimeconfig.json [D:\home\site\wwwroot\runtimeconfig.json] [D:\home\site\wwwroot\runtimeconfig.dev.json]
```

We should try to repro this on 5.0; we haven't seen any repro's since 2.2 though.

**Comment by demius** [comment]
I can confirm that this issue is occurring in .NET 5.0

**Comment by BrennanConroy** [comment]
Can you provide a repro?

**Comment by demius** [comment]
Sorry, @BrennanConroy, I've actually trashed the App Service, so I don't have access to the logs.
Suffice to say, I had a straightforward Asp.Net Core 5 application, relying upon the auto-generated _runtimeconfig.json_ (basically just specifying the TFM). Could the issue possibly be related to the fact that it was sharing a Windows App Service Plan with two .NET Core 3.1 applications?

**Comment by adityamandaleeka** [comment]
This was a bug in App Service that's just been fixed. The fix will roll out in an upcoming release. Closing this issue.
