### ISSUE TITLE
Error when Copy and Paste  On VS2019 Editing a Razor Component, IDE Change  a localization variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27475]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error-when-Copy-and-Paste-On-VS2019-Edit/1220486)._

---
[severity:It's more difficult to complete my work]
I'm making a Blazor app. When i copy and paste a code fragment on a Razor component, the IDE separate  a localization variable and its make my app break down on running time 
For example i have this=>

```
<Row Margin="Margin.Is1">
                <Column ColumnSize="ColumnSize.Is3">
                    <Alert Color="Color.Primary" Visible="true">
                         @L["Account"]:
                    </Alert>
                </Column>
                <Column ColumnSize="ColumnSize.Is4">
                    <Alert Color="Color.Secondary" Visible="true" Style="font-weight:400">
                        @TotalCount
                    </Alert>
                </Column>
</Row>
```

When i paste a code before variable @TotalCount
Then Cohde changed to this:
```
<Row Margin="Margin.Is1">
                <Column ColumnSize="ColumnSize.Is3">
                    <Alert Color="Color.Primary" Visible="true">
                        @L ["Account"]:
                    </Alert>
                </Column>
                <Column ColumnSize="ColumnSize.Is4">
                    <Alert Color="Color.Secondary" Visible="true" Style="font-weight:400">
                        Total  @TotalCount
                    </Alert>
                </Column>
</Row>
```
This change from this   `@L["Account"];` to that `@L ["Account"];`
Its may afect many code lines.

---
#### Feedback Bot on 10/14/2020, 11:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
