### ISSUE TITLE
[Linux] Components unrecognized, can't rename

### ISSUE THREAD

**Issue by allisonchou** [dotnet/aspnetcore#27477]
Components seem to be unrecognized in Linux and cannot be renamed.
For example, in the screenshot below, the default SurveyPrompt component is not recognized.
The rename dialog will pop up but upon trying to commit the rename, the dialog box "No result. No result" pops up in the bottom right.
I tried this exact scenario Windows and everything seems to be working properly.

![surveyprompt](https://user-images.githubusercontent.com/16968319/97934570-f28b9d00-1d2a-11eb-9cdc-8a6061f0b061.png)

On SurveyPrompt rename:
![surveypromptrename](https://user-images.githubusercontent.com/16968319/97934775-82c9e200-1d2b-11eb-99e7-6881dedfbcfd.png)

**Comment by NTaylorMullen** [comment]
Validated this no longer repros.
