### ISSUE TITLE
Request and response logging

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27471]
Less verbose than Kestrel connection logging.

* Structured logging, headers, body, etc
* Options to filter headers/query string (sensitive data can be logged)

**Comment by JunTaoLuo** [comment]
Is this a duplicate of https://github.com/dotnet/aspnetcore/issues/3700?

**Comment by BrennanConroy** [comment]
Does look similar, @davidfowl

**Comment by davidfowl** [comment]
Yea, mine is 😄
