### ISSUE TITLE
Blazor web assembly supports the architecture of simplcommerce project

### ISSUE THREAD

**Issue by ghd258** [dotnet/aspnetcore#27483]
Blazor web assembly supports the architecture of [simplcommerce ](https://github.com/simplcommerce/SimplCommerce)project   
https://github.com/simplcommerce/SimplCommerce

Please open the source code [SimplCommerce](https://github.com/simplcommerce/SimplCommerce) of the open source project to view the detailed architecture scheme
![QQ图片20201103103535](https://user-images.githubusercontent.com/4811375/97944921-f669fe80-1dc0-11eb-8db2-31f1a0bfb587.png)

**Comment by javiercn** [comment]
@ghd258 thanks for contacting us.

We don't have enough details to understand what you areasking us to support. Can you tell us what specific blockers are you encountering with Blazor webassembly in this scenario that you would like us to consider solving?

**Comment by ghd258** [comment]
![Uploading QQ图片20201104081510.png…]()

**Comment by javiercn** [comment]
This is not something we plan to do in the near future, we recommend looking at community projects for this type of solutions. We already provide support in the box for some of these things like lazy loading of assemblies in blazor webassembly.

If there are specific features missing that would block an implementation of something like this, we would be happy to hear about it, but we don't plan to ship an opinionated way of building applications as part of the framework.
