### ISSUE TITLE
Blazor Server/Prerendering hangs if spamming F5

### ISSUE THREAD

**Issue by isc30** [dotnet/aspnetcore#27486]
When spamming multiple renders at the same time by simply pressing F5 multiple times in the browser, the server hangs for a long time.
Using latest rc2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you share more details about the app this repros with? Are you facing this behavior with the default BlazorServer app?

**Comment by isc30** [comment]
Hi, sometimes it even happens with the default app but no, it happens
consistently with an app that uses a bit of CPU/RAM during prerender (and
takes about 150ms to return the rendered page). It feels like when the app
does some work as part of the prerender phase, it kills the whole server if
spammed few times (I'm taking about 20 or so, not thousands)

>

**Comment by mkArtakMSFT** [comment]
Thanks @isc30. Will you be able to share a small project as a GitHub repository?
