### ISSUE TITLE
Bower Package Management Document errors on VS Reopen

### ISSUE THREAD

**Issue by donnie-msft** [dotnet/aspnetcore#27480]
### Describe the bug
Bower Package Management window throws an exception in VS when VS is reopened.

VS version: 16.8.0 Preview 3.1
Worked before? Worked in 15.x, Broken in at least 16.7.4 (not tested earlier)

**Note: On Preview VS, I did not have Bower package versions populated in the dropdown. On Experimental VS, I did have versions populated.**

### To Reproduce
1. Create a bower-incompatible project, such as .NET Standard 2.0, then Open NuGet Package Manager.

2. Find a package that recommends using the Bower Package Manager, eg, jQuery.
![image](https://user-images.githubusercontent.com/49205731/94961820-6d129400-04c3-11eb-8901-95187a320869.png)

3. Select the Bower link to open the Bower Package Manager window.

4. Close Visual Studio.

5. Reopen Visual Studio.

6. An error is shown
![image](https://user-images.githubusercontent.com/49205731/94962041-cf6b9480-04c3-11eb-9b86-36e821150cd3.png)

## Other suggested things
NuGet will be removing support for Bower package manager linkage: https://github.com/NuGet/Home/issues/6623

### Exceptions (if any)
(see screenshot)

### Further technical details
- ASP.NET Core version: N/A
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS version: 16.8.0 Preview 3.1

**Comment by javiercn** [comment]
@donnie-msft thanks for contacting us.

@mkArtakMSFT we'll have to react here eventually and update these packages. (I'm guessing)

**Comment by mkArtakMSFT** [comment]
@vijayrkn, @ChrisSfanos do you know who should handle this?

**Comment by ChrisSfanos** [comment]
Sorry, I don't think I can help here

**Comment by vijayrkn** [comment]
@jodavis
