### ISSUE TITLE
Blazor web assembly supports the use of razor class library  and  Areas

### ISSUE THREAD

**Issue by ghd258** [dotnet/aspnetcore#27482]
Blazor web assembly supports the use of razor class library  and  Areas

**Comment by javiercn** [comment]
@ghd258 thanks for contacting us.

Blazor Webassembly already supports class libraries.

As for the concept of areas, it is an MVC aspect that we don't plan to Blazor webassembly, if you are looking for areas as a way to organize your code, nothing should prevent you from following the same approach.

**Comment by ghd258** [comment]
When I refer to the class library, an error is reported, as shown in the figure
![Uploading QQ图片20201104081510.png…]()
