### ISSUE TITLE
Query parameter named "action" returns name of ControllerAction instead of url-parameter

### ISSUE THREAD

**Issue by DerGuru** [dotnet/aspnetcore#27495]
# SDK: .NET CORE 3.1
# Source Snippet 
``` csharp
[Route("~/My")]
public class MyController : ControllerBase
{
    [Route("")]
    [HttpGet]
    public IActionResult Execute(string action)
    {
        // evaluate "action"
    }
}
```
# HTTP-Request
https://host/My?action=FOO

# Expected behavior:
value of action equals "FOO"

# Actual behavior:
value of action eqals "Execute"

# Workaround
Request.Query["action"].First() equals "FOO"

**Comment by javiercn** [comment]
@DerGuru thanks for contacting us.

Values like `controller`, `action` and `page` are special in ASP.NET Core MVC and you should avoid their use. In this case, attribute routes get an "implicit" controller and action values.

**Comment by DerGuru** [comment]
Thanks for the quick reply. If this is intended, then I had wrong expectations.
