### ISSUE TITLE
The new scheme-less ControllerBase.SignIn() overloads always throw an InvalidOperationException

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/aspnetcore#27494]
New `SignIn` and `SignOut` overloads allowing to trigger sign-in and sign-out operations without specifying an explicit authentication scheme were introduced in https://github.com/dotnet/aspnetcore/pull/23604.

Sadly, `SignIn` doesn't work at all, as `SignInResult` wasn't updated to support null authentication schemes and fall back to the default one. Trying to call `SignIn(principal)` always results in an `InvalidOperationException` being thrown:

https://github.com/dotnet/aspnetcore/blob/b1dcacabec1aeacef72c9aa2909f1cb49993fa73/src/Mvc/Mvc.Core/src/SignInResult.cs#L88-L94

`SignOut` doesn't seem to be impacted.

/cc @Tratcher @HaoK

**Comment by kevinchalet** [comment]
@pranavkm I believe `area-mvc` would be more appropriate, as only MVC is affected (and not the underlying security APIs).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Let's try to address this in 5.0.1.
@HaoK assigned to you to get started on the PR.
