### ISSUE TITLE
Update spinner sometimes shows up side-by-side

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27509]
I'm not sure how to reproduce this consistently, but sometimes I see the update spinner show up side-by-side in the tab:

![image](https://user-images.githubusercontent.com/1874516/98054416-bc642100-1def-11eb-8e3f-e5d1ef9cd64c.png)

**Comment by danroth27** [comment]
@pranavkm @BillHiebert

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
