### ISSUE TITLE
Confused about binding enum type in 'RequestBody'

### ISSUE THREAD

**Issue by Ethan-oss-dot** [dotnet/aspnetcore#27512]
### Describe the bug
FromQueryAttribute enum parameters throw validation_error invalid value, but parameters with FromBodyAttribute do not.

### To Reproduce
I have a enum like this:
```
public enum Example
        {     
           one=1
        };
```
And my action like this:
```
 [HttpPost]
  public object ExampleAction(Example hello)
  { 
    return Ok();
  }
```

In my postman:

**1:send with querystring:**

When I send "?hello=1",successfully bind and return 200:

When Isend "?hello=2",as shown below:
![image](https://user-images.githubusercontent.com/68624043/98087598-4af1a480-1ebb-11eb-8c87-6889bae508e8.png)

**2:send with body:**

When I send like this:
![image](https://user-images.githubusercontent.com/68624043/98088652-ab351600-1ebc-11eb-85ed-72b710da6f48.png)
![image](https://user-images.githubusercontent.com/68624043/98088938-0ebf4380-1ebd-11eb-84ec-1713c97c179f.png)

My enum does not contain 2. Why is it successfully bound,Why does it not validate like in querystring?

### Further technical details
- ASP.NET Core 3.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is known and is tracked at https://github.com/dotnet/runtime/issues/42093
