### ISSUE TITLE
Blazor HotReload External App

### ISSUE THREAD

**Issue by chrdlx** [dotnet/aspnetcore#27517]
I've been working with Blazor and trying to push it in the company I work since the first Blazor Betas arrived, and I just cannot believe all the time I've wasted rebuilding the app for every little CSS or HTML change, 10 to 15 seconds (and increasing) for each change I want to preview, even with auto browser refresh (the current solution) is insane.

 A couple of days ago, given my frustration in this area, and because the "reload" times now are getting unviable, searching the web I found https://www.livesharp.net . I don't know if Microsoft is aware of it,  but please develop something like this ASAP,  an external tool like this so we don't have to wait one year for NET 6.
 Sadly two months ago this was the main reason why the team went for a JS framework for the current project instead of Blazor, even with the love we have for C#,  the waiting is just too much.

Regards

**Comment by javiercn** [comment]
@chrdlx thanks for contacting us.

Improving the developer inner loop is something we are already tracking [here](https://github.com/dotnet/aspnetcore/issues/22566)
