### ISSUE TITLE
SignelR Client for .Net Framework 4.5.2

### ISSUE THREAD

**Issue by SPEMoorthy** [dotnet/aspnetcore#27516]
Our Server Web API developed with ASP .NET Core 3.1 Version using Microsoft.AspNetCore.SignalR Package.

Client .Net Fraework 4.5.2 WPF Application. using Microsoft.AspNet.SignalR.Client;

But both are not compatible with each other. Getting 

StatusCode: 405, ReasonPhrase: 'Method Not Allowed', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Date: Wed, 04 Nov 2020 12:02:30 GMT
  Server: Kestrel
  Content-Length: 0
  Content-Type: text/plain
}

What can we do? Any Supported Clent for WPF Application?

Thanks & Regars,
Easwar

**Comment by BrennanConroy** [comment]
ASP.NET SignalR is not compatible with ASP.NET Core SignalR like you've noticed.

The [ASP.NET Core SignalR client](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/) targets [netstandard2.0 which should run on .NET Framework 4.6.1](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md#platform-support)
