### ISSUE TITLE
asp.net core SignalR 3.1.9 incompatible with System.Text.Json 5

### ISSUE THREAD

**Issue by ChristophHornung** [dotnet/aspnetcore#27519]
In `System.Text.Json` the API will change in version 5. Especially the `type` parameter in `JsonSerializer.Serialize`. The function now throws an exception when `null` is passed. (see this [issue](https://github.com/dotnet/runtime/issues/35422))

This is fixed in the latest SignalR 5 code (see e.g. the null check before this call [here](https://github.com/dotnet/aspnetcore/blob/24b34d720366af99b20d1736b96a9ab184d37c31/src/SignalR/common/Protocols.Json/src/Protocol/JsonHubProtocol.cs#L521)) but since `System.Text.Json` is a very common dependency once updated SignalR 3.1.9 will no longer work.

Will there be a new 3.x release to fix this problem? I already encountered that problem when testing an update to the latest EF 5 RC version.

**Comment by BrennanConroy** [comment]
This issue is only happening in a client application right? Where you kept the SignalR client as 3.1.x and moved other dependencies to 5.0?

**Comment by ChristophHornung** [comment]
No, this is on the server side. The exception occurs inside the method I linked (`JsonHubProtocol.WriteCompletionMessage`).

**Comment by BrennanConroy** [comment]
Yeah I know where the issue is. How are you getting this in a server application? Are you targeting netcoreapp3.1 and pulling in 5.0 dependencies?

**Comment by ChristophHornung** [comment]
I am targeting netcoreapp3.1 in an asp.net core project and updated Entity Framework Core to version 5 RC2, this in turn pulls in the latest System.Text.Json as a dependent package.

**Comment by BrennanConroy** [comment]
Ok thanks, so two different scenarios are broken with the System.Text.Json changes. That'll help us prioritize.

Side-note: Why aren't you targeting net5.0 if you're pulling in 5.0 packages?

**Comment by ChristophHornung** [comment]
I am currently testing the upgrade path for several parts of our code base towards net5.0, this change was part of testing whether a list of libraries we use can be upgraded without a problem. (Some of our services run on azure, and since we are not deploying as self-contained at the moment I am not sure I can easily switch over immediately). 

I am pretty confident though that there will still remain a lot of signalR 3.x services running that will probably at some point in the future have implicit references to System.Text.Json in the latest version. 

Since EF core 5 runs on .net core 3.1 this will probably happen very quickly, since we want to use a few of the new features without a full .net5 upgrade.

**Comment by jkotalik** [comment]
Looks like we need to make a fix to 3.1 in SignalR to not pass null to the JsonSerializerTo/From.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/27534

**Comment by ChristophHornung** [comment]
@BrennanConroy Hey Brennan, just wanted to say thanks for the quick replies and the quick fix. Your work is appreciated!
