### ISSUE TITLE
Review the list of obsolete types and see whether we can remove any of these in .NET 6

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27529]
For .NET 6, we'd like to evaluate the APIs marked as obsolete and remove them if necessary. There's ~130 APIs marked as obsolete that are split up based on project area in the table below. The goal is to have these APIs removed by preview1 so we have time to get feedback on our decision early on in the release.

**What to do**
- If it should be removed
  - Remove it
  - Update any samples/tests that use the obsolete API.
- If it should not be removed:
  - Add an inline comment explaining why and provide a timeline for removal if possible
  - Ensure that the Obsolete description provides information about alternative APIs or guidelines on what the user should do otherwise.
  - Provide an aka.ms link to the deprecation announcement.

**Who is doing it**
| Area | Assigned | Done? |
|--|--|--|
| Azure AD | @HaoK, @JunTaoLuo, @javiercn | https://github.com/dotnet/aspnetcore/pull/27955 |
| Hosting | @Tratcher, @halter73 | https://github.com/dotnet/aspnetcore/issues/27529#issuecomment-748288221 |
| Http | @Tratcher, @jkotalik , @halter73 | https://github.com/dotnet/aspnetcore/pull/28890 |
| Middleware | @Tratcher, @HaoK, @halter73 | https://github.com/dotnet/aspnetcore/pull/28893 |
| MVC | @pranavkm, @javiercn, @captainsafia | https://github.com/dotnet/aspnetcore/pull/28337 |
| Razor | @ajaybhargavb, @captainsafia | https://github.com/dotnet/aspnetcore/pull/28706 | 
| Servers | @jkotalik, @halter73 | #29275 |
|SignalR | @BrennanConroy | https://github.com/dotnet/aspnetcore/pull/28100 |

**Things to keep in mind**
@halter73 and @captainsafia took a look at all the APIs and made the following list of things to consider when evaluating whether or not an `Obsolete`d API should be removed.

* Outside of redundancy, is there another harm to having the API around? For example, it is not performant or not supported by other parts of the ecosystem.
* What's the maintenance cost of keeping the API around? This includes things like the number of issues reported by users, whether there's a lot of flaky tests associated with the API, etc.
* Does the `Obsolete`d API no longer work?
* How common is the API that is being obsoleted? Is it likely a new user will inadvertently use it and run into issues?
* Is it actually a shipped API?
* When was the API obsoleted? If it was obsoleted in .NET 5, keep it around to make upgrading between LTS releases, from 3.1 to 6, easier for devs.
* Is this API commonly used by other packages?

**Comment by Pilchie** [comment]
Also to keep in mind - if the API was first marked `Obsolete` in .NET 5.0, we might consider keeping it for .NET 6 to make it easier for people to upgrade from LTS to LTS (.NET Core 3.1 -> .NET 6.0).

**Comment by javiercn** [comment]
We should consider adding aka.ms links to the obsolete message that point to a landing doc (the announcement?) and that suggest alternatives.

**Comment by dougbu** [comment]
We may also want to use the new `[Obsolete]` `DiagnosticId` property. The dotnet/runtime team is using this extensively. See https://github.com/dotnet/runtime/blob/329f0dbfa3a164ee2e3bf9f75b7641165995c799/src/libraries/Common/src/System/Obsoletions.cs and e.g. https://github.com/dotnet/runtime/blob/329f0dbfa3a164ee2e3bf9f75b7641165995c799/src/libraries/System.Security.Permissions/src/System/Security/SecurityManager.cs#L10

**Comment by captainsafia** [comment]
@dougbu Nice suggestion. I think that's something we should do that once we've gathered info about all the obsoleted APIs. I've updated the issue comment to reflect adding aka.ms links when necessary.

**Comment by Tratcher** [comment]
Obsolete Hosting types:
- EnvironmentName: Constants that have been moved to Extensions but otherwise unchanged. Leave it.
- IApplicationLifetime: An interface that has been moved to Extensions with a new name but otherwise unchanged. Leave it.
- IHostingEnvironment: An interface that has been moved to Extensions with a new name but otherwise unchanged. Leave it.
All include comments about their recommended replacements. I don't think any additional action is needed here. I'll mark it as done.

**Comment by halter73** [comment]
@mkArtakMSFT @captainsafia Can we close this now?

**Comment by captainsafia** [comment]
This PR is still open: https://github.com/dotnet/aspnetcore/pull/27955

But it's being tracked so we can close this.

We may want to move https://github.com/dotnet/aspnetcore/issues/27529#issuecomment-729878872 out into a separate issue as well.

But yes, this work is mostly done for preview1. Thanks everyone for chipping in!

**Comment by BrennanConroy** [comment]
FYI, created https://github.com/aspnet/Announcements/issues/450 for all PRs linked in the first comment, except for the unmerged AzureAD ones.
