### ISSUE TITLE
scss files removed from watch (hot reload)

### ISSUE THREAD

**Issue by flexoskar** [dotnet/aspnetcore#27523]
### Describe the bug
*.scss files are removed from watch automatically. Same problem as #9922 but *.scss instead of *.razor. 

### To Reproduce
1. Create Blazor wasm project.
2. Add new page StyleCss.razor.
3. Add StyleCss.razor.scss.
4. Do some changes, sometimes immediately, sometimes after a while StyleCss.razor.scss is removed from watch.

<pre><code>&lt;Project&gt;
  ...
  &lt;ItemGroup&gt;
    &lt;Watch Remove="StylingCss.razor.scss" /&gt;
  &lt;/ItemGroup&gt;
&lt;/Project&gt; 
</code></pre>

### Expected behaviour
*.scss files shouldnt be removed from watch. 

### Further technical details
Visual Studio Version 16.8.0 Preview 6.0.
.NET 5.0 RC 2

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
