### ISSUE TITLE
Add a UI indication for render tree issues

### ISSUE THREAD

**Issue by cjb110** [dotnet/aspnetcore#27521]
### Is your feature request related to a problem? Please describe.
I've built a simple search and display Blazor WASM site, and just starting on a more complex site, and in the early process of creating skeleton components, some of the data objects might be null, and the only information you get is that something somewhere was null, and maybe the name of the component .cs file.  You then get nothing displayed on screen, and you can't 'step' through either.
This is hard to debug, and slows down the process.

### Describe the solution you'd like
3 possibilities:

1. Include more information in the console message about where in the render tree (if not the name of the actual fail site, maybe the previous item that was successful?)
2. Allow the definition of Blazor 'null' fragment (that is maybe just pure HTML?) and then the rendering could use this when hits a null. So at least during debugging you get something rendered and better feedback.
3. Improve the speed of the Watch, and better integrate that into VS.  Maybe if the loop of running and failing was faster, it would be less of a hassle, currently watch takes an age to kick in and then recompile etc.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We will try to improve the experience in .NET 6 timeframe doing two things:
1. We will provide tools to help preventing these issues when enabling nullable annotation-based warnings
2. We will try to improve the exception message by pointing to the razor source where possible.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
