### ISSUE TITLE
More API docs

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#27538]
Looks like there are more API docs that need to be added for the following:

- Azure
  - [x] Microsoft.AspNetCore.AzureAppServicesIntegration @BrennanConroy 
- Caching
  - [x] Microsoft.Extensions.Caching.StackExchangeRedis @juntaoluo
  - [x] Microsoft.Extensions.Caching.SqlServer @juntaoluo
- DataProtection:
  - [x] Microsoft.AspNetCore.DataProtection @pranavkm
- Features
  - [x] Microsoft.AspNetCore.JsonPatch @SteveSandersonMS 
- Http
  - [x] Microsoft.Net.Http.Headers @pranavkm
  - [x] Microsoft.AspNetCore.Http @pranavkm
  - [x] Microsoft.AspNetCore.Http.Extensions @pranavkm
  - [x] Microsoft.AspNetCore.Http.Features @pranavkm
  - [x] Microsoft.AspNetCore.Owin @JamesNK 
  - [x] Microsoft.AspNetCore.WebUtilities @pranavkm
- JSInterop
  - [x] Microsoft.JSInterop @pranavkm
- ObjectPool
  - [x] Microsoft.Extensions.ObjectPool @pranavkm
- Razor
  - [x] Microsoft.AspNetCore.Razor @TanayParikh 
- Security
  - [x] Microsoft.AspNetCore.Authentication.Twitter @HaoK 
- Server
  - [x] Microsoft.AspNetCore.Connections.Abstractions @halter73 
  - [x] Microsoft.AspNetCore.Server.Kestrel.Core @sebastienros 
  - [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic @sebastienros 
  - [x] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets @sebastienros 
- SignalR
  - [x] Microsoft.AspNetCore.SignalR.Specification.Tests @BrennanConroy 
- WebEncoders
  - [x] Microsoft.Extensions.WebEncoders @JunTaoLuo

**Comment by JunTaoLuo** [comment]
We'll need to divide this up fyi @pranavkm

**Comment by dougbu** [comment]
@JunTaoLuo please check if dotnet/aspnetcore#27285 already lists the problem areas you mentioned above. If not, please mention this issue in the description.

**Comment by JunTaoLuo** [comment]
Hey folks. I took a look at the rest of the projects missing API docs and divided up the work. I've tried to assign folks with areas they are familiar with but let me know if they need to be reassigned.

**Comment by sebastienros** [comment]
I checked the remaining boxes to be ticked and couldn't find any namespace without doc. Can someone validate?

**Comment by BrennanConroy** [comment]
We want to remove most of the CS1591 warning skips, there are still a few left (Kestrel has some)
https://github.com/dotnet/aspnetcore/search?q=CS1591

**Comment by wtgodbe** [comment]
@SteveSandersonMS @TanayParikh @pranavkm @halter73 looks like there are still some missing comments for JsonPatch, Razor, and Connections.Abstractions. I removed the other `CS1591`s in https://github.com/dotnet/aspnetcore/pull/40104

**Comment by wtgodbe** [comment]
Actually all of the CS1591's are still active, there are a bunch of doc comments to add in Kestrel too.
