### ISSUE TITLE
Flaky test "InjectedStartup_DefaultApplicationNameIsEntryAssembly"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#27557]
> System.InvalidOperationException : Timeout while waiting for output from host process.\n---- System.TimeoutException : The operation at /_/src/Hosting/test/FunctionalTests/WebHostBuilderTests.cs:59 timed out after reaching the limit of 60000ms.

>    at Microsoft.AspNetCore.Hosting.FunctionalTests.WebHostBuilderTests.InjectedStartup_DefaultApplicationNameIsEntryAssembly(TestVariant variant) in /_/src/Hosting/test/FunctionalTests/WebHostBuilderTests.cs:line 63
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 60
   at Microsoft.AspNetCore.Hosting.FunctionalTests.WebHostBuilderTests.InjectedStartup_DefaultApplicationNameIsEntryAssembly(TestVariant variant) in /_/src/Hosting/test/FunctionalTests/WebHostBuilderTests.cs:line 59

CC @BrennanConroy @JamesNK 

https://dev.azure.com/dnceng/public/_build/results?buildId=875514&view=ms.vss-test-web.build-test-results-tab&runId=28007986&resultId=100000&paneView=debug

**Comment by JamesNK** [comment]
https://github.com/dotnet/aspnetcore/pull/25298

> All the hosting tests in functional tests project are quarantined. I wonder if we just accept that these tests can be prone to transient failures, and place them in a retry loop, i.e. the test fails if the hosting logic fails twice.

I still think that is the fix here.

**Comment by BrennanConroy** [comment]
>  I wonder if we just accept that these tests can be prone to transient failures, and place them in a retry loop

I can't accept that without a reasonable explanation as to why they are flaky. From my quick glance at this I can come up with one reason this can be flaky, the `OutputDataReceived` event is hooked up to the process after it has started which can make it racy to capture the output that will set the tcs.

https://github.com/dotnet/aspnetcore/blob/584e06fcedc7f26f59d19305b68207ec982bd11a/src/Hosting/test/FunctionalTests/WebHostBuilderTests.cs#L48

**Comment by JamesNK** [comment]
Good catch. That might be the reason.
