### ISSUE TITLE
Flaky test "CanSetCultureAndParseCultureSensitiveNumbersAndDates"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#27556]
Test failed with:

> OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: 9000.42\r\nActual:   0\r\n   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\61e89733d2e44633997c2f9f0fdaad79.png'\r\nEncountered browser errors\r\n[2020-11-04T15:16:31Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:31.270Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52619/subdir/_blazor'."\r\n[2020-11-04T15:16:31Z] [Info] http://127.0.0.1:52619/subdir 44:16 "Blazor server-side"\r\n[2020-11-04T15:16:31Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:31.329Z] Information: WebSocket connected to ws://127.0.0.1:52619/subdir/_blazor?id=EFULSsvuKmZwAK_ylZ3WGA."\r\n[2020-11-04T15:16:32Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:32.569Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52619/subdir/_blazor'."\r\n[2020-11-04T15:16:32Z] [Info] http://127.0.0.1:52619/subdir 44:16 "Blazor server-side"\r\n[2020-11-04T15:16:32Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:32.617Z] Information: WebSocket connected to ws://127.0.0.1:52619/subdir/_blazor?id=WPqfE5iY2g-72od43ifcRQ."\r\n[2020-11-04T15:16:33Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:33.521Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52619/subdir/_blazor'."\r\n[2020-11-04T15:16:33Z] [Info] http://127.0.0.1:52619/subdir 44:16 "Blazor server-side"\r\n[2020-11-04T15:16:33Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:33.528Z] Information: WebSocket connected to ws://127.0.0.1:52619/subdir/_blazor?id=0QMqNVm0DQ3gSaFKuxnqqg."\r\n[2020-11-04T15:16:33Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:33.870Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52619/subdir/_blazor'."\r\n[2020-11-04T15:16:33Z] [Info] http://127.0.0.1:52619/subdir 44:16 "Blazor server-side"\r\n[2020-11-04T15:16:33Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:33.880Z] Information: WebSocket connected to ws://127.0.0.1:52619/subdir/_blazor?id=4HKoHp3XX2ULH6vAULVxng."\r\n[2020-11-04T15:16:34Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:34.643Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52619/subdir/_blazor'."\r\n[2020-11-04T15:16:34Z] [Info] http://127.0.0.1:52619/subdir 44:16 "Blazor server-side"\r\n[2020-11-04T15:16:34Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:34.655Z] Information: WebSocket connected to ws://127.0.0.1:52619/subdir/_blazor?id=M0bG7WGD9aFhYYH4kadO1w."\r\n[2020-11-04T15:16:35Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:35.132Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52619/subdir/_blazor'."\r\n[2020-11-04T15:16:35Z] [Info] http://127.0.0.1:52619/subdir 44:16 "Blazor server-side"\r\n[2020-11-04T15:16:35Z] [Info] http://127.0.0.1:52619/subdir/_framework/blazor.server.js 0:5679 "[2020-11-04T15:16:35.169Z] Information: WebSocket connected to ws://127.0.0.1:52619/subdir/_blazor?id=CZwjVOQ5fuEouiuo33uHJw."Page content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n    <link href="Components.TestServer.styles.css" rel="stylesheet">\r\n</head>\r\n<body>\r\n    <root><div id="test-selector">\r\n    Select test:\r\n    <select id="test-selector-select"><option value="none">Choose...\r\n        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component\r\n        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases\r\n        <option value="BasicTestApp.BindCasesComponent">bind cases\r\n        <option value="BasicTestApp.ComponentRefComponent">Component ref component\r\n        <option value="BasicTestApp.ConfigurationComponent">Configuration\r\n        <option value="BasicTestApp.CounterComponent">Counter\r\n        <option value="BasicTestApp.CounterComponentWrapper">Counter wrapped in parent\r\n        <option value="BasicTestApp.DataDashComponent">data-* attribute rendering\r\n        <option value="BasicTestApp.DuplicateAttributesComponent">Duplicate attributes\r\n        <option value="BasicTestApp.ElementRefComponent">Element ref component\r\n        <option value="BasicTestApp.EventBubblingComponent">Event bubbling\r\n        <option value="BasicTestApp.EventCasesComponent">Event cases\r\n        <option value="BasicTestApp.EventDuringBatchRendering">Event during batch rendering\r\n        <option value="BasicTestApp.ExternalContentPackage">External content package\r\n        <option value="BasicTestApp.FormsTest.NotifyPropertyChangedValidationComponent">INotifyPropertyChanged validation\r\n        <option value="BasicTestApp.FormsTest.SimpleValidationComponentUsingExperimentalValidator">Simple validation using experimental validator\r\n        <option value="BasicTestApp.FormsTest.TypicalValidationComponentUsingExperimentalValidator">Typical validation using experimental validator\r\n        <option value="BasicTestApp.NavigateOnSubmit">Navigate to submit\r\n        <option value="BasicTestApp.GracefulTermination">Graceful Termination\r\n        <option value="BasicTestApp.HtmlBlockChildContent">ChildContent HTML Block\r\n        <option value="BasicTestApp.HtmlMixedChildContent">ChildContent Mixed Block\r\n        <option value="BasicTestApp.HttpClientTest.CookieCounterComponent">HttpClient cookies\r\n        <option value="BasicTestApp.InputEventComponent">Input events\r\n        <option value="BasicTestApp.InteropOnInitializationComponent">Interop on initialization\r\n        <option value="BasicTestApp.KeyCasesComponent">Key cases\r\n        <option value="BasicTestApp.LaggyTypingComponent">Laggy typing\r\n        <option value="BasicTestApp.LocalizedText">Localized Text\r\n        <option value="BasicTestApp.LoggingComponent">Logging\r\n        <option value="BasicTestApp.MarkupBlockComponent">Markup blocks\r\n        <option value="BasicTestApp.MovingCheckboxesComponent">Moving checkboxes diff case\r\n        <option value="BasicTestApp.NavigationFailureComponent">Navigation failure\r\n        <option value="BasicTestApp.PropertiesChangedHandlerParent">Parent component that changes parameters on child\r\n        <option value="Components.TestServer.ProtectedBrowserStorageInjectionComponent, Components.TestServer, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60">Protected browser storage injection\r\n        <option value="BasicTestApp.Reconnection.ReconnectionComponent">Reconnection server-side blazor\r\n        <option value="BasicTestApp.ReliabilityComponent">Server reliability component\r\n        <option value="BasicTestApp.RenderAttributesBeforeConnectedCallback">Render attributes before ConnectedCallback\r\n        <option value="BasicTestApp.RouterTest.NavigationManagerComponent">NavigationManager Test\r\n        <option value="BasicTestApp.RouterTest.TestRouterWithOnNavigate">Router with OnNavigate\r\n        <option value="BasicTestApp.RouterTest.TestRouterWithAdditionalAssembly">Router with additional assembly\r\n        <option value="BasicTestApp.SignalRClientComponent">SignalR client\r\n        <option value="BasicTestApp.SvgComponent">SVG\r\n        <option value="BasicTestApp.TextOnlyComponent">Plain text\r\n        <option value="BasicTestApp.TouchEventComponent">Touch events\r\n        <option value="BasicTestApp.VirtualizationDataChanges">Virtualization data changes

>    at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETests.Tests.GlobalizationTest`1.CanSetCultureAndParseCultureSensitiveNumbersAndDates(String culture) in /_/src/Components/test/E2ETest/Tests/GlobalizationTest.cs:line 52
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerGlobalizationTest.CanSetCultureAndParseCultureSensitiveNumbersAndDates(String culture) in /_/src/Components/test/E2ETest/ServerExecutionTests/ServerGlobalizationTest.cs:line 42
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109

https://dev.azure.com/dnceng/public/_build/results?buildId=875514&view=ms.vss-test-web.build-test-results-tab&runId=28008146&resultId=100002&paneView=debug

CC @HaoK @pranavkm

**Comment by HaoK** [comment]
FYI https://github.com/dotnet/aspnetcore/issues/27155 is a very similar issue (WithInputFields variant), maybe worth tracking as one issue

**Comment by wtgodbe** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/27155
