### ISSUE TITLE
Flaky Test "UseSpa_KillsRds_WhenAppIsStopped"

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#27552]
Test failed with:

> npm ERR! code EPIPE\r\nnpm ERR! syscall write\r\nnpm ERR! errno EPIPE\r\n\r\nExpected: True\r\nActual:   False

>    at Microsoft.AspNetCore.SpaServices.Extensions.Tests.SpaServicesExtensionsTests.AssertNoErrors() in /_/src/Middleware/SpaServices.Extensions/test/SpaServicesExtensionsTests.cs:line 162
   at Microsoft.AspNetCore.SpaServices.Extensions.Tests.SpaServicesExtensionsTests.Assert_NpmKilled_WhenAppIsStopped(IHostApplicationLifetime applicationLifetime, NpmStartedDiagnosticListener listener) in /_/src/Middleware/SpaServices.Extensions/test/SpaServicesExtensionsTests.cs:line 97
   at Microsoft.AspNetCore.SpaServices.Extensions.Tests.SpaServicesExtensionsTests.UseSpa_KillsRds_WhenAppIsStopped() in /_/src/Middleware/SpaServices.Extensions/test/SpaServicesExtensionsTests.cs:line 57
--- End of stack trace from previous location ---

https://github.com/dotnet/aspnetcore/blob/db3d23b3af6c2ade6635faac35cbaff4a94694c1/src/Middleware/SpaServices.Extensions/test/SpaServicesExtensionsTests.cs#L42

CC @AndriySvyryd @ryanbrandenburg

**Comment by wtgodbe** [comment]
Failed in this build: https://dev.azure.com/dnceng/public/_build/results?buildId=876289&view=results

**Comment by AndriySvyryd** [comment]
https://github.com/marcbachmann/node-html-pdf/issues/35#issuecomment-285686477 suggests this can happen if there's an npm module built for a different architecture.

**Comment by HaoK** [comment]
@dotnet/aspnet-build can you guys help me find where the quarantined test results for the spa services extensions are?  I'm looking at https://dev.azure.com/dnceng/public/_build/results?buildId=938618&view=logs&j=6d5af08c-e114-5ffe-77df-bfb882f83762&t=1236264d-1784-5615-742c-dbfd7ef2168f for example, and I don't see the run quarantined tests try to run these tests, and I don't see it in any of the analytics.  Am I just looking in the wrong place?  This test project is currently not running under helix, so I assumed I would see it in the windows test job for the quarantined-pr runs?

**Comment by dougbu** [comment]
I found it by clearing the Outcome filter in the Test tab and choosing `Microsoft.AspNetCore.SpaServices.Extensions.Tests.dll` as the "Test file".
![image](https://user-images.githubusercontent.com/6431421/103684286-34f67380-4f40-11eb-850b-b403cc767bb3.png)

**Comment by dougbu** [comment]
I suspect the number of tests we have is too large to reliably search for the test method when the filters are disabled.

**Comment by HaoK** [comment]
Ah that was it, thanks @dougbu!
