### ISSUE TITLE
Add interactive experience for `dotnet new`

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27554]
## Summary

1-2 sentences. Say what this is about.

## Motivation and goals

1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by Pilchie** [comment]
Should we move this to the templating repo?

**Comment by captainsafia** [comment]
@Pilchie Seems sensible. We should update the issue text to summarize the discussions we've had in this area. I can update the text later this week and transfer.

**Comment by pranavkm** [comment]
I'm going to close this. We haven't really come up with substantive ideas on how to approach this, so it feels pointless to throw this over the wall to the templating team.
