### ISSUE TITLE
Add read callback function in new Socket.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#27566]
I am using SocketConnectionFactory which in Kestrel. I don't know how to read data after creating a Socket. I've been looking at the source code for a long time, and I haven't made no progress. Who can provide a simple and efficient way to read data or protocols?

```C#

public static async void RunSocket()
{
    var endpoit = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 8989);
    var factory = new SocketConnectionFactory(new SocketTransportOptions());
    var connection =  factory .ConnectAsync(endpoit).Result;
    ReadData(connection);
    Send(connection);
}

public static async void ReadData(ConnectionContext  connection)
{
     //while(true) ?
     //how to code ??
}

public static async void Send(ConnectionContext connection)
{
     while (true)
     {
           var temp = Console.ReadLine();
           if (temp != null)
           {
               var buffer = Encoding.UTF8.GetBytes(temp);
               await connection.Transport.Output.WriteAsync(buffer);
           }
     }
 }
```

Kestrel is so complex that I have to embed code in the [ProcessReceives](https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Transport.Sockets/src/Internal/SocketConnection.cs#L234) method.   

```C#
......

var result = await flushTask;
if (paused)
{
     //_trace.ConnectionResume(ConnectionId);
}
// ↓ I added code like this : 
_receiver._awaitableEventArgs.ReadBuffer(buffer);

``` 

But this is obviously wrong. What is the best practice?

**Comment by BrennanConroy** [comment]
Have you tried using
`connection.Transport.Input.ReadAsync(...);`?

Nit: please don't use `async void` if you can avoid it.

**Comment by NMSAzulX** [comment]
@BrennanConroy Thanks! It works! It's amazing because I've tried the same way before and it doesn't work. Maybe it's the problem with my testing code. So sorry.
```C#
 var result = await connection.Transport.Input.ReadAsync();
.....
connection.Transport.Input.AdvanceTo....
```

**Comment by NMSAzulX** [comment]
Will both. Net 5 and. Net 6 use SocketConnectionFactory? I am looking forward to this feature, which allows me to complete most of the third-party network drivers. I'm afraid I've found an excellent SocketClient solution. In fact, I still lack a pooling feature, and I will try to continue to challenge HttpClientPool, even though it is super complex.

**Comment by BrennanConroy** [comment]
SocketConnectionFactory is internal currently. We may be making it public in 6.0.
