### ISSUE TITLE
About DataAnnotation doesn't create something to juqery-vaildate.js to check field

### ISSUE THREAD

**Issue by go1312223** [dotnet/aspnetcore#27567]
### Is your feature request related to a problem? Please describe.
I use dataAnnotation to do web in mvc, I am trying to let textbox to use jquery-vaildate.js to check it is digit, but dotnet doesn't create "val_number" Field in html source code, and old dotframework can create this autoly. I think it maybe you miss this function in source code? 
I want to check this situation, so I ask it. If you can, please you answer it in your free time.Thank you very much!

### Describe the solution you'd like
I think it will create a new tag (like e.g:[digit]) in dataAnnotation, then can use this to decide input is digit.

### Additional context
view:

< div class="form-group">
< label class="form-label" asp-for="Seq"></label>
< input type="text" class="form-control col-md-3 text-right" asp-for="Seq">
<  span class="form-tex- text-danger" asp-validation-for="Seq"></span>
</ div>

model:
 [Display(Name = "Seq")]
 public int Seq { get; set; }

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You're right, there is no such behavior in ASP.NET Core to generate the `val_number` (or similar) field you're referring to.
If you let the system determine the data type for you, you may get a more appropriate input element with an equivalent behavior.
Consider changing element to not use `type` attribute as follows:
```html
<input class="form-control col-md-3 text-right" asp-for="Seq">
```

**Comment by go1312223** [comment]
Thank your answer!
so, if I don't have type, it will according seq is int to change input to number.
And there is not digit tag in NET Core.It is deliberately, right?
