### ISSUE TITLE
Update CONTRIBUTING.md for project

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#27562]
Update [CONTRIBUTING.md](http://contributing.md) docs to explain our CI process, how to address common feedback from the CI, and how we review PRs.

**Comment by MCCshreyas** [comment]
Hi @captainsafia, I am also thinking to update BuildFromSource.md to get it more consistent like others. See workflow guide at other repositories. What I think is like they are more verbose and also at runtime repo they are having separate instruction on building various part of repo. 
runtime - https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md
Windows form - https://github.com/dotnet/winforms/blob/master/docs/developer-guide.md

**Comment by captainsafia** [comment]
> What I think is like they are more verbose and also at runtime repo they are having separate instruction on building various part of repo.

We are tackling this work as part of #27561.

> I am also thinking to update BuildFromSource.md to get it more consistent like others. 

We did some improvements on the BuildFromSource.md doc a while back. What kind of things should we copy from the runtime repo?

For now, this issue is focused on updating the CONTRIBUTING.md to address parts of the contribution process that aren't directly related to the build. If there's more improvements we can make in BuildFromSource.md we can track those in a different issue.

**Comment by javiercn** [comment]
@captainsafia is there anything left here you think we should consider?

**Comment by captainsafia** [comment]
I'd like to refresh the changes introduced in https://github.com/dotnet/aspnetcore/pull/37362.

I think it would be helpful to bring up the PR during the next DoI meeting. I know @dougbu had some concerns about information loss but I wanted to avoid the doc being riddled with info that was too advanced.

**Comment by mkArtakMSFT** [comment]
@captainsafia what is left to be done here, if anything? I think we should close it, if there is nothing specific, as I know you had done a lot of work a while ago on improving our docs.

**Comment by captainsafia** [comment]
I think we can go ahead and close this.
