### ISSUE TITLE
[Discussion] Changes to Nullable Reference Type Annotations in .NET 6.0

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#27564]
## Changes to Nullable Reference Type Annotations in .NET 6.0

_**This issue represents a work-in-progress. All breaking changes to nullability annotations will be aggregated into this issue throughout the course of .NET 6.0.**_

Starting in .NET 5.0, we have been applying nullability annotations to parts of ASP.NET Core. From the outset of this effort, [we anticipated that mistakes would be made](https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/api-guidelines/nullability.md#breaking-change-guidance) in these annotations and fixes would need to be made. In .NET 6.0, we are updating some annotations that have been previously applied. Some of these changes are considered source breaking changes because it leads to the APIs being incompatible or more restrictive, or could result in build-time warnings when used in projects that have nullable reference types enabled.

### Version introduced

.NET 6.0

### Old behavior

The affected APIs had incorrect nullable reference type annotations and build warnings were either absent or incorrect.

### New behavior

New build warnings will be produced and incorrect build warnings will no longer be produced for the affected APIs.

### Reason for change

Through feedback and further testing, the nullable annotations for the affected APIs were determined to be inaccurate. The updated annotations now correctly represent the nullability contracts for the APIs.

### Recommended action

Update code calling these APIs to reflect the revised nullability contracts.
### Category

ASP.NET

### Affected APIs

* [ParameterView.FromDictionary(IDictionary<string, object?>](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.components.parameterview.fromdictionary)
* [Renderer.DispatchEventAsync(UInt64, EventFieldInfo?, EventArgs))](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.components.rendertree.renderer.dispatcheventasync)
* [AuthenticationSchemeOptions.ForwardDefaultSelector](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.authenticationschemeoptions.forwarddefaultselector)

**Comment by slang25** [comment]
This is a bit of a tangent, but is there any intention to change the default for the .NET SDK in version 6 or further to enable nullable references for new projects, and have `enabled` be implicit?

**Comment by pranavkm** [comment]
@slang25 ASP.NET Core is planning to do it as part of 6.0. https://github.com/dotnet/aspnetcore/issues/27389 has an overview of the planned work here. https://github.com/dotnet/sdk/issues/14272 tracks doing it across other .NET 6 project templates.
