### ISSUE TITLE
Injection of components issue or new feature or other?

### ISSUE THREAD

**Issue by KevinValmo** [dotnet/aspnetcore#27582]
I don't know if this is an issue or a possible new feature.

However, I tried to inject blazor component in different ways via asp.net core DI.
I tried with interfaces and with BaseClasses but doesn't work.
In the program.cs i added the injection.

Here there is a repo:

[github repo](https://github.com/KevinValmo/Issues-InheritedComponent)

![image](https://user-images.githubusercontent.com/55260200/98393964-5cbd7e00-205a-11eb-8d9f-14aea53deb9b.png)

**Comment by javiercn** [comment]
@KevinValmo thanks for contacting us.

You can't inject components that way. The framework is responsible for managing the component lifecycle and is responsible for their creation and deletion. The best you can do is get a component reference to a child component you are rendering in markup. However, that's only guaranteed to be up to date within `OnAfterRenderAsync`.

**Comment by KevinValmo** [comment]
@javiercn
Reading around, times ago, I found that we can use the interface `IComponentActivator` to create an instance of a component. In this way we can set the correct type in a custom activator class.

However I have not tried yet.
Here the reference were you can find a possible implementation: #18088

Is there any problem with the implementation I mentioned?
