### ISSUE TITLE
Intellisense is so broken it's a hinderance

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27588]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Intellisense-is-so-broken-its-a-hindera/1239727?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio]
I constantly have to restart my project because Intellisense isn't working.  In my errors, I get critical errors for razor components but when I compile they run fine.  When I restart my Visual Studio, those errors go away and new ones pop up.  In some cases there may be no errors at all.

The VS preview is so horrendously broken and I deeply regret the advice I got from MSFT to upgrade to net5 to resolve the issues you introduced with JSON serialization with navigation properties in Blazor.

---
#### Feedback Bot on 11/2/2020, 00:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/2/2020, 00:40 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 5 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)
