### ISSUE TITLE
SignInAsync only takes effect with the following request, not the same

### ISSUE THREAD

**Issue by ygoe** [dotnet/aspnetcore#27595]
### Describe the bug
When using cookie authentication and calling the `SignInAsync` method, the user is still not fully signed in. This is only the case on the next request. For API scenarios where I sign in the user from a token and serve the request immediately, not even handing out an authentication cookie, this is pretty suboptimal.

### To Reproduce
I'll try to provide as much code as necessary without overloading anyone. Please let me know if you need more details.

In Startup:

```cs
public void ConfigureServices(IServiceCollection services)
{
	services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
		.AddCookie(options =>
		{
			options.EventsType = typeof(CustomCookieAuthenticationEvents);
			options.ExpireTimeSpan = TimeSpan.FromHours(4);
		});
}

public void Configure(IApplicationBuilder app)
{
	// Here's my custom middleware that works like UseStatusCodePagesWithReExecute but can sign in
	// the user from a token in the Authorization header
	app.UseMyCustomMiddleware(...);
	app.UseStaticFiles();
	app.UseAuthentication();
	app.UseRouting();
	app.UseEndpoints(endpoints => ...);
}
```

Then my custom middleware:

```cs
public async Task Invoke(HttpContext httpContext)
{
	if (access token in header or query parameter)
	{
		// Set the claims like in the Account/Login action from the interactive login form
		var claims = ...;
		// Local helper method, is used in other places, too
		var claimsIdentity = await SignInAsync(httpContext, claims, false);
		// Set user for the current request
		// This works in that it's in User.Identity, but the auth events won't fire
		httpContext.User = new ClaimsPrincipal(claimsIdentity);
	}
}

private static async Task<ClaimsIdentity> SignInAsync(HttpContext httpContext, IEnumerable<Claim> claims, bool persistent)
{
	var claimsIdentity = new ClaimsIdentity(
		claims,
		CookieAuthenticationDefaults.AuthenticationScheme);
	await httpContext.SignInAsync(
		CookieAuthenticationDefaults.AuthenticationScheme,
		new ClaimsPrincipal(claimsIdentity),
		new AuthenticationProperties
		{
			ExpiresUtc = persistent ? null : (DateTimeOffset?)DateTimeOffset.MinValue,
			IsPersistent = persistent
		});
	if (!persistent)
	{
		// Don't even send out a cookie even if it's expired from the start
		httpContext.Response.Headers.Remove("Set-Cookie");
	}
	return claimsIdentity;
}
```

And finally my custom cookie events that take the authenticated user and add some more data from the database that my application wants to easily access everywhere:

```cs
public class CustomCookieAuthenticationEvents : CookieAuthenticationEvents
{
	private readonly MainDbContext dbContext;

	public CustomCookieAuthenticationEvents(MainDbContext dbContext)
	{
		this.dbContext = dbContext;
	}

	public override async Task ValidatePrincipal(CookieValidatePrincipalContext context)
	{
		var userPrincipal = context.Principal;
		string loginName = userPrincipal.Identity.Name;
		var user = dbContext.Users.FirstOrDefault(u => u.Id == loginName);
		if (user == null || user.IsLocked)
		{
			context.RejectPrincipal();
			await context.HttpContext.SignOutAsync(
				CookieAuthenticationDefaults.AuthenticationScheme);
		}
		else
		{
			context.HttpContext.Items["User"] = user;
			context.HttpContext.Items["UserName"] = user.Name;
			context.HttpContext.Items["UserIsAdmin"] = user.IsAdmin;
		}
	}
}
```

Now what I'm seeing is this:

* When I log in interactively through the web form, after signin, a redirect is made to get the user away from the POST request with their credentials. From then on, with the persistent cookie, the `ValidatePrincipal` method is invoked on every request.
* When I log out and access a page with an access token provided through a query parameter, I'm also signed in and can see the expected resources within my application. But `ValidatePrincipal` is never called in this case and the additional HttpContext items are missing.

From what I understand, putting authentication in the pipeline after my custom middleware, it should see the signin and handle as if it's been there since the last request. But for some reason, that's not the case.

### Further technical details
- ASP.NET Core version: 3.1.9
- Include the output of `dotnet --info`

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.403
 Commit:    9e895200cd

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Tratcher** [comment]
> When using cookie authentication and calling the `SignInAsync` method, the user is still not fully signed in. This is only the case on the next request

This has always been the intentional design. That user isn't truly signed with cookies until the client has received the cookie and can send it back to you on future requests. Choosing to update the HttpContext.User on the current request is an app decision. That's not the default because often you're transitioning from one ID to another, such as from OAuth to a local identity. It's also not a good idea from a security model perspective to change the user information after the authorization checks have happened, that can lead to an escalation-of-privilege scenario.

> For API scenarios where I sign in the user from a token and serve the request immediately, not even handing out an authentication cookie, this is pretty suboptimal.

SignIn is not intended for use in API scenarios, only cookies. For actions on the same request you Authenticate the user using an AuthenticationHandler. Here's an example for Basic auth that's pretty similar:
https://github.com/blowdart/idunno.Authentication/blob/033e850737192be94eb60e1ac4f4aecb97077823/src/idunno.Authentication.Basic/BasicAuthenticationHandler.cs#L49

> And finally my custom cookie events that take the authenticated user and add some more data from the database that my application wants to easily access everywhere

Consider using [IClaimsTransformation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.iclaimstransformation?view=aspnetcore-3.1) for that instead.

**Comment by ygoe** [comment]
Thanks for the reply. I'll take a look at the provided links.

> It's also not a good idea from a security model perspective to change the user information after the authorization checks have happened, that can lead to an escalation-of-privilege scenario.

How should I do any authorisation checks before the client is authenticated? First I handle the authentication, either with the regular SignIn or by a token provided somewhere in the request. Once that's validated, the controller actions may be called and they can do the authorisation checks, depending on what was requested and what the current user's permissions are. If the controller or action has indicated that login is required, which is checked in a filter, and authentication wasn't successful, the action isn't called.

**Comment by blowdart** [comment]
_How should I do any authorisation checks before the client is authenticated?_

The simpliest answer here would be to not use cookies, or signin before calling the API, so the cookie is present (and limited to SameSite)

**Comment by blowdart** [comment]
As this is by design, and discussion has been stale for a week, closing.
