### ISSUE TITLE
As an HTTP API developer using Open API to enable integration, my APIs include an opinionated convention of ensuring operationId attributes are created for each Web API controller method

### ISSUE THREAD

**Issue by bradygaster** [dotnet/aspnetcore#27591]
One of the more important concepts in the OpenAPI Specification is the concept of `operationId`. Each API method’s descriptive metadata can be augmented with `operationId` to provide code generations and consumers with a cleaner API for consumers to use. 

When we speak of a consumer, we’re speaking of a variety of code-generation and endpoint-parsing tools that make use of the OpenAPI spec to generate code or UI. AutoRest, swagger-codegen, NSwag, and SwaggerHub - all products used throughout the API community to either generate client SDK code to call an API or to provide documentation about an API – they all prioritize operationId, as do our partners in the Power Platform, when using Open API files or API Management-hosted APIs to provide citizen developers easy ways of dialing APIs into their Power Apps.

Our Controller templates don't explicitly name each method. As such, code generators and consumers need to "guess" what to name the generated code methods. This results in odd situations where client SDKs have methods like `get`, `get1`, `get2`, and so on. 

Existing controller method syntax:

```csharp
[HttpGet]
public IEnumerable<WeatherForecast> Get()
```

Desired syntax:

```csharp
[HttpGet(Name = nameof(Get))]
public IEnumerable<WeatherForecast> Get()
```

**Comment by pranavkm** [comment]
Thanks @bradygaster. Do you see a system where we require users to specify this name if they have Swagger / ApiExplorer enabled in their apps? Or is this more of a guidance that recommends people name their operations?

**Comment by bradygaster** [comment]
@mkArtakMSFT @javiercn - definitely need this to help developers on the right `operationId` path.

**Comment by adityamandaleeka** [comment]
Triage: moving to backlog

**Comment by rafikiassumani-msft** [comment]
@bradygaster can we close this issue? OperationId work was part of .NET6. Any further improvement ?

**Comment by bradygaster** [comment]
Yes this can be closed. I'll close it. :)
