### ISSUE TITLE
Reduce E2E test dependencies

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#27610]
We currently use selenium for our E2E tests, which requires that we have the appropriate browsers installed as well as Java, NodeJS and yarn available on the machine.

Consider selenium alternatives that would allow us to remove these dependencies from the E2E test projects.

- [x] Initial replacement of Selenium with Playwright.
- [x] Enable E2E tests to run on Linux and Mac https://github.com/dotnet/aspnetcore/issues/30119
- [x] Capture E2E test artifacts upon failure on the CI https://github.com/dotnet/aspnetcore/issues/30135
- [x] Component tests migration to Playwright Sharp

**Comment by dougbu** [comment]
Including this in the DoI project for discussion in that context

**Comment by TanayParikh** [comment]
Given https://github.com/dotnet/aspnetcore/issues/37929 / https://github.com/dotnet/aspnetcore/pull/38344, I believe this is now done. Closing it out.
