### ISSUE TITLE
Back-port fix for producing correct UTC DateTime values by default, to ASP .NET 3.1.x

### ISSUE THREAD

**Issue by augustoproiete** [dotnet/aspnetcore#27618]
This is a follow-up from issue #11584 which was fixed by PR #24893 but seems it will be available in only in .NET 5.

As it stands today and described in more detail in #11584, sending a UTC time string such as `2020-11-07T02:30:04.0576719Z` to an ASP .NET Core 3.1 API  converts it to a `DateTime` with `DateTimeKind.Local` instead of `DateTimeKind.Utc` causing the API to think a conversion to UTC is necessary, leading to bad data and bugs in applications.

I completely understand the policy of not back-porting non-critical bug fixes to earlier releases which makes sense, but I am advocating that this **is** indeed a very critical bug that should be back-ported to (at least) ASP .NET 3.1.x. given that being able to correctly parse a UTC time string is fundamental to most (if not all) applications :sweat_smile:.

If back-porting is not an option, then properly documenting it on [docs.microsoft.com](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1) with a code sample/template would be the next best thing.

/cc @pranavkm

**Comment by captainsafia** [comment]
@augustoproiete While we won't be back-porting this bug-fix, you can use the code in https://github.com/dotnet/aspnetcore/issues/11584#issuecomment-506007647 as a reference for how to implement a fix in existing 3.1 applications.
