### ISSUE TITLE
[Blazor] Release compatible version of Edge

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#27612]
Will a compatible version of Edge be released in time for the next Blazor release?

I'd like to upgrade my app, but won't be able to require clients (large energy companies) to install Beta software on their computers.

**Comment by javiercn** [comment]
@mrpmorris thanks for contacting us.

Can you clarify what you are talking about? We support the latest available Edge version that is fully supported on Windows. If you are talking about old Edge (Trident + ChakraCore) we don't have any plans to support it at this time, but there might be ways to get it to work with additional transpiling + pollyfills.

**Comment by mrpmorris** [comment]
@javiercn I have clearly misunderstood something Dan said. The official release of Edge does work, thanks!
