### ISSUE TITLE
Drag Drop DataTransfer Blazor API

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/aspnetcore#27614]
Cant find any docu about DataTransfer 

as read [here](https://github.com/dotnet/aspnetcore/issues/18754)  no file drop support 
where is information about limitations and features?

**Comment by javiercn** [comment]
@hannespreishuber thanks for contacting us.

As you mentioned, we don't currently support drag and drop.

This is a dupe of the issue that you referenced, so we'll keep using that issue as a way to track the ask.
