### ISSUE TITLE
Change default server for samples from IIS Express to Kestrel

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#27630]
Samples that use IIS Express in the repo don't work because they rely on a native component that hasn't been built. For example, MVC and Blazor samples don't work when run with IIS Express. There's no guidance we currently can give to users to get samples working with IIS Express.

Although we can invest time in addressing the build process for the samples so we ensure the native component is always built before the samples are run, a quick fix is to edit the `launchSettings.json` files for the samples so they all use Kestrel for the server.

**Comment by MCCshreyas** [comment]
So the fix would be to remove IIS settings from `launchSettings.json` or to move it to 2nd option after kestral.

**Comment by captainsafia** [comment]
> So the fix would be to remove IIS settings from launchSettings.json or to move it to 2nd option after kestral.

Correct.

**Comment by MCCshreyas** [comment]
I moved the IIS Express option to 2nd one for some project, but VS still shows the IIS Express option to run, seems like VS don't respect the order of profiles in `launchSettings.json`. But if we delete the IIS Express option completely, then it shows the Kestral option as default. 
I think we need to delete the IIS Express option completely from launchSettings to get this working as expected!
So will that be ok?

**Comment by captainsafia** [comment]
@MCCshreyas Can you try renaming the `command` property for the IIS config to something other than `IISExpress`? Like "IIS Express".

**Comment by MCCshreyas** [comment]
@captainsafia I did that, but no effect on lunch selected option. See below screenshot. 
![image](https://user-images.githubusercontent.com/17148381/98902490-d8e11700-24db-11eb-8645-5b3566ab5042.png)

**Comment by gat786** [comment]
Hey,
I would like to take up this issue if it is not resolved yet. What should be done to solve this issue?

**Comment by captainsafia** [comment]
@MCCshreyas I just gave re-ordering the profiles a try and it seemed to work for me on a standalone Blazor WASM project.

I moved the Kestrel server config before the IIS Express config and the selection in the run menu changed.

Is there a chance you updated the launch settings on a project where you had already launched via IIS?

**Comment by MCCshreyas** [comment]
Ohh I will give try with reordering as you suggested!

**Comment by MCCshreyas** [comment]
@captainsafia yeah. It did work. But I needed to delete the `.vs` folder at the root to get that working. I will open PR for this!
