### ISSUE TITLE
State doesn't update the DOM when it changes and the DOM remains "dirty."

### ISSUE THREAD

**Issue by withinboredom** [dotnet/aspnetcore#27635]
### Describe the bug
When manually controlling the value of a text box, and forcing the state to stay the same, the DOM becomes out of sync with "reality" and things start to get weird.

I specifically ran into this when creating a reusable component that formats a phone number as you type. When deleting the formatting, the text box value changed (it should have stayed the same).

I'd love to know of any workarounds if you know of any.

### To Reproduce
1. Clone `https://github.com/withinboredom/Uncontrolled-example`
2. View the troublesome component: `https://github.com/withinboredom/Uncontrolled-example/blob/master/Uncontrolled/Pages/Uncontrollable.razor`
3. Build and start the project
4. In the new browser that opens, go to `/uncontrollable`
5. Enter text in the top input, value changes **(but it shouldn't)**
6. Enter text in the bottom input, value changes in both boxes (as it should)

### Further technical details
- ASP.NET Core version: 3.1 & 5.0-rc2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS 4.8.04084

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by captainsafia** [comment]
@withinboredom Can you try using a `bind` to map the `_value` parameter in your input element? The way you're modifying the `_value` variable in the event handler only work with bind in the implementation.

**Comment by withinboredom** [comment]
Ah, thanks @captainsafia! I guess that's obvious in retrospect!
