### ISSUE TITLE
UseStaticFiles returns a 404 on any file that ends with ".brotli"

### ISSUE THREAD

**Issue by weisserw** [dotnet/aspnetcore#27648]
### Describe the bug

On an ASP.NET Core 3.1 app, requesting any file that ends with the extension ".brotli" returns a 404 error.

### To Reproduce

```
$ dotnet new web
```

In Startup.cs add to Configure method:

```
app.UseStaticFiles(new StaticFileOptions {
    FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "static"))
});
```

```
$ mkdir static ; echo "Test File " > static/test.html; touch static/test.brotli
```

Open browser, navigate to http://localhost:5000/ (works), http//localhost:5000/test.html (works), http://localhost:5000/test.brotli (404)

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961
 
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.101/
 
Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
 
.NET Core SDKs installed:
  3.0.102 [/usr/share/dotnet/sdk]
  3.1.101 [/usr/share/dotnet/sdk]
 
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
 
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by blowdart** [comment]
Did you [add the extension](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1#fileextensioncontenttypeprovider) to the list of allowed file extensions and their associated mime types? .brotli is not there by default, nor is it an IANA r[eserved extension](https://www.iana.org/assignments/media-types/media-types.xhtml), which is where we source our default list from

**Comment by weisserw** [comment]
Not clear to me that responding with a 404 is the correct behavior here, but glad there is a way to return these files at least 👍

**Comment by blowdart** [comment]
404 is the secure way to respond, it doesn't give away the existence, or not, of something you didn't mean to serve up.

But I assume this unblocks you, so I'll close the issue
