### ISSUE TITLE
IOutboundParameterTransformer: add support for QueryString parameters

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#27646]
I've added a sample WebApplication:
https://github.com/alienwareone/ComplexOutboundParameterTransformerSample

Relevant Source Code:
https://github.com/alienwareone/ComplexOutboundParameterTransformerSample/blob/a52b3d8191a382cea9c35535bcf6075d0d3fc8cd/WebApplication2/ProductFiltersConstraint.cs#L91-L97

**Comment by pranavkm** [comment]
@alienwareone it looks like you were able to configure outbound transformation to use query strings. Was there a specific issue that I'm not seeing here?

**Comment by alienwareone** [comment]
@pranavkm No. Unfortunately it will get encoded:
`/Germany/Smartphone%3Fq%3Ddual%20sim`
Should be:
`/Germany/Smartphone?q=dual%20sim`
