### ISSUE TITLE
Blazor - New Razor Editor - Attempts to analyze files within the project that are marked as <Compile Remove> in the project file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27659]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor---New-Razor-Editor---Attempts-to-/1230833?preview=true)._

---
[severity:Other]
- Create a Razor Class Library and a Blazor Server Project
- Exclude some . Razor files from the project but leave them in the folder

The editor is still inspecting these files and showing any resultant errors in the Error List

---
#### Feedback Bot on 10/22/2020, 11:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
The goal here in 16.9-Preview4 is to find out what's going wrong, not to fix it. Once we know what's wrong we can decide when is the right time to fix.

**Comment by ryanbrandenburg** [comment]
As far as I can tell the problem here is that when we're loading in files (such as in `RazorFileChangeDetector.StartAsync` and maybe other places) we just look straight at the file system and don't consult `<Compile Remove />` at all. What does that say to you about timing @NTaylorMullen?

**Comment by ryanbrandenburg** [comment]
Taylor: The intent is that [this ](https://github.com/dotnet/aspnetcore-tooling/blob/c2dbbbe98334786bb4bca7a0a52183d1cbab5fe3/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs#L328-L341) would move the document from an "official" project into the misc project if it was removed from the compilation.

**Comment by ryanbrandenburg** [comment]
If we could get some  clarification of the scenario from the original filer that would be helpful. It's true that exclusion of a file VIA `<Compile Remove=""/>` doesn't keep it out, but you CAN keep a component from being compiled or analyzed by doing `<Content Remove=""/>` and I've confirmed that locally. So, if this issue is about `<Compile Remove="" />` then it's "by-design". If there's a different problem please clarify and we'll give it another look.
