### ISSUE TITLE
Blazor - New Razor Editor does not resolve component tags and shows a phantom error count in the editor window

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor---New-Razor-Editor-does-not-resol/1230820?preview=true)._

---
[severity:Other]
- Blazor Server Project and Razor Class Library
- Switch to the experimental Razor editor

- The project does build but: (1) No Goto Definition (2) Squigglies with a phantom error count appears (3) 

This is the case for every component in the project

---
#### Feedback Bot on 10/22/2020, 11:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/aspnetcore/issues/29271
