### ISSUE TITLE
Visual Studio IDE hangs on CSHTML edit

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27666]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-IDE-hangs-on-CSHTML-edit/1247503?preview=true)._

---
Microsoft Visual Studio Community 2019
Version 16.7.7

1. Create new ASP .NET Core Web Application
2. Name the application.
3. Select .NET Core, ASP.NET Core 3.1, Web-Application (Model-View-Controller)
4. Close default dev page.
5. Navigate in Solution Explorer to <Project>/Views/Shared.
6. Simple select "_layout.cshtml" (file name displayed in upper right corner of ide)
7. Select any html text for editing... IDE HANGS HERE...

8. Kill VS from Task Manager...
9. Reopen project, and "double click" the same _layout.cshtml... File is not editable... However...
10. Switch focus from VS to any other application, come back to edit file... HUNG AGAIN...

It appears that any editing of CSHTML file with this project hangs the ide indefinitely.

---
#### Feedback Bot on 11/6/2020, 11:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Stewart Basterash solved on 11/7/2020, 02:50 AM, 0 votes: 

<p>[Workaround]<br>
I tested this with an older development project. I opened a .NET Core Web Application (MVC) that was built with 2.1… It also had the same issue. Editing any CSHTML file hung the environment. VS had been updated numerous times since that build. I decided to completely remove Visual Studio and reinstall from the latest release version… I no longer see the issue, and it appears to be resolved.</p>

**Comment by NTaylorMullen** [comment]
Goal here is to see if the dump has anything interesting in it pointing to Razor specific bits in the LSPification landscape

**Comment by terryaney** [comment]
> Goal here is to see if the dump has anything interesting in it pointing to Razor specific bits in the LSPification landscape

How do you get a dump?  I'm seeing the same problem.  After opening _Layout.cshtml (v 16.9.6), any modification to file locks up VS for 60 seconds plus.  Essentially becomes unusable.  I'd love to send some info your way to help resolve the issue.

**Comment by NTaylorMullen** [comment]
> How do you get a dump? I'm seeing the same problem. After opening _Layout.cshtml (v 16.9.6), any modification to file locks up VS for 60 seconds plus. Essentially becomes unusable. I'd love to send some info your way to help resolve the issue.

Ah, best way is to use VS' "Report a Problem" in the top right hand corner:
![image](https://user-images.githubusercontent.com/2008729/119535152-93c85800-bd3c-11eb-8c64-e1866b467bbe.png). If you can link that issue here i'll take a look. Really appreciate your willingness to help out 😄

**Comment by terryaney** [comment]
I've tried three times (from sep VS recording the VS displaying the problem) and it always gives me error saying 'Error saving recording' after I record the steps.  Suggestions?

**Comment by terryaney** [comment]
OK, 4th time is a charm (along without typing comments in recording)... https://developercommunity.visualstudio.com/t/vs-ide-hangs-when-editing-layoutcshtml/1431551

**Comment by NTaylorMullen** [comment]
Thanks @terryaney, we'll take a look!

**Comment by allisonchou** [comment]
Closing as this issue no longer seems to repro with newer builds.
