### ISSUE TITLE
Repeatable crash with specific Razor text edit

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27667]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Repeatable-crash-with-specific-Razor-tex/1248069?preview=true)._

---
[severity:It's more difficult to complete my work]
I have this line of code in Razor:

```
@(Html.TextBoxFor(m => m.DeliveryDate, new { @class = "form-control datepicker", size = 4, @Value = Model.DeliveryDate.ToString("dd/MM/yyyy") }))
```
I want to add an onchange handler. So I put the caret after the yyyy"), then type:

```
 onchange = ""
```
Then press the left arrow to move the caret back to enter the handler. The caret doesn't move left. VS hangs for a moment, then crashes and restarts.

Three times in a row now. 100% repeatable.

Same thing if I start the edit with a comma:

```
, onchange = ""
```
Same thing if I start typing the handler:

```
, onchange = "something
```

Seems to crash after a certain time with onchange onscreen rather than specific combination of keystrokes.
Can't find a way to 'trick' VS into letting me make the edit so I've had to use notepad instead. After editing with notepad so the line reads:

```
@(Html.TextBoxFor(m => m.DeliveryDate, new { @class = "form-control datepicker", size = 4, @Value = Model.DeliveryDate.ToString("dd/MM/yyyy"), onchange = "something" }))
```
VS was happy to reload and display the edited line.

---
#### Feedback Bot on 11/9/2020, 01:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
This doesn't repro for me and is likely fixed with the new editor. Closing out for now.
