### ISSUE TITLE
Disable Just My Code Option in the Launch.json for Blazor

### ISSUE THREAD

**Issue by tanekim77** [dotnet/aspnetcore#27672]
I am trying to turn off "Just My Code" option in the following launch.json vs code configuration, but it seems there is no such option. Am I mssing something?

```
        {
            "name": "Launch and Debug Hosted Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "hosted": true,
            "program": "${workspaceFolder}/Server/bin/Debug/net5.0/BlazorApp.Server.dll",
            "cwd": "${workspaceFolder}/Server",
            "browser": "edge",
            "trace": true
        }
```

**Comment by javiercn** [comment]
@tanekim77 thanks for contacting us.

As far as I know there is no such option, but @captainsafia will know more.

**Comment by captainsafia** [comment]
Hi @tanekim77! This isn't supported for Blazor WASM. We're tracking adding support for this in https://github.com/dotnet/aspnetcore/issues/24623. This captures the work necessary to pass these types of configs to the Mono debugger.

If you'd like to adjust "Just My Code" for the server portion of a hosted Blazor WASM app, this will be supported in an upcoming version of the O# extension and is tracked in https://github.com/OmniSharp/omnisharp-vscode/issues/4108.

Closing this in favor of the existing issues.
