### ISSUE TITLE
Printing virtualized Data in Blazor 

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/aspnetcore#27673]
When I try to print a web page that has virtualized Data. 
**using  ```<Virtualize Items="@GetData()" Context="context"  >```**
It only shows few data and the rest is white pages.

**Comment by javiercn** [comment]
@Sharaf-Mansour thanks for contacting us.

I think when you want to print the data you'll need to switch to an `unvirtualized` version of it, so that all the data is displayed in that case.

**Comment by Sharaf-Mansour** [comment]
Using unvirtualized version made a huge performance drop.
I used ```OverscanCount="@(GetData().Count / 2)``` To render all elements.
