### ISSUE TITLE
Remove use of runtime -internal archives

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#27687]
To bring source build and the Microsoft build in line, and reduce the overall size of the .NET build output (-internal archives correspond to about 1.3GB of in the total build drop), aspnetcore should remove using of the runtime -internal archives, instead using the customer archives and extracting the bits they need.

**Comment by mmitche** [comment]
See https://github.com/dotnet/installer/issues/9042 for additional context.

**Comment by dougbu** [comment]
#27845 is failing because dotnet/runtime has stopped updating Microsoft.NETCore.App.Internal. But, is the version of Microsoft.NETCore.App.Runtime..win-x64 now guaranteed to be useful and correct in global.json❔ (Thought we had the .Internal package for a real reason.)

**Comment by mmitche** [comment]
https://github.com/dotnet/aspnetcore/pull/27737 is the right PR for this.

**Comment by wtgodbe** [comment]
As far as I can tell, we don't download the `-internal` runtime archive at all - only the public one. Here are all of the references to it in the repo that I could find:

https://github.com/dotnet/aspnetcore/blob/39c471a4a74aeadd4f3157f0556bf0bd45d0d947/src/Framework/App.Runtime/src/Microsoft.AspNetCore.App.Runtime.csproj#L34-L37

https://github.com/dotnet/aspnetcore/blob/39c471a4a74aeadd4f3157f0556bf0bd45d0d947/src/Installers/Windows/WindowsHostingBundle/Product.targets#L31-L46

**Comment by dougbu** [comment]
Closing this was the **Right Thing:tm:** to do. This was fixed in 634b50eeee1311382aee774ff32f0b54fdbb7c0f aka #27737; we now use `$(MicrosoftNETCoreBrowserDebugHostTransportVersion)` to get the correct non-stable version when downloading runtimes.

Thanks again @jkoritzinsky❕
