### ISSUE TITLE
Can't install Microsoft.AspNetCore.AzureAppServices.HostingStartup 5.0.0 to net5.0 project

### ISSUE THREAD

**Issue by natehitze** [dotnet/aspnetcore#27680]
### Describe the bug
`Microsoft.AspNetCore.AzureAppServices.HostingStartup` can't be installed via NuGet to a net5.0 project.

### Error
`Package Microsoft.AspNetCore.AzureAppServices.HostingStartup 5.0.0 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.AzureAppServices.HostingStartup 5.0.0 supports: net50 (.NETFramework,Version=v5.0)`

**Comment by javiercn** [comment]
@natehitze thanks for contacting us.

@dotnet/aspnet-build can you look into this?

/cc: @Pilchie

**Comment by BrennanConroy** [comment]
What sdk version are you using?

**Comment by natehitze** [comment]
5.0.100

**Comment by BrennanConroy** [comment]
We might need a repro app since this isn't reproducible.

**Comment by natehitze** [comment]
I'm really sorry, I should have done a little more digging before posting. Seems like this is an issue with Rider's package restore - even though it's using 5's SDK for builds it looks like it's using an old version of NuGet for package management. I updated the csproj file manually and ran `dotnet restore` on it and the project is all good now.

Thanks!!
