### ISSUE TITLE
Hierarchical use of same component causes property inheritance

### ISSUE THREAD

**Issue by artemfomin** [dotnet/aspnetcore#27698]
### Describe the bug
Got a component:

```
public partial class HierarchicMenuItem : ComponentBase
    {
        private bool _isOpen = false;

        public string IsOpen { get { return _isOpen ? "open" : string.Empty; } }
        public string DisplayChildrenStyle { get { return _isOpen ? "inherit" : "none"; } }

        [Parameter]
        public RenderFragment ChildContent { get; set; }

        [Parameter]
        public string Label { get; set; }

        public void ToggleExpand()
        {
            _isOpen = !_isOpen;
        }
    }
```
And it's usage:

```
<HierarchicMenuItem Label="Some item">
      <HierarchicMenuItem Label="Repeating item">
              <li>
                 <a href="intel_marketing_dashboard.html" title="Marketing Dashboard" data-filter-tags="application intel marketing dashboard" class=" waves-effect waves-themed">
                   <span class="nav-link-text" data-i18n="nav.application_intel_marketing_dashboard">Marketing Dashboard</span>
                 </a>
             </li>
      </HierarchicMenuItem>
</HierarchicMenuItem>
```

### To Reproduce

1. Click parent item (Some item)
2. Code behind calls `ToggleExpand()` and sets `_isOpen` to true for parent
3. We see open parent and closed child with `_isOpen` field accordingly `true` and `false`
4. Click child item (Repeating item)
5. Parent closes, `_isOpen` field is set to `false` for parent and `true` for child
6. Click parent item (Some item)
7. Code behind calls `ToggleExpand()` and sets `_isOpen` to true for parent
8. We see both child and parent open and `_isOpen` set to `true` for both

Expected behaviour is to change `_isOpen` value independently for each component instance. Clicking child item should not switch property value for parent

### Exceptions (if any)

No exceptions

### Further technical details
```
<PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.1" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="3.2.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.6" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.0" />
</ItemGroup>
```

.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual studio 2019 Professional 16.7.7

**Comment by javiercn** [comment]
@artemfomin thanks for contacting us.

This is likely due to the way Blazor diffs the DOM, the issue is probably caused by the way you are tracking the state of the hierarchy within the component.

We would recommend extracting the `_isOpen` outside the component tree and instead tracking and updating it from outside the component. That will likely resolve this issue.

If this doesn't work, we would need a minimal repro project in order for us to try and help you.

**Comment by artemfomin** [comment]
@javiercn thank you for answer.
I don't think that extracting open/closed state to upper level is a good idea from both functional and technical architecture perspective. Component structure means that each component should be able to manage it's state within itself. So most probably there might be some collision while identifying components.
What is the prefferable way to provide you the sources?

**Comment by artemfomin** [comment]
Fixed.
My bad. Has put `@onclick` event handler on `ul` element so click triggered event for both child and parent as dropdown is part of `ul` tag also
