### ISSUE TITLE
Blazor Server: don't bind event listener for non-rendered element

### ISSUE THREAD

**Issue by shanemikel** [dotnet/aspnetcore#27692]
I'm interested in keeping authorization simple by using the `AuthorizeView` component.  This request is an elaboration of the documentation issue: dotnet/AspNetCore.Docs/issues/20462.

In short, say I have Blazor pages, each of which requires authentication and role-based authorization:
```
@page "/page1"
@attribute [Authorize]

<AuthorizeView Role="page1">
    <!-- SECURE CONTENT -->
    <button @onclick="SecureAction">Secure Action</button>
</AuthorizeView>

@code {
    private void SecureAction()
    {
        // Unauthorized users should not be able to execute this code path
    }
}
```

It would be nice if it was impossible for clients to manually trigger the `SecureAction` method.  In this case, because the only element to which it binds is not rendered, no SignalR event listener should be bound.

I would prefer not to inject the `AuthenticationStateProvider` in every page and guard every protected task/method with it.

re: @guardrex

**Comment by javiercn** [comment]
@shanemikel thanks for contacting us.

I don't believe this is generally possible without integrating authorization with the renderer/dispatching mechanism in a strongly coupled way, which is not something we think we'll do.

You could alternatively write a "protected" action component that encapsulates the behavior you want.

```
<ProtectedAction Handler="SecureAction" Context="protectedHandler">
    <!-- SECURE CONTENT -->
    <button @onclick="protectedHandler">Secure Action</button>
</ProtectedAction>
```

Within the `ProtectedAction` component you'll have something like this
```
@ChildContent(_protectedHandler);
@code
{
  [Parameter] public EventCallback Handler { get; set; }
  [CascadingParameter] public Task<AuthenticationState> AuthenticationState { get; set; }

  protected override void OnParametersSet()
  {
    _protectedHandler = ProtectedHandler;
  }

  private async Task ProtectedHandler()
  {
    var state = await AuthenticationState;
    var authorized = ...
    if(authorized)
    {
      await Handler.InvokeAsync();
    }
  }
}
```

**Comment by guardrex** [comment]
We could cover this as an **_advanced_** authz pattern ..... but *later*, probably even early next year given all of the work I have to do right now. @javiercn / @mkArtakMSFT ... let me know if you would like to **_avoid_** covering this pattern. I'll close the docs issue if that's the case.

**Comment by pranavkm** [comment]
@shanemikel by default event handlers for non-rendered elements are unable to be invoked. The scenario @javiercn was talking of was that **if** your authorization status changes after an element is rendered, there is a small window (in the order of milliseconds) before a new render that event handlers could be triggered. (

[Initially authorized] --> [Unauthorized / StateHasChanged] .... You can continue to trigger the event now .... --> [Render](Now it's no longer possible to trigger)

If you were concerned about the small window, you could consider using the pattern @javiercn suggested. Most users would not need to worry about this. 

@guardrex I don't think this needs to be documented.

**Comment by shanemikel** [comment]
@pranavkm Oh, that's great!  I actually think that would be a nice addition to the documentation.

**Comment by pranavkm** [comment]
@shanemikel we generally do not document things our framework does not do. I'll defer to @guardrex to make a call here.

**Comment by guardrex** [comment]
> default event handlers for non-rendered elements are unable to be invoked

We don't say that ... we only imply it, so I'll add a line to cover it.

**Comment by javiercn** [comment]
Closing this issue since the original question was answered.
