### ISSUE TITLE
Auto refresh dotnet watch for ASP.NET Core 5 not working when razor compilation is enabled

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/aspnetcore#27707]
### Describe the bug
With the release of .NET 5 dotnet watch should have the ability to auto refresh the browser.
It seems if the razor compilation feature is enable, it will prevent refreshing from working
If I create a new project without the razor compilation option, the auto refreshing works

Is there a way to enable razor compilation ASPNETCORE_HOSTINGSTARTUPASSEMBLIES etc  and still have the auto refresh working? Right now I would have to comment out the nuget package and remove the setting from the launchSettings,json

### To Reproduce
1. Create a new ASP.NET 5 MVC project
2. Make sure to tick razor compilation feature ON
3. Run `dotnet watch run`
4. Change something in the razor page or controller

### Further technical details
- ASP.NET Core version 5
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

**Comment by iSeiryu** [comment]
Same here, but I'm using AspNetCore API and running it inside `mcr.microsoft.com/dotnet/sdk` with default setup.
It was working with
`<TargetFramework>netcoreapp3.1</TargetFramework>`
And it stopped working with
`<TargetFramework>net5.0</TargetFramework>`

**Comment by JamesFenton** [comment]
Having the same issue. This would really help our team if we could use the auto refresh with razor runtime compilation

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is fixed in 6.0 as we've added support for hot reload.
We don't plan to make any future improvements to the runtime compilation experience going forward.
