### ISSUE TITLE
Identity - Add a password validator function that doesn't require an existing user

### ISSUE THREAD

**Issue by cjimenezber** [dotnet/aspnetcore#27700]
### Is your feature request related to a problem? Please describe.
I am using fluent validator for our API and I am implementing what I would call an "invitation flow" in which users cannot register, but are instead sent an email invitation to register. Because I use fluent validator I would like to have a function that I can use a password validator that doesn't require for the user to exist. 

Instead, I want to use a validate function that lets me validate a _potential_ password, not one that belongs to a specific user. This is because I handle my validation outside of my services or repositories and would like to keep respecting this for the front end to not have any issues.

### Describe the solution you'd like

[Link to docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.passwordvalidator-1.validateasync?view=aspnetcore-3.1#Microsoft_AspNetCore_Identity_PasswordValidator_1_ValidateAsync_Microsoft_AspNetCore_Identity_UserManager__0___0_System_String_)

As you can see above, the funcion requires a user, I want a version of that funcion that respects the Identity options I have provided:

![image](https://user-images.githubusercontent.com/52975337/98744547-84248b80-2377-11eb-88c3-34815c736359.png)

But that doesn't require me to reimplement them in a custom model validator based on the options (because I know I can retrieve them) I have set up.

### Additional context

This may not be the most requested feature by many, but I believe it's very easy to do. All I want is for Identity to have a way to decouple password validation from user creation so that I can use it in a front faced validator like this one:

![image](https://user-images.githubusercontent.com/52975337/98744861-1167e000-2378-11eb-8dfe-603660d98bf1.png)

**Comment by HaoK** [comment]
Identity itself will always pass in the current user, if you are trying to use the validator for your own purposes, and you control the invocation, you can always just pass in a dummy user since your (and most validators) ignore the parameter.  The reason its passed in, is so more advanced validators can do things like password history
