### ISSUE TITLE
AddNegotiate return 401

### ISSUE THREAD

**Issue by balkarov** [dotnet/aspnetcore#27719]
Hello.

I'am trying use Kerberos on Ubuntu. 
I used [this](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio) instruction for settings and [this](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller)

My sample app is
[WinAuth.zip](https://github.com/dotnet/aspnetcore/files/5524411/WinAuth.zip)

Code:
```C#
services.AddAuthorization();
            services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate(o =>
        {
            o.Events = new NegotiateEvents
            {
                OnAuthenticated = challange =>
                {
                    Console.WriteLine("OnAuthenticated");
                    return Task.CompletedTask;
                },
                OnChallenge = challange =>
                {
                    Console.WriteLine("OnChallenge");
                    return Task.CompletedTask;
                },
                OnAuthenticationFailed = context =>
                {
                    Console.WriteLine("OnAuthenticationFailed");
                    Console.WriteLine(context.Exception.Message);
                    return Task.CompletedTask;
                }
            };
```

I connected to Active Directery on Ubuntu.
`klist` return this
![Снимок](https://user-images.githubusercontent.com/6030335/98821363-830b6100-2440-11eb-9df0-485413679fb3.PNG)

keytab exported too.

On ubuntu I run app with `dotnet WinAuth.dll`.

When I open localhost:5000/Home/Privacy browser return 401 error.
![sdfsdf](https://user-images.githubusercontent.com/6030335/98822009-5146ca00-2441-11eb-8653-876b2d35cdc5.PNG)

In Kernel logs:
![Снимок3](https://user-images.githubusercontent.com/6030335/98822235-a4208180-2441-11eb-9424-8028868a5623.PNG)

I am trying to open chrome with arguments `--auth-server-whitelist="*.DOMAIN"` but error the same

What am I doing wrong?

**Comment by akovac35** [comment]
I believe the problem is that the challenge is never sent, see how I worked around the issue: 
https://github.com/akovac35/TestingBlazor/blob/98403824abbcb54f16fffe5387eee46bc3360ef6/Startup.cs#L60

```
public class ValidateAuthentication : IMiddleware
    {
        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            if (context.User.Identity.IsAuthenticated)
                await next(context);
            else
                await context.ChallengeAsync();
        }
    }
```

This is something to improve upon for the ASP.NET team.

**Comment by Tratcher** [comment]
@akovac35 that doesn't seem related, their logs show the challenge being sent. Also, that middleware shouldn't be necessary for Negotiate. Instead, you either mark your endpoints/controllers as [Authorized], or you set the default authorization policy for the app as requiring an authenticated user. Were you also testing on Ubuntu?

@balkarov 
A) You'll get more details if you turn the "Microsoft" log levels up to Debug, you shouldn't need your own Console.WriteLines.
B) Kerberos is name sensitive, it's not going to work on "localhost", you need to at least use the machine name.
C) The main supported scenario is from Windows clients to Linux servers. Does it work for you if accessed from a Windows client?

**Comment by akovac35** [comment]
@Tratcher: You are correct, I overlooked his Negotiate header value in the screenshot. I was testing on Windows with Blazor.

**Comment by balkarov** [comment]
@Tratcher thank you for your answer
B) I change it to ip address but it does not work too
C) I tried connect from windows via IE (account in activity directory too) to Ubuntu server and it shows Login/Password promt. But must be login automatically.
![image](https://user-images.githubusercontent.com/6030335/98918782-18f5c900-24df-11eb-8d58-2b6701d52d45.png)

But I know NTLM does not work on Ubuntu and need Kerberos ticket.
PS: I enabled Intergated Windows Auth in IE settings.

**Comment by balkarov** [comment]
I have tried run this application on Windows (account in Active directory) via Kestrel: `dotnet WinAuth.dll` and open in IE url and get Login/Password promt too. But how enable Kerberos? What am I doing wrong?

**Comment by akovac35** [comment]
This problem is likely with domain and browser settings?

You have to narrow the scope of the problem a bit. Try the following:
1. Try this project with Chrome on Windows in the same domain:
https://github.com/akovac35/TestingBlazor
With Chrome there are no prompts when I test locally. If I open a private browser screen, there is a prompt.
2. the above project does not work any longer on Edge after migrating to .NET 5 even after removing the custom middleware.

If you can reproduce then this may be something for the MS team to work with.

**Comment by Tratcher** [comment]
Kerberos requires:
1) Using fully qualified names (mysite.mydomain.com)
2) SPNs registered in active directory against the account that has the kerberos ticket.
3) Communication across machines. On the same machine NTLM is always used instead.

Please share the Debug logs for more details.

**Comment by balkarov** [comment]
@akovac35 thank you for your example. 
But yours Startup is the same as mine. And you use .net 5, but I need netcoreapp.

@Tratcher 
1) Do you mean must I use domain, not IP address (internal or localhost)?
2) I has tickets. This my result
![Снимок](https://user-images.githubusercontent.com/6030335/99039041-a72d8600-2597-11eb-83b8-ebcea060662b.PNG)

3) I tried connect from another domain machine and result the same. Only NTLM

**Comment by balkarov** [comment]
My logs:
![Снимок](https://user-images.githubusercontent.com/6030335/99042933-a2b89b80-259e-11eb-96ee-8b846f75d7d8.PNG)


When I open path with Authorize attribute
![image](https://user-images.githubusercontent.com/6030335/99043015-c4b21e00-259e-11eb-8cb8-ee460af5f453.png)

**Comment by balkarov** [comment]
@Tratcher it works now!
Thank you for your help!
I used domain name instead IP and now Kerberos works on Linux!

> Kerberos requires:
> 
> Using fully qualified names (mysite.mydomain.com)
>
