### ISSUE TITLE
New files added are automatically excluded from dotnet watch in project file

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#27718]
### Describe the bug
New components are automatically excluded from watch in project file.

For every new file an entry is created in the project to exclude it from dotnet watch:
```
  <ItemGroup>
    <Watch Remove="MyNewComponent.razor" />
  </ItemGroup>
```
By default, I think the file should be watched.

The same issue applies to scoped CSS and JS files.

### To Reproduce
Create a new project and add a component and inspect the project file.

### Further technical details
- Tested with 5.0 GA and 16.8

**Comment by mkArtakMSFT** [comment]
@vijayrkn  is this something your team controls?

**Comment by davkean** [comment]
You've dup'd it against a bug that was closed as external, you need to actually file a follow-up bug to get a team to look at it. You can internally and move to it to Project\CPS.

**Comment by mkArtakMSFT** [comment]
@davkean will it work if I move this over to https://github.com/dotnet/project-system ?

**Comment by mkArtakMSFT** [comment]
Done, filed an [internal issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1248429) to track this.

**Comment by szalapski** [comment]
Is there any way to get updates to it posted here?  I can't see the internal issue.
