### ISSUE TITLE
Razor formatting doesn't work for @section blocks

### ISSUE THREAD

**Issue by KrisPetkov** [dotnet/aspnetcore#27710]
### Describe the bug
When using the VS Code with an ASP.NET Core project and try to format the cshtml file nothing happens. See the attached below gif for a reproduction. There is a similar discussion here: https://github.com/dotnet/aspnetcore/issues/14271

### To Reproduce
![0RaY9IwMpH](https://user-images.githubusercontent.com/6774998/95957630-9955db00-0e08-11eb-946e-943b54ed46d7.gif)

### Further technical details
- VS Code 1.51
- Scenario Local

**Comment by NTaylorMullen** [comment]
Hi @KrisPetkov would you mind providing a repro project for us to investigate further?

**Comment by KrisPetkov** [comment]
Hi @NTaylorMullen I will try to provide a demo project today, because the project from the description is a proprietary one.

**Comment by KrisPetkov** [comment]
Hi @NTaylorMullen,

I have prepared a demo project which you can find here: https://github.com/KrisPetkov/VscTestApp/tree/master
You can reproduce the problem in the **Views/Home/Index.cshtml** file. 

P.S. While I was preparing the demo I found something else. The problem does occur only when there is **Scripts section** in the file. If this section is missing the format functionality is working just fine. You can see the reproduction of this finding in the following gif: 

![SBqkiCIif5](https://user-images.githubusercontent.com/6774998/99946633-5714a780-2d7f-11eb-90d4-bca0ce4be3f1.gif)
