### ISSUE TITLE
Add option to disable logging in sample Blazor app

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/aspnetcore#27721]
When publishing the Blazor sample, System.Extensions.Logging and System.Extensions.Logging.Abstractions are present in the output and appear to be held alive by DependencyInjection. It would be nice to ensure they can be linked out by someone attempting to maximize size reduction, even if that requires an extra flag to be set in the build configuration.

**Comment by SteveSandersonMS** [comment]
Logging is a feature of the default app template. Is this a proposal to remove that feature, or something more subtle?

**Comment by CoffeeFlux** [comment]
This was essentially a feature request to be able to disable logging, yes. I think in light of the newer goals this is no longer very important, as we're focused on shrinking the default template instead of getting the smallest possible sample.

**Comment by CoffeeFlux** [comment]
Is that feature in the template or Blazor itself?

**Comment by eerhardt** [comment]
I believe the intention here is to introduce a [feature switch](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md) which allows for logging to be conditionally removed. All that should be necessary is to add an `if` around this code:

https://github.com/dotnet/aspnetcore/blob/85a6cb07ae2e1adf5a03740f8d40333b7b8e360c/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs#L249-L252

That would allow for the `Microsoft.Extensions.Logging*.dll` assemblies to be removed from the app (~18 KB .br compressed).

By default, we can keep the same behavior as we have now. But if someone wants to get their app as small as possible, this would enable them to remove these logging assemblies by flipping the feature switch.

**Comment by SteveSandersonMS** [comment]
@eerhardt The availability of the logger DI services is an assumption we make throughout various core components, such as `<Router>`. 3rd-party components will also freely rely on its presence since it's always been part of the mandatory minimal set and within ASP.NET Core circles it's generally assumed that any application is going to support logging.

Do you think it would be reasonable for us to consider adding a "no logging" option only if we get some clear feedback from customers that they want it? If almost nobody would realistically turn on such an option, it seems like the benefit is artificial at best, and would also impose a some disproportionate costs like us trying to account for the cases where logging isn't available.

**Comment by eerhardt** [comment]
> Do you think it would be reasonable for us to consider adding a "no logging" option only if we get some clear feedback from customers that they want it?

The idea is that if a customer wants their application as small as possible, they would turn this switch on. We would document it just like the others in https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#disable-unused-features.

> and would also impose a some disproportionate costs like us trying to account for the cases where logging isn't available.

I think the `ILogger` would always be there for any code to use. Code that needs to log shouldn't need to be aware if logging was disabled or not. We would just strip `builder.AddProvider(new WebAssemblyConsoleLoggerProvider(DefaultWebAssemblyJSRuntime.Instance)); ` and probably just add a `NullLogger` instead.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
