### ISSUE TITLE
dotnet watch not working for scss

### ISSUE THREAD

**Issue by mattd73uk** [dotnet/aspnetcore#27725]
Hi,
Similar to https://github.com/dotnet/aspnetcore/issues/25483
"Running `dotnet watch run` doesn't rebuild for changes to component specific CSS" 
This is fixed for css, but fails to work for component specific scss files 
I followed the preprocessor advice here https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#css-preprocessor-support
 and used Delegate.SassBuilder

dotnet watch should trigger compilation/relaunch either:
a) on specifically .scss file changes
b) or be able to add custom file extensions to monitor/trigger

Or am I missing something?

To reproduce:
1) Create a .Net 5 Blazor WebAssembly solution.
2) Nuget add Delegate.SassBuilder to the Client solution.
3) Add a Index.razor.scss file.  Add some css to it e.g.
h1 {
    font-family: 'Comic Sans MS';
 }
When you manually build the css is generated and displayed correctly.  But command line "dotnet watch run" and make changes to the scss, and the build isn't triggered to regen the css.

**Comment by pranavkm** [comment]
@mattd73uk, dotnet-watch allows configuring additional files to watch: https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-5.0#customize-files-list-to-watch.
