### ISSUE TITLE
Blazor: lazy loading of class libraries

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/aspnetcore#27722]
Blazor currently supports lazy loading of user assemblies, but the same should be possible for parts of the BCL. A look at loader logs indicates this might be useful, but it would be nice to have someone from the Blazor team investigate the degree to which this possible and valuable. From a runtime perspective, this should definitely be possible and we can address any issues that come up in practice.

**Comment by mkArtakMSFT** [comment]
@CoffeeFlux can you please clarify what exactly is working differently for the BCL assemblies?
