### ISSUE TITLE
(Issue #25258): Fetching dotnet.timezones.blat data fails in published Blazor app

### ISSUE THREAD

**Issue by dantronik-markus** [dotnet/aspnetcore#27720]
I am still experiencing issue #25258 despite the author claiming that it was fixed at the end of August.
This is with a published Blazor application on a server with IIS.

### Describe the bug
Please refer to #25258 for the description.

### To Reproduce
See #25258
### Exceptions (if any)
See #25258

### Further technical details
- ASP.NET Core version v5.0.0
- Include the output of `dotnet --info`
<details>
<summary>dotnet --info</summary>

```
PS C:\Users\Administrator> dotnet --info
.NET-Befehlszeilentools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

- Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 6.0

**Comment by dantronik-markus** [comment]
Setting "cacheBootResources" to "false" in blazor.boot.json works around this issue.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
 Can you please share the published `web.config` file?

**Comment by dantronik-markus** [comment]
The contents of the published `web.config` file are as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\IKON_2_0.Server.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>
<!--ProjectGuid: 7e996b4d-0bf1-4f08-bbf1-d025edba07e0-->
```

**Comment by Fredz66** [comment]
I've the same problem after an update to VS2019 16.9.0 Preview 1.0. The content of web.config is the same except for the content of processPath and ProjectGuid. Thank you.

**Comment by Fredz66** [comment]
You can ignore my previous message, the problem probably happens because I've recently started tracko,g my source with git and there is a known issue with CR-LF file endings. For now I've simply removed the files after publication because the <BlazorCacheBootResources>false</BlazorCacheBootResources> and fiddling with .gitattributes didn't work for me.

**Comment by dantronik-markus** [comment]
I previously used the Blazor Dual Mode as described here: https://github.com/Suchiman/BlazorDualMode

The issue is fixed when I undid those changes and switched back to the normal Blazor Client mode. All my changes here: https://gist.github.com/dantronik-markus/3edc8d6919051e248cac0145ee7af055

**Comment by pranavkm** [comment]
Closing this since it looks like the issue was resolved.
