### ISSUE TITLE
Excess code found in React-CSharp Template

### ISSUE THREAD

**Issue by damla** [dotnet/aspnetcore#27728]
### Description of Bug
**Folder Location:** aspnetcore/src/ProjectTemplates/Web.Spa.ProjectTemplates/content/React-CSharp/Pages/Shared/_LoginPartial.cshtml

- Templates created with SDK 5.0.100, ReactJS and Individual Identity has excess attribute, which is "asp-area="Identity", found in the cshtml file in the location above. The project does not have any area folder in it therefore, it is completely useless to have this attribute as a default.

- In addition to the problem above, there is also a missing space found in line 33.

Because of the problems above, the project started with this template gave 5 errors at the beginning but this does not effects the building process.

### To Reproduce
To reproduce this issue, you may take a look at the repo below;
https://github.com/damla/aspnet-react-template-issue

### Further technical details
- .NET 5.0.100
- React-CSharp Template with Individual Authentication
- Include the output of `dotnet --info`
- JetBrains Rider 2020.2.4
- Output of the 'dotnet --info':
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.300 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  5.0.100-preview.8.20417.9 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by javiercn** [comment]
@damla thanks for contacting us.

> * Templates created with SDK 5.0.100, ReactJS and Individual Identity has excess attribute, which is "asp-area="Identity", found in the cshtml file in the location above. The project does not have any area folder in it therefore, it is completely useless to have this attribute as a default.

The Identity UI library defines an "Identity" area in the RCL, so that file has the right code.

WRT to the missing space, that's a bug.

**Comment by damla** [comment]
Hi Javier,

I've checked it from VSCode and the errors are gone so I think the problem was about IDE. 

If it is okay for you guys, I can create a PR for the missing space. Thank you for taking your time.
