### ISSUE TITLE
SerilaizerSettings-Setter for MvcNewtonsoftJsonOptions

### ISSUE THREAD

**Issue by tsproesser** [dotnet/aspnetcore#27723]
Right now the serializer settings can only be adopted - no full instance can be set. E.g. for hubs this is possible (NewtonsoftJsonHubProtocolOptions).

```
newtonsoftJsonHubProtocolOptionsInstance.PayloadSerializerSettings = null; //possible
serilaizerSettings.SerializerSettingsInstance = null; // Exception - no setter
```

**Comment by BrennanConroy** [comment]
@pranavkm They are asking about MVC, saying that SignalR supports X and MVC doesn't seem to.

**Comment by pranavkm** [comment]
Closing as a dup of https://github.com/dotnet/aspnetcore/issues/27727.
