### ISSUE TITLE
SerializerSettings-Setter for MvcNewtonsoftJsonOptions

### ISSUE THREAD

**Issue by tsproesser** [dotnet/aspnetcore#27727]
It would be great if you could set the SerializerSettings-instance than rather just be able to adopt its settings:

`mvcNewtonsoftJsonOptionsInstance.SerializerSettings = null; //Not possible! Getter only!`

E.g. for the `NewtonsoftJsonHubProtocolOptions` it already is possible:

`newtonsoftJsonHubProtocolOptionsInstance.PayloadSerializerSettings = new JsonSerializerSettings(); //Works!`

**Comment by pranavkm** [comment]
@tsproesser thank you for your feedback. We have previously considered this suggestion and for the reasons described in https://github.com/aspnet/Mvc/issues/6816#issuecomment-329221624, we kept the current design.
