### ISSUE TITLE
Investigate fully trimming assemblies used in Blazor-wasm 

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/aspnetcore#27730]
Because of concerns around functionality and interop, the aspnetcore libraries are not fully trimmed. We should investigate doing so for the ones used in Blazor-wasm to see what kind of size savings this could produce and how much work it would be to enable.

**Comment by mkArtakMSFT** [comment]
This is a dupe of https://github.com/dotnet/aspnetcore/issues/27384

**Comment by mkArtakMSFT** [comment]
Reopening to track blazor-specific work as part of this.

**Comment by pranavkm** [comment]
All Blazor WASM assemblies have been annotated with trimmer attributes and marked as IsTrimmable=true as of preview4.
