### ISSUE TITLE
Consider treating BLAZOR102 as warning, not error

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#27731]
### Is your feature request related to a problem? Please describe.

Since the introduction of scoped CSS, having a file called `foo.razor.css` without also having a file in the same folder called `foo.razor` is now an error. This breaks my build (context: for pre-net5.0 I had my own library to do lazy loading for css, with the same convention of naming files. As part of the build process, css files are copied into wwwroot where they now live without the corresponding razor file. That's where the error now breaks the build).

### Describe the solution you'd like

Treating BLAZOR102 as warning rather than error wouldn't break builds.

Related: https://github.com/dotnet/aspnetcore/discussions/27729

**Comment by javiercn** [comment]
@stefanloerwald thanks for contacting us.

You can set `<EnableDefaultScopedCssItems>false</EnableDefaultScopedCssItems>` in your project and they won't be treated as scoped css files.

**Comment by stefanloerwald** [comment]
Sure, that works. Could you, @javiercn, please also comment on #27729?  Thanks
