### ISSUE TITLE
Testserver seems to handle Urls with escaped path segements wrong and won't work with url encoded '/'

### ISSUE THREAD

**Issue by ckuetbach** [dotnet/aspnetcore#27743]
### Different behaviour in Url Handling between TestServer and Server
The Testserver seems to handle escaped path segements wrong or at least different, than the real implementatio of the Kestrel Server.

If you have a pathsegement with an escaped ``a/b`` (``a%2Fb``), than the TestServer will not find the correct controller.

### To Reproduce

I've created a small test project:

1. checkout https://github.com/ckuetbach/DotnetUrlEscapingBug/
2. run all Tests in BasicTests
3. compare the expectation and the actual values

- Get_With_Keys_In_Query -> This works fine, the escaped char is within a query parameter
- Get_With_Keys_In_Path_TestServer -> This test fails, because the ``a%2fb`` seems to be unescaped _before_ the route is determined and the server returns an 404
- Get_With_Keys_In_Path_Server -> this test also fails, but in this case the controller gets the unescaped path. I'm not really sure, whats the expected bahaviour here.

```
EscapeTest.BasicTests.Get_With_Keys_In_Path.Get_With_Keys_In_Path(url: "/api/values", id: "a/b")

System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
```

The real implementation has a different error. It will handle the url escaping different. I think this behavior is also wrong.
```
EscapeTest.BasicTests.Get_With_Running_Web_Project.Get_With_Running_Web_Project(url: "http://localhost:5000/api/values", id: "a/b")

Xunit.Sdk.EqualException
Assert.Equal() Failure
           ↓ (pos 1)
Expected: a/b
Actual:   a%2fb
```

### Further technical details
- ASP.NET Core version

Version 2.1

- Include the output of `dotnet --info`
PS C:\Projekte\Spielwiese\Escape> dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.811
 Commit:    a9da00fd20

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.811\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.811 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Rider 2020.2

**Comment by ckuetbach** [comment]
This bug may be related to another one witin the OData framework: 
https://github.com/OData/WebApi/issues/2309

**Comment by Tratcher** [comment]
Those two tests construct the url differently, one being relative and the other absolute. Construct a full System.Uri that includes the scheme, host, port, and path and pass that to HttpClient in each test to make sure you're comparing the same inputs.

Also, why are you calling HttpUtility.UrlEncode(id) as part of the url construction? For the test input you should be passing hard-coded values.

**Comment by ckuetbach** [comment]
I've changed the tests to create the Uri simliarly. They are created with BaseAddress, to mimic the Testservers HttpClient, which is implemented like that.

Also I've removed the UrlEncode and made the values hard-coded. I initially thought, the test would be better readable with the unescaped values.

This didn't change the behaviour.

**Comment by Tratcher** [comment]
As part of https://github.com/dotnet/aspnetcore/issues/28965 we were able to track this down to an issue in PathString.FromUriComponent. Closing this as a duplicate since that one has the analysis.
