### ISSUE TITLE
Issue when publishing blazor app with dotnet.wasm.gz 5.0.0

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/aspnetcore#27741]
I have problem with dotnet.wasm.gz file. The file is kind of corrupted leading to this error in the browser.

```
blazor.webassembly.js:1 Error: Failed to start platform. Reason: RuntimeError: memory access out of bounds
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.throw (blazor.webassembly.js:1)
    at s (blazor.webassembly.js:1)

blazor.webassembly.js:1 Uncaught (in promise) Error: Error loading ICU asset.
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.next (blazor.webassembly.js:1)
    at a (blazor.webassembly.js:1)
```

I spend 3 hours digging in this. I publish the app from a build machine that had dotnet 5.0.100-rc2. I updated the sdk in this build-machine to 5.0.100. This build machine published the app successfully before update. Now it produce a different dotnet.wasm.gz file from the one that my dev machine produces. The blazor-app is hosted in aspnetcore app in a Linux Machine with nginx in front. 

If I delete dotnet.wasm.gz file from the published folder the error goes away. If I put the dotnet.wasm.gz from my machine it also works. 

The publish command I  run is 

```
dotnet publish --configuration release --output C:\xxxx\output /property:Version=1.0.20316.10327

```

**Comment by xrkolovos** [comment]
Update:
I have a second Build Machine, that I do the updates the same time that it produce the right dotnet.wasm.gz and the app works.

Also, I uninstalled the dotnet sdk and reinstalled it (in the first build machine) but the problem remains.

**Comment by xrkolovos** [comment]
Do you want to provide the 2 dotnet.wasm.gz?
Is there a way to clean - reinstall the tool that does the zip?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @xrkolovos.
Try to clean the solution (remove `bin` and `obj`) that may help.

Other than that this seems to be some kind of an issue specific to that machine. And unfortunately there is nothing else we can think of right now. If you still face this issue, try to ask in StackOverflow.

**Comment by HeroSpha** [comment]
Im also facing the problem, in my case it happens when https is used, but when the application is not secure i dnt get any error. 
This is happening in production
the site with error [www.azaniabooks.com](url)

errors im getting
`Failed to start platform. Reason: RuntimeError: memory access out of bounds`
`Error: Error loading ICU asset.`

**Comment by xrkolovos** [comment]
> Thanks for contacting us, @xrkolovos.
> Try to clean the solution (remove `bin` and `obj`) that may help.
> 
> Other than that this seems to be some kind of an issue specific to that machine. And unfortunately there is nothing else we can think of right now. If you still face this issue, try to ask in StackOverflow.

this didn't help. Should I clean nuget cache? Something else? Which component does the gz?

**Comment by xrkolovos** [comment]
Hello 
Can you tell us what we need to reinstall to have the component that does the compression reinstalled?

**Comment by AmirImam** [comment]
I have the same issue in one project (blazor wasm .net5)
any ideas here ?
