### ISSUE TITLE
[Blazor] Cannot create Nuget package if files exist inside wwwroot

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#27740]
### Describe the bug
I have a repro that is simply a razorclasslib with multiple target frameworks. When it builds there is an error

NU5118	File 'D:\Temp\blazor-package-error\Source\Fluxor.Blazor.Web\wwwroot\scripts\index.js' is not added because the package already contains file 'staticwebassets\scripts\index.js'	Fluxor.Blazor.Web	C:\Program Files\dotnet\sdk\5.0.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	207	

### To Reproduce
1. Download the repro https://github.com/mrpmorris/blazor-package-error
2. CD into the Source folder
3. Run `dotnet build` or build it in VS

**Comment by MarkStega** [comment]
I also have a dual environment library (NS2.1 & N5.0). I get a lot of the NU5118 warning when I build the nuget package. As far as I can tell, though, the package seems to be able to be consumed in either DNC3.1 or DN5.0 environments with all assets resolved.

**Comment by mrpmorris** [comment]
I have warnings as errors. So I'll need to set an ignore then?

**Comment by MarkStega** [comment]
If you have /warnaserror on that build step you'll have to take it off; I don't know of a way to suppress only certain warnings.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
I believe this error is what we've added intentionally to avoid having conflicting static assets in your app.
If this is the case (@javiercn can you confirm?) that means the file you're getting an error for exists in both your app as well as in one (or more) of its dependencies as a static asset.

**Comment by mrpmorris** [comment]
@mkArtakMSFT That is not the case, please look at the repro. There is 1 project with 1 file in wwwroot - but there are multiple TargetFrameworks in the csproj file

**Comment by JeremyCaney** [comment]
It's worth noting that while this issue is titled and labeled with ![area-blazor](https://img.shields.io/github/labels/dotnet/aspnetcore/area-blazor), it actually affects _any_ Razor Class Library (RCL) that contains static content. Technically, that can include RCLs targeting .NET Core MVC or Razor Pages.

**Comment by SteveSandersonMS** [comment]
Needs verification in RC2

**Comment by javiercn** [comment]
This appears to have been fixed in RC1

![image](https://user-images.githubusercontent.com/6995051/130077189-ed129841-3c63-4b4d-ab6c-03edd61bf1cc.png)

I've added a test to make sure we don't regress this.

**Comment by javiercn** [comment]
@mrpmorris try with the latest RC1 (when its available) or with the nightly RC1 from dotnet/installer.

I'm unable to access your repro, so I can't try with it.
