### ISSUE TITLE
Signal R Not Working With Web Assembly .net 5.0

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#27754]
I have a sample project where I use the Microsoft.AspNetCore.SignalR.Client nuget package.
I use the version 5.0.
When using the older version or web assembly it works fine.  However, when I try to use under .net 5, it thinks it cannot run some browser stuff.

Here is the sample code.

 public class SampleClass
    {
        public void RunTest()
        {
            HubConnection hub = new HubConnectionBuilder().WithUrl("https://localhost:5001").Build();
        }
    }

public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            SampleClass aa = new SampleClass();
            aa.RunTest();
            await builder.Build().RunAsync();
        }

Everything else was default from the template.
When I run under the web assembly 3.1, it works fine.
However, when I run under .net 5, gives a runtime error immediately.  That is with no extra code.

Is there a way for signal r to work with web assembly under .net 5.  I would be really disappointed if web assembly no longer supports signal r.   This would really hurt because it would mean that if somebody wanted to create any chat applications that needs signal r, they cannot do under .net 5.  I hope either can be fixed or a workaround for it.

**Comment by BrennanConroy** [comment]
Can you share the error please.

**Comment by musictopia2** [comment]
![Error](https://user-images.githubusercontent.com/39104606/98950493-4a0dd380-24b6-11eb-92c2-2bdfb088be8b.png)

This is a screenshot of the errors from the simple app.  Ran the same thing with the old version of blazor and did not have any problems.

**Comment by BrennanConroy** [comment]
@pranavkm could you take a look?

Have you tried cleaning your project and rebuilding?

**Comment by musictopia2** [comment]
![Error](https://user-images.githubusercontent.com/39104606/98973040-78001180-24d0-11eb-98e7-dff5848d7e97.png)
When I do a clean and rebuild, i get a different error.  But still does not work.

**Comment by musictopia2** [comment]
Forgot to mention I put a screenshot of the new errors that occur after doing a clean and rebuild.

**Comment by BrennanConroy** [comment]
Are you using the 5.0 RTM SignalR client? That looks like an error that would occur with either a 3.1 client or a preview 5.0 client.

**Comment by musictopia2** [comment]
If you would like a repository, I can post on github as well.  I created this sample because when I upgraded a project to net 5, i ran into the same issue.  After doing lots of experimenting and trial/error, by creating a simple project that started with .net 5 and having the same issue and knowing i am using the tech in my project, then that was the issue.

**Comment by BrennanConroy** [comment]
> If you would like a repository, I can post on github as well.

That would help, but first can you double check the version of the SignalR client you're using

**Comment by musictopia2** [comment]
This happened with all versions of signal r.  First, it happened with 5.0.  Then I dropped down to 3.1.10 and same issue.  However, the issues did not happen with older versions of web assembly.

**Comment by musictopia2** [comment]
The package reference was this
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.10" />

**Comment by musictopia2** [comment]
Tried to copy the reference but it ignored it.  The app this happened to was a web assembly but aspnet core hosted though.

**Comment by pranavkm** [comment]
@musictopia2 could you update to the 5.0 version of the NuGet package:

`<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.0" />`?

**Comment by musictopia2** [comment]
Looks like the reason I had the problem when I used that version was because I also had to do a clean and build solution.  This means the 5.0.0 worked with .net 5 web assembly with no problem.  One question?  Would that also work with .net standard 2.1 libraries?  Because I still have xamarin forms that needs to use those libraries which does not support .net 5.

**Comment by BrennanConroy** [comment]
> Would that also work with .net standard 2.1 libraries?

The signalr client works with .net standard 2.1.
