### ISSUE TITLE
.NET 5 Blazor WS with org auth creates duplicate app registrations?

### ISSUE THREAD

**Issue by jasonshave** [dotnet/aspnetcore#27755]
### Describe the bug
When creating a new .NET 5 Blazor WS app with organizational authentication enabled there are two seemingly duplicate app registrations in AAD.

### To Reproduce
1. Follow the steps in VS2019 to create a new .NET 5 Blazor WebAssembly project and choose to enable authentication.
2. Click OK to create the project.
3. Log into AAD and locate the application registration(s)
4. Observer the authentication, secret, token settings, manifest, grant-type, etc. are all the same between the two

![image](https://user-images.githubusercontent.com/28457536/98884940-59f1cd00-244e-11eb-846d-d7f8d36e067b.png)

I would expect the app to only create one, or if the purpose is to have a registration for a server and client, for them to be aptly named (<projectname_client> and <projectname_api>).

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

- Visual Studio 2019 (16.8.0)

**Comment by jasonshave** [comment]
Just noticed this: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0.

I'm assuming it's a know issue?

**Comment by mkArtakMSFT** [comment]
Correct, this is indeed a known issue. Thanks for contacting us.
