### ISSUE TITLE
.NET 5 Blazor web assembly app can't log in (token failed)

### ISSUE THREAD

**Issue by jasonshave** [dotnet/aspnetcore#27757]
### Describe the bug
I'm testing the new .NET 5 Blazor WebAssembly template with organization authentication enabled and have observed my app registration is created in AAD (actually it creates two of them #27755). When trying to log in I get the UI prompt to authenticate, then it hangs. If I close the window and refresh the page I notice token fetch errors in F12.

### To Reproduce
1. Create a regular .NET 5 Blazor WebAssembly (non-hosted) project and enable organizational authentication.
2. Start the web page in Visual Studio 2019 (debug mode)
3. Click the Log in button in the top navbar
4. Authenticate, and click Sign In
5. Observe the authentication window turn grey and hang
6. Hit F12 then F5 to reload the page
7. Observe the authentication window appear then disappear
8. Observe the following error:

![image](https://user-images.githubusercontent.com/28457536/98885677-b1dd0380-244f-11eb-877c-9452902cc075.png)

### Exceptions (if any)
Getting a token (failed) status on AuthenticationService.js:32 as seen in the image above.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

- Visual Studio 2019 (16.8.0)

**Comment by jasonshave** [comment]
Following this guide, I was able to get it to work: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-5.0

**Comment by vpekarek** [comment]
I think it is the global problem with .NET 5.0 authentication. I need to add this (before calling `services.AddAuthentication()`) to my API projects, to be able to handle authentication:

```
var keyFolder = Path.Combine(Directory.GetCurrentDirectory(), "keys");

if (!Directory.Exists(keyFolder))
{
    Directory.CreateDirectory(keyFolder);
}

var directoryInfo = new DirectoryInfo(keyFolder);

services
    .AddDataProtection()
    .PersistKeysToFileSystem(directoryInfo);
```

In this case, it will store keys in the app folder, and don't need any other permission on IIS.

Somebody says, that need to change the pool identity to user with higher privileges, but I do not like that solution.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @jasonshave. Glad that you've resolved your issue.
@vpekarek if you are facing some other problems, please file a separate issue.
