### ISSUE TITLE
.NET 5 Blazor WebAssembly project template w/org auth creates deprecated AAD graph permission

### ISSUE THREAD

**Issue by jasonshave** [dotnet/aspnetcore#27759]
### Describe the bug
Creating a new .NET 5 Blazor WebAssembly project with orgnaizational authentication sets up API permissions to use the "deprecated" Azure Active Directory Graph permission vs. "Microsoft Graph API" permission.

### To Reproduce
1. Create a regular .NET 5 Blazor WebAssembly project with organizational authentication
2. Sign into AAD and locate the app registration
3. Click on API permissions
4. Note the warning about using deprecated permissions for AAD Graph vs. Microsoft Graph API

![image](https://user-images.githubusercontent.com/28457536/98886412-41cf7d00-2451-11eb-90c6-7b1a2cc4ea9a.png)
![image](https://user-images.githubusercontent.com/28457536/98886355-25cbdb80-2451-11eb-906f-d260a64641f9.png)

I would expect the template to choose the newer API unless there is a reason?

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

- Visual Studio 2019 (16.8.0)

**Comment by blowdart** [comment]
It will get there eventualy. It needs some work from VS in order to do so, which is scheduled, but isn't complete unfortunately.

cc @jmprieur

**Comment by mkArtakMSFT** [comment]
Thanks @blowdart.
Closing as there is no pending work on our end here.
