### ISSUE TITLE
Unable to debug client-side Blazor WebAssembly hosted by ASP.NET Core inside a Docker container

### ISSUE THREAD

**Issue by NCC1701M** [dotnet/aspnetcore#27766]
Hi @javiercn

Any progress on #22092 ?

I guess this will be a crucial point for teams using dev containers and considering to switch to blazor web assembly. This could stop them from switching.

Is there another way to debug blazor web assemblies? Maybe using the F12 Devtools? I couldn't see anything there as well.

**Comment by javiercn** [comment]
@NCC1701M thanks for contacting us.

This is not something that we've made progress on as far as I'm aware, but @captainsafia will know more.

**Comment by captainsafia** [comment]
@captainsafia We're planning on shipping this alongside 16.9/.NET 6. If you're interested in this feature, I'd recommend watching the change logs for .NET 6 previews to try out the change once it ships.

We're tracking this in #22587 for VS Code. Closing this in favor of that issue.

**Comment by schaveyt** [comment]
Wonder if this issue might fix what I'm run into...

I'm on a a Chromebook and its Linux container installed. Everything has been fairly smooth installing net5.0 and even vscode. I then generated the vanilla blazorwasm project and hit F5. Things compiled successfully and when to vscode went to launch and boom! Omnisharp can't find/launch chrome....cuz it is found in the host environment and not in the linux container.

Thoughts?

**Comment by captainsafia** [comment]
@schaveyt Sounds like it! Support for debugging in Docker containers boils down to making sure that the Chrome browser and debugging proxy are launched in the host machine and not in the remote environment.
