### ISSUE TITLE
Scoped CSS is active in netcoreapp3.1 apps

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#27768]
### Describe the bug

Even though scoped CSS is supposed to be a net5.0+ only feature, it is clearly (at least partially) active in projects targetting netcoreapp3.1.

### To Reproduce

1. `dotnet new blazorserver -f netcoreapp3.1`
2. `echo "" > foo.razor.css`
3. `dotnet build`

We would expect a build success without scoped CSS, as a file called `foo.razor.css` should have absolutely no effect.

However, we get the scoped-CSS-related error

> error BLAZOR102: The scoped css file 'foo.razor.css' was defined but no associated razor component was found for it.

@javiercn identified the issue [here in a GH discussion](https://github.com/dotnet/aspnetcore/discussions/27729#discussioncomment-127207) as originating from https://github.com/dotnet/aspnetcore/blob/master/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L76

### Workaround until fix is available

As @javiercn mentioned, scoped CSS can simply be deactivated in affected projects by adding `<ScopedCssEnabled>false</ScopedCssEnabled>` to the csproj.

**Comment by SteveSandersonMS** [comment]
We don't think this is likely to cause problems since people would not have `.razor.css` files if targeting older frameworks, hence closing.

**Comment by stefanloerwald** [comment]
Not quite true, because there have been solutions similar to scoped CSS before net5.0, which involved .razor.css files, but since it only concerns practically obsolete old frameworks, I'm not going to disagree with just ignoring this ;-)
