### ISSUE TITLE
Blazor doesn't seem to support code flow with PKCE against Azure B2C

### ISSUE THREAD

**Issue by chrissainty** [dotnet/aspnetcore#27769]
### Describe the bug
To my understanding code flow with PKCE is now the recommended best practice for securing SPA applications. When trying to use code flow with PKCE to authenticate users against Azure B2C in a Blazor WebAssembly application, the request fails with the following error.

![b2c-error](https://user-images.githubusercontent.com/6171719/98918051-0ec6d100-24c5-11eb-80b7-34fce6be3b10.jpg)

I believe the underlying version of MSAL (v2) Blazor uses supports code flow with PKCE, but Blazor doesn't seem to generate the `code_challenge` query string when redirecting to B2C. 

### To Reproduce
Create a new Blazor WebAssembly application with Azure B2C authentication. Enable code flow with PKCE in the app configuration in Azure B2C.

### Further technical details
Version: .NET 5

**Comment by javiercn** [comment]
@chrissainty thanks for contacting us.

We do support Code+PKCE against Azure AD B2C, I would suggest you check your configuration to make sure that the redirect url is registered as a "SPA" redirect URL and to make sure you clean caches and so on to ensure you load the latest version of the library (5.0) which contains the updated msal version.

The demo that Dan and I did for dotnetconf 2020 does auth on blazor webassembly using msal and Code + PKCE using 5.0 RTM, so I'm going to close this issue for now, but if after checking everything (or trying with a new empty template) you still cannot get it to work, let us know and we can take a look in more depth.

**Comment by chrissainty** [comment]
Thanks for the response @javiercn. I've just tested it again and you're correct, everything is working as expected. It must have been a caching issue, we've experienced quite a few of those so it would make the most sense. 

Apologies for wasting your time on this one.

**Comment by javiercn** [comment]
@chrissainty no worries, I had my fair share of hiccups with it too.
