### ISSUE TITLE
Microsoft.AspNetCore.Mvc Reference In Project Causes Blazor WASM Issues

### ISSUE THREAD

**Issue by fafafooey916** [dotnet/aspnetcore#27779]
Good Morning,

I am trying to start a Blazor WASM application; I have the latest .NET 5 installed, VS2019 16.8, etc. I have existing projects that will be referenced in both of the Blazor generated projects *.Client && *.Server. The .Server project handles the project references without issue. But, the .Client project is having issues with my "Library" project. When I add the project reference, I am getting these build errors:

The type or namespace name 'ApplicationPartAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ApplicationParts' (are you missing an assembly reference?)

The type or namespace name 'ApplicationPartAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ApplicationParts' (are you missing an assembly reference?)

I've since gone nearly file by file, class by class, in the "Library" project to narrow down the issue: name reference and usage of Microsoft.AspNetCore.Mvc will cause this build error. Excluding these files or methods utilizing the namespace and then rebuilding the .Client project, solves the issue.

I've installed the Microsoft.AspNetCore.Mvc and Microsoft.AspNetCore.Mvc.Core nuget packages on the .Client project, and no change. All projects in the solution are running on .NET 5. These links speak about the issue and a sort of "fix" for it:

https://github.com/dotnet/aspnetcore/issues/21849#issuecomment-662030144
https://github.com/dotnet/aspnetcore/issues/24171
https://github.com/dotnet/aspnetcore/issues/25380

When I was using the 16.8 Preview, I implemented this "fix", but debugging the Blazor project was a nightmare. Oddly, I've not found much info regarding this issue and why it is happening nor any true ways to fix it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please refer to the 5.0 migration instructions to make sure you've properly updated your projects: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio
If you're still facing this issue, share your project file.

**Comment by fafafooey916** [comment]
This is my .csproj file for the referenced Library project:
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SQL\**" />
    <EmbeddedResource Remove="SQL\**" />
    <None Remove="SQL\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Extensions\BababooeyWebExceptionMiddleWareExtensions.cs" />
    <Compile Remove="Extensions\ControllerExtensions.cs" />
    <Compile Remove="Extensions\GenericWebObjectExtensions.cs" />
    <Compile Remove="Extensions\ModelStateExtensions.cs" />
    <Compile Remove="Extensions\TempDataExtensions.cs" />
    <Compile Remove="Helpers\ADONet.cs" />
    <Compile Remove="MiddleWare\BababooeyWebExceptionMiddleWare.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.mvc" Version="2.2.0" />
    <PackageReference Include="microsoft.aspnetcore.mvc.core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.tokens" Version="6.8.0" />
    <PackageReference Include="System.DirectoryServices" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>

This is what is in a brand new .Net 5 Blazor .Client project:
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Bababooey.Libraries\Bababooey.Libraries\A16092\Bababooey.Library.NET\Bababooey.Library.NET.csproj" />
    <ProjectReference Include="..\Shared\BlazorTesting.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

</Project>

**Comment by mkArtakMSFT** [comment]
Thanks for the details.
It looks like you're trying to reference an ASP.NET MVC app from a Razor Class library, which is not supported.

**Comment by fafafooey916** [comment]
Thank you for the feedback.

Its not an MVC application, just a code library that has references to the AspNetCore.Mvc namespace; code for ActionExecutingContext, ModelState stuff, etc.

I've since broken up the library to remove the .Mvc stuff and put that into a accompanying library, just so I can get going.
