### ISSUE TITLE
No Component Completions in VS Codespaces

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27777]
![image](https://user-images.githubusercontent.com/14852843/98968630-e8606000-24db-11eb-811a-dc3152400fc7.png)

Repro:
1. `dotnet new blazorserver`
2. Create component by, right click, add new file
3. Go to `Counter.razor` and try to type out that component -> no completions

Strangely, this doesn't work after I restart the VS Codespaces window either.

2.5. if the above doesn't repro, put component in different namespace -> `@namespace OtherNamespace`

**Comment by TanayParikh** [comment]
cc/ @NTaylorMullen as it's a concerning regression. Based on the behavior, I suspect this may be a scaffolding issue wherein the newly created file isn't "registered" with the project.

**Comment by TanayParikh** [comment]
Possibly related to: https://github.com/dotnet/aspnetcore/issues/27819

**Comment by NTaylorMullen** [comment]
This still an issue?

**Comment by TanayParikh** [comment]
Appears so: 
![image](https://user-images.githubusercontent.com/14852843/100801625-3fc86080-33f6-11eb-93e1-e1390a12ddd9.png)

however I believe you'd tried this before and it was working for you.

**Comment by ajaybhargavb** [comment]
Just tried this out. I am getting correct component completions using the following versions,
![image](https://user-images.githubusercontent.com/1579269/100806382-32ef4100-33e5-11eb-8300-a8ec6a6c58da.png)

I guess my client version is out of date but I assume it shouldn't matter as much as the server. I am updating my client now.

**Comment by ajaybhargavb** [comment]
Tried it out with a newer client and it still works,
![image](https://user-images.githubusercontent.com/1579269/100809022-1d304a80-33ea-11eb-9113-455c414afa14.png)

Closing this out.
