### ISSUE TITLE
Check if it's a new session or a timeout

### ISSUE THREAD

**Issue by stesvis** [dotnet/aspnetcore#27788]
Hello, I am using the latest version of .net core and I can't find a way to determine if it's a new session or an expired session.
I am doing this:
```
services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromSeconds(30);
    options.Cookie.HttpOnly = true;
    options.Cookie.IsEssential = true;
});
```

and then I added:
```
app.UseSession();
```

It works fine, because after 30 sec of inactivity i am redirected to the LogIn page.
BUT, in the LogIn page, how can I find out if the page is loaded by a new session or by a timed out session?

Basically, how can I determine wheter to show a "Your session expired" message or not?

**Comment by Tratcher** [comment]
_Session should not be used for authentication._ Use the CookieAuthentication components for that.

The only way to distinguish between an expired session and a new one is if the request has a session cookie. There's no property for this on Session, you'd need to check the request cookies collection directly.
