### ISSUE TITLE
How correctly use with Next.js

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27781]
---
**Issue moved from SignalR/SignalR#4509**
- Please respond to @pavelvondrasek.

---

_From @pavelvondrasek on Thursday, November 12, 2020 3:12:20 PM_

Hi,

I've backend in ASP.NET Core 3.1 and on the frontend I've Next.js 10.

I create hub in useEffect which is called only once (is memoized by []):

```ts
  useEffect(() => {
    if (props.node?.permission.canEdit) {
      const connection = new signalR.HubConnectionBuilder()
        .withUrl(`${process.env.BACKEND_URL}/api/node-hub?node=${props.node.id}`)
        .withAutomaticReconnect()
        .build();
    }
  }, []);
```

But in console I see multiple (mostly two) negotiation requests and successful connections. Is it ok?

Every with new `connectionId` and `token`.

Did I something wrong?

Thanks for you reploy and hints!
Pavel

**Comment by BrennanConroy** [comment]
The code you are showing is incomplete and would not cause any network calls. Can you share more?

This is likely an application bug and not a library bug. You are likely creating multiple connection objects accidentally, but it's impossible to say from your code snippet.

**Comment by pavelvondrasek** [comment]
Ah, sorry.

Here is all code:

```ts
  useEffect(() => {
    if (props.node?.permission.canEdit) {
      connection = new signalR.HubConnectionBuilder()
        .withUrl(`${process.env.BACKEND_URL}/api/node-hub?node=${props.node.id}`)
        .withAutomaticReconnect()
        .build();

      connection.start().catch(error => console.log(error));
    }
  }, []);
```

I think it's caused by automatic reconnect. Withou reconnect I normally reload page and connection is created only once.

**Comment by BrennanConroy** [comment]
So if you remove `.withAutomaticReconnect()` there is only one connection?

Is there only 2 connections if you reload the page? i.e. if you open the page for the first time how many connections are created?

**Comment by pavelvondrasek** [comment]
Yes, with remove there is only one connection and with every page reload is created.

**Comment by pavelvondrasek** [comment]
Yes, with remove there is only one connection and with every page reload is created.

If I open page for the first time there is only one connection in console:
[2020-11-12T18:28:07.430Z] Information: WebSocket connected to wss://localhost:5003/api/node-hub?node=628&id=vkAT3fDWHbGln8wez8cOlQ.

For the second time:

[2020-11-12T18:29:20.153Z] Information: Connection disconnected. Utils.js:224
[2020-11-12T18:29:20.362Z] Information: WebSocket connected to wss://localhost:5003/api/node-hub?node=628&id=qBOdyR8k2FwpuDy1u6b7Ug. Utils.js:224
[2020-11-12T18:29:23.669Z] Information: WebSocket connected to wss://localhost:5003/api/node-hub?node=628&id=l2jzbBb1wzQN2sjR3ElQ9w.

And without reconnect for every page reload in console is:
[2020-11-12T18:30:37.017Z] Information: Connection disconnected. Utils.js:224
[2020-11-12T18:30:40.552Z] Information: WebSocket connected to wss://localhost:5003/api/node-hub?node=628&id=NMh4bNf6_qmTtaI3-vZS4g.

Maybe connection live between pages reload and with reconnection it recreate connection and second connection is my connect in code in useEffect which is fired during page load in browser? I don't know.

**Comment by BrennanConroy** [comment]
> Maybe connection live between pages reload and with reconnection it recreate connection and second connection is my connect in code in useEffect which is fired during page load in browser?

That's what it seems like. Is there some unload event you're supposed to hook into and call stop on the connection?

**Comment by BrennanConroy** [comment]
The docs show you should return a cleanup function.

https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1
```
return function cleanup() {
    ChatAPI.unsubscribeFromFriendStatus(props.friend.id, handleStatusChange);
};
```

**Comment by pavelvondrasek** [comment]
Ok, so that you recommend me implement cleanup with `connection.stop()`?

Yes, I think it will work :) I'm going to try it.

I thought that it's handled by signalr that with reconnect I don't have to worry about connection :)

Because I know nothing about ws and singalR so that I did what was in docs here: https://docs.microsoft.com/cs-cz/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-5.0&tabs=visual-studio

Maybe it should be in documentation or in examples on Next.js repo: https://github.com/vercel/next.js/tree/canary/examples (I can prepare example if you want and open PR to next.js examples)

Thank you! :)

**Comment by pavelvondrasek** [comment]
Yes, I tested it and this works great:

```ts
  useEffect(() => {
    if (props.node?.permission.canEdit) {
      connection = new signalR.HubConnectionBuilder()
        .withUrl(`${process.env.BACKEND_URL}/api/node-hub?node=${props.node.id}`)
        .build();

      connection.start().catch(error => console.log(error));

      return () => {
        connection.stop();
      };
    }

    return;
  }, []);
```

Thank you!

**Comment by BrennanConroy** [comment]
> Maybe it should be in documentation or in examples on Next.js repo: https://github.com/vercel/next.js/tree/canary/examples (I can prepare example if you want and open PR to next.js examples)

Go for it, we don't own that repo 😄
