### ISSUE TITLE
After the ASP.NET Core 5.0 WebApi project is published, the interface document cannot be displayed or requested on the page after being launched by the command line

### ISSUE THREAD

**Issue by jinx429** [dotnet/aspnetcore#27798]
#19570 # Describe the bug
The ASP.NET Core 5.0 WebAPI project that we wrote was ready to be launched in VS and used postman's request interface and see the interface document,but, when I release the release, launch it with the following command --"dotnet IAIOT_alpha_api_0_5.dll --urls="http://*:80" --ip 127.0.0.1 --port 80",When it started, the command line sent out a message indicating which port it was bound to, though I couldn't reach the page using a browser, and postman couldn't ask for the interface

### Further technical details
-The version is :.ASP.NET Core 5.0
- The IDE is VisualStudio 2019 and version is 16.8.1

**Comment by jinx429** [comment]
I don't know how to add area-servers，Could you please provide the relevant documentation or how to add area-servers

**Comment by jkotalik** [comment]
I think we need more info here. Are you running that command on commandline? Were you able to bind to another port besides 80?

Logs and a reproducable sample would help speed up this investigation as well.

**Comment by jinx429** [comment]
I can bind to ports other than 80 and the console log output also has no exceptions or error messages.My first guess is that something went wrong when I was building the project.Can give me some advice on generating options
