### ISSUE TITLE
.NET Standard 2.0 library with Microsoft.AspNetCore.Mvc.Razor package could not load type CompilationFailedException at run time

### ISSUE THREAD

**Issue by abuzaforfagun** [dotnet/aspnetcore#27809]
### Describe the bug
I have updated my .net core 2.2 application to .net core 3.1. Inside that application we using Razor pages. The logic relates to razor pages are inside a .net standard class library. And that library referred by the Web API project.

After migrating the application to 3.1. I have added the **Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation** package and added the code snipet inside startup class.
`services.AddRazorPages();
            services.AddControllersWithViews().AddRazorRuntimeCompilation();`

Inside our library project we have a class containing the try-catch block, like below:

`try
            {
                _fileProvider.AddTemplate(templateId, content);
                 var findViewResult = _viewEngine.FindView(actionContext, templateId, true);
            }
            catch (CompilationFailedException e)
            {
                throw new ValidationException(e.Message);
            }`

Everything looks good during the compile-time and we are getting an exception on the runtime.
So far my understanding is: .NET Core 3.1 containing a dll named `Microsoft.AspNetCore.Mvc.Razor`. And the version of that dll is 3.1.9.0. And because of this, it ignores the version in the library project. And the version 3.1.9.0 does not contain `CompilationFailedException` class.
### To Reproduce

- Create a .net core 3.1 Web API application.
- Add Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation from nuget package. I used the version 3.1.9.
- Add following code snipet inside Startup class.
`services.AddRazorPages();
            services.AddControllersWithViews().AddRazorRuntimeCompilation();`
- Create a class library and install Microsoft.AspNetCore.Mvc.Razor from nuget.
- Create a class containing the code below:
`{
                _fileProvider.AddTemplate(templateId, content);
                 var findViewResult = _viewEngine.FindView(actionContext, templateId, true);
            }
            catch (CompilationFailedException e)
            {
                throw new ValidationException(e.Message);
            }`
- Call that class from the web api project.
### Exceptions (if any)

Could not load type 'Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException' from assembly 'Microsoft.AspNetCore.Mvc.Razor, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Visual Studio 2019 16.8.0

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by abuzaforfagun** [comment]
Hello @mkArtakMSFT please take a look over this repository https://github.com/abuzaforfagun/RazorBugReproduction

**Comment by pranavkm** [comment]
@abuzaforfagun your app references a 2.2 version of the ASP.NET Core framework and packages: https://github.com/abuzaforfagun/RazorBugReproduction/blob/master/RazorBugReproduction/RazorBugReproduction.csproj#L4. 2.2 has been [out of support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for a while now and we recommend updating to a supported release.

**Comment by abuzaforfagun** [comment]
@pranavkm sorry, I added this by mistake. But I have removed that project. And now it is containing dotnetcore3.1. https://github.com/abuzaforfagun/RazorBugReproduction/blob/master/WebAPI/WebAPI.csproj . Still now youcan reproduce the issue.

**Comment by abuzaforfagun** [comment]
This should not be closed. You can regenerate the issue in .net core 3.1. Can you please take a look @pranavkm
