### ISSUE TITLE
Blazor WASM loss of connection to the server

### ISSUE THREAD

**Issue by otopotom** [dotnet/aspnetcore#27801]
The app is published on iis, the server has two network interfaces, one of them is a corporate network, the second is the Internet. If the user is logged in from the first network, then requests to the server do not work in the second network, and Vice versa. After restarting the site pool, the network from which the user connects is running. Authorization works everywhere and always.

### Describe the bug

![FailRequest](https://user-images.githubusercontent.com/74389582/99037580-89bbe480-25b6-11eb-8978-109f47f64e49.jpg)

### Further technical details
- ASP.NET Core version 5.0

**Comment by javiercn** [comment]
@otopotom thanks for contacting us.

I don't see how there's anything specific to Blazor Webassembly here. I would suggest you check if the tokens are being included in the requests?

**Comment by otopotom** [comment]
In requests, I don't really pass the token, and this works until the user connects to the site via a different network interface. I find it strange to pass a token in a request every time. Maybe there is another solution?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
