### ISSUE TITLE
Updating object in csharp with data that came from JSInterop not re-rendering

### ISSUE THREAD

**Issue by starl1n** [dotnet/aspnetcore#27807]
### Describe the bug
Hi, I have a simple component let's say it list some customers that came from IndexedDB, I can retrieve the data perfectly fine, even see the object get the value if put some breakpoints, but the component is not re-rendering after it get the data update.

for simplicity:
```
@inject IJSRuntime js
@foreach(var item in Data)
{
<h5>@item.Name</h5>
}
 @code{
protected List<CustomerModel> Data { get; set; }
    protected override  async Task OnAfterRenderAsync(bool firstRender)
    {
        Data = await js.InvokeAsync<List<CustomerModel>>("Database.get", "customers");
  
    }
}
```

Running Blazor on dotnet 3.1, is there something I'm missing here?

I don't know if this is the right place to post the question

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@starl1n thanks for contacting us.

The current behavior is by design. We don't automatically re-render within OnAfterRender(Async), otherwise we would be introducing an infinite rendering loop. You need to call `StateHasChanged` yourself in this case.

**Comment by starl1n** [comment]
Copy @javiercn thank you for the clarification, StateHasChanged() was the missing part
