### ISSUE TITLE
Mismatch version numbers in NET 5 Web Project

### ISSUE THREAD

**Issue by ravenet** [dotnet/aspnetcore#27810]
Hi,

I have created a new .NET 5 Web application and however when I add class library using .NET 5 to create tag helpers, it is reference Razor from version 2.2.0 instead of 5.0.0. It is very confusing.

![image](https://user-images.githubusercontent.com/6859970/99071894-1abaac00-2607-11eb-9a8a-62b268e45158.png)

Any idea that will be updated to 5.0.0 or how we can fix it?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The project you're referring to isn't part of the web application project.
How have you created it? How was the reference added to the project?

Please list all the steps you've followed so we can understand where this is coming from.

**Comment by ravenet** [comment]
Hi,

Let me give full details of my application. 

1. I created a new mvc application using .NET 5
2. Then I created a new class library project with .NET 5 and then add new tag helper for  support paging. When I add that I have to add TagHelper base class 
![image](https://user-images.githubusercontent.com/6859970/99142209-23fb5580-26a7-11eb-87b7-a217d15f30ba.png)

3. When I add namespace for Taghelper it asking to install 
![image](https://user-images.githubusercontent.com/6859970/99142240-4db47c80-26a7-11eb-8d88-8b1f22d417a5.png)

As it is .NET % project why it is reference in 2.2.0 version reference.

Thanks

**Comment by pranavkm** [comment]
> Then I created a new class library project with .NET 5 and then add new tag helper for support paging. When I add that I have to add TagHelper base class

Consider starting with a [Razor Class Library template](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio) - it's already set up to have the correct references and SDKs configured. If you must use a regular class library, add a framework reference instead: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#framework-reference

**Comment by Pilchie** [comment]
@pranavkm do we need to do something to update/change the tag helper scaffolding?  @vijayrkn?

**Comment by vijayrkn** [comment]
I don't think we have an item template for it. 

@ravenet - Can you please confirm what gesture in VS prompted you to install the older version of the package?

**Comment by ravenet** [comment]
Hi,
When I add TagHelper as base class, it is asking to install 

![image](https://user-images.githubusercontent.com/6859970/99501138-74d4bc00-29cf-11eb-8eff-d60955772edd.png)

Thank you
