### ISSUE TITLE
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'

### ISSUE THREAD

**Issue by Sm1le291** [dotnet/aspnetcore#27814]
Hello,

When I migrated my Asp.net Core 3.1 Hosted Blazor Webassembly Project to .Net 5 (many projects)
I started to get at Client project below error message:

**There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.
and directs me there:**
`
ResolveRuntimePackAssets

Resolve assets from runtime packs.
-->

`
to compile successfully but the client does not render properly.

Why this is happening?

Same issue was addressed in StockExchange:
https://stackoverflow.com/questions/63993294/there-was-no-runtime-pack-for-microsoft-aspnetcore-app-available-for-the-specifi

but I don't see them having a fitting solution for me.

Thanks,

**Describe the bug**

**To Reproduce
Exceptions (if any)
Further technical details**
ASP.NET Core version .Net 5.0
Include the output of dotnet --info
dotnet info.txt
The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 16.8

**Comment by Sm1le291** [comment]
![image](https://user-images.githubusercontent.com/15110338/99083014-33a26d80-25c5-11eb-9465-1fe5cfdaa815.png)

**Comment by Sm1le291** [comment]
Just created new solution and projects and moved there all my old files. Everything works, except root problem was not solved.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like the `Microsoft.AspNetCore.Components.WebAssembly.Server` may be the offending one here as you shouldn't reference that from the client project.

**Comment by eation** [comment]
Some package  like [Microsoft.AspNetCore.ConcurrencyLimiter](https://www.nuget.org/packages/Microsoft.AspNetCore.ConcurrencyLimiter/) crash this or not support in the wasm client.
To reproduce,add [Microsoft.AspNetCore.ConcurrencyLimiter](https://www.nuget.org/packages/Microsoft.AspNetCore.ConcurrencyLimiter/)  to a new wasm standalone client,you can see the same error message.
