### ISSUE TITLE
virtualize load all images in blazor

### ISSUE THREAD

**Issue by jawaidakhter** [dotnet/aspnetcore#27816]
I am using a virtualize component in Blazor Server App, to display a list of employees with their images. Instead of loading only images in the current viewport, it is downloading complete images. Is there is any approach instead of downloading all images only download current viewport images? Or this is an issue?

**Comment by daniel-p-tech** [comment]
Have you tried lazy load the images? I'm not fully familiar with Blazor virtualization, so maybe this won't work, just an idea.

```<img loading="lazy" ... />```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It looks like you aren't using `Virtualize` correctly. Please refer to the docs to correct your usage: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0

Also note, that virtualize should only render the tags that are visible in the viewport
