### ISSUE TITLE
Limited to No Semantic Colorization in Codespaces

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27819]
![image](https://user-images.githubusercontent.com/14852843/99103992-60975600-25ae-11eb-8054-cd7dcb75cb28.png)

cc/ @ryanbrandenburg who's seeing _limited_ semantic colorization instead of no semantic colorization.

![image](https://user-images.githubusercontent.com/14852843/99104133-94727b80-25ae-11eb-8db1-d45a7e91b1af.png)

**Comment by TanayParikh** [comment]
Possibly related to: https://github.com/dotnet/aspnetcore/issues/27777

**Comment by NTaylorMullen** [comment]
Things are now working on:
![image](https://user-images.githubusercontent.com/2008729/100025137-0a3fc980-2d9d-11eb-8926-b16763002eeb.png)
