### ISSUE TITLE
Cannot upgrade Microsoft.AspNetCore.Authentication.JwtBearer to 5.0.0

### ISSUE THREAD

**Issue by lejsekt** [dotnet/aspnetcore#27815]
Hi,
I'm trying to migrate ASP .NET Core 3.1 Web API project to .NET 5.0.  When changing Microsoft.AspNetCore.Authentication.JwtBearer package version from 3.1.9 to 5.0.0, I'm getting the following error:
 error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0 supports: net5.0 (.NETCoreApp,Version=v5.0)
The target framework in .csproj is set to net5.0 and this is the only package to produces issues once upgraded to .NET 5.0. Any ideas why? Thank you

**Comment by blowdart** [comment]
Please share your csproj and the results of running dotnet --info.

**Comment by jukarox** [comment]
The same for me, I just created a new .net core 3.1 project 

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.35" />
    <PackageReference Include="Npgsql" Version="4.1.5" />
  </ItemGroup>

</Project>
`

**Comment by dalda1** [comment]
Hi,
I got the same issue with this Package "Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0".

Error on adding package to the project:
==========================================================================
NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0 supports: net5.0 (.NETCoreApp,Version=v5.0)."
==========================================================================

csproj file:
=======
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>

Thanks.

**Comment by renanpaiva64** [comment]
Hellow @blowdart,

I'm having the same issue, following the dotnet --info:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.515 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by renanpaiva64** [comment]
My mistake was using the wrong version of the package, change the version to 3.1.10.

**Comment by lejsekt** [comment]
Sorry, that was my mistake, I had two <TargetFramework> elements in my .csproj.

**Comment by KasunKoswattha** [comment]
I created a new webApp project targeting .Net5 and the base temple doesn't even compile. It gave me the same error. My issue was that I didn't have the latest VS 2019 update. Once I updated it everything works.
