### ISSUE TITLE
Blazor - JSON Content-Type problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27837]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor---JSON-Content-Type-problem/1245928?preview=true)._

---
<p>Hello, I'm calling an API, with POST method, but even if I inform the content-type as application / json, the request is sent to the API as text / plain. My page was created with Blazor. I'm getting the message: 415 Unsupported Media Type. What's wrong?</p> <p>My code:<a href="https://developercommunity.visualstudio.com/storage/attachments/163311-ezq3x.png"> Image:163311-ezq3x.png</a></p><pre>using (var client = new HttpClient())
        using (var request = new HttpRequestMessage(HttpMethod.Post, uri))
        {
            request. SetBrowserRequestMode(BrowserRequestMode.NoCors);
            var json = JsonConvert.SerializeObject(content);
            using (var stringContent = new StringContent(json, Encoding.UTF8, &quot;application/json&quot;))
            {
                client. DefaultRequestHeaders.Clear();
                client. DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue(&quot;application/json&quot;));
                request. Content = stringContent;
                request. Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(&quot;application/json&quot;);
                request. Content.Headers.ContentType = null;
                using (var response = await client
                . SendAsync(request, HttpCompletionOption.ResponseHeadersRead)
                . ConfigureAwait(false))
                {
                    response. EnsureSuccessStatusCode();
                    if (!response. IsSuccessStatusCode)
                    {
                        var errorMessage = response. ReasonPhrase;
                        Console.WriteLine($&quot;Error! {errorMessage}&quot;);
                        return errorMessage;
                    }
                }
            }
        }
</pre>

---
#### Feedback Bot on 11/5/2020, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Ariansh** [comment]
Why did you make it null?
```
request. Content.Headers.ContentType = null
```
