### ISSUE TITLE
Visual Studio single file publish behaviour changed (blozor server side)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27836]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-single-file-publish-behavi/1254207?preview=true)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.7.8]
# Problem

Visual Studio single file publish behaviour changed blozor server side between 16.7.8 and 16.8

There are multiple dlls not packed into the output exe and instead placed beside the output exe. See screenshots.

16.7.8
! [grafik.png] (https://aka.ms/dc/image?name=Bcf4a3ea297eb49ee837a23aa85707d33637407881391709645_20201112-152858-grafik.png&tid=cf4a3ea297eb49ee837a23aa85707d33637407881391709645)

16.8
! [grafik.png] (https://aka.ms/dc/image?name=B8ebaafc7e5ef47ebb6b5b0db6e92a8d7637407881257196430_20201112-152844-grafik.png&tid=8ebaafc7e5ef47ebb6b5b0db6e92a8d7637407881257196430)

I use the following publish profile.

```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DeleteExistingFiles>True</DeleteExistingFiles>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <PublishProvider>FileSystem</PublishProvider>
    <PublishUrl>bin\Release\netcoreapp3.1\publish\</PublishUrl>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <SiteUrlToLaunchAfterPublish />
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishTrimmed>False</PublishTrimmed>
    <ProjectGuid>cf8c9fc3-69a5-4420-922b-f9d78e2dce8c</ProjectGuid>
    <SelfContained>true</SelfContained>
    <ExcludeFilesFromDeployment>
      appsettings. Development.*;
    </ExcludeFilesFromDeployment>
  </PropertyGroup>
</Project>
```

---
#### Feedback Bot on 11/12/2020, 07:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### prkrishn [MSFT] on 11/13/2020, 02:17 PM: 

<p>Thank you for the issue report. There were changes to the way single file bundles are produced in 5.0 apps and one of the consequences of the change is that we were no longer able to bundle the views assembly as was done in 3.1. Unfortunately our change was not limited to net5.0 apps. This would explain why updating to 16.9 (which installs the 5.0 SDK) resulted in view assemblies being added to your app’s publish output. We’ll be using <a target='_blank' href="https://github.com/dotnet/aspnetcore/issues/27831">https://github.com/dotnet/aspnetcore/issues/27831</a> to track addressing this regression. Our hope is to get this resolved as part of the 5.0.1 patch release that should be available early next month (December 2020). In the meanwhile, you could consider adding a <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x"><code>global.json</code></a> file to your solution to target a 3.1 version of the .NET SDK:</p>
<pre><code class="language-json">{ 
   <span class="hljs-attr">"sdk"</span>: {
    <span class="hljs-attr">"version"</span>: <span class="hljs-string">"3.1.404"</span>
  }
}
</code></pre>
<p>In general though, <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core currently does not make any guarantees about what the output looks like for single file publishing. For 6.0, we’re looking at making sure it’s guaranteed to be a single file for certain kinds of workloads (such as <code>webapi</code>), but we don’t plan on trying to address it for apps with static file content. If this is something you consider important, we’d be happy to receive feedback through issues on <a target='_blank' href="https://github.com/dotnet/aspnetcore">https://github.com/dotnet/aspnetcore</a>.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue in favor of https://github.com/dotnet/aspnetcore/issues/27831.
