### ISSUE TITLE
.net 5 hosted blazor app gets 401 error

### ISSUE THREAD

**Issue by Wolfeitz** [dotnet/aspnetcore#27834]
# New Blazor app gets 401 error when accessing the WeatherData API

# General
.Net 5

Create a new Blazor project in VS 2019

- .NET 5.0
- Blazor WebAssembly App
- Authentication
Work or School Accounts
select your domain
Check in Read Directory Data
- ASP.NET Core hosted

Once created, try logging in.  I assume you will get an error that no token was found.
Go into azure portal, registrations, and select your new app.

Click the link to go to the Authentication blade and change your link from a Web redirect URL to a Single-page app redirect URL.  Then fix the port if necessary.

![image](https://user-images.githubusercontent.com/5875224/99128759-491d9480-25d1-11eb-9518-4626606e7861.png)

Once you try to authenticate again, it should work just fine.

Next, in your new Blazor app, click on Fetch Data.
Here's where I am stuck.  I keep getting a 401, unauthorized error and I am really not sure how to fix that.

![image](https://user-images.githubusercontent.com/5875224/99128875-9f8ad300-25d1-11eb-9eec-e501fe6b16b5.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We have extensive docs on how to configure your app to work with AAD https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0.

Hope this will help you resolve your issue.
