### ISSUE TITLE
Failed to build Asp.Net Core 5 MvcSandbox sample project when trying to AddJsonFile() configuration

### ISSUE THREAD

**Issue by milost1982** [dotnet/aspnetcore#27849]
I wanted to learn, explore and play around with new Asp.Net Core 5 source code and it's sample application project MvcSandbox but it won't build when I try to add Json configuration extension to it. The `Microsoft.Extensions.Configuration.Json` is referenced in .csproj by default. 
I also get several yellow triangles for assemblies when I look into dependencies node of Solution Explorer in Visual Studio 2019 v16.8.1.

To Reproduce:
1. Follow the guide at: https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md
2. Then open src\Mvc\Mvc.slnf or src\Mvc\MvcNoDeps.slnf in Visual Studio 2019 v16.8.1
3. Build project -> success
4. Open Startup.cs and add following on line 111:
```
                .ConfigureAppConfiguration(config =>
                {
                    config.AddJsonFile("appsettings.json");
                })
```
basically I want to enable appsettings.json configuration in sample MvcSandbox application.

5. Try to build agail -> build fails with the error:
`Error	CS1061	'IConfigurationBuilder' does not contain a definition for 'AddJsonFile' and no accessible extension method 'AddJsonFile' accepting a first argument of type 'IConfigurationBuilder' could be found (are you missing a using directive or an assembly reference?)`

If I look in the project dependencies I see yellow triangle for several items, mostly for Microsoft.Extensions.* as on this screenshot: 
![MWt06xy 1](https://user-images.githubusercontent.com/45071334/99151760-9109ed80-269d-11eb-8efe-a0e468c3afb4.png)

The .csproj file contains references to these assemblies and I didn't change anything there:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Mvc" />
    <Reference Include="Microsoft.AspNetCore.Components.Server" />
    <Reference Include="Microsoft.AspNetCore.Diagnostics" />
    <Reference Include="Microsoft.AspNetCore.Server.IISIntegration" />
    <Reference Include="Microsoft.AspNetCore.Server.Kestrel" />
    <Reference Include="Microsoft.AspNetCore.StaticFiles" />
    <Reference Include="Microsoft.Extensions.Configuration.Json" />
    <Reference Include="Microsoft.Extensions.Logging.Console" />
    <Reference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>

</Project>

```

**Comment by dougbu** [comment]
@milost1982 add `using Microsoft.Extensions.Configuration;` to the `Startup.cs` file to solve this compilation problem.

@pranavkm this was always an `area-mvc` issue 😺
