### ISSUE TITLE
Blazor Server & WebAssembly cannot read large file streams from client

### ISSUE THREAD

**Issue by xPucTu4** [dotnet/aspnetcore#27862]
### Describe the bug
I want to be able to read files from client browsers using blazor server-side. Using the <InputFile/> component, I choose some test file. If the file size is more than 2-3 GB, I cannot read it.
I am not trying to upload the whole file. You can see that from the sample page.

### To Reproduce
The clean template with just 1 file added
https://github.com/xPucTu4/BlazorUploadBug

You can create new blazor-server project and just add that file:
https://github.com/xPucTu4/BlazorUploadBug/blob/main/BlazorUploadBug/Pages/Upload.razor

### Exceptions (if any)
With file size of about 4GB:
Sometimes JSException with message "[object ProgressEvent]"
With file size of about 3GB there is no exception or any indications of errors.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Aadael** [comment]
Thank you so much - i really thought my brain would explode. I have the same error and as far as I can tell it's the same in Blazor WebAssembly.

**Comment by LordBenjamin** [comment]
Is the impact of this limited to server-side Blazor?

Currently debugging an issue in Blazor WASM where:
* a 1 GB file works fine
* a file of around 2 GB throws `JSException` with message `[object ProgressEvent]`
* a file of around 3.5 GB does not throw exceptions, but calling `await stream.ReadAsync(buffer, 0, buffer.Length);` always returns `0` (even though the buffer is of non-zero length and `stream.Position` is `0`

I generated a 2 GB test file using:

```
fsutil file createNew 2gb.txt 2147483647
```

This might be a separate issue, happy to raise one if it's a different code path to server-side Blazor.

**Comment by TanayParikh** [comment]
This is an issue with both Server and WebAssembly.

Fixes here:
- https://github.com/dotnet/aspnetcore/pull/33900
- https://github.com/dotnet/aspnetcore/pull/33986

Moved from rc1 to preview 7 as the target 😄
