### ISSUE TITLE
Data Type change in IdentityUser.Id Or IdentityRole.Id Is not reflected in respective methods

### ISSUE THREAD

**Issue by sandeepksharma15** [dotnet/aspnetcore#27860]
### Describe the bug
I am creating an AppUser by inheriting IdentityUser<int> and similarly I am creating an AppRole by inheriting IdentityRole<int>. This works very well for building or even creating migrations. However, when I want to use a method like "FindByIdAsync" on UserManager Or roleManager, it expects a string and NOT an int. I am working around this by using Id.ToString() and it works but I believe it is still a bug and <TKey> has not been used as it should have been.

I am using int as TKey and written similarly in my bug description but it doesn't show the same when I save it

### To Reproduce
I am not submitting a repro project as it is very very simple to reproduce it as explained above in the bug description

### Further technical details
- ASP.NET Core version: net5.0
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Microsoft Visual Studio Community 2019 Preview
Version 16.9.0 Preview 1.0

**Comment by MCCshreyas** [comment]
Hi @sandeepksharma15, 
Not sure if this is considered a bug, as the same thing was there in release 3.1 as well. 
https://github.com/dotnet/aspnetcore/blob/940dcb0aba247da054ee435380d533e04944093c/src/Identity/Extensions.Core/src/UserManager.cs#L532

Above is the line where it affects. As we can see the method does not respect the type of key that the user wants, it always accepts a string parameter.

**Comment by blowdart** [comment]
This is not a bug, it's a design decision. String is the lowest common denominator for conversion targets, and attempting to flow a primary key type everywhere would make the code even more complicated than it already is when it comes to customisation. Your stores need to do the necessary conversions.

This will not change.
