### ISSUE TITLE
Reference middleware by name

### ISSUE THREAD

**Issue by kimbell** [dotnet/aspnetcore#27864]
The background for this suggestion is a company that is developing multiple .NET Core services. Each of these services must have certain characteristics; for arguments sake we can call it infrastructure code. i.e. they should have endpoints for health, info, version information. They may have endpoints for metrics. Over time things will change. Today they may be using Prometheus for metrics, tomorrow they may choose something else. 

Most developers should focus on application logic, not infrastructure logic. They shouldn't need to know that middlware X needs to run before middleware Y. As time passes, third party libraries may change in a way that impacts the the middleware order. If you have 100 services this needs to be applied to, there are room for a lot of mistakes. 

Companies may also have different classes of applications; some are front-end, others are back-end. Each class may have different requirements when it comes to middleware. 

The way the middleware and endpoint pipeline is constructed today is very rigid; changes requires you to go and change lines of code. 

This idea is basically about registering named lambdas in IServiceCollection, and then use these when constructing the middleware pipeline. This is a system that could be developed outside ASP.NET, but having it in the core framework would allow third party libraries to take advantage of it. A possible solution would be to add extension methods that provides an alternative to today's approach; it wouldn't break anything. 

Another advantage of this solution is that it's possible to change the implementation of middleware depending on the environment. Lets assume you are using WebApplicationFactory to run your tests; this uses your Startup class. Your application requires authentication. When running tests, it can be advantageous to handle authentication in a different way. This alternative way should only be available when running tests; not something the main codebase should know about. Since we are using the same Startup class, you need to get creative. 

With named middleware, you could add code that doesn't register authentication when run during tests. In your tests you can then register your custom middleware with the same name, and that would be used instead. 

Here is some code I've been using to solve this problem. 
```cs
 public class NamedMiddlewareEntry
    {
        public string Name { get; }
        public Action<IApplicationBuilder> Setup { get; }

        public NamedMiddlewareEntry(string name, Action<IApplicationBuilder> setup)
        {
            Name = name;
            Setup = setup;
        }
    }

    public class EndpointEntry
    {
        public Action<IEndpointRouteBuilder> Setup { get; }

        public EndpointEntry(Action<IEndpointRouteBuilder> setup)
        {
            Setup = setup;
        }
    }

    public static class ExtensionMethods
    {
        public static IServiceCollection AddNamedMiddleware(this IServiceCollection services, string name, Action<IApplicationBuilder> setup)
        {
            return services.AddSingleton(new NamedMiddlewareEntry(name, setup));
        }

        public static IServiceCollection AddEnpointsEntry(this IServiceCollection services, Action<IEndpointRouteBuilder> setup)
        {
            return services.AddSingleton(new EndpointEntry(setup));
        }

        public static IApplicationBuilder UseNamedMiddleware(this IApplicationBuilder builder, IEnumerable<string> names)
        {
            var entries = builder.ApplicationServices.GetServices<NamedMiddlewareEntry>().ToList();

            foreach (var name in names)
            {
                var found = entries.Find(n => name.Equals(n.Name, StringComparison.OrdinalIgnoreCase));
                if (found != null)
                {
                    found.Setup(builder);
                }
            }

            return builder;
        }
        public static IEndpointRouteBuilder MapRegisteredEndpoints(this IEndpointRouteBuilder endpoints)
        {
            foreach (var entry in endpoints.ServiceProvider.GetServices<EndpointEntry>())
            {
                entry.Setup(endpoints);
            }

            return endpoints;
        }
    }

    public class Sample
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddNamedMiddleware("Routing", setup => setup.UseRouting());
            services.AddNamedMiddleware("Authorization", setup => setup.UseAuthorization());
            services.AddNamedMiddleware("Endpoints", setup => setup.UseEndpoints(endpoints => endpoints.MapRegisteredEndpoints()));
            services.AddEnpointsEntry(endpoints => endpoints.MapControllers());
        }

        public void Configure(IApplicationBuilder builder)
        {
            builder.UseNamedMiddleware(new string[] { "Routing", "Authorization", "Endpoints" });
        }
    }
```

**Comment by davidfowl** [comment]
This seems like something that would be great to build as an extension to the platform but isn't something we want to build in.

**Comment by Tratcher** [comment]
How does this address the ordering concerns you've raised if the app developer is still ultimately responsible for getting the ordering of the names right in `UseNamedMiddleware(new string[] { "Routing", "Authorization", "Endpoints" });`?

I'm curious to see how you'd extend this to cover your testing scenarios. Can you expand on the example for that?

**Comment by kimbell** [comment]
If a company has these requirements, chances are that they are building some framework libraries to support their efforts. A simple solution would be to have predefined application profiles. 

```cs
public class ApplicationProfiles
    {
        public static string[] BackendMiddlewareOrder = new[] { "Middleware1", "Middleware1", "Middleware3" };
        public static string[] FrontendMiddlewareOrder = new[] { "Middleware1", "Middleware5", "Middleware3" };
    }
```
Since this is being used from the Startup.Configure method, more advanced solutions might involve reading information from the configuration system. The developer knows what type of application they are building, but they don't need to know the exact order of the middleware. 

Some services might need additional middleware that is not part of the standard pipelines. Since the order is just a list of strings, it's easy to add a new entry in the relevant position. In this case the developer needs to know more about the infrastructure. The developers maintaining the infrastructure code can define a set of middleware that doesn't necessarily exist in all services; those that are not found in `IServiceCollection` are just ignored. The company can then document what extensibility points they support by default.  

For testing purposes, we can make a slight change to the `UseNamedMiddleware()`. The clue is reversing the list. 

```cs
public static IApplicationBuilder UseNamedMiddleware(this IApplicationBuilder builder, IEnumerable<string> names)
        {
            // by reversing the list, we allow entries added later to IServiceCollection to override earlier ones. 
            var entries = builder.ApplicationServices.GetServices<NamedMiddlewareEntry>().Reverse().ToList();

            foreach (var name in names)
            {
                var found = entries.Find(n => name.Equals(n.Name, StringComparison.OrdinalIgnoreCase));
                if (found != null)
                {
                    found.Setup(builder);
                }
            }

            return builder;
        }
```

So lets assume we have the following startup class
```cs
 public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddNamedMiddleware("Routing", setup => setup.UseRouting());
            services.AddNamedMiddleware("Authorization", setup => setup.UseAuthorization());
            services.AddNamedMiddleware("Endpoints", setup => setup.UseEndpoints(endpoints => endpoints.MapRegisteredEndpoints()));
            services.AddEnpointsEntry(endpoints => endpoints.MapControllers());
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseNamedMiddleware(new string[] { "Routing", "Authorization", "Endpoints" });
        }
    }
```
In test project we can then add a new implementation for 'Authorization'
```cs
public class UnitTest1
    {
        [Fact]
        public async Task Test1()
        {
            using(var tc = new TestContext())
            {
                var client = tc.CreateClient();
                var response = await client.GetStringAsync("http://localhost/weatherforecast");
            }
        }
    }

    public class TestContext : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder

                .ConfigureServices((ctx, services) =>
                {
                    services.AddNamedMiddleware("Authorization", _ =>
                    {
                        // change the middleware for Authorization
                    }); 
                });
        }
    }
```
