### ISSUE TITLE
Microsoft.AspNetCore.SignalR.Client package does not indicate that it needs Microsoft.AspNetCore.Http v3.1 (#25305)

### ISSUE THREAD

**Issue by TehWardy** [dotnet/aspnetcore#27874]
Closed by bot whilst waiting for Microsoft to respond.
     https://github.com/dotnet/aspnetcore/issues/25305

**Comment by davidfowl** [comment]
I reopened the issue

**Comment by TehWardy** [comment]
ta muchly 👍

**Comment by TehWardy** [comment]
@davidfowl  there's another one here ...
  https://github.com/dotnet/aspnetcore/issues/13853#event-3987310034
