### ISSUE TITLE
.Net5 WebAPI cannot connect to Oracle

### ISSUE THREAD

**Issue by anjoy8** [dotnet/aspnetcore#27872]
### .Net5 WebAPI cannot connect to Oracle
I upgraded vs to version 16.8, and then use. Net5 created a default webapi project, 
and use `Oracle. ManagedDataAccess. Core` class libraries to connect to the Oracle database.
it failed.
(asp.net core 3.1 It works when used this way)

But I created a .net5 console project, also use `Oracle. ManagedDataAccess. Core` class libraries, can be connected

### Exceptions  
Using **. Net5 webAPI** to connect oracle error:
```
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.91" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
  </ItemGroup>
```

The Code:

```
 var _connectionString = "Data Source=xx.xx.xxx.xx/orcl; User Id=test; Password=test;";
 using (var connection = new OracleConnection(_connectionString))
 {
     connection.Open();// error
 }

```
![图片](https://user-images.githubusercontent.com/28941816/99224923-2504c200-2822-11eb-9d13-71d5aee03de0.png)

![图片](https://user-images.githubusercontent.com/28941816/99227961-ec1b1c00-2826-11eb-8f3d-53952acc4d32.png)

Connection to Oracle using the **console of. Net5** is normal:

![图片](https://user-images.githubusercontent.com/28941816/99225639-56ca5880-2823-11eb-9ca6-c985eef4a193.png)

### Further technical details
- ASP.NET Core version ：.net 5.0
- Include the output of `dotnet --info`
```
C:\Users\laozhang>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.517 [C:\Program Files\dotnet\sdk]
  2.1.518 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

![图片](https://user-images.githubusercontent.com/28941816/99225253-b411da00-2822-11eb-8206-be521a487db9.png)

**Comment by anjoy8** [comment]
Maybe Oracle doesn't support.net5 yet

**Comment by davidfowl** [comment]
The exception message says it BinaryFormatter serialization is not supported by this application and it even provides a link to get more information on this issue https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide.

@GrabYourPitchforks it seems like the oracle provider uses binary formatter and that article doesn't show me how to turn it back on for these cases when libraries use them.

cc @ajcvickers @roji

**Comment by javiercn** [comment]
@anjoy8 thanks for contacting us.

I will suggest you follow-up on the Oracle channels for more details. Like [here](https://community.oracle.com/tech/developers/categories/odp.net) or [here](https://github.com/oracle/dotnet-db-samples)

**Comment by ajcvickers** [comment]
We have had communication with Oracle on this on internal channels and we gave them guidance on how to approach the problem. However, I don't know if they have yet implemented that guidance--for that, as Javier said, it would be best to follow up with Oracle.

**Comment by anjoy8** [comment]
Hi,Thanks for all your help! I will follow up Oracle.

**Comment by javiercn** [comment]
@ajcvickers thanks for following-up.

I'll close this issue since there's nothing else for us to do/track here.

**Comment by GrabYourPitchforks** [comment]
See also https://aka.ms/BinaryFormatter/draft, which contains some additional resources. I'm working on getting this merged in to the existing docs.
