### ISSUE TITLE
IBrowserFile Missing ContentType For Some Files

### ISSUE THREAD

**Issue by cotur** [dotnet/aspnetcore#27877]
`IBrowserFile` doesn't provide `ContentType` for some file types.

![image](https://user-images.githubusercontent.com/20099739/99246721-d69df600-2816-11eb-8b55-1a6eb8bc2bfc.png)

### To Reproduce
```csharp
<InputFile OnChange="SelectedFilesAsync" multiple />
<br />
<br />
<br />


@if (fileNameMime?.Count > 0)
{
    <table border="1" cellpadding="3" cellspacing="0">
        <tr>
            <td><b>File Name</b></td>
            <td><b>Content Type</b></td>
        </tr>
        @foreach (var (key, val) in fileNameMime)
        {
        <tr style="background-color: @(string.IsNullOrEmpty(val) ? "orange" : "white");">
            <td>@key</td>
            <td>@val</td>
        </tr>
        }
    </table>
}

@code {
    Dictionary<string, string> fileNameMime = new Dictionary<string, string>();

    void SelectedFilesAsync(InputFileChangeEventArgs args)
    {
        fileNameMime = args.GetMultipleFiles().ToDictionary(x => x.Name, x => x.ContentType);
    }
}
```

### Further technical details
- ASP.NET Core version: 5.0

![image](https://user-images.githubusercontent.com/20099739/99246682-c84fda00-2816-11eb-961d-6b2e9c0079ea.png)

**Comment by javiercn** [comment]
@cotur thanks for contacting us.

It's likely that this is just the browser behavior and we are mimicking it. Very likely the browser sets that based on the extension, so it's not something you should trust in any case.

**Comment by cotur** [comment]
@javiercn Thanks for reply. I think I need to implement my solition. Thanks again. 👍
