### ISSUE TITLE
Blazor WASM I want to pass parameters from the HTML side.

### ISSUE THREAD

**Issue by zio3** [dotnet/aspnetcore#27879]
###Problem/what I am trying to do
Based on the attributes described in the HTML, the
We want to pass a parameter to Blazor WebAssmemblry. I would like to use it to change the behavior.
This is because there are cases where we want to use more than one of the same component on the same page.

### Describe the solution you'd like
It would be nice if RootComponent can also get the value by [Parameter].

**Comment by javiercn** [comment]
@zio3 thanks for contacting us.

I'm not sure what you are trying to do, but if you render components from an MVC/Razor pages view, it's possible to pass in parameters to the root component of the page.

@SteveSandersonMS It should be simple enough if we wanted to pass in the attributes of an element with a selector as component parameters. Do you have any thoughts?

**Comment by SteveSandersonMS** [comment]
The option I've normally recommended to people is to use JS interop from your `Program.cs` logic to read whatever data you want (synchronously) out of the DOM. You can then pass those parameters to your components in the `builder.RootComponents.Add(...)` calls.

> It should be simple enough if we wanted to pass in the attributes of an element with a selector as component parameters. Do you have any thoughts?

We could do, but it opens some questions. For example, how do we know which subset of attributes to pass, and what to JSON-deserialize them as? Do we rely on assuming the root component uses `[Parameter]` properties and reflect over those?

As it stands, letting developers use JS interop themselves to fetch their own data from the DOM avoids the framework needing to know about this. The only drawback to this approach is it's hard to discover, but we could add it more clearly to docs. I suppose passing attributes automatically wouldn't be discoverable without reading docs either.

**Comment by SteveSandersonMS** [comment]
> I think the best guidance we can give is to render the components from an ASP.NET Core view/page

Or use JS interop to read from the DOM - that works great too :)

**Comment by zio3** [comment]
component tag to do what was intended. Thank you!

**Comment by SteveSandersonMS** [comment]
Glad to hear the `<component>` tag helper meets your needs.
