### ISSUE TITLE
[Blazor server] Blazor server improvements for 6.0

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#27885]
* More control over circuits lifetime (ability to monitor circuit activity and terminate from client/server).
* [Hibernate and restore circuits](https://github.com/dotnet/aspnetcore/issues/27576).
* [Better `byte []` serialization](https://github.com/dotnet/aspnetcore/issues/21877).
* [Render root components after circuit has started](https://github.com/dotnet/aspnetcore/issues/27574).
* Remove size limitations imposed by signalr message size.
* Specific components for dealing with large binary data (files and media).
* Specific component for dealing with large amounts of text data (InputTextArea)
* Better logging through activity tracing [see](https://github.com/dotnet/aspnetcore/issues/29846)
* [Tooling for Blazor Server perf & load testing](https://github.com/dotnet/aspnetcore/issues/27457)

**Comment by michalczerwinski** [comment]
Are there any details on what is to be expected?

**Comment by mkArtakMSFT** [comment]
@javiercn please add more details about what to consider as part of this issue. Thanks!

**Comment by javiercn** [comment]
I've added some high level points, but I'll add more details if necessary.

**Comment by danroth27** [comment]
We've also heard a bunch of Blazor Server users ask for tools to help load test Blazor Server apps: https://github.com/dotnet/aspnetcore/issues/27457

**Comment by SteveSandersonMS** [comment]
I've split out each of the items that didn't already have their own issues, so this meta-issue is no longer needed.

**Comment by javiercn** [comment]
@SteveSandersonMS please keep the meta-issue around, it's what we are using to track all improvements in this area.

**Comment by javiercn** [comment]
Also @SteveSandersonMS @amarie401 is helping in this area, FYI.

**Comment by SteveSandersonMS** [comment]
> please keep the meta-issue around, it's what we are using to track all improvements in this area.

Meta-issues can't really be ranked or prioritized. I'm changing it from "enhancement" to "task" at least so it doesn't show as an unranked enhancement/bug. Alternatively it could be moved to a different milestone.

Tangentially, I'm not clear on which of our planning processes make use of meta-issues.

**Comment by amarie401** [comment]
Thanks for breaking this issues out @SteveSandersonMS. I have went ahead and updated my PR to reflect the links for these newly created issues.

**Comment by mkArtakMSFT** [comment]
Closing as some items on this list are already done and for the rest we have existing tracking issues now.

**Comment by mrlife** [comment]
@mkArtakMSFT Hi, I was wondering if these are still something MS is considering or if they're not needed anymore or are done.

- Specific components for dealing with large binary data (files and media).
- Specific component for dealing with large amounts of text data (InputTextArea)
