### ISSUE TITLE
CSS isolation with multiple theming is not supported in Blazor components

### ISSUE THREAD

**Issue by icsilambarasan** [dotnet/aspnetcore#27884]
I want to use the CSS isolation for loading **mulitple themes** in my application. Eg: like with different themes (bootstrap, material, etc) to customizing the styles as scoped for my components. Seem its not supported one now or anyone share the details to get it works in my end. Anyone help me on this!!

**Comment by javiercn** [comment]
@icsilambarasan thanks for contacting us.

That's not the goal of CSS isolation. We don't have any explicit implementation/abstraction support for theming, but this is something developers need to build themselves, nor is something we plan to do in the near future.

For "theming" like changing colors, fonts, etc. we suggest you use CSS variables or a similar technology.

As per being able to switch CSS frameworks, that's not something we believe fits in the concept of "theming".
