### ISSUE TITLE
Show Images and Icons in my Projects 

### ISSUE THREAD

**Issue by FMatu2020** [dotnet/aspnetcore#27881]
Hello everybody.
Sorry, i am not a programmer, just someone who cares a lot.
Why are neither Images nor Icons displayed in all of my Projects? They are all blocked.

Thanks for your help :)

**Comment by blowdart** [comment]
Do you mean within Visual Studio? If so, you need to use their feedback mechanism under help to ask them.

**Comment by FMatu2020** [comment]
Yes with Visual Studio 2019 prof.! Ok I`ll try that. I thought via Github i will get an answer faster...
Thanks

**Comment by FMatu2020** [comment]
Hm...
I need a tip, not a ready-made solution that doesn`t address my problem :(

**Comment by afsharm** [comment]
@FMatu2020 Can you share an image of what you see?

**Comment by javiercn** [comment]
@FMatu2020 thanks for contacting us.

Unfortunately we don't have enough details to help you, can you clarify what types of project you are trying to build or provide a repro project with detailed steps on how to reproduce the issue so that we might try to help you?

**Comment by FMatu2020** [comment]
Sorry, i'm at Work :)
Thats my Code from my Testside

<Window x:Class="Test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Test"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <DockPanel>
        <Menu DockPanel.Dock="Top" Name="mnuMenu">
            
            <MenuItem Header="_Datei">
                
                <MenuItem Header="_Neu" />
                
                <MenuItem Header="_Öffnen">
                    <MenuItem.Icon>
                        <Image Source="/Icon/OpenFolder_16x.png" Width="16" Height="16" />
                    </MenuItem.Icon>
                </MenuItem>
                
                <Separator />
                
                <MenuItem Header="_Drucken">
                    <MenuItem.Icon>
                        <Image Source="Icon/Print_16x.png" Width="16" Height="16" />
                    </MenuItem.Icon>
                </MenuItem>
                
            </MenuItem>
        </Menu>
    </DockPanel>
    
</Window>

**Comment by javiercn** [comment]
@FMatu2020  thanks for the details.

Unfortunately, the code that you posted doesn't seem to be related to ASP.NET Core. I would suggest you try to post the question [here](https://github.com/xamarin/Xamarin.Forms) since they'll be able to give you a faster and better answer.
