### ISSUE TITLE
Unable to build  signalr-client-c++ app on macOS

### ISSUE THREAD

**Issue by mprather** [dotnet/aspnetcore#27899]
### Describe the bug
Create a simple app that incorporates the signalr-client-c++ library using vcpkg.

In windows, use the integrated install option for vcpkg. In linux, use the cmake instructions.  The windows compilation is just our team's starting point for all apps. Then we concentrate on cross-platform builds - first gnu/linux than macOS. We have found that build instructions that can be used in linux do not work in macOS.

### To Reproduce
We originally setup our build system to use makefiles (as main app utilizes that exclusively). We were able to get linux compilations to work. We then attempted to build on Azure Pipelines Hosted agent for MacOS 10.15. The macOS builds failed with the following:

```
2020-11-03T01:49:39.4319710Z undef: _SecCertificateCreateWithData
2020-11-03T01:49:39.4320190Z undef: _CFDataCreateWithBytesNoCopy
2020-11-03T01:49:39.4320420Z undef: _kCFAllocatorDefault
2020-11-03T01:49:39.4321260Z undef: _kCFAllocatorNull
2020-11-03T01:49:39.4321510Z undef: _CFStringCreateWithCStringNoCopy
2020-11-03T01:49:39.4321760Z undef: _CFRelease
2020-11-03T01:49:39.4322020Z undef: _SecTrustCreateWithCertificates
2020-11-03T01:49:39.4322260Z undef: _CFArrayCreate
2020-11-03T01:49:39.4322470Z undef: _SecPolicyCreateSSL
2020-11-03T01:49:39.4322670Z undef: _SecTrustEvaluate
2020-11-03T01:49:39.4322920Z Undefined symbols for architecture x86_64:
2020-11-03T01:49:39.4324010Z   "_SecCertificateCreateWithData", referenced from:
2020-11-03T01:49:39.4327280Z       web::http::client::details::verify_cert_chain_platform_specific(boost::asio::ssl::verify_context&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libcpprest.a(x509_cert_utilities.cpp.o)
<list of 9 other symbols not found in libcpprest omitted for clarity>
```

Realizing that maybe our makefiles were omitting something crucial (i.e. we didn't read the signalr cmake files correctly for settings), we scoured the library's instructions and its cmake files to see if maybe we omitted something. We could not determine that what might be different between linux and macOS compilations. 

To simplify the repro, we decided to create a simple app that leveraged cmake. We confirmed that our test app was able to use the signalr-c++ library with no problem on linux machines; however, on macOS, nearly similar build failures were received. 

```
2020-11-04T02:02:04.4632820Z Undefined symbols for architecture x86_64:
2020-11-04T02:02:04.4633430Z   "_CFArrayCreate", referenced from:
2020-11-04T02:02:04.4660730Z       web::http::client::details::verify_X509_cert_chain(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libcpprest.a(x509_cert_utilities.cpp.o)
<list of 9 other symbols not found in libcpprest omitted for clarity>
```

### Expectation
Since both the Linux and MacOS pipelines use the exact same instruction and all we're changing is the vmImage value, the build process should work on both operating systems.

I knew rolling our own makefile might be problematic but I did not expect builds on macOS with the provided cmake instructions to fail. We have successfully built on linux but cannot get the same code to compile on the mac. We've scrubbed the instructions on the project's repo and double checked everything a few times over. Is this a problem with signalr-client-c++ cmake files or vcpkg's package implementation of the signalr library?  Any guidance would be appreciated.

### Further technical details
- signalr-client-c++ library, tag = v0.1.0-alpha-1
- vcpkg, tag = 2020.06

**Comment by BrennanConroy** [comment]
Looks like an issue building the cpprestsdk, you might get better help by filing an issue at https://github.com/microsoft/cpprestsdk/

Also, take a look at https://github.com/microsoft/cpprestsdk/issues/767 where they had similar issues and resolved it by installing zlib.

**Comment by mprather** [comment]
We did look at the zlib dependency and I'm pretty sure that we confirmed that everything was in place.  The machines have zlib installed by default and the vcpkg install for signalr also references zlib (albeit a newer version). I'll go back and review our notes to confirm.

**Comment by bufrr** [comment]
Same issue, any updates?

**Comment by BrennanConroy** [comment]
> Looks like an issue building the cpprestsdk, you might get better help by filing an issue at https://github.com/microsoft/cpprestsdk/

Again, should probably file an issue on the project that's failing to build.

**Comment by mprather** [comment]
Still on my queue to investigate. We've been boxed in with SignalR test failures due to super slow startups that occur only in Azure builds. This has absolutely killed our Azure pipeline quota in the past month. Everything builds properly but slow start times kill all unit tests with Azure forcing hourly time limits. Hopefully, this can be tackled once the slow starts is put to bed.

**Comment by mprather** [comment]
Are there any build project build tests that target macOS? Seems like a build test would have found this problem a long time ago.

**Comment by mprather** [comment]
I have an update. Using a makefile style build (our default implementation), an app built on macOS will compile if you specifically add the following flags to the compilation/link command for the exe:  

```
-framework CoreFoundation -framework Security
```

I have not had the opportunity to see how this fix could be implemented in the cmake files. Looking at the cpprestsdk project page, their macOS compilation tests are passing. Is it possible that the signalr cmake files are stepping on a configuration?

**Comment by BrennanConroy** [comment]
> Are there any build project build tests that target macOS? Seems like a build test would have found this problem a long time ago

Our CI builds and tests on Mac perfectly fine.

> Looking at the cpprestsdk project page, their macOS compilation tests are passing.

Is this looking at their CI? Or did you try building it locally and succeed?

> Is it possible that the signalr cmake files are stepping on a configuration?

Very unlikely.

**Comment by mprather** [comment]
I'm not sure what additional information I can provide. We literally built a 2 line signalr app as I mentioned when I opened the bug back on Nov 16.  It could not be any simpler using the cmake style with vcpkg (as opposed to writing a makefile). The code was 1 line for the include, 1 line for the call to hub_connection_builder in main. Compiles on Windows and Linux. Fails on macOS. All builds are on Azure pipelines. We do not have any macs on hand to locally test. 

This afternoon I had a chance to look at the cmake failures once more. Leveraging the makefile approach from above, if I add the following to the exe's cmake file, the compilation will now complete.

```
  if(APPLE)
    find_library(LIBRARY_COREFOUNDATION CoreFoundation)
    find_library(LIBRARY_SECURITY Security)
    set(LIBRARIES ${LIBRARIES} 
                  ${LIBRARY_COREFOUNDATION}
                  ${LIBRARY_SECURITY})
  endif()
```
The sample exe doesn't provide insight related to this issue. Does the team have any examples that leverage vcpkg and cmake? I am curious if there are other case-specific settings that we're missing.
