### ISSUE TITLE
RemoteAuthenticatorView OnLogInSucceeded hangs with any long running task

### ISSUE THREAD

**Issue by timebenezer** [dotnet/aspnetcore#27895]
I'm writing a Blazor WASM application (5.0.0) using AAD MSAL auth....

If you have any task that takes more than a few hundred milliseconds (eg. await Task.Delay(1000) or an HTTP get outside of the Blazor application) within the OnLogInSucceeded callback event of RemoteAuthenticatorView, the application gets "stuck" on a logging in screen. I can't figure out what is causing this behaviour. Is this a bug?

**Comment by javiercn** [comment]
@timebenezer thanks for contacting us.

When you mean the app gets stuck, do you mean it stays on the page for a while and goes to the actual return url or that it never redirects to the return url even after OnLoginSucceded has finished.

**Comment by timebenezer** [comment]
It never redirects. If I do a HTTP call (eg. Http.GetAsync("https://google.com")) the behaviour is that the HTTP call happens over and over again; it's like the event gets called multiple times if there is a delay for any reason.

**Comment by amccorma** [comment]
was this issue resolved?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We couldn't prioritize this investigation given the number of customers are affected. Hence closing this issue.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
