### ISSUE TITLE
Clarify Correct Place to set default value for Parameters

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/aspnetcore#27893]
### Describe the bug
Default Parameters Value is not always set if it is done OnInitialize, whereas it is always set correctly in OnParametersSet.  The documentation recommends using OnIntialize, but if this is the case, there is a bug present.  See this Blazor documentation issue [https://github.com/dotnet/AspNetCore.Docs/issues/20602](https://github.com/dotnet/AspNetCore.Docs/issues/20602)

### To Reproduce
Create a sample Blazor app and update the Counter page with the following:

```
@page "/counter/{CurrentCount:int?}"

<h1>Counter</h1>
<p>Current count: @CurrentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
<ul>
    <li><a href="/counter/42">Navigate to /counter/42</a></li>
    <li><a href="/counter/123">Navigate to /counter/123</a></li>
    <li><a href="/counter/">Navigate to /counter</a></li>
</ul>
@code {

    [Parameter]
    public int? CurrentCount { get; set; }
    protected override void OnInitialized()
    {
        base.OnInitialized();
        CurrentCount = CurrentCount ?? 1;
    }

    //protected override void OnParametersSet()
    //{
    //    base.OnInitialized();
    //    CurrentCount = CurrentCount ?? 1;
    //}

    void IncrementCount()
    {
        CurrentCount++;
    }
}
```
Then just click on the links.  The third one will be null.  Then uncomment the OnParametersSet method and test again.  This time the third one will not be null

Tested with 16.9.128.44438.

**Comment by mrpmorris** [comment]
I recognise that code from Blazor University :)

**Comment by javiercn** [comment]
@gregoryagu thanks for contacting us.

We provided the guidance on the original docs issue.
