### ISSUE TITLE
Blazor-Wasm overriding specific framework (.Net standard library instead of .Net Core app)

### ISSUE THREAD

**Issue by juanfranblanco** [dotnet/aspnetcore#27906]
Due the omission and removal of different System.Security.Cryptography libraries in Wasm for .Net 5 I would like to target instead Netstandard2.0 libraries that use a fallback and portable mechanism to BouncyCastle.

To do so I want to force a specific package using a netstandard2.0 library like:

```xml
 <PackageReference Include="NBitcoin" ExcludeAssets="Compile" GeneratePathProperty="true">
		  <Version>5.0.54</Version>
	  </PackageReference>
	  <Reference Include="NBitcoin">
		  <HintPath>$(NuGetPackageRoot)nbitcoin\5.0.54\lib\netstandard2.0\NBitcoin.dll</HintPath>
</Reference>
```

This is completely ignored I guess during linking and used instead the NetCoreApp version:
![image](https://user-images.githubusercontent.com/562371/99389119-78344e80-28ce-11eb-807f-409206c146d0.png)

Even if force a replacement of the file, the sha256 validation will disallow the dll. Also compressing the files (gz) will also ignore the dlls.

Possible solution: Identify named package / assembly that replace existing references and use those for both linking and compressing when using blazor / wasm.

Another simpler solution: Allow to exclude specific libraries (similar to lazy load) but provide a path to load them (full Url and validation mechanism). I assume a requirement in this scenario will be to add also netstandard as a reference.

**Comment by pranavkm** [comment]
ExcludeAssets="Compile" does not remove the binaryfrom being considered as a runtime asset which is what gets copied over to the build or publish directory. You could consider using `ExcludeAssets="All"` which should get it to use your manually added Reference instead
