### ISSUE TITLE
HttpContext is null on mobile devices

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#27909]
### Describe the bug
I have a blazor server side application where the user needs to be logged in first. My razor page sets some claims and then login the user via the following line of code:
`await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);`

Now I have a service which should convert my claims into an actual object.
```
public AppMitarbeiter? GetMitarbeiter()
{
	if (context == null)
		return null;

	if (context.HttpContext.User == null)
		return null;

	AppMitarbeiter mitarbeiter = new AppMitarbeiter
	{
		Username = context.HttpContext.User.Identity!.Name!
	};

	foreach (var claim in context.HttpContext.User.Claims)
	{
		if (claim.Type.Equals(ClaimTypes.Role))
			mitarbeiter.Gruppen.Add(claim.Value);
		else if (claim.Type.Equals("employeeid", StringComparison.OrdinalIgnoreCase))
			mitarbeiter.PersonalNummer = Convert.ToInt32(claim.Value);
		else if (claim.Type.Equals("displayName", StringComparison.OrdinalIgnoreCase))
			mitarbeiter.DisplayName = claim.Value.ToString();
	}

	return mitarbeiter;
}
```

Now I inject this service to a blazor page as following:
```
public partial class Index
{
	AppMitarbeiter? mitarbeiter = null;

	protected override Task OnInitializedAsync()
	{
		mitarbeiter = mitarbeiterService.GetMitarbeiter();
		return base.OnInitializedAsync();
	}
}
```

When I start the app on my desktop and then login everything works fine as expected. But when I login from any mobile device, it crashes in this line of code:
`if (context.HttpContext.User == null)`

When I take a look on it then HttpContext is indeed null although it is not specified as a nullable reference type. Also the method gets called twice. The first time is has a valid HttpContext and in the second time it has not.

### Exceptions (if any)
System.NullReferenceException: "Object reference not set to an instance of an object."

Microsoft.AspNetCore.Http.IHttpContextAccessor.HttpContext.get hat null zurückgegeben.

### Further technical details
dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.100
 Commit:    5044b93829

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

Visual Studio 16.8.1

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

We don't recommend using HttpContext or IHttpContextAccessor within Blazor applications. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-5.0#blazor-and-shared-state) for details.

Instead, capture the information that you need from the request and pass it to the root component as a parameter on the first render.

**Comment by MarvinKlein1508** [comment]
Hi @javiercn 
Thanks for your fast reply.

How do I to transfer the data between a razor page and a razor component, is this even possible?

My problem is that I get this data from the HttpContext. How should I read the data instead?

**Comment by javiercn** [comment]
@MarvinKlein1508 [this example](https://github.com/javiercn/blazor-server-aad-sample) grabs tokens stored on a cookie from the request and makes them available to the blazor app.

You can follow the same approach with other data.

**Comment by MarvinKlein1508** [comment]
Alright, I have a service now which stores my data when I login. However, I need to get the data for a returning user again. 

I am still logged in when I close and open the browser but my data in service is gone (as expected). Where do I get this data from? I read on StackOverFlow to use the OnValidatePrincipal event for this within my ConfigureServices method. But this solution is using the HttpContext again.

`services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, configureOptions =>
{
	configureOptions.Events.OnValidatePrincipal = (context) =>
	{
		
		
		

		return Task.CompletedTask;
	};
});`

Have you any suggestion how I could solve this puzzle?

**Comment by MarvinKlein1508** [comment]
@javiercn 


My bad. Your example is very clear. It is working now. Thanks! 

Perhaps you should add this tutorial to the MSDN tutorial section. It was really helpful.

**Comment by javiercn** [comment]
It's already part of the docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app) but I guess it could be in a more prominent place.

**Comment by MarvinKlein1508** [comment]
@javiercn 
I would generalize the article about how to pass data to Blazor apps

**Comment by javiercn** [comment]
I filed an issue for tracking improvements [here](https://github.com/dotnet/AspNetCore.Docs/issues/20649) already.
