### ISSUE TITLE
.NET 5 Web API seems to be ignoring LogLevels

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#27905]
I have a simple .NET 5 Web API and wanted to set the `LogLevel` to `Trace` or `Debug` In order to get more detailed info. Used the [recommended ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0) code to setup a few extra provider and then changed the LogLevel with `SetMinimumLevel(LogLevel.Trace)` method:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureLogging(logger =>
		{
			logger.AddDebug()
			  .SetMinimumLevel(LogLevel.Trace);
		})
		.ConfigureWebHostDefaults(webBuilder =>
		{
			webBuilder.UseStartup<Startup>();
		});
```
**Also changed `appsettings.json` but no impact.**
```
"Logging": {
  "LogLevel": {
    "Default": "Trace",
    "Microsoft": "Warning",
    "Microsoft.Hosting.Lifetime": "Information"
  }
```

In my code I inject `ILogger<T>` as usually and writing logs. **But nothing shows only `Information` or above.** So it seems info level cannot be changed and ignored all config. 
Or am I setting it up wrong?

**Comment by javiercn** [comment]
@majorimi thanks for contacting us.

The more specific log levels (Microsoft, Microsoft.Hosting.Lifetime) override the default level, that's why they don't seem to be taking effect.

**Comment by majorimi** [comment]
@javiercn Thanks for your answer. 
I think specific log levels should be applied only when `<T>` type name is Microsoft* or something like that. But to be sure I have removed those log settings from `appsettings.json`.  So it look like this now:
```
  "Logging": {
    "LogLevel": {
      "Default": "Trace"
    }
```

**But no effect so I still can see only Information level logs.** I even completely removed the `Logging` section and no effect.

Not sure if it is an important detail? But **this application is a Blazor Server hosted app**. As I understand it is just a standard .NET MVC application with some SignalR and other stuff...

**Comment by Pilchie** [comment]
Do you have anything in `appsettings.Development.json`?

**Comment by majorimi** [comment]
Ah yeah... VS file nesting made it hidden. However usually I'm using environment variables...
Yes I had the same logging settings but Default was `Information`.

Cool now I can see all logs from Blazor Server in my [browser's console](https://github.com/majorimi/blazor-components/blob/master/.github/docs/ServerHostedLogging.md). Thanks.
