### ISSUE TITLE
Antiforgery fails and throws bad request for spa

### ISSUE THREAD

**Issue by naveendharnamoni** [dotnet/aspnetcore#27901]
I am trying to add anti-forgery to my asp.net core 3.1 web API by adding a filter in the startup file. 

`options => options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute())`

This web API is consumed by my angular app which is hosted in a different port. I have done all the configuration which is specified in docs as below.
In configure:
`app.Use(next => context =>
            {
                string path = context.Request.Path.Value;
                if (path != null)
                {
                    var tokens = antiforgery.GetAndStoreTokens(context);
                    context.Response.Cookies.Append("XSRF-TOKEN",
                      tokens.RequestToken, new CookieOptions
                      {
                          HttpOnly = false,
                          Path = "/",
                      }
                    );
                }
                return next(context);
            });`
In Services I have added as
`  services.AddAntiforgery(options =>
            {
                options.HeaderName = "X-XSRF-TOKEN";
            });`

It generates two tokens one is .Asp.NetCore.AntiForgery and XSRF-TOKEN. I am getting this token in my client app and sending it to API as request header as x-xsrf-token but it fails every time. I have setup my cors to allow any origin.

Let me explain to you my flow. I have an identity server, web API, and angular app all are hosted in different ports. The angular app redirects to the identity server for authentication once it's done it will be redirected back to my client app. I have set up this csrf in web api. so basically the authentication happens using a bearer token. I know that we don't need csrf protection because we already use bearer token as my authentication mechanism. But I need it to work for csrf as well. Is there any way to achieve this?

**Comment by javiercn** [comment]
@naveendharnamoni thanks for contacting us.

I would strongly discourage you from going this route and instead suggest that you use different endpoints depending on whether you are dealing with an API consuming json (protected by JWT) or an endpoint to handle form data (using CSRF).

That said, what's likely your issue is the fact that cookies are same-site.
