### ISSUE TITLE
Two-way bind is not work when updating the serialized child value within a same component i.e. GrandChildComponent

### ISSUE THREAD

**Issue by Naganathan** [dotnet/aspnetcore#27902]
1.	We have created a sample with parent-child-Grandchild components by using below data binding page. 
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0#bind-across-more-than-two-components 
 
2.	We have rendered the component as like as given below in our sample file ie. Index.razor. Where we have “GrandchildMessage” property given as two-way binding. 
 ```
<ParentComponent @ref="parentComponent"> 
    <ChildComponent ChildMessage="@childMessage"> 
        <GrandChildComponent @bind-GrandchildMessage="@grandChildMessage"></GrandChildComponent> 
    </ChildComponent> 
</ParentComponent> 
 ```
3.	We have a scenario to serialize and deserialize the component properties. So we used a System.Text.Json.JsonSerializer to serialize/deserialize the component.   
 
4.	Here, we have tried to change Grandchild component value within a razor file of serialized value to update into the current property value and handling it as two-way bind.   

[ParentComponent.razor]  
```
    public async Task Load() 
    { 
        ChildComponent child = System.Text.Json.JsonSerializer.Deserialize<ChildComponent>(data); 
       
         //Below code is used to update the child component parameter on the child component, and it is not working.         
       //Child = await Child.PropertyUpdate(child);   
       
       //Below code is used to update the child component parameter on the parent component, and it is working. 
        Child.GrandChildComponent.GrandchildMessage = await child.GrandChildComponent.UpdateProperty(child.GrandChildComponent.GrandchildMessage, Child.GrandChildComponent.GrandchildMessage, Child.GrandChildComponent.GrandchildMessageChanged); 
    } 
```
 [ChildComponent.razor] 
```
internal async Task<ChildComponent> PropertyUpdate(ChildComponent child) 
{  
    GrandChildComponent = await GrandChildComponent.PropertyUpdate(child.GrandChildComponent); 
    return this; 
} 
 ```
 
[GrandChildComponent.razor] 
```
internal async Task<GrandChildComponent> PropertyUpdate(GrandChildComponent grand) 
{ 
        GrandchildMessage = grandchildMessage = await UpdateProperty(grand.GrandchildMessage, GrandchildMessage, GrandchildMessageChanged); 
        return this; 
 } 
internal async Task<T> UpdateProperty<T>(T publicValue, T privateValue, EventCallback<T> eventCallback) 
{ 
        var finalValue = publicValue; 
        if (!EqualityComparer<T>.Default.Equals(publicValue, privateValue)) 
        { 
            await eventCallback.InvokeAsync(finalValue); 
        } 
        return finalValue; 
 } 
 ```
5.	So In the Parent Component, we tried to update the “GrandchildMessage” parameter of the GrandChildComponent through calling `PropertyUpdate` method of `GrandChildComponent`. The desterilized value set to the GrandchildMessage parameter. but it reset to previous value immediately.   
 
6.	But If we update the de-serialized Parameter of GrandChildComponent component value from root component ie. ParentComponent then it will be working fine instead of updating the same value within a grandchild component class. The below code example is we have used to update the serialized value within parent component. 
```    
public async Task Load() 
{ 
       ChildComponent child = System.Text.Json.JsonSerializer.Deserialize<ChildComponent>(data); 
       
       //Below code is used to update the child component parameter on the child component, and it is not working.         
       //Child = await Child.PropertyUpdate(child);   
       
       //Below code is used to update the child component parameter on the parent component, and it is working. 
        Child.GrandChildComponent.GrandchildMessage = await      child.GrandChildComponent.UpdateProperty(child.GrandChildComponent.GrandchildMessage, Child.GrandChildComponent.GrandchildMessage, Child.GrandChildComponent.GrandchildMessageChanged); 
} 
 ```
 
Please refer to the below attached sample. 
[Sample](https://github.com/dotnet/aspnetcore/files/5551950/BlazorApp1.zip) 
 
So could you please guide how to update the “GrandchildMessage” from `GrandChildComponent` component while updating deserialized values?

**Comment by javiercn** [comment]
Thanks for contacting us @Naganathan.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.
