### ISSUE TITLE
c#  BlazorWebAssembly net5.0 with AAD and PWA does nothing after logging but show "Completing Login ..."

### ISSUE THREAD

**Issue by peter-ferrier-occ** [dotnet/aspnetcore#27917]
Installed .net 5.0 and Visual Studio Preview.

Generated Blazor Web Assembly using Template provided with AAD connection and PWA checked.
Ran application and logged in.
I correctly used my login credentials but the app never seems to complete login action.
All I get is a "Completing login ..." message on the screen.
The app has not hung, it is responsive.
I can go to the other tabs or login over and over again.
I wrapped the Counter page in an Authorized attribute and updated the NavMenu.razor to hide or show the Counter tab.
It knows I am not logged in but never shows the Counter tab after logging in after giving the right credentials
If I use an incorrect password it does recognize that, just not the right one.
The Login Component never displays an Authorized View, just login.
I have ran this on multiple browsers:

Microsoft Edge Version 87.0.664.36 (Official build) beta (64-bit)
Opera Latest
Brave Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit) 

To reproduce this all I have to do is create a new project with the same Template, Blazor Web Assembly connected to AAD with PWA and get the same results. 

![image](https://user-images.githubusercontent.com/16689686/99452860-1ab1f900-28f2-11eb-80bb-f1385e1cd289.png)

I am using:

My Windows 10 is up to date as of today.

Visual Studio:

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 1.0
VisualStudio.16.Preview/16.9.0-pre.1.0+30709.64
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA213
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.128.44438
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2055207+87b6851d6bf3db12f59d3bd272dd0e635d31b20a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   16.9.128.44438
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.9.128.44438
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.128.44438
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.2000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.128.44438
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.2000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-1.20521.14+182c1e333b8514ac17dc463aac26b5552977a040
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.2000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.2000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.2000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.6 (8833fbf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Progress Telerik UI for Blazor Extension   2020.3.1111.1
Progress® Telerik® UI for Blazor Extension

Progress Telerik UI for WinForms Extension   2020.3.1016.1
Progress® Telerik® UI for WinForms Extension

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

Telerik Reporting Tools   3.44.8.0
Complete .NET Reporting Solution for Web, Mobile and Desktop Applications. For more information please visit http://www.telerik.com/reporting. 

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21028.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-1.20521.14+182c1e333b8514ac17dc463aac26b5552977a040
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

**Comment by javiercn** [comment]
@peter-ferrier-occ thanks for contacting us.

We'll take a look at this and get back to you.

**Comment by mrochon** [comment]
I am able to repro this issue by mis-configuring the app in AAD app registration. I get the infinite 'Completing login...' message if the app is not marked as Public Client. AAD/B2C returns then a 302 redirect as below:
`https://localhost:44356/authentication/login-callback#error=unauthorized_client&error_description=AADB2C90058%3a+The+provided+application+is+not+configured+to+allow+public+clients.%0d%0aCorrelation+ID%3...`

**Comment by gitback2work** [comment]
I think I had that problem before and if not mistaken it was because pop-ups were blocked and they opened in a separate tab. You could try getting it to open in a different browser perhaps to test.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
