### ISSUE TITLE
After NavigationManager.NavigateTo suceeded, an unhandled exception occured

### ISSUE THREAD

**Issue by ashokoienia** [dotnet/aspnetcore#27911]
I want in a blazor server side app by doubleclick on a data grid row open a new external page. I used NavigationManager.NavigateTo component. The navigation suceed and the page is open and works as expected but in my blazor app occures an unhandled exception. In bowser developer tools, there are some info as follows:

![image](https://user-images.githubusercontent.com/59563202/99417221-fa863800-28f9-11eb-8400-c269e03a198b.png)

Also here is my code:

```csharp
    void OnRowClick(DataGridRowClickEventArgs<AddressManData> args)
    {
        if (args.MouseEventArgs.Detail == 2)
        {
            int nKundenIndex = args.DataItem.lKundenIndex;

            if (nKundenIndex > 0)
            {
                try
                {
                    string strUri = "microsoft-edge:https://.../Anrufen.asp?lKundenIndex=";
                    strUri += nKundenIndex.ToString();

                    NavManager.NavigateTo(strUri);
                }
                catch (Exception ex)
                {
                    Console.Write(ex.Message);
                }
            }
        }
        else
        {

            grid.SetDataRowSelected(args.DataItem, true);
        }
    }
```

An important issue is that NavigateTo method do not cause any exception, and I'm a bit confused about the source of exception.
I used VS 2019 to develop this app and run it on IIS express on windows 10 and chrome browser.

Can anyone help me to solve this problem.

**Comment by javiercn** [comment]
@ashokoienia thanks for contacting us.

Can you give us more details about what version of ASP.NET Core are you using?

**Comment by ashokoienia** [comment]
@javiercn  thanks for replay.

My .NET Core SDK version is 3.1.403

**Comment by ashokoienia** [comment]
@javiercn  I must to tell you that the so-called unhandled exception is actually a part of default automatic genarated code for _Host.cshtml 
`       

         <environment include="Development">
                An unhandled exception has occurred. See browser dev tools for details.
          </environment>

        <a href="" class="reload">Reload</a>

        <a class="dismiss">🗙</a>

`

**Comment by mkArtakMSFT** [comment]
Thanks for the additional details. Can you please update to the latest 3.1 update (3.1.10) and see whether the error goes away? Thanks.

**Comment by ashokoienia** [comment]
@mkArtakMSFT Thanks for your reply. I updated visual studio 2019 with its installer tools to its recommended latest version 16.8.1 and now my dotnet version is 5.0.100, but unfotunatly the issue is still faulty

**Comment by mkArtakMSFT** [comment]
@ashokoienia have you updated the project too? Try to follow the .NET 5 migration guide to update properly: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio

**Comment by ashokoienia** [comment]
@mkArtakMSFT Thanks for your Notification, No, Not yet updated my project and didn't know that update 16.8 will cause to change framework. It seems and I fiel that this is not a good Idea that I migrate from .net core 3.1 to .net 5.
As I take a short look at link above, it can make a great work, is it true?

**Comment by ashokoienia** [comment]
@mkArtakMSFT , @javiercn Thanks All, Imigrate to .net 5, and It was not a greate Issue, and also my problem with NavigationManager seems to be solved.
I have to perform more tests but it seems to be solved.
Thanks
