### ISSUE TITLE
Component colorization colorizes unknown HTML elements that have directive attributes associated

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#27912]
![kEVzcEFWQ1](https://user-images.githubusercontent.com/2008729/99433830-dfe49c80-28c2-11eb-8427-9a3308a4f33d.gif)

**Comment by ryanbrandenburg** [comment]
I have a fix now. I actually did all of that super on purpose because I thought that we what we wanted, but I agree that this is more correct.
![image](https://user-images.githubusercontent.com/14987221/103388933-b5d8e980-4ac0-11eb-9192-1c165057a91e.png)

**Comment by NTaylorMullen** [comment]
If you have a fix, feel free to bring this issue into 16.9-Preview3

**Comment by ryanbrandenburg** [comment]
We want to use "IsAttributeMatch" on the Binding.
