### ISSUE TITLE
Upgrade from 3.1 to 5.0 causing issues in Blazor WASM

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#27910]
### Describe the bug
After following steps listed here https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio I am getting issues with my Blazor WASM app. When I run the app, the browser console is spammed with 496 errors saying the framework can't load required dll's.

e.g.
```
Failed to load resource: the server responded with a status of 404 () :44306/_framework/_bin/Microsoft.AspNetCore.Http.dll
Failed to load resource: the server responded with a status of 404 () :44306/_framework/_bin/Microsoft.EntityFrameworkCore.dll
Failed to load resource: the server responded with a status of 404 () :44306/_framework/_bin/Microsoft.EntityFrameworkCore.Abstractions.dll
```

The browser sources only has wasm and dotnet js files. No bin or _bin folder. The resources do exist on disk and can bit hit from the browser, although not served via:
```
https://localhost:44306/_framework/bin/wwwroot/_framework/_bin/Microsoft.AspNetCore.Http.dll
https://localhost:44306/_framework/bin/wwwroot/_framework/_bin/Microsoft.EntityFrameworkCore.dll
https://localhost:44306/_framework/bin/wwwroot/_framework/_bin/Microsoft.EntityFrameworkCore.Abstractions.dll
```

As you can see, the path here is different to what is being shown in the browser console. Is the framework targeting the wrong directory for these dll's are are they just not being served?

Client.csproj:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
	
</Project>
```

Server.csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

### Further technical details
- OS: Windows x64
- .NET SDK: 5.0.100
- IDE: Visual Studio 2019 16.8.1

**Comment by javiercn** [comment]
@ScottKane thanks for contacting us.

Remove your bin and obj folders and try again. We have an ongoing issue with version to version upgrades that we are fixing that affects incremental builds on version upgrades.

**Comment by ScottKane** [comment]
@javiercn I just tried but no luck, I was already on the latest SDK and VS versions and all packages are on the latest version.

**Comment by javiercn** [comment]
@ScottKane thanks for the additional details.

It might be that you have a shared project that is referenced between Server and Client and is bringing in additional dependencies?

From the logs you posted, seems like the app is trying to load assemblies that are typically associated with an ASP.NET Core app. while you don't seem to have any project reference on your client csproj file, I would double check.

The likely cause is that you are including those dependencies somewhere, so I would suggest tracking why
```csharp
https://localhost:44306/_framework/bin/wwwroot/_framework/_bin/Microsoft.AspNetCore.Http.dll
https://localhost:44306/_framework/bin/wwwroot/_framework/_bin/Microsoft.EntityFrameworkCore.dll
https://localhost:44306/_framework/bin/wwwroot/_framework/_bin/Microsoft.EntityFrameworkCore.Abstractions.dll
```
Also we would suggest you remove the reference to 
`<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />` as another potential source of issues.

**Comment by ScottKane** [comment]
I stripped the project files down for the sake of showing which wasm related packages I have but here they are in full:

Client:
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="3.0.0" />
    <PackageReference Include="Bogus" Version="31.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApp.Application\MyApp.Application.csproj" />
    <ProjectReference Include="..\MyApp.Components\MyApp.Components.csproj" />
    <ProjectReference Include="..\MyApp.Domain\MyApp.Domain.csproj" />
  </ItemGroup>
	
</Project>
```

Server:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyApp.Application\MyApp.Application.csproj" />
    <ProjectReference Include="..\MyApp.Client\MyApp.Client.csproj" />
    <ProjectReference Include="..\MyApp.Components\MyApp.Components.csproj" />
    <ProjectReference Include="..\MyApp.Infrastructure\MyApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
```

**Comment by ScottKane** [comment]
Also when I remove `<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />` the console errors jumps up from 496  to 797, so not sure what is going on there.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by ScottKane** [comment]
I figured out the issue, it was being caused by a publish profile I had set up in the server which was targeting `<publishUrl>bin\Release\netcoreapp3.1\publish\</publishUrl>`

**Comment by mkArtakMSFT** [comment]
Glad that you've found the issue. Closing as no further action is pending here.
