### ISSUE TITLE
Components not given an error once Component file is deleted

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#27913]
1. Create a component "Dingos.razor".
1. Add a reference to that component in an existing file.
1. Delete "Dingos.razor"
1. The reference to Dingos does not update with an error message for a non-existent component.
1. Make an edit to the file then wait a bit and it will update.

**Comment by TanayParikh** [comment]
Note; this'll fall under Razor Push Diagnostics, and likely impact VSCode as well.
