### ISSUE TITLE
Consider C# 9 top-level statements for Design-time DbContext Creation

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/aspnetcore#27923]
I migrated to .NET 5 and tried to use top-level statement for my `Program` class. Unfortunately, EF Core's migration got broken because it was not able to detect the top-level `Program`.

It would be nice if EF Core would detect the top-level `Program`.

See also https://docs.microsoft.com/en-us/ef/core/cli/dbcontext-creation
> The tools first try to obtain the service provider by invoking `Program.CreateHostBuilder()`, calling `Build()`, then accessing the `Services` property.

**Comment by davidfowl** [comment]
I think the answer will the same in the end, that code will need to detect this new pattern if we think this will be common.

**Comment by OskarKlintrot** [comment]
Did someone create a new issue we can vote on?

**Comment by bugproof** [comment]
Simple solution: Don't use Entity Framework :trollface:

**Comment by DamianEdwards** [comment]
Note that this is being fixed as part of .NET 6

**Comment by adityamandaleeka** [comment]
Triage: this is done.
