### ISSUE TITLE
Slow termination for executables using the signalR-client-c++ library on linux.

### ISSUE THREAD

**Issue by mprather** [dotnet/aspnetcore#27928]
### Describe the bug
The signalR c++ library takes a long time to complete cleanup/termination for linux compilations. After the main program stops, there's an additional 2 minutes where the signalr library continues to utilize the process.

### To Reproduce
The following code illustrates the problem.
```
int main() {

  // The hub is fully operational and works as expected. 
  signalr::hub_connection connection = signalr::hub_connection_builder::create("http://192.168.0.52:5000/hubs/live").build();

  std::promise<void> startTask;

  std::cout << "calling start\n";
  connection.start([&startTask](std::exception_ptr exception) {
    startTask.set_value();
  });  // End of start

  startTask.get_future().get();

  std::promise<void> stopTask;

  std::cout << "calling stop\n";

  connection.stop([&stopTask](std::exception_ptr exception) {
    stopTask.set_value();
  });  // End of stop

  stopTask.get_future().get();

  std::cout << "finished\n";

  return 0;
}
```

When run on Ubuntu 18.04, compiled with gcc 7.3, the following results are produced.
command line --> time ./sender ;date

The log output shows last entry made by the signalR library. Time shows total run time and the date command shows when application finished.

```
2020-11-18T01:51:17Z [info        ] [websocket transport] connecting to: ws://192.168.0.52:5000/hubs/live?id=UPNCDLRF8TiIBtjdd400EA
2020-11-18T01:51:17Z [info        ] sending data: {"protocol":"json","version":1}
calling stop
2020-11-18T01:51:17Z [info        ] stopping connection
2020-11-18T01:51:17Z [info        ] acquired lock in shutdown()
2020-11-18T01:51:17Z [info        ] Connection closed.
finished
2020-11-18T01:**51:17**Z [info        ] acquired lock in shutdown()  <---- this is the last output by the signalr logger

real    2m0.006s                                 <---- time command shows the app run time
user    0m0.015s
sys     0m0.011s
Tue Nov 17 17:**53:17** PST 2020    <---- two minutes later the application is terminated (output from date command)
```

This ~2 minute lag is consistent across multiple applications and build types (debug/release). We have noticed that the lag may vary slightly but have not been able to determine what influences the difference.

On windows, the application closes immediately after the return statement is hit.

### Further technical details
- signalr c++ version:  0.1.0-alpha1-1
- OS: Ubuntu 18.04
- Compiler: gcc 7.3

**Comment by mprather** [comment]
It appears this problem stems from the sleep call in default_http_client.cpp. In the send method, line 53, the thread is paused for 2 minutes (per the default values set by http_request class).

**Comment by glapointe** [comment]
I agree with @mprather that this is a problem. We have unit tests that would normally only take a few seconds to run but on linux they don't complete until the full 2 minutes has passed. Also, for the near real-time systems that we're developing we need the process to exit gracefully when everything is complete which again, might be in just a few seconds, but with the sleep in place we don't get a valid closure until the 2 minutes have passed which is causing other issues with the application.

**Comment by BrennanConroy** [comment]
Fixed with https://github.com/aspnet/SignalR-Client-Cpp/pull/37
