### ISSUE TITLE
Conditionally pass renderfragments to components

### ISSUE THREAD

**Issue by lindespang** [dotnet/aspnetcore#27924]
### Is your feature request related to a problem? Please describe.
I'm trying to conditionally pass renderfragments to a component using `@if` blocks but I get the build error
`Unrecognized child content inside component 'AwesomeComponent'`

**Parent.razor**
```
<AwesomeComponent>

    <ItemTemplate>
        // some code here
    </ItemTemplate>

    <AnotherItemTemplate>
        // blabla
    </AnotherItemTemplate>

    // This one i want to pass conditionally, the intuitive way is like this
    @if (condition)
    {
        <YetAnotherItemTemplate>
            // wooho
        </YetAnotherItemTemplate>
    }


</AwesomeComponent>
```

**AwesomeComponent.razor**
```
<h1>AwesomeComponent</h1>

@code
{
    [Parameter] public RenderFragment ItemTemplate {get; set;}
    [Parameter] public RenderFragment AnotherItemTemplate {get; set;}
    [Parameter] public RenderFragment YetAnotherItemTemplate {get; set;}
}
```
### Describe the solution you'd like
I would like it to work like in the example above.

### Additional context
The current workaround is either to pass a bool prop to tell `AwesomeComponent `to which fragments has been 'passed' or not, which I think is quite ugly - or to move the `if `statement outside and conditionally render two different `AwesomeComponent`. This workaround is not feasible if you have more than one renderfragment you want to pass conditionally.

**Comment by stefanloerwald** [comment]
Adding to this: the syntax allows `<AwesomeComponent ItemTemplate="(RenderFragment)null">`, but this fails at runtime due to https://github.com/dotnet/aspnetcore/issues/23892

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We recommend using a function which would return the render fragment you'd like to set and set the render fragment to the result of that function instead. Then the function will contain the conditional logic.

**Comment by stefanloerwald** [comment]
I'm not sure I understand the advice correctly, @mkArtakMSFT. Are you suggesting to move the conditional logic into the RenderFragment? If so, I don't think that's a sufficient solution.
E.g. a component implemented as

```xml
<h1>Number of non-null fragments: @((A != null ? 1 : 0) + (B != null ? 1 : 0) + (C != null ? 1 : 0))</h1>

@code
{
    [Parameter] public RenderFragment A{get; set;}
    [Parameter] public RenderFragment B{get; set;}
    [Parameter] public RenderFragment C{get; set;}
}
```

I have a use-case, where there may or may not be buttons visible, depending on the RenderFragments provided. I got by using a static pseudo-Null RenderFragment, but what @lindespang is suggesting wrt syntax would actually be much nicer.

**Comment by lindespang** [comment]
@mkArtakMSFT Unless I misunderstood, this will still lead to the fragment having a non-null value in `AwesomeComponent`? If so, the fragment is still technically passed.

If you have the time I would be grateful for a minimal example!

**Comment by stefanloerwald** [comment]
Could someone please teach @msftbot that closing issues which received comments after being marked "resolved" so quickly isn't exactly good style?

**Comment by stefanloerwald** [comment]
Could this please be re-opened so that it doesn't fall off the radar?
