### ISSUE TITLE
Blazor Title Component missing from the official docs

### ISSUE THREAD

**Issue by fingers10** [dotnet/aspnetcore#27926]
I remember seeing a `<Title>` component in Microsoft official blazor docs few months ago which was documented as an easy way to change HTML Title element value in each screen when the ASP.NET Core 5 was in preview or RC state . But now when I search for the same in the docs I'm not able to find it. 

I have posted this `<Title>` component as an solution in the following StackOverflow post - [How to set page title in blazor](https://stackoverflow.com/a/64020268/10851213)

Please can you let me know if this was missed in docs or this component was dropped in ASP.NET Core 5.0 release?

**Comment by javiercn** [comment]
@fingers10 thanks for contacting us.

We had some concerns about the API and the implementation and I believe we ended up not shipping it since we wanted to polish the component a bit more.

@danroth27 feel free to add more details.

**Comment by fingers10** [comment]
@javiercn  thanks for the inputs. Any info on when can we expect this API?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will be tracking that work as part of #25705
