### ISSUE TITLE
Grpc - implement a built-in mechanism/configuration to map existing WCF classes

### ISSUE THREAD

**Issue by hcanand** [dotnet/aspnetcore#27934]
Rewriting existing WCF ServiceContracts (Services) & DataContracts (Messages) classes to match their equivalent gRPC counterparts (defined in *.proto files) is a lot of efforts for people already invested in WCF and which are in production.

I would highly recommend Microsoft to implement a built-in mechanism/configuration to map existing classes, similar to the implementation done in the following link:

[https://github.com/protobuf-net/protobuf-net.Grpc]

This would greatly save tons of efforts required

**Comment by JamesNK** [comment]
We don't have any plans to do this. Like you said, there is already a way to do this that is offered by protobuf-net.Grpc.

**Comment by hcanand** [comment]
> We don't have any plans to do this. Like you said, there is already a way to do this that is offered by protobuf-net.Grpc.

It would have been better, if MS had it buit-in...since third-party's maintenance might be stopped without any notice.

**Comment by hcanand** [comment]
Atleast is there anyway, we could define protos with common messages and services in an assembly and reuse them across one or more projects?
