### ISSUE TITLE
HtmlContentBuilderExtensions.AppendFormat nullability is incorrect

### ISSUE THREAD

**Issue by ChristofferGersen** [dotnet/aspnetcore#27936]
### Describe the bug
`Microsoft.AspNetCore.Html.HtmlContentBuilderExtensions.AppendFormat` should accept nullable objects inside the `args` params array. So the `args` argument should change for both overloads from `params object[] args` to `params object?[] args`.
As a result, `Microsoft.AspNetCore.Html.HtmlFormattableString` also needs to change the type of its `args` constructor argument and `_args` field to `object?[]`. The `EncodingFormatProvider` class already handles null values (it is formatted as `string.Empty`), because the `ICustomFormatter` interface specifies that an `arg` may be null.

Of course I can work around this issue for now using the null-forgiving operator (!).

### To Reproduce
Current use case is adding an `AppendFormattable` extension function, to allow using `FormattableString` with an `IHtmlContentBuilder`. The problem is that `GetArguments()` returns an `object?[]`.
```
public static class HtmlContentBuilderExtensions
{
  public static IHtmlContentBuilder AppendFormattable(this IHtmlContentBuilder builder, FormattableString format)
  {
    return builder.AppendFormat(format.Format, format.GetArguments());
  }

  public static IHtmlContentBuilder AppendFormattable(this IHtmlContentBuilder builder, IFormatProvider formatProvider, FormattableString format)
  {
    return builder.AppendFormat(formatProvider, format.Format, format.GetArguments());
  }
}
```

### Exceptions (if any)
This currently results in the following compilation warning when nullability analysis is enabled.
```warning CS8620: Argument of type 'object?[]' cannot be used for parameter 'args' of type 'object[]' in 'IHtmlContentBuilder HtmlContentBuilderExtensions.AppendFormat(IHtmlContentBuilder builder, string format, params object[] args)' due to differences in the nullability of reference types.```

### Further technical details
ASP.NET Core version: 5.0.0
.Net SDK version: 5.0.100
VS version: 16.8.1

**Comment by javiercn** [comment]
@ChristofferGersen thanks for contacting us.

We'll take a look at this and see what we can do.

@pranavkm is there any centralized place where we will be tracking nullability fixes for 6.0?
