### ISSUE TITLE
NavigationManager incorrectly resolved from root scope during Options configuration.

### ISSUE THREAD

**Issue by jspuij** [dotnet/aspnetcore#27937]
### Describe the bug

Tagging @javiercn as discussed through email:
During adaptation of WebAssembly Authentication for Xamarin Mobile Blazor Bindings we found the following issue:

WebAssembly authentication seems adds the default (post configure) options as singletons. However one of these (the first) takes a dependency on NavigationManager, which is scoped. This seems to be OK for WebAssembly as there is no scope other than the root scope. We do create scopes in MBB however (because the WebView can be added as a component, but also subsequently removed and readded), which leads to a new NavigationManager being resolved from the root scope (and then not being initialized properly). There does not seem to be any harm in registering this one as scoped, and I’d argue it would be better because it’s strange for a Singleton to be able to take a dependency on a scoped service. (Not sure why container validation did not catch it).

https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L118
https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L206

As a result of this, RemoteAuthenticationService should take IOptionsSnapshot<>  instead of IOptions<> as a parameter, otherwise the options (and dependencies) will still be resolved from the root scope:
https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs#L64

And idem for DefaultRemoteApplicationPathsProvider:
https://github.com/dotnet/aspnetcore/blob/648c15dbe90fb8c113f7c6b4adeb40d9e10494f6/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/DefaultRemoteApplicationPathsProvider.cs#L13

I will create a PR to correct this.

### To Reproduce

See PR for unit test.

**Comment by javiercn** [comment]
@jspuij thanks for filing the issue.

Looking forward to review your PR.
