### ISSUE TITLE
cshtml: RazorRuntimeCompilation and "Nullable type parameter" Exception 

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#27940]
I've attached a very self explaining project to demonstrate the exception:
Relevant Code: https://github.com/alienwareone/RazorNullableTypeParameterSample/blob/master/Views/Home/Index.cshtml
Project Repo: https://github.com/alienwareone/RazorNullableTypeParameterSample

Exception:
`A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.`

Version:
ASP.NET Core 5.0

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
