### ISSUE TITLE
Add possibility to use RequireHost on specific ApiController during configure

### ISSUE THREAD

**Issue by bjornen77** [dotnet/aspnetcore#27958]
When using [ApiController] it would be good if you can use the RequireHost() extension method on specified controller. For example if you have some AdminControllers, that should only be accessible from a specific host:

app.UseEndpoints(endpoints =>
 {
     endpoints.MapControllers();

     // Require specified host(from configuration) on a specific controller
     endpoints.MapControllers(Name = "AdminController").RequireHost($"*.{Configuration["AdminPort"]}");
 }

I know that the HostAttribute exist, but with that the host value cannot be fetched from configuration as far as I know. 

Maybe there should be other ways of selecting controllers instead of name.

Perhaps there is other ways of solving this? I am thinking about custom middleware, custom policy or if it is possible to add a HostAttribute with host value from configuration to a specified controller during startup?

Other endpoints, like MapHealtChecks could be configured using RequireHost according to documentation:

`
endpoints.MapHealthChecks("/health").RequireHost($"*:{Configuration["ManagementPort"]}");
`

It would be good if something like this was available also for user specified ApiControllers.

**Comment by javiercn** [comment]
@bjornen77 thanks for contacting us.

This is already possible, just place the `HostAttribute` in the controllers you care about. If you need to do it programatically, you can do so through an application model convention. See [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-5.0#conventions) for details

**Comment by bjornen77** [comment]
@javiercn Thank you for your answer. I looked through the application model convention docs and it seems to cover my use case since I need to do this programatically. Thanks again!
