### ISSUE TITLE
Survey: Repo contribution experience, Fall 2020

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/aspnetcore#27967]
We normally focus on how to improve the product, but we’re also turning our focus to improving the open source project. Periodically we are running a survey to collect feedback on your experience working with our repos. We did one back in May, and as its been about 6 months, its about time for another. We’ve created a survey to better understand your individual experience of participating and contributing in this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. 

Survey

Thank you for your time!

**Comment by wtgodbe** [comment]
@Pilchie should we do anything to get more customer eyes on this? Maybe make an announcement?

**Comment by Pilchie** [comment]
@captainsafia got the aspnet twitter account to tweet about it, I think between that and the pinning we've probably hit most of the people we want.  I don't want to spam announcements for this.

**Comment by samsp-msft** [comment]
The survey is now closed. Thank you to everyone who provided feedback. I have removed the link from the first post.
