### ISSUE TITLE
[Blazor] CSS Isolation - 3rd party components

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#27965]
Hi,

I have a component that contains a 3rd party component styled with Boostrap class ``form-control`` that I'd like to modify using the built-in CSS isolation.

MyComponent.razor:
```
<div class="filter-tag-box">
   <ThirdPartyComponent /> @*this component has a div referencing form-control class*@
</div>
```

MyComponent.razor.css
```
.filter-tag-box .form-control
    border-bottom: none;
}
```

After the project is built, final ``MyProject.style.css`` file contains this section:
```
/* FilterTagBox.razor.rz.scp.css */
.filter-tag-box .form-control[b-lzq9nmge8o] {
    border-bottom: none;
}
```

Obviosuly, this is not going to work. What I'm looking for is this:
```
/* FilterTagBox.razor.rz.scp.css */
.filter-tag-box[b-lzq9nmge8o] .form-control {
    border-bottom: none;
}
```

Is this a bug/limitation of Blazor? I know can create the desired effect by modifying my global ``app.css`` file but I'd rather take advantage of CSS isolation if possible.

Thanks.

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

You can use the `::deep` pseudo-selector for that.

```css
.filter-tag-box ::deep .form-control
    border-bottom: none;
}
```

will produce the output you are looking for. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support) for details
