### ISSUE TITLE
[Blazor WASM] Cache busting

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#27966]
Hi,

How can I implement proper cache busting in Blazor? As I'm developing my app, I keep clearing my browser cache after each build to ensure that I have the most recent copy of all css/js/etc resources. This is quite annoying and time consuming.

Thanks.

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

Blazor dlls are correctly cache busted already, for CSS, JS and other resources you can either devise your own strategy using a query string or something similar to force the resource to be fetched again (there's no built-in mechanism for that in blazor) or you can add a bit of middleware in the pipeline to add a cache response header  with `no-cache no-store must-revalidate` during development. Like:

```
app.Use((ctx,next) => {
   if(extensions.Contains(Path.GetExtension(ctx.Request.Path)) {
     ctx.Response.Headers["Cache"] = "no-store, no-cache, must-revalidate";
   }

   return next();
}
```
