### ISSUE TITLE
SignInManager has hard coded Schemes

### ISSUE THREAD

**Issue by Shazwazza** [dotnet/aspnetcore#27979]
## Summary

The SignInManager has hard coded Schemes which are very difficult to change even if you subclass the SignInManager. It would be a relatively easy change to allow inheritors to change these hard coded schemes to what they want. It also seems that the `IAuthenticationSchemeProvider` is only used to resolve external schemes but perhaps it could/should be used to `GetDefaultAuthenticateSchemeAsync()` instead of using the hard coded `IdentityConstants.ApplicationScheme` ? (maybe that's not what `GetDefaultAuthenticateSchemeAsync()` is intended for so not too sure on that one)

## Motivation and goals

Like many things in aspnetcore, it is opinionated that things that are global are the way they need to be but this opinion doesn't cater for having multi-tenancy application setup. For example, the Umbraco CMS has back office Users and front-end Members. They don't share the same data storage/services at all because they are entirely different. You can log in as a back office user separately than a front-end member. There will be different cookies and authentication schemes working in tandem. Further, for front-end Umbraco members we don't want to get in the way of the end-user's potential default aspnetcore membership setup. This can happen because the Umbraco CMS doesn't get in the way of any existing website implementation. So in this scenario there can be up to 3x SignInManager (2 subclassed so they are unique services in DI). 

We have this working but the amount of code to replace the hard coded schemes is pretty huge where it would be pretty easy to just have virtual properties to override for these hard coded scheme names, or have another service injected that returns these schemes. 

* IdentityConstants.ApplicationScheme
* IdentityConstants.ExternalScheme
* IdentityConstants.TwoFactorUserIdScheme
* IdentityConstants.TwoFactorRememberMeScheme

It would be super easy to create a PR with these things as virtual properties to override and happy to do that but let me know what you think. I realize this isn't a typical type of thing that most websites do but there's a lot of hoops we've had to jump through to make things work that are globally unchangeable that could be very easily made more flexible (i.e. https://github.com/dotnet/aspnetcore/issues/22217)

**Comment by blowdart** [comment]
Identity is not designed for, and has never been designed for multi-tenancy.

There is a [wider issue](https://github.com/dotnet/aspnetcore/issues/27465) around multi-tenancy that would be the best place to start, as it looks at the issue from a wider aspnet perspective, rather than trying to shoehorn individual components as we've been doing before, which hasn't really worked.

**Comment by Shazwazza** [comment]
@blowdart thanks for the reply. Yep I agree, have been shoehorning things around identity for years 😂 I realize it's not designed for multi-tenancy but people are still doing such things which either requires some zany work arounds or just copying code. Small updates to make parts more flexible (i.e. not hard coding schemes) would be immediately helpful since it seems like any redesign and implementation about multitenancy is a long way away.

For any folks interested, if you want to have a SignInManager with custom schemes to replace the hard coded ones, you will need to override and copy the code from the source for these methods (it's not quite all of the SignInManager but it's a good chunk):

* `GetTwoFactorAuthenticationUserAsync` & `TwoFactorRecoveryCodeSignInAsync` 
  * copy/modify the private method `RetrieveTwoFactorInfoAsync` containing the hard coded schemes
* `TwoFactorSignInAsync` 
  * copy/modify the private methods `RetrieveTwoFactorInfoAsync`, `DoTwoFactorSignInAsync` containing the hard coded schemes
  * copy the private class `TwoFactorAuthenticationInfo` since its not public
* `IsSignedIn`
* `RefreshSignInAsync`
* `SignInWithClaimsAsync`
* `SignOutAsync`
* `IsTwoFactorClientRememberedAsync`
* `RememberTwoFactorClientAsync`
  * copy/modify the private method `StoreRememberClient` containing the hard coded scheme
* `ForgetTwoFactorClientAsync`
* `GetExternalLoginInfoAsync`
* `SignInOrTwoFactorAsync` 
   * copy/modify the private method `IsTfaEnabled` since it's not public
  * copy/modify the private method `StoreTwoFactorInfo` containing the hard coded scheme

Just being able to have properties to override these schemes would save all of this code duplication.

**Comment by halter73** [comment]
This also looks related to #17232 which I believe has been addressed in .NET 8 as part of #47232 and the introduction of [`SignInManager<TUser>.AuthenticationScheme`](https://github.com/dotnet/aspnetcore/issues/47232#issuecomment-1683086875). I'm going to close this, but if you disagree, please comment on #17232.
