### ISSUE TITLE
Support coverage of RoslynNexusTests and RazorNexusTests in cloud environment

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#27973]
Currently we make calls such as 
```C#
WaitForOperationsInProgress(); <- this will fail in cloud environment
WaitForAllOperations();
```
inside the Launch method to figure out when things are "ready". This won't work once those tests are being run in a multi-machine scenario, so we'll have to switch to using a brokered service.

We'll also have to use such a brokered service to gather the Razor logs (inside the cleanup method) which are currently just copied from a file we happen to have on disk.

**Comment by ryanbrandenburg** [comment]
@NTaylorMullen do we still need this?

**Comment by NTaylorMullen** [comment]
Definitely not! Close it out 😉
