### ISSUE TITLE
the way to get connected/disconnect state android client native

### ISSUE THREAD

**Issue by fukemy** [dotnet/aspnetcore#27977]
Hello, im using your lib follow this https://github.com/aspnet/SignalR-samples/blob/master/AndroidJavaClient/app/src/main/java/com/microsoft/aspnet/signalr/samples/androidjavaclient

 But i only see the connect and get hub data function, i want to ask is there have some way to get connected/disconnect callback, or auto reconnect state....? 
 Thanks

**Comment by BrennanConroy** [comment]
You can take a look at the docs https://docs.microsoft.com/aspnet/core/signalr/java-client?view=aspnetcore-5.0 for more info. And also the API docs https://docs.microsoft.com/en-us/java/api/com.microsoft.signalr?view=aspnet-signalr-java&viewFallbackFrom=aspnetcore-5.0 to see what methods are available. Note: auto-reconnect is not implemented in the Java client currently.
