### ISSUE TITLE
ToRfc1123String fails as InplaceStringBuilder from Microsoft.Extensions.Primitives has been removed in v5.0.0

### ISSUE THREAD

**Issue by dsun-ugl** [dotnet/aspnetcore#27986]
### Describe the bug
The method ToRfc1123String fails with Microsoft.Extensions.Primitives v5.0.0 as the method InplaceStringBuilder has been removed. Workaround is to downgrade to Microsoft.Extensions.Primitives v3.1.10

### To Reproduce
Execute 
`Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)`
e.g.
`(HTTPContext)context.Response.WriteAsync("some sort of string");`

### Exceptions (if any)
See the call stack

> System.TypeLoadException
>   HResult=0x80131522
>   Message=Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
>   Source=Microsoft.Net.Http.Headers
>   StackTrace:
>    at Microsoft.Net.Http.Headers.DateTimeFormatter.ToRfc1123String(DateTimeOffset dateTime, Boolean quoted) in /_/src/Microsoft.Net.Http.Headers/DateTimeFormatter.cs:line 65
>    at Microsoft.Net.Http.Headers.HeaderUtilities.FormatDate(DateTimeOffset dateTime, Boolean quoted) in /_/src/Microsoft.Net.Http.Headers/HeaderUtilities.cs:line 592

Which then propagates up the call stack like so

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Microsoft.AspNetCore.Server.Kestrel.Core
>   StackTrace:
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)

### Further technical details
- ASP.NET Core version 
- Include the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
>  Version:   5.0.100
>  Commit:    5044b93829
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.16299
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.100\
> 
> Host (useful for support):
>   Version: 5.0.0
>   Commit:  cf258a14b7
> 
> .NET SDKs installed:
>   2.1.602 [C:\Program Files\dotnet\sdk]
>   2.1.700 [C:\Program Files\dotnet\sdk]
>   2.1.701 [C:\Program Files\dotnet\sdk]
>   2.1.801 [C:\Program Files\dotnet\sdk]
>   2.2.300 [C:\Program Files\dotnet\sdk]
>   3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
>   5.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

> Microsoft Visual Studio Professional 2019
> Version 16.8.1

**Comment by dsun-ugl** [comment]
From a quick look at the code, it appears the only change that needs to be done is to change

```
public static string ToRfc1123String(this DateTimeOffset dateTime, bool quoted)
        {
            var universal = dateTime.UtcDateTime;

            var length = quoted ? QuotedRfc1123DateLength : Rfc1123DateLength;
            var target = new InplaceStringBuilder(length);

            if (quoted)
            {
                target.Append(Quote);
            }
...
```

to 

```
public static string ToRfc1123String(this DateTimeOffset dateTime, bool quoted)
        {
            var universal = dateTime.UtcDateTime;

            var length = quoted ? QuotedRfc1123DateLength : Rfc1123DateLength;
            var target = new StringBuilder(length);

            if (quoted)
            {
                target.Append(Quote);
            }
...
```


and of course
`using System.Text;`

**Comment by Tratcher** [comment]
DateTimeFormatter.ToRfc1123String was [removed](https://github.com/dotnet/aspnetcore/pull/5695) a long time ago, that code isn't in 5.0. I think you're mixing dependency versions. Can you share the dependencies section from your csproj?

**Comment by Tratcher** [comment]
You should probably not be referencing the Microsoft.Extensions.Primitives package directly regardless, that's part of the runtime since 3.0.

**Comment by dsun-ugl** [comment]
So with that revelation, I have discovered that Microsoft.AspNetCore.Server.Kestrel.Core dependency Microsoft.Net.HttpHeaders is listed as minimum V2.2.0(12/4/2018) which contains the old code using ToRfc1123String. I have tried to remedy this by explicitly installing the latest version of Microsoft.Net.HttpHeaders (v2.2.8)(11/19/2019) but the problem persists.

Looking at the commit tagged v2.2.8 
https://github.com/dotnet/aspnetcore/blob/7ab32c8411f40e63984c5963b79722c1f2fd9d8a/src/Http/Headers/src/HeaderUtilities.cs#L592
it seems that the aforementioned commit where ToRfc1123String is removed is not part of that update.

Would this be considered an issue with the nuget package not having been updated for a while? I'm not quite familiar with your process of having changes published on nuget.

This is now the current state of dependencies.
![image](https://user-images.githubusercontent.com/74720773/99764327-eab46100-2b50-11eb-9e09-c71ccd5066fc.png)

**Comment by Tratcher** [comment]
What is your projects target framework version? net461, netcoreapp2.2, net5.0? Many of those packages stopped being produced after the 2.2 release, they were bundled together into a shared framework install. If you're targeting netcoreapp3.0 or later then remove any reference to a package with a version of 2.2.

If you really are targeting net461 or netcoreapp2.2, don't try to use packages from higher versions.

**Comment by dsun-ugl** [comment]
I am targeting net5.0
I wish to use webhostbuilder and other associated extensions, but they cannot be found unless I install the nuget packages.
Either Microsoft.AspNetCore.Hosting or Microsoft.AspNetCore.Server.Kestrel

namely
```
new WebHostBuilder()
                .UseKestrel()
                .UseUrls(_url)
                .Configure(Configure)
                .Build();
```

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#remove-obsolete-package-references

Make sure your SDK is set to `<Project Sdk="Microsoft.NET.Sdk.Web">` in your csproj. Then remove all of those packages.

**Comment by Vossekop** [comment]
I am having the same issue. However, I cannot just target the other SDK, I want a console application. What is the best way to go about this issue in that situation?

**Comment by dsun-ugl** [comment]
So my original sdk was `Microsoft.NET.Sdk.WindowsDesktop` as it's a WPF app. It turns out that as of .NET5.0, the sdk should be  `Microsoft.NET.Sdk`.

My program builds successfully with `Microsoft.NET.Sdk,Web`, but I thought I should avoid any un-intended consequences by just using
```
 <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```
Instead of the entire web sdk.

So looks like the crux of this 'issie' was just incorrect referencing on my part. Thank you for the help though!
