### ISSUE TITLE
Add ability to createObjectURL from IBrowserFile

### ISSUE THREAD

**Issue by sps014** [dotnet/aspnetcore#27983]
## Problem 
Currently `InputFile` Component is missing ability to generate URL from byte[],
suppose I read a video stream , 

most people will hack it like this to display as video source
```cs
var videoDataUrl = 
                $"data:{format};base64,{Convert.ToBase64String(buffer)}";
```
this is really a redundant conversion and is extremely slow for videos and large files.

## Fast Way

we can do better for high performance gain with Unmarshalled Calls
```js
createObjectURL: (data,name,type) => {
            const contentArray = Blazor.platform.toUint8Array(data);
            const nameStr = BINDING.conv_string(name);
            const contentTypeStr = BINDING.conv_string(type);

            const file = new File([contentArray], nameStr, { type: contentTypeStr });

            return BINDING.js_to_mono_obj(URL.createObjectURL(file));

        }
```

###  ideal API 

something like this should be a built in to `IBrowserFile`

```cs
async void fileLoad(InputFileChangeEventArgs v)
    {
        var file = v.GetMultipleFiles()[0];
        var vidURL=file.CreateObjectURL("g.mp4");
 //can be something like this so users don't have to write Unmarshalled Call everytime
    }
```
This `CreateObjectURL` can be implemented in
https://github.com/dotnet/aspnetcore/blob/e0467560e11a739897521326b543e9652a4edb77/src/Components/Web/src/Forms/InputFile/BrowserFile.cs#L10

**Comment by javiercn** [comment]
@sps014 thanks for contacting us.

We'll gather more feedback on this issue and consider what we can do here in the future.

**Comment by njannink** [comment]
Make sure that the returned URL wrapper contains a IDisposeAsync implementation to cleanup the reserved Object URL

**Comment by amis92** [comment]
Am I correct that this won't be a feature - we've now got an example solution in the docs instead? https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=server#upload-image-preview

**Comment by TanayParikh** [comment]
That's correct.
