### ISSUE TITLE
Add Blazor specific analyzers configuration

### ISSUE THREAD

**Issue by marek-safar** [dotnet/aspnetcore#27989]
We'd like to enable roslyn analyzers which are based in dotnet/runtime or other dotnet/* repos for AOT and non-AOT Blazor workloads and are not in the default analyzers set. The combination of which analyzers will be enabled by default is expected to be different for different configurations. There does not seem to be the right place to do that today.

**Comment by mkArtakMSFT** [comment]
@lewing is there work that you plan to do here? Should we close this?

**Comment by mkArtakMSFT** [comment]
Talked to @marek-safar about this offline. Closing.
