### ISSUE TITLE
Blazor WASM -> edge worker deployment

### ISSUE THREAD

**Issue by leebenson** [dotnet/aspnetcore#27982]
IMO, a really exciting middle ground between a hosted Blazor WASM deployment, and a pure static deployment, would be to take advantage of V8-based edge hosting, a la Cloudflare Workers, or StackPath's Serverless Scripting.

These each offer a very compelling hosting proposition: Pay a low fee (typically ~$0.60 per 1M requests), with 40-150+ PoPs serving a request in 20-50ms, closest to your user.

With these V8 edge workers allowing WASM, this makes them ideal candidates for fast/cheap pre-rendering, without deploying VMs or choosing an individual geographic zone.

(Incidentally, this feels like a great option for Azure, if a competing service isn't currently offered!)

Is there a known path for deploying WASM to one of these providers? I imagine what we'd need would be something like

- All .dlls compiled into a single WASM, rather than runtime + ad hoc loading, aka self-contained, AoT compilation.
- Bootstrapping contained within the WASM, to avoid having to run the .js loaders
- An option to return a string of the resulting HTML rather than insert into the DOM (maybe `WebAssemblyHostBuilder.RootComponents.ToString()` already provides this?)

Is there a way today to achieve the above?

If not, is it on the roadmap?

Thanks in advance!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, we don't have any immediate plans in this space.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

/cc @richlander

**Comment by danroth27** [comment]
@davidfowl @glennc
