### ISSUE TITLE
MSB6004	The specified task executable location "C:\Program Files\dotnet\dotnet" is invalid.	Blazor

### ISSUE THREAD

**Issue by eghsr** [dotnet/aspnetcore#27990]
# Issue Title

Getting error MSB6004 after updating to VS 16.8.1 and creating a new blazor server app using .NET 5

# General

Not much to add. Just a brand new default SSB project. Have tried creating multiple new SSB projects and get same error.

**Comment by pranavkm** [comment]
@eghsr  / @skitscha are you able to provide a msbuild binary log from building your applications in Visual Studio? You can use https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools to capture these logs. That would help us investigate this issue further.

Note that binary logs capture your machine's environment variables. You can use https://msbuildlog.com/ to view the binlog and verify it does not have anything in there that you do not want to publicly share. Alternatively, let me know and I can share an email account for you to send these logs to.

**Comment by eghsr** [comment]
![Capture](https://user-images.githubusercontent.com/74676578/99988821-d0ec6700-2d66-11eb-8611-c94402785061.JPG)

Screenshot of build log attached including command prompt showing the dotnet.exe in the expected location.
If you need the full log, I can send it via email as you have offered.

Thanks

**Comment by pranavkm** [comment]
@eghsr could you email it to `prkrishn at microsoft.com`? When you send the logs, could you ensure the build verbosity is turned up to Diagnostic: 

![image](https://user-images.githubusercontent.com/174281/100126508-e202aa00-2e32-11eb-9bfe-53cfdd71e8a8.png)

**Comment by pranavkm** [comment]
Thanks @eghsr for sharing your binlog. Our SDK relies on using the OS variable to construct paths, which assumes the OS environment variable has a moniker `Windows_NT`. From your build logs, it looks like something changes variable to have to `Windows_9x` which is a bit unusual (9x was last used in Windows ME).

![image](https://user-images.githubusercontent.com/174281/100265636-6887bc00-2f05-11eb-9e81-8536def6b68e.png)

If you're able to remedy this to say `Windows_NT` that would resolve this issue and prevent similar issues in other parts of the SDK that rely it on being the token `Windows_NT`. Alternatively, you could configure `DOTNET_HOST_PATH` as an environment variable globally to work around this specific instance of the problem: `DOTNET_HOST_PATH = C:\Program Files\dotnet\dotnet.exe`.

**Comment by pranavkm** [comment]
A fix for this would be to update the SDK to use `$([MSBuild]::IsOSPlatform('windows'))` in here: https://github.com/dotnet/aspnetcore/blob/219ecd6880120215137f4d6ef0dd2aa62c780af2/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L42.

**Comment by eghsr** [comment]
Thank you. Changing the environment variable setting resolved the build error. Not sure where the setting came from, but the change works.
