### ISSUE TITLE
Bug With Incorrect Rendering In Blazor Web Assembly 5.0 When Using The @Key Directive

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#27994]
With Blazor Web Assembly 5.0, I have found that if a parent component uses the @Key directive, then even if the child component ShouldRender returns false, its rerendering it anyways.

However, I found that I still had to use the @Key in the parent component otherwise, there can be a case where it does not refresh properly.

There needs to be a way where if ShouldRender is false but there was a key directive, it still won't render because of the overrided method.  Let me know if I need to produce a sample to post on github to explain further.

**Comment by mrpmorris** [comment]
Repro code is always a good idea :)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by musictopia2** [comment]
I now have a repository here
https://github.com/musictopia2/KeyRenderPossibleBug 

I created the most simple sample possible.  You can see i created 2 components.  For one of them, I used a key as guid.
On the second, I overrided the ShouldRender to set to false.  When I click the button, its still render again which is false.  I do need to use a key though that is different because there has been many cases where if no key was used, either gets corrupted or even gets a runtime error saying it can't remove something by key and the only sure way to fix is to use a key as guid.  However, even with a key, if shouldrender is false, then it should not render again and should not even dispose of the component.

**Comment by javiercn** [comment]
@musictopia2 thanks for the additional details.

Seems like you are creating a new key every time [here](https://github.com/musictopia2/KeyRenderPossibleBug/blob/master/Shared/UseComponent.razor#L11) wich will force the creation of a new component every time. ShouldRender is only involved after the first render (a component will always render the first time) and the use you are making of `@key` is forcing a new component to be created every time.

See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#use-key-to-control-the-preservation-of-elements-and-components) for details on how `@key` works.

**Comment by musictopia2** [comment]
What do I do if I am forced to use a key because I get a runtime error when I don't use a key.  In the case I am having the issue, I am using svg.  When using the @key, then it solves the issue but then creates another issue.  Is there a way to solve the issue of being able to render without a key?  The component is rendering a list as well.

**Comment by musictopia2** [comment]
I also have another question.  I read the documentation about key.  However, is it possible to have more than one with the same value?  If not, can it be considered for a feature.  Because there can be cases where if the value was set to 1, then it would assume its the same and can move on.  One use case can be lets say you have a list of integer or a list of string and obviously there can be 2 numbers or 2 strings that are the same.  it needs to still use the @key feature even though the 2 values are the same.

**Comment by javiercn** [comment]
@musictopia2 we currently don't have an official support for SVG (it's in the backlog) so it's hard for us to answer that because we don't have a clear picture between the interactions of the feature and SVG specifically.

That said, it feels a bit like you are using `@key` to circumvent an error when using SVG alongside Blazor. I would not consider that to be a legitimate use case for the feature. Keys should be used to optimize rendering performance and should be unique and stable amongst the elements in the collection.
