### ISSUE TITLE
Upgrade to 8.8 now causes RazorTagHelper Error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27993]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Upgrade-to-88-now-causes-RazorTagHelper/1252433?preview=true)._

---
<p>After upgrading Visual Studio for Mac 8.8, one of my projects now has the following build error:</p><pre>/Users/myName/.nuget/packages/microsoft.aspnetcore.razor.design/2.2.0/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(5,5): Error MSB4018: The &quot;RazorTagHelper&quot; task failed unexpectedly.
System.InvalidOperationException: DOTNET_HOST_PATH is not set
  at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.get_DotNetPath () [0x00031] in &lt;62f26ce25b06449d800766f15a24cf6f&gt;:0 
  at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.GenerateFullPathToTool () [0x00000] in &lt;62f26ce25b06449d800766f15a24cf6f&gt;:0 
  at Microsoft.Build.Utilities.ToolTask.ComputePathToTool () [0x0004d] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Utilities/ToolTask.cs:464 
  at Microsoft.Build.Utilities.ToolTask.Execute () [0x002e2] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Utilities/ToolTask.cs:1441 
  at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.Execute () [0x0004d] in &lt;62f26ce25b06449d800766f15a24cf6f&gt;:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:577 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:809  (MSB4018) (Identity.API)</pre><p>It's likely related to this issue: </p><p>https://developercommunity.visualstudio.com/content/problem/1249786/razortaghelper-task-failed-unexpectedly.html But the workarounds found in windows do not apply to Mac, or at least they are not clear.</p>

---
#### Feedback Bot on 11/11/2020, 07:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Enbi Zhang [MSFT] on 11/11/2020, 11:25 PM: 

<p>Thanks for your feedback.<br>
.Net core 2.2 is already out of support and we recommend you to upgrade to supported version of the framework, such as 3.1 or 5.0. See if your issue resolved.</p>

#### Paul Carver on 11/13/2020, 01:13 PM: 

<p>Enbi, that feedback is not helpful as a 2.2 application that needs to upgrade to say, 3.1 LTS, needs to at least still compile without ANY changes (after installing the latest VS update).  The VS 16.8.1 upgrade totally breaks, cannot compile, an existing ASPNET Core 2.2 project.  There must be a workaround or fix.  You can't just release a breaking change to the IDE and then say 2.2 is out of scope.</p>

#### Jamie Houseman on 11/14/2020, 06:45 AM: 

<p>I too have this issue and would like to know how to solve it. And the fix should not involve upgrading my project. You can't release updates that break people's perfectly already working code.</p>

#### Jamie Houseman on 11/14/2020, 07:57 AM: 

<p>Just out of interest I updated my project to .NET 5 (By this I obviously mean .Net Core 5, thanks for the continued confusion on the naming front Microsoft) and updated every nuget package to the latest version and the issue still remains. The DOTNET_HOST_PATH is not set apparently although my terminal can find dotnet. Is this an error in VS 8.8 for Mac?</p>

#### Feedback Bot on 11/15/2020, 11:29 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Artak Mkrtchyan on 11/19/2020, 10:59 AM: 

<p>Thanks for trying that out, @<a target='_blank' href="https://developercommunity2.visualstudio.com/users/129950/JamieHouseman.html">Jamie Houseman</a>.<br>
We’ll move this issue to GitHub to investigate it further.</p>
<pre><code class="language-VSF_WORKAROUND_IGNORE">    (please ignore this link)
    <span class="hljs-tag">&lt;<span class="hljs-name">a</span> <span class="hljs-attr">nodeid</span>=<span class="hljs-string">"129950"</span> <span class="hljs-attr">rel</span>=<span class="hljs-string">"user"</span> <span class="hljs-attr">href</span>=<span class="hljs-string">"#"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">a</span>&gt;</span>
</code></pre>

---
#### Feedback Bot solved on 11/16/2020, 09:54 AM, 0 votes: 

<p>Thanks for creating this issue! We figured it’s covering the same as <a target='_blank' href="https://developercommunity2.visualstudio.com/t/Build-is-failing-for-MicrosoftNETSdkR/1251808?preview=true">another one</a> we already have. Thus, we closed this one as a duplicate. We’ve transferred all votes from this ticket to the other one. For more information, see also our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

#### Jamie Houseman on 11/16/2020, 10:27 AM: 

<p>The other issue relates to the problem with Visual Studio on a Windows machine and the solutions are Windows centric which is what the original poster pointed out and why he opened this issue. Do you even read these things properly? We need a solution for Mac Visual studio on a Mac, NOT Windows.</p>

#### Artak Mkrtchyan on 11/19/2020, 10:59 AM: 

<p>Thanks for trying that out, @<a target='_blank' href="https://developercommunity2.visualstudio.com/users/129950/JamieHouseman.html">Jamie Houseman</a>.<br>
We’ll move this issue to GitHub to investigate it further.</p>
<pre><code class="language-VSF_WORKAROUND_IGNORE">    (please ignore this link)
    <span class="hljs-tag">&lt;<span class="hljs-name">a</span> <span class="hljs-attr">nodeid</span>=<span class="hljs-string">"129950"</span> <span class="hljs-attr">rel</span>=<span class="hljs-string">"user"</span> <span class="hljs-attr">href</span>=<span class="hljs-string">"#"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">a</span>&gt;</span>
</code></pre>

**Comment by mkArtakMSFT** [comment]
Moved this over to GitHub, as the customer is facing the same issue with .NET 5 on VS Mac.

**Comment by mkArtakMSFT** [comment]
@pranavkm given that few other customers reported this too, can we investigate this early? Not resolve immediately, but understand what's happening. We will make the call regarding when to fix (if one required) after that.

**Comment by pranavkm** [comment]
Copying my response from https://github.com/dotnet/aspnetcore/issues/27249#issuecomment-718286186:

it looks like there are changes to the 5.0 SDK that make it incompatible with .NET Core 2.2 apps. While we attempt to avoid such incompatibilities, ASP.NET Core 2.2 has been [out of support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) for some time now so it's difficult for us to capture these kinds of regressions. 

* We would strongly encourage targeting a supported version of ASP.NET Core to ensure continued support.
* As a short term fix, you can acquire a 3.1 SDK (from https://dotnet.microsoft.com/download/dotnet-core/3.1) and add a `global.json` file to your project to pin the SDK.

```js
{
  "sdk": {
    "version": "3.1.403"
  }
}
```
