### ISSUE TITLE
.Net Core SignOut() RedirectUri not working

### ISSUE THREAD

**Issue by TestO2015** [dotnet/aspnetcore#28009]
I'm trying to do a SignOut with a ```redirect uri``` specified in the ```AuthenticationProperties```. It redirects to the OIDC SignedOutCallbackPath I configured but doesn't make it to the RedirectURI.

        [HttpGet("Logout")]
        public async Task Logout()
        {
            var prop = new AuthenticationProperties()
            {
                RedirectUri = "http://google.com"
            };

            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme, prop);
        }

Setup and info:
- The app has Cookie and OpenId Connect authentication setup
- Connects to Oracle IDCS. 
- Both HttpContext.SignOutAsync() and SignOut() have the same result.
- ```A login via ChallengeRequest with a RedirectUri on the other hand works.```

How does the Redirect URI actually work inside - ex. does it get sent to the Identity Provider and back? Any clues as to why this doesn't work?

**Comment by Tratcher** [comment]
Here's the part where the signout starts. It forwards the RedirectUri via a state property just like Challenge does.
https://github.com/dotnet/aspnetcore/blob/930fd52c2d8f02c6311e86fe15ae52343e961490/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L216-L217

And here's where it comes back:
https://github.com/dotnet/aspnetcore/blob/930fd52c2d8f02c6311e86fe15ae52343e961490/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L295-L300

If you trace the request do you see the state field coming back? If you hook into the SignedOutCallbackRedirect event do you see the RedirectUri you set in the Properties?

**Comment by AndrewTriesToCode** [comment]
@Tratcher beat me to it but I'll add that it seems not all open ID connect providers actually call the sign out callback, or if they do its just a static preconfigured URL they'll hit--without the state information passed in. If you don't see the callback getting called that could be why.

OpenID Connect and OAuth sign out isn't as well-defined out as sign in.

**Comment by TestO2015** [comment]
@Tratcher The OnRedirectToIdentityProviderForSignOut event does show the .redirectUri property. OnRemoteSignOut does not and ```OnSignedOutCallbackRedirect``` isn't called at all.

I can see the state field present when it reaches the signed out callback path:
 
https://myhost/myapp/signout-oidc?state=CfDJ8FDX1DIGbFhFpGXGafv92zCXFWXuErnnkL5NwfZ2AINAiKEOY4OmXcRtNLzG07hjHXDgQrMq5k-1gaXeG_vWx2_ljys1Qqn9ahV3qOLMH6V_LeETjROjNsCbYUmbDB52JysBVeLwsqawQALjK25-9jVM_sedBCirBATW0ltc1TO6

@AndrewTriesToCode Do you think the fact that OnSignedOutCallbackRedirect indicates that Oracle IDCS doesn't call the signed out callback?

**Comment by Tratcher** [comment]
> Do you think the fact that `OnSignedOutCallbackRedirect` isn't hit indicates that Oracle IDCS doesn't call the signed out callback?

Makes sense. It's interesting it called OnRemoteSignOut instead. That's normally reserved for notifications that a central sign-out was requested by another application.

It might also be a registration issue. You've registered the login callback path ("/signin-oidc") with Oracle, right? What about the signed out callback path "/signout-callback-oidc"?

https://github.com/dotnet/aspnetcore/blob/930fd52c2d8f02c6311e86fe15ae52343e961490/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L40-L41

**Comment by TestO2015** [comment]
> It might also be a registration issue. You've registered the login callback path ("/signin-oidc") with Oracle, right? What about the signed out callback path "/signout-callback-oidc"?

Yes I do have /signin-oidc configured in Oracle under the ```Post Logout Redirect Uri```.

I can see that the post_logout_redirect_uri is not set correctly in the logout API call. It always uses the SignedOutCallbackPath regardless of what I've configured in the RedirectUri. I switched to Azure AD and it works fine - it uses the RedirectUri.

> https://idcs-9ce....identity.oraclecloud.com/oauth2/v1/userlogout?post_logout_redirect_uri=https%3A%2F%2Fmyapp%2Fsignout-callback-oidc&id_token_hint=...

**Comment by Tratcher** [comment]
> I can see that the post_logout_redirect_uri is not set correctly in the logout API call. It always uses the OIDC `SignedOutCallbackPath` regardless of what I've configured in the RedirectUri.

That's expected. It's supposed to return to "/signout-callback-oidc" and then be redirected locally to your RedirectUri. Make sure "/signout-callback-oidc" is registered as a valid Post Logout Redirect Uri.

**Comment by TestO2015** [comment]
@Tratcher I was setting the OIDC SignedOutCallbackPath to "/signout-oidc" and apparently that causes the the RedirectUri to not be used. I'm not sure why.

After registering the default "/signout-callback-oidc" value in IDCS instead, it works - I'm good with this.

Thanks for your help.

**Comment by Tratcher** [comment]
`signout-oidc` is the value for RemoteSignOutPath which is intended to handle a different flow. Setting them to the same value seems to have caused a conflict.
https://github.com/dotnet/aspnetcore/blob/84b77de14c161803b36978bf498b8a6db8b95471/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L40-L41
