### ISSUE TITLE
Asp.net core app deploy to self-contained single file can  run on IIS .NET CLR v4.0 and integrated managed without installing net core runtime server

### ISSUE THREAD

**Issue by shps951023** [dotnet/aspnetcore#28008]
### Is your feature request related to a problem? Please describe.
I am trying to run `x64 self-contained single file asp.net core 3.1 app` on IIS server which without installing asp.net core runtime, but system'll show `HTTP Error 500.19`.
![](https://i.imgur.com/YYkQHXI.png)

### Describe the solution you'd like
If system can deploy to `a single exe file and self-contained .net core runtime environment`, then just give this file to other IIS server without .net core runtime environment can `easily` run on IIS not just kestrel console.

**Comment by davidfowl** [comment]
At a minimum you need to install the IIS module for ASP.NET Core. On top of that, you can use self contained deployments but not single file + self contained, that isn't supported as yet.

**Comment by shps951023** [comment]
@davidfowl  thanks, waiting for asp.net core's good news 👍👍
