### ISSUE TITLE
ASP.NET Core 5.0 Template with ASP.NET Identity has some inconsistency issues during login 

### ISSUE THREAD

**Issue by JoeMarkov** [dotnet/aspnetcore#28018]
### Describe the bug

When I create a new ASP.NET core MVC project with ASP.NET Identity, I get some inconsistencies when logging in users.

If I have a user in my database with username **alice** and email **alice@email.com**, then I am not able to login as that user.

The problem is that **ASP.NET Identity**, when I present my email address during login, actually looks for the user with that username.

So my proposal to fix this is:

1. In the template, allow the user to login with username or email (like most service do in real life, not just email)

2. Fix the bug, so that when I login with my email, do actually lookup the user with that specific email, and do not look for the email in the UserName column. 

  If I am supposed to login with my username and not email, then fix the razor page template and validation so that I actually can enter a username. Right now I must provide an email. 

### To Reproduce

1. Create  new .NET 5 ASP.NET Core web application with the MVC template
    With Individual user accounts (store in app)
2. Update the connection string to your database and set all logging to Debug in appsettings.Development.json
3. Add the following OnMOdelCreating to the ApplicationDbContext

```
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            //seed data

            var password = "My long 123$ password";

            var alice = new IdentityUser
            {
                Id = "1",
                UserName = "alice",
                NormalizedUserName = "ALICE",
                Email = "alice@email.com",
                NormalizedEmail = "alice@email.com".ToUpper(),
                EmailConfirmed = true,
                LockoutEnabled = false
            };
            alice.PasswordHash = new PasswordHasher<IdentityUser>().HashPassword(alice, password);
        }
```

4. Add and apply the migration

```
Add-Migration FirstMigration
Update-Database

```

5. Then in the database I get one user created in the AspNetUsers table

ID: 1
UserName: alice
NormalizedUserName: ALICE
Email: alice@email.com
NormalizedEmail: ALICE@EMAIL.COM

Great!!

6. I start the application (with kestrel, not IIS Express) and try to login and now here comes the strange things.
on https://localhost:5001/Identity/Account/Login

I get presented with the "Log in- Use a local account to log in".

Great, so I try to login with username alice, but I must enter an email for the user, (why can't I login with username or email?)
"The Email field is not a valid e-mail address."

7. So I try to login with alice@email.com and the password 

But I get an error "Invalid login attempt."

strange!

My email in the database is alice@email.com, but the user is not found!

Weird!

I look the the log, it says that it runs this SQL query

```
[      Executed DbCommand (136ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
      FROM [AspNetUsers] AS [a]
      WHERE [a].[NormalizedUserName] = @__normalizedUserName_0
](url)

```

So, this is weird! why when I login with my email, it searches for the username in the database! That does not make any sense!

If I change the username in the database to alice@email.com, then I can login!

### Further technical details
- ASP.NET Core version 5.0
- Include the output of `dotnet --info`
- Visual Studio 2019 16.9.0 Preview 1.0

C:\Users\xxxxx>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\xxxxx>

**Comment by blowdart** [comment]
The starting templates treat email address and user name as the same because it's simple. 

Once you start moving away from that assumption you do, as you've discovered, you need to adjust things to match your new, desired configuration.

@HaoK didn't we have a config option, or was this just under consideration? I can't find one.

**Comment by JoeMarkov** [comment]
sure, I understand, but the confusion is that it does not look at the email column and all these hidden assumptions makes it hard to reason about the code. 

It would be more intuitive if I could login with username or email and that it searched in both the username and email column.

**Comment by JoeMarkov** [comment]
Or if the user interface on the login asked for the users username instead of email.

**Comment by blowdart** [comment]
Oh we're aware, but it becomes a large breaking change to adjust the UI, because it's been like that for 10+ years unfortunately.

**Comment by JoeMarkov** [comment]
I understand, as a first time user it was so confusing as a first time user. Perhaps in the templates /Home/Index page, it could contain a link to a doc page that explains the core assumptions that the template takes or a Readme.txt file :-).
