### ISSUE TITLE
Custom validation errors are not used on FromQuery bound models

### ISSUE THREAD

**Issue by nieve** [dotnet/aspnetcore#28014]
### Describe the bug
Custom validation errors on models bound to query strings are not being used whereas these errors are used when the models are bound to the request body:
``` cs
public class Model
{
    [Required(ErrorMessage = "COLOR_MISSING"), EnumDataType(typeof(Colors), ErrorMessage = "INVALID_COLOR")]
    public Colors Color { get; set; }
}

[HttpPost]
public IActionResult Post([FromBody]Model body){}

// NOTE: in Startup.cs I do configure the json serializations to use the JsonStringEnumConverter, 
// though I do get the same error when not using it.
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers()
        .AddJsonOptions(opt => opt.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
}

// This test fails:
[Test]
public async Task ShouldReturnsCustomErrorOnPostColor()
{
    var scenarioResult = await System.Scenario(scenario =>
    {
        scenario.Post.Url($"/WeatherForecast/23?Color=-1");
        scenario.StatusCodeShouldBe(400);
    });

    var result = scenarioResult.ResponseBody.ReadAsJson<HttpErrorResult>();
    Assert.That(result.Errors.ContainsKey("Color"));
    Assert.AreEqual(1, result.Errors.Values.SelectMany(x => x).Count());
    Assert.AreEqual("INVALID_COLOR", result.Errors.Values.First().First());
}
```

### To Reproduce
Please see [this repository](https://github.com/nieve/GetEnumQueryString) containing an API with endpoints displaying this issue and some failing unit tests due to this issue.

### Exceptions (if any)
Rather than getting the custom error message, I get the default error message `The value '{0}' is invalid.`.

### Further technical details
- ASP.NET Core version: 3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS2019

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The JSON Deserialization happens before the validation phase and it's the deserialization which is failing for you.
What you want to do is to use a custom converter. You can read more about that at: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0
