### ISSUE TITLE
[Blazor] UseBlazorFrameworkFiles not working as intended

### ISSUE THREAD

**Issue by Coupz** [dotnet/aspnetcore#28017]
### Describe the bug
When using UseBlazorFrameworkFiles, I'm getting 404 on all DLL files.

### To Reproduce
Create a new Blazor WASM project with In-App authentication, ASP.NET hosted and PWA.
Open the Startup.cs in the Server project and change the line `app.UseBlazorFrameworkFiles();` to `app.UseBlazorFrameworkFiles("/app");`. After that, open your wwwroot/index.html in the Client project and change `<base href="/" />` to `<base href="/app" />`. After that, open your Index.razor in the client project and change `@page "/"` to `@page "/app"`. Then run the app with F5 and you'll get 404s on all DLLs that Blazor wants to load.

Example repo: https://github.com/Coupz/UseBlazorFrameworkFiles

### Further technical details
- ASP.NET Core version: .NET 5
- Include the output of `dotnet --info`
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2019 16.8.2
VSCode October 2020 (version 1.51)

### Expected outcome:
That I have to move the index.html to a subfolder of wwwroot -> `wwwroot/app/index.html` and that I can put other static HTML files/pages to the default `wwwroot` folder, which still get served by Kestrel but without loading Blazor.

**Comment by javiercn** [comment]
@Coupz thanks for contacting us.

You also need to change `StaticWebAssetBasePath` on the client project to `"/app"` but we currently have a bug in 5.0 that is preventing this from working, it will be fixed in a following patch release.

**Comment by Coupz** [comment]
Thank you @javiercn, so you mean to add the following to the csproj file:
```
    <StaticWebAssetBasePath>app</StaticWebAssetBasePath>
```

And then the files in the wwwroot folder (index.html, about.html, pricing.html) would be statically served by the Kestrel server and everything under "/app" would be picked up by blazor, because there I would have another index.html which loads blazor.webassembly.js. Did I understand that correctly?

**Comment by javiercn** [comment]
@Coupz for the wwwroot folder on the Blazor webassembly project, that's it.

That said, we have an ongoing bug where the framework files don't correctly respect the SWA base path, so this won't work until we fix it in the following weeks.

**Comment by Coupz** [comment]
Alright, thank you very much!

**Comment by Coupz** [comment]
Hi @javiercn, today was the release of .NET 5.0.1 where this issue was mentioned with the `StaticWebAssetBasePath` but I still can't get it to work. I've updated the demo repo (url in my first post).
Do I miss something here? I also tried to move everything under wwwroot to the folder wwwroot\app which didn't worked either.

**Comment by javiercn** [comment]
@Coupz did you clean the bin,obj folders after updating the SDK?

**Comment by Coupz** [comment]
Hi Javier,

my publish folder `wwwroot` looks like this:
![image](https://user-images.githubusercontent.com/1399474/101628771-99e1ab00-3a20-11eb-8db5-2f1b4e3faac9.png)

It doesn't change with `dotnet publish -c Release` either and on `https://localhost:5001` and `https://localhost:5001/app` I'm receiving 404 without any exceptions in the console.
I also deleted the repo locally and cloned from my demo repo again and build it again.

**Comment by javiercn** [comment]
@Coupz clean the bin and obj folders and change the base path like this `    <StaticWebAssetBasePath>/app/</StaticWebAssetBasePath>`

**Comment by Coupz** [comment]
Maybe I should clarify what I'm expecting (maybe this can't be done yet?).

I want to have a Blazor WASM app with Identity.

https://example.com <- index.html without Blazor
https://example.com/about <- about.html without Blazor
https://example.com/pricing <- pricing.html without Blazor
https://example.com/app <- index.html with Blazor
https://example.com/app/* <- Blazor takes care of routing

Folder structure:
wwwroot/index.html <- without Blazor
wwwroot/pricing.html <- without Blazor
wwwroot/app/index.html <- Blazor

Is this expected behaviour correct

**Comment by javiercn** [comment]
@Coupz thanks for the additional details.

There seems to be an integration issue here that we didn't catch. I'm looking into it and see if we can get this fixed in the next patch release.

**Comment by Coupz** [comment]
Alright @javiercn, thank you!

Do you think that my expected behaviour (see last comment) is doable? Because, most web apps these days need some static pages until you log in or sign up and I don't see the advantage to have these static pages to need to load Blazor. And it would also improve loading times and SEO capabilities when you could have your "no authentication" pages in static HTML files and your "real" app with Authentication and everything else is handled by Blazor.

Thanks in advance.

**Comment by javiercn** [comment]
@Coupz I'm not 100% sure I got your scenario, but WRT to hosting blazor in a folder other than "/" it makes sense.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/pull/28539

**Comment by Coupz** [comment]
Thank you @javiercn 
I just want my ASP.NET Core hosted Blazor app to be under a folder (`/app`) so that I can have static HTML pages in the `wwwroot` folder. Will try that after the next release 👍
