### ISSUE TITLE
The use of namespaces that partially share names with those in Blazor project will fail build of project

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspnetcore#28012]
I have only tested this with the server-side hosting model - I do not know if it similarly impacts the WASM hosting model.

### Describe the bug
One is intended to provide global imports in their _Imports.razor file so as not to have to clutter all the .razor files with all the usings for components and whatnot. Well, one of the perks of Blazor is that existing libraries can simply be installed via NuGet or referenced and they Just Work across the Blazor project.. unless their namespaces match any part of an existing folder in the Blazor project itself.

### To Reproduce
- I've created a new Blazor server-side app from the VS template. 
- I added a new .NET Standard 2.0 class library to the solution called "Shared.Domain".
- I created a reference from the ErrorSample1 project to the Shared.Domain library.
- I added a line to the bottom of _Imports.razor for `@using Shared.Domain`.
- I'll get a red squiggly about it indicating that Domain doesn't exist in the ErrorSample1 namespace and it will fail to build the solution with all manner of odd errors (see Logs & Exceptions below)

Please feel free to clone the project [here](https://github.com/WhitWaldo/bookish-octo-bassoon) where I have already done each of these steps. Just build to reproduce.

### Logs & Exceptions
No exceptions, but here's a screenshot of the error list when I attempt to build this solution.

![image](https://user-images.githubusercontent.com/2238529/99773380-fad92b80-2ad1-11eb-8a5e-51eecfee2658.png)

#### Language Server logs
[LSP.zip](https://github.com/dotnet/aspnetcore/files/5572039/LSP.zip)

### Further technical details
- VS Pro 2019, 16.8.2
- Scenario: Local

### Pre-requisite checklist
- [X] Steps to reproduce the issue
- [X] Razor Language Server client logs included.
- [X] HTML Language Server client logs included

**Comment by MichelJansson** [comment]
I have the same issue, but with only references (not related to folder of blazor). I also tried using the failing namespace in a regular .cs file, which works without issues.


#### MyNs.Web.BlazorClient\\_imports.razor :
``` razor
@using Grpc.Core       @*Nuget for Grpc*@
@using MyNs.Grpc       @*Namespace existing in blazor shared project*@
```
#### Error
```
CS0234	The type or namespace name 'Core' does not exist in the namespace 'MyNs.Grpc' (are you missing an assembly reference?)
```

#### Further technical details
 - VS Pro 2019, 16.8.2

**Comment by DaleCam** [comment]
I have a similar issue. 
My Project and namespace names in the Solution are "Portfolio.Web" and "Portfolio.Models".
If the page or component puts the @using Portfolio.Models in it, i get the following error:

The type name 'Models' does not exist in the type 'Portfolio

To work around this, i have to remove the @using in the component, and instead preface all my Types with the full path ie:

[Parameter] public Portfolio.Models.Trade Trade {get;set;}

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is caused by the Razor compiler not generating globally qualified identifiers. We track fixing that as part of https://github.com/dotnet/aspnetcore/issues/18757.
