### ISSUE TITLE
HttpContext.Connection.RemoteIpAddress gives a different response after a while.

### ISSUE THREAD

**Issue by Runaho** [dotnet/aspnetcore#28020]
Hello, I need to check the user's ip address over and over again.
When I start to ask for an IP address, sometimes it gives a different IP address and continues to give it the old IP address again.

My first question is What does the Remote Ip Address method actually give? I could not find this value.
My second question is why this RemoteIpAddress method gives different responses to some requests and it continues to give the old address again.
Last one Is there a more accurate and proper way to get the user's ip address?

[The starter template project I made and published for testing.](https://corewhatsmip.guneskorkmaz.net/)

Screen Shoots
![image](https://user-images.githubusercontent.com/16222645/99808424-e472b480-2b51-11eb-92d7-c73ab8b19bdf.png)
![image](https://user-images.githubusercontent.com/16222645/99808409-db81e300-2b51-11eb-9bcb-892b9b075f36.png)
![image](https://user-images.githubusercontent.com/16222645/99814537-27d12100-2b5a-11eb-942d-5f76ab12f892.png)

---------------------
Wındows 10
.Net Core 3.1.5 Razor Pages

**Comment by Runaho** [comment]
I found the cause of the problem. Since I use **Cloudflare**, I cannot directly access the ip address.

**Comment by Tratcher** [comment]
Cloudflare sets the x-fowarded-for header to give you the client's original IP.
https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-CloudFlare-handle-HTTP-Request-headers-

See here for applying those headers:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0
