### ISSUE TITLE
The way to stop authentication process in OnCreatingTicket event

### ISSUE THREAD

**Issue by mkorsukov** [dotnet/aspnetcore#28023]
### The case
Dear .NET community,

I'm looking for a proper way to stop authentication flow in the OnCreatingTicket event and call the redirect to specific page. Here is my Google Auth setup:

```c#
services
    .AddAuthentication(options =>
    {
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = GoogleDefaults.AuthenticationScheme;
    })
    .AddCookie()
    .AddGoogle(options =>
    {
        options.ClientId = "ClientId";
        options.ClientSecret = "ClientSecret";
        options.CorrelationCookie.SameSite = SameSiteMode.Unspecified;
        options.AccessDeniedPath = new PathString("/account/access-denied");

        options.Events.OnCreatingTicket = async (context) =>
        {
            var subjectId = context.Principal.FindFirst(ClaimTypes.NameIdentifier).Value;
            var localClaims = await context.HttpContext.RequestServices
                .GetRequiredService<ListUserClaimsCommand>()
                .ListAsync(GoogleDefaults.AuthenticationScheme, subjectId);

            if (!localClaims.Any()) // user not found or locked
            {
                // Need a proper logic here to let the auth middleware to reuse the 'options.AccessDeniedPath'


                // Current workaround - Begin

                    context.Principal = new ClaimsPrincipal();
                    context.NoResult();

                    await context.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                    throw new AuthenticationException("You must sign in with registred email address.");

                // Current workaround - End
            }

            var googleIdentity = context.Principal.Identity as ClaimsIdentity;
            var googleClaims = googleIdentity.Claims.ToList();

            foreach (var claim in googleClaims)
            {
                googleIdentity.RemoveClaim(claim);
            }

            googleIdentity.AddClaims(localClaims);
        };
```

Currently, I came up with a temporary workaround using exception, which I catch later and do the redirect. But I think, there should be a simplier way of doing such things. I would appreciate any feedback.

### Further technical details
- ASP.NET Core 3.1.8
- VS 2019 16.8.0, VS Code 1.51.1

**Comment by mkorsukov** [comment]
I went through many topics here, and found that probably @Tratcher or @blowdart can help with my case?

**Comment by Tratcher** [comment]
That's an authorization check rather than an authentication check, OnCreatingTicket might not be the right place for it. This seems like it should be checked in authorization policies.

When a user's google account isn't registered in your system, how do they become registered? Is there another page on the site where they can do that, or is it an out-of-band process?

**Comment by mkorsukov** [comment]
@Tratcher Thanks for response! I see your point.

I agree, this logic looks like authorization one. When we deal with custom authentication and authorization implementation (for instance, for Web API) based on ASP.NET Core contracts, there is a nice `context.NoResult()` or `context.Fail()` calls which "stop" authentication handler and let authorization one process that result. May be I should try it here as well.

I'm trying to mix such "stop & redrect" in OnCreatingTicket, but with no success.

Users are registered the manual way.

**Comment by mkorsukov** [comment]
I will try a new idea, and will post my result here.

**Comment by mkorsukov** [comment]
@Tratcher Thanks for ideas :+1: . You are right, authorization should not be done in authentication logic. Here is my working update.

1. Cookies configuration:

```c#
.AddCookie(options =>
{
    options.AccessDeniedPath = new PathString("/account/access-denied");
})
```

2. Authentication logic:

```c#
googleIdentity.AddClaims(localClaims);
googleIdentity.AddClaim(new Claim("authorized", "yes"));
```

3. Authorization check:

```c#
services.AddAuthorization(config =>
{
    config.AddPolicy("AuthenticatedUser", policy => policy
        .RequireAuthenticatedUser()
        .RequireClaim("authorized"));
});
```

Feel free to close my issue :smile:
