### ISSUE TITLE
Prerendering Blazor WASM .NET 5 app with authentication throws error

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#28025]
I have a Blazor WASM application using OIDC authentication (based on this https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio). This works fine.

Now, when I add WASM prerendering (based on this https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#support-prerendering-with-authentication), then it no longer works. I get a strange behavior after the app loads and 404 errors. The redirect after the login then also hits a 404.
In fact, every route is giving a 404... hm...

![image](https://user-images.githubusercontent.com/888718/99832273-91ecc480-2b60-11eb-9a43-6fe405cb3e50.png)

Here is a small demo video:

![BlazorDemo](https://user-images.githubusercontent.com/888718/99831913-168b1300-2b60-11eb-9b1c-ba8d00b4b365.gif)

This is the demo code:
https://github.com/thinktecture/blazor-webassembly-demo/tree/prerender

.cc @guardrex 
https://github.com/dotnet/AspNetCore.Docs/issues/20696

**Comment by guardrex** [comment]
I'll update the `<app>` to `<div id="app">` on https://github.com/dotnet/AspNetCore.Docs/pull/20698 along with anything else that we need to do for this scenario in 5.0.

**Comment by SteveSandersonMS** [comment]
We're keen to do something useful for this in 7.0 but it's too late to address in 6.0 now we're in the RC phase unfortunately.

**Comment by mkArtakMSFT** [comment]
Closing this in favor of https://github.com/dotnet/aspnetcore/issues/27592 as a dupe
