### ISSUE TITLE
empty_input_scopes_error error when using MSAL Auth - Again...

### ISSUE THREAD

**Issue by GreatIdeaz** [dotnet/aspnetcore#28022]
So I am using the current .NET 5 release and creating an AAD B2B WASM Client using the standard "Blazor App" template provided by visual studio without the ASP.NET Core Hosted flag set. The template created my AAD App Registration, I changed the WEB URL to a SPA URL as directed.

The sign in process correctly connected to my AAD B2B App Registration and validated my user but failed with a "empty_input_scopes_error" when I tried to sign in.

My appsettings.json looks like this:
{
  "AzureAd": {
    "Authority": "https://login.microsoftonline.com/5298147c-XXXX-45c1-8763-11ba8037655b",
    "ClientId": "6e584215-XXXX-4a14-bbfb-c6ff17e99b0e",
    "ValidateAuthority": true
  }
}

My program.cs contains the following:

            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
            });

I noted a previous error on this topic and wondered whether something is missing from the "Blazor App: template when creating just a WASM Client without a Server?

**Comment by javiercn** [comment]
@GreatIdeaz thanks for contacting us.

You need to add a scope to the list of default scopes, like "openid". This is covered in the migration docs

**Comment by GreatIdeaz** [comment]
So if I look at a version with a .Server project I see something like this:

            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
                options.ProviderOptions.DefaultAccessTokenScopes.Add("api://blazorapp1_server/user_impersonation");
            });

So what would be an appropriate scope if I don't have .server?

**Comment by javiercn** [comment]
@GreatIdeaz just "openid"

**Comment by GreatIdeaz** [comment]
Thank you so much for your help with this :)

As you will appreciate I'm not an expert on this aspect of ADAL and just starting with .NET 5 after many years of .NET Framework... So much new stuff to play with and learn!
