### ISSUE TITLE
ASP.NET Core 2.2 (framework) project fails to build

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28037]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ASPNET-Core-22-framework-project-fai/1224054)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:16.8.0 Preview 3.0]

```
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018: The "RazorTagHelper" task failed unexpectedly.
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018: System.InvalidOperationException: DOTNET_HOST_PATH is not set
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.get_DotNetPath()
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.GenerateFullPathToTool()
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.ComputePathToTool()
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.Execute()
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
12>C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

---
#### Brad Agee on 10/17/2020, 08:36 AM: 

<p>Sam issue on my install... </p><p>Microsoft Visual Studio Community 2019 Preview<br>Version 16.8.0 Preview 4.0<br>VisualStudio.16.Preview/16.8.0-pre.4.0+30608.117<br>Microsoft .NET Framework<br>Version 4.8.04084<br><br>Installed Version: Community<br><br>ADL Tools Service Provider   1.0<br>This package contains services used by Data Lake tools<br><br>ASA Service Provider   1.0<br><br>ASP.NET and Web Tools 2019   16.8.544.20707<br>ASP.NET and Web Tools 2019<br><br>ASP.NET Core Razor Language Services   16.1.0.2047412+61e28256c4cc2f7440cda06218667b711c678afd<br>Provides languages services for ASP.NET Core Razor.<br><br>ASP.NET Web Frameworks and Tools 2019   16.8.544.20707<br>For additional information, visit https://www.asp.net/<br><br>Azure App Service Tools v3.0.0   16.8.544.20707<br>Azure App Service Tools v3.0.0<br><br>Azure Data Lake Node   1.0<br>This package contains the Data Lake integration nodes for Server Explorer.<br><br>Azure Data Lake Tools for Visual Studio   2.6.1000.0<br>Microsoft Azure Data Lake Tools for Visual Studio<br><br>Azure Functions and Web Jobs Tools   16.8.544.20707<br>Azure Functions and Web Jobs Tools<br><br>Azure Stream Analytics Tools for Visual Studio   2.6.1000.0<br>Microsoft Azure Stream Analytics Tools for Visual Studio<br><br>C# Tools   3.8.0-4.20503.2+75d31ee941ce4dbbe5752f4ac2d5c0583f388a27<br>C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.<br><br>Common Azure Tools   1.10<br>Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.<br><br>Cookiecutter   16.8.20241.2<br>Provides tools for finding, instantiating and customizing templates in cookiecutter format.<br><br>Fabric.DiagnosticEvents   1.0<br>Fabric Diagnostic Events<br><br>IntelliCode Extension   1.0<br>IntelliCode Visual Studio Extension Detailed Info<br><br>Microsoft Azure HDInsight Azure Node   2.6.1000.0<br>HDInsight Node under Azure Node<br><br>Microsoft Azure Hive Query Language Service   2.6.1000.0<br>Language service for Hive query<br><br>Microsoft Azure Service Fabric Tools for Visual Studio   16.0<br>Microsoft Azure Service Fabric Tools for Visual Studio<br><br>Microsoft Azure Stream Analytics Language Service   2.6.1000.0<br>Language service for Azure Stream Analytics<br><br>Microsoft Azure Stream Analytics Node   1.0<br>Azure Stream Analytics Node under Azure Node<br><br>Microsoft Azure Tools   2.9<br>Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1<br><br>Microsoft Continuous Delivery Tools for Visual Studio   0.4<br>Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.<br><br>Microsoft JVM Debugger   1.0<br>Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines<br><br>Microsoft Library Manager   2.1.113+g422d40002e.RR<br>Install client-side libraries easily to any web project<br><br>Microsoft MI-Based Debugger   1.0<br>Provides support for connecting Visual Studio to MI compatible debuggers<br><br>Microsoft Visual Studio Tools for Containers   1.1<br>Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.<br><br>NuGet Package Manager   5.8.0<br>NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/<br><br>Office Developer Tools for Visual Studio   16.0.30502.00<br>Microsoft Office Developer Tools for Visual Studio<br><br>ProjectServicesPackage Extension   1.0<br>ProjectServicesPackage Visual Studio Extension Detailed Info<br><br>Python   16.8.20241.2<br>Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.<br><br>Python - Conda support   16.8.20241.2<br>Conda support for Python projects.<br><br>Python - Django support   16.8.20241.2<br>Provides templates and integration for the Django web framework.<br><br>Python - IronPython support   16.8.20241.2<br>Provides templates and integration for IronPython-based projects.<br><br>Python - Profiling support   16.8.20241.2<br>Profiling support for Python projects.<br><br>SQL Server Data Tools   16.0.62010.06180<br>Microsoft SQL Server Data Tools<br><br>ToolWindowHostedEditor   1.0<br>Hosting json editor into a tool window<br><br>TypeScript Tools   16.0.21001.2001<br>TypeScript Tools for Microsoft Visual Studio<br><br>Visual Basic Tools   3.8.0-4.20503.2+75d31ee941ce4dbbe5752f4ac2d5c0583f388a27<br>Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.<br><br>Visual F# Tools   16.8.0-beta.20471.5+03283e07f6bd5717797acb288cf6044cedca2202<br>Microsoft Visual F# Tools<br><br>Visual Studio Code Debug Adapter Host Package   1.0<br>Interop layer for hosting Visual Studio Code debug adapters in Visual Studio<br><br>Visual Studio Container Tools Extensions   1.0<br>View, manage, and diagnose containers within Visual Studio.<br><br>Visual Studio Tools for Containers   1.0<br>Visual Studio Tools for Containers<br><br>Visual Studio Tools for Kubernetes   1.0<br>Visual Studio Tools for Kubernetes<br><br>Workflow Manager Tools 1.0   1.0<br>This package contains the necessary Visual Studio integration components for Workflow Manager.</p>

#### Feedback Bot on 10/19/2020, 00:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/19/2020, 01:19 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Dennis Kiesel on 10/19/2020, 00:52 PM: 

<p>I am having the same issue with a dotnet 2.2 project. I get the error when buildling with Visual Studio 2019 Preview but not the non-preview VS.</p>

#### Murat Boduroglu on 10/19/2020, 01:12 PM: 

<p>As a workaround, I have created a new System Variable in Environment Variables</p><p><br>Variable: DOTNET_HOST_PATH<br>Value: dotnet</p><p>Afterwards, I was able to rebuild and run my .Net Core 2.2 solution.</p>

#### Brad Agee on 10/19/2020, 03:03 PM: 

<p>One possible solution is to clear the NuGet cache (see this screen shot)</p> <p><a target='_blank' href="https://www.dropbox.com/s/01niz6chke7igvf/_clear%20cache.png?dl=0">Screenshot of VS option</a></p>

#### Dennis Kiesel on 10/19/2020, 03:07 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/291513/97235729-0bcd-6c3f-b64b-a8ea1f8a4f36.html" nodeid="291513">@Brad Agee</a> I tried that as well but still have the issue.</p>

#### Feedback Bot on 10/19/2020, 06:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Artak Mkrtchyan on 10/19/2020, 09:16 PM: 

<p>Thanks for contacting us. Are you able to build the project from the command-line using the <code>dotnet</code> CLI?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Dennis Kiesel on 10/19/2020, 09:26 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/64017/52f50294-bed1-4231-b630-e4d050633c0b.html" nodeid="64017">@Artak Mkrtchyan</a> Yes. I can build from the CLI.</p>

#### Robin Sue on 10/20/2020, 10:50 AM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/64017/52f50294-bed1-4231-b630-e4d050633c0b.html" nodeid="64017">@Artak Mkrtchyan</a> yes, running `dotnet build` on the failing csproj works fine.</p>

#### Feedback Bot on 10/20/2020, 07:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/26/2020, 10:45 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### john on 10/27/2020, 11:32 AM: 

<p>Murat Buduroglu's solution above worked for me. </p>

#### Jan Kučera on 11/7/2020, 07:18 AM: 

<p>Same for me, using 16.8.0 (Preview 6.0). The repro steps are simple:</p><p>Create a new ASP.NET Core Web project, target .NET Framework and choose the MVC template. Upgrade all NuGet packages to the latest versions. Build.</p>

#### Alexander Jung on 11/11/2020, 05:32 AM: 

<p>Same here with the officially released 16.8.0.</p><p>VS build fails. CLI Build works.</p><p>Setting environment variable DOTNET_HOST_PATH =&gt; VS build works.</p>

#### Dustin on 11/11/2020, 10:33 AM: 

<p>Experienced the same issue in 16.8.0</p><p>Adding system environment variable got it to compile, but now my razer pages are not loading in elements that begin with a ~, like the one below.</p><pre>&lt;link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /&gt;</pre>

#### Kenneth Cochran on 11/13/2020, 00:13 PM: 

<p>Same problem here on mac after the last update</p>

#### aydin kadkhodaei on 11/13/2020, 01:18 PM: 

<p>I rename folder "netstandard2.0" in C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build and everything works fine !</p>

#### Artak Mkrtchyan on 11/17/2020, 02:48 PM: 

<p>This isn’t specific to VS but an issue with 2.2 and the 5.0 SDK. We have responded to another user report on GitHub - <a target='_blank' href="https://github.com/dotnet/aspnetcore/issues/27249">https://github.com/dotnet/aspnetcore/issues/27249</a></p>
<p>Looks like there are changes to the 5.0 SDK that make it incompatible with .NET Core 2.2 Mvc apps. While we attempt to avoid such incompatibilities, <a target='_blank' href="https://ASP.NET">ASP.NET</a> Core 2.2 has been <a target='_blank' href="https://dotnet.microsoft.com/platform/support/policy/dotnet-core">out of support</a> for some time now so it’s difficult for us to capture these kinds of regressions.</p>
<ul>
<li>We would strongly encourage targeting a supported version of <a target='_blank' href="https://ASP.NET">ASP.NET</a> Core to ensure continued support.</li>
<li>As a short term fix, you can acquire a 3.1 SDK (from <a target='_blank' href="https://dotnet.microsoft.com/download/dotnet-core/3.1">https://dotnet.microsoft.com/download/dotnet-core/3.1</a>) and add a <code>global.json</code> file to your project to pin the SDK.</li>
</ul>
<pre><code>{
  <span class="hljs-attr">"sdk"</span>: {
    <span class="hljs-attr">"version"</span>: <span class="hljs-string">"3.1.403"</span>
  }
}   
</code></pre>

#### Alexander Jung on 11/19/2020, 09:01 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/64017/52f50294-bed1-4231-b630-e4d050633c0b.html" nodeid="64017">@Artak Mkrtchyan</a> </p><p>"ASP.NET Core 2.2 has been out of support for some time now..."</p><p>Nobody expects you to specifically support 2.2, <strong>just don't break it</strong>.</p><p>Moving to 3.1 is not always an option (at least for the time being), as some of us have to support (or gradually phase out) .NET Framework features. </p>

---
#### Dennis Kiesel solved on 10/19/2020, 09:24 PM, 0 votes: 

<p>Responded by accident</p>

#### Kenneth Cochran solved on 11/19/2020, 09:20 AM, 0 votes: 

<p>[Workaround]<br>
The solution by <a target='_blank' href="https://aka.ms/dc/u?aid=64017">Artak Mkrtchyan</a> didn’t work for me.<br>
I was able to work around this issue by, adding the following to the project file</p>
<pre><code>  

    
  
    <span class="hljs-tag">&lt;<span class="hljs-name">EnvVarSet</span> <span class="hljs-attr">VarName</span>=<span class="hljs-string">"DOTNET_HOST_PATH"</span> <span class="hljs-attr">VarValue</span>=<span class="hljs-string">"dotnet"</span>/&gt;</span>
  
</code></pre>

#### Stefan Olson on 11/19/2020, 04:52 PM: 

<p>Doesn't work for me, get this:   Error: The attribute "VarName" in element &lt;EnvVarSet&gt; is unrecognized.</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. By pinning the SDK doesn't mean that you'll need to update your project. It rather means that the 3.1 SDK will be used to build your 2.2 project.

That said, we still strongly recommend customers to move off of 2.2 as that's out of support and does not get any patches (including security) any more.
