### ISSUE TITLE
The static web assest has a conflicting web root path with the project file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28036]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/The-static-web-assest-has-a-conflicting-/1258802?preview=true)._

---
[severity:Other] [regression] [worked-in:16.8.0]
After the update of Visual studio community to version 16.8.1, I started to get this error.

To check if the problem is in my code, I tried couple of the devices that does not have the latest version of visual studio (visual studio running in version 16.8.0 or earlier). The code runs without any problem.

Thank you to everyone for your time.

---
#### Feedback Bot on 11/17/2020, 07:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. I believe this is a change we've [announced here](https://github.com/aspnet/Announcements/issues/443).

@javiercn can you please confirm? Thanks!

**Comment by javiercn** [comment]
Yep.
