### ISSUE TITLE
Every time I edit c# code in razor files (.cshtml), visual studio becomes unresponsive and crashes.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28034]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Every-time-I-edit-c-code-in-razor-files/1218227)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:2017]
Every time I edit c# code in razor files (.cshtml), visual studio becomes unresponsive and crashes.

This only happens when i edit razor code in cshtml files. But when i edit html parts of the file, it works fine without any problems. also when i edit javascript, it works without any problems.

I have to literally comment the code and then uncomment it after entering the line for it to not break and restart visual studio.
e.g 

When I type in 
@{
        if(Model.  At this point Visual studio becomes unresponsive and then restarts.

}

Note: please also cc *@yyy when replying.

Thanks a ton in advance :)

---
#### Feedback Bot on 10/13/2020, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2020, 00:02 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by abdul-lahidris** [comment]
Same here. I just installed the latest version of Visual Studio today, and since then whenever i try to write any c# code in the .cshtml file, the app stops and then restarts and most times clears unsaved changes

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
