### ISSUE TITLE
Add config autocompletion for ASP.NET Core projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28039]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-config-autocompletion-for-ASPNET-Co/1230252?preview=true)._

---
<p>When you have a ASP.NET Core project and you use the default configuration (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1), there is no autocompletion if you access items from a appsettings.json.</p> <p>For example I have</p><pre>{
  &quot;MyConfig&quot;: {
    &quot;Hello&quot;: &quot;Hello WORLD!&quot;
  },
  &quot;Logging&quot;: {
    &quot;LogLevel&quot;: {
      &quot;Default&quot;: &quot;Information&quot;,
      &quot;Microsoft&quot;: &quot;Warning&quot;,
      &quot;Microsoft.Hosting.Lifetime&quot;: &quot;Information&quot;
    }
  },
  &quot;AllowedHosts&quot;: &quot;*&quot;
}</pre><p></p><p>and on a razor page, I injected the configuration and then I want to access MyConfig:Hello as following</p><pre>public class IndexModel : PageModel
    {
        private readonly IConfiguration _config;

public IndexModel(IConfiguration config)
        {
            _config = config;
        }

public void OnGet()
        {
            var configValue = _config[&quot;MyConfig:Hello&quot;];
        }
    }
</pre><p></p><p>It would be helpful, if IntelliSense would provide an autocompletion when I wrote _config[&quot;&quot;], to see all available config items and then, for example if I write the letter 'M', it would suggest me &quot;MyConfig&quot; and so on.</p>

---
#### Feedback Bot on 10/23/2020, 00:11 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
