### ISSUE TITLE
JSON error in dotnetcli.host.json in Microsoft.DotNet.Web.ProjectTemplates.2.2 v2.2.8 NuGet package

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/aspnetcore#28044]
I found that there is a JSON error in a `dotnetcli.host.json` file in the package https://www.nuget.org/packages/Microsoft.DotNet.Web.ProjectTemplates.2.2/2.2.8. The package was published about a year ago.

![image](https://user-images.githubusercontent.com/1283154/99867231-c45ce880-2b85-11eb-8fb4-addddf06ed68.png)

I found the error is the extra `g` character at the end of the file at https://github.com/dotnet/aspnetcore/blob/v2.2.8/src/Templating/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorClassLibrary-CSharp/.template.config/dotnetcli.host.json#L19.

I'm not sure if this has any impact on anything, but it may be worth while to see if this causes any issues with `dotnet new`. It shouldn't impact Visual Studio because we do not read that file.

cc @KathleenDollard @vijayrkn @phenning

**Comment by mkArtakMSFT** [comment]
Thanks @sayedihashimi.
We've received no reports of this causing any issues for our customers. That plus the fact that 2.2 is out of support I don't think we should do this.
