### ISSUE TITLE
ASP.NET Core セッション機能-ASP.NET Core session function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28040]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/524005/aspnet-core-セッション機能.html)._

---
セッション変数を使いパフォーマンスを向上したいですが、セッション変数にobject型を格納できないことで、シリアライズ/デシリアライズが必要になっています。
https://www.talkingdotnet.com/store-complex-objects-in-asp-net-core-session/</p><p>シリアライズ/デシリアライズの処理コストがかからないよう、セッション変数にobject型を格納できるようにしてほしい。

---
#### Jane Wu [MSFT] on 4/10/2019, 00:55 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
## Translated from Bing
I want to use session variables to improve performance, but the inability to store object types in session variables requires serialization / deserialization. https://www.talkingdotnet.com/store-complex-objects-in-asp-net-core-session/ We want to be able to store object type in session variable so that serialization / deserialization processing cost is not required.</p>

**Comment by Tratcher** [comment]
I recommend using IMemoryCache instead.

Session was intentionally designed to require serialized data so that it would work when the app was scaled to multiple machines.
