### ISSUE TITLE
HTTP Error 500.0 - ANCM In-Process Handler Load Failure

### ISSUE THREAD

**Issue by Abdalrzakalsouki** [dotnet/aspnetcore#28048]
Visual studio was reporting an errors in debugging even so there is no errors in the error list, I tried to follow some solutions like deleting the temper debugging files from it  but that is only lead to cause this additional error for me:
"HTTP Error 500.0 - ANCM In-Process Handler Load Failure"
The app was working before even with the error reporting

**Comment by rezathecoder** [comment]
try enabling developer exception page and see if any useful information comes up.
This happened to me before and the reason was that my database was not up to date with latest changes. Make sure you applied latest migration on the database

**Comment by jkotalik** [comment]
We'd recommend using https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0 to try debugging what errors are going on first.
