### ISSUE TITLE
ASP.NET Core Blazor component virtualization with CSS Grid layout

### ISSUE THREAD

**Issue by SLFD-William** [dotnet/aspnetcore#28056]
Adding the empty divs at the beginning and end to handle the virtualization throws off the layout if using a CSS Grid since it adds another div in the collection.

Any ideas how to get around this. Setting the display to none or hidden appears to break the Virtualization functionality.

> ```
> <ul class="o-ListTemplate__List c-Photographs__List"><div style="height: 0px;" _bl_2=""></div><li class="o-Card c-PhotographListItem ColumnSpan2"><div class="c-PhotographListItem__Image"><img loading="lazy" src="Content/Images/0000001320200210144829.jpg" asp-append-version="true"></div><div><ul style="list-style:none;"><li style="display:inline"><a href="animals/animal/7">Sugar</a></li></ul></div>
> 
>         <div class="o-ActionBar o-ListItem_ActionBar"><div class="o-ActionButtons o-ActionButtons__Secondary"><button class="safe" type="button" title="Tag"><span><i class="fas fa-tag"></i></span></button></div><div class="o-ActionButtons o-ActionButtons__Primary"><button class="safe" type="button" title="Edit"><span><i class="fas fa-edit"></i></span></button><button class="danger" type="button" title="Delete"><span><i class="fas fa-trash"></i></span></button></div></div></li><li class="o-Card c-PhotographListItem ColumnSpan2"><div class="c-PhotographListItem__Image"><img loading="lazy" src="Content/Images/0000001820200216131804.jpg" asp-append-version="true"></div><div><ul style="list-style:none;"><li style="display:inline"><a href="animals/animal/146">Rainbow</a></li></ul></div>
> 
>         <div class="o-ActionBar o-ListItem_ActionBar"><div class="o-ActionButtons o-ActionButtons__Secondary"><button class="safe" type="button" title="Tag"><span><i class="fas fa-tag"></i></span></button></div><div class="o-ActionButtons o-ActionButtons__Primary"><button class="safe" type="button" title="Edit"><span><i class="fas fa-edit"></i></span></button><button class="danger" type="button" title="Delete"><span><i class="fas fa-trash"></i></span></button></div></div></li><div style="height: 0px;" _bl_3=""></div></ul>
> ```

cc: @guardrex

**Comment by javiercn** [comment]
@SLFD-William thanks for contacting us.

We will look into this and update the issue accordingly.

**Comment by SteveSandersonMS** [comment]
We'll provide info about this inhttps://github.com/dotnet/AspNetCore.Docs/issues/20978

The summary is that `<Virtualize>` isn't intended to work with CSS grid because there isn't a safe place to insert placeholders. If you're using `<Virtualize>`, you should look at using CSS flex or traditional div/table layouts for that particular section of the UI.
