### ISSUE TITLE
HttpContext is not disposed of when calling a void webAPI function when using docker container. 

### ISSUE THREAD

**Issue by jonathansear** [dotnet/aspnetcore#28059]
### Describe the bug
If you create a web API .Net Core 3.1 function that returns void in a docker container, and the function is using the HttpContext object to set things like session objects it will throw a System.ObjectDisposedException: 'IFeatureCollection has been disposed.

### To Reproduce
To fix my web API I changed it from being void to returning something at the end of the request so the request persists which means the HttpContext persists.

`public async void OnPost`

to

`public async Task<IActionResult> OnPost`

Looks like the HttpContext was disposed before it was used... 

You may need to call this void function a few times for it to return the ObjectDisposedException

### Exceptions (if any)

System.ObjectDisposedException: 'IFeatureCollection has been disposed.

### Further technical details
N/A

**Comment by Tratcher** [comment]
Never use `async void` for web APIs. Use `async Task` if you don't have any return parameters. Otherwise the server doesn't know when your done and starts cleaning up immideately.
