### ISSUE TITLE
@microsoft/signalr: If HubConnection.send() is not awaited, no further send/invoke calls get executed

### ISSUE THREAD

**Issue by philippseith** [dotnet/aspnetcore#28054]
### Description
Applies to: @microsoft/signalr typescript package.
When `HubConnection.send()` is called without await, a second call to `HubConnection.send()` or `HubConnection.invoke()` is not executed. The same code works with the @aspnet/signalr package.
Because the caller of send does not expect a direct response, it seems to make no sense to enforce the usage of await. Furthermore, this makes it impossible to use send in synchronous code. 
It might be possible to circumvent the problem if only send would be affected, by storing the promise of the first call and putting the second call into the then() part of that promise. But this does not work with invoke calls, as they return `Promise<T>` with different T. 

### To Reproduce
jasmine/jest style test:
```typescript
it("should work", async() => {
  connection = builder
        .withUrl("http://127.0.0.1:5001/hub"
        .build();
    await connection.start();

    let or: (value?: unknown) => void;
    const p = new Promise((r, rj) => {
        or = r;
    });
    let tc = 0;
    // The server does call back with Clients.Caller.SendAsync("touched") 
    connection.on("touched", () => {
         tc++;
        if (tc == 2) {
            or();
        }
    })
    connection.send("touch");
    connection.send("touch"); // await connection.send("touch") doesn't work also
    await p;
})
```
The test timeouts at `await p;` because the callback is called only once. The callback is called only once because the server method is called only once.

**Comment by BrennanConroy** [comment]
Cannot repro the issue. We shouldn't be doing anything special here that requires you to await the send or invoke methods.

Can you provide a full repro app?

**Comment by philippseith** [comment]
I put the test into https://github.com/philippseith/signalr/tree/feature/messagepack.
Go to the subdir  signalr_test and run `npm run test`. The test will timeout, but if you add an await in https://github.com/philippseith/signalr/blob/592af58f49f0ad0a2e3e225fb75db11b83ccb065/signalr_test/spec/server.spec.ts#L96 it will work.

**Comment by BrennanConroy** [comment]
It looks like you're running the tests against a custom go SignalR server? That's pretty cool, but could you verify that the same behavior exists with a .NET SignalR Server?

**Comment by philippseith** [comment]
I am not able to reproduce it with a .NET SignalR Server. The problem lies in the go server. It is not able to parse more than one message from a json stream (here it is still in the state @davidfowl left it). When two sends are called without await both are sent in the same frame and not separated by an 0x1e byte.
