### ISSUE TITLE
Sln files

### ISSUE THREAD

**Issue by ragnaros12** [dotnet/aspnetcore#28058]
Sln projects do not contain any cs files.  How to fix it, and if I do what about wrong, then what

**Comment by rezathecoder** [comment]
You probably created a 'Blank Solution' which does not contain any file. You should create your project from provided templates in visual studio like 'ASP.NET Core Web Application'

**Comment by ragnaros12** [comment]
You didn't quite understand me.  For example, I want to edit a project.  I open the aspnetcore.sln file (from the folder cloned from this repository) and apart from empty solutions and iis (I do not know why it was loaded) I do not find a single file

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not entirely clear what you're trying to do.
If you're trying to clone and work with this (dotnet/AspNetCore) repo, then the [Build ASP.NET Core from Source](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md) may help you get started. Please make sure that you get all prerequisites installed.

If I'm not understanding you correctly, please try to rephrase the problem you're facing so that we can try to help.

**Comment by ragnaros12** [comment]
I am cloning the aspnetcore branch.  After I do this I execute restore.cmd.  Then the instructions say that you can run sln files.  But when you start visual studio, it says that "not all projects have been launched."  And in solution explorer there are only empty project folders that don't have any cs files.  I acted completely according to the instructions

**Comment by Pilchie** [comment]
What version of Visual Studio are you using and what branch/tag of dotnet/aspnetcore are you trying to open?

**Comment by ragnaros12** [comment]
Visual studio 2019 professional, and i tried to use v5.0 and v3.1

**Comment by Pilchie** [comment]
Can you post a screenshot/exact placement or wording of the 'not all projects have been launched' message. That isn't familiar to me, and makes it harder to route.

**Comment by ragnaros12** [comment]
![JCBDQ](https://user-images.githubusercontent.com/72325821/100385113-c239d480-3032-11eb-8b58-66dfd5d20dd8.jpg)
Ok

**Comment by Pilchie** [comment]
@davkean - any idea what might be happening here?  Note - this is trying to open this repo.

**Comment by ragnaros12** [comment]
I don't have ideas about this problem

**Comment by ragnaros12** [comment]
I dont have any idea about this

**Comment by wtgodbe** [comment]
@ragnaros12 are you using `startvs.cmd` to open the .sln file? https://github.com/dotnet/aspnetcore/blob/master/startvs.cmd

**Comment by JunTaoLuo** [comment]
There hasn't been any response in the past 7 days so we are closing this issue. Please reopen or open a new issue if you you would like to discuss further.
