### ISSUE TITLE
Url.Page() extension method is not very test-friendly for unit testing

### ISSUE THREAD

**Issue by tymur999** [dotnet/aspnetcore#28052]
## Summary

I've been having trouble with the unit testing any time I use Url.Page() inside the method I'm testing. Even when I supply an instance of IUrlHelper to the method, it still throws an exception about something. It seems that the Url.Page() test will refuse to work outside of actually loading the page. The Page method is for some reason one of the few that is a static extension of IUrlHelper, which makes it hard to unit test as the response can't be mocked and there can't be a wrapper class made because it is not actually a part of the interface. There will need to be some major abstraction done and editing of the actual method in order to support it for testing manually.
TL:DR - Why is Url.Link() mockable but Url.Page() is not? Let's fix that.

## Motivation and goals

The Url.Page() method is basically untestable without adding abstraction to the method of testing and changing it to be automatically added to the interface will allow it to be used for unit testing. Url.Page() is used in the Asp.net Identity scaffold, and being able to unit test that would be great. Url.Page() is also one of the only Url methods to accept an HttpRequest protocol in the URL, making it useful for those unique situations.

## In scope

Unit testing, mocking, that's basically the only time this is addressed.

## Out of scope

Running app manually and Integration Tests

## Risks / unknowns

Some might use the extensions class directly if the class is made un-static, so I think the Page() method should be put directly into the interface.  Some might have already used abstraction in their methods and tests to be able to swap the Url.Page() method, and changing the method to be in the interface will break those abstractions.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Before the fix:
```
Mock<IUrlHelper> urlHelper = new Mock<IUrlHelper>();
urlHelper.Setup(x => x.Link(It.IsAny<string>(), It.IsAny<object>())).Returns("http://localhost");
```
Devs forced to use Url.Link or other because Url.Page will throw an exception as it is a static class and cannot be mocked. Also, writing an interface such as:
```
public interface UrlHelper : IUrlHelper()
``` 
will not implement Page() because it is not part of the interface. I tried adding a Page method, but still, it did not change anything in the unit test.
After:
```
Mock<IUrlHelper> urlHelper = new Mock<IUrlHelper>();
urlHelper.Setup(x => x.Page(It.IsAny<string>(), It.IsAny<object>(), It.IsAny<string>(), It.IsAny<string())).Returns("http://localhost");
```
Developer should be able to simply mock the output of Page() instead of having to settle for abstraction or editing the method being tested by changing the Url.Page() to something like Url.Link().

<!--
# Detailed design

(WILL ADD TO THESE LATER)
Detailed design

Remove "static" in class UrlHelperExtensions or implement those extensions inside the IUrlHelper directly

Drawbacks
May not be compatible with builds that have already solved it by using abstraction

Considered alternatives
Anything that can make lead to it being mocked inside a unit test without unnecessary abstraction

Open questions
I'm open to any questions

References
None

**Comment by tymur999** [comment]
Hi, I think this should be the "enhancement" label instead of the "design-proposal" label. I think they could be both, though. I don't know how to move it myself, so any mod watching may switch the labels around.

**Comment by javiercn** [comment]
@tymur999 thanks for contacting us.

This would be a breaking change for existing customers, so we don't plan to do anything to address this unless we hear significant feedback that this causes an issue, since a change here would disturb the apps of many existing customers.
