### ISSUE TITLE
Allow set default JSON configuration source file's folder

### ISSUE THREAD

**Issue by tai-yi** [dotnet/aspnetcore#28066]
In some container cases, we usually mount `appsettings.json` to the container.

But there is a problem could break hot-reload-change.
When you update the file which mounted in the container, the container cannot get the newest version, so we can sat we lose the reload change ability.

When we mount a folder, the container always has the newest version.

see https://github.com/docker/for-win/issues/5530

`WebHost` load config from current directory. so if `WebHost` support load config files from given folder, that may help resolve this issue.

**Comment by BrennanConroy** [comment]
Are you rolling your own custom container or using one provided by dotnet?

The ones provided by dotnet set the polling file watcher to deal with this: https://github.com/dotnet/dotnet-docker/blob/9cb9aa049d9be928db17f6e16bfd7e6c0f5a07f0/eng/dockerfile-templates/sdk/5.0/Dockerfile.windowsservercore#L11
