### ISSUE TITLE
Need help debugging setup on ARM aarch64 machine (NXP i.MX8)

### ISSUE THREAD

**Issue by lovettchris** [dotnet/aspnetcore#28064]
### Describe the bug
I'm trying to install .net core 3.1 on an NXP i.MX8 computer running aarch64 version 10 of Debian Linux and install succeeds, but dotnet won't run.

```
chris@iot-gate-imx8:~$ ./dotnet/dotnet
-bash: ./dotnet/dotnet: No such file or directory
```

When I try and build the repo https://github.com/dotnet/aspnetcore I get the same error from `./build.sh`
```
dotnet-install: Installation finished successfully.
/home/chris/aspnetcore/eng/common/tools.sh: line 438: /home/chris/aspnetcore/.dotnet/dotnet: No such file or directory
Build failed (exit code '127').
```

Perhaps it has a missing dependency?

### To Reproduce
Following the [manual setup instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#apt-troubleshooting), I installed all the prerequisite packages for Debian 10, and ran the `dotnet-install.sh` script, which succeeded.

`gdb` says "./dotnet/dotnet" is not in executable format: file format not recognized?

`readelf` says it is ELF64, and AArch64 which is all good.

Don't know if this is an issue but readelf shows symbols depending on GLIBC_2.17, and GCC_3.0, and GLIBCXX_3.4.21, and CXXABI_1.3.  But this version of linux comes with glibc 2.28-10, and libgcc-8, and libg++-8 ?

### Further technical details
- ASP.NET Core version 3.1 and 5.0 both yield the same result.
- Include the output of `dotnet --info` (can't run that yet)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version (N/A)

**Comment by lovettchris** [comment]
Interestingly enough the docker image works fine on the same machine:

![image](https://user-images.githubusercontent.com/18707114/99927541-91883100-2cfa-11eb-8356-7e0f2ea4399d.png)

**Comment by lovettchris** [comment]
And the dependent package list is virtually identical.  Once difference is the native machine also has a whole bunch of cross-platform libraries for libcx and libgcc, probably to support gcc cross-compile.  I did not find any libraries in the docker image that were not installed on the native machine...  weird.
```
imx8:
libc6/stable,now 2.28-10 armhf [installed]
libgcc1/stable,now 1:8.3.0-6 armhf [installed]
libicu63/stable,now 63.1-6+deb10u1 armhf [installed]
libssl1.1/stable,now 1.1.1d-0+deb10u3 armhf [installed]
libstdc++6/stable,now 8.3.0-6 armhf [installed]
zlib1g/stable,now 1:1.2.11.dfsg-1 armhf [installed]

docker image:
libc6/now 2.28-10 armhf [installed,local]
libgcc1/now 1:8.3.0-6 armhf [installed,local]
libicu63/now 63.1-6+deb10u1 armhf [installed,local]
libssl1.1/now 1.1.1d-0+deb10u3 armhf [installed,local]
libstdc++6/now 8.3.0-6 armhf [installed,local]
zlib1g/now 1:1.2.11.dfsg-1 armhf [installed,local]
```
The only really minor difference I could find in package versions was this:
```
a-certificates docker has now 20200601~deb10u1 all [installed,local], imx8 has stable,now 20190110 all [installed]
libldap-2.4-2 docker has now 2.4.47+dfsg-3+deb10u4 armhf [installed,local], imx8 has stable 2.4.47+dfsg-3+deb10u2
libldap-common docker has now 2.4.47+dfsg-3+deb10u4 all [installed,local], imx8 has stable 2.4.47+dfsg-3+deb10u2 all [upgradable from: 2.4.47+dfsg-3+deb10u1]
tzdata docker has now 2020d-0+deb10u1 all [installed,local], imx8 has stable 2020a-0+deb10u1 all [upgradable from: 2019c-0+deb10u1]
```

**Comment by lovettchris** [comment]
By the way, I tried a different i.MX8 board from CompuLab running Debian 11 and it works fine, so I wonder if there is a problem with debian 10 ?

**Comment by wtgodbe** [comment]
@lovettchris sorry for not responding more quickly - I see you're running into an error with the `.dotnet\dotnet` folder, which is where our build does the local install of `dotnet`. Is it accurate that that folder does not exist after you see the error you mentioned?

**Comment by Pilchie** [comment]
Tagging @tommcdon who might know more about this.

**Comment by tommcdon** [comment]
@mikem8361 @hoyosjs

**Comment by hoyosjs** [comment]
I tested this on Debian 10.6 ARM64 using `./dotnet-install.sh --install-dir dotnet-test --architecture arm64 --version 3.1.404` and I can use `./dotnet-test/dotnet` without any issues. The list of dependencies list `armhf` and the RID in your working sample points at `debian.10-arm`, meaning that regardless of the board, you seem to hint you are targeting ARM32/armv7? If so, readelf and file shouldn't say:

> readelf says it is ELF64, and AArch64 which is all good.

I'd expect it to say ARM, along the lines of ` ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, with debug_info, not stripped`. What's the output of `uname -a`?

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the questions asked here have been answered.
