### ISSUE TITLE
Blazor Server registers page 'unload' event instead of the recommended 'pagehide' or 'visibilitychange events

### ISSUE THREAD

**Issue by nagytam** [dotnet/aspnetcore#28070]
### Describe the bug
The Chrome browser's Lighhouse (https://developers.google.com/web/tools/lighthouse) check indicates that the Blazor Server registers page 'unload' event instead of the recommended 'pagehide' or 'visibilitychange events. 

Location: blazor.server.js:8

### To Reproduce
Any Blazor server projects can be used.

### Further technical details
ASP.NET Core 5.0
Chrome version: 87.0.4280.66 (Official Build) (64-bit), Windows

**Comment by javiercn** [comment]
@nagytam thanks for contacting us.

That's by design. We don't want to terminate your app on the server when the page is hidden or the visibility of the page changes, only when the user browses away from the page.

**Comment by nagytam** [comment]
Makes sense. Thanks for the explanation.
