### ISSUE TITLE
Blazor InputSelect Boolean issue

### ISSUE THREAD

**Issue by ericschambach** [dotnet/aspnetcore#28078]
I have been having a weird problem with a InputSelect for boolean that I have made, using as a template the InputSelectNumber class that I am sure you have seen being shared around (see below):

```
public class InputSelectNumber<T> : InputSelect<T>
{
	protected override bool TryParseValueFromString(string value, out T result,
		out string validationErrorMessage)
	{
		if (typeof(T) == typeof(int))
		{
			if (int.TryParse(value, out var resultInt))
			{
				result = (T)(object)resultInt;
				validationErrorMessage = null;
				return true;
			}
			else
			{
				result = default;
				validationErrorMessage = "The chosen value is not a valid number.";
				return false;
			}
		}
		else
		{
			return base.TryParseValueFromString(value, out result, out validationErrorMessage);
		}
	}
}
```

And below, with a couple of tweaks, made it work with booleans (it does work without issues): 

```
public class InputSelectBoolean<T> : InputSelect<T>
{
	protected override bool TryParseValueFromString(string value, out T result,
		out string validationErrorMessage)
	{
		if (typeof(T) == typeof(bool))
		{
			if(bool.TryParse(value, out var resultBool))
			{
				result = (T)(object)resultBool;
				validationErrorMessage = null;
				return true;
			}
			else
			{
				result = default;
				validationErrorMessage = "The chosen value is not a valid boolean.";
				return false;
			}
		}
		else
		{
			return base.TryParseValueFromString(value, out result, out validationErrorMessage);
		}
	}
}
```

Then on the razor page, the implementation is:

```
<EditForm Model="@isMyConverted">
	<InputSelectBoolean @bind-Value="@isMyConverted">
		<option value="true" selected>USD</option>
		<option value="false">XOM</option>
	</InputSelectBoolean>
</EditForm>
 
@code {
	public bool @isMyConverted = false;
}
```

It actually works perfectly, and it makes the changes it is supposed to. However, on the selector pane, it is always empty by default, so not showing either USD or XOM. I have to select a value twice for it to stay showing on the pane. Otherwise, it stays empty (even if the changes to the actual variable occurs perfectly).

If I change the whole thing to an Int input, like this:

```
<EditForm Model="@isMyConverted">
    <InputSelectNumber @bind-Value="@isMyConverted">
        <option value="1" selected>USD</option>
        <option value="2">XOM</option>
    </InputSelectNumber>
</EditForm>

@code {
public int isMyConverted = 1;
}
```

Everything works great and the selected value is there in the selector pane as expected. Any help would be appreciated.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
