### ISSUE TITLE
lambda variables capture in for loop error 

### ISSUE THREAD

**Issue by congzhangzh** [dotnet/aspnetcore#28075]
### Describe the bug
lambda on event callback in for loop cannot correctly capture loop variable (It's an old c# bug, and be fixed in c# a long time ago) 

Error: all the lambda captures same loop variable but not the local value

### To Reproduce

```Razor
<nav class="nav nav-pills nav-fill">
    @for (int i = 0; i < 4; ++i)
    {
        <a class="@(step == i ? "nav-item nav-link active" : "nav-item nav-link ")" @onclick="@(_ => step=i)" @onclick:preventDefault href="#" >Page @i</a>
    }
</nav>

@code {
  private int step = 0;
}

```

which equal to,

```Razor
<nav class="nav nav-pills nav-fill">
    @for (int i = 0; i < 4; ++i)
    {
        <a class="@(step == i ? "nav-item nav-link active" : "nav-item nav-link ")" @onclick="@(_ => step=4)" @onclick:preventDefault href="#" >Page @i</a>
    }
</nav>
```

A workaround:

```Razor
<nav class="nav nav-pills nav-fill">
    @for (int i = 0; i < Count; ++i)
    {
        var localIndex = i; 
        <a class="@(step == localIndex ? "nav-item nav-link active" : "nav-item nav-link ")" @onclick="@(_ => step=localIndex)" @onclick:preventDefault href="#" >Page @localIndex</a>
    }
</nav>
```

### Further technical details

% dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@congzhangzh thanks for contacting us.

This is a well-known C# limitation. The recommendation is that you use a `foreach` loop instead which has the right behavior on it or that as an alternative you capture the index on a variable within the loop body.

**Comment by congzhangzh** [comment]
@javiercn tks, and after some level of rethinking about it, the current behavior seems right and more semantics meaningful
