### ISSUE TITLE
NTLM is not working with HTTP.sys of ASP.NET Core 2.1 on .NET 4.8 with https and wildcard certificate when accessing from same machine

### ISSUE THREAD

**Issue by christiantinauer** [dotnet/aspnetcore#28088]
The NTLM authentication does not work with HTTP.sys of ASP.NET Core 2.1 on .NET 4.8 with https when accessed from the browser on the same machine the server is running on. `HttpContext.User.Indentity.IsAuthenticated` stays false. Nevertheless it works when accessed from any other machine. This behaviour is independent of the used browser (I tried FF, Chrome, IE11).

The wildcard certificate is issued for example to ***.mycompany.com** and the url used for serving with HTTP.sys is **https://server01.mycompany.com:443**. The certificate is added as instructed [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.1#configure-windows-server).

To narrow the problem down, I tried the following setups:
- HTTP.sys of ASP.NET Core 2.1 on NET 4.8.
- HTTP.sys of ASP.NET Core 2.2 on NET 4.8.
- HTTP.sys of ASP.NET Core 5 on NET 5.

Setup for HTTP.sys of ASP.NET Core 2.1 on NET 4.8 is:

```
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace WildcardCertificateHttpsysTests
{
    class Program
    {
        static void Main(string[] args)
        {
            WebHost.CreateDefaultBuilder(args)
                .Configure(app =>
                {
                    app
                        .UseAuthentication()
                        .Use(async (current, next) =>
                        {
                            var user = current.User;
                            if (user != null)
                            {
                                current.Response.StatusCode = 200;
                                await current.Response.WriteAsync($"{user.Identity.IsAuthenticated} {user.Identity.Name}");
                            }
                            else
                            {
                                current.Response.StatusCode = 400;
                            }
                        });
                })
                .UseHttpSys(options =>
                {
                    options.Authentication.AllowAnonymous = false;
                    options.Authentication.Schemes = Microsoft.AspNetCore.Server.HttpSys.AuthenticationSchemes.NTLM | Microsoft.AspNetCore.Server.HttpSys.AuthenticationSchemes.Negotiate;
                    options.UrlPrefixes.Add("https://server01.mycompany.com:443");
                })
                .Build()
                .Run();
        }
    }
}
```

The same problem does exist for all mentioned setups.

**Comment by BrennanConroy** [comment]
Can you verify the same behavior without https?

**Comment by christiantinauer** [comment]
Behavior is the same for e.g. **http://server01.mycompany.com:8091** when accessing from same machine, Works when accessed from different machine.

Nevertheless **http://+:8091** and **http://localhost:8091**behaves correctly.

Problem seems to be related to the url/hostname?

**Comment by Tratcher** [comment]
Because you have both Negotiate and NTLM enabled I suspect ` server01.mycompany.com` works remotely because it's using Negotiate/Kerberos. Kerberos doesn't work on requests to the same machine so Negotiate falls back to NTLM. If you disable Negotiate I'd expect to see consistent behavior locally and remotely using NTLM.

Is `server01.mycompany.com` really the fully qualified domain name of the local machine? Or is it an alias set up in active directory? What's the "Full device name" that shows up in the System control panel?

**Comment by christiantinauer** [comment]
Actually it is the other way round. It works from a different machine with only NTLM, but never with only Negotiate.

The "full device name" is `server01.graz.mycompany.com`.

**Comment by christiantinauer** [comment]
I have to reopen the issue as I still don't understand why it works from a different machine and not from the same machine. Even without https it does not work with `server01.graz.mycompany.com` from the same machine.

I don't think it is a DNS problem, as the ip is resolved correctly when accessed from same machine and the server responds. But it only gives an endless loop of the credential window in the browser. Is this related to the HttpApi?

**Comment by Tratcher** [comment]
NTLM and Kerberos are strongly tied to machine identities, they include the expected name (SPN) as part of the auth handshake. There is the ability in the protocol to allow for alternate names but it requires configuration. For Kerberos that configuration happens in Active Directory and I assume that's what you've done for "server01.mycompany.com". For NTLM the alternatives have to be configured in the application, but that's not currently supported by HttpSys, I'm not sure it's possible for the kernel mode auth APIs we use.

**Comment by christiantinauer** [comment]
> 
> 
> NTLM and Kerberos are strongly tied to machine identities, they include the expected name (SPN) as part of the auth handshake. There is the ability in the protocol to allow for alternate names but it requires configuration. For Kerberos that configuration happens in Active Directory and I assume that's what you've done for "server01.mycompany.com". For NTLM the alternatives have to be configured in the application, but that's not currently supported by HttpSys, I'm not sure it's possible for the kernel mode auth APIs we use.

Now that I've configured "server01.mycompany.com" in AD the Negotiate-Auth does work. Also when on the same machine. Took me some time to understand what I had to do with the SPNs. And you are absolutly right about NTLM.

For Firefox the url of the server has to be added to the trusted negotiate urls via "about:config" -> "network.negotiate-auth.trusted-uris" to work. With Chrome the username has to be fully qualified with DOMAIN\username.

@Tratcher thank you very much for pointing me in the right direction!
