### ISSUE TITLE
Publish asp.net core 3.1 with dependencies

### ISSUE THREAD

**Issue by juanan** [dotnet/aspnetcore#28081]
Hi,

I have an asp.net core 3.1 project (lets call it A.proj) that has a reference to other asp.net core 3.1 project (lets call it B.proj) via hint path.

When I run "dotnet publish A.proj" the library B.dll is present in the outuput directory but no all the Nuget packages that B.proj contains.

How can I achieve that?

Many thanks.

**Comment by javiercn** [comment]
@juanan thanks for contacting us.

This is not an ASP.NET Core specific problem. We transferred an identical issue you filed to https://github.com/dotnet/sdk/issues/14657 where they will be able to give you a better and faster answer.
