### ISSUE TITLE
<AuthorizeView Roles="admin"> never rendered in blazor wasm 5.0, even when authentified in that role

### ISSUE THREAD

**Issue by dumaisf** [dotnet/aspnetcore#28083]
### Blazor wasm 5.0, individual account authentification

This follow the ASP.NET Core 5.0 documentation (doesn't work)
```
<AuthorizeView Roles="admin">
    <p>You are in admin role</p>
</AuthorizeView>
```

Tried to add Authorized  (doesn't work either)
```
<AuthorizeView Roles="admin">
    <Authorized>
        <p>You are in admin role</p>
    </Authorized>
</AuthorizeView>
```

In my SQL database:
**AspNetUsers** table only one user
**AspNetRoles** table only one role (admin)
**AspNetUserRoles** the user is attached to the role admin

I login in the web app with that user in the admin role, the paragraph is never rendered.

### Further technical details
- ASP.NET Core version
  .NET SDKs installed: 5.0.100
  .NET runtimes installed: 5.0.0
- The IDE (Microsoft Visual Studio Community 2019 Preview
Version 16.9.0 Preview 1.0)

**Comment by javiercn** [comment]
@dumaisf thanks for contacting us.

Can you point us to the docs you are following and provide a minimal repro project that illustrates this issue?

**Comment by dumaisf** [comment]
The documentation for <AuthorizeView>:
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#authorizeview-component

**Comment by dumaisf** [comment]
Here is the link to the Github Repository:
[Click here for repository](https://github.com/dumaisf/BlazorCrud-AuthorizeView.git)
### To reproduce the problem

- Open the solution in _Visual Studio_
- Change the default connexion in **BlazorCrud.Server/appsettings.json** to point to your _local SQL server_.
- Build Solution
- In _Package Manager Console_, enter: `update-database`
- Start the execution
- login with the **administrator** role:
  **user**: admin@microsoft.com
  **password**: Admin1234$
- In the _Index page_ you see "You are not the administrator!" (This is the bug because you are!!!)
- To verify that you are the **Administrator**, check the SQL Database tables: _AspNetUsers_, _AspNetRoles_ and _AspNetUserRoles_

**Comment by javiercn** [comment]
@dumaisf I took a look at the repro, it seems that you are missing the required steps to configure roles in Blazor Webassembly. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#custom-user-factory) for details on how to do it.

**Comment by javiercn** [comment]
If you still have problems after following the steps described in the provided link, please let us know.
