### ISSUE TITLE
Blazor Title / Head Tools in Microsoft.AspNetCore.Components.Web.Extensions Error

### ISSUE THREAD

**Issue by VicSmith** [dotnet/aspnetcore#28092]
**Regarding:**
Microsoft.AspNetCore.Components.Web.Extensions **5.0.0-preview9.20513.1**

In headmanager.js

Wanted to report this error in my blazor project javascript console. The title actually updates but the error is there. The title does have a large lag in updating the first time.
Please see: [https://www.screencast.com/t/FTDV3cXkSx8](https://www.screencast.com/t/FTDV3cXkSx8)

Steps to reproduce...

- Use the preview title functionality for blazor as of 2020-11-20.
- Compile blazor server project using the title functionality.
- View javascript console for error on any page/view click.

**Comment by javiercn** [comment]
@VicSmith thanks for contacting us.

This is not a feature we currently support, we created a preview package but decided to hold off on shipping it in 5.0 due to design concerns.
