### ISSUE TITLE
Send a json object to .net server using signalr and Java client

### ISSUE THREAD

**Issue by zulander1** [dotnet/aspnetcore#28095]
I am using SignalR 5.0, I am trying to send a JSON from the Android client. The send works I get the json in the test "{"Id":"123123","ReceviedDateTime":"Nov 23, 2020 12:50:55 PM","RepliedDatetime":"Nov 23, 2020 12:50:55 PM"}" but the Pong method is never called. Added services.AddSignalR().AddJsonProtocol(); in the startup

Pong model:

```
public class PongModel
{
    public int Id { get; set; }
    public int DeviceId { get; set; }
    public string PhoneNumber { get; set; }
    public DateTime SendDatetime { get; set; }
    public DateTime ReceviedDateTime { get; set; }
    public DateTime RepliedDatetime { get; set; }
}

```
Methods (.net core 5)

    public void Pong(PongModel pongModel)
    {
    }

    public void Send(string test)
    {
    }

Java:

        hubConnection.on("Ping", (id) -> {

            Pong p = new   Pong();
            p.setDeviceId(TelephonyMgr.getDeviceId());
            p.setId(id);
            p.setPhoneNumber(TelephonyMgr.getLine1Number());
            p.setReceviedDateTime(Calendar.getInstance().getTime());
            p.setRepliedDatetime(Calendar.getInstance().getTime());

            Gson  gson = new Gson() ;
            String json = gson.toJson(p);
            hubConnection.send("Pong", json);
            hubConnection.send("Send", json);
        }, String.class);

**Comment by BrennanConroy** [comment]
SignalR automatically serializes and deserializes for you. What this means is that if you pre-serialize your object and send that, then SignalR will be sending your object as a string instead of as an object.

Remove the manual gson and it should start working. Or if for some reason you need to serialize it yourself, then change the server method to receive a string and then deserialize it yourself.

**Comment by zulander1** [comment]
@BrennanConroy :
I've removed the string not working like: hubConnection.send("Pong", p);

**Comment by BrennanConroy** [comment]
Can you capture debug logs on the server and/or share the network traffic?

**Comment by zulander1** [comment]
@BrennanConroy, working saw the binding error thank's
