### ISSUE TITLE
Blazor pages do not honor interface inheritance

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28099]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-pages-do-not-honor-interface-inhe/1256291?preview=true)._

---
[severity:It's more difficult to complete my work]
Given a marker interface that simply declares different Bounded contexts within a solution:  

```
public interface IBoundedContext
{
   public interface Realestate : IBoundedContext{}
   public interface Employment: IBoundedContext{}
}
```

And a repository construct that will read from different repositories depending on which bounded context it is operating within: 
```
public Interface IReadOnlyRepositoryFor<TReadModel, TBoundedContext>
where TReadModel : IReadModel
where TBoundedContext : IBoundedContext
{
   Task<TReadModel> GetById(Guid id);
}
```

In Blazor, when I create a general component for use in different contexts, for example, a "RestaurantList.razor" component, 
the component page will have a parameter that takes in a repository: 

```
[Parameter]
public IReadOnlyRepositoryFor<Restaurant, IBoundedContext> RestaurantReader{ get; set; }
```

To use this component in a page , I would then inject an instance of  the repository, and provide that instance to my 
component as such:

```
@inject IReadOnlyRepositoryFor<Restaurant, IBoundedContext.Realestate> restaurantReader;

<RestaurantList RestaurantReader="restaurantReader" />

@code{

}
```

I EXPECT this to work, because the IBoundedContext.Realestate IS an IBoundedContext, however, the compiler complains that it cannot 
convert IBoundedContext.RealEstate to an IBoundedContext. 

This makes it very hard to create reusable components if they don't support generic interfaces.

---
#### Feedback Bot on 11/19/2020, 01:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

This seems to be a question about C# and not specifically about Blazor. We believe the problem you are referring to here is a known C# behavior. To learn more about this, we recommend you to look at covariance and contravariance on interfaces.
