### ISSUE TITLE
Blazor PWA application does not reach the server for authentication due to service worker

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/aspnetcore#28101]
Hi

I've made a blazor wasm application, aspnet core hosted, with google authentication and custom AuthenticationStateProvider. When i try to create the same application from scratch but selecting Progressive Web App upon project creation, i'm not able to authenticate users. I've replicated the situation by building again a simple blazor wasm app with google authentication and custom AuthenticationStateProvider and again the exact same steps on the PWA version.
It doesn't work!
In this [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio)  is missing what we are supposed to change in PWA application to be able to login with identity providers.

Debug:
I see that the redirection from "user/signin" back to "/" is not working, it stays in address "user-signin" and in the log on visual studio there's a error message saying: "Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Authorization failed."
In the network tab i see the navigation to "user/signin" and at the end, when trying to retrieve the user, the data for "/user" is retrieved from the service worker.
**In fact the "user/signin" is also served by the service worker. No wonder that the application doesn't logs users. It cant reach the server.**
I cant understand why this happens but the documentation should state what are the adaptations we should do on the PWA scenario to keep the login working...

Thanks

cc: @guardrex 
Original issue: https://github.com/dotnet/AspNetCore.Docs/issues/20742

[Enter feedback h

### Describe the bug
On clicking the login button i'm redirected to google for login. After selecting my account i'm redirected back to application with the google redirect url i've set in the google authentication service being displayed on the address bar, and the page displaying that nothing could be found at that address. That address is supposed to be consumed by the Microsoft.AspNetCore.Authentication.Google library on the server side but seems it gets trapped on frontEnd...

### To Reproduce
Repo with the PWA version that is exactly the same as the other one except. The only difference is that this one was created with PWA option checked upon project creation: https://github.com/Ricardoaraujo00/BlazorApp3

Steve Sanderson solution that doesn't work [here](https://github.com/dotnet/aspnetcore/issues/20888)
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Ricardoaraujo00** [comment]
I've made some checking and this problem shouldn't arise as in development mode the service worker should always pull from the server.
This code is on "service-worker.js" which is the one used on development:

"// In development, always fetch from the network and do not enable offline support.
// This is because caching would make development more difficult (changes would not
// be reflected on the first load after each change).
self.addEventListener('fetch', () => { });
.js  
So in fact seems that the Steve Sanderson solution may be correct even today.
This leave us with no clues for the reason why the service worker is hindering the login procedure even in development...

Debug:
I've made a new project with userlogins in app to check if there is any difference in the development service-worker and there wasn't any. In the published version of the service-worker there is in fact the exclusion as Steve Sanderson stated

const shouldServeIndexHtml = event.request.mode === 'navigate'
            && !event.request.url.includes('/connect/')
            && !event.request.url.includes('/Identity/');
There must be something else that we must change in order to make PWAs with a custom authentication state provider.
I don't see any major difference on the client side project.
The only one is in program.cs.
Mine:

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();
Templated:

builder.Services.AddHttpClient("BlazorApp5PWAwithlogins2.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

            // Supply HttpClient instances that include access tokens when making requests to the server project
            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp5PWAwithlogins2.ServerAPI"));

            builder.Services.AddApiAuthorization();
When i move the mouse over "builder.Services.AddApiAuthorization();" it says: "Adds support for authentication for SPA applications using ApiAuthorizationProviderOptions and the RemoteAuthenticationState"

I check that this is dependent on the Microsoft.AspNetCore.Components.WebAssembly.Authentication nuget package which i installed but for some reason the extension method is not detected. On the users in-app templated project the installed version of this nugget package is 3.2.1.0, which i cannot install in my project due to my project being 3.1 version. But i can install the 5.0 version, but as i said the extension code is not detected.

On the users in-app templated project, on the server side, there is also reference to identity server on the start-up class:

services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

            services.AddAuthentication()
                .AddIdentityServerJwt();
and there is also the line "app.UseIdentityServer();" on the configure method still inside startup.cs

Seems there must be done some amount of tweeking to be able to make a PWA Blazor app login with a custom login and custom authentication state provider. Some documentation and guidance is needed to accomplish this because this is a much needed feature.

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for contacting us.

Could you update to 5.0 and let us know if you can still reproduce the issue?

**Comment by Ricardoaraujo00** [comment]
I cannot. There are some braking changes with the packages that i cannot resolve. Although it does not seems that this is a framework version related issue because if i comment the line that loads the service worker on the index file everything works. You might give it a try in the repo that i linked on "How to reproduce". Maybe you can even do the version update. I was hindered on the signout endpoint on the API because the response can no longer be an IActionResult but a ISignoutResult or something like that. And from them on another change is needed, then another and another and i don't know how to handle that.

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for the additional details.

What evidence do you have to claim that the service worker is causing the issues here? Does it work if you remove your service worker registration from index.html and clear all the state for the application in the developer tools?

**Comment by Ricardoaraujo00** [comment]
Sorry for the delay @javiercn 
Yes, the application works properly if i just comment this line on index.html like so:


I just tested again. I had to also clean the browser cache. I didn't had to select the solution with right mouse click and select clear, if that is what you mean with "clear all the state for the application in the developer tools".

**Comment by guardrex** [comment]
@Ricardoaraujo00 ... Add triple backtacks  :point_up: ... \`\`\` ... on the lines above and below that code to make it appear in the issue comment.

**Comment by javiercn** [comment]
@Ricardoaraujo00 thanks for the additional details.

I believe this is to be expected, what likely happened here is that at some point the publish/production service-worker got installed for the same origin and that was causing the issues. 

Unfortunately, when you open a page with a service-worker it doesn't pick up the update until you navigate away from the page and come back, which might explain what you were experiencing. We do have some docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#caveats-for-offline-pwas) about it.

The recommendation (specially on a dev environment) is to clean the app state when these things happen. 

Keep in mind that this is not a Blazor specific behavior but a browser one, so there's limited things we can do.

**Comment by Ricardoaraujo00** [comment]
Sorry, my bad.
On the service worker script i did not included the return url from the google signin service in the service worker excluded cache adresses on the onFetch method. Like so:

`const shouldServeIndexHtml = event.request.mode === 'navigate'
        && !event.request.url.includes('/user')
            && !event.request.url.includes('/user/signin')
            && !event.request.url.includes('/signin-google');`

I had tried it before but i was wrongly excluding "/user/signin-google" and the correct address to exclude should be "/signin-google", as it is on the last line.
Maybe this information should appear in [Build Progressive Web Applications with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#caveats-for-offline-pwas) documentation.
Thanks anyway for the support

**Comment by guardrex** [comment]
> Maybe this information should appear

@Ricardoaraujo00 ... This product unit issue is cross-linked to the docs issue, but I'll copy your last comment over to the docs issue and schedule the docs issue for work.

Unless you want to submit a docs PR against https://github.com/dotnet/AspNetCore.Docs/issues/20742 (i.e., PR with `Fixes #20742` in the opening comment), I can work on this, but it won't be until 2021 given my current workload. In a couple of weeks, I'm taking a ⛄ *holiday vacation* 🎁 for some rest, relaxation, and *recovery* 😅.

**Comment by Ricardoaraujo00** [comment]
@guardrex i've found out how to do a PR to that documentation(i didn't knew) but i think i won't be able to use the proper language to explain the issue. I'm even running through a fog trying making this authentication, relying in tutorials and almost just following allong.
So, in this situation when i'm using a custom authentication state provider to authenticate the user on the aspnet core backend using Microsoft.AspNetCore.Authentication.Google, i must ensure to have three adresses excluded from the service worker cache(?), which are those ones that i stated, being the last one, as far as i can tell, related to the google authentication nuget package. 
Have a nice vacation 👍
