### ISSUE TITLE
Visual Studio Latest Update - Missing Blazor New Project Templates for Core 5

### ISSUE THREAD

**Issue by deanchalk** [dotnet/aspnetcore#28105]
### Describe the bug
Creating a new Blazor project after intalling the latest .NET Core 5 and the latest Visual Studio update (16.8.2), the template creates a solution with the old blazor project templates - i.e. the .NET version is Standard 2.1 etc.
Creating a new Blazor app using the dotnet command on the command line works correctly (creates a .NET Core 5 blazor app)

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment]
@deanchalk thanks for contacting us.

Did you select .NET 5 in the framework version drop down in the file new dialog? 
I'm not sure if the menu is sticky and you might picked up 3.1 by mistake.

If you don't care about loosing any other installed template (not sure if you have any) you can try go to `%userprofile%\.templateengine` and remove the folder, then close and open visual studio and it should reinitialize the templates.

**Comment by deanchalk** [comment]
OMG sorry - I completely missed the framework drop-down option, I just assumed it would just be .NET 5
everything is fine - thanks

**Comment by Grauenwolf** [comment]
FYI: If you pick "Blazor" for the project type filter, none of the new Blazor projects show up. I'm only seeing the old .NET 3.0 templates.

If I search for Blazor I see the templates that allow me to choose between 3.1 and 5.0. So it seems that it is just an issue of the tags missing on the templates.
