### ISSUE TITLE
DataProtection - From 'default' to 'PersistKeysToDbContext' - Adding key previously encrypted with DPAPI in database

### ISSUE THREAD

**Issue by sylvainb31** [dotnet/aspnetcore#28106]
Hello,

I'm using IDataProtectionProvider to encrypt / decrypt data.
Here is my usecase :
- I encrypt data
- I send the data in a link in an e-email
- The user click on the link and the data is decrypted in the application.

I was first using DataProtection without specifying any protection strategy. The default one was then used and the keys were stored in windows registred, encrypted with Windows DPAPI.

Here is what the key stored in the registry looks like :

```
<key id="***" version="1">
  <creationDate>2020-10-05T14:34:55.5758168Z</creationDate>
  <activationDate>2020-10-06T12:41:22.6368851Z</activationDate>
  <expirationDate>2021-01-03T14:34:55.4579802Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.4.0, Culture=neutral, PublicKeyToken=***">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <encryptedSecret decryptorType="Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.4.0, Culture=neutral, PublicKeyToken=***" xmlns="http://schemas.asp.net/2015/03/dataProtection">
        <encryptedKey xmlns="">
          <!-- This key is encrypted with Windows DPAPI. -->
          <value>***</value>
        </encryptedKey>
      </encryptedSecret>
    </descriptor>
  </descriptor>
</key>
```

Everything was working perfectly. But then I decided to update to asp net core 5.0.0.0 and to change the strategy used to store the keys :

```
services.AddDataProtection()
                .PersistKeysToDbContext<ApplicationDbContext>();
```

Now the key stored in the database looks like this :

```
<key id="***" version="1">
  <creationDate>2020-11-22T16:03:55.4197658Z</creationDate>
  <activationDate>2020-11-22T16:03:53.9445302Z</activationDate>
  <expirationDate>2021-02-20T16:03:53.9445302Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=5.0.0.0, Culture=neutral, PublicKeyToken=***">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection"><!-- Warning: the key below is in an unencrypted form. -->
        <value>***</value>
      </masterKey>
    </descriptor>
  </descriptor>
</key>
```
I'm in a bit of tight spot because now I only have my newly added key to the database, which means that only the data protected since my last update can be decrypted by my application. All the data protected before with the key stored in the windows registry cannot.

So here is my question :
**What can I do to still decrypt my data with the previous key which was stored in windows registry with a different version of asp net core and encrypted with Windows DPAPI ?**

I've thought about adding a new line in my table storing the old key in my database but I don't know the consequences of doing this.

Thanks for your help.

Best regards,

Sylvain

**Comment by blowdart** [comment]
- Unencrypt your data using the old keyring, on a machine it can be read on.
- Switch to new keyring.
- Re-encrypt your data.

That's pretty much it.

Oh, and please consider protecting the new keyring with encryption, right now the keys are in plain text in your database.

**Comment by sylvainb31** [comment]
Hi Barry,

Thanks for your answer.

I need to decrypt both the data encrypted with the old version and the data encrypted with the same version at the same time on the same application which is at the latest version of asp net core (5.0).
In practice, the encrypted data has been sent in e-mail as a parameter contained in the url of my application before and after my update.
In my application, I read the parameter contained in the url and decrypt it.
Which means that after my update, users who received an e-mail before the update open the application by clicking on the link with a data parameter encrypted with the previous key.
What I want is that both keys appear in my database table : 
- the old one that was stored on the windows register encrypted with Windows DPAPI
- the new one that is already stored on the database table
This way my update is transparent to the user.

**How can I add the old key that was encrypted with Windows DPAPI in my table database so that I have both keys in my keyring ?**

Thanks for your help.

Sylvain

**Comment by blowdart** [comment]
There's no support for multiple keychains in different locations right now. You could, I'd *guess* use DPAPI to unencrypt the key itself, then write an unencrypted xml entry to your database manually, keeping everything else the same, but you're far into unsupported territory now, and I'm on vacation until the new year so I'm only popping in and out of github at random :)
