### ISSUE TITLE
Blazor wasm 5.0 Server project API controller cannot be called anonymously from client side index page

### ISSUE THREAD

**Issue by dumaisf** [dotnet/aspnetcore#28116]
### Blazor wasm 5.0 - Individual account authentification

In my home index page, I call an anonymous API in the Server project:
```
    protected override async Task OnInitializedAsync()
    {
        if (!Busy)
        {
            Busy = true;

            try
            {
                Numbers = await HttpClient.GetFromJsonAsync<List<int>>("home");
            }
            catch (AccessTokenNotAvailableException exception)
            {
                exception.Redirect();
            }
            catch (HttpRequestException)
            {
                Numbers = null;
            }
            finally
            {
                Busy = false;
            }
        }

        await base.OnInitializedAsync();
    }

```
The API controller allow anonymous call at the controller level:
```
namespace BlazorCrud.Server.Controllers
{
    [Route("home")]
    [ApiController]
    [AllowAnonymous]
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult<List<int>> GetAll()
        {
            return new List<int>() { 1, 2, 3, 4, 5 };
        }
    }
}
```
As seen in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-5.0).

**You must login, before index page get rendered. (bug!)**
### Repository
The repository is on [GitHub](https://github.com/dumaisf/BlazorCrud-AllowAnonymous.git).
### Steps to reproduce the problem:

- Open the solution in Visual Studio
- Change the default connexion in BlazorCrud.Server/appsettings.json to point to your local SQL server.
- Build Solution
- In Package Manager Console, enter: update-database
- Start the execution
- You are forced to login (bug!)

### Further technical details
- ASP.NET Core version
  .NET SDKs installed: 5.0.100
  .NET runtimes installed: 5.0.0
- The IDE (Microsoft Visual Studio Community 2019 Preview
  Version 16.9.0 Preview 1.0)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The template automatically registers `BaseAddressAuthorizationMessageHandler` on the default HttpClient instance registered in DI. If you'd like to make anonymous calls, you'll need to register a separate HttpClient instance and use that instead.

**Comment by dumaisf** [comment]
Do you mean:
`builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });`

**Comment by dumaisf** [comment]
I used [Typed HttpClient](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-5.0#typed-httpclient) and it worked:

`builder.Services.AddHttpClient<HomeHttpClient>(client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));`
...
```
public class HomeHttpClient
    {
        private readonly HttpClient http;

        public HomeHttpClient(HttpClient http)
        {
            this.http = http;
        }

        public async Task<List<Rubrique>> GetRubriquesByRang()
        {
            return await http.GetFromJsonAsync<List<Rubrique>>("home");
        }
    }

```
`                Rubriques = await HomeClient.GetRubriquesByRang();
`
