### ISSUE TITLE
Relay PreventDefault with event parameters to be used inside the EventHandler at a certain point.

### ISSUE THREAD

**Issue by hmz777** [dotnet/aspnetcore#28119]
I have a Blazor wasm chat app where i want a `textarea` element to submit the `form` on pressing the `enter` key but prevent the default behaviour of the element which is appending a new line.

Now, using the `@onkeydown` and `@onkeyup` i was able to isolate this behaviour where now the `textarea` element submits the form on enter but also appends a new line with `shift`+`enter` and it's working fine.

Sample code:
```
<textarea rows="1" 
                                  @bind-value="@MessageModel.Message" 
                                  @bind-value:event="oninput" 
                                  @onkeydown="MessageOnDown" 
                                  @onkeyup="MessageOnUp" 
                                  id="MessageTextArea"
                                  placeholder="Type a message..."></textarea>
@code {
        readonly Dictionary<string, string> Keys = new Dictionary<string, string>();

        private async Task MessageOnDown(KeyboardEventArgs keyboardEventArgs)
        {
            Keys[keyboardEventArgs.Key] = keyboardEventArgs.Key;

            if (keyboardEventArgs.Key == "Enter" && Keys.Count == 1)
            {
                if (editContext.Validate())
                {
                    await ValidSubmit();
                }
            }
        }

        private void MessageOnUp(KeyboardEventArgs keyboardEventArgs)
        {
            Keys.Remove(keyboardEventArgs.Key);
        }

        private async Task ValidSubmit()
        {
            //Send message logic...
        }
}
```
But there is a small caveat where just before submitting the form (on pressing the enter key) a new line is appended.
Now, instead of using `@onkeydown:preventDefault` which blocks pressing any key in the textarea. 

My question is:
Can we have the option to call `PreventDefault` inside the EventHandler at a certain step during execution like we do in javascript? So for example we can call prevent default on a condition where a specific key is pressed like the `enter` key in my example. 

So the desired behaviour would be something like this:

```
private async Task MessageOnDown(KeyboardEventArgs keyboardEventArgs)
        {
            Keys[keyboardEventArgs.Key] = keyboardEventArgs.Key;

            if (keyboardEventArgs.Key == "Enter" && Keys.Count == 1)
            {
                keyboardEventArgs.PreventDefault();
                if (editContext.Validate())
                {
                    await ValidSubmit();
                }
            }
        }
```

To be honest i don't know if this is possible to achieve in Blazor so i completely understand if it's not.

The app is available here [Zen-Chat](https://github.com/hmz777/Zen-Chat).
And here is the component which the example code above is from [ChatSection.razor.cs](https://github.com/hmz777/Zen-Chat/blob/master/Client/Shared/ChatSection.razor.cs).

Thank you.

**Comment by mrpmorris** [comment]
At the moment you can't.  preventDefault is unconditional. This is because calls into Blazor are asynchronous, and DOM events can only be cancelled synchronously. 

To achieve this you'll need to hook into the event in JS and suppress it there,  followed by a call to tell your .NET code to submit the form.
