### ISSUE TITLE
[Future of Blazor] Deal with files : download, edit, upload

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#28110]
Hello guys, i mostly finish my rewrite of a Out Of Browser silverlight app to Blazor, and there is still a functionnality we can't reproduce : ability to download a file from our server (mostly word and excel file), let the user edit it by opening word/excel, and upload back the file to the server when the user close word/excel.

The silverlight was able to open directly executable on the client computer so it was quite of simple.

I know i can't do this in a web app, but i try to find a way to do this because i can't deliver the app without this.

- idea 1 : make this in pure web
We are ready to have something less convenient for our user than the silverlight app. for exemple a button for reupload the file manually. But we can't let the user select the file with an open file dialog. its a risk the user can't find the file he just open, or worse select the wrong file. I wondering if there is a way to keep a link to the file downloaded to automaticaly retrieve byte data of the file after edit. I look around the file system api but i don't really things like that. What do you think about it ?
- idea 2 : encapsulate the blazor app in a "kind" of native app. but something can be installed smoothly like PWA. Maybe you know womething on the roadmap of .NET 5/6 which can help me. 
- idea 3 : use a web word/excel editor, we arleady try solution like syncfusion but we are not satisfied of this concept. Our client used to use the classic app Microsoft office.

Im open for all your ideas because its something really important in apps and im really surprised there is nothing better i can do. I wonder how others webapp do this kind of thing ? (im sure we are not the first company which edit a webapp which need edit office document)

Thanks for your help !

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

> * idea 1 : make this in pure web
>   We are ready to have something less convenient for our user than the silverlight app. for exemple a button for reupload the file manually. But we can't let the user select the file with an open file dialog. its a risk the user can't find the file he just open, or worse select the wrong file. I wondering if there is a way to keep a link to the file downloaded to automaticaly retrieve byte data of the file after edit. I look around the file system api but i don't really things like that. What do you think about it ?

AFAIK there's no way to do what you are asking for within a web application. The browser doesn't have any link to downloaded files, so it can't pick up any edits/changes automatically.

> * idea 2 : encapsulate the blazor app in a "kind" of native app. but something can be installed smoothly like PWA. Maybe you know womething on the roadmap of .NET 5/6 which can help me.

There is nothing official for this in 5.0, you could try and wrap the webapp in an Electron shell as some folks have done. Three is a proposal for this in 6.0 but no concrete commitments yet.

> idea 3 : use a web word/excel editor, we arleady try solution like syncfusion but we are not satisfied of this concept. Our client used to use the classic app Microsoft office.

This would be your best bet I think in a web environment.

Also, please keep in mind that Blazor runs in a completely different environment than Silverlight and that it is a different technology that is not meant to be a "drop-in" replacement, meaning that if you are migrating or planning to migrate Silverlight apps, it is expected that you'll have to make changes into your app to adapt it to Blazor as well as probably implement or rely on a third-party package for some of the functionality available out of the box in Silverlight.

Hope this helps

**Comment by julienGrd** [comment]
@javiercn thanks for your response, i was expected something like that. do you have more precision about you plans for .NET 6.0 which can help us to achieve this functionnality ?

**Comment by javiercn** [comment]
Not at the moment
