### ISSUE TITLE
SignalR client not reconnecting/connecting properly when network change occurs

### ISSUE THREAD

**Issue by patil-vaibhav** [dotnet/aspnetcore#28111]
I have a simple Xamarin Android app which have a started hubservice with client code from  https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio

    [Service(Enabled = true)]
    public class HubService : Service
    {
        static readonly string TAG = typeof(HubService).Name;
        static readonly int TimerWait = 2000;
        Timer _timer;
        HubConnection hubConnection;

        string userName;
        TempDatabase _databaseRepo;

        public IBinder Binder { get; private set; }

        System.Diagnostics.Stopwatch watch;
        public override StartCommandResult OnStartCommand(Intent intent, StartCommandFlags flags, int startId)
        {

            return StartCommandResult.Sticky;
        }

        public override void OnCreate()
        {
            base.OnCreate();

            Log.Debug(TAG, "OnCreate called");

            Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;

            hubConnection = new HubConnectionBuilder()
                 .WithUrl("https://api.mysite.ml/chathub", options =>
                 {
                     options.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
                 })
                 .ConfigureLogging(logging =>
                 {
                     // Log to the Output Window
                     logging.AddDebug();
                     Console.WriteLine("HubConnectionBuilder");
                     // This will set ALL logging to Debug level
                     logging.SetMinimumLevel(LogLevel.Information);
                 })
                  .WithAutomaticReconnect()
                 .Build();
            StartHubConnectionAsync();

            hubConnection.Reconnected += HubConnection_Reconnected;

            hubConnection.Closed += HubConnection_Closed;

            hubConnection.On<string>("Send", (message) =>
            {

            });

            hubConnection.On<Message>("ReceiveMessage", (message) =>
            {

            });

            _timer = new Timer(o =>
            {
                Log.Debug(TAG, "Hello from simple Service. {0}", hubConnection.State.ToString());

            }, null, 0, TimerWait);
        }

        private async void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
        {
            if (e.NetworkAccess == NetworkAccess.Internet && hubConnection.State == HubConnectionState.Disconnected)
            {
                Console.Write("Internet connected. Start connection now");
                await StartHubReconnectinAsync();
            }
        }

        private async Task HubConnection_Closed(Exception arg)
        {
            await StartHubReconnectinAsync();
        }

        PendingIntent BuildIntentToShowMainActivity()
        {
            var notificationIntent = new Intent(this, typeof(MainActivity));
            notificationIntent.SetAction(Constants.ACTION_MAIN_ACTIVITY);
            notificationIntent.SetFlags(ActivityFlags.SingleTop | ActivityFlags.ClearTask);
            notificationIntent.PutExtra(Constants.SERVICE_STARTED_KEY, true);

            var pendingIntent = PendingIntent.GetActivity(this, 0, notificationIntent, PendingIntentFlags.UpdateCurrent);
            return pendingIntent;
        }

        public override IBinder OnBind(Intent intent)
        {

            Log.Debug(TAG, "OnBind");
            this.Binder = new HubBinder(this);
            return this.Binder;
        }

        public override bool OnUnbind(Intent intent)
        {

            Log.Debug(TAG, "OnUnbind");
            return base.OnUnbind(intent);
        }

        public override void OnDestroy()
        {

            Log.Debug(TAG, "Service OnDestroy");
            Binder = null;
            hubConnection.StopAsync();
            _timer.Dispose();

            base.OnDestroy();
        }

        private async Task HubConnection_Reconnected(string arg)
        {
            var rooms = await _databaseRepo.GetRoomsAsync();
            foreach (var item in rooms)
            {
                await JoinRoom(item.RoomId.ToString(), item.Name, userName);
            }
        }

        public async Task<bool> JoinRoom(string id, string roomName, string userName)
        {
            await hubConnection.SendAsync("AddToRoom", id, roomName, userName);
            return true;
        }

        public async void StartHubConnectionAsync()
        {
            if (hubConnection.State == HubConnectionState.Disconnected)
            {
                try
                {
                    Console.WriteLine("StartHubConnectionAsync");
                    await hubConnection.StartAsync().ContinueWith(async task =>
                    {
                        if (task.IsFaulted)
                        {
                            Console.WriteLine("Failed to start: {0}", task.Exception.GetBaseException());
                        }
                        else
                        {
                            
                            Console.WriteLine("Success! Connected with client connection id {0}",
                                              hubConnection.ConnectionId);

                            var rooms = await _databaseRepo.GetRoomsAsync();
                            foreach (var item in rooms)
                            {
                                await JoinRoom(item.RoomId.ToString(), item.Name, userName);
                                //Console.WriteLine("Connected :" + item.Name);
                            }
                        }
                    });

                }
                catch (System.Exception) { }
            }
        }

        public async Task StartHubReconnectinAsync()
        {
            if (hubConnection.State == HubConnectionState.Disconnected)
            {
                try
                {
                    Console.WriteLine("StartHubConnectionAsync");
                    await hubConnection.StartAsync().ContinueWith(async task =>
                    {
                        if (task.IsFaulted)
                        {
                            Console.WriteLine("Failed to start: {0}", task.Exception.GetBaseException());
                        }
                        else
                        {
                            Console.WriteLine("Success! Connected with client connection id {0}",
                                              hubConnection.ConnectionId);

                            var rooms = await _databaseRepo.GetRoomsAsync();
                            foreach (var item in rooms)
                            {
                                await JoinRoom(item.RoomId.ToString(), item.Name, userName);
                                //Console.WriteLine("Connected :" + item.Name);
                            }
                        }
                    });

                }
                catch (Exception) { }
            }
        }

        public async Task<bool> RemoveFromRoom(string id, string roomName, string userName)
        {
            await hubConnection.SendAsync("RemoveFromRoom", id, roomName, userName);
            return true;
        }
    }

it works great, until network changes or network drops and come back on

when this happens:

- when networks drops it give error : `Error: The server connection was terminated with an error. The remote party closed the WebSocket connection without completing the close handshake`
- hubconnection starts reconnecting  with : `Error: Failed to start connection. Error getting negotiation response from 'https://api.mysite.ml/chathub'.`
- after a while hubconnection disconnects with : `Reconnect retries have been exhausted after 5 failed attempts and 00:00:42.2725840 elapsed. Disconnecting.`
- now when network comes online, StartHubConnectionAsync gets called
- then it keeps saying connecting about 2-3 min then throws error : `Error: Failed to start connection. Error getting negotiation response from 'https://api.mysite.ml/chathub'.`

now the strange part is it give : `I/mono-stdout(26671): Success! Connected with client connection id ` without any connection id and connection stays diconnected after that until user restarts app.

please see attached logs below. Thanks. 

[logs.txt](https://github.com/dotnet/aspnetcore/files/5590191/logs.txt)

**Comment by BrennanConroy** [comment]
> Success! Connected with client connection id

The reason you're seeing this is because you're checking `task.IsFaulted` which will be false if the task is canceled (like in your case). Instead you can use `task.IsCompletedSuccessfully` or use `task.IsCanceled` with `task.IsFaulted`.

You shouldn't be calling `StartAsync` when the state is `Reconnecting` like you do in `StartHubReconnectinAsync`.
We also recommend you either remove the catch statements that are ignoring exceptions, or log the exceptions.

How sure are you that the network is actually back? Can you manually send an http request when the network comes online? `await new HttpClient().GetAsync("url");`

**Comment by patil-vaibhav** [comment]
Thanks for recommendation. After doing changes you recommended client is connecting properly after network change occurs.
