### ISSUE TITLE
Blazor InputFile should "remember" all files selected

### ISSUE THREAD

**Issue by havarsa** [dotnet/aspnetcore#28126]
The new InputFile component in .NET 5 is excellent, but I found a problem with it today; I am working on an application that will upload large files from a Blazor WebAssembly application to Azure Storage. Multiple files can be selected and added to a queue. From the InputFile changed event I receive IBrowserFile objects that I can use to establish a stream from the file to read (in chunks) and upload to Azure.

Now; the problem is that if the user selects files several times, they are added to the upload queue, but the previously selected files are "forgotten" by the InputFile component. So when I eventually invoke a file to set up a stream read to cloud operation, the file reference is no longer there in InputFile, and it is not able to establish the stream.

How about adding a unique Id to each IBrowserFile objects to use when referring back to JavaScript, instead of using the current list index? (I am assuming this is how it works now) And this allowing the component to keep reference of all files ever selected, until manually removed or flushed when application logic dictates it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The behavior you're looking for is not part of the current implementation of the InputFile component. You will have to come up with your own custom solution to store the files you have already selected.
We don't plan to change this behavior.
