### ISSUE TITLE
Add support for `@bind-Value="someInt"` in <InputSelect>

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#28128]
I'm not seeing where this is working in a 5.0 project.

> Closing as this was fixed as part of #23415.

_Originally posted by @MackinnonBuck in https://github.com/dotnet/aspnetcore/issues/18305#issuecomment-663658070_

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

We'll take a look at it and update the issue accordingly.

For future viewers, we don't seem to have an E2E test for this, we should just add one as a way to validate this works and fix it if it doesn't.

**Comment by mrlife** [comment]
Possible to commit to this for 6.0 since this was originally intended for 5.0?

**Comment by grigoresc** [comment]
Hello, I'm interested in working on this one.

I was thinking on adding an E2E. I would modify TypicalValidationComponent.razor.

**Comment by mrlife** [comment]
@grigoresc Thank you!

@javiercn This is technically a bug (instead of a feature request) due to https://github.com/dotnet/aspnetcore/issues/18305#issuecomment-663658070. Does that help it move up in priority?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This should be fixed already in .NET6.
