### ISSUE TITLE
Mvc.Testing: Create WebApplication from subdirectory of AppContext.BaseDirectory

### ISSUE THREAD

**Issue by ThorstenReichert** [dotnet/aspnetcore#28145]
I am trying to create unit tests for an ASP.NET Core app using the WebApplicationFactory. The twist is, that the web application is located in a subdirectory of the _\bin_ folder where the unit tests are compiled to, say _\bin\WebApp_.

Now, the WebApplicationFactory will check if the WebApp.deps.json file is present (which it is, in _\bin\WebApp_). However, it will look for this file not in the directory of the assembly containing the WebApp.Startup class, but instead in AppContext.BaseDirectory (see [EnsureDeps](https://github.com/dotnet/aspnetcore/blob/84b77de14c161803b36978bf498b8a6db8b95471/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L290)), which in my case is _\bin_. In summary:
- _\bin\WebApp\WebApp.deps.json_ does exist
- but WebApplicationFactory is looking for _\bin\WebApp.deps.json_

Maybe I am missing some workaround for the issue, but if not, it would be nice if WebApplicationFactory could start apps outside the AppContext.BaseDirectory folder.

**Comment by javiercn** [comment]
@ThorstenReichert thanks for contacting us.

Could you give us a minimal repro project that showcases this issue? (Ideally as a github repository we can clone).

**Comment by ThorstenReichert** [comment]
@javiercn here is a minimal  [repro project](https://github.com/ThorstenReichert/WebApplicationFactoryRepro) for this issue.

It consists of two solutions, one ASP NET Core WebApp and a unit test solution. To repro the issue, you can run
```
dotnet build .\WebApplicationFactoryRepro.WebApp
dotnet test .\WebApplicationFactoryRepro.Test
```

I recognize that this setup might look quite strange. In my use case, I have actually two gRPC services, that need to cooperate (and that is what I would like to test). Each service comes in via a nuget package, that extracts the service into a subfolder of $(OutputPath) (this is modelled here by having the WebApp solution build directly into _\bin\WebApp_ and the Test solution build into _\bin_).

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
