### ISSUE TITLE
Browser still using cached versions of application after re-deployment (Blazor WebAssembly app on Azure App Service)

### ISSUE THREAD

**Issue by ABIOLI-COM** [dotnet/aspnetcore#28146]
I've read the documentation about the SHA checking for assets, and anyway I didn't change anything on my generated project.
I always need to Ctrl-F5 to load the new version of the client application after deploying it to an Azure App Service.  
The documentation says that even if the SHA checks are on, the server can still decide to send different caching informations to the client. In my case, I didn't modify at all the default App Service that is created through 'normal' CLI calls, so I don't know if this behaviour is normal, or if there's some bug.  
Eventually, can anyone point me to how to configure the Azure App Service to let the SHA checking in the Blazor application to take control?  
Thanks in advance

**Comment by javiercn** [comment]
@ABIOLI-COM thanks for contacting us.

Thanks for contacting us. We are not sure about what assets you are talking about. Blazor will handle the caching for framework files and application dlls but it doesn't do anything about other assets in your wwwroot folder.

Is the problem you are having with the Blazor files or with you CSS/JS/HTML?

**Comment by ABIOLI-COM** [comment]
Probably I couldn't explain the case very well, sorry.
My problem is: I run a pipeline that destroys and recreate the app service, and then I deploy the new version of my test application (there is then no chance that there are old files).
When I browse the address, I see the old version of the application, so it's cached someway client side. I have to hit Ctrl-F5, to have the browser load the new version. I didn't change anything in the blazor.boot.json, I didn't change anything on the headers generation, and so on...

**Comment by chassq** [comment]
We re seeing a very similar, if not the same thing. We also fully replace our dlls on build/publish in our Azure Dev Ops CI/CD pipeline. However, when we hit the site the old behaviors and content still exist. We have see the blazor.boot.json file fail to fetch. Not sure that is at issue but thought I would mention it.

<img width="491" alt="Screenshot 2020-11-26 081040" src="https://user-images.githubusercontent.com/4785384/100355704-37b88d00-2fc0-11eb-9031-446ea114ce94.png">

We end up having to disable cache in the browser to get the new dlls to download.

**Comment by ABIOLI-COM** [comment]
On my side, I see that when browsing for the first time (hence downloading the client app), my Chrome browser tries three times to download blazor.boot.json, and only the first succeed (with the other two canceled each time): so maybe you have to look better in the list of the downloaded files (I always sort them alphabetically, to have a clear overview of the situation.  
![image](https://user-images.githubusercontent.com/63686917/100358075-e75c2200-2ff5-11eb-8662-11eba69647ce.png)
In theory the blazor.boot.json should be fundamental, for what I know, to have the system understand what has to be replaced locally in the browser cache.  
Maybe someone can help us to understand what happens when that file is not present at all.  
...I would like to find a more proper way, instead of disabling the cache...

**Comment by javiercn** [comment]
@chassq Please file a separate issue so that we can track it independently.

**Comment by javiercn** [comment]
@ABIOLI-COM thanks for the additional details.

It seems very strange, I would suggest you download `blazor.boot.json` using wget or something similar to ensure that the file has been updated.

Blazor will always avoid the cache when loading `blazor.boot.json` and any other framework files will fail to load if they don't match the integrity attribute described in `blazor.boot.json`.

I will suggest you check on the network tab the result from fetching `blazor.boot.json` and check whether the response was served from the cache or came back from the server, and in that case, compare the contents from the file on disk with the ones downloaded from the server.

**Comment by ABIOLI-COM** [comment]
Yes, they are different, but you can see that the blazor.boot.json had a result of 200, so it's downloaded from the server...  
![image](https://user-images.githubusercontent.com/63686917/100371810-a0c3f300-3008-11eb-8704-8abafbe80de3.png)
![image](https://user-images.githubusercontent.com/63686917/100371876-bc2efe00-3008-11eb-82fa-9aec6eff5b9a.png)
The funny thing is that if I use Visual Studio to browse the server files, and I download/open the remote blazor.boot.json, I see even different values:  
![image](https://user-images.githubusercontent.com/63686917/100372364-6b6bd500-3009-11eb-83ae-f914b9c75988.png)
I try to understand that locally it's build in debug, so it surely is different, but what is the difference when the file is browsed directly, or inside the normal browser loading???

**Comment by javiercn** [comment]
@ABIOLI-COM we think this is by design. Check [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#update-completion-after-user-navigation-away-from-app) for details

**Comment by ABIOLI-COM** [comment]
@javiercn Thanks for the link, I never checked that tab in the developer tools.  
Unfortunately each time I have slightly different results. To test what is said in the given document, I deployed a new version (the last was from yesterday).  
I didn't hit Ctrl-F5 yet, only browsing the page, and reloading with F5, so I'm seeing the old version (even after closing all the chrome browsers I have open on my machine.  
The page is loaded (apparently) correctly (in the old version), but with these errors in the console, that I never had previously:  
![image](https://user-images.githubusercontent.com/63686917/100460110-f1018a80-30c6-11eb-941a-db609234d699.png)
Moreover, the application tab shows this:  
![image](https://user-images.githubusercontent.com/63686917/100460247-2ad29100-30c7-11eb-8d86-6c328443830e.png)
The '32' in the number of errors is incrementing each time I reload (by 4 each time), but the errors on fetches apparently are much more, each time.  
It's true that I'm seeing myself that the service-worker is in yesterday version, and it's just my client application dll to be modified, but I still cannot imagine how to have the browser automatically load the new version...

**Comment by javiercn** [comment]
@ABIOLI-COM thanks for the additional details.

It seems that there are some integrity check issues. We would suggest you take a look at [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures) to diagnose what's going on.
