### ISSUE TITLE
Blazor Wasm - headManager.js - Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#28144]
### Describe the bug
We keep seeing the error **Uncaught SyntaxError: Unexpected token 'export'** for the headManager.js file (See attached screenshot).

<img width="897" alt="Screenshot 2020-11-25 051235" src="https://user-images.githubusercontent.com/4785384/100213941-42e6bc80-2edd-11eb-997f-fed7d6d4a70e.png">

Want to know if anyone else has seen this and if so is there a configuration we are missing?

### To Reproduce
This happened since we implemented the Title component for managing Page Title for our SEO. We have turned off UBlock Origin for our sites and have no other extensions enabled in the browser (Edge Version 87.0.664.41 (Official build) (64-bit)). We see this locally and when we deploy.

### Exceptions (if any)
See above.

### Further technical details
Using Edge: Version 87.0.664.41 (Official build) (64-bit)

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.9.0 Preview 1.0
VisualStudio.16.Preview/16.9.0-pre.1.0+30709.64
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA196
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.128.44438
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2055207+87b6851d6bf3db12f59d3bd272dd0e635d31b20a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.128.44438
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.128.44438
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.128.44438
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.9.0-1.20521.14+182c1e333b8514ac17dc463aac26b5552977a040
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu. 

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GhostDoc   20.2.20270.0
Generate XML Comments from your code, maintain clean and up-to-date documentation, produce help documentation in multiple formats, use intelligent source code Spell Checker in Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21028.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-1.20521.14+182c1e333b8514ac17dc463aac26b5552977a040
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

**Comment by javiercn** [comment]
@chassq thanks for contacting us.

This is not a feature we currently support.

While we offered a preview of this feature, we ended up not shipping it in 5.0, so we recommend you avoid using it alltogether

**Comment by chassq** [comment]
@javiercn Thanks but just to ask. Does this mean we have to wait until .NET 6 to be able to update the page Titles and Meta data for SEO?

**Comment by javiercn** [comment]
@chassq No.

It means that we don't provide a solution out of the box for it, but you are not blocked from implementing your own solution to achieve this.

As to when/if we will provide a solution for this, we don't have concrete plans yet.

**Comment by chassq** [comment]
@javiercn Ok thanks. Would you happen to have any samples of doing this successfully via javascript or any guidance?

**Comment by javiercn** [comment]
You can check out the source for the component we were building [here](https://github.com/aspnet/AspLabs/tree/master/src/Components.Web.Extensions)

**Comment by chassq** [comment]
@javiercn Thank you!

**Comment by benm-eras** [comment]
@javiercn are you saying that [this ](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-8/comment-page-2/#influencing-the-html-head-in-blazor-apps) blog post is no longer correct?

**Comment by javiercn** [comment]
@benm-eras yes.

We ended up not shipping that feature.

@danroth27 we should update the referenced blog post.

**Comment by benm-eras** [comment]
@javiercn thanks for the confirmation. I will look forward to this being released in the future

**Comment by vindberg** [comment]
For anyone using this you only need to add this type="module" to the script src tag for that error to disappear.

Hoping for a permanent solution ASAP! Thanks.
