### ISSUE TITLE
Remove nameof use from LoggerMessage.Define calls

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#28159]
https://github.com/dotnet/aspnetcore/blob/3a942ff5c5892fed126ab3c69406546f8e2287a0/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs#L15

These names are considered public API and should not be changed even if the thing they're named after changes. As such we don't want to use nameof because the tools would automatically rename them.

Compare to:
https://github.com/dotnet/aspnetcore/blob/49c01eefecf1dbd75e5536aa803d689390c6770a/src/SignalR/clients/csharp/Client.Core/src/HubConnection.Log.cs#L16

**Comment by adrianwright109** [comment]
I can take this issue, if you're ok with that?

**Comment by adrianwright109** [comment]
I have submitted a PR which removes the use of `nameof` from LoggerMessage.Define calls.
