### ISSUE TITLE
.NET 5 Blazor WebAssembly SPA Microsoft login error

### ISSUE THREAD

**Issue by FrancisEgan** [dotnet/aspnetcore#28150]
### Describe the bug
When logging in, it seems to be successful, and then comes back to a page hanging at "Completing login..." with the following in the console:
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
```

### To Reproduce
Following this setup guide step-for-step with a brand new app produces the issue.

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-5.0

### Exceptions (if any)
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
```
### Further technical details
- .NET 5
- dotnet --info output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- IDE: vscode latest

**Comment by javiercn** [comment]
@FrankEgan thanks for contacting us.

Could you produce a minimal repro project with detailed steps on how to reproduce the issue? (Ideally as a github repository).

**Comment by FrankEgan** [comment]
@javiercn https://github.com/FrankEgan/aspnetcore-msal-error

Just dotnet watch run the project and try to sign in

**Comment by rjarratt** [comment]
I have this problem when the Identity Provider returns an error. Specifically I have a B2C custom policy. When this policy returns an error (as a result of REST call in the custom policy returning a 409), the Blazor app hangs in "Completing login...." and there does not seem to be a way to get at the error message and display it. Specifically, when the client posts to the authresp endpoint, it gets a redirect to 

https://<mysite>/authentication/login-callback#error=server_error&error_description=AADB2C%3a+You+need+an+invitation+to+this+system.

Along with more data like correlation id etc. The app hangs on this redirect.

I have built my app on .NET 5 and it is based on the template project. It works fine for a valid login, although I think there might be a separate problem with refreshing the token and failing to do so.

**Comment by marpinello** [comment]
I´m having this same issue with my migrated project (3.1 to 5.0)
This is really disturbing, and doesn´t seem MS popes are going to fix it at a fast pace.
Wondering right now to roll back just because of it.

**Comment by FrancisEgan** [comment]
The doc says to use `--tenant-id "common"` when setting up. In our case, we have a tenant id because we are using org logins. Using our tenant id instead made logins from org work. I'm assuming common means general, non-org accounts.

@marpinello Are you using organization accounts? If so, could you try using your tenant id from your AAD app and see if it works, to confirm?

**Comment by PerseusTheGreat** [comment]
In my case (Blazor WASM on .NET 5.0.3) , every things is OK on localhost.
But, after publishing on remote share hosting (Win Server 2019 + .NET 5.0.3) this situation will be happened.
Every idea/solution/hack/..., will be appreciated.

**Comment by hanslai** [comment]
In my case, I believe Azure AD was assuming implicit grant, but I didn't have implicit grant set in my Azure Portal.
I added "ResponseType": "code", to specific the client is using Authorization Code Flow with PKCE solved problem.

**Comment by mkArtakMSFT** [comment]
Looks like there are some successful experiences shared here and it's not clear if the issue is still relevant.
@FrancisEgan can you please try this out again with the latest .NET 7 RC SDK and see if this is still an issue? Thanks!

**Comment by FrancisEgan** [comment]
@mkArtakMSFT resolved as per my previous comment, however the linked wiki page in my original post still doesn't mention that you should use your tenant ID instead of "common" if you have one. If you want, I can make an edit to the wiki page and PR it.

**Comment by javiercn** [comment]
@FrancisEgan the guide might be a bit misleading. `common` is a tenant too. It is the `shared` tenant for Microsoft Accounts. If you have your own AAD, then you need to use your tenant as you already mentioned. The guide there is for `Microsoft Accounts` explicitly.

**Comment by javiercn** [comment]
> If you want, I can make an edit to the wiki page and PR it.

I think we already have a dedicated path for standalone docs with AAD [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-5.0)
