### ISSUE TITLE
Extra Nonce and Correlation cookie created on each logout/login 

### ISSUE THREAD

**Issue by TestO2015** [dotnet/aspnetcore#28168]
I have a login and logout APIs which connect to ```Oracle IDCS``` via OpenId Connect. Every time I logout and login again, a new set of Nonce and Correlation cookies are created and they're visible in the ```/signin-oidc``` request. Eventually they overflow the request header.

        [AllowAnonymous]
        [HttpGet("Login")]
        public IActionResult Login()
        {
            return Challenge(new AuthenticationProperties
            {
                RedirectUri = returnUrl
            }, OpenIdConnectDefaults.AuthenticationScheme);
        }

        [HttpGet("Logout")]
        public IActionResult Logout()
        {
            return SignOut(new AuthenticationProperties
            {
                RedirectUri = returnUrl
            }, OpenIdConnectDefaults.AuthenticationScheme);
        }

Observations:
- While the count increases with each new login, all cookie values change - so I take it the old set is replaced and two new sets are added.
- The extra set only gets created when logging out before calling login again.
- ```I tested this on Azure AD and it works - only one cookie set is created.```

What is different for IDCS? Is there anyway of deleting the cookies manually?

**Comment by Tratcher** [comment]
It sounds like challenge is being called more then once on an unauthenticated request.

Where do those returnUrl parameters point?

You'll want to connect debug server logs and a Fiddler trace file showing the repro.

**Comment by TestO2015** [comment]
@Tratcher The returnUrl is variable but it happens regardless of where it points.

> It sounds like challenge is being called more then once on an unauthenticated request.

Wow it is, somehow the Login API gets called after executing the Logout API in IDCS (not Azure AD). I'm not sure how.
