### ISSUE TITLE
Blazor WebAssembly PWA is not working when hosting in Azure Storage static website

### ISSUE THREAD

**Issue by heavenwing** [dotnet/aspnetcore#28167]
### Describe the bug
Hosting Blazor WebAssembly app with enabling PWA in Azure Storage static website, browser don't display PWA install tip.
But if host in Azure Storage container is working.

### To Reproduce
1. Create Blazor WebAssembly app in VS2019 , enable PWA
1. Publish this app
1. Create an Azure Storage (for example name is "staticweb"), create a container (for example "mywasm"), modify published index.html, change `<base href="/" />` to `<base href="/mywasm/" />`
1. Upload published contents into this container
1. Access index.html (for example "https://staticweb.blob.core.windows.net/mywasm/index.html"), you can see PWA install tip
1. If you create an ARM account with static website, don't modify base path, upload published contents into $web container, access "https://myblazor.z7.web.core.windows.net/", you also cannot see PWA install tip

### Exceptions (if any)
N/A

### Further technical details
- ASP.NET Core version 5.0
- VS2019 16.8.2

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@heavenwing thanks for contacting us.

You seem to be modifying the contents of the app after publishing and that is causing an integrity failure on the browser. You should modify your base path before you publish your app. https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures

**Comment by heavenwing** [comment]
@javiercn I am sorry about confusing you

My original description is "If you create an ARM account with static website, don't modify base path, upload published contents into $web container, access "https://myblazor.z7.web.core.windows.net/", you also cannot see PWA install tip"

My meaning is Blazor deploy into Azure Storage static website without modifying anything content, it cannot display PWA install tip. 
If I change base path, and deploy into Azure Storage normal container, I can get PWA install tip.
