### ISSUE TITLE
Add Areas to SearchedLocation in RazorViewEngine

### ISSUE THREAD

**Issue by daping123** [dotnet/aspnetcore#28169]
### Is your feature request related to a problem? Please describe.
Asp.net core has a IRazorViewEngine interface which could render a razor view/pages.I want to search for a page which is in an area but it could only search for **Views/xxx.cshtml**,**Views/shared/xxx.cshtml** and **Pages/shared/xxx.cshtml**.

### Describe the solution you'd like
I want this interface to search for area like **Areas/{AreaName}/Pages/{Pagefolder}/{Pagename}.cshtml** and so on.Is there any other missing which it could set in asp.net core?

### The result I get:
![Capture](https://user-images.githubusercontent.com/44570676/100315389-892e3f80-2ff3-11eb-9992-cb7d86fb177b.PNG)

### Code which could reproduce the issue：
```
    public class HomeController : Controller
    {
        private readonly IRazorViewEngine _razorViewEngine;
        private readonly IServiceProvider _serviceProvider;
        public HomeController(IRazorViewEngine razorViewEngine, IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
            _razorViewEngine = razorViewEngine;
        }
        public IActionResult Index()
        {
            var viewName = "Emails/TestPage";
            var httpContext = new DefaultHttpContext { RequestServices = _serviceProvider };
            var actionContext = new ActionContext(httpContext, new RouteData(), new ActionDescriptor());
            var viewResult = _razorViewEngine.FindPage(actionContext, viewName);
            return View();
        }
    }
```

**Comment by javiercn** [comment]
@daping123 thanks for contacting us.

@pranavkm do you have any thoughts?

**Comment by pranavkm** [comment]
There's a https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorviewengineoptions.areaviewlocationformats?view=aspnetcore-5.0 that gets used if your `RouteData` includes an `area` token.

**Comment by daping123** [comment]
> There's a https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.razorviewengineoptions.areaviewlocationformats?view=aspnetcore-5.0 that gets used if your `RouteData` includes an `area` token.

I know I could get the area location from this property by the following blog.But how to apply to it in my scenario?

https://khalidabuhakmeh.com/searched-locations-razor-view-engine-aspdotnet
