### ISSUE TITLE
LinkGenerator should serialize enums according to NamingPolicy

### ISSUE THREAD

**Issue by IhnatKlimchuk** [dotnet/aspnetcore#28178]
I've faced with an issue that `LinkGenerator` serializes enum with PascalCase, while I use `JsonNamingPolicy.CamelCase` in the project for Json. That can become a real issue for snake_case or kebab-case.

### Is your feature request related to a problem? Please describe.
`LinkGenerator` do not respect enums during serialization as `JsonSerializer` do:
```
.AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.IgnoreNullValues = true;
                    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
                })
```

### Describe the solution you'd like
```
.AddLinkGeneratorOptions(options =>
                {
                    options.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
                })
```

**Comment by javiercn** [comment]
@IhnatKlimchuk thanks for contacting us.

This is not a feature we have in the box, but it's something you can trivially add to your app.

https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Mvc/samples/MvcSandbox/Startup.cs#L24-L27

https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Mvc/samples/MvcSandbox/SlugifyParameterTransformer.cs

and then use it with `{param:slugify}`
