### ISSUE TITLE
DateimOffset looses Time part if Date is of Minvalue

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#28186]
I am storing Open and Close time of the store(don't Need Date Part) into DateTimeOffset field.
When returning data from Server(asp.net Core .net5) i loose the Time part only if the date value is minValue.

```
For Such Date
dtEnd: "0001-01-01T09:00:00-06:00"
dtStart: "0001-01-01T17:30:00-600:00"

Returns 

dtEnd: "0001-01-01T00:00:00+00:00"
dtStart: "0001-01-01T00:00:00+00:00"

but if i use
dtStart: "2020-11-26T10:00:00-06:00"
dtEnd: "2020-11-26T18:35:00-06:00"

the return values are correct
dtStart: "2020-11-26T10:00:00-06:00"
dtEnd: "2020-11-26T18:35:00-06:00"

```

why does it returns incorrect value when date is MinValue ?

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

Unfortunately we don't have enough information to give you an answer. Could you provide a minimal repro project with detailed steps on how to reproduce the issue? (Ideally as a github repository)
