### ISSUE TITLE
Blazor - Still seeing cached dlls after redeploy via Azure Dev Ops CI/CD Pipeline

### ISSUE THREAD

**Issue by chassq** [dotnet/aspnetcore#28183]
Adding per @javiercn request.

We are seeing a very similar issue, if not the same thing. We also fully replace our dlls on build/publish in our Azure Dev Ops CI/CD pipeline. However, when we hit the site the old behaviors and content still exist. We have seen the blazor.boot.json file fail to fetch. Not sure that is at issue but thought I would mention it.

<img width="491" alt="Screenshot 2020-11-26 081040" src="https://user-images.githubusercontent.com/4785384/100355704-37b88d00-2fc0-11eb-9031-446ea114ce94.png">

We end up having to disable cache in the browser to get the new dlls to download. We don't see (or don't know where to look for) the blazor.boot.json file in our deployment yet. Still looking or maybe its a framework thing?

_Originally posted by @chassq in https://github.com/dotnet/aspnetcore/issues/28146#issuecomment-734295064_

**Comment by chassq** [comment]
A little more info. We started with the web site up and all content up-to-date. Then we closed the browser (MS Edge latest version) and made sure all browsers were closed. In VS 2019 we made a content change to a blazor component (just added some text in the html and synced to our origin branch (this kicks off an azure dev ops pipeline). The deploy completed successfully and we opened the browser and hit the site. The new content did not show so we opened the tools (F12) and looked at the network. See the snapshot below. 

<img width="1066" alt="Screenshot 2020-11-26 110606" src="https://user-images.githubusercontent.com/4785384/100372561-68f08780-2fd7-11eb-8123-05c57bf319f2.png">

Looks like the blazor.boot.json got a fetch status of 200 but from the service worker (we do have a PWA). Then the service worker returned a 304. Then the next fetch for the file was cancelled.

**Comment by ABIOLI-COM** [comment]
??? Why a new issue? I thought it was the same exact issue that I filed in #28146... :-)

**Comment by chassq** [comment]
@ABIOLI-COM yeah I thought so too but @javiercn asked be to setup a separate issue. See #28146... :-)

**Comment by ABIOLI-COM** [comment]
:-) I was not commenting on you, but on him! :-)

**Comment by javiercn** [comment]
@ABIOLI-COM It's confusing for us when we have crossed streams of data in the same issue, if they turn out to be the same issue, we will dupe it later, it makes our lives much easier.

**Comment by javiercn** [comment]
@chassq have you checked https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#update-completion-after-user-navigation-away-from-app

**Comment by ABIOLI-COM** [comment]
Really sorry: I was just joking, surely I didn't want to offend anyone.
Thank you for your support, I will check the link, and try to understand better.

**Comment by chassq** [comment]
@javiercn Ok thanks for that!
