### ISSUE TITLE
Blazor (WASM) AAD authentication fails: getAccessToken returns undefined

### ISSUE THREAD

**Issue by wasabii** [dotnet/aspnetcore#28185]
Upgrading to .NET 5 and my Azure AD authentication has broken. The bug ultimately exists inside AuthenticationService.ts.

```
Unhandled exception rendering component:  An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult. Path: $ | LineNumber: 0 | BytePositionInLine: 4.. See InnerException for more details. 
 Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult. Path: $ | LineNumber: 0 | BytePositionInLine: 4.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.InternalAccessTokenResult. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
```

Last meaningful line is the RemoteAuthenticationService. So, it's trying to parse some JSON returned from an InvokeJS call.

Specifically, what it's trying to do is invoke `AuthenticationService.getAccessToken` (line 149 in `RemoteAuthenticationService`).

However, this code is returning `{ status: 'success', r: undefined }`. Undefined is not valid JSON, hence it's serializing to something, and breaking.

So why is it doing this? Beacuse `getTokenCore` tries to call `getAccount` and returns null if it is unset. And it is unset: because nobody has logged in yet! `getAccessToken` then continues on, blissfully unaware, because it only returns 'requiredRedirect' if there's an exception.

So: the AAD authentication is broken if it's attempted to be used before anybody has logged on. This breaks the Blazor WASM AAD tutorial example of using `AuthorizationMessageHandler` to trap missing authentication and redirect. It means you must authenticate up front, manually, instead of allowing authentication requests to flow naturally only when authentication is required.

**Comment by javiercn** [comment]
@wasabii thanks for contacting us.

Could you share more details about your environment?
Can you make sure that the AuthenticationService.js is not being incorrectly cached and it's using the 3.1 version?
Did you update your application registration in the portal to use the new SPA platform instead of Web?

**Comment by eskaufel** [comment]
@javiercn I made a repo reproducing what @wasabii said, but this is with B2c

https://github.com/eskaufel/BlazorB2cAuth
It is precisely following the tutorial (unless i made a typo)

Program.cs
```csharp
            builder.Services.AddHttpClient(ClientName, client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
            
            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient(ClientName));

            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAdB2C", options.ProviderOptions.Authentication);
                options.ProviderOptions.DefaultAccessTokenScopes.Add("openid");
                options.ProviderOptions.DefaultAccessTokenScopes.Add("API.Access");
                options.ProviderOptions.LoginMode = "redirect";
            });
```

Index.razor
```csharp
    protected async override Task OnInitializedAsync()
    {
        try
        {
            var response = await client.GetAsync("something");
        }
        catch (AccessTokenNotAvailableException)
        {
            message = "this is expected";
        }
        catch (NullReferenceException)
        {
            message = $"this is what happens";
        }
        await base.OnInitializedAsync();
    }
```

Either I have done something stupid, or this is a severe bug.
I reckon a workaround is to catch NullReferenceException
