### ISSUE TITLE
[IE11 Support] On Blazor.server.js, revert from named capture group RegExp to an ES5 compatible format

### ISSUE THREAD

**Issue by Daddoon** [dotnet/aspnetcore#28187]
## Summary

This is in continuation of https://github.com/Daddoon/Blazor.Polyfill/issues/33

What is asked here is to revert from named capture group regexp in the Blazor.server.js library, to a ES5 compatible RegExp that would be able to be evaluated or converted for Internet Explorer 11.

## Motivation and goals

Blazor.Polyfill does not work out of the box with Blazor in .NET 5.
After investigation, two things need to be done in order to make it work for IE11:

- Some transpilation with Babel on the Blazor.server.js file for the IE11 preset in order to change incompatible keyword declaration like **import()**. 

This is not blocking as this can be done eventually afterward by a Nuget package or some other configuration behavior.

- Replace named capture group Regexp by something understandable for IE11. This cannot be done by Polyfills or didn't have found one that cover this. Babel does cover this problem but the minimum requirement is to have ES6 support, and IE11 lack this (See https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex) . This **is blocking**

This minor change would make IE11 support more easy and straightforward, and so, maintaining Blazor support on this old browser.

## Examples

In Blazor.server.js theses content:

```js
var o = /\W*Blazor:[^{]*(?<descriptor>.*)$/;
```
```js
var r = new RegExp(o).exec(n.textContent),
i = r && r.groups && r.groups.descriptor;
```

Would be this instead (taken from what is partially working with Babel after transpilation):

```js
var o = /[\0-\/:-@\[-\^`\{-\uFFFF]*Blazor:(?:(?!\{)[\s\S])*(.*)$/;
```
```js
var r = new RegExp(o).exec(n.textContent),
i = r && r[1];
```
## Final note

If any change in this direction cannot be taken in future update, it's of course possible to do some hack and change Regexp code and behavior by analyzing and changing **blazor.server.js** dynamically, but it would be cumbersome as it would be RegExp specific at each possible update of the Polyfill / Blazor.server.js code, and also i imagine it would be not easy to find the correct code to fix as the code will likely be minified when having to deal with the original Blazor.server.js file.

Also, i didn't know here, if this question was more about a **Bug** or a **Design Proposal**, as it sound like in between for me, sorry if this is miss labeled.

**Comment by javiercn** [comment]
@Daddoon thanks for contacting us.

Design proposals are meant to tackle new features to add to the framework, I would consider this a regular issue. Blazor 5.0 doesn't support IE11 and we don't plan to make changes to enable it, since we don't want to risk breaking other customers.

The recommendation is to patch blazor.server.js manually if your **really, really** want to make this work, or to keep relying on Blazor 3.1 which doesn't present this issues and is LTS. Keep in mind that the first scenario is not something we would officially support.

**Comment by Daddoon** [comment]
Understood, thanks for the reply @javiercn  !

Following this recommendation, i will try to keep two possibles "kind of" branch on the Blazor.Polyfill project, mentioning that .NET 5 support for IE11 is experimental as Microsoft doesn't plan to support it.
