### ISSUE TITLE
Generic Type parameter of ActionResult doesn't enforce strict type.

### ISSUE THREAD

**Issue by sshanzel** [dotnet/aspnetcore#28198]
### Describe the bug
When you set a Type on the Generic Parameter of ActionResult and return any type other than that - it would still proceed.
I mean, should this be expected? or not? or am I implementing web APIs incorrectly?

### To Reproduce

1. `dotnet new webapi`
2. Create a controller with a method that ActionResult is used with a generic parameter and return a different type.
```
class Sample {}

[HttpGet("{id}")]
public ActionResult<Sample> GetCourt(int id)
{
    return Ok(1);
}
```

### Further technical details
- ASP.NET Core version - **5.0** but this actually happens on different versions
- Include the output of `dotnet --info` - down below
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - VS19

dotnet info:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@javiercn thanks for contacting us.

I believe the that ActionResult<T> is only used for the purposes of being able to express the return type on the method signature.

Other action results convert implicitly to `ActionResult<T>` so I believe the behavior is by design and we don't intend to enforce it, since we want to be able to let you return alternative object types in some cases, like when there is an error.

/cc: @pranavkm  can confirm.

**Comment by sshanzel** [comment]
hi @javiercn, thank you for the awesome answer!

Interesting, I just feel though, that the appropriate response code and status would signify the actual error message. Now that you mentioned it, I realized I also return back error messages based on the `ModelState` not having the shape of the generic type itself.

How about, be type-strict when it comes to returning error codes of `2xx`? 😁

**Comment by davidfowl** [comment]
We should try out best to improve the analyzer to fix this. If we can catch simple enough cases

**Comment by sshanzel** [comment]
> We should try out best to improve the analyzer to fix this. If we can catch simple enough cases

That would be awesome. If there is any way I can contribute to this, I am up for any challenge!
