### ISSUE TITLE
Build from Source Steps - Add forking steps

### ISSUE THREAD

**Issue by adrianwright109** [dotnet/aspnetcore#28192]
I'm wondering whether the **Build ASP.NET Core from Source** steps located here:

https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md#build-aspnet-core-from-source

should include information about forking the repo, so that users can if they wish, submit future pull requests to the AspNetCore repo?

For example, if I wanted to clone the AspNetCore repo I could clone the repo as described in **Step 1**.  But I wouldn't be able to create branches or submit a pull request directly as I wouldn't have the correct write permissions to the AspNetCore repo.

I would instead need to fork the AspNetCore repo, clone that forked repo down locally, make the changes locally, push the changes to the forked repo and then submit a pull request for that to be considered for merging into the AspNetCore repo.

**Comment by dougbu** [comment]
@captainsafia turning this one over to you. Please either close or add to the DoI board.

**Comment by wtgodbe** [comment]
Putting this in backlog - we'd be happy to take a PR for this if you'd like to submit one @adrianwright109

**Comment by jacobslusser** [comment]
I haven't seen any updates on this, so I'm going to volunteer. I have the changes ready and can submit a PR if you agree.

CC: @adrianwright109

**Comment by captainsafia** [comment]
@jacobslusser Yes, please. Looking forward to the PR.

**Comment by huunab** [comment]
@captainsafia should we close this?

**Comment by jacobslusser** [comment]
Yes. This was completed with the merge.
