### ISSUE TITLE
Blazor - Designing API for complex component with nested properties

### ISSUE THREAD

**Issue by Xarlot** [dotnet/aspnetcore#28197]
I`m investigating how to design a complex component API with nested properties

Let's imagine we are creating a grid component with columns. We have a set of predefined columns, other columns are autogenerated based on source structure. Also, I have bindings to the properties of nested components.

```
<GridComponent ItemsSource="@Source" AutoGenerateColumns="AddNew">
    <Columns>
        <GridColumn Member="Test" SortMode="@SortMode" />
        <GridColumn Member="Test2" DataType="@DataType"/>
    </Columns>
</GridComponent>
```

I need to compose inner components with root component properties to obtain markup for prerendering. So I need to obtain the whole component structure before render. How to do it?

Other platforms I`m familiar with like Winforms or WPF have a System.Component.Model.ISupportInitialize concept for transactional component initialing however I can't find analogs in Blazor.

What is the recommended way to design such API?

**Comment by javiercn** [comment]
Thanks for contacting us @Xarlot.

It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow using the asp.net-core-blazor tag.
