### ISSUE TITLE
HTTP Range not working (using Kestrel)

### ISSUE THREAD

**Issue by Fabi** [dotnet/aspnetcore#28209]
### Describe the bug
HTTP Ranges are not working on Web API projects using Kestrel even though the headers are sent by the client and received by the server. The server always answers with status code OK (200) and the full content stream instead of Partial Content (206) and the partial content.

### To Reproduce
1. Create a .NET 5 Web Api Project.
2. Add a controller that should return partial content.
3. Connect using a HttpClient for example from another C# client with a Range header defined.

That's basically a very simple controller where it should already work:

```csharp
        [HttpPost]
        [Route("download")]
        public async Task<IActionResult> Download()
        {
            return File(fileStream, "application/octet-stream", true);
        }
```

### Expected
The server should answer with Partial Content (206) and the correct content and length defined by the ranges.

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by davidfowl** [comment]
Can you make a project that reproduces the problem? Both client and server or a server with specific instructions on how you are sending requests or even better a raw request that we can replay.

**Comment by Fabi** [comment]
> Can you make a project that reproduces the problem? Both client and server or a server with specific instructions on how you are sending requests or even better a raw request that we can replay.

I created a repo for the test project. It contains a very basic web api project and a client to request the data.

https://github.com/Fabi/WebApiRangeTest

**Comment by Tratcher** [comment]
Only GET/HEAD are supported, not POST.
https://github.com/dotnet/aspnetcore/blob/27610b0901535ce4b71832d7f3adf708f0c689c7/src/Mvc/Mvc.Core/src/Infrastructure/FileResultExecutorBase.cs#L125
