### ISSUE TITLE
Need to preserve commits that ship in VS

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/aspnetcore#28216]
There's a process issue where git commits of the aspnetcore-tooling repo that get inserted into a shipping VS release end up not being present in any branch on the server.

Example: if you look at the assembly attributes of this .dll in VS 16.8.2:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\RazorLanguageServices\Microsoft.CodeAnalysis.Razor.Workspaces.dll
you'll see [assembly: AssemblyInformationalVersion("6.0.0-alpha.1.20528.3+84e121f1403378489b842e1797df2f3f5a49ac3c")]

which means that this .dll was built from this commit:
https://github.com/dotnet/aspnetcore-tooling/tree/84e121f1403378489b842e1797df2f3f5a49ac3c

However there isn't a branch or a tag that points to this commit, so if git gc is ran on the server we lose the change. My hypothesis is that there is a rebase or cherry-pick or some other history rewrite that happens as part of the release, but the bits that end up getting inserted are built from the temporary commit that gets rewritten later.

This is not the first time this happened, we had the same situation with 16.7.3. I think it's important for build reproducibility, servicing, investigations etc. to preserve the exact git commit that gets inserted, even if it gets rewritten later. Perhaps the CI should create a tag on the commit?

**Comment by KirillOsenkov** [comment]
Same issue with https://github.com/dotnet/aspnetcore/tree/c5302e8ed164a260c53ac0a4e83d5d98cfc3f608, an orphaned commit

**Comment by NTaylorMullen** [comment]
I did a boo boo. This was totally on me cowboying that release 😉. I'm sorry @KirillOsenkov don't hate me too long. Shouldn't happen again.

**Comment by KirillOsenkov** [comment]
lol no worries at all, as long there isn't an underlying tooling issue 

I'm just happy I've learned how to recover orphaned commits all by myself!
