### ISSUE TITLE
IApplicationBuilder.UseWebAssemblyDebugging does not host at the correct location.

### ISSUE THREAD

**Issue by kotx** [dotnet/aspnetcore#28215]
### Describe the bug
When pressing Alt+Shift+D on a Blazor app hosted on ASP.NET Core with WASM debugging enabled, I get sent to https://localhost:5001/app/_framework/... but it 404s. The debug page is available at https://localhost:5001/_framework/... 

Most likely this is caused by #27776 

### To Reproduce

* Repro project: https://github.com/kotx/WASMDebuggingRepro

**Manual reproduction steps:**
- Create a ASP.NET Core hosted Blazor WASM app
- Use `app.UseWebAssemblyDebugging();` in **Startup.Configure**
- Add `<base href="/app/" />` to the index.html of the Blazor client app
- Add `<StaticWebAssetBasePath>app</StaticWebAssetBasePath>` to the Client .csproj
- Add this to **Startup.Configure**: `app.UseBlazorFrameworkFiles("/app");`
- In `app.UseEndpoints(endpoints => {...}` in **Startup.Configure**, add `endpoints.MapFallbackToPage("/app/{*path:nonfile}", "index.html");`
- Navigate to https://localhost:5001/app/index.html
- Press Alt+Shift+D
- Notice how the page is not found
- Remove `/app` from the debug url
- Notice that the url is correct

### Further technical details
- ASP.NET Core 5.0.0
- `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20262
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Visual Studio Community 2019 16.9.0 Preview 1.0

### Notes
Possibly related to #27776. If it is, then this should be fixed in the next patch release.

**Comment by javiercn** [comment]
@kotx thanks for contacting us.

As you point out, this is likely caused by #27776 but just to clarify, if you are mapping the app outside of the root folder, you likely need to call `app.Map("subfolder", sub => sub.UseWebassemblyDebugging())` to make sure that it is correctly configured

**Comment by kotx** [comment]
> 
> 
> @kotx thanks for contacting us.
> 
> As you point out, this is likely caused by #27776 but just to clarify, if you are mapping the app outside of the root folder, you likely need to call `app.Map("subfolder", sub => sub.UseWebassemblyDebugging())` to make sure that it is correctly configured

Thanks, that worked. app.UseBlazorFrameworkFiles() accepts a path argument, is there a reason UseWebAssemblyDebugging() doesn't?

**Comment by javiercn** [comment]
@kotx it's likely a gap in the implementation.

We would welcome a PR if you want to add it.

**Comment by kotx** [comment]
@javiercn Sorry, not much experience with this codebase... I might look into it in the future. Anyway, thanks for the help!
