### ISSUE TITLE
TimeZoneInfo.FindSystemTimeZoneById("Samoa Standard Time") should be {(UTC -11:00) Samoa} instead of {(UTC+13:00) Samoa}

### ISSUE THREAD

**Issue by melleck** [dotnet/aspnetcore#28211]
TimeZoneInfo.FindSystemTimeZoneById("Samoa Standard Time") should be {(UTC -11:00) Samoa} instead of {(UTC+13:00) Samoa}

Samoa Standard Time is UTC -11

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share more details about where you're seeing this issue. What project type?
Sending a repro project would help.
