### ISSUE TITLE
Blazor webassembly azure ad authentication issue after migration to .net5

### ISSUE THREAD

**Issue by rubeesh** [dotnet/aspnetcore#28226]
Blazor webassembly azure ad authentication issue after migration to .net5

Error: AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource. Scope https://graph.microsoft.com/User.Read api://861be009-5e73-4c6c-a095-b6e193522222/API. Access openid profile is not valid.

Scope Code(web assembly):
```
builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/User.Read");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("api://861be009-5e73-4c6c-a095-b6e193522222/API.Access");
```

**Comment by javiercn** [comment]
@rubeesh thanks for contacting us.

You need to add one of the scopes to `DefaultScopesToConsent`. This hasn't changed in 5.0 from 3.1.

**Comment by rubeesh** [comment]
> @rubeesh thanks for contacting us.
> 
> You need to add one of the scopes to `DefaultScopesToConsent`. This hasn't changed in 5.0 from 3.1.

I couldnt find any method 'DefaultScopetoConsent'.
If you are referring to AdditionalScopesToConsent, I tried it and didnt work.

**Comment by javiercn** [comment]
@rubeesh checkout [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#request-additional-access-tokens) for details

**Comment by rubeesh** [comment]
> This issue has been resolved and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
> 
> See [our Issue Management Policies](https://aka.ms/aspnet/issue-policies) for more information.

Not yet resolved

**Comment by manasimahajann** [comment]
were you able to get it to work?

**Comment by rubeesh** [comment]
> were you able to get it to work?

Follow 
https://github.com/dotnet/AspNetCore.Docs/issues/20144

**Comment by javiercn** [comment]
@rubeesh Did you get a resolution for this?

**Comment by rubeesh** [comment]
> @rubeesh Did you get a resolution for this?
Resolved. 
https://github.com/guardrex/HostedWASM50AADGroupsAndRolesSample
