### ISSUE TITLE
Dotnet new angular creating project on unsupported version.

### ISSUE THREAD

**Issue by anirugu** [dotnet/aspnetcore#28222]
If you install the Visual Studio 2019 fresh and create a asp.net core angular project, it's using version 8 by default. Is there any plan to change it to version 9 or 10 at-least which is supported (8 support end today 28 Nov 2020).

https://angular.io/guide/releases#support-policy-and-schedule

**Comment by javiercn** [comment]
@anirugu thanks for contacting us.

We do have plans to update versions in a future release, but you can always run ng upgrade on new projects to get them up to date.
