### ISSUE TITLE
Use the 'inject' keyword to identify a property or field.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#28239]
### Is your feature request related to a problem? Please describe.

When we have a lot of  members to inject, we need to write about hundreds of lines of parameters and code in the class initialization method. 
The current injection experience is bad, can it be improved?
(I don't think VS Code Hints make the experience any better, it's still not as easy as using keywords directly.)
  

### Describe the solution you'd like
```C#
public inject IxxxService _xxService;  

// source like this:
[NeedInject]
public readonly IxxxService _xxService;

```

 - The public member
```C#
//in DI ctor
Test instance = new Test();
Unsafe.AsRef(instance._xxService) = new TargetServer();
```

 - The private member ( users need to write `ctor(_server)` by themself )
```C#
//in DI ctor
Test instance = new Test(new TargetServer());
```
>Of course, there are other ways to allow values to be assigned to private fields, although this may not conform to the development specification.  
  

### Other things I want to say.
Use Roslyn instead of EMIT to build dynamic assemblies, like razor. I am using this [scheme](https://github.com/dotnetcore/Natasha/blob/master/test/NatashaUT/OopComplierTest.cs) (incomplete English documentation), and the project runs very well after it is online.
This makes it very convenient for developers to write dynamic code.

**Comment by mkArtakMSFT** [comment]
@davidfowl any recommendation where this should go to?

**Comment by davidfowl** [comment]
There's no plan to add property injection to the default container. Feel free to use one that does support it though there are lots of options

**Comment by mkArtakMSFT** [comment]
Closing per @davidfowl 's comment.

Thanks David!

**Comment by NMSAzulX** [comment]
Although it's a bit of a pity. Thanks David and @mkArtakMSFT .
