### ISSUE TITLE
Blazor WebAssembly - certificate [Linux] [Ubuntu 20.20]

### ISSUE THREAD

**Issue by przemo098** [dotnet/aspnetcore#28237]
### Describe the bug
![image](https://user-images.githubusercontent.com/6282239/100552895-826d2a00-328a-11eb-9c9f-1e04192572cc.png)

It's impossible to run secured connection in Linux environment.
As far as I'm able to generate self signed CA certificate which works for ASP.NET core:
![image](https://user-images.githubusercontent.com/6282239/100552634-b6dfe680-3288-11eb-9ddd-3b6253f7a7d3.png)

1. Using `$ dotnet dev-certs https --clean --import localhost.pfx -p 1234`
results with: 
```diff
- The certificate at 'localhost.pfx' is not a valid ASP.NET Core HTTPS development certificate.
```
There is no place to put it in Blazor WebAssembly configuration (appsettings).

### To Reproduce
Install Ubuntu 20.20
Install .NET 5
`dotnet new blazorwasm`
`dotnet run`
- connection is not secured 
- generate certificate with openssl => no place to attach it in configuration

### Further technical details
![image](https://user-images.githubusercontent.com/6282239/100552743-51d8c080-3289-11eb-982c-38b1cdc23d65.png)

- The IDE (VS Code) 1.51

P.S.
I tried to debug Blazor WASM in VS code it's also impossible.
I guess certificate issue might be the reason, yesterday I received some weird wrong certificate outputs which I'm unable to reproduce today after all day battle...
Also I was unable to debug Blazor WASM in Windows env, however after certificate installation debugger started to work...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
I believe `dotnet devcerts` doesn't support cert generation for Linux yet. I think that is tracked here: #7246.
@javiercn can you please confirm this? Thanks!

**Comment by przemo098** [comment]
Yes I know that devcerts doesn't support that however they generate certificated but the wrong one..., I want to import certs generated by me. Is there any manual way to do that?

Best regards
Przemysław Kamiński

________________________________

**Comment by aloh86** [comment]
I am needing to do the same as @przemo098. On Fedora 33, trying to debug Blazor WASM project in VSCode. According to this thread: https://github.com/dotnet/aspnetcore/issues/21166, it seems that dev-certs needs to be trusted. However, since Linux users cannot do this, we need to supply our own self-signed-certs. How do we tell the WASM project to use the .pfx file that we generated using OpenSSL?

**Comment by przemo098** [comment]
I think you can try to create Blazor WASM hosted in another project by Kestrel but I didn't tried it. I know that VS can generate solution with 2 projects. Later on appsetings.json in second project can be modified to handle your custom  .pfx

Best regards
Przemysław Kamiński

________________________________

**Comment by javiercn** [comment]
A few things to point out:
* As @mkArtakMSFT points out, there is no support for trusting certificates on Linux through the dev-certs tool.
* The `--import` flag of the `dotnet dev-certs` tool is not mean to be a general purpose tool for importing certificates, it's only meant to work with certificates generated by the `dotnet dev-certs tool`.
* You should be able to use your own certificate with the devserver by specifying the path and password as command-line arguments following the standard asp.net config format or within a json file named `blazor-devserversettings.json`
