### ISSUE TITLE
`DefaultAuthorizationService.AuthorizeAsync` log too verbosely.

### ISSUE THREAD

**Issue by PMExtra** [dotnet/aspnetcore#28234]
https://github.com/dotnet/aspnetcore/blob/5db89514e8dccb38de7ef47bcb1598f370a67bc9/src/Security/Authorization/Core/src/DefaultAuthorizationService.cs#L80-L108

https://github.com/dotnet/aspnetcore/blob/5db89514e8dccb38de7ef47bcb1598f370a67bc9/src/Security/Authorization/Core/src/LoggingExtensions.cs#L9-L37

Once I called `AuthorizeAsync`, it will print a log `[INF] Authorization was successful.` or `[INF] Authorization failed.`.
In my case, I used `AuthorizeAsync` in a loop to get a `grantedPolicyList`. That will print so much unused logs.
You may thought it's not a great use case. But I really think the log make no sense. It doesn't show any information such as who was authorized, which policy was evaluated.

I think it would be better if move this log to DEBUG level.

**Comment by blowdart** [comment]
It's an informational log, this don't show up by default, because the default is warning. If you've switched to informational I'm afraid this is what happens.

@HaoK given the lack of useful information in these now we stripping potential PII maybe we should switch the level to debug?
