### ISSUE TITLE
Blazor WASM: HttpClient Upload Progress

### ISSUE THREAD

**Issue by alienwareone** [dotnet/aspnetcore#28245]
I can't make HttpClient work without buffering the request stream.

I've implemented a ProgressableStreamContent that writes the source stream in chunkes to the request stream.

But the request starts **AFTER [SerializeToStreamAsync()](https://github.com/alienwareone/BlazorWasmUploadProgressSample/blob/5b09ccbd6cda0637bedef1d591355bbd33e731ec/Client/ProgressableStreamContent.cs#L27) finished**
and **not as expected after the first [.FlushAsync()](https://github.com/alienwareone/BlazorWasmUploadProgressSample/blob/5b09ccbd6cda0637bedef1d591355bbd33e731ec/Client/ProgressableStreamContent.cs#L47)**

Unfortunately I can't find any "Blazor WASM: Upload with Progress" sample that works.

My Sample Project:
https://github.com/alienwareone/BlazorWasmUploadProgressSample

**Comment by javiercn** [comment]
@alienwareone thanks for contacting us.

This is not a capability browsers have so Blazor can't do anything about it. There is experimental support for this in Chrome 85, but Blazor can't do anything until there is support across browsers and is enabled by default. In any case, this would be a feature that the underlying HttpClient message handler would need to support.

**Comment by pranavkm** [comment]
@alienwareone there's a sample that shows how to display progress with the InputFile component: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/file-uploads/samples/5.x/Components/FileUpload.razor.

**Comment by alienwareone** [comment]
Thanks @javiercn for the clarification. Hope this will get supported across browsers soon :)

@pranavkm Thanks for the link. But this sample doesn't cover a Blazor-WASM upload to a server-endpoint.
