### ISSUE TITLE
Make JSON in view layer

### ISSUE THREAD

**Issue by andrey-skat** [dotnet/aspnetcore#28254]
_Hi, everyone. I'm mainly a Ruby on Rails developer, but I like dotnet and I look at what's new in it from time to time.
aspnet become really enjoyable in recent years, but some features, that make web development very convenient in rails, still does not exist in it. One of them is a lack of view layer templates other than the HTML templating._

I am trying to make an API and return a JSON response. But with aspnet, I can only make JSON object serialization, which I think totally not what the view layer is. Things got more complicated when you want to return complex nested JSON-objects.

So, maybe I wrong and this is not idiomatically correct for aspnet, but if there would be a JSON view templating engine, that can improve MVC separation and adds consistency to how you respond to web requests, it would be more convenient. (Razor for JSON or something?)

#### More text
When I respond with JSON, I have some projection of real objects data mixed with computed data. All responses are not just "give me that object", they are "show me that resource".

For example, we have some user with first name, last name, and email.
In public API we can response with _public user profile resource_ ```{ "firstName: "Sponge", "lastName": "Bob" }```
But in private _account settings resource_ page, we want to response with more data ```{ "firstName: "Spunch", "lastName": "Bob", "email": "sb@live.com" }```.
And of course, it's not a model's responsibility to choose what properties to output in API and how to name JSON keys.

**Comment by javiercn** [comment]
@andrey-skat thanks for contacting us.

This is not a direction we plan to go in, there are many nuances involved in writing a templating language to emit JSON and is a huge effort we don't plan to tackle at the time nor in the near future.

Our recommendation is that if you have a response that doesn't match the current objects you get from somewhere else, you create an object model representing the response you want to produce as well as a mapping between you model and the types used for describing the actual JSON response.

**Comment by andrey-skat** [comment]
Ok, I was made that already :(
Just note, that rails JSON templates are not actually "templates" - they are special ruby code in the view directory.

And if there will be ability to replace Razor with your own view layer processing, it will also be a good feature, I think.

**Comment by javiercn** [comment]
@andrey-skat that's already possible to do.

You can replace Razor with an alternative view engine. You can check [here](https://github.com/sebastienros/fluid) for an example.
