### ISSUE TITLE
Consider allowing middleware to implement IDisposable

### ISSUE THREAD

**Issue by anpete** [dotnet/aspnetcore#2825]
Any middleware that subscribes itself to ```DiagnosticListener``` events can potentially leak because there is no clear way to unsubscribe from event notification when the server is disposed. In practice this can happen when using things like ```TestServer``` because it is common to create and dispose many instances of the server when testing. One solution may be to allow middleware to implement ```IDisposable``` and have the server call ```Dispose``` during shutdown.

**Comment by Tratcher** [comment]
@davidfowl this would be covered by the new IMiddleware scenario, if the implementation was resolved from DI and implemented IDisposable, correct?

**Comment by davidfowl** [comment]
@Tratcher yep. 

@anpete Is that happening in the constructor? Today you'd need to use IApplicationLifetime to handle server shutdown.

**Comment by Tratcher** [comment]
I don't think TestServer implements lifetime events.

**Comment by anpete** [comment]
@davidfowl Yeah, https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore/DatabaseErrorPageMiddleware.cs#L81

**Comment by Tratcher** [comment]
Related:
https://github.com/aspnet/HttpAbstractions/pull/988
https://github.com/aspnet/HttpAbstractions/pull/991

**Comment by davidfowl** [comment]
This is possible now if you use the IMiddleware and you pair it with DI.
