### ISSUE TITLE
[Blazor WASM] Synchronous events

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#28250]
Synchronous events aren't available in server-side Blazor for obvious reasons, but there is no reason I am aware of that WASM cannot support them.

If we can sync version of events then we could do things such as preventing a drag=>drop onto a specific area of a component, and other such cancellable events.

Perhaps have WASM only events that are the same as standard events but with "sync-" prepended, such as `sync-ondragover`?

PS: Will this repo now move to `aspnet` rather than `aspnetcore`?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
