### ISSUE TITLE
nuget package can't restore

### ISSUE THREAD

**Issue by li-zhixin** [dotnet/aspnetcore#28251]
package name : 
Microsoft.Extensions.FileSystemGlobbing
package version:3.1.10

```shell
 NotFound https://api.nuget.org/v3/registration5-gz-semver2/microsoft.extensions.filesystemglobbing.3.1.10.nupkg/index.json 1003ms
```

```xml
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:42934c95-601e-0099-03f9-c6bf97000000 Time:2020-11-30T09:14:43.1221526Z</Message>
</Error>
```

**Comment by Pilchie** [comment]
@aortiz-msft - this looks like a NuGet server or network issue to me, not something specific to this package.  Should I move this issue to NuGet/Home?

**Comment by aortiz-msft** [comment]
@li-zhixin - Would you please contact the package owner from https://www.nuget.org/packages/Microsoft.Extensions.FileSystemGlobbing?

Alternatively, you can request support from NuGet.org here: https://www.nuget.org/policies/Contact

**Comment by Pilchie** [comment]
@aortiz-msft - I'm the package owner - it comes from this repo, it's just that this error doesn't look like a problem with the package.

**Comment by Pilchie** [comment]
@li-zhixin - could you share the contents of .csproj file?  One suspicion is that you have a `<PackageReference>` that has version information in the wrong place.
