### ISSUE TITLE
[Question][SignalR][Message pack] How to parse enum as int?

### ISSUE THREAD

**Issue by AlexChar** [dotnet/aspnetcore#28279]
Hi,

I'm using message pack(Microsoft.AspNetCore.SignalR.Protocols.MessagePack 3.1.9) with signalr  on the server and the client(web browser). I'm trying to parse an enum as int but I got the string instead. For example in the following class:

```
public enum Gender
{
	Male = 1,
	Female = 2
}

[MessagePackObject]
 public class Person
{
	[Key("user")]
	public string User { get; set; }
	[Key("description")]
	public string Description { get; set; }
	[Key("created")]
	public DateTime Created { get; set; }
	[Key("isAnonymous")]
	public bool IsAnonymous { get; set; }
	[Key("firstPost")]
	public bool FirstPost { get; set; }
	[Key("contactInfo")]
	public ContactInfo ContactInfo { get; set; }
	[Key("gender")]
	public Gender Gender { get; set; } = Gender.Female;
}
```

The response I got in the client is the following:

![messagePack](https://user-images.githubusercontent.com/9989946/100765344-13b1dd00-3400-11eb-9084-467fdd43acc5.png)

I'm expecting to get `2` here instead of `"Female"`

I'm setting message pack on server like:

`services.AddSignalR().AddMessagePackProtocol();`

and on the client like:
```
var connection = new signalR.HubConnectionBuilder()
    .withUrl("/chatHub")
    .withHubProtocol(new signalR.protocols.msgpack.MessagePackHubProtocol())
    .build();
```

**Comment by BrennanConroy** [comment]
You can customize how your types are serialized.
```
.AddMessagePackProtocol(options =>
{
    options.SerializerOptions = options.SerializerOptions.WithResolver(...);
    // or
    options.SerializerOptions = MessagePackSerializerOptions.Standard.WithResolver(...);
});
```

More info can be found at https://github.com/neuecc/MessagePack-CSharp/blob/master/README.md

**Comment by pschnoop** [comment]
Hi @AlexChar ,
I am having the same issue.
Could you please provide a solution here for me?
