### ISSUE TITLE
Put Action Method Throws JsonException Unlike Others

### ISSUE THREAD

**Issue by Atalaybars** [dotnet/aspnetcore#28270]
So I have a simple restful api and everything works well except put action method. 

It gets a simple Hotel object which has three properties: Name, City, and Id. 

And here is the code in Hotel Repository layer:

`public async Task<int> UpdateHotel(Hotel hotel)
    {
        var sql = "UPDATE Hotels " +
                    "SET name = @name, city = @city " +
                    "WHERE Id = @id";

        var updatedHotel = new Hotel()
        {
            Name = hotel.Name,
            City = hotel.City,
            Id = hotel.Id
        };

        using (var connection = new SqlConnection(CONNECTION_STRING))
        {
            return await connection.ExecuteAsync(sql, updatedHotel);
        }
    }`

After these lines of code executed and the computer left this method the exception is thrown. 

Here is the error: 
System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.
 
Do you know why that is? 

When I first debugged the exception was thrown during the execution of the method, in the return statement specifically . I saw I didn’t add any spaces at the ends of the sql strings and I fixed that. After that the current situation is as I describe above.

**Comment by javiercn** [comment]
@Atalaybars thanks for contacting us.

This question is not about ASP.NET Core but specifically about JSON serialization. In general, serializing graphs of objects is not supported out of the box, you can change that in the configuration `AddMvc().AddJsonOptions(o => ...)`. However, this is something that we discourage you from doing. 

We recommend that you remove cyclical dependencies from your object model if you plan on serializing it via JSON or create a separate object model composed of DTOs for producing the response and map your models to those DTOs.

**Comment by Atalaybars** [comment]
Thank you!
