### ISSUE TITLE
Add ConnectionContext.Items to ConnectionInfo 

### ISSUE THREAD

**Issue by coderuid** [dotnet/aspnetcore#28278]
### Is your feature request related to a problem? Please describe.
I added middleware to ConnectionBuilder in order to detect request source. Later I expected to find my data at HttpContext.Items. But I found that ConnectionContext.Items and HttpContext.Items are different objects.

```
webHostBuilder.ConfigureKestrel((context, options) =>
    {
        options.Listen(IPAddress.Parse("0.0.0.0"), 3301, listenOptions =>
        {
            listenOptions.Use((connectionContext, next) =>
              {
                  connectionContext.Items.Add("kestrelEndpoint", "3301");
                  return next();
              });
        });
      File.Delete("/tmp/api.socket");
      options.ListenUnixSocket("/tmp/api.socket", listenOptions =>
      {
           listenOptions.Use((connectionContext, next) =>
           {
               connectionContext.Items.Add("kestrelEndpoint", "unixSocket");
               return next();
           });
      });
 });
```

### Describe the solution you'd like
Add ConnectionContext.Items to ConnectionInfo along with ConnectionId and some other fields. So, ConnectionContext.Items will be accessible over HttpContext.Connection in middlewares and controllers.
And it will be possible to pass any needed data from connection processing pipeline to request pipeline.

**Comment by coderuid** [comment]
I could make PR to add this functionality

**Comment by Tratcher** [comment]
That would only be supported on Kestrel, not IIS or HttpSys. We try not to add implementation specific APIs to the shared abstractions.

There should be a way to get to this data though. @halter73?

**Comment by coderuid** [comment]
IHttpConnectionFeature and others are not implementation specific. They are already in shared abstractions and are passed in common way for IIS and HttpSys too. ConnectionId, Local/Remote IpAddress and ports goes through all pipelines. Adding Items will add same functionality to IIS and HttpSys too.

**Comment by Tratcher** [comment]
In IIS and HttpSys the connections are not managed by the AspNetCore components, but by a component much lower in the stack. That makes it hard to add connection level features that aren't natively supported. IPs and IDs are features natively supported by all three servers. Items are not.

**Comment by coderuid** [comment]
According to this logic Items should be in Kestrel library. But we have them in global Microsoft.AspNetCore.Http.Features and if we use it only in Kestrel, it is in fact the "implementation specific APIs to the shared abstractions". Thus, we speak about enhancement of global connection stack, not about Kestrel, HttpSys or something else. Neither Kestrel nor HttpSys will be affected by passing already existed data from connection context (which is not Kestrel or HttpSys specific) to http context.

Is there any true ways to pass this data? Ugly hack: add some prefix to ConnectionId string (it works). Another way is to create some external singleton storage for that data but there is a lot of work to do to keep it consistent. But passing Items though stack seems to be more clear and reliable.

**Comment by halter73** [comment]
> Neither Kestrel nor HttpSys will be affected by passing already existed data from connection context (which is not Kestrel or HttpSys specific) to http context.

ConnectionContext is a Kestrel-specific API today. Other servers could theoretically implement the abstraction, but I'm not aware of any others that do today. As @Tratcher points out, the HTTP.Sys doesn't give you direct control over the underlying connection making implementing the abstraction in HttpSysServer impossible.

Even in Kestrel's case, I don't we should combine ConnectionContext.Items and HttpContext.Items because it's a pretty niche use case and it would technically breaking. There is a pretty easy workaround though:

To access ConnectionContext.Items and ConnectionContext.Id from request middleware, you can do something like the following:

```C#
IDictionary<object, object> connectionItems = httpContext.Features.Get<IConnectionItemsFeature>().Items;
string connectionId = httpContext.Connection.Id;
```

Does this work for you @coderuid?

**Comment by coderuid** [comment]
@halter73 Sure! I've never asked about mixing ConnectionContext.Items and HttpContext.Items. They are quite different.
Now we have only Microsoft.AspNetCore.Http.Features.IHttpConnectionFeature in HttpContext.

`httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestBodyDetectionFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpResponseFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpResponseBodyFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IRequestBodyPipeFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestIdentifierFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IServiceProvidersFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestLifetimeFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpConnectionFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IRouteValuesFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IEndpointFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestTrailersFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpUpgradeFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature
httpContext features: Microsoft.AspNetCore.Server.Kestrel.Core.Features.IHttpMinRequestBodyDataRateFeature
httpContext features: Microsoft.AspNetCore.Server.Kestrel.Core.Features.IHttpMinResponseDataRateFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpBodyControlFeature
`

And IHttpConnectionFeature is also available as HttpContext.Connection.

Passing IConnectionItemsFeature to HttpContext.Features will solve the problem.

Should I make PR?

**Comment by halter73** [comment]
I doubt we'll change IHttpConnectionFeature. Adding members to existing public interfaces is breaking. What's wrong with using `httpContext.Features.Get<IConnectionItemsFeature>().Items`?

**Comment by coderuid** [comment]
No problem with `httpContext.Features.Get<IConnectionItemsFeature>().Items`. I asked if I should make PR to add IConnectionItemsFeature to httpContext.Features because there is no IConnectionItemsFeature now:

```
foreach (var (k,v) in context.Features)
  {
    Console.WriteLine($"httpContext features: {k.FullName}");
  }
```

result:

```
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestBodyDetectionFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpResponseFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpResponseBodyFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IRequestBodyPipeFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestIdentifierFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IServiceProvidersFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestLifetimeFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpConnectionFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IRouteValuesFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IEndpointFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpRequestTrailersFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpUpgradeFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature
httpContext features: Microsoft.AspNetCore.Server.Kestrel.Core.Features.IHttpMinRequestBodyDataRateFeature
httpContext features: Microsoft.AspNetCore.Server.Kestrel.Core.Features.IHttpMinResponseDataRateFeature
httpContext features: Microsoft.AspNetCore.Http.Features.IHttpBodyControlFeature
```

**Comment by davidfowl** [comment]
It's not available in the enumeration currently but maybe it should be.

**Comment by coderuid** [comment]
`IDictionary<object, object> connectionItems = httpContext.Features.Get<IConnectionItemsFeature>().Items;` works as expected. @halter73 thank you for help!

Adding IConnectionItemsFeature to enumeration would be great.

Anyway initial problem is solved.
