### ISSUE TITLE
German translation in dotnet hosting package 5.0 wrong

### ISSUE THREAD

**Issue by fabsenet** [dotnet/aspnetcore#28284]
![grafik](https://user-images.githubusercontent.com/2065705/99945526-0ef08780-2d75-11eb-89fa-3eb95832c896.png)

"Die Installation wurde erfolgreich" is not a real german sentence. It should be either "Die Installation war erfolgreich" or "Die Installation wurde erfolgreich abgeschlossen"

it is the official dotnet-hosting-5.0.0-win.exe file downloaded last week.

**Comment by javiercn** [comment]
@dotnet/aspnet-build Can you take a look?

**Comment by wtgodbe** [comment]
I should be able to take a look tomorrow.

@wli3 I thought the infra for creating these install screens was external to our repos, and that we just provided the strings? I guess it'd be a WiX issue, so maybe @joeloff would know more, or at least who we should contact?

**Comment by joeloff** [comment]
That should be coming from the thm.wxl and what I'm seeing is 

```
  <String Id="SuccessInstallHeader">Die Installation wurde erfolgreich abgeschlossen.</String> 
```

As @wli3 said, it's likely the UI is cutting off the text and the Height needs to be adjusted in the thm.xml file for this:

```
<Text Name="SuccessInstallHeader" X="11" Y="80" Width="-11" Height="30" FontId="2" HideWhenDisabled="yes" DisablePrefix="yes">#(loc.SuccessInstallHeader)</Text>
```

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/28332

**Comment by jkotalik** [comment]
@wtgodbe put this in the 5.0.2 milestone, feel free to remilestone if that is incorrect.
