### ISSUE TITLE
Improve HttpSysOptions descriptions

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#28297]
The concept docs for HttpSys have some better descriptions of the HttpSys options than the API docs, especially the default values. 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0#configure-the-aspnet-core-app-to-use-httpsys
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.httpsysoptions?view=aspnetcore-5.0
https://github.com/dotnet/aspnetcore/blob/58a7eb63ad5c6b037c43d2bd178c79f4248bb71f/src/Servers/HttpSys/src/HttpSysOptions.cs

We don't want to maintain two copies of these options docs, we should improve the API docs and remove the redundant entries from the concept docs.

See https://github.com/dotnet/AspNetCore.Docs/issues/20827

**Comment by nmnick18** [comment]
I'd like to work on this after you guys move it from backlog to the sprint planning.

**Comment by Tratcher** [comment]
@nmnick18 feel free to do it now. It's in the backlog because we don't have bandwidth to work on it ourselves.

**Comment by nmnick18** [comment]
@Tratcher upon reading more into this. it seems like that this is version difference, but you guys want to move towards merging the old stuff to the new stuff and keeping a single doc. 

Also I apologies for looking at this very late, but I have school and work which take up most of my days

**Comment by Tratcher** [comment]
No worries.

More specifically, we want to update the comments here:
https://github.com/dotnet/aspnetcore/blob/58a7eb63ad5c6b037c43d2bd178c79f4248bb71f/src/Servers/HttpSys/src/HttpSysOptions.cs
Which will get automatically synced to here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.httpsysoptions?view=aspnetcore-5.0
And then we want to remove the redundant entries here and link to the API docs instead.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0#configure-the-aspnet-core-app-to-use-httpsys

**Comment by Rick-Anderson** [comment]
@nmnick18  mention me when you're ready and I'll help out.

**Comment by nmnick18** [comment]
@Rick-Anderson I am ready to move forward with this. Let me know a good time your free, we could schedule a call if you like.

**Comment by Rick-Anderson** [comment]
@nmnick18  send me an email
`riande@microsoft.com`

**Comment by ZarakiKanzaki** [comment]
Hi! I wanted to ask you something more about this issue, I saw it's linked to pull request that seemed incomplete. Should I contribute by making my own suggestion or its ok to replicate the closed pr with the suggestion asked in it? Thanks in advance

**Comment by Tratcher** [comment]
Please create a new PR and incorporate the outstanding feedback.
