### ISSUE TITLE
HTTP/3: Connection not upgraded to HTTP/3 with HttpClient

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#28296]
Kestrel currently sends back alt-srv value of `h3-25`.

https://github.com/dotnet/aspnetcore/blob/77fe36f069c89381caba274784902ff0f248fe57/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L1187-L1198

It sounds like HttpClient (and Chrome) are expecting `h3-29`. They won't use HTTP/3 unless explicitly asked for. See https://github.com/dotnet/runtime/issues/45319

h3-29 seems like a good value to use for now.

> Today this changes. We've found that IETF QUIC significantly outperforms HTTP over TLS 1.3 over TCP. In particular, Google search latency decreases by over 2%. YouTube rebuffer time decreased by over 9%, while client throughput increased by over 3% on desktop and over 7% on mobile. We're happy to announce that Chrome is rolling out support for IETF QUIC (specifically, draft version h3-29). Today 25% of Chrome Stable users are using h3-29, and we plan on increasing that number over the coming weeks as we continue to monitor performance data. Chrome will actively support both IETF QUIC h3-29 and Google QUIC Q050 to provide servers that support Q050 with time to update to IETF QUIC.
> Chrome m85 doesn't yet support IETF QUIC 0-RTT, so we expect these performance numbers to look even better once we launch 0-RTT support for IETF QUIC in the coming months.
> Since the subsequent IETF drafts 30 and 31 do not have compatibility-breaking changes, we currently are not planning to change the over-the-wire identifier. What this means is that while we'll keep tracking changes in the IETF specification, we will be deploying them under the h3-29/0xff00001d name. We therefore recommend that servers keep support for h3-29 until the final RFCs are complete if they wish to interoperate with Chrome. However, if the IETF were to make compatibility-breaking changes in a future draft, Chrome will revisit this decision.

https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html

**Comment by JamesNK** [comment]
FYI @jkotalik

**Comment by jkotalik** [comment]
Ah, that's where it was hard coded XD.
