### ISSUE TITLE
Blazor WebAssembly - CascadingParameters not behaving as expected.

### ISSUE THREAD

**Issue by ThomasBjallas** [dotnet/aspnetcore#28303]
I have found a strange behavior where the binding to a <InputText> works different depending on the type of a not CascadingParameter (not related to the <InputText>. Let me explain what I am trying to do.

I am trying to write a custom component that wraps the <InputText> so I automatically can add extra HTML markup before and after the <InputText>. To be able to decide how to generate the extra Markup I created a CascadingParameter in my component that is supposed to hold metadata needed for the extra markup, that is when I noticed a strange behavior with the CascadingParameter.

It is also important for me that Validations are working correctly even when I wrap the <InputText>.
Depending of the type of the cascading parameter the value in the <InputText> is lost when it gets lost focus (ValueChanged). If the CascadingParameter is a string or int it works fine, but if it is instance of a class or a enum it does not work. I think it is very strange that the behavior of the <InputText> changes based on the type of the CascadingParameter.

### To Reproduce
I have been able to reproduce the problem in a simple project that I have attached. Here are also the basics of the steps to reproduce the problem

[CascadingParameterProblem.zip](https://github.com/dotnet/aspnetcore/files/5626110/CascadingParameterProblem.zip)

First I have my Component "Component.razor"

```
@using System.Linq.Expressions;

<InputText Value="@Value" ValueChanged="@((v) => Value = v)" ValueExpression="@ValueExpression" />

@code {

    [CascadingParameter] public Page.MyDto MyCascadingObject { get; set; }
    [CascadingParameter] public string MyCascadingString { get; set; }

    [Parameter] public EventCallback<string> ValueChanged { get; set; }
    [Parameter] public Expression<Func<string>> ValueExpression { get; set; }

    public string _value;
    [Parameter] public string Value
    {
        get => _value;
        set
        {
            Console.WriteLine($"Value Setter: {value}");
            if (_value == value) return;
            _value = value;
            ValueChanged.InvokeAsync(value);
        }
    }
}
```

Secondly I have a page “Page.razor”
```
@page "/"
@using System.ComponentModel.DataAnnotations
   
<h4>Written text removed when LostFocus</h4>
<EditForm Model="dto1">
    <DataAnnotationsValidator />

    <CascadingValue Value="@MyCascadingObject">
        <Component @bind-Value="dto1.Prop1" />
    </CascadingValue>

    <ValidationSummary />
    <br />
    <button type="submit">Submit</button>
</EditForm>

<h4>Written text is kept when LostFocus</h4>
<EditForm Model="dto2">
    <DataAnnotationsValidator />

    <CascadingValue Value="@MyCascadingString">
        <Component @bind-Value="dto2.Prop1" />
    </CascadingValue>

    <ValidationSummary />
    <br />
    <button type="submit">Submit</button>
</EditForm>

<br />
<p>
    The only difference of the two examples is that the first one uses a 
    class of type MyDto in the CascadingValue and the second one uses a string.
</p>

@code {
    public MyDto MyCascadingObject { get; set; } = new MyDto();
    public string MyCascadingString { get; set; } = "";

    public MyDto dto1 = new MyDto();
    public MyDto dto2 = new MyDto();

    public class MyDto
    {
        [Required] public string Prop1 { get; set; }
    }
}
```

In the page I have added two <EditForm> components, the first one is not working and the second one is working as expected. The only difference of the code inside the 2 <EditForms> is that first one uses the property MyCascadingObject for the CascadingValue and the second <EditForm> uses the property MyCascadingString.
When you run this page and input text to the first TextBox (the <EditForm> that uses a object for a CascadingParameter) and then tabs out the TextBox is cleared. If you do the same for the second textbox it works fine.

### Further technical details
I am using ASP.NET Core 5.0.0 and here is my dotnet --info output:
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
@ThomasBjallas thanks for contacting us.

At a glance I can probably tell that this is likely due to how diffing works. With the string (inmutable type) or int, Blazor is able to determine that the value has not changed, while with an object it can't (because even though you pass the same instance it could have been mutated) so it performs a re-render.

**Comment by ThomasBjallas** [comment]
Ok, so then I guess this is the expected behavior, but if that is the case is there a better way to bind the <InputText> inside my component and still have the Validation working?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
There is also an issue with the setter of the `Value` property. you invoke value change from inside it which can lead to an infinite loop. Can you please try to address that and see whether that will resolve the issue?

**Comment by ThomasBjallas** [comment]
I have made a change to my component according to the suggestion from @mkArtakMSFT. I change it so that `ValueChanged `is not invoked from the Setter of the `Value` property. The `ValueChanged `on the `<InputText>` now calls a new method named `InputValueChanged` that calls the Setter of the property but also invokes the `ValueChanged `event.

**My modified "Component.razor"**
```
@using System.Linq.Expressions;

<InputText Value="@Value" ValueChanged="@((v) => InputValueChanged(v))" ValueExpression="@ValueExpression" />

@code {

    [CascadingParameter] public Page.MyDto MyCascadingObject { get; set; }
    [CascadingParameter] public string MyCascadingString { get; set; }

    [Parameter] public EventCallback<string> ValueChanged { get; set; }
    [Parameter] public Expression<Func<string>> ValueExpression { get; set; }

    public string _value;
    [Parameter]
    public string Value
    {
        get => _value;
        set
        {
            Console.WriteLine($"Value Setter, value: '{value}', _value: '{_value}'");
            if (_value == value) return;
            _value = value;
        }
    }

    public void InputValueChanged(string value)
    {
        Console.WriteLine($"InputValueChanged, value: '{value}', _value: '{_value}'");
        if (Value == value) return;
        Value = value;
        ValueChanged.InvokeAsync(value);
    }
}
```

This solved the problem I had but I am still not sure if all is OK. The value of the textbox is now persisted after lostfocus and the validation works fine. But as you can see in the modified component I have also added a `Console.WriteLine` in both the Setter of the property and i the new method `InputValueChanged`. If have the value "Test" in the textbox and changes it to "Test1" and Tab out of the textbox i will get the following output in the browsers console.

**Browser Console output**
```
InputValueChanged, value: 'Test1', _value: 'Test'		blazor.webassembly.js:1
Value Setter, value: 'Test1', _value: 'Test'				blazor.webassembly.js:1
Value Setter, value: 'Test', _value: 'Test1'				blazor.webassembly.js:1
Value Setter, value: 'Test1', _value: 'Test'				blazor.webassembly.js:1
Value Setter, value: '', _value: ''					blazor.webassembly.js:1
```

Even if the end result is OK since the last call to the setter will be ignored (both the `value `and the `_value ` are  empty strings). I don't understand why I do get 4 call to the setter and epecially I don't understand why second call holds the "old" value and the last call to the setter holds a empyt string.

If I do the same but instead use MyCascadingString in the CascadingValue i will get the output below. So no change in the code, other than changing the type used in the CascadingValue. In this case I still get 4 calls to the setter, but here the values are OK for all calls.  I still don't understand why changing the CascadingValue to a object causes the setter to be called with invalid values, is it supposed to be like that?

```
InputValueChanged, value: 'Test1', _value: 'Test'			blazor.webassembly.js:1
blazor.webassembly.js:1 Value Setter, value: 'Test1', _value: 'Test'	blazor.webassembly.js:1
blazor.webassembly.js:1 Value Setter, value: 'Test1', _value: 'Test'	blazor.webassembly.js:1
blazor.webassembly.js:1 Value Setter, value: 'Test1', _value: 'Test'	blazor.webassembly.js:1
blazor.webassembly.js:1 Value Setter, value: 'Test1', _value: 'Test'	blazor.webassembly.js:1
```

**Comment by ThomasBjallas** [comment]
I have read this documentation (https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0) and I think it has several sections that explains why it behaves as it does.

I understand the concept much better now and from my point I think we can close this issue.

**Comment by javiercn** [comment]
@ThomasBjallas thanks for following up.

I'm glad that the docs helped!

I'm closing this issue since there's nothing else for us to do here.
