### ISSUE TITLE
integration with Deno Aleph.js

### ISSUE THREAD

**Issue by Ashutosh94g** [dotnet/aspnetcore#28309]
As new and more secure package manager like deno is coming for js/ts and react can be used though aleph.js for now and at some time in the future react will also shift to deno from npm. please manage a spa service extension for deno.

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by javiercn** [comment]
@Ashutosh94g thanks for contacting us.

I'm not completely sure what the request is here, but we don't have plans at the moment to perform additional integrations with JS in the SPA templates.

If it's support for the equivalent of package.json on the SPA templates, we won't likely do it unless it becomes the mainstream option. You are free to start with the template and switch the package manager to the one you prefer to use.
