### ISSUE TITLE
Blazor Server App - Debugger not showing values.

### ISSUE THREAD

**Issue by ForerunnerG34** [dotnet/aspnetcore#28304]
### Describe the bug
I'm really trying to use Blazor for production, but there are important bugs in Blazor and VS2019 that makes this task not possible and will have to look somewhere else. In case somebody is interested: You can't see values of variables when debugging a Blazor Server App, instead you get variable types, could be Blazor, could be VS2019.

### To Reproduce
Create any Blazor Server App, write any code in a .razor file, se a break point and try to inspect the value of the variable.

### Further technical details
- .Net 5
![debug](https://user-images.githubusercontent.com/46511735/100811756-5330f700-3409-11eb-823e-54da7a69ae92.png)

- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
