### ISSUE TITLE
[EnableCors] attribute cannot be combined with middleware

### ISSUE THREAD

**Issue by Robulane** [dotnet/aspnetcore#28315]
### Describe the bug
It's very common to have some controllers that have a different CORS policy than the entire application.

The documentation states: "When the [EnableCors] attribute is applied to a controller, page model, or action method, and CORS is enabled in middleware, both policies are applied. We recommend against combining policies."

Even if it's not recommended, this setup works when CORS requests don't include custom headers. In such a case, the browser will directly send Get or Post request and everything will work:
1. Middleware can set the headers saying that Origin is not allowed.
2. "EnableCors" attribute will override these headers.

However, when custom headers are sent, Browser sends "Options" request before the actual "Get/Post" request.
In this case, the Middleware just returns the response without giving a chance to "EnableCors" attribute to override the headers.
As a result, the request is blocked. Here is the code that does it: https://github.com/dotnet/aspnetcore/blob/94b1c6f6b423482ce52fb0473df33b6699ea755e/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L205

This behavior doesn't correspond to the documented behavior because only Middleware code is executed. 

Current behavior limits pretty much the usage of CORS APIs in more or less serious projects. We should consider changing it and allow overriding of App-level settings per controller.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Robulane** [comment]
Actually, this bug is fixed in the new .net core version thanks to the changes in the routing endpoint. 
Now, CORS middleware knows what controller will be executed and can retrieve a good CORS policy
