### ISSUE TITLE
Aspnetcore Area parses errors when using TagHelper.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28317]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/aspnetcore-Area在使用TagHelper时，解析报错。/1266380)._

---
Aspnetcore Area parses errors when using TagHelper. For example: <a asp-area," "abc" asp-controller, "bcd" asp-action, "cde" >xxx</a>, will be parsed as: localhost:zzz/bcd?abc....

---
#### Feedback Bot on 11/24/2020, 01:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### jinlinshao on 11/26/2020, 09:16 PM: 

<p>这个问题确实存在的哟。<br>
<img src="https://aka.ms/dc/image?name=B0a4f34c938fc4a709a725f6d6be18ee6637420508097517123_AreaError.png&amp;tid=0a4f34c938fc4a709a725f6d6be18ee6637420508097517123" alt="AreaError.png"><br>
<img src="https://aka.ms/dc/image?name=B7e3b79c6268749a697e78d504864c165637420509596172277_ErrorResult.png&amp;tid=7e3b79c6268749a697e78d504864c165637420509596172277" alt="ErrorResult.png"></p>

#### jinlinshao on 11/26/2020, 11:43 PM: 

<p>If there is an area, the internal controller of the area controller cannot jump.<br>
<img src="https://aka.ms/dc/image?name=Ba5f87ff1ceec4d29b8fa63552301f7cf637420598097579444_innerGoto.png&amp;tid=a5f87ff1ceec4d29b8fa63552301f7cf637420598097579444" alt="innerGoto.png"></p>

---
#### jinlinshao solved on 11/26/2020, 09:20 PM, 0 votes: 

<p>[Workaround]<br>
<img src="https://aka.ms/dc/image?name=B7db123ed8acc4cf083c30e7af49678bb637420512337363227_ErrorResult.png&amp;tid=7db123ed8acc4cf083c30e7af49678bb637420512337363227" alt="ErrorResult.png"></p>

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
