### ISSUE TITLE
Blazor rendering verbatim component instead of component html markup

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#28312]
I am creating a charting application. For a set of components, Blazor does not render the component. It renders the component name as HTML. 

I have tried
- Clean+rebuild
- Deleting the contents of debug/bin
- Restarting visual studio and doing the above.

- .net 5.0
- Visual Studio Community 16.8.2
-  dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download[
![Parent](https://user-images.githubusercontent.com/40038634/100853793-2da9f900-34ae-11eb-99dc-3956eddb0da7.PNG)
![Console](https://user-images.githubusercontent.com/40038634/100853806-339fda00-34ae-11eb-978d-88d54262e4b1.PNG)

](url)

**Comment by javiercn** [comment]
@mayur-ekbote thanks for contacting us.

Seems for some reason the runtime is not finding the component definition so it believes it is an HTML tag. Can you add more details about the definition of EditableAxisSelector or (better yet) a minimal repro project that showcases the issue so that we can point out the problem?

**Comment by mayur-ekbote** [comment]
I found the issue after I did further digging. I had done some refactoring and the function "UpdateSeries" was renamed. When I updated the function name, it rendered correctly. It could either be a VS problem (VS doesn't highlight a problem when it should, specifically type mismatch) or as you mentioned, a runtime issue. I hope this helps?

**Comment by javiercn** [comment]
@mayur-ekbote thanks for the additional details.

This seems to be a tooling problem if anything.

@NTaylorMullen can you take it from here?

**Comment by NTaylorMullen** [comment]
> I found the issue after I did further digging. I had done some refactoring and the function "UpdateSeries" was renamed. When I updated the function name, it rendered correctly. It could either be a VS problem (VS doesn't highlight a problem when it should, specifically type mismatch) or as you mentioned, a runtime issue. I hope this helps?

Ahh @mayur-ekbote I'd be curious if this reproduces on the latest 16.9 VS builds. We recently did work to massage out all of the rename hurdles in Blazor
