### ISSUE TITLE
VS reports that UseAuthorization should appear between UseRouting and UseEndpoints... but it already does?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28313]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-reports-that-UseAuthorization-should-/1265513)._

---
[severity:It bothers me. A fix would be nice]
VS reports that UseAuthorization should appear between UseRouting and UseEndpoints... but it already does?

I've tried to "clean" the solution, rebuild, restart VS and all... It won't go away.

Please see attached additional screen-shot.

---
#### Feedback Bot on 11/23/2020, 00:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
