### ISSUE TITLE
Cant debug client side Blazor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28316]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cant-debug-client-side-Blazor/1266048)._

---
[severity:It bothers me. A fix would be nice]
I have a Blazor web assembly project with .net core hosted and I'm trying to debug the client side C# code but it does not work. 

This comes out of the box to help with debugging but doesn't go to my break point.

"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",

Any idea?

---
#### Feedback Bot on 11/23/2020, 06:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Raymond Bell on 11/26/2020, 01:43 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It's not clear whether you're having this issue with an existing project, or with any new Blazor WebAssembly Hosted project. Can you please clarify?
Also, what SDK are you targeting? Is it .NET Core 3.1 or 5.0 ?

**Comment by icedenis** [comment]
I cant even launch the Blazor Webassembly on Chrome/Edge Only Firefox is working atm , If there is a way to debug in Firefox pls help
![Unbenannt](https://user-images.githubusercontent.com/62735589/101180028-57e4ed80-364b-11eb-80e6-de4c8ad2af6d.png)

and here 
![Unbenannt2](https://user-images.githubusercontent.com/62735589/101180041-5ca9a180-364b-11eb-9657-ec44a3f63d8f.png)

**Comment by captainsafia** [comment]
@icedenis It looks like you're running into this issue with Blazor WASM 3.2. Can you repro in 5.0?
