### ISSUE TITLE
Blazor WAMS donet watch run

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28320]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-WAMS-donet-watch-run/1268455)._

---
[severity:I'm unable to use this version]
doesnt work
PM> dotnet watch run 
dotnet : It was not possible to find any compatible framework version
In Zeile:1 Zeichen:1
+ dotnet watch run
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (It was not poss... amework version:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

---
#### Feedback Bot on 11/24/2020, 11:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for  contacting us.
It looks like you don't have a recent runtime installed.
Please make sure you have the latest 5.0 SDK installed. You can download it [from](https://get.dot.net)
