### ISSUE TITLE
dotnet-sdk-5.0.100-rc.1.20452.10 HTTPS Certificate Not Recognized, Removed and  Added

### ISSUE THREAD

**Issue by ozersenol** [dotnet/aspnetcore#28322]
Win10,
dotnet-sdk-5.0.100-rc.1.20452.10 installed,
dotnet core 3.1 web app not start due to lack of https certificate. 

cmd commands --clean, --trust and --check does not recognize certificates. 

global commands also  does not remove any certs.

after uninstalling dotnet-sdk-5.0.100-rc.1.20452.10 from the system, certs recognized and everyting works as normal.

**Comment by Pilchie** [comment]
Moved to aspnetcore.  @javiercn - any ideas here?

**Comment by javiercn** [comment]
@Pilchie Nothing crosses my mind immediately.

**Comment by mkArtakMSFT** [comment]
@Tratcher any ideas what may be causing this?

**Comment by Tratcher** [comment]
Only that the dev cert version was updated in 5.0. There's a similar discussion happening at https://github.com/dotnet/aspnetcore/issues/28399.

**Comment by adityamandaleeka** [comment]
It's unclear if this is still an issue since the original report was for 5.0 RC1. Closing this, please open a new issue if needed.
