### ISSUE TITLE
@ref not compiling in conversion from Blazor Server & .NET Core 3.1 to Blazor WebAssembly & .NET Core 5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28321]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ref-not-compiling-in-conversion-from-Bl/1271329)._

---
I have a program written in Blazor Server using .NET Core 3.1.
I'm trying to convert it to .NET Core 5 WebAssembly.
I had a class derived from ComponentBase referenced in a component that worked well, but now, when trying to compile the compiler throws the next message:
Cannot implicitly convert type 'Microsoft.AspNetCore.Components.ElementReference' to 'TableroPecasV5.Logicas.CLogicaReloj'	
The message is repeated if I reference a ComponentBase variable, too.

In other components I have references to Blazor.Extensions.Canvas.BECanvas that continue to compile fine.

I don't understand why that message occurs.

---
#### Feedback Bot on 11/29/2020, 06:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### rperazzolli on 12/1/2020, 10:20 AM: 

<p>Changing in the page the razor name for the inherited class it was fixed.<br>
In Blazor Server version it worked.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This looks like some error in your code. @SteveSandersonMS do you happen to have any hints for this situation?

In case you haven't seen this, please take a look at the 5.0 migration guide: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio

**Comment by mkArtakMSFT** [comment]
Just noticed that you were able to find resolution to you problem, @rperazzolli. Thanks for using Blazor!
