### ISSUE TITLE
Attribute Transition Completion Item Shows Up At Wrong Spot

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#28338]
![AttributeTransitionCompletionItemAtWrongPoint](https://user-images.githubusercontent.com/14852843/100946288-0a447580-34d1-11eb-9c6f-f89f15611f9c.gif)

**Comment by allisonchou** [comment]
Confirmed with @TanayParikh that this no longer repros as of 30913.193.main. Will close out bug.
