### ISSUE TITLE
Blazor WASM Azure AD redirection auth not directing to return URI (NET 5)

### ISSUE THREAD

**Issue by wasabii** [dotnet/aspnetcore#28330]
Enabling MSAL authentication in Blazor client side, and decorating a page with [Authorize], forces a redirect to /authentication/login?returnUri={originalUri}. This then heads over to AAD. AAD heads back to /authentication/login-callback. But, at this point, login-callback just directs the user back to /, ignoring the original returnUri.

This works in Popup mode. It does not work in redirect mode, either specified manually, or as a fallback for a broken popup mode.

AuthorizationService.ts looks like it's supposed to be retrieving the original returnUri from sessionStorage. However, retrieveState is never actually called from completeSignIn.

However, it was in 3.1. So, this seems like a regression.

**Comment by jspuij** [comment]
Yeah I was the one who helped @wasabii diagnose this one. It seems that the msal 2.0 migration removed the call to `retrieveState`  in
https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Authentication.Msal/src/Interop/AuthenticationService.ts

in this commit:

https://github.com/dotnet/aspnetcore/commit/ecf2a23d3d3ebe18dbfc558a50a7255445c166d0#diff-e93d88646a9c7b8accad9fd0d381af964d3f5e6bba9d4e72c22f602565a3c4cc

But it could be that I'm mistaken. Anyway it's a bug and a regression from the 3.2 version of webassembly

@javiercn @captainsafia This seems to be your areas of expertise.
