### ISSUE TITLE
Issues when using DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS and DangerousInlinePipeScheduling

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [dotnet/aspnetcore#28356]
Giving some feedback as per @davidfowl request from twitter.

Enabling both options gave my app a ridiculous performance boost (2-3x), i think most gains come from not enqueuing in the threadpool, most of the cpu usage is now on the `SocketAsyncEngine` threads. (more on this issue at dotnet/runtime#44449).

The problem that i came across is that after some time, the app would die with timeouts from everything that was using a socket.
My guess is that something is deadlocking on the `SocketAsyncEngine` threads, killing one by one until all threads were blocked.
After chasing every line of code that could be the culprit, i managed to make it stable long enough that i saw this problem on one machine out of 100s once a week, but its still there. My guess is that now something on a third party lib (this app uses postgres) or maybe even the BCL (i think dns is still sync?) could be the culprit.

**Comment by davidfowl** [comment]
Yea, if something blocks, you're kinda basically hosed, that's why there's that big doc comment about the setting 😄. Once the issue starts happening, I'd suggest capturing a dump.

**Comment by Rodrigo-Andrade** [comment]
I tried a mini-dump, didn't work, next time this happens i'll try again and if it fails, ill open another issue on the dotnet-dump.

But to this app, the performance gained justifies the trouble, and most of this hangs are actually bugs.

**Comment by jkotalik** [comment]
@Rodrigo-Andrade sounds like you are working through your issues. Closing for now, feel free to reopen if you find an issue you believe is with the framework.
