### ISSUE TITLE
Upgrade Caching.RedisStackExchange to refer to Redis.StackExchange 2.1

### ISSUE THREAD

**Issue by jouniheikniemi** [dotnet/aspnetcore#28369]
Redis.StackExchange v2.0.593+ have an issue with connectivity to the Redis cluster randomly dying if there's a transient network error (until an AppDomain restart). See https://github.com/StackExchange/StackExchange.Redis/pull/1374 and https://github.com/StackExchange/StackExchange.Redis/issues/1120. These issues are fixed in 2.1. 

It would probably make sense to release a version with an upgraded dependency, as this issue seems to be particularly bothering users with Azure Redis clusters.

**Comment by shat90** [comment]
Hello, I was hoping to get the upgrade done - but the version.details mentions using the Darc utility to upgrade existing . I tried following the [markdown](https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#setting-up-your-darc-client ) here- but it seems that the link is broken to join the arcade-contrib group which is required for one to get the BAR password generated. 

Please let me know if I am on the wrong trail here

**Comment by BrennanConroy** [comment]
This would involve updating the entry under the "manual" section which does not make use of darc
https://github.com/dotnet/aspnetcore/blob/ed68ce72bd3c1cebe7f3b2697ac6b05a0b688b31/eng/Versions.props#L162

**Comment by shat90** [comment]
If thats the only change  - it seems pretty trivial , I can PR it

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/32239
