### ISSUE TITLE
Enable multi-threaded WASM runtime 

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#28360]
**Update (by @SteveSandersonMS)** This issue tracks the longer-term goal of having a true multi-threaded runtime on WebAssembly. This is not part of the roadmap for .NET 6 because not all browsers will yet support it, and there's a lot of work to do in the underlying runtime to support it.

---

We should start playing with this as soon as it's available (even if we need to hack some things together) to identify any potential issues early.

Part of # https://github.com/dotnet/aspnetcore/issues/17730

**Comment by mkArtakMSFT** [comment]
Moved to `Backlog` as the support for multi-threading won't be coming in 6.0.

**Comment by ElanHasson** [comment]
I've been thinking about this-- do you think it makes sense to have a custom TaskScheduler (like [Orleans](https://dotnet.github.io/orleans/docs/implementation/scheduler.html) that essentially schedules work to run in either a in a pthread or a web worker ?
