### ISSUE TITLE
"Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" with .Net 5.0 blazor webassembly in VS 2019 gives NETSDK1082

### ISSUE THREAD

**Issue by wiwichu** [dotnet/aspnetcore#28362]
If I use Nuget "Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" with .Net 5.0 blazor webassembly in VS 2019  Version 16.8.2 I get the following error on clean: NETSDK1082 There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

I created a brand new blazor webassembly .Net 5.0 project. The issue occurs when I include an openidconnect reference, but disappears if I delete that reference.

**Comment by javiercn** [comment]
@wiwichu thanks for contacting us.

`Microsoft.AspNetCore.Authentication.OpenIdConnect` is not designed to work on the browser, hence why you are seeing that error.

Check the docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio) for details on how to authenticate on Blazor webassembly.

**Comment by wiwichu** [comment]
I have actually set up an IDP (Identity Provider) and am able to authenticate, but what I want to do is after getting claims from the IDP, make a call to the app's API and get more app specific claims to merge with those from the IDP. This approach is described in a Pluralsight course by Kevin Dockx  [https://app.pluralsight.com/library/courses/dealing-credentials-when-securing-aspdotnet-core-3-application/table-of-contents](url). It uses Microsoft.AspNetCore.Authentication.OpenIdConnect, but the client is not Blazor. Do you know how I might implement this approach with a Blazor client?

Thanks,

PAtrick
