### ISSUE TITLE
Sql Cache In-Memory OLTP?

### ISSUE THREAD

**Issue by dauger** [dotnet/aspnetcore#28378]
Has having the option of using Sql Server 2014's in-memory OLTP instead of traditional tables been evaluated? It seems like it might be a good fit for a cache, but I'll admit that I have not done a deep dive on in-memory OLTP's capabilities & restrictions yet.

**Comment by davidfowl** [comment]
This isn't something we plan to do but feel free to use the implementation from here https://github.com/dotnet/aspnetcore/issues/28378#issuecomment-598336464

**Comment by xantari** [comment]
@davidfowl Any chance of reconsidering? The only change you need to make to the SQL Server distributed cache provider you deliver today is to change from DateTimeOffset to DateTime2 at the database level and it would work for both in memory tables as well as physical storage based tables.

**Comment by davidfowl** [comment]
That sounds fine, but we don't test it, so we won't know when it breaks.
