### ISSUE TITLE
[RedisCache] Allow injection of ConnectionMultiplexer

### ISSUE THREAD

**Issue by epignosisx** [dotnet/aspnetcore#28379]
Currently the ```RedisCache``` creates the ```ConnectionMultiplexer``` and does not allow access to it. This prevents the application from reusing the ```ConnectionMultiplexer``` for other operations like PubSub.

Granted, the application could create another ```ConnectionMultiplexer```, but the recommendation is to have only one per application.

I was thinking if it would be possible to have a separate constructor for ```RedisCache``` that would receive the ```ConnectionMultiplexer```. I understand that so far **Microsoft.Extensions.Caching.Redis** did not leak any implementation details about its usage of **StackExchange.Redis**. However, I noticed that **Microsoft.AspNetCore.DataProtection.Redis** leaks **StackExchange.Redis** [types here](https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection.Redis/RedisXmlRepository.cs#L26). So, I'm unclear about how you feel about keeping **StackExchange.Redis** as an implementation detail.

## Proposed API

```diff
namespace Microsoft.Extensions.Caching.StackExchangeRedis
{
    public class RedisCacheOptions
    {
+       Func<IConnectionMultiplexer> ConnectionMultiplexerFactory { get; set; }     
    }
```

**Comment by napalm684** [comment]
This is needed badly. If you use Redis with OIDC as the ticket store `IDistributedCache` is required. However, if you then need to run on multiple machines in a non-sticky load balanced situation, then you are forced to use data protection sharing via `PersistKeysToStackExchangeRedis` which takes a `ConnectionMultiplexer` and is only accessible via private reflection as mentioned above. Can we at least get some parity/consistency? If Data Protection functionality for Redis cannot use `IDistributedCache` then we need a way to get the multiplexer out of it in order to follow best practices and use the connection as a singleton.

**Comment by jjxtra** [comment]
I just don't understand the hesitation to expose `IConnectionMultiplexer` or an `IConnectionMultiplexerProvider` - as long as stack exchange redis is a dependent nuget package this seems safe. If for some reason a new redis provider or nuget was used, then there should be a compile error, easy to detect the problem at build time.

**Comment by davidfowl** [comment]
I think we'd make it an option instead, that seems simple enough. Make a formal API proposal and we can take it through the process.

**Comment by jjxtra** [comment]
I'm happy to do this, where do I submit the api proposal?

**Comment by alrz** [comment]
Linking to my comment in a dup https://github.com/dotnet/aspnetcore/issues/30342#issuecomment-783144405

I really do wish a full-blown API for this. IConnectionMultiplexer injection would do but it would be nice to make it a selfcontained API.

**Comment by davidfowl** [comment]
> I'm happy to do this, where do I submit the api proposal?

The API proposal template is in the new issue template. The proposal should have an addition to RedisOptions that adds the connection multiplexer, or more likely a factory for one. The rest of the template should be straight forward.

**Comment by jjxtra** [comment]
The full blown api piece is tricky. The connection multiplexer and the database it exposes have a TON of methods. What most people want is just direct access to redis through the stackexchange api. So the lowest hanging fruit by far is to just provide an option to expose that directly.

**Comment by alrz** [comment]
Good thing about HttpClientFactory API that I mentined is that it manages all the instances by itself. 

I suppose this still doesn't resolve excessive number of connections where redis can't handle.  8 workers in 4 servers each making a connection brings redis down.

**Comment by jjxtra** [comment]
I feel like this issue represents the feature. As far as an API, I would think just injecting an `IConnectionMultiplexerProvider` by default would not hurt anything. If someone never asks for it, they never know about it. No need to add an option to turn this off or on.

```cs
public interface IConnectionMultiplexerProvider
{
    // the implementation would do the right thing and ensure a singleton connection multiplexer is returned, or
    //  throw an exception if the connection multiplexer is null and not yet able to connect
    public IConnectionMultiplexer GetConnectionMultiplexer();
}
```

**Comment by davidfowl** [comment]
I don't think that should be the API. Why not just modify the existing options object like so:

```diff
public class RedisCacheOptions
{
+   Func<IConnectionMultiplexer> ConnectionMultiplexerFactory { get; set; }
}
```

**Comment by jjxtra** [comment]
How would this hook into the internal guts of the Microsoft and Stackexchange nugets? The whole point is for the provider/factory to be implemented by Microsoft and available if asked for. Then no configuration changes are needed. If the factory is never asked for or injected, it will never be created and behavior will remain same as it is today.

**Comment by davidfowl** [comment]
if the factory is null (which it will be by default) then it won't be used. Was that the question?

**Comment by jjxtra** [comment]
No. The question is why do we need a factory property on the options at all? Couldn't the Microsoft nuget package provider the factory interface and then the user of the nuget could inject that interface into a constructor if desired...

**Comment by davidfowl** [comment]
Because it's functionally equivalent, more discoverable, and doesn't introduce a new type.

**Comment by jjxtra** [comment]
Can you give an example of how a caller might implement such a factory?

**Comment by jjxtra** [comment]
Also, introducing a new type is a non-issue and could be done in a minor version nuget update, i.e. 1.X.0.

**Comment by adamhathcock** [comment]
> Can you give an example of how a caller might implement such a factory?

It's literally on RedisCache already how to make a mulitplexer (as well as the internet in general).  This option would allow you to override it with your own implementation if desired:
https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs#L228

I previously made a full type to manage a pool of mulitplexers but have since walked back on that implementation.  Having this simple Func is all I need.

**Comment by napalm684** [comment]
I would love to assist with this if I can?

**Comment by davidfowl** [comment]
@napalm684 I've updated the original issue with an API proposal. We'll review the API, you can prepare a PR in the meantime or wait for final approval.

**Comment by napalm684** [comment]
@davidfowl I guess I'm a little confused what the factory provides when the property is already private on that class if I recall correctly. Is there and example of this I could reference?

**Comment by davidfowl** [comment]
> @davidfowl I guess I'm a little confused what the factory provides when the property is already private on that class if I recall correctly. Is there an example of this I could reference?

The options could have a `ConnectionMultiplexer` instance instead of a `Func<ConnectionMultiplexer>` (if that's what people need). I assume the use case for this is to potentially reduce the number of connections to redis in the application, so we'd also need a way to know if we should be making a connection or not.

**Comment by jjxtra** [comment]
Putting the burden on the application to create and pass a connection multiplexer in the options would add un-needed complexity. Now the client has to know how to create this type properly and connect, which can be error prone if not done right.

Being able to inject `IConnectionMultiplexer` into a constructor automatically should be all that is needed, since the Microsoft frameworks already have this created under the hood. The public interface of the nuget packages need not change, since they already reference the stack exchange nuget.

**Comment by davidfowl** [comment]
They can inject the multiplexer trivially if that's what they want to do and apply it to the options. We generally don't like assuming the services that are in the container should be automagically consumed by components, especially when they are optional. The API above is the standard pattern introduced in all *extensions* and ASP.NET Core APIs for configurability.

**Comment by napalm684** [comment]
Is there a process to take this? I would like to make a PR if someone hasn't already.

**Comment by davidfowl** [comment]
We're gonna discuss the API next week and then you can send the PR

**Comment by napalm684** [comment]
Awesome will you post the result of the discussion here and then I can submit?

**Comment by napalm684** [comment]
So I took a stab in this PR https://github.com/dotnet/aspnetcore/pull/31879 . I would like some feedback (whether I did this properly - first timer here) and am willing to assist in whatever way necessary to apply feedback.

**Comment by napalm684** [comment]
@davidfowl any word on the api design discussion? If things didn't change my PR is still out there. Otherwise let's talk about updates/feedback?  Thanks!

**Comment by pranavkm** [comment]
Additional API feedback provided in the PR

**Comment by napalm684** [comment]
> Additional API feedback provided in the PR

I commented in the PR @pranavkm let's talk about a few things please.

**Comment by napalm684** [comment]
With the merge of PR https://github.com/dotnet/aspnetcore/pull/32266 can this be closed?

**Comment by JunTaoLuo** [comment]
Yup, thanks for the contribution @napalm684 !

**Comment by RehanSaeed** [comment]
I've registered `IConnectionMultiplexer` in IoC. The Hot Chocolate GraphQL server allows you to resolve `IConnectionMultiplexer` from IoC like so:

```cs
builder.AddRedisQueryStorage(x => x.GetApplicationServices().GetRequiredService<IConnectionMultiplexer>().GetDatabase());
builder.AddRedisSubscriptions(x => x.GetRequiredService<IConnectionMultiplexer>());
```

I've also raised an issue in Xabril health checks to do something similar in https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/750:

```cs
services
    .AddHealthChecks()
    .AddRedis(sp => sp.GetRequiredService<IConnectionMultiplexer>());
```

Can this be a supported scenario for the `IDistributedCache` also? Setting up Redis in three different ways is not ideal.
