### ISSUE TITLE
HMSET is deprecated, but used by Microsoft.Extensions.Caching.StackExchangeRedis

### ISSUE THREAD

**Issue by dipakyadav** [dotnet/aspnetcore#28371]
As per Redis 4.0.0, HMSET is considered deprecated. Please use HSET in new code.
As of Redis 4.0.0, HSET is variadic and allows for multiple field/value pairs.

**Comment by shat90** [comment]
Created a PR changing that - seems to be the only usage.

**Comment by udlose** [comment]
@JunTaoLuo any idea when this update will be available?  TIA

**Comment by BrennanConroy** [comment]
I should be available in preview 1 which has been published.

Closing as this should be done.

**Comment by udlose** [comment]
wow, this is pushed out to .NET 6? Nothing before then?
