### ISSUE TITLE
crit: Microsoft.AspNetCore.Server.Kestrel[0]       Unable to start Kestrel.       System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

### ISSUE THREAD

**Issue by RaniRahate** [dotnet/aspnetcore#28399]
# Issue Title

Be as descriptive as you can with your title.

# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by javiercn** [comment]
@RaniRahate thanks for contacting us.

Can you provide details on the ASP.NET Core version you are using, as well as the SDK and check if running `dotnet dev-certs https --clean; dotnet dev-certs https --trust` from within the command line solves your problem?

**Comment by RaniRahate** [comment]
> @RaniRahate thanks for contacting us.
> 
> Can you provide details on the ASP.NET Core version you are using, as well as the SDK and check if running `dotnet dev-certs https --clean; dotnet dev-certs https --trust` from within the command line solves your problem?



.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by RaniRahate** [comment]
Tried  this commans dotnet dev-certs https --clean; dotnet dev-certs https
--trust  still having same issue. following are the version details

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program
Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program
Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program
Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program
Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program
Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program
Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jkotalik** [comment]
Can you obtain the output from  `dotnet dev-certs https --clean`, `dotnet dev-certs https`, and `dotnet dev-certs https --trust` in that order?

Can you also obtain the rest of the logs coming from the server?

**Comment by RaniRahate** [comment]
Tried  commands in this order  dotnet dev-certs https --clean, dotnet
dev-certs https, and dotnet dev-certs https --trust
still getting error



S C:\DatingApp\api> dotnet run
Building...
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.InvalidOperationException: Unable to configure HTTPS endpoint.
No server certificate was specified, and the default developer certificate
could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To
trust the certificate (Windows and macOS only) run 'dotnet dev-certs https
--trust'.
      For more information on configuring HTTPS see
https://go.microsoft.com/fwlink/?linkid=848054.
         at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions, Action`1 configureOptions)
         at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext
context)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1
listenOptions, AddressBindContext context)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken
cancellationToken)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1
application, CancellationToken cancellationToken)
Unhandled exception. System.InvalidOperationException: Unable to configure
HTTPS endpoint. No server certificate was specified, and the default
developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust
the certificate (Windows and macOS only) run 'dotnet dev-certs https
--trust'.For more information on configuring HTTPS see
https://go.microsoft.com/fwlink/?linkid=848054.
   at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions, Action`1 configureOptions)
   at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions)
   at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1
listenOptions, AddressBindContext context)
   at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken
cancellationToken)
)
   at
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken
cancellationToken)
   at
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost
host, CancellationToken token)
   at
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost
host, CancellationToken token)
   at Api.Program.Main(String[] args) in C:\DatingApp\API\Program.cs:line 16
PS C:\DatingApp\api> dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. A prompt might
get displayed to confirm the removal of some of the certificates.
HTTPS development certificates successfully removed from the machine.
PS C:\DatingApp\api> dotnet dev-certs https
The HTTPS developer certificate was generated successfully.
PS C:\DatingApp\api> dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. A confirmation
prompt will be displayed if the certificate was not previously trusted.
Click yes on the prompt to trust the certificate.
The HTTPS developer certificate was generated successfully.
PS C:\DatingApp\api> dotnet run
Building...
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.InvalidOperationException: Unable to configure HTTPS endpoint.
No server certificate was specified, and the default developer certificate
could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To
trust the certificate (Windows and macOS only) run 'dotnet dev-certs https
--trust'.
      For more information on configuring HTTPS see
https://go.microsoft.com/fwlink/?linkid=848054.
         at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions, Action`1 configureOptions)
         at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext
context)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1
listenOptions, AddressBindContext context)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken
cancellationToken)
         at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1
application, CancellationToken cancellationToken)
Unhandled exception. System.InvalidOperationException: Unable to configure
HTTPS endpoint. No server certificate was specified, and the default
developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust
the certificate (Windows and macOS only) run 'dotnet dev-certs https
--trust'.For more information on configuring HTTPS see
https://go.microsoft.com/fwlink/?linkid=848054.
   at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions, Action`1 configureOptions)
   at
Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions
listenOptions)
   at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext
context)
   at
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1
listenOptions, AddressBindContext context)
   at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken
cancellationToken)
   at
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1
application, CancellationToken cancellationToken)
   at
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken
cancellationToken)
   at
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken
cancellationToken)
   at
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost
host, CancellationToken token)
   at
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost
host, CancellationToken token)
   at
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost
host)
   at Api.Program.Main(String[] args) in C:\DatingApp\API\Program.cs:line 16
PS C:\DatingApp\api>

**Comment by BrennanConroy** [comment]
Could you share the csproj of your app?

**Comment by RaniRahate** [comment]
> Could you share the csproj of your app?

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

</Project>

**Comment by RaniRahate** [comment]
> Could you share the csproj of your app?

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

</Project>

**Comment by RaniRahate** [comment]
> Could you share the csproj of your app?
![Untitled](https://user-images.githubusercontent.com/45615903/101415314-adbcce00-38b5-11eb-8259-153b204ea78f.png)
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

</Project>

**Comment by mehrshadFarzaneh** [comment]
I have this problem now

**Comment by BrennanConroy** [comment]
Can you open certmgr.msc and look at the cert under Personal > Certificates
![image](https://user-images.githubusercontent.com/7574801/101689864-014c2a80-3a22-11eb-9858-278ab9387bdf.png)

**Comment by RaniRahate** [comment]
> Can you open certmgr.msc and look at the cert under Personal > Certificates
> ![image](https://user-images.githubusercontent.com/7574801/101689864-014c2a80-3a22-11eb-9858-278ab9387bdf.png)

Hi Brennan ,
Thank you so much for all your help.When I open certmgr.msc ,there were lot of certificate copies generated for localhost.
I deleted all and again generated by using commands dotnet dev-certs https and dotnet dev-certs https --trust. 
My problem has been solved because of you. Thank you so much again .I really appreciate it.
