### ISSUE TITLE
Add out-of-proc test for request queue delegation

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#28396]
All the Http.Sys tests only verify delegating requests between two different Http.Sys queues in the same process. There are some behavioral differences (such as https://github.com/dotnet/aspnetcore/pull/28336 ) that it would be good to validate

**Comment by adityamandaleeka** [comment]
We should be able to get this in for 6 since test-only changes have a bit more runway.

**Comment by shirhatti** [comment]
How do I write an out-of-proc test? @Tratcher is there a comparable test I can look at?

**Comment by Tratcher** [comment]
Start here: https://github.com/dotnet/aspnetcore/blob/main/src/Servers/test/FunctionalTests/HelloWorldTest.cs

**Comment by Tratcher** [comment]
Or here: https://github.com/dotnet/aspnetcore/blob/a9986c33a51f5ceda5854cbfc8969f4c9079caf7/src/Hosting/test/FunctionalTests/ShutdownTests.cs#L57
