### ISSUE TITLE
`build.cmd` always fails locally

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#28394]
Running build.cmd fails for me locally now after https://github.com/dotnet/aspnetcore/commit/5fd1db26257c4154fd59fef99bedfde3fa3ad697 was merged.

```
C:\Users\jukotali\code\aspnetcore\Directory.Build.targets(155,5): error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkVersion('$(DefaultNetCoreTargetFramework)', 2)". Method '[MSBuild]::GetTargetFrameworkVersion' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. [C:\Users\jukotali\code\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj]
```

https://github.com/dotnet/aspnetcore/blame/master/Directory.Build.targets#L155

I'd imagine this is a difference between msbuild versions between native projects and dotnet projects. Also maybe a skip condition for native projects could be added here?

cc @dotnet/aspnet-build

**Comment by wtgodbe** [comment]
Yeah, I think this is related to the msbuild version on your box - I remember seeing desktop msbuild-related issues w/ the use of `GetTargetFrameworkVersion` in the past. @rainersigwald do you know exactly what the requirement is?

**Comment by wtgodbe** [comment]
CC @dougbu

**Comment by dougbu** [comment]
Our build now requires VS 16.8. That's been out for a few weeks now -- long enough to reach the main VS2019 build machines. Upgrade and you'll be fine @jkotalik

**Comment by jkotalik** [comment]
Do you know the order of precedence between VS preview and VS? My VS build is 16.9-preview, so I assume that would have been valid here if used.

**Comment by rainersigwald** [comment]
It's sometimes possible for MSBuild `X.{N}` to have changes that aren't in `X.{N+1}-preview`, depending on branching and release timelines, but it's fairly rare and should not be the case for this particular method. What is the output of `msbuild -version` when you're seeing this failure?

**Comment by jkotalik** [comment]
I already installed 16.8, so this doesn't repro anymore. I also don't have msbuild on my path, so `msbuild -version` says it isn't recognized as a command. Is the goal to figure out which msbuild takes precedence? 

At the time of repro, I had 16.9-preview1 and 16.7.x on my machine. After installing 16.8.2, this issue was resolved.

**Comment by rainersigwald** [comment]
Sounds like something was detecting "latest full release" instead of "latest prerelease" and using the 16.7 copy of MSBuild.

**Comment by jkotalik** [comment]
Yeah that'd be my guess 😄

**Comment by dougbu** [comment]
>> Sounds like something was detecting "latest full release" instead of "latest prerelease" and using the 16.7 copy of MSBuild.

> Yeah that'd be my guess 😄

I'd guess the 16.0-preview1 installation lacked or lacks one or more of the requirements listed in our global.json file. Arcade turns that into e.g. `-requires Microsoft.VisualStudio.Component.VC.ATL` on the `vswhere.exe` command line.

That said, we should probably bump the VS version in global.json to 16.8 now that's released.
