### ISSUE TITLE
Identity: Scaffolded ResendEmailConfirmation page has incorrect ModelError description when email is not found

### ISSUE THREAD

**Issue by bairog** [dotnet/aspnetcore#28402]
### Describe the bug
Inside scaffolded **ResendEmailConfirmation.cshtml.cs** when `_userManager.FindByEmailAsync(Input.Email)` finds no user a ModelError is generated with in correct decription - `ModelState.AddModelError(string.Empty, "Verification email sent. Please check your email."); `. To my mind it should be something like `$"Email '{Input.Email}' was not found!"`

### To Reproduce

1. Create a new ASP.NET Core Web Application
- Web Application (Model-View-Controller)
- Authentication: Individual User Accounts
2. In the Solution Explorer, right click, select "Add" then "New Scaffolded Item..."
- Choose "Identity"
- Choose "Override all files".
3. Open **ResendEmailConfirmation.cshtml.cs**. Code for `public async Task<IActionResult> OnPostAsync()` there is:

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByEmailAsync(Input.Email);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Verification email sent. Please check your email.");
                return Page();
            }

            var userId = await _userManager.GetUserIdAsync(user);
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            .....

To my mind that is incorrect ModelError description - it should be something like `$"Email '{Input.Email}' was not found!"`

### Further technical details
- ASP.NET Core version 5.0
- Visual Studio 2019 version 16.8.2

**Comment by bairog** [comment]
Inside **ResetPassword.cshtml.cs** inside `public async Task<IActionResult> OnPostAsync()` there is:

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByEmailAsync(Input.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToPage("./ResetPasswordConfirmation");
            }

            var result = await _userManager.ResetPasswordAsync(user, Input.Code, Input.Password);
            .....
So is that description inside **ResendEmailConfirmation.cshtml.cs** is also intended for not to reveal that the user does not exist?
If that is a good practice - were can I find some more info? 
Anyway to my mind it's better to place the same commentary in **ResendEmailConfirmation.cshtml.cs** file:

     if (user == null)
     {
         // Don't reveal that the user does not exist - docs.microsoft.com/????
         ModelState.AddModelError(string.Empty, "Verification email sent. Please check your email.");
         return Page();
     }

**Comment by blowdart** [comment]
This is on purpose, and best practice, to avoid enumeration of registered emails.  If you'd like to submit a PR adding that comment we'd welcome it.

**Comment by bairog** [comment]
@blowdart to create PR I need to create a new branch first. 
But pushing a new branch to repository results in **Access denied** for me.

**Comment by blowdart** [comment]
@pranavkm do we have instructions anywhere for getting started?

**Comment by bairog** [comment]
@blowdart @pranavkm Any firther instrucions? Pushing a new branch to repository still results in **Access denied** for me.

**Comment by blowdart** [comment]
You can't push to us, you need to issue a pull request, with links to the issue in the pr comments

**Comment by bairog** [comment]
Well, I'm clicking green **New Pull Request** button at https://github.com/dotnet/aspnetcore/pulls and I get the page:
![image](https://user-images.githubusercontent.com/44995181/101354146-befdde80-38a5-11eb-977f-f5a0a8e576c9.png)
where I am to select a branch to make a pull request.
What should I do there if I cannot push to your repository i.e. cannot create a branch for a pull request?

**Comment by blowdart** [comment]
I leave this to others for help as I've been on vacation all month and will remain so until the new year.

Tagging @mkArtakMSFT too.

**Comment by bairog** [comment]
@pranavkm  @mkArtakMSFT Any firther instrucions? I still cannot make PR as @blowdart adviced me.

**Comment by pranavkm** [comment]
Have you had a chance to look at our contributing guidelines: https://github.com/dotnet/aspnetcore/blob/master/CONTRIBUTING.md?
