### ISSUE TITLE
Expose Socket via a Kestrel ConnectionContext feature

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#28401]
### Is your feature request related to a problem? Please describe.

We should make it so you don't have to resort to something like the following to access the managed Socket if you really want to.

```C#
var socket = (Socket)connectionContext.GetType().GetField("_socket", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(connectionContext);
```

## Proposed API

```diff
using System.Net.Sockets;

namespace Microsoft.AspNetCore.Connections.Features
{
+    public interface IConnectionSocketFeature
+   {
+        Socket? Socket { get; }
+    }
}
```

## Usage Examples

```C#
var socket = connectionContext.Features.Get<IConnectionSocketFeature>().Socket;
```

**Comment by BrennanConroy** [comment]
What are examples of usage for this? What settings do you want after creation of the socket?

**Comment by BrennanConroy** [comment]
> What are examples of usage for this?

Force a reset.

**Comment by davidfowl** [comment]
Another use case that came up this week was the ability to get tcp information via a new ioctl `SIO_TCP_INFO` https://docs.microsoft.com/en-us/windows/win32/winsock/sio-tcp-info.

**Comment by pranavkm** [comment]
## Proposed API

```diff
using System.Net.Sockets;

namespace Microsoft.AspNetCore.Connections.Features
{
+    public interface IConnectionSocketFeature
+   {
+        Socket Socket { get; }
+    }
}
```

## Usage Examples

```C#
var socket = connectionContext.Features.Get<IConnectionSocketFeature>()?.Socket;
if (socket is {} nonNullSocket}
```
