### ISSUE TITLE
Blazor webassembly - SetParametersAsync calling twice on loading of the app.

### ISSUE THREAD

**Issue by rajeshaz09** [dotnet/aspnetcore#28412]
### Describe the bug
MainLayout's **SetParametersAsync** and **OnParametersSetAsync** events are raising twice during initial launch.

### To Reproduce
Check this repository https://github.com/rajeshaz09/BlazorDemo
When launching default (index) page, output showing as

```
MainLayout - SetParametersAsync
MainLayout - OnInitializedAsync
MainLayout - OnParametersSetAsync
MainLayout - SetParametersAsync
MainLayout - OnParametersSetAsync
```

### Further technical details
- .NET 5.0
- VS 2019 16.8.1
- Blazore - Webassembly

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
