### ISSUE TITLE
Performance tests for HTTP/3

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#28429]
Performance tests will be critical for guaranteeing that HTTP/3 performs as well as HTTP/2 for many scenarios. Getting this ramped up as soon as possible will allow us to identify bottlenecks and/or asks for the msquic team.

To ship in 6.0, we should ideally see plaintext request per second numbers around the same performance as HTTP/2 with HTTPS enabled.

Other metrics which will be important to track are JSON and connection establishment/close time.

We also need to think about our client load generator. Right now, wrk doesn't support HTTP/3, so either we need to write a client load generator or see if another one exists for HTTP/3.

**Comment by JamesNK** [comment]
> We also need to think about our client load generator. Right now, wrk doesn't support HTTP/3, so either we need to write a client load generator or see if another one exists for HTTP/3.

For gRPC perf on HTTP/3 I'll update Grpc.Net.Client to support HTTP/3. Grpc.Net.Client uses HttpClient internally.

@sebastienros HTTP/3 on Windows currently requires fast-ring insiders build - https://github.com/dotnet/runtimelab/tree/feature/System.Net.Experimental.MsQuic#usage. What is required to get the perf enviornment using this OS version?

**Comment by adityamandaleeka** [comment]
Right now we only have gRPC benchmarks. We should add a GET one.

**Comment by JamesNK** [comment]
I'm going to close this:
1. Networking team has written QUIC benchmarks
2. Networking team has written HTTP/3 benchmarks
3. We have gRPC benchmarks

If we decide need more in the future than we can re-open (or just go ahead and add them)
