### ISSUE TITLE
SPA (Angular) Logout logic bug

### ISSUE THREAD

**Issue by kdubious** [dotnet/aspnetcore#28421]
### Describe the bug
Clicking "Logout" results in: The logout was not initiated from within the page. The check for internal navigation versus external navigation to the logout page is flawed, in my setup at least.

### To Reproduce

1. Login.
2. Navigate to an internal Angular page.
3. Click "Logout"

``` if (!!window.history.state.local) ```

should probably be:

``` if (window.history.state.navigationId > 1) ```

### Further technical details
- ASP.NET Core version = 5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
