### ISSUE TITLE
Add a project template for ASP.NET GraphQL

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28423]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-a-project-template-for-ASPNET-Graph/1249620?preview=true)._

---
<p>It would be a great addition to have a Visual Studio project template for ASP.NET with GraphQL.</p>

---
#### Feedback Bot on 11/11/2020, 00:54 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We don't plan to add GraphQL support in ASP.NET Core at this point.
