### ISSUE TITLE
Support MaxKeepAliveRequests in Kestrel

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28428]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/500655/support-maxkeepaliverequests-in-kestrel.html)._

---
<p>For hosting asp.net core, we could host in `Kestrel` or `Kestrel with a reverse proxy`. For `Apache`, it contains the feature `MaxKeepAliveRequests` to contol the max keep alive requests. For [KestrelServerLimits](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits?view=aspnetcore-2.2). There is no such settings in `Kestrel`, and suggest to check wether it is possible in `Kestrel`.</p>

---
#### Jane Wu [MSFT] on 3/20/2019, 10:52 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by BrennanConroy** [comment]
Kestrel does not have this feature.

Could you explain the scenario that you want this for?

Triage:
http://httpd.apache.org/docs/2.2/mod/core.html#maxkeepaliverequests
design to limit session fixation
