### ISSUE TITLE
Handle DataTimeOffset while binding in asp.net core

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28425]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/489078/handle-datatimeoffset-while-binding-in-aspnet-core.html)._

---
<p>I have a model like</p><pre>class MyModel{
    public DateTimeOffset plannedStartDate {get;set;}
}
</pre><p>And, I submit the data like </p><pre><code>{    plannedStartDate:2019-03-04T16:00:00.000Z}</code></pre><p>Action  </p><pre>[HttpPost]
public IActionResult Get(MyModel activityUpdate){
}
</pre><p>I got wrong value for &quot;plannedStartDate&quot; which is not offset date.</p><p>Detail discussion:</p><h1></h1><p><a href="https://stackoverflow.com/questions/55015041/datetimeoffset-in-the-asp-net-core-api-model" target=_blank>datetimeoffset in the asp.net core api model</a></p><p></p><p></p>

---
#### Jane Wu [MSFT] on 3/14/2019, 02:20 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We recommend using the default formatter, which has support for DateTimeOffset baked in.
