### ISSUE TITLE
Command line (console app) scaffolder

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28424]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/727906/command-line-console-app-scaffolder.html)._

---

With ASP.NET Core there is a given possibility to generate automatically a new element. (Controler/Views)

In almost every MVC project I build some sort of command line utility program mostly for administration purpose that do not require a complex IHM (I'm not a regular .NET user). Such a tool requires the same context as the application (authentification/authorization, db context and DI for accessing services ). 

It could be generated automatically, with given arguments optional or not and some kind of auto-build documentation based upon code conventions, in order to provide the technical user with a console application tool in minutes.

---
#### Jane Wu [MSFT] on 9/9/2019, 11:15 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
