### ISSUE TITLE
Use stub msquic for functional tests (CI)

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#28427]
Right now there are limitations with CI machines not having TLS support for HTTP/3. A work around would be to use the stubbed version of msquic, which ignores TLS, for functional testing. 

As a first step, I think writing a functional test with HttpClient and Kestrel using stub msquic would be a good first step.

Afterwards, we can extend the test suite to either add more HttpClient tests or adding tests that are similar to the in memory functional tests using msquic instead of pipes.

**Comment by JamesNK** [comment]
No plan to test against a stub msquic. HTTP/3 tests will be against in-memory pipes. Plan to use real msquic to test our QUIC transport.
