### ISSUE TITLE
Stress tests for HTTP/3

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#28430]
One area we lacked in for HTTP/2 was stress tests initially. The runtime team wrote a [stress test suite](https://github.com/dotnet/runtime/tree/master/src/libraries/System.Net.Http/tests/StressTests/HttpStress), which ended up finding a stress bug in our HTTP/2 code for 3.0.

While perf tests get some of the main stress scenarios done, additional stress tests that have targeted scenarios, like aborting the stream or connection early, will help a ton in finding outstanding stress issues.

**Comment by adityamandaleeka** [comment]
We have the gRPC benchmarks running nightly now, and some stress coverage on the client side. Closing this.
