### ISSUE TITLE
Blazor WebAssembly always find resources over https .Net5

### ISSUE THREAD

**Issue by psibajacr** [dotnet/aspnetcore#28448]
Hi everyone, 
I'm having some throubles when deploy my Webassembly App into my IIS server. 
By client's requirements the application needs to be accesed over http, when the application is requested the index.html is displayed, however, all the application resources are requested over https and this is cause an ERR_SSL_PROTOCOL_ERROR

![Captura](https://user-images.githubusercontent.com/46540327/101247891-8dd4b100-36e1-11eb-9c4a-da95bf0cd8cc.PNG)

Is any way to make it works?

Thanks in advance.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
