### ISSUE TITLE
Read json data from web api httppost body

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28442]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Read-json-data-from-web-api-httppost-bod/1267771)._

---
So I have a simple requirement to gather logging data from a WASM client into a Web API.

**NOTE we are not using Entity Framework...**

I have created the following class:

public class EventInformation
    {
        public string Location;
        public string Context;
        public int Severity = 1;
    }

With a simple web API target:

[Route("[controller]")]
    [ApiController]
    public class UserStateController : ControllerBase
    {

[HttpPost]
        [Route("LogEvent")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public IActionResult LogEvent([FromBody] EventInformation logData)
        {
            string Context = logData.Context;
            string Location = logData.Location;
            int Severity = logData.Severity;
            return Ok();
        }
    }

I run it with the swagger.. with this json payload

{
 "Context": "hello",
  "Location": "world",
  "Severity": 0
}

and get...

! [image.png] (https://aka.ms/dc/image?name=B79a6317af1324ab8a880c75970f2ddc7637418511419634176_20201124-164540-image.png&tid=79a6317af1324ab8a880c75970f2ddc7637418511419634176)

Runs to the break point all looks good except where is the data? Doesn't seem t be populating my logData parameter from my JSON body?

---
#### Feedback Bot on 11/24/2020, 10:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/25/2020, 07:19 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by pranavkm** [comment]
Your model has fields which System.Text.Json does not support by default. If this is 3.1, consider switching to using properties. When using 5.0, you could consider using a SerializerOptions if you must use fields in your model: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#include-fields
