### ISSUE TITLE
Running on .NET 5.0 now results in "A valid non-empty content root must be provided"

### ISSUE THREAD

**Issue by mmaguigan** [dotnet/aspnetcore#28440]
### Describe the bug
Since upgrading to .NET 5.0, I have noticed that when deploying a product as a single file executable to Alpine Linux and running it under a rootless container via podman, I get the following error now. I really hope Kestrel does not *require* a directory for static content now, I use Kestrel for lightweight services and am quite happy with the 404 for any path not routed.

```
Unhandled exception. System.ArgumentException: A valid non-empty content root must be provided. (Parameter 'contentRootPath')
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String contentRootPath, WebHostOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at NamespaceChanged.Program.RunAsync(Options options)
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at NamespaceChanged.Program.Main(String[] args)
   at NamespaceChanged.Program.<Main>(String[] args)
```

I should mention that I do not use ASP.NET Core beyond using the Kestrel web server. I use my routing library, `Routable` and handle requests directly. Routable's source is available [here](https://github.com/HardenedElements/routable), but basically it does not do anything except add a handler for requests, check if the request path is matches a known route and handle it if it does, if not, it gives back control to Kestrel which until now would merrily issue a 404 (or hand off to the next handler).

The initialization looks like this:

```csharp
using var server = new WebHostBuilder()
        .UseKestrel(kestrelOptions => kestrelOptions.ListenAnyIP(options.HttpPort))
        .Configure(appBuilder => appBuilder
                .UseRoutable(routable => routable
                        .AddRouting(new DefaultRouting(routable, options, profileManager))
                        .OnError(new KestrelRouting(routable) {
                                _ => _.Do((context, request, response) => {
                                        response.Status = 500;
                                        response.ClearPendingWrites();
                                        Log.Error(typeof(Program), $"A request encountered an unhandled exception.", context.Error);
                                })      
                        })      
                )       
        )       
        .Build();

using var cancellation = new CancellationTokenSource();
Console.CancelKeyPress += (_, e) => { 
        cancellation.Cancel();
        e.Cancel = true; 
};      

await server.RunAsync(cancellation.Token);
```

### Notes

* This does not occur when debugging on Windows using Visual Studio or running on Windows via `dotnet run`.
* The executable is published as follows: `dotnet publish -o publish/ -r linux-musl-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:IncludeNativeLibrariesForSelfExtract=true /p:IncludeAllContentForSelfExtract=true src/PROJECT_NAME`

(edit: cleaned up structure a bit, added note)

**Comment by davidfowl** [comment]
It's failing trying to boot up the host. The host needs a valid path for things like configuration files. Apparently, with this publish configuration AppContext.BaseDirectory is also null?

cc @agocke @vitek-karas

**Comment by mmaguigan** [comment]
@davidfowl 

You are correct, `AppContext.BaseDirectory` is null, and the current working directory is `/data` within the container. That said, I am not making use of ASP.NET configuration files and all of Kestrel's configuration is programmatic (not *literally*, the product configuration is simply beyond the scope of this module). Is pure programmatic configuration (vs. ASP.NET style configuration files) still an option? Ideally, Kestrel when used in this manner should not even have to be aware that a file system even exists :grin: It should only be loading configuration files if requested right? If it is currently written to *probe* for configuration, the failure should be silent since it wasn't asked to load any in the first place. Let me know your thoughts.

> PS. Thank you and everyone else on the .NET team for your fantastic efforts. My customers, all .NET shops, have seen nothing but a steady rise in overall product quality and software security since efforts like these began. Please keep up the fantastic work. :bouquet:

**Comment by davidfowl** [comment]
Configuration files aren't being loaded but you need a non-null directory for configuration files even if you're not loading any. An easy workaround is to set the content root to the working directory. UseContentRoot(Environment.CurrentDirectory)

We can fix this in 6.0 and default to this when the app base is null

**Comment by mmaguigan** [comment]
@davidfowl

That seems like a reasonable workaround. I am certainly open to putting this in place for the time being, especially if an option to *fail gracefully* can be added in 6.0. Should we leave this open to track this?

**Comment by davidfowl** [comment]
Yep

**Comment by vitek-karas** [comment]
@mmaguigan If you would be willing, could you please try to run the app with:
```console
export COREHOST_TRACE=1
export COREHOST_TRACEFILE=trace.txt
<run the app>
```

The resulting `trace.txt` will contain detailed info about how the app started and such. The interesting bit is the value of `APP_CONTEXT_BASE_DIRECTORY` property which should be mentioned in the trace.

The file may contain information about the machine (I guess container in this case) and the app, like filenames, filepaths and some environment variables. If you feel comfortable sharing it, I would like to look at the trace file. It is weird that the base directory is reported as null.

**Comment by mmaguigan** [comment]
@vitek-karas @davidfowl 

Given the nature of my work, I would prefer not to publish the output in a public setting. Perhaps there is an email address where I could send this to you both more privately? If so, I will try and get it over to you this morning.

**Comment by vitek-karas** [comment]
My email is in my github profile. I can forward it to @davidfowl if he's interested internally.

**Comment by mmaguigan** [comment]
Thank you @vitek-karas, it has been sent.

**Comment by mmaguigan** [comment]
@vitek-karas identified that the single file build was created by an RC release of the .NET 5.0 SDK on an outdated build system. The single file binary build by 5.0.100 (RTM) does properly set the base directory.

**Comment by davidfowl** [comment]
Perfect, we can close this

**Comment by mmaguigan** [comment]
@davidfowl, yep, I'm happy. Thanks guys.
