### ISSUE TITLE
Blazor - Wasm - AuthorizeView Roles not working

### ISSUE THREAD

**Issue by RafaDom** [dotnet/aspnetcore#28449]
Hi.
I've been trying to  get a very simple project using the &lt;AuthorizeView Roles="rolename"&gt; without any luck.

- Using VS Community 2019 V16.8.2
- Create New Blazor app -> WASM (.NET 5.0) - [Authentication = Individual User Accts -  ASP.NET Core hosted checked]
- dotnet-ef database update
- Open DB, added a couple of roles ("admin", "user")
- Registered a couple of accounts.
- Assigned 'admin' role to one of the Accounts.
- Login with admin-role Account.
- Login success, all looks good, no errors, no problems.
- Added &lt;AuthorizeView Roles="admin"&gt; to NavMenu component
- Added .AddRoles&lt;IdentityRole&gt;() to ConfigureServices services.AddDefaultIdentity ...  (startup.cs)

The NavMenu option in the &lt;AuthorizeView Roles="admin"&gt; Never shows for the Admin Acct.

I did more testing and the authState.User.IsInRole("Admin") is always False.
&lt;AuthorizeView&gt; (no roles specified) works as expected.

reference: - https://www.c-sharpcorner.com/article/role-based-authorization-in-blazor/

Thanks in advance.
RafaDom.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Here are the docs to help with your setup: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#name-and-role-claim-with-api-authorization
