### ISSUE TITLE
Can a literal segment of a url be optional ?

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#28451]
Suppose I have a Contacts folder within the Pages folder of a Blazor app, and this folder contains a few Razor Component pages, one of which, List.razor should be the default. That is, if the user type, say, https://localhost:44376`/contatcs/`, the app should navigate to the List page:

This is how I did it, and it works, but I'm not sure if this is OK. So my question: Can a literal segment of a url be optional as done below ?

```
@page "/contacts?/list"
<h3>List</h3>

@code {
           
}
```

Thanks...

**Comment by MichelJansson** [comment]
@enetstudio, just in case you did not see my last comment on StackOverflow.
This seems to have been a bug, that recently has been closed [in the source](https://github.com/dotnet/aspnetcore/blob/cfc43b38e1d1c205fdac2cf15b994651f9520590/src/Components/Components/src/Routing/TemplateParser.cs#L55) whilst fixing  #27907.

So with the next release I assume a route template like that is going to throw.
