### ISSUE TITLE
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

### ISSUE THREAD

**Issue by kdehia** [dotnet/aspnetcore#28469]
### Describe the bug
I created a new Blazor web assembly Application 5.0  then added service reference gRPC which install the Grpc.AspNetCore(2.32.0)
Then rebuild I get the following error 
"There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'."

### To Reproduce

- create a new Blazor we assembly hosted by itself  
- create a new GRPC service  
- Add service reference gRPC 
- Rebuild  will get the error message 

### Further technical details
 - here is my output window 
Build started...
1>------ Build started: Project: BlazorApp4, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(387,5): error NETSDK1082: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.
1>Done building project "BlazorApp4.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will try to improve the error message as part of https://github.com/dotnet/aspnetcore/issues/28478.
What's happening here is that you're referencing a package which can't work on WebAssembly.

Note: there are ways to make gRPC work with Blazor WebAssembly.
@JamesNK can you create some docs on this combination so we can refer customers to in the future? Thanks!

**Comment by JamesNK** [comment]
You shouldn't reference Grpc.AspNetCore in Blazor.

Follow the instructions [here](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.0&branch=pr-en-us-20882#configure-grpc-web-with-the-net-grpc-client) and reference Grpc.Net.Client and Grpc.Net.Client.Web.

**Comment by kdehia** [comment]
> You shouldn't reference Grpc.AspNetCore in Blazor.
> 
> Follow the instructions [here](https://review.docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.0&branch=pr-en-us-20882#configure-grpc-web-with-the-net-grpc-client) and reference Grpc.Net.Client and Grpc.Net.Client.Web.


Thanks @JamesNK  
I will follow & update

**Comment by kdehia** [comment]
Hi @JamesNK  
Actually the link you provided is not working , I get "We are sorry, the page is forbidden."

Regards,

**Comment by JamesNK** [comment]
Fixed link - https://docs.microsoft.com/aspnet/core/grpc/browser#configure-grpc-web-with-the-net-grpc-client

**Comment by kdehia** [comment]
Thank you @JamesNK  
I already got it to work on Blazor Web Assembly, the link was very helpful also your video helped too 
https://www.youtube.com/watch?v=UV-VnlcpDhU

I think the main issue when I add the proto reference using Add service reference wizard
it add the package by itself 
![image](https://user-images.githubusercontent.com/15203360/101834046-aaf8ed80-3aee-11eb-8eb3-7d4e6961ea38.png)
I guess that is the root of the issue , but when I add it manually by adding  `<Protobuf`  inside .csproj file it works fine 

Maybe the wizard dialog should detect the project type and install the correct packages .

I am closing this since I already figured the solution 

Thanks again

**Comment by JamesNK** [comment]
Yeah that's a known issue. It will be fixed in a future version of VS.

**Comment by Baraka6692** [comment]
I have just upgraded my WASM project to .Net5.0 and I am getting the same error as above and I am not using GRPC or any other library except devExpress and PRISM. What could my problem possibly be?

**Comment by kdehia** [comment]
> I have just upgraded my WASM project to .Net5.0 and I am getting the same error as above and I am not using GRPC or any other library except devExpress and PRISM. What could my problem possibly be?

Could you share your *.csproj
