### ISSUE TITLE
linux-arm64 option not available from visual studio publish profile settings

### ISSUE THREAD

**Issue by Don328** [dotnet/aspnetcore#28462]
### What's happening:
The `linux-arm64` option is not available from the publish profile settings in visual studio.

### To Reproduce
Start any new dotnet application and select publish from the build menu. Follow the steps for creating a publish profile. 

`linux-arm64` is not available.

### But it does work
After creating a profile using the `linux-arm` tag, I am able to edit my `.pubxml` file and change it to `linux-arm64`, republish the binaries, and it works as advertised.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by mkArtakMSFT** [comment]
@vijayrkn  FYI

**Comment by vijayrkn** [comment]
@Don328 - Thank you for reporting this. The Publish UI only displays a subset of RIDS based on the common usage. 
(https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids)

As you mentioned, the publish process do support all the applicable RIDS. So the recommendation is to manually update them in the pubxml for the desired behavior.
