### ISSUE TITLE
Target framework error during build process upgrading to .net 5

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#28473]
When using a shared libary the target frame work is greyed out and not selectable.

![image](https://user-images.githubusercontent.com/5619229/101350727-5e5fa900-3887-11eb-9d77-fb48dbb4b51c.png)

This is the error 
`Severity    Code    Description Project File    Line    Suppression State
Error   MSB4044 The "ResolvePackageAssets" task was not given a value for the required parameter "TargetFramework". SimplCommerce.Module.PaymentPaypalExpress   C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets    241 

When I double click it it brings me to this code in the file above.

`
    <ResolvePackageAssets 
      ProjectAssetsFile="$(ProjectAssetsFile)"
      ProjectAssetsCacheFile="$(ProjectAssetsCacheFile)"
      ProjectPath="$(MSBuildProjectFullPath)"
      ProjectLanguage="$(Language)"
      EmitAssetsLogMessages="$(EmitAssetsLogMessages)"
      TargetFramework="$(TargetFramework)"
      RuntimeIdentifier="$(RuntimeIdentifier)"
      PlatformLibraryName="$(MicrosoftNETPlatformLibrary)"
      RuntimeFrameworks="@(RuntimeFramework)"
      IsSelfContained="$(SelfContained)"
      MarkPackageReferencesAsExternallyResolved="$(MarkPackageReferencesAsExternallyResolved)"
      DisablePackageAssetsCache="$(DisablePackageAssetsCache)"
      DisableFrameworkAssemblies="$(DisableLockFileFrameworks)"
      CopyLocalRuntimeTargetAssets="$(CopyLocalRuntimeTargetAssets)"
      DisableTransitiveProjectReferences="$(DisableTransitiveProjectReferences)"
      DisableTransitiveFrameworkReferences="$(DisableTransitiveFrameworkReferences)"
      DotNetAppHostExecutableNameWithoutExtension="$(_DotNetAppHostExecutableNameWithoutExtension)"
      ShimRuntimeIdentifiers="@(_PackAsToolShimRuntimeIdentifiers)"
      EnsureRuntimePackageDependencies="$(EnsureRuntimePackageDependencies)"
      VerifyMatchingImplicitPackageVersion="$(VerifyMatchingImplicitPackageVersion)"
      ExpectedPlatformPackages="@(ExpectedPlatformPackages)"
      SatelliteResourceLanguages="$(SatelliteResourceLanguages)"
      DesignTimeBuild="$(DesignTimeBuild)"
      ContinueOnError="$(ContinueOnError)"
      PackageReferences="@(PackageReference)">`

`A Further error that I get is the following

`Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1013	The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	SimplCommerce.Module.PaymentPaypalExpress	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	92	

And 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Project '..\Warehouse.Infrastructure\Warehouse.Infrastructure\Warehouse.Infrastructure\Warehouse.Infrastructure.csproj' targets 'net5.0'. It cannot be referenced by a project that targets '_,Version=v0.0'.	SimplCommerce.Module.PaymentPaypalExpress	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1662	

`
Please find enclosed my version information's as attachment

Microsoft Visual Studio Community 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA994
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.553.28003
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.553.28003
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.553.28003
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.553.28003
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by davidbuckleyni** [comment]
Please also find my .net proj file I am using the modular aspect from simply commerce in my own application and it using the following within its modules.
```

<Project Sdk="Microsoft.NET.Sdk.Razor">
 
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
 
  <ItemGroup>
    <Content Remove="bundleconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="bundleconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\PaymentPaypalExpress\Components\" />
    <Folder Include="Areas\PaymentPaypalExpress\Views\Shared\Components\" />
    <Folder Include="Data\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Warehouse.Infrastructure\Warehouse.Infrastructure\Warehouse.Infrastructure\Warehouse.Infrastructure.csproj" />
  </ItemGroup>

</Project>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Your project is missing `TargetFramework` property declaration, as the error message points out.
Consider adding the following in the `PropertyGroup` section in your project file:

```xml
    <TargetFramework>net5.0</TargetFramework>
```

**Comment by davidbuckleyni** [comment]
This does not fix the siutation i then get futher messages about this.

**Comment by davidbuckleyni** [comment]
If I added the framework version i get the following error.


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type 'Template' already defines a member called 'ExecuteAsync' with the same parameter types	WarehouseCrm.Module.PaymentPaypalExpress	D:\GitMaster\WareHouseCrm\WarehouseCrm.Module.PaymentPaypalExpress\obj\Debug\net5.0\Razor\Areas\PaymentPaypalExpress\Views\_ViewImports.cshtml.g.cs	26	Active

And it takes me to here please dont just close an issue right away this is why .net is so buggy.

#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/Areas/PaymentPaypalExpress/Views/_ViewStart.cshtml")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"baccc989a51c6a8f7d22a3ba48a16caf1d0e1adf", @"/Areas/PaymentPaypalExpress/Views/_ViewStart.cshtml")]
    public class Template
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(" ");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591

**Comment by davidbuckleyni** [comment]
Futhermore the project does not allowed me to add Microsoft.AspnetCore.APP lattest version!

**Comment by pranavkm** [comment]
@davidbuckleyni can you create a brand new Razor Class Library (with support for MVC and Razor Pages) and use that as a template to update your project? We also have guides for migrating RCL projects from 3.1 to 5.0 available here - https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-razor-class-libraries-rcls

**Comment by davidbuckleyni** [comment]
Yeah creating a new one fixed the issue but why is importing an existing one broken ?
