### ISSUE TITLE
ProtectedLocalStorage not working with webassembly

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28477]
The bad news is I try to use the proper namespace for protectedlocalstorage but its not working for webassembly.  That is bad.  Because even webassembly needs encrypted values for localstorage as well.  Plus, it would mean if somebody was creating a razor class library they would not even be able to use there either most likely.

**Comment by guardrex** [comment]
@mkArtakMSFT ... *Doc update merged and done!* :+1:
