### ISSUE TITLE
Add SDK snapshot tests for 5.0 apps

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#28489]
This issue tracks adding some tests to verify the SDK does not regress building 5.0 apps

* [x] Add a test for 5.0 MVC
* [ ] ~~Add a test for 5.0 Blazor Server~~
* [ ] Add a test for 5.0 Blazor Wasm

**Comment by captainsafia** [comment]
We've covered this for MVC apps already during the SDK migration but we still need to cover the two Blazor scenarios.
