### ISSUE TITLE
Blazor webassembly - MainLayout and Component events sequence

### ISSUE THREAD

**Issue by rajeshaz09** [dotnet/aspnetcore#28499]
### Describe the bug
OnParametersSetAsync and OnInilitized events of component are finishing first than MainLayout.

We have some static texts to display on blazor webpage like CopyRight (in MainLayout) and HomePage welcome text (Index component). Need to make HTTP call to get static texts, so I  am calling HTTP call in OnParametersSetAsync event handler. But during HTTP call, Index component's events are finished execution.

Is this correct behavior? 

### To Reproduce
Please check https://github.com/rajeshaz09/BlazorEvents repository
When you navigate to /Counter observe the output
```
Counter - OnParametersSetAsync
MainLayout - OnParametersSetAsync

```

### Further technical details
- .NET 5.0
- Blazor clientside - webassembly
- VS 2019 16.8.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. .NET doesn't guarantee the order when task continuations will execute. If you are looking for a way to invoke code as soon as possible we recommend asking for that in [StackOverflow](https://stackoverflow.com).
