### ISSUE TITLE
Consider replacing InlineStringBuilder with ValueStringBuilder

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#2849]
https://github.com/dotnet/corefx/blob/5d71d9ea70418c26874949b36e6434c4849fde52/src/Common/src/CoreLib/System/Text/ValueStringBuilder.cs#L11

We should look at the places where we use InlineStringBuilder today and consider replacing those instances with ValueStringBuilder (of course measuring performance along the way). We can also look at places where we use a StringBuilder (like QueryString.Add/Create/Append) and see if there are other wins we can get.

/cc @benaadams

**Comment by anurse** [comment]
Backlogging until we have a little more specific motivation for this.
