### ISSUE TITLE
https error on kestrel simple aspnet core web api projects

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28497]
I have a local ip address of 192.168.0.150

If i use this code
"WebApplication3": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://192.168.0.150:9002",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
in the launch settings.json file in the properties folder and run the project, the error that shows up on the page is

Your connection is not private
Attackers might be trying to steal your information from 192.168.0.150 (for example, passwords, messages, or credit cards)

has privacy error.  For this project, I was enabling https.  There is a case where I am locally hosting a page but still requires https otherwise web assembly refuses to connect to them.

What are the steps that needs to be taken so the default project which has the weather controller can actually work over https and not use localhost.  The reason I cannot use localhost is because i cannot test with other computers on the network.
Whatever makes it work with localhost, i need to know how to make it work even if i am using a local ip address but not localhost so others on the network can access it.

**Comment by Tratcher** [comment]
The default dev cert only supports localhost. If you want to use other host names or IPs then you need to create your own certificate with the matching name.

If it's just for testing can you click past the cert warning?

**Comment by musictopia2** [comment]
Is there a way to create my own certificate?  I would want to self host it.  The purpose is for local hosting.  It would mean that if somebody outside the network accessed the page, obviously would be errors because its not an internet address.  When the warning comes up, there is no way to click past the warning because its used in a blazor web assembly app so when it tries to access it, gives the runtime error.

**Comment by musictopia2** [comment]
The good news is there was some documentation for creating a certificate for hosting.  However, so far, it only works for localhost.  There should be one to show how to use a specific ip address like https://192.168.0.150 for example.
Which allows testing from other computers on the network via ssl.

**Comment by BrennanConroy** [comment]
Have you tried using the IP address in the `-DnsName` parameter?

**Comment by musictopia2** [comment]
Yes but still same problems.

**Comment by shirhatti** [comment]
You can look at the dotnet dev cert tool's source to see how we generate a self-signed certificate- https://github.com/dotnet/aspnetcore/tree/master/src/Shared/CertificateGeneration

You can use the same logic and add a Subject Alternate Name for whatever hostname you want to issue a certificate for.

If you still have problems, I recommending re-posting this question on a forum like StackOverflow.
