### ISSUE TITLE
Disable Model Binding/Multipart Request Streaming - Working on Windows and in Linux Docker container, Not working in Kubernetes

### ISSUE THREAD

**Issue by 7wingfly** [dotnet/aspnetcore#28496]
I'm attempting to implement the file streaming example documented here; https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0

The idea is to stream files directly to Azure blob storage rather than have them stored in memory before uploading to azure. 

_(otherwise things get slow when uploading large files and the progress bar on the client side hangs at 100% until its uploaded to Azure)_

The strange issue I'm facing is that my code is actually working perfectly fine on Windows and in a Linux docker container running on my local machine, however when I deploy the same docker image to Kubernetes, it suddenly starts cashing the uploaded files in memory again. 

My upload file end point:
```c#
[HttpPost]
[DisableFormValueModelBinding]
[RequestSizeLimit(100_000_000)]
public async Task<IActionResult> UploadFIle()
{   
    int UserID = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

    Console.WriteLine("{0} | User ID: {1} - Uploading attachment", DateTime.Now.ToLongTimeString(), UserID);

    if (!MultipartRequestHelper.IsMultipartContentType(Request.ContentType))
        return BadRequest("Not a multipart request");

    var boundary = MultipartRequestHelper.GetBoundary(MediaTypeHeaderValue.Parse(Request.ContentType));
    var reader = new MultipartReader(boundary, Request.Body);
    var section = await reader.ReadNextSectionAsync();

    if (section == null)
        return BadRequest("No sections in multipart defined");

    if (!ContentDispositionHeaderValue.TryParse(section.ContentDisposition, out var contentDisposition))
        return BadRequest("No content disposition in multipart defined");

    var fileName = contentDisposition.FileNameStar.ToString();
    if (string.IsNullOrEmpty(fileName))
    {
        fileName = contentDisposition.FileName.ToString();
    }

    if (string.IsNullOrEmpty(fileName))
        return BadRequest("No filename defined.");           

    Console.WriteLine("{0} | User ID: {1} - Attachment: {2}", DateTime.Now.ToLongTimeString(), UserID, fileName);

    using (Stream fileStream = section.Body)
    {
        CloudStorageAccount Account = CloudStorageAccount.Parse("MyConnectionStringblahblahblah");
        CloudBlobClient BlobClient = Account.CreateCloudBlobClient();
        CloudBlobContainer Uploads = BlobClient.GetContainerReference("MyContainerName");

        var AzureBlob = Uploads.GetBlockBlobReference(fileName);
        AzureBlob.Metadata.Add("Uploader", UserID.ToString());
                
        await AzureBlob.UploadFromStreamAsync(fileStream);
    }

    Console.WriteLine("{0} | User ID: {1} - Attachment Complete: {2}", DateTime.Now.ToLongTimeString(), UserID, fileName);

    return Ok();            
}
```

> The helper classes `DisableFormValueModelBinding` and `MultipartRequestHelper` are mentioned in the MS document linked above

I have also tried 
```c#
using (Stream azureStream = await AzureBlob.OpenWriteAsync())
{
    await fileStream.CopyToAsync(azureStream);
}
```
instead of 
```c#
await AzureBlob.UploadFromStreamAsync(fileStream);
```

And the behaviour is the same. 

I'm running Kubernetes version v1.18.3

I. Am. Stumped.

All and any advice is welcome and appreciated

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us. It seems that you have something wrong happening with your deployment.
While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
