### ISSUE TITLE
Allow MinLength to validate the minimum size of a collection

### ISSUE THREAD

**Issue by jgabrielgv** [dotnet/aspnetcore#28490]
Framework version: ASP.NET Core 3.1.

I am not really sure if this is a feature, a bug or just something that I am missing. I am trying to understand what else do I need to include in order to block the requests that do not have at least one employee Id via attributes:

```
public class SearchEmployeesModel {
     [Required, MinLength(1)]
     public List<int> EmployeeIds { get; set; }
}
```

Then pass in the model to the body of the (sample) action:
```
[Authorize]
[Route("api/v1/employees")]
public class EmployeesController : ControllerBase {

    [HttpPost("search")]
    [Authorize]
    public async Task<IActionResult> Search([FromBody] SearchEmployeesModel model) {
        ....
    }

}
```

Expected behavior:
If the model is passed in as an empty JSON object, it should throw `BadRequest`, because `EmployeeIds` Should have at least one element.

Actual behavior:
It is not throwing any exception at all.

I have read some posts and it says that if you use the native array (`int[]`) it should work, but I didn't have luck with that either.

Am I missing something or there should be a new attribute introduced to support this behavior, like `MinCollectionLength` or something like that? From my perspective, we should reuse `MinLength` to cover this.

Thank you guys for the support.

**Comment by pranavkm** [comment]
Are you inspecting model state to verify that no validation errors are recorded? See https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-5.0#how-validation-works or https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#model-state for what that would look like. 

If you use an `ApiController`, MVC will perform the validation check on your behalf. See https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0#automatic-http-400-responses.

**Comment by jgabrielgv** [comment]
`[ApiController]` and you guys saved my day. Thank you!
