### ISSUE TITLE
Blazor PWA does not force refresh / delete cache on deploy.

### ISSUE THREAD

**Issue by coderaven** [dotnet/aspnetcore#28503]
Referencing: https://github.com/dotnet/aspnetcore/issues/22353

In the thread above, https://github.com/dotnet/aspnetcore/projects/12#card-39583624 - via 5.0.0-preview7 should already contain the fix for this. However when as it currently stands, the same issue still is not resolved. Cache is still not being force deleted on deploy and manifest version still does not automatically varies.

The current workaround is by adding an updated comment (version, date, or any other update string) in the service-worker js file.

**Comment by do-it-ger** [comment]
Check out this. 
https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#offline-support
Only the service-worker.published.js will updated during the publish 

I use this: https://blog.jeremylikness.com/blog/implement-progressive-web-app-hugo/

BTW -> Abp use no PWA in the current template. Do you include it successfully? Atm the current concept of WASM theming and registration doesn't work like in a standard blazor VS Template.

**Comment by coderaven** [comment]
It seems like when you add an additional comment string on the service-worker js, it automatically works as expected on every deployment. It forces delete cache.
