### ISSUE TITLE
Blazor - Virtualize component CSS rendering issues

### ISSUE THREAD

**Issue by Dreyerized** [dotnet/aspnetcore#28512]
### Describe the bug
When using the new Virtualize component, certain elements have rendering glitches when the visible items switch. For instance, in my items being virtualized, I have a toggle switch. When the component switches the visible items, some of the toggles will flip their state and then render back to what they should be.

If I turn off the switch transition animation, it does not happen. If I do not use Virtualize, it does not happen.

It appears that there is some interaction between the items being switched out in the DOM and the CSS rendering causing some issues.

Another oddity is as you scroll through the items, the width of the columns in the table change for no apparent reason.

### To Reproduce
[https://github.com/Dreyerized/blazor-virtualize-css-issue](https://github.com/Dreyerized/blazor-virtualize-css-issue)
See the above repo. I've included two simple tables, one that has toggles that have CSS transitions, and one that does not. When you scroll the table with transitions you can see the toggles jump about, which does not happen on the other table with no transitions. The only difference between the two tables is the second table sets the `-webkit-transition` and `transition` css properties to `none`.

### Further technical details
- This issue occurs running both locally and on my deployed web application. Locally running Mac OS, deployed running on amazon-linux. Occurs on all major browsers.
- ASP.NET Core version 
  - net5.0
- Include the output of `dotnet --info`

```.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  - Rider 2020.3 EAP10 (on Mac OS 11.0.1)

**Comment by SteveSandersonMS** [comment]
This is very much as designed. The way Virtualize works is by only introducing the DOM elements when they are becoming visible - that's the whole point of the component and how it achieves its performance gain. This means you should expect any "on added" CSS animations to run at the point where those elements get added into the DOM.

> Another oddity is as you scroll through the items, the width of the columns in the table change for no apparent reason.

Also expected. If the width of the columns is determined by which elements are currently in the DOM, and you change those elements while scrolling, then the widths of the columns will change while you're scrolling. I'd recommend fixing the widths to specific values/proportions using CSS.
