### ISSUE TITLE
DefaultReturnUrl property in CookieAuthenticationOptions

### ISSUE THREAD

**Issue by timmi-on-rails** [dotnet/aspnetcore#28517]
I am using Razor Pages in ASP.NET Core 3.1 together with the CookieAuthentication middleware.
In my LoginPageModel.OnPost() method I call HttpContext.SignInAsync(...) on successful authentication.
I have set the CookieAuthenticationOptions.LoginPath to '/Login' and therefore the middleware is creating a redirection response, if the ReturnUrlParameter has been set in the query.
Everything working as expected.

### Is your feature request related to a problem? Please describe.
In the case the user visits the '/Login' page directly without the ReturnUrlParameter set, no redirection is happening (of course).
But still I want to redirect to the Index page '/Index' after successful authentication if no ReturnUrl is set.
To accomplish that I have to check the query parameters for the ReturnUrlParameter. In order to check for the ReturnUrlParameter I have to inject the CookieAuthenticationOptions into my LoginPageModel.
If it is not set, then I redirect to '/Index' otherwise I let the middleware do its job.
This is a lot of handwork for such a simple task.

### Describe the solution you'd like
I would like to add another property to the CookieAuthenticationOptions which sets a default value for the ReturnUrlParameter if it is not set in the query.
If the new property CookieAuthenticationOptions.DefaultReturnUrl is not set (== null), then the behavior is the same as it is now. 
When set it will redirect to that Url, even if no ReturnUrlParameter is defined.

Here is an implementation example, that I've done on a fork: https://github.com/timmi-on-rails/aspnetcore/commit/bab80a6400d8212e5863d979546d68e7c0346c5a

**Comment by Tratcher** [comment]
See https://github.com/dotnet/aspnetcore/issues/17475#issuecomment-714788359 and https://github.com/dotnet/aspnetcore/issues/4667 for some related discussion.

#4667 Passing the desired redirect uri to SignIn via the AuthProperties.RedirectUri would be preferred over adding yet another option to cookie auth.

**Comment by timmi-on-rails** [comment]
@Tratcher AuthProperties.RedirectUri has precedence over setting the ReturnUrlParameter in the query.
So that does not simplify my code, when I want a default value, if no ReturnUrlParameter has been set.
I would have to check for the presence of the query parameter and set AuthProperties.RedirectUri conditionally.
But then I can simply do the redirect on my own.

What I read from #17475 (comment) is, that this implicit redirect was a bad decision from todays point of view and will not be extended?

**Comment by Tratcher** [comment]
> What I read from #17475 (comment) is, that this implicit redirect was a bad decision from todays point of view and will not be extended?

Right, we'd rather remove that feature than extend it. A possible replacement would be a helper you'd call directly that checks for the query parameter value and allows you to provide a fallback.

**Comment by timmi-on-rails** [comment]
I am closing. There are enough dangling issues and the reasoning sounds plausible to me.
