### ISSUE TITLE
Multiple MapDynamicControllerRoute: Using ExpandEndpoint requires that the replaced endpoint have a unique priority.

### ISSUE THREAD

**Issue by Tripplefix** [dotnet/aspnetcore#28516]
### Description of the bug
If you try to map multiple dynamic controller routes on startup of an asp.Net core project, an "InvalidOperationException" will be thrown. I have discovered this behaviour when I was working on a larger website with multiple projects where two different projects need to register their own DynamicRouteValueTransformer. In the example code below I have registered the two Transformers as such:
```
endpoints.MapDynamicControllerRoute<Test1RouteTransformer>("{SeName}");
endpoints.MapDynamicControllerRoute<Test2RouteTransformer>("{SeName}");
```
... and then got the same exception. Remove any of the two lines and the routing works (for the one that remains).

### To Reproduce
Clone this repo: https://github.com/Tripplefix/MapDynamicControllerRouteTest 
Then start the webserver and open https://localhost:5001/test-foo and https://localhost:5001/test-bar

### Exceptions
The two URLs mentioned before throw two different but seemingly related exceptions:

```
InvalidOperationException: Using ExpandEndpoint requires that the replaced endpoint have a unique priority. The following endpoints were found with the same priority: {SeName} {SeName}
Microsoft.AspNetCore.Routing.Matching.CandidateSet.ValidateUniqueScore(int index)
Microsoft.AspNetCore.Routing.Matching.CandidateSet.ExpandEndpoint(int index, IReadOnlyList<Endpoint> endpoints, IComparer<Endpoint> comparer)
Microsoft.AspNetCore.Mvc.Routing.DynamicControllerEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
![image](https://user-images.githubusercontent.com/2863593/101527481-5b031500-398e-11eb-852a-b134b53ae3e3.png)

```
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.AspNetCore.Routing.Matching.CandidateSet+<>c.<ValidateUniqueScore>b__15_0(Endpoint e)
System.Linq.Enumerable+SelectListIterator<TSource, TResult>.MoveNext()
string.Join(string separator, IEnumerable<string> values)
Microsoft.AspNetCore.Routing.Matching.CandidateSet.ValidateUniqueScore(int index)
Microsoft.AspNetCore.Routing.Matching.CandidateSet.ExpandEndpoint(int index, IReadOnlyList<Endpoint> endpoints, IComparer<Endpoint> comparer)
Microsoft.AspNetCore.Mvc.Routing.DynamicControllerEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
![image](https://user-images.githubusercontent.com/2863593/101527506-61918c80-398e-11eb-9f90-1ddd5e1489bb.png)

### Expected behaviour
It should be possible to map/register multiple dynamic controller routes.

### Further technical details

The output of `dotnet --info`
```
C:\Entwicklung\MapDynamicControllerRouteTest>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.404\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

I am working with Rider 2020.2.4

**Comment by davidfowl** [comment]
> It should be possible to map/register multiple dynamic controller routes.

Why? What's the scenario?

**Comment by Tripplefix** [comment]
> > It should be possible to map/register multiple dynamic controller routes.
> 
> Why? What's the scenario?

Specifically, I am working on a commerce project using the asp.net application nopCommerce. NopCommerce maps dynamic controller routes (for products, blog posts, etc) here:

https://github.com/nopSolutions/nopCommerce/blob/b0e24dd28ea7f0e8773c026ba59fa1fd4dac2f8b/src/Presentation/Nop.Web/Infrastructure/GenericUrlRouteProvider.cs#L22

To extend nopCommerce with functionality, I need to create a plugin, which is a separate project within the solution. Now, I want to register my own DynamicRouteValueTransformer in such a plugin as described in the issue. This throws the mentioned exception.

**Comment by davidfowl** [comment]
Why do the routes need to conflict. I guess I don't understand that part. If you have multiple transformers trying to party on the same route which should win?

**Comment by Tripplefix** [comment]
As I understand the transformers, they work like a sieve. If a transformer does not handle a route, it returns the RouteValueDictionary without modification ...:
```
// no item found
if(!response.Items.Any())
    return new RouteValueDictionary(values);
```
... and the next registered route is checked - or in my case, the next transformer tries to handle the route. So there is (should be) no conflict.

**Comment by davidfowl** [comment]
Unfortunately that's not how it works. Transformers are attached to routes directly as metadata then a policy picks the right endpoint based on the result of the transformer. What the code above does it register duplicate routes so the system can't disambiguate between them because they have the same priority.

The null reference exception is a bug during error handling that we should fix but you'll end up with an ambiguous routes even if that works. 

In NopCommerce (I'm familiar with the project), do these transformers all have the same route template?

**Comment by Tripplefix** [comment]
NopCommerce only has one Transformer, the "SlugRouteTransformer". Unfortunately, it is built in a way that makes it difficult to extend. That's why I wanted to add my own transformer. I think I will propose an improvement on their project page.

But the exception occurs even when the route templates are different (although I am not sure if this counts as "different"):

```
endpoints.MapDynamicControllerRoute<Test1RouteTransformer>("{SeName1}");
endpoints.MapDynamicControllerRoute<Test2RouteTransformer>("{SeName2}");
```

![image](https://user-images.githubusercontent.com/2863593/101820141-7b65d780-3b26-11eb-8e09-cb86f9d7a5d1.png)

**Comment by davidfowl** [comment]
Those templates aren't different, they capture the same number of arguments. They're still ambiguous. The only difference is the parameter name. In your example, why couldn't the transformer route pattern look like this:

```
endpoints.MapDynamicControllerRoute<Test1RouteTransformer>("test-foo");
endpoints.MapDynamicControllerRoute<Test2RouteTransformer>("test-bar");
```

> Thank you for clarifying that. I found there to be very little resources or documentation about this feature.

Right. We should fix that, and the other bug you found.

**Comment by davidfowl** [comment]
After playing with this, I can see there were issues in 3.1 that have since been fixed in 5.0. In 3.1 each of those routes have the same priority and it fails as a result. This is fixed in 5.0 and works as expected.

**Comment by sefacan** [comment]
@davidfowl my example was for 5.0.

**Comment by Tripplefix** [comment]
> After playing with this, I can see there were issues in 3.1 that have since been fixed in 5.0. In 3.1 each of those routes have the same priority and it fails as a result. This is fixed in 5.0 and works as expected.
> 
> See #25073

That is exactly what I need! I have to wait then until nopCommerce uses 5.0. Until then I will use a temporary workaround. Thank you.

@sefacan I think your issue is not related to the one I mentioned. The problem I had only occurred when I tried to register multiple transformers with the same route template.

**Comment by sefacan** [comment]
Thank you. I opened a new issue.

**Comment by mkArtakMSFT** [comment]
Closing as no further action is pending here.
