### ISSUE TITLE
Blazor memory leak due to nested bind-Value

### ISSUE THREAD

**Issue by ThatFlashCat** [dotnet/aspnetcore#28518]
### Describe the bug
Nesting components that make use of `@bind-Value` will result in a memory leak. This occurs on both .NET Core 3.1, .NET 5.0, in both Blazor server and Blazor WASM, and on IIS Express and IIS.

### To Reproduce

Create a new component `BindComponent` and add this code to it:
```c#
<input type="text" class="form-control" @bind-value="Value" />

@code {
    [Parameter]
    public string Value
    {
        get => hidden;
        set
        {
            hidden = value;
            ValueChanged.InvokeAsync(value);
        }
    }
    [Parameter]
    public EventCallback<string> ValueChanged { get; set; }
    private string hidden;
}
```
In any other component, reference the component:
```c#
<BindComponent @bind-Value="bound"></BindComponent>

@code {
    string bound { get; set; }
} 
```

Run the application and type something in the text box, then tab out. Check Visual Studio dev tools and you will see a memory leak. 

I know there are ways around this issue but I doubt this should cause Blazor to leak memory.

### Exceptions (if any)
Not applicable.

### Further technical details
- ASP.NET Core version: .NET Core 3.1, .NET 5.0 (Blazor Server and Blazor WASM)

**Comment by SteveSandersonMS** [comment]
It looks like this code sets up an infinite loop. The property setter triggers `ValueChanged`, which will cause the parent to re-render, which causes this component to receive new parameters, which triggers the setter again, and so on forever. The memory growth is just a side-effect of the infinite loop. Assuming my analysis is correct, this isn't a framework defect - the code is telling it to keep rendering forever in recursive stack (as per the rules of rendering and parameter passing), so it does.

I do appreciate it's a bit subtle and possible to do this by mistake. To help with that, we have issue https://github.com/dotnet/aspnetcore/issues/26230 which tracks a way of ensuring developers avoid this problem via a compile-time warning/error.

**Comment by ThatFlashCat** [comment]
Thanks! I wasn't sure if it was allowed by design or a legitimate bug.
