### ISSUE TITLE
Add Captcha to the Framework

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28522]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/917617/add-captcha-to-the-framework.html)._

---
<p>Why isn't captcha part of the framework... I should be able to simply place a reference in a form and have captcha included on that form.  Trying to add a third party plug-in is nuts.  There are dozens to sift through and there's no way of knowing what they look like, if they will function with your configuration or if they will even work.  I'm truly frustrated with the situation. </p>

---
#### Feedback Bot on 2/14/2020, 03:06 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by blowdart** [comment]
As captchas fall under security I'm afraid I'm going to say now for a few reasons:

- They're an awful experience for anyone relaying on accessibly
- They're extremely hard to secure and keep secure, both bots and manual parsing both keep up with technology, nullifying any usefulness a captcha would provide

I don't feel it's something a framework needs to provide, and it's not something we could provide safely or in an accessible way.
