### ISSUE TITLE
Blazor Webassembly Hosted template freezes while debugging after clicking on "About" link twice

### ISSUE THREAD

**Issue by pholly** [dotnet/aspnetcore#28520]
### Describe the bug
While debugging a Blazor Webassembly Hosted (no authentication) project in Visual Studio, clicking on the "About" link twice causes the app to freeze and an error in Visual Studio:
`AI: CannotSerializeObjectNonSerializable message:"Attempting to serialize an object which does not implement ISerializable" props:"{name:baseData}"
Uncaught SyntaxError: Unexpected token c in JSON at position 30AI: CannotSerializeObjectNonSerializable message:"Attempting to serialize an object which does not implement ISerializable" props:"{name:baseData}"`

Opening developer tools in the browser causes the app to work again. Interestingly, the app freezes after clicking twice even in developer tools is open first.

Issue doesn't happen when running the server project without debugging (using dotnet watch run or ctrl+F5).

### To Reproduce

1. Create a new Blazor Webassembly Hosted project in Visual Studio. No authentication is fine.
2. Run the Server project in Visual Studio
3. Click the "About" link in the top right twice. The app freezes and an error is thrown in Visual Studio.

### Exceptions (if any)

```
AI: CannotSerializeObjectNonSerializable message:"Attempting to serialize an object which does not implement ISerializable" props:"{name:baseData}"
Uncaught SyntaxError: Unexpected token c in JSON at position 30AI: CannotSerializeObjectNonSerializable message:"Attempting to serialize an object which does not implement ISerializable" props:"{name:baseData}"
```

### Further technical details
- ASP.NET Core version 5
- Blazor packages 5.0 or 5.0.1
- Visual Studio 16.8.2 and tested with 16.8.3

`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pholly** [comment]
The same exception is thrown in Visual Studio Code (Windows) but the app doesn't freeze up.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
