### ISSUE TITLE
WebComponents Forms InputFile - Change the _inputFileElement field to protected so a class can be derived from InputFile

### ISSUE THREAD

**Issue by Valks** [dotnet/aspnetcore#28533]
Hi,
    I'm wondering if it's possible to have the [InputFile.cs](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/InputFile.cs) line 20 changed to ```protected``` instead of ```private``` so that it can be used in a derived class which replaces the ```BuildRenderTree()```.

https://github.com/dotnet/aspnetcore/blob/e14e5bc7f215c6f86f2b02882affdff758fb265b/src/Components/Web/src/Forms/InputFile.cs#L20

The reason this change is necessary is that the elementReference needs to be set during the ```BuildRenderTree()``` call for the component to work.

https://github.com/dotnet/aspnetcore/blob/e14e5bc7f215c6f86f2b02882affdff758fb265b/src/Components/Web/src/Forms/InputFile.cs#L66

I'm happy to submit a PR with the change, just wondering if there's any concerns I'm not aware of?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please share more details about your scenario. We would like to understand how it's going to be used.

**Comment by Valks** [comment]
Sure, I'm looking to change the ```BuildRenderTree``` because I'm working with web components (in my case the fast.design framework) and I'm overloading all the form components to use the fast.design web components.

Now the fast framework doesn't have a customization for ```<input type="file">``` yet, but this problem will also affect other web component frameworks i.e.
https://www.webcomponents.org/element/@fluidnext-polymer/paper-input-file

The reason I want to derive from the InputFile component is to take advantage of the work already done to handle files. A lot of those classes related to the javascript interop are internal and I don't need access so long as I can assign the ElementReference.

The easiest way to do what I need is to either expose the ```_inputFileElement``` by making it protected or add a helper function to call ```builder.AddElementReferenceCapture(3, elementReference => _inputFileElement = elementReference);```. Personally I feel making _inputFileElement protected achieves the desired outcome with minimal impact and doesn't expose it to users of the new component. Especially considering it's already a public API.

**Comment by SteveSandersonMS** [comment]
Understood. Thanks for clarifying!

We're thinking of extending https://github.com/dotnet/aspnetcore/pull/24899 to include the functionality you're asking for (that is, making the field writable via a protected setter). I'll add a note there.

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/29555
