### ISSUE TITLE
gRPC project templates use gRPC.Tools NuGet package which does not work on Big Sur

### ISSUE THREAD

**Issue by mrward** [dotnet/aspnetcore#28538]
### Describe the bug

Full bug description on the gRPC site - https://github.com/grpc/grpc/issues/24529

The underlying problem in the gRPC.Tools NuGet package has been fixed in gRPC.Tools 2.34.0 but the 
 gRPC project templates use an older version, so they do not work on macOS Big Sur out of the box.

Can the gRPC NuGet packages be updated in the project templates?

### To Reproduce

See description

### Further technical details
- .NET Core SDK version 3.1.404 and 5.0.101
- VS Mac 8.8.3

**Comment by BrennanConroy** [comment]
@Pilchie We probably want to try updating the template in 5.0. Should be simple.

**Comment by Pilchie** [comment]
Agreed!  Thanks for the heads-up.

**Comment by JamesNK** [comment]
Will need template update plus VS update for package versions it includes.
