### ISSUE TITLE
Json Deserialize to Handle String to Enum Conversion

### ISSUE THREAD

**Issue by alancohen** [dotnet/aspnetcore#28544]
## Summary

The Json deserializer does not handle when an enum value is in its string representation.

## Motivation and goals

I have a use case where an API returns a string representation of an enum and I would like to be able to deserialize it into an enum value in my C# class.

## Examples
The json that gets returned:
```
{
    ExampleId: 101,
    ExampleStatusEnum: "Approved"
}
```

The enum:
```
public enum ExampleStatus
{
    Approved = 1
}
```

The object to deserialize into:
```
public class Example
{
    public int ExampleId { get; set; }
    public ExampleStatus EampleStatusEnum { get; set; }
}
```

**Comment by Tornhoof** [comment]
Did you look at https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-5.0

**Comment by alancohen** [comment]
> Did you look at https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-5.0

Thank you, this solved my issue.
