### ISSUE TITLE
VS debugger detaches after closing file picker in certain Chromium-based browsers

### ISSUE THREAD

**Issue by Hunv** [dotnet/aspnetcore#28547]
### Describe the bug
When you implement a file upload using the <InputFile ... /> or <input type="file ... /> controls, the server process crashes with the message.
```
...\path\to\BlazorApp1\BlazorApp1\bin\Debug\net5.0\BlazorApp1.exe (process 31424) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
```
when using Vivaldi Browser (Version 3.4.2066.106 (Stable channel) (64-bit))

### To Reproduce
1. Create a new .Net 5.0 Blazor Server App
2. Change the Execution Text next to the "start"-Button in VS to your Projects name instead of "IIS Express"
3. Change the Browser that is used to start the project to Vivaldi
4. Open the Index.razor and paste the following at the end:
```
<InputFile OnChange="@UploadFile" />
@code{
    private void UploadFile() { }
}
```
5. Start the project and select a file. The server application will close after the select file dialog is gone.

I am not 100% sure, but it may not be a problem with Blazor itself but with the way how Visual Studio detects if the application Website was closed and will stop debugging then. Because: if I don't use Vivaldi as the debugging browser but i.e. Chrome and open the website in Vivaldi manually and do the action above, everything is OK.

### Exceptions (if any)
No Exceptions. Just the regular message, when an application stopped debugging.
```
...\path\to\BlazorApp1\BlazorApp1\bin\Debug\net5.0\BlazorApp1.exe (process 31424) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
```

### Further technical details
- ASP.NET Core version: 5.0
- The IDE: Visual Studio 2019 Community Version 16.8.2
dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by SteveSandersonMS** [comment]
Blazor's browser support list is at https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-5.0 Normally we'd expect other Chromium-based browsers to work, but can't 100% guarantee every detail as we don't control them.

If this does repro on Chrome/Edge, please give us details. Besides that we'll add it to the backlog.

**Comment by BLSully** [comment]
I ran into this issue today using Brave Browser. Switching to Microsoft Edge "fixed" it. 

I tried turning off all the cookie blocking stuff in Brave but still didn't work. As OP posted, I got no diagnostic information other than the exit code. Debugger would break on my first line in the FileChangeEvent handler for a split second, and then the process would immediately bail.

**Comment by kapilbhudhia** [comment]
I too am facing the exact same issue, had been breaking my head over what s wrong with my application. The application behaves as expected when using chrome/Edge.

**Comment by yyw10242** [comment]
Brave Browser.
Same Problem. Same Issue.
Yea... browser should fix this problem but...
Little worry for blazor's future.

**Comment by Benjeyyy** [comment]
Same problem!
.Net 5.0
Brave Browser Version 1.31.91

**Comment by hartmair** [comment]
see https://stackoverflow.com/questions/59611090/asp-net-3-0-mvc-app-crash-after-file-image-upload/59611796

**Comment by TheRealRolandDeschain** [comment]
https://stackoverflow.com/questions/71141070/blazor-server-file-upload-silently-crashes-server

**Comment by SteveSandersonMS** [comment]
Moving back to re-triage this.

**Comment by TheRealRolandDeschain** [comment]
I have tested the bug simply by creating a new blazor server project and adding the `<InputFile />` tag (tried different variations: single file, multiple files, with/without `OnChange` event attached to some code) to the counter page. However, there is a reference project linked in my Stackoverflow post above, which I have just tested with the same result:
https://github.com/mu88/StackOverflow_BlazorServerFileUpload

**- VS, command line (via dotnet run) or both?**
Visual Studio 2019
**- Debug, Release or both?**
Debug
**- HTTP, HTTPS or both?**
Both
**- Is it any file that causes the issue or a specific file (if specific, providing it would be appreciated!).**
No. I have tested with small and big images, small and empty text files and even simply not selecting a file, just closing the file browser dialog via the 'X' button. all the same result.
**-brave shield**
Tested both with shield up and completely deactivated for localhost
**- server type**
Issue on both IIS and Kestrel


Hope this helps a bit, let me know if you need more information.

**Comment by SteveSandersonMS** [comment]
@TanayParikh Were you launching with the debugger?

Looking in more detail at the comments above it seems likely that this isn't a real problem in production, but might actually just be a defect in the VS debugger tooling.

**Comment by SteveSandersonMS** [comment]
> Can approve that this bug only appears when running in Debug. When running in Release, it was ok

Can you clarify what you mean? By "Debug" do you mean:

 * You built in debug configuration (as opposed to release configuration)
 * Or, that you launched with a debugger (e.g., by pressing F5, and *not* by pressing Ctrl+F5)

Are you saying that F5 has the issue and that Ctrl+F5 does not, even if in both cases your project is set to debug configuration?

**Comment by Karmageddonium** [comment]
@SteveSandersonMS 

I have been trying for half an hour and can say that in VS 2022 it is floating bug which is not guaranteed to appear. I am still trying to get some strong test case but still nothing. 

Now can say that all appeared cases were in Debug configuration Funning by F5 button
Another one point: i guess it is somehow attached to OnChange event because as i see, if i make breakpoint to loadFiles method it stops there and then fail. 

`@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<InputFile id="files" OnChange="LoadFiles"></InputFile>

@code{
    private async Task LoadFiles(InputFileChangeEventArgs e)
    {
    }
}`

If i have some news, will write here

**Comment by TheRealRolandDeschain** [comment]
After your comments I tested the following with an new empty blazor server, where I added `<InputFile />` to the counter page:

**- Config: Debug => F5**
crash
**- Config: Debug => CTRL+F5**
no crash
**- Config: Release=> F5**
crash
**- Config: Release=> CTRL+F5**
no crash

seems the debugger really causes the problem

**Comment by TheRealRolandDeschain** [comment]
Starting a new ASP.NET Core web applicationa and putting `<input type=file>` seems to cause the same crash.
Again no issue when ustin CTRL+F5

**Comment by SteveSandersonMS** [comment]
Thanks very much for checking! In that case, this is a VS issue, not a Blazor or ASP.NET Core one. Would it be possible for you to report it via the VS feedback feature?

![image](https://user-images.githubusercontent.com/1101362/154670751-1721895e-e998-462d-a44f-b0a33110f72e.png)

**Comment by SteveSandersonMS** [comment]
I should also clarify that this is not a crash. It's simply the VS debugger detaching, perhaps because it thinks the main browser window was closed when in fact it was only the file picker that was closed.

**Comment by TheRealRolandDeschain** [comment]
>I should also clarify that this is not a crash. It's simply the VS debugger detaching, perhaps because it thinks the main browser window was closed when in fact it was only the file picker that was closed.

Makes perfect sense, as there are no exceptions to be found...program just 'exits'.
