### ISSUE TITLE
Possible IHubContext issue

### ISSUE THREAD

**Issue by nzstevem** [dotnet/aspnetcore#28543]
Hi,

Trying to make a Razor page send a SignalR message on loading by injecting IHubContext and then invoking Clients.All.SendAsync(...) inside OnGetAsync(). The problem is nothing happens. I've enabled tracing in signalr and nothing appears when the method executes. I've tried using SendCoreAsync with the same result. 

The application is the standard ChatHub example in the documentation. The only difference is an added Test razor. Client to client chatting works fine. I've also written a net core console app that is able to participate by sending and receive messages via /chathub. So pretty convinced the underlying Hub process is working.

The suspect code inside OnGetAsync() follows. This line simple does nothing.

await _ctx.Clients.All.SendAsync("SendMessage","Test",$"Loaded at {DateTime.Now}");

Am I doing something wrong or is this a problem??? Appreciate any help.

Rgds
Steve

Here's the hub per example.

ChatHub.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;

namespace testcore.Hubs
{
    public class ChatHub : Hub
    {
        public async Task SendMessage(string user, string message)
        {
            await Clients.All.SendAsync("ReceiveMessage", user, message);
        }
    }
}

And my test page..

Test.cshtml
@page
@model testcore.Pages.TestModel
@{
}

<div class="container">
    Test...
    <ul>
    @foreach (string x in Model.debuglog)
    {
    <li>@x</li>
    }
    </ul>
</div>

Test.cshtml.cs

 using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Hosting;
using testcore.Hubs;

namespace testcore.Pages
{
    public class TestModel : PageModel
    {
        public readonly IHubContext<ChatHub> _ctx;
        public readonly IHostEnvironment _env;

        public TestModel(IHubContext<ChatHub> ctx, IHostEnvironment env)
        {
            _ctx = ctx;
            _env = env;
        }

        public List<string> debuglog = new List<string>() { "Log created" };

        public async Task OnGetAsync()
        {
            debuglog.Add($"OnGetAsync - start");

            await _ctx.Clients.All.SendAsync("SendMessage","Test",$"Loaded at {DateTime.Now}");

            // await _ctx.Clients.All.SendCoreAsync("SendMessage", new string[]{ "Test", $"Loaded at {DateTime.Now}"});
            // await Task.Delay(1000);

            debuglog.Add($"Content RootPath: {_env.ContentRootPath}");
            debuglog.Add($"OnGetAsync - done");
        }
    }
}

**Comment by BrennanConroy** [comment]
It looks like you're trying to treat `IHubContext` as a reference to the Hub. This is incorrect, `IHubContext` is a way to send to clients from outside the Hub.

So you should be doing `await _ctx.Clients.All.SendAsync("ReceiveMessage", "Test", $"Loaded at {DateTime.Now}");`

**Comment by nzstevem** [comment]
You are dead right. Many thanks.
