### ISSUE TITLE
Blazor (Server Side in .NET 5): Injected HttpClient's BaseAddress is always null.

### ISSUE THREAD

**Issue by gordon-matt** [dotnet/aspnetcore#28554]
I am attempting to inject a typed `HttpClients` in a new **Blazor** app (.NET 5). Here's my code in Startup:

```
services.AddHttpClient<IEmployeeService, EmployeeService>(client =>
{
    client.BaseAddress = new Uri("http://localhost:56024/");
});
```

and in the `EmployeeService` class:

```
public class EmployeeService : IEmployeeService
{
    private readonly HttpClient httpClient;

    public EmployeeService(HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }
```

an instance of `HttpClient` does get injected, but the `BaseAddress` is null. What's the issue here?

**NOTE**: The code can be found here: [EmployeeManagement.Web](https://github.com/gordon-matt/BlazorEmployeeManagementTutorial/tree/main/EmployeeManagement.Web)

**Comment by JorgeValladares** [comment]
Following as I believe I have same issue

**Comment by SteveSandersonMS** [comment]
In general, server-side ASP.NET Core doesn't typically have a concept of a base address, and it's generally not something people need. In case you do need it, you can use the mechanism above.

I'll close this as it's working as expected. If many other people have problems we can reconsider the design. Hope that's OK!

**Comment by gordon-matt** [comment]
I haven't tried @JorgeValladares's suggestion yet, but that appears to only allow for a single HttpClient to be used in all controllers. In that case, there's no point setting a base address ahead of time, because we might want different base addresses used in different controllers. I was hoping for the same kind of thing in Blazor as we see here: [Use IHttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests?ranMID=42411&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-G2U8kq2f21AFfoXkjbVyKw&epi=je6NUbpObpQ-G2U8kq2f21AFfoXkjbVyKw&irgwc=1&OCID=AID2000142_aff_7815_1243925&tduid=%28ir__u6a3e1b1ewkfqnmmkk0sohzw222xpkxky1qmawkh00%29%287815%29%281243925%29%28je6NUbpObpQ-G2U8kq2f21AFfoXkjbVyKw%29%28%29&irclickid=_u6a3e1b1ewkfqnmmkk0sohzw222xpkxky1qmawkh00)

Example:

```
services.AddHttpClient<ICatalogService, CatalogService>();
services.AddHttpClient<IBasketService, BasketService>();
services.AddHttpClient<IOrderingService, OrderingService>();
```

But I could have each point to a different Base Address, as follows:

```
services.AddHttpClient<ICatalogService, CatalogService>(client =>
{
    client.BaseAddress = new Uri("/odata/Catalogs");
});
services.AddHttpClient<IBasketService, BasketService>(client =>
{
    client.BaseAddress = new Uri("/odata/Baskets");
});
services.AddHttpClient<IOrderingService, OrderingService>(client =>
{
    client.BaseAddress = new Uri("/odata/Orders");
});
```

Something like that...

Anyway, I guess @JorgeValladares's suggestion will do for now. Thanks
