### ISSUE TITLE
Negotiate ClaimsCache isn't thread safe

### ISSUE THREAD

**Issue by govorovvs** [dotnet/aspnetcore#28569]
## Describe the bug
Looks like `ClaimsCache` in the `Microsoft.AspNetCore.Authentication.Negotiate` package isn't thread safe.

## To Reproduce
https://github.com/dotnet/aspnetcore/blob/beb91f8be76a53e00876f9d10463d6e252af6b98/src/Security/Authentication/Negotiate/src/Internal/LdapAdapter.cs#L23

**Comment by blowdart** [comment]
This only happens at app startup, putting a lock in is likely to have performance side effects. As the race doesn't have any real side effects, we won't be adding locks.
