### ISSUE TITLE
Client SignalR show more than one user joined to group

### ISSUE THREAD

**Issue by michaelzapata** [dotnet/aspnetcore#28582]
### Describe the bug
First of all use a translator to write the question.

When I add a connection to a group I inform everyone that a user joined 

public async Task JoinQuestionGroup(Guid chatroomid)
{
            await Groups.AddToGroupAsync(Context.ConnectionId, chatroomid.ToString());
            await Clients.OthersInGroup(chatroomid.ToString()).UserConnected($"User has {Context.User.Identity.Name} joined");
}

and when I remove the connection from the group I report that a user has disconnected, but when I try to add the same user to the group again signalr reports more than once that the user entered to the group, why is it due?

public async Task LeaveQuestionGroup(Guid chatroomid)
{
	await Groups.RemoveFromGroupAsync(Context.ConnectionId, chatroomid.ToString());
	await Clients.OthersInGroup(chatroomid.ToString()).UserConnected($"User has {Context.User.Identity.Name} has left the room");
}

Signalr in the client tells me more than once that the user joined or left the room. How can I solve it?

### Further technical details
- NET Core 3.1

**Comment by shirhatti** [comment]
Can you share a repro app? It's unclear from your code snippets on what could be going wrong.

Are you using SignalR or SignalR Core?
