### ISSUE TITLE
Chinese characters in razor has been escaped

### ISSUE THREAD

**Issue by ahdung** [dotnet/aspnetcore#28588]
**asp.net core 5**
![image](https://user-images.githubusercontent.com/12094247/101886229-28e3f400-3bd6-11eb-9047-7de4a08df0c0.png)

in Fiddler:
![image](https://user-images.githubusercontent.com/12094247/101886664-c6d7be80-3bd6-11eb-9dfc-3f6dd560694a.png)

**Comment by ahdung** [comment]
I know, workaround:
```c#
services.AddSingleton(HtmlEncoder.Create(UnicodeRanges.All));
```
But I still recommend not to escape by default.

**Comment by javiercn** [comment]
@ahdung thanks for contacting us.

This is not a behavior that we plan to change in the immediate future. As you mentioned, there is a way to configure the Html encoder to support the behavior you expect.
