### ISSUE TITLE
Can the 'Authorization' of the key name in the request header be modified?

### ISSUE THREAD

**Issue by feigaogit** [dotnet/aspnetcore#28586]
microsoft.aspnetcore.authentication.jwtbearer

Can the 'Authorization' of the key name in the request header be modified? 
Can I change it to 'Authorization2'
What shall I do?
![image](https://user-images.githubusercontent.com/18181270/101873066-435fa280-3bc1-11eb-9ef7-d7cab52104a9.png)

**Comment by blowdart** [comment]
No, it's a standard header specified in the RFCs, so we've never made it customizable.
