### ISSUE TITLE
Replace coverage for Blazor wasm standalone individual auth 

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#28596]
The test creates a project with the following arguments:

```
dotnet new blazorwasm -au Individual --authority https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration --client-id sample-client-id
```

When it runs, it redirects the user to the MS auth endpoint.
![image](https://user-images.githubusercontent.com/6995051/101916511-e42b6f00-3b7b-11eb-8863-f6d4d13101c9.png)

The issue here is two-fold:
* Something in AuthenticationService.GetUser is triggering a redirect, we should avoid that if possible.
* The test is incorrect and flaky, so we should figure out a different set of parameters so that it works correctly.

I've reproduced this behavior with 5.0.1 to discard any testing related issues.

**Comment by javiercn** [comment]
As a first step, I'm marking the test as "skip" until we figure out what we do here.

**Comment by javiercn** [comment]
We need to ensure this test is covered by CTI

**Comment by mkArtakMSFT** [comment]
Agreed. We're going to write up instructions for CTI on how to start up an OAuth server and test against it.
