### ISSUE TITLE
Blazor - EditContext.IsModified still false after unchecking checkbox

### ISSUE THREAD

**Issue by mohankumar91** [dotnet/aspnetcore#28590]
### Describe the bug
I have some checkboxes on an EditForm and I'm getting inconsistent behavior with EditContext.IsModified(). 
 When you click **open** button, uncheck the first checkbox and click "OK", you see that IsModified() still returned false.

### To Reproduce
 <button @onclick="OnOpen">Open</button>
    
    
    @if (_weatherForecast != null)
    {
        @if (_wasModified.HasValue)
        {
            <p>EditContext.IsModified() = @_wasModified</p>
            <p>WillRain = @_weatherForecast.WillRain</p>
            <p>WillSnow = @_weatherForecast.WillSnow</p>
        }
        @if (_isVisible)
        { 
                    <EditForm Model="@_weatherForecast" OnValidSubmit="OnValidSubmit">
                        <DataAnnotationsValidator />
                        <div class="form-row">
                            <div class="form-group col">
                                <label>Will rain </label>
                                <input type="checkbox" @bind="@_weatherForecast.WillRain" />
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col">
                                <label>Will snow </label>
                                <input type="checkbox" @bind="@_weatherForecast.WillSnow" />
                            </div>
                        </div>
                        <div class="e-footer-content">
                            <button> Ok</button>
                        </div>
                    </EditForm>
        }
    
    }
    @code {
        private bool _isVisible = false;
        private WeatherForecast _weatherForecast;
        private bool? _wasModified;
    
        private void OnValidSubmit(EditContext editContext)
        {
            _wasModified = editContext.IsModified();
            _isVisible = false;
        }
    
        private void OnOpen()
        {
            _weatherForecast = new WeatherForecast { WillRain = true, WillSnow = false };
            _wasModified = null;
            _isVisible = true;
        }
    
        public class WeatherForecast
        {
            public bool WillRain { get; set; }
            public bool WillSnow { get; set; }
        }
    }

**Comment by javiercn** [comment]
@mohankumar91 thanks for contacting us.

You don't seem to be using the InputCheckbox component, so at that point the changes on the form will not be reflected on the edit context.
