### ISSUE TITLE
Event handlers steal interactions with InputRadio component

### ISSUE THREAD

**Issue by mfluehr** [dotnet/aspnetcore#28601]
### Describe the bug
If I put an `<InputRadio>` inside a wrapper element, and add an event handler to the wrapper, interactions with the radio input break. For example, a click handler breaks clicking, a keyboard handler breaks keyboard input, etc.

I've only had the issue with radio inputs. `<InputCheckbox>`, `<InputText>`, etc. seem to be unaffected. If I remove the handler, the radio works as expected.

### To Reproduce
Here's a simple way to reproduce the problem.

```C#
@page "/eventbug"

<div @onclick="OnClick">
    <EditForm Model="@model">
        <p>
            <InputRadioGroup @bind-Value="model.Size">
                Size:
                @foreach (var size in (Size[])Enum.GetValues(typeof(Size)))
                {
                    <br />
                    <label>
                        <InputRadio Value="size" />
                        @size
                    </label>
                }
            </InputRadioGroup>
        </p>

        <p>
            <label>
                Enabled:
                <InputCheckbox @bind-Value="model.Enabled" />
            </label>
        </p>
    </EditForm>

    <p>Clicks: @clicks</p>
</div>

@code {
    public enum Size { Small, Medium, Large }

    public class TestModel
    {
        public Size Size { get; set; }
        public bool Enabled { get; set; }
    }

    private TestModel model = new TestModel();

    private int clicks;

    void OnClick(MouseEventArgs e)
    {
        clicks++;
    }
}
```

### Exceptions (if any)
None.

### Further technical details
- ASP.NET Core version: 5.0.1

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
