### ISSUE TITLE
Visual Studio New Project Web API Core 3.1 using B2C does not work.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28606]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-New-Project-Web-API-Core-3/1283464)._

---
[severity:I'm unable to use this version]
When creating a New Project in Visual Studio 2019 (Web Api Core 3.1) and using B2C as authentication, the project builds but fails when deployed: HTTP ERROR 401! 

The AAD B2C documentation conflicts everywhere on the web (Microsoft Docs, GitHub, StackOverflow etc) with outdated (breaking changes) between versions.

Building and deploying a Web API Core 3.1 using AD for authentication works fine.

The App Registration seems fine, as it works with mobile (Xamarin) but a new Web App Registration using the same/relevant web settings get a HTTP Error 401.

---
#### Feedback Bot on 12/9/2020, 07:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by blowdart** [comment]
We'd like a repo and logs before we can take this any further, including the steps followed to configure B2C and how you deployed it.
