### ISSUE TITLE
Javascript parser error inside razor views

### ISSUE THREAD

**Issue by rezathecoder** [dotnet/aspnetcore#28618]
### Describe the bug
The javascript parser has issue with parsing '<' operator inside razor views when you try to produce conditional javscript code inside `<text></text>` tag.

### To Reproduce
just open a `<script>` tag inside a razor view and write some c# condition then use `<text>` tag to write javscript code and use '<' operator in an if block.
As you see in the pictures it works fine if it's outside <text> tag but not inside.

![parser-error](https://user-images.githubusercontent.com/66854399/101989026-c7458780-3cb2-11eb-8ac4-8ffd2ccc861e.png)

![parser-error2](https://user-images.githubusercontent.com/66854399/101989030-ce6c9580-3cb2-11eb-8fbc-cd1c06fc07db.png)

### Error text

End of file or an unexpected character was reached before the "" tag could be parsed.  Elements inside markup blocks must be complete. They must either be self-closing `("<br />")` or have matching end tags `("<p>Hello</p>")`.  If you intended to display a "<" character, use the "&lt;" HTML entity.

### Further technical details
- ASP.NET Core version: 3.1.10
- Visual Studio 2019 16.8.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@ajaybhargavb can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
@rezathecoder, `<text>` tags expect well-formed html. Because of that restriction, writing javascript inside `text` tags directly will not work. I suggest restructuring your code to not require text tags in this scenario.

**Comment by rezathecoder** [comment]
@ajaybhargavb Thank you for answering. So you are saying there is no good way to produce conditional javascript in razor views?
I use this pattern a lot and this is the first time i got an error.

> @rezathecoder, `<text>` tags expect well-formed html. Because of that restriction, writing javascript inside `text` tags directly will not work.

When we write well-formed html the parser automatically switches from c# to html so we don't need `<text` tag at all. It seems `<text>` should be used when we are writing something other than well-formed html am i right?
