### ISSUE TITLE
Publish Blazor WASM to App Service Linux not working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28611]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Publish-Blazor-WASM-to-App-Service-Linux/1002767)._

---
On a Blazor Web Assembly project, right-click and publish to Azure App Service Linux configuration appears to publish, but nothing is saved on the Linux server.  

This is creating a new app service with Linux.

When I SSH into the new app service, the published project files are missing from disk

---
#### Feedback Bot on 4/22/2020, 09:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 4/23/2020, 10:15 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Tim Heuer [MSFT] on 4/27/2020, 03:27 PM: 

<p>Hi Jeff! The publish steps actually complete and the files are there (curious why you wouldn’t see them, but I can see them in Kudu, etc.) however there is nothing default in Linux App Service to actually <em>serve</em> them at this time.  When publishing a Blazor Wasm project to Windows, we produce a web.config that IIS can pick up and serve, however this is not the same on Linux.</p>
<p>Team is looking at ways to make this easier/default for Linux, but right now you need to provide the server for it…whether that be a small <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core server, using Azure Storage to host the Wasm files or other means.</p>

#### Tim Heuer [MSFT] on 4/27/2020, 03:33 PM: 

<p>Option 1: Add an ASP.NET Core web project to host the Wasm content and publish the combined solution to App Service Linux</p>

---
### Original Solutions
(no solutions)

**Comment by mstancombe** [comment]
This would be great.  Have just spent a considerable amount of time working around this.  To have an out of box solution (or at least a verbose warning in vs when publishing blazor WASM to Linux) would be very helpful.

**Comment by MeesvanStraten** [comment]
Spent entire day coming to the conlusion that nothing is serving my site . Switched to windows app service and got it working within a minute. Warning at least would be great.

**Comment by project2501** [comment]
I don't get it. This is clearly a bug! VS feature for publishing is allowing to choose the Linux but it is simply not working. Pls either remove the option or guide how to publish on Linux App Service.
