### ISSUE TITLE
One proxy for every provider?

### ISSUE THREAD

**Issue by OysteinHH** [dotnet/aspnetcore#28614]
### Is your feature request related to a problem? Please describe.
I've tried to use libman behind a corporate firewall, but of course none of the providers can be reached.
Setting _http_proxy_ won't work either in my case as we can only open proxies towards specific sites, not the entire internet. So I have to stick to one provider.  

### Describe the solution you'd like
I would like to be able to set a proxy for each provider individually. One proxy for unpkg, one for cdnjs, one for jsdelivr, etc.
Or be able to override **DownloadUrlFormat** with my own URL.
I'd also like to have the proxy-configuration in the _libman.json_ file itself so the config will follow the projects, making it easier to share.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
