### ISSUE TITLE
Blazor can't find components that started out as different type

### ISSUE THREAD

**Issue by WouterrV** [dotnet/aspnetcore#28619]
Found some very interesting behaviour: adding a razor component using the Add -> Razor Component works fine, but if I make a .txt file in Visual Studio and rename it TestComponent.razor, then it's not loaded into the html, I'll just see `<TestComponent/>` there.

It's even funnier if you use the Add dialog to make a .cs file, and then rename it to razor, the compiler (intellisense doesn't see anything wrong, it's only during compiling that things break) still treats it as a .cs file and complains about missing ; and what not.

Somehow behind the scenes, files are still treated as their old type. this was done using Visual Studio 16.8.3 and .NET Core 5. A repo showing this issue is here: https://github.com/WouterrV/BlazorTesting
But it's just as easy to reproduce this with just VS.

**Comment by britney198** [comment]
> Found some very interesting behaviour: adding a razor component using the Add -> Razor Component works fine, but if I make a .txt file in Visual Studio and rename it TestComponent.razor, then it's not loaded into the html, I'll just see `<TestComponent/>` there.
> 
> It's even funnier if you use the Add dialog to make a .cs file, and then rename it to razor, the compiler (intellisense doesn't see anything wrong, it's only during compiling that things break) still treats it as a .cs file and complains about missing ; and what not.
> 
> Somehow behind the scenes, files are still treated as their old type. this was done using Visual Studio 16.8.3 and .NET Core 5. A repo showing this issue is here: https://github.com/WouterrV/BlazorTesting
> But it's just as easy to reproduce this with just VS.

you are totally right and besides i understood sometimes when you run the project at the first run it doesnt show the changes!!!

**Comment by NTaylorMullen** [comment]
Hmm, do things resolve themselves if you remove this: https://github.com/WouterrV/BlazorTesting/blob/652b6f889e23be479edf4c75af48b9d1dd4ba242/BlazorTesting.csproj#L7-L13

**Comment by WouterrV** [comment]
That does resolve it!

**Comment by WouterrV** [comment]
Can I ask, why was this removed from the milestones?
