### ISSUE TITLE
@bind value not updated when options change

### ISSUE THREAD

**Issue by stevekrile** [dotnet/aspnetcore#28620]
I'm using a form that contains a SELECT input bound to a razor page variable. The options of the select will change when the user interacts with the form. While the values properly update, the bound value DOES NOT change. 

Steps to Reproduce:
1. Select Option from select control
2. @selectedChild value updates to the option value as expected.
3. Click the "Add" button to trigger the addStudent method.
4. addStudent method completes the work of persisting the record and calls the refresh method for the option values in the select.
5. The options are refreshed in the control.
6. The option in the select associated with the previously selected index is selected BUT the @selectedValue is not updated and remains the value of the previously selected option.

Pseudo Example BEFORE options refresh:
```html
    <select @bind="@selectedValue">
        <option value="1">1</option>
        <option selected value="2">2</option>
        <option value="3">3</option>

    </select>
    @selectedValue = 2
```

Pseudo Example AFTER options refresh (options now no longer contain the value=2:
```html
    <select @bind="@selectedValue">
        <option value="1">1</option>
        <option value="3" selected>3</option>
    </select>

    @selectedValue = 2    //<== PROBLEM HERE
```

Here is sample code:

FORM

 ```html
    <select class="form-control" @bind="@selectedChild">
        <option value="0">--Select One--</option>
            foreach (Person p in CustomerService.ChildList.NotChildren.OrderBy(o => o.LastName))
                {<value="@p.Id">@p.LastName, @p.FirstName</option>}
    </select>
    <div class="input-group-append">
        <span class="input-group-text" id="basic-addon1"><span style="cursor:pointer" @onclick="@(addStudent)">Add</span></span>
    </div>
```

```
    @code{ 
        private int selectedChild = 0;
        private async void addStudent()
    {

        //service to get the child by ID from the select control
        Person c = CustomerService.ChildList.NotChildren.Find(f => f.Id == selectedChild);
        if (c != null) {
            Children postedChild = new Children()
            {
                CustomerId = Customer.Id,
                ChildId = c.Id
            };

            //save the child
            await CustomerService.AddCustomerChild(postedChild);

            //refresh the lists - this will change the options in the select control
            await CustomerService.LoadCustomerChildren(Customer.Id);

            StateHasChanged();

        }
}
```

**Comment by SteveSandersonMS** [comment]
`@bind` is a way of hooking into particular DOM events (by default, the `change` event). Those DOM events only fire when the associated DOM element is changed. They don't fire when other parts of the DOM are mutated, for example modifying the list of `<option>` nodes. As such, this behavior is expected and standard for browsers. Blazor doesn't control when the events fire, I'm afraid!
