### ISSUE TITLE
[Blazor Wasm] Chrome CPU spike causing lag when interacting with search bar from index page

### ISSUE THREAD

**Issue by andersson09** [dotnet/aspnetcore#28623]
### Describe the bug
Chrome CPU spike, lags when interacting with search bar from Blazor index page. This was working on an older version, I can't remember exactly but its where Program.cs had builder.RootComponents.Add<App>("app") instead of builder.RootComponents.Add<App>("#app")

### To Reproduce
dotnet new blazorwasm
dotnet run
https://localhost:5001/
Given I am on index page, when I click chrome search bar the CPU spikes causing chrome to briefly lag. This only occurs when interacting from the index page, not the others.
(Also happens if I kill the backend process making me believe its a javascript thing)

### Exceptions (if any)
None

### Further technical details

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by andersson09** [comment]
Hmmm, it seems to work fine if I change the port. Anyone know why this would be the case?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This seems to be specific to your app / setup. We're closing this issue as there is no action for us to take here.
