### ISSUE TITLE
[Blazor Wasm] Multiple layouts with different set of css and javascript

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#28624]
The layout system described in [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0) suggest that all the CSS and javascript files will be in the `index.html` file. That means CSS and javascript files specific to one layout will also be available in the other layout's `<head>` too.

Is it possible to have multiple layouts with completely different sets of CSS and javascript files like MVC and Razor Pages?

Thank you.

Note: Due to this problem I am already facing the CSS isolation problem described in https://github.com/dotnet/aspnetcore/issues/28626 . So each layout must have completely different `<html>`, `<head>` and `</body>` tag.

**Comment by SteveSandersonMS** [comment]
If your goal is to have different CSS stylesheets on different pages, you can do that by having different layout components for each combination, and putting the `<link>` tags for the stylesheets into those layouts. See Blazor's docs about layouts for how to pick which layout goes with which page. Note that `<link>` tags don't have to go inside `<head>`.

If your goal is to have different JavaScript files loaded into different pages, this isn't a good idea and you should look for an alternative. Once a `<script>` has been loaded into a page, it *cannot* be removed - that's simply not how scripts work in web pages. If you JS you need to load can only be loaded via `<script>`, then the most reasonable option is to load it globally. However, if the JS you need to load is an ES6 module, then you can load it on demand - see https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#use-of-javascript-libraries-that-render-ui-dom-elements

If your goal is to vary other `<head>` contents such as `<title>`, then we have an ongoing issue tracking the need to make this easy: https://github.com/dotnet/aspnetcore/issues/25705. Until then, an alternative way to do it is to have your host page (e.g., `index.html` or `_Host.cshtml`) *not* contain the `<head>` and `<body>`, but instead put those into your Blazor layout component. Then you can modify them dynamically, e.g., a mechanism like [this](https://github.com/dotnet/aspnetcore/issues/28182#issuecomment-734913956).
