### ISSUE TITLE
[Blazor Wasm] css isolation not wokring.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#28626]
I have two layouts as follows:

1. MainLayout
2. AdminLayout

CSS file for `MainLayout.razor` is `MainLayout.razor.css` as follows:

```
body {
    margin-top: 58px;
}
```

CSS file for `AdminLayout.razor` is `AdminLayout.razor.css` as follows:

```
body {
    margin-top: 0px !important;
}
```

None of the styles is applied when the respective layout page is rendered.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Per [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0), the elements the styles are targeting should be part of the components to be rendered. In your example, you're trying to style parent element, which is not something supported by the current CSS Isolation feature.
