### ISSUE TITLE
Casting IJSObjectReference to IJSInProcessObjectReference throws an exception

### ISSUE THREAD

**Issue by AradAral** [dotnet/aspnetcore#28628]
### Describe the bug
In [the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#consider-making-synchronous-calls), it's stated that: 

> When working with `IJSObjectReference`, you can make a synchronous call by casting to `IJSInProcessObjectReference`.

This obviously implies that a cast from `IJSObjectReference` to `IJSInProcessObjectReference` must be possible. In addition to that, it also makes perfect sense because it's already possible to cast `IJSRuntime` to `IJSInProcessRuntime`.

However, when attempting to cast from `IJSObjectReference` to `IJSInProcessObjectReference`, the following exception is thrown:
```
System.InvalidCastException: Specified cast is not valid.
```

### To Reproduce
All you need to reproduce this:
**Page/Index.razor:**
```razor
@page "/"
@inject IJSRuntime JS

<button class="btn btn-primary">Click me</button>

@code {
    private IJSInProcessObjectReference module;

    protected override async Task OnInitializedAsync()
    {
        IJSObjectReference objRef = await JS.InvokeAsync<IJSObjectReference>("import", "./myModule.js");
        module = (IJSInProcessObjectReference)objRef; // This line throws an "InvalidCastException"
    }
}
```

### Further technical details
- ASP.NET Core version 5.0.1
- Blazor WebAssembly

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Can you please share the content of your `Program.cs` file?

**Comment by AradAral** [comment]
@mkArtakMSFT I have not added anything to the default boilerplate that already exists once you create a Blazor Wasm project. As I said, the code above is all you need to reproduce the issue. Nevertheless, here's the Program.cs:
```
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace VidazorTest
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            await builder.Build().RunAsync();
        }
    }
}

```

**Comment by mkArtakMSFT** [comment]
Thanks @AradAral.
Found it. It's due to https://github.com/dotnet/aspnetcore/issues/26588 issue. Closing this as a dupe.

**Comment by AradAral** [comment]
@mkArtakMSFT Oh, okay. Thanks. Could you guys also check out #28627? That one I'm sure is a bug.
