### ISSUE TITLE
Publish Directory from Visual Studio 2019 can't run in CentOS 8 because of version of Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by wuyuansushen** [dotnet/aspnetcore#28633]
I have installed aspnetcore-runtime-5.0 reference form [Official Guide](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos).
After Installation, I have got this version of dotnet
```
dotnet --info
```
```
Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```
But when I run Directory published from Visual Studio 2019
It will show
```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      5.0.0-preview.8.20414.8 at [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

⚠️ <application>.runtimeconfig.json file in VS2019 published directory is 
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "5.0.0"
    },
    "configProperties": {
      "System.GC.Server": true,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```

So I change it from `"version": "5.0.0"` to `"version": "5.0.0-preview.8.20414.8"`

Success run it.......

Please repair it

**Comment by BrennanConroy** [comment]
Can you install 5.0.0 on your CentOS machine? preview 8 is not supported.

**Comment by wuyuansushen** [comment]
> Can you install 5.0.0 on your CentOS machine? preview 8 is not supported.

@BrennanConroy I installed aspnetcore-runtime-5.0 from default repo in CentOS 8. Its default version is 5.0.0-preview.8.20414.8......

**Comment by BrennanConroy** [comment]
> I installed aspnetcore-runtime-5.0 through default repo in CentOS 8

Ah sorry, we missed that.

Looks like this is a known issue, being tracked by https://github.com/dotnet/core/issues/5596
You might be able to add the microsoft feed to get the correct packages now, or you can wait for the centos folks to build the package for `dist-c8` from `dist-c8-stream`.
You can see the packages at https://packages.microsoft.com/centos/8/prod/

**Comment by wuyuansushen** [comment]
> > I installed aspnetcore-runtime-5.0 through default repo in CentOS 8
> 
> Ah sorry, we missed that.
> 
> Looks like this is a known issue, being tracked by [dotnet/core#5596](https://github.com/dotnet/core/issues/5596)
> You might be able to add the microsoft feed to get the correct packages now, or you can wait for the centos folks to build the package for `dist-c8` from `dist-c8-stream`.
> You can see the packages at https://packages.microsoft.com/centos/8/prod/

Thanks, I determine to wait for it.
