### ISSUE TITLE
Blazor WASM publish on IIS => memory access out of bounds, Error loading ICU asset

### ISSUE THREAD

**Issue by sfoslund** [dotnet/aspnetcore#28639]
---
**Issue moved from dotnet/sdk#14868**
- Please respond to @denscho.

---

_From @denscho on Monday, December 7, 2020 9:01:05 PM_

Since the last Visual Studio Preview update to 16.9.0 Preview 1.0 I get the following error from the IIS-Server in our local network:
![image](https://user-images.githubusercontent.com/66822070/101404696-47e13e00-38d7-11eb-9a63-2bb7ee2b66c5.png)
On my local machine everything works fine with the IIS Express integrated in Visual Studio. But when I publish the blazor.server project to the IIS-Server in our network I get this message when I try to access the page. So it doesn't start at all

When I jump to the rows mentioned in the message I get the following code snipets
![image](https://user-images.githubusercontent.com/66822070/101404738-592a4a80-38d7-11eb-836d-32e93cee6735.png)
![image](https://user-images.githubusercontent.com/66822070/101404749-5cbdd180-38d7-11eb-8602-46cb8b874368.png)

I tried to access the webpage directly on the server using "localhost" or "127.0.0.1" and it works without any problems. If I try to access the page from the same browser-instance using the IP-Address "192.168.50.3" I get the same error as from remote clients. Any hints on what I could do (or check) would be much appreciated :-)

**Comment by mkArtakMSFT** [comment]
@lewing I think this should go to `dotnet/runtime`. Can you please confirm?

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS FYI

**Comment by SteveSandersonMS** [comment]
It's worth checking the browser's network tab to see if there are any failing requests. In particular, look at requests for URLs containing `icu` - perhaps the server isn't returning the ICU data correctly.

**Comment by lewing** [comment]
@denscho and can you please try building this with VS 16.8.3

**Comment by lewing** [comment]
@mkArtakMSFT if it isn't networking related it should be moved.

**Comment by mkArtakMSFT** [comment]
@sfoslund can you please check on what @SteveSandersonMS asked above:

> It's worth checking the browser's network tab to see if there are any failing requests. In particular, look at requests for URLs containing icu - perhaps the server isn't returning the ICU data correctly.

**Comment by rogihee** [comment]
I'm hitting the same problem, I see normal requests from icu.dat and timezones.blat. I tried cleaning the ob/bin dirs and re-installing the packages. 

![image](https://user-images.githubusercontent.com/4984486/102351007-0b33d780-3fa6-11eb-9634-fd61b98f8802.png)

**Comment by rogihee** [comment]
Found the problem, this was caused by including the line 
`<script src="_framework/blazor.webassembly.js" asp-append-version="true"></script>`

twice on the Blazor index page. 

Long story: I host the app in a Razor Page in an ASP.NET Core website and use the environment tag to toggle between production / development:

`    <environment include="Development" exclude="Production">
        <script src="_framework/blazor.webassembly.js"></script>
    </environment>
    <environment include="Production" exclude="Development">
        <script src="_framework/blazor.webassembly.js" asp-append-version="true"></script>
    </environment>
`
In this (new) project I forgot to set the environment taghelper in the _ViewImports, so the page did not recognize the enviroment tag and imported the file blazor.webassembly.js twice.

`@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers`

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know!
