### ISSUE TITLE
Blazor Virtualize: OnInitialized called for initial Items render only

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#28638]
### Describe the bug
`OnInitialized()` is called for the initial `Items` render only.

### To Reproduce
Please see FetchData page in the repro: [VirtualizeTestServer.zip](https://github.com/dotnet/aspnetcore/files/5690619/VirtualizeTestServer.zip)

### Further technical details
- ASP.NET Core version: 5.0.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Mac

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Your `Row` should have a `key` property assigned: 
![image](https://user-images.githubusercontent.com/34246760/102252654-2ece2380-3ebb-11eb-940a-5fe57bb4fe3d.png)

Please read [relevant documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#virtualization) to learn more about the `key` property.
