### ISSUE TITLE
dotnet-watch: Browser fails to launch when using Serilog

### ISSUE THREAD

**Issue by h3rmanj** [dotnet/aspnetcore#28636]
### Describe the bug
When adding `.UseSerilog()` to the WebHostBuilder the LaunchBrowserFilter fails to identify the right URL to launch.

### To Reproduce
Install `Serilog.AspNetCore` package, set up a console logger, and apply to the WebHostBuilder.

See https://github.com/h3rmanj/dotnet-watch-serilog-repro

### Further technical details
- .NET 5.0
- Visual Studio 2019 / CLI

I have also created a fix for this specific issue in #28637

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/sdk/pull/15865
