### ISSUE TITLE
SignalR Connection continuous reconnect due to MessagePack (version 5.0.1)

### ISSUE THREAD

**Issue by teliu-ez** [dotnet/aspnetcore#28632]
### Describe the bug
I got an issue that signal will continuous reconnect when I update MessagePack to latest version(5.0.1). I can fix this issue by degrade MessagePack to version 3.1.10. Could someone help to take a look at this?.net core: 3.1.  SignalR: 1.6.1
![image](https://user-images.githubusercontent.com/65163073/102052883-cc751480-3e21-11eb-8715-1d74036986a1.png)

### Exceptions (if any)
No exception found

### Further technical details
ASP.NET Core version: 3.1
SignalR version: 1.6.1
IDE: visual studio

**Comment by BrennanConroy** [comment]
Can you share what your Hub and client are doing? Does the issue repro outside of Azure SignalR?

**Comment by teliu-ez** [comment]
Here is client side hub setting.
![image](https://user-images.githubusercontent.com/65163073/102315416-163f3580-3faf-11eb-9bb9-6ab55fb207c3.png)
he front end and the back end just pass some messages to each other.
This issue is only related to Signal. I fix this by degrade MessagePack to version 3.1.10.

**Comment by BrennanConroy** [comment]
Likely a dupe of https://github.com/dotnet/aspnetcore/issues/28354
Can you show your server logs? There is probably something like "Failed to load System.Text.Encodings.Web 5.0.0"

**Comment by teliu-ez** [comment]
Thanks very much @BrennanConroy .
**Including a reference to System.Text.Encodings.Web 5.0.0**
Or
**Downgrading your SignalR.MessagePack reference to 3.1**
can fix my issue.

**Comment by teliu-ez** [comment]
I have a question is if the MessagePack (version 5*) is designed for .netcore 5 and MessagePack (version 3*) is designed for .netcore 3? @BrennanConroy

**Comment by BrennanConroy** [comment]
Kind of, but not really. You're just hitting a bug with the System.Text.Json package and .net core 3.1.

**Comment by teliu-ez** [comment]
Thanks.
