### ISSUE TITLE
[SinalR]HttpConnectionOptions.WebSocketConfiguration action is never called when connection start

### ISSUE THREAD

**Issue by xljiulang** [dotnet/aspnetcore#28631]
### Describe the bug
```
    var connection = new HubConnectionBuilder()
    .WithUrl(options.Value.Uri, HttpTransportType.WebSockets, o =>
    {
        o.WebSocketConfiguration = c =>
        { 
            // WebSocketConfiguration action code is never called 
            // breakpoint here
            c.RemoteCertificateValidationCallback = (a, b, c, d) => true;
        };
        
       // HttpConnectionOptions action code is called 
       // breakpoint here
        o.Credentials = new NetworkCredential(options.Value.Username, options.Value.Password);
    })
    .WithAutomaticReconnect(new RetryPolicy(TimeSpan.FromSeconds(10d)))
    .Build();
```

### Further technical details
- ASP.NET Core 5.0
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by BrennanConroy** [comment]
Triage: Just need to look at this outside of triage.

**Comment by BrennanConroy** [comment]
Is the connection being established and just not calling the `WebSocketConfiguration` code? Or is the connection not being established for other reasons, so the code might not have gotten to that action yet?

**Comment by xljiulang** [comment]
I found that `SkipNegotiation` must be set to 'true', otherwise, it throws an exception: `The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors`, then `WebSocketConfiguration` action code is never called.

**Comment by BrennanConroy** [comment]
Ah, that would make sense since you need to run the same certificate validation callback for the HTTP code as well (unless you skip negotiate).

For example:
```c#
HttpClientHandler handler = new HttpClientHandler
{
    ClientCertificateOptions = ClientCertificateOption.Manual,
    ServerCertificateCustomValidationCallback = (a, b, c, d) => true;
};

var connection = new HubConnectionBuilder()
.WithUrl("...", options =>
{
    options.HttpMessageHandlerFactory = _ => handler;
    options.WebSocketConfiguration = c=>
    {
        c.RemoteCertificateValidationCallback = (a, b, c, d) => true;
    };
})
.Build();
```

**Comment by xljiulang** [comment]
Thank you for the answer!
