### ISSUE TITLE
Is there a way to detect mobile without javascript interference in blazor?

### ISSUE THREAD

**Issue by masoodafar-web** [dotnet/aspnetcore#28647]
Hi
Is there a way to detect mobile without javascript interference in blazor?
I use PreRender in blazor and as you know it is very difficult to use JavaScript in this case. Especially for mobile diagnostics.
Is there no way to solve this problem?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. There are no good APIs for you to use to detect it during pre-rendering because the only information we have are the HTTP headers that we've received. You'll have to rely on User Agent headers to identify the client.

**Comment by masoodafar-web** [comment]
Thanks for the support
So this is a big weakness because even in non-prerender we can not use javascript well. In other words, this defect is not only for prerender because in general in React can easily solve this problem.
Please find a solution, because to find out if the user is using the application with a mobile phone or not? is very important
