### ISSUE TITLE
Blazor Webassembly Client debug not working when running on Local Service Fabric cluster

### ISSUE THREAD

**Issue by francescocristallo** [dotnet/aspnetcore#28649]
### Describe the bug
Blazor Webassembly debug not working when running on Service Fabric local Cluster, breakpoints are not hit.
Happens either when Standalone or Asp.net Core Hosted.

### To Reproduce

Service Fabric with Blazor Webassembly hosted on Asp.net Core 5 repro here: https://github.com/francescocristallo/BlazorFabric

### Further technical details

- ASP.NET Core version: 5.0
- Visual Studio 2019 16.8.3 
-Service Fabric SDK 4.2.445

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known limitation which is going to be resolved when we will enable remote debugging in a later release. For now we recommend debugging locally (without service fabric) and then publishing your app as needed.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
