### ISSUE TITLE
Allow pluggable Propagators for AspNetCore

### ISSUE THREAD

**Issue by cijothomas** [dotnet/aspnetcore#28642]
### Is your feature request related to a problem? Yes. 

The issue is with the context propagation logic embedded within Asp.Net Core, HttpClient libraries. These libraries have a hard-coded propagation logic embedded inside them, which follows the W3CTraceContext protocol. However, this makes it hard for users who use non W3CTraceContext, as there is no way to "swap" the W3CTraceContext with something else.

### Describe the solution you'd like
Let `DiagnosticSource` package expose a new Propagators API, ideally, in compliance with the [OpenTelemetry specification for Propagators.](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md). Here is the issue opened in runtime to track this - https://github.com/dotnet/runtime/issues/46054
Once this API is exposed by the runtime, modify AspNetCore (and HttpClient) to simply use these new Propagators API. The default Propagator can be the W3CTraceContext one itself, to ensure backward compatibility. But users can swap it with any custom propagators they chose.

### Additional context
Related issue: https://github.com/dotnet/aspnetcore/issues/27237
Runtime issue: https://github.com/dotnet/runtime/issues/46054

**Comment by cijothomas** [comment]
@noahfalk @tarekgh @shirhatti 

@alanwest @CodeBlanch from OpenTelemetry

**Comment by cijothomas** [comment]
@reyang

**Comment by tarekgh** [comment]
@cijothomas I think this will need to open another issue in the runtime repo and list there the complete proposal according the doc https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md. you can then link this issue to the new one.

**Comment by cijothomas** [comment]
Thanks. Will open related issue in runtime repo as well!

**Comment by shirhatti** [comment]
This was completed by https://github.com/dotnet/aspnetcore/pull/33777
