### ISSUE TITLE
VS stops responding with Blazor projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28644]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-stops-responding-with-Blazor-projects/1278920)._

---
[severity:It's more difficult to complete my work] [regression]
I updated to VS2019 16.8.2 and started a new Blazor server project. On a regular basis, say every 5 or 10 minutes, VS stops responding for around 40 seconds. This makes it extremely difficult to use.

I have tried several Blazor projects, and the same thing happens with all. During the time it isn't responding, there isn't any noticeable CPU or disk activity. No indication of what it's doing at all.

---
#### Fiona Niu[MSFT] on 12/6/2020, 10:47 PM: 

<p>Thank you for taking the time to log this issue!</p>
<p>In order for us to investigate further, please provide more information by recording your repro steps via the Visual Studio Feedback Tool (Help -&gt; Send Feedback -&gt; Report A Problem). The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace). Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool – <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed">full instructions</a><br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a> , you can get tips on how to provide clear and simple reproducible steps.</p>
<p>Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.</p>
<p>We look forward to hearing from you!</p>

#### mryossu on 12/7/2020, 06:46 AM: 

<p>Hmm, odd. I did submit this through VS. When I submitted the problem, it showed me about four attached files, which I assumed were the extra info.</p>
<p>The problem I have is that I don’t have a specific repro scenario. It just happens every few minutes, not specifically in response to an action I have taken. How can I record that?</p>
<p>Thanks</p>

#### mryossu on 12/7/2020, 07:31 AM: 

<p>OK, ignore my last comment, I managed to catch it. Please see ticket 1279902 where various files were uploaded with the recording.</p>
<p>Thanks</p>

#### Feedback Bot on 12/7/2020, 06:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fiona Niu[MSFT] on 12/7/2020, 06:32 PM: 

<p>@<a target='_blank' href="https://developercommunity2.visualstudio.com/users/23194/mryossu.html">mryossu</a> Thanks a lot for providing the information. This issue has been escalated for further investigation.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

**Comment by MrYossu** [comment]
Are you seriously telling me that I have to live with this for a year? No I do not want to install preview software on my machine. 

I can't believe you think this is an acceptable response!
