### ISSUE TITLE
FrameworkReference build error with Microsoft.Identity.Web and Radzen.Blazor

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/aspnetcore#28652]
---
**Issue moved from microsoft/dotnet#1247**
- Please respond to @dakahler.

---

_From @dakahler on Friday, September 4, 2020 3:52:14 PM_

There is an interaction between these two packages that causes a build error. More strangely, if you then remove one of the references, the build error persists. However, adding either of them on their own on a fresh project builds fine.

Repro

- Create new Blazor WebAssembly hosted project with the project template in Visual Studio 16.8 Preview 2. Select .net 5.0 target.
- Add references to the Client project: Microsoft.Identity.Web (latest preview); Radzen.Blazor
- Build

Error: C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(318,5): error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized

**Comment by pranavkm** [comment]
> Add references to the Client project: Microsoft.Identity.Web (latest preview);

Microsoft.Identity.Web is a ASP.NET Core (server) feature which would explain why you're seeing this error. Blazor WASM ships with several auth options that use MSAL to connect to the Microsoft Identity platform. I would recommend starting from one of those. 

Lastly, 5.0 RTM is out, consider updating the .NET SDK installed on your machine: https://get.dot.net
