### ISSUE TITLE
Hosting Bundle installer uses ".NET Core" branding

### ISSUE THREAD

**Issue by bgrainger** [dotnet/aspnetcore#28658]
The "ASP.NET Core 5.0 Runtime (v5.0.1) - Windows Hosting Bundle Installer" from https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.1-windows-hosting-bundle-installer still has ".NET Core" branding.

![image](https://user-images.githubusercontent.com/188129/102178459-49bc7b80-3e5a-11eb-85d5-9c11a1ea0adb.png)

Since the name changed from .NET Core 3.1 to .NET 5.0, I think it should say "Microsoft .NET 5.0.1 Windows Server Hosting".

This appears to come from https://github.com/dotnet/aspnetcore/blob/4a7ed303fff26e4070e02e385fb22df484f6b81f/src/Installers/Windows/WindowsHostingBundle/WindowsHostingBundle.wixproj#L91-L92

**Comment by wtgodbe** [comment]
Thanks for the report, I'll get this fixed for the next servicing release

**Comment by Pilchie** [comment]
Just a note that we'll want to figure out the LOC implications of changing this in servicing.

**Comment by wtgodbe** [comment]
It looks to me like this string is the same across all loc versions of the installer - it's always based off of `BundleNameShort`. e.g:

https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Installers/Windows/WindowsHostingBundle/1028/thm.wxl#L3-L8

Which is set in the .wixproj: https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Installers/Windows/WindowsHostingBundle/WindowsHostingBundle.wixproj#L79

**Comment by Pilchie** [comment]
Thanks for verifying!

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/28682

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/28682
