### ISSUE TITLE
Dispose not being called on page when accessed with a WebView2 browser

### ISSUE THREAD

**Issue by jdaless** [dotnet/aspnetcore#28678]
### Describe the bug

Dispose() is not called on a disposable blazor page when a WebView2 instance is closed. Does work in Edge and Firefox.

### To Reproduce

Minimal example here: https://github.com/jdaless/WebView2Blazor

Run both projects. Access site from both Edge and the webview. In the webview, navigate to the Counter page. Close the webview2. Click the event button in Edge then navigate to the Counter page. Would expect to see a 0 but see a 1 instead.

Can instead attach a breakpoint to the Dispose method on Counter.razor and close the webview while on that page.

If this is a problem with the WebView2 package I can open an issue on their feedback repo, but I'm thinking that the issue is with the Blazor circuit.

### Further technical details

- using .NET5.0

<details>
<summary>dotnet --info</summary>

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

- VS 16.8.3
- Using WebView 1.0.721-prerelease

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The framework waits for `onbeforeunload` event to fire by the browser. If that doesn't happen the framework won't call the disposal. So this comes down to browser behavior and we have no control over it.
Note: that there is now a `window['Blazor'].disconnect` API you can call to trigger the disconnect..

**Comment by jdaless** [comment]
Calling the disconnect manually did the trick, thanks!
