### ISSUE TITLE
BlazorWasm (hosted) - "dotnet publish" does not create _framework folder in /publish/wwwroot/

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/aspnetcore#28680]
### Describe the bug
After project hosting BlazorWasm app is published, wwwroot folder does not contain _framework folder, therefore attempt to open app fails since `blazor.webassembly.js` is not found.
(Folder _is_ present in Client project's publish folder, but that doesn't really help for server project.)

It's very similar to https://github.com/dotnet/aspnetcore/issues/27551, but not related to linux-x64.
It's not the same as https://github.com/dotnet/aspnetcore/issues/27776 either, as I'm not using StaticWebAssetBasePath in any way.

### To Reproduce
cmd:
```
dotnet new blazorwasm --hosted
dotnet publish -c Release
tree .\Server\bin\Release\net5.0\publish\wwwroot
```

Expected: 
It should contain _framework folder.

Actual:
```
...TEST\SERVER\BIN\RELEASE\NET5.0\PUBLISH\WWWROOT
└───css
    ├───bootstrap
    └───open-iconic
        └───font
            ├───css
            └───fonts
```

### Further technical details
- ASP.NET Core version - 5.0.1
- Include the output of `dotnet --info`

<details>
<summary>dotnet --info</summary>

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.607 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

</details>

**Comment by pranavkm** [comment]
While this looks like a possible bug, publishing a solution file (which is what you're doing when publishing from the root directory of the WASM hosted folder) is a bit unusual. Publishing the Server project correctly includes the _framework folder:

```
dotnet new blazorwasm --hosted
cd Server
dotnet publish -c Release
tree .\bin\Release\net5.0\publish\wwwroot 
```

**Comment by robertmclaws** [comment]
I've also run into this problem when using Visual Studio build in Azure DevOps. I have to do it that way (instead of the `dotnet` commands) because I have a mixed NET 4.8 / NET 5 solution.

When publishing this way, the _framework file is left out, and file compression is turned off... even though the Client project is compiled/compressed/packaged properly.

I've spent a *significant* amount of time trying to solve this today. Very frustrating.

**Comment by robertmclaws** [comment]
Alright, I have a temporary workaround for this problem, for anyone presently dealing with it.

You can add the following Target to the *.Server.csproj file:
```
  <Target Name="CopyMissingBlazorContent" BeforeTargets="_CopyResolvedFilesToPublishAlways">
    <PropertyGroup>
      <ClientPublishWwwroot>$([System.String]::Copy('$(PublishDir)').Replace('Server','Client').Replace('PubTmp','browser-wasm\PubTmp'))wwwroot\</ClientPublishWwwroot>
      <ServerPublishWwwroot>$(PublishDir)wwwroot\</ServerPublishWwwroot>
    </PropertyGroup>

    <Message Text="ClientPublishWwwroot: $(ClientPublishWwwroot)" Importance="High" />
    <Message Text="ServerPublishWwwroot: $(ServerPublishWwwroot)" Importance="High" />

    <Delete Files="$(ServerPublishWwwroot)**\*.*" />
    
    <CreateItem Include="$(ClientPublishWwwroot)**\*.*">
      <Output TaskParameter="Include" ItemName="FilesToCopy" />
    </CreateItem>
    
    <Copy SourceFiles="@(FilesToCopy)" DestinationFiles="@(FilesToCopy->'$(ServerPublishWwwroot)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" Retries="3" RetryDelayMilliseconds="300" />
  </Target>
```

Right before the deployment package is put together, this target:
- Deletes any files already in the /wwwroot
- Copies the files from the Client publish folder to the /wwwroot folder in the Server publish. This has the added benefit of also including the pre-compressed files as well.

HTH!

**Comment by mthrift2100** [comment]
I'm experiencing a similar but slightly different issue. When I publish locally on my machine, the output is what I would expect.  We use Jenkins for our CICD, and the actual publish occurs from a linux box.  When the same publish occurs there, the _framework folder is there, but it is missing several files, specifically any .js, .wasm or .dat file.  I am still reviewing your workaround above to see if that will make a difference.

**Comment by robertmclaws** [comment]
Theoretically, it should. It just copies files from the Client build to the Server build. If you're still not getting the files after that, check the Client build outputs and make sure they are working. And make sure you're publishing and not just building.

**Comment by mthrift2100** [comment]
Definitely publishing the project.  What I eventually discovered, and I honestly don't know why this would make a difference, but if i run 
`dotnet publish Insight.Server.csproj -p:PublishTrimmed=false -c Release -o ./output --runtime win-x64 --self-contained false`

only the dll's from the client project are copied over to the server, as a result of being a project reference I susect.  But if I simply run publish without specifying the project (assuming I'm at the root folder of the project), it works as expected:

`dotnet publish -c Release -o ./output --runtime win-x64`

If i reference the project directly, I also have to explicitly call `PublishTrimmed= false`.

**Comment by SteveSandersonMS** [comment]
We think this is resolved in .NET 6. Could you please try the latest .NET 6 preview release and let us know if the issue still affects your application? Thanks!
