### ISSUE TITLE
Blazor deadlock in combination with Monaco + Omnisharp + Roslyn

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/aspnetcore#28689]
### Describe the bug
I am working on a small project to combine a Blazor **server** application with the Monaco Javascript editor and Omnisharp/Roslyn intellisense features. The final editor is part of a larger project but I have a small sample animation [here](https://raw.githubusercontent.com/Apollo3zehn/MonacoBlazorSample/master/doc/1.png).

A sample for reproduction is located here https://github.com/Apollo3zehn/BlazorMonacoRoslyn.

Whenever the code in the editor changes, a [javascript callback](https://github.com/Apollo3zehn/BlazorMonacoRoslyn/blob/master/wwwroot/js/monaco-omnisharp.js#L21-L26) fires which in turn calls back into the [C# code](https://github.com/Apollo3zehn/BlazorMonacoRoslyn/blob/master/Services/MonacoService.cs#L95) where Roslyn finally delivers the requested diagnostics.

The same happens when a trigger character is invoked in the Monaco editor. In that case the [completions](https://github.com/Apollo3zehn/BlazorMonacoRoslyn/blob/master/wwwroot/js/monaco-omnisharp.js#L13) callback fires which again invokes a C# function in the `MonacoService.cs` file. This time Omnisharp is used to help formatting the completions.

So far so good and when I slowly edit my code in the editor, I get nice completions and diagnostics. But when I type too fast everything suddenly stops - I can still edit the code in editor but the Javascript-to-C# communication stopped working.

I have already found a possible reason why that communications stops. For this I have debugged into Blazor Components and finally got to the method [ExecuteSynchronouslyIfPossible](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/Rendering/RendererSynchronizationContext.cs#L180-L198). In my main application (not this minimalistic sample) I have seen that one of the rendering tasks got enqueued (line 187) and the subsequent task (I think it was a Javascript->C# invoke task), was also enqueued because the previous task never finished. So I suspect that somehow a rendering task never completes and blocks everything else then.

### To Reproduce
Please clone the linked repo and run it (https://github.com/Apollo3zehn/BlazorMonacoRoslyn). Then quickly type into the editor, make a small pause, then type again. You should notice that the diagnostics are not updated anymore. In the animation below I first type some arbitrary characters and after a short period the diagnostics come in from the server and get applied to the editor (red underlined code). Then I start typing again, the browser's console shows that the callbacks fire, the C# console log output also indicates that SignalR recevied an `Invocation` message, but the actual C# method is never invoked.

![BlazorDeadlock](https://user-images.githubusercontent.com/20972129/102341573-50e9a380-3f98-11eb-881f-d76e64b2deee.png)

Some notes:

- I had trouble recording that animation with the ScreenToGif tool because that tool slowed down everything and then it got very hard to reproduce that bug.
- In this sample I create a single Roslyn "AdhocWorkspace". When I instead use two separate workspaces, one for diagnostics and one for completions, I am unable to reproduce the deadlock.

--> These things let me believe that there is a multithreading or timing issue. I do not create any threads in this sample application but I think every invocation is handled on a different thread?

Do you have any idea what could be wrong? I have investigated this bug for a few days now and even tried to compile Blazor Components myself (which worked) but I was not able to replace the official nuget package with my version. Up to now I was only able to debug into Blazor using Source Link but debugging an optimized async library is no fun :(

### Further technical details
- Include the output of `dotnet --info`

```
dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.100
 Commit:    5044b93829

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- Visual Studio 2019 16.8.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We don't debug customer applications because of time required for these is long. If you can produce a minimalistic application which doesn't involve any dependencies and reliably reproduces the suspicious behavior, we will investigate this further.

**Comment by Apollo3zehn** [comment]
Thanks, I understand that this might be too time consuming. Could you please advise me how to get a non-optimized Blazor components assembly so I can debug this myself more easily? Or even better, how can I use my self compiled Components lib and replace the NuGet one? That would be a great help for me and could allow me to produce a more minimalistic assembly.

**Comment by pranavkm** [comment]
You could build ASP.NET Core from source using instructions here: https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md. Using these binaries in your app, might be a bit tricky. You could try replacing the binaries in your runtime pack (for e.g. %ProgramFiles%\dotnet\shared\Microsoft.AspNetCore.App\5.0.1) with your locally built versions. Perhaps that would help.
