### ISSUE TITLE
`HeartBeat too slow` warning

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#28688]
Recently, I got some the `HeartBeat too slow` warning and I can not see any thread starvation, the thread starvation data is from the thread pool etw event data collected by [prometheus-net.DotNetRuntime](https://github.com/djluck/prometheus-net.DotNetRuntime)

The metrics data:

![](https://user-images.githubusercontent.com/7604648/102328655-4cd27b80-3fc2-11eb-9bc0-00bbbcae13c6.png)

The warning log:

![image](https://user-images.githubusercontent.com/7604648/102328867-9622cb00-3fc2-11eb-88c9-1632bfe55f6c.png)

There's a web API project running on asp.net core 3.1, could anyone help on this, thanks in advance.

_Originally posted by @WeihanLi in https://github.com/dotnet/aspnetcore/discussions/28687_

**Comment by BrennanConroy** [comment]
From David on the closed issue:
>Look at the thread pool counters. The thread count and thread pool queue count

Could you please collect those metrics and share? Also, is this on Linux or Windows? Do you have a repro app?

**Comment by WeihanLi** [comment]
I'm sorry that it's a little difficult to reproduce, we had this case three times over the last two weeks, and we currently had not collect the thread pool queue length. I'll try my best to repro it with detail data.

And besides, could we add the thread info in the log when `HeartBeat too slow` happens so that we could find more helpful information easily, just like `StackExchange.Redis` does

I'll close this for now. Sorry for your time.
