### ISSUE TITLE
Blazor wasm error Failed to find a valid digest in the 'integrity' attribute for resource using https

### ISSUE THREAD

**Issue by julitogtu** [dotnet/aspnetcore#28692]
### Describe the bug
I have a blazor wasm app deployed to an app service but i'm getting the following error: Failed to find a valid digest in the 'integrity' attribute for resource 'domain/_framework/dotnet.wasm' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.

But it just happens if i use the https, with http i do not receive that error.

I already do some changes on the .gitattributes and also i put the followings tags on the csproj:

`
<BlazorCacheBootResources>false</BlazorCacheBootResources>
<DisableGitAutoCRLFInPublishOutput>true</DisableGitAutoCRLFInPublishOutput>
`

![image](https://res.cloudinary.com/julitogtu/image/upload/v1608142195/error_q9hpwj.png)

### Further technical details
- ASP.NET Core and blazor 5
- Azure app services

**Comment by vinovero** [comment]
I had the same issue.
I cleared the cache images and files in the browser and it solves the problem.

**Comment by julitogtu** [comment]
@vinovero l already did that, but this does not solve the issue.

**Comment by pranavkm** [comment]
@vinovero \ @julitogtu could you have a look at our steps to diagnose this particular failure and see if it helps: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures?

**Comment by julitogtu** [comment]
@pranavkm yes I did.

Look the site on https: https://dodoui.azurewebsites.net/ and over http it loads (http://dodoui.azurewebsites.net/)

If you have another idea would be great

**Comment by Ariansh** [comment]
have you modified your web.config file?

**Comment by julitogtu** [comment]
> have you modified your web.config file?

Hello, no I did not

**Comment by TanvirHridoy** [comment]
anti virus blockes these files to download check if you are using any additional antivirus like shopos

**Comment by julitogtu** [comment]
Hi @TanvirHridoy I'm not using any antivirus

**Comment by SteveSandersonMS** [comment]
@julitogtu Please try out the diagnosis script provided in the help docs and let us know what problems this indicates - https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#troubleshoot-integrity-powershell-script

Your server is returning incorrect content. We don't know why, but the script above might help to pinpoint it.

**Comment by vallgrenerik** [comment]
I also has some integrity problem, but with the service-worker.js. 
@SteveSandersonMS , is that a valid script? This is what I get (no matter what I pass into the script)

```PS C:\temp> .\integrity.ps1 "temp" "temp"
At C:\temp\integrity.ps1:313 char:40
+           if (($null -eq $assetsEntry) || $assetsEntry.Count -ne 1) {
+                                        ~~
The token '||' is not a valid statement separator in this version.
At C:\temp\integrity.ps1:326 char:40
+           if (($null -eq $assetsEntry) || $assetsEntry.Count -ne 1) {
+                                        ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidEndOfLine
```
When I change my service-worker.js as the link you posted Steve to 

```.map(asset => new Request(asset.url));```
instead of 
```.map(asset => new Request(asset.url, { integrity: asset.hash }));```
then the site works with PWA.

**Comment by SteveSandersonMS** [comment]
@javiercn Does your integrity checking script require a specific version of Powershell or something like that?

> .map(asset => new Request(asset.url));

That simply removes the integrity check altogether. It makes the error go away, but doesn't provide an explanation for why your server is returning different content than was originally built when you published. You might be OK with this, but it creates a small risk that clients might cache an invalid or inconsistent version of your application files, e.g., if a deployment takes place half way through their page load process.

**Comment by javiercn** [comment]
> @javiercn Does your integrity checking script require a specific version of Powershell or something like that?

I didn't put a specific version on it, but powershell core 6.0+?

**Comment by vallgrenerik** [comment]
> > @javiercn Does your integrity checking script require a specific version of Powershell or something like that?
> 
> I didn't put a specific version on it, but powershell core 6.0+?

Great thanks. I had PS 5.1.19041.610. The script works when I upgraded PS to 7.1.2

**Comment by vallgrenerik** [comment]
Oh OK! Im so stupid. I didn't understand what I was doing. 
After the publish, I changed index.html to adjust the base href to my subsite domain https://mycomputer/myblazorapp 
When I dont change index.html after the release, it works. 
Lesson learned: Don't fiddle with the code after it's been published. 
Thanks and sorry!

**Comment by javiercn** [comment]
@julitogtu are you still having issues with this?

I would suggest a few thing:
* Remove things from your bin and obj folders and trigger a clean solution build, that might root out something that was incorrectly cached.
* Use the script mentioned above to spot any difference between your app files and the files published by the server.

That'll help determine at wich point things go wrong

**Comment by julitogtu** [comment]
Hi all, thanks, I'll take a look today

**Comment by bharathwajv** [comment]
@julitogtu Is it fixed now?

**Comment by danroth27** [comment]
@julitogtu I suspect the reason this only happens with HTTPS has something to do with your service worker, which only run with HTTPS connections.

**Comment by julitogtu** [comment]
@bharathwajv @danroth27 it's fixed now, i just update some packages and deploy it again, however, I did not change anything on the service worker or in the manifest.json
