### ISSUE TITLE
css isolation not working

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28695]
Here is a repository to show css isolation not working.
https://github.com/musictopia2/CssIsolationNotWorking 

What happens is i have a simple component with simple css that should show not visible.
However, I also created a custom div component.  The purpose of creating the custom div component is this component may have lots of routine classes and styles that are needed for many projects.  However, I used attributesplatting so i can specify a class which should show up.  If I specify a class that is not using css isolation, it works as expected.  However, if using the css isolation, then does not work.  I hope this can be fixed.  Because there are many cases where a person is using a third party component but need to use css isolation to send to the third party component that can be rendered.

**Comment by pranavkm** [comment]
Have you looked at the docs about applying css rules to child components: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support?

**Comment by musictopia2** [comment]
I did look at the docs.  That was exactly what I looked at when i created my sample.  Tried using the deep tag but that did not work either.

**Comment by musictopia2** [comment]
The issue was not resolved.  I still have a case where css isolation does not work.  The sample shows I followed the documentation but still does not work.
