### ISSUE TITLE
Syntax highlighting lost for @* comments in <script> block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28700]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Syntax-highlighting-lost-for--comments/1284063)._

---
[severity:It bothers me. A fix would be nice]
Using VS 2019 16.8.3 on Windows 10 20H2. Razor .cshtml file with HTML followed by @section Scripts { <script type="text/javascript"> ... 
In HTML block the @* comments are highlighted green, but in script block the @* comments are not highlighted.

---
#### Feedback Bot on 12/9/2020, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/10/2020, 00:55 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Alex Gavrilov [MSFT] on 12/16/2020, 00:55 PM: 

<p>Hi Serge,</p>
<p>Thank you for reporting this issue. Unfortunately, I have not been able to reproduce this issue so far and need your help with reproducing it.</p>
<p>Does it repro in all files for you, or only in a specific file? Would you be able to share that file with me?</p>
<p>Also, would you please try running Visual Studio in Safe Mode (see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/reference/safemode-devenv-exe?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/reference/safemode-devenv-exe?view=vs-2019</a>) and see if you can still reproduce the issue?</p>
<p>Finally, would you please try running Visual Studio repair (see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019</a>) and if that fixes the issue for you?</p>
<p>Regards,<br>
Alex Gavrilov</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Fixed in 16.9-Preview3
