### ISSUE TITLE
Updating blazor page not working

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28705]
Here is a repository to show the problem.
https://github.com/musictopia2/UpdatingNotWorking 

What happens is I have a process that when i click a button, it needs to not only show other text but every second move it as well.
It does show the text.  However, its not updating the information from the style of the div.
I have a console.writeline to show that its calling the method properly.  I even used the dev tools and i can see the html updated.  However, its still not moving the text like it should.

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
