### ISSUE TITLE
Blazor Virtualize Breaks if Global div Style is Different from Assumptions

### ISSUE THREAD

**Issue by legistek** [dotnet/aspnetcore#28704]
### Describe the bug
Setting a global div style contrary to assumptions breaks `Virtualize`. The component appears to require that `div`s will globally have `overflow: visible` and `display: block`. When `Virtualize` renders it ought to explicitly set the styles of essential elements in order to work correctly and not rely on assumptions about global styles. 

### To Reproduce

```
@page "/"

<style>
    .mypage > div {
        overflow: hidden;
        display: flex;
    }
</style>

<div class="mypage">
    <Virtualize Items="cars" Context="car">
        <tr>
            <td>@car.Id</td>
            <td>@car.Name</td>
            <td>@car.Cost</td>
        </tr>
    </Virtualize>
</div>

@code {
    
    private List<Car> cars;

    protected override async Task OnInitializedAsync()
    {
        cars = await MakeTenThousandCars();
    }

    private async Task<List<Car>> MakeTenThousandCars()
    {
        List<Car> myCarList = new List<Car>();

        for (int i = 0; i < 10000; i++)
        {
            var car = new Car()
            {
                Id = Guid.NewGuid(),
                Name = $"Car {i}",
                Cost = i * 100
            };

            myCarList.Add(car);
        }
        return await Task.FromResult(myCarList);
    }

    public class Car
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Cost { get; set; }
    }
}
```

UPDATE: 
After looking at the source, I figured out a mitigation. If you wrap `Virtualize` in a `div` with `overflow: visible` and `display: block` then it is fine:

```
<div class="mypage">
    <div style="overflow: visible; display: block">
        <Virtualize Items="cars" Context="car">
            <tr>
                <td>@car.Id</td>
                <td>@car.Name</td>
                <td>@car.Cost</td>
            </tr>
        </Virtualize>
    </div>
</div>
```

Maybe this is by design? I would have assumed that `Virtualize` would create its own scrolling `div` so as not to be reliant on what kind of container it's in.

In any event I didn't see anything in the documentation explaining this, so even if it's not a bug it might be helpful to explain this better in the docs. Thanks!

**Comment by pranavkm** [comment]
@legistek looks like you figured out a workaround for your issue. Your initial css rules was affecting Blazor's placeholder divs which would break it. We plan on adding a doc section (tracked by https://github.com/dotnet/AspNetCore.Docs/issues/20978) that covers all of the requirements for using the Virtualize component.

**Comment by legistek** [comment]
Hi @pranavkm yes in that particular example I could resolve it through styling the outer `div`.

In another example I had to go further and force the Virtualizer's "spacer" `div` to have `overflow-y: visible` using the `:first-child` selector. Basically hacks that depend on the inner workings of your `Virtualize` component, which is definitely not best practice. So documentation would definitely be helpful, but I really think that you should render the component to make sure that the div's it renders don't get ruined by external styling. IMO. :) Thanks!

**Comment by legistek** [comment]
So the issue is really not resolved. The workaround is a hack that would easily break if you make internal modifications to the component. If Virtualize breaks because of external CSS, that's a bug or at minimum something that needs to be very clearly documented.
