### ISSUE TITLE
Move dotnet-watch into dotnet/sdk repo

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#28713]
The `dotnet-watch` tool has no runtime impact. To enable faster iteration and fixes we need to move it to the dotnet/sdk repo to be able to release it with SDK ship cycle.

**Comment by gfoidl** [comment]
@mkArtakMSFT can please update the type in the issue-title? 
I don't want to be pendantic (especially as my typing isn't the best sometimes), but while searching for issues here on GH it might not show up with the typo.

**Comment by pranavkm** [comment]
Waiting until we can merge the removal PR: https://github.com/dotnet/aspnetcore/pull/29722
