### ISSUE TITLE
AntiforgeryValidationException preventing Blazor Server Side app to start

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#28726]
### Describe the bug
After IIS restart, when I visit `localhost/someblazorroute/` I start getting following error
![image](https://user-images.githubusercontent.com/3494407/102639365-3c083e00-4159-11eb-8150-8e4de77ef7b2.png)
and from that point I'm stuck (regardless of user and regardless route visited).

However, when I visit the root page `localhost/` first I'm redirected to login page and everything works as expe

### To Reproduce
use `endpoints.MapBlazorHub().RequireAuthorization();` and cookie authentication, deploy to IIS using release configuration, restart IIS and visit localhost/counter.

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<IISServerOptions>(options => options.AutomaticAuthentication = false);
            services.AddServerSideBlazor();

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.LoginPath = "/Auth/Login";
                    options.LogoutPath = "/Auth/Logout";
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new Microsoft.AspNetCore.Localization.RequestCulture(CultureInfo.InvariantCulture.Name, "sk")
            });

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages().RequireAuthorization();
                endpoints.MapBlazorHub().RequireAuthorization();
                endpoints.MapFallbackToPage("/_Host");
            });
        }

### Exceptions (if any)
```
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {907560ad-e64e-4cca-a2db-9f315b87fc5d} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\inetpub\wwwroot
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
       ---> System.Security.Cryptography.CryptographicException: The key {1aaa8d08-286b-466d-ad02-c0cb7bb4ac09} was not found in the key ring.
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

### Further technical details
- ASP.NET Core version 5.0.0

> Host (useful for support):
>   Version: 5.0.0
>   Commit:  cf258a14b7
> 
> .NET SDKs installed:
>   No SDKs were found.
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by blowdart** [comment]
This is why

```
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {907560ad-e64e-4cca-a2db-9f315b87fc5d} may be persisted to storage in unencrypted form.
```

You need to either run the IIS prep script which used to be in the IIS hosting docs. but I can't find it any more, so it's [here](https://github.com/dotnet/aspnetcore/blob/a784f4575b738ec5b7c6f5cfff2b1fee10de5118/src/DataProtection/Provision-AutoGenKeys.ps1) and I've logged a doc bug

Or you [configure data protection ](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0)for another storage mechanism suitable for your setup.

If you're only going to run on a single server, the IIS prep script is easiest.

**Comment by Liero** [comment]
Yes, I get it, but I still think it's a bug. A single request with wrong token should not take down the entire application.

How do you explain, that navigating to site root redirects to login page, but navigating to another blazor page first takes the app down and then navigaging to site root returns error even in inprivate/incognito mode?

**Comment by blowdart** [comment]
OK yes, that is weird, and blazor specific. So let's tag it back.

**Comment by javiercn** [comment]
@Liero thanks for contacting us.

This is by design, you should be applying require authorization to the page, not just the endpoint. The issue is that when you visit the url for the page it will authenticate and generate an antiforgery token for the authenticated user but when you visit a "client" url it will go through the fallback that doesn't contain the authorization piece hence the user will not be necessarily authenticated and the token will fail.

The solution is to apply `@attribute [Authorize]` to the page

**Comment by Liero** [comment]
thanks @javiercn: by "the page" you mean blazor pages or razor page that hosts the app?

Anyway, this does not explain why after visiting the "client url", the app stays in faulted state. This single request should not affect other requests, should it?

**Comment by javiercn** [comment]
@Liero `[Authorize]` on `_Host.cshtml`

Can you paste the callstack from the server logs that is tearing down the application?

**Comment by Liero** [comment]
@javiercn: I only have the stacktrace that I posted in the question. Is it enough? Not sure how to get callstack, because it never paused debugger

**Comment by mariohik** [comment]
Guys,
I'm trying to update my Blazor WebAssembly and facing the same issue.
The error only happens with IIS.
The application was working with .net 3.1 (3.2).
Is there any other word about it?

**Comment by Liero** [comment]
@mariohik: running the powershell script helped me. Read this comment: https://github.com/dotnet/aspnetcore/issues/28726#issuecomment-748226348
