### ISSUE TITLE
Unable to suppress Automatic Model validation in aspnetcore 3.1 Web API

### ISSUE THREAD

**Issue by thisisjagan** [dotnet/aspnetcore#28724]
# Unable to suppress Automatic Model validation in aspnetcore 3.1 Web API

I am trying to suppress the Automatic Model Validation that comes with .Net Core Web API 3.1. I have added the following line of code in ConfigureServices function in the StartUp.cs file and created a custom Action Filter. However, whenever a I post a empty body or no body, I get the default 415 error from the API. Action Filter - OnExecuting menthod gets called only when I have some content in the body. 

# Code:

![image](https://user-images.githubusercontent.com/41620595/102614225-dc5e6280-4159-11eb-9189-0ca2518d3788.png)

![image](https://user-images.githubusercontent.com/41620595/102614269-ef713280-4159-11eb-901c-d4e8644e8118.png)

![image](https://user-images.githubusercontent.com/41620595/102614255-e84a2480-4159-11eb-8960-38ba95571478.png)

# Nuget Packages:

![image](https://user-images.githubusercontent.com/41620595/102614340-10398800-415a-11eb-818d-6aa649f873ea.png)

# Error from .NET Core 3.1 Automatic Model validation:

![image](https://user-images.githubusercontent.com/41620595/102614560-74f4e280-415a-11eb-94ba-1b61568704e4.png)

**Comment by pranavkm** [comment]
The 415 error indicates that the request includes a Content-Type that cannot be read by any formatters required to deserialize the model. That's not a model validation error and consequently the flag that you're configuring does not have any effect on it.

What is it that you'd like to do if the action receives a body that cannot be formatted by any supported formatters (for e.g. the content-type is `text/plain`)?

**Comment by thisisjagan** [comment]
Thank you so much for clarifying. It makes sense now. I would like to catch the exception when the action receives a body that cannot be formatted by any supported formatters and throw a custom error message.

**Comment by pranavkm** [comment]
You could provide an action filter that replaces https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/UnsupportedContentTypeFilter.cs which is registered as a global MVC filter (`MvcOptions.Filters`) with a custom implementation. Alternatively you could write a result filter that produces a custom response when the action result is an [`UnsupportedMediaTypeResult`](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/UnsupportedContentTypeFilter.cs#L29)
