### ISSUE TITLE
Microsoft.AspNetCore.Mvc.NewtonsoftJson: package update info wrong for .NET Core 3.1

### ISSUE THREAD

**Issue by markm77** [dotnet/aspnetcore#28728]
Hi there,

I have a C# solution which uses the Microsoft.AspNetCore.Mvc.NewtonsoftJson package. Unfortunately since the release of .NET 5, both Rider and Visual Studio try to update it in my .NET Core 3.1 projects to v5.0.1 which fails.

The root problem can reproduced by running the command ```dotnet list package --outdated``` and observing the output:

```
Project `X` has the following updates to its packages
   [netcoreapp3.1]: 
   Top-level Package                              Requested   Resolved   Latest
   > Microsoft.AspNetCore.Mvc.NewtonsoftJson      3.1.10      3.1.10     5.0.1
```

I guess some meta-data need fixing somewhere?

BR,
Mark

**Comment by Pilchie** [comment]
Unfortunately, NuGet doesn't support packages like this that are tied to a TFM.

**Comment by markm77** [comment]
Thanks for the reply. Does this mean you have no way to tell Nuget v5.0.1 requires .NET 5.0. I don't seem to have this issue with any other package (presumably many have .NET 5.0 specific updates).

**Comment by Pilchie** [comment]
Well, the package does only have assets for .NET 5, but that's not enough for NuGet.

**Comment by markm77** [comment]
Does this info explain how Microsoft.AspNetCore.Mvc.NewtonsoftJson v5.0.1 could be made to have a dependency on .NET 5.0?

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#declaring-dependencies-advanced

**Comment by Pilchie** [comment]
But we don't want it to support multiple frameworks.  We want it to support 5.0 only, which is what it currently does.  I'm not sure why that shows as an updated to an app targeting 3.1.

**Comment by markm77** [comment]
> But we don't want it to support multiple frameworks. We want it to support 5.0 only, which is what it currently does. I'm not sure why that shows as an updated to an app targeting 3.1.

That's what I thought. And I can confirm if the update is attempted it fails on a .NET 3.1 project.

The problem is NuGet keeps suggesting the incorrect update. It does so in Rider, Visual Studio and on the command line. And then when you attempt the update it fails.

**Comment by markm77** [comment]
Just to be clear: I am certainly not requesting support for multiple frameworks. I just don't want to be offered a .NET 5.0-only update in a .NET 3.1 project. If you would like me to collect any particular diagnostics, I'm more than happy to do so.

**Comment by Pilchie** [comment]
This is an issue for https://github.com/NuGet/Home.

**Comment by Pilchie** [comment]
This issue was moved to NuGet/Home#10419
