### ISSUE TITLE
@microsoft/signalr not working in ios mobile browsers like safari, mozilla and chrome

### ISSUE THREAD

**Issue by Sivabalan96** [dotnet/aspnetcore#28721]
We made a web application which uses @microsoft/signalr to perform handshake and connect calls. It worked well in both web and android browsers, but not in ios mobile web browsers as mentioned above.

All mobile browsers throws an exception as "Not found",

Technical details:-
- ASP.NET Core 
- Reactjs

**Comment by shirhatti** [comment]
It sounds like a 404 which indicates your client may be pointing at the wrong URL. Can you share more information?

**Comment by Sivabalan96** [comment]
Yes, We checked the URL, We are pointing the correct URL, It worked well in both web and android mobile browsers, but not in ios mobile browsers(SignalR not connecting in ios mobile browsers).

**Comment by Sivabalan96** [comment]
Let me know what additional information required?

**Comment by BrennanConroy** [comment]
> All mobile browsers throws an exception as "Not found",

Is this a 404 Not Found? Or is this a different error like "@microsoft/signalr could not be found".

Can you share a network trace and logs? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0
