### ISSUE TITLE
Blazor Webassembly Reflection fails when published System.Runtime

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28738]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-Webassembly-Reflection-fails-when/1289484)._

---
<p>I have started to work with Blazor and i have setup a hosted web-assembly application.</p> <p>Within the App.Razor, i am using lazy loaded assemblies which are loaded from the API and then uses Reflection to inspect them for an implementation of an interface. new routes are added based on this interface etc.</p> <p>This works perfectly fine when debugging via Visual Studio, however, when i publish the solution, i get an error stating System.Runtime 5.0.0.0 is missing when trying to perform the above.</p> <p>I have tried this using Blazor server and this is working perfectly fine.</p> <p>I have tried to work with adding &lt;BlazorWebAssemblyEnableLinking&gt;false&lt;/BlazorWebAssemblyEnableLinking&gt; to see if the problem is caused bu the linking but the issue still exists. </p> <p>Any advice would be much appreciated.</p> <p>Thanks in advance</p>

---
#### Feedback Bot on 12/17/2020, 00:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
You'll need to use the `<PublishTrimmed>` flag as described in https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/configure-trimmer to disable trimming. That said, turning off trimming would significantly bloat up your application size. Consider alternative designs which might not require turning it off.
