### ISSUE TITLE
ASP.Net Core Cookies conflict when two sites are on the same host 

### ISSUE THREAD

**Issue by Vaccano** [dotnet/aspnetcore#28734]
### Describe the bug
When two or more ASP.Net Core 3.1 MVC sites are hosted on the same host, their cookies conflict.

### To Reproduce
1. Create two ASP.Core MVC projects.  
2. Set up each of them of them to work with DIFFERENT OIDC applications. (ID and Secret)
3. Run the first project (lets call it App One) and login.  
      * Take note of its cookies:  There should be an antiforgery cookie and a single `.AspNetCore.Cookies` cookie that is set to a encrypted value about 1k long.
4. Run the second project (lets call it App Two) and login.  
      * Take note of the cookies now.  The antiforgery cookie should still be there, as well as the `.AspNetCore.Cookies` cookie (still set to a encrypted value about 1k long.)  
      * BUT, you will also see 4 more cookies.  Called `.AspNetCore.CookiesC1`, `.AspNetCore.CookiesC2`, `.AspNetCore.CookiesC3` and `.AspNetCore.CookiesC4`.  The first 3 will be about 4K in size each.  The last one will be about 1K in size.
5. When you try to refresh the page for App One it will show a "Request Too Long" error page.  (Shown in the exceptions section below.)

Here is what I think is happening:
1. App One loads and only needs one `.AspNetCore.Cookies` cookie, so it makes it.
2. App Two loads and for some reason needs more cookies, so it makes the C1-C4 cookies.
3. At this time, App Two tries to set the main `.AspNetCore.Cookies` cookie to the value of "chunks-4", but that cookie is already there from App One. So it fails.  This puts the total size of the cookies to over 16K.
4. When App One is reloaded, it sees all the cookies and tries to send them, but they now total over 16K so the web server rejects the the request as too big. (and loads the error page indicated in the exception section below).

### Exceptions (if any)
Http Error Page:

>Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.

### Further technical details
- ASP.NET Core version **3.1.8**
- Include the output of `dotnet --info`
	<details>
		<summary> Click to see Output of `dotnet --info`</summary>

	PS C:\Users\18773> dotnet --info
	.NET Core SDK (reflecting any global.json):
	 Version:   3.1.403
	 Commit:    9e895200cd

	Runtime Environment:
	 OS Name:     Windows
	 OS Version:  10.0.18362
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

	Host (useful for support):
	  Version: 3.1.10
	  Commit:  1721e39439

	.NET Core SDKs installed:
	  2.1.505 [C:\Program Files\dotnet\sdk]
	  2.1.509 [C:\Program Files\dotnet\sdk]
	  2.1.519 [C:\Program Files\dotnet\sdk]
	  2.1.602 [C:\Program Files\dotnet\sdk]
	  2.1.604 [C:\Program Files\dotnet\sdk]
	  2.1.801 [C:\Program Files\dotnet\sdk]
	  2.2.202 [C:\Program Files\dotnet\sdk]
	  2.2.204 [C:\Program Files\dotnet\sdk]
	  2.2.401 [C:\Program Files\dotnet\sdk]
	  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
	  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
	  3.1.403 [C:\Program Files\dotnet\sdk]

	.NET Core runtimes installed:
	  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

	</details>
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: **Visual Studio 2019, 16.7.7**

**Comment by Tratcher** [comment]
These two sites share the same host name, port, and path? These kinds of resource conflicts will happen in local development when switching between sites. The client can't tell that they're different so it pools all of their assets like cookies.

Related: https://github.com/dotnet/aspnetcore/issues/4639, the cookie chunker doesn't do a full delete unless you explicitly call sign-out, it just overwrites. That's adequate most of the time because an apps cookies don't tend to change size very much for the same user. It's worse in this case because there are two different apps with different size cookies.

**Comment by Vaccano** [comment]
They seem to get a path of `/` no matter what.  But it is on my dev machine that I am seeing this.  Maybe when I move to my hosted containers (rather than my debug ones) it will automatically add the path and keep them separate?

**Comment by Tratcher** [comment]
Oh, they're on different paths? The cookies all default to "/", but you can set that on the cookie auth options. It willalso use the app PathBase if you set that (e.g. UsePathBase).
https://github.com/dotnet/aspnetcore/blob/90febebe4c12e6442f1ce31ffe13b34ad0b4acff/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs#L15-L24

**Comment by mqudsi** [comment]
ASP.NET Core uses a per-application unique hash for the name of the cookie used for the antiforgery token, but uses a fixed cookie name for the auth cookie. In our case, we have a main application at `/` and a separate application at `/foo`, so even though `/foo` sets its cookie with path `/foo`, it still ends up reading the first cookie set by `/` until we changed the name of the cookie at `/` to something else. It would be nice if the default auth cookie name were also unique per-app.

**Comment by blowdart** [comment]
I have concerns that a unique cookie name per app which will break some assumptions, and it will certainly break shared scenarios where you want the cookies to work across all. Manual naming is the safest choice, and we won't be making any changes I'm afraid.
