### ISSUE TITLE
[SignalR] mobile app (not Xamarin) support

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/aspnetcore#28756]
I might be missing something in the docs (if so please let me know) however it seems to me that SignalR is missing a **massive** opportunity in the mobile space for real time pub/sub.

As an Azure customer we always look first to see if a feature has a good fit with existing Azure technology. Our requirement in this instance is real time pub/sub between our Azure backend (particularly CosmosDb & functions) and iOS, Android and Web client apps.

Our iOS and Android apps are written using Flutter. The web app is written using React.

We can capture all the required real time **database** updates in the CosmosDb change feed.

Then the question is - how can we **push** these updates to all the (listening) mobile and web clients ? SignalR seemed the goto solution from Azure. However there is nothing of any substance for mobile (ie non Xamarin!!) apps ??  https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-5.0#unsupported-clients

Why is there no focus on providing SignalR to mobile platforms ? Sure we can use things like Pusher, Pubnub etc. but honestly, we'd prefer not to and rather would like to tightly integrate instead across Azure services.

Interested in the situation here, many thanks.

**Comment by BrennanConroy** [comment]
There is a Swift client from a community member (who was previously on the team), we're also working on a C++ client.

**Comment by davidfowl** [comment]
Xamarin is actually fully supported and we should make our docs reflect that.

**Comment by jamesmontemagno** [comment]
@davidbritch

**Comment by BrennanConroy** [comment]
We mention Xamarin in our .NET Client supported platforms section. https://docs.microsoft.com/aspnet/core/signalr/supported-platforms?view=aspnetcore-5.0#net-client

I think the customer was mostly saying we don't have a client for non-xamarin mobile apps.

**Comment by davidfowl** [comment]
AH, I missed the non. Still, I'm guess our docs are missing Xamarin examples. 

@SogoGolf we've had some demand for iOS, we already have an android compatible client. There's also https://github.com/moozzyk/SignalR-Client-Swift for iOS.

**Comment by SogoGolf** [comment]
thanks - any plans for MicroSoft to provide a (Swift) iOS SDK ?

**Comment by davidbritch** [comment]
I have a Xamarin sample/doc (which isn't live anymore) that I can donate to this docset if required.
