### ISSUE TITLE
Not able to debug blazorwasm project in VSCode

### ISSUE THREAD

**Issue by Ogieeeeee** [dotnet/aspnetcore#28755]
### Describe the bug
Well, literally after pressing f5 to debug I'm getting some weird error saying that "Could not load source "projtname.dll"/path
I've followed the docs too on how to debug blazorwasm projects but not success. 

Also getting these weird errors printed in terminal: 

fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-9864B35175FF237AFA7C57093727622A:::1023 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "code": -32000,
        "message": "No script for id: dotnet://188_3"
      } ]

### To Reproduce
create new blazorwasm project set breakpoint at counter method press f5 in vscode.

### Further technical details
- BlazorWasm
- Dotnet version: 5.0.101
- VSCode version: 1.52.1

**Comment by kattunga** [comment]
Same problem here

**Comment by captainsafia** [comment]
Thanks for opening this issue folks! I believe I might have an idea what's going on. Can you confirm two things?

- Does debugging within the browser as [documented here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser) work?
- What version of VS Code are you using?

**Comment by Ogieeeeee** [comment]
Hi senpai,

**_- Does debugging within the browser as documented here work?_**
No :[

**_- Can you share your launch.json?_**
```
   "version": "0.2.0",
   "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}"
        }
    ]
```
**_What version of VS Code are you using?_**
Version: **1.52.1**

**Comment by captainsafia** [comment]
> - Does debugging within the browser as documented here work?
> No :[

Bummer. Can you share a repro project? If not, can you share the `dotnet-info` for the project where the problem occurs?

**Comment by Ogieeeeee** [comment]
> Bummer. Can you share a repro project? 

Hey it's a brand new `dotnet new blazorwasm` project

> If not, can you share the `dotnet-info` for the project where the problem occurs?


.NET SDK (reflecting any global.json):
 Version:   5.0.101     
 Commit:    d05174dc5a  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19041
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Ogieeeeee** [comment]
This is what I am seeing when trying to debug: 
![image](https://user-images.githubusercontent.com/22215187/103559438-69bde880-4eb6-11eb-8cd2-7867c87f669e.png)

**Comment by captainsafia** [comment]
Does the same problem occur when you use a two-step debugging configuration?

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (Blazor Standalone)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "run"
            ],
            "cwd": "${workspaceFolder}",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        },
        {
            "name": ".NET Core Debug Blazor Web Assembly in Chrome",
            "type": "pwa-chrome",
            "request": "launch",
            "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
        }
    ]
}
```

**Comment by Ogieeeeee** [comment]
Hey, not getting these weird javascript errors anymore when running your configuration. But this time it doesn't stop at all, keeps counting.

![image](https://user-images.githubusercontent.com/22215187/103680505-8d506400-4f86-11eb-9108-edf72a413f49.png)

**Comment by captainsafia** [comment]
Ah: try adding `"url": "https://localhost:5001"` to the second config.

**Comment by Ogieeeeee** [comment]
![image](https://user-images.githubusercontent.com/22215187/103923475-72602a00-5115-11eb-981d-cf98517e20af.png)

**Comment by captainsafia** [comment]
@Ogieeeeee Can you share the output of the `dotnet run` process that is used to start the application server?

For context, it appears that there is an issue connecting the debugger to the debugging proxy. This can happen for a couple of reasons:

- the debugging proxy was not launched in the first place
- there is a firewall or proxy on your machine that prevents connections over localhost

**Comment by Ogieeeeee** [comment]
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\OneDrive\Documenten\Ogie\Projects\C#\Blazor\Blazorwasmdebug

**Comment by ilonatommy** [comment]
The problem still persists, even sample application cannot get debugged. Both configurations: of blazorwasm type and suggested by @[captainsafia](https://github.com/captainsafia) two step configuration. In both cases, the application launches but no symbols get loaded for Client.csproj.

VS Code: 1.64
Dotnet: 6.0.1

**Comment by captainsafia** [comment]
@ilonatommy Can you file a new issue for this?
