### ISSUE TITLE
Put blazor generated component code inside project

### ISSUE THREAD

**Issue by kamran65536** [dotnet/aspnetcore#28762]
## Summary

Put component's generatd  code inside the project.

## Motivation and goals

In order to create complicated blazor components you may need to code a lot and current intellisense performance is really annoying. Also if you put your code in code behind file you may also experience intellisense incompatibility between generated code and code behind.

It is suggested to push code generation to normal C# project compilation time to reduce incompatibilities and complexity between razor code generator and behind code.

## Examples

In case of adding new component it is suggested to add the following files too:
```
.
+-- XComponent.razor
|    +--  XComponent.razor.cs
|    +-- XComponent.razor.design.cs
```

then trigger code generation for XComponent.razor on file save.

**Comment by pranavkm** [comment]
@kamran65536 thanks for your suggestion. This is unlikely a direction we're going to take with how Razor files are code generated.

> current intellisense performance is really annoying

Have you tried using the [Experimental Razor editor](https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio)? If you continue seeing issues with this, we'd be interested in finding out more about your experiences. FYI  @NTaylorMullen
