### ISSUE TITLE
Deps.json file is not generated for regular Blazor WASM app build

### ISSUE THREAD

**Issue by alexkreskiyan** [dotnet/aspnetcore#28768]
### Describe the bug
`xxx.deps.json` file is not generated for basic Blazor WASM `dotnet build` execution.
Deps file is needed to load assembly with it's dependencies through `DependencyContext` in `AfterBuild` target.

### To Reproduce
```
dotnet new blazorwasm -o Wasm
cd Wasm
dotnet build
ls -lgG bin/Debug/net5.0
```
Results in:
```
drwxrwxr-x 2  4096 Dec 21 01:40 ref
-rw-rw-r-- 1 17408 Dec 21 01:40 Wasm.dll
-rw-rw-r-- 1 13828 Dec 21 01:40 Wasm.pdb
-rw-rw-r-- 1   250 Dec 21 01:40 Wasm.StaticWebAssets.xml
drwxrwxr-x 3  4096 Dec 21 01:40 wwwroot
```

### Exceptions (if any)
No

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     pop
 OS Version:  20.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by pranavkm** [comment]
This is intentional of sorts. Blazo WebAssembly does not have the same bootstrapping mechanism as .NET Core on win / linux etc. Files need to be downloaded over the network, and the dotnet muxer isn't used.

Could you elaborate on what you're trying to do?

**Comment by alexkreskiyan** [comment]
For sure. Inspired by https://github.com/Taritsyn/LibSassHost and https://cssinjs.org, I've been trying to implement CSS in CS library. 
Plugged into WebAssembly project as Nuget dependency, it would add AfterBuild target, that would load Blazor assembly with dependencies, run through predefined entry point (like EF Core does), computing styles, and writing CSS to the output `wwwroot` folder. 
As pointed above, it won't work in compile-time without the ability to discover all assembly dependencies.

**Comment by pranavkm** [comment]
> that would load Blazor assembly with dependencies, run through predefined entry point 

Did you mean the way `dotnet-ef` does? `WebAssemblyHostBuilder` assumes [it's running in a WebAssembly environment](https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyHostBuilder.cs#L60-L65) so that's going to throw if you attempt to run `Program.MainAsync` outside a browser sandbox environment.

If all you needed to do was look at the list of files being copied to the output dir, perhaps inspecting the blazor.boot.json would suffice? It's not something we necessarily document, but it's also unlikely to change dramatically between releases.

**Comment by alexkreskiyan** [comment]
As far as I remember, `dotnet-ef` does execute method with predefined name, like `IHostBuilder CreateHostBuilder(string[] args)`.
