### ISSUE TITLE
Experimental Razor Editor - IntelliSense Broken (RZ10012) for linked/embedded Blazor components

### ISSUE THREAD

**Issue by abbotware** [dotnet/aspnetcore#28766]
### Describe the bug
IntelliSense is broken for any imbedded / third-party blazor component added to a razor file.  The editor shows the error: **RZ10012 - Found Markup Element with unexpected name 'Control'**

### To Reproduce

1. create a razor library project.  
2. Add a reference to DevExpress (or any other 3rd party blazor control)
3. create a razor file
4. add any blazor component from step 2 into the razor file

you should see the 'squiggle' appear under the control as follows:

![image](https://user-images.githubusercontent.com/2100564/102719192-a71d5600-42ba-11eb-95a7-839a027e3b0f.png)

switching off the Experimental Razor Editor fixes the problem

### Further technical details
- ASP.NET Core version 5.0 / SDK 5.0.1
- VS Version 16.8.3

**Comment by NTaylorMullen** [comment]
The goal here is to investigate what's breaking and then talk about what a fix might be / when it should be done.

**Comment by NTaylorMullen** [comment]
The goal here is to investigate if this still happens. I believe I indirectly fixed this when I fixed: https://github.com/dotnet/aspnetcore/issues/29271

**Comment by ryanbrandenburg** [comment]
This did not repro for me on latest, so I'm going to close this out. @abbotware if you still experience this after upgrading to 16.9Preview4 or above let us know and we'll re-open.
