### ISSUE TITLE
Cross-site scripting (XSS), (Reflected) due to model validation

### ISSUE THREAD

**Issue by topagarwal** [dotnet/aspnetcore#28774]
I am using  Asp .Net core 3.1 for web Apis. I have decorated the controller with [ApiController] attributes and have not specified any flags in ConfigureServices in Startup.cs which lets the framework do model validation. For the routes which are of patterns : 
` HttpGet[ "v2/tenants/75/products?maxPageSize"]
public IActionResult(Guid tenantId, uint maxPageSize) {
} `

In this is user passes something like - https://core.azure.net/v2/tenants/75/products?maxPageSize='<script>alert(10754603)</script>' 

Then the model validation errors outs and gives back the original value in the ProblemDetails back to the user.  e.g.
`{"errors":{"tenantId":["The value '75' is not valid."],"maxPageSize":["The value '<script>alert(10754603)</script>' is not valid."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"741fd41f8809584f-00"} `

Kestrel trace logs says:
` Request was short circuited at action filter 'Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter'.
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11] `

Attackers can leverage this to execute malicious scripts on the vulnerable users. In this case, the call is not reaching our controllers so using default formatters is not going to help. We could possibly implement custom ProblemValidationDetails but I believe this is more of core problem and could be fixed in the framework by checking the return values in the Default implementation. Having custom implementation in code could lead to maintenance issue and also loosing on some of the improvements that might come up in future releases.

**Comment by pranavkm** [comment]
> Attackers can leverage this to execute malicious scripts on the vulnerable users

This should only be a problem if you emit the error message as raw HTML to the output. Output emitted by MVC is HTML encoded by default. In this case, markup produced by ValidationMessage \ ValidationSummary that would display the error message text is HTML-encoded. 

In the example you cited, the app's producing JSON which would not be rendered as markup by the browser so it wouldn't be a source for XSS.

Adding @blowdart in case they would like to add more. Lastly, we strongly recommend reporting (possible) security vulnerabilities privately as described in https://github.com/dotnet/aspnetcore/security/policy.

**Comment by blowdart** [comment]
I agree with @pranavkm. 

If that example caused XSS it's an application error, not a framework error. You'd have to work very hard as a developer to write code to enable XSS from this, and eschew industry practices for rendering output.

**Comment by topagarwal** [comment]
Thanks for the responses. Sorry about violating the posting policy. Good learning for me. Will take care next time.
