### ISSUE TITLE
Blazor NotFound returns wrong 200 OK HttpStatusCode

### ISSUE THREAD

**Issue by vindberg** [dotnet/aspnetcore#28776]
Using .Net 5.01 with Blazor serverside.

### Describe the bug
When using the "NotFound" template In the App.razor page it will return a HttpStatuscode of 200 (OK), which I believe is a mistake. It should return the HttpResponse with statuscode 404 for Page not found.

### To Reproduce
Simply goto a blazor page/url that doesn't exist (not configured in any pages with routing).

**Comment by vindberg** [comment]
Thanks for adding the label. Any chance this will get into the next release? Sounds easy :)

**Comment by mihaimyh** [comment]
Any news on this?

**Comment by voltcode** [comment]
+1 this is super important for hosting api and blazor code in one service.
I have no idea why on earth this is not top priority, returning wrong HTTP error codes for should be seen as urgent bugs, as they breach protocol.

**Comment by ergincelik** [comment]
Maybe this link can help you
https://stackoverflow.com/a/69404900/2123797

**Comment by vindberg** [comment]
@SteveSandersonMS please consider adding this to the next release. It's important for SEO and should be easy to fix on your end. Thanks.

**Comment by HybridSolutions** [comment]
Any news on this?? It's 2022 and this bug still exists :(

**Comment by vindberg** [comment]
Yes, I also urge the team to focus on these "web" aspects of blazor so that it can be used for production websites!

**Comment by mreinhart2805** [comment]
It is unbelievable that this bug is still not fixed. Whoever is responsible for this, do something.

**Comment by mkArtakMSFT** [comment]
After some further discussion we believe that this will be solved automatically when we do https://github.com/dotnet/aspnetcore/issues/42003 work. So closing as a duplicate.

**Comment by vindberg** [comment]
Please reconsider taking this into the 7.x release. It's hurting SEO bigtime. The "NotFound" template is already defined - just as the 404 StatusCode to the response!!!

**Comment by vindberg** [comment]
@mkArtakMSFT Please give us a workaround in the meantime!? @SteveSandersonMS maybe you can help here?

Please make Blazor server great again - this is one of the things hurting the most!

**Comment by EmilAlipiev** [comment]
> Maybe this link can help you https://stackoverflow.com/a/69404900/2123797

this only helps for Server side but not Wasm
