### ISSUE TITLE
[blazor wasm] Uncaught (in promise) DOMException: The user aborted a request。

### ISSUE THREAD

**Issue by Yuanxw612** [dotnet/aspnetcore#28775]
All API requests prompt an error
Uncaught (in promise) DOMException: The user aborted a request。

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We've had many projects where this worked. We believe this is an issue in your code. Consider asking in [StackOverflow](https://stackoverflow.com) if you are facing issues with it.

**Comment by Seanxwy** [comment]
@mkArtakMSFT This is also a problem with the wasm hosted project demo request API set up in VS. It's not a code issue

**Comment by yanjianyigaii** [comment]
any update on the root cause of this issue? we are having the same.

**Comment by Seanxwy** [comment]
There is no progress and the problem still exists. I wonder why it has not been dealt with  @yanjianyigaii
