### ISSUE TITLE
Windows Authentication in ASP.NET Core 5 is not working in linux host

### ISSUE THREAD

**Issue by amd-9** [dotnet/aspnetcore#28785]
### Describe the bug
Windows Authentication in ASP.NET Core 5 is not working in properly configured (according the Microsoft docs) linux system. 

### To Reproduce

- Clone small sample project **ASP.NET Core 5 MVC** from my [repo](https://github.com/amd-9/aspnetcore-winauth)
- Add linux host to Active Directory domain according to Microsoft [docs](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller)
- Configure Linux environment according to Microsoft [docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#linux-and-macos-environment-configuration)

### Exceptions (if any)

After entering AD Credentials in browser

```
GssApiException: GSSAPI operation failed with error - An unsupported mechanism was requested.
Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
### Further technical details
- Linux Host OS: Ubuntu 20.04
- AD - Windows Server 2019
- Client OS - Windows 10 20H2
- Client browser - Microsoft Edge 84.0.522.52 
- ASP.NET Core 5
- Output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:

 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```
- project started via `sudo dotnet run` inside **WebClientApp** folder
- Network interface activity screenshot from WireShark `192.168.77.31 `(Client), `192.168.77.39` (Linux Host)
![image](https://user-images.githubusercontent.com/9817513/102910644-f23a9300-448b-11eb-934f-ee0ca3769e1e.png)

**Comment by blowdart** [comment]
@JunTaoLuo @Tratcher

**Comment by Tratcher** [comment]
> After entering AD Credentials in browser

You shouldn't need to enter AD credentials into the browser, it should use the local credentials by default. The client is AD joined, correct?

`NTLMSSP_NEGOTIATE` implies it's using NTLM rather than Kerberos. NTLM is not supported in this configuration. I wonder how wireshark displays a kerberos handshake.

Can you share that wireshark trace so we can take a closer look?

**Comment by amd-9** [comment]
> You shouldn't need to enter AD credentials into the browser, it should use the local credentials by default. The client is AD joined, correct?

@Tratcher Yep. Client PC is AD joined. It is a fresh Windows 10 (20H2) install and user is logged-in under AD account but Edge still prompts for password on first attempt to enter `Home/Privacy`

> Can you share that wireshark trace so we can take a closer look?

Sure! Here is [pcap](https://1drv.ms/u/s!AvCdYss2kxrihzE_4fHO-KkXWEjK?e=tyVZ9a) file from Linux Host

**Comment by Tratcher** [comment]
You're using IPs in the URL and Host header. Kerberos is very name sensitive, you have to use fully qualified domain names (myservice.mydomain.com) when making the request. This should match the SPNs you used when creating the kerberos ticket.

**Comment by amd-9** [comment]
> You're using IPs in the URL and Host header (`Host: 192.168.77.39:5003`). Kerberos is very name sensitive, you have to use fully qualified domain names (myservice.mydomain.com) when making the request. This should match the SPNs you used when creating the kerberos ticket.

To make things clear I've added a new fresh installed Ubuntu host (`192.168.77.47`. Hostname: `usrvhost3`) and went through Microsoft step by step configuration docs again.

I've added `webapp5.sso.local` as a DNS "A" record pointing to 192.168.77.47 and tried to navigate to `webapp5.sso.local/Home/Privacy` via browser on client machine. I've recieved a new error. 

```
GssApiException: GSSAPI operation failed with error - Unspecified GSS failure. Minor code may provide more information (Request ticket server HTTP/webapp5.sso.local@SSO.LOCAL not found in keytab (ticket kvno 3)).
Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Step by step configuration result details**

1. Add new web service SPNs to the machine account

`setspn -L usrvhost3` result

```
CN=USRVHOST3,CN=Computers,DC=sso,DC=local:
        HTTP/webapp5.sso.local
        HTTP/webapp5@SSO.LOCAL
        RestrictedKrbHost/USRVHOST3
        host/USRVHOS
```

2. Use ktpass to generate a keytab file

Keytab file was generated via command

`ktpass -princ HTTP/webapp5.sso.local@SSO.LOCAL -pass 12345678 -mapuser SSO\usrvhost3$ -pType KRB5_NT_PRINCIPAL -out C:\usrvhost3.HTTP.keytab -crypto AES256-SHA1`

Command output 

```
Targeting domain controller: WIN-1D8TH59FA3K.sso.local
Using legacy password setting method
Successfully mapped HTTP/webapp5.sso.local to USRVHOST3$.
WARNING: Account USRVHOST3$ is not a user account (uacflags=0x11001).
WARNING: Resetting USRVHOST3$'s password may cause authentication problems if USRVHOST3$ is being used as a server.

Reset USRVHOST3$'s password [y/n]?  y
WARNING: pType and account type do not match. This might cause problems.
Key created.
Output keytab to C:\usrvhost3.HTTP.keytab:
Keytab version: 0x502
keysize 83 HTTP/webapp5.sso.local@SSO.LOCAL ptype 1 (KRB5_NT_PRINCIPAL) vno 3 etype 0x12 (AES256-SHA1) keylength 32 (0x0a3eb2103c17a6b430492b2186a0de2c0386ed1d8f4d39eb3871adb108d12105
```

3. Copy the keytab file to the Linux or macOS machine.
Since Microsoft docs do not specify exact copy path I've placed keytab file directly in `/tmp` 

4. Select the keytab file via an environment variable
`export KRB5_KTNAME=/tmp/usrvhost3.HTTP.keytab`
5. Invoke `klist `to show the SPNs currently available for use.
`klist `output:
`klist: No credentials cache found (filename: /tmp/krb5cc_1000)`

`realm list` output inside `usrvhost3`

```
sso.local
  type: kerberos
  realm-name: SSO.LOCAL
  domain-name: sso.local
  configured: kerberos-member
  server-software: active-directory
  client-software: sssd
  required-package: sssd-tools
  required-package: sssd
  required-package: libnss-sss
  required-package: libpam-sss
  required-package: adcli
  required-package: samba-common-bin
  login-formats: %U@sso.local
  login-policy: allow-realm-logins
```

**Comment by Tratcher** [comment]
Your klist output is suspect. Did you try kinit?
https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#test-the-ticket-granting-ticket-retrieval

**Comment by amd-9** [comment]
> Your klist output is suspect. Did you try kinit?
> https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#test-the-ticket-granting-ticket-retrieval

Yes. I've tried with

`sudo kinit -V HTTP/webapp5.sso.local@SSO.LOCAL -k -t /tmp/usrvhost3.HTTP.keytab`

Result was

```
Using default cache: /tmp/krb5cc_0
Using principal: HTTP/webapp5.sso.local@SSO.LOCAL
Using keytab: /home/developer-u3/Src/usrvhost3.HTTP.keytab
Authenticated to Kerberos v5
```

klist output was
`klist: No credentials cache found (filename: /tmp/krb5cc_1000)`

and after that with` kinit -V Администратор@SSO.LOCAL`

Result was

```
Using default cache: /tmp/krb5cc_1000
Using principal: Администратор@SSO.LOCAL
Password for Администратор@SSO.LOCAL: 
Authenticated to Kerberos v5
```

klist output was

```
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: Администратор@SSO.LOCAL

Valid starting       Expires              Service principal
29.12.2020 20:16:19  30.12.2020 06:16:19  krbtgt/SSO.LOCAL@SSO.LOCAL
	renew until 30.12.2020 20:16:13
```

Error remains the same

**Comment by Tratcher** [comment]
@JunTaoLuo you've run this scenario more recently, do the above commands match your notes?

If klist doesn't work then I don't expect the rest of your scenario to work. Is kinit supposed to be using sudo? I have it without sudo in my notes. It seems like that would put you in a different context.

**Comment by amd-9** [comment]
> @amd-9 If klist doesn't work then I don't expect the rest of your scenario to work. Is kinit supposed to be using sudo? I have it without sudo in my notes. It seems like that would put you in a different context.

@Tratcher not quite sure about `sudo` with `kinit`. Moreover environment configuratuion [docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#linux-and-macos-environment-configuration) do not say anything about the need of executing `kinit` on host machine, just exporting `KRB5_KTNAME` . Executing `klist` after runnig `kinit`with or without `sudo` produces the same result.

**Comment by JunTaoLuo** [comment]
Running `kinit` and `klist` isn't really relevant here since it examines the global credentials whereas we select the keytab via the environment variable `KRB5_KTNAME` for the specific session we are testing. The error 

```
Request ticket server HTTP/webapp5.sso.local@SSO.LOCAL not found in keytab (ticket kvno 3)
```

does seem to suggest that there is something incorrect with the keytab though. A few things to note, `/tmp` directory may not be persisted so it's best to store the keytab file somewhere else. Also, I'm suspicious of the generated keytab which indicated that the user account is not found:

```
WARNING: Account USRVHOST3$ is not a user account (uacflags=0x11001).
```

**Comment by amd-9** [comment]
> Also, I'm suspicious of the generated keytab which indicated that the user account is not found:
> 
> ```
> WARNING: Account USRVHOST3$ is not a user account (uacflags=0x11001).
> ```

@JunTaoLuo Adding host machine to the domain by following steps from the [docs](https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller) only adds computer to the AD and no user is been added/created.

![image](https://user-images.githubusercontent.com/9817513/104154311-aaa58800-53f5-11eb-8f37-219e4d494ff2.png)

Is there anything else that I can check?

**Comment by JunTaoLuo** [comment]
I looked through my previous setup and compared it to what's was reported here and I can't spot any obvious issues. 

But to start from the basics, can we confirm that the network connections are set up correctly? i.e. host and client use the same DNS servers and can resolve the service names correctly? Also can you share the debug level server logs when you are running `dotnet run`?

**Comment by blowdart** [comment]
We feel, given that this is so complicated, it's out of scope for GitHub issues, and everyone would be better served if [a support ticket](https://support.microsoft.com/supportforbusiness/productselection/?sapid=4fd4947b-15ea-ce01-080f-97f2ca3c76e8) is opened so support can work with you in real time. If this turns out to be a product bug your support ticket cost is refunded.
