### ISSUE TITLE
<InputFile>and IBrowserFile.RequestImageFileAsync throws Unhandled Exception

### ISSUE THREAD

**Issue by Spottigus** [dotnet/aspnetcore#28783]
### Describe the bug
When building and running the repo https://github.com/Spottigus/BlazorInputFileDebug , I receive an exception after clicking <InputFile> button on index and selecting a .png file. 

This only reproduces on one of the two of my computers. On the computer that throws the exception, I have tried the following:

- Uninstall all .net core versions and deleted left over folders
- Clear all cache on browser
- In dev panel / application, clear site data

### Exceptions (if any)
GET blob:https://localhost:5001/a3c98a6f-d700-43ed-98d2-e8fb66d7298d net::ERR_FAILED 200 (OK)
Image (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
toImageFile @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.0.js:1
do_icall @ 00aba1c6:0x194e46
do_icall_wrapper @ 00aba1c6:0x79df6
interp_exec_method @ 00aba1c6:0x44ad0
interp_runtime_invoke @ 00aba1c6:0x12efed
mono_jit_runtime_invoke @ 00aba1c6:0x118e4d
do_runtime_invoke @ 00aba1c6:0x79d3f
mono_runtime_invoke_checked @ 00aba1c6:0xf65a
mono_runtime_try_invoke_array @ 00aba1c6:0x10e81f
ves_icall_InternalInvoke @ 00aba1c6:0xed48f
ves_icall_InternalInvoke_raw @ 00aba1c6:0xecf54
do_icall @ 00aba1c6:0x194dd3
do_icall_wrapper @ 00aba1c6:0x79df6
interp_exec_method @ 00aba1c6:0x44ad0
interp_runtime_invoke @ 00aba1c6:0x12efed
mono_jit_runtime_invoke @ 00aba1c6:0x118e4d
do_runtime_invoke @ 00aba1c6:0x79d3f
mono_runtime_invoke_checked @ 00aba1c6:0xf65a
mono_runtime_try_invoke_array @ 00aba1c6:0x10e81f
ves_icall_InternalInvoke @ 00aba1c6:0xed48f
ves_icall_InternalInvoke_raw @ 00aba1c6:0xecf54
do_icall @ 00aba1c6:0x194dd3
do_icall_wrapper @ 00aba1c6:0x79df6
interp_exec_method @ 00aba1c6:0x44ad0
interp_runtime_invoke @ 00aba1c6:0x12efed
mono_jit_runtime_invoke @ 00aba1c6:0x118e4d
do_runtime_invoke @ 00aba1c6:0x79d3f
mono_runtime_try_invoke @ 00aba1c6:0x1297f
mono_runtime_invoke @ 00aba1c6:0x10ec19
mono_wasm_invoke_method @ 00aba1c6:0x108e40
Module._mono_wasm_invoke_method @ dotnet.5.0.0.js:1
call_method @ dotnet.5.0.0.js:1
(anonymous) @ dotnet.5.0.0.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Show 17 more frames

### Further technical details
Edge Versions
----Not Working Env----
Version 87.0.664.66 (Official build) (64-bit)
----Working Env----
Version 87.0.664.66 (Official build) (64-bit)

Dotnet --Info
----Not Working Env----
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

----Working Env----
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
----Working Env----
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.513 [C:\Program Files\dotnet\sdk]
  2.1.519 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@Spottigus thanks for contacting us.

Could you provide the entire callstack (there seems to be missing frames) and if possible a minimal repro project that showcases the issue?

**Comment by Spottigus** [comment]
@javiercn 
Currently it only reproduces on one of my two computers.
The minimal repo can be found here. https://github.com/Spottigus/BlazorInputFileDebug

Here is the full exception:

GET blob:https://localhost:5001/44409b32-176a-4737-b7fc-cbaff055f607 net::ERR_FAILED 200 (OK)
Image (async)		
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
r	@	blazor.webassembly.js:1
toImageFile	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
beginInvokeJSFromDotNet	@	blazor.webassembly.js:1
w	@	blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor	@	dotnet.5.0.1.js:1
do_icall	@	00aba26a:0x194e58
do_icall_wrapper	@	00aba26a:0x79df9
interp_exec_method	@	00aba26a:0x44ad3
interp_runtime_invoke	@	00aba26a:0x12efff
mono_jit_runtime_invoke	@	00aba26a:0x118e5f
do_runtime_invoke	@	00aba26a:0x79d42
mono_runtime_invoke_checked	@	00aba26a:0xf65d
mono_runtime_try_invoke_array	@	00aba26a:0x10e831
ves_icall_InternalInvoke	@	00aba26a:0xed492
ves_icall_InternalInvoke_raw	@	00aba26a:0xecf57
do_icall	@	00aba26a:0x194de5
do_icall_wrapper	@	00aba26a:0x79df9
interp_exec_method	@	00aba26a:0x44ad3
interp_runtime_invoke	@	00aba26a:0x12efff
mono_jit_runtime_invoke	@	00aba26a:0x118e5f
do_runtime_invoke	@	00aba26a:0x79d42
mono_runtime_invoke_checked	@	00aba26a:0xf65d
mono_runtime_try_invoke_array	@	00aba26a:0x10e831
ves_icall_InternalInvoke	@	00aba26a:0xed492
ves_icall_InternalInvoke_raw	@	00aba26a:0xecf57
do_icall	@	00aba26a:0x194de5
do_icall_wrapper	@	00aba26a:0x79df9
interp_exec_method	@	00aba26a:0x44ad3
interp_runtime_invoke	@	00aba26a:0x12efff
mono_jit_runtime_invoke	@	00aba26a:0x118e5f
do_runtime_invoke	@	00aba26a:0x79d42
mono_runtime_try_invoke	@	00aba26a:0x12982
mono_runtime_invoke	@	00aba26a:0x10ec2b
mono_wasm_invoke_method	@	00aba26a:0x108e48
Module._mono_wasm_invoke_method	@	dotnet.5.0.1.js:1
call_method	@	dotnet.5.0.1.js:1
(anonymous)	@	dotnet.5.0.1.js:1
beginInvokeDotNetFromJS	@	blazor.webassembly.js:1
h	@	blazor.webassembly.js:1
e.invokeMethodAsync	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1

**Comment by SteveSandersonMS** [comment]
I'm afraid I haven't been able to reproduce any problem here. Using the code you supplied, it works fine as far as I can tell.

You mention it only fails on one of your computers but not on others. This is very unusual for client-side code in a web browser, since web browsers are extremely standard and don't depend on other things installed on your computer (e.g., .NET Core SDK version).

Is it possible there's something special and unusual about the .png you're selecting? Is it possibly corrupted in some way, or perhaps does your OS deny access to the file?

**Comment by Spottigus** [comment]
This happens on both .jpg and .png. I did notice a line before the exception that I missed on the original investigation as it only happens once.  

![image](https://user-images.githubusercontent.com/71304298/105446251-5db48380-5c37-11eb-9dca-a52bcd8c02f0.png)

**Comment by SteveSandersonMS** [comment]
Sorry, there isn't really anything I can do to investigate further, since this works in every case I'm aware of, and you've seen this is specific to just one of your computers (suggesting there's some issue in that particular browser installation).

If you find a way of reproducing this on another machine (e.g., because you find that it's triggered by some 3rd-party browser extension or similar), please let us know.
