### ISSUE TITLE
Add support for well-known change password URL in Identity

### ISSUE THREAD

**Issue by mguinness** [dotnet/aspnetcore#28789]
### Is your feature request related to a problem? Please describe.
Currently browser requests for `/.well-known/change-password` result in 404 not found.  [A Well-Known URL for Changing Passwords](https://w3c.github.io/webappsec-change-password-url/#change-password-url) details how a 302 redirect can instead be returned.

### Describe the solution you'd like
[Add a redirect to change password page](https://web.dev/change-password-url/#set-up-%22a-well-known-url-for-changing-passwords%22) in Identity templates to help password managers find the URL for the change password page.

**Comment by blowdart** [comment]
@mkArtakMSFT This probably isn't just identity. There's a need for a /.well-known/ middleware generally, into which other middlewares, such as identity, or identity server/open iddict, acme certificate renewal and so on would then say "Hey we can provide our little piece for it".

As such it's probably a wider framework feature, which identity et al could then make use of.  So I'm retagging to middleware, and marking as a feature (I hope that's the "Here's a new feature tag")

**Comment by mguinness** [comment]
Closing as this is a duplicate of https://github.com/dotnet/aspnetcore/issues/25556.
