### ISSUE TITLE
Provide an AddStaticFiles extension method on IServiceCollection

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#2879]
This method will configure the default configuration options for static files and allow libraries avoid having to replicate the logic to set the default options. See https://github.com/aspnet/Identity/blob/dev/src/UI/IdentityDefaultUIConfigureOptions.cs#L52-L62

To be very clear, this is not about requiring a method call to services.AddStaticFiles() to use StaticFiles but to allow other libraries to call it in order to ensure that the options were initialized correctly.

**Comment by Tratcher** [comment]
And by initialized correctly you mean moving up / duplicating the lazy initialization that would otherwise take place in the middleware constructor?
https://github.com/aspnet/StaticFiles/blob/8b7b1b67321ddc0d5cbcedb9aa1c8daf2c8d2d8b/src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs#L59-L60

What about default files, directory browser, etc?

**Comment by javiercn** [comment]
> What about default files, directory browser, etc?

Correct me if I'm wrong, but aren't those things initialized properly when you just call app.UseStaticFiles()?

I want a convenience method that does the needful and that libraries can rely on, so that the responsibility of initializing anything static files related is  kept within the StaticFiles libraries.
The middleware can still initialize itself calling an internal version of the configure options method that that method call would add, but other libraries can just call services.AddStaticFiles and rely on the fact that at least there is a default configuration when they add things on top.

**Comment by Tratcher** [comment]
Those are independent middleware with independent options. They share some initialization logic, but not state. Only FileServer configures all of them.

**Comment by muratg** [comment]
@javiercn Is this something you need or is it a "good to have"? Backlogging, but if you need for something specific, we can talk about bringing it back.

**Comment by javiercn** [comment]
Customers (and me) should not need to do
https://github.com/aspnet/Identity/blob/884a1b7dfcd82a2050ab027dc88f2e2750cd2c35/src/UI/IdentityDefaultUIConfigureOptions.cs#L52-L62 in a library to initialize static files before adding their own file providers. Is not obvious code to write and its easy to introduce bugs (in fact I already had one).

I'm not suggesting making this method mandatory, but just having it available so that libraries (like identity UI) can call it to correctly initialize the provider so that they can add things on top of the default configuration.

It's literally an extension method + an IConfigureOptions<T> implementation that sets-up the default provider.
