### ISSUE TITLE
[Razor Source Generator] File names containing the hash symbol do not correctly flow metadata

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#28794]
This trips the MvcWithComponents test which includes a file containing hash: ihttps://github.com/dotnet/aspnetcore/blob/master/src/Razor/test/testassets/MvcWithComponents/Views/Home/%23FileName.cshtml

The bug is likely in source generators but we need a minimal app that reproduces the problem. In the meanwhile, skipping this particular scenario since it's fairly low value.

**Comment by pranavkm** [comment]
@captainsafia could I drop this in your plate to figure out for p4?

**Comment by captainsafia** [comment]
Boo -- still repros.

https://github.com/captainsafia/TestWithHashFilename

**Comment by pranavkm** [comment]
Could you file a compiler issue? My guess is it has something to do with the way AnalyzerOptions are passed around.

**Comment by captainsafia** [comment]
Yep -- I wanna debug this a little bit further before opening the issue though.

I noticed that there's a behavioral difference between when I first encountered this issue and now. Previously, it used to throw an exception. Now, it fails silently. I wanna figure out if that's because of a code change we made (and perhaps this is our bug) or if this is indeed external to the compiler.

**Comment by captainsafia** [comment]
https://github.com/dotnet/roslyn/issues/52469

Trying to see if I can workaround this in the RSG.

**Comment by JiahongJin1** [comment]
@captainsafia below warning occurrs when building project  with net 6 preview  4 SDK if project's name contains special characters e.g "#".  Is it expected currently, right?
Repro steps:
dotnet new mvc -o mymvc#
Dotnet build

![image](https://user-images.githubusercontent.com/46206739/116065538-b32a8180-a6b9-11eb-8c08-a33f53da5bc9.png)

**Comment by JiahongJin1** [comment]
@captainsafia 
Checked on the latest coherent build-6.0.100-preview.4.21225.7(runtime-6.0.0-preview.4.21222.10), errors occur when run project if project's name contains special characters e.g "#"
![image](https://user-images.githubusercontent.com/46206739/116383164-2f9f9a80-a849-11eb-98a1-b984982f9ed1.png)

**Comment by captainsafia** [comment]
@JiahongJin1 Thanks for sharing your scenario. It's under investigation. I'll share any updates on this thread.
