### ISSUE TITLE
publish profile cannot run on centos 

### ISSUE THREAD

**Issue by tinker-jim** [dotnet/aspnetcore#28795]
I dont know what's the trouble on my pc. Every publish profile cannot run on the centos 7 server.When i start the app even if the "hello world",throw the  Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'xxx.dll'. The module was expected to contain an assembly manifest.What should i do?Any advice.Thanks!
![myPc](https://user-images.githubusercontent.com/76039767/102848560-0d87ad00-4450-11eb-8a00-30d41842537c.png)
![server](https://user-images.githubusercontent.com/76039767/102848572-124c6100-4450-11eb-8dfa-1e0cd72af815.png)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by tinker-jim** [comment]
> Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

Thank you bro, i find the trouble.It might be the linux-server enviroment something has wrong.I create a vm and install the same linux sys on my vm.The publish app can work well .

**Comment by tinker-jim** [comment]
But i have a new question now,My local linux-server and the online linux-server install the same linux sys 'CentOS Linux release 7.6.1810 (Core) ' and the same .netcore sdk 3.1.404.There are three members in my team.My tl's  publish profile always can work on the online linux-server,but me and the another one can't.It's really really really weird.I need to troubleshoot the wrong direction a bit,any advice!Thanks！

**Comment by tinker-jim** [comment]
Maybe the installation of other software caused the conflict.I reload my pc system today,i'll test which the software may casue this.I hope not the java envrionment.
