### ISSUE TITLE
Blazor Selected Item not remain Persistance when we scroll down or up in the List

### ISSUE THREAD

**Issue by gopalawasthi123** [dotnet/aspnetcore#28816]
### Describe the bug
We select an item in the list and highlight it through  **js**. When we scroll down or up the list the Elements in the DOM gets replaced with the new elements. So the new Item which replace the old item in DOM of previous poisition gets highlighted.

### To Reproduce
Just Render the list through Virtualize Component and highlight the particular Item on click. On Scrolling issue will be reproduced
### Further technical details
Dot Net 5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Do you happen to use the `@key` directive for the elements being rendered in the list?
Give it a try please and let us know whether that will fix this. You can see an example usage in https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#virtualization:

[Screenshot below]
![image](https://user-images.githubusercontent.com/34246760/103018156-9e669300-44f9-11eb-8858-320743b82c59.png)
