### ISSUE TITLE
[Razor Source Generator] Figure out IDE integration for razor files

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#28825]
* [ ] Caching and build incrementalism inside source generator
* [ ] Design time build
* [ ] Edit and continue

**Comment by mkArtakMSFT** [comment]
Waiting for the IDE team to provide underlying support for this.

**Comment by pranavkm** [comment]
Closing this. We mostly understand what the issues are here (e.g. source line mappings) and have issues tracking them.
