### ISSUE TITLE
Form files are loaded while HTTP GET with route parameter

### ISSUE THREAD

**Issue by msciborski** [dotnet/aspnetcore#28822]
### Describe the bug
When the HTTP GET is processed, form files are loaded. It only occurs when there is model binding behind. 

### To Reproduce

So when endpoint use any sort of model binding then form which is sent with request is read. 
I've prepared sample repo which has two endpoints:
- one with route parameter,
- one without route parameter, 

I've changed the FormOptions to allow upload large files. 

Request from postman:
![Postman request](https://user-images.githubusercontent.com/22726160/102988826-d8915e00-4514-11eb-92c5-fc0256e2f5f0.png)

Difference in memory usage:
- Endpoint without route parameter:
![Endpoint without route parameter](https://user-images.githubusercontent.com/22726160/102989132-666d4900-4515-11eb-8acd-ffc791ab068f.png)
- Endpoint with route parameter:
![Endpoint with route parameter](https://user-images.githubusercontent.com/22726160/102989248-93b9f700-4515-11eb-9373-60ac37e02b52.png)

I think, that it is a bug, but maybe it works like that by design. 

Sample repo url: https://github.com/apoqlar/TestStrangeGetWithFiles

### Further technical details
- ASP.NET Core version 3.1.6
- Include the output of `dotnet --info`
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.10' was not found.
  - The following frameworks were found:
      3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.10&arch=x64&rid=win10-x64

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version Microsoft Visual Studio Enterprise 2019
Version 16.8.3

**Comment by pranavkm** [comment]
Thanks for the report. Kestrel supports reading the request body if it specifies a Content-Length or is chunked regardless of the HTTP method being used. Model binding in MVC will read a multipart form body since it is a source for values for parameters. Your action with a route parameter has to be model bound and consequently, the form body is read. 

Do you have a specific concern apart from the behavior being surprising?

**Comment by msciborski** [comment]
@pranavkm Hi, sorry for delay. I think, that loading body/form on HTTP GET by default is a problem. In my opinion, it should be optional.

I mean:
`services.AddMvc(c => c.AllowLoadBodyOnGet = true)`

**Comment by pranavkm** [comment]
@msciborski this would have to be a server feature, not MVC specific. That said, it's unlikely we'd add an option for a very narrow scenario when you could author a middleware that handles this. @Tratcher could you use the `IHttpRequestBodyDetectionFeature` to detect this?

**Comment by Tratcher** [comment]
IHttpRequestBodyDetectionFeature would be used to detect if the server is expecting a body. To actually suppress it you'd need to replace the request body Stream/Pipe with an empty one.

**Comment by msciborski** [comment]
@pranavkm @Tratcher I've dealt with it using filter which removes FormValueProviderFactory, FormFileValueProviderFactory, JQueryFormValueProviderFactory from http context ValueProviderFactories on HTTP GET. 

```
    public class DisableFormModelBindingOnGetFilter : IResourceFilter
    {
        public void OnResourceExecuted(ResourceExecutedContext context)
        {
        }

        public void OnResourceExecuting(ResourceExecutingContext context)
        {
            if (context.HttpContext.Request.Method.Equals("get", StringComparison.InvariantCultureIgnoreCase))
            {
                IList<IValueProviderFactory> providerFactories = context.ValueProviderFactories;
                providerFactories.RemoveType<FormValueProviderFactory>();
                providerFactories.RemoveType<FormFileValueProviderFactory>();
                providerFactories.RemoveType<JQueryFormValueProviderFactory>();
            }
        }
    }
```

**Comment by pranavkm** [comment]
That would be one way to solve this, although it does not prevent any other middleware that executes before MVC from reading the body.
