### ISSUE TITLE
Allow Varible Parameter For Blazor @page Directive

### ISSUE THREAD

**Issue by cdomino** [dotnet/aspnetcore#28827]
### Is your feature request related to a problem? Please describe.
Currently in Blazor (I'm using the lovely new .NET 5 version) the @page directive requires a hard-coded string to set the route. I am personally nutty about using constants for all my non-dynamic strings; it would be great to be able to pass a variable to this directive to avoid problematic routing issues caused by hard coding.

### Describe the solution you'd like
Here's how I set up my web apps. The last line is my proposal for how to dynamically wire a page into Blazor routing...
```
(App.Common.csproj)
public class Constants
{
    public class Routing
    {
         public const string SomePage = "some-page";
         public const string SomeRoute = "some-route";
    }
}

(App.Blazor.Server.csproj)
public class SomeController
{
    [HttpGet(App.Common.Constants.Routing.SomeRoute)]
    public async Task<IActionResult> SomeActionAsync()
    {
        this.ViewBag.WelcomeLinkHtml = "Thanks for signing up! Click <a title='Welcome' href='https://app.com/@App.Common.Constants.Routing.SomePage'>here</a> to start using the app.";
        return this.View();
    }
}

(App.Blazor.Client.csproj)
@page App.Common.Constants.Routing.SomePage;
```

### Additional context
Thanks! Loving Blazor!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@ajaybhargavb is there anything which prevents us from doing this?

**Comment by pranavkm** [comment]
This is a dup of https://github.com/dotnet/aspnetcore/issues/23195 which was closed due to inactivity. It does provide a workaround though

> you can achieve this by using `@attribute [Route(Constants.PageRoute)]` instead of `@page` and everything else should be the same.

**Comment by cdomino** [comment]
Thanks @pranavkm! I can confirm this is a variable workaround. Furthermore, I actually like this approach better than using the page directive; it feels more intuitive since these are _really_ more like routable Blazor components than physical "pages" from the app's perspective. My $0.02 is that it should be mentioned in [the docs](https://docs.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/pages-routing-layouts); I'll post a comment there and close this issue.

Much appreciated, and Happy New Year!
