### ISSUE TITLE
[Producton Issue] Blazor Server JS interop fails to read 60k of characters from session storage

### ISSUE THREAD

**Issue by frank-liu-toronto** [dotnet/aspnetcore#28832]
### Describe the bug
Blazor Server JS interop fails to read 60k of characters from session storage. But session storage supports up to 5MB of data, 60K  chars is too limited! (Blazor WebAssembly does work). **This is a production issue, please help!**

### To Reproduce
- Create a Blazor Server side app with .net core 3.1 or .net 5.
- Modify the index.razor page component to be like this:
```
@page "/"

@inject IJSRuntime JSRuntime

Welcome to your new app.


<button @onclick="Test">Test</button>

@code {
    private string value = "{a string that has more than 60k character}";

    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);

        if (firstRender)
            JSRuntime.InvokeVoidAsync("sessionStorage.setItem", "value", value);
    }

    async void Test()
    {
        var value1 = await JSRuntime.InvokeAsync<string>("sessionStorage.getItem", "value");
    }
}

```
- Make sure the string in the value variable is longer than 60k characters.
- Run the app, click on the Test button.
- Observe that the signalR channel breaks and the value1 variable never gets the result back.

**Comment by pranavkm** [comment]
Perhaps your app is running in to SignalR size limits. https://github.com/dotnet/aspnetcore/issues/9570 talks about ways to increase these limits, could you try configuring these? Another alternative to model a `Stream` to support arbitrarily large sized values. https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor/BinarySubmit shows how this would work.

**Comment by frank-liu-toronto** [comment]
Hi @pranavkm, that fixed my issue, thank you very much!


```
services.AddServerSideBlazor()                   
  .AddHubOptions(options =>
  {
      options.MaximumReceiveMessageSize = 2500000;                        
  });
```
