### ISSUE TITLE
Publishing blazor WASM .NET 5 on IIS throws not found errors with all libraries

### ISSUE THREAD

**Issue by AmirImam** [dotnet/aspnetcore#28839]
Hi
I have a .NET 5 blazor wasm project, it works on local perf, but when I try to publish it on IIS it throws a lot of 404 errors for all dll libraries as attached image
![image](https://user-images.githubusercontent.com/26382843/103064927-49dd1980-45c6-11eb-8f08-83df4ba118d6.png)

and **Error loading ICU asset** too
__________________________________________
I tried to publish it again but it throws an errors
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: *********************

Publish settings
![image](https://user-images.githubusercontent.com/26382843/103065546-e0f6a100-45c7-11eb-950a-82239eee0c3e.png)

- I found issue here in github about  **loading ICU asset** error, but nothing helpful  

Update:
Now I created a new project, and copied all files from old one into it, then I published it. It throws these errors
![image](https://user-images.githubusercontent.com/26382843/103067101-4dbf6a80-45cb-11eb-9374-9b8712b6ed71.png)

**Comment by pranavkm** [comment]
Have you looked at the instructions for self-contained deployment to IIS documented here: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#standalone-deployment?

**Comment by AmirImam** [comment]
> Have you looked at the instructions for self-contained deployment to IIS documented here: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#standalone-deployment?

The string thing is it worked now. I don't know how, but what I did is creating a new project and copying the files one by one into it and it worked. This so weird, because I did that before but didn't work. I think there is a problem here must be followed

**Comment by pranavkm** [comment]
Are you able to share a minimal app that reproduces the original issue?
