### ISSUE TITLE
Blazor static site generator

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#28849]
### Is your feature request related to a problem? Please describe.
Currently there is no option available for .NET developers to generate a pure static site.

These options exist in the JS / Node ecosystem through frameworks like:
* Gatsby for React ( https://www.gatsbyjs.com/docs/glossary/static-site-generator/ )
* Nuxt.js for Vue ( https://nuxtjs.org/docs/2.x/concepts/static-site-generation/ )  

### Describe the solution you'd like
Maybe something like dotnet publish static-site

### Additional context
This feature would allow you to generate a static site with no dependency on the dotnet runtime and does not require AOT, tree shaking / trimming dll's etc. 

This would result in extremely fast load times and will be in the same performance ball park as the other JS / Node generated sites. 

In this scenario the .NET framework is more of a tool that dev's use to build sites rather than .NET being the thing that actually executes the site similar to how the above mentioned frameworks work.

**Comment by SIkebe** [comment]
>Currently there is no option available for .NET developers to generate a pure static site.

Have you tried Statiq?
https://github.com/statiqdev

**Comment by MacdonaldRobinson** [comment]
Hi @SIkebe,

This looks great! Thanks for sharing!

Would be nice if you can write your whole site in Blazor and just have it generate the static site during the publish stage, similar to how you can write your whole site in React or Vue and just have it generate static sites during the publish stage using Gatsby or Nuxt.

**Comment by SIkebe** [comment]
@MacdonaldRobinson Yeah, I agree with you, however I saw this kind of request several times...

https://github.com/dotnet/aspnetcore/issues/26929#issuecomment-709467440
>Thanks for contacting us. This is something which came up few times. While this is a good idea, this is not something we would like to make part of the framework at the moment. You can see how similar conversations evolved in the past by reading through #5658 and #14581.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @MacdonaldRobinson.
Our position still hasn't changed on this. As @SIkebe has noted, this is not something we plan to do.
