### ISSUE TITLE
Upgrading Blazor WASM to .Net 5.0 

### ISSUE THREAD

**Issue by carlblanchard** [dotnet/aspnetcore#28840]
I can't seem to get my solution to upgrade to .net 5.0, what's going on here. 

I've set the project SDK to ```<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">```
The framework to ```<TargetFramework>net5.0</TargetFramework>```
Updated every NuGet package to all the latest pre-release versions 
Updated my <app> to ```<div id="app"> ```

All I get is this message 
NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.		C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets

and every NuGet package has a yellow icon. 

![image](https://user-images.githubusercontent.com/18427214/103068684-8fddb180-45b5-11eb-94d7-f22874c10044.png)

**Comment by pranavkm** [comment]
Several things appear to be wrong with your project file:

* Your app references the WebAssembly.Build package which is to be removed as per our migration guide: https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-blazor-webassembly-projects.
* It references unsupported versions of server components such as `Microsoft.AspNetCore.Cors` and `Microsoft.Extensions.Http` which cannot be referenced in Blazor WebAssembly. Referencing these produce the framework error you're seeing.
* Microsoft.AspNetCore.Blazor.HttpClient was deprecated in a 3.2 preview and should no longer be used. System.Net.Http.Json would be a replacement. 
* Your app's also inexplicably referencing NUnit. 

I would consider starting from a brand new 5.0 project template and using that as a template to migrate.
