### ISSUE TITLE
Asp.Net Core Blazor SignalR not working as expected in IIS

### ISSUE THREAD

**Issue by equirev73** [dotnet/aspnetcore#28845]
(Visual Studio 2019. Blazor WebAssembly with .NET 5.0. NuGget packages updated. WebSocket enabled)
Hi
I have a .NET 5 blazor wasm project, it works on local perf, but when I publish it on IIS not working as expected.

[https://github.com/equirev73/Languages](https://github.com/equirev73/Languages)

After a few minutes it waits for some time and then it no longer navigates.
In Chrome + F12 I see requests "wss" such as IIS Express. But now its status is pending.
![Prim](https://user-images.githubusercontent.com/58412457/103099847-d7346400-45ee-11eb-9476-1cd4890a7dc6.gif)

**LanguagesList.razor (only code)**

```
@code {
      List<ProgramingLanguages> languages;
      private HubConnection hubConnection;

      protected override async Task OnInitializedAsync()
      {
          hubConnection = new HubConnectionBuilder()
              .WithUrl(NavigationManager.ToAbsoluteUri("/languageshub"))
            .Build();

          hubConnection.On("ReceiveMessage", () =>
          {
            CallAllLanguages();
            StateHasChanged();
          });

          await hubConnection.StartAsync();
          await GetAllLanguages();
      }

      private void CallAllLanguages()
      {
          Task.Run(async () => await GetAllLanguages());
      }

      protected async Task GetAllLanguages()
      {
          languages = await   HttpClient.GetFromJsonAsync<List<ProgramingLanguages>>("api/ProgramingLanguages");
          StateHasChanged();
      }

      public void Dispose()
      {
          _ = hubConnection.DisposeAsync();
      }
}
```

Thanks in advance

**Comment by Ariansh** [comment]
from what I see here, you call GetAllLanguages() method twice, why? you change the state twice, why?
I suggest you to remove these two calls  await StateHasChanged(); and await GetAllLanguages(); inside OnInitialize method as they are not necessary and I strongly suggest you to avoid calling an api while you can receive data on a web socket event. honestly I dont know why you do it as far as they are both inside your own server. but for this case consider looking at memory window as well to see if you face a memory leak or something like that as well and please update here too. I might learn something as well. :D

**Comment by BrennanConroy** [comment]
Can you share client and server logs? Also, a network trace if possible. https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-5.0 and https://docs.microsoft.com/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-5.0&pivots=webassembly#signalr-net-client-logging

PS: 3.2 will be out of support soon. We recommend updating to 5.0

**Comment by equirev73** [comment]
Thanks for your suggestion @Ariansh. I found some errors in the Windows Log. I have been trying to solve it without success. I wanted to find out what it is about. I think it is the SSL.
The SSL was created with makecert. I still need to do more research with the tools suggested by @ BrennanConroy. Thank you !!!

Left side: Client || Right side: Win8.1 x86 with IIS >>)
![Server_Cliente](https://user-images.githubusercontent.com/58412457/103246967-fbbc7300-4943-11eb-822d-3fb1f9f96621.gif)
I don't understand how I didn't check the Log before. My mistake.-

**Comment by equirev73** [comment]
> from what I see here, you call GetAllLanguages() method twice, why? you change the state twice, why?
> I suggest you to remove these two calls await StateHasChanged(); and await GetAllLanguages(); inside OnInitialize method as they are not necessary and I strongly suggest you to avoid calling an api while you can receive data on a web socket event. honestly I dont know why you do it as far as they are both inside your own server. but for this case consider looking at memory window as well to see if you face a memory leak or something like that as well and please update here too. I might learn something as well. :D

Thanks for your suggestion @Ariansh. I found some errors in the Windows Log. I have been trying to solve it without success. I wanted to find out what it is about. I think it is the SSL.
The SSL was created with makecert. I still need to do more research with the tools suggested by @BrennanConroy. Thank you !!!

Left side: Client || Right side: Win8.1 x86 with IIS >>)
![Server_Cliente](https://user-images.githubusercontent.com/58412457/103246967-fbbc7300-4943-11eb-822d-3fb1f9f96621.gif)
I don't understand how I didn't check the Log before. My mistake.-

**Comment by equirev73** [comment]
"The endpoint communication in SQL Server doesn't support TLS protocol version 1.2."

[https://support.microsoft.com/en-us/help/3135852/kb3135852-fix-the-encrypted-endpoint-communication-with-tls-1-2-fails](https://support.microsoft.com/en-us/help/3135852/kb3135852-fix-the-encrypted-endpoint-communication-with-tls-1-2-fails)

I am using SQL SERVER Express 2012 SP4. I will try on SQL Server 2016.

**Comment by equirev73** [comment]
Hi. I enabled HTTPS by following the tutorial.
https://medium.com/@tbusser/creating-a-browser-trusted-self-signed-ssl-certificate-2709ce43fd15

Firefox and Chrome it gives problems. I'll see how to fix it later.
![Server_SSL2](https://user-images.githubusercontent.com/58412457/103392264-c65a8580-4afb-11eb-8e4e-f65ccdfeef34.gif)

I used EDGE. I thought it was SSL but now I don't know what it can be.
![Server_SSL](https://user-images.githubusercontent.com/58412457/103391958-6adbc800-4afa-11eb-97bd-79b117271603.gif)

Thanks @BrennanConroy.

**Comment by Ariansh** [comment]
I cant read those errors as I dont know the language. but could you share your code again (I assume it is changed by the time you posted here), or share it on a public repo so we can work it together?

**Comment by equirev73** [comment]
Hi @Ariansh. Give me an hour. I'll finish some tests and answer. Thank you!

**Comment by equirev73** [comment]
Sorry @Ariansh. Still not working.
Code was changed due to testing. Then I thought it was an SSL problem due to TLS bugs. I installed a self-signed SSL certificate. Then i undo changes the repository and commented the result. As you suggested to me, I removed "StateHasChanged();".

    protected override async Task OnInitializedAsync()
    {
        hubConnection = new HubConnectionBuilder()
            .WithUrl(NavigationManager.ToAbsoluteUri("/languageshub"))
            .Build();

        hubConnection.On("ReceiveMessage", () =>
        {
            CallAllLanguages();
            //StateHasChanged();
        });

        await hubConnection.StartAsync();
        await GetAllLanguages();
    }

current code:
https://github.com/equirev73/Languages

The code is not mine. I found it on YT. And I tried to keep it original. In development it works fine. I looked for "blazor crud realtime" but it seems this is the only way. Only run "Pages\LanguagesList.razor"

I am currently using IIS on W8.1 32 bit. SQL SERVER 2012 SP4. Windows updated!
I will test it on a WS2012 R2 64 bit updated. Then I'll post the results.

**Comment by equirev73** [comment]
Finally I realized that if I use **Chrome**, the error occurs in **Development** as well.
After 30 times this happens:
![Development](https://user-images.githubusercontent.com/58412457/103449060-64c42380-4c81-11eb-916b-b9b418f94526.gif)

Test **Firefox** over 100 times and there was **NO ERROR**.
I tested it on two PCs. Development and IIS (WS2012 R2 IIS + WebSocket) via local network. 0 Error.

Current repo:
https://github.com/equirev73/Languages5

**Comment by equirev73** [comment]
Summary
----------
**Development**
3.1 updated 5.0

- Chrome		OK
- Firefox		OK

5.0

- Chrome		After 34th time: last image
- Firefox		OK

**IIS Win8.1 (32 bits)**
3.1 updated 5.0

- Chrome		After 9th time: (*)
- Firefox		After 9th time: (*)

5.0										

- Chrome		After 9th time: (*)
- Firefox		After 9th time: (*)

(*): It is waiting for the request. No error. The IIS no longer works. Also I tested "https://192.168.1.X/api/ProgramingLanguages". I have to Stop and start the IIS.

**IIS Win 2012 R2 (64 bits)**
3.1 updated 5.0

- Chrome		OK
- Firefox		OK

5.0

- Chrome		After 34th time: last image
- Firefox		OK

I going to write the project at 5.0 version again.

**Comment by equirev73** [comment]
Well. I rewrote the project in .NET 5.0 using VIsualStudio 2019 updated.
Development: Running from VisualStudio

- Chrome same error after entering the "lenguagelist" 34 times.
- Firefox the error does not appear.

Current repo: https://github.com/equirev73/Languages5

**Comment by Ariansh** [comment]
i've checked the code. it throws an exception at the server while reading data. im checking

**Comment by BrennanConroy** [comment]
@equirev73 The error you showed above about the "delegate target no longer available" is an issue with the WASM Runtime at https://github.com/dotnet/runtime. If you have a small consistent repro it might be a good idea to file an issue there for them to look at.

As far as getting rid of that error, you are missing `@implements IDisposable` from your LanguageList.razor page which means the SignalR client is never disposed and you have a bunch of background WebSocket clients running (which is part of the reason for the error you see).

Side-note: You can use `DisposeAsync` in 5.0 with `@implements IAsyncDisposable` and we have a tutorial for Blazor Wasm + SignalR at https://docs.microsoft.com/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio
