### ISSUE TITLE
ReactSpa Template: Update to CRA 4 & React 17, Typescript

### ISSUE THREAD

**Issue by joeblas** [dotnet/aspnetcore#28843]
Both SPA templates using React (React & React Redux) are quite outdated. A few items that would be within scope for a refactor:

- Update to CRA 4.x
- Update to React 17.x
- Convert class components to function components using the Hook API

Out of scope proposal:
- A new Typescript template
- We could use [this command](https://create-react-app.dev/docs/adding-typescript/#installation) to generate a new template using Typescript

These changes would greatly improve developer experience by providing an up-to-date experience while using React with .NET.

**Comment by sstream17** [comment]
Is there anything I can do related to this that will be valuable for the team? I recently converted a project of mine to use the Hooks API; I feel comfortable working with the React SPA template. Please let me know if I can be of any help.

**Comment by mkArtakMSFT** [comment]
The project template is now updated to React 17.
