### ISSUE TITLE
Typo (duplicate word) in documentation comment for SuppressAsyncSuffixInActionNames (MvcOptions)

### ISSUE THREAD

**Issue by kristofke** [dotnet/aspnetcore#28862]
I've come across a typo in an XML documentation comment.
It contains the word "using" twice. I might be mistaken, but I assume this is not correct.

See linked code:
https://github.com/dotnet/aspnetcore/blob/1902aa21bb842ee9e5bbcf8540811432afd3753b/src/Mvc/Mvc.Core/src/MvcOptions.cs#L284

I can imagine you'd like to consolidate a few typos in a single pull request instead of every typo separately?
If not, I can make a pull request to resolve this.

**Comment by pranavkm** [comment]
> If not, I can make a pull request to resolve this.

Go ahead, we'd be happy to accept it.
