### ISSUE TITLE
RedirectRule: opportunity for performance improvement

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/aspnetcore#28883]
## Summary

1. `RedirectRule.ApplyRule` is [comparing the request path with `PathString.Empty`](https://github.com/dotnet/aspnetcore/blob/eda62e7f028ae8e761bee43d5980a8d86d01c9ce/src/Middleware/Rewrite/src/RedirectRule.cs#L41), which ends up being a string comparison.
2. `RedirectRule.ApplyRule` is boxing a `PathString`([1](https://github.com/dotnet/aspnetcore/blob/eda62e7f028ae8e761bee43d5980a8d86d01c9ce/src/Middleware/Rewrite/src/RedirectRule.cs#L77))([2](https://github.com/dotnet/aspnetcore/blob/eda62e7f028ae8e761bee43d5980a8d86d01c9ce/src/Middleware/Rewrite/src/RedirectRule.cs#L81)).

## Motivation and goals

This is in a hot path for applications that use redirections.

# Detailed design

1. Use `path.HasValue` instead.
2. Use `pathBase.ToUriComponent()` instead.
   * A better option would be use `UriHelper.BuildRelative`. The current implementation doesn't encode the path; only the path base and the query string.

**Comment by Tratcher** [comment]
Have you done any profiling here? This is a class of issue that's unlikely to be addressed unless it shows up as significant in a CPU or memory profile. 

1. HasValue is a similar string comparison (string.IsNullOrEmpty).
https://github.com/dotnet/aspnetcore/blob/e04dee0b665fd7545b5d24b8b30ebad990af424a/src/Http/Http.Abstractions/src/PathString.cs#L47-L49

2. Are you sure about the boxing? PathString has an implicit string converter that may kick in first. It also overrides the `+` operator.
https://github.com/dotnet/aspnetcore/blob/e04dee0b665fd7545b5d24b8b30ebad990af424a/src/Http/Http.Abstractions/src/PathString.cs#L454-L455
https://github.com/dotnet/aspnetcore/blob/e04dee0b665fd7545b5d24b8b30ebad990af424a/src/Http/Http.Abstractions/src/PathString.cs#L414-L419

**Comment by paulomorgado** [comment]
If you follow the `PathString` equality operator, you'll see that it's more than just `string.IsNullOrEmpty`. And then there's consistency with the rest of the codebase.

You're right about the `string.Concat` overload being used. It's `string.Concat(string, string, string)` - there are overloads up to 4 string arguments and the C# compiler prefers the implicit conversion and the overload with `string` argumetns.

However, the `PathString` addition operator doesn't apply because the type of the next argument is a `sting`, not a `PathString`. It should be, because it's not being encoded like the rest of the components.

**Comment by Tratcher** [comment]
> However, the `PathString` addition operator doesn't apply because the type of the next argument is a `sting`, not a `PathString`. It should be, because it's not being encoded like the rest of the components.

It also has an overload for PathString + string.

**Comment by paulomorgado** [comment]
Got it!

But that means that

    pathBase + newPath.Substring(0, split) + query.ToUriComponent()

will end up being

    string.Concat(string.Concat(pathBase.ToUriComponent(), newPath.Substring(0, split)), query.ToUriComponent())

Right?

One more string than it needs to be. If we accept that `newPath.Substring(0, split)` is unavoidable.

**Comment by Tratcher** [comment]
Fair point. As you said, `UriHelper.BuildRelative` would address most of this.

**Comment by paulomorgado** [comment]
Are there any unit tests for this? If so, where?

**Comment by paulomorgado** [comment]
Found! MiddlewareTests.cs
