### ISSUE TITLE
Improvement to css isolation

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28882]
I would like the possibility of using css isolation for cases where you have some custom css in a library but you want to reuse in other projects and not just in components.  The only problem with the current css isolation is if you use custom css and pass the class to another component, does not work in most cases.  An example can be if there is a component that has css isolation and you specify a class and use a telerik component that has a property for class.  in that case, the telerik component will not show the custom css at all unless you use standard css which requires the reference.  I like how javascript isolation works where you specify in the class library and anybody that uses it does not have to do any extra setup.  There are many cases where somebody may create custom css classes in a razor class library and want to reuse without having to do extra setup but instead of isolated to just a component is making it more like standard css but a person does not have to reference like javascript isolation works.

**Comment by musictopia2** [comment]
I have some more information to add for the idea.  The good news is it can be possible currently to have a parent component with all the common css.  The bad news is if using from another project, then no intellisense.  What I would like to see is a way of having a parent component that hosts all the css styles you need for many projects then being able to use and still having the intellisense for the css classes.

**Comment by musictopia2** [comment]
That would work if it can have the intellisense.  Currently, even if you have the :deep if you use outside of the class library, then there is no intellisense.  Or maybe even have another tag which would allow the intellisense to work.  That way its possible to create a library of css that is intended to use in other projects without having to reference the css and have the intellisense for showing the list of css classes so a person does not have to remember which one it is.  Having to remember is especially bad if it comes in a library because they would either have to go to the open source project and if not open sourced, then would mostly be useless.

**Comment by mkArtakMSFT** [comment]
Thanks @musictopia2.
@vijayrkn this looks like a tooling ask for better support for CSS styles from referenced static assets. How do you want to track this?

**Comment by vijayrkn** [comment]
Adding @jodavis

**Comment by mkArtakMSFT** [comment]
Ping @jodavis

**Comment by sayedihashimi** [comment]
Thanks for the suggestions, we are aware that this is a gap currently. I'm going to start to define what support for CSS Isolation would look like. From there we will put the item onto or backlog, and prioritize it among the other work.
