### ISSUE TITLE
Wrong nullable annotations on ITicketStore.RetrieveAsync

### ISSUE THREAD

**Issue by mbashov** [dotnet/aspnetcore#28919]
The interface [ITicketStore](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/Security/Authentication/Cookies/src/ITicketStore.cs) should have `Task<AuthenticationTicket?>` return type for method `RetrieveAsync`. The service using this method [expects](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L157-L158) that it could return null. Also, the only sample implementation in this repository, [MemoryCache](https://github.com/dotnet/aspnetcore/blob/v5.0.1/src/Security/Authentication/Cookies/samples/CookieSessionSample/MemoryCacheTicketStore.cs#L42-L47), clearly can return null from its method.

**Comment by blowdart** [comment]
@pranavkm I believe you were Mr Nullable Annotations, and we agree this is wrong. 

@mbashov If you'd like to create a PR we'd accept it, otherwise Pranav are you still working through these?

**Comment by pranavkm** [comment]
Happy to accept a PR, but we would get this fixed in 6.0
