### ISSUE TITLE
Component layout

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/aspnetcore#28915]
a component base has deffinition like

```
<div>Parent component</div>
@ChildContent
<div>Footer Parent component</div>

@Code {

[Parameter] public RenderFragment ChildContent{get;set;}

}
```
a child component is

```
@layout ParentComponent

<div>child component layout</div>
```
as result, rendered html is only child elements and we see only

`child component layout`

I google it and find some result like [this ](https://stackoverflow.com/questions/59990832/basic-component-layout-inheritance-blazor) that has result like this

```
child component layout
Panret component
child component layout
Footer Parent component

```
this means child component rendered two times!

this structure is work on 'page' like charm!!! if I Add

`@page "/ChildComponent" `

to ChildComponent and navigate to it, it rendered correctly. and this problem is only when we use it as component of a page

In [microsoft document](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0) , not defined a limitation to use @layout directive only for Page and internal navigation system.

if @layout directive is limit to @page directive and internal navigation system of blazor, this is not a bug.
bug is that this is not docunmented.
but if we can use it on all components, Its not work for component that has not a @page directive and we are not going to use it by navigation system 

- dot net 5.0.1
- Visual studio 2019 v 16.8.3

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is indeed by design and the `@layout` directive is applicable to pages only.

@guardrex can you please add a note to [this docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0#specify-a-layout-in-a-component) page about this? Thanks!
