### ISSUE TITLE
@ref not set if inside a @if else

### ISSUE THREAD

**Issue by Keyan01** [dotnet/aspnetcore#28922]
I have a simple piece of code in that one part of the screen is not rendered until an item is selected. part that is not rendered is a table <(Mudtable>)I need to get a ref to it but it never gets set and I have seen an issue on stackoverflow that implies that it needs to be set outside the if. But I cannot see how I could do that, am I missing something with @ref? and how to use it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Keyan01.
It's not entirely clear what you're trying to achieve. Can you please elaborate more? Perhaps sharing a minimal repro app would also help.
