### ISSUE TITLE
Missing TypeCheck in generated razor class in case of CreateInferredEventCallback

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#28949]
Let's assume I want to bind a string to a component that provides a bindable parameter of type StringModel. I can implement implicit casts on StringModel from and to string. In a blazor component it would look like this:

```
<MyComponent bind-Model="this.MyStringValue"/>
```

for the forward conversion I can see that there's already a type check generated:

```
                __builder2.AddAttribute(38, "Model", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<AppGates.Net.Presentation.ViewModels.Basics.StringModel>(
#nullable restore
#line 24 "C:\git\appgates\unsorted\src\TomSun.Net.Blazor.Demo.Common\Views\Pages\BootstrapPage.razor"
                                 this.MyStringValue));
```

For the event handler creation the type check call is missing

```         
  __builder2.AddAttribute(39, "ModelChanged", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => this.MyStringValue = __value, this.MyStringValue));
```

which leads to a runtime cast exception because the inferred type of the event callback is string instead of StringModel.

My proposal is to generate the EventCallback using the Typecheck, too:

```
__builder2.AddAttribute(39, "ModelChanged", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => this.MyStringValue = __value, Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<AppGates.Net.Presentation.ViewModels.Basics.StringModel>(this.MyStringValue)));
```

I think that would fix the runtime exception and support using implicit casts for such scenarios.

**Comment by mkArtakMSFT** [comment]
@FreekSchoenmakersBuckaroo the issue you've linked was addressed already.
As for this one, I'm going to close it given the low number of engagements from the community on this one. Just trying to prioritize things and focus only on issues with higher impact.
