### ISSUE TITLE
Blazor insignificant whitespace trimming trims too much

### ISSUE THREAD

**Issue by ilh3** [dotnet/aspnetcore#28955]
#23568 has brought about whitespace trimming which is welcome but I think it trims too much in some situations. I understand there's the `@preservewhitespace true` directive but I feel like there should be an in between level of preservation, perhaps where multiple instances of whitespace together are reduced to a single whitespace.

E.g. If you have 2 elements such as the below on separate lines then these will be separated naturally by a whitespace.
```
<button>Button 1</button>
<button>Button 2</button>
```

If you insert an `@if` in between them but do not satisfy it then the whitespace is lost so the buttons now touch each other even though it effectively turns in to the same markup as the above.

```
<button>Button 1</button>
@if (false)
{
    ...
}
<button>Button 2</button>
```

**Comment by mrpmorris** [comment]
You can put a `&nbsp;` between them four an explicit space.

**Comment by ilh3** [comment]
Not an ideal solution. Aside from just being unnatural to have do _something_ when you don't in normal HTML, you then have to know when and where a space appears naturally and where you need to add a `&nbsp;` you could end up with double spacing if you happen to remove the `@if` without realising that another space would come in to play.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We do not plan to introduce more granular support for this. Instead, we recommend customers who face this issue to try and solve it using CSS and not rely on whitespaces.
