### ISSUE TITLE
Microsoft.Authentication.WebAssembly.Msal does not work with on-prem ADFS

### ISSUE THREAD

**Issue by gix** [dotnet/aspnetcore#28956]
Securing a Blazor WASM application with on-premises ADFS 2019 does not work. There are two issues that prevent it from working:

1. The bundled `msal-browser` (2.0.0) incorrectly requires `client_info` in the token response which ADFS does not send. The login callback fails and the login process stops midway through. This is fixed in later versions of `msal-browser`.
2. Logout fails to redirect back from ADFS to the logout callback because ADFS requires the `id_token_hint` parameter. The misleading error logged by ADFS is `The specified redirect URL did not match any of the OAuth client's redirect URIs. The logout was successful but the client will not be redirected.`

Locally I have upgraded to `msal-browser` 2.8.0. I have also modified `AuthenticationService.ts` to store the received `id_token` and send it as `id_token_hint` when logging out. With that I can successfully login and logout.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

We track updating the MSAL library as part of https://github.com/dotnet/aspnetcore/issues/29010
