### ISSUE TITLE
.NET 5: specifying ASPNETCORE_ENVIRONMENT in web.config doesn't have any effect.

### ISSUE THREAD

**Issue by RomanHubyak** [dotnet/aspnetcore#28958]
After upgrading from .NET Core 3 to .NET 5 ASPNETCORE_ENVIRONMENT is always Production, when the app is published to IIS. 

![image](https://user-images.githubusercontent.com/46841287/103414803-1ed76480-4b88-11eb-949c-9f0ea1ed02a3.png)

**Comment by RomanHubyak** [comment]
I am happy to provide any additional information, just let me know, what you need.

Also, there are broken links in the .NET 5 documentation (see screens below)

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0

![image](https://user-images.githubusercontent.com/46841287/103420889-328fc480-4ba2-11eb-9ee6-f704bdb64274.png)

It links to https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-5.0#setting-environment-variables

![image](https://user-images.githubusercontent.com/46841287/103420909-4c310c00-4ba2-11eb-9e4f-0dd72dd09976.png)

But there is no such section (Setting environment variables). It exists for .NET Core 3.1.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#set-environment-variables

![image](https://user-images.githubusercontent.com/46841287/103420973-a16d1d80-4ba2-11eb-8595-902f2d0e6d90.png)

Looks like there are some breaking changes or accidental mistake. Would be great to make it clear.

**Comment by guardrex** [comment]
@RomanHubyak ... The broken doc cross-link will be fixed shortly to address https://github.com/dotnet/AspNetCore.Docs/issues/21079.
