### ISSUE TITLE
Override Span and Memory Writes for HttpResponseStreamWriter 

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#2895]
For netcoreapp2.1

Also WriteLine and WriteLineAsync as the [default implementations on TextWriter](https://github.com/dotnet/corefx/blob/0fbb5f15e2c9b7ff51f5d194dbf06c406c14da9e/src/Common/src/CoreLib/System/IO/TextWriter.cs#L551-L580) are not great

**Comment by anurse** [comment]
Putting this on the backlog for now, 3.0 is pretty fully booked.

**Comment by antifree** [comment]
I decided not to create another one issue. 
Current implementation (default) of WriteLineAsync in Asp.Net Core 3.0 causes 
`InvalidOperationException when attempting to write to the response body – with a message “Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.”`. In my opinion it is caused, because default implementation in `TextWriter` creates new Task which calls `Write` method. This method is overriden in HttpResponseStreamWriter and calls `_stream.Write(..)`. I think it is a bug.

**Comment by anurse** [comment]
We should, in general, get all the async methods overridden so they don't unintentionally cause issues with the sync I/O blocking code.

See https://github.com/aspnet/AspNetCore/issues/16740.

Let's look at this in 5.0.0-preview1

**Comment by alefranz** [comment]
Hello, any chance you can provide more details on what you are looking for, so I can see if it is something I can try to contribute?

Thank you!

**Comment by benaadams** [comment]
[HttpResponseStreamWriter](https://github.com/dotnet/aspnetcore/blob/master/src/Http/WebUtilities/src/HttpResponseStreamWriter.cs) doesn't implement all the virtual methods of TextWriter

In particular
```csharp
public virtual void Write(ReadOnlySpan<char> buffer);
public virtual Task WriteAsync(ReadOnlyMemory<char> buffer, CancellationToken cancellationToken = default(CancellationToken));
public virtual void WriteLine(ReadOnlySpan<char> buffer);
public virtual Task WriteLineAsync(ReadOnlyMemory<char> buffer, CancellationToken cancellationToken = default(CancellationToken));
```

**Comment by alefranz** [comment]
Thanks Ben for the quick reply! I'll have a look.

**Comment by alefranz** [comment]
@benaadams I've started with the easy one and opened to make sure I'm not missing the point, see #18445
I'll then have a look at the async ones.

**Comment by benaadams** [comment]
Yep exactly the thing :)

**Comment by anurse** [comment]
Yep, @benaadams is correct. @alefranz, we'll take a quick look at your draft and see if you're on the right track ;).

**Comment by anurse** [comment]
Fixed in #18802!

**Comment by alefranz** [comment]
@anurse it's actually #18451, which has been merged, as this issue is about the `HttpResponseStreamWriter`.

Sorry if I made a bit of confusion with multiples linked PRs

**Comment by anurse** [comment]
No worries, my bad! Updated!
