### ISSUE TITLE
Your connection is not secure.Error code: NS_ERROR_NET_INADEQUATE_SECURITY

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/aspnetcore#28950]
i am facing the following error given below. containers are running correctly inside the docker in ubuntu, showing no error in logs. i have used both certificates localhost and domain-specific bust facing the same issue. Please help me to solve this issue. I am facing this issue after updating the Dotnet core from 2.2 to 3.1. 
`Your connection is not secure
The website tried to negotiate an inadequate level of security.
localhost uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.
Error code: NS_ERROR_NET_INADEQUATE_SECURITY`
![2020-12-31 10_00_51-TX-AI-000 - TeamViewer - Free license (non-commercial use only)](https://user-images.githubusercontent.com/23011613/103409672-b70d2380-4b5f-11eb-80f0-72990f5dc453.png)

**Comment by Tratcher** [comment]
3.0 enabled HTTP/2 by default, but HTTP/2 has higher security requirements. You can turn off HTTP/2 or reconfigure the OpenSsl TLS settings on your Ubuntu server.

See https://stackoverflow.com/questions/57934185/asp-net-core-3-0-security-issue-with-http2-on-chrome-and-firefox.
