### ISSUE TITLE
Blazor Wasm AAD B2C authentication issue

### ISSUE THREAD

**Issue by ismailhozza** [dotnet/aspnetcore#28969]
### Describe the bug
Hi, I am struggling with the below error. Can't figure out the root cause. I have a Blazor Wasm application with AAD B2C authentication. Login works fine, but after some time I get the below error. Any ideas what could be the problem?

![image](https://user-images.githubusercontent.com/1177602/103445934-6510ee80-4c82-11eb-895b-7e1ce8c6874c.png)

Based on the console logs, it seems that ID token is undefined.  

`ClientAuthError: null_or_empty_id_token: The idToken is null or empty. Please review the trace to determine the root cause. Raw ID Token Value: undefined`

### Further technical details
- Dotnet version: 5.0.100
- Project dependencies

`    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />

    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.1" PrivateAssets="all" />

    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.1" />

    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="5.0.0" />

    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Are you able to reliably reproduce this issue? If so, please share a small repro project so that we can investigate this.

**Comment by andersson09** [comment]
I get this error too, if I'm logged in and leave it for a while, then later refresh tab.

**Comment by juho-hanhimaki** [comment]
I ran into this too after the initial token has expired (60 minutes?).

Just followed the steps in the documentation:
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0

**Comment by juho-hanhimaki** [comment]
I did change the CacheLocation to localStorage (otherwise default template):

```
builder.Services.AddMsalAuthentication(options =>
{
options.ProviderOptions.Cache.CacheLocation = "localStorage";
```

Don't yet know if the change has something to do with the issue.

**Comment by andersson09** [comment]
Hi, I don't think this should be marked as stale, there is clearly an issue as multiple people are receiving the same exception.

**Comment by juho-hanhimaki** [comment]
I did manually build a updated version of AuthenticationService.js which included patch https://github.com/dotnet/aspnetcore/pull/28498 AND updated the msal-browser library to 2.8.0 (https://github.com/dotnet/aspnetcore/issues/29010). 

Now the issue is gone for me. Don't know which one of those two things fixed the issue, but the main thing for me is that the issue seems to be gone with those steps.

**Comment by morganc9** [comment]
Hello,
I have exactly the same error on my blazor project using B2C... +1

**Comment by ismailhozza** [comment]
Hi, I think this issue is resolved for me also. I did several changes, so I am not sure which one possibly fixed the issue. I updated the dependencies like @juho-hanhimaki and added couple of scopes (openid and offline_access) to the authentication config. So, I guess it can be closed for now.
