### ISSUE TITLE
Virtualize Component Bug

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28962]
I have a situation where even if i scroll all the way to the bottom, many items are missing.  Here is my repository.
https://github.com/musictopia2/VirtualizeComponentBug 

Also, i had times when trying to scroll, it will get really hosed.
The problem was even worse in this case.
_list = Enumerable.Range(1, 200000000).ToList();

In that case, not only does it load very slowly.
But also, if i scroll at all, then seems to get into a never ending loop.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is a known issue which we track as part of https://github.com/dotnet/aspnetcore/issues/29009
