### ISSUE TITLE
Roadmap ASP.NET Core 6 - Missing issues ?

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#28975]
Hello @pranavkm @mkArtakMSFT

I had a look to [ASP.NET Core 6 Roadmap](https://github.com/dotnet/aspnetcore/issues/27883). It looks great. 😄 

What about these two points ?

1. Finalize the Microsoft.AspNetCore.Components.DataAnnotations.Validation. This is still 3.2.0-rc1.20223.4. Should it be included by default ? Sorry to ask you the same question again. It was discussed here : [Package version for ObjectGraphDataAnnotationsValidator](https://github.com/dotnet/aspnetcore/issues/23289). I think it is really necessary.
2. What about the possibility to modify the document title and meta information ? [Influencing HTML Head from a Blazor component](https://github.com/dotnet/aspnetcore/pull/23833). It was in preview but has never been released. Wasn't it?

Thanks for any answer.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @boukenka.
The roadmap issue you're referring to is still a work in progress.

> 1. Finalize the Microsoft.AspNetCore.Components.DataAnnotations.Validation. This is still 3.2.0-rc1.20223.4. Should it be included by default ? Sorry to ask you the same question again. It was discussed here : Package version for ObjectGraphDataAnnotationsValidator. I think it is really necessary.

We've decided to make the `ObjectGraphDataAnnotationsValidator` part of Blazor in .NET 6.

> 2. What about the possibility to modify the document title and meta information ? Influencing HTML Head from a Blazor component. It was in preview but has never been released. Wasn't it?

It is currently on our roadmap but it's one of the lowest priority items. What that means is that we will get to it after finishing the rest of the issues we plan to handle in .NET 6.
