### ISSUE TITLE
Blazor component virtualization with ItemsProvider when underline request change

### ISSUE THREAD

**Issue by jeanf** [dotnet/aspnetcore#28971]
I have a component virtualized to navigate among big amount of data (more than 130000).
I added a filter on a field that can change total number of object returned.
I have no wya to notify virtualization component that the statset changed.
I saw on issue #26110 someboby having nearly same problem but he used Items and not ItemsProvider.
I cannot use Items because there are too many objects to return.
If I scroll in my list it's OK but I have to scroll down and the up.

Please I need some help

cheers
Jean

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `Virtualize` component has a method called `RefreshDataAsync`, which can be used to notify the virtualize component about changes in the underlying data.
