### ISSUE TITLE
Blazor + Static Web App - page load delay with dynamic content

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#28977]
I don't know if the behavior is the fault of blazor, the static web app or something else.

when I am logged in to the site, and I open a certain page, which contains dynamic content, its loading is affected, as it is only shown when all the content is available.

when I am logged out, the page appears immediately with the static content and immediately afterwards the dynamic content loads asynchronously.

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.

**Comment by drma-dev** [comment]
@pranavkm 

[https://github.com/drma-dev/DelayTest](https://github.com/drma-dev/DelayTest)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It may take some time for us to get to this as it's not immediately clear that there is a bug here. To speed up your investigation we recommend following-up on this in [StackOverflow](https://stackoverflow.com) as the community may be able to help you faster.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
