### ISSUE TITLE
MessagePack and Signalr on Azure

### ISSUE THREAD

**Issue by avialonn** [dotnet/aspnetcore#28989]
Hi there,
I'm I've implemented message pack and signalr (not signalr service) on my .net 5 application.
Locally everything works as expected. However, when moving to Azure App Service the application revert to the Json default and there is no sign for Message pack.
Any idea?
Many thanks
AA

**Comment by BrennanConroy** [comment]
What evidence do you have that message pack is or isn't working?
How are you configuring your server and client for message pack?

**Comment by avialonn** [comment]
Hi, 
I using the developer tool to see the requests. Locally I see that it going via the WS as binary call and on the server just a simple JSON.
Is there any configuration to be made on the server? I thought it should be application configuration only.
Am I missing anything? 
Thanks
AA
