### ISSUE TITLE
Enable Cross-Origin Requests (CORS) in ASP.NET Core 5 (.Net 5)

### ISSUE THREAD

**Issue by HamidTheGeek** [dotnet/aspnetcore#28987]
### Describe the bug
I am not unable to enable the CORS in ASP.NET Core 5

### To Reproduce
- Create a new API project from the following template:
![image](https://user-images.githubusercontent.com/33150399/103486082-ff903f80-4df2-11eb-9423-09ab52d2f10c.png)
- Apply any of the changes from the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0)
- Publish and host on IIS
- Host a simple HTML file on IIS to request the API like the following:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <p id="status"></p>
    <p id="json"></p>

    <script>
        const request = new Request(
            "https://api.example.com/WeatherForecast",
            {
                method: "GET",
                mode: "cors",
            });

        fetch(request).then(response => {
            document.getElementById("status").innerText = response.status;
            response.json().then(j => document.getElementById("json").innerText = j)
        });
    </script>
</body>
</html>
```
#### Or
 Clone the project from [GitHub](https://github.com/HamidTheGeek/CorsTest)

### Exceptions (if any)
> Access to fetch at 'https://api.example.com/WeatherForecast' from origin 'https://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Further technical details
- ASP.NET Core version: 5.0
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `Microsoft Visual Studio Community 2019 Version 16.8.3`

**Comment by pranavkm** [comment]
The server in this case is `https://api.stage.meetupfarsi.com`. Does it have CORS configured to allow your app to access it's response?

**Comment by HamidTheGeek** [comment]
Thank you @pranavkm for your comment. It was related to replacing the name of my test server with `exampl.com`. I missed this one and did not replace it.

**Comment by farshidsaberi** [comment]
I have not tested the code myself yet. But I think usecors should be earlier. Move it before userouting and try.

**Comment by HamidTheGeek** [comment]
@farshidsaberi  the document reads:
> The call to UseCors must be placed after UseRouting, but before UseAuthorization.

And in another place reads:

> With endpoint routing, the CORS middleware must be configured to execute between the calls to UseRouting and UseEndpoints.

Anyway, I have tested that and it is not working.

**Comment by HamidTheGeek** [comment]
I notice that it is the IIS blocking the request. It only works when I have `"AllowedHosts": "*",` in my `appsettings.json`. So, as a workaround, I have added `"MyRandomKey": "https://example.com",` in my `appsettings.json` and use the following in my `Startup`.

```csharp
services.AddCors(options =>
                options.AddPolicy(
                    CorsPolicyName,
                    policy =>
                        policy
                            .WithOrigins(Configuration.GetValue<string>("MyRandomKey").Split(";").ToArray())
                            .AllowAnyMethod()
                            .AllowAnyHeader()
                )
            );
```

**Comment by HamidTheGeek** [comment]
Hi @pranavkm 
I actually it's not been fixed. However, the issue might not be rated to asp.net runtime and be related to  ASP.NET Core Module/Hosting Bundle. I appreciate it if you could let me know how can I report and chase this.

**Comment by ocan4214** [comment]
did you find any solution for this ?

**Comment by HamidTheGeek** [comment]
@ocan4214 I have described my workaround [here](https://github.com/dotnet/aspnetcore/issues/28987#issuecomment-754187468)
