### ISSUE TITLE
Blazor WASM - use a few Identity Providers in one Application

### ISSUE THREAD

**Issue by researchdeveloping** [dotnet/aspnetcore#28998]
I would like to use two AAD identity providers (company AAD B2B and AAD B2C in one application. I don't want to use AAD B2B via AAD B2C). I want to use them as separate Login URL addresses (two buttons, each for them). 

It is possible to do that via WebAssemblyHostBuilder-Services-AddMsalAuthentication. Maybe I can do it via [-] AddOidcAuthentication if so, how ? Or maybe there is a different way to achieve it ? The think is that it should work in SPA WASM Blazor Application.

If no, then I request such. It will be very useful in many scenarios.

### Is your feature request related to a problem? Please describe.
I want to add a login for company AAD B2B Tantent users and second login and create guest users via AAD B2C in one application. I want to make it via different buttons on - similar as you have in WoodGrove sample app - customer and business login buttons).

### Describe the solution you'd like
As I think the easiest way it would be to add possibility to add multiple MSAL identity providers (and others as OIDC) and add contexts for them configured in options in AddMsalAuthentication to mark which authorisation method you would use. For e.g. in RemoteAuthenticatorView or other configurable component. The contexts would split authentications for e.g. to B2B and B2C in my case and support different authentications for them (you could configure it in page component, configure which one use).

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
