### ISSUE TITLE
ConnectionResetException since AddSigningCredential(s)

### ISSUE THREAD

**Issue by smbengue** [dotnet/aspnetcore#28992]
### Describe the bug
I do create a Blazor Webassembly project in Hosted mode (Client + Server + Shared).
Since, I tried to replace default Identity4Server Developer signing key with self generated certificates, login is not working anymore.
There are so many ConnectionResetException.

I reproduced this bug with new ASP NET 5.0 project using several certificates ( including certificates that  work on previous projects).

Thanks in advance.

Souleymane.

### Exceptions (if any)
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Net.Security.dll
Exception levée : 'Microsoft.AspNetCore.Connections.ConnectionResetException' dans System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.IO.IOException: The request stream was aborted.
 ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.AdvanceTo(SequencePosition consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Le thread 0xbf8 s'est arrêté avec le code 0 (0x0).

### Further technical details
- ASP.NET Core version
       -  3.1 
       - and reproduced with 5.0.
- Include the output of `dotnet --info`
-dotnet --info
SDK .NET (reflétant tous les fichiers global.json) :
 Version:   5.0.101
 Commit:    d05174dc5a

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
 VS 2019 CE - version 16.8.3

**Comment by BrennanConroy** [comment]
This looks like a client disconnect, are you refreshing the browser in the middle of the request?
