### ISSUE TITLE
Blazor WASM with custom user roles on Azure B2C

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#29000]
I would like to use Azure B2C as my identity provider, instead of IdentityServer for an ASP.NET Hosted Blazor WASM App.
Currently, I have defined 2 custom roles (Admin, User) which exposes different parts of the UI for Admins and allows uploading/deleting images with the backend API.

Is it possible to have the same authorizations with Azure B2C? Is there an example repo showing this? I found the [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-5.0) but I don't think is meant for B2C.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
