### ISSUE TITLE
Blazor + Brave Browser + Response.Headers.Add + "Content-Disposition" = Crash Application

### ISSUE THREAD

**Issue by Kruzer82** [dotnet/aspnetcore#29011]
I created new App Razer Server with .net 5.0 and add Authentication thing`s.
When logged in try download  **Personal Data**  
![image](https://user-images.githubusercontent.com/12413423/103563009-54e45380-4ebc-11eb-8648-880f896d9487.png)
get ```Program „[8592] iisexpress.exe” zakończył działanie z kodem -1 (0xffffffff).```

if comment ```Response.Headers.Add("Content-Disposition", "attachment; filename=PersonalData.json");```
and click Download i get property JSON and aplication working ok, if uncomment aplication close with code -1
Problem exist with browser Brave

### Describe the bug
If someone use Brave browser and try download File with ```Response.Headers.Add("Content-Disposition", "attachment; filename=PersonalData.json");```

### Further technical details
- ASP.NET 5.0
```Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

—rodowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download```
- Windows 10/ Visual Studio 2019

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Kruzer82** [comment]
https://github.com/Kruzer82/BlazorIssue29011

to reproduce BUG u need use Brave browser

**Comment by BrennanConroy** [comment]
Using version 1.18.77 of Brave and can't reproduce this issue.

I noticed your repro app is different from the app you show, does the repro app have the same issue for you?
Can you turn on server side logs and share those?
Are other browsers working fine for you?
