### ISSUE TITLE
Blazor client error, in VS 2019

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29020]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-client-error-in-VS-2019/1293685)._

---
[severity:I'm unable to use this version] [regression]
Major error when a <InputText> tag is NOT in a Form tag, when in razor file.
Caused an error when running and could not continue.

---
#### Feedback Bot on 12/21/2020, 09:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@SteveSandersonMS looks like this results in a NullReferenceException.
If we expect the component to be used only from within `EditForm` can we make so the error message helps clarify that?

**Comment by mkArtakMSFT** [comment]
Extracted the stack-trace from the issue: 
![image](https://user-images.githubusercontent.com/34246760/103704235-d2ac6b80-4f5d-11eb-86c2-06ae7d0f5e9d.png)

**Comment by mkArtakMSFT** [comment]
Can you please confirm, that the page loads correctly, when you remove the `InputText` component?
