### ISSUE TITLE
Blazor and code behind, code compiles, runs as expected but red Squigglies "Name does not exist", demo project included

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29029]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-and-code-behind-code-compiles-r/1291136)._

---
[severity:It's more difficult to complete my work]
We have a project with a blazor app. We use a structure with projects to seperate code so each team has there own projects.
You can see in the demo project an example of such a setup and the problem I encountered.
Not sure if it is related to the project setup, but the demo shows a reproducable way of my problem:

In the demo project, open the CurrentDateTime.razor file in the editor.
The editor states that the code is invalid.
Label and CurrentDateTime can not be found, while they are defined in the CurrentDateTime.razor.cs
Compiles and runs as expected.

This is very confusing while programming and reviewing.

---
#### Feedback Bot on 12/18/2020, 00:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
The goal here is to investigate if this still happens. I believe I indirectly fixed this when I fixed: https://github.com/dotnet/aspnetcore/issues/29271

**Comment by NTaylorMullen** [comment]
Yup this was fixed by #29271
