### ISSUE TITLE
[release/2.1] transitive dependencies aren't lifted for tests in patch builds

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#29023]
Imagine a test project `Test`, which references `Project1`, which references `Project2`. If we make a functional change to `Project2` in a patch, the test project will not consume the updated project - it only consumes the live-built version of its direct dependencies. The transitive dependencies get resolved from the baseline, which points to the latest public version on nuget.org. We should check to make sure that this understanding of our behavior is accurate, and either tweak our logic or our testing policy in 2.1 to account for it.

CC @dotnet/aspnet-build

**Comment by dougbu** [comment]
Resolved in 7aef1727e374c69b621d65189d60b7d6b3f1dd23 / #29037

**Comment by dougbu** [comment]
My thanks to @Tratcher who made me aware of this issue

**Comment by Tratcher** [comment]
🥳 I can break tests again.
