### ISSUE TITLE
Renaming a new razor component results in a Visual Studio error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29030]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Renaming-a-new-razor-component-results-i/1291458)._

---
[severity:I'm unable to use this version]
I would like to report the following error: Renaming a razor component results in a Visual Studio error. Logs are attached.

---
#### Feedback Bot on 12/17/2020, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/aspnetcore/issues/25914
