### ISSUE TITLE
Razor LSP: @using is not shown in the intellisense list at the last line of razor file after “Enable experimental Razor editor (requires restart)” is checked by default

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#29031]
Regression Info: Works well on Dev16.8.3
REPRO CONFIGURATION: Win 10 19H1 ENU + Dev16.9 Preview 3 (Preview channel : pre-release-build) VSP
.NET Core SDK (CLI) Version: 5.0.200-preview.20614.14
Latest .NET Core runtime Version: 5.0.1

INSTALL STEPS

1. Clean machine: Win 10 19H1 ENU

2. Install Dev16.9 Preview 3 [main-30829.69] VSP

Run preinstall \\vspreinstall\preinstall\preinstall.cmd
Install the Dev16.9 Preview 3 build from: https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/9a472ff07a5171f684adc83a2f5ae770157d1613/9f957836-b2b6-ec62-51c5-3e0af53494bb%3bchannels/internal/Preview/bootstrappers/fixed/Professional/vs_Professional.exe
.NET Core workload
Check .NET Core 3.0/2.2 runtime under IC tab
REPRO STEPS
Create new project > Blazor Server App > .NET 5.0  >Create

In _Imports.razor file, type "@us" at the last line.
Notes
This issue also repro on other razor file, like Index,razor, Counter.razor, etc.
It works well if type "@us" at the other lines of the razor file, instead of the last line.
This issue also repro on Razor project.
This issue also repro on 3.1 project.
After uncheck  “Enable experimental Razor editor (requires restart)”  it works well.
ACTUAL
Type "@us", using is not shown in the intellisense list.

Image
![image](https://user-images.githubusercontent.com/2008729/103590162-f8743a80-4ea1-11eb-927d-1c227d8a2b23.png)

EXPECTED
Type "@us", using is shown in the intellisense list.
Image
![image](https://user-images.githubusercontent.com/2008729/103590168-fca05800-4ea1-11eb-9033-27e6e01e93ad.png)

**Comment by TanayParikh** [comment]
Verified still an issue on latest VS.

**Comment by allisonchou** [comment]
Resolved by https://github.com/dotnet/aspnetcore-tooling/pull/2933.
