### ISSUE TITLE
Blazor's OnAfterRenderAsync not being called on .NET CORE 5.0 with webview1

### ISSUE THREAD

**Issue by sihlamMSFT** [dotnet/aspnetcore#29040]
We have an app running in Azure. This app was recently upgraded from .NET CORE 3.1 to .NET CORE 5.0. We noticed that now this app can no longer be running on a webview1 control in a wpf app.

The most basic symptom is that OnAfterRenderAsync is no longer getting call. (Same thing with OnAfterRender).

### To Reproduce
Here is the most basic repro project:
https://github.com/sihlamMSFT/WebAppSample

The Blazor app was simply the template project, with one method added which is the OnAfterRenderAsync on the FetchData page.

The Wpf app was simply the template project, with a single webBrowser page designed to load the blazor app that is running on localhost.

Steps:
1. Change the Blazor app to be using .NET CORE 5.0
2. Set a breakpoint on the method OnAfterRenderAsync in FetchData.razor.cs
3. run the Blazor app
4. run the Wpf app (double check that it is loading the Blazor app on localhost with the same port)
5. Click on the FetchData page
EXPECTED:
See that the breakpoint is hit.
ACTUAL:
See that the breakpoint is not hit.

If you change step one to use .NET CORE 3.1, you will see that the breakpoint will be hit as expected.

### Exceptions (if any)
There is no error at all. I assume something went wrong during the rendering phase, but the biggest symptom is OnAfterRenderAsync is not called.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you look at your server logs and see whether there are any errors reported?
Also, are you able to run the app in a browser while not hosted through a WebView?

**Comment by sihlamMSFT** [comment]
Thanks for the quick reply!

Both on our actual running app on Azure and in this test sample, we don't see any errors reported.

As far as browser goes,
On IE, both 3.1 and 5 don't trigger OnAfterRenderAsync
On Chromium Edge, both 3.1 and 5 trigger OnAfterRenderAsync just fine.
On Webview2, both 3.1 and 5 trigger OnAfterRenderAsync just fine.

**Comment by mkArtakMSFT** [comment]
@sihlamMSFT we've dropped support for IE in .NET 5 and we've announced it here: https://github.com/aspnet/Announcements/issues/441

That said, Blazor 3.1 is an LTS release which you can use for now and not rush to update to .NET 5.

**Comment by sihlamMSFT** [comment]
Yes. I understand that IE is not supported. (It never worked even before our .NET 5 upgrade anyways)

We don't see any statement about dropping support for webview1 though. (The majority of our customer base is using webview1 currently)

 I understand that having 5.0 re-support webview1 might not be an easy task (May be not even being considered), so we are mostly in possible workaround besides the obvious downgrade to 3.1.

**Comment by kmyrup** [comment]
Thanks, @mkArtakMSFT 

Mentioning IE was just for FYI.  Webview1 is Edge (legacy) browser control, and this is the one which the majority of our customers are using.  And it's the one which works in Blazor on .NET core 3.1, but not in 5.0.
