### ISSUE TITLE
 System.InvalidOperationException: Object of type 'BlazorApp.Pages.TabComponent' does not have a property matching the name 'Body'

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#29049]
Originally reported by @furqansafdar in #11212:

Guys, I am unable to achieve a simple routing in Blazor, to illustrate the scenario, I have a tab component containing the Tab control and within one tab item I have a TreeView component containing a TreeView control. Now when I am trying to click on the TreeView item, I am showing the related view of that particular item adjacent to it in the @Body. All looks wired-up but when I click on the TreeView item it shows the view but give me an error along with it.

> Error: System.InvalidOperationException: Object of type 'BlazorApp.Pages.TabComponent' does not have a property matching the name 'Body'.

- TabComponent (@page “/tab”) - containing Tab control
  - TreeViewComponent (@page “/tab/treeview”) - containing TreeView control and @Body
    - @Body (@page “/tab/treeview/view1”) to show selected TreeView item (View1) component

I don’t understand why is it complaining to have a Body at TabComponent level which is seemingly unnecessary. How can I smoothly work out this simple routing?

I am providing the code reference below (simplified) to show the relevant parts only. Please note that i am using Tab control from Razden library, however TreeView control custom made but i don't see any problem with that because it is just rendering the view in the @Body on TreeView node selection using `NavigationManager.NavigateTo()`. 

I have also asked the same question on this [SO Link](https://stackoverflow.com/questions/65565576/blazor-routing-or-navigation-inside-tab-using-treeview-control).

**TabComponent.razor**
```
@page "/tab"
@inherits ComponentBase

<BSTabGroup>
    <BSTabList>
        <BSTab>
            <BSTabLabel>TreeView</BSTabLabel>
            <BSTabContent>
                <TreeViewComponent></TreeViewComponent>
            </BSTabContent>
        </BSTab>
    </BSTabList>
    <BSTabSelectedContent></BSTabSelectedContent>
</BSTabGroup>
```

**TreeViewComponent.razor**
```
@page "/tab/treeview"
@layout TabComponent
@inherits LayoutComponentBase
<div class="container remove-margin">
    <div class="row">
        <div class="col-md-3">
            <TreeView Data="TreeDataSource" NodeSelected="@TreeNodeSelect"></TreeView>
        </div>
        <div class="col-md-9" style="height: 100%">
            <div class="card" style="height: 100%">
                <div class="card-header">
                    @Body
                </div>
            </div>
        </div>
    </div>
</div>

@code {
    protected void TreeNodeSelect(object args)
    {
        NavigationManager.NavigateTo("/tab/treeview/view1");
    }
}
```

**View1Component.razor**
```
@page "/tab/treeview/view1"
@inherits ComponentBase
@layout TreeViewComponent

<h1>View 1</h1>
```

**Comment by danroth27** [comment]
@furqansafdar I believe the issue here is that you've specified `@layout TabComponent` on `TreeViewComponent`, but `TabComponent isn't a layout component; `TabComponent` doesn't derive from `LayoutComponentBase`, so it doesn't have a `Body` property.

**Comment by furqansafdar** [comment]
@danroth27 i do not intend to mark `@layout TabComponent` on `TreeViewComponent` but with few hit and trial, i figured out perhaps it is important to specify layout to keep Tab control visible because otherwise TreeView control alone was rendering without having Tab on top of it when i was clicking the node item on the TreeView. I hope you understand my point.

**Comment by furqansafdar** [comment]
I would also like to suggest that there should be a relative routing mechanism in place. I do not intend to mark `@page "/tab/treeview/view1"` this long absolute route for my view1 with tab information as well and Navigation should also support component wise navigation regardless of such hard-coded routes.

**Comment by furqansafdar** [comment]
I have already provided my feedback and awaiting for response, what else is required from my side?

**Comment by danroth27** [comment]
Hi @furqansafdar.  This scenario isn't really what layouts are for. Instead I think what you want to do is capture route information from your `TabComponent` page and then propagate that down the component hierarchy so that the correct components are displayed. For example, you could update the `TabComponent` route to be something like `@page /tab/{tabName?}/{viewName?}` and then render the correct tab based on `tabName` and the correct view from the `TreeViewComponent` using `viewName`, which you pass in using a component parameter.

We do have an item on our backlog to add support for nested routers, so feel free to also add a :+1: to #11212.
