### ISSUE TITLE
UseHsts is not configurable (anymore?)

### ISSUE THREAD

**Issue by ygoe** [dotnet/aspnetcore#29042]
### Describe the bug
The extension method [`UseHsts`](https://source.dot.net/#Microsoft.AspNetCore.HttpsPolicy/HstsBuilderExtensions.cs,a4f4551c80f0cf62) can be used to set the HSTS HTTP response header. But it always uses its default configuration and there's no way to change it. I found old code online from 2017 that suggests passing an `HstsOptions` instance to that method, but no overload accepts a parameter here. (In ASP.NET Core 3.1)

### To Reproduce
Try to get this to compile: https://joonasw.net/view/hsts-in-aspnet-core

### Further technical details
- ASP.NET Core version: 3.1

There is no documentation whatsoever about the involved classes and methods. (Aside from useless stubs.)

The default max-age parameter is 30 days which isn't anywhere near what somebody would want to use here. At least the other properties have safe defaults.

**Comment by Tratcher** [comment]
The options are configured in ConfigureServices. See these docs:
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#options
```
    services.AddHsts(options =>
    {
        options.Preload = true;
        options.IncludeSubDomains = true;
        options.MaxAge = TimeSpan.FromDays(60);
        options.ExcludedHosts.Add("example.com");
        options.ExcludedHosts.Add("www.example.com");
    });
```
