### ISSUE TITLE
Microsoft.Extensions.Primitives makes Kestrel failing when writing to the output

### ISSUE THREAD

**Issue by Mimetis** [dotnet/aspnetcore#29046]
### Describe the bug

To reproduce the bug, I'm using a simple `.Net Core 3.1` console application, where I'm using `Microsoft.AspNetCore` and `Microsoft.Extensions.Logging.Configuration` (which references `Microsoft.Extensions.Primitives` internally)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="5.0.0" />
  </ItemGroup>

</Project>

```
When using `Version="5.0.0"`, kestrel is failing when calling `context.Response.WriteAsync()` with an **Object not set to an instance of an object** exception.
Rollbacking to `Version="2.0.0"` fixes the issue.

### To Reproduce

Using this simple code will trigger the bug:

```
var hostBuilder = new WebHostBuilder()
    .UseKestrel()
    .UseUrls("http://127.0.0.1:0/");

hostBuilder.Configure(app =>
{
    app.Run(async context => await context.Response.WriteAsync("Hello world"));

});

var host = hostBuilder.Build();
host.Start();
string serviceUrl = $"http://localhost:{host.GetPort()}/";

var client = new HttpClient();
var s = await client.GetAsync(serviceUrl);

var d = await s.Content.ReadAsStringAsync();

Console.WriteLine(d);

```
![image](https://user-images.githubusercontent.com/4592555/103660101-823d0a00-4f6d-11eb-8ce7-cbfb1f737d09.png)

As mentioned earlier, 
- Using `Version="2.0.0"` of `Microsoft.Extensions.Logging.Configuration` fixes the issue
- Removing the package resolves the bug as well, since `Microsoft.Extensions.Logging.Configuration` is part of `Microsoft.AspNetCore`

Obviously, in this sample case, I can remove the ref to `Microsoft.Extensions.Logging.Configuration` but in my real scenario, this reference is coming from an assembly that has this `v5.0.0` ref, that i can't change.

**Comment by davidfowl** [comment]
>     <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />

This package is incompatible with ASP.NET Core 3.1. Use the Web SDK or include the framework reference for ASP.NET Core:

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#framework-reference

**Comment by Mimetis** [comment]
Thanks @davidfowl for this fast answer :)

I saw this fix from you from https://github.com/dotnet/aspnetcore/issues/28112 

I understand that referencing `Microsoft.AspNetCore.App` will fix the issue, but this package is referencing a lot of packages I don't need (like MVC, Razor, EF and so on..)
Is there a way to have some minimalistic packages references only ?

**Comment by davidfowl** [comment]
Minimalistic in what way? What are you trying to optimize exactly?

**Comment by Mimetis** [comment]
Two main reasons:

- I'm developing a `.Net Standard 2.0` assembly (So far, if i'm not wrong, i can't reference `Microsoft.AspNetCore.App` ?)
- I just need, in that assembly, to work directly with an `HttpContext` instance, getting the `Request` and creating the `Response`
- I need to work with logging base classes.

https://github.com/Mimetis/Dotmim.Sync/blob/03067529d834b05b6b53f7f6b78069f3dd816818/Projects/Dotmim.Sync.Web.Server/WebServerOrchestrator.cs#L76

```
public async Task HandleRequestAsync(HttpContext context, Action<RemoteOrchestrator> action = null, 
              CancellationToken cancellationToken = default, IProgress<ProgressArgs> progress = null)
{
   var httpRequest = context.Request;
   var httpResponse = context.Response;

   // STUFF
   // THINGS
   // OTHER STUFF
   // ....

    // data to send back, as the response
    byte[] data = this.EnsureCompression(httpRequest, httpResponse, binaryData);
    await httpResponse.Body.WriteAsync(data, 0, data.Length, cancellationToken).ConfigureAwait(false);

}
```

For now, what I understand is that **IF** I need to stay on `.Net Standard 2.0` **THEN** I need to stick with version `v2.2.0`

The only problem I see, is that all `v5.0.0` assemblies are compatible with `.Net Standard 2.0`, leading to that bug and my troubles here :) 
(You know, VS 2019 always suggesting to me *"Hey dude, you can upgrade your nuget packages man ! you want do it ? come on, dude !"* )

**Comment by davidfowl** [comment]
> I'm developing a .Net Standard 2.0 assembly (So far, if i'm not wrong, i can't reference Microsoft.AspNetCore.App ?)

Nope, you'll need to cross compile for both ns2.0 and netcoreap3.1.
