### ISSUE TITLE
Project template for Blazor Desktop

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#29057]
Users should be able to create a new Blazor Desktop project via CLI, VS and VS4Mac.

- [ ] Need to define what the template should look like.
- [ ] This should be a single-project template, with support for multi-targeting. Need to follow up with partners to see how this can be done.
- [ ] Potential support for multi-targeting should be thought out as part of this issue. This may be a tooling feature, but need to be considered.

**Comment by Eilon** [comment]
* Main template work was done here: https://github.com/dotnet/maui/pull/1055
* WinUI template was implemented here: https://github.com/dotnet/maui/pull/1065
