### ISSUE TITLE
Build a BlazorWebView native control for .NET MAUI

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#29055]
This control is going to be supported on Windows and Mac.
This is going to enable hosting Blazor desktop apps natively in WinUI and Catalyst apps.

- [x] Create a new project in dotnet/AspNetCore, get it building and start moving code from xamarin/mobileblazorbindings
- [ ] Add some testing mechanism (automated)
- [x] Figure out how IPC will work, write a spec for it and implement

**Comment by rogihee** [comment]
- Will it be possible to consume this new BlazorWebView from both WinUI and WPF/WinForms? WinUI has a long, long time of becoming stable and less deployment surface as WPF/WinForms apps.
- I assume this will be built using WebView2 under the hood, will the underlying options of that control (e.g. disable dev tools, fullscreen) be exposed?

**Comment by Eilon** [comment]
Hi @rogihee our first push towards production will be to focus on Windows using WinUI3 + WebView2 and on macOS using Catalyst + WKWebView. While doing those, we certainly won't block any other scenarios, such as Windows+WPF+WebView2 and we'll want to have support for those via projects such as [Mobile Blazor Bindings](https://github.com/xamarin/MobileBlazorBindings/), which at this time are pre-production quality.

**Comment by Eilon** [comment]
Oh and for this: Will the underlying WebView2 be exposed?

I would certainly imagine so. We haven't even begun the final design of this, but I think that exposing WebView2 in some reasonable manner would be quite important for many scenarios.

**Comment by Code-DJ** [comment]
Hi @Eilon will it support popup dialog window using window.open. Not sure if extra logic will have to be baked into the framework to support this. Just flagging it here.

**Comment by Eilon** [comment]
I think opening popups is done via an event that triggers. It's something we'll have to look at to see the best way to support it.

**Comment by rogihee** [comment]
Will Blazor run in the native (AOT-ed!) runtime? Like in the exp. mobile bindings one runtime for both app and webview2 control in the app?

With the memory and performance benefits it would then likely outperform any JavaScript speed in CPU/Memory size (like Steve's experiment showed), making this control a potential Electron killer. That would be something!

**Comment by Eilon** [comment]
> Will Blazor run in the native (AOT-ed!) runtime?

All the app's Blazor code will run in the _platform's_ .NET runtime. So on Windows that means .NET Core 6. On macOS we're trying to figure out if that's Mono or .NET Core. It does not run any .NET code in the WebView - it just does some JS/.NET interop between .NET and the WebView.

**Comment by Eilon** [comment]
The initial work for .NET MAUI for Windows/iOS/macOS/Android is merged into the .NET MAUI repo! https://github.com/dotnet/maui/pull/654

**Comment by Eilon** [comment]
Closing this because the bulk of the work is done, and no more work should be needed in this repo. There are some remaining work items for preview 4, but they will be done in the https://github.com/dotnet/maui repo.
