### ISSUE TITLE
Http/3 for IIS

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#29078]
We'll need some basic tests for Http/3 support on IIS including:
- The bindings work as expected
- The protocol version is correctly reported
- Hello World requests
- gRPC scenarios (Reset, Trailers)
- Interop with HttpClient

We can use the new windows preview helix queue to run these.

**Comment by jkotalik** [comment]
@wtgodbe sounded like I was going to take this, so unassigning you for now 😄

**Comment by wtgodbe** [comment]
@HaoK I might ask you for help on this one

**Comment by HaoK** [comment]
Sure let me know how I can help
