### ISSUE TITLE
CSS isolation not working with a Blazor Server app

### ISSUE THREAD

**Issue by AndyWDev** [dotnet/aspnetcore#29076]
### Describe the bug
Unable to get CSS to work using 'CSS isolation' with a Blazor Server app.

### To Reproduce

- Using Visual Studio 16.8.3 create a default server blazor app.
- To the pages/Counter.razor file, add a new stylesheet and call it Counter.razor.css
- Modify the body tag in the generated file to change the background color - add some other style elements such as an H1
- Press F5 to run, navigate to the counter page - none of the css is displayed (even after refreshing browser cache)

- Alternatively, add a Components directory
- Create a Hello.razor and Hello.razor.css file
- Add some content to the razor file and css as appropriate
- Update the _imports.razor file to include the components directory
- Add the <Hello /> tag to the FetchData.razor file

**Note:**
In the obj directory when the app is running I can see a scopedcss file under pages (Counter.razor.rz.scp.css) which has the modified CSS inside.  The same for the above component directory.
There is also scopedcss/bundle.myapp.styles.css file.

When I inspect the Counter page I do not see a link to the above css file, also the razor pages do not seem to be modified ( I am guessing they get modified to update the appropriate css tags - as new to blazor).

I have added a link href to the _host.cshtml but it doesn't seem to make a difference.  

### Further technical details
ASP.Net Core -  3.1.0 with latest Visual Studio release.
.Net version 5.0.101
Visual Studio Enterprise 16.8.3

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Also, just noticed the `3.1` version above.
Blazor CSS Isolation is supported from 5.0 on.

**Comment by AndyWDev** [comment]
Hi, 
 thanks for your reply -  just for confirmation, when we say 5.0, are we referring to .Net 5.0  vs ASP.Net Core 3.1  - Visual Studio gives the options for both during project creation.   

When reading through the documentation I didn't see any clear references to version requirements for Blazor CSS Isolation.

**Comment by AndyWDev** [comment]
I see when I re-created the project using .Net 5 that the MainLayout and NavMenu  shared pages had CSS Isolation files - so I re-created the project and the issue was resolved.
