### ISSUE TITLE
Http/3 for HttpSys

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#29077]
We'll need some basic tests for Http/3 support on HttpSys including:
- The bindings work as expected
- The protocol version is correctly reported
- Hello World requests
- gRPC scenarios (Reset, Trailers)
- Interop with HttpClient

We can use the new windows preview helix queue to run these.

**Comment by Tratcher** [comment]
Initial commit: https://github.com/Tratcher/aspnetcore/commit/3a6e5fe0ce589710a9c3d3e1868f369644c12884, interop with HttpClient works.

TODO:
- Requires registry keys to be enabled.
  - Should we add skip conditions for that?
  - How can we get those enabled on the CI?
- The AltSvc Http/2 frame isn't being sent by the server?
- The Alt-Svc header works, but you have to set it by hand. Should we have an EnableAltSvc option [like kestrel](https://github.com/dotnet/aspnetcore/blob/0ad1efcb48ae3afccbf2b82afe6002efe2669bb1/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs#L100) to add the header?
- More variety of tests.
- The version detection changes are to code shared with IIS so IIS might just work, but it still needs testing.
- I noticed that Http.Sys's MoreEntityBodyExists request flag was set even for a GET request and it was adding the `Transfer-Encoding: chunked` request header for body detection compat. Is the client not closing the request appropriately so the server thinks there's a body? There's no END_OF_STREAM flag in HTTP/3, it relies on closing the QUIC stream. I wonder if that's not happening fast enough.

**Comment by JamesNK** [comment]
Kestrel doesn't send HTTP/2 alt-svc frame either - https://github.com/dotnet/aspnetcore/issues/18928

**Comment by Tratcher** [comment]
> Kestrel doesn't send HTTP/2 alt-svc frame either - #18928

True, but Http.Sys claims it will.

**Comment by JamesNK** [comment]
Ah ok.

> The Alt-Svc header works, but you have to set it by hand. Should we have an EnableAltSvc option like kestrel to add the header?

It makes sense to keep them similar. If it is not difficult to do then we should. HTTP/3 would require some middleware on HttpSys to add the header without it.

> I noticed that Http.Sys's MoreEntityBodyExists request flag was set even for a GET request and it was adding the Transfer-Encoding: chunked request header for body detection compat. Is the client not closing the request appropriately so the server thinks there's a body? There's no END_OF_STREAM flag in HTTP/3, it relies on closing the QUIC stream. I wonder if that's not happening fast enough.

With HTTP/2 we read a frame, and it includes data + a flag indicating whether this is the end of the stream. For example, HEADERS + END_STREAM.

With HTTP/3 that flag is coming from QUIC. We're going to be relying on the transport sending the final data and the complete flag together. It could be an issue in either how HttpSys is getting data from QUIC on the server, or the client.

I had that challenge here - https://github.com/dotnet/aspnetcore/pull/33926 - although in this situation the transport was in-memory pipes rather than QUIC.

**Comment by Tratcher** [comment]
I tested HttpClient with Kestrel and found the same request body issue so I filed it here: https://github.com/dotnet/runtime/issues/55347.

**Comment by Tratcher** [comment]
> * The AltSvc Http/2 frame isn't being sent by the server?

Found it. The tests re-use the IIS Express certificate bindings. These bind IIS Express's cert to an IP and port `0.0.0.0:44300`. Http.Sys has some restriction that doesn't all altsvc for IP based bindings, you need to use a hostnameport binding instead:
```
netsh http>add ssl hostnameport=localhost:44400 certhash=c7306ce743cf189e984cf804eb1d14fb62bd4f4e certstorename=MY
```
I can confirm that the altsvc HTTP/2 frame gets sent now. I'm having some trust issues on the client when I set up the binding like this, not sure why, it's the same cert.

**Comment by Tratcher** [comment]
> I'm following up with Http.Sys about why there's a restriction on the binding types.

The restriction is part of their push to get people to use host name bindings rather than IP bindings. It's not a technical limitation.

**Comment by JamesNK** [comment]
Does that need to be added to our docs?

**Comment by Tratcher** [comment]
It's not even in their docs yet...
https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-http#add-sslcert

**Comment by Tratcher** [comment]
As for the alt-svc header, I don't think that's practical for us to implement this release. Http/3 can be disabled both at the machine and endpoint tls binding, and we aren't set up to read any of Http.Sys's TLS binding information. It can be done, but it's a lot more work than having the app set their own alt-svc headers.
