### ISSUE TITLE
[Blazor WebAssembly] Localization not working on Firefox Developer Edition(85.0b4)

### ISSUE THREAD

**Issue by thepra** [dotnet/aspnetcore#29089]
### Describe the bug
When I do make changes on both `CultureInfo.DefaultThreadCurrentCulture` and `CultureInfo.DefaultThreadCurrentUICulture` in any browser I perceive the change of language on the webpage except Firefox Developer Edition, where this change seems to don't function at all, and there's no logs in the browser console

### To Reproduce
Make up a project with 2 buttons and 2 resource files for 2 languages, on click of each button change the CultureInfo accordingly, and setup Firefox Developer Edition as the starting browser.

### Further technical details
- ASP.NET Core version .NET 5
- Include the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
>  Version:   5.0.101
>  Commit:    d05174dc5a
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.101\
> 
> Host (useful for support):
>   Version: 5.0.1
>   Commit:  b02e13abab
> 
> .NET SDKs installed:
>   5.0.101 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

> Microsoft Visual Studio Community 2019
> Version 16.8.3

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
