### ISSUE TITLE
How to secure Unix domain sockets created with 'ListenUnixSocket'?

### ISSUE THREAD

**Issue by FramnkRulez** [dotnet/aspnetcore#29093]
I'm trying to implement cross-platform IPC using gRPC to kestrel using unix domain sockets via the Kestrel 'ListenUnixSocket'  ([ListenUnixSocket](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.listenunixsocket?view=aspnetcore-5.0#Microsoft_AspNetCore_Server_Kestrel_Core_KestrelServerOptions_ListenUnixSocket_System_String_) API.  

However I can't seem to figure how how to set security on the unix domain socket, it seems to create the socket with security attributes allowing any user to read/write from it instead of inheriting the security attributes of the process hosting Kestrel.  Is there an override so that a unix domain socket limited to only admin or system access can be created?

**Comment by halter73** [comment]
Have you tried changing the permissions of the directory containing the unix domain socket so it's accessible to only the admin/system user/group? I haven't tried it myself, but I suspect this would work.
