### ISSUE TITLE
VSCode colourisation not correct when passing string parameter to lambda method

### ISSUE THREAD

**Issue by adrianwright109** [dotnet/aspnetcore#29103]
Step to reproduce:

1. `dotnet new blazorwasm -o BlazorApp`
2. `cd .\BlazorApp\`
3. `code .`
4. Open `Index.razor` and append the following code to the bottom on the file:
```

<button @onclick="@(() => WriteToBrowserConsole("Button 2"))">Button 2</button>

@code {
    void WriteToBrowserConsole(string buttonName)
    {
        Console.WriteLine($"I've been clicked! (from {buttonName})");
    }
}
```
**Expected**
Not sure what the expected colour should be I'm guessing it should not turn it red.

**Actual**
The double quotes around the string parameter turn the preceding parentheses and double quotes red.

![image](https://user-images.githubusercontent.com/47532258/103816026-3d43d100-505c-11eb-8e3b-a59d2b68b18a.png)

FYI in Visual Studio 2019 with the Experimental Editor preview feature ON it looks like this:
![image](https://user-images.githubusercontent.com/47532258/103816931-ac6df500-505d-11eb-9652-d874c4fb5120.png)

**Comment by ryanbrandenburg** [comment]
The first one will be fixed by https://github.com/dotnet/aspnetcore/issues/26479. We're waiting on the API we need out of VSCode.

The second picture (lack of colorization of the Razor transition) is resolved by https://github.com/dotnet/aspnetcore/issues/27109.
