### ISSUE TITLE
Console Logging does not work with .Net 5 containerized docker apps

### ISSUE THREAD

**Issue by explorer855** [dotnet/aspnetcore#29110]
### Describe the bug
After updating to VS 2019 CE  16.8.3, I'm not able to find the console logs for the containerized .Net 5 applications. I have tried Repairing the VS installation multiple times but no luck so far. PFA, in the image below we can clearly notice that there are no log traces for .Net apps however the logs are appearing for Nginx reverse-proxy container.

![image](https://user-images.githubusercontent.com/35362932/103857393-6f951300-50dc-11eb-8a4f-7893415e80bd.png)

## Program.cs file ##

public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .ConfigureLogging(x => x.SetMinimumLevel(LogLevel.Information))
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseKestrel(serverOptions =>
                    {
                        serverOptions.AddServerHeader = false;
                        //serverOptions.AllowSynchronousIO = false;
                    });
                    webBuilder.UseStartup<Startup>();
                    webBuilder.CaptureStartupErrors(captureStartupErrors: true);
                    webBuilder.UseSetting(WebHostDefaults.PreventHostingStartupKey, "true")
                    //webBuilder.UseIISIntegration()
                    .UseStaticWebAssets();
                });

## Appsettings.json ##

"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }

## Dockerfile ##

FROM mcr.microsoft.com/dotnet/aspnet:5.0.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

FROM mcr.microsoft.com/dotnet/sdk:5.0.101-buster-slim AS build
WORKDIR /src
COPY ["src/Services/<<>>/<<>>/<<>>.csproj", "src/Services/<<>>/<<>>/"]
RUN dotnet restore "src/Services/<<>>/<<>>/<<>>.csproj"
COPY . .
WORKDIR "/src/src/Services/<<>>/<<>>"
RUN dotnet build "<<>>.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "<<>>.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "<<>>.dll"]

### Exceptions (if any)

I would expect the console logging feature should work like before. Thanks

### Further technical details
- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

Microsoft Visual Studio Community 2019
Version 16.8.3
WSL2
DOCKER CE

**Comment by clintsinger** [comment]
I have noticed the same issue with my existing projects which are still on .net core 3.1 and not yet upgraded to 5.0 using Visual Studio version 16.8.0

I'm not entirely sure when the problem started as I only noticed today.  I have been running the same project for months but wasn't looking at the logs until recently.

Cheers,
Clint

**Comment by explorer855** [comment]
I'm closing this issue as I no longer found this persisting on my Win-10 Setup.
