### ISSUE TITLE
Docs for MvcOptions.RespectBrowserAcceptHeader don't render */* media type correctly.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/aspnetcore#29114]
The source code for [MvcOptions.RespectBrowserAcceptHeader](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/MvcOptions.cs#L206) mentions the `*/*` media type as shown by the red arrow below:

> ![image](https://user-images.githubusercontent.com/20465797/103878735-e1bf2500-50e7-11eb-96da-da3196c398a0.png)

...however the `*/*` media type ends up rendering as a forward slash `/` on the [live docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcoptions.respectbrowseracceptheader?view=aspnetcore-5.0#Microsoft_AspNetCore_Mvc_MvcOptions_RespectBrowserAcceptHeader) as shown by the red arrow below:

> ![image](https://user-images.githubusercontent.com/20465797/103879043-5f833080-50e8-11eb-9e28-27c2c298556b.png)

I believe this is caused by converting the XML doc comments to markdown before converting to HTML for the live docs. The reason I think markdown is to blame is because even in this github window if you type `*/*` without enclosing it in back quotes, it renders just the forward slash in italicized form which is hard to spot. Using Chrome DevTools, you can see the HTML doing the same via the `em` tag:

> ![image](https://user-images.githubusercontent.com/20465797/103879833-652d4600-50e9-11eb-9e6e-92bbd7d9a9f6.png)

**I suppose the fix is to use back quotes in the XML doc comments so we get proper rendering when markdown is used, but I am not sure what ramifications the back quotes will have in other contexts (e.g. when rendering in the IDE help tooltips).**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@safern who is best positioned to look into this?

**Comment by safern** [comment]
I would start with @gewarren and @joelmartinez.

**Comment by gewarren** [comment]
Here's an example of an existing doc that uses backticks around the word "CounterMultiTimer100NsInverse". It seems that the backticks are simply dropped in IDE IntelliSense.

![image](https://user-images.githubusercontent.com/24882762/103940554-5b541480-50e2-11eb-8b1b-411f200d85a2.png)

![image](https://user-images.githubusercontent.com/24882762/103940565-61e28c00-50e2-11eb-8999-36aa8fb55335.png)

**Comment by mkArtakMSFT** [comment]
@gewarren can we use `<c>*/*</c>` instead? Will this work? Asking, because that's something we already use in some places.

**Comment by gewarren** [comment]
Yes, that is probably a better choice than the backtick.

**Comment by ericmutta** [comment]
Many thanks @mkArtakMSFT and team for following up on this!
