### ISSUE TITLE
Blazor server side: Conflicting assets with the same path '/wwwroot/_framework/_bin/System.Console.dll' for content root paths

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/aspnetcore#29118]
### Describe the bug
I recently tried to switch my Blazor server side (with a custom Blazor library) project from `netcoreapp3.1` to `net5.0`. However, after changing the framework versions, I now fell over the issues that somehow `System.Console.dll` seems to be overwritten from the server file (If I understood https://github.com/dotnet/aspnetcore/issues/26928 correctly). Is there anything else I could check to see where exactly the issue is? Right now, I have no idea which packages or projects cause the issue. This only occurs while publishing, e.g. with `dotnet publish --configuration Release -r win10-x64 --output publish/`...

### To Reproduce
Difficult to say, I wasn't able to reproduce this in a minimum working example yet.

### Exceptions (if any)
```log
C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(208,5): error :
Conflicting assets with the same path '/wwwroot/_framework/_bin/System.Console.dll' for content root paths
'C:\Users\Nutzer\Documents\Temp\src\Example.Clients\obj\Release\net5.0\win10-x64\blazor\unlinked\System.Console.dll' and
'C:\Users\Nutzer\.nuget\packages\microsoft.netcore.app.runtime.win-x64\5.0.1\runtimes\win-x64\lib\net5.0\System.Console.dll'.
[C:\Users\Nutzer\Documents\Temp\src\Example.Server\Example.Server.csproj]
```

### Further technical details
- ASP.Net Blazor server side project.
- Net Version: .Net 5.0
- ASP.NET Core libraries version: 5.0.1
- Visual Studio Community 2019, 16.8.30804.86
- dotnet --info:

```log
.NET SDK (gemäß "global.json"):
 Version:   5.0.101
 Commit:    d05174dc5a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.806 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by SeppPenner** [comment]
Ok, I found the issue, but still I don't understand it. My project file has specified the following:

```csharp
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

// And so on ...
```

If I run `dotnet publish --configuration Release -r win10-x64 --output publish/`, the above error occurs. If I run `dotnet publish --configuration Release --output publish/`, leaving the runtime out, it works as expected.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like you didn't complete migration properly. We recommend following our [migration guide](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio) and asking questions in [StackOverflow](https://stackoverflow.com) if you face issues with it.

**Comment by SeppPenner** [comment]
Thanks for the information, I thought, I did everything in there...

In case anybody gets the same issue, I have:

* Missed `@using Microsoft.AspNetCore.Components.Web.Virtualization` in the `_Imports.razor` file (I don't believe this caused the issue, but still).
* Missed `PreferExactMatches="@true"` in `App.razor` (I don't believe this caused the issue, but still).
* Used `<Project Sdk="Microsoft.NET.Sdk.Web">` instead of `﻿<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">` on the client side project (One of the things to look at).
* Included `<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.1" />` which shouled be removed (One of the things to look at).
* Used `builder.RootComponents.Add<App>("app");` instead of `builder.RootComponents.Add<App>("#app");` (Which wasn't an issue for me as I didn't use the client side as standalone, but still).
* Used `<app></app>` instead of `<div id="app"></div>` in the client side `index.html` file.

So, probably the issue in my case was the wrong SDK and the reference to `Microsoft.AspNetCore.Components.WebAssembly.Build`.
