### ISSUE TITLE
[Blazor WebAssembly] Missed library with proper version for `System.Security.Cryptography.Cng` 5.0.0

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#29125]
### Describe the bug
Missed library with proper version

### To Reproduce
I have installed `System.Security.Cryptography.Cng` 5.0.0 and during running application I got the following error:

```console
WASM-WORKER: BlazorWorker.WorkerCore.SimpleInstanceService.SimpleInstanceService: '{App}, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is requesting missing assembly 'System.Security.Cryptography.Algorithms, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
```
Runtime tries to find `System.Security.Cryptography.Algorithms` 5.0.0, but implicitly was installed only `System.Security.Cryptography.Algorithms` 4.3.1 as dependency of `System.Security.Cryptography.Cng` 5.0.0

### Further technical details
- ASP.NET Core 5.0.1

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Cryptography APIs aren't currently supported on WebAssembly. Even more, the `System.Security.Cryptography.Cng` library you're referring to is Windows specific, and it won't work either.

**Comment by mkArtakMSFT** [comment]
@redradist, aren't you getting warnings when calling APIs from that library?
On a side note, we've based all these statements on the assumption that you're running a Blazor WebAssembly app here.

/cc @lewing

**Comment by redradist** [comment]
> 
> 
> Thanks for contacting us.
> Cryptography APIs aren't currently supported on WebAssembly. Even more, the `System.Security.Cryptography.Cng` library you're referring to is Windows specific, and it won't work either.

@mkArtakMSFT It is not true ... It worked for me in Blazor WebAssembly 3.2.0, just check it

**Comment by redradist** [comment]
> 
> 
> @redradist, aren't you getting warnings when calling APIs from that library?
> On a side note, we've based all these statements on the assumption that you're running a Blazor WebAssembly app here.
> 
> /cc @lewing

@mkArtakMSFT No, I get crashed application, error

Blazor WebAssembly runtime tries to find `System.Security.Cryptography.Algorithms` 5.0.0, but in build folder located only `System.Security.Cryptography.Algorithms` 4.3.1

It worked on Blazor WebAssembly 3.2.0, seems like loading assembly changed ...

**Comment by mkArtakMSFT** [comment]
@redradist  I should have been clear here. By `not supported` I meant in 5.0.
You can read more about this at https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly
Also, 3.2 is going out-of support in few months. We recommend moving to 5.0.

**Comment by mkArtakMSFT** [comment]
You can, for now, use JSInterop and calling browser cryptography APIs (WebCrypto) directly.

**Comment by redradist** [comment]
> 
> 
> You can, for now, use JSInterop and calling browser cryptography APIs (WebCrypto) directly.

@Why call WebCrypto that depend on Browser if there is platform-independent library that will work similar everywhere ?
