### ISSUE TITLE
Scaling RESX inner loop experience for Localization 

### ISSUE THREAD

**Issue by alohaninja** [dotnet/aspnetcore#29138]
# Is RESX Dead? 
FYSA - [here is the link regarding if RESX is "dead"](https://github.com/dotnet/project-system/issues/1553#issuecomment-657772778)... there are numerous others I've come across... just the community sentiment is that this "string localizer" story is not 1st class inner loop experience

Using existing RESX editor and incremental builds are very painful for azure.microsoft.com - we are looking for ways to improve our build times as well as general updates to RESX touches. Would love to see some UX updates and even support outside VS IDE for RESX authoring.

[Here is a hack we use today for our RESX csproj](https://stackoverflow.com/a/51962412/175679) - curious if there is a better architecture / strategy we should be looking for localization. This hack feels like RESX is not built for scaling to dozens of cultures across thousands of pages. 

### Is your feature request related to a problem? Please describe.
[Scaling the RESX inner loop](https://github.com/dotnet/arcade/blob/4873d157a8f34f8cc7e28b3f9938b32c642ef542/src/Microsoft.DotNet.Arcade.Sdk/tools/GenerateResxSource.targets) to 40k+ RESX files is painful - the IOPS overhead forces us to build `en-us` only for local builds (_we support 26 cultures_). Existing approach works great for <1k RESX files - but falls flat with scaling any larger. Even opening a RESX takes tens of seconds in our SLN. 

### Alternative Localization Approaches
- [XLIFF MSBUILD Tasks](https://github.com/dotnet/xliff-tasks)
- RESX VS Code Generator Extension
- [RESX Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/)

### Additional context
@Pilchie - we discussed this internally and you suggested I open this public issue. Thanks for any feedback / direction!

**Comment by Pilchie** [comment]
Tagging a few non-ASP.NET Core people who might have other ideas about resx support and build perf: @tmeschter @rainersigwald.

@chsienki for the source generator idea.

@stephentoub @DamianEdwards - any idea if this has come up in any of the other inner loop investigations?

**Comment by Pilchie** [comment]
Also @jaredpar

**Comment by tmeschter** [comment]
@alohaninja If I understand correctly, you're encountering multiple functional and performance issues with .resx files:

1. When you have many cultures, incremental builds after changing the .resx file are slow.
2. .resx files result in a lot of boilerplate in the project file.
3. The specific issue of https://github.com/dotnet/project-system/issues/1553.

Are there other specific problems that you have encountered or are aware of?

**Comment by stephentoub** [comment]
> any idea if this has come up in any of the other inner loop investigations?

I've not heard of it elsewhere. But I've also not seen that many solutions with thousands of .resx files.

**Comment by DamianEdwards** [comment]
It's likely fair to say that the pattern devised for `IStringLocalizer`, `IStringLocalizer<T>`, and `IViewLocalizer` in ASP.NET Core led to many more RESX files being used than was previously the case. In ASP.NET projects of old, the standard idiom was for a single RESX file per project per language, or perhaps a file per resource kind per project per language. The new `IStringLocazlier` and `IViewLocalizer` types on the other hand encourage a resource file per **type** and per **page/view**. One can see how on a large web project that could increase the number of resource files by an order of magnitude or more, thus exposing performance issues at scale of the current RESX toolchain.

`IStringLocalizerFactory` can be used to more specifically control how many files your resources are spread over (or indeed `IStringLocalizer<T>` with a "marker" type) which might be an option to move to a different RESX file layout scheme, e.g. a file per project, namespace, folder, etc. Or RESX files can be used "directly" without these abstraction interfaces in conjunction with the standard generator that produces a `Resources` class with property accessors (this is basically orthogonal to using the `IStringLocalizer` abstraction).

That said, it would of course be nice to fix whatever issue is currently preventing the toolchain from scaling better.
