### ISSUE TITLE
Roadmap ASP.NET Core 6 - Other points ?

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#29147]
Hello @pranavkm @mkArtakMSFT,

Sorry to come back for more points. I will stop after this. 😄 
 
1. What about Blazor WASM supporting Cryptography? There are issues with this:  [System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform](https://github.com/dotnet/aspnetcore/issues/26123) and [WebAssembly: Aes.Create() throws System.PlatformNotSupportedException](https://github.com/dotnet/runtime/issues/42384) I guess it will be implemented in [Developers targeting browser-wasm can use Web Crypto APIs](https://github.com/dotnet/runtime/issues/40074) ? Could it be added to the list in that case ?
2. Could the following request made by @danroth27 be included in the roadmap: [Add ILocalStorage & ISessionStorage with Blazor WebAssembly friendly implementations](https://github.com/dotnet/aspnetcore/issues/25677) ?

Thanks for any answer again.

**Comment by mkArtakMSFT** [comment]
No worries, @boukenka.
The roadmap issue we have is still a work in progress. We're close to finalizing our plans for .NET 6 and will be updating it this month.

**Comment by boukenka** [comment]
@mkArtakMSFT Thanks for the feedback. 😄
