### ISSUE TITLE
Support wildcard matching when adding connection to SignalR group

### ISSUE THREAD

**Issue by scharnyw** [dotnet/aspnetcore#29145]
SignalR groups can be used to implement some form of pub/sub messaging between clients and/or servers. The current design requires an exact matching between the group name specified by the publisher and the subscriber. Is there any possibility in the future that it could support some sort of wildcard or pattern matching for subscribers? For example, consumer could specify a wildcard pattern when adding a connection to groups:

    await Groups.AddToGroupAsync(Context.ConnectionId, "part1.part2.*");

The connection would then receive messages sent to groups `part1.part2.part3`, `part1.part2.part3.part4`, but not `part2.part3`, etc.

This would significantly enhance the pub/sub and message routing capabilities of SignalR. In terms of changes, it would require all implementations of `HubLifetimeManager` to provide the corresponding capabilities, although for `RedisHubLifetimeManager` it could make use of existing Redis `PSUBSCRIBE` and `PUNSUBSCRIBE`.

Any chance this would be considered?

**Comment by BrennanConroy** [comment]
We aren't likely to do this as it is non-trivial and we haven't heard many asks for this feature.

It would be possible to implement this yourself with a custom implementation of the `HubLifetimeManager`, although it wouldn't work with the Azure SignalR Service.

You would need to handle de-duplication of messages when multiple groups are matched, and make sure that every server knows about every group (unless you use something like Redis which has PSUBSCRIBE).
