### ISSUE TITLE
(Blazor WASM) returnUrl for the login action of RemoteAuthenticatorView is not honored when LoginMode=redirect (.NET v5.0.2)

### ISSUE THREAD

**Issue by MatthewCarse** [dotnet/aspnetcore#29151]
**Issue**
Exact same issue as reported here:
https://github.com/dotnet/aspnetcore/issues/28769#issue-771739837

**Fix attempted**
"We received a report of this bug earlier and shipped a patch in 5.0.2."

5.0.2 installed:
dotnet --version
5.0.200-preview.21057.7

**Repro**
Repro steps followed, for blazor webassembly standalone with b2c (https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-5.0) , and still encountering the issue where an authenticated page is not redirected to after login when using redirect login mode rather than popup.

_Browser console after successful login with full page redirect_
![image](https://user-images.githubusercontent.com/9403238/104009468-00cebd00-51a3-11eb-80b4-66edc67c7888.png)

_Browser console from page load and successful login with popup_
![image](https://user-images.githubusercontent.com/9403238/104009825-82bee600-51a3-11eb-9a22-5b9346c3fc7c.png)

_Originally posted by @captainsafia in https://github.com/dotnet/aspnetcore/issues/28769#issuecomment-754082340_

**Comment by MatthewCarse** [comment]
Closing as Microsoft.Authentication.WebAssembly.Msal package is still v5.0.1 and change will only be available when package v5.0.2 becomes available, not just the .net5 nightly (https://github.com/dotnet/aspnetcore/pull/28498)

**Comment by WangHui201709** [comment]
well-------- 原始邮件 --------发件人： Matthew Carse <notifications@github.com>日期： 2021年1月8日周五 20:00收件人： dotnet/aspnetcore <aspnetcore@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [dotnet/aspnetcore] (Blazor WASM) returnUrl for the login action of RemoteAuthenticatorView is not honored when LoginMode=redirect (.NET v5.0.2) (#29151)
Closing as Microsoft.Authentication.WebAssembly.Msal package is still v5.0.1 and change will only be available when package v5.0.2 becomes available, not just the .net5 nightly (#28498)
