### ISSUE TITLE
Nested component with layout

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/aspnetcore#29169]
the @layout directive is used to nested pages layout. but this is not support for nested component layout.
for ex
Component1 :

```
<div>component 1 header</div>
@ChildComponent
<div>Component 1 footer</div>
@code {

[Parameter]
public Renderfragment ChildComponent{get;set;}

}

```
 and Component2 :

```
@layout Component1
<div>component 2 content</div>
```

and call component2 on index.razor page

`<Component2 />`

we must see 

```
component 1 header
component 2 content
component 1 footer

```

Thx
BR

**Comment by javiercn** [comment]
@ehsangfl thanks for contacting us.

In order for your component to be usable as a layout I believe it needs to meet a few requirements, like inheriting from `LayoutBase`

**Comment by ehsangfl** [comment]
this feature is not supported yet
[issue](https://github.com/dotnet/aspnetcore/issues/28915)

**Comment by ehsangfl** [comment]
if it is closed, I register a new request
