### ISSUE TITLE
GetLocalStorageValueAsync - Error while getting localstorage value from Android device

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29163]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/GetLocalStorageValueAsync---Error-while-/1304984)._

---
[severity:It bothers me. A fix would be nice]
I have used Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage for storing username and password in the browser local storage for my Blazor Server application. It is working fine in my desktop browsers
and in the Android browser also.  But the problem is,  after few minutes data not getting from GetLocalStorageValueAsync, but in the desktop browser(Edge and chrome) working fine. So once logged  user need to login again.  When i used Javascript local storage function, it is working fine. **This problem I found for Android mobile chrome browser.**

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimal project (ideally a GitHub repo) that illustrates the problem.
