### ISSUE TITLE
Blazor template choice selection

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29164]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/BLAZOR-TEMPLATE-CHOICE-SELECTION/1298750)._

---
The blazor web assembly is relatively new. It is appreciated. But I think it will be better if there is a choice of layout. Take for example a top navigation rather than a side navigation. Or a custom landing page like asp.net core MVC template. We appreciate the effort but I was just thinking it would be easier if you don't have to remove the side nav yourself but like the xamarin.forms have a choice of layout either side or top nav or simple main page. Thank you in advance.

---
#### Feedback Bot on 12/30/2020, 06:26 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.

#### Feedback Bot on 12/30/2020, 06:33 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by mkArtakMSFT** [comment]
@danroth27 FYI

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
