### ISSUE TITLE
Blazor WASM: Decouple EntrypointInvoker and DefaultWebAssemblyJSRuntime from WebAssembly.dll

### ISSUE THREAD

**Issue by ejhg** [dotnet/aspnetcore#29177]
By decoupling and/or simply exposing these 2 internal classes, we can enable more aggressive trimming in minimalistic WASM apps. This results in a reduction of 15+ dll dependencies that WebAssembly.dll brings with it, improving page load performance for minimalistic wasm applications.

## Summary

Currently (in version 5.0.1), one must either exclude Microsoft.AspNetCore.Components.WebAssembly.dll from linking or at least reference the Microsoft.AspNetCore.Components.WebAssembly.Hosting class to produce a viable build that executes and interops with Javascript. 

## Motivation and goals

Microsoft.AspNetCore.Components.WebAssembly.dll is currently a monolith that
- is required to successfully produce a build because it produces JS files.
- is explicitly required by blazor.webassembly.js
- contains the mostly standalone classes EntrypointInvoker and DefaultWebAssemblyJSRuntime, which are required for JS interop
- contains additional services and dependencies to support the full Blazor framework but that are not relevant for a simple Hello World or minimalistic application.

This is a relatively simple change that would help break the WebAssembly.dll monolith.

## In scope

- This only concerns trimming of WebAssembly.dll
- A simple Hello World console application (or equivalent) should not result in the loading of Microsoft.Extensions.* and Microsoft.AspNetCore.* dlls or other unnecessary dlls.

## Out of scope

- This does not concern trimming of other Blazor or .Net dependencies.

## Risks / unknowns

This change does not break functionality.  Some documentation for proper use would be needed. 

## Examples

A project file to support the minimalistic build would look like this.

```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />
  </ItemGroup>
  <ItemGroup>
    <TrimmerRootAssembly Include="[NEW MINIMAL DEPENDENCY]" />
  </ItemGroup>
</Project>
```

**Comment by javiercn** [comment]
@ejhg thanks for contacting us.

Could you tell us more about what you are trying to accomplish? Are you trying to build an application that doesn't involve Blazor at all?

**Comment by ejhg** [comment]
Thank you for your attention @javiercn 

Not sure what you mean by "Blazor".  I think "Blazor" is a very broad term for the entire tech stack.  If you are referring to the modules to enable browser rendering and other high level services from C#, then yes, I do not have a need for that.  I only need the build pipeline and the ability to interop between C# and Javascript.

The business need is to be able to deliver my C# code (and not unnecessary dependencies) to the browser with a minimal impact to page load performance for SEO and usability.  Currently this is impossible to do with Blazor out-of-the-box.  I think Blazor is right now conflating the .Net platform with a UI platform that shouldn't be spoon fed on us.

As I mention, the WebAssembly.dll brings with itself more than 15 additional files that are "blocking" from a page load point of view.  They increase the likelihood of network failure and latencies.

What I'm requesting is very simple to do, and it works very well.  You can see my prototype here https://deflection.app/ .  If you analyze the web requests, you will see that WebAssembly.dll and Microsoft.WebExtensions.* etc are not loaded at all.  To achieve this, I copy/pasted the classes I mention in this ticket, I modded blazor.webassembly.js to work with my assembly instead, and I trimmed WebAssembly completely out of my build. 

Unfortunately, even with this optimization, the website still gets a very low performance score (<20) from Google https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdeflection.app , but I'm confident I'll be able to make other improvements.

Worth mentioning, this is not just about payload size and count.  The amount of IL code loaded affects the performance score due to the insanely huge CPU processing that has to happen when the .Net VM starts up.  This means that even if the user has cached the dlls in the browser, the app still takes several seconds to start up.  You can see in the Google pagespeed results how bad this is, and that's what's dragging the score down so much.  So another reason for dropping all the unnecessary Blazor dependencies is to help with the CPU issue.

Thanks again for looking in to this.  I hope we can do something about this.

**Comment by javiercn** [comment]
@ejhg thanks for the additional details.

I don't think this is an immediate goal for us. I want to be very clear in that Blazor is a UI framework for building single page applications and it is not a general purpose way of delivering C# code to the browser. 

There are other ways to achieve that that don't require Blazor to be involved at all, for example UNO platform does this.

That said, I'll let other folks on the team chime in. I don't think this will be a priority for us on the near future, but we might be open to accepting a change provided that it is not disruptive, but before we do that, there are other possible solutions you can do yourself, like write a custom linker descriptor to explicitly trim everything that you don't need.

**Comment by ejhg** [comment]
@javiercn From a pure software design point of view, can't we argue that EntrypointInvoker and DefaultWebAssemblyJSRuntime belong in

**Comment by ejhg** [comment]
@captainsafia @javiercn Thank you for giving consideration to this proposal.  I don't want to increase your backlog size.  I can write my own interop layer anyways, so this is not a blocker for me.  I just thought this would be good design feedback to give y'all.

I'll close this ticket so it doesn't create unnecessary backlog.  Thanks again.

**Comment by captainsafia** [comment]
@ejhg Thanks for being considerate!

@danroth27 Ping in case you want to continue digging into feasibility/interest for this.
