### ISSUE TITLE
aspnetcore-runtime-3.1:arm64 missing from Debian packages.microsoft.com repository

### ISSUE THREAD

**Issue by Kixunil** [dotnet/aspnetcore#29173]
### Describe the bug
The `arm64` version of `aspnetcore-runtime-3.1` is missing from the official Microsoft Debian repository. (packages.microsoft.com)

### To Reproduce
1. install Debian stable on Raspberry Pi 4 (using official image)
2. `gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF`
3. `gpg --export BC528686B50D79E339D3721CEB3E94ADBE1229CF | sudo apt-key add -`
4. `echo 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/10/prod buster main' | sudo tee /etc/apt/sources.list.d/microsoft.list > /dev/null`
5. `sudo apt update`
6. `sudo apt install aspnetcore-runtime-3.1`

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info` - impossible to install
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version N/A

**Comment by JunTaoLuo** [comment]
We don't build debian installers for arm64 in 3.1. To acquire the ARM64 aspnetcore-runtime for 3.1 on Linux, you need to install the binaries: https://dotnet.microsoft.com/download/dotnet/3.1.

FYI @dotnet/aspnet-build

**Comment by Kixunil** [comment]
Why? The security issues solved by Debian repositories are the same regardless of architecture.
