### ISSUE TITLE
Pages should be pushed in a stack rather than being created every time

### ISSUE THREAD

**Issue by MhAllan** [dotnet/aspnetcore#29186]
I am new to Blazor, unfortunately it seems that when you land in a page a new object is created which means we lost the previous state of the page. Wondering if this is still called SPA framework!?

**Comment by En3Tho** [comment]
Google blazor state management...

**Comment by MhAllan** [comment]
I don't want to manage the state, I want the page stays there

**Comment by En3Tho** [comment]
Your page is just a mean to show information in your model. That's where your state should be. Not in the page. Any MV* pattern respects this distinction.

**Comment by javiercn** [comment]
@MhAllan thanks for contacting us.

@En3Tho is correct. Blazor pages are components managed by the Blazor router and when you navigate to another page they get destroyed and their resources released. This is the way it works in all common UI frameworks.

A SPA is not defined for whether a component preserves its state or not, it's defined by the ability to run the app in the browser and navigate to different areas of the app without reloading the document on the browser.
