### ISSUE TITLE
Unexpected debug.assert when attempting to type @section

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#29199]
![image](https://user-images.githubusercontent.com/1579269/104139445-63b98300-5360-11eb-9576-707383c47134.png)

Happened when I type `@se|` (pipe is cursor)

Note: This only happens in a .razor page (not .cshtml). Also, it doesn't seem to reliably happen every time.

cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Interesting, I assume it was at the end of the document?

**Comment by NTaylorMullen** [comment]
@allisonchou you might find that your `@using` issue is due to this exact problem. When running the VS extension in debug mode if you get spammed with these debug asserts you'll know 😄

**Comment by allisonchou** [comment]
Resolved by https://github.com/dotnet/aspnetcore-tooling/pull/2933.
