### ISSUE TITLE
Remove type="text/javascript" attribute from script element created in blazor.webassembly.js

### ISSUE THREAD

**Issue by krompaco** [dotnet/aspnetcore#29197]
### Is your feature request related to a problem? Please describe.
A script element added from blazor.webassembly.js has a type="text/javascript" attribute which makes HTML validation fail after JS/Blazor has loaded. I'm publishing from _microsoft.netcore.app.runtime.browser-wasm\5.0.1_.

### Describe the solution you'd like
There is no reason for using `type` attributes on `script` elements in HTML5 documents so just remove that attribute... The failing excerpt:
`<script type="text/javascript">var Module; windo"...`

**Comment by saiphanish** [comment]
> ### Is your feature request related to a problem? Please describe.
> A script element added from blazor.webassembly.js has a type="text/javascript" attribute which makes HTML validation fail after JS/Blazor has loaded. I'm publishing from _microsoft.netcore.app.runtime.browser-wasm\5.0.1_.
> 
> ### Describe the solution you'd like
> There is no reason for using `type` attributes on `script` elements in HTML5 documents so just remove that attribute... The failing excerpt:
> `<script type="text/javascript">var Module; windo"...`

I am trying to fix this issue by removing the 'type' attribute but i cannot find the list of HTML5 documents, where this change must be done. can you please advice.

**Comment by krompaco** [comment]
Hi! Search for type/javascript in *.js files. It's added dynamically by the script I refer to.

**Comment by saiphanish** [comment]
> Hi! Search for type/javascript in *.js files. It's added dynamically by the script I refer to.

Thanks.  I will do this in AspNetCore.sln level?

**Comment by krompaco** [comment]
> > Hi! Search for type/javascript in *.js files. It's added dynamically by the script I refer to.
> 
> Thanks. I will do this in AspNetCore.sln level?

Looked around and seems like this is the place (so TypeScript not .js)...

https://github.com/dotnet/aspnetcore/blob/6b95e58bb4d113d210e519b99f79365b8a5dbb19/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L208

**Comment by krompaco** [comment]
I was a bit quick to type earlier. Search should have been `text/javascript` and nothing else.

https://github.com/dotnet/aspnetcore/search?q=text%2Fjavascript

**Comment by SteveSandersonMS** [comment]
Done in https://github.com/dotnet/aspnetcore/pull/29386
