### ISSUE TITLE
Blazor Feature Request: Make it possible to track downloading progress at initial website loading

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/aspnetcore#29193]
### Is your feature request related to a problem? Please describe.
The initial download size can be a problem if the appsize is huge or the first time visitor has a slow network connection. This will lead to many user leaving the site before its loaded, because they might think the website is broken and not loading.

### Describe the solution you'd like
One of the solutions that i thought of is to make a feature that can track the progress of the downloading of the initial files, and then make those download progress properties available through javascript.

Then we can use vanilla javascript and manually update the DOM the old way (because the wasm files is not loading yet) and show the download progress to the first time visitors, so then they can see that the site is loading and not broken.

This probably will make visitors stay a little longer and wait for the website to load.

I know if you load javascript files with javascript, then you can get the progress of how much it have downloaded, but im not sure how wasm file works https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#monitoring_progress

**Comment by javiercn** [comment]
@Assassinbeast thanks for contacting us.

You can create this yourself by using a custom resource loader to keep track of the progress. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0) for a snippet
