### ISSUE TITLE
Unable to load the service index for source https://www.myget.org/F/aspnetcidev/api/v3/index.json

### ISSUE THREAD

**Issue by damccorm** [dotnet/aspnetcore#29207]
### Describe the bug
We have a reference to aspnetcidev in our project that is currently failing to load with a 404. This was working on December 16 ([example successful build](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=13872227&view=results)), but is failing now ([example failing build built off the same commit](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=14071349&view=results)).

### To Reproduce

I have an Azure Pipelines build reproing the problem here - https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=14071349&view=results.

The repro itself should be as simple as adding a line like this to any project https://github.com/microsoft/azure-pipelines-agent/blob/763575e4443b61e2957d60dca9a9e068d29ccd92/src/Test/NuGet.Config#L10

### Exceptions (if any)

```
/home/vsts/work/1/s/_dotnetsdk/3.1.100/sdk/3.1.100/NuGet.targets(123,5): error : Unable to load the service index for source https://www.myget.org/F/aspnetcidev/api/v3/index.json. [/home/vsts/work/1/s/src/Test/Test.csproj] [/home/vsts/work/1/s/src/dir.proj]
/home/vsts/work/1/s/_dotnetsdk/3.1.100/sdk/3.1.100/NuGet.targets(123,5): error : Response status code does not indicate success: 404 (Feed does not exist.). [/home/vsts/work/1/s/src/Test/Test.csproj] [/home/vsts/work/1/s/src/dir.proj]
```

### Further technical details

This is from my local repro (not Azure Pipelines), but it repros there as well
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.519 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

```

**Comment by amaillo-mc** [comment]
Same here, waiting for resolution or workaround...

**Comment by pranavkm** [comment]
Thanks for the issue report. We stopped using this particular feed a while ago and have been using Azure Devops for quite some time now: https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md#how-to-get-daily-builds-of-aspnet-core. 

Is there a reason you continue referencing that particular feed? RTM versions of most packages that was previously available on that feed should be available on NuGet.org.

**Comment by emknbaker** [comment]
> Thanks for the issue report. We stopped using this particular feed a while ago and have been using Azure Devops for quite some time now: https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md#how-to-get-daily-builds-of-aspnet-core.

Hi @pranavkm , do yu know if that is that a similar outcome for the https://dotnet.myget.org/F/aspnetcore-master/api/v2 feed? I've been getting similar 404 errors to the author above for that feed, and navigate to it says that the feed no longer exists. Thank you!

**Comment by pranavkm** [comment]
@emknbaker that would be correct. We'd stopped using MyGet as a nightly feed for some time now and have more recently been removing the feeds entirely. Like I asked in my previous comment, are there specific packages from that feed that aren't available elsewhere?

**Comment by satya-rajesh** [comment]
looks this issue is observed for several packages:
/usr/lib/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Unable to load the service index for source https://powershell.myget.org/F/powershell-core/api/v3/index.json. [/usr/src/photon/BUILD/PowerShell-7.0.3/src/powershell-unix/powershell-unix.csproj]
/usr/lib/dotnet/sdk/3.1.201/NuGet.targets(124,5): error : Response status code does not indicate success: 404 (Feed does not exist.).

https://powershell.myget.org/F/powershell-core/api/v3/index.json - Feed does not exist.

Not sure which is the right area who can address this, any suggestions ?

**Comment by emknbaker** [comment]
@pranavkm Thanks for your response. I am looking for the ASP.NET Core version of `SignalR.Server`, version 0.1.0 .

**Comment by BrennanConroy** [comment]
A lot of the myget packages are available with the feed "https://pkgs.dev.azure.com/dnceng/public/_packaging/myget-legacy/nuget/v3/index.json"

> I am looking for the ASP.NET Core version of `SignalR.Server`, version 0.1.0

Please move off of that package starting 5 years ago, it is super unsupported and half done.

**Comment by axm** [comment]
Trying to install `Azure.Storage.Blobs` and getting the same error

```
Error		Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json.
Response status code does not indicate success: 404 (Feed does not exist.).				
```

Can you please advise on resolution?

**Comment by axm** [comment]
Looks like I resolved the problem by upgrading my VS to version `16.8.5`.
