### ISSUE TITLE
signalr.min.js requires signalr.min.js.map

### ISSUE THREAD

**Issue by incutonez** [dotnet/aspnetcore#29209]
### Describe the bug
I was reading [this thread](https://forums.asp.net/t/2154385.aspx?signalr+min+js+map), and I saw that signalr.min.js shouldn't require signalr.min.js.map, and I didn't see a bug related in that thread or in the Issues area of this github project, so I wanted to post here.  What I'm trying to do is use signalr.min.js in a production build, and when the page loads, I get a 404 error for signalr.min.js.map that's originating from signalr.min.js.  signalr.min.js.map doesn't seem like it's required, as signalr still works, or appears to work.

### To Reproduce
1. Extract the attached file ([Desktop.zip](https://github.com/dotnet/aspnetcore/files/5797283/Desktop.zip))
2. Open signalr.html
3. Open browser debugger
4. Notice that the connection is trying to be made (expected), and there's a 404 for signalr.min.js.map (unexpected)

### Exceptions (if any)
Firefox Debugger:
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: file:///Desktop/signalr.min.js
Source Map URL: signalr.min.js.map

### Further technical details
- Node package version @microsoft/signalr@5.0.0

**Comment by BrennanConroy** [comment]
This is a browser feature and expected when you open the browser debugger and don't have the .map file.

Are you seeing this when you don't open the browser debugger?

**Comment by incutonez** [comment]
Let's make something clear... it's not a browser feature that the browser itself is requiring the map file, it's that the min file is using [source map functionality](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map), yes?  If so, the question is, is the map file truly needed?  Like I had said, signalr seems to work without it.

I don't know how I would see this error without opening the debugger, no.

**Comment by BrennanConroy** [comment]
> is the map file truly needed?

No, source maps are a browser feature to help with debugging javascript files.

If you don't want to see those 404's you can:
1. Not open dev tools
2. Put the .map file next to your .js file
3. Modify the .js file to not include the .map reference
4. Add a rewrite rule for .map files and point them at an empty .map file
5. Turn off the source map feature in your browser

**Comment by incutonez** [comment]
This might be a dumb question, but if it's not needed, why is it referenced in the min file...?

**Comment by BrennanConroy** [comment]
Because that's how source mapping works. The article you linked explains why the comment is needed.

**Comment by incutonez** [comment]
I feel like I'm going in circles... you said the map file isn't needed, therefore, the min file shouldn't be requiring it, which is triggering the browser to make the load for the map file.  If the map file isn't needed, why does the min file require it?

**Comment by BrennanConroy** [comment]
The min file does not require it. The comment is merely a reference for the browser to try to use when debugging.

If you never press F12 which initiates the debugging tools then you'll never see an issue with the map file.

**Comment by incutonez** [comment]
Sorry, that was the disconnect for me... I didn't realize opening the debugger was the actual trigger of that load.  Thank you for explaining that.
