### ISSUE TITLE
Razor LSP: Assertion failure when pasting explicit expressions

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#29203]
Consistent repro:

- Open a .razor document
- Replace the contents of the file with the following,
```razor
@(Html.DevExtreme().TreeView()
    .ID("recordMenu")
    .KeyExpr("Id")
    .DataSource(ds => ds.Array().Data(Model.Navigation))
    .DisplayExpr("Name")
    .ItemsExpr("Items")
    .SelectionMode(NavSelectionMode.Single)
    .Width("100%")
    .FocusStateEnabled(false)
    .ItemTemplate(
    @<text>
        <div class="[%= NodeCssClass %]" title="[%= Description %]">
            <div class="[%= NodeCssClass %]-icon">[%= Icon %]</div>
            <div class="[%= NodeCssClass %]-text">[%= Name %]</div>
        </div>
    </text>
    )
    .OnInitialized("recordPopup.menuInitialized")
    .OnItemClick($"function(e) {{ recordPopup.menuItemClick(e, {Model.Id}, '{Model.DisplayMode.ToString()}'); }}")
    .OnContentReady("recordPopup.menuContentReady")
)


@{
    var x = DateTime.Now;
}
```

Expected: No assertion failure
Actual: 
![image](https://user-images.githubusercontent.com/1579269/104150437-aabe6d00-538e-11eb-8e6a-c67d6605a04d.png)

cc @ryanbrandenburg @NTaylorMullen

**Comment by ryanbrandenburg** [comment]
Glad I put that error message in there because this is 100% not what I thought it would be. Kind: 46 is `string -  escape character` and Kind: 18 is `string`. Both of those are straight out of the C# LSP. Therefore I see two possibilities: either the C# LSP is returning overlapping tokens (forbidden by the LSP spec), or remapping C# tokens isn't always consistent/correct (seems like we would have seen this express in other ways first so seems unlikely).

**Comment by ryanbrandenburg** [comment]
Filed https://github.com/dotnet/roslyn/issues/50384 against Roslyn after confirming we aren't mis-map things.

Also of note, the LSP spec changed slightly, overlapping tokens MAY be allowed, depending on the client settings, but none of our current targets (VS, VSCode) allow it so effectively it's still forbidden.

**Comment by ryanbrandenburg** [comment]
Talked with @allisonchou and we decided that the better thing to do here is to stop doing that Debug.Assert and start handling this case correctly. Roslyn will eventually fix C# LSP so it obeys the option above (needs some platform work first), but in the mean time there's no need for us to have this check.
