### ISSUE TITLE
blazor + link = #id doesn't work

### ISSUE THREAD

**Issue by drma-dev** [dotnet/aspnetcore#29218]
`<NavLink href="#head_seguranca">test</NavLink>`

`<div id="head_seguranca"></div>`

This link should take you to the section of the page where that id exists, but it is not working. Is it a limitation of the blazor or am I doing something wrong?

**Comment by meziantou** [comment]
This is not supported by Blazor out of the box. However, you can use the [`NavigationManager.LocationChanged`](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0&WT.mc_id=DT-MVP-5003978#uri-and-navigation-state-helpers) event to detect a new URL and scroll to the desired element using the JS function [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView). This logic can be wrapped into a reusable component as shown in this post: [Anchor navigation in a Blazor application](https://www.meziantou.net/anchor-navigation-in-a-blazor-application.htm)

Also, there is a similar issue with a few other solutions: https://github.com/dotnet/aspnetcore/issues/8393

**Comment by javiercn** [comment]
@drma-dev thanks for contacting us.

As @meziantou points out, this is a known limitation of the current router/link. We'll use #8393 to track it.

**Comment by drma-dev** [comment]
target="_top"

i try this and worked
