### ISSUE TITLE
Flaky test: ProjectReferences_Graph

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#29213]
This times out occasionally since moving to the SDK repo. Skipping for now and using this issue to track enabling it.

**Comment by nagilson** [comment]
Are there plans to fix this test still? It is the only thing with coverage for a fair number of scenarios

**Comment by mkArtakMSFT** [comment]
@tmat I'll let you respond to @nagilson given that you own the dotnet watch now.

**Comment by nagilson** [comment]
Thanks :) The reason I bought it up is we are making minor changes to some files tested here and with limited coverage I would like to make sure I'm not breaking anything.
