### ISSUE TITLE
Using JS Interop in OnInitializedAsync() cannot initially find JS function

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#29215]
### Describe the bug
An error occurs finding the JS function when an app is first run. The JS function isn't found until a browser refresh. Server pre-rendering is disabled.

Per [this docs page](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0), this should work since the connection is made at this point:

> JavaScript interop calls must be deferred until after the connection with the browser is established.

### To Reproduce
The following code calls `window.checkSomething()` but fails if this is the first time the component has run in the browser. Refreshing and later calls to the component work.

```
protected override async Task OnInitializedAsync()
{
    bool result = await JSRuntime.InvokeAsync<bool>("checkSomething");
}
```

### Exception in Browser console
> Error: Microsoft.JSInterop.JSException: Could not find 'checkSomething' ('checkSomething' was undefined).

### Further technical details
- ASP.NET Core version: 5.0.1

**Comment by javiercn** [comment]
@mrlife thanks for contacting us.

This is very likely something in the initialization code in your document. Ensure that the function is available and accessible in the global scope before invoking it.

If you can produce a minimal repro we can take a look at it.

**Comment by mrlife** [comment]
@javiercn thanks for getting back to me.

> This is very likely something in the initialization code in your document. 

For this, are you referring to e.g. Startup.cs or lifecycle functions?

> Ensure that the function is available and accessible in the global scope before invoking it.

I'm not sure how one would do this part. Could you elaborate what this means?

Some more information from testing:

- Only occurs on published version
- All app visits below done in a fresh Incognito window/tab
- After publish, it sometimes works the first time
- Additional fresh incognito visits to the published app always result in the error
- Moving the JS Interop call to `OnParametersSetAsync()` results in the error only about half the time

**Comment by javiercn** [comment]
@mrlife what's the error on the browser?

I would suggest you start Blazor manually ( autostart=false) and then call `Blazor.start` and set a breakpoint (debugger; in js) befor calling Blazor.start.

Then on the dev tools check that your function checkSomething is already defined at that point. It can be that you are doing something asynchronous to define the function and timing is playing a role here?

Otherwise, please give us a minimal repro so that we can take a look.

**Comment by mrlife** [comment]
@javiercn you helped me figure it out. I can't find anything about it in the docs, but the `<script src="_framework/blazor.server.js"></script>` should be after other JavaScript files in `<body>`. It makes complete sense now, but not being a JavaScript person, this rule isn't hardwired yet.

Maybe adding something to the docs, if it's not somewhere I couldn't find, would be helpful for others?

cc: @guardrex

**Comment by guardrex** [comment]
It's covered in the integration topic at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0&pivots=server#configuration

... where is says to place it immediately before the `Scripts` render section, which would be immediately inside the closing `</body>` tag.

**Comment by mrlife** [comment]
@guardrex thank you for pointing that out. Since I'm using a pure Blazor app, I have not read this entire page before. 

@javiercn thanks again for your help.

**Comment by guardrex** [comment]
I see what you mean. When a dev works with an existing app, they may place scripts in a detrimental order for their app.

I opened https://github.com/dotnet/AspNetCore.Docs/issues/21200 to see about improving the coverage. I made it a P2 tho ... I have high priority UE passes to get back to. I'll try to address it tho by the end of January.
