### ISSUE TITLE
dotnet-install.ps1 can hang on ARM64 Windows machines

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#29223]
This issue got closed without a resolution to the underlying problem: https://github.com/dotnet/install-scripts/issues/119

@MattGal has some suggestions that might be worth following up on: 

> I don't have any direct contacts, but you might be able to reach out to the cobaltselfhost distribution list. Without a reliable repro, it's difficult to know how they can help, but they may have ideas or known Powershell issues.

**Comment by dougbu** [comment]
Not much can be done here 'til the next failure and maybe not even then. The hope is we get more information from the logging @captainsafia re-added in #29021

**Comment by JunTaoLuo** [comment]
I added some retries in https://github.com/dotnet/aspnetcore/pull/29842 and https://github.com/dotnet/aspnetcore/pull/30022. I don't recall seeing more dotnet-install.ps1 issues after that. Closing fyi @dotnet/aspnet-build
