### ISSUE TITLE
Add more detailed description to Blazor @on events

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#29227]
The current description for the `@on ` events are pointless.

> Sets the '@event' attribute to provided string or delegate value. A delegate value should be of type 'XXX'

There are so many events I have never heard of. I think I am not alone with this. Some kind of description of the events would be more useful in my opinion.

What I looking for is when the event is actually triggert. Or maybe an use case of when to use the event and when not.

The [docs ](https://docs.microsoft.com/en-gb/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0) help a little bit because it shows you an overview of categories but I still don't know when I can/should use an event nor it's purpose.

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

I think it might be good to have a little more info about specific event types, but I don't think having use cases belongs in the intellisense docs.

That said, I don't think it is currently feasible to do this based on the way these events are implemented internally, I'll let other folks on the team chime in, but I don't think this is currently easy to do.

**Comment by MarvinKlein1508** [comment]
@javiercn Yes use cases might be too much. But I think you should at least a description to the events which tells the user when it gets triggered.

**Comment by allisonchou** [comment]
Removing tooling tag, I believe the tag helper descriptions live in the Razor compiler.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
