### ISSUE TITLE
In reference to: Errors when add "Razor Class Library" reference to .NET5 Blazor Webassembly. #26959

### ISSUE THREAD

**Issue by JimInNC** [dotnet/aspnetcore#29238]
Why does 'dotnet new' perpetuate the problem laid out in issue #26959?
I spent several days trying to fix this error when referencing a razor class library from blazor client:
There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.
I fixed it using the recommendation in #26959.
All of my Microsoft stuff is up to date.  Including VS2019. I'm using .NET 5.

**Comment by pranavkm** [comment]
> There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

That error message usually indicates that the app is referencing the wrong SDK. Is this for a new app? If so, could you share exact steps that reproducers the issue?
