### ISSUE TITLE
Blazor RemoteAuthenticatorView OnLogInSucceeded event firing three times instead of once

### ISSUE THREAD

**Issue by mattruma** [dotnet/aspnetcore#29235]
### Describe the bug

I created a Blazor Web Assembly application that authenticates with Azure AD B2C.

When the user logs in, I call an external API to grab some additional data.

I am noticing the **OnLoginSucceeded** of **RemoteAuthenticatorView** component is firing three times, would expect this event to only fire once.

### To Reproduce

Here is a what my Authentication Page looks like:

![image](https://user-images.githubusercontent.com/188079/104351269-2fb29f00-54d3-11eb-8ee2-0f443aec5c04.png)

`UserService` is the code that calls the external api.

Here is what the output looks like in the network tab in the browser:

![image](https://user-images.githubusercontent.com/188079/104351372-4e189a80-54d3-11eb-958c-35760e270191.png)

### Exceptions (if any)

No exceptions are being generated, just excess hits to the API.

### Further technical details

Output from `dotnet --info` follows:

.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20601.7
 Commit:    b3b934bbf2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.519 [C:\Program Files\dotnet\sdk]
  2.1.616 [C:\Program Files\dotnet\sdk]
  2.1.811 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

**Comment by mattruma** [comment]
Is there a work-around or an alternative approach?

**Comment by mattruma** [comment]
@javiercn any update on when this will be fixed? If there is a better way to handle post authentication, please let me know.

**Comment by mkArtakMSFT** [comment]
Glad that you got this working. Closing, as no further action is pending here.

**Comment by ogix** [comment]
My callback gets fired 2 times with .NET 6 Preview 6.
I think this issue should be reopened since you don't expect this event to fire more than once.
