### ISSUE TITLE
ApiAuthorizationDbContext forces string keys in database

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#29242]
This ticket is a duplicate of https://github.com/dotnet/aspnetcore/issues/9548 - which I cannot comment on because it is locked.

@HaoK Says
> The idea is that apps can derive from IdentityDbContext directly and utilize the generic support there, this class is just meant to be sugar for the most common scenario

It would be far easier for us to consume an ApiAuthorizationDbContext that lets us specify a Guid (or other) type for the key than it would to work out how to properly descend from IdentityDbContext simply because there are a number of options you can specify that will compile but refuse to generate the database.

For anyone who needs it, the solution is here:
https://stackoverflow.com/questions/58208894/asp-net-core-identity-custom-apiauthorizationdbcontext

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by mrpmorris** [comment]
It would make sense if you didn't provide a class at all, but to provide a rubbish class makes no sense to me at all.
