### ISSUE TITLE
ASP.NET Core 5 Standalone Blazor Webassembly Remote Register does not work

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#29246]
### Describe the bug
A standalone Blazor app (eg. localhost:44399) that is not hosted with ASP.NET Core will mostly rely on external Identity provider for registration and login. **The redirect to remote register URL does not work.**

![image](https://user-images.githubusercontent.com/13166236/104381194-f08b4a80-54e0-11eb-89d7-960308378890.png)

Lets assume **localhost:44382 is the server** that manage the authentication and profile management.

Now in the Client Standalone Blazor App (localhost:44399) I will configure the remote register and profile paths from server. Note there are external paths.

```
            builder.Services.AddOidcAuthentication(options =>
            {
               // Note this is the external absolute path of register and manage in server
                options.AuthenticationPaths.RemoteRegisterPath = "https://localhost:44382/identity/account/register";
                options.AuthenticationPaths.RemoteProfilePath = "https://localhost:44382/identity/account/manage";               
            });
```

If I click on the Register on my client app, the code ignores the external server host **localhost:44382** address tries to redirect to the relative register path of the client host address  **localhost:44399**...

![image](https://user-images.githubusercontent.com/13166236/104380392-cbe2a300-54df-11eb-8ef9-333ac1b5f309.png)

Obviously there is nothing there and registration fails. **I think this is a major issue, basically due to this bug the Blazor standalone app cannot work with external Identity provider for user registration.**

### Further technical details
- ASP.NET Core version 5
- Visual Studio 2019
- Blazor Standalone Web Assembly (published statically - Not Hosted with ASP.Net Core)
- Blazor Server For Authentication and Profile management

**Comment by ameyasubhedar** [comment]
@mkArtakMSFT @pranavkm thanks for prioritizing the issue. One more issue I found today while investigating this further.

As per official [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc) and[ RFC Open ID standard ](https://openid.net/specs/openid-connect-discovery-1_0.html) (See 4.2.  OpenID Provider Configuration Response) The Open Id Configuration discovery endpoint can fully describe the login, registration and user management. The Open Id standard already provides authorization_endpoint, token_endpoint, userinfo_endpoint and registration_endpoint. So if an Identity Provider already provides you with a .well-known/openid-configuration and specifies the authorization, registration and user info end points then there should not be any need to provide RemoteRegisterPath  and RemoteProfilePath again.

The Login workflow already honors this, and so should registration and user info endpoints.

So there are actualy 2 major issues as I see in the current workflow :

**1.  ASP.NET Core Blazor Webassembly should fully honor the RFC Open ID standard and endpoints provided by .well-known/openid-configuration and once the clients configure the open Id identity provider there should not be any need to specify remote AuthenticationPaths paths in the first place.** 

For e.g.
```
  builder.Services.AddOidcAuthentication(options =>
            {
                // Configure OIDC provider options.
               // Here https://localhost:44382 provides .well-known/openid-configuration and all the external endpoints
              // so there should not be any need to specify remote registration or user info paths at all.
                options.ProviderOptions.Authority = "https://localhost:44382";
                options.ProviderOptions.ClientId = "A0C77391-A240-4EAF-B9A5-736CA79ECA0F";
                options.ProviderOptions.DefaultScopes.Add("openid");
                options.ProviderOptions.DefaultScopes.Add("profile");
                options.ProviderOptions.PostLogoutRedirectUri = "authentication/logout-callback";
                options.ProviderOptions.RedirectUri = "authentication/login-callback";
                options.ProviderOptions.ResponseMode = "code id_token";
            });
```


**2. If for some reason client does require a different RemoteRegisterPath and RemoteProfilePath then the issue described above should honor the external endpoints and redirect them correctly (original issue).**

I think both these issues are important for a seamless  external OIDC Identity provider integration. Also the documentation should be improved for the advanced use cases.

Again I appreciate you prioritizing this and thanks in advance. Feel free if more info is needed.

**Comment by Urgau** [comment]
I also encounter this problem on aspnet core 3.1. The problem seems to be due to the use of **PathAndQuery** in [RedirectToProfile](https://github.com/dotnet/aspnetcore/blob/636ff94d04e6872ec8b95e740f2df9cb52384ae1/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L361) and [RedirectToRegister](https://github.com/dotnet/aspnetcore/blob/636ff94d04e6872ec8b95e740f2df9cb52384ae1/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L353-L359) which doesn't include the base url.

**Comment by Urgau** [comment]
Hello, @javiercn sorry to ping you but since you wrote the code in question, you may confirm that this is indeed a bug and that it is indeed in [RedirectToProfile](https://github.com/dotnet/aspnetcore/blob/636ff94d04e6872ec8b95e740f2df9cb52384ae1/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L361) and [RedirectToRegister](https://github.com/dotnet/aspnetcore/blob/636ff94d04e6872ec8b95e740f2df9cb52384ae1/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L353-L359).

**Comment by abdu292** [comment]
@ameyasubhedar Just was wondering if you got any solution or any workaround until this is fixed.

I'm using a standalone Blazor app as well, but cannot configure the flow yet.

@mkArtakMSFT @pranavkm Any update on this would be much appreciated. Thanks!

**Comment by ameyasubhedar** [comment]
@abdu292, not yet I am also working on this issue and evaluating any potential workaround. Will keep you posted.

**Comment by developersamim** [comment]
We need this feature badly. Its a road blocker for us
