### ISSUE TITLE
Avoid publishing dotnet-watch package from the sdk repo

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#29268]
As part of migrating dotnet-watch to the SDK, we continue publishing the package which is consumed and expanded by the installer. A simple alternative would be to publish include the watch tool in the SDK pack and discontinue publishing the package.

**Comment by pranavkm** [comment]
FYI @wli3

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/sdk/pull/15406.

**Comment by wli3** [comment]
@pranavkm the dotnet/installer part is done?

**Comment by pranavkm** [comment]
I'll get that sorted as part of the dependency update PR. Keeping an eye on the installer repo.

**Comment by wli3** [comment]
@pranavkm make sure you resolve it ASAP since we have 2 days left for 6.0 preview 1
