### ISSUE TITLE
dotnet publish multiple blazor webassembly apps generate invalid blazor.boot.json manifests

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#29264]
* Create a hosted blazor webassembly app.
* Add a second app
* Configure the apps to be served from different subpaths (use https://github.com/javiercn/BlazorMultipleApps as a reference).
* Run `dotnet publish` on the server app
* Check the contents of the manifest and you'll see that the assemblies are not defined.

**Comment by pranavkm** [comment]
Here's a snippet you could use in an app targeting the 5.0.2 SDK to workaround this issue:

```xml
<Target Name="NoSoupForBlazorSdk" BeforeTargets="_ProcessPublishFilesForBlazor">
    <ItemGroup>
      <_BlazorPublishBootResource
        Include="@(ResolvedFileToPublish)"
        Condition="!$([System.String]::Copy('%(RelativePath)').Replace('/','\').StartsWith('wwwroot\_framework')) AND '%(Extension)' != '.a'" />
    </ItemGroup>
  </Target>
```
