### ISSUE TITLE
Rendering a Razor Component without using the Razor language

### ISSUE THREAD

**Issue by JaggerJo** [dotnet/aspnetcore#29260]
## Summary

It's currently (from what I know) not possible to render a Razor Component without using the Razor language to do so. As Blazor can be used without using Razor to build components (for example with [Bolero)](https://fsbolero.io) but it's currently not possible (from what I know) to Render a component from just C# or F#.

To enable this and get rid of the `_Host.cshtml` file in my case the `IComponentRenderer` could be made public. 

## Motivation and goals

Build Blazor Apps without Razor
https://github.com/dotnet/aspnetcore/discussions/29120

## In scope

Render Components and consume the returned `IHtmlContent`. 

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

- API of `IComponentRenderer` would be public and needs to be stable. It's a single method so that should be ok.

## Examples

Would look like my posted answer on SO except there would be no reflection required. 

https://stackoverflow.com/questions/65617445/blazor-server-sider-without-razor/65646501#65646501

PR https://github.com/dotnet/aspnetcore/pull/29178

**Comment by mrpmorris** [comment]
Descend from ComponentBase and override BuildRenderTree

**Comment by JaggerJo** [comment]
@mrpmorris not sure if we talk about the same thing.

If my goal is to render a component to a html string/buffer (with the special annotation so Blazor picks it up when bootstrapped) how does implementing a component help ? / How would I render that Component without using razor ?

Building components without the razor is easy - there are plenty examples in the Bolero docs.

**Comment by mrpmorris** [comment]
Sorry, I misunderstood

**Comment by javiercn** [comment]
@JaggerJo thanks for filing an issue.

We will consider adding a specific API for this in the future. That said, we realized that this should be possible today by using the HtmlHelper (which you can use straight from C# without razor being involved). You can wrap that into your own API and use that to render a component from C#/F#.

As I said, we might add an API to do this in the future, but it should be doable today as I described. Could you give that a try and let us know?

**Comment by JaggerJo** [comment]
@javiercn using the HtmlHelper works. Thanks for pointing that out. 

```fsharp
        task {  
            let htmlHelper = container.GetService<IHtmlHelper>()
            
            (htmlHelper :?> IViewContextAware).Contextualize(ViewContext(HttpContext = httpContext))

            // RenderComponentAsync is an extension from "Microsoft.AspNetCore.Mvc.Rendering"
            let! componentHtmlContent = htmlHelper.RenderComponentAsync<App>(RenderMode.ServerPrerendered)
            
            let componentHtml: string =
                using (new StringWriter()) (fun writer ->
                    componentHtmlContent.WriteTo (writer, HtmlEncoder.Default)
                    writer.Flush()
                    writer.ToString()
                )
        }
```

**Comment by craigajohnson** [comment]
There is something deeply satisfying about this - I will replace a dynamic component wrapper we wrote for this purpose with this logic instead. Also great to eliminate the .cshtml file - just feels out of place.
