### ISSUE TITLE
Semantic tokens not showing

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#29291]
On latest Experimental VS instances SemanticTokens aren't showing. This is because of the inclusion of MarkdownTextLiterals, which map to a non-existent VSClassification and thus return null, throw an ArgumentNullException, and stop SemanticTokens being used.

**Comment by gundermanc** [comment]
Fix: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/297487

**Comment by ryanbrandenburg** [comment]
Fixed now.
