### ISSUE TITLE
Why aren't background asynchronous operations automatically stopped when the user navigates away from a component?

### ISSUE THREAD

**Issue by aahmadi458** [dotnet/aspnetcore#29307]
### Is your feature request related to a problem? Please describe.
On the page [Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#cancelable-background-work), it's stated that:
>  It's desirable to stop the background work to conserve system resources in several situations. For example, background asynchronous operations don't automatically stop when a user navigates away from a component.

Why is it that "background asynchronous don't automatically stop when a user navigates away from a component"?! Isn't that desirable 95% of the time?! In most real-world scenarios, in the `OnInitialized` or `OnAfterRender` methods of a component, you're sending HTTP requests, or in general, doing a lot of background work, and unless your case is exceptional, you most often want the background work to be aborted/canceled as soon as the component is removed/disposed of.

### Describe the solution you'd like
As soon as a component is disposed, and removed from the DOM, any asynchronous operation that originated in it would be aborted automatically, without the need for manually using `CancellationTokenSource`, etc.

**Comment by javiercn** [comment]
@aahmadi458 thanks for contacting us.

The framework doesn't have any knowledge about what operations an app triggers on the background and no way to cancel them.

**Comment by aahmadi458** [comment]
@javiercn Thanks for the quick response.
Couldn't the framework automatically abort the execution of any methods in the component as soon as the component is disposed of?

**Comment by javiercn** [comment]
@aahmadi458 the framework doesn't have any knowledge of what method is executing on a given thread, doesn't own the threads (which belong to the threadpool) and doesn't have a way to signal cancellation to the user code.

The pattern to follow here is to implement IDisposable, create a field with a CancellationTokenSource, invoke `Cancel` within the dispose method and have any invocation that does asynchronous work check that cancellation token and stop doing more work.

**Comment by aahmadi458** [comment]
@javiercn Okay, that's kind of a bummer. But thanks for the guidance. One last question: Do you have to follow a similar pattern in other SPA frameworks as well, or is this specific to Blazor? I haven't worked with the others.

**Comment by javiercn** [comment]
@aahmadi458 this is not a Blazor specific behavior. It's the same on all frameworks since they don't have control over the application code.

**Comment by aahmadi458** [comment]
@javiercn Got it. Thanks.
