### ISSUE TITLE
The docs link for NET 6.0 in CLI should be updated. 

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#29314]
Repro steps:
Install .NET 6 SDK(6.0.100-alpha.1.21063.28) from https://github.com/dotnet/installer
In CLI, run "dotnet new razor" and observe the contents

Expected  Result:
The link for net 6.0 should be updated.

Actual Result:
The link is still for net 5.0
![image](https://user-images.githubusercontent.com/65637796/104569858-30dafc00-568c-11eb-83e7-c2d177a25b4b.png)

**Comment by javiercn** [comment]
@Pilchie I'm not sure if this is us.

I did a search over our codebase and couldn't find the message. Do you know who owns the templating engine these days?

**Comment by Pilchie** [comment]
@javiercn - I think it comes from https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/.template.config/template.json#L19

**Comment by javiercn** [comment]
@Pilchie apparently I don't know how to use the search function on this website 😄

**Comment by mkArtakMSFT** [comment]
This has been resolved by @HaoK in https://github.com/dotnet/aspnetcore/pull/29361.

I've created the aka.ms mapping already, but the branches don't exist yet. That will automatically work when we will branch for 6.0.

**Comment by mkArtakMSFT** [comment]
Thanks @HaoK!
