### ISSUE TITLE
Invalid web.config file instrumentation during publishing (ASP.NET Core 5.0)

### ISSUE THREAD

**Issue by AlexBAV** [dotnet/aspnetcore#29312]
When ASP.NET Core project is published to be used with IIS, `web.config` file is generated. If the project already contains a `web.config` file (in order to specify various IIS settings), it gets modified with the following text added under `configuration/system.webServer` node:

```xml
<handlers>
  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
</handlers>
<aspNetCore processPath=".\sitename.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess">
<environmentVariables>
  <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
</environmentVariables>
</aspNetCore>
```

However, for a `web.config` file with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <!-- Some global IIS settings -->
  </system.webServer>
  <location path="specific location">
    <system.webServer>
      <!-- Some location specific IIS settings -->
    </system.webServer>
  </location>
</configuration>
```

ASP.NET Core Publish script always adds its text under `location/system.webServer` node, not under the global one. This of course breaks deployment.

The original order of global and local items does not seem to change its behavior.

**Comment by pranavkm** [comment]
@vijayrkn is this a WebSDK thing?

**Comment by AlexBAV** [comment]
> @vijayrkn is this a WebSDK thing?

This is happening when publishing from Visual Studio. As far as I know it just invokes `dotnet publish` after all. If you think this is not relevant to this repository, could you please point me to the correct location to report this?

**Comment by Pilchie** [comment]
Ping @vijayrkn ?

**Comment by Pilchie** [comment]
@vijayrkn @BillHiebert any ideas?

**Comment by vijayrkn** [comment]
@Pilchie - Sorry I missed this. This is a known issue & we should have a bug already for this. Let me find it.

**Comment by vijayrkn** [comment]
Here is the bug with some details on the various usecases and complexities involved in identifying which section to add the AspNetCore element - https://github.com/dotnet/sdk/issues/12479

Work-around is: If you add a dummy aspnetcore element in the root, we will always update that section and not touch any other sections. 

Hope this helps.

**Comment by Pilchie** [comment]
Closing this one in favour of the above.
