### ISSUE TITLE
[Blazor WASM 5.0.2] Debug breakpoint not hit in OnInitialized method in Razor Class Library

### ISSUE THREAD

**Issue by mtranchi** [dotnet/aspnetcore#29335]
### Describe the bug
Debug breakpoint not hit in OnInitialized method in Razor Class Library from an ASP.NET Core hosted Blazor Client project

### To Reproduce
In [this github repo](https://github.com/mtranchi/DebugBreakNotHitInRazorClassLibrary), set breakpoints on the OnInitialized method as well as on the if statement in the code block of RazorClassLibrary1.Component1:

```
@code{
    string message;

    protected override void OnInitialized()
    {
        message = "OnInitialized breakpoint not hit";

        if (true)
        {
            message += Environment.NewLine + "Neither is the if statement breakpoint hit";
        }

        base.OnInitialized();
    }
}
```
then run the app. The breakpoints won't be hit.

### Further technical details
- ASP.NET Core version 5.0.2
- The IDE: VS 16.8.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@captainsafia can you please look into this? Thanks!

**Comment by SQL-MisterMagoo** [comment]
Workaround: Add an `await Task.Delay(tttt)` as the first line of Main() - where tttt is a large enough time (in ms) for the debugger to attach before the client runs.
e.g.
```c#
        public static async Task Main(string[] args)
        {
            await Task.Delay(3000); // This allows time for the debugger to attach before any client code runs

            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            await builder.Build().RunAsync();
        }
```
I find that 3000ms seems to be enough time on my machine - obviously it will vary.

![image](https://user-images.githubusercontent.com/11338430/104707677-9ffc3300-5714-11eb-8a6f-56a98f2c1aa7.png)

@captainsafia I did try a smaller delay, with a while loop checking for Debugger.IsAttached, but that seems to return false even when the debugger is attached, so not much use.

```c#
        await Task.Delay(3000);
        Console.WriteLine($"Debugger: Attached={Debugger.IsAttached}");
```

![image](https://user-images.githubusercontent.com/11338430/104709839-46493800-5717-11eb-84d9-8bb150b8a028.png)

**Comment by captainsafia** [comment]
Thanks for answering the question, @SQL-MisterMagoo!

As mentioned in his comment and in our docs, we don't currently support debugging the `OnInitializedAsync` method for the initially loaded page but the workaround above should do the trick for you.
