### ISSUE TITLE
Override default identity UI Blazor WASM ASP.NET Core 5.0.2 hosted

### ISSUE THREAD

**Issue by mtranchi** [dotnet/aspnetcore#29334]
### Describe the bug
Cannot scaffold Identity UI, I get the following message box: 
![overrideIdentityUiMsgBox](https://user-images.githubusercontent.com/16783462/104665704-0eeb7480-56a0-11eb-84d0-bb0d189ece4b.png)

### To Reproduce
Create a new ASP.NET Core hosted Blazor Client app from the template, select .NET 5.0 (I'm running 5.0.2), change authentication to Individual User Accounts, make sure the ASP.NET Core hosted checkbox is selected.
Then try to scaffold all the IdentityUI pages.

### Further technical details
- ASP.NET Core version 5.0.2
- The IDE VS 16.8.4

**Comment by javiercn** [comment]
@mtranchi thanks for contacting us.

@vijayrkn this seems to be an issue with the Identity scaffolder. Any thoughts on how to capture more details?

**Comment by vijayrkn** [comment]
Adding @deepchoudhery for scaffolding

**Comment by mkArtakMSFT** [comment]
@deepchoudhery any updates on this? Do you track this with a separate issue? Would be great to link it here as we need to close this one.
