### ISSUE TITLE
CS0103: The name 'preservewhitespace' does not exist in the current context

### ISSUE THREAD

**Issue by springy76** [dotnet/aspnetcore#29347]
No matter whether I use it as first line in my razor component file:
`@preservewhitespace true`

or between some nodes:
```razor
<div>
  @preservewhitespace true
  <div>
  </div>
  @preservewhitespace false
</div>
```

I always get the same error message: **CS0103: The name 'preservewhitespace' does not exist in the current context**

Using .NET 5.02 and SDK 5.0.102, even locked by global.json file.

**Comment by pranavkm** [comment]
@springy76 `@preservewhitespace` is a Razor directive and must appear before any code or markup in your file. 

```
@preservewhitespace true
@inject IFoo foo
...

<div>
```

**Comment by springy76** [comment]
but it just doesn't work there .. pos 1 in line 1 was the first thing I tried.

**Comment by springy76** [comment]
a good answer would have been:

> look for any occurence of `<RazorLangVersion>3.0</RazorLangVersion>` and remove them all
