### ISSUE TITLE
Update precedence and identity for NET 6 templates.

### ISSUE THREAD

**Issue by phenning** [dotnet/aspnetcore#29352]
Precedence and the identities for the templates need to be updated for display in Visual Studio.

See previous change history of template.json for the templates when this needed to be done for 5.0

Precedence should be incremented by 1000 and the identity for each template from 5.0 -> 6.0. Group Identity should remain unchanged.

For example:
https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyWeb-CSharp/.template.config/template.json

**Comment by mkArtakMSFT** [comment]
Thanks @phenning.

@HaoK we need to do this in preview1. Please prioritize this work. @pranavkm should be able to point to an earlier PR with similar changes to help you get started.
