### ISSUE TITLE
error on calling javascript of razor component

### ISSUE THREAD

**Issue by brutalzinn** [dotnet/aspnetcore#29369]
I'm trying to call a function in javascript on my razor component. My application uses netcore 3.1. I tried to call it using JSRuntime but it gives me the error "JavaScript interoperability calls cannot be issued during server-side pre-rendering, because the page has not yet loaded in the browser." Then ... I discovered that there is a method called OnAfterRendering that is invoked after this rendering. And I tried to put JSRuntime inside that method but I was not successful. The event is not triggered at any time. And when creating a new blank blazor project, the event is called. The blank project uses netstandard 2.1 and my current project uses net core 3.1 .. I am using the same nuget packages. My question is how to call the javascript function from within my razor component.
Synthesis of my script without using the OnAfterRendering method:
https://gist.githubusercontent.com/brutalzinn/8b6e52f9e4e2f0238e30d2f425b54836/raw/d3ec043efbd16a8ebf6ac49f74c05a4d73085245/Test.razor
Essence of my script with the OnAfterRendering method:
https://gist.githubusercontent.com/brutalzinn/70864dec044ea77904349448c7d531da/raw/c6dd4ca0235202217379966e74f5d4eb0a54e562/TestTwo.razor

**Comment by javiercn** [comment]
@brutalzinn thanks for contacting us.

OnAfterRender only happens after the first time the app renders on the browser in an interactive way. Is your app failing before that happens?

**Comment by brutalzinn** [comment]
Thanks for response. the developer console of mozila firefox say "the blazor.webassembly.js" not found on server. I trying searching for fix this issue but not good results.

**Comment by javiercn** [comment]
@brutalzinn It seems that the application is failing to start on the browser, hence no component is rendered interactively and for that reason "OnAfterRender" never gets called.

If the console says it can't find `blazor.webassembly.js` there is likely something wrong in the application. If you are using blazor server that should be `blazor.server.js` if you are using blazor webassembly, check on the network tab if the browser is able to load the script.

**Comment by brutalzinn** [comment]
Thanks for response. I'm converted a Library Dll that my program uses of Microsoft.NET.SDK.WindowsDesktop to Microsoft.NET.Sdk.Web. In my main app, his start a web server from the library and all works, but razor component apparentily dont work as expected. I'm giving http://127.0.0.1:5000/_framework/blazor.webassembly.js 404 error. And i only find _framework in my obj folder. But i cant find this on my Debug Folder

**Comment by javiercn** [comment]
@brutalzinn From what I can tell, it's likely that you are missing some configuration or that are not running the application correctly.

I would suggest you start with a Blazor application (maybe look at Razor Class Libraries if you are trying to build a reusable library) and copy the code over to make sure that you are not missing anything.

If you are running the app from the command line make sure you use `dotnet run` to do so or publish the app and run the application's exe in the publish folder.
