### ISSUE TITLE
Debug Wasm in a Dot Net Core MVC Project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29367]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Debug-Wasm-in-a-Dot-Net-Core-MVC-Project/1306342)._

---
[severity:It's more difficult to complete my work]
I have a Dot Net Core 5.0 MVC project with Contollers and views.  I've made a new Blazor Web Assebembly project to use as a client (I copied the client part from the Blazor App created by the template) to work on future developement in this project. I have it all running together with authentication and authorization working and with the routing working. The problem is I can't debug the WebAssembly code. It does not see the breakpoints. I also do not see the the Client files in the Script Document folder as I do when I run the supplied WebAssembly project for Blazor created from the template when I debug the project. The Scipt Document folder does have the blazorWebAssembly.js, the dotnet.5.0.1.js, the ComponentsWebAssembly AuthenticationSerivce.js, a wasm.00aba26a file, and an <eval>/VM46947589 file. None of the .razor files show up as they do in a pure WebAssemble project created from the template. I've made sure the  launchSetting.json files are correct the best I know how. The debugging works for the MVC project and for the javaScript code, it just doesn't see the breakpoints in the webAssemble Counter file. Although the counter does work.
I'm running in the Edge browser. If I do an F12 and the "Shift Alt D" I get 
"No webpage was found for the web address: https://localhost:44347/_framework/debug?url=https%3A%2F%2Flocalhost%3A44347%2F"
I also have the same ports defined for the MVC project and the webAssembly project.

---
#### Feedback Bot on 1/11/2021, 06:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@vsfeedback thanks for contacting us.

You likely need the development debug proxy as well as to indicate the inspect url in launchSettings.json. Check the Startup.cs on the server project of the blazor webassembly application and the launchsettings.json to identify what you are missing in your project.

If you still have issues afterwards, let us know.
