### ISSUE TITLE
Blazor "Error: The list of component records is not valid." when passing parameters without a default public constructor.

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#29376]
Reproduction:

Setup/working: 
https://github.com/vflame/VersionedBlazorReproduction/commit/01db800cd60f5f3a9ef4772ccb2201460212eaca

Broken:
https://github.com/vflame/VersionedBlazorReproduction/commit/247690d225491a8f150aeff5537cd63da706a805

errors out on both firefox/chrome (latest) and in private/icognito

.Net 5.0.2 sdk
visual studio 2019 preview 2
win 10

**Comment by vflame** [comment]
As a followup, `OnInitializedAsync()` and `OnParameterssSetAsync()` both show the parameter being set correctly but `OnAfterRenderAsync` is never called.

**Comment by javiercn** [comment]
@vflame thanks for contacting us.

Parameters need to be serializable and deserializable, if you don't have a public constructor the deserializer doesn't work and that is what causes this issue.
