### ISSUE TITLE
[Allow Anonymous skips all authorization] do  not   take effect completely

### ISSUE THREAD

**Issue by zaozaoniao** [dotnet/aspnetcore#29377]
### Describe the bug
I am use .NET 5 program,  The program  require  authentication &&  authorization in most cases，
 but also hava some special exception (Anonymous  access).

So  I use [EndpointRouting] and  [AllowAnonymousAttribute] to   implement  the  authentication :
 - The  [EndpointRouting]  ensure all  controller  action  need authorization 
 -  [AllowAnonymousAttribute]  added in the action  generate  the  special  exception.
 
It is clear **that the [AllowAnonymousAttribute] is priority than global  authorization statements**.
> https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-5.0
>Warning
>[AllowAnonymous] bypasses all authorization statements. If you combine [AllowAnonymous] and any [Authorize] attribute, the [Authorize] attributes are ignored. For example if you apply [AllowAnonymous] at the controller level, any [Authorize] attributes on the same controller (or on any action within it) is ignored.

**But I found  my  program still goto  the  authorization code    when I  use  the [AllowAnonymous] on the action.**
 

### To Reproduce
I will give  main code : 
``` ConfigureService
 //  Authentication 
            context.Services.AddAuthentication("token")
                   .AddScheme<TokenAuthenticationOptions, TokenAuthenticationHandler>(TokenAuthenticationDefaults.AuthenticationScheme,
                   option =>
                   {
                       option.ClaimsIssuer = configuration.GetSection("AppKeys")["ClaimsIssuer"].ToString();
                       option.ClientId = configuration.GetSection("AppKeys")["ClientId"].ToString();
                       option.ClientSign = configuration.GetSection("AppKeys")["ClientSign"].ToString();
                   });

            //  Authorization  
            context.Services.AddAuthorization(options =>
            {
                //  default policy
                options.DefaultPolicy = new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                     .AddAuthenticationSchemes("token")
                     .Build();
            });
```
```Configure
            app.UseRouting();

            //  register  the  authorization  middleware
             app.UseAuthorization();

            app.UseEndpoints(endpoints =>
              {
                  endpoints.MapGet("/", async context =>
                  {
                      await context.Response.WriteAsync("/");
                  })
                  .AllowAnonymous().WithDisplayName("index");
                  endpoints.MapHealthChecks("/healthz").AllowAnonymous().WithDisplayName("healthz");
                  
                  //  Global Controller-Action need  Authorization, But  I still add  some  [AllowAnonymousAttribute] on some  Action.
                  endpoints.MapControllers().RequireAuthorization().WithDisplayName("default");
              });
```
I  will see  the code enter  into the  authorization code [TokenAuthenticationHandler]   when the  request  match the [AllowAnonymous] action.

### Source  code  

 I  have see  the  [AuthorizationMiddleware] source code  , the  code expose  the  bug.
> https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs
```
  // IMPORTANT: Changes to authorization logic should be mirrored in MVC's AuthorizeFilter
            var authorizeData = endpoint?.Metadata.GetOrderedMetadata<IAuthorizeData>() ?? Array.Empty<IAuthorizeData>();
            var policy = await AuthorizationPolicy.CombineAsync(_policyProvider, authorizeData);
            if (policy == null)
            {
                await _next(context);
                return;
            }

            // Policy evaluator has transient lifetime so it fetched from request services instead of injecting in constructor
            var policyEvaluator = context.RequestServices.GetRequiredService<IPolicyEvaluator>();

            var authenticateResult = await policyEvaluator.AuthenticateAsync(policy, context);

            // Allow Anonymous skips all authorization
            if (endpoint?.Metadata.GetMetadata<IAllowAnonymous>() != null)
            {
                await _next(context);
                return;
            }
```
The  72 line show  the  source code develop  want  to  ensure  the  [ [AllowAnonymousAttribute] is priority than global  authorization statements] , but  it is behind  the [72 line Authenticate code].

**[Allow Anonymous skips all authorization] do  not   take effect completely.**
So I think  the [72 -77 line code ] must  be  ahead  of  [67 -70 authentication code]

### Further technical details
- .NET 5
- Vs 2019 16.9.0 Preview 1.0

**Comment by javiercn** [comment]
@zaozaoniao thanks for contacting us.

AllowAnonymous doesn't imply that policies are not evaluated, only that their outcomes are ignored. 

I don't think this is a bug, I believe this behavior has existed for a long time and I believe the outcome is the same regardless. I'll let some other folks on the team chime in to provide their thoughts.

**Comment by blowdart** [comment]
@HaoK / @pranavkm to confirm or comment

**Comment by zaozaoniao** [comment]
> @zaozaoniao thanks for contacting us.
> 
> AllowAnonymous doesn't imply that policies are not evaluated, only that their outcomes are ignored.
> 
> I don't think this is a bug, I believe this behavior has existed for a long time and I believe the outcome is the same regardless. I'll let some other folks on the team chime in to provide their thoughts.

AllowAnonymous doesn't imply that policies are not evaluated, But ther is no need  to [AuthenticateAsync User]。

The [policyEvaluator.AuthenticateAsync(policy, context);] show  the  policy  is Authenticating User one by one.

I am  AllowAnonymous , why the website  authenticate  me !

**Comment by HaoK** [comment]
Right the current behavior is intentional, AllowAnonymous does not affect authentication at all, it simply just means no authorization checks are performed against the policy/requirements and all users are allowed

**Comment by HaoK** [comment]
You can avoid authentication by default by not specifying "token' as your default authentication scheme, and only selectively applying it to certain endpoints

**Comment by zaozaoniao** [comment]
> Right the current behavior is intentional, AllowAnonymous does not affect authentication at all, it simply just means no authorization checks are performed against the policy/requirements and all users are allowed

no ,
```
 var authorizeData = endpoint?.Metadata.GetOrderedMetadata<IAuthorizeData>() ?? Array.Empty<IAuthorizeData>();
            var policy = await AuthorizationPolicy.CombineAsync(_policyProvider, authorizeData);
```
The code show that  you just use  endpoint  authorize Data to  generate  the  authorize policy。
  AllowAnonymousAttribute  should be taken into account。

**Comment by zaozaoniao** [comment]
When we use  [RequireAuthorization]  on  the  controller-acrtion endpoint,   the endpoint  actually produce [AuthorizeAttribute] for  the endpoint metadata,
 but if   we use  [AllowAnonymousAttribute]  on  the mvc action, there will generate  the  [AllowAnonymousAttribute] metadata.

So there will be  two  contradictory  metadata  on a  endpoint .
-----

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-5.0
 says that :  
![image](https://user-images.githubusercontent.com/5810880/105001714-2a24fe00-5a6b-11eb-9841-963d28b6e963.png)


So I think   this is a bug  for this situation。

**Comment by javiercn** [comment]
We don't consider this to be an issue nor something we plan to change in the future, the impact this has on any application is negligible and changing it would introduce a behavior change that can has unintended consequences we don't plan to do any change in this area.

The documentation above can be more clear in mentioning that the different policies might still be evaluated, but that's it.
