### ISSUE TITLE
Reduce Object[] allocations in SignalR Core Client methods InvokeCoreAsyncCore/SendCoreAsyncCore/StreamAsChannelCoreAsyncCore

### ISSUE THREAD

**Issue by joncloud** [dotnet/aspnetcore#29399]
## Summary

I would like to propose refactoring an private method, `Microsoft.AspNetCore.SignalR.Client.HubConnection.PackageStreamingParams`, to only allocate a new `Object[]` for method arguments, given that at least one of the arguments that was provided is a streaming type, e.g., `System.Collections.Generic.IAsyncEnumerable<T>` or `System.Threading.Channels.ChannelReader<T>`.

## Motivation and goals

This will help reduce allocations in high-throughput scenarios where a SignalR Core Client is sending a lot of non-streaming messages to a Hub method.

## In scope

* Reduced allocations for Hub method calls, which include only non-streaming arguments
* No negative impact to Hub method calls, which include streaming arguments

## Out of scope

* Reduced allocations for Hub method calls, which include streaming arguments

## Risks / unknowns

* Do method arguments for the scope of the Invoke/Send/Stream method mutate the original input argument?
    * Method arguments were not always copied to a new array. This was introduced with 364018238ad8f2846132c0b84c0733bdcd82c32a

## Examples

No public API change would be required for this change. 

The scenario that I am looking at is a MonoGame sending messages during the `Microsoft.Xna.Framework.Game.Update` loop, which may run at a frequency of once every 16.67ms.

**Comment by BrennanConroy** [comment]
This is something we've been wanting to do for awhile but it's fairly low priority. Are you seeing issues because of these allocations? Or just doing some exploratory browsing?

**Comment by joncloud** [comment]
I was eliminating allocations through my code, and came up short when it went into SignalR. I created https://github.com/joncloud/aspnetcore/commit/bfb94f2172a20b4e353ef426cc1d82fd43bdafef  to resolve this, along with some [BenchmarkDotNet](https://gist.github.com/joncloud/b6b8ae1c4f5fc63c3c7821006d695e62) tests. I can create a new PR if it makes sense.

**Comment by davidfowl** [comment]
Yes please send a PR for this 😁

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/29444
