### ISSUE TITLE
Google OAuth provider should provide avatar as a claim

### ISSUE THREAD

**Issue by leotsarev** [dotnet/aspnetcore#29392]
### Is your feature request related to a problem? Please describe.
When we receive external login callback from Google, Google sends us a lot of properties. Everything is parsed and mapped to claims, excluding avatar. It's simply ignored.

### Describe the solution you'd like
I like OAuth provider to automatically map avatar link to claim of some name.
Alternative solution could be bit a bit extra configuration on user side:
```
authBuilder.AddGoogle(options =>
                {
...
                    options.ClaimActions.MapJsonKey("urn:google:photo", "picture");
...
              });
```
But I think that it should just work™

### Additional context
https://developers.google.com/identity/protocols/oauth2/openid-connect#obtainuserinfo

**Comment by blowdart** [comment]
We'd accept a PR, with tests for this :)

**Comment by leotsarev** [comment]
@blowdart thanks for quick answer!
