### ISSUE TITLE
Unauthorized response (HTTP 401 status code) when reloading a page [Blazor WASM ASP.NET Core hosted]

### ISSUE THREAD

**Issue by mtranchi** [dotnet/aspnetcore#29394]
### Describe the bug
When I reload the Products page, I get a HTTP 401 response.

### To Reproduce
Project: https://github.com/mtranchi/AuthIssue
Run the solution, Register as a new user then log in. Go to the Products page. Works the first time, but when you reload the page, it gets a 401 Unauthorized response. This does not happen with the FetchData page, even though I pretty much copied everything over to the ProductsController.

### Further technical details
- ASP.NET Core version 5.0.2
- The IDE VS 16.8.4
- Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by Tratcher** [comment]
That github repo is empty?

**Comment by mtranchi** [comment]
@Tratcher Sorry 'bout that. It's up there now: https://github.com/mtranchi/AuthIssue

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.
