### ISSUE TITLE
Allow POST/PUT without Content-Length or chunked.

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#29398]
https://github.com/dotnet/aspnetcore/discussions/28565

Kestrel refuses POST and PUT requests with a 411 if they don't have a `Content-Length` or `Transfer-Encoding: chunked` header.
https://github.com/dotnet/aspnetcore/blob/702b937577122445498a2d800c7ca1782a1b3556/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs#L182-L188

That doesn't match the RFCs and limits client compatibility.

https://tools.ietf.org/html/rfc7230#section-3.3.3
>    6.  If this is a request message and none of the above are true, then
       the message body length is zero (no message body is present).
...
>    A server MAY reject a request that contains a message body but not a
   Content-Length by responding with 411 (Length Required).

https://tools.ietf.org/html/rfc7231#section-4.3.3 (POST) doesn't say anything about 411s or requiring a non-zero body or the associated headers.

Kestrel should default to no body when there is no content-length or chunked for HTTP/1.x.

This is a non-issue for HTTP/2 since the introduction of the END_OF_STREAM flag.

Note, there's another bug with this logic anyways: #26803

**Comment by MCCshreyas** [comment]
Seems like that `if` the condition is unnecessary there!  
I think there might be a reason for adding that condition explicitly. 

@davidfowl any thoughts?

**Comment by ladeak** [comment]
If I understand HTTP 1.0 [rfc1945#section-8.3](https://datatracker.ietf.org/doc/html/rfc1945#section-8.3) PUT and POST should return 400. In contrast to HTTP 1.1 and the referenced [rfc7230#section-3.3.3](https://tools.ietf.org/html/rfc7230#section-3.3.3) which *may* return 411. As this seems to be used for request, response sections of above RFC-s fall out of consideration.

I plan to do the following changes:
- alter the if condition to return 400 only for HTTP 1.0 for PUT or POST
- HTTP 1.1 will use MessageBody.ZeroContentLength regardless
- cover cases with unit tests
- I think I can even remove LengthRequired from `internal enum RequestRejectionReason`

Do you have any objections or further suggestions?

**Comment by Tratcher** [comment]
Sure, give it a try.

**Comment by Tratcher** [comment]
From the original discussion: @Dzoge

> 
> Hey
> I ran into an issue with some clients calling my REST sevice that do not send Content-Length header when the body is empty and Transfer-Encoding is not chunked. When this happens Kestrel returns HTTP 411 Length Required response.
> 
> I was looking for a way to intercept the request and manually inject Content-Length header with 0 but could not find the way to do it.
> 
> The server is running without a reverse-proxy in front of it and the requests go directly to Kestrel docker pod.
> 
> I searched the Kestrel source code and found a check for that specifically:
> aspnetcore/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs
> 
> Line 182 in 857bb0f
> 
>  // If we got here, request contains no Content-Length or Transfer-Encoding header. 
> 
> but I could not find any way to override this behavour.
> Is there any way to configure or intercept this behaviour and manually add a Content-Length header with 0 value or somehow make it pass this validation?
> 
> There is another way to solve this issue by putting a reverse-proxy in front of Kestrel that will fix the headers, but I don't want to introduce a new component in the chain if it is other way.

@dzoge, can you clarify which clients you were testing with?

**Comment by ladeak** [comment]
To manually test this during the change I used the Sample app in the Kestrel project, and cURL for Windows.

```ini
curl.exe -X POST http://localhost:5000 --http1.0
```

**Comment by Dzoge** [comment]
> From the original discussion: @Dzoge
> 
> > Hey
> > I ran into an issue with some clients calling my REST sevice that do not send Content-Length header when the body is empty and Transfer-Encoding is not chunked. When this happens Kestrel returns HTTP 411 Length Required response.
> > I was looking for a way to intercept the request and manually inject Content-Length header with 0 but could not find the way to do it.
> > The server is running without a reverse-proxy in front of it and the requests go directly to Kestrel docker pod.
> > I searched the Kestrel source code and found a check for that specifically:
> > aspnetcore/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs
> > Line 182 in [857bb0f](https://github.com/dotnet/aspnetcore/commit/857bb0f416b746c9eb7b9a412443b39c1701df6b)
> > // If we got here, request contains no Content-Length or Transfer-Encoding header.
> > but I could not find any way to override this behavour.
> > Is there any way to configure or intercept this behaviour and manually add a Content-Length header with 0 value or somehow make it pass this validation?
> > There is another way to solve this issue by putting a reverse-proxy in front of Kestrel that will fix the headers, but I don't want to introduce a new component in the chain if it is other way.
> 
> @Dzoge, can you clarify which clients you were testing with?
> 
> If we want Kestrel to be used as a reverse proxy (YARP) we should support this case.

The consumers of my service used curl:
`curl -X POST http://localhost:5000`
