### ISSUE TITLE
[net5.0]HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by snowchenlei** [dotnet/aspnetcore#29395]
### about:
[2.2.0 IIS Hosting Bundle 500.30 error when setting web.config ASPNETCORE_ENVIRONMENT](https://github.com/dotnet/aspnetcore/issues/5973)
[Duplicate ASPNETCORE_Environment present for InProcess hosting causes ASPNET CORE 2.2 fails to load appsettings](https://github.com/dotnet/aspnetcore/issues/4566)

### description:

1. one project is deployed on iis
2. add environment to `web.config`
``` xml
<aspNetCore processPath="dotnet" arguments=".\Lzez.Tendering.Web.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" >
    <environmentVariables>
          <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
    </environmentVariables>
</aspNetCore>
```
3. request
4. Soon the server will not be accessible

### exception
![http 500.30](https://user-images.githubusercontent.com/26211283/104861558-49d4fd00-596b-11eb-9253-439e2bb10894.png)
![iis error](https://user-images.githubusercontent.com/26211283/104861659-bbad4680-596b-11eb-8f73-eff3dfe04cd3.png)
`Application '/LM/W3SVC/10/ROOT' with physical root '**\publish\' has exited from Program.Main with exit code = '1'. Please check the stderr logs for more information.`
`Application '/LM/W3SVC/10/ROOT' with physical root '**\publish\' failed to load coreclr. Exception message:
CLR worker thread exited prematurely`
![iis worker exprocess导致cpu高占用](https://user-images.githubusercontent.com/26211283/104861372-818f7500-596a-11eb-8fe5-55cd83776100.png)
Cpu usage is still rising...

### Further technical details
- ASP.NET Core 5.0
- System：Windows Server2012/Windows10

**Comment by jkotalik** [comment]
Can you also get application logs from the application itself? You can do this by enabling stdoutLogEnabled to true.

**Comment by jkotalik** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-5.0, you can also enable enhanced diagnostics for more information from ANCM itself.
