### ISSUE TITLE
.NET 5 Razor Runtime Compilation.

### ISSUE THREAD

**Issue by Lamadelrae** [dotnet/aspnetcore#29413]
I'm running .NET 5 on windows 10, on chrome, I've noticed that the razor runtime compilation does in fact work when you let the compiler search for the view for you, BUT, when you specify the view's location, it doesn't compile on runtime. 

Example: 

`
        public ActionResult MyProfile()
        {
            return View();
        } //This works!
`
`
        public ActionResult MyProfile()
        {
            return View("~/Views/BackOffice/Admin/MyProfile.cshtml", AdminService.GetMyProfile());
        } //This doesn't   
`

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
