### ISSUE TITLE
PowerShell command was found in the module, but the module could not be loaded

### ISSUE THREAD

**Issue by preslyel** [dotnet/aspnetcore#29417]
### Describe the bug
I try to migrate my web API from framework to .NET 5. I have some code to get UUID via PowerShell
```
var script = @"$computerSystemProduct = Get-WmiObject -class Win32_ComputerSystemProduct -namespace root\CIMV2 
                    $computerSystemProduct.UUID";
```
in the framework version, it works fine, but in .NET 5 version, I've got null in the result and an error
The 'Get-WmiObject' command was found in the module 'Microsoft.PowerShell.Management', but the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Management'.

I use PowerShell from System.Management.Automation In both API
I've tried to change the script to 
```
            var script = @"Import-Module Microsoft.PowerShell.Management
                    $computerSystemProduct = Get-WmiObject -class Win32_ComputerSystemProduct -namespace root\CIMV2 
                    $computerSystemProduct.UUID";
```
but get the same result.

### To Reproduce
 var script = @"$computerSystemProduct = Get-WmiObject -class Win32_ComputerSystemProduct -namespace root\CIMV2 
                    $computerSystemProduct.UUID";
using (PowerShell ps = PowerShell.Create())
            {
                ps.AddScript(script);

                var pipelineObjects = await ps.InvokeAsync().ConfigureAwait(false);

                var result = pipelineObjects.FirstOrDefault()?.BaseObject?.ToString();
                var errors = ps.Streams.Error.ReadAll();
                return result;
            }

### Exceptions (if any)
No exception, an error in ps.Streams.Error.ReadAll()

### Further technical details
- .NET 5
- Wndows 8, x64
- VS 2019

**Comment by javiercn** [comment]
Thanks for contacting us @preslyel.

It looks like this question is not about ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to StackOverflow.

You can also probably try the [Powershell repository](https://github.com/powershell/powershell) to get a faster answer.
