### ISSUE TITLE
Add Support for JsonPatch Comparsion function natively.

### ISSUE THREAD

**Issue by hanslai** [dotnet/aspnetcore#29412]
Related to #3104, #26922, #15703

Currently there is no JsonPatch document comparison natively supported for .Net.   Please add this support to JsonPatch, it will helps us a lot as .Net programmers.  Almost all the application require a "Patch" operation.

For engineers like to use RazorPage and Blazor, it is very troublesome without such a JsonPatchDocument generation method. It is kind of surprise that MS is not considering it right now and close all the issues.

For now, all the community projects are out dated and not being maintained I believe.
[CSharpJsonPatchGenerator](https://github.com/morganabel/CSharpJsonPatchGenerator)
[Tavis.JsonPatch](https://github.com/tavis-software/Tavis.JsonPatch)
[JsonDiffPatch](https://github.com/mcintyre321/JsonDiffPatch)
[JsonPatch](https://github.com/KevinDockx/JsonPatch)

### Describe the solution you'd like
Create JsonPatchDocument without use a JavaScript library. such as [fast-json-patch](https://www.npmjs.com/package/fast-json-patch)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
