### ISSUE TITLE
Could we upgrade the VS 2019 workload to have new supported Windows 10 SDK?

### ISSUE THREAD

**Issue by eriawan** [dotnet/aspnetcore#29422]
Looking at this workload to install VS:

https://github.com/dotnet/aspnetcore/blob/1d2bb105cb713eb17e3bc56f678c2fc90fd3def8/eng/scripts/vs.json#L14

It says that it needs Windows 10 SDK of 17134. 
This SDK build of 17134 was released with Windows 10 1803, according to this Windows 10 SDK archive list:
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

And this Windows 10 1803 will have the last security updates on May 11, 2021:
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/revised-end-of-service-date-for-windows-10-version-1803-may-11/ba-p/1614136

That also implies that Windows 10 1803 support (including security updates) will end soon.

Based on that, could we update the SDK version in this workload to at least Windows 10 1903 (build 18362.1)? 
I think this is necessary, because Windows 10 1803 will not be supported anymore at the time of .NET 6.0 scheduled release (November 2021) and I think ASP.NET Core in .NET 6.0 will be able to ensure that the SDK is still based on supported Windows 10 OS in 2021.

If it's ok, I'd like to submit PR to update this with `Microsoft.VisualStudio.Component.Windows10SDK.18362` 

PS: I get this reference of this workload name from this docs: https://docs.microsoft.com/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019

**Comment by eriawan** [comment]
folks, any update on this feedback?
please review.

looking at the current CODEOWNER, I'm tagging @dotnet/aspnet-build

**Comment by eriawan** [comment]
Hmm,,, looking at the current CODEOWNERS:

https://github.com/dotnet/aspnetcore/blob/4cc933927fb668a67e1ce6f2e368edb45af164b4/.github/CODEOWNERS#L4-L7

The team name should be `dotnet/aspnet-build` instead of `aspnet/aspnet-build`.

**Comment by wtgodbe** [comment]
Thank you for catching this, I agree that it sounds like an update we should make. @dougbu do you know of any reason why w wouldn't want to update this SDK (or would want to update it to a different one)?

**Comment by dougbu** [comment]
1. @eriawan is correct we need to update the .github/CODEOWNERS file to use the correct alias for our build team
2. I'm not sure about updating the Windows SDK until _after_ Windows 1803 goes out of service. I bet we have kept the SDK version where it is to ensure we remain compatible with that OS version.

@halter73 you've been involved in our OS version discussions. Have those touched on Windows 1803❔

Or, @Tratcher, you've been looking at moving toward newer Windows releases. Have you touched on any changed Windows SDK requirements in that❔

**Comment by Tratcher** [comment]
I've only been updating our test infrastructure, that hasn't needed any SDK updates.

The Windows SDK is used for building ANCM. @jkotalik.

**Comment by jkotalik** [comment]
I think we can update it without any issues.

**Comment by dougbu** [comment]
> I think we can update it without any issues.

:ok: that' leads to a different question: _Should_ we update the Windows SDK❔ Is there an actual reason for this versus a change for change's sake❔

For example, @Pilchie is the Microsoft.VisualStudio.Component.Windows10SDK.17134 component near the end of support in Visual Studio❔ (It's still included in VS but I don't know the support policy in this area. I'm just doubting it's tied to whatever Windows version happened to be around when the SDK was first released.) If you don't know, who might❔

**Comment by Pilchie** [comment]
I'll try to find out.  Just so I understand, we need an SDK which can target back to Win7, but we're wondering what our policy should be for updating the SDK we use?

**Comment by dougbu** [comment]
It's mostly the second from my PoV. As @eriawan mentions, the Windows version released about the same time as our current SDK is ending support soon. But, I'm not sure that drives us to make any change at all.

**Comment by Pilchie** [comment]
@jeffschwMSFT - how does the runtime pick Windows SDKs to depend on.  How often does it update them?

@markwilkie - is this something that's documented in the arcade toolchain docs?

**Comment by markwilkie** [comment]
The policy on the Windows SDK has not been directly sorted AFAIK.  The closest we have is https://github.com/dotnet/arcade/blob/master/Documentation/Policy/ToolsetPolicy.md.  Historically, the windows SDK has been tied to the VC toolset....

**Comment by eriawan** [comment]
folks, I'll try to help as well :)

about this from @Pilchie :
> how does the runtime pick Windows SDKs to depend on. How often does it update them?

Looking at the current vsconfig in https://github.com/dotnet/runtime, the VS workload has used Windows 10 SDK of 18362:
https://github.com/dotnet/runtime/blob/7225baf3b4e233bf4e8cf53a5c01485beaca5773/.vsconfig#L35

```
    "Microsoft.VisualStudio.Component.Windows10SDK.18362",
```

@jkotalik 
> I think we can update it without any issues.

Yes, I have tested Windows 10 18362 SDK to build ANCM, and it builds successfully. IMHO we should not have problem with Windows 10 18362 SDK.

**Comment by eriawan** [comment]
@dougbu 

> @eriawan is correct we need to update the .github/CODEOWNERS file to use the correct alias for our build team

thanks for the confirmation!

I have submitted PR to update the team name in CODEOWNER: #29481

**Comment by eriawan** [comment]
@dougbu @Pilchie 

Pardon, have you decided to approve this? Just to recap my previous comment, the dotnet/runtime is using Windows 10 SDK 18362, so I think we should be ok to sync with dotnet/runtime as (CMIIW) aspnetcore should also comply or in sync with Windows 10 SDK used in dotnet/runtime.

https://github.com/dotnet/runtime/blob/7225baf3b4e233bf4e8cf53a5c01485beaca5773/.vsconfig#L35

**Comment by jeffschwMSFT** [comment]
We would just ask that this is fully validated as new toolsets can introduce non-obvious issues.  Adding @agocke to ensure I am not overlooking anything.

**Comment by dougbu** [comment]
@ViktorHofer is the .vsconfig file from dotnet/runtime actually used in your CI at all❔ If not, are you using whatever Windows SDK the build agents have installed❔

@eriawan note our current CI does _not_ install Visual Studio nor any VS components.

@ilyas1974 could you remind me where the BuildPool.Server.Amd64.VS2019.BT.Open and BuildPool.Server.Amd64.VS2019[.Open] VS components are listed❔

**Comment by ilyas1974** [comment]
We do not have the components listed anywhere that is "easy" to read. From our YAML file, here are the workloads that are installed. 

        Microsoft.VisualStudio.Component.FSharp.MSBuild
        Microsoft.VisualStudio.Component.NuGet.BuildTools
        Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools
        Microsoft.VisualStudio.Workload.NetCoreBuildTools
        Microsoft.VisualStudio.Workload.VCTools
        Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools
        Microsoft.VisualStudio.Workload.WebBuildTools

<from https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=%2Fdefinitions%2Fshared%2Fwindows.yaml>

**Comment by dougbu** [comment]
@ilyas1974 I don't have access to that YAML file and your list doesn't tell me whether `Microsoft.VisualStudio.Component.Windows10SDK.18362` is installed. We know `Microsoft.VisualStudio.Component.Windows10SDK.17134` is installed because our CI builds succeed.

Specifically, while `Microsoft.VisualStudio.Component.Windows10SDK` is a required part of `Microsoft.VisualStudio.Workload.VCTools`, the numbered versions are all either optional or just recommended in various workloads. Is it possible to drill a bit deeper❔ Or, do you recommend we just try it out in our pipeline❔

**Comment by ilyas1974** [comment]
I think it would be quicker to try it out, I believe we still the Windows10SDKs on these images. @ChulHul creates these base images for us through image factory - perhaps he knows for sure what components are being installed.

**Comment by dougbu** [comment]
> I think it would be quicker to try it out

Will give it a shot.

@Pilchie what are your thoughts w.r.t. `release/5.0`❔

**Comment by ViktorHofer** [comment]
> @ViktorHofer is the .vsconfig file from dotnet/runtime actually used in your CI at all❔ If not, are you using whatever Windows SDK the build agents have installed❔

Nope, not used in CI and only beneficial for devs who want to install required components. Yes, we are using the SDK version that is installed on the build agents. That hasn't been a problem before.

**Comment by eriawan** [comment]
@dougbu 

> @eriawan note our current CI does not install Visual Studio nor any VS components.

Thanks for the clarification! 👍

**Comment by dougbu** [comment]
The CI agents do **not** have this version of the Windows SDK installed. eng/common/tools.ps1 downloads RoslynTools.MSBuild and tries to use that for native builds. This didn't work in #29559 because RoslynTools.MSBuild v16.5.0-alpha doesn't include _any_ Windows SDK. I updated the branch locally to fallback to RoslynTools.MSBuild v16.8.0-preview3 (the latest) and the errors are the same.

We should not do this until and unless the CI agents are updated to include Microsoft.VisualStudio.Component.Windows10SDK.18362. Even then, this would be a breaking change for most people with a local Windows clone of this repo. Not a great idea unless the current SDK can't build our repo anymore.

Example error from #29559 (which I'm closing):
``` text
error MSB4019: The imported project "...\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "...\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```

**Comment by eriawan** [comment]
@dougbu 

Many thanks for your hard work to assess this! Ok, I think I'll wait for the CI agents to have the necessary/required components to be updated. Apologize if this feedback of mine may cause trouble for aspnet team.

Is there any plan to update the CI, especially update agents to use at least MSBuild 16.8.0? As far as I know (and I have tested this), this repo is built nicely on my machine that has Windows 10 SDK both 18362 and 19041.

I was thinking to propose 16.8.0 at least, because this [build asp.net source guide](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#on-windows) says it:

![image](https://user-images.githubusercontent.com/8773147/105684480-97cba100-5f27-11eb-8571-b7bb2072ca1f.png)

Again, many thanks for your assessment and clarifications! 👍

**Comment by dougbu** [comment]
@eriawan the VS version doesn't change the Windows SDK we require or that is installed on the CI machines. In  particular, VS 16.8.0 still supports the 17134 Windows SDK. There's no action needed here until and unless the CI machines get a new Windows SDK for other reasons.

**Comment by Pilchie** [comment]
OTOH @dougbu if this is going out of support soon, should we be talking to core-eng about the ability to get the queues updated before that happens?

**Comment by dougbu** [comment]
@Pilchie I agree we should update _if_ this SDK version were near end-of-life. But, given we're talking about a component that's available in the just-released VS 16.8.0, won't it be in support for quite a while yet❔

**Comment by eriawan** [comment]
@dougbu 
Based on this comment https://github.com/dotnet/aspnetcore/issues/22951#issuecomment-780081317 now that the CI agent has 16.8.x, could we then update this vs.json that I mentioned earlier in the beginning of this issue?

**Comment by dougbu** [comment]
> could we then update this vs.json that I mentioned earlier in the beginning of this issue?

No. VS 16.8 still offers the `Microsoft.VisualStudio.Component.Windows10SDK.17134` component and that's the one available on our CI agents.
