### ISSUE TITLE
AbortController is undefined in IE11

### ISSUE THREAD

**Issue by yugandhar02** [dotnet/aspnetcore#29424]
### Describe the bug
Although signalr has ponyfill for AbortController, its not being used in FetchHttpClient.
This leads to error in IE11 where AbortController is not supported

### To Reproduce
use fetch polyfill for IE11.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/11800332/105041646-4041b700-5a89-11eb-9cd7-018e9c0943b0.png)

**Comment by BrennanConroy** [comment]
We don't support [IE11](https://docs.microsoft.com/aspnet/core/signalr/supported-platforms?view=aspnetcore-5.0#javascript-client) and recommend users switch to Edge.

Does adding an AbortController polyfill alongside the fetch polyfill fix the issue for you? If so, that's the recommended approach.

If you're interested in contributing a simple fix for IE11 we would consider merging it.

**Comment by yugandhar02** [comment]
@BrennanConroy Its not just about IE11.
It will break in older browser which doesn't have abortController support.
I see that signalr already has ponyfill for abortController which is being used in other places e.g. longPollingTransport.
Can that be used ?

**Comment by JunTaoLuo** [comment]
Let's doc this.

**Comment by pleunv** [comment]
Also kind of surprised this suddenly made it in the last release. Would it be possible to use the ponyfill for now, as @yugandhar02 suggested? Alternatively using a polyfill like https://github.com/mo/abortcontroller-polyfill in userland works as well, but a little bit unnecessary if SignalR already has a ponyfill in place.

I understand the desire to drop IE11, but a change like this on a major .NET Core upgrade has pretty severe consequences, especially if they're not well documented (and not just here, but on the general .NET Core v5 documentation as well).

**Comment by pleunv** [comment]
I'd also like to add that the version support listed [here](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-5.0#javascript-client) is rather unsatisfactory. You can't realistically expect companies to depend on a JS library if all you officially support is the latest version across all browsers. 7-10% of our (corporate) user base is on IE11, a larger percentage of that is still on a non-chromium Edge.

**Comment by bradygaster** [comment]
As @BrennanConroy stated, we don't support IE11 and recommend customers move to Edge. Does the workaround @BrennanConroy suggested result in the app working in IE11? If so, is your concern that, with that fix it will work in IE11 but not in order-than-IE11 browsers?
