### ISSUE TITLE
dotnet.timezones.blat returns 404 - file exists

### ISSUE THREAD

**Issue by glararan** [dotnet/aspnetcore#29433]
### Describe the bug
After project update 5.0.0 to 5.0.2 and file uploads dotnet.timezones.blat starts throwing 404 not found even if file exists.

### My steps I tried
- valid SSL cert
- clear cache storage
- delete _framework & _content
- change target runtime to browser-wasm
- add `<BlazorEnableCompression>false</BlazorEnableCompression>` -> publish -> reupload
- merge published web.config (wasm) with asp.net core hosted web.config

web.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <remove fileExtension=".blat" />
      <remove fileExtension=".dat" />
      <remove fileExtension=".dll" />
      <remove fileExtension=".json" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".blat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dll" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />
    </staticContent>
    <httpCompression>
      <dynamicTypes>
        <add mimeType="application/octet-stream" enabled="true" />
        <add mimeType="application/wasm" enabled="true" />
      </dynamicTypes>
    </httpCompression>
  </system.webServer>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\app.exe" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
      <security>
        <requestFiltering allowDoubleEscaping="true"/>
      </security>
    </system.webServer>
  </location>
</configuration>
<!--ProjectGuid: 6b3cabb0-21e1-49b8-882a-181e5751a48f-->
```

### Exceptions (if any)
```
dotnet.timezones.blat:1 Failed to load resource: the server responded with a status of 404 ()
admin:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/_framework/dotnet.timezones.blat' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.
admin:1 Unknown error occurred while trying to verify integrity.
blazor.webassembly.js:1 Uncaught (in promise) TypeError: Failed to fetch
```

### Further technical details
- .NET 5.0.2

So far I believe there is an issue with IIS. However if I navigate to _framework and check MIME types - .blat is inherited = ok.

**Comment by mkArtakMSFT** [comment]
@Tratcher any thoughts regarding what may be misconfigured on the IIS?

**Comment by mkArtakMSFT** [comment]
@glararan did you try to download the file manually by typing the full URL in the browser?

**Comment by Tratcher** [comment]
@mkArtakMSFT does blazor normally have to tweak the fileExtensions?

Can anyone else repro this?

**Comment by glararan** [comment]
> @glararan did you try to download the file manually by typing the full URL in the browser?

Yes I did.

Maybe can be problem I am running hosted asp.net core 3.1.11? I am using WebAssembly for admin part (just newest browser) and server-side for IE support.

I noticed .blat files were added in .NET 5.. Do I need to add some mapping ?

**Comment by captainsafia** [comment]
@glararan Can you share a repro?

The .blat extension was added in 5.0 so you will need to add it if you are upgrading from Blazor WASM 3.2 to 5.0. If you're upgrading from 5.0 to 5.0.2 then there might be something else causing this.

**Comment by glararan** [comment]
@captainsafia I just found out some "polyfill" try project bringing .NET 5 to back to IE. So I moved server-side to .NET 5. Suprise.. problem gone. = There must be some kind of .blat extension mapping. 

Server-side 3.1 + WASM .NET 5 are incompatible as hosting model (by default) :( Maybe this should be mentioned somewhere in docs?

**Comment by flamecrow** [comment]
> @captainsafia I just found out some "polyfill" try project bringing .NET 5 to back to IE. So I moved server-side to .NET 5. Suprise.. problem gone. = There must be some kind of .blat extension mapping.
> 
> Server-side 3.1 + WASM .NET 5 are incompatible as hosting model (by default) :( Maybe this should be mentioned somewhere in docs?
> 
> However its kinda weird 5.0.0 worked for few days lol..

A blank starter client-side BlazorApp and I'm getting this 404 for dotnet.timezones.blat and icudt_EFIGS.dat... was working fine before. I can't figure this one out :(

**Comment by glararan** [comment]
@flamecrow If asp.net core hosted => make sure you are using `app.UseBlazorFrameworkFiles();` (.NET 5 for .blat, 3.1+ .dat)
If you are not using asp.net core hosted then you have probably bad web.config => missing MIME type

at least thats what I found out

**Comment by flamecrow** [comment]
> @flamecrow If asp.net core hosted => make sure you are using `app.UseBlazorFrameworkFiles();` (.NET 5 for .blat, 3.1+ .dat)
> If you are not using asp.net core hosted then you have probably bad web.config => missing MIME type
> 
> at least thats what I found out

This is the webconfig file outside the wwwroot folder when published:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <remove fileExtension=".blat" />
      <remove fileExtension=".dat" />
      <remove fileExtension=".dll" />
      <remove fileExtension=".json" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".blat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dll" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />
    </staticContent>
    <httpCompression>
      <dynamicTypes>
        <add mimeType="application/octet-stream" enabled="true" />
        <add mimeType="application/wasm" enabled="true" />
      </dynamicTypes>
    </httpCompression>
    <rewrite>
      <rules>
        <rule name="Serve subdir">
          <match url=".*" />
          <action type="Rewrite" url="wwwroot\{R:0}" />
        </rule>
        <rule name="SPA fallback routing" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
          </conditions>
          <action type="Rewrite" url="wwwroot\" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>

Anything look off?

**Comment by glararan** [comment]
@flamecrow this web.config looks like non-hosted version. Should be fine.

**Comment by captainsafia** [comment]
> A blank starter client-side BlazorApp 

@glararan Is this a new 5.0 standalone WASM app?

**Comment by glararan** [comment]
@captainsafia I believe you ment to ask @flamecrow. Based on his posted config its standalone WASM app.

My case was hosted WASM app
