### ISSUE TITLE
Unable to send the domain_hint with Blazor web assembly (using MSAL JS) 

### ISSUE THREAD

**Issue by singhnishant40** [dotnet/aspnetcore#29440]
Issue reference: https://stackoverflow.com/questions/63605653/is-there-a-way-to-supply-a-domain-hint-for-single-sign-on-using-msal-net-on-a-bl

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We plan to add documentation describing how to make customizations to the underlying MSAL.js library. You can find the pending PR at: https://github.com/dotnet/AspNetCore.Docs/pull/21236
