### ISSUE TITLE
Parameter model bind success  but  TryUpdateModelAsync  fail

### ISSUE THREAD

**Issue by John0King** [dotnet/aspnetcore#29442]
### Describe the bug
`List<string>` can be bind using  parameter binding  but not the `tryUpdateModelAsync`
### To Reproduce
```C#
 //dto and User Entity has same property name

public class UserDto
{
    //....
    public List<string> Location {get;set;} = new List<string>();
    //...
}

     [HttpPost]
        public async Task<ApiResult> Edit(int id, UserDto model) // this bind ok
        {
            var user= await _db.Users.Where(u => u.Id == id)
                .AsTracking()
                .FirstOrDefaultAsync();
            if(user == null)
            {
                return ApiResult.Fail("用户已删除");
            }
            
            try
            {
               
                await TryUpdateModelAsync(user);  // throw Unable to cast object of type'System.Collections.Generic.List`1[System.String]' to type 'System.String'.
                await _db.SaveChangesAsync();
                return ApiResult.Success();
            }
            catch(Exception e)
            {
                return ApiResult.Fail(e.Message);
            }
        }
```

### Exceptions (if any)
 throw Unable to cast object of type'System.Collections.Generic.List`1[System.String]' to type 'System.String'.

### Further technical details
- ASP.NET Core version 5.0.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@pranavkm can you please take a look at this? Thanks!

**Comment by John0King** [comment]
## more detail

I using `x-www-form-urlencoded` (eg. form post)   to submit  and I tried both `location=province&location=city&location=area`
and `location[0]=province&location[1]=city&location[2]=area`

**Comment by kishanAnem** [comment]
Hi 
I've tried to reproduce bug. It is working fine.

[repo](https://github.com/kishanAnem/issue.git)


`public class UserDto
    {
        public List<string> Location { get; set; } = new();
    }`

   ```
 public class HomeController : Controller
    {
        public async Task<IActionResult> Index(UserDto model)
        {
            var userDto = new UserDto();
            await TryUpdateModelAsync(userDto);
            return View(userDto);
        }
    }
```

**Comment by John0King** [comment]
@kishanAnem   I'll make a demo later this week ,   I think maybe it related with the two model is different or EF's `[Column(TypeName="NVarchar(MAX)")]`

**Comment by kishanAnem** [comment]
@John0King pls give repo to reproduce.

**Comment by John0King** [comment]
https://github.com/John0King/ModelBindeIssue

I try to reproduce  this,   and not I find that it is cause by `[StringLengthAttribute]` on a `ValueConverter` Property,

so , this may not be a bug  after all

**Comment by kishanAnem** [comment]
@John0King 

StringLengthAttribute : Validation attribute to assert a string property, field or parameter does not exceed a maximum length.
it is not a bug. 

[Source code](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System.ComponentModel.DataAnnotations/DataAnnotations/StringLengthAttribute.cs#L56)
