### ISSUE TITLE
[Mvc] WebApplicationFactory should implement IAsyncDisposable

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#29455]
We currently only implement Dispose and call `Wait()` on the host `StopAsync()` within `Dispose`.

Ideally we want to avoid this and simply implement IAsyncDisposable with IDisposable just being a fallback for it.

The only issue here is that currently the factory can be use as an xUnit fixture out of the box, but unfortunately I believe xUnit doesn't support IAsyncDisposable in addition to IDisposable, since they have their own interface for it (IAsyncLifetime).

This means that for using IAsyncDisposable users will either have to extend the default factory and make it implement IAsyncLifetime or create the factory within the test method and use an `await using` statement to dispose of it.

**Comment by javiercn** [comment]
This is a follow up to https://github.com/dotnet/aspnetcore/pull/29404

**Comment by MCCshreyas** [comment]
We need to implement `IAsyncDisposable` for `WebApplicationFactory<TEntryPoint>` correct?

**Comment by HEskandari** [comment]
@javiercn Any objection if I tackle this issue? Looks like there was PR submitted for it, but was abandoned after the review.

**Comment by javiercn** [comment]
@HEskandari It's fine if you take over from where the other PR left it.

Please preserve their commits so that we can reflect the contribution in any case.

**Comment by singh733** [comment]
Hi @HEskandari , I believe this issue is closed. Wondering why it is still open. Please correct me if i am wrong.

**Comment by HEskandari** [comment]
This is resolved by https://github.com/dotnet/aspnetcore/pull/32645. Closing.
