### ISSUE TITLE
Why it is needed to set normalized username/email each time user updates?

### ISSUE THREAD

**Issue by Gendolph** [dotnet/aspnetcore#29458]
I'm trying to understand workflow of ASP.NET Core Identity to correctly implement UserStore.

In `UserManager.UpdateUserAsync(TUser user)`  two methods are called:
```
await UpdateNormalizedUserNameAsync(user);
await UpdateNormalizedEmailAsync(user);
```
Method `UpdateUserAsync` is called from several places such as `AccessFailedAsync` or `RemoveFromRolesAsync`.
What purpose of normalized data update in these scenarios?

**Comment by HaoK** [comment]
Basically the usermanager is responsible for ensuring that the  email/username is normalized before updating the user in the store.  Since the fields are mutable, this is done to guarantee they are consistent correct before the user's data is saved.
