### ISSUE TITLE
partManager.ApplicationParts.Remove,Releases the current assembly related services 

### ISSUE THREAD

**Issue by tanyo520** [dotnet/aspnetcore#29450]
Through_ partManager.ApplicationParts.Remove (_ After removing the assembly, install the assembly again, and find HttpContext.RequestServices The services of application services are not released, or the previous services are used. Is there any good way to release the services of the current assembly when uninstalling
![image](https://user-images.githubusercontent.com/5094034/105157689-329f3680-5b48-11eb-853f-f3680b3262eb.png)
![image](https://user-images.githubusercontent.com/5094034/105157706-359a2700-5b48-11eb-87da-34edcd430571.png)

**Comment by javiercn** [comment]
@tanyo520 thanks for contacting us.

This is not a scenario application parts supports. All modifications to the list of application parts must happen before you configure the services for the application. If you try to change them after configuring the service collection for the application the behavior is undefined.

**Comment by tanyo520** [comment]
> @tanyo520 thanks for contacting us.
> 
> This is not a scenario application parts supports. All modifications to the list of application parts must happen before you configure the services for the application. If you try to change them after configuring the service collection for the application the behavior is undefined.

I want to realize the hot loading and unloading of plug-ins. The idea is that I use the assembly loadcontext to dynamically load the DLL. When I load and unload the DLL through the application parts, it is normal when I install it for the first time. When I install it again, I find that the MVC related services are the same as before. Do you have a good idea to solve this problem?

**Comment by tanyo520** [comment]
> @tanyo520 thanks for contacting us.
> 
> This is not a scenario application parts supports. All modifications to the list of application parts must happen before you configure the services for the application. If you try to change them after configuring the service collection for the application the behavior is undefined.

Thank you very much

**Comment by javiercn** [comment]
@tanyo520 this is not something that we support in general, but there are frameworks on top of ASP.NET Core that already do this. I would suggest you look into something like OrchardCore to deal with it.
