### ISSUE TITLE
Nested component with layout

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/aspnetcore#29453]
the @layout directive is used to nested pages layout. but this is not support for nested component layout.
for ex
Component1 :

```
<div>component 1 header</div>
@ChildComponent
<div>Component 1 footer</div>
@code {

[Parameter]
public Renderfragment ChildComponent{get;set;}

}
```

and Component2 :

```
@layout Component1
<div>component 2 content</div>
```

and call component2 on index.razor page

`<Component2 />`

we must see

component 1 header
component 2 content
component 1 footer

this feature is not present yet due to this [discussion](https://github.com/dotnet/aspnetcore/issues/28915) and [this](https://github.com/dotnet/AspNetCore.Docs/issues/21143)

Thx
BR

**Comment by javiercn** [comment]
@ehsangfl thanks for contacting us.

Can you clarify what are you exactly asking for? You can have nested layouts and the only requirement is that your `Layouts` extend `LayoutBase`

**Comment by ehsangfl** [comment]
as described [hear](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0#specify-a-layout-in-a-component), this is work, only for components that has @page directive and access it throw internal navigation system.
if you have BaseLayoutComponent that extended by LayoutBase, any "pages" can implement its layout, not any components.
I ask it [before](https://github.com/dotnet/aspnetcore/issues/28915) and you can read @mkArtakMSFT response.

I want to have custom control (not page), that implement its base component layout and it is not possible now.
the structure is

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ehsangfl.
We plan to improve documentation on layouts in components and how to work with them. We will track that work as part of the [original issue you had created](https://github.com/dotnet/aspnetcore/issues/28915).

We do not plan to add any new features in this area.

**Comment by ehsangfl** [comment]
document was updated on [this](https://github.com/dotnet/AspNetCore.Docs/issues/21143).
I create this for **new feature** request 
thx
