### ISSUE TITLE
Is there anything like view location expander for Razor Pages just like in MVC?

### ISSUE THREAD

**Issue by iyilm4z** [dotnet/aspnetcore#29463]
I have a Razor Pages web app and Razor Class Libraries as modules like below.

App.WebApp
App.Module1
.
.
App.ModuleN

In web app, i would like to store pages/areas as usual. In modules i would like to store pages/areas under Web folder of each modules.

Required paths to be working:

App.Web>**Pages**>WebAppFeature1>..
App.Web>**Areas**>WebAppFeature2>**Pages**>..
App.Module1>**Web**>**Pages**>Module1Feature1>..
App.Module1>**Web**>**Areas**>Module1Feature2>**Pages**>..
.
.
App.ModuleN>**Web**>**Pages**>ModuleNFeature1>..
App.ModuleN>**Web**>**Areas**>ModuleNFeature2>**Pages**>..

I tried setting **RootPath** prop of razor pages options to “**/Web**” but it breaks default path rule for web app and also it doesn't work with areas as i required. 

It's so easy to do it with code below in MVC .

 ```csharp
public class MyViewLocationExpander : IViewLocationExpander
{
        public void PopulateValues(ViewLocationExpanderContext context)
        {
        }

        public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
        {
            return new[]
            {
                "/Web/Views/{1}/{0}.cshtml",
                "/Web/Views/Shared/{0}.cshtml"
            }.Concat(viewLocations);
        }
}
 ```

**Comment by pranavkm** [comment]
@iyilm4z unfortunately this is not a feature MVC supports. You might be able to use [route conventions](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-5.0#page-route-action-conventions) to configure routes for Razor Pages in areas (using https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.applicationmodels.pageconventioncollection.addareapageroutemodelconvention), but it doesn't really help with your folder organizational asks.

**Comment by iyilm4z** [comment]
Hi @pranavkm, thanks for your answer. Well.. it looks like RazorPages is not as flexible as MVC yet. What do you think of making this requirement tagging with feature request/discussable?  Doesn’t make sense?

**Comment by pranavkm** [comment]
@iyilm4z we've had this feature request come up occasionally (https://github.com/dotnet/aspnetcore/issues/6337). We've found that cost of implementing support for a customizable area root for Razor Pages is is not comparable to the asks we get for it. 

While we could park this as an enhancement / backlog item, our experience with this feature request indicates it's very likely to be closed with not enough community interest for us take it on.

**Comment by iyilm4z** [comment]
@pranavkm i got it, thanks.
