### ISSUE TITLE
WebApplicationFactory does not work from .NET Framework test assembly

### ISSUE THREAD

**Issue by kjetilhamre** [dotnet/aspnetcore#29469]
Hi. I have tried to understand this comment, but cannot seem to quite understand how I can do this: 

"Thanks for reaching out.
You need to reference a type on the entry point assembly of the app as the error message state. We use TStartup by convention, but you can use Program. We essentially need to know the assembly that contains the CreateHostBuilder method."

_Originally posted by @javiercn in https://github.com/dotnet/aspnetcore/issues/8210#issuecomment-470127659_

**Comment by kjetilhamre** [comment]
My Startup looks like this:
```
[assembly: OwinStartup(typeof(FDV.Web2.Startup))]

namespace FDV.Web2
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
```

**Comment by Tratcher** [comment]
WebApplicationFactory is for ASP.NET Core projects. That startup is for a [Microsoft.Owin](https://github.com/aspnet/aspnetkatana) project.

There is a lower level TestServer you can use, but no WebApplicationFactory equivalent.
