### ISSUE TITLE
Restore Microsoft.AspNetCore.Components.Web.JS.npmproj,Npm.Common.targets (40,5): error, jsinterop-3.0.0-xxx.tgz: request failed 404 Not Found

### ISSUE THREAD

**Issue by kssoftwangwg** [dotnet/aspnetcore#29464]
### Describe the bug
aspnetcore :  exec .\restore.cmd,  restore src\Components\Web.JS\Microsoft.AspNetCore.Components.Web.JS.npmproj :!!!!!! https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/-/@dotnet/jsinterop-3.0.0-preview9.19415.3.tgz: Request
failed \"404 Not Found\"".  _**Please help me solve this problem,Thank very much~~**_
![图片](https://user-images.githubusercontent.com/21151911/105184653-8d498a00-5b6a-11eb-873e-96cd983b5bb7.png)

global.json:
```json
{
  "sdk": {
    "version": "3.1.405"
  },
  "tools": {
    "dotnet": "3.1.405",
    "runtimes": {
      "dotnet/x64": [
        "$(MicrosoftNETCoreAppInternalPackageVersion)"
      ],
      "dotnet/x86": [
        "$(MicrosoftNETCoreAppInternalPackageVersion)"
      ]
    },
    "Git": "2.22.0",
    "jdk": "11.0.3",
    "vs": {
      "version": "16.8",
      "components": [
        "Microsoft.VisualStudio.Component.VC.ATL",
        "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
        "Microsoft.VisualStudio.Component.Windows10SDK.18362"
      ]
    }
  },
  "msbuild-sdks": {       // Could it be a setting problem here? If so, what should be changed?
    "Yarn.MSBuild": "1.15.2",
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.20213.4",
    "Microsoft.DotNet.Helix.Sdk": "2.0.0-beta.20213.4"
  }
}
```

### Exceptions (if any)

Yarn version: 
  1.15.2

Node version: 
  14.15.4

Platform: 
  win32 x64

Trace: 
  Error: https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/-/@dotnet/jsinterop-3.0.0-preview9.19415.3.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (C:\Users\Administrator\.nuget\packages\yarn.msbuild\1.15.2\dist\lib\cli.js:696:66)
      at new ResponseError (C:\Users\Administrator\.nuget\packages\yarn.msbuild\1.15.2\dist\lib\cli.js:802:124)
      at Request.<anonymous> (C:\Users\Administrator\.nuget\packages\yarn.msbuild\1.15.2\dist\lib\cli.js:66128:16)
      at Request.emit (events.js:315:20)
      at Request.module.exports.Request.onRequestResponse (C:\Users\Administrator\.nuget\packages\yarn.msbuild\1.15.2\dist\lib\cli.js:130418:10)
      at ClientRequest.emit (events.js:315:20)
      at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
      at TLSSocket.socketOnData (_http_client.js:509:22)
      at TLSSocket.emit (events.js:315:20)

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@kssoftwangwg thanks for contacting us.

Seems like yarn might be failing to resolve some packages in your environment, not sure why?

**Comment by kssoftwangwg** [comment]
@javiercn ，thanks Reply to a message.
It doesn't seem to be a problem with resolving packages, More like by resolve references , can can't download the jsinterop-3.0.0-preview9.19415.3.tgz file on https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/ . But this is not a network problem, because the http request (jsinterop-3.0.0-preview9.19415.3.tgz) returned a 404 status code. Are you sure that https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/ can be accessed from outside Microsoft?

**Comment by kssoftwangwg** [comment]
@javiercn ，thanks Reply to a message.
It doesn't seem to be a problem with resolving packages, More like by resolve references , can't download the jsinterop-3.0.0-preview9.19415.3.tgz file on  https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/  . But this is not a network problem, because the http request (jsinterop-3.0.0-preview9.19415.3.tgz) returned a 404 status code. Are you sure that https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/ can be accessed from outside Microsoft?

**Comment by kssoftwangwg** [comment]
@javiercn ，thanks Reply to a message.
It doesn't seem to be a problem with resolving packages, More like by resolve references , can't download the jsinterop-3.0.0-preview9.19415.3.tgz file on https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/ . But this is not a network problem, because the http request (jsinterop-3.0.0-preview9.19415.3.tgz) returned a 404 status code. Are you sure that https://dotnet.myget.org/F/aspnetcore-dev/npm/@dotnet/jsinterop/ can be accessed from outside Microsoft? Or request file Does not exist?
![image](https://user-images.githubusercontent.com/21151911/105269664-5fe2f780-5bcf-11eb-8c66-79a654a2283f.png)

**Comment by pranavkm** [comment]
Looks like @wtgodbe fixed this fairly recently: https://github.com/dotnet/aspnetcore/commit/c5f9eaf1e89f4b51c8b7a7d209f13c23765b49b0. Could you try grabbing the latest 3.1 (if that's what you're trying to build) and retry?

**Comment by kssoftwangwg** [comment]
@pranavkm, Thanks ! Finally succeeded ~~~，I am very excited thanks.
