### ISSUE TITLE
Default branch has been renamed to main

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#29475]
On Thursday, 21 January 2021 we're going to rename the default branch in this repository to `main`. For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172). Expect the process to begin after 5PM Pacific.

**Comment by dougbu** [comment]
Some cleanup remains but the work is mostly done. Will leave this issue open even after absolutely everything is complete to make the change _very_ visible. See also the following on the repo home page
![image](https://user-images.githubusercontent.com/6431421/105438083-2fbf4700-5c17-11eb-87ec-904a35e55df6.png)

**Comment by dougbu** [comment]
The GitHub instructions for updating your local environments seems to be incomplete
1. The commands didn’t update `.git/refs/remotes/origin/HEAD` at least for me. I used `git remote set-head origin --auto` to avoid errors when using `git prune` and similar commands. According to online chatter, other commands also clear things up – including deleting the file.
2. The commands don’t do anything for your local branches that target ‘master’. Recommend executing `git branch -- set-upstream-to origin/main {branch name}` for each such branch. The following PowerShell snippet should cover everything:
    ``` powershell
    git branch -vv |
        Where-Object { $_ -match '^[*+]? *([^ ]+) .*(origin/)?master: gone' } |
        ForEach-Object { git branch -- set-upstream-to origin/main $MATCHES[1] }
    ```

**Comment by mkArtakMSFT** [comment]
@dougbu should this be closed?

**Comment by dougbu** [comment]
Not yet @mkArtakMSFT The recommended process is to leave the pinned issue about the change open for 2 weeks after.
