### ISSUE TITLE
Improvement To Render Fragment

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#29479]
Here is a case where using render fragments to improve performance for web assembly does not work.
The case is if you have a base class with a property like TitleTemplate.

If creating a protected method to place it somewhere, currently does not work.

What I propose is something like this:

you have a base class with something like this

```
[Parameter]
    public RenderFragment? TitleTemplate { get; set; }
    protected RenderFragment DisplayTitle = __builder =>
    {
        <div>
            @TitleTemplate
        </div>
       
    };
```

Currently, when I try this, it gives a compile error saying "Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0236	A field initializer cannot reference the non-static field, method, or property 'FirstBaseComponent.TitleTemplate'	FlexiblePopExperiments	C:\VS\Net5\BlazorSimpleExperiments\FlexiblePopExperiments\Shared\FirstBaseComponent.razor	9	Active"

However, if using from the class, then it should work anyways.  This will open the way to have some shared fragments to use if you have a base class with some properties but sub classes need to place them in different places.  If using extra components, then you have performance problems with web assembly.  This would be another tool to still be able to have shared code from a base library but not have the performance penalty of having to break out into more components like the title component.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

That is because the method is internally compiled as static, you might be able to achieve this by doing something like

```csharp
protected RenderFragment<YourComponent> DisplayTitle = instance => __builder =>
{
        <div>
            @TitleTemplate(instance)
        </div>
}
```

**Comment by musictopia2** [comment]
Do you think there is the possibility of not having it compiled as static if the static keyword is not used.
In all other cases in C#, a method is only static if a person specified static.

**Comment by stefanloerwald** [comment]
The initializer or a field is implicitly static, that means the following part is treated as static by the language:

```cs
__builder =>
{
    <div>
        @TitleTemplate
    </div>
};
```

You are accessing a field, which isn't valid in a static context. The easiest way to change that is to make it a property:
```cs
protected RenderFragment DisplayTitle => __builder =>
{
    <div>
        @TitleTemplate
    </div>   
};
```

This is the difference

```diff
+protected RenderFragment DisplayTitle => __builder =>
-protected RenderFragment DisplayTitle = __builder =>
```

**Comment by musictopia2** [comment]
Do you think the docs can be updated to show this.  Because I went off the docs when doing the renderfragments.  They never showed the situation if you wanted to access properties from the component class.

**Comment by javiercn** [comment]
@guardrex can you add a note to the docs about this?

**Comment by guardrex** [comment]
I'll get it a shot 🎯. I'll open a docs issue with P1 priority.
