### ISSUE TITLE
SuppressImplicitRequiredAttributeForNonNullableReferenceTypes Is Not Obeyed

### ISSUE THREAD

**Issue by terryaney** [dotnet/aspnetcore#29472]
.NET 5, Razor Pages Project

I do not want the required attribute to run automatically for non-nullable types and I thought I could use SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true to disable it.

Startup.cs
```
services.AddMvc(opt =>
{
	opt.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true;
});
```

Model
```
public record Command : IRequest
{
	public int Id { get; init; }
	public string LastName { get; init; }
	public string FirstMidName { get; init; }
	public DateTime EnrollmentDate { get; init; }
}
```

On POST, ModelState contains an error for EnrollmentDate (from `new System.Collections.Generic.ICollectionDebugView<Microsoft.AspNetCore.Mvc.ModelBinding.ModelError>((new System.Linq.SystemCore_EnumerableDebugView<Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateEntry>(context.ModelState.Values).Items[3]).Errors).Items[0]` in QuickWatch)

"The value '' is invalid."

![image](https://user-images.githubusercontent.com/6237247/105231230-2c02c600-5b2c-11eb-9f68-dbd173e1d6e6.png)

Am I misunderstanding the option or should this validation not be occurring?

**Comment by pranavkm** [comment]
> Am I misunderstanding the option or should this validation not be occurring?

The error you're seeing is a result of MVC failing to parse the string value (empty string) as a DateTime value. The option you configured doesn't influence that and there isn't an option that allows ignoring empty strings or parse errors.
