### ISSUE TITLE
[.NET 6] [Source Compat Failure] CarChecker app doesn't build with .net5 and .net6 SDK

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/aspnetcore#29483]
**Application Name:**  CarChecker
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-alpha.1.21070.8
**DevDiv bug: ** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1268204](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1268204)

**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-alpha.1.21070.8 : Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 5.0.102: Fail
3). Windows 10 RS5 X64 + .NET Core SDK build  3.1.405: Pass

**Repro steps:**
1) Clone from https://github.com/SteveSandersonMS/CarChecker
2) dotnet build

**Expected Result:**
Build succeeded

**Actual Result:**
C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21070.8\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(208,5): error : The static web asset 'C:\Users\valtunc\Desktop\CarChecker-master\CarChecker-master\Client\wwwroot\favicon.ico' has a conflicting web root path '/wwwroot/favicon.ico' with the project file 'wwwroot\favicon.ico'. [C:\Users\valtunc\Desktop\CarChecker-master\CarChecker-master\Server\CarChecker.Server.csproj]

@dotnet-actwx-bot @dotnet/compat

**Comment by captainsafia** [comment]
@SteveSandersonMS Any chance you can take a look at this?

@javiercn recommends removing the favicon assets from wwwroot to resolve the issue.

**Comment by SteveSandersonMS** [comment]
@javiercn Could you clarify the recommendation - isn't it legit to have a `favicon.ico` in `wwwroot`?

**Comment by javiercn** [comment]
@SteveSandersonMS it is legit, but the one in the host conflicts with the one in the blazor webassembly app, in our hosted webassembly template we removed the one from the host.

**Comment by jiangzeng01** [comment]
Verified, removed the file wwwroot\favicon.ico from our source, it works fine now when retargeting to 5 and 6.
