### ISSUE TITLE
Blazor WASM build error: GenerateBundle, must specify host binary

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29488]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-WASM-build-error:-GenerateBundle/1314188)._

---
[severity:I'm unable to use this version]
Blazor WASM self-contained build targeting . NET5.0? The msg, "GenerateBundle, must specify host binary". Only happens with PublishSingleFile option, all other flags including trimming ones, do not seem to have any effect on if this error appears or not. Results in the project not being able to be built.

Project File:
  
    net5.0  
    x64
    win-x64
    true
    Exe
    true
    link
    true 
    embedded
    true
  

    
    
    
  

dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---
#### Feedback Bot on 1/19/2021, 07:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Single-file publishing is not supported for Blazor WebAssembly projects.

**Comment by CKeeneARC** [comment]
So:
.NET core apps can be single file published.
Blazor WebAssembly, although based on .NET core, cannot be single file published.

I must have misunderstood that "Standalone != Single-file EXE".

OK, so I guess WASM hosted is my next best option. I'd recommend making this a little more explicit in the docs though. Perhaps make the error message a bit clearer would not hurt either.

**Comment by asheroto** [comment]
For anyone working on Linux:

```
apt update
apt install libtinfo5 libkrb5-dev zlib1g-dev -y
wget dot.net/v1/dotnet-install.sh -O dotnet.sh
bash dotnet.sh -c 5.0
```
