### ISSUE TITLE
Chrome on Android does not keep screen on while playing html5 video

### ISSUE THREAD

**Issue by marufbd** [dotnet/aspnetcore#29491]
### Blazor page rendered video tag behaviour

If the video tag is dynamically created and appended to DOM with javascript, Chrome Android keeps the screen on for mobile device.
However if the same video tag is rendered inside a Blazor page Chrome does not keep the screen on (display times out) even though Android notification shows that chrome tab is playing media. I wonder what Blazor is doing differently to make chrome behave like that.

### To Reproduce

Reproduce is easy, just create a Blazor webassembly for ASP .NET 5 project and change `index.razor` to add a video tag:
```
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<!--This is the newly added video tag -->
<video width="100%" 
       controls       
       crossorigin
       playsinline
       data-poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg"
       id="player">     
    <source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4"
            type="video/mp4"
            size="576" />         
    <a href="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" download>Download</a>
</video>

```

Launch the app to listen to your local ipaddress so that you can browse from your mobile.
In my case app is running on http://192.168.1.13:5001.
I made android display settings to timeout after 15 seconds.
I browsed the page and played the video, after 15 seconds phone screen turns off.

Now if I remove the video tag from index.razor and instead add a little javascript snippet inside `wwwroot/index.html ` just before closing body tag like this:
```
<body>
    <div id="video_container" class="container">        
    </div>

    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>

    <script src="js/hls.js/hls.min.js"></script>
    <script type="text/javascript">
        var videocontainer = document.getelementbyid("video_container");
	    var video = document.createelement("video");
	    video.id = "video";
	    video.setattribute("muted", "");
	    video.setattribute("autoplay", "");
        video.setattribute("controls", "");
        video.setattribute("src", "https://cdn.plyr.io/static/demo/view_from_a_blue_moon_trailer-576p.mp4");
	    videocontainer.appendchild(video);
    </script>
</body>
```

Now when i play the video from chrome on Androin mobile the screen never goes to sleep.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
