### ISSUE TITLE
Css Isolation Not Working With Inheritance

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#29493]
Here is my repository to show the problem.
https://github.com/musictopia2/CssIsolationNotWorking 

What happens is the following:
If I have a base class that has css isolation that I want to expose to sub classes; then when the sub class tries to use it, ignores the css class.  I hope there is a way to fix it.   Because there are some cases where there may be css classes they want to expose to sub classes.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

CSS isolation is a compile time mechanism based on the file and doesn't know anything about inheritance, so this is not going to work.

The best way to deal with this is to define a deterministic css scope and use that across the types in the hierarchy. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#customize-scope-identifier-format) for details.

```xml
<ItemGroup>
    <None Update="MyComponent.razor.css" CssScope="my-custom-scope-identifier" />
</ItemGroup>
```

**Comment by musictopia2** [comment]
I read the details.  However, still does not say how that would solve the problem.   It seems all this does is allows the name to be different for a css file.  Is there any example of how by using a scope identifier then it can be used outside the current component.  I do need a way to share css that is not quite limited to just the component but still in a class library so a person using it does not have to have extra code to reference the css file.

**Comment by javiercn** [comment]
@musictopia2 Let me clarify.

The way I'm suggesting you do this is to force all components on a hierarchy to share the same scope identifier. This can be achieved by adding a razor.css class alongside each component and forcing the system to use the same scope identifier for all files in your component hierarchy.

CSS isolation is a file based mechanism not a class based mechanism so what we provide is the ability to create an isolated scope "per razor file" not per class hierarchy. In the same way that scoped CSS is targeted at razor files and doesn't apply to components defined in C#.

**Comment by musictopia2** [comment]
I updated my repository here https://github.com/musictopia2/CssIsolationNotWorking with the changes and it still did not work.
Would like to know what would have been required to make it work where it can use the css from another css file but not having to have extra code when the consumer uses the library.

**Comment by javiercn** [comment]
@musictopia2 You need to apply the the same scope to both components (.

```xml
  <ItemGroup>
    <None Update="Shared\SampleComponent.razor.css" CssScope="custom-scope" />
     <None Update="Shared\SampleComponent.razor.css" CssScope="custom-scope" />
  </ItemGroup>
```

Consumers of your library that extend your component also need to do the same
```xml
  <ItemGroup>
     <None Update="Shared\ConsumerComponent.razor.css" CssScope="custom-scope" />
  </ItemGroup>
```

> Would like to know what would have been required to make it work where it can use the css from another css file but not having to have extra code when the consumer uses the library.

I'm not entirely sure of what are you trying to achieve here.

If you want derived components to override the markup from the parent then i'm not sure why it's important to preserve the styles, but the above solution should work.

if you somehow want to compose the markup across different classes on the type hierachy, I don't know how that would work, and it would break the moment you have more than one component inheriting from the same base component and providing their own rules (since they all now would share the same scope).

The scoped css mechanism we provide is file based and a compile time step. The Razor compiler doesn't know anything about the type hierarchy when applying css scopes nor stores that information anywhere for consumption at runtime. Scoped CSS is purely a rewrite step as part of compilation that adds the value provided or generated to all the HTML elements in the file.

If you want to make it easy for consumers to rely on the scope provided by the parent component, then you can define a deterministic value (as described above) and add a property/static field with that value that derived components can use when defining their markup to access styles "from their parent"

**Comment by musictopia2** [comment]
What I was trying to achieve is something like this.

The base component has all the default styles. 
Then the sub classes use those css classes.  They would not override.  The base component is only helpers for sub components to use.

**Comment by musictopia2** [comment]
I have one question.  Is customscope a css file?  Where would that be placed.  I even tried something like this
<ItemGroup>
    <None Update="Shared\SampleComponent.razor.css" CssScope="Shared\BaseComponent.razor.css" />
    <None Update="Shared\BaseComponent.razor.css" CssScope="Shared\BaseComponent.razor.css" />
  </ItemGroup>

Even that did not work.  For the case I would use it, the sub classes would be in the same library as the main class.

**Comment by javiercn** [comment]
> I have one question. Is customscope a css file? Where would that be placed. I even tried something like this

No, it's the value for the actual scope that will be used, so if you choose `hello-world` your html will have `<a hello-world>...` on it, for example.

Assuming you want the styles to be implicit on the derived components (meaning they use the same scope as the parent in their markup) you can do what I suggested (add a derived.razor.css) file and apply it to the derived component (derived.razor) using the same cssscope as defined above.

**Comment by musictopia2** [comment]
I tried using this
<ItemGroup>
    <None Update="Shared\SampleComponent.razor.css" CssScope="Custom.css" />
    <None Update="Shared\BaseComponent.razor.css" CssScope="Custom.css" />
  </ItemGroup>

and tried with the .css and without the extenion and still did not work.

I tried placing that file in the same folder as the component, the wwwroot and even in the root folder of the project and still won't work.  I wish there was an example of it working.  So far, this part does not even seem to work.

**Comment by javiercn** [comment]
@musictopia2 here is a working sample. https://github.com/javiercn/ScopedCssCustomScopeSample

@guardrex can we get this added to the docs about css isolation?

**Comment by musictopia2** [comment]
Am i correct that the name always have to say custom-scope?

Because I recreated a sample to duplicate the functions.  Found out that somehow if I use any other name, does not work.
However, if using the name, then it works even if not inheriting from the class.  This can be very good.  I just hope it still just works when the consumer uses the library that uses it.

**Comment by javiercn** [comment]
No, the name can be whatever you want.

Make sure you rebuild, just in case there is any issue with the build incrementalism.

**Comment by musictopia2** [comment]
Just found out though that if i had this in a class library and consume it, does not work though.  Are there any plans to change it so its possible to somehow make it self contained even though the library may have to do extra steps like the javascript isolation.  The javascript isolation worked perfectly so the library author does the linking and just works when the consumer uses the library that does the javascript.

**Comment by musictopia2** [comment]
A suggestion I have now that hopefully is easy enough is if the library author specifies a name for linking for scoped css and the consumer uses the same name, then can use that css class.

**Comment by javiercn** [comment]
@musictopia2 I'm not sure what you did, but it shouldn't matter whether it is on a class library or not.

> A suggestion I have now that hopefully is easy enough is if the library author specifies a name for linking for scoped css and the consumer uses the same name, then can use that css class.

I don't understand what you mean by this, if you mean the `Link` attribute, that's not something we look at. If you want to do this on a package without consumers having to do anything, you can write a target on your nuget package that applies a given css scope based on whatever convention you want (as long as is file based).

For example you can have NavMenu.razor with a scope "hello-world" and for any file that matches the suffix *.NavMenu.razor apply the same "hello-world" scope.

If you want to know the details of how this work, you can read up more [here](https://github.com/dotnet/aspnetcore/blob/master/src/Razor/Microsoft.NET.Sdk.Razor/src/build/netstandard2.0/Microsoft.NET.Sdk.Razor.ScopedCss.targets)

**Comment by musictopia2** [comment]
How does it work if the library is in the same solution as the project.  I tried it with a class library and it did not work at all.
Or does the package have to be on nuget first?  Because I would want to test it before posting to nuget.  Good news is I got it working on normal projects when its not a class library.

**Comment by javiercn** [comment]
On a class library works in the same way, you have a file "Base.razor", you add a "Base.razor.css" file and you add an itemgroup in that project as showed above.

```xml
  <ItemGroup>
     <None Update="Base.razor.css" CssScope="hello-world" />
  </ItemGroup>
```

then you do the same thing in the project consuming your library. You have a file "Derived.razor", you add a "Derived.razor.css" file and you add an itemgroup in that project

```xml
  <ItemGroup>
     <None Update="Derived.razor.css" CssScope="hello-world" />
  </ItemGroup>
```

there is nothing different as if it were on the same project. The consumer only needs to know the value of the scope that the base class uses and how to force the scope to be used for a given file, which is done how I mentioned.

**Comment by musictopia2** [comment]
The strange thing is when I did it that way, it actually failed.  Would you like me to post a repository to show it failing?
