### ISSUE TITLE
Input element is not focused when calling FocusAsync in wasm application - Browsers Url Tab only remained focused

### ISSUE THREAD

**Issue by renjithsingh-rajendran123** [dotnet/aspnetcore#29490]
I have an issue in which the Input element is not focused at initial rendering when calling FocusAsync. Always the browser's url tab is getting focused on initial rendering.

**Note :** This works fine in Server app(input element focused properly). Only in wasm i am getting this issue.

Please refer the code which i have used 

`@page "/"

<input type="text" @ref="myref" />

@code {

    private ElementReference myref;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await myref.FocusAsync();
        }
    }
}`

**Sample demo :** https://github.com/renjithsingh-rajendran123/Input-element-not-focused

**Screenshot**
![image](https://user-images.githubusercontent.com/40191389/105350705-8e81c200-5c11-11eb-855d-e515e1b6e581.png)

**Comment by pranavkm** [comment]
I tried your app and was unable to reproduce the problem, the input field appears to be correctly focused. Perhaps you have an extension that auto-focuses on the address bar? Does this consistently reproduce on all browsers?
