### ISSUE TITLE
Can't debug ASP.NET Core hosted Blazor WebAssembly app under windows authentication

### ISSUE THREAD

**Issue by bryp** [dotnet/aspnetcore#29504]
Hi folks, I am unable to debug an ASP.NET Core hosted Blazor WebAssembly app.  The server project uses windows authentication.  Steps to reproduce are simple and listed below.  

**Create a new ASP.NET Core hosted Blazor WebAssembly app.**
![image](https://user-images.githubusercontent.com/141313/105393190-ad686000-5be1-11eb-8bf3-628f5e0c938f.png)

**Enable Windows Authentication on the Server project.**
![image](https://user-images.githubusercontent.com/141313/105393351-d852b400-5be1-11eb-8054-4efff012d9c4.png)

**Press F5 to debug.  My web browser is set to Chrome.  Receive the following error message.**
![image](https://user-images.githubusercontent.com/141313/105393390-e3a5df80-5be1-11eb-8520-fbbf1929a4d8.png)

**About Visual Studio**
![image](https://user-images.githubusercontent.com/141313/105393517-0b954300-5be2-11eb-8657-cfa61cd410b7.png)

**Attached please find visualstudio-js-debugger.txt.**
[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/5851270/visualstudio-js-debugger.txt)

**Comment by javiercn** [comment]
@bryp thanks for contacting us.

@captainsafia do you know what's going on here? (I believe i've seen this reported in the past). Feel free to close it if there is an existing issue for it or a known answer.

**Comment by bryp** [comment]
Next sprint planning?  FWIW - this one is blocking Blazor Wasm adoption at my company.  Hard to believe one can't be able to debug under windows authentication, can someone help me to figure out a work around?

**Comment by javiercn** [comment]
@bryp this is our standard process for dealing with issues.

I've dug out the issue tracking improvements for Blazor Webassembly debugging https://github.com/dotnet/aspnetcore/issues/22589, there's a more general issue https://github.com/dotnet/aspnetcore/issues/27301 and this is a known issue in 5.0

See [here](https://github.com/dotnet/aspnetcore/issues/27437) for details. The issue mentions a workaround, but I don't seem to be able to find it by skimming the docs.

I understand that this might not be what you want to hear, I can only suggest you switch to a different auth scheme (one of the ones we support out of the box) or replace/turn-off windows auth when you want to debug the application.

Also, as a side note, we don't recommend using Windows Auth with single page applications unless you take appropriate steps to further protect your app against CSRF attacks

**Comment by javiercn** [comment]
@captainsafia if you know a workaround for this, feel free to comment/point to the docs.

I'm closing this issue since it's a duplicate of #27301

**Comment by bryp** [comment]
@javiercn This is certainly disappointing.  To be clear, you do support Windows Auth out of the box.  You just don't support **debugging** Windows Auth out of the box for Wasm, which makes this issue all the more strange.  Also, as a side note, CSRF attacks have nothing to do with Windows Auth so CSRF protection applies to all Auth schemes and of course is good practice.

**Comment by captainsafia** [comment]
> To be clear, you do support Windows Auth out of the box. You just don't support debugging Windows Auth out of the box for Wasm, which makes this issue all the more strange

This is correct. The implementation for debugging .NET on WASM is a little bit different than .NET on the Server which is why this issue presents itself here.

@bryp If you're up for it, you can try manually launching the debug proxy to see if that resolves the issue. To do that, you will need to:

1. Find the location of the `BrowserDebugHost.dll` assembly in the `Microsoft.AspNetCore.Components.WebAssembly.DevServer` package.
2. Launch the debugging proxy using `dotnet BrowserDebugHost.dll`.
3. Copy the address the server from #2 is listening on.
4. Modify the `launchSettings.json` file of your and update the `inspectUri` to the following: 

```
"inspectUri": "ws://127.0.0.1:{portNumberFromStep2}/ws-proxy?browser={browserInspectUri}"
```

5. Start debugging in VS/VS Code.
