### ISSUE TITLE
[SignalR] Unable to put correct timeout

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#29519]
Hello guys, i have a signalr server and a blazor server side app which connect to this server.

Some of my method can be really long and wait for result.

I try to put timeout of 30 minutes but nothing i tried work
- my signalr server : its a local  .NET 5.0 console app with this configuration
````
services.AddSignalR(o =>
            {
                o.EnableDetailedErrors = true;
                o.MaximumReceiveMessageSize = null; // bytes
                o.HandshakeTimeout = TimeSpan.FromSeconds(1800);
                o.ClientTimeoutInterval = TimeSpan.FromSeconds(1800);
                o.KeepAliveInterval = TimeSpan.FromSeconds(1800);
            });
````
- signalr client : manage in javascript, on this way
````
this.connection = new signalR.HubConnectionBuilder()
                                                .withUrl(hub)
                                                .withAutomaticReconnect()
                                                .build();

                    await this.connection.start();

                    this.connection.serverTimeoutInMilliseconds = 1800000;

getDataVitale: async function (method, pLpsNumInstance, pFiness,  pAction, pPathTmp, pWithIns, pNom, pPrenom, pDateNaiss, pRang) {
                    return await this.connection.invoke(method, pLpsNumInstance, pFiness, pAction, pPathTmp, pWithIns, pNom, pPrenom, pDateNaiss, pRang);
                },

````

with the configuration, it seem the maximum i can reach it 60 seconds, after i have this js exception

disconnected with error 'Error: Server timeout elapsed without receiving a message from the server

I don't understand what i missed ? 

thanks for your help

**Comment by BrennanConroy** [comment]
Set the `serverTimeoutInMilliseconds` before calling `connection.start()`.

**Comment by julienGrd** [comment]
@BrennanConroy it was done but same result. 

Interesting fact : my app work as well as server mode and web assembly mode. The signalR js client is the same in the two mode.

But i have this error only in server mode, in web asembly it seem working well (i put a breakpoint on my signalr server and the client seem to wait without problem or closed connection).

i have also strange error. For example the first error (after the 60 second) is "a task was cancelled". But when the service is finish i have another error (which crash my app) : 
Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.EndInvokeJSFromDotNet(Int64 asyncCall, Boolean succeeded, String arguments)

after the circuit is disconnected

I don't understand this crash because when the service return data before it was closed, it work perfectly, so i don't know why the exception speak about json.

I begin to think the problem is not at the level of my signalr client but on the signalr connection which manage the server mode of blazor. 

What di you think about that ?

thanks !

**Comment by julienGrd** [comment]
I finally was able to solve my problem

For those who have the same kind of problem, its actually not related to my signalr connection (like i was thinking) but to the JsRuntime. Indeed, this last one have a timeout

as described here  https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.jsruntime.invokeasync?view=aspnetcore-5.0

InvokeAsync<TValue>(String, Object[])
Invokes the specified JavaScript function asynchronously.
JSRuntime will apply timeouts to this operation based on the value configured in DefaultAsyncTimeout. To dispatch a call with a different, or no timeout, consider using InvokeAsync<TValue>(String, CancellationToken, Object[]).

So to call Js without timeout, give a new CancellationToken to InvokeAsync and it will remove the timeout

hope it helps
