### ISSUE TITLE
[Feature] Ability to have a Guest Login on the login page as default.

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#29522]
### Is your feature request related to a problem? Please describe.
A user to any site should be allowed to checkin as a guest user.

### Describe the solution you'd like
When a user gets onto a site with asp.net identity installed they should be allow to access the site as a "Guest User" while ClaimType.Anoymous works their is nothing default I believe this should be a true or false 

The new feature should be in the form of the following.

    services.Configure<IdentityOptions>(options =>     {
                // Default Lockout settings.
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;
                **options.User.AllowGuestUser=true;**             
            });
### Additional context
When the user is to be true a button should be generated on the register / login pages for the user to register as a guest user with some kind of login link generated for the user which would assign the userId from the AspNet users tables in the normal way.

    Register page when AllowGuestUser= true;
 
![image](https://user-images.githubusercontent.com/5619229/105475936-e7943900-5c97-11eb-963b-1842a59e24de.png)

    Login Page when AllowGuestUser= true;

 
![image](https://user-images.githubusercontent.com/5619229/105475893-d64b2c80-5c97-11eb-8201-b9e49f1e1049.png)

**Comment by blowdart** [comment]
This isn't a feature we're interesting in developing I'm afraid, it's too big a change, and we've not seem any real demand for it.
