### ISSUE TITLE
SignalR SSE (Error: Error occurred) on every client side invoke  of an hub function

### ISSUE THREAD

**Issue by nejis** [dotnet/aspnetcore#29525]
Version of netcore used: 3.1:
Client language: JS

I use SignalR SSE to connect one hub on my server, but every time i  use 
`connection.invoke("NameOfAnFunction", p1, p2).catch(err => console.log(err));`
or
`connection.invoke("NameOfAnFunction").catch(err => console.log(err)):` for na function without an parameter.

i will get the error "Error: Error occurred" on client side, but the hub function  it self, runs without an error.

Example hub function:
  ` public async Task SendInvitation(string key)        {                    await base.Clients.Client(key).Invitation("Value for the other client");                  }`

**Comment by davidfowl** [comment]
Can you make a sample that reproduces the problem and share it with us along with the environmental details (windows, linux, which webserver, etc)
