### ISSUE TITLE
Publishing Blazor WASM on iis throws 403 error for all files

### ISSUE THREAD

**Issue by AmirImam** [dotnet/aspnetcore#29533]
Hi.
I am trying to publish Blazor WASM app on iis, but it is not working, it throws 403 error in console for all DLLs and JSs files. It looks like it need some read permissions, so I opened read permissions  but still not working
The strange thing that the errors appears only when the connection is secure (HTTPS not HTTP)

**Comment by javiercn** [comment]
@AmirImam thanks for contacting us.

That seems to be an issue with your IIS configuration.

@shirhatti do you have any ideas/suggestions on how to best troubleshoot this?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Comment by AmirImam** [comment]
> @AmirImam thanks for contacting us.
> 
> That seems to be an issue with your IIS configuration.
> 
> @shirhatti do you have any ideas/suggestions on how to best troubleshoot this?

The only thing I found after some searches is allow read permission on folders, and I did that but didn't solve the issue.

**Comment by AmirImam** [comment]
> Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

I know that this is not "general-purpose forum", and I posted issue here because I think this is a blazor related issue, and it didn't show up with any other platform, it just happened when publishing blazor web assembly on SSL
