### ISSUE TITLE
Investigate usage of ElementAt and LINQ methods in Razor

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#29538]
These methods can cause a significant performance degradation such as in https://github.com/dotnet/aspnetcore-tooling/pull/2987. Evaluate our usage in such cases using a benchmark to avoid pre-mature optimization.

**Comment by NTaylorMullen** [comment]
Just to be clear for whoever addresses this. The problem isn't really `ElementAt`, although it definitely encourages bad use. Because IEnumerable's are lazy and uncached you can get into some (O)n^2 scenarios super easily unless you force evaluation of the array you're `ElementAt`ing (ToArray).

**Comment by ToddGrun** [comment]
Or if you do it on pretty much any data structure that isn't a list
