### ISSUE TITLE
Unable to unload a class library project contains controllers in it in asp.net core web api 

### ISSUE THREAD

**Issue by shiva556** [dotnet/aspnetcore#29536]
Hi , 
We are having some class libraries containing controllers in it, which we load to the api dynamically using application part manager and after some time we remove the controllers using the application part manager, and to load the class library we are using custom assembly load context, once we remove the controllers from class library using application part manager and we are unloading the class library which is loaded earlier,but after unloading also ,when we use AppDomain.CurrentDomain.GetAssemblies it is returning the unloaded library also

**Comment by Pilchie** [comment]
Related to https://github.com/dotnet/aspnetcore/issues/21159. We haven't done a lot of work to support AssemblyLoadContext in ASP.NET Core.

**Comment by javiercn** [comment]
@shiva556 thanks for contacting us.

Application part manager doesn't support dynamically removing controllers at runtime. Any configuration must happen during service registration and before any user provided primitives (like controllers, view components, etc) are registered on the DI container.
