### ISSUE TITLE
Tell virtualize component to reload data

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#29535]
I have a virtualized component within a Blazor Server app, which loads data from an ItemProvider. 

Consider the following code:
```
<Virtualize Context="order" ItemsProvider="LoadOrders">
	<ItemContent>
		<tr tabindex="1">
			<td>@order.BEST_N_NR</td>
		</tr>
	</ItemContent>
	<Placeholder>
		<tr>
			<td>Loading...</td>
		</tr>
	</Placeholder>
</Virtualize>

private async ValueTask<ItemsProviderResult<Order>> LoadOrders(ItemsProviderRequest request)
{
	int totalOrders = await orderService.GetTotalOrdersAsync(Filter);
	var orders = await orderService.GetOrdersAsync(Filter, request.CancellationToken).ToListAsync();

	return new ItemsProviderResult<Order>(orders, totalOrders);
}


public class OrderFilter : Filter
{
	public OrderFilterOption Option { get; set; }
	public int StartIndex { get; set; }
	public int Limit { get; set; }
	public override string ToSqlQuery()
	{
		/* Generates SQL based on Filter */
	}   
}
```
As you can see I'm passing my Filter instance down to my method `GetOrdersAsync()`. However a change for this object is only detected when I start scrolling within my virtualize component, which makes sense because it is only being used within the method itself. 

But how do I call the virtualize component to reload the data?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
You can use the `RefreshDataAsync` API to achieve what you want. You can learn more about it at: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0
