### ISSUE TITLE
Blazor Server: scoped css file not generated when replacing env.IsDevelopment with env.IsEnvironment("Local")  

### ISSUE THREAD

**Issue by gvdvenis** [dotnet/aspnetcore#29560]
We tend to use another build environment name in local development scenarios. Hence we set `ASPNETCORE_ENVIRONMENT` environment variable to `"Local"` and add an extra condition in the `Configure` method in `Startup.cs`. This enables us to differentiate between local dev work and the shared dev server on which our application gets deployed for internal testing etc.

Now I know there are ways around this, for example: use `Development` for local and `DevDeploy` for shared development deploy, but this is not the point however.

## Reproduction steps:

1. Create a new empty Blazor Server application
2. Set the `ASPNETCORE_ENVIRONMENT` environment variable to `"Local"` 
3. Add condition in `Configure` method in `Startup.cs`. _Note that strictly speaking this is not necessary for reproducing this issue, but it does show you how I implement this normally._
    ```C#
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
  
        if (env.IsDevelopment() | env.IsEnvironment("Local")) // <-- note the extra condition here
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
        }
        // rest of code removed for brevity
    }
    ``` 
4. Start the application.
 
Note that the application starts up, but scoped styles are missing and (Chrome) devtools throws a 404.

My guess is that `env.IsDevelopment()` is used as a condition somewhere in the build process to distinguish local/dev builds from deployed builds and every environment that is not `Development` is considered to be a deployed build.

## Dev Environment specifics:

```
PS > dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by pranavkm** [comment]
Static web assets which is what CSS isolation uses relies on the environment being Development. To support it in other environments, you'll have to configure the middleware. https://github.com/dotnet/aspnetcore/issues/28174#issuecomment-734239932 specifies how.

@Tratcher were you still planning to tidy up the use of `IsDevelopment` in `CreateDefaultBuilder`?

**Comment by Tratcher** [comment]
Yes, but not anytime soon. https://github.com/dotnet/aspnetcore/issues/28937

**Comment by gvdvenis** [comment]
@pranavkm Thanks for the suggestion. It's really not that big of a deal, but it took me a few precious hours to discover that this simple configuration change was causing me this headache. It would have been helpful if it was mentioned more specifically in the docs.

However, after a little more investigation I found [this little gem](https://github.com/dotnet/aspnetcore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/WebHost.cs#L211-L216) in the `WebHost` source. So I ended up doing this in the `CreateHostBuilder` method in `Program.cs`:

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureLogging(logging =>
        {
            logging.ClearProviders();
            logging.AddConsole();
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            // this addition enables StaticWebAsset provisioning for the "Local" environment
            webBuilder.ConfigureAppConfiguration((ctx, cb) =>
            {
                if (ctx.HostingEnvironment.IsEnvironment("Local"))
                {
                    StaticWebAssetsLoader.UseStaticWebAssets(ctx.HostingEnvironment, ctx.Configuration);
                }
            });
            webBuilder.UseStartup<Startup>();
        });
```

... which works like a charm 👍 Any suggestions on improving on this would obviously be welcome ;) 

This solves it for me, but the bigger issue at hand here is IMHO the direct dependency on the `IsDevelopment()` method in the framework source code, without the possibility to change the naming conventions that define this environment. So I also support implementing this feature: #28937
