### ISSUE TITLE
[Blazor] The `onloadstart` event does not work for <img />

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#29582]
### Describe the bug

I used a method to bind the `<img />` element's `onloadstart` event, but it didn't get triggered

### To Reproduce

```html
 <img alt="@Alt" class="ant-image-img" src="@Src" style="@_imgStyle"
         @onerror="HandleOnError"
         @onloadstart="HandleOnLoadStart"
         @onload="HandleOnLoad" />
```

```csharp
       private void HandleOnLoadStart()
        {
            _loaded = false;
        }
```

The full source code is in my repo : https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/image/Image.razor#L8

### Further technical details
- ASP.NET Core version 5.1
- Include the output of `dotnet --info` 
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version vs2019 16.8

**Comment by SteveSandersonMS** [comment]
Could you please try putting the `@onloadstart` attribute before the `src` attribute?
