### ISSUE TITLE
Single file executable causes `System.IO.FileNotFoundException` 

### ISSUE THREAD

**Issue by cpohk26** [dotnet/aspnetcore#29581]
### Description

Single file executable causes `System.IO.FileNotFoundException` in long running applications after the application run for few days (around 5 - 15 days).

### Configuration

Version: ASP.NET Core 3.1
OS: Windows 10 Enterprise 1809 & 1909
Architecture: x86-64
Long-running, non-containerized, console application.

### Other information

There is a cron worker inside the long-running app. 

## When
When the cron triggers (eg every 30 minute mark) a specific action will execute, for the stack trace below is sending email (but not limited to). This usually occurs when the application run for few days.

Please note `_` is the organizational information removed. 

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Mail, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Net.Mail, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at _.Implementations.Common.MessengerService.SendEmail(IBodyComposer composer, MessageContent content, String host)
   at _.Implementations._.MailDispatcher.SendToAdmin(Boolean escalationMode)
```

**Comment by javiercn** [comment]
@cpohk26 thanks for contacting us.

We are not sure this issue is specific to ASP.NET Core, we'll try to route it to the right repository.

Does the functionality work when the app starts and it's only after a period of time that it breaks?

@Pilchie does this go to runtime/core/sdk?

**Comment by mkArtakMSFT** [comment]
This to me seems like an issue with the app itself, but I can be wrong. Anyway, it's not ASP.NET Core specific. [StackOverflow](https://stackoverflow.com) would be a better place to start a thread on this to get help understanding what causes it.
