### ISSUE TITLE
Improve TargetPickerUi API docs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#29584]
API docs on this type provide no information

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Components/WebAssembly/Server/src/TargetPickerUi.cs

**Comment by javiercn** [comment]
@JamesNK I don't think this class is meant to be consumed by customers. I believe it's only for the debug proxy the app host, which I think we want to change.

@captainsafia is my understanding correct? Feel free to mark as a bug otherwise

**Comment by captainsafia** [comment]
@javiercn Yep, your understanding is correct. These types aren't intended for public use. In hindsight, it would've made sense to mark them as internal but c'est la vie.

To that end, we don't need to document them.
