### ISSUE TITLE
Problem with ReadFromJsonAsync when reading nested DTO

### ISSUE THREAD

**Issue by Chas5555** [dotnet/aspnetcore#29592]
### Describe the bug
On my Clien WASM I am trying to read a nested DTO using ReadFromJsonAsync.  Unfortunately the line always throws a JsonException error.  I have carried out an extensive search on the internet but couldn't find any possible sulution that worked.
My code:
   protected override async Task<EditBlogPostViewModel> OnParametersSetAsync()
    {

        using var httpResponse = await client.GetAsync($"api/AuthorPost/{postId}");
  
                if (!httpResponse.IsSuccessStatusCode)
        {
            //THIS POINT ISN'T REACHED
        }
        else
        {
            PostVM = await httpResponse.Content.ReadFromJsonAsync<EditBlogPostViewModel>();//****FAILS ON THIS LINE ******
        }

        return null;
    }

When I make the equivalent GET call to the API using Postman using "https://localhost:44340/api/Authorposts/6" the return body is seemingly correct:

{
    "id": 6,
    "title": "Test v2",
    "content": "gdfg sdgsdg ",
    "description": "sad dsdsg",
    "publishOn": "2021-01-28T07:17:57.2659748",
    "public": false,
    "topicsList": [
        {
            "topicId": 1,
            "title": "Blogger",
            "isSelected": false
        },
        {
            "topicId": 2,
            "title": "Recipes",
            "isSelected": false
        },
        {
            "topicId": 3,
            "title": "On Your Doorstep",
            "isSelected": false
        }
    ],
    "categoriesList": [
        {
            "categoryId": -6,
            "name": "Marinades",
            "isSelected": false
        },
        {
            "categoryId": -5,
            "name": "Main Meals",
            "isSelected": false
        },
        {
            "categoryId": -4,
            "name": "Loaves",
            "isSelected": false
        },
        {
            "categoryId": -3,
            "name": "Curries",
            "isSelected": false
        },
        {
            "categoryId": -2,
            "name": "Cakes",
            "isSelected": false
        },
        {
            "categoryId": -1,
            "name": "Biscuits",
            "isSelected": false
        }
    ]
}

This is the DTO I'm using:

 public class EditBlogPostViewModel
  {
    [Required]
    public long Id { get; set; }
    [Required]
    public string Title { get; set; }
    [Required]
    public string Content { get; set; }
    [Required]
    public string Description { get; set; }
    [Required]
    //[DisplayFormat(DataFormatString = "{0:MM/dd/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
    public DateTime PublishOn { get; set; }
    [Required]
    public bool Public { get; set; }
        //[Required]
        //[JsonIgnore]// Put in to try and resolve JsonException error on client, it didn't solve problem.
        public List<TopicsCheckBox> TopicsList { get; set; }
        //[Required]
        //[JsonIgnore]// Put in to try and resolve JsonException error on client, it didn't solve problem.
        public List<CategoriesCheckBox> CategoriesList { get; set; }
  }
### Exceptions (if any)
The browser Developer Tools console provides the following error details:
 System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[ChasWasm.Shared.ViewModels.Author.EditBlogPostViewModel, ChasWasm.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[ChasWasm.Shared.ViewModels.Author.EditBlogPostViewModel, ChasWasm.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[EditBlogPostViewModel](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[EditBlogPostViewModel](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.<ReadAsync>d__20`1[[ChasWasm.Shared.ViewModels.Author.EditBlogPostViewModel, ChasWasm.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__3`1[[ChasWasm.Shared.ViewModels.Author.EditBlogPostViewModel, ChasWasm.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at ChasWasm.Client.Pages.AuthorPosts.EditPostPage.OnParametersSetAsync() in D:\chasr\source\repos\ChasWasm Git\Client\Pages\AuthorPosts\EditPostPage.razor:line 68
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

-->

### Further technical details
- ASP.NET Core version - .net 5.0 on all projects
- 
- Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\chasr>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Running on Visual Studio 2019 16.8.4

**Comment by javiercn** [comment]
@Chas5555 thanks for contacting us.

This is likely an issue in your code, I would suggest you verify the following things:
* On the network tab of the browser, check out the response coming from the server when you issue the network call.
  * Validate you are receiving a 200 status code.
  * Validate that the content-type of the response is `application/json`
  * Validate that you can serialize and deserialize the payload in a console application.

**Comment by Chas5555** [comment]
Thank you for your advice, all of which I have tried out;

On the network tab of my browser (Edge Chrome)  I checked out the response coming from the server when I issued the network call.

I can confirm I am receiving a 200 status code.  The same in Postman.

I can confirm that the content-type of the response isn't  **application/json** but **text/html**.   I tried to force the response formats by applying the **[Produces("application/json")]** filter in the controller but this still failed in the same way with  a content-type of **text/html**.  I also tried by applying **client.DefaultRequestHeaders.Add("Accept","application/json")** in the client method but this still failed in the same way with a content-type of **text/html**. 

Here is a copy of the Header from the network tab of the browser:

Request URL: https://localhost:44340/api/AuthorPost/6
Request Method: GET
Status Code: 200  (from disk cache)
Remote Address: [::1]:44340
Referrer Policy: strict-origin-when-cross-origin
accept-ranges: bytes
content-encoding: gzip
content-type: text/html
date: Mon, 25 Jan 2021 07:44:27 GMT
etag: "1d6ebd3df3dbec6"
last-modified: Sat, 16 Jan 2021 06:50:27 GMT
server: Microsoft-IIS/10.0
vary: Accept-Encoding
x-powered-by: ASP.NET

I can confirm when deserializing the payload in a console application an error is still thrown.

**Comment by Chas5555** [comment]
Further to my previous comments.
I have further explored the suggestions made by Javier and discovered that the url used in the 'ReadFromJsonAsyn' line was spelt incorrectly - a classic case of 'not seeing the wood for the trees' :-( 
Have rectified problem and the app tested ok.
Many thanks again for the feedback.
