### ISSUE TITLE
Nested <text> tags are not colorized properly in new Razor editor

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#29595]
Left is new editor right is old editor. This is with latest preview builds.

Left is new right is old:
![image](https://user-images.githubusercontent.com/2008729/105736154-56b49c00-5ee9-11eb-936e-5ec48a2472b7.png)

@ryanbrandenburg it may make sense to not colorize any C# pieces at all maybe?

**Comment by ryanbrandenburg** [comment]
Here's what this looks like in VS latest:
![image](https://user-images.githubusercontent.com/14987221/113042267-d2cc9980-914f-11eb-94bd-116b2ddea68f.png)
The `<text>` now seem to be colored correctly, but our `@if` has regressed.

**Comment by ryanbrandenburg** [comment]
![image](https://user-images.githubusercontent.com/14987221/113436730-16b2df00-939a-11eb-936d-98254ca018a1.png)
