### ISSUE TITLE
Add null check code action in Razor sometimes doesn't show up

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29606]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Add-null-check-code-action-in-Razor-some/1318633)._

---
Repro steps:
- Enable the new experimental Razor editor
- Create a new Blazor Server project
- Update Pages/Index.razor with the following code block:

```
    string GetMessage(string name)
    {
        return $"Hello, {name}!";
    }
    ```

- Right click on `name`, and select "Quick actions and refactorings..."
- See that "Add null check" shows up (but don't select it)
- Save Index.razor and close and reopen the file
- Right click on `name` again

Expected result: 
- "Add null check" option shows up

Actual result:
- The option isn't displayed.

---
#### Feedback Bot on 1/24/2021, 07:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/25/2021, 11:18 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment]
![NoNullCheck](https://user-images.githubusercontent.com/14852843/105765272-0bac8000-5f0d-11eb-8e22-b713b3af2629.gif)

Getting a repro, however not 100%. Investigating...

**Comment by TanayParikh** [comment]
Fixed 🎉. Validated by doing the repro steps 5x.
