### ISSUE TITLE
HTTP/3: Return H3_FRAME_UNEXPECTED protocol error for unexpected frames

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#29617]
Spec says that Kestrel should return H3_FRAME_UNEXPECTED protocol error for unexpected frames

https://tools.ietf.org/html/draft-ietf-quic-http-33#section-4.1

Currently doing:

https://github.com/dotnet/aspnetcore/blob/45867e0be114d5a214c573eab705dc0cf8ef222a/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs#L440-L459

Also check other places where Kestrel processes frame types.

**Comment by BrennanConroy** [comment]
@wtgodbe Would you be interested in taking this on for preview3?

**Comment by wtgodbe** [comment]
> @wtgodbe Would you be interested in taking this on for preview3?

Yup!

**Comment by JamesNK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/29665
