### ISSUE TITLE
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found

### ISSUE THREAD

**Issue by benukhanov** [dotnet/aspnetcore#29611]
Hi, what is wrong here? docker build works. Another netcore app works fine.

![image](https://user-images.githubusercontent.com/13782467/105778399-097e0c00-5f75-11eb-9bae-341d529339de.png)

This open source code is available [here](https://github.com/benukhanov/maple-fighters/tree/develop/src/auth-service).

**Comment by javiercn** [comment]
@benukhanov thanks for contacting us.

Looks like something on your installation is wrong?

Is that the output from inside the docker container? Can it be that you are targeting the wrong image?

**Comment by benukhanov** [comment]
> @benukhanov thanks for contacting us.
> 
> Looks like something on your installation is wrong?
> 
> Is that the output from inside the docker container? Can it be that you are targeting the wrong image?
> 
> It would help us if you give us a minimal repro of this issue so that we can help

Hey I'm sorry. I had to change final image from mcr.microsoft.com/dotnet/runtime:5.0 to mcr.microsoft.com/dotnet/aspnet:5.0 :)

I thought .NET 5.0 would not matter between ASP.NET and .NET since both have the same net5.0 version.

**Comment by javiercn** [comment]
@benukhanov the image matters because we want to offer folks the smallest image possible, for the SDK doesn't matter since you only use it for building, but for runtime its more important.

I'm glad you were able to figure out the issue!

**Comment by benukhanov** [comment]
> @benukhanov the image matters because we want to offer folks the smallest image possible, for the SDK doesn't matter since you only use it for building, but for runtime its more important.
> 
> I'm glad you were able to figure out the issue!

Yes that makes sense. Thanks!
