### ISSUE TITLE
CustomJsonConverter and CustomModelBinder

### ISSUE THREAD

**Issue by robertok77** [dotnet/aspnetcore#29624]
When request _POST of application/json_ then _CustomJsonConverter_ is called which is ok
but
when I register _CustomModelBinder_ then the same POST calls this _CustomModelBinder_ instead.

I need _CustomModelBinder_ in GET request.

How to delegate deserialization to _CustomJsonConverter_  in POST request ?

### 
- ASP.NET Core version 5.0

**Comment by javiercn** [comment]
@robertok77 thanks for contacting us.

You can apply the model binder specifically to the GET action using the modelbinder attribute in the action parameter instead of registering it globally.

**Comment by robertok77** [comment]
> @robertok77 thanks for contacting us.
> 
> You can apply the model binder specifically to the GET action using the modelbinder attribute in the action parameter instead of registering it globally.

well I need bunch of binders for polymorphism, I use CustomModelBinderProvider for CustomModelBinders

however, the orginal behaviour is ok,
how to get the same behaviour using CustomModelBinderProvider  _and_ CustomJsonConverter ?
