### ISSUE TITLE
Blazor oidc.user gets deleted right after login

### ISSUE THREAD

**Issue by ekjuanrejon** [dotnet/aspnetcore#29622]
Using Blazor web assembly with IdentityServer4. 

After successful authentication with IdentityServer and redirected to the Blazor App the session key oidic.user which contains the access token gets deleted right awa.

I notice this issue while running blazor locally and IdentityServer deployed with FQDN.

I have another Blazor app deployed with FQDN and the issue does not exist. Could it be only in local development

**Comment by javiercn** [comment]
@ekjuanrejon thanks for contacting us.

We don't think we have enough information to determine if there is an issue here. Are you using the support we provide outside of the box for this?

**Comment by ekjuanrejon** [comment]
Hello @javiercn 

I am using the template with individual accounts. Everything seems to work. The app get redirected to the IdentityServer and login successfully. The call back works fine. I press F12 and on the application tab and inspect the session storage. I see oidc.user appear with the access toke and id_toke and right away disappear.

```
builder.Services.AddOidcAuthentication(options =>
            {
                // Configure your authentication provider options here.
                // For more information, see https://aka.ms/blazor-standalone-auth
                builder.Configuration.Bind("Local", options.ProviderOptions);
            });

"Local": {
    "Authority": "http://login.mydomain.com/",
    "ClientId": "f42bec6c-6a82-4b52-94a0-12d2021fd48b",
    "DefaultScopes": [
      "MyApiGateway"
    ],
    "PostLogoutRedirectUri": "/",
    "ResponseType": "code"
  },

**Comment by ekjuanrejon** [comment]
I came across this issue since I am trying to access token automatically attached to Refit. I am following doc and it is not working. The reason it is not working because the oidc.user storage get's cleared and it attempts to redirect again

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#custom-authorizationmessagehandler-class

**Comment by javiercn** [comment]
@ekjuanrejon thanks for the additional details.

That indeed seems a bit strange. We do clear the state when we start a login flow, could it be that your app is in an "infinite" login flow?

A way to determine this might be to debug through the login flow on the dev tools and determine at which point the storage key gets removed.

**Comment by ekjuanrejon** [comment]
@javiercn  Yes, I was debugging the app and the token get's removed right after the callback from IdentityServer

I am experiencing the same as this stackoverflow

https://stackoverflow.com/questions/65772055/blazor-webassembly-pwa-session-storage-not-persisting-after-deployment-to-azure

**Comment by akhansari** [comment]
After a day of investigation, I finally found out that it was due to the blocking of third-party cookies.
It happens only with Blazor (or wasm) because the same behavior with a Vuejs SPA works correctly.

**Comment by mkArtakMSFT** [comment]
Thanks for sharing the update with us, @akhansari.
Closing as no further actions are pending here.
