### ISSUE TITLE
Matching Subs Components in Custom Rendered ChildContent fragment "absorb" each others properties!

### ISSUE THREAD

**Issue by appsupport-gc** [dotnet/aspnetcore#29637]
I am trying to build a custom UI framework which involves "Page" components whose ChildContents can be rendered in different locations depending on such parameters as screen size or custom page load logic.

### Describe the bug
I have found that having a custom wrapper class around the page component and child "header" component causes the "header" component to "absorb" the properties of a "similar" header component in another page when the currently displayed "page" object is changed.  

### To Reproduce
Here is a GREATLY simplified github repo showing the problem complete with built in descriptions of the problem.:  https://github.com/appsupport-gc/BlazorIssue_ChildContent-SubComponent

I don't believe I can make it any simpler (I've tried).

Please notice the text in red bold after clicking the Comp1 and Comp2 buttons.  Title1 was set on one component and Title2 and an ENTIRELY DIFFERENT component but after clicking both buttons the Header components have ABSORBED both properties!  This happens no matter how complex the properties being passed to the Header object are.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

**Comment by javiercn** [comment]
@appsupport-gc thanks for contacting us.

I'm not exactly sure of what's going on with your app, but grabbing a hold of a component through a ref and accessing it's childcontent property to render it somewhere else in the actual page is not something we support and is likely causing the behavior you are observing.

**Comment by appsupport-gc** [comment]
Wow!!  That's scary!  I've developed an entire UI framework around the idea of making a "list" of components then displaying different one of these components based on specific criteria or a specific ID. It has worked GREAT until I came to wrapping those components inside ANOTHER component in order to break out the code complexity some.  Use @CurrentPage?.ChildContent where CurrentPage is calculated from the List of pages was the only way I could see to do this.  Is there some OTHER method you would suggest?  The Pages need to be able to switch which parent object they are displayed in based on various logic including the width of the screen. E.g. In Desktops there might be 3 parent vertical panels, in Tablets 2, and in phones 1, with the pages being placed and navigated accordingly...

**Comment by appsupport-gc** [comment]
This seems VERY similar to my methodology:  https://blazor-university.com/templating-components-with-renderfragements/passing-data-to-a-renderfragement/. 
The only difference is I'm adding the ability for "pages" to be moved to an entirely different "panel" if needed based on the screen size.

**Comment by appsupport-gc** [comment]
I tried setting @key="Page" and @key="this" hoping that would solve it (since the Pages are unique) but that didn't work.

**Comment by appsupport-gc** [comment]
Adding a Clear button works but setting the DisplayPage to null, then statehaschanged, then DisplayPage = Page2 does NOT.

**Comment by appsupport-gc** [comment]
Ok adding await Task.Delay(TimeSpan.FromMilliseconds(1)); without even having to run statehaschanged!

DisplayPage = null;
await Task.Delay(TimeSpan.FromMilliseconds(1));
DisplayPage = newPage;

**Comment by appsupport-gc** [comment]
Ok I found Another issue which is a DEAL BREAKER!!!   I added it to the github repo https://github.com/appsupport-gc/BlazorIssue_ChildContent-SubComponent.  A Counter component inside a child components childfragment that get's rendered elsewhere does NOT pass or update parameters correctly!!  This seems like a HUGE deal!!  How can we build flexible UIs if we cannot make movable panes?
