### ISSUE TITLE
Consume ValueTask with GetAwaiter().GetResult()

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#29639]
https://github.com/dotnet/aspnetcore/blob/7eae2cd97f83c8cd4271df70169a4bd678d02658/src/SignalR/server/Core/src/DefaultHubLifetimeManager.cs#L106-L116
Should there be a `task.GetAwaiter().GetResult()` after the if block, so if it is a `IValueTaskSource` backed ValueTask, it will inform it its result has been read so it can reset?

**Comment by davidfowl** [comment]
Yes!

**Comment by BrennanConroy** [comment]
Closed via https://github.com/dotnet/aspnetcore/pull/29660
