### ISSUE TITLE
cshtml code change is not reflecting in the browser when refreshing , i have to launch to get effect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29646]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/cshtml-code-change-is-not-reflecting-in-/1312030)._

---
cshtml code change is not reflecting in the browser when refreshing , i have to launch to get effect, this is delaying to work a lot.

---
#### May Lei [MSFT] on 1/17/2021, 11:32 PM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? It would be very helpful if you could provide some screenshots of this problem.</p>
<p>We look forward to hearing from you!</p>

#### arunprasades on 1/17/2021, 11:53 PM: 

<p>Steps to reproduce, create a dot net core project,  version  2 and 3 with latest visual studio, debug the project,  while the project is still running,  make a change to the cshtml page, it will not reflect right away even if I refresh the browser.  I have to stop the solution and re debug it, then the change is shown. This is very time consuming and bug.</p>

#### Feedback Bot on 1/18/2021, 00:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Does your project enable runtime compilation: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio#razor-compilation?
