### ISSUE TITLE
No colorization in new Razor editor followed by report of exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29643]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/No-colorization-in-new-Razor-editor-foll/1308994)._

---
Taylor told me to send this after this happened during a shared coding session with him. padding padding padding

---
#### Feedback Bot on 1/13/2021, 10:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Fixed in latest builds.
