### ISSUE TITLE
Validate remote debugging in VS Code for Blazor WASM

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#29657]
Once https://github.com/microsoft/vscode-js-debug/issues/916 and https://github.com/dotnet/aspnetcore/issues/22587 are complete, we should validate that remote debugging Blazor WASM applications in VS Code works and address any bugs that result from.

**Comment by javiercn** [comment]
@captainsafia I tagged it and put it in a milestone, if that's not the correct milestone, then feel free to move it where appropriate.
