### ISSUE TITLE
Page Loading...

### ISSUE THREAD

**Issue by Nonelela-Hlati** [dotnet/aspnetcore#29656]
Browser showing Loading...
![image](https://user-images.githubusercontent.com/71264012/105644006-fa775b00-5e9b-11eb-99b1-5faa3d032e4c.png)

**Comment by javiercn** [comment]
@Nonelela-Hlati thanks for contacting us.

Does this happen every time for you or is this a one time thing.

Could you provide us with a minimal repro project and detailed steps to recreate the issue so that we can investigate?
