### ISSUE TITLE
Define templated component in RenderFragment with its @context available

### ISSUE THREAD

**Issue by anddrzejb** [dotnet/aspnetcore#29671]
### Is your feature request related to a problem? Please describe.
I have a tooltip component that has a child content. Tooltip will be shown whenever the mouse hovers over that child content. But tooltip does not wrap the child content with anything. So if you check out the source, you will only see the child content without any indication of the tooltip. The moment mouse cursor hovers over the child content, the tooltip container is added to the bottom of the page and is position right over that child content. This is quite problematic to achieve in blazor because the tooltip needs to have the reference to the child content. But references are established after parameters are filled. So a special wrapper is used to achieve that and Tooltip is built as a templated component.

In the code below  
* `Unbound` is `[Parameter] public RenderFragment<ForwardRef> Unbound  { get; set; }`
* `RefBack` is `[Parameter] public ForwardRef Refback { get; set; }`
and it gets me the mentioned error:
```razor
private static RenderFragment _tooltip =
@<Tooltip Title="@("Tooltip tiltle")">
    <Unbound>
        <Icon RefBack="@context" Type="download" Theme="outline" />
    </Unbound>
</Tooltip>;
```
To answer the question - why I am trying to use RenderFragment - imagine I have a collection of cards - let's say 150. The card component accepts as a parameter IList<RenderFragment> for rendering buttons on a card. I want to pass my icon with tooltip to that card. I need to have access to Tooltip's context.

I solved it using the builder:
```csharp
private static RenderFragment tooltipFormTemplate => __builder =>
{
    __builder.OpenComponent<AntDesign.Tooltip>(0);
    __builder.AddAttribute(1, "Title",
    Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>("Tooltip title"));
    __builder.AddAttribute(2, "Unbound", (RenderFragment<ForwardRef>)((context) =>
        @<Icon RefBack="@context" Type="download" Theme="outline" />
    ));
    __builder.CloseComponent();
};
```

### Describe the solution you'd like
I believe the first solution is easier to maintain. Is it achievable?

A side note - marvellous job on the Blazor Framework. Thank you all!!!

**Comment by javiercn** [comment]
@anddrzejb thanks for contacting us.

It's not clear from the sample code what you are trying to achieve. If you could provide a minimal repro project we might be able to help you.

**Comment by anddrzejb** [comment]
@javiercn [Here](https://github.com/anddrzejb/blazor_issue29671) is the repro. 
A small info:
* `Tooltip` component is just a mock in that repro. In real live scenario it creates a tooltip using the `ForwardRef` wrapper for `ElementReference` (is there any better way of passing child's reference to the parent?)
* `CardDeck` is a simulation of an external component, that I cannot change. So I am forced to create a `RenderFragment`.

**Comment by javiercn** [comment]
@anddrzejb thanks for the additional details.

I think I understand now.

I believe it will work if you make it a property instead of a field.

```
    private RenderFragment<string> TooltipFormTemplate => context => __builder =>
        @<Tooltip>
            <UnboundChildContent>                
                <span class="oi oi-arrow-bottom" ref="@context.Current"></span>
            </UnboundChildContent>
        </Tooltip>
```
alternatively, writing it as a method can also work I believe.

There's not really an "official" way to do this and I don't get to do it very often, but I believe either using a property or a method will generate the right syntax.

We have an issue tracking improving support for this in the future.

**Comment by anddrzejb** [comment]
Ok, I do not really care about the string passed to the `RenderFragment` that much. Isn't `context` in your example is a string? I need to get the `context` of the `Tooltip`'s template, not a string passed to `RenderFragment`.
Anyway, now I get `Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement`...

**Comment by javiercn** [comment]
@SteveSandersonMS do you know what the incantation was to get this to "work"?

**Comment by SteveSandersonMS** [comment]
I'm not completely certain if this is what you're asking for, but the following is legal Razor code:

```razor
private RenderFragment<MyContext> TooltipFormTemplate => context => __builder =>
{
    <Tooltip>
        <UnboundChildContent>
            <span class="oi oi-arrow-bottom" @ref="context.Current"></span>
        </UnboundChildContent>
    </Tooltip>
};

class MyContext
{
    public ElementReference Current { get; set; }
}
```

**Comment by anddrzejb** [comment]
I did not expected this to work - looks a bit magical to me, but it does work. Thank you!
