### ISSUE TITLE
CreateAppHost task failed unexpectedly

### ISSUE THREAD

**Issue by MCCshreyas** [dotnet/aspnetcore#29670]
Recently, while building the Mvc solution and `MvcSandbox` project am getting below error at the end!

![image](https://user-images.githubusercontent.com/17148381/105987373-368d0480-60c4-11eb-9293-fa6fe2299c68.png)

**Comment by Tratcher** [comment]
https://github.com/dotnet/sdk/issues/15225
https://github.com/dotnet/runtime/issues/47426

**Comment by Pilchie** [comment]
Closing as a duplicate of https://github.com/dotnet/sdk/issues/12125.  Should be fixed for preview 2 builds.
