### ISSUE TITLE
Headers are sent before context.Response.OnStarting is called

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/aspnetcore#29685]
Looks like context.Response.OnStarting has changed in .net 5, so headers are sent before callback is called

That kind ruins the whole idea of this callback as it is mostly used to modify the body of the response before it is sent.
However if Content-Length in the header has already been sent, then we cannot modify response body

**Comment by Tratcher** [comment]
There shouldn't have been any intentional changes here. Can you provide a repro?

Any modification of the response body requires buffering, how are you setting up buffering?

**Comment by FenrisWolfAtMiddleEarth** [comment]
Yes, sure.
The attached solution should reproduce the problem

[OnStarting.zip](https://github.com/dotnet/aspnetcore/files/5886301/OnStarting.zip)

**Comment by Tratcher** [comment]
The full stack trace from your repro:
```
      System.InvalidOperationException: Headers already sent.
         at Microsoft.AspNetCore.Server.HttpSys.Response.CheckResponseStarted()
         at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.ConsiderEnablingResponseCache()
         at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.OnResponseStart()
         at Microsoft.AspNetCore.Server.HttpSys.FeatureContext.CompleteAsync()
         at Microsoft.AspNetCore.Server.HttpSys.RequestContext.Execute()
         at Microsoft.AspNetCore.Server.HttpSys.RequestContext.Execute()
```
This might be related to an issue we're tracking at https://github.com/dotnet/aspnetcore/issues/12194.

FixResponseMiddleware from the repro:
```C#
        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            var originalBody = context.Response.Body;
            context.Response.Body = new MemoryStream();
            context.Response.OnStarting(async () => await FixResponse(originalBody, context.Response));
            await next(context);
        }

        private async Task FixResponse(Stream originalBody, HttpResponse response)
        {
            using (var streamReader = new StreamReader(response.Body))
            {
                response.Body.Seek(0, SeekOrigin.Begin);
                var responseBody = await streamReader.ReadToEndAsync();
                responseBody = responseBody.Replace("Wrong ", "");

                response.Body.Seek(0, SeekOrigin.Begin);
                await response.Body.CopyToAsync(originalBody);
                response.Body = originalBody;
            }
        }
```

OnStarting should only be used to modify headers, never the body.

Try this:
```C#
        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            var originalBody = context.Response.Body;
            var response = context.Response;
            response.Body = new MemoryStream();
            await next(context);

            // Clear Content-Length, if any
            response.ContentLength = null;

            using var streamReader = new StreamReader(response.Body);
            response.Body.Seek(0, SeekOrigin.Begin);
            var responseBody = await streamReader.ReadToEndAsync();
            responseBody = responseBody.Replace("Wrong ", "");

            response.Body.Seek(0, SeekOrigin.Begin);
            await response.Body.CopyToAsync(originalBody);
            response.Body = originalBody;
        }
```

**Comment by FenrisWolfAtMiddleEarth** [comment]
Yes works perfectly
Well almost.... you copied a bug, i had in my repro...

`        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {
            var originalBody = context.Response.Body;
            var response = context.Response;
            response.Body = new MemoryStream();
            await next(context);

            // Clear Content-Length, if any
            response.ContentLength = null;

            using var streamReader = new StreamReader(response.Body);
            response.Body.Seek(0, SeekOrigin.Begin);
            var responseBody = await streamReader.ReadToEndAsync();
            responseBody = responseBody.Replace("Wrong ", "");

            var newStream = new MemoryStream();
            var writer = new StreamWriter(newStream);
            await writer.WriteAsync(responseBody);
            await writer.FlushAsync();
            newStream.Position = 0;
            response.Body.Seek(0, SeekOrigin.Begin);
            await newStream.CopyToAsync(originalBody);
            response.Body = originalBody;
        }
`

In our production code migrated from .net 461 we did not actually use OnStarting
That was an attempt to make it work in net 5

All we need in our production code to migrate to net 5 was 
`context.Response.ContentLength = null;`

Thanks
