### ISSUE TITLE
Dispose X509Chain in CertificateAuthenticationHandler.ValidateCertificateAsync()

### ISSUE THREAD

**Issue by aalsamoht** [dotnet/aspnetcore#29680]
Is there a reason for not disposing the X509Chain in
CertificateAuthenticationHandler.ValidateCertificateAsync() by adding a using statement?
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Certificate/src/CertificateAuthenticationHandler.cs#L126

**Comment by blowdart** [comment]
No reason at all, we'd accept a PR for this :)

**Comment by blowdart** [comment]
Thank you very much, as you can see it's in progress now, please ensure you [sign the contributors agreement](https://github.com/dotnet/aspnetcore/pull/29724#issuecomment-769287575) because lawyers.
