### ISSUE TITLE
Implement a minimal version of MapAction 

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#29684]
This issue tracks what should be included in the first PR that adds a `MapAction` extension method to `IEndpointRouteBuilder`.

Requirements:
- Support for binding `[FromBody]`, `[FromRoute]`, `[FromQuery]`, `[FromHeaders]`, `[FromService]` parameters.
  - `[FromBody]` will be JSON-only for the first iteration
  - `[FromQuery]` will likely not support complex types due to MVC-isms
- Serialize return value as JSON-only for first iteration
- Use `[Route]` attribute instead of an explicit parameter.
- HttpContext injection 

Follow up:
- Benchmarks (#29915)
- Remove LINQ from startup path
- Input and output formatters
- Model binding validation
- Swagger support (IApiDescriptionGroupCollectionProvider implementation)
- MapAction filters

### Is your feature request related to a problem? Please describe.

I want to be able to use MVC features like parameter binding without having to write a Controller.

### Describe the solution you'd like

A `MapAction` extension method for `IEndpointRouteBuilder` that accepts controller action-like delegates.

**Comment by Tratcher** [comment]
What about `[FromForm]`?

**Comment by halter73** [comment]
I think `[FromForm]` will come later if at all because of its MVC-isms and because it's not really used much for APIs. For the first round, we're only going to support JSON for complex types. Maybe we can support it for simple stuff though.

**Comment by davidfowl** [comment]
I think you should add support FromForm as well.
