### ISSUE TITLE
Blazor C# autocomplete bug

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29705]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-C-autocomplete-bug/1315580)._

---
[severity:It's more difficult to complete my work]
When using intellisense/autocomplete in a Blazor @code block in VS 2019, sometimes code elsewhere will be deleted, including markup/components in some cases. Other times the code on which I'm attempting to autocomplete will just be deleted, including any tokens written to trigger it. On other occaisions the autocomplete will partially work (inserting only part of the snippet) while having partially erased an indeterminate amount of code that preceded it. Basically, using intellisense in a @code block is hazardous to one's existing code.

---
#### Feedback Bot on 1/20/2021, 09:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/27/2021, 04:59 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Cannot tell you how much I agree with you! This is actually one of the motivators for a new effort we've been working on: The experimental Razor editor! I believe a lot of what you mention has been/will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd be up to give it a try you can can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

Let us know if that resolves some things for you!

**Comment by freestylesimon** [comment]
Thanks, will give that a go and let you know.

**Comment by NTaylorMullen** [comment]
> Thanks, will give that a go and let you know.

Any update?

**Comment by freestylesimon** [comment]
I'm not sure it's mature enough for us to use in production yet, but maybe I just need to get used to it.

In Preview 3.0, while the new editor doesn't erase the existing code (a big win), autocomplete doesn't quite work as I'm used to. Maybe I'm typing too fast, but if I'm part way through typing a word like `overr` and pressed space, in the C# editor it would automatically get completed/corrected to `override`. In the Razor editor, if I'm typing too fast I have to go back and delete that partial word. Having said that, I've just tried again, and if I keep trying the same thing over and over, it gets quick enough to catch up with me. For reference, my machine is no slouch - it's fairly new with 32GB RAM, SSDs, overclocked 6 core i7.

In the C# editor, if I've not specified the protection level or return type and select an existing virtual/abstract method from the suggestions list, those would automatically get completed - that doesn't happen in the Razor editor.

I guess I write so much pure C# that I'm very used to that editor, and take the little things for granted which are then missed when they aren't there.

It does seem more stable - less prone to just forgetting about parsing at all - but it also is quite slow to respond to updates compared to the classic editor. As it's a preview I don't want to be overly critical about it! A replacement for the original editor is desparately needed.

**Comment by NTaylorMullen** [comment]
Really appreciate the feedback! As our experimental editor becomes less experimental we definitely expect the performance to drastically improve. For now I'm going to close out this issue as it's encompassed in that work. Again, really appreciate giving this new world a shot 😄
