### ISSUE TITLE
Add bit to DefaultHttpContext to indicate whether request is live

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#29709]
Since we pool `HttpContext`, instances of `HttpContext` no longer in use remain rooted. When scavenging the heap as part of analyzing a memory dump, this makes it extremely time consuming to ascertain whether an HttpContext represents an in-flight request. Adding a bit would greatly simplify this.

**Comment by davidfowl** [comment]
cc @Tratcher @halter73 @jkotalik

**Comment by shirhatti** [comment]
I spent some time in clrmd playing around with this. This didn't seem too complex to me and as such my current recommendation is not to add anything.

```csharp
// typeof(obj) == Microsoft.AspNetCore.Http.DefaultHttpContext
if (obj.ReadValueTypeField("_features").ReadObjectField("<Collection>k__BackingField").IsNull)
{
  // Request is not live
}
```

cc @n777ty who asked us to file this issue

**Comment by halter73** [comment]
This works, but what about people just using plain old SOS? Even in clrmd, it's harder than it needs to be. I think we should add the bit anyway.

**Comment by n777ty** [comment]
It would definitely help us a lot and speed up analysis of memory dumps (along with writing any analysis rules)... so my vote is for adding the bit.

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/29748
