### ISSUE TITLE
AuthorizeRouteView component not triggering NotAuthorized and does not render RedirectToLogin component

### ISSUE THREAD

**Issue by CoffeeStainJo** [dotnet/aspnetcore#29716]
### Describe the bug
I've got a Blazor WebAssembly hosted app with target framework net5.0 that has is secured following: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#client-app-configuration
It uses OidcAuthentication. When not logged in and navigating to the page Authorizing inside AuthorizeRouteView is triggered, but NotAuthorized is never triggered and thus the RedirectToLogin never happens. I have a similar application running .NET Core 3.1 where this is not an issue. 

As far as I can see the calls going out to IdentityServer are correct and thus the user is not authorized.
![image](https://user-images.githubusercontent.com/7232960/106139821-36494380-616e-11eb-8661-9fcd3651316e.png)

### To Reproduce

Create a Blazor WebAssembly hosted app (.net5.0)
Use OidcAuthentication
Secure app following: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#client-app-configuration

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/7232960/106139611-f1bda800-616d-11eb-8a16-f0677827b0ab.png)

### Further technical details
- ASP.NET Core version: 5.0.102
- output of `dotnet --info`:
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.617 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.812 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Microsoft Visual Studio Enterprise 2019 Version 16.8.4

**Comment by javiercn** [comment]
@CoffeeStainJo thanks for contacting us.

Are there any errors in the browser console?

**Comment by CoffeeStainJo** [comment]
Only the info about DenyanonymousAuthorizationRequirement
![image](https://user-images.githubusercontent.com/7232960/106148611-88439680-6179-11eb-8a88-3e60505d6535.png)

**Comment by javiercn** [comment]
@CoffeeStainJo thanks for the additional details.

Is the identity server instance hosted on the same origin as the Blazor app or is it a separate identity server hosted elsewhere?

Did you change anything after the project was created from the template?

Is there anything special about your configuration?

At this point a minimal repro project will help us understand what might be going on, since I'm not able to reproduce it.

**Comment by CoffeeStainJo** [comment]
The IdentityServer instance is hosted on another origin whereas the blazor app is running from localhost. Not sure if IdentiyServer is the problem seeing as pressing the login link properly redirects to /authentication/login and then to our custom login page. 

The project is completely fresh where the only change is done in Program.cs of the client. 

![image](https://user-images.githubusercontent.com/7232960/106150960-23d60680-617c-11eb-9b46-ff7fbb51f3f0.png)

Otherwise the project has these NuGet-packages

![image](https://user-images.githubusercontent.com/7232960/106151208-67307500-617c-11eb-800d-3d5d38bc9f91.png)
 
I can try to make a minimal repro project if that helps

**Comment by javiercn** [comment]
@CoffeeStainJo thanks for the additional details.

Let me make sure I understand correctly. You are able to click on login, it takes you to the `authentication/login` and from there it takes you to the IdentityServer login page, but you are not able to get back to the app?

From the original description I understood that you weren't even redirected to `authentication/login`. Does the paragraph above describe your current situation? (You are able to get to identity server login but not back to the app?)

**Comment by CoffeeStainJo** [comment]
No, after logging in on the IdentityServer login page I do return to the application (_if i manually press the login link in the top bar_) -- that's not the issue. 
![image](https://user-images.githubusercontent.com/7232960/106153458-dc9d4500-617e-11eb-9e3b-1bd008076561.png)


It's the automatic redirect to the Login component that is configured in the AuthorizeRouteView in App.razor that's not working. 

If I start a new InPrivate window/session in Edge and go to my page I expect to be redirected to the login component -- but it just does the Authorizing bit and loads the Index page.

**Comment by javiercn** [comment]
@CoffeeStainJo do you have `Authorize` on your index page?

**Comment by CoffeeStainJo** [comment]
`@attribute [Authorize]` seemed to be the culprit. Thank you for the help.
