### ISSUE TITLE
Service Provider has inconsistent behavior in case of "run by kestrel" and "host in IIS process"

### ISSUE THREAD

**Issue by lujiaxing** [dotnet/aspnetcore#29715]
### Describe the bug
When the asp.net core program is hosted in "w3wp" (IIS "In-Process" integration), root service provider can be used to resolve any registered types in anywhere, even in instances that have different lifetime cycle, But it could raise an exception if the program is run by Kestrel.

I'm not sure which behavior is correct, but at least they should be consistent.

### To Reproduce

1. Create a static class to hold ServiceProvider instance that just built in HostBuilder's initialization.
2. Register class A as "Singleton".
3. Register class B as "Scoped".
4. In the singleton class A, use the ServiceProvider instance from the static class to Instantiate class B
   (not using ScopeFactory)
5. If the program is running by kestrel, then an exception will be raised.
    If the program is hosted in w3wp, then the class A will get an instance of class B without any error.

### Exceptions (if any)
Cannot resolve scoped service '........' from root provider.

### Further technical details
.NET 5 / Windows 10 20H2 zh-CHS Business / IIS 10 / Visual Studio 2019

Here is "dotnet --info" output:
`.NET SDK (反映任何 global.json):
 Version:   5.0.102
 Commit:    71365b4d42

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   A:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.101 [A:\Program Files\dotnet\sdk]
  5.0.102 [A:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [A:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [A:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [A:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [A:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [A:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [A:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [A:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [A:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [A:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [A:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [A:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [A:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download`

Here is a smallest reproducible test:
[Lifetime Test.zip](https://github.com/dotnet/aspnetcore/files/5886273/Lifetime.Test.zip)

**Comment by davidfowl** [comment]
That's odd, it should fail in all cases.

**Comment by davidfowl** [comment]
I can't reproduce this:

![image](https://user-images.githubusercontent.com/95136/106172182-e4ea8580-6168-11eb-884b-01abbd031dd0.png)

Is it possible you're running in IIS in Production instead of development? We only turn on scope validation in development to avoid the performance hit at runtime in production.

**Comment by lujiaxing** [comment]
> I can't reproduce this:
> 
> ![image](https://user-images.githubusercontent.com/95136/106172182-e4ea8580-6168-11eb-884b-01abbd031dd0.png)
> 
> Is it possible you're running in IIS in Production instead of development? We only turn on scope validation in development to avoid the performance hit at runtime in production.

Yep. it's running in development.
![image](https://user-images.githubusercontent.com/7188738/106178799-2e70ba00-61d5-11eb-86bc-e7b69e39d77a.png)

Scope validation is truly closed in production mode.
But the program is also running under "IIS In-Process integration" in development mode. If scope validation is on in development mode, it should report the same error. Is that means IIS never read "launchSettings.json" ?

**Comment by lujiaxing** [comment]
> I can't reproduce this:
> 
> ![image](https://user-images.githubusercontent.com/95136/106172182-e4ea8580-6168-11eb-884b-01abbd031dd0.png)
> 
> Is it possible you're running in IIS in Production instead of development? We only turn on scope validation in development to avoid the performance hit at runtime in production.

Also, host this program in IIS and run.
It's sure to get this error by running "F5" or "dotnet run". But hosting in iis is another case.

**Comment by Tratcher** [comment]
https://github.com/dotnet/runtime/blob/a227f0053ee85c651a4c1a37075369eee5800bd6/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L128-L130

**Comment by davidfowl** [comment]
I can't reproduce this in your sample.

**Comment by lujiaxing** [comment]
> I can't reproduce this in your sample.

have you tried just host this project to iis? Don't publish, just set the website's path to the project's dir...

**Comment by davidfowl** [comment]
Full IIS? Does it repro in IIS express?

Are you sure it's running in development when you reproduce it? How about debugging and checking the current hosting environment? Can you do that and let me know what it is ?

**Comment by lujiaxing** [comment]
> Full IIS? Does it repro in IIS express?
> 
> Are you sure it's running in development when you reproduce it? How about debugging and checking the current hosting environment? Can you do that and let me know what it is ?

Sure. It's hosted by "Full IIS" in development mode.
Debug compile / IIS website pointed to project's source code directory.

In this case, it looks like IIS has ignored launchSettings.json and forced the application into production mode.

I did not try this in iis express. But I'll try it later

**Comment by davidfowl** [comment]
@lujiaxing can you show me an imagine in the debugger that shows the IWebHostEnvironment that says "Development"

**Comment by lujiaxing** [comment]
> @lujiaxing can you show me an imagine in the debugger that shows the IWebHostEnvironment that says "Development"


![image](https://user-images.githubusercontent.com/7188738/106354789-3cd2e900-632f-11eb-9c09-b781aa9e2935.png)

![image](https://user-images.githubusercontent.com/7188738/106354785-35abdb00-632f-11eb-8e7d-fbe3742c0398.png)

![image](https://user-images.githubusercontent.com/7188738/106354826-60962f00-632f-11eb-8fe2-3261291b9cdb.png)

**Comment by lujiaxing** [comment]
![image](https://user-images.githubusercontent.com/7188738/106355084-d6e76100-6330-11eb-93a4-d842b4fbc7da.png)
IIS Express reads launchSettings.json but IIS does not.

**Comment by BrennanConroy** [comment]
IIS does not read the launchSettings.json, this is the expected behavior.

You can set the ASPNETCORE_ENVIRONMENT environment variable in your web.config which will work in IIS.

**Comment by lujiaxing** [comment]
> IIS does not read the launchSettings.json, this is the expected behavior.
> 
> You can set the ASPNETCORE_ENVIRONMENT environment variable in your web.config which will work in IIS.

OK. it's clear. Thx
