### ISSUE TITLE
Investigate the impact of linking if views are compiled in to the app's assembly

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#29721]
A trimming follow up. This is to investigate what falls out if we turn on linking for ASP.NET Core apps when views are compiled in to the app's assembly

**Comment by pranavkm** [comment]
Parking this in preview5 since that's about the earliest we could start work in this area.

**Comment by mkArtakMSFT** [comment]
Closing as there is nothing concrete we're looking for in here.
