### ISSUE TITLE
Blazor Server circuit reconnect not working

### ISSUE THREAD

**Issue by nilssol** [dotnet/aspnetcore#29728]
### Describe the bug
Reconnect to circuit on mobile browsers doesnt work as expected. After locking the phone, and coming back some minutes later, the reconnect never happens. Either does the browser auto reload after page comes in focus (unblur/onfocusin) 

### Spec
Blazor Server (. Net 5) 
Version 5.0.2
IIS 10 hosted. (Win Srv. 2019)
Https and vaild cert.

**Comment by javiercn** [comment]
@nilssol thanks for contacting us.

Blazor server user sessions will go away after a few minutes when the client has disconnected the underlying SignalR connection. What's happening here is the mobile browser is stopping the connection when the the phone is locked and after a while the server will discard the session. When the client tries to reconnect, say 10 minutes later, the session is gone and the user needs to refresh the page to start a new session.

If you want the user to "resume" the session where they left of, you need to preserve the state for the session as describe [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=webassembly)

**Comment by nilssol** [comment]
It's no requirement to connect to the same circuit or save any session data, i just want the browser to auto refresh when the user unlock the phone. The experience now is that the user have to do a manual refresh.

There should be an option to activate this behavior without modifying the _host.cshtml.
(after modifying _host.cshtml, the login for iOS got broken)

**Comment by javiercn** [comment]
@nilssol what you are doing can be achieved by customizing the reconnection handler. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-5.0#modify-the-reconnection-handler) for details
