### ISSUE TITLE
Why Controller base class named as ControllerBase?

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#29723]
[Microsoft framework design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/base-classes-for-implementing-abstractions) stated that:

> ❌ AVOID naming base classes with a "Base" suffix if the class is intended for use in public APIs.

My question is: why the ASP.NET Core team violated their own guideline?

Secondly wouldn't the following design have been more meaningful?

```
// The base class for the MVC and API controllers which will contain all the common functionalities.
internal class Controller
{
}

// Will add the MVC specific functionalities and behaviour
public class MvcController: Controller
{
}

// Will add the API specific functionalities and behaviour
public class ApiController: Controller
{
}
```

Thank you.

**Comment by javiercn** [comment]
@TanvirArjel thanks for contacting us.

These things are not laws set in stone that can't be broken, as with any guideline there is a judgement call and that's what we decided on at the time, we don't have any plans to change it as it's not worth it compared to the painful breaking change this would create.

**Comment by TanvirArjel** [comment]
@javiercn Nothing wrong with breaking changes if it fixes any existing design mistake. More importantly, without breaking changes in some scenarios how a framework will evolve and move forward?
