### ISSUE TITLE
RazorPage: Add overload for IgnoreSection with required parameter

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/aspnetcore#29741]
## Summary

I have a layout where I want to ignore an optional section. There is currently no way to do this, IgnoreSection will always throw if the section is not defined.

## Detailed design

Mirror what we have for RenderSection onto IgnoreSection:

```csharp
public abstract class RazorPage
{
   // Existing API
   public HtmlString RenderSection(string name) {}
   HtmlString RenderSection(string name, bool required) {}
   public void IgnoreSection(string sectionName) {}

   // API Addition
   public void IgnoreSection(string sectionName, bool required) {}
}
```

**Comment by CodeBlanch** [comment]
Sorry about jumping the gun on the PR, it was just super simple to build I couldn't resist.

**Comment by javiercn** [comment]
@CodeBlanch thanks for contacting us.

I don't have anything against this addition, I'll let @pranavkm and other folks chime in if there's a reason why this could cause an issue.

**Comment by CodeBlanch** [comment]
Closing because we went with a design that doesn't require an API change.
