### ISSUE TITLE
Can not publish a project that use Razor sdk with <RazorCompileOnBuild>false</RazorCompileOnBuild>  

### ISSUE THREAD

**Issue by John0King** [dotnet/aspnetcore#29758]
### Describe the bug
`dotnet publish` failed (and vs ) when publish a Web Project  refrence a  Razor Sdk Project  and with `<RazorCompileOnBuild>false</RazorCompileOnBuild>`  options.
it's saids `can not find the <project>.view.pdb`  of the razor sdk project

### To Reproduce
- a main asp.net core web project `ProjectA`
- a razor sdk project  contains mvc's controller and views  `ProjectB`
- `ProjectA` reference `ProjectB`
- both ProjectA and ProjectB  add `<RazorCompileOnBuild>false</RazorCompileOnBuild>`
- [optional]  add `RuntimeRazorCompilation`  for both project
- publish the `projectA`

### Exceptions (if any)
publish faild   :   copy file failed because `xxxx.view.pdb` can not be found.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
.NET SDK (反映任何 global.json):
 Version:   5.0.102
 Commit:    71365b4d42

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is already fixed in the most recent 6.0 preview release.
