### ISSUE TITLE
Why dotnet core for Linux does not accept more than one service running at the same time

### ISSUE THREAD

**Issue by thisisjagan** [dotnet/aspnetcore#29766]
### Describe the bug
I have a ASP Dotnet Core Web Api running on port 8008 in a Linux Server under the service. I am trying to host another Web API on port 8009 by creating another service. However when one service is running, another does not. It fails with the following error.

MySecondService.service - MySecond API
   Loaded: loaded (/etc/systemd/system/MySecondAPI.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: core-dump) since Fri 2021-01-29 15:18:52 UTC; 3s ago
  Process: 8757 ExecStart=/usr/bin/dotnet /home/vhost/www/MySecondAPI/MySecondAPI.dll (code=dumped, signal=ABRT)
 Main PID: 8757 (code=dumped, signal=ABRT)

### To Reproduce
Deploy a ASP .Net Core 3.1 Web API in Linux Cent OS as a service and start it. Once it is started, deploy another ASP .Net Core 3.1 Web API and ensure it is configured to run on a different port.

### Exceptions (if any)
MySecondService.service - MySecond API
   Loaded: loaded (/etc/systemd/system/MySecondAPI.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: core-dump) since Fri 2021-01-29 15:18:52 UTC; 3s ago
  Process: 8757 ExecStart=/usr/bin/dotnet /home/vhost/www/MySecondAPI/MySecondAPI.dll (code=dumped, signal=ABRT)
 Main PID: 8757 (code=dumped, signal=ABRT)

### Further technical details
- ASP.NET Core version 3.1
- OS Version: 4.18.0-193.28.1.el8_2.x86_64 GNU/Linux
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

### Service Configuration
[Unit]

Description=My Second API

[Service]

WorkingDirectory=/home/vhost/www/MySecondAPI

ExecStart=/usr/bin/dotnet /home/vhost/www/MySecondAPI/MySecondAPI.dll

Restart=always

RestartSec=10

SyslogIdentifier=MySecondAPI

User=azureuser

Environment=ASPNETCORE_ENVIRONMENT=ppe

Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

[Install]

WantedBy=multi-user.target

**Comment by Tratcher** [comment]
What do the server logs say?

**Comment by thisisjagan** [comment]
I have figured out the problem. The problem was with the port binding. Though I gave a different port, the executable was picking up the port from a different appsettings.json file due to the Environment variable. After updating the port, it works fine now. Thank you so much the for the help.
