### ISSUE TITLE
dotnet-format breaks partial commits

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#29768]
I've been noticing some weirdness today. When I try to commit a subset of the files I've modified, or a subset of the lines within those files, sometimes my other modifications get committed too. This is causing some havoc with my coding workflow, making me think I was making all kinds of weird mistakes... :)

Looking at `.githooks\pre-commit`, it doesn't appear to account for partial commits - it just fully adds all the files it touches. Am I missing something here that's supposed to make this work?

I'm disabling it locally for now.

**Comment by adrianwright109** [comment]
@ryanbrandenburg - making you aware of this issue as you added the same `.githooks\pre-commit` to the [dotnet/aspnetcore-tooling](https://github.com/dotnet/aspnetcore-tooling) repo in commit [6d9eb71](https://github.com/dotnet/aspnetcore-tooling/pull/2984/commits/6d9eb7139b2252002dc9641002b477c6c8dc546e)

**Comment by SteveSandersonMS** [comment]
@javiercn Do you have a suggestion about what we should do about this? I’ve been fighting it for the last couple of weeks but it’s a drag. Breaking git defaults is pretty rough on contributors.

**Comment by javiercn** [comment]
I think I putted it up for discussion on DoI, but let me see if there's something quick we can do.

**Comment by javiercn** [comment]
@SteveSandersonMS Is this partial commit as in you have a file that is partially "staged"? (Some changes on the file are staged but some other aren't?)

**Comment by SteveSandersonMS** [comment]
It’s using the GitHub Desktop client, and selecting a subset of the lines to include in the commit.

**Comment by javiercn** [comment]
> It’s using the GitHub Desktop client, and selecting a subset of the lines to include in the commit.

Cool, I think I figured out the way, give me 30 min

**Comment by javiercn** [comment]
@SteveSandersonMS [this](https://github.com/dotnet/aspnetcore/pull/30134) should work. Can you give it a try on your box? (I did on mine and works fine)
