### ISSUE TITLE
Blazor Based Identity User Interface

### ISSUE THREAD

**Issue by scottkuhl** [dotnet/aspnetcore#29774]
The current identity interface defaults to the MVC / Razor Page model.

I would like to see these pages better integrated as Blazor components instead on a Blazor project including similar default design.

**Comment by scottkuhl** [comment]
I apologize if this has already been proposed someone.  I looked for it and could not find it.

**Comment by javiercn** [comment]
@scottkuhl thanks for contacting us.

This has indeed already been asked in the past, but I can't find the original issue.

We don't plan to offer a Blazor version of the default identity UI, it adds a significant development and maintenance cost for us and there is nothing wrong with using the existing UI or customizing it to suit your needs.

**Comment by scottkuhl** [comment]
_nothing wrong with using the existing UI_

Except that the default user interface and interaction model does not match Blazor at all.  

_customizing it to suit your needs._

Which pushes the work downstream to hundreds or thousands of projects using the template.

I have to say I don't agree with not updating such a fundamental piece of the template just because it requires work.  The existence of the identity template and its natural integration into ASP.NET is one of the benefits of the platform.

This should be updated.  It sticks out just like non-updated apps on Windows when Microsoft makes a UI shift and doesn't update its UI across the board.
