### ISSUE TITLE
ASP.NET Core Identity's GetExternalLoginInfoAsync method uses a hard-coded "Identity.External" scheme. An overload should be provided to accept a user-specified scheme.

### ISSUE THREAD

**Issue by felinepc** [dotnet/aspnetcore#29772]
## Summary

The ```SignInManager.GetExternalLoginInfoAsync``` method in ```Microsoft.AspNetCore.Identity```  is designed to obtain the external login information from the current user's external ```AuthenticationResult```. It should not do so using a hard-coded scheme.

## In scope

Source code for ```GetExternalLoginInfoAsync```:
```
public virtual async Task<ExternalLoginInfo> GetExternalLoginInfoAsync(string expectedXsrf = null)
{
    var auth = await Context.AuthenticateAsync(IdentityConstants.ExternalScheme);

   //... ...
}
```

As the code shows, the ```AuthenticationResult``` is hard-coded to be obtained from the default ```IdentityConstants.ExternalScheme``` scheme, which represents the string "Identity.External". 

This is problematic because the application's external authentication scheme is often customized, especially when Identity is integrated with a 3rd-party authentication middleware such as ```IdentityServer``` that defines their own external schemes, making the method unusable.

The method should therefore provide an overload that accepts a user-specified authentication scheme.

## Risks / unknowns

None.

**Comment by blowdart** [comment]
What actual problem are you seeing? The external auth scheme here isn't the end result, it's a temporary scheme used to marry things together for auth types that move off a site and come back again, before the sign-in completes.

**Comment by felinepc** [comment]
I first came across this method while trying to use ```SignInManager.UpdateExternalAuthenticationTokensAsync```, which takes an ```ExternalLoginInfo``` parameter, which ```GetExternalLoginInfoAsync``` returns. So I suspect that ```GetExternalLoginInfoAsync``` was designed to be a quick helper method to provide this. But I soon found that it didn't work because it was written to get it from the hard-coded scheme. So the only choice is to construct ```ExternalLoginInfo``` manually. I mean it's not a big deal because that's all the method was written to do, but I just figured that it would be nice if it didn't attempt to do so from a fixed scheme.

Yes the external auth scheme is temporary, but some workflows need to extract some information from that cookie before it's deleted. I assume that's why these helper methods mentioned above exist.

**Comment by blowdart** [comment]
The method is just syntatical sugar though, used by our UI. There's no reason you must use it yourself, and the scheme names are implementation details. I don't really see a problem to be solved here I'm afraid.

There's nothing inside that cookie that needs extracting, it doesn't contain anything from the external login information or token, it's mainly a correlation cookie. What workflow do you have that needs to extract information from it that isn't already available in the oauth events?

**Comment by felinepc** [comment]
When ```SaveTokens = true``` is set in the OIDC client middleware, the identity/access/refresh tokens returned by the external providers will be written to that cookie. ```UpdateExternalAuthenticationTokensAsync``` provides an easy way to persist these cookies, and it takes an ```ExternalLoginInfo``` which can be returned from ```GetExternalLoginInfoAsync```.

That's my understanding of the purpose of these methods. Yes you're correct we don't have to use the specific ```GetExternalLoginInfoAsync``` method as we can manually construct the ```ExternalLoginInfo``` using the correct ```AuthenticateResult``` the same way ```GetExternalLoginInfoAsync``` does. It's just that I found it strange that the method chose to hard code the scheme name of the external authentication when it was designed to be customizable.

BTW I do see a few posts on StackOverFlow and Github of people mentioning this behavior, so figured I'd make a post here.

Please feel free to close this if you feel the issue does not warrant any change.

**Comment by blowdart** [comment]
As of now, as there are ways to get the information from the external login, we don't see any need for changes. So, with your agreement closing.
