### ISSUE TITLE
Blazor Inheritance Page Cycle Issues

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29783]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-Inheritance-Page-Cycle-Issues/1312189)._

---
[severity:It's more difficult to complete my work]
Building a Blazor Application where I am using an Abstract BaseClass for all my components.  BaseClass inherits from OwningComponentBase.  When I use OnInitializedAsync, I load data and at the end call base. OnInitializedAsync.  I started running into issues related to my Authenticated Checks.  In BaseClass, I have the OnInitializedAync coded to check the Authentication so that child classes based on BaseClass don't have to have that code.  What I realized is, BaseClass OnInitializedAsync gets called after child component is build and I am not understanding why that is the case.  Please correct me if I am wrong, but isn't the Parent code supposed to run first or is this by design.  I would just really like to know how to call this correctly.  Thanks.

Take Care and Have a Great Day.

Charles E. Walk Jr.
CEO
Art In The Raw
(357-9686)
*@yyy

---
#### Feedback Bot on 1/17/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mrpmorris** [comment]
The first time you await, the component will continue and render. So your mark up had to cater for rendering a component that doesn't yet have all of its state

**Comment by javiercn** [comment]
Thanks for contacting us.

@mrpmorris answer here is correct. there are more docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0) but they seem to be a bit wrong.

**Comment by mrpmorris** [comment]
I prefer my docs :)

https://blazor-university.com/components/component-lifecycles/
