### ISSUE TITLE
Asp.Net Core v3.1 Debugging Where are Compiled files stored

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29782]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/AspNet-Core-v31-Debugging-Where-are-Co/1312301)._

---
[severity:It's more difficult to complete my work]
Dear Sirs,

I am using Visual Studio 16.8.4.
I am developing an ASP.Net Core 3.1 MVC application, using various "static" files (Javascript and CSS).

When using Kestrel for debugging my application, sometimes a specific javascript file is not updated?
My IDE for Javascript files is set to "Content" and "Copy Always"
When viewing the raw javascript file in the IDE it is correct;
However, when running with "Ctrl+F5" and using the browser to navigate to the file, the file content is incorrect.

How could this be resolved please?

Thanks

Dave

---
#### Feedback Bot on 1/26/2021, 05:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We don't have enough details to give you an answer. I would suggest navigating to the page within incognito mode or using MSBuild binary log viewer to try and determine whether the files are actually being copied.
