### ISSUE TITLE
Blazor control does not have CSS file style applied

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29780]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/BlazorコントロールにCSSファイルのスタイルが適用されない/1322306)._

---
[severity:I'm unable to use this version]
I described the page in Test.razor and .css in Test.razor

[Test.razor]
<EditForm>
    <InputText class="my_style" />
</EditForm>

[Test.razor.css]
.my_style
{
    width: 100%
}

does not my_style the style of the file

Note that < input class="my_style" />
my_style style is applied

If you check the elements in the browser's developer tools,
 <InputText class="my_style" /> has been converted to <input class="my_style valid" />
On the other <, input class="my_style" /> has been converted to <input class="my_style" [String] />

By the way, if you copy and paste [String] and set <input class="my_style valid" [String] />.
Styles are applied

---
#### Feedback Bot on 1/27/2021, 07:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

CSS isolation only affects **HTML elements** on the same razor file they are being used. It does not affect other components, since the goal is that those components can have their CSS isolated and affecting them would defeat the purpose.

@guardrex can we add a remark on the docs for this? It seems to trip a few people.

**Comment by guardrex** [comment]
I thought we already had it (and is in the process of a small language+example update on https://github.com/dotnet/AspNetCore.Docs/pull/21378) as ...

> The styles defined in `Example.razor.css` are only applied to the rendered output of the `Example` component. Any `h1` CSS declarations defined elsewhere in the app don't conflict with the `Example` component's styles.

... and there might be one more line in the text that makes the point.

@daveabrock ... Do you want to look and see if/how it's covered and see if additional work can further address this, or should I take a look? Either way, I figure your open PR is a timely for something else, if needed.

**Comment by javiercn** [comment]
@guardrex I haven't looked at the docs recently, but we keep receiving this type of issue, so just want to make sure it's covered and visible.

**Comment by guardrex** [comment]
There is a way to **_strengthen_** 💪 the point ... a full sentence **in bold** to surface it. Dave, if you're going to take a look at this for the open PR, consider bolding a full sentence to cover this. AFAICT, readers don't seem to miss a concept when handled that way.

**Comment by daveabrock** [comment]
OK, I'll add something to the open PR.
