### ISSUE TITLE
Unable to Restore the v5.0.2, v5.0.1 and v.5.0.0

### ISSUE THREAD

**Issue by huazhb** [dotnet/aspnetcore#29797]
Download the source for v5.0.2, v5.0.1 and v5.0.0 and use the Restore.cmd to restore the solution, but they all failed. 
**For v5.0.2, it report:**
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.2-servicing.20611.20/dotnet-runtime-5.0.2-servicing.20611.20-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.2-servicing.20611.20/dotnet-win-x64.5.0.2-servicing.20611.20.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.2-servicing.20611.20/dotnet-runtime-5.0.2-servicing.20611.20-win-x86.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.2-servicing.20611.20/dotnet-win-x86.5.0.2-servicing.20611.20.zip
**For v5.0.1, it report:**
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.1-servicing.20575.16/dotnet-runtime-5.0.1-servicing.20575.16-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.1-servicing.20575.16/dotnet-win-x64.5.0.1-servicing.20575.16.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.1-servicing.20575.16/dotnet-runtime-5.0.1-servicing.20575.16-win-x86.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.1-servicing.20575.16/dotnet-win-x86.5.0.1-servicing.20575.16.zip
**For v5.0.0, it report:**
\source\aspnetcore\artifacts\toolset\restore.proj : error : Unable to load the service index for source https://dotnet.myget.org/F/roslyn/api/v3/index.json.
\source\aspnetcore\artifacts\toolset\restore.proj : error : Unable to load the service index for source https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json.

**Comment by wtgodbe** [comment]
@huazhb were you able to try out Matt's suggestion from the above comment?

**Comment by huazhb** [comment]
@wtgodbe I clone the source to a clean folder and 5.0.6 are working. 5.0.0 and 5.0.2 still have the same issue and I think 
 5.0.6 is good enough for me now. Thank you very much @dougbu @mmitche
