### ISSUE TITLE
Blazor (WASM): JS Isolation Module Import can only be run asynchronously?

### ISSUE THREAD

**Issue by braidenstiller** [dotnet/aspnetcore#29808]
### Describe the bug
In Blazor WASM the `IJSInProcessRuntime`, `IJSInProcessObjectReference`, `Invoke` and `Invoke<T>` allow us to execute code and store js object ref's synchronously. 

Following the JS Isolation guide here we an see it implemented asynchronously, but with no mention a limitation to not do this synchronously in WASM:
https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references

It even mentions use of `IJSInProcessObjectReference` in synchronous applications.

Therefore we could assume that the js "import" function can also be run synchronously with `IJSInProcessRuntime.Invoke<T>` however this doesn't seem to work. No errors are thrown until you try to execute a function on the js module, where it throws an error. Changing this to `InvokeAsync<T>` works (even while using `IJSInProcessRuntime` and `IJSInProcessObjectReference`).

### To Reproduce

```
       // Inject JS Runtimes 
        [Inject]
        private IJSRuntime JSRuntime { get; set; } = default!;

        private IJSInProcessRuntime JSInterop => (IJSInProcessRuntime)this.JSRuntime;

        protected override async Task OnInitializedAsync()
        {
            // This works
            var module = await this.JSInterop.InvokeAsync<IJSInProcessObjectReference>("import", "./js/foo.js");
            var bar = module = this.ViewerInterop.Invoke<IJSInProcessObjectReference>("barFunction");

            // This does not work
            var module = this.JSInterop.Invoke<IJSInProcessObjectReference>("import", "./js/foo.js");
            var bar = module = this.ViewerInterop.Invoke<IJSInProcessObjectReference>("barFunction");

            await base.OnInitializedAsync();
        }
```

### Exceptions (if any)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'barFunction' ('barFunction' was undefined).
      Error: Could not find 'barFunction' ('barFunction' was undefined).
```

### Further technical details
- ASP.NET Core version: 
.NET 5.0

- Include the output of `dotnet --info`
  .NET SDK (reflecting any global.json):
   Version:   5.0.101
   Commit:    d05174dc5a
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19041
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\5.0.101\
  
  Host (useful for support):
    Version: 5.0.1
    Commit:  b02e13abab
  
  .NET SDKs installed:
    3.1.401 [C:\Program Files\dotnet\sdk]
    5.0.100 [C:\Program Files\dotnet\sdk]
    5.0.101 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio Community 16.8.3

**Comment by javiercn** [comment]
@braidenstiller thanks for contacting us.

Importing a module dynamically requires a network request so it can only be achieved asynchronously.

@guardrex can you add this to the docs on JS isolation?
