### ISSUE TITLE
When the Razor view path changes, how do I keep and remove one?

### ISSUE THREAD

**Issue by hueifeng** [dotnet/aspnetcore#29811]
## Summary 

I want to use the `TargetName` as the prefix of the DLL directory file to generate a directory in this format. Yes, I can generate this modular structure (directory prefixed by the project name), but I found that after generating it through MSBuild , I got two identical documents, I think this file is too big, can I directly modify the generated directory? Or can I remove the metadata?

![image](https://user-images.githubusercontent.com/34702552/106418593-b256ca80-6491-11eb-9f42-a49f3f05f314.png)

## Steps

I want to change the structure of my project when it is generated, the following is the original file structure:

``` csharp
Application
├── Program.cs
└── Startup.cs
Pages
├── Shared
│   └── _Layout.cshtml
└── Index.cshtml
└── Error.cshtml
....
```
I want to change its directory structure to:

``` csharp
MyLibrary
  Application
    ├── Program.cs
    └── Startup.cs
    Pages
    ├── Shared
    │ └── _Layout.cshtml
    └── Index.cshtml
    └── Error.cshtml
....
```

By default, the Razor SDK uses MSBuild metadata to calculate the relative path of a project. We can set the Link file's metadata so that we can use the view engine path prefixed with the project name:

```
  <Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
    <ItemGroup>
      <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />
    </ItemGroup>
  </Target>
```

Yes, I can do so, but it will cause the size of my DLL file to increase.I can see in obj file:

```csharp
├── MyLibrary
	├── Pages
      ├── Shared
      │ └── _Layout.cshtml
      ├── Index.cshtml
      └── Error.cshtml
├── Pages
	├── Shared
    │ └── _Layout.cshtml
    ├── Index.cshtml
    └── Error.cshtml
```

Yes, now it is the same two files, I want to remove the metadata from the DLL, how do I do it?

**Comment by hueifeng** [comment]
I'm sorry, I added the wrong state, it should be one Question, not design-proposal.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not a mainline scenario that we support. We recommend asking this question in [StackOverflow](https://stackoverflow.com) to get a  quicker response.
