### ISSUE TITLE
Multi-nested Razor/C# mis-formatted

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#29837]
```razor

@code {
    private WeatherForecast[] forecasts;

    protected override async Task OnInitializedAsync()
    {
        <Counter>
            @{
                    var t = DateTime.Now;
                    t.ToString();
                }
            </Counter>
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }
}
```
Ctrl-K-D the above and see that it keeps the wonky formatting. If you type it out that way it will auto-format  into this shape.

**Comment by NTaylorMullen** [comment]
@davidwengier also magically fixed this!

**Comment by davidwengier** [comment]
I tried to add a test to prevent regression of this, but it failed, and I can still repro the formatting issue in Version 17.0.0 Preview 2.0 [31427.69.main].

Going to reopen.

**Comment by NTaylorMullen** [comment]
> I tried to add a test to prevent regression of this, but it failed, and I can still repro the formatting issue in Version 17.0.0 Preview 2.0 [31427.69.main].
> 
> Going to reopen.

Oh wow, I wonder what on my box made it not, we should sync to see if this is maybe indicative of a setting difference
