### ISSUE TITLE
onTypeRename Does Not Work in Codespaces

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#29836]
![OnAutoRename](https://user-images.githubusercontent.com/14852843/106526573-b89d7480-649a-11eb-8960-5f8cc02feced.gif)

Original PR: https://github.com/dotnet/aspnetcore-tooling/pull/2795

**Comment by TanayParikh** [comment]
@alexgav / @ToddGrun do you know if this is expected to be supported in the codespaces env?

fyi/ @NTaylorMullen

**Comment by ToddGrun** [comment]
> @alexgav / @ToddGrun do you know if this is expected to be supported in the codespaces env?

I'm not sure why it wouldn't.

**Comment by NTaylorMullen** [comment]
No longer applicable.
