### ISSUE TITLE
Deeply nested implicit C# brackets do not colorize in codespaces

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#29838]
```razor
@code {
    private WeatherForecast[] forecasts;

    protected override async Task OnInitializedAsync()
    {
        <Counter>
            @{
                    var t = DateTime.Now;
                    t.ToString();
                }
            </Counter>
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }
}

```

![](https://user-images.githubusercontent.com/14987221/106526758-01552d80-649b-11eb-91e4-3c544349feec.png)
On the Codespaces client we can see that the above bracket (line 10) doesn't get colorized like its opener.

**Comment by ryanbrandenburg** [comment]
Interestingly the bracket colorization thing doesn't happen on Livespace server or on Local (Could TextMate be hiding Semantic failings?

**Comment by NTaylorMullen** [comment]
No longer applicable
