### ISSUE TITLE
Building IIS test assets results in file contention

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#29844]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=974192&view=results
Error:
```
Unhandled exception. System.IO.IOException: The process cannot access the file 'F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\bin\Release\net6.0\InProcessWebSite.deps.json' because it is being used by another process.
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
     at System.IO.StreamWriter..ctor(String path, Boolean append)
     at System.IO.File.CreateText(String path)
     at TestTasks.InjectRequestHandler.Main(String[] args) in F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\TestTasks\InjectRequestHandler.cs:line 81
F:\workspace\_work\1\s\src\Servers\IIS\build\testsite.props(70,5): error MSB3073: The command "dotnet F:\workspace\_work\1\s\src\Servers\IIS\build\..\IIS\test\testassets\TestTasks\bin\Release\net6.0\TestTasks.dll "F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\bin\Release\net6.0\InProcessWebSite.deps.json"  " exited with code -532462766. [F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\InProcessWebSite.csproj]
##[error]src\Servers\IIS\build\testsite.props(70,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command "dotnet F:\workspace\_work\1\s\src\Servers\IIS\build\..\IIS\test\testassets\TestTasks\bin\Release\net6.0\TestTasks.dll "F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\bin\Release\net6.0\InProcessWebSite.deps.json"  " exited with code -532462766.
```

Looks like the IIS test asset build is flaky. It would be good to fix this but so far it hasn't been failing very frequently.

**Comment by dougbu** [comment]
@JunTaoLuo was this issue addressed❔ @jaredpar is `runfo` restored enough to search build logs for recent errors of this ilk❔

**Comment by jaredpar** [comment]
@dougbu looks like one recent hit 

https://runfo.azurewebsites.net/search/timelines/?q=started%3A%7E7+definition%3Aaspnetcore-ci+message%3AMSB3073+kind%3A%21pr

**Comment by dougbu** [comment]
Thanks for looking @jaredpar❕ That instance was about Microsoft.AspNetCore.Server.Kestrel.pdb and not the InProcessWebSite.deps.json file. Couldn't find a relevant mention of `.deps.json` in the past 14 days.

@JunTaoLuo thoughts on expanding this issue to cover build ordering issues in general❔ If I understand the term correctly, `msbuild` "double writes" might be at the root of such issues and we could use a binary log or two to track them down.

If we don't do that, there's nothing around to investigate more fully and we should close this issue. Unless of course someone saved a binary log from https://dev.azure.com/dnceng/public/_build/results?buildId=974192❔

**Comment by dougbu** [comment]
Enough time has passed that this particular issue seems to have cleared up. On the other hand, file contention has come up in recent PRs and discussions of failed rolling builds _more_ often that in the past. @JunTaoLuo since you're the lucky person on blops today, please file a general issue -- mingling any other open issues about the new versions of this issue.
