### ISSUE TITLE
New Razor editor: Go to definition does not work for components defined in a Razor library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29841]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/New-Razor-editor:-Go-to-definition-does-/1322451)._

---
[severity:Other]
Trying the new Razor editor in VS 2019 16.9 preview 3, having the experimental features turned on in Tools| Options. 
The announced function "Go to component definition" function (F12) does not work if the component has been defined in a referenced Razor library.

Steps to reproduce:
1. create a new Blazor project (server-side) using the default template
2. open Index.razor, put the <Counter /> component. Try the "Go to definition" function on the component. It correctly opens the definition of the component in Counter.razor. So far ok.
3. add a new Razor lib project to the solution. It will by default contain the Component1.razor component. Reference the Razor lib in the Blazor project
4. add the Component1.razor to the Index.razor page. Try "Go to definition" on the component - it does not work (it does nothing)

More observations: I have tried the following scenarios, none of them works -

- Added the component as <RazorClassLibrary1.Component1 /> ... did not work
- Added the component as <Component1 /> and added @using RazorClassLibrary to the Index.razor ... did not work
- Added the component as <Component1 /> and added @using RazorClassLibrary to the _Imports.razor ... did not work

---
#### Feedback Bot on 1/27/2021, 09:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
@NTaylorMullen Is this expected to not currently work in the new editor? I noticed this is marked as "enhancement" but from testing it seems like everything actually works correctly, even in older VS versions like 16.9.6.

**Comment by allisonchou** [comment]
Addressed by https://github.com/dotnet/aspnetcore-tooling/pull/3665
