### ISSUE TITLE
Blazor Server InputFile Issue - File Size Exceed the maximum of 512000 bytes

### ISSUE THREAD

**Issue by saroshwadia** [dotnet/aspnetcore#29859]
Hi!

In a .NET 5.0 / C#9 Blazor Server App I'm trying to Upload files to the "www/Upload" Folder using the built-in "InputFile" Component.

Everything works with small files but if the file size is over 512000 bytes, I get the following error "http://System.IO.IOException: Supplied file with size 16062787 bytes exceeds the maximum of 512000 bytes."

-------------------
@page "/FileUpload"
@using System.IO
@using System.Linq
@using System.Threading
@using Microsoft.AspNetCore.Hosting
@inject IWebHostEnvironment env

<h3>File Upload</h3>

<div class="form-group row">
    <InputFile class="btn btn-information" multiple OnChange="OnInputFileChange" />    
</div>

<div class="form-group row">
    <div class="col-md-3">
        <button class="btn btn-primary btn-block" @onclick="OnFileUpload">Upload</button>
    </div>
</div>

<br />
<label>@Message</label>
<br />
<div class="image-list">
    <table class="table table-bordered">
        <tr>
            @foreach(var imageData in imageDataUrls)
            {
                <td class="text-center">
                    <p><b>@imageData.FileName</b></p>
                </td>
            }
        </tr>
    </table>
</div>

@code
{
    List<SelectedFileInfo> imageDataUrls { get; set; } = new();
    IReadOnlyList<IBrowserFile> selectedImages;
    string Message = string.Empty;

     protected override void OnInitialized()
    {
        base.OnInitialized();        
    }
  
    private async Task OnInputFileChange(InputFileChangeEventArgs e)
    {
        var Counter = 0;
        selectedImages = e.GetMultipleFiles();

        foreach(var imageFile in selectedImages)
        {
            imageDataUrls.Add(new SelectedFileInfo { ImageDataUrl = "", FileName = $"{++Counter} {imageFile.Name}"});
        }

        await Task.FromResult(true);
    }

    private async Task OnFileUpload()
    {
        var RootFolder = Path.Combine(env.WebRootPath, "Upload");
        var FileName = string.Empty;
        var FullFileName = string.Empty;

        foreach(var file in selectedImages)
        {
            FileName = file.Name;
            FullFileName = Path.Combine(RootFolder, FileName);
            
            Stream stream = file.OpenReadStream();
            FileStream fs = File.Create(FullFileName);
            await stream.CopyToAsync(fs);
            fs.Close();
        }

        Message = $"{selectedImages.Count} File(s) Uploaded...";
        StateHasChanged();
    }

    public class SelectedFileInfo
    {
    public string FileName { get; set; }
    public string ImageDataUrl { get; set; }
    }
}
-------------------

Thanks

**Comment by pranavkm** [comment]
From https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0#inputfile-component,

> The Stream returned by OpenReadStream enforces a maximum size in bytes of the Stream being read. By default, files no larger than 512,000 bytes (500 KB) in size are allowed to be read before any further reads would result in an exception. This limit is present to prevent developers from accidentally reading large files in to memory. The maxAllowedSize parameter on Microsoft.AspNetCore.Components.Forms.IBrowserFile.OpenReadStream can be used to specify a larger size if required.

**Comment by harveymw27** [comment]
@saroshwadia you need to provide a maxAllowedSize like this:

Stream stream = file.OpenReadStream(MAXALLOWEDSIZE);

**Comment by saroshwadia** [comment]
Yes, that worked :-)
