### ISSUE TITLE
Issue while running self contained executable on WSL2

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/aspnetcore#29852]
### Describe the bug
I'm facing a weird scenario. I have a ASP.NET core project. I was first trying to execute the same as Self contained deployed exe on Ubuntu. I was able to publish the file. While running the executable generated via self contained deployment via WSL I did the following

1. chmod 777 ./<<executable name>>
2.  ./<<executable>>

It just runs for some time and exits. I expect the code to open a port and launch and listen to the request. Then I gave exec ./<<executable>> whole WSL process crashes. It exists out of ubuntu shell.

proceeding further, I installed ASP.NET core core in the WSL. I did a frame dependent deployment and it started working. This looked very puzzling. 

### To Reproduce
There is no specific steps to re produce this as the executable is enterprise contained. All I'm looking for now as a first stage is there some way I can gather some logs for this scenario from WSL

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019

**Comment by javiercn** [comment]
@VenkateshSrini thanks for contacting us.

Are you able to reproduce this issue with a brand new project template?

**Comment by VenkateshSrini** [comment]
@javiercn ,
That seems to run fine without any issues

**Comment by javiercn** [comment]
@VenkateshSrini I would suggest that as a first step you turn on logs to the highest level and see if there is anything in the logs output.

**Comment by VenkateshSrini** [comment]
@javiercn ,

Tried that also. Application does not seem to even get launched

**Comment by javiercn** [comment]
Have you tried to print a line on the first statement of the program to see if that's the case?

**Comment by VenkateshSrini** [comment]
@javiercn ,
Very interesting finding. If we do not a self contained single file deployment the application is launching. But we do a self contained single file deployment it is not working. When we logged extensively we found that application is trying to load a log4net.config. The error that is logged is 
_2021-02-03 18:39:22,119 [ERROR] FEGO_DotNet_to_DotNetCore.Program - MESSAGE: Could not find file '/var/tmp/.net/venkat/FEGO-DotNet-to-DotNetCore/avonx3aw.3ex/log4net.config'._ 
 Actually inside the code we are trying to load the same using the piece of code 
`Path.Combine(Directory.GetCurrentDirectory(), "log4net.config")` 
The file is very much there but for some reason the self contained single file deployment is always looking up it **/var/tmp/.net/venkat/FEGO-DotNet-to-DotNetCore/avonx3aw.3ex/log4net.config** Any insights on this will be helpful

**Comment by javiercn** [comment]
@VenkateshSrini make sure you are following the guidance [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#exclude-files-from-being-embedded)

**Comment by VenkateshSrini** [comment]
@javiercn ,
Thanks that helped the issue was that when adding the logging.AddLog4net, the best practice is to provide the path of the file by using the overloaded method, otherwise it starts performing the search in a place where the path variable sets and excludes the current working directory. Doing that fixed the issue. Thanks for your guidance.
