### ISSUE TITLE
SignalR stop sending ping messages without any reason and error (typescript)

### ISSUE THREAD

**Issue by mikhail-khalizev** [dotnet/aspnetcore#29851]
Hi.

We using latest version `"@microsoft/signalr": "^5.0.2"` with simple code:

```
    this.connection = new signalR.HubConnectionBuilder().withUrl(MERCHANT_API_URL, {
      accessTokenFactory: () => localStorage.getItem('bearer'),
    }).withAutomaticReconnect().build();
    this.connection.keepAliveIntervalInMilliseconds = 5000;
    this.connection.start().catch(err => console.log(err));
```

And we constantly have problems with disconnection. And the main version is that the client stops sending ping messages, as a result of which the server disconnects the client:

![image](https://user-images.githubusercontent.com/18654696/106600819-f8805c80-656b-11eb-9544-dc8a184ffb83.png)

We tried the latest versions of Chrome and Firefox.

And we do not receive any errors in browser console.

**Comment by mikhail-khalizev** [comment]
Do you have any ideas why the client might stop sending ping messages?

**Comment by mikhail-khalizev** [comment]
Another screenshot:
![image](https://user-images.githubusercontent.com/18654696/106603073-e653ed80-656e-11eb-951a-2b94b3c04735.png)

**Comment by mikhail-khalizev** [comment]
Sorry, it looks like we found a bug on our side.
From time to time, on a timer, we started a script that consumed 100% cpu and worked up to 30 seconds. What did not allow the rest of the logic to work out

**Comment by roks0n** [comment]
For anyone who might be experiencing a similar issues (but does not have CPU usage), Chrome started to throttle timers since v88 when a tab becomes inactive:

```
All of the following conditions need to be true in order for the 1 minute throttling to happen :
- Page has been hidden for more than 5 minutes.
- Chain count while applying setTimeout() / setInterval() methods is greater than 5.
- Page has not made any sound using any of the sound-making APIs.
- WebRTC is not in use.
```

Source:
- https://usefulangle.com/web-updates/post/110/chrome-88-will-throttle-timers-1-minute
- https://developer.chrome.com/blog/timer-throttling-in-chrome-88/
