### ISSUE TITLE
[Blazor] Error with information splitting into different pages on DataTable

### ISSUE THREAD

**Issue by Darkside32** [dotnet/aspnetcore#29850]
### Describe the bug
I'm currently having a problem with Datatables creating a error when information is split into pages in the tableand you select a row. When the information can fit into one page (increasing table limit), it works even if you lower the limit back into 2 > pages. Once the click happens, Blazor throws out a Unhandled exception and make the webpage unresponsive.

### To Reproduce

**Information Displaying on DataTable**

`   

<tbody>
                            @foreach (var order in orders)
                            {
                               
                                    if (selectedOrder != null)
                                    {
                                        if (order.Key == selectedOrder.Key)
                                        {

                            <tr class="selected" @onclick="@(() => SelectedFunction(order.Key))">

                                <th scope="row">@order.Key</th>
                                <td>@order.Cust_Name</td>
                                <td>@order.Haulier_Name</td>
                                <td>@order.Driver_Name </td>
                                <td>@order.CollectionDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                                <td>@order.CollectionTown</td>
                                <td>@order.DeliveryDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                                <td>@order.DeliveryTown</td>
                                <td>@order.Reference</td>
                            </tr>

                                        }
                                        else
                                        {
                            <tr class="" @onclick="@(() => SelectedFunction(order.Key))">
                                <th scope="row">@order.Key</th>
                                <td>@order.Cust_Name</td>
                                <td>@order.Haulier_Name</td>
                                <td>@order.Driver_Name </td>
                                <td>@order.CollectionDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                                <td>@order.CollectionTown</td>
                                <td>@order.DeliveryDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                                <td>@order.DeliveryTown</td>
                                <td>@order.Reference</td>
                            </tr>
                                        }
                                    }
                                    else
                                    {
                            <tr class="" @onclick="@(() => SelectedFunction(order.Key))">

                                <th scope="row">@order.Key</th>
                                <td>@order.Cust_Name</td>
                                <td>@order.Haulier_Name</td>
                                <td>@order.Driver_Name </td>
                                <td>@order.CollectionDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                                <td>@order.CollectionTown</td>
                                <td>@order.DeliveryDate.Value.ToString("dd/MM/yyyy HH:mm")</td>
                                <td>@order.DeliveryTown</td>
                                <td>@order.Reference</td>
                            </tr>
                                    }
                                }
                            
                        </tbody>
                    </table>
                    }`

**Function For Selected**
` private void SelectedFunction(int key)
    {
        this.VisibleProperty = true;
        Selected = key;
        SelectedBool = true;
        foreach (var order in orders)
        {
            if (order.Key == key)
            {
                selectedOrder = order;
            }
        }
        this.VisibleProperty = false;
    } `

### Exceptions (if any)

![error](https://user-images.githubusercontent.com/22405181/106592938-0e7c2600-6548-11eb-8e46-b37c4d6e9979.png)

### Further technical details
 - .NET 5.0
 - Blazor

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by Darkside32** [comment]
Hi there. Sorry for the late response to this. I have invited you to a GIT Repo to download and have a look. Due to the API I am using, I would like the repo to be private and not for public display, therefore having to invite you.

**Comment by mkArtakMSFT** [comment]
Thanks @Darkside32. We usually avoid looking into customer projects. Instead we ask for a small repro project, which is based off of a new project template + the minimum set of changes required to reproduce the behavior under question. The reason for this approach is that most of the time customers are able to identify issues in their own code when building a repro project. Of course, that also makes our investigations shorter and reasonable.
That said, please share a newly created project instead (hosted on GitHub would be great).

**Comment by Darkside32** [comment]
This is a new project will the minimal detail to recreate the error, which has happened once again. This just has the table on the index of the project where the error occurs once you select a row with more than one page. I just connected the Azure API I've been using to make it simpler for data to be added to the table. I could remove the Azure connection to make this a public repo.

**Comment by mkArtakMSFT** [comment]
I would appreciate if you could make it public and yes, please remove those credentials.

**Comment by Darkside32** [comment]
Yeah no problem. I have linked the repo below. I just added test data to a LIST and displayed it from there

https://github.com/Darkside32/TableError

Sorry about before.

**Comment by SteveSandersonMS** [comment]
The code in this application mutates the DOM that Blazor is rendering, which makes it impossible for Blazor to know how to update it on subsequent renders. This happens when you call into the JavaScript code at https://github.com/Darkside32/TableError/blob/be516b4fbf3bf84a0c69e5140404fb94d4269a5b/BlazorApp1/Pages/_Host.cshtml#L40

For more information about how and why this is not supported, please see https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#use-of-javascript-libraries-that-render-ui-dom-elements. Note that this limitation is not specific to Blazor, but also applies to other mainstream SPA frameworks such as React and Angular.
