### ISSUE TITLE
How to pass an optional RenderFragment from a parent component to a child component in Blazor?

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#29860]
**Context:**
We have an Blazor application with the following 3 files:

 - ChildComponent.razor
 - ParentComponent.razor
 - Test.razor (this is the consumer, which uses the parent component)

**ChildComponent.razor**

    <div>
    	@if(Body != null)
    	{
    		@Body
    	}
    
    	@if(Footer != null)
    	{
            <div class="footer">
    		    @Footer
            </div>
    	}
    </div>
    
    @code
    {
    	[Parameter]
        public RenderFragment Body { get; set; }
    	
    	[Parameter]
        public RenderFragment Footer { get; set; }
    }

**ParentComponent.razor**

The ParentComponent uses the ChildComponent. We want to pass the `ParentFooter` to the Childcomponent´s `Footer`:
    
    <ChildComponent Footer="ParentFooter">
    	<Body>
    		<p>@Text</p>
    	</Body>
    </ChildComponent>
    
    @code
    {
    	[Parameter]
    	public string Text { get; set; }
    
    	[Parameter]
        public RenderFragment ParentFooter { get; set; }
    }

The consuming file is **Test.razor** and looks like this:

    <ParentComponent Text="Hello World"></ParentComponent>

We do not use a `<ParentFooter></ParentFooter>` here, because the footer is optional.

**Problem:**

We get an exception in the browser´s console:

> Unhandled exception rendering component: Delegate to an instance
> method cannot have null 'this' (Parameter 'this')

**Possible Solution:**

In the file **ParentComponent.razor**, we pass the Footer by an reference and make an `null`-check:

    <ChildComponent Footer="ParentFooter" @ref="m_ChildComponentRef">
    	<Body>
    		<p>@Text</p>
    	</Body>
    </ChildComponent>
    
    @code
    {
    	[Parameter]
    	public string Text { get; set; }
    
    	[Parameter]
        public RenderFragment ParentFooter { get; set; }
    	
    	private ChildComponent m_ChildComponentRef { get; set; }
    	
    	protected override void OnParametersSet()
        {
            base.OnParametersSet();
    
            if (ParentFooter != null)
            {
                m_ChildComponentRef.Footer = ParentFooter;
            }
        }	
    }

But this is is a bad way, because we get an warning:

> BL0005:Component parameter should not be set outside of its component.

**Question:** How can we pass an optional RenderFragment to an child component?

**Comment by javiercn** [comment]
@enetstudio thanks for contacting us.

You can override `SetParametersAsync` and implement your own logic for dealing with mapping the component parameters to the properties/fields in your class.

**Comment by enetstudio** [comment]
@javiercn,  many thanks for your prompt response. I've already solved all the issues involved. I'll close this issue. Thanks...
