### ISSUE TITLE
Error: 401 The issuer 'https://login.microsoftonline.com/{TENANT-ID}/v2.0' is invalid"

### ISSUE THREAD

**Issue by ClimberBear** [dotnet/aspnetcore#29874]
### Describe the bug
When I follow the instructions in the tutorial [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/es-es/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0) I get the error in the title, when I try to access a resouce

### To Reproduce
When I try to run the example

I'm able to to login to the sample application
I have checked the returned authorization token, and in the issuer field contains https://login.microsoftonline.com/xxxxxxxxxxx/v2.0 (where xxxxxx is my tenantid)
But, when I try to call the Wheather page (protected), I get the error
401 The issuer 'https://login.microsoftonline.com/{TENANT-ID}/v2.0' is invalid"
I have checked in internet, and I have found similar issues in other scenarios (e.g. Angular), but I don't understand the root cause of the error

For me is clear that the framework is not expanding the variable {TENANT-ID}, but it's not defined/clear where and how to manage this variable

### Further technical details
- Net Core 5.0.2
- Visual Studio 2019 for Mac
```
SDK de .NET (que refleje cualquier global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Entorno de tiempo de ejecución:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.1.404 [/usr/local/share/dotnet/sdk]
  3.1.405 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### Update
UPDATE:
I have workarounded the issue forcing the validate issuer in Server application

Edit Startup.cs
Add the IssuerValidator option to ConfigureServices (change xxxxxxx for your tenantid)
		public void ConfigureServices(IServiceCollection services)
		{
			services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
					.AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

			services.AddControllersWithViews();
			services.AddRazorPages();
			services.Configure<JwtBearerOptions>(
				AzureADDefaults.JwtBearerAuthenticationScheme, options =>
				{
					options.TokenValidationParameters.NameClaimType = "name";
					options.TokenValidationParameters.ValidIssuer = "https://login.microsoftonline.com/xxxxxxxxxx/v2.0";
				});
		}

### Other
I have also opened the bug as a documentation bug, and has been rejected
https://github.com/dotnet/AspNetCore.Docs/issues/21417

**Comment by javiercn** [comment]
@ClimberBear thanks for contacting us.

@jmprieur I think this can be a config issue with `Microsoft.Identity.Web` can you take a look?

**Comment by jennyf19** [comment]
@ClimberBear We would recommend you use the .NET 5 project templates, which use [Microsoft Identity Web](https://github.com/azuread/microsoft-identity-web), more info on the differences between the old and new templates is [here](https://developer.microsoft.com/en-us/identity/blogs/microsoft-identity-web-is-now-generally-available/). 

MS Id Web will handle the issuer validation for you, so you do not need to define it. What is your specific scenario for wanting to validate the issuer? 

Thanks.

cc: @javiercn @jmprieur

**Comment by mkArtakMSFT** [comment]
@jennyf19 do you have a repo where I can transfer these (external) issues to? It just doesn't make sense to track these here as they're not caused by AspNetCore.

**Comment by jmprieur** [comment]
@mkArtakMSFT : they are not caused by MIcrosoft.IDentity.Web, @mkArtakMSFT : it's not used in the docs which is referenced: which is an ASP.NET doc.

We recommend the users to use the new templates: https://github.com/AzureAD/microsoft-identity-web/wiki/web-app-template#use-of-the-blazor-web-assembly-template

**Comment by ClimberBear** [comment]
Thanks! I will retry with the new templetes. In fact, the initial project was created with Net Core 3.1, and later upgraded. As I have already workarounded, I have not looked 2 months ago. And, for @jennyf19 , I did not add the issuer validation. It was added by default following the tutorial.
I will come back when I have a simple test using Microsoft OAUTH2
