### ISSUE TITLE
Blazor CSS isolation with selectors

### ISSUE THREAD

**Issue by alexandrereyes** [dotnet/aspnetcore#29872]
I'm trying to add CSS selectors to a component but I think there is a bug on how Blazor renders the CSS attribute, see bellow:

`Contoso.razor`

```
<div id="footer">
  <p>bow</p>
  <p>bah</p>
</div>
```

`Contoso.razor.css`
```
#footer > * {
  margin-left: 5px;
}
```

what is rendering:
```
#footer > *[b-olw06ad2ad] {
    margin-left: 4px;
}
```

what should be render:
```
#footer[b-olw06ad2ad] > * {
    margin-left: 4px;
}

```

**Comment by javiercn** [comment]
@alexandrereyes thanks for contacting us.

You need to use 
```css
#footer ::deep > * {
  margin-left: 5px;
}
```

Otherwise the attribute always gets applied to the right
