### ISSUE TITLE
Balzor - Cannot convert from 'method group' to 'EventCallback'

### ISSUE THREAD

**Issue by GLuca74** [dotnet/aspnetcore#29871]
Hello all,

i have a Blazor webassembly application with a component :

```
@typeparam T

<p>Generic Component</p>

@code {


	[Parameter]
	public EventCallback<GenericClass<T>> OnDeleting { get; set; }


	[Parameter]
	public RenderFragment<T> ChildContent { get; set; }

}

```

and I use it in a page like this

```
@page "/genericcomponentpage"
@using Generic.Components

<h3>GenericComponentPage</h3>
<Generic.Components.GenericComponent T="int" OnDeleting="OnDeleting" >
	<p>Content</p>
</Generic.Components.GenericComponent>

@code {
	void OnDeleting (GenericClass<int> v)
	{
	}
}
```

the generic class

```
namespace Generic.Components
{
    public class GenericClass<T>
    {
        public T item { get; set; }
    }
}

```

In this situation, this component line 
`OnDeleting="OnDeleting"`

give the compiling error "Cannot convert from 'method group' to 'EventCallback'"

if i remove this from the component
	`public RenderFragment<T> ChildContent { get; set; }`

the error go away and all compiles well

Is this a bug or i am doing somenting wrong?

Thanks

[Generic.zip](https://github.com/dotnet/aspnetcore/files/5917807/Generic.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment]
This is potentially related to https://github.com/dotnet/aspnetcore/issues/28410

**Comment by SteveSandersonMS** [comment]
I'm confident this is the same as https://github.com/dotnet/aspnetcore/issues/28410, so closing as a duplicate. Will add a note there to check this scenario if it's fixed.
