### ISSUE TITLE
CSS Backer files do not load when project name has period 

### ISSUE THREAD

**Issue by TaylorWatson** [dotnet/aspnetcore#29885]
# CSS Backer files do not load when project name has period 

Can be easily reproduced.

dotnet new blazorserver -o companyname.appname

css backer files will not load due to the . in the app name.

    <link href="companyname.appname.styles.css" rel="stylesheet" />

**Comment by javiercn** [comment]
@TaylorWatson thanks for contacting us.

I just tried this and can't reproduce the behavior, if you provide minimal repro steps we can look at it.

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/106891307-595c8180-669f-11eb-999e-afd64877cfca.png)

**Comment by TaylorWatson** [comment]
This is the weirdest thing. I tried it twice, I need to go back and see what I did wrong. Thanks for the hard work guys
