### ISSUE TITLE
Improve Helix installation script retry logic

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#29888]
Follow up to https://github.com/dotnet/aspnetcore/pull/29842.

1. Remove dependency on tools.ps1 by duplicating its logic in runtests.ps1. This will likely involve including dotnet-install.ps1 in the helix payload.
2. Read the output of dotnet-install.ps1 so that if it hangs after successful completion, a more indicative message can be displayed for queries.

**Comment by dougbu** [comment]
Worth emphasizing a hope we get enough information from #29842 to determine if (1) is needed. Would also be great to see few enough retries that (2) is unnecessary.

> This will likely involve including dotnet-install.ps1 in the helix payload.

This is primarily an easy way to simplify what needs to happen in runtests.ps1

**Comment by JunTaoLuo** [comment]
We've had more reliable helix runs so I'm going to close this issue.
