### ISSUE TITLE
Razor LSP: Reference window is empty

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#29887]
Issue provided by CTI: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1270581

**Repro Steps**
1. Environment | Preview Features | Enable experimental Razor editor (requires restart) - default enabled
2. Create new project > Blazor App > .NET 5.0 ~ Blazor Server App > Create
3. Open Pages/Counter.razor
4. Right click on 'currentCount' on line 14 ans select 'Find All Reference'.

**Actual Result**
The reference window is empty
![image](https://user-images.githubusercontent.com/70516076/106741122-3fe31780-6656-11eb-8e44-377f11ad2e2c.png)

**Note**
1. This issue didn't reproduce with 16.9 Preview4.
![image](https://user-images.githubusercontent.com/70516076/106742816-7c177780-6658-11eb-9bac-2403a2ac4bd7.png)

**Comment by NTaylorMullen** [comment]
I can no longer reproduce. @TanayParikh could you validate that this has been fixed on your end as well?

**Comment by TanayParikh** [comment]
On latest VS Main from today, not working for me:
![image](https://user-images.githubusercontent.com/14852843/108258941-68b6e280-7115-11eb-8b1f-3f26e35e3728.png)

Also a new `Find External References` option (which doesn't produce results either):
![image](https://user-images.githubusercontent.com/14852843/108259032-85531a80-7115-11eb-9768-3dcc2aed8525.png)

**Comment by NTaylorMullen** [comment]
Hmm I don't have the Find External References bit which leads me to believe that you must have a feature flight on for you or something that's resulting in FAR exploding. What I do know is that Find External References is a RichNav feature they're trying out. I'll start an offline convo to see if we can get to the bottom of this.

**Comment by TanayParikh** [comment]
Discussed offline, created: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1280059

**Comment by TanayParikh** [comment]
There's an external and razor specific fix involved.
