### ISSUE TITLE
Import Key Vault Certificate

### ISSUE THREAD

**Issue by marcelWCH** [dotnet/aspnetcore#29891]
Hello 

Regarding to the Blazor Tutorial on Git (blazor-workshop/10-publish-and-deploy.md at master · dotnet-presentations/blazor-workshop (github.com)) at the step (Browse to your app service in the portal, select TLS/SSL Settings. Select the Private Key Certificates (.pfx) tab and then select Import Key Vault Certificate.) I do not get the option of “Import Key Vault Certificate”. And with the additional Infos around I still have no clue how to! 

My set-up is a Blazor-Server Project with existing Azure DBs which I try to protect the DB Password. Is your Tutorial also set-up for this kind of DB Project? 
What could be the problem and where do I find feedback? 
Thanks for your Info and support, 
marcel 

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment]
@marcelWCH thanks for filing the issue.

We'll take a look and update the documentation as necessary.

**Comment by marcelWCH** [comment]
Hello, 
I attached a print screen to show you how the workflow looks on my side, this means the option of “Import Key Vault Certificate” is missing compare to your Git Tutorial. 
What is the current status of this request? Thanks for a feedback, and how to save a Blazor Project (DB Password) in Azure. 
regards, marcel 

<img width="917" alt="Screenshot 2021-02-17 083711" src="https://user-images.githubusercontent.com/22916354/108171131-5d56bd80-70fb-11eb-8959-7c7460f88573.png">

**Comment by marcelWCH** [comment]
hi, i like to ask about the current status of this/my request? i ask because i can not see it on GIT online anymore, just over the email. 
it is still open but i do not see any feedback, please let me know about a solution for my request, kind regards, marcel

**Comment by SteveSandersonMS** [comment]
Moving to https://github.com/dotnet-presentations/blazor-workshop/issues/317
