### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer Exception when using Localization

### ISSUE THREAD

**Issue by pureggerstefan** [dotnet/aspnetcore#29890]
Greetings, 

When using localization with the given StringLocalizer from Microsoft, from time per time there occurs some Exceptions (see below) when navigating through razor-Pages in the App. 

I couldn't reconstruct this error perfectly, but i noticed that it occurs more often, if there was no resource file according to the culture set in the local storage. 

For example: When I set the culture to english and I have no english resource file for my pages, this error occurs more often than it would when there is a resource file according to the culture. 

Does anyone know what could be the cause of the exceptions?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/67411268/106859260-13b1b000-66c3-11eb-9af2-bbbb3f8cf93d.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/67411268/106859277-190efa80-66c3-11eb-9948-8f110d405fbf.png)

Best regards,
Stefan

**Comment by javiercn** [comment]
@pureggerstefan thanks for contacting us.

In order for us to be able to help here, could you provide us with a minimal repro project and detailed steps on how to trigger the problem?
