### ISSUE TITLE
Improve exception message if deps.json not found when using WebApplicationFactory<T>

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#29892]
### Is your feature request related to a problem? Please describe.

When using the `WebApplicationFactory<T>` class in tests, if the `Microsoft.AspNetCore.Mvc.Testing` NuGet package is referenced transitively, rather than directly in the test project, then an exception may be thrown with this message if the `deps.json` file of the assembly containing the startup class `T` isn't otherwise somehow copied to the test output folder:

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Mvc/Mvc.Testing/src/Resources.resx#L126-L128

The resolution is to add a direct reference to `Microsoft.AspNetCore.Mvc.Testing` in the project file so that the target to copy the `.deps.json` files during the build are run:

https://github.com/dotnet/aspnetcore/blob/ee14861aac17932feda7d9c8d5c3425bb75ce367/src/Mvc/Mvc.Testing/src/Microsoft.AspNetCore.Mvc.Testing.targets#L61-L69

### Describe the solution you'd like

Preferred solution: if possible, the target runs even when the NuGet package is included as a transient dependency.

Alternative solution: Update the error message to include checking that `Microsoft.AspNetCore.Mvc.Testing` is explicitly referenced in the tests' project file.

**Comment by javiercn** [comment]
@martincostello thanks for contacting us.

We don't expect people to reference this package transitively, but I would be ok if we update it for the targets to be loaded when referenced transitively.

The change here would be to add a \buildTransitive folder to the package with props/targets that import the ones within the \build directory.

**Comment by martincostello** [comment]
Cool thanks @javiercn - I'd be happy to pick that up a do a PR to make the change.

**Comment by javiercn** [comment]
@martincostello we would be happy to accept a PR for it.

**Comment by javiercn** [comment]
Thanks!
