### ISSUE TITLE
.NET5 (ASP.NET) with IdentityServer4: in loop after login

### ISSUE THREAD

**Issue by erossini** [dotnet/aspnetcore#29895]
I have my new project with ASP.NET Core 5 and ASP.NET Core Identity. I want to add `AddOpenIdConnect` with IdentityServer4. I have other projects already in place that they are working fine and up and running. Then, I copied the code and paste in my new project.

    services.AddSession(options =>
    {
        options.Cookie.Name = ".puresourcecode.session";
        options.IdleTimeout = TimeSpan.FromHours(12);
    });

        services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = "oidc";
        })
        .AddCookie(options =>
        {
            options.ExpireTimeSpan = TimeSpan.FromMinutes(30);
            options.Cookie.Name = "puresourcecode.cookie";
        })
        .AddOpenIdConnect("oidc", options =>
        {
            options.Authority = idsrv.IdentityServerUrl;
            options.ClientId = idsrv.ClientId;
            options.ClientSecret = idsrv.ClientSecret;

    #if DEBUG
            options.RequireHttpsMetadata = false;
    #else
            options.RequireHttpsMetadata = true;
    #endif

            options.ResponseType = "code";

            options.Scope.Clear();
            options.Scope.Add("openid");
            options.Scope.Add("profile");
            options.Scope.Add("email");
            options.Scope.Add("roles");
            options.Scope.Add("offline_access");

            options.ClaimActions.MapJsonKey("role", "role", "role");

            options.GetClaimsFromUserInfoEndpoint = true;
            options.SaveTokens = true;

            options.SignedOutRedirectUri = "/";

            options.TokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = JwtClaimTypes.Name,
                RoleClaimType = JwtClaimTypes.Role,
            };
        });

I added the new package `Microsoft.AspNetCore.Authentication.OpenIdConnect`. I configured my IdentityServer to redirect the user after the login to `/signin-oidc` and the grant types is `authorization_code`. As I said I have lot of other projects that are working fine.

When I run the new application, I redirect to the IdentityServer. I login but the the browser is in loop because it is opening again and again the IdentityServer page for authentication (I don't need to authenticate again because I have already authenticated myself).

> https://identityserver.azurewebsites.net/connect/authorize?client_id=GenericDashboard&redirect_uri=https%3A%2F%2Flocalhost%3A44396%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles%20offline_access&code_challenge=H9RoyXfqahr-f4DtyDgdNkh_8vGUST_QhgjU2VYJXdQ&code_challenge_method=S256&response_mode=form_post&nonce=637478860376726598.ZmRhOTRiNmEtZDllMC00NjY5LThmYzItNjc0Yzk3YjllZGExMjQwOGE3MTctYmJmMS00NmNkLWExNzgtZjczYzE3ZmNhOTgw&state=CfDJ8LL4MQ6yNcxBhaWzp8huStleQClOdf0oyg9kbVOBOKlghZFxCaIifcPydVsUC4cpcN1cGZ9tlFQ38G4zO7jl_boSmcwyUhEg3GDOQ6xBOGYPD-pbFrm3gPWjUp2jZx2Ex0lYMH6y9lt9V4ZZ4kSbIPb08kaN-6i429yXW3oOQ3Pc8e1GtA7RprRWoinyywFp-nt2kGu9K4K17NIrtUmCQ3SUXxCoI3AncQIJoi4wLrndzchVzkc7W3lT39ZbmP8-e7_s4rYrogGR_gQ2N_I4OqYfVnVzDt1drJXkWt9vIy6-SpjhQoX38iR9CENoVucsJfw5dqa7Dg8aYvr5Dq23QcnJc6oizYBUn-AgIAkaeCgHZTlluvxMJXKBXtcN6bhiMQ&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.7.1.0

This is the configuration of my IdentityServer4

## Basic
[![enter image description here][1]][1]

## Authentication
[![enter image description here][2]][2]

## Token
[![enter image description here][3]][3]

Here you have the [video][4] of what it is happening.

I checked Application Insights and here is what I can see for only one login (I waited few seconds after the login to generate same logs)

## Requests
![image](https://user-images.githubusercontent.com/9497415/106894699-38b81a00-66e7-11eb-8fea-a95bd25270d9.png)

## Trace
![image](https://user-images.githubusercontent.com/9497415/106894788-51c0cb00-66e7-11eb-9500-a0b3cb9da57e.png)

## Logs
[admin202102041312.txt](https://github.com/IdentityServer/IdentityServer4/files/5925901/admin202102041312.txt)

(short just few seconds) 
[admin202102041315.txt](https://github.com/IdentityServer/IdentityServer4/files/5925913/admin202102041315.txt)

The interesting thing is that all the other applications are working fine. If I use the credentials I created for this app with .NET5, the process is working. As a comparison, I use the same credentials in a project with .NET Core 3.1 and Microsoft.AspNetCore.Authentication.OpenIdConnect 3.1.9. It works

  [1]: https://i.stack.imgur.com/Lk1DR.png
  [2]: https://i.stack.imgur.com/NRvVW.png
  [3]: https://i.stack.imgur.com/SzK72.png
  [4]: https://youtu.be/bEC-v0tydSE

**Comment by blowdart** [comment]
If you capture the browser history (I tend to use f12, then the network tab) what cookies sent and dropped?

What's different to your other projects? Are they hosted the same way? If this, as it looks to be, is azure websites, did you setup the forwarding header middleware? As we don't have your full startup.cs it's hard to tell.

**Comment by erossini** [comment]
The source code is here https://github.com/erossini/AdminLTEWithASPNETCore

In the other projects I don't have Microsoft Identity but only `OpenIdConnection` and .NET Core 3.1. All of them are hosted in Azure. I run on my local machine when I develop. 

If you see the [video](https://youtu.be/bEC-v0tydSE), you have a rightly idea what it is happening.

**Comment by blowdart** [comment]
The video is private, but don't worry about it. So the goal here is to add Identity Server inside that AdminLTE repo, or to simply use an oauth identity provider? Or both asp.net identity and identity server?

**Comment by erossini** [comment]
The video is now public. I'm trying to have in the same project the authentication with Microsoft Identity or IdentityServer4. In the appsetting, If `UseIdentityServer` is `false`, I want to use Microsoft Identity. If `UseIdentityServer` is `true`, in the `Startup.cs` there is the code to connect the application with IdentityServer4 via `OpenIdConnect`.

**Comment by erossini** [comment]
I updated my code adding the events from `OpenIdConnect`. Although the user is validated again IdentityServer, the application calls again and again the IdentityServer. [Here](https://github.com/erossini/AdminLTEWithASPNETCore/blob/main/AdminLTEWithASPNETCore/Startup.cs) the updated code.

![image](https://user-images.githubusercontent.com/9497415/108362250-6aeb7080-71eb-11eb-840c-13e6023c7e7f.png)

**Comment by erossini** [comment]
I think I found the issue. If you add `Microsoft Identity` to your solution, `IdentityServer` authentication won't work. I removed all packages related to `Microsoft Identity` and the folder `Area | Identity`  and the authentication with `IdentityServer` is working.

**Comment by blowdart** [comment]
Oh that would make sense. Identity Server itself wires up identity, and tries to encapsulate everything. If you add it back again, things are going to get mixed up, because now identity has been told "Hey you're in charge", but you're still going to identity server. I'm glad you got going. If it gets stuck again, please reopen the issue.
