### ISSUE TITLE
[Blazor] Update bundle generation to use Webpack 5

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#29904]
For all the goodness it might bring and to make sure we are up to date with our dependencies

**Comment by javiercn** [comment]
See https://github.com/dotnet/aspnetcore/pull/30320 for the signalr update to follow suit

**Comment by benaadams** [comment]
Second commit in https://github.com/dotnet/aspnetcore/pull/30320

However; additionally the `blazor.server.js` should be served compressed as either `.br` or `.gz` which it isn't currently.

In `themesof.net` I currently intercept the request; then compress and cache the compressed version in memory and serve that in second request etc https://github.com/terrajobst/themesof.net/blob/2e795379c7853c6cd271cf61ce07f282a5d37510/src/ThemesOfDotNet/Middleware/PrecompressedMiddleware.cs#L177-L210; however this should be precompressed and automatic

**Comment by benaadams** [comment]
Can more than half the size of `blazor.server.js` by switching `msgpack5` to `@msgpack/msgpack`
