### ISSUE TITLE
Support Asynchronous JWT Validation

### ISSUE THREAD

**Issue by mchandschuh** [dotnet/aspnetcore#29917]
### Background

The existing authentication handlers work very well for their stated purposes. However, It's not uncommon to want to _slightly_ tweak the behavior of specific pieces, and to that end, aspnet has done a wonderful job of parameterizing pretty much every component in the framework. One area that could use improvement is supporting asynchronous, non-blocking validation of security tokens. The existing `ISecurityTokenValidator` defines a blocking API for validating `SecurityToken` objects  and creating a `ClaimsPrincipal` representing the data provided in the token.

Another way to enable asynchronous validation of tokens is by refactoring existing authentication handlers to perform token validation in its own asynchronous method. Consider `JwtBearerHandler.HandleAuthenticateAsync`, which handles resolving the token from potentially multiple sources and then validating the resolved token. Validation currently happens within this same method block by looping through the provided `JwtBearerOptions.SecurityTokenValidators` which synchronously validate the token.

An alternative to updating`ISecurityTokenValidator` to support asynchronous invocations, is to refactor authentication handlers such that token validation is performed in its own virtual method returning a `ClaimsPrincipal`. The default implementations would continue to execute synchronously via the configured list of `ISecurityTokenValidator`, however, this would provide framework consumers the chance to override this method and perform custom token validation.

### My Work Around

I'm using a custom identity server for the generation and validation of json web tokens. What makes this difficult to integrate into the existing set of authentication handlers is that it doesn't communicate over HTTP, but rather over a custom messaging protocol used by our system. My workaround is to subclass the `JwtBearerHandler` and override it's `HandleAuthenticateAsync` method. I added the exact same code as the overridden `JwtBearerHandler.HandleAuthenticateAsync` and then extracted a method from the [start of token validation](https://github.com/1Konto/aspnetcore/blob/main/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L108) until the [end of the try block](https://github.com/1Konto/aspnetcore/blob/main/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L181) with the following signature:

``` csharp
protected virtual async Task<AuthenticateResult> ValidateToken(string token, TokenValidationParameters validationParameters)
```

Here's the full derived class for  your reference.
<details>

``` csharp

public class JwtBearerAsyncValidationHandler : JwtBearerHandler
{
    private OpenIdConnectConfiguration? _configuration;

    public JwtBearerAsyncValidationHandler(
        IOptionsMonitor<JwtBearerOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder,
        ISystemClock clock
        )
        : base(options, logger, encoder, clock)
    {
    }

    protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        string? token = null;
        try
        {
            // Give application opportunity to find from a different location, adjust, or reject token
            var messageReceivedContext = new MessageReceivedContext(Context, Scheme, Options);

            // event can set the token
            await Events.MessageReceived(messageReceivedContext);
            if (messageReceivedContext.Result != null)
            {
                return messageReceivedContext.Result;
            }

            // If application retrieved token from somewhere else, use that.
            token = messageReceivedContext.Token;

            if (string.IsNullOrEmpty(token))
            {
                string authorization = Request.Headers[HeaderNames.Authorization];

                // If no authorization header found, nothing to process further
                if (string.IsNullOrEmpty(authorization))
                {
                    return AuthenticateResult.NoResult();
                }

                if (authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                {
                    token = authorization.Substring("Bearer ".Length).Trim();
                }

                // If no token found, no further work possible
                if (string.IsNullOrEmpty(token))
                {
                    return AuthenticateResult.NoResult();
                }
            }

            if (_configuration == null && Options.ConfigurationManager != null)
            {
                _configuration = await Options.ConfigurationManager.GetConfigurationAsync(Context.RequestAborted);
            }

            var validationParameters = Options.TokenValidationParameters.Clone();
            if (_configuration != null)
            {
                var issuers = new[] { _configuration.Issuer };
                validationParameters.ValidIssuers = validationParameters.ValidIssuers?.Concat(issuers) ?? issuers;

                validationParameters.IssuerSigningKeys = validationParameters.IssuerSigningKeys?.Concat(_configuration.SigningKeys)
                    ?? _configuration.SigningKeys;
            }

            return await ValidateToken(token, validationParameters).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            Logger.ErrorProcessingMessage(ex);

            var authenticationFailedContext = new AuthenticationFailedContext(Context, Scheme, Options)
            {
                Exception = ex
            };

            await Events.AuthenticationFailed(authenticationFailedContext);
            if (authenticationFailedContext.Result != null)
            {
                return authenticationFailedContext.Result;
            }

            throw;
        }
    }

    protected virtual async Task<AuthenticateResult> ValidateToken(string token, TokenValidationParameters validationParameters)
    {
        SecurityToken validatedToken;
        List<Exception>? validationFailures = null;
        foreach (var validator in Options.SecurityTokenValidators)
        {
            if (validator.CanReadToken(token))
            {
                ClaimsPrincipal principal;
                try
                {
                    principal = validator.ValidateToken(token, validationParameters, out validatedToken);
                }
                catch (Exception ex)
                {
                    Logger.TokenValidationFailed(ex);

                    // Refresh the configuration for exceptions that may be caused by key rollovers. The user can also request a refresh in the event.
                    if (Options.RefreshOnIssuerKeyNotFound && Options.ConfigurationManager != null
                        && ex is SecurityTokenSignatureKeyNotFoundException)
                    {
                        Options.ConfigurationManager.RequestRefresh();
                    }

                    if (validationFailures == null)
                    {
                        validationFailures = new List<Exception>(1);
                    }

                    validationFailures.Add(ex);
                    continue;
                }

                Logger.TokenValidationSucceeded();

                var tokenValidatedContext = new TokenValidatedContext(Context, Scheme, Options)
                {
                    Principal = principal,
                    SecurityToken = validatedToken
                };

                await Events.TokenValidated(tokenValidatedContext);
                if (tokenValidatedContext.Result != null)
                {
                    return tokenValidatedContext.Result;
                }

                if (Options.SaveToken)
                {
                    tokenValidatedContext.Properties.StoreTokens(new[]
                    {
                        new AuthenticationToken {Name = "access_token", Value = token}
                    });
                }

                tokenValidatedContext.Success();
                return tokenValidatedContext.Result!;
            }
        }

        if (validationFailures != null)
        {
            var authenticationFailedContext = new AuthenticationFailedContext(Context, Scheme, Options)
            {
                Exception = (validationFailures.Count == 1)
                    ? validationFailures[0]
                    : new AggregateException(validationFailures)
            };

            await Events.AuthenticationFailed(authenticationFailedContext);
            if (authenticationFailedContext.Result != null)
            {
                return authenticationFailedContext.Result;
            }

            return AuthenticateResult.Fail(authenticationFailedContext.Exception);
        }

        return AuthenticateResult.Fail("No SecurityTokenValidator available for token: " + token ?? "[null]");
    }
}

```

</details>

### Concluding Thoughts

I think the **ideal** solution would be to update `ISecurityTokenValidator.ValidateToken` to return `ValueTask<ClaimsPrincipal>` instead of just `ClaimsPrincipal`. This would  maintain the synchronous execution for all of the existing validators while also providing framework consumers the flexibility to implement potentially asynchronous token validation. For my particular case, I would be able to implement a custom `ISecurityTokenValidator` that reaches out to our identity server using our custom message protocol and add it to the `JwtBearerOptions.SecurityTokenValidators` list and everything else would be on the 'happy path'.

I think the refactoring of authentication handlers seems to be an easier, less risky way to achieve my desired goal of asynchronous token validation, but probably shouldn't be done for this sole purpose. I do think, however, that the authentication handlers would benefit from a mechanical refactoring aimed at making them easier and more friendly to subclassing. This would provide framework consumers with even more flexibility over authentication as some things can't be communicated through options.

### Alternate Work Around Suggestions?

On a final note, if anyone reading this has suggestions for an approach better than my above detailed workaround, by all means, please share. I did look into using a remote authentication scheme, but it seemed like **a lot** more work when all I wanted to do was make token validation happen on another server via a custom message protocol. I got about half way through prototyping it when I decided it was too much code and too risky from a security standpoint. I find it to be a much safer option to rely on existing and battle tested aspnetcore code vs rolling my own.

Thanks for taking the time to read my issue!

**Comment by Tratcher** [comment]
Duplicate of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/468.

**Comment by blowdart** [comment]
Closing as dupe :)
