### ISSUE TITLE
Router.PreferExactMatches ends up limiting trimming unnecessarily

### ISSUE THREAD

**Issue by stephentoub** [dotnet/aspnetcore#29913]
Router.PreferExactMatches has this comment on it:
https://github.com/dotnet/aspnetcore/blob/dfe625fbd122557cc4dda0f3d6f3dc5c7afc8c8e/src/Components/Components/src/Routing/Router.cs#L85-L87

As of now, though, the option is still available and still false by default.  The net effect is the "LegacyRoute" support constructed here:
https://github.com/dotnet/aspnetcore/blob/dfe625fbd122557cc4dda0f3d6f3dc5c7afc8c8e/src/Components/Components/src/Routing/Router.cs#L159-L161
ends of referencing and preventing a bunch of APIs that could otherwise by trimmed by the linker from getting trimmed in a default Blazor wasm app.

cc: @eerhardt, @javiercn

**Comment by pranavkm** [comment]
@SteveSandersonMS / @javiercn, what's our plan for this? If we want to remove legacy routing (I'd be open to it), we should do it right away. If we want to wait until 7.0 to remove legacy routing, we should consider enabling legacy routing behind a feature switch so that we have the ability to trim it away.

**Comment by SteveSandersonMS** [comment]
If possible it would be great to drop the legacy code paths ASAP. If we get any signs of dissatisfaction, we could ship the legacy router OOB in a separate package.

**Comment by pranavkm** [comment]
Cool. I have a PR out for it - https://github.com/dotnet/aspnetcore/pull/31295 - that's part of my no-linq work. Let me see if I can separate the two since they're not really dependent.

**Comment by stephentoub** [comment]
Thanks!
