### ISSUE TITLE
Subscription - Authorizarion

### ISSUE THREAD

**Issue by user321-creator** [dotnet/aspnetcore#29924]
Hi,
       Using RequireAuthorization() in MapGraphql() results in Subscription call failure with error "Could not connect to websocket endpoint ". Without RequireAuthorization, its just working fine as expected. Should anything need to be added as service to make it as work?

        app.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapGraphQL();
                    endpoints.MapGraphQL("/web", schemaName: "web").RequireAuthorization();

                    endpoints.MapGet("/", context =>
                    {
                        context.Response.Redirect("/playground");
                        return Task.CompletedTask;
                    });
                });
      app.UsePlayground("/web", "/playground");

**Comment by Tratcher** [comment]
This should be directed to the owners of MapGraphQL. What package is that coming from?

**Comment by user321-creator** [comment]
@Tratcher HotChocolate.AspNetCore.Extensions

**Comment by Tratcher** [comment]
Ah, this one.
https://github.com/ChilliCream/hotchocolate/blob/ae265d4565c223498a6675b7a7f127579e2259b8/src/HotChocolate/AspNetCore/src/AspNetCore/Extensions/EndpointRouteBuilderExtensions.cs

You'll need to ask them about their extension.
