### ISSUE TITLE
[Announcement]Disabling GitHub Discussions tab for dotnet/aspnetcore

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#29935]
Discussion issue for https://github.com/aspnet/Announcements/issues/452

## Rationale

Since we enabled GitHub Discussions, we've found them quite hard to manage for a repository the size of aspnetcore. Without labelling and assigning capabilities, there are no effective ways to triage or track what discussions have been looked at, or who has the next step.

To that end, we're going to disable them, and encourage people to just use issues instead - that way we can continue to ensure they get reviewed by the team, and acted upon if they are in fact bugs, etc.

## When will this happen

I'll make the switch in a week, on 2021-02-11.

## What happens to existing discussions

They will no longer be visible, but as far as we can tell, GitHub still keeps them, and if we ever enable discussions again, they will come back.

## Where do I discuss this

Please leave feedback below.

**Comment by SIkebe** [comment]
> [Announcement]Disabling GitHub Issues tab for dotnet/aspnetcore

Is this title right? You mean "Discussions tab" instead of "Issues tab"?

**Comment by Pilchie** [comment]
Grr.  Even when you get people to review your posts...  Fixed above.

**Comment by tomkerkhove** [comment]
A pity, feel free to share feedback with @becca @evi-liu to improve the product if you want

**Comment by ffMathy** [comment]
This is how I feel about GitHub discussions in general. No one really reads them it seems. People create issues either way.

**Comment by tomkerkhove** [comment]
> This is how I feel about GitHub discussions in general. No one really reads them it seems. People create issues either way. 

I have a few projects where they are very useful

**Comment by jzabroski** [comment]
@ffMathy I read discussions on my repository and convert some issues to discussions.

That said, I can appreciate the reasons why dotnet is disabling it.

I think, also, for such a huge repo like dotnet with thousands of issues, issues themselves need improved tools to keep track of what was said.

**Comment by Pilchie** [comment]
I did talk to @evi-liu about the issues we've faced, and I've gone ahead and made the change now.

**Comment by jzabroski** [comment]
One of the pieces of feedback I gave @evi-liu and @beccaz during the GH Discussions beta is that the moderation tool for comments is weak across issues and discussions.  The example I gave was EntityFrameworkCore repository thread on missing support for many-to-many.  GitHub Issues has the collapsed comments feature, which randomly eradicates useful replies.  There's no easy way to highlight specific comments as useful to a product owner grooming a backlog.

Whereas Discussions has an upvote feature for answers, there is no way to upvote "good points".  Plus, a lot of Issues discussions I deal with personally are people landing on some issue from Google search and then spamming an old issue with "oh, this is my problem as well" without any details or stack trace.  In this sense, I wish GitHub had Google Analytics-type features to hone in on where people came from when visiting an issue.  Was it StackOverflow?  Was it a blog post?  Was it a search engine?  Ideally, it also tracks a heat map of what the user spent time reading on the Issue/Discussion before posting a comment.  I have a relatively small but popular C# nuget package with 5M+ downloads and another with 2M+ downloads and so while my network effect is not the same as dotnet, I imagine there is a concordance of pain points around these concerns.

Hope that helps.

Thank you, @Pilchie

**Comment by brunohbrito** [comment]
Hi @Pilchie is that possible to get the text I wrote of a discussion back? So I can open an issue instead?

https://github.com/dotnet/aspnetcore/discussions/28263

**Comment by jzabroski** [comment]
@brunohbrito I will raise this to @becca and @evi-liu on the discussions beta testing forum.

**Comment by jzabroski** [comment]
@brunohbrito I logged issue 270 in the beta discussions private github repo : "Unable to recover discussion when maintainer turns off discussions"

**Comment by Pilchie** [comment]
And I put the text of the initial post from that discussion at https://gist.github.com/Pilchie/1710c640443f65c47f27cc6b09efa612.

**Comment by Beej126** [comment]
just finding this after wondering where one of my discussions went =) i was sharing a technique that helped solve a "gap" in the dotnet cli... and the reason that became handy is the corresponding issues identifying that gap were closed to further comment... i guess this all basically translates to opening new issues in this scenario which didn't seem right to me since it wasn't really an issue, it was a "show & tell" which seemed to be what discussions were intended for... what bummed me out was that creating the discussion and referencing the comment id#'s didn't register the automatic backref links under the issues that we're used to otherwise... so nobody would know about the corresponding discussion without specifically searching for those issue id's
