### ISSUE TITLE
Why WebHost Call the same method three times?

### ISSUE THREAD

**Issue by littlecodepig** [dotnet/aspnetcore#29932]
Microsoft.AspNetCore.Hosting, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

		public WebHost(IServiceCollection appServices, IServiceProvider hostingServiceProvider, WebHostOptions options, IConfiguration config, AggregateException hostingStartupErrors)
		{
			if (appServices == null)
			{
				throw new ArgumentNullException("appServices");
			}
			if (hostingServiceProvider == null)
			{
				throw new ArgumentNullException("hostingServiceProvider");
			}
			if (config == null)
			{
				throw new ArgumentNullException("config");
			}
			this._config = config;
			this._hostingStartupErrors = hostingStartupErrors;
			this._options = options;
			this._applicationServiceCollection = appServices;
			this._hostingServiceProvider = hostingServiceProvider;
			this._applicationServiceCollection.AddSingleton<ApplicationLifetime>();
			this._applicationServiceCollection.AddSingleton((IServiceProvider services) => services.GetService<ApplicationLifetime>());
			this._applicationServiceCollection.AddSingleton((IServiceProvider services) => services.GetService<ApplicationLifetime>());
			this._applicationServiceCollection.AddSingleton((IServiceProvider services) => services.GetService<ApplicationLifetime>());
			this._applicationServiceCollection.AddSingleton<HostedServiceExecutor>();
		}

My Question:

why call method of "AddSingleton((IServiceProvider services) => services.GetService<ApplicationLifetime>());" three time?

what's the purpose?

**Comment by Tratcher** [comment]
That decompile is misleading. The ApplicationLifetime class is registered as three different services:
https://github.com/dotnet/aspnetcore/blob/43a348b22468be9ed46ff1681cc113c9598b9f25/src/Hosting/Hosting/src/Internal/WebHost.cs#L86-L94
This was done to mitigate some breaking changes that have happened across versions.
