### ISSUE TITLE
Exception thrown when creating style setter value programatically

### ISSUE THREAD

**Issue by arivoir** [dotnet/aspnetcore#29936]
When creating a style setter programmatically, the following exception is thrown

```
var style = new Style(typeof(MyControl));
style.Setters.Add(new Setter() { Property = MyEnumProperty, Value = EnumType.EnumValue });
```

> Exception thrown: 'System.ArgumentException' in WinRT.Runtime.dll
An exception of type 'System.ArgumentException' occurred in WinRT.Runtime.dll but was not handled in user code
Value does not fall within the expected range.

>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
at ABI.Microsoft.UI.Xaml.ISetter.global::Microsoft.UI.Xaml.ISetter.set_Value(Object value)
at Microsoft.UI.Xaml.Setter.set_Value(Object value)

**Comment by mkArtakMSFT** [comment]
@arivoir can you please clarify how is this related to ASP.NET Core?

**Comment by javiercn** [comment]
@arivoir we don’t think this is related to aspnetcore.

If this is by any chance related to mobile blazor bindings, please file an issue in the mobile blazor bindings repo.

**Comment by arivoir** [comment]
Sorry, this wasn't intended to be published here.
