### ISSUE TITLE
Correct use of "{" unclear in coding guidelines

### ISSUE THREAD

**Issue by whatisalwaystrue** [dotnet/aspnetcore#29938]
Hi,
The coding guidelines in the wiki suggest that { should be on a new line, but then some of the examples go on to show class and method bodies where it is not on a new line.  Should the examples be consistent? Or am I missing the intent of the guideline?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please confirm whether you're referring to the [Engineering guidelines](https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines/58147322248af4148149d70aa4c19c7d1efada67) or something else?

**Comment by whatisalwaystrue** [comment]
Yes Exactly. Coding style guideline #5

**Comment by wtgodbe** [comment]
Good catch @whatisalwaystrue - we'll get this fixed up.

**Comment by JunTaoLuo** [comment]
Guidelines updated.
