### ISSUE TITLE
Blazor webrtc library

### ISSUE THREAD

**Issue by Terricide** [dotnet/aspnetcore#29943]
### Is your feature request related to a problem? Please describe.
Wrapper for the Webrtc api, I'm working on creating a wrapper for the WebRTC api and I've got it working okay however I'm worried about async/await and the json serialization performance overhead of passing many byte arrays using JSInterop.

I think I've got it working .NET - JS working okay bypassing the JSON interop however going the other way JS to .NET I don't see a way to do it.

My code is here is you want to take a look
https://github.com/Terricide/Blazor.WebRTC

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by javiercn** [comment]
@Terricide thanks for contacting us.

Can you clarify exactly what problem you are running into? Are you worried about reading JS data from .NET?

**Comment by Terricide** [comment]
Yeah I was more worried about performance and how I could squeeze out more. I'm writing this library for a remote control program and ideally I will be passing up to 4k 60fps h264 chunks and I'm looking for as low a latency as possible.

**Comment by javiercn** [comment]
@Terricide You can use the native mono bindings to pass back a reference to the array buffer or similar

**Comment by Terricide** [comment]
I was pretty sure there was a way to do it but I couldnt find an example anywhere. Ive got it qorking 1 way :)

**Comment by Terricide** [comment]
Or it might just not work. This is the thread Ive found trying to do it.

https://github.com/dotnet/aspnetcore/issues/11244

**Comment by javiercn** [comment]
@Terricide I don't think that's it. It's something like `Binding.<<something>>`. I think it's `BINDING.js_array_to_mono_array` or `js_typed_array_to_array`

**Comment by Terricide** [comment]
I think that is definitely pointing me in the right direction. However I think I have to still figure out how to pass it back to .net

This still tries to use json

var obj = window.BINDING.js_array_to_mono_array(ev.data);
await dotnetRef.invokeMethod("_ondatamessage", obj);

**Comment by javiercn** [comment]
@Terricide I'm not sure if we expose "unmarshalled" .NET interop via dotnetobjectreference which is what you would need here, but you could get it to work with a bit of indirection. 

Pass in a JS Object reference to your dotnet object reference and have it invoke the method on the jsobject reference with unmarshalled interop, and from there return it the way you are doing it. That would work I think.

**Comment by Terricide** [comment]
The library is using WebRTC and datachannel messages can come in at any point. So I guess I'll have to store the message and then invoke .net to call into javascript to get the message. Not sure if that is less overhead since it would require invoking JS-.NET - .NET-JS

**Comment by Terricide** [comment]
Actually I think this might help seeing how the ClientWebSocket works.

https://github.com/mono/mono/blob/a2d1aec5d2c01483738dfa6e69202462bca68e2b/sdks/wasm/framework/src/WebAssembly.Net.WebSockets/ClientWebSocket.cs

**Comment by Terricide** [comment]
FYI I got it working if anyone is interested.

https://github.com/Terricide/Blazor.WebRTC
