### ISSUE TITLE
self-contained not generated runtime.json

### ISSUE THREAD

**Issue by nurbat** [dotnet/aspnetcore#29956]
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli

`PS ...\bin\Debug\net5.0> dotnet Client.WebAssembly.dll
Cannot use file stream for [...\bin\Debug\net5.0\Client.WebAssembly.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '...\bin\Debug\net5.0\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '...\bin\Debug\net5.0\Client.WebAssembly.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '...\bin\Debug\net5.0\Client.WebAssembly.runtimeconfig.json' file and specify the appropriate framework.`

![изображение](https://user-images.githubusercontent.com/5789051/107125770-6605f300-68b4-11eb-8aec-b9b1c841d020.png)
![изображение](https://user-images.githubusercontent.com/5789051/107125720-2c34ec80-68b4-11eb-82e1-6e4ac74349b3.png)

### Further technical details
5.0.2 - ASP.NET Core version
`Version:   5.0.200-preview.20614.14
 Commit:    863605c8c3

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`
[ VS / VSCode ] Every

**Comment by javiercn** [comment]
@nurbat thanks for contacting us.

Can you clarify what you are trying to achieve?

Are you trying to publish a webassembly app (the wasm part) as a self contained executable?

That’s not something we support.

**Comment by nurbat** [comment]
I built the project in the usual way dotnet build file is not in the folder. I started searching, found what I need to publish through the dotnet publish command, but it did not give the desired result.

I am trying to run the file as dotnet ProjectName.dll to which I get an error. The absence of file

**Comment by nurbat** [comment]
Yes, I'm trying to run it from the command line. I have an app https://github.com/chromelyapps/Chromely I plan to run the dotnet command ProjectName.dll and then the program will connect to it. If you can tell me how to run it directly in the app, I will be very grateful. For example using https://github.com/chromelyapps/Chromely

**Comment by javiercn** [comment]
@nurbat you can't run a Blazor webassembly app from the command-line, you need to host it behind a file server like IIS, Kestrel or use a development server like `dotnet serve` to consume the app from the browser.
