### ISSUE TITLE
Could blazor let us specified custom name for publish folder ?

### ISSUE THREAD

**Issue by Thaina** [dotnet/aspnetcore#29955]
I want to publish blazor into specific folder name. Specifically for github pages, it could allow us to specified `docs` folder as a folder for pages. I could just set `PublishDir` as root repo itself if I could specified publish folder name as `docs`

### Describe the solution you'd like
Maybe a property `WWWRoot` in `.csproj`?

```xml
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PublishDir>.\</PublishDir>
    <WWWRoot>docs</WWWRoot>
  </PropertyGroup>
```

And it should became this structure when publish

![image](https://user-images.githubusercontent.com/1042507/107123276-3b756380-68cf-11eb-9c25-b741850de4da.png)

**Comment by javiercn** [comment]
@Thaina thanks for contacting us.

We don’t plan to offer this feature like this since it’s something you can achieve today via existing MSBuild extensibility for the publish workflow.
