### ISSUE TITLE
CSS Isolation breaks with NavLink component - isolation id not applied to <a> tag

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspnetcore#29969]
### Describe the bug
CSS isolation works great except when used in conjunction with a NavLink, specifically with regards to the active class.

### To Reproduce
In the backing {component}.razor.scss, define the following:

```
.active {
  color: #f00;
}
```

In the Razor markup, set something up like:

`<NavLink href="/place" ActiveClass="active">Click here!</NavLink>`

When you run the app and click on the link, you'd then expect to see the active class applied to the <a> tag. Voila, it's there! However, there's no style associated with it in the CSS.. Digging into it, you can see from the generated {project}.styles.css file that it's in there matching something like:

```
.active[v-kl12lkj21] {
  color: #f00;
}
```

But it doesn't get applied to the NavLink here because while parent and child entities will be notated with the isolation identifier, the <a> tag itself will not be, thus the class won't match any styling.

### Further technical details
- ASP.NET Core version
5.0.2

- Include the output of `dotnet --info`
Version 5.0.102

**Comment by javiercn** [comment]
@WhitWaldo thanks for contacting us.

CSS isolation applies to HTML elements within a file, not to components (since that defeats the purpose of isolation)

You can achieve this by using the `::deep` selector to avoid the scope being applied.

**Comment by WhitWaldo** [comment]
@javiercn That make sense, but still leaves me in a pickle, given that it says that I'll have a pile of slightly different "active" classes in a global file that are each specific to some component somewhere, which is the point of the CSS isolation in the first place (e.g. CSS that's specific to that component).

That leads me towards thinking it makes the most sense to just create my own NavLink component so I might set the isolated CSS for it, but especially for more elaborate controls, that's not going to be terribly practical.

**Comment by javiercn** [comment]
@WhitWaldo you can wrap the NavLink with an element and change the rule to be something like below:
```css
div::deep .active {
  ...
}
```

That should get you the results you are after.

We could allow using a RenderFragment with the NavLink and that should work I believe (or you can create your own NavLink that receives a render fragment with the markup to display the values).

In general the solution when you have a component you want to style is to wrap it on an element and use `::deep`
