### ISSUE TITLE
Question - Proposed Possible Workaround for Blazor Prerender UI Flash

### ISSUE THREAD

**Issue by flyingpie** [dotnet/aspnetcore#29968]
This would have been a discussion topic, but since those are going away, I'm asking it through an issue instead.

There have been a few posts and issues about Blazor WebAssembly and prerendering, which can cause a "UI Flash" when some async stuff is done to build the page. One example is here: https://github.com/dotnet/aspnetcore/issues/14836.

I'd like to ask some feedback about a possible workaround that I made and documented here: https://github.com/flyingpie/blazor-prerender-cache. It's very close that what I think has been suggested by Blazor contributors before, but perhaps it'd help to have a documented working example for people to find when they're running to this problem.

I wonder if you agree with the solution, and if it could help to perhaps put such a solution in the documentation.

If that is the case, I'd be happy to help out with that, but I'd like to make sure that I'm not missing some obvious problem with the workaround first :)

Thank you for all the work you're doing!

**Comment by javiercn** [comment]
@flyingpie thanks for contacting us.

We are already working on something that will solve this problem. See https://github.com/dotnet/aspnetcore/issues/28361 for details.

**Comment by flyingpie** [comment]
@javiercn Thank you for your comment, I'll keep an eye on that issue :)
