### ISSUE TITLE
Blazor InputFile doesn't notice user cancellation

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#29979]
### Describe the bug
I have an InputFile component and upload a file with it. The event OnChange gets raised fine. Now I click again on the browse button to change my uploaded document(s) and click on cancel. The component says nothing is selected now but the event doesn't raise again. So how should I detect that the user has deleted his/her upload?

### To Reproduce
Consider the following code which writes the file to an Directory called _Uploads_.
```
<InputFile OnChange="OnInputFileChange" class="form-control" accept="application/pdf" />
@code 
{
	private async Task OnInputFileChange(InputFileChangeEventArgs e)
	{
		string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Uploads");
		string filename = Path.Combine(path, e.File.Name);

		if (!Directory.Exists(path))
		{
			Directory.CreateDirectory(path);
		}

		byte[] buffer = new byte[e.File.Size];
		await e.File.OpenReadStream().ReadAsync(buffer);

		await File.WriteAllBytesAsync(filename, buffer);
	}
}
```

Without detection for deletion I am not able to do validation. Consider my model for the input has a string which stores the path to the uploaded file which is being set within this method. So the user clicks on the button again and cancels the operation.
Because a cancel i snot recognized, I would still have my string in my model set to the file, the user has uploaded before. In addtion this results in unnesscary files on the server, which could have been easily removed if there was any way to detect user cancellation. 

### Further technical details
- ASP.NET Core version 5.0.2
- VS Studio 2019 - 16.8.4 
.NET SDK (gemäß "global.json"):
 Version:   5.0.200-preview.20601.7
 Commit:    b3b934bbf2

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by DjeeBay** [comment]
Same here.

The thing is when cancelling the onChange event is not triggered by the browser itself.
As InputFile doesn't come with a solution, we have to find a workaround like adding a "clear button" and display file(s) data correctly (because when cancelling we still have the data).

You also can find JS workarounds.

Would be great if the InputFile component has the feature.

**Comment by georgehemmings** [comment]
The cancellation isn't detected as a change because [Blazor is clearing the input's value when it's clicked](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/InputFile.ts#L26). By registering your own click handler you can clean up your own state (the path or reference to the IBrowserFile object). I've found by adding a `@key` to the `InputFile` you can force the UI to create a new input element, which resolved the issue raised in #34040.

https://blazorrepl.telerik.com/mPFPYxvG34GY8AcP03

```
<div>
    <InputFile @key="uploadedCount" OnChange="@FileChange" @onclick="FileClick" />
</div>

<button @onclick="Upload" disabled="@(selectedFile == null)">Upload</button>

<p>@message</p>

@code {

    private int uploadedCount = 0;
    private string message;

    public void Upload()
    {
        if (selectedFile == null)
            return;

        // Upload selectedFile

        message = $"{selectedFile.Name} uploaded!";

        selectedFile = null;
        uploadedCount++;
    }

    IBrowserFile selectedFile;

    private void FileClick()
    {
        selectedFile = null;
    }

    private void FileChange(InputFileChangeEventArgs e)
    {
        selectedFile = e.File;
    }
}

```

**Comment by mcguu** [comment]
@georgehemmings  can the inputfile be click in the cs code?

like the documentByElementId('file‘).click();

**Comment by TanayParikh** [comment]
This is something that can already be accomplished by using a `CancellationToken` when you call into the [`BrowserFile.OpenReadStream`](https://github.com/dotnet/aspnetcore/blob/e00b58eb641f1eb3ad3fe4cb872cd9ca4c31e898/src/Components/Web/src/Forms/InputFile/BrowserFile.cs#L36-L44) (`await e.File.OpenReadStream().ReadAsync(buffer);`. 

You can have a `CancellationTokenSource` associated with the `InputFile` component. At the start of the `OnInputFileChange` method, you can check if a previous upload is still in progress, and if so, call [`CancellationTokenSource.Cancel`](https://docs.microsoft.com/dotnet/api/system.threading.cancellationtokensource.cancel?view=net-6.0) on the previous upload. Then you can create a new `CancellationTokenSource` for the next upload, and pass in the [`CancellationTokenSource.Token`](https://docs.microsoft.com/dotnet/api/system.threading.cancellationtokensource.token?view=net-6.0) into `BrowserFile.OpenReadStream`.

**Comment by TanayParikh** [comment]
Also note:

```csharp
byte[] buffer = new byte[e.File.Size];
await e.File.OpenReadStream().ReadAsync(buffer);
```

will likely result in issues with larger files. The way you'd want to achieve this would be by leveraging [`Stream.CopyToAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copytoasync?view=net-6.0) or by using `Stream.ReadAsync` using smaller chunks until you reach the end of the stream.  Note this is in line with our [streaming](https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#stream-from-javascript-to-net) and [file upload](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server) guidance. Specific examples and sample code are also available in those docs pages.
