### ISSUE TITLE
Blazor - Virtualize - virtualized table scrolling incorrect behaviour when cells have a border

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#29975]
To reproduce, create a table and add a border to all cells. If you try to scroll down, the scroll box moves much slower than the mouse cursor.

The workaround is to remove 'border-style: solid' and add 'border-bottom-style: solid; border-left-style: solid; border-right-style: solid;.

Test application:
[VirtualizeBug-CellBorder.zip](https://github.com/dotnet/aspnetcore/files/5942041/VirtualizeBug-CellBorder.zip)

Incorrect scrolling behaviour:
![StartScrollDown](https://user-images.githubusercontent.com/10242002/107191123-00b51d80-69ec-11eb-95f3-06b02ac8a370.png)
![ScrollDownError](https://user-images.githubusercontent.com/10242002/107191130-03177780-69ec-11eb-8ec1-c47fbedd1f35.png)

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS FYI

**Comment by SteveSandersonMS** [comment]
The scrollbar-out-of-sync-with-mouse is a Chromium bug (doesn't repro in Firefox). This has been logged as a bug in Edge, so I'll close this as external.

**Comment by Jarek300** [comment]
And where exactly is this bug reported? I've checked https://bugs.chromium.org/ and searching 'scrollbar out of sync' finds nothing relevant. 

I've also checked Edge Canary 90.0.792.0 and the problem is not fixed.

**Comment by SteveSandersonMS** [comment]
It’s reported on the internal Edge bug tracker. It’s up to the maintainers there whether to fix it directly in Chromium or whether to convert it into an upstream bug on chromium.org.
