### ISSUE TITLE
ExceptionHandlerMiddleware custom logging

### ISSUE THREAD

**Issue by Anderman** [dotnet/aspnetcore#29977]
### Describe the solution you'd like
I want overrule the logging at line https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L106 
This allow me to Ignore some kind of exceptions and add special request information about other execptions.

If I use https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L133
for my custom logging . I will miss exceptions where the response is started and I must filter the exceptions logged by the framework.

One way I could implement this is to subclass the ExceptionHandlerMiddleware or write my own ExceptionHandlerMiddleware

**Comment by BrennanConroy** [comment]
> write my own ExceptionHandlerMiddleware

That would be the recommended approach.
