### ISSUE TITLE
Blazor server - IServiceProvider is disposed in the OnAfterRenderAsync of Blazor page. 

### ISSUE THREAD

**Issue by rwecho** [dotnet/aspnetcore#29976]
### Refresh page again and again
When I call an async method in the OnAfterRenderAsync, It throws _System.ObjectDisposedException_ . Because I forced refresh page again when loading.

### Reproduce with a default Blazer server project, add below code to index.razor
```
<SurveyPrompt Title="How is Blazor working for you?" />
@inject IServiceProvider ServiceProvider

@code
{
    private bool IsServiceProviderDisposed()
    {
        var field = this.ServiceProvider.GetType().GetField("_disposed", BindingFlags.NonPublic |
                                                                         BindingFlags.Instance);
        var isDisposed = (bool) field.GetValue(this.ServiceProvider);
        return isDisposed;
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await Task.Delay(100);
            Debug.WriteLine($"{nameof(Index)} ->" + this.ServiceProvider.GetHashCode());
            // ServiceProvider is disposed.
            Debug.Assert(!IsServiceProviderDisposed());
        }

        await base.OnAfterRenderAsync(firstRender);
    }
}
```

### Is this a bug or feature? 
Hope loading async data to impact view like WPF loaded events.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by rwecho** [comment]
Hi @mkArtakMSFT 
I submit a demo for [reproducing](https://github.com/rwecho/BlazorApp2)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
