### ISSUE TITLE
dev-certs allow dev to add additional SAN Subject Alternative Name

### ISSUE THREAD

**Issue by patware** [dotnet/aspnetcore#29988]
### Is your feature request related to a problem? Please describe.
dotnet dev-certs creates a self-signed certificate for localhost.  

This is great when the URI of a resource is "https://localhost" but doesn't work well in the context of docker-compose when a container needs to communicate with another service...  

In the docker-compose, every service will have at least one container, and each container gets their own IP.  Obviously a container responds well to a call to localhost.

- containerA can call itself via https://localhost, cert is valid.
- containerB can call itself via https://localhost, cert is valid.

But when reaching out to another service, 

- containerA will reach serviceB via https://serviceB, however, the certificate won't be valid because it's SAN is set to localhost.

https is required for communication via gRPC. I know I can setup gRPC to disregard SSL verification with "DangerousAcceptAnyServerCertificateValidator" and only do this in "Development" but it's not elegant.

### Describe the solution you'd like
I'd like the ability to add SAN entries other than just localhost.

dotnet dev-certs https --addSAN serviceA, serviceB, serviceC

The addSAN would ignore entries already in the certificate.

### Uber solution.

It would be great if Visual Studio would handle this automatically when building/running a docker-compose Project.  The service names are in the docker-compose.yaml.

**Comment by javiercn** [comment]
@patware thanks for contacting us.

Unfortunately, the dev-certs tools is deliberately scoped to scenarios involving localhost. There are additional security constraints that we need worry about if we start adding SANS for other hosts (in addition to the fact that it would mean generating a new certificate every time a different host is needed).

We recommend you use openssl or any other well-known certificate toolchain to deal with scenarios involving hosts other than localhost.

**Comment by patware** [comment]
Thanks @javiercn ,  

Would it make sense then to give the user the ability to generate an openSSL certificate ?  

dotnet dev-certs https --openSSL

**Comment by javiercn** [comment]
@patware openssl is a complete separate toolchain from dotnet dev-certs. It's a different exe and something we wouldn't wrap within dotnet dev-certs.

There is ample documentation on the web about how to generate TLS certificates using ssl and we would recommend just following the guidance offered in any of the sites.

**Comment by patware** [comment]
Great stuff, thank you, I'll definitely have a look at this.

Suggestion: update the docs making it more obvious to use openSSL in a multi microservices/docker-compose scenario, because it has been a frustrating experience for me.  On the other hand I learned so many things in .net core, asp.net core, kestrel, docker, visual studio, certificates, ...

**Comment by blowdart** [comment]
@patware https://fabianlee.org/2018/02/17/ubuntu-creating-a-trusted-ca-and-san-certificate-using-openssl-on-ubuntu/ is the starting point I've used before, but if you search, you'll find about five separate ways to do the same thing.

This doesn't cover how to then trust the CA in containers, because it's so OS dependent, and no-one can see to get an all-inclusive master doc. Once you're heading into containers, it really becomes docker specific too, and you start looking at how to inject stuff, and then you have how to secure the keys etc.

**Comment by patware** [comment]
I don't know about you, but whenever I'm in a situation where simple things start to become impossible to do, it's usually because I've missed an important turn somewhere and I'm trying to fix a problem that shouldn't be there in the first place.  So I'll go back to drawing board and start from scratch.  RTFM, right ?
