### ISSUE TITLE
Blazor Server: allow to customize reconnection handler partially

### ISSUE THREAD

**Issue by denisbredikhin** [dotnet/aspnetcore#29991]
I'm trying to find out what is the best way to handle reconnections in my app.
For my specific case default reconnection logic is almost ok, except that I would like to auto-reload a page in case when reconnection is rejected or failed.
And now we came to my problem: I can write fully custom reconnection logic, I can use standard one, or I can change the visualization of a standard one, but not to slightly change the standard logic. 

As I see my problem can be solved in the one of the following ways:

- If it would be possible to pass not only reconnectCallback but also rejected and failed funcs to a DefaultReconnectionHandler. And if there will be documentation, how to initialize reconnectCallback with a DefaultReconnectionHandler.

- if I would be able to get prettified sources of DefaultReconnectionHandler in js (then I can copy-paste it)

- if I would be able to customize Blazor startup in ts (as I know it is not possible?) - then I can copy-paste DefaultReconnectionHandler from the sources in this repo

- if I would be able to pass custom descendant of DefaultReconnectDisplay to DefaultReconnectionHandler and initialize reconnectCallback with it

**Comment by captainsafia** [comment]
@denisbredikhin Thanks for opening this issue.

From your comment, it looks like you might've already taken a look at some of the docs we provide for this. Was the section on [modifying the reconnection handler](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-5.0#modify-the-reconnection-handler) not adequate for your needs?

```
<body>

    ...

    <script autostart="false" src="_framework/blazor.server.js"></script>
    <script>
      Blazor.start({
        reconnectionHandler: {
          onConnectionDown: (options, error) => console.error(error),
          onConnectionUp: () => console.log("Up, up, and away!")
        }
      });
    </script>
</body>
```

You can find the code for the `DefaultReconnectionHandler` here:

https://github.com/dotnet/aspnetcore/blob/56388808f8633184607b9d8e8c1a2226f3f260dd/src/Components/Web.JS/src/Platform/Circuits/DefaultReconnectionHandler.ts#L7-L38

**Comment by denisbredikhin** [comment]
@captainsafia Docs about that describes modifying the reconnection handler are clear.
But, using this docs I can only **replace** standard one but not to **change a bit** logic of a standard.
It would be more or less ok, if I would have sources of the default reconnection handler in js - then I would copy-paste them and modify.
Now I need manually re-write Ts sources into Js to achieve this, and this is possible source of mistakes.
What I want to achieve is to auto-reload page instead of showing a link to do this.

**Comment by captainsafia** [comment]
@denisbredikhin Have you considered instantiating the reconnection handler with a custom `ReconnectDisplay` that implements a refresh in either the `show` or `hide` method depending on what user experience you want?

```js
Blazor.defaultReconnectionHandler._reconnectionDisplay = {
  show: () => window.reload()
};
```

**Comment by denisbredikhin** [comment]
@captainsafia 
Thanks for idea.
Actually, in this case I still need Js sources, but not of DefaultReconnectionHandler but of DefaultReconnectionDisplay.
But it anyway easier to re-write them from ts sources than do the same with DefaultReconnectionHandler.
So I will try this tomorrow.
