### ISSUE TITLE
Blazor : Create cascading value using RenderTreeBuilder inside a new RenderFragment

### ISSUE THREAD

**Issue by David-Moreira** [dotnet/aspnetcore#30006]
Hello guys,

I am having difficulties trying to create the following Cascading Value using the Render Tree Builder API, where both the parent and childcontent renderFragments are created dynamically, and where I would like the parent RenderFragment to Cascade itself.

Here's my use case: XTabs component should be a Cascading Value.

        var xTabFragment = new RenderFragment(rBuilder =>
        {
            rBuilder.OpenComponent(0, typeof(XTab));
            rBuilder.AddAttribute(1, nameof(XTab.ChildContent), pageFragment);
            rBuilder.AddAttribute(2, nameof(XTab.Title), xTabTitle);
            rBuilder.CloseComponent();
        });

        _xTabsRenderFragment = new RenderFragment(rBuilder =>
        {
            rBuilder.OpenComponent<XTabs>(0);

            rBuilder.AddAttribute(1, nameof(XTabs.RenderMode), RenderMode);
            rBuilder.AddAttribute(2, nameof(XTabs.CloseTabs), CloseTabs);
            rBuilder.AddAttribute(3, nameof(XTabs.NewTabSetActive), NewTabSetActive);
            rBuilder.AddAttribute(4, nameof(XTabs.ChildContent), xTabFragment);

            rBuilder.AddComponentReferenceCapture(5, compRef => _xTabs = (XTabs)compRef);
            rBuilder.CloseComponent();
        });
I have tried the following snippet inside the XTabsRenderFragment, (with adequate sequence numbers) which I've found on similar threads here, but with no success since the use case on those threads was overriding the BuildRenderTree method instead

```
 rbuilder.OpenComponent<CascadingValue<TValue>>(0);
 rbuilder.AddAttribute(1, "Value", this);
 rbuilder.AddAttribute(2, "ChildContent", (builder2) =>
 {
   builder2.AddContent(3, ChildContent);
 });
 rbuilder.CloseComponent();
```
Can you guys help me figure this out, please?

**Comment by javiercn** [comment]
@David-Moreira thanks for contacting us.

You need to specify the type of the value as an attribute using  rbuilder.AddAttribute(2, "TValue", typeof(TValue));

**Comment by David-Moreira** [comment]
Ok, maybe I wasn't explicit enough.
That's precisely what I'm trying.

So this works, with no cascading value:
```
    var xTabFragment = new RenderFragment(rBuilder =>
    {
        rBuilder.OpenComponent(0, typeof(XTab));
        rBuilder.AddAttribute(1, nameof(XTab.ChildContent), pageFragment);
        rBuilder.AddAttribute(2, nameof(XTab.Title), xTabTitle);
        rBuilder.CloseComponent();
    });

    _xTabsRenderFragment = new RenderFragment(rBuilder =>
    {
        rBuilder.OpenComponent<XTabs>(0);

        rBuilder.AddAttribute(1, nameof(XTabs.RenderMode), RenderMode);
        rBuilder.AddAttribute(2, nameof(XTabs.CloseTabs), CloseTabs);
        rBuilder.AddAttribute(3, nameof(XTabs.NewTabSetActive), NewTabSetActive);
        rBuilder.AddAttribute(4, nameof(XTabs.ChildContent), xTabFragment);

        rBuilder.AddComponentReferenceCapture(5, compRef => _xTabs = (XTabs)compRef);
        rBuilder.CloseComponent();
    });
```
    
This is my attempt to set up the cascading value and does not work:

                var xTabFragment = new RenderFragment(rBuilder =>
                {
                    rBuilder.OpenComponent(0, typeof(XTab));
                    rBuilder.AddAttribute(1, nameof(XTab.ChildContent), pageFragment);
                    rBuilder.AddAttribute(2, nameof(XTab.Title), xTabTitle);
                    rBuilder.CloseComponent();
                });

                _xTabsRenderFragment = new RenderFragment(rBuilder =>
                {
                    rBuilder.OpenComponent<XTabs>(0);

                    rBuilder.OpenComponent<CascadingValue<XTabs>>(1);
                    rBuilder.AddAttribute(2, "Value", _xTabs);
                    rBuilder.AddAttribute(3, "ChildContent", (RenderFragment)((builder2) =>
                    {
                        builder2.AddContent(4, xTabFragment);
                    }));
                    rBuilder.CloseComponent();
                    rBuilder.AddAttribute(5, nameof(XTabs.RenderMode), RenderMode);
                    rBuilder.AddAttribute(6, nameof(XTabs.CloseTabs), CloseTabs);
                    rBuilder.AddAttribute(7, nameof(XTabs.NewTabSetActive), NewTabSetActive);
                    //rBuilder.AddAttribute(4, nameof(XTabs.ChildContent), xTabFragment);

                    rBuilder.AddComponentReferenceCapture(8, compRef => _xTabs = (XTabs)compRef);
                    rBuilder.CloseComponent();
                });

![image](https://user-images.githubusercontent.com/22283161/107368090-0720c380-6ad8-11eb-8e18-8a41f2aa8fbc.png)


Probably has to do with the component reference not being set yet, or maybe I'm just building it wrong, but I'm not sure how this should be handled.

**Comment by javiercn** [comment]
@David-Moreira It's not clear to me what you are trying to do, but I have a suggestion you can try.

Create this in Razor syntax, go to the obj/Debug/net5.0/Razor folder and you can find the generated code for what you are trying to there and replicate it with your component

**Comment by David-Moreira** [comment]
That was a very good suggestion. 
Thanks @javiercn. 

I figured that the cascading value that was already defined in my component, was already implicit when the component is opened .rBuilder.OpenComponent<**XTabs**>(0);
So that's working just fine.

Just that I had flawed logic in the **XTabs** with only applying the CascadingValue to its ChildContent ie:
```
<CascadingValue Value="this">
       @ChildContent
</CascadingValue>
```
which would work, but I had a shortcut adding **XTab** components inside my **XTabs** component by using:
**_xTabs**.AddPage(**xtab**);
turning out not to be adding **XTab** as a direct ChildContent of the **XTabs** component therefore not receiving the cascading value.

So once the remaining of the rendering done on the **XTabs** which had smthg like this, not wrapped by **\<CascadingValue>** it would not receive it.



```
                @foreach (var tab in TabContent)
                {
                    var isActiveCss = IsActive(tab) ? "show active" : "";
                    <_XTab CssClass='@($"{@tab.CssClass} {isActiveCss}")' IsLoading="@IsLoading">
                        <ChildContent>
                            @tab.ChildContent
                        </ChildContent>
                        <LoadingContent>
                            @tab.LoadingContent
                        </LoadingContent>
                    </_XTab>
                }
```

Probably not easy to understand without seeing the concrete use case. But it's solved, Thank you @javiercn !
