### ISSUE TITLE
VS project reloads cause language server to not boot.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30002]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/An-error-occurred-while-starting-the-rem/1332589)._

---
1. New project >Blazor App > .NET 6.0 ~ Blazor WebAssembly App, checking ASP .NET Core hosted> Create

2. Add a Razor Class Library : Open a command prompt at the location of the solution folder and add a Razor class library to the solution by running:
```
     dotnet new razorclass --support-pages-and-views false -o RazorLib1
     dotnet sln add .\RazorLib1\RazorLib1.csproj
     dotnet add .\<project name>\<client app name> reference RazorLib1
```
3. Navigate to VS, it pops up a dialog to indicate you should reload the project. Just click "reload".

---
#### Feedback Bot on 2/7/2021, 01:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Note extra repro steps here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1260251

**Comment by ryanbrandenburg** [comment]
I don't see a repro on this, even with the expanded repro steps. @v-nzicol and/or @candyzhang003 does this still reproduce for you?

**Comment by NTaylorMullen** [comment]
The repro in the issue is sufficient:
1. New project >Blazor App > .NET 6.0 ~ Blazor WebAssembly App, checking ASP .NET Core hosted> Create

2. Add a Razor Class Library : Open a command prompt at the location of the solution folder and add a Razor class library to the solution by running:
```
     dotnet new razorclass --support-pages-and-views false -o RazorLib1
     dotnet sln add .\RazorLib1\RazorLib1.csproj
     dotnet add .\<project name>\<client app name> reference RazorLib1
```
3. Navigate to VS, it pops up a dialog to indicate you should reload the project. Just click "reload".

**Comment by ryanbrandenburg** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1281060. This is a VS LSP bug that they'll take care of.
