### ISSUE TITLE
In AddOpenIdConnect middleware, add an option to save id_token only

### ISSUE THREAD

**Issue by felinepc** [dotnet/aspnetcore#30016]
## Summary

The ```SaveTokens = true``` option in the OpenIDConnect middleware would save all tokens (including access and refresh tokens) to the cookie.

However, oftentimes our web app only needs to keep the ```id_token``` for sign-out purpose (for example, ```IdentityServer``` requires the ```id_token``` hint to properly perform post logout redirect).

In these scenarios, we do not need the large access and refresh tokens that can increase the cookie size significantly, sometimes even exceeding request limit when combined with other necessary cookies..

## Risks / unknowns

None, if provided as an additional option or overload.

**Comment by Tratcher** [comment]
This can be customized by using the events.
```
            .AddOpenIdConnect(o =>
            {
                // ...
                // o.SaveTokens = true;
                o.Events = new OpenIdConnectEvents()
                {
                    OnTokenValidated = c =>
                    {
                        c.Properties.StoreTokens(new[] { new AuthenticationToken
                        {
                            Name = "id_token",
                            Value = c.ProtocolMessage.IdToken
                        }});
                        return Task.CompletedTask;
                    }
                };
```

We do not plan to add an option for this scenario until we find it affecting a majority of users.

**Comment by felinepc** [comment]
Thanks @Tratcher this solution seems perfect.

**Comment by felinepc** [comment]
I just want to add a comment here in case others run into this issue:

With my testing using `IdentityServer` and the `code` flow, the `OnTokenValidated` event's `ProtocolMessage.IdToken` value returns null as written in @Tratcher 's example.

Instead, I had to use the `OnTokenResponseReceived` event and the `TokenResponseReceivedContext.TokenEndpointResponse.IdToken` property to retrieve and save the token. The token properties in  `ProtocolMessage` there are also null.
