### ISSUE TITLE
dotnet watch should append to env variables, not override them

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#30010]
dotnet-watch currently clobbers a few environment variables, rather than appending to them:
- `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES`
- `DOTNET_STARTUP_HOOKS`

There was a PR created that was never merged- https://github.com/dotnet/sdk/pull/15450

**Comment by jkotalik** [comment]
Yes, but it's a lower priority because this specific problem wouldn't be hit in VS. Hence I haven't gotten to finishing up my PR. I'll reopen it when I get the chance.

Is issue management for dotnet watch still in the aspnetcore repo.

**Comment by captainsafia** [comment]
> Is issue management for dotnet watch still in the aspnetcore repo.

Yes. We'll transfer any issues with the Area-AspNetCore label in the SDK over here anyways.

**Comment by shirhatti** [comment]
Closed via https://github.com/dotnet/sdk/pull/16008
