### ISSUE TITLE
Watch not working for newly created project

### ISSUE THREAD

**Issue by JerryLyvers** [dotnet/aspnetcore#30018]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Changes to .razor files do not trigger a rebuild as stated in the tutorial.  Note that changes to the .csproj file will trigger a rebuild.

**Comment by JerryLyvers** [comment]
I sent a reply via email on Tuesday but don't see it here.  Does that indicate it was never received?

**Comment by danroth27** [comment]
Hi @JerryLyvers. I don't believe it was received. Could you please post the requested info here?

**Comment by JerryLyvers** [comment]
Answers (with screenshots) are in the attached PDF.

[#30018.pdf](https://github.com/dotnet/aspnetcore/files/5967804/30018.pdf)

**Comment by blowdart** [comment]
Please don't use PDFs for information transfer on github. Due to PDF's somewhat dubious security history you are adding great overhead to anyone who wants to open this, due to the need to do so securely in either a sandbox, or a dedicated VM.

Github issues support images, videos, text, pretty much everything you need for reporting issues.

**Comment by JerryLyvers** [comment]
[#30018.docx](https://github.com/dotnet/aspnetcore/files/5967871/30018.docx)

**Comment by blowdart** [comment]
PDF contents:

Good Morning, 
 
OS is Windows 10 – Version 10.0.18363 Build 18363 
 
I’m not sure what “console” you are referring. So, here’s everything I’ve have: • VS Code - Terminal  
 
![Screenshot 2021-02-11 110801](https://user-images.githubusercontent.com/796298/107686448-17f94280-6c5a-11eb-9537-91784430bed8.jpg)

 
• VS Code - Problems 
 
 
![Screenshot 2021-02-11 111142](https://user-images.githubusercontent.com/796298/107686497-29424f00-6c5a-11eb-84e6-62ec04a4626c.jpg)

• VS Code - Debug Console is blank 
 
• VS Code - Output is blank 
 
• Browser Console (Chrome) 

![Screenshot 2021-02-11 110902](https://user-images.githubusercontent.com/796298/107686529-34957a80-6c5a-11eb-82ac-c7f0908b1c18.jpg)
 
Thanks 
 
From: Daniel Roth  Sent: Monday, February 08, 2021 6:16 PM To: dotnet/core  
Cc: Lyvers, Jerry ; Mention  Subject: Re: [dotnet/core] Watch not working for newly created project (#5927) 
 
EXTERNAL email. STOP and THINK before responding, clicking on links, or opening attachments. 
@JerryLyvers Thanks for sharing this feedback! To help us diagnose this issue, could you please share the following additional details: 
• What version of Windows are you using?  • What is the full console output from dotnet watch run when you try to make these code changes?  
@pranavkm

**Comment by mkArtakMSFT** [comment]
> [#30018.docx](https://github.com/dotnet/aspnetcore/files/5967871/30018.docx)

@JerryLyvers I'm removing your comment with a doc file as we don't need it.

**Comment by mkArtakMSFT** [comment]
Closing as we've made a lot of improvements in this area and we haven't heard from you for a while.
