### ISSUE TITLE
Blazor events doesn't fire when used in a Boostrap popover (new one)

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#30029]
Hello guys, i have a problem with html inside bootstrap popover, my actually is actually exactly the same than this issue
https://github.com/dotnet/aspnetcore/issues/7612

This issue have two year, i don't really understand the code of the author who solve the problem, i try to make like him but its not work.

Blazor changed a lot since this time, so maybe you can help me to make it works (and more generally, inject html fragment with binding and event)

I create a repo for that : https://github.com/julienGrd/BlazorTestPopoverEvent
- in the js file, the first method is the case the event not work
- the second method is suppose to be the correction but it seem not work (nothing is shown)

Thanks for you help !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Blazor operates based on the assumption that only it manages the DOM and knows the state of it exactly.
It looks like the library you're referring to (popover) violates that assumption and does DOM manipulation on its own. Hence this breaks.
