### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Negotiate version history

### ISSUE THREAD

**Issue by freerider7777** [dotnet/aspnetcore#30034]
New nuget package arrives, but it's not clear what is changed there...
Microsoft.AspNetCore.Authentication.Negotiate 5.0.3 for example

**Comment by blowdart** [comment]
It will be part of this month's patch update. We don't break down what happens in individual packages.

**Comment by freerider7777** [comment]
Ok, thanks for information :)
