### ISSUE TITLE
VSCode shows error message when stopping debug of a blazorwasm project : The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 1. 

### ISSUE THREAD

**Issue by sedat-eyuboglu** [dotnet/aspnetcore#30038]
### Describe the bug
I have startd a blazorwasm project by using dotnet new blazorwasm. Whenever i start a debug by pressing F5 and stop it by pressing stop button on debug toolbox VS Code shows erro message of  : The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 1.

Please note that if i enter Ctrl + C in the terminal window of VS Code, debug stops and this case does NOT happen.

See : https://github.com/OmniSharp/omnisharp-vscode/issues/4056

### To Reproduce

->In VS Code press F5  and start a debug session for a blazorWebAssemply project
->Press stop button of the debug toolbox
->And The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 1. is shown by VS Code (see attachment).

### Further technical details
- ASP.NET Core version

Sdk="Microsoft.NET.Sdk.BlazorWebAssembly"
TargetFramework = net5.0

- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.102     
 Commit:    71365b4d42  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19041
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS Code

Omni Sharp version = 1.23.9

VSCode:
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

![resim](https://user-images.githubusercontent.com/45899129/107405397-54248a00-6b18-11eb-85a3-a7579bc43402.png)

**Comment by captainsafia** [comment]
@sedat-eyuboglu Thanks for opening this issue!

Although you are using the latest version of the O# extension, the exception that you are receiving is related to an older version of the package. Can you try doing a clean install of the extension incase an upgrade did not pick up the new sources?

**Comment by sedat-eyuboglu** [comment]
> 
> 
> @sedat-eyuboglu Thanks for opening this issue!
> 
> Although you are using the latest version of the O# extension, the exception that you are receiving is related to an older version of the package. Can you try doing a clean install of the extension incase an upgrade did not pick up the new sources?

@captainsafia Thank you for your response.
I tried to uninstall extension  (ms-dotnettools.csharp) on Vs Code. It didn't help. The problem still exists.

Unfortunately, it is not possible to remove all those SDKs and runtimes, since some of them are used by other projects.

If there is no other option i have to go with this error message on this machine.

**Comment by captainsafia** [comment]
> Unfortunately, it is not possible to remove all those SDKs and runtimes, since some of them are used by other projects.

The SDKs/runtimes aren't coming in to play here.

> If there is no other option i have to go with this error message on this machine.

We're shipping another change to the debugging experience in VS Code that should resolve this issue. The change will be in the next release of the C# extension. We'll definitely not be calling this codepath. If you still run into this issue, you might want to consider doing a clean install of the extension per https://stackoverflow.com/a/36751445 in the event that it is being cached.

If the issue still persists, we'll reopen this bug.

**Comment by sedat-eyuboglu** [comment]
@captainsafia I applied following steps. And there is no change. Message is still there.

- Uninstall ms-dotnettools.csharp extension in VS Code
- Close VS Code
- Delete folder "ms-dotnettools.csharp-1.23.9" under C:\Users\sedat\.vscode\extensions (suggested way in https://stackoverflow.com/a/36751445)
- Open VS Code
- Press f5 and start debug for my blazorwasm project
- Press stop

Error message "The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 1." occured.

**Comment by captainsafia** [comment]
Thanks for trying!

This issue should be resolved in the next release of the C# extension.
