### ISSUE TITLE
OnParametersSetAsync is being invoked multiple times in certain scenarios

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#30037]
### Describe the bug
I have a page which can be visited through out a parameter. in my case
`@page "/Test{CustomerId:int}"`

When I visit the page with a direct link within my blazor project `OnParametersSetAsync()` is invoked correctly one time. However, when I visit the page manually throughout the URL bar in my browser, it gets invoked multiple times. In another project of mine, this even chains up with every page refresh but unfortunately I was not able to find out why this is happening yet.

### To Reproduce
I Created this small repo which shows exactly what I mean.
https://github.com/MarvinKlein1508/Blazor-ParametersSetAsync

### Further technical details
- ASP.NET Core version 5.0.2
- VS 2020 v 16.4.8 

.NET SDK (gemäß "global.json"):
 Version:   5.0.102
 Commit:    71365b4d42

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

Are you prerendering the page? If so, it gets called once when the server is prerendering the page and a second time when the application starts on the browser.

**Comment by javiercn** [comment]
Also, note that the repo is private and can't check it myself

**Comment by MarvinKlein1508** [comment]
Hi @javiercn 
whoops. I changed the repo to public, thanks for mentioning it.

Yes I am using render mode `ServerPrerender`.

Whats even more strang is within my other project. In this one I am also using the ServerPrerender mode.

I got the following code there:
```
protected override async Task OnParametersSetAsync()
{
	if (CustomerId > 0)
	{
		Modus = EditMode.Edit;

		customer = await Customer.GetCustomerAsync(CustomerId.ToString());
		if (customer is not null)
		{
			Input = await customer.ToInputAsync();
			var state = await AuthStateTask;
			if ((await AuthorizationService.AuthorizeAsync(state.User, Policies.IS_MONEY_DECISION_USER)).Succeeded)
			{
				IsMoneyDecisionUser = true;
			}
		}
		else
		{
			alertService.AddAlert(new AlertBox
			{
				AlertType = AlertType.Danger,
				Message = $"Customer {CustomerId} could not be found"
			});
			navigationManager.NavigateTo("/Customers");
		}
	}
}
```

When I navigate within my blazor app using a Tags, it gets called once and everything works as expected. When I am on the page now and change the ID in the addressbar to some value which does not exist then the method is again called twice. The first time it uses the CustomerId I put in the address bar. The second time it uses the old ID. This results in a crash for me because the old ID could be found and it awaits some stuff while the first call to `OnParametersSetAsync();` navigates me back to the customer list when no customer could be found for the ID. 

It gets more confusing when the first call of `OnParametersSetAsync()` navigates me back to `/Customers `. This results in `OnInitiliazedAsync()` of `/Customers` gets invoked twice as well.

But I believe this has something todo with the crash in the second call of `OnParametersSetAsync()` because elements gets dispoed when the first call to this method navigates the user back.

Switching to render mode `Server` fixes this behaviour but it results in some noticeable performance drops for me.

**Comment by javiercn** [comment]
@MarvinKlein1508 that is expected.

The app first renders on the server and gets disposed. After the browser parses the document and runs the blazor boot script it starts the app again in "interactive mode", which is the second call that you are observing.

When you move from one page to another, the app is already started and only a client navigation happens.

When you type a value on the url, a full navigation happens, so the app again first renders on the prerenders on the server and then again is rendered on the browser.

**Comment by MarvinKlein1508** [comment]
@javiercn 

thanks for the explanation. But why does it call the method with the old value when doing a full navigation from an parameterized page?

e.g.
I am currently on the page  `/Customers/10000` and then I do a full navigation by typing another ID in the address bar, e.g. 20000.

`OnParametersSetAsync` is then called twice as expected. The first call has the value set to 20000. The second one to 10000. This second call results in issues for me because the first call is navigating the user back to another page while the second call is awaiting some stuff which gets disposed on navigating.

**Comment by javiercn** [comment]
@MarvinKlein1508 You might need to add `Cache-Control: no-cache` to the initial server response

**Comment by MarvinKlein1508** [comment]
Where do I add this? As far as I know I don't use [response caching ](https://docs.microsoft.com/en-gb/aspnet/core/performance/caching/middleware?view=aspnetcore-5.0)

**Comment by javiercn** [comment]
On `_Host.cshtml`

```
@{
   context.Response.Headers[HeaderNames.CacheControl] = "no-cache";
}
```

**Comment by MarvinKlein1508** [comment]
@javiercn Thanks!

In case anyone needs this info. In order to set this variable you need to import the namespace
`@using Microsoft.Net.Http.Headers`

Instead of context use HttpContext
`HttpContext.Response.Headers[HeaderNames.CacheControl] = "no-cache";`

After clearing the cache OnParametersSetAsync gets invoked once and not twice anymore because the first call is already redirecting the user.

**Comment by MarvinKlein1508** [comment]
@javiercn 

I need to correct myself. It still calls twice with different values for parameters at least it does in Firefox. In Edge it works fine.

I experimented a bit with the page and I notice another strange behaviour. I have overwritten the method `SetParametersAsync` with the following test code.

```
public override Task SetParametersAsync(ParameterView parameters)
        {
            IReadOnlyDictionary<string, object> parameter = parameters.ToDictionary();

            foreach (var item in parameter)
            {
                if(item.Key.Equals("Kundennummer") && item.Value is int kundennummer)
                {
                    Kundennummer = kundennummer;
                }
            }
            return Task.CompletedTask;
        }
```

`Kundennummer` is the` customer id` which is an page parameter
`@page "/Kunden/{Kundennummer:int}" `

I put a debug point in this method to see what's happening. I notice it calls `SetParametersAsync` when I switch the page. This does not seem right to me. 

https://www.youtube.com/watch?v=WiRtsVENtiA

What I want to achive is the following:
I want to check if the customer id exists in the database. If not, I want the user redirect to `/Customers` if it does, it should display the page.

Isn't there any easy way to achive this?

**Comment by mayur-ekbote** [comment]
Can you just accept the parameter as [Parameter] and then override OnSetParameters? Also, I think the additional renders are called because you are overriding the async method (not sure though)

**Comment by MarvinKlein1508** [comment]
@mayur-ekbote , @javiercn  has already clarified why `OnParametersSetAsync` is called twice. But I'm still trying to figure out what's happening in my posted video.

**Comment by MarvinKlein1508** [comment]
@javiercn could you take a look on my last question?

**Comment by javiercn** [comment]
@MarvinKlein1508 can you point me out to where in your repro this happens?
