### ISSUE TITLE
Custom fonts not working on blazor server side

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#30042]
Here is a repository that shows the problem.
https://github.com/musictopia2/LearningFontsFromAshleyFont 

If you go to the html page, you will see the custom font works.
but if you go to the main site, the custom font does not work.
i even did all the proper css part.

if i try to put under host razor page, then it gives errors and don't allow it.

I would be really disappointed if custom fonts are not supported in blazor.   If its not currently supported, hopefully, can be considered for .net 6 since there are some companies that require custom fonts to be used for a page.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

There is nothing specific about Blazor and webfonts. Can you clarify what error are you observing when using webfonts within Blazor?

**Comment by musictopia2** [comment]
I saw what happened after a while.  The online sample was wrong.  Eventually I was able to get it to work.
