### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by parveenLily** [dotnet/aspnetcore#30047]
Hi,
I am trying to build the servers folder and get the following error. when i cloned i guess that folder content did not push through. But is there a way not to build that folder. I really do not work with that content. Any tips will be appreciated.

C:\Users\lilyhome.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Could not find file 'C:\Users\lilyhome\source\repos\parveenLily\aspnetcore\src\submodules\googletest.git'. The source code won't be available via Source Link. [C:\Users\lilyhome\source\repos\parveenLily\aspnetcore\src\Http\Http.Features\src\Microsoft.AspNetCore.Http.Features.csproj]
C:\Users\lilyhome.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Could not find file 'C:\Users\lilyhome\source\repos\parveenLily\aspnetcore\src\submodules\MessagePack-CSharp.git'. The source code won't be available via Source Link. [C:\Users\lilyhome\source\repos\parveenLily\aspnetcore\src\Http\Http.Features\src\Microsoft.AspNetCore.Http.Features.csproj]

**Comment by BrennanConroy** [comment]
You need to do the second part of the `clone the source code` step
https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#step-1-clone-the-source-code

`git submodule update --init --recursive`

**Comment by parveenLily** [comment]
I managed to build it as par my need.
All the files in the VS solution explorer shows  ending delete. why and how i can fix that. screenshot attached.

![image](https://user-images.githubusercontent.com/52086691/107423862-e9108e80-6aea-11eb-89a7-d417144aef26.png)

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the questions asked here have been answered.

> All the files in the VS solution explorer shows ending delete. why and how i can fix that. screenshot attached.

If you're still running into this separate problem, please describe it in more detail in a new issue. We weren't sure of the problem nor how to reproduce it.
