### ISSUE TITLE
Improved C# Arrow implementation and Arrow Flight integration in dotnet

### ISSUE THREAD

**Issue by WilliamWhispell** [dotnet/aspnetcore#30051]
### Is your feature request related to a problem? Please describe.
protobuf is slow for moving bulk data, the arrow implementation in C# is very limited in functionality and is not fully tested. It would be great if we could easily spin up grpc services in c# with a zero-copy interchange designed for bulk data transfer.

### Describe the solution you'd like
A better C# Implementation of Apache Arrow and promotion of Arrow Flight protocol in .net 5

### Additional context
https://www.dremio.com/press-releases/dremio-announces-support-for-apache-arrow-flight-high-performance-data-transfer/
https://github.com/apache/arrow/blob/master/csharp/README.md

**Comment by JamesNK** [comment]
Hi

I believe the right place to discuss feature requests for the .NET Arrow Flight client is in its repository at https://github.com/apache/arrow/issues

I don't know what the project's status is in relation to the rest of .NET. I see @eerhardt wrote a lot of the .NET client and he might know more.

**Comment by eerhardt** [comment]
The Apache Arrow implementation is maintained by the Apache Arrow maintainers/contributors. Any issues with the C# implementation can be logged in the [project's JIRA](https://issues.apache.org/jira/projects/ARROW/issues).

With the `3.0.0` release, there is an initial implementation of an Arrow Flight + ASP.NET Core library: https://www.nuget.org/packages/Apache.Arrow.Flight.AspNetCore/. See the [TestWeb project](https://github.com/apache/arrow/tree/master/csharp/test/Apache.Arrow.Flight.TestWeb) for an example on how to use it. Try it out and see if it meets your needs. If it doesn't, please send feedback (either on the [Arrow dev list ](https://arrow.apache.org/community/) or on JIRA issues).

> the arrow implementation in C# is very limited in functionality and is not fully tested

Progress is being made, slowly on an "as needed" basis. Help on the project is welcome! Feel free to grab an existing issue from the JIRA project, or open a new one and propose a change.
