### ISSUE TITLE
Docker file: aspnetcore/src/Servers/Kestrel/samples/Http2SampleApp/Dockerfile

### ISSUE THREAD

**Issue by parveenLily** [dotnet/aspnetcore#30053]
The docker file is buiding a docker image of asnet 2.2 linux image while we are building a 6.0 project.
Tried to build with 5.0 but fails with error: "dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.0/dotnet-dev-win-x64.2.2.0.zip is not available.
Failed to install dotnet from public location."

So, is there a valid 6.0 image yet or is it possible to have 5.0 available for download.

thanks!

**Comment by BrennanConroy** [comment]
Triage: We don't use that file, and haven't since 2.2 looks like. We'll just delete the docker file and scripts.

**Comment by BrennanConroy** [comment]
If you want to use docker images for your app, take a look at https://hub.docker.com/_/microsoft-dotnet-aspnet/

**Comment by parveenLily** [comment]
Is it possible to provide a docker file example for this specific kestrel configuration?

**Comment by Tratcher** [comment]
@parveenLily what's special about this configuration?
