### ISSUE TITLE
Issue with enable/disable submit button in Forms - Blazor Wasm 

### ISSUE THREAD

**Issue by AnkitSharma-007** [dotnet/aspnetcore#30069]
I am trying to disable/enable a submit button of a Form having custom validations in a Blazor WASM application.

Repo - https://github.com/AnkitSharma-007/Blazor-Form-issue

I have followed the steps mentioned in the official docs - https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#enable-the-submit-button-based-on-form-validation

The form validations of all the fields are getting triggered as the user interacts with any one field. The doc suggest two approach:

1. Don't use a `ValidationSummary` component on the form.
    - I need to show custom validation error message on the screen so this options doesn't work for me.
    
2. Make the `ValidationSummary` component visible when the submit button is selected (for example, in a `HandleValidSubmit` method)
   - I don't know how this is supposed to work. The submit button is disabled until all the validations are passed, so I cannot click on the button and hence the `HandleValidSubmit` method cannot be invoked. Once the form is valid, I will click the button but now there is not validation errors so what is the point of showing `ValidationSummary`.

Do we have any clean approach to achieve this? Or have I missed something in the docs.

Any help is appreciated. 

Thank you

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
Two ways you could do this:

1. In the `OnFieldChanged` handler, you could use DataAnnotations APIs directly to check the model's validity state without triggering Blazor's validation APIs.
2. Or, you could ask the edit context whether all the fields were filled out before asking to validate them. Example: https://gist.github.com/SteveSandersonMS/67450524e3281641e293f7aa26acbd6a

**Comment by AnkitSharma-007** [comment]
Thanks a lot for your suggestions @SteveSandersonMS. I used the second approach and it works perfectly.
