### ISSUE TITLE
Events Not Firing in Code-Behind Blazor Components

### ISSUE THREAD

**Issue by MarkOverstreet** [dotnet/aspnetcore#30060]
I am trying to move to Blazor code-behind files and found what appears to be a bug which is that events are not fired.  For example, here is a simple test using in-line code for a razor page....

```

@page "/Test"

<h1>Test</h1>

<select @onchange="OnSelectionChanged">
    <option value="Jan">Jan</option>
    <option value="Feb">Feb</option>
    <option value="Dec">Dec</option>
</select>

@code {

    private void OnSelectionChanged(ChangeEventArgs e)
    {
        Console.WriteLine(e.Value.ToString()); // this works
    }
}

```
The OnSelectionChanged method is called.  However if we remove this code block and move it to a code-behind file, the page works the same except the method is never called when you select a different value in the drop down.

```
    public partial class Test
    {
        public void OnSelectionChanged(ChangeEventArgs args)
        {
            Console.WriteLine(args.Value.ToString());  // this does not get called
        }
    }

``` 
I am using VS2019 and .NET5.

**Comment by javiercn** [comment]
@MarkOverstreet thanks for contacting us.

Your partial class is not correctly defined. It needs to inherit from ComponentBase and be on the same namespace as the generated code for the class.

If you inspect the assembly with something like ILSpy you'll see that you have two differrent Test classes defined.

**Comment by MarkOverstreet** [comment]
Thanks for the tip.  I added this...

public partial class Test: ComponentBase

and events started working!  I would suggest adding some documentation on how to setup code-behind files since I found very little when I googled it.   Or better yet, how about updating VS2019 so it adds these code-behind files correctly by default like it has for twenty years :)
