### ISSUE TITLE
Unable to publish Blazor app because path length

### ISSUE THREAD

**Issue by astrowalker** [dotnet/aspnetcore#30067]
### Describe the bug

I have Blazor web client project which I can run OK both from Visual Studio 2019 (16.8.4) and from command line. Now I would like to publish this project into local folder (I used the defaults -- "bin\Release\net5.0\browser-wasm\publish\"). When I hit Publish I got this output:

> C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(237,5): Warning MSB3026: Could not copy "C:\Users\macias\.nuget\packages\microsoft.aspnetcore.components.webassembly.authentication\5.0.3\staticwebassets\AuthenticationService.js" to "D:\temp\Xxxxxxx\Aaa-AAA\PpppppppppppOooooo\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz.WebBlazor\Client\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js". Beginning retry 1 in 1000ms. Could not find a part of the path 'D:\temp\Xxxxxxx\Aaa-AAA\PpppppppppppOooooo\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz.WebBlazor\Client\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js'. 

The source file exists, the destination directory exists. I can copy the file manually, no problem. 

When I copy the file myself first, and then try to publish I got extra error first stating

> C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk.Publish\targets\CopyTargets\Microsoft.NET.Sdk.Publish.CopyFiles.targets(50,5): Warning MSB3231: Unable to remove directory "D:\temp\Xxxxxxx\Aaa-AAA\PpppppppppppOooooo\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz\Xxxxxxx.Yyyyyy.Zzzzzzzzzzzzzzzzzz.WebBlazor\Client\obj\Release\net5.0\browser-wasm\PubTmp\Out\". Could not find a part of the path 'AuthenticationService.js'.

### To Reproduce

Create example Blazor app located in flat/short directory, like d:\test. This will work.

Create example Blazor app located in somewhat longer path (as above). This will work initially, but then just install nuget package to web client project "Microsoft.AspNetCore.Components.WebAssembly.Authentication" and this will tip over the path limit -- this won't work (i.e. you will not be able to publish web client).

#### Issues found

I see here several issues which I think should be addressed:

* the error messages are misleading, "cannot copy" is maybe accurate internally, but should be spelled out as "path is too long"
* more serious one -- since total length path in Windows is limited to 260 characters, it is good to take user part and "infrastructure" part into consideration. The latter is this sequence "\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js" (it is 145 characters long). It means the user controls only 115 characters. It might seem like a lot but after you move from naming your project "BlazorApp1" you can quickly exceed the limit. Besides common sense tells that taking majoriy of space from the user is kind of unfair :-)
* maybe minor thing, but still, it is kind of "surprise" effect when you can build you app, run it (path length is not exceeded), and yet you cannot publish just because of the way publish internally works (I can change the publish target folder, but the error is about "obj" not target)

### Further technical details
ASP.NET 5.0

PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.513 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@astrowalker thanks for contacting us.

I don't think there's anything blazor specific here, I believe this is likely an MSBuild behavior and would be up to them to fix it. As to why this happens, it might be that .NET uses an older Windows API that does the path length check (this was relaxed a few windows releases ago) and I imagine the OS copy isn't affected by the path restriction.

In this cases I would suggest shortening the path to avoid issues.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like there is no pending action for us here. Given that this is not a feedback we've heard much we recommend you follow up with the MSBuild team at https://github.com/dotnet/msbuild

**Comment by astrowalker** [comment]
I was under impression that it is Blazor thing to create and control the temporary output, so since there is limit on path length using something such elaborate "\obj\Release\net5.0\browser-wasm\PubTmp\Out\wwwroot\_content" takes significant portion of rare resource and should be more modest (after all during just build it is). But of course if/when MSBuild would drop the path limit this concern (then) would be non-existent.

Reposted report here: https://github.com/dotnet/msbuild/issues/6149
