### ISSUE TITLE
Hosting bundle template strings

### ISSUE THREAD

**Issue by steveoh** [dotnet/aspnetcore#30071]
The 5.0.3 hosting bundle for windows screen is fouled up. The install works fine but the templates are still templates.

![image](https://user-images.githubusercontent.com/325813/107541637-9388c000-6b84-11eb-8819-0706e9e6115d.png)

**Comment by joeloff** [comment]
@wtgodbe didn't you fix this issue already?

**Comment by wtgodbe** [comment]
Yes, in the March release
