### ISSUE TITLE
VS Code: After type "<InputText" in the last line, the list of available command attributes is not displayed completely.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#30072]
**Azure DevOps work item:** [1271806](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1271806)

**Testcases Affected** [[5.0] SimpleBlazorRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.8/E2EWalkthroughs/VS/AspNetCore30/30_SimpleBlazorRazorEditingWithVSCode.md)

**Platform**
- [x] Windows
- [ ] macOS
- [x] Linux

**Repro Steps**
1. Install the latest version of [VS Code](https://code.visualstudio.com/Download)[1.52.1].
1. Install the latest version of[ C# extension](https://github.com/OmniSharp/omnisharp-vscode/releases)[v1.23.9-beta2].
1. Open the Command Prompt (do not run as administrator)
1. Create a project and open it using VS Code:
   ```
    md Blazor 
    cd Blazor
    dotnet new blazorserver 
    code .
   ```
1. In VS code, Open Pages/index.razor, type "<InputText" at the last line, press Space key, then press Ctrl + Space

**Note:** 

1. If type "<InputText"" at the other lines of the razor file, instead of the last line, this issue not repro.
2. When I install the C# extension with csharp-1.21.12/csharp-1.22.2/csharp-1.23.9, this issue still repro.

**Actual Result**
1. After typing "<InputText" in the last line, there is no complete list of available command attributes.

![image](https://user-images.githubusercontent.com/66412474/106257362-66b8dc80-6257-11eb-8750-a71e1b063597.png)

**Expected Result**
  
![image](https://user-images.githubusercontent.com/66412474/106257381-6c162700-6257-11eb-95cb-15b6b606889e.png)

**Comment by EmilyFeng97** [comment]
@NTaylorMullen This issue not repro on the last  C# extension.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen This issue not repro on the last C# extension[v1.23.10].

Awesome! We just pushed an update too. I'll close this out
