### ISSUE TITLE
Migrate from FxCopAnalyzers to NetAnalyzers

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#30099]
FxCopAnalyzers package is deprecated. The repository should use `Microsoft.CodeAnalysis.NetAnalyzers` instead.

See [Migration guide](https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers).

**Comment by javiercn** [comment]
@Youssef1313 thanks for filing this issue.

@Pilchie don't we use the newest and greatest's? If not, then I guess we should add this to the infrastructure epic

**Comment by Pilchie** [comment]
I'm out of the loop, seems like we should probably update.

**Comment by javiercn** [comment]
@Pilchie I'll add it to the infrastructure epic

**Comment by sharwell** [comment]
I made this change for tooling repository in https://github.com/dotnet/aspnetcore-tooling/pull/3102.

**Comment by javiercn** [comment]
@sharwell does this mean we don't have anything to do here?

(Thanks BTW 😄)

/cc: @dougbu

**Comment by sharwell** [comment]
@javiercn I haven't done anything for this repository. Was just showing a reference link to make it easier for whoever implements it here.

**Comment by javiercn** [comment]
@sharwell got it!

Thanks in any case, that helps!
