### ISSUE TITLE
QueryHelpers.AddQueryString generated malformed urls when using hashbangs

### ISSUE THREAD

**Issue by shoe-diamente** [dotnet/aspnetcore#30100]
### Describe the bug

Calling `QueryHelpers.AddQueryString` on a url with "hashbangs" (eg. http://localhost/abc/#/def/) results in a malformed url (e.g. `http://localhost/abc/?param1=value1&param2=value2#/def/`).

### To Reproduce

```
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.WebUtilities;
					
public class Program
{
	public static void Main()
	{
		var originalUrl = "http://localhost/abc/#/def/";
		var parameters = new Dictionary<string, string>
		{
			{ "param1", "value1" },
			{ "param2", "value2" },
		};
		var newUrl = QueryHelpers.AddQueryString(originalUrl, parameters);
		Console.WriteLine($"{newUrl}");
	}
}
```

[.NET Fiddle here](https://dotnetfiddle.net/3mbTte)

### Further technical details
- ASP.NET Core 5.0

- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VSCode Version: 1.53.1

**Comment by Tratcher** [comment]
That result looks correct, the fragment portion of a uri (`#/def/`) always comes after the query portion (`?param1=value1&param2=value2`). That said, from your example it looks like you assumed the `#` was just another character in the uri path component? If you want to use `#` in a uri path it needs to be escaped as `%23`.  Try this:
`var originalUrl = "http://localhost/abc/%23/def/";`

**Comment by shoe-diamente** [comment]
Oh right. That messes up with hashbang routings of client side frameworks but I now understand the reasoning. Thanks.
