### ISSUE TITLE
JwtBearerEvents.OnAuthenticationFailed exception message is unclear/obfuscated 

### ISSUE THREAD

**Issue by flamaniac** [dotnet/aspnetcore#30112]
When JWTtoken is expired message looks like:
"Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'."
Dates are missing.

Related to: 
https://github.com/dotnet/aspnetcore/issues/23302
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1591

Both issues closed but bug still present in net5.0;)

Maybe this is solution? 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

**Comment by blowdart** [comment]
We can't fix this, it's up to AzureAD in their library. I suggest reopening a bug in the AzureAD repo.

**Comment by blowdart** [comment]
Closing as external

@keegan-caruso IDX logs come from Wilson, so this isn't ours but over on your side.
