### ISSUE TITLE
Debugging Blazor WebAssembly rendered in WebView2

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#30117]
With the latest VS2019 Preview it is possible to activate JavaScript debugging for applications that use the WebView2 controls. Unfortunately there seem to be no way out of the box to tell the WebView2 to connect to the inspecturi that you specify in the launchSettings.json for "Blazor Webassembly in Browser debugging" .

I think it's probably not so difficult to pass the inspecturi to the webview2 so that it provides the same debugging experience like a browser.

I would like to know how the inspecturi is passed to the browser and in the same time ask for future support for Blazor Webassembly debugging in native apps with the WebView2 control.

**Comment by TFTomSun** [comment]
In case someone is interested: It's possible to debug into the blazor webassembly app by passing some additional arguments to the WebView2 controls.

What I did:
- I inspected which parameters are passed to the browser, by replacing the browser executable with a small app that dumped out all application arguments
-  then I passed the same arguments to the WebView control:

```csharp

using Microsoft.Web.WebView2.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Blazor.WebAssembly.FormsHost
{
    public partial class WebForm : Form
    {

        [Obsolete("For designer purposes only", true)]
        public WebForm() : this(null)
        {
        }

        public WebForm(string url)
        {
            Url = url;
            InitializeComponent();
        }

        public string Url { get; }

        protected override async void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            if (this.Url != null)
            {
                var browserArgs = new object[]
                         {
                            " --disable-background-networking",
                            "--disable-background-timer-throttling",
                            "--disable-backgrounding-occluded-windows",
                            "--disable-breakpad",
                            "--disable-client-side-phishing-detection",
                            "--disable-default-apps",
                            "--disable-dev-shm-usage",
                            "--disable-renderer-backgrounding",
                            "--disable-sync",
                            "--metrics-recording-only",
                            "--no-first-run",
                            "--no-default-browser-check",
                            @"--user-data-dir=C:\Users\tftom\AppData\Local\Microsoft\VisualStudio\16.0_f9005852\WebTools\EEFB0562_225BE6B4",
                            "--remote-debugging-port=64204"
                        };
                var finalargs = string.Join(' ', browserArgs);
                var environment = await CoreWebView2Environment.CreateAsync(null, null,
                    new CoreWebView2EnvironmentOptions()
                    {
                      

                        AdditionalBrowserArguments = finalargs
                    });

                await this.webView21.EnsureCoreWebView2Async(environment);
                this.webView21.CoreWebView2.Navigate(this.Url);
            }
        }

    }
}


```

- Unfortunately you need to keep the "Launch Browser" option activated, otherwise the AspNetCore App is not started with the JavaScript Debugger Engine, but as a workaround I choose the canary version of the edge and replaced the exe with an empty .NET application. 

The result is a AspNetCore Hosted Blazor WebAssembly app, where the host opens a native forms window instead of a browser to render the web assembly app. The startup performance is much better than using the Browser.

**Comment by javiercn** [comment]
@TFTomSun thanks for contacting us.

We are glad you were able to figure out a solution to this problem.

We are closing this issue since there is no further action for the team here.

**Comment by TFTomSun** [comment]
@javiercn Is there a way to determine the remote debugger port that is passed to the browser process? I discovered that this port changes from time to time. Maybe there's a way to access it from the Asp.NET Core App? The port is logged in the visualstudio-js-debugger.txt log file. e.g.

> [17:51:33.303 UTC] spawn('C:\Users\<user>\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe', ["--remote-debugging-port=55872","--no-first-run","--no-default-browser-check","--user-data-dir=C:\\Users\\<user>\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_f9005852\\WebTools\\EEFB0562_225BE6B4","about:blank"])

**Comment by javiercn** [comment]
@TFTomSun I'm not sure about it. Check out launchSettings.json for it.

@captainsafia will know better.

**Comment by TFTomSun** [comment]
@captainsafia The solution I described above is still a bit hacky. For example I hardcoded the remote debugging port and would need to change it whenever the Asp.NET Core infrastructure uses another port. Additionally I have to keep the "launchBrowser" setting to true, because the whole debug adapter is not started otherwise. To avoid having a the browser started, I replaced the browser executable with an empty app.

It would be good if I could:
- get the remote debugging port on which ASP.NET Core is waiting for the app to connect
- tell the debugging infrastructure, that I provide my own application (the win forms window with the blazor webassembly app inside) which will connect to the debugging service instead of a launched browser
- avoid launching a seperate browser

**Comment by captainsafia** [comment]
@TFTomSun Interesting workaround!

So, the debugging port that is used is randomly selected by the IDE. However, it is cached under the ".vs" directory adjacent to the solution file you are using. I can't recall the exact file name at the moment but it should be pretty quick to find.

As for the other arguments passed to the browser, those are determined by the underlying JavaScript debugger infrastructure. Copying the properties from the log file should suffice for your purposes though.

**Comment by TFTomSun** [comment]
@captainsafia thanks, I'll check for the port in the .vs folder.
Is there a possibility to avoid that a browser is launched, but keeping the debugging infrastructure running?

**Comment by captainsafia** [comment]
> Is there a possibility to avoid that a browser is launched, but keeping the debugging infrastructure running?

Not at the moment. The debugging infrastructure relies heavily on the Chrome DevTools Protocol, which relies on a Chromium-based browser running. Even in an Electron-ish scenario, you'd still need to launch a browser. It just so happens that the browser in that case is an Electron-shell.

**Comment by TFTomSun** [comment]
exactly, but that lunch happens from within my forms window, which contains the WebView2 control (which is released by Microsoft and runs the new chrome based edge browser underneath). I think that's a valid scenario, to be able to debug into the browser frontend when it's running in a WebView2 control.
