### ISSUE TITLE
launchSettings.json files should not be automatically re-created if deleted

### ISSUE THREAD

**Issue by fuzl-llc** [dotnet/aspnetcore#30129]
### Describe the bug

launchSettings.json files are automatically re-created for Blazor web assembly projects after being explicitly deleted.

### To Reproduce

You should be able to use any ASP.NET core project that hosts Blazor "sub projects," but I've tested with this project:

https://github.com/fuzl-llc/MultipleHostedBlazorApps

1. Open the solution, expand both "client" projects, and delete the \Properties\launchSettings.json files.  They are not needed in this case as the Blazor projects are only loaded from within the main host project and we have a launchSettings.json file in that "Server" project.

2. Close and re-open the solution.

3. Notice that both launchSettings.json have been re-created.

I have to manually delete them every time the solution is opened which is really frustrating.  It could also cause confusion for new developers as they might see these files and think they do something when, at least as far as I can tell, they don't do anything in this scenario of running only the main server project and letting the "sub" Blazor projects be loaded from the host.  This could be very frustrating to a developer who can't understand why changes to these files don't do what they expect.  Also, just from a cleanliness perspective, there is not good reason to keep files around that aren't needed.

### Exceptions (if any)

None, just annoying and potentially misleading as described above.

### Further technical details

- ASP.NET Core version
5.0.3

- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.400 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2019 Community 16.8.5.

**Comment by javiercn** [comment]
@fuzl-llc thanks for contacting us.

This is not a runtime issue. In order for you to get a better and faster answer we suggest you file this issue through the Visual Studio report a problem dialog. See details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

/cc: @BillHiebert

**Comment by fuzl-llc** [comment]
Thanks for the info.  After starting to report the issue there, I found an existing issue which addresses the problem.  In case anyone finds this issue here, here's the link to the solution over there:

https://developercommunity2.visualstudio.com/t/launchsettingsjson-is-created-every-tim/648360?entry=problem&ref=native&refTime=1613160176297&refUserId=f448ad0b-07d4-4c1b-887a-7479501f4fbc

...which basically involves adding this to your project  file:

<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
