### ISSUE TITLE
SignalR streaming client can hang indefinitely if it does not receive a Completion on the streaming Channel

### ISSUE THREAD

**Issue by koopaking3** [dotnet/aspnetcore#30128]
I have a pretty generic SignalR server-to-client streaming implementation with a .NET client. The hub exposes a streaming method like so:

```
public ChannelReader<byte[]> Retrieve(Guid id, CancellationToken cancellationToken)
{
    var channel = Channel.CreateBounded<byte[]>(_limit);
    _ = WriteItemsAsync(channel.Writer, id, cancellationToken);
    return channel.Reader;
}

private async Task WriteItemsAsync(ChannelWriter<byte[]> writer, Guid id, CancellationToken cancellationToken)
{
    Exception localException = null;
    try
    {
        //loop and write to the ChannelWriter until finished
    }
    catch (Exception ex)
    {
        localException = ex;
    }
    finally
    {
        writer.Complete(localException);
    }
}
```

and the client consumes the stream like this:

```
var channel = await hubConnection.StreamAsChannelAsync<byte[]>("Retrieve", _guid, cancellationTokenSource.Token);

while (await channel.WaitToReadAsync())
{
    while (channel.TryRead(out var data))
    {
        //handle data
    }
}
```

The client feeds the stream into a data flow pipeline and the server will call `Complete` on the `Channel` when that particular stream is done. The problem is that **very seldomly** (once every few thousand streaming sessions) the entire pipeline will hang completely, with the effect being that the client thinks it is still processing a stream and won't request any further streams from the server, causing the whole pipeline to come to a halt. 

My server logs will show that the server has called `Complete` on the `ChannelWriter` in the hub, but that the client is still blocking at `await channel.WaitToReadAsync()` as if it has not seen the `Complete` message. Because it has only happened a handful of times, I don't have steps to reproduce it yet and I am not 100% positive SignalR is the culprit, but an answer to the following would help me narrow it down.

So my question: when the hub calls `Complete` on a streaming `Channel`, is that `Complete` message guaranteed to make it to the client, or is it possible that the message doesn't make it in a rare case and the client blocks forever on a stream that is effectively closed? Obviously normal SignalR messages are "fire and forget", but do the completion messages that SignalR sends under the hood for streams follow the same rules?

My workaround right now is to use the `CancelAfter` method of a `CancellationTokenSource` to allow me to timeout the streaming client if it hasn't received any messages on the open stream within a given time span. I'll be able to share more data when the next hang occurs.

**Comment by BrennanConroy** [comment]
Messages over SignalR are as reliable as TCP. Basically what this means is that either you get the message, or the connection closes. In both cases the channel on the client side will be completed.

Attaching to the process when it's hanging (or getting a dump) would help identify who is hanging.

**Comment by koopaking3** [comment]
@BrennanConroy thank you for the quick reply. So are "internal" SignalR messages (such as when SignalR sends a message to signal that a stream is completed) treated differently than "normal" hub broadcasts to clients (e.g., using `Client.All`)? My understanding is that those broadcasts are not guaranteed and are susceptible to missed messages in some scenarios, for example if too many message are sent in quick succession from the hub and the client falls behind on the buffer.

**Comment by BrennanConroy** [comment]
Nope, all messages are treated the same. If the client falls behind on reading the buffer, the connection will be closed.

**Comment by koopaking3** [comment]
Thanks again! I'll close the issue and reopen later if I'm able to get a dump and there is a related issue.

**Comment by davidfowl** [comment]
Right it should never hang forever. It'll either send the complete message or disconnect. Either way, a hang would be a bug in the client
