### ISSUE TITLE
Undo component governance skip

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30126]
We skipped the task as part of https://github.com/dotnet/aspnetcore/pull/30125 because it was timing out in our builds. Once https://github.com/microsoft/componentdetection-azdo/issues/181 is resolved this should be undone.

**Comment by wtgodbe** [comment]
> microsoft/componentdetection-azdo#181 was closed w/ no action and the team (@tevoinea in particular) let us know they were focused on the auto-injection scenario. We should have just closed #30126 at the same time.
