### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly.Authentication fails authentication using the Password grant type

### ISSUE THREAD

**Issue by BjornDeRijcke** [dotnet/aspnetcore#30136]
### Describe the bug
I'm creating a Blazor web assembly app. I want to have a login page in the app itself, and not be redirected to a login page on the server.
I am using the 'WebAssembly hosted app with Identity Server' template as discussed here: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)

When adding an [Authorize] attribute to a serverside controller, 401 is always returned. `_httpContextAccessor.HttpContext.User` is also always the default unauthorized placeholder user.

Using the suggested library "Microsoft.AspNetCore.Components.WebAssembly.Authentication"

I have implemented a custom `AuthenticationStateProvider` and `Http.DelegatingHandler`.

### To Reproduce
Setup using the template "Blazor WebAssembly app", select asp.net core hosted and set Authentication to individual users accounts (store accounts in-app)

High level setup: 
 - Create a custom AuthenticationStateProvider that checks if an access token is present inside the browser session
 - Create a custom HttpMessageHandler that adds the access token to the request headers
 - Change the default startup setup for the client a bit, to use our custom StateProvider + HttpMessageHandler
 - Create a login page that calls `[POST] {server}/connect/token` with user password and name and store this token in the sessions, so our HttpMessageHandler can add it to server api requests, and that the AuthenticationStateProvider can see it is filled in, so we can use the `<AuthorizeView>` elements inside the blazor app

Code: 

- Create a new AuthenticationStateProvider:
This customer state provider should check inside the browser session if an access token exists.
```
public class CustomAuthStateProvider : AuthenticationStateProvider
{
    private string _accessToken;
    private readonly ISessionStorageService _sessionStorageService;

    public CustomAuthStateProvider(ISessionStorageService sessionStorageService)
    {
        _sessionStorageService = sessionStorageService;
    }

    public override async Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        try
        {
            _accessToken = await GetAccessTokenAsync();

            //When no accessToken found, the user is not allowed
            if (string.IsNullOrEmpty(_accessToken))
            {
                return SetAuthStateAnonymousUser(false);
            }

            return GetAuthStateFromAccessToken();
        }
        catch (Exception)
        {
            return SetAuthStateAnonymousUser(false);
        }
    }

    public async Task<string> GetAccessTokenAsync()
    {
        if (await _sessionStorageService.ContainKeyAsync("ac_tk"))
            return await _sessionStorageService.GetItemAsync<string>("ac_tk");

        return null;
    }

    public AuthenticationState GetAuthStateFromAccessToken()
    {
        return new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity(ParseClaimsFromJwt(_accessToken), "jwt")));
    }

    public async Task SetAuthStateLoggedIn(bool notify = true)
    {
        _accessToken = await GetAccessTokenAsync();

        if (string.IsNullOrEmpty(_accessToken))
            throw new AccessTokenMissingException();

        if (notify)
        {
            var state = GetAuthStateFromAccessToken();
            NotifyAuthenticationStateChanged(Task.FromResult(state));
        }
    }

    public AuthenticationState SetAuthStateAnonymousUser(bool notify = true)
    {
        _accessToken = null;
        ClaimsPrincipal anonymousUser = new ClaimsPrincipal(new ClaimsIdentity());
        AuthenticationState authState = new AuthenticationState(anonymousUser);

        if (notify)
        {
            NotifyAuthenticationStateChanged(Task.FromResult(authState));
        }

        return authState;
    }

    private IEnumerable<Claim> ParseClaimsFromJwt(string jwtToken)
    {
        JwtSecurityTokenHandler handler = new JwtSecurityTokenHandler();
        JwtSecurityToken jwtSecurityToken = handler.ReadJwtToken(jwtToken);

        return jwtSecurityToken.Claims;
    }
}
```

- Create a custom HttpMessageHandler:
This handler will add the Authorization using the access token we stored in the session of the browser.
```
public class AuthDelegatingHttpMessageHandler : DelegatingHandler
{
    private readonly ISessionStorageService _sessionStorageService;

    public AuthDelegatingHttpMessageHandler(ISessionStorageService sessionStorageService)
    {
        _sessionStorageService = sessionStorageService;
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request.Headers.Authorization == null && await _sessionStorageService.ContainKeyAsync("ac_tk"))
        {
            var accessToken = await _sessionStorageService.GetItemAsync<string>("ac_tk");
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
        }

        return await base.SendAsync(request, cancellationToken);
    }
}
```

- Changes to startup:

```
services.AddHttpClient("Blazor.ServerAPI", client => client.BaseAddress = new Uri(baseAddress))
                .AddHttpMessageHandler<AuthDelegatingHttpMessageHandler>();
services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("Blazor.ServerAPI"));

services.AddAuthorizationCore();
services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>();
services.AddScoped<AuthDelegatingHttpMessageHandler>();
```

- Create a log  in page, and when the customer has entered his credentials, use the `IdentityModel.Client` library to get an access token from the IdentityServer:

```
var disco = await _publicClient.Client.GetDiscoveryDocumentAsync();
if (disco.IsError)
{
    return new AuthenticationResponse { FailureReason = AuthenticationFailureReason.Unknown };
}

// request token
var tokenResponse = await _publicClient.Client.RequestPasswordTokenAsync(new PasswordTokenRequest
{
    Address = disco.TokenEndpoint,
    ClientId = "ZeroFriction.Portal.Client",
    UserName = userName,
    Password = password,

    Scope = "zf.portal.api openid"
});

// Set session
await _sessionStorageService.SetItemAsync("rf_tk", tokenResponse .RefreshToken);
await _sessionStorageService.SetItemAsync("ac_tk", tokenResponse .AccessToken);

// Send notification
await _authenticationStateProvider.SetAuthStateLoggedIn();
```

- Make a call to the WeatherForecastController as see that you always get a 401

### Exceptions (if any)
No exceptions, but authorization always fails, even though the Authorization header is present.
Authorization header, See image: [https://i.imgur.com/yYocf80.png](https://i.imgur.com/yYocf80.png)
No user, See image:  [https://i.imgur.com/T2S6nEA.png](https://i.imgur.com/T2S6nEA.png)

### Expected result
I expect the [Authorize] attribute to work for backend api controllers. We have correctly overridden the default AuthenticationStateProvider and httpclient behaviour and the token is added to the request to the backend api.

I expect the in-app login page to work inside Blazor using the suggested `Microsoft.AspNetCore.Components.WebAssembly.Authentication` library. We don't like the user being redirected to the backend because this breaks the flow and the UI.

### Further technical details
```
.net 5.0
Visual Studio Enterprise 2019 v16.8.5

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment]
Thanks for contacting us @BjornDeRijcke 

Microsoft.AspNetCore.Components.WebAssembly.Authentication is not part of the support we offer for authentication. You might be better off if you avoid using the package we provide all together, since it'll get in the way rather than help you in this case.

I'm not sure what is failing in your setup, but we strongly discourage the use of Resource Owner credentials flow and we don't plan to offer any guidance at the time on how to enable it.

We suggest posting this question to StackOverflow or looking at how to achieve this with Identity Server.

**Comment by BjornDeRijcke** [comment]
@javiercn Thank you for your answer. I see I should not use the 'WebAssembly.Authentication' package then. 

I have one question though, if you could spare the time:
When using the template that hosts the backend api, identity server and the razor files from one asp.net core project, why is it strongly discouraged to use the _Resource Owner credentials flow_ ? 

What difference does it exactly make having the browser `POST` username & password from the Blazor SPA opposed to redirecting to the login page of the Microsoft Identity UI, which also does a `POST` with the user credentials ? It's all from the same server anyway? it's just the url that is different. 

I would be very grateful if you could explain to me.

**Comment by javiercn** [comment]
@BjornDeRijcke resource owner credentials flow is an "obsolete" grant and was added as a compromise for people migrating from custom authentication systems to OAuth/OpenID Connect. 

Its use is discouraged because it couples the authentication mechanism to the authorization mechanism and prevents the application of best practices like multi-factor authentication and so on.
