### ISSUE TITLE
RedisCache doesn't implement disposable pattern correctly

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/aspnetcore#30139]
The [current implementation](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Caching/StackExchangeRedis/src/RedisCache.cs) flags [CA1063](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063).

**Comment by sharwell** [comment]
I find CA1063 adds a lot of complexity for a scenario (finalizers) that is never recommended (use SafeHandle instead). If the repository doesn't already closely follow this rule, I would suggest disabling it completely and using the simpler pattern of just making `Dispose()` virtual.

**Comment by Youssef1313** [comment]
@sharwell If there are going to be change either way, why not satisfy the rule and the framework design guidelines?

**Comment by shirhatti** [comment]
Triage: We don't want to turn on CA1063 in this repo. For the most part, we agree with @sharwell comments.
