### ISSUE TITLE
Share authentication cookies approach is not working when IdentityServer is enabled

### ISSUE THREAD

**Issue by ghostinside** [dotnet/aspnetcore#30146]
have 3 apps, the first one is the issuer of the application cookie

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            services.AddAuthentication("Identity.Application").AddCookie("Identity.Application", options =>
            {
                options.Cookie.Name = ".AspNet.SharedCookie";
                options.Cookie.Path = "/";
                options.Cookie.Domain = "localhost";
            });

            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("d:/dataprotection"))
                .SetApplicationName("SharedCookieApp");
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }`

the second app is the simple api app that successfully reads the cookie issued by the first app

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddControllers();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "TestAuthApi", Version = "v1" });
            });

            services.AddAuthentication("Identity.Application").AddCookie("Identity.Application");

            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("d:/dataprotection"))
                .SetApplicationName("SharedCookieApp");

            services.ConfigureApplicationCookie(options => {
                options.Cookie.Name = ".AspNet.SharedCookie";
                options.Cookie.Path = "/";
                options.Cookie.Domain = "localhost";
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "TestAuthApi v1"));
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
`

if we call the api of the second app the user will have property is authenticated = true & [Autorize] method will be accessible

`[HttpGet]
        [AllowAnonymous]
        [Route("test")]
        public void Test()
        {
            var r = HttpContext.User;
        }

        [HttpGet]
        [Authorize]
        [Route("testA")]
        public void TestA()
        {
            var r = HttpContext.User;
        }`

the third app is configured to use IdentityServier & shared cookie (unfortunately i can't set Auth Scheme to 'Application.identity' due to having error that the scheme already exists)

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            //services.AddMvcCore().AddApiExplorer();
            services.AddSwaggerGen();

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("Database_User")));

            services.AddDatabaseDeveloperPageExceptionFilter();

            services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

            services.AddAuthentication()
                .AddIdentityServerJwt();
                

            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo("d:/dataprotection"))
                .SetApplicationName("SharedCookieApp");
            
            services.ConfigureApplicationCookie(options => {
                options.Cookie.Name = ".AspNet.SharedCookie";
                options.Cookie.Path = "/";
                options.Cookie.Domain = "localhost";
            });

            services.AddControllersWithViews();
            services.AddRazorPages();
            services.AddResponseCompression();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseCors(builder => builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());
            app.UseResponseCompression();
            app.UseStaticFiles();

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.),
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("v1/swagger.json", "My API V1");
            });

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebAssemblyDebugging();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseIdentityServer();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("index.html");
            });
        }
`
but the shared cookie is not read & if we try to call the api, the user IsAuthenticated will be always false, would appreciate for helping me figure out what is wrong

P.S is the name 'Identity.Application' is mandatory for scheme to have shared cookie? if i change it, any app cant read the cookie

**Comment by ghostinside** [comment]
the reason for using shared cookies is that we have several apps build on .net 4.x and using membership, so we cant switch to token immediately

**Comment by blowdart** [comment]
Identity Server is, quite rightly, expecting to be the sole issuer of identity, that's what it actually does, it is its very purpose. Having Identity Server read another login cookie really goes against what it's designed for, It also has its own configuration for its own cookie names etc which we hide with our helpers, because we're also expecting Identity Server to be the sole issuer.

The preferred approach here would be add a custom database layer into identity server to read your existing database, and switch everything over to oauth and use the identity server as the issuer, rather than try to shim it with forwards compat, It would be more reliable.

In any case I'm afraid this is outside of our methods for IS, and this question would be better asked of [them directly](https://github.com/IdentityServer), as it's likely you'll have to drop our helpers, and use their much more flexible configuration classes.

**Comment by ghostinside** [comment]
@blowdart  appreciate for an explanation,  it is very helpful, will think over the better approach
