### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake ( Connection closed immediately ( prematurely ) after connecting

### ISSUE THREAD

**Issue by uzair1124** [dotnet/aspnetcore#30143]
### Describe the bug

I have been using Websockets in dotnet core , i am facing an issue in websockets in such a way that when i run websockets on localhost ( visual studio ) it works FINE but when i deployed(published) it on IIS & Samrter asp.net , it behaves unexpectedly different that it closes connection immediately (prematurely) after open connection ( successfully handshaked) and it giving error **The remote party closed the WebSocket connection without completing the close handshake**.
can u please guide me ? 

### Further technical details
- ASP.NET Core version 2.2
- Include the output of `dotnet --info`  (  OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.813 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App])
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version  (version 2019)

**Comment by shirhatti** [comment]
> ASP.NET Core version 2.2

We recommend upgrading to a supported version.

> The remote party closed the WebSocket connection without completing the close handshake

This sounds like an offending client and/or simply a dropped connection. Do you have any reason to suspect this is a problem?

**Comment by uzair1124** [comment]
which supported version ? @shirhatti

**Comment by shirhatti** [comment]
See https://dotnet.microsoft.com/platform/support/policy/dotnet-core for the up-to-date support policy

**Comment by uzair1124** [comment]
Thanks @shirhatti
