### ISSUE TITLE
WebApplicationFactory: Proxy cannot be specified for all created HttpClient instances

### ISSUE THREAD

**Issue by mmarkwort** [dotnet/aspnetcore#30144]
### Is your feature request related to a problem? Please describe.

I want to use the [Gatling load test tool](https://gatling.io) to load test the application. Gatling starts a proxy server to record the requests.

Unfortunetely, the client that is created by `WebApplicationFactory.CreateClient` does not support proxy use and the recorder won't see any requests made by this client.

### Describe the solution you'd like
Add possibility to add a proxy to the `HttpClient` instance created by `WebApplicationFactory.CreateClient`.

**Comment by javiercn** [comment]
@mmarkwort thanks for contacting us.

WebApplicationFactory uses an in memory server, no request/response goes through the network.
