### ISSUE TITLE
Use of AuthorizeView/Authorization in a non-routable/library Blazor Component

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#30153]
Is it possible to use Authorization/AuthorizeViews within a non-routable Blazor Component hosted out of an MVC project?

Is there a way to easily passing the authorization built around the MVC's UserManager/Claims so that <AuthorizeView> can consume the claim(s)?

I see many examples for a Blazor Server App, but nothing on how to do this for a Blazor Component.

**Comment by javiercn** [comment]
@vflame thanks for contacting us.

`AuthorizeView` is completely independent of the routing system and can be used in that context without issue.

> Is there a way to easily passing the authorization built around the MVC's UserManager/Claims so that can consume the claim(s)?

There's nothing you would need to do here other than wrapping everything within CascadingAuthenticationState for it to flow down to the AuthorizeView.

The user principal will flow to the Blazor application automatically. As for the UserManager and other Identity concepts, we don't recommend their usage inside Blazor, depending on what you try to do "your mileage might vary".
