### ISSUE TITLE
Project Breaks When Moving File to Another Folder

### ISSUE THREAD

**Issue by Anzel13** [dotnet/aspnetcore#30160]
In **Visual Studio 2019 16.9.0 Preview 4** I moved a razor component from one folder to another in a Blazor application and the project no longer builds and I get errors in the file as if the code behind is no longer there.

I simply moved a razor component and its code behind file from one folder to another within the same project.  Specifically I took a component named "**Login.razor**" and its code behind "**Login.razor.cs**" and moved them from one folder ("**Home**") to another folder ("**Users**").  I did this using **Solution Explorer**.  Once the files were moved the razor page no longer recognizes the code behind.

As an experiment **I completely deleted both files**, checked my project into source control, then created a brand new control with the same name "Login.razor" and "Login.razor.cs" and Visual Studio is **STILL** giving me the same errors.

![image](https://user-images.githubusercontent.com/30503420/107831332-72c29500-6d53-11eb-91a6-43cd6cf89b9f.png)

I am using **Visual Studio 2019 16.9.0 Preview 4** and my project is **.NET Core 5 Blazor Web Assembly** which is server hosted.

![image](https://user-images.githubusercontent.com/30503420/107831269-4870d780-6d53-11eb-8f1c-43b171ff4675.png)

I have cleaned, rebuilt the solution.  I have restarted Visual Studio.  I have tried to even use the current/release version.

**Comment by Anzel13** [comment]
More potential solutions that I've tried using the latest release.

![image](https://user-images.githubusercontent.com/30503420/107832654-9cc98680-6d56-11eb-8e84-94e8b2c44081.png)


1. I tried completely **deleting** and **recreating** the component.
2. I tried using **Source Control Explorer** to try and move it in source control.
3. I tried deleting the files in the "**obj/Debug**" directory and rebuilding.
4. I even tried **MOVING THE COMPONENT BACK** to its original location.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please confirm whether the solution builds successfully from the command line using `dotnet build`?
