### ISSUE TITLE
Perform a pass cleaning up the web templates

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30162]
* Could we move the DevServer in to the SDK / tool that's magically wired up the SDK?
* Should we consider creating a framework reference for WASM? We could remove all package references
* Why does the Client in the hosted app reference the dev server?
* Simplify file structure
* Theme redesign (for all the templates)

 Also, use this issue to synchronize templates (web with MAUI): https://github.com/dotnet/maui/issues/7868

**Comment by TanayParikh** [comment]
I believe https://github.com/dotnet/aspnetcore/issues/37201 could be taken care of during this cleanup pass of tempaltes.

**Comment by guardrex** [comment]
Reported by Kirk: There's a delta on CSS file indentation with most templates now adopting two spaces. The Blazor templates have four today.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/issues/40935

**Comment by guardrex** [comment]
Consider dropping the underscore prefix throughout project templates to make user code consistent among project templates, Blazor docs samples/examples, and dev coding guidelines. A search turned up the following. This might be all of them for Blazor project templates:

* https://github.com/dotnet/aspnetcore/blob/9e489c6cea4bba490d0874189ca2ae48ff7c16a0/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Server/Controllers/WeatherForecastController.cs#L36
* https://github.com/dotnet/aspnetcore/blob/25767dee3967bba5ebb795f33332092ebb20dd69/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/Error.cshtml.cs#L15
* https://github.com/dotnet/aspnetcore/blob/25767dee3967bba5ebb795f33332092ebb20dd69/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Areas/Identity/RevalidatingIdentityAuthenticationStateProvider.cs#L13-L14
* https://github.com/dotnet/aspnetcore/blob/25767dee3967bba5ebb795f33332092ebb20dd69/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Server/Pages/Error.cshtml.cs#L15
* https://github.com/dotnet/aspnetcore/blob/25767dee3967bba5ebb795f33332092ebb20dd69/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Server/Controllers/OidcConfigurationController.cs#L8

Cross References:

* [Remove underscores on Blazor topic+sample members (dotnet/AspNetCore.Docs #18176)](https://github.com/dotnet/AspNetCore.Docs/issues/18176)
* [Remark by Pranav that the next reference&dagger; calls for not prefixing (dotnet/AspNetCore.Docs #17797)](https://github.com/dotnet/AspNetCore.Docs/pull/17797#issuecomment-624911864)
* &dagger;Next reference: [.NET Fundamentals: Names of Type Members: Names of Fields](https://docs.microsoft.com/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields)
* [Blazor access modifiers and field underscores (dotnet/aspnetcore #18446)](https://github.com/dotnet/aspnetcore/pull/18446) - Additional remarks by Ryan and Pranav, including a comment that there was an internal meeting and a decision to use the `this` keyword for dev code/project templates.

**Comment by danroth27** [comment]
We think the important parts of this issue are already covered by other issues.
