### ISSUE TITLE
Tag end and Tag start detection

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#30170]
### Describe the bug
There is a formatting error in the IDE when following the instructions on the page: [ASP.NET Core Blazor cascading values and parameters](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-5.0). As soon as you add the paragraph section ```<p>Toggle this tab from the first tab.</p>```, the problem is displayed (Sorry, warning messages are in French)

**Note: The same code with Visual Studio Code does not create any problem in the IDE.**

![image](https://user-images.githubusercontent.com/16502423/107847588-2f1c6980-6ded-11eb-9fee-5f26e889e658.png)

### Further technical details
Visual Studio 16.9 Preview 4.0

**Comment by boukenka** [comment]
@NTaylorMullen Do you have any feedback ? 😄 Maybe this has already been solved with the new Razor Editor ?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Do you have any feedback ? 😄 Maybe this has already been solved with the new Razor Editor ?

Super odd indeed. We'd have to look into it. In the meantime would you mind trying it out in the new Razor editor and seeing if it reproduces for you similarly?

**Comment by boukenka** [comment]
The option to use the new razor editor was already checked. The problem is still present.

![Issue](https://user-images.githubusercontent.com/16502423/108416563-2a154b00-722f-11eb-835d-4460330006cf.png)

**Comment by NTaylorMullen** [comment]
Found that this is an HTML issue so created an issue on that team.

Tracking internally: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1281049

Once that's closed we'll close this issue out as well. Thanks for the report @boukenka!

**Comment by ToddGrun** [comment]
Thanks for the feedback. We've fixed this and the issue should be resolved in 16.10 Preview 3 and later. Thanks!
