### ISSUE TITLE
Blazor components' demo website

### ISSUE THREAD

**Issue by pavlexander** [dotnet/aspnetcore#30174]
I would like to suggest to create a website that would preview all the blazor components and their configuration options (if any). 

For an example please take a look at `Bootstrap's` website here:
https://getbootstrap.com/docs/4.1/components/card/

Another examples would be commercial `Blazor` components such as:
https://demos.devexpress.com/blazor/
https://demos.telerik.com/blazor-ui/grid/overview

I couldn't find anything as close to these demo websites on any of the Microsoft's own resources.. and that's sad to say the least.

The existing MS documentation on the website is very extensional/detailed, BUT
1. it lacks any visual demonstration
2. it's hard to **discover components** that framework provides out of the box

### Is your feature request related to a problem? Please describe.
I am starting a WASM project and willing to learn more about components that are built into `Blazor`. Having said that, I found some references to `EditForm` component:
https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.editform?view=aspnetcore-5.0
And then. in default project template there are: `NavLink`, `NavMenu`. I suppose there are also buttons and form elements that you could use out of the box.. However, what I don't understand, is why can't I find a single reference to demo site that lists all the components in one place? Similarly to bootstrap website where they list all available options for use. Is there something similar for `Blazor`?

### Describe the solution you'd like
I would like to see a demo website

### Additional context
I really like the direction where `Blazor` is headed technically.. So it's even more important now than ever that you have a demo website! If you want more business and contributors to adapt the platform, that is. The first impression is very important for new people :)

**Comment by guardrex** [comment]
> it's hard to discover components that framework provides out of the box

They're listed in the doc's Table of Contents (ToC) sidebar (left navigation sidebar) in the *Built-in components* node (immediately under the [Advanced Scenarios topic](https://docs.microsoft.com/aspnet/core/blazor/advanced-scenarios)). There might still be a few obscure ones not listed, but I'll be checking for that soon. I'm in the midst of many doc updates and overhauls right now.

> it lacks any visual demonstration

If you mean images, we can't support them well. The framework and tooling change rapidly these days, and images are difficult to keep up with and go stale quickly (just like sample apps). If you come to a specific concept that you think would be served well with an image, you can let us know using the **This page** feedback button and form at the bottom of the topic. Be warned tho, we reject most image requests (e.g., in tutorials) on the grounds that I mentioned.

There's a related issue WRT the [existing sample app](https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/common/samples/), which is linked into a number of the Blazor docs, at https://github.com/dotnet/AspNetCore.Docs/issues/14216. I'll get to that as soon as I can, but the document updates/overhauls need to be resolved first.

**Comment by javiercn** [comment]
@pavlexander thanks for contacting us.

We don't have plans to do this at the moment. We don't have an overwhelming amount of components, it is a large investment from the team to create and maintain and we haven't received significant requests for it.

If we hear more demand for it, we might reconsider, but we don't plan to offer anything in the short term.

**Comment by enetstudio** [comment]
@pavlexander,

You may use the stackoverflow web site to find lots of code samples about Blazor. You can, as for instance, Google up the string "enet stackoverflow blazor editform", and find many answers by me relating to the Editform, with working complete code. I believe it is an excellent source for learning Blazor, especially because it deals with real-life issues developers are facing.
