### ISSUE TITLE
Cross-compile analyzer assemblies

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30183]
We can cross-compile analyzer assemblies which allow the .net core versions to be cross-gened for some increased startup perf. In combination with https://github.com/dotnet/aspnetcore/issues/30182 we should hopefully take a smaller size hit for a better startup perf

-----

Quoting @brianrob 

From a quick test on my local machine (not the same machine that I’ve been using for realistic results on average hardware), I did a build of the blazor server template, and found the following JIT time associated with the analyzers:

Name | JitTime   msec | Num Compilations | IL Size | Native Size | Foreground   msec | Multicore JIT   Background   msec | Tiered Compilation   Background   msec | JIT Hotcode request   size | JIT RO-data request   size | Allocated size for   JIT code
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Microsoft.AspNetCore.Mvc.Analyzers.dll | 22.9 | 87 | 4,738 | 15,478 | 22.2 | 0.0 | 0.7 | 15,580 | 0 | 16,924
Microsoft.AspNetCore.Components.Analyzers.dll | 16.5 | 57 | 4,910 | 18,929 | 14.1 | 0.0 | 2.4 | 19,109 | 0 | 19,988
Microsoft.AspNetCore.Analyzers.dll | 15.4 | 67 | 3,345 | 12,282 | 15.4 | 0.0 | 0.0 | 12,375 | 0 | 13,400

On this machine, which is a pretty good one, this represents 51.7ms of foreground JIT time.  We’d be increasing the size of the SDK by 168kb, but I think that this could be a worthy improvement.

**Comment by brianrob** [comment]
@pranavkm, I followed up on this with @jkotas, and it sounds like we should be able to precompile these analyzers without having two copies of them (one for desktop, one for Core).  Do you know how these get used in the VS scenario, where they'd end up getting executed in a desktop process?  We should verify that precompiling these using ready to run doesn't break that scenario.

**Comment by brianrob** [comment]
Unfortunately we can't precompile these without having two separate copies. When they get precompiled they become arch specific and so in the case of x64, VS can't load them.
