### ISSUE TITLE
Can't Deploy Azure

### ISSUE THREAD

**Issue by staffordsmitht** [dotnet/aspnetcore#30188]
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Sample Code**
taylorstafford-smith@taylors-MacBook-Pro myMicroservice % kubectl apply -f deploy-myMicroservice.yaml

error: error validating "deploy-myMicroservice.yaml": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
taylorstafford-smith@taylors-MacBook-Pro myMicroservice % az aks get-credentials --resource-group myMicroserviceResources --name myMicroserviceCluster

Merged "myMicroserviceCluster" as current context in /Users/taylorstafford-smith/.kube/config
taylorstafford-smith@taylors-MacBook-Pro myMicroservice % cd myMicroservice

cd: no such file or directory: myMicroservice
taylorstafford-smith@taylors-MacBook-Pro myMicroservice % cd mymicroservice

**Comment by danmoseley** [comment]
I’ve transferred to aspnetcore repo where they can likely help.

**Comment by javiercn** [comment]
@staffordsmitht thanks for contacting us.

@Rick-Anderson can you route this issue to the right folks?

**Comment by Rick-Anderson** [comment]
@staffordsmitht go to the bottom of the page and select **I ran into an issue** and follow the instructions to   open an issue attached to that doc.

![image](https://user-images.githubusercontent.com/3605364/107996914-a7b62e00-6f85-11eb-9897-337577e7cd35.png)
