### ISSUE TITLE
Blazor ObjectGraphDataAnnotationsValidator issue on asure web app

### ISSUE THREAD

**Issue by timmynz548** [dotnet/aspnetcore#30185]
### Describe the bug
Get the error message when using <ObjectGraphDataAnnotationsValidator /> from the Microsoft.AspNetCore.Components.DataAnnotations.Validation package.  Using .net Standard 2.1 and deploying to a windows App on Azure.

Runs fine locally!

### To Reproduce
```
<EditForm Model="@setting" OnValidSubmit="@OnValidSubmit">
                <ObjectGraphDataAnnotationsValidator />

...
</EditForm>
```

 ```
[ValidateComplexType]
 public List<SomeOtherVMVM> alerts { get; set; }
```

### Exceptions (if any)

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Default constructor not found for type Microsoft.AspNetCore.Components.Forms.ObjectGraphDataAnnotationsValidator
System.MissingMethodException: Default constructor not found for type Microsoft.AspNetCore.Components.Forms.ObjectGraphDataAnnotationsValidator
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) <0x1c5dda0 + 0x000b0> in <filename unknown>

### Further technical details
- .net Standard 2.1 
- Azure Web App - windows

**Comment by javiercn** [comment]
@timmynz548 thanks for contacting us.

You likely need to configure the linker to avoid linking out the constructor. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1) for details
