### ISSUE TITLE
[Blazor WASM] Authentication : RemoteUserAccount not created from token after successful sign-in due to timezone/time issue on client

### ISSUE THREAD

**Issue by brettwinters** [dotnet/aspnetcore#30181]
### Describe the bug

After signing in successfully to the IDP, authentication fails on Blazor client with the exception below in the browser console when using Chrome, Edge, Firefox on desktop, but continues working on mobile browsers (tested using deployed version of the same configuration)

### To Reproduce

Create a Blazor WASM project using the templates and selecting the option to add authentication.

configure OIDC as follows (I've attempted this with AWS Cognito and Okta with same result): 

```c#
            builder.Services.AddOidcAuthentication(options =>
            {                
                options.ProviderOptions.Authority = "https://xxxxxxxxxxxxxxxokta.com/oauth2/default/";
                options.ProviderOptions.ClientId = "xxxxxxxxxxxxxxxxx";
                options.ProviderOptions.ResponseType = "code";
                options.ProviderOptions.DefaultScopes.Add("openid");
            });
```

Run the project and click "Login" button on index

Application redirects to IDP sign in page

Sign in. Application redirects back and after initially reporting that its working suddenly fails with exception in the console. (Logs on the IDP report success)

Inspecting the token returned via the network tab indicates that it is correct 

```json
{"token_type":"Bearer","expires_in":300,"access_token":"eyxxxw","scope":"openid profile","id_token":"eyxx"}
```

The Session Storage has `Microsoft.AspNetCore.Components.WebAssembly.Authentication.CachedAuthSettings` key, but local storage is empty after sign in fails.

### Exceptions (if any)

info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user

### Further technical details
ASP.NET Core 5.03
microsoft.aspnetcore.components.webassembly\5.03
microsoft.aspnetcore.components.webassembly.authentication\5.03
microsoft.aspnetcore.components.webassembly.devserver\5.03
The IDE: VS 16.9
Desktop browsers: Firefox 85.0.2, Chrome 88.0.4324.150, Edge  88.0.705.68

**Comment by javiercn** [comment]
@brettwinters thanks for contacting us.

The message you are seeing doesn't come from the OIDC authentication system but from the ASP.NET Core Authentication system and doesn't suggest that something went wrong with the authentication system. 

It only indicates that the user is not authenticated and that it is trying to access a page that requires the user to be authorized (by default that just means the user needs to be authenticated)

**Comment by brettwinters** [comment]
Hi @javiercn - right, yes, I understand it's a failed IsAuthenticated requirement in Asp.Net core and not generated by the OIDC JS code on the client.

There seems to be a problem in getting the token provided by the IDP to generate a claims principal. 

To try to troubleshoot, I attached a custom `AccountClaimsPrincipalFactory<RemoteUserAccount>` and overrode the `CreateUserAsync( RemoteUserAccount account,  RemoteAuthenticationUserOptions options)`, 

(1) I noticed that **the `account` argument is always null** when logging in successfully, so the generated and returned user from `await base.CreateUserAsync(account, options);` is always `IsAuthenticated == false`. This user has one empty identity with no claims after logging in.

(2) In the same `CreateUserAsync` override, when I `await base.TokenProvider.RequestAccessToken()` the status is always `RequiresRedirect` which gets me into a loop if I navigate there. No Access Token is available even though I can see it being delivered by the network traffic.

Just some information about the flow: After signing into the IDP the "authentication/login-callback?code=xxx" is url is displayed then "Completing Login.." followed by  "There was an error trying to log you in: ''" and the failed IsAuthenticated requirement exception which is logged to the console.

When I deploy this code and sign in on my mobile devices or friend's desktops then I can authenticate successfully. I can print the `account` so that the additional properties such as sub, name, amr, etc are displayed.

**Comment by brettwinters** [comment]
After finding these posts #27795 and #23215, I reset my timezone (it was set correctly, I just toggled the timezone and pressed "Sync Now" a couple of times) and it's working now. :)

I was not using TOTP, so my question is why is the Blazor Authentication so fragile wrt timezone/time? This would be extremely annoying for users where they can't sign in after travelling. There are no error messages produced and I've been logging into many other sites with my current laptop configuration using OIDC with no issues.

**Comment by mkArtakMSFT** [comment]
Glad that your issue got fixed.
