### ISSUE TITLE
Microsoft.AspnetCore.SignalR.Client 3.1.11 has conflicting dependencies on Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by k-eb** [dotnet/aspnetcore#30196]
### Describe the bug
I am facing a version mismatch issues when using Microsoft.AspnetCore.SignalR.Client 3.1.11 on **.NET Framework 4.8**. 

The below exception is thrown when calling the **constructor of HubConnectionBuilder**:

**Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

From what I can tell the root cause is that the very same assembly requires two different versions of Microsoft.Extensions.DependencyInjection and Microsoft.Extensions.Dependency.Abstraction at the same time.

Microsoft.AspnetCore.SignalR.Client 3.1.11
|--- Microsoft.AspNetCore.SignalR.Client.Core 3.1.11
      |--- Microsoft.Extensions.DependencyInjection **3.1.11**
      |--- Microsoft.Extensions.DependencyInjection.Abstractions **3.1.11**
      |--- Microsoft.Extensions.Logging 3.1.11
             |--- Microsoft.Extensions.DependencyInjection **3.1.0**
             |--- Microsoft.Extensions.DependencyInjection.Abstractions **3.1.0**
    
The workaround is to apply binding redirects. But of course, I'd prefer if the library would come without built-in version mismatches as binding redirects are a maintenance burden.

Thanks in advance for any feedback!

### To Reproduce

1. Create a .**NET 4.8** project
2. Add a Nuget dependency to Microsoft.AspnetCore.SignalR.Client of version 3.1.11
3. Add some code calling **new HubConnectionBuilder()**

### Exceptions (if any)
```
Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///mypath
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Extensions.DependencyInjection, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: mypath\MyApp.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
LOG: Attempting download of new URL file:///mypath/Microsoft.Extensions.DependencyInjection.Abstractions.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

Stack Trace:
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder..ctor()
```

### Further technical details
- Windows 10
- .NET Framework 4.8
- IDE: VS 2019 Professional

**Comment by k-eb** [comment]
While in the process of adding redirects, I noticed that there are more mismatches. Maybe even more are required which I only know when I am done with testing this out:

```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.11.0" newVersion="3.1.11.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.11.0" newVersion="3.1.11.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Options" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.11.0" newVersion="3.1.11.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.11.0" newVersion="3.1.11.0" />
      </dependentAssembly>
  ```

**Comment by BrennanConroy** [comment]
> The workaround is to apply binding redirects. But of course, I'd prefer if the library would come without built-in version mismatches as binding redirects are a maintenance burden.

Yeah this is a known problem area, unfortunately the binding redirects is the solution for now.
