### ISSUE TITLE
FIDO2 support anywhere and everywhere when a user needs to authenticate

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#30190]
feature request for .NET 6

**Comment by danmoseley** [comment]
Moving to aspnetcore where others may wish to share their thoughts.

**Comment by blowdart** [comment]
As we're not Fido experts and there are community implementations already which integrate with Identity and Identity Server. 

While we'll make it easier to avoid 3rd party crypto libraries, if we get specific issues around what's missing in our crypto or encoding stacks, we don't feel it's our place to fulfill the need right now.
