### ISSUE TITLE
Allow multiple connections during dotnet watch run

### ISSUE THREAD

**Issue by eugeneogongo** [dotnet/aspnetcore#30208]
### Is your feature request related to a problem? Please describe.
I am trying to debug an issue on two web browsers chrome and Edge. The two browsers are not refreshing simultaneously only one refresh. Can we have a feature to have concurrent connections during dotnet watch run?

### Describe the solution you'd like

Allow multiple connections to the WebSocket during dotnet watch run.

**Comment by javiercn** [comment]
@eugeneogongo thanks for contacting us.

@pranavkm thoughts?

**Comment by eugeneogongo** [comment]
Hi @javiercn @mkArtakMSFT @pranavkm , 

I see dotnet-watch was removed from the git.. What's the new home for dotnet-watch?

**Comment by javiercn** [comment]
@eugeneogongo https://github.com/dotnet/sdk  I believe.

**Comment by eugeneogongo** [comment]
@javiercn  Thanks

**Comment by NicolasDorier** [comment]
https://github.com/dotnet/sdk/tree/master/src/BuiltInTools/dotnet-watch

**Comment by pranavkm** [comment]
This was resolved as part of https://github.com/dotnet/sdk/pull/16401,
