### ISSUE TITLE
Allow Blazor Server app to have API endpoint

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#30204]
### Is your feature request related to a problem? Please describe.
Rather than adding the complexity of a shared project, that contains EF Core models, to be used by Blazor and an API project, it would be useful to have an API endpoint available in a Blazor Server app.

### Describe the solution you'd like
Maybe it is possible, and not documented somewhere I've found, but to add a Controller with an endpoint or handle it in the `OnGet` of `_Host.cshtml` would work for this. Is this possible now, or a good fit for a future release?

**Comment by mrpmorris** [comment]
You can already add api controllers in the usual way. Give it a try.  Is there something not working for you?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. As @mrpmorris  has pointed out, this is possible even today. Please clarify what specifically you're having trouble with so that we can try to help you.

**Comment by mrlife** [comment]
@mrpmorris @mkArtakMSFT Thanks for getting back to me. Since this is possible, I will close this out. I thought that Blazor Server just had the one endpoint available of `_Host.cshtml`. I will use the docs for the Web API tutorial to just add the relevant parts to my Blazor app.
