### ISSUE TITLE
Dev cert works for https for 2 Microsorvices but it does not work when they communicate between them

### ISSUE THREAD

**Issue by eliassal** [dotnet/aspnetcore#30216]
### Describe the bug
I created 2 dotnet core webapis on a desktop win10 , .net 5,  replaced  applicationUrl : https://localhost:5001 to applicationUrl : https://hostname:5001, 2nd Microsorvice on applicationUrl : https://hostname:5002, which works fine in browser and Postman from a remote a laptop

From my laptop I can access the APIS remotely in browser or postman. However, in the 2nd MS, I introduced a function (api), I access the 1st MS with Http client, using baseURL the url of the 1st MS https://hostname:5001 I get 

> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
>  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch

### To Reproduce
1 - Create 2 microservices using dotnet new webapi
2 - change application url to host names
3 - In 2nd Microservice, add a function to call to the first 1 using httpclient and using the secure URL for the 1st Microservice
4 - Browse to both  secure URLs for the 2 microservices, they display correctly
5 -Try to browse the 2nd function in the 2nd MS, you get the error

### Exceptions (if any)
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

### Further technical details
- ASP.NET Core version : 5

- VS Code on win 10 64
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  1.0.0-preview2-003131 [c:\program files\dotnet\sdk]
  1.0.0-preview2-1-003177 [c:\program files\dotnet\sdk]
  1.0.0 [c:\program files\dotnet\sdk]
  1.1.0 [c:\program files\dotnet\sdk]
  2.0.2 [c:\program files\dotnet\sdk]
  2.1.2 [c:\program files\dotnet\sdk]
  2.1.101 [c:\program files\dotnet\sdk]
  2.1.200 [c:\program files\dotnet\sdk]
  2.1.202 [c:\program files\dotnet\sdk]
  2.1.401 [c:\program files\dotnet\sdk]
  2.1.521 [c:\program files\dotnet\sdk]
  2.1.617 [c:\program files\dotnet\sdk]
  2.1.813 [c:\program files\dotnet\sdk]
  2.2.105 [c:\program files\dotnet\sdk]
  2.2.202 [c:\program files\dotnet\sdk]
  2.2.203 [c:\program files\dotnet\sdk]
  3.1.406 [c:\program files\dotnet\sdk]
  5.0.101 [c:\program files\dotnet\sdk]
  5.0.103 [c:\program files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Pilchie** [comment]
@javiercn ?

**Comment by blowdart** [comment]
This is by design, dev tools only creates certificates for local host. It doesn't create them for other host names. In general you end up putting a proxy in front of your containers, which terminates the HTTPS connection, and container <-> container communications are https only, because they're still within the same host, rather than over a network, so HTTPS matters less.

**Comment by javiercn** [comment]
I was in the middle of responding, lol.

What @blowdart said.

In these cases we recommend using openssl or similar to generate certificates with the right hosts and configure them in the traditional way in Kestrel.

**Comment by eliassal** [comment]
What is the traditional way in Krestel? Can you share please?

**Comment by eliassal** [comment]
Ok, but why it works fine when I access the webapi using https://myhostname:5001/items without any issue?

**Comment by javiercn** [comment]
@eliassal https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#configureiconfiguration

I suspect because if you are using a container the container runtime likely resolves the host name.

**Comment by eliassal** [comment]
@javiercn it is for all WEBAPIs apps I create I do this it works fine except this time as I am doing an inter-MS communication. It ios a basic webapi created using dotnet new, then change appurl in then I go to my laptop Postman and access without any specific configuration. I can allow see all this by yourself through teams or skyp video session on my environment if you like

**Comment by eliassal** [comment]
I solved the issue and now can access all MS correctly. Why I was able to access from laptop it was because the laoptop also trsuts dotnet certs as I have issued dotnet trust 4 months ago on the laoptop

**Comment by eliassal** [comment]
Here is the link to my article http://salam.hd.free.fr/BlogEngine/post/2021/02/18/Accessing-HTTPS-in-WEBAPI-Core-remotely-using-Self-Signed-Certificate.aspx
