### ISSUE TITLE
SignalR for .NET Core is not working on IE11

### ISSUE THREAD

**Issue by justinjalandoniiwest** [dotnet/aspnetcore#30212]
I am using the SignalR core library for IE11 and I am getting this error:

i am debugging and it seems that the signalR isn't functioning. Notice the watches on the right for the ``model` variable:
![image](https://user-images.githubusercontent.com/75491773/108071642-ef7da800-70a0-11eb-8b81-c4673f8974f2.png)

While this is one for Firefox. We can see that the `model` has a value. 
![image](https://user-images.githubusercontent.com/75491773/108071835-28b61800-70a1-11eb-9f6e-1ac4ae193d0c.png)

Here is the code in question:
```js
$.connection.hub.start().done(function () {
        console.log("SignalR started");
        model.roomList();
        model.userList();

        setTimeout(function () {
            if (model.chatRooms().length > 0) {
                model.joinedRoom(model.chatRooms()[0].name())
                model.joinRoom();
            }
        }, 100);

    });
```

Full code: https://pastebin.com/XAJ2uUYq

**Comment by davidfowl** [comment]
From the looks of your sample that isn't the .net core signalr client. Also we don't support IE11 in the new client. You may be able to make it work with polyfills though

**Comment by justinjalandoniiwest** [comment]
Hello, can you tell me which signalR client this is? Is it for .NET framework?

**Comment by davidfowl** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-5.0 for more details
