### ISSUE TITLE
Blazor WASM Standalone Authentication with CSP Portal

### ISSUE THREAD

**Issue by patrykgz** [dotnet/aspnetcore#30215]
### Describe the bug
When using Blazor WASM authenticationservice.js, with an OIDC provider that has a content security policy on the log-in website ( Corporate/Enterprise Ping Identity) the iframe fails, and the user is required to wait till the iframe times out before either a redirect( when using authentication/login ) or a fail ( when using silent login on startup). 

### Recommended Approach
Either redirect to login page, or set an option on the service to skip the iframe and allow the user to manually click "Log In" to be redirected.

### To Reproduce
Unable to share due to policy.

### Exceptions (if any)
CSP Headers: "frame-ancestors 'self'; default-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-inline'"

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by MutatePat** [comment]
Is there anything I can do in the meantime to disable it by modifying the js? As this will affect our production systems

**Comment by markdchurchill** [comment]
This also occurs using AWS Cognito auth, as it sets `X-Frame-Options: Deny`.

The proposed fix would also help out with this situation, and Cognito is a major IdP in the space.

**Comment by emahiq** [comment]
We are also very interested in this.
While we wait for a proper solution to be implemented, is there any kind of workaround we can do? Modifications to AuthenticationService.js? Something else?

**Comment by mkArtakMSFT** [comment]
We will reevaluate this ask as part of https://github.com/dotnet/aspnetcore/issues/40764 work. Linking and closing this one, so that we can find this ask when will be handling the linked item.
