### ISSUE TITLE
Add support for TagHelper element/attribute quick info classifications in Visual Studio

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#30224]
Old Editor:
![image](https://user-images.githubusercontent.com/2008729/108138869-b549e180-7073-11eb-8fdc-18263b7ee7a1.png)

![image](https://user-images.githubusercontent.com/2008729/108138888-bc70ef80-7073-11eb-9883-cab27355573e.png)

New Editor:
![image](https://user-images.githubusercontent.com/2008729/108138915-c72b8480-7073-11eb-9e9f-41e2180f00e6.png)
![image](https://user-images.githubusercontent.com/2008729/108138943-d1e61980-7073-11eb-90e0-137dfdb245d0.png)

**Comment by NTaylorMullen** [comment]
@allisonchou going to throw this into your plate as it relates pretty heavily to https://github.com/dotnet/aspnetcore/issues/30226

**Comment by allisonchou** [comment]
Addressed by https://github.com/dotnet/aspnetcore-tooling/pull/3538.
