### ISSUE TITLE
Improve HTTP/2 performance by using Channels

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#30235]
Today Kestrel locks and copies buffers into the connection pipe when multiplexing output from multiple streams. We could improve this by using a channel to queue writes to the pipe instead of locking (See https://github.com/dotnet/aspnetcore/blob/9a87636e7e5d767f2c1669b24f7fec86036442d3/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L265 for an example).

This samples shows the difference between a `SemaphoreSlim` and a `Channel<byte[]>` and the performance difference is almost 3x with 0 allocations https://gist.github.com/davidfowl/8af7b6fa21df0fe1f150fb5cfeafa8f7.

There was still lock contention in Channels itself but it was pretty optimized.

We should prototype and measure this change.

cc @JamesNK @halter73 @Tratcher

**Comment by JamesNK** [comment]
Copied from https://github.com/dotnet/aspnetcore/issues/30829

> The HTTP/2 frame writer uses `lock` to ensure only one stream can write the connection at a time. For example, [Http2FrameWriter.WriteDataAsync](https://github.com/dotnet/aspnetcore/blob/85a6cb07ae2e1adf5a03740f8d40333b7b8e360c/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L265).
> 
> When a connection has many streams with frequent writes, there is a lot of contention on the lock. Profiling shows high CPU usage from threads fighting over the lock.
> 
> A potential improvement would be to change the writer to use a producer/consumer queue using `Channel<T>`. The streams add write operations to the queue and a single consumer loop is responsible for writing frames to the connection.
> 
> Today:
> 
> ```cs
> public ValueTask<FlushResult> WriteDataAsync(byte[] data)
> {
>     lock (_writeLock)
>     {
>         _writer.Write(data);
>         return _writer.FlushAsync()
>     }
> }
> ```
> 
> Future:
> 
> ```cs
> public ValueTask WriteDataAsync(byte[] data)
> {
>     var operation = SetupWriteData(data);
>     _channelWriter.TryWrite(operation);
>     return operation.WaitForCompletedAsync();
> }
> 
> // Consumer loop that reads operations from channel
> private async ValueTask WriterConsumer()
> {
>     while (true)
>     {
>         if (!await _channelReader.WaitToReadAsync())
>         {
>             return;
>         }
> 
>         if (_channelReader.TryRead(out T item))
>         {
>             switch (item.OperationType)
>             {
>                 case OperationType.WriteData:
>                     _writer.Write(item.Data);
>                     await _writer.FlushAsync();
>                     item.Complete();
>                     break;
>                 case OperationType.WriteHeaders:
>                     // etc..
>                     break;
>             }
>         }
>     }
> }
> ```

**Comment by halter73** [comment]
Note: The HTTP/2 FlowControl logic relies on being synchronized by the _writeLock.

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs#L701-L715

We can instead move this logic into `WriterConsumer()` for synchronization, but that means TryUpdateStreamWindow will need to be an operation that can be written to the channel. That also means what looks like a single write to `WriteDataAsync()` could take several iterations of the `WriterConsumer()` loop to complete as the writes wait for flow control availability.

I don't think this causes a real problem for this approach. It's just a slight complication. I really like using Channels for this.

**Comment by JamesNK** [comment]
Perf is worse with h2 (HTTP/2 + TLS)

![image](https://user-images.githubusercontent.com/303201/130524768-c67b66cf-253f-4981-b443-0aaa5841bc95.png)

(h2 RPS is the yellow dot at the bottom)

**Comment by davidfowl** [comment]
Closing this as fixed.
