### ISSUE TITLE
Kestrel hosted Blazor WASM large file upload problem: really slow.

### ISSUE THREAD

**Issue by JeepNL** [dotnet/aspnetcore#30243]
_ASP.NET Core 5.x latest / Visual Studio Preview latest - Feb. 17th, 2021_

When uploading small files like compressed/resized images with Blazor WASM `<InputFile>` everything is workable, if you don't want to upload 100, or more, of them.

If you upload a bit larger file (20MB) the overall upload process takes a long time. If you upload it in one piece, this takes about 30 seconds. Locally, so no bandwidth bottleneck. When I upload it in chunks of 1MB it takes about 10 seconds, which is still very slow: Max 2MB/s overall throughput. I've tried it with different chunk sizes, but 2MB/s is about the max.

I am working on a app in which I need to upload very large video files: 1GB+.  AFAIK there's  no working solution for this in Blazor/C#.

There are lots of samples (blogs/videos) how to use Blazor WASM `<InputFile>` but none of them address the problem of uploading bigger files than images.

To reproduce this you can use one of these samples:

1) Ed Charbeneau's "Blazor Power Hour InputFile sample code" (_Jan. 2021_):
https://github.com/EdCharbeneau/BlazorPowerHour/tree/main/EP7-inputfile

2) Carl Franklin's Blazor Train: "Files... Uploading, Downloading, and Storing" (_Feb. 2021_): 
(_with Blazor WASM file upload in chunks_)
https://www.youtube.com/watch?v=bQ6D4VFMxc4
source code: http://blazordeskshow.com/blazortrainfiles/FileHandling.zip

If this is een internal Blazor WASM problem which isn't easy to solve, is there a work around for this? Or maybe any other ideas how to upload bigger files than images with Blazor? At the moment I'm using https://github.com/tusdotnet/tusdotnet on the server, and on the client  some plain HTML/JavaScript  in an `<IFRAME>`, but this is far from ideal imo.

FYI (_extra_): About a InputFile Progress Bar:

In August last year the official `<InputFile>` was announced during the ASP.NET Community Standup and a progress bar was mentioned. Daniel Roth answered my question about it on the Microsoft devblogs: https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/comment-page-3/#comment-2678 and created a GitHub issue for it: https://github.com/dotnet/aspnetcore/issues/26347

The status of this issue has been set to 'resolved', but it isn't really, because there's no mention of a progress bar in the docs: https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please share the samples as GitHub repos instead?

**Comment by JeepNL** [comment]
@mkArtakMSFT Here's the link to the GitHub repo I just created: https://github.com/JeepNL/BlazorWasmFileUpload

The bigger the file, the slower the data transfer. Something's strange is  happening inside the browser before the actual upload starts which slows the overall throughput down.  This code does not contain upload in chunks, with chunked upload (1MB parts) you can get +/- 2MB/s which is still too slow for a local upload. 

![Screenshot 2021-02-17 212952](https://user-images.githubusercontent.com/39458532/108284568-c5ea7c80-7185-11eb-807f-6701b4ca4b83.jpg)

![Screenshot 2021-02-18 010016](https://user-images.githubusercontent.com/39458532/108284575-c8e56d00-7185-11eb-969f-7f9b9621e4b1.jpg)

**Comment by JeepNL** [comment]
FYI:

I completely rewrote my code, you now can test uploads in Blazor WASM with chunked parts, it uses a simple progress bar and you can upload a local file, or a in memory generated random binary file (_different file sizes & chunk sizes_).

For this demo I'm only using 2 files, one on the client `FileUpload.Razor` and one on the server `UploadController.cs`. I think it's easier to see what's happening.

_FYI: I'm still learning C# / Blazor, so probably the code can be optimized... (it works on my PC 😉)_

Source: https://github.com/JeepNL/BlazorWasmFileUpload

**Start**

![Screenshot 2021-02-22 133841](https://user-images.githubusercontent.com/39458532/108711644-f16abf80-7515-11eb-96e3-161905d6b9ab.jpg)

**Uploading**

![Screenshot 2021-02-22 134238](https://user-images.githubusercontent.com/39458532/108711660-f7f93700-7515-11eb-8d13-7eb39d4ea138.jpg)

**Result**

![Screenshot 2021-02-22 134111](https://user-images.githubusercontent.com/39458532/108711650-f596dd00-7515-11eb-968d-3ba38f049957.jpg)

**Comment by JeepNL** [comment]
This I don't understand:

When I start the app (locally) in **DEBUG MODE** (_Visual Studio Preview, F5, Start Debugging_) the throughput reaches almost **10MB/s** with chunks of 512KB (_the optimal setting when not running in debug mode_)

And when I upload a generated file of 20MB in 1 chunk of 20MB in **debug mode** the throughput is **above the 40MB/s**

_20MB in 512KB chunks in debug mode_

![Screenshot 2021-02-23 141834](https://user-images.githubusercontent.com/39458532/108849403-64da0300-75e2-11eb-96f3-71c223a91cca.jpg)

_20MB in 1 chunk in debug mode_

![Screenshot 2021-02-23 142347](https://user-images.githubusercontent.com/39458532/108850061-327cd580-75e3-11eb-9b6a-e1d2ab0c2d48.jpg)

**Comment by JeepNL** [comment]
@javiercn @SteveSandersonMS @mkArtakMSFT 

**FYI**

With .NET 6 preview 5 (_Kestrel Hosted Blazor WASM_) the upload is now super fast!

On my PC with localhost it's now 50+ MB/s (Mega**Bytes**)

**Comment by endintiers** [comment]
@SteveSandersonMS More than a year later, and here I am. Same issue. Latest .NET 6 packages. Doing exactly this: https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly#upload-component a 60MB file (locally) takes 2 seconds from the swagger UI (Javascript) and 80 seconds from Blazor WASM.

Somebody is doing it wrong.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
I assume the original issue that you've reported was indeed solved in .NET 6.
