### ISSUE TITLE
Make GetJSRuntime public

### ISSUE THREAD

**Issue by mikes-gh** [dotnet/aspnetcore#30244]
### Is your feature request related to a problem? Please describe.
ElementReference.GetJSRuntime in internal
https://github.com/dotnet/aspnetcore/blob/a9d9f522a907f94fd2935eb26cb321c702de9b50/src/Components/Web/src/ElementReferenceExtensions.cs#L36

### Describe the solution you'd like
Make GetJSRuntime public so we can write our own JS related extension methods on ElementReference without resorting to reflection.

**Comment by pranavkm** [comment]
Thanks @mikes-gh for the issue. We're already considering doing this as part of https://github.com/dotnet/aspnetcore/issues/29826. Closing this as a dup.

**Comment by mikes-gh** [comment]
Thanks I did a search on GetJSRuntime first but nothing came up.  Sorry for dup
