### ISSUE TITLE
Razor source generator incrementality goes wrong on downgrades

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#30246]
This is to track fixing the issue identified at https://github.com/dotnet/sdk/pull/15756#pullrequestreview-590371197

The most likely case where this affects someone is when downgrading to an older dependency, but would also affect them when upgrading to one that's already cached locally.

**Comment by pranavkm** [comment]
This should be a good way to track that the specific issue gets fixed. Also we're continuing to use the AspNetCore repo to track SDK issues, so moved this over.

**Comment by captainsafia** [comment]
Closing this in favor of #30234.

We're moving to an in-memory cache model which will remove this particular codepath. Instead, we'll be determining whether or not to cache-bust based on a unique identifier associated with each metadata reference.
