### ISSUE TITLE
VS2019 Pro 16.8.4 C# ASP.NET Razor Page causes freeze of VS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30249]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS2019-Pro-1684-C-ASPNET-Razor-Page-/1314186)._

---
[severity:It's more difficult to complete my work]
My Razor page with a lot of conditional <view>'s caused VS to become inoperable every time I opened the file. It was impossible to edit the file using VS and I had to edit is using an external editor before I could use it in VS again. In the mean time I've just replaced the whole page by a helper class with a stringbuilder.

I just want to report the errors in the ActivityLog.xml. See attachment. Just look for the errors.

---

**Comment by NTaylorMullen** [comment]
The original issue/conversation on the public developer community issue has all the relevant info (including a dump) to investigate further. Goal here is to see where the exception is happening and forward to appropriate teams but more importantly ensure that this does not end up happening in the new experimental Razor editor.

**Comment by JHBonarius** [comment]
I should have saved the file... hope you'll find the cause and good luck.

**Comment by NTaylorMullen** [comment]
Found this to be classic ASP.NET Razor, re-opened the original public issue and moved over to the correct team.
