### ISSUE TITLE
[Infrastructure] Limit browser installation to the environments where we use it

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#30241]
We should only install the browsers on the platforms where we run E2E tests to make sure we don't introduce flakyness on other legs of the build.

We can do this by configuring the appropriate flag in our build agents [here](https://playwright.dev/docs/installation/#skip-browser-downloads)

**Comment by dougbu** [comment]
Are browsers installed when Playwright is not installed❔ We already have a flag controlling Playwright installation.

More generally, please slot test infrastructure issues specific to a suite in e.g. `area-blazor`. This isn't a general problem for most of the org.

**Comment by mkArtakMSFT** [comment]
@HaoK are you handling this as part of your playwright issue?

**Comment by HaoK** [comment]
At this point its unlikely, I'm probably just going to try and get more or less what I have merged in some form, I'll be focusing on servers issues going forward

**Comment by TanayParikh** [comment]
@dougbu @wtgodbe do you folks know if there has been any flakiness in this area, or should this be closed out?

**Comment by dougbu** [comment]
I don't think we've seen installation problems related to the browsers.

More generally, we only run InstallGoogleChrome.ps1 in one place and that's on a Windows Build agent for a single test job. The Helix setup already seems to have granular controls for what installation commands we run. Am I missing something❔

**Comment by TanayParikh** [comment]
This doesn't appear to be an issue any longer.
