### ISSUE TITLE
Custom Web.config - aspNetCore section gets overwritten in Debug and Release mode

### ISSUE THREAD

**Issue by aaroncearleytcms** [dotnet/aspnetcore#30258]
Closing because it appears this issue is fixed. If anyone is still running into this, please let us know. Thanks!

_Originally posted by @Eilon in https://github.com/dotnet/aspnetcore/issues/2993#issuecomment-404981133_

**Comment by aaroncearleytcms** [comment]
actually I just experienced it today. this is breaking my ability to debug locally. visual studio version is 16.8.4. not sure why stealth modification of the web.config would be consider a feature. especially with the fact you receive no notification.

**Comment by BrennanConroy** [comment]
Can you provide a repro project with the custom web.config? VS shouldn't be modifying the web.config anymore.
