### ISSUE TITLE
Disable CORS not working 

### ISSUE THREAD

**Issue by p3s** [dotnet/aspnetcore#30257]
![Captura de tela de 2021-02-17 09-16-51](https://user-images.githubusercontent.com/2353264/108203746-ae69b000-7101-11eb-8bed-353b862eb405.png)

### Description

when creating a new webapi project and enabling CORS, it does not work. 
I followed the documentation 
https://docs.microsoft.com/pt-br/aspnet/core/security/cors?view=aspnetcore-5.0#enable-cors

[https://imgur.com/Tiue4XI](https://imgur.com/Tiue4XI)
[https://pastebin.com/mV7kJh72](https://pastebin.com/mV7kJh72)
### Configuration

* Which version of .NET is the code running on?  5.0.103
* What OS and version, and for Linux, what distro? Ubuntu 20.10 | Windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No
* If you're using Blazor, which web browser(s) do you see this issue in?
  -->

### Other information
error seems to occur only with http request
if I remove app.UseHttpsRedirection (); works without error on http

**Comment by pranavkm** [comment]
@p3s DisableCors tells the framework not to respond with a pre-flight (CORS) response if the browser makes a pref-flight request. However it does not prevent a browser from making a pre-flight request which is essentially what you're seeing here. CORS as a feature is enabled and enforced by the browser. What you should do here is correctly set up your app to allow CORS responses for the alternate host that you're using.
