### ISSUE TITLE
blazor desktop in .net 6 preview 1 not working.

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#30269]
I see a post here https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/ 
that says that this includes blazor desktop.  I downloaded everything needed for it and even used visual studio 2019 9 preview 4.  The good news is i saw the choice for .net 6 preview.  However, when i choose it, i see no option for blazor desktop development including even wpf.  There was a screenshot showing it worked with wpf.  However, when I choose new wpf application, i see no option for any control to use blazor.  I checked out the docs but there is nothing there.  I would be really disappointed if its misleading where it says it can be done but there is no hello world sample.

**Comment by javiercn** [comment]
@musictopia2 thanks for contacting us.

Blazor desktop is not part of preview1, I believe the blog post refers to it in the context of the work that is going to be happening across .NET 6.0.

Hope that helps!

**Comment by musictopia2** [comment]
The article showed misleading.  Because the article said it was part of preview 1 even with screenshots of it already working on desktop only.

**Comment by javiercn** [comment]
@musictopia2 Point taken.

@danroth27 is there anything you want to correct on the article?
