### ISSUE TITLE
Static pages in Blazor

### ISSUE THREAD

**Issue by vishvanathan-k** [dotnet/aspnetcore#30263]
Can i build a static website with C# using blazor , just like building a normal static website using JS,HTML,CSS

**Comment by javiercn** [comment]
@vishvanathan-k thanks for contacting us.

Can you clarify your question?

**Comment by vishvanathan-k** [comment]
We all know that we can build a simple static site with **JS , CSS and of course , HTML**
My questions is that can we build a static pages with **C# instead of JS and CSS , HTML** _(that means strictly no server side scripting)_
