### ISSUE TITLE
SignalR with Firebase not working.

### ISSUE THREAD

**Issue by VirajShirwalkar** [dotnet/aspnetcore#30282]
Hello there,
Please go through below flow to figure out what is wrong with signalR.
1. I have created a demo simple **androidX** application (Hello world).
2. Connected with **firebase and push notification (FCM service)**.
3. notifications working fine.
4. Now, implemented **signalR 5.0.0.** 
5. Did connection as per documentation says.
6. server side is with Azure.
7. when i run the application, i can get notifications but hub connection got disconnected in less than 10msec.
8. It shows one error all the time, whatever you change with hub connection.
9. "Connection reset by peer".
**If i run signalR in new demo without firebase, works fine.**
It is making me frustrated since 4 days.
Need help asap.

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag or the signalr tag.
