### ISSUE TITLE
Not method UseWindowsService in NET 5.

### ISSUE THREAD

**Issue by SVD102** [dotnet/aspnetcore#30284]
### Describe the bug
I am giving a project WindowsService, but the VS2019 Express does not see the method UseWindowsService.
Use NET 5.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by SVD102** [comment]
Use Microsoft.Extensions.Hosting 6.0.0-preview.1.21102.12.

**Comment by gfoidl** [comment]
For reference see [Host ASP.NET Core in a Windows Service / App configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=netcore-cli#app-configuration)

> The app requires a package reference for [Microsoft.Extensions.Hosting.WindowsServices](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices).

**Comment by BrennanConroy** [comment]
Thanks @gfoidl :)
