### ISSUE TITLE
Blazor WASM - All Project Breakpoints Stop Working If enum is used as Attribute Parameter on Any Component

### ISSUE THREAD

**Issue by saulyt** [dotnet/aspnetcore#30281]
### Describe the bug
If you create an attribute that takes an enum as a parameter, and use that attribute on any Blazor component, you will be unable to hit a breakpoint anywhere in the project. Every breakpoint will show an Unbound Breakpoint error.

### To Reproduce
This Git Repo demonstrates the issue: https://github.com/saulyt/BlazorAttributeIssue

Using the standard Blazor WASM template I :
- Added an BreaksDebuggingAttribute class that takes an enum parameter to the Shared project.
- Added @attribute [BreaksDebugging(MyEnum.One)] to the top of Index.razor in the Client project.
- Ran the project and tried placing a breakpoint inside the IncrementCount() method in Counter.razor

When taking these steps you will see that this breakpoint, or any other breakpoint anywhere in the project, will not get hit, and you will get an Unbound Breakpoint message. If you remove the attribute at the top of index.razor and rerun, breakpoints will once again work.

### Further technical details
- ASP.NET Core version 5.0

**Comment by javiercn** [comment]
@saulyt thanks for contacting us.

@lewing should we move this to the runtime repo?

**Comment by captainsafia** [comment]
This issue has been reported before (https://github.com/dotnet/runtime/issues/47792) so I'll close this as a dupe since it's tracked.
