### ISSUE TITLE
Blazor MapFallbackToAreaPage will Display not found until the correct page is displayed

### ISSUE THREAD

**Issue by j4587698** [dotnet/aspnetcore#30283]
### Describe the bug
If use MapFallbackToAreaPage like 
```endpoints.MapFallbackToAreaPage("~/Admin/{*clientroutes:nonfile}","/_AdminHost", "Admin");```

It will show not found before the correct page is displayed.
Iike the repo

### To Reproduce

the repo is https://github.com/j4587698/RazorPagesAndBlazor

### Further technical details
- ASP.NET Core version  .net5
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version Any

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
