### ISSUE TITLE
Ability to monitor circuit activity

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#30287]
Ability to monitor circuit activity so that circuits can then be terminated as appropriate. Provide callbacks when an event, JS interop call, or other activity happens on the circuit.

The ability to terminate circuits from client/server is tracked separately by https://github.com/dotnet/aspnetcore/issues/17866.

Split out from https://github.com/dotnet/aspnetcore/issues/27885

**Comment by mkArtakMSFT** [comment]
Moving this out of 6.0 to make room for Razor tooling asks for the Razor compiler.

**Comment by javiercn** [comment]
https://github.com/dotnet/aspnetcore/issues/39615

**Comment by vflame** [comment]
Is it possible to access Blazor's signalr hub/hubcontext to disconnect clients and to override the `OnConnectedAsync` and `OnDisconnectedAsync` events as a workaround? How about making the HttpContext used establish signalr connection available when a circuit is created?
