### ISSUE TITLE
IdentityUI no longer supports SxS views

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30280]
As part of https://github.com/dotnet/aspnetcore/pull/30156 we're updating to an SDK that no longer allows running razor compilation independent of regular compilation. We're also looking to remove the Views dll completely. What this does mean for IdentityUI supporting multiple views dll?

**Comment by pranavkm** [comment]
FYI @javiercn

**Comment by blowdart** [comment]
Also @HaoK

**Comment by javiercn** [comment]
This might come up as we upgrade to Bootstrap5 if we need to keep 4 around.

**Comment by HaoK** [comment]
@javiercn this might be relevant now?

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/36378
