### ISSUE TITLE
IFormFile binding doesn't work correctly using square bracket notation

### ISSUE THREAD

**Issue by treformat** [dotnet/aspnetcore#30293]
IFormFile binding doesn't work correctly in square bracket notation. Example below explain better than words. We use .NET 5 and to resolve the issue we created some custom model binder.

1. Create simple controller
```
    [ApiController]
    [Route("[controller]")]
    public class TestController : ControllerBase
    {
        [HttpPost]
        public IActionResult Post([FromForm] Parent parent)
        {
            return Ok();
        }

        public class Parent
        {
            public Child[] Children { get; set; } = new Child[0];
        }

        public class Child
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public IFormFile Image { get; set; }
        }
    }
```

2. Execute API by using Postman, curl or some other tool
```
curl --location --request POST 'https://localhost:44356/test' \
--form 'Children[0][FirstName]="John"' \
--form 'Children[0][LastName]="Smith"' \
--form 'Children[0][Image]=@"/C:/Users/Tomek/Desktop/test.jpg"'
```

3. Issue occured. FirstName and LastName fields are binded correctly, but Image not.
![obraz](https://user-images.githubusercontent.com/6588530/108516866-043b8500-72c7-11eb-99bd-4e330b4f9326.png)

If we change request and use dot instead of square bracket notation, everything will work fine.
```
curl --location --request POST 'https://localhost:44356/test' \
--form 'Children[0].FirstName="John"' \
--form 'Children[0].LastName="Smith"' \
--form 'Children[0].Image=@"/C:/Users/Tomek/Desktop/test.jpg"'
```
![obraz](https://user-images.githubusercontent.com/6588530/108517141-52e91f00-72c7-11eb-8f3c-7149b907b299.png)

**Comment by pranavkm** [comment]
@treformat form files are sent over HTTP as a [multi-part request](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2), not as a path to a file on disk. Form file binding supports array notations. I would suggest performing a post from a browser that includes a file and using that to craft the request you're trying to replicate here.

**Comment by treformat** [comment]
@pranavkm Have you looked at example and attached screenshots? This bug it's very easy to reproduce, let's try, please. The same request works in dot notation but doesn't in square brackets - only differences were names of the keys in form data. Curl example was exported from Postman, and yes, it use multi-part request. 

![obraz](https://user-images.githubusercontent.com/6588530/108555298-978baf00-72f5-11eb-9e03-7c10c5ac7ec8.png)
![obraz](https://user-images.githubusercontent.com/6588530/108555357-ad00d900-72f5-11eb-9ad2-2fd87e3397d2.png)

As I mentioned before, the problem is not in receiving file in MVC, but it's strictly related to model binding. 

![obraz](https://user-images.githubusercontent.com/6588530/108556486-5bf1e480-72f7-11eb-97f6-67c373a6c9a5.png)

As you can see in attached screenshot, model has not been bind to Image property of type IFormFile, but the file was correctly received by MVC and exist in HttpContext.Request.Form.Files

**Comment by pranavkm** [comment]
Sorry, I looked at `--form 'Children[0][Image]=@"/C:/Users/Tomek/Desktop/test.jpg"'` and assumed you were sending a literal file path. 

The `[]` bracket notation is primarily meant to support the format JQuery uses as part of the post. The transformation is only applied to form fields and query values not to files. That might explain the behavior you're seeing here. Does using a property notation `Children[0].Image` work?

**Comment by treformat** [comment]
@pranavkm Exactly Children[0].Image works well. Today we had a cross team consultation and for us, .NET developers, the dot notation is obvious, but other technology teams like NodeJS and PHP teams use bracket notations. Till today we didn't even know, that they send to us request in not dot notation for years... If I remember well in NodeJS they use object-to-formdata library, and they use bracket notation by default. In PHP I don't remember what kind of library they use.

I understand that in your opinion this is not a bug, but for me it's definitely some model binding inconsistency. The truth is that I didn't check what the standard of w3.org say about multi-part and dot/bracket notation.

**Comment by pranavkm** [comment]
The format for sending form content isn't standardized, so each web application framework has it's own format . MVC uses the dot notation (it's what our HTML helpers produce). It's unlikely we would add support for form files to use this notation at this point. 

If you did want to go about supporting this in your app, one possible without having to meddle with model binders and value providers might be to add a middleware that tweaks the `IFormFileCollection` to support the JQuery normalized format: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ModelBinding/JQueryKeyValuePairNormalizer.cs. Basically you would either replace or duplicate the keys in the IFormFileCollection so that MVC can operate on it as it were sent using the dot format.

**Comment by treformat** [comment]
Thanks for your answer. 👍
