### ISSUE TITLE
Specific components for dealing with large binary data (files and media)

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#30290]
Split out from #27885

@javiercn Can you fill in details? No need for a full-scale design proposal unless you're really committed to this.

**Comment by javiercn** [comment]
@SteveSandersonMS I'm going to close this issue and use https://github.com/dotnet/aspnetcore/issues/25274 to track it.

I think a big chunk of the work is done here (the support for streams we added in 6.0) and the remaining work would be handled as part of the issue mentioned above.
