### ISSUE TITLE
dotnet watch run,  iisexpress and windows authentication

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30308]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/dotnet-watch-run--iisexpress-and-window/1337489)._

---
I really like the functionality of the `dotnet watch run` , especially for developing Blazor apps. The ability to save a file and have the browser auto-refresh is a huge time saver.  Unfortunately, most of the apps that I work on are internal line of business apps that rely on using Windows Authentication -- which only works if using IIS Express.  Is there a way we can IIS Express and `dotnet watch run` to play nice together, either from the command line or from within VS?

Ctrl-F5 with IIS Express doesn't provide feedback when a file changes and doesn't auto-refresh the browser :'(

---
#### Feedback Bot on 2/14/2021, 09:58 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further. You will hear from us in about a week on our next steps.

**Comment by Tratcher** [comment]
Both Kestrel and HttpSys support Windows Authentication:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#kestrel
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#httpsys

**Comment by mkArtakMSFT** [comment]
@danroth27 can you suggest what is the VS flag to enable to have dotnet-watch similar experience work?

**Comment by danroth27** [comment]
Sure, the setting is here: 
![image](https://user-images.githubusercontent.com/1874516/108755808-8eb8fa00-74fc-11eb-84b4-e885437197c9.png)

I tried out a new Blazor Server project with Windows Auth enabled and making edits after doing a Ctrl-F5 worked for me with this setting configured.
