### ISSUE TITLE
Identity Login.cshtml should only include "There are no external authentication services configured." in development environment

### ISSUE THREAD

**Issue by xtphantom** [dotnet/aspnetcore#30305]
It seems like the message:

There are no external authentication services configured. See this <a href="https://go.microsoft.com/fwlink/?LinkID=532715">article setting up this ASP.NET application to support logging in via external services</a>.

is intended for developers, but shows up in production.  

I recommend the code Login.cshtml wrap the Developer intended message with <environment include="Development">.

**Comment by blowdart** [comment]
Should be part of https://github.com/dotnet/aspnetcore/issues/18164, so closing as dupe.
