### ISSUE TITLE
ASP .Net core development certificate error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30307]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ASP-Net-core-development-certificate-er/1334670)._

---
[severity:It's more difficult to complete my work]
! [image.png] (https://aka.ms/dc/image?name=Bb89e67a21acb4a208f45287e752e0093637484621189117876_20210209-153838-image.png&tid=b89e67a21acb4a208f45287e752e0093637484621189117876)

---
#### Feedback Bot on 2/9/2021, 05:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/9/2021, 09:59 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We are unable to reproduce this behavior. Please share more details about how you get to this error so that we can try to reproduce it.
