### ISSUE TITLE
Shrink SignalR JS Client

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#30319]
It's quite chunky at `241KB` or `129KB` minimised

![image](https://user-images.githubusercontent.com/1142958/108580789-fd435f80-7324-11eb-8310-eb2695b9e94a.png)

**Comment by davidfowl** [comment]
I blame typescript

**Comment by benaadams** [comment]
67kB shaved off  https://github.com/dotnet/aspnetcore/pull/30320

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/30320
