### ISSUE TITLE
Refresh browser after build does not work after installing .NET 6.0 preview 1

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#30318]
After installing **.NET 6.0 preview 1** on my machine, `Refresh browser after build` option on the Visual Studio for ASP.NET Core projects stopped working.

If I uninstall **.NET 6.0 preview 1** then it starts working again.

Please take a look into this.

**Visual Studio versions: 16.8.5 and 16.9.0 preview 4**

![Visual Studio](https://user-images.githubusercontent.com/14342773/108579807-e287df80-7352-11eb-9660-18c0099b8d73.PNG)

**Comment by BrennanConroy** [comment]
Can you report an issue through the VS bug report tool, usually in the top right corner of VS.
