### ISSUE TITLE
Inject component "context" into scoped dependency

### ISSUE THREAD

**Issue by AndersMalmgren** [dotnet/aspnetcore#30327]
I have "ported" a NET 5 desktop library for event aggregation between server and client to Blazor WASM. Actually it just works after I added the nuget which is pretty cool. Some details here https://andersmalmgren.com/2021/02/19/signalr-event-aggregation-with-blazor-wasm/

Anyway. Since events comes into from the server at any time I need to call Statechanged to update the component. I solved it by adding a action to my scoped service and in the razor code block I connected the two like 

```

@inject EventsViewModel Events

@code {
    protected override void OnInitialized()
    {
        base.OnInitialized();

        Events.StateHasChanged = StateHasChanged;
    }
}
```

This is not very elegant i suggest that we can inject some kind of component context interface and then call StateHasChanged on these. 

Another solution would we observable members like Vue and other MVVM libraries have.

**Comment by javiercn** [comment]
@AndersMalmgren thanks for contacting us.

It's not clear to me what you are asking us. Are you suggesting that we somehow pass in the component to the Events instance when you inject it from DI?

**Comment by AndersMalmgren** [comment]
> @AndersMalmgren thanks for contacting us.
> 
> It's not clear to me what you are asking us. Are you suggesting that we somehow pass in the component to the Events instance when you inject it from DI?

Hi something like

```csharp
public class MyService
{
   private readonly IComponentContext _ctx;
   public MyService(IComponentContext ctx)
   {
      _ctx = ctx;
   }

   public void SomeBackgroundThing()
  {
     _ctx.StateHasChanged();
  }
}
```

**Comment by AndersMalmgren** [comment]
This is how the service looks today in its whole, maybe it can help understand what I want

```csharp
public class EventsViewModel : IHandle<StandardEvent>, IDisposable
{
    private IProxyEventAggregator eventAggregator;

    public EventsViewModel(IProxyEventAggregator eventAggregator)
    {
        Events = new List<IMessageEvent<string>>();
        this.eventAggregator = eventAggregator;
        eventAggregator.Subscribe(this,
            builder => builder.For<ConstrainedEvent>()
                .Add(new ConstrainedEventConstraint {Message = "HelloWorld"}));
    }

    public void Dispose()
    {
        eventAggregator.Unsubscribe(this);
    }

    public List<IMessageEvent<string>> Events { get; }
    public Action StateHasChanged { get; set; }

    public void Handle(StandardEvent message)
    {
        Add(message);
    }

    private void Add(IMessageEvent<string> message)
    {
        Events.Add(message);
        StateHasChanged();
    }
}

```

**Comment by javiercn** [comment]
@AndersMalmgren thanks for the additional details.

Unfortunately this is not something we plan to pursue. This concept doesn't exist within the dependency injection system and we are not interested in creating a Blazor specific concept for it. It would require a non trivial amount of internal changes to the framework (if its possible at all without big hacks to the DI system) and adds a new concept/mechanic .NET users would need to be aware when using Blazor.

Its likely possible to do something like what you are doing outside of the framework via an extension method you can call on the initialization of your components that reflects over the properties and subscribes to them.
