### ISSUE TITLE
[Razor] Introduce RazorLangVersion 6.0

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#30329]
We nee to introduce a 6.0 constant [here](https://github.com/dotnet/aspnetcore/blob/main/src/Razor/Microsoft.AspNetCore.Razor.Language/src/RazorLanguageVersion.cs) since this must be in sync with the SDK

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/32672.
