### ISSUE TITLE
Blazor reconnect not working

### ISSUE THREAD

**Issue by HashemGo** [dotnet/aspnetcore#30338]
There is no any way to reconnect Blazer 
I use this code from 
https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0#modify-the-reconnection-handler

```javascript
Blazor.start({
            reconnectionHandler: {
                onConnectionDown: (options, error) => console.error(error),
                onConnectionUp: () => console.log("Up, up, and away!")
            }
        }); 
```
I never see *Up, up, and away!* if my project rebuild or after the restart IIS

reload the page solve the problem but that not a good option for my App or My Clients work, I need to reconnect like SignalR without reloading the page

###I tried to use Browser Console to disconnect manually to test functions

*First: disconnect* it gives me *undefined* but the App stoped
> Blazor.disconnect()
<- undefined
<- blazor.server.js:19 [2021-02-21T02:31:02.158Z] Error: Circuit has been shut down due to error.
e.log @ blazor.server.js:19
blazor.server.js:1 [2021-02-21T02:31:02.168Z] Information: Connection disconnected.

*Second: reconnect* the App never reconnect
> *Blazor.reconnect()*
Promise {<fulfilled>: false}

*Try to start Blazor*
> *Blazor.start()*
<- Promise {<rejected>: Error: Blazor has already started.
<-   at Object.<anonymous> (https://localhost:*****/_framework/bl…}
<- blazor.server.js:8 Uncaught (in promise) Error: Blazor has already started.
<-     at Object.<anonymous> (blazor.server.js:8)
  (anonymous) @ VM14157:1

*Try again to reconnect Blazor*
> *Blazor.reconnect()*
<- Promise {<fulfilled>: false}

I hope if there any solution for this issue without reloading the page

### Further technical details
- ASP.NET Core version 5

**Comment by javiercn** [comment]
@HashemGo thanks for contacting us.

Reconnecting only deals with intermittent network connections. If your server goes down and restarts, the state on the session is not preserved in that case and the page needs to be refreshed.

**Comment by HashemGo** [comment]
@javiercn  Thank you for reply

But when I used *Blazor.disconnect()* by Browser Console then try use *Blazor.reconnect()* not working

we hope if there any plan to support reconnect without reload page like SignalR, that is really very important to us

**Comment by javiercn** [comment]
@HashemGo If you are calling `Blazor.disconnect()` you are explicitly terminating the session on the server.

Reconnection happens automatically when its a network issue. 

If the server reboots the session is completely lost since it resides in memory and the server terminated the process.
