### ISSUE TITLE
rzc discover exited with code -2147450730.	

### ISSUE THREAD

**Issue by MuhammetTalhaKaraer** [dotnet/aspnetcore#30334]
Hi please help me,i am write a code but im wait 3 or 4 months but i open my project and i show this eror on rebuild.

`Error   rzc discover exited with code -2147450730.	ProjectName`

Describe the bug
i think thats error is rear i dont see this on every time...

Exceptions (if any)

please help

 Further technical details
```
ASP.NET Core version 5.0 and others i install but project core 3
my dotnet --info
 .NET SDK (varsa global.json dosyasını yansıtır):
 Version:   5.0.103
 Commit:    72dec52dbd

Çalışma Zamanı Ortamı:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by MuhammetTalhaKaraer** [comment]
ı see one thing for my error this line is that:<RazorTagHelper
but i am so confused what can i do for this :(

**Comment by MuhammetTalhaKaraer** [comment]
#dotnet

**Comment by javiercn** [comment]
@MuhammetTalhaKaraer thanks for contacting us.

Unfortunately we don't think we have enough information to help. Could you report this through the visual studio report a problem dialog? (Details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

That will capture more information about the environment and will help in the troubleshooting process.

**Comment by MuhammetTalhaKaraer** [comment]
> @MuhammetTalhaKaraer bizimle iletişime geçtiğiniz için teşekkürler.
> 
> Maalesef yardımcı olmak için yeterli bilgiye sahip olmadığımızı düşünüyoruz. Bunu görsel stüdyo aracılığıyla bir sorun diyaloğu bildirebilir misiniz? (Ayrıntılar [burada](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
> 
> Bu, ortam hakkında daha fazla bilgi toplayacak ve sorun giderme sürecinde yardımcı olacaktır.
@javiercn ok, i do that

**Comment by MuhammetTalhaKaraer** [comment]
> @MuhammetTalhaKaraer thanks for contacting us.
> 
> Unfortunately we don't think we have enough information to help. Could you report this through the visual studio report a problem dialog? (Details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
> 
> That will capture more information about the environment and will help in the troubleshooting process.

@javiercn ok, i do that.
