### ISSUE TITLE
Attribute based routing is not "area aware"

### ISSUE THREAD

**Issue by WolfspiritM** [dotnet/aspnetcore#30333]
### Describe the bug
After switching from 3.1 to 5.0 I noticed strange behaviours of my app as some requests are "hijacked" by other areas or in general the route order changed out of some reason. I wanted to fix it by setting a Route directly but then I noticed that when using "Route", "HttpGet" and similar attributes within an Area that has Metadata added (for example to restrict the area based on a hostname) they can cause unexpected side effects as they don't seem to be area aware and cause the Route to be "globally" available in all areas.
If I use "Route" within a controller that has the "Area" attribute with "Area1", I'd expect it to not be taken into account for routing if I use ```MapAreaControllerRoute("Area2", "Area2", "{controller=Home}/{action=Index}/{id?}")```

### To Reproduce
https://gist.github.com/WolfspiritM/78f206da531edc02a205caacee814d7e
Access http://area2.localtest.me:5000/admin
Expected result:
"Hello from Area2 admin!"

Actually result:
"Hijacked!"

### Workaround
My current workaround is a bit ugly but it seems to work as expected.
https://gist.github.com/WolfspiritM/812eb919861110e1d2c6d99dfcf8505d

I made two completly seperate routing endpoints via .MapWhen().
As the Hijack Method however gets registered for both endpoints it will still hijack the "correct" admin action in area2. I then had to find a way to only allow methods to be called that belong to the current area. That's why I made a MatcherPolicy. It checks if the routeValue "area" is the same as the "expectedArea" which can be set via .RequireArea() on the MapController() endpoint (which is returning the ConventionBuilder for the attribute based routing).

### Further technical details
- ASP.NET Core version
5.0
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS 2019

**Comment by WolfspiritM** [comment]
@javiercn @mkArtakMSFT Why has this been closed without being addressed at all? I still think this is a problem.

**Comment by ctbhavius** [comment]
There are other related issues involving routing that get closed without being addressed.  See for example 

https://github.com/dotnet/aspnetcore/issues/31293

where SuppressLinkGeneration defaults to true on MapControllerRoute endpoints.  The issue gets closed without being addressed as if it no longer exists even though the problem persists.  So will issue 31293 be re-opened as this issue 30333 has been re-opened?  In general, what will be the future of routing and support for conventional routing versus attribute routing?  Should we assume that conventional routing will be abandoned in favor of attribute routing?  Or will there be continued support of conventional routing?

**Comment by valeriob** [comment]
Hi, is this related ? https://github.com/dotnet/aspnetcore/issues/31476
