### ISSUE TITLE
Allow modifying base href from appsettings.json

### ISSUE THREAD

**Issue by Banyc** [dotnet/aspnetcore#30331]
### Is your feature request related to a problem? Please describe.
> A clear and concise description of what the problem is.
> Example: I am trying to do [...] but [...]

I am trying to change the base URL of a published blazor APP but it is not available to modify it in `appsettings.json` and no not a single `cshtml` file is in the published project folder.

### Describe the solution you'd like
> A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

Allow modifying `base href` from `appsettings.json`.

### Additional context
> Add any other context or screenshots about the feature request here.

I prefer to deploy published projects on my server. Changing a `json` file is more convenient to do some local modifications without affecting the development environment. If I have to change the base URL from `cshtml`, then I have to constantly modify the URL back when I start to develop and modify it once back when I need to deploy the project on the server.

**Comment by mrpmorris** [comment]
If your app is server hosted then you have full access to the generation of the head section in your cshtml file.

**Comment by Banyc** [comment]
> If your app is server hosted then you have full access to the generation of the head section in your cshtml file.

That is true. But in development, I prefer setting the base URL as default "/" while setting another base URL for the production environment. When using `appsetting.json`, I can make the adjustment only in `appsettings.json`. In production environment, those source code like `_Host.cshtml` is complied as `exe` or `dll`, thus no way to change the fixed base URL.

**Comment by javiercn** [comment]
@Banyc thanks for contacting us.

You can do this already by injecting the Configuration object in the template and using it to set the href attribute on the base tag or by using the environment tag helper to use different values during development and production.

**Comment by Banyc** [comment]
> @Banyc thanks for contacting us.
> 
> You can do this already by injecting the Configuration object in the template and using it to set the href attribute on the base tag or by using the environment tag helper to use different values during development and production.

Thanks for reply! The problem resolved.
