### ISSUE TITLE
Issues exposing Kestrel endpoint on Docker for Windows (was ... Http2SampleApp)

### ISSUE THREAD

**Issue by parveenLily** [dotnet/aspnetcore#30332]
Hi,
Kestrel exposing additional ports on socket does not work on docker desktop over https.
Fails to bring up the application.
Thanks
Parveen

**Comment by blowdart** [comment]
What do you mean when you say "Fails to bring up the application"?

Do you get timeouts in the browser? Do you get certificate errors? Do you get some sort of console error in the container? Does it work outside of the container when ran on the desktop directly?

How did you add additional ports to kestrel? Did you change Program.cs? If so, what changes did you make? 

Please also include 

- ASP.NET Core version
- Include the output of dotnet --info
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- Please share your config, startup.cs and

**Comment by parveenLily** [comment]
Hi, 
Thanks for getting back.
This is the sample project  at the above location. It works fine on kestrel.
I just tried to run it on docker with the docker file added from visual studio and development certificate. I installed the certificate using power shell in windows trusted root.I can attach the docker file if you want to take a look.
I could make it work behind lIS as a reverse proxy.

Thanks

**Comment by BrennanConroy** [comment]
We would recommend writing your own app and not using a sample in this repo.

Have you taken a look at the docs to try and resolve your issue?
https://docs.microsoft.com/aspnet/core/security/docker-https?view=aspnetcore-5.0

**Comment by parveenLily** [comment]
Hello,
Actually i was using my own app which has a very similar way of  binding socket port on kestrel configuration and that's the piece of code is falling through the crack on docker. Works perfectly fine on Desktop. I am using a custom certificate and install it using powershell on the container. There is no certificate error. Looks like kestrel is unable to route the request on docker. or maybe needs additional settings.
Aspnet core version 5

C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

Microsoft Visual Studio Community 2019
Version 16.8.4

Below is a Link to The project:
https://github.com/parveenLily/KestrelHttpsOnDocker/

Thank You!

**Comment by BrennanConroy** [comment]
Can you share the dockerfile? (not on a private repo please)

**Comment by parveenLily** [comment]
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:5.0-windowsservercore-ltsc2019 AS base
WORKDIR /app
User ContainerAdministrator
#install certs
COPY rootca.crt ./certs/
COPY parveen.local.pfx ./certs/

RUN powershell.exe -NoProfile -Command \  
  $pwd = ConvertTo-SecureString "rootpassword" -AsPlainText -Force ; \
  $rootcert= Import-Certificate -FilePath ./certs/rootca.crt  -CertStoreLocation Cert:\LocalMachine\Root;\
  $cert = Import-PfxCertificate -Exportable -FilePath ./certs/parveen.local.pfx -CertStoreLocation cert:\localMachine\My -Password $pwd; 

EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["KestrelHttps.csproj", ""]
RUN dotnet restore "./KestrelHttps.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "KestrelHttps.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "KestrelHttps.csproj" -c Release -o /app/publish 

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KestrelHttps.dll"]

**Comment by BrennanConroy** [comment]
There are known issues with Windows Containers, could you take a look at https://github.com/microsoft/iis-docker#on-older-hosts-windows-server-version-1709-and-older to see if it resolves the issue?

**Comment by parveenLily** [comment]
I am running latest windows server 2019 docker image with aspnet core 5 installed.
docker image: mcr.microsoft.com/dotnet/aspnet:5.0-windowsservercore-ltsc2019
https://hub.docker.com/_/microsoft-dotnet-sdk/
And i also tried the container ip to access the site, nothing seems to work.
![image](https://user-images.githubusercontent.com/52086691/109364401-ba214900-785c-11eb-9d7d-807ab2e1ab7c.png)

**Comment by BrennanConroy** [comment]
> nothing seems to work

What issues are you seeing?

To confirm, you did `docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" my-running-site` to get the ip and tried that?

**Comment by parveenLily** [comment]
Hello,
Yes I did. Just to reiterate, same setting of the project works when i place them behind a mature web/reverse proxy server like IIS or nginx. So , is this behavior  by design since kestrel is a light weight server  as opposed to IIS or nginx.

**Comment by BrennanConroy** [comment]
Can you share your apps logs?

Our hypothesis is that you're binding to the loopback url.

**Comment by parveenLily** [comment]
The project is on github and shared with you.
I am binding: ipAddresses.Add(IPAddress.Any) and running linux containers,

**Comment by BrennanConroy** [comment]
This is outside the scope of what we can support through GitHub. You can reach out to paid support at http://support.microsoft.com/supportforbusiness/productselection?sapId=ef53b119-5f8c-7343-2a0f-f5008a1399b9

**Comment by parveenLily** [comment]
I believe this is an issue with kestrel binding to socket endpoint. 
thanks!
