### ISSUE TITLE
Blazor JS Interop issues with Browser's langue settings

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#30348]
It seems Blazor JS interop is trying to obey Browser's Preferred language settings. Which probably is good, however it is causing issues. I'm trying to make a call from JS code to Balzor with a DotNetRef. It was working good basically all the time but now run into an issue. 
When I try to call a C# method with a `double` value which has a decimal separator `.` in .NET. And most of Languages also uses decimal separator for `.` (dot) however some Languages has different decimal separator e.g. `,` (coma). So JS interop and JSON parser works fine when I have a browser with `en-US` settings. But with other language setting it does not work e.g. with `hu-HU`.

**In this case as you can see in JS debugger I have a valid a value of `47.437698399999995`:**
![image](https://user-images.githubusercontent.com/7632824/108631484-67195180-746a-11eb-970c-4116efd73678.png)

**After calling to .NET code I cannot see my values rendered on UI. Checked the console log and warning message showed the number value changed ot `47,437698399999995`:**
![image](https://user-images.githubusercontent.com/7632824/108631518-94fe9600-746a-11eb-9bbc-3266bf78def3.png)

So the question is it a bug? For me it looks like JS `number` values treated as `string` in JSON when interop-ed to .NET. And conversion basically changes types by using browser language preferences but on .NET side it will fail....

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by majorimi** [comment]
Hi @mkArtakMSFT,
Basically it is a simple `DotNetObjectReference` passed into JS code. And when some event happens a callback will be made on that .NET Ref into a `[JSInvokable()]` method. Which expects some arguments one of which is a `double` type. Simple and standard JS interop as usual...

The problem with your request is if I prepare an example code and you **run it with a browser which [Preferred language](https://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference) is `en-US` code will run FINE**.  Since you probably live in the US most likely your settings won't cause any issues. Code will fail only when your **environment** is set to prefer languages where the `decimal` separator is not `.`

**The requested example might lead to a wrong conclusion which is that: code works FINE. Because I cannot check in environment (Windows and Browser) setting into Git...**

**Comment by mkArtakMSFT** [comment]
@majorimi can you please provide a minimalistic repro project for us to investigate this further?

**Comment by majorimi** [comment]
Hi @mkArtakMSFT,
Thanks for checking this again. 
As already mentioned I can provide a simple `JS callback` example which returns a `double`. **BUT it will work just fine if the developer Browser language is the same as OS/Visual Studio CultureInfo. _With C#/JS code I cannot control the developer environment!_**

Basically type conversion for `DotNetObjectReference.invokeMethodAsync()` in JS somehow should be parameterized with the [IFormatProvider/CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.convert.changetype?view=net-5.0#System_Convert_ChangeType_System_Object_System_Type_System_IFormatProvider_).
Thanks.
