### ISSUE TITLE
[wasm] Blazor on Safari: The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.

### ISSUE THREAD

**Issue by JamieMair** [dotnet/aspnetcore#30347]
### Describe the bug

When trying to load my site on Safari browsers, I get the following errors:
```
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
```
These are repeated for around 10 errors in total. I cannot figure what in the website is causing this issue.

Whatever this issue is, it means that the content is not being loaded on the front page, with only the header and footer being displayed. The content in the middle of screen loads, but is blocked from view.

The link to the site is [here](https://sbphysio.z33.web.core.windows.net/). The site works perfectly on Chrome and Firefox, it is only Safari.

### To Reproduce

Go to this [link](https://sbphysio.z33.web.core.windows.net/) on any Safari browser, as try to see the front page. It should have four images in grayscale, with the headers "Home", "About", "Services" and "Contact".
### Exceptions (if any)

```
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
```
### Further technical details
Version of Dotnetcore is 5.0

Website is hosted on Azure static storage, but issue also occurs on Github pages.

**Comment by javiercn** [comment]
@JamieMair thanks for contacting us.

I don't think this is related to Blazor. The template doesn't include a CSP policy, so there must be something in your app that is adding it, but I can't find it. The warnings you are seeing might be because Safari doesn't support those values.
