### ISSUE TITLE
Investigate what git diff looks like with the new Razor editor

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#30358]
Hello,

There are various warnings for HTML when reviewing changes in '_Git Changes_' view.
They don't appear when the view is '_Solution Explorer_'.
Here is a screenshot:

![Warning](https://user-images.githubusercontent.com/16502423/108694777-c83f3480-74ff-11eb-9834-f29217629cc4.png)

Visual Studio Version 16.9.0 Preview 4.0

**Comment by TanayParikh** [comment]
@NTaylorMullen just to clarify on the filter-diagnostics side of things. We would like to specifically filter out `Element 'option' cannot be nested inside element 'div'.` when that error appears inside a `@foreach`? I think the last part of that I may've misunderstood (ie, when do we not want to see the diagnostic).

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen just to clarify on the filter-diagnostics side of things. We would like to specifically filter out `Element 'option' cannot be nested inside element 'div'.` when that error appears inside a `@foreach`? I think the last part of that I may've misunderstood (ie, when do we not want to see the diagnostic).

Not quite, suppress it when nested inside of a component because we can't know what that component will actually do

**Comment by TanayParikh** [comment]
Un-assigning myself as https://github.com/dotnet/aspnetcore-tooling/pull/3206 has been merged.

**Comment by allisonchou** [comment]
There are two issues which seem to exist with git diff today:
1. Double clicking on the file name in Git Changes doesn't automatically open git diff as it does in non-LSP scenarios. Instead, we have to right click->"Compare with Unmodified". Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1327674/ to track. (Sidenote - sorry, I don't know why the pic below is so large, and not sure how to resize it.)
![image](https://user-images.githubusercontent.com/16968319/118192409-f182a900-b3fa-11eb-885a-abd54005593b.png)

2. TextMate isn't colorizing the C# portions of the diff. Once the TextMate issue on the core editor is fixed (linked in this issue: https://github.com/dotnet/aspnetcore/issues/26975), we can hopefully re-enable C# TextMate highlighting.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/16968319/118192695-61912f00-b3fb-11eb-8e60-2bf356cc399d.png)
