### ISSUE TITLE
Debugging Blazor Apps with WebAssemblyServer 5.0.x Kills IIS Express

### ISSUE THREAD

**Issue by nolanblew** [dotnet/aspnetcore#30353]
### Describe the bug
On a Blazor WASM project, upgrading the Server to .NET 5 AND upgrading the `Microsoft.AspNetCore.Components.WebAssemblyServer` package to 5.0.x (I just tried the latest, 5.0.3) breaks any client-side debugging. After setting a breakpoint on a client page, the breakpoint does get recognized and turns fully red. However, the moment that breakpoint is hit, the .NET debugger detaches without warning or messages and IISExpress expectantly closes.

Also, attempting to debug using the remote debugger fails as well.

#### BREAKPOINT WITH `Microsoft.AspNetCore.Components.WebAssemblyServer = 3.2.1` (Click GIF for full-screen resolution)
![working](https://user-images.githubusercontent.com/1565705/108663334-2f6bd300-7485-11eb-9d14-54203b506343.gif)

#### BREAKPOINT WITH `Microsoft.AspNetCore.Components.WebAssemblyServer = 5.0.3` (Click GIF for full-screen resolution)
![not_working](https://user-images.githubusercontent.com/1565705/108665045-da31c080-7488-11eb-88f6-2c4112af76f9.gif)

### To Reproduce
You can easily repro with a clean, new project:

1. Create a new `Blazor App` project
2. Select `Blazor WebAssembly App`
  a. Ensure `Configure for HTTPS` is selected (because I haven't tested it off)
  b. Ensure `ASP.NET Core hosted` is selected (because I haven't tested it off)
  c. `Progressive Web Application` has been tested both on and off with no change 
3. Once the project is created, navigate to the Client project in Solution Explorer, and go to `Pages/[anypage]`. Set a breakpoint in the code on any page that has code (I personally used the `Counter` page as it's very simple)
4. You may run the project now and ensure the breakpoint hits, or just skip to the next step
5. Right click on `TestBlazorApp.Server` and click `Properties` (or you can do the next 2 steps using the .csproj)
6. Under `Target Framework`, select `.NET 5.0`
7. Right click again on TestBlazorApp.Server` and click `Manage NuGet Packages...` 
6. There should only be 1 package, the `Microsoft.AspNetCore.Components.WebAssemblyServer` which is on `v3.2.1`. Choose to upgrade this to `5.0.3` (the current latest)
7. Now clean and rebuild the project for good measure, though I found this not necessary to produce the bug
8. Finally, run the app and hit the breakpoint again. Observe how IIS Express suddenly closes, and Visual Studio is no longer debugging the app.

If you can't seem to repro or for other reasons would like me to create a sample github repo I can!

### Exceptions (if any)
I couldn't find any exceptions. IIS Exited with code -1, there is nothing in the EventViewer.

### Further technical details
I am using the latest stable version of Visual Studio (16.8.5) along with the latest stable version of .NET that comes with Visual Studio. I believe that IIS is on 10.0. I am using a Windows 10 Pro Edition x64 with 64GB RAM and over 500GB of SSD space remaining. I have also tested on a separate device, a Surface Pro 7 with the VS Preview installed with the same result.

Using Chromium Edge: Dev (build 90.0.796.0) as well as the latest version of Chrome.

**Comment by captainsafia** [comment]
@nolanblew Can you try clearing out the `.vs` directory next to the solution file of the project in question?

Also: are you able to reproduce the same issue when debugging with Kestrel?

**Comment by nolanblew** [comment]
> @nolanblew Can you try clearing out the `.vs` directory next to the solution file of the project in question?
> 
> Also: are you able to reproduce the same issue when debugging with Kestrel?

Unfortunately none of those helped.

Here's the output from kestrel (with the full directories redacted): 
![image](https://user-images.githubusercontent.com/1565705/108750554-059ec480-74f6-11eb-99d7-a4e8e8be1d32.png)

Deleting the `.vs` directory (I even restarted my computer for good measure) didn't help, though given I've been able to repro this issue on every PC with VS installed I hope it wouldn't be a corrupt `.vs` directory

**Comment by captainsafia** [comment]
> Here's the output from kestrel (with the full directories redacted):

It looks like the debug proxy is launching and running on port 52636. Are you able to debug?

cc: @BrennanConroy for IIS express issues

**Comment by BrennanConroy** [comment]
I noticed in your 5.0 gif, the dotnet webassembly loaded is still version 3.2.

Can you try deleting the bin and obj folders for all projects manually, or just creating a 5.0 app in the first place to see if the issue still repros?

**Comment by nolanblew** [comment]
@captainsafia 

No. When trying to use the remote browser debugger on kestrel in a debugging-browser (ALT+SHIFT+D) I get an empty page, and the kestrel output gives me this error:
```
Hosting environment: Production
Content root path: C:\Users\nolan\source\repos\TestBlazorApp\TestBlazorApp\Server
Now listening on: http://127.0.0.1:60346
Application started. Press Ctrl+C to shut down.
got exception System.Net.WebSockets.WebSocketException (997): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()
got exception System.Net.WebSockets.WebSocketException (997): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()
got exception System.Net.WebSockets.WebSocketException (997): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()
   ```

**Comment by nolanblew** [comment]
> I noticed in your 5.0 gif, the dotnet webassembly loaded is still version 3.2.
> 
> Can you try deleting the bin and obj folders for all projects manually, or just creating a 5.0 app in the first place to see if the issue still repros?

@BrennanConroy  Alright, I've closed VS, deleted the `.vs`, deleted all the `bin` and `obj` folders, deleted all my nuget caches, restarted my computer, and tried again with no avail. The issue still persists.

(Loading the dll on startup in the output now reveals:
```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Users\nolan\source\repos\TestBlazorApp\TestBlazorApp\Server\bin\Debug\net5.0\Microsoft.AspNetCore.Components.WebAssembly.Server.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

Is that where you were looking when you determined it was still loading the old dll?

**Comment by BrennanConroy** [comment]
No, I was looking at the browser output. It was showing wasm/dotnet.3.2.0.js in the developer tools

**Comment by captainsafia** [comment]
@nolanblew Can you upload the project you running into to GH so we can try to repro on our end? It would help safe the back-and-forth.

Also, there should be a log file (visualstudio-js-debugger.txt) in your $TEMP$ directory that would provide some additional details.

**Comment by nolanblew** [comment]
> No, I was looking at the browser output. It was showing wasm/dotnet.3.2.0.js in the developer tools

@BrennanConroy You got it :+1: In the prod version of VS there's no easy way to upgrade the WASM project to .NET 5 through the UI, so it was still on netstandard 2.1. Editing the csproj to force the WASM to .NET 5 fixed the issue.

I wish there was a clearer error/warning outputted when running an unsupported WASM version. Best case would be a dependency block or compile-time error, though that might be hard since the package is applied to the server, not the client project

**Comment by nolanblew** [comment]
> @nolanblew Can you upload the project you running into to GH so we can try to repro on our end? It would help safe the back-and-forth.
> 
> Also, there should be a log file (visualstudio-js-debugger.txt) in your $TEMP$ directory that would provide some additional details.

@captainsafia If you'd like I can still upload the project, though I solved my particular issue. The WASM project was not .NET 5 (as there is no template available at the moment) and there was no indication that it had to be for the dependency on the server to debug correctly. Upgrading my WASM project manually through the `.csproj` file and cleaning+rebuilding solved the issue

**Comment by captainsafia** [comment]
@nolanblew I think we tracked down the root issue in this case. There's some JS-code that enables the debugger that was changed between 3.2 and 5.0. The problem you ran into was likely a result of the incompatibility between the two.
