### ISSUE TITLE
.AddDataProtection().PersistKeysToDbContext<KeyDbContext>() configured but not used?

### ISSUE THREAD

**Issue by angelaki** [dotnet/aspnetcore#30351]
In my `ConfigureServices` I'm setting a the EfProtectionBuilder

```
paramServiceCollection.AddDataProtection()
    .PersistKeysToDbContext<KeyDbContext>()
    .SetApplicationName(_appSettings.AppName)
    ;
```

and the table is generated / a record added. But the logger still says

> Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.

and after restarting the container the credentials do not work any more. What could cause this issue?

**Comment by blowdart** [comment]
Could we first see your startup.cs (with any secrets removed) and version information about what version of .NET Core or .NET you're using?

**Comment by angelaki** [comment]
Sorry for not mentioning! I'm using version `5.0.3`. Showing my startup.cs is not really possible, since the application is bootstrapped by some kind of framework. Several dlls are registered, that can append services. Is "PersistKeysToDbContext" need to be called before some other calls are?

**Comment by blowdart** [comment]
If something else has registered data protection beforehand then it's going to default to the file system inside a container because there's no other option, so yea, register it as early as possible. You may be able to figure it out what's doing it from where that log gets written.

**Comment by angelaki** [comment]
Ok, thank you! Put it to the very beginning now and it works! I'll check now what service exactly caused the issue and let you know! Thank you so much for supporting!

**Comment by angelaki** [comment]
Just had a hell of a debuging session for finding out: adding `var x = new DataProtectionOptions();` to my Program.cs solved the issue!

I'm using an `AssemblyLoadContext` for lazy loading my modules. The only difference is: eager loading `DataProtectionOptions` makes him know the lib in the AssemblyLoadContext's `protected override Assembly Load(AssemblyName paramAssemblyName)`.

If it is **not** eager loaded he needs to load the Assembly from the the file system

`return LoadFromAssemblyPath(assemblyPath);`
assemblyPath = C:\Users\tsproesser\.nuget\packages\microsoft.aspnetcore.dataprotection\5.0.3\lib\net5.0\Microsoft.AspNetCore.DataProtection.dll

What the hell could cause this? Any ideas where else to search? The solution is ok for me for now - but really not satisfying ...

**Comment by blowdart** [comment]
Data Protection is, well, special. It needs to be configured immediately, otherwise when a protection is requested (and they're requested a few places, not just for cookies, csrf uses it for example) it will initialise itself and try to figure out the best place to persist keys. On linux it can't do it well at all, so it goes in memory, or if it's in a container it kind of figures out somewhere so it can at least run until it's shut down. It can't rely on everything in the stack being there. 

So if you're lazy loading it, it's not going to get that configuration.

**Comment by angelaki** [comment]
Haha... Ok, so my horrible fix is still probably the best. But still: any idea where to dig for a cleaner solution? I don't get why an lazy loaded assembly shouldn't work?

**Comment by blowdart** [comment]
For data protection? No, due to how it's used by multiple components, and it's self configuration I think you're stuck with "horrible"

**Comment by angelaki** [comment]
At least it got an milestone 👍  Thank you so much! Issue would have taken me days! So for now

`private readonly DataProtectionOptions _dpo = new DataProtectionOptions();`

in `Program.cs` is the solution.
