### ISSUE TITLE
HTTP_ACCEPT_LANGUAGE header in not supported by Localization middleware

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#30352]
Handle additional localization request headers out of the box.

Safari uses HTTP_ACCEPT_LANGUAGE which our middleware doesn't look for, which results in localization not working by default.

**Comment by javiercn** [comment]
The fix likely involves checking for additional language headers [here](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Localization/src/AcceptLanguageHeaderRequestCultureProvider.cs)

**Comment by Marusyk** [comment]
Please assign it to me. I'll try to prepare a PR

**Comment by Marusyk** [comment]
@javiercn 
Do you mean to look for `HTTP_ACCEPT_LANGUAGE` not only `Accept-Language`?

**Comment by Marusyk** [comment]
Related #27368

**Comment by pranavkm** [comment]
Closing until we can figure out if this is necessary. It's not clear if the header is actually being sent by the browser.
