### ISSUE TITLE
GRPC over Javascript Interop

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#30357]
## Summary

At the moment we don't have any type-safe and contract based way to communicate between Blazor Webassembly and Typescript. The Javascript Interop allows us only to call methods by name. GRPC over Javascript Interop could solve that gap. What would be needed is to replace the underlying socket based communication of GRPC with Javascript/Dotnet Interop calls.

## Motivation and goals

It would give us great benefits:
* high performance - the data transport could be optimized with marshaling of the data (byte streams)
* * so it won't use json serialization and copy the data all the time - like it is done by default with the arguments of Javascript interop calls
* Type-safe and technology independent contract (proto files) between C# and typescript that is always in sync
* interoperability (you could replace either the C# side or typescript side with something else later on)
* out of the box features like streaming, which we don't have yet with blazor-jsinterop

## In scope

* Blazor WebAssembly
* Typescript
* GRPC

## Examples

1. Define a service contract with GRPC proto files
2. use GRPC tooling to generate the typescript client and the C# server for it
3. implement the server side behavior, by overwriting the auto generated grpc server methods
4. Instantiate the client with a custom CallInvoker (which marshals the data over dotnet interop to Blazor Wasm)
5. Instantiate the server with a custom ServerCallContext (which marshals the data over javascript interop to Javascript)
6. call your generated methods from client side (typescript)

I think the same scenario might be possible vice versa with a C# client and a Typescript server. I just don't know if there's a Typescript server generator for proto files available.

# Detailed design

## Considered alternatives
- json rpc maybe - but it would be much slower 
## Open questions
- how can the http/http2 based communication be replaced on TypeScript side? Is there a possibility to pass in a CallInvoker like on the grpc .NET side?

## References
https://github.com/grpc/grpc-dotnet/issues/1208

**Comment by javiercn** [comment]
@TFTomSun thanks for contacting us.

I don't think this is feasible in principle. GRPC requires you to have a contract and JSInterop needs to work without the need for defining a contract.

**Comment by TFTomSun** [comment]
@javiercn yes, it's the same with http/http2 requests. They don't define a contract, too. But they allow communication between 2 endpoints. GRPC is a service definition on top of http/http2. So why not having a GRPC solution on top of JSInterop, to provide a contract based communication between Blazor WebAssembly and Typescript?

**Comment by javiercn** [comment]
@TFTomSun because such a contract forces everybody to define a contract to use JSInterop and that's a huge departure with the current experience.

**Comment by TFTomSun** [comment]
@javiercn  ah.. sorry. You got me wrong. I would just see it as an optional feature. Everybody is free to choose whether they want a contract based communication or pure JSInterop. Same like it is with HTTP requests and GRPC web.

**Comment by BrennanConroy** [comment]
Sounds like you effectively want to host **all** of aspnetcore inside of blazor wasm which is a non-goal for us.
