### ISSUE TITLE
PageResult invalid de/serialization

### ISSUE THREAD

**Issue by johan-v-r** [dotnet/aspnetcore#30362]
### Describe the bug

`Microsoft.AspNet.OData.PageResult` excludes properties when serializing, and fails on deserialization with `System.Text.Json.JsonSerializer`

### To Reproduce
```cs
var foo = new Microsoft.AspNet.OData.PageResult<string>(new List<string>
{
	"test"
}, new Uri("http://foo"), 1);

var json = System.Text.Json.JsonSerializer.Serialize(foo); // serializes to [\"test\"]
var bar = System.Text.Json.JsonSerializer.Deserialize<Microsoft.AspNet.OData.PageResult<string>>(json); // throws System.NotSupportedException : The collection type 'Microsoft.AspNet.OData.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated.
```

### Exceptions (if any)

>  System.NotSupportedException : The collection type 'Microsoft.AspNet.OData.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
    ---- System.NotSupportedException : The collection type 'Microsoft.AspNet.OData.PageResult`1[System.String]' is abstract, an interface, or is read only, and could not be instantiated and populated.

### Further technical details
- ASP.NET 5.0

**Comment by javiercn** [comment]
@johan-v-r thanks for contacting us.

This is not asp.net core specific. We suggest you file this issue in the [OData repository](https://github.com/OData/AspNetCoreOData) instead.
