### ISSUE TITLE
Large disk size increase in Microsoft.NET.Sdk.Razor folder

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#30379]
Between 6.0 Preview 1 and the current build of Preview 2, the size of the `Microsoft.NET.Sdk.Razor` folder increased by 180%.  In absolute terms, this is an increase of 45 MB.  A portion of this increase is due to the addition of the `source-generators` sub-folder which is understandable.

More concerning is the 100% increase in the `tasks` sub-folder and the 188% increase in the `tools` sub-folder.  These two folders contain the same amount of files between P1 and P2 but the size of those files has dramatically increased.  For example, the `Microsoft.CodeAnalysis.CSharp.dll` file went from 5.4 MB in P1 to 15.5 MB in P2.  That doesn't seem right.

### Repro Steps

1. Download and extract [6.0 Preview 1 SDK](https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.1.21103.13/dotnet-sdk-6.0.100-preview.1.21103.13-win-x64.zip)
2. Download and extract [6.0 Preview 2 SDK](https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100-preview.2.21120.3/dotnet-sdk-6.0.100-preview.2.21120.3-win-x64.zip)
3. Compare folder contents in a tool like Beyond Compare.
4. Navigate to `sdk\[version]\Sdks\Microsoft.NET.Sdk.Razor` path to compare contents.

cc @captainsafia

**Comment by captainsafia** [comment]
Note: moving this to the aspnetcore repo since that is where we are tracking these issues.

I can repro this. It also appears to be happening on Blazor WASM SDK, although to a less extent by virtue of the fact that that SDK is smaller.

![image](https://user-images.githubusercontent.com/1857993/108778703-a010ff00-751a-11eb-8811-44a41f8b6fdd.png)

We'll need to investigate further...

**Comment by captainsafia** [comment]
A thought: a change was introduced as part of preview2 to support crossgenning assemblies associated with the SDKs we migrated over (Razor and Blazor).

The size difference stats that were shared in that PR were within tolerable measures (https://github.com/dotnet/installer/pull/9635#issuecomment-775576053) and definitely not the 2x and 3.5x increases we are seeing here.

@brianrob Any thoughts on what might be going on here?

**Comment by brianrob** [comment]
The differences that I saw when precompiling just the DLLs was +33MB.  I'm not sure how big the source generators are - do they make up the 12MB difference?

**Comment by captainsafia** [comment]
@brianrob Yes, it does. The source generators directory is 11.8 MB.

I interpreted the data in the linked comment incorrectly. It looks like the size increases that we see here _are_ within the ranges that were identified in the original PR.

**Comment by brianrob** [comment]
Ok, yes, then in that case, you're right, this is expected.

**Comment by captainsafia** [comment]
@brianrob Thanks for clarifying.

@mthalman Closing this issue as it's the result of the work done in https://github.com/dotnet/installer/pull/9635. We're making a trade-off between SDK size and perf here.

**Comment by captainsafia** [comment]
Updated: ended up doing some work to reduce the 12mb impact from adding the source generators to the SDK: https://github.com/dotnet/sdk/pull/16059
