### ISSUE TITLE
Blazor Server App with SignalR refuses to work... Why ?

### ISSUE THREAD

**Issue by enetstudio** [dotnet/aspnetcore#30383]
I've created a Blazor Server App with individual accounts, added a Signalr hub, and a client page - the traditional chat application.

I tested the app, and all works perfectly well. I then added the Authorize attribute to my hub like this:

      [Authorize]
      public class ChatHub : Hub
     {
        public async Task SendMessage(string user, string message)
        {
            await Clients.All.SendAsync("ReceiveMessage", user, message);
        }
      } 

And this time tested my chat app with an authenticated user, but always get the unauthorized (401) error. I'm not sure I understand why. 

Here's the code of the client page:

    protected override async Task OnInitializedAsync()
    {
            hubConnection = new HubConnectionBuilder()
            .WithUrl(NavigationManager.ToAbsoluteUri("/chathub"))
            .Build();
      
        hubConnection.On<string, string>("ReceiveMessage", (user, message) =>
        {
            var encodedMsg = user + " says " + message;
            messages.Add(encodedMsg);
            StateHasChanged();
        });

        await hubConnection.StartAsync();
     }

As far as I know, in Blazor WebAssembly  I set HttpConnectionOptions.AccessTokenProvider to the access token provider that  will be called to return the access token for each HTTP request, but it is not clear what I should do when using Blazor Server, so I've open the docs and found this: 

Cookie authentication
In a browser-based app, cookie authentication allows your existing user credentials to automatically flow to SignalR connections. When using the browser client, no additional configuration is needed. If the user is logged in to your app, the SignalR connection automatically inherits this authentication.
[Source](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#cookie-authentication)

Now I'm confused...Please help...

**Comment by javiercn** [comment]
@enetstudio thanks for contacting us.

You are not authenticating to the SignalR hub from the browser, but from the server. In your case your connection is (Server->Server) instead of (Browser->Server) when you try to establish the connection in this case, the SignalR client doesn't have the necessary cookie to authenticate with the hub successfully.

One possible way around this is to capture the cookie when you render the Blazor server page in _Host.cshtml and flow it around.

**Comment by enetstudio** [comment]
@javiercn, many thanks for your response... Could you please give me some hints as to how I can use the captured cookie in SignalR ! I know how to pass an access token with the SignalR connection, but have no idea how to perform such a task with the captured cookie. Once again, many thanks for the invaluable help you always offer ...
