### ISSUE TITLE
Visual Studio 2019 version 16.9 Preview 4 Intellisense is not working at all

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30380]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-2019-version-169-Preview-/1337155)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9 preview 3]
Visual Studio 2019 version 16.9 Preview 4 Intellisense is not working at all no differentiation between components ant html code and also cannot use prop or ctor or any other code snippets

---
#### Feedback Bot on 2/13/2021, 09:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg can you take a look at the Razor logs and see if there's something unexpected going on here? If not, can close out as no repro because we haven't seen this as of late.
