### ISSUE TITLE
JSON parse error when invoking 3rd party script, only when Authenticated. Blazor webassembly hosted, integrated auth

### ISSUE THREAD

**Issue by sourcejon** [dotnet/aspnetcore#30393]
### Describe the bug

When the javascript Worldpay.useTemplateForm() is invoked from the blazor component, I am getting JSON parse errors (unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Worldpay.helpers.JSON.parse (worldpay.js:2)
    at h )

These errors appear to be firing every 2 seconds. This issue only occurs when a user is authenticated.

Console screenshot when user is not authenticated.
![image](https://user-images.githubusercontent.com/10117395/108830610-81197800-75c1-11eb-9d1a-c74894097780.png)

Console screenshot when user is authenticated
![image](https://user-images.githubusercontent.com/10117395/108831195-ac03cc00-75c1-11eb-82b3-e62b3ba7eee2.png)

### To Reproduce
Create a Blazor WebAssembly hosted project with Integrated Authentication.

Add reference to Worldpay JS in index.html (https://developer.worldpay.com/docs/wpop/template-form)
<script type="text/javascript" async src="https://cdn.worldpay.com/v1/worldpay.js"></script>

Add javascript file and include reference to Index.html with the following JS
https://github.com/sourcejon/BlazorAuthIssue/blob/main/scripts.js

Add Razor component and use that component on the counter page
https://github.com/sourcejon/BlazorAuthIssue/blob/main/Worldpay.razor

The Client Key error, is due to fake credentials, it does not affect the issue.

### Exceptions (if any)
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Worldpay.helpers.JSON.parse (worldpay.js:2)
    at h (worldpay.js:2)

### Further technical details
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.813 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS Pro 2019 - 16.8.5

**Comment by sourcejon** [comment]
Further note:

The issue only appears when a callback function is passed to Worldpay.useTemplateForm().
The issue appears with or without the DotNetObjectReference argument.

So I'm a little lost as to why JS Interop would throw JSON parse errors, only when a user is authenticated and there is a callback function.

**Comment by javiercn** [comment]
@sourcejon thanks for contacting us.

You shouldn't be invoking an async task without awaiting it `https://github.com/sourcejon/BlazorAuthIssue/blob/main/Worldpay.razor#L38` instead of doing that in the constructor, override OnInitializedAsync and do it there.

As for the error, it seems to be something in your app. Not sure what [this](https://github.com/sourcejon/BlazorAuthIssue/blob/main/scripts.js#L10) is but it looks suspicious.

**Comment by javiercn** [comment]
We don't think this is a JS interop issue but likely an issue in your code, we suggest setting up breakpoints in JavaScript to ensure that the arguments are matching as you are expecting.

**Comment by sourcejon** [comment]
@javiercn I appreciate your feedback and have created a simpler example, without the issues that side tracked you before. The issue however still persists.

> As for the error, it seems to be something in your app. Not sure what this is but it looks suspicious.

That was a callback to a JS invokable, function not relevant to the issue and it has been removed.

**Comment by javiercn** [comment]
@sourcejon thanks for the additional details.

Can you point us to this new sample?

**Comment by sourcejon** [comment]
@javiercn 
https://github.com/sourcejon/BlazorAuthIssue/blob/main/scripts.js
https://github.com/sourcejon/BlazorAuthIssue/blob/main/Worldpay.razor

**Comment by sourcejon** [comment]
@javiercn 

> Can you point us to this new sample? Preferable something not involving a third-party library.

unfortunately I don't have an example without a third party library.

What I can tell you is that from my research is that the JSON parse errors, only occur when:

- There is a callback function added
- the user is authenticated

I actually suspect the issue is not with JS Interop, but with the JS authentication library as the issue only occurs when a user is authenticated.
`<script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>`

**Comment by javiercn** [comment]
@sourcejon there's nothing in the call stack that involves the auth library

**Comment by sourcejon** [comment]
> @sourcejon there's nothing in the call stack that involves the auth library

@javiercn that's very strange, as you can setup the example without any authentication mechanism and you do not get the JSON parse errors. Secondly as I've stated it also runs without JSON parse errors when the user is not authenticated.

**Comment by sourcejon** [comment]
Just to update, the issue still appears on 5.0.5

**Comment by sourcejon** [comment]
@javiercn So I decided to revisit this and do some more digging, it appears that the WorldPay Script is trying to parse the MessageEvent sent by the AuthenticationService > checksession (line 306) e.source.postMessage(result, e.origin);

The script is failing to parse the message and I'm seeing this as those console errors.

**Comment by sourcejon** [comment]
Issue confirmed with 3rd Party script incorrectly trying to parse the MessageEvent sent by the AuthenticationService, closing issue.
