### ISSUE TITLE
The user aborted a request

### ISSUE THREAD

**Issue by Seanxwy** [dotnet/aspnetcore#30394]
#28775 There is no progress and the problem still exists. I wonder why it has not been dealt with

**Comment by javiercn** [comment]
@Seanxwy thanks for contacting us.

Can you produce a minimal repro project as well as detailed steps on how to reproduce the issue so that we can better understand what might not be working here correctly?

**Comment by Seanxwy** [comment]
@javiercn  The default WASM project template created using VS2019 has this problem

**Comment by javiercn** [comment]
@Seanxwy we need more details about your environment. We are not observing the behavior you mention. Please indicate the following:
* Browser (with version) you are using.
* .NET SDK version as well as library versions.
* Visual Studio version.
* Include at the very least a screenshot of the error, but we strongly encourage to produce a repro project if possible, otherwise its likely we miss something about the project/environment.

**Comment by Seanxwy** [comment]
![image](https://user-images.githubusercontent.com/15828095/108841639-0aa56600-7613-11eb-9989-ac8cb3993abd.png)
browser use edge version is 88
use .net 5.0
vs 2019 16.8.5

Create a WASM project directly using VS without any modifications

**Comment by captainsafia** [comment]
@Seanxwy Thanks for sharing the repro. Some follow-ups:

- Is this consistent across different operating systems? Will it repro on the same machine?
- Does changing the browser (Chrome, Firefox) affect the repro at all?

**Comment by Seanxwy** [comment]
@captainsafia 
This is true on many different PC devices, with different versions of Windows 10, and with Chrome, which Firefox has not tried

**Comment by mkArtakMSFT** [comment]
@Seanxwy can you also provide:
1. The full screenshot of the browser network tab, when the issue happens. We would like to see the failed request and the error code it fails with
2. your OS region  / language settings
3. the language settings from your browser

**Comment by Seanxwy** [comment]
![image](https://user-images.githubusercontent.com/15828095/109516265-f5cd4480-7ae2-11eb-8049-56f8a4fe4f27.png)

@mkArtakMSFT  
The region is China and the language is Chinese
Browser language is Chinese

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
