### ISSUE TITLE
Reuse cancellation token sources in the Kestrel

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#30390]
Today we use the request aborted token when writing large responses in various places. We can reuse these tokens across requests if they haven't been cancelled. We can take advantage of https://github.com/dotnet/runtime/issues/48492 when it becomes available.

Here's what a simple application that uses the request aborted token looks like:

```C#
var host = new HostBuilder().ConfigureWebHostDefaults(host =>
{
    host.Configure(app =>
    {
        Task Hello(HttpContext context)
        {
            return context.Response.WriteAsync("Hello World", context.RequestAborted);
        }

        app.UseRouting();

        app.UseEndpoints(routes =>
        {
            routes.MapGet("/", Hello);
        });
    });
}).Build();


await host.RunAsync();
```

Here's the allocation profile after ~10K requests

|Type|Allocations|Bytes|Average Size \(Bytes\)|
|-|-|-|-|
| - System.Threading.CancellationTokenSource|10,250|656,000|64|
| - System.SByte\[\]|1,500|312,000|208|
| - Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection\<Context\>|125|97,000|776|
| - System.IO.Pipelines.Pipe|250|96,000|384|
| - Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs|250|88,000|352|
| - Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders|125|67,000|536|
| - Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders|125|49,000|392|
| - System.IO.Pipelines.BufferSegmentStack.SegmentAsValueType\[\]|250|38,000|152|
| - System.String|504|35,570|70.58|
| - Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection|125|31,000|248|
| - System.Object|1,125|27,000|24|

**Comment by kshyju** [comment]
@davidfowl 

I am going through the PRs in [Continuous Improvement project](https://github.com/dotnet/aspnetcore/projects/17#card-57552352) as an optimization learning exercise.


>Here's the allocation profile after ~10K requests

Could you please share what tooling was used to generate the above data ? Thank You!

**Comment by davidfowl** [comment]
> Could you please share what tooling was used to generate the above data ? Thank You!

Visual Studio 2019's new allocation profiler https://docs.microsoft.com/en-us/visualstudio/profiling/dotnet-alloc-tool?view=vs-2019. You can copy as markdown 😄
