### ISSUE TITLE
Guidance on SAST scanning of .razor files

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#30399]
It looks like leading security scanning tools like Fortify and Sonarqube (which does limited SAST scanning now) cannot yet parse .razor files. Please advise on what tools currently provide SAST scanning support for .razor files...Our IT department is using the lack of available scanning tools to argue against Blazor development. Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up with us. 
@danroth27 can you handle this please? Thanks!

**Comment by blowdart** [comment]
We're currently unaware of any tools that can currently perform static analysts on razor files, or indeed web assembly files.

Obviously you're at the hands of your tool makers I'm afraid.
