### ISSUE TITLE
PROXY protocol support redux

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/aspnetcore#30407]
### Is your feature request related to a problem? Please describe.

Got here due to a design fault in Azure Application Layer Gateway

Originating bug: `Forwarded:` header not implemented or malformed in Application Layer Gateway

### Describe the solution you'd like

Plausible solution: tear down and replace application layer gateway w/ a SNI decoder; use PROXY protocol to pass the originating IP to the kestrel endpoint. All other considered solutions are completely unreasonable except trying to get the problem in application layer gateway fixed.

Since this is the second use case from essentially the same starting point (need something to pass through a reverse proxy server that just can't be, first was #10645), it should be considered for implementation.

### Additional context
We cannot tear down the encryption at the proxy; we'd fail the government's Meaningful Use certification.

**Comment by davidfowl** [comment]
There's code here you can use https://github.com/aspnet/AspLabs/tree/master/src/ProxyProtocol. We have no plans to ship this as a supported part of the product though.

**Comment by jhudsoncedaron** [comment]
Hey that's interesting. Looking at it.
