### ISSUE TITLE
OnDisconnect not being called on tab close - SignalR

### ISSUE THREAD

**Issue by TonyBeCoding** [dotnet/aspnetcore#30402]
AspNet.SignalR 2.4.1
AspNet.SignalR.Core 2.4.1

Issue Occurring in:
Chrome Version 88.0.4324.182 (Official Build) (64-bit)
Firefox 84.0.2 (64-bit)

Workflow:
I log in to my web-application, on the main screen I connect to my hub, get my connection Id and all
the usual things; I leave the tab running.
If I then log into my application again as a different user (new tab or window) it creates a new 
sessionId and new connectionId as expected.

The problem arises when I close the tab for the 1st instance of my application, the ondisconnect is 
not called. This issue doesn't occur if I close a tab associated with the latest instance of my 
application.

If I manually call OnDisconnect on the server side for the first instance of the application, 
context is null. If I manually call OnDisconnect on the client side, it doesn't get called on the 
server-side. Again, only for the first instance of my web-application 

Adding either one of the following on window.onbeforeunload didn't help:
$.connection.hubName.connection.stop();
$.connection.hub.stop();

**Comment by BrennanConroy** [comment]
You already opened this issue on the signalr/signalr repo where it belongs.
