### ISSUE TITLE
DotNet Core 3.1 Web App Event Viewer System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by genifycom** [dotnet/aspnetcore#30410]
We are starting to see more of these in DotNet Core 3.1 running on Windows Server 2019. They show up in Event Viewer.

Do we have to include Microsoft.AspNetCore.Diagnostics.Abstractions in a production release?

Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
ConnectionId: 0HM6NEM9GFLAH
RequestId: 0HM6NEM9GFLAH:00000001
RequestPath: /
SpanId: |d8c6cc9b-4501fabcf0140f78.
TraceId: d8c6cc9b-4501fabcf0140f78
ParentId: 

Connection id "0HM6NEM9GFLAH", Request id "0HM6NEM9GFLAH:00000001": An unhandled exception was thrown by the application.

Exception: 
System.IO.FileNotFoundException: 
File name: 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by BrennanConroy** [comment]
Can you share your project as a github repo please? Or at a bare minimum share your csproj and how you're building and deploying the app.

**Comment by genifycom** [comment]
Hmmm, this is a fairly big commercial project that has been running in production for at least a year. This problem has only appeared in more recent months.

The build is manual with Visual Studio 2019 16.8.5 using a folder publish which is copied to the target machines and run as a Windows Service.

Are there specific pieces of the csproj that would help you to determine what is going on?

**Comment by BrennanConroy** [comment]
> folder publish

Self-contained or relying on the runtime being on the target machine?

**Comment by BrennanConroy** [comment]
Can you check if Microsoft.AspNetCore.Diagnostics.Abstractions.dll is part of the published output?

**Comment by genifycom** [comment]
In the output release folder I do see Microsoft.AspNetCore.Diagnostics.Abstractions.dll

In csproj I have:

    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <Deterministic>false</Deterministic>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>

    
    <PublishReadyToRun>false</PublishReadyToRun>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

**Comment by BrennanConroy** [comment]
Can you try removing `<PublishSingleFile>true</PublishSingleFile>` and seeing if the problem persists?

You say that the problem has only recently started happening, what has changed on either your prod machine or build machines?
