### ISSUE TITLE
Please add a straightforward  way to add additional authorized URLs to AuthorizationMessageHandler after WebAssembly app is started

### ISSUE THREAD

**Issue by KanaHayama** [dotnet/aspnetcore#30428]
### Is your feature request related to a problem? Please describe.

I want to add additional authorized urls loaded from a web api call after the app is started.
There is no straightforward way to add after `AuthorizationMessageHandler` is configured during service registration.

My current approach is saving urls somewhere and loading them in the constructor of my custom `AuthorizationMessageHandler`.
This works but requires me pay extra attention to the order of events in various places, especially at a condition that breakpoints in `OnInitialized` is hard to be captured by debugger.

### Describe the solution you'd like

Shall we have something like 
```
IXXXHttpClientFactory
    .ConfigureHttpMessageHandler<AuthorizationMessageHandler>(h =>  
        h.AddAuthorizedUrls(urlFromCascadingParameter))
    .CreateClient("named");
``` 
or 
```
IHttpClientFactory
    .CreateClient("named")
    .HttpMessageHandlers
    .OfType<AuthorizationMessageHandler>()
    .Single()
    .AddAuthorizedUrls(urlFromCascadingParameter);
``` 
that can make every thing happen in one place?

### Additional context
[Redirected from this issue](https://github.com/dotnet/AspNetCore.Docs/issues/21617)
@guardrex

**Comment by javiercn** [comment]
@KanaHayama thanks for contacting us.

This is not a feature request we want to support. Loading the URLs from an API is not something we've received any other request for and is something we don't consider a good security practice.

If you insist in doing so, our recommendation is that you implement your own message handler to do so, but we strongly recommend having a static list of hardcoded urls since that makes it much harder to attach a token to an unwanted destination.

**Comment by KanaHayama** [comment]
Thank you @javiercn.

I hardcoded one trusted server url and pull more server urls from that server. Since I already implemented what I want, it's ok that it will not be supported.

But a general problem I come up with is that I cannot find a way to get the instances of HttpMessageHandlers attached to a HttpClient after the app is started. Is this restriction also based on a security concern?

**Comment by javiercn** [comment]
@KanaHayama no, it's based on how HttpClient works. You can't generally inspect the handlers AFAIK.

You can create your own options type and you can inject that into the handler, that would enable you to configure whatever you want in your custom handler without having access to the instance directly by just updating the options type you injected.

**Comment by KanaHayama** [comment]
Thank you, that is my current approach. Seems I got it right.
