### ISSUE TITLE
Routing with multiple levels and parameters not working properly

### ISSUE THREAD

**Issue by jonathanperis** [dotnet/aspnetcore#30420]
### Describe the bug
I have a Blazor WASM application that uses multiple levels on routing like "/products/edit/{id}" and when i try to load my edit page from my list page "/products/list" and back from it, the application routing crashes. I have the same behavior working properly with a "/products/new" that don't have any parameters, and when i try to back from this "new" page, all works correctly. I don't have the idea but when i try to navigate to a page that have a parameter and then back to the previous one that dont have, this unexpected behavior from the routing happens.

### To Reproduce
- Clone the repo on https://github.com/jonathanperis/cpnucleo-blazor/ 
- When application runs, go to "Gerenciar" -> "Relação de Sistemas" ("Relação de Sistemas" is my list page so is the page that don't have any parameters on it)
- Click on "Alterar" on any item from the table
- Click on "Voltar" on the edit page

Doing this steps above, the result will be a routing problem on trying to load the list page again, because it recognizes my folder as a part of the base route.

You can try to reproduce the steps on the live version hosted on azure https://cpnucleo-blazor.azurewebsites.net/ (the same error will happen on azure version or on localhost)

### Further technical details
- .NET version: 5.0.103
- `dotnet --info`:

SDK do .NET (refletindo qualquer global.json):
 Version:   5.0.103
 Commit:    9effbc8ad5

Ambiente de runtime:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  3.1.406 [/usr/share/dotnet/sdk]
  5.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE: VS Code on version 1.53.2

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
