### ISSUE TITLE
ComponentTagHelper Parameters are not checked compile time and no code completion

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#30429]
If I use the ComponentTagHelper to insert a server-rendered blazor component, the editor / compiler does not check whether the parameter "NonExistingParameter" exists on the type "MyComponent". No warning, no compile error, no squigly lines in the editor. Also, code completion is not working.

`<component type="typeof(MyComponent)" render-mode="Static" param-NonExistingParameter="@Something" />`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not supported by Tag Helpers in general and we don't plan to add support for it.
