### ISSUE TITLE
Add support for other OpenApi codegeneratos

### ISSUE THREAD

**Issue by kant2002** [dotnet/aspnetcore#30432]
I'm using autorest for generation of OpenAPI clients. So far it works well with success. I would like to be able use same codegenerator together with OpenApiReferences, and right now there no way how it can be done.

I would like that OpenApi generation was somewhat open, and you can switch codegenerators based on your own need, even if this is require to put some work into it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kant2002.
I believe there is a way to do this even today. Maybe not very smooth, but possible.
@dougbu can you suggest how this can be done? Thanks!

**Comment by dougbu** [comment]
> can you suggest how this can be done?

The steps are intended to be simple and use `%(OpenApiReference.CodeGenerator)` metadata as the main extension point. The main issue tends to be ordering things correctly such that defaults you want to override are actually overridden.

The basic requirements are the code generator, a reference to the Microsoft.Extensions.ApiDescription.Client package. and available MSBuild targets matching `Generate%(CodeGenerator)` for however many `%(CodeGenerator)` values you wish. See https://github.com/RicoSuter/NSwag/tree/master/src/NSwag.ApiDescription.Client for one way to do it. Note a separate package is not required though it does simplify ordering. (Infrastructure could for example be split between Directory.Build.* files and your *.csproj file to achieve ordering you prefer.)

See https://github.com/dotnet/aspnetcore/blob/e51b58e3dde10f7aaee169a89e0d15dbaa069c93/src/Tools/Extensions.ApiDescription.Client/src/build/Microsoft.Extensions.ApiDescription.Client.props#L64-L92 for the metadata passed to your CSharp or TypeScript generator. Comments about supported languages sound restrictive but note the `%(OutputPath)` caveat. (Haven't tried it recently but any project type with `$(DefaultLanguageSourceExtension)` set might **Just Work:tm:** as long as you have the right generator.)

Feel free to ask further questions if you run into problems&hellip;

**Comment by kant2002** [comment]
@dougbu My understanding that if I create target similar to

https://github.com/RicoSuter/NSwag/blob/856c75662cb1954d4191ea37b3d14b365bce4561/src/NSwag.ApiDescription.Client/NSwag.ApiDescription.Client.targets#L11

with name for example `GenerateAutoRest`
then if I specify 
```
<OpenApiReference Include="..\api\swagger-v1.json">
      <CodeGenerator>AutoRest</CodeGenerator>
      <Link>OpenAPIs\swagger-v1.json</Link>
    </OpenApiReference>
```

then everything would simply work. Correct?

**Comment by dougbu** [comment]
May hit problems with a code generator name like `AutoRest` because the tasks won't have a good way to determine the output filename. Otherwise, should be fine. Let us know how it goes.

Please close this issue when you have no further questions.

**Comment by kant2002** [comment]
@dougbu thanks. That was enough for me to start poking in the right direction
