### ISSUE TITLE
Known unepxected behavior with Internet Explorer and SignalR?

### ISSUE THREAD

**Issue by avendel** [dotnet/aspnetcore#30435]
Internet Explorer is explicitly mentioned as not supported with SignalR. Smoke testing indicates that basic functionality seems to work, though.

Is the reason you are not supporting IE that you know of things that won't work, or that you don't want to take the cost of testing and dealing with IE quirks in the future?

It seems IE support was dropped from the documentation with a [commit](https://github.com/dotnet/AspNetCore.Docs/commit/c6ad4fbe88a6211a9fa50c02696798398effc823#diff-46981e07c501d40216198dc1bbaa56d8fed881f537e51e19d62134b961eee2f1) related to Blazor, and further clarified in #21263 with [this commit](https://github.com/dotnet/AspNetCore.Docs/commit/3ed8d58f5c285f8750bb1b54a5de08b2feca0f47#diff-46981e07c501d40216198dc1bbaa56d8fed881f537e51e19d62134b961eee2f1).

Is the problem only with Blazor?

_I originally created the issue https://github.com/dotnet/AspNetCore.Docs/issues/21618, but was advised to open it here instead._

**Comment by BrennanConroy** [comment]
> Is the reason you are not supporting IE that you know of things that won't work, or that you don't want to take the cost of testing and dealing with IE quirks in the future?

Both. We make no guarantees that we wont break the library on IE. In fact, with a PR that will be merged soon, IE probably will not work by default out of the box in 6.0.
