### ISSUE TITLE
Get RoleClaimType & NameClaimType available from Iidentity or ClaimsIdentity

### ISSUE THREAD

**Issue by ghostinside** [dotnet/aspnetcore#30441]
`public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            var identity = new ClaimsIdentity();
            try
            {
                var userInfo = await GetUserInfo();
                if (userInfo.IsAuthenticated)
                {
                    identity = new ClaimsIdentity(userInfo.Claims.ToClaims(), "Server authentication", **userInfo.NameClaimType, userInfo.RoleClaimType**);
                }
            }
            catch (HttpRequestException ex)
            {
                Console.WriteLine("Request failed:" + ex.ToString());
            }
            return new AuthenticationState(new ClaimsPrincipal(identity));
        }`

if we set them anyway, would be great to have access to get user roles for example 

now it is a little bit add 

`authenticationState.User.FindAll(**ClaimsIdentity.DefaultRoleClaimType**)`

**Comment by javiercn** [comment]
@ghostinside thanks for contacting us.

We don't have enough information to understand what you are asking for. I'm assuming this request is Blazor related? If it's about Blazor webassembly we provide extensibility for users to augment the set of claims, but having roles available is not an assumption we can make on the client app.

**Comment by ghostinside** [comment]
@javiercn 
yes, it is blazer related, as you can see we put to ClaimsIdentity the keys of the name claim & role claim, so setting them on the server 
 I can add exactly the same keys instantiating the ClaimsIdentity on the client app 
**userInfo.NameClaimType, userInfo.RoleClaimType**

, but if I need them somewhere else I can't get them back "out of the box" from claims identity & need to use something like this 

**ClaimsIdentity.DefaultRoleClaimType**, just make them public

**Comment by javiercn** [comment]
@ghostinside You might be looking for https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#custom-user-factory or a similar article if you are using AAD

**Comment by javiercn** [comment]
> **ClaimsIdentity.DefaultRoleClaimType**, just make them public

@ghostinside not sure what you are referring with this
