### ISSUE TITLE
'RazorSourceGenerator' failed to generate source (NullReferenceException)

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#30442]
```
CSC : error CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'AggregateException' with message 'One or more errors occurred. (Object reference not set to an instance of an object.)' [D:\workspace\_work\1\s\src\Mvc\test\WebSites\BasicWebSite\BasicWebSite.csproj]
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1009323&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=9605d305-57d3-55b8-ba79-e50442d32137&l=2057

This happened building test projects for "Tests: Helix x64" for an aspnetcore-ci build on main. Unfortunately, I don't see a stack trace anywhere that might help track this down.

**Comment by pranavkm** [comment]
@captainsafia putting this on your plate since you're already investigating this space.

**Comment by captainsafia** [comment]
@pranavkm Thanks! Meant to assign this when putting on the labels. I'm planning on tackling this as part of https://github.com/dotnet/sdk/pull/16060
