### ISSUE TITLE
Broken Installer UI Strings in ASP.NET Core Runtime 3.1.12 Hosting Bundle

### ISSUE THREAD

**Issue by nbuuck** [dotnet/aspnetcore#30443]
Running on Windows Server 2019 Standard (CLI only).

<img width="995" alt="Screen Shot 2021-02-15 at 08 14 17" src="https://user-images.githubusercontent.com/3183127/107951633-a4f81080-6f66-11eb-8783-98e336547d28.png">

**Comment by javiercn** [comment]
@nbuuck thanks for contacting us.

@dotnet/aspnet-build do you know how to route this issue?

**Comment by Pilchie** [comment]
@wtgodbe fixed this for the next servicing release.

**Comment by wtgodbe** [comment]
Fixed a few releases ago
