### ISSUE TITLE
Custom validation class in blazor is not working as expected.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#30459]
First of all, [Custom validation class attributes](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#custom-validation-class-attributes) documentation is quite ambiguous and lack of clear instructions. It is not even stated that where to put the following code:

```C#
var editContext = new EditContext(model);
editContext.SetFieldCssClassProvider(new MyFieldClassProvider());
```

I have assumed that the above code has to be put inside at the beginning of `HandleValidSubmit` method. If I do so then it does not work on Model validation by validation attributes (data annotations) as model validation is done even before hitting the `HandleValidSubmit` method.

Secondly, If I am to do so then it means there is no global option to configure this. Rather I have to call the above code in every form submit which is even not working as expected?

Please confirm whether I have configured the **Custom validation class attributes (as described above)** correctly or it is a bug.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and bringing up this concern.

The code you're referring to should be placed in the component initializer. Also, you have to wire up the `EditContext` instance that you've created with the form by passing it as a parameter.

@guardrex do you want to address the first part of it in docs somehow?

**Comment by TanvirArjel** [comment]
@mkArtakMSFT Still there is a major issue. I do as follows:

```C#
<EditForm EditContext="@editContext" OnSubmit="@HandleSubmit">

    <button type="submit">Submit</button>
</EditForm>

@code {
    private Starship starship = new Starship() { ProductionDate = DateTime.UtcNow };
    private EditContext editContext;

    protected override void OnInitialized()
    {
        editContext = new EditContext(SetUserPasswordModel);
        editContext.SetFieldCssClassProvider(new FormFieldClassProvider());
    }

    private async Task HandleSubmit()
    {
      .....
    }
}
````

Where `FormFieldClassProvider` is as follows:

```C#
   public class FormFieldClassProvider : FieldCssClassProvider
    {
        public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
        {
            bool isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

            return isValid ? "is-valid" : "is-invalid"; // Bootstrap validation class
        }
    }
```

Then the form initially renders as follows:

![Capture](https://user-images.githubusercontent.com/14342773/109191635-8f81b280-77c0-11eb-90f4-9ec61fcdb783.PNG)

**Although the form inputs have not been touched yet. This is because you are setting `is-valid` class even before the form is touched which should not be. So currently setting a custom validation class of any CSS library would not work with this. I hope you understood it. Validation state class should only be set if the input field is touched.**

**Comment by guardrex** [comment]
@mkArtakMSFT ... The PR is up at https://github.com/dotnet/AspNetCore.Docs/pull/21634.

I put a piece in there at the end that mentions conditionally checking a subset of fields.

I'll touch it again later when I reach the topic on my UE pass later. For example, a fully working cut-'n-paste example might be best, and I might work that up later. Let's see if what's on the PR is good enough for now.

**Comment by mkArtakMSFT** [comment]
@TanvirArjel for the `there is another major issue` part, can you please file a separate issue so we keep this issue clean ?Thanks!

**Comment by TanvirArjel** [comment]
@mkArtakMSFT Surely! I shall do. We ❤️ Blazor a lot. It's a mind-blowing framework. We want to see it as fully stable as Angular. Thanks to all you guys behind this framework.

**Comment by TanvirArjel** [comment]
This is issue being closed in favour of https://github.com/dotnet/aspnetcore/issues/30496
