### ISSUE TITLE
Make @onauxclick event accessible for Blazor server apps

### ISSUE THREAD

**Issue by ANM86** [dotnet/aspnetcore#30452]
### Is your feature request related to a problem? Please describe.
I'm missing auxclick event. When navigating through the app it might be necessary sometimes that the <a> element can be decorated with an href attribute + the onauxclick event. 
e.g.: In Chrome I want to open a new tab in from a link, but I also want to trigger a C# method by the same click. The onclick event isn't triggered when using the middle button of the mouse

### Describe the solution you'd like
In my opinion the behaviour should be quite similar to the @onclick event, which is already implemented

**Comment by javiercn** [comment]
@ANM86 thanks for contacting us.

This is not something that we currently support but its something you'll soon be able to enable in 6.0 preview2 via the custom event feature we are adding.
