### ISSUE TITLE
Dynamic properties not serialized camelCase when using Microsoft Json.NET package

### ISSUE THREAD

**Issue by brgrz** [dotnet/aspnetcore#30454]
### Describe the bug

This is essentially a duplicate of https://github.com/dotnet/aspnetcore/issues/9543

It was locked there but no resolution was provided and solutions/workarounds that used to work with ASP.NET MVC 5 do not work anymore in ASP.NET Core.

The default System.Text.Json serializer [does not support](https://github.com/dotnet/runtime/issues/29690) dynamics at all. We had to revert to using Json.NET via Microsoft's Nuget package Microsoft.AspNetCore.Mvc.NewtonsoftJson (v. 3.1.12) to get support for dynamic serialization.

Then enabled it like this

```
			services
				.AddControllersWithViews()
				.AddNewtonsoftJson(options => options.UseCamelCasing(true));
```

Comments for UseCamelCasing() specifically say 

> Configures the casing behavior of JSON serialization to use camel case for property names, and optionally for dynamic types and dictionary keys.

and

> If true will camel case dictionary keys and properties of dynamic objects.

This does not work though. Properties for dynamic objects within a typed object remain PascalCase when serialized.
I think this warrants a revisit to the issue I linked above and a possible resolution.

### To Reproduce

Here is an example what comes out of a serializer when provided with a dynamic object within a typed object:

```
"records": [
        {
            "shape": null,
            "layout": "",
            "content": {
                "Location": null,
                "Address": null,
                "OpenHours": null,
                "Information": null,
```

### Further technical details
- ASP.NET Core version: 3.1

**Comment by javiercn** [comment]
@brgrz thanks for contacting us.

@JamesNK is there something specific you need to setup to enable this in Newtonsoft.Json?

@brgrz WRT to dynamic support in System.Text.Json I would suggest you file an issue on the [runtime repo](https://github.com/dotnet/runtime) so that they can track the ask.

**Comment by pranavkm** [comment]
@brgrz are you attempting to serialize a `JObject`? If so, according to https://github.com/dotnet/aspnetcore/issues/9543#issuecomment-484806912, Newtonsoft.Json will not transform the casing, so the behavior here is expected.

**Comment by brgrz** [comment]
It is a dynamic backed by a JObject, yes.
