### ISSUE TITLE
Microsoft.AspNetCore.Http.Abstractions package version still at 2.2 

### ISSUE THREAD

**Issue by MCCshreyas** [dotnet/aspnetcore#30450]
So, I was watching this video (https://www.youtube.com/watch?v=l8fYpchrv0c&t=5583s&ab_channel=DevMentors) at TimeStamp 1:35, the instructor is wanted to try the `IApplicationBuilder` interface outside ASP.NET Core project, but as that package lives in `Http.Abstractions`, he found that the package version is still 2.2. 
I even check on [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/) it still at 2.2 and last updated on 12/3/2018. 
So I just wanted to confirm, is that package intentionally kept at 2.2, OR it's going to depreciate, OR is there any other recommended package to use instead of this one!? 

Thanks!

**Comment by BrennanConroy** [comment]
After 2.2 many packages stopped being shipped as packages and are now included in the AspNetCore shared runtime. That package is one of them, so you no longer need a package reference to consume the dll.

**Comment by MCCshreyas** [comment]
But what If I wanted to access `IApplicationbuilder` in my class library, just like in video? I want my middleware to be separated in each module so that I can just call like extension method on `IApplicationbuilder` in `startup.cs`.

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio

**Comment by MCCshreyas** [comment]
![image](https://user-images.githubusercontent.com/17148381/109113465-4f8be280-7762-11eb-9f29-275abca627d7.png)

no .NET 5 support, or just that doc is outdated?

**Comment by BrennanConroy** [comment]
Very likely the docs need updating.

**Comment by MCCshreyas** [comment]
ah, ok. Thanks for the clarification! :)
