### ISSUE TITLE
Unable to remove default Date header - Kestrel

### ISSUE THREAD

**Issue by aslezak** [dotnet/aspnetcore#30466]
### Describe the bug
Kestrel adds the Date header to all responses. I tried removing it with middleware but I can't seem to plug it in to a place where that header exists.
Methods I tried:
```csharp
            // this registration I tried both as first and last middleware in Configure (see project for example)
            app.Use(async (context, next) =>
            {
                // before processing the request, makes sense here there is no Date yet
                context.Response.Headers.Remove(HeaderNames.Date);
                
                // This should theoretically happen as a last call before actually writing to output stream
                context.Response.OnStarting(state =>
                                            {
                                                if (state is HttpContext httpContext)
                                                {
                                                    httpContext.Response.Headers.Remove(HeaderNames.Date);
                                                }
                                                return Task.CompletedTask;
                                            },
                                            context); await next.Invoke();

                // there was a small chance this would work but no luck
                if (!context.Response.HasStarted)
                {
                    context.Response.Headers.Remove(HeaderNames.Date);
                }
            });
```
In case my understanding of the flow is wrong. Where is then the correct time to access Kestrel generated headers?
I know I can stop it from adding `Server=Kestrel` using an option on 
```csharp
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>().ConfigureKestrel(options => options.AddServerHeader = false);
                });
```
But there does not seem to be an option for other default headers.

### To Reproduce
https://github.com/aslezak/header-manipulation-test
- it is a simple templated web api project
- `curl -Ss -kI http://localhost:5000/WeatherForecast` will show the Date header is present despite trying to remove it with middleware

### Further technical details
.NET 5

### Reason
Normally this would not be an issue at all, but I have a requirement to have a service talk to an ancient device that was badly implemented and I need a way to monkey my way around some things like default headers, cases etc. What I am looking for is a code injection point after all the processing is done where I have access ideally to full set of headers, content etc. I am looking for a clean way of doing it not to have to put `nginx` or something similar in front of it to do rewriting.
Thanks

**Comment by Tratcher** [comment]
The HTTP spec is pretty explicit that a Date header is mandatory for responses. You can provide your own, but if you don't then Kestrel will do it for you. You may be be able to provide an empty one?

**Comment by aslezak** [comment]
Yep, that part I do know. Specific issue is that I need to be able to change the case of header that gets sent. I managed to send a double headers, one upper one lower case by using reflection and substituting the `MaybeUnkown` dictionary with the case insensitive one, but the default one still gets sent, and trips up the old device.
I do agree that what I am trying to do goes against the spec, but unfortunately I can't monkey with device itself to make it respect the spec about headers not being case insensitive.

All that being said. I was still surprised that there is no way to have middleware that plugs in after Kestrel puts in the default headers and before the response starts. As per [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse.onstarting?view=aspnetcore-5.0)

> OnStarting(Func<Task>)
> Adds a delegate to be invoked just before response headers will be sent to the client. Callbacks registered here run in reverse order.

From trying to see all the headers that will get sent at that point, there still seems to be enrichment that happens, so statement is not quite true, or that documentation needs update to state `just before default headers are added and response is sent`

**Comment by Tratcher** [comment]
Fair. Kestrel does a final pass after the OnStarting callbacks to ensure protocol correctness. That doc might be better worded as `when preparing to send the headers to the client.`

Kestrel doesn't give any control over the casing for known header names. The date header is even more special since it's always changing but always required. That's controlled here:
https://github.com/dotnet/aspnetcore/blob/b090e91529f05d68f8d0ec01dd668bc32deea599/src/Servers/Kestrel/Core/src/Internal/Http/DateHeaderValueManager.cs#L18

**Comment by aslezak** [comment]
Interesting, that is quite locked down. I guess that ultimately it will be simpler to put something in front of the service to do header rewrites than bull my way to getting Kestrel to output a lower case header for date.
It is strange that this is so hard, on one hand I get it, and spec says that protocol is header case agnostic, but since that means it can go both ways....

**Comment by davidfowl** [comment]
We can add an API to remove it from responses

**Comment by Tratcher** [comment]
> We can not override it if it's set

It's not enough to turn off the Date header here, we still don't allow you to control the casing of known response header names.

**Comment by aslezak** [comment]
Yes, from looking at the code, even if using api to disable the `Date` header like the `Server` header I would still have to do reflection hack to shove a case insensitive date into the `MaybeUnknown` dictionary and sneak it through that way.

**Comment by davidfowl** [comment]
> It's not enough to turn off the Date header here, we still don't allow you to control the casing of known response header names.

If we can find a way to do it without hurting performance sure, otherwise I would call this scenario niche. We've had 2 cases of customers wanting to control the casing.

**Comment by aslezak** [comment]
The way it is done now, there is no way to do it without hurting the performance if one is not allowed to disable the `Date` header.
If that was made possible through api in same way as `Server` header, and the `MaybeUnknown` was directly accessible as well as used Ordinal and not OrdinalIgnoreCase (need to check if this is the case, I am on the phone now and just talking from memory) for comparison then potential performance impact would be marginal at best, from what I can see.

But I will definitely agree that this is extremely niche and probably not worth tampering with very performant code.

**Comment by BrennanConroy** [comment]
Unfortunately we don't think this meets the bar for working on a fix.

> I am looking for a clean way of doing it not to have to put `nginx` or something similar in front of it to do rewriting.

This is probably what you're going to have to do for this niche scenario.

**Comment by aslezak** [comment]
Agreed, thanks for the idea bounce. Always good to get more perspective
