### ISSUE TITLE
`dotnet watch` should now do `dotnet watch run` by default

### ISSUE THREAD

**Issue by JuergenGutsch** [dotnet/aspnetcore#30470]
Hey,

As mentioned in the following blog post, `dotnet watch` should now do `dotnet watch run` by default.
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/

I tried the .NET 6 preview 1 but it doesn't. It just shows the command line help.

Steps to reproduce::
* Run `dotnet --info` to ensure the .NET 6 preview 1 SDK is used
* Create a new project `dotnet new webapp -n WatchDemo -o WatchDemo`
* cd into the project folder
* Run `dotnet watch`

It doesn't run `dotnet watch run`  but shows the command line help 

Do I miss something?

**Comment by pranavkm** [comment]
Thanks for the issue report @JuergenGutsch. We'd recently migrated the watch tool between repositories and missed this change in the process. This change is part of the preview2 builds though which is set to release very soon.

**Comment by JuergenGutsch** [comment]
Hey @pranavkm 
Great thanks. That makes absolute sense.
So it was a small mistake to mention it as a new thing in preview1 in this blog post: 
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/

I stumbled upon this because I want to start a new blog series about the new things in ASP.NET Core on .NET 6
