### ISSUE TITLE
[Discussion] Changed MessagePack library in @microsoft/signalr-protocol-msgpack javascript library

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#30471]
Discussion for https://github.com/aspnet/Announcements/issues/454

## Changed MessagePack library in @microsoft/signalr-protocol-msgpack npm package

@microsoft/signalr-protocol-msgpack used to reference msgpack5 now it references @msgpack/msgpack.

The `MessagePackOptions` that could optionally be passed into the `MessagePackHubProtocol` also has a breaking change. The options `disableTimestampEncoding` and `forceFloat64` no longer exist, and some additional options now exist.

### Version introduced

ASP.NET Core 6.0

### Old behavior

Previously to use the MessagePack hub protocol in the browser you needed to include 3 script references
```
<script src="~/lib/signalr/signalr.js"></script>
<script src="~/lib/msgpack5/msgpack5.js"></script>
<script src="~/lib/signalr/signalr-protocol-msgpack.js"></script>
```

In addition the `msgpack5` package was downloaded to your `node_modules` so you could use it in your app if you wanted.

`MessagePackOptions` had `disableTimestampEncoding` and `forceFloat64` properties, but doesn't anymore.

### New behavior

To use the MessagePack hub protocol in the browser you now only need 2 script references
```
<script src="~/lib/signalr/signalr.js"></script>
<script src="~/lib/signalr/signalr-protocol-msgpack.js"></script>
```

And you will have the `@msgpack/msgpack` package downloaded to your `node_modules` if you want to use the directly in your app.

`MessagePackOptions` has new properties and removed the `disableTimestampEncoding` and `forceFloat64` properties.

### Reason for change

Reduced asset size, reduced complexity to consume the package, and more customizability.

### Recommended action

If you were previously using `msgpack5` in your app, you will need to add a direct reference to the library in your package.json.

### Category

ASP.NET

### Affected APIs

Removed `MessagePackOptions.disableTimestampEncoding`
Removed `MessagePackOptions.forceFloat64`

---
#### Issue metadata

* Issue type: breaking-change

**Comment by John0King** [comment]
May I ask your guys put the client side code in a stand alone github repository ?
AspNetCore repo is a huge git repo ,  and I will hard to the diff.  I'm porting signalR to  [wechat miniProgram](https://developers.weixin.qq.com/miniprogram/dev/api/network/websocket/wx.connectSocket.html) and [uni-app](https://uniapp.dcloud.net.cn/api/request/websocket),

and I'm asking the ability to replace websocket protocol so I don't need to port all the code from this repo,  then I can only port a  https://github.com/John0King/WeChatApp.SignalR/blob/master/signalr/src/WeChatWebSocketTransport.ts

**Comment by BrennanConroy** [comment]
> put the client side code in a stand alone github repository

That's unlikely to happen. You can view the history for specific folders on Github, so you should be able to just monitor https://github.com/dotnet/aspnetcore/commits/main/src/SignalR/clients/ts for changes.
