### ISSUE TITLE
SignalR connection started from Blazor component is cannibalized by main page

### ISSUE THREAD

**Issue by astrowalker** [dotnet/aspnetcore#30485]
### Describe the bug

Let's say I have server with single SignalR hub and two channels/stream which simply broadcast some number every second. And I have a Blazor (webasm) client with plain page and two (!) hub connections, each connects to given channel. This works and what is most important here I can see at server side each hub connection is connected with its own connection id. So from server side I see two connections.

When I change the code on client side and move one connection as component the server side will see only one connection. So one connection id was cannibalized. As effect only one connection will receive messages from the hub.

### To Reproduce

Create Blazor webasm demo, add SignalR. Refer to this gist: https://gist.github.com/astrowalker/d26fc0a7a62eda94bb91d32bb79b20ca

add component to web client and put there client part of the gist. Copy this code again and paste it to the page that uses added component -- this time change "channelA" to "channelB".

Add SignalR hub to the server (server part of the gist). Run the solution (it is better to run it in project mode, not IIS). Navigate to the page you placed signalR connection and observe the server -- instead of two connections it will add one new, and reuse the existing one then.

If you want to compare it to working behaviour -- move code away from component and place it directly within the page at webclient (thus page will have still 2 signalr connections, but would have them directly in the body of the page). Rerun solution, observe server registers two new connections (and as effect all messages are received by the client).

### Exceptions (if any)

None.

### Further technical details
- ASP.NET Core version

Both Core 3.1 and Net 5.0

- Include the output of `dotnet --info`

PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.513 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS 2019 Version 16.8.5

**Comment by javiercn** [comment]
@astrowalker thanks for contacting us.

It's not clear to us what you expect to happen here. When you are running on web assembly the connection is Browser<->Server, when you are running Blazor server the connection is Server<->Server since your code runs on the server.

**Comment by astrowalker** [comment]
@javiercn 

Single page (webasm) with 2 hub connections (each connection uses diffeerent channel) <-> server. I works. Servers sends info, two connections id are used (this is crucial) and the info gets received correctly by both connections. 

Now I split my webasm page into page and component. I will leave one hub connection within page and move the other hub connection to component. This should work, right? But it does not. Component opens its connection, first connection id shows up, then creation of the page kicks in, page makes its own connection REUSING the same connection id. As the effect component hub connection is cut off from receiving any messages.

**Comment by BrennanConroy** [comment]
Can you share a buildable and runnable github repo that shows the problem?

**Comment by astrowalker** [comment]
@BrennanConroy  https://github.com/astrowalker/blazor-signalr

For quicker results, switch run mode from IIS to project one. Launch solution. In browser enter dev mode (usually F12), switch to console. Observe that in server console window you constantly have "no clients" message (OK).

Switch tab in browser to "Fetch data", Observe in server console message "New hub connection" (good) and "Connected with same connection" (bad), at the same time in browser console you will see "Signalr comp connected" and "Signalr page connected" (both good indicators). 

And then observe server sends the messages, but only half is received (by page, all those expected by component are lost).

If you move entire code from component to page there will be two connections id in use and all messages will be received.

**Comment by BrennanConroy** [comment]
Don't add your hub to DI, especially not as a singleton https://github.com/astrowalker/blazor-signalr/blob/92c4a0ed74e77509702baaf129cd2e87a9fa4f37/MultiSignalBlazorApp50/Server/Startup.cs#L30

If you want to store state in the hub class, it needs to be in static properties (and make sure you think about thread safety)

Don't access properties of the hub class from inside a background task (your timer). If you want to send to clients like that, you need to use the `IHubContext<THub>` https://docs.microsoft.com/aspnet/core/signalr/hubcontext?view=aspnetcore-5.0
