### ISSUE TITLE
PubSub (SignalR team task): Support for configuring connect timeouts

### ISSUE THREAD

**Issue by BhavanaMSFT** [dotnet/aspnetcore#30495]
Right now the SignalR C++ client times out at 5 seconds if SignalR websocket negotiation+websocket upgrade doesn't complete by then. The ask is to ensure the SignalR C++ client allows this timeout value to be configurable.

**Comment by BrennanConroy** [comment]
We have a timeout for the handshake now, and removed the 5 second negotiate timeout. The http client has a timeout for the http request which is used for a timeout now.

Closing as I believe we are ok with just the handshake configuration for now.
