### ISSUE TITLE
Custom validation class in Blazor is not working as expected to apply CSS library validation styles.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#30496]
To apply the Bootstrap validation styles in Blazor If we extend the **FieldCssClassProvider** as follows:

```C#
public class BootstrapValidationClassProvider : FieldCssClassProvider
{
    public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
    {
        bool isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

        return isValid ? "is-valid" : "is-invalid"; // Bootstrap validation class
    }
}
```
and use as follows:

```C#
<EditForm EditContext="@editContext" OnSubmit="@HandleSubmit">

    <button type="submit">Submit</button>
</EditForm>

@code {
    private SetUserPasswordModel SetUserPasswordModel = new SetUserPasswordModel();
    private EditContext editContext;

    protected override void OnInitialized()
    {
        editContext = new EditContext(SetUserPasswordModel);
        editContext.SetFieldCssClassProvider(new BootstrapValidationClassProvider());
    }

    private async Task HandleSubmit()
    {
      .....
    }
}
```
Then the form initially renders as follows:
![InkedCapture_LI](https://user-images.githubusercontent.com/14342773/109332207-fc13b480-7887-11eb-9530-3ccf845aa457.jpg)

**Although the form inputs have not been touched yet, the validation has been applied this is because FieldCssClassProvider is setting `is-valid` class even before the form is touched which should not be. So currently setting a custom validation class of any CSS library would not work with this. I hope you understood. Validation state class should only be set if the input field is touched and actual validation is done.**

To overcome this If do as follows:

```C#
public class BootstrapValidationClassProvider : FieldCssClassProvider
{
    public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
    {
        if (editContext == null)
        {
            throw new ArgumentNullException(nameof(editContext));
        }

        if (!editContext.IsModified())
        {
            return string.Empty;
        }

        bool isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

        return isValid ? "is-valid" : "is-invalid";
    }
}
```

Then "is-valid" and "is-invalid" classes are not applied on the form submit because on form submit without touching the input fields editContext.IsModified() returns false. If editContext.IsModified() would have returned true on form submit and marked all fields as modified then It would have worked as expected.

**I have also found that there is no way to mark editContext as modified on the form submit. Angular and React have this option to mark the form and its inputs as modified on form submit manually.**

## Possible Solution:
1.  Trigger the `FieldCssClassProvider` only if the input field is touched or the form is submitted.
2.  Mark the `editContext` and all the inputs as modified if the form is submitted or add an option to mark `editContext` and all the inputs as modified on the form submit like Angular and React. **_Surprisingly, there is a `EditContext.MarkAsUnmodified()` method but no `EditContext.MarkAsModified()` method. How was that possible?_**.  Adding `EditContext.MarkAsModified()` methods would solve the issue.

**Comment by guardrex** [comment]
:eyes:

**Comment by VahidN** [comment]
You can use the `IsModified` method on an input filed too:
```C#
var isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();
if (editContext.IsModified(fieldIdentifier))
{
    return isValid ? "is-valid" : "is-invalid";
}
return isValid ? "" : "is-invalid";

```

**Comment by TanvirArjel** [comment]
@VahidN Your solution does not work because whenever the form is submitted without touching any input field it does not apply the validation classes as currently on form submit input fields in the edit context are not marked as modified.

**Comment by VahidN** [comment]
@TanvirArjel  
It works for me `OnValidSubmit` :
![editform](https://user-images.githubusercontent.com/766010/124375980-0290bd80-dcba-11eb-9763-03545e85c760.png)

Do you know why? Because the validation system doesn't care if you have `touched` anything or not. It cares about the defined validation rules such as [Required] and if it failed, it will mark the `untouched` field [as an invalid one](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Components/Forms/src/EditContextDataAnnotationsExtensions.cs#L78). That's enough to show the validation messages and [applying the related CSS classes](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Components/Web/src/Forms/InputBase.cs#L236).

**Comment by TanvirArjel** [comment]
@VahidN Please share your `OnValidSubmit` method code.

**Comment by TanvirArjel** [comment]
@VahidN Got your point. The following does not work:

```C#
public class BootstrapValidationClassProvider : FieldCssClassProvider
{
    public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
    {
        if (editContext == null)
        {
            throw new ArgumentNullException(nameof(editContext));
        }

        if (!editContext.IsModified())
        {
            return string.Empty;
        }

        bool isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

        if (editContext.IsModified(fieldIdentifier))
        {
            return isValid ? "is-valid" : "is-invalid";
        }

        return isValid ? string.Empty : "is-invalid";
    }
}
```
Because `editContext.IsModified()` is not being marked as modified on submit. If I remove this then it works as follows:

```C#
public class BootstrapValidationClassProvider : FieldCssClassProvider
{
    public override string GetFieldCssClass(EditContext editContext, in FieldIdentifier fieldIdentifier)
    {
        if (editContext == null)
        {
            throw new ArgumentNullException(nameof(editContext));
        }

        bool isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();

        if (editContext.IsModified(fieldIdentifier))
        {
            return isValid ? "is-valid" : "is-invalid";
        }

        return isValid ? string.Empty : "is-invalid";
    }
}
```

However, Thank you for your comment.

**Comment by TanvirArjel** [comment]
I am closing this as a workaround is working as expected. But for `EditContext.MarkAsModified()` I am going to open a new issue.
