### ISSUE TITLE
Set expiration for the data protection key stored in Redis

### ISSUE THREAD

**Issue by victorm1710** [dotnet/aspnetcore#30491]
### Is your feature request related to a problem? Please describe.
I develop an asp.net web application which configures data protection key Redis storage by calling StackExchangeRedisDataProtectionBuilderExtensions.PersistKeysToStackExchangeRedis (to support a webfarm configuration). Since data protection keys are stored in Redis, as soon as the web application is deleted, the application's data protection keys stored in Redis become obsolete (Redis instance is NOT deleted together with the application, because it's shared with some other applications). It will be good if those keys were deleted automatically after the application is deleted. However currently there is a data protection key, which is stored in Redis, which doesn't have expiration (ttl) set - see this code: https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/DataProtection/StackExchangeRedis/src/RedisXmlRepository.cs#L56
It will be good of this key also have expiration (ttl) set, which would ensure that the key is automatically deleted from Redis, when the appilcation is deleted.

### Describe the solution you'd like
Implement sliding expiration for the key mentioned in the problem description: as soon as there is no user activity which interacts with data protection on asp.net application for a certain period of time, the mentioned Redis key is automatically removed from Redis (due to Redis key ttl expiration).

**Comment by blowdart** [comment]
That's not how data protection was designed, nor will it be changed to do so. No keys are ever deleted in case there is persisted data that still needs to be read (expired keys simply aren't used to protect new items). The potential for data loss is not something we're willing to risk in implementing a deletion mechanism in any data stpre.
