### ISSUE TITLE
[Razor] Error during build

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#30492]
Ran into this while running our build, likely something to account for.

CSC : error CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'IOException' with message 'The process cannot access the file 'C:\work\AspNetCore\artifacts\obj\HostedBlazorWebassemblyApp.Client\Debug\net6.0\RazorTagHelper.refs.out.cache' because it is being used by another process.' [C:\work\AspNetCore\src\Components\WebAssembly\Samples\HostedBlazorWebassemblyApp\Client\HostedBlazorWebassemblyApp.Client.csproj]

@captainsafia @pranavkm

**Comment by captainsafia** [comment]
@javiercn Try updating to a more recent preview2 build. We moved from using a file-based cache in favor of an in-memory one. The exception you're seeing is from the implementation that used a file-based cache.

**Comment by javiercn** [comment]
@captainsafia It might be that I was using the bits from release/6.0-preview2.

Thanks!

**Comment by pranavkm** [comment]
@captainsafia could you update the SDK used in this repo? We're probably using a build that does not have your changes.
