### ISSUE TITLE
Tracking Exception when using Identity's SetAuthenticationTokenAsync

### ISSUE THREAD

**Issue by FionaHolder** [dotnet/aspnetcore#30498]
When using ASP.NET Core Identity with an Entity Framework Store, the UserManager.SetAuthenticationTokenAsync always throws an exception, The instance of entity type 'SilverUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked.

**Startup.cs**
```
services.AddIdentity<SilverUser, SilverRole>(options => new IdentityOptions()
{
        User = new UserOptions() {RequireUniqueEmail = true}, // Emails should be unique
	SignIn = new SignInOptions() {RequireConfirmedEmail = true}
}) 
.AddEntityFrameworkStores<SilverDbContext>();
```

**In API Controller**
```
var token = await UserManager.GenerateUserTokenAsync(userCheck.user, API_TOKEN_PROVIDER, API_TOKEN_NAME);
await UserManager.SetAuthenticationTokenAsync(userCheck.user, API_TOKEN_PROVIDER, API_TOKEN_NAME, token);
```

**Full Stack Trace**

> 2021-02-23 17:24:48.660 +00:00 [Error] Web.Areas.Api.Filters.SilverApiExceptionFilterAttribute: Error occurred in API method /api/v1/user/loginSystem.InvalidOperationException: The instance of entity type 'SilverUser' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)at Microsoft.EntityFrameworkCore.DbContext.Attach[TEntity](TEntity entity)at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.UpdateAsync(TUser user, CancellationToken cancellationToken)at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)at Microsoft.AspNetCore.Identity.UserManager`1.SetAuthenticationTokenAsync(TUser user, String loginProvider, String tokenName, String tokenValue)at Web.Areas.Api.Controllers.UserController.Login() in D:\Projects\CGI\MentalHealthFirstAider\Web\Areas\Api\Controllers\UserController.cs:line 216at lambda_method(Closure , Object )at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### The Issue

Within the SetAuthenticationTokenAsync method of the UserManager, there is the following method (this is not my code, it is the standard implementation)

```
        /// <summary>
        /// Called to update the user after validating and updating the normalized email/user name.
        /// </summary>
        /// <param name="user">The user.</param>
        /// <returns>Whether the operation was successful.</returns>
        protected virtual async Task<IdentityResult> UpdateUserAsync(TUser user)
        {
            var result = await ValidateUserAsync(user);
            if (!result.Succeeded)
            {
                return result;
            }
            await UpdateNormalizedUserNameAsync(user);
            await UpdateNormalizedEmailAsync(user);
            return await Store.UpdateAsync(user, CancellationToken);
        }
```

The `ValidateUserAsync` call is causing the user to be tracked within Entity Framework, so that when `Store.UpdateAsync` is called, it throws the above exception every time. 

If I create my own UserManager, override SetAuthenticationTokenAsync I have to reset the change tracking following the validate user call to make the Store.UpdateAsync method call succeed. 

### Include provider and version information

EF Core version:  Microsoft.AspNetCore.Identity.EntityFrameworkCore v3.1.12
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 3.1
Operating system: Azure App Service (Windows)

**Comment by HaoK** [comment]
@FionaHolder can you include the surrounding code, how did you get the user, was this user already in the database or is this a new entity?
