### ISSUE TITLE
Debugging Blazor app with WSL raises CoreCLR error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30508]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Debugging-Blazor-app-with-WSL-raises-Cor/1337167)._

---
[severity:It bothers me. A fix would be nice]
I’m trying to debug the standard Blazor WASM template project with WSL and I get a “target process exited without raising a CoreCLR started event” error message and a suggestion to set the project to use net core. The project is using NET 5 and the IIS server can debug the app properly, I have tried falling back to NET Core 3 but the project lost the option for a WSL debug.

---
#### Feedback Bot on 2/13/2021, 04:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is currently not supported. We're working closely with relevant internal teams to enable this but nothing planned as of this moment.
