### ISSUE TITLE
[Routing] [Feature Request/Question] Mapping a Fallback for non-filename routes

### ISSUE THREAD

**Issue by cobbr** [dotnet/aspnetcore#30505]
### Is your feature request related to a problem? Please describe.

Hi, I am trying to find a way to use routing to map a fallback for _file names_. Perhaps this is already possible, but I have not found a way to do it. It seems that all of the `MapFallback*` options explicitly exclude file names (paths that end with a file extension (i.e. .exe, .txt, etc.)).

Here's an example of what my code looks like currently:

```
public void Configure(IApplicationBuilder app)
{
    app.UseRouting();
    app.UseEndpoints(endpoints =>
    {
        foreach (string route in this.routes)
        {
            endpoints.MapControllerRoute(route, route, new { controller = "Controller1", action = "Route" });
        }
        endpoints.MapFallbackToController("Fallback", "Controller1");
    });

    app.UseStaticFiles(new StaticFileOptions
    {
        FileProvider = new PhysicalFileProvider(this.StaticDir),
        RequestPath = "",
        ContentTypeProvider = new FileExtensionContentTypeProvider(Common.ContentTypeMappings),
        ServeUnknownFileTypes = true,
        DefaultContentType = Common.DefaultContentTypeMapping,
        OnPrepareResponse = ctx => this._logContext(ctx.Context)
    });
}
```

### Describe the solution you'd like

I've found that `MapFallbackToController` has worked great for capturing requests that do not have a file extension. `UseStaticFiles` has worked great for capturing requests with a file extension that actually exist. But I'd also like to capture requests with a file extension that **do not exist**.

For this purpose, I'd definitely be willing to abandon `UseStaticFiles` and implement everything I want myself in my "Fallback" route. But currently, even if I try this, any requests with a file extension are not captured by the `MapFallbackToController`.

Is there any way to accomplish this currently that I am missing? If not, would it be possible to add a Fallback method that can capture requests with file names?

**Comment by javiercn** [comment]
@cobbr thanks for contacting us.

I believe there is an overload that allows you to pass in the template, and you can use whatever path template you want there.

**Comment by cobbr** [comment]
@javiercn Thanks for the response. Is there any chance I could see an example of how to do this or a reference to the correct overload? The documentation seem pretty clear that it "will match requests for non-file-names" only.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.controllerendpointroutebuilderextensions.mapfallbacktocontroller?view=aspnetcore-5.0#Microsoft_AspNetCore_Builder_ControllerEndpointRouteBuilderExtensions_MapFallbackToController_Microsoft_AspNetCore_Routing_IEndpointRouteBuilder_System_String_System_String_

**Comment by cobbr** [comment]
Bump @javiercn . Any chance there is an example available for the overload that you mentioned?
