### ISSUE TITLE
rzc discover exited with code -2147450730. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30506]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/rzc-discover-exited-with-code--214745073/1344897)._

---
[severity:It's more difficult to complete my work]
Hi please help me,i am write a code but im wait 3 or 4 months but i open my project and i show this eror on rebuild.
i am add photos for that.
that error line this
 
```
<RazorTagHelper
		  Debug="$(_RazorDebugTagHelperTask)"
		  DebugTool="$(_RazorDebugTagHelperTool)"
		  ToolAssembly="$(_RazorToolAssembly)"
		  UseServer="$(UseRazorBuildServer)"
		  ForceServer="$(_RazorForceBuildServer)"
		  PipeName="$(_RazorBuildServerPipeName)"
		  Version="$(RazorLangVersion)"
		  Configuration="@(ResolvedRazorConfiguration)"
		  Extensions="@(ResolvedRazorExtension)"
		  Assemblies="@(RazorReferencePath)"
		  ProjectRoot="$(MSBuildProjectDirectory)"
		  TagHelperManifest="$(_RazorTagHelperOutputCache)">
		  <Output
			TaskParameter="TagHelperManifest"
			ItemName="FileWrites"/>
	  </RazorTagHelper>
```
but i am delete all razor tag helper and return rebuild for test but error on the this line everytime i tested.:(

```
<RazorGenerate
      Debug="$(_RazorDebugGenerateCodeTask)"
      DebugTool="$(_RazorDebugGenerateCodeTool)"
      ToolAssembly="$(_RazorToolAssembly)"
      UseServer="$(UseRazorBuildServer)"
      ForceServer="$(_RazorForceBuildServer)"
      PipeName="$(_RazorBuildServerPipeName)"
      Version="$(RazorLangVersion)"
      Configuration="@(ResolvedRazorConfiguration)"
      Extensions="@(ResolvedRazorExtension)"
      Sources="@(RazorGenerateWithTargetPath)"
      ProjectRoot="$(MSBuildProjectDirectory)"
      TagHelperManifest="$(_RazorTagHelperOutputCache)" />
```

Error that `rzc discover exited with code -2147450730. myprojectName`

Describe the bug
i think thats error is rare i dont see this on every time...

Further technical details

```
ASP.NET Core version 5.0 and others i install but project core 3
my dotnet --info
 .NET SDK (varsa global.json dosyasını yansıtır):
 Version:   5.0.103
 Commit:    72dec52dbd

Çalışma Zamanı Ortamı:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```

---
#### Feedback Bot on 2/21/2021, 07:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Looking at the snippet that you pasted in, it looks like the project might be a 2.x targeting project. If so, 2.x projects relied on the dotnet in the PATH to have the right runtime installed. In this case, it's possible that you have the runtime installed under the `Program Files (x86)` directory, but the 64-bit dotnet is being run. Consider grabbing the 64-bit dotnet (or perhaps uninstalling the 32-bit SDK) to see if it helps.
