### ISSUE TITLE
Blazor WASM input time fails to show values after upgrade to .NET 5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30507]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-WASM-input-time-fails-to-show-val/1343787)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:3.1]
I have a Blazor WASM project that I just have upgraded to .NET 5. After upgrade my input time:

```


@code{
    DateTime myTime = DateTime.Now.ToLocalTime();
    string myTimeFormat = "HH:mm:ss"; 
}
```

only shows 
"--:--" instead of the time on the format "HH:mm:ss" that it used to do.

Chrome (and Edge) console prints.
>blazor.webassembly.js:1 The specified value "12.52.58" does not conform to the required format. The format is "HH:mm", "HH:mm:ss" or "HH:mm:ss.SSS" where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.

I posted this as question on [SO](https://stackoverflow.com/questions/66277278/blazor-wasm-net-5-input-time-do-not-show-correctly)

---
#### Feedback Bot on 2/19/2021, 07:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by erikthysell** [comment]
Somehow it is missing the input tag : <input type="time" @bind="myTime" @bind:format=@myTimeFormat />

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What are the culture / region settings for your browser and your OS?

**Comment by erikthysell** [comment]
Hi Thanks for asking.. I use Danish /DK settings.

**Comment by erikthysell** [comment]
Very simple code to generate the problem:
Basically the `ToString` method seems to be failing in wasm:

```
string _RFC3339Format = "yyyy-MM-dd'T'HH:mm:ssK";
DateTime myTime = DateTime.Now;
Console.WriteLine(myTime.ToString(_RFC3339Format));
```

outputs this:

> 2021-03-12T11.36.40+01:00

All 3 browsers.
(Chrome  Version 88.0.4324.190 (Officiel version) (64-bit))
(Edge Version 89.0.774.48 (Officielt build) (64-bit))
(Firefox Version 86.0.1 (64-bit))

Danish settings should give timeformat hh:MM:ss - at least it says so in my windows settings.

**Comment by Andrzej-W** [comment]
I have created a simple project available here:
https://github.com/Andrzej-W/CultureCompare
which can be used to compare some of the most important properties in cultures defined on the server and in Blazor WASM. Application is available online here:
https://culturecompare.azurewebsites.net/
What does this app do? It enumerates all cultures available in WASM and compares them to cultures downloaded from the server. Currently application is hosted on Windows Server (on Linux you will see different results). `Show` button is red if there is at least one difference (EnglishName property is ignored because it is always different).
![obraz](https://user-images.githubusercontent.com/32604409/112230807-cc14c280-8c35-11eb-82cc-8c9544697167.png)

Here is how it looks on Polish Windows 10 1909:

![obraz](https://user-images.githubusercontent.com/32604409/112230595-632d4a80-8c35-11eb-9e2f-5a213c82da70.png)

and this is Windows Server (I have no idea what version)

![obraz](https://user-images.githubusercontent.com/32604409/112230686-953eac80-8c35-11eb-9554-dbc83949b71b.png)

As you can see from this application **the same culture can have different definitions in different environments** and you should always use culture independent formatting in places where a specific method of data presentation is required. Unfortunately colon in your string `yyyy-MM-dd'T'HH:mm:ssK` is only placeholder (https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#date-and-time-separator-specifiers) for culture dependent separator and it is dot for da-DK on Blazor WASM.

**Comment by erikthysell** [comment]
@Andrzej-W - thanks a lot for that piece of software. Sounds good and I think I understand what you are suggesting but I already do specify time format:
```
@page "/"

<h1>Hello, world!</h1>

Welcome to my test app.
<button class="btn btn-primary" @onclick=@UpdateTime>Update time</button> 
<input type="time" @bind="myTime" @bind:format=@myTimeFormat />

<div class="alert alert-primary">@myTime.ToString(_RFC3339Format)</div>

@code{
    private const string _RFC3339Format = "yyyy-MM-dd'T'HH:mm:ssK";
    DateTime myTime = DateTime.Now;
    string myTimeFormat = "HH:mm:ss";

    private void UpdateTime()
    {

        myTime = DateTime.Now;
        Console.WriteLine(myTime.ToString(_RFC3339Format));
    }
}
```

And this still prints out as:

> 2021-03-24T11.18.47+01:00

both on screen and in browser console.

Is there something else I should do or what am I not understanding?

**Comment by Andrzej-W** [comment]
@erikthysell run this code to understand the difference between culture dependent and culture independent formatting.

```html
@page "/"
@using System.Threading
@using System.Globalization

<h1>Date and time formatting</h1>

<button class="btn btn-primary" @onclick=@UpdateTime1>Update time en-US</button>
<button class="btn btn-primary m-2" @onclick=@UpdateTime2>Update time da-DK</button>
<input type="time" @bind="myTime" @bind:format=@myTimeFormat />

<div class="alert alert-primary mt-2">Culture dependent formatting: @myTime.ToString(Format1)</div>
<div class="alert alert-primary">Culture independent formatting: @myTime.ToString(Format2)</div>
```
```c#
@code
{
  // Please note that / (slash) will be replaced by culture dependent date separator
  // and : (colon) will be replaced by culture dependent time separator.
  // Letter T is not reserved character and will be included in the output string unchanged
  // (you don't have to use apostrophes around capital letter T)
  // Read section "Date and time separator specifiers" and "Character literals" here:
  // https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#date-and-time-separator-specifiers

  private const string Format1 = "yyyy/MM/ddTHH:mm:ssK";      // string with culture dependent placeholders
  private const string Format2 = "yyyy-MM-ddTHH':'mm':'ssK";  // string with literals - you have to use ' (apostrophe) around colon
  DateTime myTime = DateTime.Now;
  string myTimeFormat = "HH':'mm':'ss";  // use apostrophes around colons, otherwise colon will be replaced by culture dependent time separator

  private void UpdateTime1()
  {
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    myTime = DateTime.Now;
  }
  private void UpdateTime2()
  {
    Thread.CurrentThread.CurrentCulture = new CultureInfo("da-DK");
    myTime = DateTime.Now;
  }
}
```

**Comment by Andrzej-W** [comment]
In my opinion Blazor WASM works correctly (binding to `input type="time"`) and this issue can be closed.

Unfortunately there are some differences in culture definitions in various environments (Windows 10, Windows Server, Linux, WASM). What is the moral of the story? Whenever you exchange data between different systems, you must use culture-independent date, time, and number formatting, even if you are sure that both systems are set to the same culture.

**Comment by erikthysell** [comment]
@Andrzej-W -Thanks a lot. I finally see what the issue is... :) (it took some time).

**Comment by nvmkpk** [comment]
I also ran into these differences between the Blazor WASM and Blazor Server side. In .net Core 3.1 it worked fine. As soon as I updated to .net 5.0 I saw these differences. By the way I am only using the properties on `CultureInfo` (specifically `NativeName`) to let user choose a language of the website.

**Comment by SteveSandersonMS** [comment]
I attempted to reproduce this, but wasn't able to do so. I used the sample repro code from the StackOverflow post:

```
<input type="time" @bind="myTime" @bind:format=@myTimeFormat />
@code{
    DateTime myTime = DateTime.Now.ToLocalTime();
    string myTimeFormat = "HH:mm:ss"; 
}
```

... and tried this with both .NET 5 and .NET 6 in a browser set to Danish language. In all cases, the time was correctly displayed and was editable.

Looking at the implementation, I see that `@bind` generates code that formats the date with invariant culture, so it shouldn't make any difference what language the browser is set to (which is consistent with the behavior I saw during investigation).

If anyone is still able to reproduce this, please post a new issue with further repro steps. Thanks!
