### ISSUE TITLE
Blazor Desktop tenets: Reliability

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#30529]
- Need to review guidance from docs of each native WebView component for any best practices
- Check for failure modes in the various WebViews, for example, out-of-proc renderer crashing
  - Example: Detect WebView2 out-of-proc failure: https://github.com/MicrosoftEdge/WebView2Announcements/issues/17

**Comment by mkArtakMSFT** [comment]
Closing as there is no clear action pending here.
