### ISSUE TITLE
Component references not resolved when building in VS

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#30536]
### Describe the bug
Component references not resolved when building in VS. Perhaps another RSG bug to resolve.

### To Reproduce

1. Create a new Blazor Server project.
2. Navigate to to `Pages/Index.razor`.
3. Observe that it cannot resolve the reference to `SurveyPrompt`.

### Further technical details
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.10.0 Preview 2.0 [31026.214.main]
SDK: 6.0.100-preview.3.21123.4

**Comment by pranavkm** [comment]
This is a SDK issue - I can also see this when building in the CLI. Should we move this to the 6.0-p3 milestone?

**Comment by captainsafia** [comment]
Yep, my labeling here was confusing. I was trying to indicate that the bug affected both scenarios.

@NTaylorMullen: Taking this off your plate.

**Comment by NTaylorMullen** [comment]
Hmmm, is this only a .NET 6.0 Preview3 issue or is this the same one we saw in preview2?

**Comment by captainsafia** [comment]
This is only preview3.

It's resolved via https://github.com/dotnet/sdk/commit/fec787198d202006220dc3fd81ff9522c7103ba1.
