### ISSUE TITLE
GRPC :scheme pseudo-header passed from proxy/loadbalancer causes ConnectionAbortedException

### ISSUE THREAD

**Issue by simplecoder** [dotnet/aspnetcore#30532]
### Describe the bug
Grpc kestrel .net 5 sample app greeter is running in k8s under http transport, an AWS network load balancer terminates SSL and sends request to the app with :scheme pseudo-header set to "https", but the actual transport is "http" results in this error -
`Trace id "0HM6QO8HEK1N9:00000001": HTTP/2 stream error "PROTOCOL_ERROR". A Reset is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The request :scheme header 'https' does not match the transport scheme 'http'.` 

The ask here is to be less stringent on validating on the :schema pseudo header, Go lang sample apps works fine.

### To Reproduce

Deploy any sample grpc app from here - https://github.com/grpc/grpc-dotnet/tree/master/examples to k8s, setup the service type loadbalancer using AWS NLB. Test with grpcurl client.

### Exceptions (if any)

`Microsoft.AspNetCore.Connections.ConnectionAbortedException: The request :scheme header 'https' does not match the transport scheme 'http'.`
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment]
Prior discussion: https://github.com/dotnet/aspnetcore/issues/14745. The main report was the result of a bug in the Java client. No concrete examples were given for the proxy scenario at the time.

The spec is extremely vague on the proper usage of this field so we opted for a strict interpretation until the scenarios could be clarified.

> an AWS network load balancer terminates SSL

Is this an L7 or L4 proxy? 
- For an L7 proxy it would make sense to run into this as it wouldn't understand the Http/2 protocol and wouldn't be able to make hop-by-hop modifications.
- For an L4 proxy it's the usage here is undefined. An L7 proxy would normally need to add x-forwarded-proto or Forwarded to headers to convey external information like the scheme.

**Comment by simplecoder** [comment]
Its a L4 proxy.

**Comment by BrennanConroy** [comment]
@blowdart What are your thoughts on making the `:scheme` header check less strict? Or adding an option to allow configuration?

**Comment by blowdart** [comment]
Option, which you must opt into, with a suitable name like InsecureProtocolValidation. And scoped as narrowly as possible. So just to grpc.

**Comment by Tratcher** [comment]
The narrowest a setting like this could be scoped would be to an IP endpoint. gRPC is a higher level protocol.

Scoping it to the whole server instance (KestrelServerOptions) would be more consistent with our other HTTP/2 limits.

**Comment by blowdart** [comment]
Does this also happen on http/web connections then? Or is it GRPC only?

(And why can't the amazon forwarder be configured "correctly"?)

**Comment by Tratcher** [comment]
This _could_ happen with any http/2 connection coming through a revers proxy.

@simplecoder can you confirm if the AWS load balancer behaving the same for general HTTP/2 traffic?

**Comment by simplecoder** [comment]
@Tratcher - confirmed its behaving the same for general HTTP/2 traffic. The test app was the sample 'WeatherForcast' api app. Here is the output -
```
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HM6TRBO44E22" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM6TRBO44E22" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[35]
      Trace id "0HM6TRBO44E22:00000001": HTTP/2 stream error "PROTOCOL_ERROR". A Reset is being sent to the stream.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The request :scheme header 'https' does not match the transport scheme 'http'.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
      Connection id "0HM6TRBO44E22" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[36]
      Connection id "0HM6TRBO44E22" is closed. The last processed stream ID was 1.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HM6TRBO44E22" sending FIN because: "The client closed the connection."
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
```

@blowdart I didn't see an option on the AWS load balancer side to change the ":scheme" header they send.

**Comment by zhuoyang** [comment]
is there any update or workaround for this issue?

**Comment by wlhee** [comment]
This problem also affects reverse proxy (such as Envoy) that terminates TLS and then forward gRPC over h2c.

Is it possible to add an option to disable the server schema check? .NET is the only language that has this behavior. It'a arguably a correct implementation, but it causes a lot of user pains.

**Comment by turgayozgur** [comment]
Facing this issue on GCP Cloud Run.
https://stackoverflow.com/questions/67420541/problem-with-listening-grpc-requests-over-http-on-cloud-run

**Comment by davidfowl** [comment]
This is something we need to enable. Can we make the API proposal so we can review it next week @Tratcher ?

**Comment by Tratcher** [comment]
@MattyBoy4444 we'd have expected Envoy to send the https scheme as an x-forwarded-proto header and set the `:scheme` to http. Then ForwardedHeadersMiddleware would have been useful. As is, there's a hard block in the server that prevents it from accepting requests with `:scheme` values that don't match the transport. 

There's no workaround from the ASP.NET side other than using TLS between Envoy and Kestrel. I don't know if you can work around it from the Envoy end.

**Comment by Tratcher** [comment]
@davidfowl do we have kestrel ignore the scheme value, or do we have it honor it? E.g. should HttpRequest.Scheme show http or https? Envoy seems to intend this as a replacement for x-fowarded-proto.

**Comment by davidfowl** [comment]
>  Envoy seems to intend this as a replacement for x-fowarded-proto.

That's very interesting and I like it, but we should take a look at what a few other servers do here (go, no, nginx).

**Comment by MattyBoy4444** [comment]
> > Envoy seems to intend this as a replacement for x-fowarded-proto.
> 
> That's very interesting and I like it, but we should take a look at what a few other servers do here (go, no, nginx).

Not sure fixing Envoy helps with the major cloud providers.  Ex: Cloud Run.

**Comment by davidfowl** [comment]
We're discussing what the option does and we're going to get more data to see what competitors in the space do so we're well informed

**Comment by wlhee** [comment]
Thanks. To add an additional data point: IIRC, all other languages with gRPC support don't (at least by default) have this enforcement on the h2c gRPC channel.

**Comment by davidfowl** [comment]
Which ones did you try? (you said *all*)

**Comment by wlhee** [comment]
Well, I have to say I  exaggerate :)

I tired the followings and they don't enforce the scheme for gRPC h2c channels: C++, Go, Java, Kotlin, Objective-C, Node, Pythong, Rust.

I don't know what happens underneath, for example, I am not sure if language itself doesn't check, or check bug ignore, or it provides an option which set by gRPC framework.

**Comment by davidfowl** [comment]
Well that's what we want to find out 😄.

**Comment by wlhee** [comment]
Unfortunately I don't know deep enough into these layers ... I tried search around to look for golang implementation, but didn't get any conclusive answer.

**Comment by wlhee** [comment]
Envoy recently switched to using the original URL scheme or X-Forwarded-Proto as the request scheme recently:

"http: fixing a standards compliance issue with :scheme. The :scheme header sent upstream is now based on the original URL scheme, rather than set based on the security of the upstream connection. This behavior can be temporarily reverted by setting envoy.reloadable_features.preserve_downstream_scheme to false."

https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.18.0

**Comment by Tratcher** [comment]
https://github.com/envoyproxy/envoy/issues/14587 is an interesting read, they seem to be re-thinking their stance on this.

**Comment by jimm1419** [comment]
This recently broke me in Cloud Run, I guess GCP updated envoy because it was working fine a couple of weeks ago.  Here's a workaround if anyone needs it:
1.  Download this repo, I use v5 so `git clone https://github.com/dotnet/aspnetcore.git && cd aspnetcore && git checkout tags/v5.0.5`
2. Find the file `/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs` and comment out lines 244-250.  If not version 5.0.5, it's the block of code that starts with `if (!ReferenceEquals(headerScheme, Scheme) &&`, comment that whole if block
3. build the project - `./build.sh --configuration Release` in the root of the project.  It had a few errors but the file I needed was built.
4. Take file `aspnetcore/artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Core/Release/net5.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll` and copy it to a folder with the following Dockerfile:
```
FROM mcr.microsoft.com/dotnet/aspnet:5.0

COPY ./Microsoft.AspNetCore.Server.Kestrel.Core.dll /usr/share/dotnet/shared/Microsoft.AspNetCore.App/5.0.5/
```

A bit of a pain, but we're back up on Cloud Run with this ...

**Comment by MattyBoy4444** [comment]
> This recently broke me in Cloud Run, I guess GCP updated envoy because it was working fine a couple of weeks ago. Here's a workaround if anyone needs it:
> 
> 1. Download this repo, I use v5 so `git clone https://github.com/dotnet/aspnetcore.git && cd aspnetcore && git checkout tags/v5.0.5`
> 2. Find the file `/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs` and comment out lines 244-250.  If not version 5.0.5, it's the block of code that starts with `if (!ReferenceEquals(headerScheme, Scheme) &&`, comment that whole if block
> 3. build the project - `./build.sh --configuration Release` in the root of the project.  It had a few errors but the file I needed was built.
> 4. Take file `aspnetcore/artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Core/Release/net5.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll` and copy it to a folder with the following Dockerfile:
> 
> ```
> FROM mcr.microsoft.com/dotnet/aspnet:5.0
> 
> COPY ./Microsoft.AspNetCore.Server.Kestrel.Core.dll /usr/share/dotnet/shared/Microsoft.AspNetCore.App/5.0.5/
> ```
> 
> A bit of a pain, but we're back up on Cloud Run with this ...

@jimm1419  THANK YOU!!!!  I love this kind of hack!!  (Hack used in the best sense of the word)   Getting $h-t done.

You need one more step to get the submodules.  After 1, then 
`git submodule update --init --recursive`

Also, if building from windows command
`./build.cmd -Configuration Release`

**Comment by turgayozgur** [comment]
> This recently broke me in Cloud Run, I guess GCP updated envoy because it was working fine a couple of weeks ago. Here's a workaround if anyone needs it:
> 
> 1. Download this repo, I use v5 so `git clone https://github.com/dotnet/aspnetcore.git && cd aspnetcore && git checkout tags/v5.0.5`
> 2. `git submodule update --init --recursive`
> 3. Find the file `/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs` and comment out lines 244-250.  If not version 5.0.5, it's the block of code that starts with `if (!ReferenceEquals(headerScheme, Scheme) &&`, comment that whole if block
> 4. build the project - `./build.sh --configuration Release` in the root of the project.  It had a few errors but the file I needed was built.
> 5. Take file `aspnetcore/artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Core/Release/net5.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll` and copy it to a folder with the following Dockerfile:
> 
> ```
> FROM mcr.microsoft.com/dotnet/aspnet:5.0
> 
> COPY ./Microsoft.AspNetCore.Server.Kestrel.Core.dll /usr/share/dotnet/shared/Microsoft.AspNetCore.App/5.0.5/
> ```
> 
> A bit of a pain, but we're back up on Cloud Run with this ...

Thank you @jimm1419.

Building the entire solution takes a lot of time. To build only the project `Microsoft.AspNetCore.Server.Kestrel.Core`, run the following commands instead of step 4.

1- `cd aspnetcore/src/Servers/Kestrel`, 
2- `./build.sh --configuration Release --os-name linux` 

then you will be able to find the`Microsoft.AspNetCore.Server.Kestrel.Core.dll` at `aspnetcore/artifacts/bin/Microsoft.AspNetCore.Server.Kestrel.Core/Release/net5.0`.

Make sure the version you are using is the same version you are copying the dll in your Dockerfile. Example for the version `5.0.6`:

```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0.203 AS build

COPY ./Microsoft.AspNetCore.Server.Kestrel.Core.dll /usr/share/dotnet/shared/Microsoft.AspNetCore.App/5.0.6/
...

FROM mcr.microsoft.com/dotnet/aspnet:5.0.6 AS runtime
...
```

**Comment by zhuoyang** [comment]
PSA for google cloud run users, google actually fixed this issue on their side

https://issuetracker.google.com/issues/187470251?pli=1

**Comment by Tratcher** [comment]
Data point: IIS/Http.Sys also reject requests that have a mismatched scheme with the same RST_STREAM(PROTOCOL_ERROR). Note these servers only support HTTP/2 over TLS so the scheme must always be `https`.

**Comment by heatonmatthew** [comment]
The original poster indicated that the issue was with .NET 5, but I have confirm that it exists for .NET Core 3.1 also.  My hunch is that it's in the underlying gRPC framework implementation (but I'm sure you're aware of that).

I notice that @Tratcher 's [original comment](https://github.com/dotnet/aspnetcore/issues/30532#issuecomment-787011248) refers to the RFC spec being vague.  I agree.  I'm having a brief discussion with the Envoy team regarding their interpretation and can see both sides of the argument.

Since the Envoy team, and the [Istio team](https://github.com/istio/istio/issues/33136) are needing to deal with this issue (possibly specifically for .NET), I'm wondering if there is any indication from the .NET team about where their deliberations are heading (i.e. especially given that this issue has been marked with the `Next sprint planning` milestone?  It would probably be helpful to those discussions to know whether this is something that needs to be dealt with in a long-term capacity.

Thanks.  :)

**Comment by Tratcher** [comment]
> My hunch is that it's in the underlying gRPC framework implementation (but I'm sure you're aware of that).

The restriction is in the servers themselves (Kestrel, Http.Sys, IIS).

> Since the Envoy team, and the [Istio team](https://github.com/istio/istio/issues/33136), are needing to deal with this issue (possibly specifically for .NET), I'm wondering if there is any indication from the .NET team about where their deliberations are heading (i.e. especially given that this issue has been marked with the `Next sprint planning` milestone)? It would probably be helpful to those discussions to know whether this is something that needs to be dealt with in a long-term capacity.

We do not expect the behavior to change in IIS or Http.Sys. We're considering a new .NET 6 API for Kestrel that would relax this restriction but haven't worked out the details yet.

The various providers and proxies have added configuration to mitigate this or have reverted the change. With the ambiguity in the spec this will likely need to be configurable in all proxies.
https://issuetracker.google.com/issues/187470251?pli=1
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.18.0

**Comment by heatonmatthew** [comment]
Thanks @Tratcher. I'm asking because the Envoy team is planning on retiring the flag that you reference in your link (see 
[14587](https://github.com/envoyproxy/envoy/issues/14587)) and want to implement something less generic and more targeted for ongoing support.

Understanding the position of the .NET ecosystem (i.e. Kestrel may change but IIS and Http.Sys won't) is helpful and I'll respond accordingly.  Thanks.

**Comment by Tratcher** [comment]
API proposal for Kestrel:

Note HTTP/3 always requires TLS connections but the feature still makes sense for other protocol translations.

```diff
public class Http2Limits
{
+ /// <summary>
+ /// If disabled (default) then the `:scheme` field for HTTP/2 requests must exactly match the transport (e.g. https for TLS connections, http for non-TLS).
+ /// If enabled then the `:scheme` field for HTTP/2 requests can be set to alternate values and this will be reflected by `HttpRequest.Scheme`. This can be used in scenarios like proxies converting from alternate protocols. See https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3.
+ /// </summary>
+ public bool AllowAlternateSchemes { get; set; } = false;
}
public class Http3Limits
{
+ /// <summary>
+ /// If disabled (default) then the `:scheme` field for HTTP/3 requests must exactly match the transport (e.g. https for QUIC connections).
+ /// If enabled then the `:scheme` field for HTTP/3 requests can be set to alternate values and this will be reflected by `HttpRequest.Scheme`. This can be used in scenarios like proxies converting from alternate protocols. See https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-4.1.1.1.
+ /// </summary>
+ public bool AllowAlternateSchemes { get; set; } = false;
}
```

**Comment by pranavkm** [comment]
We discussed putting this on the root Kestrel options at which point it would apply to HTTP/2 and HTTP/3. Most limits are currently numeric, so this seems like a slight outlier. On the other hand, it crowds the top-level option.

API feedback: Put this on the top level Kestrel option.

Additional discussion: Need to talk to @blowdart about enabling this option at all.

**Comment by Tratcher** [comment]
Updated API proposal:
```diff
public class KestrelServerOptions
{
+ /// <summary>
+ /// If disabled (default) then the `:scheme` field for HTTP/2 and HTTP/3 requests must exactly match the transport (e.g. https for TLS connections, http for non-TLS).
+ /// If enabled then the `:scheme` field for HTTP/2 and HTTP/3 requests can be set to alternate values and this will be reflected by `HttpRequest.Scheme`. This can be used in scenarios like proxies converting from alternate protocols. See https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3.
+ /// </summary>
+ public bool AllowAlternateSchemes { get; set; } = false;
}
```

**Comment by blowdart** [comment]
I grudgingly approve, with the proviso there's a warning about the security in the xml docs. Maybe an aka.ms links to a doc explaining the issue in detail as well?
