### ISSUE TITLE
[AllowAnonymous] attribute/filter must also ignore Authentication along with Authorization

### ISSUE THREAD

**Issue by mihirdilip** [dotnet/aspnetcore#30546]
## Summary

Adding `[AllowAnonymous]` attribute or filter either to MVC *Controller* or as metadata to an *Endpoint* only ignores Authorization flow. It must also ignore Authentication flow to avoid unnecessary calls to Authentication Handlers and Policy Evaluators. It would not only help with performance but also would not log unnecessary Authentication failure logs and keep the logs clean.

If you approve this depending on the agreed solution, I can try to implement and raise a PR. 

Found these related issues raised in the past: #15285 and #29377

## Motivation and goals

- Performance improvement
- Ignores unnecessary calls to Authentication Handlers
- Ignores unnecessary calls to Policy Evaluators
- Clean logs  

## Risks / unknowns

If any developer is using this issue/bug as a feature then it would cause some problem for them. To address this risk
1. Introduce this fix as behavioural change as default implementation and add a switch on *MvcOptions* to fall-back to previous behaviour. 
2. Default behaviour is not changed but this fix can be enabled by a switch on *MvcOptions*.
3. Any other suggestions?

**Comment by blowdart** [comment]
This is, as you can see from the linked issues by design. What you're proposing links authentication to authorization, something we've worked hard to avoid. Authorization has no real idea of authentication, other than its results, and that is a good thing.

**Comment by Tratcher** [comment]
> It would not only help with performance but also would not log unnecessary Authentication failure logs and keep the logs clean.

There shouldn't be authentication failures logged if the request does not include any credentials, each auth handler should no-op. Can you give some specific examples where this is happening? If however there are invalid credentials provided then those errors still seem appropriate.

**Comment by mihirdilip** [comment]
@blowdart , @Tratcher 
I appreciate your time but, I have debugged through the pipeline (Authentication and Authorization middlewares) and it tries to call the AuthenticationHandler even when AllowAnonymous is set. I have came across this when writing these libraries [aspnetcore-authentication-apikey](https://github.com/mihirdilip/aspnetcore-authentication-apikey) and [aspnetcore-authentication-basic](https://github.com/mihirdilip/aspnetcore-authentication-basic)

So lets say we have an implementation of AuthenticationHandler<TOptions> which is overriding HandleAuthenticateAsync() method which basically throws an exception. All of my endpoints have to be authenticated which is achieved by setting FallbackPolicy on AuthenticationOptions. Some of my endpoints are decorated with AllowAnonymous. Now the exception under HandleAuthenticateAsync is thrown even for the anonymous endpoint although in normal circumstances it would return NoResult() and the response will result into OK 200. Now the issue is, it executes the HandleAuthenticateAsync() which could be doing quite a work (e.g OAuth/OAuth2) for all the AllowAnonymous endpoints which is just a waste. 

Below is the sample code from a quick throw away project for it can be found here [aspnetcore-allowanonymous-test](https://github.com/mihirdilip/aspnetcore-allowanonymous-test).


```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAuthentication("ApiKey")
            .AddScheme<ApiKeyOptions, ApiKeyAuthenticationHandler>("ApiKey", _ => { });

        services.AddAuthorization(options =>
        {
            options.FallbackPolicy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
        });

        services.AddControllers();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseHttpsRedirection()
            .UseRouting()
            .UseAuthentication()
            .UseAuthorization()
            .UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/auth", async context =>
                {
                    await context.Response.WriteAsync("Authenticated Hello World!");
                });

                endpoints.MapGet("/anonymous", async context =>
                {
                    await context.Response.WriteAsync("Anonymous Hello World!");
                }).WithMetadata(new AllowAnonymousAttribute());
            });
    }
}

public class ApiKeyAuthenticationHandler : AuthenticationHandler<ApiKeyOptions>
{
    public ApiKeyAuthenticationHandler(IOptionsMonitor<ApiKeyOptions> options, ILoggerFactory logger, UrlEncoder encoder, ISystemClock clock)
        : base(options, logger, encoder, clock)
    {
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        throw new NotImplementedException();

        //try
        //{
        //    throw new NotImplementedException();
        //}
        //catch (Exception e)
        //{
        //    Logger.LogError(e, e.Message);
        //    return Task.FromResult(AuthenticateResult.NoResult());
        //}
    }
}

public class ApiKeyOptions : AuthenticationSchemeOptions
{
}
```

**Comment by Tratcher** [comment]
`AddAuthentication("ApiKey")` sets ApiKey as the default auth type for all requests, so that handler will be executed for all requests. Authorization/AllowAnonymous doesn't factor in at this stage. `ApiKeyAuthenticationHandler` **should** return NoResult if there is no API key present on the request. It should only throw if a bad key is provided.

The other way to get what you're asking for here is to not set a default authentication handler (`AddAuthentication("ApiKey")`) and to specify the ApiKey as the required auth scheme only in the fallback policy.

**Comment by mihirdilip** [comment]
`AddAuthentication("ApiKey") sets ApiKey as the default auth type for all requests, so that handler will be executed for all requests. Authorization/AllowAnonymous doesn't factor in at this stage.`
But can it be ignored for AllowAnonymous on [AuthenticationMiddleware.cs#L54](https://github.com/dotnet/aspnetcore/blob/50c635f95f0fcbe30f30175d2884f79e693f48a7/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs#L54), on [AuthorizationMiddleware.cs#L57](https://github.com/dotnet/aspnetcore/blob/50c635f95f0fcbe30f30175d2884f79e693f48a7/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L57) instead of L73 and on [AuthorizeFilter.cs#L173](https://github.com/dotnet/aspnetcore/blob/50c635f95f0fcbe30f30175d2884f79e693f48a7/src/Mvc/Mvc.Core/src/Authorization/AuthorizeFilter.cs#L173) instead of L191?

`ApiKeyAuthenticationHandler should return NoResult if there is no API key present on the request. It should only throw if a bad key is provided.` 
I understand and which is what it does in real project. This was just to show that this code is reached and also I had left the commented out code to show that a failed authentication can generate a log entry which could be misleading. So the question is why should this code be reached when AllowAnonymous is set?

`The other way to get what you're asking for here is to not set a default authentication handler (AddAuthentication()) and to specify the ApiKey as the required auth scheme only in the fallback policy.`
I tried what you suggested and there is no change in behaviour. The AuthenticationHandler.HandleAuthenticateAsync() is still reached for anonymous endpoint.
```C#
services.AddAuthentication()
    .AddScheme<ApiKeyOptions, ApiKeyAuthenticationHandler>("ApiKey", _ => { });

services.AddAuthorization(options =>
{
    options.FallbackPolicy = new AuthorizationPolicyBuilder("ApiKey").RequireAuthenticatedUser().Build();
});
```

What I am trying convey is, most of the straight forward API's will have default or same authentication scheme set for everything and only opt out some of the endpoints which may not need authentication. Now if this API were to use any of the RemoteAuthentications (e.g OAuth2), it could be making calls to the RemoteAuthentication provider when it is not really required unless it is validated within Handler. But again I still don't get the logic of it having to reach the Handler in first place when we (developer) specifically want to ignore authentication by setting AllowAnonymous. 

I already check for AllowAnonymous in the Handler in my actual library [aspnetcore-authentication-apikey](https://github.com/mihirdilip/aspnetcore-authentication-apikey) and ignore any further validation. But I believe this should be handled within aspnetcore.

**Comment by Tratcher** [comment]
> I already check for AllowAnonymous in the Handler in my actual library [aspnetcore-authentication-apikey](https://github.com/mihirdilip/aspnetcore-authentication-apikey) and ignore any further validation.

Why even do that much? Why doesn't it no-op if there is no key provided? Are you concerned about someone sending an invalid key to an anonymous endpoint?

It should be noted that this approach would not work for any server integrated auth scenarios like NTLM/Kerberos, ASP.NET does not have sufficient control over the underlying servers to skip their auth steps.

**Comment by mihirdilip** [comment]
`Why even do that much? Why doesn't it no-op if there is no key provided? Are you concerned about someone sending an invalid key to an anonymous endpoint?`
I am not concerned about invalid key. But, I am concerned about the unnecessary call trip to a cache or database to valid the key. If the apikey header does not exists it fine, but if it does exists, it will try to validate it if I do not check for allowanonymous. 

My other concern is, to reach to this HandleAuthenticateAsync it goes through quite a bit of code (eg. Policy evaluators and if I remember correctly some of it uses reflection). 

I appreciate it would not work for server integrated authentication but would it work for all the other type of authentication?

**Comment by Tratcher** [comment]
> `The other way to get what you're asking for here is to not set a default authentication handler (AddAuthentication()) and to specify the ApiKey as the required auth scheme only in the fallback policy.`
> I tried what you suggested and there is no change in behaviour. The AuthenticationHandler.HandleAuthenticateAsync() is still reached for anonymous endpoint.

@HaoK did this not work because the anonymous policy and the fallback policy were combine before being evaluated?

**Comment by bachmannn** [comment]
@mihirdilip I have the same complexity when using `[AllowAnonymous]` it hits breakpoints on `HandleAuthenticateAsync()` and does not skip AuthenticationHandler.

For a workaround I tried to check for Anonymous but I get error mentioned in #30557.

```csharp
var endpoint = context.HttpContext.GetEndpoint();
if (endpoint?.Metadata?.GetMetadata<IAllowAnonymous>() != null)
{
}
```

Is the check in your library [aspnetcore-authentication-apikey](https://github.com/mihirdilip/aspnetcore-authentication-apikey/blob/e29771fff31637cf9ef273919d67b203ea9e250e/src/AspNetCore.Authentication.ApiKey/ApiKeyHandlerBase.cs#L235-L243) working on .NET 5.x?

```csharp
		private bool IgnoreAuthenticationIfAllowAnonymous()
		{
#if (NET461 || NETSTANDARD2_0)
			return false;
#else
			return Options.IgnoreAuthenticationIfAllowAnonymous
				&& Context.GetEndpoint()?.Metadata?.GetMetadata<Microsoft.AspNetCore.Authorization.IAllowAnonymous>() != null;
#endif
		}
```

**Comment by HaoK** [comment]
> > `The other way to get what you're asking for here is to not set a default authentication handler (AddAuthentication()) and to specify the ApiKey as the required auth scheme only in the fallback policy.`
> > I tried what you suggested and there is no change in behaviour. The AuthenticationHandler.HandleAuthenticateAsync() is still reached for anonymous endpoint.
> 
> @HaoK did this not work because the anonymous policy and the fallback policy were combine before being evaluated?

So looking at the sample code above, if the "ApiKey" was removed from AddAuthentication(), there should be no authentication done unless an AuthorizationPolicy asked for "ApiKey" in its authentication schemes, or if some code explicitly was calling AuthenticateAsync.  The fallback policy of RequireAuthenticatedUser doesn't trigger any authentication, it just adds a AuthZ requirement that the identity IsAuthenticated = true.

**Comment by HaoK** [comment]
Oh right, I didn't see that the fallback policy is specifying "ApiKey", so the fallback policy is only applied when there is no other policies set, including the default policy, which I guess is the case here

**Comment by mihirdilip** [comment]
@bachmannn 
> Is the check in your library [aspnetcore-authentication-apikey](https://github.com/mihirdilip/aspnetcore-authentication-apikey/blob/e29771fff31637cf9ef273919d67b203ea9e250e/src/AspNetCore.Authentication.ApiKey/ApiKeyHandlerBase.cs#L235-L243) working based on issue [#15](https://github.com/mihirdilip/aspnetcore-authentication-apikey/issues/15)?

It does work. I have just update the [sample project here](https://github.com/mihirdilip/aspnetcore-allowanonymous-test) to have the MVC Controller and it does work as expected i.e. the `endpoint?.Metadata?.GetMetadata<IAllowAnonymous>()` is not null.

I also copied Home controller from your sample on #30557. Unless that code is a stripped down version, the problem (I think) in the sample is it is not decorated with any routing attributes and so that Foo() (typo on sample it is property) endpoint is not reached at all.

**Comment by mihirdilip** [comment]
> Oh right, I didn't see that the fallback policy is specifying "ApiKey", so the fallback policy is only applied when there is no other policies set, including the default policy, which I guess is the case here

@HaoK, so when we use [AllowAnonymous] metadata, should the FallbackPolicy be triggered or not? 

We are using FallbackPolicy to make sure all the requests are authenticated unless the specific policy/requirement is used for a specific endpoint.

**Comment by HaoK** [comment]
AllowAnonymous is really unrelated to policies, its effect is to by pass checking authorization, it has no affect on anything else, including authentication, you can see this clearly in in the Authorization middleware: https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L73

1. The effective policy is built out of the metadata for the endpoint (this takes care of things like default/fallback policies).  
2. Authentication is done (if the policy specifies any authentication schemes).
3. We are done if AllowAnoymous is specified
4. Otherwise continue to do Authorization

This behavior is intentional and by design.  AllowAnonymous should be interpreted as SkipAuthorize, but its been around for so long its not really feasible to rename, that would make it more clear what its really doing.
