### ISSUE TITLE
Dot net cert not being trusted (or generated)

### ISSUE THREAD

**Issue by joro550** [dotnet/aspnetcore#30548]
### Describe the bug
The dotnet dev cert is not being accepted 

### To Reproduce
Terminal commands:

```
D:\> dotnet dev-certs https --check
No valid certificate found.
D:\> dotnet dev-certs https
The HTTPS developer certificate was generated successfully.
D:\> dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. A confirmation prompt will be displayed if the certificate was not previously trusted. Click yes on the prompt to trust the certificate.
The HTTPS developer certificate was generated successfully.
D:\> dotnet dev-certs https --check
No valid certificate found.
```
This was after clicking yes on the prompt that appears

I have also tried this from my `C:\Users\<username>` directory and the same thing happens
### Further technical details
- ASP.NET Core version
Not sure it was the template from my version

Include the output of `dotnet --info`

```
D:\> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Rider
Vs Code

**Comment by joro550** [comment]
Managed to fix this by following the trouble shooting on the page >.<

**Comment by Fulgar** [comment]
> Managed to fix this by following the trouble shooting on the page >.<

@joro550 
Hi, could you elaborate on which page you found this info on? Currently having a possibly similar issue. Thanks.

**Comment by joro550** [comment]
Hey @Fulgar! 

For me this particular solution helped me with my struggles: https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#windows---certificate-not-trusted

I had a bunch of certificates that were assigned to localhost, I literally deleted them all and then reran the `dotnet dev-certs https --trust` command and it hasn't asked me to trust the certificate since
