### ISSUE TITLE
Using endpoint?.Metadata?.GetMetadata<IAllowAnonymous>() mentioned in aspnet/Annoucements always defaults to null

### ISSUE THREAD

**Issue by bachmannn** [dotnet/aspnetcore#30557]
### Describe the bug
Type `IAllowAnonymous` was moved as breaking change and the [announcement](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#authorization-iallowanonymous-removed-from-authorizationfiltercontextfilters) recommends to use:

```csharp
var endpoint = context.HttpContext.GetEndpoint();
if (endpoint?.Metadata?.GetMetadata<IAllowAnonymous>() != null)
{
}
```

But `<IAllowAnonymous>` value always defaults to `null or undefined` and is not present in `Metadata?`

### To Reproduce

Use the above code snippet in method for `HandleAuthenticateAsync()` in `AuthenticationHandler<T>` when creating custom authentication handler:

```csharp
public class CustomAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
   public const string Scheme = "Custom";

    public CustomAuthenticationHandler(
            IOptionsMonitor<AuthenticationSchemeOptions> options,
            ILoggerFactory logger,
            UrlEncoder encoder,
            ISystemClock clock)
            : base(options, logger, encoder, clock)
        {
        }

     protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
     {
            var endpoint = this.Context.GetEndpoint();
 
            // Check for [AllowAnonymous] present on method
            // this is always null and not present in Metadata?
            if (endpoint?.Metadata?.GetMetadata<IAllowAnonymous>() != null)
            {
                return await AuthenticateResult.NoResult();
            }

            return await AuthenticateResult.Fail();
     }
}
```

2. Use `[AllowAnonymous]` attribute on controller method:
```csharp
public class HomeController : Controller
{
    [AllowAnonymous]   // doesn't show up in Metadata.GetMetadata<IAllowAnonymous>();
    public string Foo => "Bar";
}
```

3. Mention in Startup
```csharp
public void ConfigureServices(IServiceCollection services)
{
     services.AddTransient<IHttpContextAccessor, HttpContextAccessor>();
     
     // Authentication
     services.AddAuthentication(auth => {
          auth.AddScheme<CustomAuthenticationHandler>(CustomAuthenticationHandler.Scheme, "Custom");
     });
}

// Configure method snippet
app.UseAuthentication();
app.UseAuthorization();
```

### Exceptions (if any)

Value `endpoint?.Metadata?.GetMetadata<IAllowAnonymous>()` is not present on `Endpoint.Metadata` even with `[AllowAnonymous]` present.

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    9effbc8ad5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  5.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
> ```cs
>     [AllowAnonymous]   // doesn't show up in Metadata.GetMetadata<IAllowAnonymous>();
>     public string Foo => "Bar";
> ```

Wow, is that really a valid MVC action @pranavkm?

**Comment by Tratcher** [comment]
> ```cs
> // Configure method snippet
> app.UseAuthentication();
> app.UseAuthorization();
> ```

@bachmannn can you expand this to include the routing middleware? The order is important.

Also, as you've seen in the discussions for #30546, we strongly discourage the mixing of Authorization (IAllowAnonymous) and Authentication (AuthenticationHandler). An AuthenticationHandler shouldn't need to know about the authorization rules on the matched route, only about the incoming request.

**Comment by davidfowl** [comment]
> Wow, is that really a valid MVC action @pranavkm?

I'm like 96% sure that isn't an action.

**Comment by mihirdilip** [comment]
@bachmannn , please see comments [here](https://github.com/dotnet/aspnetcore/issues/30546#issuecomment-788851901)

**Comment by javiercn** [comment]
> ```cs
> ```cs
>     [AllowAnonymous]   // doesn't show up in Metadata.GetMetadata<IAllowAnonymous>();
>     public string Foo => "Bar";
> ```
> 
> 
> 
> Wow, is that really a valid MVC action @pranavkm?
> ```

That is not an action. That's a property.
