### ISSUE TITLE
Use DataProtection to digitally signin JWT

### ISSUE THREAD

**Issue by brunohbrito** [dotnet/aspnetcore#30550]
### Is your feature request related to a problem? Please describe.
Isn't a problem. But can improve security for API's

### Describe the solution you'd like
Change the default way to sign JWT's

### Additional context

Hi guys, 

At ASP.NET MVC after a successful login, ASP.NET generate a Cookie, encrypt it and send to user. Great. The dev doesn't really knows how it was generated. I could say that there are many devs maybe doesn't know it is encrypted. Or worst, why we use it. Anyway.

But it's really common nowadays the dev's create REST API's. And they need to emit a JWT Token instead. While the first case they don't need to care about how it works under the hood. But with JWT, they need to digitally sign it. Create a key. Store and manage it. 

Definetely isn't a simple Task. HMAC keys need to have a 64 bit key. Rotate every 90 days and so on. 
I'll not mention that I've never seen someone using RSA / ECDsa. It's a dream.

When we look at DataProtection component, it accomplish the task in a very competent way. Rotate the key every 90 days. There is an good fit with azure App Service. Many extensions to store it in a safe place.

So I've two questions: 

1. Why we don't provide a better way to sign-in a token with DataProtection masterKey? 
2. Do you see any flaws of security doing it in this way:

```c#

    [ApiController]
    [Route("jwt-protection")]
    public class JwtFromDataProtectionKeys : ControllerBase
    {
        private readonly IKeyRingProvider _keyRingProvider;
        private readonly IKeyManager _keyManager;

        public JwtFromDataProtectionKeys(
            IKeyRingProvider keyRingProvider,
            IKeyManager keyManager)
        {
            _keyRingProvider = keyRingProvider;
            _keyManager = keyManager;
        }

        /// <summary>
        /// Get current key.
        /// </summary>
        private JsonWebKey CreateJwk()
        {
            // Get current key ring from DataProtection
            var currentKeyRing = _keyRingProvider.GetCurrentKeyRing();

            // Identify current KeyId
            var defaultKeyId = currentKeyRing.DefaultKeyId;

            // Get private key from current keyid
            var storedKey = _keyManager.GetAllKeys().First(f => f.KeyId == defaultKeyId);
            var descriptorXmlInfo = storedKey.Descriptor.ExportToXml();
            var key = new XElement("key", descriptorXmlInfo.SerializedDescriptorElement.LastNode).Value;

            // generate jwk. Then sign jwk
            var bKey = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true).GetBytes(key);
            var symetricKey = new HMACSHA256(bKey);

            var jwk = JsonWebKeyConverter.ConvertFromSymmetricSecurityKey(new SymmetricSecurityKey(symetricKey.Key));
            jwk.KeyId = Base64UrlEncoder.Encode(defaultKeyId.ToString());

            return jwk;
        }

        /// <summary>
        /// Kind of jwks
        /// </summary>
        /// <returns></returns>
        private IEnumerable<JsonWebKey> GetKeys()
        {
            var jwks = new List<JsonWebKey>();
            // Get keys from DataProtectionKeys
            var storedKey = _keyManager.GetAllKeys();
            foreach (var key in storedKey.OrderByDescending(b => b.CreationDate))
            {
                var defaultKeyId = key.KeyId;

                // Export for Xml to get access to masterkey
                var descriptorXmlInfo = key.Descriptor.ExportToXml();
                var keyData = new XElement("key", descriptorXmlInfo.SerializedDescriptorElement.LastNode).Value;

                var bKey = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true).GetBytes(keyData);
                var symetricKey = new HMACSHA256(bKey);

                var jwk = JsonWebKeyConverter.ConvertFromSymmetricSecurityKey(new SymmetricSecurityKey(symetricKey.Key));
                jwk.KeyId = Base64UrlEncoder.Encode(defaultKeyId.ToString());

                jwks.Add(jwk);
            }

            return jwks;
        }
   // Normal routines to generate Jwt
}
```

I'm achieved it, but was really painful to find out every piece of code. Debbuging the aspnet code to understande how it works.

sorry about create this issue. But I've tried to search in many places and I couldn't find anywhere.

**Comment by blowdart** [comment]
The whole point of data protection is to be a black box you just use. 

JWT signing, and the meta data endpoint require knowledge of keys and algorithms, which goes against the data protection design. Additionally, internally, data protection using symmetric keys, which isn't what most JWT signing should be using because you'd have to exchange keys, and there's no repudiation using symmetric keys.

This is why we can't and won't use data protection for this sort of thing.

**Comment by brunohbrito** [comment]
@blowdart I understand, but my point is that blackbox isn't that all bad. Why not think about something like DataProtection? If we check every blog post about how to emit JWT, I could say that 99% of them will be something like: 

```c#
            var tokenHandler = new JwtSecurityTokenHandler();
            var key = Encoding.ASCII.GetBytes("my-superscret"); //Hard coded or getting from appsettings
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                // ..
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
            };
            var token = tokenHandler.CreateToken(tokenDescriptor);
```
We can't find any docs at Microsoft showing how to do better with symetric keys. Unfortunately it leads the devs to these weirds example about how to (not) do it, instead. 
p
At Microsoft docs we can find some examples. They uses IdentityServer and itself isn't a better option. Because it's hides that the Key rotation is a paid feature. And requires a lot of setup and oauth2.0 & openid knowledge to do the most simplest scenario.
(https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
(https://docs.microsoft.com/en-us/dotnet/architecture/microservices/secure-net-microservices-web-applications/)

Also the free version create a temp.key file at root folder in RSA format and don't rotate it. And things goes worst if you are using docker/k8s and need to scale up the app.

In times of microservices and distributed apps we could do better than: Create your jwt and take care of your security.

While a few devs knows about how to better manage a key with JWT, almost every dev is using it. 

So why not provide a better solution within ASP.NET, we are almost there, DataProtection has many feature that is desirable to manage a key. 

Is a componeent like it so awful?

```c#
    interface IJwtProtection 
    {
        SigningCredentials GetCurrent()
    }
```
This component can generate [64 bytes keys](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hmacsha256.-ctor?view=net-5.0) and store it safely in many flavors like [DataProtection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0) do. With options to generate new one at custom amount of time.

Or a component that use rsa/ecdsa algorithms under the hood and we can use at startup :

```c#
    public void Configure(IApplicationBuilder app)
    {
        app.UseJwtProtection(jwks_endpoint: "/jwks")
    }

    // After the app start an endpoint at: https://localhost:5000/jwks
```

Isn't so compliacated after all and aspnet can show that a Security isn't a rocket science.

Is my request far away from aspnet goals?

**Comment by blowdart** [comment]
Issuing JWTs, along with the security flows, authentication and authorization around it are things we leave to specialists like AAD, Identity Server or Auth0. Wanting to roll your own is rare, it's why the JWT components are actually owned by AAD, because this is their bread and butter not ours.

It's just not something we feel is suitable for a framework.
