### ISSUE TITLE
AddDefaultTokenProviders and TokenOptions don't seem to tally up

### ISSUE THREAD

**Issue by mondss** [dotnet/aspnetcore#30568]
### Describe the bug

Related to #24763, is there a reason why, for password token emails and confirmation emails, when using the default token providers, that the default token provider used is not the `DefaultEmailProvider` but is instead the `DefaultProvider`, which uses an equivalent of a machine key?

This is a barrier to scalability in my opinion and isn't immediately obvious and I was wondering if it was indeed a bug or intended behavior and why?

Thanks!

### To Reproduce

Calling `.AddDefaultTokenProviders` sets the default provider to be that of `DataProtectorTokenProvider<>`.

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Identity/Core/src/IdentityBuilderExtensions.cs#L21-L32

The `UserManager<T>` class then, when performing email related actions such as `GenerateEmailConfirmationTokenAsync` (and others), correctly uses the `TokenOptions.EmailConfirmationTokenProvider`

https://github.com/dotnet/aspnetcore/blob/88226213a3dcef969310de1fb7510f40bdfb2ab2/src/Identity/Extensions.Core/src/UserManager.cs#L1472-L1476

However, by default, `TokenOptions.EmailConfirmationTokenProvider` is set to use the `DefaultProvider` constant, which then uses the `DataProtectorTokenProvider<>` which will not work across multiple instances on different machines unless you persist encryption keys in a centralised place.

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Identity/Extensions.Core/src/TokenOptions.cs#L45

### Further technical details

ASP.NET Core version - 5.0.3

Include the output of dotnet --info

![image](https://user-images.githubusercontent.com/47109131/109680331-4fca1a80-7b74-11eb-8e42-fa2c7421f54a.png)

The IDE - Jetbrains Rider

**Comment by blowdart** [comment]
_which then uses the DataProtectorTokenProvider<> which will not work across multiple instances on different machines unless you persist encryption keys in a centralised place._

Can I ask why this is a problem? You already need to setup a shared machine key for any web app that is accepting forms, or authentication cookies for those to work.

**Comment by mondss** [comment]
> _which then uses the DataProtectorTokenProvider<> which will not work across multiple instances on different machines unless you persist encryption keys in a centralised place._
> 
> Can I ask why this is a problem? You already need to setup a shared machine key for any web app that is accepting forms, or authentication cookies for those to work.

Hey - thanks for your reply.

In most normal scenarios, I guess it wouldn't be an issue, and would be something you come across as soon as you scale (like you say, you wouldn't be able to login 50% of the time) - however where you use an alternate means of authenticating and issuing tokens (not saying it's a good idea to combine the two, it isn't), you don't really notice until you start getting failed token validation requests for things like emails on a multi-instance deployment.

**Comment by HaoK** [comment]
I won't say this was intentional so much as the data protection one was the one we had first so its always been the default, the 2fa style tokens came later so they weren't available as defaults originally.
