### ISSUE TITLE
endpoints.MapFallbackToFile(“index.html”) messes up routing in asp.net core project

### ISSUE THREAD

**Issue by Brilbroeder** [dotnet/aspnetcore#30569]
The solution has a web-api project that is also the host for a blazor-webassembly front-end.

With this config all works fine. WebApi endpoints get hit correctly when called from postman.

```
  app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
        endpoints.MapRazorPages();
    });

```
When adding a MapFallBackToFile suddenly some Api-Endpoints do not get hit anymore but serve that default file.

```
app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapRazorPages();
            endpoints.MapFallbackToFile("index.html");
        });

```
Adding a temp middleware to examine what happens clearly shows that the routing matches with the correct controller/method in the first case and use the fallback in the second case.

```
            app.Use(async (context, next) =>
            {
                var endpoint = context.GetEndpoint();
                if (endpoint is null)
                {
                    await next();
                }

                Console.WriteLine($"Endpoint: {endpoint.DisplayName}");

                if (endpoint is RouteEndpoint routeEndpoint)
                {
                    Console.WriteLine("Endpoint has route pattern: " + routeEndpoint.RoutePattern.RawText);
                }
                await next();
            });

```

**Comment by javiercn** [comment]
@Brilbroeder thanks for contacting us.

Can you produce a minimal repro project that illustrates the issue. We don't have enough details to determine if this is a bug or if there is a configuration issue in your application. Note that unless we get a repro project and detailed steps to cause the issue its really easy for us to miss something and be unable to reproduce the issue.

**Comment by Brilbroeder** [comment]
I'll try to strip the project and share it.

**Comment by Brilbroeder** [comment]
we have kicked Blazor out of the project. Still too much bedug issues. Promissing technology though, but we'll wait for the next version to try it again.

**Comment by mkArtakMSFT** [comment]
Thanks for the update. It's sad to hear that you're facing debugger issues with your Blazor apps.
It would be great, if you could file separate issues for what you've had trouble with. Most probably we already have tracking issues for these and there is a lot of ongoing work to improve that experience.

**Comment by Brilbroeder** [comment]
The biggest problem is that you do not get accurate info. I use both VS and Rider. In VS is 'crashes' on App that is null, in Rider on some property of a component that is Null. If you inspect the variables or objects that come in play at that point none of the are null. There must be a total different problem to crash.  Some were 'easy' to figure out because of the changes just made f.e. added some extra DI in services and forgot to configure DI for these extra classes. But nevertheless the error messages was totally different. If blazor development is working the same way MVC is, I definitely switch to Blazor, I'm cray about the concept.
