### ISSUE TITLE
Request.Body is empty after binfing in .Net 5

### ISSUE THREAD

**Issue by AmirHeydari** [dotnet/aspnetcore#30562]
Hi

after binding models (post,put methods), can not read Request.Body and it is empty.
As you see in this photo, body of the current request is empty

![1](https://user-images.githubusercontent.com/45232343/109617135-42e50100-7b4b-11eb-9d05-92e2686c2db4.png)
.

In previous versions such as 3.1, it was ok but in .Net 5 not.
my Startup is:

![Capture](https://user-images.githubusercontent.com/45232343/109618506-dc60e280-7b4c-11eb-8027-fbf2958374e4.PNG)

please advise me

**Comment by davidfowl** [comment]
You want to `EnableBuffering`  before your controller method (Update in this case) is invoked. You can do this in a filter (if you want it to specific to an action) or in a middleware (if you want it to run for more requests).

**Comment by AmirHeydari** [comment]
> You want to `EnableBuffering` before your controller method (Update in this case) is invoked. You can do this in a filter (if you want it to specific to an action) or in a middleware (if you want it to run for more requests).

It works.
Thanks
