### ISSUE TITLE
JsonPropertyName ignored when deserializing from POSTed json

### ISSUE THREAD

**Issue by DuelingCats** [dotnet/aspnetcore#30570]
### Describe the bug
When using the the .NET 5 JSON serialization library (System.Text.JSON), the JsonPropertyName attribute is ignored when deserializing a request. In my example, I have tested POST but it may also apply to other HTTP requests.

### To Reproduce

I have created a sample project that demonstrates this behavior. https://github.com/DuelingCats/JSONPropertyNameExample

In the example, I first call [SendSampleWithJSONPropertyName()](https://github.com/DuelingCats/JSONPropertyNameExample/blob/master/Program.cs#L39) which sends a POST request with the JSON members named "id" and "message_contents" as specified by their respective Properties in the [BasicMessage class](https://github.com/DuelingCats/JSONPropertyNameExample/blob/master/Program.cs#L83). This should deserialize correctly as the JsonPropertyName attribute specifies these names. However, it does not serialize correctly and the default value for the int and the string are provided instead.

When [SendSampleAsClassPropertyName()](https://github.com/DuelingCats/JSONPropertyNameExample/blob/master/Program.cs#L50) is called, the post request is sent with the JSON members having the same name of the class Properties - NodeId and Contents. In this case, it is deserialized correctly and the correct values are set.

Given that behavior, it appears that the JsonPropertyName attribute is ignored.

### Exceptions (if any)
None

### Further technical details
Using .NET 5, ASP.NET Core 5

.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Visual Studio Professional 2019 (16.8.6)

**Comment by pranavkm** [comment]
Your app has a reference to MVC 2.2: https://github.com/DuelingCats/JSONPropertyNameExample/blob/master/JSONPropertyNameExample.csproj#L9-L10 which defaults to using Json.NET. 

Do you have a regular web app that reproduces the same issue? If it's specific to this app, I would follow the [2.x -> 3.1 migration guides](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#framework-reference) to update it to correctly use 3.1.

**Comment by DuelingCats** [comment]
Ah I see, I thought I was referencing a newer version that used System.Text.Json by default. Thank you for pointing that out. Once I upgraded to 3.1, it is deserializing correctly.

**Comment by pranavkm** [comment]
The package along with a number of other ASP.NET Core packages were removed in favor of a `FrameworkReference` in 3.0. The migration guide lists the packages that were removed: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#remove-obsolete-package-references. https://github.com/aspnet/Announcements/issues/325 has some details about some of the reasons behind the change.
