### ISSUE TITLE
Add new HttpSysOptions to bypass UnsafeQueueUserWorkItem call and process requests on IO thread

### ISSUE THREAD

**Issue by NGloreous** [dotnet/aspnetcore#30575]
As part of the SharePoint team's migration to .NET Core, we are building a router based on http.sys queue delegation to enable migrating APIs over time. Since this router is adding latency to every request it's critical we add as little as possible. 

Currently [MessagePump.ProcessRequestsWorker()](https://github.com/dotnet/aspnetcore/blob/20b6779cf3af2fed6a8fe64a0865cfab50b776bb/src/Servers/HttpSys/src/MessagePump.cs#L179) calls ThreadPool.UnsafeQueueUserWorkItem to queue the RequestContext to a thread pool thread for processing. This is done to quickly free up the MessagePump thread to start accepting new requests. 

We'd like to add a new option in HttpSysOptions to bypass this call and directly process the request on the IO thread and then accept a new request afterwards. This should be acceptable in our scenario since request processing is very quick.

Based a prototype and some benchmarking, with the current Http.sys server implementation, we can process requests in 300 microseconds at P95. We found that ~118 microseconds come from the delay added by queueing the request to another thread. Without this call we were able to processes requests in 190 microseconds at P95.

**Comment by BrennanConroy** [comment]
We did the same thing in Kestrel in 5.0
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Servers/Kestrel/Transport.Sockets/src/SocketTransportOptions.cs#L66

**Comment by davidfowl** [comment]
```diff
public class HttpSysOptions
{
+    public bool UnsafePreferInlineScheduling { get; set; }
}
```
