### ISSUE TITLE
[Signalr-Cpp]Please make constructor of `hub_connection` `public`

### ISSUE THREAD

**Issue by albyho** [dotnet/aspnetcore#30572]
We need to create a instance of `hub_connection` as a filed in a `class`.

**Comment by BrennanConroy** [comment]
What's wrong with using the `hub_connection_builder`? Using the builder is how all implementations of the client create a connection.

**Comment by albyho** [comment]
> What's wrong with using the `hub_connection_builder`? Using the builder is how all implementations of the signalr clients create a connection.

`hub_connection_builder` creates 
`hub_connection` instance in stack and it’s not copyable.

**Comment by BrennanConroy** [comment]
`hub_connection` does have a move constructor, so you can move it into a class for storage currently.

We are experimenting with returning a `shared_ptr<hub_connection>` in https://github.com/aspnet/SignalR-Client-Cpp/pull/36 and that's probably the direction we'll continue on.
