### ISSUE TITLE
HostingEventSource uses EtwSelfDescribingFormat instead EtwManifestFormat

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#30584]
`HostingEventSource`, `HttpConnectionsEventSource`, and `ConcurrencyLimiterEventSource` used the `EtwSelfDescribingFormat` instead of the `EtwManifestFormat`. Surprisingly `KestrelEventSource` does not not have the same issue.

It looks like this change was inadvertently introduced as part of a [previous change](https://github.com/dotnet/aspnetcore/pull/10884/) when switching to a different EventSource ctor that changed the behavior.

I haven't profiled this, but I assume there should be some minimal overhead observed on every `WriteEvent` call when ETW is enabled. This doesn't impact EventPipe profiling scenarios.

To quote @josalem 

> Manifest mode generates the manifest on initialization by reflecting over the methods on the EventSource and writing an XML file into memory.  That file is sent whenever someone requests it and when someone starts listening to that source. It's only generated once. Self-describing creates a per-event metadata every time you send an event and attempts to send it with the event.  EventPipe works some magic to reduce the amount of data sent, but EventSource still attempts to generate it.

A simple fix would be
```diff
namespace Microsoft.AspNetCore.Hosting
{
    internal sealed class HostingEventSource : EventSource
    {
        // Used for testing
        internal HostingEventSource(string eventSourceName)
-            : base(eventSourceName)
+            : base(eventSourceName, EventSourceSettings.EtwManifestEventFormat)
        {
        }
    }
}
```

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/30629

**Comment by benaadams** [comment]
Should they be EtwSelfDescribingFormat anyway?

From https://github.com/dotnet/runtime/issues/27621#issuecomment-431236134

> ManifestBuilder functionality is largely a back-compat artifact for correct interoperation with legacy win7 and win8 era ETW readers. For any new usage he recommends customers create EventSource with the Self describing events. 

and https://github.com/dotnet/runtime/issues/27621#issuecomment-431393221

> If you wish to use complex types (that is something besides primitives, strings and DateTime), then you need to use the EtwSelfDescribingFormat flag when creating the EventSouce. This is very easy. In your TestEventSource class simpy add
>
> `private TestEventSource() : base(EventSourceSettings.EtwSelfDescribingEventFormat) { }`
>
> Things should work from there. We recommend people do this in general. We would have made this the default, except is is a breaking change for people using EventSource in manifest based scenarios.

**Comment by shirhatti** [comment]
> Should they be EtwSelfDescribingFormat anyway?

If I understood correctly, as long as we don't have non-primitives types emitted we should be okay.

Re-opening this issue to verify that is indeed what's happening

**Comment by benaadams** [comment]
Other than comments in https://github.com/dotnet/runtime/issues/27621#issuecomment-431236134 saying `EtwManifestEventFormat`  legacy win7 and win8 backcompat and `EtwSelfDescribingEventFormat` should have been the default

The docs do also suggest Self Describing is preferred? https://docs.microsoft.com/en-us/windows/win32/tracelogging/trace-logging-about

> TraceLogging is the new Windows 10 event tracing for user-mode applications and kernel-mode drivers. TraceLogging is a format for self-describing Event Tracing for Windows (ETW). TraceLogging builds on Event Tracing for Windows (ETW) and provides a simplified way to instrument code.
>
> TraceLogging offers the simplicity of Windows software trace preprocessor (WPP) with the added benefit of being able to include structured data with events, the capability of correlating events, and all without requiring a separate instrumentation manifest XML file. Events are self-describing which means that a binary containing the instrumentation manifest does not need to be registered on the system in order to use the Trace Data Helper (TDH) APIs to decode and show events.
> ...
> TraceLogging builds upon ETW but introduces several important improvements:
>
> * Tracing an event is as simple as an API call.
> * Events are self-describing and do not require any additional binaries containing the compiled event manifest to interpret the event. All the metadata about the event is recorded in the event.
> * Activities inside a single process can be easily expressed through start and stop events.
> * TraceLogging is compatible with existing instrumentation support. The new ETW APIs continue to support the old providers. You can invest in the new ETW APIs for strategic scenarios while leaving your old instrumentation points as they are.
> * TraceLogging offers the same event tracing API for Windows 10, Xbox One, and Windows 10 Mobile.
> * TraceLogging APIs are accessible from C, C++, .NET, and Windows Runtime.

**Comment by benaadams** [comment]
Raised issue https://github.com/dotnet/runtime/issues/49410

**Comment by shirhatti** [comment]
I should have mentioned my motivation for making the change in the first place was your linked investigation. Assuming we move manifest generation in to source generator., there's no startup penalty or penalty on every invocation of WriteEvent (with ETW, EventPipe is always self-describing anyways).

**Comment by benaadams** [comment]
> Assuming we move manifest generation in to source generator.

Priority was dropped on it 😢 https://github.com/dotnet/runtime/issues/43390#issuecomment-791076651

**Comment by shirhatti** [comment]
Unfortunately, I'm aware (and the instigator😅). Manifest generation is still a possibility, but it's the serializer/de-serializer generation that definitely not happening

**Comment by benaadams** [comment]
A whole lot of startup going into generating EventSource manifests and Guids etc for a standardish ASP.NET Core app with ApplicationInsights, e.g. this is https://themesof.net/

![image](https://user-images.githubusercontent.com/1142958/110574795-b4c5d780-8155-11eb-9678-6673ba7f6453.png)

**Comment by shirhatti** [comment]
Have you measured the per `WriteEvent` call overhead when ETW is enabled? If not, I'll probably profile something like this later tomorrow

```csharp
using System.Diagnostics.Tracing;

for (var i = 0; i < 10000; i++)
{
    MyEventSource.Log.MyEvent();
}

internal class MyEventSource : EventSource
{
    public static readonly MyEventSource Log = new MyEventSource();
    // public MyEventSource() : base("MyEventSource", EventSourceSettings.EtwManifestEventFormat)
    public MyEventSource() : base("MyEventSource", EventSourceSettings.EtwSelfDescribingEventFormat)
    { }
    [Event(1, Level = EventLevel.LogAlways)]
    public void MyEvent()
    {
        WriteEvent(1);
    }
}
```

**Comment by benaadams** [comment]
For https://themesof.net/ looks like 27 `EventSource`s are created on startup, most of them probably just to check `.Log.IsEnabled()` and get false back... 😅

![image](https://user-images.githubusercontent.com/1142958/110577951-a2e73300-815b-11eb-8141-c2671ac6fcff.png)

**Comment by benaadams** [comment]
> Have you measured the per `WriteEvent` call overhead when ETW is enabled?

No, would be interesting to see the difference

**Comment by shirhatti** [comment]
Unfortunately, this slipped through the cracks for 6.0. Given that the expectation is that in 7.0, we have source generators for manifest generation, it is highly unlikely that we'd want to revert this change.

As such, I'm closing this issue despite knowing there is small impact on process start time for 6.0
