### ISSUE TITLE
System.Text.Json JsonElement is not serialized properly with messagepack in SignalR

### ISSUE THREAD

**Issue by Irfan1314** [dotnet/aspnetcore#30585]
I have a project in asp .net core 3.1. there is a view model, similar to that shown below, in a controller.
`public model sample{
      public string prop1 {get; set;}
      public int prop2 {get; set;}
      public object prop3 {get; set;}
}`

when a request is hit on the controller the prop3 becomes an instance of JsonElement. This object is passed to a client method using signalr with MessagePack protocol. At client side the object is shown as {ValueKind = "Object"} which is the valuekind property of jsonElement, but there is no way to read the data passed within the JsonElement. i have tested with Json protocol and it works fine (gets JsonElement as an anonymous object at client side). Is there a workaround to make this work with MessagePack.

asp .net core v: 3.1
signalr.protocols.messagePack v: 3.1.2

**Comment by davidfowl** [comment]
The message pack serializer doesn't support JsonElement. I believe you can write an `IMessagePackFormatter`  to plug in your own serializer logic (see https://github.com/neuecc/MessagePack-CSharp#main-extension-point-iformatterresolver).

I'd also file an issue here https://github.com/neuecc/MessagePack-CSharp (this is the library we use) and request this is supported. Or change the type so it's not JsonElement

**Comment by Irfan1314** [comment]
`change the type so it's not JsonElement`
unfortunately different types of objects are passed through prop3, hence can't create a custom object definition for prop3. Also when i alter the serialization library from system.text.json to newtonsoft.json in .net core, the object is of type JObject at runtime which is not supported when using messagePack protocol.

`I'd also file an issue here https://github.com/neuecc/MessagePack-CSharp (this is the library we use) and request this is supported.`
please let me know their reply.

If i am creating a custom `IMessagePackFormatter`, does it need to be plugged in at the backend as well as the frontend side? At frontend i am using typescript.

**Comment by BrennanConroy** [comment]
> If i am creating a custom `IMessagePackFormatter`, does it need to be plugged in at the backend as well as the frontend side? At frontend i am using typescript.

frontend will just be an object that you can access arbitrary properties on. Configuration will need to be done on the backend.




> `I'd also file an issue here https://github.com/neuecc/MessagePack-CSharp (this is the library we use) and request this is supported.`
> please let me know their views on this.

We were suggesting you file an issue on that repo if you want JsonElement to be supported.
