### ISSUE TITLE
Enable HTTPS in ASP.NET Core application in AWS EKS cluster

### ISSUE THREAD

**Issue by alok00188** [dotnet/aspnetcore#30586]
I have an EKS cluster running multiple microservices developed in ASP.NET Core. I am looking to use HTTPS even for internal service to service communication.

I have used cert-manager to create the SSL certificate with AWS EKS localhost-dns and used that in ASP.NET Core application successfully. But after using this SSL certificate I am able to use my API with "-k" insecurity feature as without "-k" it is giving local issuer certificate error whereas I have already updated my ca.crt file in docker/pod system by referring this link. https://www.nowherelan.com/2011/12/28/adding-additional-ssl-ca-certificates/

Generally, the same approach is working fine in windows and mac but in Linux, it is giving the error.
So, kindly suggest any solution for it.

_ERROR: curl: (60) SSL certificate problem: unable to get local issuer certificate More details here: https://curl.haxx.se/docs/sslcerts.html curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above._

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use certs. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.

If you think there is a bug on the server side with it not using the cert correctly, we suggest filing an issue on the https://github.com/dotnet/runtime repo.
