### ISSUE TITLE
SystemTextJsonInputFormatter does not set ModelStateEntry.RawValue and ModelStateEntry.AttemptedValue

### ISSUE THREAD

**Issue by xpl0t** [dotnet/aspnetcore#30588]
### SystemTextJsonInputFormatter does not set ModelStateEntry.RawValue and ModelStateEntry.AttemptedValue
When I try to acess the RawValue/AttemptedValue of a ModelStateEntry the value is always null.

````csharp
public class ValidationFilterAttribute : ActionFilterAttribute, IOrderedFilter
{
  public int Order { get; } = int.MinValue;

  override public void OnActionExecuting(ActionExecutingContext context)
  {
    if (!context.ModelState.IsValid)
    {
      ModelStateEntry entry = context.ModelState.ElementAt(0).Value;
      var attemptedVal = entry.AttemptedValue;
      var rawVal = entry.RawValue; // Always null
      var attemptedVal = entry.AttemptedValue; // Always null
      context.Result = new OkObjectResult(rawVal);
    }
  }
}
````

### To Reproduce
Reproduction repo: https://github.com/xpl0t/input-formatter-bug

This project implements a basic **ActionFilterAttribute** in the file `ValidationFilter.cs` , which checks if the passed input model is valid. If not it sends back an OK response with the **RawValue** property of the failing **ModelStateEntry**. This always results in an **204 No Content**, because the **RawValue**/**AttemptedValue** properties are not set on the **ModelStateEntry**.

### Workaround

Overriding SystemTextJsonInputFormatter like in this Stackoverflow answer: https://stackoverflow.com/a/65684952/14981939

### Further technical details
- ASP.NET Core version **3.1**

**Comment by jak-hammond** [comment]
I've spent the best part of an afternoon looking into this and finally found this post, incredibly frustrating behaviour for an action filter that I am attempting to write. 

I can see the model being set fine on the `ActionArguments` property, but due potentially differing names of the models, I had wanted to use the `ModelState` directly if what I was looking for wasn't immediately available in those arguments. When there was a validation error, the model state was being correctly set, but when the model was valid, the results enumeration was returning nothing. 

![image](https://user-images.githubusercontent.com/664193/112038120-6263be00-8b3a-11eb-8172-89fab98cee6b.png)

There was the same behaviour it seemed when trying to use `AddNewtonsoftJson()` middleware as well fwiw.

**Comment by pranavkm** [comment]
`RawValue` and `AttemptedValue` are only available on model bound objects i.e values bound from query, routes, or form posts. MVC populates these entires as it encounters values for individual property or collection entry.

MVC deserializes a JSON or XML body in entirety and does not observe individual items. Consequently entries for these are not populated. If you must, you could consider using reflection like the StackOverflow sample from the initial report does: https://stackoverflow.com/questions/65665384/net-core-api-cannot-access-original-value-on-model-validation-failures/65684952#65684952.

**Comment by jak-hammond** [comment]
Sorry, but I still think the behaviour is confusing, when a model binding error occurs, the properties are populated by MVC in the action filter context;
![image](https://user-images.githubusercontent.com/664193/112039820-609afa00-8b3c-11eb-92d7-9e25a54c293b.png)

Yet when the model is valid, it is empty;
![image](https://user-images.githubusercontent.com/664193/112039971-87f1c700-8b3c-11eb-98ed-6fa70fb0bbf0.png)

If the items are being populated when an error is encountered then it must still be taking each item account for validation during deserialization, so in the case where there are no errors, why not still populate the state?

**Comment by pranavkm** [comment]
> If the items are being populated when an error is encountered then it must still be taking each item account for validation during
