### ISSUE TITLE
New Discussions link is broken (404) on this Repo.

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#30590]
In the issue type choose list (see screenshot) there is a "Discussions" option. But the button click redirects to a page which does not exists: https://github.com/dotnet/aspnetcore/discussions/new 

![image](https://user-images.githubusercontent.com/7632824/109800651-c0794180-7c1d-11eb-98f8-9f4070273c08.png)

**Comment by javiercn** [comment]
@majorimi thanks for reporting this.

We explicitly disabled discussions as they were really hard to triage compared to issues. We recommend that you start with opening an issue so that we can track the work there.

**Comment by blowdart** [comment]
https://github.com/dotnet/aspnetcore/pull/30596 will address this.

**Comment by majorimi** [comment]
Yes I think removed link is better than 404. Thanks I will open an issue.
