### ISSUE TITLE
Create Blazor Server project, delete '@page' one by one and then type "@pa",  press Enter to complete intellisense, it meet error "The name 'xxx' does

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30601]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Create-Blazor-Server-project-delete-p/1348833)._

---
1. File > New Project > Blazor Server App, give a name > Create > .NET 5.0 with No Auth, click Create.
2. Wait for project package restore completed, open Index.razor file under Pages folder.
3. Verify the color of "@page" at the start of page. Then put the cursor after page and then press Backspace to delete "@page" one character by one character.
4. Then type "@pa" faster and verify the intellisense list contains "page", press Enter key to complete it, it shows an error "The name 'pageag' does not exist in the current context" in Error List.

---
#### Feedback Bot on 2/24/2021, 10:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/3/2021, 09:26 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
This no longer repros on latest VSMain builds.
