### ISSUE TITLE
Close all tabs but this - Error activating language server

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30602]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Close-all-tabs-but-this---Error-activati/1349158)._

---
[severity:It bothers me. A fix would be nice]
1. Open lots of tabs including some .razor/.razor.cs files
2. Set .razor file as active tab
3. Close all tabs but this
4. Throws "There was an error activating the remote language server, Razor C# Language Server Client

---
#### Feedback Bot on 2/25/2021, 00:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/3/2021, 09:27 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Hello, does this happen for you every time?

@dibarbet could you take a look at the associated VSTS logs to see if this is the error activating case that we're trying to service?
