### ISSUE TITLE
Auto-Complete Fails in Visual Studio when selecting an override with Intellisense

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/aspnetcore#30618]
(Blazor-WASM)

Auto-Complete Fails in Visual Studio when selecting an override with Intellisense

**Steps to Reproduce**:
1. Create a new Blazor WASM Project
2. Open `index.razor`
3. Add the code-snipped below
4. In the blank line after the closing bracket for `Foo`, enter `override onin`
5. Press TAB

**Expected Behavior**
The override for `OnInitialized` will be added
`OnInitialized` is no longer an option in Intellisense when you try again

**Actual Behavior**
The text you entered is deleted.

Note that removing the function and performing the same steps with an empty code block works as expected.

```blazor
@code
{
  void Foo()
  {
    Console.WriteLine("Foo"); 
  }

}
```
![image](https://i.imgur.com/AFCZxBp.gif)

**Comment by NTaylorMullen** [comment]
@allisonchou assigning to you to validate that this is fixedin the latest experimental Razor editor

**Comment by allisonchou** [comment]
Validated that this is now fixed in the latest IntPreview.

@RobertBouillon From your screenshot, it looks like you're using the old Razor editor. If you go to Tools->Options->Preview Features and check the 'Enable experimental Razor editor' option, you should see the fix for this out soon.
