### ISSUE TITLE
[Razor] Incorrect error notification

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#30619]
Hi,

After upgrading to VS 16.9.0 I've encountered the following error in the experimental razor editor:

![image](https://user-images.githubusercontent.com/29497049/109875669-5caf4280-7c36-11eb-8942-586905436d14.png)

Thank you for your attention.

**Comment by NTaylorMullen** [comment]
Thanks for trying out the new Razor editor @daniel-p-tech! This should be fixed in the 16.10 release (preview 1 if you're trying previews out).
