### ISSUE TITLE
Code execution should wait until the debugger is attached when debugging

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/aspnetcore#30620]
### Steps To Reproduce
1. Create a new Blazor WASM application
2. Add the code below to the `index.razor` page
3. Place a breakpoint anywhere in the `OnInitializedAsync` method
4. Debug the application

### Expected Results
The application should start with the current executing line in `OnInitializedAsync`

### Actual Results
The application starts, skipping the breakpoint. The breakpoint can later be hit by navigating away from and returning to the page.

```csharp
@code
{
  protected override Task OnInitializedAsync()
  {
    return base.OnInitializedAsync();
  }
}
```

![image](https://user-images.githubusercontent.com/612152/109876244-8faa0400-7c3f-11eb-8767-e92476e5e68b.png)

**Comment by lewing** [comment]
@thaystg Is this still an issue?  I think we resolved it with some of the loading event changes?

**Comment by thaystg** [comment]
This is fixed. I don't know exactly which change fixed it, but it's fixed.
