### ISSUE TITLE
Blazor WASM does not break on exception

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/aspnetcore#30628]
### Describe the bug
When debugging Blazor WASM projects, execution should stop when an exception occurs and break of the exception in the code. This is the expected behavior when debugging and should be the default behavior of a Blazor project.

### To Reproduce
1. Create a new Blazor WASM project
2. Update the `OnInitializedAsync` method in the `FetchData.razor` page with code provided below
3. Start debugging by pressing F5
4. Click "Fetch Data" button on the web page

### Expected Results
Visual Studio should break on FetchData.razor:42

### Actual Results
An exception is displayed in the console window of Chrome

#### FetchData.razor
```csharp
  protected override async Task OnInitializedAsync()
  {
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("Bad URI");
  }
```

**Comment by captainsafia** [comment]
It looks like you might be running into a variant of https://github.com/dotnet/runtime/issues/42326 that we are tracking for 6.0.0. Closing this as a dupe.
