### ISSUE TITLE
Get Referrer of IStatusCodeReExecuteFeature

### ISSUE THREAD

**Issue by glenn2223** [dotnet/aspnetcore#30648]
### Is your feature request related to a problem? Please describe.
I am trying to find the page that caused the (e.g. 404) to happen but all that's returned is the original path (as per below)

```c#
var feature = HttpContext.Features.Get<IStatusCodeReExecuteFeature>();

feature.OriginalPathBase;
feature.OriginalPath;
feature.OriginalQueryString;
```

### Describe the solution you'd like
I'd also like the Referer information so I can track the page that has caused the misdirection/error. This way I can better attempt to replicate steps that caused the issue and also find sources of incorrect links.

Possibly something like the below

```c#
feature.ReferrerPathBase;
feature.ReferrerPath;
feature.ReferrerQueryString;
```

### Additional context
N/A

**Comment by Tratcher** [comment]
The referrer would be available in the request headers: `HttpContext.Request.Headers[HeaderNames.Referer]`. The runtime doesn't have access to any additional information.

**Comment by glenn2223** [comment]
Sorry forgot to expand/explain

All that's available in the header is the domain (pathBase) no path or query string

**The Issue**
There's a page at `domain.com/WorkingPage?ImA=QuerystringValue`  
It has a link to `domain.com/BrokenPage`  
Using the below, breifed, config all I get in the header is `..., "headers": { ..., "Referer": [ "domain.com" ], ... }, ...`

```c#
if (!development)
{
    app.UseExceptionHandler("/Error");
}
app.UseStatusCodePagesWithReExecute("/Error", "?handler=StausCode&cd={0}");
```

**Comment by Tratcher** [comment]
The information you want is only available on the client, not on the request/server.

**Comment by glenn2223** [comment]
Of course it is 🤦‍♂️

Sorry, been one of those weeks. Thanks for indulging my idiocy. I was just getting all mixed because of chromium's referrer-policy changes
