### ISSUE TITLE
Experimental Razor editor for Visual Studio - incorrect code formatting for 'if statement'

### ISSUE THREAD

**Issue by Jarek300** [dotnet/aspnetcore#30649]
Visual Studio 2019, 16.9.0.

Experimental Razor editor, incorrect code formatting:

```
                    @if (Dto.Info.Length > 0)
                    {
                    <small class="form-text text-muted">
                        <span>@Dto.Info</span>
                    </small>
                    }

```

Standard Razor editor, correct code formatting

```
                    @if (Dto.Info.Length > 0)
                    {
                        <small class="form-text text-muted">
                            <span>@Dto.Info</span>
                        </small>
                    }

```

**Comment by Jarek300** [comment]
No problem.  The name of the document is InputBoxForm.razor. I attach more razor files broken by the new editor. Compare files in Forms-OldEditor.zip and Forms-NewEditor.zip to see what is broken. 

[Forms-OldEditor.zip](https://github.com/dotnet/aspnetcore/files/6114351/Forms-OldEditor.zip)
[Forms-NewEditor.zip](https://github.com/dotnet/aspnetcore/files/6114353/Forms-NewEditor.zip)

I'm afraid that you can't reproduce the problems using my files. Formating seems to work only if all dependencies are available.

**Comment by NTaylorMullen** [comment]
> I'm afraid that you can't reproduce the problems using my files. Formating seems to work only if all dependencies are available.

Oh really??? That's definitely odd, the only sort of semantic understanding that could influence formatting would be components hmm

**Comment by NTaylorMullen** [comment]
@davidwengier fixed this as part of https://github.com/dotnet/aspnetcore/issues/30382
