### ISSUE TITLE
SignalR Java SDK does not expose or honor 429 responses during negotiate

### ISSUE THREAD

**Issue by aaronoe** [dotnet/aspnetcore#30659]
### Describe the bug
The SignalR Java SDK does not honor or expose (beyond a RuntimeException) http response codes from the negotiate call such as 429. To work around the issue we have to parse the error message from the thrown RuntimeException and manually handle the error codes which shouldn't be necessary since negotiate is an implementation detail of the SDK.

### To Reproduce

Have a SignalR service return status code 429 during negotiate and observe the client behavior when calling `hubConnection.start()`.

### Exceptions (if any)

The exception is thrown here:
https://github.com/dotnet/aspnetcore/blob/58e9360fcbbf4d0b6c7a2fb3afa11b060373f326/src/SignalR/clients/java/signalr/core/src/main/java/com/microsoft/signalr/HubConnection.java#L170-L173

### Further technical details
- SignalR Java 5.0.3

**Comment by BrennanConroy** [comment]
Sounds like a nice enhancement. We use an exception on the .NET side that contains the status in separate fields.
