### ISSUE TITLE
Support validation attributes on records 

### ISSUE THREAD

**Issue by DaveSenn** [dotnet/aspnetcore#30650]
### Is your feature request related to a problem? Please describe.
I tried to use validation attributes on a C# 9 record but it diden't work (ASP.NET Core .NET 5). 

Namly I tried to use `StringLengthAttribute`:
```
public sealed record MyRecord( [StringLength( 64 )] String MyString );
public sealed record MyRecord( [field: StringLength( 64 )] String MyString );
public sealed record MyRecord( [property: StringLength( 64 )] String MyString );
```

I got the following error message:

```
Record type '' has validation metadata defined on property '' that will be ignored.
'' is a parameter in the record primary constructor and validation metadata must be associated with the constructor parameter.
```

### Describe the solution you'd like
I would like to be able to use validation attributes on record types using the short "constructor-only-syntax".

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
