### ISSUE TITLE
Blazor Server-Side Some Images Initially Report:  "Failed to load resource: the server responded with a status of 403 "

### ISSUE THREAD

**Issue by JasonIrby** [dotnet/aspnetcore#30658]
I'm running into a weird problem.  It seems to be related to Balzor server-side.

I have a Blazor Server-Side app. One page has a lot of fairly small sized images on it. They aren't big, but there are a lot.

The first time a user hits the page, often a random number of those images will fail to load (just box with red X) and in the browser console I see: "Failed to load resource: the server responded with a status of 403 ".

That's weird because I know the images are in the right place. If I right click on the image placeholder (empty box with a red X) and select "open image in new tab", it works. So the images are on the server and in the proper path.
If I reload the page, eventually all the images will render. If I clear my internet cache of images, the behavior repeats.

It's almost as if Blazor server-side will only spend so long transferring the images for the loading page and will just quit and serve an incomplete page? But then the first set of images are cached so if I reload it has time to transfer the remaining images? Just guessing.  Runs out of time or number of image limit?

I haven’t reproduced this running locally, only on my published site. So first I suspected my Web Host  acting weird.  I have another domain with them that I have not deployed Blazor to.  So I created a plain HTML version of the page with all the same images and uploaded that to see if another non-Blazor domain on the same web host with the same images would reproduce the problem.  That works fine.

So it seems to be something related to the Blazor server rendering the page.

Is there some configuration setting I can tweak to avoid this?  Is this some kind of time-out issue?

Thanks in advance.

**Comment by JasonIrby** [comment]
I don't know if this helps, but looking at the browser console I noticed something that looked weird to me (though I am not a expert at interpreting the console):
I this screen notice in the network tab, the images that are failing are showing type "text/image".  They are not.  They are png.
Below that, I expanded the verbose console error for one of the failed images in case that helps.  

[https://www.dropbox.com/s/lhb68fh90wzd3j2/browserConsole.png?raw=1](url)

If I click on the row of one of the failed images it shows:
[https://www.dropbox.com/s/po4hr75lvsuoq28/browserConsole2.png?raw=1](url)

After reload, the images it couldn't load, now load fine (because initial images are already cached?):
[https://www.dropbox.com/s/l981py2q9u4o6e5/browserConsole3.png?raw=1](url)

This site is https.  Could that be involved?

**Comment by JasonIrby** [comment]
Well, I disabled the SSL cert for my site and I haven't been able to reproduce the problem again so far.  I'll keep trying.

**Comment by javiercn** [comment]
@JasonIrby thanks for contacting us.

The issue that you are experiencing seems to be related to your environment. Blazor server doesn't do anything special with images, so it's unlikely this issue is related to Blazor.

Blazor server doesn't transfer any image to the browser or anything similar, at most I imagine you are adding an `img` element to the page and the browser is downloading the image. That's not something Blazor server is involved with.

**Comment by JasonIrby** [comment]
It certainly involves my environment.  It seems to be caused by having a SSL cert on my site. (Which explains why I couldn't reproduce running locally.)

However, in the image: https://www.dropbox.com/s/lhb68fh90wzd3j2/browserConsole.png?raw=1
every single line in the call stack is in blazor.server.js. 
So it seemed involved as well.

**Comment by javiercn** [comment]
@JasonIrby that seems to be an artifact of Blazor being the one that creates the img element and inserts it on to the DOM. I think that is just pointing out the "source" in code that triggers the error loading the image

**Comment by JasonIrby** [comment]
Thanks for your patience.  

I believe what you are saying is correct.  
I'm wondering if it is related to:
https://really-simple-ssl.com/knowledge-base/403-errors-images-ssl-activated/
But I am confused as to why it would think the DOM being constructed by blazor.server.js is a different site.

I'll research more on Hot Link Protection.
