### ISSUE TITLE
Can't create staticfile directory automatically

### ISSUE THREAD

**Issue by wuyuansushen** [dotnet/aspnetcore#30675]
**Visual Studio Version**: 16.8.6

**Summary**: While publishes the project with the way of Directories and uses additional `app.UseStaticFiles` in Startup.cs on asp.net core project, The staticfile directory wouldn't be added to the published directory. Directories needed to be created by myself.

**Steps to Reproduce**:

1. Create an **ASP.NET Core** project with Razor Pages

2. Add following code in **Startup.cs** file
```            string locationPath = env.ContentRootPath + @"/Storage";
            var fileLocation = new PhysicalFileProvider(locationPath);
            app.UseStaticFiles(new StaticFileOptions() { RequestPath = (PathString)"/ftp", FileProvider = fileLocation, ContentTypeProvider = ExtProvider });
            app.UseDirectoryBrowser(options: (new DirectoryBrowserOptions() { RequestPath = "/ftp", FileProvider = fileLocation }));
```

3. On top menu, click _Build--Pubish <ProjectName>--Publish FolderProfile--Publish_

**Expected Behavior**: Create the **static file folder** named _Storage_ automatically

**Actual Behavior**: Not Create.

**User Impact**: Use `dotnet` to run <Project>.
dll, it will cause IO Exception.

![1](https://user-images.githubusercontent.com/43259764/109804950-d27ad480-7c5d-11eb-8fb1-51e1a43289df.png)

**Comment by BrennanConroy** [comment]
This is expected behavior, you should add a sentinel file so the directory will be deployed with the app.

**Comment by halter73** [comment]
Or just call Directory.CreateDirectory.

**Comment by wuyuansushen** [comment]
> This is expected behavior, you should add a sentinel file so the directory will be deployed with the app.

@BrennanConroy What's the sentinel file? How do I add this file? I can't find any reference or information about this concept...

**Comment by BrennanConroy** [comment]
> What's the sentinel file?

It's a concept for a placeholder file.

> How do I add this file?

Create the directory locally and put a file in the directory. Could be `empty.txt` or `.sentinel`, etc.

**Comment by wuyuansushen** [comment]
> > What's the sentinel file?
> 
> It's a concept for a placeholder file.
> 
> > How do I add this file?
> 
> Create the directory locally and put a file in the directory. Could be `empty.txt` or `.sentinel`, etc.

@BrennanConroy OK, copy that. Thanks a lot.
