### ISSUE TITLE
Add linker-friendly Roslyn source gen version of RequestDelegateFactory

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#30670]
We should add a Add linker-friendly Roslyn source gen version of [RequestDelegateFactory](https://github.com/dotnet/aspnetcore/blob/8cf98856bb96c7aad8373ae5b1fa6e7f021f649e/src/Http/Http.Extensions/src/RequestDelegateFactory.cs) similar to what's [in uController](https://github.com/davidfowl/uController/blob/aa8bcb4b30764e42bd72d326cb2718a4d4eaf4a9/src/uController.SourceGenerator/uControllerGenerator.cs)

**Comment by BrennanConroy** [comment]
Triage: not doing it for now
