### ISSUE TITLE
Dotnet Run not working like expected

### ISSUE THREAD

**Issue by joseescalon96** [dotnet/aspnetcore#30678]
I am in Mac OSX. I started a new project on Visual Studio 2019 in an ASP.NetCore Web Application. The dotnet build command and the dotnet run command are working, but when I try to go on the localhost:5000 port it says the site cant be reached. 

This is the dotnet run statement:

Escalons-iMac:DutchTreat programacion$ dotnet run
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/programacion/Desktop/Dotnet-App/DutchTreat/DutchTreat

The thing is it then redirects me to a welcome page of Net.Core and I dont know how to fix it. 

Also i get an error that says: Faile to bind to address https://127.0.0.1:5001: address already in use. Here is the code of my program.cs, the error is in the CreateHostBuilder.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace DutchTreat
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}

**Comment by BrennanConroy** [comment]
2 things, you probably have UseHttpsRedirect in your startup which is causing http://...5000 to redirect to the broken port, and you need to fix the 5001 binding issue. Find what is binding to 5001 and stop it, or change the port you're binding to.
