### ISSUE TITLE
Blazor server-side User Activity logging

### ISSUE THREAD

**Issue by RavindraBarapatre** [dotnet/aspnetcore#30681]
Hello,

We are using Blazor server.
As per standard documentation, middleware's not used in Blazor pipeline.

Is there any way to log the user's requests activity in Blazor server app?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The requests fired from client in Blazor Server application (for communication to the server) are not the usual HTTP requests, rather WebSocket ones. Those aren't going through the standard middleware pipeline. So it's not clear what specific logging are you interested in?

**Comment by RavindraBarapatre** [comment]
Thanks for response.

I want to trace all User activity:
Page visited and any operation performed like search, add, edit, delete operations using Generic implementation so, I don't need to write log statement in every method for user activity.

is it possible trace all SignalR web socket request? and log them in formatted way.

**Comment by mkArtakMSFT** [comment]
Thanks for the additional details.
The information you can get on the SignalR level will be too low level and you won't be able to know what that data actually means. So you will have to have explicit log statements for all the activity you'd like to log.
