### ISSUE TITLE
add ability to specify domain_hint for MSAL AD B2C

### ISSUE THREAD

**Issue by Ma3yTa** [dotnet/aspnetcore#30688]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/direct-signin?pivots=b2c-user-flow
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-generic-openid-connect#response-mode

**Comment by javiercn** [comment]
@Ma3yTa thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/29440
