### ISSUE TITLE
Passing JavaScript reference from JS to dotnet and back doesn't seem to work

### ISSUE THREAD

**Issue by d-p-y** [dotnet/aspnetcore#30687]
### Describe the bug

Hi,
I'm not sure if it is a bug or missing feature. In Blazor WASM project I'm using JS<->dotnet interop to pass `document.body` from JS to dotnet. This *seems* to work as I get something that is not null. Afterwards I try to pass that reference back to JavaScript. I expect that in JavaScript it will be indistinguishable from `document.body`. Unfortunately, I get something that looks like simplest empty JS Object instead.

### To Reproduce

I have dedicated repository for this case
https://github.com/d-p-y/blazor-webassembly-as-javascript-replacement

Basically I run minimalistic blazor wasm project made of default `blazorwasm` template. I execute it in Chrome with its Console panel open. As described in readme.md I expect to see 
```success: can use bodyAsObj as opaque reference to HTMLElement. Got body.id value=1```
but I see 
```failed: can not use bodyAsObj as opaque reference to HTMLElement because JS gets something that is not an original reference having id property```

### Further technical details

`dotnet --version` is `5.0.103`

`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: `Visual Studio 2019 Community Version 16.8.6`

**Comment by javiercn** [comment]
@d-p-y thanks for contacting us.

https://github.com/d-p-y/blazor-webassembly-as-javascript-replacement/blob/master/Program.cs#L57 <- That's not a JSObjectReference

**Comment by d-p-y** [comment]
@javiercn thank you for answer. OK so basically when I need to pass some JavaScript reference from JS to dotnet WASM what I need to do is to use `Microsoft.JSInterop.IJSObjectReference` instead of `System.Object` ?
I've applied such change to repo above and I get correct result (in Chrome console `document.body === p0` is true in `evalDebug()`). Thank you!

The only thing I don't understand is: 
> We also don't support accessing properties directly like document.body we will try to invoke them which is certainly not what you want.

Do you mean that when `IJSInProcessRuntime.Invoke<IJSObjectReference>("method")` is called then dotnet WASM runtime will additionally try to invoke result when it 'sees' it is invocable?

**Comment by javiercn** [comment]
@d-p-y No.

I mean that if you try to do `JS.Invoke("property", object)` it will not work I believe

**Comment by d-p-y** [comment]
@javiercn ok clear! thank you very much.
