### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Analyzers does not check EndpointRouting = false being set in methods called from inside ConfigureServices

### ISSUE THREAD

**Issue by scottgorlick** [dotnet/aspnetcore#30698]
### Describe the bug
Microsoft.AspNetCore.Mvc.Analyzers does not check EndpointRouting = false being set in methods called from inside ConfigureServices and emits warning MVC1005 for a Startup that has ConfigureServices method calling discrete methods to do service setup.

I strong suspect that the Roslyn analyzer is not recursing through method calls and only considers the ConfigureServices method as a valid location to set this value.

### To Reproduce
``` bash
$ dotnet new mvc -n repro
```
in startup.cs, change the ConfigureServices method as such:

``` C#
        public void ConfigureServices(IServiceCollection services)
        {
            SetupStuff(services);
        }

        private static void SetupStuff(IServiceCollection services)
        {
            services.AddControllersWithViews(o => o.EnableEndpointRouting = false);
        }
```

### Exceptions (if any)
no exceptions, but MVC1005 is emitted after build.

### Further technical details
- ASP.NET Core version
issue exists observed using both 3.1 and 5

- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.200   
 Commit:    70b3e65d53

Runtime Environment:  
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2019 - 16.9.0
VSCode - 1.53.2
Terminal

**Comment by pranavkm** [comment]
We intentionally did something simple to cover the common case of having configuration in ConfigureServices. For uncommon cases, you should continue to receive a runtime error if you a have your startup misconfigured.

**Comment by scottgorlick** [comment]
It is common, in my experience, to have method calls for configuration/setup in the ConfigureServices.  I understand and appreciate your statement; would you be willing to accept a PR that had the analyzer dig through the first level method calls in the ConfigureServices method?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
At this point this is not a priority as we haven't seen enough customer demand for this.
