### ISSUE TITLE
HubConnectionBuilder.WithUrl HttpConnectionOptions proxy configuration not working

### ISSUE THREAD

**Issue by sylvainb31** [dotnet/aspnetcore#30696]
### Describe the bug
I have to contact a distant hub signalr via a proxy that I have no control over.
For example, my distant signalr hub is like https://sr.mysignalrhub.net/ and the local proxy I have to go through is something like http//192.168.1.10

So when connecting my signalr client to the hub, I tried to do the following : 

```
_connectionSignalRServer = new HubConnectionBuilder()
                .WithUrl(_serveurSignalRUrl + "/ServeurCentralSignalR?windowsServiceCode=" + _windowsServiceCode, configure => { 
                    configure.HttpMessageHandlerFactory = _ => new HttpClientHandler
                    {
                        ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; }
                    };
                    configure.WebSocketConfiguration = options =>
                    {
                        options.RemoteCertificateValidationCallback = (message, cert, chain, errors) => { return true; };
                    };

                    if (configurationWorker.ConnexionSignalRViaProxy == true)
                    {
                        //var webProxy = new WebProxy(new Uri(configurationWorker.UrlProxy));
                        var webProxy = new WebProxy("192.168.23.1", 8080);
                        if (!String.IsNullOrEmpty(configurationWorker.CredentialProxyUserName) && !String.IsNullOrEmpty(configurationWorker.CredentialProxyPassword))
                        {
                            webProxy.Credentials = new NetworkCredential(configurationWorker.CredentialProxyUserName, configurationWorker.CredentialProxyPassword);
                        }

                        configure.Proxy = webProxy;
                    }                  
                })
                .ConfigureLogging(logging =>
                {
                    logging.AddDebug();
                    logging.SetMinimumLevel(LogLevel.Trace);
                    
                })
                .AddNewtonsoftJsonProtocol(options =>
                {
                    options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
                })
                .Build();
```

But when the connection starts, it connects directly to my distant signalr hub like the proxy configuration doesn't exist.
Nothing appears in the trace log of the signalr connection regarding any proxy.
Do I have to do something else to make it work ?

Thanks for your help.

### Further technical details
net5.0

Microsoft.AspNetCore.SignalR.Client Version="5.0.2"

**Comment by BrennanConroy** [comment]
> But when the connection starts, it connects directly to my distant signalr hub like the proxy configuration doesn't exist.
> Nothing appears in the trace log of the signalr connection regarding any proxy.

There wouldn't be any logging from the signalr side, how do you know the proxy wasn't used?

Also, are you using WASM? Because then it wouldn't use the proxy.

**Comment by sylvainb31** [comment]
Hi,

Thanks for your answer.

Wouldn't it appear on the client side signalr log when it's initiating the connection that it is connecting via a proxy ?

I'm running a web project in net 5.0, my signalr client connection is built on a background service.
What do you mean by "using WASM" ? Why wouldn't it use the proxy ?

**Comment by davidfowl** [comment]
So you have a signalr client connection in a background service (in a worker service?) talking to another signalr server and the proxy option isn't being respected. Is that right?

**Comment by sylvainb31** [comment]
Hello David,

Yes that is exactly right.

Here is what I want to achieve represented by a diagram.

![ImageSignalr](https://user-images.githubusercontent.com/37896804/110235903-13f7d200-7f33-11eb-9cce-02874661b865.png)

So what I expected to happen with the code below is the client signalr to connect to the signalr hub server via the proxy.
I am testing this locally, no matter the ip address I put in the WebProxy object, it connects to the signalrhub, whether I put a phony address or an existing one.

Code in the background service :

```
string _serveurSignalRUrl = "https://sr.mysignalrserver.net";

HubConnection connectionSignalRServer = new HubConnectionBuilder()
                .WithUrl(_serveurSignalRUrl + "/mysignalrhub?windowsServiceCode=" + _windowsServiceCode, configure => { 
                    configure.HttpMessageHandlerFactory = _ => new HttpClientHandler
                    {
                        ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; }
                    };
                    configure.WebSocketConfiguration = options =>
                    {
                        options.RemoteCertificateValidationCallback = (message, cert, chain, errors) => { return true; };
                    };

                    if (configurationWorker.ConnexionSignalRViaProxy == true)
                    {
                        //var webProxy = new WebProxy(new Uri(configurationWorker.UrlProxy));
                        var webProxy = new WebProxy("192.168.0.5", 8080);
                        if (!String.IsNullOrEmpty(configurationWorker.CredentialProxyUserName) && !String.IsNullOrEmpty(configurationWorker.CredentialProxyPassword))
                        {
                            webProxy.Credentials = new NetworkCredential(configurationWorker.CredentialProxyUserName, configurationWorker.CredentialProxyPassword);
                        }

                        configure.Proxy = webProxy;
                    }                  
                })
                .ConfigureLogging(logging =>
                {
                    logging.AddDebug();
                    logging.SetMinimumLevel(LogLevel.Trace);
                    
                })
                .AddNewtonsoftJsonProtocol(options =>
                {
                    options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver();
                })
                .Build();
```

**Comment by davidfowl** [comment]
I wonder if you're running into this https://github.com/dotnet/runtime/pull/48734

**Comment by sylvainb31** [comment]
Hi David,

Is there a way for me to know if it's because of the problem encountered in the link you mentioned ?

**Comment by BrennanConroy** [comment]
> Is there a way for me to know if it's because of the problem encountered in the link you mentioned ?

Because the issue is for WebSockets, you could try specifying LongPolling or SSE and see if the proxy is used.

Also, how are you verifying that the proxy isn't being used? Do you grab the IP from the server side for the client request?

**Comment by sylvainb31** [comment]
Hi Brennan,

Well first I am putting a phony ip address for the proxy and it still connects directly to my hub signalr. 
Isn't it supposed to throw an error when trying to connect with the proxy configuration set if the proxy is not reachable ?

When I tried in production in the company network with the WebSockets as the default transport type, it couldn't reach my hub signalr as it needed to go through the proxy.
I can't try right now in production with both LongPolling or SSE, but I tried locally from my computer and it connects to the signalr hub with my phony ip address set to the proxy. Is it suppose to do this ?

I tried connecting to a local hub signalr on my computer to see if I could find any info on the ip address connected, where am I supposed to see if it comes from a proxy ?

My signalr hub locally on my computer when I connect to it :
![SignalrHub](https://user-images.githubusercontent.com/37896804/110512972-021a5880-8106-11eb-9001-494df74af440.png)

My client connection with the proxy option set : (here I tried setting it to the longpolling transport type)
![ConnectionLongPollingTest](https://user-images.githubusercontent.com/37896804/110513068-18c0af80-8106-11eb-98b3-f3cb89bf099d.png)

Thanks for your help !

**Comment by BrennanConroy** [comment]
I've never used proxies before so don't really know much about their usage. However, I do know that SignalR doesn't do anything special here, we just pass the proxy option to the HttpClient and the WebSocket.

Can you try making a simple app that uses HttpClient directly and set the proxy on that and see if you're hitting similar issues?

**Comment by sylvainb31** [comment]
I will try to do this this weekend and I'll get back to you.
