### ISSUE TITLE
[Razor] Incorrect error notification

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#30694]
Hi,

After upgrading to VS 16.9.0 I've encountered the following error in the experimental razor editor:

![image](https://user-images.githubusercontent.com/29497049/110146169-dca4ec00-7d9f-11eb-813c-859ae5d2f4dd.png)

BlzCard.razor
```razor

<div class="card @CssClass">
    @if (Header != null)
    {
        <div class="card-header @HeaderCssClass">
            @Header
        </div>
    }
    @if (Body != null)
    {
        <div class="card-body @BodyCssClass">
            @Body
        </div>
    }
    @if (Footer != null)
    {
        <div class="card-footer @FooterCssClass">
            @Footer
        </div>
    }
</div>
```

The error appears when ``BlzCard`` component is placed inside a ``div``.

Thank you for your attention.

**Comment by TanayParikh** [comment]
Thanks for reporting this issue.

I've confirmed this has been resolved already via our HTML/Razor Diagnostic filtering. This will be available in the 16.10 Preview 1 release.
