### ISSUE TITLE
Random .razor compilation error when building in VS

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30720]
![image](https://user-images.githubusercontent.com/174281/110217156-6cfa3400-7e67-11eb-8366-6cf4c17b11c6.png)

This is the result of building Components.slnf. It looks like the BindTagHelperDescriptorProvider isn't resolving correctly (occasionally). I'm not able to reproduce this on the CLI

**Comment by pranavkm** [comment]
FYI @captainsafia

**Comment by captainsafia** [comment]
Marking as investigate to see if we can get a reliable repro.

**Comment by mkArtakMSFT** [comment]
This is a dupe of https://github.com/dotnet/aspnetcore/issues/31023
