### ISSUE TITLE
Return Pascal JSON format from Asp.Net Core Web API with AddNewtonsoftJson not working

### ISSUE THREAD

**Issue by nitishwebgentle** [dotnet/aspnetcore#30726]
### Describe the bug
I am working on Asp.Net Core Web API 5.0 and want to return the `Pascal` formatted data in the output. This works fine if I add the following line in the `ConfigureServices()` method

```
services.AddControllers().AddJsonOptions(op => op.JsonSerializerOptions.PropertyNamingPolicy = null);
```

I am also using HTTP Patch API to update the record partially and for this `Patch`, I am using `JsonPatchDocument`. This needs the `Newtonsoft JSON` i.e. `AddNewtonsoftJson`. Here is the link for reference - https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0
 So the mapping looks like - 

```
 services.AddControllers()
              .AddJsonOptions(op => op.JsonSerializerOptions.PropertyNamingPolicy = null)
              .AddNewtonsoftJson();
```
Now, when I use `AddNewtonsoftJson()` the Pascal formatting does not work. (It works fine without `AddNewtonsoftJson()`).
What can I do to resolve this issue if I want to use the Pascal formatting as well as the Patch?

### To Reproduce

https://github.com/nitishwebgentle/asp-net-core-web-api/tree/main/BookStore/BookStore.API

### Exceptions (if any)
None

### Further technical details
- ASP.NET Core version 5.0.3
- Include the output of `dotnet --info`

```
C:\Users\kaush>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS-2019 Professional, V- 16.8.4

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
When you call `AddNewtonsoftJson`, it ignores any existing configuration you have had in the `AddJsonOptions` as those were specifically for `System.Text.Json`. So you'll have to provide separate options for the NewtonsoftJson in the call.
There is an `AddNewtonsoftJson` overload, which accepts [MvcNewtonsoftJsonOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcnewtonsoftjsonoptions.serializersettings?view=aspnetcore-5.0#Microsoft_AspNetCore_Mvc_MvcNewtonsoftJsonOptions_SerializerSettings), which you can use to configure all the settings NewtonsoftJson serializer proivdes: https://www.newtonsoft.com/json/help/html/SerializationSettings.htm

Hope this helps.

**Comment by nitishwebgentle** [comment]
Thanks @mkArtakMSFT, I will check it out. Closing the issue.
