### ISSUE TITLE
[Question]MaxModelBindingCollectionSize limit doesnt apply to collections of simple types

### ISSUE THREAD

**Issue by ozanerdogan90** [dotnet/aspnetcore#30734]
I see in the documentation that MaxModelBindingCollectionSize limit doesnt apply to collections of simple types and I would like to ask if there is a specific reason to exclude primitive types? And also if there is a workaround to limit primitive type collections
My requirement : we have an endpoint both accepts the form value and the json payload and time to time we get InvalidDataException (if form value exceeds 1024 items in collection).I configured the FormOption.ValueCountLimit and MvcOptions.MaxModelBindingCollectionSize but MvcOptions.MaxModelBindingCollectionSize ignores is as my collection has type of guid
I want these values to be aligned with the form value and JSON payload.

Would be great if you can help with

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The `MaxModelBindingCollectionSize` doesn't apply to the JSON serializer. If you'd like the setting to apply, you'll have to write your own converter or use a collection that can be limited.

**Comment by ozanerdogan90** [comment]
hey again. 
My question was about deserializing the payload. 
Is there any specific reason that primitive (basic types) are cant be limited with `MaxModelBindingCollectionSize` ?
