### ISSUE TITLE
WebUtilities not available in client hosted Blazor WebAssembly

### ISSUE THREAD

**Issue by AlexanderRettkowski** [dotnet/aspnetcore#30737]
I wanted to use some features of the Microsoft.AspNetCore.WebUtilities namespace in a client-hosted Blazor WebAssembly project (Microsoft.NET.Sdk.BlazorWebAssembly based). Since .NET Core 3 the former WebUtilities repository/project has moved into the aspnetcore repository and I expected it to be part of the shared framework for Blazor WebAssembly. However, the namespace is not available in the shared framework. Am I missing something here?
I don't reference the old 2.2.0 versions from NuGet because of new functionalities that have been added to the namespace (or the QueryHelpers class in specific) in more recent updates.

A clean code example for my problem is just the basic WebAssembly template itself, it's not possible to use the namespace from there.

**Comment by javiercn** [comment]
@AlexanderRettkowski thanks for contacting us.

Blazor webassembly is not part of the shared framework and doesn't depend on it. Depending on what you are trying to achieve I suggest you replicate the source code within your codebase.
