### ISSUE TITLE
I am developing Blazor Server app. When I duplicate a tab I get exception “The List of component records is not valid”. What to do?

### ISSUE THREAD

**Issue by tahaAttique** [dotnet/aspnetcore#30735]
Hi !
I am developing a Blazor Server app.

There is a Blazor Razor Page which manages News. Recently I applied Save Draft Functionality which temporarily saves data in Radis Cache. When we visit the same page and we find data saved in the cache then the popup asks the user to either Start Fresh or 'Continue Editing' 

![image](https://user-images.githubusercontent.com/47359465/110308628-2dc41280-8022-11eb-843e-7ef43916491b.png)

The Issue is that When I duplicate the above mentioned tab, I get an exception "The List of component records is not valid". 

![image](https://user-images.githubusercontent.com/47359465/110308683-3e748880-8022-11eb-9f63-c4a5be1bb0e1.png)

I searched its solutions but the they are related to AzureSignalR but I am using simple SignalR i.e.

services.AddSignalR(e => 
{
   e.MaximumReceiveMessageSize = 1000;
});
Help will be appreciated.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Try to add the `Cache-Control: no-cache, no-store, max-age=0` header to your response in page action.
