### ISSUE TITLE
Blazor File Downloads Documentation

### ISSUE THREAD

**Issue by berets76** [dotnet/aspnetcore#30736]
Hi, looking around for the answer to the question "how to download a file with blazor server", several approaches are suggested, but it's not clear what the best solution is.

I found samples using controller, razor page, javascript interop, and some others hacks.

Is there a best practice regarding this topic ?

In the specific case, if I've a PDF file (but it could be anything else) content as byte[], what is the officially recommended method to generate a download in the browser ?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We don't have a clear guidance at this point. We will get one and document it in the near future.

**Comment by MarvinKlein1508** [comment]
@berets76 we are using this in our application for months now. It works like magic and is super simple to use.
`https://github.com/arivera12/BlazorDownloadFile`

**Comment by TanayParikh** [comment]
> In the specific case, if I've a PDF file (but it could be anything else) content as byte[], what is the officially recommended method to generate a download in the browser ?

Hello @berets76, I've created https://github.com/dotnet/AspNetCore.Docs/pull/23690/files which should answer this question. Please feel free to try it out and let me know if you run into issues.
