### ISSUE TITLE
Do not make JsonSerializerOptions readonly

### ISSUE THREAD

**Issue by angelaki** [dotnet/aspnetcore#30746]
The behavior of `JsonOptions` and `JsonHubProtocolOptions` seams to differ here: one is read only the other one read / write. I guess this should be unified?

**Comment by pranavkm** [comment]
@tsproesser thank you for your feedback. We have previously considered this suggestion and for the reasons described in https://github.com/aspnet/Mvc/issues/6816#issuecomment-329221624, we have stuck with the current design for MVC's JsonOptions.

**Comment by angelaki** [comment]
That's ok for me - so maybe let the ppl @ SignalR know, so they can adopt this behavior? Guess it makes sense so.

**Comment by davidfowl** [comment]
Shame we are inconsistent here @BrennanConroy
