### ISSUE TITLE
Template tests are run twice azdo + helix

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#30756]
See https://github.com/dotnet/aspnetcore/pull/30703#issuecomment-793132640 for more context, but basically today we run the template tests on both the helix job and the windows test job, this issue is to track following up and deciding what the long term plan is here.  cc @dougbu

**Comment by HaoK** [comment]
Going to address this to see if the blazor template flakiness is from azdo or helix runs

**Comment by HaoK** [comment]
Note, looks like the flakiness is almost entirely on the azdo side.  There hasn't been any failures on the helix blazor template work items since 4/27.  I'm going to remove the templates test job from ci as all project template tests are helix ready so the job is no longer needed

**Comment by dougbu** [comment]
We see _lots_ of failures in the Helix jobs with `dotnet new` timeouts in both the Blazor WASM and template tests. That's what I'm trying to debug in #32889. Just haven't had time to examine the dump I captured.

Were you looking only at the Helix jobs for 'main'❔

**Comment by HaoK** [comment]
I was just looking at the quarantined-pr analytics which showed no blazortemplate.tests--net6.0 failures in the past 14 days, as compared to the pretty awful 56-97% pass rate of the azdo runs in the same time frame.  I was just hoping to get rid of the extra noise since the helix blazor templates looks like something like 9/1k runs passed in the last 30 days, for like 98%+ which actually looks reasonable for them to be unquarantined since all the failures were between 4-26 and 4-27 and likely due a sdk issue

**Comment by HaoK** [comment]
![image](https://user-images.githubusercontent.com/6537861/119419883-f9223780-bcaf-11eb-9f3f-3102ccedf9b8.png)

**Comment by HaoK** [comment]
But the basic idea is we aren't going to be running these tests on azdo in the long term anyways, we might as well stop wasting the CPU cycles, and its adding a lot of noise to the quarantined results since we only care about the helix runs

**Comment by dougbu** [comment]
> the basic idea is we aren't going to be running these tests on azdo in the long term anyways

Alrighty-o I can buy that. Is #32985 ready for review❔
