### ISSUE TITLE
Omnisharp + Razor Source generator = sad face

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30750]
Noticed this as part of my dotnet-watch work. This was reproduced on a Windows machine, I'm not sure what the behavior is like on xplat. With  With O# sharp enabled, the generated editorconfig has lower cased paths. For e.g.
 
```
[d:/temp/watch-apps/blazorserver1/Pages/FetchData.razor]
build_metadata.AdditionalFiles.TargetPath = Pages\FetchData.razor
```

If I disable it and rebuild, the editorconfig uses the casing from the path as-is:

```
[D:/temp/watch-apps/blazorserver1/App.razor]
build_metadata.AdditionalFiles.TargetPath = App.razor
```

Notice the difference in casing - `D:/` vs `d:/`

In dotnet-watch, I'm hosting Roslyn in-proc. I use an MSBuildWorkspace, which uses the path with the same casing as $PWD i.e. in my case `D:\`. When the in-proc compiler runs Razor source generator, it fails unable to find the metadata that it expects to be present because AnalyzerOptions lookups are case sensitive. 

In fact, if I open up the generated editor config file in VSCode and build, I can see it flash (I guess first when msbuild updates it and then immediately when O# does it's thing). Occasionally building the app will fail since there's a race between MSBuild generating an editorconfig and O#.

**Comment by pranavkm** [comment]
FYI @captainsafia

**Comment by captainsafia** [comment]
Follow-up: it looks like this only repros on Windows and pertains specifically to the casing used in the drive letter.

The same issue doesn't repro on macOS.

**Comment by captainsafia** [comment]
Marking this as external.  Part of this is also being tracked in https://github.com/dotnet/roslyn/issues/51768 in addition to the issue referenced above.

**Comment by mkArtakMSFT** [comment]
Closing this as we don't have control over this. We're following up with the OmniSharp team internally to get to some resolution on this from them.
