### ISSUE TITLE
Blazor wasm AuthorizeView's NotAuthorized section executes before the authentication state returns

### ISSUE THREAD

**Issue by ldsenow** [dotnet/aspnetcore#30765]
Hi there,

I'm on Blazor wasm .net 5. I found the NotAuthorized section executes before the authentication state returns. 
I'm expecting the the AuthorizedView will evaluate the state first then render the section accordingly. 

Am I missing anything?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by ldsenow** [comment]
Please refer to the repo bellow and I have put the steps to reproduce the issue in the README

https://github.com/ldsenow/BlazorAuthDemo

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
