### ISSUE TITLE
Angular AuthorizeService getUser() is strange

### ISSUE THREAD

**Issue by kdubious** [dotnet/aspnetcore#30766]
### Describe the bug
The `getUser()` method returns an observable. In the process of doing so, it may trigger the userSubject to spit out another observable. If you subscribe somewhere to getUser, and also subscribe somewhere else... your subscriptions might get "new" observables of the same user.

Sure, you can code around this, but it doesn't match most APIs I've used.

### To Reproduce
Component 1:
```
    var authSub = this.authService
      .getUser()
      .pipe(
        tap((user) => {
          this.operatorId = user.name;
// maybe load some data here?
        })
      )
      .subscribe();
    this.subs.push(authSub);
    // please unsubscribe in ngOnDestroy()
  
    ngOnDestroy() {
        this.subs.forEach((sub) => sub.unsubscribe());
    }
```

Component 2:
```
    var authSub = this.authService
      .getUser()
      .pipe(
        tap((user) => {
          this.operatorId = user.name;
// this might trigger Component 1 to get another User
        })
      )
      .subscribe();
    this.subs.push(authSub);
    // please unsubscribe in ngOnDestroy()
```

### Exceptions (if any)
No Exceptions , but weird issues unless this is defended against. (in my opinion)

### Further technical details
To be honest, I'm not 100% clear on the intent of the existing code. Feels like the idea is to see if there's on available on the BehaviorSubject, and if not, check storage, and otherwise hand over the internal subject.

I'd propose something more standard:

In psudocode:

1. During construction, look for a valid, non-expired user in storage
2. Pass it to `userSubject.next()` if it's there
3. Otherwise, during login, pass the user to `userSubject.next()`
4. make the userSubject like this `private userSubject: BehaviorSubject<IUser | null> = new BehaviorSubject(
    null
  );`
5. make a public Observable $user object `public user: Observable<IUser | null> = this.userSubject.asObservable();`

Then we would subscribe to `user$` getting the most recent logged in user (if there is one) and getting null if they're not logged in or if they logged out.

--

However, maybe I'm missing something. I just have very strange behavior related to trying to do thinks in the app with my User, and I think this approach would fix the weirdness.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We haven't heard any similar concerns so we will keep this code as is. Feel free to modify the code in your app as you find it fit for your needs. We will eventually modify the templates as we do so from time to time.
