### ISSUE TITLE
New Experiment Razor Editor Snippets Not Working

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#30774]
I decided to try out the new razor editor.  The bad news is snippets won't even work anymore.  Even the older version, it worked.

For example, if I use @foreach and tab, does not finish that part like it used to in the old editor.

**Comment by danroth27** [comment]
See also #22744

**Comment by NTaylorMullen** [comment]
Seems like could be blocked by: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1333659

**Comment by NTaylorMullen** [comment]
More related issues:
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1345222
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1344663

**Comment by NTaylorMullen** [comment]
[LSP Platform side](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/337182) is in.
