### ISSUE TITLE
A way to turn off App_Offline.htm detection is requested by a large Enterprise customer

### ISSUE THREAD

**Issue by JasonXuMSCSS** [dotnet/aspnetcore#30782]
### Is your feature request related to a problem? Yes,

In one of our large enterprise customer environment, a false positive detection of App_Offline.htm is showing up frequently - several times a day. That false positive detection of App_Offline.htm, thus caused the ASP.Net Core app shut down unexpectedly multiple times a day. It may be due to this customer's environment, but I do see other reports online showing the same, and difficult to isolate the real root cause of such false positive, in customer's Production environment.

Customer wants a switch that can turn off such App_Offline.htm detection so no matter what the cause is, such false positive (It is 100% certain there is no such App_Offline,thm file but the App_Offline event showed up in event logs) will not cause any consequence.

### Describe the solution you'd like
Add a switch in the App_Offline.htm detection code, so no matter it is real or false positive, customer can have control of whether to use this App_Offline.htm detection or not. Switch can be a registry key, or a configuration value in app config.

This customer currently is using ASP.Net Core 2.1. They requested to add such switch to 2.1 and latest ASP.Net Core 3.x (they will upgrade in the future).

### Additional context
There is internal discussion on this issue with Justin and CSAM of this enterprise customer.

**Comment by BrennanConroy** [comment]
We recently fixed a few bugs that could cause false app_offline detection to occur. This will first appear in .NET 10 preview1. Since this issue is old and is a proxy issue for some customer I'll close it.

Using https://github.com/dotnet/aspnetcore/issues/55939 for phantom app_offline issue discussion.
