### ISSUE TITLE
Open the _Host.cshtml in Blazor server project, the label color of "<base />" is wrong.

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#30795]
Tracking issue for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1283695.

**Comment by ryanbrandenburg** [comment]
As @balachir said on the AzDO issue, isn't this "as intended" because it's not a TagHelper until you add the "~/"? As defined here: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Razor/src/TagHelpers/UrlResolutionTagHelper.cs#L29.

**Comment by NTaylorMullen** [comment]
> As @balachir said on the AzDO issue, isn't this "as intended" because it's not a TagHelper until you add the "~/"? As defined here:

It's unintended because ~/ based TagHelpers are meant to be "runtime only" and hidden at design time

**Comment by ryanbrandenburg** [comment]
We talked offline and agreed that this was by design. The "runtime only" aspect of <base /> has been removed, so the current colorization behavior is correct.
