### ISSUE TITLE
Scoped css does not appear to work nicely with StaticWebAssetBasePath

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30791]
The configured directory appears twice in the path. e..g `wwwroot/MyBaseDir/MyBaseDir/MyApp.styles.css`

**Comment by javiercn** [comment]
That's weird, we do have special logic for this file to always appear at the root of the url space by default, but you can explicitly override it if you change the StaticWebAssetBasepath. I would have swore we have tests for that.

**Comment by SteveSandersonMS** [comment]
We don't think this is a real issue.
