### ISSUE TITLE
AspNet Core 5.0.4 seems incompatible with earlier Net 5 runtimes

### ISSUE THREAD

**Issue by touchofevil2** [dotnet/aspnetcore#30801]
### Describe the bug
AspNet Core 5.0.4 seems incompatible with earlier Net 5 runtimes eg, 5.0.3

### To Reproduce
1. Ensure below runtimes are installed.
.Net core - 5.0.3
AspNet Core - 5.0.4 (Shared framework)
We also have Net Desktop 5.0.3 however that seems to be optional for the bug.

2. Create a simple AspNet api from the template. WeatherForecast example would do.
3. Build the api project.
3. Run the generated <api>.exe or run the <api>.dll using dotnet tool.

Result:
The error shows
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.4' was not found.
  - The following frameworks were found:
      2.1.24 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

Please note this issue goes away if I manually install .Net Core 5.0.4

However since this is just a patch should this need a .Net Core runtime upgrade to version 5.0.4 as well? Should we expect this behavior on any further patch/minor updates too?

### Further technical details
- ASP.NET Core version : 5.0.4
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version - VS Enterprise 16.8.4

**Comment by javiercn** [comment]
@touchofevil2 thanks for contacting us.

@dotnet/aspnet-build any thoughts?

**Comment by alexwiese** [comment]
See this comment from @anurse:

> While we do recommend you run on the latest patch, we recommend you do not update your app to target later patch versions as your app will fail to start if that patch doesn't exist on the target machine. The version of Microsoft.AspNetCore.App you reference is a lower-bound, so if you reference 2.2.4 you'll fail to start on a server that only has 2.2.3 installed. Patches shouldn't be introducing APIs that you need to update to depend upon so there's no need to update the package reference.

https://github.com/dotnet/aspnetcore/issues/10249#issuecomment-492477445

**Comment by wtgodbe** [comment]
Right, if you want to upgrade your installed version of asp.net, we recommend you install the hosting bundle, which also includes the .net runtime. You can find it [here](https://dotnet.microsoft.com/download/dotnet/5.0)

**Comment by touchofevil2** [comment]
@alexwiese : Thank you for the suggestion, that was helpful. Currently there is no explicit setting done hence am I correct in understanding that it should be default i.e. roll forward on patch and minor. Would I be correct in understanding that the comment points to roll forward of same runtime? This issue in particular is though with AspNet's backward compatibility with .Net runtime.

@wtgodbe : The bundle is helpful for upgrades, however since we use all 3 runtimes, would we also need to ensure that desktop runtime is also upgraded along with AspNet since all will depend on .Net runtime at the core of it? I would try and test the scenario by this weekend. I believe the confusion here is mainly due to it being a patch version but would be happy to understand the thoughts on it?

**Comment by wtgodbe** [comment]
> The bundle is helpful for upgrades, however since we use all 3 runtimes, would we also need to ensure that desktop runtime is also upgraded along with AspNet since all will depend on .Net runtime at the core of it? I would try and test the scenario by this weekend. I believe the confusion here is mainly due to it being a patch version but would be happy to understand the thoughts on it?

If you'd like to install all 3, we recommend you install the SDK, which carries with it all 3 runtimes. You can also find that on the left side of the page I linked above.

**Comment by dougbu** [comment]
@touchofevil2 thank you for your feedback. We're closing this issue as the questions asked here have been answered.
