### ISSUE TITLE
[Blazor] [Razor] Catching errors at compile-time

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#30804]
Hi,

Is there a reason why the build process cannot error out if the developer is setting up a component with an invalid parameter? Consider this simple scenario:

BlzCard.razor.cs
```csharp
[Parameter]
public RenderFragment Header { get; set; }

[Parameter]
public RenderFragment Body { get; set; }

[Parameter]
public RenderFragment Footer { get; set; }

[Parameter]
public string CssClass { get; set; }

[Parameter]
public string HeaderCssClass { get; set; }

[Parameter]
public string BodyCssClass { get; set; }

[Parameter]
public string FooterCssClass { get; set; }
```

Test.razor
```razor
<BlzCard
    InvalidParameter="This should throw an error during compilation">
    <Header>
        Card Header
    </Header>
    <Body>
        <p>
            Card Body
        </p>
    </Body>
</BlzCard>
```

Obviosuly, an error will be thrown at run-time, but isn't one of the selling points of Blazor that unlike the JavaScript world, compiler can catch many errors before the application even runs? Also, can the razor editor display a squiggly underneath ``InvalidParameter``?

Thanks.

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

There are several reasons for this, including the fact that we don't know if you are overriding `SetParametersAsync` and implementing your own logic.

**Comment by pranavkm** [comment]
We're using #19791 to track adding this as a feature.
