### ISSUE TITLE
Installing ASP.NET Core Runtime 2.1.25 hosting bundle on a machine where  ASP.NET Core Runtime 2.1.5 hosted bundle is resulting in error 0x80070666- Another version of product is already installed)

### ISSUE THREAD

**Issue by rambabunethi** [dotnet/aspnetcore#30818]
### Description

Upon installation of ‘Microsoft ASP.NET Core Runtime 2.1.25 Hosting Bundle’ on a machine where ‘Microsoft ASP.NET Core Runtime 2.1.5 Hosting Bundle’ is installed I see an error(0x80070666- Another version of product is already installed). 

### Configuration

* What OS and version, and what distro if applicable? - Windows server 2012 R2.
* What is the architecture x64.

### Regression?

* Did this work in a previous build or release of .NET Core
* 
yes 2.1.13, 2.1.16,2.1.18,2.1.20,2.1.23 if installed on the machine and upon installing 2.1.25 it works fine.

### Other information
![1C660B21-4DF9-4A2D-B171-C0F3F3C3873A](https://user-images.githubusercontent.com/15332566/109914116-4678a500-7c7d-11eb-8a0b-c40cf603cc01.jpeg)

* Do you know of any workarounds?
  No

**Comment by BrennanConroy** [comment]
cc @joeloff

**Comment by joeloff** [comment]
cc @wtgodbe That error is most likely being triggered from one of the MSI. Logs would be useful, they should all be in %temp%, but I'm guessing this will repro locally too

**Comment by wtgodbe** [comment]
@joeloff It repros for me locally, attached is what looks like the relevant log

[dd_dd_DotNetCoreWinSvrHosting__20210316095958.log](https://github.com/dotnet/aspnetcore/files/6150932/dd_dd_DotNetCoreWinSvrHosting__20210316095958.log)

**Comment by joeloff** [comment]
Thanks. I see the issue. ASP.NET used a different versioning scheme long ago because it used to support b2b upgrades. If you look at 2.1.5, all the ASP.NET items are versioned as 2.1.13320 (2.1.x installs were upgradable and build numbers were incremental across  patches). Now the bundles are versioned as 2.1.25.xxx which will make it a downgrade.

The only fix is to remove all the offending bundles from the upgrade list in 2.1.26 once we know at release this was migrated to the new repo/build pipeline

**Comment by rambabunethi** [comment]
Thanks for identifying the cause. I see 2.1.26 version was released on March 9th https://dotnet.microsoft.com/download/dotnet/2.1 also has same issue. Will the package be replaced after correcting the issue?

**Comment by wtgodbe** [comment]
The first release built off of TeamCity was 2.1.25. I'm surprised that the previous scheme was `Major.Minor.BuildNumber` - here's the discussion on where I changed the format of the `BuildNumber` that was passed to Wix, but at the time the version scheme was still `Major.Minor.Patch.BuildNumber` - https://github.com/dotnet/aspnetcore/pull/28829/files#r548103621

> Will the package be replaced after correcting the issue?

Unfortunately it's too late to get a fix into next month's servicing release, so we won't be able to patch this bug until May. @joeloff is there a  workaround customers can use in the meantime? Just uninstall 2.1.5?

**Comment by wtgodbe** [comment]
@joeloff so we need to remove all of the `RelatedBundleId`s from here? https://github.com/dotnet/aspnetcore/blob/release/2.1/src/Installers/Windows/SharedFrameworkBundle/Bundle.wxs#L16-L127

This lists up to 2.1.23 - 2.1.24 was the first release after we "fixed" upgrade behavior, so it isn't in there, and 2.1.25 is the first release that was built off of TeamCity.

**Comment by joeloff** [comment]
If you wanted to fix this, yes, but we can't because that break the MU requirements to remove older versions

**Comment by wtgodbe** [comment]
Looks like 2.1.7 was the first release where we included `Patch` in the version passed to WiX, so upgrading from a pre-2.1.7 build to a post-2.1.7 build would be broken

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/31457 should fix this, it will be merged for the May release of 2.1.

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/aspnetcore/pull/31457
