### ISSUE TITLE
HttpSys IServer returns from StopAsync before it has finished shutting down

### ISSUE THREAD

**Issue by mconnew** [dotnet/aspnetcore#30828]
### Describe the bug
When using the HttpSys IServer implementation via the `UseHttpSys` extension method, shutting down the server isn't completed when `StopAsync` completes. CoreWCF unit tests create an `ILogger` implementation from the test `ITestOutputHelper` instance so that `ILogger` output can go to the test output. After `IWebHost.StopAsync` has completed, `HttpSys.MessagePump` continues to write to the `ILogger` which causes the test runner to quit. Based on the callstack it looks like the shutdown is happening on a timer thread.  

This will have problems beyond the CoreWCF unit tests. If an application shuts down a host and attempts to immediately restart it, then it could have problems restarting due to the request queue already existing. This might be done in order to pick up some config changes.

### To Reproduce
Checkout the FixHttpSys branch from [this fork](https://github.com/mconnew/CoreWCF/) of CoreWCF. Run the unit tests from the command line:
```
git checkout https://github.com/mconnew/CoreWCF/ CoreWCF
cd CoreWCF
git checkout FixHttpSys 
dotnet restore src\CoreWCF.sln
dotnet build src\CoreWCF.sln
dotnet test src\CoreWCF.Http\tests\CoreWCF.Http.Tests.csproj
```

### Exceptions (if any)
```
The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while writing to logger(s). (There is no currently active test.)) ---> System.AggregateException: An error occurred while writing to logger(s). (There is no currently active test.) ---> System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
   at Helpers.XunitLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\git\CoreWCF\src\Common\tests\Helpers\XunitLogger.cs:line 29
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.<>c__DisplayClass25_0.<StopAsync>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

### Further technical details
- ASP.NET Core version 2.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version - only repros on cmd line
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.1.814 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.113 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Tratcher** [comment]
Part of this doesn't make sense. The stack trace implies you're hitting this code path:
https://github.com/dotnet/aspnetcore/blob/85a6cb07ae2e1adf5a03740f8d40333b7b8e360c/src/Servers/HttpSys/src/MessagePump.cs#L236-L243

That should only trigger if StopAsync aborts due to the CT firing. That CT uses a default timeout (5s?), and that timeout gets canceled if StopAsync completes gracefully.
https://github.com/dotnet/aspnetcore/blob/8c52e6837105f67030fda01d81d444d3b1fb5242/src/Hosting/Hosting/src/Internal/WebHost.cs#L309

Is your test taking longer than 5s to stop?

Even after the CT fires, StopAsync shouldn't complete until after the CT fires and the log is written.
https://github.com/dotnet/aspnetcore/blob/85a6cb07ae2e1adf5a03740f8d40333b7b8e360c/src/Servers/HttpSys/src/MessagePump.cs#L271

**Edit**: Nevermind, I found the issue: https://github.com/dotnet/aspnetcore/pull/24399
The WebHost StopAsync CT timer wasn't stopped/disposed until 5.0. MessagePump StopAsync doesn't unregister from the token on graceful completion, so the callback still fires in the background.

Mitigation: Try disabling the shutdown timeout.
https://github.com/dotnet/aspnetcore/blob/b9baf8cf8b90135278b26b92075bb373f6418603/src/Hosting/Hosting/src/Internal/WebHostOptions.cs#L40-L45
https://github.com/dotnet/aspnetcore/blob/b9baf8cf8b90135278b26b92075bb373f6418603/src/Hosting/Hosting/src/WebHostBuilder.cs#L84

If that works then this likely doesn't qualify for a backport.

**Comment by mconnew** [comment]
What value do I set it to for it to be disabled? 0? -1?

**Comment by Tratcher** [comment]
`-1`
https://docs.microsoft.com/en-us/dotnet/api/system.threading.timeout.infinite?view=net-5.0

**Comment by mconnew** [comment]
I'll give it a go, but I don't think that's going to work as the value is being parsed as number of seconds and gets converted to TimeSpan.FromSeconds(-1). This is different than [InfiniteTimeSpan](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timeout.infinitetimespan?view=net-5.0) which is equivalent to new TimeSpan(0, 0, 0, 0, -1). CancellationTokenSource(TimeSpan delay) has this code:
```c#
            long totalMilliseconds = (long)delay.TotalMilliseconds;
            if (totalMilliseconds < -1 || totalMilliseconds > Timer.MaxSupportedTimeout)
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.delay);
            }
```
TimeSpan.FromSeconds(-1).TotalMiliseconds will have a value of -1000 which will cause it to throw.

**Comment by Tratcher** [comment]
You're right, I'd missed the unit's here. Maybe we do need to backport this.

I saw you're targeting 2.1? 2.1 support is running out and it's hard to approve patches for it at this point. 

In 3.1 if you used the new GenericHost it has already fixed this:
https://github.com/dotnet/extensions/blob/6c3980a467865f41ccb4478cd9bf3105023daf29/src/Hosting/Hosting/src/Internal/Host.cs#L63

**Comment by mconnew** [comment]
When did LTS mean long term support until it's close to ending, in which case it's semi supported? Also 2.1 doesn't go out of support any time soon for NetFx, and one of the primary targets for CoreWCF is currently NetFx for migration support.  

I verified setting the timeout to -1 didn't work as I expected. It's generally a bad idea to come up with different representations of config values than their natural .NET format for exactly this sort of reasons. Durations in config should either be milliseconds or a parsable TimeSpan value otherwise developers aren't able to control what the value will actually be, like in this case I can't provide infinite to prevent cancellation.

I did work out a really ugly workaround. I wrap the StopAsync code like this:
```c#
                var cts = new CancellationTokenSource();
                host.StopAsync(cts.Token).GetAwaiter().GetResult();
                cts.Cancel();
                cts.Dispose();
```
That way I force the cancellation callback to execute and complete before the test exits.

**Comment by Tratcher** [comment]
That's a clever workaround and makes sense in this context. The comments about the config value format also make sense in hindsight, we've taken that approach elsewhere.

The older the product, the higher the bar is to patch it. In this case you're the only one to report this and you now have a workaround. The average application will have exited before the 5s timer fires.

For triage: I recommend closing this until we get additional feedback about it.

**Comment by BrennanConroy** [comment]
> For triage: I recommend closing this until we get additional feedback about it.

Agreed.

FYI for our servicing bar https://github.com/dotnet/aspnetcore/blob/main/docs/Servicing.md#servicing-bar
