### ISSUE TITLE
Open the Razor pipeline for extensions using dependency injection

### ISSUE THREAD

**Issue by Genbox** [dotnet/aspnetcore#30826]
## Summary

It seems the Razor engine is built with extensions (features/passes) in mind, but most of it seems to be internal.

I and many others (people that want minification in Razor, like this [one](https://github.com/dotnet/aspnetcore/issues/23570)) would like to manipulate with the Razor syntax tree, and the best way seems to be to hook in a pass to in the Razor engine, as it already parses the Razor code and reuse the syntax tree for many passes.

However, the list of passes can't be modified without significant changes. Since the DefaultRazorProjectEngineBuilder is not provided by dependency injection, nor is the instance reachable through a delegate or similar.

This means in order for me to inject a pass, I have to resort to replacing the RazorProjectEngine, which is not optimal:

```csharp
services.Replace(ServiceDescriptor.Singleton<RazorProjectEngine>(x =>
{
    RazorProjectFileSystem fileSystem = x.GetRequiredService<RazorProjectFileSystem>();
    RazorProjectEngine projectEngine = RazorProjectEngine.Create(RazorConfiguration.Default, fileSystem, builder =>
    {
        builder.Phases.Add(new AwesomeFeature());
    });

    return projectEngine;
}));
```

The second problem comes when you then try and inherit from [IRazorSyntaxTreePass](https://github.com/dotnet/aspnetcore/blob/main/src/Razor/Microsoft.AspNetCore.Razor.Language/src/IRazorSyntaxTreePass.cs), but you can't since it is internal. It even has a note that says "Internal until we flesh out public RazorSyntaxTree API". Until it is public, it is impossible to modify the syntax tree.

Razor has an extensible design, but it seems to be completely closed off users. I can't seem to find an issue that tracks this design change, so I created one.

Can we open up the APIs a little bit? Change a couple of internal interfaces/classes to be public?

**Comment by pranavkm** [comment]
Thanks for your feedback @Genbox. Unfortunately we're not prepared to open up the Razor's APIs for public usage in the general case as it increases our support costs.
