### ISSUE TITLE
why debug helloworld program load all assembly, took so long time.

### ISSUE THREAD

**Issue by srxqds** [dotnet/aspnetcore#30830]
### Describe the bug
when we run a helloworld program, I found it load all moste all assembly, it took so long time to debug.

I don't know what are your gays think, so said.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
![image](https://user-images.githubusercontent.com/5187024/110744603-eda89e00-8274-11eb-9e9d-865aa475159f.png)

![image](https://user-images.githubusercontent.com/5187024/110744623-f4371580-8274-11eb-993a-a0d40ea00f6d.png)

**Comment by blowdart** [comment]
It's always going to load those assemblies, because that's what your app needs, however if you're debugging it may be that it's going to our symbol server and downloading symbols you don't have. If you debug a second time, is it any faster?

**Comment by srxqds** [comment]
> It's always going to load those assemblies, because that's what your app needs, however if you're debugging it may be that it's going to our symbol server and downloading symbols you don't have. If you debug a second time, is it any faster?

but my project is just a helloworld, why it need so many assemblies,  I think it is a terrible experience.

**Comment by davidfowl** [comment]
> but my project is just a helloworld, why it need so many assemblies, I think it is a terrible experience.

.NET breaks components up into many assemblies for layering purposes. They are used to prevent taking dependencies at the wrong layer in the stack and to avoid loading things that aren't needed if they aren't referenced.

Hello World is optimized to be the most useful by default, not load the least assemblies. If you are trying to trim usage of features, then you can absolutely construct an application that does so but that's not as useful to the average user trying to learn or make things work.

**Comment by srxqds** [comment]
![image](https://user-images.githubusercontent.com/5187024/111117398-6cb61300-85a2-11eb-9319-0d2318f11a1f.png)

and so many exception I don't know what wrong with it.

**Comment by srxqds** [comment]
> > but my project is just a helloworld, why it need so many assemblies, I think it is a terrible experience.
> 
> .NET breaks components up into many assemblies for layering purposes. They are used to prevent taking dependencies at the wrong layer in the stack and to avoid loading things that aren't needed if they aren't referenced.
> 
> Hello World is optimized to be the most useful by default, not load the least assemblies. If you are trying to trim usage of features, then you can absolutely construct an application that does so but that's not as useful to the average user trying to learn or make things work.

how can I make it run faster when debug.
almost time I modify source code and it will reload all assembly.

**Comment by srxqds** [comment]
![image](https://user-images.githubusercontent.com/5187024/111476647-50b09e00-8769-11eb-8b3e-6cbc2b1a92dd.png)
so many assembly.
so stupid!
