### ISSUE TITLE
asp.net core modelstate validation custom error message. how to to put quotations or some other characters in place of input value

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#30842]
I am getting following response from my asp.net core 3.1 api after i put custom model validation in startup
```
{
"success": "failed",
"message": "fk entity id: The value '<script>alert(1);</script>' is not valid for fk_entity_id."
}
```
My code in startup is like

private void CustomValidationResponse(IServiceCollection services)
        {
            services.Configure<ApiBehaviorOptions>(
                options => options.InvalidModelStateResponseFactory = actionContext =>
                {
                    return CustomErrorResponse(actionContext);
                }
                );
        }

```
private BadRequestObjectResult CustomErrorResponse(ActionContext actionContext)
        {
            var errorRecordList = actionContext.ModelState
              .Where(modelError => modelError.Value.Errors.Count > 0)
              .Select(modelError => new
              {
                  ErrorField = modelError.Key,
                  ErrorDescription = modelError.Value.Errors.FirstOrDefault().ErrorMessage
              }).ToList();

            string concatenatedMessage = string.Empty;
            foreach (var error in errorRecordList)
            {
                concatenatedMessage += error.ErrorField.Replace("_", " ") + ": " + error.ErrorDescription + ",";
            }
            concatenatedMessage = concatenatedMessage.TrimEndExt(",");
            return new BadRequestObjectResult(new
            {
                success = "failed",
                message = concatenatedMessage
            });
        }
```

What i want is somehow putting some quotation/escape character in place of value in my message response something like

```
{
"success": "failed",
"message": "fk entity id: The value ['<script>alert(1);</script>'] is not valid for fk_entity_id."
}
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by KamranShahid** [comment]
I have tried stackoverflow and no response there. even posted a workaround myself there. i thought it is a  sort of feature request so posted it here
