### ISSUE TITLE
Js Isolation for Asp.Net Core Web Application for .cshtml files

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/aspnetcore#30850]
Thanks for add #25713 please add support for js Isolation for Asp.Net Core Web Application for .cshtml files, same css simply add a .cshtml.js to view folders.

**Comment by javiercn** [comment]
@mojtabakaviani thanks for contacting us.

What scenario do you have in mind for this in the context of a web app?

**Comment by mojtabakaviani** [comment]
Usually in the pages needs to add javascript for working with DOM. Now can use @section tag to add scripts to render  to layout, but if have many code lines and string literals, formatting not work perfectly and not minifying and load scripts every page called. good idea to use separated js files and minifying or just many developers like to use separated js and css files for pages. I now use my method's that create js files in wwwroot/js folder and linked to pages but if asp.net core native support css and js isolation in separated files and even can auto generating and loading .cshtml.min.css and .cshtml.min.js with versioning for production mode, it is very good news.

**Comment by javiercn** [comment]
@mojtabakaviani thanks for the additional details.

Our support for JS isolation on Blazor is limited to the fact that we support the `import` keywork via JS interop and that we return a JSObjectReference back.

None of these things apply to MVC. You can already achieve what you want without support from the runtime by using
`<script type="module" src="path-to-module.js"></script>` on your cshtml file and putting the js file within the wwwroot folder at your desired path.

Modules will be loaded once, will bring in their dependencies via imports and will render asynchronously.
