### ISSUE TITLE
TagBuilder is in the wrong namespace

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#30868]
Is the `TagBuilder` class in the wrong namespace?
It is in the `Microsoft.AspNetCore.Mvc.Rendering` namespace in the `Microsoft.AspNetCore.Mvc.ViewFeatures` assembly, but does the TagBuilder have anything with MVC?

It can also be used together with Razor pages. It can also be used outside ASP.NET for things such creating HTML for emails. Maybe it can even be used for creating XML.

**Comment by javiercn** [comment]
@vanillajonathan thanks for contacting us.

Razor pages are part of MVC. We don't plan to change API namespaces since it breaks existing code and there's very limited value. It's also a conscious decision to minimize the number of namespaces we use.

**Comment by vanillajonathan** [comment]
Maybe the `TagBuilder` ought to not even be in the ASP.NET namespace because it useful for non-ASP and non-web things such as creating SVG images or any XML documents.

Maybe a better place would be the `System.Xml` or the `System.Web` namespace.

**Comment by javiercn** [comment]
> Maybe the `TagBuilder` ought to not even be in the ASP.NET namespace because it useful for non-ASP and non-web things such as creating SVG images or any XML documents.
> 
> Maybe a better place would be the `System.Xml` or the `System.Web` namespace.

We don't plan to change its current location nor namespace. It's a facility MVC provides for usage within MVC applications. Customers are free to use in whatever context they see fit, however it's not intention to change anything about it that is not required for building ASP.NET Core MVC applications, specially if it breaks existing libraries and customers.

Hope that helps explain our position.
