### ISSUE TITLE
When I open multiple tabs at the same time then I get Microsoft.JSInterop.JSException. Dotnet Core Blazor Server.

### ISSUE THREAD

**Issue by tahaAttique** [dotnet/aspnetcore#30869]
Hi, 
I am developing a .net core blazor server web application. The application uses JSInterop extensively on Editing Pages. The website is deployed using Azure Services. 

The problem is that when I open multiple tabs of a Editing page(where JSInterop is injected and used) at the same time then I get Microsoft.JSInterop.JSException. This problem does not appear in two cases which are following

1. If I run my app on local machine 
2. If I open each tab with a little time gap (on deployed one) e.g opening one tab and get it load and then opening the other app. 

Screenshot of the exception 
![image](https://user-images.githubusercontent.com/47359465/110929120-709b2880-8349-11eb-8c5c-e2baeb16a63b.png)

This problem appears on each page where JSInterop is used but for understanding purposes I explain it by one page. 

There is a razor page named "Organization Management (Editor)". This page is used for making new organization or for editing the old ones. 

![image](https://user-images.githubusercontent.com/47359465/110927017-ea7de280-8346-11eb-8e0c-66bfa3153e86.png)

Select2 blazor component is used in the razor page of the Organization Management Editor with the label name 'Organization Type'.
![image](https://user-images.githubusercontent.com/47359465/110927996-2e251c00-8348-11eb-81d2-aac942135f6f.png)

JsInterop is used in onAfterRender of Select2.razor.cs
![image](https://user-images.githubusercontent.com/47359465/110928129-56ad1600-8348-11eb-8cd8-71e95bd78dea.png)

On opening multiple tabs simultaneously on the deployed website, we find expectation in the 3rd and onwards tabs. The exception is the following 
![image](https://user-images.githubusercontent.com/47359465/110928716-008ca280-8349-11eb-892f-0d5bbc897925.png)

Help will be appreciated.

**Comment by javiercn** [comment]
@tahaAttique thanks for contacting us.

Try adding the following line to your `_Host.chstml` to disable caching

```razor
@{
    context.Response.Headers[HeaderNames.CacheControl] = "no-cache, no-store, max-age=0";
}
```
