### ISSUE TITLE
Allow IdentityUserClaim and IdentityRoleClaim id type to be configurable

### ISSUE THREAD

**Issue by lostatredrock** [dotnet/aspnetcore#30872]
Most of the identity system allows you to specify the type used as the PK.  But IdentityUserClaim and IdentityRoleClaim do not.  They force you to use an int as the PK.  Just from a consistancy point of view it is not clear to me why these two entities are treated differently.

Also from a practical point of view this places hard limits on the number of claim records that can be created by the system.  Worse because different database systems implement auto increment ids differently the hard limit can't really be known ahead of time.  Depending on DB configuration and system load we have seen int id densities as low as 5% which means you hit the ~2 billion record limit after only ~100 million entries are created.

To me the simplest sollution is to treat these entities just like all the other identify object and allow us to specify the id type so this if our use case warrents it we can make use of a Guid or other value type.

I am not sure what a reasonable argument againt treating these two entities just like every other identity entity would be.  We could of course re-implement the store classes to use our own implementation but this would seem to me to be a ton of work when a far simpler and more straight forward sollution should exist.

**Comment by HaoK** [comment]
The tradeoff was complexity with more generics, we decided this was the appropriate balance, for the developers that need that level of customization, as you mention, subclass is the intended path.
