### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Testing Preview 2 second error

### ISSUE THREAD

**Issue by ChrisWorledge** [dotnet/aspnetcore#30876]
Having overcome the intial build error when using Microsoft.AspNetCore.Mvc.Testing

Setting the text in .nuget\packages\microsoft.aspnetcore.mvc.testing\6.0.0-preview.2.21154.6\buildTransitive\net6.0\Microsoft.AspNetCore.Testing.targets
to <Project>

	<Import Project="..\..\build\net6.0\Microsoft.AspNetCore.Mvc.Testing.targets" /> 

</Project>

I now get a build error relating to the manifest:
Error	MSB4062	The "GenerateMvcTestManifestTask" task could not be loaded from the assembly .nuget\packages\microsoft.aspnetcore.mvc.testing\6.0.0-preview.2.21154.6\build\net6.0\..\..\tasks\netstandard2.0\Microsoft.AspNetCore.Mvc.Testing.dll. Could not load file or assembly 'file:///  .nuget\packages\microsoft.aspnetcore.mvc.testing\6.0.0-preview.2.21154.6\tasks\netstandard2.0\Microsoft.AspNetCore.Mvc.Testing.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

I checked the is a file at that location and    .nuget\packages\microsoft.aspnetcore.mvc.testing\6.0.0-preview.2.21154.6\buildTransitive\net6.0 has a file called Microsoft.AspNetCore.Mvc.Testing.targets and it indicates it has been recently modified.

**Comment by martincostello** [comment]
Fixed by #30847.

**Comment by javiercn** [comment]
@ChrisWorledge thanks for reporting this.

@martincostello fixed it as part of https://github.com/dotnet/aspnetcore/pull/30847

and it will be available on the next preview
