### ISSUE TITLE
API Proposal: Consider adding a WaitForDataBeforeAllocatingBuffer in HttpsConnectionMiddleware

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#30877]
## Background and Motivation

As part of https://github.com/dotnet/aspnetcore/pull/30863, we're doing zero byte reads as a way to save memory. In some cases it might be better for performance (like in HTTPs based benchmarks), if we don't do a zero byte read before the actual read. Note, this isn't as big a deal as in the transport layer because it's not a real sys call we're making. We're calling into an in memory implementation. 

## Proposed API

```diff
namespace Microsoft.AspNetCore.Server.Kestrel.Https
{
    public class HttpsConnectionAdapterOptions
    {
+       public bool WaitForDataBeforeAllocatingBuffer { get; set; }
    }
```

## Usage Examples

```C#
var host = new HostBuilder()
                .ConfigureWebHost(webHostBuilder =>
                {
                    webHostBuilder
                        .UseKestrel(options =>
                        {
                            options.Listen(IPAddress.Loopback, 5001, o => o.UseHttps(https => https.WaitForDataBeforeAllocatingBuffer = true ));
                        })
                        .UseStartup<Startup>();
                })
                .Build();

            await host.RunAsync();
```

## Risks

None.

**Comment by BrennanConroy** [comment]
Triage: Can we see numbers before doing this?

**Comment by davidfowl** [comment]
Yea, agreed, I don't want to do it.

**Comment by davidfowl** [comment]
Seems like it isn't needed for the most part.
