### ISSUE TITLE
SignalR-Client-Cpp: Make jsoncpp source inclusion optional

### ISSUE THREAD

**Issue by tonerdo** [dotnet/aspnetcore#30888]
### Is your feature request related to a problem? Please describe.
The Microsoft Mesh SDK depends directly on both SignalR-Client-Cpp and jsoncpp (we statically link with them). The direct inclusion of jsoncpp source in SignalR-Client-Cpp means that we run into "duplicate symbols" errors/warnings when trying to build our project. We currently patch our copy of the repo to workaround this issue.

### Describe the solution you'd like
Addition of a CMake option `-DINCLUDE_JSONCPP` (ON by default) that allows us to toggle the inclusion of jsoncpp source. Resorting to `find_package(jsoncpp ...)` when it's turned off. Happy to send in a PR if this issue is accepted.

### Additional context
N/A

**Comment by BrennanConroy** [comment]
My main concern is if you use a newer version of jsoncpp that has breaking changes this wouldn't work.

I'm not against the change, but are there any possible alternatives? Rr would we just need to stay up-to-date if there are any breaking changes.

**Comment by tonerdo** [comment]
I see it as, anyone who chooses to turn off including jsoncpp by default understands that they bear the responsibility of ensuring they link with a compatible version.

**Comment by BrennanConroy** [comment]
I agree with that.

Was just wondering if there was some way we could avoid that issue, like somehow mangling the names differently when it's built in.

> Happy to send in a PR if this issue is accepted.

That would be very welcome!
