### ISSUE TITLE
how to load a site in parts

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#30881]
For example, I will make a game that weighs 200 mb of code, can I load it in parts and not at the very beginning?

**Comment by davidfowl** [comment]
What sort of game? What are the parts? Is it using Blazor? 200MB of dlls or something else?

**Comment by twepl** [comment]
@davidfowl   I gave this as an example, for example, if I have 200 MB of C# code

**Comment by davidfowl** [comment]
200MB of C# code meaning what? Source files? Binaries? Is it a single dll? Multiple? It's not clear from the description what you mean and what you're trying to optimize.

**Comment by twepl** [comment]
I want to load data in parts when switching pages

**Comment by benaadams** [comment]
Check the docs [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0)

**Comment by twepl** [comment]
@benaadams and if I go back and go to this page again, will it load the components again?
otherwise I don't want to download the same thing a hundred times
