### ISSUE TITLE
Switch access level of _idleTimeout in DistributedSession from prive to protected

### ISSUE THREAD

**Issue by vvopenka** [dotnet/aspnetcore#30890]
## Background and Motivation

In our application we have a requirement to set different IdleTimeouts for our session based on how strong the session is. If the session was establised on trusted device or after email verification of new device it can be active much longer, than if the session was established on untrusted device.

Hence we would need to set / modify idleTimeout in a controller while the app is running and not only in Startup.

Right now we would have to implement entire session ourselves. If DistributedSession hand _idleTimeout annotated as protected, we could override DistributedSession, get all it's functionality for free and only handle _idleTimeout ourselves.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Session
{
    public class DistributedSession : ISession
    {
        private const int IdByteCount = 16;

        private const byte SerializationRevision = 2;
        private const int KeyLengthLimit = ushort.MaxValue;

        private readonly IDistributedCache _cache;
        private readonly string _sessionKey;
-        private readonly TimeSpan _idleTimeout;
+       protected TimeSpan _idleTimeout;
...
}
```

## Usage Examples

``` C#
public class MySession : DistributedSession 
{
    //constructor
   public TimeSpan IdleTimeout
   {
      get {
           return _idleTimeout;
      }
      set {
           this._idleTimeout = value;
      }
   }
}

public class MySessionStore : ISessionStore
{
    public ISession Create(string sessionKey, TimeSpan idleTimeout, TimeSpan ioTimeout, Func<bool> tryEstablishSession, bool isNewSessionKey)
        {
            if (string.IsNullOrEmpty(sessionKey))
            {
                throw new ArgumentException(Resources.ArgumentCannotBeNullOrEmpty, nameof(sessionKey));
            }

            if (tryEstablishSession == null)
            {
                throw new ArgumentNullException(nameof(tryEstablishSession));
            }

            return new MySession(_cache, sessionKey, idleTimeout, ioTimeout, tryEstablishSession, _loggerFactory, isNewSessionKey);
        }
}

public class Startup
{
   public void ConfigureServices(IServiceCollection services)
   {
      services.AddTransient<ISessionStore, MySessionStore>();
       services.AddSession(options => {
           options.IdleTimeout = new TimeSpan(0, 15, 0);
       });
   }
}

public class SessionMiddleware
{
   public async Task Invoke(HttpContext httpContext, AppSession appSession)
   {
        appSession.LoadFromSessionStorage(httpContext.Session);
        if (appSession.IsSecure) {
             (httpContext.Session as MySession)?.IdleTimeout = new TimeSpan(12, 0, 0);
        }
   }
}
```

## Alternative Designs

Alternatively you could expose the IdleTimeout directly as property. But I think that it's too invasive.

I'm willing to send a PR if it's accepted.

**Comment by Tratcher** [comment]
> In our application we have a requirement to set different IdleTimeouts for our session based on how strong the session is. If the session was establised on trusted device or after email verification of new device it can be active much longer, than if the session was established on untrusted device.

Is this conflating a user session with a browser session? Browser sessions are intentionally short term caches to limit more expensive resource accesses like database hits. They also should not contain any authentication related data. That you're basing this on a device or e-mail address implies it's tied to an explicit user. Long lived user data (hours) should be backed by a more persistent store and only cached in the browser session.

As for the API, I'm not sure why DistributedSession was ever public, and it's not well designed to derive from. Having to down cast to a derived type to consume it isn't a clean pattern either.

A slightly more flexible option would be to add a new abstraction like:
```
interface IVariableSession : ISession
{
  Timespan IdleTimeout { get; set; }
}
```

And then have DistributedSession implement IVariableSession. It would still require casting to IVariableSession to consume, but at least that's not a concrete type, and that cast could be hidden by an extension method on ISession.  C# 8 Default Interface Methods would be another way to add this property to ISession and would avoid the cast.
