### ISSUE TITLE
Can't debug Blazor app in Teams

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30898]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-debug-Blazor-app-in-Teams/1364929)._

---
[severity:It's more difficult to complete my work]
Trying to attach the debugger to teams a terams instance with remote debugging enabled gives an error:

Value cannot be null.
Parameter name: source

---
#### Feedback Bot on 3/10/2021, 06:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
