### ISSUE TITLE
VS 16.9.1 Blazor Web Assembly (hosted) no longer hands URL to Edge browser on F5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30897]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-1691-Blazor-Web-Assembly-hosted-n/1364936)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9]
I worked yesterday with a Blazor Web Assembly project (ASP.NET-hosted) and debugging worked nicely. Upgraded to 16.9.1 today before work, and now I have the following issue: my project is set to start the server project (not via IIS but directly). Without having changed a thing since yesterday except the version upgrade, I can Ctrl+F5 where Edge is opened and Edge navigates to https://localhost:5001 - everything works. If, however, I press F5, yes, Edge is opened, but it stays at about:blank. 

If I manually enter https://localhost:5001, I can access the Blazor Web Assembly app, but the debugger isn't attached and after some time (mostly on closing Edge) I get

---------------------------
Microsoft Visual Studio
---------------------------
One or more errors occurred.

Failed to launch debug adapter.  Additional information may be available in the output window.

Exception of type 'Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.ProtocolException' was thrown.
---------------------------
OK   
---------------------------

Going to Debug properties and entering the URL in the text box next to the "Launch browser:" text box doesn't do anything either (it was empty all along before).

---
#### Feedback Bot on 3/10/2021, 06:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Christoph Wille solved on 3/10/2021, 03:38 AM, 0 votes: 

<p>Another reboot fixed this (had rebooted after Windows updates, but not after VS update). Don’t know how that fixed it but it did.</p>

**Comment by pranavkm** [comment]
Looks like this was a local issue that was resolved after restarting.
