### ISSUE TITLE
Cannot debug a Blazor Net core hosted project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30900]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-debug-a-Blazor-Net-core-hosted-pr/1361248)._

---
[regression] [worked-in:Version prior to 16.9]
Hi,
After upgrading to V 16.9 I cannot debug neither Client nor Server apps. It simply runs as if there were no breakpoints.

I also tried using Ctl Shift D and there is no way to get files for debugging... What have you done???

---
#### Feedback Bot on 3/8/2021, 06:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
It looks like this issue is being raised by the JS debugger. Looped in the team on the DevOps issue. Closing as external.
