### ISSUE TITLE
how to speed up website loading on blazor?

### ISSUE THREAD

**Issue by twepl** [dotnet/aspnetcore#30906]
I want to learn methods of quickly opening a site, as well as remembering the page where the user stopped and for some reason refreshed the page.

**Comment by benaadams** [comment]
`render-mode="ServerPrerendered"`

[Prerender and integrate ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0&pivots=server)

**Comment by twepl** [comment]
@benaadams it looks like the same as this https://github.com/jdtcn/HybridBlazor
The problem is I don't want to use Blazor Server, it requires ASP.NET to be installed
Therefore, I need to do everything in Blazor WebAssembly

**Comment by javiercn** [comment]
@twepl thanks for contacting us.

If you don't have access to a server and can't use prerendering your options are limited. You can try and use techniques like https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content to parallelize the resource download, but even that is going to give you limited benefits.

**Comment by twepl** [comment]
@javiercn thanks, but this does not suit me

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the blazor tag to reach a wider audience.
