### ISSUE TITLE
Add JS isolation

### ISSUE THREAD

**Issue by talley** [dotnet/aspnetcore#30902]
Add  JS isolation like this

Index.cshtml
Index.cshtml.css
Index.cshtml.js
![js isolation](https://user-images.githubusercontent.com/6354720/111018923-0191f400-838a-11eb-83c8-b12b768b7eb0.png)

**Comment by javiercn** [comment]
@talley thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/30850
