### ISSUE TITLE
Blazor Wasm 6.0.0 Preview 2: Launching via IIS Express no longer works.

### ISSUE THREAD

**Issue by makotech222** [dotnet/aspnetcore#30917]
### Describe the bug
In upgrading a blazor wasm app from .net 5.0 to .net 6.0 preview 1 + preview 2, I can no longer launch the application using the IIS Express launch profile in Visual studio 16.10 Preview 1. The specific error when launching into browser is: 

HTTP Error 500.33 - ANCM Request Handler Load Failure
Could not find the assembly 'aspnetcorev2_inprocess.dll' referenced for the in-process application. Please confirm the Microsoft.AspNetCore.Server.IIS or Microsoft.AspNetCore.App is referenced in your application.

In addition, creating a brand new wasm app using .net 6 preview 2 has the same issue.

### To Reproduce
Using Visual Studio 16.10 Preview 1, create a new blazor wasm app, using .net 6 preview 2. Make sure ASP NET Core hosting is turned off. Run the application using the default IIS Express launch profile.

### Further technical details
- .net 6.0 Preview 2
- .NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 16.10 Preview 1.

**Comment by pranavkm** [comment]
I imagine this isn't blazor specific. Are there docs for using preview builds of the SDK + IIS?

**Comment by pranavkm** [comment]
@makotech222 do you also see this issue if you create a brand new MVC or Razor Pages app?

**Comment by danroth27** [comment]
I'm able to repro this with .NET 6 Preview 2 and VS 16.10 Preview 1. It only repros with the standalone Blazor WebAssembly template.

**Comment by makotech222** [comment]
> 
> 
> @makotech222 do you also see this issue if you create a brand new MVC or Razor Pages app?

Those app types work fine, as normal. Only blazor wasm app is affected.

**Comment by mkArtakMSFT** [comment]
This is the same as https://github.com/aspnet/AspNetCore-ManualTests/issues/405, which we track internally.
