### ISSUE TITLE
Make consuming ProblemDetails responses easier from a Blazor WASM app

### ISSUE THREAD

**Issue by Jimmys20** [dotnet/aspnetcore#30910]
Hello, right now the` ProblemDetails` and `ValidationProblemDetails` classes and their JsonConverters `ProblemDetailsJsonConverter` and` ValidationProblemDetailsJsonConverter` are defined in the `Microsoft.AspNetCore.Mvc.Core` package. I want to consume an API that returns `ProblemDetails` error responses from a Blazor wasm application. To be able to deserialize the responses I have to include the whole `Microsoft.AspNetCore.Mvc.Core` package or implement my own `ProblemDetails` classes and JsonConverters. It would be nice if we could use the `ProblemDetails` model classes provided in the MVC package without having to add the MVC dependency to the project. How do you suggest implementing the following code
```
var jsonStream = await response.Content.ReadAsStreamAsync();
var problemDetails = await JsonSerializer.DeserializeAsync<ProblemDetails>(jsonStream);

// The name 'ProblemDetails' does not exist in the current context
```
when using HttpClient outside of an MVC Application e.g. in a Blazor wasm or Console application.

**Comment by pranavkm** [comment]
At this point, we think having a copy of the code from MVC would be the way to go. If you happen to need to do this often, consider publishing a NuGet package that supports this so others may be able to take advantage of this.

**Comment by Jimmys20** [comment]
Thanks for the quick answer!

**Comment by StingyJack** [comment]
This class is also used in NSwag's generated api clients, Id rather take the [package that this class is listed in](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-5.0) but the package manager wont let me install it.

Why wouldnt something like this just go into an abstractions or primitives package anyway?  Making copies seems like the wrong thing to have to be doing (like having to root your mobile to get rid of preinstalled cruft).  @pranavkm - Are you sure there isnt a better solution than that?
