### ISSUE TITLE
JWT Authentication Events Return Incorrect HTTP Status Codes

### ISSUE THREAD

**Issue by tymur999** [dotnet/aspnetcore#30918]
The ```JwtBearerOptions.Events``` when ```.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(...)``` is injected does not return the correct http status codes as specified. When adding these events to be called when the request is challenged or forbidden, the ```WriteAsJsonAsync``` method specifically describes that it will return a 200 HTTP status. This occurs normally with the OnChallenge handler, where a 200 is returned, but OnForbidden still returns a 403 even though the same method ```WriteAsJsonAsync``` says that it will return 200 HTTP status.
```
.AddJwtBearer(options =>
                {
                    options.Events = new JwtBearerEvents
                    {
                        OnChallenge = ctx =>
                            ctx.Response.WriteAsJsonAsync(<response object here>), //Returns 200, normal
                        OnForbidden = ctx =>
                            ctx.Response.WriteAsJsonAsync(<response object here>) //Returns 403, but supposed to be 200
                    };
                });
```
I know that 403 really means forbidden, and it says that is what is supposed to be returned for ```OnForbidden``` in [MS Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbearerevents.onforbidden?view=aspnetcore-5.0#Microsoft_AspNetCore_Authentication_JwtBearer_JwtBearerEvents_OnForbidden), but the ```WriteAsJsonAsync``` specifically says that 
> "the status code [will be] set to 200."

**Comment by tymur999** [comment]
Found a temporary solution
```
OnForbidden = ctx =>
{
     ctx.Response.StatusCode = 200;
     ctx.Response.WriteAsJsonAsync(<response object here>);
}

**Comment by Tratcher** [comment]
WriteAsJsonAsync originally set the status code to 200, but that changed to use the current value before 5.0 released. The docs didn't get updated until later (https://github.com/dotnet/aspnetcore/pull/27108).

The Challenge code path doesn't set the default 401 status code until after the event. By the way, you need to call `ctx.Handled()` on that event context to prevent errors later.
https://github.com/dotnet/aspnetcore/blob/891dd0fa6f16c4cd24aaeead57ece03fb098d83a/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L218-L224

The Forbid code path sets the 403 before calling the event. Not sure why they're inconsistent.
https://github.com/dotnet/aspnetcore/blob/891dd0fa6f16c4cd24aaeead57ece03fb098d83a/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L280-L281
