### ISSUE TITLE
Option to enable automatic renew of tokens

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#30929]
### Is your feature request related to a problem? Please describe.
The oidc-client supports a setting to automatically renew the token before it expires, but it is not supported in the C# API.
See https://github.com/IdentityModel/oidc-client-js/wiki under automaticSilentRenew.

Example: I am trying to do
```
         builder.Services.AddOidcAuthentication(options =>
         {
            options.ProviderOptions.AutomaticSilentRenew = true;

```

### Describe the solution you'd like
This should be available to set, and the default should be true.

### Additional context
If the access token is not renewed, and the refresh token expires before next request it may cause the problem seen in #30927

**Comment by javiercn** [comment]
@davhdavh thanks for contacting us.

We automatically renew tokens silently under the hood.
