### ISSUE TITLE
Duplicate code in RemoteAuthenticationService

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#30928]
### Is your feature request related to a problem? Please describe.
The 2 overloads of RequestAccessToken does the exact same thing, except for a single parameter sent to jsinterop.

### Describe the solution you'd like
Remove duplicate code

**Comment by javiercn** [comment]
@davhdavh thanks for contacting us.

The MSAL.JS implementation uses the overloads to request different tokens from the IdP, we don't do that in the default implementation since we haven't seen that be a common pattern in other OIDC providers.
