### ISSUE TITLE
Single file View Component

### ISSUE THREAD

**Issue by gulshan** [dotnet/aspnetcore#30920]
Most of the time my `ViewComponent`s are just passing the model argument to the view file, without any modification or any other type of processing-
```csharp
public class PriorityListViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(TodoItems items) => View(items);
}
```

It would be nice to have an option to get rid of these boilerplate `ViewComponenet` classes and define View Components using only a single file- the razor/view like this-
```cshtml
@model IEnumerable<ViewComponentSample.Models.TodoItems>

<h3>Priority Items</h3>
<ul>
    @foreach (var todo in Model)
    {
        <li>@todo.Name</li>
    }
</ul>
```

Although the ViewComponent class also provides the name of the View Componenet, it can be done with a `@ViewComponentName` property in the razor/view file itself. Or it can be generated from the file name or file path of the view file, following a naming convention.

I think this feature will also encourage lean/thin View Components, where View Components are just rendering the views and not doing other processing.

**Comment by javiercn** [comment]
@gulshan thanks for contacting us.

You could use a razor component for that (.razor file) and render it using the `<component>` tag helper.

**Comment by gulshan** [comment]
@javiercn Isn't .razor files Blazor-only? Does it integrate well with .cshtml views?

**Comment by javiercn** [comment]
@gulshan you can render a component from a regular razor page. There are 3 render modes (static, server, webassembly) the latter two are for Blazor applications, but the first one can be used in an MVC application. If you have a small widged that just displays UI from the database or something like that, it should work.

**Comment by gulshan** [comment]
Thanks.
