### ISSUE TITLE
Blazor component not re-rendering after @onclick when button is inside of a form

### ISSUE THREAD

**Issue by RelevantJesse** [dotnet/aspnetcore#30926]
### Describe the bug
I'm not sure if this is a bug, but if it's not, I'm hoping to get more clarification for why this is happening.

If I have a button inside of a form and that button has an @onclick, the form doesn't rerender after the onclick handler. Adding a `StateHasChanged()` has no effect, either.

### To Reproduce
```cs
<form>
    <button type="submit" class="btn btn-primary" @onclick="@AddBook">Add a new book</button>
</form>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Book book in allBooks)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author.FirstName @book.Author.LastName</td>
            </tr>
        }
    </tbody>
</table>

@code {
    private List<Book> allBooks;
    protected override async Task OnInitializedAsync()
    {
        allBooks = await BookService.GetAllBooksAsync();
    }
    private async Task AddBook()
    {        
        Book addedBook = new Book
        {
            Title = "This is a test"
        };
        allBooks.Add(addedBook);
    }
}
```

### Further technical details
- .NET 5
- Blazor Server
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.516 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio Professional 2019 v16.9.1

**Comment by SteveSandersonMS** [comment]
>     <button type="submit" class="btn btn-primary" @onclick="@AddBook">Add a new book</button>

The issue is in the code above. This button causes the enclosing `<form>` to be submitted to the server, which reloads the page and resets its state.

To avoid doing that, change `type="submit"` to `type="button"`, e.g.:

```razor
<button type="button" class="btn btn-primary" @onclick="@AddBook">Add a new book</button>
```
