### ISSUE TITLE
Default Blazor WASM PWA project template causes warning in Chrome 89+ - "Site cannot be installed: Page does not work offline."

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/aspnetcore#30925]
Not sure this is really a bug, but it is a problem ;-)

After creating a barebones Blazor WASM PWA project and running it in Chrome 89, we get the following warning:
`Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
`

![image](https://user-images.githubusercontent.com/888718/111078618-a92c3500-84f6-11eb-8dc8-432b9479c951.png)

Repro:
https://github.com/ChristianWeyer/blazor-wasm-pwa-chrome-repro

-------

  ~ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.2
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

**Comment by javiercn** [comment]
@ChristianWeyer thanks for contacting us.

We'll take a look at this and update the issue accordingly.

**Comment by whereisaaron** [comment]
Google has [announced](https://stackoverflow.com/questions/62265576/blazor-wasm-pwa-offline-behaviour-with-server-side-requests) new requirements for the fetch handler, now required for a PWA to be installable from Chrome 93. Warnings start from Chrome 89. Fetch handles must succeed and return a 200, even when offline.
https://stackoverflow.com/questions/62265576/blazor-wasm-pwa-offline-behaviour-with-server-side-requests

Google also has an [article](https://web.dev/install-criteria/) of the total requirements to be a PWA that can be installed by Chrome.
https://web.dev/install-criteria/

While you are looking at this, note that both a 512px and a 192px icon are required by Chrome now. I think Blazor .Net 5.0 template only includes a 512px icon by default?

![image](https://user-images.githubusercontent.com/1109585/112753156-29d45080-9022-11eb-97d7-41d971d4e584.png)

**Comment by whereisaaron** [comment]
This is someone attempt to I think solve the same problem with the Blazor fetch handler that Google is now targeting:
https://stackoverflow.com/questions/62265576/blazor-wasm-pwa-offline-behaviour-with-server-side-requests

They reference this Google example:
https://googlechrome.github.io/samples/service-worker/custom-offline-page/

> I've created a new project using the default project template for a Blazor Webassembly app, with identity, asp.net core hosted, and PWA options checked. This gives us a WASM blazor SPA app with some basic offline PWA ability, and a server-side asp.net core app.
> 
> When authenticating with identity, the pages are served by the Server app. As such, they can't be reached when the app is running offline. This is to be expected, but the user experience (out of the box) in this scenario is poor with default 404, or "you have no internet" pages rendered by the browser.
> 
> I'd like to clean this up so the user is safely/gracefully warned about the failure to GET the remote pages.

**Comment by captainsafia** [comment]
It looks like Chrome is putting the plans to add these validations on hold.

https://developer.chrome.com/blog/improved-pwa-offline-detection/.

> Updated April 14th, 2021: We previously announced plans to update the installability criteria to ensure a PWA actually provides an offline experience. After listening to your feedback, and discovering a number of issues, we have decided to put those plans on hold. We strongly believe providing a valid page when the user is offline is critical to providing a good user experience.

I also tried this on Edge 90.0.818.42 and it works fine.

So I don't think there's any work to do here for now.
