### ISSUE TITLE
Signalr Connection is Getting disconnected when using useresnposivecache  In .Net Core Blazor Server

### ISSUE THREAD

**Issue by Sharmila-Valiveti** [dotnet/aspnetcore#30933]
Iam having the below method which will start the plot hug connection.

```
 private async Task StartPlotHubConnection(string plotId)
        {
            if (string.IsNullOrEmpty(plotId))
                return;
            try
            {
                //If the connection is alive use it else disconnect/dispose and establish a new connection
                if (_plotUpdateHubConnection != null && _plotUpdateHubConnection.State == HubConnectionState.Connected)
                    return;

                if (_plotUpdateHubConnection != null)
                    await DisconnectPlotUpdateHubAsync();

                _plotUpdateHubConnection = new HubConnectionBuilder()
                    .WithUrl(Configuration["BaseUrls:PlotUpdateHubUrl"])
                    .ConfigureLogging(logging =>
                    {
                        logging.AddConsole();
                        logging.SetMinimumLevel(LogLevel.Debug);
                    })
                    
                    .WithAutomaticReconnect()
                    
                    .Build();
                
                _plotUpdateHubConnection.On<string>("ResetPlot", ResetPlotInNavigationView);
                _plotUpdateHubConnection.On<string, List<string>,List<string>>("PushTiles", PushTilesForTracks);

               
                await _plotUpdateHubConnection.StartAsync();

            }
            catch(OperationCanceledException ex)
            {

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
```

It is working fine when I havent added useresponsive middleware in restapi  project startup method .
But when I add the useresponsivecache middleware I was getting the following exception when startasync is called in blazor and connection is getting disconnected.

System.Threading.CancellationToken.ThrowOperationCanceledException() at System.IO.Pipelines.Pipe.GetReadAsyncResult() at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__80.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__58.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__58.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncInner>d__50.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__49.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Here is my startup file of restapi project .
In configure method:
```
 app.UseRouting();
          
            app.UseCors("DevPolicy");

            app.UseResponseCaching();
            app.UseAuthorization();
```

in configure services method:
```
 services.AddCors(policy => policy.AddPolicy("DevPolicy", corsPolicyBuilder =>
            {
                
                corsPolicyBuilder.AllowAnyOrigin()
                  .AllowAnyMethod()
                  .AllowAnyHeader();
            }));

            services.AddResponseCaching();
```

**Comment by BrennanConroy** [comment]
What TargetFramework are you targeting? What package versions do you have?

Can you share a simple, runnable repro app on github?
