### ISSUE TITLE
AuthenticationService.js cannot auth with popups

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#30930]
The oidc-client supports 2 different flows, one being the currently used redirect flow that alters the current url upon needing authentication, and another that opens a new popup window.
There is currently no way to use popup version in blazor since the API usage is locked to the usage of `signinRedirect` in `signIn` in https://github.com/davhdavh/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts .
The redirect flow has the huge disadvantage that it reloads the entire app multiple times
This applies to both signin and signout.

### Describe the solution you'd like
I would very much like a popup instead of the current redirect mess.
```
         builder.Services.AddOidcAuthentication(options =>
         {
            options.ProviderOptions.UsePopupsForAuthentication = true;
            options.ProviderOptions.FallbackToRedirectWhenPopupFails = false;
            options.ProviderOptions.PopupFailedCallback = async ()=> {...}; //or add support for it in the AuthorizeView or somwhere to have a CascadingParameter to indicate this state
//as per https://github.com/IdentityModel/oidc-client-js/wiki
            options.ProviderOptions.PopupWindowFeatures = "...";
            options.ProviderOptions.PopupWindowTarget = "_blank";


```

**Comment by javiercn** [comment]
@davhdavh thanks for contacting us.

We don't support Popup login in our implementation, but you can provide your own implementation to support it.
