### ISSUE TITLE
HeaderNames should introduce more of well-known security headers

### ISSUE THREAD

**Issue by Rinorragi** [dotnet/aspnetcore#30932]
### Is your feature request related to a problem? Please describe.
I am trying to implement some hardening to web application via introducing security headers. Only some of those are known by [HeaderNames](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Headers/src/HeaderNames.cs). This makes implementing those more errorprone as I need to hardcode those.  

### Describe the solution you'd like
Add more headers to HeaderNames class. I am considering following ones:

- Report-To [https://www.w3.org/TR/reporting/#header](https://www.w3.org/TR/reporting/#header)
- X-Content-Type-Options [https://www.iana.org/assignments/message-headers/message-headers.xml#perm-headers](https://www.iana.org/assignments/message-headers/message-headers.xml#perm-headers)
- Referrer-Policy [https://www.w3.org/TR/referrer-policy/](https://www.w3.org/TR/referrer-policy/)
- Permissions-Policy [https://www.w3.org/TR/permissions-policy-1/](https://www.w3.org/TR/permissions-policy-1/)
- Cross-Origin-Embedder-Policy [https://html.spec.whatwg.org/multipage/origin.html#embedder-policy](https://html.spec.whatwg.org/multipage/origin.html#embedder-policy)
- Cross-Origin-Opener-Policy [https://html.spec.whatwg.org/multipage/origin.html#cross-origin-opener-policies](https://html.spec.whatwg.org/multipage/origin.html#cross-origin-opener-policies)
- Cross-Origin-Resource-Policy [https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header)

Then there are two that I would want to add which are kind of echoes from old world but are still suggested to add when hardening web site security to support older clients.
- X-Permitted-Cross-Domain-Policies
- X-XSS-Protection

**Comment by blowdart** [comment]
There's already a few open-source middlewares for security headers that take care of these (and our own CORS middleware). 

Is there any reason those don't fit the bill for you?

**Comment by Rinorragi** [comment]
Good questions. I did not come up any better solution than just adding them up by hand. It would be handy if you would list the middlewares that you meant so I could check them out. I am sure that I am not aware of everything done in open-source. Even thought middlewares would exists it would be nice to have popular HTTP headers in the headernames file. 

Report-To header would be nice to be implemented as a middleware in the but that is an issue for another time. Also I am not entirely sure that the reporting scheme won't change anymore. But it would be nice piece for developers to catch browser problems directly to backend without third party services, software or dependencies. I haven't seen such thing as open source library. 

X-Content-Type-Options nosniff protects against MIME sniffing type of attacks. It is advised to used by OWASP Security headers project and other sources. Did not find any middleware for that when looking.

Referrer-policy helps in controlling what kind of information is leaked to third parties with referrer header. I did not find middleware for that either although it could be handy too. 

Permissions-policy is to be replacing Feature-Policy and would be also handy as a middleware but I did not find middlewares to either Feature-Policy nor Permissions-Policy. 

COOP, CORP and COEP are also relatively new and best explained maybe in Scott Helme`s blog post: https://scotthelme.co.uk/coop-and-coep/. They are related to CORS but in my case I would rather just tighten the screw instead of trying to allow CORS. Then COOP, CORP and COEP makes more sense than using CORS middleware. 

So all in all each of those enhances my solutions security posture and I would need them. I would assume that many others are in same position.  I can add them as hard coded but it would be better if they would be in HeaderNames files.

Oh and one more thing. Popular HTTP security header scanners like securityheaders.com and mozilla observatory check many of these mentioned headers.

**Comment by BrennanConroy** [comment]
Our list is not exhaustive (obviously) and we generally only include headers used by the framework.
Without a good reason for including these we're unlikely to make any changes.

You can write a class that contains these values yourself so that it's less error-prone.

**Comment by Rinorragi** [comment]
My thoughts were that as these are commonly used and often implemented with custom middlewares to software it would make sense to introduce them along other headers in the headernames class. My own experience is that I need to either implement these at each project or to host my own NuGet package to introduce these along implementation. Having them in the core framework would make a slightly easier and less error-prone. If the demand is to make implement features on top of them then I think that there could be middlewares for many of those in a same manner as HSTS is implemented. I could rewrite the issue (or open new one) if you want if that sounds better. 

Nevertheless for me security is important and anything that drives direction that it is easier to implement highly secure public services is a good reason for me. Although I really understand your take too.
