### ISSUE TITLE
Use the framework implementation of PBKDF2/RFC2898

### ISSUE THREAD

**Issue by omajid** [dotnet/aspnetcore#30941]
This is a follow up from https://github.com/aspnet/DataProtection/issues/272, https://github.com/dotnet/aspnetcore/issues/2508 and https://github.com/dotnet/runtime/issues/24897.

> ASP.NET has its own implementation of RFC2898 because it needs top-of-the-line performance for password hashing in order to have acceptable latency for login scenarios. If we bring these performance improvements to the framework's implementation of these APIs, ASP.NET can remove its own implementation and rely on the standard classes.

This was recently fixed via https://github.com/dotnet/runtime/pull/48107.

This bug/feature-request is to track that ASP.NET Core picks up and uses that API and removes its duplicate implementation.

cc @bartonjs @blowdart @GrabYourPitchforks @tmds @Tornhoof @vcsjones

**Comment by blowdart** [comment]
@HaoK

**Comment by HaoK** [comment]
Cool, I'll combine this into the existing span issue

**Comment by omajid** [comment]
Hi @HaoK ! Are there any plans to remove the managed implementation and/or Win7Pbkdf2Provider/Win8Pbkdf2Provider implementations? Will those be kept around for compatibility?

**Comment by HaoK** [comment]
Unfortunately we still have to support netstandard and net461, we can't use the new one shot pbdkdf2 in those target frameworks right?

**Comment by HaoK** [comment]
Is the new API faster than the Win8/Win7 implementations as well?

**Comment by vcsjones** [comment]
> we can't use the new one shot pbdkdf2 in those target frameworks right?

Correct. It is .NET 6.

> Is the new API faster than the Win8/Win7 implementations as well?

It should be "as fast or better". It borrows many ideas from the DataProtection implementation for Windows, and has a slight allocation improvement for Windows 10+.

On MacOS it uses CommonCrypto from the underlying OS, and for Linux it uses openssl.

**Comment by HaoK** [comment]
Cool, so sounds like we should just switch to always using this on netcoreapp, and keeping the old branching providers only for non netcoreapp, I'll open a PR tomorrow, thanks for pointing this out

**Comment by omajid** [comment]
Thanks!
