### ISSUE TITLE
Blazor RemoteAuthenticatorView OnLogOutSucceeded Callback results in multiple log out attempts.

### ISSUE THREAD

**Issue by hojlind** [dotnet/aspnetcore#30943]
### Describe the bug
When adding a OnLogOutSucceeded Callback method, that is located in the parent component (Authentication.razor in template), the log out flow is run multiple times. This seems to happen because the EventCallback results in a re-render. According to [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-5.0), a re-render should not affect Child components, if they utilize immutable primitive types:

> Components inherited from ComponentBase skip rerenders due to parameter updates if either of the following are true:
> - All of the parameter values are of known immutable primitive types (for example, int, string, DateTime) and haven't changed since the previous set of parameters were set.

### To Reproduce
To reproduce the issue clone [this minimalist repo](https://github.com/hojlind/BlazorRemoteAuth) and add a provider:
When run as is, logging out will result in both a logged-out and a logout-failed redirect.

### Further technical details
- ASP.NET Core version: 5.0
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [/usr/share/dotnet/sdk]
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS Code 1.54.1

**Comment by mariangemarcano** [comment]
@javiercn / @mkArtakMSFT do you have a suggestion about how we could do a callback upon success login without hitting this issue?

**Comment by mariangemarcano** [comment]
We also notice that using `<LogOutSucceeded>` also fails, for now we will be adding the logic on `<LogOut>`, which seems to be working consistently:

```
<RemoteAuthenticatorView Action="@Action">
    <LogOut>
        @{
             // logout logic here
        }
    </LogOut>
</RemoteAuthenticatorView>
```

**Comment by javiercn** [comment]
Fixed in RC2 by https://github.com/dotnet/aspnetcore/issues/39507
