### ISSUE TITLE
Performance: Avoid Array allocations caused by List resize

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#30959]
From https://github.com/dotnet/aspnetcore/issues/30247#issuecomment-797162033.

We've got a lot of places in our SemanticTokens code where arrays are being allocated on the LOH as a list resizes. That can be avoided by using a SegmentedList instead.

Allocations on the LOH are particularly bad because in forces a GEN2 collection, which is the slowest type, so be extra diligent in avoiding these.

**Comment by ryanbrandenburg** [comment]
Compared to total VS allocations this isn't actually THAT bad. Therefore do a quick investigation, but if the fix isn't easy (and clear) it's not worth it at this time.

**Comment by NTaylorMullen** [comment]
Notes from planning: If the work here exceeds .5d, abort and throw the issue back into the backlog.

**Comment by ryanbrandenburg** [comment]
I would say don't even backlog it, just close. If it ever justifies >.5 days it will show up in future profiling efforts.

**Comment by allisonchou** [comment]
Poked around and talked to @ryanbrandenburg. We both agreed that it may be good to just table this for now. It seems getting this into the repo, combined with the potential upkeep, may not currently be worth it (various nuget + source gen stuff to deal with). Closing this issue for now and will re-open if the list allocations end up being a larger issue in the future.
