### ISSUE TITLE
Unable to use IAsyncDisposable scoped service inside of an hosted service in ASP.NET core 3.1

### ISSUE THREAD

**Issue by EnricoMassone** [dotnet/aspnetcore#30964]
I have a simple test project implemented by using `ASP.NET core 3.1` and the` ASP.NET core web application` template in the `API` flavour.

This is the `csproj` file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>
```

I have defined an `IBar` interface and a `Bar` implementation class as follows. Notice that class `Bar` implements `IAsyncDisposable`:

```
namespace WebApplication1
{
  public interface IBar
  {
  }
}
```

```
using System;
using System.Threading.Tasks;

namespace WebApplication1
{
  public sealed class Bar : IBar, IAsyncDisposable
  {
    public async ValueTask DisposeAsync()
    {
      await Task.Delay(500).ConfigureAwait(false);
    }
  }
}
```

This is the `Program` class: 

```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace WebApplication1
{
  public class Program
  {
    public static void Main(string[] args)
    {
      CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
              webBuilder.UseStartup<Startup>();
            });
  }
}
```

This is the `Startup` class. Notice that class `Bar` is registered as a scoped service and that an hosted service (`BarHostedService`) is registered also:

```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication1
{
  public class Startup
  {
    public Startup(IConfiguration configuration)
    {
      Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
      services.AddControllers();
      services.AddScoped<IBar, Bar>();
      services.AddHostedService<BarHostedService>();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }

      app.UseRouting();

      app.UseAuthorization();

      app.UseEndpoints(endpoints =>
      {
        endpoints.MapControllers();
      });
    }
  }
}

```

The code for `BarHostedService` is as follows. The pattern used to consume a scoped dependency from the hosted service is the same documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task). 

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace WebApplication1
{
  public sealed class BarHostedService : BackgroundService
  {
    private readonly IServiceProvider _container;

    public BarHostedService(IServiceProvider container)
    {
      _container = container;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
      using (var scope = _container.CreateScope()) 
      {
        var bar = scope.ServiceProvider.GetRequiredService<IBar>();
        await Task.Delay(2000).ConfigureAwait(false);
      }
    }
  }
}
```
The host starts, the `BarHostedService` is started as expected and the host application is able to receive and handle HTTP requests. But, there are the following problems with the `BarHostedService`:

- `BarHostedService` is not completed successfully. An `InvalidOperationException` is thrown when the dependency injection scope is disposed, at the end of the using code block
- as a consequence of the previous point, `Bar.DisposeAsync` is never called

This is the  `InvalidOperationException` thrown inside `BarHostedService`:

```
System.InvalidOperationException: 'WebApplication1.Bar' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
```

Is this behavior expected ? 

Is there a way to consume a scoped service implementing IAsyncDisposable from an hosted service ?

I have noticed that, contrary to the case of hosted services, **it is possible to consume a scoped service implementing IAsyncDisposable from a controller**, but even in that case something unexpected happens (`DisposeAsync` is called twice), as I have documented in #30963

**Comment by EnricoMassone** [comment]
This is probably related to [this issue in the dotnet runtime repo](https://github.com/dotnet/runtime/issues/43970).
The proposed workaround of casting the DI scope to `IAsyncDisposable` works, as mentioned there. 
Based on my understanding, a new API will be released along with .NET 6, correct ?

**Comment by EnricoMassone** [comment]
@javiercn it's worth noticing that when using the workaround suggested in dotnet/runtime#43970 in order for the worker service being able to consume the scoped service, the same behavior describer in #30963 happens: `Bar.DisposeAsync` is called **twice**.

This is the hosted service class modified as suggested in dotnet/runtime#43970

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace WebApplication1
{
  public sealed class BarHostedService : BackgroundService
  {
    private readonly IServiceProvider _container;

    public BarHostedService(IServiceProvider container)
    {
      _container = container;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
      var scope = _container.CreateScope();

      var bar = scope.ServiceProvider.GetRequiredService<IBar>();
      await Task.Delay(2000).ConfigureAwait(false);

      await ((IAsyncDisposable)scope).DisposeAsync().ConfigureAwait(false);
    }
  }
}
```

This is the call stack of the first call to `Bar.DisposeAsync`:

![hosted-service-first-call](https://user-images.githubusercontent.com/29275408/111317626-9df71780-8664-11eb-9fa8-b8c480dfd8c1.png)

This is the call stack of the second call to `Bar.DisposeAsync`:

![hosted-service-second-call](https://user-images.githubusercontent.com/29275408/111317720-b23b1480-8664-11eb-92d3-eda214935403.png)

Hope this helps in investigating.

**Comment by davidfowl** [comment]
This was fixed in .NET 6 https://github.com/dotnet/runtime/pull/43803.

**Comment by EnricoMassone** [comment]
> This was fixed in .NET 6 [dotnet/runtime#43803](https://github.com/dotnet/runtime/pull/43803).

@davidfowl thanks for the information. 

In order to use it from `.NET core 3.1` I'll go with the workaround mentioned in dotnet/runtime#43970 (explicit cast of the scope to `IAsyncDisposable`). 

Is there any issue with that ? Apart from the double call to `DisposeAsync` it seems to work fine.

**Comment by davidfowl** [comment]
> Is there any issue with that ? Apart from the double call to Bar.DisposeAsync it seems to work fine.

Nope, that's what we do in the framework as well.

**Comment by EnricoMassone** [comment]
> > Is there any issue with that ? Apart from the double call to Bar.DisposeAsync it seems to work fine.
> 
> Nope, that's what we do in the framework as well.

@davidfowl thanks for the clarification. I think I can close the issue now.
