### ISSUE TITLE
ASP.NET core 3.1 calls DisposeAsync twice when scoped IAsyncDisposable dependency is injected in a controller

### ISSUE THREAD

**Issue by EnricoMassone** [dotnet/aspnetcore#30963]
I have a simple test project implemented by using `ASP.NET core 3.1` and the` ASP.NET core web application` template in the `API` flavour.

This is the `csproj` file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>
```

I have defined an `IFoo` interface and a `Foo` implementation class as follows. Notice that class `Foo` implements `IAsyncDisposable`:

```
namespace WebApplication1
{
  public interface IFoo
  {
  }
}
```

```
using System;
using System.Threading.Tasks;

namespace WebApplication1
{
  public sealed class Foo : IFoo, IAsyncDisposable
  {
    public async ValueTask DisposeAsync()
    {
      await Task.Delay(500).ConfigureAwait(false);
    }
  }
}
```

This is the `Startup` class, notice that class `Foo` is registered as a scoped dependency:

```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication1
{
  public class Startup
  {
    public Startup(IConfiguration configuration)
    {
      Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
      services.AddControllers();
      services.AddScoped<IFoo, Foo>();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }

      app.UseRouting();

      app.UseAuthorization();

      app.UseEndpoints(endpoints =>
      {
        endpoints.MapControllers();
      });
    }
  }
}
```

For completeness, this is the `Program` class: 

```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace WebApplication1
{
  public class Program
  {
    public static void Main(string[] args)
    {
      CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
              webBuilder.UseStartup<Startup>();
            });
  }
}
```

In this web application I have defined a single `HomeController`, which requires an instance of `IFoo` as a constructor argument:

```
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
  [ApiController]
  public class HomeController : ControllerBase
  {
    private readonly IFoo _foo;

    public HomeController(
      IFoo foo)
    {
      _foo = foo;
    }

    [HttpGet("/")]
    public string Index()
    {
      return "Hello world";
    }
  }
}
```
When calling the path `/` the `HomeController` is instantiated and a brand new instance of `Foo` is injected as a constructor argument, then the `Index` action method is executed. This is, of course, the expected behavior. However, I noticed that `Foo.DisposeAsync` is called **twice per request**, while I would have expected it to be called **once per request**. Notice that by defining `Foo` as `IDisposable` (insted of `IAsyncDisposable`) this doesn't happen: method `Foo.Dispose` is called **once per request**, as I would expect. 

Why is that ? Is this a bug or expected behavior ?

Thanks for helping.

**Comment by javiercn** [comment]
@EnricoMassone thanks for contacting us.

Can you provide the two call stacks where DisposeAsync is being invoked?

**Comment by EnricoMassone** [comment]
> @EnricoMassone thanks for contacting us.
> 
> Can you provide the two call stacks where DisposeAsync is being invoked?

Hi and thanks for replying.

Here is the call stack of the first call to `Foo.DisposeAsync`:

![first-call](https://user-images.githubusercontent.com/29275408/111315862-1230bb80-8663-11eb-8735-caede5a3e0af.png)

This is the call stack of the second call to  `Foo.DisposeAsync`:

![second-call](https://user-images.githubusercontent.com/29275408/111315966-25438b80-8663-11eb-9d2a-8a8d8d4af83f.png)

**Comment by javiercn** [comment]
@EnricoMassone thanks for the additional details. I don't think based on the call stacks that this is MVC specific.

@davidfowl do you have any thoughts on here? For now I'm duping it in favor of https://github.com/dotnet/aspnetcore/issues/30964#issuecomment-800262761
