### ISSUE TITLE
Performance: String allocations from string.concat and StringBuilder

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#30962]
From https://github.com/dotnet/aspnetcore/issues/30247#issuecomment-797114222.

The following locations allocate a lot of strings (or char[]):
|Location|Type|Size (in bytes)|Iterations|LOH|
|-|-|-|-|-|
|RazorHtmlWriter.Ctor|char[]|38,575,520|154|Yes|
|RazorHtmlWriter.GetHtmlDocument|string|38,488,800|154|Yes|
|RazorCodeDocumentExtensions.GetSourceText|string|28,251,990|113|Yes|
|RazorCodeDocumentExtensions.GetSourceText|char[]|28,241,750|113|Yes|
|SyntaxNodeExtensions.GetContent|string|96,389,580|902|No|
|HtmlTokenizer.GetTokenContent|string|76,242,780|713|No|

Some of this (maybe even most) will end up being unavoidable because of the inherent string manipulation being done here, but we should do our best to minimize.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg does this impact tooling in any way?

**Comment by ryanbrandenburg** [comment]
Yes, because allocating ~304MB of memory (a lot of it on the LOH) over the course of ~60 seconds and just a couple keyboard operations is going to cause GC, and thus slowness of the VS experience.

**Comment by ryanbrandenburg** [comment]
I had a talk with Sam and now believe that these fixes are not worth the effort at this time. Though they allocate a lot, in relation to VS as a whole they're a small percentage and aren't the cause of any specific perf problems. In addition the fixes for them are not simple, so closing.
