### ISSUE TITLE
PreventDefault and StopPropagation behave unexpectedly when placed on a component (not HTML element)

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#30969]
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Components/Web/src/Web/WebRenderTreeBuilderExtensions.cs#L50

These two overloads should check the `value` parameter and avoid adding the frame all-together when value==`false`. It is likely that this went unnoticed since the common use case is to actually trigger the non-default value, but it can cause issues when you try to specify it based on a variable.

We didn't run into this case because the compiler prevents you from using them in components which is about the only case where they would get used indirectly.

**Comment by SteveSandersonMS** [comment]
The reason this happens is that `@onsomeevent:stopPropagation` (and preventDefault) were only intended for use on HTML elements, not on components. If you do this same thing on an HTML element then it does behave in the way you expect, i.e., if the bool value is `false` then no internal attribute is added. The reason why components are different is that, in more general cases, Razor doesn't assume that false bool parameters can be elided on components (only on HTML elements).

I'll update the title to match.
