### ISSUE TITLE
Invalid Sample for Custom AuthenticationStateProvider

### ISSUE THREAD

**Issue by ddobric** [dotnet/aspnetcore#30971]
When implemented as described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#authenticationstateprovider-service), the following exception is thrown:

### Exceptions 
```

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Extensions.DependencyInjection.WebAssemblyAuthenticationServiceCollectionExtensions.<>c__0`3[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions, Microsoft.Authentication.WebAssembly.Msal, Version=5.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].<AddRemoteAuthentication>b__0_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=5.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)

```

### Further technical details

Used Visual Studio 2019.

 ```
 <ItemGroup Condition="'$(TargetFramework)' == 'net5.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="5.0.4" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
  </ItemGroup>

```

Cross-reference: https://github.com/dotnet/AspNetCore.Docs/issues/21802
cc: @guardrex

**Comment by guardrex** [comment]
Thanks @ddobric.

I asked @ddobric to move this from the docs repo here because I can't repro a problem with the published code (when used exactly from the topic) in a test app.

**Comment by javiercn** [comment]
@ddobric thanks for contacting us.

Can you provide a minimal repro project that illustrates your issue? Otherwise it's very easy for us to miss some detail and be unable to reproduce it.

**Comment by ddobric** [comment]
Hi @javiercn ,

here is the minimal sample that causes the error.
If you comment out the selected line, the app starts correctly.

### Error stack trace

```
Debugging hotkey: Shift+Alt+D (when application has focus)
[0m[48;5;127m[38;5;231mblazor[0m[1m Loaded 9.43 MB resources
[0mThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.[0m
Loaded 9.39 MB resources from cache
Loaded 0.04 MB resources from network
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Extensions.DependencyInjection.WebAssemblyAuthenticationServiceCollectionExtensions.<>c__0`3[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions, Microsoft.Authentication.WebAssembly.Msal, Version=5.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].<AddRemoteAuthentication>b__0_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=5.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=5.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__1(ServiceProviderEngineScope p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>g__Initialize|2(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.1\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
```

[Issue30971.zip](https://github.com/dotnet/aspnetcore/files/6151756/Issue30971.zip)

**Comment by andrasdevs** [comment]
It looks like the casting to the `IAccessTokenProvider` provider causes the actual exception. If you implement that interface, your custom implementation can be used.

Here is the modified code:

```csharp
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components.Authorization;

public class CustomAuthStateProvider : AuthenticationStateProvider, IAccessTokenProvider
{
    public override Task<AuthenticationState> GetAuthenticationStateAsync()
    {      
        return Task.FromResult(new AuthenticationState(user));
    }
    public ValueTask<AccessTokenResult> RequestAccessToken()
    {
      return new(); // customize the result
    }
    public ValueTask<AccessTokenResult> RequestAccessToken(AccessTokenRequestOptions options)
    {
      return new(); // customize the result
    }
}
```

**Comment by DjeeBay** [comment]
The issue is still there and implementing IAccessTokenProvider is not enough.
The combination of a CustomAuthenticationStateProvider and AddMsalAuthentication doesn't work and we need to know what to do.

**Comment by DjeeBay** [comment]
I get it working by implementing IRemoteAuthenticationService<RemoteAuthenticationState> interface to my CustomAuthStateProvider.

By doing that we need to basically rewrite all the stuff in the [RemoteAuthenticationService](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs) and manipulate the methods according to the custom user you want to auth.

An official guide to do that could be great because it's not easy to find what to do and it's kind of basic use case I presume : you want to offer both custom auth and Msal auth.

**Comment by marcoCasamento** [comment]
I have that exact problem, and I've tried to implement both IRemoteAuthenticationService and IAccessTokenProvider, ending up with a so messy copy and paste of code that I eventually give up.
I put a switch on configuration that allows the application to be authenticated EITHER through custom auth OR MSAL. 
I do agree that this is a pretty basic requirement, even more urgent giving the lack of an identity server to be provided that could work-around the problem.

What would be the recommended way of solving the problem?

**Comment by joel-robb** [comment]
I'm going to join the thread to say I am now having the same issue nearly a year down the line and not able to find a solution...

@marcoCasamento and @DjeeBay, did either of you manage to find solutions to this problem?

**Comment by DjeeBay** [comment]
@joel-robb I don't know if it's good workaround but as I said I've rewrite the existing RemoteAuthenticationService to make it work (and it's still working on .Net 7) in my Blazor WASM app.

On my Server project I need to register my custom service "ApiAuthenticationStateProvider" like this :
`builder.Services.AddScoped<AuthenticationStateProvider, ApiAuthenticationStateProvider>();`

And ApiAuthenticationStateProvider is in my Client project and looks like this :
`using Blazored.LocalStorage;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
using Microsoft.Authentication.WebAssembly.Msal.Models;
using Microsoft.Extensions.Options;
using Microsoft.JSInterop;
using System.Security.Claims;

//SEE https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/RemoteAuthenticationService.cs
//SEE (ToDo) https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#customize-the-user

namespace ClientProject.Client.Providers
{
    public class SavedToken
    {
        public IEnumerable<Claim> Claims { get; set; }
        public LoginResult SavedLR { get; set; } = new LoginResult();
    }
    public class ApiAuthenticationStateProvider : AuthenticationStateProvider, ICustomAuthenticationStateProvider, IRemoteAuthenticationService<RemoteAuthenticationState>
    {
        private readonly ILocalStorageService _localStorage;
        private readonly IGenericRepository _genericRepository;
        private UserAccessToken _userAccessToken;
        protected RemoteAuthenticationOptions<MsalProviderOptions> Options { get; }
        protected AccountClaimsPrincipalFactory<RemoteUserAccount> AccountClaimsPrincipalFactory { get; }
        protected IJSRuntime JsRuntime { get; }
        protected NavigationManager Navigation { get; }
        private bool _initialized;
        private DateTimeOffset _userLastCheck = DateTimeOffset.FromUnixTimeSeconds(0);
        private ClaimsPrincipal _cachedUser = new ClaimsPrincipal(new ClaimsIdentity());
        private static readonly TimeSpan _userCacheRefreshInterval = TimeSpan.FromSeconds(60);
        private readonly AuthenticatingService _authenticatingService;
        private readonly JavaScriptLoggingOptions _loggingOptions;

        private bool firstTimeThrough = true;

        public ApiAuthenticationStateProvider(ILocalStorageService localStorage,
            IGenericRepository genericRepository,
            IJSRuntime jsRuntime,
            NavigationManager navigation,
            IOptionsSnapshot<RemoteAuthenticationOptions<MsalProviderOptions>> options,
            AccountClaimsPrincipalFactory<RemoteUserAccount> accountClaimsPrincipalFactory,
            AuthenticatingService authenticatingService,
            ILogger<RemoteAuthenticationService<RemoteAuthenticationState, RemoteUserAccount, MsalProviderOptions>> logger
            )
        {
            _localStorage = localStorage;
            _genericRepository = genericRepository;
            JsRuntime = jsRuntime;
            Navigation = navigation;
            Options = options.Value;
            AccountClaimsPrincipalFactory = accountClaimsPrincipalFactory;
            _authenticatingService = authenticatingService;
            _loggingOptions = new JavaScriptLoggingOptions {
                DebugEnabled = logger?.IsEnabled(LogLevel.Debug) ?? false,
                TraceEnabled = logger?.IsEnabled(LogLevel.Trace) ?? false
            };
        }

        public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            SavedToken savedToken = await GetTokenAsync();

            if (string.IsNullOrWhiteSpace(savedToken.SavedLR.Token)) {
                firstTimeThrough = false;
                return new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity()));
            }
            if (firstTimeThrough) {
                firstTimeThrough = false;
                await MarkUserAsAuthenticated(savedToken);
            }
            return new AuthenticationState(new ClaimsPrincipal(new ClaimsIdentity(savedToken.Claims, "jwt")));
        }
        //Public interface...no need for claims to be exposed
        public async Task MarkUserAsAuthenticated(LoginResult lr)
        {
            SavedToken st = await ParseToken(lr);
            await MarkUserAsAuthenticated(st);
        }
        private async Task MarkUserAsAuthenticated(SavedToken savedToken)
        {
            var authenticatedUser = new ClaimsPrincipal(new ClaimsIdentity(new[] { new Claim(ClaimTypes.NameIdentifier, savedToken.SavedLR.UserId) }, "apiauth"));
            var authState = Task.FromResult(new AuthenticationState(authenticatedUser));
            await _localStorage.SetItemAsync("authToken", savedToken.SavedLR.Token);
            await _localStorage.SetItemAsync("tokenExpire", savedToken.SavedLR.ExpirationDate);
            _genericRepository.SetToken(savedToken.SavedLR.Token);
            NotifyAuthenticationStateChanged(authState);
        }

        public async Task MarkUserAsLoggedOut()
        {
            var anonymousUser = new ClaimsPrincipal(new ClaimsIdentity());
            var authState = Task.FromResult(new AuthenticationState(anonymousUser));
            await _localStorage.RemoveItemAsync("authToken");
            await _localStorage.RemoveItemAsync("tokenExpire");
            _genericRepository.SetToken(string.Empty);
            NotifyAuthenticationStateChanged(authState);
            var aadToken = await _localStorage.GetItemAsync<string>("aadToken");
            if (!string.IsNullOrEmpty(aadToken)) {
                await _localStorage.RemoveItemAsync("aadToken");
                var context = new RemoteAuthenticationContext<RemoteAuthenticationState> {
                    State = new RemoteAuthenticationState() { ReturnUrl = $"{Navigation.BaseUri}login" }
                };
                try {
                    //TODO fix aad signout - should open a popup (try navigation.Logout on NET 7)
                    var result = await JsRuntime.InvokeAsync<StatusResponse>("AuthenticationService.signOut", context);
                } catch (Exception ex) {
                    Console.WriteLine(ex);
                }
            }
        }

        private async Task<SavedToken> GetTokenAsync()
        {
            var savedToken = await _localStorage.GetItemAsync<string>("authToken");
            var expireDate = await _localStorage.GetItemAsync<DateTime>("tokenExpire");
            return await ParseToken(new LoginResult() {
                Token = savedToken,
                ExpirationDate = expireDate
            });
        }

        private async Task<SavedToken> ParseToken(LoginResult lr)
        {
            if (string.IsNullOrWhiteSpace(lr.Token)) {
                return new SavedToken();
            }
            var tokenExpired = IsTokenExpired(lr.ExpirationDate);
            if (tokenExpired) {
                await MarkUserAsLoggedOut();
                return new SavedToken();
            }
            var claims = JwtParserUtils.ParseClaimsFromJwt(lr.Token);
            string userId = claims.Where(x => x.Type == "nameid").Select(x => x.Value).FirstOrDefault();
            return new SavedToken() {
                Claims = claims,
                SavedLR = new LoginResult() {
                    UserId = userId,
                    Token = lr.Token,
                    ExpirationDate = lr.ExpirationDate
                }
            };
        }

        private bool IsTokenExpired(DateTime expireDate)
        {
            return expireDate < DateTime.UtcNow;
        }

        public async Task<RemoteAuthenticationResult<RemoteAuthenticationState>> SignInAsync(RemoteAuthenticationContext<RemoteAuthenticationState> context)
        {
            await EnsureAuthService();
            //var result = await JsRuntime.InvokeAsync<RemoteAuthenticationResult<RemoteAuthenticationState>>("AuthenticationService.signIn", context);
            var authResult = new RemoteAuthenticationResult<RemoteAuthenticationState>();
            var result = await JsRuntime.InvokeAsync<StatusResponse>("AuthenticationService.signIn", context);
            Enum.TryParse(result.Status, true, out RemoteAuthenticationStatus status);
            authResult.Status = status;
            await UpdateUserOnSuccess(authResult);

            return authResult;
        }

        public async Task<RemoteAuthenticationResult<RemoteAuthenticationState>> CompleteSignInAsync(RemoteAuthenticationContext<RemoteAuthenticationState> context)
        {
            await EnsureAuthService();
            //var result = await JsRuntime.InvokeAsync<string>("AuthenticationService.completeSignIn", context.Url);
            var authResult = new RemoteAuthenticationResult<RemoteAuthenticationState>();
            var result = await JsRuntime.InvokeAsync<StatusResponse>("AuthenticationService.signIn", context);
            Enum.TryParse(result.Status, true, out RemoteAuthenticationStatus status);
            authResult.Status = status;
            await UpdateUserOnSuccess(authResult);

            return authResult;
        }

        public async Task<RemoteAuthenticationResult<RemoteAuthenticationState>> SignOutAsync(RemoteAuthenticationContext<RemoteAuthenticationState> context)
        {
            await EnsureAuthService();
            var result = await JsRuntime.InvokeAsync<RemoteAuthenticationResult<RemoteAuthenticationState>>("AuthenticationService.signOut", context);
            await UpdateUserOnSuccess(result);

            return result;
        }

        public async Task<RemoteAuthenticationResult<RemoteAuthenticationState>> CompleteSignOutAsync(RemoteAuthenticationContext<RemoteAuthenticationState> context)
        {
            await EnsureAuthService();
            var result = await JsRuntime.InvokeAsync<RemoteAuthenticationResult<RemoteAuthenticationState>>("AuthenticationService.completeSignOut", context.Url);
            await UpdateUserOnSuccess(result);

            return result;
        }

        private async ValueTask EnsureAuthService()
        {
            if (!_initialized) {
                await JsRuntime.InvokeVoidAsync("AuthenticationService.init", Options.ProviderOptions, _loggingOptions);
                _initialized = true;
            }
        }
        private async Task UpdateUserOnSuccess(RemoteAuthenticationResult<RemoteAuthenticationState> result)
        {
            if (result.Status == RemoteAuthenticationStatus.Success) {
                var getUserTask = GetUser();
                await getUserTask;
                await UpdateUser(getUserTask);
            }
        }

        private async Task UpdateUser(Task<ClaimsPrincipal> task)
        {
            _genericRepository.SetToken(_userAccessToken.Token.Value);
            var loginResult = await _genericRepository.PostAsync<UserAccessToken, LoginResult>("/api/login-aad", _userAccessToken);
            if (!string.IsNullOrWhiteSpace(loginResult?.UserId)) {
                await _localStorage.SetItemAsync("aadToken", _userAccessToken.Token.Value);
            }
            if (loginResult.Companies.Count > 1) {
                _authenticatingService.NotifyLoginAADSuccessfullyAuthenticated(loginResult);
            } else {
                await MarkUserAsAuthenticated(loginResult);
            }
        }

        private string GetReturnUrl(string customReturnUrl) =>
        customReturnUrl != null ? Navigation.ToAbsoluteUri(customReturnUrl).AbsoluteUri : Navigation.Uri;

        private async Task<ClaimsPrincipal> GetUser(bool useCache = false)
        {
            var now = DateTimeOffset.Now;
            if (useCache && now < _userLastCheck + _userCacheRefreshInterval) {
                return _cachedUser;
            }

            _cachedUser = await GetAuthenticatedUser();
            _userLastCheck = now;

            return _cachedUser;
        }

        protected internal virtual async ValueTask<ClaimsPrincipal> GetAuthenticatedUser()
        {
            await EnsureAuthService();
            var account = await JsRuntime.InvokeAsync<RemoteUserAccount>("AuthenticationService.getUser");
            _userAccessToken = await JsRuntime.InvokeAsync<UserAccessToken>("AuthenticationService.getAccessToken");
            var user = await AccountClaimsPrincipalFactory.CreateUserAsync(account, Options.UserOptions);

            return user;
        }
    }

    internal class UserAccessToken
    {
        public string Status { get; set; }
        public AccessToken Token { get; set; }
    }
    
    internal class StatusResponse
    {
        public string Status { get; set; }
        public string ErrorMessage { get; set; }
    }

    internal class JavaScriptLoggingOptions
    {
        public bool DebugEnabled { get; set; }

        public bool TraceEnabled { get; set; }
    }
}
`

Clearly not proud of it but at least it used to work on .Net 6. Maybe .Net 7 and 8 provide better/different solutions, I'll need to check.
This implementation is very specific to work with a Blazor WASM project.
