### ISSUE TITLE
stop() should cancel any ongoing start() and return instantaneously

### ISSUE THREAD

**Issue by BhavanaMSFT** [dotnet/aspnetcore#30986]
There is a need to be able to tear down in progress start() requests instantaneously on Suspend, which means SignalR cpp client will need to cancel anything that is in progress, including negotiate requests. There is a start timeout of a minute in the cpp client to see if start() returns/errors out before proceeding to clean up. This will involve two changes:
1. Ability to configure the wait here in connection_impl.cpp:

            // we request a cancellation of the ongoing start (if any) and wait until it is canceled
            m_disconnect_cts->cancel();

            while (m_start_completed_event.wait(60000) != 0)
            {
                m_logger.log(trace_level::errors,
                    "internal error - stopping the connection is still waiting for the start operation to finish which should have already finished or timed out");
            }
2. http_client to expose an API to cancel ongoing negotiate requests

**Comment by davidfowl** [comment]
Can you file this issue here http://github.com/aspnet/SignalR-Client-Cpp/

**Comment by BrennanConroy** [comment]
This is where we put issues.

**Comment by davidfowl** [comment]
Ah

**Comment by BhavanaMSFT** [comment]
There is also a deadlock that arises out of the wait here because the thread that waits for start() to complete will hold ownership of m_stop_lock. If negotiate response arrives on a different thread and it detects cancellation of start() it will end up queuing another stop() which will wait on m_stop_lock. The fix for this issue could be addressed as part of breaking up the wait for start to complete.

**Comment by BrennanConroy** [comment]
This should be done now.
