### ISSUE TITLE
Inline css using a variable leads to `Unexpected character sequence in property value`

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30980]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Inline-css-using-a-variable-does-not-wor/1323557)._

---
[severity:I'm unable to use this version]
Inline, conditional CSS values using a C sharp variable don't work. It breaks other CSS in my application too.
For example my custom scroll bars don't work. 

When I switch to the regular version of visual studio the css-propertyvalueexpected error does not show, inline 
css value with variables work and my custom scroll bars and all other css just shows.

Please see attached screenshot

---
#### Feedback Bot on 1/28/2021, 06:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/28/2021, 10:05 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment]
![image](https://user-images.githubusercontent.com/14852843/111364435-72693280-864e-11eb-9368-dc17b05c78bf.png)

```
<span style="font-size: 12px; width: @currentCount"></span>
```

This is especially odd as the warnings are on line 3 despite this span being on line 19.

**Comment by NTaylorMullen** [comment]
@jimmylewis @ToddGrun this looks like the html-delegation piece isn't remapping the CSS errors appropriately at which point we fail to remap them as well. Should we move over to your area path?

**Comment by jimmylewis** [comment]
Interesting, the file got remapped so we know the interception is doing something, but the line/col aren't right... Yup, go ahead and give this over to us.

**Comment by NTaylorMullen** [comment]
Reopened the original feedback and moved over to your area path: https://dev.azure.com/devdiv/DevDiv/_search?type=workitem&lp=workitems-Project&text=DeveloperCommunityId%3A1323557&filters=Projects%7BDevDiv%7D&_a=search
