### ISSUE TITLE
Will signalR losses packet when the connection is bad?

### ISSUE THREAD

**Issue by kea0811** [dotnet/aspnetcore#30992]
I am creating a web app for a rural area, which has bad connection, will signalR losses partial or complete package while delivering to the client? 

Since signalR is not using TCP, does signalR uses UDP concept to transport the data?

**Comment by davidfowl** [comment]
SignalR sends pings, if enough of those pings are missed then signalr will drop the connection.

**Comment by kea0811** [comment]
Is there is a set up where we can get them retry the connection?

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#reconnect-clients

**Comment by kea0811** [comment]
It seems like signalR does retry connection for only 4 times. Can we configure to be longer time frame?

**Comment by davidfowl** [comment]
From the document:

> If you want even more control over the timing and number of automatic reconnect attempts, withAutomaticReconnect accepts an object implementing the IRetryPolicy interface, which has a single method named nextRetryDelayInMilliseconds.

**Comment by kea0811** [comment]
@davidfowl that's awesome! thanks for your prompt answer!
