### ISSUE TITLE
URL Resource Completion: After type "href=~/" inside a <link> tag, the content of the intellisense list is incorrect.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspnetcore#30997]
Copied by [1291768](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1291768?src=WorkItemMention&src-action=artifact_link)

**REGRESSION INFO**：Worked in Dev 16.9.1 and Dev 16.10 Preview 1
**REPRO CONFIGURATION**: Win 8.1 x64 ENU+ Dev16.10 Preview2 (pre-release build)VSC

**.NET Core SDK (CLI) Version**: 5.0.200
**Latest .NET Core runtime Version**: 5.0.3

TESTCASES AFFECTED: 

AspNetCoreWebAppRazorEditing

**INSTALL STEP**
1. Clean machine: Win 8.1 x64 ENU
2. Run preinstall: \\vspreinstall\preinstall\preinstall.cmd
3. Install Dev 16.10 Preview 2(main-31111.288) VSC from main branch

- Web workload 

**REPRO STEPS**
 
1. File > New project > ASP.NET Core Web App> ASP.NET Core 3.1> Create

2. Open Page > Shared > _Layout.cshtml

3. In < head >< /head >,inside a < link >tag, type href="~/ ", verify the intellisense list, and the content of the intellisense list is incorrect.

**ACTUAL**:
![image](https://user-images.githubusercontent.com/71361488/111449994-e7219700-874a-11eb-86a2-3318346c0fcf.png)
**Expected**:
![image](https://user-images.githubusercontent.com/71361488/111450203-1fc17080-874b-11eb-8943-5e43941812d1.png)

**Comment by v-sherryfan** [comment]
![image](https://user-images.githubusercontent.com/71361488/111451394-59df4200-874c-11eb-8d7f-12bc950cf91c.png)

**Comment by javiercn** [comment]
@v-sherryfan thanks for contacting us.

This issue is not specific to asp.net core. In order for you to get a better and faster answer we recommend you file this issue via the report a problem dialog in visual studio. See details [here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

**Comment by NTaylorMullen** [comment]
Going to track this on our side as well

**Comment by NTaylorMullen** [comment]
@alexgav I assume this isn't expected is it?

**Comment by NTaylorMullen** [comment]
@alexgav just fixed this like a boss. Once it flows into main will need to validate

**Comment by NTaylorMullen** [comment]
Verified this is fixed on latest main
