### ISSUE TITLE
Phantom response being issued by custom middleware

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/aspnetcore#30993]
### Describe the bug
My custom timeout middleware is responding with data from another, already "dead", response.

### To Reproduce
This custom Middleware:
```
public class TimeoutMiddleware
{
    private readonly RequestDelegate _next;

    public TimeoutMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext httpContext)
    {
        using (var timeoutTS = CancellationTokenSource.CreateLinkedTokenSource(httpContext.RequestAborted))
        {
            var delayTask = Task.Delay(500);

            var res = await Task.WhenAny(delayTask, _next(httpContext));
            if (res == delayTask)
            {
                timeoutTS.Cancel();
                httpContext.Response.StatusCode = 408;
            }
        }
    }
}
```
And this controller
```
[HttpGet]
public async Task<string> Get(string timeout)
{
    var result = DateTime.Now.ToString("mm:ss.fff");
    if (timeout != null)
    {
        await Task.Delay(2000);
    }
    var rng = new Random();
    result = result + " - " + DateTime.Now.ToString("mm:ss.fff");
    return result;
}
```

And just use fiddler to spam a dozen requests and you will see that the first ones will return 408 (as expected) but soon you will start to see a bunch of 200s. When you inspect the time on the body, you will see that the time reported is far BEHIND the request start time

### Exceptions (if any)
"Response has already started" but that's not important

### Further technical details
- ASP.NET Core version: .Net 5 and 3.1
- Include the output of `dotnet --info`:

> .NET SDK (reflecting any global.json):
>  Version:   5.0.201
>  Commit:    a09bd5c86c
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  11.0
>  OS Platform: Darwin
>  RID:         osx.11.0-x64
>  Base Path:   /usr/local/share/dotnet/sdk/5.0.201/
> 
> Host (useful for support):
>   Version: 5.0.4
>   Commit:  f27d337295
> 
> .NET SDKs installed:
>   2.1.202 [/usr/local/share/dotnet/sdk]
>   2.1.802 [/usr/local/share/dotnet/sdk]
>   2.2.207 [/usr/local/share/dotnet/sdk]
>   3.0.100 [/usr/local/share/dotnet/sdk]
>   3.1.100-preview2-014569 [/usr/local/share/dotnet/sdk]
>   3.1.100-preview3-014645 [/usr/local/share/dotnet/sdk]
>   3.1.100 [/usr/local/share/dotnet/sdk]
>   3.1.101 [/usr/local/share/dotnet/sdk]
>   3.1.102 [/usr/local/share/dotnet/sdk]
>   3.1.200 [/usr/local/share/dotnet/sdk]
>   3.1.202 [/usr/local/share/dotnet/sdk]
>   3.1.300 [/usr/local/share/dotnet/sdk]
>   3.1.301 [/usr/local/share/dotnet/sdk]
>   3.1.302 [/usr/local/share/dotnet/sdk]
>   3.1.401 [/usr/local/share/dotnet/sdk]
>   3.1.402 [/usr/local/share/dotnet/sdk]
>   3.1.403 [/usr/local/share/dotnet/sdk]
>   3.1.404 [/usr/local/share/dotnet/sdk]
>   3.1.405 [/usr/local/share/dotnet/sdk]
>   3.1.406 [/usr/local/share/dotnet/sdk]
>   3.1.407 [/usr/local/share/dotnet/sdk]
>   5.0.100 [/usr/local/share/dotnet/sdk]
>   5.0.101 [/usr/local/share/dotnet/sdk]
>   5.0.102 [/usr/local/share/dotnet/sdk]
>   5.0.103 [/usr/local/share/dotnet/sdk]
>   5.0.201 [/usr/local/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0-preview2.19525.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0-preview3.19553.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio for Mac, version 8.9.2 (build 0) (yeah the build number is ZERO, really weird)

**Comment by Tratcher** [comment]
This is an extremely unsafe pattern. If your timeout fires then `_next` is still running when InvokeAsync ends, which can cause the MVC controller to write to a stale HttpContext that might get recycled for the next request. Also, HttpContext is not thread safe, you must not access it from multiple threads concurrently.

If you call `_next` then you must wait for it to finish.

**Comment by Leonardo-Ferreira** [comment]
>HttpContext that might get recycled for the next request

yeah, that seems to be whats going on over here... this is really unfortunate... I mean, I was OK with the idea of the `_next` possibly running forever, after all, it already does, I was just hoping to be able to get a response back to my users on more reliable fashion...

the real implementation of this middleware is much more complex and performs quite beautifully... it allows for you to choose which kind of timeout you want: cooperative or strict (strict being the one I'm demonstrating here)

is there a way to check if im getting a new instance or a recycled one? perhaps I can work something out of that...

**Comment by davidfowl** [comment]
Strict mode is broken, cooperative is the only that is reliable.

**Comment by davidfowl** [comment]
BTW the above code has a mini-timer leak, you can see the bad and good pattern here https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/a87d6b804d8924e8487f3bf79f37fe9973049649/Scenarios/Infrastructure/TaskExtensions.cs#L48-L89

**Comment by Leonardo-Ferreira** [comment]
Cooperative mode works as well as your developers skills... a have a bunch here that has no idea what a `CancellationToken` is...

**Comment by davidfowl** [comment]
Thinking outside of the box here a minute, I can think of one way to implement this safely but it's expensive and not pay for play. You'd need to stub out the HttpContext and either:
- Synchronize access to the properties
- Copy the state into a new HttpContext

That would let you implement strict mode.

**Comment by Leonardo-Ferreira** [comment]
@davidfowl If I were able to spawn a HttpContext per request, I wouldn't need to worry about thread safety. This would hamper giga escale applications due to memory consumption and garbage collection, but that is not my reality here...

**Comment by davidfowl** [comment]
If that were a concern then you could pool them 😄.

**Comment by Leonardo-Ferreira** [comment]
@davidfowl for the first time now im getting acquainted with the Asp Net Core code, and its 1:20am here... ill try to cook something up on the lines of copying the state of the original... and by the way, what do you mean "it's not pay for play"?

**Comment by davidfowl** [comment]
>  ill try to cook something up on the lines of copying the state of the original... and by the way, what do you mean "it's not pay for play"?

You'd be paying the cost of wrapping the HttpContext for every request even if no timeout occurred. It's something you end up doing ahead of time just in case it times out and every request ends up being penalized as a result.

**Comment by Leonardo-Ferreira** [comment]
what if I could mark the instance which timed-out? check this out: `httpContext.Abort()` does the job in a very messy way. If I could register this "corrupted" instance for `Abort()` as soon as the request at hand concludes, its all good! I could spawn a helper `Task` and simply use a `ConcurrentQueue<HttpContext>`... the task would pool on the queue, and whenever it found something there, check if there's a active (`httpContext.RequestAborted`) request for that context, if not, `Abort` and `Dispose`

**Comment by davidfowl** [comment]
I don't think that works but I'd be fine reviewing the implementation. Also Abort will abort the entire connection, I'm not sure if you want to do that in this case?

**Comment by Leonardo-Ferreira** [comment]
by using
```
timeoutTS.Cancel();
httpContext.Response.StatusCode = 408;
httpContext.Response.OnCompleted(() => { return Task.Factory.StartNew(()=> { httpContext.Abort(); }); });
```
I managed to replace the phantom responses with 504s... not ideal but an evolution

**Comment by davidfowl** [comment]
You can't set the response. That's already a race condition. You can abort though.

**Comment by Leonardo-Ferreira** [comment]
@davidfowl how hard would you think it is to create a mechanism to prevent a given HttpContext to be reused? 
I thought of an api such as `context.Invalidate()` that would be used by my middleware. This api would set a property and the pooling mechanism would check it and not recycle this given context and release it from the pool. As soon as `_next(httpContext)` is done, the GC would be able to reclaim its memory...

**Comment by davidfowl** [comment]
It wouldn't help your situation, you still have the concurrency issue where multiple threads may end up writing to the HttpContext at the same time/

**Comment by Leonardo-Ferreira** [comment]
actually I would not have such an issue. Check this out: 

1. When the middleware acts, it will "shortcut" the whole operation (trying to avoid words like request and response due to their use in other contexts) and **set the current httpContext as dirty**. The response pipeline will continue normally as it is today
2. after the response has concluded the HttpContext recycling mechanism would check if the context at hand is dirty. If not, life goes on as usual. If it is dirty, the mechanism would exclude it from the pool, which will prevent it from being passed on.
3. when the original request that triggered the pipeline ends up (which might be never) it will have a context to write to, but that will result in nothing or an exception (which is fine). After that the GC will be able to recollect whatever resources are maintained there

As long as the httpContext that has been shortcut by the middleware does not go back in circulation, I think we're safe.

**Comment by davidfowl** [comment]
There's a built in race condition that you can't avoid. Maybe you're saying you don't care about the race? That said there are ways to disable the reuse (which happens today in Kestrel only):
- Make a new HttpContext and call next on that -> `new DefaultHttpContext(context.Features)`
- Add the IHttpContextAccessor - This disables the reuse

That won't change the fact that you can modify the response at the same time as the code you're timing out.

**Comment by weichch** [comment]
Thinking this myself, if I were to cancel my own code, I'd probably pass a cancellation token further down the request pipeline and check/throw whenever it is possible:
- Create a new `CancellationToken` that gets canceled after `timeout` in `TimeoutMiddleware`
- Set the `CancellationToken` to `HttpContext` or in a custom request feature
- In `TimeoutMiddleware` `await` on the `next` delegate, and handle operation cancel exceptions

However, this still doesn't help (like I said in the [OG question](https://stackoverflow.com/questions/66666354/asp-net-core-5-timeout-middleware-outputting-phantom-data)) if your code, or any code further down the request pipeline can start the response before the timer elapsed.

**Comment by Leonardo-Ferreira** [comment]
That approach @weichch is know as cooperative. As I stated before, it works as long as the developers implementing it know what they are doing. A large part of my devs over here don't even know what a cancellation token is and what to do with it. Hence they need a more "aggressive" approach, like it was with the good old .Net Framework.

In the complete implementation there are several safeguards that are not here.

**Comment by weichch** [comment]
Frankly, if I don't hold the knowledge of cancellation, and only saw my code got canceled aggressively, I might be more confused.

**Comment by Leonardo-Ferreira** [comment]
Again, on the real world implementation, it would not "drop out of nowhere"... this would be delivered as nuget package and you would be able to establish a default policy and opt-in/out of it on a controller level or even action level. You as a developer would be able to choose for either a cooperative strategy or a strict one also...

**Comment by davidfowl** [comment]
Regardless, you can't abort the thread and you can't abort async code because it doesn't even make sense. You can abort the connection in a thread safe way but then you don't get to set a response to the client. You can't safely write to the response in this middleware without synchronizing writing to the response with any other running code.  Then there's the other issue where the HttpContext gets reused (but can be disabled).

Those are the constraints of the system, you need to design a solution within them.

**Comment by Leonardo-Ferreira** [comment]
but that is the beauty of OSS: I can propose implementations that would eliminate such constraints! I don't want to get on the subject of cancelling threads/tasks, but I do think that the mechanism I described above is viable and would incur a very minor negative performance impact. At least, that's my big question for you now: as an more versed person on the inner workings of the AspNetCore codebase, how hard would be to do so?

**Comment by davidfowl** [comment]
I already provided a workaround for what you asked.

**Comment by Leonardo-Ferreira** [comment]
can you be more specific on that workaround? perhaps provide some protocode? Reading the workaround it seems to be an theoretical workaround that might not be actually implementable today due to some unknown particularity...

**Comment by davidfowl** [comment]
This comment https://github.com/dotnet/aspnetcore/issues/30993#issuecomment-801335330

**Comment by Leonardo-Ferreira** [comment]
so, I've tinkering with it, and I don't think its feasible... here's what I got so far:
```
public async Task InvokeAsync(HttpContext httpContext)
{
    var newContext = new DefaultHttpContext(httpContext.Features);

    newContext.Request.Body = httpContext.Request.Body;
    newContext.Request.ContentLength = httpContext.Request.ContentLength;
    newContext.Request.ContentType = httpContext.Request.ContentType;
    //foreach (var item in newContext.Request.Headers)
    //{
    //    httpContext.Request.Headers.Add(item.Key, item.Value);
    //}
    newContext.Request.Host = httpContext.Request.Host;
    newContext.Request.Method = httpContext.Request.Method;
    newContext.Request.Path = httpContext.Request.Path;
    newContext.Request.PathBase = httpContext.Request.PathBase;
    newContext.Request.Protocol = httpContext.Request.Protocol;
    newContext.Request.RouteValues = httpContext.Request.RouteValues;
    newContext.Request.Scheme = httpContext.Request.Scheme;
    newContext.Request.Form = httpContext.Request.Form;
    
    await _next(newContext);
}
```
(there have been many variations of the code above)
But the initial problem is that the request never reaches the controller its intended to... I think it might have something to do with the `httpContext.Connection`, which I cant `set` directly...

**Comment by davidfowl** [comment]
You don't need to set any of those properties, they are implemented by the passing in the original feature collection.

**Comment by Leonardo-Ferreira** [comment]
that was my first try actually... no game... so I started assigning individually...

**Comment by Leonardo-Ferreira** [comment]
Hello @BrennanConroy, I noticed you added this to the Discussions, and I would like to know if there's anything I can do help?

**Comment by davidfowl** [comment]
There's currently no work item here, that's why it's under discussions.

**Comment by Leonardo-Ferreira** [comment]
@davidfowl despite great effort I was unable to duplicate the `httpContext` and have the request arrive at the controller properly. Do you know of anybody that has successfully done so? perhaps some repo/code I can refer to?

**Comment by davidfowl** [comment]
What issues are you running into?

**Comment by Leonardo-Ferreira** [comment]
@davidfowl the request never actually hits the intended controller

**Comment by davidfowl** [comment]
If you can make me a sample I'll try to reproduce it.
