### ISSUE TITLE
InputBase throws on Dispose if not in EditContext

### ISSUE THREAD

**Issue by NikolaosWakem** [dotnet/aspnetcore#30990]
Seems that if you add an InputSelect and forget to put it inside an EditContext it causes a great Exception to be thrown but sadly then throws null exception in the finally instead...

![image](https://user-images.githubusercontent.com/4430381/110861491-2026bb00-82b6-11eb-9888-4bd41579594f.png)

**Comment by javiercn** [comment]
@NikolaosWakem thanks for contacting us.

Inputs like InputText are not meant to be used outside of an `EditFrom`/EditContext

**Comment by javiercn** [comment]
@SteveSandersonMS this is what I ran into the other day in a more "subtle" way.

**Comment by NikolaosWakem** [comment]
> @NikolaosWakem thanks for contacting us.
> 
> 
> 
> Inputs like InputText are not meant to be used outside of an `EditFrom`/EditContext

Yes - I realise that.. but code shouldn't throw a null exception in a dispose

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. Hopefully it should be a very simple fix if anyone in the community is interested in sending a PR. Otherwise we can keep it on the backlog.

**Comment by NikolaosWakem** [comment]
> Thanks for reporting this. Hopefully it should be a very simple fix if anyone in the community is interested in sending a PR.

if (EditContext != null) 

should do it ;-)
