### ISSUE TITLE
Unhandled exception rendering component: Could not find a part of the path "/C:/fakepath/Testing-1.ost".

### ISSUE THREAD

**Issue by AkshayDilod** [dotnet/aspnetcore#30994]
![error](https://user-images.githubusercontent.com/29436937/111422952-8e83d700-8715-11eb-9653-e0d5576c6d19.PNG)

### Describe the bug

when I am trying to read the file into chrome browser and perform an OSTRead Operation define in the below section.

 <input type="file" @bind="path" />

private void OSTRead()
    {
        using (PersonalStorage personalStorage = PersonalStorage.FromFile(path))
        {
            personalStorage.SaveAs(path + "test.pst", FileFormat.Pst);
        }

    }

**Comment by SteveSandersonMS** [comment]
I might be misunderstanding, but it sounds as if you're trying to read a file from the user's filesystem while running inside WebAssembly. It's not possible to access the host machine's filesystem directly as that is not permitted by the browser's sandbox. WebAssembly code is limited to the same restrictions as JavaScript when running inside a browser.

If you use something like [the `InputFile` component](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0) to let the user select a local file to load into the WebAssembly runtime then it is possible to access the file data. As for whether this suits your needs I can't be sure - it sounds as if you're trying to read Outlook data files, which users may not want to supply to a web application.
