### ISSUE TITLE
Blazor WebAssembly Azure AD automatically logging in user on mobile browser

### ISSUE THREAD

**Issue by matlui** [dotnet/aspnetcore#31009]
Hello, I have a basic hosted Blazor WASM solution created from the VS template and configured for single tenant Azure AD authentication as per the instructions here: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0

Behavior on desktop: 
- Click "Log in" at the top, provide credentials (**without** checking "Keep me signed in") and it all works as expected
- If you close the browser completely without first clicking on "Log out", the next time you visit the web app again and click "Log in" you will be prompted for credentials again. This is the expected behavior.

Behavior on mobile (tested on iOS Safari and Chrome):
- Open web app and click "Log in", provide credentials, again without checking "Keep me signed in"
- Again close browser completely without first signing out. (Fun fact, even restarting the device produces the same result)
- Open browser again and browse to the web app and click "Log in", you will be logged in automatically without having to provide any credentials.

My expected behavior would be that after a browser restart or device restart, clicking "Log in" should prompt the user for credentials again. I'm not too sure about the inner workings of mobile browsers, so let me apologize in advance if this is more of a mobile OS issue in the way it handles the tokens. The only way I am able to re-prompt for credentials is if I click on "Log out" first or if I clear all browser cache/cookies/etc.

Any suggestions on how to force the user to re-authenticate?

**Comment by javiercn** [comment]
@matlui thanks for contacting us.

This behavior is expected. If the user is authenticated in the IdP (AAD), we will silently authenticate the user in the app (Single sign-on). So I suspect the cookie in the IdP (AAD) is not being removed from your mobile device upon closing it.

**Comment by matlui** [comment]
Thanks for the explanation, much appreciated.
