### ISSUE TITLE
The [controller] placeholder in the route template doesn't use the controller name specified in ControllerNameAttribute

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/aspnetcore#31026]
Not sure if this is actually a bug, but if it's by design, it's a bit confusing.

### Describe the bug
The `[controller]` placeholder in the route template doesn't use the controller name specified in `ControllerNameAttribute`.

### To Reproduce

Create a controller like this:
```csharp
[ApiController]
[ControllerName("bar")]
[Route("api/[controller]")]
public class FooController : ControllerBase
{
...
}
```

- **Expected:** the route for the controller is `api/bar` (iow, the `[controller]` placeholder is replaced by the name specified in `[ControllerName("bar")]`)
- **Actual:** the route for the controller is `api/foo` (`[ControllerName("bar")]` has no effect)

I realize that in this case I could just set the correct route directly as `[Route("api/bar")]`, but in my actual project, my routes are a bit more complex (something like `api/v{version:apiVersion}/t/{tenantKey}/[controller]`) and I don't want to specify the full route on every controller, so I use a constant. I expected to be able to control what goes in the `[controller]` placeholder using the `[ControllerName]` attribute, but it doesn't seem to do anything. Is this expected? Is there a way to control this behavior?

### Exceptions (if any)
N/A

### Further technical details
- ASP.NET Core version : 5.0
- Include the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
>  Version:   5.0.201
>  Commit:    a09bd5c86c
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.201\
> 
> Host (useful for support):
>   Version: 5.0.4
>   Commit:  f27d337295
> 
> .NET SDKs installed:
>   3.1.407 [C:\Program Files\dotnet\sdk]
>   5.0.102 [C:\Program Files\dotnet\sdk]
>   5.0.104 [C:\Program Files\dotnet\sdk]
>   5.0.201 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version : JetBrains Rider 2020.3

**Comment by pranavkm** [comment]
Thanks for the issue repo. `ControllerNameAttribute` is shipped out of the API-versioning package which isn't something the .NET team ships (at least as of today). This explains the impedance mismatch. We'll investigate if this is something we could sort out, but given this is fairly easy to workaround issue, it'll be pretty low on our priority.

**Comment by thomaslevesque** [comment]
Hi @pranavkm,

Thanks for your reply. I didn't realize this attribute wasn't part of ASP.NET Core itself; knowing this, it makes sense that it isn't taken into account.
Is there another way to achieve what I want to do?

**Comment by pranavkm** [comment]
You might be able to author a convention:

```C#
public class MyControllerNameAttribute : Attribute, IControllerModelConvention
{
    private readonly string _controllerName;

    public MyControllerNameAttribute(string controllerName)
    {
        _controllerName = controllerName;
    }

    public void Apply(ControllerModel model)
    {
        model.ControllerName = _controllerName;
    }
}
```

**Comment by thomaslevesque** [comment]
Thanks @pranavkm, I'll give it a try!

**Comment by thomaslevesque** [comment]
@pranavkm it works great, thanks!
