### ISSUE TITLE
css isolation for asp.net core Web Application not working

### ISSUE THREAD

**Issue by tanekim77** [dotnet/aspnetcore#31022]
I created a fresh Asp.Net Web Application and added a _Layout.cshtml.css file to test if css isolation feature is working, as in the following screen shot
![image](https://user-images.githubusercontent.com/20119808/111632174-9a7da080-87ca-11eb-90e9-466e45227fda.png)

But when I run the application, I am seeing a weird letters on top of the file (i.e. "b-g6ltozs93r"), and the css content is not working either. It is supposed to have green background.

![image](https://user-images.githubusercontent.com/20119808/111631805-39ee6380-87ca-11eb-8106-edf0cb40e971.png)

**Comment by mkArtakMSFT** [comment]
Just a reminder for the team that we need to add a validation scenarios for this.

**Comment by mkArtakMSFT** [comment]
We' ll also include the styles in templates going forward and that is tracked as part of https://github.com/dotnet/aspnetcore/issues/31030

**Comment by dodyg** [comment]
I can't make the CSS Isolation even for Index.html.css (Preview 2). Maybe it's already fixed in later version.

https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/net6/css-isolation

**Comment by tanekim77** [comment]
The problem still remains in Dotnet 6 Preview 3.

**Comment by captainsafia** [comment]
Correct -- I responded in the other issue.

You can try it out in the previews at https://github.com/dotnet/installer
