### ISSUE TITLE
Expose MessageBody._observedBytes on a feature accessible by request middleware

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/aspnetcore#31032]
Expose MessageBody._observedBytes on a feature accessible by request middleware.

As this property is the best approximation to request size which is kind of lacking (without hacks like wrapping the stream to track it yourself) it'd be helpful to have this be exposed to request middleware. Ideally shipped together with a response counterpart, with the caveat either value would only be at their most accurate during Response.OnCompleted.

**Comment by Tratcher** [comment]
Do you want to observe the request body, response body, or both?

If we expose this we should do it for all three servers. 

Features are considered out of scope when OnCompleted callbacks run, that's only for disposal. Your last chance to observe anything is as your middleware exits. That should report all of the consumed request data, but would exclude any unconsumed data.

**Comment by NinoFloris** [comment]
Ideally, both :)

Yes logging, we'd like to move kestrel to the edge but its loggable info lacks a bit of fidelity compared to common reverse proxies.

I thought response.oncompleted could still access the http context, at least this issue https://github.com/aspnet/KestrelHttpServer/issues/2035 led me to believe it would be the best place to do a post flush 'request line' log. Better to do it inline with a middleware?

**Comment by davidfowl** [comment]
This is solely about request and response bodies right?

**Comment by NinoFloris** [comment]
Yup, header sizes be damned. http2 and 3 make that difficult anyway

**Comment by BrennanConroy** [comment]
If there are more asks for this we can reconsider, but closing for now.
