### ISSUE TITLE
In search of an asp.net core 5 contributor that is available for per hour paid work. +- 1 to 4 hours at first

### ISSUE THREAD

**Issue by githubDiversity** [dotnet/aspnetcore#31038]
LS,

I am not sure where to ask this so I try it here. Should it be a miss post then please let me know where to ask.

I am looking for someone that has deep knowledge of the internals of asp.net core 5. 

I have tried many freelancer websites and it just never works. Thus currently I am looking for someone that is actually involved with the development of asp.net core 5

I know their hourly rate is going to be steep but it is the only way I see forward.

I can pay ahead of time hour by hour if need be until we trust each other. After which of course a more sensible freelance-client relationship/payment schedule would come into play.

Please let me know if you are either interested or know where I should ask this question for better exposure.

**Comment by Pilchie** [comment]
This is not a jobs board. GitHub does have a careers section, I suggest posting there instead.
