### ISSUE TITLE
Consume Optimization Training Data for CrossGen2 in build

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#31040]
We'll need to:

- [ ] update our build to use crossgen2
- [ ] update our build to consume optimization training data (in the form of NuGet packages) that the perf lab will be producing.

**Comment by Pilchie** [comment]
See https://github.com/dotnet/runtime/pull/49793 for an example of some of this in `dotnet/runtime`

**Comment by davidwrighton** [comment]
The expectation is that the aspnet repo will be able to use the same packages as are used by the runtime repo, or that the runtime repo will produce a new set of packages for downstream consumption. Regardless, the priority is to enable crossgen2, and then enabling the pgo data *should* be relatively simple.

**Comment by Pilchie** [comment]
Would like to get this done no later than Preview 5, but not putting in that milestone in case we pick it up earlier.

Also tagging @dotnet/aspnet-build

**Comment by AndyAyersMS** [comment]
Is this done? 

I see the crossgen2 update happened, and that it will consume PGO data if that data's available, but I can't tell if the data actually is available.

**Comment by dougbu** [comment]
> Is this done?

Yes, @AndyAyersMS, complete with 46b56aa06511. Thanks for the reminder.

Thanks again to @davidwrighton for his #31778. My final changes (after lots of testing) wasn't much different than @davidwrighton's work.
