### ISSUE TITLE
Add default value to TagBuilder.GenerateId

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#31056]
## Background and Motivation

Make it easier, quicker and less verbose to use the `GenerateId` method on the `TagBuilder`.

## Proposed API
```diff
namespace Microsoft.AspNetCore.Mvc.Rendering
{
    public class TagBuilder : IHtmlContent
    {
-       public static string CreateSanitizedId(string name, string invalidCharReplacement);
+       public static string CreateSanitizedId(string name, string invalidCharReplacement = "_");
-       public void GenerateId(string name, string invalidCharReplacement);
+       public void GenerateId(string name, string invalidCharReplacement = "_");
    }
```

## Usage Examples

``` C#
var div = new TagBuilder("div");
div.GenerateId("Björnbärstårta"); // "Bj_rnb_rst_rta"
```

## Alternative Designs
This is like the old `TagBuilder` in the `System.Web` namespace.
https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.tagbuilder.generateid?view=aspnet-webpages-3.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
While this may be a great idea, it is not aligned with our long-term vision to make it part of the framework. For many other ideas which don't belong to the framework we encourage the community to build and ship on their own, contributing to the expanding .NET Ecosystem.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
