### ISSUE TITLE
Microsoft.AspNetCore.WebUtilities package should be out of Microsoft.AspNetCore.App meta package.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#31058]
`Microsoft.AspNetCore.WebUtilities` package contains the things which can be used in Blazor WebAssembly but it is tightly part of `Microsoft.AspNetCore.App` meta-package which can not be referenced to Blazor WebAssembly project. The available version of `Microsoft.AspNetCore.WebUtilities` is `2.2.0` which is too old because it is not being updated anymore independently as it has been part of `Microsoft.AspNetCore.App` meta-package.

Thank you.

**Comment by blowdart** [comment]
Moving things out of the shared framework means they can't be easily serviced, for bugs or security problems. That presents a huge risk.

Exactly what methods and classes do you think are useful for Blazor which don't already have a DOM equivalent?

**Comment by TanvirArjel** [comment]
1. QueryHelpers.AddQueryString(string uri, string key, string value)
2. QueryHelpers.ParseQuery(query).TryGetValue(key, out StringValues value) etc.

**Comment by blowdart** [comment]
@javiercn This seems like a doc issue. Can you suggest a supported way? There's no way we'd look at splitting WebUtilities back out.

**Comment by davidfowl** [comment]
It would be good to have these super low level helpers in then BCL itself

**Comment by javiercn** [comment]
@guardrex can you update the docs to suggest an alternative approach?

Like using `URLSearchParams` directly via JS interop in this case would be a good alternative.

**Comment by javiercn** [comment]
@davidfowl do you want to make a specific proposal for this? As it stands this package contains a lot of unrelated functionality, the majority of which is of limited value outside of asp.net core.

**Comment by javiercn** [comment]
I'm marking this as answered since we've offered an alternative approach for wasm and we are updating the docs.

**Comment by TanvirArjel** [comment]
@javiercn 

>As it stands this package contains a lot of unrelated functionality, the majority of which is of limited value outside of asp.net core.

I didn't understand this line. Isn't blazor is a part of ASP.NET Core? If all ASP.NET Core things do not work in blazor then delivering blazor under ASP.NET Core namespaces is a huge misdesign that I am always feeling whenever working with blazor. Blazor should have been under dedicated `Microsoft.Blazor.* ` namespaces.

**Comment by javiercn** [comment]
@TanvirArjel The package `Microsoft.AspNetCore.WebUtilities` contains a lot of utilities that are specific for server scenarios and that don't have value outside of them.

My reference to ASP.NET Core here is in the context of the shared framework `Microsoft.AspNetCore.App`. Blazor ships within the ASP.NET Core framework as well as packages, however that doesn't mean that everything in the shared framework can work or provides useful functionality in the context of a Blazor application.

As for the namespace, Microsoft.AspNetCore denotes the things our team ships that are related to web technologies. The component model is `Microsoft.AspNetCore.Components` and the different application models built around it are Blazor Server, WebAssembly, Webview, etc.

In general you can't assume that because something is in a given namespace it works in all posible contexts where that namespace is available. `namespace != platform support`.

Hope this helps clarify things.

**Comment by TanvirArjel** [comment]
@javiercn Thank you so much for your explanation. I have understood your explanation. But it would have been more beautiful and meaningful if it was as follows:

1. `Microsoft.AspNetCore.*` namespaces will contain all the common things for any ASP.NET Core project. Whether it MVC, RazorPages, Blazor Server, or Blazor WebAssembly project.
2. Then `Microsoft.AspNetCore.Mvc.*` namespaces will contain all the things specific to MVC and Razor Pages project.
3. Then `Microsoft.Blazor.*` namespaces will contain all the things specific to Blazor Server and Blazor WebAssembly project.

**Comment by javiercn** [comment]
@TanvirArjel we appreciate your input, however we don't see it the same way and have no plans to change those things at this point.

**Comment by guardrex** [comment]
The doc update is complete on [URLSearchParams for QS parsing (dotnet/AspNetCore.Docs #21843)](https://github.com/dotnet/AspNetCore.Docs/pull/21843). We're going to tell devs to use `URLSearchParams` and cross-link to the [*Blazor JavaScript isolation and object references* section of the JS interop topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references). There will be improvements to that section in a bit on my [UE ("user experience," i.e., doc overhauls) passes (dotnet/AspNetCore.Docs #19286)](https://github.com/dotnet/AspNetCore.Docs/issues/19286), and I might even change the example in that section to match this use case.

**Comment by TanvirArjel** [comment]
The solution you provided neither looks good nor satisfactory. We are using Blazor here to come out of JavaScript but you are forcing us to write more and more JavaScript. If we had to write a lot of JavaScript then we can simply use Angular or React instead. Please provide a pure C# solution like `QueryHelpers` class in  `Microsoft.AspNetCore.WebUtilities`.

The provided solution looks like a botch to the problem instead of a real solution.

Thank you.

**Comment by TanvirArjel** [comment]
The proper solution would be what @davidfowl said. These super low-level helpers should be in BCL.
