### ISSUE TITLE
Some classes from Microsoft.AspNetCore.Mvc.ModelBinding.Validation.Internal are no longer available in .Net Core 3.1

### ISSUE THREAD

**Issue by jerry011296** [dotnet/aspnetcore#31055]
I am migrating my class library from .Net Core 2.1 to 3.1 recently and in this class library I am using some MVC model validation code. The problem here is Microsoft.AspNetCore.Mvc is removed from the 3.1 SDK and Microsoft recommends to use it with FrameworkReference option with the reference to Microsoft.AspNetCore.App but again there are some pubInternal classes which are marked as internal in the new SDK. [Here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.0#mvc-pubternal-types-changed-to-internal), we can see the reference provided by Microsoft for the migration. 

Now I am using these two class references, _ValidatableObjectAdapter_ and _DataAnnotationsModelValidatorProvider_ in my project and I really couldn't find the workaround or any alternative to these classes. Anyone having any idea will be very appreciated. 

Code snippets : 

`new ValidatorItem
            {
                Validator = new ValidatableObjectAdapter(),
                IsReusable = true
            }` 

`var defaultProviders = (MvcOptions)options.ModelValidatorProviders.Where(p => p is DataAnnotationsModelValidatorProvider)`

**Comment by pranavkm** [comment]
The typical recommendation is to copy the code in to your assembly:
* https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.DataAnnotations/src/ValidatableObjectAdapter.cs
* https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsModelValidatorProvider.cs

You could attempt to reference the framework types by name (for instance in the 2nd scenario). 

In general we didn't think these types were good candidates for being part of ASP.NET Core's public API surface. However, we've occasionally made types public if we've heard a lot of feedback.

**Comment by jerry011296** [comment]
I am currently doing the same, that is, I have copied the code into my class library. Just wondering, is there any better solution available ?

**Comment by javiercn** [comment]
@jerry011296 no, those types were always meant to be internal and "use at your own risk". If we see enough demand for them (they are needed in a common scenario) we might consider turning them into a feature and public, but in general the suggestion that @pranavkm mentions is the place to start.
