### ISSUE TITLE
Request to Web API getting dropped before reaching controller since dotnet core 3.1 upgrade

### ISSUE THREAD

**Issue by Anil-dedsec** [dotnet/aspnetcore#31051]
We have Web APIs migrated from netcore 2.2 to 3.1 and it is deployed in Openshift. After migrating to 3.1, we started seeing issues where one instance of API is dropping all requests before even reaching to controller. 
**### Please find logs below:**
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.137ms 200 text/plain
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://test-dataaccess:8080/MyController/GetMethod  application/json; charset=utf-8 401
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'TestDataAccessAPI.Controllers.TestDataController.GetMethod (TestDataAccessAPI)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.1253ms 200 text/plain
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://test-dataaccess:8080/HealthCheck   
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.112ms 200 text/plain
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

After "Request starting HTTP/1.1 " log entry, we are not seeing any processing related to this request in the logs and it is behaving the same for the next requests.

```
**### Startup.cs>Configure():**
 if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
 app.UseHealthChecks("/HealthCheck");
            app.UseHttpsRedirection();
            app.UseRouting();
            app.UseEndpoints(endpoints => {
                endpoints.MapControllers();
            });
```

**Comment by Anil-dedsec** [comment]
Please let me know if more info is required to debug this issue.

**Comment by Anil-dedsec** [comment]
Additional info: We are have multiple APIs hosted on openshift with 30-40 instances and we are observing this behavior in only 2 3 instances(issue persists since the instance creation).  After restarting the erroneous instance, the issue usually resolves and it starts processing the requests successfully.

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.

**Comment by Anil-dedsec** [comment]
Hi Brennan,

Thanks for responding. 

I don't have any query on how to use ASP.NET Core. Actually I want to know why one instance of deployment would drop the request without processing it, but rest of the instances of the same code are working fine. 
We have been using ASP.NET Core 2.2 and our web APIs were working fine. But after we upgraded the framework to ASP.NET Core 3.1, we started seeing this issue. 
The issue is with one of the pods dropping the HTTP requests and not executing our code. Rest of the instances/pods are working fine.

Could you please read my problem statement again and let me know if you still feel this is a code issue?

**Comment by Anil-dedsec** [comment]
> Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.



> Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.

Hi Brennan,

Thanks for responding.

I don't have any query on how to use ASP.NET Core. Actually I want to know why one instance of deployment would drop the request without processing it, but rest of the instances of the same code are working fine.
We have been using ASP.NET Core 2.2 and our web APIs were working fine. But after we upgraded the framework to ASP.NET Core 3.1, we started seeing this issue.
The issue is with one of the pods dropping the HTTP requests and not executing our code. Rest of the instances/pods are working fine.

Could you please read my problem statement again and let me know if you still feel this is a code issue?
