### ISSUE TITLE
Investigate using S.T.Json source generator with Blazor

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#31065]
•	The source generator and updated System.Text.Json.dll can be obtained via a NuGet package here.
•	An early attempt to refactor JsonSerializer calls from Blazor assemblies can be found here.
•	To verify size reductions from a Blazor app, set this linker feature switch in the csproj: <_ExtraTrimmerArgs>--feature System.Text.Json.DisableJsonSerializerDynamicFallback true</_ExtraTrimmerArgs>

**Comment by danroth27** [comment]
@pranavkm @mkArtakMSFT What is this blocked on?

**Comment by pranavkm** [comment]
Closing this as we don't have any specific work planned for this.
