### ISSUE TITLE
Logout does not work when using AddOidcAuthentication

### ISSUE THREAD

**Issue by ddobric** [dotnet/aspnetcore#31088]
When using AddOidcAuthentication in Blazor WebAssmbly standalone, the logout does not work.
After logout the browser navigates to:

> https://localhost:44316/authentication/logout-failed?message=The%20logout%20was%20not%20initiated%20from%20within%20the%20page.

### To Reproduce
Use same example described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio).
The error happens when _BeginLogout_ is invoked.

```
@code{
    private async Task BeginLogout(MouseEventArgs args)
    {
        await SignOutManager.SetSignOutState();
        Navigation.NavigateTo("authentication/logout");
    }

    private void BeginLogin(MouseEventArgs args)
    {
        Navigation.NavigateTo("authentication/login");
    }
}
```

####  Authentication registration

```
   builder.Services.AddOidcAuthentication(options =>
            {
                builder.Configuration.Bind("Google", options.ProviderOptions);               
            });
```

#### App Settings

  "Google": {
    "Authority": "https://accounts.google.com/",
    "ClientId": "****u.apps.googleusercontent.com",
    "ClientSecret": ""Not needed",
    "PostLogoutRedirectUri": "https://localhost:44316/authentication/logout-callback",
    "RedirectUri": "https://localhost:44316/authentication/login-callback",
    "ResponseType": "id_token"
  },

### Error rendered in browser

> There was an error trying to log you out: ''

### Error shown in address bar

> The%20logout%20was%20not%20initiated%20from%20within%20the%20page.

![image](https://user-images.githubusercontent.com/1756871/111850788-80020f00-8911-11eb-9ddc-2b6c1e5da76d.png)

#### Project details

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <UseBlazorWebAssembly>true</UseBlazorWebAssembly>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

#### Referenced packages.

```

 <ItemGroup Condition="'$(TargetFramework)' == 'net5.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="5.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />

  </ItemGroup>

 <ItemGroup>
    <!--<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />-->
    
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="5.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.4" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Client" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="NSwag.ApiDescription.Client" Version="13.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

```

**Comment by ChristianWeyer** [comment]
Hey Damir!

I tried to repro your observation. Please see my small sample here:
https://github.com/ChristianWeyer/blazor-wasm-oidc-google-repro

I was not able to obey the same error you are seeing. (Please make sure the redirect URLs in your Google app are configured correctly).
Could you take a look and let me know whether I. missed a scenario in my code @ddobric ?
Thanks!

**Comment by javiercn** [comment]
@ddobric thanks for contacting us.

I'm not sure what's going on in this case, and I don't think we have enough information to asses your scenario. 
We do have end to end automation covering logout, and from your sample is not clear to us that you aren't doing something in a slight different way that might be causing the issue you are observing.

**Comment by ddobric** [comment]
@ChristianWeyer thanks for repro. Starting from the green field works. The issue here is that this was working. It is a long-running project moved from AAD to Oidc etc.

@javiercn I have created a repro by cutting out 99% of the code and figured out that this issue occurs when MailLayout.razor uses AuthorizeView. 

This is the example that causes the error described above:

```
@inherits LayoutComponentBase

<div class="page">
    <AuthorizeView>
        <Authorized>
            <div class="sidebar">
                <NavMenu />
            </div>
            <div class="top-row px-4 auth">
                <LoginDisplay />
            </div>
            <div class="main">
                <div class="content px-4">
                    @Body
                </div>
            </div>
        </Authorized>
        <NotAuthorized>
            <div class="top-row px-4 auth">
                Please login: <LoginDisplay />
            </div>
            <div class="content px-4">
                @Body
            </div>
        </NotAuthorized>
    </AuthorizeView>
</div>
```

This is a working example as created by project template:

```
<div class="sidebar">
                <NavMenu />
            </div>
            <div class="top-row px-4 auth">
                <LoginDisplay />
            </div>
            <div class="main">
                <div class="content px-4">
                    @Body
                </div>
 </div>
```

To me, this  "issue" is solved, but I would recommend to think about the error message:

1. The error message is saying nothing useful, and it has no intuitive relation to AuthorizationView.
2. The error message is written in the address bar.

It looks os a framework in the prototype stage.

**Comment by javiercn** [comment]
@ddobric if you can provide the repro project that would help us. I want to better understand what's going on here and want to make sure I don't miss anything.

**Comment by ddobric** [comment]
Have repro-solution right now. But, as described in my last comment, the issue occures when the MainLayout is enclosed in AuthorizeView.
