### ISSUE TITLE
Angular 11 not working with baseHref set

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31084]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Angular-11-not-working-with-baseHref-set/1348492)._

---
[severity:It's more difficult to complete my work]
VS2019 16.8.6
- install new asp.net core project with angular
- npm install

Updated to Angular 11 according to https://update.angular.io/

 - ng update @angular/cli@8 @angular/core@8
 - ng update @angular/cli@9 @angular/core@9
 - npm uninstall @nguniversal/module-map-ngfactory-loader --save [otherwise error in next step]
 - ng update @angular/cli@10 @angular/core@10
 - ng update codelyzer [otherwise error in next step]
 - ng update @angular/cli @angular/core
 - removed last line of main.ts  
`export { renderModule, renderModuleFactory } from '@angular/platform-server';`

F5 inside VS starts application and browser shows frontend

- add  
"baseHref": "/sub/"  
to angular.json ("architect" - "build" - "builder" - "options")

- add  
/sub  
to 
project properties - Debug - Web Server Settings - App URL

F5 inside VS starts application and browser shows   
**Cannot GET /**

Using `ng serve` and pointing the browser to   
https://localhost:4200/sub/  
works as expected

Any ideas how to use baseHref with Angular 11 and Visual Studio 2019?

---
#### Feedback Bot on 2/24/2021, 05:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/25/2021, 10:25 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

We believe this is something in your app configuration. You need to setup the launchUrl in your launchSettings.json to reflect the fact the app is being served from a subpath. In addition to that, you might need to update your startup application accordingly.

**Comment by steigerm** [comment]
1. everything worked before upgrading to ng11
2. launchUrl in launchSettings.json was set
3. angular.json configuration is fine because `ng serve` works only starting from VS fails
4. If I remove baseHref from angular.json VS works but then `ng build` does not generate a correct release build
