### ISSUE TITLE
Can't see generated OpenAPI generated Client after the Latest Update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31087]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-see-generated-OpenAPI-generated-Cl/1367840)._

---
[regression] [worked-in:16.8]
I was using the OpenAPI generator in VS 16.8 and it was generating a bunch of files in the project, hanging under Connected Services.
Now, since I have upgraded to 16.9, I can't see them anymore the files. 
The files seem to be under the folder obj, but easily not visible in the solution as they used to be in the previous version.

! [image.png] (https://aka.ms/dc/image?name=B9c4de867e0c54c6b80eb5c5daa25bc95637511148814245200_20210312-140120-image.png&tid=9c4de867e0c54c6b80eb5c5daa25bc95637511148814245200)

---
#### Feedback Bot on 3/11/2021, 10:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/12/2021, 01:15 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment]
AFAIK, this is expected behavior for the OpenAPI client generator by default. This behavior can be modified by setting the `OpenApiCodeDirectory` property to the generator. This can be done by setting the `OutputPath` property on the `OpenApiReference` type.

```
<OpenApiReference>
  <OutputPath>YourPathHere</OutputPath>
</OpenApiReference>
```
