### ISSUE TITLE
Persistence issue for created room in signalr hub

### ISSUE THREAD

**Issue by RahulSapkota** [dotnet/aspnetcore#31096]
I have created SignalR hub, which listens the events for creating room and attaching the room to user. It works fine if I use different tabs in same browser or open in incognito mode. But as soon as I try to access it through other network the room does not appear.

Did anyone faced same situation as me and found out the resolution or any approach to work around would be helpful.

**Comment by davidfowl** [comment]
It's unclear what you mean. When you say there's a persistence issue, what you do mean? What is being stored where? Are you using a single server instance?
