### ISSUE TITLE
Exception thrown from StaticContentProvider._manifestProvider

### ISSUE THREAD

**Issue by b-straub** [dotnet/aspnetcore#31106]
### Describe the bug
The commit 2d5da9c879065d1015bbd018470e2e64081a9cb1 triggers a long standing and never fixed dotnet extensions bug:
[ManifestEmbeddedFileProvider not working when Resources.resx in same project](https://github.com/dotnet/extensions/issues/1333)

### To Reproduce
Run the sample app from "\src\Components\WebView\Samples\BlazorWinFormsApp"

### Exceptions (if any)
InnerException = {"Invalid manifest format. 'ResourcePath' must contain a text value. ''"}
Message = "The type initializer for 'Microsoft.AspNetCore.Components.WebView.StaticContentProvider' threw an exception."

**Comment by javiercn** [comment]
@b-straub thanks for contacting us.

@Eilon  we might have missed that. We need to mark the embedded resource with ExcludeFromManifest=true
