### ISSUE TITLE
Issue debugging Blazor WASM in Visual Studio Code

### ISSUE THREAD

**Issue by RicardoValero95** [dotnet/aspnetcore#31105]
### Describe the bug
Can't debug a Blazor WASM app in Visual Studio Code. 

Cross-reference: https://github.com/dotnet/AspNetCore.Docs/issues/21825
cc: @guardrex

**Comment by guardrex** [comment]
@RicardoValero95 ... Copy over all of the content from the docs issue.

**Comment by RicardoValero95** [comment]
Sorry @guardrex

### Describe the bug
I keep failing to debug Blazor WASM. 
I think I followed everything from the article [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio).
I can run it without problems. 

### To Reproduce
1. Create a Blazor WASM app
`dotnet new blazorwasm -o MyBlazorApp`

2. Install the extensions and follow the other steps in the article

3. Setup the `launch.json`

```json 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "browser": "edge",
            "cwd": "${workspaceFolder}/src/MyFirstBlazorApp"
        }
    ]
}
```
4. Start debugging (F5)

### Exceptions (if any)
This message keeps popping on:
```
Couldn't find a debug adapter descriptor for debug type 'blazorwasm' (extension might have failed to activate)
```

I also can't get rid of this from the `Problems` tab:
```json
{
	"resource": ".../MyBlazorApp/src/MyBlazorApp/Program.cs",
	"owner": "csharp",
	"code": "CS0246",
	"severity": 8,
	"message": "The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [MyBlazorApp]",
	"source": "csharp",
	"startLineNumber": 18,
	"startColumn": 40,
	"endLineNumber": 18,
	"endColumn": 43
}
```

### Further technical details

MacBook Air (M1, 2020) 
- macOS Big Sur v11.2.3 (20D91)
- .NET SDK v5.0.201
- Visual Studio Code v1.54.3
  - C# v1.23.9
  - .NET Install Tool for Extension Authors v1.0.0
  - Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension v1.0.0
- Microsoft Edge v89.0.774.54 

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@captainsafia can you please look into this? Thanks!

**Comment by captainsafia** [comment]
> I also can't get rid of this from the Problems tab:

So, this particular feedback is coming from the C# extension. You might want to file an issue specifically for that over at https://github.com/OmniSharp/omnisharp-vscode.

> This message keeps popping on:

This message indicates that VS Code wasn't able to find the debug type associated by Blazor apps. This debug type is registered by the C# extension.

Based on the two problems you reported, I'd recommend doing a clean install of the C# extension. See https://stackoverflow.com/a/36751445 for instructions on how to clean install an extension.

**Comment by RicardoValero95** [comment]
So work has been getting on the way, sorry... but I still haven't figured out how to fix this. I've wiped the extensions, reinstalled vscode, created a new Blazor wasm project but still the same errors appear. Is this a M1 related issue?

**Comment by captainsafia** [comment]
@RicardoValero95 Just to clarify, the "same error" is:

> Couldn't find a debug adapter descriptor for debug type 'blazorwasm' (extension might have failed to activate)

If you did a re-install, I would recommend verifying that the C# extension was installed again.

**Comment by liorbalmas** [comment]
Hi
I also have this issue.
Tried to clean and reinstall extensions but no luck..
@captainsafia, if that works for you, can you please share your launch.json file?

Thank you.

**Comment by captainsafia** [comment]
As a fallback, you can use the following two-step launch.json

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (Blazor Standalone)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "run"
            ],
            "cwd": "${workspaceFolder}/src/Project.UI",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        },
        {
            "name": ".NET Core Debug Blazor Web Assembly in Chrome",
            "type": "pwa-chrome",
            "request": "launch",
            "timeout": 30000,
            "url": "https://localhost:5001",
            "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
        }
    ]
}
```
