### ISSUE TITLE
Tear down of Microsoft.AspNetCore.Components.WebView

### ISSUE THREAD

**Issue by b-straub** [dotnet/aspnetcore#31112]
### Describe the bug
The tear down of the 'Microsoft.AspNetCore.Components.WebView' component will cause an exception

### To Reproduce
Add the following code line to "src\Components\WebView\Samples\BlazorWinFormsApp"
`public Form1()
 {
...
            serviceCollection.AddScoped<ExampleJsInterop>();
}
`
Add the following code line to "src\Components\WebView\Samples\WebviewAppShared"
`@inject ExampleJsInterop Js
`

### Exceptions (if any)
System.InvalidOperationException: ''WebviewAppShared.ExampleJsInterop' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.'

### Further technical details
The same problem has been reported here #13343

**Comment by Eilon** [comment]
@TanayParikh - is this related to the issue you're working on for JS Interop in BlazorWebView?

**Comment by TanayParikh** [comment]
> @TanayParikh - is this related to the issue you're working on for JS Interop in BlazorWebView?

No, this doesn't seem to be related.

**Comment by Eilon** [comment]
Main part of the fix is in https://github.com/dotnet/aspnetcore/pull/33482. The rest will be in https://github.com/dotnet/maui/pull/1678

**Comment by Eilon** [comment]
This is fixed in RC1 as part of https://github.com/dotnet/maui/issues/1280.
