### ISSUE TITLE
Fresh VS 2019 installation: Unable to find packageMicrosoft.AspNetCore.Components.WebAssembly

### ISSUE THREAD

**Issue by tr4g** [dotnet/aspnetcore#31113]
### Describe the bug
I'm trying to create a Blazor project, I'm picking "WebAssembly" option and leaving all default settings. After the project is created, I get all these errors on the console:

![image](https://user-images.githubusercontent.com/197329/111914303-b2c31900-8a71-11eb-9845-9af2247fe966.png)

### To Reproduce

Have a fresh install of Visual Studio 2019 community, then install web packages as required to create Blazor projects, then create a new project and check the error list.

### Further technical details
- ASP.NET Core version  : **5.0**
- Include the output of `dotnet --info`

```
SDK de .NET (que refleje cualquier global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Pilchie** [comment]
It looks like you have either removed NuGet.org from your list of package sources, or have turned off automatic package restore at Tools\Options\NuGet Package Manager.  Can you take a look?

**Comment by tr4g** [comment]
thanks @Pilchie , it turned out to be that it was missing from the list, however it was a fresh install so i don't get how it got removed in the first place

**Comment by Pilchie** [comment]
Not sure either - you can follow up on https://github.com/NuGet/Home if you want to pursue that, but I'm going to close this as it seems to be resolved.
