### ISSUE TITLE
Blazor WASM standalone: How to implement OIDC authentication with multiple providers?

### ISSUE THREAD

**Issue by ddobric** [dotnet/aspnetcore#31114]
We have implemented the OIDC authentication in Blasor WASM standalone for Google, AAD etc. as described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio).

The selection of the provider is done with the following code in the startup.cs. This works fine.

```
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("Local", options.ProviderOptions);
});
```

Is it possible and if, how to implement support for multiple providers at the same time as known from ASP.NET Core? It means the user selects the provider and authentication is redirected to the selected provider.
The code shown above is bound to the configuration that specifies the provider. It is executed on startup and cannot be changed by the user's selection.

Looking for something like this:

```
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("Google", options.ProviderOptions);
});
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("AAD", options.ProviderOptions);
});
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("Twitter", options.ProviderOptions);
});
```

Is that currently possible? If so, looking for an example (pseudo code).

Thanks in advance.

**Comment by javiercn** [comment]
@ddobric thanks for contacting us.

This is not a scenario we support out of the box. 

If you want to enable something like this you would need to dive into the extensibility model to support it. Unfortunately this is likely to be somewhat involved and we don't have the bandwidth to produce a sample for it, but if you are interested in trying to implement it yourself, we could give you some pointers on where to start.

**Comment by ddobric** [comment]
Thanks for your response @javiercn.
Yes this question is related to the standalone application. And yes, I would be great to provide some useful pointers.

Thanks

**Comment by ddobric** [comment]
🤔 why is this on status resolved?

**Comment by javiercn** [comment]
@ddobric the general question is solved in the sense that is not an scenario we support. If you want to do this you'll have to:
* Create your own "provider" (look at the msal backed library for a reference). 
* Within that provider you'll need to maintain a dictionary of authentication options.
* You'll have to key the UI (login-callback and so on based on the available auth options).
* You'll have to flow those options to the underlying JS supporting authentication service overriding methods in Microsoft.AspNetCore.Components.WebAssembly.AuthenticationService to handle the different authentication options.
* You'll have to support routing the call to specific providers on the JS side.

For reference:
* Our msal library https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebAssembly/Authentication.Msal/src
* Our authentication service https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts
