### ISSUE TITLE
Unexpected behaviour when using Response.OnCompleted

### ISSUE THREAD

**Issue by disonancia** [dotnet/aspnetcore#31123]
### Describe the bug
I'm trying to perform some background operations after returning an Ok response to the client without affecting the content nor the timing of the response. What I can see is that the response is not sent to the client until the operations within OnCompleted are finished.

The operations include one call to an external api which needs to be called after the response is actually received by the client. Even though, I can reproduce it simply using Task.Delay inside OnCompleted

### To Reproduce
```
public async Task<IActionResult> DoSomething([FromBody] Some some, [FromRoute] string id)
{
await DoSomething(id);

        Response.OnCompleted(async () =>
        {
            await Task.Run(() => Thread.Sleep(5000));
        });
       return Ok();
}
```

OR

```
public async Task<IActionResult> DoSomething([FromBody] Some some, [FromRoute] string id)
{
       try
       {
          await DoSomething(id);
          return Ok();
       }
       finally
       {
          Response.OnCompleted(async () =>
          {
              await Task.Run(() => Thread.Sleep(5000));
          });
       }
}
```

### Further technical details
- ASP.NET Core 3.0
- dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET Core SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Tratcher** [comment]
Which server is this? There was a known issue with  OnCompleted for IIS in-process.

> The operations include one call to an external api which needs to be called after the response is actually received by the client.

While you can know you've sent a response, you can't know when they've received it processed it.

See the following example for the recommended way to dispatch work off of a request:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#queued-background-tasks

**Comment by disonancia** [comment]
Hi Chris,

When searching about the issue I was convinced that the issue was with Kestrel but I obviously misread. Indeed, the issue is happening on IIS in-process in .NET Core. The tests perfomed with Out of process hosting showed the expected behaviour.

We will re-consider the solution and/or migrating to 5.0 to keep the hosting in-process.

Thanks a lot for the feedback.
