### ISSUE TITLE
Resource based localization not working for flags enum

### ISSUE THREAD

**Issue by whvanderpost** [dotnet/aspnetcore#31122]
### Describe the bug
I'm using localization in my ASP .Net Core WebApplication (.net 5). Translation of a (flags) enums work perfectly, but when I have a value with more than one flag it does not translate, as seen in the screenshots below:

en-US:
![image](https://user-images.githubusercontent.com/2821657/111981635-36c7e000-8b08-11eb-949f-4d24350049e0.png)
nl-NL:
![image](https://user-images.githubusercontent.com/2821657/111981661-3f201b00-8b08-11eb-83b0-ed8687569a0a.png)

Translation of a single item (Missing) works, translation of a value with 2 flags (LampFailure and Missing) doesn't work.

### To Reproduce
Included is a solution ([WebApplication1.zip](https://github.com/dotnet/aspnetcore/files/6181666/WebApplication1.zip)). 
In this solution identity is also added to be able to quickly change the UI language, to change it:
- Create a user account
- Login
- Go to the user profile page and change the Language with the pull down menu.
- Go back to the home page to see the test values.

### Exceptions (if any)
-

### Further technical details
- ASP.NET Core version: 5
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE: 
```
Microsoft Visual Studio Community 2019 - Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please provide the repro app as a minimalistic GitHub repo. We won't b e able to use repros in other formats going forward.

**Comment by whvanderpost** [comment]
> Thanks for contacting us. Please provide the repro app as a minimalistic GitHub repo. We won't b e able to use repros in other formats going forward.

repro available: https://github.com/whvanderpost/core-issue-repro

**Comment by hishamco** [comment]
@whvanderpost could you please update your repo to .NET 7.0, I need to reproduce the issue, then probably pushing a fix for it

**Comment by whvanderpost** [comment]
> @whvanderpost could you please update your repo to .NET 7.0, I need to reproduce the issue, then probably pushing a fix for it

Hi, I've upgraded the repo to .NET 7 and the problem seems to be fixed already.

**Comment by hishamco** [comment]
Looks good
