### ISSUE TITLE
Should Kestrel try to keep HTTP/1.1 connections open after 413s?

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#31136]
I wonder if it also wouldn't make sense to attempt to have Kestrel drain even too-large bodies if we can do so within the 5 second drain timeout (which we would need to make configurable). Kestrel would continue to respond with a 413 and throw from Request.Body.ReadAsync.

This has come to my attention because an internal customer noticed a spike in other seemingly-unrelated errors after Kestrel responded to a bunch of requests with too-large request bodies with 413s and closed connection. I can see how a bunch of connections between a reverse proxy and the Kestrel backend being closed due to 413 errors could cause perf/reliability issues with an otherwise well-behaving app. Clients generally try to keep HTTP connections alive because it's far more efficient to do so and you avoid running into port exhaustion issues (though port exhaustion usually happens when the client rather than the server starts closing TCP connections leaving them in TIME_WAIT so I don't think that's the issue here).

This would mean wasting some cycles to /dev/null payloads that are potentially very large, but the cost should be fairly symmetric to that of the client. Closing the connection and requiring a client to reopen a connection isn't exactly cheap either.

@blowdart @GrabYourPitchforks

**Comment by halter73** [comment]
If we do this, we could no longer respond with the "Connection: close" header. That means if the drain does time out, the behavior is worse than what we have today because the client might try to reuse the connection after Kestrel has abandoned it.

**Comment by halter73** [comment]
We should consider automatically injecting a "Connection: close" header when the app writes its own 413 response. Maybe we could do this any time flush headers and we already know the request body exceeds the limit. Do we need to worry about the app changing the limit after flushing headers? That seems unlikely but technically possible.

**Comment by BrennanConroy** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/31169
