### ISSUE TITLE
Unable to pass UrlHelper to the App component

### ISSUE THREAD

**Issue by JHBonarius** [dotnet/aspnetcore#31135]
### Describe the bug
For some reason somebody decided that my previous issue (#31097) was resolved and that it should be closed. I disagree, as I'm not helped and it's still broken.

To reiterate: We have a large project using Razor Pages and Razor Views (MVC). Many many pages. We're now using js and jquery, but would like to slowly switch over to Blazor. As it is an ongoing project, controller routes have changed over the years, or are different between users, thus we don't want to hardcode urls in our code.

I.e. one of many controllers is
```c#
public class FooController : Controller
{
    [Route("Alpha/Beta")]
    Public public IActionResult Index() => View();
}
```
which in future might change to 
```c#
public class FooController : Controller
{
    [Route("Gamma/Delta")]
    Public public IActionResult Index() => View();
}
```

Thus we've been abundantly using HTML helpers, like the `Microsoft.AspNetCore.Mvc.TagHelpers` and the `Microsoft.AspNetCore.Mvc.UrlHelper` in both Razor Pages and Views. We want (and expect) the same in Razor Components.

i.e. we really wat to use things like
```c#
UrlHelper.ActionLink(controller: "Foo", action: "Index")
```
or
```html
<a asp-controller="Foo" asp-action="Index">All Speakers</a>
```
To have a helper determine the route dynamically.

Javier commented on my previous question to pass data to the Route Component. I've been trying that, but it doesn't seem to work.

To `_Host.cshtml` I added a model
```c#
    public class _HostModel : PageModel
    {
        public IUrlHelper UrlHelper { get; init; }

        public _HostModel(IUrlHelper urlHelper)
        {
            UrlHelper = urlHelper;
        }
    }
```
To `App.razor` I added:
```c#
@code{
    [Parameter]
    public IUrlHelper UrlHelper { get; set; }
}
```
Then I modified `_Host.cshtml`.
```html
    <component type="typeof(App)" param-UrlHelper="Model.UrlHelper" render-mode="Server" />
```
Then didn't work  and throws an expection: `InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.`

An to be honest, I think this "passing a data down the (component) hierachy" is not the right way to go. We have DI for that right?

Why is there no simple/good solution for this in Razor Components, while there is in Razor Pages and Controllers? This makes it kind of hard for us to switch over...

### To Reproduce
See previous question

### Exceptions (if any)
`InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.`

### Further technical details
- ASP.NET Core version 5.0.0
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version VS 2019 16.9.2 and 16.10.0 preview 1.0

**Comment by javiercn** [comment]
@JHBonarius I'm sorry about the issue being closed.  Our system closes them automatically after we mark them as resolved. 

Let me clarify a few things:
* URLHelper is an MVC concept that is not meant to be used inside a Blazor Server application.
* If you want to generate links to your controllers/actions you should use [LinkGenerator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.linkgenerator?view=aspnetcore-5.0) instead.
* You should avoid any overload that uses HttpContext since it's not available inside Blazor applications.

**Comment by JHBonarius** [comment]
@javiercn YES! GREAT! Thanks! 🥳🥳🥳
That was what I was looking for. Is that in the documentation? Else it should definitely be! (Or be more in the spotlight).
I close this now.
