### ISSUE TITLE
'Go to definition' on child component does not work in razor file in some projects.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31139]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Go-to-definition-on-child-component-do/1373198)._

---
[severity:It's more difficult to complete my work]
Hello.

I am working on a a server side blazor project with using Visual Studio 2019 Community (Version 16.9.2). And until recently I used resharper extension. But I had to disable it because editing in razor caused frequent hangs.
Since I disabled resharper, I noticed that 'Go to definition' action does not work on child components in razor file.
This action does not work not matter whether experimental editor feature is enabled or not.
I also tried to open my project with Visual Studio Code and there I have the same experience.
Then I created a new server side blazor project and I found out that 'Go to definition' action is working there.
Also I noticed difference in highlighting in my and template project.
For template project child component in razor is always highlighted with bold font.
But in my project child component in razor often is not highlighted with bold font. 
Often when I opening razor file I see that child components are highlighted with bold font for short time period (less than 1 second). But sometimes they are kept highlighted with bold font but 'Go to definition' action still does not work.

So it seems the issue somehow related with project content but I can't figure out myself what is wrong.
I will be grateful for any help.

Thanks in advance,
  Dmitry Filippov.

---
#### Feedback Bot on 3/18/2021, 01:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Hello, would you mind providing some additional repro steps? Are you saying that navigating via F12 in a nested Blazor component on `Child` in :

```CSHTML
<Parent>
    <Child>
    </Child>
</Parent>
```

doesn't work for you in the new experimental Razor editor?

**Comment by crui3er** [comment]
Hello,
not exactly.
Navigating via F12 both to Parent and Child components does not work. But it does not work for particular one project I am working on now. For other projects this functionality is working.
Moreover this functionality does not work on this project nor for experimental Razor editor, not for regular one.
And I can't figure out what prevents normal functionality.
