### ISSUE TITLE
ManifestEmbeddedFileProvider not working when Resources.resx and other embedded resources (like .XML files) are part of same project

### ISSUE THREAD

**Issue by satishfied** [dotnet/aspnetcore#31131]
Bug description:

Ref: https://github.com/dotnet/extensions/issues/1333
When adding a regular Resources.resx file into an asp.net core (.NET 5)  project that uses <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest> and a ManifestEmbeddedFileProvider, the file provider throws an InvalidOperationException with this message:
Invalid manifest format. 'ResourcePath' must contain a text value. ''

Using nuget package "Microsoft.Extensions.FileProviders.Embedded" version 5.0.3 running in .NET 5 ASP.NET core project 

Looking into the generated assembly, I found that the generated Resources has "Microsoft.Extensions.FileProviders.Embedded.Manifest.xml" manifest file  looks like this:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Manifest>
	<ManifestVersion>1.0</ManifestVersion>
	<FileSystem>
		<File Name="">
			<ResourcePath></ResourcePath>
		</File>
	<File Name="Microsoft.Extensions.FileProviders.Embedded.Manifest.xml">
	<ResourcePath>Microsoft.Extensions.FileProviders.Embedded.Manifest.xml</ResourcePath>
	</File>
	</FileSystem>
</Manifest>
```

### To Reproduce
1. Add following code snippet into startup ConfigureServices

            `var physicalProvider = environment.ContentRootFileProvider;
            var assembly = typeof(Program).Assembly;
            var nameSpace = typeof(Program).Namespace;
            //Read Resource from Resource.resx file
            ResourceManager manager = new ResourceManager($"{nameSpace}.Resource", assembly);
            var resourceKey1Value = manager.GetString("Key1");
            var manifestEmbeddedProvider = new ManifestEmbeddedFileProvider(assembly);
            var compositeProvider = new CompositeFileProvider(physicalProvider, manifestEmbeddedProvider);
            services.AddSingleton<IFileProvider>(compositeProvider);   `     

2. in  public void Configure(IApplicationBuilder app, IWebHostEnvironment environment), add
app.UseStaticFiles();
3. Using version '5.0.3' of package 'Microsoft.Extensions.FileProviders.Embedded'
4. Run this code '....'
4. See error at  "var manifestEmbeddedProvider = new ManifestEmbeddedFileProvider(assembly);" in Startup.cs

### Expected behavior
No Error should be thrown

### Screenshots

![image](https://user-images.githubusercontent.com/16125236/109580914-45dee380-7ab0-11eb-8371-81ada102f98b.png)
![Invalidmanifestformat1](https://user-images.githubusercontent.com/16125236/109580984-6ad35680-7ab0-11eb-8cf0-7c1586b8a7d1.png)
![ProjectFileWithExcludeFromManifest](https://user-images.githubusercontent.com/16125236/109580985-6b6bed00-7ab0-11eb-8fb5-8dc2efe22b16.png)
![DefaultProjectFile](https://user-images.githubusercontent.com/16125236/109580990-6b6bed00-7ab0-11eb-8b68-f77321995114.png)
![dotPeek_ResourcesManifest](https://user-images.githubusercontent.com/16125236/109580991-6c048380-7ab0-11eb-8605-154cee4df68c.png)
![VS_Invalidmanifestformat](https://user-images.githubusercontent.com/16125236/109580992-6c048380-7ab0-11eb-8ec9-e8131602d246.png)

### Additional context
If I add following XML node in .csproj to exclude Manifest for Resource.resx it solves the problem of Empty ResourcePath in Microsoft.Extensions.FileProviders.Embedded.Manifest.xml
https://github.com/satishfied/TestWebAPIForFileProviders

**Comment by javiercn** [comment]
@satishfied thanks for contacting us.

You can exclude them from the project via `<EmbeddedResource Update="..." ExcludeFromManifest="true" />`

**Comment by satishfied** [comment]
Yes, I had resolved this issue 

> @satishfied thanks for contacting us.
> 
> You can exclude them from the project via `<EmbeddedResource Update="..." ExcludeFromManifest="true" />`

Yes, I resolved it using  

```
<ItemGroup>
	  <EmbeddedResource Include="ResourceXMLFile.xml"/>
	  <!--Need to make sure that exclude manifest for .resx to resolve runtime error for Empty ResourcePath in Manifest file-->
	  <EmbeddedResource Update="Resource.resx">
		  <ExcludeFromManifest>true</ExcludeFromManifest>
	  </EmbeddedResource>
	</ItemGroup>
```
