### ISSUE TITLE
Differentiate between design time and run time compiled sources in Razor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#31155]
To fulfill both tooling requirements and runtime requirements, the Razor compiler currently generates two different generated types from a single source Razor file:

- A design time build that tooling uses for intellisense, etc.
- A runtime build that is used when the app is executing

Although these generated files are entirely different representations, they have the same source file, filename, and contain some of the same type definitions.

This can cause havoc in VS when both design-time and runtime builds are included in the workspace.

![image](https://user-images.githubusercontent.com/1857993/112193903-946e3200-8bc5-11eb-8bec-b1ad57431867.png)

We need a way to differentiate between runtime and design-time generated files and have a way for the Roslyn workspace to ignore design-time builds when compiling.

**Comment by EmilyFeng97** [comment]
@captainsafia Verify this issue on the lateast .Net 6.0 Preview 3 (6.0.100-preview.3.21201.20) , this issue not repro.

**Comment by captainsafia** [comment]
@EmilyFeng97 Great! Thanks for the update.

**Comment by captainsafia** [comment]
Closing since we completed the work necessary for this on our end.

There's still pending work for VS to react to the changes.
