### ISSUE TITLE
Purpose of RazorGeneral.xaml rule file

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspnetcore#31150]
The .NET Project System team is producing a new Project Properties UI. It generates its property model from XAML rule files.

For ASP.NET Web Applications, a "Razor Properties" rule file is injecting properties at the top of this UI:

![image](https://user-images.githubusercontent.com/350947/111923248-50f6c380-8af2-11eb-9343-f798a87ee9dd.png)

The values are coming from https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Rules/RazorGeneral.xaml

Are these properties useful to the user?

If these properties are not useful to the user, let's work to remove this rule file from the Project Properties UI altogether.

If they are useful, let's tweak the experience:

- Order the page lower down in the UI
- Add descriptions to the properties
- Add `HelpUrl` values is appropriate, so that the user can easily navigate to more information about these properties
- Potentially change them from `StringProperty` to `EnumProperty` so that a drop-down list of valid values is provided, rather than an open text box.

cc: @captainsafia

**Comment by captainsafia** [comment]
I think we can probably remove this.

There are _rare_ cases where a user might want to change the Razor language version used by their project but with the way the SDK/compiler relate -- this is probably going to cause them more headaches than it is worth. I don't know of any scenarios where an end-user would need to change the configuration (let me know if there are ones, @pranavkm).

Given that if we remove these, they can still modify these values in their project files, I think removing is fine.

**Comment by drewnoakes** [comment]
Thanks @captainsafia. From what you say, removing them sounds sensible.

Is that something that could happen soon? Right now these are appearing high in the list of properties visible in the UI.

**Comment by captainsafia** [comment]
It should be as a straightforward as removing the `RazorGeneral.xml` file referenced above.

One more thing I want to check.

@NTaylorMullen @ryanbrandenburg Does Razor tooling need this file https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Rules/RazorGeneral.xaml for any reason?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen @ryanbrandenburg Does Razor tooling need this file https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Rules/RazorGeneral.xaml for any reason?

Yes, this enables us to introspect on the project system at tooling time to extract information: https://github.com/dotnet/aspnetcore-tooling/blob/5b6dd93b4657f9f9c5fa884a0d1911e7c431ab32/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs#L65-L71

**Comment by drewnoakes** [comment]
Given removing it is not an option, here are the other options:

1. Change the `Context` [here](https://github.com/dotnet/sdk/blob/446589256a6fc128d1adffe83551a727ebf7f234/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.DesignTime.targets#L78-L80) from `Project` to `BrowseObject`, which will remove it from the UI without breaking the ability to access it from code, or
2. Set all properties to have `Visible="False"`, as occurs in [`RazorGenerateWithTargetPath`](https://github.com/dotnet/sdk/blob/446589256a6fc128d1adffe83551a727ebf7f234/src/RazorSdk/Targets/Rules/RazorGenerateWithTargetPath.xaml#L28) and [`RazorComponentWithTargetPath`](https://github.com/dotnet/sdk/blob/446589256a6fc128d1adffe83551a727ebf7f234/src/RazorSdk/Targets/Rules/RazorComponentWithTargetPath.xaml#L28).

You'll notice that the [`RazorExtension`](https://github.com/dotnet/sdk/blob/446589256a6fc128d1adffe83551a727ebf7f234/src/RazorSdk/Targets/Rules/RazorExtension.xaml#L27) rule has visible properties, but does not appear in the UI. This is because it has `File` context type ([here](https://github.com/dotnet/sdk/blob/446589256a6fc128d1adffe83551a727ebf7f234/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.DesignTime.targets#L75-L77)).

The simplest fix to the original problem is just to manually hide the properties, which I've done in https://github.com/dotnet/sdk/pull/16623. That PR should address the core problem here.

I'll leave it to others to decide whether there's a desire to tidy up the slight inconsistency across these rules.
