### ISSUE TITLE
API project or Api: DataAnnotation model bind failures to use JsonPropertyName name if provided

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/aspnetcore#31164]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by javiercn** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/31166
