### ISSUE TITLE
How to get users (Students) from SQL server database by asp.net core signalR?

### ISSUE THREAD

**Issue by amnaw** [dotnet/aspnetcore#31177]
I need to get all the Students from the database and return List<Student> inside signalR Hub class, but every time I get null instead of that list and don't know why, I tried many ways to get that list but none of them worked, 
Can anyone help me please ;(

`

namespace Student_Training.SignalR
{
    [Authorize]
    public class ChatHub : Hub
    {
        private readonly TrainingDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _Identitycontext; 
`

        

        public ChatHub(TrainingDbContext context, UserManager<IdentityUser> userManager, ApplicationDbContext Identitycontext)
        {
            _context = context;
            _userManager = userManager;
            _Identitycontext = Identitycontext;
        }

        
        public override Task OnConnectedAsync()
        {
            Clients.All.SendAsync("BroadcastConnections", LstAllConnections);
            ConnectedUser.Ids.Add(Context.ConnectionId);
            return base.OnConnectedAsync();
        }
        public override Task OnDisconnectedAsync(Exception exception)
        {
            ConnectedUser.Ids.Remove(Context.ConnectionId);
            return base.OnDisconnectedAsync(exception);
        }
        

        public async Task GetUsersToChat()
        {
            // Here we bring list of users
            
            // First Way
            var students  = await _context.Student.Include(s => s.AcademicSupervisor).Include(s => s.Faculty).Include(s => s.Major).Include(s => s.OrganizationSupervisor).ToListAsync();

            // Second Way by Service
            List<Student> users = new UsersListService().GetUsersToChat();

            await Clients.All.SendAsync("BroadcastUsersToChat", students);
        }

    }

}
`

this is the UsersListService:
`

namespace Student_Training.Services
{
    public class UsersListService
    {

        private readonly TrainingDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _Identitycontext;

        public UsersListService()
        {
            _context = new TrainingDbContext();
        }
        // or list of identity user
        public List<Student> GetUsersToChat()
        {
            var students = _context.Student.Include(s => s.AcademicSupervisor).Include(s => s.Faculty).Include(s => s.Major).Include(s => s.OrganizationSupervisor);
            List<Student> studentslist = students.ToList();
            
            return studentslist;
        }
    }
}
`

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.
