### ISSUE TITLE
Mircosoft.apnetcore.Identity v2.2 package not run in core 5

### ISSUE THREAD

**Issue by ganbolor** [dotnet/aspnetcore#31173]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#remove-obsolete-package-references
