### ISSUE TITLE
Is there a way to disable EditForm 

### ISSUE THREAD

**Issue by decie** [dotnet/aspnetcore#31178]
We can use disabled to disable the form in the normal html.

` <form disabled>
           `

But how to disable the entire EditForm in blazor.

**Comment by meziantou** [comment]
It's already possible to add custom attributes to the `form` element by adding attributes to the `EditForm` 

````
@page "/"

<button @onclick="OnClick">Toggle disabled</button>

<EditForm Model="model" disabled=@disabled> @* Add the disabled attribute to the form element*@
    <InputText @bind-Value="model.Name"></InputText>
</EditForm>

@code{
    bool disabled;
    Model model = new Model();

    void OnClick()
    {
        disabled = !disabled;
    }

    public class Model
    {
        public string Name { get; set; }
    }
}
````

However, this attribute doesn't seem to disable inputs on Edge. A workaround is to use a `<fieldset disabled=@disabled>`.
