### ISSUE TITLE
UseStatusCodePagesWithReExecute fails to handle status that is manually set during OnRedirectToAccessDenied event

### ISSUE THREAD

**Issue by SwagStork** [dotnet/aspnetcore#31172]
I have been building a website with Razor Pages and Azure AD using Microsoft.Idneity.Web andMicrosoft.Identity.Web.UI. With policies in place, when a policy fails and the user is unauthorized they will typically be redirected to a standard unauthorized page. However, I modify the OnRedirectToAccessDenied event to throw a 403 instead.

```
services.Configure<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, options => {
    options.Events.OnRedirectToAccessDenied = new Func<RedirectContext<CookieAuthenticationOptions>, Task> (context => 
    {
        context.Response.StatusCode = StatusCodes.Status403Forbidden;
        context.Response.Body = new MemoryStream();

        return context.Response.CompleteAsync();
    });
});
```

If I chose to use `app.UseStatusCodePagesWithRedirects("/errors/{0}");` the error will be captured and redirect just fine. However, when I switch to `app.UseStatusCodePagesWithReExecute("/errors/{0}");` the error is ignored and instead a 403 is redirect return to the browser showing nothing. 

No exceptions are thrown, If you place a break point into the OnGet of the 403.cshtml.cs, it will be hit in both instances, however the 403 page will never render using ReExecute. To me it seems like they should both function the same except one rexeecutes, and the other redirects however this does not seem to be the case.

**Comment by Tratcher** [comment]
Setting `context.Response.Body = new MemoryStream();` and not reverting it later prevents any component from generating a response during the re-execute phase. Are you setting this to suppress the response from the initial request?

Why are you calling `Response.CompleteAsync();` here?

**Comment by SwagStork** [comment]
Well now I feel dumb. Switching it around to this solves the problem. I must have been staring at this for too long.

```
services.Configure<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, options => {
    options.Events.OnRedirectToAccessDenied = new Func<RedirectContext<CookieAuthenticationOptions>, Task> (context => 
    {
        context.Response.StatusCode = StatusCodes.Status403Forbidden;
        return Task.CompletedTask;
    });
});
```

Thanks for calling out why mistakes!
