### ISSUE TITLE
get unobtrusive validation html attributes by ViewModelType and property name

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#31188]
I need to get the unobtrusive validation html attributes (data-val-required="msg", data-val-length, etc.)
Ideally there would be a method like this:
`IDictionary<string, string> dict = GetUnobtrusiveValidationAttributes<TViewModel>(propName);`

I would call this inside an html helper (`IHtmlHelper `extension method)

this issue is similar this one for MVC5 here https://github.com/aspnet/AspNetWebStack/issues/296 where I was able to find a solution, not perfect but it works.

so is this possible in ASP.net Core ?

**Comment by omuleanu** [comment]
I got it working like this:
```
public static IHtmlContent GetVldRules<TModel>(this IHtmlHelper html)
{	
	foreach (var prop in typeof(TModel).GetProperties())
	{
		IHtmlContent content;
		using (html.BeginForm())
		{
			content = html.TextBox(prop.Name);
		}
		
		var tagBuilder = content as TagBuilder;

		var attributes = tagBuilder.Attributes
			.Where(item => item.Key.StartsWith("data-", StringComparison.OrdinalIgnoreCase))
			.ToDictionary(item => item.Key, item => item.Value);
```
the only problem is (just like in MVC5) it only works if I call the html helper in a view with
`@model MyVM`

**Comment by pranavkm** [comment]
Have you looked at https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.validationhtmlattributeprovider.addvalidationattributes?view=aspnetcore-5.0? It would be fairly close to what you're trying to do here.

**Comment by omuleanu** [comment]
> Have you looked at https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.validationhtmlattributeprovider.addvalidationattributes?view=aspnetcore-5.0? It would be fairly close to what you're trying to do here.

how should I use this method ?
or how do I go from `ValidationHtmlAttributeProvider.AddValidation(...)`
to `GetVldAttributes(type, propName)` ?
I don't know how to pass the Model type and property name to this method.

**Comment by pranavkm** [comment]
Something like:

```C#
ModelMetadaProvider modelMetadataProvider = /* from DI */
ValidationHtmlAttributeProvider attributeProvider = /* from DI */
var modelExplorer = modelMetadataProvider.GetModelExplorerForType(typeof(TModel));

foreach (var prop in typeof(TModel).GetProperties())
{
    var propertyExplorer = modelExplorer.GetExplorerForProperty(property.Name);
    var clientAttributes = new Dictionary<string, string>();
    
    attributeProvider.AddValidationAttributes(viewContext, propertyExplorer, clientAttributes);
}
```

Note that I wrote this in notepad, so I'm not entirely sure it compiles

**Comment by omuleanu** [comment]
I finally got it working like this: 
```
public static IHtmlContent GetVldAttrs<TModel>(this IHtmlHelper html)
{
	var res = string.Empty;
	var attributeProvider = html.ViewContext.HttpContext.RequestServices.GetRequiredService<ValidationHtmlAttributeProvider>();

	foreach (var prop in typeof(TModel).GetProperties())
	{
		var clientAttributes = new Dictionary<string, string>();

		var modelExplorer = html.MetadataProvider.GetModelExplorerForType(typeof(TModel), null);
		attributeProvider.AddValidationAttributes(html.ViewContext, modelExplorer.GetExplorerForProperty(prop.Name), clientAttributes);

		res += JsonConvert.SerializeObject(clientAttributes);
	}

	return new HtmlString(JsonConvert.SerializeObject(res));
}
```
