### ISSUE TITLE
No Content Security Policy is compatible with Blazor WASM .Net 5.0 and Chrome 89.0

### ISSUE THREAD

**Issue by whereisaaron** [dotnet/aspnetcore#31190]
### Describe the bug

I have found with Chrome 89.0 it appears **impossible** to use a Content Security Policy with Blazor WASM. It appears the way it is invoked via eval violates any possible Chrome 89.0 CSP policy. For my Blazor WASM app Chrome warns if I don't add `wasm-eval` Chrome won't run the WASM code. But if it add `wasm-eval` and/or `wasm-unsafe-eval` (in addition to unsafe-eval) Chrome say is will both ignore all those and still won't run WASM because no `wasm-eval` 🤣

With `script-src 'self' 'wasm-eval' 'wasm-unsafe-eval' 'unsafe-eval' 'unsafe-inline'` the CSP is basically a no-op policy at this point yet it still can't support WASM.

![image](https://user-images.githubusercontent.com/1109585/112314407-1ca32300-8cfd-11eb-8729-c54b3138ebac.png)

While this appears to be a Chrome Browser issue, it also appears to be triggered by the way the WASM code is invoked by the loader. More discussion here:

https://github.com/WebAssembly/content-security-policy/issues/7

### To Reproduce

Publish a Blazor WASM application with Content Security Policy HTTP header.
Add everything possible to `script-src` and note that Blazor WASM loader still violates the CSP.

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/1109585/112315186-fc279880-8cfd-11eb-9c37-c863334f088a.png)

### Further technical details

- ASP.NET Core version 5.0.201
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2019

.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by whereisaaron** [comment]
For completeness, if you remove the `script-src` sources Chrome 89.0 complains about: `wasm-eval` and `wasm-unsafe-eval`, even while retaining `unsafe-eval` you get this CSP violation instead, saying you have to add back `wasm-eval`:

![image](https://user-images.githubusercontent.com/1109585/112328225-3f880400-8d0a-11eb-9d10-65ae95b4601d.png)

**Comment by javiercn** [comment]
@whereisaaron thanks for contacting us.

Can you give us the CSP policy you are using so that we can see if we can avoid this?

**Comment by whereisaaron** [comment]
Thanks @javiercn AFAIK, only the `script-src` bit is relevant, but here is the whole example I was testing.

`default-src 'self'; object-src 'none'; style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com/ https://use.fontawesome.com/; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://stackpath.bootstrapcdn.com/ https://code.jquery.com/ https://cdn.jsdelivr.net/ https://cdn.raygun.io/ https://www.googletagmanager.com/; img-src 'self'; font-src 'self' https://use.fontawesome.com/; connect-src 'self' https://www.google-analytics.com/ https://api.raygun.io; report-to foo`

**Comment by javiercn** [comment]
@whereisaaron thanks for the additional details.

It'll make it easier for us to see the exact line in source that it's causing the problem and determine what we can do about it.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This seems to be a WebAssembly issue on Chrome. It's tracked at https://github.com/WebAssembly/content-security-policy/issues/7

**Comment by coderanger** [comment]
I'm a little confused, the policy @whereisaaron showed is using unsafe-eval. Seeing similar issues and I think this might have been closed too early.

**Comment by javiercn** [comment]
@coderanger it's a bug in chrome causing this, not a bug in our code there's nothing we can do about it on our side.

**Comment by coderanger** [comment]
The linked issue shows clearly that it's supposed to work with unsafe-eval, and unsafe-eval is present. I agree it might be a bug in Chrome but I don't think it's the one linked so far and I'm unable to find a matching Chromium report so maybe we should file one?

**Comment by coderanger** [comment]
Digging deeper into the Chromium bug tracker I found https://bugs.chromium.org/p/chromium/issues/detail?id=915648 which appears to say this might not even be a real bug, just a spurious error :)

**Comment by whereisaaron** [comment]
@coderanger you correct; the error you get in CSP 'report-only' mode is bogus - ignore it. The 'issue' you get in CSP enforcing mode it also bogus, ignore that too. See #7 for the full detail and screen shots. The `script-src unsafe-eval` does work to enable WebAssembly for Chrome same as other browsers, despite what the errors/issues say 😄. Thanks for the 2018 bug reference, that looks like exactly my experience.
