### ISSUE TITLE
How do I build all managed code in the repo?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/aspnetcore#31194]
https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md talks about there being a build.cmd that it suggests is in the root of the repo, but there's no such build.cmd currently.  I do see one in various subdirectories, e.g. src\Servers.

**Comment by davidfowl** [comment]
cc @captainsafia

**Comment by captainsafia** [comment]
@stephentoub You can run `.\eng\build.cmd`.

**Comment by javiercn** [comment]
@captainsafia can you update the docs?

**Comment by captainsafia** [comment]
As part of https://github.com/dotnet/aspnetcore/issues/27631, we moved the top-level build script to encourage contributors to use the project-specific build scripts (which are what people should do 98% of the time).

We can add a little disclaimer about the location of the top-level build script for those who need it.

**Comment by stephentoub** [comment]
Thanks.  In my case, I wanted to enable an analyzer, in which case not building all the code in the repo would be irresponsible :)
