### ISSUE TITLE
Add CreatedAtActionResult<T> and associated ControllerBase method.

### ISSUE THREAD

**Issue by rcollette** [dotnet/aspnetcore#31192]
### Is your feature request related to a problem? Please describe.
I would like to avoid having to use the annotation
```c#
[ProducesResponseType(typeof(SomeDto), StatusCodes.Status201Created)]
```
`Action<T>` is recognized for OpenApi generation but `CreatedAtActionResult` is not because it is not a generic type.  

I also believe there may be some simplification of unit tests based on

https://github.com/dotnet/AspNetCore.Docs/issues/12533

### Describe the solution you'd like

Add a type `CreatedAtActionResult<T>` perhaps using `ActionResult<T>` as its base.   Add the method `ControllerBase.CreatedAtActionResult<T>()`

**Comment by javiercn** [comment]
@rcollette thanks for contacting us.

This doesn't align with how ActionResult<T> is designed. ActionResult<T> is meant to be a T element or an action result and its used for providing type hints for API explorer.

**Comment by rcollette** [comment]
@javiercn Can you explain why CreatedAtActionResult cannot be made generic to also provide type hints to API explorer?
