### ISSUE TITLE
Blazor publish - brotli compression runs against images?

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#31193]
### Describe the bug

I have read that images should not be compressed either by gzip or Brotli as they are already compressed and compressing them again will make their sizes larger.

Given this assertion, I noted the following build output when running a `dotnet publish` of my blazor wasm application, and saw that it appeared to be compressing image files:

```
 D:\a\1\s\src\Foo\wwwroot\Images\Bar\Logos\1a.jpg
         -o
         D:\a\1\s\src\Foo\obj\Release\net5.0\compress\sU1SxZNy.br
         -s
         D:\a\1\s\src\Foo\wwwroot\Images\Bar\Logos\1b.png
         -o
         D:\a\1\s\src\Foo\obj\Release\net5.0\compress\nCCbL+ww.br
```

Either the output is misleading, the assertion is not valid, or this can be considered a bug?

### To Reproduce
publish any blazor wasm project in Release configuration, that has some images such as jpg files etc.

### Further technical details
- ASP.NET Core version: 5.0.2
- Include the output of `dotnet --info`
 build server builds with dotnet sdk `5.0.102`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by andrew-tevent** [comment]
Seeing this also.  It makes the publish output massively inflated as files are triplicated for no reason.

![image](https://user-images.githubusercontent.com/78795042/113160195-2e248780-9235-11eb-825a-fc808258d3bd.png)

AFAIK a browser won't request a .gz or .br compressed version of an already compressed image type?

**Comment by SteveSandersonMS** [comment]
We believe this is fixed in newer .NET 6 previews. Please try out the latest and let us know if you still see the issue. Thanks!
