### ISSUE TITLE
[Blazor] Is ObjectGraphDataAnnotationsValidator production-ready?

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#31208]
Hi,

Is there a reason why ``ObjectGraphDataAnnotationsValidator`` is still "experimental"? Can I use it in production? When will it be part of the official .NET?

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/28640
