### ISSUE TITLE
RequestTimezoneMiddleware for ASP.NET Core

### ISSUE THREAD

**Issue by trannamtrung1st** [dotnet/aspnetcore#31203]
### Is your feature request related to a problem? Please describe.
I want to enable time zone detection functionality in my i18n application. However, I can not find any built-in way from the current framework for this.

### Describe the solution you'd like
Can we create a middleware like RequestLocalizationMiddleware? I think it is suitable in this situation.
I enabled the functionality in my app using this approach and it would be great if I could contribute my idea to the repo.

### Additional context
I'm using .NET Core 3.1 SDK and ASP.NET Core

**Comment by Tratcher** [comment]
How would the middleware determine the time zone a request originated from? And what would you expect it to do with that information?

**Comment by trannamtrung1st** [comment]
> How would the middleware determine the time zone a request originated from? And what would you expect it to do with that information?

### How?
Like **RequestLocalizationMiddleware**, we can provide some built in Timezone providers from Query, Header, Cookie. The clients will send the value of current TimeZoneId (e.g., SE Asia Standard Time) or the current TimezoneOffset (in minutes) so server could determine the time zone of current request.

### What I want to do
In my application, when a client submits a datetime value, I need to identify which time zone of the request is so that I can convert it to UTC then save to the storage, e.g., I want to setup a reminder in Google calendar in my current time zone. Without information of my time zone, I think Google calendar can not determine how to store the time properly. 
In contrast, if I store UTC datetime value, I need to know the current time zone of the client so I can convert the value to proper time zone before return it.

Enable this functionality will allow users to use their favorite time zone flexibly.

**Comment by davidfowl** [comment]
This doesn't seem feasible. There's no ambient timezone to set in .NET that will make all functionality adapt to the currently set time zone. You need to file an issue on https://github.com/dotnet/runtime, to expose functionality like that before this request is meaninful.

With the culture middleware, we set the current culture and that affects many things in .NET, this wouldn't have the same effect.

**Comment by trannamtrung1st** [comment]
> This doesn't seem feasible. There's no ambient timezone to set in .NET that will make all functionality adapt to the currently set time zone. You need to file an issue on https://github.com/dotnet/runtime, to expose functionality like that before this request is meaninful.
> 
> With the culture middleware, we set the current culture and that affects many things in .NET, this wouldn't have the same effect.

Currently, I store the value of detected time zone to HttpContext.Items. It is just a mean for developer to retrieve the value and will not cause too much side effect. Basically I think it is an extension for the current framework, not mandatory.

**Comment by davidfowl** [comment]
I don't see the value in this middleware, it's something you can do yourself today. Why do you think we should put this in the framework rather than it being something you maintain in a github repository?

**Comment by trannamtrung1st** [comment]
I already resolved it using the above approach so I want to raise the idea here. I just think that it would be more complete if the section **Globalization and localization in ASP.NET Core** includes this because time zone is also an important aspect of i18n applications. 
You could think about this and if it is still not in the plan, it's okay to close this issue.

Many thanks.
