### ISSUE TITLE
Install-able windows service app

### ISSUE THREAD

**Issue by glennc** [dotnet/aspnetcore#31206]
Epic https://github.com/aspnet/AspNetCore/issues/8834

In 3.0 we want to explore how to install a generichost based WindowsServices.

Suggested designs:

1. Self-installable app where you run myapp --install to install it.
2. A new tool that can install an app as a windows service

We would like to expand this to include SystemD daemons as well.

**Comment by BrennanConroy** [comment]
Looks like little to no interested, closing
