### ISSUE TITLE
Blazor WASM with Azure AD auth hangs on 'Completing login' 

### ISSUE THREAD

**Issue by ddobric** [dotnet/aspnetcore#31227]
### Describe the bug
I have implemented the Blazor WASM standalone application with login using OIDC. That works fine as long I use the authority

~~~
https://login.microsoftonline.com/TENANTID
~~~

As next I want to enable the same application for MS Accounts (live.com). I have created the AAD application by enabling all AAD and personal accounts.

![image](https://user-images.githubusercontent.com/1756871/112438479-403f8b00-8d48-11eb-9e4d-e90ac8f12254.png)

In my Blazor application, I changed the authorization endpoint to:
 
~~~
https://login.microsoftonline.com/common/v2.0/
~~~

Unfortunately, the application hangs with "Completing login...", after the user has been successfully authenticated. The endpoint sends the following redirect to the app:

> https://localhost:44316/authentication/login-callback#id_token=eyJ0eXAi***

I have also tried the v1 endpoint. Unfortunately, with the same result.

~~~
https://login.microsoftonline.com/common
~~~

Am I doing something wrong or is this a bug? Unfortunately, when using _https://login.microsoftonline.com/TENANTID_, all works fine, but only members of the tenant can be signed in, Because the requirement is to also support personal accounts, another endpoint must be used. The common-endpoints seem to send the invalid redirects, I guess?

I'm aware of [this ]([https://github.com/dotnet/aspnetcore/issues/27941]) and [this](https://github.com/dotnet/AspNetCore.Docs/issues/20657) issue.

### Application registration in AAD

I use SPA application type (platform)
![image](https://user-images.githubusercontent.com/1756871/112439166-13d83e80-8d49-11eb-8b0d-aa5a6398125d.png)

With enabled ID token and Implicit Flow
![image](https://user-images.githubusercontent.com/1756871/112439236-29e5ff00-8d49-11eb-83f2-da38078db144.png)

I also tried without implicit flow.

#### Blazor version
```
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <UseBlazorWebAssembly>true</UseBlazorWebAssembly>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>
```

**Comment by javiercn** [comment]
@ddobric thanks for contacting us.

If you follow https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-5.0 does this work?

**Comment by ddobric** [comment]
No, it doesn't. This document does not realy describe MS Account. Instead it describes AAD account with a single org.

And yes, it works as described in this document if you setup an Azure AD und login with the account registered in the tenant that owns the app.

If I change the authorize url to the common one, then redirect doesn't work as expected and application hungs in login.

We need a document specific to personal accounts. There is even no specified authorization endpoint that should used.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
