### ISSUE TITLE
Blazor: RefreshDataAsync downloads data but does not show them

### ISSUE THREAD

**Issue by Trapulo** [dotnet/aspnetcore#31231]
### Describe the bug
I have a Virtualize  binded to an ItemsProvider.
When I receive a signalR notification I call RefreshDataAsync()
the Virtualize  downloads a new set of data from the the provider, but does not update the GUI. For example if the list was empty, it downloads new available data but list remains empty

### To Reproduce
 await hubConnection.StartAsync();
                    hubConnection.On<int>("ListChanged", async (ID) =>
                    {
                        await listVirtualizer.RefreshDataAsync();
                    });

### Further technical details
- ASP.NET 5.0

**Comment by gurux-kurumi** [comment]
Hi,

I have struggled with the same thing for two days. It' seems that when RefreshDataAsync is called again UI is updated.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Do you get any errors ? can you share them, if you do?

**Comment by campersau** [comment]
According to the code comment it looks like this behavior is intentional and you need to call `StateHasChanged` manually afterwards. I also ran into this issue some months ago.

https://github.com/dotnet/aspnetcore/blob/a28da74c363454b78fbcf042e1a94dfc6e255e1a/src/Components/Web/src/Virtualization/Virtualize.cs#L110-L113

**Comment by mkArtakMSFT** [comment]
If not, please provide a small repro project hosted in GitHub.

**Comment by Trapulo** [comment]
> 
> 
> According to the code comment it looks like this behavior is intentional and you need to call `StateHasChanged` manually afterwards. I also ran into this issue some months ago.
> 
> https://github.com/dotnet/aspnetcore/blob/a28da74c363454b78fbcf042e1a94dfc6e255e1a/src/Components/Web/src/Virtualization/Virtualize.cs#L110-L113

You pointed to the right way. It works if I force a stateChanged on my component after the refresh

await listVirtualizer.RefreshDataAsync();
this.StateHasChanged();

I cannot understand why RefreshDataAsync does not provide a way to perform a "full refresh", eg. managing a renderOnSuccess parameter.

**Comment by gurux-kurumi** [comment]
Hi,

Thanks for your advice this is now working.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @Trapulo!

**Comment by pranavkm** [comment]
Resolved as part of additional documentation to the Virtualize component.
