### ISSUE TITLE
Middleware lost AsyncLocal state if "next" is awaited

### ISSUE THREAD

**Issue by glucaci** [dotnet/aspnetcore#31233]
### Describe the bug
`Activity` used inside a middleware get lost if `next` `RequestDelegate` is awaited.

### To Reproduce
```csharp
public class Program
{
    public static void Main(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                DiagnosticListener.AllListeners
                    .Subscribe(new HostingDiagnosticSubscriber());

                webBuilder
                    .Configure(app =>
                    {
                        app.Use(next => context =>
                        {
                            _ = new Activity("Middleware 1").Start();
                            return next(context);
                        })
                        .Use(next => async context =>
                        {
                            _ = new Activity("Middleware 2").Start();
                            await next(context);
                        });
                    });
            })
            .Build()
            .Run();
}

public class HostingDiagnosticListener :
    IObserver<KeyValuePair<string, object?>>
{
    public void OnCompleted() { }
    public void OnError(Exception error) { }
    public void OnNext(KeyValuePair<string, object?> value)
    {
        switch (value.Key)
        {
            case "Microsoft.AspNetCore.Hosting.HttpRequestIn.Start":
                // Activity.Current is "Microsoft.AspNetCore.Hosting.HttpRequestIn"
                break;
            case "Microsoft.AspNetCore.Hosting.HttpRequestIn.Stop":
                // Activity.Current should be "Middleware 2" but it is "Middleware 1"
                break;
        }
    }
}

public class HostingDiagnosticSubscriber :
    IObserver<DiagnosticListener>
{
    public void OnCompleted() { }
    public void OnError(Exception error) { }
    public void OnNext(DiagnosticListener value)
    {
        if (value.Name == "Microsoft.AspNetCore")
        {
            value.Subscribe(new HostingDiagnosticListener());
        }
    }
}
```
### Further technical details
- SDK 5.0.104
- ASP.NET Core Runtime 5.0.4
- VS 16.9.0

**Comment by davidfowl** [comment]
This is by design and how async locals work. Modifications do not bleed out of the async method.

**Comment by glucaci** [comment]
Yes, just found the [blog post](https://blog.stephencleary.com/2016/12/eliding-async-await.html) from @StephenCleary and I didn't know that it will only "flow down" and not "up".

So the idea is than, who an `Activity` created on a lower level can be accessed on a higher level? (given the example above)

**Comment by glucaci** [comment]
For me it's now clear that using `Activity.Current` in this case is not possible. From my point of view we can close this but if you want, we can keep it open for Discussions.

**Comment by StephenCleary** [comment]
Activities have a "scope" as described. By the time `Microsoft.AspNetCore.Hosting.HttpRequestIn.Stop` is triggered, the inner scope has already been closed.

You could attach extra data, though, in this case using `HttpContext.Items`, and that may work for what you need. I use a similar technique in `HttpClient`'s pipeline - I have an outer handler that does logging and an inner handler that attaches data from response headers that is then passed "up" to the logging handler. Of course, you need custom code at both ends: to add the data *and* pull it out.
