### ISSUE TITLE
Content-Security-Policy issues with Blazor WASM

### ISSUE THREAD

**Issue by IvanFeric** [dotnet/aspnetcore#31236]
I'm building a Blazor WASM app that's using OpenID Connect for authentication and I started with a built-in template for Blazor WASM with included Individual Accounts authentication type, and checked all of the checkboxes ("Configure for HTTPS", "ASP.NET Core hosted", and "Progressive Web Application").

I've decided to strengthen the security by adding a Content Security Policy. For starters, I took an example you provided in the official documentation (https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy) and pasted in

```
<meta http-equiv="Content-Security-Policy" 
      content="base-uri 'self';
               block-all-mixed-content;
               default-src 'self';
               img-src data: https:;
               object-src 'none';
               script-src https://stackpath.bootstrapcdn.com/ 
                          'self' 
                          'sha256-v8v3RKRPmN4odZ1CWM5gw80QKPCCWMcpNeOmimNL2AA=' 
                          'unsafe-eval';
               style-src https://stackpath.bootstrapcdn.com/
                         'self'
                         'unsafe-inline';
               upgrade-insecure-requests;">
```
Since it's a progressive web app, I also had to add an additional SHA for the service worker file ('sha256-9mThMC8NT3dPbcxJOtXiiwevtWTAPorqkXGKqI388cI=').

However, when I run the app inside the Google Chrome browser, I get a comment inside the console with a message `"Some messages have been moved to the Issues panel."`. When I click on a "View issues" link, I'm getting an error message `"Content Security Policy of your site blocks the use of 'eval' in JavaScript"` with the following details:

> The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
> To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
> If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
> ⚠️ Allowing string evaluation comes at the risk of inline script injection.
> 1 directive
> Source Location		Directive	Status
> blazor.webassembly.js:1	script-src	blocked
> Learn more: Content Security Policy - Eval

This comes as a big surprise to me since there is clearly an `'unsafe-eval'` entry inside the `script-src` directive. If I delete the `'unsafe-eval'`, there are a lot more errors so it does appear to be working but for some reason, it's not applying to blazor.webassembly.js. I also inspected the content of blazor.webassembly.js and there are no evals there (nor any of the mentioned string evaluation function calls mentioned in the Chrome issue description). 

The web app itself appears to be running normally but I'm not sure if that's just an appearance and if Chrome is stopping any underlying code from running that might stop Blazor from running normally. Are there any workarounds to this issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a dupe of #31190
