### ISSUE TITLE
ctx.RequestAborted in a trace surfaces many Dictionary.Resize calls

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/aspnetcore#31240]
Feature collection initializes the inner dictionary without a capacity, after the first insert this would mean it grows to 3 (due to prime based capacity growth). 
https://github.com/dotnet/aspnetcore/blob/1c8da41a1063c9776e559178af16477d78417e55/src/Http/Http.Features/src/FeatureCollection.cs#L74-L78

What we're seeing in traces is that we have a lot of pointless resizing as the framework and users use certain features on every request leaving no capacity to grow without resizing, for us this is:

- HttpRequestIdentifierFeature (when scopes are enabled this gets logged by the framework) 
- RequestServicesFeature (we set our own on every request due to multi-tenancy, but framework would too either way)
- ItemsFeature (there is some state passing here)

Which means we're already at 3 without really doing anything special.

Now when we access ctx.RequestAborted, which we do only on certain requests, this triggers a resize to fit the HttpRequestLifetimeFeature. (this could just as easily have happened by doing auth, which we do on other requests, or accessing session or some other `_features` backed HttpContext properties)

If we can agree on the initial set not doing anything particularly uncommon, would it then make sense to initialize the dictionary with a capacity slightly larger than 3? For Dictionary this would mean it would resolve to capacity 7 which I believe is much more comfortable for most aspnet core uses.

**Comment by davidfowl** [comment]
What server implementation is this?

**Comment by NinoFloris** [comment]
Kestrel with DefaultHttpContext

**Comment by davidfowl** [comment]
Doesn't make sense. Kestrel doesn't use this implementation of the FeatureCollection.

**Comment by NinoFloris** [comment]
I see, let me try and find the right one then. I've been doing github spelunking starting from DefaultHttpContext

**Comment by davidfowl** [comment]
I say this because there's literally no dictionary https://github.com/dotnet/aspnetcore/blob/85a6cb07ae2e1adf5a03740f8d40333b7b8e360c/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.Generated.cs.

There's a list for unknown features but this is a known feature...

**Comment by NinoFloris** [comment]
Ah right it's the codegenned unit, do the custom ones end up in MaybeExtra with an initial capacity of 2?

Either way, going to look again where the Dictionary.Resize is coming from, could it be the Items dictionary itself? (this trace is massive, I get lost in the stack depth) 

I'll update my opening comment if I still think there's anything actionable, otherwise I'll close.

Thanks for the quick replies!

**Comment by NinoFloris** [comment]
Looking at it again from the backtrace I really do see the FeatureCollection pop up, yet I'm certain we use Kestrel, how can this be?

<img width="920" alt="Screenshot 2021-03-25 at 19 05 24" src="https://user-images.githubusercontent.com/4218809/112521743-28462680-8d9d-11eb-85e1-ac36f5f46278.png">

**Comment by davidfowl** [comment]
We just need an API suggestion to allow specifying the capacity instead of hardcoding it.

**Comment by NinoFloris** [comment]
Done https://github.com/dotnet/aspnetcore/issues/31249
