### ISSUE TITLE
New FeatureCollection constructor for initialCapacity

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/aspnetcore#31249]
## Background and Motivation
Some background can be found here, dictionary resizes were fairly visible in traces https://github.com/dotnet/aspnetcore/issues/31240

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http.Features
{
    public class FeatureCollection
    {
+       public FeatureCollection(int initialCapacity);
    }
}
```

## Usage Examples
Initial place this will be used is

``` C#
        public DefaultHttpContext()
            : this(new FeatureCollection(10)) // right here
        {
            Features.Set<IHttpRequestFeature>(new HttpRequestFeature());
            Features.Set<IHttpResponseFeature>(new HttpResponseFeature());
            Features.Set<IHttpResponseBodyFeature>(new StreamResponseBodyFeature(Stream.Null));
            // At least some slots left before resize for storing RequestAborted feature, Services and other such things. 
        }
```

The initial capacity of 10 is just an example, say 5 or 7 would also be fine for me.

## Alternative Designs
This could also be handled through an internal constructor.

## Risks
It can be viewed as api bloat if it provides minimal overall value.

**Comment by davidfowl** [comment]
API looks good to me. We'll review it in API review.

**Comment by mkArtakMSFT** [comment]
Thanks for the proposal, @NinoFloris.
It looks great. We'll mark this as `help-wanted` so community members can handle this too.

**Comment by mareklinka** [comment]
Hello all. This looks rather straight-forward - if it's still open, I'd like to take a crack at it. Is there anything special or important that I should be aware of?

**Comment by davidfowl** [comment]
> Hello all. This looks rather straight-forward - if it's still open, I'd like to take a crack at it. Is there anything special or important that I should be aware of?

Nope, its as straight forward as it seems!

**Comment by davidfowl** [comment]
Assigned to you @mareklinka
