### ISSUE TITLE
ASP.Net Core 3.1 app not starting in IIS (on Azure App Service)

### ISSUE THREAD

**Issue by wasabii** [dotnet/aspnetcore#31243]
### Describe the bug
One of my App Services is failing with an exception on Azure. Long before it hits user code. Started on updating some NuGet packages. Some native IIS stuff inside AspNetCore.Server.IIS is throwing an exception when it gets an invalid HRESULT. What's interesting about this is everytime it happens, the "Version" it lists is different. That tells me there's some sort of memory stuff going on. And the Version is being picked up from some uninitialized memory or something. Maybe. Got me. This is beyond me.

### To Reproduce
I can't.

### Exceptions (if any)Application: w3wp.exe
CoreCLR Version: 4.700.21.11102
.NET Core Version: 3.1.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80004005): Version 154.1 is not a compatible version.
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.Validate(Int32 hr)
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.HttpGetApplicationProperties()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIIS(IWebHostBuilder hostBuilder)

Application: w3wp.exe
CoreCLR Version: 4.700.21.11102
.NET Core Version: 3.1.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80004005): Version 37.2 is not a compatible version.
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.Validate(Int32 hr)

Application: w3wp.exe
CoreCLR Version: 4.700.21.11102
.NET Core Version: 3.1.13
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x80004005): Version 235.1 is not a compatible version.
   at Microsoft.AspNetCore.Server.IIS.NativeMethods.Validate(Int32 hr)
### Further technical details
- ASP.NET Core version: 3.1.13

**Comment by BrennanConroy** [comment]
We need a repro app to be able to investigate further.
