### ISSUE TITLE
Blazorwasm: enable publish-time relinking for non-AOT projects

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/aspnetcore#31256]
This will enable additional size savings, particularly when InvariantGlobalization is setup.

It requires both SDK changes to acquire the workload packs and lifting the condition [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/BlazorManifest/src/WorkloadManifest.targets#L6).

cc: @pranavkm

**Comment by SteveSandersonMS** [comment]
Done
