### ISSUE TITLE
Distributed cache key access

### ISSUE THREAD

**Issue by steveoh** [dotnet/aspnetcore#31264]
I am building a demo of distributed cookie auth with redis and hoping to end up with something where I can see all of the places the same user is logged in. 

![image](https://user-images.githubusercontent.com/325813/112567071-cb9b3980-8da5-11eb-999f-ca3a96161f54.png)

The distributed caching is working but I am unable to retrieve the key that is being used to store that value in a controller method. 

It appears that https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/Session/src/IDistributedSessionStore.cs is the interface that would let me take the HttpContext.Session.Id and find the distributed cache key, but it is marked as internal. Is there a public interface to allow me to find the cache key from the httpcontext somehow so I can use my IDistributedCache object to find the cache entry?

It looks like the middleware does decode the cookie, https://source.dot.net/#Microsoft.AspNetCore.Session/SessionMiddleware.cs,88, maybe that is what I should be doing as well... 

I've tried looking at the ISessionFeature from the httpcontext but that has the same id as the HttpContext.Session.Id.

**Comment by BrennanConroy** [comment]
@Tratcher thoughts on exposing the session id?

**Comment by steveoh** [comment]
@BrennanConroy are you meaning that there currently isn't a way to get the cache key since the session id is exposed but not linked to the cache key?

**Comment by Tratcher** [comment]
Cookie auth and Session are unrelated components and you should not be putting any auth related data into Session. Can you back up and explain your higher level design?

**Comment by steveoh** [comment]
Yes of course @Tratcher. I am not using session at all. I assumed that the httpcontext session id would correspond with the distributed cache key for the auth but that was a mistake.

Ultimately, I am trying to use the distributed cache to list how many places a user is logged in like the photo.

My experimental design is a web app with a cookie session store pointed at a redis cache using the stack exchange library. I've got data protection persisting keys so the auth data can be read by multiple apps or survive a restart/republish. 

Now in a secure controller method, I've been trying to query fo how many other auth sessions the logged in user has. My first thoughts, however poor, were to get the redis key from the logged in user, query redis for their auth ticket, then take some of that information and query the other redis keys to see if there are more. 

That doesn't make perfect sense right now because I probably have all the information I'd need from the logged in user to query the redis cache keys to see if there were more than 1. It feels bad to query every auth record in the cache and decode the ticket to implement such a feature. Maybe this isn't a big deal with redis. I'm not sure yet, I'm still exploring.

**Comment by Tratcher** [comment]
Ah, you're talking about CookieAuth's SessionStore, not HttpContext.Session. No relation 😁. 
https://github.com/dotnet/aspnetcore/blob/e05640cda39b87f3181867967c1efa93e24ed5b2/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L149-L162

Your implementation of ITicketStore would likely need to create a separate redis table that listed all user ids and session ids. You wouldn't be able to do that with IDistributedCache, you'd need to work directly with redis. Your controller could then query that table by user to list their sessions.

I haven't actually worked with redis in years, I'll leave the implementation details to you.

**Comment by steveoh** [comment]
Ok, the I have browsed the code you pasted which leads me to try and decode then read the auth cookie to get the session id claim.

I tried this unsuccessfully and that is when I created the ticket. Is there a simpler way to get the session id claim or would I basically duplicate this code?

**Comment by Tratcher** [comment]
If you're implementing ITicketStore then you already have the session id in there. You'd be querying redis using the user id, not the session id. Where else do you need direct access to the session id?

**Comment by steveoh** [comment]
Right probably no where since the ticket store will generate another table with the data necessary to remove sessions from a controller method.

**Comment by steveoh** [comment]
https://github.com/steveoh/distributed-auth-code-flow this works.
