### ISSUE TITLE
IAuthorizationService is async only, so call callers must be async

### ISSUE THREAD

**Issue by Plasma** [dotnet/aspnetcore#31266]
Hey,

I've hit an issue where some code paths (eg, interceptor code that intercepts non-async code paths) cannot call `AuthorizeAsync` because this would be async over sync.

Is there any guidance on how to approach this, on one hand I could use `_authService.AuthorizeAsync(...).GetAwaiter().GetResult()`, and not use any actual async/await code in the handlers (eg use `Task.FromResult` for everything), but not sure if that avoids deadlock scenarios?

Alternatively, is there any thought on extending `IAuthorizeService` to not require an async-enabled caller?

Thank you

**Comment by davidfowl** [comment]
Where are you calling it from that isn't asynchronous?

**Comment by Plasma** [comment]
Hey David, a few examples:

1. A custom built `MyService` service that has a `DoSomething()` method that happens to be non-async, and so I want to re-validate authorization at that moment. For me to do that, I'd need to make it `async` (and bubble that up)

2. An explicit `IInterceptor` I have between data passing between service method calls, so having a validation between method calls (and those method calls are synchronous).

I'm using `async` in many places (controllers, other services, etc), but as you know not everything necessarily begins its life as non-async nor could be async etc.

Thank you

**Comment by davidfowl** [comment]
Unfortunately, you'll need to make your calls asynchronous to accommodate the async APIs here. As async is viral, this change would mean making many other calls in the chain sync and that's not feasible.

**Comment by blowdart** [comment]
We've never envisaged a synchronous version at all, especially when database calls themselves are usually async. It seems like it would be better to authorize before you go into sync calls, but you would have to manage TOCTOU concerns.

**Comment by Plasma** [comment]
Thanks @davidfowl and @blowdart for your comments. Understood, I'll look to make some changes.

Besides database access though, you can imagine some other non-async service, that just wants to re-validate authorization internally, but for that to happen, it now needs to be async "all the way up", which may not always be possible.

**Comment by blowdart** [comment]
Honestly I can't. 

For authentication AAD is async due to output network calls, Kerberos would potentially be the same. Even JWT validation has async http calls to get the validation keys. 

For authorization you're inside an async controller method at the top of the tree, even if you're using attribute based validation. As authorization itself can make database calls, being async makes it more flexible. If you're calling your service from inside a controller, then going async makes way more sense, rather than making every implementation of the authentication service also support a sync entry point. Most things in asp.net are async now, moving to sync seems like a step back overall.

**Comment by davidfowl** [comment]
One way to work around the limitation is to retrieve the auth information when you're in the async code path and stash it for later

**Comment by blowdart** [comment]
Yes, but be careful of TOCTOU as I mentioned above when it was suggested

**Comment by Plasma** [comment]
Thanks for the discussion -- to provide a bit more context, by using `IInterceptor` I'm trying to protect data objects being passed from one method call to another (by inspecting parameters and return values) as an aggressive authorization flow check.

Some of these method signatures themselves are not async -- eg, imagine a simple "Is this thing null?" method (for a basic example).

But because its not async, my intercept can't run async code either, so it cant call `IAuthorizeService.AuthorizeAsync` to validate the object at that moment.

A few workaround I'm looking into (part one done, just make a sync copy of `IAuthorizeService` for my use -- which is OK to me but not ideal!), the other is waiting for EF Core to support a "post-load entity filter" (not the simple query filter on offer now, but something letting me run complex logic via an auth handler) that would support async, then make this pluggable.

I realise its an edge case, just trying to explain my use case -- thank you for the comments.

**Comment by blowdart** [comment]
That's an interesting use indeed, but seems right on the edge of what folks would do I'm afraid. I'll defer to David here though.
