### ISSUE TITLE
Update Java SignalR client to use RxJava3

### ISSUE THREAD

**Issue by Bludator** [dotnet/aspnetcore#31265]
Java SignalR client still uses [RxJava](https://github.com/ReactiveX/RxJava)2. 

[RxJava](https://github.com/ReactiveX/RxJava)2 reached end-of-life last month so it is beyond time to update to [RxJava](https://github.com/ReactiveX/RxJava)3.

**Comment by BrennanConroy** [comment]
Makes sense, we'll need to update. In the meantime, I believe you can add RxJava3 to your project manually and it'll use that version.
