### ISSUE TITLE
Bad request when passing parameter

### ISSUE THREAD

**Issue by ddobric** [dotnet/aspnetcore#31270]
Have a Blazor  WASM standalone application that has a page receiving a parameter.

`/pagename/param`

Sometimes, parameter is few hundert characters long or it contains URLenxoded values. When some of these happen, the page cannot be opened.

To repro this, create a page with a single parameter [Parameter] and navigate to page by providing in URL the value similar to encoded JWT token. That one is long enough and it contains encoded characters.

Does parameters in the route have some limitations regarding the length and encoding?
Interestingly, when working with authentication, Auth providers typically redirect to the app by passing also very long and url encoded values like token. A good example is authorization.razor. However that one bound the action instead of parameter.
If parameters are limited to handle such requests, what kind of workoround is recommended to handle such requests similar to redirects used during authentication flow.

Thanks.

**Comment by captainsafia** [comment]
@ddobric Can you share a repro of the problem that you are running into?

I tried to reproduce this issue with a parameter that contain 1000 chars and some encoded values and wasn't able to verify the bug.
