### ISSUE TITLE
Add UserStore<TUser> : UserStore<TUser, DbContext, TKey>

### ISSUE THREAD

**Issue by pantonis** [dotnet/aspnetcore#31275]
## Summary

When you want to override UserStore in order to be able to use it with custom ```UnitofWork``` and ```IdentityUser<TKey>``` is used,  there is no way to do it as there is only one constructor signature which defaults to ```UserStore : UserStore<IdentityUser<string>>```. Bear in mind that ```TRole``` is not used so I cannot use that overload

## In scope

A modern SaaS project does include logic that goes beyond TUser (Tenant creation). Usually a tenant and a user have some kind of exclusive relationship therefore they have to be created within a single transaction. Using current implemenation there is no way to do this as you first have to create user and then tenant or vice versa. If something is wrong with either entities creation you have to write manual rollbacks and in my scenario I have also 3-4 entites created when a user is registered which causes a huge mess

**Comment by blowdart** [comment]
Identity is not designed for multi-tenancy, and we have no plans to do so. You could consider using [Orchard Core](https://www.orchardcore.net/)'s implementation of multi-tenancy and see if separate databases work for you. You don't need the full CMS, I believe the multi-tenancy pieces are quite stand alone.

**Comment by pantonis** [comment]
@blowdart The purpose of this design proposal is not to fulfil multitenancy. I just described my scenario. For me it sounds pretty logical to be able to specify TKey as part of the IdentityUser to be able to create custom stores. I mean it seems like a missing constructor overload. I can see that all other overloads exist and it seems to me like a forgotten one, unless I am missing something

**Comment by TanvirArjel** [comment]
@pantonis You are correct. Unfortunately @blowdart even did not try   to understand what you said but proposed a solution out of the context. Pathetic 😥 ASP.NET Core identity has numerous misdesign and issues which needs to be fixed and improved but ASP.NET Core indentity team is not interested and that's why we don't submit any issues anymore regarding ASP.NET Core indentity. If we submit any issues they will say some sporadic words out of the context and then will close issue. Sigh 😥

**Comment by pantonis** [comment]
@blowdart any update after my clarification?

**Comment by blowdart** [comment]
Triage for identity is tomorrow, so it'll be discussed then.

**Comment by HaoK** [comment]
I'm not exactly sure what functionality is being asked for, but the leaf user store classes are basically just customizing the base cases, see https://github.com/dotnet/aspnetcore/blob/main/src/Identity/EntityFrameworkCore/src/UserStore.cs

There should be nothing preventing you from directly customizing one of the base store classes with the proper generic types you want, if you don't want Roles, you can use the https://github.com/dotnet/aspnetcore/blob/main/src/Identity/EntityFrameworkCore/src/UserOnlyStore.cs

**Comment by pantonis** [comment]
@HaoK ''''public class UserOnlyStore<TUser, TContext> : UserOnlyStore<TUser, TContext, TKey>
        where TUser : IdentityUser<TKey>
        where TContext : DbContext''' is much more simplier that what you currently have

**Comment by pantonis** [comment]
@HaoK @blowdart Can you check the latest post I did please? Shouldn't be difficult for you to add this missing overload
