### ISSUE TITLE
Blazor server. Scoped Service created twice outside the @Body. * is bug? *

### ISSUE THREAD

**Issue by mshakurov** [dotnet/aspnetcore#31278]
If Razor Component1 injecting Scoped Service1 is inserted outside the @Body of the LayoutComponent, then Service1 is created two times. Even if you insert 100 such components outside the @Body, two services will be created nevertheless. If Component1, or 100 such components is inserted inside another Razor Component2 inside the @Body, then Service1 is created once. 

**I understand that this is about pre-rendering.**
**But**, in many manuals and tutorials, you suggest putting, for example, the AuthorizeView in the App component, wrapping the RouteView. Next, the RouteView includes a LayoutComponentBase, and you suggest inserting any components and content into the LayoutComponentBase, including those that might inject a service prepared inside the AuthorizeView. But you are not warning that these components, which are outside the @Body fragment, will be re-created, and worst of all, injected scoped services will be re-created too.
Interesting, It turns out that, on the one hand, Blazor Server offers a convenient markup with Many Pages, but as One SPA, i.e. Layout with Menu, Title and any Pages the router can detects. On the other hand, in fact, it turns out that all services injected in components/pages will be created twice if these components/pages are outside @Body fragment.

**Tell me:**
- I just didn't understand the design approach of the "Blazor Server Main Layout" and I **must not** use DI outside @Body?
- Instead, why in the tutorials/manuals you do not warn about such specific behavior of scoped services?
- Or is it just a bug?

Sample MainLayout.razor :

    @*  MainLayout.razor  *@ 
    ...
    @inherits LayoutComponentBase
    ...
    <div class="main">
      <div class="top-row px-4">
        <div>
           <Component1InjectingService1 />
           <Component2InjectingService1 />
     ...
           <Component100InjectingService1 />
        </div>
      </div>
    </div>
    ...
    <div class="content px-4">
      @Body
    </div>

And Component1InjectingService1.razor :

    @*  Component1InjectingService1.razor  *@ 
    ...
    @inject Service1 service1
    ...
    <div>
      @service1.Info
    </div>
    ...

And register Scoped Service1 in Startup.cs:

    @*  Startup.cs  *@ 
    ...
    public void ConfigureServices(IServiceCollection services)
    {
        ...
        services.AddScoped<Service1>();
        ...
    }
    ...

- Tested in 3 separate environments: ASP.NET Core 6.0, 5.0, 3.1, 3,0
- SDK .NET:
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

- Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

- Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

- .NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

- .NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We haven't heard any other reports similar to this. To make sure we focus our time on high priority work, we will move this to `Backlog` and wait for more feedback from the community. If we find out that this is something impacting many others then we'll look into this.

**Comment by mshakurov** [comment]
If that doesn't take you too long, could you suggest some simple, elegant solution to the problem of controlling the re-creation of Scoped Services injected into components outside of @Body?
Thanks in advance!
