### ISSUE TITLE
Get active Blazor page component

### ISSUE THREAD

**Issue by kev160967** [dotnet/aspnetcore#31280]
I'd like to obtain a reference to the component object for the currently displayed page.

I'm writing a menu component with the goal of not allowing the user to navigate away from a page (via the menu) if the active page wishes to block it (for example, if it has uncommitted changes). Before initiating a page navigation my component would like to ask the current page component whether it should allow this or not, and if not then display a message generated by the current page explaining why. To support this my page components can implement an interface that supports the ability to check this state. To make use of this though, I need to be able to make a call through the active page's reference.

I can see a workaround where the page components update a state on the menu component to indicate if navigation should be blocked, but this has more risks (for example, if something causes a page not to release a block). It also feels like the wrong way around.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
It looks like you're looking for a way to cancel navigation. For that we have a different issue planned, which we track as part of #24417.

**Comment by kev160967** [comment]
Thanks Artak, I was aware of the issue you linked, but I was hoping to get something in place for a system I have live at the moment, and (unless I've missed it) there's no release date announced for the changes described in that issue?
