### ISSUE TITLE
SignalR Hub OnDisconnectedAsync is not called when client disconnects ungracefully 

### ISSUE THREAD

**Issue by matthewpetch** [dotnet/aspnetcore#31285]
### Describe the bug

Microsoft.AspNetCore.SignalR.Hub.OnDisconnectedAsync() is not called when client disconnects ungracefully 

### To Reproduce

Run a service with a SignalR Hub

            services.AddSignalR(opt =>
            {
                opt.KeepAliveInterval = System.TimeSpan.FromSeconds(15);
                opt.HandshakeTimeout = System.TimeSpan.FromSeconds(15);
                opt.ClientTimeoutInterval = System.TimeSpan.FromSeconds(30);
                if (!environment.IsDevelopment())
                    opt.EnableDetailedErrors = true;
            });
            
            services.Configure<HubOptions>(options =>
            {
                options.KeepAliveInterval = System.TimeSpan.FromSeconds(15);
                options.HandshakeTimeout = System.TimeSpan.FromSeconds(15);
                options.ClientTimeoutInterval = System.TimeSpan.FromSeconds(30);
                options.MaximumReceiveMessageSize = null;
            });
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<MyHub>("/myHub");
            });
            
            
Then connect on a client and terminate the client application (I'm ending the task via task manager to reproduce consistently) 

I have tried both with and without debugger attached as [this](https://github.com/dotnet/aspnetcore/issues/18879#issuecomment-583474378) comment on another issue #18879 mentions OnDisconnectAsync not being called if the debugger is attached

I've also tried with and without the KeepAliveInterval, HandshakeTimeout, and ClientTimeoutInterval set. I added these because a [stackoverflow comment](https://stackoverflow.com/questions/64141004/signalr-how-to-validate-if-a-connection-id-is-still-active) mentioned needing to set these despite them supposedly having a default value 

### Further technical details
- ASP.NET Core version 3.0, 5.0 (both versions tried)
- Visual Studio 4.8.04084

.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

**Comment by BrennanConroy** [comment]
Can you provide a repro application, there isn't enough info here to figure out if anything is wrong.

**Comment by matthewpetch** [comment]
> Can you provide a repro application, there isn't enough info here to figure out if anything is wrong.

I have been trying to create a repo that reproduces this without success. I've now managed to find the cause of the issue, if the client HubConnection has the Transports set to LongPolling then OnDisconnectAsync is never called in the Hub on the server. 

Is this by design? Is there a workaround?

**Comment by BrennanConroy** [comment]
> the Transports set to LongPolling then OnDisconnectAsync is never called in the Hub on the server.

LongPolling has "implicit" keep alives, which means that an ungraceful disconnect will take ~90 seconds, but `OnDisconnectedAsync` will still be called after that. If you can't provide a repro app, can you at least share Debug logs on the server and client side?
