### ISSUE TITLE
Blazor WebAssembly compiler error after copy and rename

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31282]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssembly-compiler-error-after-/1375366)._

---
[severity:It's more difficult to complete my work]
I have a component that I have copied to a different folder/namespace and then renamed.
Blazor compiler shows error because it detects it is a duplicate, but it isn't because I have renamed it, even though the compiler doesn't pick up the new name after the change.

To make it work I need to close VS, clean and restart VS and rebuild.

See image below.

! [image.png] (https://aka.ms/dc/image?name=B1db6144d347a42d98724271d0d3ac86b637517126495851284_20210319-120408-image.png&tid=1db6144d347a42d98724271d0d3ac86b637517126495851284)

---
#### Feedback Bot on 3/19/2021, 00:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/25/2021, 11:47 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
There's a high chance this is related to: https://github.com/dotnet/aspnetcore/issues/33957

**Comment by NTaylorMullen** [comment]
For the original reporter of this issue, if you edit said file after rename do things return to normal?

**Comment by ryanbrandenburg** [comment]
It seems like the problem is somewhere in `project.razor.json` serialization. The name of the component updates in the project.razor.json of the RCL, but not in the projects which depend on it. When any edit gets made to the non-RCL project project.razor.json gets reserialized and we pick up the new Component name.

I don't see any evidence of accounting for dependent projects in the project.razor.json code, but I'll give it another look tomorrow.
