### ISSUE TITLE
SuppressLinkGeneration defaults to true on MapControllerRoute endpoints

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31293]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SuppressLinkGeneration-defaults-to-true-/1363604)._

---
[severity:It's more difficult to complete my work]
It seems that SuppressLinkGeneration defaults to true on endpoints created with IEndpointRouteBuilder.MapControllerRoute().  

What is recommended available method to change that default from true to false?  So that it is NOT suppressed and so that links from the declared route endpoints can be generated?

---
#### Mila Zhou[MSFT] on 3/9/2021, 10:09 PM: 

<p>Could you please tell us which programming language you are using? Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? What is the actual result and which result do you expect to happen? It would be very helpful if you could provide some screenshots of this problem.</p>
<p>We look forward to hearing from you!</p>

#### Carl Taswell on 3/10/2021, 07:41 AM: 

<p>C# with Net 5 and this function:<br>
<a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.controllerendpointroutebuilderextensions.mapcontrollerroute?view=aspnetcore-5.0">https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.controllerendpointroutebuilderextensions.mapcontrollerroute?view=aspnetcore-5.0</a></p>
<p>When the endpoints generated from calls to MapControllerRoute are examined, they have default metadata with SuppressLinkGeneration set to true.  That means that these routes cannot have links generated  in Razor view files.  And there does NOT appear to be any method call that can be used with MapControllerRoute that supports configuring SuppressLinkGeneration to false.  So please explain how to do that?</p>
<p>Otherwise the endpoints created with convention calls to MapControllerRoute are created with SuppressLinkGeneration true.</p>

#### Feedback Bot on 3/11/2021, 10:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please share more about your scenario and how this is impacting it?

Thanks!
