### ISSUE TITLE
[Blazor] [Razor] File nesting not working properly

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#31291]
Hi,

Please refer to the following file structure:

Component.razor
---Component.razor.cs

I want to split rather large ``Component.razor.cs`` to two (or more) partial classes and be able to see all partial classes after expanding ``Component.razor``.

Component.razor
---Component.razor.cs
---Component.MyPartial_1.razor.cs
---Component.MyPartial_2.razor.cs
---Component.MyPartial_3.razor.cs

After creating ``Component.MyPartial.razor.cs`` file, the built-in "File Nesting" in VS 16.9.0 tool does nothing. If I rename the new file to ``Component.razor.MyPartial.cs``, then the file will be displayed underneath ``Component.razor.cs`` which is not intuitive:

Component.razor
---Component.razor.cs
------Component.MyPartial.razor.cs

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
