### ISSUE TITLE
Consider creating new dictionary type which allocates an array for small capacities instead of an entire dictionary

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31290]
We allocate a lot of dictionaries across ASP.NET Core, which have a non-zero allocation cost to them. An interesting idea would be to see if we could use an array internally for smaller sizes. 

We already do this today in Routing: https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/Routing/RouteValueDictionary.cs. I think we could probably use RouteValueDictionary (or a copy of it) in different places across the stack.

**Comment by jkotalik** [comment]
Confirmed that RouteValueDictionary allocates less bytes by default than a Dictionary (40 bytes vs 66 bytes). @JamesNK thoughts on using RouteValueDictionary in more places where we expect small amounts of values in a dictionary?

**Comment by blowdart** [comment]
Be careful to check it's protected against hash collision attacks if any user data goes near it.

**Comment by halter73** [comment]
Kestrel's IFeatureCollections use a `List<KeyValuePair<Type, object>>? MaybeExtra` which is better than Dictionary for small sets, but those might be a good candidate for this.

**Comment by JamesNK** [comment]
The concept you're interested in with `RouteValueDictionary` is fine - an array backed dictionary for small numbers of values.

The actual `RouteValueDictionary` implementation probably shouldn't be exactly reused because it also supports a dictionary of property values, i.e. `new RouteValueDictionary(new { hello = "world" })`, which most places don't need.

**Comment by JamesNK** [comment]
> Be careful to check it's protected against hash collision attacks if any user data goes near it.

No hashing involved. Keys are matched by looping over all the items in the dictionary. O(n) world.

**Comment by blowdart** [comment]
Ah hence for "very small" collections :)

**Comment by jkotalik** [comment]
> The actual RouteValueDictionary implementation probably shouldn't be exactly reused because it also supports a dictionary of property values, i.e. new RouteValueDictionary(new { hello = "world" }), which most places don't need.

Yeah, I did a quick test with RouteValueDictionary and it seemed to be fine, but agree we should create a new type.
