### ISSUE TITLE
Consider shipping ASP.NET Core analyzers in targeting pack

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#31294]
As we plan on adding new analyzers in 6.0, one of the problems we'll run in to is that these changes would affect all ASP.NET Core apps targeting 3.1 onwards. We could do something special the analyzer to light up the new ones, but it seems like a better strategy to follow from the [in-box source generator design](https://github.com/dotnet/designs/pull/181) recommends and ship this as part of a pack instead. We would freeze the current set of analyzers that ship as part of the SDK to be point in time and use the ones in the pack to target 6.0 and newer apps.

**Comment by dougbu** [comment]
At least for now, assigning to @pranavkm because we (the build v-team) are not likely to drive this product change. We are available to provide guidance as needed.

/cc @mkArtakMSFT

**Comment by pranavkm** [comment]
Closing this as we don't have any plans to change things here at this point.
