### ISSUE TITLE
Formatting breaks code in a .razor file

### ISSUE THREAD

**Issue by mkArtak** [dotnet/aspnetcore#31304]
I have VS 16.10 Preview 2, with experimental Razor editor turned on.
In my project, when I try to format a razor file (a specific one), it adds tabs in the middle of a `foreach` and breaks it:
![Formatting break](https://user-images.githubusercontent.com/7347708/112711560-87cc3100-8e86-11eb-93fb-b75f7cac2e65.gif)

I'm using .NET 6 Preview2 SDK.
I am unable to repro this with another file, but am happy to share any information from VS you may need.
@NTaylorMullen whoever is going to work on this, let them know that they can reach out to me and I will share what's needed.

**Comment by NTaylorMullen** [comment]
@mkArtak validated this was fixed in 16.11 P2. @davidwengier fixed again!

**Comment by mkArtakMSFT** [comment]
Thanks @NTaylorMullen ! I'm indeed am unable to repro this any more. Great work guys :)
