### ISSUE TITLE
Large number of duplicate strings for concurrent websocket connections

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#31305]
Seems like something we could consider interning:

![image](https://user-images.githubusercontent.com/95136/112711553-7be06f00-8e86-11eb-908a-4167239ed677.png)

We could probably eliminate this by making these known headers (though I think we should potentially remove other known headers and replace them with the websocket headers 😄).

cc @benaadams

**Comment by benaadams** [comment]
Should resolve it? https://github.com/dotnet/aspnetcore/pull/31311

It won't get rid of `localhost:5000` though as the `Host` value; that is amortized across many requests and the WebSocket upgrade is just one per connection. Would need a different approach.

Could switch it in the "allowed origins" middleware; so if you specify allowed origins and one matches then it could switch the header value for the string object in the middleware options? 🤔
