### ISSUE TITLE
Blazor CSS Isolation bundle does not include CSS generated during pre-build

### ISSUE THREAD

**Issue by g0tsimid** [dotnet/aspnetcore#31302]
### Describe the bug
In a Blazor Server application, component-isolated CSS files that get updated at build-time do not get reflected in the generated bundle. For example, if you are writing component styles using Sass and have a build task to build your *.razor.scss files into *.razor.css, those changes will not be included in the Project.styles.css bundle the first time you build the project. This is inconsistent with how css changes are handled in the wwwroot folder, where files that you copy to wwwroot during the pre-build step _are_ included in build output.

### To Reproduce
1. Create a new `blazorserver` project. `dotnet new blazorserver`
2. Move NavMenu.razor.css to wwwroot/css/NavMenu.css
3. In the csproj, create a target that runs before the build target to copy NavMenu.css back to NavMenu.razor.css (this simulates other activities like using LibSassBuilder to build NavMenu.razor.scss)
4. Run the project without explicitly building first. NavMenu.razor.css should not exist yet at this stage. ie, `dotnet run`
5. Open https://localhost:5001 and observe that the nav menu isn't displaying correctly, and that no styles related to NavSidebar.razor.css appear in the Project.styles.css file.

The same thing applies if you run `dotnet publish` instead of `dotnet run`; the Project.styles.css will not include any styles from the NavMenu.razor.css.

A full demonstration can be found here: https://github.com/g0tsimid/BlazorCssIsolationBugDemo

### Further technical details
- ASP.NET Core version
5.0
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Microsoft Visual Studio Community 2019 Version 16.9.2

**Comment by javiercn** [comment]
@g0tsimid thanks for contacting us.

You need to make the target that generates the CSS run before `ResolveScopedCssInputs` and follow the convention defined by blazor or create a ScopedCssInput item explicitly with the `RazorComponent` pointing to the razor file it is associated with.

**Comment by g0tsimid** [comment]
Thanks @javiercn, that pointed me in the right direction. There were actually two requirements for getting the ScopedCssInput task to pick up the generated files.

1. The build task had to be run before the ResolveScopedCssInputs target, like you said.
2. The generated files had to be added to the Content or None item groups, since that is what gets passed into the DiscoverDefaultScopedCssItems task.

When using LibSassBuilder to build the project scss files, this looks like:

```xml
  <Target Name="BuildScopedSass" BeforeTargets="ResolveScopedCssInputs" DependsOnTargets="LibSass_Build">
    <ItemGroup>
      <None Remove="**/*.razor.css" />
      <None Include="**/*.razor.css" />
    </ItemGroup>
  </Target>
```
