### ISSUE TITLE
Make MVC Razor runtime-compilation extendable

### ISSUE THREAD

**Issue by chrfin** [dotnet/aspnetcore#31314]
## Summary

At the moment most of the classes used for runtime compilation are internal and it is nearly impossible to extend it without copying many classes to your own project. I would like to adapt some of them to make it easy to extend.

## Motivation and goals

I am creating a system which is able to dynamically load and unload plugins containing MVC controller/views and Razor components. This works fine with a simple custom view-compiler if you do not use runtime compilation. Especially for development, but also for "UI/text quick-fixes" on live systems it would be great to be able to add/change `*.cshtml` files of such plugins and get them runtime-compiled.  

## In scope

With the current `RuntimeViewCompiler` you cannot do the following:

- add dynamically loaded pre-compiled views
- add a file-path to watch for changed views after the compiler is initialized
- unload and reload the same model-types

## Out of scope

The actual logic to solve the two points from above should not be part of this. Just the possibility to add such functionality without the need to copy/change framework classes.

## Risks / unknowns

Opening up some of the classes could create backwards-compatibility issues if such classes are planned to be changed in the future. My proposal for the changes are based on my implementation and maybe I did miss some points to make this useful for everyone or other cases.

## Examples

The following class is an example-implementation of an extended `RuntimeViewCompiler` which is able to solve point 1) & 3) from above. For this it adds pre-compiled views to the precompiled views list with a custom cancelation token to cancel them when the views are unloaded and uses a custom load-context to load the runtime-compiled views to be able to unload them with the plugin:

```
public class PluginViewCompiler : RuntimeViewCompiler
{
	public static PluginViewCompiler Instance { get; private set; }

	private readonly ConcurrentDictionary<AssemblyLoadContext, List<string>> loadedViews = new();
	private readonly ConcurrentDictionary<string, CancellationTokenSource> viewsTokenSources = new();

	public PluginViewCompiler(IFileProvider fileProvider, RazorProjectEngine projectEngine, CSharpCompiler csharpCompiler, IList<CompiledViewDescriptor> precompiledViews, ILogger logger)
		: base(fileProvider, projectEngine, csharpCompiler, precompiledViews, logger)
	{
		Instance = this;
	}

	public void LoadCompiledViews(AssemblyLoadContext context, IRazorCompiledItemProvider itemProvider)
	{
		var cancellationTokenSource = new CancellationTokenSource();
		viewsTokenSources.AddOrUpdate(context.Name, _ => cancellationTokenSource, (_, i) =>
			{
				cancellationTokenSource = i;
				return i;
			});

		foreach (var compiledItem in itemProvider.CompiledItems)
		{
			var compiledView = new CompiledViewDescriptor(compiledItem);
			if (PrecompiledViews.ContainsKey(compiledView.RelativePath))
				continue;

			compiledView.ExpirationTokens = new List<IChangeToken>() {new CancellationChangeToken(cancellationTokenSource.Token)};
			PrecompiledViews.Add(compiledView.RelativePath, compiledView);
		}
	}

	public void UnloadViews(AssemblyLoadContext context)
	{
		var compiledViews = PrecompiledViews.Where(kvp => context.Assemblies.Contains(kvp.Value.Type.Assembly)).ToList();
		foreach (var entry in compiledViews)
			PrecompiledViews.Remove(entry.Key);

		if (viewsTokenSources.TryRemove(context.Name, out var contextSource))
			contextSource.Cancel();

		if (!loadedViews.TryRemove(context, out var views))
			return;

		views.ForEach(i =>
			{
				if (viewsTokenSources.TryRemove(i, out var source))
					source.Cancel();
			});
	}

	protected override IList<IChangeToken> GetExpirationTokens(CompiledViewDescriptor precompiledView)
	{
		var expirationTokens = base.GetExpirationTokens(precompiledView);

		foreach (var token in precompiledView.ExpirationTokens)
			expirationTokens.Add(token);

		return expirationTokens;
	}

	protected override void GetChangeTokensFromImports(IList<IChangeToken> expirationTokens, RazorProjectItem projectItem)
	{
		base.GetChangeTokensFromImports(expirationTokens, projectItem);

		var tokenSource = new CancellationTokenSource();
		expirationTokens.Add(new CancellationChangeToken(tokenSource.Token));
		viewsTokenSources[projectItem.FilePath] = tokenSource;
	}

	protected override Assembly LoadAssembly(RazorCodeDocument codeDocument, MemoryStream assemblyStream, MemoryStream pdbStream)
	{
		string relativePath = codeDocument.Source.RelativePath;
		var pluginPath = codeDocument.Source.FilePath.Substring(0, codeDocument.Source.FilePath.Length - codeDocument.Source.RelativePath.Length);
		var pluginContext = PluginService.Current.GetContext(pluginPath.Split('\\', '/').Last());
		var assembly = (pluginContext ?? AssemblyLoadContext.Default).LoadFromStream(assemblyStream, pdbStream);
		if (pluginContext != null)
		{
			loadedViews.AddOrUpdate(pluginContext, _ => new List<string>() {relativePath}, (_, l) =>
				{
					if (!l.Contains(relativePath))
						l.Add(relativePath);
					return l;
				});
		}

		return assembly;
	}
}
```
This compiler must be loaded via a custom `IViewCompilerProvider` which is easy to implement.

And the following is an extension of the `RuntimeCompilationFileProvider` class to be able to add new file-paths after the compiler is initialized to solve point 2) by supplying an `IFileProvider` which can be altered:

```
public class PluginFileProvider : RuntimeCompilationFileProvider
{
	public PluginFileProvider(IFileProvider fileProvider, IOptions<MvcRazorRuntimeCompilationOptions options) : base(options)
	{
		FileProvider = fileProvider;
	}

	public override IFileProvider FileProvider { get; }
}
```
This class must be registered with `services.AddSingleton<RuntimeCompilationFileProvider, PluginFileProvider>();` before the runtime compilation is initialized as it is then picked up instead of the base class.

**Comment by pranavkm** [comment]
At this point we think copying the types in to your application is best way forward. Making the implementation details of MVC public makes it incredibly difficult for us to change or evolve these types. As such, we prefer not making them public.

**Comment by chrfin** [comment]
@pranavkm  Thanks for the quick feedback. I fully understand and already suspected that as can be seen by my note under "**Risks / unknowns**".

Would you be open to a solution along the line of introducing two simple public interfaces to make it possible to

1.  provide a custom `RuntimeCompilationFileProvider`
2.  manually load the generated assemblies

(Please see my second pull-request for an example)

This would limit the increased public surface heavily, but still would enable all the possibilities by wrapping the `IViewCompiler ` to supply pre-compiled views via the wrapper and only call the "original" view-compiler for other views, but also let the runtime-compiler be able to find files in added locations and not load all compiled assemblies in the main load-context.

My goal is to avoid copying duplicated files from the official repo to my own code-base because these files will get out-of-date with future updates of the framework/packages.

**Comment by pranavkm** [comment]
Apologies for the delay in getting back, I missed your most recent comment. 

1. You should be able to configure arbitrary file providers using: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Razor.RuntimeCompilation/src/MvcRazorRuntimeCompilationOptions.cs#L23. I'm not sure why a new API is needed. What does this do?
2. If the intent is to supply an alternate source of views, you could consider implementing an `IViewEngine`. It has ordering, the first one that discovers a view wins. 

I'm hesitant to expose what amounts to internal implementation details without a very strong need for it.

**Comment by chrfin** [comment]
@pranavkm Thanks again for looking into this:

@1) The problem with adding the file provider to the `MvcRazorRuntimeCompilationOptions` is that they need to be defined at startup, because the `RuntimeCompilationFileProvider` copies the list from the options on first call: [https://github.com/chrfin/aspnetcore/blob/main/src/Mvc/Mvc.Razor.RuntimeCompilation/src/RuntimeCompilationFileProvider.cs#L31.](https://github.com/chrfin/aspnetcore/blob/main/src/Mvc/Mvc.Razor.RuntimeCompilation/src/RuntimeCompilationFileProvider.cs#L31.) My idea of the interface is to be able to supply a different provider which does not have this requirement without the need to change or open up the current implementation. An alternative would be to extend the current provider to be able to either detect changes in the options or have some way of triggering a re-creation of the underlying composite-provider.

@2) A custom `IViewEngine` solves the problem of using precompiled views, but for runtime-complied views it would prevent unloading as the current runtime-compiler loads all compiled views in the default load-context. So, a plugin with custom runtime compiled views can't be unloaded anymore.

**Comment by aloksharma1** [comment]
I dont know if my issue is related to this, but for a modular application where i am defining views from custom file providers like Database or Embedded source. Everything works fine until the related modules are directly referenced with Main project Otherwise i get the following error InvalidOperationException: Cannot find compilation library location for package 'MyApp.Plugin' [Stack Trace Reducted].

I traced this using debugging, the result was if the plugin assembly have local views & layouts it serves fine, otherwise its breaking if:

1. The common layouts are defined in a RCL library
2. Views Coming From DB or Different Custom Provider
3. Individual modules or Host module with direct project reference runs without issues from same code.

amusingly these views are called ok (as i put a lots of logs code to emit response on console) , but instead of rendering these final Views the ViewEngine never stops searching for more. 
Here is a small gist of assembly loader code:

```
 // This loads MVC application parts from plugin assemblies
            var partFactory = ApplicationPartFactory.GetApplicationPartFactory(pluginAssembly);
            foreach (var part in partFactory.GetApplicationParts(pluginAssembly))
            {
                mvcBuilder.PartManager.ApplicationParts.Add(part);
            }

            // This piece finds and loads related parts, such as MvcAppPlugin1.Views.dll.
            var relatedAssembliesAttrs = pluginAssembly.GetCustomAttributes<RelatedAssemblyAttribute>();
            foreach (var attr in relatedAssembliesAttrs)
            {
                var assembly = pluginLoader.LoadAssembly(attr.AssemblyFileName);
                partFactory = ApplicationPartFactory.GetApplicationPartFactory(assembly);
                foreach (var part in partFactory.GetApplicationParts(assembly))
                {
                    mvcBuilder.PartManager.ApplicationParts.Add(part);
                }
                foreach (var view in CompiledRazorAssemblyApplicationPartFactory.GetDefaultApplicationParts(assembly))
                {
                    mvcBuilder.ConfigureApplicationPartManager(apm => apm.ApplicationParts.Add(view));
                }
                
            }
```
            
        `public static void AddCompiledViews(this IServiceCollection serviceCollection, IMvcBuilder mvcBuilder)
        {
            mvcBuilder.AddRazorOptions(o =>
            {
                o.ViewLocationExpanders.Add(new ThemeableViewLocationExpander());
            });
            var PhysicalFileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
            var dBPageProvider= new DBPageProvider(serviceCollection.BuildServiceProvider());
            var dBCustomViewProvider=new DBCustomViewProvider(serviceCollection.BuildServiceProvider());
            var dBViewModuleProvider=new DBViewModuleProvider(serviceCollection.BuildServiceProvider());
            var _CompositeFileProvider = new CompositeFileProvider(PhysicalFileProvider, dBPageProvider, dBCustomViewProvider, dBViewModuleProvider);
            //serviceCollection.AddSingleton<IFileProvider>(_CompositeFileProvider);
            mvcBuilder.AddRazorRuntimeCompilation(options =>
            {
                options.FileProviders.Clear();
                options.FileProviders.Add(_CompositeFileProvider);
                ReflectionHelpers.GetAssemblyByInterface<ICustomViews>()?.ForEach(views =>
                {
                    options.FileProviders.Add(new EmbeddedFileProvider(views.Assembly));
                    //options.AdditionalReferencePaths.Add(views.Assembly.Location);
                });
                //foreach (var dir in Directory.GetDirectories(Path.Combine(AppContext.BaseDirectory, "plugins")))
                //{
                //    //options.FileProviders.Add(new PhysicalFileProvider(dir));
                //    var pluginFile = Path.Combine(dir, Path.GetFileName(dir) + ".dll");
                //    options.AdditionalReferencePaths.Add(pluginFile);
                //}
                
            });
        }`    

Here i tried everything from providing additional reference paths to what not, Nothing Works. This completely beats up the concept of modularity, as now my only option is to use all modules in Host Module as reference project.

So i Think its either the issue with viewengine or how the razor runtime compiler is handling stuff (also why is it trying to handle already compiled views in RCL?).

**Comment by chrfin** [comment]
> So i Think its either the issue with viewengine or how the razor runtime compiler is handling stuff

@aloksharma1: Does everything work if you are not using runtime compilation? That's the easiest way to narrow down, what is causing your problems...

**Comment by aloksharma1** [comment]
@chrfin yea in both cases without runtime compilation or when using the individual module (not loaded through assembly load context) the app runs fine and everything works. the problem is i cant do without runtime compilation as i need views from db & embebdded resources.
otherwise its as i explained in above case, the views are found but viewengine just doesnt stop, if you want full stacktrace its here:

An unhandled exception occurred while processing the request.
```
InvalidOperationException: Cannot find compilation library location for package 'MyApp.PluginXXX'
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List<string> assemblies)
===========
InvalidOperationException: Cannot find compilation library location for package 'MyApp.PluginXXX'
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List<string> assemblies)
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPartExtensions+<>c.<GetReferencePaths>b__0_0(CompilationLibrary library)
System.Linq.Enumerable+SelectManySingleSelectorIterator<TSource, TResult>.MoveNext()
System.Collections.Generic.List<T>.InsertRange(int index, IEnumerable<T> collection)
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.GetReferencePaths()
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.GetCompilationReferences()
System.Threading.LazyInitializer.EnsureInitializedCore<T>(ref T target, ref bool initialized, ref object syncLock, Func<T> valueFactory)
System.Threading.LazyInitializer.EnsureInitialized<T>(ref T target, ref bool initialized, ref object syncLock, Func<T> valueFactory)
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.get_CompilationReferences()
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.LazyMetadataReferenceFeature.get_References()
Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(string relativePath)
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(string normalizedPath)
Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(string relativePath)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet<IChangeToken> expirationTokens, string relativePath, bool isMainPage)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(string executingFilePath, string pagePath, bool isMainPage)
Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetPage(string executingFilePath, string pagePath)
Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, string executingFilePath, string layoutPath)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
MyApp.Services.Middleware.ValidateAntiForgeryTokenMiddleware.Invoke(HttpContext context) in ValidateAntiForgeryTokenMiddleware.cs
+
            await _next(context);
MyApp.Services.Middleware.CustomAuthMiddleware.InvokeAsync(HttpContext httpContext) in CustomAuthMiddleware.cs
+
            await _next(httpContext);
MyApp.Services.Middleware.SystemFeaturesMiddleware.InvokeAsync(HttpContext httpContext, TenantFeatures TenantFeatureMap, IHttpContextAccessor httpContextAccessor) in TenantFeaturesMiddleware.cs
+
            await _next(httpContext);
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
MyApp.Services.Middleware.ActiveSitesMiddleWare.InvokeAsync(HttpContext httpContext, ActiveSites ActiveSitesMap, IHttpContextAccessor httpContextAccessor) in ActiveSitesMiddleWare.cs
+
            await _next(httpContext);
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

As you can see here :
```
**Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)**
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
**Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)**
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
**Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)**
```

The views are found, hit and executed but **ViewEngine** is not just stopping there, and doing god knows what. this doesnt happen if i do a direct project reference but that kills the whole concept of modularity.

**Comment by aloksharma1** [comment]
@chrfin if your solution solves this , can you create a minimal repo or if you want to look into mine let me know i will put a repo online.
thanks for the help

**Comment by chrfin** [comment]
@aloksharma1 See my initial post and first/closed pull-request for my implementation...

**Comment by aloksharma1** [comment]
@chrfin i tried copying your code, its missing a lot of references i am unable to resolve them.

**Comment by chrfin** [comment]
@aloksharma1 You need to add them from the original repo here

**Comment by chrfin** [comment]
@aloksharma1 No, not my repo, THIS repo here, the original aspnetcore one has all the files needed - you need to add them to your project as most of them are internal...

**Comment by aloksharma1** [comment]
@chrfin  oh understood, this will take a lots of time will check on sunday how it goes.

**Comment by chrfin** [comment]
@aloksharma1 It's straight forward as you just search in this repo for each missing type and then add that file. Should be doable in under an hour for all needed files...

**Comment by aloksharma1** [comment]
@chrfin what if we write a customviewengine will that not solve this issue? asking after checking this SO post here [click here](https://stackoverflow.com/questions/48830519/render-view-to-string-caching-issue)
