### ISSUE TITLE
HTTPSysServer does not use LoggerMessage.Define

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#31313]
### Describe the bug

`LoggerMessage.Define` is the preferred approach to logging as it saves re-parsing format strings and doing dictionary lookups (and potential allocations if the cache isn't full). We should update the log calls to use it.

cc @sebastienros

**Comment by martincostello** [comment]
Happy to pick this up if you've not already started on it.

**Comment by davidfowl** [comment]
Sounds good. Are you aware of the latest pattern we've been using? It's a nested static Log class with static methods that do logging. If the class is big enough we make a partial class and put the log methods in there m. If that's not clear, take a look at SignalR

**Comment by martincostello** [comment]
I took a look at the repo and saw that there's a class called `LoggingExtensions` ([example](https://github.com/dotnet/aspnetcore/blob/155f402f759f21a3676faff2469665f8cd99f6cb/src/Security/Authentication/OpenIdConnect/src/LoggingExtensions.cs#L8)) and then the messages are defined in there.

If you're moving to nested per-class instead I'll do it that way instead 👍

**Comment by davidfowl** [comment]
E.g. https://github.com/dotnet/aspnetcore/blob/155f402f759f21a3676faff2469665f8cd99f6cb/src/Servers/IIS/IIS/src/Core/IISHttpContext.Log.cs#L12

https://github.com/dotnet/aspnetcore/blob/46359cd0a28f551d4021c9c9823752b049eaec79/src/SignalR/clients/csharp/Http.Connections.Client/src/Internal/SendUtils.cs#L112

**Comment by davidfowl** [comment]
Assigned the issue to you @martincostello

**Comment by davidfowl** [comment]
Thanks!
