### ISSUE TITLE
_Imports.razor doesn't work

### ISSUE THREAD

**Issue by Duke4848** [dotnet/aspnetcore#31328]
### Describe the bug
All usings in _Imports.razor are unused, I need to add usings in the razor files instead, also even the app template in VS just added the usings to the FetchData.razor for the WeatherForecast demo page cause _Imports.razor doesn't work(It also automatically created the _Imorts.razor that is broken)..

### To Reproduce
Create Blazor Web Assembly app and open the _Imports.razor file.

### Exceptions
Error	CS0118	'Person' is a namespace but is used like a type

### Further technical details
- ASP.NET Core 5.0
- WebAssembly App

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The error you're referring to above is a valid error indicating a problem in your own code.
However, there is a separate issue you're pointing out here regarding the `using`-s in _Imports.razor which we're aware of. That  improper colorization is because the tooling in VS is confused but the app is buildable properly. We're going to address it in the upcoming release of VS.

**Comment by Duke4848** [comment]
It's not problem with my code. I wrote that it's the state out of the box created by Blazor WebAssembly template. The imports don't work and the template it adds usings in the razor components file itself like Imports.razor wouldn't exist in the first place.

**Comment by Duke4848** [comment]
Can somebody help, out the box _Imports.razor doesn't WORK!

**Comment by Duke4848** [comment]
> Thanks for contacting us. The error you're referring to above is a valid error indicating a problem in your own code.
> However, there is a separate issue you're pointing out here regarding the `using`-s in _Imports.razor which we're aware of. That improper colorization is because the tooling in VS is confused but the app is buildable properly. We're going to address it in the upcoming release of VS.

It's not problem with my code. I wrote that it's the state out of the box created by Blazor WebAssembly template. The imports don't work and the template it adds usings in the razor components file itself like Imports.razor wouldn't exist in the first place.

In other words the FetchData.razor for WeatherForecast from template has using in it as well the same using is in the Imports.razor out of the box in fresh project.

**Comment by Duke4848** [comment]
I checked a project downloaded from Github: https://github.com/robalexclark/BlazorTopMenu/tree/master/Blazor-Top-Menu it's server project, the _Imports doesn't work too.

Microsoft Visual Studio Community 2019
Version 16.9.2
Microsoft Visual Studio Community 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.688.6828
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.688.6828
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.688.6828
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IncrediBuild Build Acceleration   1.5.0.13
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Linux Core Dump Debugging   1.0.9.31112
Enables debugging of Linux core dumps.

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.31112
Visual C++ for Linux Development

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes
