### ISSUE TITLE
System.Security.Cryptography APIs not supported on Blazor WebAssembly. Please fix it.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#31339]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly

Application can not work without aes

**Comment by Xyncgas** [comment]
I am begging you to fix it

**Comment by davidfowl** [comment]
See https://github.com/dotnet/runtime/issues/44996 and https://github.com/dotnet/runtime/issues/40074
