### ISSUE TITLE
[blazor webassembly] HttpClient can not send a httpget request with a request body 

### ISSUE THREAD

**Issue by futugyou** [dotnet/aspnetcore#31335]
Code like this:
```
var body = new { name = "testdata" };
HttpRequestMessage httpRequest = new HttpRequestMessage
{
    Content = new StringContent(JsonSerializer.Serialize(body)),
    Method = HttpMethod.Get,
    RequestUri = new Uri("someuri")
};
httpRequest.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
var httpResponseMessage = await httpclient.SendAsync(httpRequest);
var somestring = await httpResponseMessage.Content.ReadAsStringAsync();
```

This code can works  normally in [Blazor Server App] model, 
but it will throw an exception in [Blazor WebAssembly App] model.

### Exceptions
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

How can I send a HttpGet Request with a HtppContent in WASM model?

### Further technical details
- ASP.NET Core version
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
  vs2019 enterprise preview, version 16.10.0 preview 1.0

**Comment by blowdart** [comment]
This is one of those places where the RFC (7231) lets us down, there's no definition of what should happen to a GET request with a body. Some servers allow it, some services (especially proxies) don't. JavaScript and browsers don't allow it, and that's what you're up against, the server-side libraries do. There's nothing blazor clientside can do here, as it's beholden to the browser implementation.
