### ISSUE TITLE
Static logging delegates nested inside generic types

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#31340]
Static logging delegates will allocate a new copy for each generic type.

See https://github.com/dotnet/aspnetcore/pull/31333#discussion_r602938029

Should audit for all usages of static logging delegates to see if there are other places they are nested in generic types.

Before:
```cs
// RequestContext.Log.cs
internal sealed partial class RequestContext<TContext>
{
    private static class Log { }
}
```

After:
```cs
// RequestContext.Log.cs
internal static class RequestContext
{
    private static class Log { }
}
```

Edit: That won't work because Log will be private. How about `internal static class RequestContextLog` with no nested Log type.

**Comment by andrzejpindor** [comment]
Happy to pick this up - in #31345 I've already refactored `RequestContext<T>` but I can also check other places where situation may be similar.

**Comment by martincostello** [comment]
Other than the two already mentioned in #31333, I also found these two which I can fix up at the same time:

https://github.com/dotnet/aspnetcore/blob/c0d17cfeb527127c1b5e300fbe466c6a2af55b72/src/SignalR/server/Core/src/HubConnectionHandler.cs#L23

https://github.com/dotnet/aspnetcore/blob/c0d17cfeb527127c1b5e300fbe466c6a2af55b72/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.Log.cs#L11-L13

**Comment by martincostello** [comment]
Oh - I see you've already done it in #31345 - I was already in the middle of doing it from this comment https://github.com/dotnet/aspnetcore/pull/31333#discussion_r602955223, but happy for you to do it instead.

**Comment by andrzejpindor** [comment]
I can also cover the two cases mentioned by you and scan project for similar problems. I'll wait to become an assignee to this issue to continue work ;)

**Comment by martincostello** [comment]
I did a search in VS Code across the whole ASP.NET Core solution for `private static class Log` and those were the only other two I could find that were inside a generic type.

I hadn't started on changing those two yet, so feel free to make the change yourself 🙂

**Comment by jkotalik** [comment]
Feel free to pick up the ones in SignalR as well.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/31364
