### ISSUE TITLE
Update behavior in Rolemanager SetRoleNameAsync

### ISSUE THREAD

**Issue by pocki** [dotnet/aspnetcore#31347]
### Describe the bug
In Identity Rolemanager all data changing methods do a update on store/database (with UpdateRoleAsync) except SetRoleNameAsync

Is this the expected behavior?

SetRoleNameAsync always returns IdentiyResult.Success instead of the result of UpdateRoleAsync.

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Identity/Extensions.Core/src/RoleManager.cs#L293

### To Reproduce
Change a Rolename with the method SetRoleNameAsync. 
New rolename gets written to database only after UpdateRoleAsync

For example AddClaimAsync (or CreateAsync) updates the store/database.

### Exceptions (if any)
none

### Further technical details
- ASP.NET Core 5.0
 

>  dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.201
 Commit:    a09bd5c86c

> Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

> Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

> .NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

**Comment by blowdart** [comment]
@HaoK Is this expected?

**Comment by HaoK** [comment]
Yes this is equivalent to `role.Name = "foo"`, which does not update the store, it just updates the poco.  You still have to call `UpdateAsync()`.  Its somewhat confusing but its always been that way.

**Comment by pocki** [comment]
Thanks for the answers. 
SetRoleNameAsync also has the call `UpdateNormalizedRoleNameAsync(role);` which is also in `UpdateAsync()`. So it's not the exact the same as `role.Name = "foo"` but at the end there are. So it's a little bit confusing.
