### ISSUE TITLE
Blazor bind to document mouseup event dynamically

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#31355]
I'm basically trying to reproduce this js code in blazor:
```
btn1.on('mousedown', function(){
    console.log('start');
    $(document).one('mouseup', function(){
       console.log('stop');
    });
});
```
Imagine that you do `mousedown `on the button and keep the mouse button down move it outside the button and after do `mouseup`.
(you may or may not move the cursor outside of the button but I need to detect the `mouseup `regardless).
**is this possible without js interop ?**

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

/cc @SteveSandersonMS, @danroth27

**Comment by omuleanu** [comment]
basically a numeric textbox where you have an up and down button, 
if you click and hold on the up button, even if you move the cursor outside the button while still holding mousedown the value of textbox will keep incrementing, and I need to know when the mouseup occurs in order to stop the timer (setInterval), that's why I need to bind to document.

you can actually try it [here](https://demo.aspnetawesome.com/TextBoxDemo) (click an up/down button hold and move the cursor)
so I wanted to make sure that this is only possible with js interop and blazor can't do that yet.
