### ISSUE TITLE
F7 does not properly toggle between a razor file and a razor.cs file of the same class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31368]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F7-does-not-properly-toggle-between-a-ra/1383426)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.9.2]
Create a razor component xyz.razor & a backing cs file of xyz.razor.cs

F7 while in the window of xyz.razor.cs moves you to a xyz.razor; F7 in xyz.razor does nothing.

This occurs in VS 2019 16.10 P1, reverting to VS 2019 16.9.2 'fixes' the issue.

---
#### Feedback Bot on 3/29/2021, 02:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Totally valid feature gap in the new Razor editor

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/aspnetcore/issues/33794
