### ISSUE TITLE
No colorization for Blazor component

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31367]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-colorization-for-Blazor-component/1380881)._

---
Clone and open https://github.com/shirhatti/trivia in VS. Open TriviaClient/Pages/PlayTrivia.razor. The QuesitonComponent tag isn't colored correctly as a Blazor component.

---
#### Feedback Bot on 3/25/2021, 00:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Investigated and LSP platform issue.
