### ISSUE TITLE
Hot reload not enabled if dotnet CLI initialized with arguments

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#31365]
I want to be able to run `dotnet watch run --urls="https://localhost:7005"` to start my application server at a specific port and have hot reload enabled.

However, hot reload is not enabled if `dotnet watch` is invoked with non-default parameters.

**Comment by rabberbock** [comment]
We are using pathbase in our blazor development and need to pass it in as part of the dotnet command. Are there any workarounds for this at the moment?

**Comment by maloo** [comment]
Any progress on this? It is kind of sad that you have to hard code any app parameters in the app to use dotnet watch. Why not just forward parameters after -- to the app as with dotnet run.

**Comment by christiansparre** [comment]
That's a few hours wasted for me before I found this issue... major pain. We se a few env vars in launchSettings.json for local development and `dotnet watch run` did not select a launch profile (I'm pretty sure it used to do that!) so tried using --launch-profile flag and then hot reload died 🤦‍♂️!

Resorted to a .ps1 file that sets the env vars before `dotnet watch run` and then running that.

Hope you can get this fixed soon!

**Comment by ionoy** [comment]
Any news on this?

**Comment by kurtcodemander** [comment]
Same here. I wasted hours before finding this issue. I wanted to select a launch profile with --launch-profile argument or using --urls and hot reload died :(

**Comment by ZachIsAGardner** [comment]
I am having the same issue with running a MonoGame game :(

**Comment by mkArtakMSFT** [comment]
@tmat leaving this up to you to prioritize.

**Comment by Bidthedog** [comment]
Chiming in as I'm also experiencing this issue, and it's causing devs to have to wait for a 2-minute build time + ~30-60 seconds to navigate back to the relevant section in the app, for every change they make. Not very productive, as you might imagine. We run various other dev watchers too, which we don't want the VS build to handle in dev mode (webpack etc).

.Net 6 with SDK 6.0.8

I'm using this command:

`dotnet watch run --no-restore --launch-profile service-hosts -v n -c Debug-CustomerName`

With the following launch profile:

```
        "service-hosts": {
            "commandName": "Project",
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "launchBrowser": false,
            "dotnetRunMessages": "true",
            "applicationUrl": "https://localhost:12345",
            "sslPort": 12345
        }
```

And the following env variables:

```
$Env:ASPNETCORE_ENVIRONMENT = $dotNetEnv;
$Env:ASPNETCORE_URLS = "https://localhost:$($app.port)";
$Env:DOTNET_WATCH_SUPPRESS_EMOJIS = "true";
```

**Comment by wocar** [comment]
bump

**Comment by marcindruzgala** [comment]
Is there any workaround for this issue?
