### ISSUE TITLE
App restarts after fixing compilation error instead of doing a hot reload

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#31372]
Repro steps:
- Run a Blazor Server app using `dotnet watch`
- Create a compilation error and save (ex remove a semicolon)
- After the error message appears in the browser, fix the compilation error and save.

Expected result:
- Successful hot reload of new changes if any, or the app resumes as it was.

Actual result:
- The app restarts

@pranavkm

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/dotnet/sdk/pull/16600.
