### ISSUE TITLE
Refactor inefficient WebSocket handshake

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#31373]
> This HandshakeHelpers class is a relic of an outdated design. Can you try simplifying this code by merging this method into the UpgradeHandshake class?
> 
> You could remove these allocations and query the header collection directly:
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Middleware/WebSockets/src/WebSocketMiddleware.cs#L121-L128
>
> NeededHeaders can also be removed.

https://github.com/dotnet/aspnetcore/pull/31311#discussion_r603602893

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/aspnetcore/pull/31506
