### ISSUE TITLE
Move RequestDelegateFactory out of Microsoft.AspNetCore.Http.Extensions

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#31376]
`RequestDelegateFactory` is currently in the Microsoft.AspNetCore.Http.Extensions assembly because it calls into `WriteAsJsonAsync` and `ReadFromJsonAsync`. We could just copy the very straightforward implementation to a lower-level assembly like Microsoft.AspNetCore.Http or maybe even Microsoft.AspNetCore.Http.Abstractions unless we want to support that assembly's [JsonOptions](https://github.com/dotnet/aspnetcore/blob/9e150eb5f3565f0a37f3321c6f0b5012cd44b7af/src/Http/Http.Extensions/src/JsonOptions.cs) (not to be confused with MVC's [JsonOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/JsonOptions.cs)).

Microsoft.AspNetCore.Http.Extensions is already pretty lightweight, so I'm not sure it's worth it to remove features just to get it one layer deeper in the dependency chain. I opened this issue to start a discussion since I forgot to bring this up in API review 😄. @davidfowl

**Comment by BrennanConroy** [comment]
We aren't doing anything here.
