### ISSUE TITLE
WebHostBuilderExtensions Configure can result in HostingStartupAssemblies being run twice

### ISSUE THREAD

**Issue by k-s-s** [dotnet/aspnetcore#31382]
## Background
I am using IHostingStartup within my package library as it is used by external users to create the web host, targets NET 4.6 and NET Core 3.1. I set the builder setting HostingStartupAssembliesKey to package library assembly **FullName**
I have added a feature to add use an instanced startup class instead of using the normal UseStartup. It is a custom interface, not Microsoft.AspNetCore.Hosting.IStartup
The intention is for testing, to make an easier way of testing different services, rather than separate startup classes.
## Bug
1. When using the Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.Configure method (I add the method of the instanced startup), the extension method sets WebHostBuilder setting ApplicationKey to startup assembly. This was not correct as it was setting to the package library, using assembly **Name**
`public static IWebHostBuilder Configure(this IWebHostBuilder hostBuilder, Action<WebHostBuilderContext, IApplicationBuilder> configureApp)
`
2. When I do host.Build(), the method:
`private IServiceCollection BuildCommonServices(out AggregationException hostingStartupErrors)`
create WebHostOptions, which registers 2x hosting startup assemblies because of **Name** and **FullName**

### To Reproduce
1. Use IHostingStartup, using assembly **FullName**
2. Use WebHostBuilder.Configure 
3. Run WebHost.Build()

### Exceptions (if any)
I found the issue that Swashbuckle raised an exception that a document was already registered.

### Further technical details
- NET 4.6.1, NET Core 3.1

**Comment by davidfowl** [comment]
@k-s-s do you have a sample application?

**Comment by davidfowl** [comment]
Trying to interpret what you put in the issue, this is what I came up with so far. I know I'm missing something 😄 .

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace WebApplication50
{
    public class HostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseSetting(WebHostDefaults.HostingStartupAssembliesKey, typeof(Program).Assembly.FullName)
                              .Configure(new Startup().Configure);
                });
    }
}
```

**Comment by davidfowl** [comment]
@Tratcher should we back port this?

**Comment by Tratcher** [comment]
> @Tratcher should we back port this?

Why? This one report doesn't seem to justify that.

**Comment by davidfowl** [comment]
It's not about the number of reports, it's about the potential impact, and re-reading this issue again I don't think its common to set a different assembly name like this.
